### ISSUE TITLE
`cargo why <crate>`

### ISSUE THREAD

**Issue by homersimpsons** [rust-lang/cargo#10006]
### Problem

It is hard to know `why` a specific crate is required (and why it has a specific version).

### Proposed Solution

There could be a sub command named `why` that could display the constraints applied to a crate and the dependency tree linked to it in order to understand why a specific crate is required.

Composer (PHP's package manager) exposes such sub command: https://getcomposer.org/doc/03-cli.md#depends-why-

### Notes

This issue should be flagged with A-new-subcommand I guess.

A "similar" issue exists https://github.com/rust-lang/cargo/issues/1211 but it does not have the same intent

**Comment by weihanglo** [comment]
[`cargo-tree`](https://doc.rust-lang.org/cargo/commands/cargo-tree.html) covers some usages here. For example. run `cargo tree -i curl` shows the reversed dependency tree:

```console
curl v0.4.40
├── cargo v0.59.0 (/dev/cargo)
├── crates-io v0.33.0 (/dev/cargo/crates/crates-io)
│   └── cargo v0.59.0 (/dev/cargo)
└── git2-curl v0.14.1
    └── cargo v0.59.0 (/dev/cargo)
```

The tree command also supports showing enabled features for dependencies. But unfortunately, it doesn't cover "why it has a specific version" as you mentioned.

**Comment by homersimpsons** [comment]
Oh, I didn't notice that you could invert `cargo-tree`. Thank you for this information !

**Comment by epage** [comment]
Since we have `cargo tree -i`, do we still need this issue?  Is there something we could do to make it easier to go from user problem ("why this dependency") to discovering `cargo tree -i`?

Granted, for myself, I just use `cargo tree | less` and just search the output because I forget about `-i` (speaking of, maybe we should have pager support for `cargo tree`).

**Comment by epage** [comment]
Closing this as covered by `cargo tree`.  #12903 adds some more documentation around this.
