### ISSUE TITLE
Allow cargo +rust-version build|test|...

### ISSUE THREAD

**Issue by imp** [rust-lang/cargo#10012]
### Problem

Now that [rust-version](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) is stable it makes sense to have a CI task/job that asserts this commitment. In that case, one would need to set up a CI config that runs tests on the selected Rust version. Usually, it means that the specific version will be specified twice
1. `rust-version` in `Cargo.toml`
2. Somewhere in CI configuration.

And they need to be in sync to make sense. This is where extra work is required and that may be avoided.

### Proposed Solution

I suggest teaching `cargo` to understand the `+rust-version` parameter, alongside the `+stable`, `+nightly`, and friends. When specified it will cause cargo to use the Rust toolchain referenced in the `rust-version` parameter. (And installing it on demand as it does today when used with other `+toolchain` parameters).
If used for crates that lack `rust-version` parameter it will fall back to otherwise default toolchain configured for this crate.

As a result, the potential disagreement between CI and `rust-version` will be avoided completely, better usability, less time wasted, etc

**Comment by Eh2406** [comment]
I do not have permissions to transfer to rustup. @imp can you open an issue there?

**Comment by imp** [comment]
Done
