### ISSUE TITLE
How can I pass some compiler flags to certain crates?

### ISSUE THREAD

**Issue by fCorleone** [rust-lang/cargo#10014]
### Problem

I want to compile a project with `cargo build`.  This project has one binary and several libraries. I would like to pass some compiler flags such as `llvm-args=-sanitizer-coverage-level=2` to certain crates. If I change the environment variable: RUSTFLAGS, all the dependencies will also be passed with the flags. Is there a way?

**Comment by weihanglo** [comment]
The unstable [profile rustflags](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option) feature can help this. For example

```toml
[profile.dev.package.foo]
opt-level = 3
rustflags = [ "-C", "..." ]
```

Let's track this issue over there. Closing and thanks!
