### ISSUE TITLE
Cargo Update Error

### ISSUE THREAD

**Issue by cylof22** [rust-lang/cargo#10020]
### Problem

Updating crates.io index
error: failed to get `anyhow` as a dependency of package `cargo v0.59.0 (/Users/yuanle.cao/Documents/cargo)`

Caused by:
  failed to load source for dependency `anyhow`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  an unknown git error occurred; code=NotFound (-3)

**Comment by ehuss** [comment]
Can you include the version information `cargo version --verbose`, and say how you installed Rust?  Can you try on the nightly channel?  Which operating system are you using?

**Comment by cylof22** [comment]
The problem is fixed now. It is caused by the local bad .gitconfig file.

**Comment by LucasLarson** [comment]
> bad .gitconfig file

Same here: specifically that my default git config file (`$XDG_CONFIG_HOME/git/config`) wasn’t being read, but an empty file at `~/.gitconfig` _was_ trying to be read. After  deleting it with `rm $HOME/.gitconfig`, everything worked again.
