### ISSUE TITLE
Error: unable to update registry `crates-io`

### ISSUE THREAD

**Issue by AVAtarMod** [rust-lang/cargo#10021]
### Problem

I have some problem as in  #10020
I just install rust and cargo on opeSUSE Tumbleweed and get broken cargo. I tried "cargo intall --path ." and other commands on several projects from different people but it not solve issue.
Installing cargo from rustup didn't solve issue too.

### Steps

1. Cd to rust app
2. cargo install --path .

### Notes

Example of cargo's work:
$ cargo install --path .
  Installing i3status-rs v0.20.5 (path)
    Updating crates.io index
error: failed to compile `i3status-rs v0.20.5 (path)`, intermediate artifacts can be found at `path`

Caused by:
  failed to get `chrono` as a dependency of package `i3status-rs v0.20.5 (path)`

Caused by:
  failed to load source for dependency `chrono`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  invalid version 0 on git_proxy_options; class=Invalid (3)

### Version

```text
cargo 1.55.0
release: 1.55.0
```

**Comment by ehuss** [comment]
Hm, sorry you're running into that trouble.  I haven't seen that error, but I suspect it is an incorrect version of libgit2 in cargo.

Can you try on the latest nightly release?  And can you also provide the output of `cargo +nightly version --verbose` after installing nightly?

**Comment by AVAtarMod** [comment]
Steps:
1. 
```
$ rustup install nightly
...
nightly-x86_64-unknown-linux-gnu installed - rustc 1.58.0-nightly (ff0e14829 2021-10-31)
```
2.
```
$ cd project
$ rustup run nightly cargo version --verbose
cargo 1.58.0-nightly (6c1bc24b8 2021-10-24)
release: 1.58.0
commit-hash: 6c1bc24b8b49d4bc965f67d7037906dc199c72b7
commit-date: 2021-10-24
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: openSUSE 20211029 [64-bit]
```
Now using cargo from official repo fixed problem!
Thanks, project successful builded.
