### ISSUE TITLE
`cargo new` fails if git template directory is non-existent

### ISSUE THREAD

**Issue by ammgws** [rust-lang/cargo#10038]
#### Current Behaviour

With a specific git config, `cargo new foo` will fail after creating an empty directory but before creating the usual template files, and the git repo is not initialised:
 
```sh
>cargo new foo
error: Failed to create package `foo` at `/tmp/foo`

Caused by:
  could not find '/tmp/DoesNotExist/' to stat: No such file or directory; class=Os (2); code=NotFound (-3)

> find foo
foo
foo/.git
```

#### Expected Behaviour

Since `git init` itself still initalises a repo even if the template dirs do not exist, `cargo new foo` should not fail in the way it does.

### Steps

1. Set git config to contain:
```ini
[init]
  templatedir = "/tmp/DoesNotExist"
```

2. Run `cargo new foo`

### Possible Solution(s)

If recognised as an issue with libgit2 (https://github.com/libgit2/libgit2/pull/6106), then need to wait for git2-rs to be updated?

### Version

```text
cargo 1.52.0 (69767412a 2021-04-21)
release: 1.52.0
commit-hash: 69767412acbf7f64773427b1fb53e45296712c3c
commit-date: 2021-04-21
```

**Comment by ammgws** [comment]
The fix was merged this morning in in libgit, so just have to wait for a new release I think.

**Comment by wangkirin** [comment]
> 

fine， thank you for your remind

**Comment by weihanglo** [comment]
Confirmed that it succeeds starting from 1.61. Thanks everyone. Closing
