### ISSUE TITLE
Dash (`-`) in a crate name breaks `rustdoc-scrape-examples`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/cargo#10035]
### Problem

When a crate has a dash (`-`) in its name, the unstable `rustdoc-scrape-examples` option stops working. 

### Steps

1. Create a crate with a dash in it's name: `cargo new --lib da-sh && cd da-sh`
2. Add a function to the crate: `echo "pub fn f() {}" >> src/lib.rs`
3. Add an example that uses the added function: `mkdir examples && echo "fn main() { da_sh::f() }" > examples/e.rs`
4. Run `rustdoc`: `cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples=examples --open`
5. Observe documentation of `f` (example is missing): ![image](https://user-images.githubusercontent.com/38225716/140387919-4dfb11fa-3936-4eee-96a1-48d9dc4a2a2f.png)
6. Remove dash from the crate name: `sed -i 's/da-sh/dash/' Cargo.toml && sed -i 's/da_sh/dash/' examples/e.rs`
7. Run `rustdoc`: `cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples=examples --open`
8. Observe documentation of `f` (example is present): ![image](https://user-images.githubusercontent.com/38225716/140388134-303266b1-3a25-45b5-9138-ad48e952a82d.png)

### Notes

I'm not sure if this is an issue with `rustdoc` or `cargo`, maybe this issue should be moved to `rustdoc` repo.

### Version

```text
cargo 1.58.0-nightly (94ca096af 2021-10-29)
```

**Comment by Eh2406** [comment]
cc @willcrichton

**Comment by willcrichton** [comment]
Thanks for the concise repro @WaffleLapkin! I just created a PR for the fix.
