### ISSUE TITLE
cargo should attempt to read Cargo.lock of later format versions

### ISSUE THREAD

**Issue by dekellum** [rust-lang/cargo#10046]
### Problem

I noticed `version = 3` starting to appear with updates to `Cargo.lock`, and was initially wondering how safe it was to commit this version change, from an MSRV compatibility perspective.

From testing, it appears that cargo version <1.47.0 will ignore the new top level `version` field. The [change log for 1.47][1.47] only describes the "preparation" inspiring this addition.

[1.47]: https://github.com/rust-lang/cargo/blob/333ee58d24/CHANGELOG.md#cargo-147-2020-10-08

Further wondering about compatibility, I manually set `version = 4` in a `Cargo.lock`, and on run of cargo (1.47.0 through 1.58.0), receive the fatal error shown below:

```txt
error: failed to parse lock file at: /home/david/src/test-lock-version/Cargo.lock

Caused by:
  lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?

```

### Possible Solution(s)

Wouldn't it be better to issue only a _warning_ message, and for cargo to make a best effort to read the lock file anyway, attempting forward compatibility? The git dependency default branch changes that inspired version 3 will only effect a small subset of projects, and unlike the V2 change, the actual lock format is compatible. If it remains a hard error, it practically means that when `version = 4` is introduced, users will need to avoid committing the new format until their MSRV supports it.  If you agree, the sooner this is converted to a warning, the better, from a future MSRV compatibly perspective.

### Version

```text
cargo 1.58.0-nightly (94ca096af 2021-10-29)
release: 1.58.0
commit-hash: 94ca096afbf25f670e76e07dca754fcfe27134be
commit-date: 2021-10-29
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Arch Linux [64-bit]
```

**Comment by alexcrichton** [comment]
This is currently working as intended, and there's a [long comment in the source](https://github.com/rust-lang/cargo/blob/fa03f0e16987270ea1ad70f315dc7cda617e8dd3/src/cargo/core/resolver/encode.rs#L1-L112) explaining this as well. The tl;dr; is that Cargo already attempts to read future versions, but it's a feature that it generates a first-class error on an unknown version. If you see hte "unknown version found" error then it should either mean your toolchain is accidentally so ancient you didn't mean that or the Cargo team was too hasty and needs to fix its release schedules.

**Comment by dekellum** [comment]
Thanks @alexcrichton for sharing the source doc reference, as I hadn't found that, and it wasn't clear this was intentional.  The concern was inspired by what I observed with the v2 lock format rollout the seemed to follow the same release strategy:

> * Wait a "long time". This is at least until the \[new lock version] changes here hit stable
>    Rust. Often though we wait a little longer to let the changes percolate
>    into one or two older stable releases.

As many projects are attempting to purposefully update MSRV once or twice a year, lock format support in 3-5 stable releases will frequently not be enough to avoid breakage.   The inconvenient workaround will be to avoid the new format (by not updating Cargo.lock with newer cargo versions) until the project is ready to update MSRV.  

To be clear, v2 was a breaking change but a nice improvement to the format (for example reducing conflicts in lock file commits).  Bumping the lock file version integer for changing a default value of a less commonly used feature might be less desirable on balance?

**Comment by alexcrichton** [comment]
It's fine to open specific issues about too-fast rollouts but otherwise this is all stuff we take into account when rolling out features like this. It's also hard to talk about policy in the abstract when there isn't a concrete change on hand being considered.
