### ISSUE TITLE
.cargo configuration directory in workspace subcrate

### ISSUE THREAD

**Issue by jonay2000** [rust-lang/cargo#10050]
### Problem

Placing a `.cargo` directory (with a cargo config file) in the root of a crate can configure cargo. However, when a crate has the following form:
```
/
    Cargo.toml  (has [worspace] with members a and b
    a/
        Cargo.toml
        src/
    b/
        Cargo.toml
        src/
       .cargo
           config
```

the .cargo config in b is not used, which is not what I expected. There may be a very good reason for disallowing, but I couldn't find it. Is this expected or unexpected behavior?

### Steps

Create a project conform the template in the above section. I created a git repository demonstrating the bug: https://github.com/jonay2000/cargo-bug

### Possible Solution(s)

I'm not entirely sure if we should support this (even though it is something I could use). The docs also don't list subcrates under the list of directories cargo looks in. Maybe it would be nice to explicitly state that subcrates are not included. 
![image](https://user-images.githubusercontent.com/22172241/140618978-79015a3d-d29e-47ff-bab0-1d7e4308c5ad.png)

Alternatively, we could support this. I'm not sure what the technical limitations of supporting this are, maybe people with more knowledge about cargo internals could help with this.

### Notes

In some sense, this may not be considered a bug, and more of a feature request. Feel free to reclassify it as such.

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by ehuss** [comment]
Yea, this is currently expected behavior. Cargo searches for config files based on the current working directory where it is launched.  I understand that can be potentially confusing.  I'm going to close this in favor of #9769.

**Comment by jonay2000** [comment]
thanks for the quick reply!
