### ISSUE TITLE
cargo clean [--offline] downloads toolchain if specified

### ISSUE THREAD

**Issue by DzenanJupic** [rust-lang/cargo#10056]
### Problem

When running `cargo clean` or `cargo clean --offline` in a cargo project with a `rust-toolchain` file, cargo downloads the toolchain if not yet installed.

This is really unexpected since I'd expect `cargo clean` to work without a specific toolchain installed. And if it's actually desired to download the new toolchain, the `--offline` flag should prevent this.

### Steps

1. create a new cargo project : `cargo new temp`
2. `cd temp`
3. add a `rust-toolchain` file: `printf '[toolchain]\nchannel = "nightly-2021-05-24"\ncomponents = ["rust-src", "rustc-dev", "llvm-tools-preview"]' > rust-toolchain`
4. run `cargo clean [--offline]`

### Possible Solution(s)

Don't check for `rust-toolchain` files when running `cargo clean`, or don't allow downloading toolchains when running `cargo <CMD> --offline`.

### Notes

While filing this issue, I noticed that this also happens when running `cargo --version` 🤔

### Version

```text
cargo 1.58.0-nightly (94ca096af 2021-10-29)
release: 1.58.0
commit-hash: 94ca096afbf25f670e76e07dca754fcfe27134be
commit-date: 2021-10-29
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:Schannel)
os: Windows 10.0.19042 (Windows 10 Pro) [64-bit]
```

**Comment by DzenanJupic** [comment]
A quick fix is `cargo +<toolchain> clean`.

**Comment by Eh2406** [comment]
Toolchain is a Rustup concept, Cargo itself has no idea what a Toolchain is let alone witch it is being run from. Rustup wraps Cargo to figure out which one to run for the directory you are in. In order to run the one specified in your `rust-toolchain` file it needs to be downloaded. You may want to discuss this with the Rustup taem; I don't think the Cargo team can help you.

**Comment by ehuss** [comment]
Yea, unfortunately cargo and rustup are two separate tools that don't really know much about each other. If the toolchain is not installed, rustup wouldn't know which one to use to execute `cargo clean`.

I understand, though, that it can be a little surprising if you pass something like `--offline`.  

Given that this is a fundamental limitation of having rustup be an outer wrapper, I'm going to close as something we cannot address.
