### ISSUE TITLE
Segmentation fault when attempting to update crates.io index on WSL

### ISSUE THREAD

**Issue by cbondurant** [rust-lang/cargo#10058]
### Problem

I have been developing a rust application under the Windows Subsystem for Linux. I recently added a dependency on the md5 crate.

Upon trying to build, cargo will attempt to update the crates.io index and immediately segfault.

### Steps

1. Make a new directory `cargo_test`
2. `cargo init`
3. add `md5 = "0.7.0"` to the dependencies section of Cargo.toml
4. `cargo run`
5. the following error will appear:
```
    Updating crates.io index
[1]    4269 segmentation fault (core dumped)  cargo run
```

### Notes

This error occurs specifically with WSL Debian. and I have not experienced the same issue on standard versions of Debian not installed through WSL.

### Version

```text
cargo 1.42.1
release: 1.42.1
```

**Comment by cbondurant** [comment]
Oh something I forgot to add: 
While researching possible fixes, I did attempt to debug using `lldb` as suggested in other old issues similar to this one. However it completely stalls out and never reaches the segmentation fault, so I have not been able to get a backtrace at this time.

**Comment by ehuss** [comment]
`1.42.1` is quite an old release.  How did you install Rust? Can you try with the latest stable or nightly version?

**Comment by cbondurant** [comment]
Uninstalling the package from debian's repository and installing instead through rustup resolved the problem. 

Thank you for the advice.
