### ISSUE TITLE
cargo clean -p does not clean if path contains glob characters

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#10068]
### Problem

`cargo clean -p` fails to delete a number of files from `target/` if the path to `target` contains glob characters. This is due to the use of `rm_rf_glob` used for cleaning, which does not escape glob characters in the path before adding the pattern:

https://github.com/rust-lang/cargo/blob/e11cd814f8ec5d11a65ae3aea7c3976f250d36a6/src/cargo/ops/cargo_clean.rs#L210-L216

Here for example:

https://github.com/rust-lang/cargo/blob/e11cd814f8ec5d11a65ae3aea7c3976f250d36a6/src/cargo/ops/cargo_clean.rs#L137-L142

### Steps

```bash
#!/bin/bash
rm -rf glob-in-rm
mkdir glob-in-rm
cd glob-in-rm

for d in '[hello]' 'hello'; do
	mkdir "$d"
	pushd "$d"
	cargo new foo
	cd foo
	cargo check
	cargo clean -p foo
	popd
done

diff -qr '[hello]/foo/target' 'hello/foo/target'
```
```
Only in [hello]/foo/target/debug/.fingerprint: foo-8ca57bdc9f429d2a
Only in [hello]/foo/target/debug/deps: foo-8ca57bdc9f429d2a.d
Only in [hello]/foo/target/debug/deps: libfoo-8ca57bdc9f429d2a.rmeta
Only in [hello]/foo/target/debug/incremental: foo-1qp1vfygk93x
```

### Possible Solution(s)

Escape any non-pattern part of the string passed to `glob` with [`glob::Pattern::escape`](https://docs.rs/glob/0.3/glob/struct.Pattern.html#method.escape).

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by henrifrancois** [comment]
!rustbot claim
