### ISSUE TITLE
Cargo new does not use git default branch on Windows.

### ISSUE THREAD

**Issue by adoble** [rust-lang/cargo#10085]
### Problem

I have following installation:
- cargo 1.56.0
- rustc 1.56.1
- git version 2.34.0.windows.1  (i.e running on Windows 10) 

Running: 
```console
$ git config --get init.defaultBranch
main
```
However running: 

```console
$ cargo new new-project
$ cd new-project
$ git status
On branch master

...
```

Despite having specified the default branch in git to be `main`, cargo new has created a project with git branch `master`. 

I tried using `cargo init`, but this also created a branch with the name 'master". 

I was under the impression that setting the `init.defaultBranch` in the git config should have changed the behaviour of `cargo new`. Am I doing something wrong or is this a problem specific to Windows?

Note that this has been raised before in, for instance, issue #9716, but the issue has been closed. 

### Steps

See the problem description.

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
```

**Comment by ehuss** [comment]
Can you run `git config --show-origin --get init.defaultBranch` and make sure the setting is in your global config?

**Comment by adoble** [comment]
Thanks for getting back on this.  

Running:

```console
$ git config --show-origin --get init.defaultBranch
file:C:/Program Files/Git/etc/gitconfig main
```

**Comment by ehuss** [comment]
Hm, that's not a file location that I've seen used on Windows.  Are you using [Git for Windows](https://gitforwindows.org/)? Which version of git do you have installed?

My understanding of Windows config file locations are:
* System: `C:\Program Files\Git\mingw64\etc\gitconfig`
* Global: `%USERPROFILE%\.gitconfig`
* Portable: `C:\ProgramData\Git\config`

**Comment by adoble** [comment]
I do believe I am using Git for Windows  - I downloaded it from https://git-scm.com/download/win (the 64 bit version). 

All the config files you identified also exist on my development laptop.  However, I specified the default branch name during the installation process, rather than using Git directly.

**Comment by adoble** [comment]
So, the previous comments have just given me an idea. Trying the following:

``` console
$ git config --global init.defaultBranch main
$ git config --show-origin --get init.defaultBranch
file:C:/Users/T440s/.gitconfig  main
```

Gives the same result as before. But then trying:

``` console
$ cargo new another-project
$ cd another-project
$ git status
On branch main
...

``` 
I.e. has correctly worked! 

I have the feeling that something strage happens during the installation of `git`, but here I'm not an expert.

**Comment by adoble** [comment]
Just tried to duplicate the above problem on a different machine. During the installation of `git` (version 2.34.0.windows.1) specified that the default branch was `main`.  Typing:

```console
$ git config --show-origin --get init.defaultBranch
file:C:/Program Files/Git/etc/gitconfig main
```
I got the "unusual" config file from before. However `cargo new` **worked correctly** and set up a git repository with default branch `main`.  A case of "doesn't work on my machine" :blush: so closing the issue.
