### ISSUE TITLE
Tracking Issue for `--crate-type` flag

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#10083]
### Summary

RFC: [#3180](https://github.com/rust-lang/rfcs/pull/3180)
Implementation: #10093
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#crate-type

This is the tracking issue for RFC 3180 which adds the `--crate-type` argument to `cargo rustc` to explicitly change the crate type of the crate being built.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by hi-rustin** [comment]
I would like to try to add it. Can I claim it?

**Comment by ehuss** [comment]
Sure! I don't think anyone else has expressed interest.

Let me know if you have any questions.  For handling unstable support, [`fail_if_stable_opt`](https://github.com/rust-lang/cargo/blob/d2cc298079ff99096c4c70ee9b84fde6473e69c8/src/cargo/core/features.rs#L898) can be used to require `-Z unstable-options`.  

I'm not sure about the best way to pass the information down to the right place.  I'm thinking adding another map to `BuildContext` similar to `extra_compiler_args` might be a good option for now. Then the points where the crate-type is selected can consult that map to see if there is an override.

**Comment by seanmonstar** [comment]
I tried this out in hyper today, and hit errors. Filed https://github.com/rust-lang/cargo/issues/10356

**Comment by hi-rustin** [comment]
> Is making this feature stable on hold until the cargo team has additional review capacity? If not, what needs to happen to get this over the finish line?
> 
> I assume we just want to wait to see if anyone runs into more issues, but how long should we wait?

Yes, I think we need to wait a little longer.

**Comment by yodaldevoid** [comment]
It's been a little over two months since I last asked so I thought I'd poke this issue once more.

I took a look at the `cargo` issue tracker and could find no open issues about the `--crate-type` flag nor any issues opened and then closed in the past two months.

I asked last time how long the team would like to wait, though I didn't get any answer. I understand if this is something that is more of a gut feeling.

I'm sorry if I'm being a bit of a bother, I know I'm just being impatient.

**Comment by hi-rustin** [comment]
@ehuss What do you think? Should we stabilize it now? 

I'm happy to help stabilize it if needed.
