### ISSUE TITLE
Cargo should respect `DEBIAN_FRONTEND`

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/cargo#10087]
### Problem

Currently, hosting providers like [Railway](https://railway.app) do not render Cargo properly, due to them showing a progress bar that generally isn't supported. This should check whether or not `DEBIAN_FRONTEND` is `noninteractive`, and if it is, shouldn't show the spinner.

### Version

```text
N/A
```

**Comment by Eh2406** [comment]
We already have a number of ways of turning off the progress bar [sorce](https://github.com/rust-lang/cargo/blob/1a8692df1112dfde43a3bd73ac52aeea4c128f62/src/cargo/util/progress.rs#L42), including the "CI" environment variable and various command line options. Can one of those be used in your case?

**Comment by Milo123459** [comment]
Whilst that would work, I think also making a check for this is a good idea.

**Comment by joshtriplett** [comment]
`DEBIAN_FRONTEND` is a Debian-specific environment variable, and I don't think Cargo should be looking at it.

It *sounds* like Railway may be providing a TTY, but not supporting enough terminal features to be a functional TTY for Cargo's purposes. There are several ways to work around this:

- Don't provide a TTY, just a pipe or output file. In that case, Cargo will automatically avoid trying to do terminal control such as for the progress bar.
- Set `TERM=dumb`, which is the canonical way to say "terminal control sequences won't work on this terminal".
- Get Railway to implement the necessary control sequences.

I don't think we want to add any more workarounds for this, especially not by checking a Debian-specific environment variable that's not primarily directed at us (it's directed at Debian maintainer scripts and the tools commonly run within them).
