### ISSUE TITLE
papercut: cargo does not provide feedback when using a `cfg(feature = "...")` that is not declared in `Cargo.toml`

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/cargo#10102]
### Problem

Rust code in a crate can use `cfg(feature = "...")` attributes even if those features are not defined in `Cargo.toml`.

I would expect this to be an error or a warning.

### Steps

```sh
git clone https://github.com/artichoke/intaglio.git
cd intaglio/benchmarks
git checkout 28dc9784a59336aac5b879a9c90a56b85bee4216
cargo bench
```

Then observe that none of the `bytes` benches are ran.

This was fixed after stumbling upon this code during an ad hoc review:

- https://github.com/artichoke/intaglio/pull/114

### Possible Solution(s)

Emit a warning when Rust sources use a `cfg(feature = "...")` attribute for a feature that cargo will never pass for the crate because it is not declared in `Cargo.toml`.

### Version

```text
$ cargo --version --verbose
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by ehuss** [comment]
Thanks for the suggestion!  [RFC 3013](https://github.com/rust-lang/rfcs/blob/master/text/3013-conditional-compilation-checking.md) has been accepted to implement this. You can follow the tracking issue at https://github.com/rust-lang/rust/issues/82450 for updates.

**Comment by lopopolo** [comment]
ooo thank you. I looked in the cargo issues but didn't think to check the Rust repo. 😅
