### ISSUE TITLE
`--message-format` option missing from `cargo install`

### ISSUE THREAD

**Issue by Zingam** [rust-lang/cargo#10104]
I want to build, install and launch debugging from the install directory in VSCode.
I have created the following launch configuration:
```json
        "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Install & Debug 'HelloWorld'",
            "cargo": {
                "args": [
                    "install",
                    "--path",
                    ".",
                    "--bin=HelloWorld",
                    "--root",
                    "./install"
                ],
                "filter": {
                    "name": "HelloWorld",
                    "kind": "bin"
                }
            },
            "args": [],
            "cwd": "${workspaceFolder}"
        },
```
which causes the following error:

> Running `cargo install --path . --bin=HelloWorld --root ./install --message-format=json`...
error: Found argument '--message-format' which wasn't expected, or isn't valid in this context

Am I holding it wrong or is this a limitation of the system? 

Well it looks like I'm holding it wrong. Could we have this `--message-format=json` option in the install context to enable install&debug workflow?

**Comment by ehuss** [comment]
I have transferred this to the cargo repo since it looks like a cargo issue.

Indeed, `--message-format` seems to be missing from `cargo install`.  It should be a relatively easy thing to add.

**Comment by hi-rustin** [comment]
@rustbot claim

I will add it.

**Comment by Zingam** [comment]
That was FTL fast! Thanx!
