### ISSUE TITLE
Confusing error message for invalid Cargo.toml file

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1011]
This Cargo.toml file:
```
[package]

name = "matches"
version = "0.0.1"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]

[lib]
path = "lib.rs"
```

Gives a confusing error message:

```
matches/Cargo.toml is not a valid manifest

expected a value of type `array`, but found a value of type `table` for the key `lib`
```

Adding a `lib.name` key fixes it, but the error message was not helpful in finding that out.
```
[package]

name = "matches"
version = "0.0.1"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]

[lib]
name = "matches"
path = "lib.rs"
```

Also, since omitting the `[lib]` section entirely works, overriding just `lib.path` should work as well, keeping the default name.

**Comment by toh-ableton** [comment]
Just ran into this as well. I appears that the bug is that you need more than one key-value pair in the ``[lib]``-section.

**Comment by oli-obk** [comment]
I think this is fixed. The error is now ```expected a value of type `string` for the key `lib.name` ```

**Comment by alexcrichton** [comment]
Thanks @oli-obk!
