### ISSUE TITLE
`cargo fetch -Zbuild-std` doesn't fetch dependencies for the standard library

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#10127]
### Problem

`cargo fetch -Zbuild-std` only fetches dependencies listed in Cargo.toml, not dependencies for the standard library. It will only try to fetch libstd dependencies when running `cargo build -Zbuild-std`. This is an issue for sandboxed builders, like https://github.com/rust-lang/rustwide, which disallow network access during builds.

### Steps

1. `rm -r ~/.cargo/registry/cache`
2. `cargo new --lib my_project && cd my_project`
3. `cargo fetch -Zbuild-std`. Note that nothing is downloaded.
4. `cargo build -Zbuild-std --target x86_64-unknown-linux-gnu`
```
cargo build -Zbuild-std --target x86_64-unknown-linux-gnu
  Downloaded rustc-demangle v0.1.21
  Downloaded memchr v2.4.1
  Downloaded unicode-width v0.1.8
  Downloaded libc v0.2.106
  Downloaded addr2line v0.16.0
  Downloaded adler v0.2.3
  Downloaded cfg-if v0.1.10
  Downloaded getopts v0.2.21
  Downloaded cc v1.0.69
  Downloaded hashbrown v0.11.0
  Downloaded miniz_oxide v0.4.0
  Downloaded object v0.26.2
  Downloaded compiler_builtins v0.1.52
  Downloaded gimli v0.25.0
  Downloaded 14 crates (2.0 MB) in 0.57s
   Compiling compiler_builtins v0.1.52
   Compiling core v0.0.0 (/home/joshua/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling libc v0.2.106
   Compiling cc v1.0.69
   Compiling memchr v2.4.1
   Compiling std v0.0.0 (/home/joshua/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std)
^C  Building [>                           ] 2/41: core, std(build.rs), memchr(build.rs), cc
```

### Possible Solution(s)

Fetch the dependencies earlier, in `cargo fetch`.

### Version

```text
cargo 1.58.0-nightly (ad50d0d26 2021-11-17)
```

**Comment by ehuss** [comment]
Thanks for the report, this is a known issue tracked in https://github.com/rust-lang/wg-cargo-std-aware/issues/22, so closing in favor of that.
