### ISSUE TITLE
Can "--host" related command information be deleted?

### ISSUE THREAD

**Issue by QiangHeisenberg** [rust-lang/cargo#10121]
I found that in 2017 "--host" has been replaced by "--index". https://github.com/rust-lang/cargo/pull/4209

Is it necessary to keep this command or prompt message now?
https://github.com/rust-lang/cargo/blob/7f08ace4f1305de7f3b1b0e2f765911957226bd4/tests/testsuite/search.rs#L184-L236
and
https://github.com/rust-lang/cargo/blob/7f08ace4f1/src/cargo/util/command_prelude.rs#L633

**Comment by alexcrichton** [comment]
Our policy on removing features is to first confirm that they have been warning for a long time, and only if the warning has been issued then it's safe to remove at this point.

**Comment by QiangHeisenberg** [comment]
I think it has been reminded long enough. Do you mean that there is still a need to issue a warning to remove the feature? What to do next?

**Comment by alexcrichton** [comment]
If the warning has been issued for years then it should be safe to remove, yes.
