### ISSUE TITLE
cargo build not working on Ubuntu wsl2

### ISSUE THREAD

**Issue by blockchainlover2019** [rust-lang/cargo#10144]
### Summary

Hi.
I am using Ubuntu wsl - windows subsystem for linux.
To build solana project, I need to run cargo build-bpf.
When I try to build rust project, cargo build or cargo build-bpf doesn't work.
```
user@DESKTOP-54YU45:/mnt/d/Blockchain/Solana/program-rust$ cargo build-bpf
```
or
```
user@DESKTOP-54YU45:/mnt/d/Blockchain/Solana/program-rust$ cargo build
Updating crates.io index
```
I waited half a day, but still not built, still nothing displayed.
but in Windows, it works
```
D:\Blockchain\Solana\program-rust>cargo build
   Compiling proc-macro2 v1.0.30
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.80
   Compiling serde_derive v1.0.130
   Compiling serde v1.0.130
   Compiling typenum v1.14.0
   Compiling version_check v0.9.3
   Compiling cfg-if v1.0.0
   Compiling subtle v2.4.1
   Compiling semver-parser v0.7.0
   Compiling winapi v0.3.9
   Compiling getrandom v0.1.16
   Compiling crunchy v0.2.2
   Compiling memchr v2.3.4
    Building [>                         ] 10/138: getrandom(build.rs), memchr(build.rs), crunchy(build.rs), winapi...
```

What's the reason?

**Comment by ehuss** [comment]
Can you provide the following?
* Are you on wsl1 or wsl2? You can see this by running `wsl -l -v` in a powershell prompt.
* Which version of Ubuntu do you have?
* Which version of Windows are you using?
* Do you have a proxy or any other unusual network configuration?
* Can you access github from within your Ubuntu image? For example, can you clone a repository?

**Comment by blockchainlover2019** [comment]
Hey, @ehuss, thanks for your reply. These are my answers.
- I use wsl2.
```
wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
  Ubuntu-20.04           Running         2
```
- Ubuntu version is the latest Ubuntu 20.04 LTS (version is 2004.2020.424.0)
- Windows is also the latest. Windows10 pro(20H2) 19042.1348
- I don't use proxy
- I can clone github repository in my wsl Ubuntu. I tried.

Help me

**Comment by weihanglo** [comment]
Random tips here:

- Create a file `.cargo/config.toml` and follow the guide of [`http.debug`] or else to debug the connection.
- Replace libgit2 in cargo with CLI git by the config [`net.git-fetch-with-cli`]. Then try again.

[`http.debug`]: https://doc.rust-lang.org/cargo/reference/config.html#http
[`net.git-fetch-with-cli`]: https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

**Comment by blockchainlover2019** [comment]
Hey, @weihanglo , thanks for your answer.
But still not work.
This is content of ~/.cargo/config.toml
```
[http]
debug = true

[net]
git-fetch-with-cli = true
```
When I run cargo build then
```
user@DESKTOP-54YU45:/mnt/e/RUST/rust/rust-examples$ cargo build -v
    Updating crates.io index
     Running `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' 'HEAD:refs/remotes/origin/HEAD'`
error: failed to get `arr_macro` as a dependency of package `example v0.1.0 (/mnt/e/RUST/rust/rust-examples)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' 'HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
  --- stderr
  fatal: unable to access 'https://github.com/rust-lang/crates.io-index/': gnutls_handshake() failed: Error in the pull function.
```
Well, what's the reason?

**Comment by ehuss** [comment]
Searching for the [error message](https://www.google.com/search?q=gnutls_handshake+failed%3A+Error+in+the+pull+function.) shows a number of people having similar issues with git and wsl2. You might try some of the following:

* Delete the directory `~/.cargo/registry`. This should delete any existing repositories.
* Maybe try updating gnutls, or installing openssl (i'm not sure how your system is set up).
* When using `http.debug`, you have to also set the `CARGO_LOG=cargo::ops::registry=debug` environment variable to get the output.

Also, where did you install Rust from?  I'm a bit confused by the mention of `gnutls`, as the official distributions are built with OpenSSL.  Perhaps you installed Rust from your package manager? If so, you might instead try using the [official distribution](https://rustup.rs/).
