### ISSUE TITLE
Allow spaces in paths printed by build scripts

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#1015]
Right now the output looks like:

```
cargo:rustc-flags=-L foo bar
```

We don't know whether this is the directory `foo bar` or `-L foo` plus a flag `bar`. We should support some form of escape sequences.

**Comment by pornel** [comment]
I can imagine string escaping is going to be a bit annoying and often forgotten with the current `println!`-based API.

Could you abstract that print away with a native API?

```rust
extern crate cargo;

fn main() {
    cargo::current_build().lib_path(Path::new("foo bar"));
}
```

It could also solve problem of using lossy `path.display()` for `format!()` (e.g. behind the scenes you could print base64-encoded path).

**Comment by alexcrichton** [comment]
I agree! I'd love to have a helper library for common tasks like this.

**Comment by cmr** [comment]
Proposed design:

```
cargo:link-lib=KIND=....
cargo:link-search=KIND=...
```

With treating `\` as an escape character, with the only escape sequence being `\\` and `\n` (to embed newlines). This avoids all need for Cargo to try and parse command line arguments, and doesn't have the misleading look of allowing passing arbitrary arguments.

**Comment by alexcrichton** [comment]
Hm, I think I like this a bit better, yes. I haven't been super happy with how `rustc-flags` has turned out. I would personally recommend `cargo:rustc-link-lib=...` and `cargo:rustc-link-search=...` to be clear that it's `rustc`-specific.

I'm also not so sure about the escaping newlines. This means that practically all windows paths have to be escaped by default (which is easily forgotten, and we don't have a helper). I suppose it's possible to have a newline in a path, but I'm also fine just "opening up an issue" and calling it a day.

**Comment by cmr** [comment]
Yes, that's true... how about just using a NUL, which is (to my knowledge) an invalid path character in every OS.

**Comment by alexcrichton** [comment]
We could, although it is a little surprising (and messes with the line-oriented output). If it really is pressing to add the ability to support newlines we could always add another metadata key as well (yay extensibility!)

**Comment by cmr** [comment]
Yeah. I'll just leave it out for now.
