### ISSUE TITLE
cargo doc: Optionally generate foo/index.html with foo/ links, instead of foo.html

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1017]
If https://github.com/rust-lang/rust/issues/19600 happens, it should be exposed by `cargo doc`. A command-line switch should be available so that `cargo doc` can default to generating longer links that work for `file://…` local viewing, but e.g. a Travis-CI script can generate nicer-looking links for HTTP(S) publication.

**Comment by alexcrichton** [comment]
I believe this is more of a rustdoc issue than a Cargo issue as Cargo isn't the one generating any of these links, so I think this would be better placed in rust-lang/rust instead of here.

**Comment by SimonSapin** [comment]
The rustdoc issue is https://github.com/rust-lang/rust/issues/19600, as linked from the first message. Assuming that one gets fixed, *this* issue is about exposing it somehow to `cargo doc`.
