### ISSUE TITLE
Cargo does not re-use artifacts with different `CARGO_HOME`

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#10179]
### Problem

Cargo's artifact fingerprinting includes the path to `CARGO_HOME`, which means that two builds that share a `CARGO_TARGET_DIR`, but have separate `CARGO_HOME`s, end up re-compiling shared dependencies unnecessarily.

### Steps

1. Create two new Cargo projects with a shared dependency:
   ```bash
   cargo new foo
   echo 'serde = "1"' >> foo/Cargo.toml
   cargo new bar
   echo 'serde = "1"' >> bar/Cargo.toml
   ```
2. `mkdir target foo/home bar/home`
3. Build `foo` with a known target directory, and it's own Cargo home directory:
   ```bash
   env \
	CARGO_TARGET_DIR="$PWD/target" \
	CARGO_HOME="$PWD/foo/home" \
	cargo check --manifest-path foo/Cargo.toml
   ```
4. Build `bar` with the same target directory, but a different Cargo home directory:
   ```bash
   env \
	CARGO_TARGET_DIR="$PWD/target" \
	CARGO_HOME="$PWD/bar/home" \
	cargo check --manifest-path bar/Cargo.toml
   ```
5. Notice that `serde` gets compiled when `bar` is built.
6. Re-execute the build for `foo` above — not that `serde` gets built yet again.

Cargo does not re-build `serde` if the builds share a `CARGO_HOME`.

### Possible Solution(s)

Cargo's fingerprinting includes the path to the crate's source here:
https://github.com/rust-lang/cargo/blob/40dc281755137ee804bc9b3b08e782773b726e44/src/cargo/core/compiler/fingerprint.rs#L1340

Which is actually computed here:
https://github.com/rust-lang/cargo/blob/40dc281755137ee804bc9b3b08e782773b726e44/src/cargo/util/workspace.rs#L113-L114

There is currently a bit in there that tries to normalize the path for (I think) directory registries:
https://github.com/rust-lang/cargo/blob/40dc281755137ee804bc9b3b08e782773b726e44/src/cargo/util/workspace.rs#L118-L122

But it feels like if the source path is under `CARGO_HOME/registry/src`, then we should strip that from the prefix too, at least as far as fingerprinting is concerned. All that matters if whether we're using the same coordinate from the same registry, not which extracted copy of that `.crate` we're using (since they should all be identical).

### Notes

This is tangentially related to https://github.com/rust-lang/cargo/issues/7078

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.64.1 (sys:0.4.49+curl-7.79.1 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 11.6.1 [64-bit]
```

**Comment by alexcrichton** [comment]
I believe this is correct behavior on behalf of Cargo right now because the full source path is used for debug information so it affects the final artifact. "Fixing" this issue would mean somehow doing something along the lines of remapping the paths to the same value.

**Comment by jonhoo** [comment]
Oh that's interesting — I didn't think of source paths in debug info. That certainly makes things more awkward. In my particular case I think using a relative path in the debug info would work, but that's obviously not a general fix. Alternatively, I wonder if we could save a bunch of the work if debuginfo was split out from the main binary 🤔

**Comment by bjorn3** [comment]
> Alternatively, I wonder if we could save a bunch of the work if debuginfo was split out from the main binary 🤔

I don't think so. The debuginfo contains the location of individual instructions for line debuginfo. To get these locations you need to run all optimizations and compile it down to a binary. In addition the object file itself contains paths to include in panic messages.

**Comment by ehuss** [comment]
I'm going to close, as this doesn't seem feasible to support at this time.
