### ISSUE TITLE
false positive optional dependencies

### ISSUE THREAD

**Issue by flisky** [rust-lang/cargo#10181]
### Problem

We build a library with `reqwest` & `tokio` dependencies using target `wasm32-unknown-unknown` **in a workspace**, but cargo wrongly includes some `tokio` optional dependencies (`bytes`, `memchr`, `mio` in this case) which fails to build under `wasm32`. 

### working 
```
cargo new sandbox
cd sandbox
cargo add reqwest
cargo add tokio
cargo tree --target wasm32-unknown-unknown
```
output:
```
└── tokio v1.14.0
    └── pin-project-lite v0.2.7
    [build-dependencies]
    └── autocfg v1.0.1
```

### unexpected
```
make test
cd test
echo '[workspace]\nmembers = ["sandbox"]' > Cargo.toml
```
and do the above steps.

`cargo tree --target wasm32-unknown-unknown` outputs:
```
└── tokio v1.14.0
    ├── bytes v1.1.0
    ├── memchr v2.4.1
    ├── mio v0.7.14
    │   └── log v0.4.14
    │       └── cfg-if v1.0.0
    └── pin-project-lite v0.2.7
    [build-dependencies]
    └── autocfg v1.0.1
```

### Version

```text
cargo +stable version --verbose


cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: aarch64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.77.0 (sys:0.4.49+curl-7.79.1 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 12.0.1 [64-bit]
```

cargo +nightly version --verbose
```
cargo 1.58.0-nightly (294967c53 2021-11-29)
release: 1.58.0
commit-hash: 294967c53f0c70d598fc54ca189313c86c576ea7
commit-date: 2021-11-29
host: aarch64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.77.0 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 12.0.1 [64-bit]
```
```

**Comment by ehuss** [comment]
The difference is that a single-package project with the 2021 edition will use a different resolver. In a workspace, since there isn't a way to specify the edition, you have to explicitly specify the resolver as in:

```toml
[workspace]
resolver = "2"
```

You can read more about resolver versions here: https://doc.rust-lang.org/nightly/cargo/reference/resolver.html#resolver-versions

**Comment by flisky** [comment]
Thanks for the anwser. I knew the `resolver = "2"`, but didn't realize I have to specify it with workspace
