### ISSUE TITLE
Add the option to refer to crates via author::crate_name syntax.

### ISSUE THREAD

**Issue by VivekYadav7272** [rust-lang/cargo#10184]
### Problem

Malware-ridden crates are starting to seep into crates.io repository that are named suspiciously similar to a lot of popular crates. It might or might not be possible to enforce a hierarchical structure onto the repository now, but if we're able to refer to these crates via author::crate_name syntax in Cargo.toml, then if the author is well-known and trusted (like Microsoft/Google or any individual author that's trusted), it's unlikely to spell the author name wrong and it'll provide additional protection against these kinds of typo mistakes leading to introducing malware-ridden libraries into our code.

### Proposed Solution

 Add the option to refer to crates via author::crate_name syntax.

**Comment by Eh2406** [comment]
If you have examples of Malware-ridden crates please report them responsibly.
If you just want to add name spacing, then look on https://internals.rust-lang.org/ to see previous discussions.
