### ISSUE TITLE
Seg fault with 'cargo build' on rust doc guessing game

### ISSUE THREAD

**Issue by Jbburris** [rust-lang/cargo#10180]
### Problem

I was starting with the rust docs and working through the first guessing game intro. At the point where we import our first dependency (rand), I get a seg fault with `cargo build`. Building on a raspberry pi running raspbian.

Stdout:
```
cargo build
    Updating crates.io index
Segmentation fault
```

src/main.rs:
```
use std::io;

fn main() {
        println!("Guess the number!");

        println!("Please input your guess.");

        let mut guess = String::new();

        io::stdin()
                .read_line(&mut guess)
                .expect("Failed to read line");

        println!("You guessed: {}", guess);
}
```

Cargo.toml:
```
[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Brooks <jbrooksburris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
```

Cargo.lock:
```
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "guessing_game"
version = "0.1.0"
```

OS: 
Static hostname: raspberrypi
         Icon name: computer
        Machine ID: xxxxxxxxxxxxxxxxxxxxxxx
           Boot ID: xxxxxxxxxxxxxxxxxxxxxxxxxx
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.63-v7+
      Architecture: arm

### Steps

Steps:
Pretty self-explanatory. Just follow the directions in the docs for "guessing game"

### Version

```text
cargo version --verbose
cargo 1.42.1
release: 1.42.1
```
```

**Comment by ehuss** [comment]
Sorry you're running into trouble.  Can you say where you installed rust from?  `1.42` is quite old, so I would recommend getting the latest stable version. Using the [rustup installer](https://www.rust-lang.org/tools/install) will install the official binaries.

**Comment by Jbburris** [comment]
Yeah I installed rustc via apt. I was then looking and found the rustup tool and that seemed to work for me. Thanks I'll close the issue
