### ISSUE TITLE
`cargo test` should show test execution time for slower tests

### ISSUE THREAD

**Issue by nyurik** [rust-lang/cargo#10208]
### Problem

`cargo test` only prints `ok/FAILED` after each test. In some cases, it might be very useful to see the test duration, similar to [mocha-js](https://mochajs.org/#test-duration).  Of course this is not as good as having a comprehensive benchmark tests, but in many cases it would give general feedback of how long each test took.

### Proposed Solution

Print the time each test took to run in ms, either always, or just for the tests that take longer than some magic number like 10ms:

```
running 2 tests
test tests::test_fast ... ok
test tests::test_slow ... ok (1200ms)
```

### Notes

Not sure if it would be worth it to introduce attributes to set the expected execution time, something like `#[test(slow = 5000)]` -- this would clearly be a far wider discussion.

#### Example from the Mocha project
![image](https://user-images.githubusercontent.com/1641515/146462009-73296009-fd73-43b1-ad46-e7d3c06e5f4f.png)

**Comment by ehuss** [comment]
Thanks for the suggestion!  I believe this is already implemented via the [`--report-time`](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/report-time.html) option.  I'm going to close in favor of the [tracking issue](https://github.com/rust-lang/rust/issues/64888).  For future reference, the test harness (the thing that runs the tests and prints the output) is tracked in the https://github.com/rust-lang/rust/ repository as it is not part of cargo.

**Comment by nyurik** [comment]
@ehuss thanks for the quick reply -- this is exactly what I was looking for!  I so wish it was a bit more discoverable - I searched through the `cargo test --help`, but didn't realize some of the options were not part of that text (the `cargo help test` doesn't mention it either).   Do you think it would be possible to somehow list all options available after the `--` ?

**Comment by ehuss** [comment]
[`cargo help test`](https://doc.rust-lang.org/cargo/commands/cargo-test.html#description) does point out how to get the information:

> For details about libtest's arguments see the output of `cargo test -- --help` and check out the rustc book's chapter on how tests work at <https://doc.rust-lang.org/rustc/tests/index.html>.

I don't think we want to replicate all of the help content (and I don't think we can with the built-in help), but I think adding a small mention to run `cargo test -- --help` at the bottom of `cargo test --help` would be good.  That goes [here](https://github.com/rust-lang/cargo/blob/8f8212c7baada3aef30a0c15668cb0ff084ed66e/src/bin/cargo/commands/test.rs#L59) if you'd like to post a PR.
