### ISSUE TITLE
cargo build fails with HTTP parser error: success; class=Net (12)

### ISSUE THREAD

**Issue by uglyoldbob** [rust-lang/cargo#10216]
### Problem

I am running cargo build and am encountering an odd failure.

$ cargo build
    Updating crates.io index
warning: spurious network error (2 tries remaining): HTTP parser error: success; class=Net (12)
warning: spurious network error (1 tries remaining): HTTP parser error: success; class=Net (12)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  HTTP parser error: success; class=Net (12)

I am running debian 10, 4.19.0-18-686-pae #1 SMP Debian 4.19.208-1 (2021-09-29) i686 GNU/Linux

Not really sure what to do since it says "error: success".

### Version

```text
cargo 1.42.1
release: 1.42.1
```

**Comment by ehuss** [comment]
> cargo 1.42.1

This version is quite old, would you be able to use a newer version? The latest release is 1.57.

**Comment by uglyoldbob** [comment]
I upgraded to debian testing, which has cargo 1.56.0. This solved my problem.

**Comment by ehuss** [comment]
Sounds good, I'm going to close this out as fixed.
