### ISSUE TITLE
"File system loop found" upon `cargo build`

### ISSUE THREAD

**Issue by winterqt** [rust-lang/cargo#10213]
### Problem

When running `cargo build`, an error is thrown:

```
Caused by:
  failed to determine the most recently modified file in /path/to/package

Caused by:
  failed to determine list of files in /path/to/package

Caused by:
  File system loop found: /path/to/package/node/tools/node_modules/eslint/node_modules/eslint points to an ancestor /path/to/package/node/tools/node_modules/eslint
```

### Steps

1. Clone [`nodejs/node`](https://github.com/nodejs/node) to a package directory
2. Run `cargo build`

### Notes

This does not occur on Cargo v1.56.0 (I'm experiencing this on 3787309df66b32995f91bbf4d251e17e90fca4af).

### Version

```text
cargo 1.59.0
release: 1.59.0
host: aarch64-apple-darwin
libgit2: 1.3.0 (sys:0.13.25 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:SecureTransport)
os: Mac OS 12.1.0 [64-bit]
```

**Comment by weihanglo** [comment]
This was introduced by the patch #10188

Here is a reproducible script:

```
mkdir eloop && cd eloop
cargo init . --vcs none
mkdir -p a/b/c
ln -s "$PWD/a/b" a/b/c/d
```

Then run `cargo doc`, you will see a similar error:


```
[
    "/Users/me/eloop/Cargo.lock",
    "/Users/me/eloop/Cargo.toml",
    "/Users/me/eloop/_build.rs",
    "/Users/me/eloop/a/b/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e/c/e",
    "/Users/me/eloop/src/main.rs",
],
```

Why cargo before #10188 can succeed to build is that cargo [ignores bad symlinks] when checking it's mtime. Unfortunately #10188 proactively detects and aborts when got a loop symlink. I guess a revert might be fine. 

[ignores bad symlinks]: https://github.com/rust-lang/cargo/blob/3787309df66b32995f91bbf4d251e17e90fca4af/src/cargo/sources/path.rs#L448-L453
