### ISSUE TITLE
unexpected error with `cargo rustdoc` while using both `--document-private-items` and `--output-format json`

### ISSUE THREAD

**Issue by tklebanoff** [rust-lang/cargo#10225]
### Problem

i get an error 
```
error: internal compiler error: unexpected panic

error: Unrecognized option: 'document-private-items'
```

when i try to add --document-private-items to the command. (ie `cargo rustdoc -p my-crate -- --document-private-items --output-format json -Z unstable-options`

note: the following command generates successfully (without --document-private-items):   `cargo rustdoc -p my-crate -- --output-format json -Z unstable-options`

### Version

```
> $ cargo  --version   
cargo 1.57.0-nightly (7fbbf4e8f 2021-10-19)
```

**Comment by ehuss** [comment]
I'm unable to reproduce on any local projects.  `2021-10-19` is quite old for a nightly.  Can you try the latest version?

**Comment by ehuss** [comment]
Without more information, I'm going to close.  If you're able to reproduce on the latest nightly, feel free to reopen.
