### ISSUE TITLE
`bench` does not pass dash-prefixed arguments to binary

### ISSUE THREAD

**Issue by SpriteOvO** [rust-lang/cargo#10228]
### Problem

`cargo bench -- --blah` raises error `Unrecognized option: 'blah'`.
`cargo bench -- -b` raises error `Unrecognized option: 'b'`.
However, `cargo bench -- blah` is okay.

`cargo` still seems to be handling them on its own. The expected behavior is to pass all arguments after " -- " to the binary.

### Steps

1. run `cargo bench -- --blah` or `cargo bench -- -b`.

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:Schannel)
os: Windows 10.0.19042 (Windows 10 Pro) [64-bit]
```

**Comment by ehuss** [comment]
Sorry, maybe I'm confused by what you are trying to illustrate, but I believe this is working as expected.  The test harness has its own argument handling.  You can see the kinds of arguments it takes by running `cargo bench -- --help`.  

If you want to handle arguments yourself, you have to set `harness=false` in Cargo.toml and write your own main function.

**Comment by SpriteOvO** [comment]
@ehuss Sorry I forgot to mention this, I have set `harness=false`.

So in more details:

Cargo.toml
```toml
[package]
name = "bench_bug"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench_example"
harness = false
```

benches/bench_example.rs
```rust
fn main() {
    println!(
        "Bench_example args: {:?}",
        std::env::args().collect::<Vec<String>>()
    );
}
```

(The following binary paths are simplified)

I expect to get output:
```
Bench_example args: ["bench_example.exe", "--blah", "--bench"]
```

But there seems to be no way, I tried:
```
$ cargo bench
Bench_example args: ["bench_example.exe", "--bench"]

$ cargo bench -- blah
Bench_example args: ["bench_example.exe", "blah", "--bench"]

$ cargo bench -- --blah
error: Unrecognized option: 'blah'
error: bench failed
```

I just found a way to make it work:
```
$ cargo bench -- -- --blah
Bench_example args: ["bench_example.exe", "--", "--blah", "--bench"]
```
But you can see a "--" argument. Is this also expected? If so, I may have to manually filter both "--" and "--bench" to get it working with my `#[derive(clap::Parser)]` structure.

**Comment by weihanglo** [comment]
It seems that `Unrecognized option: 'blah'` is [from getopts], which is [used by libtest].
Without specifying a benchmark to run, args after `--` slip into test harness. Running benchmark with `--bench` arg should fix your issue.
 
```
$ cargo bench --bench bench_example -- --blah
    Finished bench [optimized] target(s) in 0.00s
     Running unittests (target/release/deps/bench_example-1e2b3187f40626fe)
Bench_example args: ["target/release/deps/bench_example-1e2b3187f40626fe", "--blah", "--bench"]
```


[from getopts]: https://github.com/rust-lang/getopts/blob/c11eb65097d0dc9fe9ceb351d63c3ac8b5f05e0b/src/lib.rs#L1183
[used by libtest]: https://github.com/rust-lang/rust/blob/e100ec5bc7cd768ec17d75448b29c9ab4a39272b/library/test/Cargo.toml#L11

**Comment by SpriteOvO** [comment]
@weihanglo It works now, thank you very much!

If this is by design, I think we can close this issue.
