### ISSUE TITLE
`cargo test --workspace` does not properly isolate its resolve cache depending on build DAG

### ISSUE THREAD

**Issue by ShadowJonathan** [rust-lang/cargo#10222]
### Problem

While investigating why [ruma/ruma@`2163c1d` (#758)](https://github.com/ruma/ruma/pull/758/commits/2163c1d24cb78079443bfa8b2fa3a72f0acc955b) fails CI, I discovered that, while running `cargo test --workspace` on that commit, crate discovery rules seem to be different than running the same command on the main branch commit https://github.com/ruma/ruma/commit/6b78988d396463000cbced9d4ace931c5db46259.

CI fails at the following spot;

![image](https://user-images.githubusercontent.com/22740616/146840731-1e73ef9a-8caa-46a5-85e5-8bae780d7ef0.png)

At this point, `ruma` should be "known", all sub-crates of ruma depend on the head crate as the main dependency the user pulls when using the crate.

`tokio-stream` should also be known, it is explicitly required in the `ruma` cargo.toml `dev-dependencies`.

---

My best guess for what is happening here is that, since https://github.com/ruma/ruma/pull/758 adds an example to test and check in CI, it becomes the new "head" in the build DAG that cargo resolves when building all elements.

However, when building this DAG, cargo does not properly consider that individual crates would need dev dependencies at this time, and does not properly "isolate" or otherwise note what side-effects the top-compiled crate would have on the resolve cache.

In the end, the tests are performed with the `misterbot` crate's view on the cache, and the crates that the tests depend on are hidden in that view.

### Version

```text
cargo 1.58.0-nightly (294967c53 2021-11-29)
release: 1.58.0
commit-hash: 294967c53f0c70d598fc54ca189313c86c576ea7
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Pop!_OS 21.10 (impish) [64-bit]
```

---

And also tested and confirmed on stable:

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Pop!_OS 21.10 (impish) [64-bit]
```

**Comment by ehuss** [comment]
I believe cargo is working as expected here.  The features that are enabled are unioned across all packages that are currently being built (#4463). To work around that, you need to test the packages individually.

In this case, the `ruma-client` fails to run tests when the `client-api` feature is enabled. The package you are added causes that feature to get enabled.  `cargo test -p ruma-client --features client-api` also fails to run.

**Comment by ShadowJonathan** [comment]
Interesting, before submitting the current version of the bug, I ruled out some false positive fails when compiling without some flags, but I did not test each flag for each package to see if one of them would fail if it was defined, this is probably a problem on our side then, sorry for the confusion.

If this bug pops up again though, I'll reopen this if my original hypothesis was indeed the case.
