### ISSUE TITLE
Cargo can't fetch submodules with ssh urls

### ISSUE THREAD

**Issue by gostkin** [rust-lang/cargo#10220]
### Problem

Tried to add the dependency in the following way:
```
cardano = { package = "cardano-serialization-lib", git = "https://github.com/Emurgo/cardano-serialization-lib.git", branch = "cip30-multiasset-largest-first" }
```
The dependency project has a submodule with such url in `.gitmodules`:`git@github.com:WebAssembly/binaryen.git`
This submodule is public and available on GitHub. However, cargo can't fetch it:
```
Execution failed (exit code 101).
/Users/gostkin/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features
stdout :     Updating git repository `https://github.com/Emurgo/cardano-serialization-lib.git`
    Updating git submodule `git@github.com:WebAssembly/binaryen.git`
error: failed to get `cardano-serialization-lib` as a dependency of package

Caused by:
  failed to load source for dependency `cardano-serialization-lib`

Caused by:
  Unable to update https://github.com/Emurgo/cardano-serialization-lib.git?branch=cip30-multiasset-largest-first

Caused by:
  failed to update submodule `binaryen`

Caused by:
  failed to fetch submodule `binaryen` from git@github.com:WebAssembly/binaryen.git

Caused by:
  failed to authenticate when downloading repository

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  no authentication available

stderr : 
```

**Comment by ehuss** [comment]
It's important to note that Cargo does not support reading OpenSSH configuration or keys. It only supports using ssh-agent. Are you using ssh-agent? There is more information about it here: https://doc.rust-lang.org/cargo/appendix/git-authentication.html#ssh-authentication

**Comment by Eh2406** [comment]
What have you tried?

My recollection is that this is a limitation of `libgit2`, so setting https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli may help.

**Comment by gostkin** [comment]
> What have you tried?
> 
> My recollection is that this is a limitation of `libgit2`, so setting https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli may help.

@Eh2406 net.git-fetch-with-cli doesn't help unfortunately. I see the following note here:
```
Note: Cargo does not support git's shorthand SSH URLs like git@example.com:user/repo.git. Use a full SSH URL like ssh://git@example.com/user/repo.git.
```

Probably that's the reason why cargo can't fetch submodules. The urls are without `ssh://` prefix there

**Comment by ehuss** [comment]
> Probably that's the reason why cargo can't fetch submodules. The urls are without `ssh://` prefix there

Shorthand URLs are specifically supported for submodules. That note is jus about URLs used in `Cargo.toml` or similar.

**Comment by ehuss** [comment]
FWIW, I'm able to fetch with your example dependency.

One thing I would do is run `ssh-add -l` to verify you have the correct key added (one that can authenticate with github.com that is listed in https://github.com/settings/keys).

What kind of keys are you using and what bit size are they?  My only thought is maybe the internal ssh library doesn't support it? Though I would expect a different error.

**Comment by ehuss** [comment]
Without more information, I'm going to close for now.  However, if you're able to provide some more information that can help diagnose the authentication issue, feel free to re-open.  Or, trying the suggested `net.git-fetch-with-cli` might be a solution, which supports more SSH capabilities.

**Comment by ljttl3q04t** [comment]
According to https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
You should try `CARGO_NET_GIT_FETCH_WITH_CLI=true cargo update`
Note:  I'm good with linux but encounter this issue on MacOS
