### ISSUE TITLE
Colliding filenames cause a panic when a build is re-run

### ISSUE THREAD

**Issue by saethlin** [rust-lang/cargo#10231]
### Problem

When cargo emits a warning about output filename collision, running a second build produces a panic inside cargo.

### Steps

Download either one of `chipo-2.1.0` or `paranoia-caller-0.1.0`, run `cargo build` twice. The first run emits a warning, the second panics.

### Possible Solution(s)

Promote the warning to a hard error.

### Notes

This was found browsing crater outputs. Here are the two published crates that produce the error:
https://crater-reports.s3.amazonaws.com/beta-1.58-1/1.57.0/reg/chipo-2.1.0/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.58-1/1.57.0/reg/paranoia-caller-0.1.0/log.txt

### Version

```text
cargo 1.59.0-nightly (fcef61230 2021-12-17)
release: 1.59.0-nightly
commit-hash: fcef61230c3b6213b6b0d233a36ba4ebd1649ec3
commit-date: 2021-12-17
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 20.4.0 [64-bit]
```

**Comment by QiangHeisenberg** [comment]
Did I make a mistake?
I run:
```
git clone https://gitlab.com/jeffrey-xiao/chipo-rs.git
cargo build
cargo build
```
But nothing seems to have happened.
![image](https://user-images.githubusercontent.com/46313511/147379932-82eecd52-b7c6-4a24-8623-6cca74cdc0c6.png)

**Comment by saethlin** [comment]
I found this with crater among the published versions on crates.io. You can use `cargo-download` or in this case the author has made git tags for releases, so `git checkout tags/v2.1.0` will get you the right code.

**Comment by weihanglo** [comment]
After an investigation, this panic exists for a long time since 1.36.0 released. Although it acts like a "hard error" but I don't think we can turn the warning to an error until an actual fix is landed. 
Maybe we can do it in reversed by removing the `assert!`?

**Comment by ehuss** [comment]
It looks like these packages set both `dylib` and `cdylib` crate types.
Cargo can't support that at this time, since they both output the same filename.
I think that specific case can be turned into a hard error now.

In the future, there might be something like #9778 which would allow setting different filenames for things like cdylibs, but it isn't supported now (and might be difficult to add).
