### ISSUE TITLE
Windows OpenSSH ssh-agent not Supported by cargo from rustup

### ISSUE THREAD

**Issue by yodaldevoid** [rust-lang/cargo#10237]
### Problem

Support for the Windows OpenSSH `ssh-agent` was added to `libssh2` with https://github.com/libssh2/libssh2/commit/c998f79384116e9f6633cb69c2731c60d3a442bb and added to `libssh2-sys` with version `0.2.22` (https://github.com/alexcrichton/ssh2-rs/commit/3fe863b41ad4fbe0d78c626d58c16a8c2f000b32). `libssh2-sys 0.2.23` looks to have been included at least since `cargo 1.57.0` based on CI builds.

All that said, the copy of `cargo` pulled down by `rustup` doesn't seem to include a new enough version of `libssh2-sys` to include support for Windows OpenSSH. This can be confirmed by searching the binary for the string `"openssh-ssh-agent"` as this string must be in the binary to be able to talk to the agent. A similar string for Pageant (`"PageantRequest"`) can be find in the binary from `rustup`.

Lastly, building `cargo` from source from the same commit as the binary pulled by `rustup` works fine.

### Possible Solution(s)

There may be a difference between the CI builds and those used for releases. If so, it may be that the version of `libssh2-sys` has been pinned either through `Cargo.lock` or some other means and needs to be updated.

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:Schannel)
os: Windows 10.0.19043 (Windows 10 Pro) [64-bit]
```

**Comment by ehuss** [comment]
I have posted https://github.com/rust-lang/rust/pull/92374 to update it.

**Comment by yodaldevoid** [comment]
Ah, releases use the lock file from the main Rust repo, that makes sense.

Thank you for making the PR.
