### ISSUE TITLE
Warn about `--workspace` usage in workspace root

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/cargo#10246]
### Problem

If I understand the documentation correctly now, `--workspace` is only useful when used in a subdirectory of the workspace to be able to e.g. run the tests of all workspace crates instead of just the crate of the current directory.

It took me a while to realize this though, and I thought that `--workspace` was always required, even when in the top-level workspace directory.

### Proposed Solution

I was wondering if it would make sense to show a low severity warning message when `--workspace` is used from within the top-level workspace directory. Something like:

> Note: Usage of `--workspace` is redundant if used in the top-level workspace directory.

**Comment by epage** [comment]
`--workspace` is only redundant when inside of a virtual workspace (no crate in the workspace manifest).

Personally, I would dislike a warning for this case because this is the type of flag I might have a tool set when running from whatever my current directory is and I would expect it to work without extra noise.

**Comment by bjorn3** [comment]
I believe rust-analyzer unconditionally passes `--workspace` even at the root of a virtual workspace.

**Comment by ehuss** [comment]
I'm going to close, as I don't think we'll be adding this warning.  As mentioned, there are tools that may unconditionally pass it without knowing if it is in the root or not.  Since it is harmless to include the option, I don't think it is particularly necessary to warn about it.

**Comment by Turbo87** [comment]
yep, no worries :)
