### ISSUE TITLE
Cargo should self update

### ISSUE THREAD

**Issue by netroby** [rust-lang/cargo#1025]
Cargo should self update
Shall we put a single command for daily auto update it's self?
Like:
```
cargo self-upgrade
```

will upgrade rust with cargo to latest version.

**Comment by alexcrichton** [comment]
For now I think we're going to stick with `rustup.sh` now that Cargo is installed by default (and packaged with rustc itself). If we do grow the need to release new versions rapidly we can evolve this over time, but for now our installation story is similar to that of `rustc`, which is that you need to install/update elsewhere.

**Comment by vors** [comment]
For anybody who come here from google, at the moment the correct way to update toolchain is

```
rustup update 
```

**Comment by 00imvj00** [comment]
cargo not updating with this.

**Comment by vors** [comment]
hm, so `cargo` is not part of toolchain?
