### ISSUE TITLE
Docs that link to rustc are broken

### ISSUE THREAD

**Issue by Dispersia** [rust-lang/cargo#10257]
### Problem

 Hello, it seems that any doc that links to rustc currently shows a 404, as an example, `-C opt-level flag` under:
 https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/profiles.md

 I'm not sure if rustc used to be submoduled, or this docs were moved because there are a lot accross the /reference that point to this location.

Sorry if not really a "bug", just didn't know what to report it under

**Comment by ehuss** [comment]
That's to be expected.  Those source files get processed and published in a book here: https://doc.rust-lang.org/cargo/
Viewing the raw source on GitHub won't work since it hasn't been compiled.

**Comment by ehuss** [comment]
I'm going to close, as this is just the nature of viewing raw source files on github.
