### ISSUE TITLE
Allow Main Branch Option with `cargo new`

### ISSUE THREAD

**Issue by reskin89** [rust-lang/cargo#10261]
### Problem

When running `cargo new` there is no option for default main branch.  Currently a git repository is initialized with a branch `master`.  Current trends are moving away from using the term `master` in favor of `main` or `primary`

### Proposed Solution

when using `cargo new` the git repository should be initialized with `main` instead of `master` as the initial/default branch, and potentially adding a switch to allow the user to define the branch name.

**Comment by Eh2406** [comment]
> `cargo init` should use the default branch you have configured in the global git configuration. You can update that with `git config --global init.defaultBranch main`

from https://github.com/rust-lang/cargo/issues/9716#issuecomment-885327037 and closing as a dup of that.
