### ISSUE TITLE
Which library does the progress bar depend on in cargo?

### ISSUE THREAD

**Issue by JesseAtSZ** [rust-lang/cargo#10260]
### Problem

Which library does the progress bar depend on in cargo? I want to add a progress bar to my project, so I want to learn from it.

**Comment by weihanglo** [comment]
Cargo got its home-made progress bar [here](https://github.com/rust-lang/cargo/blob/358e79fe56fe374649275ca7aebaafd57ade0e8d/src/cargo/util/progress.rs).

There are many other progress bar crates like [indicatif] and [pbr] to named a few.

[indicatif]: https://crates.io/crates/indicatif
[pbr]: https://crates.io/crates/pbr

**Comment by weihanglo** [comment]
Friendly remind that you can ask questions on [the user forum]. People there usually have great idea with this kind of topics.

[the user forum]: https://users.rust-lang.org/

**Comment by alexcrichton** [comment]
I think the question here is answered, so I'm going to close this as well.
