### ISSUE TITLE
"cargo update" fails on macos M1

### ISSUE THREAD

**Issue by ericcurtin** [rust-lang/cargo#10263]
### Problem

When running

$ cargo update
error: could not find `Cargo.toml` in `/Users/username` or any parent directory

it fails

### Steps

1. brew install rust
2. cargo install alacritty
3. cargo update

**Comment by ericcurtin** [comment]
Installing via:

`curl https://sh.rustup.rs -sSf | sh`

gives the same result.

**Comment by weihanglo** [comment]
Are you trying to update alacritty via `cargo update`? If so, it is not what `cargo update` designed to do. According to The Cargo Book, [`cargo update`] is for updating dependencies in a cargo package (a rust project controlled by cargo with a Cargo.toml file). `cargo update` **cannot** update any binary installed via `cargo install`.

To update binaries you installed, taking alacritty for example, run `cargo install alacritty` is sufficient to get the latest version of alacritty on crates.io.

Ref: [`cargo update`], [`crago install`]

[`crago install`]: https://doc.rust-lang.org/cargo/commands/cargo-install.html]

[`cargo update`]: https://doc.rust-lang.org/cargo/commands/cargo-update.html

**Comment by ericcurtin** [comment]
Thanks
