### ISSUE TITLE
Want method to determine publish date offline

### ISSUE THREAD

**Issue by sdroege** [rust-lang/cargo#10285]
### Problem

The tar files created by `cargo package` (and in extension `cargo publish`) have bogus file times, usually somewhere around the years 1970-1973.

### Steps

1. `cargo init`
2. `cargo package`
3. `tar fvzl target/package/foo.crate`

```
-rw-r--r-- 0/0             554 1973-11-29 23:33 foo-0.1.0/.gitignore
-rw-r--r-- 0/0             148 1970-01-01 02:00 foo-0.1.0/Cargo.lock
-rw-r--r-- 0/0             557 1970-01-01 02:00 foo-0.1.0/Cargo.toml
-rw-r--r-- 0/0             173 1973-11-29 23:33 foo-0.1.0/Cargo.toml.orig
-rw-r--r-- 0/0              45 1973-11-29 23:33 foo-0.1.0/src/main.rs
```

### Version

```text
This was a problem in earlier versions too

cargo 1.58.0 (7f08ace4f 2021-11-24)
release: 1.58.0
commit-hash: 7f08ace4f1305de7f3b1b0e2f765911957226bd4
commit-date: 2021-11-24
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Debian unstable (sid) [64-bit]
```

**Comment by Eh2406** [comment]
What problem is this causing?

**Comment by sdroege** [comment]
Or said differently, is there any good reason for not writing valid dates?

**Comment by alexcrichton** [comment]
This is intentional at the request to make the tarballs more deterministic. Currently the best way to figure out the publish/release date would be to query the crates.io API.

**Comment by sdroege** [comment]
That doesn't allow offline builds though

**Comment by Eh2406** [comment]
You can look at the commit that added the version to the index https://github.com/rust-lang/crates.io-index

**Comment by sdroege** [comment]
That also requires getting that information over the network. Ideally I'd have some information inside the crate that allows to infer that.

**Comment by epage** [comment]
@sdroege why is an accurate release date important for GST plugins?    Should the burden for that be shifted to the plugins themselves?   That can be handled as part of the release process (e.g. `cargo-release` can handle inserting a date).  I'm also assuming from this, that these plugins are then being published to crates.io and that version is then being distributed through another means.  Could the repos be used instead, taking with it the git information?

For me, with the problems laid out, the alternatives available, and the size of the problem, I'm not seeing that this is something we should change.  As such, I'm proposing to the cargo team that we close this.  Others might not agree or there could be more information that makes us change our mind.  Even if we close this, it can always be re-visited in the future when more information becomes available.

**Comment by sdroege** [comment]
> why is an accurate release date important for GST plugins

It's not *required*, but it's metadata that is stored together with a release.

----

It would be possible to do this as part of the release process, however that requires people to do additional steps apart from `cargo publish` that could be easily forgotten, i.e. external tools or manual steps are needed. That's the approach I'm planning to implement though if I ever got time for it.

I'm still don't understand why it's so hard and undesirable to store the files as is inside the tarball but instead go out of your way to set all the file's metadata to a timestamp of 0. The argument of "more deterministic tarballs" seems misguided because if the file's mtime changes you probably also want a *different* tarball? Something has changed after all.

Anyway, let's close this. I don't have the energy to argue about this and it's also not the most important thing missing from cargo either.
