### ISSUE TITLE
`cargo:rustc-link-arg-bin` may not be provided multiple times in build script

### ISSUE THREAD

**Issue by piegamesde** [rust-lang/cargo#10301]
### Problem

One can use `cargo:rustc-link-arg` multiple times within a `build.rs` to set multiple linker arguments. However, when this needs to be done per binary, i.e. `cargo:rustc-link-arg-bin` it does not work: using it more than once will produce zero arguments instead (this is intriguing, the more obvious failure mode would be to only use the last or first or something).

Furthermore, mixing `cargo:rustc-link-arg` and `cargo:rustc-link-arg-bin` gives weird results depending on the combination. This may be related or not, I did not investigate any further.

### Steps

1. Have a crate with build script
2. `println!("cargo:rustc-link-arg-bin=main=-Tfoo.x");`
3. `println!("cargo:rustc-link-arg-bin=main=-Tbar.x");`

### Notes

I'm compiling for a custom, modified `riscv32im-unknown-none-elf` target (using `riscv32i-unknown-none-elf` as base and added `m`).

### Version

```text
cargo 1.59.0-nightly (fcef61230 2021-12-17)
release: 1.59.0-nightly
commit-hash: fcef61230c3b6213b6b0d233a36ba4ebd1649ec3
commit-date: 2021-12-17
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Arch Linux [64-bit]
```
```

**Comment by ehuss** [comment]
Can you say more about why it appears to not be passing the arguments? Can you show a complete example?

If I try your example (with `main` replaced with the binary name), I get:

```
     Running `rustc --crate-name foo ..... -C link-arg=-Tfoo.x -C link-arg=-Tbar.x`
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" ..... "-Wl,-zrelro,-znow" "-nodefaultlibs" "-Tfoo.x" "-Tbar.x"
  = note: /usr/bin/ld: cannot open linker script file foo.x: No such file or directory
```

Here it is shown that the `-T` args are being passed to the linker ("cc").

**Comment by piegamesde** [comment]
Wow. I suddenly cannot reproduce the issue anymore; everything works as it should now. I don't remember having changed anything significant, and my file system history did not reveal anything else of interest.

I'm going to blame some caching issue or an omitted `rerun-if-changed` and reopen if it ever reappears (fingers crossed). Sorry for the noise.
