### ISSUE TITLE
Specifying the manifest path ignores .cargo/config.toml

### ISSUE THREAD

**Issue by allsey87** [rust-lang/cargo#10302]
### Problem

When specifying `--manifest-path=dir/Cargo.toml` the `.cargo/config.toml` files appear to be ignored. It doesn't seem to matter whether `.cargo/config.toml` is (e.g., in my crates, workspace, or the directory from which I am running Cargo). It is always ignored.

### Steps

1. Place some configuration in a `.cargo/config.toml` file. For example, I have:
```toml
[build]
target = "wasm32-unknown-unknown"
```
So that Cargo compiles to WebAssembly by default.
2. Run `cargo build --manifest-path=path/to/Cargo.toml`
3. Observe that instead of WebAssembly, Cargo is producing shared libraries (i.e., `.so` on Linux)

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by ehuss** [comment]
It should, unless something else is overriding it.  Can you show a complete example?  For example:

```
~/Temp> mkdir foo
~/Temp> cd foo
~/Temp/foo> mkdir .cargo
~/Temp/foo> cat > .cargo/config.toml << EOF
> [build]
target = "wasm32-unknown-unknown"
> EOF
~/Temp/foo> cargo new myproj
     Created binary (application) `myproj` package
~/Temp/foo> cargo build --manifest-path myproj/Cargo.toml
   Compiling myproj v0.1.0 (/Users/eric/Temp/foo/myproj)
    Finished dev [unoptimized + debuginfo] target(s) in 1.42s
~/Temp/foo> ls -al myproj/target/wasm32-unknown-unknown/debug/myproj.wasm
-rwxr-xr-x  1 eric  staff  1664827 Jan 17 08:40 myproj/target/wasm32-unknown-unknown/debug/myproj.wasm
```
