### ISSUE TITLE
Incorrect dependency check causing unnecessary cross-platform rebuilds

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [rust-lang/cargo#10315]
### Problem

On a build environment that cross compiles to several platforms, Cargo rebuilds all crates all the time even when Cargo.lock and the cargo registry are being cached between builds.

Running with CARGO_LOG=cargo::core::compiler::fingerprint=trace shows an issue where Cargo tries to fetch the mtime of a given architecture not from the architecture-specific build directory, but from the host directory.

For instance, for an android build, this results in a flurry of errors such as 
```
[2022-01-21T09:49:20Z DEBUG cargo::core::compiler::fingerprint] failed to get mtime of "/home/jenkins/workspace/hello/target/debug/build/arrayvec-8ca56e3564ea50ba/build_script_build-8ca56e3564ea50ba": failed to stat `/home/jenkins/workspace/hello/target/debug/build/arrayvec-8ca56e3564ea50ba/build_script_build-8ca56e3564ea50ba`
```

(The expected behaviour would have been not to try to stat the mtime from the "default" target directory

`/home/jenkins/workspace/hello/target/debug/build/arrayvec-8ca56e3564ea50ba/build_script_build-8ca56e3564ea50ba/`

but from the architecture-specific directory:

`/home/jenkins/workspace/hello/target/armv7-linux-androideabi/debug/build/arrayvec-8ca56e3564ea50ba/build_script_build-8ca56e3564ea50ba/`

 in this case).

In turn, this makes Cargo incorrectly label the files as stale when in fact they are up-to-date. From function `check_filesystem`:
```
        let mut mtimes = HashMap::new();

        // Get the `mtime` of all outputs. Optionally update their mtime
        // afterwards based on the `mtime_on_use` flag. Afterwards we want the
        // minimum mtime as it's the one we'll be comparing to inputs and
        // dependencies.
        for output in self.outputs.iter() {
            let mtime = match paths::mtime(output) {
                Ok(mtime) => mtime,

                // This path failed to report its `mtime`. It probably doesn't
                // exists, so leave ourselves as stale and bail out.
                Err(e) => {
                    debug!("failed to get mtime of {:?}: {}", output, e);
                    return Ok(());
                }
            };
            assert!(mtimes.insert(output.clone(), mtime).is_none());
        }
```
resulting in much greater build times than necessary.

### Steps

1. Have a cross-platform build on a Jenkins build server

2. After checking out code from source control, before the build, symlink relevant target directories to point to the old build to be used as cache for the new one:

```
	# user dependent target dir so we don't keep rebuilding
	# *everything* when swapping across sudo/nonsudo envs
	rm -rf target  # remove symlink or dir
	rm -rf ~/.cargo/registry
	mkdir -p ~/build_cache/target_`whoami`_$(CROSSCOMPILE_TARGET)
	ln -sf ~/build_cache/target_`whoami`_$(CROSSCOMPILE_TARGET) target
	# we also cache Cargo.lock to avoid unnecessary crate rebuilds
	echo -n "" >> target/Cargo.lock
	ln -sf target/Cargo.lock .
	# finally, use the appropriate architecture-dependent cargo registry
	mkdir -p ~/.cargo/registry_$(CROSSCOMPILE_TARGET)
	ln -sf ~/.cargo/registry_$(CROSSCOMPILE_TARGET) ~/.cargo/registry
	chown `ls -l Makefile |awk '{print $3":"$4}'` target
```

3. Run the build with CARGO_LOG=cargo::core::compiler::fingerprint=trace

Observe that rather than caching previously built crates, all builds rebuild everything instead of just those bits that need rebuilding based on the last build.

### Possible Solution(s)

Ensure dependencies are checked against the architecture-specific target directory.

### Version

```text
Occurs for cargo 1.60.0-nightly (95bb3c92b 2022-01-18)
```

**Comment by alexcrichton** [comment]
Would it be possible for you to reduce the reproduction steps to things only involving Cargo and/or perhaps a script? Step 1 of having a Jenkins build server I have no idea how to get started on myself.

What's likely happening here is that build scripts, built for the host, may have somewhat tweaked settings across compilations such as opt-level or features enabled. It's likely that your compilations are colliding on this filename and is what's causing reubilds. I can't say for certain, however, since I  don't have the reproduction in front of me to look att.

**Comment by ehuss** [comment]
Without a reproduction that we can try, I don't think we'll be able to help.  I'm going to close, as there isn't enough information here.  However, if you're able to put together a self-contained reproduction, feel free to reopen!

**Comment by marcbrevoort-cyberhive** [comment]
It's not a trivial setup as it involves a cross-platform build and a build server. However I think the main clue would be in the path generation where `target/debug/` being generated for cross-compile caching rather than `target/{triple}/debug/`. This is completely understandable considering cross-compiling and caching were likely implemented separately.

Also, of course since, this is just a cache path, the main effect is that files with the cache fingerprint aren't found in that directory, so the build runs otherwise normally (although operating as if nothing was built yet, and hence a lot slower than it needs to).

**Comment by ehuss** [comment]
It is normal when cross-compiling to not have a target-specific directory for host crates like build scripts, which go in the `target/debug/build` directory. It's hard to say without the full logs, but I would guess that `arrayvec` is probably getting built with different features or something like that.  There are quite a few differences that can result in the file being missing.

**Comment by marcbrevoort-cyberhive** [comment]
Looking at my build scripts today, I wonder if it possible that the "full rebuild" is a result of the `CARGO_INCREMENTAL=0` flag?
This flag is a pre-requisite for code coverage tests. If so, it would be a bit ironic that the bottleneck is in re-building all the existing crates, since **their** coverage metrics wouldn't be all that interesting for the typical developer.
