### ISSUE TITLE
cargo fix reports false positive "function is never used"

### ISSUE THREAD

**Issue by tisonkun** [rust-lang/cargo#10312]
### Problem

In crate https://github.com/tisonkun/reactivex, the function `just` is used both as `pub use` and in tests. However, when running `cargo build` or `cargo fix`, it reports:

```
warning: function is never used: `just`
  --> src/flowable/just.rs:17:8
   |
17 | pub fn just<T>(t: T) -> FlowableJust<T> {
   |        ^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```

### Steps

1. `git clone https://github.com/tisonkun/reactivex`
2. `cargo fix`

### Notes

* [Definition (`pub fn`)](https://github.com/tisonkun/reactivex/blob/d1989abd5cdb1f15a25f6735e6ea1f6f72e34e0a/src/flowable/just.rs#L17-L19)
* [`pub use just::just;`](https://github.com/tisonkun/reactivex/blob/d1989abd5cdb1f15a25f6735e6ea1f6f72e34e0a/src/flowable/mod.rs#L17)
* [Used in tests](https://github.com/tisonkun/reactivex/blob/d1989abd5cdb1f15a25f6735e6ea1f6f72e34e0a/src/flowable/just.rs#L34-L42)

### Version

```text
cargo 1.58.0-nightly (40dc28175 2021-12-06)
release: 1.58.0
commit-hash: 40dc281755137ee804bc9b3b08e782773b726e44
commit-date: 2021-12-06
host: x86_64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.64.1 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 10.15.7 [64-bit]
```

**Comment by jmesmon** [comment]
This is likely because in `reactivex`'s `lib.rs`, none of the `mod`s are `pub` (and no `pub use`'s exist). This means there's no way for other crates to call `just`, resulting it in being marked as unused when not building tests. In fact, it looks like there is no public API for the crate (you can check this by looking at `cargo doc`'s output)

**Comment by tisonkun** [comment]
@jmesmon thanks for your information! I should publish the function in `lib.rs` :)
