### ISSUE TITLE
[workspace issue] Error: invalid register after refactor under workspace

### ISSUE THREAD

**Issue by PeterWrighten** [rust-lang/cargo#10314]
### Problem

The same issue as [rust #93151](https://github.com/rust-lang/rust/issues/93151).

When I want to refactor an [OS project](https://github.com/rcore-os/rCore-Tutorial-v3/tree/ch2) with Cargo workshop, which its original rust code is not encapsulated under cargo workspace but could promise successful run , compiler reported 'invalid register' issue as follow: 

(My code is [here](https://github.com/PeterWrighten/OperatingSystem/tree/chap2/peter_batch_os), refactored by Cargo workspace) 

```shell
% cargo build
   Compiling user_lib v0.1.0 (/Users/apple/GitHub/OperatingSystem/peter_batch_os/user)
error: invalid register `x10`: unknown register
 --> user/src/syscall.rs:9:13
  |
9 |             inlateout("x10") args[0] => ret,
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: invalid register `x11`: unknown register
  --> user/src/syscall.rs:10:13
   |
10 |             in("x11") args[1],
   |             ^^^^^^^^^^^^^^^^^

error: invalid register `x12`: unknown register
  --> user/src/syscall.rs:11:13
   |
11 |             in("x12") args[2],
   |             ^^^^^^^^^^^^^^^^^

error: invalid register `x17`: unknown register
  --> user/src/syscall.rs:12:13
   |
12 |             in("x17") id
   |             ^^^^^^^^^^^^

error: could not compile `user_lib` due to 4 previous errors
```

My source code [here](https://github.com/PeterWrighten/OperatingSystem/blob/chap2/peter_batch_os/user/src/syscall.rs) has added ```unsafe``` statement and ```asm``` mod, target triple is also modified to "riscv64gc-unknown-none-elf", but it seems that stil could't work under cargo workspace :(

### Version

cargo 1.60.0-nightly (2022-01-18)

**Comment by PeterWrighten** [comment]
Now it works well by changing rustflags, but still cound not guarantee its performance when ```.cargo``` config file is not under the root. I want to know how could I do to work it out just depended by ```.cargo``` file under members' crate.

**Comment by bjorn3** [comment]
`.cargo/config.toml` is read for the current directory and all of it's parent directories. It isn't necessarily read for the specific workspace member you are trying to build if you are not in it's directory.

**Comment by PeterWrighten** [comment]
> `.cargo/config.toml` is read for the current directory and all of it's parent directories. It isn't necessarily read for the specific workspace member you are trying to build if you are not in it's directory.

But actually, in my case, if `.cargo/config.toml` is just in members' crate (In my code, it is `./user/.cargo/config.toml`) but not in `peter_batch_os` directory, it couldn't be built at all...

**Comment by ehuss** [comment]
I'm going to close as this sounds like an issue with config file search order. Those issues are tracked in #9769. There are a few other workarounds, some of them unstable (such as [per-package-target](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#per-package-target) and [profile rustflags](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option)).
