### ISSUE TITLE
cargo seems to launch excessive number of jobs when building veloren

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#10320]
### Problem

I have a dual core system (2 cores, 2 threads each), so usually cargo launches 4 jobs per `cargo build`.

When building `veloren` I found that cargo sometimes launched up to 7 jobs at a time,  many of them being `(build)` ones:
```` Building [===================>     ] 658/803: spirv_cross(build), veloren-voxygen-dynlib, libsqlite3-sys(build), libsqlite3-sys(build), wgpu-types, pistoncore-input, tracing-subscriber````

When I try to explicitly force a single job `cargo build --release -j 1` it looked like it still launched two:
``` Building [==================>      ] 642/803: shaderc-sys(build), spirv_cross(build) ```

I don't think I have seen this for any other projects yet.

### Steps

1) git clone https://gitlab.com/veloren/veloren.git
2) cd veloren
3) cargo build --release -j 1 

### Version

```text
cargo 1.59.0-nightly (fcef61230 2021-12-17)
release: 1.59.0-nightly
commit-hash: fcef61230c3b6213b6b0d233a36ba4ebd1649ec3
commit-date: 2021-12-17
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Manjaro 21.2.1 (Qonos) [64-bit]


veloren uses `nightly-2021-12-19` atm
```

**Comment by ehuss** [comment]
I think this is the same as #7689, is it not?  This is expected behavior with build scripts using a jobserver. Those extra jobs aren't performing any actual work.

**Comment by matthiaskrgr** [comment]
Ah oops, looks like it is the same, sorry about that. :sweat_smile: 
I'm wondering "aren't performing any actual work" what does that mean?
Isn't cargo executing the build script then?

**Comment by matthiaskrgr** [comment]
When we run a build script that compiles some C code, does `cc` also takes cargos job count into account when launching c-compiler instances (as in `make -j x`)

**Comment by bjorn3** [comment]
Exactly! Cargo implements the make jobserver protocol.

**Comment by ehuss** [comment]
> I'm wondering "aren't performing any actual work" what does that mean?

The build script process is live, but it is blocking waiting for a token.

**Comment by ehuss** [comment]
I'm going to close as I believe this is the same as #7689.
