### ISSUE TITLE
signal: 7, SIGBUS: access to undefined memory

### ISSUE THREAD

**Issue by joelnet** [rust-lang/cargo#10359]
### Problem

When running `anchor test` I am getting the following error message:

```
BPF SDK: /home/joel/.local/share/solana/install/releases/1.9.5/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
error: process didn't exit successfully: `rustc -vV` (signal: 7, SIGBUS: access to undefined memory)
```

### Steps

1. cargo install --git https://github.com/project-serum/anchor anchor-cli --locked
2. anchor init myepicproject --javascript
3. cd myepicproject
4. anchor test

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 21.10 (impish) [64-bit]
```

**Comment by Eh2406** [comment]
There are plenty of bugs in cargo and we are happy to work on them. But we are not responsible for all code ever built with our tool. Can you show some work here? What evidence led you to think this was a bug in cargo, as opposed to a bug in anchor or solana? When we have minimized the example to something wrong with Cargo, we will be happy to help!

**Comment by joelnet** [comment]
Hello, Thanks for responding!

When I run the following command:

```bash
cargo +bpf build --target bpfel-unknown-unknown --release
```

I am receiving the following error message:

```
error: process didn't exit successfully: `rustc -vV` (signal: 7, SIGBUS: access to undefined memory)
```

I am new to rust and cargo and wasn't able to find anything with a google search, so I am lost as to where to look next.

Thanks for your help!

**Comment by ehuss** [comment]
The `cargo +bpf` part means it is running a custom build of Rust, presumably with `bpfel-unknown-unknown` support.  I'm guessing this is part of solana, so I would contact [them](https://github.com/solana-labs/solana).  I don't know anything about their setup or what kind of custom toolchain they are building.

**Comment by joelnet** [comment]
Ok thank you!

**Comment by joelnet** [comment]
For those curious, I was able to solve this issue my erasing the solana cache.

```bash
rm -rf ~/.cache/solana/v1.21/
```

**Comment by SkyYap** [comment]
Hi @joelnet,

I run `anchor test` and it shows the same issue. I tried using your `rm -rf ~/.cache/solana/v1.21/` but still it doesn't work.

BPF SDK: /root/.local/share/solana/install/releases/1.10.32/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
error: process didn't exit successfully: `rustc -vV` (signal: 7, SIGBUS: access to undefined memory)

Version:
`rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5`
