### ISSUE TITLE
2 dependencies of the same name - "multiple definitions" issue

### ISSUE THREAD

**Issue by hahnbeelee** [rust-lang/cargo#10355]
### Problem

On my Mac this Cargo.toml works fine: (emphasis on the 2 versions of tree-sitter)
```
[package]
name = "parser"
version = "0.1.0"
authors = ["Mintlify"]
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = { package = "tree-sitter", version = "0.20.2" }
tree-sitter-old = { package = "tree-sitter", version = "0.19.5" }
tree-sitter-java = "0.19.0"
tree-sitter-javascript = "0.20"
tree-sitter-typescript = "0.20.0"
tree-sitter-python = "0.19.1"
serde = "1.0.133"
serde_json = "1.0.74"
serde_derive = "1.0.133"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]

[build-dependencies]
cc="*"

```
However, once I push this onto Heroku (the cargo version is defined below) It doesn't successfully compile because of several "multiple definition of insert-function-name" errors.

### Steps

1. Have 2 dependencies that are the same, but different versions & named differently
2. Compile

### Possible Solution(s)

Rustflags? `--allow-multiple-definitions` ? I tried this but wasn't able to find clear directions as to where and how I need to place these flags. Would it be inside the `Cargo.toml`?

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
       release: 1.58.0
       commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
       commit-date: 2022-01-19
       host: x86_64-unknown-linux-gnu
       libgit2: 1.3.0 (sys:0.13.23 vendored)
       libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
       os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by weihanglo** [comment]
If it is related to linker arguments, configuring rustflags in `.cargo/config.toml` under your project root might help.

```toml
# ⚠️ Haven't yet tested it.
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=--allow-multiple-definition"]
```

Refs: 

- https://doc.rust-lang.org/rustc/codegen-options/index.html#link-arg
- https://doc.rust-lang.org/cargo/reference/config.html#targettriplerustflags

**Comment by ehuss** [comment]
I'm going to close per the comment at https://github.com/rust-lang/cargo/issues/10355#issuecomment-1030565775.  I believe this is due to tree-sitter using a C library.  C libraries don't work the same as Rust libraries, as Cargo will handle name mangling to avoid duplicates, but C libraries won't get that support.  That is a bit out of scope for cargo.  The tree-sitter library should actually be defining the [links](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) value to prevent one from trying to link multiple copies.
