### ISSUE TITLE
rust 1.58.1 with toolchain override breaks cargo

### ISSUE THREAD

**Issue by saintdev** [rust-lang/cargo#10366]
### Problem

If a workspace has a toolchain override for the current stable version: 1.58.1, cargo fails with `error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.58.1-x86_64-unknown-linux-gnu' toolchain`

### Steps

1. rustup install 1.58.1
2. cargo new bug-test
3. cd bug-test
4. rustup override set 1.58.1
5. cargo --version

### Possible Solution(s)

This is possibly because the released version of cargo included in the 1.58.1 toolchain is 1.58.0

### Notes

This also happens with file-based toolchain overrides such as `rust-toolchain` or `rust-toolchain.toml` files.

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Solus 4.3 (fortitude) [64-bit]
```

**Comment by ehuss** [comment]
Hm, unfortunately I'm unable to reproduce the issue.  Can you try to uninstall the `1.58.1` toolchain and try again?  I'm wondering if the installation got corrupted somehow.  Can you also provide the version from `rustup --version`?

**Comment by saintdev** [comment]
> Hm, unfortunately I'm unable to reproduce the issue. Can you try to uninstall the `1.58.1` toolchain and try again? I'm wondering if the installation got corrupted somehow.

A corrupted install was the first thought I had too, so reinstalling was the first thing I did. But I just did it again just in case and it's fine now.

 Can you also provide the version from `rustup --version`?

Included, just in case.
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.58.1 (db9d1b20b 2022-01-20)`
```

**Comment by ehuss** [comment]
Glad you got it working!  

One thing to be careful of when installing toolchains is that rustup does not support more than one install running concurrently. That will typically corrupt it.  If you have an editor running in the background with rust-analyzer or something like that, and you install in another shell, they can conflict with one another.

**Comment by saintdev** [comment]
Ahh, I did have an editor with rust-analyzer running at the time. So that might have been it. Thanks for the tip!
