### ISSUE TITLE
cargo metadata fails due to `munmap_chunk(): invalid pointer`

### ISSUE THREAD

**Issue by YoshieraHuang** [rust-lang/cargo#10393]
### Problem

Related: https://github.com/rust-analyzer/rust-analyzer/issues/11485
`cargo metadata --format-version 1 --manifest-path /home/yoshiera/dynx/Cargo.toml --filter-platform x86_64-unknown-linux-gnu` fails. Here is the output:
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  munmap_chunk(): invalid pointer
```

However, the command ``rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` works.

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: OracleLinux 35.0.0 [64-bit]
```

**Comment by weihanglo** [comment]
Haven't dug it deep, but I doubt that this is an error from previous build cache. [Here is the code where the error is emitted](https://github.com/rust-lang/cargo/blob/f01b232bc7f4d94f0c4603930a5a96277715eb8c/src/cargo/core/compiler/build_context/target_info.rs#L185-L187).

Clean the build cache might fix it. Could you run `cargo clean` and try again?

**Comment by YoshieraHuang** [comment]
> Haven't dug it deep, but I doubt that this is an error from previous build cache. [Here is the code where the error is emitted](https://github.com/rust-lang/cargo/blob/f01b232bc7f4d94f0c4603930a5a96277715eb8c/src/cargo/core/compiler/build_context/target_info.rs#L185-L187).
> 
> Clean the build cache might fix it. Could you run `cargo clean` and try again?

Ok. It works well after cleaning the cache. Thank you!
