### ISSUE TITLE
Unable to get packages from source (failed to download `solana-program v1.9.6`)

### ISSUE THREAD

**Issue by Gogotchuri** [rust-lang/cargo#10390]
### Problem

While trying to build a project initialized with [anchor](https://project-serum.github.io/anchor/getting-started/introduction.html) I get the following error. I was trying to search and deduce solution, I was not successful.
When I run *cargo build* from project root, I am getting error written below.
I am not sure what kind of additional information I should provide, give me instructions if necessary and I'll provide the additional info.

P.S. I am posting this here, since output suggested so. 

## Error Output
error: failed to download `solana-program v1.9.6`
Caused by:
  unable to get packages from source

Caused by:
  failed to find solana-program v1.9.6 in path source
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note: cargo 1.58.0 (f01b232bc 2022-01-19)

### Steps

- Installed solana 1.9.6 : *sh -c "$(curl -sSfL https://release.solana.com/v1.9.6/install)"*
- Installed anchor : *cargo install --git https://github.com/project-serum/anchor --tag v0.21.0 anchor-cli --locked*
- initialized project using: *anchor init <name>*

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Manjaro 21.2.3 (Qonos) [64-bit]
```

**Comment by ehuss** [comment]
I'm guessing the registry cache has gotten corrupted somehow.  I might suggest just deleting it.  It is located at `$CARGO_HOME/registry` where `$CARGO_HOME` is usually `$HOME/.cargo`.
