### ISSUE TITLE
Add `default` features for each [[bin]]

### ISSUE THREAD

**Issue by Icelk** [rust-lang/cargo#10409]
### Problem

When adding [[bin]] entries to a `Cargo.toml`, you can specify required dependencies, but not additional "recommended", default features.

### Proposed Solution

Add a key, namely `default-features` to the [[bin]] sections in `Cargo.toml`.
Both the `dependencies.default` and this new key would be applied. If `--no-default-features` is passed, both declarations are ignored.

**Comment by weihanglo** [comment]
Sorry, I don't get it. Where can I specify required dependencies for a `[[bin]]` target? Cannot find any relevant doc in [1.58.1 Cargo Guide](https://doc.rust-lang.org/1.58.1/cargo/reference/cargo-targets.html). Only found [an RFC](https://github.com/rust-lang/rfcs/pull/2887) still in discussion.

Presumably you want to **build the binary without specifying features in CLI**, there is a similar feature request you might be interested in, which proposes to enable required features automatically: https://github.com/rust-lang/cargo/issues/4663

**Comment by Icelk** [comment]
That issue is about enabling required dependencies. I’m talking about “recommended”, default dependencies, as those in `dependencies.default`. You can currently supply required dependencies per bin in `<bin name>.required.features`.
See [the guide on the Cargo.toml format](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target).

**Comment by weihanglo** [comment]
Sorry @Icelk, I've searched the key `dependencies.default` and still couldn't find such key in either 1.58.1 Cargo Guide or the link you provided. I might miss something important. Can you provide a screenshot or else to point out where it is?

Also, I am a bit confused. Is this issue concerning **features** or **dependencies**? They are not interchangeable terms in Cargo.toml. AFAIK, a target like `[[bin]]`  only has a `required-features` field at this moment.

---

Here is my bold guess about what you mean by "recommended". Correct me if I am wrong.

```toml
# ...
[[bin]]
name = "foo"
default-features = ["serde", "log"]
```

In Cargo.toml, there is a bin target `foo` with the proposed `default-features` field, so when one tries to `cargo build --bin foo`, the `serde` and `log` features are on by default unless `--no-default-features` is also passed.

Is this what in your mind?

**Comment by Icelk** [comment]
Precisely!
I’m sorry, I of course mean `features.default`.

As you mentioned, one could specify both dependencies and other features in the `<bin>.default-features` field, just as is possible in `features.default`.

**Comment by weihanglo** [comment]
Discussion in <https://github.com/rust-lang/cargo/issues/1982> cover some of scenarios here. <https://github.com/rust-lang/rfcs/pull/3374> is an attempt to resolve this as well.

**Comment by weihanglo** [comment]
Triage: after a re-read. This is covered by #1982 and <https://github.com/rust-lang/rfcs/pull/3374>, especially the latter that automatically enabling features for target requested. Let's continue discussing there. Thank you for your report :)
