### ISSUE TITLE
cargo list not showing my installed command

### ISSUE THREAD

**Issue by FrankC01** [rust-lang/cargo#10403]
### Problem

From my package folder I run
`cargo install cargo-solana --path .`

It installs, I test it elsewhere.... everything is hunky dory. However; when I run:

`cargo --list` I see
```bash
    search               Search packages in crates.io
    solana
    t                    alias: test
```

My command description is blank (as apposed to the surrounding commands

### Steps

1. `git clone https://github.com/FrankC01/cargo-solana`
2. `cd cargo-solana`
3. `cargo install cargo-solana --path .`
4. `cargo --list`

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.77.0 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 12.2.1 [64-bit]
```

**Comment by weihanglo** [comment]
Thank for the report! Unluckily, cargo doesn't know about what and how to display the description of external commands. Even `cargo clippy` and `cargo fmt` [are hardcoded][hardcoded]. There was [an attempt] to fix this issue, and Alex explained the situation very clear, 

_"...we'll want to look for a solution that both works and satisfies the constraints of maintainability in Cargo."_

It would be great if you have a viable solution to share! 😄

[hardcoded]: https://github.com/rust-lang/cargo/blob/46c9b51957e335ad03051ae8c513f3ba2a55b3b2/src/bin/cargo/cli.rs#L17-L25
[an attempt]: https://github.com/rust-lang/cargo/pull/9045

**Comment by FrankC01** [comment]
OK, thanks for the update and references. I will take a look at the code specifically in the install/uninstall space and give you my thoughts if not a PR.

**Comment by weihanglo** [comment]
Hi. There is a new feature request https://github.com/rust-lang/cargo/issues/10662, and it gets a reference implementation. I am going to close this one. If you are still interested in this feature, we can move further discussions there. Thanks for your report!
