### ISSUE TITLE
`cargo publish` deployed a corrupted tar file to the central repo

### ISSUE THREAD

**Issue by carllerche** [rust-lang/cargo#1041]
I am attempting to publish curl, however somehow a corrupted tarball got pushed out: https://crates.io/crates/curl-sys

When I try to publish `curl`, I get the following error:

```
failed to verify package tarball

Caused by:
  Unable to get packages from source

Caused by:
  Failed to unpack package `curl-sys v0.1.0`

Caused by:
  invalid input

**Comment by alexcrichton** [comment]
A few bugs have been fixed in tar-rs since this was opened, so I'm going to close this as presumed fixed. I have also not seen this in quite some time.

**Comment by xtuc** [comment]
It looks like to happen again
```
$ cargo build
error: failed to download `curl-sys v0.4.25`

Caused by:
  unable to get packages from source

Caused by:
  failed to unpack package `curl-sys v0.4.25`

Caused by:
  failed to unpack entry at `curl-sys-0.4.25/curl/src/tool_operate.c`

Caused by:
  failed to unpack `~/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.25/curl/src/tool_operate.c`
[1]    25421 exit 101   cargo b
```

**Comment by ehuss** [comment]
@xtuc it is more helpful to file a new issue than to comment on one that is over 4 years old.  Unfortunately there's not enough information in the error message to see what is wrong.  I posted #7874 to fix the error message, though that is not immediately helpful for you.  I would check that there isn't anything wrong with your filesystem (not full, no permission issues, etc.), and maybe just delete the `~/.cargo/registry/src` directory to see if it clears it up.
