### ISSUE TITLE
Weird error with cargo

### ISSUE THREAD

**Issue by palladium-coder** [rust-lang/cargo#10418]
### Problem

Hello,

I came across this error while trying to compile some code

```
error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
   --> C:\Users\<username>\.cargo\registry\src\github.com-1ecc6299db9ec823\ansi_term-0.12.1\src\lib.rs:252:5
    |
252 | use std::intrinsics::size_of;
    |
```

But the weird part is if you look at file src\lib.rs:252:5 in ansi_term-0.12.1 github repo (https://github.com/ogham/rust-ansi-term/blob/v0.12.1/src/lib.rs) , that line is not present.

Even upon running ```cargo clean``` I faced the same error. I had to resolve this by deleting the C:\Users\<username>\.cargo\ folder and then it worked fine.

It happened to me one time and I wasnt able to reproduce this again .

### Steps

Complie bevy hello world program.

### Notes

I am not able to reproduce this again after I deleted the .cargo folder. It might be a one off incident , but felt its better to report it here.

rustc details are as follows

```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-pc-windows-msvc
release: 1.58.1
LLVM version: 13.0.0

```

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.22000 (Windows 10 Home Single Language) [64-bit]
```

**Comment by ehuss** [comment]
That's strange!  I would have to guess that somehow the file got edited.  Without a reproduction, I'm not sure there is much we can do here, so I'm going to close this out.  However, #9455 is open to change it so that these files won't accidentally get modified. There are other issues like #9691 for validating the contents of the cache (though I'm not sure how feasible that is).
