### ISSUE TITLE
Cargo documentation test page should have link or example on how to define a test

### ISSUE THREAD

**Issue by davidpaulmcintyre** [rust-lang/cargo#10415]
### Problem

A google search for “cargo test” takes me to this page https://doc.rust-lang.org/cargo/commands/cargo-test.html, which is also the top result returned when searching from within https://doc.rust-lang.org/stable/cargo/.  

As a new rust user, i feel that there are only 2 code snippets i need from this page:
- `cargo test`
- `#[test]`

The first item is present, the second is not. If this second bit of info is not present on this page (maybe justifiably bc there are different test types), there should be a link to a page that does contain it, notably https://doc.rust-lang.org/stable/cargo/reference/cargo-targets.html?highlight=cargo%20test#tests.

i would be happy to submit pr if this is acceptable.

### Steps

1. search for "cargo test" in a search engine or from w/in the cargo search box
2. open result, which is https://doc.rust-lang.org/cargo/commands/cargo-test.html
3. observe there is no assistance in how to define a test or where to find this info

### Possible Solution(s)

Under "SEE ALSO" there should be a link to https://doc.rust-lang.org/stable/cargo/reference/cargo-targets.html?highlight=cargo%20test#tests w/ the description "How to define a test". 

### Notes

if everyone agrees w/ me, pls assign this to me and i'll create a pr w/ a link

### Version

```text
current version of the online docs
```

**Comment by Eh2406** [comment]
Improving documentation is almost always welcome!

From https://doc.rust-lang.org/cargo/commands/cargo-test.html,
> and check out the rustc book's chapter on how tests work at https://doc.rust-lang.org/rustc/tests/index.html.

Perhaps that sentence could be reworked to make it clear that it is also the link for "how to write tests".

**Comment by weihanglo** [comment]
Fixed with https://github.com/rust-lang/cargo/pull/10417. Thanks!
