### ISSUE TITLE
`-Zbindeps` panics with activated_features for invalid package: features did not find PackageId 

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-lang/cargo#10431]
### Problem

```cmd
thread 'main' panicked at 'activated_features for invalid package: features did not find PackageId { name: "jni", version: "0.19.0", source: "registry `crates-io`" } NormalOrDevOrArtifactTarget(Some(CompileTarget { name: "aarch64-linux-android" }))', src\tools\cargo\src/cargo\core\resolver\features.rs:318:14
```

Attached is a small copy of the project, it's a copy of the android-ndk-rs hello world sample that I'm trying to adapt to use bindeps to see if I can have them create an apk.

[android-test.zip](https://github.com/rust-lang/cargo/files/8149081/android-test.zip)

### Steps

1. Download attached zip file
2. Build with `cargo +nightly build -Zbindeps`, or a clean cargo from main (`5be1b1b5b`)

**Comment by ehuss** [comment]
Thanks!

@Byron I think the issue is [these lines](https://github.com/rust-lang/cargo/blob/188298f08f20bbaecc03b4b49fa75e99bb3a6db5/src/cargo/core/resolver/features.rs#L773-L775).  I believe those should be looking at `FeaturesFor`.  In this example, android isn't in `requested_targets`.

**Comment by Jasper-Bekkers** [comment]
Thanks for taking a look @ehuss !

**Comment by Byron** [comment]
Thanks @Jasper-Bekkers for the files, I will try to reproduce it today, thanks @ehuss for narrowing it down, that will help with the fix.
I will submit it as new PR when ready.
