### ISSUE TITLE
cargo should be published on crates.io

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/cargo#1043]
It makes it so that plugins like `cargo tags` don't have to depend on the git version.

**Comment by alexcrichton** [comment]
For now I think that cargo will only reside in a git repository as the API is super unstable and it's quite a moving target (rarely compiles on master). Once Rust is more stable though we can certainly take the time to go clean up the APIs!

At this time though this isn't super actionable, so I'm going to close.
