### ISSUE TITLE
Unable to pass an environment variable to target.runner

### ISSUE THREAD

**Issue by leapofazzam123** [rust-lang/cargo#10445]
### Problem

```
error: could not execute process `$CARGO run --package runner -- target/x86_64-arius/debug/arius` (never executed)
```

### Steps

```toml
[target]
runner = '$CARGO run --package runner --'
```

### Version

```text
cargo 1.61.0-nightly (ea2a21c 2022-02-15)
release: 1.61.0-nightly
commit-hash: ea2a21c994ca1e4d4c49412827b3cf4dcb158b1d
commit-date: 2022-02-15
host: aarch64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by weihanglo** [comment]
Hi. Assumed you are referring to [`target.<triple>.runner`] config. At this moment, [the implementation] is not able to expand environment variables. Actually, as far as I know, to keep it simple, cargo tries to avoid duplicating what a shell should do.

As a workaround, if you know the value of the environment variable beforehand, you might want to configure it in [`env`] configuration. (Note that it doesn't support shell expansion either.)

[`target.<triple>.runner`]: https://doc.rust-lang.org/1.59.0/cargo/reference/config.html#targettriplerunner
[the implementation]: https://github.com/rust-lang/cargo/blob/40b674cd1115299034fafa34e7db3a9140b48a49/src/cargo/util/config/path.rs#L52-L78
[`env`]: https://doc.rust-lang.org/1.59.0/cargo/reference/config.html#env

**Comment by weihanglo** [comment]
Going to close this in favour of #10789, which I left more alternatives there.
Thanks for your report anyway!
