### ISSUE TITLE
Invalid handle problem

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/cargo#10464]
### Problem

I am not sure if it's really Cargo's fault, perhaps it's just an unknown problem in my system. Since few days I'm having a problem with Cargo on Windows. (I've used for years Cargo on the same system with no problems). If I try to create the project "test1" cargo gives me (the same error is generated if I run it as administrator):

```
error: Failed to create package test1 at ...\test1

Caused by:
  failed to open file ...\test1\.gitignore

Caused by:
  Error 6 - The handle is invalid 
```

### Steps

cargo new test1

### Notes

I am using:
```
rustc 1.61.0-nightly (38a0b81b1 2022-03-06)
```
(rustc and rustup work well, I can update the Nightly compiler with no problems).

### Version

```text
cargo 1.61.0-nightly (3d6970d50 2022-02-28)
release: 1.61.0-nightly
commit-hash: 3d6970d50e30e797b8e26b2b9b1bdf92dc381f34
commit-date: 2022-02-28
host: x86_64-pc-windows-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 6.3.9600 (Windows 8.1) [64-bit]
```

**Comment by weihanglo** [comment]
Hmm... Just found a [similar issue] from Windows official support site, though it may or may not be relevant to what you reported.

Could you test against stable/beta channel to see if the problem still occurs?

[similar issue]: https://support.microsoft.com/en-us/topic/-the-handle-is-invalid-error-message-when-you-run-a-command-that-runs-a-script-and-saves-the-output-to-a-file-in-x64-based-versions-of-windows-server-2008-2adeb0e7-4084-80e0-56d0-630084ebba9e

**Comment by leonardo-m** [comment]
Now it gives me a different error:

```
...>cargo new test1
thread 'main' panicked at 'couldn't initialize the libgit2 library: -1, error: unknown error', C:\...\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\libgit2-sys-0.13.1+1.4.2\lib.rs:4126:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/458262b1315e0de7be940fe95e111bb045e4a2a4\/library\std\src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/458262b1315e0de7be940fe95e111bb045e4a2a4\/library\core\src/panicking.rs:143:14
   2: <std::sync::once::Once>::call_once::<libgit2_sys::init::{closure#0}>::{closure#0}
   3: std::sync::once::Once::call_inner
             at /rustc/458262b1315e0de7be940fe95e111bb045e4a2a4\/library\std\src\sync/once.rs:428:21
   4: libgit2_sys::init
   5: <git2::config::Config>::open_default
   6: cargo::ops::registry::http_proxy
   7: cargo::ops::registry::needs_custom_http_transport
   8: cargo::init_git_transports
   9: cargo::cli::main
  10: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Using the latest Nightly:

```
cargo 1.61.0-nightly (65c826642 2022-03-09)
release: 1.61.0-nightly
commit-hash: 65c82664263feddc5fe2d424be0993c28d46377a
commit-date: 2022-03-09
host: x86_64-pc-windows-gnu
libgit2: 1.4.1 (sys:0.14.1 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 6.3.9600 (Windows 8.1) [64-bit]
```

**Comment by leonardo-m** [comment]
After installing "Git for Windows" I'm back to the "Error 6 - The handle is invalid" (now using the latest cargo 1.61.0-nightly 65c826642 2022-03-09).

**Comment by leonardo-m** [comment]
I've done some bisection, and the first rust/cargo Nightly that gives that Error 6 is:

    cargo 1.61.0-nightly (3d6970d50 2022-02-28)
    release: 1.61.0-nightly
    commit-hash: 3d6970d50e30e797b8e26b2b9b1bdf92dc381f34
    commit-date: 2022-02-28
    host: x86_64-pc-windows-gnu
    libgit2: 1.3.0 (sys:0.13.23 vendored)
    libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
    os: Windows 6.3.9600 (Windows 8.1) [64-bit]

**Comment by AndreKR** [comment]
I can confirm that the issue can be worked around with
```
rustup default nightly-2022-02-27-x86_64-pc-windows-gnu
```

**Comment by ehuss** [comment]
@weihanglo Can you post a PR to update git2/libgit2-sys to see if that will resolve the problem?

**Comment by leonardo-m** [comment]
I've updated Nightly, with the Cargo improvements, so far no change.

**Comment by ehuss** [comment]
I tracked down the issue to https://github.com/rust-lang/rust/issues/95154

**Comment by leonardo-m** [comment]
Now it's fixed, thank you :)
