### ISSUE TITLE
Cargo shouldn't use println! for transmitting commands

### ISSUE THREAD

**Issue by evandrocoan** [rust-lang/cargo#10475]
### Problem

Cargo shouldn't use println! for transmitting commands. Problem discussed on: https://github.com/rust-lang/cargo/issues/985#issuecomment-913189097

### Proposed Solution

Cargo if it wants to use print, open a special file and print to it instead of stderr/stdout. Then, users do not have to open a file for their print. It is more reasonable for the tool (cargo) to open a file for its commands than the user to open a file for its debug printing.

**Comment by Eh2406** [comment]
What's the recommended plan for backwards compatibility?

**Comment by evandrocoan** [comment]
What would break if cargo stops using stdout and writes its commands to a file? Do you mean there are users using Cargo stdout feature to pass commands to it?

If so, we can keep the current/old behavior by default and allow the user to enable the new behavior by changing the recipe. If someday cargo releases a major release with breaking changes, we can enable this by default and keep the old behavior as opitional.

**Comment by epage** [comment]
> Cargo shouldn't use println! for transmitting commands.

I think some context is missing as to why this is the case. It is fairly standard for stdout to be used for interprocess communication like this with a defined contract.  stderr is generally what shouldn't be interpreted but sent further up the stack.

> What would break if cargo stops using stdout and writes its commands to a file? Do you mean there are users using Cargo stdout feature to pass commands to it?

It isn't cargo that is doing the writing to stdout but cargo reads `build.rs` stdout to receive instructions as specified at https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script

If we stop using stdout for IPC, we need a different mechanism and a way to still know when to use the old mechanism for existing `build.rs` that write instructions to `stdout`.

If the new mechanism is a file, we need a way for both cargo and the `build.rs` to know which file it is.  However, it feels strange to use a file for IPC like this.

Like I said earlier, Its not clear to me where there is a problem with what cargo currently does with stdout.  If its not exposing stderr, content, I can see that being something to explore further.

**Comment by Ryan1729** [comment]
> If its not exposing stderr, content, I can see that being something to explore further.

It is not currently exposing stderr output, as can be easily checked by using [`eprintln!`](https://doc.rust-lang.org/std/macro.eprintln.html) in a `build.rs` file.

Using `println!("cargo:warning=MESSAGE");` does show "warning: MESSAGE" however, [as mentioned on the page linked above](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargo-warning).

For example, after running `cargo new build_rs_example` and adding the following `build.rs` inside that folder:
```rust
fn main() {
    println!("This doesn't show up");
    eprintln!("This doesn't show up either");
    println!("cargo:warning=This does show up though");
}
```
... I get the following output when running the crate:
```
$ cargo r
   Compiling build_rs_example v0.1.0 (/home/ryan/code/rust/bug_repros/build_rs_example)
warning: This does show up though
    Finished dev [unoptimized + debuginfo] target(s) in 0.70s
     Running `target/debug/build_rs_example`
Hello, world!
```

**Comment by ehuss** [comment]
I'm going to close as I don't think we are going to change the method cargo uses to communicate with build scripts. There doesn't seem to be enough motivation here for such a large and disruptive change.

**Comment by peternann** [comment]
I will throw my 2c worth in since I found my way here...

Not having an obvious, non-hacky way to debug and log progress through build.rs is quite surprising.
Sure, you might not want your builds to be too 'noisy' once they are working well... But you've got to get them to the point of 'working well' first, and that often means debugging.

I am using the '-vv' hack with eprintln!(), but it is far from what I really want with all the other guff that comes out with -vv.

What about prefixing lines like:
```
eprintln!("cargo:info=Running build step x...");
```
to get them to come out cleanly?

**Comment by resistcorp** [comment]
Couldn't cargo simply relay any stdout/stderr lines it doesn't use as commands? Or even just relay everything while interpreting the "cargo:" commands ?

**Comment by zdivelbiss** [comment]
> Couldn't cargo simply relay any stdout/stderr lines it doesn't use as commands? Or even just relay everything while interpreting the "cargo:" commands ?

This seems like a reasonable compromise. If it doesn't start with `cargo:` and evaluate to a known command, just spit it out into the console.
