### ISSUE TITLE
Incorrect flag in --locked --offline error message

### ISSUE THREAD

**Issue by QSchulz** [rust-lang/cargo#10504]
### Problem

Trying to build a crate with:
```
cargo build --locked --offline
```
when no `Cargo.lock` file is provided in the crate source repository leads to the following error message:
```
error: the lock file /path/to/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```
It should mention `--locked` and not `--frozen`.

### Possible Solution(s)

https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/lockfile.rs#L50-L54
```
        let flag = if ws.config().network_allowed() {
            "--locked"
        } else {
            "--frozen"
        };
```
could actually be:
```
        let flag = if ws.config().locked() {
            "--locked"
        } else {
            "--frozen"
        };
```

### Notes

(Never done rust and didn't compile the suggestion)

The absence of Cargo.lock file shouldn't matter to reproduce the bug but it's an easy way to reproduce it.

**Comment by hi-rustin** [comment]
I can reproduce it.
@rustbot claim
