### ISSUE TITLE
Cargo.toml `forced-target` ignored by .cargo/config.toml `target.<triple>`/`target.<cfg>`

### ISSUE THREAD

**Issue by 4LT** [rust-lang/cargo#10518]
### Problem

When setting `package.forced-target` in Cargo.toml, the value used (e.g. "wasm32-unknown-unknown") is ignored as the target used in .cargo/config.toml `[target.<triple>]` or `[target.<cfg>]`

e.g. if I have the following in .cargo/config.toml

```
[target.'cfg(target_arch="wasm32")']
runner = "echo"
```

"echo" won't be used as the runner when running `cargo test` or `cargo run`

### Version

```text
cargo 1.61.0-nightly (109bfbd 2022-03-17)
release: 1.61.0-nightly
commit-hash: 109bfbd055325ef87a6e7f63d67da7e838f8300b
commit-date: 2022-03-17
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by weihanglo** [comment]
See https://github.com/rust-lang/cargo/issues/14833

> Several places calling `BuildConfig::requested_kinds` don't consider anything from default-target or forced-target, so some target platform info may be missing.
> ...
> The fix for the latter should be a bit easier. Managing all calls to `requested_kinds` through on `requested_kinds` method, which reuse a similar logic like [this one](https://github.com/rust-lang/cargo/blob/5dbda8b4ee6c1ef6480f9af197cfb10ad5c95cea/src/cargo/ops/cargo_compile/unit_generator.rs#L115-L128). This should resolve the issue if only your top-level primary package has `forced-target` specified.

**Comment by weihanglo** [comment]
The thing I am unsure is the future of the unstable feature itself. Whether we keep it or combine with `-Zbindeps` or any other directions.

**Comment by weihanglo** [comment]
While this is an older issue and <https://github.com/rust-lang/cargo/issues/14291> is a dup, that one contains more info so close this in favor of <https://github.com/rust-lang/cargo/issues/14291>.
