### ISSUE TITLE
Please use Discussions instead of https://users.rust-lang.org/

### ISSUE THREAD

**Issue by elibroftw** [rust-lang/cargo#10510]
### Problem

I try posting an issue, and I get hit with "you can't post two links"

Then after "fixing" my post by reducing its correctness, my post gets auto hidden https://users.rust-lang.org/t/akismet-has-temporarily-hidden-your-post/73464.

Come on, don't do that! Should I be posting to stackoverflow instead?

### Proposed Solution

Use github discussions or recommend users to use stackoverflow for help. There are questions on https://users.rust-lang.org/, reddit, and stackoverflow. Better to use these forums for what they excel at rather than broadening their scopes.

### Notes

This problem wouldn't have occurred if the documentation for https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section, was better. I've never read the documentation for pip, and I've been using it for 5+ years. However, I've been using cargo for less than 6 months and after reading the docs, I'm left even more confused because shits not working.

> Caused by:
  patch for `tauri-runtime-wry` in `https://github.com/rust-lang/crates.io-index` points to the same source, but patches must point to different sources

the docs says replace is deprecated, so I'm left writing about my struggles!

**Comment by Eh2406** [comment]
We are not the moderators of users.rust-lang.org . We have no control over their policies or systems. 
You should feel free to ask your questions on stackoverflow, or any place else you feel comfortable.

Without a minimal reproducible example of how you are stuck, it's going to be hard for us to figure out how to help.

Documentation is always a work in progress. If you have suggestions for how we can improve it, that would be wonderful!

**Comment by elibroftw** [comment]
https://users.rust-lang.org/t/how-to-actually-use-patch-with-good-examples/73463 was my issue. Note was. It's not relevant to me right now, but it definitely is an issue.

**Comment by ehuss** [comment]
I'm sorry you had trouble getting your question answered. Unfortunately we don't have the capacity to open up another discussion forum. We also feel like that would further fracture the readership, leading to fewer people being able to help. For the record, there are several places to get help:

* https://users.rust-lang.org/
* Community Discord: https://discord.com/invite/rust-lang-community
* https://stackoverflow.com/
* https://www.reddit.com/r/rust/ (which has a sticky thread for questions)
* There are various other services like Matrix and Slack which also have Rust channels
