### ISSUE TITLE
Add cargo-rm (from cargo-edit) to cargo proper 

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#10520]
### Problem

With #5586, users will have an "IDE-like experience" for adding dependencies but not removing them where they have to deal with updating feature tables, etc.

### Proposed Solution

Merge cargo-rm

**Comment by epage** [comment]
This will require
- An evaluation of prior art
- A re-evaluation of what the behavior should be
- Updates on behavior
- Port to cargo's code base in a `merge-rm` branch
- Actual merge PR

https://github.com/killercup/cargo-edit/issues/682 is where I'm starting to organize thoughts on this.

**Comment by epage** [comment]
Blocked on #10581 so it can share test logic with `cargo-add`

**Comment by stshine** [comment]
Can we call this `cargo remove` instead of `rm`?

**Comment by tshepang** [comment]
am with @stshine... `rm` tripped me up a number of times

**Comment by epage** [comment]
Yes, most prior art uses `remove` (see the linked cargo-edit issue) though I expect we would provide an `rm` alias, whether visible or not.
