### ISSUE TITLE
`rerun-if-not-exists` for rerun the `build.rs` file if a particular file does not exist

### ISSUE THREAD

**Issue by sassman** [rust-lang/cargo#10541]
### Problem

Imagine a `build.rs` that triggers the generation of some file(s) (e.g. `src/foo.rs`) based on some kind of configuration.

Now if those files do not exist the `build.rs` should run. As well as if the configuration has changed. 
If the generated files are already present, then it should not run per se, only if the configuration has changed.

### Proposed Solution

Introducing a new `rerun-if` flag to control the file-does-not-exist case.
Suggestion: `rerun-if-not-exists:src/foo.rs`

```rust
// build.rs

fn main() {

    // generating `src/foo.rs`

    // rerun if the configuration has changed
    println!("cargo:rerun-if-changed=my-config.toml");

    // rerurn if the generated source file does not exist
    println!("cargo:rerun-if-not-exists=src/foo.rs");
}
```

### Notes

I would be happy to volunteer for the implementation if the proposal gets accepted.

**Comment by ehuss** [comment]
I may not be understanding this, but build scripts should not be modifying files within the source tree.  Per the docs [here](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script), they are only designed to write to `OUT_DIR`.

**Comment by sassman** [comment]
I see, the docs clearly indicate the `OUT_DIR`. 
So I guess we are kinda abusing the `build.rs` here. On the other hand, it's not the first time that I've seen usages where some sort of pre-compilation is happening, so that source files are being produced by the build file.

**Comment by aminya** [comment]
I have also faced this issue. My problem is that I have a `./build` directory that `build.rs` generates. But when I delete `./build`, build.rs doesn't rebuild! If I use `cargo:rerun-if-changed=./build`, it will always rebuild no matter what.

**Comment by Eh2406** [comment]
> If I use `cargo:rerun-if-changed=./build`, it will always rebuild no matter what.

That sounds like a bug, can you make a reproducible example and open a new issue?

**Comment by ehuss** [comment]
> That sounds like a bug, can you make a reproducible example and open a new issue?

I think this is to be expected. `rerun-if-changed` will track if a file has changed *before* a build script runs, not after. In this case, the build script is modifying files that it itself depends on. That's not the intended way to use `rerun-if-changed`, or build scripts in general.  `rerun-if-changed` should only be used for static files that are *inputs* to the build script.

Build scripts aren't designed for generating files outside of `OUT_DIR`. Although it is feasible to do so, it's generally recommended to use other mechanisms to do that (like a separate command).

**Comment by aminya** [comment]
Thanks for the explanation. Can't cargo extend the functionality for checking the changes? It seems a missed opportunity to re-run the scripts even if it is not the original intent.
