### ISSUE TITLE
Unnecessary error for weak dependency features

### ISSUE THREAD

**Issue by CryZe** [rust-lang/cargo#10540]
### Problem

I just tried out the weak dependency features support in Rust 1.60. And I'm getting the following error:

```
error: failed to parse manifest at `[...]\Cargo.toml`

Caused by:
  feature `std` includes `serde?/std` with a `?`, but `serde` is not an optional dependency
  A non-optional dependency of the same name is defined; consider removing the `?` or changing the dependency to be optional
```

This error is unnecessary and should probably be removed. The whole point of the weak dependency features is to fix the old system where you accidentally bring in dependencies. Ideally the default would be changed, but can't due to backwards compatibility, so `?/` is the alternative that was chosen. Now in order to not accidentally bring in dependencies I don't want, I want to use `?/` everywhere, but apparently this error prevents me from doing so.

### Steps

1. Use `?/` with a dependency that is not optional.

### Possible Solution(s)

Don't show the error.

### Version

```text
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
release: 1.60.0
commit-hash: d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422
commit-date: 2022-03-01
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.19042 (Windows 10 Education) [64-bit]
```

**Comment by ehuss** [comment]
We discussed this issue, and we decided it is best to stay with the current syntax. The `?` was intentionally chosen to mean "optional" (with some similarity with Rust's use of `?` and options). We'd also like to avoid further churn in changing syntax.

We understand that the current syntax is not ideal, and was forced by need of backwards compatibility.  I opened #10556 with a possible option for the future.

**Comment by CryZe** [comment]
This is not what this issue is about.

**Comment by epage** [comment]
When discussing syntax, we are also referring to the semantics of that syntax.  We are not wanting to allow `?` when something is optional.  As ehuss said, #10556 is the path forward for improving the behavior here.

**Comment by CryZe** [comment]
When the long term goal are the semantics I'm proposing here (independent of syntax), then why artificially cripple `?` now with no advantages?
