### ISSUE TITLE
Cargo interacts badly with flexible target specification

### ISSUE THREAD

**Issue by Tobba** [rust-lang/cargo#1055]
Right now, if you attempt to use flexible target specification in your project rustc will look for the target files in the current working directory. With cargo this means that it'll look in the root directory of each package it builds.

This is incredibly impractical when dependencies get involved.

**Comment by Tobba** [comment]
This can be worked around using the (only documented in the middle of rustc code) RUST_TARGET_PATH environment variable

**Comment by alexcrichton** [comment]
I think this was fixed in #1396 and some other related internal refactorings, but please reopen if it still happens!
