### ISSUE TITLE
error: could not create home directory: '.....' The filename, directory name, or volume label syntax is incorrect. (os error 123)

### ISSUE THREAD

**Issue by masta99wrfvsHsa** [rust-lang/cargo#10573]
### Problem

set up rust with rustup init,
custom installation so path is not edited and i needs to set path when i do my dev.
so i copy the .cargo and .rustup to my local dev path.
and i tried to *Setup and use cargo.....oops.this erro came

### Steps

1.set up rust with rustup init,(ps,win10,64bit)
2.custom installation so env var path is not edited
3..copy the .cargo and .rustup to a local dev path.
4.create a simple script to set the RUSTUP_HOME and CARGO_HOME add then cargo binary path into the $Path/%PATH%.
5.run it.

my full steps log>
cargo
'cargo' is not recognized as an internal or external command,
operable program or batch file.
(THIS STEP PROVE NO CARGO IN PATH)

D:\>cd D:\Coding\rust\gnuwin

D:\Coding\rust\gnuwin>frust

D:\Coding\rust\gnuwin>set RUSTUP_HOME="D:\Coding\rust\gnuwin\.rustup"

D:\Coding\rust\gnuwin>set CARGO_HOME="D:\Coding\rust\gnuwin\.cargo"

D:\Coding\rust\gnuwin>set PATH="D:\Coding\rust\gnuwin\.cargo"\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;(........lillong)

D:\Coding\rust\gnuwin>cargo new test
error: could not create home directory: 'D:\Coding\rust\gnuwin\"D:\Coding\rust\gnuwin\.rustup"': The filename, directory name, or volume label syntax is incorrect. (os error 123)

### Possible Solution(s)

no idea.does the cargo do some weird path append of local path and RUSTUP_HOME?
should i just not set RUSTUP_HOME?

### Version

```text
cargo version --verbose
error: could not create home directory: 'D:\Coding\rust\gnuwin\"D:\Coding\rust\gnuwin\.rustup"'
```

**Comment by masta99wrfvsHsa** [comment]
retried with different (") position also doesnt work.
'D:\Coding\rust\gnuwin\"D:\Coding\rust\gnuwin"\.rustup':
doesnt seems to be win specific problem

**Comment by ChrisDenton** [comment]
Have you tried it without using quotes?

**Comment by masta99wrfvsHsa** [comment]
oh it worked.but i wonder why quotes caused that.It should support quotes perfectly right?It think its common to make the make sure the path can support spaces.like "/a/home/my special rust folder/"

**Comment by masta99wrfvsHsa** [comment]
for now it will close it.
Summary,cargo doesnot support the path with quotes

**Comment by ChrisDenton** [comment]
I think this is one case where quotes aren't needed even if there are spaces in the path. But you're right that quotes should be handled correctly anyway.
