### ISSUE TITLE
testsuite fails with clap v3.1.11

### ISSUE THREAD

**Issue by Muscraft** [rust-lang/cargo#10591]
### Problem

[clap v3.1.11](https://github.com/clap-rs/clap/releases/tag/v3.1.11) is causing the test suite to fail on the following tests:
- build::invalid_jobs
- cargo_add::dev_build_conflict
- cargo_add::invalid_arg
- cargo_add::invalid_target_empty
- cargo_add::no_args
- help::help
- init::unknown_flags
- install::install_empty_argument
- install::not_both_vers_and_version
- metadata::cargo_metadata_bad_version
- new::new_with_bad_edition
- new::no_argument
- new::unknown_flags
- run::run_bins
- run::run_multiple_packages
- rustc::fail_with_multiple_packages
- vendor::test_sync_argument

### Steps

1. Pull down the master branch of cargo
2. run `cargo update`
3. run `cargo build` and check the lockfile for
    ```toml
    [[package]]
    name = "clap"
    version = "3.1.11"
    ```
4. run `cargo test --features 'deny-warnings'

### Notes

cc @epage 

### Version

```text
cargo 1.62.0 (c85a71e6f 2022-04-21)
release: 1.62.0
commit-hash: c85a71e6f3cf9390d77fd2c75b276ba3f088f40c
commit-date: 2022-04-21
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.82.0-DEV (sys:0.4.53+curl-7.82.0 vendored ssl:SecureTransport)
os: Mac OS 12.3.1 [64-bit]
```

**Comment by Muscraft** [comment]
It looks like clap changed what should go to stdout vs stderr slightly and it might have caused this.

**Comment by epage** [comment]
v3.1.12 s released
