### ISSUE TITLE
Cargo client to support private registry authentication while pulling the dependencies !

### ISSUE THREAD

**Issue by vasanthkg** [rust-lang/cargo#10610]
### Problem

root@aa24ac221e56:/# cargo --version
cargo 1.60.0 (https://github.com/rust-lang/cargo/commit/d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422 2022-03-01)`

And the cargo build fails to download the dependencies crates while i am able to publish the crates successfully.

https://github.com/rust-lang/cargo/issues/21 63.39 error: failed to download from https://example.com/artifactory/api/cargo/cargo-local/v1/crates/messagingapi/0.1.0/download
https://github.com/rust-lang/cargo/issues/21 63.39
https://github.com/rust-lang/cargo/issues/21 63.39 Caused by:
https://github.com/rust-lang/cargo/issues/21 63.39 failed to get 200 response from https://example.com/artifactory/api/cargo/cargo-local/v1/crates/messagingapi/0.1.0/download, got 403
executor failed running [/bin/sh -c cargo build --release]: exit code: 101

**Comment by Eh2406** [comment]
403 is an authentication error. It looks like you do not have artifactory correctly configured.
We (the cargo team) do not have backroad on how to set up artifactory.

**Comment by ehuss** [comment]
Closing as this does not appear to be directly related to cargo.
