### ISSUE TITLE
New testing style isn't documented

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#10628]
### Problem

With cargo-add and #10581, we are getting a  new way of testing but its not in the contributing guide

### Steps

See docs

### Possible Solution(s)

Docs should cover
- writing new tests
  - multiple bin calls to verify in a test
  - cover `.keep` files
  - cover `curr_dir`
- updating tests

### Notes

Blocked on #10626 and #10627 as they will change things up

### Version

_No response_cover

**Comment by weihanglo** [comment]
We have docs here <https://doc.crates.io/contrib/tests/writing.html#ui-tests>. I believe this can be closed now. If we have more ideas to enhance, we could reopen or file a new one.
