### ISSUE TITLE
Hard to review snapshots because they are far from their intended code

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#10627]
### Problem

Right now we have
```
tests/snapshots/add/*
...
tests/testsuite/cargo_add.rs
...
```
This is mildly annoying to review in small cases but in cases like #10620, its a big pain

### Steps

See #10620

### Possible Solution(s)

In `cargo-test-macro` we add a macro that will discover test files in the snapshot directory

To ensure it rebuilds when new tests are added, we add a `build.rs` that says to rebuild when that directory changes (downside being we'll rebuild more when making test changes which avoiding that was one of the benefits of snapshots)

### Notes

We should wait for #10620 so we can update all of them at once

**Comment by Muscraft** [comment]
I believe this should also wait on #10626 since it will reorganize snapshot tests
