### ISSUE TITLE
Build mode that does not touch global / shared locations

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/cargo#1063]
One piece of feedback from RelEng in Portland was that they expect the build process to be isolated - that is, that all of the sources and configuration files live within the directory that is being built. It would be good to have a configuration option that we could set to ensure that cargo does not write/read from places like ~/.cargo, as this will potentially mess up build isolation expectations that they have.

**Comment by alexcrichton** [comment]
Now that @brson implemented `CARGO_HOME` in https://github.com/rust-lang/cargo/pull/1084, I think this is resolved.
