### ISSUE TITLE
cargo new: automatically add to workspace

### ISSUE THREAD

**Issue by theduke** [rust-lang/cargo#10670]
### Problem

When running `cargo new` in a workspace a warning is printed, but you have to manually add the new crate to the `members = []` section.

### Proposed Solution

Add a new `--workspace` / `-w` flag to `cargo new` that automatically adds the new crate with the correct path to `members`.

Print a hint about the flag when `cargo new` is run in a workspace.

This is admittedly a small quality of life feature, but I do it often enough that it becomes annoying.

**Comment by ehuss** [comment]
Thanks for the report. This is a known issue, closing as a duplicate of #8365.

**Comment by ehuss** [comment]
Sorry, I should have linked to #6378.

**Comment by felipetesc** [comment]
Any news about this proposal ? What's the current situation ? Thanks.
