### ISSUE TITLE
signal: 11, SIGSEGV: invalid memory reference

### ISSUE THREAD

**Issue by heyanlong** [rust-lang/cargo#10679]
### Problem

   Compiling libc v0.2.124
   Compiling proc-macro2 v1.0.37
error: failed to run custom build command for `libc v0.2.124`

Caused by:
  process didn't exit successfully: `/var/www/html/SkyAPM-php-sdk/target/debug/build/libc-9fc25dbd7adcc169/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: build failed

### Notes

https://github.com/SkyAPM/SkyAPM-php-sdk/runs/6517898614?check_suite_focus=true

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-unknown-linux-musl
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Alpine Linux 3.7.1 [64-bit]
```

**Comment by weihanglo** [comment]
Without reproducible steps it's hard to perform further analysis. The culprit might be build script of crate `libc`. A "build script" in a Cargo project is a native binary compiled by Cargo. It runs to do works at build time. The segfault is not from rustc or cargo, so the failure probably has nothing to do with Cargo. You may instead check out the [build script](https://github.com/rust-lang/libc/blob/master/build.rs) in libc.

To investigate more, you could pass `-vv` to enable "very verbose mode" to display all the output from build script. Alternatively, you can build your project with gdb/lldb to debug the segfault, such like `gdb --args /var/local/git/skywalking/target/release/build/libc-b5ddf0437c163328/build-script-build`.

**Comment by heyanlong** [comment]
In Alpine, Use `export RUSTFLAGS="-Ctarget-feature=-crt-static"` fix it.

**Comment by MarcDorval** [comment]
This also happens when there is not enough RAM available on the system.
