### ISSUE TITLE
cargo test --no-run prints executable names, even with --message-format json (or json-render-diagnostics)

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/cargo#10684]
### Problem

Hi there, I'm the primary author of [cargo nextest](https://nexte.st/), a tool that wraps `cargo test`. Part of [how nextest works](https://nexte.st/book/how-it-works.html#the-nextest-model) is separating out the build and run phases: for the build phase, nextest runs `cargo test --no-run --message-format json-render-diagnostics` to gather a list of test binaries.

With cargo 1.60 or below, this integrated well with the UI:

![image](https://user-images.githubusercontent.com/180618/169597155-d2dd30de-c1be-4c8d-8b3a-f37c77f7d328.png)

However, with 1.61 it looks like it prints out all the executable names before starting any tests.

![image](https://user-images.githubusercontent.com/180618/169596896-c01821a0-3084-4ae9-9adf-aced97c4b8fa.png)

### Steps

`cargo test --no-run --message-format json-render-diagnostics`

### Possible Solution(s)

I think this feature makes a lot of sense if not invoked from a programmatic context, but I believe executable names should not be printed out if JSON output is requested.

### Version

```text
cargo 1.61.0 (a028ae4 2022-04-29)
release: 1.61.0
commit-hash: a028ae42fc1376571de836be702e840ca8e060c2
commit-date: 2022-04-29
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Pop!_OS 22.04 (jammy) [64-bit]
```

**Comment by ehuss** [comment]
Yea, sounds reasonable to not show that with `--message-format json`.

**Comment by danilhendrasr** [comment]
Hey, I saw this issue marked as E-easy. I'm new to cargo's code base but I'm interested in contributing and this seems like a good starting point. Can I work on it?

**Comment by weihanglo** [comment]
@danilhendrasr Definitely yes. Go ahead!

Basically, the message `Executable unittests ...` is from [`display_no_run_information`](https://github.com/rust-lang/cargo/pull/10346). You can determine whether or not to print the message by something like `TestOptions.compile_opts.build_config.emit_json()`. You may also want to [add new tests](https://doc.crates.io/contrib/tests/writing.html) if needed.

**Comment by danilhendrasr** [comment]
Got it, thank you for the hints!
