### ISSUE TITLE
Release Notes for 1.59 Missing Change to `profile.dev` optimization

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-lang/cargo#10709]
### Problem

On 1.58, `[profile.dev] opt-level=1` implies that a crate being tested with `cargo test` without a `-C opt-level` argument, but builds all dependent crates (including workspace crates, if there's a workspace dep, from what I can see) with `-C opt-level=1`. On 1.59 this changed to include all crates getting compiled with `-C opt-level=1`, increasing compile time and increasing performance (obviously).

Given its been a while, it seems like the correct solution is to simply amend the release notes to point this out.

CC https://github.com/rust-lang/rust/issues/97460#issuecomment-1139959106

**Comment by ehuss** [comment]
Hm, I don't believe there were any changes to profiles in 1.59. Unfortunately, I can't reproduce what you are referring to. Can you put together a set of steps to reproduce the issue?  For example:

```
cargo new foo
cd foo

cat >> Cargo.toml << EOF
[dependencies]
itoa = "1.0"
[profile.dev]
opt-level = 1
EOF

cargo +1.58.0 test -v
```

should produce output similar to:

```
   Compiling itoa v1.0.2
     Running `rustc --crate-name itoa … -C opt-level=1 …
   Compiling foo v0.1.0 (/Users/eric/Temp/foo)
     Running `rustc --crate-name foo ¬ -C opt-level=1 … --test …
    Finished test [optimized + debuginfo] target(s) in 1.03s
     Running `/Users/eric/Temp/foo/target/debug/deps/foo-d949ffb9e23fe5ab`

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
