### ISSUE TITLE
cargo test: continue other packages' tests when one package's test is failed.

### ISSUE THREAD

**Issue by RinChanNOWWW** [rust-lang/cargo#10712]
### Problem

My cargo version: 1.63.0-nightly (3f052d8ee 2022-05-12)

When I run multiple packges's tests like:

```
cargo test --package p1 --package p2 --package p2
```

When some test in p1 failed, it will not continue to test p2 and p3. I think it is better to continue to test p2 and p3.

### Notes

The PR support multiple packages testing: https://github.com/rust-lang/cargo/pull/1828. (Related issue: https://github.com/rust-lang/cargo/issues/1528)

**Comment by weihanglo** [comment]
There is a flag [`--no-fail-fast`](https://doc.rust-lang.org/cargo/commands/cargo-test.html#test-options):

> Run all tests regardless of failure. Without this flag, Cargo will exit after the first executable fails. The Rust test harness will run all tests within the executable to completion, this flag only applies to the executable as a whole.

Does it work for you?

**Comment by RinChanNOWWW** [comment]
It works. Thank you! @weihanglo
