### ISSUE TITLE
Cargo always 'Updating registry', fails when offline

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1072]
Related to #1031, but I’ll let you decide if it’s a duplicate.

How to reproduce:
- Run `cargo test` successfully
- Touch a local source file
- Run `cargo test` again. The crate is rebuilt as expected, but not until after:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

… which had already happened seconds ago in the previous run.
- Go offline (disable WiFi or something)
- Touch a local source file again
- Run `cargo test` again.

Actual result:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

To learn more, run the command again with --verbose.
```

… then Cargo aborts, and doesn’t even try to rebuild the crate or run the tests.

Expected result: The second run _maybe_ should not update the registry again, if the last update is "recent enough". But more importantly, the third run should succeed based locally cached data, even if a long time has passed and the local copy of the registry is considered outdated.

**Comment by vemilyus** [comment]
I can attest that this is an existing issue, I encountered it as well. The way to reproduce this is to launch a build in a project directory that doesn't contain a `Cargo.lock` file.

System: `Ubuntu 15.04 64-bit`
Cargo: `cargo 0.3.0-nightly (a2dd2ac 2015-06-24) (built 2015-06-23)`

Notes: I tested this with a project of mine `yagr`. Just cd into `src/rifle`, remove the `target/` directory and `Cargo.lock` file, then execute `cargo build`.

**Comment by bluejekyll** [comment]
I just ran into this on the plane. I was doing something funky to get some local src dependencies to build, and cargo threw the stated error.

**Comment by liudonghua123** [comment]
I use the following settings of `config`.

```
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = 'tuna'

# https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index.git/
[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

# https://mirrors.ustc.edu.cn/help/crates.io-index.html
[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"
```
