### ISSUE TITLE
When pull crates.io-index repository in gitlab ci/cd so slowly.

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/cargo#10735]
### Problem

crates.io-index repository growth big size. When pull crates.io-index repository in gitlab ci/cd so slowly.

**Comment by weihanglo** [comment]
Thanks. The [HTTP-based index registry] is under development. It helps avoid fetching the whole index as you mentioned. Here is [the tracking issue] and you can follow the instructions to test the feature.

Closing as tracking in #9069

[HTTP-based index registry]: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#http-registry
[the tracking issue]: https://github.com/rust-lang/cargo/issues/9069
