### ISSUE TITLE
-Zbuild-std gives error: duplicate lang item in crate `core`:

### ISSUE THREAD

**Issue by Grommish** [rust-lang/cargo#10734]
### Problem

Multiple variations of:
```
error: duplicate lang item in crate `core`: `bool`.
  |
  = note: the lang item is first defined in crate `core` (which `std` depends on)
  = note: first definition in `core` loaded from /media/data/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/angelcam-connector-0.10.1/target/armv7-openwrt-linux-muslgnueabihf/release/deps/libcore-8bec01d570fa74ab.rlib, /media/data/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/angelcam-connector-0.10.1/target/armv7-openwrt-linux-muslgnueabihf/release/deps/libcore-8bec01d570fa74ab.rmeta
  = note: second definition in `core` loaded from /media/data/openwrt/staging_dir/host/lib/rustlib/armv7-openwrt-linux-muslgnueabihf/lib/libcore-533ac1cfe6c35904.rlib
```

as adding `-Zbuild-std` adds `--extern` flags to the invoke when they already exist in the sysroot.

### Notes

Reference thread https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/The.20basics.20of.20debugging.20duplicate.20definitions/near/285316237

In which @jyn514 figured it out.

### Version

```text
cargo 1.60.0-nightly
```

**Comment by ehuss** [comment]
Can you provide some more information on how to reproduce the problem?

It is normal behavior for cargo to use `--extern` flags with `-Zbuild-std`, even if there is a sysroot. The `--extern` ones take precedence.

**Comment by Grommish** [comment]
This is rust 1.60.0 under OpenWrt (`x86_64-unknown-linux-gcc` Build/`mips64-openwrt-linux-musl` Host/Target).  My standardized `cargo` call included a `-Zbuild-std`, which was causing issues

See the attached build log, and the thread at https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/.E2.9C.94.20The.20basics.20of.20debugging.20duplicate.20definitions

Removing the `-Zbuild-std` flag solved the duplicate definition issue, and it was suggestion (at the above Zulip link) that it probably was a cargo issue, and to report it.  

I'm not a rust-dev, but I can get any information you might want me to collect

[connector.log](https://github.com/rust-lang/cargo/files/8861483/connector.log)

**Comment by ehuss** [comment]
I'm going to close as this seems to be an issue with some integration with the OpenWrt build system. 
I understand the `duplicate lang item` error can be annoying and difficult to diagnose. However, without a specific minimal reproduction, it is unlikely we'll be able to help here. If you can boil it down to a minimal set of steps using a stock Rust installation without using another build system, that might be helpful. However, I understand that might be difficult if you are not a Rust developer.
