### ISSUE TITLE
build fully statically linked executable for Android not supported

### ISSUE THREAD

**Issue by leleliu008** [rust-lang/cargo#10765]
### Problem

I want to build a fully statically linked executable for Android.

I respectively tried following settings:

```
export RUSTFLAGS="$RUSTFLAGS -C target-feature=+crt-static"
```

```
export RUSTFLAGS="$RUSTFLAGS -Clink-arg=-static"
```

both are not work. the final executable is always dynamically-linked.

### Steps

build https://github.com/sharkdp/bat.git for Android

### Version

```text
cargo 1.59.0 (49d8809dc 2022-02-10)
release: 1.59.0
commit-hash: 49d8809dc2d3e6e0d5ec634fcf26d8e2aab67130
commit-date: 2022-02-10
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 22.04 (jammy) [64-bit]
```
```

**Comment by weihanglo** [comment]
Seems like on Android `crt-static` is ignored. 

- https://github.com/rust-lang/libc/issues/1711
- https://github.com/rust-lang/libc/blob/6b6a6a7818596c042a3a4effddfa3cab17cf26ba/src/unix/mod.rs#L357-L364

If you feel hard to tell whether it is a bug from Cargo, I'd recommend asking on the [user forum](https://users.rust-lang.org/). Community there is often more helpful for general usage questions. I am going to close this for now. We can reopen it at anytime if there are things Cargo can improve on. Thanks for the report!

**Comment by petrochenkov** [comment]
This is an issue (or rather lack of a feature) with rustc and libc, not with cargo.
https://github.com/rust-lang/rust/issues/65447#issuecomment-687681800 has instructions that were used for enabling `+crt-static` for glibc, but they are more or less applicable to bionic libc on Android too.

It would be really great to implement this, it's been in my work queue for years, just never with a high enough priority.

**Comment by leleliu008** [comment]
> It would be really great to implement this

Yes, if this feature is implemented, we can link the lastest libc.a to the executable, then the executable can be run on older devices.

**Comment by petrochenkov** [comment]
@leleliu008 
You can try implementing it yourself, it's shouldn't be a complex task, see https://github.com/rust-lang/libc/pull/1899 and https://github.com/rust-lang/rust/pull/77386 for examples.

**Comment by leleliu008** [comment]
@petrochenkov Thanks for the hint.

**Comment by leleliu008** [comment]
@petrochenkov 

I find a easy way to build fully statically linked executable for Android without changing any code.

```bash
ANDROID_API_LEVEL=31
ANDROID_NDK_ROOT="/home/leleliu008/.ndk-pkg/android-ndk-r23b"
ANDROID_HOST_TAG=$(uname | tr A-Z a-z)-x86_64
ANDROID_LIBRARY_DIR="$ANDROID_NDK_ROOT//toolchains/llvm/prebuilt/$ANDROID_HOST_TAG/sysroot/usr/lib/aarch64-linux-android/$ANDROID_API_LEVEL"

export RUSTFLAGS="-Clink-arg=-L$PWD -Clink-arg=-static -Clink-arg=-ffunction-sections -Clink-arg=-fdata-sections -Clink-arg=-Wl,--gc-sections -Clink-arg=-Wl,--no-dynamic-linker"

cat > libc.a <<EOF
INPUT($ANDROID_LIBRARY_DIR/libc.a)
EOF

cat > libm.a <<EOF
INPUT($ANDROID_LIBRARY_DIR/libm.a)
EOF

cat > libz.a <<EOF
INPUT($ANDROID_LIBRARY_DIR/libz.a)
EOF

cat > libdl.a <<EOF
INPUT($ANDROID_LIBRARY_DIR/libdl.a)
EOF

```

**I successfully build the fully statically linked executable in this way.**

![Screenshot from 2022-06-20 00-03-22](https://user-images.githubusercontent.com/3040852/174490169-7a23c928-f263-481c-b6ef-144f4be0912c.png)

**the only fly in the ointment being the fact that `the dynamic section` is in the final statically linked executable.**
![Screenshot from 2022-06-20 00-04-26](https://user-images.githubusercontent.com/3040852/174490356-3c27fc95-f990-47ef-93f5-182d8fd0c126.png)

**Although this way has a slight flaw but it doesn't  affect the usage.**
