### ISSUE TITLE
Cargo lets dependency use disabled features 

### ISSUE THREAD

**Issue by infiniteregrets** [rust-lang/cargo#10775]
### Problem

In our project mirrord - https://github.com/metalbear-co/mirrord/ in the mirrord-cli package we have the `reqwest` package declared in `Cargo.toml` without the blocking feature enabled https://github.com/metalbear-co/mirrord/blob/main/mirrord-cli/Cargo.toml#L26 and this does not give any build errors and let use use the blocking feature which is weird because it should error out. 
Relevant issue on a container on which it errors out https://github.com/metalbear-co/mirrord/issues/152, 
but on my setup it does not. 
```
mehula@mehul-machine:~/mirrord$ uname -a
Linux mehul-machine 5.13.0-1029-azure #34~20.04.1-Ubuntu SMP Thu Jun 9 12:37:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Version

```text
mehula@mehul-machine:~/mirrord$ cargo version --verbose
cargo 1.63.0-nightly (8d42b0e87 2022-06-17)
release: 1.63.0-nightly
commit-hash: 8d42b0e8794ce3787c9f7d6d88b02ae80ebe8d19
commit-date: 2022-06-17
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by epage** [comment]
Its most likely being activated via feature unification.  The details are dependent on which [resolver](https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions) is used.

**Comment by Eh2406** [comment]
Cargo has no concept of "disabled features". Your dependency can request certain set of features, and cargo will make sure that at least that set of features is enabled. There is no way to ask for a particular feature not to be enabled. You will see the "blocking" feature if any of the libraries that depend on that version of `reqwest` requested it.

**Comment by ehuss** [comment]
Closing as this is likely expected behavior.
There's more information in the docs if you'd like: [features](https://doc.rust-lang.org/cargo/reference/features.html), [resolver](https://doc.rust-lang.org/cargo/reference/resolver.html), [unification](https://doc.rust-lang.org/cargo/reference/resolver.html#features).
