### ISSUE TITLE
Breaking change in `cargo_util` 0.1.3, in semver-minor version!

### ISSUE THREAD

**Issue by steffahn** [rust-lang/cargo#10803]
### Problem

[ProcessBuilder::get_args](https://docs.rs/cargo-util/0.1.3/cargo_util/struct.ProcessBuilder.html#method.get_args) returns an `impl Iterator<Item = &OsString>` now, whereas [previously](https://docs.rs/cargo-util/0.1.2/cargo_util/struct.ProcessBuilder.html#method.get_args), it returned `&[OsString]`.

This has the effect that non-locked builds of `cargo-outdated` and `cargo-geiger` fail (these crates are depending on `cargo` `1.61` or `1.60`).

**Comment by ehuss** [comment]
Apologies for that, we need to be more vigilant in handling versions around here.

I'll start the process of getting a version bump and yanking 0.1.3 of cargo-util.

**Comment by ehuss** [comment]
I have yanked cargo-util 0.1.3 and cargo 0.63.0 and published new versions (0.2.0 and 0.63.1 respectively).
Please let me know if you have any issues.

Closing as fixed by #10806.

**Comment by sdroege** [comment]
That fixes it, thanks!

**Comment by steffahn** [comment]
Can confirm this resolves the problems :-)
