### ISSUE TITLE
Debian bullseye build cargo or rustc on armv5 (Linkstation NAS)

### ISSUE THREAD

**Issue by VR-Punk** [rust-lang/cargo#10808]
### Problem

hi,

debian stable provides rustc 1.48.0 and cargo 1.46.0, but I need a newer version which supports the "Edition 2021".
But if i want to build cargo I will get an error:

git clone https://github.com/rust-lang/cargo
cd cargo
cargo build --release

error: failed to parse manifest at /cargo/Cargo.toml

Caused by:
failed to parse the edition key

Caused by:
this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

and for rustc:

git clone https://github.com/rust-lang/rust.git
cd rust
cp config.toml.example config.toml
./x.py build && ./x.py install

downloading https://static.rust-lang.org/dist/2022-05-20/rust-std-beta-armv5te-unknown-linux-gnueabi.tar.xz

RuntimeError: src/stage0.json doesn't contain a checksum for dist/2022-05-20/rustc-beta-armv5te-unknown-linux-gnueabi.tar.xz. Pre-built artifacts might not be available for this target at this time, see https://doc.rust-lang.org/nightly/rustc/platform-support.html for more information

### Version

```text
cargo version --verbose
cargo 1.46.0
release: 1.46.0

rustc --version
rustc 1.48.0
```

**Comment by ehuss** [comment]
Cargo can only be built with the latest stable version of Rust.

Since prebuilt artifacts are not available for armv5te-unknown-linux-gnueabi, it will take a bit of work. You'll either need to cross-compile from a host that is supported, or you may be able to incrementally build each version using your existing Rust installation.  For example, download the 1.49 sources of Rust, configure it to use your local 1.48 installation in config.toml, and build rustc and cargo. Then repeat for each successive version.

**Comment by VR-Punk** [comment]
How do i configure my 1.49 config.toml  to use my local 1.48 installation to upgrade to 1.49 ?

**Comment by ehuss** [comment]
Set the `cargo` and `rustc` values to the path of your locally installed 1.48 (see [example](https://github.com/rust-lang/rust/blob/7425fb293f510a6f138e82a963a3bc599a5b9e1c/config.toml.example#L214-L220)).

**Comment by VR-Punk** [comment]
thx a lot ,
but i have still the same error

./x.py build && ./x.py install
unknown cpu type: armv5tel

rustc 1.48 is installed 

and i changed in the config.toml of rustc 1.49:

# Instead of downloading the src/stage0.txt version of Cargo specified, use
# this Cargo binary instead to build all Rust code
cargo = "/bin/cargo"

# Instead of downloading the src/stage0.txt version of the compiler
# specified, use this rustc binary instead as the stage0 snapshot compiler.
rustc = "/bin/rustc"

**Comment by ehuss** [comment]
Unfortunately it looks like you'll need to apply some patches to the rust repo to make it work for armv5tel.  I recommend looking at debian's build scripts and patches to see what they do. This issue tracker probably isn't the best place to get support for building Rust for an unsupported target. I recommend trying one of the user forums such as https://users.rust-lang.org/ or check if there are any debian forums.

Closing as this isn't particularly a cargo issue.
