### ISSUE TITLE
cargo doc generated files contain references to absolute pathes

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#1081]
```
<meta name="description" content="Source to the Rust file `src/lib.rs`.">
<meta name="description" content="Source to the Rust file `/home/user/…/src/lib.rs`.">
```

The first description as generated by invoking `rustdoc` directly. The second one, generated by invoking `cargo doc`, contains full path to the file on the developer machine.

**Comment by alexcrichton** [comment]
I think this will be fixed by https://github.com/rust-lang/cargo/pull/1164, but please feel free to reopen if it still happens afterwards!
