### ISSUE TITLE
cargo install fails while feching crates.io index with "invalid distance too far back; class=Zlib"

### ISSUE THREAD

**Issue by araruna** [rust-lang/cargo#10815]
### Problem

While trying to install any binary crate from a fresh system installation, `cargo` fails to fetch the crates.io index everytime, reporting the following error:
```
    Updating crates.io index
warning: spurious network error (2 tries remaining): invalid distance too far back; class=Zlib (5)
warning: spurious network error (1 tries remaining): invalid distance too far back; class=Zlib (5)
error: Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  invalid distance too far back; class=Zlib (5)
```

### Steps

1. Get a fresh installation of cargo (in order to force fetching the crates.io registry)
2. Try to install any binary crate (in my case `paru`) with `cargo install paru`

### Possible Solution(s)

I believe this actually is some problem with Zlib, as I have found several bug reports containing the same message related to several different technologies, but none of the suggested solutions I found worked or were even applicable.

### Notes

I just installed the latest stable toolchain by running `rustup toolchain install stable`. The version of `rustup` is `1.24.3 (2021-11-09)`.

The problem still reproduces with different connection types (wired/wireless connection, and with/without VPN).

### Version

```text
cargo 1.62.0 (a748cf5a3 2022-06-08)
release: 1.62.0
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1n)
os: Manjaro 21.3.1 (Ruah) [64-bit]
```

**Comment by araruna** [comment]
I deleted the old registry and tried again. Unfortunately, the error still happens.

This is the debug info I got from running it with the provided command line: https://mega.nz/file/7gYTXa4B#zUADXp9LGrKqyURcABtGCs1MNftynRJSqDoxaNpY6-I

This is a recording of the process (without the debug commands): https://asciinema.org/a/jwrfnv1jdDBwdZxDpJ9OV0qqu

**Comment by ehuss** [comment]
Unfortunately the logs aren't illuminating anything for me.  I tried accessing the same IP for GitHub and wasn't able to reproduce. I also tried on Manjaro linux just in case there was anything unique about that, but I wasn't able to repro there.

My only suggestion is to try with the [`net.git-fetch-with-cli`](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli) option (you can quickly try with the `CARGO_NET_GIT_FETCH_WITH_CLI=true` environment variable).

**Comment by araruna** [comment]
Strangely, I can't reproduce the problem anymore... Even after trying to delete the cache.

This is unfortunate (although I'm finally able to carry on...). I'll close the issue by now and if something related happens again I'll comment again.

Than you.

**Comment by ehuss** [comment]
> Strangely, I can't reproduce the problem anymore... Even after trying to delete the cache.

The index was squashed yesterday bringing the size down from 237M to 62M, so that is likely the reason it changed. I'll keep an eye out to see if anyone reports the same error when it grows again.
