### ISSUE TITLE
`cargo build` reports `fatal: couldn't find remote ref HEAD`

### ISSUE THREAD

**Issue by jiangying000** [rust-lang/cargo#10826]
### Problem

`cargo build` throws `fatal: couldn't find remote ref HEAD` on an normal repo.

for more details please take a look at https://github.com/starcoinorg/starcoin/issues/3508

### Steps

this is difficult to reproduce intentionally

**Comment by ehuss** [comment]
I posted #10829 with a fix.  I'm guessing the checkout process got interrupted, and cargo wasn't able to recover from that correctly.

As a workaround, as you noticed you can disable the git-fetch-with-cli. Or, you can delete `~/.cargo/git/checkouts/` (or whichever subdirectory underneath that is causing you trouble).
