### ISSUE TITLE
Sparse-registry fetching total size keeps increasing

### ISSUE THREAD

**Issue by pickfire** [rust-lang/cargo#10820]
### Problem

From original thread https://internals.rust-lang.org/t/call-for-testing-cargo-sparse-registry/16862/20?u=pickfire

> One thing I noticed is that the fetching need to go through several loops now, previously it just fetch until 100% then done, but now when it reached 100%, then it had to fetch another time again, and the total stuff needed to fetch which keeps increasing (1 -> 10 -> 50 -> 100 -> 130) resulting in the progress decreasing, feels weird.
>
> I feel like the total should be - until there is a definite answer to the total number that needs to fetch then only show it rather than keep increasing it.

### Steps

1. `rustup update nightly`
2. `cargo +nightly -Z sparse-registry update`

### Possible Solution(s)

> A way to improve that in the registry would be to on publish, provide an optional `expected_dep_forest_size` from the number of transitive dependencies used at publish time. This number could be used to provide a reasonable progress estimate quickly.

**Comment by arlosi** [comment]
This is expected behavior, but I understand it's confusing to have progress go backwards. 

@rustbot modify labels: -C-bug +C-enhancement

**Comment by arlosi** [comment]
Some additional ideas on what we could do.

## Remove the progress bar
* But keep the `X/Y` status. `Y` will still change as deps are discovered.
```
Fetching (35/38)
```

## Include an estimate of the dependency graph size when publishing
* Dependency graph size can change depending on features, platform, etc.
* Would require running a batch job to generate for all existing crate versions
* Increases metadata size

## Attempt to run the resolver using cached metadata to get an estimate
* Only works if the local cache is fresh
* Wastes CPU time

## Use the lockfile to get an estimate of the total number of dependencies
* Only works if a lockfile is present.

**Comment by arlosi** [comment]
Maybe instead of `35/38` something like:
```
Fetching (35 completed; 3 downloading)
```

**Comment by pickfire** [comment]
Or maybe `X/N+3` then until it is confirmed, `X/Y`

**Comment by arlosi** [comment]
What do you mean by confirmed? Each dependency that's fetched could potentially require additional dependencies that aren't fetched yet.

**Comment by pickfire** [comment]
Confirmed as in cargo knows that there won't be any additional dependencies.
