### ISSUE TITLE
cargo build using uncalled target variables

### ISSUE THREAD

**Issue by sadilekivan** [rust-lang/cargo#10840]
### Problem

Correct me if it's intentional, but I think this isn't.

`cargo` checks the linker path of the local machine architecture target even if that target was not called. It does not do this for any other target.

It causes trouble when cross-compiling, for example with `cross` the linker won't be mounted in docker. And even if compiling to a different target where that linker is not needed it causes an error.

### Steps

1. Setup a project `.cargo/config.toml` with one target of your local machine architecture, my is `x86_64-unknown-linux-gnu`:
```
[target.x86_64-unknown-linux-gnu] #My local machine
linker = "non_existing_linker_gnu"
```
2. Build for any other target
```
cargo build --target aarch64-unknown-linux-gnu
   Compiling libc v0.2.126
...
error: linker `non_existing_linker_gnu` not found
...
```
4. Try this with a different target than local machine
```
[target.x86_64-unknown-linux-gnux32] #Not my local machine
linker = "non_existing_linker_gnux32"
```
5. Build for other targets than `x86_64-unknown-linux-gnux32`, even `cargo build` works

### Version

```text
cargo 1.62.0 (a748cf5a3 2022-06-08)
release: 1.62.0
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1n)
os: Fedora 36 (ThirtySix) [64-bit]
```

**Comment by ehuss** [comment]
Build scripts and proc-macros are still built for the host, and will use whatever linker is specified for the host target.

**Comment by sadilekivan** [comment]
Thanks, it's clear to me now!
