### ISSUE TITLE
Path to test completion

### ISSUE THREAD

**Issue by volucris1** [rust-lang/cargo#10841]
### Problem

If i wanna test something special like: "a::b::c::test::test_group::test_name" cargo won't complete this path. Of course i can just type "test_name" but it still without completion. Is it be possible?

**Comment by weihanglo** [comment]
I guess you were talking about editor/IDE experience. And that might be sort of resposibliity of [rust-analyzer](https://rust-analyzer.github.io/)

Could you elaborate more on what your scenario is and where you want cargo to complete stuff?

**Comment by volucris1** [comment]
I'm talking about completion in command line (bash/zsh/fish). But you right, it sounds more likely thing for editor

**Comment by weihanglo** [comment]
Thank you for the reply!

I am afraid it is not possible at this moment. Completing a module path or an item requires sort of parsing the info from test harness. #7864 are tracking a more stable programmatic way to list all the tests. Close in favour of that. Thanks!
