### ISSUE TITLE
Extra period in documentation

### ISSUE THREAD

**Issue by johnmatthiggins** [rust-lang/cargo#10845]
### Problem

There is an extra period in the cargo documentation on the `cargo::ops` page.

### Steps

Go to the [cargo::ops](https://docs.rs/cargo/latest/cargo/ops/index.html) page, you can see it in the description of `resolve_with_previous`.

### Possible Solution(s)

Remove the period.

### Version

```text
cargo 1.64.0 (b1dd22e66 2022-07-09)
```

**Comment by weihanglo** [comment]
Good spot! Here is what goes wrong, and don't hesitate to send a fix for doc improvement!

https://github.com/rust-lang/cargo/blob/b1dd22e668af5279e13a071ad4b17435bd6bfa4c/src/cargo/ops/resolve.rs#L212-L227
