### ISSUE TITLE
failed to download `aho-corasick v0.7.18`

### ISSUE THREAD

**Issue by ash-hashtag** [rust-lang/cargo#10858]
### Problem

when building a docker image at(haven't tested locally)
RUN cargo chef cook --release --recipe-path recipe.json:
#13 0.774     Updating crates.io index
#13 1.664  Downloading crates ...
#13 1.689 error: failed to download `aho-corasick v0.7.18`
#13 1.689
#13 1.689 Caused by:
#13 1.689   unable to get packages from source
#13 1.689
de: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.37/src/recipe.rs:156:27

#14 3.488 note: this is an unexpected cargo internal error
#14 3.488 note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
#14 3.488 note: cargo 1.62.0 (a748cf5a3 2022-06-08)
#14 3.492 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.37/src/recipe.rs:156:27

```text
cargo 1.61.0 (a028ae42f 2022-04-29)
release: 1.61.0
commit-hash: a028ae42fc1376571de836be702e840ca8e060c2
commit-date: 2022-04-29
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.22000 (Windows 10 Home Single Language) [64-bit]

wait whaaaat? I'm on windows 11
```

**Comment by epage** [comment]
> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.37/src/recipe.rs:156:27

It looks like that panic is coming from `cargo-chef`, a third-party plugin into cargo.  See https://github.com/lukemathwalker/cargo-chef

**Comment by ash-hashtag** [comment]
I opened issue there and they sent me back here :( telling issue was with cargo and crates.io

**Comment by epage** [comment]
The panic came from within cargo-chef.  If they have more details as to what went wrong within cargo or reproduction steps outside of cargo-chef,. that'd be a help.
