### ISSUE TITLE
Cargo build - Native Cross compiling binary for Win, Linux, MacOS, Arch64, etc like Golang

### ISSUE THREAD

**Issue by MeRahulAhire** [rust-lang/cargo#10873]
### Problem

Hi, I'm Using Windows PC and wanted to compile for Linux and MacOS. I though it'd be as simple as what Go might be doing but turns out there's no specific easy process to this. I've read many solutions for it and most of them suggest using docker to build the binaries.

Basically what I'm requesting is Rust to support cross compiling for any platform like Golang without any additional configuration.

**Comment by ehuss** [comment]
Hi!  Thanks for the suggestion!  I understand it can be frustrating to get cross-compiling set up correctly, and that Go has a much smoother experience.  This isn't something that can be addressed through an issue on the Cargo repository, and is likely to be a very large task that would require a large investment.  It would likely require putting together a working group, or some other coordinated group of people.  Closing as this isn't something we can track here.

**Comment by MeRahulAhire** [comment]
appreciate your comment, I can understand it. 

It works fine for native windows build but just need your help that how to install linker '`cc`' on windows?
I'm using this command:
```zsh
cargo build --target=x86_64-apple-darwin 
```
and it generates error like below
```zsh
Compiling rust v0.1.0 (C:\Users\rahul\Desktop\rust)
error: linker `cc` not found
  |
  = note: program not found

error: could not compile `rust` due to previous error
```

**Comment by weihanglo** [comment]
Basically, you need at least a cross-compiling linker installed and set it in `.cargo/config.toml` via [`target.<triple>.linker`](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinker) or rustflags. Might also require target specific library existing to make it work.

There are [several](https://users.rust-lang.org/t/38323/) [posts](https://users.rust-lang.org/t/72664/) out there on user forum discussing cross compilation. They should be worth a read.

**Comment by MeRahulAhire** [comment]
Thanks for the info. It works better on WSL but still having issue for apple silicon. Do we strictly need M1 mac for `arch64-darwin` compilation?
