### ISSUE TITLE
Linker cc not found

### ISSUE THREAD

**Issue by AlePon123** [rust-lang/cargo#10897]
### Problem

I installed gcc and cmake 
but cargo gives me error : 
 cargo build
   Compiling serde v1.0.140
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

### Notes

i'm using nixos 22.05

### Version

```text
1.62.1
```

**Comment by weihanglo** [comment]
Usually, installing gcc would resolve this issue. That's a bit strange as you already did that. Could you provide a minimal `configuration.nix` file that reproduces your issue?
