### ISSUE TITLE
Cannot set TARGET_*_RUNNER to a binary whose filename contains a whitespace

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#10892]
Is it possible that when I set `TARGET_*_RUNNER` to a value like `C:\Users\Good Game\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo-miri.exe`, that cargo will split this at the whitespace and try to run the binary `C:\Users\Good`?  That is my conclusion of what happens in https://github.com/rust-lang/miri/issues/2417, which took me by surprise. After all, RUSTC_WRAPPER, RUSTC and RUSTDOC work fine when they contain whitespace. Only the runner variables seem to have this strange behavior.

Reading the docs more carefully now, [this says](https://doc.rust-lang.org/cargo/reference/config.html#targettriplerunner) "Type: string or array of strings". I guess that helps for when the variable is set via toml, but when I set this via the environment (which I think is our only choice here), then how do I configure a runner that is stored in a directory that contains a whitespace in its name? It looks like StringList (which I think is where this ends up?) interprets a single string as being separated at whitespaces, rather than interpreting it as a one-element list of strings.

**Comment by ehuss** [comment]
I would recommend using the newly stabilized `--config` CLI option if possible.  Otherwise, you cannot pass commands with spaces in them for `CARGO_TARGET_<triple>_RUNNER`.

**Comment by RalfJung** [comment]
`--config`? Sounds intriguing! Yes we could probably set that when invoking `cargo rust/test` from cargo-miri. I'll look into it.

**Comment by RalfJung** [comment]
To make sure I understand correctly: would something like this
```
--config "target.'cfg(true)'.runner=['cargo-miri', 'runner']"
```
make  cargo call `cargo-miri runner ...` to invoke all binaries?

How to quotes have to be escaped in the binary name? If I understand https://toml.io/en/v0.3.0 correctly, I should do the following:
- replace all `\` by `//` and all `"` by `\"`
- and then surround the string in `"`

**Comment by ehuss** [comment]
Depends on how you are launching cargo (whether it is from a shell script or from Rust).  

Escaping `\` and `"` should be sufficient, yea.

https://doc.rust-lang.org/nightly/cargo/reference/config.html#command-line-overrides gives some examples of different ways to escape things via shell.

**Comment by RalfJung** [comment]
We are launching it from Rust.

**Comment by RalfJung** [comment]
The `cfg(true)` does not seem to be working. Looks like I need to give the target explicitly.

I tried this on the terminal (in a random project, I used xargo):
```
cargo +nightly "run" "-v" "--target" "x86_64-unknown-linux-gnu" "--config" "target.'cfg(true)'.runner=[\"nonsense\", 'runx']"
```
and expected an error, but it actually works fine. If instead I do
```
cargo +nightly "run" "-v" "--target" "x86_64-unknown-linux-gnu" "--config" "target.x86_64-unknown-linux-gnu.runner=[\"nonsense\", 'runx']"
```
then I get the expected error.

**Comment by RalfJung** [comment]
Also it looks like https://github.com/rust-lang/cargo/pull/8629 hasn't entirely fixed the issue in the PR description... when I pass `"--config" "target.x86_64-unknown-linux-gnu.runner=[\"nonsense\", 'runx']"` twice, it concatenates the two arrays!

**Comment by ehuss** [comment]
`true` is never a truthy cfg expression. It's the same as saying `cfg(foobar)`.  I don't think there is a way to specify something unconditionally.

**Comment by RalfJung** [comment]
Ah, that's a bummer, but you are right -- it doesn't work in rustc either.

But `all()` works in rustc, so maybe it works here, too... after all, universal quantification over the empty set is true. ;)

**Comment by RalfJung** [comment]
Okay, this seems to be working. Thanks a lot. :D

I will close this issue, since the issue with setting a runner with spaces is resolved. I will open a new issue for what double-`--config`.
