### ISSUE TITLE
Tracking Issue for source replacement ambiguity

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#10894]
### Summary

RFC: [#3289](https://github.com/rust-lang/rfcs/pull/3289)
Implementation: https://github.com/rust-lang/cargo/pull/10907
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/source-replacement.html

This RFC is to resolve the interaction of source-replacement and registry API operations like publishing.

### Unresolved Issues

* [x] Should the `--registry <NAME>` command line argument be allowed to reference the name of a `source` from the `[source]` table as well?  Resolved: At this time, `--registry` does *not* support `[source]` names.  (However, `[source]` `replace-with` *can* reference `[registries]` names. So there is some overlap.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by arlosi** [comment]
@ehuss could you update the Implementation link to #10907

**Comment by ehuss** [comment]
Closing as I believe this is resolved by #10907.
