### ISSUE TITLE
Features added in dev-dependencies are always active inside a virtual workspace

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/cargo#10909]
### Problem

If a crate has a dependency as both a normal dependency and as a dev-dependency, then the features it activates for the dev-dependency will be active during a normal build _iff_ that crate is a member of a virtual workspace.

### Steps

Playground building a local workspace showing the error: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=36347271fd4c23914346a6df034dc1dd

The `Error` is expected, it is the panic at the end that should not happen.

### Notes

Found while investigating https://github.com/rust-lang/docs.rs/issues/1783

**Comment by Eh2406** [comment]
[resolver](https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions) and workspaces interact oddly, see https://github.com/rust-lang/cargo/issues/10745#issuecomment-1152612730

**Comment by Nemo157** [comment]
Ok, setting `workspace.resolver = "2"` does fix it; and it looks like https://github.com/rust-lang/cargo/issues/10112 tracks adding a warning that would have instantly diagnosed this.
