### ISSUE TITLE
`cargo update --precise` without `-p` flag silently succeeds and runs `cargo update`

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/cargo#10919]
### Problem

I tried to use `cargo update` with the `--precise` flag to downgrade a dependency without reading the docs.

I tried:

```console
$ cargo update --precise chrono-tz@0.6.1
    Updating crates.io index
```

This succeeded with no error and did not do what I expected.

The docs mention that `--precise` is meant to be combined with the `-p` flag:

> When used with `-p`, allows you to specify a specific version number to set the package to. If the package comes from a git repository, this can be a git revision (such as a SHA hash or tag).

### Steps

run `cargo update --precise chrono-tz@0.6.1`

### Possible Solution(s)

The docs mention that `--precise` is meant to be combined with the `-p` flag. If `--precise` is given without `-p`, I think this should be an error.

### Version

```text
cargo 1.62.1 (a748cf5a3 2022-06-08)
release: 1.62.1
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.5.0 [64-bit]
```

**Comment by weihanglo** [comment]
I'd suggest starting a transition period that warns users it's a no-op. Steps to fix might like:

1. When `--precise` or `--aggressive` is present but zero `-package` given, emit a warning inside [`update_lockfile()`](https://github.com/rust-lang/cargo/blob/d56b42c549dbb7e7d0f712c51b39400260d114d4/src/cargo/ops/cargo_generate_lockfile.rs#L38)
2. Turn it into hard error once the warning hits stable Rust release. That is, the transition period would be three months.
3. In addition, leverage clap's [`requires`](https://docs.rs/clap/3/clap/builder/struct.Arg.html#method.requires) to enforce the hard requirement relationship as epage suggested.
