### ISSUE TITLE
Allow `cargo publish --dry-run` even if publish=false

### ISSUE THREAD

**Issue by tranzystorek-io** [rust-lang/cargo#10922]
### Problem

`cargo publish --dry-run` fails immediately if `publish=false` is set in manifest.

### Proposed Solution

Allow dry-run to run to completion in all cases.

**Comment by ehuss** [comment]
Can you say more about why you would want to try to publish something that is explicitly marked to not publish?

`cargo package` will do almost the equivalent of `cargo publish --dry-run`, so I suggest using that instead.

**Comment by tranzystorek-io** [comment]
That's an alternative. I wanted to add `publish = false` to a crate that did `cargo publish --dry-run` as a test in CI, might be pointless when I give it a second thought...

**Comment by ehuss** [comment]
I'm going to close as I think having `cargo publish --dry-run` fail in this case is the correct action, as the package is explicitly indicating it does not support publishing, and `--dry-run` is there to detect errors like that.
