### ISSUE TITLE
Cargo build twice with compile-time errors

### ISSUE THREAD

**Issue by sim4life** [rust-lang/cargo#1092]
If `cargo build` command is performed on a script that has compile-time errors, it prints some errors on command line console. However, if `cargo build` is performed again without changing the code, it does not print the previous compile-time errors misleading that `cargo build` has worked successfully.
Kindly, make `cargo build` print any previous errors/warnings if the code hasn't changed and if there were some errors/warnings in the previous `cargo build`.

**Comment by alexcrichton** [comment]
I think this may have been a transient issue, I'm able to reproduce, so closing.
