### ISSUE TITLE
cargo tree: feature request: print features used to build each crate in tree

### ISSUE THREAD

**Issue by fschutt** [rust-lang/cargo#10949]
### Problem

This is a re-open of https://github.com/sfackler/cargo-tree/issues/18 - the issue seems to have gotten dropped silently when the repository was merged into rust-lang/cargo. Often times, when debugging why certain dependencies are pulled in, it is important to know which features are enabled on the crates dependencies (in order to debug what features depend on each other). Dealing with feature flags that depend on each other is currently a mess in larger projects.

### Proposed Solution

An example of what I'd like to see is something like this (printing the enabled as well as the available features):

```sh
$ cargo tree --print-features
wasmer-cli v3.0.0-alpha.4 ["http", "wasi", "wat"] # inactive: ["cache", "emscripten", "compiler"]
├── http_req v0.8.1 ["rustls", "webpki", "webpki-roots"] # inactive: ["native-tls"] 
│   ├── rustls v0.19.1 [...]
```

**Comment by ehuss** [comment]
This is available with the format flag: `cargo tree -f "{p} {f}"`

The [cargo tree](https://doc.rust-lang.org/cargo/commands/cargo-tree.html#examples) docs include some examples of how to explore features.

**Comment by fschutt** [comment]
Alright, then this issue can be closed, thank you.
