### ISSUE TITLE
CARGO_LOG is not documented in cargo reference

### ISSUE THREAD

**Issue by rfjakob** [rust-lang/cargo#10947]
### Problem

The environment variable `CARGO_LOG` exists, is talked about (example: https://stackoverflow.com/questions/70174147/how-do-i-make-cargo-show-what-files-are-causing-a-rebuild/70174212#70174212 ) and changes cargo's behavoir.

But is not listed on
* https://doc.rust-lang.org/cargo/reference/environment-variables.html
* https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/environment-variables.md

### Possible Solution(s)

Add it to https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads

### Version

```text
https://github.com/rust-lang/cargo/blob/e6827eee9b6720a1bd69c6115cac22f8125b24aa/src/doc/src/reference/environment-variables.md
```

**Comment by weihanglo** [comment]
Thanks for the report! We do have `CARGO_LOG` [documented in Cargo contributor guide](https://doc.crates.io/contrib/architecture/console.html#debug-logging). It's more like an internal debugging variable but might be worth mentioning in general user guide. Need some word tweaks tho.
