### ISSUE TITLE
please update to os_info = "3.5.0" to fix os detection for various linux distros

### ISSUE THREAD

**Issue by stefson** [rust-lang/cargo#10940]
### Problem

on linux-x64 (gentoo in my case) `cargo -Vv` shows wrong value for `os`: 

```
cargo 1.64.0-nightly (4fd148c47 2022-08-03)
release: 1.64.0-nightly
commit-hash: 4fd148c47e733770c537efac5220744945d572ef
commit-date: 2022-08-03
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: OracleLinux 2.8.0 [64-bit]
```

the actuall fix in https://github.com/stanislav-tkach/os_info/pull/317 is part of os_info v.3.5.0, please pull that update into the cargo nightly. Thank you.

**Comment by weihanglo** [comment]
Thank you for this posting! 
The way to update is relatively simple. Updating [`os_info` in Cargo.toml](https://github.com/rust-lang/cargo/blob/master/Cargo.toml#L49) to `os_info = 3.5.0` should be sufficient.

**Comment by stefson** [comment]
@weihanglo thanks for the fix; however I'm not very familiar with how the rust/cargo live branch works - how will the update be pulled into `rust-lang/rust`?  I just compiled the live branch, and their cargo is actually four days old :D

**Comment by weihanglo** [comment]
The process [has been documented here](https://doc.crates.io/contrib/process/release.html#submodule-updates). Generally, Cargo team updates it about once a week. Whoever wants to update can follow the guide and post an PR against rust-lang/rust.

**Comment by stefson** [comment]
thanks, that sounds like a little over the top for my needs. I'll just wait happily for the update to be pulled in through rust-lang/rust git branch, so that I can confirm the fix (hopefully)
