### ISSUE TITLE
can't install cargo target manually

### ISSUE THREAD

**Issue by nicolasJJJ** [rust-lang/cargo#10957]
### Problem

Hello,

I have a company computer in witch i cannot install rustup. However, Rustc and cargo are installed.
I need a linux target to build an executable, compatible with GLIBC 2.17 as said Stack Over Flow : https://stackoverflow.com/questions/63724484/build-and-bind-against-older-libc-version

### Steps

1. I downloaded the x86_64-unknown-linux-musl target with this link : https://download.eclipse.org/justj/?file=zenoh/zenoh/0.5.0-beta.9/x86_64-unknown-linux-gnu

2. I changed my project's cargo.toml  :

[target.x86_64-unknown-linux-gnu]
runner = "C:\\xxxxx\\x86_64-unknown-linux-gnu" as said in Rust Cookbook

3. cargo build --target x86_64-unknown-linux-gnu

**_4. the `x86_64-unknown-linux-gnu` target may not be installed_**

### Notes

Where are installed "rustup target add ****" outputs and how to use it ??
Thank you in advance !

Sincerly yours

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
host: x86_64-pc-windows-msvc
```

**Comment by weihanglo** [comment]
The general steps to add a target without rustup installation is like the followings (untested, use at your own risk):

1. Download the specific target tarball from official static assets, e.g. https://static.rust-lang.org/dist/rust-std-1.58.0-x86_64-unknown-linux-musl.tar.gz
2. Unpack the tarball and there should be a `rustlib/<target>` folder.
3. Determine where current rustc installed via the command `rustc --print sysroot`. A `rustlib` folder should be there.
4. Move and merge the `rustlib/<target>` folder we download to the `rustlib` installation location.

Seems like you are trying to cross-compile Linux target on a Windows machine. There might be much more work than that. I'd suggest you to ask usage questions on [Rust user forum](https://users.rust-lang.org). People there generally more helpful for these kind of topics. I am going to close this issue as it is not Cargo specific. Feel free to comment below if you have different thoughts.
