### ISSUE TITLE
Add hg flag to Cargo config

### ISSUE THREAD

**Issue by sscherfke** [rust-lang/cargo#1095]
In Cargo’s config file, you can set `git = true|false`. It would be coul if you could also set `hg = true` here in order to create an hg repo by default.

**Comment by tshepang** [comment]
Since16d3e72a8fd71de9df1fab8ef8c791d5f7666ad0, one can now do this:

```
[cargo-new]
vcs = "hg"
```

**Comment by alexcrichton** [comment]
Ah yes, thanks @tshepang!
