### ISSUE TITLE
No implicit dependencies

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang/cargo#1096]
Currently all cargo packages implicitly depend on both std and it's backing crates---Even though you need to explicitly `extern` core, alloc, etc, rustc always sees those crates on its link path, and if you try to make your own crate with that name, it will cause a conflict.

This is a practical problem for people working on freestanding with cargo: I was rebuilding core for some reason. Then, when they go to link their project with their core and rlibc, I got an error saying there are multiple crates named core. Modifying core is probably not necessary for freestanding use (and indeed I was able to avoid the need to do so), but rebuilding alloc with the new flag to allow it to use heap functions defined elsewhere almost always is. Were somebody to link another crate depending on alloc, they would run into the same issue.

I propose making it so cargo will configure rust to not link any crate it explicitly tells it about. This seems to be the simplest and most intuitive remedy. That means that users using libstd will have to add that as a dependency. I understand that it may not be convenient to actually supporting building std or its backing crates with cargo at this time, in which case I propose just hacking cargo to special case on that dependency. The hack is ugly, but it can be transparently removed in the future. I do think it is important to do this in the short-term (if it is done at all), because the more mature the cargo ecosystem gets, the harder it will be to get everyone to update their dependencies.

While I am a not big fan of `#![no_std]`, or rustc implicitly linking crates in the first place, I understand the argument concerning programming in the small in their favor. I'd argue however that once somebody is writing a cargo project, they are effectively programming in the large, and thus my proposal, while slightly more verbose in the common case, is justified.

**Comment by steveklabnik** [comment]
closing in favor of https://github.com/rust-lang/rfcs/pull/1133
