### ISSUE TITLE
Add flag that set working directory for `cargo run`

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang/cargo#10974]
### Problem

Today I found myself needing to run `cargo run` in a directory separated from the Rust project. If I attempt `cd $target_dir && cargo run`, it would only emit an error for missing `Cargo.toml`. The only way to do it was to add `$project/target/debug` to `$PATH` but it would come with its own set of inconveniences.

### Proposed Solution

Implement a flag named `--work-dir <DIR>` (or whatever name you may find more intuitive and conventional) to `cargo run` to let user set working directory for the binary before run.

**Comment by epage** [comment]
Alternatively, you can do `cargo run --manifest-path <toml path>` though that can run into issues, see https://github.com/rust-lang/cargo/issues/2930. To work around that, we are considering https://github.com/rust-lang/cargo/pull/10952

Some quick thoughts:
- resolving this feels like the workarounds are piling up.
- we'd need to make the distinction between this and `-C` clear.

**Comment by ehuss** [comment]
In addition to the above, cargo will run the executable from wherever cargo is run from. If it is outside of your project directory, you can pass `--manifest-path` to specify where the project is.

I'm going to close with the same reasoning from https://github.com/rust-lang/cargo/issues/9864#issuecomment-949795033, which lists several other workarounds.

**Comment by epage** [comment]
@ehuss what are your thoughts on the limitation of `--manifest-path` while we don't have a path forward on #2930?

(personally, I've not needed config files and make heavy use of `--manifest-path` to run bins our of source)

**Comment by ehuss** [comment]
If the user wants the equivalent of `cargo build && cd /some/path && /path/to/project/target/debug/foo` to pick up the config files, I think scripting that with something like xtask or the other suggestions in the linked issue is probably the best path forward now.  Or using seperate terminals.  Or building from an editor and launching in a terminal. There are quite a few different ways to deal with it.

As for the config file discovery issue itself, I think we should continue to scrutinize the use cases that require config files. If there are common tasks that are not environment-specific, those should likely be pushed to `Cargo.toml` or a build script. For example, one use case that some people wanted package-specific config files was to set the target which is now covered by [per-package-target](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#per-package-target).

**Comment by pronebird** [comment]
This is somewhat unfortunate that `cargo run` does not support changing the working directory for the binary. This is especially useful for binaries that are dependent on current directory
