### ISSUE TITLE
dev-dependency propagating out of package and leading to a crash

### ISSUE THREAD

**Issue by rib** [rust-lang/cargo#10980]
### Problem

Debugging a crash in an Android application that uses the cpal audio library I realised it was being caused by an (unused) `ndk-glue` dependency that shouldn't have existed because it's only a dev-dependency for cpal's android example.

Just for reference the panic hit on-device at runtime looked like:
```
INFO [android_debugger] RustStdoutStderr: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\hitus\.cargo\registry\src\github.com-1ecc6299db9ec823\ndk-glue-0.6.2\src\lib.rs:60:39
```
_(providing more detailed context with a backtrace is awkward on Android so sorry I don't have any backtrace that I collected, but the main point of surprise here is that `ndk-glue` really shouldn't have been linked into this application)_

In this case cpal doesn't use `ndk-glue` for anything and the application I'm building is using `android-activity` as a glue layer which conceptually serves the same purpose as `ndk-glue` (handling IPC between the native rust code and Java) and it's important that there can only be a single implementation of the glue layer built into the final cdylib that will be loaded on Android.

I found that I could workaround the crash in the application by simply commenting out the dev-dependency within cpal's Cargo.toml but as far as I understand it, Cargo shouldn't be propagating any dev dependencies outside of the package they are declared in.

Checking Cargo's reference manual I found this wording, which describes what I would have expected:

```
Dev-dependencies are not used when compiling a package for building, but are used for compiling tests, examples, and benchmarks.

These dependencies are not propagated to other packages which depend on this package.
```

### Steps

1. Checkout this branch of `android-activity` which contains a minimal example using cpal: https://github.com/rib/android-activity/tree/cpal-example
2. cd examples/agdk-cpal
3. Tweek the Cargo.toml to comment out the patch for the workaround branch of cpal
4. Compile for Android:
```
export ANDROID_NDK_HOME="path/to/ndk"
export ANDROID_HOME="path/to/sdk"

rustup target add aarch64-linux-android
cargo install cargo-ndk

cargo ndk -t arm64-v8a -o app/src/main/jniLibs/  build
./gradlew build
./gradlew installDebug
```

Or, without going as far a fully building the app, it's possible to just use `cargo ndk -t arm64-v8a tree` to see that ndk-glue is being pulled in, which is the crux of the problem: e.g.:
```
export ANDROID_NDK_HOME="path/to/ndk"
rustup target add aarch64-linux-android
cargo install cargo-ndk
cargo ndk -t arm64-v8a -o app/src/main/jniLibs/  tree
```
A suitable NDK can be downloaded from: https://developer.android.com/ndk/downloads

### Notes

Some additional context for the specific issue can be found here: https://github.com/rib/android-activity/issues/7

The workaround branch for cpal that just comments out the dev-dependency can be found here: https://github.com/rib/cpal/tree/no-ndk-glue-dev-dependency

### Version

```text
$ cargo version --verbose
cargo 1.62.1 (a748cf5a3 2022-06-08)
release: 1.62.1
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Home) [64-bit]
```
```

**Comment by ehuss** [comment]
Version 0.13.5 of cpal doesn't specify ndk-glue as a dev-dependency: https://github.com/RustAudio/cpal/blob/971c463462e3560e66f7629e5afcd6b25c4411ab/Cargo.toml#L55-L59

That was changed recently: https://github.com/RustAudio/cpal/commit/f8b05ade39561169d22496f5acbdf766d4686312

Perhaps you need a newer version?

**Comment by rib** [comment]
cpal master has a ndk-glue dev-dependency here:
https://github.com/RustAudio/cpal/blob/9b7bb33965079aa6ab9799ed010f89ec0fbc683d/Cargo.toml#L24

**Comment by rib** [comment]
> That was changed recently: [RustAudio/cpal@f8b05ad](https://github.com/RustAudio/cpal/commit/f8b05ade39561169d22496f5acbdf766d4686312)

this patch is actually what adds the dev-dependency (instead of it being a dependency)

**Comment by ehuss** [comment]
Right. I'm saying the reproduction at https://github.com/rib/android-activity/tree/cpal-example has the dependency on cpal 0.13.5 which unconditionally depends on ndk-glue.  

Or are you saying that with:

```toml
[patch.crates-io]
cpal = { git = "https://github.com/rib/cpal", branch = "master" }
```

you are also seeing an issue?

**Comment by rib** [comment]
aah, right, I see what you meant - hmm yeah I'm guessing you're right and I jumped the gun by just looking at cpal master which actually probably doesn't have the issue and I was just assuming my change "fixed" it, even though it was probably redundant. my bad, sorry, I'll double check though.

**Comment by rib** [comment]
Yeah, you were right @ehuss - sorry about the noise!
