### ISSUE TITLE
Improve error message for wrong target names

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#10982]
If you type the wrong target name, Cargo presents a rather terse error message:

```
> cargo run --bin foo
error: no bin target named `foo`
```

If the typo detection works, then it will provide a suggestion; but if it does not, then it doesn't print anything.

It would be helpful if cargo provided a list of valid target names. There are two similar cases where it does that:

```
> cargo run
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: abc, xyz
```

or

```
> cargo run --bin
error: "--bin" takes one argument.
Available binaries:
    abc
    xyz
```

I think the case where the typo detection fails, it should just list all the target names, similar to those two other error messages.

[Here](https://github.com/rust-lang/cargo/blob/efd4ca3dc0b89929dc8c5f5c023d25978d76cb61/src/cargo/ops/cargo_compile.rs#L1528-L1542) is where this code lives.

```
cargo 1.65.0-nightly (ce40690a5 2022-08-09)
```

**Comment by weihanglo** [comment]
FYI, [here](https://github.com/rust-lang/cargo/blob/58a961314437258065e23cb6316dfc121d96fb71/src/cargo/util/workspace.rs#L81-L95) is the code printing available targets. It's a bit irksome to make it work peacefully with `fn find_named_targets()` without poking already lengthy arguments list. When fixing this, we should avoid adding complexity to existing code.
