### ISSUE TITLE
Rename --no-git to --no-vcs

### ISSUE THREAD

**Issue by tshepang** [rust-lang/cargo#1099]
I think we had `--no-git` before `hg` was supported. Using `--no-vcs` as replacement now makes more sense.

As a sidenote, I would prefer not to need such a flag. That is, `cargo new` should not create any VCS-related files in the root of the project. These flags should be explicitly requested... `cargo new --hg` or `cargo new --git`. 2 reasons:

* This would avoid exposing preference for one VCS over another
* I think most invocations of `cargo new` are not going to result in a project that is tracked on a VCS

**Comment by crazymykl** [comment]
I strongly disagree with your second point. Everything more complex that "hello world" is put into version control ASAP by every developer I know.

**Comment by tshepang** [comment]
This was fixed by a45aa4ad27884d2a113907623c71d90f3111296d, though differently (and better) than I imagined.
