### ISSUE TITLE
Hide dependencies in build messages

### ISSUE THREAD

**Issue by kkocdko** [rust-lang/cargo#11003]
### Problem

Currently, `cargo build`'s output includes dependencies:

```
   < many many messages that fill my terminal >
   Compiling hyper v0.14.20
   Compiling hyper-rustls v0.23.0
   Compiling axum v0.5.15
    Building [=======================> ] 177/180: axum, ksite
```

I'm modifying a crate which depended by many dependencies, every time `cargo build` will put many many messages into my terminal, this prevent me to browse previous error message or my app's output.

Yeah I can use `--quiet`, but waiting without progress is quite anxiety. IMO maybe this will be fine:

```
    Building [=======================> ] 177/180: axum, ksite
```

Only one line, indicate the progress.

There is already a `--message-format=short` switch but it seems do the same with `human` format:

https://github.com/rust-lang/cargo/blob/3b4df5a54a4987e65422e879554d150a264ae945/src/cargo/core/compiler/mod.rs#L1399-L1402

### Proposed Solution

`MessageFormat::Short` seems useless now, could we let it display progress only?

Or, add a new `MessageFormat::Progress` to do this?

### Notes

( If cargo refused to add this, maybe I wlll create a sub command...

**Comment by epage** [comment]
There is also an semi-active discussion on build output at https://github.com/rust-lang/cargo/issues/8889

**Comment by kkocdko** [comment]
> There is also an semi-active discussion on build output at #8889

Ok I'll try to create / find a sub command. It seems that no many people care about this...
