### ISSUE TITLE
Resolving deltas takes long time 

### ISSUE THREAD

**Issue by ar37-rs** [rust-lang/cargo#11014]
## Problem

Cargo can be very slow updating the crates.io index. You may see a progress bar such as:

```
    Updating crates.io index
       Fetch [=================>       ]  74.01%, (64415/95919) resolving deltas
```

## Workaround

There are three different workarounds for this issue. The following instruction assume that [`CARGO_HOME`](https://doc.rust-lang.org/cargo/guide/cargo-home.html) is the default of `.cargo` in your home directory.

### Use net.git-fetch-with-cli

The [`net.git-fetch-with-cli`](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli) config option will instruct cargo to use the `git` CLI to update the index instead of its built-in git client. The `git` CLI should be more efficient at updating the repository. Enter the following into your global cargo configuration file, usually `~/.cargo/config.toml` (or `~/.cargo/config` for older setups):

```toml
[net]
git-fetch-with-cli = true
```

Or set the environment variable `CARGO_NET_GIT_FETCH_WITH_CLI=true`.

### Delete the index cache

To work around this issue, delete the existing git index in cargo's cache. This will cause cargo to re-download the index which should have minimal deltas to resolve.

For most users, the following should be sufficient:

```bash
rm -rf ~/.cargo/registry/index
```

For Powershell users:

```pwsh
rm -R -Force ~\.cargo\registry\index
```

For Windows cmd users:

```batch
rmdir /s /q %USERPROFILE%\.cargo\registry\index
```

### Switch to the sparse protocol

> **Warning**: This is only available starting in 1.68 (to be released 2023-03-09). Due to a config issue, older releases will forbid setting this option.

In the 1.68 release of Rust, you can opt-in to the new [sparse protocol](https://doc.rust-lang.org/nightly/cargo/reference/registries.html#registry-protocols). This uses HTTPS instead of git to update the index, which should be much more efficient in most cases. In your global `~/.cargo/config.toml` file, enter:

```toml
[registries.crates-io]
protocol = "sparse"
```

Or set the `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse` environment variable.

## Cause

Cargo uses the libgit2 library for handling git operations. Its "delta resolution" algorithm has some inefficiencies, particularly when updating an existing repository that has a chain of historic updates. This issue is tracked upstream in https://github.com/libgit2/libgit2/issues/4674.

## Solutions

There are several approaches that the Cargo Team is investigating for resolving this:

* Enabling the sparse protocol by default.
* Improving the delta resolution algorithm in libgit2.
* More aggressively garbage-collecting or deleting the git index when it grows too large.
* Switching to [`gitoxide`](https://crates.io/crates/gitoxide) for git operations.

**Comment by weihanglo** [comment]
Hi. Supposed your are talking about updating crates.io index, such like this

```
    Updating crates.io index
    Fetch [==============>          ]  63.70%, (76766/170478) resolving deltas
```

It is a known issue and the community are working on this from different angles.

First, Cargo introduced a unstable feature called **sparse index**, which is tracked here[^tracked]. It provides a new way to fetch crate dependencies on demand, without downloading the whole index up front. Please [check its doc](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#sparse-registry) and help us improve and push it to stable!

The other approach is a speedup of Git itself. We're going to do experiments on replacing some of [git2] functionality in Cargo with [gitoxide], which is a more modular, safer, and faster Git implementation in Rust. This doesn't remove the entire "resolve deltas" phase but does accelerate it, not to mention the long lingering performance issue about shallow clone[^shallow] and local index[^local] being fixed.


In the meanwhile, you can use [`net.git-fetch-with-cli`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#netgit-fetch-with-cli) or its equivalent environment variable `CARGO_NET_GIT_FETCH_WITH_CLI` to make git fetching faster.

I am going to close this as each approach has already been tracked by other issues. Thank you for the report!

[git2]: https://crates.io/crates/git2
[gitoxide]: https://crates.io/crates/gitoxide
[^tracked]: https://github.com/rust-lang/cargo/issues/9069
[^shallow]: https://github.com/rust-lang/cargo/issues/1171
[^local]: https://github.com/rust-lang/cargo/issues/9167

**Comment by ar37-rs** [comment]
@weihanglo that's a good news,  thank you for your reply.

**Comment by katopz** [comment]
Just hit this today via
```
cargo install -q worker-build && worker-build --release
```
I've to change it to
```
cargo install worker-build && worker-build --release
```
to see what going on and seem like I get stuck at
```
Updating crates.io index
     Fetch [====>                    ]  20.72%, 7.22MiB/s  
```
for a long waiting time, then i try  again and get
```
 Updating crates.io index
       Fetch [=================>       ]  75.61%, (65996/95304) resolving deltas
```
yet another long waiting time, maybe after update `wrangler` to `2.7.1` or maybe after `rustup update stable` not sure (i did both).

**Comment by steakknife** [comment]
Also experiencing this. Cargo should be using a global anycast HA endpoint something other than leaning on github. It should be minimal, binary, versioned, differential transformations, compressed, authenticated, continuable, and performant... not git.

**Comment by joshuataylor** [comment]
Maybe it's a local Github country mirror issue, my main one is the deltas part. Everything else is okay, but AU is offpeak. I get around 30-90mb/s to Github.

**Comment by Eh2406** [comment]
In addition to the fixes mentioned above dell `~/.cargo/registry` will probably also work. This is a known long-standing bug with libgit2. The process of a clean clone of a repository is linear in the history, but the process of updating into an existing repository is quadratic. Also cargoes index is big and can have a lot of history.

**Comment by Eh2406** [comment]
Apparently the [index normalization](https://github.com/rust-lang/crates.io/pull/5558) was [done today](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/index.20normalization). Which means that today's delta includes a change of almost every file.

**Comment by Eh2406** [comment]
@JohnYepthomi I'm sorry you're having such a frustrating experience. Which of the mitigations have you tried?

**Comment by weihanglo** [comment]
Some good news:

* [Sparse registry is stabilized today in 1.68](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol). You don't need nightly anymore to enable this feature.
* The MVP of gitoxide integration is now behind [`-Zgitoxide`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#gitoxide) unstable flag, starting from `nightly-2023-03-09`. Would appreciate if people can give it a try.

**Comment by weihanglo** [comment]
[Sparse registry is now the default](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html) for crates.io in 1.70. [`-Zgitoxide`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#gitoxide) unstable flag also provides shallow clone on crates.io index since `nightly-2023-05-05` IIRC.

I would say this is largely resolved. Close and thanks everyone.

**Comment by joshlf** [comment]
Does anyone have a suggested fix for this on older Rust versions? I'm currently trying to test on my crate's MSRV (1.57), and so the more recent Cargo fixes aren't available. I believe what I'm seeing is a download issue because there's no "resolving deltas" message printed, but I keep getting network timeouts to GitHub despite my other network traffic behaving as normal. It's timed out multiple times, meaning I literally am unable to update the index, and so I can't compile, period. Has anyone figured out a workaround for the network part of this (notably on older versions of Cargo)?

**Comment by Byron** [comment]
Here is something you can try:

```
cd ~/.cargo/registry/index/github.com-1ecc6299db9ec823
git fetch https://github.com/rust-lang/crates.io-index refs/heads/master:refs/remotes/origin/master
```

That will fetch all objects you are missing, so next time `cargo` tries to fetch it won't have to fetch that much, which hopefully won't timeout.

Please let me know how it goes and good luck!

**Comment by joshlf** [comment]
> Here is something you can try:
> 
> ```
> cd ~/.cargo/registry/index/github.com-1ecc6299db9ec823
> git fetch https://github.com/rust-lang/crates.io-index refs/heads/master:refs/remotes/origin/master
> ```
> 
> That will fetch all objects you are missing, so next time `cargo` tries to fetch it won't have to fetch that much, which hopefully won't timeout.
> 
> Please let me know how it goes and good luck!

Okay I'll try that, thanks!
