### ISSUE TITLE
Have `cargo add --optional <dep>` create a `<dep> = "dep:<dep>` feature

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#11010]
### Problem

This is inspired by my running `cargo add` and seeing a lot of features that might be there only because people have not updated to the new `dep:` syntax to disable unintended implicit features.  For my crates, I'm aware of the syntax and plan to transition my crates.  For others, they might not be aware the feature exists and by us `cargo add` turning it explicit, it would help raise visibility on these features to help lead more people to using it.

In addition,  https://github.com/rust-lang/cargo/issues/10556 mentions the idea of `cargo fix` doing

> possibly define a feature named "package" if it doesn't already exist and dep:package isn't already used

ie by convention moving away from implicit feature declarations.

### Proposed Solution

`cargo add --optional <dep>` would create a `<dep> = "dep:<dep>` feature iff
- `rust-version` is unset or is new enough for the syntax
- `dep:<dep>` doesn't already exist

**Comment by Bina1791** [comment]
> ### Problem
> 
> This is inspired by my running `cargo add` and seeing a lot of features that might be there only because people have not updated to the new `dep:` syntax to disable unintended implicit features.  For my crates, I'm aware of the syntax and plan to transition my crates.  For others, they might not be aware the feature exists and by us `cargo add` turning it explicit, it would help raise visibility on these features to help lead more people to using it.
> 
> In addition,  https://github.com/rust-lang/cargo/issues/10556 mentions the idea of `cargo fix` doing
> 
> > possibly define a feature named "package" if it doesn't already exist and dep:package isn't already used
> 
> ie by convention moving away from implicit feature declarations.
> 
> ### Proposed Solution
> 
> `cargo add --optional <dep>` would create a `<dep> = "dep:<dep>` feature iff
> - `rust-version` is unset or is new enough for the syntax
> - `dep:<dep>` doesn't already exist

**Comment by epage** [comment]
This will be needed for #12826 once we no longer allow optional dependencies to be unreferenced.  I'd propose we go ahead and implement it now to help raise awareness of `dep:` and prepare for that future.

**Comment by epage** [comment]
The contrib guide will soon have some guidance on how we should be handling formatting.  See #12836

**Comment by LuuuXXX** [comment]
Looks like nobody's handling it. I'd like to try it. @rustbot claim
