### ISSUE TITLE
Ubuntu (wsl1 & 2) doesn't support Cargo Build

### ISSUE THREAD

**Issue by xmas7** [rust-lang/cargo#11024]
### Summary

user@DESKTOP-54YU45:/mnt/d/Blockchain/Solana/program-rust$ cargo build
Updating crates.io index

### Unresolved Issues

Tried to use 'Cargo Build' in Ubuntu wsl on Windows rather than Ubuntu Native System.
But it seems not working properly...?

**Comment by Anthony-3** [comment]
D:\Blockchain\Solana\program-rust>cargo build
   Compiling proc-macro2 v1.0.30
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.80
   Compiling serde_derive v1.0.130
   Compiling serde v1.0.130
   Compiling typenum v1.14.0
   Compiling version_check v0.9.3
   Compiling cfg-if v1.0.0
   Compiling subtle v2.4.1
   Compiling semver-parser v0.7.0
   Compiling winapi v0.3.9
   Compiling getrandom v0.1.16
   Compiling crunchy v0.2.2
   Compiling memchr v2.3.4

My Case://

**Comment by epage** [comment]
I'm doing the majority of my development on WSL2 at the moment, so it works generally, leaving us to narrow down what is failing in your specific case.

Can you give more detail of what is happening.  Is it hanging while updating the index or something else?  Can you run with `-vv` to see if we get extra information

**Comment by millucas** [comment]
Are you on wsl1 or wsl2? You can see this by running wsl -l -v in a powershell prompt.
Which version of Ubuntu do you have?
Using win10, win11 or something else?

**Comment by xmas7** [comment]
> I'm doing the majority of my development on WSL2 at the moment, so it works generally, leaving us to narrow down what is failing in your specific case.
> 
> Can you give more detail of what is happening. Is it hanging while updating the index or something else? Can you run with `-vv` to see if we get extra information

Thanks for your reply.

**Comment by xmas7** [comment]
Millucas as well.

**Comment by gimbles** [comment]
"Not working properly" isn't exactly the most helpful description of the issue, can you tell how it doesn't work more specifically? Or is it just getting stuck at the index? Because that can take a *while* to download on slower internet connections. :P

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. Feel free to open a new issue if there is any update. Thank you!
