### ISSUE TITLE
requested file is a directory; class=Invalid (3); code=NotFound (-3)

### ISSUE THREAD

**Issue by RozeFound** [rust-lang/cargo#11026]
### Problem

I tried to install ferium with cargo and got this error
```
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  requested file is a directory; class=Invalid (3); code=NotFound (-3)
```

OS: Fedora 36 Workstation

### Steps

1. Install Fedora 36 Workstation
2. sudo dnf install cargo
3. cargo install ferium

### Version

```text
cargo 1.63.0
release: 1.63.0
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.82.0 (sys:0.4.55+curl-7.83.1 system ssl:OpenSSL/3.0.5)
os: OracleLinux 36.0.0 [64-bit]
```

**Comment by weihanglo** [comment]
The error occurred from [here](https://github.com/rust-lang/cargo/blob/4ed54cecce3ce9ab6ff058781f4c8a500ee6b8b5/src/cargo/sources/registry/remote.rs#L299-L300). Something went wrong during git fetching the crates.io registry index.

- Does it work for you to `git clone https://github.com/rust-lang/crates.io-index`?
- If it does, could you try using `CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install …`?
- If it is still broken, I suspect that some settings are misconfigured.
  - Have you set any proxy or mirror in `.cargo/config.toml`?
  - Does your system have a global proxy or else?

There are several things might affect your experience of fetching index. More information can help debug this situation. Thank you!

**Comment by RozeFound** [comment]
Oh, I'm sorry. The problem was occurred because of git misconfiguration. 
I accidentally created directory ~/.config/git/config, which must be a config file actually.

**Comment by RozeFound** [comment]
Thanks for your help! I didn't even tried just cloning it, so I didn't seen an actual error
