### ISSUE TITLE
Stop Always Updating crates.io index

### ISSUE THREAD

**Issue by archuser555** [rust-lang/cargo#11022]
### Problem

Hey, Im A Rust Dev & Lover, I Love The Langue And I Love How Cargo Save Me Time To Install dependencies that i need but my data plan are not enough to updating crates.io index everytime i install a new dependencies, Thanks!

### Proposed Solution

You Can Add A Option To Ignore Updating crates.io index everytime i install some dependencies, Thanks!

### Notes

Thanks :-)

**Comment by Eh2406** [comment]
My colleague just did an excellent write up of the big work we're doing on this problem. https://github.com/rust-lang/cargo/issues/11014#issuecomment-1222191543

There is also the stable `--offline` flag that will prevent all Internet access by only letting you update to versions that you already have completely downloaded.
There is an unstable `-Zno-index-update` that just skips downloading the index, exactly like you want. It will not be stabilized, as it can easily lead to very confusing behavior for users.

**Comment by archuser555** [comment]
Ok wait me try thos and give you an answer, thx btw

**Comment by archuser555** [comment]
Thank You For Save My Day And My Data @Eh2406
