### ISSUE TITLE
Cargo update doesn't look for overrides in the config file

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#1103]
This makes it a bit hard to work on rust upgrades locally, since `cargo update` provides convenient way of updating the lockfiles to specific hashes. However, if the hash doesn't exist in the github repo, it fails to update the lockfile with this error:

```
$ cargo update -p html5ever --precise 497339bd717fcd78451139a1d8ddc3d6d5836842 --verbose
    Updating git repository `https://github.com/servo/html5ever`
Unable to update https://github.com/servo/html5ever#497339bd

Caused by:
  [4] Revspec '497339bd717fcd78451139a1d8ddc3d6d5836842' not found.
```

This happens even if the hash exists in the local repo that the config `paths` key points to.

(Manually updating the lockfile and building works fine, since `cargo build` does look for overrides)

**Comment by Ericson2314** [comment]
Do `[replace]` overrides work differently than this? Cargo weirdly fails to fetch me repos all the time.

**Comment by Ericson2314** [comment]
Nevermind on the failure, old lockfile + force pushes was the issue and chucking the lockfile fixed it. Still, the fetches can sometimes be slow and it would be nice to avoid them.
