### ISSUE TITLE
cargo search return non-zero exit code when no results found

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/cargo#11037]
### Problem

Using cargo search in scripts is difficult because if it doesn't find any results it doesn't return a non-zero exit code.

### Proposed Solution

Return a non-zero exit code when the search yields no results.

**Comment by epage** [comment]
In what ways are you using `cargo search` in scripts?  We don't provide a programmatic output mode for it, so it seems that either the value for using it in scripting is limited or its very brittle.  By improving the scripting experience, I worry we send the wrong message about our compatibility on the text output.

**Comment by leighmcculloch** [comment]
I'm using the output to check if a prior publish finalized. 

Although I've also discovered the `cargo add` command can be used in the same way and it will return a non-zero exit code if the version of the crate cannot be found.

**Comment by epage** [comment]
Some tools, like cargo-release, have support for that built-in.

You can also use the crate crates_index to look information up.

We are also looking at dedicated plumbing for the registry, see https://github.com/rust-lang/cargo/issues/11034

I lean towards closing this issue as the driving use case for using `cargo search` is is unreliable (considering we can return results from other crates) and there are other options.

**Comment by epage** [comment]
I should add that we also have https://github.com/rust-lang/cargo/issues/9507 where we want to add our own polling directly into cargo.
