### ISSUE TITLE
cargo update --workspace --offline can fail with git dependencies

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/cargo#11056]
### Problem

I use `cargo update --workspace --offline` on CI to ensure that the version number in Cargo.lock is up to date with Cargo.toml. Recently I noticed it fail:

```text
$ cargo update --workspace --offline
error: failed to load source for dependency `foo`
Caused by:
  Unable to update https://github.com/alecmocatta/foo#7fc68e8e
Caused by:
  can't checkout from 'https://github.com/alecmocatta/foo': you are in the offline mode (--offline)
```

Maybe I'm misunderstanding `cargo update --workspace`, but it shouldn't need to touch git dependencies, right? So `--offline` should be fine?

### Steps

1. Add a git dependency to a crate
2. `rm -rf ~/.cargo/git/db`
3. `cargo update --workspace --offline`

### Possible Solution(s)

Removing `--offline` works fine.

### Version

```text
cargo 1.65.0-nightly (efd4ca3dc 2022-08-12)
release: 1.65.0-nightly
commit-hash: efd4ca3dc0b89929dc8c5f5c023d25978d76cb61
commit-date: 2022-08-12
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.4.0 [64-bit]
```

**Comment by ehuss** [comment]
In order to update the lock file, cargo needs access to all of the dependencies (so that it can see what the graph looks like). If the git dependencies haven't been previously cached, then cargo will need to download them. Without the git dependencies, cargo wouldn't know what to put in `Cargo.lock` for them.

**Comment by alecmocatta** [comment]
Understood. It seems like perhaps cargo could update the workspace packages' `version` and `dependencies` offline as long as any git deps are already in the Cargo.lock. But even if possible there's no burning need for that, so will close.
