### ISSUE TITLE
add option for configuring where vendor files are written by cargo vendor

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/cargo#11065]
### Problem

`cargo vendor` always writes vendored crates to the `vendor/` directory.

Sometimes it is necessary to build vendor directories for purposes other than filling the crate workspace's local `vendor/` directory. To do this at the moment requires removing any existing `vendor/` directory, running `cargo vendor`, moving the directory to wherever it is needed.

### Proposed Solution

There are a couple possible solutions:

1. Add an option to `cargo vendor` such as `--vendor-path` that defaults to `./vendor/` but can be changed to any relative / absolute path.

2. Add a cargo configuration for changing the vendor path.

### Notes

Note that the source replacement cargo configurations allow for specifying a vendor directory at any location.

```toml
[source.my-vendor-source]
directory = "path/to/vendor"
```

Ref: https://doc.rust-lang.org/cargo/reference/source-replacement.html

If cargo can consume a vendor directory from anywhere, it seems odd that it will only write the vendor directory to a single hardcoded location.

Discussion on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/cargo.20vendor.20for.20multi-crate.20workspace.20package.20verification/near/297866366

**Comment by ehuss** [comment]
The path can be specified as an argument, such as `cargo vendor some-other-directory`.  See the [`cargo vendor`](https://doc.rust-lang.org/cargo/commands/cargo-vendor.html) docs for more.

**Comment by leighmcculloch** [comment]
Woah 🤦🏻, I'm so used to arguments to the cargo commands being options and config values, I looked in those places and totally missed it was a positional argument. Thanks @ehuss!!!
