### ISSUE TITLE
cargo run --features only activates first feature in space-separated list

### ISSUE THREAD

**Issue by jruiss** [rust-lang/cargo#11076]
### Problem

```F, --features <FEATURES>       Space or comma separated list of features to activate```

Executing ```cargo run --features cuda opencl``` only activates "cuda".
Running comma-separated, ```cargo run --features cuda,opencl``` works as expected.

### Steps

Run  
```rust
#[cfg(feature="cuda")]
println!("Cuda activated");

#[cfg(feature="opencl")]
println!("OpenCL activated");
``` 
with ```cargo run --features cuda opencl```

### Version

```text
cargo 1.63.0 (fd9c4297c 2022-07-01)
release: 1.63.0
commit-hash: fd9c4297ccbee36d39e9a79067edab0b614edb5a
commit-date: 2022-07-01
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Pro) [64-bit]
```

**Comment by epage** [comment]
When you run
```console
$ cargo run --features cuda opencl 
```

Your shell is parsing that as
```rust
["cargo", "run", "--features", "cuda", "opencl"]
```
`--features` does not support arbitrary number of argument values but only 1, so `opencl` is being passed to the program being run.

Instead you would need to do:
```console
$ cargo run --features "cuda opencl"
```
which your shell will turn into
```rust
["cargo", "run", "--features", "cuda opencl"]
```
and everything will work as expected

**Comment by jruiss** [comment]
Ah, my bad!
