### ISSUE TITLE
test variants of binary artifact dependencies

### ISSUE THREAD

**Issue by Hezuikn** [rust-lang/cargo#11108]
### Problem

to test for the things i want to

### Proposed Solution

id like the ability to enable "rustc --test / harness = true" for artifacts; being able to pass metadata to build.rs would also be nice

**Comment by weihanglo** [comment]
It would be nice if you can add more contexts, such as

- What exactly you're trying to resolve. A concrete example and links are great.
- Any existing solution/workaround to achieve what you want? How do they look like?

This would help not only maintainers but other random contributors to come up with better ideas. 😁

**Comment by ehuss** [comment]
Sorry, without more information I don't think we'll be able to help gather what you are looking for. If you have time to fill out some details, feel free to reopen.
