### ISSUE TITLE
--out-dir but for cargo test

### ISSUE THREAD

**Issue by stevenhansel** [rust-lang/cargo#11109]
### Summary

Original issue: #4875 
Implementation: #6790  
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html?highlight=--out-dir#out-dir

I'm glad that the `--out-dir` is out for the `cargo build` command, but is it possible to also include this feature in `cargo test`? The use case for me is to run the binary containing the tests under the debugger. I know that probably I can use `cargo build` and use the `--tests` flag, but that means I have to modify the `Cargo.toml` in every project.

P.S. would be so happy if I can contribute to this issue! (if approved)

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by weihanglo** [comment]
Thank you for your report! 
However, this shouldn't be a tracking issue. Should choose ["Feature Request"](https://github.com/rust-lang/cargo/issues/new?assignees=&labels=C-feature-request&template=feature_request.yml) template instead. Could you help adjust the description of this issue to align with the correct template? (Or alternatively close this one and reopen)

**Comment by stevenhansel** [comment]
> I'm glad that the `--out-dir` is out for the `cargo build` command, but is it possible to also include this feature in `cargo test`? The use case for me is to run the binary containing the tests under the debugger. I know that probably I can use `cargo build` and use the `--tests` flag, but that means I have to modify the `Cargo.toml` in every project.

Sure thing, I have re-opened it into a new issue (Feature Request) #11110
