### ISSUE TITLE
metadata: pretty

### ISSUE THREAD

**Issue by 89z** [rust-lang/cargo#11112]
current output is just minified JSON:

https://doc.rust-lang.org/cargo/commands/cargo-metadata.html

I think it would be helpful if a pretty option was available. The JSON package does have a function for it:

https://docs.rs/serde_json/latest/serde_json/fn.to_string_pretty.html

**Comment by epage** [comment]
I also wonder if we should include a pager.  Then someone can configure to to `bat` and get syntax highlighting as well.

Should we restrict pretty to tty?

**Comment by 89z** [comment]
my opinion, keep it simple. If someone want a pager, they can just do:

~~~
cargo metadata | less
~~~

or whatever. I have coded internal pagers, and its significantly more complex than just `to_string_pretty`. but up to you guys

**Comment by ehuss** [comment]
I might suggest using something like `jq` instead. The output of `cargo metadata` is not intended to be human-readable, and the output can be quite large. `cargo metadata | jq` should pretty-print and highlight the output, and then the content can be explored with queries like `cargo metadata | jq .workspace_root`. There are various tools for pretty-printing javascript or JSON, and they can provide more flexibility (indentation, etc.) that I would not want cargo to get pulled down the rabbit hole with.

**Comment by 89z** [comment]
> I might suggest using something like `jq` instead.

No thank you. People might not like to admit it, but the reality is that `jq` is a DSL. Once I came to that realization, I stopped using it and have been happy with that decision. It would be one thing if Cargo was using some smaller JSON package, but Cargo is already using `serde_json`:

https://github.com/rust-lang/cargo/blob/531ce1321d282d3a975d0799a322e6bd20f4c3c6/Cargo.toml#L54

which means you get `to_string_pretty` for free. All you have to do is make pretty the default, or if people think its an issue, then it could be put behind the `--format-version` flag, or possibly some new flag.

> The output of `cargo metadata` is not intended to be human-readable, and the output can be quite large.

Its JSON, so that's about as readable as it gets, unless you're talking TOML or YAML. If it was a binary format like ProtoBuf or similar, I would agree with you. However in my case, I manually dumped the mini-JSON, then indented it using another tool. I can keep doing that, but it would be helpful if it was an option.

> I would not want cargo to get pulled down the rabbit hole with

Its only a rabbit hole if you make it one. For example in this case you could say "we will consider this, but no extra crates can be added". Since in this case `serde_json` already being used, then it works. Personally I think its a minor change, but you guys call the shots.

1. <https://wikipedia.org/wiki/Domain-specific_language>
