### ISSUE TITLE
Unknown [project] table in cargo docs

### ISSUE THREAD

**Issue by TheNeikos** [rust-lang/cargo#11129]
### Problem

In the cargo docs there is a reference to a `[project]` table: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace 

I could not find anything about it. Is it maybe meant to say 'package'? Or is it only undocumented?

(I specifically could not find it in the manifest: https://doc.rust-lang.org/cargo/reference/manifest.html)

**Comment by Muscraft** [comment]
Thanks for the report!

I believe [`[project]` used to be what `[package]`](https://github.com/rust-lang/cargo/issues/3388#issuecomment-266504735) is today. Both are still supported within Cargo but it's not documented and shouldn't be used. This was an oversight on my part when writing up the documents. I'll make sure to fix it here soon!

**Comment by epage** [comment]
Looks like this was resolved.
