### ISSUE TITLE
Representation of local dependencies in Cargo.lock

### ISSUE THREAD

**Issue by dan-t** [rust-lang/cargo#1113]
Hi,

I just tried to support local dependencies in [rusty-tags](<https://github.com/dan-t/rusty-tags>).

`crates.io` and `git` dependencies have a `source` entry in their package table inside of `Cargo.lock` e.g.:

    [[package]]
    name = "glob"
    version = "0.1.3"
    source = "registry+https://github.com/rust-lang/crates.io-index"

Currently local dependencies only have a `name` and a `version` entry, would it be possible to add a
`source` entry for them e.g.:

    [[package]]
    name = "lib"
    version = "0.2"
    source = "local+path-to-source"

Greetings,
Daniel

**Comment by alexcrichton** [comment]
We'd be unable to put the full path into the `source` attribute due to the requirement that the lockfile couldn't change between hosts (with different actual source directories), but are you looking to find a relative path to the source from the root of the project?

**Comment by dan-t** [comment]
> We'd be unable to put the full path into the source attribute due to the requirement that the lockfile couldn't change between hosts (with different actual source directories), but are you looking to find a relative path to the source from the root of the project?
> 
It would be more than fine for me if local dependencies have a relative path in their source attribute.

I haven't yet tried dependency overrides, are they also represented in the 'Cargo.lock'?


Greetings,
Daniel

**Comment by alexcrichton** [comment]
Hm yes this does require a bit of legwork on behalf of external tooling. Placing relative paths would be plausible though. I think we'd need to refactor how we deal with a `SourceId` because currently everything says it's from the same path (assumes that you traverse the directory deeply looking for `Cargo.toml`).

Overrides via `.cargo/config` and `paths` are not in the lock file.

**Comment by dan-t** [comment]
> Overrides via .cargo/config and paths are not in the lock file.
> 

Would it be somehow feasible to get the whole by cargo resolved dependencies
for a cargo project?

Otherwise tools like rusty-tags have to duplicate - to some degree - the resolving algorithm.


Greetings,
Daniel=

**Comment by alexcrichton** [comment]
Acquiring the fully resolved graph is probably best done through Cargo itself right now. That being said, though, requests like this sound like a new subcommand for Cargo rather than modifying the lockfile format itself. The composability of `cargo` was one of its core design goals, and we've got tons of room to expand into!

I'd fine with a subcommand that printed out a fully resolved graph for a project as well as all of the manifests of where everything came from, both in "I'm building this" mode as well as "I'm just looking at the lockfile" mode.

**Comment by dan-t** [comment]
> That being said, though, requests like this sound like a new subcommand for Cargo rather than modifying the lockfile format itself.
> 
Yes, pretty much my thoughts, and the subcommand should print out something easy parsable like JSON.

Can you give me some hints where cargo already does the dependecy resolving and handling of the
overrides, then I might try to implement this subcommand.

**Comment by alexcrichton** [comment]
[This is the primary file](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/resolve.rs) for resolution, and you can see examples in [`cargo_compile.rs`](https://github.com/rust-lang/cargo/blob/5443813c6dcc7c11dd4e80195c46498a5a033ff3/src/cargo/ops/cargo_compile.rs#L93-L112) of how to use it.

**Comment by dan-t** [comment]
On Sat, Jan 03, 2015 at 11:38:22AM -0800, Alex Crichton wrote:
> This is the primary file for resolution, and you can see examples in
> cargo_compile.rs of how to use it.

I don't quite understand how the mapping of the subcommands is done.

I can see that some registration for the subcommands is done in
'cargo.rs' and they're somehow dispatched there.

Some subcommands have a module named after them under 'ops/cargo_*.rs'
and inside of the module a function named after them, other
subcommands don't seem to follow this pattern.

I also can't see where this subcommand function is called with the
correct arguments.


Regarding the SourceId, is there already a function/method that
maps the SourceId to the directory where cargo downloads its source code?


For 'Kind::Path' dependencies, does 'SourceIdInner::Url' then contain
the path to the source directory?


When the overrides are applied to the 'Resolve' data structure, are
then all 'SourceId' with an available override transformed to
'SourceIds' containing a 'Kind::Path'?


Thanks for any hints!

**Comment by alexcrichton** [comment]
> I don't quite understand how the mapping of the subcommands is done.

That can be found [here](https://github.com/rust-lang/cargo/blob/master/src/bin/cargo.rs#L118-L130)

> Some subcommands have a module named after them under 'ops/cargo_*.rs' and inside of the module a function named after them, other subcommands don't seem to follow this pattern.

Yeah in general take a look at `src/bin/foo.rs` for the code corresponding to `cargo foo`. That should help point you into where in libcargo the functionality resides.

> Regarding the SourceId, is there already a function/method that maps the SourceId to the directory where cargo downloads its source code?

Not currently, this normally comes from a `Source` and is source-specific. You'll eventually load a `Package` through which you can get the path.

> For 'Kind::Path' dependencies, does 'SourceIdInner::Url' then contain the path to the source directory?

Yes

> When the overrides are applied to the 'Resolve' data structure, are then all 'SourceId' with an available override transformed to 'SourceIds' containing a 'Kind::Path'?

Yes

**Comment by dan-t** [comment]
Hi Alex,

> Not currently, this normally comes from a Source and is source-specific. You'll
> eventually load a Package through which you can get the path.

Ok, I've now a working subcommand that gets till the resolved package.

Can you please point out, how I can now get at the source directories?


Greetings,
Daniel

**Comment by dan-t** [comment]
Ok, I can now get at the source path for each `SourceId`, but I still don't know how I should get at the below paths for each library/package for `Kind::Git` and `Kind::Path`.

For `Kind::Registry` I can just use the information of `PackageId::get_name` and `PackgeId::get_version`,
but for the other two kinds I'm currently a bit clueless.

**Comment by dan-t** [comment]
Precisely, for a git source path like `~/.cargo/git/checkouts/semver-c17c2041aa98241a/master/`, how can I get
at the hash `c17c2041aa98241a`? The `master` part of the path seems just to be the string contained in `GitReference`, right?

And for a local dependency like:

    [dependencies.registry]
    path = "src/registry"

How can I get at the `src/registry`?

Thanks for any hints!

**Comment by dan-t** [comment]
Ok, I think I got the `Kind::Git` one now, its source path can be completely dertermined by just a `SourceId`.

But I'm still looking how I can get at this `src/registry` path.

**Comment by alexcrichton** [comment]
Given a `SourceId`, you'll want to [`load`](https://github.com/rust-lang/cargo/blob/d100bef931843fcee27bfb76655d8952857e5553/src/cargo/core/source.rs#L194-L210) it to get a `Source`, after which you'll want to [`update`, `download`, and `get`](https://github.com/rust-lang/cargo/blob/d100bef931843fcee27bfb76655d8952857e5553/src/cargo/core/source.rs#L18-L44) the package. This will give you a `Package` where you can [get the path](https://github.com/rust-lang/cargo/blob/d100bef931843fcee27bfb76655d8952857e5553/src/cargo/core/package.rs#L103-L105).

**Comment by dan-t** [comment]
Thanks!

I'm now closing this issue and will open a pull request if I've finished the subcommand.

**Comment by dan-t** [comment]
Hi Alex,

On Sun, Jan 18, 2015 at 06:55:48PM -0800, Alex Crichton wrote:
> Given a SourceId, you'll want to load it to get a Source, after which you'll
> want to update, download, and get the package. This will give you a Package
> where you can get the path.

It doesn't seem to work for registry dependencies that way.

The following code iterates over a 'HashMap<&SourceId, Vec<PackageId>>':

    for (mut src_id, ref pkg_ids) in src_id_to_pkg_ids.iter() {
        println!("source id: {:?}", src_id.to_url());
        print!("package ids: ");
        for pkg_id in pkg_ids.iter() {
            print!("{:?} ", pkg_id.get_name());
        }

        println!("");

        let mut src = src_id.load(config);
        try!(src.update());
        try!(src.download(pkg_ids.as_slice()));
        let pkgs = try!(source.get(pkg_ids.as_slice()));

        println!("pkgs: {:?}", pkgs);

        for pkg in pkgs.iter() {
            println!("{:?}", pkg.get_root());
        }
    }

When I'm running my new subcommand - which contains this loop - on the cargo
project itself, then I'm getting (I've reduced the output for 'Package'):

source id: "Path source"
package ids: "cargo" "registry" 
pkgs: [Package { ... name: "registry" ...}, Package { ... name: "cargo" ...}]
/home/dan/projekte/cargo/src/registry
/home/dan/projekte/cargo

source id: "registry+https://github.com/rust-lang/crates.io-index"
package ids: "docopt" "rustc-serialize" "pkg-config" "term" "tar" "libssh2-sys" "regex" "miniz-sys" "curl" "libgit2-sys" "time" "glob" "gcc" "toml" "openssl-sys" "matches" "libz-sys" "url" "log" "semver" "git2" "curl-sys" "flate2" 
pkgs: []


Both SourceIds have the expected PackageIds, but if I'm trying to get the
Packages with 'SourceId::get' from the PackageIds, it only seems to work
for the path dependencies and for the registry depedencies I'm just
getting an empty vector.

Any ideas? Thanks!


Greetings,
Daniel

**Comment by dan-t** [comment]
Hi Alex,

I just saw that I'm using the wrong source, this line:

   let pkgs = try!(source.get(pkg_ids.as_slice()));

should be:

   let pkgs = try!(src.get(pkg_ids.as_slice()));


Then it works like expected.

There's no other way than building cargo with static linking, right?
Because the static linking times are a bit painful.


Greetings,
Daniel

**Comment by alexcrichton** [comment]
Unfortunately yes at this time there are no plans to distribute `libcargo.dylib`, only the `cargo` executable for now.

**Comment by CodeSandwich** [comment]
@dan-t This is a bizarre question, but how is this change going? Shouldn't this issue be reopened?
