### ISSUE TITLE
book: document default opt-level

### ISSUE THREAD

**Issue by 89z** [rust-lang/cargo#11142]
this page:

https://doc.rust-lang.org/cargo/reference/profiles.html

lists the different `opt-level` values, but it doesn't say which one is the default. After some testing, it appears to be:

~~~
opt-level = 3
~~~

this appears to differ from `rustc`, which defaults to:

~~~
opt-level = 0
~~~

this is all fine, but I think the cargo default should be documented. Otherwise people will either assume its the same as `rustc`, or have to manually test all six to find out which it is.

**Comment by weihanglo** [comment]
If you scroll down a little bit, there is a section ["Default profiles"](https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles) telling the defaults Cargo gives. Something like

> The `dev` profile is used for normal development and debugging. It is the default for build commands like [`cargo build`](https://doc.rust-lang.org/cargo/commands/cargo-build.html), and is used for `cargo install --debug`.
> 
> The default settings for the dev profile are:
>
> ```
> [profile.dev]
> opt-level = 0
> ...
> ```

**Comment by 89z** [comment]
true, thanks for the info
