### ISSUE TITLE
Workspace Support for cargo add

### ISSUE THREAD

**Issue by theduke** [rust-lang/cargo#11152]
### Problem

The newly stabilized workspace inheritance and workspace level dependencies are currently not supported by `cargo add`.

### Proposed Solution

Add a `-w` / `--workspace` flag to `cargo add` that will add dependencies as a workspace dependency.

**Comment by weihanglo** [comment]
Thank you for your suggestion! It seems to be a duplicate of <https://github.com/rust-lang/cargo/issues/10608>. Anyone interested in it can continue discussing there. Closing now.
