### ISSUE TITLE
`git` option in config should be an enumeration

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/cargo#1116]
`.cargo/config` supports an option `git` that determines whether a new Git repository should be initialized by default when using `cargo new`. Now that Cargo supports Mercurial, and the `--git` and `--hg` flags almost always should be considered mutually exclusive, this could be replaced by a more flexible option in the config file that controls VCS initialization.

For example, you might have:

`vcs = git | hg | <more some day...> | none`

See also #1115. An alternative design concerning all defaults for `cargo new` could be considered as well.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/cargo/issues/517 and https://github.com/rust-lang/cargo/issues/1099, I'd be fine with changing the key to `vcs`, but it should be accompanied with changes to the CLI as well. I suspect that travis would also want to fall under a generic key.
