### ISSUE TITLE
Adding a crate with non-existent feature(s)

### ISSUE THREAD

**Issue by maxwase** [rust-lang/cargo#11171]
### Problem

Even though cargo shows an error, it still shows `+ not_exist`

```
➜  test_add git:(master) ✗ cargo add futures --features=not_exist
    Updating crates.io index
      Adding futures v0.3.24 to dependencies.
             Features:
             + alloc
             + async-await
             + executor
             + not_exist
             + std
             - bilock
             - cfg-target-has-atomic
             - compat
             - futures-executor
             - io-compat
             - thread-pool
             - unstable
             - write-all-vectored
error: unrecognized features: ["not_exist"]
```

### Steps

Try to add a dependency using `cargo add` with non-existent feature, for example

`cargo add futures --features=not_exist`

### Possible Solution(s)

Small fix in printing

### Version

```text
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Manjaro 22.0.0 (Sikaris) [64-bit]
```

**Comment by weihanglo** [comment]
Thank you for your report! You are not the only one reported this, and really glad we already addressed it with  <https://github.com/rust-lang/cargo/pull/11098>! 

Closing as it has been improved.

**Comment by maxwase** [comment]
> Thank you for your report! You are not the only one reported this, and really glad we already addressed it with  <https://github.com/rust-lang/cargo/pull/11098>! 
> 
> Closing as it has been improved.

Oh, I've searched only in opened tickets, thanks for pointing)
