### ISSUE TITLE
error: could not find `--path/ move-cli` in registry `crates-io` with version `*`

### ISSUE THREAD

**Issue by leonardo07746git** [rust-lang/cargo#11189]
While installing Cargo with Move it returns this error:

$ cargo install language/tools/move-cli

error: could not find `tools/move-cli` in registry `crates-io` with version `*`

anyway to fix this??

Thanks

**Comment by Eh2406** [comment]
What were you expecting it to do?

**Comment by leonardo07746git** [comment]
to install cargo, what else

**Comment by weihanglo** [comment]
The commands they provide are different from yours (as of [move-language/move#10e921dd](https://github.com/move-language/move/tree/10e921dd044e58739b16c86d8c9c56934c0261cc)).

> ## Installation
> ```shell
> $ cargo install --path move/language/tools/move-cli
> ```
> or
> ```shell
> $ cargo install --git https://github.com/move-language/move move-cli --branch main
> ```

You need to use `--path` flag if you are going to install a binary from a local package. For more information, please see [the manual of `cargo install`](https://doc.rust-lang.org/cargo/commands/cargo-install.html).

Those commands work on my machine, and it is more appropriate to file this kind of bug first to the project `move-language/move` before identifying it is a bug from Cargo. I am going to close this as there seems no bug and not related to Cargo. Thank you.

**Comment by leonardo07746git** [comment]
thanks
