### ISSUE TITLE
Cargo no longer seems to build anything using tagged git versions

### ISSUE THREAD

**Issue by shadowmint** [rust-lang/cargo#1119]
Tok:rust-array doug$ rustc --version
    rustc 0.13.0-nightly (39d740266 2015-01-01 15:51:08 +0000)

    Tok:rust-array doug$ cargo --version
    cargo 0.0.1-pre-nightly (1a1868b 2014-12-31 21:39:41 +0000)

    Tok:rust-array doug$ cargo test --verbose
        Updating git repository `https://github.com/shadowmint/rust-traits`
    Unable to update https://github.com/shadowmint/rust-traits?tag=0.1.6

    Caused by:
       failed to find tag `0.1.6`

    Caused by:
       The requested type does not match the type in the ODB

In Cargo.toml:

    [dependencies.traits]
    git = "https://github.com/shadowmint/rust-traits"
    tag = "0.1.6"

The requested tag exists here: 

    https://github.com/shadowmint/rust-traits/releases/tag/0.1.6

Seems to compile things fine without the 'tag' or by replacing 'tag' with 'version', although it doesn't download the correct tagged version.
 
Is this option depreciated? I couldn't see anything in the commit logs for it?

**Comment by shadowmint** [comment]
NB. This is the osx nightly from a few days ago, because cargo doesn't currently compile against the rust master, so... can't really test cargo head to check if this is already resolved.

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like that git repo has tags of a form that we weren't quite expecting, and I think I've fixed this in https://github.com/rust-lang/cargo/pull/1122
