### ISSUE TITLE
Using 'cargo new package_name' sets the edition of package to 2021 by default.

### ISSUE THREAD

**Issue by rtarun9** [rust-lang/cargo#11199]
### Problem

This is a very minor bug, but I found that while creating a new cargo package using `cargo new package_name`, the Cargo.toml file generated looks as follows : 
```toml
[package]
name = "package_name"
version = "0.1.0"
edition = "2021" <-- Maybe change to 2022?
```
I think a nice default for edition would be 2022 😄 

### Steps

1. Install the rust toolchain using rustup-init.exe (I installed it on Windows 11 from [here](https://rustup.rs/).
2. Create new cargo package using `cargo new project_name`.
3. The Cargo.toml file will have edition set to 2022 by default. 

### Notes

{While this bug is very minor, setting edition default to 2022 would be nice!}

### Version

```text
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 10 Home Single Language) [64-bit]
```

**Comment by ehuss** [comment]
Rust editions are released roughly once every three years. The current valid editions are 2015, 2018, and 2021. There may be a new edition in 2024, but the schedule is not necessarily fixed. You can learn more about editions in the [Edition Guide](https://doc.rust-lang.org/edition-guide/).

**Comment by rtarun9** [comment]
Thank you for letting me know @ehuss! I should have seen that before, which is my bad. I will be closing this issue now👍🏾.
