### ISSUE TITLE
Cargo publish throws a wildcard error

### ISSUE THREAD

**Issue by nurmukhametdaniyar** [rust-lang/cargo#11198]
### Problem

I wanted to publish my [project](https://github.com/nurmukhametdaniyar/pust) on crates.io with `cargo publish`, but it throws an error:

`the remote server responded with an error: wildcard (`*`) dependency constraints are not allowed on crates.io. See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information`

I have tried to look through dependencies, but there is not any with wildcard versioning.

### Version

```text
cargo 1.61.0-nightly (109bfbd05 2022-03-17)
release: 1.61.0-nightly
commit-hash: 109bfbd055325ef87a6e7f63d67da7e838f8300b
commit-date: 2022-03-17
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

**Comment by ehuss** [comment]
It looks like you might have a typo in your `clap` dependency. It has `versino` but it should be `version`.

**Comment by nurmukhametdaniyar** [comment]
> It looks like you might have a typo in your `clap` dependency. It has `versino` but it should be `version`.

Oh, that solves the issue. Thank you @ehuss :)

**Comment by satake0916** [comment]
I made the same mistake and had the same error. Thank you!
