### ISSUE TITLE
Allow building and executing programs from crates

### ISSUE THREAD

**Issue by coffee-is-power** [rust-lang/cargo#11201]
### Problem

Yes, cargo install exists, but managing different versions of a binary for different projects is a challenge, for example, if you use prisma, you want the library AND the cli

### Proposed Solution

The solution would be to build the binaries from the crates with the libraries, and install it somewhere inside the target folder `target/.bin/`, and a way to execute the binaries, for instance, `cargo run-crate <crate> <args>`

**Comment by ehuss** [comment]
Thanks for the suggestion!  I think this is very closely related to #2267, so I'm going to close in favor of that.
