### ISSUE TITLE
Cargo build tries to read files that it has no permissions for (Permission denied (os error 13))

### ISSUE THREAD

**Issue by sirno** [rust-lang/cargo#11220]
### Problem

I want to compile my code on a cluster. Clusters are messy sometimes, and as such in the `/home` directory of our system someone or something  made a mess, creating all sorts of directories, one of which is called `Cargo.toml`.

When building `Cargo.toml` the compiler fails:

```
error: failed to read `/Users/Cargo.toml`

Caused by:
  Permission denied (os error 13)
```

### Steps

These work on any system :)

1. `cd ~/..`
2. `sudo mkdir Cargo.toml` or `sudo touch Cargo.toml`
3. `sudo chmod 300 Cargo.toml`
4. try to compile any project...

### Possible Solution(s)

Probably plenty

- Check permissions before writing files
- Do not read stuff outside of the user directory
- Blacklist or whiltelist search paths

### Version

```text
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: CentOS 7.9.2009 (Core) [64-bit]
```

**Comment by epage** [comment]
FYI in the future, you might run into problems with https://github.com/rust-lang/cargo/pull/10736

One workaround is to put `[workspace]` in your project which will tell cargo it shouldn't walk up the directory hierarchy to find if a `Cargo.toml` with a `[workspace]` exists.

**Comment by sirno** [comment]
Thank you so much. This works. I am closing this issue.
