### ISSUE TITLE
Provide cargo init --workspace

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/cargo#11233]
### Problem

Right now, it is very slightly inconvenient to set up a new Rust project with a workspace rather than as a standalone lib or bin.

### Proposed Solution

In addition to `cargo init --bin` and `cargo init --lib`, it would be great to have `cargo init --workspace`, which just sets up `Cargo.toml` as a workspace with no members. Not a big deal, but perhaps also really easy?

**Comment by epage** [comment]
I think this might be a duplicate of #8365 if we keep parity between `init` and `new`.

Other related workspace issues
- #6378
- #10870

**Comment by BartMassey** [comment]
Agreed. Apologies for the issue spam: I *did* do a search, honest, but somehow managed to miss the relevant issues.
