### ISSUE TITLE
Sparse Registry Fails with Unsupported Protocol on nightly-2022-10-13

### ISSUE THREAD

**Issue by robertwayne** [rust-lang/cargo#11246]
### Problem

Trying to download crates from crates.io with the sparse registry feature enabled results in a failure

```
> rob@pop-os:/mnt/Primary/projects/sparse-error-test$ cargo +nightly -Z sparse-registry check

Updating crates.io index
error: failed to get `tokio` as a dependency of package `sparse-error-test v0.1.0 (/mnt/Primary/projects/sparse-error-test)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of config.json failed

Caused by:
  failed to download from `sparse+https://index.crates.io/config.json`

Caused by:
  [1] Unsupported protocol (Protocol "sparse+https" not supported or disabled in libcurl)
```
```
> rob@pop-os:/mnt/Primary/projects/sparse-error-test$ cargo version
cargo 1.66.0-nightly (b332991a5 2022-10-13)
```

Running with `cargo 1.66.0-nightly (b8f30cb23 2022-10-10)` works fine.

### Steps

1. Create a new project.
2. Add any crate to your `Cargo.toml`.
3. Run `cargo +nightly -Z sparse-registry check`.

### Notes

I see there were a bunch of commits between the `nightly-2022-10-10` and `nightly-2022-10-13` release relating to sparse registry, but I didn't see anything signalling a change from the prior behaviour or usage.

### Version

```text
cargo 1.66.0-nightly (b332991a5 2022-10-13)
release: 1.66.0-nightly
commit-hash: b332991a57c9d055f1864de1eed93e2178d49440
commit-date: 2022-10-13
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Pop!_OS 22.04 (jammy) [64-bit]
```

**Comment by Eh2406** [comment]
@arlosi want to take a look?

**Comment by folex** [comment]
Hi, thanks for the quick fix! 

What's the best way to overcome this in CI? Clear cargo cache?

**Comment by arlosi** [comment]
Any of these methods will get you unblocked:
* Disable the sparse-registry flag
* Install an older nightly such as `nightly-2022-10-10`
* Wait for a newer nightly - should be available in a couple days.
