### ISSUE TITLE
Cargo can't find adler on crates.io

### ISSUE THREAD

**Issue by gjf2a** [rust-lang/cargo#11256]
### Current Behavior

When I try to include the `adler` crate, the Rust compiler complains it cannot find it:

```
error[E0433]: failed to resolve: use of undeclared crate or module `adler`
 --> src\lib.rs:2:20
  |
2 |     let mut hash = adler::Adler32::from_checksum(value);
  |                    ^^^^^ use of undeclared crate or module `adler`
```

Here is my include line in `Cargo.toml`:
```
[dependencies]
adler = "1.0.2"
```

If I replace the above line with a link to the Github repo, it works fine:

```
[dependencies]
adler = { git = "https://github.com/jonas-schievink/adler" }
```

### Expected Behavior

I expect the program to compile properly when I use the `crates.io` include line.

### Steps To Reproduce

1. Clone my bug-demonstration repository: https://github.com/gjf2a/adler_test
2. Run `cargo build` to try to compile it.
3. Observe the compile error message.
4. Edit `Cargo.toml` to get `adler` from Github instead.
5. Run `cargo build` to compile it.
6. Observe that it now compiles.

### Environment

OS:
```
Edition	Windows 10 Education
Version	21H1
Installed on	‎10/‎18/‎2021
OS build	19043.1288
Serial number	PF1C5VWB
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

Machine:
```
Device name	20003LPU
Full device name	20003LPU.hendrix.local
Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
Installed RAM	12.0 GB (11.8 GB usable)
Device ID	29A20975-2723-4644-B9A6-A9500C206F8E
Product ID	00328-10000-00001-AA962
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points
```

Rust/Cargo:
```
PS C:\Users\ferrer\IdeaProjects\adler_test> cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)
PS C:\Users\ferrer\IdeaProjects\adler_test> rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

**Comment by Eh2406** [comment]
Transferred.

**Comment by gjf2a** [comment]
Deleting `.cargo/registry` did the trick. It now works fine! Thank you for the suggestion!
