### ISSUE TITLE
cargo vendor dropping fields when applied to workspace.

### ISSUE THREAD

**Issue by aarond10** [rust-lang/cargo#11269]
### Problem

Attempting to cargo vendor the "type_hash" crate fails to preserve some package fields. 

Specifically, these disappear from "type_hash_core" after the Cargo.toml manifest rewrite:
```
documentation = "https://docs.rs/type_hash"
homepage = "https://github.com/peterjoel/type_hash"
repository = "https://github.com/peterjoel/type_hash"
```
----
I had a quick look but can't see the problem here.

Vendored Cargo.toml:
```
..
[dependencies]
type_hash = "0.3"
..
```

Invoking `cargo vendor` will succeed, but will leave type_hash_core without the above-mentioned fields.
Note that "type_hash_core" package is version 0.2. The other two are version 0.3.

Actually, the repository is missing from crates.io as well:
 * https://crates.io/crates/type_hash_core
 * https://crates.io/crates/type_hash_macros
 * https://crates.io/crates/type_hash

I'm not sure if its a parsing error (I don't see the problem) or something related to treatment of these fields WRT different version numbering.

### Version

```text
cargo 1.59.0 (49d8809dc 2022-02-10)
release: 1.59.0
commit-hash: 49d8809dc2d3e6e0d5ec634fcf26d8e2aab67130
commit-date: 2022-02-10
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Debian rodete (rodete) [64-bit]
```

**Comment by ehuss** [comment]
`type_hash_core` 0.2.0 as published on Jan 2, 2021 did not have those fields: https://github.com/peterjoel/type_hash/blob/v0.2.0/core/Cargo.toml

It looks like they have added them afterwards, but have not published a new version.

**Comment by aarond10** [comment]
This was the piece I was missing. The latest (0.3.0) `type_hash/Cargo.toml` depends on:
```
type_hash_core = { version = "=0.2.0", path = "../core" }
```
It looks like some tooling I am working with is ignoring the path and querying crates.io for the older release. The version in the repo should probably be bumped to avoid this sort of thing. I'll send a pull request and close this.

Thanks for the help!
