### ISSUE TITLE
Profile based `rustflags` generate unknown unstable option: `build-std`

### ISSUE THREAD

**Issue by Wyvern** [rust-lang/cargo#11275]
When using some -Z flags in `profile based rustflags` such as `build-std` `build-std-features` `panic-in-drop=abort`, the compiler generate error `unknown unstable option:  build-std ...`.

for example: a customized `src` profile with `rustflags`:

```
[profile.src]
inherits = "release"
panic="abort"
rustflags = ["-Zbuild-std=core,alloc,std,"-Zbuild-std-features=panic_immediate_abort","-Zpanic-in-drop=abort"]
[profile.std.build-override]
inherits = "release"
[profile.std.package."*"]
inherits = "release"

```
When build using `cargo b --profile src` the above error raised.

Is it a bug of `cargo-features = ["profile-rustflags"]` or something else?

**Comment by ehuss** [comment]
Transferred to rust-lang/cargo

`rustflags` in a profile are flags that apply to `rustc`.  `-Zbuild-std` is a flag for cargo. Cargo's flags cannot be set from a profile.  I recommend using an alias to set which flags to use.

**Comment by Wyvern** [comment]
Thx @ehuss , that make sense.

Use `-Zpanic-in-drop=abort` in `[profile.src] rustflags` combined with set alias `src= "build --profile src -Zbuild-std=std... --target <target>" ` compiler hit `error: the crate std is compiled with the panic-in-drop strategy unwind which is incompatible with this crate's strategy of abort`. 

But, if set `-Zpanic-in-drop=abort` in `[build] rustflags` everything works fine. It seems that `profile based rustflags` wasn't aware of `cargo -Zbuild-std` flags in this scenario.

**Comment by ehuss** [comment]
Indeed that flag does not work in a profile rustflags because profile rustflags are being passed to build scripts. That is one of the concerns registered with the design over on the tracking issue at #10271.

**Comment by ehuss** [comment]
I'm going to close, as I don't think cargo will be parsing `profile.rustflags` to validate the flags.  As for the build-script issue, that is an open question on the design tracked in #10271.
