### ISSUE TITLE
optional path imported dependency is not optional

### ISSUE THREAD

**Issue by flisky** [rust-lang/cargo#11279]
### Problem

I'm twisting my project into `wasm` target, and found this unexpected behaiver.

### Steps

1. the workspace Cargo.toml:
```
[workspace]
members = [
  "root",
]
resolver = "2"
```
2. the root Cargo.toml:
```
[package]
name = "root"
version = "0.1.0"
edition = "2021"

[dependencies]
dep1 = { path = "../dep1", optional = true }
```
3. the on-purpose compile failed dependency dep1/src/lib.rs
```
compile_error!("not compiled");
```

expected: compile fine
result: 
```
error: not compiled
 --> dep1/src/lib.rs:1:1
  |
1 | compile_error!("not compiled");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `dep1` due to previous error
```

### Version

```text
cargo 1.66.0-nightly (071eeaf21 2022-10-22)
release: 1.66.0-nightly
commit-hash: 071eeaf210708219a5a1b2c4728ca2f97df7f2ae
commit-date: 2022-10-22
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

**Comment by weihanglo** [comment]
As [The Cargo Book says](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields),

> All [path dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies) residing in the workspace directory automatically become members.

This should be the expected behaviour. You could use `exclude` field to prevent path dependencies from being included.

**Comment by weihanglo** [comment]
Close as it is expected. See <https://github.com/rust-lang/cargo/issues/11279#issuecomment-1288002627>. Thank you!

**Comment by flisky** [comment]
Thank you for the quick response, and I can live with the explicit `workspace.exclude`:)
