### ISSUE TITLE
Forbidden to exist multiple versions for some dependency

### ISSUE THREAD

**Issue by LYF1999** [rust-lang/cargo#11288]
### Problem

there is a crate `some_tls` export a thread local 
```rust
thread_local! {
    pub static FOO: RefCell<u32> = RefCell::new(1);
}
```
and it is dependent on crate `A` and crate `B`.
if there are multiple versions `some_tls`, there will be multiple thread local `FOO`.

### Proposed Solution

can we add a config key for `cargo.toml`like
```
[[bans.deny]]
name = "some_tls"
multiple-versions = "deny"
```
to force there is only one version `some_tls` in dependency tree.

**Comment by Eh2406** [comment]
There are 2 ways to do this now. One is to never bump your major version. The other is to add a `links` attribute to your Cargo.toml. In ether case you may want a separate "core" crate just for "can't duplicate" stuff

**Comment by LYF1999** [comment]
hm... I think it's really hard for us to never bump the major version. we may change the type of thread local key in `some_tls`

**Comment by Eh2406** [comment]
Either there is only one version of the crate in a dependency tree or there are two copies of the `some_tls`.

You can decide that it is better to have a build error then duplicate copies, then a `links` attribute is what you want. If the dependencies do not agree on a version then your users will get a build error. If you need to change the API, then all your users will need to coordinate changing together.

You can decide that duplicate copies are bad, but not so bad as to require a build error, then a core crate that only changes its major version when `some_tls` has an API change is what you want. When you do a change, users may have duplicates until all of the intermediate deps have been updated.

See https://crates.io/crates/rayon-core for an example.

What behavior do you want when you have to change the API of `some_tls`?

**Comment by LYF1999** [comment]
thanks, I have understood the behavior of `links`. And it can solve my problem.
