### ISSUE TITLE
Allow bin directory outside $CARGO_HOME

### ISSUE THREAD

**Issue by dancojocaru2000** [rust-lang/cargo#11284]
Allow specifying a folder where cargo binaries are located (perhaps using `$CARGO_BIN` or something similar).

**Comment by weihanglo** [comment]
Assumed you want to invoke a external subcommands from your own director. Roday every executable prefixed with `cargo-` under your `$PATH` will be discovered as an available subcommand. See [External tools: Custom subcommands](https://doc.rust-lang.org/nightly/cargo/reference/external-tools.html#custom-subcommands) for more. Is this what you want?

**Comment by dancojocaru2000** [comment]
Not that, no.

Right now, cargo binaries (like `cargo` itself) are located at `$CARGO_HOME/bin`. I'd like that `bin` folder to be located somewhere else outside `$CARGO_HOME`.

**Comment by weihanglo** [comment]
You can tweak the following options to change the install root:

- `--root` option
- `CARGO_INSTALL_ROOT` environment variable
- `install.root` Cargo config value

See the description section of [`cargo-install` manual](https://doc.rust-lang.org/cargo/commands/cargo-install.html). I believe this is what you want, no? 😆

For `cargo` binary itself, I guess you can just move it to wherever you love.

**Comment by ehuss** [comment]
I'm going to close, as I believe there are multiple ways to change the directory in where things are located. For `cargo install`ed binaries, the options mentioned above will change the directory. If you are using rustup, you can change the location of `cargo` and `rustc` by setting `CARGO_HOME` before running the installer.
