### ISSUE TITLE
Extra "Updating index" messages after publishing a crate

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#11304]
### Problem

This is split out of #11062

When we poll for the crate having been published, it reports "Updating index" for each iteration

> One thing we may want to look at separately is the UI while it is waiting. Cargo just keeps repeating Updating crates.io index. I'm wondering if it might be better to suppress the Updating message? That could maybe be implemented by temporarily enabling quiet mode. I'm also wondering about maybe showing some kind of busy indicator (maybe a progress bar that ticks forward for each second)?

### Steps

With the latest cargo, publish a crate

### Possible Solution(s)

Temporarily turn on quiet in the code

**Comment by epage** [comment]
I **think** this only happens with git registries, so the problem will diminish over time.

There is the potential for multiple exit points, so RAII would be the most robust way of handling this.  At first, I thought lifetimes made that impossible due  conflicting access to `Shell` but instead of the Drop struct holding onto `Shell`, it can hold onto `Config`, so it shouldn't be too hard to implement.

**Comment by mitsuhiko** [comment]
> I think this only happens with git registries, so the problem will diminish over time.

From my experience it happens on crates.io so that seems pretty widespread. Since cargo is already capable of showing progress bars I wonder if something like that could be used here instead. It almost looks like a bug now.

**Comment by epage** [comment]
> Yes, it does happen with crates.io when used via git. I believe in my testing, we don't see that when accessing crates.io via the soon-to-stablize sparse api. Granted, when I wrote this, I thought sparse registry support would have been stablized by now.
