### ISSUE TITLE
Overriding build script path

### ISSUE THREAD

**Issue by Noxivs** [rust-lang/cargo#1130]
Hi,
Apparently, It is not working, but cargo will be able to override the build script path ?
It is maybe a bad way to handle things, but my thinking seems like that :
```
./.build/build.rs
./.build/Cargo.toml    // It is here that I would like to override the build script path.
./.cargo/config          // paths = ["./.build"]
Cargo.toml
```

Thank you,
Regards.

**Comment by alexcrichton** [comment]
The `paths` key in the configuration is used to override packages, not individual build scripts.

To override a build script you need to override the library that it's linking: http://doc.crates.io/build-script.html#overriding-build-scripts
