### ISSUE TITLE
Cannot build Cargo due to cyclic dependency

### ISSUE THREAD

**Issue by mjk-gh** [rust-lang/cargo#11309]
I wanted to install a program (mail client 'meli') that offered installation via "Cargo":

```
# cargo install meli
    Updating crates.io index
  Downloaded meli v0.7.2
  Downloaded 1 crate (642.0 KB) in 0.51s
  Installing meli v0.7.2
  Downloaded fallible-streaming-iterator v0.1.9
  Downloaded async-executor v1.4.1
  Downloaded futures-executor v0.3.25
  Downloaded enumflags2 v0.7.5
  Downloaded encoding-index-singlebyte v1.20141219.5
  Downloaded fastrand v1.8.0
  Downloaded filetime v0.2.18
  Downloaded futures-channel v0.3.25
  Downloaded flate2 v1.0.24
  Downloaded futures-core v0.3.25
  Downloaded encoding_index_tests v0.1.4
  Downloaded encoding-index-simpchinese v1.20141219.5
  Downloaded futures-sink v0.3.25
  Downloaded getrandom v0.2.8
  Downloaded futures-macro v0.3.25
  Downloaded encoding-index-tradchinese v1.20141219.5
  Downloaded lazycell v1.3.0
  Downloaded log v0.4.17
  Downloaded futures-task v0.3.25
  Downloaded mio-extras v2.0.6
  Downloaded num_cpus v1.13.1
  Downloaded once_cell v1.15.0
error: failed to compile `meli v0.7.2`, intermediate artifacts can be found at `/tmp/cargo-installi9e8QH`

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.15.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

As my Linux distribution does not offer a newer version of Cargo than `0.47`, I tried to build the current version from the github source, but README.md states:

```
            ### Requirements

Cargo requires the following tools and packages to build:

* `cargo` and `rustc`
```

A cyclic dependency as requirement for building Cargo?

And building the current version of Cargo with an older version of Cargo doesn't work:

```
$ cargo build --release
error: failed to parse manifest at `/home/mjk/tmp/prog/cargo/cargo/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

What am I doing wrong?

**Comment by Eh2406** [comment]
> As my Linux distribution does not offer a newer version of Cargo than `0.47`

This is your problem. Your Linux distribution claims to provide Cargo but doesn't actually keep it up to date. If you want to stick with your Linux distribution, then install `meli` from them.
If you're willing to install programs from the Internet, then use an approved installation method for Cargo and Rust.

**Comment by mjk-gh** [comment]
> > As my Linux distribution does not offer a newer version of Cargo than `0.47`
> 
> This is your problem. Your Linux distribution claims to provide Cargo but doesn't actually keep it up to date.

It would provide security fixes, if there were any. That concept is called a "stable" flavor of a Linux distribution, and obviously has pros and cons.

> If you want to stick with your Linux distribution, then install `meli` from them. If you're willing to install programs from the Internet, then use an approved installation method for Cargo and Rust.

I found another approved installation method, which does not come with a Kafkaesque cyclic dependency (at least it's not obvious):

URL: https://doc.rust-lang.org/cargo/getting-started/installation.html
<hr>
The easiest way to get Cargo is to install the current stable release of [Rust](https://www.rust-lang.org/) by using [rustup](https://rustup.rs/). Installing Rust using rustup will also install cargo.

On Linux and macOS systems, this is done as follows:

`curl https://sh.rustup.rs -sSf | sh`

It will download a script, and start the installation. If everything goes well, you’ll see this appear:

`Rust is installed now. Great!`
<hr>

Honestly, why is there a cyclic dependency? Asking for a friend. :-)

**Comment by Eh2406** [comment]
> Not in the repositories yet.

This is one of the big cons of stable distributions. They fundamentally can't get new projects, or versions of projects.

> Honestly, why is there a cyclic dependency? Asking for a friend. :-)

Lots of languages are self hosted. Clang is written in C++ so in order to get your C++ compiler you need to have one already. Rust is the same way, in order to build the current version of the compiler you need the previous version of the compiler. You can do what's called "bootstrapping" installing each version one at a time, using 1.x to build 1.(x+1) then using it to build 1.(x+2)... And this is how the official releases are made. For now you can only do bootstrapping one version at a time, because the current development version of the compiler uses features from the most recently released version of the compiler. One of the best ways for the developers of language to test new features and see if they work well is to use them on a big production project like the Rust compiler itself.

Cargo only promises to work with the version of the Rust compiler it ships with. We could decide to use new functionality and language the moment there is development version of the compiler that supports that functionality. Because it makes development easier we actually only use features when they're available in the current released version of the compiler.

**Comment by mjk-gh** [comment]
> > Not in the repositories yet.
> 
> This is one of the big cons of stable distributions. They fundamentally can't get new projects, or versions of projects.
> 
> > Honestly, why is there a cyclic dependency? Asking for a friend. :-)
> 
> Lots of languages are self hosted. Clang is written in C++ so in order to get your C++ compiler you need to have one already.

But just _some_ (not totally outdated) version of it, I presume. At least I never ran in a situation where installation of X required the direct previous version of X already installed, that's new to me.

[...]
> For now you can only do bootstrapping one version at a time, because the current development version of the compiler uses features from the most recently released version of the compiler. One of the best ways for the developers of language to test new features and see if they work well is to use them on a big production project like the Rust compiler itself.

Okay, that is a comprehensible point.

Thanks for the detailled answer, I feel unconfused now. :)

**Comment by weihanglo** [comment]
Thank you for raising this issue, and also thank Eh2406 for demystifying the situation.

I am going to close this out as there is nothing Cargo can do at this moment. If you think it is wrong, leave comments here and we can reopen.
