### ISSUE TITLE
rustc (when called by cargo) should print filenames with respect to the current directory.

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/cargo#1134]
It doesn't when it compiles dependencies.

**Comment by huonw** [comment]
cc https://github.com/rust-lang/cargo/issues/209

**Comment by alexcrichton** [comment]
Closing as a dupe between the combination of https://github.com/rust-lang/cargo/issues/209 and https://github.com/rust-lang/cargo/issues/694
