### ISSUE TITLE
0.66.0 git tag missing

### ISSUE THREAD

**Issue by Bo98** [rust-lang/cargo#11345]
### Problem

Cargo 0.66.0 has been pushed to crates.io (https://crates.io/crates/cargo/0.66.0) and is a part of the Rust 1.65 release, but there isn't a git tag for it yet.

**Comment by Mark-Simulacrum** [comment]
Yep, @pietroalbini is going to take a look at creating it (probably in the next week or so). We ran into some trouble with our scripts to do this so didn't quite get it done yet, but it's a known problem. Thanks for filing an issue to track it.

In the future we expect to move tagging and publishing Cargo to the same system that publishes the rust-lang/rust tag (https://github.com/rust-lang/promote-release/) which will eliminate this problem.

**Comment by pietroalbini** [comment]
Fixed.
