### ISSUE TITLE
Support for 'cargo rebuild' or  'cargo clean build'

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang/cargo#1136]
Once I build using 'cargo build' command, it doesn't rebuild even though I modified source file.  I have to do cargo clean and than cargo build again.

Can we have support for one of these two below where clean and build are done in one command?

    cargo rebuild
        or
    cargo clean build

**Comment by alexcrichton** [comment]
Cargo actually supports custom commands so long as the executable `cargo-foo` is in your `$PATH`. This means that this is actually already done today with https://github.com/pwoolcoc/cargo-do via `cargo do clean build`!

**Comment by rohitjoshi** [comment]
Thx for the suggestion but  would prefer setting an alias in my bash script  rather than installing/building external tool on top of cargo :)

**Comment by yeukhon** [comment]
@alexcrichton  I second this. Coming to rust as a new comer, I wish it supports out of the box. I doubt this would add much weight to the project. This is not quite a big feature request.

cc: @rohitjoshi

**Comment by antoyo** [comment]
One difference of having `rebuild` command (compared to do `clean`, then `build`) would be that you don't have to recompile all of the dependencies.
That would be a major win in compile time when you have to do that.
