### ISSUE TITLE
features settings are incorrectly overridden

### ISSUE THREAD

**Issue by ktmlm** [rust-lang/cargo#11372]
### Problem

When a crate that is directly dependent on the codebase is also depended on by another dependency, the features set for this crate in the codebase will be incorrectly overwritten by the features in that indirect dependency.

The premise of this phenomenon is that the version of the crate used is the same, and the source of the code is the same. But if the version is different, or the source of the code is different (for example, one comes from 'crates.io', and the other refers to a local path), this kind of error will not appear.

For example:
- crate A depend on crate X, features settings for X is `["json_codec"]`
- crate A depend on crate B
- crate B depend on crate X, features settings for X is `["bincode_codec"]`

The end result will be: the features settings for `crate X` in `crate A` will be overridden by the settings in `crate B`, that is `["bincode_codec"]`, this behavior should be an unexpected bug.

### Possible Solution(s)

Multiple references to the same version of the same crate but with different features should be compiled and referenced separately as different libraries.

### Version

rust 1.65 stable

**Comment by weihanglo** [comment]
In Cargo, [features get unified](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) during the compilation. In your particular case, assumed all the presences of crate `X` in your dependency tree are in SemVer-compatible versions. You should get a unified feature set `["json_codec", "bincode_codec"]` annd `X` compiles only once with that feature set.

You can also run `cargo build --verbose` and search for something like `--cfg 'feature="bincode_codec"'` and `--cfg 'feature="json_codec"'` to verify Cargo passing the correct features to rustc.

If this is not the case you encountered. Please provide a minimal reproducible example to help maintainers find the quirky behaviour.
