### ISSUE TITLE
config.lock exceptions when sharing only ~/.cargo/registry mount

### ISSUE THREAD

**Issue by howardjohn** [rust-lang/cargo#11376]
### Problem

We are seeing issues when we have multiple Cargo instances running concurrently while sharing a `~/.cargo/registry`. These builds are run in docker containers, but with a shared volume mounted to `~/.cargo/registry`, with the intent that crate dependencies will be cached between jobs.

This works normally. However, when we run 2 jobs concurrently, we occasionally see issues.

Below shows three examples:

```
+ cargo build --release
error: failed to get `anyhow` as a dependency of package `ztunnel v0.0.0 (/home/prow/go/src/istio.io/ztunnel)`

Caused by:
  failed to initialize index git repository (in "/home/.cargo/registry/index/github.com-1ecc6299db9ec823")

Caused by:
  failed to lock file '/home/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/config.lock' for writing: ; class=Os (2); code=Locked (-14)
make: *** [Makefile.core.mk:23: release] Error 101
```

```
+ cargo build --release
    Updating crates.io index
 Downloading crates ...
error: failed to download `petgraph v0.6.2`

Caused by:
  unable to get packages from source

Caused by:
  failed to unpack package `petgraph v0.6.2`

Caused by:
  failed to open `/home/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/.cargo-ok`

Caused by:
  File exists (os error 17)
make: *** [Makefile.core.mk:23: release] Error 101
```

```
+ cargo build --release
error: failed to get `anyhow` as a dependency of package `ztunnel v0.0.0 (/home/prow/go/src/istio.io/ztunnel)`

Caused by:
  failed to initialize index git repository (in "/home/.cargo/registry/index/github.com-1ecc6299db9ec823")

Caused by:
  could not find repository from '/home/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/'; class=Repository (6); code=NotFound (-3)
make: *** [Makefile.core.mk:23: release] Error 101
```

### Steps

Its a bit hard to reliably reproduce. We do see this in our CI fairly often though. I can try to isolate this in a local environment if desired.

### Possible Solution(s)

My expectation is that locks are either waited for, or at least a more clear error message around why its locked and what to do (I assume "don't run cargo concurrently" or similar would be the recommendation, if this is WAI?)

### Version

```text
cargo 1.65.0 (4bc8f24d3 2022-10-20)
release: 1.65.0
commit-hash: 4bc8f24d3e899462e43621aab981f6383a370365
commit-date: 2022-10-20
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for posting this. 

Is the shared volume on NFS? I am asking because Cargo does have a [coarse advisory file lock mechanism] with the file `~/.cargo/.package-cache`, based on `flock` on Unix and `LockFileEx` on Windows. It seems like flock doesn't work on your platform. Or maybe some other special settings on Docker shared volumes is causing this?

[coarse advisory file lock mechanism]: https://github.com/rust-lang/cargo/blob/26f4c036610a8dfeb368406d7299ba8da0e50c84/src/cargo/util/config/mod.rs#L1692-L1755

**Comment by howardjohn** [comment]
Its on a Kubernetes cluster with a hostPath mount. Its actually using containerd I guess, not Docker.

Volume settings:

```
            {
                "destination": "/home/.cargo/registry",
                "type": "bind",
                "source": "/var/lib/kubelet/pods/b0f72898-1ae9-40b0-8677-1887f3868a30/volume-subpaths/build-cache/build-tools/1",
                "options": [
                    "rbind",
                    "rprivate",
                    "rw"
                ]
            },
```

The OS is "COS" (a GCP container optimized OS).

As far as I know this should be ~equivalent to just a standard docker container and mount

**Comment by weihanglo** [comment]
Hmm… I see. I guess probably the file lock located at `~/.cargo/.package-cache` is not shared, so the advisory lock mechanism won't work. A possible way to solve this might be fetching registry data and `.crate` file in a single container, and then using multiple containers to build concurrently. This will also save some bandwidth.

**Comment by howardjohn** [comment]
Thanks for the insight, that would certainly explain this! 

Unfortunately our CI is pretty naive so we can't easily sequence containers. I had initially wanted to mount the full `~/.cargo`, but the issue I ran into is that it then overrides `~/.cargo/bin` so we lose a bunch of binaries from the container. I suppose we could just move everything out of `~/.cargo/bin` though, as a workaround?

It doesn't look like there is a way to "mount ~/.cargo except ~/.cargo/bin" in docker.

**Comment by howardjohn** [comment]
Thanks a bunch! Super helpful and I think we have things working now. Sounds like this is WAI so I made the title more clear for future folks and will close
