### ISSUE TITLE
`cargo add` and `ctrl + c`

### ISSUE THREAD

**Issue by cavemanloverboy** [rust-lang/cargo#11386]
### Problem

I hit `ctrl+c` when cancelling a redundant `cargo add` command, and discovered that my Cargo.toml had been entirely deleted.

### Steps

1. `cargo add` a crate
2. `ctrl+c` before it finishes successfully

### Version

```text
cargo version --verbose
cargo 1.65.0 (4bc8f24d3 2022-10-20)
release: 1.65.0
commit-hash: 4bc8f24d3e899462e43621aab981f6383a370365
commit-date: 2022-10-20
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: CentOS 7.9.2009 (Core) [64-bit]
```

**Comment by epage** [comment]
We are using `std::fs::write`, so the scope of this race condition is very small.  Resolving this completely would require an atomic write.

**Comment by ChrisDenton** [comment]
Could it not write to a temporary file and then atomically replace the original?
