### ISSUE TITLE
docs: add documentation on platform 'triple's, example usages

### ISSUE THREAD

**Issue by kevinushey** [rust-lang/cargo#11398]
### Problem

Primarily related to https://doc.rust-lang.org/cargo/reference/config.html.

I believe it would be helpful if that page included:

- A brief discussion of what a platform 'triple' is, or a link to a document with such a description;
- Some instructions on how one can figure out the 'triple' for their host machine, or other potential targets.

### Proposed Solution

Perhaps a small section could be added immediately after https://doc.rust-lang.org/cargo/reference/config.html#configuration-format. Here's a short draft:

## Platform Triples

Platform-specific compiler and linker flags can be specified as part of `[target.<triple>]` configuration entries in `config.toml`. Here, `<triple>` refers to a [Target Triplet](https://wiki.osdev.org/Target_Triplet). It has the form `<machine>-<vendor>-<os>`, and you can use:

```
rustc -vV
```

to infer your machine's platform triple, which is printed as part of the `host:` field.

### Notes

I'm making this as an issue first just to confirm whether this feels like a worthwhile change; if so, I can make a PR.

**Comment by weihanglo** [comment]
Thanks for the report!

Target triple has its own place in the appendix: <https://doc.rust-lang.org/cargo/appendix/glossary.html#target>. Cargo also mentions target triple in the manual of each build command, such as <https://doc.rust-lang.org/cargo/commands/cargo-build.html#compilation-options>. 

We may want to refer to the appendix, but I am not sure where to add and what is the right amount of doc to add. Maybe put a reference under [`[target]` key](https://doc.rust-lang.org/cargo/reference/config.html#target)?

**Comment by kevinushey** [comment]
Thank you for pointing that out! I like the idea of adding a link to the target triple section in the appendix.

Maybe the simplest answer here is to add a sentence after the example configuration in https://doc.rust-lang.org/cargo/reference/config.html#configuration-format, with something like:

> See [Target](https://doc.rust-lang.org/cargo/appendix/glossary.html#target) in the glossary for more details on target triples.

**Comment by jofas** [comment]
https://github.com/rust-lang/cargo/blob/fc2242a8c5606be36aecfd61dd464422271dad9d/src/doc/src/reference/config.md?plain=1#L1034-L1039

I'd suggest making  `<triple>` a link to the target section of the glossary. We could do this for every occurrence of `<triple>` on this page. Do you agree that this would be enough to clarify what  target triples are?

**Comment by weihanglo** [comment]
I think that is sufficient, despite that you cannot link to **Target Triple** directly 🥲. We could also update other pages mentioning that if possible. 

(Except `--target`  in build command manual I guess. They already got enought information).

**Comment by jofas** [comment]
https://github.com/rust-lang/cargo/blob/fc2242a8c5606be36aecfd61dd464422271dad9d/src/doc/src/appendix/glossary.md?plain=1#L181-L200

Couldn't we convert the list in the glossary to `<h4>` subsections with `####` in order to link to them? The depth is supported by mdbooks, as seen in the snippet I posted above: 

> https://github.com/rust-lang/cargo/blob/fc2242a8c5606be36aecfd61dd464422271dad9d/src/doc/src/reference/config.md?plain=1#L1034

**Comment by jofas** [comment]
True. Also the `Target` section in the glossary is not that long to begin with. I'll start working on a PR where I add links to occurrences of `triple` or `host triple` inside the `src/doc/src/` directory (except to the `--target` option of the `cargo build` command).

**Comment by weihanglo** [comment]
I believe #11603 fixes this. Close it now. Thank you everyone for participating in the discussion and fix!
