### ISSUE TITLE
Cargo clone optional git dependencies even if related feature is disabled

### ISSUE THREAD

**Issue by fMeow** [rust-lang/cargo#11393]
### Problem

Cargo clone optional git dependencies even if the feature is disabled.

We would like to use private cartes in a git repo, and use feature to enable different functions. Moreover, each features gate is provided for different teams, that have varied access to git repos of optional dependencies.

But cargo check will clone all the repo listed in `Cargo.toml`, regardless of whether the crates is needed in current feature settings.

### Steps

1. Say we have have a feature gate that requirs an optional dependency
```toml
[features]
empty = [ "non-exist" ]

[dependencies]
non-exist = { git = "ssh://git@github.com/fMeow/non-exist.git", optional = true }
```
2. Even if we disable the all features, optional git dependencies are still cloned.
```
$ rm Cargo.lock
$ cargo build --no-default-features
    Updating git repository `ssh://git@github.com/fMeow/non-exist.git`
```

### Possible Solution(s)

Only clone and update git repo for required depencies.

### Version

```text
cargo 1.67.0-nightly (16b097879 2022-11-14)
release: 1.67.0-nightly
commit-hash: 16b097879b6f117c8ae698aab054c87f26ff325e
commit-date: 2022-11-14
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.84.0 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 13.0.1 [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report!  I think this is a variant of the issue reported at #11352. Due to the way the feature resolver works, it needs to download all dependencies *before* doing feature resolution. At that point, it doesn't yet know that the dependency isn't enabled.

I'm going to close in favor of #11352 just to track the limitations of `download_accessible` in one place.

**Comment by fMeow** [comment]
Thanks
