### ISSUE TITLE
compilation fail Tier 1 x86_64-apple-darwin ,error: linking with cc failed: exit status: 1

### ISSUE THREAD

**Issue by devdailytester** [rust-lang/cargo#11396]
### Problem

Most of the infos is stated in https://github.com/cross-rs/cross/issues/1144
The problem is faced when i try to build a build app from other repo using github actions that internally uses cargo.

### Steps

git clone https://github.com/devdailytester/testgithubci
cross build --release -v --target=x86_64-apple-darwin

### Notes

i suspect cargo doesnt fully support thr cross compilation from ubuntu unix to macos?
If can confirm its the case then I will make my action compile natively with a macos setup if possible.

**Comment by weihanglo** [comment]
Copying from <https://github.com/rust-lang/cargo/issues/10873#issuecomment-1186244653>:

> This isn't something that can be addressed through an issue on the Cargo repository, and is likely to be a very large task that would require a large investment. It would likely require putting together a working group, or some other coordinated group of people.

If you have access to GitHub Action, I'd recommend setting up native macOS to make life easier.

Going to close this as it is not a thing we can track here. Thank you!
