### ISSUE TITLE
atty dependency has security issue

### ISSUE THREAD

**Issue by cemoktra** [rust-lang/cargo#11416]
### Problem

The dependency to atty has a security issue, also atty seems to be unmaintained. 

https://rustsec.org/advisories/RUSTSEC-2021-0145

### Possible Solution(s)

Use https://crates.io/crates/is-terminal instead

### Version

```text
0.66.0
```

**Comment by ChrisDenton** [comment]
As noted in the advisory official releases of Cargo aren't affected by this particular soundness issue because they don't use an allocator that aligns to less than 8 bytes.

However the maintenance issue is still a concern.

**Comment by epage** [comment]
While cargo-the-bin isn't affected, cargo-the-lib would be and there are people who link against cargod

**Comment by cemoktra** [comment]
Great is this coming to next rust version or earlier?

**Comment by Muscraft** [comment]
This will be in `1.67.0`, which should release on [January 26 2023 UTC](https://forge.rust-lang.org/#current-release-versions). 

The cutoff for `1.66.0` was on [October 28 2022 UTC](https://forge.rust-lang.org/#current-release-versions).
