### ISSUE TITLE
Document new default of `-Zrustdoc-scrape-examples` 

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#11424]
### Problem

#10343 introduces new behaviours for `-Zrustdoc-scrape-examples`, specifically, scraping examples by default under some circumstances. It would be helpful if the unstable doc can reflect this change a bit.

### Proposed Solution

Update https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#scrape-examples

**Comment by weihanglo** [comment]
cc @willcrichton, could you help this?

**Comment by willcrichton** [comment]
Yes I'll take care of it.
