### ISSUE TITLE
cargo locking doesn't work on Solaris

### ISSUE THREAD

**Issue by psumbera** [rust-lang/cargo#11421]
### Problem

As described in https://bugzilla.mozilla.org/show_bug.cgi?id=1802095#c5 cargo locking doesn't work on Solaris:

"normally, running cargo twice in the same workspace will make one of them wait for the other".

Can you please point me to relevant peace of code? Maybe it's related to missing flock() system call on Solaris?!

**Comment by glandium** [comment]
Erf https://github.com/rust-lang/cargo/blob/5a7ba9cdfbb09d389888bfaade91dd48ed034140/src/cargo/util/flock.rs#L397-L400

**Comment by glandium** [comment]
I guess you'd want something like https://www.perkin.org.uk/posts/solaris-portability-flock.html#flock-wrapper
