### ISSUE TITLE
Cargo error when rustc's dylibs not in path is cryptic

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#1142]
See conversation here: https://twitter.com/coda/status/553682288874385408

**Comment by brson** [comment]
Cargo could probably figure out where rustc's dylibs are and set up the environment appropriately.

**Comment by alexcrichton** [comment]
Hm, I'm not sure this is related to `DYLD_LIBRARY_PATH`, the error is different in that case:


```
$ unset DYLD_LIBRARY_PATH   
$ cargo build -v                                             
An unknown error occurred
Process didn't exit successfully: `rustc -v verbose` (status=5)
--- stderr
dyld: Library not loaded: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-4e7c5e5c.dylib
  Referenced from: /Users/acrichton/code/rust/bin/rustc
  Reason: image not found
```

Seems bad though!

**Comment by alexcrichton** [comment]
This seems very very similar to https://github.com/rust-lang/cargo/issues/987, however.

**Comment by alexcrichton** [comment]
Ok, After re-reading I think this is a dupe of #987, so closing as such.
