### ISSUE TITLE
[cargo build] pass option to do clean build

### ISSUE THREAD

**Issue by HomyeeKing** [rust-lang/cargo#11443]
### Problem

fow now, we have to run `cargo clean` to clean the previous build, as a new rust learner, I think it better to give an option to control whether do a `clean build` or `default build`

### Proposed Solution

cargo build --clean  -----> same with cargo clean

**Comment by epage** [comment]
I'm assuming that by having a `cargo build --clean` short cut for `cargo clean && cargo build`, that you are doing a lot of clean builds.  Could you help me understand why?  I find that its rare that I need to do a clean build.

**Comment by HomyeeKing** [comment]
@epage 
I don't have much rust development experience and I would like to know why design like this.

For me I think instinctively that the `build`  should be a clean build by default and the `cache` should an option.

 I've asked some guys in a group, it seems that the developer seldom use the legacy compile.
It  also kind of wasteful of space

![image](https://user-images.githubusercontent.com/49113249/204953282-21f40cdb-89e0-4d4c-a56e-5c38335f0740.png)

**Comment by epage** [comment]
Build times are a common concern with Rust and doing clean builds each time could negatively impact iteration time. For example, with most of my projects, that means I'd be waiting 3-10 minutes for each compile.

Looking back, I've never used a build tool that does clean builds by default. I have used some that do so for official build artifacts built. In Rust terms, that would either be `cargo publish` which does a clean build or CI which generally requires opting into caching as most services these days use ephemeral runners.

**Comment by epage** [comment]
Also, what do you mean by legacy compiler and what are you showing in the screenshot?

**Comment by HomyeeKing** [comment]
when first run `cargo build`, it generates `hello` binary, after changing manifest name to `hello2` then rerun build command, it generate `hello2` binary
at least for binary case, the  `hello` is no longer useful in most of case

**Comment by epage** [comment]
Thanks for the clarification. Cache invalidation is a difficult problem and tracking unreferenced caches is also difficult. I would also suspect this type of change is rare with little impact until the next `cargo clean` that the costs of addressing it outweigh the benefits.

> An example of a costlier one is when upgrading the compiler. None of the old artifacts are still relevant and take up enormous space. I've taken to clearing all caches on upgrade. There is also little that can be improved as cargo doesn't know if you upgraded or are switching between commonly used compilers, like the latest and your minimum-supported version.

**Comment by HomyeeKing** [comment]
I see.
And also thanks for your reply!
