### ISSUE TITLE
index should be pulled from GitHub archive or shallow clone

### ISSUE THREAD

**Issue by 9hk** [rust-lang/cargo#11440]
### Problem

I dont use Rust a ton, so it seems every single time I `cargo add`, I am greeted with this fun result:

~~~
Updating crates.io index
   Fetch [==========>              ]  45.65%, (66291/307343) resolving deltas
~~~

checking more, I see this is created:

~~~
C:\Users\Steven\.cargo\registry\index\github.com-1ecc6299db9ec823\.git
~~~

which is a whopping 282 MB. If I instead do this:

~~~
git clone --bare --depth 1 https://github.com/rust-lang/crates.io-index
~~~

the same folder is 66 MB. Or I can do this:

~~~
curl -O -L https://github.com/rust-lang/crates.io-index/archive/refs/heads/master.tar.gz
~~~

and the result is 52 MB. So the question is why? Why is Cargo doing this? isnt this hugely wasteful?

**Comment by epage** [comment]
For shallow clone, I'd recommend checking the description for #11176 as it goes into details for why we do what we do and that we have a longer term plan for improving this (sparse registries).   Unsure if there is anything newer than the [call for testing](https://internals.rust-lang.org/t/call-for-testing-cargo-sparse-registry/16862) on using sparse registries today.  #11224 is the issue to track for stablization.

The challenge with downloading the archive is that isn't incremental.   cargo would need to re-download it on every new package published.  For someone using cargo regularly, the incremental approach would be best.  Even for someone who doesn't use cargo regularly, when they do use it they are likely to be using it for an hour or so.  Incremental updates within that time would be useful.

**Comment by 9hk** [comment]
good information. However another question comes to mind. I dont use Rust often, **but I do use it**, maybe once a month or something. So my new question is, why do I not check to choose when cargo updates the index? Maybe I am fine with using a month old index. Why cant I just configure cargo somehow to say "download index the first time, but never download it again, unless I specifically command cargo to do that".

I am not always in strong need of the latest bleeding edge anything, so it seems useful not to be hit with a 280 MB download every week or whatever the current interval is. So, is this something that can be configured, or are the updates forced upon the user?

**Comment by epage** [comment]
There is an `--offline` flag and you can [configure it as well](https://doc.rust-lang.org/cargo/reference/config.html#configuration-format)

**Comment by weihanglo** [comment]
Besides useful tips from epage, highlight that in [RFC 2789](https://rust-lang.github.io/rfcs/2789-sparse-index.html#future-possibilities) it does consider the extensibility of incremental download. Also, there is a [summary](https://github.com/rust-lang/cargo/issues/11014#issuecomment-1222191543) I wrote a while back about the integration of gitoxide.

If you don't mind, I'll close this now, as alternatives are tracked by other issues and features already. Thank you!
