### ISSUE TITLE
Error messages for mismatched versions of path dependencies could be nicer

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1145]
```toml
# Cargo.toml
[package]

name = "a"
version = "0.0.1"
authors = []
```

```toml
# b/Cargo.toml
[package]

name = "b"
version = "0.0.1"
authors = []

[dependencies.a]
path = ".."
```

The first build of `b` works fine:

```
$ cd b; cargo build
   Compiling a v0.0.1 (file:///home/huon/tmp/a/b)
   Compiling b v0.0.1 (file:///home/huon/tmp/a/b)
```

But changing the version number of `a` (say, bumping to 0.0.2) will break the pinning in b/Cargo.lock, and then `cargo build` of `b` will give:

```
$ cd b; cargo build
no package named `a` found (required by `b`)
location searched: file:///home/huon/tmp/a/b
version required: = 0.0.1
```

Running `cargo update` in `b/` fixes this:

```
$ cd b; cargo update && cargo build
   Compiling a v0.0.2 (file:///home/huon/tmp/a/b)
   Compiling b v0.0.1 (file:///home/huon/tmp/a/b)
```

But it's a rather unhelpful error message, especially since there is definitely a package called `a` there. It would be helpful to at least special case `path` dependencies to print something like ``help: found package with version 0.0.2; consider running `cargo update`.``.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I opened one too ( #1144 ). Should I close it ? Btw, your presentation is better than mine.

**Comment by huonw** [comment]
@GuillaumeGomez oh, I didn't realise! I think this one is more focused, so I've closed your one.

**Comment by GuillaumeGomez** [comment]
Ok ! Now let's wait.
