### ISSUE TITLE
cargo bench builds examples but does not do so correctly

### ISSUE THREAD

**Issue by amaranth** [rust-lang/cargo#1146]
It looks like PR #1120 caused `cargo bench` to also build the examples in a project. However, it seems cargo only includes the dev-dependencies which are required to build the examples when you run `cargo bench --verbose`. On top of this, it seems to get the build order wrong so the examples will build first, fail to find their dependencies, then the dependencies will build. This means you have to run the command twice to get a successful build.

We're running in to this in [noise-rs](https://github.com/bjz/noise-rs) which has a setup like this:

```
[package]

name = "noise"
version = "0.0.3"
authors = []

[lib]

name = "noise"

[[example]]

name = "perlin"

[[bench]]

name = "benches"

[dev-dependencies.image]

git = "https://github.com/PistonDevelopers/image.git"
```

The perlin example fails to build with `cargo bench` because it's missing `image` and fails to build until the second run of `cargo bench --verbose` for the same reason.

**Edit:** After poking at it some more it actually seems random whether or not `cargo bench` or `cargo bench --verbose` will ever actually build `image`. It does not appear to be dependent on passing the `--verbose` flag though.

**Comment by huonw** [comment]
Could you paste some example output of cargo?

**Comment by amaranth** [comment]
https://gist.github.com/amaranth/ddbea514754dfdb90c16 shows the two ways it'll fail to build. A successful build had too many warnings from noise-rs so went off my scrollback. It's not very interesting though as it just builds the noise-rs bits the same way as the other attempts but this time succeeds since it has image built already.
