### ISSUE TITLE
Cannot extend build directives within cargo

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#11461]
Because of `cargo:KEY=VALUE`, it isn't safe to add `cargo:error=` (or any other directive) as it can be interpreted as a KEY/VALUE, blocking #10159.

**Comment by XaurDesu** [comment]
Could i take a look into this?  Currently learning rust and it is marked as 'help wanted'

**Comment by epage** [comment]
Sure.  Feel free to message me on Zulip if you have questions

**Comment by hi-rustin** [comment]
@rustbot claim

Since there was no progress for a long time, I wanted to try to implement it.

**Comment by hi-rustin** [comment]
> * Change it on an edition boundary
>   
>   * A directive could opt-in to the style
>     
>     * We'd need "begin" and "end"s to allow composing with third-party dependencies
>   * Provide an env variable with the `package.edition` for what directive syntax is accepted by default
>     
>     * There are target-specific editions but the build script is tied to the package and not the target

@epage Could you explain a bit about `change it on an edition boundary`? Did you mean we use `cargo:` in edition 2021, and use `cargo::` in the next edition?

**Comment by XaurDesu** [comment]
> @rustbot claim
> 
> Since there was no progress for a long time, I wanted to try to implement it.

Go ahead, i wanted to help here but college brought me down. As @epage told me, please take a look into #11461 , because it points out to a bunch of the places that must be changed for this request.

**Comment by epage** [comment]
@hi-rustin sorry if this wasn't clear but all of those notes were a summary of the discussion.  We ended up deciding this will not need an edition boundary as we ended up preferring the "Hack in a new namespace, say cargo:: instead of cargo:" route (those were meant to be alternatives, not parts of the same solution).

**Comment by epage** [comment]
Its not quite clear to me what we would want another issue for or what you mean by "added to the issue list".

This issue would be resolved by the `cargo:::`.  We could have an issue for directive versioning support but I personally wouldn't bother creating one.  If we actually run into that, we can reference this issue for context.  I see it as unlikely and adding noise to our already large backlog.

**Comment by XaurDesu** [comment]
Alright then, makes sense.

**Comment by hi-rustin** [comment]
> @hi-rustin sorry if this wasn't clear but all of those notes were a summary of the discussion. We ended up deciding this will not need an edition boundary as we ended up preferring the "Hack in a new namespace, say cargo:: instead of cargo:" route (those were meant to be alternatives, not parts of the same solution).

Got it. Thanks! I will give it a try recently.
