### ISSUE TITLE
cargo publish can fail after --dry-run succeeded

### ISSUE THREAD

**Issue by ijackson** [rust-lang/cargo#11466]
### Problem

In my case, I failed to write a `description` in my `Cargo.toml`.  This caused crates.io to reject my upload.

### Steps

1. Make a package with no `description`
2. `cargo publish --dry-run`, observe success
3. `cargo publish`, observe failure

### Possible Solution(s)

There are many reasons things might go wrong, and the local cargo doesn't know the policy of the remote site.  I think the solution has to be:

 * cargo publish --dry-run should actually send the package to the repository, to an endpoint which *checks* rather than ingests
 * cargo publish --dry-run --offline should not do this.

### Version

```text
cargo 1.65.0-beta.1 (082503982 2022-09-13)
release: 1.65.0-beta.1
commit-hash: 082503982ea0fb7a8fd72210427d43a2e2128a63
commit-date: 2022-09-13
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Debian 10 (buster) [64-bit]
```

**Comment by weihanglo** [comment]
See https://github.com/rust-lang/crates-io-cargo-teams/issues/82

**Comment by weihanglo** [comment]
I am going to close this in favour of #5941, as more discussions happened there. If you think they are inherently different, we can re-open this.
