### ISSUE TITLE
failed to download crate: [60] SSL peer certificate or SSH remote key was not OK (schannel: CertGetCertificateChain trust error CERT_TRUST_IS_PARTIAL_CHAIN)

### ISSUE THREAD

**Issue by Joezeo** [rust-lang/cargo#11502]
### Problem

error: failed to download from `https://crates.io/api/v1/crates/anyhow/1.0.68/download`

Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (schannel: CertGetCertificateChain trust error CERT_TRUST_IS_PARTIAL_CHAIN)

### Notes

I'm trying to access the same URL with curl for Windows, and it works fine.
```
> curl --location --request GET https://crates.io/api/v1/crates/anyhow/1.0.68/download --output anyhow.crate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 43882  100 43882    0     0  29067      0  0:00:01  0:00:01 --:--:--  124k
```

And I changed these configs trying to fix that but didn't work.  
For git:  
```
[http]
    sslVerify = false
```
For cargo:  
```
[net]
git-fetch-with-cli = true

[http]
check-revoke = false
```

### Version

```text
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: x86_64-pc-windows-msvc
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Pro) [64-bit]
```

**Comment by Joezeo** [comment]
Finally, I fix this problem by setting the environment variable CARGO_HTTP_CAINFO manually. 
But I still don't know how this problem came about, everything was fine before today.

**Comment by epage** [comment]
See also #1420
