### ISSUE TITLE
Docs for Cargo Test mislieadingly imply that examples can be built and run as tests

### ISSUE THREAD

**Issue by Farmadupe** [rust-lang/cargo#11528]
### Problem

(Possible alternative title: Cargo Test does not run examples as tests when commanded)

[(Relevant confusion in reddit thread here)](https://www.reddit.com/r/rust/comments/101ifyi/can_i_have_cargo_test_double_check_that_none_of/)

When read literally,  [line 140](https://github.com/rust-lang/cargo/blob/master/src/doc/src/commands/cargo-test.md?plain=1#L140) of Cargo Test docs states that Cargo can reinterpret the main function of an example binary as a test, and execute it.

Since cargo does not appear to do this, a wording that does not have the misleading reading might be appropriate here.

**Comment by epage** [comment]
Not having tried this, I'm assuming what is implicit here is that the default test harness is used, like any other test executable.  This means it will discover and run `#[test]` functions.  You'd have to disable the default test harness to do your own thing.
