### ISSUE TITLE
Asymmetric Tokens from credential processes

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/cargo#11520]
The RFC describes how credential processes can generate Asymmetric Tokens, however that was not implemented in https://github.com/rust-lang/cargo/pull/10771 . We should implement this before stabilization.

cc https://github.com/rust-lang/cargo/issues/10519

**Comment by linyihai** [comment]
Hello, what is the status of this issue? I am looking for a good-first-issue, can i make a try ...

**Comment by weihanglo** [comment]
IIRC, it has just been integrated into the recently stabilized credential provider, under the credential provider alias `cargo:paseto`. See [doc](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#asymmetric-token) for more.

If you are willing to help stabilize asymmetric token feature, there are some unresolved issue listed in #10519 looking for helps. Yet there is no clear mentorship of them at this moment, and it might require extra efforts to figure out the plan and design.

If you are looking for issues open for contribution in general, issues with <https://github.com/rust-lang/cargo/labels/S-accepted> and <https://github.com/rust-lang/cargo/labels/E-easy> are good starts. Please read [the doc on issue label system](https://doc.crates.io/contrib/issues.html#issue-labels) for more.

Thank you.

**Comment by weihanglo** [comment]
@arlosi, I am going to close this as resolved since you've checked the box in #10519. Feel free to reopen if there are more needing to be addressed.

**Comment by linyihai** [comment]
> IIRC, it has just been integrated into the recently stabilized credential provider, under the credential provider alias `cargo:paseto`. See [doc](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#asymmetric-token) for more.
> 
> If you are willing to help stabilize asymmetric token feature, there are some unresolved issue listed in #10519 looking for helps. Yet there is no clear mentorship of them at this moment, and it might require extra efforts to figure out the plan and design.
> 
> If you are looking for issues open for contribution in general, issues with [ S-accepted](https://github.com/rust-lang/cargo/labels/S-accepted) Status: Issue or feature is accepted, and has a team member available to help mentor or review and [ E-easy](https://github.com/rust-lang/cargo/labels/E-easy) Experience: Easy are good starts. Please read [the doc on issue label system](https://doc.crates.io/contrib/issues.html#issue-labels) for more.
> 
> Thank you.

OK, thank you for you suggestions.
