### ISSUE TITLE
Enable the use of alternate fonts in `cargo doc`.

### ISSUE THREAD

**Issue by arj0019** [rust-lang/cargo#11530]
### Problem

I would like to utilize alternate fonts with `cargo doc`. I specifically seek the ability to utilize monospace fonts.

### Proposed Solution

Allow the user to configure `cargo doc` via the command line and/or configuration file.

**Comment by weihanglo** [comment]
`rustdoc` provides a couple of flags letting you customize CSS:

- [`--markdown-css`](https://doc.rust-lang.org/rustdoc/command-line-arguments.html#--markdown-css-include-more-css-files-when-rendering-markdown)
- [`-e`/`--extend-css`](https://doc.rust-lang.org/rustdoc/command-line-arguments.html#-e--extend-css-extend-rustdocs-css)
- Many other [HTML related flags](https://doc.rust-lang.org/rustdoc/command-line-arguments.html?highlight=html)

You can combine them with Cargo's config value [`build.rustdocflags`](https://doc.rust-lang.org/cargo/reference/config.html#buildrustdocflags) or command [`cargo rustdoc`](https://doc.rust-lang.org/nightly/cargo/commands/cargo-rustdoc.html) to get what you want.

**Comment by weihanglo** [comment]
Cargo does promote flags from `rustc`/`rustdoc` to become first-class flags of Cargo itself, such as `cargo doc --document-private-items` (https://github.com/rust-lang/cargo/issues/1520). However, for this case I feel like it is not that frequent to tweak style via command line. It should be more common to set up a configuration for styling once and for all. 

As a result, I am going to close this given the alternatives are obvious. Thank you!

**Comment by arj0019** [comment]
I am able to implement the cargo config file, but it does not recognize the `--markdown-css` flag and there is no example of interfacing with the rustdoc CSS.

```
PS C:\Users\johnsoar\Documents\Personal\GITHUB\charts> cargo doc
 Documenting charts v0.1.0 (C:\Users\johnsoar\Documents\Personal\GITHUB\charts)
error: Unrecognized option: 'markdown-css docstyle.css'

error: could not document `charts`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name charts src\lib.rs -o C:\Users\johnsoar\Documents\Personal\GITHUB\charts\target\doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=8b232a5edf7611e6 -L dependency=C:\Users\johnsoar\Documents\Personal\GITHU
B\charts\target\debug\deps "--markdown-css docstyle.css" --crate-version 0.1.0` (exit code: 1)

```

**Comment by weihanglo** [comment]
Your arguments are merged into one `"--markdown-css docstyle.css"`. If you're using Cargo configuration, try using array, like `rustdocflags = ["--markdown-css", "docstyle.css"]`.

**Comment by arj0019** [comment]
Is there documentation of how to implement custom CSS for rustdoc? Where is the default CSS located?

**Comment by weihanglo** [comment]
Links above https://github.com/rust-lang/cargo/issues/11530#issuecomment-1369556594 are probably enough to play with.

There is also [an old article](https://www.rust-lang.org/governance/teams/dev-tools#Rustdoc%20team) from an official rustdoc team member talking about unstable `--extend-css` stuff (now stabilized).

I guess the default CSS is embedded in the rustdoc source code and generated on-the-fly, though I am not familiar with rustdoc internals.

Hope these help :)
