### ISSUE TITLE
crates.io: Cargo sparse-registry stabilization

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#11536]
@rust-lang/crates-io: This is a proposal to stabilize Cargo's sparse-registry support. We are FCP'ing each team individually to make it easier to get multi-team approval. There is a detailed write-up at https://github.com/rust-lang/cargo/pull/11224#issuecomment-1371266126 of what is being stabilized, along with documentation in the linked PR. We are requesting approval from you for supporting https://index.crates.io/.

If you have questions, feel free to comment on the stabilization PR or here or #t-cargo on Zulip.

**Comment by ehuss** [comment]
@rfcbot fcp merge

**Comment by ehuss** [comment]
Oops, I forgot a team member needs to start the FCP.  Can someone at @rust-lang/crates-io type the `@rfcbot fcp merge` command?

**Comment by JohnTitor** [comment]
@rfcbot fcp merge

**Comment by Turbo87** [comment]
I think I'd feel better if the infra team would also sign off on this since the CDNs are mostly managed on their team

**Comment by Turbo87** [comment]
ah, nevermind, I've just found https://github.com/rust-lang/cargo/issues/11537 😅

**Comment by Eh2406** [comment]
Cargo and Infra have now signed off, so it's all up to you.

**Comment by Turbo87** [comment]
I've put it on the agenda for the team meeting tomorrow 👍

**Comment by Turbo87** [comment]
we discussed this today and we would feel a little better if we had a way to quickly revert users to the git-based index for now. as we noticed with the index normalization, it's always tricky when you don't have a way to rollback such fundamental changes.

we were thinking that maybe if we put something in the `config.json` of the HTTP-based index it could fall back to the git-based index? the exact design is still tbd, but then we could temporarily turn it on and off, if necessary for whatever reason.

does that make sense?

**Comment by arlosi** [comment]
@Turbo87 This doesn't switch users to the sparse index by default. It provides a stable configuration option for users to switch the default.

If for some reason we do need to undo this feature, we can simply revert it (as long as we do it before the 1.68.0 stable release).

I'd rather avoid the complexity of making it an option in `config.json` if possible.

**Comment by Turbo87** [comment]
I think part of the problem here is that we're conflating "stablize the feature in cargo" with "declare https://index.crates.io/ as stable".

I have no issues with stableizing the feature in cargo, but declaring the HTTP-based index as non-experimental is a bit different IMHO. while we have done a bit of testing with a few users it's hard for me to anticipate what kind of issues we will be seeing once we enable everyone to use the HTTP-based index. if we hit some unforeseen scaling issues we would probably need a way to force people back to the old git-based index.

**Comment by arlosi** [comment]
If we really need to force users back to the git index, we could configure `index.crates.io` to respond to requests with an HTTP 403 stating something like: 
> index.crates.io is not available because <reasons>, please remove the registries.crates-io.protocol = 'sparse'` configuration.

Then when users attempted to access the sparse index, they would get the message from Cargo.

Thanks to @Eh2406 for this suggestion. Do you think that would be sufficient?

**Comment by Eh2406** [comment]
We are proposing stabilizing `registries.crates-io.protocol = "sparse"`is an easy way for users to try `sparse+https://index.crates.io/`. Given that the user has opted into it, I don't think it's a good user experience for them to be automatically forced back to the git index. Say for example a user cannot access GitHub, I think it would be very confusing for them to configure to use sparse registries and then get errors about GitHub not being available. On the other hand a good error message like... well @arlosi beat me to it.

I do think it's completely reasonable for crates.io to reserve the right to permanently go back on this stabilization of to this being in beta. I also think it's reasonable for there to be temporary outages with good error messages all the way until some future stabilization of making `protocol = "sparse"` the default.

**Comment by ehuss** [comment]
I would expect that the adoption curve will be slow at first. Only a *very* small number of nightly users will enable it. When it reaches stable, I would still expect that the adoption will be relatively slow. Especially since I imagine people updating CI will be slow (I know I will be too lazy to bother for months or years). Also, not everyone jumps on the latest stable right away. I'm not sure what that adoption curve is, but I imagine it takes weeks or months for things to start ramping up.

Are there any traffic stats for anyone using https://index.crates.io today? I'm curios if *anyone* is testing it. That might be useful to monitor.

**Comment by Turbo87** [comment]
> Then when users attempted to access the sparse index, they would get the message from Cargo.
> 
> Thanks to @Eh2406 for this suggestion. Do you think that would be sufficient?

yes, that sounds sufficient to me. but we should ensure that enabling these errors is documented in the crates.io ops guide and that such errors from the HTTP index are shown to cargo users in a visible way.

**Comment by arlosi** [comment]
@Turbo87 I verified that having the server return an HTTP 403 when fetching `config.json` that the body of the response will be shown to the user. Here's an example:

```
    Updating crates.io index
error: download of config.json failed

Caused by:
  failed to get successful HTTP response from `https://index.crates.io/config.json`, got 403
  body:
  Test message stating why the crates.io sparse endpoint is unavailable.
```

With the upcoming fork for 1.68.0 on Friday the 20th, it would be great if we could get this in before then. Then, if all goes well, we can consider switching the default for 1.69.0.

**Comment by Turbo87** [comment]
checkbox is disabled, let's see if this works:

@rfcbot reviewed

**Comment by carols10cents** [comment]
@rfcbot reviewed

**Comment by pichfl** [comment]
@rfcbot reviewed

**Comment by Eh2406** [comment]
Ping @jtgeibel, @locks, and @smarnach. We are so close. Any chance we can get one of you to sign off today?

**Comment by locks** [comment]
@rfcbot reviewed

**Comment by jtgeibel** [comment]
@rfcbot reviewed

**Comment by ehuss** [comment]
Thanks everyone!
