### ISSUE TITLE
infra: Cargo sparse-registry stabilization

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#11537]
@rust-lang/infra: This is a proposal to stabilize Cargo's sparse-registry support. We are FCP'ing each team individually to make it easier to get multi-team approval. There is a detailed write-up at https://github.com/rust-lang/cargo/pull/11224#issuecomment-1371266126 of what is being stabilized, along with documentation in the linked PR. We are requesting approval from you for supporting https://index.crates.io/.

If you have questions, feel free to comment on the stabilization PR or here or #t-cargo on Zulip.

**Comment by Mark-Simulacrum** [comment]
@rfcbot merge

(I think an infra member needs to do that)

**Comment by jyn514** [comment]
> Publish timeouts: A risk factor is if a user opts-in to the sparse index and uses cargo publish to publish a package. It can sometimes take longer for the sparse index to update due to caching issues. cargo publish will wait up to 1 minute for the index to be updated, which may not be long enough

Can you talk more about what causes these issues? Is CloudFront not invalidating the CDN cache or something like that?

That said I don't think it's a blocker :) I'm very excited to start using this feature!

@rfcbot reviewed

**Comment by jyn514** [comment]
Alternatively, does cargo *need* to wait until the cache is invalidated? Can it use the 200 OK from crates.io instead?

**Comment by ehuss** [comment]
> Can you talk more about what causes these issues? Is CloudFront not invalidating the CDN cache or something like that?

There are two main causes of delays. crates.io itself processes updates asynchronously through a queuing system (similar to docs.rs since I assume you are familiar with that). Each item in the queue can take some time to process, and if it the queue backs up, it can take more than a minute. Each update needs to update the git index on GitHub, post a CouldFront invalidation, upload to S3, etc. There was a recent outage when a user posted thousands of yank requests in a short period of time.  Another example is when GitHub goes down or slows down.

The other cause is CloudFront invalidation. For various reasons, CloudFront invalidation can take a while. It is usually fast (within a few seconds), but sometimes can be slow (some CloudFront docs say up to 100 seconds). There's also a known issue where CloudFront sometimes responds with a 503 error (crates.io has a retry loop to deal with that).

The reason Cargo waits for the cache to be invalidated is so that the user can publish multiple inter-dependent packages. If cargo didn't wait, then when they publish the next package in the dependency chain, it will fail since the previous package isn't "visible" yet. Waiting also provides some assurance to the user that the package is available and they can announce to their users that they can start using it.

We can't make crates.io delay the 200 response due to Heroku connection time and resource limits.

Ideally in the future there would be a better publishing API that avoids these concerns. Perhaps something that allows publishing multiple packages atomically, or possibly with a UI for approving new publishes. There hasn't really been much movement on that, though.

**Comment by jyn514** [comment]
👍 makes sense, and also sounds like a pre-existing problem to some extent, the HTTP index just makes the publish step take slightly longer than before.

**Comment by shepmaster** [comment]
@rfcbot reviewed

**Comment by Eh2406** [comment]
Thank you all for the feedback, and the ongoing support! We couldn't do it without you.
