### ISSUE TITLE
Report when a `cfg(feature)` refers to a feature which doesn't exist on a crate

### ISSUE THREAD

**Issue by illicitonion** [rust-lang/cargo#11559]
### Problem

I have a crate with a feature.

I have CI which runs `cargo test` with that feature enabled.

I also have some tests which are specific to that feature, which are gated behind a `cfg(feature)` attribute.

However, there was a typo in the `cfg(feature)` attribute, which meant that the feature-specific tests were never actually enabled.

Ideally, I would have gotten a compile-time error telling me "You have a `cfg(feature)` which doesn't exist for your crate" (or just a standard unreachable code diagnostic). But at least a warning would be useful.

### Proposed Solution

Provide an error, or at least warning, when a `cfg(feature)` attribute is used which Cargo doesn't treat as a feature for the crate being compiled.

### Notes

I filed this against Cargo because it has the knowledge of the known features of a crate, but it's really a rustc feature request at core - I imagine this either looks like cargo supplying a known feature universe to rustc, or rustc reporting encountered features back to cargo.

**Comment by ehuss** [comment]
There is an unstable feature called [`check-cfg`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#check-cfg) which validates cfg expressions. Perhaps you could give it a try and see if it works with your project? Having people test nightly features (even if just once) is helpful since it can be difficult to get real-world testing.

**Comment by illicitonion** [comment]
I tested it out and https://github.com/rust-lang/cargo/issues/10554 would indeed have prevented my issue - thanks for the pointer!
