### ISSUE TITLE
Updating crates.io index fish: Job 1, 'cargo update' terminated by signal SIGKILL (Forced quit)ing deltas

### ISSUE THREAD

**Issue by CraZySacX** [rust-lang/cargo#11569]
### Problem

The nightly today started what seemed to be a full refresh of the registry when I ran `cargo update` on a local project.  After getting to ~85% it stopped with the message in the title.   This left behind a zombie cargo update process.  

I should note this issue happened on my Linux machine as well as my Mac, with the same message.

### Steps

1. Migrate to a local project
2. Run `cargo update`

### Notes

I was able to fix the issue by deleting the `~/.cargo/registry` directory and re-running cargo update

### Version

```text
cargo 1.68.0-nightly (d992ab4e9 2023-01-10)
release: 1.68.0-nightly
commit-hash: d992ab4e9034930e7809749f04077045af8f4d79
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux [64-bit]
```

**Comment by Eh2406** [comment]
I'm going to consolidate in https://github.com/rust-lang/cargo/issues/11014

**Comment by CraZySacX** [comment]
Yeah the sigkill here was a red herring.  I was ssh'd from my mac into my linux box and didn't notice it.   I've seen the note about the index normalization today which explains the 95k deltas I was seeing across machines.   Thanks for the update.
