### ISSUE TITLE
cargo-install-update doesn't terminate

### ISSUE THREAD

**Issue by float3** [rust-lang/cargo#11575]
### Problem

```cmd
cargo-install-update install-update --git --all
cargo-install-update install-update --all
```
both of these commands do not terminate, and just run forever.
No output beyond `Updating registry 'https://github.com/rust-lang/crates.io-index`
my cpu usage is significantly increased while it's running

### Steps

1. run `cargo-install-update install-update --git --all`

### Notes

I've tried this on `rustup default stable` and `rustup default nightly`
and I also tried stracing the processes but I couldn't make anything of the output, it was just endless console spam.
this command worked before but suddenly stopped working, I don't remember if it was after a specific update or something but it started around 2 days ago iirc.

### Version

```text
cargo 1.68.0-nightly (d992ab4e9 2023-01-10)
release: 1.68.0-nightly
commit-hash: d992ab4e9034930e7809749f04077045af8f4d79
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: EndeavourOS Rolling Release (rolling) [64-bit]
```

**Comment by Eh2406** [comment]
You are hitting https://github.com/rust-lang/cargo/issues/11014 if I had to gess.

**Comment by float3** [comment]
possible, for me it doesn't show a progress bar. I've left it running for 30 mins previously and there was not output

**Comment by weihanglo** [comment]
Close in favor of #11014.

The missing progress bar issue is tracked in #9444 and #11574. Probably related, but could also be an issue of downstream. Thank you
