### ISSUE TITLE
--manifest-path is often silently or partly ignored.

### ISSUE THREAD

**Issue by Tobba** [rust-lang/cargo#1158]
This can be extremely confusing. Specifying `--manifest-path <directory>` will completely ignore the parameter (without telling you). `--manifest-path <directory>/` doesn't do anything either. However,`--manifest-path <directory>/<filename>` causes cargo to check in the specified directory while silently ignoring the filename.

**Comment by mattyhall** [comment]
Hi. I was looking at fixing this.

I was wondering, should the argument to ``--manifest-path`` be a filename or a directory (or both)? 

Thanks.

**Comment by alexcrichton** [comment]
I believe the intention was for `--manifest-path` to always point to a `Cargo.toml` itself

**Comment by alexcrichton** [comment]
I believe this was fixed in #1182.
