### ISSUE TITLE
Set the `CARGO_PKG_README` environment variable

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#11597]
### Problem

Cargo may rewrite the package’s `Cargo.toml` and move the README file around, relative to the manifest. I would like to `include_str!()` this README in my `lib.rs`, but am unable to do so right now, because if I specify `include_str!("../../README")` it works for development, but I can’t package my crate. Conversely if I specify `include_str!("../README")` it works when packaged, but not during development.

### Proposed Solution

Having an environment variable that would tell me where to find the README file would probably be the most straightforward option.

**Comment by weihanglo** [comment]
To me, it seems fine to add a new environment variable. You could follow how other environments were added. Basically you will

- Set a new environment variable [here](https://github.com/rust-lang/cargo/blob/ba6217e40fc05ac95f8a0fbe77aa83cdbc907a10/src/cargo/core/compiler/compilation.rs#L323)
- Add an explanation [here](https://github.com/rust-lang/cargo/blob/ba6217e40fc05ac95f8a0fbe77aa83cdbc907a10/src/doc/src/reference/environment-variables.md#environment-variables-cargo-sets-for-crates) for the new variable.
- Assert the new variable has been set in [this test](https://github.com/mathstuf/cargo/blob/ae6b2f66cf052abf5b5eea9c71d77bcae6ff5582/tests/testsuite/build.rs#L1331-L1398).
- Submit a pull request with a explanation why this is useful with a clear use case.

The Cargo team would probably do an FCP for that before merging.
