### ISSUE TITLE
Duplicate cargo future incompatibilities reports

### ISSUE THREAD

**Issue by rwxsach** [rust-lang/cargo#11594]
### Problem

I have been getting warnings for the traitobject v0.1.0 crate and the number of future incompatibility reports has reached to 950, with the size of the .future-incompat-report.json file at 38kB.  

![image](https://user-images.githubusercontent.com/29777821/213156786-b0477662-74bb-4763-bac7-32a28e1cd1e9.png)

### Possible Solution(s)

Check and return an id if it already exists.

### Version

```text
cargo 1.66.1 (ad779e08b 2023-01-10)
release: 1.66.1
commit-hash: ad779e08be893e57a9e17a810223a3e966f8c0d8
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Fedora 37.0.0 [64-bit]
```

**Comment by rwxsach** [comment]
> Can you say more about what this issue is about? What kind of concerns do you have? It is normal for cargo to increment the `ID` number for each build. It only keeps the last 5 entries on disk.

Thank you for your response. The issue here is the increment in `ID`. Shouldn't it be just 1 since the report is just for the one crate?

**Comment by ehuss** [comment]
Yea, if the report is identical to an existing one on-disk, it sounds reasonable to reuse an existing ID and avoid writing to the file. I think the code for that would likely go around [here](https://github.com/rust-lang/cargo/blob/23424fde2ed33850c749169056c6804b29f4675e/src/cargo/core/compiler/future_incompat.rs#L103-L119).
