### ISSUE TITLE
1.67 release broken on illumos when stdout is not a tty

### ISSUE THREAD

**Issue by davepacheco** [rust-lang/cargo#11629]
### Problem

After installing toolchain 1.67 on illumos, all cargo invocations with stdout not being a tty fail with:

```
$ cargo version > /dev/null
thread 'main' panicked at 'unexpected error from isatty: 0', /cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.3/src/backend/libc/termios/syscalls.rs:141:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It's fine if stdout is a tty:

```
$ cargo version
cargo 1.67.0 (8ecd4f20a 2023-01-10)
```

This is unfortunately a showstopper for us because stdout is not a tty in CI, so we can't use this toolchain in CI.

### Steps

On an illumos system:

1. `rustup toolchain update stable`
2. `cargo version` (to make sure you got 1.67)
3. `cargo version > /dev/null` (should reproduce the problem)

### Possible Solution(s)

We believe this is https://github.com/bytecodealliance/rustix/issues/467, which was introduced to Cargo by https://github.com/rust-lang/cargo/commit/48895b16812a745a7c89e684fdbae0527288b611.  This has been fixed upstream.

### Version

```text
$ cargo version --verbose
cargo 1.67.0 (8ecd4f20a 2023-01-10)
release: 1.67.0
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: x86_64-unknown-illumos
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: illumos helios-1.0.21408 [64-bit]
```

(thanks @jgallagher for having found this before, fixed it upstream, and identified it here)

**Comment by weihanglo** [comment]
Sorry for this bug affecting you. We could had included this fix https://github.com/rust-lang/rust/pull/105511 but unfortunately it got merged after 1.67 branched from master to beta. And the Cargo team wasn't aware of this situation 😞.

I don't really know about illumos, so don't know how to help. As always, if permitted, I would recommend every project runs tests on beta channel in CI pipelines.

**Comment by Brooooooklyn** [comment]
Same on FreeBSD: https://github.com/Brooooooklyn/Image/actions/runs/4032326915/jobs/6932135051

**Comment by weihanglo** [comment]
@Brooooooklyn Sorry for that. Could you provide more context? I don't really know how to interpret the job failure log.

**Comment by jgallagher** [comment]
The build step from the job failure shows the same panic message as above (although with a different errno):

```
Type Error: Could not parse the Cargo.toml: Error: Command failed: cargo metadata --format-version 1 --manifest-path "/Users/runner/work/Image/Image/packages/binding/Cargo.toml"
thread 'main' panicked at 'unexpected error from isatty: 45', /cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.3/src/backend/libc/termios/syscalls.rs:141:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at 'unexpected error from isatty: 45', /cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.3/src/backend/libc/termios/syscalls.rs:141:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by weihanglo** [comment]
BTW, could anyone check if the bug is fixed under the current beta?
(probably `cargo 1.68.0-beta.2 (0762e3bbd 2023-01-30)`)

**Comment by jgallagher** [comment]
It is fixed in the current beta (and was also fixed in the initial beta). On an illumos system:

```
john@helios1:~$ cargo -V
cargo 1.67.0 (8ecd4f20a 2023-01-10)
john@helios1:~$ cargo -V >/dev/null
thread 'main' panicked at 'unexpected error from isatty: 0', /cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.3/src/backend/libc/termios/syscalls.rs:141:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
john@helios1:~$ cargo +beta -V
cargo 1.68.0-beta.2 (0762e3bbd 2023-01-30)
john@helios1:~$ cargo +beta -V >/dev/null
john@helios1:~$
```

**Comment by weihanglo** [comment]
Thank you for testing the fix on beta! I am going to close this, and sorry for the inconvenience.
