### ISSUE TITLE
Cargo should not consider the build script as stale with every modification

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#1162]
When a package has a build script and you modify any file in your project, everything gets recompiled.

I'm currently working on a library named [glium](https://github.com/tomaka/glium) which is starting be have a moderate size and which uses build scripts only for code generation.

Modifying the code of an example or a test and running "cargo build" recompiles *everything*, which takes 3-4 minutes on my machine. Due to this, it's *very* annoying to write tests or examples.

## Suggestion

Build scripts should output `cargo:depends=/path/to/file` just like they output `rustc-flags`. Only modifications in the files which they depend upon, plus the build script itself and its modules, trigger a recompilation.

**Comment by alexcrichton** [comment]
This seems like a pretty great use of the metadata output to me, I like the idea!

I would add one caveat that if `cargo:depends` is *not* printed, then the behavior is the same as it is today. That means that if you go out of your way to print dependencies then you get better incremental times, but if you don't do anything we at least won't do anything wrong!

**Comment by tomaka** [comment]
What if a build script has *no* dependency? Should it print `cargo:depends=` with nothing behind, or should it print `cargo:no-deps`?

**Comment by alexcrichton** [comment]
I'd be down with either, but the latter seems like a better idea

**Comment by marcusklaas** [comment]
Is this something that could be done by someone with little knowledge of Cargo's internals? 

I'd like to work on this, but it would be nice to have a sense of the complexity involved first..

**Comment by alexcrichton** [comment]
@marcusklaas yeah I think this should be relatively easy. You'd want to [add parsing code](https://github.com/rust-lang/cargo/blob/e67c3c0601a266f6f4b64e29c1dbb3e88733ef54/src/cargo/ops/cargo_rustc/custom_build.rs#L285-L297) for this key being printed out first. Next you'd want to serialize it out to a custom location (probably something in the relevant fingerprint directory).

You'd then [update the build script fingerprint](https://github.com/rust-lang/cargo/blob/e67c3c0601a266f6f4b64e29c1dbb3e88733ef54/src/cargo/ops/cargo_rustc/fingerprint.rs#L241-L261) routine to take this file into account.

**Comment by marcusklaas** [comment]
Thanks for the pointers. I'll give it a shot!
