### ISSUE TITLE
Is gcc not included in the stable-x86_64-pc-windows-gnu?I remember it being included before

### ISSUE THREAD

**Issue by LJWxyz** [rust-lang/cargo#11626]
### Problem

I cause many build to fail with 

Caused by:
  process didn't exit successfully: `E:\Prog\Actdev\rust\proj\broot-main\target\release\build\onig_sys-1358b744f0089c77\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=RUSTONIG_DYNAMIC_LIBONIG
  cargo:rerun-if-env-changed=RUSTONIG_STATIC_LIBONIG
  cargo:rerun-if-env-changed=RUSTONIG_SYSTEM_LIBONIG
................................
  --- stderr

  error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/rust-lang/cc-rs#compile-time-requirements for help)

### Steps

1. git clone https://github.com/Canop/broot
2. cd inside
3. cargo build --release --target=x86_64-pc-windows-gnu
4. error

### Possible Solution(s)

Include it?
or 
is it possible to have a cached built cc-rs dynamically linked?

### Notes

i think its not really cargo's problem,but if its possible to add a flag to auto download cached lib or the relevant c requirements then would be helpful.

Maybe its out of scoop?any suggestions?

### Version

```text
release: 1.66.1
```

**Comment by ehuss** [comment]
gcc is included for linking only, it is not capable of compiling C code. You'll need to install something like MinGW to get a C compiler.

I'm going to close as I believe this is currently out of scope for Cargo. I believe there is interest in making the building/linking experience much easier (similar to something like Zig), but that is a massive project that doesn't have the resources behind it.
