### ISSUE TITLE
Cargo patch still requires access to private ssh repository

### ISSUE THREAD

**Issue by jonathanpwang** [rust-lang/cargo#11639]
### Problem

In my Cargo.toml I have
```
[dependencies]
foo = { git = "ssh://git@github.com/secret-repo" } 
```

Then in `.cargo/config.toml` I have
```
[patch."ssh://git@github.com/secret-repo"]
foo = { git = "ssh://git@github.com-bar/secret-repo" } 

[net]
git-fetch-with-cli = true
```

And my `.ssh/config` has an item
```
Host github.com-bar
  Hostname github.com
```

This should only apply `git fetch` on `github.com-bar`, however `cargo update` still errors and say `github.com/secret-repo` is not found because my SSH key only has access to `github.com-bar/secret-repo`.

This is especially relevant for git deploy keys. 

### Version

```text
cargo 1.69.0-nightly (3c5af6bed 2023-01-24)
release: 1.69.0-nightly
commit-hash: 3c5af6bed9a1a243a693e8e22ee2486bd5b82a6c
commit-date: 2023-01-24
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.79.1 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

**Comment by weihanglo** [comment]
From [ssh_config(5)](https://linux.die.net/man/5/ssh_config):

> **HostName**
> Specifies the real host name to log into. This can be used to specify nicknames or abbreviations for hosts. The default is the name given on the command line. Numeric IP addresses are also permitted (both on the command line and in HostName specifications). 

It means that if you try to `ssh github.com-bar`, you actually perform `ssh github.com`. That also implies your SSH key needs to have the permission to access `github.com`. `cargo update` under the hood performs `git fetch` when `net.git-fetch-with-cli` is enabled. It should behave identically.

If that doesn't answer your question, could you share the error message you actually encountered? Also, if remove the entire `[patch]` section and just write `foo = { git = "ssh://git@github.com-bar/secret-repo" }` in `[dependencies]`, are you able to reproduce? Thank you!

**Comment by ehuss** [comment]
@weihanglo I believe when using a `[patch]` for a git dependency, Cargo still needs to clone the original git dependency to determine what it actually points to.  Similar to if you patch a crates.io dependency, you still need to have the crates.io index downloaded.  I don't believe this is something that can be changed.  I think you'll need to use [source-replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html) instead.

**Comment by weihanglo** [comment]
Now I see what you mean. When `patch`ing a git dependency, you still need to clone the original repository to check the validity of the patch. I'd say it is not going to change in Cargo, unfortunately.

**Comment by jonathanpwang** [comment]
I didn't know about source-replacement, that's exactly what I need! Thank you! 
I'll close this issue now.

**Comment by jonathanpwang** [comment]
Sorry, just wanted to confirm: is the source-replacement supposed to get around this cloning original repository issue? 
I deleted the [patch] section from `.cargo/config.toml` and replaced it with
```
[source]
[source."ssh://git@github.com/secret-repo"]
git = "ssh://git@github.com-bar/secret-repo" } 

[net]
git-fetch-with-cli = true
```
but it still complains about access issues. I wasn't sure if this is the correct way to use source replacement.

**Comment by ehuss** [comment]
You have to define the original source and the replaced source separately. It would be something like:

```toml
[source.original-secret-repo]
git = "ssh://git@github.com/secret-repo"
replace-with = "other-secret-repo"

[source.other-secret-repo]
git = "ssh://git@github.com-bar/secret-repo"
```

**Comment by jonathanpwang** [comment]
Hm I tried this, but then it went back to the complaint about not having access to the original repo. Does the order of `git` and `replace-with` in the `[source.original-secret-repo]` entry matter?

**Comment by ehuss** [comment]
The order doesn't matter.   You have to make sure the URLs match exactly, though.
You do need a `Cargo.lock` file generated from the original repo.

**Comment by jonathanpwang** [comment]
Ah OK, the `Cargo.lock` file is the issue Cargo gave an error about. So I should clone a `Cargo.lock` file and then use source-replacement to do `cargo update`. 

Thanks, closing this again.
