### ISSUE TITLE
Allow passing CLI options in cargo aliases

### ISSUE THREAD

**Issue by Flippette** [rust-lang/cargo#11637]
### Problem

Suppose I have this alias:

```toml
[alias]
brr = "rustc --release -- -C target-cpu=native
```

```
❯ cargo brr
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing, e.g., `--lib` or `--bin NAME` to specify a single target
```

Yet `cargo rustc` requires a single target, so I tried this:

```
❯ cargo brr --bin inert
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing, e.g., `--lib` or `--bin NAME` to specify a single target
```

...which returns the same error message. How can I pass options to Cargo and not to `rustc`? (as in, before the `--`)

**Comment by weihanglo** [comment]
AFAIK, Cargo expands an alias and all arguments are appended to that expanded command. `cargo rustc` use [`trailing_var_arg`](https://docs.rs/clap/4.1/clap/builder/struct.Arg.html#method.trailing_var_arg) specifically, so yeah every argument you add is collected as var arg. It's unlikely to find a way to achieve that.

One potential approach is to introduce some kind of string interpolation, which may let you insert args into anywhere in your aliases. Nonetheless, it is really hard to have a behavior everybody satisfies. At this moment, I would recommend looking into workflows like [`cargo xtask`](https://github.com/matklad/cargo-xtask), [justfile](https://github.com/casey/just), or a plain old Makefile.

**Comment by weihanglo** [comment]
As a side note, who wants this to become a thing please bring your own design proposal. The Cargo team might not have the bandwidth to get this done as a main driver. Also, there are a plenty of obvious alternatives in the wild. Thank you.

**Comment by Flippette** [comment]
How have I never stumbled upon `cargo-xtask`?! Thank you for your suggestion!
