### ISSUE TITLE
Dependency in target-skipped crate still changes feature list used for compilation

### ISSUE THREAD

**Issue by ttiurani** [rust-lang/cargo#11653]
### Problem

A depencency inside a crate that is skipped for a target, e.g.:

```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fs-dep = { path = "../fs-dep" }
```

still adds to the features list of said dependency. This makes it impossible to build a project for many targets.

### Steps

Repository that replicates the problem for WASM compilation of tokio here:

https://github.com/ttiurani/cargo-target-dep-feature-wasm-bug

### Possible Solution(s)

I would expect that if a crate is skipped from compilation, then whatever is in its Cargo.toml would not affect the build.

### Version

```text
cargo 1.67.0 (8ecd4f20a 2023-01-10)
release: 1.67.0
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.79.1 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

**Comment by Eh2406** [comment]
You may want to try with [`resolver = "2"` or `edition = "2021"`](https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions). It fixes many instances of unexpected interactions with features and dependencies.

**Comment by ttiurani** [comment]
Thanks @Eh2406 ! Either one of those seems to fix the issue, and a change is also only needed in the "top" project, which makes life a lot easier.

Closing.
