### ISSUE TITLE
cargo vendor does not respect configured default registry

### ISSUE THREAD

**Issue by tones111** [rust-lang/cargo#11654]
### Problem

We're trying to set up [Artifactory Cargo support](https://www.jfrog.com/confluence/display/JFROG/Cargo+Package+Registry) at work and I noticed some strange behavior / inconsistency in how cargo handles the default registry.  This leads to users downloading crates directly from crates.io instead of the expected registry.

Artifactory has users set up their config.toml with this pattern

```
[registry]
default = "foo"

[registries.foo]
index = "https://foo.com/remote.git"

[net]
git-fetch-with-cli = true

[source.foo]
registry = "https://foo.com/remote.git"

[source.crates-io]
replace-with = "foo"
```

However, when trying to vendor dependencies Cargo appears to ignore the configured default registry and downloads the files from the crates-io registry.
```
$ cargo vendor
    Updating crates.io index
...
```

Attempting to build fails as expected (since the url is invalid)
```
$ cargo build
    Updating `foo` index
error: Unable to update registry `crates-io`
```

As does ```cargo search```
```
$ cargo search bindgen
    Updating `foo` index
error: failed to update registry `foo`
```

I have to modify the dependency in the project's Cargo.toml file to get the expected behavior.
```
[build-dependencies]
bindgen = { version = "0.63", registry = "foo" }
```
```
$ cargo vendor
    Updating `foo` index
error: failed to sync
```

### Possible Solution(s)

Cargo vendor should use the configured default registry.

### Version

```text
$ cargo --version -v
cargo 1.67.0 (8ecd4f20a 2023-01-10)
release: 1.67.0
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux [64-bit]
```
```

**Comment by ehuss** [comment]
I think this is unrelated to the `default` field. The `default` field is only for a few circumstances like `cargo publish` or `cargo search` (essentially any command with a `--registry` flag).

Have you tried the `--respect-source-config` flag? It is intentional that `cargo vendor` ignores the source configuration by default, since the source configuration is usually the vendored sources.

**Comment by tones111** [comment]
That flag seems to explain my confusion. TIL.

I'm still a little confused why that's the default behavior, but thank you for confirming it's operating as intended.  I just discovered ```cargo search``` today which seems like a much better test of our Artifactory config then the ```cargo vendor``` I'd been using previously.

Thanks for your insight!
