### ISSUE TITLE
crates always considered dirty when building in fresh git clone

### ISSUE THREAD

**Issue by alex** [rust-lang/cargo#11682]
### Problem

Consider a CI setup like the below:

1. `git clone` a repository
2. Maintain a cache of `target/`
3. `cargo build` it

Local crates will _always_ be considered dirty (and thus rebuilt), because `git clone` doesn't set `mtime` on files to when they were last modified, `mtime` is always the time of the commit.

For a repository that contains exclusively rust code in a single local crate, this doesn't matter too much -- presumably most of your commits dirty the crate anyways.

However, for repositories that are mixed Rust and other language, or contain multiple local crates, this results in a bunch of false dirties, and thus the slowing down of CI.

### Possible Solution(s)

Using a file's hash, instead of mtime, would resolve this. At the cost of computing hashes of all files being more expensive than just stating them.

### Notes

You can see a clear reproducer of this in https://github.com/pyca/cryptography/actions/runs/4097399094/jobs/7065746771 -- grep "dirty" in the "Create toxenv" step.

**Comment by Eh2406** [comment]
This is a duplicate of #6529.
It is more complicated than it first appears, if someone wants make a sustained (~6 months) effort to make it happen we would be open to the effort.

**Comment by alex** [comment]
thanks, closing as a dupe
