### ISSUE TITLE
Set the CARGO_BIN_NAME environment variable also when building (binary) examples

### ISSUE THREAD

**Issue by t-rapp** [rust-lang/cargo#11689]
### Problem

The CARGO_BIN_NAME environment variable is useful when building command-line programs (see #8251). It lets the command know its binary name for printing out simple usage instructions.

Currently CARGO_BIN_NAME is only set when building a `[[bin]]` target, though. In my projects a lot of the examples are wrappers around functions of a library crate to allow testing with custom data, similar to small command-line programs. In those example binaries CARGO_BIN_NAME is not available during compilation.

### Proposed Solution

It would be useful to also set the CARGO_BIN_NAME environment variable for (binary) examples.

**Comment by weihanglo** [comment]
I think it should be feasible to make it happen [here](https://github.com/rust-lang/cargo/blob/82c3bb79e3a19a5164e33819ef81bfc2c984bc56/src/cargo/core/compiler/compilation.rs#L375). 

```diff
 fn fill_rustc_tool_env(mut cmd: ProcessBuilder, unit: &Unit) -> ProcessBuilder {
-    if unit.target.is_bin() {
+    if unit.target.is_executable() {
```

**Comment by weihanglo** [comment]
Let's do a quick poll whether to accept this feature: “Set the `CARGO_BIN_NAME` environment variable also when building (binary) examples”. I don't have any concern so far. 

@rfcbot poll T-cargo "feature accept?"

**Comment by t-rapp** [comment]
@weihanglo: This was the line change that I stumbled over, too. From a quick check with a custom-built cargo it works. 
Do you intend to write a PR in case the feature gets accepted? Otherwise I can do it.

**Comment by JRAndreassen** [comment]
Hi...

I have an issue that is related to this..

I need to know when the build target is a bin.
Scenario:
I have several sub-projects with their own build script.
   + app
       + -build.rs
   + libs
       + lib1
           + build.rs
       + lib2
           + build.rs
One of the build steps is generating a resource file(crate winres).
When app gets built, the build scripts for lib1 & lib2 runs and creates resource files.
Which creates duplicates and link fails.

So, I need to find a way to determine if the build is a lib/rlib/exe so I can do something like :
```rust
#[cfg(windows)]
pub fn build_resource () {

   #[cfg(bin)]
    if Ok("release".to_owned()) == std::env::var("PROFILE")  {
        let mut res = winres::WindowsResource::new();
        res.set_icon("../libs/myicon.ico")
            ;
        if let Err(e) = res.compile() {
            eprintln!("{}", e);
            std::process::exit(1);
        } 
    }
}
```

Or is that possible some other way ?

Thanks
JR

**Comment by weihanglo** [comment]
Hi @JRAndreassen. This feels like a separate issue to me, and probably more like a user issue. I don't clearly understand the problem, but you may want to move resource generation to `build.rs` of `app`. Unfortunately we are not able to support you here. I'd suggest you try one of the user forums such as <https://users.rust-lang.org/> to see if someone can help.

Alternatively, you can also create a new issue explaining the expectation with a reproducer and possible solutions and workarounds. Thank you.

**Comment by weihanglo** [comment]
@t-rapp, since the majority of the Cargo team voted for accepting this, we can move forward implementing this. Thank you!

**Comment by alshdavid** [comment]
I would also like to have a `CARGO_CYDLIB_NAME` and `TARGET_DIR` at build time and integration test time. This will help me consume dynamic libraries in integration tests and rename the files as needed (in the case of Nodejs, from `{prefix}libname.{ext}` to `libname.node`.

**Comment by epage** [comment]
For target-dir, see #9661

**Comment by epage** [comment]
Hadn't noticed this is a closed issue. If there isn't an open issue for that need, I'd recommend creating one
