### ISSUE TITLE
Using assets in a crate

### ISSUE THREAD

**Issue by Inspirateur** [rust-lang/cargo#11683]
### Problem

I'm writing a crate for crates.io that needs to use assets and none of these solutions satisfy me:
- embed them in the binary -> too heavy
- have the user provide them to my crate -> I don't want the user to bother with that
- have my crate download them at runtime -> too slow

That seemed like a simple need but after hours of searching I still couldn't find anything except this post https://stackoverflow.com/questions/74606543/ship-tera-templates-in-a-crate-without-embedding-them-into-the-binary
with 0 replies.

### Proposed Solution

If there is any way to achieve that it would be nice to have it clearly documented somewhere (I couldn't find anything about it in the cargo book either). If there is not, it would be great to add a way for my crate to use its own assets, or explain somewhere why this is not possible/desirable.

**Comment by arlosi** [comment]
You can include files in the crate package - see the [`include` manifest key](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) for details on what's included by default. Then access the path to the files relative to the [`CARGO_MANIFEST_DIR` environment variable ](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates).
```rust
let path_to_crate= env!("CARGO_MANIFEST_DIR");
```

Note that crates.io has a 10MB limit on the `.crate` file.

**Comment by Inspirateur** [comment]
Thank you ! that's exactly what I needed ❤

**Comment by epage** [comment]
Note that that doesn't help with `cargo install`.  Asset handling for `cargo install` is being tracked in #2729.

**Comment by Inspirateur** [comment]
> You can include files in the crate package - see the [`include` manifest key](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) for details on what's included by default. 

If i understand the doc correctly, an assets/ folder at the root of the crate that is not in the gitignore would be included by default ?

**Comment by weihanglo** [comment]
> If i understand the doc correctly, an assets/ folder at the root of the crate that is not in the gitignore would be included by default ?

I believe so. You can also use `cargo package --list` to verify what will be included in the `.crate` tarball.

**Comment by schneems** [comment]
This is great, thanks! Did you verify if this technique works? I think we can close the issue if so.

**Comment by Inspirateur** [comment]
Yes ! I made this crate using this technique that was perfect for my needs https://github.com/Inspirateur/twemoji-rs
