### ISSUE TITLE
--quiet flag prints info logs

### ISSUE THREAD

**Issue by Integralist** [rust-lang/cargo#11691]
### Problem

I'm programmatically parsing the output of `cargo locate-project --quiet` but finding that 'info' logs are being printed to stderr when I would expect them to not be shown.

### Steps

1. `rustup toolchain uninstall stable-aarch64-apple-darwin`
2. `cargo locate-project --quiet`

### Possible Solution(s)

Redirecting stderr is a workaround I'm using:

```
cargo locate-project 2>/dev/null
```

But ideally the `--quiet` flag would do as it describes and not display 'info' logs.

### Version

```text
cargo 1.67.0 (8ecd4f20a 2023-01-10)
release: 1.67.0
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.84.0 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 13.0.1 [64-bit]
```

**Comment by weihanglo** [comment]
What kind of 'info' log did you see? It would be great if you can provide some log output. 

Also, could you check the value of the environment variable [`CARGO_LOG`]? Setting `CARGO_LOG`  will turn on debug logging regardless of `--quiet` being set.

[`CARGO_LOG`]: https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html?highlight=CARGO_LOG#environment-variables-cargo-reads

**Comment by Integralist** [comment]
Hi @weihanglo 

So the `CARGO_LOG` environment variable is not set, and the output I'm seeing is as follows...

```
$ cargo locate-project --quiet
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2023-01-26, rust version 1.67.0 (fc594f156 2023-01-24)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
{"root":"/Users/integralist/Code/test-projects/testing-fastly-cli/Cargo.toml"}
```

**Comment by Integralist** [comment]
**NOTE:** I even tried `--offline`, thinking that it wouldn't attempt to sync and download but that didn't work either (albeit that flag has a different purpose than `--quiet` but I was just trying things out).

**Comment by weihanglo** [comment]
If you install Rust via rustup, `cargo` command is very likely a proxy provided by rustup. I believe the implicit download behavior is from rustup. See <https://github.com/rust-lang/rustup/issues/1397>. People interested in this issue could discuss over there. 

Thank you for the report anyway!
