### ISSUE TITLE
add a one line comment for LTO

### ISSUE THREAD

**Issue by Ethan-000** [rust-lang/cargo#11697]
### Problem

hey,

I'm wondering if its okay to add a one line comment explaining what `LTO` stands for.
something like

```
/// LTO: Link Time Optimizations
```

It is not obvious to a newbie like me and I have to search for what it means. If it is very obvious to most I guess it should be fine to not add it.

### Proposed Solution

add

```
/// LTO: Link Time Optimizations
```

in `lto.rs`

**Comment by weihanglo** [comment]
Also, we could link LTO to this <https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#lto>
