### ISSUE TITLE
Cargo hits OOM when building many examples

### ISSUE THREAD

**Issue by argentsileo** [rust-lang/cargo#11707]
### Problem

When building examples on a large project with many of them, Cargo quickly runs through all available memory.

### Steps

1. Clone a repository with many examples (e.g. [Bevy](https://github.com/bevyengine/bevy) with 142 examples)
2. Run `cargo build --examples`

### Possible Solution(s)

It should be possible for Cargo to identify jobs that will consume high amounts of memory and ensure that other high-memory jobs don't occur at the same time.

### Version

```text
cargo 1.67.0 (8ecd4f20a 2023-01-10)
release: 1.67.0
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by weihanglo** [comment]
Is that propositional to the number of examples? How large is the RAM of your machine? 
I'd say that it's a bit hard for Cargo to predict memory usage beforehand. Profile data could be persisted but Cargo currently doesn't have such a persistence mechanism.

It would be helpful if you can share memory profiling data here. There are several tools out there such as [heaptrack](https://invent.kde.org/sdk/heaptrack). Here is also [a list of profiling tools](https://nnethercote.github.io/perf-book/profiling.html).

**Comment by ThomasWaldmann** [comment]
Maybe related (not with examples, but a real project): https://github.com/pyca/cryptography/issues/8640

**Comment by silvergasp** [comment]
I've run into a similar issue with building surrealdb [on github actions](https://github.com/google/oss-fuzz/actions/runs/4811955499/jobs/8566597852#step:8:575). Where it builds perfectly fine on my local machine. Without some detailed heap profiling I eyeballed the memory usage of the docker-container I was using to build on my local machine and it was peaking at about 6.7GB when compiling the surrealdb package.

**Comment by epage** [comment]
Closing in favor of #12912 so we keep the conversation in one place.
