### ISSUE TITLE
add `--ignore-rust-version` for `cargo install`

### ISSUE THREAD

**Issue by ensc** [rust-lang/cargo#11718]
### Problem

Subcommands like `build` allow to ignore the minimum rust version of dependencies by the `--ignore-rust-version` flag.

Because `build` is a step of `cargo install`, this flag should be available there too.

### Proposed Solution

```diff
Index: cargo/src/bin/cargo/commands/install.rs
===================================================================
--- cargo.orig/src/bin/cargo/commands/install.rs
+++ cargo/src/bin/cargo/commands/install.rs
@@ -78,6 +78,7 @@ pub fn cli() -> App {
                 .conflicts_with_all(&["git", "path", "index"]),
         )
         .arg_message_format()
+        .arg_ignore_rust_version()
         .arg_timings()
         .after_help("Run `cargo help install` for more detailed information.\n")
```

**Comment by weihanglo** [comment]
This seems good to have to me.

BTW, Could you provide some crates that fail to compile due to their `rust-version` being set?

**Comment by weihanglo** [comment]
The Cargo team talked about this in today's triage meeting. This is likely just an oversight and wasn't intended to not add it. That is to say, we are open to a pull request for adding this flag for `cargo install`.

Note that this flag is designed for low-level or exceptional circumstances. It is not something expected people use regularly.
