### ISSUE TITLE
Missing docs for `cargo schema`

### ISSUE THREAD

**Issue by amab8901** [rust-lang/cargo#11721]
### Problem

Write `cargo schema` in CLI. Now try to find info in the Cargo Book (or elsewhere on the internet) to explain what just happened. Nothing available. 

### Possible Solution(s)

Add documentation for `cargo schema` to Cargo Book

**Comment by weihanglo** [comment]
`cargo schema` is not a built-in command in Cargo. Where did you install it?

Perhaps it is a third-party subcommand and you may check their documentation.

**Comment by amab8901** [comment]
I found that `cargo schema` is a customized alias defined in `.cargo/config`
