### ISSUE TITLE
`Unsupported protocol` with sparse registry

### ISSUE THREAD

**Issue by bebecue** [rust-lang/cargo#11726]
### Problem

When using sparse registry, cargo reports `Unsupported protocol` error.

HTTP multiplexing defaults to true at https://github.com/rust-lang/cargo/blob/39c13e67a5962466cc7253d41bc1099bbcb224c3/src/cargo/sources/registry/http_remote.rs#L223-L225 and this error is produced at https://github.com/rust-lang/cargo/blob/39c13e67a5962466cc7253d41bc1099bbcb224c3/src/cargo/sources/registry/http_remote.rs#L555-L556
cargo is dynamic linked to `libcurl`, however `libcurl` from Apple in macOS 10.12.6 has no `HTTP2`:flushed:

### Steps

```
$ env CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse rustup run nightly cargo install oris
    Updating crates.io index
error: failed to query replaced source registry `crates-io`

Caused by:
  [1] Unsupported protocol
```

### Possible Solution(s)

- fallback to `HTTP/1.1`
- replace the ambiguous error message
  - maybe add suggestion: set `CARGO_HTTP_MULTIPLEXING` to `false` if `libcurl` doesn't support `HTTP/2`
- static link to `libcurl`

### Version

```text
$ rustup run nightly cargo version --verbose
cargo 1.69.0-nightly (39c13e67a 2023-02-12)
release: 1.69.0-nightly
commit-hash: 39c13e67a5962466cc7253d41bc1099bbcb224c3
commit-date: 2023-02-12
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.54.0 (sys:0.4.59+curl-7.86.0 system ssl:SecureTransport)
os: Mac OS 10.12.6 [64-bit]

$ otool -L (rustup which --toolchain nightly cargo)
/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo:
    /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
    /System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60158.100.133)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
    /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

$ /usr/bin/curl-config --version
libcurl 7.54.0

$ /usr/bin/curl-config --feature 
SSL
IPv6
UnixSockets
libz
AsynchDNS
GSS-API
SPNEGO
Kerberos
NTLM
NTLM_WB
```

**Comment by weihanglo** [comment]
Thank you for the report. We just found that as well during [a recent PR review](https://github.com/rust-lang/cargo/pull/11448#discussion_r1108996353). Personally I'd like to backport a fix to beta channel, copying what this does:

https://github.com/rust-lang/cargo/blob/a66f1233f9ad61e91cc8fd86f0b6bd15e66443a8/src/cargo/core/package.rs#L738-L754

**Comment by Eh2406** [comment]
+1 for a backport.

**Comment by bebecue** [comment]
Thanks for the pointer, I realized this is [5 years old](https://github.com/rust-lang/cargo/commit/38fd476a1287050a010d6d19343854cf5f515fb0) problem and can be fixed quickly.

As someone haven't done any backport before, I found a guide at [Backporting](https://forge.rust-lang.org/release/backporting.html#backporting). I think it needs 3 PRs in total.

1. a PR to `rust-lang/cargo/master` to fix it like the [previous one](https://github.com/rust-lang/cargo/blob/a66f1233f9ad61e91cc8fd86f0b6bd15e66443a8/src/cargo/core/package.rs#L738-L754)
1. a PR prefixed with `[beta]` that __cherry picks__ the above commit from `rust-lang/cargo/master` to `rust-lang/cargo/rust-1.68.0)`
1. another PR prefixed with `[beta]` to `rust-lang/rust/rust-1.68.0` that updates the Cargo submodule to `rust-lang/cargo/rust-1.68.0)`

Is that right?

**Comment by weihanglo** [comment]
@bebecue, that's pretty much correct! 

I might also try to reuse that code snippet if feasible, though it's also fine just copying over at this moment.

**Comment by weihanglo** [comment]
Rust toolchain `v1.68.0-beta.6` should include the fix (https://github.com/rust-lang/rust/pull/108508). Closing and thanks for the help!
