### ISSUE TITLE
flag for `cargo add` to add platform specific dependencies

### ISSUE THREAD

**Issue by akabinds** [rust-lang/cargo#11720]
### Problem

Currently, there is no support for adding platform specific dependencies (such as `[target.'cfg(windows)'.dependencies]`) using `cargo add`.

### Proposed Solution

Add a `--cfg` option that allows the user to specify the whole desired `cfg` predicate.

*Examples*:
- `cargo add windows --cfg windows`
- `cargo add raw_cpuid --cfg any(target_arch = "x86", target_arch = "x86_64")`

### Notes

- Currently, since `cfg` dependency specifications only are supported using platform predicates, one might think that the option should be named differently. But, in case other `cfg` pairs/options become supported in the future, the name of the flag allows for it to also include those without confusion for its name being named after the fact it specifies platform specific dependencies only.

**Comment by epage** [comment]
@akabinds FYI this has not been marked as Accepted and there are likely things still left to resolve, like what the flag should be called.  Starting on this now might lead to extra churn during review as we settle those kind of questions.

**Comment by akabinds** [comment]
> @akabinds FYI this has not been marked as Accepted and there are likely things still left to resolve, like what the flag should be called. Starting on this now might lead to extra churn during review as we settle those kind of questions.

I understand. I just wanted to claim it because I want to implement it if it is accepted. But, I had a quick question. I was looking around the code base for relevant code to help implement this. I found that this feature seems to already have tests in the test suite using the existing `--target` flag:

https://github.com/rust-lang/cargo/blob/a66f1233f9ad61e91cc8fd86f0b6bd15e66443a8/tests/testsuite/cargo_add/target_cfg/mod.rs#L8-L25

But, when attempting to add platform-specific dependencies this way in my own project to test, it seems to not work. Has this been implemented already, but not present in a release?

**Comment by epage** [comment]
Huh, I thought we had this; I should have checked rather than assuming the issue author hadn't missed it.

> But, when attempting to add platform-specific dependencies this way in my own project to test, it seems to not work. Has this been implemented already, but not present in a release?

Could you provide more details as to what didn't work?

**Comment by akabinds** [comment]
> Could you provide more details as to what didn't work?

My shell was giving me an error after running it. It seems like all I had to do was wrap the `cfg` predicate in quotations and it worked fine. But, I ran this to test:
```
> cargo add --target cfg(windows) serde
zsh: unknown file attribute: i
```

If I did `--target 'cfg(windows)'`, it worked fine.

I'm not sure if this fix is needed on other shells.

**Comment by weihanglo** [comment]
I believe different shells have different ways to escape things. If that works for you, seems like this issue is not really an issue as cargo-add already supports that?

**Comment by akabinds** [comment]
> I believe different shells have different ways to escape things. If that works for you, seems like this issue is not really an issue as cargo-add already supports that?

Indeed. But should it not be at least documented that quotations might be needed based on the shell?

**Comment by epage** [comment]
That gets into an interesting line of how much do we document how to use each users system vs users knowing it being an expectation in using cargo.
