### ISSUE TITLE
"cargo +nightly rustc -Z polymorphize" fails

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/cargo#11734]
### Problem

```
$ cargo +nightly rustc -Zpolymorphize
error: unknown `-Z` flag specified: polymorphize
```
This fails even `with rust-toolchain.toml` containing
```toml
[toolchain]
channel = "nightly"
```

Running `cargo override set nightly` and then `cargo rustc -Zpolymorphize` does not work.

Adding `.cargo/config.toml` with
```toml
[build]
rustflags = "-Z polymorphize"
```
works fine.

Spelling it as "polymorphise" instead does not change anything :smiley:.

This is a valid (and useful) nightly `rustc` flag, but `cargo` seems to struggle with it. Hopefully not just some dumb error on my part.

### Version

```text
cargo 1.65.0-nightly (646e9a0b9 2022-09-02)
release: 1.65.0-nightly
commit-hash: 646e9a0b9ea8354cc409d05f10e8dc752c5de78e
commit-date: 2022-09-02
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Debian n/a (bookworm) [64-bit]
```

**Comment by ehuss** [comment]
rustc options starting with a `-` need to be passed after the `--` to differentiate them from the ones for cargo. 

That is, something like: `cargo +nightly rustc -- -Zpolymorphize`

**Comment by BartMassey** [comment]
Ah. My bad. Thanks and apologies!
