### ISSUE TITLE
Feature: import individual files

### ISSUE THREAD

**Issue by angeldollface** [rust-lang/cargo#11731]
### Problem

This isn't a problem as such. It is a thought I had. I've been playing around with Deno a bit and I do think that importing modules from a remote URL isn't only pretty efficient but also much easier than speicifying a whole bunch of dependencies. This would probably also improve build times by a whole lot. Rust is hypersonic in production, let's make it hypersonic in development.

### Proposed Solution

Here's my idea: Say you'd like one specific function from one specific module but you don't want to import a whole module and compile the whole module just to access that one function. Instead you just do this:

```Rust
mod "https://raw.githubusercontent.com/angeldollface/chico/main/src/modules/binary.rs"

use binary::bin_to_dec;
```
Just that one file is compiled and any other files it depends on.
Cargo would cache the file somewhere and you could fall back on it if you want to use the same function in another project.

### Notes

I would work on this as a plugin. However, I need to understand how Cargo fetches and compiles dependencies.

**Comment by epage** [comment]
I think this is more of a language proposal that might be backed up by changes in cargo, than a cargo feature.

Generally, the path forward for something like this is to consider
- Why the current system works the way it does
  - For example, a major feature of the current design is the be "leftpad safe".  By directly referencing a dependency, how do we keep that?  I believe deno's approach is to not be prescriptive about this but to still offer a hosting service
- What problems the proposed idea may have
  - For example, very few projects are structured to allow referencing a single module within it.  Some people have talked about ["subcrates"](https://poignardazur.github.io/2023/01/24/subcrates/) as a concept that strictly enforces boundaries, allowing more parallel compilation and would work as a target for this.
- How to resolve those problems

Then post a "Pre-[RFC](https://github.com/rust-lang/rfcs/blob/master/0000-template.md)" on [internals](https://internals.rust-lang.org/).  The RFC format helps in making sure different points are considered and help you communicate them out.

**Comment by angeldollface** [comment]
Hi Ed! @epage You might remember me, but under a different name. When we talked last I was called "iamtheblackunicorn" and I asked you about a static-site generator I had written, called Acid. I rewrote the static-site generator with massive improvements in features and code quality and it is now called Mandy. You can find that project [here](https://github.com/angeldollface/mandy). Mandy still uses the same knowledeg that you so helpfully gave me plus the `file-serve` crate. I never thanked you enough. She's quite over-powered, would love to hear/read what you think. You could also drop by the Discord if you like.

I'm sorry for the late reply but I was really busy with university. I still am but I've kept you waiting long enough. About my suggestion:

- What is "leftpad safe"? Never heard of this. :see_no_evil:
- Ad potential problems: The plugin could possibly only fetch and compile the modules that are required?

Hyped to hear your thoughts! :heart:

**Comment by weihanglo** [comment]
I believe Ed was talking about the leftpad incident [^1] in npm ecosystem. IIRC the author of widely used package `leftpad` yanked their `leftpad` from npm registry, making lots of package depending on that failed to build.

The Rust community also has a centralized registry crates.io. However, a yanked package can continue compiling if you have a `Cargo.lock` containing that package. Without the proposed URL referenced module, it might fall into the same situation if someone removed their package from that URL.

[^1]: https://www.theregister.com/2016/03/23/npm_left_pad_chaos/

**Comment by weihanglo** [comment]
> this is more of a language proposal that might be backed up by changes in cargo, than a cargo feature.

Unfortuately Cargo knows nothing about Rust module systems and source code. This is why Ed suggests seeking opinions from outside Cargo project frist. The feature might start from a language change, requiring [the language team](https://www.rust-lang.org/governance/teams/lang)'s involvement a lot I believe.

**Comment by angeldollface** [comment]
So doing this as plugin or macro wouldn't work?

**Comment by weihanglo** [comment]
It might work but is out of the scope that Cargo currently handles. Cargo is a build system for Rust not a Rust compiler. Changing the meaning of `mod` should start a talk with the lang team. Cargo won't parse `.rs` files by itself in the near future.

That being said, there is a semi-related unstable feature `-Zscript` <https://github.com/rust-lang/cargo/issues/12207>. It indeed parses some source code like doc comments.

**Comment by angeldollface** [comment]
Hmm, I'll work on this some time soon.
