### ISSUE TITLE
`--all-targets` is missing documentation

### ISSUE THREAD

**Issue by amab8901** [rust-lang/cargo#11732]
### Problem

example CLI command:
`cargo clippy --all-targets` 

`--all-targets` is missing documentation. Please add documentation for it.

**Comment by amab8901** [comment]
> Thank you for reporting this. The issue is a consequence that cargo-clippy is not actually a built-in command; they live in [rust-lang/rust-clippy](https://github.com/rust-lang/rust-clippy) repository.
> 
> You're correct. The help text fails to mention `--all-target`, but it tells that other options [are available the same as `cargo check`](https://github.com/rust-lang/rust-clippy/blob/6444621/src/main.rs#L21), which indeed contains that option. It's not that obvious though. If anyone wants to improve that, I guess we can start from that repository first.

even if `cargo` mentions it in the list, it doesn't offer any explanation to what the option actually does. I had to ask ChatGPT to get the context of what the difference is between using the option and not:
- without it, the CLI command will be applied only to either library or to binary
- with it, the CLI command will be applied to library, and binary, and tests -- all of them simultaneously.

But idk, that's what I got from ChatGPT. Maybe that's not entirely correct.

**Comment by weihanglo** [comment]
Sorry I didn't really follow know. Which documentation are you reading? There is a nice section [Target Selection](https://doc.rust-lang.org/cargo/commands/cargo-check.html#target-selection)  explaining each options, and `--all-targets` is at the bottom of that. You can also access this manual by running `cago help check`.

Besides the indirection from cargo-clippy to cargo-check, do you have other ideas to improve the documentation?

**Comment by amab8901** [comment]
> Besides the indirection from cargo-clippy to cargo-check, do you have other ideas to improve the documentation?

Oh, I couldn't find it previously. Now I see it, thanks :+1:  I think solving the indirection will be good for now. If there's anything else, then it can probably be discovered in the future

**Comment by weihanglo** [comment]
Hey. I am going to close this in order to reduce the already too long issue backlog. For the discovery enhancement, one can either file an issue against `rust-lang/rust-clippy` to fix it, or file a new issue with a clear alternative solution to `rust-lang/cargo`. Otherwise, the discovery is probably a wontfix in the near feature, as it generally needs to starts from clippy side. Thank you!
