### ISSUE TITLE
Unnecessary downloads of same dependencies

### ISSUE THREAD

**Issue by SparkySimp** [rust-lang/cargo#11739]
### Problem

When we check [crates.io](https://crates.io), we can see that several packages depend on the same crate. (e.g. [syn](https://crates.io/crates/syn)) Every time cargo builds a project dependent on this crate's same version, it downloads the crate again. This makes the build time annoyingly long.

### Proposed Solution

Cargo can download dependencies to a single directory, and hard link them to the .cargo/bin (I forgot the exact name) of the project directories, or simply link the project with pre-built crates.

**Comment by weihanglo** [comment]
Thanks for reporting this. Could you say more on the download part, like Why you thought it re-downloads, or how you configured your environment for Rust?

Generally Cargo stores downloaded `.crates` file under [`$CARGO/registry/cache`](https://doc.rust-lang.org/nightly/cargo/guide/cargo-home.html#directories). It should just work. If you home directory or `CARGO_HOME` environment variable varies for each build. It might cause this issue.

If possible, could you provide the version of cargo suffering from this (via `cargo -vV`), and also a reproducible example? That would be a great help for the investigation. Thanks!

**Comment by weihanglo** [comment]
I'm going to close due to inactivity. Please open a new issue with a minimal, complete reproduction if it still happens.
