### ISSUE TITLE
Success message containing link to crates.io after `cargo publish`

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/cargo#11768]
### Problem

The output of `cargo publish` could be a little bit more helpful.

A lot of people want to check that their crate was published successfully after running `cargo publish`. It would be really handy if after a successful publishing process, Cargo printed the URL for checking your crate.

### Proposed Solution

Maybe something like:

```
$ cargo publish
    [...]
    Updating crates.io index

Your crate was successfully published to crates.io! Check it at https://crates.io/crates/<CRATE>.

$
```
<sub>(Where `<CRATE>` gets replaced with the published crate)</sub>

### Notes

This takes advantage of the URL recognition that some terminal emulators have, and it's a nice touch for first-time publishers.

**Comment by hi-rustin** [comment]
We might need to consider other registries. Because Cargo also supports publishing to different registries.

**Comment by blyxyas** [comment]
Guess I'll just do it myself
@rustbot claim
