### ISSUE TITLE
Cargo failed to install and produce incorrect bug log

### ISSUE THREAD

**Issue by Its-Just-Nans** [rust-lang/cargo#11776]
### Problem

I wanted to install dust on a Debian

I installed cargo

```
apt install cargo
```
> `cargo --version` : cargo 1.46.0

I installed dust

```
cargo install du-dust
```
> produce an error

```
error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/du-dust-0.8.4/Cargo.toml`
Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`
```

So I changed the config key

```toml
[profile.release]
lto = true
codegen-units = 1
strip = "debuginfo"
```

I tried to re-install and got the error

```
error: failed to download `du-dust v0.8.4`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/du-dust-0.8.4/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

**My question is why cargo didn't check for the "edition" key before checking others keys ?**

Thanks

### Version

```text
cargo 1.46.0
release: 1.46.0
```

**Comment by weihanglo** [comment]
> …why cargo didn't check for the "edition" key before checking others keys?

The first error “failed to parse manifest at” [occurred during serde deserialization](https://github.com/rust-lang/cargo/blob/f3de2de2c83d5b8b760ca5488890fb4370124e3c/src/cargo/util/toml/mod.rs#L59-L61), so it definitively happend before the second one. The `edition` field need the entire manifest to get parsed first, and then has a special treatment [here](https://github.com/rust-lang/cargo/blob/f3de2de2c83d5b8b760ca5488890fb4370124e3c/src/cargo/util/toml/targets.rs#L822-L828)
(I didn't look into 1.46.0 but the cause should be similar I believe).
