### ISSUE TITLE
bindep std errors when no_std bindep has a dependency which uses std in a build.rs

### ISSUE THREAD

**Issue by devsnek** [rust-lang/cargo#11772]
### Problem

When a project contains a bindep, and that bindep is `no_std`, and that bindep has a dependency on a package which has a build.rs, *sometimes* this causes the entire build to freak out and fail:
```
$ cargo build
   Compiling phf_shared v0.11.1
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-none` target may not support the standard library
  = note: `std` is required by `phf_shared` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `std`
 --> /home/snek/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_shared-0.11.1/src/lib.rs:9:1
  |
9 | extern crate std as core;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
  |
  = note: the `x86_64-unknown-none` target may not support the standard library
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error: cannot find macro `write` in this scope
   --> /home/snek/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_shared-0.11.1/src/lib.rs:368:5
    |
368 |     write!(f, "{:?}", array)
    |     ^^^^^
    |
    = help: consider importing this macro:
            core::write
[...]
```

I don't know which things cause this and which don't (I've run into several at this point), but my repro repo, which depends on the crate `pci-ids`, fails consistently:  https://github.com/devsnek/bindep-repro

If I cd into the bindep directory and run `cargo build`, it compiles just fine. This only happens when compiling the project which has the bindep as a dependency.

### Steps

1. Create a project
2. Create a bindep in that project
3. Add a dependency to that bindep
4. If you are (un)lucky, it will fail to build.

### Version

```text
cargo 1.69.0-nightly (9d5b32f50 2023-02-22)
release: 1.69.0-nightly
commit-hash: 9d5b32f503fc099c4064298465add14d4bce11e6
commit-date: 2023-02-22
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by Momijiichigo** [comment]
I have a similar problem with [my project](https://github.com/Momijiichigo/my-os/tree/cb1373ae72b3ec70a4fcd054e7c90ae6a29ffb19).

### Project structure
In this project, there is a workspace member `kernel` which is a `no_std` bindep artifact, and targets `x86_64-unknown-none` which is different from the workspace root target.

`kernel` has a dependency `bootloader-boot-config` that imports `serde` while disabling std:
```toml
[dependencies]
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
```
[above line on github](https://github.com/rust-osdev/bootloader/blob/7c8e2ca63449f92cd1f7494b9cdc9fcf58b7375d/common/config/Cargo.toml#L10C1-L10C81)

When I move out the `kernel` folder and compile it as a separate single project (not as a bindep workspace member), it compiled successfully.

### Error

The compiler throws error while compiling `kernel`, saying a dependency `serde` uses std while `kernel` is no_std: 
```
> cargo run
   Compiling serde v1.0.188
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-none` target may not support the standard library
  = note: `std` is required by `serde` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `std`
   --> /home/daichi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.188/src/lib.rs:166:17
    |
166 |         pub use std::*;
    |                 ^^^ can't find crate
```

### Steps

1. Clone this repo of this version: https://github.com/Momijiichigo/my-os/tree/cb1373ae72b3ec70a4fcd054e7c90ae6a29ffb19
2. `cargo build`

### Cause 

Other workspace members import `serde` with std feature on, which might be the cause.

<details><summary>cargo tree:</summary>
<p>

```
my-os v0.1.0 (/home/daichi/workspace/my-os)
└── ovmf-prebuilt v0.1.0-alpha.1
[build-dependencies]
├── bootloader v0.11.4
│   ├── anyhow v1.0.75
│   ├── bootloader-boot-config v0.11.4
│   │   └── serde v1.0.188
│   │       └── serde_derive v1.0.188 (proc-macro)
│   │           ├── proc-macro2 v1.0.66
│   │           │   └── unicode-ident v1.0.11
│   │           ├── quote v1.0.33
│   │           │   └── proc-macro2 v1.0.66 (*)
│   │           └── syn v2.0.31
│   │               ├── proc-macro2 v1.0.66 (*)
│   │               ├── quote v1.0.33 (*)
│   │               └── unicode-ident v1.0.11
│   ├──  ...
│   ├── mbrman v0.5.2
│   │   ├── bincode v1.3.3
│   │   │   └── serde v1.0.188 (*)
│   │   ├── ...
│   │   ├── serde v1.0.188 (*)                                <- imports serde with std on 
│   │   ├── serde-big-array v0.4.1
│   │  ...  └── serde v1.0.188 (*)
│   └──...
└── kernel v0.1.0 (/home/daichi/workspace/my-os/kernel)
    ├── bootloader-x86_64-common v0.11.4                       <- remove this dependency & error gone
    │   ├── bootloader-boot-config v0.11.4 (*)                  <- imports serde with no_std
    │   ├── bootloader_api v0.11.4
    └──...
```


</p>
</details>

**Comment by Momijiichigo** [comment]
Update on my issue:
> I have a similar problem with my project.

I was able to resolve the issue by adding `package.resolver = "2"` in the Cargo.toml of the workspace

**Comment by devsnek** [comment]
I forgot to update this but yeah, setting `resolver = "2"` in the workspace, rather than the individual packages, fixes this issue.
