### ISSUE TITLE
Error is not providing any relevant info pertaining to the issue 

### ISSUE THREAD

**Issue by rhmcruiser** [rust-lang/cargo#11787]
### Problem

Error message during cargo build: 

```console
guessing_game$ cargo build
   Compiling guessing_game v0.1.0 (/home/ronald/learning-rust/guessing_game)
error: expected one of `.`, `;`, `?`, `else`, or an operator, found `{`
  --> src/main.rs:17:43
   |
17 |     let guess: u32 = guess.trim().parse() {
   |                                           ^ expected one of `.`, `;`, `?`, `else`, or an operator         <<  Error 

warning: unused import: `std::cmp::Ordering`
 --> src/main.rs:2:5
  |
2 | use std::cmp::Ordering;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `guessing_game` (bin "guessing_game") generated 1 warning
error: could not compile `guessing_game` due to previous error; 1 warning emitted             <<<< 
guessing_game$ 
```

### Steps

Environment: 
Linux Ubuntu 22.04 
Kernel -  5.15.0-60-generic

```console
$ rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

1 . Create a new project and add the below as the src/main.rs  file

```console
$ cargo new guessing_game
```
```rust
use rand::Rng;
use std::cmp::Ordering;
use std::io;

fn main() {
    println!(" Guess the number !");
    
    let secret_number  = rand::thread_rng().gen_range(1..=100);
    println!(" The secret number is : {secret_number}");

   loop {
    println!("Please input your guess ");
    let mut guess = String::new();
    io::stdin().read_line(&mut guess).expect("Failed to read line");
    println!("You guessed: {guess}");

    let guess: u32 =  guess.trim().parse() {
        Ok(num) => num,
        Err(_) => continue,
    };

    match guess.cmp(&secret_number) {
        Ordering::Less => println!("Too small"),
        Ordering::Greater => println!("Too big"),
        Ordering::Equal => {
            println!("You win !");
            break;
        }
    }
 
  }
}
```

==== Cargo.toml  file: 

```toml
[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
```

2. Run  Cargo build  which will result in following error 

```
17 |     let guess: u32 = guess.trim().parse() {
   |                                           ^ expected one of `.`, `;`, `?`, `else`, or an operator            << 
```

3.  THE ERROR MESSAGE  does not give a hint of the actual cause of error. Which is actually caused due to missing the control flow operator  "match" 

### Possible Solution(s)

Expected: Cargo build to provide info and error code help/ suggestion for  missing "match" control flow operator. 

Actual Error:  
```
|     let guess: u32 = guess.trim().parse() {
   |                                           ^ expected one of `.`, `;`, `?`, `else`, or an operator 
```

The Actual Error produced is not readily helpful. 

### Notes

After making the change of including "match" in the above source code src/main.rs The code compiles successfully. 
```rust
let guess: u32 = **match** guess.trim().parse()  {
        Ok(num) => num,
        Err(_) => continue,
    };
```
```console
$ cargo build
   Compiling guessing_game v0.1.0 (/home/test-rust/guessing_game)
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
$ 
```

### Version

```text
$ cargo --version verbose
cargo 1.67.1 (8ecd4f20a 2023-01-10)
```

**Comment by rhmcruiser** [comment]
Would be nice to have cargo build produce a more readable error for this scenario of missing "match" control flow operator

**Comment by epage** [comment]
Thanks for reporting your idea on a better error message!  As a heads up, the error isn't coming from `cargo` but the rust compiler, [`rustc`](https://github.com/rust-lang/rust).  I don't know how practical it is for rustc to guess that a `match` was missing but the rustc maintainers would have a lot better idea.  I would recommend heading over there and seeing how they would prefer to discuss improved error messages.  I know one developer in particular is doing great work on trying to improve them.

FYI I've updated the issue with code fences to improve the readability

As this isn't a cargo issue, I'm going to go ahead and close this.  Hope you are able to get this improved!
