### ISSUE TITLE
`cargo grep`

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1179]
Sometimes I want to use grep to look for something in Servo, but it might be in a dependency. Since switching to Cargo, the source code for dependencies is now either in `~/.cargo/git/checkouts` or in `~/.cargo/registry/src`. But these have many subdirectories and it’s not obvious which are relevant: there can be multiple versions of the same library, or libraries used by other projects but not Servo. And then there are overrides with the `path` key in `.cargo/config`.

I think Cargo could help if it had a `cargo grep` commands that accepts arbitrary arguments, and invokes `grep` with these arguments followed by the paths, as additional arguments, to all directories that contains source code relevant to `cargo build`.

For example, running `cargo grep -i drawtarget` from `~/projects/servo` on my machine would invoke `grep -i drawtarget ~/projects/servo ~/.cargo/git/checkouts/rust-azure-03a3575c638f374d ~/.cargo/git/checkouts/skia-c7a55308e929f530 (many other paths…)`

**Comment by alexcrichton** [comment]
This sounds like a pretty awesome utility, but I'd probably prefer this to be an external command rather than baked into cargo itself. I think the only external utilities we rely on calling right now are `hg` (rarely) and `rustc`. Adding `cargo grep` which requires `grep` to be installed would likely put Windows users at a disadvantage unfortunately.

Seems like a great idea though!

**Comment by SimonSapin** [comment]
I don’t mind it being external, but it’d still need cooperation from Cargo to find out which are the relevant directories.

**Comment by sanxiyn** [comment]
Maybe grep should be implemented in Rust using Rust regex library, instead of spawning a new grep process. For example, `git grep` does not use grep binary.

**Comment by SimonSapin** [comment]
It could, but I don’t know if it should. Is far as I understand, one reason `git grep` re-implements matching itself is in order do to search in things like the tree of an earlier commit that are not necessarily in the filesystem.

**Comment by jeberger** [comment]
Or it could be made more general. Something like `cargo shell command` would invoke `command` on all the relevant directories. @SimonSapin's use case would then be satisfied with `cargo shell grep -ri drawtarget`.

**Comment by SimonSapin** [comment]
Generalizing even more, this could be built on top of #1098.

**Comment by alexcrichton** [comment]
With `cargo-install` now in existence this should be easy enough to implement externally and integrate into the normal workflow, and if this ends up being broadly used we can certainly consider inclusion!

**Comment by SimonSapin** [comment]
Is it possible for external crates to use Cargo as a library, say in this case to find the list of all crates in a dependency tree and the path to their source? How stable is Cargo’s API?

**Comment by alexcrichton** [comment]
It is indeed pretty easy! Cargo is [published on crates.io](https://crates.io/crates/cargo) whenever a release is made. Currently no API stability is made, but major version bumps follow each release so you can just pin to a particular Cargo.

**Comment by SimonSapin** [comment]
:+1:
