### ISSUE TITLE
Config env snapshot doesn't handle case-insensitive env vars correctly on windows

### ISSUE THREAD

**Issue by sokra** [rust-lang/cargo#11814]
### Problem

Some recent changes introduce snapshotting of env variables:

https://github.com/rust-lang/cargo/blob/a5d47a72595dd6fbe7d4e4f6ec20dc5fe724edd1/src/cargo/util/config/mod.rs#L209-L210

e. g. this PR https://github.com/rust-lang/cargo/pull/11727 by @kylematsuda

That introduces a little bug on windows where env vars are case-insensitive. `env::var_os` would handle that correctly, but `config.get_env_os` does a HashMap lookup which is case-sensitive.

e. g. the mentioned PR breaks the lookup of cargo subcommands on windows (where the env var is called `Path` instead of `PATH`).

### Steps

1. On windows install a cargo subcommand into a different directory
2. Add the directory to your PATH
3. Run cargo <subcommand>
4. Cargo says: no such command: `<subcommand>`

Workaround:

```
set PATH2=%PATH%
set PATH=
set PATH=%PATH2%
set PATH2=
```

This changes the casing of the env variable.

### Possible Solution(s)

Wrap the keys in the env snapshot HashMap with some case-insenstive NewType struct.

### Version

```text
nightly-2023-03-01
```

**Comment by kylematsuda** [comment]
Hi, thanks for the detailed explanation. Sorry about this, I didn't know that env vars are case-insensitive on Windows until now.

The `Config` has another hashmap (`upper_case_env`) that contains the environment variables converted to upper case. @ehuss, do you think it might be an acceptable workaround to (1) convert the variable name to upper case, then (2) check in `upper_case_env` if the variable is not found in `env` (on Windows only)?

**Comment by ehuss** [comment]
Hm, I don't think that will work perfectly since `upper_case_env` modifies `-` to `_` also. I can't offhand think of way to do this without having two separate maps (one with `-` converted, and one without).

I believe Windows does case conversion a little differently from how Rust does it (and it depends on the version of Windows), but I think for our purposes, `to_uppercase()` should be ok.

**Comment by ChrisDenton** [comment]
Btw, I wrote [a detailed comment](https://github.com/Aembit/env_wrapper/issues/1#issuecomment-1422321773) on a similar issue elsewhere.
