### ISSUE TITLE
Likely race conditions when using local dependency with a build script more than once

### ISSUE THREAD

**Issue by wackazong** [rust-lang/cargo#11818]
### Problem

I am using a local crate as a dependency in my main project's `Cargo.toml` using the `path` specifier. The local crate has a build script in it. When I add the local crate as a `dependency` and a `build-dependency` in the main project's `Cargo.toml` and I add a build.rs to the main project, it seems that when building Cargo starts the `build.rs` script of the dependency two times in parallel, which leads to general confusion if there is some file mangling going on. 

### Steps

1. Create a main project in a workspace with a build.rs
2. Create a dependency with a build.rs and in there with some file operations
3. Run `cargo build` in the main project
4. Due to parallel execution of the dependencies build.rs, there will likely be some read/write file errors

### Possible Solution(s)

I would expect that Cargo runs the build.rs script of the dependency only once and never in parallel.

### Version

```text
cargo 1.66.1 (ad779e08b 2023-01-10)
release: 1.66.1
commit-hash: ad779e08be893e57a9e17a810223a3e966f8c0d8
commit-date: 2023-01-10
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.5)
os: Mac OS 12.3.0 [64-bit]
```

**Comment by wackazong** [comment]
I added some simple file-based locking to the build script of the dependency. Now the build of the main project works fine. This supports my hypothesis about the parallel execution.

**Comment by ehuss** [comment]
It's hard to say without seeing a complete example what is going on. Usually a workspace dependency will only ever be built once (with a small caveat around proc-macros).

Also, build-scripts are only intended to write to the `OUT_DIR` directory, which should be unique per package and set of features. Writing outside of that directory is not supported.

**Comment by wackazong** [comment]
> Also, build-scripts are only intended to write to the OUT_DIR directory, which should be unique per package and set of features. Writing outside of that directory is not supported.

Ok, I did not know that. Thanks.
