### ISSUE TITLE
Cargo New Should Have Tests

### ISSUE THREAD

**Issue by JimLynchCodes** [rust-lang/cargo#11837]
### Problem

why is there no unit test in the project created with `cargo new`??

**Comment by weihanglo** [comment]
`cargo new` by default creates a package with a main binary target, so no unit tests for it. If you run `cargo new --lib` it does create a unit test for the new “library” package. Cargo tries to put a proper amount of code of a new project.

Do you have any thought on what a unit test should look like in a package with a binary target?

**Comment by weihanglo** [comment]
In the meantime, you could take a look at some cargo extensions from crates.io, like [cargo-generate](https://github.com/cargo-generate/cargo-generate) which does project customizations. 

For further discussion of creating a new package from pre-defined templates, please see <https://github.com/rust-lang/cargo/issues/5151>.

**Comment by JimLynchCodes** [comment]
Interesting... ok, thanks!
