### ISSUE TITLE
Getting Started guide needs some help

### ISSUE THREAD

**Issue by coderanger** [rust-lang/cargo#1184]
The "Getting Started" link on crates.io goes to http://doc.crates.io/guide.html, but that page doesn't actually show how to add/use a dependency except via git. The first section of http://doc.crates.io/crates-io.html should probably replace that section of documentation and be moved up the page.

**Comment by steveklabnik** [comment]
Yeah, I have a general "clean up Cargo docs" thing on my list, this is certainly part of it.

**Comment by steveklabnik** [comment]
This has since been fixed to show `time` from crates.io first.
