### ISSUE TITLE
error: could not find native static library 

### ISSUE THREAD

**Issue by shadowmint** [rust-lang/cargo#1185]
Various rust crates seem suddenly to be broken.

The error message is some what confusing, it typically appears as:

    Compiling sterm v0.0.1 (https://github.com/shadowmint/rust-sys-sterm?tag=0.0.1#04a98b92)
    Running `rustc ../../../.cargo/git/checkouts/rust-sys-sterm-06604d5232be1dae/0.0.1/src/lib.rs --crate-name sterm --crate-type lib -g -C metadata=6f2688cc21140749 -C extra-filename=-6f2688cc21140749 --out-dir /Users/doug/dev/rust-all/rust-terminal/target/deps --emit=dep-info,link -L dependency=/Users/doug/dev/rust-all/rust-terminal/target/deps -L dependency=/Users/doug/dev/rust-all/rust-terminal/target/deps -Awarnings -L c/build -l sterm:static`
    error: could not find native static library `sterm`, perhaps an -L flag is missing?

That is, the system library rust-sys-sterm exports:

    cargo:INCLUDE_DIRS=/Users/doug/dev/rust-all/rust-sys-sterm/c/include
    cargo:LIB=/Users/doug/dev/rust-all/rust-sys-sterm/c/build/libsterm.a
    cargo:rustc-flags=-l sterm:static -L c/build

...however, when a dependent crate compiles, it fails to locate the static library.

You can see another example of that in this repo; https://github.com/shadowmint/rust-sys-ruv

Oddly, when the error is received:

    Process didn't exit successfully: `rustc ../../../.cargo/git/checkouts/rust-sys-uv-172c5feec234e9e9/0.0.1/src/lib.rs --crate-name uv --crate-type lib -g -C metadata=ec54d3eb248926fd -C extra-filename=-ec54d3eb248926fd --out-dir /Users/doug/dev/rust-all/rust-sys-ruv/target/deps --emit=dep-info,link -L dependency=/Users/doug/dev/rust-all/rust-sys-ruv/target/deps -L dependency=/Users/doug/dev/rust-all/rust-sys-ruv/target/deps -Awarnings -L build/libuv-0.11.29/build/Release -l uv:static` (status=101)

Attempting to compile the check'd out crate seems to work fine:

    Tok:rust-sys-ruv doug$ cd ~/.cargo/git/checkouts/rust-sys-uv-172c5feec234e9e9/0.0.1
    Tok:0.0.1 doug$ cargo build
    Tok:0.0.1 doug$ cargo test
       Compiling uv v0.0.1 (file:///Users/doug/.cargo/git/checkouts/rust-sys-uv-172c5feec234e9e9/0.0.1)
         Running target/uv-d6e11405c05915d0
    running 0 tests
    test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
       Doc-tests uv
    running 0 tests
    test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

Anyway, long story short, this appears to be because this is (for some reason?) now being honoured by cargo; I'm not sure why, since this is a really old commit, but anyhow...

    commit a6f5b980cc44621efeed847e8d359f3b90c29080
    Author: Alex Crichton <alex@alexcrichton.com>
    Date:   Wed Dec 31 15:10:45 2014 -0800
    rustc: Re-jigger -L and -l for MSYS compatibility
    
    As discovered in #20376, the MSYS shell will silently rewrite arguemnts that
    look like unix paths into their windows path counterparts for compatibility, but
    the recently added `:kind` syntax added to the `-L` flag does not allow for this
    form of rewriting. This means that the syntax can be difficult to use at an MSYS
    prompt, as well as causing tests to fail when run manuall right now.
    
    This commit takes the other option presented in the original issue to prefix the
    path with `kind=` instead of suffixing it with `:kind`. For consistence, the
    `-l` flag is also now migrating to `kind=name`.
    
    This is a breaking change due to the *removal* of behavior with `-L`. All code
    using `:kind` should now pass `kind=` for `-L` arguments. This is not currently,
    but will become, a breaking change for `-l` flags. The old `name:kind` syntax is
    still accepted, but all code should update to `kind=name`.

However, the new syntax (kind=foo) doesn't work:

    Tok:rust-sys-ruv doug$ rustc ../rust-sys-uv/src/lib.rs --crate-name uv --crate-type lib -g -C metadata=8a530e5f46874e35 -C extra-filename=-8a530e5f46874e35 --out-dir /Users/doug/dev/rust-all/rust-sys-ruv/target/deps --emit=dep-info,link -L dependency=/Users/doug/dev/rust-all/rust-sys-ruv/target/deps -L dependency=/Users/doug/dev/rust-all/rust-sys-ruv/target/deps -L build/libuv-v1.0.2/build/Release -l static=uv
    error: could not find native static library `uv`, perhaps an -L flag is missing?

@alexcrichton Is this the intended behavior, or a bug in rustc?

Specifically, should kind=foo work, or is it deliberately kindfoo?

Either way, the documentation at http://doc.crates.io/build-script.html#outputs-of-the-build-script needs to be updated to reflect the new export syntax.

Extra edits: It would appear that it's not just the syntax; linking with staticuv attempts to locate the static library 'staticuv.a':

    ld: warning: directory not found for option '-L/Users/doug/dev/rust-all/rust-sys-ruv/.rust/lib/x86_64-apple-darwin'
    ld: warning: directory not found for option '-L/Users/doug/dev/rust-all/rust-sys-ruv/lib/x86_64-apple-darwin'
    ld: library not found for -lstaticuv
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

...so this *is* actually broken completely as far as I can tell.

**Comment by shadowmint** [comment]
Seems like this was mainly as a result of Path no longer providing an absolute path, resulting in the combination of -L and -l no longer working.

However, I'm going to leave this open for now, because the format that rustc accepts is now:

    -l kind=foo -L /path/to/folder/

The documentation at  http://doc.crates.io/build-script.html#outputs-of-the-build-script  should be updated to reflect this~

**Comment by alexcrichton** [comment]
Yes the syntax of `-l` and `-L` has been tweaked in the compiler recently, and I think the other relevant change is that the cwd of the command we invoke is no longer always the cwd of the project itself (at least when we invoke rustc). I think your `-L` you print out may wish to be a full path instead of a relative path.
