### ISSUE TITLE
Support --path when using --git

### ISSUE THREAD

**Issue by mway** [rust-lang/cargo#11868]
### Problem

Hi friends,

Apologies if this is covered in an issue already - I did some searching but didn't see anything related.

What I'd like to do is specify a `--path` when installing using `--git`. For example, consider Helix's `cargo`-based instructions ([ref](https://docs.helix-editor.com/install.html)):

```shell
git clone https://github.com/helix-editor/helix
cd helix
cargo install --locked --path helix-term
```

That works but is cumbersome; it feels like this is something that cargo could do instead.

### Proposed Solution

What I'd like to be able to run is:

```shell
cargo install --locked --path helix-term https://github.com/helix-editor/helix
```

and have cargo do all the magic behind the scenes.

### Notes

A couple of quick questions:

1. Is there a technical limitation that prevents this? I haven't dug too deeply yet, but at a high level, it feels like this should be doable.
2. Assuming the answer to (1) is "no", is this a feature that you would be open to?

I'm happy to take a stab at it, but want to sanity check that it's not a non-starter first.

Any thoughts/input would be appreciated. Thanks in advance!

**Comment by ehuss** [comment]
You can pass the name of the package you want to install like this:

```
cargo install --locked --path helix-term https://github.com/helix-editor/helix helix-term
```

Does that work for you?

**Comment by mway** [comment]
That does work! I'm sorry, new to Rust, so I didn't connect the dots on the `--path` argument vs the `[crate]...` command doc.

Thanks for the help!
