### ISSUE TITLE
`cargo fix` hard-codes the bug report URL

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#11877]
`fix` applies to more tools than just rustc itself; `cargo clippy --fix` is supported on stable, and I hope to make rustdoc lints fixable in the future: rust-lang/rustfix#192

It would be nice to make this the correct url for each tool, either by making it configurable somehow or hard-coding a different URL per-tool.

```
after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
```

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/109486#issuecomment-1479956569_

**Comment by ehuss** [comment]
Transferred to rust-lang/cargo as this message is generated from cargo.
