### ISSUE TITLE
cargo package & publish emit colour escapes on Win32 if they run git with net.git-fetch-with-cli = true

### ISSUE THREAD

**Issue by nabijaczleweli** [rust-lang/cargo#11909]
### Problem

![](https://user-images.githubusercontent.com/6709544/228532691-490e783f-54fa-404a-9ead-70cc8de7395d.png)

![](https://user-images.githubusercontent.com/6709544/228534189-84326758-f52a-47c7-8867-43db10a3da92.png)

### Steps

1. `cargo publish` or `cargo package`

### Possible Solution(s)

Making Win32 colours appears to be possible on the "Updating" and "Packaging" lines, so… do that later as well?

### Notes

My default rustup toolchain is stable-x86_64-pc-windows-gnu, updated yesterday.

I don't have TERM in the environment (but, y'know. it's Win32). This is fixed (by virtue of not emitting colours at all) if I export NO_COLOR=1.

### Version

```text
cargo 1.68.2 (6feb7c9cf 2023-03-26)
release: 1.68.2
commit-hash: 6feb7c9cfc0c5604732dba75e4c3b2dbea38e8d8
commit-date: 2023-03-26
host: x86_64-pc-windows-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.14393 (Windows 10 Home) [64-bit]
```

**Comment by nabijaczleweli** [comment]
Updated OP with --verbose; terminal is native cmd.exe, and cmd /V agrees with the --verbose output. No "shell" in this case (or I guess you could say cmd.exe is the shell), but I also repro this when running from [db]ash.

I agree it's strange; this appears to be governed by:
```rust
    // Package up and test a temporary tarball and only move it to the final
    // location if it actually passes all our tests. Any previously existing
    // tarball can be assumed as corrupt or invalid, so we just blow it away if
    // it exists.
    config
        .shell()
        .status("Packaging", pkg.package_id().to_string())?;
    dst.file().set_len(0)?;
    let uncompressed_size = tar(ws, pkg, ar_files, dst.file(), &filename)
        .with_context(|| "failed to prepare local package for uploading")?;
    if opts.verify {
        dst.seek(SeekFrom::Start(0))?;
        run_verify(ws, pkg, &dst, opts).with_context(|| "failed to verify package tarball")?
    }

    dst.seek(SeekFrom::Start(0))?;
    let src_path = dst.path();
    let dst_path = dst.parent().join(&filename);
    fs::rename(&src_path, &dst_path)
        .with_context(|| "failed to move temporary tarball into final location")?;

    let dst_metadata = dst
        .file()
        .metadata()
        .with_context(|| format!("could not learn metadata for: `{}`", dst_path.display()))?;
    let compressed_size = dst_metadata.len();

    let uncompressed = human_readable_bytes(uncompressed_size);
    let compressed = human_readable_bytes(compressed_size);

    let message = format!(
        "{} files, {:.1}{} ({:.1}{} compressed)",
        filecount, uncompressed.0, uncompressed.1, compressed.0, compressed.1,
    );
    // It doesn't really matter if this fails.
    drop(config.shell().status("Packaged", message));
```
which in the first bit correctly colours it, and in the last doesn't.

The thing that appears to separate them is the git output (I apparently have `net.git-fetch-with-cli = true`) and I can confirm it looks normal without it:
![](https://user-images.githubusercontent.com/6709544/228555633-9485b84f-1e42-4256-aa51-4911881023fa.png)

I also re-ran it with `net.git-fetch-with-cli = true` again soon after, and when it didn't output anything – because my local head matched the remote head – it was also coloured properly.

**Comment by nabijaczleweli** [comment]
Apparently running *any* (I tried `cp $(which echo).exe git.exe; PATH=.:$PATH cargo package` and the same for `true`) git process in `fetch_with_cli()` triggers this.

**Comment by epage** [comment]
When instantiating a termcolor stream, it tells windows to enable ANSI escape code support.  `cargo` instantiates those streams once and then reuses them throughout the process.

I wonder if windows is reseting that when a child process gets access to the TTY so in case it doesn't support ANSI escape codes.  Because we are reusing the termcolor stream, we then never re-enable it when git is done.

If this is the case, a workaround would be to initialize the termcolor streams on demand.  No idea how much of a performance overhead that would add.  Its likely not much to be concerned about because we are dealing with human-facing output.

**Comment by epage** [comment]
@nabijaczleweli does this reproduce with Terminal or Terminal Preview?  I've found `cmd.exe` is a bit more finicky when it comes to ANSI escape codes.

**Comment by nabijaczleweli** [comment]
No clue, that doesn't appear to be part of my distribution and the stand-alone package from github doesn't seem to work (indeed, the smallest minver I found in the README is for build 18362).

**Comment by weihanglo** [comment]
Or, does git version matter? I cannot reproduce under Git for Windows 2.41.0.

**Comment by nabijaczleweli** [comment]
I can on git 2.41.0: ![](https://github.com/rust-lang/cargo/assets/6709544/0ab5485e-7361-4a6a-bddc-e3f98c456a7f)

**Comment by ehuss** [comment]
Windows 10.0.14393 is about 7 years old. Are you unable to update? I suspect some change to the console has happened along that time (there have been *a lot* of changes to windows consoles in the past few years). The oldest Windows 10 I have handy is 17763, which I can't reproduce on.

**Comment by nabijaczleweli** [comment]
Stellar stuff from the compatibility manufacturer. If this only affects windows 10 but doesn't affect windows 10 then I don't think this is much of an issue (non-default configuration, minor graphical bug), or worth spending much time on, so closing accordingly.
