### ISSUE TITLE
`0.69.1` tag is missing

### ISSUE THREAD

**Issue by ZhongRuoyu** [rust-lang/cargo#11907]
### Problem

While packaging Rust 1.68.2 for Homebrew at https://github.com/Homebrew/homebrew-core/pull/126876, I noticed that Rust 1.68.2 ships Cargo 0.69.1 (based on the info obtained from https://github.com/rust-lang/rust/pull/109644). However, Cargo 0.69.1 is not tagged in the GitHub repo at the moment, and 0.69.0 is still displayed as the latest version on crates.io (https://crates.io/crates/cargo). May I confirm if there should be a `0.69.1` tag for Cargo? Thanks!

**Comment by weihanglo** [comment]
@pietroalbini could you take a look or delegate this to someone? Thanks!!

**Comment by pietroalbini** [comment]
Pushed the tag and published on crates.io.

**Comment by ZhongRuoyu** [comment]
Thanks @pietroalbini and @weihanglo!
