### ISSUE TITLE
Stabilize `cargo logout`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#11910]
This is a proposal to stabilize the `cargo logout` command.

This command is a fairly straightforward companion to `cargo login`. It will remove the token for a registry from `~/.cargo/credentials.toml`, or from a credential store with `-Zcredential-process`. This was added as part of `-Zcredential-process` because otherwise it would be quite awkward to try to remove a credential. However, it also has utility for the traditional `credentials.toml` file in the same way that `cargo login` is helpful. A user can manually edit the file in both cases, but providing a CLI command should be more convenient.

Other tools have similar functionality:
* [`npm logout`](https://docs.npmjs.com/cli/v7/commands/npm-logout)
* [`gem signout`](https://guides.rubygems.org/command-reference/#gem-signout)
* [`yarn logout`](https://classic.yarnpkg.com/en/docs/cli/logout)
* [`dart pub token remove`](https://dart.dev/tools/pub/cmd/pub-token)
* [`docker logout`](https://docs.docker.com/engine/reference/commandline/logout/)
* [`aws logout`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso/logout.html)
* [`gh auth logout`](https://cli.github.com/manual/gh_auth_logout)

(and probably many others)

I do not know of any concerns about the design or implementation of the command. Since I doubt we will discover anything new by keeping it unstable, I'd like to propose to stabilize it.

**Comment by Nemo157** [comment]
Is there any mention when running the command that the token is not revoked and that you may want to visit the website to revoke it too?
