### ISSUE TITLE
Powershell path conflict

### ISSUE THREAD

**Issue by VladImpaler64** [rust-lang/cargo#11914]
### Problem

When running cargo run or deploy and having multiple dependencies, linking command can't link cause path conflict.

### Steps

1-Running cargo build/run
2-Having paths with spaces or strange chars (allowed in windows)
3-Command genereted by cargo won't execute correctly cause path conflict
Output may look like this:

     error: linking with `x86_64-w64- mingw32-gcc` failed: exit code: 1 -the list of paths tha failed-
  = note: c://mingw.../../../../../ld.exe could not open ../../project.exe

### Possible Solution(s)

Make the correct paths when needed

C://Users/Example/Cargo_Build/My project -> ❌
"C://Users/Example/Cargo_Build/My project" -> ✅

### Notes

If path follow conventions you get normal execution

### Version

```text
cargo 1.68.2 (6feb7c9cf 2023-03-26)
release: 1.68.2
commit-hash: 6feb7c9cfc0c5604732dba75e4c3b2dbea38e8d8
commit-date: 2023-03-26
host: x86_64-pc-windows-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os:Windows 10.0.22621 (Windows 10 Home Single Language) [64-bit]
```

**Comment by ehuss** [comment]
Hm, that's strange, I can't seem to reproduce this.

Can you provide some more information:
* Does this happen with a hello-world project?  If not, what is the required project setup?
* Which mingw do you have installed (which distribution, which version, etc.)?
* What is the output of `x86_64-w64-mingw32-gcc --version`

**Comment by VladImpaler64** [comment]
This happened while I was following the first project in the book of rust introduction, adding the rand dependency, this is my mingw version:

```
GNU Make 4.4
Built for x86_64-w64-mingw32
Copyright (C) 1988-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
x86_64-w64-mingw32-gcc.exe (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

All I did was using` $ cargo run` and it keep showing the error that couldn´t link

I suspected the path was making some kind of conflict due to the output it was giving and yes, it was. As a spanish user I had this path 'C:/Users/Example/Programación/Rust/guessing_game/' the conflict comes from the 'ó' or any strange char or space(powershell allows this) so as I realize and removed it, it worked perfect and make the compile
