### ISSUE TITLE
reuse already compiled packages during `cargo build`

### ISSUE THREAD

**Issue by sk1122** [rust-lang/cargo#11923]
### Problem

build times are very long for bigger packages, and as build times take longer, reiterating with small changes take 10-15 minutes

### Proposed Solution

I know `cargo build` recompiles every package to build a 100% updated binary but cargo should add a flag to build command like `cargo build --reuse` which will reuse already compiled packages like `cargo run`

I also know that `cargo run` should be used for rapidly testing but some application requires binary to be able to work with test suites

**Comment by ehuss** [comment]
Cargo should already be caching all dependencies. Are you perhaps running cargo from different terminals, or in an editor and a terminal separately? If so, you may want to ensure that the environment variables are the same between the two.

On the second build, can you set the environment variable `CARGO_LOG=cargo::core::compiler::fingerprint=trace,cargo_util::paths=trace` and run `cargo build --verbose` and paste the entire output?

**Comment by sk1122** [comment]
Thanks, I found the issue, it was running in different environments, sorry for wasting your time😅

**Comment by ehuss** [comment]
Oh good, glad you figured it out. Closing as resolved, then.
