### ISSUE TITLE
Example and specifications do not match in cargo documentation

### ISSUE THREAD

**Issue by jthulhu** [rust-lang/cargo#11955]
In the paragraph [description](https://doc.rust-lang.org/cargo/commands/cargo-pkgid.html#description) of the `cargo pkgid` subcommand documentation, in the table that specifies the allowed formats, there is a mismatch between the format *url*`#`*name*`:`*version* and its example, `https://github.com/rust-lang/cargo#crates-io@0.21.0`: the format requires a `:` to separate the name from the version, but the example uses `@` (which is consistent with the rest of the specification).

**Comment by epage** [comment]
Both are actually supported but we have shifted the focus to `@` and it looks like that only got partially updated
