### ISSUE TITLE
Projects created on Windows with "cargo.toml" fail to run on Linux

### ISSUE THREAD

**Issue by aldencolerain** [rust-lang/cargo#11962]
### Problem

A project created on Windows, where the user decided to use "cargo.toml" will not run on Linux.

### Steps

1. Create a project on Windows and rename "Cargo.toml" to "cargo.toml"
2. Attempt to "cargo run" the project on Linux.

### Possible Solution(s)

I think a practical solution is for Cargo to maintain its default convention as decided in https://github.com/rust-lang/cargo/issues/45 but to read "Cargo.toml" in user friendly case insensitive way on Linux instead of warning the user that the project can't be run on Linux (or other case sensitive systems).

This would help Linux users given that people are already doing this:

https://github.com/rust-lang/cargo/issues/45#issuecomment-1416907917
> Today I searched "Why is Cargo.toml upper case." A strange thing to search, I admit, and I'm not sure if it's me being pedantic or nitpicky, or if it actually makes an aesthetic difference.
> 
> Either way, considering Rust promotes snake_case conventions, I too find it odd that Cargo.toml has an uppercase.
> 
> But today I also found out I can simply rename it to use a lower case and everything works. That makes me happy.
> 
> Though for the sake of convention, I'm here to put my vote for `cargo.toml`.

**Edit: Removed opinions regarding https://github.com/rust-lang/cargo/issues/45**

**Comment by epage** [comment]
As you are aware of #45 which is closed, is there a reason you feel this issue needs to be distinct from #45 vs keeping all of that conversation in one place?

**Comment by aldencolerain** [comment]
@epage For me the core issue is someone can create and run a package on on Windows and it doesn't run on Linux due to the lack of case interoperability.

I think the https://github.com/rust-lang/cargo/issues/45 feature request is relevant, only as one possible solution to this problem.  There are alternative solutions, one would be expanding the warning to prevent Windows and Mac users from running with "cargo.toml".  I'm not a Windows export but I assume that's possible?  I also think more warnings are less ergonomic and something like that other proposal would solve this nicely.

**Comment by aldencolerain** [comment]
If there is interest, I would be happy to make a PR.

**Comment by epage** [comment]
> only as one possible solution to this problem. There are alternative solutions

FYI at least for me, it didn't come across that way since the "Possible Solution" section puts so much effort into re-litigating #45.

> One would be expanding the warning to prevent Windows and Mac users from running with "cargo.toml". I'm not a Windows export but I assume that's possible? I think more warnings are less ergonomic and something like that other proposal would solve this nicely.

If case-insensitive FS users can use `cargo.toml` today, then we wouldn't be able to error as that would break compatibility.  The most we could do is warn.  For the most part, we've been minimizing our warnings as cargo does not have a way to  enable/disable warnings today.  Hopefully https://github.com/rust-lang/rfcs/pull/3389 will help with that, unblocking a warning like this.

**Comment by aldencolerain** [comment]
Good point on re-litigating the old issue, I shouldn't have opining so much on that.  I will edit that out so as not to muddle the issue.  I hit the bug and had just gone through source code looking for the warning, then to that issues for relevant discussion and it was fresh on my mind.

I agree that breaking "cargo.toml" and on adding more warnings doesn't make sense.  I found the warning on Linux confusing since the package worked for the person who made it.

Would it be acceptable to not reopen the old discussion and maintain the standard of "Cargo.html" etc as decided previously, but to read the file in a case insensitive manner instead of warn on Linux?

**Comment by weihanglo** [comment]
> Would it be acceptable to maintain the standard of "Cargo.html" etc as decided previously, but to read the file in a case insensitive manner instead of warn on Linux?

It could be the other kind of breaking. Users with old toolchain cannot compile new project with lowercase "cargo.toml" even it is completely compatible. External tools also need a non-trivial update for the new logic to accept “cargo.toml”. It feels like a quite large break to me.

**Comment by aldencolerain** [comment]
> Users with old toolchain cannot compile new project with lowercase "cargo.toml" even it is completely compatible.

This is the problem I'm describing, people have already created projects with "cargo.html".  They compile and run on Windows and Mac now, but not on Linux.

**Comment by weihanglo** [comment]
You cannot fix older versions of Cargo. Any potential fix will only affect future versions. Since Cargo already emits a warning, people creating lower case cargo.toml should be quite less.

Formally accepting lower case cargo.toml is completely a different story. It implies the whole ecosystem of cargo plugins needs to make that transition in order to follow this change, otherwise an inconsistency occurs between Cargo and those tools. That would be a huge churn to the plugin ecosystem, as well as other 3rd party service analyzing manifest files. 

Normally, users seldom create the manifest by hand and create a lower case cargo.toml simultaneously. Those cases should be rare and niche. If they did that they might have a compelling reason not to share code with Linux. Besides, this issue can be fixed easily by end-users, and I don't think any of changing the convention or making it just compile is easier than a simple fix on the user's side.

That being said, we still look into a way to suppress warning emitted by Cargo. This is tracked by rust-lang/rfcs#3389 . Closing this now. Thank you for the discussion!

**Comment by ChrisDenton** [comment]
If cargo can detect it could cargo also fix it? It's a bit tricky to fix manually because it'd require two renames, which may not be obvious to the user.

**Comment by weihanglo** [comment]
I don't really know 😞. An auto-fix sounds great to me. However Cargo is better doing so after a confirmation from the user.

Do you have a reliable way to detect case-sensitivity for paths on Windows?

**Comment by epage** [comment]
We shouldn't be mutating a users project without their explicit choice.  We could use `cargo fix` to address that.

**Comment by epage** [comment]
> Do you have a reliable way to detect case-sensitivity for paths on Windows?

Windows is case-preserving, so if we just check if `path.file_name() == Some(OsStr::new("cargo.toml")` and warn on that, it should be sufficient from my experience.

**Comment by weihanglo** [comment]
Expand this a bit more. Should we also check `cargo.lock`, `.cargo/Config.toml` or any misuse of letter case? Maybe just for `cargo.toml` is good enough.

**Comment by aldencolerain** [comment]
I agree the convention should not be changed, just clarify.  I think showing a warning (that doesn't actually prevent things from being compiled/run on a case insensitive system) could be helpful and certainly an improvement.

In regard to having Cargo just read "Cargo.toml" case intensively, that seems like an easy non breaking solution.  Can you clarify why that isn't being considered?

One possible solution is to warn the users on all systems and then read the file case insensitively.  It would not break anyone's code but would encourage users fix the issue at their leisure.

**Comment by aldencolerain** [comment]
I am going to close this issue for now.  I think the warning might help, but doesn't really address this issue and forcing "Cargo.toml" on case insensitive systems would be a breaking change. I think there is a fairly clear distinction between what the formal convention is as discussed in the other issue and making the tool operate gracefully between the systems.

That being said, I gathered from the comments that if Cargo on Linux read the file flexibly that might inadvertently imply that "cargo.toml" is acceptable or conventional.  If that is a concern, I understand, and probably better to close this for now until this issue becomes more problematic for more people or there is a simple and acceptable solution.
