### ISSUE TITLE
unable to update a dependency using sparse protocol

### ISSUE THREAD

**Issue by jakecoffman** [rust-lang/cargo#11965]
### Problem

Hello from the Dependabot team 👋 

We recently updated to Rust 1.68.2 and enabled the sparse registry environment variable but we're seeing this error when running updates: ```usage of sparse registries requires `-Z sparse-registry` ```.

The blog post doesn't mention needing to set that, and when I do I get: ```error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel``` so this seems like it might be a bug?

### Steps

```
export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
git clone --depth=1 https://github.com/geo-engine/geoengine
cd geoengine
cargo update -p time --verbose
```

### Version

On my Mac where I can reproduce it:

```text
cargo 1.68.0-nightly (2381cbdb4 2022-12-23)
release: 1.68.0-nightly
commit-hash: 2381cbdb4e9b07090f552d34a44a529b6e620e44
commit-date: 2022-12-23
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.87.0 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 13.3.1 [64-bit]
```

But you can see what Dependabot is running [here](https://github.com/dependabot/dependabot-core/blob/a35b39d3a440cc6e3bc6f60a17bb83d3d7793eb3/cargo/Dockerfile#L21-L20).

**Comment by weihanglo** [comment]
The stabilization was done and synced up to rust-lang/rust was on Jan 20th <https://github.com/rust-lang/rust/pull/107120>. Before that the feature was still unstable, and `geoengine` seems to pin on `nightly-2022-12-28`.

**Comment by jakecoffman** [comment]
Ah ok, we'll have to be a bit smarter about the older toolchains then. Thanks for the info!
