### ISSUE TITLE
config-cli should be inherited automatically by third-party subcommands

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#11972]
### Problem

When you run `cargo --config foo.toml subcommand` or `cargo --config foo.bar=baz subcommand`, where subcommand is provided by a cargo-subcommand crate, the subcommand doesn't act as if the extra config was set.

Compare to git, where `git -c foo.bar=baz subcommand` does propagate the extra config to the subcommand.

**Comment by weihanglo** [comment]
Thanks for the report. This seems to be a duplicate of <https://github.com/rust-lang/cargo/issues/11031>.

**Comment by glandium** [comment]
Indeed, it is.

**Comment by weihanglo** [comment]
Thanks. Close in favour of #11031.
