### ISSUE TITLE
Spurious CI failure: registry::not_found_permutations

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#11975]
This [bors CI failure](https://github.com/rust-lang/rust/pull/110177#issuecomment-1508313026) was almost certainly spurious:

```
 thread 'registry::not_found_permutations' panicked at 'assertion failed: `(left == right)`
  left: `["/index/a-/b-/a-b-c", "/index/a-/b_/a-b_c", "/index/a_/b-/a_b-c", "/index/a_/b_/a_b_c"]`,
 right: `["/index/a-/b-/a-b-c", "/index/a_/b-/a_b-c", "/index/a-/b_/a-b_c", "/index/a_/b_/a_b_c"]`', src/tools/cargo/tests/testsuite/registry.rs:3187:5


failures:
    registry::not_found_permutations
```

I think this is the cargo test suite? Hard to say from the logs.

**Comment by ehuss** [comment]
Thanks for the report. I will fix this shortly.

In the future, please tag me or the cargo team for a cargo test issue. Otherwise there is a high chance the issue will just get lost in rust-lang/rust.  I transferred this to rust-lang/cargo since it is an issue here.

**Comment by RalfJung** [comment]
I considered pinging the team but wanted to avoid over-pinging; will try to remember this for the future. :)
