### ISSUE TITLE
Please allow to unset configuration items

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#11973]
### Problem

When multiple cargo config.tomls are involved, the last one read supersedes the older ones, so if the first sets foo.bar=baz, and the second sets foo.bar=qux, cargo will use qux as the value. This also applies to config-cli, where what is given to the cli is preferred.

But this scheme doesn't allow to unset foo.bar. The best that can apparently be done is to set it to some empty value, but that only works if an empty value has the same semantic meaning as if the value was not set. That's not the case for e.g. `source.*.replace-with`.

**Comment by weihanglo** [comment]
Thank you for proposing this feature. This is effectively a duplicate as #8687. Closing in favour of that. If something is wrong, please let us know :)
