### ISSUE TITLE
Cargo workspace and crates dependency inconsistency

### ISSUE THREAD

**Issue by rjzak** [rust-lang/cargo#11989]
### Problem

Regarding this commit https://github.com/malwaredb/malwaredb-rs/tree/1cdbab09ad36915758c921f3265d96bf8d6a85e8...

I'm working on a client/server system, where the server is the main project, some common items are sub-crates in `crates/`, and a client application in `client/`. I'm using Cargo workspaces, and I've run into a weird issue.

I'm trying to use the `reqwest` crate in the `client/` sub-crate, and if I'm in the `client/` directory, `cargo build` works fine. However, if I'm in the project directory, `cargo build` fails with `use of undeclared crate or module 'reqwest'`. The Cargo.toml file for the project has `reqwest` listed in `[workspace.dependencies]`, and `client/Cargo.toml` has `request = { workspace = true }`.

If I add `reqwest` as a crate for the root project in `[dependencies]`, then building in the root directory works fine. Am I missing something?

The sub-crate `crates/server` has workspace dependencies not listed as `[dependencies]` in the root Cargo.toml, and it works fine. Also, trying to move `client/` to `crates/client/` didn't help.

__Root Cargo.toml__
```
[workspace.dependencies]
reqwest = { version = "0.11.6", features = ["blocking", "json", "deflate", "gzip"], default-features = false }

[workspace]
resolver = "2"
members = [
    'crates/api',
    'crates/types',
    'crates/server',
    'client',
]
```

__client/Cargo.toml__
`reqwest = { workspace = true }`

PWD=`${PROJECT_HOME}/client/`: `cargo build` works fine!
PWD=`${PROJECT_HOME}/`: `cargo build` has the error: `undeclared crate or module 'reqwest'`

### Notes

Happens on my PowerPC system, but also on Github Runners https://github.com/malwaredb/malwaredb-rs/actions/runs/4728111029/jobs/8389343476, so it's not an architecture thing.

### Version

```text
cargo 1.68.2 (6feb7c9cf 2023-03-26)
release: 1.68.2
commit-hash: 6feb7c9cfc0c5604732dba75e4c3b2dbea38e8d8
commit-date: 2023-03-26
host: powerpc64le-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Debian 11 (bullseye) [64-bit]
```

**Comment by rjzak** [comment]
Adding `reqwest = {workspace = true}` under `[dependencies]` in the root `Cargo.toml` makes things compile, but that's inconsistent. The other sub-crates in `crates/` have workspace dependencies not under the root `[dependencies]`, and they compile fine. So why is the project under `client/` treated differently?

**Comment by weihanglo** [comment]
When running `cargo build`, Cargo compiles bin target `mdb_client` but cannot find `reqwest` in `[dependencies]` in the root Cargo.toml. Note that Cargo targets is a not a workspace thing. It cannot understand dependencies from other workspace members.

If you use the currently nightly, you'll see a better error message (We've just improved it a bit!). It indicates that the error was from bin target `mdb_client` of package `malwaredb`.

```console
error: could not compile `malwaredb` (bin "mdb_client") due to 2 previous errors
```

**Comment by rjzak** [comment]
I figured it out, it was due to an entry for the second crate in a `[[bin]]` section in the root `Cargo.toml`, which was inadvertently bringing the other crate into scope.
