### ISSUE TITLE
Use glob syntax when probing members in `[workspace]` for Cargo itself

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#11988]
This is just for the record of making it happen in Cargo the project itself. The actual feature request is in #11405 and other issues listed there.

The problem in cargo itself is that both `crates/*` and `crates/credential/*` contain crates, but when probing with `crates/*` Cargo expects `crates/credential` to be a workspace member.

**Comment by epage** [comment]
Should we move `credential/` into the root to unblock this?

Longer term, #11362 fits this situation.

**Comment by weihanglo** [comment]
I think yes in the short-term moving crates is a better approach. It's relatively easy to rollback so let's do it.

Keep in mind that we also need to update [code here in rust-lang/rust](https://github.com/rust-lang/rust/blob/4e463012580415a932ae4fc255aff45982c70369/src/bootstrap/tool.rs#L588-L603) accordingly.

BTW I found that `cargo-credential-gnome-secret` is not built in rust-lang/rust. Perhaps just an oversight when updating cargo submodule?

**Comment by ehuss** [comment]
> BTW I found that `cargo-credential-gnome-secret` is not built in rust-lang/rust. Perhaps just an oversight when updating cargo submodule?

That was intentional.  At the time, the version of Linux used in the dist builders was too old for libsecret. I'm not sure if that is still the case. However, it needs to be linked dynamically, and I'm not sure how that would work when transferred to various different distros. The current intent is that if someone wants to use `cargo-credential-gnome-secret`, they need to manually build it (`cargo install cargo-credential-gnome-secret`). There is some documentation for this in the unstable chapter.

**Comment by kornelski** [comment]
Are you sure about this change? I can't run workspace commands since that has been changed:

```
cargo test
error: failed to load manifest for workspace member `/Users/user/www/cargo/crates/credential`

Caused by:
  failed to read `/Users/user/www/cargo/crates/credential/Cargo.toml`

Caused by:
  No such file or directory (os error 2)


cargo fmt
`cargo metadata` exited with an error: error: failed to load manifest for workspace member `/Users/user/www/cargo/crates/credential`

Caused by:
  failed to read `/Users/user/www/cargo/crates/credential/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
cargo-fmt
This utility formats all bin and lib files of the current crate using rustfmt.

USAGE:
    cargo fmt [OPTIONS] [-- <rustfmt_options>...]

ARGS:
    <rustfmt_options>...    Options passed to rustfmt

```

**Comment by weihanglo** [comment]
Hmm… in which commit you ran these commands? 🤔

Mine looks fine with dcc47025991ca570bb930bb7e89a3d171cdfbba6. CI also reported it without failures. https://github.com/rust-lang/cargo/blob/dcc47025991ca570bb930bb7e89a3d171cdfbba6/.github/workflows/main.yml#L26

**Comment by weihanglo** [comment]
Maybe you need to `rm -r crates/credential`?

**Comment by kornelski** [comment]
I was using `master` branch of a pre-existing `cargo` checkout. `rm -rf` did solve the problem! I guess that was the pitfall of git not managing directories directly.
