### ISSUE TITLE
Vendoring on Windows replaces license files contents by a path for some packages that didn't change

### ISSUE THREAD

**Issue by yjugl** [rust-lang/cargo#11985]
### Problem

I'm using:

```
$ cargo --version
cargo 1.68.2 (6feb7c9cf 2023-03-26)
```

And trying to update only the `getrandom` dependency to the latest version in Firefox:

```
cargo update -p getrandom
./mach vendor rust
```

That results in changes in some LICENSE files for packages not related to `getrandom`, where the contents of the file gets replaced by a path: `third_party/rust/cssparser-macros/LICENSE` now contains the text`../LICENSE`, and `third_party/rust/wgpu-{core,hal,types}/LICENSE.{APACHE,MIT}` now contain the text `../LICENSE.APACHE` or `../LICENSE.MIT`.

The .cargo-checksum.json files also reflect these change as though they were legit changes of contents on the files.

Analyzing what's going on in the system seems to point to the sync function in `src/cargo/ops/vendor.rs` as the culprit for deleting then writing the file.

**What should happen**

`cssparser-macros` and `wgpu-{core,hal,types}` should be unaffected by vendoring.

### Version

```text
$ cargo version --verbose
cargo 1.68.2 (6feb7c9cf 2023-03-26)
release: 1.68.2
commit-hash: 6feb7c9cfc0c5604732dba75e4c3b2dbea38e8d8
commit-date: 2023-03-26
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 10 Home) [64-bit]
```
```

**Comment by ehuss** [comment]
Do you perhaps have `core.symlinks=false` in your git configuration? Do you have Windows Developer mode enabled? Do you have any cargo configuration files?

**Comment by yjugl** [comment]
Thanks for your reply! With these keywords I was able to find [this issue](https://github.com/rust-lang/cargo/issues/5664) and [this post](https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201), which in turn helped me solve my issue as follows:

```
git config --global core.symlinks true
rm -rf ~/.cargo/git/checkouts/*
./mach vendor rust
```

So indeed I had `core.symlinks=false` set globally, and I also needed to update the local value for `core.symlinks` in the already-checked-out repositories (for simplicity I just deleted them so that cargo would check them out again).
