### ISSUE TITLE
Check if a pull request forgot to commit Cargo.lock in CI

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#11992]
### Problem

Starting from #11851, this project commits `Cargo.lock` into git history. However, CI has yet got a good process to detect the error when a change of `Cargo.lock` should be committed but not. This kind of failure is now caught by `docs` job, which effectively runs `ci/validate-man.sh`. 

For example, CI failures below detect `Cargo.lock` changed and was not committed.

- https://github.com/rust-lang/cargo/actions/runs/4731403990/jobs/8396280788
- https://github.com/rust-lang/cargo/actions/runs/4731845144/jobs/8397266389

### Proposed Solution

We shouldn't rely on `ci/validate-man.sh`, as it serves for a different purpose. We may add a new CI job or step to detect if `Cargo.lock` changes and git status is dirty after a build.

**Comment by epage** [comment]
> We may add a new CI job or step to detect if Cargo.lock changes and git status is dirty after a build.

Can't you just do a CI job with `cargo check --locked` as the first step?

**Comment by weihanglo** [comment]
> Can't you just do a CI job with `cargo check --locked` as the first step?

I believe yes! That will be a new “CI step”.
