### ISSUE TITLE
cross-compilation: can't build with --target=arm-unknown-linux-gnueabi

### ISSUE THREAD

**Issue by piec** [rust-lang/cargo#1200]
Hello,

I'm trying to use cargo to build arm binaries on my linux x86_64 machine. At the moment I'm only trying to build a simple hello world using cargo.
I successfully built rustc with arm support and it's great, I invoke it like this

    rustc -C linker=arm-linux-gnueabi-gcc --target=arm-unknown-linux-gnueabi ...

I'm now trying to use cargo in order to build packages (crates).
I tried to use cargo nightly with the ``--target`` argument:

    cargo build --verbose --target=arm-unknown-linux-gnueabi

but rustc doesn't use the correct linker, it uses ``/usr/bin/ld`` instead of ``arm-unknown-linux-gnueabi-ld`` [full log](https://gist.github.com/piec/43c559cad7e4a8b66104)
I can see that cargo invokes rustc without the ``-C linker=arm-linux-gnueabi-gcc`` argument (if I do so manually then the build succeeds).

I thought I would try to build cargo with arm support since the configure has a ``--target`` flag, but the build fails [full log](https://gist.github.com/piec/98634d2a5dd9a32b8ab3)
It seems weird to me to build cargo for a specific target platform since I just use it as a build tool (make doesn't need to know about arm for example). Does cargo just need to pass the correct ``-C linker=...`` parameter to ``rustc`` ?

Thanks in advance :)

**Comment by huonw** [comment]
You may need to point cargo at the correct linker in [a `.cargo/config` file](http://doc.crates.io/config.html), e.g. add this to `~/.cargo/config`.

```toml
[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"
```

**Comment by piec** [comment]
Ah cool I've been able to build crates with that config :+1: 
But it's just a workaround right?

**Comment by alexcrichton** [comment]
Yes as @huonw mentioned the method of solving this is a `.cargo/config` file. Cargo has no way to have prior knowledge about what linkers to invoke for which targets, so I think we'll always require some form of configuration if it's a nonstandard target.
