### ISSUE TITLE
Make "cargo init name" still operate in current directory

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/cargo#12008]
### Problem

The difference between `cargo new` and `cargo init`, as I understand it, is that `cargo new mycrate` creates a project named `mycrate` in a new subdirectory `mycrate` of the current directory, while `cargo init` creates a project in the current directory with the directory name as the project name.

Right now, `cargo init mycrate` acts like `cargo new mycrate`: it creates a project named `mycrate` in a new subdirectory `mycrate` of the current directory. This is unfortunate, as it gives no way (that I can see) to create a crate using `cargo new` or `cargo init` that has a directory name different from its project name; it's at the least inconvenient in this common case.

### Proposed Solution

I would strongly prefer `cargo init mycrate` to create a project in the current directory with project name `mycrate`.

### Notes

I understand that this might conceivably break existing scripts. If this change is too painful, perhaps a flag could be required for this behavior, or some different command name could be used.

**Comment by ehuss** [comment]
> This is unfortunate, as it gives no way (that I can see) to create a crate using `cargo new` or `cargo init` that has a directory name different from its project name; it's at the least inconvenient in this common case.

You should be able to set the package name with the `--name` option along with the directory as an argument. For example, `cargo new --name package-name directory-name`

**Comment by BartMassey** [comment]
Doh. I somehow missed that flag when looking at `cargo init --help`. Will read more carefully next time, thanks.

Would still prefer that `cargo init` always worked in the current directory, but I can live with this.

**Comment by weihanglo** [comment]
Thanks for confirming the flag meets your need! This seems resolved. Closing.
