### ISSUE TITLE
`cargo install --release` gives a confusing error

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#12009]
### Problem

I have a friend who doesn't know rust and tried to install a program written in Rust. First he tried `cargo build` and that ran too slowly, so I told him to use `--release`. Then he tested it to his satisfaction and tried to install it:
```
$ cargo install --release --path . --locked
error: unexpected argument '--release' found

  note: argument '--examples' exists

Usage: cargo install --examples [crate]...

For more information, try '--help'.
```
The problem here is that the defaults are flipped between `build` and `install`: build defaults to the `dev` profile and has a `--release` flag, `install` defaults to the release profile and has a `--debug` flag. That seems ok, but the error message is unhelpful.

### Proposed Solution

Improve the error message:
```
$ cargo install --release --path . --locked
error: unexpected argument '--release' found

  note: `install` uses the release profile by default
  help: remove `--release` to install using the release profile: `cargo install --path . --locked`

Usage: cargo install [OPTIONS] [crate]...

For more information, try '--help'.
```

### Notes

Don't remember when this happened originally, but the error messages in the issue description came from `cargo 1.68.2 (6feb7c9cf 2023-03-26)`.

**Comment by jyn514** [comment]
It probably makes sense to do the same for `cargo build --debug`, which gives a similarly unhelpful error currently:
```
$ cargo build --debug
error: unexpected argument '--debug' found

Usage: cargo build [OPTIONS]

For more information, try '--help'.
```

**Comment by epage** [comment]
clap-rs/clap#4706 would be useful for this

**Comment by weihanglo** [comment]
#11702 wants exactly the same feature. Close this as it seems to be a duplicate. I'll add this case to the list there.
