### ISSUE TITLE
Allow creating test binaries with predictable names

### ISSUE THREAD

**Issue by jjant** [rust-lang/cargo#12004]
### Problem

I have a fleet of machines that build code, on these I want to run `cargo build --tests` to build a test binary, and hand that over to the machines that actually run the tests.

At the moment, because the generated binary has a non-predictable name (it contains a hash), we'd have to resort to the annoying trick of using `--mesage-format=json` and parse the output json to find the binary. See [example](https://github.com/rust-lang/cargo/issues/3670#issuecomment-1239984481).

### Proposed Solution

It'd be nice to have a flag to name the test executable: `cargo build --tests --out-name="my-tests-binary"`, or a way to remove the hash from the name.

**Comment by weihanglo** [comment]
Thanks for the report! 

It feels like [Cargo targets](https://doc.rust-lang.org/nightly/cargo/reference/cargo-targets.html) generally have the same problem; only some of them are uplift to `target/{debug,release}/` directory and have hash suffix erased. From my understanding, test/bench/example targets weren't designed to share final artifact outside the project.

There is an unstable feature [`different-binary-name`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#different-binary-name) (tracking issue #9778) enabling Cargo to set a different file name for `[[bin]]` targets. There are some discussions around mkaing it support `[lib]` target as well. Not sure if we want to extend its functionality to tests/benches/examples.

OTOH, here is a `cargo rustc` workaround. Could you try if it meets your need?

```
cargo rustc --test myinteg-test -- --emit link="myinteg-test.exe"
```

**Comment by weihanglo** [comment]
Thanks for the info. Closing in favor of #3670.
