### ISSUE TITLE
"An unknown error occurred" <- can this give more details? maybe stacktrace ?

### ISSUE THREAD

**Issue by emanueLczirai** [rust-lang/cargo#1201]
I run this inside the folder of a git clone of https://github.com/jeaye/ncurses-rs

```
export VERBOSE=1
$ cargo build -v
An unknown error occurred
```
I see the code saying that is here: https://github.com/rust-lang/cargo/blob/73b904c05e1a4504591da65d1c4f733b558d5908/src/cargo/lib.rs#L158

```
$ cargo -V
cargo 0.0.1-pre-nightly (2422edc 2015-01-19 07:28:44 +0000)
$ rustc -v
rustc 0.12.0-pre (7277fe9ee 2014-09-13 17:25:54 +0000)
```

Maybe I am missing some requirements for cargo, but I am expecting it to be more specific about the error.

I haven't gotten into Rust yet, but want to. I hope this doesn't speak about the coding practices borne by the language ie. easier to code with lack of specificity in mind  with regards to error reporting; maybe it is possible to get a stacktrace with Rust but cargo coders decided against it(?)

I'll let you know if I find out what caused this error, for me. (can't recompile rust currently due to a compilation error that I'm looking into)

**Comment by alexcrichton** [comment]
This is certainly not good! This seems to be a recent regression in diagnostics, however:

```
$ cargo build -v
An unknown error occurred
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names` (status=101)
--- stderr
error: Unrecognized option: 'print'.

$ cargo -V
cargo 0.0.1-pre-nightly (8154255 2015-01-14 19:14:12 +0000)
```

I'll see if I can't tell what's going on soon!

**Comment by emanueLczirai** [comment]
The error went away after upgrading rust (in my case, the only thing I've changed):

```
rustc -V
rustc 1.0.0-dev (3bf41dafc 2015-01-20 06:45:02 +0000)
```

**Comment by emanueLczirai** [comment]
Thanks! Btw, I looked into Rust more and I'm loving everything so far! All your work is much appreciated!
