### ISSUE TITLE
[env] settings are not consistently applied to rustc invocations

### ISSUE THREAD

**Issue by main--** [rust-lang/cargo#12028]
### Problem

The [docs](https://doc.rust-lang.org/cargo/reference/config.html#env) on the `[env]` section in the config file state:

>The `[env]` section allows you to set additional environment variables for build scripts, **rustc invocations**, cargo run and cargo build.

Hence, I would expect these variables to be set whenever rustc is invoked. In practice, compiling a simple Hello World crate reveals that the compilation starts with a rustc invocation that does not have these environment variables set.

### Steps

1. Set an environment variable in the cargo config
2. Expect it to consistently apply to all rustc invocations
3. It doesn't

### Possible Solution(s)

The environment variable should be consistently applied to all rustc invocations.

### Notes

This problem is especially frustrating in conjunction with sccache (as `rustc-wrapper`). sccache can be configured via environment variables, which makes an `[env]` section in a `config.toml` an extremely attractive way for a project-specific caching setup. sccache launches a server process on its first invocation. Since the current behavior of cargo is to ignore environment variables for the first rustc invocation, sccache will at that point launch a server process that is missing the config (and instead defaults to caching on the local disk). Subsequent invocations would have the environment variables present, but since the sccache server is already running, they will be ignored. In essence, the only way to make this work is to wrap sccache in a shell script that explicitly sets the variables, rendering cargo's env feature entirely useless for this usecase.

### Version

```text
cargo 1.68.0 (115f34552 2023-02-26)
release: 1.68.0
commit-hash: 115f34552518a2f9b96d740192addbac1271e7e6
commit-date: 2023-02-26
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by epage** [comment]
Can you give more detailed reproduction steps?

I setup a project

```console
$ cargo init
$ mkdir .cargo
```

`.cargo/config.toml`
```toml
[env]
HELLO="goodbye"
```

`src/main.rs`
```rust
fn main() {
    println!("{}, world!", env!("HELLO"));
}
```

And got this result:

```console
$ cargo run
   Compiling cargo-12028 v0.1.0 (/home/epage/src/personal/dump/cargo-12028)
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/cargo-12028`
goodbye, world!
```

**Comment by main--** [comment]
Sure!

```
$ cargo init
$ mkdir .cargo
$ cat > .cargo/config.toml
[build]
rustc-wrapper = './wrapper.sh'

[env]
HELLO="goodbye"
$ cat > wrapper.sh
#!/bin/sh
echo "HELLO=$HELLO" >> build.log
exec "$@"
$ chmod +x wrapper.sh
$ cargo build
$ cat build.log
HELLO=
HELLO=goodbye
```

This problem is especially obnoxious to debug because the output of the env-less invocation is totally suppressed, so it's only directly reproducible by writing into a file.

**Comment by ehuss** [comment]
@epage They are referring to the target discovery (around [here](https://github.com/rust-lang/cargo/blob/1c14e10523773908676ccdd7f0594ddd5058e387/src/cargo/core/compiler/build_context/target_info.rs#L177-L189)).  I think it was just an oversight.

**Comment by weihanglo** [comment]
To make `[env]` work for the rustc invocation of the target discovery, we could apply code similar to this:

https://github.com/rust-lang/cargo/blob/a4a8bd1742b8e60f069a5a9cea6351de39ef80d9/src/cargo/core/compiler/compilation.rs#L352-L362

Could it be that people already depend on this unfortunate oversight that first rustc call get no env from `[env]`? Feel like it's pretty rare.
