### ISSUE TITLE
Should cargo rebuild all files when the rust compiler version changes?

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/cargo#1203]
We've noticed in Servo that when we upgrade Rust, Cargo, or both, if we don't manually clean the target/ directory, Cargo will rebuild some unpredictable subset of the Rust code and attempt to link against rlibs produced by an old version of the compiler, resulting in badness.

Is this something Cargo should be handling? Or should we just have our infra clean the directories whenever Cargo or Rust are updated (https://github.com/servo/servo/issues/4663 )?

**Comment by alexcrichton** [comment]
Interesting! This is definitely something that I would expect Cargo to take care of, and Cargo does [have logic for dealing with this](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_rustc/fingerprint.rs#L222). Every time I've updated rustc I've ended up having everything rebuilt.

Do you have a sequence of steps which would reproduce this behavior deterministically?

**Comment by alexcrichton** [comment]
I think some refactorings may have fixed a few bugs related to this, but I believe that this is all working as it's supposed to today. Please reopen though if it reproduces!
