### ISSUE TITLE
cargo commands fail to work with `tput reset`

### ISSUE THREAD

**Issue by nikitavoloboev** [rust-lang/cargo#12063]
### Problem

I am trying to make a nice working setup with rust, I wanted to run this

`tput reset && cargo watch -q -x "run -q"`

This should in theory recompile and show result on rust code changes, tput reset should reset the terminal so old results go away but it does not.

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/6391776/235369019-67cd6dd0-ba55-4b32-a0f1-49c0c8cd4add.png">

If I run `watchexec --restart --exts ts "tput reset && bun run $argv"` using [watchexec](https://watchexec.github.io) it works as I want it to. I don't know what is special about `cargo` that is breaking it but I would really love it to be fixed.

Thank you.

p.s. I tried this solution too, it did not work

<img width="838" alt="image" src="https://user-images.githubusercontent.com/6391776/235369043-afc4332c-c023-474e-aead-0d8cee762eb7.png">

### Steps

1. Have a rust program
2. Run `tput reset && cargo watch -q -x "run -q"`
3. Edit rust code, see output of terminal, the output of terminal should clear after every time a rerun happens.
4. It does not do this, it just stacks results on top.

### Possible Solution(s)

Use [watchexec](https://watchexec.github.io) solves this but I would like to use cargo as it probably preserves some cache + other things on reruns.

**Comment by nikitavoloboev** [comment]
Someone on Discord said I could do this:

`cargo watch -q -- sh -c "tput reset && cargo run -q"`

And it works.

Do I lose anything with using this approach? Any cache optimisations on recompiles or something?

Thanks.

**Comment by weihanglo** [comment]
What happens if you run watchexec directly, something like `watchexec --restart --exts rs "tput reset && cargo run -q"`?

**Comment by nikitavoloboev** [comment]
It works too

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/6391776/235370283-794f9ebf-1b1e-4b2d-819f-d515d5904d98.png">

**Comment by weihanglo** [comment]
Okay I see. `cargo-watch` is not a built-in Cargo subcommand but community 3rd-party one. I'd suggest reporting this issue to their issue tracker instead. 

That said, if they find some missing feature Cargo should provide to help them through this, we can open a new issue. 

Thank you for the report anyway!
