### ISSUE TITLE
Build fails on master rust: Unrecognized option: 'print-file-name'

### ISSUE THREAD

**Issue by suhr** [rust-lang/cargo#1206]
Subj:
```
An unknown error occurred
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print-file-name` (status=101)
--- stderr
error: Unrecognized option: 'print-file-name'.
```
Probably it is `--print file-names` now.

**Comment by alexcrichton** [comment]
What version of Cargo are you running?

**Comment by suhr** [comment]
Latest snapshot downloaded by `./configure` (trying to build cargo from git).

**Comment by alexcrichton** [comment]
Ah I see! Right now Cargo builds with a pinned version of the compiler, not the current nightly compiler (see the README for instructions). We'll have to update the snapshot when the compiler is next upgraded.
