### ISSUE TITLE
cargo explain the dependency tree. Why am I downloading this package?

### ISSUE THREAD

**Issue by Kreijstal** [rust-lang/cargo#12075]
### Problem

I am installing a package from pip (jupyterlab) from mingw and I have no idea why it ring is a dependency from it.
The cargo part simply says, downloading *package*, but not why! At least the parent package would be nice!

### Proposed Solution

Print the parent package at the beginning.

### Notes

[kre.txt](https://github.com/rust-lang/cargo/files/11373424/kre.txt)
As you can see it is impossible to figure out why ring is being downloaded. No trace of its parent.

**Comment by epage** [comment]
When directly interacting with a package, you can run `cargo tree` to see the dependency tree of `cargo tree -i ring` to see where the dependency on `ring` comes from

By parent package do you mean what the top-level package is or the direct parent(s) of each package being downloaded and compiled?

If its direct parent(s), then that likely would be taking up a lot of space, obscuring what is happening.  Even for the top-level package, that is a big redundant with other output and we need to be mindful of how much we show.

Granted, you are working through `pip`.  I'm assuming `ring` is coming in via `cryptography`.  Showing direct parents seems meaningless to the Python developer.  Even the top-level Rust package might not be meaningful, but the Python package that caused it to build would.  Between the Python package being more meaningful and being mindful of how much we print, I feel like it'd be better for the build wrapper around cargo to print information than for cargo.

**Comment by epage** [comment]
Looking at the output, it looks like that information is already shown
```
  Building wheels for collected packages: maturin
    Building wheel for maturin (pyproject.toml): started
    Running command Building wheel for maturin (pyproject.toml)
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.mingw_x86_64-cpython-310
    creating build/lib.mingw_x86_64-cpython-310/maturin
    copying maturin/import_hook.py -> build/lib.mingw_x86_64-cpython-310/maturin
    copying maturin/__init__.py -> build/lib.mingw_x86_64-cpython-310/maturin
    copying maturin/__main__.py -> build/lib.mingw_x86_64-cpython-310/maturin
    running egg_info
    creating maturin.egg-info
    writing maturin.egg-info/PKG-INFO
    writing dependency_links to maturin.egg-info/dependency_links.txt
    writing requirements to maturin.egg-info/requires.txt
    writing top-level names to maturin.egg-info/top_level.txt
    writing manifest file 'maturin.egg-info/SOURCES.txt'
    reading manifest file 'maturin.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'license-apache'
    adding license file 'license-mit'
    writing manifest file 'maturin.egg-info/SOURCES.txt'
    running build_ext
    running build_rust
    cargo build --manifest-path Cargo.toml --message-format=json-render-diagnostics --release -v --locked
       Compiling proc-macro2 v1.0.51
        ...
```

**Comment by Kreijstal** [comment]
But maturin does not depend on ring..?

**Comment by epage** [comment]
```console
$ cargo tree -i ring
ring v0.16.20
├── rustls v0.20.8
│   ├── maturin v1.0.0-beta.7 (/home/epage/src/personal/maturin)
│   └── ureq v2.6.2
│       ├── maturin v1.0.0-beta.7 (/home/epage/src/personal/maturin)
│       └── xwin v0.2.12
│           └── cargo-xwin v0.14.2
│               └── maturin v1.0.0-beta.7 (/home/epage/src/personal/maturin)
├── sct v0.7.0
│   └── rustls v0.20.8 (*)
└── webpki v0.22.0
    ├── rustls v0.20.8 (*)
    ├── ureq v2.6.2 (*)
    └── webpki-roots v0.22.6
        └── ureq v2.6.2 (*)
```

**Comment by Kreijstal** [comment]
You're worthy. I apologize for any inconveniences I've caused.
