### ISSUE TITLE
Build scripts being able to provide extra context on errors

### ISSUE THREAD

**Issue by ShadowJonathan** [rust-lang/cargo#12071]
Take the following build error;

```
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `libc` due to previous error
```

For a new user, this might be a bit of a "show stopper", or otherwise a kink/bump in the road for them to get started. Rust already has a bunch of helpful errors, I think it could help if the build script (or any script) is able to "catch" this error, observe it, and possibly provide additional information useful for the user at hand. (f.e. "TIP: You are on a debian OS, installing `build-essential` will provide the relevant files for this build").

This would allow library developers to provide "here, do this to proceed building" instructions for common cases, and/or even try to diagnose tricky cases, or provide extra debug/context information on output of such a build.

**Comment by weihanglo** [comment]
Thanks for the report. However, the error message is subject to how a build script is written. Cargo cannot know in advance what a build script needs to compile. <https://github.com/rust-lang/cargo/issues/11593> is a proposal for displaying message to instruct library users. I think that's a route to resolve this issue. Close in favor of that and other relevant issues listed in <https://github.com/rust-lang/cargo/issues/11593#issuecomment-1386965436>.
