### ISSUE TITLE
Feature Request: Ability to use dependencies as cargo extensions

### ISSUE THREAD

**Issue by octplane** [rust-lang/cargo#1208]
Hello,

Because I think Rust should be also used for websites, I'm trying to build a tool inspired by another build-tool, `sbt`, the Scala build tool. This tool offers a readline console in which you can issue most commands it supports.

One of the commands allows the user to ask `sbt` to rebuild the project every time there is a file change in the project. A similar command can also be used to restart the project after it's been rebuilt.

In order to emulate this behavior, I have successfully released the fsevent library for rust. This is my second released piece of rust (and I'm happy I have managed to handle FFI and Rust together), my first one being a FFI binding to a readline like library...

Now I would like to be able to:

- add a special dependency to my project that will add a subcommand to `cargo` (for example `shell`)
- that when this command is invoked, some of my code is called with the `cargo` environment available,
- so that I would use my FSEvent library to instruct `cargo` to build the project, or clean it, or whatever...

How do you think this should be addressed ? Do you think this is a reasonable idea ? Do you see any other way to achieve the same result without having to modify cargo ?

Thank you for your time...

**Comment by octplane** [comment]
Note that part of the behavior could be implemented using a custom `build.rs` file...

**Comment by alexcrichton** [comment]
This sounds like a pretty great idea to me! I've often wanted a better way to install cargo subcommands. In general we don't deal much currently with the installation of crates, but this would certainly be a nice to have!

**Comment by alexcrichton** [comment]
As in, today we don't deal much with installation, but I'd certainly love to :)

**Comment by octplane** [comment]
How do you think I could help, or I should proceed ? Adding a new Cargo directive ? What's your vision for that ?

**Comment by alexcrichton** [comment]
I haven't really given much thought to the story of `cargo install` and what it might look like. There's been a bunch of issues on the topic, but there's lots of design work to do in order to figure out precisely what it means, what the scope of the command is, etc.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/37 as it's likely how one would install such packages.
