### ISSUE TITLE
cargo update should respect the current toolchain

### ISSUE THREAD

**Issue by nwalfield** [rust-lang/cargo#12106]
### Problem

I work on [Sequoia](https://gitlab.com/sequoia-pgp/sequoia).  We try our best to keep the oldest MSRV possible that doesn't impose too many constraints.  Before doing a release, I run `cargo update` to update our `Cargo.lock` file.  Unfortunately, `cargo update` updates dependencies that are not compatible with our MSRV:

```shell
$ git clone git@gitlab.com:sequoia-pgp/sequoia-sq.git
...
$ rustup default 1.63
info: using existing install for '1.63-x86_64-unknown-linux-gnu'
info: default toolchain set to '1.63-x86_64-unknown-linux-gnu'

  1.63-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

$ rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)
$ cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)
$ grep rust-version Cargo.toml
rust-version = "1.63"
$ cargo update
    Updating crates.io index
...
    Updating assert_cmd v2.0.8 -> v2.0.11
    Updating clap v4.0.32 -> v4.2.7
      Adding clap_builder v4.2.7
    Updating clap_complete v4.0.7 -> v4.2.1
    Updating clap_derive v4.0.21 -> v4.2.0
...
$ CARGO_TARGET_DIR=/tmp/sequoia-sq-build cargo build
error: package `clap_derive v4.2.0` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.63.0
```

I work around this by changing our direct dependencies in `Cargo.toml` to known good versions (e.g., `clap = "=4.0.32"`), and using `cargo update -p PKG --precise VERSION` for indirect dependencies.

It would be nice if `cargo update` would prune versions that are incompatible with a specific version of rustc.  I see a few strategies to figuring our what version to use:

  - Use the currently installed `rustc`'s version
  - Respect `rust-version` as set in the projects `Cargo.toml` file
    - Pro: Helps detect accidental semver bumps (when the MSRV is part of semver)
    - Con: The user or a distribution may prefer to use newer dependencies if they have a newer rustc
  - Allow the user to set it explicitly, e.g., `cargo update --msrv 1.63`. 

Relatedly (I think), `cargo install` has the same issue:

```
$ cargo install sequoia-sq --force
    Updating crates.io index
  Installing sequoia-sq v0.30.0
error: failed to compile `sequoia-sq v0.30.0`, intermediate artifacts can be found at `/tmp/cargo-installmjJedT`

Caused by:
  package `colorchoice v1.0.0` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.63.0
```

But building with `--locked` works fine:

```
$ cargo install sequoia-sq --force --locked
...
    Finished release [optimized + debuginfo] target(s) in 3m 37s
   Replacing /home/us/.cargo/bin/sq
    Replaced package `sequoia-sq v0.30.0` with `sequoia-sq v0.30.0` (executable `sq`)
```

If `cargo install` respected the current `rustc` when computing the dependencies, this would work fine.

### Proposed Solution

`cargo update` prunes dependencies what are incompatible with a version of rustc.

**Comment by epage** [comment]
FYI We are discussing how to expose the MSRV aware resolver to users in #9930.

Closing in favor of that issue.

**Comment by nwalfield** [comment]
Although I spent a fair amount of time looking, I somehow didn't find that issue. Thanks for following up and pointing me to it.
