### ISSUE TITLE
Can't publish from third-party repo package with dependencies to `crates.io`

### ISSUE THREAD

**Issue by PkAIR** [rust-lang/cargo#12105]
### Problem

We have a  self-developed tool to copy package from one repo to `crates.io`. However it's impossible to publish from third party repo cargo package with dependencies hosted on crates.io. Error thrown is `Failed to publish packages: [Dependency `rand` is hosted on another registry. Cross-registry dependencies are not permitted on crates.io.]`

For packages without any dependencies publishing works as expected. 

### Steps

Try to upload package hosted on 3-rd party repo.

Example of `config.toml` file
```
[registries]
space-crates = { index = "sparse+https://3-rd-party-repo-url-here" }

[unstable]
registry-auth = true
```

`Cargo.toml`
```
[package]
name = "cargo_calc"
version = "0.2.2-alpha"
authors = ["..."]
edition = "2021"
rust-version = "1.56"
description = "Simple calculation lib"
documentation = "https://www.github.com/"
readme = "./README.md"
homepage = "https://www.github.com/"
repository = "https://www.github.com/"
license = "MIT"
keywords = ["..."]
categories = ["..."]
exclude = [".idea"]
include = ["/src"]

[dependencies]
random = "0.14.0"
```

`Cargo.lock`
```
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "cargo_calc"
version = "0.2.1-alpha"
dependencies = [
 "random",
]

[[package]]
name = "random"
version = "0.14.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "61c7093a82705b48f10d4b165c6482dbe9f58cd63a870d85537e857b2badbd88"
```

### Possible Solution(s)

Allow publishing packages hosted on 3-rd party repos with dependencies hosted on `crates.io`

### Version

```text
cargo 1.71.0-nightly (de80432f0 2023-04-21)
release: 1.71.0-nightly
commit-hash: de80432f04da61d98dcbbc1572598071718ccfd2
commit-date: 2023-04-21
host: aarch64-apple-darwin
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 7.87.0 (sys:0.4.61+curl-8.0.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Mac OS 13.3.1 [64-bit]
```

**Comment by ehuss** [comment]
It looks like you copied the `Cargo.toml` file twice, and didn't include the `config.toml`.  Can up update it to include that?

Also, can you reproduce with just using cargo and not an external tool?  If not, it sounds like this is an issue with the tool and not cargo.  With the information provided, I don't think we would be able to reproduce.

**Comment by PkAIR** [comment]
Sorry for the late notice. I've updated `config.toml` file however I was unable to reproduce this issue using only cargo. Will try another way of publishing artifacts. Thank you!

**Comment by ehuss** [comment]
Since there isn't a reproduction using cargo, I'm going to close assuming this is related to some external tooling. Thanks!
