### ISSUE TITLE
[Gratitude] cargo bench is amazing, thank you

### ISSUE THREAD

**Issue by digitalstain** [rust-lang/cargo#12113]
Just a quick note to thank you for the work on the bench command. It saves me a lot of trouble developing and maintaining my own harness. It also functions as a common reference for everyone to use, which means i don't need to explain some custom method for running benchmarks and gathering results.

In my view it functions as a base reference for everyone to quickly communicate either ad hoc measurement setups or build results. And it works brilliantly on first use, with simple setup and straightforward results.

Thank you.

**Comment by weihanglo** [comment]
Thanks for the words! There are still rooms to improve for <https://github.com/rust-lang/cargo/labels/Command-bench>. Always open to contributions, and feel free to have a chat with the maintainers [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo)!
