### ISSUE TITLE
crate version mismatch between cargo.toml and cargo.lock

### ISSUE THREAD

**Issue by Mohan6677** [rust-lang/cargo#12129]
### Problem

When i am running `cargo build --release` in one of my projects. Cargo is downloading and compiling latest versions of crates mentioned in cargo.toml instead of the version i specified. so some of the latest crates which are getting downloaded have a msrv of 1.65 but i am using 1.64 because of which i am not able to compile my code and generate a binary. i haven't changes anything in my code recently. i am unable to find the cause behind this behaviour. Any help would be much appreciated!!.

### Version

```text
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.87.0 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 13.3.1 [64-bit]
```

**Comment by epage** [comment]
cargo uses maximal compatible versions by default, rather than minimal compatible versions.

#8539 is for supporting minimal versions.

#9930 is for making the resolver MSRV-aware (hopefully by default)

I believe those capture the concerns mentioned in this issue, so I'm closing in favor of those.  If there is something I missed, let us know!

**Comment by Mohan6677** [comment]
what can i do to strictly generate the binary with exact versions of dependencies i specified in cargo.toml?

**Comment by weihanglo** [comment]
Tracking [`Cargo.lock`](https://doc.rust-lang.org/nightly/cargo/appendix/glossary.html#lock-file) in your version control system is probably the best way I know at this moment.

**Comment by Mohan6677** [comment]
@weihanglo. yes i am not checking in  cargo.lock file. i think that's what caused the issue.
