### ISSUE TITLE
Specification of the "branch = master" in Cargo.toml breaks the build

### ISSUE THREAD

**Issue by vityafx** [rust-lang/cargo#12128]
### Problem

If we have two crates depending on some crate X being a git repository, they should have the dependency:

```toml
[dependencies]
x = { git = "<repo>" }
```
In both crates' `Cargo.toml` files.
By default, the `master` branch is taken, according to the documentation.

However, if one crates decides to explicitly mention the branch name, as in
```toml
[dependencies]
x = { git = "<repo>", branch = "master" }
```

Cargo treats these as two different `x` crates and breaks the symbol compatibility between the two crates: both crates can't work with each other any longer, since they depend on two different crates, even if this is not the case.

In the `Cargo.lock` file one can observe for the first crate:
```
[[package]]
name = "first"
version = "0.1.0"
dependencies = [
  "x 99.99.99 (git+https://github.com/x/x?branch=master)",
```
And for another:
```
[[package]]
name = "second"
version = "0.1.0"
dependencies = [
 "x 99.99.99 (git+https://github.com/x/x)",
```

### Steps

1. Create a workspace with two crates, depending on some other crate `x`.
2. In the first crate, depend on the crate `x` using git and don't specify the branch name.
3. In the second crate, do depend on the crate `x` using git and specify the branch name.
4. Observe the problem that even though the crate `x` is actually the same, as per the documentation, if the branch name is omitted the `master` is taken, and the actual contents are actually the same, the symbols clash and don't merge, the compatibility breaks between the first and the second crates within the same workspace.

### Possible Solution(s)

Either forbid the omission of the branch name or revision or somehow make it work.
Note, that [the documentation says that it should work](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html):
```
Since we haven’t specified any other information, Cargo assumes that we intend to use the latest commit on the main branch to build our package. 
```

### Version

```text
❯ cargo version --verbose
cargo 1.69.0 (6e9a83356 2023-04-12)
release: 1.69.0
commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
commit-date: 2023-04-12
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report and the reproducer! This seems to share the same root cause with #7497 and #11490. We're also tracking changes that need a lockfile version bump in #12120. Close in favor of those :)
