### ISSUE TITLE
Cargo recompiles some crates between `build` and `run`

### ISSUE THREAD

**Issue by sergiimk** [rust-lang/cargo#12134]
### Problem

In a simple sequence of `cargo clean` -> `cargo build` -> `cargo run` the `run` step recompiles some basic crates that trigger a large chain reaction of recompilation.

Expectation: `cargo build` and `cargo run` both produce `dev/debug` builds and should reuse the cache.

<i>// Sorry for another "cargo recompiles ..." issue, but I really did my best to debug it and still don't understand the cause.</i>

### Steps

I tried to create a small repro case, but so far it only happens on my large multi-crate project:
1. `git clone https://github.com/kamu-data/kamu-cli.git && cd kamu-cli`
2. `cargo clean`
3. `RUST_LOG=info cargo build -vv 2> build.log` ([build.log gist](https://gist.github.com/sergiimk/83976bd47acf6f128abdb790d042dca3))
4. `RUST_LOG=info cargo run -vv --bin kamu-cli  -- --version 2> run.log` ([run.log gist](https://gist.github.com/sergiimk/3f0abfa557b7c997c7720c87421a5da3))

### Notes

As you will see in the `run.log` - `semver v1.0.17` is the first one to re-compile.

At first I thought it has something to do with `semver`'s `build.rs` script (that does emit `cargo:rerun-if-changed=build.rs`), but then we have a crate like `winnow` that also recompiles WITHOUT having a build script OR depending on any other previously recompiled crates.

### Version

```text
cargo 1.71.0-nightly (26b73d15a 2023-05-09)
release: 1.71.0-nightly
commit-hash: 26b73d15a68fb94579f6d3590585ec0e9d81d3d5
commit-date: 2023-05-09
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Manjaro 22.1.0 (Talos) [64-bit]
```

**Comment by weihanglo** [comment]
I didn't really look into your workspace layout and feature setup, but I guess it is because the Cargo [feature unification](https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-unification) is a workspace-level stuff. That means when you `build` and `run` might resolve a different set of features. Try this:

```console
cargo build -p kamu-cli
cargo run -p kamu-cli 
```

It shouldn't recompile stuff.

BTW, you should use `CARGO_LOG` instead if you want to read logs from Cargo. See [this FAQ](https://doc.rust-lang.org/nightly/cargo/faq.html#why-is-cargo-rebuilding-my-code) for more.

**Comment by sergiimk** [comment]
@weihanglo Thank you for prompt reply. You are right, with `cargo build -p kamu-cli` it doesn't recompile. 

I guess I'm misunderstanding how workspace feature unification behaves in the case of plain `cargo build` - will need to read up on that.

Appreciate your help - will close this issue now.

**Comment by sergiimk** [comment]
For those who stumble upon this issue - [this article](https://nickb.dev/blog/cargo-workspace-and-the-feature-unification-pitfall/) explains the somewhat non-intuitive behavior of workspace feature unification.

Thinking about this more, I'd expect `cargo run -p binary` to compile and execute a crate with crate-level feature unification, and `cargo run --bin binary` to do workspace-level unification, but they both seem to result in crate-level. 

This seems problematic as I really want to run one binary between my `build` and `test` phases for the entire workspace, but seemingly can't do so without excessive recompilation.
