### ISSUE TITLE
Compiling cargo v0.70.1 as a dependency fails if `panic = "abort"`

### ISSUE THREAD

**Issue by Centri3** [rust-lang/cargo#12132]
### Problem

When specifying cargo as a dependency with `panic = "abort`, and running `cargo build`, running cargo's build script fails.

output:
```
error: failed to run custom build command for `cargo v0.70.1`

Caused by:
  process didn't exit successfully: `C:\Users\centri\GitHub\cargo-panic-repro\target\debug\build\cargo-e2cd261fb353c96a\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `-6`,
   right: `0`', C:\Users\centri\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flate2-1.0.26\src\ffi\c.rs:286:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Doing a bit more digging, `-6` appears to equal `Z_VERSION_ERROR`; this refers to a zlib version mismatch, but this feels off.

It does not appear this is an issue with flate2 rather than cargo - specifying `flate2 = { version = "1.0.3", default-features = false, features = ["zlib"] }` in Cargo.toml (what cargo uses itself) does not reproduce this, only when I compile cargo.

I need `panic = "abort"` since unwinding in ffi is UB. Note that since this specific crate does not revolve around anything ffi, I can create another profile specifically for this but that's a bit of a hacky workaround.

### Steps

1. Run `cargo init`
2. Add this to Cargo.toml:
```
[dependencies]
cargo = "0.70.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
```
3. Compile. For me, this will fail.

### Notes

I'm using cygwin and running ssh, this can cause issues with compiling a select few other libraries but not using either doesn't fix this one.

I cannot reproduce this on Linux, only Windows.

### Version

```text
cargo 1.71.0-nightly (9e586fbd8 2023-04-25)
release: 1.71.0-nightly
commit-hash: 9e586fbd8b931494067144623b76c37d213b1ab6
commit-date: 2023-04-25
host: x86_64-pc-windows-gnu
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Home) [64-bit]
```
```

**Comment by weihanglo** [comment]
I don't have a Windows machine at hand now. Could you try 0.69.0 and 0.70.0 as well? I will really appreciate it if you could also bisect to find the bad commit 🙇🏾

**Comment by Centri3** [comment]
Just tried, the issue arose in 0.48.0

**Comment by Centri3** [comment]
It appears this is also the version when build.rs was added as well.

I could not reproduce this when I copied build.rs to a minimal repro, though compilation did fail but for a different reason (presumably because I didn't have the included man pages). Forcing it to not do this (which doesn't do anything revolving around flate2, I might add) causes it to compile flawlessly.

**Comment by ehuss** [comment]
FWIW, I am unable to reproduce this (at least with mingw). Can you try maybe using a different toolchain, like [mingw-w64](https://www.mingw-w64.org/)? It may be possible that something like pkg-config is picking up a system library for libz or something like that, and the version found isn't compatible, or is miscompiling with the particular C toolchain you have installed.

**Comment by Centri3** [comment]
I'm on mingw, actually. Though it seems I can't reproduce this either now, which is incredibly confusing since I tried this earlier today and still couldn't compile yet, even without any changes (or even an intermediate restart) between the two, I somehow cannot reproduce this anymore. It was entirely transient.

I'll leave this open in case I manage to reproduce this again, I'll then upload a minimal repro, but it seems this is solved(?).

**Comment by Centri3** [comment]
Just reencountered this :/ let me setup a minimal repro.
I upped my nightly toolchain to 2023-05-14 (though 13 is the latest) and it began again.

**Comment by Centri3** [comment]
And just as soon as it came, it went... I cannot reproduce this anymore.
Still, I've decided to upload what I COULD reproduce this on: https://github.com/Centri3/lol

I hope somebody else can reproduce this at least once.

**Comment by ehuss** [comment]
I'm going to close since we don't have a specific reproduction. If you're ever able to figure out what might be the issue, feel free to reopen!
