### ISSUE TITLE
cargo new does not detect author name and email for author field

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/cargo#1213]
```
/tmp$ cargo new --bin hello
/tmp$ cat hello/Cargo.toml 
[package]

name = "hello"
version = "0.0.1"
authors = ["josh"]
```

I have `$NAME`, `$GIT_AUTHOR_NAME`, and `$GIT_COMMITTER_NAME` all set, and likewise for EMAIL.  git knows who I am:

```
/tmp/hello$ git add .
/tmp/hello$ git commit -m 'Initial commit'
[master (root-commit) 51b94a2] Initial commit
 3 files changed, 9 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 Cargo.toml
 create mode 100644 src/main.rs
/tmp/hello$ git log
commit 51b94a2fab5045e4c822684f5450f8ede817c2ad (HEAD, master)
Author: Josh Triplett <josh@joshtriplett.org>
Date:   Fri Jan 23 17:12:20 2015 -0800

    Initial commit
```

**Comment by alexcrichton** [comment]
Aha! I was unaware of `GIT_AUTHOR_NAME` and `GIT_COMMITTER_NAME`. Currently we read `user.email` and `user.name` from `~/.gitconfig` or `cargo-new.name` and `cargo-new.email`.

Should be easy enough to add though!

**Comment by joshtriplett** [comment]
Ideally you don't want to duplicate the logic from git to detect the user's name and email address.  Git reads NAME, GIT_AUTHOR_NAME, GIT_COMMITTER_NAME, and user.name for the name, and EMAIL, GIT_AUTHOR_EMAIL, GIT_COMMITTER_EMAIL, and user.email for the email.  I don't actually know what order they're read in, other than that AUTHOR and COMMITTER are used for the author and committer information, respectively.

**Comment by lfairy** [comment]
`git var GIT_AUTHOR_IDENT` may help:

```
$ GIT_AUTHOR_NAME='Bon Bon' GIT_AUTHOR_EMAIL='bon.bon@example.com' git var GIT_AUTHOR_IDENT
Bon Bon <bon.bon@example.com> 1430212753 +1200
```

**Comment by rasendubi** [comment]
Triage: still an issue.
