### ISSUE TITLE
cargo build --show-out

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/cargo#12141]
### Problem

I'm building a test to debug it with debugger, or copy it to another machine if it is build for another architecture.

Where is the binary?

```
cargo build --tests --verbose
```

does not print the path. There is a lot of paths with hashes in `targets` directory, finding the binary with the latest built test is not easy.

### Proposed Solution

Either:
* print binary paths by default (to stderr, so paths are not machine readable, so this is not API change), or
* add an option `cargo build --show-out`

### Notes

Related to https://github.com/rust-lang/cargo/issues/12140

```
cargo 1.68.0-nightly (d992ab4e9 2023-01-10)
```

**Comment by weihanglo** [comment]
With [`--no-run`](https://doc.rust-lang.org/nightly/cargo/commands/cargo-test.html#option-cargo-test---no-run), Cargo also emits the executable paths for human. For instance,

```console
$ cargo test --no-run
    Finished test [unoptimized + debuginfo] target(s) in 0.46s
  Executable unittests src/cargo/lib.rs (target/debug/deps/cargo-f8c8ae4254239e92)
  Executable tests/build-std/main.rs (target/debug/deps/build_std-de679ea102561ead)
  Executable tests/internal.rs (target/debug/deps/internal-5b3c0fb3a9e0c0d1)
  Executable tests/testsuite/main.rs (target/debug/deps/testsuite-afcbe389bffe84ae)
```

Does it meet your needs?

**Comment by stepancheg** [comment]
It does. TIL, thanks!
