### ISSUE TITLE
"no linkable target" should not warn to become a hard error

### ISSUE THREAD

**Issue by novafacing** [rust-lang/cargo#12155]
### Problem

When compiling a crate that depends on another crate that is `crate-type = ["staticlib"]`, the following warning appears:

```
warning: The package `some_crate` provides no linkable target. The compiler might raise an error while compiling `build_script_build`. Consider adding 'dylib' or 'rlib' to key `crate-type` in `some_crate`'s Cargo.toml. This war
ning might turn into a hard error in the future.
```

This should not threaten to turn into a hard error in the future (and should not turn into a hard error in the future), because there are legitimate reasons to do this.

### Steps

1. `cargo new --lib /tmp/test-lib`
2. `echo -e '[lib]\ncrate-type = ["staticlib"]' >> /tmp/test-lib/Cargo.toml`
3. `cargo new --bin /tmp/test-bin`
4. `cargo add --manifest-path /tmp/test-bin/Cargo.toml --path /tmp/test-lib/`
5. `cargo build --manifest-path /tmp/test-bin/Cargo.toml`

You should see:

```
warning: The package `test_lib` provides no linkable target. The compiler might raise an error while compiling `test_bin`. Consider adding 'dylib' or 'rlib' to key `crate-type` in `test_lib`'s Cargo.toml. This warning might turn into a hard error in the future.
```

### Possible Solution(s)

This warning is ok (it may be intentional, but it is more likely an accident -- it is probably ok to warn and possibly help someone fix their typo), but it should not threaten to become a hard error. The error message should read:

```
warning: The package `test_lib` provides no linkable target. The compiler might raise an error while compiling `test_bin`. Consider adding 'dylib' or 'rlib' to key `crate-type` in `test_lib`'s Cargo.toml if this was not intentional.
```

### Notes

There is a major use case that making this a hard error breaks: custom compilation of `staticlib` crate used as a dependency to add sanitizers (although this applies to other LLVM/rustc options as well).

For example, I need to compile my fuzzing target with `SanitizerCoverage`, so I write a build script like this:

```rust
use std::{env::var, process::Command};

fn main() {
    let status = Command::new("cargo")
        .arg("rustc")
        .arg("-p")
        .arg("first-target")
        .arg("--target-dir")
        .arg("target/first-target/")
        .arg("--")
        .arg("-C")
        .arg(format!(
            "opt-level={}",
            var("OPT_LEVEL").expect("No OPT_LEVEL variable set")
        ))
        .arg("-C")
        .arg("prefer-dynamic")
        .arg("-C")
        .arg("passes=sancov-module")
        .arg("-C")
        .arg("llvm-args=-sanitizer-coverage-level=3")
        .arg("-C")
        .arg("llvm-args=-sanitizer-coverage-inline-8bit-counters")
        .arg("-C")
        .arg("llvm-args=-sanitizer-coverage-prune-blocks=0")
        .arg("-C")
        .arg("link-dead-code")
        .arg("-C")
        .arg("lto=no")
        .arg("--emit=dep-info,link")
        .status()
        .expect("Failed to spawn Cargo");

    assert!(status.success(), "Target build command failed");

    println!("cargo:rustc-link-lib=first_target");
    println!(
        "cargo:rustc-link-search={}/target/first-target/debug/",
        env!("CARGO_MANIFEST_DIR")
    );
}
```

Being able to use `-p` here allows me to avoid doing path magic and requiring that the target crate be in a particular location (I can host it on a private repo, from git, a local path, anywhere a cargo dependency can live), while still being able to compile my fuzzer and link the instrumented harness with `cargo build`.

### Version

```text
cargo 1.69.0 (6e9a83356 2023-04-12)
release: 1.69.0
commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
commit-date: 2023-04-12
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Fedora 38.0.0 [64-bit]
```
```

**Comment by epage** [comment]
The language was originally added in #4797.

The commit message is a little more descriptive than the PR itself

> If a dependency is a library that provides no linkable targets, we warn
> about the impending error in rustc about an unresolvable `extern crate`.
> 
> Fixes https://github.com/rust-lang/cargo/issues/3169.

About the warning, alex commented

> Yeah I don't currently know of a use case of where you'd depend on a cdylib/staticlib via [dependencies]. That being said I've learned time and time again that just because I can't think of something doesn't mean someone else won't!
>
> Maybe we can start with a warning (saying it'll become a hard error if you don't report an issue) and go from there?

So this was something that was left open for discussion

**Comment by epage** [comment]
It sounds like what you will be wanting, long term, is [artifact dependencies](https://doc.rust-lang.org/cargo/reference/unstable.html#artifact-dependencies) and you are currently emulating them.

**Comment by novafacing** [comment]
Yep, I have been tracking artifact dependencies since they were proposed. Of course, it's a long road to stabilization :)

Artifact dependency is the right answer here, I would just like to make sure people are aware that there are legit, non-error reasons for depending on `staticlib` and also make sure that at least for my use case and until artifact dependencies are stabilized, nobody decides to actually go ahead and propose making this an error instead of a warning.

**Comment by epage** [comment]
Looking  back over #4797, I noticed #7825 is already open which sounds like your use case.  Is there something specific to this issue that we need to keep it open vs closing this in favor of #7825?

**Comment by novafacing** [comment]
Whoops, guess I missed that one in my search (probably because I searched for "staticlib"), no I think that issue covers it especially since it now refers here. Thanks!
