### ISSUE TITLE
dependency on a local workspace crate requires full crates path instead of just workspace root

### ISSUE THREAD

**Issue by softstream-link** [rust-lang/cargo#12161]
### Problem

```
project_a
   Cargo.toml # workspace
   crate_1
      Cargo.toml 
   crate_2
      Cargo.toml
 ```

```
project_b
   Cargo.toml
      [dependencies]
      crate_1 = { path = "../project_a/crate_1" }  # Why does this work
      vs
      crate_1 = { path = "../project_a/" }  # And this DOES Not
```

**Comment by weihanglo** [comment]
Hi! Workspaces cannot recognize each other's member as of now. I'd like to learn the rationale behind why you want to achieve that and how it could be better if Cargo supports that. We have been collecting some real world nested workspace needs for a while. This sounds like a thing the nested workspace feature can resolve. Close in favor of <https://github.com/rust-lang/cargo/issues/5042>, and feel free to provide feedback!

**Comment by weihanglo** [comment]
BTW, there is a draft proposal for nested workspaces still brewing: <https://hackmd.io/AWv4c8dUT9ahWEo4epNG4g>.
