### ISSUE TITLE
Running 'cargo -h' does not display the clippy subcommand.

### ISSUE THREAD

**Issue by cpcgskill** [rust-lang/cargo#12164]
### Problem

I tried this code:

```
cargo -h
```

I expected to see this happen: 
```
...
Some common cargo commands are (see all commands with --list):
    build, b    Compile the current package
    check, c    Analyze the current package and report errors, but don't build object files
    clean       Remove the target directory
    clippy      <An introduction to the clippy command>
...
```

Instead, this happened: 
```
...
Some common cargo commands are (see all commands with --list):
    build, b    Compile the current package
    check, c    Analyze the current package and report errors, but don't build object files
    clean       Remove the target directory
...
```

### Steps

in windows, run 'cargo -h'.

### Possible Solution(s)

I believe you should be able to add the description directly at this link:[https://github.com/rust-lang/cargo/blob/a6c0d43787269d48510c0a4e8acf2207790a6daa/src/bin/cargo/cli.rs#LL465C9-L465C9](https://github.com/rust-lang/cargo/blob/a6c0d43787269d48510c0a4e8acf2207790a6daa/src/bin/cargo/cli.rs#LL465C9-L465C9).

### Version

```text
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-pc-windows-msvc
release: 1.69.0
LLVM version: 15.0.7
```

**Comment by weihanglo** [comment]
Thanks for the report! 

Although `cargo-clippy` is an official external command, it doesn't always come with Cargo if you installed Rust via [rustup](https://rustup.rs/). If you choose [`minimal` profile](https://rust-lang.github.io/rustup/concepts/profiles.html) when downloading a toolchain, it won't contain `cargo-clippy` nor `cargo-fmt` component. I guess that was one of the reason that it's intentionally not included in the `cargo -h` help manual. 

When you run `cargo +1.69.0 --list | grep clippy` to see a full list of commands, `cargo clippy` should still be there. This keeps short help manual concise — if people want more info they always have a way to do so.

**Comment by cpcgskill** [comment]
thank you very much, I see!
