### ISSUE TITLE
Configure cargo building by current host machine spec

### ISSUE THREAD

**Issue by Kovalit31** [rust-lang/cargo#12179]
### Problem

Linker (ld, link.exe and so one) arguments for building bare metal program (x86_64) is depending on current machine running os (windows - "/ENTRY:_start", linux - (link-args=-nostartfiles) and so one)
I can't solve this problem myself at all. So I need for your help or additional feature in cargo

### Proposed Solution

Add cfg(host_os), cfg(host_arch) support for Cargo

**Comment by weihanglo** [comment]
It would be great if you can provide more contexts, such as

- What exactly you're trying to resolve. A concrete example and links are great.
- Why the feature should be a built-in feature of Cargo. Any possible workaround exists?
- This also seems to be a bug, no? If so, please attach the version info.

A well-written would help not only maintainers but other random contributors to come up with better ideas.

**Comment by Kovalit31** [comment]
At current time, i've resolved problem.
It was a bug with other contributor guide's instructions (https://os.phil-opp.com/freestanding-rust-binary/#unifying-the-build-commands).
Also, this bug currently is tracking by another issue with per-package .cargo/config.toml and this may be configured by build script (build.rs).
Sorry about inconsistence.
P.S. I haven't found any other workarounds (like xbuild or something else), what will support this thing.
