### ISSUE TITLE
build scripts with exit code 256 are considered successful

### ISSUE THREAD

**Issue by OmarTawfik** [rust-lang/cargo#12170]
### Problem

For this example crate:

### `build.rs`

```rust
fn main() {
    std::process::exit(0);
}
```

### `src/main.rs`

```rust
fn main() {
    println!("SUCCESS");
}
```

### Steps

If I set exit code to `std::process::exit(0)`, the program compiles and runs successfully:

```log
SUCCESS
```

If I set exit code to `std::process::exit(1)`, the build fails as expected:

```log
Caused by:
  process didn't exit successfully: `target/debug/build/app-fe47b5cc6fa9e381/build-script-build` (exit status: 1)
```

If I set exit code to `std::process::exit(256)`, the build succeeds instead of failing:

```log
SUCCESS
```

### Possible Solution(s)

This caused a really hard to track issue in our build system, as our build scripts exit with the number of errors found during internal validation `std::process:exit(count)`.

Short term fix is to always exit with code `1` for now, but I would like to use the exit code to inform callers of the error count. Thoughts?

### Version

```text
cargo 1.69.0 (6e9a83356 2023-04-12)
```

**Comment by epage** [comment]
This is likely not a problem with build scripts but with how Unix-like systems handle exit codes: [they are 8-bit, making 256 turn into 0](https://doc.rust-lang.org/std/process/fn.exit.html#platform-specific-behavior).  For this reason, returning the number of failures is not generally a good idea.

**Comment by wesdgray** [comment]
This might be related to `std::process::exit` platform specific behavior outlined here https://doc.rust-lang.org/std/process/fn.exit.html#platform-specific-behavior:

> For example, the exit code for this example will be 0 on Linux, but 256 on Windows:
```
use std::process;

process::exit(0x0100);
```

**Comment by OmarTawfik** [comment]
Thanks for the information. Is there anything we can do to detect such cases (from Cargo itself)? if the extra bits are still visible to the calling process.

**Comment by weihanglo** [comment]
Agree with epage. It is not a good practice returning an arbitrary exit code. From [GNU libc manual](https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html):

> A general convention reserves status values 128 and up for special purposes. In particular, the value 128 is used to indicate failure to execute another program in a subprocess. This convention is not universally obeyed, but it is a good idea to follow it in your programs.
>
> **Warning:** Don’t try to use the number of errors as the exit status. This is actually not very useful; a parent process would generally not care how many errors occurred. Worse than that, it does not work, because the status value is truncated to eight bits. Thus, if the program tried to report 256 errors, the parent would receive a report of 0 errors—that is, success. 

My take is avoiding such cases and leave the behavior as-is.

**Comment by ehuss** [comment]
I'm going to close as there is nothing cargo can do here. This might be something that would be good for Rust's standard library to support, but that is something that should be filed at https://github.com/rust-lang/rust/issues. It looks like `waitid` is what would be needed, but I am not clear how widespread that is supported, and whether that would require an extension trait or any other sort of considerations.

**Comment by OmarTawfik** [comment]
I see. thank you for the information and links.
Let's close in that case.
