### ISSUE TITLE
Transition out implicit features for optional dependencies

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#12173]
### Problem

Today cargo will implicitly create a feature for optional dependencies unless the dependency is referenced in a feature as `dep:<dep_name>`.

Downsides
- People overlook using `dep:` and unintentionally create features
  - Exposing implementation details in their public API
  - Confusing users on which features to activate (#9459)
- Remove the need for people to special case this (e.g. #10543)
- Avoid mistakes with explicitly creating the feature (#10125)

### Proposed Solution

We should stop implicitly creating features in a new Edition

Optional dependencies without a `dep:` reference can be either
- A hard error
- Allowed assuming people will then want to use it via the future `#[cfg(accessible)]`
  - The downside is users might assume a feature would exist (at first) and things not work as expected
  - We could start with an error and move away from it
- Create private features (#10882, see also #1596)

`cargo add foo --optional` can implicitly create a feature with the dependency's name, if a `dep:foo` doesn't already exist (#11010).

**Comment by epage** [comment]
See also #9088

**Comment by epage** [comment]
The main hurdle for transitioning is that #12130 was just barely merged though there is the workaround of `"dep:foo", "foo?/feat"` which would be the standard way of doing it with #10556.

**Comment by ehuss** [comment]
@epage Do you want to keep this issue open?

**Comment by epage** [comment]
If this were about a specific use case then I might want to keep it open but since its effectively "lets make an RFC", lets close it out.
