### ISSUE TITLE
Expose the Path of Cargo.toml in `cargo-metadata` output

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/cargo#12187]
### Problem

There are a few cases in tooling (I am thinking of cases primarily inside of rust-analyzer, but I'm sure there are others) where it'd be very helpful to deterministically determine the crate's root folder (e.g., the folder containing `Cargo.toml`) in order to present the crate in a meaningful and idiomatic fashion _and without_ resorting to approximations like "search parent folders of the crate root for a Cargo.toml".

For context, both Buck2 and Bazel—which don't enforce structures on the crates that they build—both allow the user to query the build system to determine the file that defines the build target.

### Proposed Solution

When emitting the crate root (the Rust file, not the Cargo.toml!), `cargo-metadata` should _also_ emit the absolute path of the Cargo.toml that defines the crate. In the case of a Cargo workspace, I'd guess that the output should *also* return the Cargo.toml that defines Cargo workspace if the crate is not downloaded from crates.io.

(I assume this information already exists within Cargo, but it's not exposed and hasn't been asked for before, which is why I didn't see an issue for this request.)

### Notes

I'd be happy to add this feature to Cargo's metadata output.

**Comment by epage** [comment]
Could you clarify what you are looking for.  For example, `cargo metadata` includes a [Package::manifest_path](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Package.html#structfield.manifest_path) field but I assume you saw that, so I'm trying to understand what is still missing.

**Comment by davidbarsky** [comment]
> Could you clarify what you are looking for. For example, `cargo metadata` includes a [Package::manifest_path](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Package.html#structfield.manifest_path) field but I assume you saw that, so I'm trying to understand what is still missing.

That's very generous of you to assume that I saw `Package::manifest_path`, but I unfortunately did not! I completely missed its existence—that's exactly what I'm looking for. My apologies for the noise; I'll close this issue.
