### ISSUE TITLE
perhaps an -L flag is missing? error doesn't print -L flags given or any other info

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#1219]
I keep running into this problem:
1. I write a build script that seems to work fine (no panics) and outputs `-L` flags that I hope are correct
2. Something isn't right and Cargo tells me 
   
   > error: could not find native static library `foo`, perhaps an -L flag is missing?

To me information printed by Cargo, even in verbose mode, is insufficient to diagnose the problem.
- Cargo doesn't tell me if it got any -L flags at all. 
  I could try to guess if it got flags by searching the long noisy " Running `rustc…`" lines, but the paths are usually based on random-looking expansion of `OUT_DIR` (e.g. I see different hash in paths when I add `panic!()` to my script and I don't know if that's normal), so I don't really know what paths I'm looking at. Due to #1106 it's a pain to find that out.
- Cargo doesn't tell me what files it expected to find.

It would be so much nicer if Cargo had message such as:

> Can't link native library `foo` wanted by `foo-sys`. Expected to find `libfoo.so` in these directories:
> - `/foo/lib` (set by `foo/build.rs`) (this directory doesn't exist)
> - `/usr/lib/bar` (set by `bar.sh`) (found `libfoo.a`, but not `libfoo.so`)

**Comment by alexcrichton** [comment]
I don't think that we'll get to quite that level of fidelity with an error message because this error is being generated by the compiler, not by Cargo itself, but I'd believe that it could certainly improve!

**Comment by m13253** [comment]
I think it is important to break the glass to see what's happening inside.

Sometimes the first step goes (falsely) successful, but it caused later steps to fail.
The error report mechanism is not always smart to find out the direct cause of the error (or debuggers would retire).

So, debugging the whole build process need to be possible.
For example, add a logging mode to print as much as information (command lines, environments, inputs/outputs) during each step.
Or a way to invoke GDB to debug the build script.

**Comment by pornel** [comment]
GDB in Rust part of the build script wouldn't help me much, since my Rust build scripts are:

```rust
fn main() {
    if !std::io::Command::new("./src/build.sh")
        .stdout(::std::io::process::InheritFd(1))
        .stderr(::std::io::process::InheritFd(2))
        .status().unwrap().success() {
        panic!("Script failed");
    }
}
```

**Comment by m13253** [comment]
But I'm sorry to say that Cargo eat up all std{in,out,err}. (#1106)
So it is no use doing `InheritFd`.

I saw you discussing on #1106 .
But I need more reasons to prove the significance of not eating stderr with --verbose.

**Comment by pornel** [comment]
> But I need more reasons to prove the significance of not eating stderr with --verbose.

But what is the reason _for_ eating it? So far I've seen "it looks clean!". So to me it's

* Pro: it looks neat!
* Con: I can't develop working Cargo packages!

I feel like Cargo is highly "opinionated" and its opinions completely don't match mine. On every step I'm fighting around it :(

I want to use "printf debugging", without stopping the program, since it's easy and works with entire toolchain that I'm using. I can't imagine how could I possibly use GDB to debug the mountain of crap scripts that autotools spits out. 

Since pure Rust build scripts are supposed to be the right way, I've tried that. I gave up after my 4-line bash script started to exceed 100 lines.

**Comment by m13253** [comment]
> I want to use "printf debugging", without stopping the program, since it's easy and works with entire toolchain that I'm using. I can't imagine how could I possibly use GDB to debug the mountain of crap scripts that autotools spits out.

You can achieve your goal by:

1. Start an XTerm to print out things (or AllocConsole on Windows). But this degrades user experiences.

2. Write to `/proc/$PARENT_PID/fd/2` as stderr (or OpenProcess + DuplicateHandle combination on Windows). This tweak works perfectly as no restrictions are there.

Maybe we can make a helper library to do what we want to do without modifying Cargo.

**Comment by pornel** [comment]
Uhhh… I'm telling you that Cargo is hard to use, opaque and hostile to newcommers, and you're showing me even more complex and elaborate workarounds :(

**Comment by alexcrichton** [comment]
@pornel you may want to weigh in on https://github.com/rust-lang/cargo/issues/1106 to see some various tradeoffs when dealing with the output of build scripts.

**Comment by pornel** [comment]
@alexcrichton I've done that: https://github.com/rust-lang/cargo/issues/1106#issuecomment-71251619

**Comment by alexcrichton** [comment]
Gah sorry! Thanks for weighing in though :)
