### ISSUE TITLE
0.71.0 tag missing

### ISSUE THREAD

**Issue by tranzystorek-io** [rust-lang/cargo#12216]
### Problem

The `0.71.0` tag seems to be missing. This obstructs version bump for the Void Linux Rust package.

**Comment by weihanglo** [comment]
Thanks and please be patient. Release team will work on it. See <https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/1.2E70.2E0/near/362858537>.

There is an automation plan <https://github.com/rust-lang/cargo/issues/11345#issuecomment-1304851662>, though not sure how's it going.

**Comment by weihanglo** [comment]
[Tagged](<https://github.com/rust-lang/cargo/releases/tag/0.71.0>). Kudos to [T-release](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/meeting.202023.2006.2002/near/363301351)!

Close as resolved.
