### ISSUE TITLE
Cargo should strip features of dev dependencies

### ISSUE THREAD

**Issue by Morganamilo** [rust-lang/cargo#12225]
### Problem

https://github.com/rust-lang/cargo/pull/7333 added stripping of dependencies, but did not strip features pointing to those dependencies.

This causes a rather unintuitive error where cargo says the dependency does not exist. Which one would only understand if they knew about the stripping that cargo does.

### Proposed Solution

Cargo should also strip these features from the manifest before publishing.

If `foo` is a dev-dependency being stripping then `a = ["foo/a"]` should be transformed to `a = []`.

**Comment by eval-exec** [comment]
Hello, I submitted a PR to fix this。 Would you kindly review my PR and provide your feedback? :heart_decoration:

**Comment by linyihai** [comment]
@rustbot claim

I'm going to try, and if I haven't moved for a long time, feel free to pick it up and continue.
