### ISSUE TITLE
`split-debuginfo` documentation contradiction

### ISSUE THREAD

**Issue by Meadowsys** [rust-lang/cargo#12243]
On [`rustc` documentation](https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo), it says that `split-debuginfo` is `packed` by default. On [`cargo` documentation](https://doc.rust-lang.org/cargo/reference/profiles.html#split-debuginfo), it says that `split-debuginfo` is `unpacked` by default. Is this an accidental contradition or one of them was left outdated, or is there something that I am missing on it?

**Comment by weihanglo** [comment]
Transferred to rust-lang/cargo so it won't be lost in the future.

I think it's good to have a one line notice at the end of [this section](https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#split-debuginfo). Perhaps something like

> Note that Cargo and rustc might have differents defaults for `split-debuginfo`. This is preserved for Cargo to experiment on different combination of flags, for providing better debugging and developer experience.

@rustbot label +S-accepted +E-easy +C-bug +A-documenting-cargo-itself +A-profile -T-cargo
