### ISSUE TITLE
Transient Linker Mangling

### ISSUE THREAD

**Issue by DrewRidley** [rust-lang/cargo#12250]
### Problem

Hey all,

I am trying to statically link a library and have been struggling to do so for nearly a week :( 
In the past few days I have been making the most grounds, but am at another standstill due to some behavior which is really not obvious and quite confusing to me.

In my FFI crate, there were quite a few linker arguments that were required. I managed to wrangle in the arguments to the point that the FFI crate builds, and a unit test that uses the exported functions works as expected.

Unfortunately, the excitement was short lived and I was greeted by a linker error when I tried writing a crate that depended on the (functional) FFI crate. Messing around with linker arguments for the past day or so, I have been oscillating between link errors or undefined behavior and segmentation faults. Normally I would point fingers directly at the linker since it has been giving me the most troubles, but that would not explain why I am able to compile the FFI crate and test it with zero undefined behavior/linker errors. 

### Steps

I am not really sure on a concrete method to reproduce at this time, because I still don't fully understand the problem. It seems to specifically be an issue with my architecture (M1 mac). I can happily provide the exact script used to reproduce, but it involves some additional build steps and compilation that might complicate the matter.

```rust
       if output.success() {
            
            let output_dir = bepuvy_base.to_owned() + "/bin/" + (if debug {
                "Debug"
            } else {
                "Release"
            }) + "/net8.0/" + arch + "/publish";

            println!("cargo:rustc-link-search={}", output_dir);
            println!("cargo:rustc-link-lib=static:+verbatim=Bepuvy.a");

            let required_libs = [
                "libbootstrapperdll.a",
                "libRuntime.WorkstationGC.a",
                "libstdc++compat.a",
                "libeventpipe-disabled.a",
                "libSystem.Native.a",
                "libSystem.IO.Compression.Native.a",
                "libSystem.Globalization.Native.a",
                "libSystem.Net.Security.Native.a",
                "libSystem.Security.Cryptography.Native.OpenSsl.a",
            ];

            //Search in the AOT base folder...
            println!("cargo:rustc-link-search={}/sdk", aot_base);
            println!("cargo:rustc-link-search={}/framework", aot_base);

            for lib_name in required_libs {
                println!("cargo:rustc-link-lib=static:+verbatim={}", lib_name);
                
            }

            println!("cargo:rustc-link-arg=-ldl");
            println!("cargo:rustc-link-arg=-lm");
            println!("cargo:rustc-link-args=-Wl,-u,_NativeAOT_StaticInitialization");
            
            println!("cargo:rustc-link-arg=-Wl,-no_fixup_chains");
            
            println!("cargo:rustc-link-arg=-framework");
            println!("cargo:rustc-link-arg=Foundation");

    }
    else {
        panic!("Failed to build with NativeAOT: {}", output);
    }
```

Here is my build.rs script linking ``Bepuvy.a``. What I can't piece together is why this not only compiles, but successfully runs with no UB. When moving over to a different crate that depends on this one, I get a linker error:

```
" "-lm" "-Wl,-no_fixup_chains" "-framework" "Foundation"
  = note: ld: library not found for -lBepuvy.a
          clang: error: linker command failed with exit code 1 (use -v to see invocation
```

What is even more puzzling is that the full output of arguments to ``ld`` does include this ``.a`` file and the file still exists!?

### Possible Solution(s)

I guess in short, I was hoping that by posting this here on this issues page, someone with more experience with how cargo handles and passes around linker arguments might be able to help me. I have consistently been able to get the library working within a single crate, but the behavior is not consistent, stable or safe when brought to a dependent library.

### Version

```text
cargo 1.72.0-nightly (f7b95e316 2023-05-30)
```

**Comment by DrewRidley** [comment]
```

error: could not compile `bepuvy-sys` (lib) due to previous error
drewridley@drews-mbp bepuvy_test % 
drewridley@drews-mbp bepuvy_test % cargo build
   Compiling bepuvy-sys v0.1.0 (/Users/drewridley/Documents/Projects/bepuvy-sys)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/drewridley/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/drewridley/Library/pnpm:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/drewridley/.cargo/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-Wl,-exported_symbols_list,/var/folders/z5/qk5mxlnx3bq2yhc9jrf6nk8w0000gn/T/rustcgCdGxN/list" "-arch" "arm64" "/var/folders/z5/qk5mxlnx3bq2yhc9jrf6nk8w0000gn/T/rustcgCdGxN/symbols.o" "/Users/drewridley/Documents/Projects/bepuvy_test/target/debug/deps/bepuvy_sys.1cza2bge2fsi33qh.rcgu.o" "/Users/drewridley/Documents/Projects/bepuvy_test/target/debug/deps/bepuvy_sys.1o4fe7cw1aeqvq9d.rcgu.o" "/Users/drewridley/Documents/Projects/bepuvy_test/target/debug/deps/bepuvy_sys.ch4h84w1sfo10uk.rcgu.o" "/Users/drewridley/Documents/Projects/bepuvy_test/target/debug/deps/bepuvy_sys.u3zkgqf3a757o02.rcgu.o" "/Users/drewridley/Documents/Projects/bepuvy_test/target/debug/deps/bepuvy_sys.24nx4j7mr08v3vf8.rcgu.rmeta" "-L" "/Users/drewridley/Documents/Projects/bepuvy_test/target/debug/deps" "-L" "/users/drewridley/RiderProjects/Bepuvy/Bepuvy/bin/Debug/net8.0/osx.13-arm64/publish" "-L" "/users/drewridley/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/8.0.0-preview.6.23309.7/sdk" "-L" "/users/drewridley/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/8.0.0-preview.6.23309.7/framework" "-L" "/Users/drewridley/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-lBepuvy.a" "-llibbootstrapperdll.a" "-llibRuntime.WorkstationGC.a" "-llibstdc++compat.a" "-llibeventpipe-disabled.a" "-llibSystem.Native.a" "-llibSystem.IO.Compression.Native.a" "-llibSystem.Globalization.Native.a" "-llibSystem.Net.Security.Native.a" "-llibSystem.Security.Cryptography.Native.OpenSsl.a" "-L" "/Users/drewridley/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-lstd-cf18d152fce14205" "/Users/drewridley/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-d1be01496bebb995.rlib" "-lSystem" "-lc" "-lm" "-L" "/Users/drewridley/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/drewridley/Documents/Projects/bepuvy_test/target/debug/deps/libbepuvy_sys.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs" "-ldl" "-lm" "-Wl,-no_fixup_chains" "-framework" "Foundation"
  = note: ld: library not found for -lBepuvy.a
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

theres the full output of the second crate compilation. Notice how the ``verbatim`` linker argument is transiently changed to be ``"-lBepuvy.a"``

**Comment by DrewRidley** [comment]
I just spent another couple hours researching, and heres what I concluded.

I managed to get the unit test in my original FFI crate to work as highlighted above, but am still unable to get my second external crate to link properly. I always seem to get it to compile with UB. I noticed that if I removed ``verbatim`` from the link lib name, it will begin to attempt to link, but it incorrectly assumes that it is a dylib. If I attempt to add ``static`` to the name, it produces UB because the symbols aren't linked.

I would consider this a fairly pressing issue because it may lead to completely unexpected, extremely hard to reproduce UB.

**Comment by weihanglo** [comment]
Can you try only `Bepuvy` without the `.a` extension? Something like `cargo:rustc-link-lib=static:+verbatim=Bepuvy`.

**Comment by weihanglo** [comment]
Was hoping the issue author to give <https://github.com/rust-lang/cargo/issues/12250#issuecomment-1590978953> a try, but never heard back. Going to close this due to inactivity. Feel free to reopen with an MRE if it turns out that <https://github.com/rust-lang/cargo/issues/12250#issuecomment-1590978953> doesn't solve the issue.

**Comment by DrewRidley** [comment]
I apologize for not replying sooner. I managed to resolve the issue following the above steps. The issue was related to NativeAOT's prior requirement to have a unused symbol present in the final binary. Cargo or rustc itself was stripping these symbols, even though they were explicitly declared.

Afaik in newer versions of NativeAOT this is no longer a problem.
