### ISSUE TITLE
cargo vendor modifies the package cache without locking

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/cargo#12254]
We are getting occasional, but infrequent, failures in our CI which uses `cargo vendor`. Looking into it, it seems that this could be due to https://github.com/alexcrichton/cargo-vendor/pull/131, where `cargo vendor` will delete downloaded crates in the package cache, even though those crates could be concurrently used by other build processes.

This is done without holding the package cache lock, but even if it did I'm not sure this is correct since other cargo commands will read from the package cache (e.g. `cargo build` will read the code from extracted crates) without holding the package cache lock.

**Comment by weihanglo** [comment]
I think your observation is correct. This line does delete sources from cargo glocal package source cache.

https://github.com/rust-lang/cargo/blob/928b9561c16e73fca6206b42e4c464b80b0e9221/src/cargo/ops/vendor.rs#L138

> This is done without holding the package cache lock, but even if it did I'm not sure this is correct since other cargo commands will read from the package cache (e.g. `cargo build` will read the code from extracted crates) without holding the package cache lock.

I think the suggested approach is pretty much doable, and my impression is that during the dependency resolution `cargo build` also need to acquire package-cache lock. May be as easy as [putting a line above here](https://github.com/rust-lang/cargo/blob/56bb8c49db1b99fed671700b48ffa696d3a9655f/src/cargo/ops/vendor.rs#L116) to acquire the package cache lock. Just the heavy-hammer approach for removing-then-redownloading is still a bit uncomfortable to me in terms of performance.

---

triage:

@rustbot label +C-bug +Command-vendor +S-accepted +E-easy

**Comment by weihanglo** [comment]
`cargo build` is already acquiring the package cache lock if I rememeber correctly. It isn't? 🤔

**Comment by Amanieu** [comment]
Only for dependency resolution and downloading crates, not during the actual build itself. However it still needs to read the crate source code from the package cache during the build.

**Comment by weihanglo** [comment]
> However it still needs to read the crate source code from the package cache during the build.

That's what I was saying. `cargo build` gets the lock for reading.

> I think the best way forward might be to just revert https://github.com/alexcrichton/cargo-vendor/pull/131.

The bad news is that `~/.cargo/registry/src` [is not readonly](https://github.com/rust-lang/cargo/issues/9455) at this moment. If we want to make sure the integrity a bit, we might be better starting over from unpacking. It also sounds safer to me to get the advisory lock every time when reading source code from package cache. Otherwise we'll still have a chance that other process gets the lock and modify stuff during our reading.

**Comment by Amanieu** [comment]
This turns out to be more complicated than I expected: the package cache lock is a recursive lock and OSes don't like it when you acquire both a read and write lock on the same file.

I still think the best way forward is to revert https://github.com/alexcrichton/cargo-vendor/pull/131: we should never be modifying code for extracted crates.

**Comment by weihanglo** [comment]
> I still think the best way forward is to revert [alexcrichton/cargo-vendor#131](https://github.com/alexcrichton/cargo-vendor/pull/131): we should never be modifying code for extracted crates.

I personally like this idea. However I was not there and have no idea what would happen after doing so. Let's label this as `S-needs-design` to have someone explore to investigate it a bit.

@rustbot label +S-needs-design -S-accepted

**Comment by hi-rustin** [comment]
I think if we revert it then we would have this kind of issue again. https://github.com/rust-lang/cargo/issues/5956

But I also agree with `we should never be modifying code for extracted crates.`
