### ISSUE TITLE
Start running tests from last failed ones

### ISSUE THREAD

**Issue by whiteand** [rust-lang/cargo#12263]
### Problem

When I run `cargo test`  it is possible that several different tests are failed. And rerunning all tests after some fix can be time consuming. Because all not failed tests are rerun. 

### Proposed Solution

To somehow cache which tests were failed previously and start execution of next `cargo test` from failed ones. Something like in [jest](https://jestjs.io/blog/2016/10/03/jest-16#upgraded-cli)

**Comment by epage** [comment]
I believe this is a subset of #6266

**Comment by ehuss** [comment]
This sounds like a duplicate of #10673 to me?

**Comment by whiteand** [comment]
@epage You are right, I will closed thsi issue

**Comment by whiteand** [comment]
This is a duplicate of #6266. And the described problem can also be fixed if #10673 will be implemented.
