### ISSUE TITLE
Can't download any crate

### ISSUE THREAD

**Issue by MikeGreatLedger** [rust-lang/cargo#12273]
### Problem

[35] SSL connect error (schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.)

### Steps

1. cargo install crate_name

### Possible Solution(s)

This doesn't help:

1. Adding [http] check-revoke = false into cargo.toml in the project folder
2. Adding [env] CARGO_HTTP_CHECK_REVOKE = false in addition to [http] check-revoke = false into cargo.toml in the project folder
3. Adding only [env] CARGO_HTTP_CHECK_REVOKE = false into cargo.toml in the project folder
4. Adding [http] check-revoke = false into config (no extention) file in the users/username/.cargo folder
5. Adding [http] check-revoke = false into config.toml file in the users/username/.cargo folder
6. Adding [env] CARGO_HTTP_CHECK_REVOKE = false into config (no extention) file in the users/username/.cargo folder
7. Adding [env] CARGO_HTTP_CHECK_REVOKE = false into config.toml file in the users/username/.cargo folder
8. Adding both [http] and [env] into config.toml file or config w/o extention in the users/username/.cargo folder
9. rustup update
10. changing curl.exe path
11. to use proxy

Firewall/antivirus are disabled

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-pc-windows-msvc
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 6.1.7601 (Windows 7 Ultimate) [64-bit]
```

**Comment by weihanglo** [comment]
Copied from this <https://github.com/rust-lang/cargo/issues/11344#issuecomment-1345637248>:

> …this is a duplicate of https://github.com/rust-lang/cargo/issues/8688 and https://github.com/rust-lang/cargo/issues/7104. Windows, unlike all other platforms, defaults to checking for TLS revocation certificates. We have considered disabling that on Windows, but have not followed through. This might also be resolved if crates.io leaves Heroku and switches to a service that supports OCSP stapling.

I am also going to close. Thanks for the report anyway.

**Comment by weihanglo** [comment]
See <https://github.com/rust-lang/cargo/issues/12296#issuecomment-1632210190> for the possible fix.
