### ISSUE TITLE
No Internet Access development?

### ISSUE THREAD

**Issue by Jojoshua** [rust-lang/cargo#1229]
Here is the scenario.

I do development on Network-A which is fairly open and has intenet access. I am able to cargo build fine. Next, I need to move the code to Network-B for real testing and possible tweaks. Network-B is completely closed off and has no internet access. Is cargo build going to work after I move it to Network-B?

Note: It is very difficult to get things approved on Network-B so I would need to know before even trying.

**Comment by steveklabnik** [comment]
If you also have a copy of `~/.cargo`, and a `Cargo.lock` yes.

**Comment by alexcrichton** [comment]
Yes, as @steveklabnik mentioned this should certainly be possible! Running `cargo fetch` on Network-A and then developing on Network-B should do the trick!
