### ISSUE TITLE
cargo init - check .gitignore before appending /target

### ISSUE THREAD

**Issue by Mirch** [rust-lang/cargo#12306]
### Problem

When running `cargo init` in an existing git repository, cargo adds a `/target` line to `.gitignore`, regardless of whether that line is already present.

### Proposed Solution

After checking if the `.gitignore` file exists, scan the lines to search for a `/target`, `target/` or `*/taget` line. 

### Notes

`cargo -vV` output:

```
cargo 1.68.0 (115f34552 2023-02-26)
release: 1.68.0
commit-hash: 115f34552518a2f9b96d740192addbac1271e7e6
commit-date: 2023-02-26
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.79.1 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.5.1 [64-bit]
```

**Comment by weihanglo** [comment]
What version did you use having that issue? Having an output of `cargo -vV` attached here would be nice for us to track the issue.

The feature exists from 1.33 via <https://github.com/rust-lang/cargo/pull/6521>  so far I can tell. The function [`format_existing`](https://github.com/rust-lang/cargo/blob/5febbe5587b74108165f748e79a4f8badbdf5e0e/src/cargo/ops/cargo_new.rs#L617
) does the job.

There is also a snapshot test to verify the behavior. The input is:

https://github.com/rust-lang/cargo/blob/5febbe5587b74108165f748e79a4f8badbdf5e0e/tests/testsuite/init/simple_git_ignore_exists/in/.gitignore#L1-L2

And output be like:

https://github.com/rust-lang/cargo/blob/5febbe5587b74108165f748e79a4f8badbdf5e0e/tests/testsuite/init/simple_git_ignore_exists/out/.gitignore#L1-L9

So it looks like the issue shouldn't happen. I wonder if the entry of your `/target` have some trailing spaces?

**Comment by Mirch** [comment]
@weihanglo I added the `cargo -vV output` to the issue.

I also tried to reproduce the problem and found the following: 

If `/target` is present, the line added by `cargo init` is indeed commented out. However, it looks like `target/` or `*target/`  are not correctly identified.

 The following `.gitignore` file is what I'm left with after creating a new repository from Github (with the `Rust` template for `.gitignore`), cloning the repo and then running `cargo init`:

```
# Generated by Cargo
# will have compiled files and executables
debug/
target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these, which store debugging information
*.pdb


# Added by cargo

/target

```

**Comment by weihanglo** [comment]
Thanks for the reply. I think your reproduction is correct.

However, `cargo init` at this moment doesn't add an item if there is an exact-matched one. For `/target`, `target/` and `*target/`, each of them has a slightly different meaning. I don't feel like Cargo should be “smarter” to ignore all of them when one exists.
