### ISSUE TITLE
Build scripts can not add Mac framework dependencies

### ISSUE THREAD

**Issue by dylanede** [rust-lang/cargo#1230]
Currently, build scripts are only allowed to add `-l` and `-L` flags to rustc. This means that they cannot add `-framework` or `-F`, required for linking to frameworks on Mac. Should be a simple fix to allow the extra flags.

**Comment by alexcrichton** [comment]
The compiler actually adds frameworks via `-l framework=foo` and `-L native=foo`, so you should be able to do this today!
