### ISSUE TITLE
Unkind error message failing patch non-existing package with a prerelease version package

### ISSUE THREAD

**Issue by loloicci** [rust-lang/cargo#12315]
### Problem

Trying to patch a stable version package (0.1.0) with prerelease version one (0.1.1-prerelease) fails with an unkind error message if there are no other matching repositories. For example,

root's Cargo.toml:
```Cargo.toml

[package]
name = "cargo-mybin"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-mylib = "0.1.0"

[patch.crates-io]
cargo-mylib = { git = "https://github.com/loloicci/cargo-mylib.git" }
```

cargo-mylib's Cargo.toml
```Cargo.toml
[package]
name = "cargo-mylib"
version = "0.1.1-prerelease"
edition = "2021"
```

`cargo update` in this cargo-mybin fails with

```sh
$ cargo update
    Updating git repository `https://github.com/loloicci/cargo-mylib.git`
    Updating crates.io index
error: no matching package named `cargo-mylib` found
location searched: registry `crates-io`
required by package `cargo-mybin v0.1.0 (/.../cargo-mybin)`
```

This message says wrong information that no matching package was found. This is because https://github.com/rust-lang/cargo/blob/5febbe5587b74108165f748e79a4f8badbdf5e0e/src/cargo/core/resolver/errors.rs#L226-L228 does not match prerelease version.

### Steps

1. clone https://github.com/loloicci/cargo-mybin
2. execute `cargo update` on it

### Possible Solution(s)

use `OptVersionReq::Any` instead of `semver::VersionReq::parse("*").unwrap()` in https://github.com/rust-lang/cargo/blob/5febbe5587b74108165f748e79a4f8badbdf5e0e/src/cargo/core/resolver/errors.rs#L226-L228.

### Version

```text
$ cargo version --verbose
cargo 1.71.0-nightly (09276c703 2023-05-16)
release: 1.71.0-nightly
commit-hash: 09276c703a473ab33daaeb94917232e80eefd628
commit-date: 2023-05-16
host: x86_64-apple-darwin
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 7.64.1 (sys:0.4.61+curl-8.0.1 system ssl:(SecureTransport) LibreSSL/2.8.3)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Mac OS 10.15.7 [64-bit]
```

**Comment by loloicci** [comment]
https://github.com/rust-lang/cargo/blob/5febbe5587b74108165f748e79a4f8badbdf5e0e/src/cargo/core/resolver/errors.rs#L226-L228
is intended and this is used to judge "dependency" specifies the prerelease version package. Using this, printing kind error message for mistakes in "dependency". (see https://github.com/rust-lang/cargo/pull/12316 and its CI fails)

I suggest improving error messages for "patch" specifies prerelease versions.

**Comment by Eh2406** [comment]
I agree we should use `OptVersionReq::Any` instead of `semver::VersionReq::parse("*").unwrap()`!
