### ISSUE TITLE
`cargo publish --config package.publish=true` doesn't work

### ISSUE THREAD

**Issue by davidanthoff** [rust-lang/cargo#12314]
### Problem

I have a `Cargo.toml` with `package.publish=false`. I need that setting because I am using `cargo release` and don't want a publish to happen when I tag a new release with `cargo release`. But I _do_ want to publish at a later point in the workflow via `cargo publish`, and I would have thought that overriding via `--config` would then allow me to "force" `cargo publish` to work. Instead I get an error message
```
error: `XXX` cannot be published.
`package.publish` is set to `false` or an empty list in Cargo.toml and prevents publishing.
```

### Steps

1. Create `Cargo.toml` with a setting `package.publish=false`.
2. Try to publish via `cargo publish --config package.publish=true`.

**Comment by epage** [comment]
`Cargo.toml` is generally referred to as the [package manfiest](https://doc.rust-lang.org/cargo/reference/manifest.html) which is distinct from [cargo configuration](https://doc.rust-lang.org/cargo/reference/config.html), so the `--config` flag won't work in this case.

`cargo release` does offer various settings and flags which might help in your case.  I'd recommend [starting a dicussion](https://github.com/crate-ci/cargo-release/discussions)

**Comment by davidanthoff** [comment]
Ah, completely missed that, sorry :)

I actually found a simple solution for this: I added a `release.toml` with `publish = false` and then in `Cargo.toml` changed `publish=true`, and now it all works exactly as I want it to. Sorry for the noise and thanks for the hint!
