### ISSUE TITLE
cargo build failed due to fetching dependencies Killed

### ISSUE THREAD

**Issue by goodidea-kp** [rust-lang/cargo#12311]
### Problem

 cargo update
    Updating crates.io index
Killed Fetch [=====>                   ]  27.41%, 2.19KiB/s

I was able to build my project on Ubuntu, but the sane Dockerfile is not working for Mac Pro M2
cargo update or build sending 'Killied' message on updating crates. I set `registries.crates-io.protocol = "sparse"` it doesn't help.

### Steps

1. In any Docker file `FROM ekidd/rust-musl-builder:stable as builder`
2. create a simple project
3. `COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml
COPY ./.cargo ./.cargo

ADD ./src ./src

RUN cargo build --release --lib`

### Possible Solution(s)

add configuration to wait network longer? Not sure that is correct solution though

### Version

```text
cargo 1.59.0 (49d8809dc 2022-02-10)
release: 1.59.0
commit-hash: 49d8809dc2d3e6e0d5ec634fcf26d8e2aab67130
commit-date: 2022-02-10
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Linux [64-bit]
```

**Comment by weihanglo** [comment]
Sorry for the inconvenience. 

I noticed that the Rust/Cargo version you use is fairly old. That version doesn't even have sparse registry support. Could you try again with latest stable (1.70) to see if the problem persists?

triage: @rustbot label -S-triage +S-needs-info

**Comment by weihanglo** [comment]
I'm going to close due to inactivity. The Rust project doesn't backport features to such an old version. I'd also recommend giving [the official Rust docker images](https://hub.docker.com/_/rust) an attempt. They should be fairly stable and up-to-date.

Feel free to comment here or open a new issue if you've got any update.
