### ISSUE TITLE
cargo check uses older version of git dependency after cargo update

### ISSUE THREAD

**Issue by JesseGlick** [rust-lang/cargo#12328]
### Problem

I have a project consisting of two crates, each in a private repository on GitHub. One is a library crate called "aws-modeling", containing code to be reused in future projects, and the other is a binary crate that uses aws-modeling as a dependency.

When I add a new feature to aws-modeling, run cargo update, and then add code to my binary project using the feature, cargo check produces various errors, the key part of which appears to be:

`note: method defined here
 --> /home/jesseglick/.cargo/git/checkouts/aws-modeling-09b36d7dc6bd99f7/d9093db/src/lib.rs:106:18`

The commit d9003db is an earlier one then the one specified in cargo.lock after the update:

[[package]]
name = "aws-modeling"
version = "0.1.0"
source = "git+https://github.com/jesseglick/aws-modeling#cc941cf55bab6a4f3fc6ab1dbf404a4ede367e76"

(The link above will not work, as it is to a private repository.)

cargo build compiles with no errors.

I expected cargo check to produce the same results as cargo build.

### Steps

1. Create a library crate.
2. Create a binary crate that uses the library as a git dependency.
3. Add a new public function to the library crate.
4. Run cargo update on the binary crate.
5. Add code to the binary crate that calls the new function.
6. Run cargo check.

### Possible Solution(s)

Apparently, cargo check is still caching older code, perhaps partly compiled, after the update.

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-unknown-linux-gnu
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
os: Pop!_OS 22.04 (jammy) [64-bit]
```

**Comment by Mrt3383x38** [comment]
Serbes bırakın sadece bakmakla kalıyoruz islem yapamıyoruz

**Comment by weihanglo** [comment]
Going to close due to inactivity, and there is no clear step to reproduce. The above test case <https://github.com/rust-lang/cargo/issues/12328#issuecomment-1625745890> demonstrates that it successfully updates git source. There might be something disconnected. Feel free to reopen if you have a chance to provide an easier way to inspect or reproduce the error.
