### ISSUE TITLE
Build script not run

### ISSUE THREAD

**Issue by a-maier** [rust-lang/cargo#12326]
### Problem

I am trying to build a crate with a build script that outputs linker flags taken from a `const` defined in another crate and has some additional code:
```rust
fn main() {
    for flag in ntuple::ROOT_LINKER_FLAGS {
        println!("cargo:rustc-link-arg={flag}");
    }
   std::env::var("CARGO_MANIFEST_DIR");
}
```
When running `cargo build -vv`, no `target/debug/build/ntuple-bug-*/output` file is created, the linker flags are not added, and linking fails. [Here is a log](https://github.com/rust-lang/cargo/files/11946284/build_log.txt).

If I remove or comment out the line `std::env::var("CARGO_MANIFEST_DIR");` the crate builds without problems.

The code for the crate is here: [https://github.com/a-maier/ntuple-bug]( https://github.com/a-maier/ntuple-bug)

### Steps

1. Install [ROOT](https://root.cern.ch/). I installed to `$HOME/local/opt/`.
2. Ensure that the `root-config` binary is in the `$PATH`.
3. Create a crate with `ntuple = "0.7.0"` as a build dependency and the above build script:
 ```rust
fn main() {
    for flag in ntuple::ROOT_LINKER_FLAGS {
        println!("cargo:rustc-link-arg={flag}");
    }
   std::env::var("CARGO_MANIFEST_DIR");
}
```
Alternatively, clone [https://github.com/a-maier/ntuple-bug]( https://github.com/a-maier/ntuple-bug)
4. Run `cargo build`

### Notes

- Adding a `panic!()` at the end of the build script does not seem to have any effect, so it appears that the script is never executed.
- Whether the build script is being run seems to depend on the code outside the `for` loop, but I have not found any clear pattern.
- There is no problem when using a locally defined `const`.

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-unknown-linux-gnu
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by weihanglo** [comment]
Unfortunately we are unable to provide support here for helping with issues. I cannot tell whether there is a bug inside ntuple's build.rs or in Cargo. If you can minimize the reproducer it would be easier to follow.

Apart from that, you try one of the user forums such as <https://users.rust-lang.org/> to see if someone can help.

**Comment by a-maier** [comment]
> If you can minimize the reproducer it would be easier to follow.

Thanks, I will try to do that.

> I cannot tell whether there is a bug inside ntuple's build.rs or in Cargo.

I am realising that I was not very clear. ntuple itself seems to build without any problems, both stand-alone and as a dependency. 

However, build scripts of crates that have ntuple as a build dependency and use `ntuple::ROOT_LINKER_FLAGS` are apparently not always run.

I don't see how a bug in ntuple's build script could cause such a behaviour.

**Comment by weihanglo** [comment]
I am going to close due to the lack of a minimal set of steps to reproduce, and it has been inactive for a while. Feel free to comment below or open a new issue if there is any update or you have chances to set up a minimal reproduction. Thank you.

**Comment by a-maier** [comment]
Sorry for the lack of updates. I have not been able to trim down the steps any further. Seemingly unrelated changes like renaming the imported crate made the problem go away.

For posterity's sake, I have worked around the problem by exporting a function generating the linker flags in place of the `ROOT_LINKER_FLAGS` constant.
