### ISSUE TITLE
Cargo downloads wrong version of a dependency 

### ISSUE THREAD

**Issue by bingis-khan** [rust-lang/cargo#12333]
### Problem

Alternate title: Cargo ignores alpha version when a "non-alpha" exists.

I have a dependency in my `Cargo.toml` file:
```
select = "0.6.0-alpha.1"
```

However, cargo downloads the "0.6.0" version, in this case causing a compiler error if the `select()` method is used.

### Notes

I'm not sure if this is a bug or a security feature. (although if it's a "feature", I still think it's misleading, since my `Cargo.toml` clearly states I want the alpha version.)

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-unknown-linux-gnu
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
os: Arch Linux [64-bit]
```

**Comment by epage** [comment]
At this time, cargo treats all pre-release versions as compatible with each other and with subsequent non-pre-release versions.

There is more discussion of this problem at #2222

Closing in favor of that.  If there is something we missed, let us know!
