### ISSUE TITLE
(WIndows)cargo build says: unrecognized option: 'print-file-name'

### ISSUE THREAD

**Issue by Jervac** [rust-lang/cargo#1235]
I have rust and cargo working on a Linux VM, but cargo build on windows says unrecognized option: 'print-file-name' and that it's error code 101. I'm using rust nightly 1.0.0 and cargo 0.0.1.

**Comment by alexcrichton** [comment]
You may want to be sure you're using the most up-to-date Cargo (it should be a date this january). Could you paste the output of `cargo -V`?

**Comment by Jervac** [comment]
cargo 0.0.1-prenightly (fd5d7a9) 2014-12-25 but I downloaded the binary today. Hmm..

**Comment by alexcrichton** [comment]
Oh dear, which binary did you download?

**Comment by Jervac** [comment]
windows binary 64. It was a tar.gz

**Comment by alexcrichton** [comment]
Do you have the URL? The target triples have changed in the past and old triples aren't necessarily updated any more. I'd recommend installing from the [official installers](http://www.rust-lang.org/install.html) to get the most up-to-date version.

**Comment by Jervac** [comment]
https://crates.io/install and I checked and have the up-to-date version of Rust

**Comment by alexcrichton** [comment]
Do you know the precise URL that you downloaded? I just downloaded both the 32/64 bit nightlies from that page and they both report a date of 2015-01-22

**Comment by Jervac** [comment]
My downloads says i got it from https://static.rust-lang.org/cargo-dist/cargo-nightly-x86_64-pc-windows-gnu.tar.gz

**Comment by alexcrichton** [comment]
And you're sure you're running the binaries from that exact download?

**Comment by Jervac** [comment]
seems i have cargo from a month ago when i tried to set it up. I think it may work

**Comment by Jervac** [comment]
It works, my mistake :+1:

**Comment by alexcrichton** [comment]
Glad it worked out! Thanks for the report regardless :)

Always a good idea to second check that our automation is working like we think it is...
