### ISSUE TITLE
Cargo new

### ISSUE THREAD

**Issue by EinfachNurBaum** [rust-lang/cargo#12389]
### Problem

Cargo new has problems to create directories. I also tried without spaces and without "\" and without "--bin" parameter but nothing works.

```
PS C:\......\Documents\coding\low level stuff\rust\tutorials> cargo new hello_world\ --bin
error: Failed to create package `hello_world` at `C:\.....\Documents\coding\low level stuff\rust\tutorials\hello_world\`                            

Caused by: failed to create directory `C:\.....\Documents\coding\low level stuff\rust\tutorials\hello_world\`

Caused by: The system cannot find the specified file. (os error 2)

PS C:\........\Documents\coding\low level stuff\rust\tutorials> cargo --version
cargo 1.71.0 (cfd3bbd8f 2023-06-08)



PS C:\.........\Documents\coding\low level stuff\rust\tutorials> cargo new hello_world
error: Failed to create package `hello_world` at `C:\......\Documents\coding\low level stuff\rust\tutorials\hello_world`
Caused by: failed to create directory `C:\........\Documents\coding\low level stuff\rust\tutorials\hello_world`
Caused by: ...... (os error 2)  
```

### Notes

I think it has prblems to detect Windows rightly because:

> cargo init 
error: Failed to create package `hello_world` at `C:\........\Documents\coding\low level stuff\rust\tutorials\hello_world\.`                      Caused by: failed to make directory 'C:\........\Documents\coding\low level stuff\rust\tutorials\hello_world\./.git': 
.....; class=Os (2)

it wants to create "./.git". 

### Version

```text
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
```

I just use Windows 10 home, without WSL or anything else. system variable of "OS" is "Windows_NT".

**Comment by EinfachNurBaum** [comment]
I reinstalled it today but same problems. Looks like something in Cargo does not work well. Rustup-init worked well except that the files in tmp directory does not work

**Comment by ChrisDenton** [comment]
Can you show the output of `cargo version --verbose`?

**Comment by EinfachNurBaum** [comment]
> Can you show the output of `cargo version --verbose`?

cargo 1.71.0 (cfd3bbd8f 2023-06-08)
release: 1.71.0
commit-hash: cfd3bbd8fe4fd92074dfad04b7eb9a923646839f
commit-date: 2023-06-08
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Education N) [64-bit]

**Comment by ChrisDenton** [comment]
Hm, I haven't been able to reproduce this yet but if git is failing for some reason you could try disabling it. In your user folder, look for a directory called `.cargo`. In the directory create a file called `config.toml` and add this:

```toml
[cargo-new]
vcs = "none"
```

**Comment by EinfachNurBaum** [comment]
I guess something like logs feature would be good

**Comment by EinfachNurBaum** [comment]
> Hm, I haven't been able to reproduce this yet but if git is failing for some reason you could try disabling it. In your user folder, look for a directory called `.cargo`. In the directory create a file called `config.toml` and add this:
> 
> ```toml
> [cargo-new]
> vcs = "none"
> ```

![image](https://github.com/rust-lang/cargo/assets/82251642/501fbd0c-7709-4d8f-b3c5-78d3e915c253)

looks like it is also a problem in rustup. I checked with python now the env. variables and it shows Windows_NT. Maybe that I use a AMD64 Processor let it thinks that my os uses slash.

**Comment by ChrisDenton** [comment]
Windows will accept both `\` and `/` in most contextts so I doubt that's the issue.

**Comment by EinfachNurBaum** [comment]
> Windows will accept both `\` and `/` in most contexts so I doubt that's the issue.

Okay, it looks like I can create in my User directory new directories but not in my Documents folder:

![image](https://github.com/rust-lang/cargo/assets/82251642/9f4b5346-701b-4be1-87f6-3fc025eeb324)

**Comment by EinfachNurBaum** [comment]
So it says always: "The system can not find the file"

**Comment by EinfachNurBaum** [comment]
Okay, if someone else has also this problem. You just have to add the "Everyone" to the permission of the Documents Folder. You can edit the permission in Properties.
