### ISSUE TITLE
`cargo rm foo` on error should suggest `--dev` or `--build`, if appropriate

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#12405]
### Problem

I just ran
```console
$ cargo rm dunce
    Removing dunce from dependencies
error: the dependency `dunce` could not be found in `dependencies`.
```

### Proposed Solution

It'd be nice if the error had a note saying that a `--dev` dependency existed

**Comment by epage** [comment]
If you accidentally run `cargo rm dunce` twice, it shouldn't act as if you did `cargo rm --dev dunce`.

While "if the tool knew what I intended, it should just do it" is a great principle, I feel like over doing it could lead to some very wrong behavior.

**Comment by hi-rustin** [comment]
I am working on it.
