### ISSUE TITLE
Providing a token to `cargo login` via command line causes a hang on CI

### ISSUE THREAD

**Issue by DrChat** [rust-lang/cargo#12438]
### Problem

Specifying the logon token via the command-line will cause a hang if `stdin` is not attached to a terminal (such as when running in automation).

### Steps

```
cargo login --registry xxxxxxxx "Bearer XXXXXXXXXXXXXXXXXXXXXXXXX"
```

### Possible Solution(s)

Workaround:
```
"Bearer XXXXXXXXXXXXXXXXXXXXXXXXX" | cargo login --registry xxxxxxxx
```

### Notes

Likely introduced by #12334:

https://github.com/rust-lang/cargo/blob/263d24baca913d7ace29e2f59a3254e47272fd6b/src/cargo/ops/registry/login.rs#L38-L44

### Version

```text
cargo 1.73.0-nightly (c91a693e7 2023-07-31)
release: 1.73.0-nightly
commit-hash: c91a693e7977e33a1064b63a5daf5fb689f01651
commit-date: 2023-07-31
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by ehuss** [comment]
@arlosi Do you have a chance to look at this? I think an easy change would be to move the `is_terminal` check into the `or_else` closure.

I'm a bit unclear why CI has a stdin that isn't `/dev/null` and isn't a terminal. I would expect non-terminal stdin to immediately return an empty input.
