### ISSUE TITLE
TypeId of types in dependencies depends on the main crate

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1244]
e.g.

```
$ tree
.
├── Makefile
├── x
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── y
│   ├── Cargo.toml
│   └── src
│       └── main.rs
└── z
    ├── Cargo.toml
    └── src
        └── main.rs

6 directories, 7 files
```

``` rust
// x/src/lib.rs
pub struct Foo { x: i32 }

pub fn go() {
    println!("{:?}", std::any::TypeId::of::<Foo>());
}
```

``` rust
// {y,z}/src/main.rs
extern crate x;

fn main() {
    x::go();
}
```

Running them gives `TypeId { t: 9197138652898941418 }` for `y` and `TypeId { t: 3222965878591603564 }` for `z`.

I'm filing this as a Cargo issue because I suspect it may be caused by metadata cargo is passing. It seems unfortunate that changing the context in which a crate appears should change its internal typeids, but I'm not sure this is a bug (or if it's solvable).

**Comment by huonw** [comment]
Repo: https://github.com/huonw/cargo-issue-1244 just run `make`.

**Comment by alexcrichton** [comment]
What in the world is happening here

**Comment by DanielKeep** [comment]
@alexcrichton: If I run the following sequence of commands, I get two different `TypeId`s:

    rustc x\src\lib.rs --crate-name x --crate-type lib -g -C metadata=y -C extra-filename=-y --out-dir .
    rustc x\src\lib.rs --crate-name x --crate-type lib -g -C metadata=z -C extra-filename=-z --out-dir .
    rustc y\src\main.rs --crate-name y --crate-type bin -g --out-dir . -L . --extern x=libx-y.rlib
    rustc z\src\main.rs --crate-name z --crate-type bin -g --out-dir . -L . --extern x=libx-z.rlib
    .\y
    .\z

Output:

    TypeId { t: 14097120357172906008 }
    TypeId { t: 16366992035564179121 }

If I change both compilations of `x` to use `metadata=x`, however, they match.  That is:

    rustc x\src\lib.rs --crate-name x --crate-type lib -g -C metadata=x -C extra-filename=-y --out-dir .
    rustc x\src\lib.rs --crate-name x --crate-type lib -g -C metadata=x -C extra-filename=-z --out-dir .
    rustc y\src\main.rs --crate-name y --crate-type bin -g --out-dir . -L . --extern x=libx-y.rlib
    rustc z\src\main.rs --crate-name z --crate-type bin -g --out-dir . -L . --extern x=libx-z.rlib
    .\y
    .\z

Outputs:

    TypeId { t: 12164603829377429615 }
    TypeId { t: 12164603829377429615 }

It looks very much like the crate metadata is influencing the `TypeId`; either it shouldn't, or Cargo should be passing the same metadata for both compilations.  For reference:

    rustc 1.0.0-nightly (92ff8ea52 2015-01-27 23:08:13 +0000)
    binary: rustc
    commit-hash: 92ff8ea52816982ad4cbfac8168e216d32d74c77
    commit-date: 2015-01-27 23:08:13 +0000
    host: i686-pc-windows-gnu
    release: 1.0.0-nightly

**Comment by alexcrichton** [comment]
Oh right, I forgot about that. Thanks @DanielKeep!

This is basically highly inter-related to https://github.com/rust-lang/cargo/issues/497 because the metadata comes from the hash of the PackageId and in this case the PackageId points at a `Path`. The `Path` that it points at is the root path of the first compilation, not necessarily at the dependant package itself.

For example, in @huonw's example, the first path is `.../z` and the other is `.../y`. This is the path listed for the `x` crate (despite it being in a different path).

That's at least the source of the bug at least :)

**Comment by alexcrichton** [comment]
Sure!
