### ISSUE TITLE
"not a valid url scheme" when publishing

### ISSUE THREAD

**Issue by andrewrk** [rust-lang/cargo#1246]
when publishing I got this message:
`api errors: not a valid url scheme: git://github.com/andrewrk/math3d-rs.git`

Cargo.toml:

```
repository = "git://github.com/andrewrk/math3d-rs.git"
```

I did not get a warning or error when I did `cargo package`.

**Comment by alexcrichton** [comment]
Currently only [`http` and `https`](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L185-L188) are valid schemes because we generate a link to it on the crate's page. If you think that `git://` links should be display-able, could you open an issue on `crates.io` instead? Thanks!
