### ISSUE TITLE
missing 0.72.2 tag

### ISSUE THREAD

**Issue by chenrui333** [rust-lang/cargo#12460]
👋 while [upgrading rust to 1.71.1 on the homebrew side](https://github.com/Homebrew/homebrew-core/pull/138466), we found that the 0.72.2 tag is missing? Is that intentional, thanks!

**Comment by ehuss** [comment]
Maybe I'm a bit confused, but there is no 0.72.2 version.  There is a tag for 0.72.1: https://github.com/rust-lang/cargo/releases/tag/0.72.1

**Comment by arlosi** [comment]
There doesn't seem to be a tag in the Cargo repo that corresponds to the Rust 1.71.1 release. The cargo submodule in rust-lang/rust for 1.71.1 points to https://github.com/rust-lang/cargo/commit/7f1d04c0053083b98fa50b69b6f56e339b0556a8

But the 0.72.1 tag in the Cargo repo points to https://github.com/rust-lang/cargo/commit/c0eb6cc012af6d6555c761729f7fb5f5254b40ab (which doesn't include the CVE fix)

**Comment by ehuss** [comment]
Oh, I see!  Right, I forgot we did an out-of-band 0.72.1 release.

Can someone volunteer to post a PR to the rust-1.71.0 branch to bump the version to 0.72.2? I can publish a new release after that is done.

**Comment by ehuss** [comment]
0.72.2 should now be published and tagged.

**Comment by chenrui333** [comment]
Thanks @ehuss and all!
