### ISSUE TITLE
Cargo check has false negatives in a workspace with internal dependencies

### ISSUE THREAD

**Issue by Wodann** [rust-lang/cargo#12470]
### Problem

When using a workspace that has multiple crates that depend on each other, enabling of feature flags prevents running of `cargo check --no-default-features` on all crates.

### Steps

Example workspace:
- crates
  - A [features: `Foo`]
  - B [depends on: A with feature `Foo` enabled]

Running 
```bash
cargo c --no-default-features
```

inside `{workspace-dir}/crates/A` will cause errors when anything that should be hidden behind the `Foo` feature flag is referenced

```bash
cargo c --no-default-features --all
```

inside `{workspace-dir}` does not cause any errors.

### Possible Solution(s)

I'd potentially expect two version of A to be checked:
- One that complies with the `cargo check --no-default-features` command
- One that suffices the dependency for B (`Foo` enabled)

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-pc-windows-msvc
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 10 Home) [64-bit]
```

**Comment by epage** [comment]
We generally refer to this as "feature unification" and this is expected.  When only do one build combination within a run.  I believe #4463  is the most relevant existing issue for this.

One workaround is to use tools like [cargo-hack](https://crates.io/crates/cargo-hack) to do multiple `cargo check` runs.

Going to go ahead and close this but if there is something I missed, let us know and we can re-open it!

**Comment by weihanglo** [comment]
For more on feature unification, see https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
