### ISSUE TITLE
`.cargo/config.toml` not defining documented env variables

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/cargo#12476]
### Problem

In the [Cargo reference for `.cargo/config.toml`](https://doc.rust-lang.org/cargo/reference/config.html), it is written that when adding configuration (e.g. an alias in the `[alias]` table) to `.cargo/config.toml`, an environment variable is defined.

I can't get these environment variables to work.

### Steps

1. Create a `.cargo/config.toml` file on your project with an `[alias]` table and some aliases.
2. Set a simple program to view Rust's environment variables (e.g. using a loop with `std::env::vars()`)
3. There isn't any mention of the supposed `CARGO_ALIAS_<name>` environment variables.

### Possible Solution(s)

Maybe it's a bug on scope. This `.cargo/config.toml` is defined on a project-level, but maybe this functionality works on a `~/.cargo/config.toml` level.

### Version

```text
cargo 1.73.0-nightly (d78bbf4bd 2023-08-03)
release: 1.73.0-nightly
commit-hash: d78bbf4bde3c6b95caca7512f537c6f9721426ff
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Pop!_OS 22.04 (jammy) [64-bit]
```

**Comment by not-my-profile** [comment]
I think you misunderstood that page. It clearly says:

> Cargo **can also be configured** through environment variables in addition to the TOML configuration files.

(emphasis mine)

As far as I can see it never says that cargo **will define** these environment variables from the `.cargo/config.toml` file.

i.e. you can do `CARGO_ALIAS_FOO=help cargo foo` and that works as expected for me.

**Comment by weihanglo** [comment]
Thanks for the clarification @not-my-profile!

If you do want to read alias definitions within your program the best way at this moment is consuming `cargo` as a dependency (sorry we're trying hard making it more ergonomic…).

Going to close this. Let us know if this needs to remain open, or you've got an idea to improve the doc :)
