### ISSUE TITLE
Platform-specific `linker` option ignored when specified using `cfg` syntax

### ISSUE THREAD

**Issue by tgnottingham** [rust-lang/cargo#12472]
### Problem

When the following is placed in `.cargo/config.toml`, the `linker` option is respected (on an x86_64 Linux system):

```
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
```

However, when the `cfg` syntax is used, as in the following, the `linker` option seems to be ignored (`-C linker=clang` isn't visible in `cargo -vv` output):

```
[target.'cfg(unix)']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
```

In either case, the `rustflags` option is respected.

Is the `linker` option being ignored here a bug?

### Version

```text
cargo 1.71.1 (7f1d04c00 2023-07-29)
release: 1.71.1
commit-hash: 7f1d04c0053083b98fa50b69b6f56e339b0556a8
commit-date: 2023-07-29
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by weihanglo** [comment]
[This section of `[target]`](https://doc.rust-lang.org/1.71.1/cargo/reference/config.html#target>) config lists all possible configurations and doesn't include `target.<cfg>'.linker` and `target.<cfg>.<links>`.

Delved into the history, it seems that just nobody requested for that.

* For rustflags — https://github.com/rust-lang/cargo/pull/3854 
* For runner — https://github.com/rust-lang/cargo/pull/5959

However, the mechanisms of plain target-triple and `cfg` expression are different. May need some efforts to implement those configs. My guess is that they'll behave the same as `target.<cfg>.runner`: `<triple>` takes precedence over them, and errors out when multiple `<cfg>` of them found.

@ehuss the wise, was there any reason not supporting `linker` and link overridden with cfg expression?

**Comment by ehuss** [comment]
I don't think there is a specific reason other than nobody needed it. If we add it, I suppose it should follow the same logic as `runner`.

**Comment by weihanglo** [comment]
Thanks for quick reply!

Here are pointers for people wanting to jump in on adding `target.<cfg>.linker` feature:

* Basically as Eric said, it should follow the same logic as `runner`. Here is how `runner` find matched config: https://github.com/rust-lang/cargo/blob/7e9de3f4ec3708f500bec142317895b96131e47c/src/cargo/core/compiler/compilation.rs#L403-L406
* A new `linker` field is required to be added to `TargetCfgConfig`: https://github.com/rust-lang/cargo/blob/7e9de3f4ec3708f500bec142317895b96131e47c/src/cargo/util/config/target.rs#L12
* `TargetConfig.linker` is accessible through the field itself, as well as via [`BuildContext::linker`](https://github.com/rust-lang/cargo/blob/7e9de3f4ec3708f500bec142317895b96131e47c/src/cargo/core/compiler/build_context/mod.rs#L124). We should consolidate them into one place. By copying `runner`'s logic, perhaps adding a `target_links` field to `Compilation` struct?

---

@rustbot label -S-needs-info +S-accepted +E-easy

Assumed it is not too hard, though I might be wron.
