### ISSUE TITLE
`cargo build` fails with `RUSTFLAGS="--error-format=json"`

### ISSUE THREAD

**Issue by sourcefrog** [rust-lang/cargo#12486]
### Problem

If `RUSTFLAGS` sets `--error-format` then `cargo-build` fails.

### Steps

```
; cargo init demo
     Created binary (application) package
; cd demo
; env RUSTFLAGS="--error-format=json" cargo build
   Compiling demo v0.1.0 (/tmp/demo)
error: Option 'error-format' given more than once

error: could not compile `demo` (bin "demo")
```

### Possible Solution(s)

I haven't looked in the code but I guess something else is setting `--error-format` in the rust argv and that needs to be reconciled with or override `RUSTFLAGS`.

### Notes

This was reported in https://github.com/sourcefrog/cargo-mutants/issues/136 but it turns out the behavior is easily reproduced in cargo alone.

This looks like https://github.com/rust-lang/cargo/issues/11452 (but it's not about `--target`) and https://github.com/rust-lang/cargo/issues/6375 (but it's not about `build.rs` or cross compilation), so I think it's a distinct new bug, but perhaps the solution is the same.

### Version

```text
; cargo version --verbose
cargo 1.72.0-beta.6 (44b6be4bd 2023-08-03)
release: 1.72.0-beta.6
commit-hash: 44b6be4bdf2cd7d3f4d4cb266bfe428dfc2a7952
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Pop!_OS 22.04 (jammy) [64-bit]
```

It fails the same way on nightly:

```
; cargo +nightly version --verbose
cargo 1.73.0-nightly (d78bbf4bd 2023-08-03)
release: 1.73.0-nightly
commit-hash: d78bbf4bde3c6b95caca7512f537c6f9721426ff
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Pop!_OS 22.04 (jammy) [64-bit]
bobcat /tmp/demo (main) 08:05
```

**Comment by ehuss** [comment]
If you want JSON output, the correct way to do that is `cargo --message-format=json`. Generally, using RUSTFLAGS should only be done for very advanced use cases, in situations where it is understood how the flags will interact with cargo (and understand that it may break in the future).

**Comment by arlosi** [comment]
Cargo internally sets `--error-format` when running `rustc`, so setting it via `RUSTFLAGS` causing an error is expected.

As ehuss said, the correct way to get JSON output from Cargo is `cargo --message-format=json`

**Comment by sourcefrog** [comment]
Should I send a PR updating https://doc.rust-lang.org/cargo/reference/environment-variables.html to add some kind of warning?

**Comment by weihanglo** [comment]
I remember we have a such a notice already in <https://doc.rust-lang.org/nightly/cargo/reference/config.html#buildrustflags>.
