### ISSUE TITLE
cargo doc does not seem to respect `RUSTFLAGS`

### ISSUE THREAD

**Issue by yongqli** [rust-lang/cargo#12481]
### Problem

In the following repo:
https://github.com/yongqli/bug-test

Running

    RUSTFLAGS="-L/opt/homebrew/opt/libomp/lib" cargo build --release

on macOS works, but running

    RUSTFLAGS="-L/opt/homebrew/opt/libomp/lib" cargo test --doc

fails with linker error.

Tested on cargo 1.71

### Notes

On macOs you may need to install dependencies by running `brew install libomp`.

**Comment by yongqli** [comment]
Looks like this was the issue: https://github.com/rust-lang/cargo/issues/4737

**Comment by weihanglo** [comment]
Have you tried `RUSTDOCFLAGS`?

**Comment by yongqli** [comment]
Is there a way to pass linker arguments to cargo doc based on target triple? Only `rustflags` is listed under `[target.<triple>]`: https://doc.rust-lang.org/cargo/reference/config.html#configuration-format

**Comment by yongqli** [comment]
> Have you tried `RUSTDOCFLAGS`?

Yes, RUSTDOCFLAGS worked.

**Comment by weihanglo** [comment]
> Is there a way to pass linker arguments to cargo doc based on target triple? Only `rustflags` is listed under `[target.<triple>]`: https://doc.rust-lang.org/cargo/reference/config.html#configuration-format `rustdocflags` is not accepted.

No. And afaik no one requested for that. (I've fixed an issue around btw <https://github.com/rust-lang/cargo/pull/11323>)

The request does look different from this issue you've tried to fix. If possible, to make it clear, could you open a new one and close this?

**Comment by weihanglo** [comment]
Okay. Maybe don't need to open a new one. In #6460 there are some upstream issue linked need to deal with first. I'll close this now. If you have different thoughts, please let use know. Thank you :)
