### ISSUE TITLE
Can't add package because of conflict in feature I haven't enabled

### ISSUE THREAD

**Issue by apa512** [rust-lang/cargo#12493]
### Problem

I'm trying to run a project with the following dependencies:

```
sqlx = { version = "0.7.1", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
solana-sdk = "1.16.8"
```

This results in conflicting dependencies:

```
error: failed to select a version for `zeroize`.
    ... required by package `curve25519-dalek v3.2.1`
    ... which satisfies dependency `curve25519-dalek = "^3.2.1"` of package `solana-program v1.16.8`
    ... which satisfies dependency `solana-program = "=1.16.8"` of package `solana-sdk v1.16.8`
    ... which satisfies dependency `solana-sdk = "^1.16.8"` of package `playground v0.1.0 (/home/erik/Code/playground)`
versions that meet the requirements `>=1, <1.4` are: 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0

all possible versions conflict with previously selected packages.

  previously selected package `zeroize v1.5.3`
    ... which satisfies dependency `zeroize = "^1.5"` of package `rsa v0.9.0`
    ... which satisfies dependency `rsa = "^0.9"` of package `sqlx-mysql v0.7.1`
    ... which satisfies dependency `sqlx-mysql = "=0.7.1"` of package `sqlx v0.7.1`
    ... which satisfies dependency `sqlx = "^0.7.1"` of package `playground v0.1.0 (/home/erik/Code/playground)`
```

The weird thing is that I haven't enabled the `sqlx-mysql` feature so that dependency should not be needed.

Is there anything I can do to tell Cargo that I really don't care about sqlx-mysql? Or any other way to fix this?

### Steps

1. Add `sqlx = { version = "0.7.1", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }` to Cargo.toml
2. `cargo add solana_sdk`

### Version

```text
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
release: 1.71.0
commit-hash: cfd3bbd8fe4fd92074dfad04b7eb9a923646839f
commit-date: 2023-06-08
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Arch Linux Rolling Release [64-bit]
```

**Comment by epage** [comment]
So can't speak for why the resolver is doing what it is but I would consider `curve25519-dalek`s upper-bound on zeroize to be [a bug](https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#multiple-requirements) which looks to be fixed in the 4.0 release.

**Comment by ehuss** [comment]
> Is there anything I can do to tell Cargo that I really don't care about sqlx-mysql? Or any other way to fix this?

I'm not aware of any way to fix that other than to fork and [patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) a dependency (like fixing the requirement in `curve25519-dalek`). 

Because features can be enabled through direct dependencies, the resolver has to resolve as-if all features are enabled so that there is a single `Cargo.lock` that works for all scenarios.

**Comment by apa512** [comment]
Thanks. I patched the dependency by bumping the `curve25519-dalek` version and making some necessary changes.

Feel free to close this.
