### ISSUE TITLE
Build dependency awareness

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#1251]
As issues like https://github.com/rust-lang/cargo/issues/1240 and https://github.com/rust-lang/cargo/issues/888 talk about, build scripts are not exactly trivial to write right now. We've got a fantastic system for making them easier to write via `build-dependencies`, but there's no current great way to discover build dependencies.

I think that we need a better strategy for promoting build dependencies, raising awareness about them, and generally discouraging "please install these 4 libs" sections of READMEs in favor of having scripts themselves take care of the necessities.

Some possible ideas:
- Add an "official" `build-dependency` keyword on crates.io
- Add a curated list of known build dependencies that are good for use.
- Expand documentation about build dependencies and how best to utilize them
- Have a list of "wanted build dependencies" for functionality that should be in a separate crate but currently isn't

I do think that some work is going to be need to put into writing some new build dependencies as I have a feeling we're still lacking some basic utilities. It's good track some of this though!

**Comment by pornel** [comment]
:+1: I've searched crates.io for "automake", "autotools", "configure", "cmake" and haven't found anything that would be able to integrate with C toolchain, so help there would be great!

**Comment by pnkfelix** [comment]
cc me

**Comment by brson** [comment]
@alexcrichton Removed P-high since this is inactive.

**Comment by sanxiyn** [comment]
Update? This issue started from #888 which is basically that `src/doc/build-script.md` used handwavy `cc` crate. But #1760 changed the documentation to use actually existing `gcc` crate, and added example of adding `build-dependencies` section to `Cargo.toml`.

**Comment by alexcrichton** [comment]
This is still a pretty hand-wavy bug, but I don't think it's done in the sense that there's not a one-stop-shop for "how do I write this build script" or things like "best build script practices" yet.
