### ISSUE TITLE
cargo global user config.toml ignores CARGO_HOME

### ISSUE THREAD

**Issue by budde25** [rust-lang/cargo#12519]
### Problem

I have two cargo directories.
~/.cargo the default with a config.toml
and ~/.cargo-ppc with a config.toml

When setting CARGO_HOME to `/home/budd/.cargo-ppc` I would expect it to ignore the ~/.cargo/config.toml and use ~/.cargo-ppc/config.toml instead.
but it does not.

### Steps

here I put 'bad data' it the ~/.cargo/config.toml to prove it choosing that one.

```console
> echo $CARGO_HOME
/home/budd/.cargo-ppc
> cargo install cargo-auditable
error: could not load Cargo configuration

Caused by:
  could not parse TOML configuration in `/home/budd/.cargo/config.toml`

Caused by:
  could not parse input as TOML

Caused by:
  TOML parse error at line 4, column 5
    |
  4 | bad data
    |     ^
  expected `.`, `=`
> cat ~/.cargo/config.toml
[profile.dev]
opt-level = 1

bad data
> cat ~/.cargo-ppc/config.toml
[profile.dev]
opt-level = 1
```

### Possible Solution(s)

perhaps the config searching code does not check for CARGO_HOME to be set?

### Notes

The rest of cargo does respect the custom CARGO_HOME for example placing the bins into ~/.cargo-ppc/bin/
It seems like it is just the config reading that had the issue.

### Version

```text
cargo 1.71.1 (7f1d04c00 2023-07-29)
release: 1.71.1
commit-hash: 7f1d04c0053083b98fa50b69b6f56e339b0556a8
commit-date: 2023-07-29
host: powerpc64le-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Red Hat Enterprise Linux 8.6 (Ootpa) [64-bit]
```

**Comment by weihanglo** [comment]
Could you `pwd` to print the path of your working directory?

Cargo [probes configuration](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure) all the way down from the current working directory to `/` root , so you might still end up reading the `~/.cargo/config.toml` if you're in somewhere under your home directory.

**Comment by budde25** [comment]
Ah that sounds like it would be the problem.
I was executing the commands from my home directory. Thanks!

**Comment by weihanglo** [comment]
Thanks for confirming that. Closing.

**Comment by sundeep-kokkonda** [comment]
> Could you `pwd` to print the path of your working directory?
> 
> Cargo [probes configuration](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure) all the way down from the current working directory to `/` root , so you might still end up reading the `~/.cargo/config.toml` if you're in somewhere under your home directory.

I have the same issue and the above solution works for me but I couldn't understand what is the significance of setting the `cargo_home`? Can anyone clarify me this?
