### ISSUE TITLE
Make extra keys usable without warnings

### ISSUE THREAD

**Issue by mdinger** [rust-lang/cargo#1252]
It would be nice if you could create extra keys like this `title` below that would be parsed externally from Cargo and there not be any warnings.

```
[[example]]
name = "test"
path = "examples/hello/hello.rs"
title = "Hello world!"
```

Currently you get this warning:

``` cmd
$ cargo test
unused manifest key: example.title
```

One use case is discussed some at https://github.com/rust-lang/cargo/issues/1249#issuecomment-72119273

@alexcrichton suggested 3 possible options to make it work:
- Turn warnings off by default
- Have a global config
- Have a manifest key indication how warnings should be emitted

**Comment by alexcrichton** [comment]
This is now done with the addition of `[package.metadata]`, so closing.
