### ISSUE TITLE
Cargo Help

### ISSUE THREAD

**Issue by bfrog** [rust-lang/cargo#1253]
cargo help is missing some commands that show up in cargo --list

cargo --list seems odd in general as well, it seems like thats a command rather than an argument

**Comment by alexcrichton** [comment]
It's currently intentional that `cargo help` doesn't show all the commands (there are quite a few!), it's largely just meant to show a sample selection.

I suppose I haven't thought too too hard about `--list` vs `cargo list`, but I think we can implement it either way!

**Comment by JacobHenner** [comment]
There's probably a better, DRY way to do 3cb2c91, some functions probably need to be moved around.

**Comment by felixc** [comment]
Since the partial list in `cargo help` is working as intended, and the `--list` vs. `list` discrepancy has been resolved, should this bug be closed out? Or are there any remaining issues?

**Comment by felixc** [comment]
@JacobHenner Playing around with Cargo today, I was quite confused by seeing `--list` still wasn't a command, until I realized you never sent your change as a pull request! Were you still planning on getting it incorporated?

**Comment by munyari** [comment]
Is there still any work to be done for this issue?

**Comment by alexcrichton** [comment]
Ah no I believe it's now been done, thanks for the ping!
