### ISSUE TITLE
I can't get dependences, what's the problem?

### ISSUE THREAD

**Issue by FillZpp** [rust-lang/cargo#1254]
I add
```
[dependencies]
time = "*"
```
in my Cargo.toml and try `cargo build`, it gives me
```
Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.1.1
Unable to get packages from source

To learn more, run the command again with --verbose.
```
Then i use `cargo build --verbose`, it shows
```
Downloading libc v0.1.1
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.1` from https://crates.io/api/v1/crates/libc/0.1.1/download

Caused by:
  Timeout was reached
```
What's wrong?

**Comment by alexcrichton** [comment]
If you run `curl -OL https://crates.io/api/v1/crates/libc/0.1.1/download` how long does the download normally take for you?

**Comment by FillZpp** [comment]
Oh, i get it. Now i use proxy, everything is ok. 
I'm pretty sure it is because the terrible GWF in China.
Thinks.
