### ISSUE TITLE
Errors on Windows

### ISSUE THREAD

**Issue by ProtectedMode** [rust-lang/cargo#1255]
While building some crates like glutin and sdl2 using Cargo on Windows, I am getting strange errors as a dialog like (the original message isn't English):
```
The program cannot be run because std-4e7c5e5c.dll is missing on your PC.
```
The error on the console says it failed to run the custom build command for, for example, user32-sys. This seems a bit hard since it's [pretty basic](https://github.com/retep998/winapi-rs/blob/master/user32-sys/build.rs). I'm curious to whether this is my fault or whether this is a strange bug in Cargo.

**Comment by alexcrichton** [comment]
This message looks like the `bin` directory of the Rust installation isn't in your `PATH`. Are you able to run the compiler from the command line successfully?

**Comment by ProtectedMode** [comment]
@alexcrichton, rustc ran fine, but it turns out it has something to do with running it from MSYS' bash. I'm sorry for opening this issue, I thought I had tried building without bash.

**Comment by alexcrichton** [comment]
No worries! Thanks for the report regardless :)
