### ISSUE TITLE
Clarify crate resolver version mismatch warning

### ISSUE THREAD

**Issue by algesten** [rust-lang/cargo#12557]
### Problem

Today I noticed this warning:

```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
```

The problem is that it doesn't explain _why_ I should care about this resolver mismatch. Since my project compiles and everything seems fine, it's unclear. 

### Proposed Solution

I can of course google the reason, but I similarly think this warning is not up to Rust's usual high standards of warning/error feedback. Maybe it at least could have a link to where I can read about why this matters?

**Comment by epage** [comment]
If this warning was exclusively for resolver=2, then this would be easy to talk to.  Likely we should delegate to the  https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions documentation.

Also I feel like part of the motivation for this was that people might not be getting the resolver behavior they expect and so we could tweak the wording to shift the focus to that.

Part of the reason this warning is important is to help people who do run into resolution errors.  So we might be able to speak to that as well though that borderlines on getting into specifics of the different algorithm versions.

**Comment by epage** [comment]
Also, technically, its packages that are on the new edition, not individual crates.

**Comment by epage** [comment]
Maybe
```
warning: defaulting to `workspace.resolver="1"` despite some packages setting  `package.edition="2018"` (which implies `package.resolver="2"`) because the workspace is virtual.

For more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```

Still not fully there but feels like somewhat of an improvement.

**Comment by epage** [comment]
So long as we show the message once for the entire workspace and don't include information on individual packages (which I think isn't needed for the intent of this warning), I'm assuming it should be fine.

**Comment by weihanglo** [comment]
Oh nice. Didn't know it only emits once.

However, seems like we've already emitted [a message with extra notes](https://github.com/rust-lang/cargo/blob/b2c162c0678aa336bcd9bb63c072ec2b93be92a2/src/cargo/core/workspace.rs#L1024-L1028).

```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```

So, maybe just append this at the end and we're all good?

```
For more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```


---

triage: @rustbot label +S-accepted -S-triage +E-easy

**Comment by epage** [comment]
Oh, nice, we also have the notes.

The other part my message tweaks is it puts the "problem" first and clarifies that the warning is about not tracking to your edition
