### ISSUE TITLE
Clippy not detecting all problems in multi-crate project

### ISSUE THREAD

**Issue by bobhy** [rust-lang/cargo#12561]
### Problem

I have a multi-crate project and want lint `clippy::wildcard_dependencies` enabled for all crates.
To configure this, I add `build.rustflags = ["-Dclippy::wildcard_dependencies"] to the top-level `./.cargo/config.toml` (there being no hierarchical config for clippy, currently).

This config does complain as desired about wildcard dependencies in child crates, but fails to complain about wildcard dependencies in the parent. 

If I change the project's root `Cargo.toml` so the child crates are not in the workspace, `cargo clippy` detects wildcard dependencies in the root crate (but not, of course in the children). 

And finally, if I eliminate wildcard dependencies from all the the child crates, `cargo clippy` fails to complain about the remaining wildcard dependency in the parent crate.  This is the crux of the bug report.

I'm thinking this is more a cargo problem than a clippy problem, or, of course, that `build.rustflags` doesn't do what I want it to do.

### Steps

1. `git clone https://github.com/bobhy/wc_dep; cd wc_dep`
2. `cp Cargo_fails.toml Cargo.toml`
3. `cp crates/sub_pop/Cargo_wc_dep.toml crates/sub_pop/Cargo.toml` # child crate *has* a wildcard dependency
4. 
```
> cargo clippy
    Checking sub_pop v0.1.0 (/home/bobhy/src/rust/wc_dep/crates/sub_pop)
error: wildcard dependency for `test_crate_test`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wildcard_dependencies
  = note: requested on the command line with `-D clippy::wildcard-dependencies`

error: could not compile `sub_pop` (lib) due to previous error
```
Note: there is an additional wildcard dependency in the root `./Cargo.toml` that was not detected!

Drop the child crate(s) out of the workspace:
1. `cp Cargo_works.toml Cargo.toml`
2.
```
> cargo clippy
    Checking wc_dep v0.1.0 (/home/bobhy/src/rust/wc_dep)
error: wildcard dependency for `b`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wildcard_dependencies
  = note: requested on the command line with `-D clippy::wildcard-dependencies`

error: could not compile `wc_dep` (bin "wc_dep") due to previous error
```
Now the error in root `Cargo.toml` is detected, as expected.

And finally, eliminate wildcard dependencies from the child crate:
0. `cargo clean` # sometimes needed to get the repro to work
2. 'cp crates/sub_pop/Cargo_no_wc_dep.toml crates/sub_pop/Cargo.toml`
3. `cp Cargo_fails.toml Cargo.toml`  # restore multi-crate config
4.  
```
> cargo clippy
    Checking sub_pop v0.1.0 (/home/bobhy/src/rust/wc_dep/crates/sub_pop)
    Checking wc_dep v0.1.0 (/home/bobhy/src/rust/wc_dep)
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
```

Now the error in root crate is *not* detected.

### Notes

Maybe I shouldn't expect `cargo clippy` to detect *all* problems in one run, maybe it's coded to exit on first error (though that's not really desirable).  But in any case, I think I'm justified in expecting it to find 1 error in any crate of the workspace.

Caching of build artifacts might be involved.  Sometimes I don't get an expected error but doing a `cargo clean` restores the repro scenario.

### Version

```text
cargo 1.71.1 (7f1d04c00 2023-07-29)
release: 1.71.1
commit-hash: 7f1d04c0053083b98fa50b69b6f56e339b0556a8
commit-date: 2023-07-29
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Ubuntu 23.04 (lunar) [64-bit]
```

**Comment by weihanglo** [comment]
Just checked the implementation of the lint: <https://github.com/rust-lang/rust-clippy/blob/706c48b62afb036d34dfa3d6119846edb0afda63/clippy_lints/src/cargo/wildcard_dependencies.rs#L10>. 

If I understand correctly, seems like it invokes `cargo metadata` and get direct dependencies **ONLY** from the first package, which is the first one as the array is in alphanumeric order. That's why you've got `sub_pop` checked but not your root package `wc_dep`.s 

This doesn't look like a Cargo issue, and since you've open an issue on clippy side. I'll close this in favor of <https://github.com/rust-lang/rust-clippy/issues/11409>.

In long term, I think cargo lints should be implemented in rust-lang/cargo, and clippy could focus on the thing it excels at — analyzing Rust code.

Thanks for the report!

**Comment by bobhy** [comment]
... thanks for your analysis!
