### ISSUE TITLE
Invalid proxy default for Cargo

### ISSUE THREAD

**Issue by arichr** [rust-lang/cargo#12566]
### Problem

I installed `stable` Cargo from `rustup` (which I got from a Manjaro package manager). When I created an empty project and tried to add a new dependency, Cargo said it couldn't connect to 127.0.0.1:9150.
```log
    Updating crates.io index
warning: spurious network error (3 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 9150 after 0 ms: Couldn't connect to server)
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 9150 after 0 ms: Couldn't connect to server)
[...]
```

### Steps

1. Install `rustup 1.26.0-3` by using `pacman`
2. `rustup toolchain install stable` 
3. Create a new project
4. Try to add a dependency to it

### Possible Solution(s)

Use Cargo with this configuration:
```toml
[http]
proxy = ""
```

### Notes

```console
$ rustup default
stable-x86_64-unknown-linux-gnu (default)
$ rustup --version
rustup 1.26.0 (2023-05-04)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.72.0 (5680fa18f 2023-08-23)`
$ uname -a
Linux hostname 6.1.44-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Aug  9 09:02:26 UTC 2023 x86_64 GNU/Linux
```

### Version

```text
cargo 1.72.0 (103a7ff2e 2023-08-15)
release: 1.72.0
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Linux [64-bit]
```

**Comment by Carreau** [comment]
Trying to reproduce here (on macos), and I can't. But it seem that [`CARGO_HTTP_PROXY` env variable](https://doc.rust-lang.org/cargo/reference/config.html#httpproxy) takes precedence. Any chance this is set, or any other things that would override `.config.toml` ?

**Comment by weihanglo** [comment]
You could check each of the environment variables:

* `CARGO_HTTP_PROXY`
* `HTTPS_PROXY`
* `https_proxy`
* `http_proxy`

Also, you could use `cargo +nightly -Zunstable-options config get http.proxy` to check if you've set the proxy config value elsewhere.

**Comment by Carreau** [comment]
Oh, nice, I see on `main`, you can even add `--show-origin` to show the provenance !

**Comment by arichr** [comment]
@Carreau @weihanglo 
No environment variables are set for the proxy:
```console
$ set | grep -i proxy
history '[...]'
```
Just installed `nightly`:
```console
$ cargo +nightly -Zunstable-options config get http.proxy
error: config value `http.proxy` is not set
$ cargo +nightly update
    Updating crates.io index
warning: spurious network error (3 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 9150 after 0 ms: Couldn't connect to server)
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 9150 after 0 ms: Couldn't connect to server)
[...]
```

**Comment by arichr** [comment]
The "possible solution" also works for `nightly`:
```console
$ cargo +nightly --config http.proxy=\"\" update
    Updating crates.io index
$ echo $status
0
```

**Comment by Carreau** [comment]
I have no idea, so I'm going to throw some random guesses: 

 - nothing in you `~/.netrc`, not your local/global git config ?

And I'm going to guess if you remove `proxy = ""` from the .toml file it works ....

**Comment by Carreau** [comment]
Also port 9150 is tor, did you play with tor recently ? Or have something going on with tor ?

**Comment by weihanglo** [comment]
Cargo respects these configurations as [documented here](https://doc.rust-lang.org/nightly/nightly-rustc/cargo/util/network/proxy/fn.http_proxy_exists.html).

Try `git config --show-origin http.proxy` to check if you set anything in `.git/config` or other git configuration files.

Also, try something like `curl https://github.com/rust-lang/crates.io-index` or `curl https://index.crates.io`, since under the hood libcurl is in use for proxies.

---

Beyond the investigation, if you can provide a minimal reproduction, like executing a set commands in a docker image, that would be a big help to resolve this.

**Comment by arichr** [comment]
I'm closing this issue, because somehow `.git/config` had proxy settings set. Thanks, @Carreau @weihanglo

**Comment by Carreau** [comment]
Great ! Enjoy your new project now.
