### ISSUE TITLE
cargo 0.73 build broken on windows

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#12562]
I updated cargo to 0.73 from crates.io in cargo-udeps ([commit](https://github.com/est31/cargo-udeps/commit/17f086096d69ee8d03d69bba91861007d8cf9e34)) and got the following [build failure on ci](https://github.com/est31/cargo-udeps/actions/runs/5980865638/job/16227804165):

```
 error[E0432]: unresolved import `windows_sys::Win32::Storage::FileSystem::LockFileEx`
   --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cargo-0.73.0\src/cargo\util\flock.rs:443:9
    |
443 |         LockFileEx, UnlockFile, LOCKFILE_EXCLUSIVE_LOCK, LOCKFILE_FAIL_IMMEDIATELY,
    |         ^^^^^^^^^^
    |         |
    |         no `LockFileEx` in `Windows::Win32::Storage::FileSystem`
    |         help: a similar name exists in the module: `LockFile`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `cargo` (lib) due to previous error
```

If you look at the [rustdoc for LockFileEx](https://docs.rs/windows-sys/0.48.0/windows_sys/Win32/Storage/FileSystem/fn.LockFileEx.html), it writes:

```
Required features: "Win32_Storage_FileSystem", "Win32_Foundation", "Win32_System_IO"
```

Compare this with the Cargo.toml of 0.73:

https://github.com/rust-lang/cargo/blob/103a7ff2ee7678d34f34d778614c5eb2525ae9de/Cargo.toml#L180-L188

The former two are found while `Win32_System_IO` isn't present. I suppose this is the cause for the failure: in the `cargo` repo this works fine because of dependency unification and another crate in the DAG enabling the `Win32_System_IO` features. But if you use `cargo` from crates.io, then it is not enabled, which is what I ran into.

The fix is simple, just add `Win32_System_IO` to the list. Ideally this would also be published in a new release.

I have worked around the issue by making cargo-udeps depend on windows-sys and enabling the feature ([commit](https://github.com/est31/cargo-udeps/commit/51e2285425a5dcbe68c4b4ef8d0f2c5026da59bb)).

**Comment by est31** [comment]
So apparently with master cargo the issue doesn't occur, as seen in the second commit of my PR https://github.com/est31/cargo-udeps/pull/194 . the third commit uses cargo 0.73 from git and reproduces the issue. The fourth commit applies a [patch](https://github.com/est31/cargo/commit/93cc7c897b307392748f4b1e3e1fb3e94c3526fd) that just adds `Win32_System_IO` and it fixes the issue. IDK about beta cargo or what changed to fix the issue until master.

**Comment by weihanglo** [comment]
Thanks for the report! This was introduced by <https://github.com/rust-lang/cargo/pull/12176>, which claimed has tested against each crate.

The short term plan here is adding back missing features. In long term we might adding tool like [`cargo-hack`](https://crates.io/crates/cargo-hack) or [`cargo-hakari`](https://crates.io/crates/cargo-hakari) to prevent this from happening again.

We might also have a deeper look at <https://github.com/rust-lang/cargo/issues/11987>, which might not worth pursuing in CI.

Sorry for the inconvenience 😞.

**Comment by ehuss** [comment]
0.73.1 should be published now.

I opened #12567 to try to figure out if there is some way to avoid this in the future.

**Comment by est31** [comment]
@ehuss @weihanglo thanks for the quick fix!
