### ISSUE TITLE
Better error message when registry is added to Cargo.toml instead of Cargo config

### ISSUE THREAD

**Issue by BatmanAoD** [rust-lang/cargo#12576]
### Problem

Alternative registries are added in Cargo-config (e.g. `~/.cargo/config.toml`), not in a project's `Cargo.toml` file.

If a registry is added in `Cargo.toml` but not used, a helpful warning is printed:

```
warning: unused manifest key: registries
```

If, however, a dependency is added that uses the alternate registry, only an error message is shown:

```
error: failed to parse manifest at `<path>\Cargo.toml`

Caused by:
  no index found for registry: `<name>`
```

This is actually somewhat confusing: I initially didn't notice that the `dependencies` section belongs in a different file, so when I got this error, I thought it was a problem with the registry URL or syntax.

### Proposed Solution

Multiple possible solutions, with different levels of effort:

* Change the wording of the `no index found` message to explicitly mention `config.toml`. For instance, it could be reworded as `registry index was not found in any config.toml` file
* Print the `unused manifest keys` warning even if the manifest fails to parse (I'm not sure how easy this would be)
* When the `no index found` message occurs, explicitly check to see if `Cargo.toml` has a `registries` section, and if so, print a separate error message, something like "`registries` must be defined in `config.toml`; see https://doc.rust-lang.org/cargo/reference/config.html"
* Just permit `registries` to be in either `config.toml` or `Cargo.toml` (I'm assuming there's a good reason for _not_ doing this, though).

**Comment by BatmanAoD** [comment]
It looks like #12531 might indirectly make it easier to control whether warnings are still printed when there's a hard error, making the 2nd suggestion ("Print the `unused manifest keys` warning...") more viable.

**Comment by weihanglo** [comment]
In short term, I feel like the option one is the way to go: 

```
registry index was not found in any configuration: {reg_name}
```

@rustbot label: -S-triage +S-accepted +E-easy +A-error +A-registries

**Comment by torhovland** [comment]
Looks like this issue should be closed as fixed.

**Comment by dev-ardi** [comment]
This is better but it's still not great. Maybe add a suggestion on how to fix?

```
hint: add this to `.cargo/config.toml`:

[registries.{reg_name}]
index = [the link to your index]
```
