### ISSUE TITLE
Consider whether `--keep-going` deserves a short flag (`-k`?)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#12571]
This issue is to track a suggestion brought forth by @joshtriplett in https://github.com/rust-lang/cargo/pull/10383#issuecomment-1081100749.

> _"I'd also love to see a `-k` shorthand added, similar to `make -k`; the nature of this option is such that it'd should be easy for people to invoke."_

As part of stabilization of `--keep-going` in https://github.com/rust-lang/cargo/issues/10496#issuecomment-1677102935, it was decided to stabilize without `-k` and defer a thorougher consideration of `-k` to a followup issue.

> _"For `-k` short alias, I'll create an issue for it after the FCP."_

**Comment by dtolnay** [comment]
FWIW for my own use case in https://github.com/dtolnay/trybuild which motivated `--keep-going`, I don't need `-k` and wouldn't use it.

**Comment by joshtriplett** [comment]
One option would be to go ahead and add this, on the theory that people may want it. Another would be to let people use `--keep-going` for a while, and see if it gets used manually (rather than by other tools) often enough to warrant a short option.

**Comment by epage** [comment]
I lean towards the latter.

**Comment by joshtriplett** [comment]
Likewise.

**Comment by dtolnay** [comment]
I have been happily using `--keep-going` in the `trybuild` crate for 9 months to great effect, which was my original motivation for contributing this flag. So far I have not had any occasion to use this flag in interactive command-line usage, despite the existence of the flag being clearly well-known to me.

I think I would close this issue, and just rely on anyone for whom this flag appears commonly in their interactive workflow to make the case for a short flag in a separate issue, as they would for any other long-only flag that has been stable for longer.

**Comment by saurik** [comment]
Did you also not use it with make? FWIW, I use it all the time with make... it is much more rare that I want to have a build stop short despite a single error. Regardless, it is certainly a common enough use for me that it was strange that --keep-going (which is annoying to type, but does at least work) isn't even documented in --help (which is how I ended up in these issues).

**Comment by saurik** [comment]
Did you also not use it with make? :( FWIW, I use it all the time with make... it is much more rare that I want to have a build stop short despite a single error. ;P I often want to start a long build and then task switch away to come back to a really complete list of errors to deal with.
