### ISSUE TITLE
Automatically build packages on crates.io on various platforms

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#1257]
It would be great if crates.io provided a build bots running on various platforms and marked on which platforms the package builds (and passes tests?) successfully.

* This would help detect packages that don't work on Windows or other systems (and perhaps allow users to filter out such packages from search results).

* It would help detecting missing (undeclared) dependencies and "works on my machine!" errors.

**Comment by steveklabnik** [comment]
I'm moving this over to the crates.io repository.
