### ISSUE TITLE
Can’t build and run rust application using cargo 

### ISSUE THREAD

**Issue by Adooobe** [rust-lang/cargo#12577]
### Problem

I'm just getting started with Rust, and I wanna build and run 'Hello-Rust' demo created by `cargo new hello-rust`.

 but errors happened as follows:

> $HOME/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features --filter-platform aarch64-apple-darwin
> stdout : error: failed to parse the cfg from `rustc --print=cfg`, got:
> ___
> lib___.rlib
> lib___.dylib
> lib___.dylib
> lib___.a
> lib___.dylib
> $HOME/.rustup/toolchains/stable-aarch64-apple-darwin
> off
> packed
> unpacked
> ___
> debug_assertions
> panic="unwind"
> proc_macro
> target_arch="aarch64"
> target_endian="little"
> target_env=""
> target_family="unix"
> target_feature="aes"
> target_feature="crc"
> target_feature="dit"
> target_feature="dotprod"
> target_feature="dpb"
> target_feature="dpb2"
> target_feature="fcma"
> target_feature="fhm"
> target_feature="flagm"
> target_feature="fp16"
> target_feature="frintts"
> target_feature="jsconv"
> target_feature="lor"
> target_feature="lse"
> target_feature="neon"
> target_feature="paca"
> target_feature="pacg"
> target_feature="pan"
> target_feature="pmuv3"
> target_feature="ras"
> target_feature="rcpc"
> target_feature="rcpc2"
> target_feature="rdm"
> target_feature="sb"
> target_feature="sha2"
> target_feature="sha3"
> target_feature="ssbs"
> target_feature="vh"
> target_has_atomic="128"
> target_has_atomic="16"
> target_has_atomic="32"
> target_has_atomic="64"
> target_has_atomic="8"
> target_has_atomic="ptr"
> target_os="macOS"
> target_pointer_width="64"
> target_vendor="apple"
> unix
> 
> 
> 
> 
> 
> 
> Caused by:
>   failed to parse `` as a cfg expression: expected identifier, but cfg expression ended
> 
> 
> 
> 
> 
> stderr : 

I installed rust by `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` and did nothing except checking the version by `cargo -V & rustc -V`.

I execute `rustc --print=cfg`, then I got

```
rustc --print=cfg








debug_assertions
panic="unwind"
target_arch="aarch64"
target_endian="little"
target_env=""
target_family="unix"
target_feature="aes"
target_feature="crc"
target_feature="dit"
target_feature="dotprod"
target_feature="dpb"
target_feature="dpb2"
target_feature="fcma"
target_feature="fhm"
target_feature="flagm"
target_feature="fp16"
target_feature="frintts"
target_feature="jsconv"
target_feature="lor"
target_feature="lse"
target_feature="neon"
target_feature="paca"
target_feature="pacg"
target_feature="pan"
target_feature="pmuv3"
target_feature="ras"
target_feature="rcpc"
target_feature="rcpc2"
target_feature="rdm"
target_feature="sb"
target_feature="sha2"
target_feature="sha3"
target_feature="ssbs"
target_feature="vh"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="macos"
target_pointer_width="64"
target_vendor="apple"
unix
```

my rustc,cargo version is 1.71.0, and my OS version is MacOS13.4

### Steps

1. Install rust using `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh `  by default
2. cargo new hello-rust
3. cargo build

**Comment by Antelope13** [comment]
I'm encountering the same issue today on a Windows 11 machine with the latest nightly. `cargo new` works correctly, but `cargo build`, `cargo run`, and `cargo clean` fail silently, even with `-vv`. Using rustup to uninstall and reinstall the toolchain didn't fix the issue. Reverting to the previous version, `nightly-2023-08-27-x86_64-pc-windows-msvc`, fixes the issue.

For the current nightly:
```
cargo --version -vv
cargo 1.74.0-nightly (925280f02 2023-08-25)
release: 1.74.0-nightly
commit-hash: 925280f028db3a322935e040719a0754703947cf
commit-date: 2023-08-25
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:Schannel)
os: Windows 10.0.23531 (Windows 11 Professional) [64-bit]

rustc --version -v
rustc 1.74.0-nightly (4e78abb43 2023-08-28)
binary: rustc
commit-hash: 4e78abb437a0478d1f42115198ee45888e5330fd
commit-date: 2023-08-28
host: x86_64-pc-windows-msvc
release: 1.74.0-nightly
LLVM version: 17.0.0
```

**Comment by AdobeStu** [comment]
> 
Thx, but It seems useless to me.

**Comment by AdobeStu** [comment]
> I'm encountering the same issue today on a Windows 11 machine with the latest nightly. `cargo new` works correctly, but `cargo build`, `cargo run`, and `cargo clean` fail silently, even with `-vv`. Using rustup to uninstall and reinstall the toolchain didn't fix the issue. Reverting to the previous version, `nightly-2023-08-27-x86_64-pc-windows-msvc`, fixes the issue.
> 
> For the current nightly:
> 
> ```
> cargo --version -vv
> cargo 1.74.0-nightly (925280f02 2023-08-25)
> release: 1.74.0-nightly
> commit-hash: 925280f028db3a322935e040719a0754703947cf
> commit-date: 2023-08-25
> host: x86_64-pc-windows-msvc
> libgit2: 1.6.4 (sys:0.17.2 vendored)
> libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:Schannel)
> os: Windows 10.0.23531 (Windows 11 Professional) [64-bit]
> 
> rustc --version -v
> rustc 1.74.0-nightly (4e78abb43 2023-08-28)
> binary: rustc
> commit-hash: 4e78abb437a0478d1f42115198ee45888e5330fd
> commit-date: 2023-08-28
> host: x86_64-pc-windows-msvc
> release: 1.74.0-nightly
> LLVM version: 17.0.0
> ```



> I'm encountering the same issue today on a Windows 11 machine with the latest nightly. `cargo new` works correctly, but `cargo build`, `cargo run`, and `cargo clean` fail silently, even with `-vv`. Using rustup to uninstall and reinstall the toolchain didn't fix the issue. Reverting to the previous version, `nightly-2023-08-27-x86_64-pc-windows-msvc`, fixes the issue.
> 
> For the current nightly:
> 
> ```
> cargo --version -vv
> cargo 1.74.0-nightly (925280f02 2023-08-25)
> release: 1.74.0-nightly
> commit-hash: 925280f028db3a322935e040719a0754703947cf
> commit-date: 2023-08-25
> host: x86_64-pc-windows-msvc
> libgit2: 1.6.4 (sys:0.17.2 vendored)
> libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:Schannel)
> os: Windows 10.0.23531 (Windows 11 Professional) [64-bit]
> 
> rustc --version -v
> rustc 1.74.0-nightly (4e78abb43 2023-08-28)
> binary: rustc
> commit-hash: 4e78abb437a0478d1f42115198ee45888e5330fd
> commit-date: 2023-08-28
> host: x86_64-pc-windows-msvc
> release: 1.74.0-nightly
> LLVM version: 17.0.0
> ```

Thx, but It seems useless to me.

**Comment by AdobeStu** [comment]
> I'm encountering the same issue today on a Windows 11 machine with the latest nightly. `cargo new` works correctly, but `cargo build`, `cargo run`, and `cargo clean` fail silently, even with `-vv`. Using rustup to uninstall and reinstall the toolchain didn't fix the issue. Reverting to the previous version, `nightly-2023-08-27-x86_64-pc-windows-msvc`, fixes the issue.
> 
> For the current nightly:
> 
> ```
> cargo --version -vv
> cargo 1.74.0-nightly (925280f02 2023-08-25)
> release: 1.74.0-nightly
> commit-hash: 925280f028db3a322935e040719a0754703947cf
> commit-date: 2023-08-25
> host: x86_64-pc-windows-msvc
> libgit2: 1.6.4 (sys:0.17.2 vendored)
> libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:Schannel)
> os: Windows 10.0.23531 (Windows 11 Professional) [64-bit]
> 
> rustc --version -v
> rustc 1.74.0-nightly (4e78abb43 2023-08-28)
> binary: rustc
> commit-hash: 4e78abb437a0478d1f42115198ee45888e5330fd
> commit-date: 2023-08-28
> host: x86_64-pc-windows-msvc
> release: 1.74.0-nightly
> LLVM version: 17.0.0
> ```

Thx, but It seems useless to me.

**Comment by ehuss** [comment]
@AdobeStu can you please include the output of `cargo --version --verbose` and `rustc --version --verbose`? Can you try upgrading to the latest stable version (1.72)? Can you verify that `which rustc` print the path to `~/.cargo/bin/rustc`?

> $HOME/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features --filter-platform aarch64-apple-darwin

This looks like a fairly peculiar command to be running for a basic hello-world project. Can you say more about what you are doing, and what your environment is like? What is running that command?

**Comment by Adooobe** [comment]
> @AdobeStu can you please include the output of `cargo --version --verbose` and `rustc --version --verbose`? Can you try upgrading to the latest stable version (1.72)? Can you verify that `which rustc` print the path to `~/.cargo/bin/rustc`?
> 
> > $HOME/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features --filter-platform aarch64-apple-darwin
> 
> This looks like a fairly peculiar command to be running for a basic hello-world project. Can you say more about what you are doing, and what your environment is like? What is running that command?

@ehuss hi, Sry to answer you so late. I tried to change my rust version to 1.72 and the path of `which rustc` has been changed to `~/.cargo/bin/rustc`. And more over, I didn't do any other things except trying to run hello-world with Cargo.  I execute `cargo build` command only (and I got the error:( ). By the way, I can build & run successfully the hello-world project without Cargo. 
So any other things Can I provide to help solve this tough problem?

**Comment by weihanglo** [comment]
> @AdobeStu can you please include the output of `cargo --version --verbose` and `rustc --version --verbose`? 

Any chance you can have this information shared?

**Comment by Adooobe** [comment]
> > @AdobeStu can you please include the output of `cargo --version --verbose` and `rustc --version --verbose`?
> 
> Any chance you can have this information shared?

@weihanglo  Sure.

> cargo --version --verbose:
> cargo 1.72.0 (103a7ff2e 2023-08-15)
> release: 1.72.0
> commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
> commit-date: 2023-08-15
> host: aarch64-apple-darwin
> libgit2: 1.6.4 (sys:0.17.2 vendored)
> libcurl: 7.88.1 (sys:0.4.63+curl-8.1.2 system ssl:(SecureTransport) LibreSSL/3.3.6)
> ssl: OpenSSL 1.1.1u  30 May 2023
> os: Mac OS 13.4.0 [64-bit]

And rustc --version --verbose:

> rustc 1.72.0 (5680fa18f 2023-08-23)
> binary: rustc
> commit-hash: 5680fa18feaa87f3ff04063800aec256c3d4b4be
> commit-date: 2023-08-23
> host: aarch64-apple-darwin
> release: 1.72.0
> LLVM version: 16.0.5

**Comment by ehuss** [comment]
@Adooobe I'm sorry we weren't able to help with diagnosing your issue. I'm going to close since this is quite old, and there isn't an obvious way to figure out what might have gone wrong. If you are still experiencing a problem, please feel free to reopen, and we can try to diagnose what is going wrong. 

The issue appears that `rustc` is printing blank lines in its config output which is not a valid output for it. I have not heard of anyone else running into this issue, and I don't see from the code how that might be possible.

I suspect there might be some issue with the installation or environment. We have limited ability to help support installing Rust here, but you may get better support on one of the user forums such as https://users.rust-lang.org/.
