### ISSUE TITLE
Unable to get packages from source

### ISSUE THREAD

**Issue by SUNKIST-EDEN** [rust-lang/cargo#1258]
Cargo version.
```
cargo 0.0.1-pre-nightly (2b9a3d6 2015-01-30 02:47:30 +0000)
```

Error output from cargo build --verbose.
```
 Downloading bitflags v0.1.0
Unable to get packages from source

Caused by:
  Failed to download package `bitflags v0.1.0` from https://crates.io/api/v1/crates/bitflags/0.1.0/download

Caused by:
  SSL connect error
```

Output of command ipconfig /displaydns after flushing it and run the above command.
```
Windows IP Configuration

    crates.io
    ----------------------------------------
    Record Name . . . . . : crates.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 216
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 23.23.121.177


    Record Name . . . . . : crates.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 216
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 54.243.209.93


    Record Name . . . . . : crates.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 216
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 54.225.123.15
```

Excerpt at Cargo.toml file.
```
[[package]]
name = "bitflags"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
```

I'm not behind a proxy.
Other packages like clock_ticks downloaded fine. That (bitflags) and rustc-serialize don't.

**Comment by alexcrichton** [comment]
Can you run `curl -OL https://crates.io/api/v1/crates/bitflags/0.1.0/download` and paste what it outputs?

**Comment by SUNKIST-EDEN** [comment]
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  8667  100  8667    0     0   3678      0  0:00:02  0:00:02 --:--:-- 17907
```

**Comment by SUNKIST-EDEN** [comment]
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  8667  100  8667    0     0   3779      0  0:00:02  0:00:02 --:--:-- 18519
```

**Comment by SUNKIST-EDEN** [comment]
Uhh, when the build fails there's a blocked connection
```
INBOUND ip_here_from_crates_io port 443 to local_ip registered_ports(1024 through 49151)
```
Why crates.io connecting via inbound but when it's a git it's okay with just outbound?

**Comment by alexcrichton** [comment]
That is... quite surprising! I would not expect libcurl to start accepting connections at all.

**Comment by alexcrichton** [comment]
Are you using a firewall locally? (something I could try to reproduce with).

**Comment by eswordthecat** [comment]
TinyWall http://tinywall.pados.hu/

**Comment by SUNKIST-EDEN** [comment]
Tinywall, http://tinywall.pados.hu/

**Comment by alexcrichton** [comment]
Are you sure the firewall wasn't accidentally blocking cargo itself?

**Comment by SUNKIST-EDEN** [comment]
It was fine on github links (only outbound). It's not on crates.io because it was requesting an inbound access (why?).

**Comment by alexcrichton** [comment]
How did you determine that was an inbound access? I couldn't find the relevant logs in tinywall

**Comment by SUNKIST-EDEN** [comment]
Right click TinyWall at taskbar, change mode to normal protection (you'll loose internet access so revert it later) add cargo.exe to application exceptions with radio button set to allow only specified ports and put 443 at out tcp (for github and should be for crates.io too) click ok then right click again tinywall at taskbar show connections untick show active ... and tick show blocked apps. Do cargo build --version something then click refresh to see crates.io wants to inbound (it's 443 at source port and a crates.io ip at local/source address column, destination columns is self explanatory).

**Comment by alexcrichton** [comment]
Thanks for the details! I believe I was able to configure everything correctly. My local build, however, completed just fine (after downloading a bunch of packages). I did, however, see some blocked incoming connections (they say they're from `System(0)`...).

I'm really not quite sure why this is happening, maybe it's some new fancy HTTP/2 thing implemented in libcurl? I'm surprised that it's outright failing for you when it succeeds for me...

**Comment by SUNKIST-EDEN** [comment]
Is the piston crate the one you tested?

**Comment by SUNKIST-EDEN** [comment]
```
>cargo build --verbose
    Updating git repository `https://github.com/PistonDevelopers/piston.git`
    Updating git repository `https://github.com/pistondevelopers/input`
    Updating git repository `https://github.com/pistondevelopers/event`
    Updating git repository `https://github.com/pistondevelopers/quack`
    Updating git repository `https://github.com/pistondevelopers/window`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/PistonDevelopers/event_loop`
    Updating git repository `https://github.com/tomaka/clock_ticks`
 Downloading bitflags v0.1.0
Unable to get packages from source

Caused by:
  Failed to download package `bitflags v0.1.0` from https://crates.io/api/v1/cra
tes/bitflags/0.1.0/download

Caused by:
  SSL connect error
```

**Comment by alexcrichton** [comment]
Which piston crate are you building?

**Comment by retep998** [comment]
I sometimes run into this issue when Cargo downloads packages from crates.io. It is always a fleeting occurrence and I can never get it to reliably occur. Usually just trying again gets things to pass. It would be really nice if Cargo could at least retry the download a couple times if it failed. That way for people who just have intermittent issues, this problem would be mitigated.

**Comment by Domii894** [comment]
Hey guys!
I don't want to annoy your conversation but I got the same issue. Disabling the firewall didn't help. (I use bitdefender)

I got the cargo version:
0-0.1-pre-nightly (a58ffd7 2015-02-27)
I tested some other things but nothing worked.

Now I thought to directly inform you guys about my issue. As far as I have seen that there are also other people, who have the same error.
Thanks :)

**Comment by alexcrichton** [comment]
I think that this was probably just intermittent, so I'm going to close this in favor of  https://github.com/rust-lang/cargo/issues/1602
