### ISSUE TITLE
Persistent warning: link against the following native artifacts

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#1260]
When building a static library Cargo prints:

> warning: link against the following native artifacts when linking against this static library

The problem is when I invoke Cargo from Xcode, Xcode detects the "warning: " and displays it as if it was a real issue requiring attention.

As far as I can tell it's not possible to "fix" anything to make that warning disappear (Cargo won't stop displaying it, because it can't know if I link everything in the correct order), so it's noise.

Could you downgrade that message to a note?

**Comment by alexcrichton** [comment]
This is actually more of a Rust issue than a Cargo issue, but I [opened a PR](https://github.com/rust-lang/rust/pull/21849) regardless!

**Comment by pornel** [comment]
Thank you :)
