### ISSUE TITLE
`cargo rm` cannot handle wildcard package spec in profile setting overrides

### ISSUE THREAD

**Issue by cyqsimon** [rust-lang/cargo#12620]
### Problem

When using the wildcard syntax to specify [profile setting overrides](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides) for all dependencies, `cargo rm` will error:

> error: invalid character `*` in pkgid: `*`, the first character must be a Unicode XID start character (most letters or `_`)

### Steps

1. Create a new cargo project
2. Add the following section to `Cargo.toml`:
```toml
[profile.dev.package."*"]
opt-level = 3
```
3. Run `cargo add foo`
4. Run `cargo rm foo`, and observe the error

### Version

```text
cargo 1.72.0 (103a7ff2e 2023-08-15)
release: 1.72.0
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: EndeavourOS Rolling Release (rolling) [64-bit]
```

**Comment by weihanglo** [comment]
The reason `cargo rm` does this is that it garbage-collects related fields in your Cargo.toml. For example, if you have a `[profile.dev.package."foo"]` it will be gc'd.

This line bails out when parsing `*`, which is not a valid `PackageIdSpec`.

https://github.com/rust-lang/cargo/blob/cff6d19f6e3966972e768bcabd944747aeb16469/src/bin/cargo/commands/remove.rs#L235

To fix this, we may probably just skip `*`.
