### ISSUE TITLE
Errors for transitive resolution failures are lacking

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#1263]
Servo depends on hyper, which depends on cookie-rs, which depends on the url crate. I made a change which switched the version of hyper in use to one which depended on a much older version of cookie-rs that depended on a very old version of rust-url that couldn't be resolved. The only information cargo gave me was:

```
Updating git repository https://github.com/servo/hyper
Updating git repository https://github.com/servo/cookie-rs
Updating git repository https://github.com/servo/cookie-rs
Updating git repository https://github.com/rust-lang/time
Updating git repository https://github.com/sfackler/rust-openssl
Updating git repository https://github.com/servo/rust-url
no package named url found (required by cookie)
location searched: https://github.com/servo/rust-url
version required: ^0.1.0
```

**Comment by jdm** [comment]
Information like the chain of dependencies that led to this unresolvable package would be useful, as would be the versions that were found that didn't satisfy the constraint, I suppose.

**Comment by jdm** [comment]
Additionally, Servo has its own dependency on cookie-rs, which made it even more confusing when trying to sort out the chain of dependency problems.

**Comment by Eh2406** [comment]
This should be much better now. Move to close.

**Comment by alexcrichton** [comment]
Indeed!
