### ISSUE TITLE
Can't build hello_word in example

### ISSUE THREAD

**Issue by michaelgwelch** [rust-lang/cargo#1264]
I'm following instructions for [hello_world](http://doc.rust-lang.org/nightly/intro.html).

```shell
$ cargo new hello_world --bin
```

Everything looks fine: the generated directory structure and files look like the ones in the sample. 

However, I get build errors trying to compile.

```shell
$ cargo run
An unknown error occurred

To learn more, run the command again with --verbose.
$ cargo run --verbose
Process didn't exit successfully: 'rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names' (status=101)
--- stderr
error: Unrecognized option: 'print'.
```

I'm running on a Mac running OS X 10.10.2. I installed rust using brew and cargo using homebrew cask. Here are the versions that were installed:

```shell
$ rustc --version
rustc 0.12.0-dev
$ cargo --version
cargo 0.0.1-pre-nightly (2b9a3d6 2015-01-30 02:47:30 +0000)
```

**Comment by alexcrichton** [comment]
It looks like your version for rustc is a bit out of date, the cargo nightlies are intended to work with the most recently rustc nightlies for now.

Once you update rustc everything should work ok again!

**Comment by michaelgwelch** [comment]
Yes, that was it. (I assumed I had the latest because I just installed it today. I had to `brew update` and `brew upgrade rust` to get the latest which appears to be `1.0.0-alpha`)
