### ISSUE TITLE
build-override results in the same dependency being compiled twice

### ISSUE THREAD

**Issue by link2xt** [rust-lang/cargo#12645]
### Problem

I am compiling tag v1.121.0 of https://github.com/deltachat/deltachat-core-rust with command `cargo build`. It compiles `aho-corasick v1.0.2` dependency twice, once as a dependency and once as a build dependency, resulting in two `.rlib` field being produced and actually slowing down the build process rather than speeding it up as intended by the build-override feature.

### Steps

1. Clone https://github.com/deltachat/deltachat-core-rust, tag v1.121.0, commit a8551510cdb5be7a35ebd3574df79d15a4fa471a
2. Run `cargo build -v`.
3. Observe `aho-corasick v1.0.2` dependency being compiled twice. Once as a proper dependency with `-C panic=abort` as specified in the manifest, and once as a build dependency without `-C panic=abort`.
4. Try to specify `panic='abort'` in the `[profile.dev.build-override]` section of `Cargo.toml` as a workaround, it results in an error "`panic` may not be specified in a `build-override` profile".

### Possible Solution(s)

Do not apply `build-override` to dependencies that are actual dependencies of the project? Or allow to disable build-override completely.

### Notes

I wrote a longer thread with my observations of the build times and duplicate builds of dependencies at https://users.rust-lang.org/t/same-dependency-has-four-different-debug-fingerprints/99580

### Version

```text
$ cargo version --verbose
cargo 1.72.0
release: 1.72.0
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1 (sys:0.4.63+curl-8.1.2 system ssl:OpenSSL/3.1.2)
os: Arch Linux [64-bit]
```

**Comment by weihanglo** [comment]
That's a consequence of [this setting](https://github.com/deltachat/deltachat-core-rust/blob/a8551510cdb5be7a35ebd3574df79d15a4fa471a/Cargo.toml#L10), not `build-override`. Guess you just had a typo 🤔.

By default, the panic strategy applies to build scripts and build dependencies is `panic = "unwind"`. This cannot be overridden. Here are some [prior discussions](https://github.com/rust-lang/cargo/pull/5384#issuecomment-383403070).

Compiler settings of build scripts are usually different from normal dependencies. This is kind of a tradeoff and somebody may run into the bad part. However, I don't really know why we cannot force change panic for build scripts. Let's nominate this to discuss.

**Comment by weihanglo** [comment]
Sorry not being clear. I meant the title is a bit misleading. It's about the panic setting always sticking to unwind. If that is the case, could you update to something like "support `panic` for `build-override` profile"?

**Comment by weihanglo** [comment]
> cargo could detect automatically that dependency is used as a normal dependency and build dependency and use normal dependency built will all optimizations without the build override

As ehuss said in <https://github.com/rust-lang/cargo/issues/12647#issuecomment-1711740622>, it's unlikely for Cargo to know whether a build script could be built with `panic=abort`, given a build script can have arbitrary code. At this time, `lto`, `rpath`, `panic` are kinda global settings that you cannot set a different value for a single dependency. For other profile settings, build artifacts should be shared between normal and build in usual situations.

Going to close this as not planned, but let us know if you've got new thought to resolve the limitation.
