### ISSUE TITLE
Allow to set `panic='abort'` in `build-override`

### ISSUE THREAD

**Issue by link2xt** [rust-lang/cargo#12647]
### Problem

Currently trying to create a section `[profile.dev.build-override]` with `panic='abort'` results in error "`panic` may not be specified in a build-override profile".

This validation seems to have been added for the `test` override to make sure tests are not built without `panic='unwind'` according to discussions in https://github.com/rust-lang/cargo/pull/5384#issuecomment-383403070

### Proposed Solution

Remove unnecessary validation for the build override.

### Notes

This issue is a spin-off of #12645

**Comment by ehuss** [comment]
It is not possible to build proc-macros with abort since they are loaded within the compiler. Additionally, some build scripts will fail with panic=abort since they rely on catching unwinding. Can you say more about what you are trying to do and why?

**Comment by weihanglo** [comment]
It's unfortunate there are some limitations described in <https://github.com/rust-lang/cargo/issues/12647#issuecomment-1711740622>. I would probably unset `panic=abort` in `dev` profile if appropriate, and only set it in `release` profile.

Closing. If you have an idea to circumvent the behavior, please share.

See also https://github.com/rust-lang/cargo/issues/12645#issuecomment-1713642419
