### ISSUE TITLE
can't resolve local deps

### ISSUE THREAD

**Issue by HomyeeKing** [rust-lang/cargo#12653]
### Code

```Rust
[package]
name = "gito"
version = "0.2.7"
description = "A tool to expand the ability of git"
categories = ["command-line-utilities"]
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
license.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
regex = "1"
serde_json = "1.0.91"
colored = "2.0.0"
gito_core = {path = "../core"}  # <----- this line
# gito_core = "1.0.3"
rust-ini = "0.18.0"
home = "0.5.4"
prettytable = "0.10.0"
```

### Current output

```Shell
failed to resolve: use of undeclared crate or module `gito_core`
```

### Anything else?

here's a reproduce [repo](https://github.com/HomyeeKing/gito/blob/repro/packages/cli/Cargo.toml?rgh-link-date=2023-08-20T15%3A32%3A42Z#L22)

**Comment by weihanglo** [comment]
https://github.com/rust-lang/cargo/blob/2fc85d15a542bfb610aff7682073412cf635352f/src/cargo/core/compiler/mod.rs#L1269-L1272

Cargo already emits such a warning:

> warning: The package `gito_core` provides no linkable target. The compiler might raise an error while compiling `xx`. Consider adding 'dylib' or 'rlib' to key `crate-type` in `gito_core`'s Cargo.toml. This warning might turn into a hard error in the future.

This is a known limitation. Please follow the message to adjust your `Cargo.toml`. Thank you.
