### ISSUE TITLE
cargo clippy invokes cargo for another target

### ISSUE THREAD

**Issue by ognevnydemon** [rust-lang/cargo#12656]
### Problem

I have [GHA workflow](https://github.com/ognevnydemon/ognlib/blob/master/.github/workflows/rust.yml) that runs check on MSYS2 provided rust package on Windows runner. When it runs `cargo clippy -- -D warnings` it invokes rustc from rustup with *-msvc target. it can be seen [here](https://github.com/ognevnydemon/ognlib/actions/runs/6149268169/job/16684767703#step=clippy).
@mati865

### Steps

1. install rust toolchain for `x86_64-pc-windows-msvc` target.
2. install rust toolchain and needed dependencies via [MSYS2](https://msys2.org/):
```console
$ pacman -S mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-autotools
```
3. fetch crate's repository `git clone https://github.com/ognevnydemon/ognlib.git`
4. run `cargo build` (get ready for a very big compile-time)
5. run `cargo clippy -- -D warnings`

### Notes

--offline flag returns an error because cargo wants to download deps for *-msvc target ([log](https://github.com/ognevnydemon/ognlib/actions/runs/6149062056/job/16684146843#step=clippy));
--target flag is ignored ([log](https://github.com/ognevnydemon/ognlib/actions/runs/6149414678/job/16685246794#step=clippy)). 

### Version

```text
if run `cargo -vV` in workflow

cargo 1.72.0
release: 1.72.0
host: x86_64-pc-windows-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:Schannel)
os: Windows 10.0.20348 (Windows Server 2022 Datacenter) [64-bit]
```

**Comment by mati865** [comment]
This happens even when `~/.cargo/bin` is not in PATH so I think Cargo just calls Rustup proxy binaries from their default locations when calling subcommands that call external tools.

**Comment by weihanglo** [comment]
https://github.com/ognevnydemon/ognlib/actions/runs/6149062056/workflow#L47-L52

Why `cargo b -v` was invoked from `${MINGW_PREFIX}` but not for clippy? Were they resolved to the same cargo?

```
      - name: build
        shell: msys2 {0}
        run: ${MINGW_PREFIX}/bin/cargo b -v
      - name: clippy
        shell: msys2 {0}
        run: cargo clippy -v --offline -- -D warnings
```


OTOH, `rust-clippy` [command invokes `cargo` again from PATH](https://github.com/rust-lang/rust-clippy/blob/98363cbf6a7c3f8b571a7d92a3c645bb4376e4a6/src/main.rs#L131), so it may also be resolved to a different `cargo` than calling `cargo`.

**Comment by ognevnydemon** [comment]
> Why `cargo b -v` was invoked from `${MINGW_PREFIX}` but not for clippy? Were they resolved to the same cargo?
> 
> ```
>       - name: build
>         shell: msys2 {0}
>         run: ${MINGW_PREFIX}/bin/cargo b -v
>       - name: clippy
>         shell: msys2 {0}
>         run: cargo clippy -v --offline -- -D warnings
> ```

there is action where I specified `${MINGW_PACKAGE_PREFIX}/bin/cargo`. it also doesn't help

**Comment by ognevnydemon** [comment]
> OTOH, `rust-clippy` [command invokes `cargo` again from PATH](https://github.com/rust-lang/rust-clippy/blob/98363cbf6a7c3f8b571a7d92a3c645bb4376e4a6/src/main.rs#L131), so it may also be resolved to a different `cargo` than calling `cargo`.

thanks for this information. the only thing left is to somehow remove rust toolchain from rustup

**Comment by mati865** [comment]
Isn't it Cargo's responsibility to call correct Clippy driver?

```
$ echo $PATH
/clang64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

$ which cargo
/clang64/bin/cargo

$ cargo -V
cargo 1.72.0

$ which cargo-clippy
/clang64/bin/cargo-clippy

$ cargo clippy -V
clippy 0.1.74 (030e4d38 2023-09-10)

$ cargo-clippy -V
clippy 0.1.72
```
There is no Rustup provided Cargo in `PATH`, yet running `cargo clippy -V` calls `/c/Users/<username>/.cargo/bin/cargo-clippy.exe` which is set to nightly toolchain on my machine.

**Comment by ognevnydemon** [comment]
> FWIW, it seems unusual to install rust from MSYS2 if there is also a rustup-installed version. Typically if you want to test the `-gnu` toolchain, that just involves running `rustup target add x86_64-pc-windows-gnu` or if for some reason you really need a `gnu` host that can be installed as well. I'm curious if there is some reason that doesn't work?
> 

but also I need to remove `-msvc` target because it breaks build. I'm not user of rustup, will `rustup target remove x86_64-pc-windows-msvc` work?

**Comment by ognevnydemon** [comment]
forgot to say, the `x86_64-pc-windows-gnu` from rustup fails to compile my project. maybe after migration to another dependency it will, but I'm not sure actually

**Comment by ognevnydemon** [comment]
> but also I need to remove `-msvc` target because it breaks build. I'm not user of rustup, will `rustup target remove x86_64-pc-windows-msvc` work?

it also failed for very interesting reason https://github.com/ognevnydemon/ognlib/actions/runs/6162019845/job/16722571923#step=clippy

**Comment by ehuss** [comment]
rustc defaults to using the same target as the host toolchain, and the host target is required for proc-macros and build scripts. Since the workflow file is still using the `-msvc` toolchain, it is trying to build for msvc, but `rustup target remove x86_64-pc-windows-msvc` removed it.

The different ways to do this are:

1. Use msvc host, with gnu target:
```
rustup target add x86_64-pc-windows-gnu
cargo clippy --target x86_64-pc-windows-gnu
```

2. Use gnu host, with gnu target:
```
rustup toolchain install stable-x86_64-pc-windows-gnu
rustup default stable-x86_64-pc-windows-gnu
cargo clippy
```

I'm not suggesting you should change the setup, just curious why it was done that way.

**Comment by ognevnydemon** [comment]
> rustc defaults to using the same target as the host toolchain, and the host target is required for proc-macros and build scripts. Since the workflow file is still using the `-msvc` toolchain, it is trying to build for msvc, but `rustup target remove x86_64-pc-windows-msvc` removed it.

the host for msys2.cmd is rust from MSYS2. and it **doesn't** use msvc toolchain. if it do, then I will receive error every time because one dependency **does not compiles** for msvc toolchain

**Comment by ognevnydemon** [comment]
tried to fully switch to -gnu host from it rustup. it fails with
```console
configure: error: No usable m4 in $PATH or /usr/5bin (see config.log for reasons).
```
([log](https://github.com/ognevnydemon/ognlib/actions/runs/6162816826/job/16725059896#step=build)). m4 is provided only by MSYS2 AFAIK

**Comment by ognevnydemon** [comment]
anyway IMO this is cargo issue when it doesn't let you to fully use toolchain if you have several toolchains installed

**Comment by mati865** [comment]
> tried to fully switch to -gnu host from it rustup. it fails with
> 
> ```
> configure: error: No usable m4 in $PATH or /usr/5bin (see config.log for reasons).
> ```
> 
> ([log](https://github.com/ognevnydemon/ognlib/actions/runs/6162816826/job/16725059896#step=build)). m4 is provided only by MSYS2 AFAIK

You haven't added MSYS2 to `PATH` because `#shell: msys2 {0}` is commented out.
But it wouldn't work anyway because `-gnu` target doesn't LLVM mingw-w64 toolchains like `CLANG64` provided by MSYS2.

**Comment by ognevnydemon** [comment]
> 
> You haven't added MSYS2 to `PATH` because `#shell: msys2 {0}` is commented out.
> But it wouldn't work anyway because `-gnu` target doesn't LLVM mingw-w64 toolchains like `CLANG64` provided by MSYS2.

I know, I just showed that host change doesn't help anyway
