### ISSUE TITLE
Enable build on multiple hosts without causing a full recompile.

### ISSUE THREAD

**Issue by hugoduncan** [rust-lang/cargo#1266]
When working on cross-platform code, it is useful to have a source directory mounted in several vms, with different operating systems, so changes can be rapidly tested on all targets.

When running `cargo build` on a different host (VM), cargo does a full recompile of the whole project, which slows down running of tests, etc.

The problem seems to be due to `cargo build` using paths for build artifacts that aren't scoped by the target triple.

When manually specifying a `--target`, the paths seem to be scoped by the target triple.  Could this logic be used for the implied default triple when running without `--target`?

**Comment by alexcrichton** [comment]
This could in theory be done but it makes the "easy case" a little harder in that right after you run `cargo build` for the first time ever you've gotta go digging around in some target specific directories which you may not care too much about.

I'm a little worried about the first impression use case, but I can see where this definitely would be super annoying. Perhaps another possibility would be to always scope dependencies under target-specific directories but the crate being built sticks around in `target/`. Just a thought though.

**Comment by hugoduncan** [comment]
I can certainly see the utility of having the latest build artifacts under `target/`.  Would symlinking the final artifact to `target/` be sufficient?

**Comment by alexcrichton** [comment]
Perhaps! In general we've tried to shy away from symlinks as much as possible (due to complications on older Windows), but there's a whole slew of issues with that so it may not be so bad.

**Comment by carllerche** [comment]
At the very least, it would be nice for this to be a local option.

**Comment by Diggsey** [comment]
Symlinks may not work too well, even on newer windows: depending on how you share the folders, a symlinked folder on the host can appear as two ordinary, separate folders from within a VM, and vice versa.

An alternative would just be to copy the final output to `target/` as a final build-step if the target is left unspecified.

**Comment by eminence** [comment]
> Perhaps another possibility would be to always scope dependencies under target-specific directories but the crate being built sticks around in `target/`

I like this idea.  For some projects, building the dependencies is the longest part of the build, so this compromise will definitely help some users.
