### ISSUE TITLE
More configurable tests

### ISSUE THREAD

**Issue by tontm1981** [rust-lang/cargo#12672]
### Problem

Actually, we have three types of tests, each one located in different place in a crate:
- doc tests are, usually and by the Rust docs, in specific comments
- unit tests, placed in each file with the code we want to test
- integration tests, located in the `test` folder

In a bigger project, I think this pattern makes files organization difficult. For example, if I want to put all unit test in `tests/unit-tests` and integration tests in `tests/integration` or anything like this, I can't.

I saw in some sites that is possible to change unit test place, by using `#[path='...']` annotation or some other way that I don't remeber now, but even so, in projects with too many files, using these kind of workaround in each file constraints Rust language to small projects, if I want a project with automated tests

### Proposed Solution

Since there is a stablished way to write and run tests, I suggest to makes tests configurable in `Cargo.toml`, allowing to configure unit, and integration tests location. Also, configuring `cargo test` arguments in the same file will be great.

### Notes

Doc tests are in specific comment blocks. I think changing its location, implies in change the way lib docs are generated, so, it's ok, ignoring it in the proposed solution.

**Comment by epage** [comment]
To move an "integration test", you can specify it with the [`test` table](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target).  You have to do that for each test file *or* you can have a test directory with a `main.rs` that does a `mod` for each test file in that directory (cargo follows this pattern though it doesn't change the path).

Something to keep in mind is that "unit test" and "integration test" is a misnomer.  They are instead "whitebox test" and "blackbox test".  Whitebox tests have access to the internals of your library which requires them to live inside the code to access the code at the relevant level of visibility.  It is unlikely anything is going to change about this.  If you can have everything just use the public API, that is actually a "blackbox test" and can live in the `tests/` folder which you can organize as you wish.

**Comment by epage** [comment]
> About the misnomers, for disambiguations or avoid any mismatch understandings, I just used the names we can see [here](https://doc.rust-lang.org/book/ch11-03-test-organization.html).

Yes, but I suspect the imprecise terms used in that (and Rust community in general) might make this specific conversation more difficult to have which is why I was wanting to focus on the mechanisms and not the policies behind the names.

For me, the question is that if your unit tests can be separate like you want (ie don't need to be whitebox tests), then why not make them blackbox tests?

> Are there any oficial documentation or tutorial good enough that can be used as reference, about a main.rs in test folder or test folder as a project (I mean, with a Cargo.toml inside)? I already saw the same proposed way in other sites, but nothing about it in documentation, neither teaching how to go this way.

The main place I've seen it documented is at https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html

Cargo's documentation has not gone too far into documenting practices.  Its something I want to expand on.  While I'm not 100% aligned with everything on https://matklad.github.io, I expect I'll be using that blog as a starting point for a lot of it because the posts capture a lot of great practices.

**Comment by tontm1981** [comment]
> Yes, but I suspect the imprecise terms used in that (and Rust community in general) might make this specific conversation more difficult to have which is why I was wanting to focus on the mechanisms and not the policies behind the names.

I agree that names may lead us to errouneous understandings, and I suppose we are focusing in different aims about same subject. My focus was the project organization and test object, but thinking in approaches and mechanisms, make things more clear.

> For me, the question is that if your unit tests can be separate like you want (ie don't need to be whitebox tests), then why not make them blackbox tests?

This may be good for me. Thanks for advise.

> Cargo's documentation has not gone too far into documenting practices. Its something I want to expand on. While I'm not 100% aligned with everything on https://matklad.github.io/, I expect I'll be using that blog as a starting point for a lot of it because the posts capture a lot of great practices.

Thank you for your effort. I confess I have some issues with tests and the lack of documentation about tests in Rust does not help. I hope I can help you with this documentation or anything else.

**Comment by epage** [comment]
#2725 is also about making test folders configurable.  Since we closed that, I'm closing this to match.
