### ISSUE TITLE
Add an easy way to see why a certain package/version is being used

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1268]
Sometimes one can get stuck with an older version of a certain package, and it's not necessarily obvious where it is coming from, so it can be hard to diagnose and fix. Currently one can look in the `Cargo.lock` manually, but it might be nice to have, e.g. `cargo parents <package_spec>` that prints the dependency chain(s) of `<package_spec>` to the main package.

**Comment by sfackler** [comment]
Gradle can make a neat `tree(1)`-style view of your dependency graph: https://gradle.org/docs/current/userguide/tutorial_gradle_command_line.html#sec:listing_dependencies and has another task that can generate an inverse dependency graph for problematic dependencies: https://gradle.org/docs/current/userguide/tutorial_gradle_command_line.html#sec:dependency_insight

**Comment by huonw** [comment]
Very similar to https://github.com/rust-lang/cargo/issues/1211.
