### ISSUE TITLE
Cargo --list group installed and alias

### ISSUE THREAD

**Issue by Hellzbellz123** [rust-lang/cargo#12719]
### Problem

When running cargo without a command it shows a --list option. This lists "all commands", however the text that shows implies that they are installed. This can be confusing and less helpful.

the --list command should show the different types in groups, this data is already dealt with in the function that writes too console, so it should be quick and easy, in fact i have a pr ready too submit but i'm kind of new too rust so i'm not sure if this is the best way too do this and would like some input

### Proposed Solution
https://github.com/Hellzbellz123/cargo/tree/fix-list

cargo --list should group aliases, built in commands and installed commands separately  
output of cargo --list should look as below
❯ cargo run -- --list
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/cargo --list`
Configured Aliases:
    t                    alias: alias: test
    bump-check           alias: run --package xtask-bump-check --
	....
Built-In Commands:
    yank                 Remove a pushed crate from the index
    add                  Add dependencies to a Cargo.toml manifest file
	....
Installed Commands:
    zigbuild
    xwin
    .....

**Comment by weihanglo** [comment]
Seems like pretty much similar to #12114 and effectively the same as #12093?

**Comment by weihanglo** [comment]
See also https://github.com/rust-lang/cargo/pull/12196#pullrequestreview-1448339868

**Comment by Hellzbellz123** [comment]
I searched for  --list and list but missed those particular issues, closing as duplicate
My apologies
