### ISSUE TITLE
integration tests' dependencies do not have a dedicated manifest section

### ISSUE THREAD

**Issue by tamird** [rust-lang/cargo#12717]
### Problem

[integration tests](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html) are a useful concept, but in cases where additional test-only 3rd party crates are needed, they are unusable because they don't get to use dev-dependencies and do not have their own dependency section in the manifest.

### Proposed Solution

The simplest solution would be to link dev-dependencies into integration tests.

**Comment by epage** [comment]
Could you provide an example scenario?  I'm not too sure what the problem is you are trying to highlight.

**Comment by tamird** [comment]
When I write some unit tests, and I want to use test-only dependencies such as `pretty_assertions`, the [documentation](https://doc.rust-lang.org/rust-by-example/testing/dev_dependencies.html) suggests using `dev-dependencies`.

Now suppose I want to write an [integration test](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html) that uses `pretty_assertions` - where do I declare that my test needs that crate? As I write in the issue description: integration tests are compiled without `dev-dependencies`, and it would be inappropriate to add `pretty_assertions` to my crates `dependencies`.

**Comment by epage** [comment]
> s I write in the issue description: integration tests are compiled without dev-dependencies

They should be compiled with dev-dependencies.  Do you have a reproduction case?

**Comment by tamird** [comment]
I was attempting to reproduce this by writing a test in the cargo repo, but you are right - they seem to be getting the dev-dependencies. This was PEBKAC.

**Comment by tamird** [comment]
The actual issue was that `dev-dependencies` are linked to both unit and integration tests, which can create poor interactions with the [`unused-crate-dependencies` lint](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-crate-dependencies).

It would be good to have a separate section in the manifest for the dependencies of integration tests for this reason.

**Comment by tamird** [comment]
Not only that, it will also trigger on the main crate if the dev-dependency isn't used in any *unit* tests.

**Comment by epage** [comment]
Is there any reason we shouldn't close in favor of #1982?

**Comment by tamird** [comment]
Seems reasonable to do so.
