### ISSUE TITLE
[feat] crates-io mirror environment config

### ISSUE THREAD

**Issue by loynoir** [rust-lang/cargo#12724]
### Problem

Let package manager env-configure-able is very convenient for scenario like 

- docker

- devcontainer

`.devcontainer/devcontainer.json`

```json
  "remoteEnv": {
    "NPM_CONFIG_REGISTRY": "http://self-hosted-verdaccio",
```

within container

```
$ npm config ls -l | grep verdaccio
registry = "http://self-hosted-verdaccio" 
```

But currently, cargo seems not env-configure-able, only accept `.cargo/config`.

### Proposed Solution

Let cargo config env-configure-able.

**Comment by weihanglo** [comment]
Configuring Cargo via environment variables is documented here: <https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environment-variables>. You can also set configuration via `--config` cli argument.

Is there something missing you're looking for specifically?

**Comment by loynoir** [comment]
Seems not working.

Expected

```toml
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirror/crates.io-index/"
```

```txt
$ cargo build
...
    Updating `mirror` index
...
```

Actual

```sh
$ env \
    CARGO_REGISTRIES_MIRROR_INDEX="sparse+https://mirror/crates.io-index/" \
    CARGO_REGISTRY_DEFAULT="mirror" \
    cargo build
...
    Updating crates.io index
...
```

**Comment by Eh2406** [comment]
In your second example you set https://doc.rust-lang.org/cargo/reference/config.html#registrydefault but in the ferst you set https://doc.rust-lang.org/cargo/reference/config.html#sourcenamereplace-with witch do very difrent things. (despite the confusing naming, sorry.)

**Comment by weihanglo** [comment]
Also, as you may have read, a Cargo config value usually but **not always** has a counterpart of environment variable
> Currently only integer, boolean, string and some array values are supported to be defined by environment variables. [Descriptions below](https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys) indicate which keys support environment variables and otherwise they are not supported due to [technical issues](https://github.com/rust-lang/cargo/issues/5416).

Besides, there is a pretty unstable feature `-Zadvanced-env` tracked in <https://github.com/rust-lang/cargo/issues/7406>, which tries to fill the gap between config files and environment variables. I believe that also fixes your issue of setting source replacement via env, so closing in favor of #5416 and #7406.

Thank you for the report :)
