### ISSUE TITLE
Custom build should allow "-F" and "-framework" flags

### ISSUE THREAD

**Issue by jonasp** [rust-lang/cargo#1272]
On OS X we need framework directories `-F` and framework names `-framework` to build dependencies.

Here is for example the Qt Qml library
```
$ pkg-config --libs Qt5Qml
-F/usr/local/Cellar/qt5/5.4.0/lib -framework QtQml -F/usr/local/Cellar/qt5/5.4.0/lib -framework QtNetwork -F/usr/local/Cellar/qt5/5.4.0/lib -framework QtCore
```

Cargo explicitly allows only `-L` and `-l` flags.

**Comment by alexcrichton** [comment]
The Rust compiler doesn't use the same `-F` and `-framework` flags that the linkers use, it actually uses `-l framework=foo` and `-L native=foo` for `-framework` and `-F`, respectively. Which is all to say that this should be possible today!

**Comment by jonasp** [comment]
This is great, `-l framework=foo` works perfectly but `-L native=foo` does not give `-F` but `-L`. Any ideas why?

Sidenote: if this works pkg-build-rs still needs to accept the -F and -framework flags and translate them accordingly. Do you want me to open a separate issue at the pkg-build-rs issue tracker?

**Comment by alexcrichton** [comment]
Gah, right! Looks like two issues need to be opened:

1. An issue on `rust-lang/rust` for accepting `-L framework=foo` and translating that to `-F`.
2. An issue on `pkg-config-rs` to accept `-F` and `-framework` and translate accordingly.

**Comment by jonasp** [comment]
There is already [rust-lang/rust/#20259](https://github.com/rust-lang/rust/issues/20259) so I won't open a new one. I'll just add a note on the `-L framework=foo` solution.

**Comment by alexcrichton** [comment]
Ok, thanks @jonasp!
