### ISSUE TITLE
target features are not accessible from build scripts

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#12737]
Right now `cargo` does not pass the build scripts a `CARGO_CFG_TARGET_FEATURE` environment variable with all the target features, so I guess the value of `cfg(target_feature = "...")` is set within rustc. 

This makes writing build scripts that need to access target features unnecessarily hard.

**Comment by epage** [comment]
This seems related to #12728.  As far as I could tell, cargo does a straight transform of whatever cfg's rustc prints to environment variables.

**Comment by epage** [comment]
@gnzlbg I know this is old but do you happen to have reproduction steps?  Trying to understand which root cause you might have seen that led to this
