### ISSUE TITLE
Test doc for binary projects

### ISSUE THREAD

**Issue by Blackhole16** [rust-lang/cargo#1274]
In #318 it was asked if one could build the doc for binary projects, which you allowed with #320. Could you also please enable doc testing with cargo test like it is done in library projects?

Kind Regards,
BH16

**Comment by alexcrichton** [comment]
Unfortunately the design of `rustdoc --test` does not allow for this. Whenever `rustdoc --test` is run it will try to link against the library being tested, but for binaries there's no library to link against.

You may want to open an issue on the rust-lang/rust repository instead to expand `rustdoc --test` to work for bin crates as well as lib crates.

**Comment by andrewdavidmackenzie** [comment]
Was an issue ever opened "to expand rustdoc --test to work for bin crates as well as lib crates."?

If so, I'd like to know which one and be able to +1 it, so I can write "system" tests that test my binaries with different input and files.

**Comment by steveklabnik** [comment]
It's inherent to the way that rustdoc works. I think that there's a ticket open.

**Comment by andrewdavidmackenzie** [comment]
BTW: i see "benchmarking" was in the main testing section - of the offline eBook version I was reading, hence my confusion.....
