### ISSUE TITLE
Depend on subcrates of workspace as git dependency

### ISSUE THREAD

**Issue by KronsyC** [rust-lang/cargo#12756]
### Problem

I have a monorepo set up as a workspace, with many subcrates within it. This is repo A
I also have a tauri desktop app, this is repo B.

I need access to the RPC interface crate, which is developed under repo A, within the desktop app B.

This RPC crate is developed tightly in tandem with other crates of repo A, so it would be preferential to have it kept there, and not brought out into a separate repo.

### Proposed Solution

Currently, cargo disallows having both a `git = ` and `path = ` specification within a dependency. I am proposing that we allow both to be specified. For my case, like such:
`rpc_lib = {git = "ssh://github.com/KronsyC/some_repo.git", path = "src/rpc"}`

An issue that I can foresee with this approach, is that it removes the abstraction of crate internals currently provided by the system

**Comment by epage** [comment]
Could you expand on what problem is happening in trying to use a crate from repo A within repo B?

**Comment by KronsyC** [comment]
Cargo expects a crate to exist at the root of repo A, and will not allow you to specify a crate within a subdirectory for use instead.
I found a workaround to this issue by making the root workspace into a package, and conditionally re-exporting its crates depending on passed features

**Comment by weihanglo** [comment]
IIRC, you don't need to specify a path to depend on a crate inside a Git repo. Cargo auto-discovers then crate with a name matching your dependency.

For example, if the `package.name` is `rpc_lib`, `rpc_lib = { git = "ssh://github.com/KronsyC/some_repo.git" }` should just work. If not, please share the repo or have a reproducible example with us, so we can investigate the issue.

**Comment by KronsyC** [comment]
> IIRC, you don't need to specify a path to depend on a crate inside a Git repo. Cargo auto-discovers then crate with a name matching your dependency.
> 
> For example, if the `package.name` is `rpc_lib`, `rpc_lib = { git = "ssh://github.com/KronsyC/some_repo.git" }` should just work. If not, please share the repo or have a reproducible example with us, so we can investigate the issue.

Oh that is cool, I never knew about this feature before
Is it currently documented in the cargo dependencies docs?
If not, can it be added

**Comment by weihanglo** [comment]
See <https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories>

> Cargo will fetch the `git` repository at this location then look for a `Cargo.toml` for the requested crate anywhere inside the `git` repository (not necessarily at the root — for example, specifying a member crate name of a workspace and setting `git` to the repository containing the workspace).

**Comment by KronsyC** [comment]
> See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
> 
> > Cargo will fetch the `git` repository at this location then look for a `Cargo.toml` for the requested crate anywhere inside the `git` repository (not necessarily at the root — for example, specifying a member crate name of a workspace and setting `git` to the repository containing the workspace).

My god, I cannot believe I missed that
thanks for the help
