### ISSUE TITLE
Replacement source does not resolve packages the same way as replaced source

### ISSUE THREAD

**Issue by wackazong** [rust-lang/cargo#12778]
### Problem

Cargo seems to resolve packages differently in git repos and in file locations.

### Steps

I have a workspace with dependencies linked to a Github repository. There are entries in Cargo.toml like:

```toml
my_dependency.git = "ssh://github.com/foo/bar.git"
```

The repo is a collection of workspaces. Cargo successfully finds the package as a member of one of the workspaces. Great! All good so far. 

Now when I want to build in Docker, I try to point the repo URL to a local copy in `.cargo/config.toml`:

```toml
[source.my-repo]
git = "ssh://github.com/foo/bar.git"
replace-with = "local"

[source.local]
directory = "path/to/files"
```

Problem is, now Cargo does not find the package anymore. It complains:

```console
found a virtual manifest at `/path/to/files/some-workspace/Cargo.toml` instead of a package manifest
```

I would expect that Cargo can find the package in this scenario in the same way it can find the package in the Github repo. To me it seems package resolution works differently in a github repo and in a file source. 

### Version

```text
cargo 1.72.1 (103a7ff2e 2023-08-15)
release: 1.72.1
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-apple-darwin
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 7.88.1 (sys:0.4.63+curl-8.1.2 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 13.4.1 [64-bit]
```

**Comment by ehuss** [comment]
Can you clarify, did you build the directory source using `cargo vendor`? That is the only supported way to build a directory source.

If you want to refer to a local git clone, then that should use a `git` source.

**Comment by wackazong** [comment]
Ok, that clears it up. I thought the directory source could be used out of `cargo vendor`. Thanks.
