### ISSUE TITLE
Poor error message when `target` is a broken symlink

### ISSUE THREAD

**Issue by rben01** [rust-lang/cargo#12789]
### Problem

When running `cargo build`, Cargo tries to output to `target`. If `target` is an ordinary file, or a symlink that points to one, this (naturally) fails with 

```sh
$ cargo build
error: failed to create directory `/path/to/crate/target/debug`

Caused by:
  Not a directory (os error 20)
```

However, if `target` is a _broken_ symlink, Cargo prints a much less helpful error message:

```sh
$ ln -s /a/b/c target  # assuming /a/b/c doesn't exist on your machine
$ cargo build
error: Not a directory (os error 20)
```

The `error: failed to create directory` part of the error message has been lost.

### Steps

1. Create a new crate with `cargo init`
2. Create a broken `target` symlink with e.g., `ln -s /a/b/c target` (assuming you don't actually have `/a/b/c` on your computer)
3. Run `cargo build`

### Possible Solution(s)

Cargo should catch the broken `target` symlink and print the same error message it would if `target` were an ordinary file.

### Version

```text
cargo 1.74.0-nightly (2cc50bc0b 2023-08-22)
release: 1.74.0-nightly
commit-hash: 2cc50bc0b63ad20da193e002ba11d391af0104b7
commit-date: 2023-08-22
host: aarch64-apple-darwin
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2 (sys:0.4.65+curl-8.2.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 14.0.0 [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report. Sounds pretty reasonable to enhance that. 

@rustbot label +S-accepted +A-error -S-triage

**Comment by linyihai** [comment]
It seems a good-first-issue for me. I will give it a try. :wink:

**Comment by linyihai** [comment]
@rustbot claim

I will try to support it. if you have any idea, please let me know. :grin:

**Comment by linyihai** [comment]
Hi,  I found the code that trigger this issue. 

[paths:::create_dir_all_excluded_from_backups_atomic](https://github.com/rust-lang/cargo/blob/master/crates/cargo-util/src/paths.rs)

```
    if let Err(e) = fs::rename(tempdir.path(), path) {
        if !path.exists() {
            return Err(anyhow::Error::from(e));
        }
    }
```

It will failed when `fs::rename` want to copy the temp folder to `target` folder which is a broken symlink.  and then it return the err without the err context like `.with_context(|| format!("failed to create directory `{}`", p.display()))`. 

In my opinion, the simple way is to add the err context like 

```
    if let Err(e) = fs::rename(tempdir.path(), path) {
        if !path.exists() {
            return Err(anyhow::Error::from(e)).with_context(|| format!("failed to create directory `{}`", path.display()));
        }
    }
```

In addition,  it is necessary to check whether the symlink is valid?

**Comment by hi-rustin** [comment]
@linyihai Could you please give an example output to help us to check the new error message?

**Comment by weihanglo** [comment]
Hi @linyihai, that looks about right.

One more improvement you can do is using `anyhow::anyhow!("failed to create directory ``{}``", path.display())` instead of `return Err(….with_context(…))`.


> In addition, it is necessary to check whether the symlink is valid?

The above error message should be sufficient for people to find what caused the error. I don't feel like we need more checks here.

**Comment by linyihai** [comment]
> @linyihai Could you please give an example output to help us to check the new error message?
make the `target` folder refer to broken symlink like `/a/b/c`, then run `cargo build`, the output is:

```
error: Not a directory (os error 20)
```

the detailed error message is missing.

**Comment by linyihai** [comment]
I think the final output will be like this: 

```
cargo build
error: failed to create directory `/root/workspace/playground/target`

Caused by:
  the path `/root/workspace/playground/target` is invalid or broken symbolic link

Caused by:
  Not a directory (os error 20)
```

I lean to keep the initial err.

```
Caused by:
  Not a directory (os error 20)
```

**Comment by weihanglo** [comment]
Fair enough. Feel free to open a pull request.

**Comment by rben01** [comment]
@linyihai Are you sure that that https://github.com/rust-lang/cargo/blob/a9d71d291fa2cdba6844e734724d039782e006dd/crates/cargo-util/src/paths.rs#L695 is the issue? I would assume that the [`create_dir_all(parent)?`](https://github.com/rust-lang/cargo/blob/a9d71d291fa2cdba6844e734724d039782e006dd/crates/cargo-util/src/paths.rs#L674) call above would fail before reaching that code.
