### ISSUE TITLE
SPDX License expression link broken

### ISSUE THREAD

**Issue by RossSmyth** [rust-lang/cargo#12797]
### Problem

In the Cargo Book, the "[SPDX 2.1 license expression](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60)" link is broken.
https://github.com/rust-lang/cargo/blob/b27f203e7f461a6e98bf78abc88d7e7fc6ff1a8f/src/doc/src/reference/manifest.md?plain=1#L261-L262

https://github.com/rust-lang/cargo/blob/b27f203e7f461a6e98bf78abc88d7e7fc6ff1a8f/src/doc/src/reference/manifest.md?plain=1#L631

### Steps

1. [Go to Cargo Book webpage](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields)
2. Click on "[SPDX 2.1 license expression](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60)"
3. See "Page not found" page

### Possible Solution(s)

Update the link or complain to SPDX as it looks like the [link is broken on their website too](https://spdx.dev/use/specifications/)

https://spdx.dev/spdx-specification-21-web-version/

So an issue may need to be raised here:

https://github.com/spdx/LicenseListPublisher

### Version

```text
b27f203e7f461a6e98bf78abc88d7e7fc6ff1a8f ?
```

**Comment by weihanglo** [comment]
Looking at crates.io project, it uses [`spdx#0.10.2`](https://github.com/rust-lang/crates.io/blob/1afc4120a60a2fab64fb185ad5cdb8e2ace3cee5/Cargo.toml#L87), which at least uses SPDX license expression v2.1 or later.

[v2.3](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/) looks like to have the same syntax as v2.1, though I am not knowledgeable enough to tell the difference.

cc @Turbo87, any insight?

**Comment by Turbo87** [comment]
interestingly the link to the license expressions in the https://github.com/EmbarkStudios/spdx README is also broken, but AFAIK the syntax is the same as before and only the list of licenses was updated.

even more funny, the link to the 2.1 spec on https://spdx.dev/use/specifications/ is also broken 😅

**Comment by weihanglo** [comment]
Should we just link them to 2.3, as they are quite the same thing? I would love to let you or crates.io team decide as this is more concerned about crates.io

**Comment by Turbo87** [comment]
yeah, I guess updating the link to the latest spec should probably be fine
