### ISSUE TITLE
Add line number to error messages about parsing Cargo.toml

### ISSUE THREAD

**Issue by andresovela** [rust-lang/cargo#12816]
### Problem

When there's a problem with Cargo.toml, cargo outputs an error but it does not mention where the error is coming from. For example:

```
$ cargo build
error: failed to parse manifest at `path/to/Cargo.toml`

Caused by:
  error inheriting `$crate` from workspace root manifest's `workspace.dependencies.$crate`

Caused by:
  failed to find a workspace root
```

### Proposed Solution

It'd be nice if cargo mentioned which is the offending line in the manifest. For example:

```
$ cargo build
error: failed to parse manifest at `path/to/Cargo.toml:24`

Caused by:
$crate = { workspace = true } 

Caused by:
  error inheriting `$crate` from workspace root manifest's `workspace.dependencies.$crate`

Caused by:
  failed to find a workspace root
```

**Comment by epage** [comment]
So with Rust 1.75, more errors will include span information.

We also have #12810 about adding span information.  Closing in favor of that.  If there is a reason to keep both open, let us know!
