### ISSUE TITLE
`cargo clippy`: Provides confusing help on wrong usage

### ISSUE THREAD

**Issue by Jujumba** [rust-lang/cargo#12831]
### Problem

When passing an unexpected argument to `cliippy`, the `Usage` section of the output help is wrong
```sheel
$ cargo clippy ? 
error: unexpected argument '?' found

Usage: cargo check [OPTIONS]  # Should be `Usage: cargo clippy [OPTIONS]` I guess

For more information, try '--help'.
``` 

### Steps

1. Open up a terminal
2. Execute `cargo clippy <whatever>`
3. See the misconfusing help

### Possible Solution(s)

Change corresponding help section

### Version

```text
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:Schannel)
os: Windows 10.0.25967 (Windows 11 Core) [64-bit]
```

**Comment by epage** [comment]
FYI `cargo clippy` lives in https://github.com/rust-lang/rust-clippy (and for some reason I can't transfer the issue).  Going ahead and closing it. Feel free to open one over there!
