### ISSUE TITLE
`cargo … --message-format json` should tell you when it starts compiling a cate.

### ISSUE THREAD

**Issue by bend-n** [rust-lang/cargo#12864]
### Problem

`cargo build --message-format json` will have output such as:
```jsonc
// stdout: (none)
// stderr:
Compiling png
// stdout:
{"reason":"compiler-artifact","package-id":"png 0.17.0"} // compilation finishes
```
There is no way to see when `png` starts compiling.
The only way to find out, is to *parse stderr*, which also doesnt give you the full version information + manifest + etc

### Proposed Solution

`cargo build --message-format json` will have output such as:
```json
{"reason":"begin-compile-crate","package_id":"png 0.17.0","target":"…","features":[],"executable":null,"profile":"…"}
{"reason":"compiler-artifact","package-id":"png 0.17.0"}
```

**Comment by weihanglo** [comment]
Thanks for the report. The story of Cargo its own JSON message output is tracked in #8283. I'll compile them together in #8283 and close this. Thanks!
