### ISSUE TITLE
`cargo` should provide builtin support to let `build.rs` detect `feature` is supported

### ISSUE THREAD

**Issue by loynoir** [rust-lang/cargo#12872]
### Problem

There is a 

- 1 ~ 2 weeks project, with 1 ~ 2 weeks cache

- recent `RA` v0.3.1705

- deep dependency tree have recent version, `thiserror-1.0.50` `anyhow-1.0.75`,  same author `dtolnay`

I encounter **same old bug** on `thiserror-1.0.50` `anyhow-1.0.75`.

- `#![feature]` may not be used on the stable release channel`

This bug was happening one year ago, but then fix.

In conclusion, this is maybe a mix problem of

- build.rs workaround to detect `feature`, such as `error_generic_member_access`, is supported

- RA rustc wrapper for performance

- sccache

- cargo build cache

And I think the core problem  is

- cargo does not provide builtin support to let `build.rs` detect `feature` is supported, so dev invent themself.

### Proposed Solution

`cargo` should provide builtin support to let `build.rs` detect `feature` is supported

### Notes

Related

https://github.com/dtolnay/thiserror/issues/192

https://github.com/dtolnay/thiserror/blob/e9ea67c7e251764c3c2d839b6c06d9f35b154647/build.rs#L12

https://github.com/dtolnay/anyhow/blob/05e413219e97f101d8f39a90902e5c5d39f951fe/build.rs#L17

https://github.com/rust-lang/rust-analyzer/issues/15057

**Comment by loynoir** [comment]
Generally, I think `implement which makes less assumption` is better than `implement which makes more assumption`.

So, personally, I agree with @epage .

But, according to my understanding, @dtolnay does not agree with

> Personally, I think auto-detecting nightly features is a mistake and instead feature flags should be used to enable them explicitly.

So, I still insist

-  `rustc` or `cargo` should provide builtin support to let `build.rs` detect `feature` is supported

Which will make build system robust, with less assumption.

**Comment by epage** [comment]
Note that I did not close this because of my opinion but that cargo isn't in a place to solve this.

**Comment by loynoir** [comment]
Tired. Leave it for next one who fall into `cargo clean` workaround.
