### ISSUE TITLE
Paths from config.toml do not get properly processed for the platform they run on

### ISSUE THREAD

**Issue by hcldan** [rust-lang/cargo#12873]
### Problem

setting a config.toml:
```toml
C_API_ROOT = { value = "target/lib/capi", force = false, relative = true }
```

results in something like this on windows: `c:\\Users\\user\\git\\project\\target/lib/capi`

### Steps

For steps, see above.

### Possible Solution(s)

Translate the path according to the platform processing the build, or give us a way to set the path based on the platform being built on or for.

If that is already possible, please make that information easier to access. Perhaps in https://doc.rust-lang.org/cargo/reference/config.html#configuration-format or the section about `env`.

**Comment by ehuss** [comment]
Sorry, I'm not really clear, what is wrong with the path?

**Comment by hcldan** [comment]
mixed `/` and `\` characters

**Comment by ehuss** [comment]
Can you say more about what kind of problems that causes? Almost all the Windows APIs support both forward and backward slashes.

**Comment by hcldan** [comment]
I haven't yet tried some older compilers, but hopefully that won't matter.
I'll re-open if I run into further issues with this.
