### ISSUE TITLE
tests are not rebuilt when the crate changes

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/cargo#1289]
I observe a problem with cargo 0.0.1-pre-nightly (9404539 2015-02-09 20:54:26 +0000).
The 'integration' test crates in the `tests` subdirectory are not automatically rebuilt on `cargo test` when the main crate gets rebuilt. This may result in some of the test crates becoming stale with regard to the changes in the crate under test, but they still run OK if they have linked a previous build of the crate statically.

**Comment by alexcrichton** [comment]
Do you have a reproducible example of this? I tried this out locally but it seems to rebuild ok for me.

**Comment by mzabaluev** [comment]
I cannot reproduce the problem any more. I'll reopen this if I have more evidence.

**Comment by mzabaluev** [comment]
Reproduced again, with cargo 0.0.1-pre-nightly (9404539 2015-02-09 20:54:26 +0000).

Changed the crate code, built with `cargo build`. After that, `cargo test` does not rebuild the tests:
```
cargo test --verbose
       Fresh c_string v0.4.2-dev (file:///home/mzabaluev/work/rust/rust-c-str)
     Running `/home/mzabaluev/work/rust/rust-c-str/target/bench-85920b1faacb98ef
```
After `cargo clean && cargo build`, the rebuild happens and fails:
```
cargo test --verbose
   Compiling c_string v0.4.2-dev (file:///home/mzabaluev/work/rust/rust-c-str)
     Running `rustc src/c_str.rs --crate-name c_string --crate-type lib -g --test -C metadata=2bca42bf28d3b985 -C extra-filename=-2bca42bf28d3b985 --out-dir /home/mzabaluev/work/rust/rust-c-str/target --emit=dep-info,link -L dependency=/home/mzabaluev/work/rust/rust-c-str/target -L dependency=/home/mzabaluev/work/rust/rust-c-str/target/deps`
```

**Comment by alexcrichton** [comment]
Can you point me at a repository as well? A sequential series of steps would also be helpful (sorry had a bit of trouble following your last comment)

**Comment by mzabaluev** [comment]
Caught it dead with

```sh
git clone git@github.com:gi-rust/grust.git
cd grust
git checkout feb3a4f3fc9622f10ad0fbd339c59b96d4621f50
cargo build --verbose
cargo test --verbose
git checkout 5265fca705f5579803c6aac979403fe600767b98
cargo build --verbose
cargo test --verbose
# The binary gets rebuilt for unit tests, but the tests-derived targets aren't
cargo clean
cargo test --verbose
```
