### ISSUE TITLE
`cargo rustc --target` behavior is different to `rustc --target`

### ISSUE THREAD

**Issue by tmvkrpxl0** [rust-lang/cargo#12895]
### Problem

I'm using CLion which fetches target information with this command:
```sh
cargo rustc -Z unstable-options --target /home/tmvkrpxl0/linux/scripts/target.json --print cfg
```
However it says it's invalid target, while running same command without cargo works.

### Steps

1. Run `RUSTC_BOOTSTRAP=1 cargo rustc -Z unstable-options --target <custom_target_json> --print cfg` which fails
2. Run `RUSTC_BOOTSTRAP=1 rustc -Z unstable-options --target <custom_target_json> --print cfg` which succeed

### Notes

rustc 1.73.0 (cc66ad468 2023-10-03)

### Version

```text
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Linux 22.04 (jammy) [64-bit]
```

**Comment by tmvkrpxl0** [comment]
@epage  I can, but setting it up will take ages, I'm building linux kernel module and you need to compile whole kernel.
https://codeberg.org/tmvkrpxl0/tefexia
Instead you can just try target.json
[target.json](https://github.com/rust-lang/cargo/files/13209567/target.json)

**Comment by tmvkrpxl0** [comment]
```sh
❯ RUSTC_BOOTSTRAP=1 cargo rustc -Z unstable-options --target /home/tmvkrpxl0/linux/scripts/target.json --print cfg
error: Error loading target specification: Could not find specification for target "target". Run `rustc --print target-list` for a list of built-in targets

error: process didn't exit successfully: `/home/tmvkrpxl0/.cargo/bin/sccache /home/tmvkrpxl0/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -L /lib/modules/6.6.0-rc4-kindergarten+/build/rust -Zbinary_dep_depinfo=y -Cembed-bitcode=n -Zfunction-sections=n -Cforce-unwind-tables=n -Csymbol-mangling-version=v0 -Crelocation-model=static -Ctarget-feature=-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2 -Ztune-cpu=generic -Cno-redzone=y -Ccode-model=kernel -Cforce-frame-pointers=y --emit=dep-info=./.tefexia.o.d --emit=obj=./tefexia.o --cfg MODULE --target target --print cfg` (exit status: 1)
```

**Comment by weihanglo** [comment]
> Instead you can just try target.json [target.json](https://github.com/rust-lang/cargo/files/13209567/target.json)

Tried the `target.json` file you provided with both `rustc` and `cargo` printing `cfg`. Both of the commands succeeded without any error. I am not what happened to you :(

Just noticed that you have `/home/tmvkrpxl0/.cargo/bin/sccache` as a rustc wrapper. I don't think that would be an issue but could you try removing the setting?

**Comment by weihanglo** [comment]
Going to close due to inactivity. Feel free to reopen if you have a chance to provide more info.
