### ISSUE TITLE
Reference parameters inside the `format!` string (`format!("package '{name}'...`)

### ISSUE THREAD

**Issue by shnaramn** [rust-lang/cargo#12892]
nit: saying this just because I already made another comment but feel free to reference these inside the `format!` string (`format!("package '{name}'...`)

_Originally posted by @epage in https://github.com/rust-lang/cargo/pull/12766#discussion_r1355114146_

**Comment by shnaramn** [comment]
I'd like to fix this if approved.

**Comment by hi-rustin** [comment]
Sounds good. You can give it a shot :(

**Comment by weihanglo** [comment]
I would recommend we wait until #12178 gets landed, and adjust lint rules gradually. And it's getting closer!

**Comment by weihanglo** [comment]
Going to close this as it is a general clippy fix. We don't need a dedicated issue for this specific review comment <https://github.com/rust-lang/cargo/pull/12766#discussion_r1355114146>.

Despite that, #12178 has been merged, so feel free to open a PR to update. And let's see how enormous the patch will be.
