### ISSUE TITLE
Does the Cargo team accept  RFC: Packages as (optional) namespaces #3243 

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#12901]
rust-lang/rfcs#3243 has enough impact on cargo (and we want to make sure all voices are heard) that we wanted to have an FCP for this, rather than an informal yay/nay.

To avoid the "two team FCP" problem (both teams - 2 people must approve), we're holding the FCP here so its only "cargo team - 2 people"

**Note:** This issue exists purely for process purposes and feedback should be given on rust-lang/rfcs#3243

**Comment by epage** [comment]
@rfcbot fcp merge

**Comment by weihanglo** [comment]
> What should the lib name be? 

The current iteration of <https://github.com/rust-lang/rfcs/pull/3243/commits/482fae89e524edfe3ac883c0d867169b887473e7> choose `pkg` as the autogenerated `lib.name` for `namespace::pkg`. This might introduce more name conflicts on build artifacts (see <https://github.com/rust-lang/cargo/issues/6313>). For example, a workspace contains both `png::codec` and `avif::codec` and want to build them into `dylib`.

This is not a blocker if postponing it to implementation stage is permitted, but it would be great if we can have a consensus on it.

**Comment by ehuss** [comment]
@weihanglo Can you clarify what kind of conflict you see?  For rlibs, the filename should have a distinct hash between them.

The conflicts I can think of are:
* `dylib`/`cdylib` — these don't have hashes. This seems unlikely in practice, though something to consider.
* rustdoc — I'm going to leave a comment about this on the RFC.

**Comment by weihanglo** [comment]
Yes thanks, Eric. `dylib`/`cdylib` are things I am aware of. Might not be common, and if cargo can apply rename feature to namespaced package, everything would be okay. `rustdoc`'s issue is more prominent.

**Comment by decathorpe** [comment]
This has the potential to create massive headaches for Linux distributions which package Rust crates (namely Fedora Linux and Debian, and possibly other, less popular distributions).

For example, the mapping between crate names and package names is currently unique in Fedora (crate `$CRATE` is packaged as `rust-$CRATE`), which works perfectly, since crates.io is a flat namespace. With this addition, this mapping will break - the colon (from the proposed namespace separator `::`) is not a valid character in RPM package names, and I'm pretty sure it's not a valid character in DEB either. There are only a limited number of valid punctuation characters that are usable in package names that are not already clashing with valid characters from crate names - only `.` and `+` currently come to mind ... so it will make implementing support for this feature possibly quite tricky for us.

A little more of a heads-up would have been nice ... 🙇🏻‍♂️

**Comment by weihanglo** [comment]
Thanks for the feedback, @decathorpe. It doesn't sound good from what you've said 😞. I wonder how distro package maintainer handle namespaced packages for NPM. But don't answer me here. This PR is primarily for collecting feedback from members of the Cargo team. For wider audience, you can find a general discussion in <https://github.com/rust-lang/rfcs/pull/3243>, and perhaps post a comment there. I do think this issue worthy a look from more people.

**Comment by epage** [comment]
This comment would likely be better on the RFC rather than on the cargo-specific FCP issue. 

Also, this isn't new. The RFC has also been around for years. Its been over a year in its current state.

**Comment by tarcieri** [comment]
There is a Cargo-specific issue which is semi-relevant to @decathorpe's question: how namespaced packages are represented in the registry index trie, where a similar delimiter needs to be decided upon: https://github.com/rust-lang/rfcs/pull/3243/files#r983881223

It looks like `.` would be valid both for that use case and for the distribution packaging case, and if the Cargo/crates.io teams are happy with that, perhaps the RFC could mention how it's specified in the registry index trie and also include a recommendation as to how namespaces should map to distribution package names.

**Comment by epage** [comment]
There are a lot of different options we can choose the for index that would not be appropriate for package names.  I've added that and the naming of the `.crate` to the open questions for us on this.  Since I expect both to have little cross-team or community concerns, we can likely handle it during stabilization, like the other issues.

That said, it would really be best for this feedback to go on the main RFC.  This exists just for the cargo team to hold a vote. **If this continues to divert attention away from the RFC, we likely should lock this thread.**

**Comment by werdahias** [comment]
I agree with @decathorpe that this will break distros' established workflows. At debian we also use the rust- prefix for the source package and just add the cratename.` ::` is not a vaid character for debian package names; so this would certainly become a major inconvenience for us if implemented.

**Comment by ehuss** [comment]
I'm going to close this as accepted. Thanks everyone!
