### ISSUE TITLE
Cargo false build failure when different dep versions in workspace dependencies + default-features = false

### ISSUE THREAD

**Issue by vlovich** [rust-lang/cargo#12936]
### Problem

I have a workspace with 2 crates `foo` and `bar`. `foo` internally depends on `fastrand` and when added to `bar` as a test dependency, `bar` fails to build, throwing a compile error:
```
    |                 let value = fastrand::Rng::new().usize(0..5);
    |                                                              ^^^ function or associated item not found in `Rng`
```
This obviously doesn't make sense since the `new` function is definitely there (I can even ctrl-click through it in VScode to open the definition which I believe is rust-analyzer finding it).

It appears to be some weird corner case with different versions of the same crate in the dependency tree + turning off default features for the newer version.

### Steps

1. Create a workspace with 2 member crates
2. In the workspace dependencies, add:
```
[workspace.dependencies]
fastrand = { version = "2", default-features = false }
futures-lite = { version = "1.13", default-features = false }
glommio = { git = "https://github.com/DataDog/glommio.git" }
```
3. In `foo/Cargo.toml` add:
```
[dependencies]
fastrand = { workspace = true }
glommio = { workspace = true }
``` 
4. In `foo/lib.rs`:
```
pub fn rand_value() -> usize {
   fastrand::Rng::new().usize(0..5)
}
```
5. In `bar/Cargo.toml` add
```
[dev-dependencies]
# Just so that certain internal crate methods are made public when building benchmarks.
bar = { path = ".", features = ["benchmarking"] }
```
8. Call `rand_value` from `bar/lib.rs`.

Specifically, the minimal dependency tree of my current project looks something like:

```
bar v0.1.0
|--- baz v0.1.0
|   |--- foo v0.1.0
|       |--- fastrand v2.0.1
|       |--- glommio 0.8.0 (https://github.com/DataDog/glommio.git)
|--- foo v0.1.0
```

If I change `fastrand` to use `default-features = true` then the build works for some reason.

### Notes

The exact combination of things that have to be present is hard to pin down. The `foo` crate only has the `Rng` codepath  behind a non-default `test-support` feature which only gets enabled when `foo` is in the `dev-dependencies` (it's normally in `dependencies` without the `test-support` feature). If I expose the `Rng` codepath to be available always independent of the flag, them normal builds also fail but just for this one crate for some reason.

### Version

```text
cargo 1.72.0 (103a7ff2e 2023-08-15)
cargo 1.74.0-nightly (d5336f813 2023-09-14)
```

**Comment by epage** [comment]
Could you please provide a complete reproduction case?  There are many details missing (e.g. the definition of `benchmarking`, what `workspace.resolver` is set to, etc).

**Comment by vlovich** [comment]
Here's a completely minified repro. Doesn't even need all those complex dependencies. Just run cargo test within that folder and you get:

```
error[E0599]: no function or associated item named `new` found for struct `Rng` in the current scope
 --> foo/src/lib.rs:4:20
  |
4 |     fastrand::Rng::new().usize(0..5)
  |                    ^^^ function or associated item not found in `Rng`

For more information about this error, try `rustc --explain E0599`.
```

If you swap the `fastrand` declaration in `foo/Cargo.toml` to use the `default-features = true` variant, then it builds OK.
[repro.zip](https://github.com/rust-lang/cargo/files/13312696/repro.zip)

**Comment by vlovich** [comment]
NVM looks like PEBKAC. `fastrand::Rng::new` requires the `std` feature to be enabled for the crate.
