### ISSUE TITLE
Determine how to handle `--quiet` in commands with subcommands

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#12957]
Commands that have subcommands (like `cargo report future-incompat`, `cargo config get`, `cargo owner add`, `cargo clean gc`, etc.) currently don't support the `--quiet` flag. The problem is:

[`arg_quiet()`](https://github.com/rust-lang/cargo/blob/9a1b0924c6ea3ac306b663aa73347d3b6a59e7c3/src/cargo/util/command_prelude.rs#L366-L380) is specified on every command individually, instead of using `.global(true)` like `--verbose` does. This is done in order to customize the help string on some commands (like [`cargo test`](https://github.com/rust-lang/cargo/blob/9a1b0924c6ea3ac306b663aa73347d3b6a59e7c3/src/bin/cargo/commands/test.rs#L27-L33)). 

AFAIK, we can't have both `.global(true)` and a per-command customized help text.

This means that commands like `cargo owner add` don't support the `--quiet` flag. It doesn't work to add `.arg_quiet()` on the subcommand because [`config_configure`](https://github.com/rust-lang/cargo/blob/9a1b0924c6ea3ac306b663aa73347d3b6a59e7c3/src/bin/cargo/cli.rs#L375) only looks at the arguments of the top-level command, and the global arguments. It isn't capable of seeing subcommands.

I don't really know how to fix this. Some ideas:

- Change `config_configure` to somehow "see" subcommand arguments.
- Have each subcommand manually set the quiet argument on the config. This might have some awkwardness, since `config_configure` handles things like clashing arguments (I suspect clap's conflicts_with won't help with that).
- Drop support for per-command customized help text, and use `.global(true)`.

**Comment by epage** [comment]
Ill have to double check but I think you can have a global and locally override it and the value still gets propagated.

**Comment by ehuss** [comment]
Hm, I was running into a panic, but I think just defining it as global fixes it. I'll post a PR with that.
