### ISSUE TITLE
`run --{example,bin} fake` should give "unknown example" error

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1296]
```rust
$ cargo new test
$ cd test
$ cargo run --example fake
a bin target must be available for `cargo run`
```

This isn't the real error, it should say "unknown example `fake`" (or similar).

The same thing is emitted when a bin target does exist, and for `--bin fake`.

**Comment by alexcrichton** [comment]
Dupe of https://github.com/rust-lang/crates.io/issues/130 and PR at https://github.com/rust-lang/cargo/pull/1283
