### ISSUE TITLE
Intermittent failure to build nested dependencies (Windows only, Rust 1.73)

### ISSUE THREAD

**Issue by scouten-adobe** [rust-lang/cargo#12979]
### Problem

We are seeing frequent, but inconsistent, failures to build our crates when performing CI builds in our GitHub Actions-based environment.

The behavior is generally of the form (excerpted from https://github.com/contentauth/c2pa-rs/actions/runs/6870013213/job/18684036271):

```
   Compiling xmp_toolkit v1.6.0
error[E0463]: can't find crate for `num_enum`
  --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\xmp_toolkit-1.6.0\src\xmp_error.rs:19:5
   |
19 | use num_enum::FromPrimitive;
   |     ^^^^^^^^ can't find crate
```

I'm still working out the exact pattern of the intermittent failure, but it appears to involve the following factors:

* An indirect dependency (in this case `num_enum`) fails to build in time for the direct dependent crate (in this case `xmp_toolkit`) to use its dependencies. (Important: The direct dependent crate _does_ properly declare its dependency. In this case, that dependency is declared here: https://github.com/adobe/xmp-toolkit-rs/blob/main/Cargo.toml#L35.)
* The exact pairing of direct dependent and indirect dependent crate is inconsistent. In the specific case cited above, it was an attempt on our part to break another recurring build failure of this same pattern that led to this failure.
* We have _only_ observed the failures in the `windows-latest` environment on GitHub. We also run similar `mac-latest` and `ubuntu-latest` builds and have never observed this failure in those environments.
* We have _only_ observed the failures in `stable` version of Rust (Rust 1.73.0 as of this writing). We also run similar tests on our MSRV version (1.70.0) for this crate and have never observed this failure in that version.
* The failure reproduces frequently, but not reliably. I'd call it ~40% of builds based on recent experience.

### Version

```text
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-pc-windows-msvc
release: 1.73.0
LLVM version: 17.0.2
```

**Comment by weihanglo** [comment]
I am seeing it failed with `cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info`. Would it also fail without llvm-cov? For example `cargo test --all-features --workspace`.

**Comment by ehuss** [comment]
Some other suggestions for trying to figure it out:
* Try without CI caching. It could be corrupting the build cache, in which case there isn't much cargo could do about it. 
* Dump a list of all files in the target directory and see if `libnum_enum-*.rmeta` and `libnum_enum-*.rlib` are in the target directory, and look correct (not truncated, for example). 
* I don't know if you have the capacity to exfiltrate the build cache, but that could also provide you insight on what might be wrong. 
* Set the environment variable `RUSTC_LOG=rustc_metadata=trace` and see if the rustc crate loader tells you anything interesting. For some reason, cargo is thinking that the dependencies are there, but rustc isn't finding them.

**Comment by jackfarzan** [comment]
I've been working with @scouten-adobe on attempting to reproduce this issue with the latest stable release and haven't been able to, so I'm going to assume it's resolved.

**Comment by scouten-adobe** [comment]
As per @jackfarzan comment above, we are no longer seeing this issue. Closing as no longer reproducible.
