### ISSUE TITLE
Unknown flags should be pointed out

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1297]
```
$ cargo build --lib --rlease --feature foo 
Usage:
    cargo build [options]
```

This should say something along the lines of "invalid flag `--rlease`".

**Comment by alexcrichton** [comment]
cc @BurntSushi, does docopt give us an easy way to do this?

**Comment by BurntSushi** [comment]
Hmm, this is actually one of the few matching errors that `docopt.rs` tries to find. It should print in the error message:

```rust
extern crate docopt;

static USAGE: &'static str = "Usage: mycmd [-a]";

fn main() {
    let args = docopt::Docopt::new(USAGE)
                              .and_then(|d| d.parse())
                              .unwrap_or_else(|e| e.exit());
    println!("{:?}", args);
}
```

```bash
[andrew@Liger play] cargo build
[andrew@Liger play] ./target/scratch 
-a => Switch(false)
[andrew@Liger play] ./target/scratch -a
-a => Switch(true)
[andrew@Liger play] ./target/scratch -b
Unknown flag: '-b'

Usage: mycmd [-a]
```

I looked around in the Cargo source, but I couldn't see any obvious places where the error gets diced up. Or maybe the error is dropped and only the usage is printed?

**Comment by huonw** [comment]
(Pie-in-the-sky extension: "did you mean `--release`?")

**Comment by BurntSushi** [comment]
@huonw Issue added. :-)

**Comment by alexcrichton** [comment]
Cargo's transformation of docopt errors happens here: https://github.com/rust-lang/cargo/blob/13f32f900b31d23a712df9b20ffe1814ac6f68d0/src/cargo/lib.rs#L212-L218.

It looks pretty fishy to me, so I'll look into it soon and see if we're just doing something wrong. Thanks anyway @BurntSushi!
