### ISSUE TITLE
Workspace lints should have the option to be opt-out rather then opt-in

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-lang/cargo#12984]
### Problem

The newly introduced `[lints]` section has a fatal flaw for our codebase, which is that we define all of our lints in our root workspace, but then have to opt in, in every crate, to those lints through `[lints] workspace = true`. 

This means, for us, that we need to audit the Cargo.toml files every code review to make sure we didn't accidentally miss adding this line to the toml file. This introduces an additional manual workflows: a reviewer manually needs to check that it's present. (It looks from https://github.com/rust-lang/cargo/pull/12174 that at least `cargo new` adds the line automatically)

### Proposed Solution

Ideally we can force clippy lints for the entire workspace rather then having them be opt-in for every crate. 

Currently we're using the rustflags hack to accomplish this and while I'd love to move away from it in due time, the 1.74 release unfortunately can't be the release that does this for us.

**Comment by epage** [comment]
Closing in favor of #12208 so we talk about if/how we want to handle implicit inheritance holistically, rather than piece-meal for each feature.  If there is a reason we should keep this open separately, let us know!

**Comment by Jasper-Bekkers** [comment]
Thanks @epage would you want me to comment on that issue to describe how we'd like to be using this?

**Comment by epage** [comment]
Yes, that would be helpful
