### ISSUE TITLE
Cannot build projects that contain Git submodules

### ISSUE THREAD

**Issue by nukep** [rust-lang/cargo#1299]
I'm working on a Rust wrapper that compiles C source code using the `gcc` package. I'd like to use Git submodules in favor of copy-pasting the source tree, but Cargo refuses to build with them.
https://github.com/nukep/libxm-rs/issues/1 https://github.com/nukep/libxm-rs/tree/git-submodules-wont-work

Whenever I try to build the Rust wrapper or any of its dependants, Cargo spits out:
```
dan@HOBBES /c/src/rust/libxm-rs
$ cargo build --verbose
[17] Submodule 'libxm-sys\libxm' has not been added yet
```

However, the `libxm-sys` project will successfully build if `cargo build` is run inside the libxm-sys directory:
```
dan@HOBBES /c/src/rust/libxm-rs/libxm-sys
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling gcc v0.2.0
   Compiling libxm-sys v0.0.2 (file:///C:/src/rust/libxm-rs/libxm-sys)
```

Projects such as `git2-rs` won't compile either; Cargo gives a similar error very early on:
```
dan@HOBBES /c/src/rust/git2-rs
$ cargo build --verbose
[17] Submodule 'libgit2-sys\libgit2' has not been added yet
```

---

Building on Linux 64-bit works without errors, given the exact same steps and using Cargo nightly (9404539 2015-02-09 20:54:26 +0000).

I'm on Windows 64-bit using Cargo nightly (9404539  2015-02-09 20:54:26 +0000).

**Comment by msiemens** [comment]
A workaround that seems to work is to remove the project's `.git` and the submodule's `.git` directory.

**Comment by jmesmon** [comment]
I've run into something that seems very similar to this: If a cargo package has submodules that are not initialized, the same failure occurs/error message is emitted.

This needlessly complicates some of the packaging scripts I maintain.
