### ISSUE TITLE
error: no matching package named `clap` found location searched: registry `crates-io` required by package `node-template v4.0.0-dev

### ISSUE THREAD

**Issue by deepak-pawaar** [rust-lang/cargo#13013]
### Problem

im getting this error

error: no matching package named `clap` found location searched: registry `crates-io` required by package `node-template v4.0.0-dev 

when trying to run cargo build --release

**Comment by epage** [comment]
Could you include more in your reproduction steps, like
- Version of rust
- A minimal reproduction cast

**Comment by weihanglo** [comment]
Going to close due to inactivity. If you have a chance to provide more info, please reopen one.
