### ISSUE TITLE
`rustfix`: Fix Windows tests

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#13033]
For some reason, the [`parse_and_replace`](https://github.com/rust-lang/cargo/blob/65d0eb536dd4a7ae6ddc50ca14556896e450c4ff/crates/rustfix/tests/parse_and_replace.rs#L2) test of `rustfix` is disabled on Windows. I don't know why, but it would be nice for someone to investigate and fix that.

**Comment by tompscanlan** [comment]
After removing the `#![cfg(not(windows))]` on line 2, tests will run on win11 powershell. 1 test passes, one test is ignored. Ignored test requires a "custom rustc build" but I'm not sure what that would entail and don't see it in cursory docs scan. 

This may be another case like #13034... fix it and keep an eye out for flaky tests.
