### ISSUE TITLE
Builds always look for `src/main.rs`

### ISSUE THREAD

**Issue by bfops** [rust-lang/cargo#1303]
Even when building libraries, cargo will implicitly include `src/main.rs` implicitly in its list of fiels to build into the project. It won't complain if it's *not* there, but it will use it if it is, even if `main.rs` is referenced nowhere.

Create three files:

Cargo.toml:

    [package]

    name = "test"
    version = "0.0.0"

    [lib]

    name = "lib"
    path = "src/lib.rs"

src/lib.rs can be empty

src/main.rs:

    arglebargle

Compiling the project gives:

    [ben@windoze8isbest8 testbed]$ cargo build
       Compiling test v0.0.0 (file:///home/ben/testbed)
    src/main.rs:1:1: 1:12 error: expected item, found `arglebargle`
    src/main.rs:1 arglebargle
                  ^~~~~~~~~~~
    Could not compile `test`.

Removing `main.rs` or moving the files out of the `src` directory causes it to build fine.

**Comment by alexcrichton** [comment]
This is correct! Many projects rely on this inference to elide the corresponding `[[bin]]` section in the manifest.

You can explicitly ask the file to not be looked at with:

```toml
bin = []

[project]
# ...
```

**Comment by bfops** [comment]
That makes sense (although less so for libraries that don't have a `main`), but even with `bin`, if I *haven't* elided that section, and I've explicitly specified my "main" file to be, say, `src/bin.rs`, it seems really unintuitive to still try and build in `src/main.rs` just because it's there.

**Comment by alexcrichton** [comment]
Do you have a project I could look at? I'm unable to reproduce that behavior. (if true it's definitely a bug though!)

**Comment by bfops** [comment]
Oops you're right, I was completely off, it *doesn't* happen with `bin` if `path` is explicitly set to something else. It does happen with `lib`, though, even when path is set (e.g. `path = "src/lib.rs"`).
