### ISSUE TITLE
Deduplication problem with binary artifacts

### ISSUE THREAD

**Issue by tsatke** [rust-lang/cargo#13049]
### Problem

See https://github.com/tsatke/issue-showcase-01 for a showcase.

I have a workspace, that has a bindep dependency with a target (`x86_64`) different to the host system (`aarch64`) to one of its members.

The member is `no_std`.

Both the workspace root and the member depend transitively on `memchr` (which is irrelevant I think, but in this case, that's what happens), however the workspace root depends (transitively) on it with default-features, while the member requires `default-features=false`.

If I try to build, the compiler tells me that it can't find `std` for `memchr` (which is correct).
If I remove the `build.rs` file (which does nothing in the showcase, but is required in my actual use case), everything works fine again (which I don't entirely understand).

I think what's happening is, that cargo tries to build `memchr` only once with default features, which obviously can't work in the `no_std` member. This seems like incorrect behavior to me, especially since I can't seem to find a way around (so that the member actually gets `memchr` without default features).

### Steps

1. check out https://github.com/tsatke/issue-showcase-01
2. `cargo b`
3. `memchr` can't find `std`

Remove the `build.rs` file.

1. `cargo b`
2. no error anymore

### Notes

Probably related: https://github.com/rust-lang/cargo/issues/12863

<details><summary><code>cargo tree -I memchr -e features</code></summary>
<code>
memchr v2.6.4
└── object v0.32.1
    ├── object feature "archive"
    │   └── backtrace v0.3.69
    │       └── kernel v0.1.0 (/Users/tsatke/Desktop/showcase/devos/kernel)
    │           [build-dependencies]
    │           └── devos v0.1.0 (/Users/tsatke/Desktop/showcase/devos)
    │               └── devos feature "default" (command-line)
    ├── object feature "coff"
    │   └── object feature "pe"
    │       └── backtrace v0.3.69 (*)
    ├── object feature "elf"
    │   └── backtrace v0.3.69 (*)
    ├── object feature "macho"
    │   └── backtrace v0.3.69 (*)
    ├── object feature "pe" (*)
    ├── object feature "read_core"
    │   └── backtrace v0.3.69 (*)
    └── object feature "unaligned"
        └── backtrace v0.3.69 (*)
├── memchr feature "alloc"
│   └── memchr feature "std"
│       └── memchr feature "default"
│           ├── futures-lite v1.13.0
│           │   ├── futures-lite feature "alloc"
│           │   │   └── futures-lite feature "std"
│           │   │       └── futures-lite feature "default"
│           │   │           ├── async-io v1.13.0
│           │   │           │   └── async-io feature "default"
│           │   │           │       └── async-process v1.8.1
│           │   │           │           └── async-process feature "default"
│           │   │           │               [build-dependencies]
│           │   │           │               └── bootloader v0.11.4 (https://github.com/rust-osdev/bootloader?rev=a1b2eb88fd365fa7b4b35e29495076f22932cb7f#a1b2eb88)
│           │   │           │                   ├── bootloader feature "bios"
│           │   │           │                   │   └── bootloader feature "default"
│           │   │           │                   │       [build-dependencies]
│           │   │           │                   │       └── devos v0.1.0 (/Users/tsatke/Desktop/showcase/devos) (*)
│           │   │           │                   ├── bootloader feature "default" (*)
│           │   │           │                   └── bootloader feature "uefi"
│           │   │           │                       └── bootloader feature "default" (*)
│           │   │           └── async-process v1.8.1 (*)
│           │   ├── futures-lite feature "default" (*)
│           │   ├── futures-lite feature "fastrand"
│           │   │   └── futures-lite feature "std" (*)
│           │   ├── futures-lite feature "futures-io"
│           │   │   └── futures-lite feature "std" (*)
│           │   ├── futures-lite feature "memchr"
│           │   │   └── futures-lite feature "std" (*)
│           │   ├── futures-lite feature "parking"
│           │   │   └── futures-lite feature "std" (*)
│           │   ├── futures-lite feature "std" (*)
│           │   └── futures-lite feature "waker-fn"
│           │       └── futures-lite feature "std" (*)
│           └── futures-util v0.3.29
│               └── futures-executor v0.3.29
│                   └── futures v0.3.29
│                       ├── futures feature "alloc"
│                       │   └── futures feature "std"
│                       │       ├── futures feature "default"
│                       │       │   [build-dependencies]
│                       │       │   └── bootloader v0.11.4 (https://github.com/rust-osdev/bootloader?rev=a1b2eb88fd365fa7b4b35e29495076f22932cb7f#a1b2eb88) (*)
│                       │       └── futures feature "executor"
│                       │           └── futures feature "default" (*)
│                       ├── futures feature "async-await"
│                       │   └── futures feature "default" (*)
│                       ├── futures feature "default" (*)
│                       ├── futures feature "executor" (*)
│                       ├── futures feature "futures-executor"
│                       │   └── futures feature "executor" (*)
│                       └── futures feature "std" (*)
│                   └── futures-executor feature "std"
│                       └── futures feature "executor" (*)
│               ├── futures-util feature "alloc"
│               │   ├── futures feature "alloc" (*)
│               │   └── futures-util feature "std"
│               │       ├── futures feature "std" (*)
│               │       ├── futures-executor feature "std" (*)
│               │       ├── futures-util feature "channel"
│               │       │   └── futures feature "std" (*)
│               │       └── futures-util feature "io"
│               │           └── futures feature "std" (*)
│               ├── futures-util feature "async-await"
│               │   ├── futures feature "async-await" (*)
│               │   └── futures-util feature "async-await-macro"
│               │       └── futures feature "async-await" (*)
│               ├── futures-util feature "async-await-macro" (*)
│               ├── futures-util feature "channel" (*)
│               ├── futures-util feature "futures-channel"
│               │   └── futures-util feature "channel" (*)
│               ├── futures-util feature "futures-io"
│               │   └── futures-util feature "io" (*)
│               ├── futures-util feature "futures-macro"
│               │   └── futures-util feature "async-await-macro" (*)
│               ├── futures-util feature "futures-sink"
│               │   └── futures-util feature "sink"
│               │       └── futures v0.3.29 (*)
│               ├── futures-util feature "io" (*)
│               ├── futures-util feature "memchr"
│               │   └── futures-util feature "io" (*)
│               ├── futures-util feature "sink" (*)
│               ├── futures-util feature "slab"
│               │   └── futures-util feature "std" (*)
│               └── futures-util feature "std" (*)
├── memchr feature "default" (*)
└── memchr feature "std" (*)
</code>
</details>

### Version

```text
cargo 1.76.0-nightly (9b13310ca 2023-11-24)
release: 1.76.0-nightly
commit-hash: 9b13310ca596020a737aaa47daa4ed9ff8898a2f
commit-date: 2023-11-24
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.1.2 (sys:0.4.68+curl-8.4.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 14.1.0 [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report. You need to set the resolver in your workspace, like:

```toml
[workspace]
resolver = "2"
```

The previous version of the resolver unifies features across build dependencies and targets.

**Comment by tsatke** [comment]
Thanks @ehuss, big oversight on my part. The subcrate was `edition = 2021` (which implies the `resolver = 2`), but my workspace wasn't. `edition = 2021` fixed the problem for me.
