### ISSUE TITLE
Bug: Extremely Slow speed for cargo update

### ISSUE THREAD

**Issue by Lordworms** [rust-lang/cargo#13044]
### Problem

I am using the following operating system which is rent in a public cloud VPS
<img width="654" alt="image" src="https://github.com/rust-lang/cargo/assets/48054792/9cf504eb-2180-470e-9beb-925254ac8fde">

when I run cargo update or cargo check, the process is extremely slow and stuck here
<img width="691" alt="image" src="https://github.com/rust-lang/cargo/assets/48054792/dea6a3c2-1af5-4746-b9bb-6317bfca283c">

and the process goes like this
<img width="1025" alt="image" src="https://github.com/rust-lang/cargo/assets/48054792/7f4a594a-5aea-46b8-a49e-854b5f5d2f85">

### Steps

I just have two problem 
1. why does the default cargo download the unknown-linux-gun toochain since I am using a version of ubuntu.
<img width="970" alt="image" src="https://github.com/rust-lang/cargo/assets/48054792/225df7a3-8132-460d-bc56-12f79b95780c">
2. how to address the problem, is there any LOG file that I could check?

### Possible Solution(s)

1. Does the bug come with the incompatible between ubuntu and unknown-linux-gnu toolchain?

### Version

```text
cargo 1.74.0 (ecb9851af 2023-10-18)
```

**Comment by weihanglo** [comment]
> why does the default cargo download the unknown-linux-gun toochain since I am using a version of ubuntu.

`x86_64-unknown-linux-gnu` is the ["target triple" format](https://doc.rust-lang.org/nightly/cargo/appendix/glossary.html#target) for specifying platform architecture. It has less thing to do with your Linux distros.

> how to address the problem, is there any LOG file that I could check? 

It may depend on how large the repo of your git dependency is.

Unless you've configured some http proxies or turned `term.progess` off, you shall see a progress bar there, like:

```
    Updating git repository `https://github.com/rust-lang/rust.git`
       Fetch [==>                      ]  12.68%, 13.46MiB/s                                                                                  
```

Cargo underlying uses `libgit2` to perform git clone operations. If you find it slow, consider set env `CARGO_NET_GIT_FETCH_WITH_CLI=true` and try again.

There is a [`CARGO_LOG` environment variable](https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html?highlight=cargo_log#environment-variables-cargo-reads) you can set to debug. You might want to try `CARGO_LOG=cargo::sources::git=trace cargo update --verbose`.

**Comment by Lordworms** [comment]
OK, I would try that soon

**Comment by Lordworms** [comment]
turns out to be a git problem 
```
GnuTLS recv error (-110): The TLS connection was non-properly terminated.
```
I just banned the SSL and enlarged the HTTP buffer to solve the problem
```
git config --global http.sslVerify
git config --global http.postBuffer 1048576000
```
the problem may happen a lot on some new public cloud vps 

Thanks so much for your patient answer. I am a rookie in Rust and I learned a lot from it.

**Comment by weihanglo** [comment]
Great finding. Thank you for providing a solution to the issue.

Going to close this as it doesn't appear to be a Cargo issue. Feel free to add comments if you have any other thought.
