### ISSUE TITLE
Unable to Pass Arguments Through Cargo to Executable from PowerShell

### ISSUE THREAD

**Issue by mkozachek** [rust-lang/cargo#1305]
Running the command:
> cargo test -- --nocapture

in PowerShell produces:
>Usage:
cargo test [options] [--] [<args>...] 

However the same command works just fine in the regular cmd.exe command prompt.

**Comment by alexcrichton** [comment]
It looks like this is just a PowerShell oddity in dealing with `--` (e.g. googling [found this](http://stackoverflow.com/questions/12197823/powershell-why-do-i-need-to-escape-a-double-dash-parameter-in-args))

**Comment by coffeenotfound** [comment]
This still happens because, as mentioned, it's a weird thing that PowerShell does.
The workaround is using qoutes to escape all double dashes. The following seems to work as expected:
```
cargo test "--" "--nocapture"
```
