### ISSUE TITLE
Note build profile in `cargo build` output

### ISSUE THREAD

**Issue by tanadeau** [rust-lang/cargo#1309]
Currently the output of the `cargo build` command does not reference the build profile (debug/default or release) anywhere in its output. This creates two issues:
1. It hurts discoverability of the release profile, especially those coming from JIT'ed/interpreted languages where that's usually not user-visible
2. Makes saved build logs harder to decipher unless the commands themselves are echoed

I propose that the output of `cargo build` and similar "building" commands go from:
```
   Compiling foo v0.0.1 (file:///Users/tanadeau/foo)
```

to

```
   Using debug build profile. Optimizations are off. Use --release to turn them on.
   Compiling foo v0.0.1 (file:///Users/tanadeau/foo)
```

and

```
   Using release build profile. Optimizations are on. Remove --release to turn them off.
   Compiling foo v0.0.1 (file:///Users/tanadeau/foo)
```

**Comment by tanadeau** [comment]
From @Valloric on [this thread](http://internals.rust-lang.org/t/optimizing-by-default/1532/21), yet another story of a user not knowing about optimizations and the `--release` flag in Cargo: http://www.reddit.com/r/rust/comments/2vzxjr/poor_http_performance_iron_framework/

**Comment by tomjakubowski** [comment]
I'd like to add a suggestion that this nag message could be disabled via a Cargo config flag.

Also, it isn't necessarily true that the release profile is optimized and the debug profile is not, so Cargo should probably check these things before printing those messages.

**Comment by alexcrichton** [comment]
I do agree that this does seem like a problem, but I really do worry about non-newbie users. As soon as you know the difference you never want to see this message again, and I suspect that *all* Rust programmers will eventually know the difference. This means that if configuration is required it will mean that *all* Rust programmers will want that configuration. This indicates to me that it may be the wrong default.

It's definitely a tricky problem figuring out the best way to show this, but I just wanted to lay out some of my own personal worries.

**Comment by tanadeau** [comment]
@alexcrichton I'm not sure I understand why it would be an issue. It's a one-line message that should only show up when the "Compiling foo..." notice would appear anyway. Even for non-newbie users it would be useful as a configuration check like "whoops, I forgot to pass --release that time".

I would definitely agree more if `cargo build` gave only error output unless a `--verbose` flag was added, but that's not the case.

**Comment by steveklabnik** [comment]
In general, I tend to prefer the Unixism of 'dont print anything unless it's unexpected'

**Comment by tanadeau** [comment]
@steveklabnik If Cargo did that, then all of the current notices about compiling, downloading dependencies, etc. would not be printed either.

**Comment by steveklabnik** [comment]
I know.

**Comment by tanadeau** [comment]
I don't know of any build systems off the top of my head that are completely silent by default.

**Comment by pornel** [comment]
I wouldn't like extra lines in the output, but perhaps the existing "Compiling…" line could be changed accordingly from:

> Compiling foo v0.0.1

To something like:

> Building debug/unoptimized foo v0.0.1

**Comment by Ryman** [comment]
For `cargo run` we already print "Running `target/examples/blah`" we could append " with optimisations *OFF*" or similar.

**Comment by alexcrichton** [comment]
Having the debug/release folders has ended up meaning that I haven't seen this in quite some time, so I'm going to close this for now as the debug/release folder seems to be sufficient.

**Comment by Valloric** [comment]
Running a "debug" binary provides zero indication to developers coming from Ruby, Python, Java, JavaScript, C# or the other languages that together make up 90% of all modern development that the binary is much slower than a release build. We've been over this many, many times now. Dozens of people have pointed this out in discourse threads, RFC comments, r/rust discussions etc. 

"Debug" is not enough. There needs to be _something_ telling these users that an unoptimized build is being produced. Running a binary from a debug folder does _not_ convey this information.
