### ISSUE TITLE
`cargo publish` not sending token

### ISSUE THREAD

**Issue by davidcorrigan714** [rust-lang/cargo#13109]
### Problem

I'm trying to use `cargo publish` with our Artifactory instance running something like `cargo publish --token mytoken --package my_package --index "sparse+https://our.server.com/artifactory/api/cargo/rnd-cargo-pre-local/index/"` and I've been getting 401:

```
error: failed to get successful HTTP response from `https://our.server.com/artifactory/api/cargo/rnd-cargo-pre-local/index/config.json`, got 401
body:
{
  "errors" : [ {
    "status" : 401,
    "message" : "Authentication is required"
  } ]
}
```

I've confirmed the token I've specified is correct. I setup nginx on my local machine to poke a bit and requesting it with `cargo publish --index "sparse+http://127.0.0.1:8085/" --token "buffalo" --package artifactory_uploader_common` sure enough it's not sending the value specified with `--token` when requesting config.json which of course results in a 401. 

### Version

cargo 1.70.0 (ec8a8a0ca 2023-04-25)

**Comment by weihanglo** [comment]
Does latest stable (1.74) work for you?

**Comment by davidcorrigan714** [comment]
Well that worked on my dev box but apparently I haven't dove too deeply into rust versioning concepts yet. We're on 1.70.0 and don't really plan on updating the compiler version especially so late in the quarter and close to holidays. We just set RUSTUP_TOOLCHAIN at the top of the build CI pipelines and that's essentially standard for everyone until we bump every few quarters but trying to bump cargo up to 1.74 while keeping the rest of the toolchain at 1.70 doesn't look particularly easy to accomplish.

**Comment by davidcorrigan714** [comment]
Well I'll figure out the versioning woes at some point, it works in latest so whatever bug/feature was in 1.70.0 is fixed so not much to do here for that.
