### ISSUE TITLE
Cargo doesn't respect CARGO_TERM_COLOR for help messages

### ISSUE THREAD

**Issue by Sindisil** [rust-lang/cargo#13124]
### Problem

I always run with CARGO_TERM_COLOR=never, as I find colorized output very hard to read, nearly impossible to read with default term colors on many systems (both Windows & Linux), and of negligible value even if I tweak  the default term colors.

Color enable/disable for cargo sub-commands is all over the map, which I understand, since each sub-command is responsible for implementing a "--color" option and/or reading and respecting CARGO_TERM_COLOR. However, even cargo itself is ignoring color preferences, at least in help. I've tried in both:

cargo version
cargo 1.74.0 (ecb9851af 2023-10-18)

and

cargo version
cargo 1.76.0-nightly (623b78849 2023-12-02)

![image](https://github.com/rust-lang/cargo/assets/6267121/83d604d8-f7ca-499f-bf48-fd8f82e3dd55)

### Steps

1. Set CARGO_TERM_COLOR=never
2. Run the command "cargo help"
3. Observe that the help message is colorized.

### Version

```text
Happens with both

>cargo version --verbose
cargo 1.74.0 (ecb9851af 2023-10-18)
release: 1.74.0
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 11 Professional) [64-bit]

and

>cargo version --verbose
cargo 1.76.0-nightly (623b78849 2023-12-02)
release: 1.76.0-nightly
commit-hash: 623b788496b3e51dc2f9282373cf0f6971a229b5
commit-date: 2023-12-02
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 11 Professional) [64-bit]
```

**Comment by weihanglo** [comment]
See #13052 and #9012, and we track that in #9012. Cargo respects `NO_COLOR=1` btw.

**Comment by weihanglo** [comment]
Thanks. I'll close this in favor of #9012. Probably tweak the issue title to make it more obvious.
