### ISSUE TITLE
testsuite: explictly update the mtime when needed

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/cargo#13139]
Currently some tests use [`Project::change_file`](https://github.com/rust-lang/cargo/blob/749654c5fdb26e81f543e76806aedde4327c6cd1/crates/cargo-test-support/src/lib.rs#L398-L400) with an empty content string just to update the modified time of the file e.g.:

https://github.com/rust-lang/cargo/blob/bdef274df29a4f521a2c4f59f7ed286f1b720ee0/tests/testsuite/freshness.rs#L558

However, updating a zero length file to be zero length isn't guaranteed to change the modified time (it might be a no-op). Cargo's tests should explicitly set the modified time using the new [`File::set_times`](https://doc.rust-lang.org/beta/std/fs/struct.File.html#method.set_times) API.

There are at least a couple of ways this could be done. An explicit method could be added and used in place of calling `change_file` with an empty string. Or else `change_file` (or the underlying `FileBuilder`) could be updated to always set the modified time.

**Comment by ehuss** [comment]
> updating a zero length file to be zero length isn't guaranteed to change the modified time

I'm not aware of any tests that do this. Can you point to some? They should always be modifying a file that already has content, which absolutely should change the mtime. (That is what the linked `rebuild_tests_if_lib_changes` does.)

I would be reluctant to have tests manually changing mtimes. They already do that a lot, but I wouldn't want them to do that *more*. I like having tests try to behave as close to the way real users would be doing things as possible.

If the `change_file("src/lib.rs", "")` isn't clear enough, a suggestion would be to something like `change_file("src/lib.rs", "// modified")` to make it clearer what its intent is.
