### ISSUE TITLE
Passing non-boolean options to dependencies

### ISSUE THREAD

**Issue by Binero** [rust-lang/cargo#1315]
Is it possible to pass options to the build script of one of the dependencies? I require this for some sophisticated code generation.

**Comment by alexcrichton** [comment]
There are indeed! All enabled features of a crate are passed through into the build script. This means various options are enabled via enabling features.

**Comment by Binero** [comment]
This is not really what I'm looking for. This only allows me to set on/off flags, which represent packages. I want to be able to set other options, like integers, version numbers, etc.

**Comment by alexcrichton** [comment]
Ah yes, this is not currently supported (you'd have to add a feature-per-value basically).
