### ISSUE TITLE
Publish  `home` crate 0.5.9 

### ISSUE THREAD

**Issue by dallenng** [rust-lang/cargo#13165]
### Problem

I don't know if it is intended or not, but the `home` crate had a few unpublished version bumps. The last published version is `0.5.5` while the version in this repo `Cargo.toml` is actually `0.5.9`.

**Comment by weihanglo** [comment]
It's not intended. Just somebody need to stand out and fix it (and it presumably should be me).

Posted a fix <https://github.com/rust-lang/cargo/pull/13167> to skip that checks. For the next published version we can just publish 0.5.9. There is no real need to go back and publish 0.5.6, 0.5.7, or 0.5.8 I believe.

**Comment by ehuss** [comment]
@dallenng Is there something that you need from the unpublished changes? From what I can tell, there were only some documentation changes.

We could certainly publish an update if someone wants to update the changelog.

**Comment by dallenng** [comment]
As far as I can tell, apart from the documentation changes, there is also the `windows-sys` dependency update, which could be useful for minimizing dependency duplication. For example, if a crate depends on `home` and a crate `X`  depending on `windows-sys` `0.52.0`, publishing a new `home` version will allow having only one `windows-sys` in the dependency tree.

**Comment by weihanglo** [comment]
Sounds good to me if anyone wants to help prepare the changelog for 0.5.9 release. Maybe could also fix [this issue](https://github.com/rust-lang/cargo/issues/13138) altogether in 0.5.9.

**Comment by dallenng** [comment]
Hopefully I didn't miss a change but here is a list of meaningful changes since the `0.5.5` release :
- #12654
- #13089
- #13173

I will make a PR preparing the changelog.
