### ISSUE TITLE
How to Become a Member?

### ISSUE THREAD

**Issue by artwalker** [rust-lang/cargo#13169]
### Problem

Hello everyone,

I'm interested in becoming a member of rust-lang. Could someone please guide me on the process or requirements to become a member?

Thank you in advance for your assistance!

Best regards,
Ethan Wang

**Comment by weihanglo** [comment]
Can also look around this page and see which area you're interested in, and then contact them: https://www.rust-lang.org/governance/

**Comment by artwalker** [comment]
Thank you all. Wish you all best!

**Comment by weihanglo** [comment]
If you don't mind, I'll close this as resolved.

Feel free to chat with us (and other teams) on <https://rust-lang.zulipchat.com>. The Cargo team also hosts [office hours](https://github.com/rust-lang/cargo/wiki/Office-Hours) third times a week, so come and join us!

**Comment by artwalker** [comment]
@weihanglo Thank you. I want to apply for the Embeded group. Maybe I should make up my resume, right? Then I can apply for it.

**Comment by weihanglo** [comment]
> I want to apply for the Embeded group.

They are on Matrix. See their repo for more <https://github.com/rust-embedded/wg>.

>  Maybe I should make up my resume, right? Then I can apply for it.

@artwalker, you definitely could, but it is not always necessary. Participating in open source projects is a process of “earning trust”. If you can read Chinese, I find this blogpost useful for understanding how it works: <https://www.tisonkun.org/2022/09/12/maintainer-criterions/>

**Comment by artwalker** [comment]
@weihanglo  Thanks a lot. You give me many useful materials.
