### ISSUE TITLE
Static linking not locating libraries in standard paths

### ISSUE THREAD

**Issue by Wenzel** [rust-lang/cargo#13161]
### Problem

I am encountering an issue with static linking in my [xenstore-sys](https://github.com/Wenzel/xenstore-sys) crate, a binding to the [libxenstore](https://packages.debian.org/buster/libxenstore3.0) library.

After modifying the build script to enable static linking, rustc fails to locate the libxenstore library, despite it being installed in standard paths.

```shell
$ find /usr/lib -name '*xenstore*'
/usr/lib/x86_64-linux-gnu/libxenstore.so.4
/usr/lib/x86_64-linux-gnu/libxenstore.so.4.0
/usr/lib/x86_64-linux-gnu/libxenstore.a
/usr/lib/x86_64-linux-gnu/pkgconfig/xenstore.pc
/usr/lib/x86_64-linux-gnu/libxenstore.so
```

### Steps

The [static linking](https://github.com/Wenzel/xenstore-sys/pull/10) PR showcases the problem.
This [commit](https://github.com/Wenzel/xenstore-sys/pull/10/commits/4fac7d8fbb72f849aa38669710c9801d8496c4cb) enables static linking

```rust
println!("cargo:rustc-link-lib=static=xenstore");
```

The [next one](https://github.com/Wenzel/xenstore-sys/pull/10/commits/868b1ed35f419b2a70b94519935eee06e1e28bc0) enables the build on stable and nightly

And you can see that now the library fails to build on Github Action:
https://github.com/Wenzel/xenstore-sys/actions/runs/7191653299/job/19586697996#step:5:118
![image](https://github.com/rust-lang/cargo/assets/964610/14f4bbe2-e9b4-4dbb-944f-4c63e8f469e7)

Here is also a Dockerfile to repro the issue locally:
```Dockerfile
FROM rustlang/rust:nightly

RUN apt-get update && apt-get install -y git build-essential clang libxen-dev
RUN git clone https://github.com/Wenzel/xenstore-sys && cd xenstore-sys && git checkout 4b6fda11cbff22e8a8889bed6918c29f0f0f03a1
WORKDIR xenstore-sys
RUN cargo build -v
```

### Possible Solution(s)

A temporary solution now is to manually specify the search path:
https://github.com/Wenzel/xenstore-sys/pull/10/commits/fc79546b5d32d790c1aba0b720f11e08399044a2

```rust
println!("cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu");
```

However this is just a workaround, since standard libary paths should be recognized by rustc like it's already doing for dynamic libraries.

### Version

```text
cargo 1.74.1 (ecb9851af 2023-10-18)
release: 1.74.1
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 23.10 (mantic) [64-bit]
```

**Comment by weihanglo** [comment]
I am not sure why static link is needed generating xenstore bindings, but I would recommend taking a look at [`pkg-config`](https://crates.io/crates/pkg-config). 

You may have something like (⚠️ NOT GUARANTEED TO WORK)

```rust
let lib = pkg_config::Config::new()
    .cargo_metadata(false)
    .probe("xenstore")
    .unwrap();
println!("cargo:rustc-link-lib=static=xenstore");

for path in &lib.link_paths {
    println!("cargo:rustc-link-search=native={}", path.display());
}
```


However, it might not work, since in `/usr/lib/x86_64-linux-gnu/pkgconfig/xenstore.pc` it might have `Requires.private` and you end up need to static link to those as well. So you might need extra tweak like

```rust
for lib in &xenstore.libs {
    println!("cargo:rustc-link-lib=static={lib}");
}
```
