### ISSUE TITLE
Cargo --config KEY=VALUE is not effective

### ISSUE THREAD

**Issue by UmeshKalappa0** [rust-lang/cargo#13163]
### Problem

We have the hello world sample and added dependency rand like

```console
$ cargo add rand 
```

then Cargo.toml looks like

```console
$ cat Cargo.toml
```

```toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
```
and we are trying to pass the linker option for rustc through the cargo like

```console
$ cargo --config 'build.rustflags = ["-L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/ -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/"]' build  --verbose
```
rand has the dependency like libc and cargo try to build and fails like

```
Some errors have detailed explanations: E0408, E0412, E0425, E0463, E0531.
For more information about an error, try `rustc --explain E0408`.
error: could not compile `libc` (build script) due to 50 previous errors
```
```console
$ rustc --crate-name build_script_build CARGO_HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.151/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=97b99bae06b5ff0f -C extra-filename=-97b99bae06b5ff0f --out-dir /path/rust/hello/target/debug/build/libc-97b99bae06b5ff0f -L dependency=/path/rust/hello/target/debug/deps --cap-lints allow
```
note that from 1.70.0 rustc or cargo needs to pass the "-L/rustlib/" target libs path manually and before pervious version are working fine without ,hence we tried to pass through cargo like --config or RUSTFLAGS ,which is not effective and cargo is not passing to rustc like mentioned above ...

any suggestions here to avoid these errors or how we make cargo search the target libs by default without manually intervention from command-line /RUSTFLAGS/ etc ?

### Steps

like

```console
$ export RUSTFLAGS="-L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/ -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/"

   Compiling libc v0.2.151
   Compiling cfg-if v1.0.0
   Compiling ppv-lite86 v0.2.17
     
  Running `rustc --crate-name cfg_if --edition=2018 <path>/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cfg-if-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1f5677bb9cb2f9d9 -C extra-filename=-1f5677bb9cb2f9d9 --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/ -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/`
  Running `rustc --crate-name ppv_lite86 --edition=2018 <path>/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ppv-lite86-0.2.17/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="simd"' --cfg 'feature="std"' -C metadata=3911f71223ba48c3 -C extra-filename=-3911f71223ba48c3 --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/ -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/`
  Running `rustc --crate-name build_script_build <path>/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.151/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=97b99bae06b5ff0f -C extra-filename=-97b99bae06b5ff0f --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/build/libc-97b99bae06b5ff0f -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow`
```
     
no luck also with

```console
$ cargo rustc -- "-L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/ "
```
if look at above cipher ,the library search was passed to CFG-If and PPV-lite86 compiling ,but not LIBC ...

any inputs from experts will helps us to debug the issue further ,thanks in advance

### Notes
```console
$ cargo build  --target aarch64-wrs-vxworks --verbose
   Compiling libc v0.2.151
   Compiling cfg-if v1.0.0
   Compiling ppv-lite86 v0.2.17
     Running `rustc --crate-name cfg_if --edition=2018 /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cfg-if-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=94c41ef99b5090bf -C extra-filename=-94c41ef99b5090bf --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps --target aarch64-wrs-vxworks -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/`
     Running `rustc --crate-name ppv_lite86 --edition=2018 /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ppv-lite86-0.2.17/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="simd"' --cfg 'feature="std"' -C metadata=9c465ec463cac700 -C extra-filename=-9c465ec463cac700 --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps --target aarch64-wrs-vxworks -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/`

Running `rustc --crate-name build_script_build /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.151/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=97b99bae06b5ff0f -C extra-filename=-97b99bae06b5ff0f --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/build/libc-97b99bae06b5ff0f -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow`
error[E0463]: can't find crate for `std`

error: cannot find macro `panic` in this scope
```

### Version 
```console
$ cargo --version 
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
```

_No response_

**Comment by epage** [comment]
@UmeshKalappa0 its not to clear to me why you are passing `-L`.  You mention it is needed as of 1.70 but that shouldn't be the case

FYI I tried to go back through the issue to add code fences but its unclear what is meant to be literal output or not and what looks to be literal output is incomplete, like mentioning errors exist but not showing the errors.

**Comment by UmeshKalappa0** [comment]
@epage  ,than you for reply and queries 
>>@UmeshKalappa0 its not to clear to me why you are passing -L. You mention it is needed as of 1.70 but that shouldn't be the case
looks like sysroot is not configured likely  ,i.e  with 1.70

rustc --print sysroot --target aarch64-wrs-vxworks 

/folk/prj-rust-dev/umesh/vxworks/vx7-2309-features

and with 1.64 ,we see 
rustc --print sysroot --target aarch64-wrs-vxworks 

/folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu//

>>FYI I tried to go back through the issue to add code fences but its unclear what is meant to be literal output or not and what looks to be literal output is incomplete, like mentioning errors exist but not showing the errors.
my bad we see the issue like 

`cargo build  --target aarch64-wrs-vxworks --verbose
   Compiling libc v0.2.151
   Compiling cfg-if v1.0.0
   Compiling ppv-lite86 v0.2.17
     Running `rustc --crate-name cfg_if --edition=2018 /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cfg-if-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=94c41ef99b5090bf -C extra-filename=-94c41ef99b5090bf --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps --target aarch64-wrs-vxworks -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/`
     Running `rustc --crate-name ppv_lite86 --edition=2018 /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ppv-lite86-0.2.17/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="simd"' --cfg 'feature="std"' -C metadata=9c465ec463cac700 -C extra-filename=-9c465ec463cac700 --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps --target aarch64-wrs-vxworks -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/aarch64-wrs-vxworks/debug/deps -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow -L /folk/prj-rust-dev/umesh/vxworks/vx7-2309-features/compilers/rust-1.70.0.0/x86_64-unknown-linux-gnu/bin/../lib/rustlib/aarch64-wrs-vxworks/lib/`

Running `rustc --crate-name build_script_build /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.151/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=97b99bae06b5ff0f -C extra-filename=-97b99bae06b5ff0f --out-dir /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/build/libc-97b99bae06b5ff0f -L dependency=/folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/hello/target/debug/deps --cap-lints allow`
error[E0463]: can't find crate for `std`

error: cannot find macro `panic` in this scope
   --> /folk/prj-rust-dev/umesh/vxworks/vsb/usr/rust/../../usr/rust/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.151/build.rs:192:25
    |
192 |                 None => panic!("Failed to get rustc version"),
    |                         ^^^^^
...
197 |     let rustc = otry!(env::var_os("RUSTC"));
    |                 --------------------------- in this macro invocation
    |
    = note: this error originates in the macro `otry` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `panic` in this scope`

@epage 
any suggestion on sysroot and how we can change to sysroot  from cargo that is effective on build.rs invocation too ?

**Comment by weihanglo** [comment]
I had a hard time understanding the question. If you want to use your own custom toolchain, you might want to [link to it via rustup](https://rust-lang.github.io/rustup/concepts/toolchains.html?highlight=link#custom-toolchains). If not, could you format the comment better, and provide a reproducer as a git repo or a zip file?

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. Here are tips about [how to create a minimal, complete, and verifiable example][mcve].

Feel free to comment below or open a new issue if there is any update.

[mcve]: https://stackoverflow.com/help/mcve
