### ISSUE TITLE
cargo error: unrecognized subcommand, but sees it in --list

### ISSUE THREAD

**Issue by aharbis** [rust-lang/cargo#13170]
### Problem

I am working on building a `cargo` subcommand, let's call it `cargo deps`. The binary name is `cargo-deps`, following the documentation for [extending cargo with subcommands](https://doc.rust-lang.org/book/ch14-05-extending-cargo.html). After installing the binary via `cargo install`, I can see and execute the binary directly via my `$PATH`, and `cargo --list` sees it, but `cargo deps` reports an error stating `unrecognized subcommand`.

### Steps

```
$ cargo install --path .
  Installing cargo-deps v0.2.0 (/home/aharbis/git/cargo-deps)
    Updating crates.io index
    ...
    Finished release [optimized] target(s) in 26.38s
  Installing /home/aharbis/.cargo/bin/cargo-deps
   Installed package `cargo-deps v0.2.0 (/home/aharbis/git/cargo-deps)` (executable `cargo-deps`)

$ which cargo-deps
/home/aharbis/.cargo/bin/cargo-deps

$ cargo-deps --version
cargo-deps 0.2.0

$ cargo --list
Installed Commands:
    ...
    clippy               Checks a package to catch common mistakes and improve your Rust code.
    config               Inspect configuration values
    d                    alias: doc
    deps
    doc                  Build a package's documentation
    fetch                Fetch dependencies of a package from the network
    ...

$ cargo deps --version
error: unrecognized subcommand 'deps'

Usage: cargo-deps [OPTIONS] [COMMAND]

For more information, try '--help'.
```

### Notes

I have installed other public subcommands, such as `cargo audit`, and that works fine:

```
$ which cargo-audit
/home/aharbis/.cargo/bin/cargo-audit

$ cargo audit --version
cargo-audit 0.18.3
```

The `cargo-deps` project is private, but if necessary I can try to reproduce this in a new open-source project.

### Version

```text
$ cargo version --verbose
cargo 1.74.1 (ecb9851af 2023-10-18)
release: 1.74.1
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by epage** [comment]
The unrecognized `deps` subcommand is coming from `cargo-deps`, not from `cargo` (notice the usage in the error message)

Unlike git's third-party subcommands, cargo passes the name of the subcommand to the binary being run.

You can find an [example for how to write a third-party subcommand within clap's documentation](https://docs.rs/clap/latest/clap/_derive/_cookbook/cargo_example_derive/index.html).

**Comment by aharbis** [comment]
Ah, okay. Yeah, the usage output was a bit odd to me - but that makes more sense now. I didn't realize the name of the subcommand would be passed to the binary, but that's simple enough to handle.

Thanks for the pointer to the clap documentation!

**Comment by weihanglo** [comment]
FWIW, the way Cargo handles external commands is also documented here in The Cargo Book: <https://doc.rust-lang.org/nightly/cargo/reference/external-tools.html#custom-subcommands>
