### ISSUE TITLE
Update a Github dependency with `--precise <short_id>` fails

### ISSUE THREAD

**Issue by JEnoch** [rust-lang/cargo#13188]
### Problem

Updating a Github dependency with a short commit id fails with such log:
```log
error: Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
  object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)
```

### Steps

```bash
cargo new test-cargo-precise 
cd test-cargo-precise 
cargo add --git https://github.com/rust-lang/regex regex 
CARGO_LOG=trace cargo update -p regex --precise 837fd85
```

Resulting `cargo update` log:
```log
   0.000038417s TRACE cargo: start="2023-12-21T07:57:53.908041000Z"
   0.000538542s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_ALIAS_UPDATE", parts: [("alias", 5), ("update", 11)] }
   0.000570375s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_TERM", parts: [("term", 5)] }
   0.000589250s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_NET", parts: [("net", 5)] }
   0.001122417s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_HTTP", parts: [("http", 5)] }
   0.001523083s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_BUILD", parts: [("build", 5)] }
   0.001558208s TRACE cargo::util::toml: read_manifest; path=/Users/julienenoch/tmp/test-cargo-precise/Cargo.toml; source-id=/Users/julienenoch/tmp/test-cargo-precise
   0.001857042s DEBUG cargo::core::workspace: find_members - only me as a member
   0.002212917s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_PATCH", parts: [("patch", 5)] }
   0.002268583s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRY_INDEX", parts: [("registry", 5), ("index", 14)] }
   0.002286292s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRIES_CRATES_IO_PROTOCOL", parts: [("registries", 5), ("crates-io", 16), ("protocol", 26)] }
   0.002298250s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRIES_CRATES_IO_PROTOCOL", parts: [("registries", 5), ("crates-io", 16), ("protocol", 26)] }
   0.002305875s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRY_INDEX", parts: [("registry", 5), ("index", 14)] }
   0.002316875s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_SOURCE", parts: [("source", 5)] }
   0.002328917s DEBUG cargo::core::registry: load/missing  https://github.com/rust-lang/regex#837fd85
   0.002347417s DEBUG cargo::core::registry: loading source https://github.com/rust-lang/regex#837fd85
   0.002353417s DEBUG cargo::sources::config: loading: https://github.com/rust-lang/regex#837fd85
   0.002360000s TRACE cargo::core::source_id: loading SourceId; https://github.com/rust-lang/regex#837fd85
    Updating git repository `https://github.com/rust-lang/regex`
   0.009446625s TRACE cargo::sources::git::source: updating git source `GitRemote { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/rust-lang/regex", query: None, fragment: None } }`
   0.010665208s DEBUG cargo::sources::git::utils: attempting GitHub fast path for https://api.github.com/repos/rust-lang/regex/commits/837fd85000000000000000000000000000000000
   0.225184458s DEBUG cargo::sources::git::utils: skipping gc as there's only 2 pack files
   0.225689625s DEBUG cargo::sources::git::utils: doing a fetch for https://github.com/rust-lang/regex
   0.226630292s DEBUG cargo::sources::git::utils: initiating fetch of ["+refs/heads/*:refs/remotes/origin/*", "+HEAD:refs/remotes/origin/HEAD"] from https://github.com/rust-lang/regex
   0.716648583s DEBUG cargo::sources::git::utils: attempting GitHub fast path for https://api.github.com/repos/rust-lang/regex/commits/837fd85000000000000000000000000000000000
   0.739785417s DEBUG cargo::sources::git::utils: skipping gc as there's only 0 pack files
   0.739872500s DEBUG cargo::sources::git::utils: doing a fetch for https://github.com/rust-lang/regex
   0.740022625s DEBUG cargo::sources::git::utils: initiating fetch of ["+refs/heads/*:refs/remotes/origin/*", "+HEAD:refs/remotes/origin/HEAD"] from https://github.com/rust-lang/regex
   2.332392833s DEBUG cargo: exit_with_error; err=CliError { error: Some(Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
    object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)), exit_code: 101 }
   2.332410958s DEBUG cargo: display_error; err=Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
    object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)
error: Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
  object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)
```

### Notes

This Github API URL used by `cargo` returns an error:
https://api.github.com/repos/rust-lang/regex/commits/837fd85000000000000000000000000000000000

While the same but with short commit id succeeds:
https://api.github.com/repos/rust-lang/regex/commits/837fd85

What's strange is that I successfully used such `cargo update -p <dep> --precise <short_id>` few weeks ago.
Could it be that Github changed its API ?

### Version

```text
cargo 1.74.1 (ecb9851af 2023-10-18)
release: 1.74.1
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.1.2 (sys:0.4.68+curl-8.4.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 14.1.2 [64-bit]

--
Also same issue with:

cargo 1.71.0 (cfd3bbd8f 2023-06-08)
release: 1.71.0
commit-hash: cfd3bbd8fe4fd92074dfad04b7eb9a923646839f
commit-date: 2023-06-08
host: aarch64-apple-darwin
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.1.2 (sys:0.4.61+curl-8.0.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Mac OS 14.1.2 [64-bit]
```

**Comment by weihanglo** [comment]
Got an impression that @Eh2406 just talked about this somewhere. @Eh2406 do you remember anything?

**Comment by JEnoch** [comment]
Digging into the code, I see this completion with `0`s of short commit id comes from usage of `git2::Oid::from_str(s)` in [`SourceId::precise_git_oid()`](https://github.com/rust-lang/cargo/blame/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/core/source_id.rs#L469).
It somehow ends up to be used in [`github_fast_path()`](https://github.com/rust-lang/cargo/blame/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/sources/git/utils.rs#L1466), probably after conversion from `git2::Oid` to `GitReference::Rev(String)`. Possibly [this one](https://github.com/rust-lang/cargo/blame/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/sources/git/utils.rs#L112) ?

Could the regression come from https://github.com/rust-lang/cargo/pull/12849 ?
But that wouldn't explain why the issue also occurs with cargo 1.71.0 that was release before this PR.

**Comment by weihanglo** [comment]
Good finding! Thank you.

I've tested several toolchains. Starting from 1.46.0 Cargo contains this bug, which contains the PR <https://github.com/rust-lang/cargo/pull/8363> that you observed the potential bad commit. The Cargo started using `Oid::from_str` to parse `precise` field since then:

https://github.com/rust-lang/cargo/blob/ddc27999c17c55170e1812b50d27121cf43894ee/src/cargo/sources/git/source.rs#L35-L37

The zero-padding behavior is [a documented behavior in libgit2](https://github.com/libgit2/libgit2/blob/d5afc0390c3ef919fcde23300d7aefdaeafa5daa/include/git2/oid.h#L70-L71
) like from the beginning, so not a dependency issue.

It might or might not be GitHub has changed the API. I cannot tell, as Cargo had no such a test exercising `--precise <SHA>` [until recently](https://github.com/rust-lang/cargo/blob/363a2d11320faf531f6aacd1ea067c6bc08343b9/tests/testsuite/git.rs#L774-L775). And that doesn't even test against short ID.


Feel like [`SourceId::from_url`](https://github.com/rust-lang/cargo/blob/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/core/source_id.rs#L143-L153) has an assumption that `precise` for Git source is always a valid long-enough Git SHA (the format is opaque to cargo users btw). One fix I can think of is comparing if the value of `--precise` is a hex string of 40/64 characters [here](https://github.com/rust-lang/cargo/blob/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/ops/cargo_generate_lockfile.rs#L112), and give a nice error if not. This is only a fix on the surface, if we find more commands have this kind of bug, we might want to push the fix down to lower-level.

**Comment by linyihai** [comment]
> One fix I can think of is comparing if the value of --precise is a hex string of 40/64 characters [here](https://github.com/rust-lang/cargo/blob/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/ops/cargo_generate_lockfile.rs#L112), and give a nice error if not.

I will provide a PR to fix it based on this

>  This is only a fix on the surface, if we find more commands have this kind of bug, we might want to push the fix down to lower-level.

This is worth a look, I will check the relevant code by the way, once there is any feasible plan I will make a corresponding plan

@rustbot claim

**Comment by JEnoch** [comment]
> One fix I can think of is comparing if the value of --precise is a hex string of 40/64 characters [here](https://github.com/rust-lang/cargo/blob/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/ops/cargo_generate_lockfile.rs#L112), and give a nice error if not.

If possible I would like to still have the possibility to use `--precise` with short SHA.

As a use case in [Zenoh](https://github.com/eclipse-zenoh/zenoh-backend-influxdb?tab=readme-ov-file#example-with-a-version-built-from-sources): there are some plugins (shared libraries) for which the dependency to the `zenoh` crate must be the exact same commit than the hosting binary (to avoid ABI incompatibility). The short commit id can be retrieved via `--version` that return the result of `git describe`.
Using this short commit id in `--precise` would avoid the user to search for the long commit id.

I think a solution could be the following:
 - [`github_fast_path()`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/utils.rs#L1394) could trim the extra `0`s from the [`GitReference::Rev(rev)`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/utils.rs#L1411) before querying `https://api.github.com/repos/{username}/{repository}/commits/{rev}`. 
   Thus the query will succeed with short SHA. The long SHA is returned in [`FastPathRev::NeedsFetch(oid_to_fetch)`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/utils.rs#L1496).
 - Then the [`fetch()`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/utils.rs#L926) operation could return this `oid_to_fetch` returned by `github_fast_path()` as an `Option<Oid>`
 - Finally, in [`checkout()`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/utils.rs#L104), if [`fetch()`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/utils.rs#L115) returns `Some(rev)` this `rev` is the long SHA and should be tested if contained in `db`
 
 I tested such a patch [here](https://github.com/JEnoch/cargo/commit/0be684bd2de29d1b955b34635ac288290a36b075), and it seems to work.
 What do you think?

**Comment by weihanglo** [comment]
Thanks for looking into the issue! The effort is much appreciated :)

However, there are probably two things we need to take care of:

* [The patch](https://github.com/JEnoch/cargo/commit/0be684bd2de29d1b955b34635ac288290a36b075) seems for GitHub only. I would like to see a general fix, as this issue is not GitHub-specific. GitLab or even a local git repository has the bug.
* [Changing `locked_rev`](https://github.com/JEnoch/cargo/commit/0be684bd2de29d1b955b34635ac288290a36b075?diff=unified&w=0#diff-0e22d3c91f7eac28d92382b445103b421ef842eef760bdc1885be073117f3e9dL124-R124) is not desired, as the new rev might not be the same as the old one, which we lose the meaning of "locked". Git short hashes can also [be generated deliberately](https://github.com/not-an-aardvark/lucky-commit), and it doesn't seem too safe to trim and query over network.

That said, it doesn't mean we cannot support short hashes. We need to find a reliable way to pass down the value from `--precise`, and get it resolved to a full SHA. If the solution is not yet ready, for now we can give a nice message of "short hash not supported".

**Comment by JEnoch** [comment]
Understood, that makes sense.

I think the root of the issue is that the conversion from short SHA to `git2::Oid` leads to a 20 bytes SHA completed with `0`s that cannot be found in the `git2::Repository` via call to `revparse_single()`.

I made [some tests](https://gist.github.com/JEnoch/36750b89d7f40dec90afbed076f76736) with git2:
`revparse_single()` accepts short SHA and returns the full SHA. It detects short SHA collisions, returning such this error message: _"ambiguous OID prefix - found multiple offsets for pack entry"_. So I think it's safe to use it to resolve a short SHA into a long SHA before storing it as `locked_rev`.
Actually,  [`GitDatabase::resolve(&self, r: &GitReference)`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/utils.rs#L211) uses it and will return a `Oid` containing the long SHA.

This call to `GitDatabase::resolve()` for long SHA retrieval could be done in [`GitSource::new()`] as a replacement to `source_id.precise_git_oid()` call. But this requires to create the `GitDatabase` here, while it's only created in [`GitSource::block_until_ready()`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/source.rs#L254) so far. Not sure if it's a problem.

An alternative is to retrieval the long SHA in [`GitSource::block_until_ready()`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/source.rs#L254), just after `GitDatabase` creation. No need to replace `self.locked_rev`, but just to use the retrieved long SHA instead in the following [`match (self.locked_rev, db)`](https://github.com/rust-lang/cargo/blob/1f7059724151cc013fbc0b8b5875bee5a90614a1/src/cargo/sources/git/source.rs#L255)

**Comment by weihanglo** [comment]
> I think the root of the issue is that the conversion from short SHA to `git2::Oid` leads to a 20 bytes SHA completed with `0`s that cannot be found in the `git2::Repository` via call to `revparse_single()`.

Yeah. Totally agree on the root cause. 

There seems to be an “implicit assumption” that a git `SourceId` has a `precise` field of a full SHA. `cargo update` is an exception that makes use of `--precise` to have a transient `precise` value presenting a arbitrary git revision. It would eventually become a full SHA when the revision is resolved.

The proposed solutions aren't wrong, though I would like to see `locked_rev` to be a type that represent a "revision", so we could have either full SHA (oid), or an arbitrary git revision. That would also make the behavior aligned to the doc:


> <dt class="option-term" id="option-cargo-update---precise"><a class="option-anchor" href="#option-cargo-update---precise"></a><code>--precise</code> <em>precise</em></dt>
> <dd class="option-desc">When used with <em>spec</em>, allows you to specify a specific version number to set
> the package to. If the package comes from a git repository, this can be a git
> revision (such as a SHA hash or tag).</dd>

BTW, I accidentally have a working patch of this during code exploration. I may post a PR later but feel free to propose more better solutions :)

**Comment by linyihai** [comment]
> > One fix I can think of is comparing if the value of --precise is a hex string of 40/64 characters [here](https://github.com/rust-lang/cargo/blob/363a2d11320faf531f6aacd1ea067c6bc08343b9/src/cargo/ops/cargo_generate_lockfile.rs#L112), and give a nice error if not.
> 
> I will provide a PR to fix it based on this
> 
> > This is only a fix on the surface, if we find more commands have this kind of bug, we might want to push the fix down to lower-level.
> 
> This is worth a look, I will check the relevant code by the way, once there is any feasible plan I will make a corresponding plan
> 
> @rustbot claim

Sorry, I haven't started this work yet.  It's nice to see a better solution being proposed. :thumbsup:

**Comment by weihanglo** [comment]
Oops. I didn't realize this is claimed. Sorry for that, @linyihai 😔

Actually I was trying to provide guidance but ended up writing a fix

**Comment by linyihai** [comment]
> Oops. I didn't realize this is claimed. Sorry for that, @linyihai 😔
> 
> Actually I was trying to provide guidance but ended up writing a fix

The content to be changed is already very different from what I have been exposed to before,  So feel free to continue it.  Your PR is also a good guidance for me.

**Comment by JEnoch** [comment]
> BTW, I accidentally have a working patch of this during code exploration. I may post a PR later but feel free to propose more better solutions :)

You PR is more advanced than my proposal. I agree that having a `Revision` enum that can be a `GitReference` to be resolved when required is more accurately reflecting reality. Nice job! 😃
