### ISSUE TITLE
Not able to install cargo-modules

### ISSUE THREAD

**Issue by rupamharod1** [rust-lang/cargo#13190]
i am getting this error when trying to install cargo-modules
 
   
   Compiling cargo-platform v0.1.5
error[E0445]: private trait `FileIdToSyntax` in public interface
   --> /home/rupam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_hir_expand-0.0.190/src/files.rs:107:1
    |
86  | trait FileIdToSyntax: Copy {
    | -------------------------- `FileIdToSyntax` declared as private
...
107 | impl<FileId: FileIdToSyntax, T> InFileWrapper<FileId, T> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private trait

For more information about this error, try `rustc --explain E0445`.
error: could not compile `ra_ap_hir_expand` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-modules v0.13.1`, intermediate artifacts can be found at `/tmp/cargo-installZZPgGO`

**Comment by weihanglo** [comment]
[`cargo-modules`](https://crates.io/crates/cargo-modules) is a third-party plugin from the community. I don't see this is related to cargo. You might want to follow this issue <https://github.com/regexident/cargo-modules/issues/245>, or file an new issue on [their repo](https://github.com/regexident/cargo-modules).

Closing. Let us know if this is actually a bug in cargo itself.
