### ISSUE TITLE
Pass in options to rustc compilation command

### ISSUE THREAD

**Issue by benanders** [rust-lang/cargo#132]
I need to pass in a library search path to rustc with -L (looking for some C .dylibs) in order for my program to compile, and I can't find a way to do this with cargo. The ability to pass in options to the rustc command when compiling a file would be a very nice feature to have. Perhaps an option under a [[bin]] specifying additional compilation arguments, ie:

```
[package]

name = "test"
version = "0.1.0"
authors = ["example@gmail.com"]

[[bin]]

name = "test"
rustc_args = "-L/usr/local/lib"
```

Apologies if this is already implemented or there's another issue for it.

**Comment by joelthelion** [comment]
Could you give a pointer to the current solution, if any? It would be useful for people ending up here after a Google search.

**Comment by GravityScore** [comment]
It's been a while since I used Rust, but from memory there was no way to actually pass command line options to the linker. I ended up setting some environment variable (don't remember what it was), but I think this method has been superseded by the `rustc-link-search` feature in Cargo.
