### ISSUE TITLE
`cargo --list` shows a subcommand `miri` without actual implementation and description

### ISSUE THREAD

**Issue by yoonghm** [rust-lang/cargo#13229]
### Problem

`> cargo --list` show the following output:

```
    logout               Remove an API token from the registry locally
    metadata             Output the resolved dependencies of a package, the concrete used versions including overrides, in machine-readable format
    miri
    new                  Create a new cargo package at <path>
    owner                Manage the owners of a crate on the registry
    package              Assemble the local package into a distributable tarball
```

What is `miri`?

### Steps

Run `cargo --list`

### Possible Solution(s)

I could not find the word `miri` inside `github-com/rust-lang/cargo`

### Version

```text
cargo 1.74.1 (ecb9851af 2023-10-18)
release: 1.74.1
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Enterprise) [64-bit]
```

**Comment by weihanglo** [comment]
miri is a tool helping detect undefined behavior of your binaries. See <https://github.com/rust-lang/miri>. It is not shipped by default via rustup but a third party custom subcommands, so no description provided.

For displaying descriptions for custom subcommands, it is tracked here <https://github.com/rust-lang/cargo/issues/10662>.

**Comment by yoonghm** [comment]
Thanks
