### ISSUE TITLE
Cargo.lock file not cleaned

### ISSUE THREAD

**Issue by Phlosioneer** [rust-lang/cargo#1322]
Is it intentional that executing <code>cargo clean</code> doesn't remove Cargo.lock?

Because I just had a hell of a bug hunt today tracking down what was wrong in my piston build, and it turned out one of the dependencies upgraded from version 0.2.13 to 0.2.14, while the Cargo.lock file still specified 0.2.13. I ran <code>cargo clean</code> several times, with the expectation that it was fully cleaning all build information, but apparently not.

**Comment by Manishearth** [comment]
`cargo clean` is like `make clean`, it deletes the objdir and other build artifacts.


`Cargo.lock` is not a build artifact; and some projects even commit the lockfile to the source tree. You use `cargo update` to fetch new versions for all projects (or just delete the lockfile). `cargo update -p packagename` can be used to update a particular package.

**Comment by Phlosioneer** [comment]
Ah. Alright. Good to know, then - that wasn't obvious from the docs as far as I could tell.
