### ISSUE TITLE
Publishing a crate with patched dependencies

### ISSUE THREAD

**Issue by 3andne** [rust-lang/cargo#13222]
### Problem

Hi team,

I want to discuss a challenge that arises when working with forked dependencies in Rust, specifically regarding the publishing process on [crates.io](https://crates.io/).

I'm working on a fork of `rustls` which includes features won't be merged in the original `rustls` repository. Typically, end-users leverage `rustls` through higher-level crates such as `tokio-rustls` or `hyper-rustls`, which have `rustls` as a transitive dependency. While binary applications can substitute the original `rustls` with my fork using the `[patch]` section in `Cargo.toml`, this solution does not extend to crates intended for publication.

If such a crate depends on both `tokio-rustls` and my `rustls` fork, it can patch `rustls` locally; however, this patched crate cannot be published to `crates.io`. This creates a dilemma for crate maintainers: either avoid using the fork altogether or give up publishing their crate.

Maintaining separate forks of all direct dependencies (like `tokio-rustls`) as a workaround is not sustainable. It adds unnecessary maintenance burden and may not even cover all indirect dependencies that are unknown to us.

This situation presents a significant limitation for the adoption of forked versions of low-level libraries like `rustls`. I am reaching out to you for advice or suggestions on how we might address this issue. Are there any best practices or alternative approaches you could recommend that would allow the use of a forked `rustls` in a way that's compatible with publishing on `crates.io`?

Thank you for your time and assistance.

**Comment by weihanglo** [comment]
Thanks for the report.

To myself, `patch` is better to be controlled by the downstream consumers in a fully transparent way. crates.io and Cargo shouldn't worry about `[patch]` from dependencies.

This issue could somehow be resolved if cargo `[patch]` is able to patch packages from the same source, so that fork maintainers can publish to crates.io and tell their users to add a `[patch]` section. This would reduce the burden of maintaining all transitive dependencies, though the tracking issue <https://github.com/rust-lang/cargo/issues/9227> is still open and waiting for designs.

**Comment by weihanglo** [comment]
Just FYI that `[patch]` in dependencies' Cargo.toml will be [ignored](https://doc.rust-lang.org/1.75.0/cargo/reference/overriding-dependencies.html#the-patch-section) during builds.

> Cargo only looks at the patch settings in the `Cargo.toml` manifest at the root of the workspace. Patch settings defined in dependencies will be ignored.

<https://github.com/rust-lang/cargo/issues/9227#issuecomment-1697916963> sketched out the potential solution for make maintaining a fork easier, so going to close this in favor of #9227. Let us know if there is a reason this should remain open. Thank you.
