### ISSUE TITLE
`cargo fetch --offline` documentation directs user to use `cargo fetch --offline`

### ISSUE THREAD

**Issue by larswirzenius** [rust-lang/cargo#13232]
### Problem

The documentation for `cargo fetch --offline` (the manual page) includes the words "See the cargo-fetch(1) command to download dependencies before going offline."

This seems needlessly self-recursive. In fact, I'm not sure why `cargo fetch` offers an offline mode, but maybe it's useful in some case.

### Possible Solution(s)

Drop the sentence directing the user to `cargo fetch --offline` from the description of `cargo fetch --offline`. I realize this is boilerplate shared with all `cargo` subcommands that have an `--offline` option, and I don't know if the template system used allows a way to exclude parts for specific commands.

### Notes

This is really not a big issue. I'd be happy for you to ignore this until all other issues have been resolved.

### Version

```text
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Debian 12 (bookworm) [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report. The template language is [handlebars](https://crates.io/crates/handlebars), and it supports conditional templating.

For each command there should be a `command` variable available, so guess we can check if it is `fetch` and exclude the self-referential part.

<https://github.com/rust-lang/cargo/blob/ac6bbb33293d8d424c17ecdb42af3aac25fb7295/src/doc/man/cargo-fetch.md?plain=1#L2>

Though I am unsure if it is worth the complexity to have an additional condition there. Seems no harm to me to have self-referential, so tag `P-low` but feel free if pick up and fix it.

**Comment by linyihai** [comment]
@rustbot claim

it seems a another document issue, I'd like to take a shot.
