### ISSUE TITLE
Inconsistency in move semantics between `cargo build` and `rustc`

### ISSUE THREAD

**Issue by Toby222** [rust-lang/cargo#13240]
### Problem

It is possible to create a single-source-file project that compiles with cargo while being rejected with a use-after-move error by plain rustc.
It is my understanding that the behaviour between the two should be equivalent.

This was found in a discussion on whether the relevant field would or would not be moved, so I do not know what the correct behavior is.

### Steps

sample code:
```rust
#[derive(Debug)]
struct NewCount(pub usize);
fn main() {
    let mut count = NewCount(0);
    let mut counter = std::iter::from_fn(move || {
        count.0 += 1;
        Some(count.0)
    });

    for _ in 0..5 {
        dbg!(counter.next().unwrap());
    }
    dbg!(count);
}
```

1. Create empty cargo project (with cargo init)
2. Replace `main.rs` contents with above
3. Compile using `cargo build` -> works
4. Compile using `rustc ./src/main.rs` -> causes error

```

error[E0382]: use of moved value: `count`
  --> src/main.rs:13:5
   |
4  |     let mut count = NewCount(0);
   |         --------- move occurs because `count` has type `NewCount`, which does not implement the `Copy` trait
5  |     let mut counter = std::iter::from_fn(move || {
   |                                          ------- value moved into closure here
6  |         count.0 += 1;
   |         ------- variable moved due to use in closure
...
13 |     dbg!(count);
   |     ^^^^^^^^^^^ value used here after move
   |
   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.```
```

### Notes

I'm unsure if this is a bug with cargo or rustc (or even a bug at all?), but it is certainly unintuitive behaviour.

### Version

```text
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: NixOS 24.5.0 [64-bit]
```

**Comment by epage** [comment]
Note that with `cargo init`, the latest Edition is inserted into `Cargo.toml` but `rustc` defaults to 2015 Edition.  I wonder if this is an Edition difference.

**Comment by weihanglo** [comment]
I believe that is a feature of edition 2021 — [Disjoint capture in closures](https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html#disjoint-capture-in-closures).

**Comment by Toby222** [comment]
Changing the edition to 2015 indeed caused the error with Rust.
But if it's something that was introduced in edition 2021, why is `rustc` still causing the error?
