### ISSUE TITLE
Remove support for rustc plugins

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/cargo#13246]
### Problem

Cargo still supports building and depending on rustc plugins despite this having been removed from rustc a while ago.

### Proposed Solution

Remove support for building rustc plugins.

### Notes

Support was removed in https://github.com/rust-lang/rust/pull/116412

**Comment by ehuss** [comment]
I think it would be good, but I think we need to be a little cautious since I believe there are people abusing (or misunderstanding) the plugin setting to force building a dylib. We may need to do a deprecation notice for a little while.

**Comment by bjorn3** [comment]
Opened https://github.com/rust-lang/cargo/pull/13248 for a deprecation warning.
