### ISSUE TITLE
Make fixing build errors in packages easier

### ISSUE THREAD

**Issue by ntrrgc** [rust-lang/cargo#1327]
Currently, if I install a dependency with Cargo and it fails to build (e.g. because of recent changes in the compiler) I may edit the source code files in (`~/.cargo/registry`) to fix it and carry on, but this way the software keeps broken for the next user, who has to do the same thing.

It would be handy if cargo could generate a patch file for those changes, so the user can later clone the repo, apply the patch and send a pull request.

**Comment by alexcrichton** [comment]
This is actually precisely what [path overrides](http://doc.crates.io/guide.html#overriding-dependencies) are for. We highly recommend **not** editing code in `~/.cargo/registry`.
