### ISSUE TITLE
unable to : pip install openai in godaddy linux hosting.

### ISSUE THREAD

**Issue by tinamdar21** [rust-lang/cargo#13276]
unable to : pip install openai in godaddy linux hosting.
I am trying to install openai in godaddy linux terminal but I am getting error 
PermissionError: [Errno 13] Permission denied: 'cargo'
I find solution on internet they suggest to install rust 
I tried installation but I am unable to understand the step to install rust in godaddy hosting. 
screen shot is below. please check and help
![image](https://github.com/rust-lang/cargo/assets/17919682/b8484f34-052f-4565-8874-6c6c9b49cc0f)

**Comment by weihanglo** [comment]
Unfortunately, we are unable to provide support here for a specific Linux hosting service. You might want to check out which Linux distro GoDaddy hosting is using, and download Rust toolchain via the distro package manager or [from the official channels](https://rust-lang.github.io/rustup/installation/index.html).

This is nothing related to cargo itself, so closing.
