### ISSUE TITLE
Dependencies supplied via .cargo/path are required to be uploaded to crates.io

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/cargo#1328]
Reproduction script:
```
#! /bin/sh

cargo new foo
cargo new bar

cat >> foo/Cargo.toml <<EOF
[dependencies]
bar = "*"
EOF

mkdir -p foo/.cargo
cat >> foo/.cargo/config <<EOF
paths = [ "../bar" ]
EOF

cd foo
cargo build
```

Output:
```
 ./test.sh 
    Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `bar` found (required by `foo`)
location searched: registry
```

Expected: it to build using the local version supplied by paths

**Comment by steveklabnik** [comment]
This is intended behavior.

**Comment by jmesmon** [comment]
why is it intended behavior?

**Comment by steveklabnik** [comment]
I can't find @alexcrichton 's big post from the last time this was reported, but the basic idea is that if it's not published, this `Cargo.toml` is not actually build-able without your overrides.

**Comment by alexcrichton** [comment]
Yes we need to generate a `Cargo.lock` which requires that the actual packages are published and download-able. (sorry I can't seem to find my last post about this either...)

**Comment by jmesmon** [comment]
So it's a policy decision that `.cargo/config` can't be required for the build to work which causes this error?

You do realize this is trivially subvertable by creating empty packages on crates.io (or locally pointing Cargo.toml's path at a single dummy package).

I'm not seeing very much value in forbidding this.

**Comment by alexcrichton** [comment]
Path overrides are intended to *override* a previous decision of a package resolution. This requires the entire graph to be resolved *without* overrides and then apply them later, hence requiring the packages to exist before they are overridden.

This is why we have other forms of dependencies such as `git` and `path` to facilitate this form of development.

**Comment by jmesmon** [comment]
Ah, so it's a current implementation choice about how the dependency graph is formed? (I note that purely resolving dependencies with some overrides, outside the context of cargo, doesn't actually require the items that were overridden to exist, as no metadata from them is actually needed to form the dependency graph)

**Comment by alexcrichton** [comment]
Yes this is unfortunately just not what path overrides were designed for.

**Comment by vinipsmaker** [comment]
I noticed [rust-utp](https://crates.io/crates/utp) work around this somehow. Can anyone enlighten me how this is done?

**Comment by vinipsmaker** [comment]
Never mind, I just noticed [the rust-utp's `with_read_timeout` subcrate path-based isn't published/tagged in any release](https://github.com/meqif/rust-utp/commit/bec0ca8a2ed84e4d8c12793ff22e256ae96f2090).
