### ISSUE TITLE
Provide a way to figure out why a specific dependency feature is enabled during build

### ISSUE THREAD

**Issue by SludgePhD** [rust-lang/cargo#13289]
### Problem

I'm currently trying to disable a feature in a dependency, but Cargo clearly still enables it (the items it gates are still available; there is no other way Cargo communicates this). I've checked all other crates in my dependency graph that depend on that crate, and none of them seem to enable that feature.

There does not seem to be any way, or at least any documented way, or any third-party subcommand, that can help debug this. This is *incredibly* frustrating.

**Comment by epage** [comment]
Try running `cargo tree -e features -i <dep>`.

If not, rust-lang/rfcs#3553 should have you covered

**Comment by SludgePhD** [comment]
Thanks, that helped. Is there any way to make this more visible perhaps? I searched the web for a bunch of related queries and `-e features` has never come up.

**Comment by epage** [comment]
#12903 expanded the [troubleshooting](https://doc.rust-lang.org/cargo/reference/resolver.html#troubleshooting) but somehow we overlooked "why is this feature enabled" and would be a good topic to add.

**Comment by linyihai** [comment]
@rustbot claim

> Try running cargo tree -e features -i <dep>.

This is a new world for me, too.
