### ISSUE TITLE
Different behavior in features resolution during testing for workspace

### ISSUE THREAD

**Issue by artemyarulin** [rust-lang/cargo#13297]
### Problem

Different behavior in features resolution during testing between `cargo test` on workspace level and `cargo test` in every workspace member.

Repo with minimal example which reproduce the issue https://github.com/artemyarulin/cargo-test-feature-bug/tree/main

Workspace contains of two members - `a` and `b`. 

Member `a` contains an optional feature `foo` and when tested with this feature on - panics. By default `foo` is not enabled so `cd a && cargo test` succeeds as test is skipped.

Member `b` references `a` with feature `foo` enabled. Although `cd b && cargo test` succeed as when tests are run - tests of dependencies are skipped.

But if `cargo test` is run on workspace level then tests fails and `a` test runs which is not expected.

### Version

```text
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.1.2 (sys:0.4.68+curl-8.4.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 14.1.1 [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the reproducer.

As I understand it, the behavior is so-called [feature unification](https://doc.rust-lang.org/1.75.0/cargo/reference/features.html#feature-unification). Feature unification is a workspace-level thing — you only get one feature unification result when running a single `cargo build` invocation.

For this case, both `a` and `b` are built and tested with `a/foo` enabled when building all default workspace members (`cargo build`). And as you've observeed, either `cd`ing to the member directory or running `cargo build --package <member>` will narrow the scope of feature unification to specific members, so the feature unification result is different.

See also ["Features"](https://doc.rust-lang.org/1.75.0/cargo/reference/resolver.html#features) paragraph in Dependency Resolution chapter: 

> When building multiple packages in a workspace (such as with `--workspace` or multiple `-p` flags), the features of the dependencies of all of those packages are unified. If you have a circumstance where you want to avoid that unification for different workspace members, you will need to build them via separate `cargo` invocations.

**Comment by artemyarulin** [comment]
Got that, thank you for the explanation
