### ISSUE TITLE
Missing “Generated” status for `cargo rustdoc --output-format json`

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#13303]
### Problem

For HTML format, `cargo rustdoc` would output a “Generated” status showing the file path

```
 Documenting foo v0.1.0 (/home/rust/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
   Generated /home/rust/foo/target/doc/foo/index.html
```

However, for `--output-format json` you cannot find the “Generated” status.

### Steps

1. `cargo new foo`
2. `cd foo`
3. `cargo +nightly rustdoc -Zunstable-options --output-format json`

### Possible Solution(s)

Expect there is a corresponding "Generated" status for JSON format.

For `--open` different formats are handled, but for "Generated" they aren't.

https://github.com/rust-lang/cargo/blob/350098d5ef2a93e62679c061972457eb45ef5a64/src/cargo/ops/cargo_doc.rs#L64-L73

https://github.com/rust-lang/cargo/blob/350098d5ef2a93e62679c061972457eb45ef5a64/src/cargo/ops/cargo_doc.rs#L91-L94

### Version

```text
cargo 1.77.0-nightly (84976cd69 2024-01-12)
release: 1.77.0-nightly
commit-hash: 84976cd699f4aea56cb3a90ce3eedeed9e20d5a5
commit-date: 2024-01-1
```

**Comment by kanru** [comment]
May I take this?

**Comment by weihanglo** [comment]
@kanru yeah sure. You can use [`@rustbot claim`](https://doc.crates.io/contrib/process/index.html?highlight=claim#issue-assignment) to assign this issue to yourself.

Feel free to reach us out on [Zulip](https://rust-lang.zulipchat.com/#streams/246057/t-cargo) or [office hour](https://github.com/rust-lang/cargo/wiki/Office-Hours).
