### ISSUE TITLE
`cargo build` shouldn't access the network

### ISSUE THREAD

**Issue by wizeman** [rust-lang/cargo#1330]
... at least, not unless it's needed.

I have a project that builds a binary with dependencies from `crates.io`. The project has an updated `Cargo.lock` file.

I need to package this project, and the way any sane packaging system (such as Debian's, Gentoo's or NixOS's) works is that downloads are not allowed when building / compiling.

What I need to do is download the project's dependencies separately and then provide them to `cargo` when building.

I know about `cargo fetch` but it's not adequate for this purpose, because all it does is create an idiosyncratic directory structure in `$CARGO_HOME`, which 1) is not appropriate to save inside some package or tarball (it contains superfluous data such as the registry), and 2) is hard to reproduce manually as part of building a package without having network access.

So the way I'm doing this is downloading the dependencies manually, e.g. `wget https://crates.io/api/v1/crates/time/0.1.12/download`, extracting the tarballs and then, just before building the project, creating a `.cargo/config` file with contents such as:
```
paths = [ "/tmp/deps/abort_on_panic-0.0.4", "/tmp/deps/time-0.1.12", ... ]
```

I did this in the hopes that the manually downloaded dependencies override the registry dependencies specified in `Cargo.toml`, so that `cargo` doesn't need to download them. I made sure that all the manually downloaded dependencies' versions exactly match the ones in the `Cargo.lock` file.

This way, even if `$CARGO_HOME` is empty, it shouldn't be necessary to download anything, because all the dependencies' sources are already available in the overriden paths specified in `.cargo/config`.

However, even when I do this the `cargo build` command still tries to update the registry:
```
$ cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
An unknown error occurred

To learn more, run the command again with --verbose.
```

Do you agree with my reasoning or is there a better way to manually provide the source code (or compiled library!) of `crates.io` dependencies to `cargo` so that building a package does not try to access the network?

**Comment by bombless** [comment]
I think you should prepare all dependencies of your project, then use an separate Cargo.toml file to change dependencies as local library, and pass the --manifest-file option to `cargo build`.

But I think the "An unknown error occurred" message should be improved, I may try to fix that.

**Comment by alexcrichton** [comment]
The current method of achieving this functionality is indeed `cargo fetch` followed by `cargo build` (bugs like #1329 notwithstanding).

Path overrides were not intended for this purpose and the reason that you're still hitting the registry is that the dependencies still need to be located and resolved from the registry to generate the lockfile. The path overrides only come into effect *after* the lockfile has been created.

I'd be quite interested to learn about your woes with `cargo fetch` though! Would you be ok opening a new issue describing what you'd like to see out of `cargo fetch` and why it's not adequate today?

**Comment by wizeman** [comment]
On Sat, Feb 21, 2015 at 7:15 AM, Alex Crichton <notifications@github.com>
wrote:

> Path overrides were not intended for this purpose and the reason that
> you're still hitting the registry is that the dependencies still need to be
> located and resolved from the registry to generate the lockfile. The path
> overrides only come into effect *after* the lockfile has been created.
>

I don't understand. As I mentioned, this project already had an updated
`Cargo.lock` file. So why does `cargo build` still need to download the
registry?

I'd be quite interested to learn about your woes with cargo fetch though!
> Would you be ok opening a new issue describing what you'd like to see out
> of cargo fetch and why it's not adequate today?
>

Ok, will do. Thanks!

**Comment by alexcrichton** [comment]
> So why does `cargo build` still need to download the
registry?

The download URL (where to look for on `crates.io` for the download) is located as a config file in the index which needs to be downloaded.

**Comment by wizeman** [comment]
On Mon, Feb 23, 2015 at 8:38 AM, Alex Crichton <notifications@github.com>
wrote:

> The download URL (where to look for on crates.io for the download) is
> located as a config file in the index which needs to be downloaded.
>
>
But if the `Cargo.lock` file is already created (and updated), and all the
dependencies have been overridden in `.cargo/config`, then cargo doesn't
need the download URLs, right? Since all the dependencies are available in
the local system.
Or am I missing something?

**Comment by alexcrichton** [comment]
The `Cargo.lock` file does not contain all metadata about a package. Information such as platform-specific dependencies, features, etc, is only stored in the index. This means that even with a `Cargo.lock` the index is needed to fully perform resolution.

**Comment by wizeman** [comment]
>
> The Cargo.lock file does not contain all metadata about a package.
> Information such as platform-specific dependencies, features, etc, is only
> stored in the index. This means that even with a Cargo.lock the index is
> needed to fully perform resolution.
>

What do you mean, it's only stored in the index?

All that information should be in the sources of the dependencies, inside
~/.cargo/registry/src/*
The sources should be enough for `cargo build`, otherwise it wouldn't be
possible for `Cargo.toml` to point to non-registry dependencies, right?

I just don't see why the registry index has to be consulted during `cargo
build` when all the sources have already been fetched and all information
is available locally (*outside* the local copy of the index)...

@alexcrichton I'm at my wit's end trying to package programs that use cargo.

Is there any chance that the output of `cargo fetch` (possibly with some
post-processing) can be made deterministic (meaning, the output will be the
same if the current source code being compiled is the same), and that if I
pass this deterministic output of `cargo fetch` to `cargo build`, then the
latter will not try to download anything from the network?

Because if not, I don't think `cargo fetch` can be used when building
cargoed rust packages in NixOS... (and without `cargo fetch`, it will be a
nightmare to use any other solution).

**Comment by alexcrichton** [comment]
Sorry but I think I'm a little lost here. Are you running `cargo fetch` and then `cargo build` and the build step still accesses the network? If not, could you remind me what this is requesting?

**Comment by khurshid-alam** [comment]
Yes `cargo build` still try to access network although it doesn't download anything as `cargo fetch` has already been performed. Why does `cargo build` need network access then?

This makes it impassible to compile anything on debian (other than on local machine) even with bundled dependencies.

**Comment by steveklabnik** [comment]
Can you help reproduce this behavior somehow?
