### ISSUE TITLE
(optionally) save logs of stdout and stderr

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#1331]
Related to #985 and #1106.

It would be nice to save logs of the output of rustc and build scripts. Just dumping a log file in the target dir or have a new dir to put the logs in, either way would be fine. This could always happen or be specified with a flag to `cargo build`. I expect this to be useful for debugging and also (my use case) when replacing rustc with a tool and you want to see its output, even when it is successful.

**Comment by FlashYoshi** [comment]
According to #985 output should be located in `target/build/$crate-$hash/output`. Saving them by default doesn't seem very user-friendly to me. Most of the time you can find the info you need in the printed logs thus users would actually be spammed by these log files they don't need. A special flag is a way better idea. If you are on a unix system you could ofcourse just use output redirection.

**Comment by alexcrichton** [comment]
Ah yeah Cargo actually already does this for build scripts (in the places @FlashYoshi mentions) and otherwise Cargo no longer captures rustc/rustdoc output ever so it's always printed. As a result, I'm gonna close this.
