### ISSUE TITLE
`cargo run` error: package(s) `...` not found in workspace

### ISSUE THREAD

**Issue by kzhui125** [rust-lang/cargo#13310]
### Problem

With `cargo run --package time-core:10.0.0 --bin time-core ` in workspace folder, I get error `error: package(s) ... not found in workspace`.

<img width="633" alt="image" src="https://github.com/rust-lang/cargo/assets/11925432/c5beb398-301b-421c-b998-0e55b255e2c2">

[workspace_0117.zip](https://github.com/rust-lang/cargo/files/13960582/workspace_0117.zip)

```
cargo run --package time-core:10.0.0 --bin time-core 
```

expected: no error.

### Version

```text
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0 (sys:0.4.68+curl-8.4.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 14.2.1 [64-bit]
```

**Comment by kzhui125** [comment]
If cargo don't support the same name for `my crate` and `dependency crate`. The error message should change and vscode rust extension should give error.

If cargo support the same name for  `my crate` and `dependency crate`.  cargo run should work.

What if `my crate` and `dependency crate` have the same name and same version?

**Comment by hi-rustin** [comment]
It seems to work if we don't use a package name. For example:
```console
❯ cargo run                           
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/time-core`
Hello world
```

**Comment by kzhui125** [comment]
VSCode extension will use `cargo run --package time-core:10.0.0 --bin time-core`, and it will fail.

**Comment by epage** [comment]
It looks like we are passing the `spec` unchanged as a package name.  In my quick glance, not seeing why `cargo check` translates the spec into a package id but `cargo run` doesn't.  `cargo run` does do somethings differently.

**Comment by hi-rustin** [comment]
@rustbot claim

Let me try to fix it.

**Comment by hi-rustin** [comment]
After some debugging:

I think the problem is here:
1. We store the spec as the name in this function: https://github.com/hi-rustin/cargo/blob/aa6444734d0049b3534fa1ae623c55dfbef63412/src/cargo/ops/cargo_compile/packages.rs#L201
2. But we use it here to match only the name of the package: https://github.com/hi-rustin/cargo/blob/aa6444734d0049b3534fa1ae623c55dfbef63412/src/cargo/ops/cargo_compile/packages.rs#L128

So `foo@0.5.0` does not match with `foo`. So it said there is no `foo@0.5.0` in the workspace.

**Comment by CSEwkm** [comment]
Try running `cargo build` first
