### ISSUE TITLE
add --dry-run to `cargo publish`

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/cargo#1332]
Running `cargo package` reported no errors, but running `cargo publish` warns:

> all dependencies must come from the same source

The docs seems to indicate that `cargo package` is to be used as a "pre-flight" check of the package. I would have expected `cargo publish` to only be able to fail for reasons that involve communicating with crates.io proper.

**Comment by alexcrichton** [comment]
I initially agreed with this, but I think I may be convincing myself of the opposite now. In terms of future expansion, we could have `cargo package` output anything from a tarball to an rpm, for example. We could also in theory provide fun options for `cargo package` like `--include-dependencies` or other minutia related to distributing source code.

Technically the restriction that all dependencies come from the same source is only imposed by the registry itself, not the packaging step. I suppose what I'm getting at is that if we only ever use `cargo package` to generate a `.crate` to upload then this makes sense, but if we expand beyond that it may not end up making sense.

**Comment by shepmaster** [comment]
I think your explanation makes sense, so maybe this becomes a feature request for a `--dry-run` switch for `cargo publish` then. That way, we can check for specific issues for a repository (and a parallel `cargo rpm --dry-run` in the future, as you say).

**Comment by alexcrichton** [comment]
Updated title as I think it'd be a nice piece to have as well!

**Comment by JustAPerson** [comment]
So as tagged, this is a pretty simple thing to take care. I've gone ahead and patched `src/bin/publish.rs` and `src/cargo/ops/registry.rs`, but I just want some input on what the output should look like.

Here's a sample of what it looks like currently
![image](http://i.imgur.com/3AZcZHS.png)

I'm not sure if `Config::shell().status()` is the correct way to output here. Additionally, should the `--no-verify` and `--dry-run` flags be mutually exclusive (i.e. error if both are supplied)? What should the messages look like?

With some feedback on what the cargo developers would like here, I'll fix things up and open a pull request.

**Comment by alexcrichton** [comment]
@JustAPerson that looks pretty good to me! Perhaps it could actually print "Uploading"... as usual but just print a warning status right after saying "Aborting upload due to dry run" or something like that.
