### ISSUE TITLE
cargo build`--config 'lib.crate-type = ...'` not impacting output

### ISSUE THREAD

**Issue by FreeMasen** [rust-lang/cargo#13323]
### Problem

When attempting to adjust the configuration value of `lib.crate-type` passing the `--config` argument to cargo doesn't impact the output of a build.

### Steps

1. In a library project attempt to run `cargo build --config 'lib.crate-type = ["staticlib"]'`
2. Check the contents of the target directory, the file produced will be a `.rlib` file and not an `.a` file

### Notes

I've created a repo/lib project as an example.

https://github.com/FreeMasen/config-crate-type-override

The github actions here perform a series of builds with different values provided by `--config`, after the build an `ls ./target/release` is performed to evaluate what was generated. I would expect the output file extention to change from `.rlib` to `.so` to `.a` depending on what value is provided however all outputs are `.rlib`

### Version

```text
cargo 1.75.0 (1d8b05cdd 2023-11-20)
```

**Comment by epage** [comment]
`--config` is for modifying the Cargo's [configuration](https://doc.rust-lang.org/cargo/reference/config.html) while `lib.crate-type` is a field in the [manifest](https://doc.rust-lang.org/cargo/reference/manifest.html).

You can use [`cargo rustc --crate-type`](https://doc.rust-lang.org/cargo/commands/cargo-rustc.html#compilation-options) to change it on the fly.

**Comment by FreeMasen** [comment]
Ok, thank you for the context I didn't realize that it wasn't overriding the `Cargo.toml` but the `.cargo/config.toml` (and similar). I will close this issue.
