### ISSUE TITLE
Default timeout is too short.

### ISSUE THREAD

**Issue by nwin** [rust-lang/cargo#1333]
The default timeout if [30 s](https://github.com/carllerche/curl-rust/blob/master/src/http/handle.rs#L44-L47). The upload limit of crates.io is 10 MB. Assuming an internet connection with about 1mbit/s, it would roughly take 60 s to download a package. That does not fit.

Actually I do not even see how much sense a timeout makes, if the download works fine. Cargo should probably only use a timeout for establishing the connection but not for the download itself. 

In principle I would even say this should fixed in rust-curl. The default timeout should be set to 0.

**Comment by alexcrichton** [comment]
I agree that the limit should probably be raised.
