### ISSUE TITLE
"PROFILE" environment variable is still buggy in build script

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#1335]
After #1288, running `cargo build` sets `PROFILE` to `compile`, and running `cargo bench` sets `PROFILE` to `bench`.
However running `cargo test` sets `PROFILE` to `compile` instead of `test`.

Also, according to the docs the profile when you run `cargo build` is supported to be named `dev` and not `compile`.

**Comment by alexcrichton** [comment]
Hm upon reflection I'm not sure that we actually want to expose this kind of profile. If the output can changed based on `PROFILE`, then we need to re-run the build script each time the `PROFILE` changes. This means that a library would have to *always* be recompiled between `cargo build` and `cargo test` which seems unfortunate.

I do think we may want to rename `compile` to `dev`, but I think we may want to actually limit the profile environment variable to either `dev` or `release` instead of leaking through the other profiles.

**Comment by tomaka** [comment]
My use case is this one:

We have a library named `gl_generator` which generates Rust code.

In order to test it, we have another library named `gl` whose build script is basically this (simplified):

```rust
gl_generator::generate("regular_output.rs");

if env("PROFILE") == "test" {
    gl_generator::generate("test1.rs");
    gl_generator::generate("test2.rs");
    gl_generator::generate("test3.rs");
    gl_generator::generate("test4.rs");
    ....
}
```

Then the `lib.rs` file of `gl` includes `regular_output.rs`, while `gl`'s tests include the `testX.rs` files.

**Comment by alexcrichton** [comment]
Unfortunately though we don't have a concept of "output for tests" and "output for normal compiles". Whenever a build script runs it re-triggers compilation of the library itself and this means that `cargo test` will *always* rebuild the library if it was previously built with `cargo build` (which is currently a showstopper).

Would it be possible to have `gl_generator` be a dev-dependency and write an integration test which executes those commands?

**Comment by tomaka** [comment]
> Would it be possible to have gl_generator be a dev-dependency and write an integration test which executes those commands?

The `gl_generator::generate` function generates Rust code (and *a lot* of Rust code), so in order to test if it works correctly we simply compile this code and try using it.

**Comment by alexcrichton** [comment]
> The gl_generator::generate function generates Rust code (and a lot of Rust code), so in order to test if it works correctly we simply compile this code and try using it.

Yeah I was thinking as part of the test you could run the compiler as well.

> We could however create another library named gl_generator_test just for this purpose.

I'd probably opt for the integration-test-that-runs-the-compiler first, but I can see where neither is necessarily the best :(

**Comment by alexcrichton** [comment]
Hm, another possible option would be to add "build scripts for tests" which is a separate script with roughly the same set of inputs that gets run before tests are built. That way you could build C libs just for testing and also cover a use case like this perhaps.

(just an idea)

**Comment by alexcrichton** [comment]
After finishing #1441 I've concluded that the current behavior is probably the best way to go as it rationalizes well with our current directory layout. I think the best way to tackle this would be to add a build script for just binaries or just tests, for example, but that I think is beyond the scope of this issue and isn't something we want to pursue at this time.
