### ISSUE TITLE
`cargo install` thinks `$CARGO_HOME/bin` isn't in PATH, but it is (Windows)

### ISSUE THREAD

**Issue by CAD97** [rust-lang/cargo#13378]
### Problem

When `cargo install`ing tools, I'm getting the warning

```text
warning: be sure to add `\\?\D:\.rust\cargo\bin` to your PATH to be able to run the installed binaries
```

despite `D:\.rust\cargo\bin` being in my path. Note that the former is an extended-length path (`\\?\`) but the latter isn't.

### Steps

0. have `$CARGO_HOME/bin` in PATH as a non-canonicalized path
1. `cargo install` some package
2. observe output

### Possible Solution(s)

- Canonicalize paths from PATH before comparing against bin dst
- Compare against both bin dst and bin dst without a `\\?` prefix

### Notes

Relevant code: https://github.com/rust-lang/cargo/blob/0f37cfb1f5da7e60ba60fd896751d8142882c582/src/cargo/ops/cargo_install.rs#L748-L761

`dst` is an extended-length path because (presumably, I didn't check) it's been canonicalized.

### Version

```text
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: x86_64-pc-windows-msvc
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:Schannel)
os: Windows 10.0.22631 (Windows 11 Education) [64-bit]
```

**Comment by epage** [comment]
Huh, generally paths in cargo should not be canonicalized.

**Comment by ChrisDenton** [comment]
If you can't skip canonicalization then it might be better to use the `same-file` crate. The solutions listed here do come with some gotchas.

> Canonicalize paths from PATH before comparing against bin dst

Canonicalizing would be ok when it works, though it can fail. A more robust way is to open both directories and directly use `GetFinalPathNameByHandleW` with `VOLUME_NAME_NT` and compare the strings. This won't fail if the volume doesn't integrate (some RAM drives and some third-party VM shared volumes are like this).

> Compare against both bin dst and bin dst without a `\\?` prefix

That doesn't quite work for UNC paths (e.g. `\\?\UNC\server\cargo\bin` maps to `\\server\cargo\bin`). You'd need a more robust comparison, though if both paths are absolute then this is simpler.

**Comment by epage** [comment]
imo the first step of investigation is determining why the path is canonicalized with a UNC prefix.  For example, are we using `canonicalize` rather than joining with `config.cwd()`?

For an example of how paths should be made, see
https://github.com/rust-lang/cargo/blob/master/src/cargo/util/command_prelude.rs#L967-L970

**Comment by CAD97** [comment]
cargo-install is doing

https://github.com/rust-lang/cargo/blob/0f37cfb1f5da7e60ba60fd896751d8142882c582/src/cargo/ops/cargo_install.rs#L622-L623

**Comment by ehuss** [comment]
I'm not able to reproduce this.

Can you clarify, do you have CARGO_HOME set? If so, what is its value?
Did you set CARGO_HOME when installing rustup? If so, how?
Can you share the value of your PATH?
Which shell are you using when you run `cargo install`? Is it powershell? Git bash?

**Comment by CAD97** [comment]
Hmm, I just tried reproducing again, and it didn't. As such, closing. It was probably caused by something in the nushell pipeline.

**Comment by CAD97** [comment]
aha: the warning is coming out of `cargo install-update`, not `cargo install`.

**Comment by CAD97** [comment]
Specifically, I believe `cargo install-update` is providing a normalized path to the `--root <DIR>` argument, and that's why cargo is seeing an extended-length path there. I believe this is probably a cargo-update issue, not a cargo issue. https://github.com/nabijaczleweli/cargo-update/issues/252

**Comment by stasbalazuk** [comment]
cargo search cargo-install-update
