### ISSUE TITLE
Include location of workspace manifest in error loading workspace

### ISSUE THREAD

**Issue by fawq** [rust-lang/cargo#13394]
### Problem

I've tried to create new project inside project which was previously created by cargo init and removed. Now when I want to create new project inside, I've got an error that there is a missing Cargo.toml in parent directory, but parent directory doesn't need to have Cargo.toml because it should be simple directory contains all rust projects.

Steps:
1. Create directory e.g. "/home/ubuntu/Projects/Rust/"
2. Go inside this directory and type `cargo init`
3. Change mind and remove all files `rm -r *`
4. Create new project inside this directory e.g. `cargo new test_rust_wsl`
5. New directory is created "/home/ubuntu/Projects/Rust/test_rust_wsl"
6. Go inside new directory and try build `cargo build`

Get the error: 
> error: failed to load manifest for workspace member /home/ubuntu/Projects/Rust
> 
> Caused by:
>   failed to read /home/ubuntu/Projects/Rust/Cargo.toml
> 
> Caused by:
>   No such file or directory (os error 2)

### Version

```text
cargo 1.75.0 (1d8b05cdd 2023-11-20)
release: 1.75.0
commit-hash: 1d8b05cdd1287c64467306cf3ca2c8ac60c11eb0
commit-date: 2023-11-20
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by ehuss** [comment]
Hm, it seems like there is a possible step missing from the reproduction. Can you check if you have a `Cargo.toml` located in any parent directory of `/home/ubuntu/Projects/Rust`? Or perhaps there is a workspace table in `/home/ubuntu/Projects/Rust/test_rust_wsl/Cargo.toml`?

**Comment by fawq** [comment]
![image](https://github.com/rust-lang/cargo/assets/30419862/c719c7c9-8246-4425-a57e-da370340510a)
![image](https://github.com/rust-lang/cargo/assets/30419862/97c4d1ef-cb04-4fdd-9c0b-68a5b4131d11)
As you can see, there is no other Cargo.toml in a whole directory (except the one which I need and cannot build)

**Comment by ehuss** [comment]
Can you check the parents of the `Projects` directory, such as `/home/ubuntu`, `/home`, or `/`?  Cargo searches all ancestor directories for a `Cargo.toml`.

Probably the easiest thing to do is to copy the output of `CARGO_LOG=trace cargo build`

**Comment by fawq** [comment]
Thanks for help, it was created in home directory. The question is why it was not detected or printed by inside project? Is it possible to get from `cargo build` more information about "parent workspace"? Or only `CARGO_LOG=trace cargo build` can found the issue? Nevertheless, Issue can be closed, I think.

**Comment by ehuss** [comment]
For now, `CARGO_LOG` seems to be the only way to debug this particular issue.

I think it would be good to keep this open as a suggestion to improve the error message so that it tells you where the workspace manifest is located.

**Comment by weihanglo** [comment]
I wonder if this happened because  `cargo new` adds the new package to the workspace found without any notice (since https://github.com/rust-lang/cargo/pull/12779).

https://github.com/rust-lang/cargo/pull/13391 may  make this kind of issues less frequent. Cargo might also print a note when workspace inheritance happens.

**Comment by tusharxoxoxo** [comment]
is this the cause of this issue??
At some point, you might have accidentally initialized a Rust project (with cargo new) from the /home directory, making that entire directory the project root.

**Comment by tusharxoxoxo** [comment]
I think i kind of able to reproduce it, but i am getting slightly different errors compared to what is mentioned above, i created a copy of my cargo.toml in my home directory for this

![image](https://github.com/rust-lang/cargo/assets/79051850/35353fa9-8d57-413a-a21a-f6195e84b7b1)

**Comment by ehuss** [comment]
@tusharxoxoxo To reproduce:

Create a `Cargo.toml` with the contents:

```toml
[workspace]
members = ["foo", "bar"]
```

Then:
* `cargo new --lib bar`
* `cd bar`
* `cargo build`

The last step should show: 
```
error: failed to load manifest for workspace member `/path/to/foo`
```

Notice that the error does not display the path to the workspace `Cargo.toml` (which is where the problem is, because the `members` field points to a directory "foo" that does not exist).
