### ISSUE TITLE
Error - RPC failed

### ISSUE THREAD

**Issue by hanusek** [rust-lang/cargo#13395]
### Problem

I have a problem with the cargo. 

```
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
```

### Steps

```
$ docker pull energotest/ubuntu-18-04-arm
$ docker run -it --network host --rm -v $(pwd):$(pwd) -w $(pwd) -t energotest/ubuntu-18-04-arm
$ cargo +1.66.0 b --release --target=arm-unknown-linux-gnueabihf
    Updating crates.io index
error: Unable to update registry `crates-io`
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
  --- stderr
  error: RPC failed; curl 18 transfer closed with outstanding read data remaining
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
ERROR: Job failed: exit code 1
```

### Notes
Giltab CI / Docker container.

### Version

```text
$ cargo version --verbose
cargo 1.66.0 (d65d197ad 2022-11-15)
release: 1.66.0
commit-hash: d65d197ad5c6c09234369f219f943e291d4f04b9
commit-date: 2022-11-15
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 18.4.0 [64-bit]
```

**Comment by weihanglo** [comment]
>   ```
>   process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
>   ```

It seems that you've configured [`net.git-fetch-with-cli`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#netgit-fetch-with-cli), so you're already used `git` CLI.

See <https://github.com/rust-lang/cargo/issues/8499#issuecomment-661093739>. It might be some network issue on your side. 

* Could you install the latest Rust (1.75.0) and try again?
* Could you try if you can run the `git` command shown in the error message in the docker container?

**Comment by weihanglo** [comment]
I'm going to close due to inactivity. Feel free to reopen if you have a chance to help investigate the issue.
