### ISSUE TITLE
Print a note when `cargo new` is editing `workspace.members`

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#13403]
### Problem

Starting from #12779, `cargo new` automatically adds the new package to `workspace.members` when invoked inside from a directory of a workspace. This is a great feature, however sometimes a bit less noticeable.

### Proposed Solution

Print a notice when a workspace is found and cargo new are editing `workspace.members` of it. For example,

```diff
      Creating binary (application) `foo` package
+ note: adding `foo` as a workspace member of workspace `bar` at `/home/projects/bar`
  note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
```

### Notes

version

```
cargo 1.77.0-beta.1 (7bb7b5395 2024-01-20)
release: 1.77.0-beta.1
commit-hash: 7bb7b539558dc88bea44cee4168b6269bf8177b0
commit-date: 2024-01-20
```

**Comment by weihanglo** [comment]
cc @linyihai 

This may have conflicted with #13391, or you can take this after #13391 merges :)

**Comment by linyihai** [comment]
@rustbot claim

Thank you for ping me.  I'd like to addressed this after https://github.com/rust-lang/cargo/pull/13391

**Comment by epage** [comment]
I wonder if this could work as a status

```
Adding foo as member of workspace /path
```
