### ISSUE TITLE
Cargo build giving checksum mismatch error

### ISSUE THREAD

**Issue by neetabisht** [rust-lang/cargo#13414]
### Problem

Hi All,
I have cargo.toml file present in windows 11 machine where trying to use rumqtt 0.31.0 version.

![cargo-toml](https://github.com/rust-lang/cargo/assets/105039104/4ea663a5-0887-44e2-8afd-a227cd96fbc8)
But when i am running "cargo build" cli, I'm getting below error:
```
**$ cargo build
    Updating crates.io index
  Downloaded autocfg v0.1.8
error: failed to download replaced source registry `crates-io`

Caused by:
  failed to verify the checksum of `autocfg v0.1.8`**
```
can anyone please help me with this error.

### Steps

steps:
1. Install rust
2. Install gitbash to run all commands.
3. Modify the cargo.toml file as per above screen shot.
4. execute "cargo build" cli.

**Comment by neetabisht** [comment]
$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.75.0 (82e1608df 2023-12-21)`

INNEBIS1@IN-L-7402183 MINGW64 /d/eventgrid_project/rust_project (master)
$

**Comment by weihanglo** [comment]
It seems you'v configured [source replacement](https://doc.rust-lang.org/nightly/cargo/reference/source-replacement.html) (a.k.a. mirrors). Check your `.cargo/config.toml`. Comment out  `[source]` table and see if the original crates.io registry has the same issue.

**Comment by Eh2406** [comment]
If you look in your cargo.lock for the section about autocfg v0.1.8, what is there?

**Comment by arlosi** [comment]
Cargo's error for this case will indicate source replacement even when it's not explicitly configured due to the built-in sparse replacement of crates.io, so it's possible that no source replacement is configured here. I just opened #13433 to improve the errors.

Can you check if `~/.cargo/registry/cache/index.crates.io-6f17d22bba15001f/autocfg-0.1.8.crate` exists? That's where it will be downloaded by default if a source replacement is not configured.

Another way to check (if you have nightly available) is to run `cargo +nightly -Zunstable-options config get source`. If it gives you an error, then no source replacement is configured.

**Comment by neetabisht** [comment]
~/.cargo/registry/cache/index.crates.io-6f17d22bba15001f/autocfg-0.1.8.crate  it is not created for me.

**Comment by Eh2406** [comment]
The error you're getting "failed to verify the checksum of `autocfg v0.1.8`**" is being generated [here](https://github.com/rust-lang/cargo/blob/30addeaa9028b28b533f29636a9705c4ac834afe/src/cargo/sources/registry/download.rs#L126). That is to say when cargo attempts to download `autocfg v0.1.8`, the file contents do not hash to "0dde43e75fd43e8a1bf86103336bc699aa8d17ad1be60c76c0bdfd4828e19b78"

**Comment by weihanglo** [comment]
[`0dde43e75fd43e8a1bf86103336bc699aa8d17ad1be60c76c0bdfd4828e19b78`](https://github.com/rust-lang/crates.io-index/blob/master/au/to/autocfg#L13) is the correct checksum for `autocfg@0.1.8` on crates.io. So perhaps you've downloaded the `.crate` file from a different location, or the `.crate` file is corrupted. In the latter case, you can remove `~/.cargo/registry/cache/` and do `cargo fetch` again to re-download.

**Comment by weihanglo** [comment]
I'm going to close due to inactivity. Feel free to reopen if you have run possible workarounds above and had new findings to share.
