### ISSUE TITLE
`cargo build` is broken, passing `-` to rustc as a crate name

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/cargo#1342]
With a fresh build of both rustc and cargo, `cargo build` and other similar commands are executing `rustc` somewhere along the way with the crate name `-`, which is completely forbidden since rust-lang/rust#22664 landed a few hours ago. I guess it used to work in some manner or other but is now a non-zero exit code propagating to cause failure of the build.

This is happening on all my libraries, regardless of any dependencies they may or may not have.

```
$ cargo build --verbose
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names` (status=101)
--- stderr
error: crate name cannot start with a hyphen: -
error: aborting due to previous error
```

- cargo 0.0.1-pre (b6c07a6 2015-02-24 00:28:31 +0000)
- rustc 1.0.0-dev (91a5a1ab4 2015-02-23) (built 2015-02-24)

**Comment by lfairy** [comment]
Oh noes! :scream:

Looking at [the code], it seems that Cargo runs `rustc` with a dummy crate name first, to probe for platform-specific data. And that dummy name just happens to a single hyphen.

[the code]: https://github.com/rust-lang/cargo/blob/9404539e80a3614b56f7cdfeec4eb2cd777ee912/src/cargo/ops/cargo_rustc/context.rs#L89-L102

I think we can fix this by changing the hyphen to an underscore instead, or some other meaningless-but-valid value.

**Comment by lfairy** [comment]
Okay, I have a possible fix on [my fork]. I couldn't get the dependencies to build though, so if someone could confirm it works that would be great.

[my fork]: https://github.com/lfairy/cargo/commit/db0662c916b637f1d15576bad9718e6277ae984e

**Comment by Tobba** [comment]
This is the third time this one routine has completely broken cargo.
