### ISSUE TITLE
Cargo 1.78 release date is in the future

### ISSUE THREAD

**Issue by ffjdm** [rust-lang/cargo#13428]
### Problem

CHANGELOG.md contains Cargo 1.78 (2024-05-02)
Notice the date is in the future
It should probably be 2024-02-05

### Possible Solution(s)

Update date to 2024-02-05

### Version

```text
1.78 (visible in master too)
```

**Comment by epage** [comment]
1.78 is in the future, see https://releases.rs/  

We have a predictable release schedule so we can put the version and date in for unreleased versions.
