### ISSUE TITLE
Add support for binary dependencies

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/cargo#13431]
### Problem

I couldn't find an issue about this so opening one. In my blog post about [writing your own rust linter](https://blog.guillaume-gomez.fr/articles/2024-01-18+Writing+your+own+Rust+linter), I need to have two cargo binaries:  the first calling the second with the right arguments. However, it means that I need to ask users to install the two binaries (with `cargo install`) manually.

### Proposed Solution

It would be quite convenient if I could add in my `Cargo.toml`:

```
[binary.dependencies]
cargo-tools-inner = "x.y.z"
```

Like that, when running `cargo install cargo-tools`, it would also install `cargo-tools-inner` automatically. It's also important that the version is respected as the argument passed to `cargo-tools-inner` is quite important (the rustc toolchain to be used).

**Comment by rukai** [comment]
That sounds like https://rust-lang.github.io/rfcs/3028-cargo-binary-dependencies.html

**Comment by GuillaumeGomez** [comment]
It's exactly what I want. :+1: Closing the issue then, thanks!
