### ISSUE TITLE
Option to disable workspace edit feature of cargo new

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/cargo#13432]
### Problem

`cargo new` will unconditionally add the new crate to a cargo workspace when there is a Cargo.toml in the parent directory, even when that Cargo.toml is not intended as cargo workspace. For example I might create a new crate just to quickly test something or the build system can't handle the parent Cargo.toml being a cargo workspace for whatever reason.

### Proposed Solution

Add an option to `cargo new` to stop it from adding the new crate to any cargo workspace. And maybe disable the auto adding when there isn't yet a cargo workspace.

**Comment by epage** [comment]
#13391 stops adding the package to  the "workspace" if there isn't already a `[workspace]`.

cargo script will also be helping with these "quick experiment" cases.

For myself, I lean away with making this configurable.

**Comment by bjorn3** [comment]
> https://github.com/rust-lang/cargo/pull/13391 stops adding the package to the "workspace" if there isn't already a `[workspace]`.

Great! My nightly was just a bit too old for that, so I missed it.

**Comment by weihanglo** [comment]
With #13391, is this still relevant?
