### ISSUE TITLE
add #![feature(env)] to the crate attributes to silence this warning

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/cargo#1343]
I only need to specify this crate attribute in a single file called a.rs (not the root module).

However, I must specify this in the root module. This doesn't seem right.

I tried to set the attribute in the a.rs file without using the  bang like this:

#[feature(env)]

because it doesn't seem to be a crate-level attribute (if it was, the error message says, "crate-level attribute should be in the root module" - and the error message does not say this).

Not using bang didn't help.

I can workaround this by setting the attribute in the root module - it just seems confusing.

**Comment by alexcrichton** [comment]
Features are only detected at the crate root, not in each individual module itself. This is an issue for the rust-lang/rust repository instead of this one as well.
