### ISSUE TITLE
Native build on aarch64 is different than on x86

### ISSUE THREAD

**Issue by isbm** [rust-lang/cargo#13471]
### Problem

I have a project and I have two machines: x86 and NXP aarch64, both running identical Ubuntu 22.04.3 LTS. Both machines has no `musl` and both machines are on `glibc`. No cross-compilation process involved. Then all I do is just this:

    cargo build --release

In both cases I have `target/release...` binary. However, on x86 the resulting binary is dynamically linked, but on aarch64 is static.

Why is that? I need in both cases they get dynamically linked. And static linking with glibc is a no good idea from many points, including their LGPL lincence. And I cannot even influence it.

### Version

```text
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by arlosi** [comment]
Thanks for the report. The default is supposed to be dynamic linking the crt (`glibc`) for both those targets. I don't have an aarch64 machine to test this myself.

Does this also repro with the an empty project (created by `cargo new`)?

Could you also try this on the current stable version (1.76)?

How are you verifying that it's dynamically linked to glibc?

The `rustc` flag to control this behavior is `-C target-feature=+crt-static` to enable static linking or `-C target-feature=-crt-static` to disable it. You could also experiment with running `cargo rustc ` with those flags to see if you get a different result.

**Comment by isbm** [comment]
> Thanks for the report. The default is supposed to be dynamic linking the crt (`glibc`) for both those targets. I don't have an aarch64 machine to test this myself.

Any Raspberry would also do, BTW 😉 

> Does this also repro with the an empty project (created by `cargo new`)?

Did not tried per se, but all my packages I build on aarch64 are always static, while the same packages built on x86 are always dynamic. I read somewhere in community forums that `cargo` is trying to outsmart itself and is trying to magically switch between static/dynamic depends on conditions (not sure how it is implemented), trying to detect if it is `glibc` or not. But statically linking with `glibc` is a very bad idea anyway.

> Could you also try this on the current stable version (1.76)?

Would be sad if it worked. 😉 But I will try.
 
> How are you verifying that it's dynamically linked to glibc?

Because I am packaging Rust software for Ubuntu LTS and I really have no `musl` around. 😉 It is just really `glibc` provisioned by buildenv bootstrap and nothing else is there ensured.

After that, I just install the package on a test machine and `ldd` tells me everything.

> The `rustc` flag to control this behavior is `-C target-feature=+crt-static` to enable static linking or `-C target-feature=-crt-static` to disable it. You could also experiment with running `cargo rustc ` with those flags to see if you get a different result.

Thanks for the hint, I did not tried that yet. I will come back here to update you.

**Comment by isbm** [comment]
@weihanglo so now I have to figure out how my `cargo build --release` is different from your `cargo build --release`...

At least `cargo -Z unstable-options config get` returns me nothing. `+nightly` doesn't work, because I do not use it.

**Comment by Muscraft** [comment]
Do you mind running `cargo version --verbose` on your aarch64 machine? I saw you ran it on your x86_64 machine but not aarch64.

**Comment by ehuss** [comment]
I'm going to close due to a lack of reproduction. I also suspect this isn't a cargo issue, since cargo is not involved with determining how things are linked. I also get the same results as https://github.com/rust-lang/cargo/issues/13471#issuecomment-1957949315 above on my Ubuntu 22 image on aarch64.

If you need more assistance with trying to figure out why things don't seem to be linking as you expect, I'd suggest one of the user forums such as https://users.rust-lang.org/. It can be helpful if you can put together a specific reproduction, such as a Dockerfile that contains the exact commands to run.
