### ISSUE TITLE
build (compilation) errors on OS X 10.10

### ISSUE THREAD

**Issue by alexreg** [rust-lang/cargo#1349]
They seem related to C++.

https://gist.github.com/e000a1deb33fb9dd1e2d

**Comment by alexcrichton** [comment]
Cargo currently compiles with a pinned version of rust so be sure to [install `rustc`](https://github.com/rust-lang/cargo#compiling-cargo) according to the README. After that the compile errors should go away :)

**Comment by alexreg** [comment]
I don’t see any instructions on how to install rustc there…

**Comment by alexcrichton** [comment]
The compilation instructions are the relevant portions:

```
git clone https://github.com/rust-lang/cargo
cd cargo
git submodule update --init
./.travis.install.deps.sh
./configure --local-rust-root="$PWD"/rustc
make
make install
```

The `.travis.install.deps.sh` installs the pinned version of rustc locally and then `--local-rust-root` informs the makefiles about it.

**Comment by alexreg** [comment]
Ah right. Well, I did all of this, and the previous steps succeeded, but no luck at the “make” step.

(FYI, see my other bug I recently submitted, which I got around by disabling certificate verification in the Python code.)

**Comment by alexcrichton** [comment]
Hopefully that should be addressed by https://github.com/rust-lang/cargo/pull/1347 (just switching to using `curl`)

**Comment by alexreg** [comment]
Ah good, and it seems like that fix will be merged soon? Very well.

Anyway, I reran *all* the steps now and cargo is building just fine.

Thanks for your help.

**Comment by alexreg** [comment]
One final little question: is there some way to install the pinned rustc that cargo uses? (And rustdoc/other Rust utilities ideally.)

**Comment by alexcrichton** [comment]
I'd recommend the [multirust project](https://github.com/brson/multirust) for doing that, then it would be:

```
multirust update nightly-$date
```

**Comment by alexreg** [comment]
Perfect. Thanks!
