### ISSUE TITLE
Format change of ids in 'cargo metadata' with cargo 1.78

### ISSUE THREAD

**Issue by dan-t** [rust-lang/cargo#13528]
### Problem

The format of the id entries in the cargo metadata changes in cargo 1.78.

In cargo 1.76 the format is:
   "ansi_term 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)"

In cargo 1.78 the format is:
   "registry+https://github.com/rust-lang/crates.io-index#ansi_term@0.11.0"

Both formats are with '--format-version 1'.  Is this considered as a breaking change?

### Steps

- Execute 'cargo metadata --format-version 1' with cargo 1.76
- Execute 'cargo metadata --format-version 1' with cargo 1.78
- Compare the output

**Comment by epage** [comment]
This is not considered a breaking change.

From https://doc.rust-lang.org/1.76.0/cargo/commands/cargo-metadata.html#output-format

> Changing opaque representations — The inner representations of some fields are implementation details. For example, fields related to “Package ID” or “Source ID” are treated as opaque identifiers to differentiate packages or sources. Consumers shouldn’t rely on those representations unless specified.

With the change that was made, we have stabilized the format and you can rely on it, see #12914

**Comment by dan-t** [comment]
If you want to get the name and version of a package that‘s referenced as a resolved dependency or as a workspace member, you seem to have to parse the id. Therefore I‘m not quite sure that I would consider this as a non breaking change.

**Comment by weihanglo** [comment]
> get the name and version of a package that‘s referenced as a resolved dependency or as a workspace member, you seem to have to parse the id.

For this use case, it doesn't seem to. `workspace_members` array contains IDs that you can find matching `id` of a package in `packages` array.

**Comment by dan-t** [comment]
On Mon, Mar 04, 2024 at 10:54:21AM -0800, Weihang Lo wrote:
> For this use case, it doesn't seem to. `workspace_members` array
> contains IDs that you can find matching `id` of a package in
> `packages` array.

Yes, you're right.

From my point of view this ticket can then be closed.

**Comment by kyrias** [comment]
While it's true for workspace members, _is_ there currently any reliable way to get the name corresponding to an indirect dependency by the package ID specifier without having to parse it?

Because it seems like there's currently no way to reliably resolve a `package_id` from the `cargo build --message-format json-diagnostic-rendered-ansi` output into a package name that works with both <1.77 and >=1.77 cargo versions.

**Comment by epage** [comment]
@kyrias can't you take the package id and iterate over [`Metadata::packages`](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Metadata.html#structfield.packages), comparing the id from `cargo build` with [`Package::id`](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Package.html#structfield.id)?

**Comment by kyrias** [comment]
@epage `Metadata::packages` doesn't contain indirect dependencies.

**Comment by kyrias** [comment]
Wait, that's not true, it seems to contain *some* but not *all* indirect dependencies?  I'm confused now.

**Comment by kyrias** [comment]
Ah, I guess the issue here is that we're using `-Zbuild-std` and so we're getting `build-script-executed` lines for crates which end up not existing in the metadata.
