### ISSUE TITLE
Crate builds, but not as dependency

### ISSUE THREAD

**Issue by emmyoh** [rust-lang/cargo#13521]
### Problem

Hello,

I'm able to build [this crate](https://github.com/n0-computer/appa/tree/matheus23/it-will-have-iroh-i-promise) locally, but as soon as I specify it as a dependency for another crate, compilation fails, claiming that a certain struct (`Flatfs`) doesn't implement a certain trait (`wnfs_common::blockstore::BlockStore`) when it [clearly does](https://github.com/n0-computer/appa/blob/ea0c17dbeaf8a3f46849612455b678f379ee15b1/src/store/flatfs.rs#L400). I'm assuming that, since it's building otherwise, this must be a bug.

### Steps

1. Create a Rust project
2. Include [this crate](https://github.com/n0-computer/appa/tree/matheus23/it-will-have-iroh-i-promise) as a Git dependency (not sure what makes it special here)
3. Attempt to build your Rust project 

### Possible Solution(s)

Compilation should be successful, without:
> error[E0277]: the trait bound `Flatfs:wnfs_common::blockstore::BlockStore` is not satisfied

### Version

```text
cargo 1.78.0-nightly (194a60b29 2024-02-21)
release: 1.78.0-nightly
commit-hash: 194a60b2952bd5d12ba15dd2577a97eed7d3c587
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.71+curl-8.6.0 vendored ssl:OpenSSL/3.2.1)
ssl: OpenSSL 3.2.1 30 Jan 2024
os: Arch Linux Rolling Release [64-bit]
```

**Comment by ehuss** [comment]
The branch `matheus23/it-will-have-iroh-i-promise` of the repository https://github.com/n0-computer/appa does not build because it has a git dependency on https://github.com/fission-codes/rs-car-mirror.git with branch `matheus23/streaming`, but that branch does not exist.

Can you show the exact steps for the reproduction? What does the `Cargo.toml` look like exactly?

**Comment by emmyoh** [comment]
@ehuss You're right—sorry about that. To fix:
1. Clone the crate I mentioned, and modify line 15 its `Cargo.toml` like so:
```diff
- car-mirror = { git = "https://github.com/fission-codes/rs-car-mirror.git", branch = "matheus23/streaming", features = ["quick_cache"] }
+ car-mirror = { git = "https://github.com/fission-codes/rs-car-mirror.git", rev = "ec0a4d56", features = ["quick_cache"] }
```
2. Include the cloned copy of the crate in your Rust project with `path` instead of `git` (eg, `appa = { path = "/home/emil/Documents/GitHub/appa" }` on my machine)

Now you should be seeing the same behaviour I described?

**Comment by ehuss** [comment]
The appa project at has [a patch](https://github.com/n0-computer/appa/blob/ea0c17dbeaf8a3f46849612455b678f379ee15b1/Cargo.toml#L44-L45):

```
[patch.crates-io]
wnfs-common = { git = "https://github.com/wnfs-wg/rs-wnfs.git", branch = "matheus23/root-tree" }
```

When you use something as a dependency, the `[patch]` table is ignored in dependencies. You'll need to copy that into your project.

**Comment by emmyoh** [comment]
Oh, wow. I feel so silly. That was it! Closing. Thank you!
