### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by bibhas2** [rust-lang/cargo#1352]
Cargo is failing to build any project.

Platform: rustc 1.0.0-nightly (c4fe7d6ae 2015-02-23) (built 2015-02-24). Mac OS X.

``cargo build --verbose`` produces:

```
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names` (status=101)
--- stderr
error: crate name cannot start with a hyphen: -
error: aborting due to previous error
```

Ways to duplicate the problem:

1. Create a new project: ``cargo new mycoolstuff``.
2. ``cd mycoolstuff``
3. ``cargo build --verbose``

**Comment by steveklabnik** [comment]
Yes, this is a bug which has been fixed, but hasn't made it to a nightly yet: http://users.rust-lang.org/t/psa-the-2015-02-25-nightly-contains-a-broken-cargo/455
