### ISSUE TITLE
Include crate/package name in `cargo test -- --format=json` output

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/cargo#13553]
### Problem

Currently, it is very hard (impossible?) to distinguish between events of tests with similar name in different crates in a cargo workspace `cargo test -- --format=json` output.

### Proposed Solution

Include crate or package name inside the event. That is, current state:
```json
{ "type": "suite", "event": "started", "test_count": 760 }
{ "type": "test", "event": "started", "name": "some_test" }
{ "type": "suite", "event": "ok", "passed": 1, "failed": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.002828253 }
{ "type": "suite", "event": "started", "test_count": 760 }
{ "type": "test", "event": "started", "name": "some_test" }
{ "type": "suite", "event": "ok", "passed": 1, "failed": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.002828253 }
```
becomes:
```json
{ "crate": "crate1", "type": "suite", "event": "started", "test_count": 760 }
{ "crate": "crate1", "type": "test", "event": "started", "name": "some_test" }
{ "crate": "crate1", "type": "suite", "event": "ok", "passed": 1, "failed": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.002828253 }
{ "crate": "crate2", "type": "suite", "event": "started", "test_count": 760 }
{ "crate": "crate2", "type": "test", "event": "started", "name": "some_test" }
{ "crate": "crate2", "type": "suite", "event": "ok", "passed": 1, "failed": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.002828253 }
```

**Comment by weihanglo** [comment]
Thanks for the report. This unstable JSON output is currently under re-design and experimental process. This will be implemented outside Cargo. (and it's never Cargo controling that. It's libtest inside rustc)

You can read the [RFC 3558](https://rust-lang.github.io/rfcs/3558-libtest-json.html), and follow the tracking issue <https://github.com/rust-lang/testing-devex-team/issues/1>.

Close in favor of <https://github.com/rust-lang/testing-devex-team/issues/1>.
