### ISSUE TITLE
Package builds as part of workspace, but not as a single package with missing feature declaration.

### ISSUE THREAD

**Issue by maciektr** [rust-lang/cargo#13554]
### Problem

Hi!

I stumbled upon a situation, when `cargo build` run in workspace root successfully builds all packages residing in it, while `cargo build -p package` returns an error due to missing feature declaration for one of my dependencies. 

After a bit of poking around, I suspect it is due to inclusion of an optional dep from one of the other packages (it's only my theory though). Please consider following to be the minimal reproduction: [github.com/maciektr/cargo-repro-1](https://github.com/maciektr/cargo-repro-1) (when run with `cargo build -p aaa` build fails, while `cargo build` completes successfully).

### Steps

1. Create a new Cargo workspace (`resolver = "2"`), with two packages - `A` and `B`. 
1. Add dependency on `serde_json` to `A` using default features. 
2. Add dependency on `axum` (which in turn depends on `serde_json` with `raw_value` feature enabled as optional dep) to `B`
3. Note there is no dependency on `B` in `A` or vice versa - just the same workspace. 
4. Try building whole workspace with `--workspace` and each of packages separately.

### Notes

Note that this can be misleading, e.g. when using `check --workspace` in CI. 

### Version

```text
1.76.0
```

**Comment by weihanglo** [comment]
Thanks for the issue report. I believe it's something to do with feature unification like this <https://github.com/rust-lang/cargo/issues/13297#issuecomment-1891117079>.

**Comment by weihanglo** [comment]
Looked at the repro on a proper machine. It does look like an expected result of the feature unification and `--package` flag. Close and thanks!
