### ISSUE TITLE
Remove unecessary mentions of semver

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#1356]
Since cargo does not enforce semver, and probably never will, it would be nice if it didn’t mention semver so much. Most mentions of semver can simply be replaced with just “version” without much loss.

E.g.

> cannot parse `0.0` as semver for key `package.version`

to

> cannot parse `0.0` as a version for key `package.version`, try `0.0.0`

**Comment by steveklabnik** [comment]
Cargo does in fact resolve versions according to SemVer.

**Comment by alexcrichton** [comment]
I do think that while we don't enforce the *rules* of semver for updating crates we definitely have it permeate elsewhere. For example:

* The way we actually interpret a version string is in accordance with the SemVer specification
* The way we compare versions is defined by SemVer
* During resolution, we only allow one "semver compatible" version in a series (e.g. something defined by SemVer).

So although we do not enforce SemVer on modifications of a crate, we definitely still use the concepts in SemVer throughout Cargo in many places.
