### ISSUE TITLE
Not reproducible when a project is copied to another directory

### ISSUE THREAD

**Issue by cathy-sjh** [rust-lang/cargo#13585]
### Problem
-Cmetadata Inconsistency Caused by Directory Change, please see this: 
https://github.com/rust-lang/cargo/issues/13586

### Steps

-Cmetadata Inconsistency Caused by Directory Change

### Version

```text
rustc 1.76.0-nightly (f5dc2653f 2023-11-25)
binary: rustc
commit-hash: f5dc2653fdd8b5d177b2ccbd84057954340a89fc
commit-date: 2023-11-25
host: aarch64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

**Comment by weihanglo** [comment]
<https://github.com/rust-lang/cargo/issues/13586> is transferred so close this in favor of that.
