### ISSUE TITLE
Windows - can't run Cargo within Bash

### ISSUE THREAD

**Issue by nebffa** [rust-lang/cargo#1358]
1. Install Rust nightly from http://www.rust-lang.org/install.html
2. Open up Git bash in Windows and call "cargo" - immediately I get "cargo.exe has stopped working..."

It does, however, work from within the msys or MinGW shells I have installed.

**Comment by alexcrichton** [comment]
Are you unable to run `rustc`  as well?

**Comment by nebffa** [comment]
Hey Alex, I investigated this a bit more and was able to fix it - it's not a problem with `rust` or `cargo`. After searching and finding ![this issue for the ConEmu console emulator](https://code.google.com/p/conemu-maximus5/issues/detail?id=1596) I thought maybe this was a separate problem with `ConEmu`.

`rustc`, `cargo` and running binaries all worked fine when I opened `Powershell` and `Git Bash` on their own, so I updated `ConEmu` to the latest development version (I had been using the latest stable version), I can run `cargo` and `rustc` just fine and execute the binaries as normal. 

You can close this issue. Thanks!

**Comment by alexcrichton** [comment]
Thanks for investigating @nebffa!
