### ISSUE TITLE
Cargo cannot parse azure devops ssh git urls

### ISSUE THREAD

**Issue by juliusl** [rust-lang/cargo#13622]
I'm running into a bit of trouble trying to get a crate from an azure devops registry.

I am able to run the git command that cargo will eventually call successfully, 

```bash
❯ git fetch --force --update-head-ok '<omitted>@ssh.dev.azure.com:v3/<omitted>/<omitted>/<my-repo>' '+HEAD:refs/remotes/origin/HEAD'
❯  
```

However, due to this line:

https://github.com/rust-lang/cargo/blob/8bcecfeed464c990733ff680e0b4546a73fbed44/src/cargo/util/toml_mut/dependency.rs#L888

I get the error: 

```
 invalid url `<omitted>`: relative URL without a base
```

I've tried several variations of the url, but that format seems to be the only one that works. The recommendation from the cargo book does not work and returns this error:

```
 git fetch --force --update-head-ok 'ssh://<omitted>@ssh.dev.azure.com/<omitted>/<omitted>/<my-repo>.git' '+HEAD:refs/remotes/origin/HEAD'
remote: Command git-upload-pack '/<omitted>/<omitted>/<my-repo>.git' is not in expected format.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Since cargo is able to parse that format, the above error is what I receive when calling `cargo update`, which circles back to this issue.

Also, if I try to use `ssh://<omitted>@ssh.dev.azure.com:v3/<omitted>/<omitted>/<my-repo>`, `url::Url::parse` will return:

```
invalid url `<omitted>`: invalid port number
```

Given how nuanced private git repo urls can be, I feel like `url::Url` might not be the right type at this point and could be refactored w/ a newtype that is more flexible. Would this be open to discussion? (I don't mind contributing this change if a maintainer allows it)

**Comment by epage** [comment]
This looks to be a duplicate of #13549.  Does that cover your use case?

**Comment by juliusl** [comment]
@epage @weihanglo Thanks for the reply. Actually yes, there's a link I found in those issues: https://fahn.co/posts/cargo-auth-for-private-git-repos.html. 

I was able to get it to work by changing `:v3` to `/v3`.
