### ISSUE TITLE
having a space in the build path somewhere causes it to error and not run

### ISSUE THREAD

**Issue by Tygo2008** [rust-lang/cargo#13634]
### Problem

having a space in the build path somewhere causes it to error and not run
for example i have my projects in a "Rust Projects" folder and i tried running a tauri project and cargo gave me an error because it had a space in there and it turned it into "Projects"
![image](https://github.com/rust-lang/cargo/assets/154841662/1b44ddd4-1196-4f88-9549-480235ce3453)

### Steps

1. setup cargo project
2. have a space in the build path somewhere (like 'Rust Projects/project/')
3. try to build it

### Possible Solution(s)

cargo should surround paths with quotes

### Version

```text
cargo 1.77.0 (3fe68eabf 2024-02-29)
release: 1.77.0
commit-hash: 3fe68eabf93cbf3772bbcad09a9206c783e2de3f
commit-date: 2024-02-29
host: x86_64-pc-windows-msvc
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.5.0-DEV (sys:0.4.70+curl-8.5.0 vendored ssl:Schannel)
os: Windows 10.0.22631 (Windows 11 Professional) [64-bit]
```

**Comment by weihanglo** [comment]
It seems like `-L C:\dev\Rust Projects\tauri-radar-app\src-tauri\.cargo` was passed to the rustc invocation. It is usually from [`RUSTFLAGS`](https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html) environment variable, or [`build.rustflags`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#buildrustflags) configuration. If passed as strings, they are separated by spaces. You need to either use `CARGO_ENCODED_RUSTFLAGS` or `build.rustflags = [...]` if your args contain spaces.

**Comment by weihanglo** [comment]
Going to close this as this is user's responsibility to quote or escape spaces, if passing via `RUSTFLAGS` or `build.rustflags = "<string-value>"`. Let us know if it still happens, and feel free to open a new issue with a minimal complete reproduction.
