### ISSUE TITLE
Add global --[no-]-color flags

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/cargo#1363]
This is a request to add `--color` and `--no-color` command line flags to Cargo, to explicitly enable and disable ANSI colors in the CLI's output.

A use case for `--color` is when configuring Vim to run Cargo as its build program, invoked with Vim's `:make` command. This command does not allocate a TTY, which results in colorless output from Cargo. With a `--color` flag, Vim could be configured to pass the flag to all Cargo subcommands to produce colored output.

I don't have a specific use case for --no-color, but it's pretty standard to provide on/off variants for boolean flags.

**Comment by pornel** [comment]
:+1: 

My usecase is `cargo build 2>&1 | more` to be able to read the first error out of many.

**Comment by Wmaxlees** [comment]
My auto `cargo test` running program, [trust](https://github.com/Wmaxlees/trust) would benefit from color as well

**Comment by iliekturtles** [comment]
I started looking at this and found that `Shell::create` is called before options are parsed. I'm looking for a recommendation about how to adjust once options have been parsed:

 * Call `Shell::create` again after options are parsed and replace the existing `out` and `err` `Shell`s in `MultiShell`.
 * Always attempt to create a color `Shell` and after options are parsed capture the desired state for color output and check every time output is sent to the `Shell`. This is similar to how the `--verbose`/`--quiet` flags work.

**Comment by alexcrichton** [comment]
@iliekturtles I think it's fine to assume the normal (current) logic about coloring before the options have been parsed, and then after they've been parsed the option can take over.
