### ISSUE TITLE
Already borrowed panic (`BorrowMutErr`) during `cargo update`

### ISSUE THREAD

**Issue by TheLostLambda** [rust-lang/cargo#13658]
### Problem

When running `cargo update`, I encountered the following crash:
![image](https://github.com/rust-lang/cargo/assets/6251883/c1d815ee-4d96-41f7-b229-e688707f65b1)

With the error being:
```
thread 'main' panicked at src/cargo/util/context/mod.rs:412:20:
already borrowed: BorrowMutError
```

### Steps

1. Clone this repo: https://github.com/TheLostLambda/smithereens
2. Switch to the `cargo-bug` branch
3. Run `cargo update`
4. Crash!

### Notes

Happy to help debug and gather more information if there are any issues reproducing!

### Version

```text
cargo 1.79.0-nightly (a510712d0 2024-03-25)
release: 1.79.0-nightly
commit-hash: a510712d05c6c98f987af24dd73cdfafee8922e6
commit-date: 2024-03-25
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux Rolling Release [64-bit]
```

**Comment by TheLostLambda** [comment]
Also, I've just tested with the `beta` release of cargo, and it works fine! It would seem that the bug has been introduced / exposed between this version and now:
```
cargo 1.78.0-beta.2 (2fe739fcf 2024-03-15)
release: 1.78.0-beta.2
commit-hash: 2fe739fcf16c5bf8c2064ab9d357f4a0e6c8539b
commit-date: 2024-03-15
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux Rolling Release [64-bit]
```

**Comment by TheLostLambda** [comment]
And I think that makes this the diff containing potential trouble-makers...
https://github.com/rust-lang/cargo/compare/2fe739fc...a510712

It's a big one, so perhaps someone with a bit more time / knowledge of the cargo internals will have to `git bisect`!

**Comment by epage** [comment]
This was likely a duplicate of #13646 and fixed in #13647.

**Comment by TheLostLambda** [comment]
@epage I think you're probably right — I'll try with the current git version and let you know!
If it is fixed, then I'll close this!

**Comment by TheLostLambda** [comment]
Looks to be fixed! Thanks for the rapid response @epage !
