### ISSUE TITLE
Inconsistent file permissions

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1366]
The permissions of files generated by `cargo new`, `cargo build`, `cargo build --release` and `cargo doc` seem inconsistent, I'm wondering as to the reasoning behind this logic.

As shown here:
```
target
├── [drwxr-xr-x]  build
├── [drwxr-xr-x]  deps
├── [drwx------]  doc
│   ├── [-rw-------]  FiraSans-Medium.woff
│   ├── [-rw-------]  FiraSans-Regular.woff
│   ├── [-rw-------]  Heuristica-Italic.woff
│   ├── [drwx------]  implementors
│   ├── [-rw-------]  jquery.js
│   ├── [-rwx------]  .lock
│   ├── [-rw-------]  main.css
│   ├── [-rw-------]  main.js
│   ├── [-rw-------]  normalize.css
│   ├── [-rw-------]  playpen.js
│   ├── [-rw-------]  search-index.js
│   ├── [-rw-------]  SourceCodePro-Regular.woff
│   ├── [-rw-------]  SourceCodePro-Semibold.woff
│   ├── [-rw-------]  SourceSerifPro-Bold.woff
│   ├── [-rw-------]  SourceSerifPro-Regular.woff
│   └── [drwx------]  src
│       └── [drwx------]  project
├── [drwxr-xr-x]  examples
├── [drwxr-xr-x]  .fingerprint
│   └── [drwxr-xr-x]  project-005523747bb810c4
│       ├── [-rw-------]  dep-lib-project
│       ├── [-rw-------]  doc-lib-project
│       └── [-rw-------]  lib-project
├── [-rw-r--r--]  libproject-005523747bb810c4.rlib
├── [drwxr-xr-x]  native
└── [drwx------]  release
    ├── [drwxr-xr-x]  build
    ├── [drwxr-xr-x]  deps
    ├── [drwxr-xr-x]  examples
    ├── [drwxr-xr-x]  .fingerprint
    │   └── [drwxr-xr-x]  project-005523747bb810c4
    │       ├── [-rw-------]  dep-lib-project
    │       └── [-rw-------]  lib-project
    ├── [-rw-r--r--]  libproject-005523747bb810c4.rlib
    └── [drwxr-xr-x]  native
```

All regular build files, and build files in the `release/` directory have at least 644 (755 for directories). However, the `release/` directory itself has 700, and the entire `doc/`directory is 600 (700 on directories).

I'm mainly wondering what the reasoning behind this is, mainly why the `doc/` directory has only owner permissions.

One other question is why `cargo new` produces 700 directories and 600 files only, rather than 755 and 644.

The full terminal output I used to test this can be found at: https://gist.github.com/daboross/3eab74343308a60eb99d.

**Comment by alexcrichton** [comment]
Thanks for the report! This has to do with `std::old_io::fs` vs `std::fs` where the behavior slightly differs. This behavior should become consistent in time and this is largely just an artifact of the transition period we're currently in.

This should be taken care of soon though!
