### ISSUE TITLE
cargo should clone iced and smithay one time and partial

### ISSUE THREAD

**Issue by soloturn** [rust-lang/cargo#13671]
### Problem

rust based desktop cosmic desktop has modules. most modules depend on smithay and iced git repo. building cosmic modules clones such dependencies 20 times, and cannot be convinced to do a partial clone, despite stting CARGO_TARGET_DIR.

### Steps

```
git clone git@github.com:pop-os/cosmic-epoch.git
cd cosmic-epoch
git submodule update --init --filter=tree:0
RUSTUP_TOOLCHAIN=stable CARGO_TARGET_DIR=/tmp/mytarget CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse just sysext
```

### Possible Solution(s)

somehow put the checked out repo into same location, and pass GITFLAGS "--filter=tree:0"

**Comment by weihanglo** [comment]
The dependency tree contains the same dependencies on different revision, so multiple clones is unavoidable unless one commit object is already included in the git history of the other. Some experimental git features like shallow clones can be found in [`-Zgitoxide`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#gitoxide) and [`-Zgit`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#git) unstable flags. Sparse and partial clones supports are being tracked under <https://github.com/rust-lang/cargo/issues/11165>, so close in favor of them. Thanks for the report.
