### ISSUE TITLE
Option to disable installation with `install`

### ISSUE THREAD

**Issue by vertesians** [rust-lang/cargo#13699]
### Problem

Some crates require extra processing that `cargo install` cannot provide even with build scripts (e.g., fish-shell/fish-shell#10181), causing them to be broken without warning.

### Proposed Solution

Provide a config option on a bin that prevents it from being installed with `cargo install`, with an error message telling the user to refer to the crate's documentation or repository instead. Maybe also provide a flag that forces an install with a warning.

**Comment by epage** [comment]
Could you help me understand what would be the point of publishing the bin package if it isn't meant to be installed?

**Comment by vertesians** [comment]
> Could you help me understand what would be the point of publishing the bin package if it isn't meant to be installed?

It's nice to have projects up on crates.io since it's how many Rust users discover crates in the first place. And I think not publishing a crate would make other things difficult, like putting code documentation up on docs.rs.

**Comment by epage** [comment]
> It's nice to have projects up on crates.io since it's how many Rust users discover crates in the first place. And I think not publishing a crate would make other things difficult, like putting code documentation up on docs.rs.

If you have a lib, that makes sense.  If you are using crates.io to post a bin for the sake of advertising, that sounds more like a hack than anything else.

> It's extra awkward with crates that are both bins and libraries, though I suppose you could make a separate unpublished crate for the bin... but that feels hacky.

Not hacky and there are lots of good reasons to split bins and libs into separate packages, for example
- https://blog.rust-lang.org/inside-rust/2024/02/13/this-development-cycle-in-cargo-1-77.html#when-to-use-packages-or-workspaces
- https://blog.axo.dev/2024/03/its-a-lib-and-a-bin

You can also use `package.exclude` to exclude the bin from being included in the `.crate` if you don't have an explicit `[[bin]]` table.  #13713 proposes changing cargo to automatically remove those `[[bin]]` tables.

**Comment by vertesians** [comment]
@epage Hmm. Okay, I see what you mean, and I'm convinced. Closing the issue.
