### ISSUE TITLE
Release notes/upgrade documentation?

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#1369]
Does Cargo have a recommended way of associating release notes with versions?

Some way of providing upgrade instructions to users when they upgrade packages via Cargo.

This came up in [discussion](https://github.com/GuillaumeGomez/c_vec-rs/issues/3) when c_vec changed exposed type signatures, and I'm not sure where would be the right place for the project to inform users about that change.

**Comment by GuillaumeGomez** [comment]
Why not providing a message with a new crate version for example ?

**Comment by alexcrichton** [comment]
There currently is not "official way" of doing this, it's done on a per-repo basis.

**Comment by carols10cents** [comment]
> Does Cargo have a recommended way of associating release notes with versions?
> 
> Some way of providing upgrade instructions to users when they upgrade packages via Cargo.

These two things sound like different features potentially, if I'm understanding correctly.

The first feature I'm hearing is to have a key in `Cargo.toml` like `release-notes = "CHANGELOG.md"` that would be something like the `readme` key, where crate authors could indicate a file in the repo that contains release notes/change logs, and users could go look there, and crates.io could potentially display them somewhere, etc.

The second feature sounds like a thing rubygems has that it calls ["post-install messages"](http://brandonhilkert.com/blog/ruby-gem-post-install-message/)-- library authors can put a message in their Cargo.toml equivalent that will get displayed on stdout when a user installs that library. While they can be used to inform the user about changes and point to release notes (the newrelic example in the link), they can also be used for silly things that annoy people (the httparty example in the link)

Could you clarify if you were thinking of one, both, or neither of these? :)

**Comment by pornel** [comment]
I was thinking about something displayed similarly to post-install messages, but only after an upgrade (so a "post-upgrade" message).

**Comment by dhardy** [comment]
I'm not personally convinced displaying changelogs on the command line is worthwhile. On the other hand a field in `Cargo.toml` like `release-notes` (mentioned above) and an extra link when browsing packages on crates.io would be useful.

It may also be worth recommending some conventions: http://keepachangelog.com/en/1.0.0/

**Comment by carols10cents** [comment]
I'm going to close this issue because it's actually replaced by this RFC, which contains lots of discussion: https://github.com/rust-lang/rfcs/pull/2129
