### ISSUE TITLE
Support for loading command line arguments from a file

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#13690]
### Problem

Currently, the only way to supply arguments to `cargo` is directly through the command line.
For example if you want to build with a set of features, you always have to invoke cargo with `(--no-default-features) --features=[...]`.
Furthermore, every single piece of tooling that invokes cargo (rust-analyzer, clippy, [bacon](https://github.com/Canop/bacon), etc.) has to also be configured to invoke cargo with the same flags, if the user wants to keep working with a specific feature combination.

If there was a way to tell cargo to load arguments from a file (through `.cargo/config.toml` for example), then all invocations of cargo would automatically load the specified flags, solving the problem of syncing various tooling, and having to needlessly repeat command line flags.

Also see <https://internals.rust-lang.org/t/pre-rfc-presets-for-cargo/20527> for what I'm trying to accomplish.
Argfile support would greatly ease a third party implementation of presets, which currently requires a [wrapper executable](https://github.com/crumblingstatue/cargo-presets/) that rewrites arguments before executing cargo.

### Proposed Solution

Have a way to configure cargo to load arguments from a specified file.
This could be done in `.cargo/config.toml`.
```toml
[args]
file = "myargfile.txt" # Load command line flags from myargfile.txt
```
Cargo would proceed to load the command line flags from the configured file, if it exists.

- I think it would be reasonable if cargo printed a warning if the file doesn't exist, but would continue regardless.
- If any command line arguments conflict with the arguments specified in the argfile, I think it would make sense for the CLI flags to override the flags provided in the file, but stopping with an error is also reasonable, if that behavior is more desirable.

### Notes

- Rustc has support for argfiles via [`@argfile`](https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path), although for cargo, I want a solution that can be configured without having to specify `@argfile` on the command line to work.
- Zulip discussion: <https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Argfile.20discussion>

**Comment by epage** [comment]
As this is conveyed to be for every cargo command, I do not think this is something we can or should do
- Not all arguments apply to all commands
- Like with concerns over aliases overriding built-in commands, this makes it harder to tell what cargo will do / to automate cargo.

**Comment by crumblingstatue** [comment]
> * Not all arguments apply to all commands

That's a good point that I haven't considered.

Looks like unfortunately, looks like the only solution for my problem for the foreseeable future will be a cargo wrapper.
