### ISSUE TITLE
Reference staging.crates.io in the Cargo book

### ISSUE THREAD

**Issue by allsey87** [rust-lang/cargo#13707]
### Problem

Sometimes people create crates on crates.io simply to learn about how the process works. This can lead to congestion and unnecessary reservation of crate names.

### Proposed Solution

In [this section of the Cargo book](https://doc.rust-lang.org/cargo/reference/publishing.html), clearly mention how to configure everything to push to https://staging.crates.io/ first.

**Comment by epage** [comment]
The staging server sounds like its more for development of crates.io than for users (see zulip thread [Testing Index](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/Testing.20index/near/409438298)).  I worry that by making this more prominent, we'd be giving users a wrong impression about 
how this fits into their development workflow.

@Turbo87 thoughts?

**Comment by allsey87** [comment]
If not staging, it would be valuable to have somewhere where people can upload their tests without polluting crates.io with crates like https://crates.io/crates/test123

**Comment by Turbo87** [comment]
I agree with what Ed has said above. We don't give any stability guarantees for the staging environment. Adding it to official docs means we'd have to maintain some level of stability.

**Comment by epage** [comment]
As for any kind of user registry playground, I'd recommend finishing that conversation with the [crates.io team](https://github.com/rust-lang/crates.io/).

As the Cargo side of this is unlikely to move forward, I'm going to go ahead and close this.
