### ISSUE TITLE
vsock 0.4.0 fails to compile

### ISSUE THREAD

**Issue by veselinas** [rust-lang/cargo#13711]
# Problem

I am trying to run a particular GitHub project in rust - cloned the repository and attempted to run the project, but it fails during the dependencies loading process. It cannot compile vsock-0.4.0. This seems to depend on the libc library which I can see from the Cargo.lock file is version 0.2.153 - all looks stable in cargo.io and the modules which are listed all seem to be present in the latest stable version - https://docs.rs/libc/0.2.153/libc/. I am a new Mac user so I can be doing something wrong, but wondering if it can be platform related? Also, the project seems to be pointing to a nightly version of Rust in rust-toolchain.toml but I don't know if this can have impact here.

# Steps

1. Create a new cargo project
2. Update the Cargo.toml file to have the vsock="0.4.0" dependency
[package]
name = "playground"
version = "0.1.0"
edition = "2021"
[dependencies]
vsock = "0.4.0"
3. cargo run 

# Possible Solution(s)

_No response_

# Notes

error[E0432]: unresolved imports `libc::accept4`, `libc::SOCK_CLOEXEC`
  --> /Users/veselinastefanova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vsock-0.4.0/src/lib.rs:21:5
   |
21 |     accept4, ioctl, sa_family_t, sockaddr, sockaddr_vm, socklen_t, susec...
   |     ^^^^^^^ no `accept4` in the root
22 |     FIONBIO, SOCK_CLOEXEC,
   |              ^^^^^^^^^^^^ no `SOCK_CLOEXEC` in the root
   |
help: a similar name exists in the module
   |
21 |     accept, ioctl, sa_family_t, sockaddr, sockaddr_vm, socklen_t, suseconds_t, timeval, AF_VSOCK,
   |     ~~~~~~
help: a similar name exists in the module
   |
22 |     FIONBIO, O_CLOEXEC,
   |              ~~~~~~~~~

error[E0432]: unresolved import `libc::VMADDR_CID_LOCAL`
  --> /Users/veselinastefanova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vsock-0.4.0/src/lib.rs:42:72
   |
42 | ...ADDR_CID_HYPERVISOR, VMADDR_CID_LOCAL};
   |                         ^^^^^^^^^^^^^^^^
   |                         |
   |                         no `VMADDR_CID_LOCAL` in the root
   |                         help: a similar name exists in the module: `VMADDR_CID_HOST`

error[E0599]: no associated item named `SOCK_CLOEXEC` found for struct `SockFlag` in the current scope
   --> /Users/veselinastefanova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vsock-0.4.0/src/lib.rs:49:19
    |
49  |         SockFlag::SOCK_CLOEXEC,
    |                   ^^^^^^^^^^^^ associated item not found in `SockFlag`
    |
note: if you're trying to build a new `SockFlag` consider using one of the following associated functions:
      socket::_::<impl SockFlag>::empty
      socket::_::<impl SockFlag>::all
      socket::_::<impl SockFlag>::from_bits
      socket::_::<impl SockFlag>::from_bits_truncate
      and 2 others
   --> /Users/veselinastefanova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.27.1/src/sys/socket/mod.rs:275:1
    |
275 | / libc_bitflags! {
276 | |     /// Additional socket options
277 | |     pub struct SockFlag: c_int {
278 | |         /// Set non-blocking mode on the new socket
...   |
307 | |     }
308 | | }
    | |_^
    = note: this error originates in the macro `$crate::__impl_bitflags` which comes from the expansion of the macro `libc_bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0560]: struct `sockaddr_vm` has no field named `svm_zero`
   --> /Users/veselinastefanova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vsock-0.4.0/src/lib.rs:118:13
    |
118 |             svm_zero: [0u8; 4],
    |             ^^^^^^^^ `sockaddr_vm` does not have this field
    |
    = note: available fields are: `svm_len`

error[E0599]: no associated item named `MSG_NOSIGNAL` found for struct `MsgFlags` in the current scope
   --> /Users/veselinastefanova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vsock-0.4.0/src/lib.rs:334:57
    |
334 |         Ok(send(self.socket.as_raw_fd(), buf, MsgFlags::MSG_NOSIGNAL)?)
    |                                                         ^^^^^^^^^^^^ associated item not found in `MsgFlags`
    |
note: if you're trying to build a new `MsgFlags` consider using one of the following associated functions:
      socket::_::<impl MsgFlags>::empty
      socket::_::<impl MsgFlags>::all
      socket::_::<impl MsgFlags>::from_bits
      socket::_::<impl MsgFlags>::from_bits_truncate
      and 2 others
   --> /Users/veselinastefanova/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.27.1/src/sys/socket/mod.rs:310:1
    |
310 | / libc_bitflags! {
311 | |     /// Flags for send/recv and their relatives
312 | |     pub struct MsgFlags: c_int {
313 | |         /// Sends or requests out-of-band data on sockets that suppor...
...   |
398 | |     }
399 | | }
    | |_^
    = note: this error originates in the macro `$crate::__impl_bitflags` which comes from the expansion of the macro `libc_bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0432, E0560, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `vsock` (lib) due to 5 previous errors

# Version

```text
cargo 1.78.0-nightly (fc1d58fd0 2024-02-09)
release: 1.78.0-nightly
commit-hash: fc1d58fd0531a57a6b942a14cdcdbcb82ece16f3
commit-date: 2024-02-09
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.4.0 (sys:0.4.71+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.3.0 [64-bit]
```

**Comment by veselinas** [comment]
It actually fails in this stable version too:
cargo 1.77.1 (e52e36006 2024-03-26)
release: 1.77.1
commit-hash: e52e360061cacbbeac79f7f1215a7a90b6f08442
commit-date: 2024-03-26
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.4.0 (sys:0.4.70+curl-8.5.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.3.0 [64-bit]

**Comment by ehuss** [comment]
It looks like vsock does not support macOS. Types like `SOCK_CLOEXEC` are linux-specific. I understand it can be a little confusing looking at docs.rs when there are platform-specific `cfg` items. It defaults to showing documentation for linux. You can click the "Platform" link at the top of docs.rs, and select `aarch64-apple-darwin` to see the documentation for your platform. There you can see that those types don't exist.

**Comment by veselinas** [comment]
Thank you very much for confirming this and for the insights!
