### ISSUE TITLE
Cargo build/run not working - Bad CPU type in executable

### ISSUE THREAD

**Issue by ramit29** [rust-lang/cargo#13733]
### Problem

`cargo run` and `cargo build` is not working

`cargo run

error: could not execute process `rustc -vV` (never executed)

Caused by:
  Bad CPU type in executable (os error 86).`

### Version

```text
cargo 1.77.1 (e52e36006 2024-03-26)
release: 1.77.1
commit-hash: e52e360061cacbbeac79f7f1215a7a90b6f08442
commit-date: 2024-03-26
host: x86_64-apple-darwin
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.4.0 (sys:0.4.70+curl-8.5.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 13.6.6 [64-bit]
```

**Comment by heisen-li** [comment]
I don't have a Mac, so I may not have an accurate answer. I googled it and it looks like something needs to be installed or upgraded. These references might be useful to you:
https://github.com/rustwasm/wasm-pack/issues/1098
[Fix for MacBook Air M1/M2 — ‘Bad CPU type in executable’ Error](https://medium.com/@jithmisha/fix-for-macbook-air-m1-m2-bad-cpu-type-in-executable-error-3719a0a1cb6)

**Comment by ramit29** [comment]
Sorry, I managed to fix it, It was an issue with my $PATH referencing a different rust version
