### ISSUE TITLE
ffmpeg-sys vs ffmpeg-sys-next

### ISSUE THREAD

**Issue by soloturn** [rust-lang/cargo#13755]
### Problem

if one owner archives his repo which produces ffmpeg-sys, another one can produce ffmpeg-sys-next. new owner cannot continue to produce ffmpeg-sys?

**Comment by weihanglo** [comment]
What did you mean by produce? Could you clarify the question?

**Comment by soloturn** [comment]
produce means put a binary here:
https://crates.io/crates/ffmpeg-sys

**Comment by weihanglo** [comment]
If I understand correctly, you want to "publish" new version of `ffmpeg-sys` to crates.io. That means you need to either have the publish permission or take over the ownership of `https://crates.io/crates/ffmpeg-sys`. Per [crates.io's policy](https://crates.io/policies), you'll need to contact the author by yourself or ask crates.io team for help with that if they haven't replied for a long while. 

The alternative solution is using [`[patch]`](https://doc.rust-lang.org/nightly/cargo/reference/overriding-dependencies.html#the-patch-section), though it has a limitation that you cannot patch a crates.io dependency over the other also from crates.io. You might want to subscribe this issue <https://github.com/rust-lang/cargo/issues/9227>.

Close as ownership of crates is controlled by crates.io team and services, not Cargo the tool.
