### ISSUE TITLE
Inconsistent behavior with --nocapture

### ISSUE THREAD

**Issue by michaelbeaumont** [rust-lang/cargo#1377]
`cargo test -- --nocapture` runs all my tests and I see all the stdout as it comes.
`cargo test mod::test_name -- --nocapture` runs mod::test_name but still captures all the output.
I don't think this is intended behavior.

I assume it has something to do with passing parameters using `--` in general but I have no idea.

I'm using the nightly version of cargo installed with `rustup.sh`

**Comment by alexcrichton** [comment]
cc @BurntSushi, I think we may be doing something wrong with docopt here, and I'm curious to get your thoughts on this. As an example, for this program:

```rust
extern crate docopt;                                
use docopt::Docopt;                                 
                                                    
static USAGE: &'static str = "                      
Usage:                                              
    foo test [options] [--] [<args>...]             
                                                    
Options:                                            
    -h, --help              Print this message      
";                                                  
                                                    
fn main() {                                         
    let args = Docopt::new(USAGE).unwrap()          
                      .parse()                      
                      .unwrap_or_else(|e| e.exit());
    println!("{:?}", args);                         
}                                                   
```

I get the following invocations.

```
$ ./target/wut test a -- -b
-- => Switch(false)
-h, --help => Switch(false)
<args> => List(["a", "--", "-b"])
test => Switch(true)
$ ./target/wut test -- -a
-- => Switch(true)
-h, --help => Switch(false)
<args> => List(["-a"])
test => Switch(true)
$ ./target/wut test a -b
Unknown flag: '-b'

Usage:
    foo test [options] [--] [<args>...]
```

The bug here is that `cargo test foo -- --nocapture` causes Cargo to pass down `foo -- --nocapture` as arguments to the test binary, and the test binary doesn't like the `--` before the `--nocapture`. Is it a bug that docopt doesn't strip the `--` argument?

**Comment by BurntSushi** [comment]
@alexcrichton Yeah, that does seem like a bug. I think I have a fix in https://github.com/docopt/docopt.rs/commit/b90c40d375ca18cc29db13d576f8dfd090f5c77a, where I just strip the `--` from the argv. I added your test cases as a regression test. :-)

**Comment by alexcrichton** [comment]
Oh awesome, thanks @BurntSushi!

**Comment by alexcrichton** [comment]
I think this was fixed in a recent update of docopt, but feel free to reopen if it still reproduces!
