### ISSUE TITLE
Suggest possible manifest key in case they are misspelt

### ISSUE THREAD

**Issue by javierhonduco** [rust-lang/cargo#13787]
### Problem

In one of my projects I was enabling a feature for a crate I use but I misspelt the `features` manifest key and used `feature` (notice the singular form). After figuring out why the feature wasn't activated I realised the missing trailing `s`. Later on, I noticed the helpful warning above (`warning: /home/javierhonduco/code/rbperf/Cargo.toml: unused manifest key: dependencies.nix.feature`).

### Proposed Solution

Similarly to other great cargo / rustc features, if the key is not part of the manifest but if it is close enough to a correct one, perhaps the correct one could be suggested.

**Comment by weihanglo** [comment]
Thanks for the report! https://github.com/rust-lang/cargo/issues/9731 is the issue tracking this. Close in favour of that.

**Comment by javierhonduco** [comment]
My bad didn't see there was an open issue already, thanks for the super quick reply!
