### ISSUE TITLE
Space separated features not working from command line

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/cargo#1378]
When I add it in the Cargo.toml, it works, but when trying to use multiple features from command line I get an "Invalid arguments" error. It works with a single feature.

https://github.com/bvssvni/start_piston

```
$ cargo build --features include_gfx include_sdl2
Invalid arguments.

Usage:
    cargo build [options]
```

```
$ cargo -V
cargo 0.0.1-pre-nightly (a58ffd7 2015-02-27) (built 2015-02-27)
```

**Comment by alexcrichton** [comment]
Right now that's being parsed as `include_gfx` as the argument to `--features` and `include_sdl2` as an argument to `cargo build` I think you may want to change your invocation to:

```
cargo build --features "include_gfx include_sdl2"
```

**Comment by bvssvni** [comment]
@alexcrichton Thanks!
