### ISSUE TITLE
dyld[18030]: Symbol not found on Mac Sonoma 14.3.1 ARM M3

### ISSUE THREAD

**Issue by beonic-rufus** [rust-lang/cargo#13795]
### Problem

cargo 1.77.2

$ rustc --version
dyld[18030]: Symbol not found: __ZN4llvm10PGOOptionsC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_S7_S7_NS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEENS0_9PGOActionENS0_11CSPGOActionEbb
  Referenced from: <EEB49284-2EAD-3371-9401-139E8557678B> /opt/homebrew/Cellar/rust/1.77.2_1/lib/librustc_driver-3dc17bded25d4e59.dylib
  Expected in:     <B0C4597F-D1E6-36D5-83FD-81D0ACE34F6C> /opt/homebrew/Cellar/llvm/18.1.4/lib/libLLVM.dylib
[1]    18030 abort      rustc --version

$ cargo install battop
error: process didn't exit successfully: `rustc -vV` (signal: 6, SIGABRT: process abort signal)
--- stderr
dyld[18302]: Symbol not found: __ZN4llvm10PGOOptionsC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_S7_S7_NS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEENS0_9PGOActionENS0_11CSPGOActionEbb
  Referenced from: <EEB49284-2EAD-3371-9401-139E8557678B> /opt/homebrew/Cellar/rust/1.77.2_1/lib/librustc_driver-3dc17bded25d4e59.dylib
  Expected in:     <B0C4597F-D1E6-36D5-83FD-81D0ACE34F6C> /opt/homebrew/Cellar/llvm/18.1.4/lib/libLLVM.dylib

Rust installed via brew:
$ brew list rust
/opt/homebrew/Cellar/rust/1.77.2_1/.bottle/etc/bash_completion.d/cargo
/opt/homebrew/Cellar/rust/1.77.2_1/bin/cargo
/opt/homebrew/Cellar/rust/1.77.2_1/bin/cargo-clippy
/opt/homebrew/Cellar/rust/1.77.2_1/bin/clippy-driver
/opt/homebrew/Cellar/rust/1.77.2_1/bin/rust-demangler
/opt/homebrew/Cellar/rust/1.77.2_1/bin/rust-gdb
/opt/homebrew/Cellar/rust/1.77.2_1/bin/rust-gdbgui
/opt/homebrew/Cellar/rust/1.77.2_1/bin/rust-lldb
/opt/homebrew/Cellar/rust/1.77.2_1/bin/rustc
/opt/homebrew/Cellar/rust/1.77.2_1/bin/rustdoc
/opt/homebrew/Cellar/rust/1.77.2_1/lib/librustc_driver-3dc17bded25d4e59.dylib
/opt/homebrew/Cellar/rust/1.77.2_1/lib/libstd-5b4c550f4b110959.dylib
/opt/homebrew/Cellar/rust/1.77.2_1/lib/rustlib/ (3233 files)
/opt/homebrew/Cellar/rust/1.77.2_1/libexec/rust-analyzer-proc-macro-srv
/opt/homebrew/Cellar/rust/1.77.2_1/share/doc/ (36165 files)
/opt/homebrew/Cellar/rust/1.77.2_1/share/man/ (38 files)
/opt/homebrew/Cellar/rust/1.77.2_1/share/zsh/site-functions/_cargo

### Steps

rustc --version
cargo install <anypackage>

### Version

```text
cargo 1.77.2
release: 1.77.2
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.2 system)
libcurl: 8.4.0 (sys:0.4.70+curl-8.5.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 14.3.1 [64-bit]
```

**Comment by weihanglo** [comment]
Do you have llvm@18 installed through homebrew?

It seems that the current `rust` homebrow formula [depends on llvm@17](https://github.com/Homebrew/homebrew-core/blob/588936e8585740559e5bfd5eaf247b495ffe50e4/Formula/r/rust.rb#L39) but not 18. I am not familiar of how dynamic linkage works in homebrew, though it seems like there is a conflict between them. You might need to uninstall llvm@18 to avoid that

You might want to [`brew install rustup-init`](https://formulae.brew.sh/formula/rustup-init) for a better toolchain experience.

Note that the Rust project has no control over how other system package managers handle rust releases. If you have an issue of a certain package manager, I'll recommend seeking helps from them. You could also install rust toolchain via rustup through the official installation method: <https://rustup.rs/>.

**Comment by beonic-rufus** [comment]
Right - okay cool, will close this issue. Homebrew will probably update the formulae

**Comment by beonic-rufus** [comment]
I had llvm 17 - but uninstalling and reinstall both rust and llvm appeared to resolve it.
