### ISSUE TITLE
Misleading error message when crate's root file is missing

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/cargo#1379]
I was just starting over on a Rust package, and removed all the files in the src directory. When I ran `cargo clean`, I got this message:

```
failed to parse manifest at `/path/to/package/Cargo.toml`

Caused by:
  either a [lib] or [[bin]] section must be present
```

I'd never seen this before and thought it must have been a new change to Cargo in the latest nightly. But after looking around at other packages I found that most Cargo manifest files did not explicitly include [lib] sections still. Eventually I realized it was because I'd removed `src/lib.rs`, and Cargo expects it to be present. The error message made it sound like something was missing in the manifest.

**Comment by steveklabnik** [comment]
Yes, in a certain sense, this is the correct error: it cannot find a lib or bin. That doesn't mean that we can't revise it, though.

**Comment by ye** [comment]
Yeah, after touching a `src/lib.rs` file. `cargo build` works. It looks like this is the line emitting this error https://github.com/rust-lang/cargo/blob/master/src/cargo/util/toml.rs#L120
