### ISSUE TITLE
[regression] `cargo vendor` keeps workspace inheritance for some things

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#13843]
### Problem

With 1.77.2, a vendored Cargo.toml might contain something like:
```
[lints.clippy.pedantic]
level = "warn"
priority = -1
```
instead of what's in the original crate (vendored via git):
```
[lints]
workspace = true
```

with 1.79.0-beta.1, you see what's in the original crate.

It happens with nightly-2024-04-28 but not nightly-2024-04-27, which would put the regression in the range c9392675917..b60a1555155. Edit: fixed the versions.

Presumably this could affect `cargo publish` too.

### Steps

1. `cargo new testcase; cd testcase`
2. add the following dependency to `Cargo.toml`: `neqo-common = { tag = "v0.7.5", git = "https://github.com/mozilla/neqo" }`
3. `cargo vendor vendoring`
4. Look at the file `vendoring/neqo-common/Cargo.toml`

**Comment by glandium** [comment]
Looks like it could be a regression from d5bc35d84454fd4653b5ffe546e86363803b0a1b

**Comment by epage** [comment]
@Muscraft unsure how I overlooked this.

Our options
- Inherit this during `prepare_for_publish`
- Don't differentiate between workspace and package source
- Use `original_toml` like you had proposed

As this is in beta, we will need to fix this soonish and do a beta backport.  Unsure how bad this will be for merge conflicts.  I wonder if we should take a very hacky route just for beta (like revert the change) to keep risk down.

**Comment by weihanglo** [comment]
* Beta backport is just merged <https://github.com/rust-lang/rust/pull/124647>. We'll have this fix in the next beta release tomorrow.
* I'll do a nightly update for <https://github.com/rust-lang/cargo/pull/13852> later today.

I believe this is resolved, so close. Thanks people.
