### ISSUE TITLE
Signal when a newer version is available?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1385]
So I had a dependency on `rustc-serialize = "0.2"`, and Cargo correctly did not upgrade to 0.3.x, per SemVer. Should it still have printed a warning or something, to make the developer aware that a newer version is available (that they might want to upgrade to) but was rejected by the dependency spec?

This possibly depend on what convention becomes recommended: http://users.rust-lang.org/t/should-be-used-for-cargo-dependencies/313

**Comment by killercup** [comment]
I would like to see something like `cargo outdated` that lists for which dependencies new versions are available (without actually updating).

I regularly use `npm outdated --depth=1` in my node projects. It shows

```plain
```

**Comment by alexcrichton** [comment]
I think @killercup's got a great idea, I'd love to see this as a new subcommand as it may be too noisy on `cargo build` (plus requires network to figure this out).

**Comment by SimonSapin** [comment]
Or perhaps it could be part of `cargo update`?

**Comment by alexcrichton** [comment]
Perhaps yes, although I'd prefer that it'd be a separate flag to `cargo update`. Projects that know that they don't want the latest-and-greatest, for example, may find it annoying.

**Comment by dguo** [comment]
I would really like to see this feature. [npm](https://docs.npmjs.com/cli/outdated), [pip](https://pip.pypa.io/en/latest/reference/pip_list.html#cmdoption-o), [RubyGems](http://guides.rubygems.org/command-reference/#gem-outdated), and [Bower](http://bower.io/docs/api/#list) all have some way of listing outdated packages. Would this require a RFC?

**Comment by icorderi** [comment]
+1 on `cargo outdated`

**Comment by kbknapp** [comment]
I'd love to see this as well, but would strongly prefer a separate subcommand. Maybe I'm just stating the obvious, but `cargo update --outdated` would look like its only updating outdated packages (even though that's just the default functionality anyways).

Plus a separate subcommand allows for further functionality. 

Maybe I'll play with trying to build this out this week.

**Comment by kbknapp** [comment]
I've got an initial implementation of [cargo outdated](https://github.com/kbknapp/cargo-outdated). I like the look of the `npm outdated` a little more, so perhaps soon I'll change the output to match.

**Comment by alexcrichton** [comment]
I believe `cargo-outdated` serves this quite nicely and with `cargo install` it should be easy to get!
