### ISSUE TITLE
cargo build/run unconditionally rebuilds the target

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#1386]
Since a recent cargo update ( I don't know which ), `cargo build` / `cargo run` rebuilds my project unconditionally every time. It doesn't rebuild the dependencies, only the target.

Reproduction:
```bash
cargo new foo && cd foo && cargo build && cargo build
```

I expect that this would only rebuild foo once, but instead, this is the output:
```
   Compiling foo v0.0.1 (...)
   Compiling foo v0.0.1 (...)
```

Cargo version: `cargo 0.0.1-pre-nightly (dd7c7bd 2015-03-04) (built 2015-03-04)`
Rustc version: `rustc 1.0.0-nightly (b0746ff19 2015-03-05) (built 2015-03-06)`
OS: `Linux 3.19.0-1-ARCH #1 SMP PREEMPT Mon Feb 9 07:08:20 CET 2015 x86_64 GNU/Linux`

**Comment by alexcrichton** [comment]
Unfortunately this is caused by https://github.com/rust-lang/rust/pull/23090, but hopefully that fix will land soon!

**Comment by hugoduncan** [comment]
Would rust-lang/rust#2309 also be causing unconditional rebuilds of dependencies with `paths` specified in `.cargo/config`?

**Comment by alexcrichton** [comment]
It would indeed!
