### ISSUE TITLE
assertion failed: edges.remove(&key)

### ISSUE THREAD

**Issue by fenollp** [rust-lang/cargo#13889]
### Problem

I'm working on my own `RUSTC_WRAPPER` and it may slow down some calls to `rustc` made by `cargo`. Toying with the amount of `--jobs=N`, I notice I can fail a `cargo` assertion: 
```shell
2024-05-09T07:46:34.9182036Z thread 'main' panicked at src/cargo/util/dependency_queue.rs:191:13:
2024-05-09T07:46:34.9183450Z assertion failed: edges.remove(&key)
2024-05-09T07:46:34.9184589Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-05-09T07:46:36.0109959Z ##[error]Process completed with exit code 101.
```

Now I'm not sure if I'm doing something wrong or if it's on `cargo`'s side?

### Notes

* the mentioned code: https://doc.rust-lang.org/beta/nightly-rustc/src/cargo/util/dependency_queue.rs.html#191
* the build logs https://productionresultssa6.blob.core.windows.net/actions-results/fe4adb8f-2924-4ee1-9d51-2ddc2c68553e/workflow-job-run-5d30e883-8d76-5db4-605e-068efef1550f/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-09T08%3A10%3A05Z&sig=eU4enoWXQZTBDKBXjwWMnbSXRC4rLMx1g3pJP0nBhC4%3D&sp=r&spr=https&sr=b&st=2024-05-09T08%3A00%3A00Z&sv=2021-12-02

### Version

```text
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 23.10 (mantic) [64-bit]
```

**Comment by weihanglo** [comment]
Could you share a minimal reproduction for this, and also a log without authentication to view? Without them it's a bit hard to come out with anything valuable.

**Comment by fenollp** [comment]
Ah well sorry about that link
* The failing GA job: https://github.com/fenollp/rustcbuildx/actions/runs/8998781512/job/24766171190?pr=35
* Its logs https://github.com/fenollp/rustcbuildx/suites/23560676757/logs?attempt=2
To reproduce pretty deterministically: on that branch `wip`, starting with commit `9b2587603` run 
```shell
# Needs docker up and running
jobs=8 ./hack/clis.sh cov clean
```

I'll try to reproduce with `jobs=N, N<8` to help with debugging..

**Comment by fenollp** [comment]
FYI since this clearly doesn't reproduce with `jobs=1`, this is surely a missed dependency issue on my end!
