### ISSUE TITLE
Add an easier way of running `rustc --explain`

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/cargo#13888]
### Problem

```rs
fn main() {
    hello
}
```
This errors with `E0425`. It would be nice if cargo offered a way to explain the error in depth!
```
error[E0425]: cannot find value `hello` in this scope
 --> src/main.rs:2:5
  |
2 |     hello
  |     ^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `tests` (bin "tests") due to 1 previous error
```
You can of course copy and paste the command but it would be nicer to not have to.

### Proposed Solution

You could run `cargo check --explain` that opens up the help page for the given error.

**Comment by weihanglo** [comment]
Are you proposing [`cargo --explain`](https://doc.rust-lang.org/nightly/cargo/commands/cargo.html#option-cargo---explain) without a given error code should just check the latest error we've got?

**Comment by dev-ardi** [comment]
More specifically, adding it to `check`, `build`, etc should do that if it encounters any explainable error.

Not sure what should happen for several errors.

**Comment by epage** [comment]
rustc has been exploring hyperlink support and having the error codes be a link to the relevant page seems the most useful.  You could immediately click the link without having to go back in your history to re-run the command and then avoid that entry in your history when you want to run without it.

**Comment by dev-ardi** [comment]
That would be even better indeed

**Comment by weihanglo** [comment]
@epage do you have any discussion we can link to? I think we can close this  in favor of that then.

**Comment by epage** [comment]
I'm not aware of a tracking issue for the unstable feature
- MCP: rust-lang/compiler-team#587
- Initial work: rust-lang/rust#107838 (which looks to implement what I suggested)
- Zulip thread: https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/Richer.20diagnostics.3F/near/430145899

**Comment by weihanglo** [comment]
Sounds good. Thanks and close in favor of those.

@dev-ardi feel free to join and discuss on Zulip :)
