### ISSUE TITLE
In `Cargo.toml` I missspelled "version" and it still worked, but after I corrected it I now get compile errors.

### ISSUE THREAD

**Issue by exo-cortex** [rust-lang/cargo#13918]
### Problem

The code is in this github repo: https://github.com/exo-cortex/simple_axum_button_response
In `Cargo.toml` I missspelled "version" in the line
```toml
tower-http = { verion = "0.4", features = ["fs"] }
```
Everything still worked fine and compiled without errors. 
But once I corrected the mistake my project now does not compile anymore. I don't completely understand what's happening here. While compiling cargo displayed that it compiled `tower-html v0.5.2` - so it somehow read the package name, but ignored the malformed version-statement. 

I fixed my problem with the newer version (that cargo somehow used), but It is problematic IMHO that cargo does not warn the user of a misspelled dependency version statement; I did not correctly state the version and it still installed *some* version. 
I don't think this is intended.

### Steps

1. git clone the repo at https://github.com/exo-cortex/simple_axum_button_response
2. run cargo build
3. correct the misspelled word "verion" in `Cargo.toml`
4. run cargo build again 
this should give you an errror.

### Possible Solution(s)

Check toml file integrity when running cargo commands and warn user.

**Comment by epage** [comment]
Cargo had a bug where a missing `version` was treated as `version = "*"`.  After a several year transition period for people to stop relying on the bug, we've fixed it in #13775 which will be released in 1.79

Closing as this appears to be resolved.  If there is a reason for us to keep this open, let us know.

btw you should have at least gotten the following (I do follow the reproduction steps)
```
warning: dependency (tower-http) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
warning: unused manifest key: dependencies.tower-http.verion
```

**Comment by weihanglo** [comment]
This is the other relevant issue tracking for typo correction for Cargo.toml: https://github.com/rust-lang/cargo/issues/9731

**Comment by exo-cortex** [comment]
@epage 
You're absolutely right! I somehow didn't see it, but it was there. Thank you.
