### ISSUE TITLE
$CARGO_HOME/.cargo/config.toml does not respect XDG specifications

### ISSUE THREAD

**Issue by DaniD3v** [rust-lang/cargo#13928]
### Problem

Title.

Cargo should not clutter my home directory. Data should go into $XDG_STATE_HOME and config files should be (read-only!) from $XDG_CONFIG_HOME

### Steps

1. cd
2. ls -a
3. be annoyed about the .cargo and .rustup folders

### Possible Solution(s)

Solution: changing the default paths and adding another path to this priority queue
![image](https://github.com/rust-lang/cargo/assets/124387056/8e31014c-9c27-4379-8991-f608bb92cb82)
I'd suggest we insert the XDG compliant paths above the current $CARGO_HOME/config.toml

The more difficult part about this is probably splitting the CARGO_HOME into 2 different paths.

There's 2 rust libraries implementing the XDG specifications:
directories-rs (cross-platform)
rust-xdg (linux-only)

This would not be a breaking change as you can still use the old location if there's already data there.
I assume this should only require changing a few paths. I could PR this myself if someone could pinpoint me to the code where the configs are read. I already did a repo-wide search but couldn't find anything referencing the path.

### Notes

Read the full XDG specifications here: `https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html`

This would also resolve #11267

### Version

```text
cargo 1.80.0-nightly (4de0094ac 2024-05-09)
release: 1.80.0-nightly
commit-hash: 4de0094ac78743d2c8ff682489e35c8a7cafe8e4
commit-date: 2024-05-09
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: NixOS 23.11.0 [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the report! The issue is probably a duplicate of <https://github.com/rust-lang/cargo/issues/1734>, and the proposed solution has been discussed in <https://internals.rust-lang.org/t/pre-rfc-split-cargo-home> (and still ongoing though a bit stale).

**Comment by DaniD3v** [comment]
oh looks like doing that is quite a bit more complicated than I originally thought. I'll close this issue
