### ISSUE TITLE
False positives in dead code warning

### ISSUE THREAD

**Issue by iajoiner** [rust-lang/cargo#13933]
### Problem

For some clearly used trait methods there can be dead code warnings.

### Steps

Need to make it reproducible without proprietary code. Hold on..

### Version

```text
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by iajoiner** [comment]
There are some weird Clippy issues after the 1.78.0 upgrade as well so maybe it will be a great idea to have a 1.78.1 release. :)

**Comment by ehuss** [comment]
I'm going to close since this needs to be filed over at https://github.com/rust-lang/rust/issues/new/choose. Also, this will be unactionable until there is a code example, so I suggest you hold off until you have some reproduction. Thanks!
