### ISSUE TITLE
Allow passing a `credentials.toml` file path as a CLI arg for `cargo login` and `cargo publish`

### ISSUE THREAD

**Issue by DeflateAwning** [rust-lang/cargo#13932]
### Problem

Publishing crates with multiple accounts is a common-enough practice. It would be nice if one could run `cargo publish --cred ~/account1/cargo_cred.toml` to use account1's credentials. 

This feature should be added for both `cargo login` and `cargo publish` (and any other subcommands I'm forgetting).

### Proposed Solution

Python's PyPI supports this functionality via the `--config <path>` arg (but `--config` is already in use for cargo). `--cred <path.toml>` is probably the next best option.

**Comment by epage** [comment]
We support [credentials from multiple sources](https://doc.rust-lang.org/cargo/reference/registry-authentication.html), not just `credentials.toml` and I think there is a preference for deprecating `cargo:token` as it stores the credential in plain text.

**Comment by DeflateAwning** [comment]
Good to know! Unless there's a solid plan and a deprecation date picked for removing `credentials.toml` support, I still think that there should be a way to pick the credential storage file via an arg. 

All those other methods seem very good once they're implemented, but they seem like a pain to get right, and a pain to make sure the right credentials are used for the job.

**Comment by epage** [comment]
>  Unless there's a solid plan and a deprecation date picked for removing credentials.toml support,

The plain text credential is all but deprecated.  Tote that deprecation is separate from removal.  This isn't so bad that we expect to break compatibility.  However, i see it unlikely for us to add new features specific to plain text token management.  The finishing of the deprecation is dependent on a documentation audit (and improving small workflow issues found along the way).

> All those other methods seem very good once they're implemented, but they seem like a pain to get right, and a pain to make sure the right credentials are used for the job.

We have other credential managers today.

**Comment by weihanglo** [comment]
See also <https://github.com/rust-lang/cargo/issues/13623> for some possible approaches we might want for de-emphasizing plain text login.

**Comment by weihanglo** [comment]
Since we tend to deprecate and discourage the usage, for me I wouldn't add more features for plaintext credentials. 

For implementing custom credential providers, the protocol accepts [additional arguments](https://doc.rust-lang.org/nightly/cargo/reference/credential-provider-protocol.html#login-request) so shouldn't be too complicated to roll out out something like `cargo login -- --cred <path>` by hands.

**Comment by ehuss** [comment]
Credentials like `token` are just regular config files. The `--config` CLI option should work to specify a file that has your token values.

However, as stated above, it is probably not a good idea to store your credentials in an unencrypted plain file.

**Comment by weihanglo** [comment]
Second. Close.
