### ISSUE TITLE
cargo-upgrade verbose option broken

### ISSUE THREAD

**Issue by sedan-cell** [rust-lang/cargo#13959]
### Problem

when running with `--verbose` no verbose output is printed and the command says to use `--verbose`.

```
> cargo upgrade --verbose
    Updating 'https://github.com/rust-lang/crates.io-index' index
    Checking MYCRATE's dependencies
note: Re-run with `--verbose` to show more dependencies
  latest: 20 packages
```

### Steps

1. run `cargo upgrade --verbose`
2. observe output

### Possible Solution(s)

unsure of the code fix, but verbose should print the actual verbose info and not a message to use verbose

### Version

```text
> cargo version --verbose
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: x86_64-pc-windows-msvc
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:Schannel)
os: Windows 10.0.22631 (Windows 11 Professional) [64-bit]
```

**Comment by epage** [comment]
`cargo upgrade` is not an official cargo command but comes from a third-party package, [cargo-edit](https://github.com/killercup/cargo-edit).  I'd recommend creating an issue there.

However, my guess is that the command is telling you that you need an extra level of verbosity to see the output (`--verbose --verbose`).

**Comment by sedan-cell** [comment]
@epage double flag works. i thought the whole `cargo-edit` suite was being merged into cargo itself which is why it was posted here. i opened an issue on their tracker though as requested.

**Comment by epage** [comment]
Yes, cargo-edit is being merged in but `cargo upgrade` has not been and will not be directly merged.  See https://github.com/rust-lang/cargo/issues/12425

cargo-edit hasn't been getting much activity because there isn't much activity to do.
