### ISSUE TITLE
`cargo build --release` SIGKILL:ed on OSX

### ISSUE THREAD

**Issue by sasq64** [rust-lang/cargo#13961]
### Problem

Suddenly, all my release builds fail with these type of error(s)
```
error: failed to run custom build command for `libc v0.2.155`

Caused by:
  process didn't exit successfully: `/Users/sasq/projects/rustplay/target/release/build/libc-8998c335a3ef8871/build-script-build` (signal: 9, SIGKILL: kill)
```

### Steps

Build any project (with build.rs or dependencies with build.rs) in release mode.

Since this is such a fundamental problem I assume there is some underlying difference in my system, but I don't know what.

### Possible Solution(s)

The failure is caused by the `build-script-build` binaries. They are instantly `SIGKILL`:ed when you try to execute them, indicating that OSX security finds some problem with them.

Comparing the binaries from debug and release builds we can see that;
```
$ file target/release/build/libc-8998c335a3ef8871/build-script-build
target/release/build/libc-8998c335a3ef8871/build-script-build: Mach-O executable arm64
$ file target/debug/build/libc-7c3fcac8659920ac/build-script-build
target/debug/build/libc-7c3fcac8659920ac/build-script-build: Mach-O 64-bit executable arm64
```

`Mach-O 64-bit` seems to be used by all other binaries in the system, maybe the 32-bit version is no longer supported?

So the question then becomes why build scripts are built in this format.

### Notes

Happens both on stable and nightly.

I have many extra targets installed used for embedded development, including other ARM targets.

### Version

```text
cargo 1.80.0-nightly (05364cb2f 2024-05-03)
release: 1.80.0-nightly
commit-hash: 05364cb2f61a2c2b091e061c1f42b207dfb5f81f
commit-date: 2024-05-03
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.4.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.2.0 [64-bit]
```

**Comment by sasq64** [comment]
Found the cause:

I had install `binutils` from homebrew and added it to my path. One of the tools their must have been picked up instead of the real one, which produced the older 'Mach-O' format.

I had built only debug builds for so long that I forgot I did this when the problem arose...

**Comment by sasq64** [comment]
Closing, sorry if I wasted anyones time (I suspect it could happen to others, but it's hard for cargo to protect against).

**Comment by sasq64** [comment]
FYI: hombrew binutils `strip` outputs 32-bit Mach-O, that was the issue.

**Comment by justinyaodu** [comment]
My build was still failing after uninstalling `binutils`, but it worked after I deleted the `target` directory. I assume some of the intermediate artifacts built with `binutils` were still cached.
