### ISSUE TITLE
`cargo fmt --all` from excluded sub-directory still checks parent workspace

### ISSUE THREAD

**Issue by dhardy** [rust-lang/cargo#13962]
### Problem

[Here](https://github.com/rust-random/rngs/pull/51/commits/061af2943f51207746917ea7d6d1d422e7eb9afc) I run tests on an `exclude`-d sub-directory, `benches`. CI kept failing until I removed the `--all` from `cargo fmt` due to issues with other workspace members, which *should not be checked from here*.

`Cargo.toml` looks like this:
```toml
[workspace]
members = [
    "rand_jitter",
    "rand_isaac",
    "rand_xorshift",
    "rand_xoshiro",
    "rand_hc",
]
exclude = [
    "benches",
]
resolver = "2"
```
Therefore, `cargo test -p benches` from the repo root fails (expected).

However, this succeeds:
```
$ cd benches/
$ cargo test -p rand_hc
   Compiling libc v0.2.155
```
This *should fail* since `benches` is, by explicit exclusion, not part of the parent workspace.

**Comment by newpavlov** [comment]
@weihanglo 
It's not only about `cargo fmt`, you also can run tests for packages in root workspace from an excluded crate directory. Adding `[workspace] members = ["."]` to excluded crates does not help.

**Comment by weihanglo** [comment]
`cargo fmt` is actually an external subcommand implemented in `rust-lang/rustfmt` repository. It has different behavior than `--all` in other built-in commands Cargo.
(note that `--all` is dep created and we favor `--workspace`).

Here is [the current implementation of `cargo fmt --all`](https://github.com/rust-lang/rustfmt/blob/d5f1200ed6a8e375f963e0c59a8bee45c0018c55/src/cargo-fmt/main.rs#L344-L346). And [here is a prior discussion](https://github.com/rust-lang/rustfmt/issues/5010) you might be interested.

Given this is a thing managed by [the Rustfmt team](https://www.rust-lang.org/governance/teams/dev-tools#team-rustfmt) an issue in Cargo, please find an existing issue and reach out to them for further discussions.

**Comment by dhardy** [comment]
Thanks for the explanations @weihanglo.

So I can `cd rand_distr` then do `cargo test -p num-traits` for example, running tests on Cargo's cached copy of `num-traits`. I hadn't expected this to work and it contributed to the confusion above, but otherwise this is likely unimportant.

Given the linked `rustfmt` issue, it sounds like they are uninterested in being compliant with the behaviour of other Cargo commands, so I guess this issue can be closed now.

**Comment by weihanglo** [comment]
Thanks for the understanding. Closing.
