### ISSUE TITLE
Incorrect formatting for git fetch 

### ISSUE THREAD

**Issue by kali** [rust-lang/cargo#13968]
### Problem

Problem appeared 2 days ago running CI against rust nightly for tract.

See: https://github.com/sonos/tract/actions/runs/9251978441/job/25448634660

Same CI is still working on both stable and beta.

### Steps

```
git clone https://github.com/sonos/tract
cd tract
CARGO_NET_GIT_FETCH_WITH_CLI=true cargo +nightly -vvv  test -p test-f16
    Updating crates.io index
    Updating git repository `https://github.com/kali/tflitec-rs.git`
     Running `git fetch --verbose --force --update-head-ok 'https://github.com/kali/tflitec-rs.git' '+b37d65a000000000000000000000000000000000:refs/commit/b37d65a000000000000000000000000000000000'`
POST git-upload-pack (102 bytes)
POST git-upload-pack (167 bytes)
fatal: remote error: upload-pack: not our ref b37d65a000000000000000000000000000000000
error: failed to get `tflitec` as a dependency of package `test-f16 v0.1.0 (/tract/test-rt/test-f16)`

Caused by:
  failed to load source for dependency `tflitec`

Caused by:
  Unable to update https://github.com/kali/tflitec-rs.git?rev=b37d65a

Caused by:
  failed to fetch into: /root/.cargo/git/db/tflitec-rs-2d4221cf6acd5dab

Caused by:
  process didn't exit successfully: `git fetch --verbose --force --update-head-ok 'https://github.com/kali/tflitec-rs.git' '+b37d65a000000000000000000000000000000000:refs/commit/b37d65a000000000000000000000000000000000'` (exit status: 128)
```

I had to run this on a clean docker container though. On my regular system some cache was masking the issue.

### Notes

Probably related to #13946 

See comment https://github.com/rust-lang/cargo/pull/13946#pullrequestreview-2070092191 maybe.

Issue appears with or without CARGO_NET_GIT_FETCH_WITH_CLI=true , but it makes it very visible as cargo will show git command line call.

**Comment by weihanglo** [comment]
My apologies. Forgot that libgit2 will zero-pad revisions. A fix is up: <https://github.com/rust-lang/cargo/pull/13969>.

**Comment by weihanglo** [comment]
The fix is now available on `nightly-2024-05-29` toolchain.
