### ISSUE TITLE
Cargo Tree: New format string parameter

### ISSUE THREAD

**Issue by timbess** [rust-lang/cargo#14009]
### Problem

[rules_rust is using](https://github.com/bazelbuild/rules_rust/blob/e3f6258b1e1660652ae044f01c6dac074f9fb206/crate_universe/src/metadata.rs#L530-L558) `cargo tree` to query the dependency graph and create an equivalent internal graph of dependencies per architecture it's configured to build for. The issue I observed with their current implementation is that they were querying all build dependencies when querying for each target architecture, which caused host architecture only transitive build deps to be added to graph of the target architecture.

I tried querying with just `build` edges, but then we don't get to see the `normal` transitive deps under the `build` deps so we can't actually build a dependency graph of all the build deps accurately using filtering. Next I went to look through the format parameters and saw there wasn't really a way for me to extract what platform it's building for.

### Proposed Solution

Add a `platform` format string parameter to `cargo tree`.

### Notes

I have a draft PR https://github.com/rust-lang/cargo/pull/14008. There may be a better way to do this, open to suggestions if so.

**Comment by epage** [comment]
> [rules_rust is using](https://github.com/bazelbuild/rules_rust/blob/e3f6258b1e1660652ae044f01c6dac074f9fb206/crate_universe/src/metadata.rs#L530-L558) cargo tree to query the dependency graph and create an equivalent internal graph of dependencies per architecture it's configured to build for.

Less serious: Seeing comments like this makes me feel like we should have a `rust_version % N` to select one of several variations of our text output.

More serious: This being for programmatic use has me less sympathetic to extending `cargo tree`.  We should be focusing on what humans reading the output need, both in terms for understanding and in terms of what can overload them (in output, CLI flags, etc).

**Comment by timbess** [comment]
I would argue that the `format` and `prefix` options are already not for humans. The output of `cargo tree --manifest-path Cargo.toml --edges=normal,build,dev --prefix=depth --format='|{p}|{f}|{lib}' --color=never --workspace --target=x86_64-pc-windows-msvc` on my project is:

```
3|dirs-sys-next v0.1.2||dirs_sys_next
4|winapi v0.3.9|consoleapi,errhandlingapi,fileapi,handleapi,iphlpapi,knownfolders,libloaderapi,minwinbase,minwindef,namedpipeapi,ntdef,ntstatus,objbase,processenv,processthreadsapi,shlobj,std,synchapi,sysinfoapi,winbase,wincon,winerror,winnt,winreg,winsock2,winuser,ws2def,ws2ipdef,ws2tcpip|winapi
2|encoding_rs v0.8.32|alloc,default|encoding_rs
3|cfg-if v1.0.0||cfg_if
2|flate2 v1.0.30|any_impl,default,miniz_oxide,rust_backend|flate2
3|crc32fast v1.4.2|default,std|crc32fast
4|cfg-if v1.0.0||cfg_if
3|miniz_oxide v0.7.3|with-alloc|miniz_oxide
4|adler v1.0.2||adler
```

That said it seems like they're trying to work around this issue https://github.com/rust-lang/cargo/issues/9863 by switching to `cargo tree` so I imagine that fixing either would be fine so long as there's _a_ way to do it.

**Comment by timbess** [comment]
After reading [some more about the issue](https://github.com/bazelbuild/rules_rust/issues/2212) on the `rules_rust` side, I think the solution of adding a `--host-triple` would be a better solution, so I'm going to close this.
