### ISSUE TITLE
Update feature docs for no implicit features in 2024

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#14011]
See https://doc.rust-lang.org/cargo/reference/features.html

**Comment by linyihai** [comment]
I was going to update the documentation and wasn't sure if it was a good time. 

If anyone is confused by this behavior, please leave a comment here and I will try to update it

**Comment by epage** [comment]
We need to come to a conclusion on #14016 first.

**Comment by epage** [comment]
As the feature has been reverted, I'm closing this
