### ISSUE TITLE
Build scripts only get `RUSTFLAGS` when not passing `--target`

### ISSUE THREAD

**Issue by nilfit** [rust-lang/cargo#14046]
### Problem

When passing `RUSTFLAGS=-Dwarnings` to upgrade compiler warnings to errors, the flags are sometimes present in the `rustc` invocation for the build script and sometimes not.

### Steps

1. Set up a crate that produces a warning when compiling the build script.
2. `RUSTFLAGS=-Dwarnings cargo check -v` produces an error for the build script. `-Dwarnings` is visible on the the `Running` command line for the build script. 
3. `RUSTFLAGS=-Dwarnings cargo check -v --target x86_64-unknown-linux-gnu` produces a warning for the build script. `-Dwarnings` is absent from the command line for the build script and present on the command line for the main build.

I expected step 3 to behave like step 2.

### Notes

- Replacing `RUSTFLAGS` with `CARGO_ENCODED_RUSTFLAGS` gave the same results.
- Setting the `build.target` in `.cargo/config.toml` has the same effect as passing `--target`.
- Reproducible with `cargo 1.81.0-nightly (b1feb75d0 2024-06-07)`.

### Version

```text
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux [64-bit]
```

**Comment by weihanglo** [comment]
Your observation exactly matches what is documented in [`build.rustflags`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#buildrustflags) section in The Cargo Book:

> If the `--target` flag (or [build.target](https://doc.rust-lang.org/nightly/cargo/reference/config.html#buildtarget)) is used, then the flags will only be passed to the compiler for the target. Things being built for the host, such as build scripts or proc macros, will not receive the args.

This is a behavior people relying on under some circumstances, such as when [using address sanitizer](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#build-scripts-and-procedural-macros). One alternative solution to this is `target-applies-to-host` unstable feature. See the tracking issue: <https://github.com/rust-lang/cargo/issues/9453>.

Besides it being a behavior by-design (but not great), is there any issue other than `target-applies-to-host` trying to resolve?

**Comment by nilfit** [comment]
> Your observation exactly matches what is documented in build.rustflags section in The Cargo Book

Oh, I hadn't seen that.

> is there any issue other than target-applies-to-host trying to resolve?

I'm trying to consistently apply deny warnings in CI across a cortex-m embedded codebase. Removing cross-compilation-by-default (through `.cargo/config.toml`) to get the desired warnings-to-errors behavior would break the build.

I only see `target-applies-to-host` solving the confusion, but the related [`host-config`](https://github.com/rust-lang/cargo/issues/9452) seems like it would allow the configuration I'm looking for.

While I would love to have an easier way to do all this than through `RUSTFLAGS`, https://github.com/rust-lang/cargo/issues/8424 covers that better.

Then everything in this issue is covered by others (I guess that makes it a duplicate). Thanks for clearing things up!
