### ISSUE TITLE
Cargo cannot resolve a dependency using a tag in github

### ISSUE THREAD

**Issue by tsal** [rust-lang/cargo#14077]
### Problem

I'm attempting to use a specific tagged version of an as-yet-unreleased version of a package, using a tag in the github repo. Strangely, the URL given in the error message takes me ... directly to the tag in the repository without issue?

### Steps

1. Create a new project
2. Add dependency for bevy using `git = https://github.com/bevyengine/bevy, tag = 0.14.0-rc2` as the dependency configuration
3. try to `cargo build`

get the following:

```
error: failed to get `bevy` as a dependency of package ... {redacted}

Caused by:
  failed to load source for dependency `bevy`

Caused by:
  Unable to update https://github.com/bevyengine/bevy?tag=0.14.0-rc.2

Caused by:
  failed to find tag `0.14.0-rc.2`

Caused by:
  reference 'refs/remotes/origin/tags/0.14.0-rc.2' not found; class=Reference (4); code=NotFound (-3)
```

### Possible Solution(s)

I'm not entirely sure, but I suspect there's something with the github API that is different than cargo is expecting around tag refs? I've never had to use this before, so I'm not 100% sure but it seems like a good place to start.

### Version

```text
1.80.0-nightly (4de0094ac 2024-05-09)
release: 1.80.0-nightly
commit-hash: 4de0094ac78743d2c8ff682489e35c8a7cafe8e4
commit-date: 2024-05-09
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.4.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.4.1 [64-bit]
```

**Comment by weihanglo** [comment]
The tag `0.14.0-rc2` doesn't exist at the time of writing on that GitHub repository, so that should be an expected behavior.

<img width="705" alt="image" src="https://github.com/rust-lang/cargo/assets/14314532/6acc76b9-432c-42fc-8dce-a974b8938af2">

**Comment by tsal** [comment]
`https://github.com/bevyengine/bevy/tree/v0.14.0-rc.2`

**Comment by Muscraft** [comment]
It looks like you are missing the `v` from the front of the tag you are looking for. At least, that is what it looks like in the output from your original comment. 

I tried adding `bevy` as a dep with what was specified and it failed:
```toml
bevy = { git = "https://github.com/bevyengine/bevy", tag = "0.14.0-rc.2"}
```
But adding the `v` to the front worked:
```toml
bevy = { git = "https://github.com/bevyengine/bevy", tag = "v0.14.0-rc.2"

**Comment by weihanglo** [comment]
Close as it was a typo not a bug. Thanks.
