### ISSUE TITLE
Document how to run specific tests

### ISSUE THREAD

**Issue by arthurprs** [rust-lang/cargo#1407]
I found out on IRC that I could use ```cargo test test_name``` to run specific tests (actually any tests containing the text).

Despite being a very useful feature I couldn't find it documented anywhere.

**Comment by alexcrichton** [comment]
Cargo doesn't actually support running specific tests, instead we just pass the `test_name` argument to the test binary itself, and then *rust's* test runner uses that as a filter. This is also documented in `cargo test -h`, however, so I'm curious where you're thinking this documentation needs to go?

**Comment by arthurprs** [comment]
In my opinion it should be stated in Cargo Guide or FAQ.

I didn't realize it was at the ```cargo test -h``` though, it may be enough.

**Comment by nathanl** [comment]
@arthurprs For what it's worth, I just googled `rust run specific tests` and found the answer here. :smile:

**Comment by lucaszanella** [comment]
This thread is old. 

Now

`cargo test test_function_name`

simply works!
