### ISSUE TITLE
Tracking Issue for merging `cargo-information`/`cargo info` to Cargo

### ISSUE THREAD

**Issue by Rustin170506** [rust-lang/cargo#14081]
### Summary

Rust Internals: https://internals.rust-lang.org/t/feedback-on-cargo-info-to-prepare-it-for-merging/20369
Original issue: https://github.com/rust-lang/cargo/issues/948
Implementation: TBD
Documentation: TBD

We developed 'cargo-information' as a solution for #948

**Features:**

- Works with all registries that are compatible with Cargo
- Fetches and displays basic package information (name, version, owners, etc.)
- Shows package dependencies and their versions
- Provides information about package features

And in the last six months, we have released 8 versions and had 3,428 downloads. At the same time, we have covered almost all the features it needs. So I think it is a good time to merge it back into Cargo and prove it to all Cargo users.

### Unresolved Issues

* [ ] We want to report some crates.io metrics in this command as well, we will do that after we merge it back into Cargo See: https://github.com/hi-rustin/cargo-information/issues/20 
* [ ] After the public dependency feature is stable, we should consider what dependencies we want to show in this command. See: https://github.com/hi-rustin/cargo-information/issues/138

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by epage** [comment]
Curious, what is the role of this tracking issue.  I'm assuming we can't have this feature be unstable and instead must insta-stable it like `cargo add` and `cargo remove`.  At which point, we are just tracking the command being merged which the original issue can handle.  Likely, the tasks listed are not blockers.  This is a UX heavy command and we have a lot of flexibility of adding / removing functionality.

**Comment by weihanglo** [comment]
As a hub connecting to other issues? That said, we can create a label `Command-info` for this purpose.
