### ISSUE TITLE
`maybe a missing crate` with `workspace` when `edition` is not declared

### ISSUE THREAD

**Issue by bukowa** [rust-lang/cargo#14108]
## Problem

```sh
$ cargo build
   Compiling package3 v0.1.0 (\root\package3)
error[E0432]: unresolved import `ignore`                                                                                                                                     
 --> package3\src\tree.rs:4:5
  |
4 | use ignore::{DirEntry, Error, Walk, WalkBuilder};
  |     ^^^^^^ maybe a missing crate `ignore`?
  |
  = help: consider adding `extern crate ignore` to use the `ignore` crate

error[E0432]: unresolved import `serde`
```

### Steps

```toml
# /root/Cargo.toml
[workspace]
resolver = "2"
members = [
    "package1", "package2", "package3",
]
```

```toml
# /root/package3
[package]
name = "package3"
version = "0.1.0"

[dependencies]
ignore = "0.4.22"
serde = { version = "1.0.203", features = ["derive"] }
```

### Working Solution(s)

Add `edition = "2021"`
```toml
# /root/package3
[package]
name = "package3"
version = "0.1.0"
edition = "2021"
````

### Notes

Better information would be helpful.

### Version

```text
cargo 1.79.0 (ffa9cf99a 2024-06-03)
```

**Comment by bukowa** [comment]
https://github.com/rust-lang/cargo/issues/14023

**Comment by weihanglo** [comment]
```
   = help: consider adding `extern crate ignore` to use the `ignore` crate
```

The rust compiler already gave a help message, so people do get a hint for fixing that compile error.

Note that if a package was created by a newer cargo, the `package.edition` should be set to the latest stable edition (2021 as of now). I would consider missing `edition` as a deliberate choice and won't bother users with any further warning. See

* https://github.com/rust-lang/cargo/pull/13505#issuecomment-1975051432
* https://github.com/rust-lang/cargo/pull/13533

You'll get a warning if `package.rust-version` is set as a version greather than 1.30.

**Comment by epage** [comment]
Is that output complete? In #13505 (1.78), we warn on unset edition.

**Comment by epage** [comment]
Also, this explicitly calls out that a workspace was used but this should behave the same without it. Can you confirm if there is something different with workspaces?

**Comment by epage** [comment]
Rustc giving a hint to specify a new edition would be worth considering but that would be for their repo, and their decision to make.

**Comment by weihanglo** [comment]
I saw what went wrong. `rust_version` is None here because it doesn't take the current toolchain version into account.

https://github.com/rust-lang/cargo/blob/ac8c6aba13c07e8e94940a3c465f1f52294832ea/src/cargo/util/toml/mod.rs#L1133

There are some ways to fix this:

* Warn if both `rust-version` and `edition` are missing
* Make `package.rust_version` aware of toolchain version during `to_real_manifest`

@epage which do you like?

**Comment by bukowa** [comment]
> Is that output complete? In #13505 (1.78), we warn on unset edition.

https://github.com/bukowa/rustrover-compilebug/tree/8d684228275dacc9d6a6befc53bcf192c3a27b41
```bash
$ cargo build
   Compiling package2 v0.1.0 (C:\Users\buk\RustroverProjects\rustrover-compilebug\package2)
error[E0432]: unresolved import `serde`                                                                                                                                                        
 --> package2\src\lib.rs:1:5
  |
1 | use serde::Serialize;
  |     ^^^^^ maybe a missing crate `serde`?
  |
  = help: consider adding `extern crate serde` to use the `serde` crate

For more information about this error, try `rustc --explain E0432`.                                                                                                                            
error: could not compile `package2` (lib) due to 1 previous error
```
```bash
$ cargo version
cargo 1.79.0 (ffa9cf99a 2024-06-03)
```

**Comment by weihanglo** [comment]
> I saw what went wrong. `rust_version` is None here because it doesn't take the current toolchain version into account.
> 
> https://github.com/rust-lang/cargo/blob/ac8c6aba13c07e8e94940a3c465f1f52294832ea/src/cargo/util/toml/mod.rs#L1133
> 
> There are some ways to fix this:
> 
>     * Warn if both `rust-version` and `edition` are missing
> 
>     * Make `package.rust_version` aware of toolchain version during `to_real_manifest`
> 
> 
> @epage which do you like?

Probably the first one? People only get the warning on 1.78 or later, so it is sufficent for Cargo to know that they are already on a newer toolchain. They can alwasy set the `package.rust-version` field to silent it.

**Comment by bukowa** [comment]
> > @epage which do you like?

As a new user playing around with rust and workspaces, not understanding how everything fits together, I would expect a message that allows me to track down why this issue arises.

**Comment by bukowa** [comment]
Thank you by looking at the PR this is much more helpful.
