### ISSUE TITLE
Add third alternative to module file naming convention

### ISSUE THREAD

**Issue by TRI99ERED** [rust-lang/cargo#14120]
Currently modules support the following file locations:
- src/module/mod.rs
- src/module.rs

I suggest to add a third alternative:
- src/module/module.rs

# Rational
Originally modules could only be declared with "src/module/mod.rs", which lead to multiple different files having the same name, which may be confusing.
Later on "src/module.rs" alternative was introduced, to combat that same issue, but it brought its own: now main module file is no longer close to its submodules and is instead another entry alongside the directory of the same name.
That's why I suggest a third alternative (opt-in, like the other two) "src/module/module.rs", which addresses both issues neatly.

# Known caveats
It is possible, that some existing project has a structure as follows:
```
└── src
      ├── module
      │       └── module.rs
      ├── module.rs
      └── main.rs
```
With this structure (or a similar one using mod.rs convention) it would lead to compiler ambiguity. For this reason it's necessary, that compiler stops checking for "src/module/module.rs" (as a main file for the module) after it already found either "src/module.rs" or "src/module/mod.rs". That way the change should be backwards compatible.

**Comment by weihanglo** [comment]
Cargo is not able to control the module resolution. It's rustc that does it. Please create an issue in rust-lang/rust repository instead. Thank you.

**Comment by epage** [comment]
I also assume this would be at the level of an RFC / MCP  for rustc and it might be good to get early feedback on the idea at https://internals.rust-lang.org/

**Comment by ehuss** [comment]
Yes, language changes need to go through the [RFC process](https://github.com/rust-lang/rfcs/?tab=readme-ov-file#when-you-need-to-follow-this-process) which would start by starting a discussion in https://internals.rust-lang.org/. Closing as not a cargo issue.
