### ISSUE TITLE
Some git dependencies(image, rust-sdl2) failed to clone.

### ISSUE THREAD

**Issue by Potpourri** [rust-lang/cargo#1414]
```
Unable to update https://github.com/PistonDevelopers/image#92a5cec8

Caused by:
  failed to clone into: /home/travis/.cargo/git/db/image-f4d4ca6613133df7

Caused by:
  [-1] an unknown error occurred
```
cargo -V: `cargo 0.0.1-pre-nightly (66849de 2015-03-10) (built 2015-03-11)`
In cargo builded from latest source I get the same error.

**Comment by alexcrichton** [comment]
I can reproduce as well. I think that this may be a bug in an older version of libgit2. I'll try to update it.

**Comment by CraZySacX** [comment]
I was getting this earlier as well.  I can't recall the exact error and I can't reproduce it now, but it was [23] authentication required....  with cargo build --verbose

**Comment by Potpourri** [comment]
Very strange, today error just disappeared!

**Comment by alexcrichton** [comment]
This was closed in a recent update to libgit2 I believe, but feel free to reopen if it reproduces!
