### ISSUE TITLE
Cargo update dependencies failed case by execute git command failed

### ISSUE THREAD

**Issue by Gitfz810** [rust-lang/cargo#14152]
#### Description
Cargo add personal repo failed.

<img width="1098" alt="image" src="https://github.com/rust-lang/cargo/assets/38970394/e627d732-d107-4333-a504-4f7f94e4eb2a">

It seems that cargo use git command only read the global configuration.

### Steps

1. `cargo new foo && cd foo` 
2. `git config url."ssh://git@<personal git address>".insteadOf "https://<personal git address>"`
3. `mkdir .cargo`
4. 
```sh
cat > .cargo/config.toml << EOF
[net]
git-fetch-with-cli = true
EOF
 ```
5. `cargo add <repo name> --git <https://<personal git address>/<repo name>.git`

### Possible Solution(s)

I don't know how to fix it, but for now I add git global configuration to fix it.
`git config --global url."ssh://git@<personal git address>".insteadOf "https://<personal git address>"`

### Version

```text
$ cargo version --verbose
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 7.86.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 13.2.0 [64-bit]
```

**Comment by weihanglo** [comment]
> It seems that cargo use git command only read the global configuration.

That is kinda expected. One can argue that git CLI invocation should respect project local configurations. However, git dependencies cache in Cargo is global. Respecting local configurations may pollute the global cache with unexpected data or format, leading the cache to be in an unusable state.

Here is the code that [spawning git is spawn at the directory of the repository-to-fetch](https://github.com/rust-lang/cargo/blob/471287ffed354a468114caa5c72db97da6b6ddfb/src/cargo/sources/git/utils.rs#L1209-L1220).

Therefore, I propose to the team to close this.

@rustbot label +S-propose-to-close -S-needs-team-input

**Comment by epage** [comment]
I second this.
