### ISSUE TITLE
Generated .gitignore should only ignore top-level target directory

### ISSUE THREAD

**Issue by bluetech** [rust-lang/cargo#1415]
If my `src/` directory happens to contain a file named "target", it should not be ignored. So I think the .gitignore should be changed to say `/target` rather than just `target`.

**Comment by alexcrichton** [comment]
Ah sorry this flew under my radar! I [commented on #1488](https://github.com/rust-lang/cargo/pull/1488#issuecomment-90133579), but I think that we actually want to continue just saying `target` and `Cargo.lock` for now.
