### ISSUE TITLE
Example code in build-script.md should use var_os() instead of var()

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1416]
I believe that just using `env::var()` instead of `env::var_os()` will stop paths in environmental variables which might not be valid UTF8 (but are valid paths) from being used. Not sure if cargo will allow non-utf8 paths, but it seems like it should. I think it'd be good to use `var_os()` if the only usage of the variable is to make a `Path`.

**Comment by daboross** [comment]
I'm not entirely sure Cargo will actually run on paths which aren't valid UTF8, but if it will this would be a good change to make.

**Comment by steveklabnik** [comment]
```
$ cd src/doc/
$ git grep "var_os"
$ 
```

looks like this has been fixed.
