### ISSUE TITLE
Cargo recompiles everything when rerunning a failed build or install

### ISSUE THREAD

**Issue by DamianPlayz1** [rust-lang/cargo#14179]
### Problem

If I'm running a build and the build or install fails, and I fix the problem that caused the build to fail and rerun the command to install the packages I want to install, cargo will rebuild all the dependencies and the package which is an inconvenience if the build or install fails at the end

### Proposed Solution

Save the dependencies and built files to a tmp file like yay does

**Comment by weihanglo** [comment]
When submitting a report, please include the version information. The output of `cargo -vV` should suffice. Also, if possible, providing [a minimal, complete, and verifiable example][mcve] could help things move forward.

[mcve]: https://stackoverflow.com/help/mcve

**Comment by weihanglo** [comment]
If you ran `cargo install`, it should output a temporary path for further investigation of the build failure. Such as

```
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo v0.80.0`, intermediate artifacts can be found at `/var/folders/h5/wtddncln7xl_r9k9f35njsg40000gr/T/cargo-installkTOMU4`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Note the “intermediate artifacts can be found at <path>” part.
