### ISSUE TITLE
Memory leak/spike during doc-tests

### ISSUE THREAD

**Issue by madonuko** [rust-lang/cargo#14190]
### Problem

Both `cargo test` and `cargo test --doc` use around `(1 + n)` GB of memory during doc-test linking, where `n` is the number of doc-tests. This behaviour can be seen here:

https://github.com/rust-lang/cargo/assets/48051237/4a61db72-bd7d-4f22-9985-85914b832fda

The code in question is https://github.com/rpm-rs/rpmspec-rs (master branch or commit `1e57d1d`)

### Steps

```
git clone https://github.com/rpm-rs/rpmspec-rs --depth 1
cd rpmspec-rs
cargo test #--doc
```
Try removing one of the doc-tests. On my machine, for every doc-test I remove, the memory usage drops by 1 GB.

### Things I have already tried
- `cargo clean`, problem persists
- Use another linker, but #14189 
- Changing doc-tests to normal `#[test]`s, memory issue disappears entirely

### Extra notes
Notice the memory usage comes from `ld` (see the video above). However, this only happens with doc-tests; this never happens under `cargo check`, `cargo build` and normal tests (i.e. `cargo test` excluding doc-tests).

### Version

```text
cargo 1.79.0 (ffa9cf99a 2024-06-03)
release: 1.79.0
commit-hash: ffa9cf99a594e59032757403d4c780b46dc2c43a
commit-date: 2024-06-03
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ultramarine Linux 40.0.0 (lostumbrella) [64-bit]
```

**Comment by weihanglo** [comment]
This is not a memory "leak". Under the current architecture, each doctest compiles to a separate binary on-the-fly, so there are N linking happening when compile N doctests.

See some other issues:

* <https://github.com/rust-lang/cargo/issues/12916>
* <https://github.com/rust-lang/cargo/issues/12912>

We've already come up with some other ideas to resolve this. See:

* <https://github.com/rust-lang/testing-devex-team/issues/5>
* <https://github.com/rust-lang/rust/issues/124853>

Close in favor of those issues. Thank you.
