### ISSUE TITLE
Building a binary with cargo named `build` fails with `Is a directory (os error 21)`

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1424]
Whenever I create a project named simply `build` (any other name works), it fails building with `An unknown error occurred`. When run with `--verbose`, it fails with `Is a directory (os error 21)`.

If the project is just a library project without a binary, the compilation runs normally.

Shell commands/output:
```
$ cargo new --bin build
$ cd build
$ cargo build
   Compiling build v0.0.1 (file:///home/daboross/build)
Build failed, waiting for other jobs to finish...
An unknown error occurred

To learn more, run the command again with --verbose.
$ cargo build --verbose
   Compiling build v0.0.1 (file:///home/daboross/build)
Is a directory (os error 21)
```

**Comment by steveklabnik** [comment]
I'm assuming this is becuase of `build.rs`, but a better error is certainly a good thing here.

**Comment by alexcrichton** [comment]
This is actually because we auto-make a directory in the output folder called `build`. If you create a project called `examples`, `deps`, or `native` it will likely also cause problems. I think I'd just like to improve the error message in these caess.

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/cargo/issues/1618 which I think is the solution we want to take.
