### ISSUE TITLE
`cargo bench` fails when running `unittest`s

### ISSUE THREAD

**Issue by abrassel** [rust-lang/cargo#14247]
### Problem

I have a benchmark set up in my cargo project. When I run `cargo bench` I expect for it to execute this benchmark.

Instead, it begins executing my unit tests and then fails with a SIGKILL. However, running `cargo test` passes.

```
❯ cargo bench criterion_benchmark
   Compiling <> v1.7.0 (<>)
    Finished `bench` profile [optimized] target(s) in 3.19s
     Running unittests src/lib.rs (target/release/deps/<>_lib-799808ee04af93f2)
error: bench failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `<path/to/debug/target> criterion_benchmark --bench` (signal: 9, SIGKILL: kill)
```

### Steps

1. create `cargo bench` target. I used the fibonacci example from the Criterion quick start page.
2. run `cargo bench`
3. observe unit test failures.

### Possible Solution(s)

I was curious if there might be an issue on my side so I checked out the Criterion repo. All tests and benchmarks work fine.

It seems as though something about the way my tests are executing does not play well with `cargo bench`. 
I may be able to work around this by bypassing unittest execution, but even executing `cargo bench -- <test_name>` does not help.

### Version

```text
cargo 1.80.0-nightly (4de0094ac 2024-05-09)
release: 1.80.0-nightly
commit-hash: 4de0094ac78743d2c8ff682489e35c8a7cafe8e4
commit-date: 2024-05-09
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.5.0 [64-bit]
```
```

**Comment by weihanglo** [comment]
Just setup a new package and followed [Getting Started](https://bheisler.github.io/criterion.rs/book/getting_started.html#getting-started). No issue found. Could you provide a complete minimal reproducer? Either a Git repo, or uploading a zip of your package.

**Comment by weihanglo** [comment]
Saw SIGKILL so was wondering something like <https://github.com/rust-lang/cargo/issues/13961#issuecomment-2129450166>. Looks like it only happens on this specific package but not other so may be irrelevant.

**Comment by abrassel** [comment]
I'll try to repro. My crate is proprietary so I'll have to make a repro. Can you give me more information about how I can debug this or what step of the build is failing?

**Comment by weihanglo** [comment]
See <https://github.com/rust-lang/cargo/issues/8961> and <https://github.com/rust-lang/rust/issues/79857>. Check if it is OOM-killed.

**Comment by ehuss** [comment]
On macOS, you can view the system logs to see if the `memory_pressure` system is activating, or any other unusual things. You can do that with the `Console` app (just click "start" to start recording), or in the CLI with the `log show` command. The `log` command has a bunch of options like `--last 1m` to just get the last minute, or filtering predicates.

**Comment by abrassel** [comment]
Some updates. `CARGO_BUILD_JOBS=1 cargo bench` does not resolve the issue. @ehuss I ran `Console` with `cargo bench` and only saw this error: `unable to get a dev_t for store 1795162192.`

**Comment by abrassel** [comment]
Root caused - my company laptop was blocking the executable.
