### ISSUE TITLE
`cargo clean` does not clean downloaded crates

### ISSUE THREAD

**Issue by carbotaniuman** [rust-lang/cargo#14256]
### Problem

I tried to build a crate, but ran into an issue where a dependency was corrupted. I then tried to `cargo clean` the project, thinking that would fix it, but it didn't. I had to nuke my WSL and reinstall it to get the crate to build, losing a lot of time and effort.

### Possible Solution(s)

`cargo clean` should also apply to dependencies, and not just the direct project.

**Comment by weihanglo** [comment]
See <https://doc.rust-lang.org/nightly/cargo/guide/cargo-home.html#directories> and [unstable `-Zgc` feature](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#manual-garbage-collection-with-cargo-clean) if you want to manually remove source caches for now.

Assuming “downloaded crates” refer to downloaded source code resides under `$CARGO_HOME/registry/{crate,src}`, the design is tracked in <https://github.com/rust-lang/cargo/issues/13060>. Going to close this in favor of that. Please comment below if there is any reason keeping this issue open. Thank you.

**Comment by carbotaniuman** [comment]
Thanks for the pointers - I wish I'd have found those links sooner... I'm not sure my issue is directly related to the `gc` issue though - I would like to clean my dependencies entirely, not gc them depending on cache age.

**Comment by epage** [comment]
Unlike some other build systems, dependency source is kept in a global cache while `cargo clean` is focused on your local cache.  Think of the GC feature as a way for managing the global cache.  The interface for doing so is not yet defined.
