### ISSUE TITLE
Cargo does not seem to always propagate `cfg(clippy)` correctly to dependencies

### ISSUE THREAD

**Issue by rmalmain** [rust-lang/cargo#14251]
### Problem

When using path dependencies in `Cargo.toml`, cargo does not seem to propagate the special `cfg(clippy)` to dependencies correctly.
A minimized example [is available here](https://github.com/rmalmain/cargo-bug).

### Steps

In the [minimized example repo](https://github.com/rmalmain/cargo-bug), run `cargo clippy --features feature1,feature2`. As far as I understand, it should not trigger a compiler error.

### Version

```text
cargo 1.81.0-nightly (154fdac39 2024-07-07)
release: 1.81.0-nightly
commit-hash: 154fdac39ae9629954e19e9986fd2cf2cdd8d964
commit-date: 2024-07-07
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.8.0-DEV (sys:0.4.73+curl-8.8.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux Rolling Release [64-bit]
```

**Comment by epage** [comment]
`cargo clippy` is managed in the clippy repo and they control how the cfg gets passed to cargo.  I can't seem to transfer this to that repo so could you instead open this at https://github.com/rust-lang/rust-clippy

**Comment by rmalmain** [comment]
Thank you for your answer, and sorry for opening this issue in the wrong place.
I'll re-open the issue there.
