### ISSUE TITLE
Cargo run strips all `--`

### ISSUE THREAD

**Issue by jhelwig** [rust-lang/cargo#1426]
The usage string of "cargo run" suggests that any arguments after an optional `--` will be preserved and passed to the compiled binary:
```
Usage:
    cargo run [options] [--] [<args>...]
```

Instead it appears that any `--` will be stripped from the arguments passed along:
```
% cargo run 1 2 3 4 5
     Running `target/debug/signing-participants 1 2 3 4 5`
Value for algorithms: SHA256,RIPEMD160
Value for input: 1
Value for output: 2
Value for datestring: 3
Value for organizer: 4
Value for title: 5
% cargo run 1 2 3 -- 4 5
     Running `target/debug/signing-participants 1 2 3 4 5`
Value for algorithms: SHA256,RIPEMD160
Value for input: 1
Value for output: 2
Value for datestring: 3
Value for organizer: 4
Value for title: 5
% cargo run -- 1 2 3 -- 4 5
     Running `target/debug/signing-participants 1 2 3 4 5`
Value for algorithms: SHA256,RIPEMD160
Value for input: 1
Value for output: 2
Value for datestring: 3
Value for organizer: 4
Value for title: 5
```

In the second & third `cargo run` invocations above, I would expect the values for `organizer`, and `title` to have been `--` and `4` respectively if the `--` after the first one were preserved, so this appears to be more than just a display issue with the "Running ...." line.

**Comment by alexcrichton** [comment]
cc @BurntSushi

**Comment by jhelwig** [comment]
Forgot to initially include the version: `cargo 0.0.1-pre-nightly (07cd618 2015-03-12) (built 2015-03-13)`.

**Comment by BurntSushi** [comment]
I think this is fallout from fixing https://github.com/rust-lang/cargo/issues/1377#issuecomment-77486428 --- I already have a bug filed for this I think: https://github.com/docopt/docopt.rs/issues/111

I'll see what I can do to come up with fixing it. It seems like the `--` should only be removed when it matches something inside of a usage pattern. (But only one should be removed.)

**Comment by BurntSushi** [comment]
I think this should be fixed in https://github.com/docopt/docopt.rs/commit/ef83ed425d8b19f3998eb7a4107ec7b02cd92abf (on crates.io in `0.6.69`).

**Comment by alexcrichton** [comment]
Thanks @BurntSushi!
