### ISSUE TITLE
`CACHEDIR.TAG` not created if `rust-analyzer` runs before `cargo build`

### ISSUE THREAD

**Issue by problame** [rust-lang/cargo#14281]
### Problem

After checking out a Rust/Cargo project from Git, if `rust-analyzer` is run before the first `cargo build`, the `target/CACHEDIR.TAG` is missing

### Steps

1. Check out some default Rust/Cargo project that has `target` directory excluded from Git.
2. Open in a VSCode `code .` that has rust-analyzer extension installed
3. Wait a bit until `target/analyzer/CACHEDIR.TAG` is created
4. `cargo build` => `cargo build` not creating `target/CACHEDIR.TAG`

### Possible Solution(s)

~~Revert https://github.com/rust-lang/cargo/pull/13132/files~~

### Notes

I verified that this reproduces on both macOS and Linux.

### Version

```text
cargo 1.79.0 (ffa9cf99a 2024-06-03)
release: 1.79.0
commit-hash: ffa9cf99a594e59032757403d4c780b46dc2c43a
commit-date: 2024-06-03
host: aarch64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Debian 11.0.0 (bullseye) [64-bit]
```
```

**Comment by weihanglo** [comment]
Where did you configure `target/analyzer/CACHEDIR.TAG`?
The directory doesn't seem to be created when trying to reproduce it with Rust Analyzer v0.3.2037.

Could you give a complete reproducer like

* Which repo you cloned and run
* The version of the rust-analyzer extension

**Comment by weihanglo** [comment]
Relevant issues:

* <https://github.com/rust-lang/cargo/issues/12441>

**Comment by problame** [comment]
> Where did you configure target/analyzer/CACHEDIR.TAG?

Hm, I configured `target/analyzer` in vscode

```
...
    "rust-analyzer.server.extraEnv": {
        "CARGO_TARGET_DIR": "target/analyzer"
    },
    "rust-analyzer.check.extraArgs": [
        "--target-dir=target/analyzer"
    ],
...
```

So, I guess we can dedupe this into #12441

**Comment by weihanglo** [comment]
Yeah that seems like a dup. I am going to close this.
Would you mind sharing ideas in #12441 about why `CACHEDIR.TAG` is critical in this case, and why a separate target dir is needed? We can discuss there.
