### ISSUE TITLE
mention release.toml in the documentation

### ISSUE THREAD

**Issue by szabgab** [rust-lang/cargo#14289]
### Problem

There are more than 500 crates that have a `release.toml` file in the root of their git repository.
As far as I can tell it is not mentioned anywhere in the documentation.

There are also 2 crates with `.release.toml` (leading dot).

### Proposed Solution

Mention it in the documentation explaining what fields can it have.

**Comment by szabgab** [comment]
As further search show it seems to be used by [cargo-release](https://github.com/crate-ci/cargo-release/) so maybe it is not relevant here.

**Comment by epage** [comment]
Yes, that is for a cargo plugin. As this isn't relevant to cargo itself, I'm going to close this.
