### ISSUE TITLE
SCCACHE not caches same crate for different component

### ISSUE THREAD

**Issue by soloturn** [rust-lang/cargo#14313]
### Problem

am using

     CARGO_TARGET_DIR=/tmp/mytarget  RUSTC_WRAPPER=sccache cargo ... 

for 2 components, on linux. the cache works quite well when compiling a component again. but when compiling the second component it fails. both comonents have approximately 600 crates, most of them same version. so download into CARGO_HOME is done only one time for 95% of the crates. compile is 2 times 600, 100% cache miss.

### Steps

``` 
❯ rm -rf ~/.cargo/
❯ rm -rf ~/.cache/sccache/
❯ RUSTUP_TOOLCHAIN=stable RUSTFLAGS="-C link-arg=-fuse-ld=mold" CARGO_TARGET_DIR=/tmp/mytarget RUSTC_WRAPPER=sccache cargo vendor 
  Downloaded 628 crates (108.5 MB) in 2m 14s (largest was `windows` at 11.8 MB)
❯ RUSTUP_TOOLCHAIN=stable RUSTFLAGS="-C link-arg=-fuse-ld=mold" CARGO_TARGET_DIR=/tmp/mytarget RUSTC_WRAPPER=sccache cargo build --release --frozen --offline


``` 

during compile one can check the cache state
`` 
❯ sccache --show-stats
Compile requests                     86
Compile requests executed            51
Cache hits                            0
Cache misses                         45
Cache misses (Rust)                  45

``` 


### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

_No response_

**Comment by epage** [comment]
As expressed in other threads, this is not a Cargo bug or feature request but a support request for a third-party tool, sccache.

Please either reach out to sccache through their means or the wider Rust community at https://users.rust-lang.org/

**Comment by soloturn** [comment]
this is a cargo flag, would be strange if this would not be in cargo then.

**Comment by epage** [comment]
Its a cargo flag that allows you to plug third-party programs into Cargo. What those third-party programs do is not up to Cargo which is the intent of a flag like this.
