### ISSUE TITLE
Cargo vendor regression for git sources containing `exclude = ["build.rs"]`

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#14348]
### Problem

In Rust 1.79 and older releases, `cargo vendor` used to work for crates that have build scripts applying only to their source repo, and not published to crates.io. An example of such a crate is https://github.com/dtolnay/cxx/blob/1.0.124/macro/Cargo.toml#L8. The build script was correctly omitted from being vendored.

Since Rust 1.80, Cargo still does not vendor the build script, but now it inserts `build = "build.rs"` into the vendored Cargo.toml, which causes compilation of the vendored sources to fail.

### Steps

Create an empty project with this Cargo manifest:

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
cxxbridge-macro = { git = "https://github.com/dtolnay/cxx", tag = "1.0.124" }
```

```console
$ mkdir .cargo
$ cargo vendor > .cargo/config.toml
$ cargo check
...
   Compiling cxxbridge-macro v1.0.124 (https://github.com/dtolnay/cxx?tag=1.0.124#afd4aa3f)
error: couldn't read /path/to/vendor/vendor/cxxbridge-macro/build.rs: No such file or directory (os error 2)

error: could not compile `cxxbridge-macro` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### Possible Solution(s)

Do not inject `build = "build.rs"` into the vendored manifest if build.rs is not being vendored.

### Notes

Bisects to https://github.com/rust-lang/cargo/pull/13713/commits/1e6047763d72edf5dfaee52e1c2305b94d0b7ccc.

**Comment by epage** [comment]
cxx-bridge-macro has an inferred `build.rs`

https://github.com/dtolnay/cxx/blob/master/macro%2FCargo.toml

We cover a lot of these cases for `build.rs` for package
https://github.com/rust-lang/cargo/blob/fa646583675d7c140482bd906145c71b7fb4fc2b/tests/testsuite/package.rs#L3909

But only had minimal tests for `cargo vendor`

**Comment by epage** [comment]
We are using a `PathSource` to list the files to copy for vendor

https://github.com/rust-lang/cargo/blob/fa646583675d7c140482bd906145c71b7fb4fc2b/src/cargo/ops/vendor.rs#L222

but only vendoring the normlalized git `Cargo.toml`

https://github.com/rust-lang/cargo/blob/fa646583675d7c140482bd906145c71b7fb4fc2b/src/cargo/ops/vendor.rs#L363

This is not the first time we've been bitten by `cargo vendor` being almost but not quite like `cargo package`

https://github.com/rust-lang/cargo/blob/fa646583675d7c140482bd906145c71b7fb4fc2b/src/cargo/ops/vendor.rs#L356

While we might want to do a minimal change for backporting, we should evaluate packaging sources to fully unify these so we stop having these problems.

**Comment by weihanglo** [comment]
Cargo flavored UI test for the situation of excluding build script.

<details><summary>Details</summary>
<p>

```rust
#[cargo_test]
fn dont_copy_excluded_build_script_for_git_dep() {
    let git = git::new("git_dep", |p| {
        p.file(
            "Cargo.toml", 
            r#"
                [package]
                name = "git_dep"
                edition = "2021"
                exclude = ["build.rs"]
            "#,
        )
            .file("src/lib.rs", "")
            .file("build.rs", "fn main() {}")
    });

    let p = project()
        .file(
            "Cargo.toml",
            &format!(
                r#"
                    [package]
                    name = "foo"
                    edition = "2021"

                    [dependencies]
                    git_dep = {{ git = '{}' }}
                "#,
                git.url()
            ),
        )
        .file("src/lib.rs", "")
        .build();

    let output = p
        .cargo("vendor --respect-source-config")
        .exec_with_output()
        .unwrap();

    // Before 1.80.0 `package.build` expected to be false
    // After cargo#13713 it normalized Carg.toml before copying source from git repo.
    // Taht make `package.build=["build.rs"] get into Cargo.toml.
    //
    // While the behavior of vendoring a git source is not well-defined,
    // this is considered a regression in 1.80.0
    //
    // See cargo#14348 for more.
    assert_e2e().eq(
        p.read_file("vendor/git_dep/Cargo.toml"),
        str![[r##"
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite `path` dependencies
# to registry (e.g., crates.io) dependencies.
#
# If you are reading this file be aware that the original Cargo.toml
# will likely look very different (and much more reasonable).
# See Cargo.toml.orig for the original contents.

bin = []
example = []
test = []
bench = []

[package]
edition = "2021"
name = "git_dep"
build = "build.rs"
exclude = ["build.rs"]
autobins = false
autoexamples = false
autotests = false
autobenches = false
readme = false

[lib]
name = "git_dep"
path = "src/lib.rs"

"##]],
    );

    let output = String::from_utf8(output.stdout).unwrap();
    p.change_file(".cargo/config.toml", &output);

    // TODO: this should success when we fix cargo#14348.
    p.cargo("check")
        .with_status(101)
        .with_stderr_data(
            str![[r#"
[COMPILING] git_dep v0.0.0 ([ROOTURL]/git_dep#[..])
[ERROR] couldn't read [ROOT]/foo/vendor/git_dep/build.rs: [NOT_FOUND]

[ERROR] could not compile `git_dep` (build script) due to 1 previous error

"#]]
        )
        .run();
}
```

</p>
</details> 

I am checking if there is any regression beyond build scripts.

**Comment by epage** [comment]
We have `cargo package` tests that would be good models, testing every build target type. We likely don't need to cover implicit vs explicit as well.

**Comment by epage** [comment]
#14368 backports this to 1.81
