### ISSUE TITLE
downloaded rust, but cargo and rustc dont work

### ISSUE THREAD

**Issue by yoyoxnd** [rust-lang/cargo#14349]
### Problem

I needed rustc to install maturin. After finding how to download it on android arm v7, i retried the command. Only, i discovered rust is downloaded, bit rustc and cargo dont work. Here is a screenshot of the /.cargo/bin
![Screenshot_20240803_171715_Termux](https://github.com/user-attachments/assets/4564e015-b8ed-4354-808a-742e5932309a)

### Steps

1. Download rust for android armv7 on termux with everything default
2. Try to use cargo or rustc

### Possible Solution(s)

Give a way to download cargo and rustc separately

### Version

```text
Latest rust version
Cargo not installed
```

**Comment by epage** [comment]
> Download rust for android armv7 on termux with everything default

How are you installing it?

If I'm reading this correctly, android armv7 seems to be "tier 2 without host tools" (with cargo being a "host tool"), see https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-without-host-tools

**Comment by yoyoxnd** [comment]
It say the full libtary is supported
![Screenshot_20240805_175203_Mull](https://github.com/user-attachments/assets/20771044-3dcf-4c9d-a8ad-a94350df3dcd)

**Comment by epage** [comment]
I believe  "Tier 2 without host tools" means you can cross-compile but not run cargo or rustc. The std column is meant to highlight you get all of std and not just core.

As this an unsupported target for cargo, I'm closing this. If there is a reason this  should be open, let us know!
