### ISSUE TITLE
`carge metadata` error on MacOS 12 (x86_64)

### ISSUE THREAD

**Issue by daeho-ro** [rust-lang/cargo#14387]
### Problem

Tried to build a python package `maturin` on MacOS 12 (x86_64) but it is failed.
- https://github.com/PyO3/maturin/issues/2166

Error:
```
cargo metadata --manifest-path Cargo.toml --format-version 1 --locked
```

Can anyone help to figure why this happen? Thanks,

### Steps

1. `git clone https://github.com/PyO3/maturin.git`
2. `cd maturin`
3. `git checkout tags/v1.7.0 -b temp`
4. `cargo metadata --manifest-path Cargo.toml --format-version 1 --locked`
5. error: `cargo metadata --manifest-path Cargo.toml --format-version 1 --locked` failed with code -6

### Version

```text
1.79.0
```

**Comment by weihanglo** [comment]
Could you provide some information for helping the investigation:

* The complete reproduction steps. Note that you provide a `git clone` without pinning to a commit. That may introduce uncertainty when reproducing it.
* The actual errro output you got.
* The way you installed the Rust toolchain. And where is the `cargo` executable located.

**Comment by workingjubilee** [comment]
Latest commit to maturin is https://github.com/PyO3/maturin/commit/dd301e1fc141a6d00cf4a5ae8f0f8d7f352892ad

**Comment by daeho-ro** [comment]
@weihanglo I have updated the steps. rust is installed through `homebrew`,
```
brew install rust
```
and the location looks like `/usr/local/Cellar/rust`.

**Comment by daeho-ro** [comment]
On the same condition but 1.81 looks like working and so please ignore this.
