### ISSUE TITLE
Update snaphots.txt.

### ISSUE THREAD

**Issue by o01eg** [rust-lang/cargo#1438]
The cargo version from snapshot.txt doesn't support `rustc-link-search` and `rustc-link-lib` from https://github.com/rust-lang/cargo/pull/1402 so it cann't use new `gcc-rs` that output new parameters.
This causes linked error with `miniz` library from `flate2-rs`:
https://gist.github.com/o01eg/69f4ce3527b6f2a1ae03#file-build-snapshot-cargo-log
If I use local `cargo 0.0.1-pre (f841530 2015-03-19) (built 2015-03-21)` compilation successed:
https://gist.github.com/o01eg/69f4ce3527b6f2a1ae03#file-build-local-cargo-log

**Comment by alexcrichton** [comment]
Thanks for the report! Cargo builds with a snapshot of Rust as well as Cargo though, so this'll get taken care of during the next rust upgrade.
