### ISSUE TITLE
Can't fetch repository with a non-default ssh port?

### ISSUE THREAD

**Issue by chengchangwu** [rust-lang/cargo#1439]
I can git clone a priviate repository on bitbucket, but cannot clone it with cargo build
>    git clone git@bitbucket.org:another_project/rtforth.git

But cargo build --verbose give the following message:

> failed to parse manifest at `/home/my_name/git/my_project/Cargo.toml`
> Caused by:
>   invalid url `ssh://git@bitbucket.org:another_project/rtforth.git`: invalid port number

The corresponding lines in Cargo.toml are
> [dependencies.rtforth]
> git = "ssh://git@bitbucket.org:another_project/rtforth.git"

**Comment by alexcrichton** [comment]
I think the url needs to look like `ssh://bitbucket.org/another_project/rtforth.git` (no colon in the middle). The default username for git-over-ssh is also `git` so you should be able to leave that off.

**Comment by chengchangwu** [comment]
No colon in the middle! Thanks!
I tried ssh://bitbucket.org/another_project/rtforth.git, doesn't work.
But ssh://git@bitbucket.org/another_project/rtforth.git with username git did work.

**Comment by alexcrichton** [comment]
Ah ok, looks like it worked though, thanks for the issue!
