### ISSUE TITLE
`cargo info` requires login

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#14409]
### Problem

Running `cargo info foo` seems to require a login to crates.io. I would not expect a simple information command to require authentication (or for those with a hardware token, a hardware key) to access it.

### Steps

1. Set up config.toml with:
```toml
[registry]
global-credential-providers = ["false"]
```
2. Run `cargo info syn`
3. See that it fails:
```
    Updating crates.io index
error: credential provider `false` failed action `get`

Caused by:
  failed to deserialize hello

Caused by:
  EOF while parsing a value at line 1 column 0
```

### Possible Solution(s)

I'm guessing this is because of the call to `try_list_owners`. I do not think `cargo info` should be trying to access API endpoints that require authentication.

### Version

```text
commit-hash: ff6df29857a5fc5f6bb0b9da8436cb501ee5894c
```

**Comment by Rustin170506** [comment]
@rustbot claim

I will take a look.

**Comment by Rustin170506** [comment]
I can reproduce it.

**Comment by Rustin170506** [comment]
> I do not think `cargo info` should be trying to access API endpoints that require authentication.

From the current design, if we can access the owner list, then we will display it; otherwise, it will skip the missing token error.

I think the bug from here:
https://github.com/rust-lang/cargo/blob/c76c8fd9aadff705336d348676d87b15a86b50ce/src/cargo/ops/registry/info/mod.rs#L239

We only checked the missing token error, maybe we should ignore all errors here.

The reason we introduced this information is that sometimes knowing who maintained the crate should be helpful.

**Comment by ehuss** [comment]
> We only checked the missing token error, maybe we should ignore all errors here.

It's not an issue of checking for errors. Credentials can pop up requests for passwords, biometrics, or hardware keys. I do not think it would be good if `cargo info` pops up a password request every time you try to use it.

AFAIK, the [`owners list`](https://doc.rust-lang.org/nightly/cargo/reference/registry-web-api.html#owners-list) API endpoint does not require authentication on crates.io. Does the call to `registry()` require the `Operation::Read` entitlement?

**Comment by Rustin170506** [comment]
> It's not an issue of checking for errors. Credentials can pop up requests for passwords, biometrics, or hardware keys. I do not think it would be good if `cargo info` pops up a password request every time you try to use it.

I see. I didn't consider that. You are right. It doesn't make sense at all.



> AFAIK, the [`owners list`](https://doc.rust-lang.org/nightly/cargo/reference/registry-web-api.html#owners-list) API endpoint does not require authentication on crates.io. Does the call to `registry()` require the `Operation::Read` entitlement?

Good point. The `owners list` API from crates.io does not require any authentication.

Yes, we passed the 'Operation::Read' entitlement. However, I found that even if we do not pass it, the 'crates-io' crate will still require us to pass a token.

I believe that whenever we send a request, we simply pass `Auth::Authorized` to the req function.
https://github.com/rust-lang/cargo/blob/2d1728088fa5214ec3b8a472cf7361840aab91f9/crates/crates-io/lib.rs#L388


I will dig a little deeper to see why we are forcing it.

**Comment by Rustin170506** [comment]
Since this commit https://github.com/rust-lang/cargo/commit/0c25226b35447a51918d5a17ba62a36b109757fe, authentication is required for this API.

**Comment by Rustin170506** [comment]
I guess we shouldn't "fix" this problem because our registry specification states that this API requires authentication.

So there are two ways to fix it:
1. Add a special case for crates.io.
2. Remove this feature at all.

@ehuss @epage What do you think?

**Comment by epage** [comment]
Let's just remove it for now and we can always re-evaluate it later.

**Comment by Rustin170506** [comment]
> Let's just remove it for now and we can always re-evaluate it later.

I agree, I will go head to remove it tomorrow.
