### ISSUE TITLE
`cargo test` produces `Too many open files` on NixOS when using multiple integration tests

### ISSUE THREAD

**Issue by wvffle** [rust-lang/cargo#14437]
### Problem

Hi!

Recently I switched to a new machine running NixOS. I've used the same configuration as on the previous machine but with slight modifications. However. When I started working on a project that I've been working on on a previous machine, it turned out, that I cannot run `cargo test` successfully.  

The compilation of integration tests (multiple files) always fails with a `Too many open files` error on random `.rlib` or `.rmeta` file either during compilation or during linking. On my previous machine it compiled just fine.

- `cargo test`: [cargo-test.log](https://github.com/user-attachments/files/16691817/cargo-test.log)
- `strace cargo test`: [strace-full.log](https://github.com/user-attachments/files/16691792/strace-full.log)
- `strace -e open,close,openat cargo test`: [strace.log](https://github.com/user-attachments/files/16691782/strace.log)

What did help was to change the extension of all integration test files but one, compile, change the extension back to `.rs` for another file and repeat until all tests are renamed and compiled. But making bigger changes to the codebase means that I have to recompile all of the integration tests again.

I also tried to compile only one crate at the time, but it was taking too much time with all of the dependencies of the project. 

Currently the only way to mitigate it for me is to put all the tests into unit tests, as they seem to work fine.

### Steps

1. Clone https://github.com/wvffle/nixos-rust-too-many-open-files/tree/master
2. enter dev shell with `nix develop`
3. run `cargo test`

Note that the repro, has unused dependencies imported in the `tests/common/mod.rs`. When I remove them, I can compile just fine. But if they are imported (even if unused) the compilation fails. 

### Notes

I've tried rust 1.75, 1.80 and 1.82.0-nightly but all versions fail the same way. 

The `ulimit -n` was initially set to `1024`. I've tried to set it higher but that didn't work either. I've even raised the hard and soft limits in PAM using this configuration, but that didn't help also:
```nix
  systemd.extraConfig = "DefaultLimitNOFILE=1048576";
  security.pam.loginLimits = [{
    domain = "*";
    item = "nofile";
    type = "-";
    value = "1048576";
  }];

```

Tried linking using mold, no change.

### Version

```text
cargo 1.82.0-nightly (0d8d22f83 2024-08-08)
release: 1.82.0-nightly
commit-hash: 0d8d22f83b066503f6b2b755925197e959e58b4f
commit-date: 2024-08-08
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/3.3.1)
ssl: OpenSSL 3.3.1 4 Jun 2024
os: NixOS 24.11.0 [64-bit]
```

**Comment by the8472** [comment]
Your strace calls don't cover child processes, you need to use `-ff` for that. The error seems to occur in rustc.

> The ulimit -n was initially set to 1024. I've tried to set it higher but that didn't work either.

Do you mean that increasing the limit failed or that increasing the limit didn't help?

**Comment by campbellcole** [comment]
I'm having a very similar issue but it is not exclusive to tests. I've increased `ulimit -n` to 1073741816 and it still happens. Importantly, I am using [impermanence](https://github.com/nix-community/impermanence) and mounting [`/` in a tmpfs](https://elis.nu/blog/2020/05/nixos-tmpfs-as-root/). Both `.cargo` and my project (including `target/`) are within an persistence path which is mounted using `fuse`. The `strace` output from a fresh compile contains hundreds of individual logs but the quantity from an incremental build (which still unconditionally fails) is much more manageable.

`strace -ffe open,close,openat cargo test`: [strace.tar.gz](https://github.com/user-attachments/files/16806055/strace.tar.gz)

**Comment by the8472** [comment]
>  are within an persistence path which is mounted using fuse.

It's possible that the fuse server then is sending this error code and you need to bump its file limit.

**Comment by campbellcole** [comment]
That's just what impermanence does. I believe it uses bind mounts for any persisted locations outside of the home directory. I checked and it doesn't seem like there's any built-in way for forcing home directory children from being bindmounted instead of using `bindfs`. I haven't noticed any performance issues with using fuse besides this error appearing when compiling Rust projects. I'll try to trick impermanence into using a bind mount and see how that goes.

**Comment by wvffle** [comment]
@the8472 here is the  strace with ff:

`strace -ffe open,close,openat cargo test`: [strace-ff.log](https://github.com/user-attachments/files/16829525/strace-full-ff.log)

**Comment by the8472** [comment]
Grepping through that log I don't find any `EMFILE` or `many open files` match. Use `-Z` to get only failing syscalls and then see which one is failing with that code.

**Comment by wvffle** [comment]
> I was able to fix this issue by using bind mounts instead of bindfs. For anyone who happens to be encountering this issue, move everything from `home.persistence."/nix/persist/home/USERNAME".*` to `environment.persistence."/nix/persist".users.USERNAME.*`.

@campbellcole I managed to compile my project when using symlink instead of bindfs:

```diff
  home.persistence."/persist/home/${config.home.username}" = {
    allowOther = true;
    directories = [
-      "workspace"
-      ".cargo"
+      {
+        directory = "workspace";
+        method = "symlink";
+      }
+      {
+        directory = ".cargo";
+        method = "symlink";
+      }
    ];
  };

```

**Comment by the8472** [comment]
That suggests that the FUSE server process is running into the file limit or emitting the code for some other reason. I.e. it's not a rust process that's exhausting its own limit. If it's the ulimit then you have to raise that of the server. If it's some other limitation then you'll have to file a bug with them. Or don't run Rust on FUSE.

**Comment by wvffle** [comment]
I think we can close this issue in favor of https://github.com/nix-community/impermanence/issues/206
