### ISSUE TITLE
Unable to cargo build with custom source registry when no access to static.crates.io

### ISSUE THREAD

**Issue by lawrenceching** [rust-lang/cargo#14443]
### Problem

I'm trying to build rust project in an internal network that without access to crates.io.
And fetch dependencies from an internal mirror registry.

But the `cargo build` failed:
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server (Failed to connect to static.crates.io port 443 after 0 ms: Couldn't connect to server)

Here is the <project>/.cargo/config.toml
```
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
```

A create a simple Rust project and reproduced this issue in GitHub Action:
https://github.com/lawrenceching/hello-rust/actions/runs/10511488341/job/29122560049

By overriding the /etc/hosts, I simulated the network environment without external access.
```
127.0.0.1 index.crates.io
127.0.0.1 static.crates.io
```

It seems cargo didn't full respect to the custom source registry and had hard dependency to static.crates.io

### Steps

1. Disable network access to crates.io
we can simulate it by overriding the /etc/hosts
```
127.0.0.1 index.crates.io
127.0.0.1 static.crates.io
```

3. Set mirror source registry
```
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
```
4. cargo build

### Version

```text
cargo 1.80.1 (376290515 2024-07-16)
release: 1.80.1
commit-hash: 37629051518c3df9ac2c1744589362a02ecafa99
commit-date: 2024-07-16
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Debian 12.0.0 [64-bit]
```

**Comment by ehuss** [comment]
The mirror at https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git has a `config.json` file with the line:

```
  "dl": "https://static.crates.io/crates",
```

This tells cargo where to download the `.crate` files. If you do not want to download crate files from crates.io, then the mirror needs to change that file so that it points to a different host which contains a copy of all of the `.crate` files.

**Comment by weihanglo** [comment]
See https://github.com/tuna/issues/issues/941

Closing as TUNA mirror seems intended to mirror index only . Thank you.
