### ISSUE TITLE
Document having only `src/bin/*.rs` binaries is valid

### ISSUE THREAD

**Issue by nekomachi-touge** [rust-lang/cargo#14463]
### Problem

I found the following section of the cargo book could make readers think they must provide `src/main.rs`.

https://github.com/rust-lang/cargo/blob/59ecb11a298f0c3740216220361024cf05ed5b5a/src/doc/src/reference/cargo-targets.md?plain=1#L30-L34

However, it is also valid to have only `src/bin/*.rs` binaries and not to have `src/main.rs`.  
I believe clarifying this situation on the book will help readers when arranging codes for binaries.

### Proposed Solution

Changing the section like below should work:
```
Binary targets are executable programs that can be run after being compiled. 
The default binary filename is `src/main.rs`, which defaults to the name of 
the package. Additionally one or more binaries are stored in the [`src/bin/`
 directory][package layout]. In this case the default binary `src/main.rs` 
is not required. The settings for each binary can be [customized] in the
`[[bin]]` tables in `Cargo.toml`.
```

**Comment by nekomachi-touge** [comment]
@Dnts1 looks like you posted your comment in a wrong issue.

**Comment by epage** [comment]
Thanks for providing this feedback on the confusion you had!  It looks like the suggested change is the addition of

> n this case the default binary `src/main.rs`  is not required.

It feels odd to call out that a default is not required, that is generally the case for a default.

For brainstorming purposes, another approach is something like
```
Binary targets are executable programs that can be run after being compiled. 
A binary's source can be `src/main.rs` and/or stored in the  [`src/bin/` 
directory][package layout].  For `src/main.rs`, the default binary name is the package name. The settings for each binary can be [customized] 
in the `[[bin]]` tables in `Cargo.toml`. 
```

**Comment by nekomachi-touge** [comment]
@epage Thank you for the quick response!

I support your fix.
Using `and/or` make the section much clearer than my take, and also stating `*.rs` are sources sounds more natural than the original text.
Maybe we need to make sure the text is wrapped at 80 characters though.

I'm considering making a PR after waiting feedbacks for a couple of days.

**Comment by nekomachi-touge** [comment]
Since no one seems to submit another proposal, I’m going to make a PR based on the @epage ‘s text to keep this issue from being stale.
