### ISSUE TITLE
Adding workspace profiles to the member's manifest at `cargo package`

### ISSUE THREAD

**Issue by dalance** [rust-lang/cargo#14470]
### Problem

`[profile.*]` can be added only to the root `Cargo.toml` in workspace.
But `cargo package` at the each member doesn't add the profiles into the `Cargo.toml` in crate package.
As a result, 

* `cargo build --release` or `cargo install --path ..` at the local environment uses the profiles
* `cargo install ..` through crates.io doesn't use the profiles

For example, https://crates.io/crates/veryl requires the following profile to avoid https://github.com/rust-lang/rust/issues/129776.
In this case, `cargo install ..` through crates.io will take too long time because the profile is not affected.

```
[profile.release]
codegen-units = 1
```

### Proposed Solution

I think adding workspace profiles to the member's manifest at `cargo package` is reasonable.
This change will reduce the behaviour difference between `cargo build --release` and `cargo install`.

**Comment by epage** [comment]
The underlying need seems to be the same as #8264 and one of the proposed solutions is copying the profiles.  I'm going to close in favor of that.  If there is a reason for us to re-open this, let us know!
