### ISSUE TITLE
cargo build cache is invalidated.

### ISSUE THREAD

**Issue by jm-observer** [rust-lang/cargo#14485]
### Problem

In a Windows environment, using Docker for cross-compilation can cause some of the compilation cache to become invalid.

### Steps

1. run command like this: docker run --rm -it -v D:\git\rathole:/root/src  rust_aarch64-gcc_openssl:1.80.1_9.4.0_1.1.0l         sh -c "cargo build --bin rathole --release -v "
2. run command again.It will result in logs similar to the following:
```
Dirty libz-sys v1.1.12: the dependency build_script_build was rebuilt (1725281026.427356500s, 427356500ns after last build at 1725281026.000000000s)
Dirty rustversion v1.0.14: the file `target/release/build/rustversion-0bf5fffcec081f72/out/version.expr` has changed (1725281004.366127800s, 366127800ns after last build at 1725281004.000000000s)
```
3. However, they shouldn't actually be considered changes.

### Version

```text
cargo 1.80.1 (376290515 2024-07-16)
release: 1.80.1
commit-hash: 37629051518c3df9ac2c1744589362a02ecafa99
commit-date: 2024-07-16
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 16.4.0 [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the issue report. This is a known issue: <https://github.com/rust-lang/cargo/issues/12060>, and we have an open PR #13955. Close in favor of those.
