### ISSUE TITLE
No link to playpen for example code in documentation

### ISSUE THREAD

**Issue by yann-ledu** [rust-lang/cargo#1448]
Using Mac nightly, I don't have any playpen link on my code generated in the docs. I'm certainly not doing something I should, but can't figure out what it is.

**Comment by alexcrichton** [comment]
You'll actually need to [manually instruct rustdoc](https://github.com/rust-lang/rust/blob/master/src/libstd/lib.rs#L107) about playpen if you'd like to use it. Unfortunately it may not work out well though if the examples depend on your crate being available. If it is separable though that configuration should do the trick!

**Comment by yann-ledu** [comment]
Very, very nice, thanks! Is there any plan to link each such snippet to the corresponding local execution of "cargo test"?

**Comment by alexcrichton** [comment]
Unfortunately no because play.rust-lang.org is a remote service that only has access to the standard library, not the crates.io community.
