### ISSUE TITLE
duplicate document and missing document

### ISSUE THREAD

**Issue by loynoir** [rust-lang/cargo#14483]
### Problem

https://github.com/loynoir/cargo/blob/feat-json-schema-for-editor/schema/cargo-config.schema.d.mts#L415-L428

https://doc.rust-lang.org/cargo/reference/config.html#profilenamestrip

https://doc.rust-lang.org/cargo/reference/config.html#profilenamestrip-1

`strip` is duplicated

---

https://github.com/loynoir/cargo/blob/feat-json-schema-for-editor/schema/cargo-config.schema.d.mts#L507-L510

`inherits` is missing

---

related https://github.com/rust-lang/cargo/pull/14482

**Comment by ehuss** [comment]
Thanks for the report! Closing as this has already been resolved via #14146 and will be live in the next release.
