### ISSUE TITLE
`cargo update --verbose` "note" is showing a command that fail

### ISSUE THREAD

**Issue by TaylorHo** [rust-lang/cargo#14513]
### Problem

When running the `cargo update --verbose` command, it outputs a list of packages changed/unchanged and, before exiting, it shows a "note" saying:

```
note: to see how you depend on a package, run `cargo tree --invert --package <dep>@<ver>`
```

When running `cargo tree --invert --package <dep>@<ver>` with **any** of the shown packages, it outputs the following message:

```
warning: nothing to print.

To find dependencies that require specific target platforms, try to use option `--target all` first, and then narrow your search scope accordingly.
```

It never shows what we want to see without the `--target all`, so the "note" message could include the `--target all` parameter in its contents to ensure a working command.

### Steps

1. Run `cargo update --verbose`
2. Run the command shown in the "note" section of the previous command
3. See the warning

### Possible Solution(s)

Add the `--target all` parameter to the "note" message in the `cargo update --verbose` output.

### Version

```text
cargo 1.81.0 (2dbb1af80 2024-08-20)
release: 1.81.0
commit-hash: 2dbb1af80a2914475ba76827a312e29cedfa6b2f
commit-date: 2024-08-20
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.73+curl-8.8.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.6.1 [64-bit]
```

**Comment by weihanglo** [comment]
Thanks for the suggestion!

I found `cargo tree --invert --package <dep>@<ver>` is already verbose. Adding `--target all` makes it too lengthy. Also, we already have the line teaching users how to narrow down the search scope.

```
To find dependencies that require specific target platforms, try to use option `--target all` first, and then narrow your search scope accordingly.
```

The flag and instruction seem sufficient to follow and discover to me. I'd like to know if you feel the same.

> It never shows what we want to see without the `--target all`

That might be because you have lots of platform dependent dependencies. It may not always be the most common case.

**Comment by TaylorHo** [comment]
Got it! I couldn't find a working example without `--target all`, but that might be due to my project's dependencies, as you've mentioned.

And yes, it's already quite verbose 😅

I think it's fine to leave it as is for now. I'll close the issue and PR. Thanks!
