### ISSUE TITLE
[patch.crates-io] doesn't correctly override git dependancy

### ISSUE THREAD

**Issue by AshleySetter** [rust-lang/cargo#14526]
### Problem

I have a Cargo.toml for a rust package with some private git dependencies like so:

```
[dependencies]
vc_signing = {git = "ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git"}
get_github_schema = {git = "ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git"}
```

When I attempt to use [patch.crates-io] to patch in the https address instead as shown below: (I am doing this because I am setting up a CI github action to build the package and run tests and am using Personal Access Tokens to enable read access to the github repository, which require the https address be used, but ssh keys are used locally by developers for access).

```
[dependencies]
vc_signing = {git = "ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git"}
get_github_schema = {git = "ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git"}

[patch.crates-io]
get_github_schema = { git = "https://github.com/nqminds/Verifiable-Credential-Tools.git" }
vc_signing = { git = "https://github.com/nqminds/Verifiable-Credential-Tools.git" }
```

Cargo raises the following error:

```
Caused by:
  failed to load source for dependency `get_github_schema`

Caused by:
  Unable to update ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git

Caused by:
  failed to fetch into: /root/.cargo/git/db/verifiable-credential-tools-0c62aa03dacc025c

Caused by:
  failed to authenticate when downloading repository

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  no authentication methods succeeded
```

However if I change the dependencies directly cargo is able to install the dependencies correctly. 

```
[dependencies]
vc_signing = {git = "https://github.com/nqminds/Verifiable-Credential-Tools.git", branch="main"}
get_github_schema = {git = "https://github.com/nqminds/Verifiable-Credential-Tools.git", branch="main"}
```

### Steps

1) Have a Cargo.toml with a git ssh dependency
2) Add a [patch.crates-io] section with a git https override for that dependency

### Version

```text
cargo 1.81.0 (2dbb1af80 2024-08-20)
release: 1.81.0
commit-hash: 2dbb1af80a2914475ba76827a312e29cedfa6b2f
commit-date: 2024-08-20
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.8.0-DEV (sys:0.4.73+curl-8.8.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 24.4.0 [64-bit]
```

**Comment by ehuss** [comment]
The sub-table after `patch` indicates the [*source*](https://doc.rust-lang.org/cargo/reference/source-replacement.html) that you are patching. (A source in cargo is a registry, git server, vendor directory, etc.) When you have `[patch.crates-io]`, that's patching the `crates.io` server, not your git server. To patch a git dependency, you'll need something like `[patch."ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git"]` to indicate you are patching that git source (not certain on the exact syntax there, but I think that should work). There's more information in the [patch docs](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section). Does that work for you?

**Comment by AshleySetter** [comment]
I tried following the syntax in the [patch docs](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section).

I tried adding the following to my cargo.toml, but it didn't result in any change in behaviour.

```
[patch.'ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git']
get_github_schema = { git = 'https://github.com/nqminds/Verifiable-Credential-Tools.git' }
vc_signing = { git = 'https://github.com/nqminds/Verifiable-Credential-Tools.git' }
```
I also tried replacing the 2 dependencies with the following, just in case, but it didn't work either:

```
[dependencies.get_github_schema]
git = 'ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git'

[dependencies.vc_signing]
git = 'ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git'

```

**Comment by AshleySetter** [comment]
I also tried the following as I noticed the lack of a `.git` in the patch header

```
[patch.'ssh://git@github.com/nqminds/Verifiable-Credential-Tools']
get_github_schema = { git = 'https://github.com/nqminds/Verifiable-Credential-Tools.git' }
vc_signing = { git = 'https://github.com/nqminds/Verifiable-Credential-Tools.git' }

```

**Comment by ehuss** [comment]
Do you perhaps have transitive dependencies that are also in git? Sorry, I did not look at your use case very closely. `[patch]` is generally not intended for this kind of redirect.

Another option (which I would recommend) is to use [insteadOf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) git configuration. The git config might look something like:

```
[url "https://github.com/"]
        insteadOf = ssh://git@github.com/
```

----

Another option is to use [source replacement](https://doc.rust-lang.org/nightly/cargo/reference/source-replacement.html) where one source (git-ssh) is entire replaced with another (git-https). That might look something like this (in `.cargo/config.toml`):

```toml
[source.git-ssh]
git = "ssh://git@github.com/nqminds/Verifiable-Credential-Tools.git"
replace-with = "git-https"

[source.git-https]
git = "https://github.com/nqminds/Verifiable-Credential-Tools.git"
```

**Comment by AshleySetter** [comment]
Using git's insteadOf configuration worked great, neat solution to my problem, thanks!
