### ISSUE TITLE
`--all-targets` ignores specific targets

### ISSUE THREAD

**Issue by mo8it** [rust-lang/cargo#14542]
### Problem

When both `--all-targets` and a specific target like `--bin BIN_NAME` are specified, Cargo ignores the specific target. This is not intuitive and not documented.

### Steps

1. Create a package with 2 binaries `bin1` and `bin2`.
2. Run `cargo check --all-targets --keep-going --bin bin1`. (`--keep-going` to make sure that it runs until the end)
3. Both `bin1` and `bin2` are checked.

### Possible Solution(s)

There are two solutions:
1. My preference: Throw an error because the user is doing something wrong and the result isn't as they would expect.
2. Document that `--all-targets` ignores any specific targets specified before or after it.

### Notes

See related issue in Rust-Analyzer: https://github.com/rust-lang/rust-analyzer/issues/18110

### Version

```text
cargo 1.82.0-beta.3 (8f40fc59f 2024-08-21)
release: 1.82.0-beta.3
commit-hash: 8f40fc59fb0c8df91c97405785197f3c630304ea
commit-date: 2024-08-21
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Fedora 40.0.0 [64-bit]
```

**Comment by RalfJung** [comment]
> Both bin1 and bin2 are checked.

That is what you asked for, so... why do you think this is not intuitive? You said "please build everything" and "please build the `bin1` bin target", and cargo did both of these things.

I would find it quite non-intuitive if cargo had *not* built `bin2` in your case.

**Comment by mo8it** [comment]
Thanks for your input. One could think about explaining this bevahior in the help message, but I don't think that it is required.
