### ISSUE TITLE
Saving a specific `message-format` to a file, while also producing "normal" output

### ISSUE THREAD

**Issue by BatmanAoD** [rust-lang/cargo#14555]
### Problem

In CI, it can be useful to generate a code-quality report while also printing a job log designed for humans to read. `cargo check` provides `--message-format json`, which enables generating machine-readable output that can be used to generate a report programmatically (e.g. with https://crates.io/crates/gitlab_clippy); but currently, there's no way to do this in such a way that `cargo` _also_ produces useful human-readable output. `cargo clippy --message-format json | tee <file>` is too verbose and difficult to read.

Because of this, `gitlab_clippy` recommends running `cargo check` twice in CI, once to produce readable output and fail the job if there are errors, and again to produce a report.

### Proposed Solution

There could be an additional flag that would take a file argument and permit sending `json` messages to that file, while emitting the "normal" Cargo output on `stdout`.

**Comment by epage** [comment]
>  https://crates.io/crates/gitlab_clippy);

Another similar conversion command: https://crates.io/crates/clippy-sarif

**Comment by ehuss** [comment]
Thanks for the report! The cargo team discussed this and decided to close this for now. We suggest that, if possible, gitlab_clippy be responsible for printing the rendered output from the JSON messages. If there are events or other things missing from the JSON that would be useful, feel free to open a new issue for any missing messages (though I think we have a few currently open).
