### ISSUE TITLE
Cargo bench --bench $benchname doesn't work on Windows

### ISSUE THREAD

**Issue by iopq** [rust-lang/cargo#1456]
It doesn't run the benchmark, it just returns.

My benchmark is in a file with other tests, not sure if that matters.
My generated binary can be run with --bench $benchname, but not with the cargo bench command.

**Comment by alexcrichton** [comment]
Do you have an example I could test this out on? A simple example locally works just fine.

**Comment by iopq** [comment]
I am working on https://github.com/ujh/iomrascalai

I tried to do `cargo bench --bench no_eyes_13x13` and it just quit without doing anything
running `iomrascalai-3a75076b1fcf11b1.exe --bench no_eyes_13x13` works perfectly fine

**Comment by iopq** [comment]
I just updated Cargo, now it says `no bench target named `no_eyes_13x13``

**Comment by alexcrichton** [comment]
Ah I see, `cargo bench --bench foo` will run the *Cargo benchmark* named `foo`, not the actual benchmark test named `foo`. To do that you want to pass the argument `foo` to the binary so you would do `cargo bench foo`.

**Comment by iopq** [comment]
Ah, I see. It wasn't clear from `cargo bench --help` text.

**Comment by andrewdavidmackenzie** [comment]
Same happened to me - maybe we should do a PR for that help text in cargo?
