### ISSUE TITLE
cargo-timing.html supports dark mode

### ISSUE THREAD

**Issue by ahaoboy** [rust-lang/cargo#14586]
### Problem

For users using dark mode, opening cargo-timing.html is very glaring

I can use some browser ext to force the web page to switch to dark mode, but the canvas will still be white background.

![Image](https://github.com/user-attachments/assets/82e98b9e-e053-4ba8-93b4-7416b8893be3)

### Proposed Solution

For web pages, there is already prefers-color-scheme

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

For canvas, maybe just invert the basic white and black, and keep the other colors?

**Comment by weihanglo** [comment]
Thanks for the proposal. This is a good feature, though I don't think any of the maintainers has time to either mentor or design it.
