### ISSUE TITLE
Next `tar-rs` update creates sparse entries by default

### ISSUE THREAD

**Issue by xzfc** [rust-lang/cargo#14594]
Recently, the `tar` crate got support for creating archives with sparse entries (https://github.com/alexcrichton/tar-rs/pull/375). It is going to be enabled by default in the next release.

For Cargo (which depends on this crate), keeping the default would mean that some very old versions of Cargo would not be able to read some archives created by the latest Cargo. Specifically, the ability to read sparse entries was added in `tar` `0.4.6` (released 2016-06-09). The corresponding `tar-rs` bump for Cargo was #2973, which is included in Cargo `0.13` which is included in rust `1.12`.

The sparseness check does not affect Rust source files (as text files generally do not contain large chunks of null bytes), but it may affect crates containing binary files. For example, [`protobuf-build`](https://docs.rs/crate/protobuf-build/0.14.0/source/bin/protoc-linux-ppcle_64) and [`metal`](https://docs.rs/crate/metal/0.29.0/source/examples/mps/shaders.metallib) crates contain binaries that could possibly be sparse. The command `rg -ca '\x00{4096}' ~/.cargo/registry/` might reveal other similar binaries.

I'm creating this issue at the [request](https://github.com/alexcrichton/tar-rs/pull/375#issuecomment-2364276823) of @alexcrichton to let the Cargo team decide whether to
- keep the new default as-is, or
- add a few `ar.sparse(false)` calls explicitly everywhere `tar::Builder` is used.

**Comment by alexcrichton** [comment]
As a further note, I've publisehed [tar 0.4.42](https://crates.io/crates/tar/0.4.42) with this change

**Comment by epage** [comment]
@alexcrichton is there a reason this didn't justify a breaking release?

**Comment by alexcrichton** [comment]
Honestly I just didn't even think about it. It's API-compatible and backwards-compatible for versions ~8 years back, though, so I'm not sure it'd warrant a breaking release. I figured Cargo might want a heads up though since it may want more compat than that.

**Comment by weihanglo** [comment]
Since a new release has already come out, I would suggest we proactively bump to `tar@0.4.42` in both Cargo.toml, and turn off sparse entries before the next beta branches off.
