### ISSUE TITLE
Unexpected feature resolution behaviour with intra-workspace dependencies and `--no-default-features`

### ISSUE THREAD

**Issue by Dzejkop** [rust-lang/cargo#14635]
### Problem

`--no-default-features` behaves differently if ran in a workspace with `--bin` or `--package`.

I'm putting the link in steps, but it's best to see it in an [actual example](https://github.com/dzejkop/bizarre-rust-features-behaviour).

It seems that `--package x --no-default-features` correctly resolves to not use default features of package x, but `--bin x --no-default-features` does not

### Steps

Clone https://github.com/dzejkop/bizarre-rust-features-behaviour and follow instructions

### Version

cargo 1.81.0 (2dbb1af80 2024-08-20)
release: 1.81.0
commit-hash: 2dbb1af80a2914475ba76827a312e29cedfa6b2f
commit-date: 2024-08-20
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.4.0 (sys:0.4.73+curl-8.8.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.2.1 [64-bit]

**Comment by Patryk27** [comment]
Possibly related: https://github.com/rust-lang/cargo/issues/8157.

**Comment by epage** [comment]
Looking over the repo, this looks like #8157, so closing this as a duplicate.  If there is a reason we missed for why this should be kept open separately, let us know!
