### ISSUE TITLE
Cargo cannot find github team, when trying to add owner

### ISSUE THREAD

**Issue by DraftedDev** [rust-lang/cargo#14646]
### Problem

I tried to add the org [maycoon-ui](https://github.com/maycoon-ui) as an owner of the `maycoon` crate using  `cargo owner --add github:org:maycoon-ui`, but cargo keeps giving me an error:

`the remote server responded with an error (status 400 Bad Request): could not find the github team org/maycoon-ui. Make sure that you have the right permissions in GitHub. See https://doc.rust-lang.org/cargo/reference/publishing.html#github-permissions`

I double **checked the permissions** and I even **re-authenticated the Crates.io OAuth App** and **re-logged** into crates.io, but it keeps giving me this error message. I already **granted crates.io access** in my organization profile and I'm the **owner/admin** of the whole organization.

**Images as proof:**

# Organization OAuth Settings

![Image](https://github.com/user-attachments/assets/685457d5-23e2-425c-bbe0-03d9cffbb898)

# My Profile OAuth Settings

![Image](https://github.com/user-attachments/assets/1fd346a6-07cd-41b6-bae0-9fb0cc500f41)

**Thanks for any help I can get!**

### Version

cargo 1.83.0-nightly (c1fa840a8 2024-08-29)
release: 1.83.0-nightly
commit-hash: c1fa840a85eca53818895901a53fae34247448b2
commit-date: 2024-08-29
host: x86_64-pc-windows-msvc
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:Schannel)
os: Windows 10.0.22000 (Windows 11 Professional) [64-bit]

**Comment by weihanglo** [comment]
The syntax is `github:org:team`. Should replace `org` with `maycoon-ui`, and `team` with whatever team in your organization.

For example, this is how the release-publishers team under rust-lang org looks like:
https://crates.io/teams/github:rust-lang:release-publishers
