### ISSUE TITLE
`cargo-fmt` and `cargo-clippy` are not documented in The Cargo Book

### ISSUE THREAD

**Issue by WorikWork** [rust-lang/cargo#14640]
### Problem

I am looking for documentation on `cargo fmt`

So I came to [here](https://doc.rust-lang.org/cargo/commands/index.html) 

It is an undocumented Cargo command.

It seems like a good place to document it.

thank you

**Comment by epage** [comment]
Neither is `cargo clippy`. They aren't built in commands but extension that get installed when you install those rustup components.

**Comment by WorikWork** [comment]
> Neither is `cargo clippy`. They aren't built in commands but extension that get installed when you install those rustup components.

Really?  Ok.

I changed the title of the issue to reflect that.

I am raising this simply because this is where I came, and it seems a logical place to come (the Cargo Book) to find the documentation for the tools I use Cargo for.

**Comment by weihanglo** [comment]
We could technically put a link to each external command in new HTML pages. However there are things worth noting:

* None of them (`cargo-fmt` and `cargo-clippy`) has a man page like documentation in their repository  ([rust-lang/rustfmt](https://github.com/rust-lang/rustfmt) and [rust-lang/rust-clippy](https://github.com/rust-lang/rust-clippy/)) for us to link to.
* The [man page style docs](https://doc.rust-lang.org/cargo/commands/index.html) are also accessible via `cargo help <cmd>` in your terminal emulator. We can't link to arbitrary format if their man pages are available. Those man pages are generated from the source here <https://github.com/rust-lang/cargo/tree/master/src/doc>.
* The Cargo team (maintainers of this repo) has no control over `cargo-fmt` and `cargo-clippy` in those repositories. The maintainers of those two repos can indeed write some man page docs in rust-lang/cargo repo, though it would be a burden to keep things sync in different repos.
* There are [some discussion](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Cargo.20Lints/near/429873543) about moving cargo-fmt/cargo-clippy into Cargo as built-in commands, though it is not going to happen anytime sooner.

**Comment by weihanglo** [comment]
We might have a possible way forward at this moment:

Writing a static markdown for `cargo fmt` and `cargo clippy` only for HTML documentation at <https://doc.rust-lang.org/cargo/>. For each page, explain it is an external subcommand and is available via `rustup component add`. Also provide a link to <https://doc.rust-lang.org/clippy/installation.html> or <https://github.com/rust-lang/rustfmt> (sorry I cannot find the official doc for rustfmt under doc.rust-lang.org).
