### ISSUE TITLE
`cargo publish` fails building even after successful `cargo build --release`

### ISSUE THREAD

**Issue by dd-dreams** [rust-lang/cargo#14661]
### Problem

Hello. As the title says, I have released a new version of my package, though `cargo publish` fails. All the checks pass, builds are passing, but only `cargo publish` won't pass. I have implemented a Clone trait for my struct, and I'm running `self.writer.1.clone()` on another module, though it fails. I'm talking about: https://github.com/dd-dreams/aft/blob/2021421ea77881f0d0fecd268a081580eb7bdc97/aft-crypto/src/data.rs#L126, https://github.com/dd-dreams/aft/blob/2021421ea77881f0d0fecd268a081580eb7bdc97/aft/src/sender.rs#L310.
I receive this error:
```rust
error[E0599]: no method named `clone` found for struct `EncAlgo` in the current scope
   --> src/sender.rs:310:27
    |
310 |             self.writer.1.clone()
    |                           ^^^^^ method not found in `EncAlgo<T>`
```

### Steps

1. Clone my repository.
2. Run `cargo publish --dry-run -p aft`.

**Comment by epage** [comment]
Note that the reproduction steps are incomplete
```console
$ git clone https://github.com/dd-dreams/aft.git
$ cd aft
$ cargo publish --dry-run
error: the `-p` argument must be specified to select a single package to publish
```
I assume you meant
```console
$ git clone https://github.com/dd-dreams/aft.git
$ cd aft/aft
$ cargo publish --dry-run
```

When `cargo publish` runs, it removes all `path`s from `[dependencies]`, relying solely on the registry.  The verify step then builds using these updated `[dependencies]`.  You can see this in action if you run `cargo package` and inspect the generated `.crate` file.

I'm assuming in this case, you need to publish `aft-crypto` first.  #1169 is tracking support for `cargo publish --dry-run --workspace`.

**Comment by dd-dreams** [comment]
Oh, I guess I forgot about publishing `aft-crypto` first. Thanks, much appreciated!
