### ISSUE TITLE
Compression of packages

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/cargo#1468]
Hi,

I [have][1] a [number][2] of [packages][3] that include rather large code bases via submodules. Today I was updating them due to the changes in Rust and Cargo, and I could not `cargo package` them in order to `cargo publish`. All the errors I get when running `cargo package --verbose` are related to compression in one way or another.

```
…
failed to verify package tarball

Caused by:
  invalid tar archive
```

```
…
failed to verify package tarball

Caused by:
  corrupt deflate stream
```

```
failed to prepare local package for uploading

Caused by:
  could not archive source file `OpenBLAS/lapack-netlib/DOCS/lapacke.pdf`

Caused by:
  failed to write whole buffer
```

Thank you.

Regards,
Ivan

[1]: https://github.com/cmr/netlib-blas-provider
[2]: https://github.com/cmr/openblas-blas-provider
[3]: https://github.com/stainless-steel/git

**Comment by huonw** [comment]
Dupe of https://github.com/rust-lang/cargo/issues/1468. Thanks for filing.

**Comment by IvanUkhov** [comment]
@huonw, can you please correct the number of issue you wanted to refer to? Thanks!

**Comment by huonw** [comment]
Whoops, https://github.com/rust-lang/cargo/issues/1465.
