### ISSUE TITLE
Extract with docker broken on master branch

### ISSUE THREAD

**Issue by Flo354** [rust-lang/cargo#14706]
### Problem

The docker image doesn't work with the "-e" argument. It is working perfectly with tag "version-2.3.4"

### Steps

```bash
<> docker run -it --rm -v "$(pwd):/home/appuser" refirmlabs/binwalk -e "file.bin"
[2024-10-19T13:43:56Z ERROR binwalk::binwalk] Failed to create symlink /home/appuser/extractions/file.bin -> /home/appuser/file.bin: Permission denied (os error 13)
thread 'main' panicked at src/main.rs:81:6:
Binwalk initialization failed: BinwalkError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    76653 exit 101   docker run -it --rm -v "$(pwd):/home/appuser" refirmlabs/binwalk -e 
```

**Comment by weihanglo** [comment]
This is not immediately clear to me how it is related to Cargo. Looks like an issue against <https://github.com/ReFirmLabs/binwalk/tree/master>. Let us know if you were exactly meant to open a Cargo issue.

**Comment by Flo354** [comment]
I'm sorry, I should have had mixed my links when I opened the issue.
Indeed it's not related to cargo.

Regards,
