### ISSUE TITLE
create a message format targeted at ci / build pipelines

### ISSUE THREAD

**Issue by kurtbuilds** [rust-lang/cargo#14709]
### Problem

Currently, it's surprisingly difficult to get the artifact built by `cargo-build` . (Prior discussion: https://github.com/rust-lang/cargo/issues/3757)

I have a custom build pipeline where it's helpful to both show human ANSI colored diagnostics (so if something goes wrong, I can see it easily in the logs), but also necessary to print the artifact path to stdout for the build pipeline to manage.

I built a very small wrapper tool (https://github.com/kurtbuilds/cargo_build_artifact) that runs cargo in json-diagnostic-rendered-ansi, and depending on the message that's output, sends diagnostics and errors to stderr, swallows other diagnostics, and emits a single line - the path of the built artifact - to stdout.

Curious if `cargo` team would support a PR to merge that functionality in under a new `message-format` - (maybe called `human-with-build-artifacts` to build on naming conventions already used?)

### Proposed Solution

Create a new message-format (tentatively called `human-with-build-artifacts`) that outputs colored warnings and errors to stderr, and prints build artifact paths, one per line, to stdout.

**Comment by epage** [comment]
For at least myself, this feels too specialized.  This will work for you but there are slight variants that people might need to work with other use cases.

**Comment by weihanglo** [comment]
> I built a very small wrapper tool…

I am so happy that it actually works for people to customize their workflow!

> Currently, it's surprisingly difficult to get the artifact built by cargo-build . (Prior discussion: https://github.com/rust-lang/cargo/issues/3757)

I would say a new message format is not an ideal solution to this. Possibly better solutions in my mind  would be like a better build plan support, or [a query interface](https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/Query.20Interface.20for.20Cargo) for users to get metadata for a package.

**Comment by kurtbuilds** [comment]
Ok!
