### ISSUE TITLE
Cannot dry-run `cargo publish` without bumping versions

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#14721]
### Problem

When a tool like `cargo release` runs in a dry-run mode, it shouldn't be bumping version numbers.  However, as of #14448, `cargo publish --dry-run` will fail unless the version numbers are bumped

### Steps

```console
$ git clone git@github.com:clap-rs/clap.git
$ cd clap
$ cargo +beta release major -vvv
```

### Possible Solution(s)

Revert #14448 which makes us lose out on early error reporting.  However, if we view publish as plumbing with tools like `cargo release` handling it, make its not too bad

Skip #14448's check in dry-run mode or downgrade it to a warning.  Deviating behavior between dry-run or not can be confusing and break other workflows.

Tell people to use `cargo package`.  There are slight behavior differences though.

### Notes

cargo 1.83.0-beta.2 (15fbd2f60 2024-10-08)

**Comment by weihanglo** [comment]
See also https://github.com/rust-lang/cargo/pull/14550

**Comment by weihanglo** [comment]
> Skip [#14448](https://github.com/rust-lang/cargo/pull/14448)'s check in dry-run mode or downgrade it to a warning. Deviating behavior between dry-run or not can be confusing and break other workflows.

What kind of workflows it may break?

The benefit of #14448 is it fails fast, so users don't need to wait for the verification step. Unless I misunderstood, it doesn't really change any final result of non dry-run publish.

**Comment by epage** [comment]
I've been thinking more about that comment I made.  A lot of it comes down to framing.  If you view this as general validation, it should always be reported.  If you view this as just reporting the upload error earlier, than warning or ignoring is perfectly fine.

I do not remember what I was considering when I said it could break other workflows.

**Comment by weihanglo** [comment]
If it is not too hard to downgrade to a warning, I am slightly inclined to that.

**Comment by ehuss** [comment]
The team discussed this today and decided to downgrade it to a warning for dry-run only, which is up at #14742.
