### ISSUE TITLE
Diagnostic suggestion for enabling required-features is wrong

### ISSUE THREAD

**Issue by bonsairobo** [rust-lang/cargo#14737]
### Problem

The diagnostic looks like:

```
error: target `foo` in package `bar` requires the features: `featA`, `featB`
Consider enabling them by passing, e.g., `--features="featA featB"`
```

However, the syntax `--features="featA featB"` does not work. Instead, you must use a comma separator, like `--features="featA,featB"`.

### Possible Solution(s)

Replace the `" "` with `","` [here](https://github.com/rust-lang/cargo/blob/e75214ea4936d2f2c909a71a1237042cc0e14b07/src/cargo/ops/cargo_compile/unit_generator.rs#L688).

### Version

```
cargo 1.84.0-nightly (cf53cc54b 2024-10-18)
release: 1.84.0-nightly
commit-hash: cf53cc54bb593b5ec3dc2be4b1702f50c36d24d5
commit-date: 2024-10-18
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: NixOS 24.11.0 [64-bit]
```

**Comment by ehuss** [comment]
Spaces should work. Are you perhaps using an unusual shell that doesn't support double-quotes?
Switch the diagnostic to use commas seems fine, but I'm curious what problem you ran into.

**Comment by bonsairobo** [comment]
@ehuss I get the same behavior in bash and fish. Spaces don't work; commas do.

I can try making a minimal repro.

**Comment by bonsairobo** [comment]
My apologies. I just found the issue. I was using a wrapper script for cargo which forwards arguments, and apparently this breaks it somehow.
