### ISSUE TITLE
Failed testing proc-macros built with `-Zbuild-std`

### ISSUE THREAD

**Issue by madsmtm** [rust-lang/cargo#14735]
### Problem

When testing proc-macros with `-Zbuild-std`, the binary under test fails to load the standard library (at least on macOS):

```console
     Running unittests src/lib.rs (target/debug/deps/foo_proc_macro-0dc0d3e74fa08def)
dyld[99947]: Library not loaded: @rpath/libstd-7cbc1cc35ff1ddd0.dylib
  Referenced from: <E6DCD012-647E-354E-B422-B62E4D01C5BF> target/debug/deps/foo_proc_macro-0dc0d3e74fa08def
  Reason: tried: '$(pwd)/target/debug/deps/libstd-7cbc1cc35ff1ddd0.dylib' (no such file), '$(pwd)/target/debug/libstd-7cbc1cc35ff1ddd0.dylib' (no such file), '$HOME/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/libstd-7cbc1cc35ff1ddd0.dylib' (no such file), '$HOME/lib/libstd-7cbc1cc35ff1ddd0.dylib' (no such file), '/usr/local/lib/libstd-7cbc1cc35ff1ddd0.dylib' (no such file), '/usr/lib/libstd-7cbc1cc35ff1ddd0.dylib' (no such file, not in dyld cache)
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `$(pwd)/target/debug/deps/foo_proc_macro-0dc0d3e74fa08def` (signal: 6, SIGABRT: process abort signal)
```

### Steps

```sh
# Create basic proc-macro
cargo new foo-proc-macro --lib
cd foo-proc-macro/
echo "\n[lib]\nproc-macro = true" >> Cargo.toml
echo > src/lib.rs

# Test it with -Zbuild-std
cargo +nightly test --lib -Zbuild-std --target=aarch64-apple-darwin
```

### Notes

This started happening since https://github.com/rust-lang/rust/pull/131188, because now `$HOME/.rustup/toolchains/$TOOLCHAIN/lib` (which cargo is adding to the `DYLD_FALLBACK_LIBRARY_PATH`/`LD_LIBRARY_PATH`) no longer includes `libstd-*.dylib`, that is only present in `$HOME/.rustup/toolchains/$TOOLCHAIN-$HOST/lib/rustlib/$HOST/lib` (which Cargo normally adds, but doesn't add when using `-Zbuild-std`).

This was found in https://github.com/sonos/dinghy/issues/238.

### Possible Solution(s)

Not sure, perhaps the code that sets `DYLD_FALLBACK_LIBRARY_PATH`/`LD_LIBRARY_PATH` https://github.com/rust-lang/cargo/blob/80d82ca22abbee5fb7b51fa1abeb1ae34e99e88a/src/cargo/core/compiler/compilation.rs#L293-L339 needs to be adjusted? Or perhaps different handling when testing proc macros is needed altogether?

### Version

cargo 1.84.0-nightly (cf53cc54b 2024-10-18)
release: 1.84.0-nightly
commit-hash: cf53cc54bb593b5ec3dc2be4b1702f50c36d24d5
commit-date: 2024-10-18
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.7.0 [64-bit]

**Comment by fredszaq** [comment]
I can confirm there this also happens on linux, looks like it started with the 2024-10-06 nightly
```
$ cargo +nightly-2024-10-05 test -Zbuild-std --target=x86_64-unknown-linux-gnu 
   Compiling my-proc-macro v0.1.0 (/tmp/my-proc-macro)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.25s
     Running unittests src/lib.rs (target/debug/deps/my_proc_macro-7e0727f90075e76f)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests my_proc_macro

running 0 tests
```

```
$ cargo +nightly-2024-10-06 test -Zbuild-std --target=x86_64-unknown-linux-gnu
   Compiling my-proc-macro v0.1.0 (/tmp/my-proc-macro)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.40s
     Running unittests src/lib.rs (target/debug/deps/my_proc_macro-7e0727f90075e76f)
/tmp/my-proc-macro/target/debug/deps/my_proc_macro-7e0727f90075e76f: error while loading shared libraries: libstd-f157c25fb2dbfbe0.so: cannot open shared object file: No such file or directory
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/tmp/my-proc-macro/target/debug/deps/my_proc_macro-7e0727f90075e76f` (exit status: 127)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
```
