### ISSUE TITLE
Enhance missing Cargo error message with platform-specific instructions

### ISSUE THREAD

**Issue by ystoneman** [rust-lang/cargo#14746]
## Current Behavior
When Cargo is not installed, the error message is generic:
```
Cargo, the Rust package manager, is not installed or is not on PATH.
This package requires Rust and Cargo to compile extensions. Install it through
the system's package manager or via https://rustup.rs/
```

## Proposed Improvement
Add platform-specific package manager suggestions for common platforms. For example on macOS:
```
Cargo, the Rust package manager, is not installed or is not on PATH.
This package requires Rust and Cargo to compile extensions.
On macOS, you can install it via Homebrew:
`brew install rust`
Alternatively, you can install via https://rustup.rs/
```

## Implementation Note (extra credit)
- Use standard OS detection to provide relevant package manager commands

**Comment by epage** [comment]
Could you provide reproduction steps for this error message?

**Comment by ehuss** [comment]
I think that error message is generated by [maturin](https://github.com/PyO3/maturin). We have no control over that. If that is correct, I would suggest filing an issue with them.

**Comment by weihanglo** [comment]
> I think that error message is generated by [maturin](https://github.com/PyO3/maturin). We have no control over that. If that is correct, I would suggest filing an issue with them.

https://github.com/PyO3/maturin/blob/dbe456b6d16109c0ea4630c993fc126e4979703c/maturin/__init__.py#L179-L181

Seems like it. Closing.
