### ISSUE TITLE
Update dependency `handlebars` to v6 for `mdman`

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#14764]
### Problem

Renovate bot found a newer version available for dependency `handlebars` in <https://github.com/rust-lang/cargo/pull/14763>. `handlebars` is used by `mdman` for templatizing and generating man pages.

However, the new version has some API changes that need to be fixed:

<details><summary>Build failure. Click to See details</summary>
<p>

```
   Compiling mdman v0.0.0 (/Users/runner/work/cargo/cargo/crates/mdman)
error[E0639]: cannot create non-exhaustive struct using struct expression
  --> crates/mdman/src/hbs.rs:27:19
   |
27 |       let options = DirectorySourceOptions {
   |  ___________________^
28 | |         tpl_extension: ".md".to_string(),
29 | |         hidden: false,
30 | |         temporary: false,
31 | |     };
   | |_____^
```

</p>
</details> 

### Steps

1. Clone `rust-lang/cargo`
2. Run `cargo build-man`
3. Fix the build failure.

### Possible Solution(s)

Look into what have been changed in handlebars and update accordingly.

### Version

```text
7421ccf9159d5ac43883c53abe41ef1da657acfd
```

**Comment by hcbarker** [comment]
I can do this!
