### ISSUE TITLE
Snake Game when compiling

### ISSUE THREAD

**Issue by arnoexe** [rust-lang/cargo#14771]
### Problem

For small projects, it doesn't take too long to compile Rust projects.

For big projects, it can take a while, definitely if you've made a lot of changes. Hence why it could be nice to have a small snake game to play on the side in your terminal. Maybe a cool little easter egg that only works when you pass a specific flag in the cargo run command.

### Proposed Solution

Snake game.

### Notes

Snake game.

**Comment by weihanglo** [comment]
As for gaming during compilation, I would recommend Factorio, which you also wait for cargos a lot in game.

Joke a side, we have a [`Performance`](https://github.com/rust-lang/cargo/issues?q=sort%3Aupdated-desc%20is%3Aissue%20is%3Aopen%20label%3APerformance) label tracking Cargo's performance issues. The compilation of Rust mostly spend on the compiler side. Read [this chapter](https://nnethercote.github.io/perf-book/build-configuration.html#minimizing-compile-times
) of The Rust Performance Book for how to improve the compile time.

As for Cargo itself, issues would immediately impact compile time is a better story around caches. [Per user cache](https://github.com/rust-lang/cargo/issues/5931) is one of them. [A better scheduling algorithm](https://github.com/rust-lang/cargo/issues/7437) also a potential one.

Close as maintainers have no capacity to maintain this easter egg. Feel free to discuss more on those issues :)
