### ISSUE TITLE
Unexpected dependency resolution (duplicated crate when unification is possible)

### ISSUE THREAD

**Issue by bestdevever123** [rust-lang/cargo#14784]
### Problem

I have a project with `maturin 1.7.4`, that depends on `python-pkginfo`, that depends on `zip = { version = ">=0.6,<2", default-features = false, features = ["deflate"] }`, and maturin itself depends on `zip = { version = "0.6.1", default-features = false, features = [
    "bzip2",
    "deflate",
    "time",
] }`. 
I would expect the dependency resolver to unify the zip version to 0.6.6, but instead, I get both zip 0.6.6 and zip 1.1.4

### Steps

```bash
cargo new --lib testing
cd testing/
cargo add maturin
cargo tree | grep zip
```

### Version

```
cargo 1.82.0 (8f40fc59f 2024-08-21)
release: 1.82.0
commit-hash: 8f40fc59fb0c8df91c97405785197f3c630304ea
commit-date: 2024-08-21
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 24.4.0 (noble) [64-bit]
```

**Comment by ehuss** [comment]
Thanks for the report! I believe this is the same as #9029, so closing in favor of that.
