### ISSUE TITLE
Allow build.rs scripts to provide a set of cfg flags to be used when compiling the lib

### ISSUE THREAD

**Issue by carllerche** [rust-lang/cargo#1478]
[Nix](https://github.com/carllerche/nix-rust) needs to be able to be able to detect what the current version of libc provides in order to figure out how to provide bindings. For example, figuring out if eventfd is available, figuring out what flags are supported for various fns, etc...

This detection can be done in the `build.rs` script, however there is no way for this script to provide the results to the compilation stage. Ideally, `build.rs` could specify a set of CFG flags that get passed to `rustc` in order to perform the conditional compilation as required.

cc @alexcrichton

**Comment by wycats** [comment]
It's already possible for people to expose environment variables that end users can  use to control this kind of behavior, but that's strictly worse than using `cfg` and abstracting common `cfg`s via the build script.

**Comment by dcuddeback** [comment]
Just ran into this as well while writing libudev bindings. Older versions of libudev are missing `udev_hwdb_*` functions, which I'd like to detect in the build script and enable with a `#[cfg(...)]` attribute, similar to using Autoconf's `AC_CHECK_FUNCS` macro.
