### ISSUE TITLE
Could not fetch git crate in `Cargo.toml` on linux

### ISSUE THREAD

**Issue by Supermanuu** [rust-lang/cargo#14783]
### Problem

Hi! 

I could not fetch a git repo from `Cargo.toml` and I don't know why. I have a similar issue than #9191. I tried to set `init.defultbranch` globally and then remove `~/.cargo/git` but it did not work.

Distro: `Ubuntu 22.04.5 LTS`
Cargo version: `cargo 1.82.0 (8f40fc59f 2024-08-21)`
Rustc version: `rustc 1.82.0 (f6e511eec 2024-10-15)`
Git config --list (before setting init.defaultbranch, the default, actually):
```
init.defaultbranch=master
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:Supermanuu/360-RPIZ-WEB.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
```

Problematic cargo build output:
```
$ rm -rf ~/.cargo/git/ && cargo build
    Updating git repository `https://github.com/Supermanuu/gopro-controller.git`
error: failed to get `gopro-controller` as a dependency of package `P360-RPIZ-BACK v0.1.0 (/home/nolito/360-RPIZ-WEB/P360-RPIZ-BACK)`

Caused by:
  failed to load source for dependency `gopro-controller`

Caused by:
  Unable to update https://github.com/Supermanuu/gopro-controller.git?branch=wifi-connect#da271ba4

Caused by:
  the given reference name 'refs/commit/.l2s.da271ba4356e83b5cf0840f9853e8a29c893f9e7.lock0001' is not valid; class=Reference (4)
```

The build could not even start. It fails on the git clone. The problematic crate is one that I have forked myself and I am trying to fetch. In that repo I only changed some source files. The repo is public.

Cargo.toml problematic line:
```
gopro-controller = { git = "https://github.com/Supermanuu/gopro-controller.git", branch = "wifi-connect" }
```

It fails even without the branch option.

I can fetch the crate without the git option but I need it to be my forked repo... It will be some stupid thing I am forgetting but I don't figure out what it could be.

Thank you in advance! 🤓

### Steps

1. Create a new cargo project
2. Add `gopro-controller = { git = "https://github.com/Supermanuu/gopro-controller.git", branch = "wifi-connect", version = "0.10.5" }` in dependencies
3. Run `cargo bulild`

### Version

cargo 1.82.0 (8f40fc59f 2024-08-21)
release: 1.82.0
commit-hash: 8f40fc59fb0c8df91c97405785197f3c630304ea
commit-date: 2024-08-21
host: aarch64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.4.0 [64-bit]

**Comment by ehuss** [comment]
Hm, that's quite strange. Can you show the part of `Cargo.lock` that includes `gopro-controller`? Does it happen if you delete `Cargo.lock`?

**Comment by Supermanuu** [comment]
Hi!

This is the `Cargo.lock` section (if I use the crate from crate.io):
```
[[package]]
name = "gopro-controller"
version = "0.10.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "efe5692ef5d2bd61e97671444ae22975ce226bc5ff5a726d749bafc30dbefbd3"
dependencies = [
 "btleplug",
 "futures",
 "tokio",
 "uuid",
]
```
 
If I use the crate from git a `Cargo.lock` is not generated. I have removed the file and is not being generated.

Thank you!

**Comment by Supermanuu** [comment]
Hi!

Thank you for your time!

This is the output of the `cargo run` with that environment:

```
$ CARGO_LOG=network=debug,cargo::sources::git=trace cargo run
    Updating crates.io index
   0.021146459s DEBUG network: fetch https://index.crates.io/config.json
   0.021192500s DEBUG network: downloading config.json as 0
    Updating git repository `https://github.com/Supermanuu/gopro-controller.git`
   0.025125417s TRACE cargo::sources::git::source: updating git source `GitRemote { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/Supermanuu/gopro-controller.git", query: None, fragment: None } }`
   0.027502292s DEBUG cargo::sources::git::utils: attempting GitHub fast path for https://api.github.com/repos/Supermanuu/gopro-controller/commits/wifi-connect
   0.442246667s DEBUG cargo::sources::git::utils: github fast path up-to-date
error: failed to get `gopro-controller` as a dependency of package `P360-RPIZ-BACK v0.1.0 (/home/nolito/360-RPIZ-WEB/P360-RPIZ-BACK)`

Caused by:
  failed to load source for dependency `gopro-controller`

Caused by:
  Unable to update https://github.com/Supermanuu/gopro-controller.git?branch=wifi-connect

Caused by:
  the given reference name 'refs/remotes/origin/.l2s.wifi-connect.lock0001' is not valid; class=Reference (4)
```

**Comment by weihanglo** [comment]
Just found this issue https://github.com/termux/proot/issues/250
Do you use proot or something similar? It seems to be an issue of it

**Comment by Supermanuu** [comment]
Wow men, that was nice!

The Andronix Ubuntu installation command generates a `rootfs` and a script that launches `proot` for me. That script uses `--link2symlink` option that breaks cargo git fetching process.

I could be able to compile my whole app without problems with `cargo run` just commenting this out in `start-ubuntu22.sh`:

```
...bash
command="proot"
command+=" --kill-on-exit"
#command+=" --link2symlink"
command+=" -0"
command+=" -r ubuntu22-fs"
...
```

Thank you very much! I have not realized that this error could be generated by `proot` behaviour.

**Comment by weihanglo** [comment]
No idea. Maybe one is a symlink the other is not?

Anyway this seems to be resolved, so I am going to close this. sudo yum -y install epel-release
sudo yum install ShellCheck
