### ISSUE TITLE
Cargo does not build on stable (beta) channel

### ISSUE THREAD

**Issue by callahad** [rust-lang/cargo#1479]
When I try to build Cargo with rust-1.0.0-beta, I see a bunch of failures, but most of it seems to be fixed upstream. Here's a summary:

### Can't derive `Copy` as trait `core::clone::Clone` is not implemented on:

- liblibc: __Fixed upstream__
    - `types::os::common::posix01::{glob_t,timeval,timespec,timezone}`
    - `types::os::common::bsd43::rusage`
    - `types::os::common::bsd44::{sockaddr,sockaddr_storage,sockaddr_in,in_addr,sockaddr_in6,in6_addr,ip_mreq,ip6_mreq,addrinfo,sockaddr_un,ifaddrs}`
    - `types::os::arch::posix01::{stat,utimbuf,pthread_attr_t}`
    - `types::os::arch::extra::mach_timepase_info`
- term-0.2.4: __Fixed in 0.2.6__
    - `terminfo::parm::{States,FormatState,Flags,FormatOp`
    - `Attr`
- semver-0.1.17: __Fixed in 0.1.18__
    - `version_req::{ReqParseError,LexState}`
- regex-0.1.24: __Fixed in 0.1.25__
    - `vm::{MatchKind,StepState}`
- glob-0.2.7: __Fixed in 0.2.9__
    - `MatchResult`

### Use of feature flags

- threadpool-0.1.2: __Fixed in 0.1.3__
    - `#!feature(unsafe_destructor)`
- pkg-config-0.3.2: __Fixed in 0.3.3__
    - `#!feature(convert)`
- gcc-0.3.3: __Fixed in 0.3.4__
    - `#![feature(convert)]`

### Other

- tar-0.2.7: __Fixed in 0.2.9__
    - Wrong arity when calling `Error::new`
- rustc-serialize-0.3.10: __Fixed in 0.3.11__
    - Uses undeclared trait `std::error::FromError`

**Comment by callahad** [comment]
...and that rabbit hole went a bit deeper than expected. Iteratively updating a bunch of dependencies landed me at a point where I can *almost* compile Cargo, but for tar's reliance on `#![feature(fs, fs_time, fs_ext)]`.

Upstream tar bug: https://github.com/alexcrichton/tar-rs/issues/17

**Comment by andersk** [comment]
Cargo also needs `git2`, which doesn’t build on beta due to `#![feature(catch_panic)]` (alexcrichton/git2-rs#54).

**Comment by alexcrichton** [comment]
Thanks for this! This is a known issue, and we've actually got quite a small set of features to remove before Cargo builds on stable rust (as you've discovered!).

At this time this unfortunately isn't actionable as all these features are crucial to the operation of Cargo and can't be removed. I plan to write an RFC for all the fs-related features quite soon, and `git2`'s feature of `catch_panic` will likely also be stabilized during this next cycle (it was a late addition in the last one).
