### ISSUE TITLE
Support underline and shortline compatible for cargo-remove

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/cargo#14814]
### Problem

**Reproduction**:
```sh
lrne@Acer-Lrne[/path/to/]
    $ cargo new foo && cd foo
    Creating binary (application) `foo` package
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
lrne@Acer-Lrne[/path/to/foo/]
    $ cargo add cfg_if
    Updating `rsproxy-sparse` index
warning: translating `cfg_if` to `cfg-if`
      Adding cfg-if v1.0.0 to dependencies
             Features:
             - compiler_builtins
             - core
             - rustc-dep-of-std
    Updating `rsproxy-sparse` index
     Locking 2 packages to latest compatible versions
lrne@Acer-Lrne[/path/to/foo/]
    $ cargo remove cfg_if
    Removing cfg_if from dependencies
error: the dependency `cfg_if` could not be found in `dependencies`
lrne@Acer-Lrne[/path/to/foo/]
    $ cargo remove cfg-if
    Removing cfg-if from dependencies
lrne@Acer-Lrne[/path/to/foo/]
    $ 
```

**Comment by epage** [comment]
At least providing a "did you mean" more generally and not just for word separators) in the error messages would be good.

However, I'm unsure how far we should take normalization in Cargo. Yes, we do it in `cargo-add`. I don't remember the reason it did this in cargo-edit and I think we overlooked discussing this when merging. While `remove` is parallel to `add`, its also like other commands in that you've now been warned that the name isn't correct and you are operating on your existing dependencies.

**Comment by A4-Tacks** [comment]
If cargo-remove cannot translating underline and shortline, at least try giving a similar package name hint in the error message

**Comment by epage** [comment]
#14818 improved the error message.

**Comment by A4-Tacks** [comment]
Thanks!
