### ISSUE TITLE
`cargo add "package@*"` evaluates features of wrong version

### ISSUE THREAD

**Issue by ctz** [rust-lang/cargo#14832]
### Problem

My goal is to enable a crate feature on an existing dependency, via the CLI.

If I run:

```shell
$ cargo add --dev --features bindgen "aws-lc-sys@*" --package rustls --verbose
```

(I already have `aws-lc-sys` as a dependency, I want to enable this feature _without_ introducing a different version.)

I get:

```
    Updating crates.io index
      Adding aws-lc-sys * to dev-dependencies
error: unrecognized feature for crate aws-lc-sys: bindgen
disabled features:
    asan
```

I think this is because  `cargo add` resolves a different version to that which would be selected if I just wrote `aws-lc-sys = { version = "*", features = ["bindgen"] }` into the `Cargo.toml` myself. That means that the features it prints are the wrong ones.

### Steps

1. git clone --branch v/0.23.17 https://github.com/rustls/rustls.git
2. cd rustls
3. cargo add --dev --features bindgen "aws-lc-sys@*" --package rustls --verbose

### Possible Solution(s)

I think `cargo add` should reuse normal version resolution when asked for version "*"?

### Version

```text
cargo 1.81.0 (2dbb1af80 2024-08-20)
release: 1.81.0
commit-hash: 2dbb1af80a2914475ba76827a312e29cedfa6b2f
commit-date: 2024-08-20
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.8.0-DEV (sys:0.4.73+curl-8.8.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 24.4.0 (noble) [64-bit]
```

**Comment by epage** [comment]
This looks like a duplicate of #14648. See that issue for context on what is going on.

**Comment by ctz** [comment]
Thanks!
