### ISSUE TITLE
Add option to omit the hash value when building a library

### ISSUE THREAD

**Issue by nwin** [rust-lang/cargo#1484]
At the moment it is not really practical to build a library with cargo that is intended to be linked from a C program.

As the hash is added to the lib, the C program has to be rebuild every time the rust library is changed although this is unnecessary. This will get really problematic on an OS level where you would have to update tons of depending libs instead of just patching the flaw in a single file.

**Comment by alexcrichton** [comment]
> As the hash is added to the lib, the C program has to be rebuild every time the rust library is changed although this is unnecessary. 

Can you elaborate on this a little more? Right now the best way to do this would be to set the `crate-type` in the manifest to `"staticlib"` and then use the final library when linking into C. It does mean you have to guess the hash, which is unfortunate, but I'm not sure where it forces rebuilds?

**Comment by nwin** [comment]
> Right now the best way to do this would be to set the crate-type in the manifest to "staticlib" and then use the final library when linking into C.

This works of course, but not common practice…

> but I'm not sure where it forces rebuilds?

Maybe it is just my lack of understanding but if I naïvely compile my program it depends on the library having exactly that name (including the hash). The problem is, that the hash value gets written into the .dylib itself. So renaming doesn’t help.

    $ mv libgif-<hash>.dylib libgif.dylib
    $ cc -lgif test.c
    $ ./a.out
    dyld: Library not loaded: libgif-<hash>.dylib
      Referenced from: ./a.out
      Reason: image not found
    Trace/BPT trap: 5

So if cargo now changes the hash even guessing doesn’t help.
