### ISSUE TITLE
Feature Request: Allow cargo to specify the directory to run in

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/cargo#1485]
This would just be a nice feature for interfacing with other build systems, like Make. Currently, you have to

```bash
cd dir && cargo build
```

whereas, in this case you could just

```bash
cargo build --directory dir
```

This would be nice for integration with things like vim's `make` command, because cargo currently gives the wrong file: as if `dir` is the base directory, not `dir/..`.

**Comment by alexcrichton** [comment]
This is actually already possible! If you do `cargo build --manifest-path=dir/Cargo.toml` it should do the trick.

**Comment by GBGamer** [comment]
Thanks! I'm sorry for wasting y'all's time :stuck_out_tongue_closed_eyes:

**Comment by alexcrichton** [comment]
No worries, thanks for the issue regardless!

**Comment by 1480c1** [comment]
Sorry for the necro, but a quick question, does the `--manifest-path=dir/Cargo.toml` thing also apply to commands other than build, like for example third-party cargo sub-commands? I personally am searching for something similar to `make`'s, `ninja`'s, and `git`'s `-C` option that applies command wide and this was one of the first results that popped up

**Comment by Bobbbay** [comment]
@1480c1 I would most recommend you test it out yourself! 😉

**Comment by mikhail-putilov** [comment]
It's such a pity that every tool requires its own name for the same concept. Maven requires '-o', git '-C' and cargo '--manifest-path' :-(

**Comment by weihanglo** [comment]
This is already possible via an [unstable flag `-C`](https://doc.rust-lang.org/cargo/commands/cargo.html#option-cargo--C). See <https://github.com/rust-lang/cargo/issues/10098> for more.
