### ISSUE TITLE
Platform specific dependencies in Cargo.lock?

### ISSUE THREAD

**Issue by dan-t** [rust-lang/cargo#1487]
Hi,

the `term[1]` library has the dependencies  `winapi` and `kernel32-sys`
which seem to be only relevant for the windows platform, but they're
still listed in the `Cargo.lock` file on other platforms, in my case linux.

Is this a bug or a feature?

Greetings,
Daniel

[1] https://github.com/rust-lang/term/blob/master/Cargo.toml

**Comment by steveklabnik** [comment]
IIRC, it's a feature. You still have to do full resolution to make sure the versions are right, even if it's not used on that platform.

**Comment by alexcrichton** [comment]
@steveklabnik is correct! The pathological case here is that each time you build a library on a different platform the `Cargo.lock` changes, making it quite difficult to track the versions being used!
