### ISSUE TITLE
Stack offset of *** exceeded max offset of 4096 by **** bytes, please minimize large stack variables

### ISSUE THREAD

**Issue by Kelvin-1013** [rust-lang/cargo#14907]
### Problem

I saw this problem so many times, but still suceeded in build
If I didn't fix this problem what happened?

`Error: Function _ZN122_$LT$lb_clmm..instructions..initialize_permission_lb_pair..InitializePermissionLbPair$u20$as$u20$anchor_lang..Accounts$GT$12try_accounts17h838b3530f022d855E Stack offset of 4640 exceeded max offset of 4096 by 544 bytes, please minimize large stack variables
`
`
   Compiling dynamic-amm v0.1.0 (https://github.com/mercurial-finance/mercurial-dynamic-amm-sdk?rev=7be5237e9d688f83d40df71278fdbd6ec2d42979#7be5237e)
Error: Function _ZN129_$LT$dynamic_amm..instructions..initialize_permissionless_pool..InitializePermissionlessPool$u20$as$u20$anchor_lang..Accounts$GT$12try_accounts17h39927b5d6ea3a7f4E Stack offset of 7600 exceeded max offset of 4096 by 3504 bytes, please minimize large stack variables
Error: Function _ZN140_$LT$dynamic_amm..instructions..initialize_permissionless_pool..InitializePermissionlessPoolWithFeeTier$u20$as$u20$anchor_lang..Accounts$GT$12try_accounts17hf88f2863e5ecac54E Stack offset of 7600 exceeded max offset of 4096 by 3504 bytes, please minimize large stack variables
Error: Function _ZN125_$LT$dynamic_amm..instructions..initialize_permissioned_pool..InitializePermissionedPool$u20$as$u20$anchor_lang..Accounts$GT$12try_accounts17hbbcbf85262bf970bE Stack offset of 7536 exceeded max offset of 4096 by 3440 bytes, please minimize large stack variables
`

### Version

```text

```

**Comment by epage** [comment]
This looks like its related to the compiler or compilation of a specific library, and not Cargo.  You might have a better chance of finding an answer on the [user forums](https://users.rust-lang.org/).

**Comment by wizasol** [comment]
plz decrease instruction calc size or increases compute budge unit
