### ISSUE TITLE
Dev dependency specific features are activated when building released

### ISSUE THREAD

**Issue by Kayanski** [rust-lang/cargo#14905]
### Problem

When importing a library in dependencies and this same library with features inside `dev-dependencies`, the feature seems to be active when building for `release`.

We expect dev-dependencies and their features to be ignored when building for release.
This issue seems specific to working with workspaces. I couldn't reproduce the issue with only crates.

### Steps

To reproduce, please visit the reproduction repo (https://github.com/Kayanski/rust-compiler-bug-repr). The README there gives you more details, but this command will yield an unwanted compilation error : 
`cd crate3 && cargo build --release`

### Version

```text
Here are the versions I am using : 
cargo 1.83.0 (5ffbef321 2024-10-29)
rustc 1.83.0 (90b35a623 2024-11-26)
```

**Comment by epage** [comment]
If I apply the following to `crate3/Cargo.toml`, it works
```diff
[workspace]
members = ["./crate3"]
+resolver = "2"
```

`crate3` has
```toml
[package]
name = "crate3"
version = "0.1.0"
edition = "2021"
resolver = "2"
```

`resolver = "2"` is a workspace-wide setting and is ignored in packages unless they are published at which point that becomes the workspace root.

When a workspace root has a package in it, it will read from `package.resolver` and then fallback to `package.edition`.  However, in this case there is no package in the workspace root.

To help with this, `cargo build --release` was reporting the following messages
```
warning: resolver for the non root package will be ignored, specify resolver at the workspace root:
package:   /home/epage/src/personal/dump/rust-compiler-bug-repr/crate3/crate3/Cargo.toml
workspace: /home/epage/src/personal/dump/rust-compiler-bug-repr/crate3/Cargo.toml
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021
which implies `resolver = "2"`
```

See also https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions

As this seems to be a matter of what resolver is used and we provide diagnostics to help with it, this seems resolved and I'm going to go ahead and close.  If there is a reason for us to re-evaluate this, let us know!
