### ISSUE TITLE
Weird behavior when `cargo add` dep (workspace) to dependencies

### ISSUE THREAD

**Issue by cxw620** [rust-lang/cargo#14904]
### Problem

The workspace dependencies:
![Image](https://github.com/user-attachments/assets/4afcf7e1-81f1-487b-9a32-071208324552)

The `Cargo.lock`
![Image](https://github.com/user-attachments/assets/2e55860f-3d98-40a0-864a-7dffe9848f72)

However, when I run the command like `cargo add --package my_package chrono --features std`, cargo complains:
```
    Updating crates.io index
      Adding chrono (workspace) to dependencies
error: unrecognized feature for crate chrono: std
disabled features:
    rustc-serialize, serde
```

`rustc-serialize, serde` are actually the features of `chrono@=0.4.0` instead of `chrono@=0.4.38`.

`workspace.resolver` is set to "3", edition 2024.

### Version

```text

```

**Comment by epage** [comment]
Can you share your `workspace.dependencies`?

Most likely what is happening is your version requirement in `workspace.dependencies` is low enough to include a version with `rustc-serialize` and `serde`.

Dependencies specify a version requirement which includes support for a range of supported versions. To aid users in supporting the full range of their version requirement, `cargo add` only validates against and lists features for the lowest version within the range, making the assumption that features are not removed as that is a breaking change. 

See also
- #14832
- #14648

**Comment by cxw620** [comment]
> Can you share your `workspace.dependencies`?

`chrono = { version = "0.4", default-features = false }`.

![Image](https://github.com/user-attachments/assets/5aa8a709-23e4-4e5c-8907-dd7ac6a54c2a)

If I set to `0.4.38` instead of `0.4`, it works well.

![Image](https://github.com/user-attachments/assets/ba21e08d-b841-4af7-8984-d621e65c022b)

According to your explanation in #14648, the oldest version compatible with `0.4` is `0.4.0`...

Thank you for your reply and I will close the issue.
