### ISSUE TITLE
Cache issue when multiple targets are used

### ISSUE THREAD

**Issue by psibi** [rust-lang/cargo#14918]
### Problem

When different targets are used, cargo marks the external crate as a dirty package and re compiles them again. This seem to happen only in CI systems and I couldn't reproduce it locally.

### Steps

I have reproduced it in this repository: https://github.com/psibi/cross-cache-issue

These are the steps to reproduce it in a CI action:
- Make sure you cache ~/.cargo and the target directory in the CI system.
- Create a small binary which has some external dependency
- Compile it for some platform:
  - `cargo test --workspace --release --no-run --locked --target x86_64-unknown-linux-musl --verbose`
- Compile it for some other platform:
  - `cargo test --workspace --release --no-run --locked --target x86_64-unknown-linux-gnu --verbose`
- Make sure to do initial run so that it builds and stores cache.
- In the subsequent run, I can see output like this:

```
       Dirty proc-macro2 v1.0.92: the path to the source changed
   Compiling proc-macro2 v1.0.92
```

And as you can see it compiles the dependency again. The above bug disappears if I use only one target (i.e. remove one of the cargo command so that only one target is exercised)

### Possible Solution(s)

There are some workarounds to avoid the above issue:

- Have separate target directories. You can use the option `target-dir` to specify a different directory and then cache it. No recompilation happens in that case.
- Crate a new job for each target compilation i.e. Do not mix different targets in the same github action job.

### Version

```text
cargo 1.81.0 (2dbb1af80 2024-08-20)
release: 1.81.0
commit-hash: 2dbb1af80a2914475ba76827a312e29cedfa6b2f
commit-date: 2024-08-20
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.8.0-DEV (sys:0.4.73+curl-8.8.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.4.0 (jammy) [64-bit]
```

**Comment by epage** [comment]
Could you update the workflow with `CARGO_LOG=cargo::core::compiler::fingerprint=trace` set?

**Comment by weihanglo** [comment]
* https://github.com/psibi/cross-cache-issue/actions/runs/12280621981/job/34267493466 — after adding CARGO_LOG it
* https://github.com/psibi/cross-cache-issue/actions/runs/12289755018/job/34295769930

Looks like cache works fine now. I assume the previous cache was corrupted, or [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache) isn't compatible with cross or other tools, or you have both `action/cache` and `Swatinem/rust-cache` and I don't know if they are compatible.

From `Swatinem/rust-cache`:

> The ~/.cargo/registry/src directory is not cached since it is quicker for Cargo to recreate it from the compressed crate archives in ~/.cargo/registry/cache.

This might be an issue when build script instruction `cargo::rerun-if-changed` points to a directory, as directory mtime is set at the `.crate` file unpacking time. Though this is not your situation.


Going to close this as resolved. If you find more odd things Cargo did, let us know.
