### ISSUE TITLE
std::env `env!` Cannot expand binary crate name for helper libraries

### ISSUE THREAD

**Issue by Redhawk18** [rust-lang/cargo#14936]
Hi everyone, my first issue. I've run into this situation a few times, where I structure my projects as libraries of a very small binary crate. This is because of the speed up that happens from this, I forget exactly what it's called. [However one major disadvantage of doing this is you lose access to a lot of the env variables that binary crates have. ](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates)

This is a good example, but I've had many in the past.
```rs
fn list_profiles() -> Vec<Profile> {
    let path = config_dir()
        .expect("Unsupported platfrom by `dirs` crate")
        .join(env!("CARGO_BIN_NAME").to_owned() + "/LethalCompany" + "/profiles");

    debug!("Looking for config path at {:?}", path);

    // ...
```
It just seems silly to me that this is a limitation of this great language. I should never have to choose to make my project slower to compile because of a silly macro not expanding correctly. Ideally this code *should* just work whether or not if this code is in my binary crate or a helper library.

**Comment by weihanglo** [comment]
I am not sure if I understand it correctly. You want to access `CARGO_BIN_NAME` inside a `[lib]` target, right? If yes, could you elaborate more on the reason and your use case behind?

Note that usually `[lib]` doesn't know about which `[[bin]]` will depend on it. That is, when a `[lib]` compiles it doesn't know what `CARGO_BIN_NAME` is going to expand to.

**Comment by Redhawk18** [comment]
> I am not sure if I understand it correctly. You want to access `CARGO_BIN_NAME` inside a `[lib]` target, right? If yes, could you elaborate more on the reason and your use case behind?
> 
> Note that usually `[lib]` doesn't know about which `[[bin]]` will depend on it. That is, when a `[lib]` compiles it doesn't know what `CARGO_BIN_NAME` is going to expand to.

Yes, because of dep parallel compilation is faster when a project is split up my project looks like this.
```
mod-loader v0.1.0 (/home/redhawk/code/mod-loader)
├── mod-loader_gui v0.1.0 (/home/redhawk/code/mod-loader/gui)
│   ├── dirs v5.0.1
│   │   └── dirs-sys v0.4.1
│   │       ├── libc v0.2.168
│   │       └── option-ext v0.2.0
│   ├── iced v0.13.1
...
```

Where I have many libraries just to keep other deps lower for faster compile times. The con of this is that env variable is no longer accessible. So I have to trade faster compile time or this variable working properly.

**Comment by Redhawk18** [comment]
I got around this by just making a consist in the gui library above, but that obviously isn't ideal.

**Comment by weihanglo** [comment]
> I got around this by just making a consist in the gui library above, but that obviously isn't ideal.

Is the mod-loader_tui a bin crate? 

By the nature of dependency relation, I don't think lib can expand `env!` compile time to get a value it doesn't even know. Making env an function argument and letting bin crate pass it is what I can think of now. Or alternatively export another macro wrap `env!` so it will delay the expansion on call site

**Comment by Redhawk18** [comment]
> > I got around this by just making a consist in the gui library above, but that obviously isn't ideal.
> 
> Is the mod-loader_tui a bin crate?
> 
> By the nature of dependency relation, I don't think lib can expand `env!` compile time to get a value it doesn't even know. Making env an function argument and letting bin crate pass it is what I can think of now. Or alternatively export another macro wrap `env!` so it will delay the expansion on call site

Yes, but I don't understand what you mean about creating another macro that wraps around `env!`.

**Comment by weihanglo** [comment]
Make your `fn list_profiles()` a macro so it would be expanded at callsite.


BTW, where is `list_profiles` defined, a dependency of `mod-loader`?
Having a minimal reproducible example would help explore workaround.

**Comment by Redhawk18** [comment]
> Make your `fn list_profiles()` a macro so it would be expanded at callsite.
> 
> BTW, where is `list_profiles` defined, a dependency of `mod-loader`? Having a minimal reproducible example would help explore workaround.

[Here, I pushed and linked the entire project.](https://github.com/Redhawk18/mod-loader/blob/207b61b9cc30ad3b1c9d7bcd12da4aab4f14273e/gui/src/screens/profile.rs#L52) This should be a good mre to review.

**Comment by weihanglo** [comment]
I see. Thanks for the MRE.

In this case, you're inverting the dependency relation. `mod-loader_gui`, as a dependency of `mod-loader` should know nothing about who is using it. I don't foresee anything Cargo will make any change to break the dependency relation.

I am not familiar with iced. By just looking at how [`iced::application`](https://docs.rs/iced/latest/iced/application/fn.application.html) works, you might want to add an `&str` argument to `fn run()`, and call `mod_loader_gui::run(std::env!("CARGO_BIN_NAME"))` so you bin has access to some env vars. With that you could also have more runtime configuration logic in bin, and make a generic `AppConfig` struct to pass into `fn run()`. As a result, when you test and change any config-related settings, say you want to change "/LethalCompany/profiles" path to "MyAwesomeAppCompany/profiles", you then don't need to recompile lib `mod_loader_gui`.

**Comment by Redhawk18** [comment]
> I see. Thanks for the MRE.
> 
> In this case, you're inverting the dependency relation. `mod-loader_gui`, as a dependency of `mod-loader` should know nothing about who is using it. I don't foresee anything Cargo will make any change to break the dependency relation.

No I understand this why it works like this, and I could pass it through iced. But if this is required through a deeper crate that has more common code that the gui crate depends on then I would have the same problem.

**Comment by weihanglo** [comment]
If you have a deeper crate that is under your control, you could make then accept `AppConfig` struct as well. This is better when you have more run time logic when you break gui to more crate, and don't need to recompile because of any compile-time env change.

If the deeper crate is from crates.io, it is unlikely to happen because `[lib]` crate never compile with `env!("CARGO_BIN_NAME")` exists. It will just fail to upload when running `cargo publish`.

Another scenario this is unlikely to be supported: If you have 3 `[[bin]]` crates depending on the same lib, you then need to compile the lib three times because each of them expands `CARGO_BIN_NAME` to differents name at compile time. This doesn't make the compilation faster.

**Comment by Redhawk18** [comment]
That's a good point, maybe the approach isn't to expand `CARGO_BIN_NAME` but instead somehow embed consist into the cargo.toml that can be set at compile time for non-build scripts?

**Comment by weihanglo** [comment]
You could have `package.metadata` or `workspace.metadata` in your Cargo.toml and use whatever tool to help you inject compile time environment variable when building.
(Note that Cargo doesn't support workspace inheritance for `package.metadata`, as it is intended to be read and used by external tools directly)

The other way is defining your environment variable in  [the `[env]` table](https://doc.rust-lang.org/nightly/cargo/reference/config.html#env) in `.cargo/config.toml`, so they would be picked up automatically when compiling.

--- 

The most similar feature request you may be interested in is <https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618>. However, I don't think it is really relevant and still think a runtime config struct is better for things like for application, see some examples,

* https://github.com/sharkdp/bat/blob/3e07483f7a5b54ce574485ce38792c70a675e05d/src/bin/bat/main.rs#L316-L321 — a popular CLI `bat` loading config and asset files in bin crate.
* https://github.com/rust-lang/cargo/blob/769f622e12db0001431d8ae36d1093fb8727c5d9/src/bin/cargo/main.rs#L24 — Cargo itself reads and setup configuration in `fn main()`.

---

Upon this point, I am going to close as not-planned, specifically for supporting reading bin-only env in lib crate. Please refer to other feature requests and alternatives. Thank you.
