### ISSUE TITLE
home 0.5.11 MSRV is now v1.81.0

### ISSUE THREAD

**Issue by imdanielsp** [rust-lang/cargo#14950]
This morning I noticed that one of my pipeline is failing with the latest `home` release as the MSRV is 1.81.0 now (a 11 versions jump from home's 0.5.9). Surely I have to add `--locked` to my pipeline, but I just wanted to make sure that this is required for a minor release.

**Comment by epage** [comment]
See #14944, closing in favor of that

**Comment by imdanielsp** [comment]
Thanks @epage!
