### ISSUE TITLE
`cargo cache -r all` duplicates its output

### ISSUE THREAD

**Issue by sudo-nice** [rust-lang/cargo#14971]
### Problem

The command: `cargo cache -r all` produces the following output. As you can see, the bottom part is duplicated (which should not be the case, IMO):

    removing: '/mnt/ssd1/rust/cargo/git/db'
    removing: '/mnt/ssd1/rust/cargo/git/checkouts'
    removing: '/mnt/ssd1/rust/cargo/registry/src'
    removing: '/mnt/ssd1/rust/cargo/registry/cache'
    removing: '/mnt/ssd1/rust/cargo/registry/index'
    Cargo cache '/mnt/ssd1/rust/cargo':

    Total:                           211.67 MB
      15 installed binaries:         211.67 MB
      Registry:                           0  B
        0 registry indices:               0  B
        0 crate archives:                 0  B
        0 crate source checkouts:         0  B
      Git db:                             0  B
        0 bare git repos:                 0  B
        0 git repo checkouts:             0  B

    Cargo cache '/mnt/ssd1/rust/cargo':

    Total:                           211.67 MB
      15 installed binaries:         211.67 MB
      Registry:                           0  B
        0 registry indices:               0  B
        0 crate archives:                 0  B
        0 crate source checkouts:         0  B
      Git db:                             0  B
        0 bare git repos:                 0  B
        0 git repo checkouts:             0  B

### Version

```text
cargo-cache 0.8.3

cargo 1.85.0-nightly (99dff6d77 2024-12-18)
release: 1.85.0-nightly
commit-hash: 99dff6d77db779716dda9ca3b29c26addd02c1be
commit-date: 2024-12-18
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Debian 11.0.0 (bullseye) [64-bit]
```

**Comment by epage** [comment]
‘cargo-cache` is not maintained here. This would better be reported at https://github.com/matthiaskrgr/cargo-cache
