### ISSUE TITLE
cargo install'ing multiple outdated but installed crates only installs one crate

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/cargo#14988]
### Problem

`cargo install` accepts a list of crates. if given a list of crates where all crates are already installed and more than one is outdated, only the leftmost outdated crate in the list will be installed.

### Steps

Have all of these crates installed with some subset of them not the latest:

-  bindgen-cli
-  cargo-about
-  cargo-bisect-rustc
-  cargo-bloat
-  cargo-deny
-  cargo-diet
-  cargo-expand
-  cargo-fuzz
-  cargo-geiger
-  cargo-insta
-  cargo-mutants
-  cargo-nextest
-  cargo-outdated
-  cargo-tally
-  cargo-udeps
-  flamegraph
-  ucd-generate

Run:

```
cargo install --locked \
              bindgen-cli \
              cargo-about \
              cargo-bisect-rustc \
              cargo-bloat \
              cargo-deny \
              cargo-diet \
              cargo-expand \
              cargo-fuzz \
              cargo-geiger \
              cargo-insta \
              cargo-mutants \
              cargo-nextest \
              cargo-outdated \
              cargo-tally \
              cargo-udeps \
              flamegraph \
              ucd-generate
```

Observe that cargo detects all crates are already installed but then only compiles a new version for the first outdated crate in the arg list.

### Version

```text
cargo 1.83.0 (5ffbef321 2024-10-29)
release: 1.83.0
commit-hash: 5ffbef3211a8c378857905775a15c5b32a174d3b
commit-date: 2024-10-29
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.1.1 [64-bit]
```

**Comment by weihanglo** [comment]
would you mind minimizing the reproducible example? The description of it now is vague and we don't know what should be installed and what shouldn't. Perhaps also give an exact set of input and expected output?

**Comment by lopopolo** [comment]
I lost my scrollback buffer and haven't been able to minimize or reproduce in ~30 minutes so I'll go ahead and close this.

**Comment by weihanglo** [comment]
No worries at all. Feel free to reopen when you manage to have an MRE :)
