### ISSUE TITLE
Globally set transitive features (especially for FIPS), or block certain features

### ISSUE THREAD

**Issue by xnox** [rust-lang/cargo#14984]
### Problem

I want to compile application with FIPS approved cryptography only (for example by using boringssl rustls provider in fips mode; or by using rustls with the aws-lc-fips-sys provider).

My package/workspace has many dependencies, and they in turn have multiple declarations to rustls.

Despite setting my toplevel rustls features to use aws-lc-fips-sys, transitive dependencies that have repeated rustls dependencies may activate default features and pull in rustls again but with non-fips provider.

Ideally when compiling application and choosing rustls with aws-lc-fips-sys, I want to prevent non-fips feature being pull in; or able to inspect this.

Building binaries with cargo-auditable appears to indicate that it often is trivially possible to link two rustls implementations aws-lc-sys & aws-lc-fips-sys.

Is there a way to globally enforce cargo dependencies and features? to only pull in one rustls with desired features and no other ?

### Proposed Solution

File bug reports against all rustls dependants asking them to add a feature that pulls in rustls with FIPS feature; rather than with default feature. (Currently 945 https://crates.io/crates/rustls/reverse_dependencies )

Somehow make rustls by default have no features activated, and allow dependency resolution to always happen without any features for the packages; yet allow each one of them to choose desired feature set for the compiled binaries - such that packages/library dependencies do not impose a feature selection; yet all individual binaries can make a choice.

Ask rustls to default to a FIPS implementation by default..... Or somehow locally override default rustls features to be FIPS.

### Notes

Related:
- https://github.com/rustls/webpki/issues/307
- https://github.com/rustls/webpki/pull/308
- https://github.com/rustls/rustls/pull/2291
- https://github.com/istio/ztunnel/issues/1404
- https://github.com/rust-lang/cargo/issues/3126
- https://github.com/rust-lang/cargo/issues/2980

**Comment by weihanglo** [comment]
FWIW, aws-lc-sys is worse in the opposite way in this situation. Usually the `package.links` field is set to a string that ensures for the same string, only one unique version of native dependency exists in the dependency graph. However, aws-lc-sys bumps the field for each release. That is the reason you could have muliple versions of the native dependencies.
https://github.com/aws/aws-lc-rs/blob/0470373fe2ac92391085d928099e9d2c2292e5cd/aws-lc-sys/Cargo.toml#L5

**Comment by xnox** [comment]
@weihanglo sounds good! And this issue is useful as is, as a pseudo index-reference to all of these things.

Indeed, all of this is complicated.

**Comment by xnox** [comment]
Separately, for example "openssl-provider" of rustls is not a default features; so yeah without any tooling support it is not possible to force the whole workspace (and all transitive deps) to drop default features and allow one at build time to "and please pull in this rustls provider by default".

At this point I am pondering to fork crates.io to somehow republish the world with dependencies that I desire =/ but that's completely impractical solution.
