### ISSUE TITLE
On windows, use SetDllDirectory when dynamically linking libraries.

### ISSUE THREAD

**Issue by LaylConway** [rust-lang/cargo#1500]
Currently results from cargo that need a .DLL on windows aren't runable until you copy over the .DLLs from their out directories to the folder the .exe is in. Making the .exe use SetDllDirectory before trying to load the DLLs should fix this without having to move the DLLs in the build result.

MSDN Reference for SetDllDirectory:
https://msdn.microsoft.com/en-us/library/ms686203(VS.85).aspx

Moved over from:
https://github.com/rust-lang/rust/issues/24226

**Comment by alexcrichton** [comment]
I think there's a few issues in play here, and neither `cargo` nor `rustc` will likely call these functions for you unfortunately:

* I [share the fears](https://github.com/rust-lang/rust/issues/24226#issuecomment-91220913) of @nagisa that calling this function in an executable is at a point that's too late in execution. That primarily affects `LoadLibrary` which is not how linked libraries are loaded.
* This would imply that cargo/rustc is injecting code into binaries, which is a pretty big no no.
* When shipping dynamic libraries, these same worries show up on unix and OSX, so solving it only on Windows probably wouldn't be the right thing to do.

For now I would recommend not building DLLs as part of cargo. Instead you can build all Rust libraries as rlibs (e.g. don't specify a dylib). For native dependencies you control, I would recommend building them all as static libraries, and for distribution right now it's basically best practice to ship any required DLLs next to the binary you're shipping as well.

Thanks for the issue though!
