### ISSUE TITLE
Cargo not being conservative enough when deciding what to rebuild

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/cargo#1503]
I have a library that I'm working on that takes a long time to build.  But when I work on examples for the library I run into this problem.

1. `cargo run --example example_foo`
  * Builds the library
  * Builds example_foo
2. Edit just example_foo
3. `cargo run --example example_foo`
  * Builds the library
  * Builds example_foo

My problem with this is that the library shouldn't be built on the 2nd time around if nothing in the library was modified.  My library takes 3-4 minutes to compile, so it's a huge time sink.

**Comment by alexcrichton** [comment]
Does your library also have a build script? I tried this out locally without one and it looks like it all worked as expected.

**Comment by TyOverby** [comment]
No build script.

**Comment by alexcrichton** [comment]
Do you have some example code that I could try this out with?

**Comment by TyOverby** [comment]
I'm trying to repro on something smaller, but it looks like I was mistaken.  Cargo prints the message "compiling library_name v0.0.1" regardless of if it is actually building the library or just the example (hence my confusion).  

I guess my examples musts just be taking forever to link.
