### ISSUE TITLE
Add `--offline` option to `cargo search`

### ISSUE THREAD

**Issue by gentoo90** [rust-lang/cargo#1506]
... which doesn't show any results if wasn't able to update the index.
Similar to #1031, #1072.
`cargo query` or `info` (#948) should also have it probably.

**Comment by alexcrichton** [comment]
Unfortunately `cargo search` works by hitting the crates.io server to run a query. I don't think we want to duplicate that right now in Cargo itself, but perhaps #948 could include something about not hitting the registry itself!
