### ISSUE TITLE
cargo run should be able to pass parameters to program

### ISSUE THREAD

**Issue by arnm** [rust-lang/cargo#1513]
I'd like for ```cargo run``` to be able to pass parameters to the program being ran. This would be tremendously useful, especially for cli programs.

```cargo run``` already runs the program, why not make this feature more powerful?

Thoughts?

**Comment by steveklabnik** [comment]
Cargo already does this, try cargo run -- foo.

**Comment by arnm** [comment]
Awesome. Missed that in the help message. Closing this issue. Thanks
