### ISSUE TITLE
Be lazy when attempting a download of rust nightlies and cargo snapshots

### ISSUE THREAD

**Issue by lloeki** [rust-lang/cargo#1525]
`./travis.install.deps.sh` and `src/etc/dl-snapshot` unconditionally redownload with curl, whether the file is present or not. It would be extremely friendly to networks and package maintainers if those could call curl with either `-C -` or be tested out for file existence, making pre-copying of the files possible by package build tools able to download, validate, and cache dependencies.

Alternatively, it is stupendously annoying to wait for the download when operating on a slow link, especially when retrying builds.

In any case, in the rare event of a partial or corrupted download, the user's course of action would be perfectly obvious, especially given the targeted crowd.

**Comment by gentoo90** [comment]
To prevent snapshot downloading you can run `./configure` with `--local-cargo=<PATH TO CARGO BINARY>` option

**Comment by alexcrichton** [comment]
This script is now gone, so closing.
