### ISSUE TITLE
Argument parsing seems wrong

### ISSUE THREAD

**Issue by posix4e** [rust-lang/cargo#1526]
```
posix4e@posi:~/projects/eventual$ cargo test -h
Execute all unit and integration tests of a local package

Usage:
    cargo test [options] [--] [<args>...]

Options:
    -h, --help               Print this message
    --test NAME              Name of the integration test to run
    --bin NAME               Name of the binary to run tests for
    --no-run                 Compile, but don't run tests
    -p SPEC, --package SPEC  Package to run tests for
    -j N, --jobs N           The number of jobs to run in parallel
    --features FEATURES      Space-separated list of features to also build
    --no-default-features    Do not build the `default` feature
    --target TRIPLE          Build for the target triple
    --manifest-path PATH     Path to the manifest to build tests for
    -v, --verbose            Use verbose output
```

Implies that 
```
 cargo test -- --verbose --test ....
```
But it gets

```
thread '<main>' panicked at '"Unrecognized option: \'verbose\'."', /home/posix4e/projects/rust/src/libtest/lib.rs:255
```

What actually works is
```
cargo test --verbose -- --test ....
```
I'd love to get this done? Is anyone already working on this?

**Comment by alexcrichton** [comment]
The placement of the `--` is actually pretty significant here. Everything afterwards is passed blindly to the underlying test binary, which in this case is the test harness built by the compiler. In the first example you gave you're passing `--verbose` to the binary (it's after the `--`) and the binary doesn't accept that flag (hence the failure). In the second case you're passing `--verbose` to cargo but you're passing `--test` to the binary (which the test runner does accept).

I think this is all working as expected though, so I'm going to close this for now. Let me know if there's any more trouble though!

**Comment by svark** [comment]
I ran into a similar error running
` cargo test -no-run`
  
```
Running <target>
thread 'main' panicked at '"Unrecognized option: \'n\'."', ../src/libtest/lib.rs:246
<stack trace>
error: test failed
```
  Note that -no-run was passed instead of --no-run.  The error is quite misleading. Please reconsider fixing this.

**Comment by alexcrichton** [comment]
@svark that actually looks like it's coming from libtest in the rust-lang/rust repository, can you open a bug over there for that?
