### ISSUE TITLE
Multiple --package parameters

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#1528]
If `foo` is a dependency, I can run its tests with `cargo test -p foo` or `cargo test --package foo`.

I’d like to test many dependencies with `cargo test -p foo -p bar -p baz` and take advantage of Cargo’s built-in parallelism.

Currently, a `cargo` command only accepts at most one `-p` parameter. So I have to run multiple commands: `cargo test -p foo && cargo test -p bar && cargo test -p baz`. These commands can not run in parallel with each other because of #354.

This also applies to other Cargo commands (`build`, `doc`, `bench`, …) that accept `--package`.

**Comment by fhahn** [comment]
I would like to look into this. Would you mind elaborting on Cargo’s built-in parallelism briefly, just as a starting point?

**Comment by alexcrichton** [comment]
@fhahn all of Cargo's parallelism is based on an internal [`DependencyQueue`](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/dependency_queue.rs), if that queue determines two tasks as not depending on one another then they will be run in parallel automatically.

In the case of testing multiple packages, they'll already be inferred to not depend on one another, so they just need to be added to the job graph and the backend should take care of the rest.

**Comment by fhahn** [comment]
Thanks @alexcrichton. I had a closer look and just want to make sure I understand correctly. It seems like compiling multiple packages that should be tested could be parallelized by passing multiple targets to ```ops::compile_targets```. The actual execution of the tests does not seem to be backed by a task queue. Should the tests be executed in parallel as well?

**Comment by alexcrichton** [comment]
Nah currently tests are already internally parallelized so it's fine to not execute them in parallel, we just need to make sure to build them in parallel.

**Comment by fhahn** [comment]
At the moment I am looking for ways to compile tests for two packages in parallel. Currently I am trying to create targets for the test files of two packages, but after adding them to the queue in with [compile](https://github.com/fhahn/cargo/commit/ef09b3fbfee121634238b1bed3fda8e166ae2fd1#diff-59acd1a3101aebbb591ac7ab51c19d9eR130), the queue seems to hang. Does this approach sound reasonable at all?
 Unfortunately, I am not sure where the best place would be to add the tests of multiple packages to the queue.

**Comment by alexcrichton** [comment]
Perhaps that's adding duplicate entries to the dependency graph? The input may just want to change from a package + slice of targets to just a slice of package + targets
