### ISSUE TITLE
Docs should not be built for build-dependencies

### ISSUE THREAD

**Issue by nathan7** [rust-lang/cargo#1529]
Currently, if I depend on `gcc`, the docs for it show up in my package.
I'm working around this with `--no-deps`, but ideally I'd have docs for my regular dependencies.

**Comment by nixpulvis** [comment]
Maybe we're saying the same thing, but I'd like a way to have the docs generated for all of my *direct* dependencies, but not their dependencies. In fact I'd argue this should be the default behavior.

If I add a crate `bar` as a dependency of the crate I'm working on `bar`, then I'd love to see both `foo` and `bar`'s documentation. However, if `bar` needs `baz` I frankly couldn't care less, as that's the decision of `bar` and I shouldn't need to look up anything in `baz`.

**Comment by alexcrichton** [comment]
Oh! This was actually [fixed recently](https://github.com/rust-lang/cargo/pull/1974).

@nixpulvis could you open an issue for that? Seems like a useful option to have for `cargo doc`!
