### ISSUE TITLE
Environment variables should be documented outside of build scripts section

### ISSUE THREAD

**Issue by niconii** [rust-lang/cargo#1538]
There are a number of environment variables which Cargo exposes to programs, such as `CARGO_MANIFEST_DIR`, which is useful for the very common case of reading/writing files relative to the crate root.

However, despite their utility, currently they are only documented in the [Build Script Support](http://doc.crates.io/build-script.html) section of the documentation, which is problematic as it is not obvious to look there if you need them outside of build scripts, nor is it obvious that some (if not all) of the listed environment variables are also available for actual crates via `cargo run`.

**Comment by blaenk** [comment]
Yeah, this is better than having to grep through the source.
