### ISSUE TITLE
Cargo and the shell 

### ISSUE THREAD

**Issue by icorderi** [rust-lang/cargo#1541]
Hey, not sure where to bring this up. 

I created a **shell** project ([crate], [github]) by moving [cargo/core/shell.rs] into it's own project.
It seemed like something people would like to use when building command line applications.

Let me know if you guys think it's worth keeping a separate crate from cargo for the shell and shell utilities. I'm happy to transfer ownership if you guys want to keep it under rust-lang. 

Keep up the good work,
-n

[crate]: https://crates.io/crates/shell
[github]: https://github.com/icorderi/shell.rs
[cargo/core/shell.rs]: https://github.com/rust-lang/cargo/blob/master/src/cargo/core/shell.rs

**Comment by alexcrichton** [comment]
Oh wow, thanks! I think for now we'll probably stick to the status quo, but I'm sure this will be quite useful to others! Next time I'm looking into refactoring this code I can probably switch to the external crate.
