### ISSUE TITLE
Cargo has no way of producing an output that can be run outside of cargo.

### ISSUE THREAD

**Issue by LaylConway** [rust-lang/cargo#1544]
When `cargo build` is run, even in --release, it builds an output that can only be run through `cargo run` with DLLs spread all over the place. It is a major headache to produce anything that can be published and run on non-development computers. This makes rust nearly unusable for me for any applications as copying over the DLLs manually (that aren't always in expected places) is tedious and error-prone. Static linking is not an option as even with everything else statically linked, gcc's runtime is not.

**Comment by alexcrichton** [comment]
Could you be a little more specific about what DLLs are in play? Cargo does not specifically build dynamic libraries, and the compiler emits static libraries with static linkage by default, so it could be that the specific libraries you are using are building DLLs and may need to be modified.

**Comment by LaylConway** [comment]
After a bit of trial and error, the main problem seems to be `libgcc_s_dw2-1.dll` when everything's statically linked. However I'm in a situation where I'll be needing dynamic linking for some crates so just copying along only the libgcc DLL will not solve the problem in that situation.

**Comment by alexcrichton** [comment]
Yes the story with `libgcc_s_dw1-1.dll` is [known today](https://github.com/rust-lang/rust/issues/20908), and it is a current technical detail of the compiler. As this doesn't have much to do with Cargo itself, though, I'm going to close this. Thanks anyway for the issue!
