### ISSUE TITLE
reports incorrect error when no src files are in src

### ISSUE THREAD

**Issue by jhigdon** [rust-lang/cargo#1547]
executing cargo build when src directory is empty returns the following incorrect diagnostic message

cargo build
failed to parse manifest at `C:\Development\rust\moocows\Cargo.toml`

Caused by:
  either a [lib] or [[bin]] section must be present

if rust src file is put into src directory cargo build works correctly

**Comment by jaredbeck** [comment]
To reproduce this error message:

```
cargo new foobar --bin
cd foobar
mv src/main.rs src/hello_world.rs
cargo build
```

The existing error message is not really sufficient to help a beginner diagnose this problem. :)

**Comment by alexcrichton** [comment]
Closing as a dupe of #1379, but thanks for the report!
