### ISSUE TITLE
bash completion fails on OS X

### ISSUE THREAD

**Issue by jeffs** [rust-lang/cargo#1548]
```
~$ cargo --version
cargo 0.2.0 (dac600c 2015-04-22) (built 2015-04-25)
```

Completion fails on OS X Yosemite 10.10.3.  The following error message appears whenever the tab key is tapped: `bash: _init_completion: command not found`

Completion fails regardless of whether the system default bash (GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)) or the latest available from homebrew (GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin14.1.0)) is used, and regardless of whether the homebrew bash-completion or bash-completion2 packages are installed.

I installed the completion by sourcing the `etc/bash_completion.d/cargo` written by `make install`.

**Comment by alexcrichton** [comment]
cc @critiqjo

**Comment by critiqjo** [comment]
`_init_completion` was actually included with bash-completion version 2 from 2011 (see: [tree](http://anonscm.debian.org/cgit/bash-completion/bash-completion.git/log/?h=2.x&ofs=600))
@jeffs did you try sourcing the `bash_completion` file that comes with the package (see: [source](http://anonscm.debian.org/cgit/bash-completion/bash-completion.git/tree/bash_completion#n669))?
If that fails too, I will try updating the completion script to not use `_init_completion`...

**Comment by jeffs** [comment]
I was using the default bash_completion installed by homebrew on OS X.  I just tried sourcing the one you linked, and got the following error messages, the same for bash versions 4.3.33 (installed by homebrew) and 3.2.57 (shipped by Apple on OS X 10.10.3 Yosemite).  Thanks for looking into this.

```
~$ . bash_completion
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```

**Comment by critiqjo** [comment]
`declare -A`, used to declare associative arrays, is a bash 4 feature (see [docs](http://tldp.org/LDP/abs/html/bashver4.html))...
I have never used Mac. When you install bash 4 using homebrew, is the old version replaced? Or is it a side-by-side install? Also, see [this issue](https://github.com/kislyuk/argcomplete/issues/64), and please tell me how it goes.

**Comment by jeffs** [comment]
Side by side.  I'll dig into this when I can, and report back to you.

**Comment by shepmaster** [comment]
> is a bash 4 feature

Does that indicate that bash 4 is a prerequisite to having completion for cargo?

**Comment by critiqjo** [comment]
Unfortunately, yes... It's easy to have an alternative to associative arrays, but the more problematic thing is the way bash3 handles long-opts with `=` at the end, I think... I will issue a pull request which works in bash 3 but does *not* handle options like `--url=` nicely...

**Comment by jeffs** [comment]
No-go on OS X.  The file is sourced without error; but Tab produces the following error:

```bash
_get_comp_words_by_ref: command not found
```

The error is identical for Bash 3.2.57 (default) and 4.3.33 (homebrew).
