### ISSUE TITLE
Allow `cargo new .` to create a cargo package in the current folder

### ISSUE THREAD

**Issue by kballard** [rust-lang/cargo#1549]
Cargo should support `cargo new .` to create a cargo package in the current folder, using the existing name of the folder. It should probably abort if any files/folders it wants to create already exists, but otherwise it should just work. It should also default to `--vcs none` in this case.

**Comment by steveklabnik** [comment]
dup of https://github.com/rust-lang/cargo/issues/21

**Comment by steveklabnik** [comment]
@anonymoustafa yes, at the time that this issue was filed, `cargo init` did not exist.
