### ISSUE TITLE
'Expect argument for flag' shows Debug instead of Display output

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/cargo#1553]
Example:
```
$ cargo build --features
Expected argument for flag 'Long("features")' but reached end of arguments.

Usage:
    cargo build [options]
```

I suspect this is a case of using `{:?}` instead of `{}` in the error message.

**Comment by alexcrichton** [comment]
I believe that this will be fixed in the [next docopt upgrade](https://github.com/rust-lang/cargo/pull/1551) which is [currently blocked](https://github.com/rust-lang/rust/pull/24873), so I'm going to close this as it should be fixed regardless soon!
