### ISSUE TITLE
Spurious rebuilds

### ISSUE THREAD

**Issue by gkoz** [rust-lang/cargo#1567]
I'm encountering non-deterministic spurious rebuilds of already built dependencies when building this crate: https://github.com/rust-gnome/examples
The fingerprint traces: [clean build](https://gist.github.com/gkoz/eef4e7f39a6d05f4292d/raw/21275aa0f816bfa74eb15f7e95949b77227c1088/clean.txt), a [rebuild a minute later](https://gist.github.com/gkoz/eef4e7f39a6d05f4292d/raw/8f599ad73c21307c3b908de317e22b8a652a5143/rebuild.txt) that should've been a noop.
Contrary to what I said on the IRC, the behaviour doesn't require any path overrides, this was a vanilla checkout.

**Comment by gkoz** [comment]
@larsbergstrom might've been having the same issue with servo.

**Comment by alexcrichton** [comment]
It looks like that project has a ton of C dependencies (that I can't seem to figure out how to install), so could you elaborate a little more on how you generated the clean build and how you generated the rebuild?

**Comment by gkoz** [comment]
Oh, sorry about the dependencies :( They're covered here: https://github.com/rust-gnome/gtk/blob/master/README.md (in a nutshell just install `glib-dev` and `gtk3-dev` and also `XQuarz` if on OSX).
The first log is from `cargo build` after doing `cargo clean` so it had to build everything. The second log is from doing `cargo build` again when it shouldn't have built anything at all.

**Comment by alexcrichton** [comment]
Awesome, thanks for the pointer to the README @gkoz! I have reproduce and found the bug now, should have a fix soon!
