### ISSUE TITLE
Add dependency of examples towards features

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#1570]
Cargo should allow writing:

``` toml
[package]
# ...

[features]
a = []

[example]
src = "examples/example-that-uses-a.rs"
features = ["a"]
```

`example-that-uses-a` would only be compiled if you call `cargo test --features "a"`.
More formally, examples should have the possibiliy to declare a list of features that must be enabled for this example to be compiled.

The motivation is to avoid having to write [ugly code like this one](https://github.com/tomaka/glium/blob/master/examples/image.rs#L4-L22).
Newcomers often copy-paste a library's examples to get started, and don't necessarly understand what the `#![cfg(feature)]` thing is and that they shouldn't copy it.

**Comment by tsurai** [comment]
Considering that this issue is from may I wonder if this has been solved in some other way by now. Because I stumbled into a similar problem recently and would like to try to implement this feature if it still is desired.

**Comment by alexcrichton** [comment]
@tsurai nah unfortunately this hasn't been implemented just yet, but feel free to jump on it!

**Comment by tsurai** [comment]
@alexcrichton I've written a [simple implementation](https://github.com/tsurai/cargo/commit/38967d96ccf28f011471b973a82acc6b668c7c3a) allowing the user to declare feature dependencies for examples like this:

```toml
[package]
# ...

[features]
a = []
b = []

[examples]
ex_1 = ["a", "b"]
```
``ex_1`` is the name of example and relates to ``examples/ex_1.rs``.

This is my first time working on cargo and I'm not sure if my code is at the right place or has flaws in its logic. It would be very nice if you could look over it and give me some critique. I don't want to open a pull request with code that has errors or a too low quality for cargo.

**Comment by alexcrichton** [comment]
Nice work @tsurai! I know it's probably not easy jumping into Cargo :)

I think though that we may want to instead have a design like:

* A `[[example]]` section is allowed to have a `features` key which indicates what features it depends on
* An example isn't built during `cargo test` unless those features are otherwise activated

That should avoid having an extra manifest key and put the dependency next to the example definition if there is one

**Comment by tsurai** [comment]
Thanks for your guidance @alexcrichton!

I didn't even know that a ``[[example]]`` already exists (doesn't seem to be documented on crates.io?)

Before I'm running off in the wrong direction again...
you want me to add a ``features`` field to the ``TomlExampleTarget`` type? Basically write a new but slightly altered version of ``TomlTarget`` with an additional field to hold the feature dependencies.

The filter logic should not need much changing as it prevents examples from being build if their dependencies are not met.

Is that what you mean?

**Comment by alexcrichton** [comment]
Ah it's [somewhat documented](http://doc.crates.io/manifest.html#configuring-a-target) but not explicitly mentioned. 

I think what you mentioned does align with what I was thinking, but it's starting to feel a little odd to me in terms of making `[[example]]` special over other kinds of targets. It's likely that all targets but `[lib]` want the ability to only be conditionally included if a feature is activated (e.g. binaries, benchmarks, or tests may not otherwise be compiled).

**Comment by tsurai** [comment]
I made another [prototype](https://github.com/tsurai/cargo/commit/013a16a83a98a3e0629fe05c13110d4056ab8e17) that works for all targets but ``[lib]`` as you suggested.
It's just the basic logic without any notifications but is this more like what you want @alexcrichton?

**Comment by alexcrichton** [comment]
Yeah that seems about right to me!

**Comment by rtbo** [comment]
Do you have any news on `example.features`?
Will `cargo test` be the only use case?
Is it possible also to use it to automatically add features for `cargo run --example my_example`

**Comment by alexcrichton** [comment]
@rtbo there's a [PR to implement this](https://github.com/rust-lang/cargo/pull/2056) but it seems to be going stale

**Comment by adamcrume** [comment]
What's the status of this?  It seems to be still unavailable in Rust 1.10.

**Comment by alexcrichton** [comment]
@adamcrume there was a [rebased version](https://github.com/rust-lang/cargo/pull/2325) of the original PR, and it basically just needs a revival at this point I believe with some comments addressed (all on the PR itself)

**Comment by loggerhead** [comment]
Any news?

**Comment by Kixunil** [comment]
I'd appreciate if this was available. I'd also like to add feature-dependent examples directly in doc - is there any way to solve it?

**Comment by alexcrichton** [comment]
AFAIK no news since my [previous comment](https://github.com/rust-lang/cargo/issues/1570#issuecomment-233228932)

**Comment by cyplo** [comment]
It seems that the referenced PRs are closed/merged now, would that mean that this issue is no longer ? thanks !

**Comment by alexcrichton** [comment]
Indeed!

**Comment by Kixunil** [comment]
Is it implemented for examples in doc too? I can't figure out from code...

**Comment by brendanzab** [comment]
Seems it is [the `required-features` field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-required-features-field-optional). Eg.

```toml
[[example]]
name = "stlc"
required-features = ["moniker-derive"]
```
