### ISSUE TITLE
Unhelpful error messages

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#1573]
Cargo outputs too low-level error messages. Currently when running "cargo build --verbose", I get the following error:

`The system cannot find the path specified. (os error 3)`

Neither the missing path, nor information about the current task is displayed, so I have no way of knowing why this is happening. Whenever cargo receives a "Result" from a stdlib operation, it should wrap any errors, adding information about what it was trying to do when the error occurred, instead of just returning them raw.

edit:
Without --verbose the error is even more unhelpful #1516

**Comment by alexcrichton** [comment]
Cargo actually puts in quite a bit of effort to produce good error messages, but there are cases where the error message could certainly be improved! Put another way, we're already doing this all over the place and the infrastructure is all there, so the only action here is to drill down to where this is happening and add a more specific error message.

What were you doing to trigger this error message?

**Comment by Diggsey** [comment]
I eventually tracked down this particular error to a subfolder several levels down which contained a broken symlink.

Related to #1524, cargo shouldn't care about broken symlinks unless they are actually part of the build, and when they are it should give the path of either the symlink or the missing target.

**Comment by alexcrichton** [comment]
Do you have a way that I can reproduce this? I've created some broken symlinks and haven't been able to get this error message to show up.

**Comment by Diggsey** [comment]
I can reproduce it by creating the following folder structure on windows, and running "cargo build":
```
$ ls -lR
.:
total 2
drwxrwx---+ 1 Diggory None   0 May  5 23:46 broken
-rwxrwx---+ 1 Diggory None 130 May  5 23:46 Cargo.toml
-rwxrwx---+ 1 Diggory None  48 Nov  4 17:23 lib.rs
drwxrwx---+ 1 Diggory None   0 May  5 23:46 test

./broken:
total 0

./test:
total 0
lrwxrwxrwx 1 Diggory None 14 May  5 23:46 link -> ../broken/link
```

I'm using cygwin to run the "ls -lR" command, but these are native windows symlinks and the error occurs however I invoke "cargo build".

**Comment by alexcrichton** [comment]
Can you gist an exact set of commands you're running, as well as the version of Cargo that you're using? I'm still unable to reproduce this on Windows.

**Comment by Diggsey** [comment]
Sure:
https://gist.github.com/Diggsey/19276f59c07a26d4f813

I removed lib.rs, since it's not required to reproduce the problem, and was in the wrong place anyway.

**Comment by alexcrichton** [comment]
Can you clarify what version of Cargo you are running? Also can you show me how to create the directory you're working in from scratch?

**Comment by Diggsey** [comment]
$ cargo --version
cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-05-02)

I created the directory from windows explorer in my user folder, saved cargo.toml from the gist, and then ran the commands in a cygwin terminal at that location. Non-cygwin methods of creating the symlinks also work, the only requirement is that they are native windows symlinks (on windows admin privileges are required to create symlinks).

**Comment by carols10cents** [comment]
I've actually [fought this error message before in a different context](http://carol-nichols.com/2011/03/17/the-system-cannot-find-the-path-specified/), and I don't think it's possible for cargo to give a better error message.

Given the lack of activity on this issue, I'm going to close it -- please reopen if this is still a problem!
