### ISSUE TITLE
Allow loading plugins into dependencies

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#1579]
This would essentially just be exposing the functionality of `rustc -Z extra-plugins=...`. The use case I imagine is that programmers can force dependencies to satisfy specific lint requirements (e.g. to outlaw common bad patterns, have stricter requirements around `unsafe` etc.).

See also http://stackoverflow.com/q/30047179/1256624

**Comment by llogiq** [comment]
I haven't read enough of the cargo source, but I gather it would be most useful to add a config parameter to profiles, e.g.

    [profile.dev]
    extra-plugins=clippy, tenacious

    [profile.test]
    extra-plugins=clippy, tenacious

**Comment by alexcrichton** [comment]
Cargo is currently very specifically avoiding all `-Z` flags, so we wouldn't want to just pass that through, and I'd also be a little worried about modifying how dependencies' code is being compiled, but in theory I can see where this may be useful.

**Comment by llogiq** [comment]
It's not only theoretically useful – I very practically want to a) lint my code on test and b) test my lints on other code. And I'd prefer to use a cargo option instead of putting `#![plugin(clippy)]` in front of every file.

**Comment by Manishearth** [comment]
I really think that the toplevel package and/or .cargo config should be able to provide any and all flags to rustc

**Comment by llogiq** [comment]
Exactly my sentiment. I'm also fine with restricting the extra flags to the top-level package.

**Comment by llogiq** [comment]
A somewhat related problem I recently had: If a dependency (such as compiletest.rs) declares `#![deny(deprecate)]` it will make the build fail once a new version arrives that deprecates any of the features it uses. This actually happened to me yesterday.

Note that my [RFC PR](https://github.com/rust-lang/rfcs/pull/1147) would make this a non-problem, but it may still be useful to have a cargo-based workaround in the meantime.

**Comment by Ticki** [comment]
:+1:

**Comment by alexcrichton** [comment]
Cargo currently doesn't reexport any unstable functionality of the compiler (as Cargo doesn't have feature staging like Rust does). For this reason I don't think Cargo will support this until it's either stabilized in the compiler or you can pass arbitrary flags down (which you can do with `cargo rustc` currently). 

As a result this isn't totally actionable today (until upstream support is stabilized), so I'm going to close this.

**Comment by Manishearth** [comment]
You can't. `cargo rustc` passes flags only to the crate being compiled. I don't know any variant which passes flags all the way down to deps.
