### ISSUE TITLE
Difference between Manifest format and implementation: [lib] section name key required

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/cargo#1580]
The manifest format (http://doc.crates.io/manifest.html#configuring-a-target) says

```
All values listed are the defaults for that option unless otherwise specified.
```
and
```toml
# The name of a target is the name of the library that will be generated. This
# is defaulted to the name of the package or project.
name = "foo"
```
---
From this I assumed that the name field is optional. But when leaving it out like this:
```
[lib]
plugin = "true"
```
I get an error from cargo
```
Executing: cargo  test
failed to parse manifest at `Cargo.toml`

Caused by:
  expected a value of type `string` for the key `lib.name`
```

**Comment by Dineshs91** [comment]
Where would the fix be, in toml-rs or in cargo itself ?

I think its in toml-rs decoder.

**Comment by alexcrichton** [comment]
The change would be to [make this line](https://github.com/rust-lang/cargo/blob/d406d25797c04f91aeea49846a584e48bd06c6d9/src/cargo/util/toml.rs#L618) have an `Option<String>` instead of `String`, but still requiring a name for non-lib targets.

**Comment by Dineshs91** [comment]
@alexcrichton Thanks for pointing me out in the right direction.

I have a question though. The cargo [doc](http://doc.crates.io/manifest.html#configuring-a-target) says that, name is optional for  [[bin]], [lib], [[bench]], and [[test]]. Is that true or am i missing something.

Please correct me if i am wrong.

**Comment by alexcrichton** [comment]
For `[lib]` it's 100% ok to omit as there's only one, so if you leave off the name we know which one you're referring to. For the others if you leave off `name` I believe that `path` at least needs to be specified (in which case `name` will be inferred), but there needs to be something to identify which binary/bench/test the section applies to.
