### ISSUE TITLE
either a [lib] or [[bin]] should be present -- error should suggest src/main.rs too

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/cargo#1583]
```bash
$ ls src
foo.rs
$ cargo build
failed to parse manifest at `/home/wilfred/projects/example/Cargo.toml`

Caused by:
  either a [lib] or [[bin]] section must be present
$ mv src/foo.rs src/main.rs
$ cargo build
```

The Cargo error could be clearer here I think. I was working through [Hello, Cargo](https://doc.rust-lang.org/book/hello-cargo.html) and misnamed my main.rs. The error does not suggest I could supply a `src/main.rs` (or a `src/lib.rs`), instead it says my `Cargo.toml` is wrong.

**Comment by alexcrichton** [comment]
Closing as a dupe of #1379, but thanks for the report!
