### ISSUE TITLE
Cargo version bump

### ISSUE THREAD

**Issue by gentoo90** [rust-lang/cargo#1588]
Please bump the version. `0.2.0` build is failing with latest rust-nightlies for quite some time due to syntax and `libstd` changes. This complicates packaging.

**Comment by alexcrichton** [comment]
Currently Cargo does not build against Rust nightly, it requires a pinned version of Rust (listed in `src/rustversion.txt`) to compile. We do periodically, however, update Cargo to the most recent Rust nightly. Cargo will likely require nightly rust until 1.1 when the necessary `std::fs` features have stabilized.

Out of curiosity though, why does this make packaging easier? Are you trying to connect a built-from-source Cargo to the currently package version of the compiler? Unfortunately that probably just won't happen until the 1.1 release at least.

**Comment by gentoo90** [comment]
OK, pinned version makes sense.
> Are you trying to connect a built-from-source Cargo to the currently package version of the compiler?

To the current rust-nightly package, yes.

Well, anyway
> We do periodically, however, update Cargo to the most recent Rust nightly.

Could you also bump cargo's version on every `rustversion.txt` or `Cargo.lock` update?
If no, how often will new versions be released?

**Comment by alexcrichton** [comment]
> Could you also bump cargo's version on every rustversion.txt or Cargo.lock update? If no, how often will new versions be released?

We don't currently have an explicit policy about the versions for Cargo like we do with the compiler itself, but it's likely that some similar cadence will be followed. I suspect that updating `rustversion.txt` probably isn't itself enough to warrant a version bump, but would it be possible for the packaging story for Cargo to download the snapshot compiler that Cargo requires? Is it a hard requirement that it *must* use the `rust-nightly` package?

**Comment by gentoo90** [comment]
> Is it a hard requirement that it must use the rust-nightly package?
No, just more convenient. We'll use pinned version for now.
