### ISSUE TITLE
New commands for { install, upgrade, uninstall, list } packages directly from crates.io

### ISSUE THREAD

**Issue by icorderi** [rust-lang/cargo#1593]
A `cargo install foobar` is far more convenient and clean than:
```
git clone foobar.git, 
cd foobar
cargo build --release
ln -s target/release/foobar /usr/local/bin/.
```
> modulo error checks...

We will probably need the siblings too, `cargo uninstall foobar`, `cargo upgrade foobar`. 

While we are at it: 
- `cargo view foobar` for checking details on an installed package and, 
- `cargo list` for the list of packages, versions installed
- `cargo upgrade`, latest and greatest for all the installed crates.

`cargo package foobar` would allow one to deploy without _cargo_ on the target (originally posted in #557). 

### Where do we want this?
Do we want this features under `cargo`? or should be start building a `crane` and split compilation related features (`cargo`) from package management and deployment (`crane`).

**Comment by steveklabnik** [comment]
There's already a ticket open for this, and we even had a PR with a basic implementation, though it ended up not landing. So I'm closing as a duplicate.

**Comment by alexcrichton** [comment]
We're specifically tracking the story of `cargo install` and all related features in https://github.com/rust-lang/cargo/issues/37.
