### ISSUE TITLE
Print a clear warning when including untracked files in package

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#1597]
Print a clear warning when including untracked files in package.

Admonition the user to track or ignore these files in git.

See issue #1584.

Cargo should help the author for two reasons:

* If the file is untracked, it might be lost and an important part of a working package is lost
* It might alert the author to junk. It happens easily, perf.data, files you saved to test, logs

If it's about empty directories, tell the crate author to use the standard workaround (.gitignore inside to make it non-empty).

**Comment by bluss** [comment]
Some food for thought, I downloaded all packages from crates.io, and I'm grepping for junk and filing bugs. Mostly the bugs will help everyone because we don't have to download things like 10 MB of perf.data files or a random mp4 file that a developer had lying around.

issues:

- [ ] meh/rust-lzma#1
- [ ] huonw/simple_parallel#6
- [ ] Aatch/ramp#18
- [ ] Geal/nom#67

**Comment by jmesmon** [comment]
This came up on IRC #rust recently.

I'd prefer:
 - exclude untracked files by default
 - require special additions to Cargo.toml for the special cases that need to ship non-tracked files

Because:
 - by the time we get warnings, we're moments away from uploading anyhow
 - including untracked files is probably not widely used

**Comment by rillian** [comment]
See also #2063. I'd prefer cargo not package anything not explicitly traceable from the crate sources and Cargo.toml, but limiting it to VCS-tracked files would definitely help.

**Comment by bluss** [comment]
Issue Geal/nom/issues/117 is another “victim”
