### ISSUE TITLE
The reported crate name from --verbose is not the same as the compiled target

### ISSUE THREAD

**Issue by sondrele** [rust-lang/cargo#1599]
There might be another minor issue with the `-` and `_` in the crate names.
I've included some test output below:
```
$ cargo new --bin foo-bar
$ cd foo-bar/
$ cargo build --verbose
   Compiling foo-bar v0.1.0 (file:///home/sondre/test/foo-bar)
     Running `rustc src/main.rs --crate-name foo_bar --crate-type bin -g --out-dir /home/sondre/test/foo-bar/target/debug --emit=dep-info,link -L dependency=/home/sondre/test/foo-bar/target/debug -L dependency=/home/sondre/test/foo-bar/target/debug/deps`
$ tree
.
├── Cargo.lock
├── Cargo.toml
├── src
│   └── main.rs
└── target
    └── debug
        ├── build
        ├── deps
        ├── examples
        ├── foo-bar
        └── native
```
It can be seen that the command says `--crate-name foo_bar`, but the target gets stored as `foo-bar`. 

If I copy and execute the ``Running`...` `` command, it gets stored as `foo_bar`:
```
$ rustc src/main.rs --crate-name foo_bar --crate-type bin -g --out-dir /home/sondre/test/foo-bar/target/debug --emit=dep-info,link -L dependency=/home/sondre/test/foo-bar/target/debug -L dependency=/home/sondre/test/foo-bar/target/debug/deps
$ tree
.
├── Cargo.lock
├── Cargo.toml
├── src
│   └── main.rs
└── target
    └── debug
        ├── build
        ├── deps
        ├── examples
        ├── foo_bar
        ├── foo-bar
        ├── foo_bar.d
        └── native
```

Maybe this could be part of #1572 ?

**Comment by alexcrichton** [comment]
This is actually because Cargo [renames the crate](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_rustc/mod.rs#L406-L414) after the compile succeeds. Cargo needs to specify a `--crate-name` that does not contain hyphens (the compiler does not allow it), but it wants to also preserve the original target name whenever possible (for ease of use), so I believe this is all working as intended!

**Comment by sondrele** [comment]
I see, it sure seems like works!

We had some issues today concerning this renaming, but I guess that's what
we get for working around cargo!
