### ISSUE TITLE
Building package with a custom target cannot find crate core

### ISSUE THREAD

**Issue by dschatzberg** [rust-lang/cargo#1606]
If I create a cargo package which I build with a custom `target.json`, then I get the error: 

    error: can't find crate for `core`

when I try to use the core crate. This makes sense, rust was not configured for my target, so the core crate it built isn't compatible. But what am I to do here? I modified my project to have a dependency on a crate core which I pointed at a cargo compatible package containing the core library source. This actually works quite well.

The next problem is that a dependency of my package tries to use `extern crate core;` and fails with the same error above. And because this package doesn't list `core` as a dependency, I can't point it at my checkout.

This seems like a problem anyone would hit with a custom `target.json`. What is the recommended solution?

**Comment by alexcrichton** [comment]
To solve this you'll need to compile libcore against your target.json and then arrange for the library to appear in the `-L` path somewhere. You can do this via the `RUST_PATH` environment variable or by perhaps writing your own `rustc` script which adds `-L` and then shells out to the real compiler.

Due to the nature of libcore (no one explicitly depends on it), you won't be able to inject a dependency via Cargo, but instead you'll be required to overwrite how the compiler looks for core in general.

I hope that's at least enough info to get you started! I don't think there's much that's a bug Cargo can deal with here, so I'm going to close this, but feel free to ask any questions about anything that arises!

**Comment by dschatzberg** [comment]
@alexcrichton Thanks for your response. I thought based on your message that RUST_PATH functioned similarly to LD_LIBRARY_PATH, but this doesn't appear to be the case? What does the variable do, I could not find any documentation on it and no responses on IRC. Is there some environment variable that is equivalent to LD_LIBRARY_PATH? Alternatively, how can I get cargo to either pass -L to rustc (for my package and its dependencies), or get it to call my own script instead of rustc.

All the solutions I've found are pretty heavy-handed and aren't just restricted to my package and its dependencies.

**Comment by alexcrichton** [comment]
`RUST_PATH` should perform like `LIBRARY_PATH` to the linker where it's an implicit `-L` flag to the compiler. You currently can't get Cargo to pass `-L` flags to the compiler without overriding the `rustc` executable that it's running, but setting `RUST_PATH=/path/to/libcore/dir` should work out ok.

**Comment by dschatzberg** [comment]
I'm not understanding something:

    $ rustc --version
    rustc 1.1.0-nightly (e5394240a 2015-05-14) (built 2015-05-14)
    $ ls $LIB_CORE_PATH
    libcore.rlib
    $ rustc -L $LIB_CORE_PATH ...
    $ RUST_PATH=$LIB_CORE_PATH rustc ...
    ... error: can't find crate for `core`

Shouldn't those last two lines have the same output?

**Comment by alexcrichton** [comment]
Ah `RUST_PATH` doesn't point at the actual files, but rather at directories, so you may want `RUST_PATH=.`

**Comment by dschatzberg** [comment]
Sorry, I wasn't clear. `$LIB_CORE_PATH` contains `libcore.rlib` in the example above. I am using it just as I would use `LD_LIBRARY_PATH`

**Comment by alexcrichton** [comment]
Oh hm, are you sure that the libcore in that directory is the same architecture as the one being targeted by the compiler? Could you also gist the output of `RUST_LOG=rustc::metadata::loader`?

**Comment by dschatzberg** [comment]
Yes, I built it using the same target spec and as shown in my output above, if I use `rustc -L $LIB_CORE_PATH`, everything works.

Odd, I get no additional output by setting `RUST_LOG=rustc::metadata::loader`. If I remove `--target=mytarget.json` then I get some log output

**Comment by alexcrichton** [comment]
Hm it definitely seems like something fishy might be going on... The `RUST_PATH` feature is untested and quite ancient (and also not used that often), so it may actually be broken now unfortunately. The alternative solution I'd recommend is creating a `rustc` script that adds the `-L` that you need and make sure that shows up first in `PATH` so Cargo will run that instead.

**Comment by dschatzberg** [comment]
Yeah, I ended up creating that exact solution. Thank you very much for your help.
