### ISSUE TITLE
libc not found, why?

### ISSUE THREAD

**Issue by samuelyao314** [rust-lang/cargo#1608]
samuel@samhost:~/myrust/guessing_game$ cargo build --verbose
 Downloading libc v0.1.7
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.7` from https://crates.io/api/v1/crates/libc/0.1.7/download

Caused by:
  Failure when receiving data from the peer

samuel@samhost:~/myrust/guessing_game$ cat Cargo.toml 
[package]
name = "guessing_game"
version = "0.1.0"
authors = ["samuel"]

[dependencies]
rand="0.3.8"

I tried to run program 'guessing_game' in the Rust Book

**Comment by steveklabnik** [comment]
Does it still happen over time? This could be any sort of network error.

**Comment by steveklabnik** [comment]
also, cargo build --verbose will show more detail

**Comment by alexcrichton** [comment]
Yeah it looks like this was just an intermittent issue, so closing, but if it persists feel free to reopen!
