### ISSUE TITLE
clarify how the cache works

### ISSUE THREAD

**Issue by vks** [rust-lang/cargo#1609]
How is cargo's cache being cleaned? I couldn't find the answer in the documentation. This is important to know when developing offline.

**Comment by alexcrichton** [comment]
When you say Cargo's cache, do you mean `target/$build` or `~/.cargo/*`? Cargo currently performs no cleaning of either at any time unless you execute `cargo clean` at which point the `target` folder is blown away.

**Comment by vks** [comment]
I meant the cache for the downloaded sources, which I believe is inside
`~/.cargo`. I wanted to build my local project offline, and it tried to
download dependencies it downloaded before. If understand correctly, cargo
does never delete those cached sources? Maybe a rust update caused it then?

**Comment by alexcrichton** [comment]
Yes once a crate is downloaded it is never removed by Cargo explicitly. Are you sure the versions didn't change inbetween or perhaps `CARGO_HOME` came into play?

**Comment by vks** [comment]
Versions don't change unless you run `cargo update` or change the version
in `Cargo.toml`, right? How would `CARGO_HOME` come into play?

Anyway, I think it would be helpful to mention in the documentation that
the cache does not get cleaned ever. This is helpful information if you
want to develop offline.

**Comment by alexcrichton** [comment]
Yeah once a `Cargo.lock` is created the only way to modify it is through `cargo update` or editing `Cargo.toml`. Altering `CARGO_HOME` changes the location of the cache so it'd have to re-download if the location changed.

I definitely agree the docs could be more explicit in this regard :)
