### ISSUE TITLE
Cargo build fails due to locked index

### ISSUE THREAD

**Issue by andrey-gvrd** [rust-lang/cargo#1610]
I can't build anything with cargo on cygwin when there are dependencies present. This is what happens:

    [dependencies]
    time = "0.1.12"

    $ cargo build --verbose
	    Updating registry `https://github.com/rust-lang/crates.io-index`
	Unable to update registry https://github.com/rust-lang/crates.io-index

	Caused by:
	  [10] The index is locked. This might be due to a concurrent or crashed process

	$ rustc --version
	rustc 1.1.0-nightly (7bd71637c 2015-05-06) (built 2015-05-06)

**Comment by alexcrichton** [comment]
Interesting! Did cargo recently get killed when the registry update was in progress perhaps? You can probably solve this by removing `~/.cargo/registry/index/*/.git/index.lock`.

**Comment by andrey-gvrd** [comment]
Yep! Removing index.lock solved the problem, thanks.

**Comment by theronic** [comment]
This happens for me when you fetched some packages as root, then later tried to build as non-root.

You can verify this by running `ls -la rm /Users/petrus/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/FETCH_HEAD` and looking at owner of the FETCH_HEAD file.

Solved by deleting FETCH_HEAD and rebuilding.
