### ISSUE TITLE
dylib outputs required for TARGET when cross-compiling with syntax extension

### ISSUE THREAD

**Issue by mcoffin** [rust-lang/cargo#1612]
When you list a syntax extension as a cargo dependency, even with `plugin = true`, if your chosen target doesn't have dylib outputs available, cargo will complain even if the target being built is a staticlib/executable.

This isn't working as intended, right?

For an example, try compiling the `zinc` (root crate) with `--target=thumbv7m-none-eabi` from mcoffin/zinc@ac834f2debf3df1ef763d10d4b208e160537f687 which depends on the syntax extension crate `ioreg` from the same project. The syntax extension crate is correctly compiled for the host architecture, but cargo gives an error after compilation about dylib outputs not being available for `thumbv7m-none-eabi` (which is correct, but shouldn't matter).

**Comment by alexcrichton** [comment]
Hm it could be that Cargo is mixing up a host/target triple somewhere, could you gist the full error logs of a compile?

**Comment by mcoffin** [comment]
Here's the full log, though spectacularly uninteresting: https://gist.github.com/mcoffin/fdc1358787dea6ca570b

I actually didn't think to check if it actually built the archive until just now (it does). I just saw the error and assumed it didn't. The error is given afterwards for some reason.

**Comment by alexcrichton** [comment]
Hm ok, I think I've found the issue but I'm not quite sure if it'll fix the bug you found, could you try out [this branch of cargo](https://github.com/alexcrichton/cargo/tree/fix-kind-after-the-fact) and see if it works for you?

**Comment by posborne** [comment]
Hi @alexcrichton, I have been working on zinc as well and tried your branch and it does appear to fix the issue that @mcoffin reported.

**Comment by mcoffin** [comment]
@alexcrichton @posborne Works for me as well.

**Comment by alexcrichton** [comment]
Excellent, thanks for testing @posborne and @mcoffin! I've submitted #1617 now
