### ISSUE TITLE
Blacklist some target names for better errors

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#1618]
Right now if a binary is called `build` it will die horribly with a bad error because `target/debug/build` is already a directory that Cargo uses itself. Cargo should give a nicer error in these situations.

Moved over from https://github.com/rust-lang/rust/issues/25518

**Comment by retep998** [comment]
This issue shouldn't affect Windows due to the `.exe` extension, right?

**Comment by alexcrichton** [comment]
It shouldn't, no, but I think it's probably better to have consistent cross-platform behavior. Otherwise this is just one more hazard for developing a project on Windows that won't compile on Unix.

This was fixed by #1682 as well.
