### ISSUE TITLE
Suboptimal "location searched" feedback on "no matching package"

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/cargo#1630]
If I put in a manual path for a dependency, and get something subtly wrong like the name of the package itself, the error report is not as helpful as it could be.

Example:

```
% cargo new spelling
% cargo new my-proj
% cd my-proj/
% cat >> Cargo.toml <<EOF
> [dependencies.zpelling]
> path = "/tmp/demo/spelling"
> EOF
% cargo build
no matching package named `zpelling` found (required by `my-proj`)
location searched: file:///private/tmp/demo/my-proj
version required: *
% 
```

In this case, while it is easy to see that `zpelling` is different from `spelling`, it is worth noting that the path `"/tmp/demo/spelling"` is not being printed anywhere in the error output.

**Comment by carols10cents** [comment]
Triage: the output I get today is:

```
 $ cargo build
error: no matching package named `zpelling` found (required by `my-proj`)
location searched: file:///tmp/demo/spelling
version required: *
```

Since the path `/tmp/demo/spelling` is being printed, this seems fixed and I'm closing.
