### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by mdinger** [rust-lang/cargo#1631]
Compiling of the time crate on a different hard drive causes build failure. This builds fine at `~/folder`:
```cmd
timeit$ cargo build --verbose
       Fresh libc v0.1.8
   Compiling time v0.1.25
     Running `/path/to/timeit/target/debug/build/time-e758cbe877e9589d/build-script-build`
       Fresh gcc v0.3.5
failed to run custom build command for `time v0.1.25`
Could not execute process `/path/to/timeit/target/debug/build/time-e758cbe877e9589d/build-script-build` (never executed)

Caused by:
  Permission denied (os error 13)
```

I'm not sure why it should fail though. Seems like a cargo issue.

**Comment by alexcrichton** [comment]
Hm, when you say "a different hard drive", could you clarify what that means? It looks like Cargo didn't attempt to recompile the build script, so is it possible that the build script was made not executable between runs?

**Comment by mdinger** [comment]
I guess I have a single hard drive partitioned so linux can access the ext4 part and an alternate partition which is formatted ntfs so windows can access it when I'm in Windows. Oh, I think I see the problem. I'm trying `chmod +x` manually on the file but it's not working and I'm not sure why. It seems like that could be why it failed for cargo too.

**Comment by mdinger** [comment]
I don't think this is a cargo issue anymore. Apparently NTFS doesn't support file permissions on a file by file basis. Only on a filesystem basis. Meaning, I have to remount the partition with [higher permissions](http://askubuntu.com/questions/11840/how-do-i-use-chmod-on-an-ntfs-or-fat32-partition/11843#11843) or this will never work.
