### ISSUE TITLE
Strings are not escaped in Cargo.toml created by "cargo new"

### ISSUE THREAD

**Issue by Demurgos** [rust-lang/cargo#1635]
Hi,  
I'm discovering Rust, so I created a new project with the following command:

    cargo new hello_world --bin

The created directory included a pre-configured `Cargo.toml` file with the project name, version & author field. The author field was retrieved from my git global config so I got the following Cargo.toml:

    [package]
    name = "hello_world"
    version = "0.1.0"
    authors = ["Charles "Demurgos" Samborski <demurgos@demurgos.net>"]

**And here is a problem: my git name includes also my quoted pseudo, but the string is added as-is without being escaped causing `cargo run` to break (parse error).**

I quickly escaped the inner quotes, but I post it here to help you improve the overall experience.
Regards

    I installed Rust with the latest Windows x64 installer.
    Platform: Windows 8.1 x64
    cargo --version
    cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)
    rustc --version
    rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

**Comment by kstep** [comment]
I believe this is a bug in [toml-rs](https://github.com/alexcrichton/toml-rs).

**Comment by FlashYoshi** [comment]
Triage: as this has been fixed in commit 9a35735 I suppose this can be closed now?

**Comment by alexcrichton** [comment]
Indeed, thanks!
