### ISSUE TITLE
Wishlist: Cargo should compile with 1.0 stable (not nightly)

### ISSUE THREAD

**Issue by anguslees** [rust-lang/cargo#1638]
(Afaics there isn't already a bug open for this?)

At the moment, I think it fails while building the tar-rs dependency - due to the mode_t change in libc.
Unclear exactly whose responsibility it is to address that, but it would be a good exercise for cargo's pinning features to find a snapshot of dependencies that build against rustc stable, even while rustc nightly marches ahead.

**Comment by lucab** [comment]
I think this has been reported several times (eg. #1223 and #1588), and closed all the time.

@alexcrichton's initial answer to me was "it is intended that Cargo builds with entirely stable code at the 1.0 release of Rust", then updated to "probably just won't happen until the 1.1 release at least."

It may be worth keeping a bug open to track progress on this, as this is effectively a blocker for most of downstream distributions.

**Comment by alexcrichton** [comment]
Cargo is now slated to build with 1.1 stable, so I'm going to close this.
