### ISSUE TITLE
Wildcard dependencies

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/cargo#1644]
We have a lot of target-specific dependencies. With these, we often need to specify the same thing over and over with two parts of the triple constant. i.e., https://github.com/larsbergstrom/rust-layers/commit/327bbe38aa1825adf0b1292d7718645ad36a3f38

It would be great to have wildcards or something similar to reduce the number of rules you have to write.

**Comment by alexcrichton** [comment]
Closing as a dupe of https://github.com/rust-lang/cargo/issues/1007 as it's likely the route we'd take to start out with. I'll add this as an alternative to that though!
