### ISSUE TITLE
CFG_LOCALSTATEDIR and CFG_SYSCONFDIR do not take --prefix into account at ./configure time

### ISSUE THREAD

**Issue by flavius** [rust-lang/cargo#1647]
The two variables do not take the prefix into account, violating a good old autoconf unwritten rule.

**Comment by alexcrichton** [comment]
Can you elaborate a little more on this? I'm not quite sure what these variables are :(

**Comment by alexcrichton** [comment]
We don't have either of these variables in our codebase, so I'm going to close this.
