### ISSUE TITLE
Command completion fails in OS X

### ISSUE THREAD

**Issue by pcx** [rust-lang/cargo#1650]
While using Cargo on OS X, command completion fails.

#### How to reproduce?

Enter 'cargo ' in Terminal and press \<tab\>.

#### What is the expected result?

A list of suggestions with sub-commands of Cargo.

#### What is the actual result?

    $ cargo -bash: _init_completion: command not found

#### Other info

    $ cargo version
    cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-29)

    $ brew info bash-completion
    bash-completion: stable 1.3

**Comment by shepmaster** [comment]
See also #1548

**Comment by pcx** [comment]
related to #1598
