### ISSUE TITLE
How do I use cargo like make?

### ISSUE THREAD

**Issue by aseaday** [rust-lang/cargo#1660]
I want to rewrite my kernel via rust.
But I find it lack of a makefile to build it even though I could write it in program with package gcc and ld.

**Comment by alexcrichton** [comment]
Thanks for the report! Currently Cargo is not striving to be a complete build system, however, and for use cases like this the recommended steps are to specify `crate-type = ["staticlib"]` in `Cargo.toml` and then use that library to then call gcc or ld manually to link everything together. This means you'll probably still need a `Makefile` shim, but you can leave most of the heavy lifting to Cargo.
