### ISSUE TITLE
Re-exported features not used for build dependency that's also a runtime dependency

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#1662]
I have a package A that depends on A-sys for both build and runtime. Several of A's features are re-exported to A-sys. When I try to build package A with a feature enabled, A-sys gets built as a build dependency without any features and then the build of A fails because of missing features in A-sys.

Reduced version at https://github.com/jethrogb/cargo-builddepbug

```
$git clone -b build_ok https://github.com/jethrogb/cargo-builddepbug.git
$cd cargo-builddepbug/a
$cargo build --features bar
   Compiling a-sys v0.1.0
   Compiling a v0.1.0
$git checkout build_error
$cargo build --features bar
   Compiling a-sys v0.1.0
   Compiling a v0.1.0
src/lib.rs:9:2: 9:20 error: unresolved name `a_sys::feature_foo`
src/lib.rs:9 	a_sys::feature_foo();
             	^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `a`.
```

Related:
https://travis-ci.org/sfackler/rust-openssl/jobs/64508660
https://github.com/sfackler/rust-openssl/pull/221

**Comment by alexcrichton** [comment]
Huh it looks like this was resolved in the meantime, yay! Closing in that case.

**Comment by jethrogb** [comment]
Add a test?

**Comment by alexcrichton** [comment]
I'd be fine with one, yeah, although I'm also fine with the underlying problem also having a test elsewhere as well (not entirely sure what fixed this in the long run)
