### ISSUE TITLE
Unable to pack Git submodules

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/cargo#1663]
Cargo currently fails to create a package (`cargo package`) if the corresponding repository contains a Git submodule. The error is as follows:

```
   …
failed to prepare local package for uploading

Caused by:
  could not archive source file `my_submodule`

Caused by:
  Is a directory (os error 21)
```

After reverting [this commit][1], the problem disappears.

Regards,
Ivan

[1]: https://github.com/rust-lang/cargo/commit/8fa3aaf697c0d641736b2c68b8fc5aeebe027ec6

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/cargo/pull/1664
