### ISSUE TITLE
Document how to use `env_logger` with Cargo

### ISSUE THREAD

**Issue by nham** [rust-lang/cargo#1666]
Hi, sorry if I missed this somewhere but I wasn't able to find any documentation on how to use `env_logger` with Cargo. I have an executable crate `my_crate`. Using `RUST_LOG=debug cargo run` spits out a bunch of stuff I don't want to see. I found a comment [here](https://github.com/rust-lang/cargo/issues/818#issuecomment-71667895) which seemed to suggest that using

`RUST_LOG=debug:my_crate cargo run`

would show only the debugs coming from `my_crate`, but it doesn't seem to work.

**Comment by alexcrichton** [comment]
I think this doesn't necessarily belong in the Cargo repo itself as this is an internal implementation detail, but you can find documentation for env_logger here: http://doc.rust-lang.org/log/env_logger/

**Comment by nham** [comment]
Ahh, thanks! I missed that.
