### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by bantl23** [rust-lang/cargo#1672]
Feature request: Add option for code coverage. This is scripted with the travis-cargo python script, which might be sufficient, but I thought it would be nice to see it part of cargo.

**Comment by alexcrichton** [comment]
Thanks for the report! At this time though this is unfortunately blocked on nice cross-platform support [users.rust-lang.org has a nice tutorial](https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650) on how to get code coverage with `kcov` on Linux, but this strategy unfortunately doesn't work on OSX and Windows (requirements for a subcommand of Cargo).

We generally don't leave open long-term feature requests like this in the rust-lang/cargo repo, but if you're interested you can open an issue in rust-lang/rust for perhaps a Rust-specific code coverage tool which is guaranteed to work on all platforms!
