### ISSUE TITLE
Automated tests don’t cover Python 3

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/cargo#1676]
#1674 broke snapshot downloading on machines where Python 3 provides `python`, but this was not caught by the integration bots.

**Comment by alexcrichton** [comment]
It'd be great to cover cases like this, but there's no way that we can add a bot for all possible configurations, and this isn't exactly a critical part of the build system so I'm going to close this. We'll certainly always accept packages to work with python 3, however!
