### ISSUE TITLE
Insert package name/version in API docs

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#1681]
Find a way to insert package name/version in generated docs by `cargo doc`.

Currently I use `sed` to add the version of my package to the title of all doc pages. Adding this feature to cargo would spread this convention further, which would be useful, and I wouldn't have to use make & sed to script it :smile:

**Comment by manuel-woelker** [comment]
So what is the best solution for handling this?
 1. Have rustdoc parse the Cargo.toml and extract the version (but should rust know about cargo?)
 2. Have cargo set a parameter when invoking rustdoc to set version (roundabout but somewhat clean)
 3. fixup the html after rustdoc has done its job (no changes to rustdoc, but messy and error-prone)

**Comment by Razican** [comment]
I would say 2 should be the way to go.

**Comment by softprops** [comment]
fwiw worth, [these env vars](https://github.com/rust-lang/cargo/blob/master/src/doc/environment-variables.md#environment-variables-cargo-sets-for-crates) should be available to any cargo triggered process, included `CARGO_PKG_NAME`, `CARGO_PKG_VERSION`. I've often found them to be vary useful for generating automated cli output for versions and user agent strings for http clients. They may also be helpful here.

**Comment by bluss** [comment]
Those that still don't use docs.rs like https://docs.serde.rs/serde/ or other big projects -- I would still like to see the crate version right in their API doc, so if rustdoc or cargo makes this easy to do, we could see it more even in the projects that host their own docs.

**Comment by aleksator** [comment]
I've noticed that there is already an unstable option in `rustdoc` to include crate version, added in [this PR](https://github.com/rust-lang/rust/pull/44989), with the systax being
`rustdoc src/main.rs -Z unstable-options --crate-version 0.0.1`
 
[I added a corresponding unstable option to cargo](https://github.com/rust-lang/cargo/pull/7903).

Thanks @ehuss for providing some guidance over Discord's \#cargo channel.

This is my first issue in cargo project, so feedback would be very appreciated!
