### ISSUE TITLE
Pathed custom target files break TOML table syntax

### ISSUE THREAD

**Issue by jdub** [rust-lang/cargo#1683]
I have yet to work out a way to engage Cargo settings based on a custom target when the target file includes a path delimiter… which pretty much limits you to putting target files in the crate root… which may be perceived as messy. :smile: 

For example, in a `.cargo/config` you might try:

```
[target.i686-unknown-linux-gnu]
linker = "util/linker.sh"
```
:white_check_mark: Works! (normal behaviour: linker parameter appears, but that's not a custom target)

```
[target.i686-unknown-linux-gnu.json]
linker = "util/linker.sh"
```
:white_check_mark: Works! (linker parameter appears as expected, custom target behaviour appears to be engaged)

```
[target.targets/i686-unknown-linux-gnu.json]
linker = "util/linker.sh"
```
:no_entry_sign: FAILS. (toml parse error)

```
[target.targets\/i686-unknown-linux-gnu.json]
linker = "util/linker.sh"
```
:no_entry_sign: FAILS. (attempted backslash escape, toml parse error)

**Comment by alexcrichton** [comment]
Ah TOML actually [has syntax for this](https://github.com/toml-lang/toml#table) via:

```toml
[target."targets/i686-unknown-linux-gnu".json]
linker = "util/linker.sh"
```

And that should do the trick!

**Comment by jdub** [comment]
… gah, I did give quoting a go, but had always quoted the .json too, which didn't work. Argh! Thanks. :clap:
