### ISSUE TITLE
Target-specific dependencies with path settings

### ISSUE THREAD

**Issue by jdub** [rust-lang/cargo#1684]
I have a circumstance in which I'd like to depend on different sub-crates for particular build targets. (For now, I've left them as modules, optionally using them with `#[cfg(target_arch)]` + `#[path="…"]`.)

After reading the documentation, I tried cargo-culting (sorry-not-sorry) the following:

```
[dependencies.other]
path = "other"

[target.i686-unknown-linux-gnu.dependencies]
rlibc = "0.*"

[target.i686-unknown-linux-gnu.dependencies.pants]
path = "i686/pants"

[target.x86_64-unknown-linux-gnu.dependencies.pants]
path = "x86_64/pants"
```

The first two stanzas work, as expected. Unfortunately, the others don't -- the crate can't be found.

This isn't crucial, because the module approach works, but I thought I would point it out just in case you regarded it as an odd inconsistency. :smile:

**Comment by alexcrichton** [comment]
Hm, do you seen an error message with this? I would expect this to work

**Comment by jdub** [comment]
Here's the stanza in my `Cargo.toml` (which you'll recognise from #1683):

```
[target."arch/x86/i686-unknown-linux-gnu".json.dependencies.arch]
path = "arch/x86"
```

And here's the `cargo rustc` output. No `--extern` for arch, and it wasn't built prior.

```
   Compiling derp v0.0.0 (file:///home/jdub/src/derp/pants)
     Running `rustc src/lib.rs --crate-name derp --crate-type staticlib -g -C soft-float -C lto -C opt-level=1 --out-dir /home/jdub/src/derp/pants/target/i686-unknown-linux-gnu/debug --emit=dep-info,link --target arch/x86/i686-unknown-linux-gnu.json -C linker=util/linker.sh -L dependency=/home/jdub/src/derp/pants/target/i686-unknown-linux-gnu/debug -L dependency=/home/jdub/src/derp/pants/target/i686-unknown-linux-gnu/debug/deps --extern alloc=/home/jdub/src/derp/pants/target/i686-unknown-linux-gnu/debug/deps/liballoc-bc5d311d3f3ea5c0.rlib --extern collections=/home/jdub/src/derp/pants/target/i686-unknown-linux-gnu/debug/deps/libcollections-65119d886a5f770c.rlib --extern core=/home/jdub/src/derp/pants/target/i686-unknown-linux-gnu/debug/deps/libcore-b5608082921fd6e0.rlib`
src/lib.rs:34:1: 34:19 error: can't find crate for `arch`
src/lib.rs:34 extern crate arch;
              ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `derp`.
```

Works fine with:

```
[dependencies.arch]
path = "arch/x86"
```

**Comment by alexcrichton** [comment]
What you've specified is actually a separate key altogether:

```toml
# This is a key for ["target", "arch/x86/i686-unknown-linux-gnu", "json", "dependencies", "arch"]
[target."arch/x86/i686-unknown-linux-gnu".json.dependencies.arch]
```

If you put the `.json` into the quotes I think it should work?

**Comment by jdub** [comment]
Indeed it does! :tada: Though, that's unexpected given the answer to #1683, for which including `.json` in the quotes does not work.

Thanks for being so helpful with these not-bugs-just-support questions. Would you appreciate some clarifying patches for the crates.io documentation?

**Comment by alexcrichton** [comment]
We definitely welcome all patches of such kind :)
