### ISSUE TITLE
cargo rustc prepends arguments instead of appending

### ISSUE THREAD

**Issue by Furyhunter** [rust-lang/cargo#1688]
When using the `rustc` command in cargo, the arguments passed to `rustc` are _prepended_ to the arguments that cargo gives to rustc.

This is preventing a specific use-case where I would like to output llvm-ir for a binary package. Even if I run, for example:

    $ cargo build --target my-target.json -- --emit=llvm-ir

it will always append `--emit=dep-info,link`, making the argument ineffective.

**Comment by huonw** [comment]
Hm, I've found `--emit=llvm-ir` works for me: the `.ll` will be found next to the binary. 

BTW, your example uses `build` instead of `rustc`; typo?

**Comment by Furyhunter** [comment]
Yes, that is a typo. And what you've said is correct: the `.ll` output does show up next to the binary. It's not immediately obvious though since the `link` step fails and thus the whole build is considered to have failed.
