### ISSUE TITLE
SSL connect Error on Windows

### ISSUE THREAD

**Issue by zerterone** [rust-lang/cargo#1689]
Hi all,
i'm experiencing this error on windows 7 64bits with
Cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)
from Rust 1.0.0
lauching a *cargo build --verbose*
this is what i get :
```sh
 Downloading libc v0.1.8
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.8` from https://crates.io/api/v1/crates/libc/0.1.8/download

Caused by:
  SSL connect error
```
out of curiosity i launched the url **https://crates.io/api/v1/crates/libc/0.1.8/download**  in Google chrome and landed on a page that display **"Oops, that route doesn't exist!"**

I'm currently unable to use Cargo to get dependencies and been experiencieng this problem before stable version 1.0.0
I double checked Windows Firewall and AntiVirus Bitdfender exclusion lists for firewall and cargo is supposed to have no problems accessing the net.
In fact , and i don't know if it's significant, but **cargo update -p log** generates no error so i'm assuming it connects just fine : *"Updating registry `https://github.com/rust-lang/crates.io-index"*

Is this something i i've forgot to check ?
or the url it's trying to use is wrong ? (but if so where does it comes from ?)

Any help very appreciated.

**Comment by alexcrichton** [comment]
Do you perhaps have a proxy locally configured? This could just be a routine and/or sporadic error.

**Comment by zerterone** [comment]
i double checked : no proxy 
Connection is direct IP (through ISP box of course) no NAT
And it happens all the time for me, and as you can see below Cargo behaviour changes upon restart
```sh
\rust\rust-sorts>cargo build --verbose
 Downloading libc v0.1.8
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.8` from https://crates.io/api/v1/crates/libc/0.1.8/download

Caused by:
  SSL connect error

\rust\rust-sorts>cargo build --verbose
 Downloading rand v0.3.8
Unable to get packages from source

Caused by:
  Failed to download package `rand v0.3.8` from https://crates.io/api/v1/crates/rand/0.3.8/download

Caused by:
  SSL connect error

\rust\rust-sorts>cargo build --verbose
 Downloading libc v0.1.8
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.8` from https://crates.io/api/v1/crates/libc/0.1.8/download

Caused by:
  SSL connect error

\rust\rust-sorts>cargo build --verbose
 Downloading log v0.3.1
Unable to get packages from source

Caused by:
  Failed to download package `log v0.3.1` from https://crates.io/api/v1/crates/log/0.3.1/download

Caused by:
  SSL connect error

\rust\rust-sorts>cargo build --verbose
 Downloading libc v0.1.8
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.8` from https://crates.io/api/v1/crates/libc/0.1.8/download

Caused by:
  SSL connect error
```
Disabled entirely the AV
disabled bluetooth and virtualbox adapters
changed DNS to Google ones
still same issue
Do you need any more informations that can help you ?

**Comment by alexcrichton** [comment]
It could be that the SSL certificate isn't being accepted by the HTTP backend, can you use the `curl` command line utility to connect to crates.io?

**Comment by zerterone** [comment]
you were right about certificates :
```sh
\rust\rust-sorts>curl https://crates.io/api/v1/crates/libc/0.1.8/download -v
* Adding handle: conn: 0x5b6360
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x5b6360) send_pipe: 1, recv_pipe: 0
* About to connect() to crates.io port 443 (#0)
*   Trying 50.19.122.121...
* Connected to crates.io (50.19.122.121) port 443 (#0)
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

using the  -k switch for cURL it seems to work :
```sh
\rust\rust-sorts>curl https://crates.io/api/v1/crates/libc/0.1.8/download -vk
* Adding handle: conn: 0x674f40
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x674f40) send_pipe: 1, recv_pipe: 0
* About to connect() to crates.io port 443 (#0)
*   Trying 50.19.122.121...
* Connected to crates.io (50.19.122.121) port 443 (#0)
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES128-SHA
* Server certificate:
*        subject: OU=GT87339749; OU=See www.rapidssl.com/resources/cps (c)14; OU
=Domain Control Validated - RapidSSL(R); CN=crates.io
*        start date: 2014-11-06 11:11:23 GMT
*        expire date: 2015-11-09 14:30:14 GMT
*        issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
*        SSL certificate verify result: unable to get local issuer certificate (
20), continuing anyway.
> GET /api/v1/crates/libc/0.1.8/download HTTP/1.1
> User-Agent: curl/7.33.0
> Host: crates.io
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
* Server nginx is not blacklisted
< Server: nginx
< Date: Tue, 09 Jun 2015 05:19:25 GMT
< Transfer-Encoding: chunked
< Set-Cookie: cargo_session=--3c156d7a3629aa08a1a0d538832f99ea30835cc8; HttpOnly
; Secure; Path=/
< Location: https://crates-io.s3-us-west-1.amazonaws.com/crates/libc/libc-0.1.8.
crate
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 vegur
<
* Connection #0 to host crates.io left intact
```
however i went and downloaded certificates from mozilla as indicated from **http://superuser.com/questions/442793/why-cant-curl-properly-verify-a-certificate-on-windows** and it works *without* the -k switch

```sh
\rust\rust-sorts>curl https://crates.io/api/v1/crates/libc/0.1.8/download -v
* Adding handle: conn: 0x1cb6350
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x1cb6350) send_pipe: 1, recv_pipe: 0
* About to connect() to crates.io port 443 (#0)
*   Trying 50.19.122.121...
* Connected to crates.io (50.19.122.121) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Rust\bin\curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES128-SHA
* Server certificate:
*        subject: OU=GT87339749; OU=See www.rapidssl.com/resources/cps (c)14; OU
=Domain Control Validated - RapidSSL(R); CN=crates.io
*        start date: 2014-11-06 11:11:23 GMT
*        expire date: 2015-11-09 14:30:14 GMT
*        subjectAltName: crates.io matched
*        issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
*        SSL certificate verify ok.
> GET /api/v1/crates/libc/0.1.8/download HTTP/1.1
> User-Agent: curl/7.33.0
> Host: crates.io
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
* Server nginx is not blacklisted
< Server: nginx
< Date: Tue, 09 Jun 2015 05:26:50 GMT
< Transfer-Encoding: chunked
< Set-Cookie: cargo_session=--3c156d7a3629aa08a1a0d538832f99ea30835cc8; HttpOnly
; Secure; Path=/
< Location: https://crates-io.s3-us-west-1.amazonaws.com/crates/libc/libc-0.1.8.
crate
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 vegur
<
* Connection #0 to host crates.io left intact
```

at least for cURL :(
```sh
\rust\rust-sorts>cargo build --verbose
 Downloading libc v0.1.8
Unable to get packages from source

Caused by:
  Failed to download package `libc v0.1.8` from https://crates.io/api/v1/crates/libc/0.1.8/download

Caused by:
  SSL connect error
```

so i'm guessing that something is not well set up regarding SSL certificates on Cargo side or on Windows side ?

**Comment by alexcrichton** [comment]
Cargo may actually be using a slightly different SSL implementation than the `curl` command line executable I suppose, but this definitely sounds like fishy certificate business. On Windows Cargo uses [curl-rust](https://github.com/carllerche/curl-rust/blob/ad80df68d74d642f8a2360d916415bb8c233e5b6/curl-sys/build.rs#L61-L63) for HTTP downloads which [is configured](https://github.com/carllerche/curl-rust/blob/ad80df68d74d642f8a2360d916415bb8c233e5b6/curl-sys/build.rs#L61-L63) to use WinSSL, so it should just be using whatever the native system has.

I am not personally too familiar with WinSSL, however, or where it's store of certificates may live or how to verify it.

**Comment by alexcrichton** [comment]
According to some [libcurl documentation though](http://curl.haxx.se/docs/sslcerts.html):

> If libcurl was built with Schannel (Microsoft's native TLS engine) or Secure Transport (Apple's native TLS engine) support, then libcurl will still perform peer certificate verification, but instead of using a CA cert bundle, it will use the certificates that are built into the OS. These are the same certificates that appear in the Internet Options control panel (under Windows) or Keychain Access application (under OS X). Any custom security rules for certificates will be honored.

Perhaps there's a missing cert from the internet options?

**Comment by zerterone** [comment]
i added the same cert used before with cURL to Internet Options cert tabs (all of them) with no changes.
Maybe i'm missing something or it needs a reboot...
i will look into this more and come back to you.

**Comment by zerterone** [comment]
reboot and retry : no luck
it may be a cURL issue with WinSSL as pointed by [some bug reports](http://sourceforge.net/p/curl/bugs/1352/)
I guess that (if corrected in last cURL versions) rebuilding Cargo with an updated curl package should do the trick ?

**Comment by alexcrichton** [comment]
@zerterone that linked issue looks like it's related to timeouts? Perhaps another link was intended?

You can try compiling Cargo yourself, yeah, but it'll use itself to build itself so it may be somewhat difficult! You can use [overrides](http://doc.crates.io/build-script.html#overriding-build-scripts) to provide your own custom copy of libcurl if necessary as well.

Unfortunately I don't know of a great way to debug this, but perhaps libcurl has some options that we could expose?

**Comment by zerterone** [comment]
i believe it's related to timeout somehow cause the first try is always longer and then following attempts are almost instantaneous. I may be wrong on that though.
I'm willing to give it a try at building Cargo from scratch, can you give me a brief how-to aside from downloading all packages by myself ?
If i understand this right i need to complie all dep with rustc and then Cargo itself ?

**Comment by alexcrichton** [comment]
Building Cargo should be relatively easy, actually! There are [general instructions](https://github.com/rust-lang/cargo/#compiling-cargo) in the README (although Windows doesn't need `pkg-config`), and that should get you up and running soon!

**Comment by Tekarihoken** [comment]
I have exactly the same problem. However i haven't this problem with nightly version of the 13/04

**Comment by alexcrichton** [comment]
@zerterone it was reported in https://github.com/rust-lang/cargo/issues/976 that the OpenSSL update may have fixed this, could you try again with the most recent nightly?

**Comment by zerterone** [comment]
@alexcrichton : same issue with cargo 0.3.0-nightly (87b5bfd 2015-06-21) (built 2015-06-22)
FYI , i tried under a Kubuntu VM on the same host and got no problems, i believe that confirms that its related with winssl.

**Comment by WonderboyFromMars** [comment]
I have the same problem with rust 1.1.0 and 1.2.0 on Windows 10 (worked on Windows 7 before the update). Any news on this issue?

**Comment by haodaivshen** [comment]
I also have this problem with rust 1.3.0, cargo 0.4.0 on Windows 7.

**Comment by funIntentions** [comment]
I'm also having this problem with rust 1.3.0, cargo 0.4.0 on Windows 10.

**Comment by alexcrichton** [comment]
If you're running into this, what does the environment look like? I'd love to be able to reproduce this myself to help diagnose, but I've personally never seen this issue.

**Comment by funIntentions** [comment]
I'd be happy to provide any information that might help, but I'm really unsure what would be causing the error (i.e what's relevant). I don't believe it's a firewall issue as I only use bit defender and when I disable it, the error persists. I can also connect to crates.io using the curl command line utility just fine.

**Comment by alexcrichton** [comment]
@funIntentions could you describe the environment you're running in? e.g. information like:

* The exact cargo version 
* The exact rustc version
* Are you in MSYS, MinGW, MinGW-w64, etc
* Where'd you install Cargo/Rust from
* Does using the latest nightly of Cargo help?

**Comment by funIntentions** [comment]
I've tried the Nightly, Beta and Stable (1.3.0) release, but I'm getting the same SSL connect error with all of them. The versions I currently have are:
* rustc 1.5.0-nightly (219eca11b 2015-09-27)
* cargo 0.6.0-nightly (c76e9d1 2015-09-26)

I'm using Cygwin and I've always installed the Rust & Cargo releases using the 64bit windows installers from the Rust install page https://www.rust-lang.org/install.html. As I mentioned, I'm running Windows 10.

Thanks! hope that helps.

**Comment by alexcrichton** [comment]
Out of curiosity, does the same error happen in contexts like:

* Outside of the Cygwin environment? E.g. if you just run `cargo build` in `cmd.exe` does it at least download dependencies?
* In a fresh Cygwin environment? Perhaps there's a package that's confusing something about SSL?
* In a different, perhaps MinGW environment?

I tried to reproduce locally in Cygwin and was unable to, unfortunately :(

**Comment by funIntentions** [comment]
Unfortunately the same error occurs whether I run the ``` cargo build ``` command in Cygwin, Command Prompt, or Git Bash which uses MinGW :(

**Comment by alexcrichton** [comment]
OK, good to know! Given that Cargo should be using the WinSSL option of libcurl I suppose that kinda makes sense. Hm, I suppose it *may* have something to do with Windows 10 vs Windows 7 that I'm running locally, but I'd also be surprised if that were the case (and @haodaivshen is also running Windows 7 and ran into this).

It'd be helpful to figure *where* this error is origination from (e.g. which function) but that would involve opening up a debugger and poking around for errors, and I'm not 100% sure how to pinpoint this unfortunately...

**Comment by funIntentions** [comment]
So cargo is no longer giving me the ```ssl connect error```, but I'm really not sure why it started working... I'll outline what I did nonetheless in case it somehow helps someone else.

First I decided to try and compile cargo from source following the [instructions](https://github.com/rust-lang/cargo) on the cargo GitHub page. After running the ```make``` command, this process fails because during the make process the ```cargo build``` command is called and in my case it attempted to download kernel-sys v0.1.4 but was unable to get packages from source.

Once that happened I used wireshark to see how packets were being sent when the ```cargo build``` command was run. It looked like something was blocking my outgoing communication. My computer never responded to the server, which would send a couple hellos and then give up.

After that I tried turning off my bit defender firewall entirely (even though I explicitly have specified a rule that cargo.exe should be allowed any communication it wants), and ran the ```cargo build``` command again. This time it didn't get the ssl connect error and downloaded all the packages just fine. I felt pretty silly and thought it must be bit defender causing the blocked communication. To confirm this, I turned my bit defender firewall back on (without adjusting anything else), predicting that it would now get the ssl connect error again. For some reason it continued to work just fine...

**Comment by alexcrichton** [comment]
Hm, fascinating! This definitely sounds like something we might be able to pattern match on at least in terms of errors to give a nicer error message. I wonder if the firewall just needed to "get restarted" to pick up the changes to allow Cargo to make requests?

For others having similar issues on this thread, could you check to see if there's a firewall in play? If so that sounds like a likely culprit!

**Comment by WonderboyFromMars** [comment]
I have Bit Defender myself (2015 version). Unfortunatly deactivating the firewall didn't help. Windows defender is switched off.
Did you just disable the firewall via the bitdefender control panel?

**Comment by alexcrichton** [comment]
Hm interesting, could you install wireshark to see what network traffic is happening? If Cargo's actually talking to crates.io then the issue may be elsewhere, but if no traffic goes out to crates.io then it may be a firewall issue.

**Comment by WonderboyFromMars** [comment]
I have Bit Defender myself (2015 version). Unfortunatly deactivating the firewall didn't help. Windows defender is switched off.
Did you just disable the firewall via the bitdefender control panel?

**Comment by WonderboyFromMars** [comment]
Cargo is running now just fine and downloading everything it needs! I found the culprit of this. The adapter settings in the BitDefender Firewall were the culprit. Setting the adapter to trusted and stealth mode to remote or off resolved the issue. 
Seems to be a odd combination of Windows 10 and BitDefender 2015.

Interestingly turning off BitDefender Firewall didn't help at all. Only the adapter settings are relevant.

**Comment by funIntentions** [comment]
That's great! I'm still not sure why when I simply switched my firewall on and off (from the dashboard) it started working. The stealth mode is off now, perhaps turning it off and on turns stealth mode off automatically too and that's why... Not around my computer to test that, but I'm glad it's working for you as well now.

haodaivshen is running Windows 7 and experiencing the same issue so perhaps it's just a Bit Defender 2015 thing if they're also running 2015?

**Comment by alexcrichton** [comment]
Thanks for the update @WonderboyFromMars! I wonder if there's some way that Cargo can detect this and provide a nicer error message? That seems like the ideal possible situation at least.

**Comment by RenaudParis** [comment]
Hi,

Got the same error on Windows 7 here. Unluckily, I do not have BitDefender. I tried deactivating Avast + Windows Firewall, but to no avail. Also tried with Git Bash, still no luck.

First I got the "SSL connect error", and then I got "Couldn't connect to server". Maybe it is temporary!

I am using Rust 1.3, it was working fine with Rust 1.1. Cargo is 0.4.0-nightly (553b363 2015-08-03).

If I can help you by testing a few things, please do ask me!

Best regards,

**Comment by RenaudParis** [comment]
As promised I checked again today, and it seems to be back to normal, without any modification of any kind on my end.

Best regards,

**Comment by Tekarihoken** [comment]
I have made an update i have now
-rustc 1.4 installed throw the 64bit windows installer
-cargo 0.5.0-Nightly also installed by the installer
-Windows 10
-Bitdefender 2016

But stoping and restarting the firewall have not solved the problem :(

Regards

**Comment by funIntentions** [comment]
Hey @Tekarihoken, what are your adapter settings like? Even though turning off the Firewall didn't work, setting the adapter to trusted and stealth mode to remote or off resolved the issue for @WonderboyFromMars. Perhaps that will work for you as well? Although It might be different for bitdefender 2016.

**Comment by Tekarihoken** [comment]
I have setted the adapter to stealth mode and it have solved the problem (event if the stealthmode was active).
The next step is to understand why Cargo is blocked when the network is not in this mode beacause the trusted adapter should not be a good option for people connected to public wifi

**Comment by zerterone** [comment]
Cargo from Rust stable 1.4 is finally working for me.
@alexcrichton : i have no clues except a suspicion on Bitdefender which is not fully enabled : waiting for subscription renewal.
Should i close this BR ?

**Comment by alexcrichton** [comment]
Ok, that sounds good to me, we can continue to follow up on other issues in future tickets!

**Comment by ljani** [comment]
I had this problem as well on Windows 10 with `rustc 1.6.0` and `cargo 0.7.0-nightly` . It seems I need to allow `C:\Windows\system32\lsass.exe` through my firewall in addition to `cargo.exe`.

I'm quite sure it's because of the WinSSL.

**Comment by rageix** [comment]
I am also having this issue.  Windows 10, `rustc 1.6.0 (c30b771ad 2016-01-19)`, `cargo 0.7.0-nightly (1af03be 2015-12-08)`.

Here's a curl dump:

```
curl https://crates.io/api/v1/crates/racer/1.2.2/download -v
*   Trying 54.204.5.236...
* Connected to crates.io (54.204.5.236) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\tools\curl-7.47.0-win64-mingw\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: CN=www.crates.io
*        start date: Nov  5 16:52:33 2015 GMT
*        expire date: Nov  7 22:55:23 2016 GMT
*        subjectAltName: crates.io matched
*        issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
*        SSL certificate verify ok.
> GET /api/v1/crates/racer/1.2.2/download HTTP/1.1
> Host: crates.io
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
< Server: nginx
< Date: Wed, 03 Feb 2016 20:16:12 GMT
< Transfer-Encoding: chunked
< Location: https://crates-io.s3-us-west-1.amazonaws.com/crates/racer/racer-1.2.2.crate
< Set-Cookie: cargo_session=--PBVtejYpqgihoNU4gy+Z6jCDXMg=; HttpOnly; Secure; Path=/
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 vegur
<
* Connection #0 to host crates.io left intact
```

Seems weird they couldn't agree on a protocol?  Makes me think your server is possibly misconfigured.

**Comment by alexcrichton** [comment]
@ljani do you know where `lsass.exe` came from in terms of why Cargo was trying to use it? That seems odd...

@rageix that actually looks like `curl` worked where `cargo` didn't (you got a response using curl). Do you have any firewalls or anti-virus-like programs active? Those can often cause unexpected results when dealing with new applications that want to talk to the network.

**Comment by ljani** [comment]
@alexcrichton It's part of Windows. Has been since XP at least.

**Comment by rageix** [comment]
@alexcrichton right curl worked that's why I was so confused.  I did a Wire Shark session too and it seemed to get a response from the server then failed.  It didn't seem to be related to my firewall but I just figured it out and it seems it was.

Like others in this thread I run Bitdefender, but it doesn't seem to be the issue.  After turning off the Bitdefender firewall it still didn't work. I also had to disable the Windows firewall, and then everything finally worked (after days of trying).  

So there seems to possibly be an issue with Windows firewall, because after bringing it back up with no edits to the rules it works just fine.  This is the only program I've ever had to do this with, it's very bizarre.

**Comment by rageix** [comment]
So it seems it's probably just caused by running 2 firewalls Bitdefender and Windows firewall, and Windows firewall shouldn't be running (not sure why it was) if you are running another firewall.

**Comment by alexcrichton** [comment]
@rageix hm, can you reproduce this now any more? Or does it stay "fixed" after firewalls were turned off then back on? I wonder if there's some "thing" somewhere asking for permission and it's being accidentally hidden or something like that? This definitely seems like something we need to fix...

@ljani was Cargo literally executing `lsass.exe`? I'd be surprised if some standard WinSSL things didn't work *because* they tried to execute it...

**Comment by ljani** [comment]
@alexcrichton I can't say for sure as I didn't check it, but as far as I know Cargo didn't directly execute `lsass.exe`. Instead `lsass.exe` is running all the time and some IPC magic is done causing the `lsass.exe` singleton process to trigger. Anyway, I agree that WinSSL is probably the one who triggered it. It failed and WinSSL failed, finally causing Cargo to fail.

Any idea if other apps are utilizing WinSSL as well? I haven't seen any other apps fail because of that.

**Comment by rageix** [comment]
@alexcrichton I can confirm that shutting off the firewall and starting it again seems to fix the issue and still works after restart.  

I tested this on my laptop as well, running Windows 10 and Bitdefender as well.  Windows firewall wasn't running on the laptop, but toggling Bitdefender firewall off, running `cargo install package`, then restarting the firewall now allows cargo to work with firewall up even after restart.  Odd stuff, I didn't make any other modifications to anything.

**Comment by alexcrichton** [comment]
@ljani weird! We only use WinSSL through libcurl, so in theory anything else using libcurl would have the same problems, but maybe we're miscompiling libcurl?

@rageix also weird! A little unfortunate we can't reproduce to dig more into this.

**Comment by alexcrichton** [comment]
Maybe bitdefender is just known to cause problems with SSL? Googling "bitdefender windows blocks ssl" brings up tons of articles about this...

**Comment by mitsukuri** [comment]
Are the any plans to move away from Curl in favor of something that doesn't rely on WinSSL?

**Comment by shihzenq** [comment]
hello, my mac version is 10.13.6。 cargo build error : Caused by:
  [60] Peer certificate cannot be authenticated with given CA certificates (SSL certificate problem: certificate has expired).
  
  I have tried all the above methods, but the error is still reported.
