### ISSUE TITLE
regression: `cargo` no longer passes `-L native=(..)/build/dep-of-dep/out` to `rustc` when cross compiling a binary with `cargo rustc -- (..)`

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#1695]
This broke [std-with-cargo](https://github.com/japaric/std-with-cargo)

The regression appeared somewhere between 06dbe65 (good) and 1777ab7 (bad).

Context: I'm cross compiling the `std` crate using cargo, and I've added a cargo feature `jemalloc_dynamic` to the `std` crate that let's you dynamically link to jemalloc. This feature depends on a feature of the `alloc` crate that has the same name. When the feature is enabled, `cargo` will cross compile a shared library version of `jemalloc` when building the `alloc` crate, and the final binary will be dynamically linked to `jemalloc`.

When cross compiling a binary that depends on `std` (but not on `alloc`) and `jemalloc_dynamic` is enabled, with the "good" cargo revision, this is the last command:

```
$ cargo rustc --target=mips-unknown-linux-gnu --verbose -- -C opt-level=0
(..)
Compiling hello v0.1.0 (file:///home/japaric/tmp/rust/src/hello)
Running `
rustc
src/main.rs
--crate-name hello
--crate-type bin
-g
-C opt-level=0
--out-dir /home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug
--emit=dep-info,link
--target mips-unknown-linux-gnu
-C ar=mips-openwrt-linux-ar
-C linker=mips-openwrt-linux-gcc
-L dependency=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug
-L dependency=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug/deps
--extern std=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug/deps/libstd-3d19f461db50ea76.rlib
-L native=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug/build/alloc-ea35edb81fd92388/out
-L native=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug/build/std-3d19f461db50ea76/out
`
```

But running the same command with the "bad" cargo revision results in a similar command with one less flag:

``` diff
 --extern std=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug/deps/libstd-3d19f461db50ea76.rlib
- -L native=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug/build/alloc-ea35edb81fd92388/out
 -L native=/home/japaric/tmp/rust/src/hello/target/mips-unknown-linux-gnu/debug/build/std-3d19f461db50ea76/out
```

which then errors with:

```
note: (..)/mips-openwrt-linux-uclibc/bin/ld: cannot find -ljemalloc
```

Here's the [full cargo log](https://travis-ci.org/japaric/std-with-cargo/jobs/65940382), if that helps.

The odd thing is that the flag is only missing when using `cargo rustc -- $SOMETHING`, both `cargo rustc --` and `cargo build` work fine with the "bad" cargo revision.

cc @alexcrichton 
cc @kteza1 for now, avoid today's or newer nightlies, or avoid using `cargo rustc -- -C link-args=-s`.

**Comment by alexcrichton** [comment]
I so far haven't been able to reproduce this, but this may be connected to cross compilation. My attempts to cross to a 32-bit arch or android have failed (failures to build jemalloc). Do you know if there's an easy way to get the mips toolchain you're using? (I'm on ubuntu fwiw)

**Comment by japaric** [comment]
> Do you know if there's an easy way to get the mips toolchain you're using? 

Yes, it's in the OpenWRT SDK, here are [the installation steps](https://github.com/japaric/rust-on-openwrt#installing-the-openwrt-sdk). Check that and the next section, you need to export the STAGING_DIR and PATH env variables to make the toolchain work.
