### ISSUE TITLE
Cargo bench should put deliminators on nanosecond numbers

### ISSUE THREAD

**Issue by mdinger** [rust-lang/cargo#1696]
This might be a rust issue but I'm not sure. From [this initial rust experience blog](http://ericsink.com/entries/rust1.html), `cargo bench` should report nanosecond times as `3_000_000` or `3,000,000`, not `3000000`

**Comment by alexcrichton** [comment]
Thanks for the report! This code actually lives in the libtest library of the standard distribution, so could you open this bug up against rust-lang/rust instead of Cargo?

**Comment by mdinger** [comment]
@alexcrichton Done at https://github.com/rust-lang/rust/issues/26109. Thanks for directing.
