### ISSUE TITLE
"cargo test" autocompletion gets an error

### ISSUE THREAD

**Issue by saghmrossi** [rust-lang/cargo#1703]
On zsh, when I type `cargo test ` and then press tab, instead of autocompleting the names of the tests, the error `_test_names:3: bad pattern: ![[` gets printed out. This is actually more annoying than if cargo just didn't attempt to complete my test names at all. Any idea if this is happening because of something on cargo's end rather than zsh?

**Comment by alexcrichton** [comment]
cc @eerden

**Comment by eerden** [comment]
This was a bug in the autocompletion script.

**Comment by saghmrossi** [comment]
Awesome, thanks for getting on that!
