### ISSUE TITLE
docs show example of `version = "*"` w/o explanation

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/cargo#1707]
I was wondering what the precise semantics of using `version = "*"` were, especially what the "gotchas" are for using it.

So I skimmed over the cargo docs at http://doc.crates.io/manifest.html but could not find any discussion of what `version = "*"` even *means*.  The docs do say that:

> Cargo bakes in the concept of [Semantic Versioning](http://semver.org/)

but that link goes to http://semver.org/, which does not include any discussion of something like `"*"`.

I ended up resorting to looking at the cargo source code, which led me to http://doc.rust-lang.org/semver/semver/index.html which has a section labelled "Wildcard requirements" that has the most important piece of information I was looking for (namely, what `"*"` *means*.)

So, two things to fix:
 1. Say what `version = "*"` means
 2. Add some discussion about when it is appropriate to use `version = "*"`, versus when one should put in a specific version label.

**Comment by steveklabnik** [comment]
It means 'any version'.

**Comment by pnkfelix** [comment]
Ah, I now see there is: 

  http://doc.crates.io/crates-io.html

which does describe of the format of the version string.

That page does not ever use the syntax `version = "string"`; it always uses the `dep_name = "version_string"` format.  That might be one reason why I overlooked it, I am not sure.

Anyway, it would probably suffice to just add a link from the `manifiest.html` doc to the `crates-io.html` doc.
