### ISSUE TITLE
shared target dir doesn't prevent all rebuilds

### ISSUE THREAD

**Issue by metajack** [rust-lang/cargo#1718]
In servo master:

`./mach build --dev` followed by `./mach build-cef` rebuilds script when it shouldn't. Previous versions of cargo would only rebuild servo and embedding, but in fixing the link propagation errors this regressed.

**Comment by alexcrichton** [comment]
Could you gist a full log of what's going on? I can't seem to reproduce this.

**Comment by metajack** [comment]
You can see it intermittently on our Servo CI logs:

http://build.servo.org/builders/linux2/builds/2069/steps/compile_1/logs/stdio

**Comment by alexcrichton** [comment]
Ok, I believe we've found the bug, but it's unrelated to the current description, so I'm gonna move this to a more targeted bug: https://github.com/rust-lang/cargo/issues/1729
