### ISSUE TITLE
Inconsistent handling of command-line key/value arguments separated by `=`

### ISSUE THREAD

**Issue by mlalic** [rust-lang/cargo#1720]
Imagine a crate with two optional features, named "first" and "second".

This is how cargo handles different command line arguments:

- `cargo build --features="first"` - compiles the "first" feature, as expected
- `cargo build --features "first"` - compiles the "first" feature, as expected
- `cargo build --features "first second"` - compiles both features, as expected
- `cargo build --features="first second"` - returns *invalid arguments*
- `cargo test --features "first second"` - compiles and correctly runs the tests
- `cargo test --features="first second"` - compiles the source ignoring both features and then passes the `--features="first second"` bit to the executable, which causes it to panic since it's not a recognized option

To summarize, when the value is a space separated (but still quoted) string and the key/value argument is specified as a single command-line argument (where the key and value are separated by a `=`), the build command says that the arguments are invalid, while the test completely fizzles out. When the value is a single string (with no spaces), then both styles work identically.

In my opinion, cargo should properly handle `=` separated option-value arguments, which means that the result should be the same as when the value is a separate command-line argument in all cases.

If, however, this style is not to be supported by cargo, then it should at least always cause the invalid arguments message when used, otherwise it leads to inconsistencies such as the `build` command failing, but `test` working (and failing very unexpectedly), while given the same set of command line arguments.

**Comment by alexcrichton** [comment]
cc @BurntSushi, is this perhaps a bug in docopt?

**Comment by mlalic** [comment]
Even if there is an underlying bug in docopt, it still seems at best strange that `cargo build` and `cargo test` work so differently when given the same args, doesn't it?

**Comment by alexcrichton** [comment]
@mlalic see https://github.com/docopt/docopt.rs/issues/129

**Comment by BurntSushi** [comment]
This was indeed a bug in Docopt, and it should be fixed on crates.io in `0.6.67`. Nice find!

@mlalic The bug explains all of the behavior you observed. The underlying issue was that `--feature="a b"` wasn't detected as a long flag because of the space character. As a result, it was thrown into the catch all `<args> ...` for `cargo test`. The "Invalid arguments" on `cargo build` was because the `cargo build` usage didn't have a `<args> ...`, so Docopt the extra arguments didn't match any usage pattern, and thus, an error was reported.

**Comment by mlalic** [comment]
@BurntSushi Thanks for the quick fix and the extra context there!
