### ISSUE TITLE
Ability to prevent windows console opening with .exe

### ISSUE THREAD

**Issue by trolleyman** [rust-lang/cargo#1721]
Currently when you run an executable generated using Rust a console window opens automatically. This is extremely helpful in debugging situations, however during release scenarios it is best for this to not open as it clutters up the screen.

I can hide the window after launch using external crates (following code), however I would prefer to not include all of these dependencies.

```rust
extern crate winapi;
extern crate user32;
extern crate kernel32;
use std::ptr;
fn hide_console_window() {
  let window = unsafe {kernel32::GetConsoleWindow()};
  // https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548%28v=vs.85%29.aspx
  if window != ptr::null_mut() {unsafe {user32::ShowWindow (window, winapi::SW_HIDE)};}
}
```

Would it be best for the console to diable automatically in `--release` builds, or maybe add a switch to cargo?

**Comment by alexcrichton** [comment]
Thanks for the report! This doesn't quite seem like it's Cargo's responsibility, however, as it's just driving the compiler under the hood. If this is going to be done it'd likely be an option and/or default configuration of the compiler itself, so I'd recommend reporting an issue against rust-lang/rust

**Comment by trolleyman** [comment]
According to [this](http://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window) stackoverflow question, there's a flag in the rustc compiler (-mwindow) that cargo could pass to rustc?

**Comment by alexcrichton** [comment]
Hm that sounds like it should be either a first-class option to the compiler itself or perhaps even passed by default, but it likely shouldn't be dealt with by Cargo itself.
