### ISSUE TITLE
Cargo fails when rustc isn't in default location

### ISSUE THREAD

**Issue by Virtlink** [rust-lang/cargo#1723]
For my project I have a script that setups a Rust installation in a subdirectory so that the user's system doesn't need to be changed, superuser rights are not needed, and the installation doesn't mess with any Rust installation the user already has. So I execute

	curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- \
	--channel=nightly --prefix=/home/mint/rustbin/ \
	--disable-sudo --disable-ldconfig --yes

and Rust installs fine. I can run `rustc`

	cd ~/rustbin/bin
	export LD_LIBRARY_PATH=/home/mint/rustbin/lib
	./rustc --version
	
	rustc 1.2.0-nightly (906ad7246 2015-06-15)
	
but Cargo doesn't work:

	cd ~/rustbin/bin
	export LD_LIBRARY_PATH=/home/mint/rustbin/lib
	./cargo --version
	Could not execute process `rustc -vV` (never executed)

	Caused by:
	  No such file or directory (os error 2)

I believe this is caused by Cargo looking for `rustc` in `/usr/local/bin`, where it's not unless it's installed there.

**Comment by alexcrichton** [comment]
Thanks for the report! Cargo currently does not make any assumptions about where `rustc` is located, however, and requires that it is part of your `PATH` to be able to run. You can override this in nightly verions of Cargo though with the `RUSTC` environment variable or the `build.rustc` configuration key.
