### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by adjkldd** [rust-lang/cargo#1725]
### Environment
install **cargo** in **MSYS2**

### The step caused the error
when I ran the `make` command

### what is the error

> /mingw32/bin/python src/etc/dl-snapshot.py i686-pc-windows-gnu
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

> curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Traceback (most recent call last):
  File "src/etc/dl-snapshot.py", line 96, in <module>
    raise Exception("failed to fetch url")
Exception: failed to fetch url
Makefile:91: recipe for target 'target/snapshot/cargo/bin/cargo.exe' failed
make: *** [target/snapshot/cargo/bin/cargo.exe] Error 1

**Comment by alexcrichton** [comment]
This will be fixed by https://github.com/rust-lang/cargo/pull/1724 as we're switching hosts, I never figured out what the underlying problem was here.

**Comment by Byron** [comment]
While unsure if this is the right place for this, the same error message is visible when running [the smoke tests](https://github.com/rust-lang/cargo/runs/4064166071?check_suite_focus=true#step:19:43), currently.

**Comment by Byron** [comment]
Update: it seems to be a more widespread issue, and anything using curl under the hood has issues understanding an issuer certificate with the latest versions of the respective crates: https://github.com/Byron/gitoxide/runs/4065271932?check_suite_focus=true#step:6:3484 .
