### ISSUE TITLE
Unable to build cargo on freebsd(64) due to libssh2

### ISSUE THREAD

**Issue by posix4e** [rust-lang/cargo#1727]
I'm trying to build a freebsd port of cargo and rust. I was able to get a snapshot installed, but when I run cargo build in the rust directory.

stdout::
   Compiling gcc v0.3.8
   Compiling threadpool v0.1.4
   Compiling libc v0.1.8
   Compiling filetime v0.1.4
   Compiling glob v0.2.10
   Compiling strsim v0.3.0
   Compiling semver v0.1.19
   Compiling bitflags v0.1.1
   Compiling regex-syntax v0.1.2
   Compiling pkg-config v0.3.5
   Compiling term v0.2.9
   Compiling matches v0.1.2
   Compiling rustc-serialize v0.3.15
   Compiling memchr v0.1.3
   Compiling log v0.3.1
   Compiling tar v0.2.14
   Compiling time v0.1.26
   Compiling num_cpus v0.1.0
   Compiling miniz-sys v0.1.5
   Compiling libz-sys v0.1.6
   Compiling libgit2-sys v0.2.17
   Compiling libssh2-sys v0.1.25
   Compiling openssl-sys v0.6.2
   Compiling curl-sys v0.1.24
   Compiling aho-corasick v0.1.3
   Compiling regex v0.1.35
   Compiling flate2 v0.2.7
   Compiling env_logger v0.3.1
Build failed, waiting for other jobs to finish...
stderr:
failed to run custom build command for `libgit2-sys v0.2.17`
Process didn't exit successfully: `/usr/home/posix4e/cargo/target/debug/build/libgit2-sys-aaaf80b7fae7ffe0/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/posix4e/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.2.17/libgit2" "-DBUILD_SHARED_LIBS=OFF" "-DBUILD_CLAR=OFF" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=/usr/home/posix4e/cargo/target/debug/build/libgit2-sys-aaaf80b7fae7ffe0/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64 -fPIC"
-- The C compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28") 
-- Found OpenSSL: /usr/local/lib/libssl.so;/usr/local/lib/libcrypto.so (found version "1.0.2c") 
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser was not found or is too old; using bundled 3rd-party sources.
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.8") 
-- checking for module 'libssh2'
--   package 'libssh2' not found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED - Success
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/home/posix4e/cargo/target/debug/build/libgit2-sys-aaaf80b7fae7ffe0/out/build

--- stderr
thread '<main>' panicked at '
libgit2 failed to find libssh2, and SSH support is required

build script failed, must exit now', /home/posix4e/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.2.17/build.rs:166

I was able to go into  /usr/home/posix4e/cargo/target/debug/build/libgit2-sys-aaaf80b7fae7ffe0/out/build
and it built fine just with a make command. Where is a log that will give me more information?

Although I checked truss and it seems to find  libssh2.so in /usr/local/lib just fine.

**Comment by alexcrichton** [comment]
The libssh2 library actually built successfully here, there's just a check in the git2 build script that libgit2 detected the libssh2 library successfully, but it failed to do so. There's some coercions which are needed to push libgit2 to find libssh2, but some extra shoves may need to be in order.

**Comment by posix4e** [comment]
Is there a log I can look at?

On Wed, Jun 17, 2015, 12:41 Alex Crichton <notifications@github.com> wrote:

> The libssh2 library actually built successfully here, there's just a check
> in the git2 build script that libgit2 detected the libssh2 library
> successfully, but it failed to do so. There's some coercions which are
> needed to push libgit2 to find libssh2, but some extra shoves may need to
> be in order.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/cargo/issues/1727#issuecomment-112924262>.
>
-- 

Sent from my mobile 5045076749
Alex Newman

**Comment by alexcrichton** [comment]
What's printed to stdout is the log of the libgit2 build, and it's got the directories that the cmake build files wound up in.

**Comment by jroesch** [comment]
I ran into this exact same issue on a fresh Linux box today. It built just fine after I installed pkg-config.
