### ISSUE TITLE
nocapture for doc-tests

### ISSUE THREAD

**Issue by diwic** [rust-lang/cargo#1732]
Hi,

For ordinary tests, I can run `cargo test -- --nocapture` and the output will shown on-screen. However, I have doc-tests as well (examples in the documentation), and even though I use `--nocapture` the output of these are not shown.

I'm not sure whether this is a bug in cargo or somewhere else, but at least the behaviour is inconsistent.

**Comment by alexcrichton** [comment]
Are you sure that this doesn't work? I just ran `cargo test -- --nocapture` and saw all the output from the doctests (the compiles). The actual output of the tests themselves isn't printed anywhere, but that's a rustdoc issue, not a Cargo one.

**Comment by diwic** [comment]
> The actual output of the tests themselves isn't printed anywhere

Right, that's what I'm missing.

**Comment by diwic** [comment]
Closing, already filed: https://github.com/rust-lang/rust/issues/26309

**Comment by jsermeno** [comment]
Linking the follow-up pull request since this issue is what comes up in a Google search. Rustdoc fixed the issue in 2021. There was a pull request to fix the issue in Cargo, but the pull request was never resolved: https://github.com/rust-lang/cargo/pull/9705.

**Comment by ArtemIsmagilov** [comment]
I also tried to get output from println. There is no output yet(
No output from println! and eprintln!
`cargo test -- --nocapture`

**Comment by w1th0utnam3** [comment]
@rustbot note blocked-on-rust-98550

@ArtemIsmagilov @jsermeno This seems to be the most recent and still active issue on the topic: https://github.com/rust-lang/rust/issues/98550
