### ISSUE TITLE
`cargo package` doesn't catch errors with invalid keywords

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#1736]
If you create a package with a keyword specified with multiple words, `cargo package` works fine but `cargo publish` errors with:
```
api errors: invalid upload request: ApplicationError("invalid keyword specified: key word")
```

I *think* that `cargo package` should probably try to catch this error.

**Comment by alexcrichton** [comment]
Thanks for the report! There will inevitably be errors that `cargo publish` will report that `cargo package` cannot (e.g. a duplicate package on crates.io), so the charter of `cargo package` isn't so much to *guarantee* that `cargo publish` will succeed so much as just making sure the packing step itself succeeds. As a result I don't believe that this is a bug, so closing.
