### ISSUE TITLE
Unhelpful error messages when parsing of Cargo.toml failed

### ISSUE THREAD

**Issue by vberger** [rust-lang/cargo#1739]
In the updating process of one of my libs, I needed to add these lines in my `Cargo.toml`
```
[dev-dependencies]
wayland-client = { features = ["dlopen"] }
```
But at first, I made a mistake, and forgot the `[ ]` around `"dlopen"`, thus writing
```
[dev-dependencies]
wayland-client = { features = "dlopen" }
```
the error message generated by cargo was
```
expected a value of type `string`, but found a value of type `table` for the key `dev_dependencies`
```
which wasn't really helpful to see my mistake.

Would it be possible to make more precise error messages in cases like this?

**Comment by alexcrichton** [comment]
Wow, that is a pretty bad error message! This originates from the toml crate, but I'd want to take some time to get a minimization before closing in favor of an issue over there.
