### ISSUE TITLE
cargo build says "Build failed, waiting for other jobs to finish..." and then never finishes.

### ISSUE THREAD

**Issue by jakerr** [rust-lang/cargo#174]
When a dependency build fails, cargo can hang at the:
_Build failed, waiting for other jobs to finish..._
message.

Some context:

Cargo version is:
e268c1378677e903313b053cbabf97fad463b113 auto merge of #169 : cburgdorf/cargo/name_clean, r=alexcrichton

I was trying to cargo build:  https://github.com/Coeuvre/rust-2048.git on windows.
I'm not sure if the actual reason for the failure is relevant at all and haven't looked into it (nor do I know how to debug it.) Let me know if you'd like me to dig more.

```
$ cargo build
unused manifest key: package.readme
   Compiling gl v0.0.1 (https://github.com/bjz/gl-rs)
   Compiling piston v0.0.0 (https://github.com/pistondevelopers/piston/)
   Compiling image v0.0.0 (https://github.com/PistonDevelopers/rust-image)
   Compiling sdl2 v0.0.1 (https://github.com/AngryLawyer/rust-sdl2)
   Compiling graphics v0.0.0 (https://github.com/pistondevelopers/rust-graphics)
Build failed, waiting for other jobs to finish...
```

The issue is that it hangs here and never returns. I gave it 30 minutes before I killed the process.

**Comment by rphmeier** [comment]
I've been encountering this issue on every failed build using cargo 0.10 and 0.11 nightlies.

**Comment by alexcrichton** [comment]
@rphmeier interesting! Do you have a reliable reproduction I could try out locally?

**Comment by EwoutH** [comment]
@alexcrichton I still got the same issue on Rust Nightly on rust-av.

- See this PR: https://github.com/rust-av/rust-av/pull/74
- [Full AppVeyor build log](https://ci.appveyor.com/project/EwoutH/rust-av/build/job/p43wn7xiu7n789cy)
- [AppVeyor configuration](https://github.com/rust-av/rust-av/blob/06a58e3f8829badd9e296f27fdd2d32aad07ab17/appveyor.yml)

```
cargo build --release --target=%target%
```
```
error: aborting due to 37 previous errors
Some errors occurred: E0206, E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0206`.
error: Could not compile `winapi`.
warning: build failed, waiting for other jobs to finish...
```

**Comment by EwoutH** [comment]
It eventually exited by itself, just took somewhat longer than expected (6 min).

**Comment by alexcrichton** [comment]
@EwoutH this issue is over 5 years old, I'd recommending opening a new issue as what you're experiencing is probably entirely different than this one.

**Comment by user9825** [comment]
install
sudo apt-get install libssl-dev

**Comment by LucianoRicardo737** [comment]
> install sudo apt-get install libssl-dev

work for me.. Thx

**Comment by ORUNSOLU** [comment]
I am on Ubuntu 22.04.2 LTS, cargo 1.67.1 and I am experiencing this issue. I have RustUp running. I am experiencing this issue. 

warning: build failed, waiting for other jobs to finish...
error: failed to compile `sqlx-cli v0.6.2`, intermediate artifacts can be found at `/tmp/cargo-installC88L8W`

**Comment by prichardsondev** [comment]
RPI 4 - Bookwork Server V12
cargo 1.77.2

cargo install cargo-generate

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.20.0`, intermediate artifacts can be found at `/tmp/cargo-installg2JwCE`.

install sudo apt-get install libssl-dev
cargo install cargo-generate

Solved Problem -ty

**Comment by JianWei777** [comment]
> RPI 4 - Bookworm Server V12 64 bit cargo 1.77.2
> 
> cargo install cargo-generate
> 
> warning: build failed, waiting for other jobs to finish... error: failed to compile `cargo-generate v0.20.0`, intermediate artifacts can be found at `/tmp/cargo-installg2JwCE`.
> 
> sudo apt-get install libssl-dev cargo install cargo-generate
> 
> Solved Problem -ty

it works for me too,thank you

**Comment by JianWei777** [comment]
> RPI 4 - Bookworm Server V12 64 bit cargo 1.77.2
> 
> cargo install cargo-generate
> 
> warning: build failed, waiting for other jobs to finish... error: failed to compile `cargo-generate v0.20.0`, intermediate artifacts can be found at `/tmp/cargo-installg2JwCE`.
> 
> sudo apt-get install libssl-dev cargo install cargo-generate
> 
> Solved Problem -ty

it works for me too,thank you

**Comment by ventiwang** [comment]
Could not find openssl via pkg-config:
  Could not run `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl`
  The pkg-config command could not be found.

  Most likely, you need to install a pkg-config package for your OS.
  Try `apt install pkg-config`, or `yum install pkg-config`,
  or `pkg install pkg-config`, or `apk add pkgconfig` depending on your distribution.

  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.

  If you did not expect this build to link to a pre-installed system library,
  then check documentation of the openssl-sys crate for an option to
  build the library from source, or disable features or dependencies
  that require pkg-config.

  cargo:warning=Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge. If OpenSSL is installed and this crate had trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the compilation process. See stderr section below for further information.

  --- stderr


  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.104


  It looks like you're compiling on Linux and also targeting Linux. Currently this
  requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
  could not be found. If you have OpenSSL installed you can likely fix this by
  installing `pkg-config`.


warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.22.0`, intermediate artifacts can be found at `/tmp/cargo-installi7avY6`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by ventiwang** [comment]
> Could not find openssl via pkg-config: Could not run `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl` The pkg-config command could not be found.
> 
> Most likely, you need to install a pkg-config package for your OS. Try `apt install pkg-config`, or `yum install pkg-config`, or `pkg install pkg-config`, or `apk add pkgconfig` depending on your distribution.
> 
> If you've already installed it, ensure the pkg-config command is one of the directories in the PATH environment variable.
> 
> If you did not expect this build to link to a pre-installed system library, then check documentation of the openssl-sys crate for an option to build the library from source, or disable features or dependencies that require pkg-config.
> 
> cargo:warning=Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge. If OpenSSL is installed and this crate had trouble finding it, you can set the `OPENSSL_DIR` environment variable for the compilation process. See stderr section below for further information.
> 
> --- stderr
> 
> Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge. If OpenSSL is installed and this crate had trouble finding it, you can set the `OPENSSL_DIR` environment variable for the compilation process.
> 
> Make sure you also have the development packages of openssl installed. For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
> 
> If you're in a situation where you think the directory _should_ be found automatically, please open a bug at https://github.com/sfackler/rust-openssl and include information about your system as well as this message.
> 
> $HOST = x86_64-unknown-linux-gnu $TARGET = x86_64-unknown-linux-gnu openssl-sys = 0.9.104
> 
> It looks like you're compiling on Linux and also targeting Linux. Currently this requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config` could not be found. If you have OpenSSL installed you can likely fix this by installing `pkg-config`.
> 
> warning: build failed, waiting for other jobs to finish... error: failed to compile `cargo-generate v0.22.0`, intermediate artifacts can be found at `/tmp/cargo-installi7avY6`. To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.


Solved Problem:
```bash
sudo apt install pkgconf
pkg-config --libs --cflags openssl
cargo install cargo-generate
```
