### ISSUE TITLE
Remind the user when an override is set

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/cargo#1743]
It prints the URL, but it would be nice if it said something like `Compiling azure (override: file:///Users/pcwalton/Source/azure)` to remind me that overrides are in place without me having to parse the URL.

**Comment by alexcrichton** [comment]
This might be a great use case for more terminal colors as well.

**Comment by Dineshs91** [comment]
I think this is pretty easy to do. We can add `override:` [here] (https://github.com/rust-lang/cargo/blob/master/src/cargo/core/package_id.rs#L175) by checking if source_id.is_path. 

I am not clear, how to add terminal colors to fmt::Display()
