### ISSUE TITLE
'no entry found for key'

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/cargo#1751]
See https://github.com/PistonDevelopers/conrod/issues/485
PR https://github.com/PistonDevelopers/conrod/pull/486

`rustc 1.3.0-nightly (e5a28bca7 2015-06-25)`
`cargo 0.3.0-nightly (e6fff69 2015-06-24) (built 2015-06-24)`

When trying to update the dependencies in Conrod, I get:

Running with `RUST_BACKTRACE=1 cargo test`:

```
thread '<unnamed>' panicked at 'no entry found for key', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:330
stack backtrace:
   1:        0x10a39a8e5 - sys::backtrace::write::h6e963597537e900csas
   2:        0x10a3a17f4 - panicking::on_panic::hc6a54e36471e710eOtw
   3:        0x10a37bbd8 - rt::unwind::begin_unwind_inner::hc2503abaf1a353b16bw
   4:        0x10a37c36c - rt::unwind::begin_unwind_fmt::h5191fd3526b65934cbw
   5:        0x10a3a10ac - rust_begin_unwind
   6:        0x10a3c5225 - panicking::panic_fmt::h77445f1832864594i5B
   7:        0x10a133cc2 - ops::cargo_rustc::rustc::closure.33096
   8:        0x10a133336 - ops::cargo_rustc::job::F.FnBox<A, R>::call_box::h2785876919849651134
   9:        0x10a0f3569 - ops::cargo_rustc::job::F.FnBox<A, R>::call_box::h1688256377523264599
  10:        0x10a202532 - ops::cargo_rustc::job::F.FnBox<A, R>::call_box::h14669685106895006122
  11:        0x10a11ebed - F.FnBox::call_box::h13519971316597680418
  12:        0x10a261ecb - boxed::F.FnBox<A>::call_box::h5956848479252763573
  13:        0x10a260b17 - rt::unwind::try::try_fn::h4043412221538007623
  14:        0x10a3a3698 - rust_try_inner
  15:        0x10a3a3685 - rust_try
  16:        0x10a392ef5 - rt::unwind::try::inner_try::hf8418fa68612ccb4Z7v
  17:        0x10a260d72 - boxed::F.FnBox<A>::call_box::h10946525392169938074
  18:        0x10a3a017d - sys::thread::Thread::new::thread_start::h143ebbdca41cb5fdywv
  19:     0x7fff95cf4898 - _pthread_body
  20:     0x7fff95cf4729 - _pthread_start
```

**Comment by alexcrichton** [comment]
Hm I can't seem to reproduce this, and the travis logs on that PR seem to indicate an otherwise legitimate error?

**Comment by bvssvni** [comment]
Might be an OSX issue. Investigating.

**Comment by csherratt** [comment]
@bvssvni You can work around this issue by setting the the number of jobs to 1. `cargo test -j 1`

**Comment by bvssvni** [comment]
It works with `cargo test -j 1`.

**Comment by csherratt** [comment]
The issue occurs when a `[dev-dependencies]` are used that include a native library that are needed for tests/examples but not the library itself. Cargo correctly understands that the `[dev-dependencies]` do not need to be be build before the library can be build. But it incorrectly adds them as a build dependencies in order to capture their link flags. As the build for these projects is not done, the build_state will not be filled for these packages (yet).

Anyone effected by this bug can work around it in one of two ways:
1) do a `cargo build` before a `cargo test`
2) move the native `[dev-dependencies]` to be `[dependencies]`

**Comment by alexcrichton** [comment]
@csherratt do you have a minimized example I can reproduce on? I unfortunately still can't reproduce this...

**Comment by csherratt** [comment]
@alexcrichton here is a minimal project that reproduces the bug https://github.com/csherratt/cargo_issue_1751

```
cargo 0.4.0-nightly (4e5fdcd 2015-06-29) (built 2015-06-29)
rustc 1.3.0-nightly (faa04a8b9 2015-06-30)
```

**Comment by alexcrichton** [comment]
Thanks for the example @csherratt! I've reproduced and am investigating.
