### ISSUE TITLE
Copy files to target directory after build, before run

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/cargo#1759]
Let's assume I have a game with the following directory structure:

    /src
    /resources
    Cargo.toml

I would like `cargo build` (and `cargo run`) to copy the files in the `resources` directory and paste them in the same directory as the executable file. This way I could run the game directly, without having to move things myself or using a custom script.

I think this situation can be pretty common for other projects as well and I have seen it implemented for other languages (for example, Visual Studio can do this for C# projects). Do you think it would be a good idea for Cargo?

Maybe something like

```
[resources]
path = [
    "resources_dir_1",
    "resources_dir_2"
]
```

**Comment by alexcrichton** [comment]
Would build scripts suffice for this? I feel like adding one-off features like this doesn't interoperate as well if we've got build scripts already which can perform arbitrary actions like this.

**Comment by aochagavia** [comment]
My primary concern is that many people will reinvent the wheel in a build script to achieve the same result. However, I realize now that there are good alternatives to this feature.

I think I am going to write a little library to copy files from a directory to the target directory. People could use it from their custom build script with a one-liner. With that in mind, I think this issue can be closed.

**Comment by StelarCF** [comment]
The biggest issue here is that if you have to do your own build script for this, you're going to have to track files that changed yourself, which is an annoyance considering what cargo wants to achieve, or you're going to just prolong your build times because of files being moved around all the time...

**Comment by iMplode-nZ** [comment]
@aochagavia What library is this?

**Comment by jangorecki** [comment]
Could we re-open this FR? Person who opened it doesn't need it anymore but there are others who would find it useful.

My use case: I have an app specific app.toml config file in project root dir. It is used to replaces interface of command line arguments by specifying them in app.toml file.
As long as my project uses only `src/main.rs` the app.toml config file from root dir is reachable during `cargo run`. After splitting code into `main.rs` and `lib.rs` the `cargo run` command now fails because it cannot find a file anymore (`No such file or directory`).
If this feature is not going to be implemented I think the problem (and some references to possible solutions) should be explained in https://doc.rust-lang.org/book/ch12-03-improving-error-handling-and-modularity.html where splitting main into main+lib is describe, but as of now, now comprehendingly enough.

**Comment by thehappycheese** [comment]
I am sad that this has been closed :( This is a good idea. Why would cargo need to track changes to these files? Just copy paste-overwrite. Seems like it should be a one-liner in the Cargo.toml. My use-case is a single small file called config.json which i would like to edit in /src directory and have copied to be in the working directory of the executable (somewhere buried in "target" i don't want to care where)

**Comment by kotx** [comment]
I'd like to include more dynamic resource loading for my game, so I can have a user-customizable `resources` directory. I'd like for the existing directory to be copied to build output as well.

**Comment by sam0x17** [comment]
I would also use this feature. Need to copy a dll file to the target directory that I'm linking with

**Comment by iMplode-nZ** [comment]
Who do we ping in order to get this reopened?

**Comment by iMplode-nZ** [comment]
An alternative solution to this would be to make a wrapper package, that depends on the actual package, and has build.rs doing the copying.

**Comment by sam0x17** [comment]
I was able to solve my issue with the following:
```rust
fn get_output_path() -> PathBuf {
    //<root or manifest path>/target/<profile>/
    let manifest_dir_string = env::var("CARGO_MANIFEST_DIR").unwrap();
    let build_type = env::var("PROFILE").unwrap();
    let path = Path::new(&manifest_dir_string).join("target").join(build_type);
    return PathBuf::from(path);
}

# and then inside my build.rs main() method:
fn main() {
// ...
    let out_dir = env::var("OUT_DIR").unwrap();
    let target_dir = get_output_path();
    let src = Path::join(&env::current_dir().unwrap(), "vendor\\ViGEmClient.dll");
    let dest = Path::join(Path::new(&target_dir), Path::new("ViGEmClient.dll"));
    fs::copy(src, dest).unwrap();
// ...
```

**Comment by aleokdev** [comment]
Any progress on this? There are still no nice solutions to achieve this in a simple way. Build scripts are a lot of extra work and copying folders is no easy task without an extra dependency.

**Comment by 7tsvn** [comment]
I have written a small library to do this
You can find it here: https://crates.io/crates/copy_to_output/

**Comment by piratf** [comment]
It's hard to make a convenient example with rust when it needs some config files.
In c++, I can use CMake to manage all the dependencies, and the IDE supports it smoothly.
In rust, I have to write a bunch of "start.sh"\"start.cmd"\"start.bat" for each of them, feels bad.

**Comment by duaneellissd** [comment]
I too need this feature for numerous reasons.

I think this could be solved very simply - by something like this:
```
[package.build]
pre_build_command_line="some command line here" executed blindy via "std::process::command"
# the existing build.rs 
build=build.rs
post_build_command_line="some command here"
```
In both cases - RUST has a feature called: "std::process:command" that looks like it could handle this.
The general idea should be something like:

1)  "everything in the quoted string" is passed to the 'system()' function in the standard C library.
2) If the command exits 0 processing continues.
3) If the command exits NON-ZERO - processing halts.

One quick example here is  I need to  A) "digitally sign" the executable then B) using ssh push the image to the test/target machine and C) using ssh - execute commands on the target machine. In this case: HOST=x86 linux, target=ARM64 Linux.

In both cases, CARGO should expose as many ENV Vars as possible.
For example the script might need to do other things if building for unit test environment on an x86 host, and something totally different on an ARM64 linux target.

Another use case:
    I need to build 'scaffolding' - aka: An x86 library (Written in C, and some things in python) that emulate features only present in my physical arm64 target.

**Comment by ssokolow** [comment]
> "everything in the quoted string" is passed to the 'system()' function in the standard C library.

In this day and age, pretty much anything related to `system()` is considered Bad Practice™ and Deprecated™ for the same reason that SQL client libraries moved to parameterized SQL. Languages like Python have already migrated away from `system`-style APIs.

To be consistent with APIs elsewhere which are designed to resist becoming command injection footguns, `post_build_command_line` should at least take a list of literals which don't have any kind of interpolation done on them.

However, it would be much more consistent with how Rust currently operates to just run a `post_build.rs` after the build if you make it in the project root, similar to how `build.rs` gets run before the build.

**Comment by shanelenagh** [comment]
> Would build scripts suffice for this? I feel like adding one-off features like this doesn't interoperate as well if we've got build scripts already which can perform arbitrary actions like this.

This might help no-one, but I have this in my build.rs build script to copy some native dependencies for a native/unsafe integration project to the target build folder--and I totally realize it might not solve the OP problem, just sharing for anyone it does help; it doesn't happen "after" the main build, but I don't need it to in my case, as it happens after the cmake native build runs in the code above it:


```
    // Copy dependency lib's to ./target/{releaseType}
    let build_type_dir = if env::var("DEBUG").unwrap() == "true" { "Debug" } else { "Release" };
    let source_pattern = format!("{}/build/{}/*.*", target.display(), build_type_dir);
    for entry in glob(&source_pattern)? {
        let path = entry?;
        let file_name = path.file_name().ok_or("Invalid file name")?;
        let destination_path = Path::new(&("./target/".to_owned() + build_type_dir)).join(file_name);
        eprintln!("Copying {:?} to {:?}", &path, &destination_path);
        let _ = fs::copy(&path, &destination_path);
    }
```

**Comment by epage** [comment]
As accessing the target-dir is fraught with issues (#9661), #13663 is where we are focusing the conversation on build scripts staging final artifacts.  In #14903, we are working towards reusable build scripts that are data driven which would be a good way to experiment with doing this in a data driven way before considering whether built-in data driven resources should be supported and how.

**Comment by duaneellissd** [comment]
A pre/post_build.rs script would greatly help here
 
You might want to pass some flags to that script ie build success or test success or test NAME failed 

Because in some cases you might need to sign the binary the copy it to a remote machine or jtag the image to run the test
