### ISSUE TITLE
ops::CompileFilter restricts cargo/rustc’s operational scope

### ISSUE THREAD

**Issue by kayellpeee** [rust-lang/cargo#1767]
`ops::CompileFilter` sometimes restricts cargo from passing all relevent information to rustc.

If I have a /tests directory, filled with both `#[test]`’s and `#[benchmark]`’s, `cargo test` treats both as tests. Additionally, `cargo bench` won’t look in the /tests directory, even if there is no /benches directory. Benchmarks should lie in /benches, but perhaps it would be prudent to warn:
```
#[bench] found in /tests directory. Consider moving to /benches
```
on both `cargo test` as well as `cargo bench` with that given project architecture (I don’t know if there’s a similar issue with `cargo docs`).

At the very least cargo shouldn’t exclude /tests directory from being searched for `#[benchmark]` unless /benches is present. And `cargo test` should not tell rustc that `#[benchmark]`’s found in /tests should be treated like a `#[test]` (not entirely sure if that is what’s happening though — I’m not intimate with cargo's internals).

However, creating that warning message would require some communication between cargo and rustc, no? Implementing this functionality will be a bit tricky, and I’m not sure how to go about doing it without adding complexity to cargo.

Would like a little clarification on this if possible, then would love to submit a PR that resolves the issue.

**Comment by alexcrichton** [comment]
I'm not really sure what's going on here, `CompileFilter` is a structure that's internal to Cargo itself and what benchmarks/tests Cargo runs is orthogonal to how it probes for them. You can test any benchmark via `cargo test --bench foo` and you can benchmark any test with `cargo bench --test foo`.

Can you elaborate a little more on what you're trying to do, what's happening, and what you expect to happen?

**Comment by kayellpeee** [comment]
Sorry for the confusion. I don’t really know how cargo probes for tests/benches—I think that’s the real issue.

[Here is my project](https://github.com/kayellpeee/cipha/tree/9b125a3b460b7802199b113b6da3a6cf7c6d46f0), in the state when I first encountered the issue. There are a mix of benchmark tests and normal tests in src/lib.rs. I’m trying to move all my benches and tests out of /src directory for clarity & brevity.

At first I moved them all into a /tests directory [(see commit c835)](https://github.com/kayellpeee/cipha/tree/c835eb74b7f8cf427f64499c8f31d49727625a4c). The file in /tests contains both `#[test]` functions and `#[bench]` functions. At that point, running `cargo test` runs all `#[test]` *as well as all `#[bench]`*.

`cargo bench` runs 0 tests, `cargo bench --test paragraph_decryption` returns `no test target named ‘paragraph_decryption'`. `cargo test --bench paragraph_decryption`: `no bench target named 'paragraph_decryption'`¹. Strikeout.

I wanted `cargo bench` to run the 4 benches I set up in tests/lib.rs. I’ve since found out that cargo expects all benchmarks tests to be in /benches [(see commit 315d)](https://github.com/kayellpeee/cipha/tree/315dba74940fb28499a75ad80190104082fe9ec1), as long as one part of `ops::CompileFilter` is present. The offending lines of code in cargo [(link)](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_compile.rs#L219-L233):

```
pub fn new(lib_only: bool,
               bins: &'a [String],
               tests: &'a [String],
               examples: &'a [String],
               benches: &'a [String]) -> CompileFilter<'a> {
if lib_only || !bins.is_empty() || !tests.is_empty() ||
!examples.is_empty() || !benches.is_empty() {
            CompileFilter::Only {
                lib: lib_only, bins: bins, examples: examples, benches: benches,
                tests: tests,
            }
        } else {
            CompileFilter::Everything
        }
    }
```

However, if main directory is not what cargo expects it to be while probing for benchmarks/tests, I think there should be some sort of warning (i.e. “Hey, there’s some benchmark tests in /tests directory. I’m going to run those as tests. If you don’t want that, would you mind making a new directory—/benches—and putting them there?). That’s what this issue tries to make a case for.

--
¹ I’ve never come across `cargo test --bench foo` before, I thought I had to explicitly write a function, foo, and mark it with the attribute `#[bench]` in order to benchmark it.

**Comment by alexcrichton** [comment]
Hm ok, I'm going to classify this as a docs issue to make sure we get this straight. Otherwise I don't think there's a bug here, but I'll try to explain what's going on.

Cargo has a notion of benchmarks and tests as targets, but these do not correspond to the literal `#[test]` and `#[bench]` attributes, they're basically just entry points for crates. These are automatically probed from the `tests/` and `benches/` directories, but you can also specify them in `Cargo.toml` via `[[test]]` and `[[bench]]`. 

When you run `cargo <foo> --test name` then it will try to find the test *target* named `name` and run the command `<foo>` for it. This is why `cargo bench --test paragraph_decryption` didn't work, you'd instead need to specify `cargo bench --test lib` because the name of the test is `lib` (e.g. it was found in `tests/lib.rs`).

**Comment by kayellpeee** [comment]
Ahhh, thanks for the clarification!

**Comment by steveklabnik** [comment]
So, what should be added to the documentation and where?

**Comment by alexcrichton** [comment]
I believe the target selection flags, `--test`, `--bench`, etc, just need to be clarified as selecting *targets*, not unit tests to run.
