### ISSUE TITLE
fail to build cargo behind  proxy

### ISSUE THREAD

**Issue by Jfromchina** [rust-lang/cargo#1771]
I am trying to build cargo from source behind a proxy,  It tells like this:

$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [12] SSL error: error:140E0114:SSL routines:SSL_shutdown:uninitialized

I have configed environment variables like this:
export HTTP_PROXY=proxy.example.com:8000
export HTTPS_PROXY=proxy.example.com:8000
export FTP_PROXY=proxy.example.com:8000

there is no config file under .cargo dir，does it because of this? what can I do next? By the way, dose the git need to config either? how? I am a new user for Rust, thanks a lot!

**Comment by alexcrichton** [comment]
Does `curl` work for you behind the proxy? Is the proxy trying to do some funny SSL business? If the proxy is trying to give you an invalid certificate then this is likely to happen. Lots more info can be found in https://github.com/rust-lang/cargo/issues/636

**Comment by pnkfelix** [comment]
I spoke to @Jfromchina in person; he (or we) think fixing #1180 would address this.

**Comment by alexcrichton** [comment]
Ok, in that case I'm going to close this in favor of that
