### ISSUE TITLE
Manifest field to select default build targets for project.

### ISSUE THREAD

**Issue by aXe1** [rust-lang/cargo#1784]
It would be nice to have a field in manifest for selecting default build targets.
#### Use case 1
I have a project with support for 3 targets. Just now I have to manually ask cargo to build one:
```cargo build --target=<triplet>```
For testing purpose and production it is reasonable to build for all platforms (as example). And now it would be 3 calls to Cargo. But when I debug one of them I do not need neither all of then, nor cargo current default.
#### Use case 2
For project with only one (cross-compiling) target (such as arm-linux-androideabi), we also have to specify target by hand every time we use cargo. But it's project specific, so it should be in `Cargo.toml`, I think.

**Comment by alexcrichton** [comment]
Thanks for the issue! Dealing with targets, however, is quite a platform specific issue and doesn't quite seem like something that belongs in a manifest. For example all compilers we distribute today can only currently target one platform, and whether or not a project will compile for a various platform or not probably shouldn't be limited by the manifest.

For first case you have you can probably just provide a script in the repo which builds all the necessary targets, and for the second case it seems like a `README` mention with a TODO of porting to more platforms.

**Comment by aXe1** [comment]
It isn't critical, I agree. But I don't understand enough: if Cargo is a package manager, then why (ideally) should I need additional script for build process? Also similar entities for other languages has that feature. Proofs: Ruby's [RubyGems](http://guides.rubygems.org/specification-reference/#platform=), Ruby's [Bundler](http://bundler.io/v1.3/man/gemfile.5.html) (see "PLATFORMS (:platforms)" section), Python's [PIP](https://www.python.org/dev/peps/pep-0425/#id13), Haskell's [Cabal](https://www.haskell.org/cabal/users-guide/developing-packages.html#meaning-of-field-values-when-using-conditionals) (See "Conditions" in "Configuration" section).

**Comment by alexcrichton** [comment]
Cargo allows you to have platform-specific configuration, but Cargo is not trying to be a complete build system. It sounded like this was a bug that wasn't asking for *configuration* though, but rather changing the behavior of `cargo build`?

**Comment by aXe1** [comment]
Both of them: add configuration options and make `cargo build` use them (so the default behavior would change).
> Cargo is not trying to be a complete build system

Why? Is there are plans for another tool for that sort of functionality, or GNU make is enough, and there are no need for special Rust build system?

**Comment by alexcrichton** [comment]
Cargo does not want to be a complete build system because that's just not what it's chartered to do. Cargo builds Rust code well, but you need to rely on other external tools to do more advanced features.
