### ISSUE TITLE
zsh completion cargo _locate_manifest dont likes 'spaces' in path

### ISSUE THREAD

**Issue by Kerollmops** [rust-lang/cargo#1790]
Hello,

I try to fix some error form the zsh completion file `src/etc/_cargo`... but I don't find the bug...
It seems like zsh don't like bad file path in local variable, when I try to do `cargo bench -p=\tab` in a cargo repo which have a space in it's path name, the completion crash with a cropped name.
Like: `42 jobs/genetic-rs` become `jobs/genetic-rs`...
That's coming from `local manifest=$(cargo locate-project 2> /dev/null)`(300) I think...

The error is transmitted to `_get_package_names` which call `_locate_manifest`

Thanks in advance

**Comment by cyplo** [comment]
Hello ! 
Could you let us know if the original crash is still there for you ?
I tried doing the same, got completion for `--p[\tab]` that got me `--package=` with no evidence of crash.
Same for `-p=`.
However, I think that `=` in the option does not work, as cargo is complaining of `invalid package id specification` then.

I wonder what would be the ideal completion mechanism here ?

thanks a lot !

**Comment by carols10cents** [comment]
It sounds like this might not be an issue anymore, or at least that there's a workaround. Please reopen with reproduction steps and clarify what is meant by "crash" if this is still a problem! Thanks!
