### ISSUE TITLE
Set the working directory to the top level directory

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/cargo#1791]
I tried to discuss this [here](https://github.com/rust-lang/cargo/issues/293), but received no response, so I'm opening a new issue. Here is my comment copied over:

>I'd actually prefer the working directory to be set to the top level directory. I have folders like resources at the top level, and I'd like to be able to access them regardless of which folder I was in when I ran cargo run. I'm used to this behavior from Java/Eclipse, so there is some precedent for this.

>What's the benefit of making the current directory the working directory?

**Comment by alexcrichton** [comment]
> What's the benefit of making the current directory the working directory?

This reflects how `cargo run` is just a thin wrapper around running an executable, you can set the current directory by setting the current directory of where `cargo run` is run, and then you can select a project via `--manifest-path`.

This also reflects how many other tools execute sub-processes in how they tamper with as few environment values as possible.
