### ISSUE TITLE
recommend semver-abiding version number

### ISSUE THREAD

**Issue by blaenk** [rust-lang/cargo#1793]
This is a long-term feature request.

It would be great if cargo were able analyze rust code in comparison to the previous crate version to determine the severity of the changes in order to recommend --- or perhaps even enforce --- a semver-abiding version number.

I got this idea after reading that [Elm does this](https://github.com/elm-lang/elm-package#version-rules), which I thought was pretty awesome.

**Comment by cmr** [comment]
There's a long series of issues on the Rust repo about doing this.

**Comment by blaenk** [comment]
Alright then.

**Comment by blaenk** [comment]
I'll leave it up to you guys to close it if you decide it should be closed. It seems that this idea has been proposed before for rust in general, but I'm specifically requesting that the functionality be added to cargo when and if it's possible.

**Comment by blaenk** [comment]
Nevermind, I found #374
