### ISSUE TITLE
Cargo build doesn't watch for the code generated by build.rs

### ISSUE THREAD

**Issue by can3p** [rust-lang/cargo#1794]
Hi everyone,

In general cargo does a great job by watching for changes in the source code before doing a build, but recently I got into situation where I wanted to generate some code at compile-time. According to the [build tutorial](http://doc.crates.io/build-script.html) I've added a build.rs script that generates a simple code depending on contents of env var:

```rust
fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let test_var = env::var("TEST_VAR").unwrap_or("not set".to_string());
    let out_path = Path::new(&out_dir).join("test_var.rs");
    let mut f = File::create(&out_path).unwrap();

    f.write_all(format!("
        static TEST_VAR: &'static str = \"{}\";
    ", test_var).as_bytes()).unwrap();
}
```

Then I include the generated file in main.rs and print contents of the variable (the full repo is [here](https://github.com/can3p/rs-env-test))
```rust
include!(concat!(env!("OUT_DIR"), "/test_var.rs"));

fn main() {
    println!("test var is {}", TEST_VAR);
}
```

The problem is that cargo either doesn't launch build.rs script because other source files do not change or doesn't watch for changes in generated files.

```bash
~ TEST_VAR=test1 cargo run
   Compiling rs-env-test v0.1.0
     Running `target/debug/rs-env-test`
test var is test1
~ TEST_VAR=test2 cargo run
     Running `target/debug/rs-env-test`
test var is test1
```

Is it intentional behavior? If so, what is suggested way of working around such issues? I could have used features but in my case I don't need a flag, I need and option with value which I can pass to the source code.

The behavior was tested on latest nightly.

**Comment by alexcrichton** [comment]
Yeah this is currently intentional. Cargo, like `make` and many other build systems, watches the mtime of files to determine when a build script should be re-run and rebuilt. It doesn't consider changes to the environment as candidates for re-running a built. To re-run the build script you can just `touch build.rs` and that should trigger a recompile!
