### ISSUE TITLE
failure to resolve with equality requirement.

### ISSUE THREAD

**Issue by danburkert** [rust-lang/cargo#1800]
Cargo fails to resolve a dependency with an equality requirement if a newer version is published.

Steps to reproduce: clone https://github.com/carllerche/mio/commit/eed4855c627892b88f7ca68d3283cbc708a1c2b3 and change the dependency on libc from "0.1.8" to "=0.1.8".  `cargo build` fails with the following error:

```
failed to select a version for `libc` (required by `mio`):
all possible versions conflict with previously selected versions of `libc`
  version 0.1.9 in use by libc v0.1.9
  possible versions to select: 0.1.8
```

**Comment by carllerche** [comment]
libc 0.1.9 was yanked. Going to close this.

**Comment by carllerche** [comment]
Woops, I thought this was the mio repo
