### ISSUE TITLE
Compiling Cargo from source - missing libssl

### ISSUE THREAD

**Issue by simendsjo** [rust-lang/cargo#1806]
**EDIT:** Oops.. I see it's looking for the *static* library, which I don't have on my system. I don't even know which package should supply this library.

----

I'm trying to build Cargo from source, but I get an error about missing the native `ssl` library.
Not sure if this is a Cargo or `openssl-sys` issue, but I think the problem was there a week ago too, and I guess others are happily building Cargo from source.

The error:

```
$ make
# ... snip ...
   Compiling openssl-sys v0.6.4
error: could not find native static library `ssl`, perhaps an -L flag is missing?
Could not compile `openssl-sys`.
```

```
$ locate libssl.so | grep '/usr/lib'                                                                                                                           
/usr/lib/libssl.so
/usr/lib/libssl.so.1.0.0
/usr/lib32/libssl.so
/usr/lib32/libssl.so.1.0.0
```

**Comment by tamird** [comment]
rust-openssl's docs appear to provide some guidance https://github.com/sfackler/rust-openssl

**Comment by alexcrichton** [comment]
@simendsjo do you have the `OPENSSL_STATIC` environment variable set? It looks like that's the reason rust-openssl may try to link statically vs dynamically.

**Comment by simendsjo** [comment]
@alexcrichton:
I don't have `OPENSSL_STATIC` defined, and I cannot see it being
defined in either cargo nor openssl. When compiling with verbose,
I get the following:

```
     Running `rustc /home/simendsjo/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.6.4/src/lib.rs --crate-name openssl_sys --crate-type lib -C opt-level=3 -C metadata=149f6ef08ad7404d -C extra-filename=-149f6ef08ad7404d --out-dir /mnt/win/simendsjo/code/rust/cargo/target/x86_64-unknown-linux-gnu/release/deps --emit=dep-info,link --target x86_64-unknown-linux-gnu -L dependency=/mnt/win/simendsjo/code/rust/cargo/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/mnt/win/simendsjo/code/rust/cargo/target/x86_64-unknown-linux-gnu/release/deps --extern libc=/mnt/win/simendsjo/code/rust/cargo/target/x86_64-unknown-linux-gnu/release/deps/liblibc-2eda841eb12a3090.rlib -Awarnings -L /home/rustbuild/root64/lib -l static=ssl -l static=crypto -l dl`
```

The last part shows that it's trying to use the static libraries.

Looking at `./configure`, I see that using `--enable-nightly`
might be of importance:

```
if [ ! -z "$CFG_ENABLE_NIGHTLY" ]; then
    if [ ! -f .cargo/config ]; then
        mkdir -p .cargo
        cat > .cargo/config <<-EOF
[target.x86_64-unknown-linux-gnu.openssl]
rustc-flags = "-l static=ssl -l static=crypto -l dl -L /home/rustbuild/root64/lib"
root = "/home/rustbuild/root64"
include = "/home/rustbuild/root64/include"

[target.i686-unknown-linux-gnu.openssl]
rustc-flags = "-l static=ssl -l static=crypto -l dl -L /home/rustbuild/root32/lib"
root = "/home/rustbuild/root32"
include = "/home/rustbuild/root32/include"
EOF
    fi
fi
```

I tried without `--enable-nightly`, but then I get a lot of errors
due to `#[deny(missing_docs)]` in various libraries.

I tried deleting `~/.cargo` and running again, but the same errors
apply.

I really have no idea how I should try to locate these issues.

**Comment by alexcrichton** [comment]
Ah I see! You shouldn't need to configure Cargo with `--enable-nightly`  as that's just meant for the bots (like in the normal Rust distribution) and you also may want to [follow the instructions](https://github.com/rust-lang/cargo#compiling-from-source) for compiling from source in the README, as it'll show how to download the same version of Rust we're using to test on the bots.

Updating dependencies for `missing_docs` warnings is done in a separate PR, and I hope to set up automation soon for all three channels of Rust, so I'm going to close this for now as if you don't use `--enable-nightly` it should fix the problem as listed.

**Comment by simendsjo** [comment]
I tried updating my rust installation from source and then cargo (without nightly). It works now. I guess I was a bit unlucky with my combination of rustc/cargo.
