### ISSUE TITLE
cargo build instructions and scripts don't address `git submodule`

### ISSUE THREAD

**Issue by brianolson** [rust-lang/cargo#1807]
There was #1071 but the line in the README about git submodule was lost for a line about install-deps.py which does not do anything with git submodule. Thus the instructions and/or scripts are wrong again.

Really `git submodule` should not be used. It's not okay to tell git "check out the code" and git tell you it did but then it didn't check out all the code. Mercurial and Subversion get this right. git submodule is broken and should not be used.

**Comment by brianolson** [comment]
change was cfb69ad256fc7e16d271d755339345fbfa892b9d

**Comment by achanda** [comment]
@alexcrichton this one can be closed now, I believe

**Comment by alexcrichton** [comment]
Thanks!
