### ISSUE TITLE
Cargo fails to install on OS X 10.11 public beta

### ISSUE THREAD

**Issue by arynhard** [rust-lang/cargo#1816]
Following the installation instructions I get the following:

````
"/Users/andrewrynhard/Desktop/cargo/rustc/bin/rustc" -V
dyld: Library not loaded: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-74fa456f.dylib
  Referenced from: /Users/andrewrynhard/Desktop/cargo/rustc/bin/rustc
  Reason: image not found
make: *** [cargo-x86_64-apple-darwin] Trace/BPT trap: 5
````

I tried exporting `DYLD_LIBRARY_PATH` and `rustc` works

````
export DYLD_LIBRARY_PATH=/Users/andrewrynhard/Desktop/cargo/rustc/lib/
./rustc/bin/rustc -V
rustc 1.3.0-nightly (7ea2674c7 2015-07-13)`
````
however `make` still fails with the above error. Changing 

````
define CARGO_TARGET
cargo-$(1): $$(CARGO)
        "$$(CFG_RUSTC) -V"
        "$$(CARGO)" --version
        $$(CARGO) build --target $(1) $$(OPT_FLAG) $$(VERBOSE_FLAG) $$(ARGS)

test-unit-$(1): $$(CARGO)
        @mkdir -p target/$(1)/cit
        $$(CARGO) test --target $(1) $$(VERBOSE_FLAG) $$(only)
ended
````

to

````
...
        $$(CFG_RUSTC) -V
        $$(CARGO) --version
        $$(CARGO) build --target $(1) $$(OPT_FLAG) $$(VERBOSE_FLAG) $$(ARGS)
...
````
seems to fix the issue, but now I am getting
````
failed to run custom build command for `libssh2-sys v0.1.26`
````

**Comment by felixbuenemann** [comment]
This is due to a security "feature" in El Capitan. You can no longer export DYLD_LIBRARY_PATH to childprocesses:
```bash
DYLD_LIBRARY_PATH=foo printenv DYLD_LIBRARY_PATH
# no output
_DYLD_LIBRARY_PATH=foo printenv _DYLD_LIBRARY_PATH
foo
```
See https://forums.developer.apple.com/message/31148 for more info.

**Comment by alexcrichton** [comment]
Umm... oh dear! Do you know if there's a way to specify `DYLD_LIBRARY_PATH` to child processes @felixbuenemann? This may be otherwise quite unfortunate...

**Comment by felixbuenemann** [comment]
@alexcrichton You can still use DYLD_LIBRARY_PATH if it is used in the same shell, but you can no longer export it to subshells. It is a bit hard to describe:

```bash
$ cat test.rb
#!/usr/bin/env ruby
puts "test.rb DYLD_LIBRARY_PATH=#{ENV['DYLD_LIBRARY_PATH']}"

$ DYLD_LIBRARY_PATH=foo ruby test.rb
test.rb DYLD_LIBRARY_PATH=

$ DYLD_LIBRARY_PATH=foo ./test.rb
test.rb DYLD_LIBRARY_PATH=
```
So calling the script directly using the ruby binary works. But spawning ruby via a shebang doesn't. So you can still use DYLD_LIBRARY_PATH as long as you don't use shell wrappers, or you need to set it from within the shell wrappers.

This would work as a rustc wrapper script:
```bash
#!/bin/sh
rust_root="/opt/rust-1.2.0"
DYLD_LIBRARY_PATH="${rust_root}/lib" exec ${rust_root}/bin/rustc $*
```
This means that multirust which uses a similar technique keeps working on 10.11.

**Comment by arynhard** [comment]
@felixbuenemann: Thank you. I still do not know why removing the double quotes fixed this issue.
