### ISSUE TITLE
Allow subdirectories with no Cargo.toml

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/cargo#1820]
For a personal project, I wanted to add several examples under a same "examples" subdir.
I had to put a dummy Cargo.toml and src/main.rs in order for it to work, otherwise cargo complained.

See https://github.com/Keruspe/tar-parser.rs/commit/a0c64813f1624a911c7abfef19e139402c9d6c04

**Comment by alexcrichton** [comment]
Can you elaborate a little more? It's unclear what error messages you were seeing, what you were trying to do, and why adding a sub-Cargo.toml ended up fixing the issue.

**Comment by Keruspe** [comment]
nvm, the issue was not what I thought it was.
The problem came from one of the example's Cargo.tml.
