### ISSUE TITLE
Vendoring dependencies for offline builds

### ISSUE THREAD

**Issue by crawford** [rust-lang/cargo#1823]
What is the recommended approach for vendoring dependencies? I have a project that needs to be built in a Gentoo Portage environment. The environment is sandboxed, so Cargo won't be able to access the Internet or any files outside of the project's repo.

My current approach is to use `CARGO_HOME` and `cargo fetch` to commit a copy of the dependencies and the index. The downside to this approach is that there are now 6,378 files, totalling 50MB in my relatively small project.

I've also tried using path overrides, but I'm having trouble getting a number of dependencies building. Cargo is failing while trying to resolve dependencies listed under `[dev-dependencies]`. My understanding is that these dependencies are only needed for tests and benchmarks.

Any guidance would be greatly appreciated.

**Comment by alexcrichton** [comment]
This is currently the best way to do so without rewriting `Cargo.toml` files to use a `path = ...` dependency instead of a normal dependency.

**Comment by crawford** [comment]
Does that mean that I need to manually checkout each of the dependencies (and it's dependencies) into a known location? Or is there a more automated way to achieve this? I started down this path and quickly ran into trouble satisfying all of the dependencies.

**Comment by alexcrichton** [comment]
Yeah unfortunately that's the only way currently, there's no way Cargo provides to do something like this yet.

**Comment by crawford** [comment]
I'm missing something here. When I try to manually vendor the dependencies (download directly from crates.io and then specify a `path =` dependency), I see a lot of errors due to Cargo failing to read the manifest for dev dependencies. For example:

```
$ RUST_LOG=trace CARGO_HOME="${WORKDIR}/crates.io-index-master" cargo build --release --verbose
...
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/build/amd64-usr/var/tmp/portage/coreos-base/coreos-metadata-9999/work/rand-0.3.8/Cargo.toml; source-id=file:///build/amd64-usr/var/tmp/portage/coreos-base/coreos-metadata-9999/work/coreos-metadata-9999
DEBUG:cargo: handle_error; err=CliError { error: Could not find `Cargo.toml` in `/build/amd64usr/var/tmp/portage/coreos-base/coreos-metadata-9999/work/rand-0.3.8/rand_macros`, unknown: false, exit_code: 101 }
Could not find `Cargo.toml` in `/build/amd64-usr/var/tmp/portage/coreos-base/coreos-metadata-9999/work/rand-0.3.8/rand_macros`
```

Looking at the Cargo.toml file for rand, shows:

```
[dev-dependencies.rand_macros]
path = "rand_macros"
version = "*"
```

It looks like Cargo is attempting to resolve all dependencies, regardless of whether or not they are going to be compiled. In my case, this is a problem because I haven't downloaded the dev dependencies.

**Comment by alexcrichton** [comment]
Yeah Cargo will auto-translate `path` dependencies to crates.io dependencies when uploading, but it doesn't modify the `Cargo.toml`. You can basically just drop the `path` field on those manifests.

**Comment by crawford** [comment]
If I drop the `path` field, doesn't that imply that the package will come from the registry (which results in Cargo hitting the network)?

**Comment by alexcrichton** [comment]
Yeah, but if you're vendoring dependencies you're already handling crates.io dependencies, right? In general vendoring dependencies right now requires rewriting `Cargo.toml` as opposed to just providing `path` overrides.

**Comment by crawford** [comment]
Right, but doesn't Cargo still need to update it's index?

**Comment by alexcrichton** [comment]
Only if any of the dependencies come from the registry, if there are no registry dependencies then Cargo doesn't need to update the index.

**Comment by crawford** [comment]
How does it know if it comes from the registry? I've been slowly working my way through the code base, but I don't have much time these days.

**Comment by alexcrichton** [comment]
Each dependency in Cargo.toml indicates what its source is, and if one isn't specified then it comes from the registry by default. For example path dependencies have a `path` key, git dependencies have a `git` key, etc.

**Comment by crawford** [comment]
Ah, I see. I was able to get my project building without the registry (a very manual process). I'm going to try putting together a subcommand for doing this vendoring.

Thanks for your help.

**Comment by crawford** [comment]
I just saw https://github.com/alexcrichton/cargo-vendor. Awesome!
