### ISSUE TITLE
Command line options via env variable

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#1824]
Did you consider adding an env variable to indicate additional build options ? For example `CARGO_OPTS='-j 4' cargo build`.

**Comment by alexcrichton** [comment]
Currently cargo doesn't have this kind of ability, and for now I don't think we want to explore this realm. I suspect that we'd take the same route as the compiler (if we were to do this) as well.

**Comment by Yamakaky** [comment]
Which means ?

**Comment by alexcrichton** [comment]
Cargo doesn't currently do this, and probably won't until an RFC is written for both the compiler and Cargo.

**Comment by Yamakaky** [comment]
Ok, too bad.
