### ISSUE TITLE
Support local path dependencies (relative to root Cargo.toml) on crates.io

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/cargo#1833]
At the moment, cargo appears to explicitly disallow all path dependencies when uploading to crates.io, even those that could easily be packaged along with the user crate

This has lead to many single-use helper crates appearing on crates.io (e.g. [va_list-test](https://crates.io/crates/va_list-test)).

From an outsider's perspective, this could just be a matter of changing the packaging logic (to collect local path dependencies under the same package version) and loosening the dependency type restrictions.

**Comment by alexcrichton** [comment]
This is actually supported, you [just need a `version` field](https://github.com/alexcrichton/git2-rs/blob/master/Cargo.toml#L22) indicating what the version range of the dependency should be when it's on crates.io.

**Comment by thepowersgang** [comment]
... I don't see how the version field applies. This was about keeping single-use package out of the central crates.io repository (i.e. ones that are tightly coupled to the main package)

**Comment by alexcrichton** [comment]
Ah I think I may have misunderstood this bug, but it still stands that you can indeed publish path dependencies to crates.io. We decided to not allow multiple crates in one package on crates.io because it allows easier sharding of dependencies and extraction of reusable portions.
