### ISSUE TITLE
Cargo not passing arguments to binary

### ISSUE THREAD

**Issue by jhod0** [rust-lang/cargo#1855]
The `cargo run` command passes arguments like `1 2 3` or `<filename>` to the binary, but sees flags as arguments to cargo itself.

I have a crate which produces an executable which takes flags in the form of `./<mybinary> -r 4`. Executing `cargo run --bin <targetname> 4` works fine, but `cargo run --bin <targetname> -r 4` gives the error:

```
Unknown flag: '-r'

Usage
    cargo run [options] [--] [<args>...]
```

So, it looks like Cargo is trying to parse arguments intended for my binary. I think all arguments after `--bin <targetname>` should be passed straight to the executable. Arguments to cargo would then have to be before `--bin`.

My version info:
```
$ cargo --version
cargo 0.4.0-nightly (84ef25d 2015-07-23) (built 2015-07-23)
```

**Comment by alexcrichton** [comment]
This is part of our option parsing, you need to pass `--` as a separator between the flags to your binary and the flags to Cargo. `cargo run --bin foo -- -r 4` should do the trick!

**Comment by jhod0** [comment]
Ahh great that works fine. Thanks!  
That might be worth an explanation in `cargo help run` :)

**Comment by alexcrichton** [comment]
Sounds like a reasonable idea! reopening as a docs bug to add info about `--` to the cargo help page.

**Comment by ProtectedMode** [comment]
Shouldn't the usage just be changed from:
`cargo run [options] [--] [<args>...]`
to
`cargo run [options] [-- <args>...]`?

**Comment by alexcrichton** [comment]
Unfortunately that would require `--` be passed 100% of the time, which we don't want to do. It's just required for flags, not necessarily for positional arguments (e.g. `cargo run foo`)
