### ISSUE TITLE
Activation of optional dependencies from build scripts

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/cargo#1880]
One can say the following in a build script:

```rust
println!(r#"cargo:rustc-cfg=feature="foo""#);
```

The code instructs the compiler to enable a feature, and this feature becomes available in `#[cfg(…)]` queries. One can also say the following in the corresponding Cargo manifest:

```toml
[dependencies.foo]
optional = true
```

Since dependencies are essentially features, one might expect the dependency to be compiled and available for the package to make use of. However, this is not currently the case. The following code fails with “error: can’t find crate …”:

```rust
#[cfg(feature = "foo")]
extern crate foo;
```

So, `#[cfg(…)]` works, but the package is not there. I’m wondering if the activation of _optional_ dependencies from build scripts is something that can be useful for Cargo to have or if it’s a terrible idea.

Now it’s going to go off on a tangent, and I apologize for that in advance. My original motivation was to provide multiple mutually exclusive features and make one of them be the default one. Once a feature has been declared as default in the manifest, it’s hard to get rid of it: Suppose A depends on B, B depends on C, and C has a default feature D and an alternative feature E. Now A wants to switch from D to E, but it can’t since B already depends on D by default. The only solution that comes to my mind is to keep reexporting features in all packages that are on the way from C to A (only B in this example); this solution doesn’t scale well. I thought I would turn on the default feature from the build script of C if nobody has expressed any preference.

I would appreciate any thoughts. Thank you.

Regards,
Ivan

**Comment by alexcrichton** [comment]
I'm pretty wary about dynamically modifying the dependency graph during the build of a crate, I'd personally recommend just always building the dependency and then conditionally linking to it depending on whether the build script says it can be linked to or not.

**Comment by IvanUkhov** [comment]
Thanks for the reply! Let’s close this then.

**Comment by RReverser** [comment]
@alexcrichton This doesn't work in cases when specific `feature` might or might be not supported in current Rust version (this is a cross-issue with https://internals.rust-lang.org/t/setting-cfg-nightly-on-nightly-by-default/1893/8). In that thread it was recommended to use `rustc_version` crate from a build script, which solved automatically activating `[feature(...)]` based on stable/nightly versions of Rust, but doesn't solve dependency on a crate which can be built *only* on nightly Rust (in my case, `proc_macro` crate).
