### ISSUE TITLE
Consider post-build scripts, too

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/cargo#1894]
There are many actions that can be taken after the build that require custom steps:
- Making an installer (.deb / .dpkg / .apk / .msi / etc.)
- Codesigning the binary
- Uploading the output to an S3 bucket

While these can (and presumably are) done in larger projects by the autotools or CMake solution that is driving Cargo, it might be nice to be able to do it in Cargo itself instead of relying on the project's build runner.

**Comment by steveklabnik** [comment]
I would argue that many of these would just be additional Cargo commands that invoke 'build' first.

**Comment by larsbergstrom** [comment]
I'm not sure how that works if you have multiple of them (e.g., cargo-sign the binary, then cargo-package the signed binary, then cargo-upload the package), but possibly I'm just being dense, as I haven't been able to figure out how to work custom Cargo commands into Servo's build process yet (because we'd want to build them during the build process, but then they have to be on the `PATH`, which is... awkward).

**Comment by steveklabnik** [comment]
well, I'm thinking something like https://github.com/pwoolcoc/cargo-do, which lets you invoke multiple commands. So you'd write a `cargo package` that creates a .deb, but makes sure to invoke `cargo build` before it.

basically, in my mental model, 'cargo foo' is the equivalent of a `foo` task in a Makefile.

**Comment by alexcrichton** [comment]
I'm also not sure that this fits well into a manifest per se. It goes a bit against the idea that Cargo's not "yet another build system" but rather just a tool to build with. I could imagine small scripts being available in separate locations and you just `cd` into them and run `cargo run` perhaps from a build system to automate these various tasks.

Some thorny questions I can think of are:

* Are post-build scripts always run when the build finishes? Only when it's a top-level package?
* What if you don't want to run the scripts? For example I may not always want to build a .deb on all platforms all the time.
* What about dependencies for post-build scripts? Should they always be built or is it a separate dependencies section in Cargo.toml?

Using a separate crate altogether driven from a different location seems like a nice answer to many of these questions perhaps?

**Comment by larsbergstrom** [comment]
I think using a separate crate is fine. I'm glad to have some guidance around it, as we've had a bunch of discussion on how to design these things in #servo and #cargo (and with @tomaka), so it's good to put a nail in it.

Feel free to close the issue if you think there's nothing more to discuss!

**Comment by steveklabnik** [comment]
`npm` has a 'scripts' feature: https://docs.npmjs.com/misc/scripts

**Comment by alexcrichton** [comment]
Ok for now I think I'm in camp "use an external build tool to script after the build finishes", but we can certainly perhaps explore options here if the need becomes more pressing. We'll probably never do a script feature like npm does (e.g. not cross platform), but we could certainly add the ability to add more Rust scripts which hook into the build process.

**Comment by pornel** [comment]
Related discussion: #545
