### ISSUE TITLE
cargo does not show the build script output when build fails due during linking

### ISSUE THREAD

**Issue by briansmith** [rust-lang/cargo#1899]
When the build fails because linking failed then the build script's output isn't shown like it is when the build script fails.

Based on the conversation in #1106, the build script output is always supposed to be shown when the build fails. This is especially important when one is debugging a remote build (Travis, AppVeyor, etc.) where it is hard to retrieve the output file.

**Comment by briansmith** [comment]
By the way, the platform I tested this on is Windows using Rust Nightly. I don't know if it is a problem on other platforms.

**Comment by alexcrichton** [comment]
I don't think this something that Cargo should necessarily do as it seems pretty hairy:

* First, Cargo would have to parse the output of the compiler to determine whether a link error happened or not.
* If this happened, then Cargo needs to go back in time and print out all the build script outputs that were transitive dependencies (many of which probably aren't relevant)
* There's probably lots more build scripts than one may expect which need to be dealt with, and wading through the output can be quite confusing.

Overall I think it'd make more sense to just have an option to not suppress the output of the build script, e.g. #1106, so I'm going to close in favor of that. I definitely sympathize with the motivation here though (debugging appveyor/travis), but adding a flag (like `--verbose`) for a temporary build should be easy enough to add and see what's going on.

**Comment by briansmith** [comment]
I agree that #1106 makes sense. I filed this because people objected to implementing #1106.
