### ISSUE TITLE
GitHub release 0.4.0 tarball doesn't include rust-installer

### ISSUE THREAD

**Issue by pharaujo** [rust-lang/cargo#1901]
```bash
$ curl -sLO https://github.com/rust-lang/cargo/archive/0.4.0.tar.gz
$ tar tzf 0.4.0.tar.gz | grep rust-installer
cargo-0.4.0/src/rust-installer/
```

This then impacts running `make install` from the release tarball:
```
$ make install
(...)
sh: src/rust-installer/gen-installer.sh: No such file or directory
make: *** [target/x86_64-apple-darwin/debug/dist/cargo-0.4.0-x86_64-apple-darwin.tar.gz] Error 127
```

**Comment by alexcrichton** [comment]
Unfortunately it looks like GitHub just doesn't include submodules in the downloaded tarballs, so there's not a whole lot we can do about this. We currently don't have source releases for Cargo like we do for Rust itself, but cloning via git and going to the tag should work just fine!

**Comment by alexcrichton** [comment]
cc @brson

**Comment by brson** [comment]
Same problem as with Rust. We should probably disable those automated tarballs if we can since they are useless and misleading.

**Comment by brson** [comment]
I don't see any options to turn them off.

**Comment by brson** [comment]
Might also want to make source releases of Cargo ala Rust. cc @edunham
