### ISSUE TITLE
cargo test: Failure to run all tests if one of them fails

### ISSUE THREAD

**Issue by nbigaouette** [rust-lang/cargo#1904]
Running "cargo test" seems to exit prematurely when some tests fail.

I am following the rust 1.2 book, more specifically section [4.3 - Testing](https://doc.rust-lang.org/stable/book/testing.html).

It seems there is three kinds of tests: unit, integration and doc. Unit tests go directly in the source file, either as specific functions or functions inside a "tests" module. Integration tests have their own files in the tests/ directory and documentation tests are code appearing in modules or functions documentation blocks.

After implementing all three types of tests for the "adder" tutorial example from the docs, I added a couple more tests to see what a test failure would look like.

I then realized that "cargo test" will run all test from the unit section, and only continue to the integration if all tests pass. Same thing to go from integration to doc tests.

My "adder" tutorial code is here: https://github.com/nbigaouette/adder

Commit 846d259 contains simple unit and integration tests, all passing. The output is:

    $ git checkout 846d259
    $ cargo test
       Compiling adder v0.1.0 (file:///Users/nicolas/Documents/perso/codes/rust/adder.git)
         Running target/debug/adder-cd88aa840737f8b6

    running 1 test
    test tests::it_works ... ok

    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

         Running target/debug/lib-1d9abbd2769b2cbf

    running 4 tests
    test it_works_new ... ok
    test should_panic ... ok
    test should_assert_indirectly ... ok
    test should_panic_assert_eq ... ok

    test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured

       Doc-tests adder

    running 0 tests

The next commit (203e1d6) forces the unit test to fail. Running cargo test will then skip the integration and doc tests:

    $ git checkout 203e1d6
    $ cargo test
       Compiling adder v0.1.0 (file:///Users/nicolas/Documents/perso/codes/rust/adder.git)
         Running target/debug/adder-cd88aa840737f8b6

    running 1 test
    test tests::it_works ... FAILED

    failures:

    ---- tests::it_works stdout ----
    	thread 'tests::it_works' panicked at 'assertion failed: `(left == right)` (left: `3`, right: `4`)', src/lib.rs:18

    failures:
        tests::it_works

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

    thread '<main>' panicked at 'Some tests failed', ../src/libtest/lib.rs:255
    test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

Shouldn't all tests be always run, whatever their state?

@steveklabnik mentioned on IRC:

    so, it looks like what happens is, it stops executing after the first batch of tests failes, ie, it does run the unit tetss, and then the integration, and then the docs. it runs all of them within that section, but doesnt' bother to continue once one of the sections fails

    which is one reaosnable behavior, but i thought it always ran all three, no matter what. i'd say open a cargo issue and see what @alexcrichton has to say

**Comment by alexcrichton** [comment]
I've personally always wanted a "fail fast" situation where tests stop running as soon as they start failing. That being said I'd be totally fine with a `--no-fail-fast` flag to `cargo test` which just keeps running tests but remembers if they failed or not.

**Comment by nbigaouette** [comment]
I totally agree that a fail fast option is required. It would be extremely frustrating to run _all_ tests of a large project when developing a specific feature, especially during TDD. Even when specifying exactly which tests to run.

I do think the information reported right now is misleading though. Since cargo stops after a failed test, it is not aware of the other tests that it did not tried to run. So in the example above, there is a total of 5 tests, but in the second example there is only one. When I saw this I thought it was a problem with my code. This might be considered another bug though; account for all tests, even if failing fast, and report any skipped tests as such. That could be an interesting addition to cargo.

My ideal situation would be: `cargo test` defaulting to `--no-fail-fast`, with `--fail-fast / -f` available. This is what [Python](https://docs.python.org/3/library/unittest.html#cmdoption-unittest-f) is doing.

What do you think?

**Comment by alexcrichton** [comment]
> When I saw this I thought it was a problem with my code.

What problem are you referring to here? The counts of tests that are run?

---

I'd personally not want to default to no-fail-fast as it's what I've always wanted (failing fast), but it's also somewhat backwards incompatible with what Cargo does today.

**Comment by alexcrichton** [comment]
Flag added in #1949
