### ISSUE TITLE
Let user specify used compiler plugins in Cargo.toml

### ISSUE THREAD

**Issue by Ticki** [rust-lang/cargo#1905]
To use a compiler plugin, you have to write

```
#![feature(plugin)]
#![plugin(...)]
```

in the top of every file.

A work around is to write: `cargo rustc -- -L ... -Z extra-plugins=...`, but in the long run, this is annoying. I suggest, instead making it possible to declare used plugins in Cargo.toml. This will make Cargo more flexible.

Note: The rust compiler plugin API is highly unstable at this point, so that's a possible caveat.

**Comment by Ticki** [comment]
Related (duplicate?): https://github.com/rust-lang/cargo/issues/1579

**Comment by alexcrichton** [comment]
Thanks for the report! For now, however, Cargo doesn't expose any unstable functionality of the compiler in a first-class manner, so this would require stabilizing plugins in the main distribution (or moving the `-Z` flag to a not-unstable flag). As a result I'm going to close this until that happens (as there's not much actionable here)
