### ISSUE TITLE
intermittent "an unknown error occurred"

### ISSUE THREAD

**Issue by sourcefrog** [rust-lang/cargo#1913]
On OS X 10.10.4, with 

    cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-09)
    rustc 1.2.0 (082e47636 2015-08-03)

I get a few times a day:

```
% cargo test
   Compiling conserve v0.2.0 (file:///Users/mbp/Code/conserve-rust)
Build failed, waiting for other jobs to finish...
An unknown error occurred

To learn more, run the command again with --verbose.
```

Unfortunately the error goes away when I re-run with or without `--verbose`. I guess I should just use it every time until I get more info.

**Comment by alexcrichton** [comment]
Do you happen to have Cargo running in the background as well? Currently concurrent invocations of Cargo will generally result in badness. Otherwise yeah unfortunately this isn't very actionable without a better backtrace of what happened.

**Comment by sourcefrog** [comment]
Not intentionally but it's possible Atom was running it in the background. Could we add a lockfile or something to make this less confusing?

**Comment by alexcrichton** [comment]
It's largely just a hunch of mine, you're more likely to see compile errors from concurrent Cargo invocations than Cargo errors itself, but that's tracked by #354 as well. Just want to confirm it's a dupe before closing this one

**Comment by sourcefrog** [comment]
I'll turn that off and see if I can reproduce this.

**Comment by achanda** [comment]
@alexcrichton why didn't we merge https://github.com/alexcrichton/cargo/commit/dbbc6962e8c109be2afb25ffdbc682e3d98ebdc8 ?

**Comment by alexcrichton** [comment]
It was an experiment that didn't end up panning out on all platforms for various reasons if I remember correctly, but I unfortunately don't precisely remember why any more.

**Comment by sourcefrog** [comment]
Semaphores won't work over NFS or other network filesystems. If you don't care about NFS, most of the objections in http://0pointer.de/blog/projects/locking.html go away and you can use `flock` on unix.

I think actually the least worst option is probably a file existence lock holding the running cargo's pid.

**Comment by sourcefrog** [comment]
I think this is a dupe and it looks like Byron has a patch well underway, so great.
