### ISSUE TITLE
`cargo install` command

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/cargo#1917]
It would be cool if cargo had a `cargo install` command similar to e.g. `npm install --save`. That command would then look in the index for the most recent version of the crate, install it, and add the dependency to the `Cargo.toml` file.

**Comment by Turbo87** [comment]
it seems like https://github.com/killercup/cargo-edit and https://github.com/withoutboats/cargo-add implement something similar to my suggestion, however it would be awesome if that was part of `cargo` itself instead of having to install it as a plugin.

**Comment by huonw** [comment]
Dupe of #4, thanks for filing!

**Comment by Turbo87** [comment]
sorry, only searched for "install" before creating this issue ;)

**Comment by brandonros** [comment]
How is this not done yet?...

**Comment by cup** [comment]
https://github.com/rust-lang/cargo/issues/1917
https://github.com/rust-lang/cargo/issues/2179
https://github.com/rust-lang/cargo/issues/4
https://github.com/rust-lang/cargo/issues/5586
https://github.com/rust-lang/cargo/issues/6457
https://github.com/rust-lang/cargo/issues/6488
https://github.com/rust-lang/cargo/issues/651
https://github.com/rust-lang/cargo/pull/5611
