### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/cargo#1919]
I was wondering what changes got introduced from v0.3 to v0.4 of cargo and noticed that there doesn't seem to be a changelog anywhere. I think it would be a good idea to have a high level `CHANGELOG.md` in the root of the project for this purpose. The alternative is going through the commits one by one, but I don't think anyone will ever do that.

**Comment by carols10cents** [comment]
It looks like as of rust 1.6.0, [rust's RELEASES.md is including a changelog section for cargo](https://github.com/rust-lang/rust/blob/master/RELEASES.md) (and there are other cargo-related entries throughout, but it has its own section now.

I wouldn't have thought to look there, though, if I wasn't looking for how the rust team manages changelogs in general, so perhaps a note in cargo's README or a CHANGELOG.md or RELEASES.md that points to rust's RELEASES.md is in order?

**Comment by alexcrichton** [comment]
Yeah we're trying to be more vigilant about making sure Cargo release notes make their way into the official release notes, and a pointer in the README would definitely be welcome! I'd also be fine leaving this issue open as in theory the Cargo release notes could be more detailed and could outline things like bugs fixed as opposed to just features added.

**Comment by Turbo87** [comment]
marking this as resolved by https://github.com/rust-lang/cargo/pull/2382
