### ISSUE TITLE
Consider adding a `cargo build-examples`-esque command

### ISSUE THREAD

**Issue by erickt** [rust-lang/cargo#192]
Eventually we're going to have some large rust projects that contain both examples and a test suite that could run for a significant period of time. In this situation, an end user might want to play around with an example without having to sit through running the entire test suite. For this situation, I think it would be especially helpful to have a `cargo build-examples`-esque command that an end user could use to build just the examples.

As an alternative, @o11c mentioned that a project could use:

```
[[bin]]
name = "foo"
test = false
```

But the downside with this direction is that if end up adding a `cargo install`, I wouldn't expect my `[[example]]`s being installed, but I would my `[[bin]]`s.

**Comment by rofrol** [comment]
What if I want to just cross-compile build them?

Right now I use this command:

`for i in examples/*; do cargo build --target=x86_64-pc-windows-gnu --verbose --example $(basename $i .rs); done`

**Comment by cramertj** [comment]
There's still no way to just "build all examples" yet, is there?

**Comment by alexcrichton** [comment]
@cramertj unfortunately no, not yet.
