### ISSUE TITLE
Allow user to override the index's config.json from .cargo/config

### ISSUE THREAD

**Issue by gmjosack** [rust-lang/cargo#1923]
Currently the only way to change the place that cargo downloads packages from is to run your own index. When you're trying to run a simple mirror of the existing crates.io index for an internal network this is complicated as you have to maintain a fork that constantly pulls from upstream and will have merge conflicts if/when the `config.json` is modified.

I'd love to have the ability to specify `dl` or `api` locally in the `.cargo/config` that would override the `config.json` of the index.

I'd be happy to do that actual work to cargo here if this is agreed to be valuable.

Context: https://internals.rust-lang.org/t/production-user-research-summary/2530/11?u=gmjosack

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this may be situation-solving what's happening today at a bit too fine grained a level. I certainly agree that running your own mirror is an important part of Cargo's story, and this issue basically just plays into that (e.g. making it easy to set up your own mirror). 

As a result I'm going to close this in favor of https://github.com/rust-lang/crates.io/issues/67 which should serve for solving this as well.
