### ISSUE TITLE
Running Cargo purely as a build tool

### ISSUE THREAD

**Issue by dastbe** [rust-lang/cargo#1926]
I'm trying to integrate Cargo into my company's internal build system. We already do dependency management via this system, and vendor packages by importing them individually and modeling their dependencies via our own manifest system. This has worked for a variety of languages with wrapper scripts to configure their build tool, but cargo's dependence on a particular registry-as-git-repo is making 

Vendoring all of a packages dependencies in a package defeats the purpose of our internal build system, and leads to repo bloat. We could in theory build a fake registry per build, but that feels like overkill for this problem. We could require Cargo.toml's be rewritten so they define a conventional path (or rewrite them at the build stage to do that), but that's a stopgap measure and likely a brittle one. We also noticed that doing path overrides doesn't take version into account, and while we'd be modeling version dependencies in our dependency manager that doesn't mean we want to stop Cargo from doing it as well.

There've also been several issues from people wanting an offline mode for other reasons, so it's not like its just us. Is there any way/any plan to decouple the dependency resolution stage of cargo from build stage?

**Comment by alexcrichton** [comment]
I think the best solution here would indeed be to rewrite Cargo.toml files to use `path` dependencies instead of registry dependencies. If you're already vendoring everything then you've got it all stored locally for this, and if there are no dependencies on the remote registry then Cargo won't attempt to talk to it.

**Comment by valenting** [comment]
I think you can now do this using a repo-local .cargo/config file to override the paths to each dependency [1], and [http] timeout = 0

[1] http://doc.crates.io/guide.html#overriding-dependencies
[2] http://doc.crates.io/config.html#configuration-keys

**Comment by valenting** [comment]
So, at the moment, if all crates are specified in Cargo.toml via a path, cargo doesn't attempt to fetch the registry.
However, if we override the paths through the use of a .cargo/config, it still attempts to fetch the registry, even if all of the dependencies are satisfied.
@alexcrichton Would it be possible to check the config paths before we decide if we need to go online?

**Comment by alexcrichton** [comment]
@valenting unfortunately path overrides are implemented in such a way that working like that is impossible. This is what `[replace]` is intended for, however, to fix.

**Comment by valenting** [comment]
@alexcrichton I fiddled with the cargo source code a bit, and I managed to make this work.
This way, the paths are overrided before we actually update the registry, so it doesn't attempt to go online. I don't know the code well enough to know if is correct to do this, but it fixes my use case.

```
diff --git a/src/cargo/ops/cargo_compile.rs b/src/cargo/ops/cargo_compile.rs
index 12356ac..8117754 100644
--- a/src/cargo/ops/cargo_compile.rs
+++ b/src/cargo/ops/cargo_compile.rs
@@ -111,6 +111,8 @@ pub fn resolve_dependencies<'a>(root_package: &Package,
         registry.add_preloaded(root_package.package_id().source_id(), source);
     }
 
+    try!(add_overrides(&mut registry, root_package.root(), config));
+
     // First, resolve the root_package's *listed* dependencies, as well as
     // downloading and updating all remotes and such.
     let resolve = try!(ops::resolve_pkg(&mut registry, root_package, config));
@@ -120,8 +122,6 @@ pub fn resolve_dependencies<'a>(root_package: &Package,
     // overrides, etc.
     let _p = profile::start("resolving w/ overrides...");
 
-    try!(add_overrides(&mut registry, root_package.root(), config));
-
     let method = Method::Required{
         dev_deps: true, // TODO: remove this option?
         features: &features,
```

**Comment by valenting** [comment]
Actually, this doesn't seem to be related to my change :) It works if I build cargo master, but not with the latest rust-nightly. 
Did something land in the past 1-2 days that might have fixed it?

**Comment by alexcrichton** [comment]
@valenting unfortunately that actually changes the `Cargo.lock` that's emitted, whereas path overrides are intended to *not* change the `Cargo.lock`.

I'm not personally aware of anything that changed behavior recently, but path overrides do have some level of nondeterminism unfortunately which may not play nicely with everything else.

**Comment by valenting** [comment]
Yeah, my bad, I wasn't installing the binary properly.

Indeed, this does seem to be changing Cargo.lock.
Any idea on how and when the `[replace]` way is supposed to work? (it doesn't seem to work at the moment).

**Comment by alexcrichton** [comment]
Ah `[replace]` may be beta+ for now (I forget if it's landed in stable), but it basically does what you did in the sense of it changes the lock file.

**Comment by carols10cents** [comment]
I believe the main request in this issue is addressed by https://github.com/alexcrichton/cargo-vendor and https://github.com/alexcrichton/cargo-local-registry or by the [grander build system integration plan](https://github.com/rust-lang/rfcs/pull/2136), so I'm going to close this in favor of those.
