### ISSUE TITLE
Cargo's OUT_DIR variable sometimes doesn't seem to depend on target triple

### ISSUE THREAD

**Issue by dlecan** [rust-lang/cargo#1944]
This is a problem when I try to cross-compile a project with generated code (x86_64 + arm).
As OUT_DIR seems to be always linked to default out directory (`<my_project>/target/debug/build/.../out`), generated code can't found with arm target.

My configuration:
- Ubuntu 14.04 x86_64
- Rustc 1.2.0 compiled for `arm-unknown-linux-gnueabihf` and `x86_64-unknown-linux-gnu`
- Cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-10)

### Sample

`Cargo.toml`:

```toml
[package]
...
build = "build.rs"
```
`build.rs` file logs `OUT_DIR` env value during build script step.
`main.rs` file logs `OUT_DIR` during build step (as it would be used in `include!(concat!(env!("OUT_DIR"), "/codegen.rs"));`).

#### Empty target
`cargo build` =>
build.rs: `OUT_DIR = /.../test/target/debug/build/test-92a33f41a3e62e1a/out`
main.rs: `OUT_DIR = /.../test/target/debug/build/test-92a33f41a3e62e1a/out`

#### Target `arm-unknown-linux-gnueabihf`
`cargo build --target=arm-unknown-linux-gnueabihf` =>
build.rs: `OUT_DIR = /.../test/target/debug/build/test-92a33f41a3e62e1a/out`
main.rs: `OUT_DIR = /.../test/target/arm-unknown-linux-gnueabihf/debug/build/test-92a33f41a3e62e1a/out`

AS `OUT_DIR` values are not equal, generated code can't be found when compiling code with it for arm target.

What's wrong ? Cargo OUT_DIR in build scripts or how the generated code is included in my code ? (`include!(concat!(env!("OUT_DIR"), "/codegen.rs"));`)

**Comment by alexcrichton** [comment]
How are you determining what `OUT_DIR` is set for each of these scripts? Testing locally everything is working as-expected for me, so perhaps there are just some stale results?

**Comment by dlecan** [comment]
In `build.rs`, I dump "OUT_DIR" into a local file to read its value.
In `main.rs`, it's just `println!(env!("OUT_DIR"));`

I ran into this issue when using [Valico](https://github.com/rustless/valico), which uses a build script which generates some code.
I can't cross compile it for ARM.

Valico `build.rs`: https://github.com/rustless/valico/blob/master/build.rs
Valico's file which does include: https://github.com/rustless/valico/blob/master/src/json_schema/schema.rs#L81

### `cargo build`
=> Success

```
$ tree target/
target/
└── debug
    ├── build
    │   ├── advapi32-sys-cfef7a1f30f1e5f6
    │   │   ├── ...
    │   └── valico-f0bc094a311d8173
    │       ├── build-script-build
    │       ├── out
    │       │   └── codegen.rs
    │       └── output
    ├── deps
    │   ├──...
    ├── examples
    ├── libvalico.rlib
    └── native
```

### `cargo build --target=arm-unknown-linux-gnueabihf`
=> Fail with following error:
```
failed to run custom build command for `valico v0.8.0 (file:///.../valico)`
Process didn't exit successfully: `/.../valico/target/debug/build/valico-f0bc094a311d8173/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:731
```

```
$ tree target/
target/
├── arm-unknown-linux-gnueabihf
│   └── debug
│       ├── build
│       │   ├── advapi32-sys-cfef7a1f30f1e5f6
│       │   │   ├── out
│       │   │   └── output
│       │   └── valico-f0bc094a311d8173
│       │       └── out
│       ├── deps
│       │   ├── ...
│       ├── examples
│       └── native
└── debug
    ├── build
    │   ├── advapi32-sys-cfef7a1f30f1e5f6
    │   │   ├── ...
    │   └── valico-f0bc094a311d8173
    │       └── build-script-build
    ├── deps
    │   ├──...
    ├── examples
    └── native
```

If I create manually `/.../valico/target/debug/build/valico-f0bc094a311d8173/out`, build still fails but goes farther:

```
$ cargo clean \
  && mkdir -p ./target/debug/build/valico-f0bc094a311d8173/out \
  && cargo build --target=arm-unknown-linux-gnueabihf
...
src/json_schema/schema.rs:81:1: 81:51 error: couldn't read "/.../valico/target/arm-unknown-linux-gnueabihf/debug/build/valico-f0bc094a311d8173/out/codegen.rs": No such file or directory (os error 2)
src/json_schema/schema.rs:81 include!(concat!(env!("OUT_DIR"), "/codegen.rs"));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not compile `valico`.
```
It goes farther because OUT_DIR exists so code generation can run, but out_dir doesn't depend on target triple.
Then compilation fails because of an include in directory which depends on target triple but there is no file to include here.
```
$ tree target/
target/
├── arm-unknown-linux-gnueabihf
│   └── debug
│       ├── build
│       │   ├── advapi32-sys-cfef7a1f30f1e5f6
│       │   │   ├── out
│       │   │   └── output
│       │   └── valico-f0bc094a311d8173
│       │       ├── out
│       │       └── output
│       ├── deps
│       │   ├── ...
│       ├── examples
│       └── native
└── debug
    ├── build
    │   ├── advapi32-sys-cfef7a1f30f1e5f6
    │   │   ├── build-script-build
    │   │   ├── out
    │   │   └── output
    │   └── valico-f0bc094a311d8173
    │       ├── build-script-build
    │       └── out
    │           └── codegen.rs
    ├── deps
    │   ├── ...
    ├── examples
    └── native
```

**Comment by alexcrichton** [comment]
Aha! I believe I see the problem here now, the build script is using `env!("OUT_DIR")` instead of `env::var("OUT_DIR")`, so it's using the output directory at *compile time* instead of at runtime. Because the build script is itself compiled for the host architecture the `OUT_DIR` at compile time doesn't have a triple in it. If you instead switch that up to using the runtime value of `OUT_DIR` it should work just fine!

**Comment by dlecan** [comment]
Ah, thank you for your help.
