### ISSUE TITLE
What do we think about integrating rustfmt into cargo

### ISSUE THREAD

**Issue by posix4e** [rust-lang/cargo#1946]
I'd love to be able to run cargo format

**Comment by alexcrichton** [comment]
I'd also love to see this done! For now, however, I don't think that we'll want official support in Cargo until `rustfmt` itself is a little more mature. There can certainly be a `cargo fmt` subcommand that is developed next to rustfmt. As a result I'm gonna close this as it's basically "let's wait for rustfmt", and we may not necessarily need an issue for that. I'll certainly closely watch rustfmt though!
