### ISSUE TITLE
Build with debug logging disabled in release builds (by default)

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/cargo#1947]
The `log_level` configuration variable is used by macros in the `log` crate to enable/disable logging statements at compile time. Because this feature controls a performance versus debugging trade-off, it would be useful to control it per-profile, like Cargo already does for the `debug_assertions` cfg variable.

I suggest adding a `log_level` key to the `[profile.*]` sections, with a default value of `info` for the `release` and `bench` profiles.

Note: Unlike `debug_assertions`, this variable is not used by the compiler standard library, but it's used by the Rust team's own `log` library, and can potentially be used by other logging libraries, so I think it's worth having sensible default values built in to Cargo.  But an alternate solution is to add a way to set arbitrary cfg variables in the profile sections, and allow each application to choose whether to set log_level.

**Comment by mbrubeck** [comment]
Should this be an RFC?

**Comment by pcwalton** [comment]
+1

**Comment by alexcrichton** [comment]
I [commented on the associated PR](https://github.com/rust-lang/cargo/pull/1948#issuecomment-135279556) but for now I'm going to close this in favor of "needs an RFC".

**Comment by mbrubeck** [comment]
Filed rust-lang-nursery/log#58 for an alternate solution.
