### ISSUE TITLE
Possibility to modify rendered doc

### ISSUE THREAD

**Issue by b52** [rust-lang/cargo#1951]
I would like to include [KaTeX](https://khan.github.io/KaTeX/) in my rendered docs to write some beautiful math.

**Problem 1:** `rustdoc` doesn't support some form of math rendering, therefore I have to implement it manually on the client side using KaTeX (or MathJax). This requires the inclusion of some HTML tags in the rendered documentation.

**Problem 2:** I would have to use `rustdoc`'s `--html-in-header`, `--html-before-content`, and/or `--html-after-content` parameters. However, these are not configurable using `cargo`, which means I would have to write some scripts or use other make tools. But I would like to refrain from that and use a cargo only solution.

The point is that I would like to use `cargo` and only `cargo`.

What are your thoughts on that?

**Comment by alexcrichton** [comment]
Yeah I think the best option here would be something like #331 where you can specify these sorts of flags in your manifest which are then passed down to rustdoc.

You can work around this for now by setting the RUSTDOC environment variable and then pointing it at a shell script which adds the arguments, but it's definitely a hack :(.

Regardless though I'm gonna close this in favor of #331 as that's probably the route we'd take!
