### ISSUE TITLE
cargo new should only gitignore/hgignore "target" at root folder

### ISSUE THREAD

**Issue by AndiDog** [rust-lang/cargo#1952]
Current behavior ignores all files/folders named "target". Let's say you want to write military software and create a module "target" at "src/thearmy/rocket/science/target/mod.rs". You can't. Morally this might be fine, but please change this current behavior

```rust
fn mk(config: &Config, path: &Path, name: &str,
      opts: &NewOptions) -> CargoResult<()> {
    let cfg = try!(global_config(config));
    let mut ignore = "/target\n".to_string();
    let in_existing_vcs_repo = existing_vcs_repo(path.parent().unwrap());
    if !opts.bin {
        ignore.push_str("Cargo.lock\n");
    }
```

to output

*.gitignore:*
```
/target
/Cargo.lock
```

*.hgignore:*
```
^target
^Cargo.lock
```

**Comment by alexcrichton** [comment]
Thanks for the report! This has [come up before](https://github.com/rust-lang/cargo/pull/1488), and the current behavior is intentional. Note though that this is just a set of defaults, and you're free to modify the gitignore yourself!
