### ISSUE TITLE
The crates-io crate should be handled better

### ISSUE THREAD

**Issue by achanda** [rust-lang/cargo#1954]
I was trying to use that crate in another and I got a build error on the `-` in it's name. Here are the things that should change:
1. It should be in a separate repository and should be published separately
2. It should have a generic name that does not indicate specific association to http://crates.io Sooner or later, we will have standalone crates hosting, there should be a generic API to access those.
3. The name should not have a `-`

I will be happy to get this done if we think this is a valid problem.

**Comment by alexcrichton** [comment]
Hm, could you elaborate on these points? My thoughts on each of them (respectively) are:

1. Is there a reason for this? Currently the main consumer is Cargo, and there's no particular reason it can't expand in-tree here.
2. Perhaps, I guess a better name would be connected to "registry"
3. Why?

**Comment by achanda** [comment]
@alexcrichton Sorry for being late on this.
1. I assumed that once crates.io can be deployed in a private network, there will be a need for a rust API to access it. But, admittedly, this is not necessary right now.
2. Sounds fine to me.
3. That was my mistake, a typo. This one can be ignored.

**Comment by carols10cents** [comment]
It looks like the only remaining request here is:

> 2. It should have a generic name that does not indicate specific association to http://crates.io 

I don't think this is necessary. A private network deploy of crates.io will still be running crates.io's *code*, so I think the name is fine. Please reopen if I've misunderstood and there's still a need for anything mentioned in this issue!
