### ISSUE TITLE
locate-project usage message is wrong and option name non descriptive

### ISSUE THREAD

**Issue by diaphore** [rust-lang/cargo#1958]
The [usage message](https://github.com/rust-lang/cargo/blob/a6dad62221350701340081cdcaea6a663b6a552e/src/bin/locate_project.rs#L14) for `locate-project` mentions "benchmarks" for no apparent reason (seems like the remnant of a cut/paste).

```
Options:
    --manifest-path PATH    Path to the manifest to build benchmarks for
```

Similarly, the `--manifest-path` option is ill-named : the path to the manifest is precisely what we're looking for.

On a side note, `read-manifest` ought to `locate-project` automatically when it's not provided a `--manifest-path`. I could hack at it if anyone is interested.

**Comment by alexcrichton** [comment]
The `read-manifest` command is losing the requirement of `--manifest-path` in https://github.com/rust-lang/cargo/pull/1955, but feel free to submit a PR to update the docs of this!

**Comment by diaphore** [comment]
My search-fu is lacking ... PR looks good though, thanks.

**Comment by carols10cents** [comment]
LOL! I've seen this happen so many times, an issue lays around for *months* and then two people notice it like the same day :) I wasn't sure what the argument to `locate-project` should be called instead of `--manifest-path` but I agree that it doesn't make sense... `--search-path` maybe?

**Comment by diaphore** [comment]
@carols10cents Wouldn't it make sense to just drop the option altogether and make it a normal argument ? `cargo locate-project ~/in/some/path`

Maybe rename `locate-project` to `locate-manifest` too for consistency ... but that might be too disruptive.

**Comment by alexcrichton** [comment]
I think for now we'll just leave the name as-is, but I'd be fine adding another option for something like `--search-path` or something similar.

In the meantime I'm labeling this as a docs bug as the help page should just be update dnow.

**Comment by carols10cents** [comment]
> In the meantime I'm labeling this as a docs bug as the help page should just be updated now.

This looks fixed, closing this!

```
$ cargo locate-project --help
Print a JSON representation of a Cargo.toml file's location

Usage:
    cargo locate-project [options]

Options:
    --manifest-path PATH    Path to the manifest to locate
    -h, --help              Print this message
```
