### ISSUE TITLE
Windows: Cargo should put files in ~/appdata, not directly in ~/

### ISSUE THREAD

**Issue by briansmith** [rust-lang/cargo#1976]
In particular, everything should go in ~/appdata/locallow or ~/appdata/local,since ~/.cargo is just a cache, AFAICT.

This is `FOLDERID_LocalAppData` for `SHGetKnownFolderPath`, `CSIDL_LOCAL_APPDATA` for `SHGetFolderPath`, and `%LOCALAPPDATA%` in the environment.

See also #1734

**Comment by alexcrichton** [comment]
cc #1734, a similar ish issue for linux

**Comment by briansmith** [comment]
A practical reason for doing this is to avoid having automated backup/sync software backup/sync the .cargo directory.

**Comment by DanielKeep** [comment]
[`cargo-script` already does this, using this code](https://github.com/DanielKeep/cargo-script/blob/master/src/platform.rs#L118-L130).  Feel free to steal :)

Disclaimer on the function:

> This is *not* chosen to match the location where Cargo places its cache data, because Cargo is *wrong*.  This is at least *less wrong*.

**Comment by retep998** [comment]
There has still been no movement on this front. The [RFC](https://github.com/rust-lang/rfcs/pull/1615) is still open and the relevant teams still are unsure of themselves. Several implementations have popped up over time, and they've all been closed for various reasons.

**Comment by epage** [comment]
FYI I've generalized #1734 to cover all OS as we need to address them all together.  Closing this in favor of that issue.
