### ISSUE TITLE
Cfgs from build script not passed to rustdoc

### ISSUE THREAD

**Issue by gkoz** [rust-lang/cargo#1980]
The `cfg` directives returned by the build script via the `cargo:rustc-cfg=foo` convention are not passed to `rustdoc` when invoking `cargo doc`.

`rustdoc` seems to accept them just fine i.e. invoking it manually with `--cfg foo` produces the expected results.

**Comment by alexcrichton** [comment]
I think this is a dupe of #1277, but thanks for the report!

**Comment by gkoz** [comment]
Not really. #1277 talks about features. It appears to have been fixed back then.

**Comment by alexcrichton** [comment]
Hm, good point. I could of sworn we had a few dupes for this issue, but I guess this one will now become the "one true issue"!
