### ISSUE TITLE
allow binary-only dependencies

### ISSUE THREAD

**Issue by vks** [rust-lang/cargo#1987]
Binaries usually have a lot of dependencies libraries don't care for. If you want to have different dependencies, you currently cannot build the library and the binary using the same `Cargo.toml`, resulting in needless duplication of the `Cargo.toml`.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/1982, however, so closing in favor of that.
