### ISSUE TITLE
`cargo new .`

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/cargo#1990]
Small feature, but sometimes I have a directory with some random stuff in it, and I want to turn it into a crate. This typically happens when I'm setting up a bunch of projects at once and copying in documentation or support files. I'd like to be able to type `cargo new .` and have it use the current directory as the crate.

**Comment by steveklabnik** [comment]
We have a ticket open for this somewhere.... :+1: from me for sure

**Comment by nixpulvis** [comment]
Ah sorry, didn't see it in a quick search.

**Comment by alexcrichton** [comment]
Ah yeah this is covered by https://github.com/rust-lang/cargo/issues/21, but thanks for the report!
