### ISSUE TITLE
`cargo doc` search on local machine does not work on Google Chrome on Windows

### ISSUE THREAD

**Issue by trolleyman** [rust-lang/cargo#2001]
When documentation is generated for a local project everything works fine except the searching. I looked in the Chrome Console and saw that main.js was generating an error.

![image](https://cloud.githubusercontent.com/assets/4435960/10117518/97a381ba-6451-11e5-8eb7-493b086ab8b9.png)

When I commented out the whole history block searching worked again. Does someone know how to fix this and maintain the history setting thing?

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like it may actually be a bug in rustdoc rather than Cargo, and rustdoc issues live at https://github.com/rust-lang/rust, could you open an issue over there instead? I think this may be fixed on nightly, however, so you may want to check there first!
