### ISSUE TITLE
`cargo doc` searching doesn't clear list of results when X is pressed

### ISSUE THREAD

**Issue by trolleyman** [rust-lang/cargo#2002]
When you search for something on the online docs (which I assume are generated using cargo doc) a list of results comes up. When you clear the search bar/press the X button it probably should clear the results to allow you to view the original page. Anyone know how to fix this?

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually more of a rustdoc issue than a Cargo one, so could you open a bug report over at https://github.com/rust-lang/rust instead? Thanks!
