### ISSUE TITLE
Duplicate dependency in manifest ignored

### ISSUE THREAD

**Issue by Virtlink** [rust-lang/cargo#2023]
If I have a `Cargo.toml` manifest with a duplicate dependency name, I get a parse error as expected:

```
[package]
name            = "foo"
version         = "1.0.0"

[dependencies]
bar             = { path = "../shim-bar" }
bar             = { path = "../linux-bar" }
```

> `cargo build`
> 
> ```
> failed to parse manifest at `/home/daniel/repos/test2/foo/Cargo.toml`
> 
> Caused by:
>   could not parse input as TOML
> Cargo.toml:7:1-7:4 duplicate key: `bar`
> ```

However, if I put the second `bar` dependency in a separate section, then it doesn't complain at all.

```
[package]
name            = "foo"
version         = "1.0.0"

[dependencies]
bar             = { path = "../shim-bar" }

[target.x86_64-unknown-linux-gnu.dependencies]
bar             = { path = "../linux-bar" }
```
> `cargo build --target=x86_64-unknown-linux-gnu`

From my tests I find that the second `bar` dependency is ignored.

I would expect either an error, or that the target-specific dependency overrides the general dependency (which would be really useful).

**Comment by alexcrichton** [comment]
The first error is actually imposed by the [TOML format](https://github.com/toml-lang/toml#user-content-table), and the second is likely something that Cargo should be generating an error on as well!
