### ISSUE TITLE
[feature request] well-known URLs for crate links

### ISSUE THREAD

**Issue by durka** [rust-lang/cargo#2024]
I often type out a crates.io link, e.g. crates.io/crates/libc, with the sole intention of scrolling down and clicking "Documentation". But what if I could type crates.io/crates/libc/docs or crates.io/docs/libc and it would automatically redirect to the crate's doc link? Similarly for the homepage and repository links. A 404 is fine if the crate hasn't provided a link.

Does this sound like a useful feature?

**Comment by alexcrichton** [comment]
I'd be down for this, seems pretty reasonable to me! (this may belong over at https://github.com/rust-lang/crates.io though instead of here)

**Comment by durka** [comment]
Oh, I didn't realize the repositories were separate. I'll move it over there.
