### ISSUE TITLE
`cargo run` passes arguments incorrectly

### ISSUE THREAD

**Issue by dhardy** [rust-lang/cargo#2027]
Code in `src/main.rs`:

    fn main() {
        println!("Arguments:");
        for arg in std::env::args() {
            println!("\t'{}'", arg);
        }
    }

Cargo's `run` command passing arguments:

    $ cargo run -- one two "three and four"
     Running `target/debug/argtest one two three and four`
    Arguments:
            'target/debug/argtest'
            'one'
            'two'
            'three'
            'and'
            'four'

Notice that it splits "three and four". This is what it *should* do:

    $ target/debug/argtest one two "three and four"
    Arguments:
            'target/debug/argtest'
            'one'
            'two'
            'three and four'

After reading some cargo code, I think the bug is in Docopt [but it is still exhibited by Cargo].

**Comment by dhardy** [comment]
I'm confused now: `std::env::args_os()` seems to do a different thing in Cargo to in a standalone test case. Has Rust changed recently?

In `cargo/src/bin/cargo.rs`:

    fn main() {
        println!("[main] env::args_os():");
        for ao in env::args_os() {
            println!("\t{:?}", ao);
        }
        env_logger::init().unwrap();
        execute_main_without_stdin(execute, true, USAGE)
    }

Output:

    $ cargo run -- arg1 "arg two"
    [main] env::args_os():
            "/home/install/cargo/bin/cargo"
            "run"
            "--"
            "arg1"
            "arg"
            "two"
    [snip]

In a stand-alone test project:


    use std::env;

    fn main() {
        println!("[main] env::args_os():");
        for ao in env::args_os() {
            println!("\t{:?}", ao);
        }
    }

Output:

    $ target/debug/argtest -- arg1 "arg two"
    [main] env::args_os():
            "target/debug/argtest"
            "--"
            "arg1"
            "arg two"

**Comment by alexcrichton** [comment]
What version of Rust and Cargo and using, and also what shell are you using? I'm unable to reproduce this locally, so something funny may be in play?

**Comment by dhardy** [comment]
Cargo: latest off the master branch with whichever Rust version the Python build script downloaded (something like 15th Aug).

Stand-alone test: Rust 1.3 release.

**Comment by alexcrichton** [comment]
Could you also clarify what shell you're using? (a paste of the exact output of `cargo -V` may also be useful)

This is what I'm seeing:

```
$ cat src/main.rs 
fn main() {
    println!("Arguments:");
    for arg in std::env::args() {
        println!("\t'{}'", arg);
    }
}
$ cargo run -- a b "c d"
     Running `target/debug/wut a b c\ d`
Arguments:
        'target/debug/wut'
        'a'
        'b'
        'c d'
$ rustc -vV
crustc 1.3.0 (9a92aaf19 2015-09-15)
binary: rustc
commit-hash: 9a92aaf19a64603b02b4130fe52958cc12488900
commit-date: 2015-09-15
host: x86_64-unknown-linux-gnu
release: 1.3.0
$ cargo -V
cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-02)
$ multirust run nightly cargo run -- a b "c d"
   Compiling wut v0.1.0 (file:///home/alex/code/wut)
     Running `target/debug/wut a b c\ d`
Arguments:
        'target/debug/wut'
        'a'
        'b'
        'c d'
$ multirust run nightly cargo -V              
cargo 0.6.0-nightly (7f21e73 2015-10-01)
```

**Comment by dhardy** [comment]
Cargo (source build):

    cargo 0.6.0 (61952eb 2015-10-04)

Cargo nightly does the same: `cargo 0.6.0-nightly (a7b2c92 2015-09-22)`.

As does Cargo from the 1.3.0 release: `cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-02)`.

Shell is bash: `GNU bash, version 4.3.42(1)-release (x86_64-redhat-linux-gnu)`.

Currently downloading the latest Rust nightly...

**Comment by dhardy** [comment]
I also tried installing the `dash` and `fish` shells, and get the same result (with Cargo 61952eb 2015-10-04).

**Comment by alexcrichton** [comment]
Is `cargo` overwritten in your path to something else perhaps? When you execute `cargo run` in the examples above it doesn't print `Running`, so it sounds like something in the environment may be in play?

**Comment by dhardy** [comment]
`cargo` is `cargo` but via a script and not in `/usr/local/bin`. This is a different computer but exhibits the same problem.

Moment while I reboot...

**Comment by alexcrichton** [comment]
Aha! I think the problem is in your script, if you change `$@` to `"$@"` it should fix the problem!

**Comment by dhardy** [comment]
Well spotted! Thanks.
