### ISSUE TITLE
Allow manifest with byte order mark (BOM)

### ISSUE THREAD

**Issue by andersforsgren** [rust-lang/cargo#2031]
A cargo .toml file with a byte order mark is a valid UTF-8 encoded file, and should be readable by cargo.

Current behavior (Windows):

    failed to parse manifest at `C:\Path\to\Cargo.toml`
    
    Caused by:
      could not parse input as TOML
    Cargo.toml:1:1 expected a key but found an empty string

The corresponding issue for the compiler (libsyntax) is https://github.com/rust-lang/rust/issues/12974

    cargo --version

    cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-03)

**Comment by andersforsgren** [comment]
Should this perhaps be handled at the parser level in the toml crate? (https://github.com/alexcrichton/toml-rs)

**Comment by alexcrichton** [comment]
Thanks for the PR @andersforsgren, I release a new version of toml-rs, would you like to send a PR to update the version Cargo is using?

**Comment by alexcrichton** [comment]
Ah looks like there's another reason (https://github.com/rust-lang/cargo/issues/2033) to update toml, so I'll just go ahead and do so, thanks again @andersforsgren!
