### ISSUE TITLE
execv: Argument list too long

### ISSUE THREAD

**Issue by arcnmx** [rust-lang/cargo#2054]
Let's say we have a crate with an external native dependency. Its build script outputs `cargo:rustc-flags=-L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out`. Now let's say we have 40 crates in one project with tons of interdependencies that all end up depending on this one common crate.

> rustc -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out -L native=/tmp/whatever/target/x86_64-unknown-linux-gnu/debug/build/stuffs-0ba7e3ceba953973/out

gcc: error trying to exec '/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/collect2': execv: Argument list too long

**Comment by alexcrichton** [comment]
Thanks for the report! This was a bug fixed recently in Cargo, however, so it should be fixed if you update to a more recent nightly.
