### ISSUE TITLE
Trouble building cargo: insists on download

### ISSUE THREAD

**Issue by hadmut** [rust-lang/cargo#2057]
Hi, 

I've compiled and installed Rust from the 1.3.0 source on my machine, so I have a stable rustc on /usr/local/bin/rustc. 

https://github.com/rust-lang/cargo states, rust would come with cargo by default, but actually it didn't. I therefore took a git checkout as described on the same web page, and proceeded as given on the web page. 

When doing the 

python -B src/etc/install-deps.py

step, it tried to download a huge file with precompiled binaries from the web. 

How can I avoid this? Why doesn't it just use the fresh and locally installed rustc? And why does it require a nightly build? How would I get that cargo that belongs to the 1.3.0 stable version of rust?

regards

**Comment by alexcrichton** [comment]
Thanks for the report! To use a local rustc, however, you can pass the `--local-rust-root` option which should allow you to use the local rustc to build Cargo.
