### ISSUE TITLE
https://doc.crates.io gives untrusted connection error

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#2059]
Presumably because it is deployed via github pages from this repo.

Error message:

> doc.crates.io uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, github.com, *.github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com 

cc @edunham

**Comment by alexcrichton** [comment]
Yeah unfortunately without going through our nginx proxy there's probably no way to handle this. Note that we currently also don't have a `doc.crates.io` certificate.

**Comment by carols10cents** [comment]
Closing as a duplicate of https://github.com/rust-lang/crates.io/issues/621, there's more info over there.
