### ISSUE TITLE
Possible (total) loss of crate ownership when revoking GitHub access rights.

### ISSUE THREAD

**Issue by sbstp** [rust-lang/cargo#2073]
I maintain a couple of crates and I almost lost the ownership of them. What I believe happened is that I revoked crates.io's priviledges in my Github settings by mistake. When I tried to login a few minutes ago, it created a new account, with new tokens and everything (I had to use `cargo login` again because I just re-installed my OS). There also are no crates listed in my dashboard. Anyway, I tried to publish with the new token and it failed. Luckily, I still had the token from my old account on another computer and I was able to publish using that one.

So my crates are kind of in a weird state now, because the crate's owner is a revoked account which I can still publish with, and the new account is not an owner of the crate (or at least can't publish to them).

If I try to add myself with using `cargo owner --add SBSTP` and the old token, I get an error saying that SBSTP is already an owner.

**Comment by alexcrichton** [comment]
Did your github login change in the meantime? In theory we should update that row even if our token is revoked...

**Comment by sbstp** [comment]
Oh yes! I also renamed from SBSTP to sbstp.

**Comment by alexcrichton** [comment]
Aha! In that case I'm gonna close this in favor of https://github.com/rust-lang/crates.io/issues/136 as I think it's covered by that.

If you need any help getting access to your previous crates, though, please just let me know!

**Comment by sbstp** [comment]
Should I keep using the old token?

**Comment by alexcrichton** [comment]
You probably want to use your new token, so I can just transfer all the old crates to your new user instead if you like?

**Comment by sbstp** [comment]
I managed to re-gain access. I'm there twice though, idk if this is a problem https://crates.io/crates/igd. Maybe just remove the old owner now? I have two crates, igd and loirc.

**Comment by alexcrichton** [comment]
Ah yeah if you just remove the old owner it should be fine, but if you run into more problems please just let me know!

**Comment by sbstp** [comment]
Everything is fixed now, thanks again.
