### ISSUE TITLE
Add user expectations to the crates.io guide

### ISSUE THREAD

**Issue by mdinger** [rust-lang/cargo#2074]
People who look at the crate should expect a few things consistently across crates and these should be documented:
- Auto-built documentation. This is commonly done via [travis-cargo](https://github.com/huonw/travis-cargo) and github pages
- Documentation should be linked from the readme
- Auto-built and tested via https://travis-ci.org or http://homu.io/ though homu is more strict
- http://shields.io/ for build status (if using travis) and version numbers. All others are optional I guess.
- A license should be chosen
  - maximal conformance with Rust is achieved via dual licensing with MIT & Apache

---

These mostly pertain to the github readme and come up frequently when new crates are released. Maybe this will get easier if/when rust starts self-hosting the documentation for all crates but in the meantime, this seems like a good idea.

I'd probably put it at the beginning of the 'Using crates.io' page so people see it before uploading a crate.

Maybe this list should be longer but nothing else really jumps out at me.

This is a clone of https://github.com/rust-lang/crates.io/issues/203 which was apparently the wrong location.

**Comment by GabrielMajeri** [comment]
Is this issue still applicable? If so, where would be the right place to document these best practices?

**Comment by weihanglo** [comment]
I think this is no longer relevant. We have some suggestions for crates.io publish [here](https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate). We also have docs.rs hosting all documentations. 

Closing now. If you have more ideas, please file a new issue. Thank you!
