### ISSUE TITLE
features cannot be modified when the main package is not being built

### ISSUE THREAD

**Issue by arcnmx** [rust-lang/cargo#2083]
`cargo build --features x -p y`

Is fairly useful functionality to have, but cargo does not allow this behaviour. It seems to be disabled simply because it's unsupported/unimplemented? Perhaps as a starting point the fingerprints could be checked to see that the features match what were used on the last non-p build.

**Comment by alexcrichton** [comment]
This'll actually be fixed by https://github.com/rust-lang/cargo/pull/2070
