### ISSUE TITLE
Cargo profile documentation is confusing (out of date)

### ISSUE THREAD

**Issue by briansmith** [rust-lang/cargo#2084]
According to http://doc.crates.io/manifest.html#the-profile-sections, there are these profiles:
- `[profile.dev]`
- `[profile.release]`
- `[profile.test]`
- `[profile.bench]`
- `[profile.doc]`

And according to http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-build-scripts, the `PROFILE` environment variable for build scripts is set to the "name of the profile currently being built".

So, I expect that `$PROFILE` will be one of { `dev`, `release`, `test`, `bench`, `doc` }. However, instead, $PROFILE is either `debug` or `release`.

Note that the implemented behavior is more sensible than the documented behavior. The documentation should be fixed to match the implemented behavior.

**Comment by bluetech** [comment]
> Note that the implemented behavior is more sensible than the documented behavior.

Not that it matters (the behavior cannot be changed now), but I wonder why you think so? Providing the actual profile name sounds strictly more useful (or arguably, should not be provided at all).
