### ISSUE TITLE
Occasional hangs at updating registry

### ISSUE THREAD

**Issue by matthewkmayer** [rust-lang/cargo#2090]
I'm seeing `cargo build` and other cargo commands such as `test` and `package` start hanging sometimes at this step:

```bash
Updating registry `https://github.com/rust-lang/crates.io-index` 
```

Example of `cargo package`:

```bash
Packaging rusoto v0.7.0 (file:///Users/matthewmayer/Documents/DualSpark/rust-aws)
   Archiving .gitignore
   Archiving .travis.yml
   Archiving AWS-CREDENTIALS.md
   Archiving Cargo.toml
   Archiving codegen/botocore_parser.py
   Archiving codegen/requirements.txt
   Archiving codegen/s3.json
   Archiving codegen/s3.rs
   Archiving codegen/sqs.json
   Archiving codegen/sqs.rs
   Archiving docgen.sh
   Archiving LICENSE
   Archiving README.md
   Archiving RELEASING.md
   Archiving s3-sample-creds
   Archiving src/bin/main.rs
   Archiving src/credentials.rs
   Archiving src/error.rs
   Archiving src/lib.rs
   Archiving src/params.rs
   Archiving src/regions.rs
   Archiving src/request.rs
   Archiving src/s3.rs
   Archiving src/sample-credentials
   Archiving src/signature.rs
   Archiving src/sqs.rs
   Archiving src/xmlutil.rs
   Archiving tests/sample-data/default_profile_credentials
   Archiving tests/sample-data/list_queues_with_queue.xml
   Archiving tests/sample-data/multiple_profile_credentials
   Archiving tests/sample-data/no_credentials
   Archiving tests/sample-data/s3_complete_multipart_upload.xml
   Archiving tests/sample-data/s3_get_buckets.xml
   Archiving tests/sample-data/s3_initiate_multipart_upload.xml
   Archiving tests/sample-data/s3_list_multipart_uploads.xml
   Archiving tests/sample-data/s3_list_multipart_uploads_no_multipart_uploads.xml
   Archiving tests/sample-data/s3_multipart_uploads_with_parts.xml
   Archiving tests/sample-data/s3_temp_redirect.xml
   Verifying rusoto v0.7.0 (file:///Users/matthewmayer/Documents/DualSpark/rust-aws)
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

It was at the last line for 15 minutes, pinning a single core of my machine, until I gave up and ctrl-c'd it.  Rerunning the cargo command finishes instantly.

I'm also seeing this behavior with our Travis CI builds, sometimes.  Travis automatically cancels the build after 10 minutes of waiting.

I think the easiest way of reproducing this issue is to check out Rusoto (https://github.com/DualSpark/rusoto) @ be07f36 and running this command:

```bash
cargo clean && cargo package
```

**Comment by alexcrichton** [comment]
This looks like resolution is going into a seemingly infinite loop... seems bad!

**Comment by matthewkmayer** [comment]
That could be it.  Is there other information I can provide, such as more detailed logging?  I'm not sure how to provide more info.

Another piece of information that may help: I don't recall this being an issue before we locked down to specific version of dependencies in our Cargo.toml file.

**Comment by matthewkmayer** [comment]
Dang, same issue.

```bash
$ rustc --version
rustc 1.4.0 (8ab8581f6 2015-10-27)

$ cargo --version
cargo 0.5.0-nightly (833b947 2015-09-13)

git checkout be07f36

cargo clean && cargo package
   Packaging rusoto v0.7.0 (file:///Users/matthewmayer/Documents/DualSpark/rust-aws)
   Verifying rusoto v0.7.0 (file:///Users/matthewmayer/Documents/DualSpark/rust-aws)
    Updating registry `https://github.com/rust-lang/crates.io-index`

```

**Comment by alexcrichton** [comment]
Nah it's ok, I can reproduce locally with the latest nightly, so I'll try to get around to investigating soon!

**Comment by mitchmindtree** [comment]
Just thought I'd let you know we're getting this issue when trying to update and build glutin. Here is the error occuring within travis, for example:

```
0.00s0.00s0.00s$ rustc --version
rustc 1.4.0 (8ab8581f6 2015-10-27)
$ cargo --version
cargo 0.5.0-nightly (833b947 2015-09-13)
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

That's the output of the current stable osx build.
The nightly linux build also produced the same error.

Strangely however, the build passed without issues on both nightly osx and stable linux? :confused: 

[This](https://github.com/tomaka/glutin/pull/655) is the PR in which I first noticed the issue.

I'm also currently hitting this trying to build glutin locally and haven't yet worked out a way around it.

**Comment by jimmycuadra** [comment]
Workaround: Change the dependencies to "x.y.z" (which is the same as "^x.y.z) instead of locking them at exact versions with "=x.y.z". This is probably a better practice for a library anyway.

**Comment by matthewkmayer** [comment]
Anything I can do to help work on this?  Is whatever fix https://github.com/rust-lang/cargo/issues/2064 will yield going to solve this?

Happy to do some investigation work if pointed in the right direction.

**Comment by alexcrichton** [comment]
@matthewkmayer yeah I suspect that #2064 will likely yield a resolution for this, unfortunately other than that I'm not sure if there's an easy way to tackle this.

One idea @wycats had was to bail out after more than N instances of recursion (where N is something like 20k) which would cause Cargo to generate an error, but that unfortunately still wouldn't be the greatest because these graphs *do* have solutions which can be reached quickly via one traversal, just not another.

**Comment by jaemk** [comment]
I seem to be hit with this. cargo is hanging on "updating registry" and pinning a core on stable(1.18) and the latest nightly on both linux and mac.

**Comment by jaemk** [comment]
Update: I got it to work again by changing the newly added (to my `Cargo.toml`) crate version to `*`. After it updated, I was able to set it back to a partial version (`0.7`).

**Comment by Masood-Lapeh** [comment]
Hi. `$ cargo search bidi` hangs:
`    Updating registry `https://github.com/rust-lang/crates.io-index``
I'm using cargo 0.19.0.

**Comment by MTRNord** [comment]
It is back again :( got it on my Server and on TravisCI builds :/

**Comment by exowaucka** [comment]
Also happening here inside a Docker container, although it might just be taking a very long time.  It doesn't seem to take as long when running directly on the host system, though.  (No VMs are involved, just Docker.)

**Comment by alexcrichton** [comment]
If you think you're hitting this issue then it'd be great to get assistance in debugging this. If Cargo's hogging CPU then you're probably running into https://github.com/rust-lang/cargo/issues/4066. If Cargo's not hogging CPU it'd be great if you could attach a debugger. The backtrace of the main thread will very likely indicate that https://github.com/rust-lang/cargo/issues/4261 is the actual issue here.

**Comment by exowaucka** [comment]
I'm not too keen on trying to attach a debugger inside a Docker container, but it's happening right now, and don't see any significant CPU usage, so it's probably #4261.  I'm on a janky workplace network, so it wouldn't surprise me if git operations sometimes take unreasonably long.

**Comment by PeterZhizhin** [comment]
I have tried to attach a debugger to the cargo process when it hanged at Updating registry point.
Of course, I did not have debugging symbols in the binary so I could not get readable backtrace.

I have tried to get cargo from Github and build cargo with debugging symbols. Unfortunately, my cargo from Homebrew hanged at "Updating registry" while trying to build cargo with `cargo build`.

Inception.

**Comment by Aarowaim** [comment]
`gfx-rs` is unstable so I attempted to switch one of my projects to `Piston-Graphics`. I encountered this issue of cargo being stuck updating the registry today while trying to compile with these `Cargo.toml` dependencies from the [piston tutorials](https://github.com/PistonDevelopers/Piston-Tutorials/tree/master/getting-started):
    
    [dependencies]
    piston = "0.35.0"
    piston2d-graphics = "0.23.0"
    pistoncore-glutin_window = "0.42.0"
    piston2d-opengl_graphics = "0.49.0"

I suspect that one of the packages may be unavailable but cargo continuously tries to access it.
