### ISSUE TITLE
Some way of writing plugins for Cargo

### ISSUE THREAD

**Issue by masoodahm** [rust-lang/cargo#2095]
This is sort of a feature and less of an issue (or no issue). I think It would be useful if devs could create plugins (or a custom command) for cargo say, if I install cargo-migrate plugin, cargo would allow me to do 
```bash
cargo dbmigrate -postgresql
```
that would do database migrations for the developer

**Comment by jonas-schievink** [comment]
You can do that with an [external subcommand](https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands)

**Comment by masoodahm** [comment]
yes I suppose that is what I was looking for.

**Comment by alexcrichton** [comment]
Yeah for now Cargo won't support plugins like the compiler (e.g. via dynamic loading), but with the subcommands @jonas-schievink mentioned as well as `cargo install`, I think we're pretty covered here!

Additionally, the Cargo library [is on crates.io](https://crates.io/crates/cargo), so you can even use all the existing library APIs!
