### ISSUE TITLE
Windows: Static libraries should end with .lib not .a when using the MSVC ABI install

### ISSUE THREAD

**Issue by pjmlp** [rust-lang/cargo#2100]
The standard extension for Windows static libraries is .lib.

By keeping the .a extension while using the MSVC ABI, we are forced to rename the files when integrating Rust libraries into compiler chains that expect .lib as an extension.

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually coming from the compiler, however, rather than Cargo, so could you reopen the bug over at rust-lang/rust?
