### ISSUE TITLE
Trouble with `cargo install --git` and ~/.gitconfig symlink under Cygwin

### ISSUE THREAD

**Issue by vadz** [rust-lang/cargo#2101]
This is a rather specific setup, so I'm not sure if it's worth fixing, but let me report it just in case:

When using `cargo install --git ...` with the latest nightly build under Windows with Cygwin git, I was getting "failed to clone into" error and further:
```
Caused by:
  [7] Failed to parse config file: Invalid configuration key (in c:/Users/me/.gitconfig:1, column 0)
```
This is due to the fact that my `.gitconfig` is a symlink (to a directory containing git-managed dot files), but apparently Cargo now tries to read it directly (via libgit2?) instead of using `git config` as it used to do before, I think.

An obvious workaround is to just delete the symlink, but perhaps Cargo could just ignore it if it can't read it?

**Comment by retep998** [comment]
Is the symlink an actual Windows directory symbolic link or cygwin's "symlink" which isn't actually a symbolic link but cygwin makes it seem like it is?

**Comment by vadz** [comment]
It's a Cygwin symlink, not a Windows shortcut, sorry for being unclear. I.e. the file contents starts with the bytes "!<symlink>" followed by the UTF-16-encoded file name.

**Comment by retep998** [comment]
Yeah, Cargo is just a normal Windows program. It doesn't understand the weird "symlinks" that cygwin does. There's not much that can be done except modifying libgit2 so that it simply ignores `.gitconfig` fails that it fails to parse.

**Comment by alexcrichton** [comment]
Also, do you know if this is specific to `cargo install`? I would expect the same failure to happen for any git dependency as well.

**Comment by vadz** [comment]
No, it's indeed not specific to `cargo install`.

FWIW I just replaced the Cygwin symlink with a "real" Windows symbolic link, as created by cmd `mklink` builtin and now everything works fine.

**Comment by cyplo** [comment]
Hi ! I think this one might be related: #2698 - it was closed by @alexcrichton, so probably this one may be as well ?

**Comment by alexcrichton** [comment]
Ah yes, thanks @cyplo!
