### ISSUE TITLE
cargo fetch fails when unpacking nom on Windows

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/cargo#2102]
I added [nom](https://crates.io/crates/nom) to an empty Rust project on Windows. When I ran `cargo fetch` it failed with:

```
E:\Rust\test>cargo fetch --verbose
unable to get packages from source

Caused by:
  Failed to unpack package `nom v1.0.0-beta`

Caused by:
  The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

I tried adding another project (win-api) and that worked fine so I think this is a Cargo issue.

Here's some info about my system:
```
OS: Windows 8.1 x64
Rust: 1.4 (stable) MSVC (8ab8581f6 2015-10-27)
Visual C++ toolchain: Visual Studio Community 2015
```

**Comment by alexcrichton** [comment]
Could you describe the directory/filesystem structure you had here as well? For example was this all working within one drive, across a few, etc?

**Comment by dkinitiate** [comment]
+1

Creating a new project in `%userprofile%\src`, with `cargo new --bin` and appending to `Cargo.toml`:
```
[dependencies]
nom = "~0.5.0"
```

reproduces this on my machine, windows 10 x64.
No other version of nom that I try to specify seems to be working either.
Other packages seem to work.

**Comment by wesleywiser** [comment]
Sure! I have two hard drives so my setup looks a little like this:

```
My Computer
|- C
  - Users\wesley (home)
  - Program Files and Program Files (x86) (Visual Studio installation path, default settings)
  - Windows (Windows installation, default settings)
|- E:
   - Rust\1.4 (Rust installation directory)
   - test (my empty rust project)
```

**Comment by alexcrichton** [comment]
Ah looks like one of the files in the package is `:w` and Windows doesn't like creating a file with the name, oh dear! cc @Geal may be something to fixup when packaging nom?

Regardless Cargo should either handle this or give a better error, so I'll keep investigating!

**Comment by alexcrichton** [comment]
OK, looks like MSYS is doing some scary things with semicolons and such in path names. It appears that if you extract a tarball with a file that has a semicolon in the name it will silently replace that semicolon with `\u{f03a}` on the filesystem. The MSYS tools will then all display that character as a colon, but if you do something like `fs::read_dir` or look at it in `cmd.exe` you'll see the funny unicode character.

This behavior seems a little odd to me, so my preferred course of action would be to do something like:

1. Provide a nicer error when unpacking a tarball.
2. Provide either a warning or hard error when creating a tarball with these special characters.

**Comment by Geal** [comment]
I'm truly sorry for that one. I was warned of untracked files appearing in
the packaes, but I did not check recently. I'll fix that tomorrow.

**Comment by e-oz** [comment]
just reproduced on aws ec2, redhat (ec2):

```
cargo build --release --verbose
 Downloading openssl v0.7.5
unable to get packages from source

Caused by:
  failed to unpack package `serde_xml v0.6.2`

Caused by:
  No such file or directory (os error 2)
```
