### ISSUE TITLE
Publish source tarballs of Cargo releases

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2107]
Although Cargo does have tagged releases, we don't publish source tarballs (the GitHub auto-tarballs are of course broken because submodules). Distros generally prefer tarballs to git.

Update the `make dist` rules to publish source tarballs consistently with Rust's own.

This will also likely require adding 'stable' dist bots for cargo.

re https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767

**Comment by lucab** [comment]
Just for reference: as of today, Debian is using github auto-tarballs of cargo tags as stable releases. The only git submodule in use is `rust-installer`, which at moment is probably useless for most of downstream distributors.

You may however still want to improve the status quo on your side, as the rust binary installer itself is not using/providing stable cargo releases.

**Comment by steveklabnik** [comment]
> as the rust binary installer itself is not using/providing stable cargo releases.

There are no 'stable' releases of Cargo at the moment, there are only nightlies. That doesn't mean that we're going to break the public interface, it's about the internals.

**Comment by lucab** [comment]
My bad, my comment was only meant to talk about release artifacts, not internal stability. I've updated it as I understand the term 'stable releases' was wrong and confusing.

**Comment by alexcrichton** [comment]
Note that if we do this I think we'll want to take advantage of `cargo-vendor` to pre-download all deps ahead of time.

**Comment by cuviper** [comment]
The cargo snapshot may have to be advanced for that.  The current choice only supports the older registry-index style as generated by `cargo-vendor 0.1.0`.  Newer versions make directory registries.

FWIW in Fedora I'm currently using the git tags to get a source archive from GitHub, along with a `cargo-vendor` tarball that I prepare myself.

**Comment by alexcrichton** [comment]
Oh yeah to support literally `cargo-vendor` today we'd need to fast-forward the "stage0" of Cargo to a Cargo that supports it. We just released Cargo 0.13.0, though, which supports it, so it may be plausible to snap to that if we need.

**Comment by alexcrichton** [comment]
This is now transitively done through rust's source tarballs, so closing.
