### ISSUE TITLE
Pair Cargo releases with Rust releases

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2108]
While Cargo does have tagged releases, _we don't actually use those in the Rust releases_, instead pairing rustc with an arbitrary recent revision of Cargo.

Update [rust-packaging](https://github.com/rust-lang/rust-packaging) to pair rustc not with Cargo nightlies, but with Cargo stable releases.

This will probably require having 'stable' cargo dist bots that produce versioned artifacts, though right now we're solving this in a hackish way by only tagging cargo commits that were nightlies.

re https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767

**Comment by carols10cents** [comment]
I think this can be closed now since cargo rides the trains...
