### ISSUE TITLE
Make binary releases of Cargo

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2109]
To pair Cargo releases with Rust our distribution servers must have versioned releases of Cargo to download. Add new stable dist builders and modify the Rust release process to also do a Cargo release.

re https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767

**Comment by Ericson2314** [comment]
What's the status of this? https://static.rust-lang.org/cargo-dist/index.html was a thing? Now we have actual channels?

**Comment by Ericson2314** [comment]
I see https://github.com/rust-lang/cargo/issues/2968#issuecomment-269650973 but that doesn't help get nightlies by date.

**Comment by Ericson2314** [comment]
@flosse informed me https://static.rust-lang.org/dist/index.html now contains Cargo too. All is well!

**Comment by carols10cents** [comment]
Sounds like this can be closed now. Please reopen if I'm mistaken!
