### ISSUE TITLE
hope make import module from local easy

### ISSUE THREAD

**Issue by psychoss** [rust-lang/cargo#2116]
so frustrated by this, i have been  tried no less twenty times to install the racer via cargo , it's still  stop there, and after a few minutes  broke with the same message.by the fact to connection github from china is awaly slowly,but i can download the project directly just take a little long while , is github use different server for "git"？

if possible，download everything may need, just place in the some directory, then cargo take care of  what module to import,or warn what important is missing。

give the user a another choice to suite what they need。

i have tried   to use `log = [path=“”]` to load the local moudle. but it is a hard work because you must check every submodule, then create a directory for place what it depended，if the sub-submodule is still depend on somthing, the work becomes a black hole。

sorry english not my mother language. 

![](http://www.mean101.com/Screenshot%20from%202015-11-05%2021:19:46.png)

**Comment by alexcrichton** [comment]
Sorry but I'm not quite sure what's going on here, could you describe a little more in detail about what you're trying to do along with what the errors you're seeing are (e.g. via gists)?

**Comment by psychoss** [comment]
@alexcrichton  thank first, it's almost only becasue the slow or poor internet connection, and i cant provide anything expect the above picture showed,  i just hoped the cargo would be provide a more easy way to load the local modules
