### ISSUE TITLE
Allow Specification of Object Files for Linking

### ISSUE THREAD

**Issue by esheri3** [rust-lang/cargo#2117]
I have a situation where I'm using Rust + C++ in a single project. The C++ code *must* call a #[no_mangle] function within the Rust code. I am trying to keep the entire build under Cargo by calling a makefile in build.rs to build the C++ code first. Unfortunately, the C++ code will not build as a dylib/static because of an unresolved reference to the method in the Rust code (reasonable). To work around this, I'm exploring having the makefile build C++ object files that could then be linked by rustc. Is there anyway within Cargo to specify additional object files for linking? I see the ability to specify additional libraries (dylib/static) via rustc-link-lib, but I'd need something for object files like "rustc-link-obj". Is this available? If not, is this something that could be supported?

Trying hard to keep the build Cargo-centric. Thanks and great work!

**Comment by alexcrichton** [comment]
There is indeed a way to do this! If you build all the C++ code into a static archive (e.g. `libfoo.a`) you can then link that via:

```rust
println!("rustc-link-search=native=/path/to/where/lib/is/located");
println!("rustc-link-lib=static=foo");
```

You may also be interested in the [`gcc` crate](https://crates.io/crates/gcc) which is generally used to compile C/C++ code and link it into a Cargo project (with no extra `println!` directives needed).

Lemme know if you need any more help though

**Comment by esheri3** [comment]
Thank you! Unfortunately, it appears as though many symbols from the C++ static library are being discarded as they are not directly called by the Rust code, yet I need those symbols (and everything else in the C++ staticlib) to be included in the resulting Rust dylib. Some googling suggests I would need to use the "--whole-archive" option from gcc. Is there a way to express in Cargo that the entire C++ staticlib, regardless of what is actually called by the Rust code, be linked and included within the resulting Rust dylib?

**Comment by alexcrichton** [comment]
We should actually be passing `--whole-archive` when building a dylib (for this reason), so are you sure you're running an up-to-date rustc? We may have perhaps forgotten to add the flag for native libraries?

**Comment by esheri3** [comment]
I am running rustc 1.4.0 on OSX. It seems a reasonable possibility that --whole-archive is not being passed to native libraries. I'm going to try making use of the gcc-rs pattern instead of println to see if that makes a difference. Will report back shortly.

**Comment by esheri3** [comment]
Using gcc-rs within build.rs worked! The symbols from the C++ staticlib were preserved. I'm guessing --whole-archive is not passed to native libs, but I won't be digging further as encompassing everything within rust, including C++ via build.rs, is much cleaner then incorporating makefile. Thank you!

**Comment by alexcrichton** [comment]
Glad to hear that it worked out, glad I could help!

**Comment by ratnadeepb** [comment]
Though this is an old post, I find myself in a similar situation. We have built, in our lab, an NFV manager on top of DPDK. This manager runs as a primary process and one can build multiple NFs as secondary processes. There are certain linker magic through included *.mk files. Now that I am trying to build a Rust NF as a secondary process, I find it impossible to move across these linker errors. Maybe this is simply my inexperience with Rust, but any advice would be welcome!
