### ISSUE TITLE
expose test binary path

### ISSUE THREAD

**Issue by danburkert** [rust-lang/cargo#2119]
There should be a way to get the path to the binary resulting from `cargo test --no-run` via scripts in a non interactive setting.

**Comment by danburkert** [comment]
It can be done via file globbing, but it's a little messy.

**Comment by alexcrichton** [comment]
My preferred method of doing this would be to actually just have predictable names, so I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/1924, but thanks for the report!
