### ISSUE TITLE
build test binary with cargo rustc

### ISSUE THREAD

**Issue by danburkert** [rust-lang/cargo#2120]
It's currently not possible to package a test binary using `cargo rustc`, which can be useful when cross compiling a test binary.

**Comment by alexcrichton** [comment]
Does passing `--test` to `rustc` work?

**Comment by danburkert** [comment]
No, or at least I don't think so.  `--test` takes a test target, but I don't know how to specify the target as the libraries in-source tests.

**Comment by alexcrichton** [comment]
Ah I meant along the lines of:

```
cargo rustc --lib -- --test
```

(e.g. passing `--test` to rustc, not cargo)

**Comment by danburkert** [comment]
I tried that, but it fails at that point to link dev dependencies.  Perhaps
there's a workaround to force cargo to link in the dev dependencies with
`cargo rustc`?

**Comment by alexcrichton** [comment]
Ah, right yes of course! Currently there's no way to work around that, but I have also wanted this in the past!
