### ISSUE TITLE
Duplicate binary names are not handled well.

### ISSUE THREAD

**Issue by vi** [rust-lang/cargo#2125]
```
echo 'fn main(){}' > a.rs
echo 'fn main(){}' > b.rs
cat > Cargo.toml <<\EOF
[package]
name = "qqq"
version = "0.1.0"
authors = ["A <a@a.a>"]

[[bin]]
name = "e"
path = "a.rs"

[[bin]]
name = "e"
path = "b.rs"
EOF
cargo build
```

```
   Compiling qqq v0.1.0 (file:///tmp/carg)
error: failed to remove /tmp/carg/target/debug/e.0.o: No such file or directory (os error 2)
error: failed to remove /tmp/carg/target/debug/e.metadata.o: No such file or directory (os error 2)
An unknown error occurred

To learn more, run the command again with --verbose.
```

Expected something like "Error parsing Cargo.toml: duplicate binary name `e`".

**Comment by alexcrichton** [comment]
Ah yeah this should probably just be rejected at the top level, I can't actually imagine a situation in which it'll work!

**Comment by psyomn** [comment]
Hi! I'd like to give this a shot! I'm pretty new to the internals of cargo. I'm suspecting you'd like this to stop the compilation process in case something like this is defined in the manifest?

**Comment by alexcrichton** [comment]
I'd actually also be fine with just rejecting Cargo.toml files that look like this. I think some validation would just need to be added to `src/cargo/util/toml.rs` to ensure non-library targets all have unique names.
