### ISSUE TITLE
Cargo install doesn't install current crate

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/cargo#2142]
If I cd to a crate's root directory and run

```bash
cargo build --release
cargo install
```

I expect cargo to install the current crate. However, it says ``Updating registry `https://github.com/rust-lang/crates.io-index` `` which it shouldn't do and then fails with `must specify a crate to install from crates.io`.

**Comment by alexcrichton** [comment]
Ah yeah this seems like a reasonable thing to add, seems like an easy bug to knock out!

**Comment by Stebalien** [comment]
Thanks @JIghtuse!
