### ISSUE TITLE
Registry updates make `cargo search` painful to use on slow/high-latency connections

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#2144]
For me, every `cargo search` invocation takes several seconds due to registry updates, which makes using it surprisingly unpleasant (every time I type it, it hurts a little bit :( ).

``` rust
$ time cargo search foobarbaz
    Updating registry `https://github.com/rust-lang/crates.io-index`

real    0m2.397s
user    0m0.048s
sys 0m0.044s
```

It might be nice if registry updates were optional (either opt-in or opt-out) and/or was rate-limited, e.g. the registry probably doesn't need to be updated 5 times in 20 seconds if I'm searching for several things.

**Comment by alexcrichton** [comment]
The problem here is that the github URL of the registry is known, but the API URL to actually call into is stored in the github repo (e.g. it can change). Architecturally that seems like a not-great decision perhaps.

**Comment by nodakai** [comment]
Any plans to introduce caching?

Cf. caching in Fedora's `yum(8)`
- https://ask.fedoraproject.org/en/question/31808/how-to-make-yum-consume-less-traffic/

**Comment by thuzhf** [comment]
+1. Almost unbearable.

**Comment by alexcrichton** [comment]
An HTTP fast path has been added to speed up noop registry fetches, so I'm going to close this.
