### ISSUE TITLE
Add a "cargo outdated" command

### ISSUE THREAD

**Issue by alex** [rust-lang/cargo#2148]
Similar to `bundle outdated` or `pip list --outdated`, `cargo outdated` would list packages pinned in the `Cargo.lock` which were outdated. Similar to `cargo update` except not actually writing to `Cargo.lock`.

**Comment by jonas-schievink** [comment]
Already exists externally: https://github.com/kbknapp/cargo-outdated

**Comment by alexcrichton** [comment]
Indeed! `cargo install cargo-outdated` should do the trick and [a related bug was recently closed](https://github.com/rust-lang/cargo/issues/1385) so I'll close this for now like that one.

If this ends up being widely used then we can certainly consider inclusion into the main repo!
