### ISSUE TITLE
Segmentation Fault on cargo build

### ISSUE THREAD

**Issue by yeliknewo** [rust-lang/cargo#2150]
I am on ubuntu 15.04 and using multirust with stable which is currently rustc 1.4.0 and cargo 0.5.0. When I try to cargo build I get 
Segmentation fault (core dumped)
but rustc works.

**Comment by alexcrichton** [comment]
Could you provide some of the code in question or a way to reproduce this locally? Unfortunately this isn't really enough information to be an actionable issue right now.

**Comment by alexcrichton** [comment]
Could you paste the output of `cargo -V` and `rustc -V`? Can you also get a backtrace of the segfault? I'm unable to reproduce this in a minimal docker container of ubuntu 15.04 unfortunately.

**Comment by yeliknewo** [comment]
It seems to be working now. Must have been something with atom and racer.
