### ISSUE TITLE
Use single quotes in .toml

### ISSUE THREAD

**Issue by flying-sheep** [rust-lang/cargo#2157]
I’m always a proponent of keeping things minimal. Since the vast majority of strings won’t need escapes, and since they make strings look less cluttered, I propose using single-quoted strings in

* `cargo new`-created projects
* the cargo guide and docs
* the <kbd>Cargo.toml <kbd>some-crate = "1.0.0"</kbd></kbd> copybox on crate pages

**Comment by alexcrichton** [comment]
This is certainly possible to do in TOML, and it's always possible to change. I'm not sure if there's much benefit from taking an "opinionated stance" here and changing everything?

**Comment by flying-sheep** [comment]
maybe not worth the effort, but as of now, i’m always a bit annoyed that everything uses the slightly worse alternative. if there’s alternatives, someone did have an opinion at one point, so keeping double quotes is opinionated as well :smile:

**Comment by alexcrichton** [comment]
I think that for now it's probably best to at least stay consistent across everything, and seeing how there's not really a benefit one way or another from changing I'm gonna close this for now due to "unfortunate inertia".

**Comment by flying-sheep** [comment]
damn. well, i hope at least `cargo add` with the [hypothetical new backend](https://users.rust-lang.org/t/looking-for-a-project-how-about-a-toml-parser-that-writes-nice-files/3719) could detect and adapt to style.
