### ISSUE TITLE
Cargo Tab Completion broken

### ISSUE THREAD

**Issue by tbelaire** [rust-lang/cargo#2163]
I have a nightly cargo
`cargo 0.7.0-nightly (fb73974 2015-11-18)`
and when I do `cargo build <TAB>`, it produces

```
$ cargo build Extraneous text ' ...' in option description '-p SPEC --package SPEC ...'....
```

And it just loops that text over and over till I kill it.

This is in a directory with no cargo.toml yet.  This appears to be a bug related to `docopt`.

Also, for `cargo init <TAB>` I get

```
$ cargo init Could not find usage patterns in doc string....
```

**Comment by sbeckeriv** [comment]
Triage: Is this still a problem? I can not reproduce it on an a mac with cargo 0.9.0.

**Comment by steveklabnik** [comment]
I think it's not getting installed sometimes; @ashleygwilliams was also not seeing tab completion when she installed through rustup a few days ago.

**Comment by sbeckeriv** [comment]
Good to know. I have installed stable via the new rustup.rs. The installed 'cargo' tab completes but not the 'rustup run stable cargo'.

**Comment by steveklabnik** [comment]
Huh, for her, she had no tab completion. Maybe it's a rustup bug, not  acargo bug.

**Comment by carols10cents** [comment]
I... didn't think cargo had builtin tab completion? And if it was broken somehow in the initial report, I can't reproduce either.

Using bash on osx, if I type `cargo init <tab><tab>` i get filenames from the current directory, similarly if I type `cargo build <tab><tab>`.

If someone can provide more information about the environment in which you're expecting tab completion, when it kicks in with what info, and any unexpected output you're getting, please reopen this!

**Comment by sbeckeriv** [comment]
I have not check in a long time but I think this file use to work out of the box
https://github.com/rust-lang/cargo/blob/master/src/etc/cargo.bashcomp.sh
