### ISSUE TITLE
No way of specifing a rpath so custom Frameworks aren't linkable

### ISSUE THREAD

**Issue by schmitch** [rust-lang/cargo#2171]
Hello, currently we use some Frameworks inside of mac which are inside the /Library/Frameworks folder, however in cargo there is no way of setting this @rpath so that the Framework gets found.

**Comment by alexcrichton** [comment]
Yeah currently Cargo doesn't allow passing flags like `-C rpath`, but build scripts can specify framework search paths and frameworks to the compiler via `rustc-link-{lib,search}`. I believe we have other bugs about passing extra flags to rustc, so I'm going to close this in favor of those, thanks for the report though!
