### ISSUE TITLE
Provide API to query crates owned by the project

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#2172]
Various third-party cargo subcommands ([cargo-count](https://github.com/kbknapp/cargo-count), [cargo-fmt](https://github.com/pwoolcoc/cargo-fmt)) operate on the crates (and their source files) owned by the current Cargo project.

Currently, they are operating recursively on all `.rs` files in the current working directory, disregarding which `.rs` files are actually owned by the project.

I have come across `.rs` files in the `target/` directory for example, which probably shouldn't be operated on. And there could be various other `.rs` files which are not owned by the project.

Furthermore, for `cargo-fmt`, `rustfmt` runs on a module, and all of its submodules, so simply running it recursively on all `.rs` files needlessly formats submodules multiple times.

Reimplementing the behavior of Cargo for determining which crates are owned by the project and which are not would be error-prone, and a duplication of effort.

Therefore, it would be beneficial if Cargo exposed an API for this functionality, which could be used by subcommands.

Furthermore, it would be nice if it was possible to get the crates for various configurations (i.e. `--bin`, `--lib`, etc.). This would allow things like `cargo fmt --bin my_bin_target`, which would only format that bin target.

**Comment by alexcrichton** [comment]
Yeah in general this is kinda under the umbrella of a `cargo metadata` subcommand where you can learn more about the dependency graph and such. For now I'd recommend just doing `extern crate cargo` and using that, the API is unstable but it should work well to just pin to one version and call it a day for now.

**Comment by crumblingstatue** [comment]
> For now I'd recommend just doing extern crate cargo and using that, the API is unstable but it should work well to just pin to one version and call it a day for now.

Is there such a functionality exposed in the public API of the cargo crate though? If there is, I can't find it.

**Comment by epage** [comment]
I fee like `cargo package --list` could help.  It'll do the walking for you and return the results.

**Comment by weihanglo** [comment]
I can confirm `cargo package --list` should return a list sufficient to compile a given crate. With `cargo metadata` you can also figure out workspace members to query Furthermore, you can take these lines as a reference of retrieving a list of files:

https://github.com/rust-lang/cargo/blob/13413c64ff88dd6c2824e9eb9374fc5f10895d28/src/cargo/ops/cargo_package.rs#L87-L101

That said, I think the original issue is resolved. Just the Cargo API is a bit not ergonomics. I'll close this as resolved now. If you feel it is wrong, please let us know.
