### ISSUE TITLE
Interrupting and restarting cargo-package (or publish) can skip verification

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#2173]
Scenario:

* Run `cargo publish`
* See

    ```
        Updating registry `https://github.com/rust-lang/crates.io-index`
    warning: manifest has no description, license or license-file. See http://doc.crates.io/manifest.html#package-metadata for more info.
    warning: some dependencies have wildcard ("*") version constraints. On December 11th, 2015, crates.io will begin rejecting packages with wildcard dependency constraints. See http://doc.crates.io/crates-io.html#using-crates.io-based-crates for information on version constraints.
    dependencies for these crates have wildcard constraints: make-cmd
       Packaging expat-sys v2.1.0 (file:///home/simon/projects/servo/deps/libexpat)
    ```
* Think “that’s wrong, I need to fix it before publishing”
* Hit CTRL+C
* Fix `Cargo.toml`
* Run `cargo publish` again
* The crate is apparently published without being compiled, as if I had specified `--no-verify`.

I’m guessing that `cargo package` is a no-op if a tarball already exists. Interrupting it earlier has left a tarball behind even though verification did not complete.

In this case the crate was fine, but maybe I could have published one with build errors.

**Comment by alexcrichton** [comment]
Yeah I think I've run into this before as well, we should in theory only move the tarball to its final location *after* the build has finished, and perhaps not even write it out to disk until that time.

**Comment by SimonSapin** [comment]
Something like that, yes. Although unless it proves costly I’d still do the tarball compress/uncompress dance so that what’s tested is as close to possible to what will be published.
