### ISSUE TITLE
`cargo doc` ignores build script

### ISSUE THREAD

**Issue by rasendubi** [rust-lang/cargo#2175]
I have the libcore in a custom location because I'm cross-compiling to a custom target. I specify the link path with a build script. My library builds fine but generating documentation with `cargo doc --target=thumbv7em-none-eabi` fails because it can't find libcore. From `--verbose` I see cargo doesn't run my build script and doesn't pass my link directory.

**Comment by rasendubi** [comment]
Still an issue.

I also forgot to say it has worked fine somewhen before Nov 28, 2015.

**Comment by rasendubi** [comment]
Found a workaround. `rustc` and `rustdoc` flags can be set using `RUSTFLAGS` and `RUSTDOCFLAGS` respectively.

So in my case, I used the following command to specify my library directory:
```
RUSTFLAGS="-L lib/thumbv7em-none-eabi" RUSTDOCFLAGS="-L lib/thumbv7em-none-eabi" cargo doc --target=thumbv7em-none-eabi
```

**Comment by eminence** [comment]
Triage:  this is a very old issue that seems to be about rustdoc, not cargo.  It probably should be just closed

**Comment by ehuss** [comment]
Indeed, there's also not quite enough information to go on here.  I suspect it sounds like this is building the standard library using an unsupported means. Today, this would normally be handled by build-std. Or it's not clear why this didn't use a sysroot. Closing as not something we will support.
