### ISSUE TITLE
Upload should be transactional

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#2177]
With a dependency `expat-sys = "=2.1.0"`, `cargo build -v` shows:

```
unable to get packages from source

Caused by:
  failed to unpack package `expat-sys v2.1.0`

Caused by:
  failed to unpack `expat-sys-2.1.0/testdata/largefiles/recset.xml` into `/home/simon/tmp/multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/expat-sys-2.1.0/testdata/largefiles/recset.xml`

Caused by:
  corrupt deflate stream
```

I’m just guessing what happened here, but I think that when I hit CTRL-C in https://github.com/rust-lang/cargo/issues/2173 I interrupted `cargo publish` in the middle of the upload, and crates.io got a partial (corrupted) tarball. It should instead have considered this upload failed and not published that version.

**Comment by alexcrichton** [comment]
Hm yes this is quite bad! I think it's basically the same as #2173 though (e.g. the same solution), so I'm gonna close in favor of that. Hoping to tackle it this week though!

**Comment by SimonSapin** [comment]
It’s sort of related, but there are at least two sorts of failures to protect against (and that might required different measures):

* Verification is accidentally skipped (without `--no-verify`) and a crate with a build error is published
* Upload is interrupted in the middle and a partial tarball (that can not be extracted, or even can but is missing some files) is published

**Comment by alexcrichton** [comment]
Ah well I'm gonna post a PR soon to fix both of these, so it doesn't matter too much.
