### ISSUE TITLE
Add "changelog" to Cargo.toml and crates.io

### ISSUE THREAD

**Issue by jFransham** [rust-lang/cargo#2188]
Inspired by [this blog post](https://blog.dbrgn.ch/2015/12/1/rust-crates-keep-a-changelog/), I think it would be a great idea for the `[package]` section in the Cargo.toml to contain a changelog option (as it contains a readme option), and for crates.io to recognise this and have it as a link under "Links", or to somehow reference it under the "versions" links.

**Comment by dbrgn** [comment]
This would be fantastic.

**Comment by emoon** [comment]
Yeah this would be great to have.

**Comment by yupferris** [comment]
+1

**Comment by dbrgn** [comment]
I'm giving this a stab. Do you think the `changelog` metadata entry should be a file path (relative to Cargo.toml) or an URL? If it were a path, it could be parsed, but since there's no standard changelog format I think a URL would be more flexible.

**Comment by alexcrichton** [comment]
@dbrgn this'd probably want to be the same as `readme` which is just a path relative to Cargo.toml. The `cargo publish` process could then basically make sure it's a file and send it off to crates.io, although crates.io may not necessarily do anything with it just yet.

**Comment by zofrex** [comment]
Is this still something we want?

**Comment by Boscop** [comment]
Yes, definitely. I often find myself wading through git commits trying to figure out how much effort it would be to upgrade to a newer version of a crate.
It would be a huge time saver to have a succinct changelog.
The changes should be recorded as a diff from each last version, so that when I'm interested in upgrading from version x to y, it will integrate all those diffs of the intermediate versions into one changelog summary on crates.io.

**Comment by dbrgn** [comment]
> The changelog should have annotations for how much effort each change requires when upgrading, e.g. 1 to 3 stars *** in front. 

That is *very* subjective. But it would be good to at least link to existing CHANGELOGs as a first step.

**Comment by Boscop** [comment]
Yes, I kinda said it to revive this discussion. It's not really necessary but what would be very useful is to get an changelog summary integrated over all versions from my current version to the one I want to update to.

**Comment by nagisa** [comment]
I do [this](https://github.com/nagisa/rust_libloading/blob/master/src/changelog.rs) and find it works way better than a file in root IMO.

**Comment by dead10ck** [comment]
@newpavlov I actually really like that idea, except that I'd maybe add a title section similar to the existing Keep a Changelog format, and always keep an extra newline at the end of the file. That way you can just `cat changelog/*` to get the whole `CHANGELOG.md`. This takes care of the problem of having a single file grow forever, and it would make it easy to enforce change logs in CI builds and such.

**Comment by newpavlov** [comment]
@dead10ck 
Idea was to generate this title section automatically based on crates.io registry and instead of `cat` use `cargo changelog` to get whole `CHANGELOG.md`. I don't think it's worth to increase amount of manual work to make it a bit easier for programs to compile full changelog.

**Comment by dead10ck** [comment]
How would `cargo` generate the date consistently, though?  Only thing I could think of would be VCS, and that would necessitate implementing support for every VCS via the `cargo changelog` command, which is a lot of effort just to about another line in a file you have to create manually anyway.

**Comment by newpavlov** [comment]
@dead10ck 
As I've explicitly wrote it will get all necessary information from crates.io registry, so no need for supporting VCS.

**Comment by dead10ck** [comment]
@newpavlov ah, my apologies, I didn't think about that info being in the registry. Still, though, it seems like a bit of over engineering to require registry info to save one line of text. And that approach makes it incompatible with tools outside of the `cargo changelog` command.

**Comment by dead10ck** [comment]
Also, it precludes a big use case, which is crates that aren't published on crates.io. Which is I think the biggest problem with that approach.

**Comment by carols10cents** [comment]
Discussion of this should now happen on [RFC 2129](https://github.com/rust-lang/rfcs/pull/2129), and if that is accepted, it'll get its own tracking issue, so I'm going to close this one.
