### ISSUE TITLE
crates.io build script guide: optional dependencies mistake?

### ISSUE THREAD

**Issue by hobofan** [rust-lang/cargo#2191]
In the ["Linking to system libraries" example](http://doc.crates.io/build-script.html#case-study-linking-to-system-libraries) of the build script guide it says:

> It has a **optional dependency on libssh2** on all platforms to implement the ssh transport.

A few lines later there is a contradicting statement while still talking about the same example:

> Here we also see the **unconditional dependency on libssh2** via the libssh2-sys crate

Am I missing something or should the former also read "unconditional dependency"?

**Comment by steveklabnik** [comment]
I think you're correct.

**Comment by alexcrichton** [comment]
This is actually intentional, but I think the antecedents may not be clear enough. "It" in the optional part is referring to libgit2 itself whereas later the "it" is the Rust crate which chose to have an unconditional instead of optional dependency.

**Comment by alexcrichton** [comment]
(I can see where this is confusing though!)
