### ISSUE TITLE
Add metadata subcommand to cargo

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2193]
This is a follow up of #1225, #1434 and #2091

cc @dan-t @lunaryorn @winger @alexcrichton 

Currently we have an **external** sub command by @winger. The fork compatible with the recent version of cargo is [here](https://github.com/intellij-rust/cargo-metadata).  It is very experimental, but already can be used to extract valuable metadata ([a proof by gif](
https://camo.githubusercontent.com/8aac2a369ea19ba71a732d53bdf5a897224de846/687474703a2f2f672e7265636f726469742e636f2f50365933426c784139662e676966 )). It depends on the dev version of cargo and is not available on crates.io, but you can `cargo install --git https://github.com/intellij-rust/cargo-metadata` it.

I would really like to include this sub command to cargo:
  * It's not very convenient to ask a user to install some tool when she just tries to open a project in an IDE.
  * Installing metadata can be a hassle: it depends on the cargo itself, so it takes ages to compile and can fail if you don't have necessary OpenSSL headers. 
  * A "standard" metadata command would help tools interoperability.

So I ask the following questions:

* What data and in what format should metadata provide? @dan-t, @lunaryorn could you experiment with it and give feedback? 
* What steps are to be taken to merge this thing to cargo?

**Comment by dan-t** [comment]
>   • What data and in what format should metadata provide? @dan-t, @lunaryorn
>     could you experiment with it and give feedback?

As long as I'm getting the source path of all dependencies, including
local path dependencies and local overrides, I'm fine for my use case.

**Comment by alexcrichton** [comment]
In terms of format, I think it should probably default to the Cargo standard of TOML but also be configurable to other formats like JSON or perhaps just some textual encoding. I wouldn't be too worried about that, however.

In terms of what data this should provide, I think that basically exposing the standard structures of `Package` and such are probably sufficient (e.g. exporting a subset of their fields), and then we may want to provide various stages for example metadata of the current package before resolution and then metadata after resolution (to include dependencies).

https://github.com/rust-lang/cargo/pull/1434 seemed pretty promising to me but it unfortunately stalled :(

**Comment by matklad** [comment]
I will try update #1434 then

**Comment by matklad** [comment]
@alexcrichton am I correct that `read-manifest` and `metadata` should be two separate commands? They seem pretty similar in scope. May be we should use a single command with different flags?

**Comment by alexcrichton** [comment]
Yeah I think it's fine to start a new `metadata` command from scratch. I'd be fine deprecating `read-manifest` as well eventually in favor of just one command if it comes to that as well.

**Comment by alexeykudinkin** [comment]
@alexcrichton any progress on this? It really impedes us introducing fully-fledged Cargo's projects support in https://github.com/intellij-rust/intellij-rust.

**Comment by alexcrichton** [comment]
Indeed! @matklad is doing some awesome work over in #2196 to add this command.

**Comment by alexcrichton** [comment]
(any suggestions about what sort of output you'd like to see would also be quite welcome!)
