### ISSUE TITLE
Wrong directory with path dependency

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#2195]
When using a path dependency, cargo seems to print out the current path, rather than the dependency's path.

For example, if I change the `semver` requirement to point at my local one, when building cargo, cargo prints

```
   Compiling semver v0.2.0 (file:///home/steve/src/cargo)
```

but that should be

```
   Compiling semver v0.2.0 (file:///home/steve/src/semver)
```

**Comment by alexcrichton** [comment]
This ends up being the same as https://github.com/rust-lang/cargo/issues/497, and while somewhat odd is an artifact of the way Cargo is structured which won't change for now. This has to do with how what's being printed here is a package id and the URL for that package id is the "source id" which in this case is a filesystem path. Packages with `path` dependencies are considered to all come from the same source, which allows Cargo to not reread the filesystem repeatedly all the time.

All in all, this is currently expected, but hopefully doesn't cause any bugs!
