### ISSUE TITLE
RFC: Add option to mark a crate "private" so it's not publishable to crates.io

### ISSUE THREAD

**Issue by erickt** [rust-lang/cargo#2202]
npm has a helpful "private" option that prevents an internal package from being published. This would be really useful as people develop internal applications, or a project like Servo where only some crates can be safely published.

**Comment by JanLikar** [comment]
Like this?
```
[package]
name = "foo"
private = true
```

**Comment by alexcrichton** [comment]
@JanLikar yeah that's what I was thinking
