### ISSUE TITLE
Cargo build fails when another folder exists

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang/cargo#2211]
Disagreeable conflict: If I put `node_modules` folder with npm packages into folder with Rust project I get an error:

```
$ cargo build
Unable to update file:///C:/DEV/SIMULATOR
```

Maybe it's not a good idea to combine projects, but I think that conflict isn't a right behaviour.
If I remove that folder, cargo builds well. Why it happens?

package.json which produce `node_modules` folder (`npm install` command):

``` json
{
  "name": "simulator-client",
  "version": "0.1.0",
  "description": "- - -",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Denis Kolodin",
  "license": "Proprietary",
  "devDependencies": {
    "connect": "^3.4.0",
    "connect-livereload": "^0.5.3",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-csso": "^1.0.1",
    "gulp-imagemin": "^2.4.0",
    "gulp-jade": "^1.1.0",
    "gulp-less": "^3.0.5",
    "gulp-livereload": "^3.8.1",
    "gulp-myth": "^1.1.0",
    "gulp-stylus": "^2.1.0",
    "gulp-uglify": "^1.5.1",
    "serve-static": "^1.10.0",
    "tiny-lr": "^0.2.1"
  },
  "dependencies": {
  }
}
```

Env: _rustc 1.7.0-nightly (110df043b 2015-12-13) | 64 bit | Win 10_

**Comment by durka** [comment]
I can't reproduce, using an arbitrary crate. I'm on OSX, and I tried stable/beta/nightly.

```bash
$ git clone https://github.com/durka/guard
$ cd guard
$ pbpaste >package.json
$ npm install
...
$ cargo build
   Compiling guard v0.2.4 (file:///Users/alex/Programming/rust/guard)
```

Can you try to narrow it down further and/or upload the rest of the crate somewhere for testing?

**Comment by steveklabnik** [comment]
Might be worth doing a grep for 'DEV/SIMULATOR' to see where that is.

**Comment by durka** [comment]
@steveklabnik I think C:\DEV\SIMULATOR is @DenisKolodin's current directory.

**Comment by durka** [comment]
Anyway,

```bash
cargo $ ag -Qi simulator
cargo $
```

:)

**Comment by steveklabnik** [comment]
Ah, given that it was saying "update" I was thinking it might be something else.

**Comment by alexcrichton** [comment]
If you're on linux, can you perhaps try `strace` to see what syscall is failing?

**Comment by carols10cents** [comment]
I'm not able to reproduce this:

```
 $ cargo new issue-2211
     Created library `issue-2211` project

$ cd issue-2211/

$ mkdir node_modules

$ cargo build
   Compiling issue-2211 v0.1.0 (file:///private/tmp/demo/issue-2211)
    Finished dev [unoptimized + debuginfo] target(s) in 0.29 secs
```

Given that we haven't had any other reports of this, I'm going to give this a close. Please reopen with reproduction instructions if you encounter this again!
