### ISSUE TITLE
Add a local filesystem registry type

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2212]
For the purpose of packaging Rust applications, Debian (and likely other distros) wants to also package all of the application's dependencies. They have tried doing this be rewriting registry dependencies into path dependencies and found it burdensome. What we want them to be able to do is construct a directory tree on the local filesystem that cargo understands as a new type of registry, and override cargo to use it instead of crates.io

The layout of this directory structure needs to be easily reproduced through scripting.

**Comment by sfackler** [comment]
This might be covered by https://github.com/alexcrichton/cargo-vendor ?

**Comment by warner** [comment]
I've found myself wanting a way to use `cargo` offline (on a plane): telling it to skip the registry-update step and just use the cached index+tarballs that it fetched last time. A `filesystem` registry type might be an elegant way to accomplish that, if the `filesystem` and "normal" registries share the same format (and even the same disk location), but the `filesystem` type doesn't do an update each time you run `cargo`. Then I could switch between online and offline modes by just editing the prefix of the `[registry] index=` field in `.cargo/config`.

**Comment by marcbowes** [comment]
Isn't this already supported (poorly)? You can set `registry.index` to the filesystem by using `file://`. The only niggle is that you have to do a `git commit` in the filesystem registry.

**Comment by alexcrichton** [comment]
@marcbowes sorta, yeah, but it's pretty painful and not exactly intended for that purpose :)

**Comment by marcbowes** [comment]
Agreed on the painful (this is what I'm doing at work). I just wanted to point out that you can work around this *without* rewriting Cargo.toml files.

**Comment by joshtriplett** [comment]
@warner I encountered the same problem on a plane.  I made a minor tweak to my Cargo.toml file, and cargo then refused to proceed without updating, which it couldn't do offline.  I'd like to download an offline snapshot of a pile of Cargo dependencies, so that I can always build.

**Comment by carols10cents** [comment]
I believe the main request in this issue is addressed by https://github.com/alexcrichton/cargo-vendor and https://github.com/alexcrichton/cargo-local-registry, and the offline issues are covered by https://github.com/rust-lang/cargo/issues/1882 and https://github.com/rust-lang/cargo/issues/3479.
