### ISSUE TITLE
[Cargo run] passing arguments to the binary works unexpectedly

### ISSUE THREAD

**Issue by JanLikar** [rust-lang/cargo#2213]
I'm trying to pass arguments to a binary that then passes arguments after -- to another binary.

```
`jan@hp:~/Projekti/rustfmt$ cargo run --bin cargo-fmt -- -- --write-mode=diff
Running `target/debug/cargo-fmt --write-mode=diff`
```

I would expect cargo to run `target/debug/cargo-fmt -- --write-mode`

**Comment by alexcrichton** [comment]
Huh, I thought this was a fixed bug...

cc @BurntSushi

**Comment by BurntSushi** [comment]
I would have thought so too given [this test](https://github.com/docopt/docopt.rs/blob/master/src/test/testcases.docopt#L992-L994). There might be something else going on with two uses of `--`. I'll dig into this soon.

**Comment by JanLikar** [comment]
I have additional info: If a flag is passed to both binaries, it works just as expected, if a flag is passed only to the "final" binary, it doesn't work.

**Comment by carols10cents** [comment]
Triage: this is still a problem as far as I can tell.

```
 $ cargo new --bin foo
     Created binary (application) `foo` project
$ cd foo/
$ mkdir src/bin
$ mv src/main.rs src/bin/
$ cargo run --bin main  -- -- --write-mode=diff
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/main --write-mode=diff`
```

and the last line should instead say:

```
     Running `target/debug/main -- --write-mode=diff`
```

**Comment by patricksjackson** [comment]
This appears to be fixed in the latest nightly but not yet in stable.

Using @carols10cents repro steps:

```
$ cargo --version
cargo 0.26.0 (41480f5cc 2018-02-26)
$ cargo run --bin main  -- -- --write-mode=diff
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
      Running `target/debug/main --write-mode=diff`
$ rustup default nightly
$ cargo --version
cargo 1.27.0-nightly (0a1add2d8 2018-04-20)
$ cargo run --bin main  -- -- --write-mode=diff
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
      Running `target/debug/main -- --write-mode=diff`
```

**Comment by matklad** [comment]
@patricksjackson indeed! 

I've added a test for this in https://github.com/rust-lang/cargo/pull/5429
