### ISSUE TITLE
Possible values of OPT_LEVEL and DEBUG are not documented

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#2238]
The [build script documentation](http://doc.crates.io/build-script.html) only mentions existence of these variables in passing, and leaves it to the reader to guess their exact meaning and values.

I'd be nice to have a comprehensive reference of variables set by cargo, like this one:

https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html

**Comment by steveklabnik** [comment]
http://doc.crates.io/environment-variables.html is the more comprehensive list.

**Comment by pornel** [comment]
Oh, I haven't noticed that page. Thank you.
