### ISSUE TITLE
Linking fails on Ubuntu ARM

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2239]
For example, `"-l" "speexdsp"` results in:
````
note: /usr/bin/ld.gold.real: error: cannot find -lspeexdsp
````
It seems the system library path `/usr/lib/arm-linux-gnueabihf/` is not considered.

Is it because cargo is put off by this:

**`include /etc/ld.so.conf.d/*.conf`** in `/etc/ld.so.conf` instead of explicit paths?

**Comment by alexcrichton** [comment]
This looks like it may be a problem with local configuration or a local package rather than Cargo itself as Cargo doesn't deal with linkers or link paths. It may be the case that the right linker isn't being used or is perhaps being used for the wrong architecture, but that should be solvable through configuration.

Closing for now, but feel free to let me know if there's something I could do to help!

**Comment by petevine** [comment]
The correct path is not being considered which doesn't happen with gcc. The command line printed by Cargo contained `-l" "speexdsp` which according to my understanding is equivalent to `-lspeexdsp`.

Simply creating a symlink in `/usr/lib` solves this issue - are you saying it's solely down to a broken build script?

**Comment by alexcrichton** [comment]
Yeah this likely either comes down to a build script somewhere or perhaps the wrong linker being used

**Comment by petevine** [comment]
Could you elaborate on the wrong linker aspect? I made `ld.gold` the default on this system but it hasn't caused any problems so far. Thx.

**Comment by alexcrichton** [comment]
When cross compiling the system linker typically doesn't have the same search paths (or may not even be able to emit the specified architecture). Toolchains for cross-targets typically come with a `$target-ld` executable which is the appropriate linker to call for that cross compile.

**Comment by petevine** [comment]
Oh, you meant cross-compilation - nah, it's just a native Linux build and putting a symlink in `/usr/lib` was enough anyway.

**Comment by alexcrichton** [comment]
Oh is your host architecture `arm-linux-gnueabihf`? And the library you want to link to is located in `/usr/lib/arm-linux-gnueabihf`?

**Comment by petevine** [comment]
Yes, indeed :)

**Comment by alexcrichton** [comment]
Whoa, fascinating! In that case I wonder if `ld.gold` just has different search paths than `ld` perhaps? Either that or `gcc` itself is passing through the search paths for some compiles but not others? Does seem kinda fishy...

**Comment by petevine** [comment]
Thanks for the suggestions - I'll try investigating :)
