### ISSUE TITLE
Pass crate root to custom subcommands

### ISSUE THREAD

**Issue by JanLikar** [rust-lang/cargo#2244]
I believe most of the subcommand need the path to the crate's root, so this should be passed to subcommands on invocation. Would environment variables be an option?

**Comment by sfackler** [comment]
Finding the crate root is a one-line call to `cargo::util::important_paths::find_root_manifest_for_cwd`: https://github.com/sfackler/cargo-tree/blob/ebc89804becb489266c86d5bb376a21f78216dc2/src/main.rs#L146

**Comment by alexcrichton** [comment]
Yeah for now this is up to the subcommands as they may not all require crate roots (e.g. something like `cargo search`) so it's up to the subcommand to find the root. As @sfackler pointed out when linking to the cargo support library it should be easy enough to find.
