### ISSUE TITLE
Crate dependency with already present version

### ISSUE THREAD

**Issue by viraptor** [rust-lang/cargo#2246]
I've run a few times into a situation where I depend on two crates. Let's call them: A and A-helpers. A-helpers does something extra on top of A, but I need to use both apis.

But unless I make sure I'm listing the same version limit for A as A-helper does, I end up with errors like "expected struct `A::Context`, found a different struct `A::Context`". Since this can come back after each update, it gets a bit tedious.

I'd like to have a way to specify dependencies:
```
A-helpers = "1"
A = "use whatever A-helpers already uses"
```

Maybe I'm missing some existing functionality, but if not, this would be very helpful.

**Comment by alexcrichton** [comment]
Thanks for the report! For now I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/2064 as I believe it's basically the same issue in that case, there's a few underlying architectural problems here which expose the desire to have a version requirement like this, and that's becoming kinda the tracking issue for all this!

**Comment by ctsrc** [comment]
The referenced issue in turn has a lot of discussion and further links to other places. Searching for *rust use same crate version as dependency* led me to this one here and so it'd be useful if someone could state in a comment here whether this is now possible and if so, how.

**Comment by ctsrc** [comment]
I think this is the way to do it:

```
A-helpers = "1"
A = "*"
```
