### ISSUE TITLE
Don't recheck files for 'build' if they have already passed 'check'

### ISSUE THREAD

**Issue by White-Oak** [rust-lang/cargo#2248]
It would be really great to have a simmilar behavior to how `cargo build` works:
If `cargo check` has passed and no files have been changed since then — don't recheck them and compile directly.

I'm not sure if it's possible at all and at what cost it would be, since checking code is probably an intermidiate action. Also, `cargo-check` is an external subcommand.

But what brought this to my mind: if it was possible, it could really speed up compilation times when working in IDEs, since `cargo check` is run very often to lint files. And after a satisfying check to have an ability to build project quick would be really great.

**Comment by xamgore** [comment]
:+1:

**Comment by Dashed** [comment]
:+1: 

Are there plans for `cargo check` to be built into `cargo`? 

I'm using `cargo check` in combination with `cargo watch`: https://github.com/passcod/cargo-watch
which is useful when I'm subconsciously saving rust files, and then do a compilation step (i.e. `cargo build`) when output of `cargo check` looks fine.

**Comment by aNNiMON** [comment]
+1

**Comment by jonas-schievink** [comment]
> If `cargo check` has passed and no files have been changed since then — don't recheck them and compile directly.

Unfortunately, type checking (the slowest checking pass in most cases AFAIK) produces information needed by later passes in the compiler (mainly, translation).

Sounds like what you want is incremental compilation, which is currently being worked on. See rust-lang/rfcs#1298.
