### ISSUE TITLE
unable to reach cargo.io-index

### ISSUE THREAD

**Issue by peerzombie** [rust-lang/cargo#2249]
So lately i discovered rust and tried it out.
After following the ![Tutorial](https://doc.rust-lang.org/stable/book/guessing-game.html) the docs offered i came to the point of including rand. now, when i run `cargo build` ( or `cargo build --verbose` for that matter) i get the following error:
```
C:\Users\TheLazyAdmin\Documents\RustCode\guess_game>cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [2] failed to send request: Das Zeitlimit für den Vorgang wurde erreicht.
```
i tried reinstalling rust, and did it on 2 different networks. nothing of it helped.

**Comment by felixc** [comment]
Does this problem still happen? It could perhaps have been a temporary GitHub outage/connection problem?

**Comment by alexcrichton** [comment]
Yeah it's likely that this was an intermittent issue, so closing. Feel free to reopen if it happens again though!
