### ISSUE TITLE
Fetching git repositories via SSH makes cargo crash

### ISSUE THREAD

**Issue by muja** [rust-lang/cargo#2250]
How to reproduce:

First, append this in your .gitconfig:
```
  [url "git@github.com:"]
         insteadOf = https://github.com/
```

Then, run any cargo command (install, update, even build) - it will crash with a rather cryptic message of `failed to authenticate when downloading repository`.

**Comment by Jragonmiris** [comment]
Probably a duplicate of:

https://github.com/rust-lang/cargo/issues/1851

?

**Comment by alexcrichton** [comment]
Yeah I believe this is a dupe of https://github.com/rust-lang/cargo/issues/1851, but thanks for the report!
