### ISSUE TITLE
Support relative paths for registries

### ISSUE THREAD

**Issue by marcbowes** [rust-lang/cargo#2252]
I have a use case where I need a local registry. I currently do this by editing `.cargo/config` and specifying the absolute path to the registry:

``` toml
[registry]
index = "file:///Users/me/blah/registry/git"
```

Because the path is absolute, this means I can't really check in `.cargo/config` since the paths may differ for my peers. This has a couple of problems:
1. Without this file present, cargo doesn't work (because it won't have the custom registry). Cargo has become a standard integration point for editors, so this means that people can't even edit the project without having errors.
2. http://doc.crates.io/config.html - there are some options there I might want to check in that are specific to the project.

If I specify a relative path, e.g.:

``` toml
[registry]
index = "registry/git"
```

Then I get:

```
$ cargo build --verbose
failed to parse manifest at `/Users/..../Cargo.toml`

Caused by:
  invalid url `registry/git`: relative URL without a base
```

According to https://github.com/servo/rust-url/blob/2aa249b5bbc462e5582735bdae76a27acc9d70fd/src/lib.rs#L115, this can be fixed by adding a `base_url` to the `UrlParser` that is used in cargo/src/cargo/util/to_url.rs

---

Instructions to fix this added by @carols10cents:

- Check out the code from [this PR](https://github.com/rust-lang/cargo/pull/2253) 
- Rebase it on master, fix any git merge conflicts and make any updates to code that's changed a lot in the meantime
- Add some tests around the behavior in that PR 
- Resubmit!

**Comment by anhbakhia** [comment]
I apologize if I cause annoyance, I know this is an old issue.

I think it might be good if I add one similar example about using dependencies too. Currently Rust 1.32.0 doesn't work with local Git relative paths, like this:

```toml
[dependencies]
some-lib = { git='file:../../some-lib/', tag='...' }
```

So it would be great if you also consider that use case.

Thank you,

**Comment by fluffysquirrels** [comment]
@ghost,

I think that your Git relative path problem deserves its own issue, so just made https://github.com/rust-lang/cargo/issues/6859 . Hope that helps!

**Comment by fluffysquirrels** [comment]
I'm taking a look at this issue.
