### ISSUE TITLE
Update timestamp of output file even when nothing has to be done

### ISSUE THREAD

**Issue by lilred** [rust-lang/cargo#2254]
Sometimes it's handy to use GNU Make to drive Cargo, like so:

``` make
libfoo.a: src1.rs src2.rs
     cargo build
```

If I make a non-functional change to src1.rs, then its timestamp becomes more recent than libfoo.a. From then on, anytime I run `make`, `cargo build` is run. (Workaround: `make clean`.)

**Comment by alexcrichton** [comment]
This may be a rustc issue instead of a cargo issue, but is cargo not re-running the compiler?

**Comment by carols10cents** [comment]
This is pretty old and doesn't have any recent activity-- please reopen if this is still an issue and clarify about whether cargo is or is not rerunning rustc when a change is made to a file! Thank you!
