### ISSUE TITLE
"rerun-if-changed" in build script causes causes fingerprint error and extra rebuild

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/cargo#2261]
If a dependency contains the following build script:

```rust
fn main() { println!("cargo:rerun-if-changed=build.rs"); }
```

Then running `cargo build` twice in a row compile the dependency twice, instead of just once:

```
$ cargo build
   Compiling a v0.1.0 (file:///home/mbrubeck/src/test/cargotest)
   Compiling cargotest v0.1.0 (file:///home/mbrubeck/src/test/cargotest)
$ cargo build
   Compiling a v0.1.0 (file:///home/mbrubeck/src/test/cargotest)
   Compiling cargotest v0.1.0 (file:///home/mbrubeck/src/test/cargotest)
$ cargo build
$ 
````

Possibly related: the following message appears in the log output during the second build, but not the first or third build:

```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for a v0.1.0 (file:///home/mbrubeck/src/test/cargotest): local fingerprint type has changed
```

As reported by @cDlm on IRC, this affects the current version of the `glutin` crate. And here is a minimal test case for this issue: https://github.com/mbrubeck/cargotest

**Comment by mbrubeck** [comment]
cc #2134

**Comment by alexcrichton** [comment]
Note that you don't need to depend on the build script's source to re-trigger compiling the build script, Cargo does that automatically. That being said this probably shouldn't happen either way, so there may still be a bug.

**Comment by mbrubeck** [comment]
This happens for any value of `rerun-if-changed`. For example, `cargo:rerun-if-changed=src/lib.rs` triggers the same issue.

**Comment by alexcrichton** [comment]
Fixed by https://github.com/rust-lang/cargo/pull/2279
