### ISSUE TITLE
Build failure for libssh2 on Windows 10, MSYS2

### ISSUE THREAD

**Issue by jamesgraves** [rust-lang/cargo#2264]
I wasn't able to build cargo on Windows 10 64-bit, using MSYS2.

I checked out rust from git, and built it according to the instructions, and installed it into `/usr/local`.

For cargo, I followed the instructions in the README, and used this for configure:

    ./configure --local-rust-root=/usr/local

And then ran make.   Here's the end of the build:

       Compiling cmake v0.1.12
       Compiling curl-sys v0.1.29
       Compiling url v0.2.38
       Compiling libgit2-sys v0.3.8
       Compiling libssh2-sys v0.1.34
    Build failed, waiting for other jobs to finish...
    failed to run custom build command for `libssh2-sys v0.1.34`
    Process didn't exit successfully: `C:\msys64\usr\local\src\cargo\target\release\build\libssh2-sys-b1f216ef589edc64\build-script-build` (exit code: 101)
    --- stdout
    running: "cmake" "C:\\msys64\\home\\james.c.graves.jr\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.1.34\\libssh2" "-G" "MSYS Makefiles" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=/" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\msys64\\usr\\local\\src\\cargo\\target\\x86_64-pc-windows-gnu\\release\\build\\libssh2-sys-b1f216ef589edc64\\out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Release"
    
    --- stderr
    CMake Error: Could not create named generator MSYS Makefiles
    thread '<main>' panicked at '
    command did not execute successfully, got: exit code: 1
    
    build script failed, must exit now', C:\msys64\home\james.c.graves.jr\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.12\src\lib.rs:424
    
    Makefile:93: recipe for target 'cargo-x86_64-pc-windows-gnu' failed
    make: *** [cargo-x86_64-pc-windows-gnu] Error 101

I'm not sure if this is a cargo issue, or if it is a problem with libssh2.  I'm new to rust and cargo.

**Comment by alexcrichton** [comment]
Where did you install cmake from? I would expect that this generator would be pretty common among all cmakes...

**Comment by jamesgraves** [comment]
I just ran `pacman -S cmake`, so it is whatever currently installed by default with MSYS2.

**Comment by alexcrichton** [comment]
Oh right this is when I don't quite understand what's up with MSYS2 and whatnot. The `foo` packages typically aren't actually the ones you want, but rather `mingw-w64-{x86_64,i686}-foo`. So for example in this case the `cmake` package is somewhat broken but the `mingw-w64-x86_64-cmake` package is what you want.

I have no idea why this is the case :(

**Comment by jamesgraves** [comment]
OK, I installed that version of cmake, and uninstalled the plain `cmake` package using pacman.

The build ran to completion, and I was able to install it and it seems to work.  Excellent!

Is this something that people more familiar with MSYS2 are likely to know about already, or should this be mentioned in the documentation?

I did see a bunch of warnings during the compile like this:

    src\bin\bench.rs:64:25: 64:32 warning: private type in public interface (error E0446), #[warn(private_in_public)] on by default
    src\bin\bench.rs:64 pub fn execute(options: Options, config: &Config) -> CliResult<Option<()>> {
                                                ^~~~~~~
    src\bin\cargo.rs:155:22: 63:22 note: in this expansion of cmd! (defined in src\bin\cargo.rs)
    src\bin\cargo.rs:155:5: 155:27 note: in this expansion of each_subcommand! (defined in src\bin\cargo.rs)
    src\bin\bench.rs:64:25: 64:32 note: this lint will become a HARD ERROR in a future release!

Is this already known?  Should we create a separate issue for them?

Thanks for your help.

**Comment by alexcrichton** [comment]
Ah it looks like some new warnings are showing up on nightly which haven't been handled yet, feel free to open an issue about that.

I'm also honestly not sure if it's standard practice on MSYS2, but feel free to open an issue about the docs! (or send a PR yourself is also cool)
