### ISSUE TITLE
cargo run  --example checking

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2266]
User mistypes, leaves the computer, comes back to nothing. `Cargo` should do the check at the start.

````
$  cargo run --example helloworld.rs 
    Updating git repository `https://github.com/arthurprs/nix-rust.git`
    Updating git repository `https://github.com/arthurprs/tendril.git`
 Downloading encoding-index-japanese v1.20141219.5
 Downloading encoding-index-korean v1.20141219.5
 Downloading encoding-index-tradchinese v1.20141219.5
 Downloading promising-future v0.1.6
 Downloading twox-hash v0.1.1
 Downloading spin v0.3.4
 Downloading threadpool v0.1.4
 Downloading futf v0.1.1
 Downloading encoding-index-singlebyte v1.20141219.5
 Downloading redis v0.5.2
 Downloading url v0.5.2
 Downloading fnv v1.0.0
 Downloading miow v0.1.1
 Downloading linked-hash-map v0.0.7
 Downloading cfg-if v0.1.0
 Downloading debug_unreachable v0.0.6
 Downloading slab v0.1.3
 Downloading net2 v0.2.20
 Downloading encoding_index_tests v0.1.4
 Downloading void v0.0.5
 Downloading encoding v0.2.32
 Downloading fs2 v0.2.2
 Downloading mio v0.5.0
 Downloading encoding-index-simpchinese v1.20141219.5
 Downloading nix v0.4.2
 Downloading mac v0.0.2
 Downloading unreachable v0.0.2
 Downloading bytes v0.3.0
 Downloading sha1 v0.1.1

no example target named `helloworld.rs`
````

Has to be restarted with:
`$  cargo run --example helloworld`

 Maybe `cargo` could strip the trailing `.rs` automatically?

**Comment by alexcrichton** [comment]
It's possible for `.rs` to actually be in the name of an example, however, so there'd be no way to disambiguate? I personally would prefer to keep the meaning straightforward with an easy mapping of the command line argument to what's specified in the manifest itself.

**Comment by alexcrichton** [comment]
Now that being said I could imagine that a diagnostic "did you mean" would be helpful here

**Comment by petevine** [comment]
That was just an afterthought - a diagnostic would be more than enough. I use tab-completion on the other system so it's not a big problem. The issue is about detecting the name is wrong **before** starting the build process.

**Comment by alexcrichton** [comment]
Ah unfortunately can't detect a wrong name before downloading the source because the index doesn't contain as much information as the manifests in the downloaded source do

**Comment by petevine** [comment]
I can't say I understand the problem; if tab completion can point to a local file called `helloworld.rs` located in `examples` by simply stripping the `.rs` why can't cargo check for it as well? Are there non-local examples too?

**Comment by alexcrichton** [comment]
Oh right, this is a local package, not a remote one. Then we do indeed have all the names locally!

**Comment by alexcrichton** [comment]
I think this should be relatively easy to do, so tagging as E-easy and feel free to ask me for help!

**Comment by ryanq** [comment]
I'd like to take this one on.

**Comment by alexcrichton** [comment]
Sure thing @ryanq! If you have any questions feel free to each out to me (acrichto) on IRC or on here.

**Comment by petevine** [comment]
@alexcrichton 

Please reopen - the issue was about doing the check at the start; the last part, that the PR addressed, was just a usability suggestion.

**Comment by petevine** [comment]
Thanks. Cargo still goes to the net, updating git repos, which can take a long time before failing.

**Comment by ryanq** [comment]
The change I originally posted had done the check before dependencies were downloaded. It might be simple to move the generate_targets() call before the dependency resolution. I'll investigate that.

**Comment by ryanq** [comment]
@petevine Thanks for catching that. I lost sight of making cargo bail early and got focused on finding the suggestion.

**Comment by petevine** [comment]
Thanks @ryanq!
