### ISSUE TITLE
Per crate build.target-dir

### ISSUE THREAD

**Issue by mneumann** [rust-lang/cargo#2268]
It would be great to have something like:

```
# /home/mneumann/.cargo/config
[build]
target-dir = "/var/cargo/build/%P"
```

And when I build a cargo package in ```/home/mneumann/src/mypackage```, this would build it in ```/var/cargo/build/mypackage-1.0.0/target```. For example, the FreeBSD ports systems works like that in that it compiles it's packages in ```/usr/obj/ports/...```. It's a bit annoying especially regarding wasted space for backups when all the compiled crates are living on the same partition as the source. 

If this is a desired change, I am happy to try to implement it.

**Comment by alexcrichton** [comment]
I would personally be wary of inventing our own syntax for these strings here, so I wouldn't want to take action on this just yet. Is there anything wrong with just having a global build directory though?

**Comment by mneumann** [comment]
I made the wrong assumption that with a single build directory, building multiple projects will have collisions. But now, taking a closer look, I realize that in most cases, there is no problem. It's only troublesome if I have two projects that have binaries or examples with a colliding name, which I don't have atm.
