### ISSUE TITLE
assertion failed: checkout.is_fresh()

### ISSUE THREAD

**Issue by retep998** [rust-lang/cargo#2271]
`thread '<main>' panicked at 'assertion failed: checkout.is_fresh()', src/cargo\sources\git\utils.rs:174 `

A friend of mine ( @diamondo25 ) got this error while trying to build a project after pinning a git dependency to a specific revision with `rev = "v0.5.2"`.

Cargo version is `cargo 0.8.0-nightly (08da2f5 2015-12-21) ` using `x86_64-pc-windows-msvc`.

Possibly related to https://github.com/rust-lang/cargo/issues/1069

cc @alexcrichton

**Comment by alexcrichton** [comment]
Was there perhaps a concurrent `cargo` running in the background somewhere? It looks like this could get triggered in that case perhaps.

**Comment by alexcrichton** [comment]
This looks like it was probably just a case of concurrency, and with #2486 landed that should be fixed, so I'm gonna close.
