### ISSUE TITLE
make all error 101 on Ubuntu 14.04 

### ISSUE THREAD

**Issue by tiansiyuan** [rust-lang/cargo#2272]
https://github.com/rust-lang/rust-by-example/issues/693#event-511355523

make all
./setup-stage.sh
取出版本 134。
cargo run
Downloading regex v0.1.41
unable to get packages from source

To learn more, run the command again with --verbose.
make: *** [all] 错误 101

**Comment by alexcrichton** [comment]
Can you run with the `--verbose` flag? It would be useful to see some more error information here.

**Comment by tiansiyuan** [comment]
where to add this --verbose flag?

I tried to add it in Makefile: cargo --verbose run

I got the following with make all:

make all
./setup-stage.sh
取出版本 134。
cargo --verbose run
Invalid arguments.

Usage:
    cargo <command> [<args>...]
    cargo [options]
make: *** [all] error 1

**Comment by alexcrichton** [comment]
You'll want to do `cargo run --verbose`

**Comment by tiansiyuan** [comment]
Thanks and done.

make all
./setup-stage.sh
取出版本 134。
cargo run --verbose
 Downloading memchr v0.1.6
 Downloading rustc-serialize v0.3.16
unable to get packages from source

Caused by:
  Failed to download package `rustc-serialize v0.3.16` from https://crates.io/api/v1/crates/rustc-serialize/0.3.16/download

Caused by:
  Timeout was reached
make: *** [all] error 101

I think I have to use VPN to cross the GFW.

**Comment by alexcrichton** [comment]
Ah yes, in this case if a timeout is reached it may just mean that the timeout needs to [be increased](http://doc.crates.io/config.html#configuration-keys)
