### ISSUE TITLE
Cargo install --path is not working as expected?

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/cargo#2278]
First of all i'm not really sure which path should be specified.
Is it supposed to be root directory or toml file?

Both variants produce:
>E:\Downloads\Git\rust
> cargo install --path .\lazy-git-ext\
invalid path url `.\lazy-git-ext\`
E:\Downloads\Git\rust
> cargo install --path lazy-git-ext\
invalid path url `lazy-git-ext\`
E:\Downloads\Git\rust
> cargo install --path lazy-git-ext
invalid path url `lazy-git-ext`
E:\Downloads\Git\rust
> cargo install --path .\lazy-git-ext\Cargo.toml
invalid path url `.\lazy-git-ext\Cargo.toml`
E:\Downloads\Git\rust
> cargo install --path lazy-git-ext\Cargo.toml
invalid path url `lazy-git-ext\Cargo.toml`

Cargo 0.6.0 | Rust 1.5 | Win 10 x64

p.s. is cargo trying to resolve it as url?

**Comment by alexcrichton** [comment]
Ah this was fixed in 06bb0b28 which is part of Cargo 0.7.0, should be coming out soon though!

**Comment by DoumanAsh** [comment]
O. glad to hear it
