### ISSUE TITLE
Building libcore with cargo

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/cargo#2283]
It would be nicer if there was a way to build standard library crates with cargo.

This is especially important for libcore since there currently isn't a way to cross compile that (without also building all the standard libraries, which may not be supported on the target).

I suggest an way of having cargo build libcore into a sysroot (passed with `--sysroot=<path>`) so that crates can build against libcore using just `rustc --sysroot=<path> `

So for example with libcore having `use_sysroot = true` in `Cargo.toml`;
`cargo build --target=x86_64-pc-avery --sysroot=sysroot` would store libcore in `sysroot/lib/rustlib/x86_64-pc-avery\lib`

**Comment by alexcrichton** [comment]
Thanks for the report! There's bee quite a bit of discussion around this in the past, and the current place for this is actually a [current RFC](https://github.com/rust-lang/rfcs/pull/1133), so I'm gonna close this to centralize discussion over there. If that specific RFC is closed we can be sure to reopen an issue over here, however.
