### ISSUE TITLE
Cargo intercepts --version flags in third party subcommands

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#2286]
If a third party subcommand registers a --version flag and uses the `execute_main_without_stdin` infrastructure, the cargo crate will intercept `--version` and print its own version, rather than passing it through to to the subcommand main.

**Comment by alexcrichton** [comment]
Should be a relatively easy fix

**Comment by antonlarin** [comment]
The issue should be closed since it was fixed in #2336.
