### ISSUE TITLE
Cargo binary from crates.io should be updated

### ISSUE THREAD

**Issue by nodakai** [rust-lang/cargo#2288]
https://crates.io/install -> cargo 0.4.0-nightly (e0a82d6 2015-07-29) (built 2015-07-29)

https://static.rust-lang.org/dist/rust-1.5.0-x86_64-unknown-linux-gnu.tar.gz -> cargo 0.6.0-nightly (e1ed995 2015-10-22)

**Comment by alexcrichton** [comment]
I may be a bit confused, but which links did you click on with crates.io? The Linux download links give me `cargo 0.8.0-nightly (2c1426e 2016-01-15)` at least

**Comment by nodakai** [comment]
My bad, that must have been some proxy issue in my environment.  Confirmed `cargo 0.8.0-nightly (28a0cbb 2016-01-17)`.  Closing.

But ideally Cargo's tarballs should be named after Cargo binary's version.
