### ISSUE TITLE
cant download packages , its always time out issue

### ISSUE THREAD

**Issue by windyslove** [rust-lang/cargo#2289]
windys-OEM:~$ cargo install nickel -v
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading nickel v0.7.3
Failed to download package `nickel v0.7.3` from https://crates.io/api/v1/crates/nickel/0.7.3/download

Caused by:
  Timeout was reached

**Comment by alexcrichton** [comment]
You should probably just be able to increase the timeout via the [`http.timeout` configuration option](http://doc.crates.io/config.html#configuration-keys), and that should do the trick!

**Comment by windyslove** [comment]
but it goes well on windows PC in my company ，is any special setting need to be done under ubuntu linux ?

**Comment by alexcrichton** [comment]
Nah it may just be a slow network perhaps?

**Comment by windyslove** [comment]
well thanks you
