### ISSUE TITLE
Cargo should help devs have their tags in order.

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#2291]
This is inspired by: https://www.reddit.com/r/rust/comments/419pm5/psa_please_please_please_tag_your_git/cz0qz4y

Cargo already does a lot of git related things, why couldn't it automatically create annotated tags on `cargo publish`? Optionally it could make a `git push --tag`. Or it could go all the way generic and have a hooks for `cargo publish` so anyone can customize their `cargo publish` policy.

**Comment by jonas-schievink** [comment]
Duplicate of #841

**Comment by alexcrichton** [comment]
I agree this is a dupe, but thanks for the report!
