### ISSUE TITLE
'cargo update' results in unrelated(?) error with unrelated package

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/cargo#2293]
```sh
$ git clone git@github.com:servo/servo.git
$ cd components/servo/
$ cargo update -p "objc-foundation" --precise 0.0.4
    Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `objc` found (required by `servo-glutin`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: = 0.1.8
```

**Comment by SimonSapin** [comment]
FWIW, https://crates.io/crates/objc/ is a dependency of both servo-glutin and objc-foundation

**Comment by Ms2ger** [comment]
CC @alexcrichton

**Comment by alexcrichton** [comment]
This is likely some overly constrained portion of the graph elsewhere (e.g. some cascading update made this un-resolvable). I suspect that this is just https://github.com/rust-lang/cargo/issues/782 in disguise, so I'm going to close in favor of that.

Thanks for the report though!

**Comment by SimonSapin** [comment]
Do you have any advice on how to find out which part of the graph is over constrained, and how to resolve it?

**Comment by alexcrichton** [comment]
Unfortunately no as there have been very few reports of errors like this, but I suspect it is somewhat reconstructible from the logging output (albeit confusingly)

**Comment by frewsxcv** [comment]
I'm slightly skeptical of closing this in favor of #782; the latter seems to be an extremely vague issue with no concrete examples exemplifying the issue

**Comment by frewsxcv** [comment]
Added a minimal example: https://github.com/rust-lang/cargo/issues/782#issuecomment-172890688
