### ISSUE TITLE
cargo install error when no binary

### ISSUE THREAD

**Issue by azerupi** [rust-lang/cargo#2308]
When you run `cargo install` for a crate that contains no binary you get "An unknown error has occurred"

```
$ cargo install gtk  
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading gtk v0.0.6
An unknown error occurred

To learn more, run the command again with --verbose.

$ cargo install gtk --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading gtk v0.0.6
specified package has no binaries
```

You shouldn't have to run verbose mode to get the origin of the error, it's not user friendly.

Also the error could point out that lib crates should be added to the Cargo.toml and could eventually point to relevant docs.

**Comment by alexcrichton** [comment]
Are you sure that there wasn't an intermittent HTTP error to start out with? I can't reproduce this locally:

```
$ cargo install gtk
    Updating registry `https://github.com/rust-lang/crates.io-index`                                 
specified package has no binaries                                                                    
```

**Comment by azerupi** [comment]
I am not sure, it was posted on reddit and I just retransmitted it here. I
will test when I come home but if it was just temporary you can close it.

**Comment by azerupi** [comment]
It seems to work correctly for me too, I will close this issue. 
Sorry for the false positive!
