### ISSUE TITLE
Add a --sysroot option to build and rustc commands

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/cargo#2312]
When cross compiling you need to provide both a target and a sysroot (a place where all the target libraries can be found). Both cargo and rustc should provide a way to set these. rustc's `--sysroot` might be buggy or rust specific, see https://github.com/rust-lang/rust/issues/31180 and it does not pass it on to the linker.

**Comment by alexcrichton** [comment]
This sounds like it's a use case for [`RUSTFLAGS`](https://github.com/rust-lang/cargo/pull/2241) rather than its own dedicated flag. All of the cross-compiling linkers I've seen in the past auto-find their own sysroot so making this a first-class option may be too front-and-center for this?

**Comment by Zoxc** [comment]
This won't be very useful if you have to pass the C sysroot in `RUSTFLAGS` anyway.

**Comment by carols10cents** [comment]
This sounds like it can be closed. Please reopen if I'm wrong! 🌵
