### ISSUE TITLE
Improve output of machine oriented commands

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2313]
Several cargo sub commands use `JSON` for output, for example `read_manifest` and `metadata`. 

It would be nice to to customize this output (e.g. use TOML instead of JSON, redirect output to a file or control pretty printing). The relevant bit of code is [here](https://github.com/rust-lang/cargo/blob/f052d9953f23f55534f497cc70b2b106beefb988/src/cargo/lib.rs#L120-L131)

[Original discussion](https://github.com/rust-lang/cargo/pull/2196#issuecomment-174224951)

**Comment by matklad** [comment]
@alexcrichton what do you think about pretty printing json by default? 

We don't send JSON over the network, so there is no much gain in removing all whitespace. And with pretty printing it should be easier for humans to develop cargo-related tools.

**Comment by alexcrichton** [comment]
I'd personally prefer to have an alternate `pretty-json` output format, as this is in theory only really intended for pipelining between tools.

**Comment by carols10cents** [comment]
This seems like a concern that's outside of cargo's responsibilities.... for example, you can pipe compact JSON to something like [jq](https://stedolan.github.io/jq/) to get pretty JSON. Given that there hasn't been a mass clamoring for this in the past year and a half, I'm going to close this :)
