### ISSUE TITLE
warn on `cargo publish` if crate has github repo with out-of-date Cargo.toml

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/cargo#2322]
This may be a pie-in-the-sky idea, but... I have noticed (both on my own crates and those of other people) that sometimes one does a `crate publish` but forgets to do a corresponding `git push` of the source code back over to github.

This can be annoying for very small crates that don't have documentation (where i often resort to browsing the source code on github), since the github provided source is not in sync with the most up-to-date version on crates.io.

It might be nice if `cargo` were to warn in response to this.

(One might argue that there are issues, like "how would cargo know which branch to look at for the Cargo.toml", but we already have `rev` `tag` and `branch` options that it could look at.)

I would only want this to be a soft-warning, since there are plenty of use cases where one might want to publish to crates.io without updating github.com immediately (or at all).

**Comment by alexcrichton** [comment]
In general yeah there's quite a bit of git-management that could happen with integration with cargo publish. There's also [tag mangement](https://github.com/rust-lang/cargo/issues/841) and warning about [untracked files](https://github.com/rust-lang/cargo/issues/1597). 

This seems reasonable to me in terms of "nice git integration" to have.

**Comment by alexcrichton** [comment]
I think that this is now effectivley fixed with tracking untracked files in a git repo, so closing.
