### ISSUE TITLE
New arm target missing from cargo manifests

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2341]
The new `armv7` target hasn't been introduced in the crates ecosystem yet, [predictably]  (https://github.com/rust-lang/rust/pull/30948#issuecomment-176646360 ) resulting in errors like this:

````
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/libssh2-sys-0.1.34/lib.rs:10:1: 10:26 error: can't find crate for `openssl_sys` [E0463]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/libssh2-sys-0.1.34/lib.rs:10 extern crate openssl_sys;
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
````

BTW, @alexcrichton well spotted [fixing](https://github.com/rust-lang/rust/commit/ea31ff20f0437db5f77fc3e8d6d6f2efad74f887) the `.mk` file - I was going to open a PR myself.

I was also wondering if on the last line:
`CFG_GNU_TRIPLE_armv7-unknown-linux-gnueabihf := armv7-unknown-linux-gnueabihf` 

it was really necessary to differentiate from `arm-`?

**Comment by alexcrichton** [comment]
I don't think this is a particularly actionable bug in Cargo itself, it'll just take time for the target to be found on the stable/beta compilers. If you use a nightly compiler to build the target then everything should work just fine. Cargo itself has no knowledge of targets or target triples, so it's just the underlying compiler that needs to be updated here (or perhaps a stale build directory?)

**Comment by petevine** [comment]
I was using a bootstrapped compiler - otherwise I wouldn't even have the necessary rlibs to try this.

I'm well aware cargo itself doesn't know about targets, etc; when I jokingly wrote about "telling cargo" I meant stuff like this:

https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/Cargo.toml#L39

or this:

https://github.com/tomaka/glutin/blob/master/Cargo.toml#L96

So I meant you probably had the tools to automatically fix the affected crates.

**Comment by alexcrichton** [comment]
Oh yeah for those you can just send PRs to update them (or wait for the `cfg`-in-dependencies to get implemented)
