### ISSUE TITLE
Test cases should not modify the host system

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/cargo#2345]
Currently, some of the test cases modify the git config (e.g. `finds_author_git` in `tests/test_cargo_new.rs`). This is not nice :cry:.

**Comment by alexcrichton** [comment]
It's a bug that this test is modifying global configuration, the reset of `$HOME` should in theory tell git where it should be modifying this. Does git read some other environment variables to figure out where the global configuration should go?

**Comment by Stebalien** [comment]
It uses `XDG_CONFIG_HOME`. The test suite should also set `GIT_CONFIG_NOSYSTEM`.

According to the manual

> GIT_CONFIG_NOSYSTEM
> Whether to skip reading settings from the system-wide $(prefix)/etc/gitconfig file. This environment variable can be used along with $HOME and $XDG_CONFIG_HOME to create a predictable environment for a picky script, or you can set it temporarily to avoid using a buggy /etc/gitconfig file while waiting for someone with sufficient permissions to fix it.

**Comment by alexcrichton** [comment]
Whelp

**Comment by Stebalien** [comment]
Thanks!
