### ISSUE TITLE
Can't not upload ffi binding package which does not have link attribute

### ISSUE THREAD

**Issue by Ginurx** [rust-lang/cargo#2346]
I wrote a binding for zeromq, but have problem to upload the package.
I declared ffi functions without link attribute, 
because in order to build it on Windows I had to specify linkage info in build script.

cargo reported me ``` error: unresolved name `..................``` after typing cargo package.
While the package can be successfully built by `cargo build` and `cargo test`

[repo](https://github.com/Ginurx/zmq-rs)

**Comment by alexcrichton** [comment]
This may have just been an intermittent error, and I think the fact that this is an FFI binding or anything to do with the "link attribute" may be a red herring.

Can you gist the full error and/or transcript of what happened?

**Comment by Ginurx** [comment]
Here is the build log
[build.txt](https://github.com/rust-lang/cargo/files/114031/build.txt)

[https://github.com/Ginurx/zmq-rs](https://github.com/Ginurx/zmq-rs)

These error only show up when running`cargo package`, anyway

**Comment by alexcrichton** [comment]
Ah this looks like it's just a standard compile error. When publishing to crates.io all path dependencies are rewritten to crates.io dependencies (e.g. the dependency on `zmq-sys`), so you may need to publish `zmq-sys` before publishing `zmq` to ensure the updated bindings have all made their way to crates.io.

Let me know if that doesn't work out though!
