### ISSUE TITLE
Add guide to maintaining a quality crate.

### ISSUE THREAD

**Issue by AndrewBrinker** [rust-lang/cargo#2349]
Per https://github.com/rust-lang/crates.io/issues/249, I have started work on a guide to maintaining a quality crate. Right now it's in the brainstorming phase, and I will soon start contacting crate maintainers to solicit input.

The current work-in-progress document may be found here: https://github.com/AndrewBrinker/crate-guide

The goal is to have a document of best practices that people can be pointed to, and that can codify certain community practices for crate creation and maintenance based on input and ideas from the Rust community.

cc @steveklabnik

**Comment by killercup** [comment]
You might be interested in https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries/ :smile:

**Comment by AndrewBrinker** [comment]
Thanks! Those are some fantastic ideas.
