### ISSUE TITLE
cargo bench --no-run doesn't work properly

### ISSUE THREAD

**Issue by debris** [rust-lang/cargo#2350]
according to *--help* `cargo bench --no-run` should *Compile, but don't run benchmarks*, but it runs them.

cargo --version:

```
cargo 0.9.0-nightly (c4c6f39 2016-01-30)
```

rustc --version -v:

```
rustc 1.8.0-nightly (094c5b0d6 2016-01-31)
binary: rustc
commit-hash: 094c5b0d61a0fb19a1cb94dddd6f59a975089b4b
commit-date: 2016-01-31
host: x86_64-apple-darwin
release: 1.8.0-nightly
```

**Comment by steveklabnik** [comment]
Hm, trying this out in the `semver` crate locally ignores all of the tests. Do you have a sample crate which does this?

**Comment by debris** [comment]
sure. https://github.com/debris/cargo-bench-testrepo

**Comment by steveklabnik** [comment]
Ah, I see what's going on here. `semver` has no bench tests, so they were ignored for that reason, not because of the `--no-run`. Sigh. Sorry.

**Comment by alexcrichton** [comment]
Gah oops! Looks like it's just missing [this check](https://github.com/rust-lang/cargo/blob/7330169feb3c2e7beb194fba10f2713699fd9396/src/cargo/ops/cargo_test.rs#L20).

Should be a pretty easy bug for anyone interested in working on Cargo!
