### ISSUE TITLE
Crate DAG is not respected when filling in -L flags

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#2354]
Right now when Cargo passes `-L` flags to the compiler from the output of build scripts, the crate DAG is not preserved. For example, if crate A links against path `pathA`, crate B links against `pathB`, and B depends on A. Cargo will compile B like:

```
rustc b/src/lib.rs -L native=pathA -L native=pathB
```

Instead it should pass `pathB` first and in general use a topological ordering to ensure that more relevant paths come first. 

This was [discovered by Servo](https://github.com/servo/servo/pull/9314) where a native library was being picked up from /usr/lib even though it was properly compiled into the build directory. The /usr/lib version wouldn't link while the build directory one was the correct one to use.

**Comment by larsbergstrom** [comment]
Awesome, thanks for jumping on this so quickly!
