### ISSUE TITLE
move read-manifest into metadata?

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2356]
@alexcrichton in the metadata PR we've discussed that we might want to deprecate `cargo read-manifest` and provide similar functionality with `cargo metadata --no-deps`:  https://github.com/rust-lang/cargo/pull/2196#issuecomment-174408391

Now I'm not sure if this is a good idea: `cargo read-manifest` works fine, and I don't see any real benefit in moving it to `metadata`. 

But if you think that we should do this, I'll be glad to send a PR :)

**Comment by alexcrichton** [comment]
I do think that we'll want to deprecate `cargo read-manifest` eventually, but we probably want to wait for `cargo metadata` to hit stable Rust first. We can message out that `read-manifest` is being deprecated and we can also print a warning if the command is run.
