### ISSUE TITLE
Allow specifying crate-type on examples

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#2358]
I'm working on a crate that is specifically designed to be used in libraries. As such, I want to include some example libraries. It is not currently possible to have cargo build these, as the `crate-type` is ignored in the `[[examples]]` section.

**Comment by alexcrichton** [comment]
In theory, though, you could have the whole example with just a `fn main() {}` at the bottom, though, right?

**Comment by jethrogb** [comment]
That would work if this crate can be linked into an executable, which it can't. I need to specify the crate type so that the linker gets invoked correctly.

**Comment by alexcrichton** [comment]
I guess I'm a little confused on the use case here, can you elaborate a little more on what use case you have in mind?

That being said this seems pretty innocuous to add support for.

**Comment by alexcrichton** [comment]
Also tagging as E-easy as this should be pretty approachable!

**Comment by jethrogb** [comment]
> I guess I'm a little confused on the use case here, can you elaborate a little more on what use case you have in mind?

When trying to link this crate+this example, there will be unresolved symbols (by design). This is fine for a library, but not for an executable.

**Comment by alexcrichton** [comment]
Ah ok, that makes sense to me!

**Comment by KalitaAlexey** [comment]
I am working on it.

**Comment by retep998** [comment]
This would also be quite useful with `cdylib` and `staticlib` crate types.
