### ISSUE TITLE
Finish implementing `cargo config` and related support

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#2362]
Configuration in Cargo initially had a relatively grand vision, but much of it was unfortunately never implemented. This issue should help track finishing this support as well as explaining what it is intended to be!
### A `cargo config` subcommand

It was initially intended to have a `cargo config` subcommand ala `git config` or `bundle config`. Configuration values could be read/written through this interface to the various locations on the system as need be.

An example of this would be Bundler's [`bundle config`](http://bundler.io/v1.2/bundle_config.html) command.

The major blocker for this is being able to read a TOML file, modify some aspects of it, and then write it back to the filesystem. This should crucially preserve aspects such as comments, formatting, etc. Today we cannot do this.
### Environment variables for configuration

Right now we've got a [smattering of environment variables](http://doc.crates.io/environment-variables.html#environment-variables-cargo-reads), but it's somewhat inconsistent in terms of what's an environment variables, what's a command line option, and what's a configuration option. 

I believe it was originally intended that environment variables and configuration options should be one-and-the-same. All configuration options should have a mapping to an environment variable which provides the ability to read/write that field. For example [Bundler has this as well](http://bundler.io/v1.2/bundle_config.html#configuration_keys).

**Comment by dwijnand** [comment]
So looks like this is blocked on the switch to `toml_edit`.

**Comment by ehuss** [comment]
I have put together a proposal for the design of `cargo config` here: <https://hackmd.io/@ehuss/rkjp32Fg_>

@rust-lang/cargo FYI, if you have a chance to read and maybe give feedback.

**Comment by alexcrichton** [comment]
Thanks for typing this up @ehuss! 

My initial reaction was that I was wondering if we could do something `git`-like where `cargo config the-key` would work for fetching and (in the future) `cargo config the-key the-value` would work for setting. After reading over the references at the end of your notes, though, I see that it's also quite common nowadays to use subcommands. Given that and how adding `cargo config the-key` would be backwards-compatible I think it's fine to use the subcommands for now.

Otherwise I thought your specification looked great. I like the multiple output options which should be easy enough for us to implement and should help make it a relatively powerful tool even right-out-the-gate.

The other thought I had reading it was towards the end about alternative ways of configuring things, e.g. `RUSTC` vs `build.rustc`. I would personally think that we should reimplement Cargo internally to not have these special one-off environment variables but instead have them built-in to `Config` loading. For example `RUSTC`, `CARGO_BUILD_RUSTC`, `build.rustc` would be the order of precedence for checking what `rustc` to use. (similarly for other keys where possible). I'm not sure that this would fit 100% cleanly into our configuration with no breakage, but I think it'd be great to move in that direction at least.
