### ISSUE TITLE
Manifest option publish = false seems to have no effect

### ISSUE THREAD

**Issue by florianjacob** [rust-lang/cargo#2364]
I just updated the [manifest of qmlrs](https://github.com/cyndis/qmlrs/blob/9a7de1d9547e74cbb6055b1fb19214a7bc8390ed/Cargo.toml) to prepare for an eventual cargo upload, including `publish = false` as [described in the manifest documentation](http://doc.crates.io/manifest.html#the-publish--field-optional).

To see whether everything was done right, I thought I could do a dry-run:
```
cargo publish
```
Which worked a little too well. :laughing:
The result is now https://crates.io/crates/qmlrs/

It doesn't hurt much in our case, but it seems like the `publish = false` option had no effect at all. Did I use it the wrong way, or is this a bug?

**Comment by alexcrichton** [comment]
What version of Cargo did you use to publish? This feature was added recently and hasn't made it out to the stable release just yet.

**Comment by florianjacob** [comment]
In that case, that's probably the explanation. :smile: I used cargo 0.7.0-nightly (1af03be 2015-12-08) (the one that comes with multirust stable 1.6.0).

**Comment by alexcrichton** [comment]
Ah ok, thanks for the report regardless!
