### ISSUE TITLE
Supported Rust versions & dependencies

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#2368]
https://users.rust-lang.org/t/rust-version-support-in-library-crates-best-practices/4405/7
> One reason to stay on older Rust is if you plan on becoming a dependency of Cargo; it has picked 1.2, IIRC, as its minimum version.

Well, I wasn’t aware of that. rust-url v0.5.4 fails to build on 1.2 because it uses `Iterator::ne` which is apparently stable since 1.5.

rust-url master uses `rustc-test` (for data-driven tests) which depends on the `term` crate, which fails to build on 1.2 for reasons I don’t understand right now.

In the in-progress rewrite that I want to become rust-url 1.0 I also use `std::str::Chars::as_str`, added in 1.4.0.

All of this can (probably?) be worked around with, but:

* If supporting old versions of Rust is a requirement for Cargo dependencies, the maintainers of said dependencies need to know about it :)
* Is it really worth it? Is anyone stuck on 1.2 and can’t upgrade? (This goes back to the discussion linked above.)

**Comment by durka** [comment]
[Not anymore, apparently](https://github.com/rust-lang/cargo/commit/ca1377214a9b1022dce4ccfd92049f35075fbf5e) (linked further down in that thread).

**Comment by steveklabnik** [comment]
Yes, it was changed.

**Comment by alexcrichton** [comment]
Yes this was a pretty arbitrary decision that just didn't work out. As @durka mentioned the information is slightly out of date, as of https://github.com/rust-lang/cargo/pull/2319 Cargo just builds on stable/beta/nightly.

If there is a request for an older version we can deal with it then, but none has ever come up and I'm not sure if it every will come up!

**Comment by SimonSapin** [comment]
Sounds good, thanks.
