### ISSUE TITLE
'cargo doc --open' should have warning if web browser can't be determined

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/cargo#2371]
https://github.com/rust-lang/cargo/blob/3e285ce32317f79439b939df1d7b7b3e4268cbd8/src/cargo/ops/cargo_doc.rs#L63-L82

If all those `match`s fail, it might be helpful if we had an error/warning message instead of silently failing

**Comment by frewsxcv** [comment]
Even though it's unlikely, it might be helpful to have a message in the OSX and Windows cases too

**Comment by alexcrichton** [comment]
Makes sense to me!

**Comment by TheNeikos** [comment]
Would a check for $BROWSER also be something that is accepted? It would take priority over the others as it is set explicitly by the user.
