### ISSUE TITLE
cargo doc --open does nothing a binary crate

### ISSUE THREAD

**Issue by hfiguiere** [rust-lang/cargo#2372]
cargo doc --open does nothing a binary create

ie it generate some stuff but never opens it.

IMHO it should

1. at least report an error that it is binary create
2. better, it should generate documentation, still and open it.

**Comment by frewsxcv** [comment]
Related to https://github.com/rust-lang/cargo/pull/1533

**Comment by hfiguiere** [comment]
looks like it

**Comment by alexcrichton** [comment]
Oh dear, sounds bad! Should be pretty easy to tackle though

**Comment by hfiguiere** [comment]
Cargo tries to open the index.html file that isn't being created.

**Comment by hfiguiere** [comment]
The file is ````target/doc/<CRATE>/index.html````

**Comment by JIghtuse** [comment]
Looks like it is fixed.

**Comment by alexcrichton** [comment]
Thanks @JIghtuse!
