### ISSUE TITLE
Docs for `PROFILE` environment variable are confusing

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2374]
[Here](http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) it is said that PROFILE is the name of the profile currently being built. However, for the `dev` profile, the value "debug" is [used](https://github.com/rust-lang/cargo/blob/3e285ce32317f79439b939df1d7b7b3e4268cbd8/src/cargo/ops/cargo_rustc/custom_build.rs#L110)

Kinda related to #2373

**Comment by pornel** [comment]
I think root of the problem is that `profile.dev` is an odd name for what everyone calls debug. 

There's a similar inconsistency that `profile.release` builds in `target/release`, but `profile.dev` builds in `target/debug`.

**Comment by hobofan** [comment]
related/duplicate: #2084

**Comment by alexcrichton** [comment]
Aha indeed!
