### ISSUE TITLE
Have a more meaningful error message for third party subcommands exiting unsuccessfully

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/cargo#2378]
Currently it prints `An unknown error occurred`.

An example where this is surprising, with [`cargo-check`](https://crates.io/crates/cargo-check):

```
$ tmp=$(mktemp -d) && cd $tmp
$ echo "this-=:[won't-parse[]" > Cargo.toml
$ cargo check
failed to parse manifest at `/tmp/tmp.ySuwR73Jbz/Cargo.toml`

Caused by:
  could not parse input as TOML
Cargo.toml:1:7-1:8 expected a value

An unknown error occurred

To learn more, run the command again with --verbose.
```

I think "Third party subcommand `cargo check` failed" or something like that would be good.

**Comment by kamalmarhubi** [comment]
Or "... exited unsuccessfully". Even when `cargo check` doesn't hit config errors, it terminates with non-zero status if it found issues, and saying it "failed" would also be a bit odd.

**Comment by alexcrichton** [comment]
Sounds reasonable to me! The location for this error I believe is  [here](https://github.com/rust-lang/cargo/blob/3e285ce32317f79439b939df1d7b7b3e4268cbd8/src/bin/cargo.rs#L200).
