### ISSUE TITLE
Deleting target/doc doesn't first doc regeneration

### ISSUE THREAD

**Issue by hfiguiere** [rust-lang/cargo#2379]
* Delete ````target/doc````
* Run ````cargo doc --no-deps````

Observed:
Nothing happens but ````target/doc```` is recreated and is empty

Expected:
Doc is all rebuilt.

**Comment by hfiguiere** [comment]
This is on rust nightly.

**Comment by alexcrichton** [comment]
Ah I think right now the "freshness" to see whether we re-run a target is currently only computed from whether the source change, but should be easy enough to add a check that at least `index.html` exists!
