### ISSUE TITLE
Add an install.rs that lets a file perform installation setup, as well as a permanent installation outdir

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#2386]
Currently, `cargo install` builds a binary using the regular build script and copies it to `.cargo/bin`.

In this process we lose the outdir. Which makes sense, since usually that's only needed for compilation.

However, some binaries may need to do extra work on installation, as well as store some data in an output dir. It would be nice if `cargo install` would run a specified `install.rs` which has access to an `$INSTALL_OUT_DIR` variable which is a directory under `.cargo/bin` which is deleted if empty after installation.

This, for example, makes it possible to run `cargo install rust-clippy` (clippy needs a place to stash the compiled plugin).

**Comment by mbrubeck** [comment]
See also #545.

**Comment by Luthaf** [comment]
I think this could be a solution for both #545 and #2729.

Do we need a full RFC for this? If so, should the rfc go to the main rust-lang/rfcs repository?

**Comment by joshtriplett** [comment]
Please see https://github.com/rust-lang/rfcs/2376 for an RFC proposal on this.

**Comment by zslayton** [comment]
> Please see https://github.com/rust-lang/rfcs/2376 for an RFC proposal on this.

Updated link: https://github.com/rust-lang/rfcs/pull/2376

**Comment by epage** [comment]
As this is a specific solution to the problem in #2729, I'm closing in favor of #2729.  If I missed something about that and we should keep this open, feel free to speak up!
