### ISSUE TITLE
Feature request: read settings from environment variables as well as command line

### ISSUE THREAD

**Issue by edunham** [rust-lang/cargo#2395]
In the Rust build system, all actual calls to Cargo are buried within several layers of scripts, but it's easy to set environment variables. If others try to automate the builds of Rust projects that use Cargo, they may encounter similar challenges. 

In the case that caused me to file this issue, it would be convenient for Cargo to read a var like `CARGO_VERBOSE` instead of only the command-line `--verbose` when deciding how much debug info to print.

**Comment by alexcrichton** [comment]
Ah this was implemented in #2398, yay!
