### ISSUE TITLE
Build script output shouldn't be completely in red 

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/cargo#2401]
Hi there,

if the build script fails, cargo prints it's output -- sadly completely in red. It looks like:

![red](https://cloud.githubusercontent.com/assets/7419664/13199449/cacc8ca6-d825-11e5-819b-9cfb2f5dd8bc.png)

But it's of course useful to format the output specifically to make it more readable, like so:

![color](https://cloud.githubusercontent.com/assets/7419664/13199456/f2f1be0e-d825-11e5-97df-ffbedb3911b2.png)

I _assume_ that `cargo` saves the output to a string, which is printed only if the build script exited with a non 0 status. In this case, restoring colors could be difficult. But I'd like to have nice build script output...

**Comment by alexcrichton** [comment]
Yeah the UI here unfortunately isn't great, I've long since wished we could do better! This is somewhat related to https://github.com/rust-lang/cargo/issues/1106 as well.

Unfortunately capturing colorization would only work on Unix, but it may just be a case where we should do the best we can on each platform.

**Comment by LukasKalbertodt** [comment]
Or we could provide some kind of API, that the build script can call to get access to stdout. It would be some "annoying" synchronization between processes, but it could work...

Making it possible on Unix alone would be fine by me, too ;)

**Comment by sbeckeriv** [comment]
The error messages are no longer in red on master. It does not fix the display of the original color of the message.   
 

Related pull request https://github.com/rust-lang/cargo/pull/2421

**Comment by carols10cents** [comment]
> The error messages are no longer in red on master.

Sounds like this is fixed, please reopen if I'm incorrect!
