### ISSUE TITLE
Cargo fails to update registry 

### ISSUE THREAD

**Issue by Awarua-** [rust-lang/cargo#2403]
I get the follow error when running cargo install, upgrade and build commands

cargo install -v racer
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [4/-1] Corrupted loose reference file: HEAD

**Comment by alexcrichton** [comment]
Interesting! Maybe a previous operation corrupted the index by accident? You should be able to fix this by `rm -rf $CARGO_HOME/registry/index`, but that shouldn't be necessary in theory.

**Comment by Awarua-** [comment]
Hmm I deleted the index at that does seem to have fixed it, I wonder if its corrupted in the latest windows GNU distribution of Rust or it could just be my system.

**Comment by durka** [comment]
I ran into this error today. `registry/src` was apparently also corrupted. Removing them both convinced `cargo build` to start building, but IMO cargo should know how to recover from this error, or at least continue without updating the registry as a fallback.

**Comment by alexcrichton** [comment]
@durka hm so the corruption you ran into wasn't the git index, it was the unpacked tarballs?

**Comment by durka** [comment]
@alexcrichton well the index was definitely corrupted, and I had to delete it to get past the error shown here. But then it started complaining that it "couldn't get packages from source" because the Cargo.toml was corrupted, and when I checked the Cargo.toml it was complaining about, it sure was empty. I don't know if it was a crate that was already in the cache or a new one that didn't download well. After deleting the src directory the build completed.

**Comment by alexcrichton** [comment]
Interesting! I'll take another look at the index updating code to ensure it handles corruption, and we can just keep an eye out for `src` corruption as well (as it in theory is written in a way that it doesn't happen)

**Comment by przygienda** [comment]
happened to me today as well. no warning

**Comment by vishalsodani** [comment]
Suddenly happened to me on Windows 7. I deleted _registry/index_ folder and then cargo build started working again! Relief!

**Comment by simonsan** [comment]
Happened to me as well today as battery was empty during `cargo install-update -a` building process. Deleting the `index` directory fixed it, though I think `cargo` should be able to recover from this. Could this be reopened? @alexcrichton

**Comment by Eh2406** [comment]
I don't think there's context from fore years ago that will be helpful. @simonsan Just open a new issue describing your problem.

**Comment by simonsan** [comment]
> I don't think there's context from fore years ago that will be helpful. @simonsan Just open a new issue describing your problem.

@Eh2406 Would feel like a duplicate though, because I would write exactly the same as in this issue. `Cargo fails to update registry when index is corrupted` and that cargo should be able to recover from it. :/ So not sure if a new issue i the solution here.
