### ISSUE TITLE
Consider no matching tests a failure

### ISSUE THREAD

**Issue by sbeckeriv** [rust-lang/cargo#2410]
Hello,

I was running a test to watch it fail but it was not. It turns out I typed the test wrong. It seems like that if a test name is provided but not found it should be a failure or at least a warning.

`
cargo test test_something_that_is_typo
` 
Thoughts?
Becker

Checked on version 0.7.0 and 0.9.0

**Comment by alexcrichton** [comment]
Ah unfortunately Cargo doesn't have a lot of information in this regard, it just forward the argument `test_something_that_is_typo` to the underlying binary which chooses how to interpret it. Along those lines perhaps this issue would be more appropriate in rust-lang/rust against libtest?

**Comment by sbeckeriv** [comment]
thanks! I will move it.
