### ISSUE TITLE
.cargo/config paths doesn't affect link line.

### ISSUE THREAD

**Issue by ehiggs** [rust-lang/cargo#2412]
If we add a `.cargo/config` file with a `paths` variable, it doesn't appear to affect the link line.

To reproduce: 

```
$ cd /tmp
$ cargo new linkline-test
$ cargo new other-crate
$ cd linkline-test
$ mkdir .cargo
$ echo paths=[\"/tmp/other-crate\"] > .cargo/config
$ cargo build --verbose
   Compiling linkline-test v0.1.0 (file:///tmp/linkline-test)
     Running `rustc src/lib.rs --crate-name linkline_test --crate-type lib -g --out-dir /tmp/linkline-test/target/debug --emit=dep-info,link -L dependency=/tmp/linkline-test/target/debug -L dependency=/tmp/linkline-test/target/debug/deps`
```
This is missing a path to `/tmp/other-crate` where I may have a `.so` for the crate to link. e.g. `paths=[/home/myusername/.local/lib']` would be something that should work for users with installs local to their user account.

**Comment by ehiggs** [comment]
`strace` suggests that the file is found and read:
```
$ strace -f cargo build --verbose 2>&1 | fgrep '.cargo/config'
stat("/tmp/linkline-test/.cargo/config", {st_mode=S_IFREG|0664, st_size=27, ...}) = 0
open("/tmp/linkline-test/.cargo/config", O_RDONLY|O_CLOEXEC) = 3
stat("/tmp/.cargo/config", 0x7ffdb815ba30) = -1 ENOENT (No such file or directory)
stat("/.cargo/config", 0x7ffdb815ba30)  = -1 ENOENT (No such file or directory)
```

**Comment by alexcrichton** [comment]
Ah this is actually intended behavior of the `paths` configuration, it's only meant for Cargo to read to learn about crate overrides. To get linker arguments propagated you'll need to either use [build scripts](http://doc.crates.io/build-script.html) or [build script overrides](http://doc.crates.io/build-script.html#overriding-build-scripts) in `.cargo/config`. Let me know if you run into any snags though!

**Comment by ehiggs** [comment]
Ok, this requires that I have the following in my `Cargo.toml`:
```
links=somelib
build=build.rs
```
With `build.rs`:
```
fn main () {}
```

And `.cargo/config`:
```
[target.x86_64-unknown-linux-gnu.somelib]
rustc-link-search = ["/home/ehiggs/.local/lib"]
rustc-link-lib = ["somelib"]
```

As simple as 1,1,2. And if I want to link multiple libraries, I need to wrap each one it's own crate? This is a pretty onerous solution for simply telling Cargo that I also keep libraries in other places. I mean, I can also (and already do as a workaround) use `LIBRARY_PATH`, but it makes more sense to just let us add a library path in the `.cargo/config`.

**Comment by alexcrichton** [comment]
Yeah you can either do that for all crates at once or you can do a crate-per-lib (it's up to you). This is a little unergonomic to do at large because it's a pretty strong antipattern in Rust today. This basically means that the build can only succeed on your one machine in one particular configuration, which is counter to Cargo's "reproducible builds" goal

**Comment by norru** [comment]
Just tripped on this problem. Any progress?

**Comment by ehiggs** [comment]
@norru, I think I work around this by just pulling in the crates I depend on as a vendorised crate in-tree with my other work. i.e. using workspaces.

**Comment by norru** [comment]
@ehiggs it's one hell of a workaround. No, thanks :)

**Comment by ehiggs** [comment]
@norru, sure. @alexcrichton wrote a tool to do it:

https://github.com/alexcrichton/cargo-vendor

**Comment by norru** [comment]
Sounds interesting, but AUGH! It's even more "nope" :D
