### ISSUE TITLE
Add ability to add dependency with version from another dependency

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/cargo#2413]
There is crate *A*. There is crate *B*.

Crate *A* depends on *B* and uses it. It exports some methods those accepts types from *B*.

I use crate *A*. To work with crate *A* I also depends on *B*, but I cannot write
```
use B::something;
```
Also I cannot write
```
extern crate B;
```
Before that I must add to Cargo.toml
```
[dependencies]
B = "here is version"
```
But I want version which is required by *A*. How to do it?

**Comment by alexcrichton** [comment]
Thanks for the report! This has been [reported before](https://github.com/rust-lang/cargo/issues/2246), and I [closed that](https://github.com/rust-lang/cargo/issues/2246#issuecomment-170631200) in favor of https://github.com/rust-lang/cargo/issues/2064. Solving that will end up solving this as well!
