### ISSUE TITLE
Inconsistency about when each buildscript env var is set

### ISSUE THREAD

**Issue by dikaiosune** [rust-lang/cargo#2417]
On the [environment variables docs page](http://doc.crates.io/environment-variables.html), the example of using a cargo environment variable suggests using the `env!` compile-time macro:

```rust
let version = env!("CARGO_PKG_VERSION")
```

And below, a series of environment variables are specified for use in buildscripts. However, using the example from the top of the page doesn't work for all of them:

```rust
// build.rs
fn main() {
    // both of these will compile on 2016-02-25
    let out_dir = env!("OUT_DIR");
    let manifest_dir = env!("CARGO_MANIFEST_DIR");

    // none of these will compile on 2016-02-25
    let target = env!("TARGET");
    let host = env!("HOST");
    let num_jobs = env!("NUM_JOBS");
    let opt_level = env!("OPT_LEVEL");
    let debug = env!("DEBUG");
    let profile = env!("PROFILE");
}
```

```
$ cargo build
   Compiling demo v0.1.0 (file:///home/adam/rust-projects/demo)
build.rs:7:18: 7:32 error: environment variable `TARGET` not defined
build.rs:7     let target = env!("TARGET");
                            ^~~~~~~~~~~~~~
build.rs:8:16: 8:28 error: environment variable `HOST` not defined
build.rs:8     let host = env!("HOST");
                          ^~~~~~~~~~~~
build.rs:9:20: 9:36 error: environment variable `NUM_JOBS` not defined
build.rs:9     let num_jobs = env!("NUM_JOBS");
                              ^~~~~~~~~~~~~~~~
build.rs:10:21: 10:38 error: environment variable `OPT_LEVEL` not defined
build.rs:10     let opt_level = env!("OPT_LEVEL");
                                ^~~~~~~~~~~~~~~~~
build.rs:11:17: 11:30 error: environment variable `DEBUG` not defined
build.rs:11     let debug = env!("DEBUG");
                            ^~~~~~~~~~~~~
build.rs:12:19: 12:34 error: environment variable `PROFILE` not defined
build.rs:12     let profile = env!("PROFILE");
                              ^~~~~~~~~~~~~~~
error: aborting due to 6 previous errors
Could not compile `demo`.

To learn more, run the command again with --verbose.
```

If I change the failing statements to get the variables when the buildscript is run instead of compiled, everything seems fine:

```rust
// build.rs
use std::env;
fn main() {
    // both of these will compile on 2016-02-25
    let out_dir = env!("OUT_DIR");
    let manifest_dir = env!("CARGO_MANIFEST_DIR");

    // these will now compile on 2016-02-25
    let target = env::var("TARGET").unwrap();
    let host = env::var("HOST").unwrap();
    let num_jobs = env::var("NUM_JOBS").unwrap();
    let opt_level = env::var("OPT_LEVEL").unwrap();
    let debug = env::var("DEBUG").unwrap();
    let profile = env::var("PROFILE").unwrap();
}
```

Success!

```
$ cargo build
   Compiling demo v0.1.0 (file:///home/adam/rust-projects/demo)
```

So, it looks to me like the `OUT_DIR` and `CARGO_MANIFEST_DIR` are being set when the buildscript is compiled, but the other variables are only being set when the buildscript is run. However, this isn't in the docs anywhere that I can find.

I would propose either:

1. Make all of the variables available when the buildscript is compiled, so they can be included statically. I'd be happy to work on this if it's an approach the team would merge.
2. Document which variables are declared when, and provide a usage example for how to use the only-at-runtime buildscript environment variables. I'd also be happy to write some disambiguation is the team would prefer this approach.

Thoughts?

**Comment by alexcrichton** [comment]
Ah yeah, looks like a deficiency in the docs! All environment variables in [this section](http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) are only available when the build script runs, and [this section](http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-crates) is for when the crate is compiled.

**Comment by dikaiosune** [comment]
OK, that makes sense. I'd be happy to clarify the docs if a PR is welcome. Before I do though, where does `OUT_DIR` fit into that distinction? It's listed in the section for buildscript runtime, but it compiles and seems to work just fine when it's included as `env!("OUT_DIR")`.

**Comment by alexcrichton** [comment]
Certainly! OUT_DIR is actually a bit of an outlier in that the value at compile time is different than the value at runtime. We... actually probably shouldn't set it at compile time for build scripts (but it's available at compile-time for crates)

**Comment by dikaiosune** [comment]
OK, sounds good. I'll write something up once I go and remove `env!("OUT_DIR")` from my crate's buildscript :). I'd also be interested in contributing a patch to exclude it at buildscript compile-time if it's not too dicey a task for someone new to the codebase.

**Comment by alexcrichton** [comment]
I *think* it shouldn't be too bad, but if you need any help just let me know!
