### ISSUE TITLE
for dependencies permit a "hash='' / commit='' " option as alternative to version=''

### ISSUE THREAD

**Issue by allan-simon** [rust-lang/cargo#243]
of course most of the time people will prefer to have a version , hash would only be to cover the edge case , but that happens "often enough":

1 - your project depends on B ,   B current 'stable' version has a bug  which impact you 
2 - you report the bug to B, they fix it and say they are waiting for other stuff before releasing a new version 
3 - this new release never come 

also the case of a  regression in middle of two release etc. 

i.e all the cases where you need the state of the code at a specific commit (it's true that in the best of world people will not disapear or abandon their project, that you can fork on github etc.  but often enough that's not the case)

**Comment by qm3ster** [comment]
Necroposting for documentation purposes:
## [Yes you can!](https://github.com/rust-lang/cargo/issues/126#issuecomment-48101852)
https://github.com/rust-lang/cargo/issues/126#issuecomment-48101852
