### ISSUE TITLE
Could we get a CARGO_PKG_AUTHORS to complement CARGO_PKG_VERSION?

### ISSUE THREAD

**Issue by rtaycher** [rust-lang/cargo#2441]
`CARGO_PKG_VERSION` is useful to auto-configure app version in cmd line arguments.

clap-rs has `crate_version!()` macro which reads the version from the environment instead of specifying it twice and possibly forgetting to update it.

It would be useful to have a `CARGO_PKG_AUTHORS`.

It's true that authors isn't likely to change for small projects, and only rarely for large ones but it would still help with DRY and prevent larger projects from missing credits.

**Comment by alexcrichton** [comment]
Hm how should we encode this as an environment variable? Perhaps comma separated? I guess it'd be pretty rare for someone's name to have a comma in it.

**Comment by rtaycher** [comment]
Is there anything wrong with doing it like in Cargo (with double quotes) minus newlines:

    "author 1", "author 2", "author 3"

is there anything wrong with double quotes in environmental variables.

**Comment by alexcrichton** [comment]
I suppose we could also do that, yeah, just depends on how fancy we want to get.

**Comment by TheNeikos** [comment]
Oh hey, looks like I'm not the only one who wants this!
