### ISSUE TITLE
cargo not installing and getting error

### ISSUE THREAD

**Issue by flik** [rust-lang/cargo#2445]
I was following these instructions: 
 if you have rustc installed and not Cargo, you can simply run:

./configure
make
make install

and then getting errors:

failed to run custom build command for `libssh2-sys v0.1.36`
Process didn't exit successfully: `/var/www/cargo/target/release/build/libssh2-sys-1373436876d3ffec/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/root/.cargo/registry/src/github.com-48ad6e4054423464/libssh2-sys-0.1.36/libssh2" "-DCRYPTO_BACKEND=OpenSSL" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=/var/www/cargo/target/i686-unknown-linux-gnu/release/build/libssh2-sys-1373436876d3ffec/out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m32" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m32" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring incomplete, errors occurred!
See also "/var/www/cargo/target/i686-unknown-linux-gnu/release/build/libssh2-sys-1373436876d3ffec/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindOpenSSL.cmake:334 (find_package_handle_standard_args)
  src/CMakeLists.txt:62 (find_package)

thread '<main>' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /root/.cargo/registry/src/github.com-48ad6e4054423464/cmake-0.1.13/src/lib.rs:446
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make: *** [cargo-i686-unknown-linux-gnu] Error 101

**Comment by nodakai** [comment]
> Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
> system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
> OPENSSL_INCLUDE_DIR)

I guess you need either `aptitude install libssl-dev` or `yum install openssl-devel`

**Comment by jespino** [comment]
I'm agree. This is a dependency problem, not a cargo bug.

**Comment by alexcrichton** [comment]
Indeed, looks to be the case! I'm gonna close this for now but feel free to reopen if it's still a problem after installing the dependencies!
