### ISSUE TITLE
`cargo doc --open` regression on Windows

### ISSUE THREAD

**Issue by SpaceManiac** [rust-lang/cargo#2446]
On Windows 7, `cargo doc --open` has stopped working between stable and beta, instead failing silently. I was unable to find any obvious offending commits in the diff, or compile Cargo to narrow down the commit range myself.
```
Working: cargo 0.8.0-nightly (28a0cbb 2016-01-17)
Broken:  cargo 0.9.0-nightly (8fc3fd8 2016-02-29)
```

**Comment by pravic** [comment]
Confirming, same issue for me:
`cargo 0.10.0-nightly (61ad6a0 2016-03-22)`

**Comment by SpaceManiac** [comment]
Still exhibiting the problem on versions:
```
cargo 0.10.0-nightly (10ddd7d 2016-04-08)
cargo 0.11.0-nightly (59238e8 2016-04-14)
```
The output now ends with:
```
   Launching cmd /C start
```
