### ISSUE TITLE
Skip no-op git fetches from the registry

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#2451]
Quoting https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193801376:

> this new, preview API should help: https://developer.github.com/changes/2016-02-24-commit-reference-sha-api/. It's helped Homebrew dramatically reduce the number of no-op `git fetch`s which also will make things better for your users as a no-op API HTTP call is significantly faster for you (and less expensive for GitHub) than a no-op `git fetch`. 

Cargo could use this to determine that its local copy of rust-lang/crates.io-index is already up to date and it doesn’t need to git fetch.

In addition to limit the risk of hitting GitHub’s rate limiting on git traffic (see #2452) this can maybe make "Updating registry" faster.

It doesn’t seem rare in my Cargo using to see "Updating registry" multiple times within a few minutes, while the registry has had an average of one commit per ~half hour since its creation.

Servo may be more of a pathological case, but we have a `./mach cargo-update` command that call `cargo update` in each of four "top-level" crates (that each have a `Cargo.lock` file), causing the registry to be updated four times within a few seconds. Updating the registry seems to often dominate the time taken by this command (and `cargo update` in general).

**Comment by alexcrichton** [comment]
This seems reasonable to do eventually, but I don't want to start using unstable GitHub APIs as we're not really watching updates to the API.

It'd be nice though to see some benchmarks about how fast this is such as:

* How fast is the HTTP request vs a noop fetch?
* How fast is a HTTP request followed up by a fetch? (vs just a fetch)

**Comment by sfackler** [comment]
Also worth thinking about what the behavior should be when the registry isn't Github hosted.

**Comment by dtolnay** [comment]
I am seeing the HTTP request take 440 (+/- 10) ms and a noop fetch take 1350 (+/- 150) ms but occasionally up to 4 seconds.

At those numbers, HTTP request followed if necessary by fetch would save time if less than 2/3 of registry updates require a fetch which is certainly true in my usage.

**Comment by alexcrichton** [comment]
Thanks for the data @dtolnay! I'd actually be pretty curious to test this out and see what kind of perf gains we get in practice. We could perhaps even go as far as having an environment variable flag to test it out unstable-y for awhile.

Note that the [referenced github API support](https://developer.github.com/changes/2016-02-24-commit-reference-sha-api/) was in preview when first introduced, but this appears to [no longer be the case](https://developer.github.com/v3/repos/commits/#get-the-sha-1-of-a-commit-reference), so we should be good to go in that sense!

@sfackler I would expect this logic to be along the lines of when updating a git index which has the host of "github.com" the special logic takes effect, so it should be quite easy to continue to support arbitrary registries not on github. We could then implement fast paths for other registries in the future as well if need be.

**Comment by sfackler** [comment]
Cool. I could see having a "github-like" flag in custom registry config to enable the fast path for stuff hosted on e.g. GitHub for Enterprise.

**Comment by Ericson2314** [comment]
I'd be interested in trying this with the rust repo. Cargo fetches that ungodly slowly, but that may be the actual fetching itself rather than the would-be fast path.

**Comment by dtolnay** [comment]
I just want to follow up and say this change has been a noticeable improvement for me.
