### ISSUE TITLE
Specifying synchronized dependencies

### ISSUE THREAD

**Issue by mikedilger** [rust-lang/cargo#2479]
It would be helpful in some situations to be able to specify synchronization between dependencies, e.g.:

```
exactly_one_of { 
  {  serde = 0.6;  serde_codegen = 0.6 },
  { serde = 0.7; serde_codegen = 0.7 }
}
```

In some downstream projects, cargo  occasionally mixes-and-matches these versions for `textnonce` and the compile error then appears in `textnonce`, for which a bug is logged that doesn't really exist.  It's very confusing to the downstream user.  ~~The real bug is that one of their dependencies requires serde 0.6, another requires serde 0.7, and it was never going to work~~.... but the blame lands on `textnonce` because that's what fails to compile first:  https://github.com/mikedilger/textnonce/issues/7

**Comment by mikedilger** [comment]
Alternatively conditional dependencies, e.g.:

````
serde = ">= 0.6, < 0.8"
serde_codegen = { if serde = "0.6" then "0.6";  if serde = "0.7" then "0.7" }
````
(ignore my atrocious syntax)

**Comment by alexcrichton** [comment]
This is somewhat along the lines of https://github.com/rust-lang/cargo/issues/2064 I think?

**Comment by mikedilger** [comment]
Similar

**Comment by carols10cents** [comment]
I believe this will be solved by [public/private dependencies](https://github.com/rust-lang/rust/issues/44663), the RFC for which has been accepted, and now has a tracking issue: https://github.com/rust-lang/rust/issues/44663
