### ISSUE TITLE
Can't package applications using pbuilder / pdebuild and cargo

### ISSUE THREAD

**Issue by mdeguzis** [rust-lang/cargo#2492]
This is really annoying, so I hope there is some kind of workaround. I use pdebuild/pbuilder to build all of my packages for SteamOS. If I log into the chroot, invoke the hook to add my sources (which contain verified cargo/rustc builds), I can invoke `cargo fetch` and `cargo build --release` _perfectly fine_ under the [root git directory](https://github.com/libretro/rustation-libretro). I'd really prefer to maintain clean-room environments. And before anyone asks, yes USENETWORK is set to "yes", or else the github submodules would not update.

Is this because of some environment error being in a chroot?

When I try to run the build against the [debian](https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/retroarch/libretro-rustation/debian), I get:

```
   debian/rules override_dh_auto_build
make[1]: Entering directory '/build/libretro-rustation-0.0.1+20160317git+bsos1'
cargo fetch
    Updating registry `https://github.com/rust-lang/crates.io-index`
An unknown error occurred

To learn more, run the command again with --verbose.
debian/rules:14: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 101
make[1]: Leaving directory '/build/libretro-rustation-0.0.1+20160317git+bsos1'
debian/rules:11: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

Full build log:
https://gist.github.com/ProfessorKaos64/c881ff7a659e432e6e43

**Comment by alexcrichton** [comment]
Could you try rerunning the Cargo step with `-v`? That should help print out more error information to diagnose.

**Comment by ProfessorKaos64** [comment]
Hmm...so a permission issue? However pdebuild builds as root user.

```
dh build --parallel
   dh_testdir -O--parallel
   dh_auto_configure -O--parallel
   debian/rules override_dh_auto_build
make[1]: Entering directory '/build/libretro-rustation-0.0.1+20160318git+bsos1'
cargo fetch -v
    Updating registry `https://github.com/rust-lang/crates.io-index`
Permission denied (os error 13)
debian/rules:14: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 101
make[1]: Leaving directory '/build/libretro-rustation-0.0.1+20160318git+bsos1'
debian/rules:11: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debia
```

**Comment by ProfessorKaos64** [comment]
Could it be related to this issue? 
https://forum.safenetwork.io/t/rust-and-debian-packaging/3797/5

But, what is odd, is I built the package just fine inside the chroot with debuild.

**Comment by ProfessorKaos64** [comment]
Update: found this to be an issue how $HOME is being interpreted (guessing because of `cargo fetch` pushes the registry to $HOME/.cargo)

I put this in debian/rules
```
export HOME=$(CURDIR)/debian/home-tmp
```

**Comment by alexcrichton** [comment]
Sounds like Cargo could *definitely* produce a better error message here, but there's a number of ways to configure the `CARGO_HOME` value, so I don't think we'd want to fall back to various locations in the face of errors. If we had a better error message, however, it should facilitate diagnosis much more easily and could even suggest other locations.

**Comment by kellda** [comment]
Now the error message is better:

```
$ HOME=/dev/null cargo fetch
error: failed to acquire package cache lock

Caused by:
  failed to open: /dev/null/.cargo/.package-cache

Caused by:
  Not a directory (os error 20)
```

Should this error be closed then ?

**Comment by ehuss** [comment]
Yea, I think the current error should provide enough context.
