### ISSUE TITLE
Option to show cached error messages on 'cargo build' re-run

### ISSUE THREAD

**Issue by sekjun9878** [rust-lang/cargo#2494]
Hello,

Similar to this issue: http://stackoverflow.com/questions/31125226/it-is-possible-to-always-have-cargo-show-warnings

It would be nice to have an option for cargo to cache and display the build errors and warnings even when no changes are detected. This way, recompilation is not required just to see the last error messages.

**Comment by alexcrichton** [comment]
This seems like it would require quite a bit of support for a somewhat niche use case, but could perhaps be done one day?

**Comment by sekjun9878** [comment]
I agree that it is a bit of a niche case, but support for it would still be nice :)

**Comment by sekjun9878** [comment]
@alexcrichton A more useful alternative would be an option that displays all the errors, without going through the process of generating a binary. If it's fast enough, it could be run continuously on edits without the overhead of generating a binary every time? (I'm guessing the error-checking and binary compilation steps are separated)

**Comment by alexcrichton** [comment]
Ah yeah unfortunately the compiler doesn't support doing that, but we've talked about a mode like that in the past!

**Comment by carols10cents** [comment]
This sounds like it would have to be fixed in rust-lang/rust, so I'm closing!

**Comment by BatmanAoD** [comment]
I'm not sure why this is considered "niche" usage. Repeatedly attempting to compile one's codebase is a *typical* use case, and I would say it's pretty common for some files to be compiled successfully before others, causing any warnings from those files to be glossed over in order to focus on the remaining hard errors.

**Comment by ehuss** [comment]
This has been implemented and is tracked in #6986.
