### ISSUE TITLE
Provide package.name as CARGO_PKG_NAME

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/cargo#2504]
In the same spirit of not duplicating information as `CARGO_PKG_VERSION` and `CARGO_PKG_AUTHORS`, could cargo provide the package.name field as `CARGO_PKG_NAME`?  That would avoid duplication when providing the package name and version in help text or similar.

Along the same lines, I'd find it quite helpful to have `CARGO_PKG_DESCRIPTION` and `CARGO_PKG_HOMEPAGE`.

**Comment by alexcrichton** [comment]
Seems fine to me!

**Comment by srinivasreddy** [comment]
Still a work in progress but here is the PR- https://github.com/rust-lang/cargo/pull/2523

**Comment by srinivasreddy** [comment]
@alexcrichton  please close this issue.

**Comment by alexcrichton** [comment]
Thanks!
