### ISSUE TITLE
Ignore `[build]` in .cargo/config for cargo install

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/cargo#2507]
I tried to install `cargo-edit` through `cargo install`. But it failed with:

```
error: can't find crate for `std` [E0463]
error: aborting due to previous error
```

The reason was that the current directory contains a `.cargo/config` that overrides the default target. So `cargo install` tried to build for that target, too.

I found that a bit surprising since `cargo install` is close to something like `apt-get install`, which is independent of the current directory. Is there a reason why `cargo install` doesn't just ignore `.cargo/config` files?

**Comment by alexcrichton** [comment]
I would be wary of blanket ignore the entirety of `.cargo/config`, but perhaps ignore some select tables (for example `[build]`) on a `cargo install` does seem reasonable

**Comment by japaric** [comment]
:+1: to at least ignore build.target. Right now I'm working this around with:

```
$ mv .cargo cargo
$ cargo install $crate
$ mv cargo .cargo
```

**Comment by ehuss** [comment]
The local `.cargo/config` file is now ignored in `cargo install` as of #6026.  The global HOME directory config is still used.
