### ISSUE TITLE
Display all Cargo target executables in `cargo metadata` or similar command

### ISSUE THREAD

**Issue by bruno-medeiros** [rust-lang/cargo#2508]
Enhancement: a command to display all Cargo targets (including implicit test targets such as bin-tests and lib-tests) and their associated executable.

See also: https://github.com/rust-lang/cargo/issues/1924

**Comment by alexcrichton** [comment]
cc @matklad

**Comment by matklad** [comment]
>Enhancement: a command to display all Cargo targets

`cargo metadata` already does this. 

>and their associated executable.

There can be several executables for one target (`target/debug/foo`, `target/release/foo`).

**Comment by matklad** [comment]
>I just realized that currently the test binary for #[test] tests aren't included in cargo read-manifest output. 

Ah, yes, now I also realize this.

**Comment by epage** [comment]
Going to close in favor of #5866 as it has more discussion
