### ISSUE TITLE
`cargo run` cannot accept non-unicode arguments

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/cargo#2511]
Say I write a small program that just prints its args:

``` rust
fn main() {
    for arg in std::env::args_os() {
        println!("{:?}", arg);
    }
}
```

Because it uses `args_os()` instead of `args()`, this program can handle command line args that aren't valid unicode. However, `cargo run` chokes:

```
$ cargo run $(printf '\xff')             
invalid unicode in argument: "\u{fffd}"
```

I have to invoke the binary directly to test the program:

```
$ ./target/debug/scratch $(printf '\xff')
"./target/debug/scratch"
"\u{fffd}"
```

Does Cargo need to inspect the command line args at all? It not, it would be nice if it didn't require them to be utf8.

**Comment by jonas-schievink** [comment]
You might want to try `cargo run -- $(printf '\xff')` - without the `--`, cargo parses the 0xff as an argument for cargo run

**Comment by oconnor663** [comment]
Oh I hadn't tried that. But it does look like I get the same result:

```
$ cargo run -- $(printf '\xff')
invalid unicode in argument: "\u{fffd}"
```

**Comment by alexcrichton** [comment]
cc https://github.com/docopt/docopt.rs/issues/152 and @BurntSushi, unfortunately this is a limitation of the underlying docopt library that Cargo is currently using.

**Comment by alexcrichton** [comment]
Now that being said I think we're also storing `Vec<String>` in a few places instead of `Vec<OsString>`, so there's also changes to be had on the Cargo side as well

**Comment by BurntSushi** [comment]
Yeah, docopt should grow support for this. The arg parser itself is written to work on `&str`, so there are a fair amount of guts that will have to change, but shouldn't be too bad.
