### ISSUE TITLE
Make cargo fetch able to ignore target validation when reading the manifest files

### ISSUE THREAD

**Issue by theypsilon** [rust-lang/cargo#2518]
There are some workflows where you don't have yet available the sources from your project target, but you still want to download the dependencies, in order to isolate or optimize your build pipeline.

I was thinking that there is no much benefit from checking targets at all during cargo fetch, so maybe this is a change that would be overall nice to happen.

I can give more details from my real use case (docker), and about why this would be not only good in terms of isolation but also for speeding up the building process. Basically, the reason of the speed up relies on how docker build cache works. If you add a manifest file in an early build step, and you operate over it, you will cache the resulting intermediate image, and the cache will get invalidated only if you modify that manifest file, which is expected to happen not so often. That way, you can add the rest of the sources in a later step, and build them using an environment that is already cached into an intermediate image, so you don't need to rebuild the whole pipeline from scratch every time your code changes.

**Comment by alexcrichton** [comment]
Seems reasonable to me! When you mention target validation, do you mean how we run the compiler to learn a bit of information? I'm curious what errors you're seeing here.

**Comment by theypsilon** [comment]
This is the error of this particular use case:

```
Sending build context to Docker daemon 5.632 kB
Step 1 : FROM scorpil/rust:1.7
 ---> 1c1705caf03f
Step 2 : WORKDIR /app
 ---> Using cache
 ---> 359515da308b
Step 3 : ADD Cargo.toml /app/Cargo.toml
 ---> Using cache
 ---> a6f0db198d73
Step 4 : RUN cargo fetch
 ---> Running in 02370a42a457
failed to parse manifest at `/app/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
The command '/bin/sh -c cargo fetch' returned a non-zero code: 101
```

The workaround is clear there in the nice error description. Creating a fake src/main.rs with just 'fn main() {}' is a possible hack. But defining a [[bin]] section looks a bit better. 

In fact, I don't know what is the idiomatic cargo manifest definition, but if it is always recommended to add the [[bin]]/[lib] section, then there is no need to address this change, because the error would be consequence of having an ill-formed cargo manifest file, more than the fetch behaviour. I'm still unsure about the designers intention with this.

**Comment by alexcrichton** [comment]
Aha! I think I see what's going on here.

These targets, the [lib] and [[bin]] ones, unfortunately can't be ignored. We need to successfully parse the manifest to ensure that we have a list of dependencies to fetch during `cargo fetch`. If you'd like to just prepopulate the index, however, you could do something like `cargo new foo && cargo fetch --manifest-path foo/Cargo.toml` perhaps?

**Comment by carols10cents** [comment]
This sounds like there's a workaround. Please reopen if this workaround is insufficient!
