### ISSUE TITLE
Support default profile settings in ~/.cargo/config

### ISSUE THREAD

**Issue by pravic** [rust-lang/cargo#2520]
Is it possible? For example I want to specify my own settings for the `[profile.release]` which can be used by all cargo builds until overrided by crate's Cargo.toml.

**Comment by alexcrichton** [comment]
This isn't currently possible, no, but seems reasonable!

**Comment by ehuss** [comment]
See also https://github.com/rust-lang/cargo/issues/3459#issuecomment-466076347, config profiles are now implemented (https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-profiles). However, the precedence is different (config overrides manifest).  If that is important, please comment on the tracking issue: https://github.com/rust-lang/rust/issues/48683
