### ISSUE TITLE
Allow more-easily-parsable output format for `cargo bench`

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/cargo#2528]
I thought about creating a utility to visualize the results of `cargo bench`. Has there been any thought about adding a `--format=json` flag to `cargo bench` so this would be easier? I might be interested in implementing this if this gets approval

**Comment by alexcrichton** [comment]
This would probably want to get filed against libtest rather than Cargo itself, as Cargo's just running binaries

**Comment by frewsxcv** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/32595
