### ISSUE TITLE
Cargo does not recover from failed git update (File lock issue?)

### ISSUE THREAD

**Issue by jfhumann** [rust-lang/cargo#2533]
I'm currently trying to build servo, which uses cargo for this (Current nightly is used afaik).

When updating some git repositories servo depends on cargo fails (not always, but sometimes (I'm puzzled about this, but I think this might be another issue completely)).
After manually restarting the cargo build, cargo continues, but when it again handles the git repository it previously failed on it just prints "Blocking waiting for file lock on the git checkout" and waits there indefinitely. 

I attached a full log of what I did.
[cargo-lock.txt](https://github.com/rust-lang/cargo/files/195982/cargo-lock.txt)

When searching for this in the existing issues I found #2486, which is a quite recent pull request apparently concerning the same message I got. So maybe this might be related to that change.

**Comment by jfhumann** [comment]
Please let me know if you need additional information, I'll try to provide everything which might come in handy.

**Comment by alexcrichton** [comment]
Hm when Cargo prints that it's blocking, are you *sure* that there are no other processes on the system that have that lock acquired? It may be the case that some Cargo may be spuriously running around in the background for example.

**Comment by jfhumann** [comment]
Hm at least I can't think of any processes running that acquire this lock. Is there a good way to find out?

Well I already tried:

- Restarting my system
- Deleting the whole local servo project, recreating it with a new git clone
- Deleting ~/.cargo which somehow had been created.

**Comment by alexcrichton** [comment]
Whoa lol if after a restart the directory is still locked then that's probably a bug in Cargo!

Could you try running cargo with `RUST_LOG=debug` and gist the output of that as well?

**Comment by emilio** [comment]
I can reproduce it with a clean build also. RUST_LOG=debug:
```

**Comment by emilio** [comment]
This is the changeset https://github.com/servo/servo/pull/10291/files, the dependency is added and cargo fails to update the .lock files it seems.

**Comment by emilio** [comment]
Updating the lockfile (using `./mach cargo-update -p webrender_traits --precise 2ad5e68f3f49c91ef627848d9561649f3c1be344` solves the issue for me).

**Comment by alexcrichton** [comment]
Aha, thanks for the info @emilio! I've been able to reproduce locally with a small test case, I'll try to get a fix up quickly

**Comment by alexcrichton** [comment]
Ok, found a fix!

https://github.com/rust-lang/cargo/pull/2534/files

**Comment by emilio** [comment]
Whoah, awesome! Thanks for the quick fix! :)

**Comment by jfhumann** [comment]
Thank you :)

**Comment by theronic** [comment]
This happens for me when you fetched some packages as root, then later tried to build as non-root.

You can verify this by running `ls -la rm /Users/petrus/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/FETCH_HEAD` and looking at owner of the FETCH_HEAD file.

Solved by deleting FETCH_HEAD and rebuilding.
