### ISSUE TITLE
Request: provide path-to-root of conflict

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/cargo#2544]
Scenario:
- cargo build
- failed to select a version for `winapi` (required by `backtrace`):

Problem: 'backtrace' isn't in my Cargo.toml. It would be a great help to know what package was requiring winapi, and the parent of that parent, etc.

If I had this path I would at least have a place to start.
All paths that reference winapi would be even better - so I could quickly find out where the version divergence happens and adjust accordingly with a few Cargo.toml adjustments.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/cargo/issues/782, our errors here are probably unfortunately lacking in general (:

**Comment by carols10cents** [comment]
Does [`cargo tree -i`](https://crates.io/crates/cargo-tree) work if cargo can't resolve the dependencies? If so, I think that command provides what is requested here. Whether `cargo tree` should be part of cargo is a different discussion :)

So I'm going to close this, please reopen if I'm mistaken.
