### ISSUE TITLE
Could not execute cargo, Access is denied (os error 5)

### ISSUE THREAD

**Issue by leighflix** [rust-lang/cargo#2546]
I've looked all over google and haven't found anything related to cargo and windows, even then their problems were different and couldn't help at all. I cannot run anything related to cargo (run, build, --version, etc). 

```
C:\Users\leigh
λ cargo --version
Could not execute process `C:\Program Files\Rust stable GNU 1.7\bin -vV` (never executed)

Caused by:
  Access is denied. (os error 5)
```

**Comment by alexcrichton** [comment]
Thanks for the report! Do you perhaps have any environment variables like `RUSTC` set or some build configuration in `.cargo/config` changing the compiler? It looks like something is indicating to Cargo that it should execute a directory, which is failing

**Comment by leighflix** [comment]
Extremely sorry for not responding, and I suspected it was because the environment variables were for my accout so I changed them to the systems environment variables but still, problem occurs.

**Comment by leighflix** [comment]
And I have never build a cargo project as the project obstructs that. So I doubt I have a \config file anywhere.

**Comment by leighflix** [comment]
As a side note: Turning off my antivirus (windows defender) would not help. (I do not have any other AV program installed)

**Comment by alexcrichton** [comment]
In the shell, can you print the value of the `RUSTC` environment variable?

**Comment by leighflix** [comment]
`C:\Program Files\Rust stable GNU 1.7\bin` is the value.

**Comment by alexcrichton** [comment]
Ah I think that's it! The `RUSTC` environment variable is intended to point to the compiler, so if you point it at `rustc.exe` does it work?

**Comment by leighflix** [comment]
Yes it does work, thank you very much :)
