### ISSUE TITLE
cfg!(test) doesn't seem to work for build.rs

### ISSUE THREAD

**Issue by azerupi** [rust-lang/cargo#2549]
When using a `build.rs` file, cargo doesn't seem to pass the `test` flag when `cargo test` is used.

```rust
fn main() {
    if cfg!(test) { ... }
}
```

Does not work. As a workaround you can use features:

```rust
fn main() {
    if cfg!(feature="test") { ... }
}
```

But it requires you to use `cargo test --features=test`

**Comment by alexcrichton** [comment]
Yeah today build scripts aren't re-run for tests (only for libraries), but I think this is covered by https://github.com/rust-lang/cargo/issues/1581 so closing in favor of that. Thanks for the report though!
