### ISSUE TITLE
Error on build script output without leading cargo that is not utf-8

### ISSUE THREAD

**Issue by Shaktyi** [rust-lang/cargo#2556]
Cargo's [documentation of build scripts](http://doc.crates.io/build-script.html#outputs-of-the-build-script) state that output beginning with `cargo:` is interpreted. Other lines, however, are not completely ignored as non-utf-8 characters there cause the build to fail.

An example where the build fails is using a build script with cmake on Windows with a german MSVC. While compiling a C library, the german output includes umlauts that are not utf-8. Even though the lines starting with `cargo:` contain only utf-8, the build fails.

**Comment by Luthaf** [comment]
See https://users.rust-lang.org/t/encoding-problem-of-cmake-path-on-windows/5333 for the initial issue.

**Comment by alexcrichton** [comment]
Oh dear, seems like a bad failure mode!
