### ISSUE TITLE
`cargo doc --lib`

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/cargo#2557]
I'd love an option to only build and document the lib portion of a crate. I use rustdocs a lot in planning things out and sometimes during a refactor I'll break the binaries but still want to see the docs. Cargo supports `cargo build --lib` for this, seems like `cargo doc --lib` is a natural flag to support.

**Comment by alexcrichton** [comment]
Oh oops! I thought I modified all commands to take `--lib`, `--bin`, etc. Should be an easy bug to knock out :)

**Comment by nixpulvis** [comment]
Oh and `cargo test --doc` too.
