### ISSUE TITLE
"no matching package named `ffmpeg-sys` found" but required version is part of the index

### ISSUE THREAD

**Issue by AndiDog** [rust-lang/cargo#2558]
Getting this error while building a project that needs crate "ffmpeg" (which in turn currently requires ffmpeg-sys 2.8.3). I have path overrides in ".cargo\config", but that does not seem to matter since Cargo does not consider them (I removed the overrides and get the same issue).

> Updating registry `https://github.com/rust-lang/crates.io-index`
> error: no matching package named `ffmpeg-sys` found (required by `ffmpeg`)
> location searched: registry https://github.com/rust-lang/crates.io-index
> version required: ^2.8.3

The searched version is apparently on the index (with suffixes, e.g. "2.8.3-1"):
https://github.com/rust-lang/crates.io-index/blob/master/ff/mp/ffmpeg-sys

Is this a bug?!

(using Rust 1.9 nightly on Windows, `cargo 0.10.0-nightly (10ddd7d 2016-04-08)`)

**Update:** Just checked on Mac OS X with exact same files. Was still working there because I used an older Cargo (`cargo 0.9.0-nightly (f052d99 2016-01-24)`). Updated to nightly now and I get the same error (`cargo 0.10.0-nightly (10ddd7d 2016-04-08)`) as on Windows 🤔.

**Comment by alexcrichton** [comment]
I believe this is the same https://github.com/rust-lang/cargo/issues/2381, but the gist is that ffmpeg-sys has only been released with prerelease versions so you'll have to pin to those specifically.
