### ISSUE TITLE
no way to install cargo when built with cargo

### ISSUE THREAD

**Issue by rkitover** [rust-lang/cargo#2564]
If you build cargo with `cargo build --release`, then there is no mechanism to install it on the system.

Running `./configure && make install` is not really an option because that tries to download a snapshot, and there may not be a snapshot and/or downloading it may be undesirable in a package build situation.

**Comment by alexcrichton** [comment]
There's a `./configure --local-cargo=/path/to/cargo` which doesn't download a snapshot, does that suffice?

**Comment by rkitover** [comment]
This would be perfect, but there seems to be a problem, when I do a gmake install I get:

```
sh: /home/rkitover/src/cargo//src/rust-installer/gen-installer.sh: No such file or directory
Makefile:320: recipe for target 'target/x86_64-unknown-openbsd/release/dist/cargo-0.10.0-x86_64-unknown-openbsd.tar.gz' failed
gmake: *** [target/x86_64-unknown-openbsd/release/dist/cargo-0.10.0-x86_64-unknown-openbsd.tar.gz] Error 1
```

**Comment by alexcrichton** [comment]
Oh the `src/rust-installer` directory is actually a submodule and the configure script doesn't currently check it out just yet, so if you run `git submodule update --init` head of time, does that fix it?

**Comment by rkitover** [comment]
Yes this works fine, thank you. However, there are no tags for rust-installer and therefore no github tarballs of it, which is also a problem for packaging, because you cannot download things during a build.

Could you please make a tag for rust-installer?

**Comment by alexcrichton** [comment]
cc @brson

**Comment by alexcrichton** [comment]
Ok, closing in favor of https://github.com/rust-lang/rust-installer/issues/45
