### ISSUE TITLE
When using a git dependency with a submodule, and an update is stopped, then there is an error

### ISSUE THREAD

**Issue by julienw** [rust-lang/cargo#2567]
STR:
1. Use a git dependency with a submodule (ex: https://github.com/fxbox/openzwave-rust)
2. run "cargo build" but then type "CTRL-C" while it's being updated.
3. run "cargo build" again.

The error I get is:
```
error: Unable to update https://github.com/fxbox/openzwave-rust#1d7ab4d3

Caused by:
  failed to update submodules

Caused by:
  [3/-4] '/home/julien/.multirust/toolchains/nightly-2016-04-10/cargo/git/checkouts/openzwave-rust-3fdf6c635691fa96/master/openzwave-sys/open-zwave' exists and is not an empty directory
```

The error is fixable by deleting that directory and starting again. Maybe this should be done if a `git submodule update` or a `git clone --recursive` (or whatever you're doing) is interrupted ?

One additional issue is that an update can be silently started at `cargo build` without any message, and as a result the user may want to interrupt the process because he has no idea of what's going on, even with `--verbose`.

**Comment by alexcrichton** [comment]
Seems bad! Sounds like a directory should get blown away somewhere when we hit an error (or if we simply start to update a submodule)
