### ISSUE TITLE
Feature request: search docs

### ISSUE THREAD

**Issue by deepak** [rust-lang/cargo#2569]
I use a custom search query like "site:doc.crates.io subcommand" on google
to search the docs

can use something like [google CSE](https://cse.google.com/cse/)
and embed on the website

to make it more obvious

**Comment by alexcrichton** [comment]
Would that basically be something where we farm out the search queries and UI to an external provider? I haven't had too much experience with that, but we'd probably want to keep this in line with the main rust book/docs as well

**Comment by deepak** [comment]
yeah. will record a GIF to show how it will look

**Comment by deepak** [comment]
google CSE (Custom Search) is similar to searching google
for a particular website
eg. search query "site:doc.crates.io custom"
    
It is a service hosted by Google. It has a free plan
which serves ads. And paid plans without ads and
more customization evidently (have not looked into it)
    
but we can
    
- include multiple websites
- has various options for styling
    
But the design of the results page looks vintage
and not in a good way
    
the advantage is that it is free of course
    
there are multiple options for integrating google CSE
normally google CSE, asks you to add their javascript
but we can make do with redirecting to their url

for more information
    
https://support.google.com/customsearch/answer/4513751?hl=en
https://en.wikipedia.org/wiki/Google_Custom_Search
https://cse.google.com

**Comment by deepak** [comment]
google CSE is looking ugly. Gif is 
![search rust s cargo docs with google cse](https://cloud.githubusercontent.com/assets/9192/14513895/52ed3f42-0209-11e6-9401-0a4c87816de1.gif)

**Comment by deepak** [comment]
redirecting to google looks better

![search rust s cargo docs with google redirect](https://cloud.githubusercontent.com/assets/9192/14513935/ae865ff0-0209-11e6-8da4-d11ecd75e9dc.gif)

**Comment by deepak** [comment]
code is at https://github.com/rust-lang/cargo/compare/gh-pages...deepak:gh-pages-2569-search-docs?expand=1

**Comment by alexcrichton** [comment]
Interesting! I feel like this is such a non-native UI though that we probably don't want to add it at this time. We've wanted to expand and reorganization the documentation for some time now, however, which I think will improve readability and figuring out where to go on the docs. In that case I'm gonna close this in favor of https://github.com/rust-lang/cargo/issues/2580, but thanks for the report and investigation!
