### ISSUE TITLE
Support depending on generated crates

### ISSUE THREAD

**Issue by jadahl** [rust-lang/cargo#2570]
I would like to auto generate crates from files already installed on the system via build.rs, and include them in the same way as dependencies are included, i.e. without using the include!() macros.

I imagine this could work simply by adding a new type of dependency with a different variable, or an extra variable saying the path provided is relative to the OUT_DIR.

Does this sound like a reasonable thing to add? I would volunteer to implement a solution myself if it'd solve my use case.

**Comment by alexcrichton** [comment]
Thanks for the report! So if I understand this correctly you basically want a way to generate `src/lib.rs` in addition to the rest of the crate?

**Comment by jadahl** [comment]
Yes, and "import" it as if they would be external dependencies. Right now the way to do this is to automatically generate these crates, place them somewhere static and add a dependency with the path to where you placed them. What I want to do is completely avoiding having to install these completely generated libraries, and just generate and import them on the fly.

I started looking at adding this to cargo, but thought I should go through here before doing anything serious.

**Comment by alexcrichton** [comment]
In theory this is all possible today with a crate that looks like:

```rust
// lib.rs
include!(concat!(env!("OUT_DIR"), "/lib.rs"));
```

```rust
// build.rs
fn main() {
    // generate crate into $OUT_DIR
}
```

Does that suffice?

**Comment by jadahl** [comment]
You mean to have a code tree that looks like this:

project/
  src/...
  deps/dependency1/lib.rs
  deps/dependency2/lib.rs
  deps/dependency3/lib.rs

and then have the build description file generate those?

This, I suppose, could work, but seems more like a work around due to the build system lacks the required feature to implent it properly. It would just make it easier to just depending on someone's uploaded generated crate. What I aim for is making it equally easy to not go through a distributed auto-generated crate (because it makes you rely on someone else running the generate command and uploading a new version on each new release of each dependency). So having to add boiler plate all over the tree is not good enough IMHO.

**Comment by alexcrichton** [comment]
Hm I guess I'm a little confused in that case. In some sense we already do support generating crates at build time (through build scripts), so I'm confused what the issue here is about. Could you elaborate a bit more on the use case of what's involved here?

**Comment by jadahl** [comment]
The use case is generating crates from GObject introspection files. A GObject introspection file is a file containing a description of an API. By adding support to a language to read these files and integrate the bindings in some language specific way, one will have access to any library that is GObject introspectable. A couple examples of such libraries are gtk+, gstreamer and pango. What I want to do is to simply use these libraries from a rust application by generating crates given the GObject introspection files.

Currently there are supposedly three ways of doing this.

One way this is done is that someone generates these files, then uploads them somewhere, while others will depend on them by adding a dependency, linking to where they uploaded.

Another way is to wrap cargo in another build script which will generate the crates, while making cargo simply depend on those by providing a local path.

The third way, which I haven't tested, would be to generate the files, and for each generated crate, create a wrapper rust file that includes the file.

All these solutions are IMHO flawed. I want to avoid the unnecessary uploading and distributing of the generated files, I would like to avoid using multiple build systems, and I would like to avoid adding boiler plate code for each dependency.

Does this make it clear what I'm suggesting?

**Comment by alexcrichton** [comment]
> Another way is to wrap cargo in another build script which will generate the crates, while making cargo simply depend on those by providing a local path.

This sounds like the solution that I'd probably recommend for both now (and long term), concretely looking like:

```toml
[package]
name = "gstreamer"
# ...
build = "build.rs"

[build-dependencies]
gobject-introspection = "0.2"
```

```
// src/lib.rs
include!(concat!(env!("OUT_DIR"), "/lib.rs"));
```

```
// build.rs
extern crate gobject_introspection;
fn main() {
    gobject_introspection::generate("gstreamer", "lib.rs");
}
```

That way you don't upload any generated files, you centralize all logic for gobject introspection, and all crates are generated at build time. Does that sound like it'd solve your constraints? In theory this isn't *that* much boilerplate and you shouldn't need to make a bunch of these templates in a project, right?

**Comment by jadahl** [comment]
Are you implying I add three new files for each dependency, or just use some other build system than cargo for this?

If you suggest to use something other than cargo, then there is no point in adding any rust based build-dependencies or gobject_introspection::generate(..) functionality, since it'd be the other build system that needs to check for dependencies and all that. I suppose that build system could generate the Cargo.toml file as well, instead of calling rustc, so at least building is done via Cargo.

Is there any reason why you are hesitant to allow adding the possibility to directly depend on generated crates?

**Comment by alexcrichton** [comment]
Ah sorry so to elaborate more, what I've shown above uses Cargo, and it's Cargo's support for depending on generated code. I'm not quite understanding how that's not sufficient or how you would want to tweak the support in Cargo.

Could you expand a bit on what you'd specifically like to see in Cargo?

**Comment by jadahl** [comment]
When opening this issue, what I had in mind was to add something like the following in Cargo.toml:
```
[build-dependencies]
gobject-introspection = "0.2"

[dependencies.gtk]
out_directory_relative_path = "gtk"

[dependencies.gdk]
out_directory_relative_path = "gdk"
```

and then this it build.rs:

```
extern crate gobject_introspection;

fn main() {
    gobject_introspection::generate("gtk", "Gtk-3.0");
    gobject_introspection::generate("gdk", "Gdk-3.0");
}
```
The only cargo addition would be to add a type of dependency where the path is relative to the unique out/[...]/ directory.

Another option, which might be even better, would be to add all of it in build.rs, i.e. something like:

```
extern crate gobject_introspection;

fn main() {
    gobject_introspection::generate("gtk", "Gtk-3.0");
    gobject_introspection::generate("gdk", "Gdk-3.0");
    println!("cargo:add-import-path=gtk");
    println!("cargo:add-import-path=gdk");
}
```

which would instead of adding a type of dependency add the path to the generated crate directly from build.rs.

**Comment by alexcrichton** [comment]
Thanks for the explanation! That seems pretty similar to [what I mentioned above](https://github.com/rust-lang/cargo/issues/2570#issuecomment-212037389), though, except that it lacks features like:

* The entire `Cargo.toml` now needs to be specified on stdout for build scripts, including all metadata.
* You can't specify dependencies for the generated crates (resolution happens before building).

Overall that seems like a "very magical" feature to avoid just a few files?

**Comment by jadahl** [comment]
Not sure I follow you here. What do you mean with "specify the entire `Cargo.toml`"? Isn't the stdout from build.rs simply meant as a way to pass meta data back to cargo? At least with the second idea, what cargo would do is to read the "add-import-path" properties, build and import so that the actual application/library can use them.

With what you mentioned before, and the first of the two options I mentioned above, the dependencies in Cargo.toml would be bogus anyway. The actual dependency checking would still be done either by a wrapping build system (like autoconf) or by build.rs.

**Comment by alexcrichton** [comment]
There's basically a whole ordering problem going on where Cargo has to know that it runs things out of order. For example the build script would run *before* dependencies so it can generate them, then Cargo would go backwards and compile those dependencies.

Furthermore Cargo doesn't have metadata about the dependencies (e.g. the `Cargo.toml` I mentioned) until they're generated, at which point it's too late to add more dependencies, activate features, etc.

**Comment by jadahl** [comment]
Couldn't we make the generated crates not behave as dependencies (as dependency checking would actually be done in build.rs), but rather as some extra targets that is to be built on build time? In other words, build.rs adding various meta data (like the cargo.add-import-path example), cargo would add those paths to the builder not as dependencies, but as targets (or whatever they may be called). Those same paths would then be added as the equivalent of include paths when building the rest.

I understand that it might not be a trivial thing to add, and I'm not asking anyone to implement it for me, so just to point out, if we manage to figure out something that we both agree on is reasonable to add/use, I'd be happy to make an attempt to implement it.

**Comment by alexcrichton** [comment]
I suspect that any generated FFI binding would want to at least link to `libc`, so you'd need at least some method of specifying dependencies (and this would likely grow over time)

Basically what I'm pointing out is that today we have support for this, and it seems much more composable than a one-off specialized solution like this?

**Comment by jadahl** [comment]
Couldn't that just be communicated with rustc-link-lib and rustc-link-search?

I can see what you are pointing out, but I can't say that I agree. Then again, I opened this issue with the reason to see if it would, to upstream, be an acceptable feature addition before attempting to implement it, and if it is not, then so be it, I will have to manage some other way, be it autotools or a bunch of extra files and boiler plate.

**Comment by alexcrichton** [comment]
Unfortunately those options are just meant for native libraries, not rust crates.

Ok, for now I think that we'll probably want to stick with the current code generation scheme, but we can always reevaluate if it's too painful though!
