### ISSUE TITLE
install doesn't fully respect `-q` parameter.

### ISSUE THREAD

**Issue by goertzenator** [rust-lang/cargo#2571]
When I use the `-q` (quiet) parameter with the install command, I still get the following output:

```
cargo install --path crates/erl_comm/ --root priv/rust -q
be sure to add `/home/goertzen/rust.mk_demo/priv/rust/bin` to your PATH to be able to run the installed binaries
```

The expectation is to not see the `be sure to add...` line.

Use case:  I am writing a plugin for Erlang to build extension modules in Rust.  Cargo is too noisy during build:

```
goertzen@g550jk ~/rust.mk_demo $ make
 DEPEND rustmk_demo.d
 ERLC   complex1.erl rustmk_demo_app.erl rustmk_demo_sup.erl
 APP    rustmk_demo
 CARGO  erl_comm
be sure to add `/home/goertzen/rust.mk_demo/priv/rust/bin` to your PATH to be able to run the installed binaries
```

**Comment by alexcrichton** [comment]
Oops! Should be a pretty easy conditional to add somewhere though

**Comment by alexcrichton** [comment]
I think this is something like `Shell::warn` just needs a check like `Shell::status` has today (or something like that)
