### ISSUE TITLE
Cargo should run doc tests before integration tests

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/cargo#2572]
In the process of refactoring I'd like to focus on a single module, making the needed changes to get all the module's tests passing again, then work my way to getting all the integration tests working again. Currently I need to comment out the integration tests to do this, or run with `--no-fail-fast`.

**Comment by alexcrichton** [comment]
The exact sequencing of tests in theory shouldn't matter too much, but we should definitely allow `cargo test --doc`

**Comment by nixpulvis** [comment]
I disagree that the order of running tests doesn't matter. It implies a sort of *flow* for fixing and refactoring tests. It seems weird to tell people to fix their integration tests before they have a working library.

**Comment by alexcrichton** [comment]
Hm perhaps, although we do always support filters in terms of matching the test name to skip running any integration test and go straight to doc tests.

Unfortunately the way Cargo composes multiple test suites isn't necessarily the best right now (e.g. it's not configurable like this)

**Comment by nixpulvis** [comment]
Problem with filtering is that it requires them to build first. I want to be able to fix my doc tests before thinking about integration.

**Comment by alexcrichton** [comment]
Right that's what `cargo test --doc` is useful for because you say you only want to test the `--doc` target, nothing else.

**Comment by carols10cents** [comment]
This sounds like `cargo test --doc` is sufficient, please reopen if I'm mistaken. Thanks!
