### ISSUE TITLE
It would be useful to have a way to hook on `cargo clean` for build scripts

### ISSUE THREAD

**Issue by julienw** [rust-lang/cargo#2573]
Currently we can't easily clean a C library we built with a `build.rs` file.

For maximum backward compatibility, a `clean.rs` file would be the best option IMO.

Another option is an opt-in in Cargo.toml so that build.rs can take the target as a parameter (without the opt-in, it would work like it does today).

**Comment by alexcrichton** [comment]
Does the build script not build into `$OUT_DIR`? Cargo should clean that out entirely?

**Comment by julienw** [comment]
In my case I use a "make" command in a subdirectory first. This creates a `.a` file we link to statically.

After `cargo clean`, if we run `cargo build` again, all the `.o` files and the final `.a` file are still present. So the "make" does not rebuild everything.
I could always run `make clean` before `make` but I thought this is not elegant. Ideally we'd want to clean only if the developer tuns `cargo clean`.

So I think it would make sense to run `make clean` in the submodule directory only when we run `cargo clean`.

**Comment by alexcrichton** [comment]
Hm yeah running `make` in the source directory unfortunately wreaks havoc with Cargo's ability to determine when to rerun the build script. Currently Cargo sees that a file has changed, which causes it to rerun the build script next time, which changes a file, etc. This ends up meaning that Cargo's incremental builds don't end up working.

A lot of the custom build command support for Cargo is designed around the assumption that scripts use `$OUT_DIR` for generated files (including the `cargo clean` aspect). Would it be possible to tweak the build script to do the same?

**Comment by julienw** [comment]
> Currently Cargo sees that a file has changed, which causes it to rerun the build script next time, which changes a file, etc. This ends up meaning that Cargo's incremental builds don't end up working.

Mmm I don't see this happening. The directory I'm running "make" in is a git submodule, and the generated files (.o, .so, .a, etc) are all in .gitignore. Is cargo using git to determine which files are source files ?

> Would it be possible to tweak the build script to do the same?
I just looked and I think there is actually an env variable just for this, I'll have a closer look.

**Comment by julienw** [comment]
> I just looked and I think there is actually an env variable just for this, I'll have a closer look.

So yes, I could do it like this. So this issue is not an issue anymore for me :) Yet don't you think this could be generally useful ?

**Comment by alexcrichton** [comment]
> Is cargo using git to determine which files are source files ?

Ah yeah we ignore what's in .gitignore by default.

> So this issue is not an issue anymore for me :) Yet don't you think this could be generally useful ?

Interesting! Could you elaborate a bit on what you found? I wasn't sure we had an env var for this...

**Comment by julienw** [comment]
> Interesting! Could you elaborate a bit on what you found? I wasn't sure we had an env var for this...

The Makefile I used had an env var :) So nothing related to Cargo, I just set this env var when running make: https://github.com/julienw/openzwave-rust/commit/ebc2ad4681902003ebb825733b1bdf8367eb42ae

**Comment by alexcrichton** [comment]
Ah yeah! Most makefiles are pretty good about allowing you to specify "place the output over here instead"

**Comment by carols10cents** [comment]
Sounds like this is no longer an issue, so I'm closing! Please reopen if I'm mistaken.
