### ISSUE TITLE
allow installation of multiple packages in one line

### ISSUE THREAD

**Issue by kindlychung** [rust-lang/cargo#2585]
Currently `cargo install racer rustfmt` would produce an error.

**Comment by alexcrichton** [comment]
Sounds fine to me! We can't easily parallelize the compilation just yet, but sequencing should be easy enough.

**Comment by cyplo** [comment]
Hi ! Currently `cargo install racer` and `cargo install rustfmt` take a lot of time. It seems that most of the dependencies are duplicated, i.e. racer and rustfmt use same crates in the same versions and would benefit from shared compilation cache. Is that part of the envisioned solution here ?

**Comment by alexcrichton** [comment]
@cyplo I'd be ok if it weren't part of the first solution, but I think as a long term goal that's definitely something to strive for!

**Comment by durka** [comment]
Seems like two PRs #2601 #3075 have stalled out trying to implement this. I'm going to try to pick it up, wish me luck!
