### ISSUE TITLE
Allow -q (quiet) to override verbose from config

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#2588]
If you set term.verbose = true in the config, you'd want the possibility to have `cargo build -q` override.

current result:
```
cargo build -q
error: cannot set both --verbose and --quiet
```

version: cargo 0.11.0-nightly (59238e8 2016-04-14)

**Comment by alexcrichton** [comment]
Seems bad!

**Comment by bluss** [comment]
Great!
