### ISSUE TITLE
`OUT_DIR` env variable is also set during crate compilation

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#2598]
but only, it seems, if there is a build script declared in the Cargo.toml.

This is not documented in [doc/environment-variables.md](https://github.com/rust-lang/cargo/blob/master/src/doc/environment-variables.md). I hope this is just an omission in the docs and not a bug. Because we are using this feature in [rustup.rs](https://github.com/rust-lang-nursery/rustup.rs). :smile:

**Comment by japaric** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Ah yeah this is definitely intentional and just an accidental omission from the docs

**Comment by ehuss** [comment]
Closed in #3758.
