### ISSUE TITLE
rerun-if-changed on directory does not rerun on new timestamp or file contents

### ISSUE THREAD

**Issue by durka** [rust-lang/cargo#2599]
I did `println!("cargo:rerun-if-changed=dir")` where `dir` is a directory in the same directory as `Cargo.toml`.

I expected the build script to rerun if any file within `dir` changes its timestamp or contents. However, it only reruns if files are created or deleted.

I have created a quick-and-dirty test script in [this crate](https://github.com/durka/rrict). This is the output:

```
$ uname -mrs
Darwin 13.4.0 x86_64
$ cargo -V
cargo 0.11.0-nightly (d99a7eb 2016-04-19)
$ ./test.sh
......
[PASS] no rerun with no changes
[FAIL] no rerun with changed timestamp
[PASS] rerun with new file
[FAIL] no rerun with changed file contents
[PASS] rerun with deleted file
```

cc @huonw

**Comment by durka** [comment]
This is not a regression. Same pattern with cargo 0.9 and 0.10.

**Comment by durka** [comment]
For sanity: deleting both `rerun-if-changed` lines from `build.rs` this is the output:

```
$ ./test.sh
......
[FAIL] rerun with no changes
[PASS] rerun with changed timestamp
[PASS] rerun with new file
[PASS] rerun with changed file contents
[PASS] rerun with deleted file
```

**Comment by alexcrichton** [comment]
Yeah this is actually intended behavior. Cargo does not traverse a directory and try to find changes inside, but rather it just looks at the mtime of the directory itself (which can vary depending on platform when it's updated).

This was discussed in the [original implementation](https://github.com/rust-lang/cargo/pull/2134) and the special support for directories was [explicitly removed](https://github.com/rust-lang/cargo/pull/2134#issuecomment-155911513).

Thanks for the report though!

**Comment by durka** [comment]
Please reopen as docs bug, as this is not clear at all.

**Comment by durka** [comment]
So how do I say "please rerun the build script if files are created or deleted **or changed** within this dir"? Do I need to print a line for the directory itself and every file/directory within it?

**Comment by alexcrichton** [comment]
Ah yeah a docs bug is fine.

And yeah, you'll need to print a line per file in the directory you care about.

**Comment by huonw** [comment]
Could `rerun-if-changed` support globs?

**Comment by alexcrichton** [comment]
Perhaps, yeah, but it's arguably much simpler to keep track of specific files (someone's gonna have to do it).

**Comment by umaYnit** [comment]
Is there a way to add extra file detection, but overwrite the default?
I want to be able to re-run the build script when all source code and git changes.

**Comment by mdegans** [comment]
I need to run `build.rs` if any file at all in my project is changed. Is this possible at all? It seems like this should be the default.

**Comment by kupiakos** [comment]
Note from the future: Cargo will rescan an entire directory recursively for changes, done in https://github.com/rust-lang/cargo/commit/cee088b0db01076deb11c037fe8b64b238b005a2.
