### ISSUE TITLE
Can not update registry

### ISSUE THREAD

**Issue by netroby** [rust-lang/cargo#2605]
```
cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository

Caused by:
  [23/-1] error authenticating: 

```

I am sure i can using browser to open https://github.com/rust-lang/crates.io-index
and i can using curl to get it

**Comment by netroby** [comment]
After upgrade to rust lang 1.8.0 
```
 cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [23/-1] username does not match previous request

```

**Comment by alexcrichton** [comment]
Do you perhaps have an `insteadOf` entry in you `~/.gitconfig`? I believe that a better error message happens on nightly, but Cargo is [known to not work](https://github.com/rust-lang/cargo/issues/2078) with `insteadOf` configuration.

**Comment by netroby** [comment]
Oh, yes. i have insteadOf settings.

But golang working currect. why cargo not working ?

**Comment by netroby** [comment]
see https://github.com/rust-lang/cargo/issues/2078
Now i changed the gitconfig , and it's working now
