### ISSUE TITLE
Deterministic build order of crates

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2607]
Benchmarking on a multicore system would benefit from being able to replay compilations in the exact same order. 

The biggest source of variability presently is when memory hogging crates get bunched up together leading to swapping.

A deterministic compilation switch is probably not worth the effort, but the ability to simply dump the last build order to a toml file and feed it back to cargo could help with reproducible benchmarking. 

Or is it already possible perhaps?

**Comment by gnzlbg** [comment]
you are not alone!
