### ISSUE TITLE
Consider showing future incompatible warnings from dependencies

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#2609]
Consider showing future incompatible warnings from dependencies; otherwise projects may not have a head's up before that warning turns into an error one day.

Example: lalrpop depends on petgraph `^0.1.11`, so they get version `0.1.18` from the registry. Version 0.1 is not receiving updates for whatever reason. There's a new future incompatible warning discovered that applies to all existing versions, and the 0.2 branch gets an update (0.2.6) that addresses it.

If the warning is not visible, then the rdeps of petgraph don't get any notice until their projects stop building. With the warning, they can maybe be encouraged to switch to the 0.2 version by themselves.

**Comment by alexcrichton** [comment]
This is somewhat related to https://github.com/rust-lang/cargo/issues/2608, although it wouldn't solve this precisely

**Comment by epage** [comment]
Since this was opened, future incompats are shown for dependencies.  Closing this as resolved.
