### ISSUE TITLE
RFC: Load environment variables from files

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/cargo#2612]
# Problem

Build projects with **openssl** is hard.
It is required to specify environment variables.

```
env OPENSSL_LIB_DIR=C:/OpenSSL-Win64 OPENSSL_INCLUDE_DIR=C:/OpenSSL-Win64/include cargo build
```

I use VSCode.
VSCode does not support passing environment variables to cargo process.
I want to develop on Windows easy.
This RFC make development on Windows more easier.
# Solution

Cargo should load environment variables from _**.toml_\* files in directory **env** near **Cargo.toml**.
## Why not load from single file

This mechanism may be used for different purposes also.
Sometimes there are private configurations (may vary for developer) and common configurations (common for each developer within project).
## My problem solution

With this feature I'd have

```
project/
    env/private.toml
    Cargo.toml
```

**env/private.toml**

```
OPENSSL_LIB_DIR=C:/OpenSSL-Win64
OPENSSL_INCLUDE_DIR=C:/OpenSSL-Win64/include
```

I'd build project with simple `cargo build`.

**Comment by epage** [comment]
Would [`.cargo/config.toml`s `[env]` table](https://doc.rust-lang.org/cargo/reference/config.html#env) work for this?

**Comment by weihanglo** [comment]
> Would [`.cargo/config.toml`s `[env]` table](https://doc.rust-lang.org/cargo/reference/config.html#env) work for this?

Yep `[env]` should resolve this. Move forward and close this. Should you have any issue, please let us know. Thank you.
