### ISSUE TITLE
Prepopulate examples and tests directories

### ISSUE THREAD

**Issue by sandeep-datta** [rust-lang/cargo#2613]
I think it might be useful if we pre-populate the `examples` and `tests` directories with some minimalistic files when creating new crates using cargo new. It might encourage newcomers to explore and make use of these options.

Proposed templates: https://github.com/sd-rust/templates
Files changed: lib.rs, basic.rs, test.rs, README.md, Cargo.toml :)

*Note: executable crates should probably not have the examples directory*

**Comment by steveklabnik** [comment]
I am 50/50 on this. The current minimalism is really nice. At the same time, I can see how these features may not be advertised well enough.

**Comment by sandeep-datta** [comment]
What if we add a command line switch for creating a "bare" crate to `cargo new`?

**Comment by alexcrichton** [comment]
I'd probably prefer a flag the other way around (generate a "full skeleton") rather than switch the defaults, but sounds reasonable to me!

**Comment by killercup** [comment]
This seems related to #396 and #1747 (project templates).

**Comment by sandeep-datta** [comment]
Yup project templates can definitely take care of this.
