### ISSUE TITLE
Parsing of RUSTFLAGS broken in cargo

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2618]
```rust
RUSTFLAGS='-C link-args="-s -fPIC"' rustc hello.rs //OK
````
```rust
RUSTFLAGS='-C link-args="-s -fPIC"' cargo build // error: Unrecognized option: 'f'
````

**Comment by alexcrichton** [comment]
Thanks for the report! As mentioned [in the documentation](http://doc.crates.io/environment-variables.html#environment-variables-cargo-reads), however, the `RUSTFLAGS` argument is currently space separated, so you can't pass arguments with nested spaces (e.g. this behavior is intentional)

**Comment by huonw** [comment]
Isn't that worth considering that intentional behaviour as incorrect (i.e. a bug)?

**Comment by petevine** [comment]
In any case, the fact quoting works for rustc, but not cargo, is a nasty surprise.

-original message-
Subject: Re: [rust-lang/cargo] Parsing of RUSTFLAGS broken in cargo (#2618)
From: Huon Wilson <notifications@github.com>
Date: 26.04.2016 07:23

Isn't that worth considering that intentional behaviour as incorrect (i.e. a bug)? 

---

**Comment by huonw** [comment]
I... don't think the `rustc` looks at `RUSTFLAGS` at all, since one can just pass the arguments directly when invoking the `rustc` binary. (In other words, the "OK" case is the same as just running `rustc hello.rs` by itself.)

**Comment by petevine** [comment]
Rustc ignoring RUSTFLAGS?? 

Until now I've been convinced it didn't as the quoted string works as expected during bootstrap. But it seems it might be passed directly indeed by the make scripts.

-original message-
Subject: Re: [rust-lang/cargo] Parsing of RUSTFLAGS broken in cargo (#2618)
From: Huon Wilson <notifications@github.com>
Date: 26.04.2016 16:40

I... don't think the `rustc` looks at `RUSTFLAGS` at all, since one can just pass the arguments directly when invoking the `rustc` binary. (In other words, the "OK" case is the same as just running `rustc hello.rs` by itself.)

---

**Comment by alexcrichton** [comment]
> Isn't that worth considering that intentional/documented behaviour as incorrect (i.e. a bug)?

The space separation was discussed a good bit on the [original implementation PR](https://github.com/rust-lang/cargo/pull/2241), and the decision was to defer it for now. `RUSTFLAGS` is space separated, and `build.rustflags` is correctly already a vector in TOML.

> or maybe you know of a work-around that means this isn't a total impossibility?

Unfortunately, I know of no workaround beyond [this RFC](https://github.com/rust-lang/rfcs/pull/1509).

> In any case, the fact quoting works for rustc, but not cargo, is a nasty surprise.

No, the quoting is parsed by the shell, not rustc.

**Comment by petevine** [comment]
> No, the quoting is parsed by the shell, not rustc.

Right, the modified first example should look like this:

`$ export RUSTFLAGS='-C link-args="-s -fPIC"'`
`$ rustc hello.rs $RUSTFLAGS`
`error: Unrecognized option: 'f'.`

Consistent!
