### ISSUE TITLE
Frequent failure caused by 302

### ISSUE THREAD

**Issue by louy2** [rust-lang/cargo#2626]
Building servo with

```
./mach build --release
```

```
Caused by:
  failed to get 200 response from https://crates.io/api/v1/crates/quasi/0.9.0/download
Response {302, transfer-encoding: chunked, connection: keep-alive, keep-alive, set-cookie: ......; HttpOnly; Secure; Path=/, location: https://crates-io.s3-us-west-1.amazonaws.com/crates/quasi/quasi-0.9.0.crate, server: nginx, strict-transport-security: max-age=31536000, date: ......, via: 1.1 vegur, ]
```

On one hand, it seems cargo failed to follow the redirection replied by 302. On the other, simply rerunning the command would continue normally.

**Comment by alexcrichton** [comment]
This seems odd... and perhaps a bug with our curl bindings? Dealing with 302 should be handled automatically in theory.

**Comment by carols10cents** [comment]
I would have expected this issue to have a lot more activity if this continued to be an issue for everyone; since it hasn't gotten that activity, I'm going to close this. Thanks!!
