### ISSUE TITLE
Failed to resolve address (https://github.com/rust-lang/crates.io-index)

### ISSUE THREAD

**Issue by laktak** [rust-lang/cargo#2637]
Cargo is unable to connect to github on OS X (installed via nix, not using a proxy):

```
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [12/-1] Failed to resolve address for https: nodename nor servname provided, or not known
$ ping github.com
PING github.com (192.30.252.122): 56 data bytes
64 bytes from 192.30.252.122: icmp_seq=0 ttl=45 time=117.037 ms
64 bytes from 192.30.252.122: icmp_seq=1 ttl=45 time=116.741 ms
^C
--- github.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 116.741/116.889/117.037/0.148 ms
```

I have a Ubuntu VM on the same machine where Cargo can connect just fine (also installed via nix).

**Comment by alexcrichton** [comment]
Looks like a bug in URL parsing somewhere along the line? It looks like something is trying to resolve the hostname `https:`. Did you perhaps use an external libgit2 build rather than the bundled one?

**Comment by laktak** [comment]
I'm completely new to rust/cargo. What I did was install it via `nix-env -i rustc cargo` on OS X (where it fails) and Ubuntu (where it works).

Is this a problem of the *nix* distribution?

**Comment by alexcrichton** [comment]
Maybe? I've also no idea how Cargo-in-nix works, so it could also be totally unrelated. Unfortunately without a way to reproduce locally this may be very difficult to debug.

**Comment by obadz** [comment]
```
$ cargo build --verbose
could not find `Cargo.toml` in `/home/obadz` or any parent directory
```

What's the simplest thing I could check out to reproduce?

**Comment by laktak** [comment]
@obadz  try:

```
$ git clone https://github.com/serde-rs/json
$ cd json/json
$ cargo build --verbose
```

**Comment by retrry** [comment]
Could problems arise from using different Cargo and rustc versions? Nix is using Cargo 0.9.0 with rust 1.8.0?

**Comment by laktak** [comment]
The official dist (where it works) uses

```
$ cargo -V
cargo 0.9.0-nightly (8fc3fd8 2016-02-29)
$ rustc -V
rustc 1.8.0 (db2939409 2016-04-11)
```

**Comment by mpkh** [comment]
saw the same on suse

**Comment by laktak** [comment]
Not using nix anymore.
