### ISSUE TITLE
OpenSSL downloads on nightlies are guaranteed to eventually fail

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#2638]
Looks like OpenSSL doesn't host source tarballs at `/sources` forever, only the current one. Older ones can be found in `/sources/old`, but the _most recent_ release cannot be found in `/sources/old`.

We'll need to figure out a way to download from one of two URLs to make the download more robust. We'll almost always want to use the most recent version, but when that switches over we'll still want to be able to land things while we go and update.

**Comment by carols10cents** [comment]
I don't think this is an issue in this repo at least, since https://github.com/rust-lang/cargo/commit/50a46f47086c01effe195ad6a1566f7cf9084fb5#diff-7e056ddc530791272d363e50c1f25647L335, so I'm closing. Please reopen if I'm incorrect!
