### ISSUE TITLE
manpages for cargo are seriously lacking

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#2645]
The manpage for cargo only lists the commands available, but there isn’t any documentation on flags etc for the commands.

**Comment by istankovic** [comment]
Is this still relevant? Current cargo (0.19.0-nightly (fa7584c14 2017-04-26)) has a main main page, that lists all the commands without options, however there are separate man pages for commands, and those do list the options.

**Comment by alexcrichton** [comment]
Indeed yeah, I think things have improved quite a bit, thanks for the ping @istankovic!
