### ISSUE TITLE
error when attempting to dynamically link with interwoven dependencies.

### ISSUE THREAD

**Issue by posix4e** [rust-lang/cargo#2659]
I'm trying to create a dynamic library for postgresql to run as a logical decoder in rust.
The change I'm trying to make is  at https://github.com/posix4e/jsoncdc/tree/autogenerated.

I'm trying to take my rust postgresql  extension and break out the postgresql generic parts. Specifically the parts in regards to making postgresql extensions in rust. Code which is running in the postgresql server needs access to the internal postgresql api to understand the callbacks it's going to receive. The problem is that when I go from one crate to many I start getting linking errors. I now have 3 layers of crates, where I had one:

- rpg94-sys,rpg95-sys these are autogenerated bindings to postgresql
- rpg some useful functions for writing postgresql extensions 
- jsoncdc a postgresql extension 

The error I receive is 

error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "..."
note: Undefined symbols for architecture x86_64:
  "_row_to_json", referenced from:
      decoder::row_to_json::__rust_abi in rpg-29c63f7bad060f77.0.o
....
      decoder::change::hb0f127f8fea09f79nda in rpg-29c63f7bad060f77.0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
Could not compile `rpg`.

Where do I even begin?

**Comment by alexcrichton** [comment]
Unfortunately I can't reproduce b/c I don't know where the relevant headers come from, but I suspect that this isn't Cargo-related and instead is because a native library is being linked in the wrong place by accident. It should be the case that a crate with `extern { ... }` symbols is the one that links to the native library those symbols come from, are you sure that's still the case?

**Comment by posix4e** [comment]
Oh your totally right. Make actually seems to work with some small changes
