### ISSUE TITLE
Output of cargo metadata may not be machine-readable if the registry needs to be updated

### ISSUE THREAD

**Issue by SSheldon** [rust-lang/cargo#2661]
Repro steps:

1. `rm Cargo.lock`
2. `cargo metadata`

Observe that the JSON output is preceded by:
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

A workaround is possible by running `cargo metadata --quiet`, but I can't really imagine that output being wanted in a command whose output is supposed to be machine-readable.

It's a pretty easy edge case to miss since usually your registry doesn't need to be updated. It bit me in SSheldon/rust-test-ios#3.

**Comment by SSheldon** [comment]
Oh and I'm running `cargo 0.9.0-nightly (8fc3fd8 2016-02-29)`, apologies if this has since been fixed but I couldn't find anything by searching.

**Comment by alexcrichton** [comment]
cc @matklad, I wonder if perhaps `cargo metadata` should imply a quiet shell by default? Either that or perhaps https://github.com/rust-lang/cargo/issues/1473 would fix this

**Comment by matklad** [comment]
>but I can't really imagine that output being wanted in a command whose output is supposed to be machine-readable.

Actually we want that output in IntelliJ-Rust :) `cargo metadata` may take a while for downloading dependencies, so we use `updating registry` and `downloading foo` messages to show a progress bar. 

We can make `metadata` quite by default, and use `--verbose` to override this.

However I would argue that quite by default is a bad behavior.  `metadata` will cause dependencies to be resolved and downloaded, and you really want to see the feedback. If `cargo metada` runs for 10 minutes, you want to know if you Internet is slow, or if you wi-fi died, or if maybe `cargo` is just stuck picking the versions. 

#1473 seems like the correct solution here. 

Another option is to better document current behavior and to make sure that something (`Registry is up to date`?) is always printed before the JSON.

**Comment by alexcrichton** [comment]
Interesting! Sounds like #1473 is the right solution

**Comment by matklad** [comment]
closed by https://github.com/rust-lang/cargo/pull/2722

**Comment by alexcrichton** [comment]
🎊

**Comment by matklad** [comment]
So this will hit stable Rust with 1.10? I need to remember to fix progress reporting on the IntelliJ side

**Comment by alexcrichton** [comment]
Yeah that sounds right!
