### ISSUE TITLE
To determine executing cargo command from build script

### ISSUE THREAD

**Issue by astavonin** [rust-lang/cargo#2671]
Sometimes it's important to know currently executing cargo command (build, clean, etc.) inside build script for handling internal stuff. For example:
`cargo build` – compile/recompile foreign C++ library;
`cargo clean` – clean foreign C++ library..? There is now way to distinguish `cargo build` from `cargo clean` inside build script.

**Comment by alexcrichton** [comment]
Currently Cargo doesn't actually run scripts on clean, so the answer here is simple in that it's always build!

Running a build script, however, on cleaning is tracked over at https://github.com/rust-lang/cargo/issues/2573, so I'm gonna close this in favor of that, but thanks for the report!
