### ISSUE TITLE
Manpage does not document all the commands

### ISSUE THREAD

**Issue by hatsunearu** [rust-lang/cargo#2689]
cargo has a "secret" command called rustc that allows the user to input extra flags to pass-through to rustc in addition to the flags cargo normally provides to rustc during build. This feature is not documented in the manpage.

I'd like to do a PR but first I need to figure out what features the rustc command has.

edit: PR created:  #2690

**Comment by carols10cents** [comment]
This was fixed in https://github.com/rust-lang/cargo/pull/2690, but it looks like the changes got lost in https://github.com/rust-lang/cargo/pull/2706 :(

**Comment by raytung** [comment]
@carols10cents Mind if I pick this up?

**Comment by gibix** [comment]
I think this issue can be closed

**Comment by carols10cents** [comment]
Looks like it! Thanks!
