### ISSUE TITLE
Turn a warning for a bad crate type into hard error

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2692]
This is the follow up of #1914 

Currently `Cargo` will only warn you if you had a bad crate type in your `Cargo.toml`, like

```
        [lib]
        crate-type = ["bad_type", "rlib"]
```

Perhaps we should produce a hard error instead? 

The intention of #1914 was to issue a warring first and then to turn it into an error, but looks like the second part has not happened yet.

**Comment by alexcrichton** [comment]
In retrospect with the addition of the `cdylib` crate type we probably should just specially recognize things like "rlib" and pass everything else through to the compiler (to be more forwards compatible)

**Comment by thirtythreeforty** [comment]
If everything would get forwarded to the compiler, why does `rlib` need special treatment?

**Comment by alexcrichton** [comment]
Ah it's just a suspicion of mine. I think we enable some features for rlibs like doctests which we don't do for other crate types like staticlibs

**Comment by carols10cents** [comment]
This warning was removed in 3f7b09ccc925d4c357236fd94fdd3d90f535e2c1 so I'm closing this :)
