### ISSUE TITLE
Generate table of contents for docs at http://doc.crates.io

### ISSUE THREAD

**Issue by smaximov** [rust-lang/cargo#2694]
It would be nice to have TOCs for documentation articles. TOC gives a summary of topics an article addresses and allows to quickly navigate between sections.
### How it can be implemented
- Place some marker (e.g. `%TOC%`) in a Mardown file:
  
  ``` markdown
  % Cargo Guide
  
  Welcome to the Cargo guide. This guide will give you all that you need to know
  about how to use Cargo to develop Rust projects.
  
  %TOC%
  
  # Why Cargo exists
  ...
  ```
- Use some tool ([first hit in google](https://github.com/ekalinin/github-markdown-toc), actually works) to generate TOC.
- Replace the marker with the generated TOC.
### Mockups

Simple TOC:

![toc](https://cloud.githubusercontent.com/assets/1370047/15275596/6572eaea-1b13-11e6-8b20-6ca9ae3a6979.png)

Fixed ("sticky") sidebar TOC:
![toc-fixed](https://cloud.githubusercontent.com/assets/1370047/15275597/6573472e-1b13-11e6-9e97-85f3f9833db5.png)

**Comment by alexcrichton** [comment]
cc @steveklabnik, @carols10cents

**Comment by steveklabnik** [comment]
I like this idea a lot. I think I like the second version better.

**Comment by carols10cents** [comment]
YES love it!! Just to be clear, in the 2nd mockup, the TOC would be `position: fixed` or `position: sticky` and remain visible as you scroll, correct? That would be awesome.

**Comment by smaximov** [comment]
> Just to be clear, in the 2nd mockup, the TOC would be `position: fixed `or `position: `sticky and remain visible as you scroll, correct?

Yes, that's exactly what I meant. I believe it will be much more usable that way than with just absolute positioning.

**Comment by istankovic** [comment]
When it comes to cargo docs, I'd vote for this to have the highest priority. The current cargo docs layout has serious usability issues and having a TOC would help a lot. In fact, I'd much rather see cargo docs mimic https://doc.rust-lang.org/book, which makes it much easier (still not ideal, but definitely miles ahead compared to what we have here) to get around and get to the necessary bits.

**Comment by carols10cents** [comment]
> In fact, I'd much rather see cargo docs mimic https://doc.rust-lang.org/book

Good news! [That's exactly the plan](https://github.com/rust-lang/rfcs/blob/master/text/1828-rust-bookshelf.md), it's just that there's only so much time and not very many people contributing towards this goal at the moment.

**Comment by istankovic** [comment]
That is indeed good news, thanks for the info.

**Comment by carols10cents** [comment]
Related: #4040

**Comment by dwijnand** [comment]
This think this can be closed now. The cargo docs now use mdbook, and thus have a sidebar TOC.

**Comment by alexcrichton** [comment]
Indeed!
