### ISSUE TITLE
Cargo silently ignores git revision when branch is specified

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#2695]
If a dependency specifies both a branch and a commit hash, then the commit hash is silently ignored. Either cargo should error if both are specified, or the commit hash should take precedence (and ideally, if this option is chosen, cargo should check that the specified commit is in the history of the branch).

**Comment by matklad** [comment]
Should be closed by #2940!

**Comment by alexcrichton** [comment]
Yay!
