### ISSUE TITLE
`cargo rustc` should have an `--all-targets` option

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#2702]
See also: https://github.com/Manishearth/rust-clippy/issues/935

Tools like `cargo check` and `cargo clippy` use `cargo rustc`, but they don't need the extra restriction of having to specify a single target. It would be nice if cargo rustc/rustdoc had an `--all-targets` or `--allow-multiple-targets` option that could be used here.

**Comment by alexcrichton** [comment]
Got a chance to talk about this with @wycats today and the conclusion was that this flag shouldn't be added for now. The workflow being created, `cargo clippy`, is using `cargo rustc` as an implementation detail, and it can just run multiple `cargo rustc` invocations with the relevant filters. Targets can already be learned about programmatically through `cargo metadata` so the plumbing should all be there.

Along those lines it doesn't quite make sense just yet to add new functionality to `cargo rustc` for just these use cases as it's intended to be a *primitive*, not necessarily ergonomic to call
