### ISSUE TITLE
Enforce crate naming rules of rustc

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/cargo#2708]
## Actual behavior

Creating a new crate:

``` sh
cargo new --bin 'UPPERcase_name'
```

No issue.

Compiling it:

``` sh
 cargo build
```

```
warning: crate `UPPERcase_name` should have a snake case name such as `uppercase_name`, #[warn(non_snake_case)] on by default
```
## Expected behavior

Cargo should only create crates with names that raise `rustc` warnings if forced.
## Meta

```
  rustc --version --verbose
rustc 1.8.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.8.0
```

```
  cargo --version
cargo 0.10.0 (10ddd7d 2016-04-08)
```

**Comment by gsurrel** [comment]
I would say that it should warn before creation that it's not according to rules and offer the following options:

1. Edit the name
1. Continue
1. Continue and add the ignore directive where needed

**Comment by shnaramn** [comment]
Can I try a fix for this?  I've just started learning rust/cargo and this feels like a good first fix.

There are several validations for crate name at function check_name in [cargo_new.rs](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_new.rs).  Will adding a warning (similar to the existing ones) about the casing be a good fix?  The existing validations don't prompt for a new name.  Want to be consistent with the existing behavior.

**Comment by epage** [comment]
So long as its only a warning, I feel that is the most we should do.  My main concern about a warning is making sure we get the language right to  give people a heads up without coming across to strong (since they can just `allow` it or ignore it).  I wonder if we should also check the status of the warning in the lints table (#12115).

**Comment by sanmai-NL** [comment]
Rather than warning or not warning you could just be informative. Something like this name doesn't match the naming rules standard X, please see documentation blah blah blah blah.

**Comment by epage** [comment]
How is that different from a warning?

**Comment by sanmai-NL** [comment]
A warning is a value judgment.

**Comment by shnaramn** [comment]
If this change looks good, I can start a PR: 
https://github.com/rust-lang/cargo/compare/master...shnaramn:cargo:WarnAboutNameCase

**Comment by epage** [comment]
Theres details to work out in  a PR but that is the general direction of what I'd expect.
