### ISSUE TITLE
How can I know if C code I'm including needs -fPIC?

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#2712]
As part of my package I need to build and link a C file. In my `build.rs` I'm launching `./configure && make` and link with that. It works on OS X, but when run on Linux it fails to link with error (probably same as #713):

> target/debug/deps/foo.rlib(foo.o) … can not be used when making a shared object; recompile with -fPIC

Obviously in this case I can add the flag, but I wonder is `-fPIC` *always* required for Rust? Always on Linux? 

Does cargo set something like `CFLAGS` that I should pass to my C toolchain to portably compile with correct flags?

**Comment by alexcrichton** [comment]
I'd recommend using the gcc crate for this as it should handle cases like this plus all sorts of cross compilation, but in general the answer is "always" and there's no way to tell if the compiler was configured to not emit a position-independent output right now.

**Comment by pornel** [comment]
Thanks. I'll be adding the flag then. I can't use the gcc crate, as it isn't compatible with configure && make toolchain.
