### ISSUE TITLE
Cargo chokes on duplicate entry

### ISSUE THREAD

**Issue by petevine** [rust-lang/cargo#2715]
```shell
$ cargo build
thread '<main>' panicked at 'a package was referenced twice in the lockfile', src/cargo/core/resolver/encode.rs:51
````

**Comment by alexcrichton** [comment]
Could you describe how you got into this situation or provide the example Cargo.lock?

**Comment by petevine** [comment]
I edited one of the Cargo.lock dependencies without noticing the upgraded crate version was also present.

**Comment by alexcrichton** [comment]
Yeah that's not supported, you should use `cargo update -p`. It's possible though to produce a better error message in cases like this.

**Comment by petevine** [comment]
But seriously, I'd like to see some sort of `--force` flag to make updating from the command line possible, in cases like [this](https://github.com/willi-kappler/mandel-rust/blob/c0a5ba364492ab033ed2150cc4efb95d187762b8/Cargo.toml), just to see if it could work.

A sort of a one-time `paths` override.
