### ISSUE TITLE
cargo-0.10.0 fails to install from source

### ISSUE THREAD

**Issue by postmodern** [rust-lang/cargo#2717]
### Steps to Reproduce

1. Install rustc-1.8.0 from source:

        wget https://static.rust-lang.org/dist/rustc-1.8.0-src.tar.gz
        tar xzvf rustc-1.8.0-src.tar.gz
        cd rustc-1.8.0/
        ./configure && make && make install
        rustc --version

2. Install cargo-0.10.0 from source:

        wget -O cargo-0.10.0.tar.gz https://github.com/rust-lang/cargo/archive/0.10.0.tar.gz
        tar xzvf cargo-0.10.0.tar.gz
        cd cargo-0.10.0/
        ./configure && make && make install

### Expected Result

`cargo` is installed into `/usr/local/bin`

### Actual Result

<pre>
sh /usr/local/src/cargo-0.10.0//src/rust-installer/gen-installer.sh --product-name=Rust --rel-manifest-dir=rustlib --success-message=Rust-is-ready-to-roll. --image-dir=target/x86_64-unknown-linux-gnu/release/dist/cargo-0.10.0-x86_64-unknown-linux-gnu-image --work-dir=./target/x86_64-unknown-linux-gnu/release/dist --output-dir=./target/x86_64-unknown-linux-gnu/release/dist --non-installed-overlay=target/x86_64-unknown-linux-gnu/release/dist/cargo-0.10.0-x86_64-unknown-linux-gnu-overlay --package-name=cargo-0.10.0-x86_64-unknown-linux-gnu --component-name=cargo --legacy-manifest-dirs=rustlib,cargo
sh: /usr/local/src/cargo-0.10.0//src/rust-installer/gen-installer.sh: No such file or directory
Makefile:320: recipe for target 'target/x86_64-unknown-linux-gnu/release/dist/cargo-0.10.0-x86_64-unknown-linux-gnu.tar.gz' failed
make: *** [target/x86_64-unknown-linux-gnu/release/dist/cargo-0.10.0-x86_64-unknown-linux-gnu.tar.gz] Error 127
</pre>

Note: `src/rust-installer/gen-installer.sh` actually exists in the `rustc-1.8.0/` source directory.

**Comment by alexcrichton** [comment]
Yes unfortunately the release tarballs on github aren't suitable as they don't include submodules, and otherwise this is covered by https://github.com/rust-lang/cargo/issues/2107, so I'm going to close in favor of that.

Thanks for the report though!
