### ISSUE TITLE
Support wget as a build dependency in src/etc/download.py

### ISSUE THREAD

**Issue by postmodern** [rust-lang/cargo#2718]
`wget` is installed by default on most Linux distros. It's also designed specifically for downloading files; where as `curl` is designed for doing HTTP(S) communication. It should be easy to scan `os.path` or use `shutil.which()` to check if `wget` or `curl` is present.

**Comment by alexcrichton** [comment]
This was removed from the configure script awhile back, so I believe this issue is no loner relevant.
