### ISSUE TITLE
Manpage erroneous "new executable project" example

### ISSUE THREAD

**Issue by WillemMali** [rust-lang/cargo#2731]
In the examples section there's an example for "Create a new project that builds an executable", with the following code:

`cargo new --init foobar`

This is my first hour with Rust but I really think this should be:

`cargo new --bin foobar`

I'm on the latest stable, just installed via rustup.sh. I don't think this should be too hard to fix, but I don't want to jump to learning your contributing rules before learning anything beyond println!

(As an aside: wow, the learning curve to rust has surprisingly been very, very smooth, great job! The "Getting started" docs are a joy to work through. The manpages are still lacking, though, using --help for now.)

**Comment by alexcrichton** [comment]
cc @carols10cents
