### ISSUE TITLE
unsupported protocol from cargo install rustfmt

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/cargo#2732]
```
$ cargo install rustfmt -v
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustfmt v0.5.0
error: failed to download package `rustfmt v0.5.0` from https://crates.io/api/v1/crates/rustfmt/0.5.0/download

Caused by:
  Unsupported protocol
```

I built rust and cargo from git a week or so ago. Updated cargo to HEAD and built again, still get this error.

**Comment by alexcrichton** [comment]
Yeah this can happen if libgit2 wasn't configured correctly to have https support, what system did you build cargo on?

**Comment by rbtcollins** [comment]
My Ubuntu xenial system.

**Comment by rbtcollins** [comment]
libgit2 isn't installed via the package manager (and I haven't installed it by hand).
```
dpkg -l libgit*
dpkg-query: no packages found matching libgit*
```

**Comment by rbtcollins** [comment]
I did:
```
sudo rm -rf target
make
sudo make install
```

and now cargo is happy. I'm not sure if you wish to consider this a valid bug or not. Perhaps a FAQ would be good though?

**Comment by alexcrichton** [comment]
Ah yeah libgit2 is built from source. Did you perhaps install a library as part of the build when something else failed?

**Comment by rbtcollins** [comment]
Nope, but I've had that build dir around for ages; I couldn't tell you how
deep the junk was.

**Comment by alexcrichton** [comment]
It may have just been a stale build of libgit2 then or something like that? There's been a few fixes to the detection of system deps in libgit2, and cargo tests at least fail if https support isn't built in. I'm gonna close this for now as "probably fixed at some point" or "likely spurious", but thanks for the report!
