### ISSUE TITLE
Please start with "What is Cargo"

### ISSUE THREAD

**Issue by guettli** [rust-lang/cargo#2733]
I was interested in "Rust package metadata" and read the top of this page:

  http://doc.crates.io/index.html

What do I read? How to install it and how to start a new project with "cargo new".

Why not start with the basics first? What is cargo about?

**Comment by alexcrichton** [comment]
cc @steveklabnik, @carols10cents

**Comment by carols10cents** [comment]
Oh hmmm... there is info about what cargo is and why it exists at the top of The Guide: http://doc.crates.io/guide.html 

Should we fold http://doc.crates.io/index.html into the guide and call it "Getting Started Guide" in the menu?

**Comment by carols10cents** [comment]
Also @guettli, I'm not sure what kind of information about Rust package metadata you were looking for-- did you find what you wanted to know? 

My best guess for what you might have been looking for is this page listed in the menu as "Cargo.toml format": http://doc.crates.io/manifest.html, which might make sense once you've read about Cargo and its manifest, but probably isn't understandable before then.

Thank you for bringing this up, I'd love to help make it easier for people to find the info they're looking for!!

**Comment by guettli** [comment]
I found all information below "Why Cargo exists".

I just ask myself why the first paragraph of the main page for so many great applications start with "how to install...".

Why not start with the basic information first? I guess programmers love details more than the big pictures :-)

In the past installing projects (in general) was difficult. Today it is quite easy. 

My hint: Start with the big pictures. Then explain the details.

**Comment by dwijnand** [comment]
Seeing as the first thing you read in https://doc.rust-lang.org/cargo/ is:

> Cargo is the [Rust] *package manager*. Cargo downloads your Rust project’s
dependencies, compiles your project, makes packages, and upload them to
[crates.io], the Rust community’s *package registry*.

[rust]: https://www.rust-lang.org/
[crates.io]: https://crates.io/

I would say this issue has been resolved and can be closed now.

**Comment by alexcrichton** [comment]
Indeed!
