### ISSUE TITLE
--color not respected?

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/cargo#2734]
This is with `cargo 0.11.0 (ca743f3 2016-05-23)` and `rustc 1.10.0-nightly (764ef92ae 2016-05-19)`.

When using `cargo build --color=never`, I get colored "Compiling" from Cargo and colored diagnostics from rustc. Conversely, when using `cargo build --color=always` and redirecting stderr to a file, I don't get ANSI escapes in the file.

Is there a config I'm missing? Environment variables?

**Comment by alexcrichton** [comment]
Oh dear! Looks like this was always being ignored for the stderr stream and just didn't show up because all output went to stdout. Should have a patch soon!
