### ISSUE TITLE
-q suppressing stderr output, but not all of it

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/cargo#2735]
This is with `cargo 0.11.0 (ca743f3 2016-05-23)` and `rustc 1.10.0-nightly (764ef92ae 2016-05-19)`.

The option help (checked cargo build, cargo run) says
```
-q, --quiet             No output printed to stdout
```
while most of (all of?) Cargo's messages are printed to stderr.

When using the option, some output is not suppressed, for example the `error: Process didn't exit successfully` when using `cargo run` and getting a nonzero exit status.

This makes it unnecessarily hard to use `cargo run` and capture the output of only the subprocess. (In my case, using `target/debug/foo` directly is cumbersome because the executable is partially dynamically linked and cargo is doing nice things like setting `LD_LIBRARY_PATH` correctly for me.)

**Comment by alexcrichton** [comment]
Yeah currently the shell continues to emit errors whenever it's configured in quiet mode, but this should probably be suppressed for the binary itself for `cargo run`
