### ISSUE TITLE
Clarify format of author strings

### ISSUE THREAD

**Issue by donaldpipowitch** [rust-lang/cargo#2736]
What is the correct format for author strings?

1. `name <email>` (`<email>` is optional) _or_
2. `name <email> (url)` (`<email>` and `(url)` are optional) like npm?

Thanks.

**Comment by alexcrichton** [comment]
Currently it's primarily "name <email>" where the email is optional, but we don't necessarily have many tools parsing these just yet. Adding in (url) would probably also be fine!

**Comment by donaldpipowitch** [comment]
So it is "1." for now, thanks!
