### ISSUE TITLE
UX for invalid RUSTFLAGS is poor

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#2756]
If `RUSTFLAGS` has a typo, then running `cargo` leads to error messages like:

```
$ RUSTFLAGS=wrong rustup run 1.9.0 cargo build
   Compiling blank v0.1.0 (file:///home/huon/projects/test-rust/blank)
error: multiple input filenames provided
error: Could not compile `blank`.

To learn more, run the command again with --verbose.
```

```
$ RUSTFLAGS=wrong rustup run beta cargo build
error: failed to run `rustc` to learn about target-specific information

To learn more, run the command again with --verbose.
```

```
$ RUSTFLAGS=wrong rustup run nightly cargo build
error: failed to run `rustc` to learn about target-specific information

To learn more, run the command again with --verbose.
```

Passing `--verbose` does give more info (i.e. one can see the invocation that failed and the actual rustc output, and hence hopefully connect the dots back to `RUSTFLAGS`). However, it seems like that info is always useful/shouldn't be hidden, since there's not much a user can do about "failed to run `rustc` to learn about target-specific information" (in beta and nightly).

**Comment by epage** [comment]
If we've improved the output. I'm not sure what more there is for us to do.  Like with #2559, being too smart can be its own problem.  RUSTFLAGS should likely be viewed as an advanced workflow anyways with us finding ways to adapt that workflow to users more generally (https://github.com/rust-lang/cargo/issues/12739).

I'm going to propose to the cargo team that we close this.

**Comment by weihanglo** [comment]
```
RUSTFLAGS=wrong cargo +1.74.1 build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/user/.rustup/toolchains/1.74.1-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names wrong --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: multiple input filenames provided (first two filenames are `-` and `wrong`)
```

Confirmed that as of 1.74.1, the error message is like above, so should be sufficient good to tell it's something wrong in RUSTFLAGS.

Agree on closing.
