### ISSUE TITLE
[documentation] Please, stop saying everywhere what cargo goes with rust

### ISSUE THREAD

**Issue by ghost** [rust-lang/cargo#2784]
Many texts on Rust documentations sites misleads newcomers with information on installation of Cargo. I've just built rustc from tarball and started reading https://doc.rust-lang.org/book/ . I know what rustc tarball provides rust-gdb, rustc and rustdoc executables, and when in section https://doc.rust-lang.org/book/crates-and-modules.html I've suddenly encountered mysterious "cargo new phrases" line.

At least following pages saying what "Cargo goes with Rust":
1.
"Cargo comes installed with Rust itself, if you used the official installers."
https://doc.rust-lang.org/book/getting-started.html
2.
"Rust comes with Cargo by default"
https://crates.io/install

This forced Me search rustc tarball contents for Cargo, but no traces of Cargo on the first look (except, as I've discovered farther, of tiny note in readme saying "This install does not include [Cargo]").. So I've had to use ddgo to find rust cargo. Search gave Me this page: http://doc.crates.io/index.html - and there is no fast documentation on how to get cargo tarballs. And I don't want to use Your rustup, to not make garbage in My system because of not using package manager.

I've started searching how to obtain cargo tarballs. Why You, ppl, do not making cargo tarballs? While rustc tarballs goodly enough distributed on https://static.rust-lang.org/dist/ , cargo's https://static.rust-lang.org/cargo-dist/ suddenly replies with 404.

---

please,
1. fix documentations;
2. provide cargo tarballs or include it with rustc tarballs.

**Comment by steveklabnik** [comment]
The line in Rust's docs says "if you used the official installer." Given that Rust is not in most package ma garment systems yet, it's the suggested way to install Rust.

I do agree that the Cargo docs should use the same phrasing, though.

**Comment by AnimusPEXUS** [comment]
> "if you used the official installer."
Tarballs' "make install" provided by https://static.rust-lang.org/dist/ is official enough, omho.

**Comment by steveklabnik** [comment]
It's official, but it's not an installer. Those are linked from the
"Install" page.

**Comment by alexcrichton** [comment]
Yeah for now the tarballs aren't considered the "official installer" as it's just getting the compiler, not the rest of the ecosystem.

**Comment by steveklabnik** [comment]
The OP is now gone, and a lot of this has changed. Closing!
