### ISSUE TITLE
Add man pages for all subcommands

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#2789]
`cargo owner` isn't listed in the man page for `cargo`, and doesn't have its own subcommand man page. We should have man pages for all subcommands

**Comment by munyari** [comment]
Which man pages do you refer to? Cargo doesn't seem to install anything in /usr/share/man

**Comment by Manishearth** [comment]
Depends on the OS I guess (or perhaps your method of installation doesn't set it up)? It does have man pages (https://github.com/rust-lang/cargo/tree/master/src/etc/man), which I have seen installed by default for some people.

**Comment by munyari** [comment]
On Arch Linux, 4.6.2-1-ARCH, installed with rustup 0.2.0-2 from the [AUR](https://aur.archlinux.org/packages/rustup/). Cargo 0.10.0-nightly. So in this case, it would be that rustup doesn't set up man pages? Because I don't have a man page for rustc either

**Comment by Manishearth** [comment]
Given the way rustup works, it can't install man pages. It could have a symlink but that needs to point from a root-controlled area to non-root, which is bad.

Perhaps it could stick a symlink in ~/.local/share/man but I'm not sure if that works on all Linux OSes. @brson, thoughts?

**Comment by brson** [comment]
rustup's approach to exposing man pages is with an unimplemented [`rustup man`](https://github.com/rust-lang-nursery/rustup.rs/issues/490) command. It's pretty lame but I don't know how else to do it in a way that will work consistently.

rustup might additionally install placeholder man pages that just say 'run `rustup man`'.

**Comment by Manishearth** [comment]
`rustup install-man`, perhaps?

**Comment by munyari** [comment]
Hmm, so there are proposed solutions that work for *nix systems, but not Windows, correct? What is the Windows analogue to man pages, and why can't these be used?

Excuse me if this is off-topic in cargo's issues, but rustup's README says "And it runs on all platforms Rust supports, especially Windows." Does this indicate that Windows is given higher priority than Linux/OSX/BSD/etc, or has feature parity been made a big priority of the project due to the historical difficulty of installing and using such toolchains on Windows?

**Comment by Manishearth** [comment]
man should work on mingw. There is no developer analogue on MSVC; you have help pages but MSVC sticks to online docs usually. 

This is all getting slightly off topic though. This bug is focusing on adding man page files, hot the process of installing them :smile:

**Comment by brson** [comment]
> rustup install-man, perhaps?

Perhaps. It would be the first cargo feature that needed root.

> Hmm, so there are proposed solutions that work for *nix systems, but not Windows, correct? What is the Windows analogue to man pages, and why can't these be used?

Maybe .chm files? But I think really HTML is fine for all documentation, and works everywhere. If we had the man pages generated as part of the HTML docs, rustup could load those instead.



> Excuse me if this is off-topic in cargo's issues, but rustup's README says "And it runs on all platforms Rust supports, especially Windows." Does this indicate that Windows is given higher priority than Linux/OSX/BSD/etc, or has feature parity been made a big priority of the project due to the historical difficulty of installing and using such toolchains on Windows?

The latter. I just [removed 'especially'](https://github.com/rust-lang-nursery/rustup.rs/pull/558) to eliminate this confusion.

**Comment by munyari** [comment]
Where are the man pages for subcommands actually used? It seems like calling a subcommand with the `-h` flag reads from bin/<subcommand>.rs, since owner doesn't have a man page in src/etc/man but `cargo owner -h` still shows a description of the command and its arguments

**Comment by Manishearth** [comment]
If you call `man cargo` it mentions the other subcommand man pages, e.g. `man cargo-build`

**Comment by munyari** [comment]
Are there any more still outstanding man pages?

**Comment by Manishearth** [comment]
`cargo rustc`, `cargo rustdoc`, etc. Diffing `src/bin/` with the list of man pages, I get:

```
fetch
generate_lockfile
git_checkout
help
locate_project
login
metadata
pkgid
read_manifest
rustc
rustdoc
uninstall
verify_project
version
yank
```

The ones with underscores aren't so important, nor is `help`.

**Comment by munyari** [comment]
Thanks. And if I added multiple man pages, would you want these all done on the same branch/PR or should one make a separate PR for each page?

**Comment by alexcrichton** [comment]
@munyari one PR is fine, thanks!

**Comment by keeperofdakeys** [comment]
Since this issue seems general enough, I'll throw another request in. The main CARGO man page should list the environment variables that can be used with cargo, e.g. RUSTC.

**Comment by carols10cents** [comment]
This was fixed in https://github.com/rust-lang/cargo/pull/2918.
