### ISSUE TITLE
Please bundle an updated version of Cargo to Rust official installer

### ISSUE THREAD

**Issue by dipucian** [rust-lang/cargo#2796]
currently `cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-10)` is installed by the Rust 1.9.0 Windows installer

**Comment by alexcrichton** [comment]
In theory all the installers have appropriate versions of Cargo, so it sounds like something has definitely gone awry! Could you detail how you installed Rust (e.g. where from), what architecture (e.g. 32/64 and msvc/gnu), and perhaps anything else flavorful about your Rust setup?

**Comment by dipucian** [comment]
I'm so so sorry I assumed I have 1.9.0 installed on one machine, cause I've installed it on multiple machines recently, but in fact it was an Rust installed long time ago...
