### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by hh9527** [rust-lang/cargo#2797]
Is this problem related to ca certification verify?
Is there something I can do to disable verify certification?

I am running in WINDOWS 7 behind my company's proxy. with a cntlm as local proxy.

Here is my config:
```
# .cargo/config

[http]
proxy = "http://127.0.0.1:10922/"
```

And this is what I got when execute `cargo build`

```
C:\home\dws\learn\lrust\r1>cargo --version
cargo 0.10.0-nightly (10ddd7d 2016-04-08)

C:\home\dws\learn\lrust\r1>rustc --version
rustc 1.9.0 (e4e8b6668 2016-05-18)

C:\home\dws\learn\lrust\r1>cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [12/-2] SSL connect error
```

**Comment by alexcrichton** [comment]
Disabling SSL verification is the topic of https://github.com/rust-lang/cargo/issues/1180, but maybe this is just a misconfigured proxy or a bug in the proxy handling code somewhere?

**Comment by hh9527** [comment]
My npm (node package manager) works well with same proxy configuration, but it needs to config `strict-ssl = false`, so I think it maybe related to ssl verification.

My company proxy use has a self-signed cert. but it is still use legacy algorithm(SHA-1). And I can not import it to chrome/firefox.

**Comment by alexcrichton** [comment]
Ah ok, in that case I'm gonna close this in favor of #1180 as it sounds like it's a case of correctly rejecting an SSL cert and then it's just otherwise difficult to customize the root certs and such.
