### ISSUE TITLE
`cargo package` never repackages

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#2799]
If you run `cargo package` to completion, change something in your crate, and then run it again, a new package will not be generated. You can change *anything*, add/remove source files, modify the build script, change dependencies, include features, go on vacation for 2 weeks, and `cargo package` will still do nothing. The only thing that triggers a rebuild is manually deleting the appropriate `.crate` file in `target/package` or changing the crate version or name in `Cargo.toml`.

Since `cargo publish` just runs `ops::package` before uploading, it suffers from the same behaviour.

I think the same freshness check for `cargo build` should be used for `cargo package`.

**Comment by nagisa** [comment]
It also prints something along the lines of 

```
$ cargo package
error: 1 dirty files found in the working directory:

Cargo.toml

to publish despite this, pass `--allow-dirty` to `cargo publish`
```

when you change something. 

cc @alexcrichton seems like a serious issue to me

**Comment by alexcrichton** [comment]
Yeah this was done initially with the intent of smoothing the `cargo package` followed by `cargo publish` process, but I agree that without proper dependency tracking it can have disastrous consequences. The fix should be basically to just [remove this block](https://github.com/rust-lang/cargo/blob/aec15e3d0076312a2455afe92a8c72625d3b1663/src/cargo/ops/cargo_package.rs#L52-L60) in favor of just the `open_rw` call in the fall through case.

Gonna tag this E-easy as it should be a simple modification with an easy-enough test to add, and I'll try to get around to it if no one else does before the end of the next cycle.
