### ISSUE TITLE
Please document the default for cargo build's -j option

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/cargo#2805]
`cargo help build` says:
```
    -j N, --jobs N               The number of jobs to run in parallel
```

This should document the default.  Does it default to 1, or to the number of CPUs?

**Comment by alexcrichton** [comment]
For reference, defaults to the number of CPUs, but would be good to mention!

**Comment by munyari** [comment]
@alexcrichton I think you can close this one too now :smile:

**Comment by joshtriplett** [comment]
Thanks!

**Comment by sakgoyal** [comment]
it seems like it works with or without a space (`-j4` and `-j 4`) seem to work the same. 

but the docs seems to imply that a space is always required. that could be specified

**Comment by weihanglo** [comment]
@sakgoyal 

It is not only `-j` having this behavior. That is more like a CLI parsing convention throughout the Rust community, especially when using clap. Even outside Rust ecosystem, the parsing rule is also common. Like `git commit -mmycommitmessage`. I am not sure if it is worth a special doc. 

BTW this is an old closed issue. Please open a new one for your proposal. Thanks.
