### ISSUE TITLE
Documentation about MIR

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/cargo#2806]
Hi all

I wanted to try MIR with my projects. Since they all rely on many crates I was wondering how I can enable it in Cargo.

I think I managed to build a project with a `.cargo/config` file:
```
[build]
rustflags = ["-Zorbit"]
```
but I was wondering what the prefered way is and if it was documented already.

Regards

**Comment by jonas-schievink** [comment]
You can also set the `RUSTFLAGS` environment variable to `-Zorbit` for now. Keep in mind that MIR is mainly just an implementation detail of rustc, so there isn't going to be much official documentation or support. `-Zorbit` is also an inherently unstable flag, it might be removed soon after old trans is removed.

**Comment by dns2utf8** [comment]
Ah, this is good to know. I found the docs now http://doc.crates.io/environment-variables.html

As it is not documented: Can I set the flags with the [profile](http://doc.crates.io/manifest.html#the-profile-sections)?

**Comment by jonas-schievink** [comment]
Not as far as I know

**Comment by alexcrichton** [comment]
Thanks for the report! As @jonas-schievink mentioned this is just an implementation detail of passing `-Z orbit` everywhere for now, and that can be done through `RUSTFLAGS` or `build.rustflags` in `.cargo/config`. Right now unfortunately profiles cannot be used for this, so you can't modify `Cargo.toml` to pass these flags.

We probably don't want to document something ephemeral like this just yet, so I'm going to close this for now.
