### ISSUE TITLE
Requires lib.name to be present

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#2807]
I installed cargo 0.4.0-nightly (4e5fdcd 2015-06-29) (built 2015-06-29) from https://static.rust-lang.org/dist/2015-06-30/rust-nightly-x86_64-unknown-linux-gnu.tar.gz which might not be a complete nightly build.

I'm reporting this anyway, since if it's indicative of a regression, it's important.

my crate fails to build with this message:

```
$ cargo build
failed to parse manifest at `Cargo.toml`

Caused by:
  expected a value of type `string` for the key `lib.name`
```

The lib section is simply this:

```toml
[lib]
bench = false
```

**Comment by alexcrichton** [comment]
Indeed! This change was made in https://github.com/rust-lang/cargo/pull/1762 and was intentional. There can only be one lib, so there's not really much of a need to name it. Thanks for the report though!

**Comment by bluss** [comment]
It's a breaking change though, itertools and ndarray don't build anymore.

**Comment by bluss** [comment]
The version cargo 0.12.0-nightly (50dad37 2016-06-21) is not affected.

**Comment by bluss** [comment]
Hm indeed maybe it's all about an incomplete tarball

**Comment by alexcrichton** [comment]
A breaking change? Could you elaborate?
