### ISSUE TITLE
May support override 'config.json' from crates.io-index ?

### ISSUE THREAD

**Issue by hh9527** [rust-lang/cargo#2817]
In my company's network, there is no direct access to internet.
All request will is handled by company's proxy which will replace cert with its own self-signed ca.
But the cert used by this proxy used SHA-1 algo which will be treated as unbelievable.
So cargo will failed on SSL verification in this situation even after I imported this self-signed CA.

To resolve this, I make a forwarder/proxy to forward request from cargo to internet (disable ssl verification). But the problem is: cargo use url prefixes from crates.io-index/config.json, and this file is fetched by git protocol which can not be intercepted by my forwarder/proxy. I have to manual edit `c:\Users\user\.cargo\registry\index\xxxx\config.json` to replace `api` and `dl` to my forward/proxy after cargo's 'updating registries' each time.

So I think if cargo supported override config.json, for example: `set CARGO_FORCE_OVERRIDE_CONFIG=/path/to/my/config.json`, that will be much simpler.

**Comment by hh9527** [comment]
And further more, I think remove config.json from crates.io-index and serve this file directly via from a restful http(s) server. may be a better solution. 

There is the approach:

1. fetch config.json from 'https://crates.io-index/repo/', got:
```json
{
  "index": 'https://github.com/rust-lang/crates.io-index.git',
  "dl": ''https/crates.io/api/v1/crates",
  "api": "https/crates.io/"
}
```

2. and then git clone from url which descripted in field `index`
3. ...

**Comment by alexcrichton** [comment]
Thanks for the report! There's a few things going on here so I'm gonna try to help tease them apart into pieces that can be tackled.

First up the problem with SSL and company proxies certainly isn't a new one. There's lots of discussion on https://github.com/rust-lang/cargo/issues/1180 as well, but in general you should be able to configure Cargo to use a custom SSL cert which is then communicated to all of the tools that Cargo uses.

Second, fetching sources from a different location than the crates.io registry is basically implementing mirrors, which we very much want to do! I'm working on some support right now to enable this and hopefully get the ball rolling on official mirrors, which likely can be something you set up locally, point Cargo at, and then everything works A-OK.

Lastly, I'm somewhat wary of adding "replacement semantics" somewhat ad-hoc for a situation like this when other solutions are probably be "correct solution" here. We also can't really change the protocol Cargo learns about crates very easily at this time, but other changes should make the motivation for these changes not as relevant hopefully!

**Comment by carols10cents** [comment]
I believe the support for mirrors is handled today with [source replacement](http://doc.crates.io/source-replacement.html) or tools like https://github.com/alexcrichton/cargo-local-registry and https://github.com/alexcrichton/cargo-vendor. Please reopen if I'm mistaken!
