### ISSUE TITLE
Cargo should export path to rustc for build scripts

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#2819]
Cargo should explicitly export `RUSTC` envvar to build scripts indicating path to `rustc` used to compile things, regardless of whether `rustc` comes from `RUSTC` envvar, `PATH` envvar or somewhere else.

**Comment by alexcrichton** [comment]
I've often wanted this from time to time as well, yeah, and should be an easy fix!

**Comment by munyari** [comment]
I'd like to jump on this, but don't know where to start

**Comment by alexcrichton** [comment]
Awesome! Almost all build script logic can be found in [`custom_build.rs`](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_rustc/custom_build.rs) and you can see where [some other environment variables](https://github.com/rust-lang/cargo/blob/6b98d1f8abf5b33c1ca2771d3f5f3bafc3407b93/src/cargo/ops/cargo_rustc/custom_build.rs#L105-L127) are set as well. This would probably involve just adding a line there.

The value of `RUSTC` comes from [`Config::rustc`](https://github.com/rust-lang/cargo/blob/6b98d1f8abf5b33c1ca2771d3f5f3bafc3407b93/src/cargo/util/config.rs#L99) which should be accessible through the local context.

**Comment by munyari** [comment]
I think this is closable now

**Comment by alexcrichton** [comment]
Thanks @munyari!
