### ISSUE TITLE
doc fails on 'hyper' crate

### ISSUE THREAD

**Issue by alexreg** [rust-lang/cargo#2820]
Running `cargo doc` on a crate that depends on `hyper` gives this error.

```
 Documenting hyper v0.9.9
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not document `hyper`.
```

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this may actually be a bug in rustdoc (similar to this - https://github.com/rust-lang/rust/issues/34554) which is apparently [fixed upstream](https://github.com/rust-lang/rust/issues/34554#issuecomment-229478281) and just waiting on nightlies! As a result I'm gonna close this for now, but once a nightly is built if it's still not working just let me know.

**Comment by alexreg** [comment]
Sure, will let you know tomorrow if it’s still a problem.

**Comment by carols10cents** [comment]
> I'm gonna close this for now
