### ISSUE TITLE
no such subcommand doesn't print the command, which hinders troubleshooting

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#2825]
When `cargo` is run with a command that is not recognized, it prints *suggestion* of a valid command, but doesn't print the actual command that was rejected.

This is fine when cargo is run from an interactive shell. However, when cargo is run as part of a script or — in my case — [Sublime Linter plugin](https://github.com/oschwald/SublimeLinter-contrib-rustc/issues/25), this becomes a problem, because the command line is not visible. When only the printed output is available in the log, it's impossible to see what command was really meant.

> SublimeLinter: rust output:
> error: no such subcommand
>
>	Did you mean `clean`?

**Comment by alexcrichton** [comment]
Oh dear, sounds bad! Shouldn't be too hard to fix though!

**Comment by KaivoAnastetiks** [comment]
@pornel @alexcrichton I'll try to fix this one. What wording do you think it should have? 
1. `error: no such subcommand: 'subcommand'`
2. `error: no 'subcommand' subcommand`
3. `error: no such subcommand (subcommand)`

**Comment by alexcrichton** [comment]
@KaivoAnastetiks sounds good to me, it's all yours! I like option(1) there except I'd recommend tick marks instead of single quotes (style used throughout cargo)

**Comment by alexcrichton** [comment]
er, tick marks as in \`

**Comment by KaivoAnastetiks** [comment]
@alexcrichton There you go. I meant back ticks as well but just couldn't figure out how to escape backticks in markdown.
