### ISSUE TITLE
How to get a version of `rustc` which is used by `cargo`?

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2833]
Hi! 

I'd like to show which version of `rustc` is used by `cargo` in IntelliJ GUI. Currently we just invoke `/path_configured_by_user/cargo --version` and `/path_configured_by_user/rustc --version`, but this may be wrong. For example, [the `rustc` may not be in `PATH`](not in path). Also there is `RUSTC` environment variable...

What do you think about extending `cargo --version` such that it also prints the version of the compiler, like this:

```
$ cargo --version --verbose
cargo 0.10.0-nightly (10ddd7d 2016-04-08)

rustc 1.9.0 (e4e8b6668 2016-05-18)
binary: rustc
commit-hash: e4e8b666850a763fdf1c3c2c142856ab51e32779
commit-date: 2016-05-18
host: x86_64-unknown-linux-gnu
release: 1.9.0
```

Looks like rustc version is queried anyway:

```
$ rm ~/.cargo/bin/rustc
$ ~/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo --version          
error: Could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
```

And maybe `cargo --version` should work even if there is no `rustc` available? 

[not in path]: https://gitter.im/intellij-rust/intellij-rust?at=577e4720b79455146f586cfc

**Comment by matklad** [comment]
Ah, I must say that I can't use `cargo rustc -- --version`, because when you configure `cargo` you don't yet have a `Cargo.toml`.

**Comment by alexcrichton** [comment]
Heh yeah today we have `rustc --version` on hand (it's parsed when `Config` is created) but I'd prefer if we didn't do that. That's just an implementation detail though, so we could change at any time!

I'd actually be fine I think if we printed out `rustc --version` as well when we ran `cargo --version`, so long as we make it clear which is which.

@brson what do you think?

**Comment by brson** [comment]
I agree with the motivation, and can't think of anything smarter to do. Hopefully though we we don't need to do the same for rustdoc.

I think `cargo --version` should work when rustc doesn't exist. That's bitten me before.

**Comment by matklad** [comment]
I've though about it more and came to the conclusion that we probably don't want this feature. 

As for the original motivation about IntelliJ Rust, we now always explicitly pass ( https://github.com/intellij-rust/intellij-rust/pull/517 ) `RUSTC` environmental variable to Cargo and it works fine so far. 

Knowing which `rustc` is used by Cargo can be useful for the end user to troubleshot problems, but I don't think that `--version` is the correct place to do this. Together with the compiler version we might want to output the path to the compiler, or the path to the configuration files or some other info. Something like `cargo --show-config` seems a better approach hear. 

But Cargo almost always just works, so there is no need to provide this functionality.

**Comment by sesam** [comment]
Sorry for commenting on an old issue.

I see this as an either or; either

- cargo just works most of the time, so there's no harm in cargo also upgrading rustc to latest stable by itself; and whenever a cargo command fails it could check for newer releases and suggest upgrading.

or 

- versions are important, and Cargo.toml should allow package creators to say which versions are known good and known bad, so users don't have to rediscover this by guessing maybe rustup to latest, or to one before latest, or ...

Case: Several beta testers for https://github.com/mimblewimble/grin/ have `vargo build` fail with some hard to understand error, and all they would need is to get rustc >=1.21

Thanks for your time. Workaround ideas very welcome

**Comment by matklad** [comment]
@sesam I think the up-to-date discussion is here https://github.com/rust-lang/rfcs/pull/2182

**Comment by sesam** [comment]
Thanks, and sorry, it seems I pasted my comment on the wrong issue.

I noticed that RFCs get closed. Your suggested 2182 (closed), 1953 (closed), 1707 (closed).

For your own original issue, I guess you could solve that by heuristics, reimplementing the same rustc discovery and selection code that cargo already uses... which probably saves the cargo team a few code lines, and adds more code lines elsewhere.

**Comment by henhito** [comment]
thanks i had install using the following guide, i think i just need to set the env variable to source from the updated rust version.

https://itsfoss.com/install-rust-cargo-ubuntu-linux/

**Comment by Timmmm** [comment]
> Knowing which rustc is used by Cargo can be useful for the end user to troubleshot problems

Yes definitely, especially when dealing with nightly. E.g. I'm trying to compile `rustfmt` and it needs a specific nightly version and I'm not sure it is being used. Did anything like this ever happen?
