### ISSUE TITLE
`Cargo.lock` contents depend on whether `cargo build` is invoked in workspace or member

### ISSUE THREAD

**Issue by euclio** [rust-lang/cargo#2837]
Expected behavior: the file is not changed between builds.

Steps to reproduce:

1. Create a root crate with a single dependency.
2. Create a member crate inside the root crate with a single dependency.
3. Add a `[workspace.members]` key that points to the member crate.
4. `cargo build` in the root.
5. `cargo build` in the member.

Notice that the `Cargo.lock` file has changed. Depending on which crate you build in, the root `Cargo.lock` will have different contents.

**Comment by alexcrichton** [comment]
Oh dear, definitely a bug!
