### ISSUE TITLE
Help developers handle licenses somehow

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#2838]
I wrote some Rust code as part of (re)learning Rust. I imagine I'd publish it at some point in the future, when it reaches an interesting enough point. Part of publishing software is deciding what license to use. There are multiple criteria in the process of choosing a license. One of them is your own values regarding open source vs. free software, copyleft vs. not, etc. Another is compatibility with the licenses of the libraries you rely on, and with cargo making pulling dependencies very easy, and with Rust making static linking the default, this pushes the whole licensing issue to another level.

My small toy project has exactly 4 dependencies in Cargo.toml. Cargo.lock lists 12 more (so 17 in total (the project itself, the 4 direct dependencies, and their dependencies). I guess it's easy to end up with close to a hundred dependencies for middle-sized projects. And figuring out the license of all those pieces is a time consuming process. Even worse if you factor the complexity of license compatibility.

I think at the minimum, cargo should help with determining the license of all the pieces involved, even if it doesn't attempt to resolve license compatibility (which would be a nice touch, but a complex one ; determining the overall license of distributed binaries would be fun).

**Comment by onur** [comment]
This idea lead me to write [cargo-license](https://github.com/onur/cargo-license) subcommand to display license of all dependencies. It is categorizing dependencies by license.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rfcs/issues/1396, another feature request along these lines

**Comment by alexcrichton** [comment]
@onur also, nice project!

**Comment by Nemo157** [comment]
I wrote a similar command as well a while ago (https://github.com/Nemo157/cargo-lichking) it has some (very) limited support for checking compatibility.

**Comment by ishitatsuyuki** [comment]
Another thing is to generate bundled third-party license file automatically, since they are basically mass copying.

**Comment by carols10cents** [comment]
This sounds like it's taken care of by external commands, so closing!
