### ISSUE TITLE
macOS Sierra beta2, cargo can't work properly.

### ISSUE THREAD

**Issue by LiVincent-Zhang** [rust-lang/cargo#2843]
After I update my system to macOS Sierra beta2, cargo is broken. The cpu usage is always 100% and show nothing in the terminal even the "cargo --version" can not work.

**Comment by alexcrichton** [comment]
I think this may be a dupe of https://github.com/rust-lang/rust/issues/34674 perhaps?

**Comment by LiVincent-Zhang** [comment]
@alexcrichton , the pr is merged as I know. When this code will be available in the nightly version? thanks.

**Comment by alexcrichton** [comment]
I believe should be tonight or tomorrow. Note though that Cargo is compiled with a pinned version of the compiler, so it won't pick up the fix immediately. Could you try compiling Cargo with tomorrows nightly and then see if that Cargo works for you?

**Comment by LiVincent-Zhang** [comment]
@alexcrichton ok, I will try.

**Comment by LiVincent-Zhang** [comment]
@alexcrichton, the cargo works fine in the latest nightly version, thanks.

**Comment by alexcrichton** [comment]
Awesome, thanks! I'll update the nightly we use to build Cargo to ensure this fix gets out ASAP
