### ISSUE TITLE
Simple commands like `--version` or `--help` should not fail if there is no `rustc`.

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2848]
I've split this off the #2833. 

So the idea is not to invoke `rustc -vV` until we really need it. 

I see two ways of implementing this: 

1. Change `Config` structure such that `rustc_info` is calculated lazily. That is, change [`rustc_info()`] signature to `pub fn rustc_info(&self) -> CargoResult<Rustc>`.

2. Push `Rustc` info from `Config` down to `CompileOptions` and then to `BuildConfig`. 

Option 1 can be implemented with a relatively small code change, but it is somewhat complex, because retrieving rustc info can fail, and if this retrieval is lazy then you don't really know when this error surfaces. 

Option 2 naturally requires some minor refactoring, but seems to be a proper way to address this issue. 

Currently, `Rustc` info is used for three things:

* Determining the host and default target triples. 
* Full version is used to calculate fingerprints. 
* `--cap_lints` is feature detected to allow interop with older compilers which lack this flag. 

[`rustc_info()`]: https://github.com/rust-lang/cargo/blob/350232ba8ff818be3705848eb3bc119ac9afe607/src/cargo/util/config.rs#L103

**Comment by alexcrichton** [comment]
I'd personally prefer option (1), but rustc info isn't the only thing we should scrape lazily. Right now `Config::new` can fail for a number of reasons which should probably all be guarded against in the case of `cargo version`.

For example I think all these tests should pass:

```rust
#[test]                                                    
fn version_works_without_rustc() {                         
    let p = project("foo");                                
    assert_that(p.cargo_process("version").env("PATH", ""),
                execs().with_status(0));                   
}                                                          
                                                           
#[test]                                                    
fn version_works_with_bad_config() {                       
    let p = project("foo")                                 
        .file(".cargo/config", "this is not toml");        
    assert_that(p.cargo_process("version"),                
                execs().with_status(0));                   
}                                                          
                                                           
#[test]                                                    
fn version_works_with_bad_target_dir() {                   
    let p = project("foo")                                 
        .file(".cargo/config", r#"                         
            [build]                                        
            target-dir = 4                                 
        "#);                                               
    assert_that(p.cargo_process("version"),                
                execs().with_status(0));                   
}                                                          
```

**Comment by matklad** [comment]
Turns out it's hard to implement the second test at the moment, because we need to parse config early because of aliases. See #2901.

**Comment by alexcrichton** [comment]
Ah I'd be fine just ignoring errors like that if we're on a fast track like `--version`
