### ISSUE TITLE
`cargo update -p winapi` fails after removing winapi replacement

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2856]
In rustup I was trying to remove a winapi replacement, and couldn't figure out how to do it.

Starting from commit 011f79ae16dc6317d9fdffdcd6bb1309b5d79069 I removed all the 'winapi' replacement lines from 4 toml files, then typed `cargo update -p winapi`. I see:

```
$ cargo update -p winapi
error: There are multiple `winapi` packages in your project, and the specification `winapi` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  https://github.com/sfackler/winapi-rs#winapi:0.2.7
  https://github.com/rust-lang/crates.io-index#winapi:0.2.7
```

I don't know where to go from there. I can run `cargo update` successfully, but I'd strongly prefer not to need to do a full dep upgrade.

**Comment by alexcrichton** [comment]
I believe the command to execute here was:

```
cargo update -p 'https://github.com/rust-lang/crates.io-index#winapi:0.2.7'
```

which is to say the crates.io dep needed to get updated and that would also clear out the forked dep. Perhaps the error message could be better though?

**Comment by alexcrichton** [comment]
Also deleting the `[replace]` sections for winapi I believe would work?

**Comment by brson** [comment]
I don't have any intuition for why `cargo update -p 'https://github.com/rust-lang/crates.io-index#winapi:0.2.7'` would be the right command. I expected just `winapi` to work, and I might even expect to specify the *other* crate since that's the one I touched. The correct one is the last one I'd guess :)

> Also deleting the [replace] sections for winapi I believe would work?

I don't understand this comment. I thought that was what I did. Started with

```
[replace]
"winapi:0.2.7" = { git = "https://github.com/sfackler/winapi-rs" }
```

Ended with neither of those lines.

**Comment by alexcrichton** [comment]
Oh oops I meant to talk about this in person today and then forgot to look at my inbox...

Anyway, the suggestion of the `-p` flag is intended to be purpose of this text in the error message:

```
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  https://github.com/sfackler/winapi-rs#winapi:0.2.7
  https://github.com/rust-lang/crates.io-index#winapi:0.2.7
```

> I don't understand this comment. I thought that was what I did. Started with

Oh hm, I may be misinterpreting then. Starting from the commit you mentioned, if I deleted all the `[replace]` sections and ran `cargo build`, the lock file updated automatically to pull in a different version of winapi.

**Comment by cyplo** [comment]
Heyo ! Do we need more work to close this one ?

**Comment by alexcrichton** [comment]
Indeed looks to be no, so let's close
