### ISSUE TITLE
Support --jobs on publish argument for build parallelism

### ISSUE THREAD

**Issue by adamcrume** [rust-lang/cargo#2860]
`cargo build` supports a `--jobs` argument for controlling the build parallelism, and this is very useful for controlling the parallelism of non-Rust builds for *-sys crates.  `cargo publish` should support the same option.

**Comment by alexcrichton** [comment]
Ah good point! This should be relatively easy to do, so I'm tagging with E-easy. This largely just needs to modify `src/bin/publish.rs` and then plumb the `-j` option all the way down to where the crate is actually verified. Feel free to ask questions if someone needs help implementing this!

**Comment by mattscamp** [comment]
I will take it. Just to confirm @alexcrichton, this also involves also adding -j in 'package' since publish runs through it?

**Comment by alexcrichton** [comment]
Indeed! (although it looks like you've already done it)

**Comment by brson** [comment]
Fixed. Thanks @mattscamp !
