### ISSUE TITLE
Show a warning if the new crate would fail to be pushed to crates.io

### ISSUE THREAD

**Issue by adelarsq** [rust-lang/cargo#2864]
When trying to use `cargo new` show a warning if the crate would fail to be pushed to [crates.io](https://crates.io/).

This issue was based on [this](https://www.reddit.com/r/rust/comments/4rlom7/what_characters_are_allowed_in_a_crate_name/) reddit topic.

**Comment by mattscamp** [comment]
Skimmed through the comments and the code associated. It seems like the only difference between them is crates.io required ASCII characters and some reserved names we should be checking for. Is that accurate?

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this may actually be mostly a subset of https://github.com/rust-lang/cargo/issues/883, so I'm gonna close this in favor of that.

Yeah I think it'd be fine to change `cargo new` though to verify that the project name doesn't have ASCII by default, as that's mostly what crates.io does. I originally wanted to leave most of this validation to crates.io to avoid duplicating, but it should be small enough that it's harmless to duplicate.
