### ISSUE TITLE
doc.crates.io - docs menu onclicks only work once

### ISSUE THREAD

**Issue by nathansizemore** [rust-lang/cargo#2865]
The docs drop down menu does not navigate anywhere once on any page served from doc.crates.io has been served from that menu.

To reproduce:

1. Click [here](http://doc.crates.io/guide.html)
2. Navigate to any page through "docs" menu.
3. Attempt step 2.

```
$ cat /etc/debian_version
8.5

$ lsb_release -a
Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 8.5 (Hydrogen)
Release:	8.5
Codename:	bunsen-hydrogen

$ google-chrome --version
Google Chrome 51.0.2704.106
```

**Comment by alexcrichton** [comment]
I wonder if this may be a chrome-specific thing? It's working for me in firefox at least

**Comment by alexcrichton** [comment]
Should be an easy bug though for anyone familiar with JS!

**Comment by tommymcdonald** [comment]
I'd love to help fix this, but I'm unable to reproduce on OS X El Capitan, Chrome version 51.0.2704.106 (64-bit).

**Comment by alexcrichton** [comment]
Interesting! You're even using the exact same version of browsers... @nathansizemore perhaps there was a stale cache on your end? Or maybe it only happens for one or two of the links?

**Comment by nathansizemore** [comment]
Alright, so I checked on the same with macOS too, and it happens there as well. But, I think I have found how to actually reproduce it: If you trigger menu to drop, wait one sec, it will go to wherever you click. It seems to only refuse navigation when clicked fast. If I remove the following snippet from the js, I can click as fast as I want and it always goes:

``` javascript
if ($(this).hasClass('active')) {
    $(document).on('mousedown.useroptions', function() {
        setTimeout(function() {
            $('button.dropdown, a.dropdown').removeClass('active');
            $('button.dropdown + ul').removeClass('open');
        }, 150);
        $(document).off('mousedown.useroptions');
    });
}
```

Maybe the timing of the attributes being changed or whatever with that timeout affects things?

**Comment by rjgoldsborough** [comment]
I was able to reproduce this... kind of.

What do you mean fast? Are you trying to click as fast as possible?

I was able to add some console logs and see a mousedown event fire but the link not work.
I think the mousedown is firing but it's actually a drag and so the click on the link isn't being caught.
I could reproduce it every time by opening the menu and trying to do a moving or drag click instead of a straight click.

I added a PR that tweaks this a bit. I can still make it not follow the link but just doing a drag click but I'm not sure you can fix that, but it does make the menu not disappear if you happen to not click and only drag.

**Comment by nathansizemore** [comment]
What I meant by fast was the measure of time from when you click to open the nav, to the time you click on a section of the nav. If you do that quickly, you can reproduce it. It might have to do with that code snippet above, it may be using the prevent defaults action internally? I'm not super up to date on my jQuery. If that is removed, the problem does go away, and since it is a full page reload anyway, I'm not sure why that section is even there.
