### ISSUE TITLE
Conflicting fields are ignored in deps specified by location

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang/cargo#2869]
1. Within git deps, it is possible to specify all three of branch, tag, and revision:

   ```rust
    let reference = details.branch.clone().map(GitReference::Branch)
        .or_else(|| details.tag.clone().map(GitReference::Tag))
        .or_else(|| details.rev.clone().map(GitReference::Rev))
        .unwrap_or_else(|| GitReference::Branch("master".to_string()));
   ```

2. It is possible to specify git and path, in which case git is used

  ```rust
  let new_source_id = match details.git {
      Some(ref git) => {
          ...
      }
      None => {
          match details.path.as_ref() {
              Some(path) => {
                  ...
              }
              None => None,
          }
      }
  }
  ```

We should add a warning or make this an error. I learn towards error because any package that uses this is already violating the author's intention.

**Comment by alexcrichton** [comment]
I'm going to tag this as E-easy as it should be relatively easy to detect this in the manifest parser, and it should also be pretty easy to add a warning.

We'll want to add a warning for at least a few cycles, and maybe after a few months we can turn it into a hard error once we're certain it's not used. For now though we can just lint against this happening.
