### ISSUE TITLE
Desugar dev-dependencies

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang/cargo#2872]
Does it make sense that `[target.'cfg(test)'.dependencies]` could mean the same thing as `[dev-dependencies]`? This opens the door to test-only build deps.

**Comment by alexcrichton** [comment]
Right now the `#[cfg]` business in Cargo is basically only meant for `rustc --print cfg` to match, which while this may work with `rustc --print cfg --test` I'd rather not encode this and instead just use `dev-dependencies` which is clearer to understand.

**Comment by alexcrichton** [comment]
Today there's not even somewhere to put those so they wouldn't mean anything anyway.
