### ISSUE TITLE
Add a way to add arbitrary environment variables to invocation of rustc from build scripts

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#2875]
probably by printing something like `cargo:rustc-env...`

Crates may use environment through macros like `env!`, therefore it is very useful to be able to set environment variables from build scripts. A potential use case would be to embed a git short-hash/version/build environment into the binary on build.

**Comment by Xion** [comment]
I just encountered this issue in the precise use case mentioned, i.e. embedding git sha into the binary for logging purposes.

I think the possible workaround is to produce a file in `$OUT_DIR` and then do `include!(concat!(env!("OUT_DIR"), "sha"))` in the crate code, but passing it as an env. var would obviously be much nicer.

**Comment by kennytm** [comment]
This should be closed? #3929 has been merged.

**Comment by nagisa** [comment]
the namespacing does not work well together with the requirement of
arbitrary here. What if I want to add, say, a search path for pkg-config?
Those surely wont take a variable prefixed with apparent garbage.

**Comment by nagisa** [comment]
Quick reading of the code suggests there is no namesoacing going on, so
never mind me.

**Comment by alexcrichton** [comment]
Yes @kennytm, this can be closed.
