### ISSUE TITLE
'cargo build --color always' should enable colors for rustc too

### ISSUE THREAD

**Issue by bennofs** [rust-lang/cargo#2877]
Currently, if you run `cargo --color always build`, it'll only enable colors for the output of cargo itself, but not for any errors produced by rustc. To get colors from both `cargo build` and `rustc`, you have to use the following complex command:

    $ cargo rustc --color always -- --color always 2>&1

I think cargo should forward the `--color` argument to `rustc`.

**Comment by alexcrichton** [comment]
Indeed! That should be [done here though](https://github.com/rust-lang/cargo/blob/1c329c46a0777e2b9ff401f14a772f12acc25e76/src/cargo/ops/cargo_rustc/mod.rs#L454-L457), maybe an older version of Cargo is being used?

**Comment by bennofs** [comment]
Oh yes, I think you're right. I'm using 0.10, and that change is only in 0.12 i think

**Comment by bennofs** [comment]
Indeed, it works with master.

**Comment by alexcrichton** [comment]
Yay!
