### ISSUE TITLE
Provide a way to run cargo subcommands on all crates in the workspace

### ISSUE THREAD

**Issue by euclio** [rust-lang/cargo#2878]
This is mentioned as a "future extension" in [RFC 1525](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md#future-extensions).

**Comment by alexcrichton** [comment]
Thanks for the issue @euclio! This was indeed intended to have an issue. And to expand a bit the thought was to add `--all` flags to many subcommands so executions like:

```
cargo test --all
```

would test all the crates in a workspace, or

```
cargo publish --all
```

would publish all crates in a workspace that haven't already been published.

**Comment by jdc2172** [comment]
just wondering if anyone is still working on this

**Comment by alexcrichton** [comment]
@jdc2172 I don't believe the currently is, but if you'd like to take it feel free!

**Comment by retep998** [comment]
`cargo doc --all` would be exceptionally useful.

**Comment by euclio** [comment]
I'd be interested in tackling this, but I think we need to hammer out which commands should get this flag.

Also, what sort of implementation approach should be taken?

**Comment by steveklabnik** [comment]
`cargo build` and `cargo test` are the biggies for me.

**Comment by jdc2172** [comment]
Cargo test definitely needs this.

Not sure cargo build is as high priority given that it already builds path
deps in the crate

**Comment by steveklabnik** [comment]
Oh yeah. That's what I get for hasty commenting! On my project that uses workspaces, those are the only two sub commands I use, so I didn't think it through 😅😞

**Comment by alexcrichton** [comment]
@euclio to me yeah `test` and `doc` are the biggies to cover here. I think `publish` would also be great but that has other tricky semantics we'd want to cover later.

**Comment by euclio** [comment]
@alexcrichton Trying to get my feet wet with `test`. What's the best plan of attack here? Modifying `ops::compile` to take a flag to compile all members of the workspace instead of the current?

**Comment by alexcrichton** [comment]
@euclio yeah there's a few points where the `-p` flag is passed down, but that could just be an enum of *either* a `-p` flag or a `--all` flag. When that needs to be resolved we can then just iterate over all packages in a workspace.

**Comment by euclio** [comment]
@alexcrichton How should I handle the ambiguity when the member has the same name as a dependency?

**Comment by alexcrichton** [comment]
Oh that's ok, `-p` is a "package id specification" which will uniquely identify a crate in the dependency graph

**Comment by cbiffle** [comment]
Is there a reason not to make `--all` the default in "virtual workspaces?"

It seems like a more reasonable default than the current behavior, which is:

```text
$ cargo build
error: manifest path `/path/embrs/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

**Comment by alexcrichton** [comment]
@cbiffle perhaps yeah, I figured it'd be good to ask for an explicit `--all` but there's not really any other interpretation of a `cargo build` against a virtual manifest, so just defaulting seems reasonable.

**Comment by Arnavion** [comment]
I've had a PS function `cargoall` in my local profile to do `cargoall { cargo test }`. Perhaps an approach to add a `cargo all` subcommand (eg `cargo all test` or `cargo all cargo test`) will be preferable to adding `--all` to every existing subcommand?

```powershell
function cargoall ([ScriptBlock] $ScriptBlock) {
	(cargo metadata --no-deps | ConvertFrom-Json).packages |
		%{ ([System.IO.FileInfo] $_.manifest_path).Directory } |
		%{
			$_.FullName
			Push-Location $_
			&$ScriptBlock
			Pop-Location
		}
}
```

(This runs `cargo metadata --no-deps`, parses the JSON output, then executes the parameter as a command inside the directory of each package.)

**Comment by rocallahan** [comment]
`cargo build --all` would be very helpful to us. We have a collection of crates, several of which are `--bin`, and it would be nice to have a single cargo command to build them all. That would let us get a parallel build.

**Comment by sdroege** [comment]
cargo build --all (https://github.com/rust-lang/cargo/pull/3511) and cargo doc --all (https://github.com/rust-lang/cargo/pull/3515) also exist now

**Comment by Dushistov** [comment]
@sdroege 
It would be nice to exclude some crates from `build --all`, for example
I have bunch of crates and one of them specific for android, it depends on android NDK,
and it is possible to build it only with `cargo build --target=arm-linux-androideabi`,
so `cargo build --all` failed, it would be nice to have something like `cargo build --all --exclude android`

**Comment by gifnksm** [comment]
It would be very nice to have `cargo bench --all`.

**Comment by sdroege** [comment]
> It would be very nice to have cargo bench --all.

Indeed, I'll take a look at that tomorrow if nobody else is faster. What other commands would be useful to have with an --all variant?

**Comment by alexcrichton** [comment]
Thanks @sdroege!

**Comment by kvark** [comment]
@Dushistov 
> It would be nice to exclude some crates from build --all, for example
I have bunch of crates and one of them specific for android, it depends on android NDK,

This is very applicable to gfx-rs as well, we have dependencies on Windows, OSX, and other stuff, that can't be ON at the same time.

**Comment by torkleyy** [comment]
I created a PR for the `--exclude` flag ( #4031 ), would somebody like to review?

**Comment by azriel91** [comment]
Hi, does this issue cover supporting `--all` to any arbitrary custom subcommand to run that subcommand across all workspace crates? For example, `cargo fmt` works on the current crate, but I'd like to have a way to run it against all workspace members.

The way the current code looks, each subcommand determines whether or not it supports running against the workspace via the `--all` flag. I'm wondering if it makes sense to have a command that switches the order like so:

```bash
cargo workspace <subcommand> [opts] [args]
# this would run the following against each crate in the workspace:
cargo subcommand [opts] [args]
```

That way any custom subcommands will be able to be run against all crates in the workspace without needing to implement it.

**Comment by alexcrichton** [comment]
@azriel91 I'm not currently thinking that we'd have such a subcommand or interpretation of this, it'd be up to subcommands to interpret and act on `--all` if they'd like.

**Comment by gnzlbg** [comment]
`cargo fmt --all` and `cargo clippy --all` would be really useful.

**Comment by carols10cents** [comment]
A bunch of commands have `--all` flags now, and the remaining ones should get their own issue, [like publish does](https://github.com/rust-lang/cargo/issues/1169). Any 3rd party subcommands would need to implement this on their own, so issues should be filed on those commands' repos.

So I'm closing this!

**Comment by gnzlbg** [comment]
@carols10cents 

> and the remaining ones should get their own issue

Did you fill these issues?

**Comment by azriel91** [comment]
@gnzlbg that's up to the subcommands (and we probably don't know *all* of them), at least these subcommands support it:

* build
* test
* clippy
* rustfmt

Another cargo command which I found useful is [`cargo make`](https://crates.io/crates/cargo-make), which supports running arbitrary commands in each workspace member. The default configuration is pretty good, and you can add your own if you wish.

**Comment by gnzlbg** [comment]
That's good news, 9 days ago clippy and fmt still did not support `-all`. I think the only other one missing from the ones mentioned here is `cargo bench --all`.

**Comment by carols10cents** [comment]
@gnzlbg 

```
$ cargo --version
cargo 0.21.0 (5b4b8b2ae 2017-08-12)
$ cargo bench --help
Execute all benchmarks of a local package

Usage:
    cargo bench [options] [--] [<args>...]

...
    --all                        Benchmark all packages in the workspace
...
```

It looks like `cargo bench` supports `--all` to me.

**Comment by azriel91** [comment]
This ugly command tells you what subcommands you have installed have the `--all` option:

```bash
cargo --list | grep -vF 'Installed' | xargs -I {} bash -c 'echo -n {}: ; cargo {} --help 2>&1 | grep -m 1 "^.\+--all[^-a-z]" || echo' | grep '.\+--all'
```

Sample output:

```
bench:    --all                        Benchmark all packages in the workspace
build:    --all                        Build all packages in the workspace
check:    --all                        Check all packages in the workspace
doc:    --all                        Document all packages in the workspace
fmt:        --all           format all packages (only usable in workspaces)
test:    --all                        Test all packages in the workspace
```
