### ISSUE TITLE
Add watcher command

### ISSUE THREAD

**Issue by mdinger** [rust-lang/cargo#2884]
f# has a pretty nice and convenient build system through the [scaffold](https://github.com/fsprojects/ProjectScaffold/) project. It handles building, dependency management, and document generation which works pretty well once it's setup.

Of note is the [KeepRunning](https://github.com/fsprojects/ProjectScaffold/blob/master/build.template#L267-L277) build command which is pretty cool. With that command, you can call `./build KeepRunning` and it will build the docs and then monitor the docs folder (mostly markdown). If anything changes in the docs, the build system will rebuild the docs immediately. All that is needed is the user working on the docs refresh their browser.

I think some cargo command which did this would be pretty cool. I'm not sure how it should handle building the regular library though maybe it would only handle docs changes.

**Comment by alexcrichton** [comment]
This actually [already exists](https://github.com/passcod/cargo-watch)! Once you do that sounds like `cargo watch doc` is all you need to do ):

**Comment by mdinger** [comment]
Thanks for pointing that out. I just wanted to note it before I forgot but looks like people are already way ahead of me.

The fact that stuff like this already exists on this project one year after 1.0 is very cool!
