### ISSUE TITLE
Cannot test dylib

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/cargo#2890]
Cargo will create DSOs and compile src/bin/*rs files just fine (which also run fine).

However, Cargo is unable to compile/run test programs for crates that have [lib] crate-type = ["dylib"].

I can not add rlib - if I do then any dependent crates will only link statically - and they MUST link this crate dynamically.

I tried to craft my own rustc, but it seems the thing blocking me is '--test'.

Is there any way at all to write tests against crates with crate-type = ["dylib"] ?

Thanks.

**Comment by alexcrichton** [comment]
I think this may actually be a bug in the compiler right now. To be clear, you're talking about a `tests/*.rs` test and a crate which is a dylib?

**Comment by MarkSwanson** [comment]
Yes, exactly.

**Comment by MarkSwanson** [comment]
Would it help if I logged a bug with rustc and referenced this issue?

**Comment by alexcrichton** [comment]
Oh sure yeah, I opened up an issue here -- https://github.com/rust-lang/rust/issues/34909

**Comment by carols10cents** [comment]
Sounds like this issue has been replaced by the rust-lang/rust issue https://github.com/rust-lang/rust/issues/34909 so I'm closing this one. Please reopen if there's a cargo component that needs to be changed once that issue is fixed that I'm missing. Thanks!
