### ISSUE TITLE
Re-open discussion around mentioning the target

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/cargo#2894]
I'd like to reopen the discussion on https://github.com/rust-lang/cargo/pull/1374. We're still seeing new-to-Rust users tripping over this.  Specifically, things like this:

https://www.reddit.com/r/rust/comments/4tikmf/why_is_my_forth_virtual_machine_written_in_rust/

Should be almost impossible to happen for new users.  Users should be able to easily see the target and get clued in that the unintended target is being built.

@alexcrichton mentions a simple fix by mentioning the target in the build message, and I think this is perfectly fine.  We don't need an over-engineered, show-all-the-things approach, but instead just simply write the target name.  If we support custom target, we can put that there too.

The key piece, though, is cluing in users at a glance to what's going on.

**Comment by alexcrichton** [comment]
I believe @jonathandturner is working on a rebase of that PR and will open a new PR shortly

**Comment by jonathandturner** [comment]
PR: https://github.com/rust-lang/cargo/pull/2896

**Comment by jonathandturner** [comment]
Closed with #2909
