### ISSUE TITLE
Cargo not passing arguments to executable

### ISSUE THREAD

**Issue by Osspial** [rust-lang/cargo#2898]
Currently, attempting to use `--` to pass arguments to the executable in cargo does not actually pass arguments to the executable, and in fact causes cargo to throw an error.

Let's take the following program, in the cargo project `carg`, using the `clap` library version 2.9 for argument parsing:

```rust
extern crate clap;
use clap::{Arg, App};

fn main() {
    let matches = 
    	App::new("Cargo Argument-Passing Test")
    		.arg(Arg::with_name("print")
    				.short("p")
    				.long("print")
    				.takes_value(true))
    		.get_matches();

    match matches.value_of("print") {
    	Some(s) => println!("{}", s),
    	None    => println!("Error: No print value provided")
    }
}
```

Using this program is very simple - you simply tell it what to print with the argument `-p` or `--print` and it will print that string, unless the user does not provide a print argument, in which case it will print "Error: No print value provided". Navigating to the `/target/debug/` directory, we can test this ourselves:

```
> ./carg.exe -p rust
rust

> ./carg.exe --print github
github

> ./carg.exe
Error: No print value provided

> ./carg.exe --foo
error: Found argument '--foo' which wasn't expected, or isn't valid in this context

USAGE:
    carg.exe [OPTIONS]

> 
```

However, if we navigate back to the project's root folder and attempt sending the arguments through cargo, we get a cargo error. We would expect that cargo would pass the arguments to the executable, like so:

```
> cargo run -- --print foo
     Running 'target\debug\carg.exe'
foo

>
```

Instead, this happens (note that just running without arguments prints "Error: No print value provided" as expected): 

```
> cargo run -- --print foo
error: Unknown flag: '--print'

Usage:
    cargo run [options] [--] [<args>...]

> cargo run -- -p bar
error: Unknown flag: '-p'

Usage:
    cargo run [options] [--] [<args>...]

> cargo run
     Running 'target\debug\carg.exe'
Error: No print value provided

>
```

# Meta
This issue occurs on both stable and nightly.

Stable versions: 
```
> cargo --version
cargo 0.11.0-nightly (259324c 2016-05-20)

> rustc --version --verbose
rustc 1.10.0 (cfcb716cf 2016-07-03)
binary: rustc
commit-hash: cfcb716cf0961a7e3a4eceac828d94805cf8140b
commit-date: 2016-07-03
host: x86_64-pc-windows-gnu
release: 1.10.0
```

Nightly versions:
```
> cargo --version
cargo 0.13.0-nightly (15c1cd2 2016-07-17)

> rustc --version --verbose
rustc 1.12.0-nightly (34f35ed29 2016-07-17)
binary: rustc
commit-hash: 34f35ed29c8acdbe1e3c172786fc41d6f4fb6090
commit-date: 2016-07-17
host: x86_64-pc-windows-gnu
release: 1.12.0-nightly
```

**Comment by alexcrichton** [comment]
Hm interesting! I wonder if your shell is perhaps interpreting flags? This works for me:

```
$ cat src/main.rs 
fn main() {
    println!("{:?}", std::env::args().collect::<Vec<_>>());
}
$ cargo run -- --print foo
     Running `target/debug/foo --print foo`
["target/debug/foo", "--print", "foo"]
$ cargo run
     Running `target/debug/foo`
["target/debug/foo"]
$ cargo -V
cargo 0.11.0-nightly (259324c 2016-05-20)
```

What shell are you running locally?

**Comment by Osspial** [comment]
I'm running Windows 7 Powershell. Interestingly, pass-through actually works if I'm doing it through cmd and not Powershell, so it seems that it *is* in fact an issue with Powershell interpreting the flags differently than other shells.

**Comment by alexcrichton** [comment]
It looks like [this may be relevant perhaps](http://stackoverflow.com/questions/15780174/powershell-command-line-parameters-and)?

In any case though I don't think this is a Cargo bug, so closing. Thanks for the report though!
