### ISSUE TITLE
Cargo Test passes when threads panic.

### ISSUE THREAD

**Issue by 1BADragon** [rust-lang/cargo#2899]
Maybe this is on purpose but I am running some tests on classes that use TcpStreams so I have to spawn threads for client/server communication. In the server thread I am checking that the Client sent the proper data or the thread should panic. Unfortunately, even if a spawned thread panics Cargo says the test passes. Am I doing this wrong or is that a bug?

**Comment by jonas-schievink** [comment]
The test harness only checks if the thread it spawned panics, you'll have to propagate the panic inside your own thread to the thread that invoked the test.

**Comment by 1BADragon** [comment]
Oh I see, and is there some documentation on that I could read?

**Comment by jonas-schievink** [comment]
I don't think the book explicitly mentions this, but it has a chapter on tests. Other than that, there's no way to get a list of running threads (that you didn't spawn yourself), so how would the harness check if they panicked? (threads are also exited when they panic, so you wouldn't want to keep them in that list)

**Comment by 1BADragon** [comment]
Alright well thanks, I guess I will just investigate further. Ill close the issues.

**Comment by ibraheemdev** [comment]
Is there any solution to this?

**Comment by jonas-schievink** [comment]
Call [`JoinHandle::join`](https://doc.rust-lang.org/std/thread/struct.JoinHandle.html#method.join) and `.unwrap()` the result.

**Comment by ibraheemdev** [comment]
What if the thread is being spawned elsewhere?
```rust
fn should_fail() {
  std::thread::spawn(|| {
    assert!(false);
  });
}

#[test]
fn test() {
  should_fail()
}
```
Can I get the test to fail without editing the `should_fail` method?
