### ISSUE TITLE
Aliased commands should not shadow build in commands

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#2901]
Looks like currently an alias can shadow a built in command ([relevant code]). Is this the expected behavior? Git for example forbids this:

>To avoid confusion and troubles with script usage, aliases that hide existing Git commands are ignored

https://www.kernel.org/pub/software/scm/git/docs/git-config.html

[relevant code]: https://github.com/rust-lang/cargo/blob/master/src/bin/cargo.rs#L199-L221

**Comment by matklad** [comment]
cc @sbeckeriv

**Comment by sbeckeriv** [comment]
My only thoughts were around sub-commands. I have an alias that is fast-build on a project and another contributor installs the sub-command fast-build  the project should consistently run. It looks like we can use list_commands to get a list of installed commands and  throw an error or warning. Sounds like if want to mimic git cargo should throw an error and have the user clean up their file. 

Going back to my example an error would not allow you to use an alias in a project and a sub-command in another. I think that can be sorted out by people talking vs cargo supporting that configuration.

**Comment by alexcrichton** [comment]
Ah yeah it was definitely intended that default subcommands wouldn't be allowed to get aliased!
