### ISSUE TITLE
`cargo rustc --frozen` unimplemented

### ISSUE THREAD

**Issue by rillian** [rust-lang/cargo#2902]
As far as I can tell, `cargo rustc` is like `cargo build` in that it reads Cargo.toml for dependencies and download them if necessary. Therefore it makes sense for that command to take the `--frozen` switch to assert if network access is necessary for the build. However:
```
$ cargo rustc --frozen
error: Unknown flag: '--frozen'
```

**Comment by rillian** [comment]
The `--frozen` option landed in #2811.

**Comment by alexcrichton** [comment]
Hm it looks like this is implemented [on master](https://github.com/rust-lang/cargo/blob/master/src/bin/rustc.rs#L56) perhaps an older build of Cargo was being used?

**Comment by rillian** [comment]
Yep, works on a clean cargo build. I must have made a mistake. Thanks for checking!
