### ISSUE TITLE
Expose rustc version to build.rs

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/cargo#2903]
Currently the only way to find the rustc version is to invoke rustc. Which is for instance what the `rustc_version` crate does.  It would be great if `RUSTC_VERSION` or something similar was set automatically so that build scripts could customize what happens based on the version of Rust it compiles with.

See also #4408

**Comment by alexcrichton** [comment]
I'm a little wary of piling *too* much information onto build script environment variables. Right now we added exposing `RUSTC` unconditionally as the compiler being used, would that be enough?

**Comment by nagisa** [comment]
Link to the crate for the lazy: https://crates.io/crates/rustc_version

**Comment by mitsuhiko** [comment]
@alexcrichton that's what I'm using currently to shell out to rustc. Just seems like not particularly the best idea to parse compiler output manually for something that I would assume is a common problem. Alternatively one could make the argument that rust itself should provide a macro maybe that exposes the version?

**Comment by alexcrichton** [comment]
Yeah I guess a macro would perhaps be better, one day Cargo may not always run `rustc` ahead of compiling crates, so it may not even have this information on hand at all time.

**Comment by dwijnand** [comment]
#4408 tracks the more general idea of setting an env var for the rust version.

**Comment by epage** [comment]
I wonder if rust-lang/rfcs#2523 would be more appropriate.  I feel like we should at least have a cohesive plan between cargo/lang on how we should be handled version detection.

**Comment by epage** [comment]
Considering rust-lang/rfcs#2523  is an approved RFC that is meant to target these kinds of use cases, I'm going to close in favor of that.  If there is a reason we should reconsider this, let us know!

Note that we still have #4408 for gathering the rustc version for reporting purposes (like a `--bugreport` flag)./
