### ISSUE TITLE
Changing a version of a dependency based on target causes cargo to install both versions regardless

### ISSUE THREAD

**Issue by glademiller** [rust-lang/cargo#2905]
I wanted to do this

[target.'cfg(windows)'.dependencies]
schannel = "0.0.2"
hyper = {version = "0.7", default-features = false}

[target.'cfg(unix)'.dependencies]
hyper = {version = "0.9", default-features = true}

But it always ends up installing both versions of hyper and all the dependencies for hyper 0.9. 

I have observed this behaviour on Windows and have not attempted it on any other platform.

**Comment by alexcrichton** [comment]
Interesting! I'm kinda surprised this works at all, I'd expect Cargo to trip an assert somewhere...

In general though I'm not sure how feasible this would be to get working, we may just have to issue a warning for awhile saying "this probably won't work".

I'll try to think about it though and see if it's plausible to get working.

**Comment by alexcrichton** [comment]
I think this may have been fixed by https://github.com/rust-lang/cargo/pull/3123, @glademiller could you test that out and see if it works?

**Comment by glademiller** [comment]
I just tested on Nightly and it does appear to be fixed.
