### ISSUE TITLE
Instructions on how to bootstrap Cargo

### ISSUE THREAD

**Issue by mneumann** [rust-lang/cargo#292]
I ported Rust to DragonFlyBSD. Naturally there exists no snapshot of Cargo for this platform. Would be great to provide a shell script that builds Cargo.

**Comment by marcopeereboom** [comment]
I am running into the exact same issue an I am not finding anything useful from google.  Here is my output:

$ ./configure --target=x86_64-unknown-bitrig
configure: looking for configure programs
configure: found cmp
configure: found mkdir
configure: found printf
configure: found cut
configure: found head
configure: found grep
configure: found xargs
configure: found cp
configure: found find
configure: found uname
configure: found date
configure: found tr
configure: found sed
configure: found file
configure: found cmake
configure: found pkg-config
configure: found curl
configure: recreating config.tmp
configure: 
configure: processing ./configure args
configure: 
configure: CFG_PREFIX           := /usr/local 
configure: CFG_LOCAL_RUST_ROOT  :=  
configure: CFG_RUSTC            := /usr/local/bin/rustc (rustc 1.0.0-dev (built 2015-03-13))
configure: CFG_BUILD            := x86_64-unknown-bitrig 
configure: CFG_HOST             := x86_64-unknown-bitrig 
configure: CFG_TARGET           := x86_64-unknown-bitrig 
configure: CFG_LOCALSTATEDIR    := /var/lib 
configure: CFG_SYSCONFDIR       := /etc 
configure: CFG_DATADIR          := /usr/local/share 
configure: CFG_INFODIR          := /usr/local/share/info 
configure: CFG_MANDIR           := /usr/local/share/man 
configure: CFG_LIBDIR           := /usr/local/lib 
configure: CFG_LOCAL_CARGO      :=  
configure: 
configure: validating ./configure args
configure: 
configure: 
configure: looking for build programs
configure: 
configure: CFG_CURLORWGET       := /usr/local/bin/curl (curl 7.40.0 (x86_64-unknown-bitrig1.0) libcurl/7.40.0 LibreSSL/2.0.0 zlib/1.2.3 libidn/1.29)
configure: CFG_PYTHON           := /usr/local/bin/python2.7 
configure: CFG_CC               := /usr/bin/cc (Bitrig clang version 3.6.0 (tags/RELEASE_360/final) 20150227)
configure: CFG_RUSTDOC          := /usr/local/bin/rustdoc (rustdoc 1.0.0-dev (built 2015-03-13))
configure: 
configure: writing configuration
configure: 
configure: CFG_SRC_DIR          := /home/marco/git/rust/cargo/ 
configure: CFG_BUILD_DIR        := /home/marco/git/rust/cargo/ 
configure: CFG_CONFIGURE_ARGS   := --target=x86_64-unknown-bitrig 
configure: CFG_PREFIX           := /usr/local 
configure: CFG_BUILD            := x86_64-unknown-bitrig 
configure: CFG_HOST             := x86_64-unknown-bitrig 
configure: CFG_TARGET           := x86_64-unknown-bitrig 
configure: CFG_LIBDIR           := /usr/local/lib 
configure: CFG_MANDIR           := /usr/local/share/man 
configure: CFG_RUSTC            := /usr/local/bin/rustc 
configure: CFG_RUSTDOC          := /usr/local/bin/rustdoc 
configure: 
configure: cp /home/marco/git/rust/cargo/Makefile.in ./Makefile
configure: mv config.tmp config.mk
configure: 
configure: complete
configure: 
configure: 
[master]$ gmake
/usr/local/bin/python2.7 src/etc/dl-snapshot.py x86_64-unknown-bitrig
Traceback (most recent call last):
  File "src/etc/dl-snapshot.py", line 56, in <module>
    raise Exception("no snapshot for the triple: " + triple)
Exception: no snapshot for the triple: x86_64-unknown-bitrig
Makefile:91: recipe for target 'target/snapshot/cargo/bin/cargo' failed
gmake: *** [target/snapshot/cargo/bin/cargo] Error 1

I am looking for some doco on how to bootrap cargo straight from the git repo.
