### ISSUE TITLE
List of installed crates?

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/cargo#2922]
Would be great to have a command to list installed crates with their versions and note of new versions.
Both for installed binaries and dependency crates

**Comment by alexcrichton** [comment]
Today there's `cargo install --list` for installed crates, and there's the [`cargo-outdated` project](https://crates.io/crates/cargo-outdated) for dependencies. Does that work for your needs?

**Comment by DoumanAsh** [comment]
Hm... i didn't know about cargo-outdated.
Thanks for tip, though i hope it will get integrated into cargo eventually.
Kinda nice thing like in npm :)

It would be good to have also option to update all outdated binaries :)

I suppose i'll close this issue since it is not an issue.

**Comment by Hyperion101010** [comment]
Hi there, I have a problem, 
why not have an option -r for recursive tree representation.
So that it can show subdependencies as well.
Cause I had an error in libc of one crate, which i couldn't trace back.

**Comment by ordovicia** [comment]
@Hyperion101010 Are you talking about `cargo outdated`? Please file an issue to [the project's repository](https://github.com/kbknapp/cargo-outdated).

**Comment by joelparkerhenderson** [comment]
Potentially helpful-- here's how I list user-installed crates and update them.

```sh
cargo install --list | 
awk '/^\w/ { print $1 }' | 
while read x; do cargo install "$x"; done
```

**Comment by qtfkwk** [comment]
You all might consider [cargo-list](https://crates.io/crates/cargo-list), which I created earlier this year.
