### ISSUE TITLE
cargo hangs

### ISSUE THREAD

**Issue by redhatlinux10** [rust-lang/cargo#2923]
>$ cargo --version
cargo 0.13.0-nightly (664125b 2016-07-19)

os : Manjaro 16.06 64bit
https://github.com/rust-lang/crates.io-index is reachable here.

>$ RUST_LOG=trace cargo build
DEBUG:cargo::build: executing; cmd=cargo-build; args=["cargo", "build"]
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/home/bruce/MyProject/conrod/Cargo.toml; source-id=file:///home/bruce/MyProject/conrod
DEBUG:cargo::core::workspace: find_root - trying /home/bruce/MyProject/Cargo.toml
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/home/bruce/MyProject/Cargo.toml; source-id=file:///home/bruce/MyProject
DEBUG:cargo::core::workspace: find_root - trying /home/bruce/Cargo.toml
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/home/bruce/Cargo.toml; source-id=file:///home/bruce
DEBUG:cargo::core::workspace: find_root - trying /home/Cargo.toml
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/home/Cargo.toml; source-id=file:///home
DEBUG:cargo::core::workspace: find_root - trying /Cargo.toml
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/Cargo.toml; source-id=file://
DEBUG:cargo::core::workspace: find_members - only me as a member
DEBUG:cargo::core::registry: load/missing  file:///home/bruce/MyProject/conrod
TRACE:cargo::core::source: loading SourceId; file:///home/bruce/MyProject/conrod
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/home/bruce/MyProject/conrod/Cargo.toml; source-id=file:///home/bruce/MyProject/conrod
TRACE:cargo::ops::cargo_read_manifest: read_package; path=/home/bruce/MyProject/conrod/Cargo.toml; source-id=file:///home/bruce/MyProject/conrod
DEBUG:cargo::core::resolver: initial activation: conrod v0.37.2 (file:///home/bruce/MyProject/conrod)
TRACE:cargo::core::resolver: activating conrod v0.37.2 (file:///home/bruce/MyProject/conrod)
DEBUG:cargo::core::registry: load/missing  registry https://github.com/rust-lang/crates.io-index
TRACE:cargo::core::source: loading SourceId; registry https://github.com/rust-lang/crates.io-index
    Updating registry `https://github.com/rust-lang/crates.io-index`

**Comment by alexcrichton** [comment]
Thanks for the PR @redhatlinux10! 

Depending on exactly what's happening here, this *may* be fixed by https://github.com/rust-lang/cargo/pull/2885. Could you try running `strace` and see what's happening? Also do you have `insteadOf` config like in https://github.com/rust-lang/cargo/issues/2845?

**Comment by alexcrichton** [comment]
er, s/PR/report/ :)

**Comment by redhatlinux10** [comment]
@alexcrichton 
> Could you try running strace and see what's happening? 

my `cargo build` strace log is here  http://paste.opensuse.org/view/raw/93202576

> Also do you have insteadOf config like in #2845?

no .

**Comment by alexcrichton** [comment]
@redhatlinux10 oh did you mean to close?

It looks like you're connected to 192.30.253.113 (I believe github.com's IP) on port 443 and communicating over that, was the trace hung when you killed it or making progress? It may just be a case of taking awhile to clone the registry
