### ISSUE TITLE
`cargo run` has current directory set to top folder

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/cargo#293]
This should probably be set to `target/`?

**Comment by gsingh93** [comment]
I'd actually prefer the working directory to be set to the top level directory. I have folders like `resources` at the top level, and I'd like to be able to access them regardless of which folder I was in when I ran `cargo run`. I'm used to this behavior from Java/Eclipse, so there is some precedent for this.

What's the benefit of making the current directory the working directory?
