### ISSUE TITLE
Bumping a local crate's version forces a registry sync

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2931]
Happened to me on a train today. If you increment your local crates version, Cargo will hit the registry. There's no need to do that.

**Comment by brson** [comment]
Hm, more precisely. I have sever local crates with interdependencies, so I bumped several of their versions as well as their dependencies on each other. All local deps.

**Comment by alexcrichton** [comment]
Fixed in  https://github.com/rust-lang/cargo/pull/3144
