### ISSUE TITLE
Cannot compile for musl because of missing libc::NFS_SUPER_MAGIC

### ISSUE THREAD

**Issue by jirutka** [rust-lang/cargo#2937]
[libc](https://github.com/rust-lang/libc) crate does not provide [NFS_SUPER_MAGIC](https://github.com/rust-lang/libc/blob/16f3a8e96c835c3bbf071292305eeab58a286b15/src/unix/notbsd/linux/other/mod.rs#L367) for musl libc (don’t know why).  This constant is used in [cargo/util/flock:295](https://github.com/rust-lang/cargo/blob/941f48815cd44bd9281873e2d0304ffdd1af6eac/src/cargo/util/flock.rs#L295).

**Comment by alexcrichton** [comment]
I'd be fine with either just not executing this check on musl or hardcoding the value of NFS_SUPER_MAGIC, it looks like musl doesn't have a definition for that in its header files.

**Comment by jirutka** [comment]
To be honest, I have no clue what implications it may have when you hard-code that value, so the decision is up to you. I’ve simply disabled that check in Alpine package for cargo.

**Comment by alexcrichton** [comment]
Yeah that's fine, do you want to upstream that as well? I'd be more than fine taking a PR for that!
