### ISSUE TITLE
Cargo doesn't understand build metadata in versions

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#2939]
Semver allows specifying versions such as `1.0.0+20130313144700`, see http://semver.org/#spec-item-10 . Cargo can't handle such versions. See e.g. https://crates.io/crates/core_rustc-serialize which has these versions:

* 0.3.19
* 0.3.19+patch1

Specifying a dependency `core_rustc-serialize = "*"` (or  `core_rustc-serialize = "^0.3"`) results in Cargo choosing 0.3.19. There is simply no way to select `0.3.19+patch1`. Putting it in the `Cargo.toml` results in the error message "the given version requirement is invalid". You also can't select it using `cargo update --precise`. This results in a crate existing on crates.io that can effectively not be used by anyone.

See also #2222 #2935

**Comment by steveklabnik** [comment]
What if you specify the build metadata version exactly?

**Comment by steveklabnik** [comment]
Oh, sorry, I mis-read, you clearly tried that. Sorry. What does --verbose say?

**Comment by jethrogb** [comment]
The quoted text.

**Comment by steveklabnik** [comment]
That seems very strange. As part of the SemVer crates tests, I attempt to parse every version on crates.io, so it should know how to parse it...

I suspect that this is more of a SemVer bug than a Cargo bug; I'll try to investigate more in the next few days.

**Comment by alexcrichton** [comment]
@steveklabnik I wonder if this is related to version requirements vs version themselves? Maybe version requirements don't parse build metadata?

**Comment by steveklabnik** [comment]
Ah ha! That is the case. 

```
"1.2.3+250".parse::<Version>(); // this is fine
"= 1.2.3+250".parse::<VersionReq>();  // this is not fine
```

So yes, this is actually a `semver` issue that will then make it into `Cargo` once that happens.

I've opened an issue: https://github.com/steveklabnik/semver/issues/88 so closing in favor of that.
