### ISSUE TITLE
.gitignore should ignore rustfmt backup files .rs.bk by default

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#2949]
Automatically generated `.gitignore` files should probably ignore rustfmt backupfiles `.rs.bk` by default on new projects.

**Comment by alexcrichton** [comment]
Thanks for the report! This has been [proposed](https://github.com/rust-lang/cargo/pull/2926) [before](https://github.com/rust-lang/cargo/pull/2409), but this is something I think rustfmt should deal with, not Cargo.
