### ISSUE TITLE
Make https://static.rust-lang.org/cargo-dist browsable (i.e. add indexes)

### ISSUE THREAD

**Issue by jirutka** [rust-lang/cargo#2950]
It’s kinda hard to find what snapshots are available when static.rust-lang.org doesn’t provide indexes.

Related to: https://github.com/rust-lang/rust/issues/31322#issuecomment-236466490

**Comment by alexcrichton** [comment]
cc @brson, @edunham 

(I forget how the script otherwise runs here)

**Comment by brson** [comment]
I've modified `update-rust-dist-index.sh` on the build master to generate indexes for `cargo-dist` and ran it. Should be fixed.

**Comment by jirutka** [comment]
It's not, https://static.rust-lang.org/cargo-dist/ still returns an error message.

**Comment by japaric** [comment]
https://static.rust-lang.org/cargo-dist/index.html works but I'm seeing the same thing as https://static.rust-lang.org/dist/index.html

**Comment by alexcrichton** [comment]
@brson it looks like it's just uploading the same index twice, rather than regenerating for the cargo-dist dir?

**Comment by brson** [comment]
Uh, wow. My previous fix for this was all kinds of wrong. Should be working now. I've done the CDN invalidation on the main index.html but it could be 24 hours until some of the other pages are refreshed.

**Comment by jonhoo** [comment]
It looks like no builds from 2017 show up in the listing yet?

**Comment by alexcrichton** [comment]
We're no longer using buildbot for nightlies, so those archives won't be populated any more

**Comment by jirutka** [comment]
Yeah, nightlies are now on totally unpredictable URLs… 😕

**Comment by alexcrichton** [comment]
The historical process for building Cargo nightlies has been discontinued. There is a current process uploading to deterministic URLs at:

* https://s3.amazonaws.com/rust-lang-ci/cargo-builds/6f1b860da7aba4c5ea97a49de08a61f3f330e92d/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz

We plan on also maybe discontinuing this process as the main rust-lang/rust repository will be responsible for building Cargo and distributing it.

**Comment by jirutka** [comment]
So how can we easily get the **latest** nightly...?

**Comment by alexcrichton** [comment]
https://static.rust-lang.org/dist/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz

**Comment by jirutka** [comment]
Okay, but why https://static.rust-lang.org/dist/cargo-nightly-x86_64-unknown-linux-musl.tar.gz and https://static.rust-lang.org/dist/cargo-0.17.0-x86_64-unknown-linux-musl.tar.gz returns 404?

**Comment by alexcrichton** [comment]
rust-lang/rust isn't buliding musl cargo binaries

**Comment by sanmai-NL** [comment]
@alexcrichton https://static.rust-lang.org/cargo-dist/index.html seems to have fossilized ... Somewhere around 2016.
