### ISSUE TITLE
Nightly fails to hard link on Cargo build

### ISSUE THREAD

**Issue by PerryBirch** [rust-lang/cargo#2956]
Cargo build produces the following error:
error: failed to link `/{src}/target/x86_64-unknown-linux-gnu/debug/deps/liblib.a` to `/{src}/target/x86_64-unknown-linux-gnu/debug/liblib.a`

OS: Ubuntu 16.04 LTS

Tracked it down to this line:
http://bit.ly/2alFcRH

Switching to older "nightly-2016-05-26-x86_64-unknown-linux-gnu" seems to resolve.

**Comment by alexcrichton** [comment]
Interesting! Is there more of the error there as well? I'm curious why a hard link would fail in a directory that cargo basically owns entirely...

**Comment by carols10cents** [comment]
I believe this was fixed in https://github.com/rust-lang/cargo/pull/3118. Please reopen if I'm mistaken! Thank you!
