### ISSUE TITLE
Allow [replace] to reference a github pull request

### ISSUE THREAD

**Issue by vvuk** [rust-lang/cargo#2958]
Instead of 

```
[replace]
"mozjs_sys:0.0.0" = { git = "https://github.com/vvuk/mozjs.git", branch = "rust-msvc" }
```

it would be quite nice to be able to do

```
[replace]
"mozjs_sys:0.0.0" = { git = "https://github.com/servo/mozjs/pull/82" }
```

because that would make it very explicit that there is an open PR for this replacement.  This is especially helpful when publishing a test branch of a project that has a number of updated dependencies that you're trying to land.

**Comment by jonas-schievink** [comment]
This would require integration into GitHub's API

**Comment by vvuk** [comment]
Not as much as you might think -- you can get a JSON view of a PR without any authentication, e.g. https://github.com/servo/mozjs/pull/82 -> https://api.github.com/repos/servo/mozjs/pulls/82 -> then you pull out `result.git_url` and `result.head.sha`.

**Comment by alexcrichton** [comment]
I think there's a ref for all PRs, right? In that sense, you could do something like specifying `rev` directly, but we could also support `ref` for what I think is `refs/heads/pull/82`

**Comment by vvuk** [comment]
Doesn't seem to be:
```
vladimir@glacier[6120]$ git fetch origin refs/heads/pull/82:test
fatal: Couldn't find remote ref refs/heads/pull/82
vladimir@glacier[6121]$ git fetch origin heads/pull/82:test
fatal: Couldn't find remote ref heads/pull/82
```

**Comment by alexcrichton** [comment]
@vvuk oh sorry that wasn't the literal syntax, I was just guessting

https://help.github.com/articles/checking-out-pull-requests-locally/ indicates it's

```
git fetch origin pull/ID/head:BRANCHNAME
```

**Comment by jonas-schievink** [comment]
Hey, that's neat!

**Comment by vvuk** [comment]
We can probably close this -- given `pull/ID/head`, this can be handled as maybe a note in the documentation.

**Comment by yihuang** [comment]
How to specify that pull request or `ref` again?

**Comment by evanjs** [comment]
> How to specify that pull request or `ref` then?

I was able to use it like this:
``` toml
[dependencies.sqlx]
features = ["all", "default", "postgres", "json"]
git = "https://github.com/launchbadge/sqlx/"
ref = "pull/535/HEAD"
branch = "ab/macro-refresh"
```

**Comment by detly** [comment]
It requires some extra git config, see: https://gist.github.com/piscisaureus/3342247 - specifically there needs to be a way to add `+refs/pull/*/head` to the fetch config.

**Comment by mooori** [comment]
In the meantime an example has been added to the [cargo docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#choice-of-commit):

> ```toml
> # HEAD commit of PR 493
> regex = { git = "https://github.com/rust-lang/regex.git", rev = "refs/pull/493/head" }
> ```
