### ISSUE TITLE
When doing cargo update -p with replacements in play, be smarter about selecting the replaced package

### ISSUE THREAD

**Issue by vvuk** [rust-lang/cargo#2959]
When a replacement is in play, if you try to update the package by its simple name, you get:

```
> cargo update -p servo-freetype-sys
error: There are multiple `servo-freetype-sys` packages in your project, and the specification `servo-freetype-sys` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  https://github.com/vvuk/libfreetype2.git#servo-freetype-sys:2.4.11
  https://github.com/rust-lang/crates.io-index#servo-freetype-sys:2.4.11
```

it would be nice if in this case, the logic went like:
1. Does the given name match exactly two packages
2. Does one package replace the other
3. If so, then assume the replacement package is the one that is being updated

**Comment by epage** [comment]
Given `replace` is deprecated, I don't see us improving its UX further and I'm going to close this.  If there is a reason for us to reconsider this, let us know!
