### ISSUE TITLE
Deadlock in the `directory` tests

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#2961]
I reproduced this locally and it appears to be because libgit2 and rust-openssl are both initializing OpenSSL at the same time. That is, OpenSSL has weird locking support that makes it kinda hard to use as a hidden dependencies, and now it's being hard about using it as a hidden dependency :(

@sfackler do you have thoughts on this? The `libgit2` library is trying to initialize OpenSSL locking I think, although I may be able to figure out how to disable that. Before that, though, are there various options on the rust-openssl side of things?

**Comment by sfackler** [comment]
`openssl-sys` provides an [`init`](http://sfackler.github.io/rust-openssl/doc/v0.7.14/openssl_sys/fn.init.html) function that handles initialization behind a `Once`. If you can figure out how to tell libgit2 to stop doing its thing, you should be able to call `init` and the right things will hopefully happen.

**Comment by sfackler** [comment]
We could also provide a function to tell openssl-sys to assume OpenSSL has already been initialized if necessary.

**Comment by alexcrichton** [comment]
Ok, perfect, thanks! I'll funnel everything into using that function.
