### ISSUE TITLE
Nightly fails to compile the latest regex crate

### ISSUE THREAD

**Issue by pravic** [rust-lang/cargo#2963]
I am not sure that this is a cargo issue, but lets start here.

`cargo build` fails with

>error: failed to parse manifest at `t:\regex\Cargo.toml`
Caused by:
  duplicate build target found: `t:\regex\src/lib.rs`

Toolchain versions:

> `rustup -vV`
rustup 0.5.0 (4be1012 2016-07-30)
`rustup toolchain list`
stable-i686-pc-windows-gnu
stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc
nightly-i686-pc-windows-msvc (**default**)
nightly-x86_64-pc-windows-msvc
`rustc -vV`
rustc 1.12.0-nightly (545a3a94f 2016-08-04)
binary: rustc
commit-hash: 545a3a94fcbdd68c4eeb60848c8eae2118c639c7
commit-date: 2016-08-04
host: i686-pc-windows-msvc
release: 1.12.0-nightly
`cargo -vV`
cargo 0.13.0-nightly (af4ec39 2016-08-03)

**Comment by pravic** [comment]
`rustc 1.12.0-nightly (a005b6785 2016-08-02)` works fine.

**Comment by steveklabnik** [comment]
Fixed by https://github.com/rust-lang/cargo/pull/2962

**Comment by pravic** [comment]
Thanks.
