### ISSUE TITLE
Cargo should NOT package everything from the crate directory

### ISSUE THREAD

**Issue by lunemec** [rust-lang/cargo#2969]
Hello,

While I was figuring out why my project will not publish on crates.io because of maximum size, I noticed cargo added *everything* inside the project directory. This is not such a good idea, since for example Idea IDE has some xml files inside, which I have in .gitignore but are being added to the crate. Also I figured out the reason of the maximum file size limit exceeded was I forgot to delete a test LOG file which had ~200MB and was being uploaded with the crate. This also should not happen. The file was not in .gitignore, but was not commited in git.

I think the cargo should uphold files in .gitignore and extend it by common file formats that should not be in a crate - .log, .mp4 ... But this could have some downsides.

**Comment by alexcrichton** [comment]
Thanks for the report @lunemec! The nightly version of Cargo will error to publish by default if there are any untracked or dirty files in the working tree when a `cargo publish` is performed, and Cargo *should* use gitignore by default.

Perhaps you could try out nightly Cargo and see if the default ignore settings are suitable?

**Comment by alexcrichton** [comment]
Also note that `package.include` and `package.exclude` are available for fine-grained configuration in Cargo itself.

**Comment by lunemec** [comment]
Thank you for the information, I'll try the nightly version.

**Comment by lunemec** [comment]
Awesome, it works as expected:
```
error: 7 dirty files found in the working directory:

.idea/encodings.xml
.idea/misc.xml
.idea/modules.xml
.idea/rust-http-logger.iml
.idea/vcs.xml
.idea/workspace.xml
js.log
```

Thanks!
