### ISSUE TITLE
.cargo/config path overrides do not work with exact version deps

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/cargo#2983]
In serde we use a `.cargo/config` to make cargo use the local crates instead of the crates.io crates. This worked until we changed our dependencies' version requirements to `=`. Updating a crate's version and also changing the dependent's dependency version will cause cargo to not find that crate anymore.

**Comment by alexcrichton** [comment]
Interesting! Do you have an example that I could reproduce with? I was unfortunately unable to reproduce this locally.

**Comment by alexcrichton** [comment]
Note though that in general this may not be the best use of path overrides, I'd personally recommend `path` dependencies for crates that all live in one repository

**Comment by oli-obk** [comment]
while trying to create the minimal example, I noticed that

> Note: using a local configuration to override paths will only work for crates that have been published to crates.io. You cannot use this feature to tell Cargo how to find local unpublished crates.

so I guess that was our issue, I changed the version requirement and bumped the version without publishing the crate first. That definitely makes it unusable for local development. We've moved back to path dependencies
