### ISSUE TITLE
Cargo install hangs when setting .gitconfig insteadOf

### ISSUE THREAD

**Issue by gerred** [rust-lang/cargo#2985]
My $HOME/.gitconfig includes (used to, at least) the following:

```
[url "git@github.com:"]
    insteadOf = https://github.com/
```

I used this when I was working in Go to `go get` private repositories, and forgot about its existence on one of my computers. I recently was getting it up to date, and noticed that `cargo install` would completely hang. I removed it, and it now works totally fine.

This probably is closely related to #1851

**Comment by alexcrichton** [comment]
Thanks for the report! What version of Cargo was this with? I think we fixed a bug on nightly recently which I believe should address this?

**Comment by gerred** [comment]
I'm on cargo 0.13.0-nightly (c205132 2016-08-09).

**Comment by alexcrichton** [comment]
Hm can you try running `strace` to determine what syscalls Cargo's blocking at?
