### ISSUE TITLE
windows support needed to select subsystem for compilation

### ISSUE THREAD

**Issue by metajack** [rust-lang/cargo#2986]
Currently rustc seems to default to the console subsystem on windows (both for gnu and msvc builds). There should be some way to set this in Cargo.toml so that the correct subsystem is used.

Here are the known ways to deal with this currently, all of which suck:
1. After cargo builds a console subsystem app, if you want a windows subsystem one, run editbin.exe manually or as part of some higher level build script like mach.
2. Override the linker with fake one that runs editbin.exe on the executable and swaps the subsystem. This solution won't work if your link command is not a real compiled executable because the link command line might be too long due to windows command line argument limitations.
3. Set RUSTFLAGS="-C link-args=-Wl,--subsystem,windows" or whatever subsystem you want. Unfortunately this causes Cargo to link every executable with the windows subsystem. In particular this means all build scripts get compiled this way which means they pop up console windows constantly during the build process.

**Comment by metajack** [comment]
cc @vvuk @alexcrichton @larsbergstrom

**Comment by metajack** [comment]
See these for more context:
https://www.reddit.com/r/rust/comments/40l6t8/windowed_applications_with_rust/

http://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window

**Comment by alexcrichton** [comment]
I think this is just https://github.com/rust-lang/rfcs/pull/1665?

**Comment by alexcrichton** [comment]
Or rather, a concern that should be addressed as part of that RFC.

**Comment by denisbider** [comment]
OK guys. I'm a Windows developer who's looking into picking up Rust because of its safety advantages over C/C++.

The very first thing I need is to be able to target the Windows subsystem. I need to be able to target either the console subsystem or the graphical subsystem individually for each binary. That's the very first thing I need in order to use Rust.

Are you saying this is *still* not implemented at this time...?

**Comment by alexcrichton** [comment]
@denisbider this is implemented, it's just not stabilized yet. You can track support at https://github.com/rust-lang/rust/issues/37499

**Comment by alexcrichton** [comment]
This was stabilized in rust-lang/rust, so closing.
