### ISSUE TITLE
crates-io: where is version 0.3.0 coming from?

### ISSUE THREAD

**Issue by lucab** [rust-lang/cargo#2989]
Right now, crates.io reports 0.3.0 as latest version for crates-io: https://crates.io/crates/crates-io/0.3.0/

However, according to this repository history, 0.3.0 never existed and version bumped from 0.2.0 to 0.4.0: https://github.com/rust-lang/cargo/commit/bb82035f9c9e0e387d28c1a3112a087ad03c2497#diff-3a890ae5304d9c421c7206b550482ea9L3

I'm honestly not sure what's going on here: where is that 0.3.0 coming from and to which real revision (if any) does it correspond?

**Comment by onur** [comment]
also cargo-0.12.0 is missing in crates.io

**Comment by lucab** [comment]
@onur that will be tagged together with rustc 1.11.0, see https://github.com/rust-lang/cargo/issues/2882#issuecomment-233097611.

**Comment by alexcrichton** [comment]
Oh I think I may have messed up with the bumps somewhere along the way. I often forget to bump something like this around the time of publishing, so it's likely that at some point I just bumped crates-io to 0.3.0 and published that. I'll fix it all with the next publish though and ensure that the 0.12.0 tag has the right version of everything in it.

**Comment by lucab** [comment]
Thanks, I see this was some manual mashup. I guess all of this will be sorted once https://github.com/rust-lang/cargo/issues/2108 is fixed.

Another related question, once cargo is moved to stable releases: can we move development to use `+git` (or similar) pre-release labels? Rationale is that now there are multiple commits in `crates-io` labeled as "0.4" and cargo has a path-import on it, so it is very hard to check which commit is really being used and is prone to situations like this one here where artifacts on crates.io do not match.

**Comment by alexcrichton** [comment]
Oh we definitely always want to at least have git tags for all releases. I don't think we do that for the crates-io crate right now, but tbh if it's this much pain I'll just delete it as it's not worth it at all.

Could you clarify what you mean by pre-release labels though?

**Comment by lucab** [comment]
> Could you clarify what you mean by pre-release labels though? 

Something like this: https://github.com/coreos/rkt/blame/master/Documentation/devel/release.md#L40:L41. Real release version should exist in a single commit (the release itself), while everything else normally stays under development/pre-release labels.

**Comment by alexcrichton** [comment]
Sure yeah, we can try to do that! I think though that this issue has been answered so I'm going to close, but please let me know if I forgot something!

**Comment by lucab** [comment]
Yes, thanks for the insights and sorry for the disturb!
