### ISSUE TITLE
Add example of a [[...]] section to src/doc/manifest.md

### ISSUE THREAD

**Issue by casey** [rust-lang/cargo#2992]
Currentlly, http://doc.crates.io/manifest.html mentions [[...]] style sections but doesn't include an example of one.

I would suggest adding an example of a simple [[bin]] item, so that users don't need to refer to the TOML spec to understand how to use them.

For example:

```
[[bin]]
name = "my-cool-binary"
path = "src/my-cool-binary.rs"
```

**Comment by panicbit** [comment]
The manifest already gives an example using a `[lib]` section and also mentions that it works the same for the other section types. IMO that should be enough, since the only difference is an additional pair of brackets.

**Comment by casey** [comment]
Well, just speaking for myself, it wasn't at all obvious to me how to do it from the current description.

**Comment by panicbit** [comment]
Yeah, a few people on IRC (me included) didn't realise this, so maybe a bit of paraphrasing is needed.

**Comment by alexcrichton** [comment]
Seems reasonable to me!
