### ISSUE TITLE
Compiler plugin gets installed in working directory

### ISSUE THREAD

**Issue by TheDan64** [rust-lang/cargo#2993]
If I do `export CARGO_HOME=~/.cargo/` (as opposed to the full path) then `cargo install clippy` will install into my current directory:

`Installing /home/user/..path../~/.cargo/bin/cargo-clippy`

**Comment by alexcrichton** [comment]
Cargo currently doesn't do `~` expansion as that's part of your shell, so maybe the trouble is with whatever is doing that expansion? In theory shell scripts should expand that by default, but if another process is setting that which isn't a shell then it may not work.

**Comment by TheDan64** [comment]
Hmm. I had it added in my zshrc settings file

**Comment by alexcrichton** [comment]
If you print it out in a Rust program, e.g. `println!("{:?}", env::var("HOME"))`, what does that print?

**Comment by TheDan64** [comment]
`Ok("/home/dkolsoi")` with CARGO_HOME set to `~/.cargo/`

**Comment by alexcrichton** [comment]
Ah ok that's probably it, `CARGO_HOME` will need the `~` expanded

**Comment by TheDan64** [comment]
It returns the same result with it expanded, if it make any difference. Shouldn't cargo be getting it correctly from that envvar?

**Comment by alexcrichton** [comment]
What does Rust print the environment variable `CARGO_HOME` as? Cargo doesn't do `~` expansion, so if a `~` is in there then that's likely the problem.

**Comment by TheDan64** [comment]
Ah, yep. `CARGO_HOME` prints the local path, ie `Ok("/home/dkolsoi/repos/foobar/src/~/.cargo/")`

**Comment by carols10cents** [comment]
This sounds like it's not actually a cargo issue so I'm closing. Please reopen if I'm mistaken! Thanks!
