### ISSUE TITLE
Build following file lock wait results in malformed test run

### ISSUE THREAD

**Issue by ghost** [rust-lang/cargo#2995]
Migrating from https://github.com/rust-lang/rust/issues/35658.
## Steps to reproduce
1. Run emacs? (It makes and deletes autosave files in the same directories as working file buffers, which may help trigger it.)
   - `flycheck-rust` may be a contributor.
2. Iterate over a file and `cargo test` immediately after saving. Success if you see "waiting for file lock" in build output.
3. Observe that build process can't actually get the crate referenced properly (as below).
### Workaround
1. `cargo test` again without touching any files.
2. Observe usual passing tests.
## Error log

An example from a project I'm working on:

```
$ cargo test
    Blocking waiting for file lock on build directory
   Compiling wd40 v0.1.0 (file:///Users/talex/git/starfighter/wd40)
    Finished debug [unoptimized + debuginfo] target(s) in 14.0 secs
     Running target/debug/deps/wd40-f757f6198b80f6ed

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests wd40

running 11 tests
test account::orders_0 ... FAILED
test game::start_level_0 ... FAILED
test account::place_order_0 ... FAILED
test account::stock_orders_0 ... FAILED
test heartbeat_0 ... FAILED
test stock::order_cancel_0 ... FAILED
test stock::last_quote_0 ... FAILED
test stock::order_status_0 ... FAILED
test venue::heartbeat_0 ... FAILED
test venue::stocks_0 ... FAILED
test stock::orderbook_0 ... FAILED

failures:

---- account::orders_0 stdout ----
    error: extern location for wd40 does not exist: /Users/talex/git/starfighter/wd40/target/debug/deps/libwd40.rlib
<anon>:1:1: 1:19 error: can't find crate for `wd40` [E0463]
<anon>:1 extern crate wd40;
         ^~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
thread 'account::orders_0' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:674
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'account::orders_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:287

---- game::start_level_0 stdout ----
    error: extern location for wd40 does not exist: /Users/talex/git/starfighter/wd40/target/debug/deps/libwd40.rlib
<anon>:1:1: 1:19 error: can't find crate for `wd40` [E0463]
<anon>:1 extern crate wd40;
         ^~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
thread 'game::start_level_0' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:674
thread 'game::start_level_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:287

TRUNCATED
```
## Meta
- Rust: rustc 1.12.0-nightly (28ce3e8a5 2016-08-01)
- OS: Latest OSX

**Comment by alexcrichton** [comment]
I believe the underlying issue here is that if you run `cargo test` twice it may try to compile things both times, and we don't hold the lock while running tests. This in turn means that one process may stomp over the results needed by the other while tests are running.

We can probably solve this by just holding the lock on the target directories until the `Compilation` structure itself returned is dropped.
