### ISSUE TITLE
Error message when version not found could be improved

### ISSUE THREAD

**Issue by djc** [rust-lang/cargo#2997]
It would be nice if this didn't lead with "no matching package named `ring` found":

```
error: no matching package named `ring` found (required by `ladaemon`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.2.4
versions found: 0.2.3, 0.2.2, 0.2.1, ...
```

**Comment by alexcrichton** [comment]
Should be relatively easy to tackle! The error message [originates here](https://github.com/rust-lang/cargo/blob/5593045ddef2744c1042dee0c0037c2ebcc1834e/src/cargo/core/resolver/mod.rs#L641-L654) and we could just provide a different message when we have some candidates possible.

**Comment by djc** [comment]
@alexcrichton thanks for the pointer. So is this location in the code already restricted to a part where the problem is definitely down to the package existing, but no correct candidate found anyway? Or should there be some further branches to determine the best error message?

**Comment by alexcrichton** [comment]
Oh I think we could just detect that a requirement was specified, the name existed, and then use that to provide a much more tailored error message.
