### ISSUE TITLE
Split the crates-io crate

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/cargo#2999]
The dependency is currently specified as `crates-io = { path = "src/crates-io", version = "0.4" }`

While this works fine from git, it makes things needlessly complicated for packagers.
Usually, package managers download the tarball from crates.io and then runs the build. When doing that, the src/crates-io folder doesn't exist, so the build fails.
`sed -re '/^crates-io =/s/= .*version = ([^ ]+) .*/= \1/' -i Cargo.toml` "fixes" the issue.

I think just splitting crate-io out of cargo would make sense, wouldn't it? Given that it doesn't change that often anyways.

**Comment by alexcrichton** [comment]
I'd personally prefer to keep it in tree as the API is tightly coupled and the two are developed together. Why does it complicate things for packagers? It should just come in normal source tarballs and such?

**Comment by Keruspe** [comment]
I'll come back with some logs by tomorrow, but src/crates-io wasn't in the
crates.io tarballs last time I checked and thus made the build fail for
cargo releases fetched from there without the sed pasted earlier.

**Comment by alexcrichton** [comment]
Yes tarballs from crates.io are not meant to be buildable, but source tarballs from this repository should be buildable.

**Comment by Keruspe** [comment]
I see. Sounds a little weird at first, but I guess using the tarball from github makes as much sense in the end.
Works fine doing so, thanks!
