### ISSUE TITLE
regression: * deps no longer parsed

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#3001]
On `cargo 0.13.0-nightly (c205132 2016-08-09)`, deps like `0.2*` no longer parse.

I'm not sure if these are valid, but they used to work, e.g on stable (`cargo 0.11.0-nightly (259324c 2016-05-20)`)

Minimal example:

```rust
[package]

name = "foo"
version = "0.3.0"

[lib]
name = "foo"
path = "src/lib.rs"

[dependencies]
plugin = "0.2*"
```

works fine on stable, gives the following on nightly:

```
$ cargo build --verbose
error: failed to parse manifest at `/Users/manishearth/sand/bar/tempcrate/Cargo.toml`

Caused by:
  you have already provided an operation, such as =, ~, or ^; only use one
```

**Comment by steveklabnik** [comment]
They are not valid per semver, you need the `.`

**Comment by Manishearth** [comment]
Can we then phase them out slowly? This is a breaking change that affects people pinning to iron 3 (e.g. rust-playpen).

**Comment by steveklabnik** [comment]
It's going to be a giant pain for me.

We could always revert cargo back to a previous semver version as a quick fix.

**Comment by steveklabnik** [comment]
So, thinking more: I could backport a warning to the 2.x series of semver, we could make cargo use that instead. That probably wouldn't be _too_ bad, though part of the reason why I re-wrote all that code was because it is a giant mess...

**Comment by Manishearth** [comment]
Yeah, I don't want to muck up semver's code too much. But I'm not sure how this can be done on the pure-cargo side either.

Perhaps a crater run would help us gauge the full impact and determine if this is necessary? @brson

**Comment by steveklabnik** [comment]
So, another thing:

I currently do a regression test across all of crates.io: https://github.com/steveklabnik/semver/blob/master/tests/regression.rs

But note that's just for the version, not for dependencies. it looks like that's supported https://frewsxcv.github.io/rust-crates-index/crates_index/struct.Dependency.html

So I could also figure it out that way, and probably should add that regardless.

**Comment by steveklabnik** [comment]
So, uh https://travis-ci.org/steveklabnik/semver/jobs/152783177

That is, this seemgly passed on semver master for every crate on crates.io.

@Manishearth I can't actually find a released `iron` that has this dep. v3.0: https://github.com/iron/iron/commit/16c858ec2901e2992fe5e529780f59fa8ed12903

Shows them actually _fixing_ this. And it looks like 2.6 wasn't tagged?

**Comment by steveklabnik** [comment]
I used cargo-clone to grab iron 2.6, and it does have `0.2*`

So, now I'm confused about my tests :(

**Comment by steveklabnik** [comment]
okay so https://travis-ci.org/steveklabnik/semver/jobs/152791793

```
testing crate iron at version: 0.2.6

testing dependency: ^0.1

testing dependency: ^0.2

testing dependency: ^0.7

testing dependency: ^0.3

testing dependency: 0.2.*

testing dependency: ^0.3

testing dependency: ^0.1

testing dependency: ^0.5

testing dependency: ^0.1

testing dependency: ^0.7
```

apparently, the crates-index crate is not returning the same contents as the actual cargo.toml.

Looking at https://github.com/rust-lang/crates.io-index/blob/master/ir/on/iron#L47

```json
{"name":"iron","vers":"0.2.6","deps":[{"name":"modifier","req":"^0.1","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"num_cpus","req":"^0.2","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"conduit-mime-types","req":"^0.7","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"log","req":"^0.3","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"plugin","req":"0.2.*","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"typemap","req":"^0.3","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"error","req":"^0.1","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"url","req":"^0.5","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"lazy_static","req":"^0.1","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"hyper","req":"^0.7","features":[],"optional":false,"default_features":false,"target":null,"kind":"normal"},{"name":"time","req":"*","features":[],"optional":false,"default_features":true,"target":null,"kind":"dev"}],"cksum":"6d02706746b2d95c50f463fc619de64efe10682adfa17fa18dc95e0a92b10237","features":{"default":["ssl"],"ssl":["hyper/ssl"]},"yanked":false}
```

This _also_ has `0.2.*`. 

@alexcrichton do you have any idea what's going on here?

**Comment by steveklabnik** [comment]
From IRC:

```
20:43 <~acrichto> steveklabnik: I think we round trip
20:43 <~acrichto> in the sense of we parse the requirement
20:43 <~acrichto> and then when we emit the json we emit that requirement to a string
20:43 < steveklabnik> would that be in cargo or in crates.io?
20:45 <~acrichto> steveklabnik: oh probably both actually
20:45 <~acrichto> as in, Cargo's sending requests to crates.io
20:45 <~acrichto> but crates.io is then re-parsing and re-encoding
```

So yeah, @brson a crater run to check this out might be a good idea. idk. uuuugh

**Comment by steveklabnik** [comment]
That said, this change has been in nightly for a while, and we also haven't seen it break. So maybe things are okay? I dunno :frowning:

**Comment by alexcrichton** [comment]
Hm ok, so I think we'll want to revert this for now and go back to the old semver version. @steveklabnik could you send a PR for that? Otherwise I can do so later tonight.

A similar situation here is that I fixed a parsing bug in TOML but Cargo's still issuing warnings about it. From time to time I still see that url's 0.5.* manifest doesn't parse correctly, so it'll take awhile to flesh all this out.

**Comment by alexcrichton** [comment]
@steveklabnik 

So to clarify what happened with TOML, awhile ago the parser was discovered to [have a bug](https://github.com/alexcrichton/toml-rs/pull/94) where it accepted invalid syntax. This was found in the wild as part of url-0.5.9. To enable a smooth transition, I implemented an [option in the TOML parser](https://github.com/alexcrichton/toml-rs/commit/1ed6801137ede253844a6d798d5f9f8327dc0090) to accept the old, broken, syntax.

When [toml was updated](https://github.com/rust-lang/cargo/pull/2680/files) I [added some logic](https://github.com/rust-lang/cargo/blob/5593045ddef2744c1042dee0c0037c2ebcc1834e/src/cargo/util/toml.rs#L167-L185) which basically does:

* Attempt to parse TOML with the "real" parser. If that succeeds, we're good.
* Attempt to parse TOML with the old/broken parser. In this case flip a flag in the parser. If that succeeds, issue a warning but we're otherwise good.
* Otherwise, return the first error.

Could something like that be done for the semver crate as well? E.g. have a temporary option (off by default) to accept the old syntax?

**Comment by steveklabnik** [comment]
Conceptually, we can. It might make the crate's deps heavier, but I imagine most non-trivial programs will already have a regex dep...

**Comment by steveklabnik** [comment]
(and this would need coordination with cargo)

**Comment by alexcrichton** [comment]
@Manishearth note that we've pushed an upgrade of the semver dependency in https://github.com/rust-lang/cargo/pull/3154. I believe we've provided a transition path for any crates with these sorts of bad version requirements, but an extra pair of eyes is always helpful! 

If you see any breakage, please be sure to let us know!

**Comment by Manishearth** [comment]
cc @nox, our resident overlord of versioning

**Comment by Manishearth** [comment]
I think iron was the only broken one for us, but that should have been fixed since then. Hopefully nothing breaks now.

Thanks!
