### ISSUE TITLE
Cargo metadata subcommand should work with workspaces

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3003]
Currently it gives

```
error: manifest path `/home/matklad/projects/vulkano/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

Ideally it should return the info in the same format as `metadata` command for the non-virtual manifest. The only obstacle seems to be the `root` node in the `resolve`.

And perhaps for any package that is a part of the workspace `cargo metadata` should indicate it.

**Comment by matklad** [comment]
Ok, so to solve this we need to get rid of the `root` field in the `Resolve` structure. It is not used in a significant way during resolve procedure and basically just duplicates `Workspace::current`.

**Comment by matklad** [comment]
Note: `check_cycles` in the `resolver` may be buggy because it currently only checks for cycles in sub graph reachable from the `root`.

**Comment by alexcrichton** [comment]
Note that unfortunately we can't get rid of `root` in the lockfile (and transitively `Resolve`), but it's fine to just ignore it and not really treat it as the "root" any more. Seems reasonable to me that this'd be expected to work!

**Comment by matklad** [comment]
>Note that unfortunately we can't get rid of root in the lockfile (and transitively Resolve)

But why? What are the reasons besides backwards compatibility?

**Comment by alexcrichton** [comment]
No reason beyond backwards compatibility. The thinking is that older Cargo instances should be able to work with newer lock files wherever possible.

**Comment by matklad** [comment]
But we don't use `root` from the `Resolve` when we are writing a lock file: https://github.com/rust-lang/cargo/blob/master/src/cargo/core/resolver/encode.rs#L279-L281.

So it should be possible to remove it?

**Comment by matklad** [comment]
That is, remove from the `Resolve` struct, not from the lockfile of course (though we can accept lockfiles without `root` to be able to delete it later).

**Comment by alexcrichton** [comment]
Oh! We should totally do that if we can!

**Comment by matklad** [comment]
And is there any way to get the list of workspace members? Perhaps this should be a part of `cargo metadata` json? 

We *don't* need this in IntelliJ Rust yet, but it seems to be generally useful.

**Comment by alexcrichton** [comment]
Oh yeah certainly, I believe you can iterate over packages with [`ws.members()`](http://doc.crates.io/cargo/core/struct.Workspace.html#method.members)
