### ISSUE TITLE
Need way to run some code before any of unit tests

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/cargo#3008]
The details can be found [logging while running cargo test](http://stackoverflow.com/questions/35289510/logging-while-running-cargo-test).

The problem for me is in usage of [rust log library](https://doc.rust-lang.org/log/log/index.html),
to get it work you need call "initialization" code that provide implementation of  `log::Log` trait
to logging macros. 

So to get output from your code that tested by "cargo test" you need somehow call "logging_init" function, but as I see at now there is no way to tell "cargo" run something before any tests.

**Comment by alexcrichton** [comment]
Thanks for the report! Cargo doesn't manage the test harness, however, so this bug may be more appropriate for rust-lang/rust. Could you reopen over thre?

**Comment by Dushistov** [comment]
@alexcrichton as you suggest I report it as [rust-lang/rust bug](https://github.com/rust-lang/rust/issues/35762)

**Comment by alexcrichton** [comment]
Thanks!
