### ISSUE TITLE
Non-UTF-8 output on localized MSVC

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/cargo#3012]
This might be related to the comments in #2560, but I'm not sure: A localized (e.g. German) MSVC can produce non-UTF-8 output, which can become almost unreadable in the way it's currently forwarded to the user.

This can be seen in an (otherwise unrelated) issue comment: https://github.com/alexcrichton/gcc-rs/issues/87#issuecomment-233023624
Note especially this line:
```
note: Non-UTF-8 output: LINK : fatal error LNK1104: Datei \"ucrt.lib\" kann nicht ge\xf6ffnet werden.\r\n
```
That output might be a lot longer for multiple LNK errors (one line per error, but the lines are not properly separated in the output, because they are converted to `\r\n`) and become really hard to read.
If possible, the output should be converted to Unicode in this case.

**Comment by alexcrichton** [comment]
Interesting! Are you seeing these messages as part of a standard `cargo build`?

**Comment by Boddlnagg** [comment]
No, I'm modifying linker arguments with `cargo rustc ... -Clink-args=...`, so the actual linker errors are totally my fault, but I would like to read them to see what I'm doing wrong :wink:

**Comment by alexcrichton** [comment]
Oh actually this output is coming from the compiler, not from Cargo. Can you open a bug over there instead?

**Comment by Boddlnagg** [comment]
Done.

**Comment by alexcrichton** [comment]
Thanks!
