### ISSUE TITLE
Provide time taken for cargo doc

### ISSUE THREAD

**Issue by retep998** [rust-lang/cargo#3016]
Right now `cargo build` has a very informative message saying how long a build took. It would be useful if `cargo doc` could provide a similar message.

**Comment by srinivasreddy** [comment]
I am taking it.

**Comment by KalitaAlexey** [comment]
@srinivasreddy,
Hi.
Are you working on it?

**Comment by srinivasreddy** [comment]
nope. Please take it.

**Comment by KalitaAlexey** [comment]
@srinivasreddy,
Okay.
I will start working.
