### ISSUE TITLE
(travis-)Build fails with beta, works with stable

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang/cargo#3028]
Hi. [This build on travis](https://travis-ci.org/matthiasbeyer/imag/builds/153957192) fails. 

[The (succeeding) build before](https://travis-ci.org/matthiasbeyer/imag/builds/152339412) used:

```
rustc 1.11.0-beta.3 (052e32bd9 2016-08-08)
cargo 0.12.0-nightly (6b98d1f 2016-07-04)
```

The failing one uses:

```
rustc 1.12.0-beta.1 (822166b84 2016-08-16)
cargo 0.13.0-nightly (cd8ad10 2016-08-15)
```

On my local machine I cannot reproduce (`cargo 0.11.0 (built 2016-07-17)`) this issue. I talked to `sfackler` on IRC and I was told to open an issue here.

---

Besides:

I have a messed up dependency spec in https://github.com/matthiasbeyer/imag/blob/master/libimagentryselect/Cargo.toml#L7 but that was fixed (https://github.com/matthiasbeyer/imag/pull/650) and the fix didn't solve the issue.

**Comment by alexcrichton** [comment]
Thanks for the report! We'll fix this with a new beta after https://github.com/rust-lang/rust-packaging/pull/56 lands, and the actual PR that fixed this was https://github.com/rust-lang/cargo/pull/3010.

cc @steveklabnik 

I'm gonna close for now as we'll try to get a new beta out soon

**Comment by matthiasbeyer** [comment]
@alexcrichton so it was a cargo issue, not something on my side? Nice to know! Lets hope the new beta lands soon, so I can continue working. :heart:

**Comment by alexcrichton** [comment]
@matthiasbeyer indeed! That semver requirement spec is technically invalid I believe, so you may wish to update it (that'll get things working again immediately), but Cargo will have a longer "deprecation period" for those kinds of invalid version requirements.

**Comment by matthiasbeyer** [comment]
You mean the one from https://github.com/matthiasbeyer/imag/blob/master/libimagentryselect/Cargo.toml#L7 ?

It was fixed in https://github.com/matthiasbeyer/imag/pull/650 in https://github.com/matthiasbeyer/imag/pull/650/commits/eb70ec70dff36d1a61020d55082392a8d9cffaeb but that didn't solve the issue.

**Comment by alexcrichton** [comment]
I think `2.*` may also be an invalid spec? Maybe it has to be `2.*.*`?

**Comment by matthiasbeyer** [comment]
No, [I don't think so](http://doc.crates.io/specifying-dependencies.html#wildcard-requirements).

**Comment by alexcrichton** [comment]
Looks like there's [another one here](https://github.com/matthiasbeyer/imag/blob/master/libimagtimeui/Cargo.toml#L7) that needs to be updated

**Comment by matthiasbeyer** [comment]
That indeed seems to fix the issue, though a dependency now fails to compile.
