### ISSUE TITLE
Can't enable a feature that only exists in a local Cargo override

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#3033]
I have a local clone of servo/rust-mozjs, and I have added the path to Servo's .cargo/config. When I add `promises = ['mozjs_sys/promises']` to the clone's `features` section, then add `features = ["promises"]` to Servo's Cargo.toml entry for rust-mozjs, I get this error:

```
error: Package `js v0.1.3 (https://github.com/servo/rust-mozjs#755c8cc8)` does not have these features: `promises`
```

**Comment by alexcrichton** [comment]
Yeah this is unfortunately just another limitation of path overrides, we should document it though!

**Comment by kellda** [comment]
Looks like a duplicate of #2762, maybe either one can be closed ?

**Comment by kellda** [comment]
Looks like a duplicate of #2582, maybe either one can be closed ?
