### ISSUE TITLE
Unstable dependency selection and rebuilding

### ISSUE THREAD

**Issue by jwilm** [rust-lang/cargo#3043]
I've got a project with workspaces that looks roughly like

```
├── Cargo.lock
├── Cargo.toml
├── push
│   └── Cargo.toml
├── src
└── util
    └── Cargo.toml
```

`util` has a dependency on `postgres` with the `uuid` feature. I've recently upgraded postgres to support `uuid` 0.3. Since a new version hasn't been cut, I've added `postgres` to my `.cargo/config`. There's a package in my project that depends on `uuid` 0.2 internally; this may be important. Now, whenever I run `cargo build` from the `push` folder, there's a change that `postgres` decides to switch between 0.2 and 0.3 of `uuid` thereby triggering rebuilds of `postgres`, `util`, and my `push` crate.

Here's some fingerprint logs demonstrating the behavior:

One run

```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for postgres v0.11.10 (file:///home/jwilm/code/rust-postgres): new (uuid v0.2.3) != old (uuid v0.3.1)
```

Some number of runs later (varies)

```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for postgres v0.11.10 (file:///home/jwilm/code/rust-postgres): new (uuid v0.3.1) != old (uuid v0.2.3)
```

Other fingerprint logs are a result of postgres deciding to rebuild, and there's nothing to suggest why it chose a different uuid abrubtly. The Cargo.lock file does not appear to change.

I've tried setting a workspace in `rust-postgres/Cargo.toml` to no effect. The rust-postgres uuid dependency looks like this:

```
uuid = { version = ">= 0.1, < 0.4", optional = true }
```

which does allow for other versions. In my project Cargo.toml files, only uuid `0.3` is ever specified other than in third-party dependencies which use `0.2` internally.

rustc/cargo versions:

```
jwilm@jwilm-desk ➜  ~/code/onepush/push  rustc -V
rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)
jwilm@jwilm-desk ➜  ~/code/onepush/push  cargo -V
cargo 0.13.0-nightly (41b2177 2016-08-22)
```

**Comment by alexcrichton** [comment]
Hm, sounds fishy! Do you have any `paths` overrides in `.cargo/config` in play?

**Comment by jwilm** [comment]
Only for `rust-postgres`, but there's nothing changing over there to warrant a rebuild.

```
paths = ["/home/jwilm/code/rust-postgres"]
```

**Comment by alexcrichton** [comment]
Ah that'd do it, if you remove that is the build deterministic?

There's a couple of known bugs in Cargo where `paths` can cause nondeterministic compiles.

**Comment by jwilm** [comment]
Well, it's a deterministic failure. I need the path override so that another dependency uses my version of `rust-postgres`. Should this just be closed with a reference to one of those issues?

**Comment by alexcrichton** [comment]
I'd recommend using `[replace]` for overriding for now, otherwise I believe this is https://github.com/rust-lang/cargo/issues/2041

**Comment by nathanaeljones** [comment]
@alexcrichton Is there a nightly build available which supports combining workspaces and `[replace]`? [Do I just have a bad build here?](https://github.com/rust-lang/cargo/issues/3099).

**Comment by alexcrichton** [comment]
@nathanaeljones I'll comment more on that issue

**Comment by alexcrichton** [comment]
I believe we've since implemented warnings for `paths` overrides that are likely to cause fishy compilations, so I'm going to close this.
