### ISSUE TITLE
Options to turn on treating warnings as error

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/cargo#3045]
When just using rustc, this can be turned on via `-D warnings`. But there seems no way to get this working with cargo. It can be done via `#[deny(warnings)]` too, but when there are several crates in one project, for example, a project can contains a library, several binaries, tests, benches and some examples, it will be convenient to just trigger it via an option of cargo instead of adding a line to each crate (and future crates).

**Comment by alexcrichton** [comment]
Would `RUSTFLAGS=-Dwarnings` suffice?

**Comment by BusyJay** [comment]
Thx, it works perfectly!
