### ISSUE TITLE
Consider changing `cargo --version` to output a proper semver

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3046]
`cargo --version` does a wonderful job providing a human readable version, however its output format is not standardized anywhere and may be difficult to parse programmatically. 

Perhaps we should introduce something like `cargo version --semver` which outputs a string strictly adhering to semver standard (`major.minor.patch-release+build.meta`)? 

```
$ cargo version --semver
 0.11.0-nightly+259324c.2016-05-20
```

http://semver.org/

**Comment by alexcrichton** [comment]
cc @brson 

We'd probably want to mirror this change to `rustc` as well if we were to land it, but seems reasonable to me

**Comment by matklad** [comment]
And also for rustup.

**Comment by brson** [comment]
Agree it should be done across all tools, using the same switch, so maybe like `--v-semver`, or `--semversion`.

We could also just tack the build metadata onto the existing reported version, which is already semver (if you parse it out), at the risk that existing tools would not understand it (I suspect this wouldn't work for that reason).

But for multiple reasons this doesn't strike me as particularly important: tools will need to continue understanding the existing format for back-compat; the extra metadata isn't all that important.

If we were to do this we might want to consider fixing the confusing distinction between the commit date and build date as well, though that requires changes to the release build process.

**Comment by carols10cents** [comment]
I don't believe this is an issue anymore, since `cargo --version` now outputs text such as: 

- `cargo 0.21.0 (5b4b8b2ae 2017-08-12)`
- `cargo 0.22.0-beta (3d3f2c05d 2017-08-27)`
- `cargo 0.23.0-nightly (8118b02ac 2017-09-14)`

and the second parts of these look like valid semver to me. Please reopen if I'm mistaken!
