### ISSUE TITLE
Multiple Packages With Binaries Found

### ISSUE THREAD

**Issue by mmstick** [rust-lang/cargo#3049]
Having an odd issue which I can't figure out. If I install my Rust application with:

```sh
cargo install --git https://github.com/mmstick/parallel
```

I get this error:

```
error: multiple packages with binaries found: generate-files, libc-test, parallel
```

Yet if I install the application with this command:

```sh
cargo install parallel
```

It compiles perfectly.

**Comment by alexcrichton** [comment]
Ah yeah if a git repository has multiple crates inside of it all with binaries Cargo has to know which one is actually being installed. The package on crates.io, however, is specific, so that's why that works instead.

Does this work for you?

```
cargo install --git https://github.com/mmstick/parallel parallel
```

**Comment by mmstick** [comment]
That does work perfectly.

**Comment by daiheitan** [comment]
The RFC is still indicating to use `-p` https://github.com/rust-lang/rfcs/blob/master/text/1200-cargo-install.md

@alexcrichton

**Comment by steveklabnik** [comment]
https://doc.rust-lang.org/cargo/commands/cargo-install.html says

```text
--bin name...
Install only the specified binary.
--bins
Install all binaries.
```

neither of these worked for me, still giving the error about wanting to know which of multiple packages to install, but passing the binary name as an argument like suggested in this issue did work.

**Comment by epage** [comment]
@spease this is a fairly old issue and it is unclear if its related to this issue.  If this appears to be a bug, it might be good to create a new issue and include full reproduction steps.  If this is a question on how to use Cargo, you might want to post on https://users.rust-lang.org/

**Comment by spease** [comment]
Sorry, maybe it's not clear how I arrived at this ticket.

If I run

```
CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --git "ssh://user@host/home/user/repo"
```

I get `Multiple Packages with Binaries Found`.

If I run 

```
CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --git "ssh://user@host/home/user/repo" --bin app
```

which is what the `--help` suggests is the right option for what I'm trying to do, I get the same error. That's when I started googling and found this ticket.

If I use the suggested solution in this ticket

```
CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --git "ssh://user@host/home/user/repo" app
```

then I get
```
failed to load manifest for workspace member...

Caused by:
  failed to load manifest for dependency `dependency`
```

I don't know if this is the best ticket, but it seems like this is broadly the same usability issue.

**Comment by epage** [comment]
As you highlighted, something is going on with `dependency` but I can't really say much without a reproduction case.

**Comment by spease** [comment]
Figured it out.  The issue was that an underlying dependency was outside the project tree as I had to modify a third-party library and the PR never got accepted or rejected, so I never updated the dependency to a permanent value. Opened #14924 to discuss making the error clearer.
