### ISSUE TITLE
Ability to refer to features in dependencies from the command line is broken

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#3058]
See https://github.com/servo/servo/issues/13117

`./mach clippy` in servo used to run `cargo build --features script/plugins/clippy`. The `servo` crate (the one being built) does not directly use the `plugins` crate (which has a `clippy` feature), but its dependency, `script` does.

This used to work fine. It now gives an error "feature name must not contain slashes: `plugins/clippy`"

Seems like a breaking change?

cc @alexcrichton

**Comment by alexcrichton** [comment]
Yes this was a change made in https://github.com/rust-lang/cargo/pull/2821 as it was never intended to be exposed. Features of transitive dependencies are intended to be private implementation details, not exposed as part of the API.

**Comment by carols10cents** [comment]
Sounds like this should be closed, please reopen if I'm mistaken! Thanks!
