### ISSUE TITLE
Enforce semver rules on crates.io

### ISSUE THREAD

**Issue by NeoLegends** [rust-lang/cargo#3074]
Elm does this. Whenever somebody pushes code to their package management system, it checks the public API for incompatibilities and checks whether those are reflected in the associated version number. This would be great for crates.io! See http://elm-lang.org/.

**Comment by steveklabnik** [comment]
Could you re-file this on https://github.com/rust-lang/crates.io please? Thanks! (I thought we already had one, but I guess not.)
