### ISSUE TITLE
No colors in git bash on windows

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3077]
Hi! I don't get colored output when using Git Bash on windows:

![colors](https://cloud.githubusercontent.com/assets/1711539/18302219/2aeb19a8-74df-11e6-9f99-21a7ef59f282.png)

cc @Stebalien

**Comment by Stebalien** [comment]
What's your `$TERM`?

**Comment by Stebalien** [comment]
Actually, that's probably https://github.com/Stebalien/term/issues/58. Now that my thesis is "done" (well, submitted) I should have time to fix this once and for all.

**Comment by matklad** [comment]
Yep, doing `TERMINFO=$(cygpath -w /usr/share/terminfo) cargo build --color always` does the trick. I somehow assumed that "only a very minimal set of operations are supported on mys2/cygwin" includes colors, and that this one is a different issue than. I was wrong, so this could be closed :)

**Comment by ehuss** [comment]
@zubair1024 colors should "just work" on msys terminals.  Is it not working for you?  Can you provide more detail on your environment (versions you are using, etc.)?
