### ISSUE TITLE
Possible mistake in documentation

### ISSUE THREAD

**Issue by poidl** [rust-lang/cargo#3079]
As far as I understand, workspaces have not been added to the currently stable cargo version (0.12.0 ... by "stable version" I don't mean the master branch, but the most recent commit in the master branch that is tagged as a release). However, http://doc.crates.io/manifest.html explains how to use workspaces. Is it intended to document a feature in the mainstream documentation, which has not been implemented in the currently stable release? If yes, I have to say it's confusing for a beginner like me, because I'm thinking I'm doing something wrong on my end if it doesn't work. Thanks for your help! Stefan

**Comment by keeperofdakeys** [comment]
I just got caught out by this issue too. I'm guessing that crates.io grabs the ./src/doc/manifest.md from git mater, because the 0.12.0 tag doesn't have any mention of them in its version of the file. Unless a new cargo release is planned soon, I'd recommend removing the mention from crates.io.

**Comment by alexcrichton** [comment]
Ah yeah this is an unfortunate repercussion of how our documentation is set up, we don't currently have nightly/beta/stable docs like rust does :(

**Comment by poidl** [comment]
I see. As a further suggestion: if there exists only one version on the main website, shouldn't it be the stable one? Would it be technically difficult (or otherwise disadvantageous) to display the "old" but stable docs? I assume that the majority of people consulting the docs do have the stable cargo version installed. 

keeperofdakeys pointed out that the docs are located in src/doc. That helps, now I know how to browse the "stable" *.md files from the github repository. They are nicely formatted too.

**Comment by alexcrichton** [comment]
Yeah ideally we'd have staged docs like Rust does, where they're promoted every so often, but it's just infrastructure we haven't set up yet :(
