### ISSUE TITLE
cargo ignores warning from dependecies

### ISSUE THREAD

**Issue by ASMfreaK** [rust-lang/cargo#3081]
I have crate `a` which has dependency on crate `b` which inside has local dependency on crate `b-c`. 
Crate `b-c` have build.rs, which prints warning on some (mis)configurations like this:
```rust
fn main() {
    if condition {
        println!("cargo:warning=You have been warned!");
    }
}
```
When I cargo build `b` and condition is true, cargo do prints warning, but if I cargo build `a` with the same condition warning gets ommited from output. Is it a bug or a feature?

**Comment by alexcrichton** [comment]
Thanks for the report! Currently Cargo only prints warnings in builds scripts for *path* dependencies, not upstream dependencies. Is `b-c` a path dependency in your project, or is it from crates.io?

**Comment by ASMfreaK** [comment]
It is from github.

**Comment by alexcrichton** [comment]
Ah yeah I think that'd explain it. Upstream deps from different sources (e.g. git or crates.io) won't show warnings by default. If you pass the `-v` flag, though, I believe it should show up

**Comment by ASMfreaK** [comment]
`-v` is `--verbose`? I tried both ways and the warning is omitted.

**Comment by alexcrichton** [comment]
Oh right sorry, it's printed out on `-vv`, not just `-v`

**Comment by ASMfreaK** [comment]
Yeah. So hidden warnings are expected behavior?

**Comment by alexcrichton** [comment]
Indeed! (to keep the noise down for a normal build)

**Comment by ASMfreaK** [comment]
Thank you.
