### ISSUE TITLE
Build is broken after updating to cargo 0.12 (include! works differently)

### ISSUE THREAD

**Issue by Riateche** [rust-lang/cargo#3082]
Minimal example: https://gist.github.com/Riateche/9d3a583e5c0f2507f76e70494f8078c7

It seems that `include!` macro behaves differently in cargo 0.12. The example compiles successfully in cargo 0.11 because `include!` seems to work relative to current file.  In 0.12 it seems to work relative to crate root, so it fails to find file2:

> ...include_test-7982a069036284d5/out/file1.rs:1:1: 1:22 error: couldn't read "src/file2.rs": No such file or directory (os error 2)
> ...include_test-7982a069036284d5/out/file1.rs:1 include!("file2.rs");
> 
> src/lib.rs:3:1: 3:49 note: in this expansion of include!

The obvious solution is to use `include!` with an absolute path, but sudden break of build is still unexpected.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this may be a rustc bug, however, could you open an issue on the rust-lang/rust repository instead?
