### ISSUE TITLE
Cargo's tests fail on osx when using rustup.rs

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#3084]
I've been using rustup.rs these days, but it's been a while since I worked on cargo. I just tried to run cargo's test suite and I get 7 failures, some of which contain the error message "error: no default toolchain configured", which is pointing at rustup.rs as the culprit. 

Further evidence is that when I remove `~/.cargo/bin` from my `PATH`, then run:

```bash
$ ./configure --disable-cross-tests --disable-optimize
$ make
$ make test
```

All of cargo's tests pass. This uses my checkout of rustc installed to `/usr/local/bin/rustc`, which I just rebuilt today, so it's `rustc 1.13.0-dev (1fca1ab0e 2016-09-10)`.

When I put `~/.cargo/bin` in my path before `/usr/local/bin` so that I'm using rustup.rs, `which rustc` is `~/.cargo/bin/rustc`, and my rustup default is set to nightly, which I updated yesterday, `rustc --version` returns `rustc 1.13.0-nightly (f1f40f850 2016-09-09)`. `rustc -vV` runs without error.

With this setup, if I run the same 3 commands above, I get 7 test failures. [Full output in this gist](https://gist.github.com/carols10cents/4683ffcdca1e66495f02bca7bf6071ef); note the error messages I'm seeing in some of the tests that say "error: no default toolchain configured".

I looked around in rustup's issue tracker a bit for potential situations or causes of this problem, and the only thing I found that looked slightly promising was the aside that "rustc -vV should not be failing with that error even if no default toolchain is configured" [in an issue's comments](https://github.com/rust-lang-nursery/rustup.rs/issues/75#issuecomment-188901151).

I'm going to continue poking around a bit, my next guess is to look at how the cargo tests invoke commands and see if they're changing the PATH or something else about the environment that makes rustup sad... 

I'm also happy to move this whole issue to rustup's issue tracker if this sounds like rustup is creating the problem. `rustup --version` is `rustup 0.6.3 (a0e2132 2016-08-28)`. /cc @brson

**Comment by alexcrichton** [comment]
Ah yes I've seen this classic error before, and I believe @brson has run into it. I haven't been able to reproduce it yet, but I think it's now been unlocked! The key difference here is that you're using `./configure && make test` vs `cargo test` (which I use locally). 

Cargo tests munge the value of `$HOME` for subprocesses to prevent polluting or reading the home directory configuration. If you run `./configure && make` then this means we're running the rustup `rustc` binary with `$HOME` pointing to an arbitrary new location, which greatly confuses rustup. If you run `cargo test`, however, I believe that the environment variables rustup sets (I think `PATH`?) end up getting the tests working.

I suppose my *preferred* solution here would be to update rustup to work if `$HOME` isn't set (if that's possible) and we can perhaps investigate other alternatives if that doesn't work.

**Comment by carols10cents** [comment]
> The key difference here is that you're using ./configure && make test vs cargo test (which I use locally).

Aha! Interesting! I was using `make test` since that's what travis does. If I run `CFG_DISABLE_CROSS_TESTS=1 cargo test`, then I get all the tests to pass locally.

Is that how you'd recommend a casual contributor run tests before submitting a PR? If so, I'm happy to add that command to the README and move this issue over to rustup, which sounds like the best course of action at this time to me...?

**Comment by alexcrichton** [comment]
Ah yeah if you specifically want to just disable the cross-compile tests when running `cargo test`, that's how it's done. 

For casual contributors I currently recommend `cargo test` plus "ignore the cross-compile test failures", but that obviously isn't great :(. We should probably add that to the README at the very least, but in my opinion the ideal situation would be:

* Synchronize all cross-tests to check for a cross-compiler at the beginning.
* If one is found, run all tests
* If one is not found, **only fail one test** but have all the others pass
* In the failing test, try to detect rustup and recommend `rustup target add ...`. 
* If rustup is not found, then print out that this is a failure that can be ignored or you can set an environment variable to ignore the test.

Does that make sense?

**Comment by carols10cents** [comment]
> Does that make sense?

I.... am going to make a new issue for all of that, haha :) Will propose a readme change in a minute!
