### ISSUE TITLE
Can't add GitHub's new style teams as crate owners.

### ISSUE THREAD

**Issue by brettfo** [rust-lang/cargo#3093]
REPRO
=====

0 - Have an older (not sure how old?) GitHub organization.
1 - Add a GitHub org team as a crate owner with `cargo owner --add github:<org>:owners` where `<org>` is the name of an organization.
2 - Click on the new owner's link on the crate's listing (e.g., `https://github.com/orgs/<org>/teams/owners`).
3 - Notice that GitHub says that the `owners` team is now the `owner` role.  Follow the suggestion by GitHub and rename the `owners` team to something non-conflicting like `Maintainers`.
4 - Attempt to add this team as a crate's owner with `cargo owner --add github:<org>:Maintainers`.

RESULT
======

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Owner adding ["github:<org>:Maintainers"] to crate <crate>
error: failed to add owners to crate <crate>: api errors: could not find the github team <org>/Maintainers
```

PROLOG
======

GitHub 404's when navigating to the `/orgs/<org>/teams/owners` page, but works on `/<org>/teams/Maintainers` (as expected).
Cargo still allows removal/re-adding of the `/orgs/<org>/teams/owners` team, even though it's gone (not expected).

DETAILS
=======
Platform = Windows 10, with 1.11 GNU x64 installer.
`cargo --version` == `cargo 0.12.0-nightly (6b98d1f 2016-07-04)`
`rustc --version` == `rustc 1.11.0 (9b21dcd6a 2016-08-15)`
crate = [dxf](https://crates.io/crates/dxf)
team = [IxMilia/Maintainers](https://github.com/orgs/IxMilia/teams/maintainers)

It should also be noted that the name of the organization starts with an upper-case letter, but running the `cargo owner --add` command with a lower-case organization results in a different error:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Owner adding ["github:IxMilia:maintainers"] to crate dxf
error: failed to add owners to crate dxf: failed to get a 200 OK response, got 502
headers:
    HTTP/1.1 100 Continue



    HTTP/1.1 502 Bad Gateway

    Connection: keep-alive

    Server: nginx

    Date: Wed, 14 Sep 2016 21:01:31 GMT

    Content-Type: text/html

    Content-Length: 166

    Via: 1.1 vegur



body:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by alexcrichton** [comment]
Interesting! I think that this may actually have more to do with code on crates.io, perhaps the bug could be filed over there?

The API errors at least are coming from crates.io, and crates.io is the one communicating with GitHub about all the team information.

**Comment by brettfo** [comment]
Thanks for the pointer!  Ported over to rust-lang/crates.io#446.
