### ISSUE TITLE
 Please add documentation for the different crate types

### ISSUE THREAD

**Issue by JinShil** [rust-lang/cargo#3097]
Moved from https://github.com/rust-lang/rust/issues/36522

Please add documentation comparing and contrasting the different crate types:  rlib, dylib, cdylib, etc...  Thanks!

**Comment by JinShil** [comment]
Found this information in the Rust Reference here:  https://doc.rust-lang.org/reference.html#linkage

Closing.

**Comment by MatthieuBizien** [comment]
Broken link ; new link is https://doc.rust-lang.org/reference/linkage.html
