### ISSUE TITLE
[replace] silently ignored if crate is part of a workspace

### ISSUE THREAD

**Issue by nathanaeljones** [rust-lang/cargo#3099]
Using `cargo 0.13.0-nightly (b78beb1 2016-09-01)`
Also reproduced with `cargo 0.13.0-nightly (9399229 2016-09-14)`
Repro: 

```
git clone https://github.com/nathanaeljones/cargo_replace_test
cd cargo_replace_test/any_crate
cargo build
(note pkg-config pulled from crates.io)
cd ..
git checkout no_workspace
cargo build
(note pkg-config pulled from replacement location)
```

**Comment by SergioBenitez** [comment]
Just ran into the issue (I believe) you're describing. To be clear, Cargo ignores the `[replace]` section in non-workspace root crates without emitting a warning. However, not emitting a warning will surely lead to confusion (as it did for me). Thus, Cargo should emit a warning when it ignores `[replace]`. What's more, this should likely be an error.

**Comment by nathanaeljones** [comment]
What do you mean by root crate? Are there any circumstances in which Cargo honors `[replace]` if workspaces are in use?

**Comment by SergioBenitez** [comment]
Yes. Crate honors `[replace]` if the section is placed in the root crate or virtual root crate.

**Comment by nathanaeljones** [comment]
I cannot reproduce success in that scenario.

**Comment by SergioBenitez** [comment]
I'm on IRC as @Sergio. Ping me and let's see if we can find the differences.

**Comment by nathanaeljones** [comment]
So, I can now reproduce that success. I have a failed build against a August nightly of cargo where it fails, and some corner cases where the lockfile cache doesn't get updated, but I think I have a path to success for my *actual* project as well as the repro above. 

Raising an error would be super helpful, though.

**Comment by alexcrichton** [comment]
@nathanaeljones ah ok, looks like things got sorted out with the right build here? Could you clarify though what error should be raised?

**Comment by SergioBenitez** [comment]
@alexcrichton No, the issue still exists. See my original comment:

> Just ran into the issue (I believe) you're describing. To be clear, Cargo ignores the [replace] section in workspace non-root crates without emitting a warning. However, not emitting a warning will surely lead to confusion (as it did for me). Thus, Cargo should emit a warning when it ignores [replace]or, better yet, fail with an error.

**Comment by alexcrichton** [comment]
Oh right, indeed! Sounds good to me.

**Comment by sanmai-NL** [comment]
So this issue can be closed? @alexcrichton

**Comment by alexcrichton** [comment]
I believe so, yes!
