### ISSUE TITLE
`cargo build` fails when dependencies for another platform cannot be found

### ISSUE THREAD

**Issue by oconnor0** [rust-lang/cargo#3106]
I have a `Cargo.toml` like the following:

```toml
[package]
name = "textbox"
version = "0.0.1"
authors = ["Matthew O'Connor <thegreendragon@gmail.com>"]

[target.'cfg(windows)'.dependencies]
winapi = { path = "../../winapi-rs" }

[target.'cfg(unix)'.dependencies]
```

When I run `cargo build` on Linux, I get the following error:

```
error: Unable to update file:///home/moconnor/Source/winapi-rs

Caused by:
  failed to read `/home/moconnor/Source/winapi-rs/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Failing to compile on Linux when a dependency for Windows cannot be found seems like a bug.

**Comment by alexcrichton** [comment]
Yes to succeed Cargo needs to be able to find all dependencies for all platforms (to generate one `Cargo.lock`). So in that sense this is intended behavior.

Thanks for the report though!
