### ISSUE TITLE
"cargo metadata" should contain license info

### ISSUE THREAD

**Issue by jsgf** [rust-lang/cargo#3108]
The `cargo metadata` should include info from the `license` and `license_file` fields in `Cargo.toml`. This is useful for integration into other build systems which keep track of license details.

Ideally `license_file` should be a full relative path to the file, but maybe its sufficient if its relative to `manifest_path`.

**Comment by alexcrichton** [comment]
Indeed! Should be an easy bug to tackle I think, just a few modifications to [this block](https://github.com/rust-lang/cargo/blob/dd912506f23f7768b398397ddd43d6733f85cbb3/src/cargo/core/package.rs#L27-L55).

**Comment by srinivasreddy** [comment]
Pls close this @alexcrichton

**Comment by alexcrichton** [comment]
Indeed!
