### ISSUE TITLE
how about rank the crates using dependencies as reference?

### ISSUE THREAD

**Issue by robertnie** [rust-lang/cargo#3113]
Hi all,

I think it is inaccurate to rank a crate by using download times, while the "Dependencies" list is much more accurate. If a crate is referred more times, it should be more stable, widely accepted. Combined with the factor of download times, the best/popular crates can be put at the top place, which will be valuable to developers.

Thanks,
Robert

**Comment by alexcrichton** [comment]
Thanks for the report! I think this may be more appropriate in the rust-lang/crates.io repo, however, so could you reopen over there?
