### ISSUE TITLE
Integration with Dlang (as backend language)

### ISSUE THREAD

**Issue by 9il** [rust-lang/cargo#3120]
The Idea is to use [Mir](https://github.com/libmir/mir/) (not to be confused with MIR) as a backend for very low level algorithms that is required in Rust numerical libraries, such as https://github.com/bluss/rust-ndarray (ping @bluss).

Mir is an LLVM-Accelerated Generic Numerical Library for Science and Machine Learning. See also the first [Mir's benchmarks](http://blog.mir.dlang.io/glas/benchmark/openblas/2016/09/23/glas-gemm-benchmark.html).

D has [DUB package manager](http://code.dlang.org/), it is also packed with recent LDC (LLVM D Compiler) `v1.1.0-beta2`. Mir does not need other compilers, but LDC.

I can add required changes to the D infrastructure, but I have no idea what is required

**Comment by steveklabnik** [comment]
What specifically is the request here? I'm not 100% sure what you're asking. It's for Cargo to be able to build D code?

**Comment by 9il** [comment]
Yes, something like LDC cargo package with binaries and its integration to cargo (build D project, rebuild, fetch new minor release and etc). What is required to do it?

**Comment by 9il** [comment]
Some initial feedback would be helpful too.

What Object format is used for 32/64bit windows ? COFF?

**Comment by alexcrichton** [comment]
Thanks for the report @9il! I wonder if this use case could perhaps be subsumed by build scripts in Cargo? Something like the gcc-rs crates for D perhaps?

**Comment by 9il** [comment]
@alexcrichton It may be part of solution. Mir requires addition information about the compilation target. This information should be passed to the dub configuration file. But first, the script should retrieve this information from Cargo

**Comment by 9il** [comment]
For example `-mattr=avx2` will allow Mir to use AVX instructions. This should be configurable from cargo

**Comment by alexcrichton** [comment]
With https://github.com/rust-lang/rfcs/pull/1721 learning about things like AVX would work as `--print cfg` would print out `target-feature=avx2`

**Comment by carols10cents** [comment]
It sounds like https://github.com/rust-lang/rfcs/pull/1721 enables this, so I'm going to close this. Please reopen if I'm mistaken! Thank you!
