### ISSUE TITLE
`cargo build` with `[replace]` with a `*` version number fails

### ISSUE THREAD

**Issue by oconnor0** [rust-lang/cargo#3129]
Using `[replace]` without a specific version number but a `*` fails with a `Parse error`. For example running `cargo build` when the following is in the `Cargo.toml`:

```
[dependencies]
winapi = "*"
[replace]
"winapi:*" = { git = "https://github.com/oconnor0/winapi-rs.git", rev = "textbox" }
```

Gives:

```
error: failed to parse manifest at `/home/moconnor/Source/build-your-own-editor/textbox/Cargo.toml`

Caused by:
  Parse error
```

If this is intended behavior, an improved error message would be greatly appreciated.

**Comment by alexcrichton** [comment]
Oh dear, that's a terrible error! 

But yes the part after the `:` needs to be a valid semver, so this error is because `*` isn't a valid semver (e.g. `0.1.0`). Definitely need a better error message here.

**Comment by alexcrichton** [comment]
This should also be a pretty easy bug to tackle for anyone interested, I think it's just a `chain_error` in `toml.rs` that needs to happen somewhere!

**Comment by jhbabon** [comment]
@alexcrichton I can check this out if nobody else is on it.

**Comment by alexcrichton** [comment]
@jhbabon all yours! Let me know if you need any help

**Comment by jhbabon** [comment]
@alexcrichton cool, I'll let you know if I need anything.
