### ISSUE TITLE
Unable to update registry - unknown error occurred

### ISSUE THREAD

**Issue by aspiers** [rust-lang/cargo#3131]
How can I debug this?

```
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  [0/-1] an unknown error occurred
$ cargo -V
cargo 0.11.0
$ rustc -V
rustc 1.10.0-dev
```

I get the same thing trying to install `git-series`:

```
$ cargo install --verbose --root ~/.local git-series
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: [0/-1] an unknown error occurred
```

See https://github.com/git-series/git-series/issues/25 for more details.

**Comment by alexcrichton** [comment]
Hm this is likely coming from git2-rs where apparently it thinks an operation failed but libgit2 disagrees. Can you reproduce this reliably locally? Do you have perhaps any filesystem weirdness set up around CARGO_HOME (`$HOME/.cargo`)?

**Comment by aspiers** [comment]
I can reproduce this 100% of the time locally.  No I haven't set `CARGO_HOME` or anything else related - it's the first time I ever tried Cargo so it's a totally vanilla setup and I didn't even know about that environment variable!  I do have a complex `~/.gitconfig`, so after reading about Cargo issues triggered by use of `insteadOf`, I tried again after renaming that file, but it didn't help.

I have no experience with rust either, but I am an experienced developer who is keen to help debug this, if you can just give me some pointers of where to look :)  I tried `--verbose` as originally suggested by `cargo install` but it didn't make any difference.  Thanks!

**Comment by alexcrichton** [comment]
Ah well if you're willing to help debug, let's keep digging!

How'd you install Cargo? I wonder if maybe it's using a different libgit2 version that's out of sync?

**Comment by alexcrichton** [comment]
Also if you can get a debug build of Cargo, you could try breaking on [this line](https://github.com/alexcrichton/git2-rs/blob/9faefc218153ea2498d042b3a34a3584557a6b31/src/call.rs#L49). That'll give a stack trace as to what called the operation that purportedly failed.

**Comment by aspiers** [comment]
Thanks for the reply!  I installed Cargo from [the Open Build Service](https://software.opensuse.org/package/cargo).

Well, this is incredibly weird.  I just re-ran this for the hell of it:

    $ cargo install --verbose --root ~/.local git-series

and now I'm getting a verbose build with a totally different failure! #wtf 

```
[...]
   Compiling tempdir v0.3.5
     Running `rustc .cargo/registry/src/github.com-1ecc6299db9ec823/tempdir-0.3.5/src/lib.rs --crate-name tempdir --crate-type lib -C opt-level=3 -C metadata=c5a9975021308003 -C extra-filename=-c5a9975021308003 --out-dir /tmp/cargo-install.x1BdtE9KCHF8/release/deps --emit=dep-info,link -L dependency=/tmp/cargo-install.x1BdtE9KCHF8/release/deps -L dependency=/tmp/cargo-install.x1BdtE9KCHF8/release/deps --extern rand=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/librand-49a08859d086fffe.rlib --cap-lints allow`
.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.13.0/src/errors.rs:857:35: 857:46 error: no method named `description` found for type `std::fmt::Error` in the current scope
.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.13.0/src/errors.rs:857         Error::with_description(e.description(), ErrorKind::Format)
                                                                                                                ^~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: failed to compile `git-series v0.8.10`, intermediate artifacts can be found at `/tmp/cargo-install.x1BdtE9KCHF8`

Caused by:
  Could not compile `clap`.

Caused by:
  Process didn't exit successfully: `rustc .cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.13.0/src/lib.rs --crate-name clap --crate-type lib -C opt-level=3 --cfg feature="term_size" --cfg feature="strsim" --cfg feature="wrap_help" --cfg feature="ansi_term" --cfg feature="libc" --cfg feature="default" --cfg feature="color" --cfg feature="suggestions" -C metadata=315a0a334d3f6b4c -C extra-filename=-315a0a334d3f6b4c --out-dir /tmp/cargo-install.x1BdtE9KCHF8/release/deps --emit=dep-info,link -L dependency=/tmp/cargo-install.x1BdtE9KCHF8/release/deps -L dependency=/tmp/cargo-install.x1BdtE9KCHF8/release/deps --extern vec_map=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/libvec_map-d843695eff67d492.rlib --extern unicode_width=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/libunicode_width-bcfd50e6d35d16e0.rlib --extern term_size=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/libterm_size-9fd23557733de795.rlib --extern unicode_segmentation=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/libunicode_segmentation-e3fd0169850011a0.rlib --extern strsim=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/libstrsim-b42a694875d9a3b0.rlib --extern ansi_term=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/libansi_term-aa5dcc2affa8dc75.rlib --extern bitflags=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/libbitflags-0e272044714c8076.rlib --extern libc=/tmp/cargo-install.x1BdtE9KCHF8/release/deps/liblibc-1417726cb94dbc83.rlib --cap-lints allow` (exit code: 101)
```

Apparently this is an incompatibility with newer clap with older rust: kbknapp/clap-rs#663
I have rustc 1.10.0-dev and apparently I need 1.11 to fix this, which unfortunately will require updating some distribution packages ...

But I have no idea why the original error magically vanished!

**Comment by alexcrichton** [comment]
Interesting! It sounds like you're installing from a "non standard" location (in these that it's not literally our nightlies), so maybe the build process there was different and maybe cargo wasn't compiled quite right? I guess there's not much we can do until it can get reproduced again :(

**Comment by aspiers** [comment]
The details of the build process are all here:

https://build.opensuse.org/package/show/devel:languages:rust/rust

In particular, you can see in [the `.spec` file](https://build.opensuse.org/package/view_file/devel:languages:rust/rust/rust.spec?expand=1) the [URL used to obtain the source tarball](https://static.rust-lang.org/dist/rustc-1.10.0-src.tar.gz) and exactly how it was built.  The [build log](https://build.opensuse.org/package/live_build_log/devel:languages:rust/rust/openSUSE_Leap_42.1/x86_64) is also just one click away from that page.

I have literally zero experience in building rust, but that `.spec` file looks very standard to me.  I wonder is it possible that the original problem was caused by some temporary internet glitch?

**Comment by alexcrichton** [comment]
Hm unfortunately I can't quite deduce how this may have arisen from that, so maybe it's unrelated! I guess ping again if you get a reproduction?

**Comment by aspiers** [comment]
Yeah, I certainly will!  I guess we can close this issue and reopen if necessary?

**Comment by alexcrichton** [comment]
Ok, sounds good to me!
