### ISSUE TITLE
Fails to document rustc_macro

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#3132]
Reported by @neon64 in https://github.com/serde-rs/serde/issues/567: `cargo doc` cannot document any rustc_macro crate or any crate depending on a rustc_macro crate.

https://docs.rs/crate/serde_derive/0.8.10/builds/31363

```
error: the `#[rustc_macro_derive]` attribute is only usable with crates of the `rustc-macro` crate type
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.10/src/lib.rs:9:3
  |
9 | #[rustc_macro_derive(Serialize)]
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `#[rustc_macro_derive]` attribute is only usable with crates of the `rustc-macro` crate type
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.10/src/lib.rs:18:3
   |
18 | #[rustc_macro_derive(Deserialize)]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Compilation failed, aborting rustdoc
```

@alexcrichton I don't know Cargo well enough to tell whether this is a cargo issue or a rustc issue or a rustdoc issue so sorry if this is filed in the wrong place.

**Comment by alexcrichton** [comment]
ugg

This is a rustdoc bug actually, but I'll re-file over at rust-lang/rust

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/rust/issues/36820
