### ISSUE TITLE
`cargo build` and `cargo install -f` write `Cargo.lock` differently

### ISSUE THREAD

**Issue by oconnor0** [rust-lang/cargo#3133]
Given the following repo: https://github.com/oconnor0/build-your-own-editor/tree/24586c991a7faa513723595164df544e7c81ae73

When I run `cargo build` from the root, the `Cargo.lock` is written out one way.
When I run `cargo install -f` from the root, the `Cargo.lock` is written in a different way.

They are consistent - so that if I run `cargo build`, git will show no changed. If I then run `cargo install -f`, I see changes in `Cargo.lock`. Running `cargo build` again shows no changes.

There are only two `Cargo.toml` in the repository:

At the root:
```
[package]
name = "build-your-own-editor"
version = "0.0.1"
authors = ["Matthew O'Connor <thegreendragon@gmail.com>"]

[dependencies]
textbox = { path = "textbox" }

[workspace]
members = [".", "textbox"]

[replace]
"winapi:0.2.8" = { git = "https://github.com/oconnor0/winapi-rs.git", rev = "textbox" }
"wio:0.1.2" = { git = "https://github.com/oconnor0/wio-rs.git", rev = "textbox" }
```

Inside the `textbox` directory:
```
[package]
name = "textbox"
version = "0.0.1"
authors = ["Matthew O'Connor <thegreendragon@gmail.com>"]
workspace = ".."

[dependencies]
bitflags = "*"
bit-set = "*"
num-traits = "*"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
wio = "0.1.2"
kernel32-sys = "*"

[target.'cfg(unix)'.dependencies]
termbox-sys = "*"
```

**Comment by alexcrichton** [comment]
Interesting! Could you gist the diff between the two lock files?

**Comment by oconnor0** [comment]
https://gist.github.com/oconnor0/c64d3a95fb5784fb2f485e46fec01df1

**Comment by alexcrichton** [comment]
Thanks! Confirms my suspicions and fixed in https://github.com/rust-lang/cargo/pull/3146
