### ISSUE TITLE
Add possibility to exclude binaries from being built on specific platforms

### ISSUE THREAD

**Issue by philippkeller** [rust-lang/cargo#3138]
I have `src/bin/linux-only.rs` which does some things which work on Linux only (e.g. libc bindings which only exist on Linux). I want to exclude that file from being built on OS X.

Could you add a way to exclude those, e.g. 

```
[package(target_os=macos)]
exclude = ["src/bin/linux-only.rs"]
```

or (and that's probably the better way as it doesn't need new syntax): just remove the error `error: main function not found` when there's a `#![cfg(target_os = "linux")]` at the top of `src/bin/linux-only.rs`

Disclaimer: I'm fairly new to rust so maybe I'm doing something wrong. I read through the Cargo.toml docs and didn't find a way to make this work, I also did not get a satisfying answer on [this SO post](http://stackoverflow.com/questions/39733252).

**Comment by alexcrichton** [comment]
Thanks for the report! Yeah in Cargo right now this isn't too easy, but you can work around this with `#[cfg]` where on the non-relevant platforms it's just an empty `fn main() {}` with maybe a `println!` diagnostic explaining why.

**Comment by philippkeller** [comment]
@alexcrichton that's what I'm currently doing. But it needs a `#[cfg]` attribute above every block (including `use`, structs, c bindings, etc. So I end up with 10-20 of these attributes which is cluttering the code. Is there a better way to do that?

**Comment by philippkeller** [comment]
found a workoround via [a `build.sh` script](https://gist.github.com/philippkeller/deda2570ed6e7228f1750194fd4c501f) that generates separate `Cargo.toml` files for linux and osx, which leaves out rs files with the `#![cfg(target_os = "...")]` which doesn't match the current architecture.

**Comment by weihanglo** [comment]
Hey there. I am going to close this since more discussions happens in #9208 for the same issue. Thank you!
