### ISSUE TITLE
travis-cargo currently cannot upload / generate code coverage information for documentation tests

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#3140]
There should be a way in cargo for travis-cargo to be able to run the documentation tests with code-coverage generation, so that it can upload correct code coverage information to coveralls.

The travis-cargo issue is here: https://github.com/huonw/travis-cargo/issues/63

**Comment by alexcrichton** [comment]
Thanks for the report! Mind reopening this on rust-lang/rust? I think this is specifically a bug for `rustdoc --test` perhaps?

**Comment by carols10cents** [comment]
Closing this issue in favor of https://github.com/rust-lang/rust/issues/36956.
