### ISSUE TITLE
Feature request: Ability to [replace] a path dependency with another path dependency.

### ISSUE THREAD

**Issue by jessstrap** [rust-lang/cargo#3148]
Related to #2996.

**Comment by alexcrichton** [comment]
In theory this is possible, if you run `cargo pkgid foo` to learn the pkgid of a crate, and then use that in the `[replace]` key, does it work?

Although that may involve encoding an absolute path into your `Cargo.toml` which should be avoided...

**Comment by jessstrap** [comment]
I haven't tried using the pkgid. I've since switched to a setup based solely on features and optional dependencies (as seen [here](https://github.com/jessstrap/servotk/tree/3fcca8c6b318ea1fa931c58a2a1a2f4b668ad5c6/components/script_engine_pluggable)). It works, but it is a bit kludgey.

**Comment by larsbergstrom** [comment]
cc @larsbergstrom @nox

**Comment by nox** [comment]
I can confirm that using `pkgid` works, we can close this ticket.
