### ISSUE TITLE
per target rustflags

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#3153]
I have this use case where I'm developing a crate for an embedded, no_std, cross target and need to
use additional linker flags to get working binaries (or to even get the binary to link at all) and
I'm passing those to the linker using build.rustflags in .cargo/config.

The issue is that I also want to `cargo test` some parts of the crate on the host (because `cargo
test` doesn't work for the cross target -- there's no `test` crate over there (or threads for that
matter)) but I can't because the linker flags that *I only want to use for the cross target* also get
picked up by native compilation wreaking havoc.

Having per target rustflags will fix this problem, then I can set:

``` toml
[target.thumbv7em-none-eabihf]
rustflags = [
# linker flags go here
]
```

in my .cargo/config to have rustflags for the cross target but that don't get used in the host builds.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by japaric** [comment]
I'm going to take a stab at this and I'm wondering what would happen if both build.rustflags and target.$T.rustflags are specified in the .cargo/config. I'd expect the target.$T.rustflags to take precedence. Does that sound right?
