### ISSUE TITLE
Feature request / discussion: add some discussion on crates.io to leave feedback and compare functionality (to avoid Pythonic mess)

### ISSUE THREAD

**Issue by d33tah** [rust-lang/cargo#3155]
I love the concept of crates.io! Having learned from Python though, may I suggest that you add some way to leave feedback for the projects? My reasoning is that unless crates.io becomes moderated, sooner or later there will be multiple crates for the same problems, leading to confusion about what each project is good at. Alternatively, crates.io could have the concept of "features" comparison, like shown here:

https://djangopackages.org/grids/g/admin-styling/

Note that the later the feature gets added, the less packages will support it - it's better to add an imperfect solution to this problem now than none at all and get back with a Pythonic mess.

**Comment by steveklabnik** [comment]
Can you move this to https://github.com/rust-lang/crates.io, thanks!
