### ISSUE TITLE
Default .gitignore will ignore files named "target" in any subdirectory

### ISSUE THREAD

**Issue by casey** [rust-lang/cargo#3158]
`cargo --init foo` will produce a `.gitignore` that contains the line `target`. A non-slash prefixed line of a `.gitignore` will ignore matching files in any subdirectory of a project.

Since `target` is a pretty common word, I would suggest prefixing it with a slash, since a user might have a file called `target` somewhere else in their project.

**Comment by casey** [comment]
I think I would also suggest prefixing `/Cargo.toml` and `/Cargo.lock` with a slash, since sub-crates created with `cargo --init` will still be covered by their own .gitignores.

**Comment by alexcrichton** [comment]
Thanks for the report! This is intentional on behalf of Cargo so the generated gitignore will ignore any sub-crates' Cargo.lock or target directory. As you've seen though this won't work for *all* projects, however, but for those projects it's just a short edit away to success.

**Comment by casey** [comment]
I think I would still argue for the other way around.

If you generate a crate with `cargo init --lib`, and then inside of it you have a crate generated with `cargo init --bin`, your `Cargo.lock` will be ignored by the outer git ignore, which wouldn't be the case if it were `/Cargo.lock`. So bin inside lib nesting is currently broken.

Also, when a file is ignored when you don't want it to be it's somewhat mysterious, it just doesn't show up in a `git status`. You might even `git commit -a` and not notice that it isn't getting committed. The opposite is much less confusing, since you will actually see the file in a `git status` and know that it isn't being ignored.

**Comment by alexcrichton** [comment]
Yeah the default gitignore isn't intended to be perfect, it basically can't ever be. But that's why it's just a template so you can still edit it after-the-fact.

**Comment by casey** [comment]
I gather that cargo init includes a check for a `.git` or `.hg` folder, and uses that to decide whether or not to call `git init` or `hg init`, and also whether or not to create a `.gitignore`.

What if it always created a new `.gitignore` in new sub-crates, even if it found a `.git` or `.hg`, and all `.gitignore`s used slash prefixed paths? This would ensure that only the right files are ignored. I think that accidentally ignoring a file named `target` is less of an issue, but that ignoring a `Cargo.lock` with bin-in-lib is a bit worse, since when to check in `Cargo.lock` is a bit subtle to begin with.

**Comment by alexcrichton** [comment]
Again though, this is purely just intended to be a very simple template that's suitable for most projects, not necessarily a complicated template that's suitable for just a few more. As simply templates, they can always be tweaked once generated do do something like generating a new `.gitignore` per directory or such (or specifically un-ignoring `target` directories)

**Comment by casey** [comment]
Okay, I guess the improvements I'm suggesting are out of scope, so I'll go ahead and close this issue.
