### ISSUE TITLE
Default features of dependencies get pulled in for no reason

### ISSUE THREAD

**Issue by nox** [rust-lang/cargo#3164]
When building `webrender_traits` with https://github.com/servo/webrender/pull/430, even running `cargo build --no-default-features --features serde_derive` ends up building `serde_codegen` with its feature `with-syntex`. This should not happen.

**Comment by nox** [comment]
Cc @alexcrichton

**Comment by alexcrichton** [comment]
Hm what version of Cargo are you using actually? I just used `cargo 0.13.0-nightly (cbe47ed 2016-09-29)` locally and got:

```
features: {
  offscreen_gl_context v0.4.4: {"serde", "serde_serialization", "default"}
  unicode-xid v0.0.3: {"default"}
  serde v0.8.11: {"std", "default"}
  app_units v0.3.0: {"default"}
  byteorder v0.5.3: {"std", "default"}
  uuid v0.3.1: {"rand", "v4"}
  bincode v0.6.0: {"serde", "rustc-serialize", "default"}
  libc v0.2.16: {"use_std", "default"}
  serde_codegen v0.8.11: {"with-syn"}
  webrender_traits v0.6.0 (file:///home/alex/code/lol): {"serde_derive"}
  x11 v2.8.0: {"xlib"}
  log v0.3.6: {"use_std", "default"}
  syn v0.8.7: {"quote", "unicode-xid", "aster", "printing", "default", "visit", "parsing"}
}
```

which looks correct? Maybe we fixed this bug? (not that I remember it)

**Comment by nox** [comment]
@alexcrichton 

```
cargo 0.13.0-nightly (ebcf0a8 2016-10-03)
```

And in Cargo.lock:

```
[[package]]
name = "serde_codegen"
version = "0.8.11"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "quote 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_codegen_internals 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "syn 0.8.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "syntex 0.44.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "syntex_syntax 0.44.0 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**Comment by alexcrichton** [comment]
Hm it looks like there's something else in play here because it works if I use the exact `Cargo.toml` from webrender_traits. What `Cargo.toml` are you building from again to reproduce?

**Comment by nox** [comment]
The one in 94437c4bbbee843e172dfc306b113a13a8a840c8, which is the tip of the PR I linked.

**Comment by nox** [comment]
I wonder if that is related to https://github.com/rust-lang/cargo/issues/1197, it's certainly similar.

**Comment by alexcrichton** [comment]
If the "bug" is that syntex_syntax is mentioned in Cargo.lock then that's not a bug. There exists a mode to build `webrender_traits` which builds the `syntex_syntax` crate, so it must be in the lock file.

**Comment by nox** [comment]
I see! Now that makes sense. Closing this then!
