### ISSUE TITLE
Cannot run benchmarks with `panic = "abort"`

### ISSUE THREAD

**Issue by AaronFriel** [rust-lang/cargo#3166]
The following error is obtained when running `cargo bench`, with the a `panic = "abort"` option in `cargo.toml`:

```
error: the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`
```

The `cargo.toml` needs to set the panic behavior in `[profile.bench]`, e.g.:

`cargo.toml`:

```
[package]
name = "foobar"
version = "0.1.0"
authors = ["Aaron Friel <mayreply@aaronfriel.com>"]

[dependencies]
clap="^2.13.0"

[profile.bench]
panic = "abort"
```

**Comment by alexcrichton** [comment]
Dug a bit more into this today. The dependency actually isn't needed here to trigger the bug, and if you configure `profile.test` with abort then `cargo test` is also broken.

The problem here is that libtest, Rust's testing framework, requires the unwind panic mode and is incompatible with `panic = "abort"`. If you configure `profile.dev` to have `panic = "abort"`, it actually compiles all dependencies with `-Cpanic=unwind` when you execute `cargo test` to satisfy this constraint.

The "fix" here would be to ignore `panic = "abort"` in the bench and test profiles.

**Comment by AaronFriel** [comment]
The patch in #3175 is confusing to me. Is there any way to run tests or benchmarks with `panic="abort"`?

**Comment by alexcrichton** [comment]
Unfortunately no because they all link to libtest which is compiled with `panic=unwind` :(

**Comment by AaronFriel** [comment]
I see, and because `libtest` depends on panics to observe `assert!` failures, that's the blocking issue?

Is there any work on making an alternative `libtest` based on `Result<>`, with an, e.g.: `try_assert!` that works like `try!`?

**Comment by alexcrichton** [comment]
Perhaps yeah, but that's more of a rust-lang/rust issue than a Cargo one.

**Comment by AaronFriel** [comment]
Interesting. If I were to make an alternative `libtest`, is there a way to specify that in `cargo.toml`? Or are tests (and their return types) part of rust-lang/rust?

**Comment by alexcrichton** [comment]
Yeah you can specify `harness = false` in which case Cargo will just compile the test as an executable, and then you can link to whatever

**Comment by sanmai-NL** [comment]
@alexcrichton:
Thanks for fixing the issue in 4a73741 and explaining the test harness design in this thread. I think the issue hasn't been fully resolved though. I had a problem similar to the reporter and I had to find out what was happening from this thread. Can the limitation on panic strategy please be shown as a warning? That would be way less confusing than Cargo silently ignoring the `panic` profile field.

**Comment by alexcrichton** [comment]
@sanmai-NL seems reasonable to me! Want to open an issue for that?

**Comment by sanmai-NL** [comment]
My first reaction to your suggestion is that it would be too much overhead. I can try to make a PR for it straight away. If it doesn't cost you too much time, perhaps you can give some pointers on how to generate an appropriate warning in Cargo, e.g. similar to the current ‘Unknown field’ warning.

**Comment by alexcrichton** [comment]
Sure yeah sounds good! The best way to generate warnings right now is the [`add_warning`](https://github.com/rust-lang/cargo/blob/62acd6e3298a488d411f73a832a2ead75f23fe01/src/cargo/util/toml.rs#L815-L816) method (called throughout that file). I suspect that this logic would go somewhere in `toml.rs`.

If that doesn't end up working out though, just let me know
