### ISSUE TITLE
Provide a command to check if build is up-to-date (without building)

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/cargo#3180]
Cargo has to do this internally, but the functionality is not exposed.
`ubsan` on IRC agreed that it should be.

This would be handy for IDE integration.

**Comment by dwijnand** [comment]
Is there still a need for this?  There is IDE integration already in Rust.  Does that mean this isn't necessary?

**Comment by dralley** [comment]
Copying my comment from the duplicate issue

> I don't think this would need a new subcommand. Just add [cached] (or something) to the output string when nothing needed to be rebuilt.

e.g. instead of the line `Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs`

it could say

`Using cached [unoptimized + debuginfo] target(s)` or something along those lines

**Comment by epage** [comment]
Looking at this, it sounds like a duplicate of #1989.  Closing in favor of that.  If there is a distinction I missed, let us know!
