### ISSUE TITLE
bump hamcrest to 0.1.1 - license clarification

### ISSUE THREAD

**Issue by semarie** [rust-lang/cargo#3181]
Hi,

I wonder if hamcrest could easily be bumped to 0.1.1 ?

Currently, cargo use `hamcrest-0.1.0` (dev-dependency). This particular version has some licenses issues:
  - cartes.io reports it as MIT
  - but published 0.1.0 crate doesn't contains any license information

Some months ago, hamcrest has officially switched to Apache2/MIT (see https://github.com/carllerche/hamcrest-rust/issues/22), and some days ago a 0.1.1 has been published with updated license (see https://github.com/carllerche/hamcrest-rust/issues/40).

Updating to 0.1.1 would permit a more easy distribution of prerequistes for cargo.

As example, the current status for OpenBSD is the following (from http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/devel/cargo/Makefile?rev=1.4&content-type=text/x-cvsweb-markup): 

```
# cargo is dual licensed MIT/Apache-2.0
# third-parties (detail below):
#  - MIT
#  - Unlicense/MIT
#  - MIT/Apache-2.0
#  - MPL-2.0
#  - one with no indication of licence (hamcrest)
#
# hamcrest is used only for the testsuite, and isn't builded with cargo.
# so the package doesn't contain it.
#
PERMIT_PACKAGE_CDROM = Yes
PERMIT_DISTFILES_FTP = No as hamcrest has no license information
```

we are unable to distribute source archives for cargo due to hamcrest dependency (cargo and dependencies are considere as a whole). Hopefully, binary-package is possible as hamcrest isn't builded with cargo (only used for testing).

Having cargo to depends to properly licensied dependencies would simplify the whole.

Thanks.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/cargo/pull/3174 is updating some dependencies, but not this one. It shouldn't be difficult.

**Comment by alexcrichton** [comment]
Sure! Want to send a PR to update?
