### ISSUE TITLE
all links disabled in documentation

### ISSUE THREAD

**Issue by cainlevy** [rust-lang/cargo#3182]
All links on http://doc.crates.io/index.html are currently disabled by the `$(document).on('click')` handler in `all.js`.

**Comment by cainlevy** [comment]
Correction: all links not in the pulldown menu are disabled.

**Comment by alexcrichton** [comment]
cc @rjgoldsborough related to https://github.com/rust-lang/cargo/pull/3168 maybe?

**Comment by rjgoldsborough** [comment]
Yup, it was :(. Sorry about that. I thought I tested it better before pushing but I guess not. I most definitely clicked around the site and everything seems to be in order again.

**Comment by rjgoldsborough** [comment]
And I'm still not sure #2865 is a bug so we could always just revert #3168 change too.

**Comment by cainlevy** [comment]
:confetti_ball: thanks!
