### ISSUE TITLE
Moving auto from Buildbot to Travis+Appveyor

### ISSUE THREAD

**Issue by edunham** [rust-lang/cargo#3186]
Buildbot will remain for nightlies at the moment, but we can get the rest off of it. 
- [X] add GNU triples to https://github.com/rust-lang/cargo/blob/master/appveyor.yml  -- https://github.com/rust-lang/cargo/pull/3187
- [ ] Fill out Travis matrix to include all of 64 & 32-bit Mac & Linux https://github.com/rust-lang/cargo/pull/3190/files
- [ ] Port cross matrix from https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg#L223 to Travis matrix also https://github.com/rust-lang/cargo/pull/3190/files
- [ ] Make sure Travis & Appveyor are working correctly
- [ ] Switch Homu to using Travis+Appveyor insead of Buildbot
- [ ] Verify that's all working
- [ ] Remove auto stuff from Buildbot configs

**Comment by alexcrichton** [comment]
Travis is landed and publishing builds now, so closing.
