### ISSUE TITLE
Build failed at openssl_sys

### ISSUE THREAD

**Issue by salmonix** [rust-lang/cargo#3188]
OS: Ubuntu 16.04.1 LTS
Rustc: rustc 1.7.0
Installed: libssh2-1 libssh2-1-dev libssl-dev openssl

[See log](https://github.com/rust-lang/cargo/files/521870/make.txt).
Bests,
s

**Comment by alexcrichton** [comment]
Interesting! Could you try also gisting the output of `make VERBOSE=1`?

**Comment by salmonix** [comment]
[Here it is.](https://github.com/rust-lang/cargo/files/523712/make.txt)
Bests,
s

**Comment by alexcrichton** [comment]
Hm was that accidentally the same as before?

**Comment by alexcrichton** [comment]
Oh so actually I think that the rustc version may be too old, could you try updating and compiling again?

**Comment by salmonix** [comment]
After installing Rust with RUSTUP_PREFIX= $HOME/.local [rustup.sh](https://doc.rust-lang.org/1.0.0/book/installing-rust.html) and setting .bashrc $PATH to point to $HOME/.local (export PATH=$HOME/.local:$PATH )  cargo compiles ( though it is not necessary to compile cargo, as rustup.sh installs cargo, too. )
As You suggested: it seems that that the conservative packaging of Ubuntu is too slow to follow the changes.
Thanks,
s

**Comment by alexcrichton** [comment]
Ah ok, good to know, and thanks again for the report!
