### ISSUE TITLE
Workspaces: Add a way to disable transitive inclusion of path dependencies

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/cargo#3192]
Right now, a workspace root automatically includes all of its path dependencies as workspace members. It would be nice if we could disable this somehow.

This is a follow-up to [#3156](https://github.com/rust-lang/cargo/issues/3156#issuecomment-251475209).

**Use case**:

Assume that we have a local library crate that we don't want to publish (yet). We include it in multiple executable crates through `path = "../our_library"` dependencies:

```
├── our_library
│   ├── Cargo.toml
│   └── src
├── executable_1
│   ├── Cargo.toml
│   └── src
└── executable_2
    ├── Cargo.toml
    └── src
```

Now we want to make the executables workspace roots. This leads to the following errors:

> error: workspace member `/home/…/our_library/Cargo.toml` is not hierarchically below the workspace root `/home/…/executable_{1,2}/Cargo.toml`

So each executable requires that we make `our_library` a workspace member of its own workspace. But a crate can't be part of multiple workspaces.

Right now, there is no way to resolve this problem, since there is no way to disable the automatic inclusion of path dependencies.

**Comment by alexcrichton** [comment]
Thanks for the report!

**Comment by Boscop** [comment]
Upvote!
I run into this problem frequently.
The easiest solution would be to only make imported crates that are in a subfolder of the workspace members of that workspace.
Especially if the workspace members are explicitly specified, there should be no confusion!
Anyone would intuitively assume that a workspace can only include crates in the subfolders.

**Comment by whitequark** [comment]
This makes using cargo workspaces a nightmare when I need to develop a crate outside of the workspace. Currently, for any trivial change, I have to:
  * do a commit in the external crate
  * get its git hash
  * update Cargo.toml of the crate inside the workspace
  * rebuild

**Comment by SergioBenitez** [comment]
Chiming in as I've run into this as well.

I believe the correct thing to do here is to assume that any path dependency that is not hierarchically below the workspace is not part of that workspace. In other words, do not implicitly include path dependencies that are not hierarchically below the workspace. If a user explicitly adds such a member to the workspace, then this error can be given.

**Comment by alexcrichton** [comment]
Ah I didn't think this was entirely closed out with #3443, so I'm going to reopen. (manual annotations are still not implemented)

**Comment by alexcrichton** [comment]
Ok, so here's a thought of how to fix this. Add a new key to `Cargo.toml`:

```toml
[workspace]
exclude = [
    "path1",
    "path/to/dir2",
    # ...
]
```

The idea is that as a workspace *root* you can dictate paths which are not included in the workspace (hierarchically). That means that if you traverse upwards through one of those dirs into the `[workspace]` you're not considered part of that workspace.

Thoughts?

**Comment by Boscop** [comment]
I like that, if all non-excluded crates in subfolders are automatically members of the workspace.

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/cargo/pull/3837 as a sample implementation of my idea to close this issue. Feedback would be much appreciated!
