### ISSUE TITLE
Workspaces: Cargo commands with explicit package should work from the root of the workspace.

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3194]
Currently most Cargo commands do not work with workspaces. There is #2878 for providing `--all` flag. However oftentimes you want to execute command only on a single member. `--package` argument should handle that, but currently `cargo test --package foo` will give you a virtual manifest error.

**Comment by alexcrichton** [comment]
👍 

Definitely the intention of workspaces!

**Comment by matklad** [comment]
Hm, and how should profiles work with workspaces? I am looking at [this line](https://github.com/rust-lang/cargo/blob/a8baa5b8f36e88170c8c56523b6eb72efc2cc55e/src/cargo/ops/cargo_compile.rs#L172) and I don't know what to do if we don't have a current package. 

One possible solution is to treat a single `--package` argument as if it specifies the current package, but this won't work if there are several `-p` specified, or if the package is not from the current workspace.

**Comment by alexcrichton** [comment]
Oh that may be a bug from the RFC actually, it was intended that the workspace root configured all the profiles of one compilation.

**Comment by matklad** [comment]
Can the virtual manifest contain `profiles` section?

**Comment by alexcrichton** [comment]
Hm maybe not currently, but it in theory should be able to, yeah.
