### ISSUE TITLE
Race condtion when building on stable?

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#3196]
Something is causing release builds of slog-rs on stable to intermittently fail:

https://travis-ci.org/dpc/slog-rs/jobs/164791054

```
   Compiling slog-example-lib v0.1.0 (file:///home/travis/build/dpc/slog-rs/crates/example-lib)
error[E0460]: found possibly newer version of crate `log` which `env_logger` depends on
 --> examples/binary-no-slog.rs:2:1
  |
2 | extern crate env_logger;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: crate `log` path #1: /home/travis/build/dpc/slog-rs/target/release/deps/liblog-bf16bb9a4912b11d.rlib
  = note: crate `log` path #2: /home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-40393716.so
  = note: crate `env_logger` path #1: /home/travis/build/dpc/slog-rs/target/release/deps/libenv_logger-c716af707f2027e1.rlib
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `slog-example-lib`.
```

Restarting the build usually fixes the issue.

I suspect since it happens on stable only, it has something to do with `[workspaces]` that we use in main `Cargo.toml`, but stable does not support yet.

Corresponding slog-rs issue: https://github.com/dpc/slog-rs/issues/63

**Comment by alexcrichton** [comment]
Ok, I've been trying to reproduce this locally trying to compile as your travis builds do for the past few hours but I've been unable to reproduce anything :(

Could you try passing `-v` to Cargo on Travis and see if we can capture a failed log like that? That may help debug what's going on here.

Also, this is just intermittent for you, right? There's no way to reliably reproduce this?

**Comment by dpc** [comment]
It seems it always fail the first time. Afterwards restarting it just works. It might be some timing issue with travis internals and the way they setup rust support?

I'll get back to you with `-v` results.

**Comment by dpc** [comment]
https://travis-ci.org/dpc/slog-rs/jobs/168441426

**Comment by alexcrichton** [comment]
Thanks!

...

Weird!

....

I'll try to digest soon...

**Comment by rocallahan** [comment]
This fails for me 100% of the time at the moment :-(

**Comment by rocallahan** [comment]
100% of the time in any incremental build, that is. Clean builds are OK.

**Comment by dpc** [comment]
@rocallahan Any link to travis jobs with `-v` or something like it?

**Comment by rocallahan** [comment]
No, this was a local build.

And the problem has gone away :-(.

Next time I'll get an rr trace of it :-).

**Comment by rocallahan** [comment]
I hit it again.

With `-v` I get
````
     Running `rustc src/main.rs --crate-name registers_recorder_cmd --crate-type bin -g -C metadata=404a81f7c580d11d --out-dir /home/roc/pernosco/code/target/debug --emit=dep-info,link -L dependency=/home/roc/pernosco/code/target/debug/deps --extern log=/home/roc/pernosco/code/target/debug/deps/liblog-bf16bb9a4912b11d.rlib --extern db_io=/home/roc/pernosco/code/target/debug/deps/libdb_io.rlib --extern remix_interface=/home/roc/pernosco/code/target/debug/deps/libremix_interface.rlib --extern env_logger=/home/roc/pernosco/code/target/debug/deps/libenv_logger-c716af707f2027e1.rlib --extern registers_recorder=/home/roc/pernosco/code/target/debug/deps/libregisters_recorder.rlib --extern clap=/home/roc/pernosco/code/target/debug/deps/libclap-8f0c0e13919e3e65.rlib --extern rr_trace=/home/roc/pernosco/code/target/debug/deps/librr_trace.rlib --error-format=json -L native=/home/roc/pernosco/code/target/debug/build/miniz-sys-60c8d67696f63a43/out -L native=/home/roc/pernosco/code/target/debug/build/registers-recorder-65a2d1344123b6ba/out -L /home/roc/rr/obj/lib/rr -L /home/roc/dynamorio/obj/lib64 -L /home/roc/dynamorio/obj/lib64/release`
{"message":"found possibly newer version of crate `log` which `env_logger` depends on","code":{"code":"E0460","explanation":null},"level":"error","spans":[{"file_name":"src/main.rs","byte_start":19,"byte_end":43,"line_start":2,"line_end":2,"column_start":1,"column_end":25,"is_primary":true,"text":[{"text":"extern crate env_logger;","highlight_start":1,"highlight_end":25}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[{"message":"perhaps that crate needs to be recompiled?","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"crate `log` path #1: /usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-5c6cf767.so","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"crate `log` path #2: /home/roc/pernosco/code/target/debug/deps/liblog-bf16bb9a4912b11d.rlib","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"crate `env_logger` path #1: /home/roc/pernosco/code/target/debug/deps/libenv_logger-c716af707f2027e1.rlib","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":null}
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":null}
error: Could not compile `registers-recorder-cmd`.
````

**Comment by alexcrichton** [comment]
@rocallahan oh interseting! If you've got a repro locally could you describe the steps to reproduce? Even if it's flaky I can try to help poke at it locally as well.

**Comment by alexcrichton** [comment]
@dpc if you can still reproduce on Travis it'd be helpful to set `RUST_LOG=cargo::ops::cargo_rustc::fingerprint` as well. Unfortunately I still can't reproduce locally :(

**Comment by rocallahan** [comment]
>  If you've got a repro locally could you describe the steps to reproduce?

Not enough to reproduce. I have a number of crates sharing a workspace. I have a script that iterates through the crates running `cargo build` in each one.

Next time it shows up I'll try that `RUST_LOG`. I have an rr trace but it appears the compiler was not built with debug info so that's not much sue.

**Comment by dpc** [comment]
@alexcrichton It stopped happening on Travis for me, couple of weeks ago.

**Comment by alexcrichton** [comment]
@rocallahan oh the more interesting trace would actually be Cargo rather than the compiler. I suspect the bug is there as not much around this changed in the compiler recently (afaik). A RUST_LOG + verbose trace with Cargo though should provide me enough information to debug though without reproducing

**Comment by carols10cents** [comment]
I'm going to close this due to inactivity and inability to reproduce, but please reopen if this happens again!
