### ISSUE TITLE
unexpected full rebuild after delete ~/.cargo/{git  registry}

### ISSUE THREAD

**Issue by jarod** [rust-lang/cargo#3197]
I want to do clean up of old crate cache, so I deleted ~/.cargo/{git  registry}, now cargo do full build when I change even one line of code in my project.
I understand it should do full rebuild at first build, but not everytime.
```
$ rustc --version
rustc 1.12.0 (3191fbae9 2016-09-23)
$ cargo --version
cargo 0.13.0-nightly (109cb7c 2016-08-19)

```

**Comment by alexcrichton** [comment]
Thanks for the report! Can you try running with this as well:

```
RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info
```

and gist the output of that (when it causes a rebuild when it shouldn't)

**Comment by jarod** [comment]
part of the output:
```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for rustc-serialize v0.3.19: RUSTFLAGS has changed
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for env_logger v0.3.5: RUSTFLAGS has changed
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for log v0.3.6: RUSTFLAGS has changed
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for regex v0.1.77: RUSTFLAGS has changed
```

I was using atom with rust plugin as editor. which auto-build with cargo on save. 
But I'm pretty sure these full-rebuild not happen when I switch between atom / console build before I delete ~/.cargo/{git registry}.
Anyway, I verified that when only build with cargo on console it won't do full-rebuild. so, not an issue of cargo.
