### ISSUE TITLE
Cargo recompile when modifying an inner crate

### ISSUE THREAD

**Issue by antoyo** [rust-lang/cargo#3199]
Hello.
Let's say I have a crate `a` and within this crate directory, I have another crate `b`.
The crate `a` does not depend on crate `b` for some reason (perhaps because crate `b` is loaded at run time).
If I modify the code of crate `b`, `cargo run` executed on crate `a` will recompile even thought it is useless (remember crate `a` does not depend on `crate `b`).
It would be nice to avoid this useless compilation in this specific case.

Running with `RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info` gives the following:
```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for project v0.1.0 (file:///path/to/project): profile configuration has changed
```
Thanks.

**Comment by alexcrichton** [comment]
This looks like the profile configuration is changing, which means pieces like optimization level, debuginfo, etc. Does that perhaps cause a problem here as well?

**Comment by antoyo** [comment]
I don't understand your question.
Here is what I am doing:
```
# Update file in the inne crate.
# In inner crate directory.
cargo build
# In the outer crate directory.
cargo run
```
Everytime I do so, the `cargo run` command rebuilds the project, even thought it is useless since it does not depend on the inner crate (the outer crate loads the inner library .so at run time).

**Comment by alexcrichton** [comment]
Are the crate part of the same workspace? If not then they'll have separate target directories which means that a build in one doesn't necessarily carry over artifacts to the other.

**Comment by antoyo** [comment]
Here is the directory tree:
```
.
├── Cargo.lock
├── Cargo.toml
├── src
├── target
└── inner-crate
    ├── Cargo.lock
    ├── Cargo.toml
    ├── src
    └── target
```

**Comment by alexcrichton** [comment]
Ah yes this is expected, the to output directories (the two `target` directories) are disjoint, so you'll rebuild as you move between projects. This can be fixed with Cargo's recent feature of workspaces or with `CARGO_TARGET_DIR`

**Comment by antoyo** [comment]
I was actually caused by [`clippy`](https://github.com/Manishearth/rust-clippy/issues/1281).
