### ISSUE TITLE
A linkage error when running tests relying on a sys crate

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/cargo#3200]
There is a crate that depend on a sys crate. The crate has documentation tests and benchmarks. The tests used to compile and pass on nightly a couple of days back, but they fail to do so right now. The benchmarks work just fine in both cases. The error is due to linkage:

```
dyld: Library not loaded: @rpath/libfoo.dylib
  Referenced from: /var/folders/_c/vpdds93d4h1_bqdypvl5jqd40000gn/T/rustdoctest.V4bH22QTQP0U/rust_out
  Reason: image not found
', ../src/librustdoc/test.rs:323
```

The versions of Rust and Cargo that don’t have this issue are as follows:

```
rustc 1.14.0-nightly (a3bc191b5 2016-10-10)
cargo 0.13.0-nightly (957a47b 2016-10-10)
```

The versions of Rust and Cargo that have this issue are as follows:

```
rustc 1.14.0-nightly (098d22845 2016-10-13)
cargo 0.13.0-nightly (5f2cc15 2016-10-13)
```

Here is how it looks on Travis CI: [before](https://travis-ci.org/stainless-steel/blas/jobs/167233371) and [after](https://travis-ci.org/stainless-steel/blas/jobs/167564407).

I’m wondering if it’s indeed due to the latest changes in Rust and/or Cargo, or it’s a problem with the crate itself. Let me know if the rust repository is a better fit for this issue. Thank you.

Regards,
Ivan

**Comment by alexcrichton** [comment]
Hm two relevant PRs could be https://github.com/rust-lang/cargo/pull/3193 or https://github.com/rust-lang/cargo/pull/3198. Intended to be refactorings but may have been buggy, I'll take another look.

**Comment by alexcrichton** [comment]
@matklad it looks like the dylib path var stuff in https://github.com/rust-lang/cargo/pull/3198 changed in some of the refactoring, I think maybe that's what caused this?

**Comment by matklad** [comment]
Yep, looks like it. Will investigate.

Looks like `rustdoc` gets different flags:

<details>

Before:
```
Running `rustdoc --test /home/user/projects/blas/src/lib.rs --crate-name blas
-L dependency=/home/user/projects/blas/target/debug/deps
-L dependency=/home/user/projects/blas/target/debug
-L /home/user/projects/blas/target/debug/build/openblas-src-243dacb5e0bf19bc/out/opt/OpenBLAS/lib
--cfg feature=\"blas-sys\" --cfg feature=\"default\" --cfg feature=\"openblas\" --extern num_complex=/home/user/projects/blas/target/debug/deps/libnum_complex-704ef091ce88b7b2.rlib --extern blas_sys=/home/user/projects/blas/target/debug/deps/libblas_sys-c7db4cd665708a15.rlib --extern blas=/home/user/projects/blas/target/debug/libblas.rlib --extern libc=/home/user/projects/blas/target/debug/deps/liblibc-ad32fde1bd850538.rlib`
```

After:
```
Running `rustdoc --test /home/user/projects/blas/src/lib.rs --crate-name blas
-L dependency=/home/user/projects/blas/target/debug/deps
-L /home/user/projects/blas/target/debug/build/openblas-src-243dacb5e0bf19bc/out/opt/OpenBLAS/lib
--cfg feature=\"openblas\" --cfg feature=\"default\" --cfg feature=\"blas-sys\" --extern num_complex=/home/user/projects/blas/target/debug/deps/libnum_complex-704ef091ce88b7b2.rlib --extern blas_sys=/home/user/projects/blas/target/debug/deps/libblas_sys-c7db4cd665708a15.rlib --extern libc=/home/user/projects/blas/target/debug/deps/liblibc-ad32fde1bd850538.rlib --extern blas=/home/user/projects/blas/target/debug/deps/libblas.rlib`
```

</details>

**Comment by IvanUkhov** [comment]
@matklad, thanks for the help! Please note also that the job in question had a custom feature enabled, not the default one:

```
cargo test -vv --no-default-features --features=netlib
```

By default, it’s `openblas`, not `netlib`.
