### ISSUE TITLE
Incorrect [root] in Cargo.lock when using workspaces

### ISSUE THREAD

**Issue by debris** [rust-lang/cargo#3203]
I have a project with several (10+) local libraries

```
…
├── Cargo.toml
├── src
├── sub1
│   ├── Cargo.toml
│   ├── src
├── sub2
│   ├── Cargo.toml
│   ├── src
```

My `Cargo.toml` looks like this.

```
[project]
name = "foo"
version = "0.1.0"
authors = []

[dependencies]
sub1 = { path = "sub1" }
sub2 = { path = "sub2" }
```

After adding `[workspace]` to the end of `Cargo.toml`

```
[project]
name = "foo"
version = "0.1.0"
authors = []

[dependencies]
sub1 = { path = "sub1" }
sub2 = { path = "sub2" }

[workspace]
```

All of my dependencies compile as a part of my workspace (as expected). **But** what's strange, `foo` is no longer a `[root]` in my `Cargo.lock` file. Instead `sub1` is. Is it intended behaviour?

**Comment by alexcrichton** [comment]
Indeed! The `[root]` in `Cargo.lock` is basically just backwards compatibility at this point. We essentially just had to deterministically choose a crate to go there. Shouldn't affect any usage of Cargo though!

**Comment by debris** [comment]
> Shouldn't affect any usage of Cargo though!

That's right. It only affects one of the tools I'm using - [cargo-graph](https://github.com/kbknapp/cargo-graph). I've created the issue over there. https://github.com/kbknapp/cargo-graph/issues/33

**Comment by alexcrichton** [comment]
Ok, thanks!

**Comment by behnam** [comment]
@alexcrichton, was there any reason to not use the workspace root as the lock root, at least for cases where workspace Cargo.toml is combined with a package? If not, is it still possible to make this happen, or is it too late?

At the moment, there's no way to find the workspace root looking only at the lock file, which is kind of unexpected and demands extra work for tools, like cargo-graph, to figure it out.

**Comment by alexcrichton** [comment]
Unfortunately that'd make a backwards incompatible change at this point :(

**Comment by remram44** [comment]
Honestly I think the `[root]` should either be removed or fixed. There is no point keeping it "for compatibility" if compatibility has been broken. Either cargo-graph shouldn't use this (but why not use this if it's present?) or the correct info should be written to `Cargo.lock`.

**Comment by remram44** [comment]
After #4571, Cargo no longer includes `[root]` in the lock file. This makes cargo-graph even more broken. (I have updated my patch)
