### ISSUE TITLE
build.rs won't run if lib.rs if missing

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/cargo#3208]
Cargo won't compile a dependency if `lib.rs` is missing, confusingly reporting that it can't validate the manifest. This makes it difficult, if not impossible, to have a `build.rs` which generates `lib.rs` without a non-Cargo preparation step (eg `touch src/lib.rs`).

In my case, for the FFI bindings for DPDK, I need to generate them as part of the build as I'm using a forked DPDK with fixes to make it usable to both Rust and with musl.

**Comment by matklad** [comment]
Can you generate `src/ffi.rs` instead, and use the following `src/lib.rs`:

```
mod ffi;

pub use ffi::*;
```

? 

Cargo uses `src/lib.rs` to implicitly define a target, and it would be strange if a custom build script changed the set of targets. This could be done, but perhaps a `pub use::*` is a simpler solution?

**Comment by raphaelcohn** [comment]
I probably can use a `pub use` - thank you for the suggestion. However, that seems to be very much a workaround. I don't really understand your point about `src/lib.rs` being used to implicitly define a target. Is there more of an explanation you can give me?

**Comment by matklad** [comment]
>Is there more of an explanation you can give me?

Sure! Each Cargo package (the directory with source code and a Cargo.toml) can produce several crates. For example, the typical layout

```
my_project/
  Cargo.toml
  src/ 
    main.rs
    lib.rs
```

has two crates, the library crate with the root modules in `lib.rs` file and a binary crate with a root module in `main.rs` file. 

These crates are called targets and can be specified in Cargo.toml: http://doc.crates.io/manifest.html#configuring-a-target. 

Some targets are inferred implicitly from the project layout: `src/lib.rs` is the default library target, `src/main.rs` is the default binary target and `src/foo.rs` is **not** a target by default.

So if you have

```
Cargo.toml
src/
   lib.rs
   foo.rs
```

and an explicit `[[bin]] path = "src/foo.rs"` in `Cargo.toml`, you can easily say just from the project structure that there are two targets. 

Looks like you want something like these:

```
Cargo.toml
build.rs
```

For this project, you can't determine the set of targets upfront, because `build.rs` can generate them.

**Comment by KalitaAlexey** [comment]
@raphaelcohn I actually think that code generation should be in **target** directory.
I suggest you to create **lib.rs** with the following content:
```rust
include!(concat!(env!("OUT_DIR"), "/lib.rs"));
```
and to generate **lib.rs** in target directory with the following code:
```rust
let out_dir = env::var_os("OUT_DIR").unwrap();
let dst = Path::new(&out_dir).join("lib.rs");
```

**Comment by alexcrichton** [comment]
Indeed as @matklad mentioned this is currently intentional. The current solution is to do what @KalitaAlexey mentions by generating a file into `OUT_DIR` in a build script and then including that from the main library.

**Comment by raphaelcohn** [comment]
@matklad @KalitaAlexey Thank you for your detailed, clear and useful explanations and suggestions. It'd be quite easy to switch to building to `OUT_DIR` and I'll consider doing that. A disadvantage of doing so is that currently I'm making the contents of it invisible to my IDE because it contains a lot of noise - and I'm constantly examining generated structs, etc to try to write effective wrappers. DPDK contains an insane number of types - 900+ and counting...

(As an aside, I actually loathe code generation as it makes the simple so opaque; sadly, DPDK being the beast it is there really isn't any option).

**Comment by matklad** [comment]
>A disadvantage of doing so is that currently I'm making the contents of it invisible to my IDE because it contains a lot of noise - and I'm constantly examining generated structs, etc to try to write effective wrappers.

A useful convention from the Java world is to use different folders for source code (`src`), generated code (`gen`) and output (`out`). It does help with IDEs, because you mark `out` as excluded, `src` as sources and `gen` as generated sources.

**Comment by raphaelcohn** [comment]
@matklad Yes, I'm quite familiar with Java; I previously created a build DSL for Java that was self-parallelizing - back in the days when Ant was considered the bees knees... Sadly mainstream Java has spawned a whole raft of horrid build and deployment patterns, which I've spent the last few years ignoring with ever larger hands over my ears...

**Comment by alexcrichton** [comment]
Ok, sounds like there's an alternate solution here, so closing. Feel free to correct me though if I'm misled!

**Comment by raphaelcohn** [comment]
FYI: Have tried `include!(concat!(env!("OUT_DIR"), "/lib.rs"));` this morning. It doesn't work as `include!` is moaning about wanting everything to be a string literal...

```
error: argument must be a string literal
 --> src/lib.rs:5:10
  |
5 | include!(concat!(env!("OUT_DIR"), "/lib.rs"));
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/lib.rs:5:1: 5:47 note: in this expansion of include!

error: non-item macro in item position: include
 --> src/lib.rs:5:1
  |
5 | include!(concat!(env!("OUT_DIR"), "/lib.rs"));
  | ^^^^^^^
```
I suspect this may be because the build script runs a macro (a derivative of rust-cpp) that generates C...

Feel free to close this issue if you like - but a few notes somewhere in Cargo's docs on best practice for this sort of thing would be appreciated. It'd be nice if the default targets set were evaluated AFTER `build.rs` ran, but that might not be possible, I suppose.

**Comment by matklad** [comment]
@raphaelcohn you may find this section of the docs useful: http://doc.crates.io/build-script.html#case-study-code-generation

**Comment by raphaelcohn** [comment]
Thank you.
