### ISSUE TITLE
Feature request: add a command to list the build targets for a given source file

### ISSUE THREAD

**Issue by fmdkdd** [rust-lang/cargo#3211]
[flycheck](http://www.flycheck.org/en/latest/) contributor here.  I'm working on improving the rust support for flycheck, and adding a command to cargo to get the potential build targets for a rust source file could be useful to us.

Flycheck is an Emacs package that reports errors in the buffer.  For rust, it calls rustc or cargo to get compilation errors and displays them at their correct location in the buffer every time you save the file.  Flycheck works on a file basis, not a on project basis like most IDEs.  The user does not set a build target and trigger a "built target" to get compilation error.  We currently pick a suitable build target, run it when the buffer is saved to a file, and report the compilation errors and warnings inline.

Since users expect to get error feedback for the current file they are editing, we must pick a built target that includes the current file.  We don't have to guess when the current file is the main file of a target (like `src/main.rs` or `src/lib.rs`), but for other files in the project we do.  At the moment we read the output of `cargo read-manifest` to find if the current file is mentionned, and default to the first target if the file isn't found.  

I'm working on flycheck/flycheck-rust#43 to expand our automatic target detection, based on the conventional cargo layout: files under `src/` belong to the library target (if there's one) or to the main target, files under `tests/common` belong to a test target.

Now obviously, these guesses are limited, since we never read the files to resolve their imports, we cannot tell that, e.g., `src/bin/support/x.rs` is actually used by the binary target `src/bin/b.rs`.  If we guess wrong, we will build the wrong target and won't report any errors for the current file.

If we had a cargo command `list-targets` that gave, for a source file under a cargo project, the list of build targets the file is used in, that would allow us to reliably build the right target and produce the compilation errors.

For example: if `src/main.rs` in the crate foo depends on `src/a.rs`, `cargo list-targets src/a.rs` would return:

```
[
  { "kind": ["bin"],
    "name": "foo" }
]
```

Alternatively, `cargo list-targets` could return just a list of root source files:

```
src/main.rs
```

and we could match these with the targets returned by `cargo read-manifest`.

_Note_: I'm aware that work on the RLS is ongoing, and that it does currently report compilation errors for a given file.  So if you'd rather focus efforts on that, I'd understand.  However, this command might still be useful, especially if the cost of implementation is not too high.

**Comment by matklad** [comment]
>At the moment we read the output of cargo read-manifest to find if the current file is mentionned, and default to the first target if the file isn't found.

You might want to use `cargo metadata --no-deps` instead. `readmanifest` is deprecated, and `cargo metadata --no-deps` produces more info and is able to handle workspaces. 

In general I think it is impossible to list build targets without building the project, so this is a bit of a chicken and egg problem. Consider the following layout:

```
src/
  lib.rs
  main.rs
  foo.rs
```

What target does `foo.rs` belong to? All four answers (`bin`, `lib`, both, neither) are possible, depending on the contents of the `lib.rs` and `foo.rs`.

**Comment by matklad** [comment]
To expand a bit, Cargo does not now the answer about `foo.rs` at all. It just invokes the compiler on the appropriate root file, and it is the compiler who reads `foo.rs` when it sees `mod foo;`.

**Comment by fmdkdd** [comment]
Thanks for the `metadata` tip.  I didn't know `read-manifest` was deprecated :fearful:.

Yeah, I looked into the cargo source a bit, and I saw that it was definitely not building or even reading the project files to determine the targets.

So, do you think the compiler could give us the build targets then, or at least, the root source file for `foo.rs`?  Or is that just a part of the build process, and we are better talking to the RLS directly?

**Comment by matklad** [comment]
I don't think you can use the compiler for this, because you'll need to know the root source file.

So looks like this task should be a part of RLS. And I think that racer perhaps can answer this question as well: it can crawl up the module tree up to the root module, and if you know the root module, you can just lookup it in the array of targets returned by `cargo metadata`. We do something similar in IntelliJ Rust, except for the fact that we reconstruct the module structure by actually parsing the files.

**Comment by matklad** [comment]
Just some random potentially useful info: looks language server protocol does not specify an API to query for executable targets for the file, while the Dart analyzer protocol has this API: https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#domain_execution

**Comment by alexcrichton** [comment]
Some more thoughts of mine:

* Right, Cargo doesn't actually have this knowledge at all. Cargo only understands *entrypoints*, not the files those depend on.
* Cargo does, however, use the compiler to track dependencies. Basically the output of `rustc --emit dep-info` which will list all files used by a particular compile.
* To that end, you could combine `cargo metadata` (learning of entry points) with `rustc --emit dep-info` (learning of file dependencies) to determine what targets a file belongs to
* Unfortunately though even that won't always work, for example in situations with code generation (aka `include!`). Perhaps this is rare enough to not matter though?

In that sense I think we may be able to add this to Cargo, but it might be worth exploring locally first. Cargo would have to do a fair amount of work to learn this information so it all just needs to be written up somewhere! Does that make sense?

**Comment by fmdkdd** [comment]
`rustc --emit dep-info` does indeed give the answer, but it seems it only does so after a successful compilation, so if the project has any errors we won't get anything, right?  Unfortunately, in our case the project most likely *has* errors that will prevent a compilation. 

I'll look into racer to see what we can get out of it.  But even then, it's a third-party tool that might not be installed.  So I think we'll just keep guessing the dependencies (eventually with racer) until we can talk to the RLS directly to get errors, at which point we can skip interacting with Cargo.

Thank to both of you for taking the time to lay out the options :)

Feel free to close this, unless you think this feature would be useful to Cargo regardless of whether we'd use it in Flycheck.

**Comment by alexcrichton** [comment]
@fmdkdd it's the intention at least that `--emit dep-info` exits the compiler immediately after dependency information is available (aka after parsing). If that's not the case though then that's a bug in the compiler!

**Comment by fmdkdd** [comment]
@alexcrichton I was mistaken: checking again, it does emit dependencies even if the target has compilation errors.  But, it seems the compiler it won't stop as soon as this information is available.

I have one file `src/lib.rs` that contains only the line: `mod a;`, and in `src/a.rs` I have a syntactical correct function with a borrowing error:
```
fn foo() {
  let mut a = 0;
  let b = &mut a;
  let c = &mut a; 
}
```
Invoking:
```
rustc --crate-type lib --emit dep-info src/lib.rs
```
creates the file `lib.d` (and nothing in `target/`):
```
lib.d: src/lib.rs src/a.rs

src/lib.rs:
src/a.rs:
```
But the output also reports the borrow error:
```
error[E0499]: cannot borrow `a` as mutable more than once at a time
 --> src/a.rs:4:16
  |
3 |   let b = &mut a;
  |                - first mutable borrow occurs here
4 |   let c = &mut a;
  |                ^ second mutable borrow occurs here
5 | }
  | - first borrow ends here

error: aborting due to previous error
```
Is this as intended?  From what you describe, it seems it would return well before the borrow checking pass.  

For our use case, it might not be an issue, as we still get dependencies.  In fact, it means we would get dependencies and errors in just one call.  But for larger projects, skipping the later passes could speed up getting the dependencies.

**Comment by alexcrichton** [comment]
@fmdkdd oh I think that's a compiler/rustc bug, want to open an issue against rust-lang/rust for that?

**Comment by fmdkdd** [comment]
@alexcrichton Sure: rust-lang/rust#38025.

**Comment by fmdkdd** [comment]
Regarding the deprecation of `read-manifest`: I see that was the plan in #2356 to emit a warning, but that was never implemented, as far as I can tell.

**Comment by alexcrichton** [comment]
@fmdkdd ah if that warning hasn't been implemented yet then that just means we won't be able to remove it even longer, unfortunately.

**Comment by carols10cents** [comment]
Given:

> Feel free to close this

and https://github.com/rust-lang/rust/issues/38025 being closed as fixed, and https://github.com/flycheck/flycheck-rust/pull/43 being merged, and RLS having progressed, I'm going to close this :) Thanks!
