### ISSUE TITLE
Add a flag to set the library type

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#3218]
# cargo build --lib --crate-type=dylib
    # cargo build --lib --crate-type="dylib staticlib"
It would temporarily override the `lib.crate-type` in `Cargo.toml`.

**Comment by Yamakaky** [comment]
Closing for https://github.com/rust-lang/rust/issues/37329

**Comment by Yamakaky** [comment]
Oops

**Comment by Yamakaky** [comment]
My use case is that I have a rust library with a C interface + bins. Normally I only want to build as a rlib, but sometimes I want to release the `.so`. The build is a few seconds longer with the two enabled at the same time.

**Comment by Yamakaky** [comment]
`cargo rustc --lib -- --crate-type=dylib` seems to do the job.

**Comment by alexcrichton** [comment]
Ah right, yes indeed that should work! Does that suffice for this use case?

**Comment by Yamakaky** [comment]
Yes!
