### ISSUE TITLE
Cargo is confusing itself with different library versions?

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#3222]
So, I'm halfway between breaking one workspace into separate git repositories and I've stumbled upon a weird case.

If you build this version of slog: https://github.com/slog-rs/slog/commit/b3bbfe2854d887d47c13530996519d6b56de66ba inside it's own repository (`make all`) the `crate/stream` will fail to build with:

```
   Compiling slog-stream v1.2.0 (file:///home/dpc/lab/rust/slog-rs/crates/stream)
   Compiling slog-stream v1.2.0
   Compiling chrono v0.2.25
error[E0277]: the trait bound `slog::Fuse<Streamer<W, F>>: slog::Drain` is not satisfied
  --> crates/stream/lib.rs:87:5
   |
87 |     Async::new(Streamer::new(io, format).fuse())
   |     ^^^^^^^^^^
   |
   = note: required by `slog_extra::Async::new`

error: aborting due to previous error
```
even though `Streamer` definitely implements `Drain` and it works when included as a dependency in outside create.

But if you just include `slog-stream = "1.2"`  as a dependency in outside software, everything compiles just fine.

Also I've noticed that for whatever reason multiple versions of `rlib` files are created for some libraries. Following is after cleaning the repo and doing `make all`

```
[I] dpc@futex ~/l/r/slog-rs (master) [I]> find . | grep libslog
./target/debug/deps/libslog.rlib
./target/debug/deps/libslog-899858e0a14f3a18.rlib
./target/debug/deps/libslog_atomic.rlib
./target/debug/deps/libslog_scope.rlib
./target/debug/deps/libslog_extra-e584797eeeb9116d.rlib
./target/debug/deps/libslog_stream-b6dea449db722860.rlib
./target/debug/libslog.rlib
```

How come there is one `libslog.rlib` with some hexstring and one without it?

**Comment by dpc** [comment]
Ok. So I've found the issue. All my addon-creates `slog-x` depend on `slog` itself, while `slog` specify some of them in `[dev-dependencies]`. Everything was fine until I've moved one of my `slog-x` outside of the current `workspace`. Now it seems to be pulling in `slog` from crates.io, and not use my local `slog` version. Adding `.cargo/config` with:

`paths = [ "." ]`

fixes the issue.

I don't know if that's an intended behaviour. Feel free to close if it is.

**Comment by alexcrichton** [comment]
Ah yes that'd do it! For crates in a workspace they should generally all depend on one another as `path` dependencies as there's no need for crates.io to come into the picture. You can do that with a `paths` override but a path dependency itself is likely to work better.

Also for the multiple rlibs, the hex strings are inserted for upstream crates (crates.io and git) but no hex strings are present for local crates (e.g. those with path dependencies and such).
