### ISSUE TITLE
the command `cargo build --target=` panic

### ISSUE THREAD

**Issue by thiolliere** [rust-lang/cargo#3224]
the command `cargo build --target=` panic

**Comment by alexcrichton** [comment]
I believe the relevant panic is [this one](https://github.com/rust-lang/cargo/blob/9a0801da0caa81653950baffabd8705d41d24d40/src/cargo/ops/cargo_rustc/layout.rs#L81) and should be relatively easy to remove, just need to punt upwards an error there!
