### ISSUE TITLE
Doc tests ignore RUSTFLAGS

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#3227]
(Moved from https://github.com/rust-lang/rust/issues/37330)

I am writing doc examples for the bindings of a C library.
In my `RUSTFLAGS`, I add a search path for the C library using `-L /path/to/lib`. (needed because I am using a custom version of the library that's not installed globally)

`cargo build/run` picks this up fine, and the C library links correctly.
However, doc tests cause a linking error, because `RUSTFLAGS` seem to be ignored when compiling doc examples.

**Comment by alexcrichton** [comment]
Ok so as [pointed out by @rkruppe](https://github.com/rust-lang/rust/issues/37330#issuecomment-255964675) I was corrected in that we actually *can't* do this blindly per se. That is, rustdoc doesn't currently have a feature for "pass these flags to the compiler". 

What you can do today, however, is hopefully use RUSTDOCFLAGS!

**Comment by carols10cents** [comment]
It sounds like using `RUSTDOCFLAGS` fixes this issue, so I'm going to close this. Please reopen if I'm mistaken! Thank you!
