### ISSUE TITLE
Cargo does not play nicely with sudo

### ISSUE THREAD

**Issue by alexreg** [rust-lang/cargo#3228]
Example:

```
sudo -Hs -u _homebrew cargo
error: could not crate home directory: '/usr/local/.multirust'
info: caused by: Permission denied (os error 13)
```

Ideally, sudo (at least when used with the `-H` option) should use the toolchain/settings for the parent user, not root/_homebrew/whatever use you're sudoing as.

Also, note the typo "crate" (should be "create").

**Comment by alexreg** [comment]
Note, this is on OS X 10.12.

**Comment by alexcrichton** [comment]
While I could definitely believe that Cargo itself doesn't play nicely with sudo (with the global cache) this specific error I believe is coming from rustup, not Cargo itself.

**Comment by alexreg** [comment]
Oops, my bad, sorry.

**Comment by alexcrichton** [comment]
No worries! My guess is that Cargo may have similar issues once it gets that far :)
