### ISSUE TITLE
Cargo 0.14.0-nightly fails to download github dependency

### ISSUE THREAD

**Issue by rphmeier** [rust-lang/cargo#3232]
We're seeing a lot of CI failures on travis where Cargo can't fetch our fork of hyper (e.g. https://travis-ci.org/ethcore/parity/jobs/170781731), but only on the beta branch. The fork in question hasn't been updated for quite some time. This might be a cargo issue, maybe not.

**Comment by alexcrichton** [comment]
Interesting! I wonder if perhaps the travis cache is busted there? Maybe the git repo is corrupt? 

Before that's blown away, though, could you try passing `-v` to Cargo to print out why the fetch is failing?

**Comment by rphmeier** [comment]
Haven't tried with `-v` yet, sorry. But I've tried clearing the cache and I'm almost certain that the github repo isn't corrupted since none of our other builds (CI or local) fail for this reason.

**Comment by alexcrichton** [comment]
Weird! I think the `-v` logs are the next step for debugging here as that should print out the precise error that's happening hopefully

**Comment by rphmeier** [comment]
Appears to be a travis issue.
