### ISSUE TITLE
cargo generate-lockfile at a specific crates.io-index revision

### ISSUE THREAD

**Issue by sjmackenzie** [rust-lang/cargo#3234]
I have the strong need to constrain cargo to a specific version of crates.io-index. Is this possible?

**Comment by alexcrichton** [comment]
Currently I don't think this is possible, but could you elaborate on the constraints you've got? There may be another route here!

**Comment by sjmackenzie** [comment]
Okay, I have my own cloned crates.io-registry on upstream fractalide. Which
will automatically setup in the users /nix/store upon execution.

Now the problem; when a programmer creates *new* components in
github.com/fractalide/frac_workbench, cargo generates a lockfile derived
from the $HOME/.cargo registry folder.
The $HOME folder advances faster than my fractalide crates.io-registry
clone, this means when I come round to compiling that new component with
fractalide's cargo, the lockfile contains unknown deps. This process is not
deterministic and the build fails.

So it would be really nice if I could run pass a flag cargo
generate-lockfile --at-rev <crates.io-index rev>
and cargo would generate a lockfile at that revision only.

I hope I'm being clear!

**Comment by alexcrichton** [comment]
Ah ok, so Cargo is fundamentally designed to produce deterministic builds through lock files. That is, once a lock file exists, you're guaranteed a deterministic build. Along those lines, would existing Cargo features like lock files, source replacement, and/or vendoring suffice here?

**Comment by sjmackenzie** [comment]
I suppose you're right, just point the two cargo instances at the same source replacement. Okay thanks, sorry for these bothersome issues, they're probably starting to annoy you ;-)

**Comment by alexcrichton** [comment]
Ah no worries! Let me know if you need any help, and if it doesn't quite work I'd love to figure out how to help Cargo work in this situation!

**Comment by sjmackenzie** [comment]
Ta!
