### ISSUE TITLE
Successful build keeps trying to update from remote repo

### ISSUE THREAD

**Issue by gavinb** [rust-lang/cargo#3235]
Working with `rust-rosetta`, rev `3b5fd74d`.

I performed the following steps:

```
cargo update
cargo clean
cargo build
```

This all completes successfully. At this stage, I have all the dependencies required, and have successfully built all the crates and targets.

However each time I run `cargo build`, it keeps updating the `open-ssl` repo:

```
$ cargo build
Updating git repository `https://github.com/sfackler/rust-openssl`
Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
```

What this means is that it is not possible to work _offline_, as the build tries to update the repo, failing with the following:

```
$ cargo build
    Updating git repository `https://github.com/sfackler/rust-openssl`
warning: spurious network error (2 tries remaining): [12/-1] Failed to resolve address for github.com: nodename nor servname provided, or not known
warning: spurious network error (1 tries remaining): [12/-1] Failed to resolve address for github.com: nodename nor servname provided, or not known
error: failed to load source for a dependency on `openssl-sys`

Caused by:
  Unable to update https://github.com/sfackler/rust-openssl

Caused by:
  failed to fetch into /Users/gavinb/.cargo/git/db/rust-openssl-41da9d20ce19f5aa

To learn more, run the command again with --verbose.
```

I would expect to be able to work offline once you have successfully completed a build.

This is not the only situation where I have discovered that working offline with cargo can be problematic, but it is an easily described and reproducible example.

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have any `paths` overrides in play that you know of? Also, what version of Cargo are you using?

**Comment by gavinb** [comment]
No path overrides are in effect. Sorry, should have included versions! Running:

```
cargo 0.13.0-nightly (02fed69 2016-10-18)
rustc 1.14.0-nightly (16eeeac78 2016-10-18)
```

**Comment by alexcrichton** [comment]
Intersting! Could you also gist the build of `RUST_LOG=cargo=trace` when it erroneously updates?

**Comment by gavinb** [comment]
Here's the full trace: https://gist.github.com/gavinb/0c9874b66cae5779424a228b6c9b4dac

**Comment by alexcrichton** [comment]
Ah so before I dig in too much this may actually be https://github.com/rust-lang/cargo/pull/3220

**Comment by gavinb** [comment]
I just tried building cargo from your alexcrichton/bad branch which includes the patch for #3220. It didn't seem to make a difference. I've saved the trace into another gist: https://gist.github.com/gavinb/8afca1d2335f3c1939cb23c475fe5429

I noticed the following around the place where it says it's updating:
```
DEBUG:cargo::core::resolver: found an override for openssl-sys = 0.7.17
DEBUG:cargo::core::registry: load/mismatch https://github.com/sfackler/rust-openssl
DEBUG:cargo::sources::config: loading: https://github.com/sfackler/rust-openssl
TRACE:cargo::core::source: loading SourceId; https://github.com/sfackler/rust-openssl
    Updating git repository `https://github.com/sfackler/rust-openssl`
TRACE:cargo::sources::git::source: updating git source `GitRemote { url: "https://github.com/sfackler/rust-openssl" }`
```

Let me know if there's anything else I can try.

**Comment by alexcrichton** [comment]
Hm ok so the problem seems to be related to this line in the `[replace]` section:

```toml
"openssl-sys:0.7.17" = { git = "https://github.com/sfackler/rust-openssl" }
```

If that's removed then the spurious update doesn't happen. Definitely not related to #3220, still investigating.

**Comment by alexcrichton** [comment]
Ok, found the problem! -- https://github.com/rust-lang/cargo/pull/3248

**Comment by gavinb** [comment]
Verified your `bad2` branch fixes the problem. Thanks!
