### ISSUE TITLE
Feature request: Upload broken crate for getting help or reporting issues

### ISSUE THREAD

**Issue by casey** [rust-lang/cargo#3240]
It would be great if cargo had a sub command for uploading the current state of a crate, working or not, along with the output from running a cargo command.

The uploads would be available in some form which displayed the command run, the error, the browsable code of the crate, a zip containing the source code.

This would be helpful in a few different scenarios:
- getting help with a difficult to solve compile time error, like a borrow or lifetime issue
- getting help with a failing test
- reporting a bug in cargo or rust itself
- reporting a bug in a dependency

Imagining for a second that the command is called [`wat`](https://www.destroyallsoftware.com/talks/wat), an invocation would look like this:

```
$ cargo wat build
cargo wat: invoking `cargo build`...
   Compiling just v0.2.11 (file:///Users/rodarmor/src/just)
error: no method named `pusheen` found for type `std::string::String` in the current scope
    --> src/lib.rs:1601:18
     |
1601 |           str.pusheen(c);
     |               ^^^^^^^

error: aborting due to previous error

error: Could not compile `just`.

To learn more, run the command again with --verbose.
cargo wat: `cargo build` failed with exit code 101
cargo wat: uploading crate and output of `cargo build` to crates.io.....
done: https://crates.io/wats/11f36cb3438abdf
```

At that point could share it with someone who can help or open an issue with a link. The person who was helping could either diagnose the issue from the source code and error message, or download a zip of the the crate and debug it locally.

I think this would be especially nice given the current focus on helping out noobs and mentoring, since it would hopefully lower the barrier to getting help.

**Comment by alexcrichton** [comment]
I'd love to have this! I even love the name "wat" as well :)

I feel like we've discussed this before actually with @nikomatsakis about incremental compilation as well. Basically just some subcommand to upload the world so someone else could poke around later. I'd be a little hesitant to add it to Cargo proper for now but I could imagine that `cargo-wat` could be built as an external subcommand and then moved in if it's useful enough.

Also cc @jonathandturner, this could perhaps be a super useful tool for newbies as well.

**Comment by casey** [comment]
One reason to make it part of cargo proper is that it would likely use all the same code as `cargo publish`, and differing only by including an error message and making it available at a different url.

**Comment by casey** [comment]
Another random thought is that it would be very convenient to also have a command for downloading a wat archive for local debugging:

```
$ cargo wat --fetch 11f36cb3438abdf lifetime-problem
fetching https://crates.io/wats/11f36cb3438abdf.zip...
done
$ cd lifetime-problem
# ... fix all the problems ...
```

**Comment by alexcrichton** [comment]
Oh yeah it's true that it'd fit well in Cargo itself, and if it works well I'd be fine adding it eventually, I just figure that it should start externally first.

**Comment by casey** [comment]
Another idea for the name is `snapshot`. I'm sort of torn as to which is better. On the one hand `wat` is pretty funny, and but `snapshot` would probably be more self explanatory.

**Comment by nikomatsakis** [comment]
I think I wanted to call this `cargo wtf` ;)

**Comment by nikomatsakis** [comment]
Ah, except that I imagined it as a standalone command for basically filing a bug report with the code to reproduce. That is, not coupled with the execution of `build`. 

Regarding incremental, work on [that tool (called `cargo-incremental`)][ci] is proceeding. The way it works there is to track a local branch saving the state of each build. We haven't done the "file bug with error report" yet though.

[ci]: https://github.com/nikomatsakis/cargo-incremental/

**Comment by casey** [comment]
@nikomatsakis It would be ideal if it worked with any command. You might want to do `cargo wtf doc`, `cargo wtf run`, `cargo wtf test`, or `cargo wtf build`.

**Comment by nikomatsakis** [comment]
@casey yeah -- I agree this version is better. =) Also, `wat` is perhaps better than `wtf`. I like the idea of a playful name, anyway.

**Comment by carols10cents** [comment]
Given that we'd like this to start as an external command, I'm going to close this :) Love the idea though!
