### ISSUE TITLE
Cache build results per feature matrix for dependencies

### ISSUE THREAD

**Issue by dhardy** [rust-lang/cargo#3245]
Concrete example:

```
git clone https://github.com/maidsafe/routing.git && cd routing
cargo build
cargo build --features=clippy
cargo build
```
All three build commands causes many dependencies to be rebuilt from scratch. I would expect the third command not to rebuild dependencies which had already been built with the current feature matrix; currently toml, log4rs, maidsafe_utilities, crust and routing itself get rebuilt by the last build command.

Note that when switching release and debug builds, Cargo does cache dependency builds and not force a rebuild when switching.

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually the topic of https://github.com/rust-lang/cargo/pull/3102, which I believe should fix this

**Comment by dhardy** [comment]
Great!
