### ISSUE TITLE
Modifying a dependency of a target specification should recompile of all the relevant crates / Allow targets to express dependencies

### ISSUE THREAD

**Issue by ppannuto** [rust-lang/cargo#3252]
Similar in spirit to #2616, but one level of indirection further:

If I have something like
```
    "pre-link-args": [
        "-mcpu=cortex-m4", "-mthumb",
        "-mfloat-abi=soft",
        "-Wl,-gc-sections",
        "-Tlayout.ld"
    ],
```

If I modify the memory map `layout.ld`, I want things to rebuild.

Detecting all cases where a target specification depends on another file could very well be an intractable problem. It may make more sense to simply add a `dependencies` target option that accepts a list of files that cargo should check to see if a rebuild is necessary.

**Comment by alexcrichton** [comment]
There's probably a limit to what Cargo can realistically do here, unfortunately. Tracking https://github.com/rust-lang/cargo/issues/2616 is plausible but inspecting arguments to see what files they read is... maybe a bit far fetched.

**Comment by ppannuto** [comment]
Yeah, I think the more realistic approach was my second suggestion of letting people explicitly list files that Cargo should check whether they have changed. Would that be an amenable patch?

**Comment by alexcrichton** [comment]
Ah yeah, that sounds reasonable! You should be able to actually do that today build build scripts and `cargo:rerun-if-changed`

**Comment by ppannuto** [comment]
Ah, perfect. That did exactly what I needed.

A little cumbersome to have the indirection of a `build.rs` that just `println!`'s, but not the end of the world. Thanks!
