### ISSUE TITLE
'cargo run' should start building other crates in workspace as soon as possible.

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#3260]
When I do 'cargo run' on one exe in my workspace and on another, the second one doesn't actually start compiling after the first one finished. It only starts after the exe returns running. 
But I would like to run both exes at the same time, because they are server and client and have to communicate with each other. I'm developing both in lockstep so I always have to build and test both.

**Comment by matklad** [comment]
If your project has git dependencies, then this could be https://github.com/rust-lang/cargo/issues/3209. Can you check if you experience the same issue with the nightly Cargo?

**Comment by Boscop** [comment]
Ah, it seems to be working correctly now. I should have updated before...
