### ISSUE TITLE
Passing nonsense toolchain is silently ignored

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/cargo#3264]
If you want to build with a particular toolchain, you can pass it to the +:

```
cargo +stable build --release
```

Awesome.  Unfortunately, it will happily ignore any mistyped name you give it

```
cargo +stablle build --release
```

Seems like this should be an error

**Comment by alexcrichton** [comment]
I think this may be a rustup bug instead of a Cargo bug?

**Comment by jonathandturner** [comment]
Ah yis, I shall post over there
