### ISSUE TITLE
Install resources files with cargo install

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#3271]
`cargo install` already auto-downloads, builds and installs a crate. It would be handy if it could also install resources files, like images, html/js files...

**Comment by alexcrichton** [comment]
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/2729, but thanks for the report!

**Comment by Yamakaky** [comment]
Sorry, couldn't find something with "resource" in the title ^^
