### ISSUE TITLE
Rustc arguments order

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#3276]
The current order of the arguments to rustc is `rustc <source.rs> <args>`. When the source path is long, it's hard to see which process correspond to which crate. For example:
```
rustc .cache/cargo/registry/src/github.com-0a35038f75765ae4/bitflags-0.1.1/src/lib.rs --crate-name bitflags <args>
```
It's even worst if rustup is used, and `rustc` is a absolute path.

I propose that the arguments be reorganized like this:

```
rustc --crate-name bitflags .cache/cargo/registry/src/github.com-0a35038f75765ae4/bitflags-0.1.1/src/lib.rs <args>
```

**Comment by alexcrichton** [comment]
Thanks for the report! Could you expand on the rationale for this? I'm not sure why the argument order to rustc would matter...

**Comment by Yamakaky** [comment]
If you run `top -c`, it's easier to see which line does what in the second ordering. It's a cosmetic change, but it help monitoring the progress of the build, and see which dependency builds slowly.

**Comment by alexcrichton** [comment]
Ah that makes sense to me!

**Comment by ibabushkin** [comment]
I've written the code for this, I'll send a PR soon if that's still relevant :)

**Comment by alexcrichton** [comment]
Sure!

**Comment by Yamakaky** [comment]
Cool, thanks!

**Comment by Yamakaky** [comment]
I tried with a build from today, the problem is still there.

**Comment by alexcrichton** [comment]
I believe that all builds and such should have the right toolchain now (even rustup), @Yamakaky could you perhaps try again?

**Comment by Yamakaky** [comment]
It's good!
