### ISSUE TITLE
`cargo test` should build benches/*.rs

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#3277]
Today, running `cargo test` also builds examples in `examples/*.rs` but doesn’t run them. This helps ensure that they’re kept up to date when a library’s API changes. The same should be done for `benches/*.rs`, for the same reason.

It’s been a couple times now that html5ever have been found broken. This is because they’re not built in CI, so when making a breaking API change we don’t necessarily think of updating them. We could have CI run `cargo bench --no-run`, but that rebuilds the entire dependency graph with optimization, which would add significantly to the already-long CI times.

**Comment by alexcrichton** [comment]
Ideally, yeah, but benches are unstable (e.g. `extern crate test` and `test::Bencher`), so this'd be a breaking change to do by default. Also, we likely shouldn't do it until benchmarking is stable.

**Comment by SimonSapin** [comment]
Ok. Is there some way to make Cargo build (not run) `benches/*.rs` in the `dev` or `test` profile?

**Comment by alexcrichton** [comment]
Sure yeah we can make Cargo compile these pretty easily, my point is just that this isn't backwards compatible as it's break any project that only runs `cargo bench` on nightly because on stable `cargo test` would compile code starting with `#![feature(test)]`

**Comment by SimonSapin** [comment]
Right, I got your point about changing the default behavior causing breakage. So I’m changing my question to: is there some other command or argument that I can use to opt into that? If not, how do you feel about adding something?

**Comment by alexcrichton** [comment]
Oh right now I believe you can do `cargo test --bench <name>`, although there's no way to do that for all benchmarks all at once automatically

**Comment by SimonSapin** [comment]
Good to know, thanks! This is good enough for html5ever since there’s only one benchmark there: https://github.com/servo/html5ever/pull/237

Closing, as I’m not sure if it’s worth adding something else.
