### ISSUE TITLE
Ctrl+C on `cargo run`

### ISSUE THREAD

**Issue by alexreg** [rust-lang/cargo#3281]
When I Ctrl+C on `cargo run` and my Rust program is set up to intercept the signal, the Cargo process stops and returns control to the terminal, even though my Rust program may still be running. I've observed this on latest nightly.

I think it would be best for `cargo run` to also intercept Ctrl+C when running a program, and ignore it – instead, it should just check regularly to see if the program it's running has exited. This would certainly be a more reliable approach.

**Comment by alexcrichton** [comment]
I believe this was fixed by https://github.com/rust-lang/cargo/pull/2818, so I'm curious, which version of Cargo were you running?

**Comment by alexreg** [comment]
The very latest.

rustc 1.14.0-nightly (cae6ab1c4 2016-11-05)

**Comment by alexcrichton** [comment]
Oh are you using rustup? If so then that's the same wrapper problem so this'd actually be a rustup bug at that point.

**Comment by alexreg** [comment]
Ah, fair point. Sorry about that. Do you know if it's already been reported for Rustup?

**Comment by alexcrichton** [comment]
AFAIK no

**Comment by Vlad-Shcherbina** [comment]
This still happens on Windows.

### Steps to reproduce
1. Create the following program:
    ```rust
    // [dependencies]
    // ctrlc = "*"
    fn main() {
        ctrlc::set_handler(move || {
            println!("Ctrl-C received, but I'm not exiting.");
        });
        loop {}
    }
    ```
2. `cargo run` (where cargo is rustup)
3. Press `Ctrl-C`.

### Expected result
The program should print `Ctrl-C received, but I'm not exiting.` and continue running.

### Actual result
The program terminates.

### Version info
```
> rustup --version
rustup 1.18.3 (435397f48 2019-05-22)
```

---------------

I tried it without (`C:\Users\username\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo.exe run`). It works as expected.

Cargo itself used to have this problem before (https://github.com/rust-lang/cargo/issues/4575), but it was solved with this workaround: https://github.com/rust-lang/cargo/pull/6004.
