### ISSUE TITLE
`--message-format` is released ahead of time

### ISSUE THREAD

**Issue by White-Oak** [rust-lang/cargo#3282]
Message formats introduced in #3000 were supposed to be in the next stable release (see [this comment](https://github.com/rust-lang/cargo/pull/3000#issuecomment-252644295)).

But it looks like it jumped from nightly to stable immediately. Is is this supposed to be so?

**Comment by alexcrichton** [comment]
Yeah we unfortunately had to accelerate the Cargo release due to releasing the curl/OpenSSL security fixes. As a result other features landed before that were included implicitly as well.
