### ISSUE TITLE
Differentiate between last version yanked and entire crate yanked

### ISSUE THREAD

**Issue by casey** [rust-lang/cargo#3285]
Currently, if you `cargo publish` a few versions and then yank the last one, crates.io will display an error message [like this one](https://crates.io/crates/c) whose wording suggests that the entire crate has been yanked.

I ran into this when I accidentally published a version I didn't intend to, then yanked it, and then had to publish a new version so that users wouldn't think that the entire crate was gone for some reason.

I would suggest differentiating between yanking a crate and yanking an individual version.

For example by adding `cargo yank --crate` as opposed to the existing `cargo yank --vers VERSION`.

Yanking a crate would display an error message with the existing wording at `https://crates.io/crates/$CRATE_NAME`.

Yanking a version would only display an error message for `https://crates.io/crates/$CRATE_NAME/$YANKED_VERSION`, or if the yanked version is the only version of the crate.

If someone navigates to `https://crates.io/crates/$CRATE_NAME`, and the last version has been yanked, it would display the last un-yanked version.

**Comment by alexcrichton** [comment]
I think this is actually a [separate bug](https://github.com/rust-lang/crates.io/issues/76), perhaps?

**Comment by casey** [comment]
Yup, looks like the same bug. Closing.
