### ISSUE TITLE
Incorrect RUSTFLAGS parsing

### ISSUE THREAD

**Issue by lucab** [rust-lang/cargo#3287]
It looks like [env_args() is blindly splitting env args on spaces](https://github.com/rust-lang/cargo/blob/0.14.0/src/cargo/ops/cargo_rustc/context.rs#L761-L767), making `-C link-args` impossible to use. 

This happens when trying to use multiple linker args:
```
$ rustc -C help | grep link-args
    -C         link-args=val -- extra arguments to pass to the linker (space separated)

$ RUSTFLAGS='-C link-args="-fPIE -pie -Wl,-z,relro -Wl,-z,now"' ./target/release/cargo build --verbose
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name _ --print=file-names -C link-args="-fPIE -pie -Wl,-z,relro -Wl,-z,now" --crate-type bin --crate-type rlib --target x86_64-unknown-linux-gnu` (exit code: 101)
--- stderr
error: Unrecognized option: 'p'.
```

Output above is from current master (0.15.0-pre).

**Comment by alexcrichton** [comment]
Thanks for the report! This is working as expected, however, as this is defined behavior of how `RUSTFLAGS` is parsed. You can work around this, however, with `.cargo/config` which supports spaces in paths.

**Comment by alexcrichton** [comment]
er, spaces, in arguments*

**Comment by lucab** [comment]
While I understand the dotfile feature, I'm a bit puzzled on the UX side of this. 

How are scripts supposed to pass existing/dynamic environmental `$LDFLAGS` to cargo/rustc? Especially when those are inherited though makefile or similar automation tools, I can't envision doing  dotfile manipulation all the times.

Is there any other way which doesn't require going back and forward through user files?

**Comment by alexcrichton** [comment]
In some sense `$LDFLAGS` is a bash-ism (or shell-ism), and Cargo isn't a shell, so interpretation is inevitable no matter what. With more recent versions of rustc you can split `$LDFLAGS` on spaces and pass each as `-Clink-arg=$foo` (note the `link-arg`, not `link-args`).

**Comment by lucab** [comment]
Thanks for the answer, that's indeed a good way forward! For readers from the future, recent here means `>= 1.13.0`.

With the answer at hand, it was easier finding references (which I'm dumping here for cross-linking):
 * RFC: https://github.com/rust-lang/rfcs/pull/1509
 * PR: https://github.com/rust-lang/rust/pull/36574
 * Release notes: https://github.com/rust-lang/rust/blame/1.13.0/RELEASES.md#L18
