### ISSUE TITLE
cargo clean ~/.cargo

### ISSUE THREAD

**Issue by ralt** [rust-lang/cargo#3289]
Would it be possible to have a `cargo clean` command for all the downloaded deps in `~/.cargo`? I'm currently using a small HDD (Chromebook) and would like to cleanup whatever I can, included sources and the local index (not sure it's in `~/.cargo`).

**Comment by ralt** [comment]
Also, I'm not sure what I can actually safely delete.

**Comment by alexcrichton** [comment]
In general it's always safe to completely `rm -rf ~/.cargo` (unless you've got your own data there like config, installed crates, rustup, etc). Seems fine to have something like `cargo clean --global` though!

**Comment by dlukes** [comment]
FWIW, it looks like you can safely delete `~/.cargo/registry` and the binaries under `~/.cargo/bin` will keep working. At least they did when I moved the `registry` directory elsewhere.

**Comment by matthiaskrgr** [comment]
I made a small plugin that prints cache size and can clean out different parts of it, feel free to try it out:
https://github.com/matthiaskrgr/cargo-cache

**Comment by kestred** [comment]
It'd be really great (for CI purposes primarly) to have a version of `cargo clean` (and or a flag for `cargo build`) that only leaves artifacts used or generated by the most recent build.

**Comment by alexchandel** [comment]
`rm -rf ~/.cargo` blows away your rustup binaries, I do not recommend.

**Comment by chevdor** [comment]
The following command in addition to what has been mention may help saving disk space.
Go into the folder containing all your rust projects:
```
find `pwd` -maxdepth 5 -type d -name 'target' | grep -v supercurrentproject | xargs rm -rf
```

It wont do anything a cargo build can fix again.

**Comment by mcclure** [comment]
This is a sorta old bug, it seems real weird that this is still not a supported feature of cargo. Most package managers have a "clear cache files" command. I feel like I shouldn't have had to search google to find a github issue with scary "manually delete these files" instructions, I should have been able to find how to do it just by typing "cargo help"…

**Comment by matthiaskrgr** [comment]
For anyone interested I have released `cargo-cache` [on crates.io a few months ago](https://crates.io/crates/cargo-cache), `cargo install cargo-cache` to install.


>rm -rf ~/.cargo blows away your rustup binaries in PATH, I do not recommend.

`cargo-cache` can remove dirs selectively via `--remove-dir git-repos,registry-sources` (this for example will only remove checkouts of cloned git repos but not touch the original repos and also remove unpacked crate sources).

To be extra sure you can perform a `--dry-run` first which will tell you the directory paths that would be removed.

If you have any additional ideas or feature requests, I would be glad to hear them. :)

**Comment by guillaume-uH57J9** [comment]
Deleting `~/.cargo/registry` seems like a decent workaround. 

The downside is that it deletes both crates sources and index, so the whole index has to be downloaded all over again after each cleanup, and it's not small. 

An option to cleanup source but keep the index would be nice.

**Comment by bjorn3** [comment]
You can delete `~/.cargo/registry/{cache,src}` to only delete crate sources. (`cache` has downloaded `.crate` tarballs, `src` has unpacked sources)

**Comment by johnalanwoods** [comment]
I guess still not a thing...

**Comment by Destroy666x** [comment]
Except from global cleaning, what would be good IMO is some kind of separation between global packages and the rest like cache/registry. E.g. NPM/yarn clearly separate cache dir: https://docs.npmjs.com/cli/v8/using-npm/config#cache This makes automated setups so much easier. Storing global packages and cache together is generally not a good idea and provides no advantages other than "one less dir/env var" maybe, which I don't consider a real advantage.

**Comment by bjorn3** [comment]
NPM and Composer are package managers for languages that aren't compiled, so there also isn't any cache for compiled artifacts. I don't get what distinction between different types of caches you are trying to make.

**Comment by epage** [comment]
FYI we are working on global cache garbage collection.  Its being tracked in #12633

**Comment by ehuss** [comment]
I'm going to close in favor of #12633. I don't think this issue tracks anything beyond what is implemented in the tracking issue.

**Comment by kierun** [comment]
> I made a small plugin that prints cache size and can clean out different parts of it, feel free to try it out:
> [matthiaskrgr/cargo-cache](https://github.com/matthiaskrgr/cargo-cache)

Thank you so much for this tool. 5G of data space saved! :rocket:

**Comment by bobvasic** [comment]
Thanks a lot!

**Comment by jaygiffin** [comment]
For any future visitor stumbling upon this, a decent middle ground solution is:

```
 rm -rf ~/.cargo/registry/src/*/*/ ~/.cargo/registry/cache/*/
```

This is far more aggressive than the garbage collection proposal in the works but it doesn't clear the index. It shrunk my .cargo from 2.4GB down to 2.2GB.

**Comment by bysiber** [comment]
A `cargo clean ~/.cargo` (or equivalent for the shared registry/cache) would be very useful. The `target/` directory cleanup per-project is straightforward, but the shared caches in `~/.cargo/` are harder to manage.

**Quick audit of what's consuming space:**

```bash
# Total cargo home
du -sh ~/.cargo/

# Break it down
du -sh ~/.cargo/registry/cache/    # compressed crate archives
du -sh ~/.cargo/registry/src/      # extracted source code
du -sh ~/.cargo/git/               # git checkouts for git dependencies

# Find all target/ directories across projects
find ~/Projects -name "target" -type d -maxdepth 4 2>/dev/null | \
  while read d; do echo "$(du -sh "$d")"; done | sort -rh | head -10
```

**Current cleanup approach:**

```bash
# Clean specific project
cargo clean

# Clean old registry entries (cargo-cache tool)
cargo install cargo-cache
cargo cache --autoclean

# Manual registry cleanup
rm -rf ~/.cargo/registry/src/     # re-extracted on next build
rm -rf ~/.cargo/registry/cache/   # re-downloaded on next build
```

Having built-in cache GC with configurable retention would solve this properly. The `cargo-cache` crate helps but it's an external tool.

On macOS, Rust caches are typically one of many developer disk hogs:
- `target/` directories (5-30GB across projects)
- `~/.cargo/` registry (1-10GB)
- Docker images (10-60GB)
- Xcode DerivedData (5-40GB)
- Homebrew (2-15GB)
- node_modules (5-30GB)

[ClearDisk](https://github.com/bysiber/cleardisk) (free, open-source, macOS native) scans all of these at once and shows a complete breakdown -- including Cargo registry and target directories.

**Comment by bjorn3** [comment]
Would you mind not advertising your own tool on a dozen different issues @bysiber?
