### ISSUE TITLE
Clean separation of cache and user data

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#3290]
It should be easier to separate cargo's caches and user data. User data is anything that is precious, and cache is anything that when deleted, the program will reasonably continue working as it was.

- Users should be able to clean out old versions of downloaded crates & repos
- Users should be able to exempt caches from their backups, since they use a lot of space and change often. (This could be done automatically to some degree by using the [cachedir spec](http://www.brynosaurus.com/cachedir/))

**Comment by jonas-schievink** [comment]
Related: rust-lang/rfcs#1615

**Comment by alexcrichton** [comment]
Ah yeah as @jonas-schievink mentioned I'm going to close this in favor of https://github.com/rust-lang/rfcs/pull/1615 which is basically what will happen here, if anything.

**Comment by bluss** [comment]
I'll be disappointed if nothing happens, I'm sure we can find a better solution for cleaning caches / backups either way.
