### ISSUE TITLE
Unexpected dependency resolution when using ">"

### ISSUE THREAD

**Issue by stusmall** [rust-lang/cargo#3292]
I ran into this because an upstream project is using > in one of their dependencies.  This ended up causing a major issue for me because cargo would ignore it and get the newest package.  I have an example of this behavior here: https://github.com/stusmall/broken_dep

I declare openssl-sys = "> 0.7.0" but cargo gives me v0.9.1.  

I don't know if > is an acceptable operator.  If it is I would expect for it to pull down 0.7.17, if it isn't an acceptable operator I would expect a fatal error for an malformed version string.

**Comment by steveklabnik** [comment]
> I don't know if > is an acceptable operator.

It is, yes: http://doc.crates.io/specifying-dependencies.html#inequality-requirements

> If it is I would expect for it to pull down 0.7.17

Why? `0.9.0` is greater than `0.7.0`, and `0.7.17` is less than `0.9.0`.

**Comment by stusmall** [comment]
Oh my gosh,  this is what happens.  When I try to enter bugs before proper coffee..... I tried to reduce it down to the smallest project to produce but I reduced down to the point I lost sight of the actual issue.  :)

I've updated the project to show the problem better.  There is a dependent crate ("library") that declares:
openssl-sys = "> 0.7.0"
but the main crate declares openssl-sys = "0.7".  I would expect 0.7.17 but it fails to build with the error:

error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.7.17
  openssl-sys v0.9.1

**Comment by steveklabnik** [comment]
Right. So `>0.7.0` resolves to the newest version greater than 0.7.0, which is `0.9.0`. The `0.7` is `^0.7`, which will match like `>= 0.7.0 < 0.8.0`, which gives `0.7.17`. Hence the conflict.

**Comment by stusmall** [comment]
Oh sorry for the misunderstanding.  Is there a way to force the project to use just one common version of openssl-sys?  I thought that pinning to a version in my cargo.toml will cause it to use this version if possible.  

Is the only way to change the restraints on a dependent project to change that project's cargo.toml?

**Comment by steveklabnik** [comment]
>  I thought that pinning to a version in my cargo.toml will cause it to use this version if possible. 

So, Rust supports having multiple versions of transitive dependencies installed. If `openss-sys` _didn't_ link to a native library, then you'd get two versions of it and everything would Just Work.

> Is the only way to change the restraints on a dependent project to change that project's cargo.toml?

Yes. I would argue that `> 0.7.0` is a very bad bound, and should be just `0.7.0`. You should send them a PR for it, and in the meantime, you can use [an override](http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies) to use your forked version in the meantime.

Anyway, giving this a close as it's not a bug! Let's continue discussing stuff in the users' forum thread you started if you have more problems 😄

**Comment by stusmall** [comment]
Thank you!
