### ISSUE TITLE
rustdoc: Show package version in the generated documentation when invoked through `cargo doc`

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#3295]
It would be useful for users to know for which version of a package they are reading the documentation for.

This would be especially helpful in identifying outdated documentation online, which there is an abundance of.

Moved from https://github.com/rust-lang/rust/issues/29275 due to request.

**Comment by alexcrichton** [comment]
Does rustdoc have the ability to do this? AFAIK we'd need to expose a flag to rustdoc first.

**Comment by crumblingstatue** [comment]
I don't think rustdoc has the ability to do this, which is why I opened this issue at rust-lang/rust, but @steveklabnik closed the issue there, requesting it to be moved here.

**Comment by alexcrichton** [comment]
Ok... well it's at least a todo item here!

**Comment by steveklabnik** [comment]
I thought rustdoc had the ability to control output directly already; in the end, even if rustdoc needs some support, it will need cargo to actually do the right thing here, since rustdoc can't know version info.

**Comment by ehuss** [comment]
This has been implemented, stabilization is tracked in #7907.
