### ISSUE TITLE
Fixing the toolchain in Cargo.toml

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#3298]
It would be nice for those working with particular snapshots of nightly if it would be possible to fix the toolchain in the Cargo.toml file, e.g., something like:

```
[toolchain]
channel = nightly
date = 2016-11-13
host = x86_64-apple-darwin
```

and if cargo would use `rustup` to get the appropriate toolchain.

**Comment by alexcrichton** [comment]
This is similar to https://github.com/rust-lang/cargo/issues/2751 which has some more comments: https://github.com/rust-lang/cargo/issues/2751#issuecomment-222812947.

The tl;dr; is that I don't think this'd be too useful to add to Cargo right now. Cargo doesn't manage toolchains, so it'd basically ignore this configuration most of the time.

**Comment by gnzlbg** [comment]
Indeed, I'll close this and repost there instead. Thanks!
