### ISSUE TITLE
different feature sets use the same output directory ($OUT_DIR)

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#3302]
they should use different output directory so build scripts that generate files whose contents vary with Cargo features will work correctly (otherwise you will only one instance of such files across different builds that use different feature sets)

cc @alexcrichton

**Comment by japaric** [comment]
Example where you can observe this bug:

```
$ tail -n5 Cargo.toml
build = "build.rs"

[features]
a = []
default = ["a"]

$ cat build.rs
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let outfile = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("foo.txt");

    writeln!(File::create(outfile).unwrap(),
             "{:?}",
             env::var_os("CARGO_FEATURE_A")).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}

$ cargo clean

$ cargo build

$ cat **/foo.txt
Some("1")

$ cargo build --no-default-features

$ cat **/foo.txt
None

$ cargo build

# Expected `Some("1")`!
$ cat **/foo.txt
None
```

**Comment by japaric** [comment]
To elaborate: The second `cargo build` command doesn't run the build script and that's fine. The problem is that both feature sets, "a" (the default) and "" (no-default-features), use the same $OUT_DIR so the `cargo build --no-default-features` command overwrites the `foo.txt` file that `cargo build` generated.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/cargo/pull/3310
