### ISSUE TITLE
Does not produce coloured output on FreeBSD over SSH

### ISSUE THREAD

**Issue by alexreg** [rust-lang/cargo#3307]
I'm not sure about a physical (non-SSH) shell, but over SSH Cargo does not colour it's output at all, on FreeBSD 10.3. My `TERM` env var has value `xterm-256color`, if that's relevant.

**Comment by alexcrichton** [comment]
cc @Stebalien, perhaps related to the term crate?

**Comment by Stebalien** [comment]
Yes (https://github.com/Stebalien/term/issues/44). A work-around is to copy a compiled `xterm-256color` terminfo database from a non-freebsd machine (linux or macos) into `~/.terminfo/x/xterm-256color` (or `/usr/share/terminfo/x/xterm-256color` if you have root on the target machine).

**Comment by alexreg** [comment]
Work-around does the job for now, thanks!

**Comment by carols10cents** [comment]
So [cargo is using termcolor rather than term now](https://github.com/rust-lang/cargo/pull/4162), which makes this issue moot. If there are problems with termcolor, please open new bugs! Thanks!!

**Comment by alexreg** [comment]
Sounds good, thanks!
