### ISSUE TITLE
.cargo/config path override & crates with optional deps broken

### ISSUE THREAD

**Issue by vvuk** [rust-lang/cargo#3313]
If a crate has an optional dependency, and it's ever used a .cargo/config, the optional dependency is always reported as a changed dep.  STR:

1. Pull https://github.com/servo/webrender
2. Pull https://github.com/vvuk/dwrite-rs
3. Set up path override to dwrite-rs
4. Build in webrender/sample

Results in:
```
warning: path override for crate `dwrote` has altered the original list of
dependencies; the dependency on `serde_derive` was either added or
modified to not match the previously resolved version
```

(Note -- dwrite-rs is only used on Windows; for purposes of this, it should be possible to modify the Cargo.toml's in webrender to require it on all platforms... but a similar issue can likely be seen in many other crates.)

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/cargo/pull/3336
