### ISSUE TITLE
Enable setting crate type on bins

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#3314]
This is currently sort of supported like so:

```
bin = []

[package]
...

[lib]
path = "src/main.rs"
crate-type = ["bin", "dylib"]
```

This breaks `cargo run` though (“error: a bin target must be available for cargo run”).

Rationale: I'd like to be able to use `extern crate my_crate` in integration tests for my binary crate. With the setup above I can run tests using `RUSTFLAGS="-C prefer-dynamic -C rpath" cargo test`.

**Comment by alexcrichton** [comment]
Hm if the library needs to be tested, couldn't the unit tests either be in that binary or the library for the binary extracted to its own project?

**Comment by est31** [comment]
For a tool in lewton, I have used both a lib.rs and a main.rs and separated the crate into two so to say: https://github.com/est31/lewton/blob/0.4.1/dev/cmp/Cargo.toml

**Comment by carols10cents** [comment]
Separating into a src/lib.rs and a src/bin.rs is the recommended way to do this, so I'm closing this issue. Thanks!
