### ISSUE TITLE
Cargo search not displaying `just` crate

### ISSUE THREAD

**Issue by casey** [rust-lang/cargo#3317]
This is a little mysterious, cargo isn't returning any hits when searching for the `just` crate:

```
$ cargo search just
    Updating registry `https://github.com/rust-lang/crates.io-index`
$
```

Other searches are working fine:

```
$ cargo search regex
    Updating registry `https://github.com/rust-lang/crates.io-index`
regex (0.1.80)           An implementation of regular expressions for Rust. This implementation uses finite automata and guarantees linear time matching…
verex (0.2.2)            This crate provides a Rust implementation of VerbalExpressions in order to build regex strings without knowing the minutiae of …
...
```

**Comment by alexcrichton** [comment]
Cargo's just using the search API on crates.io, so this is unfortunately likely just a crates.io issue

**Comment by ducks** [comment]
I believe `just` is a default stopword for postgres.

iirc, I've seen an issue floating around about a `which` crate not being found on search.

**Comment by casey** [comment]
Found it: github.com/rust-lang/crates.io/issues/321

**Comment by casey** [comment]
I'll comment there. Thanks for the pointers!
