### ISSUE TITLE
Fail gracefully when out of storage space

### ISSUE THREAD

**Issue by lilred** [rust-lang/cargo#3322]
I tried installing YouCompleteMe with Racer autocomplete. The installation hung partway through, and it took me a little while to figure out what was wrong.

Turns out I'm out of storage space.

It would be nice if Cargo failed with an error message when out of memory.

**Comment by alexcrichton** [comment]
Do you have a gist of the error that Cargo emitted? If we're hiding information we should definitely emit it!

**Comment by lilred** [comment]
No error was emitted to `stdout`, are they recorded somewhere else?

**Comment by alexcrichton** [comment]
Errors are typically emitted to stderr, but was that empty as well?

**Comment by lilred** [comment]
I didn't see any command-line output, the only thing that happened is that
the package installation hung.

(I could be wrong, maybe it's just a package that takes more than ten
minutes to install. It was `iron-hmac`. I doubt it though, it would be one
hell of a coincidence for me to run out of space at the exact same moment.)

**Comment by alexcrichton** [comment]
Hm so I *believe* that Cargo should always report some error when storage runs out of space, so without a reproduction I'm not sure how to close this :(

**Comment by lilred** [comment]
Close it as "no repro" or something, I'll re-open if I encounter that issue again.
