### ISSUE TITLE
Failure linking against native Windows libraries in a crate that builds both library and executables

### ISSUE THREAD

**Issue by StrayLightning** [rust-lang/cargo#3327]
This problem relates to linking against native libraries on Windows when building multiple targets in a crate.  I am using Rust 1.13.0.

I have a project which I have just converted from a crate that produces a single executable to one that produces a library (most of the code) and three executables (so that the executables can share the library code.)

I have prepared a git repo with a demonstration:
https://github.com/StrayLightning/problematic

For comparison, here is a repo with a crate that builds a single executable, representing my project before the refactor, which works fine:
https://github.com/StrayLightning/notproblematic

The project links against a static build of OpenHMD, which in turn requires SetupAPI.lib from the Windows SDK to be linked.  The build.rs specifies (on Windows):

    println!("cargo:rustc-link-lib=static=openhmd");
    println!("cargo:rustc-link-lib=static=hidapi");
    println!("cargo:rustc-link-lib=static=setupapi");
    println!("cargo:rustc-link-search=native=./lib-win");

Problem 1: When linking the executables the library search paths are correctly specified, but not the libraries from build.rs to link against.  Required entrypoints are therefore missing and the link fails.

Problem 2: Delete lib-win\setupapi.lib to see this problem.  When building the library code, Cargo specifies the static libraries to link against, and my local library path, but not the Windows SDK library search paths that it normally does when linking an executable.  So it fails to find the requested SetupAPI.lib from the Windows SDK.

I have searched for some build.rs or Cargo.toml magic to work around these issues, but to no avail. It seems as if Cargo is not specifying the link libraries and library paths at the right times:

* When linking an executable, the libraries specified in the build.rs are missing (Problem 1)
* When building the library, the native libraries specified in the build.rs are included but not the normal library path used when linking an executable (Problem 2)

**Comment by retep998** [comment]
>When building the library, the native libraries specified in the build.rs are included but not the normal library path used when linking an executable (Problem 2)

1. Don't use kind=static.
2. Seriously, do __not__ use kind=static.
3. Always use kind=dylib instead (and sometimes kind=static-nobundle when it is eventually implemented)

So basically, do `println!("cargo:rustc-link-lib=dylib=setupapi");`. `link.exe` knows where the Windows SDK is (either due to `LIB` or because `rustc` told it), so as long as you use kind=dylib, the library will be passed directly to the linker and everything is fine.

**Comment by StrayLightning** [comment]
Aha, thanks.

println!("cargo:rustc-link-lib=dylib=setupapi");
Schoolboy error...!  setupapi.lib is the import library the DLL. I've never liked Windows' dynamic library system.

println!("cargo:rustc-link-lib=dylib=hidapi");
But this I don't understand when hidapi.lib is a static library.  I am clearly not understanding the kind specification.

But thank you again.  I'm closing this as I have confirmed that changing everything to dylib works for my full project.

**Comment by retep998** [comment]
>But this I don't understand when hidapi.lib is a static library. I am clearly not understanding the kind specification.

It's because Rust chose to make the naming not correspond to what it is actually doing. `kind=dylib` means to pass the library to the linker while `kind=static` means to bundle the library into the rlib which can cause all sorts of issues and is never necessary (unless you're distributing an rlib over the internet and you _need_ the library bundled into the rlib).

**Comment by StrayLightning** [comment]
Thank you.  Yes, that understanding makes all the difference to comprehending the documentation.  It is not entirely clear that this refers to the same thing: https://doc.rust-lang.org/nightly/book/ffi.html#linking  The Cargo documentation that I've read doesn't really address the kind parameter for rustc-link-lib.
