### ISSUE TITLE
Nightly regression: The SSL certificate is invalid

### ISSUE THREAD

**Issue by cuviper** [rust-lang/cargo#3340]
We're having cargo trouble on rust-num/num#243, and it appears to be a new regression in the nightly.  Note [the initial Travis build succeeded](https://travis-ci.org/rust-num/num/jobs/179513752), which was using `cargo 0.16.0-nightly (b26d672 2016-11-25)`.  Then [several](https://travis-ci.org/rust-num/num/jobs/179552072) [homu](https://travis-ci.org/rust-num/num/jobs/179553991) [builds](https://travis-ci.org/rust-num/num/jobs/179555817) have all failed using `cargo 0.16.0-nightly (3568be9 2016-11-26)`.

```
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to load source for a dependency on `rand`
Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  [16/-17] The SSL certificate is invalid
```

I confirmed the error locally after updating to the same cargo, running on Fedora 25.

**Comment by brson** [comment]
Lots of people reporting this problem today. cc @alexcrichton

**Comment by brson** [comment]
On IRC camlorn said the workaround for https://github.com/rust-lang/cargo/issues/598 worked for this too.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/cargo/pull/3342

**Comment by cuviper** [comment]
FWIW, that #598 workaround isn't quite right for Fedora 25 -- instead it's `SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt`, which is actually a symlink to `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`.

**Comment by tbu-** [comment]
The new nightly doesn't include the new Cargo, maybe the nightly build of Cargo is broken?

```
$ rustup show 
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.15.0-nightly (1c448574b 2016-11-28)
```

```
$ cargo --version
cargo 0.16.0-nightly (3568be9 2016-11-26)
```

**Comment by alexcrichton** [comment]
A new rust nightly didn't go out, so a new Cargo nightly didn't go out. The fix isn't in nightlies.

**Comment by bunnybooboo** [comment]
This is also experienced in Arch Linux rolling release. Pretty excited to come find there's a fix on the way.

**Comment by tbu-** [comment]
New nightly doesn't contain a new cargo, still from 2016-11-26, rustc is from 2016-12-01.

**Comment by alexcrichton** [comment]
Ah I can't believe I forgot about that, this is now a rustup issue -- https://github.com/rust-lang-nursery/rustup.rs/issues/844

**Comment by sanmai-NL** [comment]
Could you (I think @alexcrichton and @brson) please also do a postmortem on this issue? From what I can see the bug was introduced in `libgit2-sys`, which was then tagged `0.6.5` but but not tested. In what places can some more basic tests be added? E.g. testing against a locally running https Git server hosting a crates index seems very useful?

**Comment by alexcrichton** [comment]
@sanmai-NL yes I can try to write something up when everything is working again. Unfortunately I don't know how to test this, it's a very specific issue that seems like it could greatly complicate the test infrastructure naively at least.
