### ISSUE TITLE
Support comma-separation of features

### ISSUE THREAD

**Issue by dhardy** [rust-lang/cargo#3360]
```
$ cargo test --features=use-mock-crust,clippy
error: Package `routing v0.25.1 [...]` does not have these features: `use-mock-crust,clippy`
```
Please don't tell me a comma is a valid part of a feature name. Cargo should split on comma to enable `--features=a,b,c` as well as `--features="a b c"`.

**Comment by aochagavia** [comment]
This should probably be closed now after (see https://github.com/rust-lang/cargo/pull/4084)

**Comment by alexcrichton** [comment]
Indeed!
