### ISSUE TITLE
cargo run: exit on signals not communicated

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/cargo#3367]
Simple example crate that segfaults:
```
fn main() {
    unsafe {
        println!("{}", *(0 as *mut i32));
    }
}
```
Running it:
```
$ cargo run
   Compiling rust-test v0.1.0 (file:///home/gbr/devel/rust-test)
    Finished debug [unoptimized + debuginfo] target(s) in 0.14 secs
     Running `target/debug/rust-test`
$ target/debug/rust-test
[1]    7789 segmentation fault  target/debug/rust-test
```
It would be nice to have the exit by signal communicated back by Cargo, otherwise this looks like everything went fine.

BTW, the exit codes as given by `$?` are `1` for `cargo run` and `139` for direct invocation.

**Comment by alexcrichton** [comment]
Our of curiosity, what version of Cargo are you using?

**Comment by alexcrichton** [comment]
Oh actually, I believe this is a rustup, not a Cargo issue. Could you open an issue at rust-lang-nursery/rustup.rs?

**Comment by birkenfeld** [comment]
Ah. Right, cargo is wrapped yet again.

**Comment by eddyb** [comment]
Is there a different issue for this problem but when `cargo` runs `rustc`?
That is, `cargo test -v` shows `rustc` dying from a signal, but if I remove `-v`, that's not mentioned and all I can see is `error: build failed`.

**Comment by alexcrichton** [comment]
@eddyb if Cargo doesn't print out information like that by default that's definitely a bug! Do you know how to reproduce it?

**Comment by eddyb** [comment]
@alexcrichton sure, put `unsafe { *(1 as *const u8) = 0; }` in a proc macro and use it.
That should segfault the compiler. What I was hitting was `SIGPIPE`, but this should be similar.

**Comment by ehuss** [comment]
If you mean that it should always show the complete error if it was killed by a signal, then the following should do the trick:

```diff
diff --git a/src/cargo/core/compiler/mod.rs b/src/cargo/core/compiler/mod.rs
index 59834c40..a2b5d8d5 100644
--- a/src/cargo/core/compiler/mod.rs
+++ b/src/cargo/core/compiler/mod.rs
@@ -5,13 +5,14 @@ use std::io::{self, Write};
 use std::path::{self, Path, PathBuf};
 use std::sync::Arc;
 
+use failure::Error;
 use same_file::is_same_file;
 use serde_json;
 
 use core::manifest::TargetSourcePath;
 use core::profiles::{Lto, Profile};
 use core::{PackageId, Target};
-use util::errors::{CargoResult, CargoResultExt, Internal};
+use util::errors::{CargoResult, CargoResultExt, Internal, ProcessError};
 use util::paths;
 use util::{self, machine_message, Freshness, ProcessBuilder, process};
 use util::{internal, join_paths, profile};
@@ -275,6 +276,18 @@ fn rustc<'a, 'cfg>(
             }
         }
 
+        fn internal_if_simple_exit_code(err: Error) -> Error {
+            if err
+                .downcast_ref::<ProcessError>()
+                .as_ref()
+                .and_then(|perr| perr.exit.and_then(|e| e.code()))
+                .is_none()
+            {
+                return err;
+            }
+            Internal::new(err).into()
+        }
+
         state.running(&rustc);
         if json_messages {
             exec.exec_json(
@@ -284,13 +297,14 @@ fn rustc<'a, 'cfg>(
                 mode,
                 &mut assert_is_empty,
                 &mut |line| json_stderr(line, &package_id, &target),
-            ).map_err(Internal::new)
+            )
+            .map_err(internal_if_simple_exit_code)
             .chain_err(|| format!("Could not compile `{}`.", name))?;
         } else if build_plan {
             state.build_plan(buildkey, rustc.clone(), outputs.clone());
         } else {
             exec.exec_and_capture_output(rustc, &package_id, &target, mode, state)
-                .map_err(Internal::new)
+                .map_err(internal_if_simple_exit_code)
                 .chain_err(|| format!("Could not compile `{}`.", name))?;
         }
```

If that's what you meant, I can make that a PR.

**Comment by eddyb** [comment]
@ehuss Is there logic for doing that for `cargo run`, elsewhere in Cargo?

I think that's what I mean, though.

**Comment by alexcrichton** [comment]
@ehuss ah yeah that makes sense how we make those errors "internal" for now, and it definitely makes sense to me that any abnormal exit like that should not be considered internal but rather relevant information!

@ehuss do you want to send a PR?

**Comment by ehuss** [comment]
Posted at https://github.com/rust-lang/cargo/pull/6270
