### ISSUE TITLE
Release cargo/src/cargo/util/shell_escape.rs independently

### ISSUE THREAD

**Issue by ghost** [rust-lang/cargo#3374]
I'd love to be able to use shell escapes in contexts other than Cargo.

I'm using a a copy of an old version of that file in Thrussh, when doing an ssh exec request, which is a remote command without opening a shell.

How about a shell_escape crate, which would be used by Cargo instead of this file?

**Comment by alexcrichton** [comment]
Seems fine to me! I may not get around to this soon but if someone else would like to do so I wouldn't mind adding a dep to Cargo.

**Comment by sfackler** [comment]
@alexcrichton Should this live in this repo or can I just yank it into a new one?

**Comment by alexcrichton** [comment]
@sfackler be my guest!
