### ISSUE TITLE
build from source fails configure

### ISSUE THREAD

**Issue by 2114L3** [rust-lang/cargo#3375]
ArchLinux 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux
rustc 1.13.0 (from pacman)
cmake version 3.6.3
/bin/python is Python 3.5.2 (default, Nov  7 2016, 11:31:36) 
curl 7.51.0 (x86_64-pc-linux-gnu) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.8.0

commands;
```
git clone --recursive https://github.com/rust-lang/cargo
cd cargo
./configure
```

output;
```
configure: looking for configure programs
configure: found cmp
configure: found mkdir
configure: found printf
configure: found cut
configure: found head
configure: found grep
configure: found xargs
configure: found cp
configure: found find
configure: found uname
configure: found date
configure: found tr
configure: found sed
configure: found cmake
configure: found make
configure: recreating config.tmp
configure: 
configure: processing ./configure args
configure: 
configure: CFG_PREFIX           := /usr/local 
configure: CFG_LOCAL_RUST_ROOT  :=  
configure: CFG_CARGO            := cargo 
configure: CFG_RUSTC            := rustc 
configure: CFG_RUSTDOC          := rustdoc 
configure: CFG_CARGO            :=  
configure: error: needed, but unable to find any of: CFG_CARGO cargo
```

no errors on clone
occurs on two machines, other with similar specs above, same output.

**Comment by 2114L3** [comment]
`./configure --target=i686-unknown-linux-gnu,x86_64-unknown-linux-gnu`
has the same error

**Comment by alexcrichton** [comment]
Thanks for the report! The error though is indicating that Cargo needs a pre-existing `cargo` to build itself, so you'll need to be sure to install another version of Cargo ahead of time to bootstrap Cargo.
