### ISSUE TITLE
OUT_DIR set for compling libraries/binaries

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#3379]
The docs don't seem to cover when `OUT_DIR` is set while compiling a library / binary (and not just running its build script).

`OUT_DIR` can be used by the non-build script, like in this test: https://github.com/rust-lang/cargo/blob/333a79884d2463b11f279d815284b6406656c949/tests/build-script.rs#L903

I think `OUT_DIR` is only set if a build script exists.

**Comment by alexcrichton** [comment]
Yes `OUT_DIR` is only set if a build script exists, because otherwise there's no output.

Sounds like something that's good to document!

**Comment by mbrubeck** [comment]
> Yes `OUT_DIR` is only set if a build script exists, because otherwise there's no output.

This is true in Rust 1.15 and newer.  In Rust 1.14 and older, `OUT_DIR` is set whether or not a build script exists.

**Comment by dwijnand** [comment]
Fix by #3758.
