### ISSUE TITLE
--crate-name and #[crate_name] are required to match, but `rust_sqlite` != `sqlite3`

### ISSUE THREAD

**Issue by sjmackenzie** [rust-lang/cargo#3382]
Problem:

rust-sqlite wants to be called sqlite3 internally and to find that out we have to parse the Cargo.toml only, see this crates.io index: ru/st/rust-sqlite

```
{"name":"rust-sqlite","vers":"0.3.0","deps":[{"name":"bitflags","req":"^0.1.0","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"libc","req":"^0.2.5","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"enum_primitive","req":"^0.1.0","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"time","req":"^0.1.5","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"}],"cksum":"b7bfffcb0c817390ec867e7ee898c13767322ca1f63af7a916c6fc5cb51885d3","features":{},"yanked":false}
```
rust-sqlite

```
building 
rust-sqlite -  --extern time=/nix/store/1nzxnhzlr7646hq8ijshr657rbqw7872-time/libtime.rlib --extern enum_primitive=/nix/store/404mx6ijxqcmlnxkm5acl1qxkj2mjw5d-enum_primitive/libenum_primitive.rlib --extern libc=/nix/store/jzaw6m5yzmq9nv7sn7iw72p9pyds3nwc-libc/liblibc.rlib --extern bitflags=/nix/store/8ifmqhx605fcg22icq7bl0dijfc4603s-bitflags/libbitflags.rlib
namefix rust_sqlite
4.0K    ./.travis.yml
4.0K    ./src/access/flags.rs
4.0K    ./src/access/mod.rs
12K     ./src/access
28K     ./src/core.rs
16K     ./src/lib.rs
76K     ./src/ffi.rs
8.0K    ./src/types.rs
144K    ./src
4.0K    ./.gitignore
4.0K    ./Cargo.toml
4.0K    ./tests/ex.rs
4.0K    ./tests/typical.rs
4.0K    ./tests/opening.rs
16K     ./tests
4.0K    ./mylibs/liblibc.rlib
4.0K    ./mylibs/libnum_integer.rlib
4.0K    ./mylibs/libenum_primitive.rlib
4.0K    ./mylibs/libnum_traits.rlib
0       ./mylibs/libnum.rlib
4.0K    ./mylibs/libbitflags.rlib
4.0K    ./mylibs/libtime.rlib
4.0K    ./mylibs/libnum_iter.rlib
32K     ./mylibs
4.0K    ./README.md
4.0K    ./LICENSE
216K    .
name rust-sqlite
About to use rustc to compile some lib - rust-sqlite
src/lib.rs:82:1: 82:27 error: --crate-name and #[crate_name] are required to match, but `rust_sqlite` != `sqlite3`
src/lib.rs:82 #![crate_name = "sqlite3"]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/access/mod.rs:18:5: 18:29 error: struct `OpenFlags` is private
src/access/mod.rs:18 use access::flags::OpenFlags;
                         ^~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
note: keeping build directory ‘/tmp/nix-build-rust-sqlite.drv-1’
builder for ‘/nix/store/086v04xbkgbs8g7bbnhdxff8h8ax1s43-rust-sqlite.drv’ failed with exit code 101
```

Should `cargo` should check for this somehow and not write to `crates.io-index` if they don't match.

**Comment by qknight** [comment]
please do this:

* rename the directory in the archive
* rename this lib to sqlite3
* rename all the deps to sqlite3 (these are not many in crates.io)

basically don't use `name=sqlite` in the `Cargo.toml` and instead just use the name which is also used in the rust repository

**Comment by alexcrichton** [comment]
@sjmackenzie hm it looks like you're not invoking Cargo here? Is this a Cargo bug or an internal bug for you?

(note that if Cargo's not being called I'd *highly* recommend chatting with me in `#cargo` to figure out how we can do so)

**Comment by qknight** [comment]
@alexcrichton your observation is correct. we don't use cargo but rather parse the crates.io index directly and derive the dependencies from there.
that said, sqlite3 is the only library which requires the actual toml file being parsed for the `name` attribute. it would be more consistent if the name of the whole library was adapted instead of wrapping it with this method.

do you think that would be an option?

**Comment by sjmackenzie** [comment]
This is also an issue with `xml-rs` != `xml` i suspect `Cargo.toml will
need to be parsed for that too.

**Comment by alexcrichton** [comment]
The index does not contain enough information to compile crates, so if that's the only input then I'd again highly recommend being able to use Cargo and/or reach out to me on IRC. IIRC there are quite a few crates with different package names and crate names.

**Comment by sjmackenzie** [comment]
hey alex, we're already compiling quite a lot of crates. I'll implement same kind of regression test and do explicit mapping when the crates fail due to this reason.  I'll hop on #cargo shortly, still got a helluva lot of work to complete!

**Comment by qknight** [comment]
@alexcrichton 
have a look at https://github.com/nixcloud/nixcrates which is quite useable already! also thanks for your help!

**Comment by alexcrichton** [comment]
Ok, well it sounds like this isn't a bug in cargo itself, so I'm going to close, but feel free to reach out to me on IRC!

**Comment by sjmackenzie** [comment]
Thanks Alex! Much appreciated!
