### ISSUE TITLE
cargo for x86_64-pc-windows-gnu is broken

### ISSUE THREAD

**Issue by retep998** [rust-lang/cargo#3384]
Specifically `x86_64-pc-windows-gnu`. No other target is known to be affected.

https://ci.appveyor.com/project/retep998/winapi-rs/build/1.0.1027/job/s9rb4k8hlukyrf87

```
cargo -vV
Command exited with code -1073741701
```

That exit code is `0xC000007B   STATUS_INVALID_IMAGE_FORMAT`.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Hm I have yet to see the reproduce elsewhere, and can't reproduce it locally unfortunately. Does this happen deterministically for you? Would it be possible to test this out via AppVeyor's RDP feature to poke around and see what the invalid image is?

**Comment by retep998** [comment]
It is deterministic, and I figured out what the issue is. `cargo.exe` gained a dependency on `zlib1.dll`.

**Comment by alexcrichton** [comment]
That'd do it! I'll look into fixing that.

**Comment by eminence** [comment]
Since I can't run `cargo --version`, what's the best way to track this fix (and to see when it'll be available via a `rustup update`)?

**Comment by retep998** [comment]
@eminence You can follow http://rusty-dash.com/nightlies to see when the next Rust nightly comes out.

**Comment by eminence** [comment]
Thanks!   Looks like there was a new nightly release today, and running `cargo --verbose` works again.  Yes there is another crash later on.  Do we think this is related to this issue, or is something different?

**Comment by alexcrichton** [comment]
@eminence it may be unrelated, but what are the crashes that you're seeing?

**Comment by eminence** [comment]
During a `cargo build`, there was a crash that resulted in a very generic "cargo.exe has crashed" popup.  However I can no longer reproduce the issue.  i'll continue trying to reproduce and will open a new issue if i figure it out.  thanks!
