### ISSUE TITLE
crates.io and doc.crates.io are out of sync

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3387]
Hi! Currently, `Docs` menu on [crates.io](https://crates.io) misses some documentation sections:

![docs](https://cloud.githubusercontent.com/assets/1711539/21104621/4ff11950-c098-11e6-8321-24492dc6a4e8.png)

Menu on [doc.crates.io](http://doc.crates.io) has them all. Not sure if this is intentional or not.

**Comment by steveklabnik** [comment]
They're two different codebases, so that's why. Could you re-file this against https://github.com/rust-lang/crates.io please, since it's the one that's out of date? Thanks!
