### ISSUE TITLE
Trying to install dependencies on Windows, getting 'Group Policy' violations

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [rust-lang/cargo#3389]
So I'm trying out rust + cargo at my work and we use Windows machines. When I want to install rustfmt (or any other dependency), it looks like cargo is recompiling the source and placing it in a temporary working directory and my windows machine does not like this.

When I install a dependency, I see this:

```
   Compiling kernel32-sys v0.2.2                                                                                                                                                                                      
     Running `rustc C:\Users\shiraaz.moollatjie\.cargo\registry\src\github.com-1ecc6299db9ec823\kernel32-sys-0.2.2\build.rs --crate-name build_script_build --crate-type bin -C opt-level=3 -C metadata=d6afa5bd3d7cfa
ef --out-dir C:\Users\SHIRAA~1.MOO\AppData\Local\Temp\cargo-install.g5SAiZ1VoTBJ\release\build\kernel32-sys-d6afa5bd3d7cfaef --emit=dep-info,link -L dependency=C:\Users\SHIRAA~1.MOO\AppData\Local\Temp\cargo-install
.g5SAiZ1VoTBJ\release\deps --extern build=C:\Users\SHIRAA~1.MOO\AppData\Local\Temp\cargo-install.g5SAiZ1VoTBJ\release\deps\libbuild-493a7b0628804707.rlib --cap-lints allow`                                          
```

Based on the --out-dir, it then runs the build script from that directory. 

```
     Running `C:\Users\SHIRAA~1.MOO\AppData\Local\Temp\cargo-install.g5SAiZ1VoTBJ\release\build\kernel32-sys-d6afa5bd3d7cfaef\build-script-build`
Build failed, waiting for other jobs to finish...
error: failed to compile `rustfmt v0.6.3`, intermediate artifacts can be found at `C:\Users\SHIRAA~1.MOO\AppData\Local\Temp\cargo-install.g5SAiZ1VoTBJ`

Caused by:
  failed to run custom build command for `kernel32-sys v0.2.2`
could not execute process `C:\Users\SHIRAA~1.MOO\AppData\Local\Temp\cargo-install.g5SAiZ1VoTBJ\release\build\kernel32-sys-d6afa5bd3d7cfaef\build-script-build` (never executed)

Caused by:
  This program is blocked by group policy. For more information, contact your system administrator. (os error 1260)
```

The main reason is that the policy at work restricts applications running from this folder.

So is there a way to set the **--out-dir** property when running `cargo install`? 

I tried setting `CARGO_TARGET_DIR` in my shell, but only the cargo project commands respects this and not the cargo install command.

Version info:
```
cargo 0.13.0-nightly (eca9e15 2016-11-01)
```

```
rustc 1.13.0 (2c6933acc 2016-11-07)
binary: rustc
commit-hash: 2c6933acc05c61e041be764cb1331f6281993f3f
commit-date: 2016-11-07
host: x86_64-pc-windows-gnu
release: 1.13.0
```

**Comment by alexcrichton** [comment]
Unfortunately there's no way to set the output directory with `cargo install foo` right now, but if you check out the project locally and run `cargo install` it'll use the current directory as the output directory.

Sounds like a good reason though to add a flag!

**Comment by retep998** [comment]
Last I checked, when setting `CARGO_HOME`, `cargo install` will respect that.

**Comment by ShiraazMoollatjie** [comment]
Okay so I figured this out. Cargo, on windows, seems to use the User's `TEMP` (or `TMP`) variable as the work directory for `cargo install`

So I updated the TEMP and TMP user local variables to execute from a different location, then **--out-dir** is updated to a different value :)
