### ISSUE TITLE
Error message for missing paths on an indirectly used crate, don't show the filepath containing the error

### ISSUE THREAD

**Issue by ideasman42** [rust-lang/cargo#3400]
Recently I decided to restructure my directory layout for a project that uses multiple crates in the same repository with the intention of correcting the errors as they were reported.

The problem with this, is the error message only prints:

- The base toml file which failed to build.
- The file path which isn't found.

It doesn't print the path to the TOML file which contains the invalid path, so any fixes have to be done by manually searching for the TOML which has the incorrect path.

eg:

This is the error message:
```
+ exec cargo build --manifest-path /src/bmesh-rs/app_driver_sdl/Cargo.toml
error: failed to load source for a dependency on `polyfill_2d`

Caused by:
  Unable to update file:///src/bmesh-rs/intern/extern/polyfill_2d

Caused by:
  failed to read `/src/bmesh-rs/intern/extern/polyfill_2d/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```
To solve this I needed to edit an indirectly used TOML file (in this example `intern/bmesh/Cargo.toml`).

----

I could make a sample repository if it helps, but think its not too hard to redo the error? - just make a path in an indirectly used crate invalid - and that file wont show up in the error message.

**Comment by alexcrichton** [comment]
Thanks for the report! And yeah I think this is descriptive enough to reproduce, and would be great to fix!

**Comment by antoyo** [comment]
I don't know if it is related to this issue, but if you specify a git repository instead of a `path` directive, you also get this error.
It would be nice to get a better error message for that too.

**Comment by ehuss** [comment]
I'm going to close this as I believe it is fixed. The root error displayed now is something along the lines of:

```
error: failed to get `baz` as a dependency of package `bar v0.1.0 (/path/to/myproject/bar)`
    ... which is depended on by `foo v0.1.0 (/path/to/myproject/foo)`
    ... which is depended on by `myproject v0.1.0 (/path/to/myproject)`
```

which gives the chain of dependencies that led to the error, along with their paths.
