### ISSUE TITLE
Subversion folders confuse cargo

### ISSUE THREAD

**Issue by jonathanpallant** [rust-lang/cargo#3414]
I'm trying to a build a project using vendored sources in a private CI system. It worked find when I was using Subversion exports, but if I use a Subversion (1.6) checkout, the .svn folders confuse cargo.

```
error: failed to load source for a dependency on `getopts`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to update replaced source `registry https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to read `/home/user/trunk/crate_name/vendor/.svn/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by alexcrichton** [comment]
Thanks for the report! I think I've covered this in https://github.com/rust-lang/cargo/pull/3417.

You may hold the badge for "first Rust project  using SVN" now :)

**Comment by thejpster** [comment]
Thank you! If that merges soon, we're looking at stable in 1.15?

The work-around (just in case anyone else has the same issue) is to update to a Subversion 1.7 working copy, which replaces the multitude of `.svn` folders with a single one at the top level.

**Comment by jonathanpallant** [comment]
Thank you! If that merges soon, we're looking at stable in 1.15?

The work-around (just in case anyone else has the same issue) is to update to a Subversion 1.7 working copy, which replaces the multitude of .svn folders with a single one at the top level.

**Comment by alexcrichton** [comment]
Indeed! It may miss the 1.15 release at this point, though.

**Comment by k06a** [comment]
@alexcrichton  I wish to have svn depencency, is it possible? `= { svn = "https://..." }`
