### ISSUE TITLE
Windows: zlib1.dll missing

### ISSUE THREAD

**Issue by Ploppz** [rust-lang/cargo#3415]
With both the latest Beta (1.14) and Nightly (1.15), when I run `cargo`, I get an error that `zlib1.dll` is missing. So I went to download it from some 3rd-party webpage called dll-files.com and put the dll in System32. But now when I try to run `cargo`, it gives error `c000007b` and exits.

**Comment by alexcrichton** [comment]
Thanks for the report! I believe this is a dupe of https://github.com/rust-lang/cargo/issues/3384, fixed in https://github.com/rust-lang/cargo/pull/3393, and recently now should be included in the latest nightlies!

**Comment by arynadam** [comment]
Try different version the file from http://www.dll4free.com/zlib1.dll.html
It should be the correct version in order to work...
