### ISSUE TITLE
`cargo metadata` outputs relative file names for targets

### ISSUE THREAD

**Issue by fmdkdd** [rust-lang/cargo#3416]
With the following Cargo.toml:
```
[package]
name = "relative-filename"
version = "0.1.0"
authors = ["fmdkdd <..>"]

[lib]
path = "lib.rs"
```
The file name of the target reported by`cargo metadata` is relative:
```
    "targets": [
        {
          "kind": ["lib"],
          "name": "relative-filename",
          "src_path": "lib.rs"
        }
      ],
```
If you remove the `[lib]` directive from Cargo.toml, `cargo metadata` reports an absolute file name for the target:
```
 "targets": [
        {
          "kind": ["lib"],
          "name": "relative-filename",
          "src_path": "/home/[..]/relative-filename/src/lib.rs"
        }
      ],

```

It seems that the `src_path` is reported directly from the Cargo.toml when the `[lib]` directive or other targets are present in the file.

I don't know if this is the expected behavior, but for tools eating `cargo metadata` output it means reconstructing absolute path names when `cargo` could just canonicalize them.  

(Assuming that relative paths in Cargo.toml are relative to the location of the Cargo.toml file, which is also reported by `cargo metadata` as "manifest-path")

**Comment by alexcrichton** [comment]
cc @matklad is this a problem you've run into as well?

It seems fine to me to always print out absolute paths, but I can't even seem to find where we generate the absolute paths in the first place...

**Comment by matklad** [comment]
Yeah, I also remembering seeing a mixture of relative and absolute paths.... In IntelliJ Rust, we just handle [either](https://github.com/intellij-rust/intellij-rust/blob/c92313d92a14cb7cbfa07f42944a524ea9238577/src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt#L147) [of those](https://github.com/intellij-rust/intellij-rust/blob/c92313d92a14cb7cbfa07f42944a524ea9238577/src/main/kotlin/org/rust/utils/Extensions.kt#L18-L22).

But frankly, this seems like a bug in Cargo to me!

**Comment by matklad** [comment]
I think this is the place where abs paths crop in: https://github.com/rust-lang/cargo/blob/109d9c5ec64bcc61343d713fc00bb72bfc18d804/src/cargo/util/toml.rs#L44

**Comment by matklad** [comment]
Are absolute paths should be allowed in `Cargo.toml`?

This is accepted now:

```
[[bin]]
name = "hello"
path = "/home/user/trash/hello/src/main.rs"
```

Is this intended? 

If it is, then we need just to make sure that `src_path` of targets is always absolute both internally in Cargo and externally at the serialization. 

If it is not intended, we must choose either always relative, or always absolute paths, and I am not sure which alternative would make more sense.

**Comment by alexcrichton** [comment]
@matklad technically, yes, and it should be fine to allow I think as `.join` on paths tends to always take care of those use cases.

**Comment by alexcrichton** [comment]
@matklad out of curiosity, would you be interested in sending a PR for this?
