### ISSUE TITLE
Allow Cargo.toml to specify custom linker

### ISSUE THREAD

**Issue by mat8913** [rust-lang/cargo#3429]
It'd be real useful if in the Cargo.toml I could specify a custom linker. I tried doing it manually in build.rs but I got back an error telling me that only `-l` and `-L` flags are allowed.

**Comment by alexcrichton** [comment]
This is currently supported through `target.$target.linker` in `.cargo/config`, would that work for your use case?

**Comment by mat8913** [comment]
Yes, this is exactly what I'm looking for. For some reason, I was under the impression that the config would only load from `~/.cargo/config` and not from `./.cargo/config`.
