### ISSUE TITLE
Cargo does not track env!("FOO") for rebuilding

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/cargo#3434]
Given the code below, I would expect Cargo to rebuild the crate when `FOO` changes, but this currently does not happen. I don't know if Cargo currently has enough information to handle this, though.

```rust
fn foo() -> &'static str {
    env!("FOO")
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/cargo/issues/2776, so I'm going to close it in favor of that

**Comment by Imberflur** [comment]
For future readers, cargo now tracks these via https://github.com/rust-lang/cargo/pull/8421
