### ISSUE TITLE
Bootstrapping cargo - instructions unclear

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/cargo#3437]
Hi,
  the readme says:

> If, however, you have neither rustc nor cargo previously installed you can run:
> ```
> python -B src/etc/install-deps.py
> ./configure --local-rust-root="$PWD"/rustc
> make
> make install
>

This seems to be outdated.
The `src/etc/install-deps.py` doesn't seem to exist anymore.
Also, running `configure` says:

```
configure: CFG_CARGO            :=  
configure: error: needed, but unable to find any of: CFG_CARGO cargo
``` 

I'm wondering now how does one compile cargo on a system without cargo.
Thanks!

**Comment by alexcrichton** [comment]
Oh this is actually just a case where we forgot to update the docs! Cargo now requires a previous installation of Cargo/rustc to be present to build Cargo.

**Comment by starius** [comment]
What to do if I do not want to run cargo binaries not built by myself?

**Comment by alexcrichton** [comment]
Cargo requires a Rust compiler to build, and all Rust compilers should be coupled with Cargo, so you can run that Cargo you've got on hand.

**Comment by vojtechkral** [comment]
@starius There's @dhuseby/cargo-bootstrap

**Comment by starius** [comment]
@vojtechkral Thanks!
I wrote a script installing Rust and Cargo locally:
https://github.com/starius/config/blob/master/.bin/install-rust

**Comment by mpkh** [comment]
`all Rust compilers should be coupled with Cargo` sounds problematic/complicated to package cargo and rust in modular way, seems like in source based distribution we will need some separate rust binary bootstrap with compiler and cargo and then rust package and cargo package will depend on that bootstrap package, I wish configure to be smarter and download binaries it needs in case when cargo is not installed.

**Comment by carlorosati** [comment]
@alexcrichton 

> Cargo requires a Rust compiler to build, and all Rust compilers should be coupled with Cargo, so you can run that Cargo you've got on hand.

Which directory does cargo get installed into after ```./configure```ing and ```make install```ing rustc?

**Comment by alexcrichton** [comment]
@carlorosati right now `make install` in the rust repo doesn't install Cargo (but it will eventually!)

**Comment by carlorosati** [comment]
@alexcrichton Temporarily I will be using the [cargo release tar](https://static.rust-lang.org/dist/2017-01-31/cargo-0.16.0-x86_64-unknown-linux-gnu.tar.gz).

As of now, I cannot find these release tars documented anywhere on the rust website(s). Is there any plans on documenting these or are they meant sheerly for developers.

**Comment by alexcrichton** [comment]
They're mostly just meant for developers currenlty

**Comment by Michele31415** [comment]
I understand that this is a bit old now but I just tried starius' script above and it failed thusly:

...
Submodules updated in 482.25 seconds
downloading https://static.rust-lang.org/dist/2019-12-18/rust-std-beta-sparcv9-sun-solaris.tar.gz
######################################################################### 100.0%
extracting /tmp/tmp.DYuS0c/build/cache/2019-12-18/rust-std-beta-sparcv9-sun-solaris.tar.gz
curl: (22) The requested URL returned error: 404 

???
