### ISSUE TITLE
Can't use a git dependency to https://github.com/tomaka/hlua

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#3441]
If I put this dependency in my Cargo.toml:

```
hlua = { git = "https://github.com/tomaka/hlua" }
```

I'm getting this error:

```
error: failed to load source for a dependency on `hlua`

Caused by:
  Unable to update https://github.com/tomaka/hlua

Caused by:
  Could not find `Cargo.toml` in `C:\Users\pierre\.cargo\git\checkouts\hlua-31acaa46c204a4dc\7d6aba3ae554055486c3aa91d74f298e9398c3d9\rust-hl-lua`
```

Cargo seems to think that there's a directory named `rust-hl-lua` in the repository while there isn't one.
It is to note that `rust-hl-lua` is the old name of this repository before I renamed it to `hlua`. If I remember correctly that was around the release of Rust 1.0. Maybe github's API is still somehow reporting this old name. Also note that `hlua`'s Cargo.toml is not at the root of the repository but in a subdirectory named `hlua`.

I'm confident that it used to work at some point in the past, because I think I would have noticed.

I reproduced this bug both on my primary Windows machine after clearing half of the `.cargo` directory, but also on a secondary Linux machine that only had Rust/Cargo installed a few days ago. Therefore it's likely not a problem with some sort of cache.

**Comment by alexcrichton** [comment]
When Cargo clones a repository it probes the repository for crates, learning about the structure as it goes along. It looks like there's a [`Cargo.toml`](https://github.com/tomaka/hlua/blob/master/rust-hl-lua-modules/Cargo.toml) that points to the old `rust-hl-lua` folder which is what Cargo's likely bailing on. If that's updated does the repo compile?

I believe that improving the error message here should be covered by https://github.com/rust-lang/cargo/issues/3400 where we need to make the cause of why a `Cargo.toml` is read more readily available.

**Comment by tomaka** [comment]
Thanks, that's working!

Should I leave this open for the improved error message?

**Comment by alexcrichton** [comment]
Yeah I want to leave something open to improve the error message, but I think that's covered by https://github.com/rust-lang/cargo/issues/3400, so I'm going to close in favor of that.
