### ISSUE TITLE
Release 0.15.1 with rust-openssl 0.9.4

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/cargo#3449]
It was released just now and adds back support for libressl which was lost in the 0.9 branch.

**Comment by alexcrichton** [comment]
We don't currently do point releases of Cargo, so could this be a local patch to just modify the lock file?

**Comment by Keruspe** [comment]
It could, indeed.

It kind of sad to have this regression in compatibility though.

Is there any reason why there are no minor releases? iiuc rust 1.12.1 was
released because some serious regressions needed tonne fixed. This one is
maybe not that serious but still.

**Comment by alexcrichton** [comment]
Infrastructurally we essentially have no ability to make minor releases right now, unfortunately.

**Comment by Keruspe** [comment]
Local patch it'll be then, thanks
