### ISSUE TITLE
Add **/*.rs.bk to default gitignore file

### ISSUE THREAD

**Issue by waynenilsen** [rust-lang/cargo#3450]
I find myself doing this all the time after running `cargo new` but I couldn't figure out where to add it to submit a PR. I added it in this [pr](https://github.com/github/gitignore/pull/2108) for the github gitignore repo.

**Comment by alexcrichton** [comment]
Thanks for the report! This has been [proposed](https://github.com/rust-lang/cargo/pull/2926) [before](https://github.com/rust-lang/cargo/pull/2409), but this is something I think rustfmt should deal with, not Cargo.
