### ISSUE TITLE
unable to build from source without existing cargo

### ISSUE THREAD

**Issue by starius** [rust-lang/cargo#3452]
I have built and installed Rust from source. I am building Cargo using instructions from README.md (case "Otherwise, if you have rustc installed and not Cargo")
```
git clone --recursive https://github.com/rust-lang/cargo
cd cargo
./configure
```

It fails with the following error message:
```
configure: error: needed, but unable to find any of: CFG_CARGO cargo
```

**Comment by steveklabnik** [comment]
looks like a kind-of dup of https://github.com/rust-lang/cargo/issues/3437

**Comment by starius** [comment]
Yes, it is a dup.
