### ISSUE TITLE
Can't find crate & multiple crates found

### ISSUE THREAD

**Issue by jtmarmon** [rust-lang/cargo#3456]
using `cargo 0.16.0-nightly (ddb5c32 2016-12-16)`, when running:

`extern crate rocket;`

I get both 
multiple matching crates for `rocket`
and 
can't find crate for `rocket`

This was fixed with a `cargo clean`.

My Cargo.toml has the following deps:

```
[dependencies]
rocket = { version = "0.1.2", path = "../lib/" 
```

**Comment by jtmarmon** [comment]
you  can recreate this reliably with the above version of cargo by doing the following:

clone git@github.com:SergioBenitez/Rocket.git

cd to codegen, run all tests: ` cargo test --all-features` you'll see they're successful.
cd ../lib and run `cargo build`
go back to codegen and run tests again

running cargo clean fixes this

**Comment by alexcrichton** [comment]
Thanks for the report! I don't think this is a bug in Cargo though but rather a bug in how compiletest is used in the rocket project. Cargo aggressively caches builds of libraries to improve compile times, and as a result it doesn't provide guarantees about the build directory and contents, which causes this problem.
