### ISSUE TITLE
Global profile configuration

### ISSUE THREAD

**Issue by torkleyy** [rust-lang/cargo#3459]
I hope I didn't miss something but I couldn't find a way to configure the cargo profiles globally. I know about `~/.cargo/config`, however there is no way to do so.

Wouldn't it be nice to have cargo search for global configuration files, so that we could use one `Cargo.toml` to set e.g. Link-Time Optimization to true?

## Possible solution

Search the parent directories for a `Cargo.toml` and let the children directories override the defaults.

## Unresolved Issues

Should cargo search all the way up to `/`? Or just to `~`? Also, if the project is outside the home directory, should the home directory be searched, too?

Is it really good to have such defaults on a local machine? Could this break anything if one clones a git repository and tries to build it? And if so, should we instead use just a template file which gets copied when you type `cargo new`?

**Comment by steveklabnik** [comment]
>  I know about ~/.cargo/config, however there is no way to do so.

Sorry, what did you mean here?

**Comment by torkleyy** [comment]
@steveklabnik I wanted to say that specifying defaults for, say the optimization level for release profile, is not possible with this config file.

**Comment by steveklabnik** [comment]
Ah! Thanks.

**Comment by torkleyy** [comment]
I added a few thoughts to my first comment. Probably we should go with the template approach?

**Comment by ehuss** [comment]
Closing, as this is now implemented, see https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-profiles and the tracking issue https://github.com/rust-lang/rust/issues/48683.
