### ISSUE TITLE
Cargo check gives error where cargo build does not

### ISSUE THREAD

**Issue by evertvp** [rust-lang/cargo#3461]
`cargo check` gives the following error in my code:
```
error[E0277]: the trait bound `rubato_server::db::DbConnection: rocket::request::FromRequest<'_, '_>` is not satisfied
```

`cargo run` and `cargo build` do not give this error (and run/compile correctly).

You can find the code (as minimal as I could get it) [here](https://github.com/evertvp/rubato_server/tree/e42284465933f69b2a4225acc4acbfa8152335c5)

**Comment by alexcrichton** [comment]
I ran this locally with Cargo build from master and I think this was fixed with https://github.com/rust-lang/cargo/pull/3426, so this should get fixed as soon as the next nightly is released!

**Comment by alexcrichton** [comment]
In any case, though, thanks for the report!
