### ISSUE TITLE
stderr from build script still does not get saved anywhere

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#3462]
Consider this build script:

```rust
use std::io::Write;
fn main(){
    write!(::std::io::stderr(), "boom").unwrap();
    write!(::std::io::stdout(), "woaw").unwrap();
}
```

the `stdout` output gets saved into `output` file, but `stderr` is dropped. Would be nice if the `stderr` was also saved in this manner.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!
