### ISSUE TITLE
cargo test for plugins fails on Windows when using rustup

### ISSUE THREAD

**Issue by retep998** [rust-lang/cargo#3463]
If a crate has `plugin = true` then any binaries crated by `cargo test` will depend on the DLL versions of Rust libraries instead of statically linking to them. If the directory containing the DLLs is not in `PATH` then the test binaries will fail to run. The most common way that this occurs is if the user is using rustup as recommended. So either rustup needs to make sure that directory is in `PATH` before forwarding to the actual cargo/rustc or cargo needs to make sure it adds that directory when running tests or possibly make tests statically link. The reason this is specific to Windows is because Windows does not have rpath, so the only way for the DLLs to be found is via `PATH`.

cc @brson

**Comment by retep998** [comment]
Oh, this is a dupe of https://github.com/rust-lang/cargo/issues/3394

**Comment by alexcrichton** [comment]
Ok, closing as a dupe.
