### ISSUE TITLE
Cargo check on nightly seems to have problems with re-exported types

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/cargo#3464]
https://github.com/MaikKlein/ash/tree/b49b2b1deb84aea24a9e1701f22cc8d2d30f02e2

`cd examples && cargo check`

The following errors should appear

```
error[E0308]: mismatched types
   --> src/bin/texture.rs:845:45
    |
845 |             base.device.destroy_framebuffer(framebuffer, None);
    |                                             ^^^^^^^^^^^ expected struct `ash::vk::types::Framebuffer`, found struct `ash::vk::Framebuffer`
    |
    = note: expected type `ash::vk::types::Framebuffer`
    = note:    found type `ash::vk::Framebuffer`
```

Here `ash::vk::Framebuffer` and `ash::vk::types::Framebuffer` are actually the same thing.

Here is the re-export https://github.com/MaikKlein/ash/blob/b49b2b1deb84aea24a9e1701f22cc8d2d30f02e2/src/vk.rs#L2

And here is the type definition
https://github.com/MaikKlein/ash/blob/b49b2b1deb84aea24a9e1701f22cc8d2d30f02e2/src/vk.rs#L3254

```
➜  ~ rustc --version
rustc 1.15.0-nightly (71c06a56a 2016-12-18)
```

**Comment by alexcrichton** [comment]
Thanks for the report! I tested against the master branch and I think https://github.com/rust-lang/cargo/pull/3426 fixed this, so we should get that out as soon as a new nightly is available!
