### ISSUE TITLE
The color option is not passed to tests

### ISSUE THREAD

**Issue by alygin** [rust-lang/cargo#3474]
When running `cargo test`, the `--color` option affects cargo's output but is not propagated to tests themselves, which prevents coloring their results (`ok` or `FAILED`) under certain circumstances when `--color=always` is used.

The `--color` option should be passed to tests the same way it's passed to the compiler and other tools.

**Comment by matklad** [comment]
The same underline issue as https://github.com/rust-lang/cargo/issues/1983. We can't just pass --color=always to test runner because theoretically you can plug in a custom test runner which does not accept this flag.

**Comment by alygin** [comment]
Thanks! That sounds reasonable.
