### ISSUE TITLE
cargo create a new cargo project fail on Windows

### ISSUE THREAD

**Issue by DCjanus** [rust-lang/cargo#3481]
On Windows. If you use `cargo new` or `cargo init`  , it seems like a endless loop.
And on Linux, it works.

Tested with the latest stable Rust, installed via rustup-rs:

    rustup 1.0.0 (17b6d21 2016-12-15)
    host: x86_64-pc-windows-msvc
    rustc 1.14.0 (e8a012324 2016-12-16)
    cargo 0.15.0-nightly (298a012 2016-12-20)
   

sorry, my english is not very good , but i am working on it.

**Comment by alexcrichton** [comment]
Thanks for the report! Can you provide logs or such of what's going on perhaps? Or is Cargo just spinning with no output?

**Comment by DCjanus** [comment]
No output, no logs. (and no girlfriend in the past year)
Cargo just spinning with no output and CPU utility of one core is 100%.
I'm trying to positioning problem. but to be honest, it's too hard for me
 /(ㄒoㄒ)/~~

**Comment by DCjanus** [comment]
I `cargo new` in root directory. On Windows, which requires system administrator privileges.
If use cargo in other directory, it works.

**Comment by alexcrichton** [comment]
Hm interesting! Out of curiosity, did you install Cargo through rustup.rs? If so this ma also be a bug there. If you can manage to attach a debugger to the spinning process that would help greatly! That'd at least identify a stack trace to see where to look.

**Comment by DCjanus** [comment]
I hope I can provide stack trace, but I don't why, GDB can't work on my computer.

I hope I can ues it, but In the next week. I have these final exams. And math is too hard for me.(ಥ_ಥ)
(yes, not every Asian good at it)
So maybe, I have no time for this, recently.
(っ╥╯﹏╰╥c)

But after that is Chinese new year, I'll try to find what cause this bug, in the long vocation.(I think that's interesting.)
～(￣▽￣～)~

before fixed, maybe can just warring users and exit when they try to do this.
(´｡✪ω✪｡｀)

by the way, cargo can just create a new crate in other place and then, move it!
(it's so dirty, but I like it.)

**Comment by alexcrichton** [comment]
Oh no worries if you're busy! I'd like to fix the error here as it at least seems like it needs a better error message. Unfortunately with the information here I haven't quite been able to pin down where this error is coming from though :(

Let me know though if you make more progress!

**Comment by DCjanus** [comment]
Yesterday, I run code from rust std docs;

    use std::sync::Arc;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::thread;
    fn main() {
        let val = Arc::new(AtomicUsize::new(5));

        for _ in 0..10 {
            let val = val.clone();

            thread::spawn(move || {
                let v = val.fetch_add(1, Ordering::SeqCst);
                println!("{:?}", v);
            });
        }
    }

It seems like a deadlock.
But I  try it on Linux, it's works.
Some friends of mine run it on Windows, some works and some deadlock.

On Windows, it's hard to build Cargo with GNU ABI Cargo,  but build with MSVC ABI Cargo, I can't debug by GDB.
So I used WinDbg, It seems there is a deadlock, too.
I know little anti-compilation, I'm asking my friend.

Maybe, there is a bug in the rustc ?
Maybe. god think I shouldn't study Rust ?
/(ㄒoㄒ)/~~

**Comment by alexcrichton** [comment]
@DCjanus that's actually a bug in IIRC where if the program exits while a thread is still running it causes the whole process to lock up. In any case though I think that's not a bug in Cargo, so I'm going to close.
