### ISSUE TITLE
Cannot silence test runner

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/cargo#3482]
[IRC Logs](https://botbot.me/mozilla/rust/2017-01-01/?msg=78674895&page=5)

```
cargo 0.17.0-nightly (740f9c0 2016-12-29)
```

We should be able to silence the test runner's stdout via `--quiet` like `build` and `clean`'s `--quiet` flag, but alas this is not currently done.

```
tmba:sentinel thill $ cargo test --quiet -- quiet

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

```
tmba:sentinel thill $ cargo test --quiet

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

**Comment by alexcrichton** [comment]
Thanks for the report! This output actually comes from the test harness in libtest in the rust-lang/rust repository. Could you open an issue over there instead?
