### ISSUE TITLE
Option for stripping binary

### ISSUE THREAD

**Issue by torkleyy** [rust-lang/cargo#3483]
I think it would be helpful to have an option for stripping the binary (probably as default in release mode) because executables often get much smaller.

**Comment by mdsteele** [comment]
I would like to have this as well.  See also #4122.

**Comment by cup** [comment]
https://github.com/rust-lang/cargo/issues/3483
https://github.com/rust-lang/cargo/issues/4122
https://github.com/rust-lang/rust/pull/49212

**Comment by cup** [comment]
(ugly) workaround is:

~~~sh
RUSTFLAGS='-C link-arg=-s' cargo build --release
~~~

https://github.com/rust-lang/cargo/issues/4122#issuecomment-378928831

**Comment by johnthagen** [comment]
Possible solution is the recently released [`cargo-strip`](https://github.com/guedou/cargo-strip)

**Comment by dewyatt** [comment]
> Possible solution is the recently released [`cargo-strip`](https://github.com/guedou/cargo-strip)

That appears to just call `strip`, which may not always be what you want (you may want `x86_64-linux-musl-strip`, for example).

**Comment by johnthagen** [comment]
@dewyatt I'd suggest opening an issue with `cargo-strip` as that may be a use case that wasn't considered.

**Comment by fadeevab** [comment]
For the record, I was slightly confused why my release binary had 3 MB of size, and I found _debug_ info inside of my _release_ binary. After `strip` the size is just 500 KB.

**Comment by GabrielMajeri** [comment]
It's now possible (on nightly) to have the linker strip symbols from the final build by adding a `strip = "symbols"` line to your `[profile.dev]`/`[profile.release]` section in `Cargo.toml` (and enable the corresponding `cargo-feature`).

**Comment by ehuss** [comment]
To be clear, the Cargo support will land in nightly sometime next week.

**Comment by zonyitoo** [comment]
When will this feature to be released in stable channel? It seems that this feature is not included in v1.46.0. @ehuss

**Comment by ehuss** [comment]
@zonyitoo It will not appear in stable until the feature is stabilized. You can follow the tracking issue at https://github.com/rust-lang/rust/issues/72110 to see when it is stabilized.

**Comment by 89z** [comment]
Came here from internet search. Since I dont see this mentioned already, you can add this to `Cargo.toml`:

~~~toml
[profile.release]
strip = true
~~~
