### ISSUE TITLE
document/clearify environment variables set when running tests (i.e. OUT_DIR/MANIFEST_DIR)

### ISSUE THREAD

**Issue by dathinab** [rust-lang/cargo#3484]
Hy,

In the current stable version[1] OUT_DIR is available while _running_ tests, from the beta version on it isn't any more. While OUT_DIR had been useful for _integration_ tests (e.g. testing thin `std::fs` wrapper) it is not nessesary needed. Nevertheless it would be good to document which variables are available and which "might go away". 

[1]: cargo 0.15.0-nightly (298a012 2016-12-20) / rustc 1.14.0 (e8a012324 2016-12-16)

Other variables currently (and in nightly) available are:

- CARGO_PKG_HOMEPAGE
- CARGO_PKG_NAME
- CARGO_PKG_VERSION_MAJOR 
- CARGO_PKG_VERSION_MINOR
- CARGO_PKG_VERSION_PATCH
- CARGO_MANIFEST_DIR 
- CARGO_PKG_VERSION
- CARGO_PKG_VERSION_PRE
- CARGO_PKG_AUTHORS
- CARGO_PKG_DESCRIPTION

Which can be relied on, which can't? 
I would  preferable to have at last CARGO_PKG_NAME standardized, through it's not necessary. (not that environment variables available during build time will not help, if  you use utility function for testing, which are placed in their own crate)

**Comment by alexcrichton** [comment]
Hm so in theory none of these are actually available when running tests, only when compiling. If these have leaked into the actually executions themselves that was just accidental...

**Comment by dathinab** [comment]
Already resolved
