### ISSUE TITLE
workspaces: All building all members of the workspace

### ISSUE THREAD

**Issue by sdroege** [rust-lang/cargo#3491]
Something like "cargo build" in the root of the workspace would seem useful, which would then build all members of the workspace. Similar to how "cargo clean" currently cleans the workspace.

**Comment by steveklabnik** [comment]
This should be `--all`.

**Comment by alexcrichton** [comment]
Yeah we've got `cargo test --all` now on Nightly so it should be easy enough to add `cargo build --all`!

**Comment by sdroege** [comment]
Basically something similar to 62c0497912f6c424a4a68d7af504f7943fad9864 then, just doing the same for build? Are there any other commands that could use some --all'ification?
I might take a look into that later, would be nice to replace my Makefile doing just that with a cargo command

**Comment by alexcrichton** [comment]
Now that all of the support was landed with `cargo test --all` it may just involve [copying these lines](https://github.com/rust-lang/cargo/blob/afe53bdf7043c2ea8ed3cd0fb8c778ff11dccf4a/src/bin/test.rs#L119-L123) into [`build.rs`](https://github.com/rust-lang/cargo/blob/afe53bdf7043c2ea8ed3cd0fb8c778ff11dccf4a/src/bin/build.rs#L87). We could add `cargo doc` as well, although I'd want to just tread purposefully here to ensure we don't expand it *too* quickly

**Comment by sdroege** [comment]
Thanks, it was almost just that (I've submitted a pull request). For "cargo doc" a little bit more is needed, but if you think that's useful to have (it seems useful to me), I can prepare a pull request for that too.

**Comment by alexcrichton** [comment]
`cargo doc --all` sounds great to me! I'm sure it'll be requested sooner rather than later :)

**Comment by sdroege** [comment]
Ok, I'll get to that once "build --all" is ready to be merged

**Comment by frewsxcv** [comment]
Can this be closed now?

**Comment by frewsxcv** [comment]
Should the default Travis CI Rust script use `--all` by default once this lands in stable?

**Comment by sdroege** [comment]
I would wait until https://github.com/rust-lang/cargo/issues/3515 landed before closing
