### ISSUE TITLE
Failed to start SSH session: socket disconnect

### ISSUE THREAD

**Issue by eminence** [rust-lang/cargo#3492]
```
d:\users\lxd\devel\rust_libs\scm_utils>cargo update --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `ssh://git@dockersim:10022/lxd/sma_rust.git`
error: failed to load source for a dependency on `sma_utils`

Caused by:
  Unable to update ssh://git@dockersim:10022/lxd/sma_rust.git

Caused by:
  failed to fetch into C:\Users\lxd\.cargo\git\db\sma_rust-ee8fef5f32375505

Caused by:
  [23/-1] Failed to start SSH session: socket disconnect


```

I've just moved my workspace to a new machine, and I'm having troubles with remote private repos.  I expected to have a few troubles with keys and credentials (since this is a new machine), but I'm getting this error that I don't understand:  `socket disconnect`

It sounds like a generic networking issue, but I'm not sure what it could be (the hostname resolves, is pingable, and if i jump over to a msys2 shell, i can ssh to it and receive the gitlab welcome banner)

Any ideas?  Debugging variables I can enable?

**Comment by eminence** [comment]
Running `cargo 0.17.0-nightly (71e996e 2017-01-02)`

(I tried the stable and beta versions, but cargo.exe crashes!)

**Comment by alexcrichton** [comment]
I've actually never personally gotten private repos working on Windows. We leverage libssh2 for support here, but I'm not sure if it's using something like an incompatible protocol with ssh-agent or something like that. This could also be a bug in libssh2 I suppose? 

Unfortunately I don't have much info of how to debug this further :(

**Comment by eminence** [comment]
does cargo use libssh2 directly?  or indirectly via libgit2?

**Comment by alexcrichton** [comment]
Ah yeah we only indirectly use it through libgit2

**Comment by jethrogb** [comment]
To use private repos on Windows, use [Pageant](http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) as your SSH agent. The windows-msvc version of libssh2 doesn't support UNIX sockets (duh), which is normally used on UNIX to talk to an SSH agent. On Windows, Pageant is also supported.

**Comment by dmwp37** [comment]
Hi @jethrogb 
I can't use Pageant working with the latest cargo install. Is there any special settings? Have you evert test it successfully?

**Comment by jethrogb** [comment]
It definitely worked at some point for me. I don't know if it's broken again. It worked with nightly-2016-10-03 . It's possible only certain key types are supported (i.e. RSA)

**Comment by dmwp37** [comment]
I test it on nightly-2016-10-03, but with no luck
```sh
D:\project\xxx>cargo test --verbose
    Updating git repository `ssh://git@gitlab.com/dmwp37/yyy.git`
error: failed to load source for a dependency on `yyy`

Caused by:
  Unable to update ssh://git@gitlab.com/dmwp37/yyy.git

Caused by:
  failed to fetch into C:\Users\dmwp37\.cargo\git\db\yyy-5ed341e4be267694

Caused by:
  [23/-1] Failed to start SSH session: Unable to exchange encryption keys

D:\project>cargo --version
cargo 0.13.0-nightly (d8936af 2016-09-30)

D:\project>rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

nightly-2016-10-03-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-2016-10-03-x86_64-pc-windows-msvc (default)
rustc 1.14.0-nightly (144af3e97 2016-10-02)
```

and my pageant version is Release 0.69. key is RSA.

**Comment by dmwp37** [comment]
@alexcrichton
finally find out the root cause of windows cargo ssh issue. on windows platform the libssh2-sys crate use the WINCNG backend. and this backend only support a limited number of ciphers which cause the KEX failure with most sshd servers. 

After change the backend to openssl, cargo work perfect with Pageant and can successfully update  my private ssh repos.  However with the openssl backend you need to install openssl on windows [manually](https://github.com/sfackler/rust-openssl#windows-msvc), after the installation only set OPENSSL_DIR path is enough for build.

and you need to update libssh2-sys with this [patch](https://github.com/alexcrichton/ssh2-rs/compare/master...dmwp37:master)

**Comment by alexcrichton** [comment]
@dmwp37 ah thanks for the investigation!

**Comment by jethrogb** [comment]
As I understand it, CNG should support most common ciphers and cipher modes. Which ciphers besides X.25519 are not supported using CNG?

**Comment by carols10cents** [comment]
It sounds like this issue has been resolved. Please reopen if I'm incorrect! Thanks!
