### ISSUE TITLE
Failed to build a project with a git dependacy

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/cargo#3498]
Yesterday I pushed some changes to both my repositories, where one depend on an other, and got a mail from travis-ci because of failed build:

```
$ cargo build --verbose
    Updating git repository `https://github.com/RazrFalcon/libsvgdom.git`
error: failed to load source for a dependency on `svgdom`
Caused by:
  Unable to update https://github.com/RazrFalcon/libsvgdom.git
Caused by:
  Could not find `Cargo.toml` in `/home/travis/.cargo/git/checkouts/libsvgdom-a2eb2848e646b406/svgdom`
```

Build on the local machine is also became broken. As far as I remember it was build successfully before pushing.

Here is the [main project](https://github.com/RazrFalcon/svgcleaner) (svgdom's repo link is above). Also here is the [travis log](https://travis-ci.org/RazrFalcon/svgcleaner/jobs/188799293) (I hope it's public).

As you can see I'm using the git version of the `svgdom` and didn't changed Cargo.toml for a month.

My only ideas is that there are: a bug in cargo, somehow broken repo on github (or any kind of github problem) or problem with `svgdom`'s Cargo.toml, which I changed today.

Also, project name is `svgdom`, but repo name is `libsvgdom`. But it worked fine for months.

And path is incorrect, because real path is: `/home/razr/.cargo/git/checkouts/libsvgdom-a2eb2848e646b406/1b1c6e1092dc073f52b599147dafd7ddf9472375/Cargo.toml`

Today I tried to add new dummy commits to both repositories, but result is the same.

Copy of the: https://users.rust-lang.org/t/cargo-stops-downloading-dependencies-via-git-today/8704

**Comment by alexcrichton** [comment]
@RazrFalcon I think it's due to [this Cargo.toml](https://github.com/RazrFalcon/libsvgdom/blob/master/tests/build-tests/parsing/Cargo.toml). Cargo's looking at all `Cargo.toml` files in the git repo and I think that's pointing outside the git repo with a path dependency.

**Comment by RazrFalcon** [comment]
Wow! It actually fixed everything. Magic.

I have completely forgot about this test and it's really badly written (but works locally, since I have this folder).

I didn't know that 'Cargo's looking at all Cargo.toml files in the git repo' and error message was a bit confusing. It saying that it can't find a file and cant update (I thought that mean download) a dependency. Maybe a better error message will be a good idea.

Thank for a hint!

**Comment by alexcrichton** [comment]
Glad it's working! 

https://github.com/rust-lang/cargo/issues/3400 covers a better error message, so I'm going to close in favor of that.
