### ISSUE TITLE
Tests in proc-macro lib doesn't run

### ISSUE THREAD

**Issue by F001** [rust-lang/cargo#3514]
There is a bin crate which depends on a proc-macro crate.
If I run `cargo test` in the main project, the test cases in library do not execute at all.

This issue is only related to the new `proc-macro` lib. 
I'm not sure it should be fixed in cargo or rustc.

**Comment by alexcrichton** [comment]
Hm I just tested this with the latest beta/nightly and it seems to work. Can you describe how to reproduce this?

**Comment by F001** [comment]
@alexcrichton 

```
rustc -V
rustc 1.16.0-nightly (6f1ae663e 2017-01-06)
```

Test repository: https://github.com/F001/HelloWorld

In hello-world-derive directory, `cargo test` works fine. In hello-world directory, `running 0 tests`.

OS version: Mac OS X 10.11.5

**Comment by alexcrichton** [comment]
@F001 that's because `hello-world-derive` is a separate crate, and `cargo test` only runs tests for the current crate. If you `cd` into that directory and run `cargo test` you'll see the tests being run.

**Comment by F001** [comment]
Ah, sorry. I have the impression that the `cargo test` command will run all the tests including ones in dependencies. I must be wrong when I do exercises. 

Please close this issue.

**Comment by alexcrichton** [comment]
Ok, thanks!
