### ISSUE TITLE
[replace] section replaces all kinds of dependencies

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#3522]
I'm compiling for a target for which I need to replace some crates. However, using the `[replace]` section also uses the replacement crate for build dependencies, which is not what I want since I'm cross-compiling.

**Comment by alexcrichton** [comment]
This... seems pretty unlikely to ever get implemented, but an issue nonetheless.

**Comment by jethrogb** [comment]
I'm still hoping for some big overhaul getting rid of the contamination between dependencies, dev-dependencies and build-dependencies and this could be part of that.

**Comment by Eh2406** [comment]
link to one of the other issues related to the contamination https://github.com/rust-lang/cargo/issues/2589

**Comment by epage** [comment]
Considering [`replace` is deprecated](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-replace-section), I think a major new feature is unlikely enough that I'm going to close this.  If there is a reason we should keep this open, let us know!  This doesn't say anything about `patch` and how that should behave and I could see a similar request being made for that.
