### ISSUE TITLE
Passing rustc arguments on Windows doesn't work in nightly

### ISSUE THREAD

**Issue by VelocityRa** [rust-lang/cargo#3523]
Error/Repro instructions:
```bash
set RUSTFLAGS="-C target-cpu=native"
cargo build --release --verbose
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: \`rustc - --crate-name ___ --print=file-names "-C target-cpu=native" --crate-type bin --crate-type rlib --target i686-pc-wind
ows-msvc\` (exit code: 101)
--- stderr
error: multiple input filenames provided

---
The following has the same result:
```bash
cargo rustc --release -- -C target-cpu=native
```
and
```bash
rustc -C target-cpu=native file.rs
```
works (so it's definitely Cargo's issue).

**Cargo version:** cargo 0.17.0-nightly (40a4ce6 2017-01-06)
**Rustc version:** rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)

Thank you.

**Comment by alexcrichton** [comment]
Thanks for the report! I think the problem here, though, is that your syntax for setting an environment variable is including the quotes in the *value*, so you can probably just elide them. If that doesn't work though just let me know!

**Comment by VelocityRa** [comment]
Oh, whoops, I'm used to `bash` syntax.
Thanks!
