### ISSUE TITLE
`cargo clean -p` only cleans the build for a version with zero arguments

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/cargo#3530]
Given a clean checkout of `foo`:

```
cargo clean -p foo
cargo rustc -p foo -- -Zverbose

cargo clean -p foo
cargo rustc -p foo -- -Zverbose
```

Only the first `cargo rustc` will actually *build*. But if you change the argument to `-Z verbose` the second time, it will build (but only once). My hypothesis (which @alexcrichton confirmed) is that each generates a distinct fingerprint, and `cargo clean -p foo` is looking for a version with no arguments.

I would expect it rather to clean all builds related to `foo` with *any* arguments.

**Comment by xftroxgpx** [comment]
Hitting this when compiling for a different [target](https://github.com/xftroxgpx/rustlearnage/tree/14a075e10e74fd0b78227dd84eceb4481a5d1cc0/usize):

```bash
$ cargo run -v --target i686-unknown-linux-gnu
$ cargo clean -vv -p usize
(nothing is cleaned)
$ cargo run -v --target i686-unknown-linux-gnu
...
Fresh usize v0.1.0 (file:///home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/usize)
...
$ cargo clean -vv -p usize --target i686-unknown-linux-gnu
    Removing /home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/target/i686-unknown-linux-gnu/debug/usize
    Removing /home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/target/i686-unknown-linux-gnu/debug/.fingerprint/usize-d5bf39b5c2514907
    Removing /home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/target/i686-unknown-linux-gnu/debug/deps/usize-d5bf39b5c2514907
```

Used https://github.com/rust-lang/cargo/pull/5059 to show Removed files.

OP clearly explains the issue, thanks!

**Comment by dwijnand** [comment]
Under-compiling is dangerous. Let's try and fix this issue.
