### ISSUE TITLE
Published crates should include LICENSE file

### ISSUE THREAD

**Issue by raphlinus** [rust-lang/cargo#3537]
I'd like for published crates to include the text of the LICENSE along with the code. For our use case (making a repo of vendored crates), the cargo-vendor tool is populating the vendor directory with lots of packages that are missing LICENSE. There are basically two reasons for this:

1. The LICENSE file is present in the source repository, in the same directory as the Cargo.toml config file, but the config file doesn't include the LICENSE in the list of files to be uploaded (because of an explicit "include" keyword). Examples include [dtoa](https://crates.io/crates/dtoa) and [serde](https://crates.io/crates/serde).

2. The LICENSE file is present in the source repo (typically in the repo root), but the crate is published from a subdirectory. Examples include [num-traits](https://crates.io/crates/num-traits) and [xi-core-lib](https://crates.io/crates/xi-core-lib).

There are (at least) two things "cargo publish" could do to mitigate this problem:

1. The publish tool could do a lint check that an appropriate license file is present. There's a small amount of client-side sanity-checking now (checking that a license file exists if specified), and I believe the crates.io server also checks the spdx string.

2. Automatically including LICENSE files from the repo root if publishing from a subdirectory.

I'll get around this for the time being by making my vendoring script do the latter at vendoring time, but I think it would be better if every stage in the chain precisely matched the exact contents.

**Comment by joshtriplett** [comment]
There's a third possibility that needs to be covered: the crate source cites a well-known license and *intentionally* does not include a license file. That's not necessarily a bug.

If the crate *does* include a license file, I'm entirely in favor of having cargo make sure it gets included.

**Comment by kelseasy** [comment]
And some licenses can be found in a `COPYING` file too. There are also `PATENTS` files that can change the meaning of a license to something else entirely. :(

**Comment by joshtriplett** [comment]
This issue still exists.

Would someone be interested in contributing to this? In particular, making `cargo package` check for a file named "LICENSE" or "COPYING" (or a few other patterns) and automatically including it in the `.crate` file?

**Comment by richardwhiuk** [comment]
cargo publish does do this doesn't it - but cargo package doesn't?
