### ISSUE TITLE
Fixing errors of a new project does not make it clear that non-OSI-approved license may be used

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#3540]
```
$ cargo new banana
     Created library `banana` project
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: manifest has no description, license, license-file, documentation, homepage or repository.
...
error: api errors: missing or empty metadata fields: description, license. Please see http://doc.crates.io/manifest.html#package-metadata for how to upload metadata
# add
# description = "this is a banana"
# license = "TBA"
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: manifest has no documentation, homepage or repository.
…
error: api errors: unknown license or other term: TBA; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers
# From the error above assume non-OSI license cannot be used T_T
```

The errors should make it clear what *all* the alternatives/valid values are. For example nowhere it is stated (other than in documentation), that `license = "custom"` is a valid option.

**Comment by nagisa** [comment]
A bit unrelatedly, the errors from the API should probably not exposed verbatim. 

> Please see http://doc.crates.io/manifest.html#package-metadata for how to upload metadata

for example is very unrelated to a cargo user.

**Comment by steveklabnik** [comment]
> that license = "custom" is a valid option.

To be clear, it's not; you use `license-file` and point to a file locally instead.

**Comment by ehuss** [comment]
I'm going to close as this is effectively solved by https://github.com/rust-lang/crates.io/pull/6545.

I don't know if cargo should be validating license expressions itself so that you can get earlier feedback, and to ensure there is consistency for all kinds of dependencies. However, there are downsides to doing validation in cargo, so that seems a bit up in the air.
