### ISSUE TITLE
Extending `cargo test` with extra steps

### ISSUE THREAD

**Issue by vorner** [rust-lang/cargo#3541]
It would be nice if I could specify additional commands/steps to run when running `cargo test`. The example would be to run `cargo fmt -- --write-mode diff` as a sub-test, or running the binary (not just its tests) with supplied parameters. Now, I have to type all these commands before committing my code, or wrap them in a makefile.

But, to be honest, I don't have a concrete idea how the configuration would look like while preserving some amount of platform-independence. I know I can create a fake integration test with no harness and do these steps from there, but that sounds a little overcomplicated.

**Comment by KalitaAlexey** [comment]
@vorner,
You should use either Makefile or cmd/sh script.
Cargo isn't designed as a replacement for them.

**Comment by vorner** [comment]
Either after or before, I don't really care about the order.

So, is the right way to use cargo to actually wrap it into something? From all the tutorials I got the impression it should be the user-facing tool, not a backend.

**Comment by KalitaAlexey** [comment]
@vorner,
Yes, you should wrap it into something.
You can use build.rs to do something before, but it is antipattern.
Look at https://github.com/rust-lang/cargo/issues/545

**Comment by vorner** [comment]
So, if you explained this likely isn't going to happen and why, should I close the issue, or is the intention to leave it here just in case the idea gets revisited? Maybe I'm old-school, but I kind of expected a „WontFix“ resolution by now O:-)

**Comment by KalitaAlexey** [comment]
@vorner,
Your issue is duplicate of #545.
This is why I suggested you to close your issue.

**Comment by vorner** [comment]
That one looks *similar*, but runs at different time, so I don't think it is a direct duplicate (that one talks about post-build, I talk about running during tests). And I didn't get the suggestion to close it myself O:-). OK.
