### ISSUE TITLE
`cargo run` with a huge number of arguments doesn’t work

### ISSUE THREAD

**Issue by ariasuni** [rust-lang/cargo#3547]
I have a folder with 16’000 files. When I run `cargo run folder/*`, Cargo seems blocked and takes a lot of RAM. However, when I run the exec directly (e.g. `./target/debug/exec`) it works perfectly well.

**Comment by alexcrichton** [comment]
Thanks for the report! If possible, could you get a snapshot/profile of where the time is being spent in Cargo?

**Comment by ariasuni** [comment]
I used callgrind, waited 20 seconds before terminating the program with Ctrl+c, and I got that: https://gist.github.com/ariasuni/26822c6dc6121167a5b226c636779582

**Comment by alexcrichton** [comment]
Thanks! I've reported upstream at https://github.com/docopt/docopt.rs/issues/207

**Comment by Eh2406** [comment]
with https://github.com/rust-lang/cargo/pull/5152 we are using clap. Move to close?

**Comment by ariasuni** [comment]
ripgrep, which is using Clap, don’t choke with twice as much as arguments on the command line.

**Comment by matklad** [comment]
@ariasuni could you verify just in case that Cargo itself works ok with huge number of arguments now? The fact that we”ve switched to clap does not mean we use it 100% correct :)
