### ISSUE TITLE
rustdoc: Allow crate manifests to specify a canonical documentation source for use with rustdoc

### ISSUE THREAD

**Issue by krstoff** [rust-lang/cargo#3550]
Currently when documenting a local crate, rust-doc has to traverse the entire dependency graph and document every dependency. Most important crates (for instance, the extremely large ones!) already post their docs publicly at some canonical location. Would it be possible to get crate documentation to refer to these canonical doc sources to avoid redocumenting subcrates? I understand this might not work for older versions of crates, so maybe crates.io can cache docs (or a smaller encoding) for old crates?

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is actually already implemented as you've got a few options locally:

* `cargo doc --no-deps` will avoid building documentation for dependencies and instead use their http locations for links
* `cargo doc` will build deps for offline viewing
* Crates can use `#![doc(http_root_url = "...")]` to specify their root location

Does that make sense?
