### ISSUE TITLE
Should cargo suggest replacing underscores with dashes in package names?

### ISSUE THREAD

**Issue by stjepang** [rust-lang/cargo#3551]
Inconsistency is cropping up in the ecosystem. Some packages use dashes (e.g futures-mpsc) and others underscores (syntex_syntax), without any logical rules whatsoever. Should we stick with just one of these styles?

As a first step towards consistency, I'd like to see cargo suggesting one of the styles when initializing or publishing a crate, if the name does not conform to whatever is considered idiomatic. Thoughts?

**Comment by alexcrichton** [comment]
It's true that inconsistency is unfortunate, but I would personally not want a warning in Cargo because there's often a legitimate reason to have a `_` vs a `-`, and Cargo can't necessarily distinguish.
