### ISSUE TITLE
Ability to sign packages on publication

### ISSUE THREAD

**Issue by michael-zapata** [rust-lang/cargo#3555]
Right now, there is no support for package signature.

Such a feature has two major steps, at least on the cargo side of things:
- adding an optional argument to the `publish` option, such as `--sign`
- the corresponding ` cargo build --verify`

This could be implemented wrapping something like `gpg`, and would improve confidence in the Rust ecosystem (It's somewhat of a requirement in some production environments, and could ease packaging issues in distros as well).

Would such a feature require an RFC, would a PR do just as well, or is it simply not desired?

**Comment by alexcrichton** [comment]
Thanks for the report! Progress for this is currently being tracked at https://github.com/rust-lang/crates.io/issues/75, so I'm going to close in favor of that.
