### ISSUE TITLE
Describe in `cargo test --help` what `cargo test --example <example>` does

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/cargo#3559]
Hi everybody.

During work on https://github.com/rust-lang/cargo/pull/3556 I have found out that I can't understand what `cargo test --example <example>` does.

There is no useful information in `cargo test --help`:
*--example NAME Test only the specified example*.

I can't understand what exactly it does.

**Comment by alexcrichton** [comment]
FWIW I think for now it just compiles the example, rather than executing unit tests in it (but I may have forgotten)

**Comment by KalitaAlexey** [comment]
@alexcrichton,
Yes it is.
But it isn't what `test` subcommand for.

**Comment by KalitaAlexey** [comment]
@alexcrichton,
It just compiles the example, but the description is *Test only the specified example*.
The description is wrong.

**Comment by alexcrichton** [comment]
Ok, want to send a PR to update the description?

**Comment by KalitaAlexey** [comment]
@alexcrichton,
I think we should change behavior. Can we?
My motivation is that *test* should test not just build.

**Comment by alexcrichton** [comment]
I don't think we can change the behavior unfortunately for backwards compatibliity

**Comment by KalitaAlexey** [comment]
@alexcrichton,
I don't think that anyone rely on the behavior.
Do you disagree about it?

**Comment by alexcrichton** [comment]
I don't think we can really say for sure either way, so we're forced to conservatively assume that someone's relying on it somewhere.

**Comment by KalitaAlexey** [comment]
@alexcrichton,
I got it. It is shame. Then I will open a PR to change the description.

**Comment by KalitaAlexey** [comment]
I have found:

*cargo test runs additional checks as well. For example, it will compile any examples you’ve included and will also test the examples in your documentation. Please see the testing guide in the Rust documentation for more details.*

in [Cargo Guide](http://doc.crates.io/guide.html)

**Comment by conradkdotcom** [comment]
Didn't Rust use to check for crates on crates.io using certain features to see if a breaking change would actually affect anyone? Maybe we could use this here too, no?

**Comment by ehuss** [comment]
I'm going to close this.  Since 1.23, `test --example NAME` will actually build the example as a test.  There is also a little bit of extra documentation in the [man page](https://doc.rust-lang.org/cargo/commands/cargo-test.html) which attempts to explain how examples are handled.
