### ISSUE TITLE
Is it safe to kill Cargo? 

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3566]
Hi! This is a continuation of #3564.

I've "fixed" it on the intelliJ side by making sure that we kill all outstanding Cargo processes when the IDE project is closed (https://github.com/intellij-rust/intellij-rust/commit/44b03baeeaaa1ce17334aa3dc553061900df9c1e). 

But I wonder now if this is safe? Can we get a corrupted index/orphan file locks if Cargo is killed? It seems much safer not to terminate `Cargo` processes... What would your advice be? 

Related: https://github.com/libgit2/libgit2/issues/3334

**Comment by alexcrichton** [comment]
The theory is "yes!", in practice though it may lead to corruption if there's bugs we haven't fixed yet. Cargo's killed all the time with ctrl-c so it's a pretty normal thing to do. 

The main part of Cargo at risk of being corrupted is git repositories. We try to handle what we can by completely recloning when possible, but not all errors are caught all the time unfortunately.

My advice personally would be to kill Cargo and open bugs if/when they happen!

**Comment by matklad** [comment]
That's great!

Is it imporatant to try  a graceful kill (SIGINT) first? Or is going with SIGKILL OK?

Unfortunately, IntelliJ OOP makes it difficult to do a graceful termination, so I just SIGKILL cargo atm.

**Comment by alexcrichton** [comment]
I've personally always been under the impression Cargo gets SIGKILL at any time, so either should work.

**Comment by matklad** [comment]
Great, thanks!

**Comment by Dr-Emann** [comment]
I'd still be wary of SIGKILL, especially on a process like cargo, which is bound to have some children, since the children will be orphaned. It's probably better to send the SIGINT, and let cargo kill its own children (man the sentences you write in the computer world...). Alternatively, you could start cargo in a new process group, and send a SIGKILL to the whole process group.

**Comment by matklad** [comment]
We've been killing Cargo in IntelliJ Rust since about this issue was posted, and so far nobody has complained, so it works well in practice :) 

I'd be wary of process groups and such, because that will mean that we will do different things for windows and unixes, so quite probably we will be wrong on at least one platform. Besides, this whole process stuff is so deeply buried under the layers of cross platform Java and IntelliJ APIs, that just implementing this would require a lot of effort :)
