### ISSUE TITLE
support cargo unpack

### ISSUE THREAD

**Issue by grosser** [rust-lang/cargo#3577]
I'm about to publish my first crate but am scared that I'm shipping target/debug folder by accident ... 
It would be great to be able to `cargo unpack foo.crate`

**Comment by alexcrichton** [comment]
This is part of the reason why we have `cargo package` in addition to `cargo publish`, you can inspect the size of the crate file emitted to ensure that it's not overly large. Does that suffice here?

**Comment by grosser** [comment]
I did not like how package produces a folder structure with lots of files I did not include like `target/*` and `Cargo.lock` ... so having a dedicated unpack to see the true content of the file would be nice ... I was hoping it is only a `unzip` but that did not work ... might also come in handy if a crate only exists on crates.io and the homepage 404ed ... so I'd love having it as an option.

**Comment by juhp** [comment]
Okay I see crates are just .tar.gz files, so an unpack workaround is `tar xf some.crate` or `tar tvf some.crate` to list its files.

Coming from Haskell where we have `cabal unpack` and `stack unpack`, I was mildly shocked how hard this is naively.

I am doing some rust package reviews for Fedora and wanted to inspect the contents of crates directly.

**Comment by epage** [comment]
In https://github.com/rust-lang/crates.io/discussions/7020 I proposed crates.io adopt the third-party website https://diff.rs/ which would be another avenue for understanding what is in a crate file.

Even [docs.rs can help](https://docs.rs/crate/clap/latest/source/)

**Comment by epage** [comment]
Solutions today
- `cargo package` and either unpacking directly or looking at the directory that the tarball is created from
- `cargo package --list`
- https://docs.rs/
- https://diff.rs/ 

Other active proposals
- #1861
- rust-lang/crates.io#7020 

Between all of those, I'm not seeing a space left for this dedicated issue and am closing it.  If there is a reason to keep it open, let us know!
