### ISSUE TITLE
excluding a folder should exclude all it's content

### ISSUE THREAD

**Issue by grosser** [rust-lang/cargo#3578]
for example here the complete content of the `foo` folder should be excluded ... but it needs to be `foo/*` atm ... which means I always shipped a ton of useless stuff ... so please make folders exclude the whole folder + content

```
exclude = [
    "foo"
]
```

**Comment by froydnj** [comment]
We ran into the same issue in servo/rust-cssparser#169.

**Comment by behnam** [comment]
And we just fell into this trap too!

Here's the status quo:

These *work*:
* `"dir/*"`
* `"dir/**"`

These *DON'T work*:
* `"dir/"`
* `"dir"`

**Comment by behnam** [comment]
https://github.com/rust-lang/cargo/blame/master/src/cargo/sources/path.rs#L113

(CC'ing from blame: @alexcrichton, @mbrubeck, @llogiq)

Is the status quo the desired behavior? If so, I can add a note to the docs to prevent people from facing the same issue.

If not, I suppose we should replace `Pattern::matches_path()` calls with something that also covers no-asterisks prefix matchings.

What do you think?

**Comment by alexcrichton** [comment]
Sounds reasonable to me to add support for this! To me seems like the existing behavior is a bug.

**Comment by behnam** [comment]
Okay, so I'll give this a shot soon.

**Comment by behnam** [comment]
I believe we can now close this issue in favor of <https://github.com/rust-lang/cargo/issues/4268>, which is implementing the feature and tracking the migration.

**Comment by alexcrichton** [comment]
👍 
Thanks @behnam!
