### ISSUE TITLE
support listing files in Cargo.toml

### ISSUE THREAD

**Issue by grosser** [rust-lang/cargo#3579]
Instead of having to exclude lots of files and shipping things by accident it would be nice if I could set `files = ['src/main.rs']` ... and be done / not need to worry

**Comment by alexcrichton** [comment]
I believe this [can be done](http://doc.crates.io/manifest.html#the-exclude-and-include-fields-optional) with the `include` key, but let me know if that doesn't work!

**Comment by grosser** [comment]
Yes, that worked!
I'd still prefer to rename this since they are not symmetric / means different things:
 - exclude "from the standard set, exclude these"
 - include "only include these" ... but to symmetric should be "to the standard set, add these"
... so 'files' would be better
