### ISSUE TITLE
Feature request: add possibility to separate dependency fetching and building steps

### ISSUE THREAD

**Issue by jauhien** [rust-lang/cargo#358]
Please, add a possibility to separate these steps:

- dependency fetching

- dependency building

- project building

It is may be not necessary when you are building your project by hand during development, but it is really needed in some automatic builds.

An example is ongoing integration of rust related stuff in Gentoo, where fetching and building phases should be separated even for packages that use git live versions, see https://github.com/Heather/gentoo-rust/issues/25

**Comment by alexcrichton** [comment]
With `cargo fetch` plus `cargo build -p` I believe this is fixed now.
