### ISSUE TITLE
support `cargo --version --verbose`, just as rustc does

### ISSUE THREAD

**Issue by froydnj** [rust-lang/cargo#3584]
When checking for `rustc` versions, we've found its `--version --verbose` output very useful:

```
froydnj@hawkeye:~$ rustc --version --verbose
rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-unknown-linux-gnu
release: 1.14.0
LLVM version: 3.9
```

It would be splendid if `cargo` supported the same form of output (obviously deleting things like the LLVM version, but perhaps there are other pertinent things that could be output).  The `--version --verbose` output is somewhat easier to parse if you want to get at things like exact version number without worrying to deeply about the form of your regexes, for instance.  The consistency between the two tools is also welcome.

**Comment by glandium** [comment]
So, one thing that is different between `rustc --version --verbose` and `cargo --version --verbose` is version numbers for nightlies:

```
$ rustc --version --verbose | sed -n '1p;/release/p'
rustc 1.17.0-nightly (956e2bcba 2017-02-12)
release: 1.17.0-nightly
$ cargo --version --verbose | sed -n '1p;/release/p'
cargo-0.18.0-nightly (6f1b860 2017-02-11)
release: 0.18.0
```

**Comment by froydnj** [comment]
> So, one thing that is different between rustc --version --verbose and cargo --version --verbose is version numbers for nightlies:

I think I accidentally changed this in 775c900.

**Comment by froydnj** [comment]
@alexcrichton Do you think it's worth changing it back?  It'd be a one-line change.

**Comment by alexcrichton** [comment]
@froydnj ah yeah makes sense to me!
