### ISSUE TITLE
Add a feature like `cargo test --all-workspace-members`

### ISSUE THREAD

**Issue by luser** [rust-lang/cargo#3585]
If you've got multiple crates in a single repository and they're configured with a workspace, and you're using path dependencies to specify dependencies then `cargo build` will build everything, but `cargo test` will only build and run the tests from the root crate. It would be nice to have something like `cargo test --all-workspace-members` that would effectively run `cargo test -p X` for each crate in the workspace.

**Comment by alexcrichton** [comment]
This one's actually implemented on nightly already! It should be available as `cargo test --all`, but if it doesn't work out just let me know

**Comment by luser** [comment]
Oh, great, thanks for the info!
