### ISSUE TITLE
Cargo behind SOCKS proxy

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#3596]
I have to use a SOCKS proxy (the kind created by `ssh -D`). The documentation doesn't say whether/how SOCKS is supported:

> proxy = "..."       # HTTP proxy to use for HTTP requests (defaults to none)

I've tried changing config, as mentioned in #636, but Cargo seems to assume the proxy is a HTTP proxy. I've tried:

```
[http]
proxy = "socks://localhost:9050"
[https]
proxy = "socks://localhost:9050"
```

but that's not enough:

> cargo run
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: spurious network error (2 tries remaining): [12/-2] [6] Couldn't resolve host name (Could not resolve host: github.com)
warning: spurious network error (1 tries remaining): [12/-2] [6] Couldn't resolve host name (Could not resolve host: github.com)
error: failed to load source for a dependency on `vpsearch`

> Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

> Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Are SOCKS proxies supported?

**Comment by alexcrichton** [comment]
I believe the syntax for libcurl is the `socks5` or `socks5h` protocol (e.g. `socks5://localhost:9050`). Does that work?

**Comment by pornel** [comment]
`socks5h` worked, thank you!
