### ISSUE TITLE
publish source tarballs for each release

### ISSUE THREAD

**Issue by cardoe** [rust-lang/cargo#3612]
There should be a source tarball generated for each release as well. This is really for the distros that build things from source. Currently I use the GitHub "give me a tarball from the git tag" in Gentoo and Yocto but GitHub doesn't necessarily produce stable tarballs which is problematic.

**Comment by cardoe** [comment]
I guess this is a dup of #2107

**Comment by alexcrichton** [comment]
Yeah I'm gonna close in favor of https://github.com/rust-lang/cargo/issues/2107, but thanks for the report!
