### ISSUE TITLE
Version subcommand should handle verbose flag

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3613]
There is `cargo --version` and `cargo version`. https://github.com/rust-lang/cargo/issues/3584 was implemented only for the first one. I wonder if we should just special case the `version` subcommand to avoid duplication and similar issues in the future?

**Comment by matklad** [comment]
Or maybe to deprecate it altogether? why do we need to ways to print a version anyway?

**Comment by alexcrichton** [comment]
I'd prefer to keep it around, but special casing to remove duplication sounds find to me!

**Comment by ehuss** [comment]
This was fixed in #6076.
