### ISSUE TITLE
workflow to separate dependency install step from the build step

### ISSUE THREAD

**Issue by gregwebs** [rust-lang/cargo#3615]
I think cargo has great defaults, but it isn't meeting the needs for all my workflows.

On a continous integration server, to setup my cache I want to run `cargo build --only-dependencies`, which does not attempt to compile my program and instead just installs the Cargo.lock dependencies.

This workflow is supported by Haskell's stack tool (which Cargo learn other things from also, including docker integration and snapshots).

I apologize if there is already a way to achieve this functionality: I am not an experienced Cargo user.

**Comment by KalitaAlexey** [comment]
@gregwebs,
What do you mean under *install the Cargo.lock dependencies*?
Do you want them to be downloaded and that's all?

**Comment by gregwebs** [comment]
That would be a different workflow, perhaps `--download-only`. I want to build all the library dependencies also.

**Comment by KalitaAlexey** [comment]
Look at #3567

**Comment by gregwebs** [comment]
oh, perfect! That didn't turn up in my initial search

**Comment by gregwebs** [comment]
Actually, I will keep this open since the PR is still open (maintainers may change according to their worfklows).

**Comment by gregwebs** [comment]
Ahh, I see there is already an issue too. Sorry, I probably should have been able to find these in my searching.
https://github.com/rust-lang/cargo/issues/2644
