### ISSUE TITLE
Local copy of crates

### ISSUE THREAD

**Issue by blodan** [rust-lang/cargo#3623]
I'm trying to create a package / port for FreeBSD of mozillas geckodriver.

However, FreeBSDs packagesystem does not allow a software access to internet during build which kind of borks out cargos entire build system.

How can I build a software with local crates? 

I figured I could just tar the registry folder where cargo downloads all the dependencies to and then untar it before i run cargo build again on the package build system, however, cargo doesnt seem to read the already downloaded crates from the registry folder where it stored them the first time around, but instead tries to contact github eventhough all dependencies are already present and downloaded in the registry folder.

How do I solve this particular problem? I need to be able to build geckodriver without internet, I can however download a tar before build with the crates and put it in the right place.

**Comment by steveklabnik** [comment]
This question is better asked on https://github.com/rust-lang/rust/pull/39427; cargo supports these features, but we try to keep the issue tracker for issues only. Thanks!
