### ISSUE TITLE
cargo doc should only include &self methods from Deref target

### ISSUE THREAD

**Issue by Storyyeller** [rust-lang/cargo#3641]
Currently, if Foo impls Deref<Target=Bar>, then the generated documentation for Foo will include every method defined on Bar, regardless of receiver type. &mut self methods should only be included if DerefMut is impled, and self methods shouldn't be included at all.

It may also be worth excluding methods on the Deref target from the generated documentation if a method of the same name is defined on the original type, since that's the one that will be called under normal circumstances.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is more of a rustdoc bug, though, so could you open a report over at rust-lang/rust?

**Comment by Storyyeller** [comment]
Done (https://github.com/rust-lang/rust/issues/39550)
