### ISSUE TITLE
Doc test errors should include line numbers

### ISSUE THREAD

**Issue by Storyyeller** [rust-lang/cargo#3643]
Current if I have an assertion failure in a doc test, the line number just says something like "anon:6", which isn't helpful in finding where the error is. It would be nice if the line numbers matched up to the actual file containing the documentation.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a rustdoc bug, though, so could you open an issue against rust-lang/rust instead?

**Comment by Storyyeller** [comment]
Sorry, I wasn't sure where to file bugs about doc generation.

**Comment by alexcrichton** [comment]
No worries! In the meantime I'll close this.
