### ISSUE TITLE
Two different crates with name 'X' error only when using --target= 

### ISSUE THREAD

**Issue by nathanaeljones** [rust-lang/cargo#3665]
When compiling an integration test which uses the imageflow_tool rlib - and there is an imageflow_tool binary as well. Cannot reproduce on linux.

`Compiling imageflow_tool v0.1.0 (file:///C:/projects/imageflow/imageflow_tool)
error[E0523]: found two different crates with name `imageflow_types` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.`
from: 

https://ci.appveyor.com/project/imazen/imageflow/build/job/g5h6idn8kv3fwme9

```[package]
name = "imageflow_tool_lib"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"

[dependencies]
imageflow_core = { path = "../imageflow_core", version = "*" }
imageflow_types = { path = "../imageflow_types", version = "*" }
libc = "0.2.0"
clap = "2"
time = "*"
rustc-serialize = "*"
threadpool = "1.0"
serde = "*"
serde_json = "*"
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }

[[bin]]
name = "flow-proto1"
path = "src/bin/flow-proto1.rs"

[[bin]]
name = "imageflow_tool"
path = "src/main.rs"
doc = false
```

Any ideas?

**Comment by alexcrichton** [comment]
Is there a way to reproduce this locally, and if so how?

**Comment by nathanaeljones** [comment]
It's a recent regression (since November). I'm not sure where to look - but if nobody else does either, I will try to spin up a vm and narrow down a case.

**Comment by nathanaeljones** [comment]
I can repro this outside of Windows if I invoke cargo with a target: `cargo test --target=x86_64-unknown-linux-gnu`

Since fingerprints are involved, could #3658 be involved, or can that be ruled out? I haven't gotten any successes, so failure appears deterministic... but sometimes the odds of a consistent result are just incredibly low.

**Comment by nathanaeljones** [comment]
It appears to be non-deterministic - or, at least, it works sometimes, and I haven't isolated a useful variable.

**Comment by alexcrichton** [comment]
Can you describe how to reproduce this succinctly? Inferring [from the logs](https://ci.appveyor.com/project/imazen/imageflow/build/job/g5h6idn8kv3fwme9) I cloned https://github.com/imazen/imageflow and then went inside `imageflow_tool` to build, but was met with the error:

```
error: couldn't read "/home/alex/code/imageflow/imageflow_core/conan_cargo_build.rs": No such file or directory (os error 2)

Build failed, waiting for other jobs to finish...
error: Could not compile `imageflow_core`.

To learn more, run the command again with --verbose.
```

**Comment by nathanaeljones** [comment]
I've struck out so far on creating a repro project. To get it building, you'll need to install `conan`, which can fetch the C dependencies.

**Comment by nathanaeljones** [comment]
I got the  metadata count to 1, so this seems deterministic again. 

For a local build, `./build.sh debugtarget64linux` should reproduce the issue.

**Comment by nathanaeljones** [comment]
Strangely enough, this workspace does *not* repro the issue: https://github.com/nathanaeljones/cargo_bug_name_conflict

**Comment by nathanaeljones** [comment]
If you want to repro this in a published docker container, this should work  (no `conan` required):

`cd imageflow_server && ./dockerize.sh debugtarget64linux docker tool`

**Comment by alexcrichton** [comment]
Hm that just printed this out?

```
[code/imageflow/imageflow_server[master]] $ ./dockerize.sh debugtarget64linux docker tool                                                                       [alex@acrichton-desktop] 
./dockerize.sh debugtarget64linux docker tool                                                                                                                                            
help: ./dockerize.sh (debug|quiet[123]|release|clean|valgrind|test|rusttest)+ localbuild|docker server|tool #SMOKE TESTS ONLY                                                            
Cannot find /home/alex/.docker_imageflow_caches/.docker_build_if_gcc54_cache/target/debug                                                                                                
                                                                                                                                                                                         
=================== Compiling ======================                                                                                                                                     
BINARY_OUT=/home/alex/.docker_imageflow_caches/.docker_build_if_gcc54_cache/target/debug/imageflow_tool                                                                                  
./test.sh: line 183: conan: command not found                                                                                                                                            
```

**Comment by nathanaeljones** [comment]
It doesn't use docker for compilation unless you pass it those flags.

**Comment by nathanaeljones** [comment]
I guess I lied. You *should* be able to comment out line 183, as the file ownership issue it resolves may not apply to you. 

Also delete lines 112/113 to prevent sharing of the host ~/.cargo folder (unless that's desired). 

To cleanup, delete ~/.docker_imageflow_caches

**Comment by nathanaeljones** [comment]
(note that the host ~/.cargo is *copied* into the instance. The host ~/.cargo is never modified).

**Comment by nathanaeljones** [comment]
Let me get you a better repro tool.

**Comment by nathanaeljones** [comment]
This is a stateful bug. One must build without the same target twice, once implicitly, once explicitly.

`cd imageflow_tool && cargo build --test test_tool && cargo build --test test_tool --target x86_64-unknown-linux-gnu` 

Still working on better repro.

**Comment by nathanaeljones** [comment]
```
error[E0523]: found two different crates with name `imageflow_types` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> tests/test_tool.rs:1:1
  |
1 | extern crate imageflow_tool_lib;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `imageflow_tool_lib`.

Caused by:
```

```
  process didn't exit successfully: `rustc --crate-name imageflow_tool src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=94c521babddb8470 -C extra-filename=-94c521babddb8470 --out-dir /home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu 

-L dependency=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps 
-L dependency=/home/n/Documents/imazen/imageflow/target/debug/deps 
--extern imageflow_helpers=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libimageflow_helpers-0edcf1274a98db2e.rlib 
--extern clap=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libclap-500ee8bb9b944a99.rlib 
--extern time=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libtime-cd5e3a346d1a17b6.rlib 
--extern threadpool=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libthreadpool-f0446a4715142f26.rlib 
--extern imageflow_core=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libimageflow_core-620935e05fea8da2.rlib 
--extern serde_json=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libserde_json-4d0e79b6e35d2df7.rlib 
--extern serde=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libserde-eb150695fea2362e.rlib 
--extern libc=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/liblibc-2a4507ee5e52ea3e.rlib 
--extern imageflow_types=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libimageflow_types-8b8a15cc3fa7e88f.rlib 
--extern rustc_serialize=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/librustc_serialize-2c0b16b7ceb9fdcb.rlib 
--extern imageflow_tool_lib=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/deps/libimageflow_tool_lib-ed225bec2e2b20b8.rlib 
-L /home/n/.conan/data/OpenSSL/1.0.2j/lasote/stable/package/8dc0071dc4241826d308f93b7589b40fa9c51286/lib 
-L native=/home/n/Documents/imazen/imageflow/target/x86_64-unknown-linux-gnu/debug/build/miniz-sys-18005000ddedadf4/out 
-L native=/home/n/.conan/data/OpenSSL/1.0.2j/lasote/stable/package/8dc0071dc4241826d308f93b7589b40fa9c51286/lib 
-L native=/home/n/.conan/data/imageflow_c/0.1.0/imazen/testing/package/9590d048412ceec2ab01993c362139477de0da0d/lib 
-L native=/home/n/.conan/data/libjpeg-turbo/1.5.1/imazen/testing/package/5dfb956a1439c84606389c92be7ec45b23c2e716/lib 
-L native=/home/n/.conan/data/libpng/1.6.21/lasote/stable/package/4bed5bcecebb11c5b891863880f3ef10411fb2da/lib 
-L native=/home/n/.conan/data/littlecms/2.7/lasote/stable/package/3a5f72c8cd50641b8efa6ed13e6914c6ced2747c/lib 
-L native=/home/n/.conan/data/zlib/1.2.8/lasote/stable/package/755fc07adbed235a7d3eadec4b6882d4912f09bc/lib` (exit code: 101)
```

**Comment by alexcrichton** [comment]
@nathanaeljones I still can't seem to reproduce, an easy docker image or a strict set of instructions of how to reproduce from a checkout would be great!

**Comment by nathanaeljones** [comment]
It... came back. This time with a crate not under my control, and *without* any implicit builds. And only on 32-bit, not on 64-bit.

```
   Compiling imageflow_abi v0.1.0 (file:///C:/projects/imageflow/imageflow_abi)
error[E0523]: found two different crates with name `backtrace` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
   --> src\lib.rs:130:1
    |
130 | extern crate imageflow_core as c;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: Could not compile `imageflow_abi`.

```
https://ci.appveyor.com/project/imazen/imageflow/build/626/job/jm0cmmx8tvp4f7gx#L6603

Only on windows. I have no theories.

**Comment by nathanaeljones** [comment]
It would appear that cargo now writes to both `/target/debug` and `/target/i686-pc-windows-msvc/debug` during a single command (such as `cargo check --all --target=i686-pc-windows-msvc`)

**Comment by alexcrichton** [comment]
@nathanaeljones is there a way to reproduce this locally? The AppVeyor logs look quite intimidating :(

**Comment by nathanaeljones** [comment]
I put ~16 hours or so into trying to repro this separately in a smaller project. Given I have limited knowledge of how Cargo is even *supposed* to behave, it's hard to for me to make educated hypothesis and test them. 

Good news - I don't think there are interacting non-deterministic bugs involved, so you won't have to build it in a loop. 

Conan is a prerequisite for build Imageflow on any platform - it handles the C dependencies, then passes the paths off to Cargo via build scripts. The latest incarnation of the bug (which seems to have a wider scope) was reproduced on windows. If you have VS 2015, Conan, Git, CMake, and Nasm installed, then it should be straightforward to build commit 6c71c659. https://github.com/imazen/imageflow#windows

**Comment by Kixunil** [comment]
I'm not sure if I did hit this bug or something else but here are my steps:

* Create a cargo project with two binaries (e.g. `main` and `test`)
* Make both binaries depend on the same crate (i'm not sure if crates.io work; I did it with my local crate, using path = "../my_crate")
* Try `cargo build` - works
* Try `cargo build --target=...` - works
* Try `cargo check` - works
* Try `cargo check --target=...` - fails with the aforementioned message.

Not huge issue, but kinda surprising.

**Comment by alexcrichton** [comment]
@Kixunil I was unable to reproduce that locally, do you have a script which reproduces that behavior?

**Comment by Kixunil** [comment]
@alexcrichton it was nightly 1.19. I tried to update and it works now.

**Comment by carols10cents** [comment]
I'm going to close this due to a lack of activity and inability to reproduce. Please reopen if this comes up again and you have reproduction steps! Thank you!
