### ISSUE TITLE
Cannot lock file on lustre filesystem

### ISSUE THREAD

**Issue by z1mvader** [rust-lang/cargo#3666]
When I tried to install Cargo and Rust under a lustre filesystem using rustup I got the following error after trying to build a simple crate:

```
$ cargo run
error: failed to lock file: ~/simple_crate/Cargo.lock

Caused by:
  Function not implemented (os error 38)
```

It would be nice to let Cargo handle missing flock() by not locking? (durka42)
```

**Comment by alexcrichton** [comment]
Sounds good to me! I believe the relevant support would go [here](https://github.com/rust-lang/cargo/blob/ef00a5352d4c2eb6fa42c28b9e966299eb84feb2/src/cargo/util/flock.rs#L250-L317). Would you be interested in sending a PR for this?

**Comment by z1mvader** [comment]
I would need some mentoring, but sure!

**Comment by alexcrichton** [comment]
Sure yeah I'd be happy to help! I think you'll basically want to add a clause [like the existing one for OSX](https://github.com/rust-lang/cargo/blob/ef00a5352d4c2eb6fa42c28b9e966299eb84feb2/src/cargo/util/flock.rs#L273-L277) except which matches the error code coming out of libc. I don't know precisely what 38 is but you can likely find what it is in the libc crate.

**Comment by z1mvader** [comment]
Ok! Hands on! Where can I write to you?

**Comment by alexcrichton** [comment]
Hm not sure I understand, can you elaborate?

**Comment by z1mvader** [comment]
I'm not sure how to start

**Comment by alexcrichton** [comment]
Oh sure yeah, so to start out you'll want to [compile from source](https://github.com/rust-lang/cargo#compiling-from-source) to ensure that's working. After that you can likely run `cargo test` to ensure all tests are passing.

Once that's all taken care of you can toy around modifying the [relevant match block](https://github.com/rust-lang/cargo/blob/ef00a5352d4c2eb6fa42c28b9e966299eb84feb2/src/cargo/util/flock.rs#L273-L277) and see if that fixes tests for you.

If that's all working, then you can [send a PR](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)!

**Comment by z1mvader** [comment]
ok i found 38

https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/constant.ENOSYS.html

**Comment by alexcrichton** [comment]
Ah yeah that looks right! (for a constant to check against)

**Comment by z1mvader** [comment]
That would be enough? or there is something else to be done?

**Comment by alexcrichton** [comment]
In theory that's it, but you may want to test out the cargo binary locally to ensure you don't get the same error

**Comment by z1mvader** [comment]
Ok, I have a logistical problem. I cannot build it using cargo because it won't lock Cargo.lock, but I don't have cmake (and cannot install it because I'm not su) to run ./configure

**Comment by alexcrichton** [comment]
Heh that would indeed cause problems! Could you build it in /tmp perhaps which may not be the same filesystem?

**Comment by z1mvader** [comment]
Almost there. However the cargo registry is still in my home folder on lustre, how can I change this path?

**Comment by alexcrichton** [comment]
Oh you can probably do CARGO_HOME=/tmp/cargo

**Comment by z1mvader** [comment]
It failed:

```
note: /usr/bin/ld: /tmp/make_temp/cargo/target/release/deps/libopenssl_sys-59e7705a3169e032.rlib(s23_meth.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/tmp/make_temp/cargo/target/release/deps/libopenssl_sys-59e7705a3169e032.rlib: could not read symbols: Bad value
collect2: ld returned 1 exit status

```

**Comment by alexcrichton** [comment]
It seems that somehow you've picked up a statically linked version of OpenSSL as opposed to a dynamic version. You wouldn't happen to know why, would you?

**Comment by z1mvader** [comment]
I had to compile it myself, i suppose i need some flag on the ./configure?

**Comment by z1mvader** [comment]
Ok it compiled, then i ran "cargo test" and it failed:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at '/buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/filesearch.rs:157: failed to get realpath: No such file or directory (os error 2)', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:784
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by z1mvader** [comment]
However it is not reproducible, if i run the tests again other ones fail

**Comment by z1mvader** [comment]
Ok. I had to compile openssl and download the cmake binaries to make this work. I can build cargo correctly, but some test fail randomly. This is what i've been doing

https://gist.github.com/z1mvader/9185f4a8f18adefe516d63b4b338469a

I'll work on this tomorrow

**Comment by z1mvader** [comment]
Ok, there is a pattern on the random failures of tests. Everytime one of them fails. This error appears somewhere:

```
thread 'rustc' panicked at '/buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/filesearch.rs:157: failed to get realpath: No such file or directory (os error 2)', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:784
```

**Comment by z1mvader** [comment]
hey I just tested cargo on the same filesystem and this still happens, any suggestions?

**Comment by alexcrichton** [comment]
Does the [proposed fix](https://github.com/rust-lang/cargo/pull/3671) not work?

**Comment by z1mvader** [comment]
Apparently not, but when I PR the fix it worked compiling cargo from source

**Comment by alexcrichton** [comment]
The code is [still there](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/flock.rs#L279-L280), so I'm not sure :(

**Comment by z1mvader** [comment]
Ok i just rechecked:

`error: failed to write ~/some_crate/Cargo.lock

Caused by:
  failed to lock file: ~/some_crate/Cargo.lock

Caused by:
  Function not implemented (os error 38)
`
According to the [libc docs](https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/constant.ENOSYS.html), `libc::ENOSYS` is 38.

Am I missing something?

**Comment by alexcrichton** [comment]
Are you sure the version of Cargo you're using has the fix?

**Comment by z1mvader** [comment]
I hate myself, yeah I forgot to set nightly as default. Thanks Alex
