### ISSUE TITLE
Cargo hangs on Windows 7

### ISSUE THREAD

**Issue by rofrol** [rust-lang/cargo#3673]
rustup-init.exe on Windows 7 installs cargo.exe that hangs. I've copied cargo.exe from Windows 10 and it works. Also cargo from toolchains directory works.

Here `~/.cargo` is the one copied from Windows 10, and `/.cargo.bad` is the one installed by `rustup-init.exe`.

```
$ ls -lh ~/.cargo*/*
/c/Users/frolowr/.cargo.bad/bin:
total 27M
-rwxr-xr-x 6 frolowr 1049089 4,5M lut  8 02:34 cargo.exe*
-rwxr-xr-x 6 frolowr 1049089 4,5M lut  8 02:34 rustc.exe*
-rwxr-xr-x 6 frolowr 1049089 4,5M lut  8 02:34 rustdoc.exe*
-rwxr-xr-x 6 frolowr 1049089 4,5M lut  8 02:34 rust-gdb.exe*
-rwxr-xr-x 6 frolowr 1049089 4,5M lut  8 02:34 rust-lldb.exe*
-rwxr-xr-x 6 frolowr 1049089 4,5M lut  8 02:34 rustup.exe*

/c/Users/frolowr/.cargo/bin:
total 44M
-rwxr-xr-x 1 frolowr 1049089 7,3M lut  8 03:03 cargo.exe*
-rwxr-xr-x 1 frolowr 1049089 7,3M lut  8 03:03 rustc.exe*
-rwxr-xr-x 1 frolowr 1049089 7,3M lut  8 03:03 rustdoc.exe*
-rwxr-xr-x 1 frolowr 1049089 7,3M lut  8 03:03 rust-gdb.exe*
-rwxr-xr-x 1 frolowr 1049089 7,3M lut  8 03:03 rust-lldb.exe*
-rwxr-xr-x 1 frolowr 1049089 7,3M lut  8 03:03 rustup.exe*
```

**Comment by alexcrichton** [comment]
Thanks for the report! We shouldn't special case installs on versions of Windows, so maybe these are different versions of Rustup? Also, to be clear, these are rustup wrappers that are hanging, right? Or Cargo itself?

**Comment by rofrol** [comment]
How can I know if it's wrapper?

**Comment by alexcrichton** [comment]
If you installed through rustup (which looks to be the case if you used rustup-init.exe) then these'd all be wrappers. In that sense I think this is a rustup bug if at all?

**Comment by rofrol** [comment]
I've created git repo and copied `.cargo` and `.rustup` from window 10 installation.

Then overwritten it with `.cargo` and `.rustup` from window 7 installation.

There is no diff.

So maybe it's something with privileges? The win7 is a corporate windows installation.

**Comment by rofrol** [comment]
Closing in favor of https://github.com/rust-lang-nursery/rustup.rs/issues/1075
