### ISSUE TITLE
should be searchable

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#3678]
Either a single page version of documentation should be provided or the documentation should be made searchable – its pain having to check all the pages which could be at least remotely useful.

**Comment by steveklabnik** [comment]
this is gonna end up being an upstream bug https://github.com/azerupi/mdBook/issues/51

**Comment by DarkDrek** [comment]
The upstream issue has been closed and the their documentation has a search https://rust-lang-nursery.github.io/mdBook/.
Maybe the cargo documentation https://doc.rust-lang.org/cargo/ has to be regenerated using the newest version?

**Comment by ehuss** [comment]
The beta (https://doc.rust-lang.org/beta/cargo/) or nightly (https://doc.rust-lang.org/nightly/cargo/) docs have search.  The stable docs should pick up the change during the next release (~6 weeks).

**Comment by nagisa** [comment]
Thanks!
