### ISSUE TITLE
Alternative to RUSTFLAGS that allows spaces within arguments

### ISSUE THREAD

**Issue by Jascha-N** [rust-lang/cargo#3686]
I'm working on a build tool for setting up a cargo environment to build projects that depend on Arduino cores and libraries. It detects the target architecture, compiler locations and arguments, linker location and arguments and a bunch of other stuff that needs to be passed to `rustc` based on a given Arduino board specification. Currently I pass these arguments using the `RUSTFLAGS` environment variable, Things like the linker path and linker script can point to arbitrary files on the file system and can thus contains spaces. Neither `RUSTFLAGS` nor `CARGO_BUILD_RUSTFLAGS` support spaces in arguments and generating a `.cargo/config` file that could possibly overwrite a user specified config file is also not an option. What are my options?

And another question. Does the `CARGO_BUILD_TARGET` variable not work or could this be a problem on `xargo`'s end?

Thanks!

**Comment by alexcrichton** [comment]
If you're not willing to use `.cargo/config`, another option would be to change the compiler entirely to a wrapper of some form you provide around the real compiler, although that's not guaranteed to work in all situations.

Also I'm not so sure about xargo :(

**Comment by Jascha-N** [comment]
Thanks.

> If you're not willing to use .cargo/config, another option would be to change the compiler entirely to a wrapper of some form you provide around the real compiler, although that's not guaranteed to work in all situations.

That seems a little bit excessive, but I guess it's possible.

If parsing quoted `RUSTFLAGS` arguments is out of the question it would at least be nice to be able to pass a custom config file location to `cargo`, either through an environment variable or a command line option. Another possibility is to allow `CARGO_` config overrides for lists/tables. For example: `CARGO_BUILD_RUSTFLAGS.0`, `CARGO_BUILD_RUSTFLAGS.1`, etc. or use JSON serialization for config overrides with composite data types.

If I'm not mistaken one of the goals for Cargo in 2017 is better integration into other build systems. Not having any (non-destructive) way to pass custom arguments with spaces to the compiler seems pretty limiting in this respect. No straightforward way to obtain the paths of generated artefacts is another.

For now, I'll go with your solution of creating a wrapper around the compiler.

**Comment by alexcrichton** [comment]
Yeah I'd be totally open to alternatives here in how to define env vars, and something like `FOO.n` where `n` is an index in an array sounds plausible at least!

Also for now RUSTC == CARGO_BUILD_RUSTC, we just added the former first and the latter fell out of blanket "read config from env vars as well"

**Comment by jyn514** [comment]
You can do this today with `-Z unstable-options --config build.rustflags="$RUSTFLAGS"`, the same way that docs.rs does: https://github.com/rust-lang/docs.rs/blob/bcc1a2c9f63a62907abbe68dcbe3f73632a9a4de/crates/metadata/lib.rs#L255-L263

**Comment by ehuss** [comment]
Closing as this is mostly resolved now. There are several mechanisms for setting flags that have spaces in them:

* [`CARGO_ENCODED_RUSTFLAGS`](https://doc.rust-lang.org/cargo/reference/environment-variables.html) uses the `\x1f` character to separate arguments.
* The [`--config`](https://doc.rust-lang.org/cargo/reference/config.html#command-line-overrides) CLI option can pass arbitrary TOML.
* Flags can be set in `cargo.toml` with `build.rustflags` and other variants.
* (nightly only, undocumented) `-Z advanced-env` with `CARGO_BUILD_RUSTFLAGS` supports TOML values
