### ISSUE TITLE
[RFE] expose tokenized target dependency via cargo-metadata

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/cargo#3688]
For 3rd-party tools it would be very cool to not implement own tokenizer as it's done in cargo. Not sure what would be best syntax for it though.

```json
    {
      "name": "openssl-sys",
      "source": "registry+https://github.com/rust-lang/crates.io-index",
      "req": "^0.9",
      "kind": null,
      "optional": true,
      "uses_default_features": true,
      "features": [],
      "target": "cfg(all(unix, not(target_os = \"macos\")))"
    }
```

**Comment by alexcrichton** [comment]
The syntax for this is currently defined in [RFC 1361](https://github.com/rust-lang/rfcs/blob/master/text/1361-cargo-cfg-dependencies.md#detailed-design), and while I do agree it'd be nice to expose a parsed version it should be able to build a parser out of tree as well (or extract Cargo's to a standalone crate)

**Comment by ignatenkobrain** [comment]
oh, thanks for the reference to RFC! we'll build our own parser in Fedora Rust packaging.

**Comment by ehuss** [comment]
I'm going to close this as cfg parsing is now extracted into a separate crate: [cargo-platform](https://crates.io/crates/cargo-platform).
