### ISSUE TITLE
Create test project inside temporary directory

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3690]
If I understand correctly, currently we create test projects inside a `target` directory. Why are we not using a temporary directory `/tmp` for this purposes? 

I've just spend some time investigating why a simple test run for more than one minutes, and it turned out that the cargo spawned by the test process was actually compiling cargo from the ancestor directory :rofl:

**Comment by alexcrichton** [comment]
I think the vague idea was to avoid polluting global state if tests went south (which they definitely do sometimes), but other than that I don't personally have a concrete reason.

I know that running cargo in the target dir has tripped me up before when it picked up hierarchical configuration.

**Comment by matklad** [comment]
>I think the vague idea was to avoid polluting global state if tests went south

Hm, if we create a temporary directory with semi-random name and clean it up in `Drop` then we should not pollute anything? Basically, https://github.com/rust-lang-nursery/tempdir should do the right thing? 

Or do you mean that sometimes we **want** the tests to leave the data around for post-mortem?

**Comment by alexcrichton** [comment]
Nah it's moreso ctrl-c doesn't clean up temporary state, not that panic doesn't

**Comment by alexcrichton** [comment]
But that's also true that I've on occasion cd'd into test directories to poke around and debug failures.

**Comment by matklad** [comment]
Yeah, that makes sense! Let's close this then!

I can imagine hacks to prevent Cargo from looking above target: we can add a bogus `.cargo/config` and `Cargo.toml` in the directory above the project directory, but this seems like some work without much benefit!
