### ISSUE TITLE
'cargo install' with no args should build and install local project

### ISSUE THREAD

**Issue by thibran** [rust-lang/cargo#3697]
Usability wise I think it would be nice if running `cargo install` with no further arguments in a cargo project would do the same as running `cargo install --path .`.

**Comment by alexcrichton** [comment]
I believe this is already the case, but what version of Cargo are you using? Maybe it needs an update?

**Comment by thibran** [comment]
`cargo 0.16.0-nightly (6e0c18c 2017-01-27)`

Hmmm, it works. Now I'm confused. I had the impression that I couldn't install my local project when using `cargo install`, than I tried with `cargo install --path .` and it worked. Sorry for taking some of your time.

**Comment by alexcrichton** [comment]
Ah no worries!
