### ISSUE TITLE
Possible regression bug in workspaces handling

### ISSUE THREAD

**Issue by nbaksalyar** [rust-lang/cargo#3698]
Cargo/rustc behavior has changed from 1.14 to 1.15 when building libraries within workspaces.

E.g. here's the output for 1.14:

```
$ cargo build --release
Compiling safe_app v0.1.0
...
$ ls ../target/release/deps/
libsafe_app.so
libsafe_app.rlib
libsafe_app.a
```
And there's also `libsafe_app.so` in `../target/release`.

Now, after I switch my toolchain to 1.15 in rustup, a hash is appended to output file names:
```
$ cargo build --release
Compiling safe_app v0.1.0
...
$ ls ../target/release/deps/
libsafe_app-98e60e5e55f57beb.so
libsafe_app-98e60e5e55f57beb.a
libsafe_app-98e60e5e55f57beb.rlib
```
And, more importantly, there's nothing in the `../target/release/` directory.

At the same time it still works correctly for non-workspaced projects and I can find the library file copied to the `target/release/` dir.

This breaks continuous integration scripts on 1.15 for projects that use workspaces.

**Comment by matklad** [comment]
>And there's also libsafe_app.so in target/release`.

Do you mean `../target/release`, or `./target`. If there were two different target directories, than that means that some package was actually outside the workspace.

**Comment by nbaksalyar** [comment]
@matklad yep, clarified that - thanks!

**Comment by alexcrichton** [comment]
Ah yes I think this is a dupe of https://github.com/rust-lang/cargo/issues/3674, fixed in https://github.com/rust-lang/cargo/pull/3478 and caused by https://github.com/rust-lang/cargo/issues/3221.

Could you test beta to make sure it works?

**Comment by nbaksalyar** [comment]
> Could you test beta to make sure it works?

Yes, it works! Thanks! :)

**Comment by alexcrichton** [comment]
Ok, thanks for checking!
