### ISSUE TITLE
Empty release folder created

### ISSUE THREAD

**Issue by alexbowers** [rust-lang/cargo#3709]
If I have a project which has a `.cargo/config` file in it, which contains:

```
[build]
target = "x86_64-unknown-linux-gnu"
```

and then run `cargo build --release`, I get the following structure.

![image](https://cloud.githubusercontent.com/assets/842974/22986509/b5d5f644-f3a3-11e6-9549-a9c839aa615d.png)

with `target/release` containing nothing.

![image](https://cloud.githubusercontent.com/assets/842974/22986521/c1961c02-f3a3-11e6-924f-0d2d685f77e5.png)

**Comment by alexbowers** [comment]
Cargo version:

`cargo 0.15.0-nightly (298a012 2016-12-20)`

**Comment by alexcrichton** [comment]
Ah yeah this is expected behavior, but thanks for the report! The `target/release` folder is used for artifacts like build scripts and plugins, so Cargo prepares it in advance unconditionally
