### ISSUE TITLE
[REGRESSION] cargo metadata looks into $HOME/Cargo.toml

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/cargo#3718]
```
[brain@ignatenko-w541 bitflags-0.8.0]$ cargo --version
cargo 0.15.0 (built 2017-02-07)
[brain@ignatenko-w541 bitflags-0.8.0]$ cargo metadata
{"packages":[{"name":"bitflags","version":"0.8.0","id":"bitflags 0.8.0 (path+file:///home/brain/rpmbuild/BUILD/bitflags-0.8.0)","license":"MIT/Apache-2.0","license_file":null,"source":null,"dependencies":[],"targets":[{"kind":["lib"],"name":"bitflags","src_path":"/home/brain/rpmbuild/BUILD/bitflags-0.8.0/src/lib.rs"},{"kind":["test"],"name":"external","src_path":"/home/brain/rpmbuild/BUILD/bitflags-0.8.0/tests/external.rs"},{"kind":["test"],"name":"external_no_std","src_path":"/home/brain/rpmbuild/BUILD/bitflags-0.8.0/tests/external_no_std.rs"},{"kind":["test"],"name":"i128_bitflags","src_path":"/home/brain/rpmbuild/BUILD/bitflags-0.8.0/tests/i128_bitflags.rs"}],"features":{"i128":[],"unstable":["i128"]},"manifest_path":"/home/brain/rpmbuild/BUILD/bitflags-0.8.0/Cargo.toml"}],"workspace_members":["bitflags 0.8.0 (path+file:///home/brain/rpmbuild/BUILD/bitflags-0.8.0)"],"resolve":{"root":"bitflags 0.8.0 (path+file:///home/brain/rpmbuild/BUILD/bitflags-0.8.0)","nodes":[{"id":"bitflags 0.8.0 (path+file:///home/brain/rpmbuild/BUILD/bitflags-0.8.0)","dependencies":[]}]},"version":1}

...

[brain@ignatenko-w541 bitflags-0.8.0]$ cargo --version
cargo 0.16.0 (built 2017-02-14)
[brain@ignatenko-w541 bitflags-0.8.0]$ cargo metadata
error: failed to parse manifest at `/home/brain/Cargo.toml`

Caused by:
  no `package` or `project` section found.
```

The problem is that I created empty `~/Cargo.toml` for something else and forgot to remove it which broke normal cargo operations (in my case `cargo metadata`)...

**Comment by ignatenkobrain** [comment]
The `cargo build` is affected as well:

```
+ /usr/bin/cargo build --release -j8
error: failed to parse manifest at `/home/brain/Cargo.toml`
```

**Comment by cuviper** [comment]
I think cargo now walks up the directory tree looking for a parent workspace -- finding your ~/Cargo.toml.

**Comment by ignatenkobrain** [comment]
@cuviper that seems weird... especially if I would have multiple subdirectories with different projects...

**Comment by cuviper** [comment]
But you would probably not put those different projects with one in a subdirectory of another, would you?

Anyway, I think that would probably still work fine if every Cargo.toml is well-formed.  The issue as I see it here is that it found an *invalid* (empty) Cargo.toml and treated this as a fatal error.  I think it would be reasonable to expect cargo to just ignore such errors. (assuming it had already found a more immediate file as the primary.)

**Comment by alexcrichton** [comment]
Yeah ignoring invalid Cargo.toml as we traverse upwards looking for a root sounds reasonable to me!

**Comment by matklad** [comment]
>Yeah ignoring invalid Cargo.toml as we traverse upwards looking for a root sounds reasonable to me!

We've just recently fixed cargo in the opposite direction: https://github.com/rust-lang/cargo/pull/3409 :)

I think that the current behavior of not silently ignoring errors in `Cargo.toml` is the correct one, because problems like the one in https://github.com/rust-lang/cargo/issues/3407 are much harder to diagnose and fix.

And here the error is a very reasonable one:

```
error: failed to parse manifest at `/home/brain/Cargo.toml`

Caused by:
  no `package` or `project` section found.
```

But it is indeed can be surprising that now Cargo walks the directory tree up.

**Comment by ignatenkobrain** [comment]
@matklad I've created Cargo.toml in my $HOME just for testing purpose and even forgot about that and was very surprised, why cargo looks into it.

**Comment by alexcrichton** [comment]
@matklad oh right thanks for refreshing my memory! At least I can rest easy knowing that if such a change were implemented the tests would have caught it :)

In that case though I'm going to close this as this is currently a deliberate decision.
