### ISSUE TITLE
`cargo init` no longer handles pre-existing source files nicely

### ISSUE THREAD

**Issue by vi** [rust-lang/cargo#3722]
#3004 broken it a bit.

Previously Cargo looked for files like `main.rs`, `src/main.rs`, `lib.rs`, `src/lib.rs`, `projectname.rs` and `src/projectname.rs` and created `[[bin]]` and/or `[lib]` sections in `Cargo.toml` automatically if source files located unusually. 

Now it does look for those files, but fails to use this information meaningfully and just creates `src/main.rs` or `src/lib.rs` instead of using sections in Cargo.toml even if a usable source file outside `src` already exists, making the "hello world" lib or app while previously it used pre-existing source code.

What shall be done? Options:

* Remove any auto-detection code. Rely only on explicit `--lib`/`--bin`. Don't look at any files except of `src/{main,lib}.rs`
* Implement insertion of `[[bin]]` and `[lib]` again (when `--template` is not in use)
* Make Cargo move pre-existing source file to the appropriate location in `cargo init`, e.g `myapp/myapp.rs` becomes `myapp/src/main.rs`.

**Comment by alexcrichton** [comment]
cc @ehiggs, mind taking a look?

**Comment by alexcrichton** [comment]
My gut would say that we should preserve the original behavior, inserting `[[bin]]` and `[lib]` but perhaps only when `--template` isn't specified.

**Comment by ehiggs** [comment]
Hi.
I guess I misinterpreted the code and thought it was only trying to avoid clobbering the existing files. I hope I at least preserved that aspect of the behaviour.

>My gut would say that we should preserve the original behavior, inserting [[bin]] and [lib] but perhaps only when --template isn't specified.

Is this based on the flag used on the command line or is there any possibility that the code is grepped for `fn main()`?

**Comment by vi** [comment]
Yes, code was indeed grepped for `fn main` in some cases.

The idea is/was that user can begin playing with Rust without cargo, just with `rustc myprog.rs && ./myprog`, then may want to add a dependency. Only now he things about (or even discovers) Cargo and now wants a Cargo project, not just `myprog.rs`. `cargo init` was designed to seamlessly allow `cargo test` or `cargo run` without user manually arranging their source code for Cargo's convention or reading docs to find out `[[bin]]` or whatever sections.

The algorithm approximately like this:

* Detect project name from directory. If bad name then err.
* Look for `src/main.rs`, `src/lib.rs`, `src/<projectname>.rs`, `main.rs`, `lib.rs`, `<projectname.rs`.
* If nothing found, create `src/lib.rs` (or `src/main.rs` if `--bin`).
* If it is `<projectname>.rs` or `src/<projectname>.rs` and no `--bin` specified then grep for `fn main`.
* Determine if a file is located by conventions. If not, create `[[bin]]` or `[lib]`.
* If both `lib.rs` and `src/lib.rs` exist, fail and refuse to create any project.

The scheme may be improved: if nothing of `[src/]{main,lib,<projectname>}.rs` exists but there is just one `*.rs` source file in the entire project, it can be used as basis. More notices can be printed to user if source directory scheme is confusing or non-standard. Like `Source source file .... is named and located ..., but guidelines recommend it to be src/main.rs. [[bin]] section was added automatically to Cargo.toml to accommodate to this.`. There may be `--move` option of `cargo init` to allow moving source files around. There may be helpful message like `A dummy source file created at src/lib.rs. Please overwrite it with some of your actual source code` in case of there are existing sources, but Cargo's heuristics failed to determine what should be the root of the project.

**Comment by ehiggs** [comment]
>There may be --move option of cargo init to allow moving source files around.

Based on my reading of the git log, there has never been a `--move` option to init. My understanding was that this issue is to fix the regression. New features should go in a new issue, imo.

So, I guess the issue is that in `init` the following from patch 800172fbe713670edab4d8c486b2e1e67d3a1038 was removed:

```
+    
+    let mut cargotoml_path_specifier = String::new();
+    
+    // Calculare what [lib] and [[bin]]s do we need to append to Cargo.toml
+    
+    for i in &opts.source_files {
+        if i.bin {
+            if i.relative_path != "src/main.rs" {
+                cargotoml_path_specifier.push_str(&format!(r#"
+[[bin]]
+name = "{}"
+path = {}
+"#, i.target_name, toml::Value::String(i.relative_path.clone())));
+            }
+        } else {
+            if i.relative_path != "src/lib.rs" {
+                cargotoml_path_specifier.push_str(&format!(r#"
+[lib]
+name = "{}"
+path = {}
+"#, i.target_name, toml::Value::String(i.relative_path.clone())));
+            }
+        }
+    }
+
+    // Create Cargo.toml file with necessary [lib] and [[bin]] sections, if needed
 ```

**Comment by vi** [comment]
Yes. The tests were testing that the project is buildable after `cargo init`, but didn't test that it is uses the pre-existing source file instead of newly generated.

**Comment by alexcrichton** [comment]
@ehiggs yeah the intention here was to just pick up what exists (if possible) and otherwise fill in gaps that are missing.

Do you think it'd be a small change to reinstate the existing behavior?

**Comment by vi** [comment]
There should be additional tests to prevent similar breakage in future, so the change is not going to be trivial.

**Comment by ehiggs** [comment]
I agree with @vi.

**Comment by vi** [comment]
@ehiggs , Are you planning on resolving the issue yourself or I should [someday] prepare my own pull request?

Further advancements for `cargo init`'s existing code detection should probably be out of scope for this issue and come in a separate PR.

**Comment by ehiggs** [comment]
I'm sorry I was unresponsive this week. I've been very busy. I can take a look.

First, the test. What test is needed here? At least three to prevent further regressions:

1. Create `src` dir with `src/main.rs` and make sure that `cargo init` creates a `Cargo.toml` with a `[[bin]]` section.

2. Create `src` dir with `src/lib.rs` and make sure that `cargo init` creates a `Cargo.toml` with no `[[bin]]` section.

3. Create `src` dir with `src/foo.rs` with `fn main() {}` in it and make sure that `cargo init` creates a `Cargo.toml` with a `[[bin]]` section.

**Comment by vi** [comment]
@ehiggs , Yes.

"3." -> And also not create `src/main.rs`.

"4." -> And also not create `src/lib.rs`.

The same for source code without `src/` that just neighbouring newly created `Cargo.toml`.

**Comment by ehiggs** [comment]
@vi, please review #3767 when you get a chance. Thanks

**Comment by vi** [comment]
Checked c7d904a61dab69eef11d708f701d249a4d14d0e2.

@ehiggs , Outstanding issues:

* It still prints `Created library project` even if it auto-detected a bin project and added the section.
* Likewise `Created binary (application) project` is printed if one issues `cargo init --bin` in a directory with source code suggesting a library.

Otherwise looks OK. Fortunately `Cargo.lock` presence in `.gitignore` does not depend on `--bin`.

Future ideas about `cargo init` (out of scope for this issue):

* Automatic `license-file:` if `COPYING` or something like that is found
* More versatile heuristic detection for existing source code (e.g. not limiting to just three variants). Detecting project name based on source file name instead of directory name (especially if directory name is bad like `123`).
* Auto-creation of an example for library projects.

**Comment by ehiggs** [comment]
>Likewise Created binary (application) project is printed if one issues cargo init --bin in a directory with source code suggesting a library.

This seems like correct behaviour. The user explicitly specified a bin project but hasn't written a main function. That seems like a bad idea to override.

>It still prints Created library project even if it auto-detected a bin project and added the section.

Ok, we can fix this. In line with the above, I think the detection step should only take place if there was no explicit `--lib`. Ignoring the user's explicit directions is bad UI imo.

**Comment by vi** [comment]
It may be reasonable to avoid adding any `[lib]` or `[[bin]]` in base of `--lib` or `--bin` and creating template `src/lib.rs` or `src/main.rs` (unless they already exist), ignoring other non-standard source locations.

**Comment by ehiggs** [comment]
I took a look at fixing this final issue with the output. I thought the best way to fix it would be to return the Workspace from `ops::init` and `ops::new` and then ask the Workspace if there are any binary targets:

```rust
// In impl Workspace:
    pub fn has_binary_targets(&self) -> bool {
        self.packages.packages.values()
            .any(|ref mp| {
                match *mp {
                    &MaybePackage::Package(ref p) => {
                        p.targets().iter().any(|t| { *t.kind() == TargetKind::Bin })
                    },                                                         
                    _ => false,
                }
            })
    }
```

But this doesn't work because Cargo is somehow a target for every project. If I put in a print statement in the above check for `TargetKind`, I get the following when I run my tests (see gist, below):
```
other output:
`Manifest Target: Target { kind: Lib([Lib]), name: "cargo", src_path: "/Users/ehiggs/src/download/cargo/src/cargo/lib.rs", required_features: None, tested: true, benched: true, doc: true, doctest: true, harness: true, for_host: false }
Manifest Target: Target { kind: Bin, name: "cargo", src_path: "/Users/ehigg90120/src/download/cargo/src/bin/cargo.rs", required_features: None, tested: false, benched: true, doc: false, doctest: false, harness: true, for_host: false }
`', /Users/ehiggs/.cargo/registry/src/github.com-1ecc6299db9ec823/hamcrest-0.1.1/src/core.rs:31
```

Is that correct? Should Cargo be a binary target for every workspace?

To reproduce, I have a patch here: https://gist.github.com/ehiggs/bd120ef8c9fe5cee89dea9c4223758d9
```

**Comment by alexcrichton** [comment]
Returning the workspace seems fine yeah, but I wonder if that's just a bug in cargo's tests? (i.e. how cargo runs its own tests in a subdir of itself)

**Comment by ehiggs** [comment]
Templates have been removed pending an RFC. There is a pre-RFC thread [here](https://internals.rust-lang.org/t/pre-rfc-cargo-templates/5056). I think this can be closed for now.

**Comment by alexcrichton** [comment]
Thanks @ehiggs!
