### ISSUE TITLE
Show a summary for each command (cargo --list)

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/cargo#3726]
Running cargo shows a list of commands with a summary for each, but cargo --list does not show a summary.

Probably a summary can just be showed for internal commands.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by dwijnand** [comment]
Had a look at this and two things:

1. The strings that `cargo` prints don't match the about of the commands. For example for `build`, `cargo` prints ["Compile the current project"](https://github.com/rust-lang/cargo/blob/0.28.0/src/bin/cargo/cli.rs#L163), while the about string is ["Compile a local package and all of its dependencies"](https://github.com/rust-lang/cargo/blob/0.28.0/src/bin/cargo/commands/build.rs#L8). Is that fine? Which one should `--list` output?

2. `--list` supports `-v` to output the path of the command (TIL!). Given the descriptions we want to add are for built-in commands, which don't have an associated "path", do you think it's fine to mix descriptions with paths, or is that confusing?
