### ISSUE TITLE
Separate ~/.cargo/credentials

### ISSUE THREAD

**Issue by tarcieri** [rust-lang/cargo#3748]
Originally from: https://github.com/rust-lang/crates.io/issues/78

Right now the crates.io API token used by cargo is stored in the `[registry.token]` section of `~/.cargo/config` (which, as it were, has `644` file permissions by default, i.e. world readable)

I think it would make more sense to separate credentials into a separate file (e.g. `~/.cargo/credentials` or `~/.cargo/token`) which always has `600`  file permissions and will warn or not function if the permissions are too loose

Some precedent here is RubyGems, which stores its equivalent credentials in a `~/.gem/credentials` file, which always has `600` permissions

**Comment by alexcrichton** [comment]
Sounds like a good idea to me!

**Comment by kmcallister** [comment]
This is a pretty big deal!

As another data point, OpenSSH will refuse to run if your file permissions aren't on point.

**Comment by sfackler** [comment]
I think this can be closed.

**Comment by tarcieri** [comment]
Nice! Glad to see this ship.
