### ISSUE TITLE
Add option to run given file's tests

### ISSUE THREAD

**Issue by amosbird** [rust-lang/cargo#3753]
Something like `cargo test --file <current-file>` would be really useful to implement quickrun command.

**Comment by alexcrichton** [comment]
Cargo doesn't currently have the knowledge or ability to do this I believe, it's a part of the test runner/test harness. If you're using the standard test harness, though, then you can probably get away with `cargo test $name_of_file`

**Comment by amosbird** [comment]
um, Is there any plan to support such feature? This would make quick testing more convenient like Python's main block and Java's main class.

**Comment by alexcrichton** [comment]
@matklad I'm curious, does IntelliJ handle this?

**Comment by matklad** [comment]
I would say it 90% handles it. We can run test from a Rust mod (`cargo test foo::bar::baz`) and from a test crate (`cargo test --test build`) and in the majority of cases a file corresponds to a module. 

We can also enumerate all the tests in a file, but there isn't an easy way to make the test harness execute several tests by name. But in my experience testing a mod is usually enough.

**Comment by alexcrichton** [comment]
@amosbird does that make sense?

**Comment by amosbird** [comment]
@alexcrichton I don't quite understand that. Say I'm writing `lib.rs` using emacs. How can I quickly run a selected code snippet inside current buffer?

**Comment by alexcrichton** [comment]
@amosbird I think the point is that this is where IDE integration steps in. Cargo has all the tools necessary but it's up to an IDE to drive Cargo at that point

**Comment by amosbird** [comment]
Ok, thanks for the clarification.
