### ISSUE TITLE
cargo test fails with tmpdir noexec (documentation tests only)

### ISSUE THREAD

**Issue by chifflier** [rust-lang/cargo#3756]
When running `cargo test` to run unit tests, the documentation tests are executed from `/tmp`, which is mounted as noexec on many distros (for security reasons).
This does not happen for other unit tests (using the `test` attribute), because they are build in `target/<build type>`.

Suggested solution: build documentation tests in the same directory ?

Example code:
```
/// ```
///
/// # fn main() { test1 () }
pub fn test1() {
}
```

And mount `/tmp` as noexec:
```
mount -o remount,noexec /tmp
```

**Comment by alexcrichton** [comment]
Unfortunately I think this is largely a rustdoc bug rather than a Cargo bug. Could you reopen an issue against rust-lang/rust?

**Comment by chifflier** [comment]
Hi Alex,

Thanks for your reply. Reopened as https://github.com/rust-lang/rust/issues/40065

**Comment by alexcrichton** [comment]
Thanks!
