### ISSUE TITLE
cargo build doesn't emit assembly as of 1.15.0

### ISSUE THREAD

**Issue by beholdnec** [rust-lang/cargo#3761]
I use

`set RUSTFLAGS=--emit asm`

to get assembly output from my builds. As of Rust 1.15.0, this doesn't work anymore. Compiling a program manually with `rustc --emit asm blah.rs` prints assembly to a file called blah.s, but compiling a program with `cargo build` doesn't emit assembly anymore.

**Comment by alexcrichton** [comment]
Using `RUSTFLAGS` to do this wasn't really ever support per se, would `cargo rustc -- --emit asm` suffice here for you?

**Comment by beholdnec** [comment]
`cargo rustc -- --emit asm` doesn't output any assembly.

**Comment by alexcrichton** [comment]
Ah I think I see what's going on here. Cargo recently tweaked how it generated output artifacts to improve caching and I think that's adversely affecting this workflow. If you poke around in `target/debug/deps` you'll find the assembly files I think you're looking for, just with weird hashes in the name.

**Comment by beholdnec** [comment]
So that's where the assembly files went. Thank you.
