### ISSUE TITLE
Crates.io compatibility with old versions of cargo

### ISSUE THREAD

**Issue by hjr3** [rust-lang/cargo#3763]
A version of cargo was shipped in a version of Ubuntu LTS that is not compatible with some crate versions on crates.io. Examples of incompatible versions: `-alapha`, `-rc4`. The error persists even if the incompatible version is yanked.

Some major crates, such as serde, are now not compatible. As more crates start to use these new version types, it will continue to get worse.

To make matter worse, the error message a user receives from cargo is `the given version requirement is invalid`. I suspect most people do not realize that the issue is with their version of cargo and not with the specific crate.

Full discussion on urlo is here: https://users.rust-lang.org/t/crates-io-compatibility-with-old-cargo/9127

**Comment by alexcrichton** [comment]
Is there really anything we can do about this? Should we not fix bugs in Cargo?

**Comment by cuviper** [comment]
There is perhaps more that could be done to prevent such regressions in the future, assuming that crates.io does *intend* to be compatible with a wide range of Cargo versions, not just the latest.  To that end, I filed rust-lang/crates.io#580.

**Comment by aturon** [comment]
I'm going to close this in favor of https://github.com/rust-lang/crates.io/issues/580 for now.

I definitely think there's more to be done here regarding being more intentional about version compatibility, and testing that level of expected compatibility.
