### ISSUE TITLE
Ignore some warnings from rustc

### ISSUE THREAD

**Issue by NickeZ** [rust-lang/cargo#3765]
I would like to be able to ignore "dead_code" when I build with cargo with neomake inside neovim. I don't want to add exceptions to the sources because I want the warnings when I compile manually in the shell. I also don't think it is possible to set env vars in neomake so I can't use RUSTFLAGS. This is clearly a productivity issue since I'm distracted by irrelevant warnings when I'm in the exploration phase of a project.

**Comment by jbendig** [comment]
I'm not familiar with neomake but if you're only building one target, you can try using `cargo rustc` instead of `cargo build`. For example, if you're working on a lib: `cargo rustc --lib -- -A dead_code`.

**Comment by NickeZ** [comment]
I get `no library targets found` if I run that command. Btw, it would be great if the arguments work no matter which kind of project I build..

I obviously can't use rustc alone on the file because all the imports fail.

**Comment by NickeZ** [comment]
Either I need the possibility to inform rustc of all the dependencies so that it doesn't fail on imports. Or I need the possibility to tell cargo to use rustc with some specific flags, without resorting to environment variables...

**Comment by jbendig** [comment]
Are you building a binary instead of a library? If you have a src/main.rs and no [[bin]] sections in your Cargo.toml file, then try this instead: `cargo rustc --bin <project-name> -- -A dead_code` where <project_name> is the name of your project.

Passing arbitrary flags to rustc was discussed in #60 but was closed in favor of per-project profiles. Unfortunately, that won't do what you want even if an appropriate field was available. I think the above command will work for your use case though.

**Comment by NickeZ** [comment]
So you mean that I need to parse the toml file to figure out which flags to pass to cargo? I really want to be able to configure this once in my editor and still have it work with any rust file. If I didn't think that this is a usability problem I wouldn't have posted an issue about it.

**Comment by jbendig** [comment]
> So you mean that I need to parse the toml file to figure out which flags to pass to cargo?

For a general solution that doesn't use environment variables, yes, as far as I know. But, if you're working on a project with one binary, then it's not something you have to change as your project grows and you add more source files.

Where `cargo build` can build any number of targets (binaries, examples, etc.) in one command, `cargo rustc` needs to know the specific one. See `cargo rustc --help` for how to specify which target. If you have only one binary in your project, you can just run `cargo rustc -- -A dead_code` without specifying a target explicitly.

Maybe consider this as a temporary solution?

> I really want to be able to configure this once in my editor and still have it work with any rust file. If I didn't think that this is a usability problem I wouldn't have posted an issue about it.

Sure, seems reasonable. I've had problems when environment variables were not available with build systems for other programming languages. An alternative might be nice but I'm not familiar with the decisions that lead to not allowing passing flags to rustc directly. Maybe @alexcrichton can chime in?

**Comment by NickeZ** [comment]
As a temporary solution I will set `RUSTFLAGS` in my bashrc. It works with any source code, I just have to remember to unset it when I want to see dead_code and unused_imports and so on in the future again...

**Comment by NickeZ** [comment]
One issue with using RUSTFLAGS is that it recompiles all the modules if I set/unset RUSTFLAGS...

Is this an issue in rustc? should it recompile stuff if I change warnings that are emitted?

**Comment by alexcrichton** [comment]
@NickeZ that's intended behavior currentl, Cargo treats RUSTFLAGS opaquely and will recompile code when it changes (because that affects how code is compiled)

**Comment by NickeZ** [comment]
@alexcrichton So there is no way to filter the warnings from rustc without affecting how the code is compiled? This blew my plan that I was going to compile with fewer warnings in vim and all warnings in the terminal.

I'm sure the rust language server will be awesome when it is finished. But right now it would have been great if I could have filtered the warnings when neomake is compiling in the background so that I can focus on the real issues when I'm developing.

**Comment by alexcrichton** [comment]
AFAIK, yeah, there's no great way to do that right now short of writing your own rustc shim.

**Comment by NickeZ** [comment]
Hmm you mean that I should have my own rustc shell script that calls rustc with/withut `-A dead_code` depending on some other environment variable?

I guess that cargo will recompile everything if I switch between my shim and the real rustc?

**Comment by alexcrichton** [comment]
Yeah if you switch compilers Cargo will recompile, but you could have your own script read an env var and that'd subvert Cargo's caching mechanism.

**Comment by NickeZ** [comment]
Great, I'll try something like this:

```
!/bin/sh
if [ -z "${NEOMAKE_CARGO}" ] ; then
»···"$HOME/.cargo/bin/rustc" "${@}"
else
»···"$HOME/.cargo/bin/rustc" -A dead_code "${@}"
fi
```

**Comment by alexcrichton** [comment]
Yeah that'd do it!

**Comment by NickeZ** [comment]
@alexcrichton I can't get it to work. How do I check which rustc is used by cargo? How do I override that?

```
$ cat ~/.local/bin/rustc
#!/bin/sh
if [ -z "${NEOMAKE_CARGO}" ] ; then
        echo "rustc regular"
        "$HOME/.cargo/bin/rustc" "${@}"
else
        echo "rustc without dead_code"
        "$HOME/.cargo/bin/rustc" -A dead_code "${@}"
fi
$ which rustc
/home/niklas/.local/bin/rustc
$ rustc --help
rustc without dead_code
Usage: rustc [OPTIONS] INPUT
...
$ echo $NEOMAKE_CARGO
1
$ cargo build
   Compiling rups v0.1.0 (file:///home/niklas/git/procServ-ng)
warning: field is never used: `noinfo`
  --> src/telnet_server.rs:41:5
   |
41 |     noinfo: bool,
   |     ^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default
```

**Comment by NickeZ** [comment]
OK it's working I had to set `RUSTC=~/.local/bin/rustc`. But overall it is a pretty bad experience...
