### ISSUE TITLE
Build configure fails due to missing Cargo

### ISSUE THREAD

**Issue by itarato** [rust-lang/cargo#3772]
I've noticed the Cargo documentation seems to require Cargo already installed on the system. Even so that the build instructions have a no-cargo scenario, if I run `./configure` it fails with the following error:

```bash
configure: processing ./configure args
configure: 
configure: CFG_PREFIX           := /usr/local 
configure: CFG_LOCAL_RUST_ROOT  :=  
configure: CFG_CARGO            := cargo 
configure: CFG_RUSTC            := rustc 
configure: CFG_RUSTDOC          := rustdoc 
configure: CFG_CARGO            :=  
configure: error: needed, but unable to find any of: CFG_CARGO cargo
```

In my case I compiled Rust from source, which doesn't have Cargo included anymore. Also as far as I know it is a bad practice to have a pre-existing Rust install (such as via rustup) when compiling Rust and Cargo. In any case, I couldn't figure out from the makefile or the docs if I really need to install Cargo before I build the project.
For clarity - my intention is to build Cargo (and Rust) from source.
What do you recommend?

**Comment by alexcrichton** [comment]
Indeed yeah Cargo is required to compile Cargo. In future Rust releases we'll have `--enable-extended` which will compile Cargo as well as Rust.

In general though having an existing Rust install when compiling from source should work just fine, no need to avoid it.

**Comment by itarato** [comment]
Thanks @alexcrichton

**Comment by 0joshuaolson1** [comment]
> In future Rust releases we'll have --enable-extended

@alexcrichton is there an [issue](https://github.com/rust-lang/cargo/issues?utf8=%E2%9C%93&q=enable-extended) for this?

**Comment by alexcrichton** [comment]
@0joshuaolson1 it's currently present on the master branch of rust-lang/rust

**Comment by 0joshuaolson1** [comment]
That started with [this commit](https://github.com/rust-lang/rust/commit/44a01b8a54b078d15620d1133b94ee21ee7a6915), right? I see `--enable-extented` in [beta](https://github.com/rust-lang/rust/blob/beta/src/ci/docker/dist-x86_64-linux/Dockerfile#L91) and [stable](https://github.com/rust-lang/rust/blob/stable/src/ci/docker/cross/Dockerfile#L60) too.

Can I use the cargo build outside of Docker if my machine is the right arch?

**Comment by alexcrichton** [comment]
Sorry I'm not really sure what you're asking? How does this relate to this issue?

**Comment by 0joshuaolson1** [comment]
> --enable-extended which will compile Cargo as well as Rust.
I was interested in learning how to use this to compile Cargo without Cargo.

**Comment by alexcrichton** [comment]
Unfortunately that's not really supported right now, if you're looking to port Cargo to a new platform you'll need to do so through cross-compilation.

**Comment by 0joshuaolson1** [comment]
Thanks.
