### ISSUE TITLE
Cargo install fails on Windows with SSL connect error

### ISSUE THREAD

**Issue by f9rocket** [rust-lang/cargo#3774]
I am behind a corporate firewall that installs its own self-signed CA certificates. When I run cargo from the Windows command line I get the following error:

    > cargo install racer --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Downloading racer v2.0.6
    error: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.)

Cargo version:

    > cargo --version
    cargo 0.16.0-nightly (6e0c18c 2017-01-27)

I am using Rust stable 1.15.1, installed from the standalone i686-pc-windows-msvc installer (I could not use rustup since it fails with the same error).

I am trying to introduce Rust to our internal teams and this is a blocker. Any help is appreciated.

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this'll get solved with https://github.com/rust-lang/cargo/pull/3699

**Comment by f9rocket** [comment]
Thank you! These are great news, any ETA on when the fix will be released?

**Comment by alexcrichton** [comment]
Oh right thanks for the ping, I'll close this as well now that the PR is merged.

This'll ride the trains to stable in the Rust 1.17 release which is scheduled for release April 27, 2017

**Comment by f9rocket** [comment]
Awesome, thanks!
