### ISSUE TITLE
Cargo should tell subcommands the path to itself

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/cargo#3778]
Many subcommands listed [in the wiki](../wiki/Third-party-cargo-subcommands) need to run other existing cargo commands one way or another. Most of them seem to just call `cargo` (that is, the one in `PATH`) and hope it's the right one.

Cargo should pass the path to itself to subcommands so that they can be sure they're running the right `cargo`. IMHO the best way would be an environment variable, something like `CARGO_BIN`.

(In case you feel this is ok, I'm willing to write the patch.)

**Comment by matklad** [comment]
Related issue: https://github.com/rust-lang/cargo/issues/3744

**Comment by alexcrichton** [comment]
Yeah sounds like we shoudl just blanket set a `CARGO` env var or something like that for subprocesses to learn the path to the original Cargo

**Comment by matklad** [comment]
Fixed by https://github.com/rust-lang/cargo/pull/3789
