### ISSUE TITLE
rustflags expects a table, but docs say otherwise.

### ISSUE THREAD

**Issue by vext01** [rust-lang/cargo#3780]
Hi,

I'm using rust/cargo nightly a few days old on OpenBSD. The [cargo docs](https://github.com/rust-lang/cargo/blob/master/src/doc/config.md) shows rustflags should bre passed of the form:

```
rustflags = ["..", ".."]
```

So I should be able to do stuff like this in my toml:

```
[target]
rustflags = ["-L/usr/local/lib"]
```

But this gives:

```
  expected a value of type `table`, but found a value of type `array` for the key `target.rustflags`
```

Is that a bug in the docs? If not, I don't find the docs clear.

Thanks

**Comment by vext01** [comment]
Similarly the docs say the following about the linker:
```
[target]
# For Cargo builds which do not mention --target, this is the linker
# which is passed to rustc (via `-C linker=`). By default this flag is not
# passed to the compiler.
linker = ".."
```

Yet if I have:
```
[target]
linker = "eg++"
```

This is a parse error:

```
error: failed to parse manifest at `/home/edd/research/blocker/Cargo.toml`

Caused by:
  expected a value of type `table`, but found a value of type `string` for the key `target.linker`
```

**Comment by vext01** [comment]
Ah, the problem here is that I am supposed to be putting these variables into `~/.cargo/config` not `Cargo.toml`. They work as expected there.

But are these keys even valid in a `Cargo.toml`? If not then the error messages are misleading.

**Comment by alexcrichton** [comment]
Oh right yes these are only valid in `.cargo/config`, not `Cargo.toml`, where the `target` table has different meanings. Does that clear things up for you?

**Comment by carols10cents** [comment]
I'm not sure how to improve the docs to distinguish better between `~/.cargo/config` and `Cargo.toml`, so I'm going to close this. If you have any suggestions, please reopen!

**Comment by pwil3058** [comment]
Any suggestions? Write separate documentation for ~/.cargo/config and Cargo.html would be a good way to distinguish between them.
