### ISSUE TITLE
On Windows, projects living at the root of a drive don't work

### ISSUE THREAD

**Issue by wagenet** [rust-lang/cargo#3783]
I had a project that was directly mounted to E:. When I tried to run `cargo` I got the following unclear error: "error: invalid path url `E:`". I was able to resolve this problem by moving my project into a directory.

**Comment by alexcrichton** [comment]
Hm I seem to be unable to reproduce this locally in a `C:` drive, do you have a set of instructions of how to reproduce? I'd be surprised if it was *specific* to `E:` as opposed to `C:`...

**Comment by wagenet** [comment]
@alexcrichton I had a shared directory mounted to E: with a cargo project in that directory. Any cargo command that tried to do something with my code (i.e. not `cargo -V`, but `cargo test`) caused this error. Our project is also set up as a workspace with members inside of it.

**Comment by alexcrichton** [comment]
Oh this may be related to the shared drive then maybe? We've had reports of `fs::canonicalize` returning errors in these situations in the past.

Could you gist the full error you saw as well as a description of the structure of the project (e.g. workspace layout)

**Comment by wagenet** [comment]
There was no error message except what I posted. The project was a clone of https://github.com/tildeio/helix.

**Comment by carols10cents** [comment]
This is the similar-sounding issue that has to do with `fs::canonicalize`: https://github.com/rust-lang/cargo/issues/2990

Given that this issue is stale, I'm going to close this.

@wagenet if this is still an issue, could you try running `RUST_LOG=debug cargo build` in the project on shared drive and reopen with a gist of the output? Thanks!

**Comment by wagenet** [comment]
@carols10cents I'm still seeing issues with `rust 1.22.0-nightly (d6d711dd8 2017-10-10)`. I'm not seeing any additional output beyond the single line error message. I'm investigating more right now.

**Comment by wagenet** [comment]
Whoops, I forgot to add the `RUST_LOG=debug`. Here's the output I get:

```
$ RUST_LOG=debug cargo build
DEBUG:cargo::build: executing; cmd=cargo-build; args=["C:\\Users\\Peter\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\bin\\cargo.exe", "build"]
DEBUG:cargo::core::workspace: find_root - is root Z:\Cargo.toml
DEBUG:cargo::core::workspace: find_members - Z:\examples\calculator\Cargo.toml
INFO:cargo::util::job::imp: found 0 remaining processes
DEBUG:cargo: exit_with_error; err=CliError { error: Some(CargoError(Msg("invalid path url `Z:`"), State { next_error: None, backtrace: None })), unknown: false, exit_code: 101 }
error: invalid path url `Z:`
```

**Comment by carols10cents** [comment]
Interesting, thank you! Reopening!
