### ISSUE TITLE
cargo prints "Compiling <name-of-crate>" while compiling example

### ISSUE THREAD

**Issue by durka** [rust-lang/cargo#3784]
This is a minor issue, but it seems like it'd better to print the example name (possibly in addition to the crate name).

**Comment by aturon** [comment]
@durka Agreed! Is this something you'd be interested in taking on, with some guidance?

**Comment by durka** [comment]
Sure, why not.

**Comment by eminence** [comment]
Trigate:  cargo will now give you hints that it's compiling your examples.  Specifically, it'll show you `example_name(example)` in the status line from `cargo build`.  For example (hah, pun very much intended):

    Building [=======================> ] 130/134: interface_stats(example), netstat(example), pressure(example), process_hierarchy(example)

**Comment by ehuss** [comment]
Yea, closing as I think this is effectively resolved by #5828.
