### ISSUE TITLE
Cargo config should allow an option for search paths for local crates

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/cargo#3788]
To disambiguate, I'm not talking of the currently available variable `paths` that allows one to mention overrides for crates. 

I'm proposing that there be a new variable, say, `search_paths` which are the paths relative to which `crate_name ={ path = ".." }` directives search for the crate. So for example I have a directive:

`my_fancy_crate = {path = "my_fancy_crate"}` 

and my cargo config is

`search_paths = [ "/home/mememe", "/home/mememe/rust/libs" ]`

then the lookup will be done at two places: 

`/home/mememe/myfancy_crate` and `home/mememe/rust/libs/my_fancy_crate`. 

This is not an issue with git because there the `Cargo.toml` file is looked up in the entire hierarchy. 

Alternate solution I think is to do for local paths what's done for git- search throughout for `Cargo.toml`.

EDIT (3rd March, 4:54pm UTC): I should note that using local git-repos will not work unless change is committed to the repository.

**Comment by alexcrichton** [comment]
Could you elaborate on the rationale for such a feature as well? In general we try to avoid configuration where building a project involves cloning followed by configuration of Cargo itself, but I'm curious to hear how you ran into this!

**Comment by SRGOM** [comment]
Thanks for reading the proposal. I have a local crate repository that I keep making changes to live (before version controlling them). I would like that I should be able to refer to my crates from my projects, projects which are in arbitrary locations wrt the crates. I could always give the complete absolute path but:

1) That's a bit tedious
2) On another machine when I may check out the crates in a different location and projects in a new relative location.

I hope I've made the scenario clear, please let me know if I haven't. This is not an artificial scenario and as I learnt on irc.mozilla.org#rust yesterday, I'm not the only one facing this exact "issue".

**Comment by SRGOM** [comment]
@alexcrichton Didn't cc you...

**Comment by alexcrichton** [comment]
Thanks for the explanation! I wonder, would [this scheme for prepublish](https://github.com/rust-lang/cargo/issues/2649#issuecomment-279615299) fit your use case? (I think it sounds like it does)

**Comment by SRGOM** [comment]
@alexcrichton If I've understood the scheme correctly, it still requires me to do local git commits. I'm looking to not do any commits. I want to keep updating my dependency live and see how it affects my app until I settle on a version that I can commit. 

I am basically using this to use my own libraries without going through the commit/publish cycle.

**Comment by alexcrichton** [comment]
@SRGOM oh well it doesn't have even an RFC yet so it's up in the air, but the idea is that it supports the concept of "assume these crates are from the registry, even though they're not. That way you'd say in your local configuration "append these crates to the crates.io registry" and then you'd write you Cargo.toml as-if you had published those crates, even if you hadn't.

**Comment by SRGOM** [comment]
@alexcrichton  But you'll still have commited them, no? I'd prefer if that were not hte case. 

 I have a work-around that works fine for me but I just feel like it's a good thing to have.

Don't worry too much about it- but if you  like it- put it somewhere on the list so you guys can discuss.

**Comment by alexcrichton** [comment]
Ok well in that case I think I'm going to close in favor of https://github.com/rust-lang/cargo/issues/2649#issuecomment-279615299 which is itself still in flux so we have yet to see how the dust settles on that issues anyway. Thanks for the report though!
