### ISSUE TITLE
Error message "malformed cfg value or key/value pair" could be improved.

### ISSUE THREAD

**Issue by vext01** [rust-lang/cargo#3792]
I've just encountered this:

```
$ RUSTC=../../target/debug/blocker cargo build          
error: malformed cfg value or key/value pair
```

I assume this is a cargo error, assuming it is:
 * Which file?
 * Which key?

The cause is something to do with the custom rustc (I'm playing with compiler plugins), but the error message gives no clue as to what has really gone wrong. It works fine if I omit the `RUSTC=...` part.

Thanks

**Comment by vext01** [comment]
I don't think this is a cargo error actually. It seems to be cause by the following:

```
impl<'a> CompilerCalls<'a> for Blocker {
    ...
    fn build_controller(&mut self, _: &Session,  _: &getopts::Matches) -> driver::CompileController<'a> {
        let mut control = driver::CompileController::basic();
        control.after_analysis.stop = Compilation::Continue;
        control.after_analysis.callback = box |state: &mut driver::CompileState| {
            match &state.tcx {
                &Some(ref gcx) => print_type_of(&gcx.maps.mir),
                _ => panic!("no gcx"),
            }
        };
        control
    }
}
...
fn print_type_of<T>(_: &T) {
	println!("{}", unsafe { std::intrinsics::type_name::<T>() });
}
```

If I comment out the call to `print_type` the error is gone, so I guess this is actually an error from that(?). I don't understand the error message :(

**Comment by alexcrichton** [comment]
Oh I think this was actually in a historical version of Cargo, but if you update Cargo in use it'll print out what the malformed cfg actually is.

FWIW the error comes from here: https://github.com/rust-lang/cargo/blob/a226b3ca04037e52bfcdc9d21bfeeefb18dab5d5/src/cargo/util/cfg.rs#L47

**Comment by vext01** [comment]
Oh, I was under the impression I was using yesterday's nightly cargo.

```
$ which cargo
/home/build-rust/build-rust/install_dir/nightly/bin/cargo
$ cargo -V   
cargo 0.16.0 (built 2017-03-02)
```

So the build script I used has installed the wrong cargo! Sorry, for the noise.

**Comment by vext01** [comment]
For example on a newer cargo (different program):
```
error: malformed cfg value or key/value pair: `visit an item: Item { name: (0), attrs: [Attribute { id: AttrId(1), style: Outer, value: MetaItem { name: prelude_import(83), node: Word, span: <anon>:0:1: 0:1 }, is_sugared_doc: false, span: <anon>:0:1: 0:1 }], id: NodeId(2), node: ItemUse(path(std::prelude::v1), Glob), vis: Inherited, span: <anon>:0:1: 0:1 }`
```

:)

**Comment by alexcrichton** [comment]
wut

**Comment by vext01** [comment]
Sorry, let me explain.

The error message you see above shows that on the master branch (as of 3 days ago), cargo does indeed print the reason why there is a `malformed cfg value or key/value pair` (ignore the actual reason, that's irrelevant for this PR).

BTW, the build script was using (which had the "historical version of cargo") uses the cargo version found in `src/stage0.txt`, which is `bfee18f73287687c543bda8c35e4e33808792715` from `2016-12-29`. As I understand that is the same version of cargo rustup nightly would install too?

(The reason I am having to use a build script is because there are no nightly binaries for OpenBSD)

Thanks

**Comment by alexcrichton** [comment]
Heh, well glad it's at least making more progress now!
