### ISSUE TITLE
Cargo doesn't allow cyclic features

### ISSUE THREAD

**Issue by retep998** [rust-lang/cargo#3796]
If a crate has two features `foo` and `bar` which depend on each other, Cargo will error.

```toml
[features]
foo = ["bar"]
bar = ["foo"]
```
```
error: Cyclic feature dependency: feature `foo` depends on itself
```
However, I ended up needing this in `winapi`. In order to allow people to compile only the bits they need to save time, `winapi` has a feature for each header. However since headers depend on each other, the features in turn had to depend on each other to ensure that `winapi` would compile correctly. Unfortunately sometimes those headers would have cyclic dependencies on each other, causing Cargo to complain. There were several workarounds I tried such as having a feature that is common to a set of headers which depend on each other, but I eventually settled on doing feature dependency resolution myself via a build script. https://github.com/retep998/winapi-rs/blob/dev/build.rs#L175-L191

**Comment by aturon** [comment]
@alexcrichton I presume the cycle dependency is largely just a debugging aid, right?

It seems probably not too hard to determine whether the cycle went through any intermediate nodes on the way.

@alexcrichton, if you agree, would you be open to taking a PR from @retep998 to this effect?

**Comment by alexcrichton** [comment]
Yes IIRC non-cyclic features was just matching non-cyclic dependencies. Cyclic dependencies fundamentally can't be compiled, but cyclic feature dependencies should always be compileable (e.g. just pass a bunch of `--cfg` flags)

In that sense should be good for a PR!

**Comment by antonlarin** [comment]
Can I take this on if @retep998 doesn't mind?

**Comment by retep998** [comment]
@antonlarin Feel free.
