### ISSUE TITLE
Capture stderr of tests

### ISSUE THREAD

**Issue by SilverWingedSeraph** [rust-lang/cargo#3798]
I'm currently having a problem with testing libraries that use `log` with either `env_logger` or `flexi_logger` in their tests. In the "real world", they should log to `stderr`, but Cargo doesn't capture `stderr` from tests, so I have to jump through hoops to get these libraries to log to `stdout` instead. 

Would it be possible to add an option to `cargo test` that allows it to capture `stderr` from tests?

**Comment by alexcrichton** [comment]
Thanks for the report! This is more of a rust-lang/rust issue (where libtest lives) rather than a Cargo issue though, could you file an issue on that repository?

**Comment by SilverWingedSeraph** [comment]
OK, will do.
