### ISSUE TITLE
Referencing sub directory of a multi-crate git repo

### ISSUE THREAD

**Issue by sunng87** [rust-lang/cargo#3804]
Currently I think it's impossible to reference a module of multi-crate git repository. For example, the `pest` repo ( https://github.com/pest-parser/pest/tree/procedural ) is a multi-crate one with `pest` and `pest-derive`. I cannot specify it like:

```
pest = { git = "...", branch = "procedural", path = "pest" } 
```

By checking the code I saw there is no path of git dependency.

**Comment by alexcrichton** [comment]
You should be able to just leave out `path` and reference the git repo, does that work for you?

**Comment by sunng87** [comment]
I'm sorry this is an invalid issue. I can reference to the pest module by removing `path`.
