### ISSUE TITLE
Open documentation for a given crate

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#3805]
I often want to see documentation for a dependency (including build dependencies), but it's cumbersome to open it — I have to go to crates.io, find the dependency, and then follow its Documentation link.

Cargo already knows this link from metadata, so it could open the documentation for me.

I'd expect it to work like this:

```sh
cargo doc crate-name
```

Such functionality is in npm `npm docs package-name`.

**Comment by steveklabnik** [comment]
> I have to go to crates.io, find the dependency, and then follow its Documentation link.

Doesn't `cargo doc` already document dependencies? so it should be `cargo doc --open`, click the link on the left hand sidebar.

**Comment by pornel** [comment]
1. It doesn't do that for build dependencies. 
2. And it's just an unordered function reference. I prefer to see a webpage with a tutorial (sadly, few crates have that).

**Comment by steveklabnik** [comment]
> It doesn't do that for build dependencies.

Ah, this sounds like a bug, then, and probably what this ticket should focus on.

> I'm hoping for documentation link to provide more than that (i.e. a tutorial, prose, examples)

This is covered by https://github.com/rust-lang/cargo/issues/739

**Comment by pornel** [comment]
I assume it's intentional, since build and dev dependencies are not part of crate's interface. 

I would not like build/dev dependencies included in `cargo doc` output if I were to publish it on a website for others, since the extra dependencies would be a distraction. I only need to consume, not publish their docs.

**Comment by alexcrichton** [comment]
Yes it's intentional that build-dependencies don't show up in Cargo by default, but I think this works?

```rust
cargo doc -p gcc --open
```

Does that work for your use case?

**Comment by pornel** [comment]
Thanks! That works. I did not see that in the help file, because I don't know what `SPEC` is. I looked for "crate".

**Comment by prasannavl** [comment]
Does the source code work with this method though? The last I checked, it doesn't. Clicking `src` just leads me an empty page. Perhaps, that has to be created as a separate issue?
