### ISSUE TITLE
PROFILE={release,debug} is not exposed for integration tests

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang/cargo#3806]
I have this use case:
- I would like to use the crate `compiletest_rs` which needs to know the build paths for linking artifacts, e.g. `-L target/debug/deps`.
- I would prefer _not_ to hardcode `'target/debug`, because this would fail for `cargo test --release`.

I've searched a little and there seems to be an `env::var("PROFILE")`, but [only for build scripts](http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

PS: all examples I can find on github have this hardcoded, e.g. https://github.com/PistonDevelopers/hematite_nbt/blob/b4abe9277fd16c63c0fe8d56c9c2500b4db59ff5/macros/tests/compiletest.rs#L14

**Comment by matklad** [comment]
Perhaps you can find the location of libraries by looking at the path to the test executable?

Here's an example: https://github.com/rust-lang/cargo/blob/4a3c0a63b07e9a4feb41cb11de37c92a09db5a60/tests/cargotest/support/mod.rs#L308-L313

Cargo uses this trick to find `cargo` binary in `target/release` or `target/debug` during testing.

**Comment by carols10cents** [comment]
Because there's a workaround and because this issue is stale, I'm going to close this. Please reopen if the workaround isn't sufficient! Thanks!
