### ISSUE TITLE
Automatic Fix Linting for some cases

### ISSUE THREAD

**Issue by PSeitz** [rust-lang/cargo#3813]
Hi,

would be nice if there was some auto fix for some minor linting issues, like 
`variable  ...  should have a snake case name `

Although I'm not sure if cargo (or rustc?) is the right place for something like this

**Comment by alexcrichton** [comment]
You may be interested in [`rustfix`](https://github.com/killercup/rustfix) perhaps?

**Comment by aturon** [comment]
This is definitely something we'd like to pursue in general, but it's not really within Cargo's wheelhouse. It might go through rustc, or through the rls, or an external tool.

If you're interested in working on such a tool, I'd recommend talking to folks in the #rust-internals IRC channel.

I'm going to close this in the meantime.
