### ISSUE TITLE
Unable to find appropriate src/main.rs if it's in src/bin/main.rs

### ISSUE THREAD

**Issue by ehiggs** [rust-lang/cargo#3814]
According to https://github.com/rust-lang/rust/issues/40185, the following test case should pass:

```rust
#[test]
fn run_proper_binary_main_rs() {
    let p = project("foo")
        .file("Cargo.toml", r#"
            [package]
            name = "foo"
            authors = []
            version = "0.0.0"
            [[bin]]
            name = "foo"
        "#)
        .file("src/lib.rs", "")
        .file("src/bin/main.rs", r#"
            fn main() {
            }
        "#);

    assert_that(p.cargo_process("run").arg("--bin").arg("foo"),
                execs().with_status(0));
}
```

The problem appears to be that cargo should look for `src/bin/main.rs` as well as `src/main.rs` for defaults when named binaries are not found in `src/bin/<name>.rs`. This was introduced in e3edc064761b75a0d9a8dfcd4ce46e9294e43f06.

**Comment by ehiggs** [comment]
@jmatraszek, do you have bandwidth to take a look at this? Thanks

**Comment by jmatraszek** [comment]
@ehiggs Yes, investigating.

**Comment by jmatraszek** [comment]
Proposed fix in #3818.

**Comment by alexcrichton** [comment]
Thanks for the quick fix @jmatraszek!

**Comment by pooyapeyravi** [comment]
is done ?
