### ISSUE TITLE
error: specified package has no binaries - dir not initialized

### ISSUE THREAD

**Issue by happylynx** [rust-lang/cargo#3821]
```
$ ~/.cargo/bin/cargo install time
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: specified package has no binaries
```

If `cargo install` is run in directory without `Cargo.toml`, it fails with quite counter-intuitive message. I'd prefer rather something like *Cargo.toml not found in current directory.*

**Comment by happylynx** [comment]
```
$ ~/.cargo/bin/cargo --version
cargo 0.16.0-nightly (6e0c18c 2017-01-27)
```

**Comment by alexcrichton** [comment]
@happylynx I'm not quite sure I understand? The error message is indicating that the `time` package from crates.io has no binaries, but are you saying that you ran this command from a directory with `Cargo.toml` that had a `time` binary and you expected this to install that?

**Comment by carols10cents** [comment]
I'm going to close this-- `cargo install` is only meant for installing binary packages, and `time` is not a binary package. For a command that will add a package to your `Cargo.toml` for you, please see https://crates.io/crates/cargo-edit. Thanks!
