### ISSUE TITLE
cargo verbose = warning as error mode

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/cargo#3823]
I saw many times when `cargo build -v -v` failed, while `cargo build` work without problems.

For example if you use `iron` that depend on `typemap`, with `cargo build -v -v` you will see:

    error: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions., #[deny(invalid_type_param_default)] on by default
       --> /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/typemap-0.3.3/src/lib.rs:185:18
        |
    185 | impl<'a, K: Key, A: ?Sized + UnsafeAnyExt + 'a = UnsafeAny> Entry<'a, K, A> {
        |                  ^

And `cargo build` failed.

Or for example if you use `syntex` library, with `cargo build -v -v` you will see:

    error: unused `#[macro_use]` import
      --> /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_errors-0.54.0/src/lib.rs:22:1
       |
    22 | #[macro_use]
       | ^^^^^^^^^^^^

    error: aborting due to 2 previous errors

So is `cargo build -v -v` not only make output more verbose, but turn on something like "error on warning mode? Can it be at least documented.

**Comment by alexcrichton** [comment]
Hm it's definitely not the intention of `-v -v` to turn warnings to errors, so this is quite surprising! Do you have a reproductio available that I could test out?

**Comment by Dushistov** [comment]
@alexcrichton 
>Do you have a reproductio available that I could test out?

`cargo new cargo_verbose` add

```
[dependencies]
iron = "0.4.0"
```
to Cargo.toml and `extern crate iron;` to `src/lib.rs`

```
$ cargo build -v -v
...
error: build failed

$ cargo --version
cargo-0.17.0-nightly (0bb8047 2017-02-06)
$ rustc --version
rustc 1.16.0-beta.3 (ecbf0b59e 2017-03-02)
```

**Comment by ereichert** [comment]
My team has also hit this error this past week.

**Comment by alexcrichton** [comment]
Thanks for the snippet @Dushistov! Looks like `-vv` isn't properly passing `--cap-lints warn`, I'll look into fixing this.

**Comment by ignatenkobrain** [comment]
Looks like this is not fixed...

```rust
+ /usr/bin/cargo build --release -j8
   Compiling bytes v0.3.0 (file:///home/brain/rpmbuild/BUILD/bytes-0.3.0)
     Running `/usr/bin/rustc --crate-name bytes src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=2d4d196649939b42 -C extra-filename=-2d4d196649939b42 --out-dir /home/brain/rpmbuild/BUILD/bytes-0.3.0/target/release/deps -L dependency=/home/brain/rpmbuild/BUILD/bytes-0.3.0/target/release/deps -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now`
error: unused import: `ByteStr`
 --> src/buf/byte.rs:2:38
  |
2 | use traits::{Buf, MutBuf, MutBufExt, ByteStr};
  |                                      ^^^^^^^
  |
  = note: #[deny(unused_imports)] implied by #[deny(warnings)]
note: lint level defined here
 --> src/lib.rs:2:9
  |
2 | #![deny(warnings)]
  |         ^^^^^^^^

error: unused import: `Any`
 --> src/str/bytes.rs:4:16
  |
4 | use std::any::{Any, TypeId};
  |                ^^^
  |
  = note: #[deny(unused_imports)] implied by #[deny(warnings)]

error: unused import: `MutBuf`
 --> src/str/small.rs:2:19
  |
2 | use traits::{Buf, MutBuf, ByteStr, ToBytes};
  |                   ^^^^^^
  |
  = note: #[deny(unused_imports)] implied by #[deny(warnings)]

error: aborting due to 3 previous errors
```

```
[brain@ignatenko-w541 bytes]$ cargo --version 
cargo 0.19.0
[brain@ignatenko-w541 bytes]$ rustc --version
rustc 1.18.0
```

**Comment by ignatenkobrain** [comment]
P.S. I have set

```toml
[term]
verbose=True
```

in `.cargo/config`
