### ISSUE TITLE
Remove `--cap-lint` feature detection.

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3828]
We use feature detection to check if compiler supports `--cap-lints` flag. This flag was added way back in 1.4, so it makes sense to jettison detection code and just assume that `--cap-lints` is available. 

It is neccessary to remove this field: https://github.com/rust-lang/cargo/blob/4a3c0a63b07e9a4feb41cb11de37c92a09db5a60/src/cargo/util/rustc.rs#L10 and fix all its usages and related tests.

**Comment by vbmade2000** [comment]
@matklad I think this issue can be closed.

**Comment by matklad** [comment]
Indeed!
