### ISSUE TITLE
Support for 'cargo init --force' that overwrites existing files

### ISSUE THREAD

**Issue by sbuller** [rust-lang/cargo#3832]
**Every** time I run `cargo init` I forget the --bin option. I'd prefer an alternative to `rm -rf *; cargo init --bin`. Alternatively, a n00b mode might be helpful. I'd appreciate it if a bare `cargo init` stopped to ask me if I'd forgotten the --bin like a n00b again.

**Comment by epage** [comment]
`--bin` is now the default but the point still stands ;)

The differences between bins and libs shrunk a little in that we make the `Cargo.lock` the same.

Deciding what to overwrite with a `--force` seems dubious.  I think I'd prefer to explore `cargo init` being additive.

**Comment by epage** [comment]
@weihanglo are you then leaning towards "close"?  If so, I think thats fine as well.

**Comment by weihanglo** [comment]
Yes. I am going propose to close this to the cargo team. This looks a feature likely to be an extension of cargo-template.

**Comment by epage** [comment]
I second.
