### ISSUE TITLE
Compiler warning on 1.16 with CARGO_INCREMENTAL

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/cargo#3835]
Steps:
- create a new project
- `CARGO_INCREMENTAL=1 cargo build` with rust 1.16
```
warning: the option `Z` is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details
```
Seems to be because of `-Zincremental=<path>`.

**Comment by alexcrichton** [comment]
CARGO_INCREMENTAL is currently a nightly-only feature, so this is expected.

**Comment by Yamakaky** [comment]
Oops, sorry

**Comment by alexcrichton** [comment]
cc @nikomatsakis @michaelwoerister

**Comment by michaelwoerister** [comment]
Does Cargo know if it's using a nightly version of Rust?

**Comment by alexcrichton** [comment]
Currently, no. It knows the version of rustc (as a string) but it doesn't attempt to parse the string

**Comment by jonhoo** [comment]
Yeah, this is quite disturbing when you have some projects using nightly, and some that are stable/beta. I have `CARGO_INCREMENTAL=1` in my `.bashrc`, and now see a large number of these warnings appear whenever I try to build one of my stable crates. Presumable they'll just refuse to build entirely now that `-Z` is dropped completely? Shouldn't `cargo` simply not pass `-Zincremental` if it's not supported?

**Comment by alexcrichton** [comment]
@jonhoo the intention here was that `CARGO_INCREMENTAL=1` was experimental, e.g. a one-off basis rather than a global config. Cargo doesn't have a huge amount of knowledge of stable/beta/nightly right now. It seems reasonable to me though to patch cargo if possible!

**Comment by jonhoo** [comment]
Hmm, I don't know of anyone who explicitly types out `CARGO_INCREMENTAL=1 cargo +nightly ...`. The people I've seen use it all have it set in their environment, but only expect it to apply to nightly builds. I have very limited knowledge of the cargo codebase, so don't quite know where I'd start to make changes to have it know about nightly flags..

**Comment by alexcrichton** [comment]
I do! I don't like it though...

In any case, for anyone curious to change this (and that could be you @jonhoo!) some helpful pointers might be:

* Where we read [`CARGO_INCREMENTAL`](https://github.com/rust-lang/cargo/blob/de52ccd5356b0ac50286fc42328b40e78cf9c6e9/src/cargo/ops/cargo_rustc/context.rs#L78-L84)
* [`Config::rustc`](https://github.com/rust-lang/cargo/blob/de52ccd5356b0ac50286fc42328b40e78cf9c6e9/src/cargo/util/config.rs#L95-L98) is used to learn about the current compiler.
* The `Rustc` structs [knows about the underlying version](https://github.com/rust-lang/cargo/blob/de52ccd5356b0ac50286fc42328b40e78cf9c6e9/src/cargo/util/rustc.rs#L8) which typically will have "nightly" in the version string if it's a nightly compiler.

**Comment by jonhoo** [comment]
@alexcrichton sure, I'll take a look. Do you think it'd be better to only *allow* `-Z` on rustc versions that match `nightly`, or to instead *ignore* on things that match `stable`/`beta`?

**Comment by jonhoo** [comment]
PR filed in #4000.
