### ISSUE TITLE
Target serialization in JSON looks ugly

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3840]
Currently, `SerializedTarget` has both `kind` and `crate_types` and looks like

```JSON
{
  "crate_types": ["test"],
  "kind": ["test"],
  "name": "foo",
  "src_path": "/home/user/trash/vvv/tests/foo.rs"
}
```

I think this particular format is problematic, and I wonder if we could do better. 

Here are specific issues:

* `crate_types` and `kind` almost always duplicate each other, which leaves you wondering which one of the two do you need to look at. 

* `kind` conflates two pieces of data in one field: 1) what flag (`--bin`, `--example`, `--lib`, `--test`) should be used on the command line to refer to the target, 2) what sort of artifact(s) is produced for the target.

* `kind` is mostly an enum, but is serialized into array of strings, which is odd. 

* In the code, both fields just present the same internal data in two different ways, which is a smell 

So, the problem was with the `kind` field form the start, and `crate_types` is actually much better!

We have cargo metadata versioning in place, so let's just add `version 2`, and use a simple string for `kind`?

cc #3654 

@KalitaAlexey @ehuss @alexcrichton what do you think about it? 

@KalitaAlexey @ehuss make sure that you explicitly pass `--format-version` when invoking `cargo metadata` anyway :)

**Comment by alexcrichton** [comment]
`kind` is basically there for backwards compatibility for now, I'd prefer to avoid going to version 2 for now (as that's a pretty weighty change)

**Comment by matklad** [comment]
>kind is basically there for backwards compatibility for now, I'd prefer to avoid going to version 2 for now (as that's a pretty weighty change)

Hm, you need kind to decide which argument do you need, `--example` or `--lib`. Just `crate_types` will be insufficient in this case I think?

I'm OK with the current format, it works for all use cases so far, it's just not as good as it could be :)

**Comment by alexcrichton** [comment]
Oh yeah I'd definitely agree that it's not as good as it could be! I wouldn't mind adding more docs/fields and indicate "don't look at this field" or "look at this field" or something like that.

**Comment by matklad** [comment]
I am trying to write some docs for this now, and I don't seem able to write what `crate_type` field stands for. 

It is definitely not a `crate_type` from [the reference](https://doc.rust-lang.org/reference.html#linkage): there is no `example` or `custom_build` crate type. Also, the fact that for `ExampleBin` `crate_types` field is `example` and not `bin` seems just wrong to me.

What do you thing about changing `crate_types`  to precisely correspond to `crate_type` attribute?

**Comment by alexcrichton** [comment]
Guh. It it suspposed to be precisely what the `crate_type` attribute is, it appears I didn't review closely enough... I think we may be able to change though as it's a pretty recent feature.

**Comment by matklad** [comment]
>Guh. It it suspposed to be precisely what the crate_type attribute is, it appears I didn't review closely enough... I think we may be able to change though as it's a pretty recent feature.

Will try to fix that tomorrow!

**Comment by alexcrichton** [comment]
Thanks!
