### ISSUE TITLE
`cargo version` unwraps `None`

### ISSUE THREAD

**Issue by jkcclemens** [rust-lang/cargo#3844]
`RUST_BACKTRACE=full cargo version` results in [this](https://gist.github.com/jkcclemens/edafe6e9a22d85ae662108bc5dc7ea35). That backtrace is from macOS 10.12.4 beta.

I have verified this issue exists on both macOS and Arch. [Arch backtrace](https://gist.github.com/jkcclemens/f9ba90448d9902054fb73b974591d796).

**Comment by TyOverby** [comment]
currently failing on travis 

https://travis-ci.org/TyOverby/bincode/jobs/212339208

**Comment by jkcclemens** [comment]
I found https://github.com/rust-lang/cargo/issues/3819, but it looks like that was supposed to be fixed, and this issue still persists in `rustc 1.17.0-nightly (a559452b0 2017-03-17)`.

**Comment by SilverWingedSeraph** [comment]
Also happens for me https://api.travis-ci.org/jobs/212348423/

**Comment by SergioBenitez** [comment]
😢

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/40625

sorry for the breakage!

**Comment by wagenet** [comment]
Is there a temporary workaround for this? It's kill all of our CI tests.

**Comment by abonander** [comment]
I've disabled the `nightly` branch in my Travis config for the time being, otherwise I don't know.

**Comment by diggyk** [comment]
I need nightly to do my build.  How long does a fix like this make it into nightly?

**Comment by abonander** [comment]
It's been approved as high-priority so it should merge tonight, but then there's rollup merging and testing and that takes a day or two to go through (unless high-priority PRs skip rollups), so maybe Monday's nightly?

**Comment by Arnavion** [comment]
Usually one configures travis to ignore failures on nightly. If your code only builds with nightly, then you might want to consider pinning it to a known good version. It's nightly after all; it can break.

**Comment by TomasTomecek** [comment]
@Arnavion 
> If your code only builds with nightly, then you might want to consider pinning it to a known good version. 

Is there a guide how to do that?

**Comment by Arnavion** [comment]
The version of rust you specify in .travis.yml is just passed to rustup, so anything rustup accepts will work. Eg `nightly-2017-03-16` will install the nightly released on 2017-03-16.

**Comment by gaurikholkar** [comment]
Build fails
https://travis-ci.org/nikomatsakis/rayon/jobs/212389174

**Comment by wagenet** [comment]
Ah whoops, I was pinning my Rust version but wasn't going far enough back in time. Strange that it didn't start happening until yesterday. I wonder if it is somehow a twofold failure. Anyway it seems like the team has it under control :)

**Comment by lilianmoraru** [comment]
Similar issue with Windows a few days ago... :)

**Comment by TomasTomecek** [comment]
@Arnavion thank you: I wasn't using rustup, instead I used to download tarballs manually. Switching to rustup now then. For anyone interested, here's an url of nightly, based on @Arnavion suggestion, which works:

```
https://static.rust-lang.org/dist/2017-03-16/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
```

Full command in my Dockerfile:

```
ARG RUST_CHANNEL="nightly-2017-03-16"
RUN curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --spec=$RUST_CHANNEL --verbose --disable-sudo
```
