### ISSUE TITLE
Cargo can find cargo-clippy when searching, but not when installing

### ISSUE THREAD

**Issue by nertpinx** [rust-lang/cargo#3850]
Output of the commands follows:
```
$ cargo search cargo-clippy 
    Updating registry `https://github.com/rust-lang/crates.io-index`
cargo-clippy (0.2.2)    A subcommand for cargo to perform linting on cargo projects. Can be used as a substitution for cargo-check.
clippy (0.0.120)        A bunch of helpful lints to avoid common pitfalls in Rust
$ cargo install cargo-clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: could not find `cargo-clippy` in `registry https://github.com/rust-lang/crates.io-index`
```

**Comment by alexcrichton** [comment]
Out of curiosity do you have `.cargo/config` with a `replace-with` active? Otherwise I'm not entirely sure what'd cause this...

**Comment by alexcrichton** [comment]
Er wait nevermind, turns out [cargo-clippy](https://crates.io/crates/cargo-clippy) is yanked, and search isn't respecting that by default.

**Comment by carols10cents** [comment]
I think the real fix for this will be in crates.io, namely: https://github.com/rust-lang/crates.io/issues/1058, if that is fixed, `cargo search` would say `cargo-clippy (0.0.0)   this crate has been yanked` or similar. I think it's important to still return yanked crates in searches in case the reason you're doing a search is to see if the crate name has been taken or not. 

Closing in favor of https://github.com/rust-lang/crates.io/issues/1058, please continue any discussion there!
