### ISSUE TITLE
Exclude internal benches from cargo test

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/cargo#3853]
Currently `cargo test` excludes benches in the `benches/` folder and includes internal benches within the crate.  

Besides this assymetric behaviour functions annotated with `#[bench]` may be very compute intense, by definition and should be excluded from `cargo test` by default since they add high overhead whenever the test suite is running.  

This issue conflicts with issue #2984 that proposes to include benches in the `benches/` directory for `cargo test` which I am strictly against! To solve the problems issue #2984 tries to target it should be possible to mark `#[bench]` tests with an additional `#[test]` attribute in order to include them for `cargo test`:
```rust
#[bench] #[test]
fn foo(b: &mut Bencher) { .. }
```

A current ugly work around to exclude benches from running with `cargo test` is to add a crate feature (e.g. a feature called `run_internal_benches`) and invoke `cargo bench` as `cargo bench --features run_internal_benches`. This works as intended but is ugly.

Another thing we could think about is to introduce a flag for `cargo test` to include benches while the default should be set to exclude them.  

**Do not confuse testing with benchmarking:**

 - Tests are for testing the functionality of the system and should be performed often and should be as low-overhead as possible.
 - Benchmarks are often high-overhead and should be run whenever performance critical changes have been made.

**Comment by alexcrichton** [comment]
FWIW I think this behavior is surfaced from the test harness in rust-lang/rust, not Cargo itself. Perhaps an issue can be filed over there?

**Comment by Robbepop** [comment]
@alexcrichton 
Thanks for your comment!

Filed an issue at `rustc`!

**Comment by alexcrichton** [comment]
thanks! I'll close this in favor of that.
