### ISSUE TITLE
Cargo workspaces and `[replace]` may give a spurious warning

### ISSUE THREAD

**Issue by chriscoomber** [rust-lang/cargo#3861]
(accidentally raised at https://github.com/rust-lang/rfcs/issues/1957)

### Repro

https://github.com/chriscoomber/workspace_replace_example

### Symptoms

If I'm using workspaces, and I put a `[replace]` block in the workspace's `Cargo.toml`,  

then any crates within my workspace directory that **don't** depend on the crate being replaced produce the warning:

```
warning: package replacement is not used: ...
```

This is spurious because I've done nothing wrong. This exact usage is [what the rfc recommends](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md#lockfile-and-override-interactions) (unless I'm reading it wrong). Indeed, `[replace]` is totally ignored on non-workspace `Cargo.toml` files if a workspace exists (I just tested this).

This is undesirable because warnings like these may causes automatic builds to fail, which look for warnings.

### Workaround

So far I haven't figured out a workaround. For example - is the a flag I can pass to cargo to ignore this warning in particular? Is there a way to undo the `[replace]` on the crates that aren't affected?

**Comment by alexcrichton** [comment]
cc @matklad and https://github.com/rust-lang/cargo/pull/3386
