### ISSUE TITLE
Cargo tests can accidently pickup `~/.cargo/config`

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3863]
When testing `Cargo` itself, it picks up configuration from `~/.cargo/config` which may cause some test to fail. 

We probably want to fix it, but I can't concoct a non ugly way do do this. An ugly way would be to set a `__CARGO_TEST_STOP_AT` environmental variable.

**Comment by alexcrichton** [comment]
Yeah I'd be ok w/ an ugly env var for now, it'd at least get the job done.
