### ISSUE TITLE
cargo test should run unit tests alwais before integration tests

### ISSUE THREAD

**Issue by la10736** [rust-lang/cargo#3880]
I created a simple lib by `cargo init` command and then I added a integration `tests` directory with a test in a file named `integration.rs`.

If the integration test fail cargo don't execute unitests unless you are using `--no-fail-fast` flag. That is quite odd and make harder work in outside-in TDD style.

I suspect that in this case name mater because if I rename  `integration.rs` in `zzz.rs` unittests are executed before integration tests.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by la10736** [comment]
@bors Thx!! ... I'm too slow. I've fixed it on my fork yesterday and cleaned it this morning. I was done to send my PR that I found your (better) fix.

Thx again!
