### ISSUE TITLE
Will platform specific replace be a useful feature?

### ISSUE THREAD

**Issue by king6cong** [rust-lang/cargo#3881]
Now cargo support platform specific dependencies like this:

```
[target.'cfg(windows)'.dependencies]
winhttp = "0.4.0"
```

I think platform specific replace may also be need like this:

```
[target.'cfg(target_os = "ios")'.replace]
"backtrace:0.3.0" = { git = "https://github.com/alexcrichton/backtrace-rs" }
"native-tls:0.1.1" = { git = "https://github.com/king6cong/rust-native-tls/" }
```

Background:

1. I have to use my fork before PR merged or all upstream updated. in the meantime, replace is needed
2. use replace for backtrace make backtrace rebuild every time even without code change (is this expected?)
3. rebuild backtrace is slow so I want to replace it only on needed platform (iOS)

Will this be a useful feature or better ways to work around this?
Thanks.

**Comment by alexcrichton** [comment]
No unfortunately the design of `[replace]` means that it cannot be platform specific, the way that it affects lock file generation means that the original dependency doesn't even get resolved, meaning that it's impossible for the original dependency to be used later in Cargo's compilation graph.
