### ISSUE TITLE
Cannot depend on a proc-macro crate as a library

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/cargo#3882]
I want to make a procedural macro that's based on serde's derive (and so calls the serde tokenstream functions directly) but there's no way to say I want to consume serde derive as a library rather than a procedural macro (unless I missed something).

My only solution appears to be forking `serde_derive`.

**Comment by alexcrichton** [comment]
I believe this is a rustc limitation, not a cargo limitation?

**Comment by aidanhs** [comment]
Ah, I thought it'd be just a matter of passing the right flags to rustc, but it looks like it is indeed explicitly forbidden which I hadn't realised, thanks for pointing it out. Made a comment at https://github.com/rust-lang/rust/issues/38356
