### ISSUE TITLE
Cargo's temp files cause backup churn on macOS

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#3884]
macOS automatically makes hourly backups. Cargo's build temp files are large and frequently changing, causing gigabytes of redundant data backed up every day. 

Because the temp files are in multiple project-relative locations, it's not practical for users to manually exclude all the target folders from backup.

Mac applications generally avoid this problem by using system-designed caches directory, but the issue for it (#1615) seems to be in a stalemate.

So I'm proposing an alternative quick fix that doesn't require changing any paths in Cargo. macOS allows excluding individual directories from backups. I suggest marking `target/{build,deps,incremental}` as excluded. It can be done with:

```objc
[URL setResourceValue: @YES] forKey: NSURLIsExcludedFromBackupKey error:nil];
```

**Comment by alexcrichton** [comment]
Sounds like a nifty idea to me!

**Comment by cyplo** [comment]
What do you think about promoting this issue as beginner-friendly ?

**Comment by pornel** [comment]
For me the question is how to call ObjC method from Cargo. There are various approaches for this. Does Cargo have some crate/macro/.m files for this already?

**Comment by alexcrichton** [comment]
Perhaps the [objc](https://crates.io/crates/objc) crate could be of assistance?

**Comment by pornel** [comment]
I've managed to implement marking using the objc crate: 

https://gitlab.com/kornelski/exclude_from_backups/blob/master/src/macos.rs

Are you OK adding [it as a dependency](https://crates.io/crates/exclude_from_backups), or should I copy the code to Cargo?

**Comment by alexcrichton** [comment]
Either's fine by me, although I'd slightly lean towards just copying it into Cargo as it may change over time. Thanks @pornel!

Out of curiosity, have you confirmed that this does indeed fix the problem?

**Comment by pornel** [comment]
I've verified that it sets `com.apple.metadata:com_apple_backup_excludeItem` extended attribute on files and directories, so the call works. 

The feature requires macOS 10.8+, so I'll need to disable it on 10.7. Does Rust's CI run on 10.7? I don't have a 10.7 machine to test on.

**Comment by alexcrichton** [comment]
Does this also solve the backup churn you were noticing?

Also yeah we'll need to work on 10.7 somehow, but it's ok to not add a test for this. Is it possible to just ignore errors on 10.7?

**Comment by pornel** [comment]
It may fail to link on 10.7. I'd have to use `#[linkage = "extern_weak"]`.

**Comment by pornel** [comment]
I've verified that it prevents the backup churn (I've manually marked all target dirs, and none were in my latest backup).

**Comment by pornel** [comment]
I've also got a new implementation using servo/core-foundation-rs, which makes the code shorter.

**Comment by alexcrichton** [comment]
Ok looks and sounds great to me!
