### ISSUE TITLE
Installing section is outdated

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3886]
Installing section at https://github.com/rust-lang/cargo/blob/master/src/doc/index.md is an ancient artifact of the pre-rustup era. It should probably just direct the reader to https://www.rust-lang.org/en-US/install.html.

**Comment by cyplo** [comment]
It seems mentioning rustup now, is that good enough ?

**Comment by dwijnand** [comment]
The instructions use rustup _and_ link to the Rust install docs. This issue has be resolved and can be closed.
