### ISSUE TITLE
Cargo run does not display segmentation fault information

### ISSUE THREAD

**Issue by isaacg1** [rust-lang/cargo#3891]
With the following program, which causes a segmentation fault by allocating too much on the stack:
```
fn main() {
    println!("Hello world");
    let memo = [[[0; 255]; 255]; 255];
}
```
Running `cargo build` followed by executing the binary prints: `Segmentation fault (core dumped)`.
In contrast, running `cargo run` gives no textual indication of the failure. The output displayed is:
```
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `./three`
```

This is using either of cargo 0.16.0 and 0.15.0 on Ubuntu Linux 14.04

**Comment by alexcrichton** [comment]
Thanks for the report! Cargo just calls `exec`, however, on the binary `./three`. In that sense it's up to your shell to report segfault information, but this is likely being [swallowed by rustup](https://github.com/rust-lang-nursery/rustup.rs/issues/845), so I'm going to close in favor of that issue.
