### ISSUE TITLE
Disable default feature not working in dependency

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/cargo#3894]
When project A depends on crate B and crate C, both B and C depend on D, and C requires D disable default feature, I can't find a way to get A compiled without forking either B or C then modify its Cargo.toml.

A simple example: https://github.com/BusyJay/test-custom-allocator. test-custom-allocator depends on rocksdb and jemallocator, both depend libc. When compile it, cargo complains
>error: the crate `jemallocator` cannot depend on a crate that needs an allocator, but it depends on `alloc`

That's because libc's default feature is eanbled, which will depend on the std crate and then be conflict with the jemallocator. It seems cargo ignores the "default-features = false" I specify in Cargo.toml. I also try `[replace]`, and due to https://github.com/rust-lang/cargo/issues/3034, it doesn't work. I can get it compiled to fork rocksdb, and add "default-features = false" to its Cargo.toml.

**Comment by alexcrichton** [comment]
Yes this is an unfortunate consequence of how features work in Cargo. Cargo *unions* all enabled features of a dependency which means that if *any* crate enables the default feature (implicitly or explicitly) then it's turned on for everyone.

In general the `no_std` feature for libc should not be a default-on feature, it should be a default-off feature. Unfortunately for backwards compatibility we haven't changed it yet, but we'll do so on the next major release.

**Comment by BusyJay** [comment]
I was able to get round this via using `#[feature(libc)]`. But latest nightly includes two libc.rlib, which will lead to conflict and not work any more.
