### ISSUE TITLE
Symlinks are silently published as regular files

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#3896]
I've got an opposite problem of #2748 — in my package I needed [a symlink for a test](https://github.com/pornel/duplicate-kriller/tree/master/tests), but the symlink silently [became a regular file](https://github.com/pornel/duplicate-kriller/issues/3) in the copy obtained from crates.io.

I'd prefer the symlink to stay as a symlink, at least on non-Windows. Or an error/big warning during publishing that the symlink has been replaced.

**Comment by da-x** [comment]
Please note that some packages currently rely on this behavior. Example: https://github.com/serde-rs/serde/tree/bb99b31eb0a55393101f9c80cd959b3a739ad70f/serde (symlinks in the serde repo).

**Comment by kornelski** [comment]
I think a nice compromise would be to keep symlink *if* it points to a file within the package, and copy if the symlink points to outside of the package (like the often used `../README` symlink).

But given how annoying Windows is with its semi-support for symlinks, I probably have to resign to symlinks being lost.
