### ISSUE TITLE
Allow modifying codegen-units from .cargo/config

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#3897]
There are a couple reasons why this could be useful:
* rather than forcing all developers to use a particular number of codegen units (unless they modify Cargo.toml, which is annoying in a VCS-tracked file), this allows overriding a suggested default with something appropriate to the current hardware
* this will allow me to work around https://github.com/rust-lang/rust/issues/39160 with much less friction while maintaining a sensible default for other Servo developers

**Comment by ehuss** [comment]
Setting codegen-units in config files can now be done via config-profiles (https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-profiles).  The tracking issue for stabilization is at https://github.com/rust-lang/rust/issues/48683.
