### ISSUE TITLE
CARGO_INCREMENTAL breaks debuginfo

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/cargo#3905]
In the same project, if I compile with CARGO_INCREMENTAL=1 and run the application through lldb, I get:

```
$ lldb target/debug/hello
(lldb) target create "target/debug/hello"
Current executable set to 'target/debug/hello' (x86_64).
(lldb) b main
Breakpoint 1: where = hello`main, address = 0x00000001000141d0
```

Same project without:

```
$ lldb target/debug/hello
(lldb) target create "target/debug/hello"
Current executable set to 'target/debug/hello' (x86_64).
(lldb) b main
Breakpoint 1: 2 locations.
```

The latter, I believe, is what we want as it's what you'd get by hand when using `rustc`.  With incremental turned on, we can't easily step into the original source.  Instead, we end up stepping through the assembly.

**Comment by jonathandturner** [comment]
cc @michaelwoerister and @nikomatsakis

**Comment by michaelwoerister** [comment]
Is this on OSX? If so this might be the same problem as https://github.com/rust-lang/rust/issues/39160.

**Comment by jonathandturner** [comment]
Yes, this on macOS

Jonathan
_____________________________

**Comment by nikomatsakis** [comment]
@jonathandturner care to try and narrow it down by building w/o incremental, but w/ codegen-units?

**Comment by nikomatsakis** [comment]
eg, by setting `RUSTFLAGS="-Zcodegen-units=256"` or something; I guess it' snot clear what setting would do it, but something big is likely to work :)

**Comment by jonathandturner** [comment]
@nikomatsakis - yes, I can confirm the -Ccodegen-units=256 causes the same issue.

**Comment by jonathandturner** [comment]
Closing as a dupe of https://github.com/rust-lang/rust/issues/39160

(plz fix kthx 😄)
