### ISSUE TITLE
Support wildcard version spec that matches any version

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#3910]
I have private crates in tree that carry various tests and depend on the parent crate.

I would like all the private (never published to crates.io) crates to be able to use `parent = { version = "*", path = ".." }`.

This works fine, until the parent crate uses a prerelease version for any duration of time, then the wildcards suddenly don't match. This is very inconvenient.

**Comment by alexcrichton** [comment]
cc @steveklabnik, do you know if there's any standard semver tool for this?

**Comment by matklad** [comment]
@bluss won't `parent = { path = ".." }` work for you? That is, just omitting the `version` key?

**Comment by bluss** [comment]
@matklad Indeed, that's great, it seems to work just like it was needed.
