### ISSUE TITLE
Load author name and email from innermost git config

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/cargo#3920]
It appears that `cargo init` always uses the name and email configured in ~/.gitconfig. It would be more useful (especially when working with workspaces with many crates) if `cargo init` produced the same output as `git config user.name` and `git config user.email` which can be configured per repo.

**Comment by alexcrichton** [comment]
Sounds plausible to me! I believe the relevant change would go [around here](https://github.com/rust-lang/cargo/blob/89ca25e1c0944c79bc025c4012f26b3e2f04a369/src/cargo/ops/cargo_new.rs#L516) and would likely attempt to use [`Config::open`](https://docs.rs/git2/0.6.4/git2/struct.Config.html#method.open) instead on the cwd.
