### ISSUE TITLE
When updating dependency with submodules fails, make error source more apparent

### ISSUE THREAD

**Issue by koivunej** [rust-lang/cargo#3922]
Given a dependency `foo` which in it's dependent revision depends on a submodule revision that no longer exists the error message currently looks like this (only error part):

```
error: failed to load source for a dependency on `foo`
Caused by:
  Unable to update <foo-url>?rev=hash
```

and only with `--verbose` you see (only error part):

```
error: failed to load source for a dependency on `foo`
Caused by:
  Unable to update <foo-url>?rev=hash
Caused by:
  failed to update submodules
Caused by:
  [9/-3] object not found - no match for id (another_hash)
```

where `another_hash` is the submodule revision that cannot be found in the case of git.

This is a rather contrived example, but I think other people than me could achieve this as well if you happen to have:
 1. your own crate which...
 2. ...depends on a custom fork of a library where you develop a PR
 3. rebasing your PR on top of latest changes and force-pushing deletes the old revision

@alexcrichton noted that [error here should be more visible without needing `--verbose`](https://github.com/rust-lang/cargo/issues/3561#issuecomment-293947103) so I am opening an issue not to highjack the original issue in which this was discussed for any longer.

For the initial error without `--verbose`, perhaps the output should had been:

```
-error: failed to load source for a dependency on `foo`
+error: failed to update submodules for a dependency on `foo`
 Caused by:
-  Unable to update <foo-url>?rev=hash
+  Failed to update submodules of <foo-url>?rev=hash
```

I am hoping to fix this myself with some mentoring from alexcrichton. Does the proposed new error output look good enough?

**Comment by koivunej** [comment]
Looks like the errors are generated in [`src/cargo/sources/git/utils.rs`](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/git/utils.rs) lines [160](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/git/utils.rs#L160) or [342](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/git/utils.rs#L342). Luckily there is also a basic functionality test for git submodules at [`tests/git.rs`](https://github.com/rust-lang/cargo/blob/master/tests/git.rs#L708-L752).

Related error functionality can be found at `src/cargo/util/errors.rs`](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/errors.rs). Root error ("failed to load source for a dependency") seems to come out of [`src/cargo/core/registry.rs`](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/registry.rs#L340-L341) so changing the root message is probably not preferred, instead I'll try to aim at:

```
 error: failed to load source for a dependency on `foo`
 Caused by:
-  Unable to update <foo-url>?rev=hash
+  Failed to update submodules of <foo-url>?rev=hash
```

**Comment by alexcrichton** [comment]
Spot on on all counts! Thanks for opening this, I'll take a look at the PR
