### ISSUE TITLE
Benchmark is not found if it is named "bench.rs"

### ISSUE THREAD

**Issue by sunjay** [rust-lang/cargo#3932]
This is from @vbuell's report here: https://github.com/bluss/bencher/issues/8
I have slightly modified it to add more details.

Step to reproduce:

Create some simple benchmark file in `benches/bench.rs`. Put in Cargo.toml:

```
[[bench]]
name = "bench"
harness = false
```

Run `cargo bench`.

Cargo fails with the error:

```
error: couldn't read "src/bench.rs": No such file or directory (os error 2)
error: Could not compile `benchmark_templates`.
```

Note that it tries to read benchmark file from src/ directory. Strangely enough that it fails only if file named as bench.rs. Any other name works ok - if I change the name to "bench_" in Cargo.toml, it looks for the file in benches directory:

```
error: couldn't read "benches/bench_.rs": No such file or directory (os error 2)
error: Could not compile `benchmark_templates`.
```

**Comment by alexcrichton** [comment]
Oh dear, what an odd bug! Hard to imagine how that came about...

Definitely a bug to fix though!

**Comment by tee-too** [comment]
When the name of a bench is `bench`, it is searched in `src/` on purpose (see [here](https://github.com/rust-lang/cargo/blob/03efb7fc8b0dbb54973ee1b6188f3faf14fffe36/src/cargo/util/toml.rs#L1377-L1383))

Note that there is the same hack for test. If the name of a test is `test`, it is searched in `src/` (see [here](https://github.com/rust-lang/cargo/blob/03efb7fc8b0dbb54973ee1b6188f3faf14fffe36/src/cargo/util/toml.rs#L1369-L1375)).

Probably easy to fix, but this could be a breaking change, with an easy remediation (using `path`).

@alexcrichton, I you still think it's a bug, I would be happy to fix it.

**Comment by matklad** [comment]
@tee-too ah, I've just send a PR with a fix :) 

Looks like `src/test.rs` and `src/bench.rs` used to be default test/bench target, the same way `src/main.rs` is a default `bin`. This no longer works though, so the only backcompat hazard is that someone has

```
[[test]]
name = "test"
```

and a test file in `src/test.rs` which seems rather unlikely.

**Comment by tee-too** [comment]
@matklad Seems I was too slow on this. Nice shot 😄
