### ISSUE TITLE
Disabling recursive Cargo.toml search on `cargo install --git ...`

### ISSUE THREAD

**Issue by fantoine** [rust-lang/cargo#3935]
I have a bin project which I want to install from a git repository with `cargo install --git ...`.

I have some files named `Cargo.toml` on my tests. These files are not meant to be used by Cargo but only for my tests, and some of them are intentionally malformed.

Installing from git doesn't work correctly because of this. It looks like Cargo seek to find and interpret all `Cargo.toml` files on the repository, and then, obviously, it breaks the compilation because of these malformed files.

Strangely, it works correctly if I use `cargo install --path ...` on a local cloned repository.
By the way, if I change the call to `PathSource::new_recursive(..)` by `PathSource::new(..)` on `cargo/sources/git/source.rs` file, it works correctly for my case.

I looked on Cargo source code, but didn't find why this recursive search is required?
Is there a way to disable it, or at least on `tests` folder?

**Comment by alexcrichton** [comment]
Ah yeah this is an unfortunate aspect of Cargo where when you specify a git dependency you only specify a repository, not a path within that repository. This means that to find nested dependencies Cargo must auto-probe the repository for all `Cargo.toml` files.

I think though that Cargo should probably just ignore malformed `Cargo.toml`, especially in git dependencies. That I believe would work for your use case as well, right?

**Comment by fantoine** [comment]
I understand better why it works like this.

I guess that ignoring malformed `Cargo.toml` files could work in my case.

However, intuitively I expected `git` source to behave just like `path` source.
Maybe, an other solution could be to have an optional flag in parallel of `--git` to enable/disable this recursive behavior?

**Comment by fantoine** [comment]
Or even simpler, it may ignore all Rust folders just like `target` is ignored:

**Comment by alexcrichton** [comment]
Nah I think we should basically just ignore bad manifests for now. Anything else runs the risk of being a breaking change, unfortunately.

**Comment by fantoine** [comment]
I think it's ok for me like this. :)

Should I submit a PR?
I'm not sure where to ignore invalid `Cargo.toml` files.

**Comment by alexcrichton** [comment]
Oh yes of course PRs would be most welcome! 

The errors stem from [around this location](https://github.com/rust-lang/cargo/blob/7cfeec1aaac3d1909af8476f66c547619eceb640/src/cargo/sources/path.rs#L70-L71) (notably the `recursive` flag), although I'm not 100% sure where the fix would go.

**Comment by carols10cents** [comment]
Looks like this was fixed by https://github.com/rust-lang/cargo/pull/3998. Closing, thank you!!
