### ISSUE TITLE
doctests don't print warnings by default

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/cargo#3938]
Running `cargo test` runs doctests by default, and shows warnings for regular code, but not for the doctests themselves. This can be enabled by running `cargo test -- --nocapture`. I'd like to have warnings also show in our CI tests, even for doctests, but setting `-- --nocapture` shows all the output which we don't want (and can't control, because they come from the underlying libraries complaining about our tests that are supposed to fail).

I'd think having warnings on for doctests by default would be good, but that wouldn't be backwards compatible. Maybe a `--doctest-warnings` option could be added in lieu of that?

**Comment by alexcrichton** [comment]
I believe this is a bug for rustdoc, not cargo?

**Comment by alexcrichton** [comment]
er didn't mean to close yet

**Comment by Susurrus** [comment]
Sure, is rustdoc an external crate? I didn't see it under `rust-lang` so I figured it was part of cargo. Where should I file tickets for this? Also, should this ticket stay open if the default behavior of rustdoc might change?

**Comment by alexcrichton** [comment]
Oh it's just a portion of the rust-lang/rust repository

**Comment by Susurrus** [comment]
Should I file this issue with rust or rfcs then?

**Comment by alexcrichton** [comment]
Oh just in rust-lang/rust is fine, likely no need for an rfc

**Comment by Susurrus** [comment]
Closing in lieu of rust-lang/rust#41574
