### ISSUE TITLE
Can I store things in the target directory?

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/cargo#3939]
If I have a build dep that needs to create intermediate files (not rust source), is it safe to store them in the target directory? Does cargo whipe this directory ever? Is there any convention about this (like how noncargo configs in the toml belong in package.metadata)?

**Comment by alexcrichton** [comment]
Cargo will wipe it on `cargo clean` (without arguments), but otherwise should be good!

**Comment by carols10cents** [comment]
Sounds like the answer is "yes" so I'm closing this-- please reopen if there's some action we need to take here! Thank yoooouuu :)
