### ISSUE TITLE
The wording in error message is not clear

### ISSUE THREAD

**Issue by dkotrada** [rust-lang/cargo#3940]
Running this command `cargo build --target=armv7-unknown-linux-gnueabihf` on Windows 7
I got this message. 
~~~
error: could not exec the linker `arm-linux-gnueabihf-gcc-4.9`: Das System kann die angegebene Datei nicht finden. (os error 2)
~~~

It says in German "The System can't find a file". So my question what System? Who is "System"

**Comment by alexcrichton** [comment]
Thanks for the report! This error message is actually printed by rustc, but the wordering there actually comes from Windows itself. 

Could you open a bug against rust-lang/rust for improving this error message?

In the meantime, though, that message means that the binary was not found, and you may be able to fix it by pointing Cargo at the appropriate linker for cross-compiling to Android on Windows.
