### ISSUE TITLE
Support fully reproducible `fetch` phase and build with no network

### ISSUE THREAD

**Issue by bennofs** [rust-lang/cargo#3943]
For packaging rust crates, it would be nice if building cargo crates could be split into the following two phases:

* a fetch phase, which has full network access
* a build/install phase, which may not access the network

where the `fetch` phase produces some directory with a consistent hash that may be accessed by the `build/install` phase. This is almost doable today with `cargo vendor` or `cargo local-registry`, but unfortunately `cargo vendor` does not work for git dependencies. Git dependencies are also tricky because a git repository does not have a constant hash, so ideally cargo would support replacing the git dependency with a checkout that has no `.git` anymore.

**Comment by alexcrichton** [comment]
So, as written, this is precisely possible with:

* `cargo fetch`
* `cargo build`

This is intended to be solved in the packaging world with the two dependencies that you mentioned, and the fact that `cargo vendor` doesn't support git directories is just a bug. Thanks for the report though!

**Comment by bennofs** [comment]
@alexcrichton the problem is though that we would need to replace git dependencies with a path that is not a git repository at all, since git repositories aren't deterministic on the file system (because `.git` is not deterministic)

**Comment by bennofs** [comment]
@alexcrichton how would this be possible to implement with the current cargo features, if I want to contribute to `cargo-vendor`? I'd should also deal well with submodules.

**Comment by alexcrichton** [comment]
Ok well to be clear we're diverging pretty quickly from this issue as-stated. That's ok, just want to point that out.

Yes it's correct that Cargo doesn't support replacing git dependencies today, I forgot about that! Support would first need to be [added to Cargo](https://github.com/rust-lang/cargo/blob/03efb7fc8b0dbb54973ee1b6188f3faf14fffe36/src/cargo/sources/config.rs#L131-L155) and then support would need to be added to `cargo-vendor` and `cargo-local-registry` for vendoring git deps.
