### ISSUE TITLE
Fail to use git in dependencies

### ISSUE THREAD

**Issue by xinghun92** [rust-lang/cargo#3958]
When I use git in dependencies like this:

```
[dependencies]
rand = { git = "https://github.com/rust-lang-nursery/rand.git" }
```

Once I run `cargo build --verbose`, the terminal shows this:

```
Updating git repository `https://github.com/rust-lang-nursery/rand.git`
warning: spurious network error (2 tries remaining): [2/-1] failed to create temporary file '/pack_git2_DYHRZh': Permission denied
warning: spurious network error (1 tries remaining): [2/-1] failed to create temporary file '/pack_git2_PFZfpl': Permission denied
error: failed to load source for a dependency on `rand`

Caused by:
  Unable to update https://github.com/rust-lang-nursery/rand.git

Caused by:
  failed to fetch into /Users/wangsijie/.cargo/git/db/rand-02690058d91f0548

Caused by:
  [2/-1] failed to create temporary file '/pack_git2_dBJExA': Permission denied
```

Git attempts to create temporary files in root directory. When I run `cargo build --verbose` with `sudo`, the process also failed, and the terminal shows this:

```
Updating git repository `https://github.com/rust-lang-nursery/rand.git`
error: failed to load source for a dependency on `rand`

Caused by:
  Unable to update https://github.com/rust-lang-nursery/rand.git

Caused by:
  failed to fetch into /Users/wangsijie/.cargo/git/db/rand-02690058d91f0548

Caused by:
  [4/-1] target OID for the reference doesn't exist on the repository
```
When I clone this repository by `git clone`, it works. 

Mac version : macOS Sierra 10.12.4
Cargo version : cargo 0.19.0-nightly (03efb7fc8 2017-04-23)
Rustc version : rustc 1.18.0-nightly (2b4c91158 2017-04-25)

**Comment by alexcrichton** [comment]
Seems odd! Do you have a `~/.gitconfig` or other form of git configuration active?

**Comment by xinghun92** [comment]
I could not find what's wrong in my git configuration. So I re-install my MacOS, then it works.

**Comment by whilei** [comment]
I ran into exactly the same thing. `rm -rf ~/.git_template/.git` worked for me. Don't version control your version control.
