### ISSUE TITLE
Feature request: Expose a way to check whether a binary is fresh or not

### ISSUE THREAD

**Issue by golddranks** [rust-lang/cargo#3960]
Cargo subcommands and scripts would benefit from this.

Here's my use case: if the binary is not fresh, I want to trigger `cargo build` before the script continues. In this case I want to expose the output of `cargo build` to the user. However, if the binary is fresh, I don't want to show the line `Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs` to the user. It would be nice if there would be a script-oriented way to check if there is a need to rebuild a particular binary.

**Comment by dralley** [comment]
I don't think this would need a new subcommand.  Just add ```[cached]``` (or something) to the output string when nothing needed to be rebuilt.

**Comment by epage** [comment]
Is this the same thing as #3180?

**Comment by dralley** [comment]
Sounds like it
