### ISSUE TITLE
Retry if S3 returns 500

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#3962]
Crates.io redirects to S3 for /download requests. [Sometimes S3 returns a 500](https://github.com/rust-lang/rust/issues/41545), and cargo should automatically retry.

Cargo has [network retry logic](https://github.com/rust-lang/cargo/pull/2396), but right now it [only retries if the error is "spurious"](https://github.com/rust-lang/cargo/blob/fa7584c1495c2d9c04a6416f8e7b546abfa88a52/src/cargo/util/errors.rs#L337-L345).

We should tweak `maybe_spurious` to count 500 as something that should be retried, not sure which one of [the curl errors](https://docs.rs/curl/0.4.6/curl/struct.Error.html) corresponds to that or if we should just check the status code [like this check does](https://github.com/rust-lang/cargo/blob/fa7584c1495c2d9c04a6416f8e7b546abfa88a52/src/cargo/sources/registry/remote.rs#L173-L175).

**Comment by alexcrichton** [comment]
Currently the way curl operates a 500 isn't actually an error, but rather the [`perform` function](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/registry/remote.rs#L170) returns `Ok(())`, and then later when we extract the status code from the handle it says that it 500'd. Sort of like how if you `.wait()` on a process it'll return `Ok` even though the exit status may indicate failure.

I think the best way to solve this will be to first create a new error type:

```rust
enum CargoCurlError {
    Io(curl::Error),
    Code(u32),
}
```

Next implement the `CargoError` trait for this type as well as the network error trait. The [closure here](https://github.com/rust-lang/cargo/blob/fa7584c1495c2d9c04a6416f8e7b546abfa88a52/src/cargo/sources/registry/remote.rs#L161-L171) would then be updated to return this new error, moving the 500 checking logic into the closure. The implementation of the network error trait would then return "true" for "maybe_spurious" when the code is 500.

I'm gonna tag this as E-easy as I think it's a good starter bug, but if help is needed please just let me know!

**Comment by 0X1A** [comment]
@alexcrichton I'm willing to offer a PR for this

**Comment by alexcrichton** [comment]
Awesome thanks @0X1A! Lemme know if you have any questions

**Comment by nagisa** [comment]
500, 502, 503, 504 errors are all “spurious”.

**Comment by aturon** [comment]
@0X1A Just checking in, are you still interested in working on this?

**Comment by 0X1A** [comment]
@aturon Sorry, I've been a bit swamped recently, someone else is free to take this one

**Comment by alexcrichton** [comment]
I've opened a PR for this at https://github.com/rust-lang/cargo/pull/4032
