### ISSUE TITLE
docs for * deps don't mention locally vs crates.io

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#3971]
reported here https://news.ycombinator.com/item?id=14217327

**Comment by carols10cents** [comment]
Copy pasting because I've been bitten by bug reports linking to something that went away:

> The version requirement in the cargo.toml file under [dependencies] is
> 
>    chrono="*"
>
> which, according to this manual [1] is valid.
> 
> [1] http://doc.crates.io/specifying-dependencies.html

>> Yes, star dependencies were removed like a year ago, for semver issues. They went through multiple release cycles of warnings.
>
> From the Cargo manual [1]:
>
>    Wildcard requirements
>
>    Wildcard requirements allow for any version where the wildcard is positioned.
>
>    *, 1.* and 1.2.* are examples of wildcard requirements.
>
>    * := >=0.0.0
>    1.* := >=1.0.0 <2.0.0
>    1.2.* := >=1.2.0 <1.3.0
>
> Apparently, nobody bothered to update the manual after removing the feature.
> 
> [1] http://doc.crates.io/specifying-dependencies.html

> Second, the Cargo star dependencies report. Manishearth is wrong, we disallow those dependencies from being uploaded to crates.io, but end users are allowed to use them just fine (strongly recommended that you don't, though!).

**Comment by alexcrichton** [comment]
Just to make sure I understand, sounds like we should update the documentation for crates.io that `*` dependencies are disallowed, but that's the only change?

**Comment by carols10cents** [comment]
> Just to make sure I understand, sounds like we should update the documentation for crates.io that * dependencies are disallowed, but that's the only change?

Pretty much, yeah, we should clarify that `*` dependencies are allowed *in general* but are disallowed *if you publish your crate to crates.io*.
