### ISSUE TITLE
CARGO_INCREMENTAL: Cargo should only compile crates incrementally that can be changed by the user

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/cargo#3972]
Compiling a crate in incremental mode with an empty cache is often slower than compiling the crate non-incrementally. Also, the generated binary is likely to exhibit worse runtime performance and the IC cache for the crate takes up space on disk. At the same time, having a non-incrementally compiled dependency does not have any detrimental effects on incremental compilation as long as that dependency does not change. For these reasons it makes sense to always compile things coming from crates.io or other external sources in non-incremental mode.

**Comment by alexcrichton** [comment]
Sounds reasonable to me! 

Such a change would likely [go here](https://github.com/rust-lang/cargo/blob/04574f0d1893781edf9cf5c8df643237443d9371/src/cargo/ops/cargo_rustc/context.rs#L867-L873) and have an extra check for [path sources](https://github.com/rust-lang/cargo/blob/04574f0d1893781edf9cf5c8df643237443d9371/src/cargo/ops/cargo_rustc/context.rs#L392). Users can only modify path sources, all others should be frozen in Cargo's cache somewhere.
