### ISSUE TITLE
Git sources cannot be overridden

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/cargo#3976]
```
[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo" }

[replace]
"cargo:0.20.0" = { path = "cargo" }
```

No, it doesn't work.

```
warning: package replacement is not used: https://github.com/rust-lang/crates.io-index#cargo:0.20.0
```

**Comment by alexcrichton** [comment]
For git sources you need to specify the URL as well, does it work then?

**Comment by ishitatsuyuki** [comment]
Can you clarify about the format? Simply specifying the URL as the version was rejected as invalid syntax.

**Comment by alexcrichton** [comment]
The documentation for the [replace section](http://doc.crates.io/manifest.html#the-replace-section) indicates keys are [package id specifications](http://doc.crates.io/pkgid-spec.html) which has docs and [examples](http://doc.crates.io/pkgid-spec.html#example-specifications) of package ids.

**Comment by ishitatsuyuki** [comment]
This was resolved with the following syntax:

```
[replace]
"https://github.com/rust-lang/cargo#0.20.0" = { path = "cargo" }
```

Thanks for pointing me to the right direction.
