### ISSUE TITLE
cargo metadata's resolve output doesn't specify depenency kinds

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#3984]
[cargo-tree](https://github.com/sfackler/cargo-tree) needs to know the kind of dependencies (i.e. normal, build, dev) before it can switch over to using `cargo metadata` rather than linking to cargo as a library.

**Comment by alexcrichton** [comment]
This seems reasonable to me! Serialization currently [happens here](https://github.com/rust-lang/cargo/blob/7cfeec1aaac3d1909af8476f66c547619eceb640/src/cargo/ops/cargo_output_metadata.rs#L88-L103) and we'd probably just tweak the `dependencies` list slightly in `Node`

**Comment by sfackler** [comment]
Seems like this'd require a metadata version bump, right?

**Comment by matklad** [comment]
>Seems like this'd require a metadata version bump, right?

Adding new keys doesn't need a version bump, the clients should ignore extra keys.

**Comment by alexcrichton** [comment]
Ah yeah I think it may require some intrusive code changes, but I figured we could just add keys to the maps emitted.
