### ISSUE TITLE
Give more examples of turning `.cargo/config` keys into env vars

### ISSUE THREAD

**Issue by shahn** [rust-lang/cargo#3985]
I'm using cargo in an autoconf-managed build system. I want to auto-generate a part of the .cargo/config file, because Cargo doesn't seem to expose env variables for the vendored sources config options, but where the vendored sources live should be overwritable by the user during ./configure. It seems cargo really wants to be run inside the source tree, but config.status places the generated .cargo/config into the build dir. Copying the entire rust tree of the project from the source dir into the build dir could be a workaround, but instead it'd be neat if cargo allowed to just specify a different location for its config file.

**Comment by alexcrichton** [comment]
Note that it's a bug in Cargo if Cargo doesn't read `.cargo/config` values from the environment, so I think that may be the best fix here?

**Comment by shahn** [comment]
Perhaps I misunderstand, but what would the env variables even be for something like [source.vendored-sourced] where the vendored-sources seems to be a user-defined string?

**Comment by alexcrichton** [comment]
Oh in general we just have a standard mechanism for defining config values [as environment variables](http://doc.crates.io/config.html#environment-variables)

**Comment by shahn** [comment]
that doesn't explain at all how to set that. It says: "For each configuration key above of the form foo.bar the environment variable CARGO_FOO_BAR can also be used to define the value. For example the build.jobs key can also be defined by CARGO_BUILD_JOBS."

This doesn't explain how to put this:
    [source.vendored-sources]
    directory = "foo"
into env variables. Also, how can I unset something via env variable that's given in a configuration file? Happy to improve the documentation once I understand that :)

**Comment by alexcrichton** [comment]
Oh that would in theory be `CARGO_SOURCE_VENDORED_SOURCES_DIRECTORY=foo`. Unfortunately there's no way to unset what's in a config file, although I believe the environment takes precedence.

PRs are of course always welcome to improve the docs!

**Comment by dylanede** [comment]
@alexcrichton It doesn't look like setting environment variables to set source properties like that is supported, and the relevant source code is just looking up "sources" from a hash map, without checking the environment variables. I'll raise a bug for this.

**Comment by ehuss** [comment]
There is now a lot more information about setting environment variables via #7650.  The `[source]` table not supporting env vars is tracked via #5416.
