### ISSUE TITLE
Add an envvar to disable network tests

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#3987]
Debian buildservers run with network access disabled during the build, so I have to manually patch out some cargo tests like this:

https://sources.debian.net/src/cargo/0.17.0-1~exp2/debian/patches/disable-net-tests.patch/

Also right now it is slightly annoying to keep this patch updated for future version of cargo, because I have to run *all* the tests N times, if I want to disable N more tests, because cargo fails on the first error.

Something like `CFG_DISABLE_NETWORK_TESTS` would be good, I'm already setting `CFG_DISABLE_CROSS_TESTS=1`. In order to keep this working correctly in the long run, you could set up an iptables rule for the rust buildbots, something [like this](https://wiki.debian.org/sbuild#Disabling_network_access_for_dpkg-buildpackage) (ignore the "doesn't work notice, it applies to that specific program being run afterwards but the rule should work fine).

**Comment by alexcrichton** [comment]
Oh dear none of our tests should depend on the outside network!

I'd be more than willing to take PRs to correct these mistakes in Cargo!

**Comment by carols10cents** [comment]
Just turned my internet off and ran cargo's tests and they all passed, so I'm closing this as fixed :)
