### ISSUE TITLE
Update binary names blacklist

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#3990]
We [blacklist](https://github.com/rust-lang/cargo/issues/1618) certain binary names, including "examples". However, we don't check the blacklist when creating the project

```
λ cargo new --bin examples --verbose
warning: compiling this new crate may not work due to invalid workspace configuration

failed to parse manifest at `/home/user/trash/examples/Cargo.toml`
     Created binary (application) `examples` project
```

Also, we now store `incremental` directory in the `target`, so it should be blacklisted as well.

So we need to check that blacklist is up-to-date, and use it when creating a new project. 

Alternatively, perhaps we can go the other way around and remove `examples` and other folders from the `target` dir and store them elsewhere?

**Comment by alexcrichton** [comment]
I'd probably stick to just extending the blacklist for now, changing the structure of the target dir tends to be tricky
