### ISSUE TITLE
Ignore /target instead of any target

### ISSUE THREAD

**Issue by behnam** [rust-lang/cargo#3997]
When creating a `.gitignore` file with this line:
```
target
```
it will ignore any file/dir named `target` anywhere in the repo. Meaning, this would also ignore `/src/target/`, a submodule, and all its content.

To resolve this problem, we should instead ignore the `target` dir on the top level:
```
/target
```
and, if we want to make sure it's only ignored if a dir:
```
/target/
```

What do you think?

**Comment by alexcrichton** [comment]
This has come up a few times before (https://github.com/rust-lang/cargo/issues/3158, https://github.com/rust-lang/cargo/issues/2565, https://github.com/rust-lang/cargo/issues/1952, https://github.com/rust-lang/cargo/issues/1415), but it seems surprising enough that something needs to change! Mind taking a look at some of those linked issues and see if it changes things?

**Comment by behnam** [comment]
So, this was **not** an issue before, because `target` would only match the path in root. But, now that we're in the migration to [gitignore-style matching](https://github.com/rust-lang/cargo/issues/4268), we will need to update this after State 1.1 of the migration makes it to beta or stable channels.

Keeping this issue open as a tracker for this specific of the migration.

**Comment by behnam** [comment]
This is already addressed in master: https://github.com/rust-lang/cargo/blob/62f800fd8760faec2f4b69a464194d9b89d56983/src/cargo/ops/cargo_new.rs#L395-L404

PR: https://github.com/rust-lang/cargo/pull/4099
