### ISSUE TITLE
'cargo new --vcs hg' generates an invalid .hgignore file

### ISSUE THREAD

**Issue by gclinch** [rust-lang/cargo#4005]
```bash
tmp$ hg --version
Mercurial Distributed SCM (version 4.2)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2017 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
tmp$ cargo --version
cargo 0.18.0 (fe7b0cdcf 2017-04-24)
tmp$ cargo new --vcs hg hgtest
     Created library `hgtest` project
tmp$ cd hgtest/
hgtest$ hg status
abort: /private/tmp/hgtest/.hgignore: invalid pattern (relre): **/*.rs.bk
hgtest$ 
```

Mercurial's default hgignore syntax is 'regexp', which doesn't accept an initial '*'.

Adding 'syntax: glob' to the top of the file (but only when the vcs is hg) should resolve this.

**Comment by alexcrichton** [comment]
Oh dear sounds bad! FWIW the ignore file is [generated here](https://github.com/rust-lang/cargo/blob/58c7e7f50ed40aff96eb68085c43753820dae6bc/src/cargo/ops/cargo_new.rs#L387-L389) and looks like it doesn't have special cases for git/hg
