### ISSUE TITLE
How can I check for SSL errors?

### ISSUE THREAD

**Issue by ekicyou** [rust-lang/cargo#4009]
Cargo Install/Build now produces an SSL error. Is there a better way to investigate?

* Windows 10 pro / 64bit / ja-JP
* stable-x86_64-pc-windows-msvc unchanged - rustc 1.17.0 (56124baa9 2017-04-24)
* cargo 0.18.0 (fe7b0cdcf 2017-04-24)

command
```
set RUST_LOG=trace
cargo install racer --verbose
```

result
```
DEBUG:cargo::sources::config: loading: registry https://github.com/rust-lang/crates.io-index
TRACE:cargo::core::source: loading SourceId; registry https://github.com/rust-lang/crates.io-index
    Updating registry `https://github.com/rust-lang/crates.io-index`
DEBUG:cargo::sources::registry::remote: attempting github fast path for https://github.com/rust-lang/crates.io-index
DEBUG:cargo::sources::registry::remote: fast path failed, falling back to a git fetch
INFO:git2_curl: action upload-pack /info/refs?service=git-upload-pack
DEBUG:git2_curl: request to https://github.com/rust-lang/crates.io-index/info/refs?service=git-upload-pack
INFO:git2_curl: action upload-pack /git-upload-pack
DEBUG:git2_curl: request to https://github.com/rust-lang/crates.io-index/git-upload-pack
INFO:git2_curl: action upload-pack /git-upload-pack
DEBUG:git2_curl: request to https://github.com/rust-lang/crates.io-index/git-upload-pack
TRACE:cargo::sources::registry::remote: [registry https://github.com/rust-lang/crates.io-index] updating to rev 67ff9d7a6da6f3918a77fcee97c5f06d0c64fb20
 Downloading racer v2.0.6
INFO:cargo::util::job::imp: found 0 remaining processes
DEBUG:cargo: exit_with_error; err=CliError { error: Some(Error { description: "SSL connect error", code: 35, extra: Some("schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - �����T�[�o�[���I�t���C���̂��߁A�����̊\u{590}��͎������m�F�ł��܂���ł����B") }), unknown: true, exit_code: 101 }
error: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - �����T�[�o�[���I�t���C���̂��߁A�����̊֐��͎������m�F�ł��܂���ł����B)
```

Garbled characters, not enough information Because the SSL part cannot be confirmed by the packet monitor, I want the means to obtain additional information. Who is cargo to communicate with the error?

**Comment by alexcrichton** [comment]
Oh dear that looks bad! The error message is definitely getting garbled there rather than showing up naturally. It looks, though, like you're using a proxy? Is your proxy replacing the SSL certificate or are you otherwise perhaps not trusting the proxy's root ssl cert?

**Comment by ekicyou** [comment]
Thank you for your reply.
I am using a proxy, but it is not likely to be a fault by a proprietary certificate.

* Via authentication Proxy.
* Until April 28, it was working fine.
  I am having a problem from May 8.
* https://crates.io/ from IE looks normal.
  * Certificate path
    * DST ROOT CA X3
    * Let's Encrypt Authority X3
    * crates.io
* rustup works fine.
* Access to https://github.com/ using git command is normal.

I am checking in-house about the possibility of https://crates.io/ access restrictions.

**Comment by ekicyou** [comment]
It seems to have been stopped by Windows Firewall.
We have explicitly allowed Cargo.exe communication to work.

It may have been a security patch.
Let's look at the situation for a while.

**Comment by alexcrichton** [comment]
Ok thanks for the update! In that case I'll close for now.

**Comment by ekicyou** [comment]
Thank you for your support.

The phenomenon was reproduced again, but the revocation check of the certificate was turned off and corresponded.

```toml
[http]
check-revoke = false               # Indicates whether SSL certs are checked for revocation

```

**Comment by azriel91** [comment]
I just hit this today:

```
export RUST_LOG=trace
cargo build
```

Output:

```
... omitted a lot of TRACE logs ...
 Downloading unicode-segmentation v1.2.0
INFO:cargo::util::job::imp: found 0 remaining processes
DEBUG:cargo: exit_with_error; err=CliError { error: Some(ChainedError { error: unable to get packages from source, cause: Curl(Error { description: "SSL connect error", code: 35, extra: Some("schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ????????????????????????????????????") }) }), unknown: false, exit_code: 101 }
error: unable to get packages from source

Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - ????????????????????????????????????)
```

I'm on Windows 10 Home / x64, I'm not behind a proxy. My firewall isn't blocking `cargo.exe` (or at least, it's not listed in blocked apps).

I added the above `[http] check-revoke = false` section to my `Cargo.toml` but cargo said it's an unused key.

**Comment by alexcrichton** [comment]
Thanks for the report @azriel91, I wonder if that may have been connected with the [let's encrypt outage](https://letsencrypt.status.io/?170519)? Oh and to clarify the `check-revoke` business goes in `.cargo/config`, not the manifest itself.

The corrupted error message comes from libcurl itself, so I'm not sure what's going on there :(

**Comment by alexcrichton** [comment]
@azriel91 I've [filed an issue](https://github.com/rust-lang/cargo/issues/4074) about the corrupt error message.
