### ISSUE TITLE
Environment Variable Collisions when using build scripts

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/cargo#4011]
Cargo sets unnamespaced environment variables such as `DEBUG`. In my case, this breaks a third party library built as part of my build script. which uses this variable to determine whether to bootstrap a second, debug build. I'd strongly recommend that all the un-namespaced cargo variables are deprecated to prevent this sort of problem causing subtle bugs, and even potential security expolits. With the sheer quantity of environment variables cargo now passes, sanitizing a build environment to make builds reproducible is going to get progressively harder.

Background: I'm working on a FFI binding crate for NVML (aka pmem.io), a persistent memory library for DRAM, which needs a build script. NVML uses recursive `Makefile`s which uses the value of the environment variable `DEBUG` to communicate with each other as to whether it is doing a `DEBUG` build or not.

**Comment by alexcrichton** [comment]
Yeah makes sense to me! In retrospect these should've all been `CARGO_*` variables ...

**Comment by raphaelcohn** [comment]
Closing as far, far too late to change.
