### ISSUE TITLE
cargo publish doesn't take a --target

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/cargo#4012]
I'm writing a build script for NVML, a persistent memory library for DRAM. NVML only supports x86-64 linux currently, but I'm working on my Mac. I have no problem with building using this approach, as I use a local cross-compile toolchain via `--target`. However, I can't publish from this machine as `cargo publish` doesn't take a `--target`.

**Comment by alexcrichton** [comment]
Seems reasonable to me to add! In the meantime you can also just pass `--no-verify` to avoid compilation verification on publish

**Comment by nisargthakkar** [comment]
@alexcrichton Is anybody working on this? Can I pick it up? I believe it should not be too difficult of a task. I'm considerably new to Rust, hence, might be way off point. Please share your thoughts

**Comment by alexcrichton** [comment]
@nisargthakkar no I believe it's up for grabs, feel free to do so! You may want to take a look at how [`cargo build` works with `--target`](https://github.com/rust-lang/cargo/blob/master/src/bin/build.rs) and then you can likely adapt [`cargo publish`](https://github.com/rust-lang/cargo/blob/master/src/bin/publish.rs) to do something similar, likely threading through an option down to [verification](https://github.com/rust-lang/cargo/blob/3fa09c2f48911ae225e4112360b3ada08d6f7679/src/cargo/ops/cargo_package.rs#L292). Let me know if you need any help!

**Comment by nisargthakkar** [comment]
@alexcrichton Thanks for all the pointers. I'll try implementing this.

**Comment by carols10cents** [comment]
Looks like this was fixed in https://github.com/rust-lang/cargo/pull/4440, closing!
