### ISSUE TITLE
Only fetch the master branch of the registry index

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#4016]
Right now [Cargo clones all branches](https://github.com/rust-lang/cargo/blob/80f19a8e240577d90caf38503bb3034ac7dd630d/src/cargo/sources/registry/remote.rs#L98-L100) of the index today when it updates. There's only one branch so this isn't so bad but we may one day [add more branches](https://github.com/rust-lang/cargo/issues/1171#issuecomment-300310825).

Let's [update the refspec](https://github.com/rust-lang/cargo/issues/1171#issuecomment-300313179) we fetch and only fetch the master branch.

**Comment by alexcrichton** [comment]
I believe this should be easy enough to implement, so I'm going to tag as E-easy. If anyone would like any assistance though with this please let me know!

**Comment by alexcrichton** [comment]
I've got this implemented locally in a branch that also implements https://github.com/rust-lang/cargo/issues/4015

**Comment by rsertelon** [comment]
Oh, I was just pushing this for a PR ;)

**Comment by alexcrichton** [comment]
Oh sorry about that @rsertelon! If you want to send a PR though it may take me a bit to collect the data to justify the one I'm writing, no harm in having two!

**Comment by rsertelon** [comment]
Should I proceed or not? Given that this is not so much of a big change ^^ (t'was my first attempt at contributing to rust :))

**Comment by rsertelon** [comment]
ok, moving forward with my PR then!
