### ISSUE TITLE
Display the target directory in cargo metadata output

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#4017]

**Comment by alexcrichton** [comment]
cc @matklad

**Comment by matklad** [comment]
Should definitely do this! We even need it in IntelliJ Rust. I can implement this, but I don't have a ton of time right now. But it should be pretty strait forward to add: add `target_dir` to `ExportInfo` [here](https://github.com/rust-lang/cargo/blob/80f19a8e240577d90caf38503bb3034ac7dd630d/src/cargo/ops/cargo_output_metadata.rs#L59) and populate it from `ws.target_dir()`.

**Comment by sfackler** [comment]
Done!
