### ISSUE TITLE
Rewrite Cargo.toml on publication to crates.io

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#4027]
Right now when Cargo publishes a crate to crates.io it doesn't modify the manifest at all. This in turn means that literally checking out the manifest on crates.io and attempting to build it may fail! Notably:

* `path` dependencies are listed, likely to nonexistent paths
* The `[workspace]` key may be listed, pointing to a nonexistent path

This has long been ok in Cargo as it reinterprets dependencies internally, but many situations have arisen over time which make this just too difficult to work with:

* When you've got a bunch of vendored sources lying nearby you may wish to edit them, and the most natural way to do that is to `[replace]` point at them, but the previously mentioned points can prevent this from working.
* Cargobomb/crater test crates.io crates and [frob the tomls](https://github.com/brson/cargobomb/blob/master/src/toml_frobber.rs) to get them to work.
* Packagers have asked in the past for a way to deal with this if they're packaging published code to crates.io.

**Comment by alexcrichton** [comment]
cc @brson

**Comment by cuviper** [comment]
/sub

I had thought that the way to solve this would be to just have a command-line option which *ignores* the parts that you're proposing to strip here.  So you still wouldn't be able to do a bare `cargo build`, but you might be able to use `cargo build --paint-my-bikeshed` to ignore path-deps, workspaces, etc.

**Comment by alexcrichton** [comment]
@cuviper I think that'd work in some situations, yeah, but it's not necessarily composable. The primary use case driving this, for example, is for projects like Gecko to use `[replace]` pointing at the vendored source code that they already have in the repository, editing it afterwards. In that sense there's no commands being executed in the directory, but rather just a typical `path` dependency.

I suppose we could add a feature like:

```toml
[dependencies]
foo = { path = 'vendor/foo', special-dep = true }
```

Although that'd be kinda unfortunate. My thinking is that in *theory* rewriting the manifest will work, it's just that in practice we're probably messing something up unfortunately.

**Comment by cuviper** [comment]
Maybe you could just use a file in the crate root to indicate special handling?  e.g. cargo-vendor already adds `.cargo-ok` and `.cargo-checksum.json`, so you could change behavior based on those.

**Comment by alexcrichton** [comment]
It's possible, yeah. Similar to some of the discussion on https://github.com/rust-lang/cargo/pull/4030. The [downside](https://github.com/rust-lang/cargo/pull/4030#issuecomment-301127225) though is that any out-of-band marker is a stable interface to Cargo, wheras simply rewriting Cargo.toml doesn't expose any new stable API surface area in Cargo.

There's also the point in that linked comment about "what do paths default to?" Today it's crates.io but one could imagine that with a future implementation it may be different registry, perhaps context dependent on where you publish to (in which case a rewrite could come in handy). This out of band file could also contain the information, though.
