### ISSUE TITLE
Could not find `Cargo.toml or any parent directory

### ISSUE THREAD

**Issue by dotnetspec** [rust-lang/cargo#4034]
Hi,

I'm in the process of installing Parity on Win 10 32 bit machine.

I follow download and follow instructions from here:

https://parity.io/parity.html

git clone https://github.com/paritytech/parity.git && cd parity

cargo run --release

and get error:

could not find `Cargo.toml` in `C:\Program Files\Ethcore\Parity` or any parent directory

all the cargo.toml files are in sub directories. 

Why is cargo looking in parent directories?

How to fix?

**Comment by alexcrichton** [comment]
Thanks for the report! Are you sure you're cd'ing into the parity directory? The [repository](https://github.com/paritytech/parity) has a top-level [Cargo.toml](https://github.com/paritytech/parity/blob/master/Cargo.toml), so in theory this would work

**Comment by tregismoreira** [comment]
Hey, I got the same error. But I realized that the installation instructions in [Pariti's hub](https://hub.docker.com/r/ethcore/parity/) isn't accurate. The commands in the section _Build from source_ doesn't clone the repository.

```
# download Parity code
$ git clone https://github.com/ethcore/parity
$ cd parity
```

If you go to https://github.com/ethcore/parity you will see the following message:

```
Moved to https://github.com/paritytech/parity
```

Then you should run the following command to clone the project:

```
$ git clone https://github.com/paritytech/parity.git
```

It worked for me.

**Comment by alexcrichton** [comment]
Ah that'd do it, thanks for the comment @tregismoreira!

**Comment by achillegley** [comment]
I got the same issue and i fix it by finding the path of Cargo.toml  " .cargo\registry\src\github.com-1ecc6299db9ec823\cargo_toml-0.11.6 " in my case... so i just run "cargo check" or "cargo update" or "cargo add library" from terminal from this path..... may be i should add specific environnement PATH to avoid reffering all time to this path..
