### ISSUE TITLE
Should document CARGO_CFG_* environment variables

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#4041]
Cargo exports these extremely useful variables but they aren’t documented in http://doc.crates.io/environment-variables.html.

(I also wrote a [blog post](https://kazlauskas.me/entries/writing-proper-buildrs-scripts.html) on them, if anybody needs some use-cases for them)

**Comment by retep998** [comment]
`rustc --print cfg`

**Comment by alexcrichton** [comment]
Original docs for this are at: https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md#lowering-cfg-values-to-cargo-build-script-environment-variables
