### ISSUE TITLE
Only warn about adding `.cargo/bin` if its not already in $PATH

### ISSUE THREAD

**Issue by avindra** [rust-lang/cargo#4042]
E.g., I see:

```
warning: be sure to add `/home/user/.cargo/bin` to your PATH to be able to run the installed binaries
```

It should be fairly trivial to check if the `bin` folder exists in `$PATH` and suppressing that warning in that case.

**Comment by alexcrichton** [comment]
We should [already be doing this](https://github.com/rust-lang/cargo/blob/3fa09c2f48911ae225e4112360b3ada08d6f7679/src/cargo/ops/cargo_install.rs#L250-L261), but do you think there's a bug there?

**Comment by avindra** [comment]
Ah good call. I guess the issue is that my  `$PATH` uses `~/.cargo/bin`, which isn't recognized because cargo is looking for `/home/user` instead of just `~`.

Not sure what the best approach to support both would be...

**Comment by alexcrichton** [comment]
In general shells are the one responsible for expanding `~`, most tools don't know what `~` is and won't work correctly if that's what's in `PATH`

**Comment by carols10cents** [comment]
It sounds like we can't fix this issue, so I'm closing. Please reopen if I'm mistaken! Thanks!!
