### ISSUE TITLE
provide a richer set of target/host environment variables to build scripts

### ISSUE THREAD

**Issue by froydnj** [rust-lang/cargo#4052]
Cargo currently provides `TARGET` and `HOST` environment variables denoting the LLVM target triples for the target and host, respectively.  If you have build scripts that care a lot about the peculiarities of the target and/or host, such as Servo's script for running bindgen, then that means parsing the triple and then dealing with peculiarities of triples: number of parts, architecture canonicalization, etc.  This would be a lot of code that would have to be repeated across various build scripts.

It would be ideal if Cargo provided `TARGET_ARCH`, `TARGET_OS`, `TARGET_CPU`, etc. values (and their `HOST_*` equivalents, similar to the `target_*` variables available to `cfg!`.

**Comment by alexcrichton** [comment]
You're in luck! Cargo actually already does this, but it's [unfortunately not documented](https://github.com/rust-lang/cargo/issues/4041).

You can read more about the design in the [original RFC](https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md#lowering-cfg-values-to-cargo-build-script-environment-variables)

**Comment by froydnj** [comment]
Perfect, thank you! 👍
