### ISSUE TITLE
Allow other languages to be used for build scripts.

### ISSUE THREAD

**Issue by treyzania** [rust-lang/cargo#4063]
I'm sorry if this has been asked before, I did some searching and didn't see anything similar to this mentioned.

Anyways, I think that it might be useful to include support for using certain other languages like Python in `build.rs` (or `build.py`).  Using Rust for it is great but for something straightforward like this it feels like a little overkill, plus we wouldn't have to compile it beforehand and could execute the code directly.  The downside I can see is that users would need to have interpreters installed on their systems already or embed portable versions of it.  (In the case of Lua this might not be an issue as it's so easy to embed already.)

For Python, we could also amend `$PYTHONPATH` to directly make available libraries that would do the equivalent of the [gcc crate](https://docs.rs/gcc/0.3.46/gcc/) but in Python.

**Comment by alexcrichton** [comment]
Thanks for the report! The intention of using Rust however includes a few factors:

* We're guaranteed to have a rustc compiler on the system
* We can add dependencies via `[build-dependencies]`

The thinking is that if you'd like to write a build script in not-Rust that's totally ok! You'd just write a small script that shells out to something like `make` or Python. It'd then be up to you to modify things like `PYTHONPATH` and such.
