### ISSUE TITLE
`cargo test` requires an order of magnitude more memory to link

### ISSUE THREAD

**Issue by JustAPerson** [rust-lang/cargo#4067]
I'm working on a private repository and hit some weird behavior. 

`cargo build` uses about 2GB mem usage and finishes fine.
`cargo test` uses about 14GB before swap thrashing occurs so badly as to halt all progress.

I don't have time to minimize a test case today, maybe sometime next week, but I was curious how to proceed here attempting to diagnose the root cause.

**Comment by alexcrichton** [comment]
Thanks for the report! I think the bug here may be with rust-lang/rust, though, and not Cargo? (Cargo just calls the compiler). It'd be useful though to learn what process is running out of memory here, if it's something like `ld` then there may not be much we can do about it :(
