### ISSUE TITLE
Document CARGO_CFG_* enviromnent variable

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#4068]
https://github.com/rust-lang/cargo/pull/3243 added them. https://kazlauskas.me/entries/writing-proper-buildrs-scripts.html points out (that they exist! and) that they’re not documented on http://doc.crates.io/environment-variables.html

**Comment by alexcrichton** [comment]
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/4041, so closing in favor of that issue.
