### ISSUE TITLE
Installation manifest doesn't respect prefix for `bash_completion.d/cargo`

### ISSUE THREAD

**Issue by rillian** [rust-lang/cargo#4070]
Running the install script for the cargo package from [channel-rust-nightly.toml](https://static.rust-lang.org/dist/channel-rust-nightly.toml) I get an error:
```
install: creating uninstall script at /home/giles/firefox/taskcluster/docker/rust-build/rustc/lib/rustlib/uninstall.sh
install: installing component 'cargo'
install: cannot create regular file '/etc/bash_completion.d/cargo': Permission denied
```
It seems like installer isn't respecting the `--prefix` for the bash_completion file.

**Comment by rillian** [comment]
`sysconfdir` defaults to `/etc` without prepending the prefix. I'm not sure if that's helpful or not, but I suppose I can work around with DESTDIR or --sysconfigdir=$prefix/etc

**Comment by alexcrichton** [comment]
cc @Keruspe, I think this changed recently in rust-lang/rust, right?

**Comment by Keruspe** [comment]
It changed in rust-installer indeed. Previously it would be unconditionally installed in `$prefix/etc` and it's now installed in `$sysconfdir`.
I hesitated between `/etc` and `$prefix/etc` for the default value and I actually followed what is done by rust configure script: https://github.com/rust-lang/rust/blob/master/configure#L469
Passing `--sysconfdir` would indeed fix your issue.

**Comment by Keruspe** [comment]
See https://github.com/rust-lang/rust-installer/pull/64
