### ISSUE TITLE
Submodules not updated

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/cargo#4071]
So while updating rustc, running ./x.py was failing. I solved this by cd-ing into the cargo checkout and running `git submodule update`, but this should obviously not be necessary. I'm uncertain how or why this happened... I can attempt to provide more than the below if necessary, but hoping that someone knows what's wrong.

```
INFO:cargo::sources::git::utils: update submodules for: "/home/mark/.cargo/git/checkouts/cargo-e7ff1db891893a9e/2b32084/"
error: failed to load source for a dependency on `cargo`

Caused by:
  Unable to update https://github.com/rust-lang/cargo#2b320842

Caused by:
  failed to update submodule `src/rust-installer`

To learn more, run the command again with --verbose.
```

**Comment by alexcrichton** [comment]
Is this reproducible? If so, try to catch me on IRC I'd love to live debug this.

**Comment by Mark-Simulacrum** [comment]
Yeah, I can reproduce reliably (worked 10 times so far) by just deleting the cargo git checkout in `~/.cargo/git/checkouts` reliably. I'll ping you on IRC later.

**Comment by Mark-Simulacrum** [comment]
Discussed on IRC. I had to reboot the machine which this happened on, and after that this mostly went away, so ... closing.

**Comment by nicodemus26** [comment]
@alexcrichton, this is still a problem as of `cargo 0.23.0 (61fa02415 2017-11-22)`, I have a build that was getting stuck on libz-sys's submodules.

As a workaround, this bash command performs a recursive submodule update on all of cargo's checkouts:
```
for REPO in ~/.cargo/git/checkouts/*/*; do pushd $REPO; git submodule update --init --recursive; popd; done
```

**Comment by nicodemus26** [comment]
It looks like it wasn't your version of zlib-sys, but @BusyJay's. This commit makes src/zlib a submodule: https://github.com/BusyJay/libz-sys/commit/2d69a4e44ed86499d01976356f761d3eaeec45b6#diff-8903239df476d7401cf9e76af0252622

I got this version of zlib-sys as a transitive dependency of rocksdb ala:
```
rocksdb v0.3.0 (https://github.com/pingcap/rust-rocksdb.git?rev=5753b96#5753b968)
├── librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git?rev=5753b96#5753b968)
│   ├── libz-sys v1.0.18 (https://github.com/busyjay/libz-sys.git?branch=static-link#bb77b618)
│   │   └── libc v0.2.33 (*)```

**Comment by alexcrichton** [comment]
Oh dear! @nicodemus26 do you have a way I could reproduce this locally?

**Comment by nicodemus26** [comment]
Unfortunately even with some git timetraveling I can't recreate the broken state. The recursive submodule update of all cargo checkouts fixed the issue in some stateful way.

**Comment by alexcrichton** [comment]
Ok thanks!

**Comment by BusyJay** [comment]
Actually I can reproduce it on my machine. Because I'm behind GFW, everytime when I try to add https://github.com/pingcap/grpc-rs.git as a dependency, it will fails the first time with error message:
```
% cargo build --verbose                                 
error: failed to load source for a dependency on `grpcio`

Caused by:
  Unable to update https://github.com/pingcap/grpc-rs.git#d5063d5b

Caused by:
  failed to update submodule `grpc-sys/grpc`

Caused by:
  failed to update submodule `third_party/boringssl-with-bazel`

Caused by:
  [12/-1] curl error: Failed to connect to boringssl.googlesource.com port 443: Connection timed out
```

And the second time, it will not try to initial the submodule anymore, and fails immediately due to lack of submodule in build.rs.
```
% cargo build --verbose                                                                                                                  :(
       Fresh pkg-config v0.3.9
       Fresh log v0.3.8
       Fresh libc v0.2.34
       Fresh cc v1.0.3
   Compiling protobuf v1.4.3
       Fresh futures v0.1.17
       Fresh cmake v0.1.29
     Running `rustc --crate-name protobuf /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-1.4.3/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=555ad4088b5801da -C extra-filename=-555ad4088b5801da --out-dir /tmp/test-sub/target/debug/deps -L dependency=/tmp/test-sub/target/debug/deps --cap-lints allow`
   Compiling grpcio-sys v0.1.2 (https://github.com/pingcap/grpc-rs#d5063d5b)
     Running `/tmp/test-sub/target/debug/build/grpcio-sys-f30718a8063642fe/build-script-build`
error: failed to run custom build command for `grpcio-sys v0.1.2 (https://github.com/pingcap/grpc-rs#d5063d5b)`
process didn't exit successfully: `/tmp/test-sub/target/debug/build/grpcio-sys-f30718a8063642fe/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG

--- stderr
thread 'main' panicked at 'Can't find module grpc/third_party/zlib. You need to run `git submodule update --init --recursive` first to build the project.', /home/jay/.cargo/git/checkouts/grpc-rs-d2d7508a79dd0c2c/d5063d5/grpc-sys/build.rs:50:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```
Cargo version:
```
% cargo --version                                                                                                                        :(
cargo 0.23.0 (61fa02415 2017-11-22)
```

**Comment by alexcrichton** [comment]
@BusyJay awesome thanks! That's definitely a bug and should be fixed by https://github.com/rust-lang/cargo/pull/4837

**Comment by CPerezz** [comment]
Idk if the status of this is updated, but It happened to me also when using a git dependency to use a testing branch of `kelvin` repo.
```
error: failed to get `kelvin` as a dependency of package `poseidon252 v0.2.0 (/home/path../Poseidon252)`

Caused by:
  failed to load source for dependency `kelvin`

Caused by:
  Unable to update https://github.com/dusk-network/kelvin?branch=merkle_proofs

Caused by:
  failed to update submodule `examples/kelvin-web/www`

Caused by:
  no URL configured for submodule 'examples/kelvin-web/www'; class=Submodule (17)

```

If it's interesting, I can branch it out so it can be debugged or if it helps.

**Comment by ehuss** [comment]
@CPerezz  The path `examples/kelvin-web/www` in that repo is a gitlink, but there is no `.gitmodules` file to provide the mapping. Either the path needs to be removed, or add a `.gitmodules` providing the mapping.

Also, it's best to file a new issue instead of commenting on one closed years ago. Your issue looks unrelated to the original.
