### ISSUE TITLE
cargo cannot download packages from crates.io on Windows 32 bit

### ISSUE THREAD

**Issue by alexbool** [rust-lang/cargo#4072]
![cargo-failure](https://cloud.githubusercontent.com/assets/1283792/26248169/deb8d424-3ca9-11e7-98ff-98e90ee57184.png)

**Comment by alexbool** [comment]
Somehow it fixed itself. Maybe it was a server infrastructure issue.
By the way, printing error messages is far from ideal (I have russian localized Windows).

**Comment by alexcrichton** [comment]
I think this may have actually been related to the let's encrypt outage? https://letsencrypt.status.io/?170519

I saw a similar error (I think) here - https://ci.appveyor.com/project/alexcrichton/backtrace-rs/build/1.0.541/job/qyxkso0m02qhnne9

The corrupted message being printed out may be a different bug though? (similar to https://github.com/rust-lang/cargo/issues/4009#issuecomment-302623312)

**Comment by alexcrichton** [comment]
I've filed an issue about the corrupted error message (https://github.com/rust-lang/cargo/issues/4074) so I'm going to close this for now, thanks for the report though! Note that if this happens again you may be able to get it working again by [disabling revocation](https://github.com/rust-lang/cargo/issues/4009#issuecomment-302284004) via `.cargo/config`.

**Comment by Viv-Rajkumar** [comment]
@alexcrichton looks like we're also hitting this issue from appveyor builds for the last few hours: https://ci.appveyor.com/project/MaidSafe-QA/safe-client-libs/build/1.0.203/job/kst7jamqaqm69k0x

**Comment by alexcrichton** [comment]
@Viv-Rajkumar is it still happening? The Let's Encrypt status at least says they're back online, so it *may* be fixed now

**Comment by Viv-Rajkumar** [comment]
@alexcrichton yeh looks like it is still happening. https://ci.appveyor.com/project/MaidSafe-QA/maidsafe-utilities/build/1.0.310/job/ery1h4web8y2u222 just hit the error seconds ago

**Comment by alexcrichton** [comment]
@Viv-Rajkumar ah ok :( 

Want to try out the `check-revoke = false` mentioned above?

**Comment by Viv-Rajkumar** [comment]
@alexcrichton sure @Fraser999 is just trying that. although not a great solution for CI. not having the issue from local machines though

**Comment by alexcrichton** [comment]
Yeah unfortunately other than that it looks like this is either a bug in schannel or something we don't have a lot of control over :(

**Comment by Fraser999** [comment]
The `check-revoke = false` workaround does indeed work.

**Comment by est31** [comment]
cc https://github.com/rust-lang/crates.io/issues/733
