### ISSUE TITLE
Cargo needlessly(?) rebuilds dependencies

### ISSUE THREAD

**Issue by NfNitLoop** [rust-lang/cargo#4076]
Cargo seems to be having a problem with a few of my dependencies (`error-chain`, and its dependencies, `backtrace` and `cpp_demangle`). Every time I run `cargo build` or run, it rebuilds them. 

~~~
$ cat Cargo.toml 
[package]
name = "sample_project"
version = "0.1.0"

[dependencies]
error-chain = "*"

$ cat src/main.rs 

fn main() {
    println!("Hello, world!");
}

$ cargo build
   Compiling cpp_demangle v0.2.1
   Compiling backtrace v0.3.1
   Compiling error-chain v0.10.0
   Compiling sample_project v0.1.0 (file:///Users/codyc/programs/rust/sample_project)
    Finished dev [unoptimized + debuginfo] target(s) in 6.68 secs

$ cargo build # Everything *should* be cached?
   Compiling cpp_demangle v0.2.1
   Compiling backtrace v0.3.1
   Compiling error-chain v0.10.0
   Compiling sample_project v0.1.0 (file:///Users/codyc/programs/rust/sample_project)
    Finished dev [unoptimized + debuginfo] target(s) in 6.61 secs
~~~

Hmm... I'm just realizing that if these the only libraries that that's happening for, it might be an issue with one of those libraries in particular, and not Cargo? I don't know enough about the cargo build process to know how to track that down, though.

**Comment by crumblingstatue** [comment]
If I comment out `println!("cargo:rerun-if-changed=in/*");` in cpp_demangle, it doesn't rebuild every time anymore.

1. Are globs valid in this context?
2. If they aren't, shouldn't cargo throw an error instead of behaving weirdly like this?

**Comment by crumblingstatue** [comment]
Here is a test case for cargo always rerunning on a non-existent rerun dependency:

Cargo.toml:
```toml

[package]
name = "foo"
build = "build.rs"
version = "0.0.1"
```

build.rs:
```rust
fn main() {
	println!("cargo:rerun-if-changed=idontexist");
}

```

main.rs:

```rust
fn main() {}

```

**Comment by alexcrichton** [comment]
Ah yeah I believe that this basically boils down to https://github.com/fitzgen/cpp_demangle/issues/79 in the sense that it's not a bug in Carog, but rather a bug in the build script in question.

**Comment by crumblingstatue** [comment]
> Ah yeah I believe that this basically boils down to fitzgen/cpp_demangle#79 in the sense that it's not a bug in Carog, but rather a bug in the build script in question.

Just to make sure: You're saying it's acceptable behavior that Cargo always reruns rerun-if-changed targets that don't exist.

**Comment by NfNitLoop** [comment]
@crumblingstatue That makes sense to me. (ex: If a file used to exist, and was deleted, it makes sense to redo the build. Maybe the build creates it?)

It's also unfortunate that `*` can be a valid character in a file name (if you're a masochist) so you can't unambiguously detect someone trying to use a glob and tell them that it's an error.

Maybe `cargo check` could have an extra check added to make sure that your build is cacheable? That's a separate issue/feature-request though, let's not go down that road here.  😄 

Thanks for finding and linking the root cause, Alex!

**Comment by crumblingstatue** [comment]
@NfNitLoop Got it, thanks!

**Comment by alexcrichton** [comment]
@inferiorhumanorgans true, but the quotes can be omitted?

**Comment by inferiorhumanorgans** [comment]
@alexcrichton Well, yes.  But that's not intuitive behavior.
