### ISSUE TITLE
Add 'alternatives' metadata to Cargo.toml

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/cargo#4078]
When searching for a crate to use the first one that you find isn't necessarily exactly what you're looking for. For example, I came across the 'text_io' crate but was looking for something similar that did not panic.

Listing 'alternatives' is also a sign of a high quality crate as it suggests the author is aware of the other crates that might do similar things and understands how their crate fits in the existing ecosystem. Having the 'alternatives' metadata will also help with search results ordering as it can act similar to citations/page rank style metric.

**Comment by carols10cents** [comment]
I don't think it's the responsibility of a crate to know about/recommend/advertise alternative crates; this would be better for, say, blog posts to do surveys of the crates for a particular task and how they differ.

Thank you for the suggestion though!
