### ISSUE TITLE
Document environment variables in cargo help

### ISSUE THREAD

**Issue by devurandom** [rust-lang/cargo#4079]
According to the [Cargo docs on crates.io](http://doc.crates.io/environment-variables.html), `cargo build` will be influenced by e.g. `CARGO_TARGET_DIR`, but `cargo help` does not document this.

Furthermore, the [Cargo guide](http://doc.crates.io/guide.html) does not link to the [documentation of the environment variables](http://doc.crates.io/environment-variables.html), which makes this feature rather hard to find.

**Comment by dwijnand** [comment]
Well the later half is no longer true. The Cargo guide now presents a sidebar TOC where the documentation for the environment variable is reachable.

**Comment by ehuss** [comment]
The documentation has been updated along the way to include more hints about environment variables.  The `--target` flag at https://doc.rust-lang.org/cargo/commands/cargo-build.html mentions it. The [`cargo-build`](https://doc.rust-lang.org/cargo/commands/cargo-build.html) man page also has an Environment section which links to the reference.  Embedding more detailed help in the built-in `help` output is tracked in #6104, so I'm going to close in favor of that for future improvements.
