### ISSUE TITLE
`cargo update` hangs forever on stdx, using explicit equality dependencies

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#4080]
```
$ git log -1
commit ec0b42a49b282be602afd6b7b4e9c2d3c96ed6a4
Merge: 3acd06c f8204b6
Author: Brian Anderson <andersrb@gmail.com>
Date:   Sat Apr 8 15:57:02 2017 -0700

    Merge pull request #25 from dtolnay/serde9

    Update chrono, ndarray, reqwest, toml to serde 0.9 versions

brian@DESKTOP-CODN6ST MINGW64 /c/Users/brian/Documents/dev/stdx
$ rustc -Vv
rustc 1.16.0 (30cf806ef 2017-03-10)
binary: rustc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: x86_64-pc-windows-msvc
release: 1.16.0
LLVM version: 3.9
```

When I run `cargo update` on stdx, it hangs forever at "Updating registry". stdx uses "=" for all it's dependencies, and when I remove the "=" it no longer hangs.

**Comment by brson** [comment]
I have to imagine this graph has somehow become unresolvable per cargo's algorithm, though it used to resolve.

**Comment by alexcrichton** [comment]
Ah this is actually an instance of https://github.com/rust-lang/cargo/issues/4066. The crate graph at brson/stdx@ec0b42a49b282be602afd6b7b4e9c2d3c96ed6a4 is actually un-resolvable.

cpp_demangle (required for backtrace required through error-chain) requires clap 2.24.2 whereas stdx requires =2.20.1, which means it's impossible for Cargo to select a correct version constraint here. In that case Cargo's just doing a terrible job of telling you that it's an unresolvable graph!
