### ISSUE TITLE
cargo publish fails with "ValueAfterTable" error

### ISSUE THREAD

**Issue by steffengy** [rust-lang/cargo#4081]
Cargo version: `cargo 0.20.0-nightly (397359840 2017-05-18)`

When trying to `cargo publish` [tiberius](http://github.com/steffengy/tiberius) I get the following:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', 
src\libcore\result.rs:859
stack backtrace:
   0: git_note_author
   1: git_note_author
   2: git_note_author
   3: git_note_author
   4: git_note_author
   5: git_note_author
   6: git_note_author
   7: git_note_author
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: git_note_author
  17: git_note_author
  18: git_openssl_set_locking
  19: BaseThreadInitThunk
```

Anyone having any clue what's going on there?

**Comment by alexcrichton** [comment]
Thanks for the report! This is likely related to https://github.com/rust-lang/cargo/pull/4030, and you can fix this for now by publishing on an older version of Cargo. I'll look into a fix though soon.
