### ISSUE TITLE
feature request: get app/package version from a Rust source file

### ISSUE THREAD

**Issue by aerickson** [rust-lang/cargo#4082]
CLI apps often provide a --version flag. It would be sweet if Cargo could get it out of a Rust file.

Ruby's Gemspec is able to do this (it's possible to just reference a variable in any included file), but I guess Gemspecs are pure ruby not a configuration language.

**Comment by alexcrichton** [comment]
Cargo sets a [few env vars](http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-crates) for crate compilation, is that what you're thinking or perhaps some other version here?

**Comment by aerickson** [comment]
That seems to provide the version when compiling, but an application needs it during runtime.

**Comment by Mark-Simulacrum** [comment]
I believe what you want is something like `cargo get-version foo.{o,rlib, ... ?}` and get the version of the Rust compiler that compiled that crate. This should be possible, but should probably be in rustc -- cargo doesn't really know about our metadata format AFAIK.

**Comment by aerickson** [comment]
Hm, but I want the app's version (not the Rust compiler version).

As an example, in this project the Cargo.toml has a the version string "0.1.0". src/cli.rs has the same string. 

https://github.com/TomasTomecek/pretty-git-prompt/blob/master/Cargo.toml
https://github.com/TomasTomecek/pretty-git-prompt/blob/master/src/cli.rs

**Comment by alexcrichton** [comment]
@aerickson when compiling that crate though `CARGO_PKG_VERSION ` will be set to `0.1.0`, so you can replace [this line](https://github.com/TomasTomecek/pretty-git-prompt/blob/089813c9cfb429feef23f79e476b89a9cc60472d/src/cli.rs#L10) with `env!("CARGO_PKG_VERSION")`

**Comment by Mark-Simulacrum** [comment]
If I recall correctly, clap can actually automatically do this for you, though I don't recall the exact methods to call to do so.

**Comment by TomasTomecek** [comment]
@Mark-Simulacrum you are correct, here's the macro: https://docs.rs/clap/2.24.2/clap/macro.crate_version.html

Thank you all for help.

**Comment by alexcrichton** [comment]
Ok sounds like we're good!

**Comment by vassilevsky** [comment]
Hello :) Could you tell how CARGO_PKG_VERSION can be read from shell? My vague understanding is that I can make Cargo run some shell script and this variable will be available from that script. But how do I do it? Sorry, I'm new to Rust :)

**Comment by philgebhardt** [comment]
> Hello :) Could you tell how CARGO_PKG_VERSION can be read from shell?
@vassilevsky I just found that this can be done with a little bit of string manipulation with `cargo pkgid`

```bash
cargo pkgid | cut -d# -f2 | cut -d: -f2
```
