### ISSUE TITLE
 cargo build --release

### ISSUE THREAD

**Issue by bsed** [rust-lang/cargo#4083]
/crossbeam-0.1.6/src/sync/seg_queue.rs:34:29
   |
34 |             ready: unsafe { mem::transmute([0usize; SEG_SIZE]) },
   |                             ^^^^^^^^^^^^^^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `crossbeam`.

To learn more, run the command again with --verbose.

**Comment by alexcrichton** [comment]
Thanks for the report! This issue is... a bit cryptic though? Do you have more information about what's going on here?

**Comment by matklad** [comment]
@bsed looks like your are using a very outdated version of the crossbeam crate, which sadly does not work with current Rust any more :( 

It could have been pulled by one of your dependencies, and you might need to update those. One notable crate which depends on old crossbeam and does not work any more is simple_parallel. If your project depends on simple_parallel, consider switching to the [rayon](https://github.com/nikomatsakis/rayon) crate! :)

**Comment by bsed** [comment]
I have user `rustup update nighty`  updated to the new version  ,and set rustup update defauly in  ubuntu17.10 . thank you.
