### ISSUE TITLE
Infer multi-file binaries like `src/bin/server/main.rs` by convention

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4086]
Currently `cargo` infers binaries from files in `src/bin`. This works if you binary fits in one file, but if you need more than one file, you have to write custom `[[bin]]` specification in Cargo.toml.

Looks like a reasonable convention for multifile binary projects is this:

```
src/
  bin/
    server/
        main.rs
        aux.rs
    client/
        main.rs
        foo.rs
```

So let's infer `src/bin/foo/main.rs` as a binary named `foo`?

This should be mostly backwards compatible change. The only failure case is when someone has `src/bin/foo/main.rs` which is not a binary, and no `[[bin]]` sections are present, and this seems unlikely. 

A potential edge case is

```
src/
  bin/
    foo.rs
    foo/
      main.rs
```

This should be an error.

**Comment by alexcrichton** [comment]
Sounds great to me!

**Comment by matklad** [comment]
If anyone wants to fix it, the place to look at is this line https://github.com/rust-lang/cargo/blob/263548d9781efb17b72de601665a7cf0ca472ba1/src/cargo/util/toml.rs#L54
and this function https://github.com/rust-lang/cargo/blob/263548d9781efb17b72de601665a7cf0ca472ba1/src/cargo/util/toml.rs#L503. 

The tests should probably go into this file: https://github.com/rust-lang/cargo/blob/master/tests/build.rs

**Comment by msehnout** [comment]
Is anybody working on this?

**Comment by alexcrichton** [comment]
@msehnout not that I know of, feel free to take it!

**Comment by crumblingstatue** [comment]
#4214 enabled this for src/bin, but how about also enabling this pattern for examples (and maybe integration tests)?

**Comment by matklad** [comment]
@crumblingstatue that sounds plausible! Right now I am refactoring the implementation of this stuff in https://github.com/rust-lang/cargo/pull/4259 though, so, if you'd like to send a PR, it's better to wait for a while :)

**Comment by rwakulszowa** [comment]
Hi @matklad, I think I could try to work on this one. The PR you mentioned is merged already. Is there anything I should be aware of before I start?

**Comment by matklad** [comment]
Awesome @rwakulszowa ! I think toml/targets.rs is the only file that should me modified, besides the test.

**Comment by rwakulszowa** [comment]
Hey, I have a few questions
- the discussion here mentions tests and examples. What about banchmarks?
- is there a nice way to test for existence of test binaries? Examples end up in the `examples` folder, but tests only produce artifacts in the main folder, decorated with hashes; is there a way to pass a regex / prefix string to the `assert_that(..., existing_file())`?

**Comment by matklad** [comment]
>the discussion here mentions tests and examples. What about banchmarks?

Yeah, the benchmarks could use the same logic

>is there a nice way to test for existence of test binaries?

I would probably check that `cargo test --test foo` works.

**Comment by sunjay** [comment]
Did support for examples with a main.rs file get added as part of this or should that be a separate issue?

**Comment by rwakulszowa** [comment]
Yes - examples, benches and tests follow the same logic and allow
multi-file directories, as long as they contain a main.rs file.

Did you encounter a problem with that?

19.11.2017 17:01 "Sunjay Varma" <notifications@github.com> napisał(a):

**Comment by sunjay** [comment]
@rwakulszowa Yes, it didn't work. Here's a minimal example:

From the base project created by `cargo new --lib <project name>`, I added a file `examples/dir/main.rs` and a file `examples/foo.rs`.
```
.
├── Cargo.lock
├── Cargo.toml
├── examples
│   ├── dir
│   │   └── main.rs
│   └── foo.rs
└── src
    └── lib.rs
```

Both files contain the simple hello world program. When I try to run them, this is what happens:
```
$ cargo run --example dir
error: no example target named `dir`

Did you mean `foo`?
```
```
$ cargo run --example foo
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/foo`
Hello, world!
```

The flat file worked, but nesting a file within a directory and having a file called "main.rs" did not work.

**Comment by rwakulszowa** [comment]
Are you sure you are using a recent cargo build? This change got merged in
September, but I'm not sure which cargo release contains it ( @matklad ?)

I have limited network access at the moment, so I'll check the official
release tomorrow, but I tested the feature locally and it works fine.

Maybe the feature didn't make it to the official release yet, or some other
changes modified the behavior. I'll take a look.

19.11.2017 19:42 "Sunjay Varma" <notifications@github.com> napisał(a):

**Comment by sunjay** [comment]
> Maybe the feature didn't make it to the official release yet, or some other
changes modified the behavior. I'll take a look.

Yes it seems so. I tried running it with `cargo +nightly run --example dir` and it worked. Looks like this will probably be out in Rust 1.22 :smile:

**Comment by rwakulszowa** [comment]
Alright!

19.11.2017 20:45 "Sunjay Varma" <notifications@github.com> napisał(a):
