### ISSUE TITLE
Command to update Cargo.lock to minimal versions

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4100]
From today's meeting.

Problem:

You write a library A, which depends on B, so you put `B = 1.0` in A's Cargo.toml. The you run Cargo build, and Cargo greedily pulls B 1.1 into the lockfile. Then you accidentally start depending on features introduced in 1.1, but you don't change `Cargo.toml`. Your test locally pass, and CI passes as well, and you publish a crate whose Cargo.toml is a lie. 

Solution:

Add `cargo update --minimal`, which generates lockfile picking the minimum possible version of all crates (it's not possible, of course, because there's no total order on dependency graphs, but some heuristics might work well in practice). Then in CI environment you generate the minimal lockfile to make sure you don't accidentally depend on newer than Cargo.toml features.

**Comment by matklad** [comment]
Note that we can envision some kind of mechanical solution here, for example, by tagging library functionality with #since attribute. However, actually testing things is still needed, because you may depend on a critical bugfix from the dependency.

**Comment by carols10cents** [comment]
Related: https://github.com/rust-lang/rfcs/blob/master/text/1977-public-private-dependencies.md#changes-to-cargo-publish-lowest-version-resolution

**Comment by Eh2406** [comment]
This I think would just involve changing https://github.com/rust-lang/cargo/blob/3ed34979a7036c62e2227b43ad3a8117d04fc69f/src/cargo/core/resolver/mod.rs#L1088 to depend on an argument; Then bubble that argument up till it is user facing.

**Comment by Eh2406** [comment]
I am still learning cargo internals, but I would be willing to help someone who wanted to take this on!

**Comment by bluetech** [comment]
> Then you accidentally start depending on features introduced in 1.1, but you don't change Cargo.toml

Perhaps there's some way to tackle this problem head-on? Probably not, but it's interesting to think about. Two possible ways I can think of:

- Force `B` to add `since="1.1.0"` annotations to API introduced in `v1.1.0`. Cargo prevents using APIs added later than the minimal version allowed by`Cargo.toml`.

- Use an automatic tool like https://github.com/rust-lang-nursery/rust-semverver.

**Comment by alexcrichton** [comment]
@Eh2406 I'd imagine that with yours and @aidanhs's work on the resolver recently it may be relatively easy to encode this as a constraint and have it finish in a hopefully-not-too-long amount of time too!

**Comment by Eh2406** [comment]
The relevant line of code has moved to:
https://github.com/rust-lang/cargo/blob/af6086182d98d284e4be72695be18ce3ddcbe671/src/cargo/core/resolver/mod.rs#L664
I think we would add a arg to:
https://github.com/rust-lang/cargo/blob/af6086182d98d284e4be72695be18ce3ddcbe671/src/cargo/core/resolver/mod.rs#L573

**Comment by Dylan-DPC** [comment]
Can give this a try :)

**Comment by Eh2406** [comment]
@Dylan-DPC That is wonderful!

The idea is that the sort on line L664 determines the order that cargo tries versions of packages. Currently from newest to oldest and we want to reverse that order.
Steps as I see it:
- Add a `-Z` flag, like I did in https://github.com/rust-lang/cargo/pull/4990/files
- Get that flag on L364 something like `config.cli_unstable().minimal_versions` and pass it to `RegistryQueryer`
- Use it in the sort function, `if minimal_versions {a.summary.version().cmp(b.summary.version()) } else the existing code`
- Add it to some tests. I'd fine them by (temporarily) hard coding `minimal_versions` to true and looking at wich test in `cargo\tests\testsuite\resolve.rs` fail.

How can I be helpful!?

**Comment by Dylan-DPC** [comment]
Thanks @Eh2406 will take a look whenever I'm free and see how far I get :)

**Comment by Eh2406** [comment]
If that turns out to be challenging, feel free to ask!

**Comment by Dylan-DPC** [comment]
@Eh2406 
> Get that flag on L364 something like config.cli_unstable().minimal_versions and pass it to RegistryQueryer

L364 of which file?

**Comment by Eh2406** [comment]
Sorry I wasn't clear 
cargo/src/cargo/core/resolver/mod.rs
