### ISSUE TITLE
Testing workspace package with features expects the root package to have those features

### ISSUE THREAD

**Issue by torkleyy** [rust-lang/cargo#4106]
Consider this project structure:

```
foo
├── bar
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── Cargo.toml
└── src
    └── lib.rs
```

If I add a feature to `foo/bar/Cargo.toml` called `whatever` and I run

```
cargo test -p bar --features whatever
```

I get

```
error: Package `foo v0.1.0 (file://[...]/foo)` does not have these features: `whatever`
```

**Comment by alexcrichton** [comment]
Ah yes currently Cargo interprets `--features` as applying to the "target" crate of the `--manifest-path` or current directory arguments. Right now there's no way to activate selective features in selected crates transitively, unfortunately.

**Comment by sharksforarms** [comment]
Do feature flags get passed down to sub-crates in a workspace?

**Comment by torkleyy** [comment]
No, unless you depend on that feature from your main crate.

**Comment by sharksforarms** [comment]
Oops, I had deleted my comment shortly after I posted, to give some context to torkleyy's comment, I had asked if `--features` flags got passed down to dependencies.
