### ISSUE TITLE
OpenSSL usage in cargo

### ISSUE THREAD

**Issue by equal-l2** [rust-lang/cargo#4112]
As far as I've found, cargo itself uses `openssl` only for calculating SHA256, in util/sha256.rs.
(Cargo uses the crate thorough the other dependencies, though.)

Do we really need OpenSSL binding just for calculating SHA256?

**Comment by alexcrichton** [comment]
Ah right now OpenSSL is a dependency of libssh2 and libgit2, we just use it for hashing because it's already there.
