### ISSUE TITLE
Can not upload large crate - important questions for current FFI approach

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/cargo#4114]
Whilst trying to publish the [dpdk-sys](https://github.com/lemonrock/dpdk-sys) crate, a FFI wrapper around DPDK and TLDK (user space networking libraries for Linux and FreeBSD), I've run into a bit of a problem:-
 `Uploading dpdk-sys v0.0.1 (file:///Volumes/Source/GitHub/lemonrock/dpdk/workspace/dpdk-sys)
error: api errors: max upload size is: 10485760`

This occurs because DPDK with TLDK is enormous - both the amount of rust code, and the size of the underlying C code. I'm bundling the third party C code with the crate as per current normal practice. Stripping this out will probably get me under the upload window.

There's a larger problem here that I seem to keep coming back to - third party dependency management - which is tied into C toolchains and the like. It's not nice and the solutions aren't clear, particularly when the need for accurate security management and audit is needed\*. There's also a classic conflict between shipping working third-party source code at the correct revision and relying on system dependencies (or integrating with their package managers).

In DPDK's case, it's massively complicated by the fact that it also has custom Linux kernel modules and many potentially valid configurations; it's deployment approach a bit like the model nginx adopts, or some of DJB's tools.

\* There are lots of nasty sharp edge cases to snag on. From my own perspective, I put my last decade's worth of learning into [Libertine Linux](https://github.com/libertine-linux), but that's just one approach.

Personally, I'd love to lead the Rust cargo team through a face-to-face white boarding session on how we can make this a lot better. If you're ever in the North of England...

**Comment by carols10cents** [comment]
Sooooo we have a way to raise the filesize limit for particular crates, but I sense that doesn't really deal with the larger problem you're getting at :) I agree the larger problem sounds hairy and we should discuss it more! Perhaps an RFC?

**Comment by raphaelcohn** [comment]
A potential solution is to not upload sources but track git (or other) version control references. That would allow for proper IT auditing of software dependencies, something that would be necessary should I propose Rust for a secure government project, say. Distributing software tarballs (which is what a cargo publish is doing) breaks the auditable chain.

The problem is intricately intertwined with Rust's need to integrate via FFI with C and C++ libraries, both of which are technologies awash with truly awful build, deploy and package management solutions... if they are used at all. Autoconf, pkg-config, CMake, Makefiles when intersected with the conflicting needs of incremental building, deploying on the machine built for or cross-compiling and Orphesus weeps in Hades...

**Comment by OTL** [comment]
I have same issue. My crate is using assimp which is written in C/C++.

**Comment by OTL** [comment]
My comment was a mistake, ignore it. sorry.
