### ISSUE TITLE
[Question] cargo run uses the project folder as the working folder. Is this behaviour intended?

### ISSUE THREAD

**Issue by quixoticaxis** [rust-lang/cargo#4115]
I'm currently learning Rust and I'm surprised by the way `cargo run` acts (I use Rust on Windows with msvc toolchain and call cargo from PowerShell):

The following code:
```
    use std::io::Write;
    let mut file = std::fs::File::create("some.txt").expect("Couldn't create some.txt");
    let buffer = b"some text";
    let result = file.write(buffer);
```
when executed by `cargo run` creates "some.txt" in the root folder of the project, not in the folder where .exe file reside. It's strange, at least because this way debug execution and release execution overlap.

Is this behaviour intended? And if yes, then I'd be interested in knowing why. Thank you.

**Comment by alexcrichton** [comment]
Hm I think `cargo run` should preserve the current dir of the calling process, did you invoke it from the root dir? If so, I believe that's expected behavior

**Comment by quixoticaxis** [comment]
Yes, I invoked it from the root directory of the project. It still looks strange to me, but I guess I'll find some scenario in which this behaviour is needed one day. Thanks for the quick reply ^-^

**Comment by alexcrichton** [comment]
No worries! Ok in that case I think this expected behavior, so closing.
