### ISSUE TITLE
Transitive minor updates of deps shouldn't fail `cargo update`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#4127]
Let's say you've got the following project structure:

* Top level project, A
* A depends on `log = "0.3.6"`
* A depends on B, a sub-project in this same directory
* B depends on `log = "0.3.6"`

When you generate a lock file for this project let's say you get `log = "0.3.6"`. If you then later edit B's `Cargo.toml` to instead say `log = "0.3.8"` then if you run `cargo update -p a` Cargo will inform you:

```
error: failed to select a version for `log` (required by `b`):
all possible versions conflict with previously selected versions of `log`
  version 0.3.6 in use by log v0.3.6
  possible versions to select: 0.3.8
```

Cargo should gracefully handle this and not generate an error!

I'm not sure whether this is 100% related to path dependencies. Some more info can also be [found here](https://bugzilla.mozilla.org/show_bug.cgi?id=1361005).

**Comment by upsuper** [comment]
FWIW this happend again for https://hg.mozilla.org/integration/autoland/rev/6b5e1e49a4c2fdaa164072ceef196c66197cf1d5

```
error: failed to select a version for `app_units` (required by `style`):
all possible versions conflict with previously selected versions of `app_units`
  version 0.5.1 in use by app_units v0.5.1
  possible versions to select: 0.5.2
```

**Comment by shepmaster** [comment]
Thank you, @alexcrichton !
