### ISSUE TITLE
`cargo test` doesn't capture print from threads

### ISSUE THREAD

**Issue by kpcyrd** [rust-lang/cargo#4129]
I ran the tests for one of my crates that uses threads in its example code. I've noticed it printed some lines to stdout, even though `--nocapture` wasn't set, but not all of them. It appears that text printed from new threads are not correctly captured, I think this is not intended.

```
running 2 tests
request: 123
test tests::readme ... ok
test tests::single_requester ... ok
```

**Comment by Mark-Simulacrum** [comment]
You're correct, this should be filed on rust-lang/rust (closing in favor of https://github.com/rust-lang/rust/issues/42474).
