### ISSUE TITLE
Cargo publish error message referencing dirty files ambiguous

### ISSUE THREAD

**Issue by natboehm** [rust-lang/cargo#4130]
Currently when `cargo publish` is run on files not under version control, an error message is given as follows:

```
error: 2 dirty files found in the working directory:

Cargo.toml
src/lib.rs
```

In this case 'dirty files' is ambiguous. The message might be more helpful having some reference to the files not currently being tracked by version control.

**Comment by alexcrichton** [comment]
You're [not the only one](https://github.com/rust-lang/cargo/issues/3876) who found this confusing! The good news is that it should be [improved on master](https://github.com/rust-lang/cargo/pull/3909) and it should make its way to stable soon!
