### ISSUE TITLE
Separate debug/release dependency directories

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/cargo#4132]
While there are requests (#1359, #1596) to allow for the optimization of  dependencies, a suggestion to curb dev times would be to cache the results of dependency builds for debug/release separately, so that switching between `cargo build` and `cargo build --release` does not require a full rebuild of all dependencies, only the changed rs source files in question.

**Comment by alexcrichton** [comment]
This should currently be the case (`target/debug` and `target/release`), but is that not working for you?

**Comment by mqudsi** [comment]
I'm sorry, I've been avoiding switching between them like the plague since I started using rust for this reason; it seems that it has indeed been resolved some time ago and I never dared to try it and find out :)
