### ISSUE TITLE
Keep package.metadata in new manifest

### ISSUE THREAD

**Issue by onur** [rust-lang/cargo#4142]
Docs.rs finally got support for building non-default features but looks like cargo is striping  `package.metadata.docs.rs` section from manifest. Docs.rs is heavily using cargo and getting manifest path with `cargo::core::package::Package::manifest_path` on multiple occasions.

So it would be great to keep `package.metadata` in new manifest or maybe we can add a function like `manifest_path_orig` to `Package`.

**Comment by alexcrichton** [comment]
Ah yes definitely a bug and not intentional! I'll look to fixing this soon.

**Comment by alexcrichton** [comment]
Ok, fix submitted as https://github.com/rust-lang/cargo/pull/4167

**Comment by onur** [comment]
Thanks!
