### ISSUE TITLE
Getting invalid tar file for a number of crates

### ISSUE THREAD

**Issue by Muhd** [rust-lang/cargo#4143]
OS: Windows

Crates with issue (probably not exhaustive): "num_cpus", "rayon-core", "xargo"

Example:
```
> cargo install rayon-core --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
Failed to unpack package `rayon-core v1.0.2`

Caused by:
  invalid tar archive
```

**Comment by alexcrichton** [comment]
Thanks for the report! Can you run `cargo -vV` and gist the output of that as well? (the version of Cargo you're using)

**Comment by Muhd** [comment]
```
cargo 0.6.0-nightly (e1ed995 2015-10-22)
```

**Comment by Muhd** [comment]
Hmm... that seems rather old if it's really from 2015... I just did the installer from rustup a few days ago...

**Comment by alexcrichton** [comment]
Ah yeah that is indeed a pretty ancient version! If you update Cargo this should work, but thanks for the report!
