### ISSUE TITLE
bench_all_exclude test is fragile

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/cargo#4144]
The test `bench::bench_all_exclude` is fragile because its expected output includes the line:

```
test bar ... bench:           0 ns/iter (+/- 0)
```

Expecting an average of 0 ns/iter seems reasonable at first, since the `bar` function in question is
```rust
            #[bench]
            pub fn bar(b: &mut test::Bencher) {
                b.iter(|| {});
            }
```

But, on my machine at least, for some reason (perhaps due to load elsewhere, though its relatively unloaded IMO), when I do `cargo test` I am getting output like this:

```
test bar ... bench:           0 ns/iter (+/- 3)
```

so, due to variance in the reported variance, the test fails for me. 😞 

(When I do `cargo test --release`, the test passes, so I have worked around the issue in the short term that way. but I think we should be able to run tests in debug mode without things like this failing.)

Can we make the expected output a regexp or something so that the concrete numbers  do not matter? This seems to be the only test that relies on the output from a benchmark.

**Comment by matklad** [comment]
Yep, we use `[..]` as a wildcard in Cargo tests.
