### ISSUE TITLE
Pass -Ctarget-cpu=native during cargo install

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#4150]
This lets LLVM assume that the binary will be run on a machine with all the features as the host machine (and thus optimize more e.g. with better SIMD/AVX). Which is true for `cargo install`, and we should pass it by default, perhaps with a flag to turn it off.

cc @rust-lang/cargo

**Comment by joshtriplett** [comment]
We can't automatically make this assumption; people do use `cargo install` as part of packaging systems, too.

**Comment by Nemo157** [comment]
Based on the discussion in the linked PR and @joshtriplett's comment, should this be closed as "won't fix"?

**Comment by alexcrichton** [comment]
I think so!

**Comment by joshtriplett** [comment]
We could reasonably pass this by default for build scripts, if we want to, though.

**Comment by Rudxain** [comment]
This should be closed as "not-planned", not "completed". This may be misleading

**Comment by Nemo157** [comment]
That is a github bug, there was no such thing as a close reason when this issue was closed and github assigned "completed" to all previously closed issues.

**Comment by weihanglo** [comment]
They provide a way to close it again as not planned. Lemme try.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/14314532/189368048-712718ea-f363-4032-8524-ed39929ac341.png">

**Comment by Rudxain** [comment]
> That is a github bug, there was no such thing as a close reason when this issue was closed and github assigned "completed" to all previously closed issues.

I'm sorry for my ignorance. Thank you for clarifying this

**Comment by Rudxain** [comment]
What about a [new sub-cmd](https://github.com/rust-lang/cargo/issues/10399#issuecomment-2127045486)? (we can bike-shed the name later)
