### ISSUE TITLE
Cargo still in 0.19.0 version

### ISSUE THREAD

**Issue by Songbird0** [rust-lang/cargo#4154]
Hi there!

I ran `rustup update stable`:

* `rustc` has been upgraded to `1.18`;
* `cargo` has not been upgraded, he's still in `0.19.0` rather than `0.21.0`.

I reinstalled `rustup` but the problem is still here. Could you help me, please ?

Platform: 
```
Kernel: 4.4.0-67-generic x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by sfackler** [comment]
That's the current stable release of Cargo.

**Comment by Songbird0** [comment]
Thanks for responding!

> That's the current stable release of Cargo.

Okay, so... Can you explain me why `cargo build --bins` don't work ? :/
`--bin` option **[is effective](https://github.com/rust-lang/cargo/blob/rust-1.18.0/src/cargo/ops/cargo_compile.rs#L135)** for `1.18`, though.

**Comment by sfackler** [comment]
Hmm, that bit of the 1.18 release announcement may have been wrong - @alexcrichton?

**Comment by mcarton** [comment]
Is it also intended that the crate is stuck at 0.19.0 on crates.io?

**Comment by sfackler** [comment]
The crates.io release matches the stable release.

**Comment by alexcrichton** [comment]
@Songbird0 ah yes looks like the release announcement was wrong, this feature is coming in Rust 1.19, not Rust 1.18.

@mcarton we only publish stable versions of Cargo currently, which is why it's at 0.19.0.

Looks like the only issue here is with the release announcement, though, so I'm going to close.
