### ISSUE TITLE
Add an option to output crate build timings

### ISSUE THREAD

**Issue by luser** [rust-lang/cargo#4164]
Currently cargo outputs a line at the end of the build like `Finished dev [unoptimized + debuginfo] target(s) in 4.78 secs` giving the overall build time. It would be nice if there was a way to get out build times for the individual crates that were built, and even timings for the individual build steps within each crate, like compiling a build script, executing a build script, compiling the crate, compiling any binaries, etc. The most useful thing to me would be to just output a JSON file, probably.

**Comment by federicomenaquintero** [comment]
Note that with #7405 this is more or less already in place.

**Comment by ehuss** [comment]
Yea, I'll close in favor of #7405.
