### ISSUE TITLE
No bump ssh2-rs to 0.2.6 for the 0.19.0 release version?

### ISSUE THREAD

**Issue by martell** [rust-lang/cargo#4172]
@alexcrichton Forgive my lack of understanding with the stable, beta rotation going on in rust-lang but
version 0.19 of cargo was released a few days ago and ssh2-rs was still at version 0.2.5 and not 0.2.6 which effectively fixes cloning private git repos via ssh on windows as described here https://github.com/alexcrichton/ssh2-rs/commit/0a2c2694eaaed9196f3ee869dd9ea2f3c1fa5019 and here https://github.com/alexcrichton/git2-rs/issues/202

Is there a reason this did not get a backport for the release? I see that it was committed here a month ago
https://github.com/rust-lang/cargo/commit/77b761260ba35bea88a4f7bca10c429fc8b66d8a

I can probably just cherry-pick or backport it for msys2 but I am just wondering what is going on :)

**Comment by alexcrichton** [comment]
Ah no worries! The release process confused me sometimes too...

We don't mind doing backports but at this point it's probably too late for cargo 0.19.0 (the rust-1.18.0 branch). This should go out in the next release though, right?

**Comment by mati865** [comment]
It was merged to master which became beta with release of 1.18.0.
[Link to current beta](https://github.com/rust-lang/cargo/blob/c9bdd3e9bd77debf4715a074ee90d19f5551000e/Cargo.lock#L363)

@martell you should backport this for MSYS2.

**Comment by carols10cents** [comment]
This sounds like it's moot now.

**Comment by martell** [comment]
Is is, thank you for closing :)
