### ISSUE TITLE
Re-factor argument parsing so that options shared by multiple commands aren't duplicated.

### ISSUE THREAD

**Issue by tomprince** [rust-lang/cargo#4177]
This might involve some clever refactoring of the docopt definitions, or it might involve porting to something like clap.

I know @matklad has looked into this.

**Comment by tomprince** [comment]
Previous discussions:
- https://github.com/rust-lang/cargo/pull/4031#discussion_r116165737
- https://github.com/rust-lang/cargo/pull/4031#discussion_r116165737

**Comment by tomprince** [comment]
I'm going to investigate porting things to clap.

**Comment by alexcrichton** [comment]
👍

**Comment by matklad** [comment]
I'm going to make another stab at it :)

**Comment by dwijnand** [comment]
Fixed by https://github.com/rust-lang/cargo/pull/5152?

If you take the `--feature` option as an example you just need `arg_features` from `command_prelude`.

Look ma, no behaviour duplication!
https://github.com/search?q=repo%3Arust-lang%2Fcargo+arg_features&type=Code

**Comment by matklad** [comment]
Indeed, thanks @dwijnand
