### ISSUE TITLE
cargo package incorrectly calculates dependencies for git submodule

### ISSUE THREAD

**Issue by the8472** [rust-lang/cargo#4183]
Cargo.toml

```
[dependencies]
btrfs = { path = "./rust-btrfs", version = "1.2.1" }
```
this points to a git submodule
```
$ git submodule status rust-btrfs/
 fe45750b2ad9a25e712a3a918cd2717415efc8c5 rust-btrfs (version-1.2.1-2-gfe45750)
```
rust-btrfs/Cargo.toml
```
[dependencies]
	crc = "1.4"
	flate2 = "0.2"
	nix = "0.8.1"
	lazy_static = "0.2"
	libc = "0.2"
	minilzo = "0.1"
	uuid = "0.3"
```

`cargo build` succeeds. `cargo package` fails with the following error:
```
error: failed to verify package tarball

Caused by:
  no matching package named `ioctl` found (required by `btrfs`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.3
``` 

Note that the `ioctl` crate is not a dependency of the included submodule, it is only a dependency of the crate on crates.io.

**Comment by alexcrichton** [comment]
@the8472 I think that's becuase `ioctl` has all versions yanked on crates.io?

**Comment by the8472** [comment]
@alexcrichton that's the issue I am trying to fix. the original btrfs crate depends on ioctl, but my patched version in the git submodule does not and yet it still fails as if it were using the original. So something with the dependency resolution appears to be wrong.

**Comment by alexcrichton** [comment]
Ah this is actually expected behavior, when you publish to crates.io all path dependencies are translated to crates.io dependencies. You'll need to publish the `ioctl` crate with a new version (or pick a new unique name) to publish the `btrfs` crate.
