### ISSUE TITLE
Cargo check fails with internal error

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4188]
The error looks like this:

```
λ cargo check --all --verbose
error: dep-info not in an understood format: /home/matklad/projects/fall/target/debug/.fingerprint/fall_gen-1d7df0cac95e3081/dep-bin-gen-1d7df0cac95e3081
```

Removing `.target` directory fixes the error. I don't think I understand what caused the error originally.

**Comment by alexcrichton** [comment]
Do you have the original source code I could poke around with? I wonder if something got corrupted by accident...

**Comment by matklad** [comment]
No, I originally expected that this was due to upgrade from 1.17.0 to 1.18.0, so I deleted `target` and tried compiling with 17 and then switching to 18, but everything worked fine then, and I was unable to reproduce the error at all :(

**Comment by m-cat** [comment]
I just had the good luck to run into this.

```
❯ cargo test --verbose
error: dep-info not in an understood format: /Users/marcin/Dropbox/Work/maidsafe/safe_client_libs/target/debug/.fingerprint/safe_authenticator-151ddd9151afa849/dep-lib-safe_authenticator
```

The contents of the `dep-lib-safe_authenticator` file:

```
src/lib.rs
