### ISSUE TITLE
Silently ignored dependency

### ISSUE THREAD

**Issue by sanpii** [rust-lang/cargo#4192]
Hello,

I take long time to find why `cargo build` doesn’t compile my local crate (required via path).

My crate had a `main.rs` file (without `main` function) instead of `lib.rs`.

I don’t know the best way to inform about this mistake (missing `main` function or crate without `lib.rs`) but it’s difficult to find its.

**Comment by alexcrichton** [comment]
Thanks for the report! I don't quite understand the construction of a project to lead to this error, mind giving an example or a repo I can poke around in?

**Comment by sanpii** [comment]
As I recall:
* develop a first crate;
* split this crate by moving files;
* create missing files (`Cargo.toml`, `main.rs`, …);
* develop the second crate with tests;
* require the second crate in the first one with path.

**Comment by alexcrichton** [comment]
Do you have an example project structure or a more concrete definition of how to reproduce this?

**Comment by sanpii** [comment]
https://github.com/sanpii/cargo-bug

**Comment by alexcrichton** [comment]
Can you clarify what the bug is in this case? If you `cargo build` in the top-level it won't work because the `bad-crate` crate doesn't have any libraries.

**Comment by sanpii** [comment]
> If you cargo build in the top-level it won't work because the bad-crate crate doesn't have any libraries.

Yes, the compilation failed but the message is ambiguous:

```
$ cargo build
   Compiling rust v0.1.0 (file:///home/sanpi/test/rust)
error[E0463]: can't find crate for `bad_crate`
 --> src/main.rs:1:1
  |
1 | extern crate bad_crate;
  | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error(s)

error: Could not compile `rust`.

To learn more, run the command again with --verbose.
```
I registered a crate, but it’s a binary crate.

**Comment by creativcoder** [comment]
Cargo distinguishes a crate as binary if it has a `main.rs` file and as a library if it has a `lib.rs` file. Anything other than that will result in your crate not being identified.

But this behavior can be overridden if you explicitly specify the file that you want to be treated as your crate/library root; in `bad-crate`'s Cargo.toml file like:

```toml
[lib]
path = "src/main.rs"
```
Then it will compile and pull the bad-crate as a library dependency just fine.

**Comment by alexcrichton** [comment]
Yeah I definitely agree the error message could be improved here! I'll tag it as such.

**Comment by eminence** [comment]
Triage:  Cargo will now give this warning message, which gives the user a hint that something is wrong with their dependency:

 > warning: rust v0.1.0 (/home/achin/tmp/66/cargo-bug) ignoring invalid dependency `bad-crate` which is missing a lib target

**Comment by ehuss** [comment]
Yea, this seems sufficiently resolved now, thanks!

**Comment by sanpii** [comment]
Great, thank you.
