### ISSUE TITLE
`cargo install` leaves sockets open when calling `cc`

### ISSUE THREAD

**Issue by setharnold** [rust-lang/cargo#4193]
Hello,

I have written an AppArmor profile to confine cargo, rustup, rustc, etc. This profile is not perfect but works for me. As a result of this profile I can see the `cargo install` tool leaves open sockets too long. For example,

```
cargo install cargo-script
```

causes AppArmor to report that `cc` has been passed file descriptors for sockets to:

```
192.30.255.116:443
50.17.240.35:443
52.219.20.136:443
```

I'd be happy to share my AppArmor profile if it would help but I suspect a faster way to debug the issue might start with replacing `cc` with a program that dumps its `/proc/self/fd/` and looks for symlinks to `socket:[nnnnn]` (or simply sleeps and let a human do the work).

Thanks

**Comment by alexcrichton** [comment]
Thanks for the report! I've never used AppArmor myself so I'm not really sure, could you clarify what's going on here? Does this mean that Cargo has file descriptors leaking into child processes?

**Comment by setharnold** [comment]
Hello Alex, that's exactly what's happening. They may be leaking before `cc` is called, of course, but the way I wrote my profile it's easiest to spot it at this execve() call.

I confirmed that putting the following shell script in my `/usr/bin/gcc-5` shows the same results:

```
#!/bin/sh
ls -l /proc/$$/fd/ > /tmp/files.$$
true
```

The results are:

```
$ cat /tmp/files.6697 
total 0
lr-x------ 1 1000 1000 64 Jun 19 19:06 0 -> /dev/null
l-wx------ 1 1000 1000 64 Jun 19 19:06 1 -> /tmp/files.6697
lr-x------ 1 1000 1000 64 Jun 19 19:06 10 -> /usr/bin/gcc-5
l-wx------ 1 1000 1000 64 Jun 19 19:06 11 -> pipe:[27713330]
l-wx------ 1 1000 1000 64 Jun 19 19:06 2 -> pipe:[27713331]
lrwx------ 1 1000 1000 64 Jun 19 19:06 4 -> socket:[27713296]
```

(The `1000` is due to AppArmor still blocking uid lookups here. Yours will have user names and group names as expected.)

The `socket` line in fd 4 is the unexpected entry.

Thanks

**Comment by alexcrichton** [comment]
AFAIK all sockets Cargo opens in Rust are CLOEXEC, so maybe this is coming from libgit2 or libcurl? I'm not entirely sure :(

**Comment by alexcrichton** [comment]
Looks like it's both libcurl and libgit2, neither use CLOEXEC from what I can tell.

**Comment by alexcrichton** [comment]
Or rather libcurl doens't seem to try, and libgit2 only uses if `O_CLOEXEC` is defined and it isn't when we build cargo nightlies (due to the kernel being old)

**Comment by alexcrichton** [comment]
Oh actually looks like libcurl [gives us the option to open sockets](https://github.com/alexcrichton/curl-rust/pull/172) so we can at least cover ourselves there!

**Comment by ashleygwilliams** [comment]
hey @alexcrichton! looks like you got a commit in related to this issue- does that mean we've addressed it and can close the issue? (thanks for filing @setharnold! we really appreciate it 🐬 🦀 ✨ )

**Comment by alexcrichton** [comment]
@setharnold can you test on recent nightlies and see if this is fixed?

**Comment by alexcrichton** [comment]
I'm going to close this as libcurl I believe has been fixed and otherwise libgit2 seems to be out of our hands :(
