### ISSUE TITLE
Can the rust-lang develop environment more portable？like go lang

### ISSUE THREAD

**Issue by mokeyish** [rust-lang/cargo#4198]
I install the rust-lang a month ago，but I reinstall the system yesterday.Now I have to download rust and install it .very inconvenient... but the go-lang ,set go-root path in intellij idea  and it works,no installation required, very convenient.

**Comment by Mark-Simulacrum** [comment]
I don't believe there's any solution to this. I'd assume that either Go was pre-installed by default on the system or otherwise available; eventually this may be true of Rust, but I don't think we can do much to fix this.

**Comment by carols10cents** [comment]
@mokeyish Can you clarify what you mean by "reinstall the system"? What is the system, your operating system? Which operating system are you on?

**Comment by mokeyish** [comment]
@Mark-Simulacrum This is just a suggestion. Rust cargo installed in the user directory by default,after reinstall the operating system ,it has gone ,then rust must be reinstall too. But go-lang or JAVA jdk,can install into the directory which i choose,after reinstall operating system ,I just need to set the environment variable.

**Comment by mokeyish** [comment]
@carols10cents sorry ,"reinstall the system" means operating system。

**Comment by Mark-Simulacrum** [comment]
Rustup has an issue tracking user-specified installation directory (including global) https://github.com/rust-lang-nursery/rustup.rs/issues/313.

**Comment by carols10cents** [comment]
Oh! I see. Yes, I think this is covered by the rustup issue. Thank you!
