### ISSUE TITLE
`cargo search` now writes search results to stderr

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/cargo#4203]
Previously only the "Updating registry" used to be written to stderr. Now the search results are as well.

```
$ cargo --version
cargo 0.21.0-nightly (50b1c24d1 2017-06-17)

$ cargo search error-chain
    Updating registry `https://github.com/rust-lang/crates.io-index`
error-chain = "0.10.0"           # Yet another error boilerplate library.
...

$ cargo search error-chain 2>/dev/null
```

With an older version I had lying around:

```
$ cargo --version
cargo 0.20.0-nightly (13d92c64d 2017-05-12)

$ cargo search error-chain
    Updating registry `https://github.com/rust-lang/crates.io-index`
error-chain = "0.10.0"           # Yet another error boilerplate library.
...

$ cargo search error-chain 2>/dev/null
error-chain = "0.10.0"           # Yet another error boilerplate library.
...
```

**Comment by Arnavion** [comment]
I guess this accidentally added the `.err()` ?

https://github.com/rust-lang/cargo/commit/f8fb0a022853ab3f423889d442c695511ece3692#diff-abcc7479bcfaa9a504970c60506e10aeL427

**Comment by alexcrichton** [comment]
Yes this changed recently, did it cause a regression?

**Comment by Arnavion** [comment]
It broke my scripts. Is it intentional?

**Comment by alexcrichton** [comment]
It is intentional in the sense that we knew we were changing this, as we didn't imagine there'd be much breakage as we thought that humans mostly looked at this (as opposed to tools). Mind describing the context in which this broke though?

**Comment by Arnavion** [comment]
Just personal scripts as I said, eg

```powershell
function cargo-outdated {
	(cargo metadata --no-deps --format-version 1 | ConvertFrom-Json).packages.dependencies |
		Select-Object -Property name, req |
		Sort-Object -Property name, req -Unique |
		%{
			New-Object psobject |
				Add-Member -NotePropertyName Name -NotePropertyValue $_.name -PassThru |
				Add-Member -NotePropertyName Req -NotePropertyValue $_.req -PassThru |
				Add-Member -NotePropertyName Latest -NotePropertyValue (cargo search $_.name 2>$null | Select-String -Pattern "^$($_.name) = `"([^`"]+)" | %{ $_.Matches[0].Groups[1].Value }) -PassThru
		} |
		?{ $_.Latest } |
		%{
			[regex] $regex = "^$($_.Req -replace '\.', '\.' -replace '\*', '[\d\.]*')$";
			$_ | Add-Member -NotePropertyName UpToDate -NotePropertyValue $regex.IsMatch($_.Latest) -PassThru
		} |
		%{ Write-Host -ForegroundColor $(if ($_.UpToDate) { 'Green' } else { 'Red' }) "$($_.Name) $($_.Req) $($_.Latest)" }
}
```

ie a minimalistic (and slightly hacky in its handling of semver) version of the cargo-outdated crate that doesn't take an age to install itself and gives me just the output I care about.

It's a trivial change to make them work with the new cargo (`2>$null` -> `2>&1`, etc), so it's not a big deal for me. I just didn't imagine the primary output of a tool going to stderr could be a deliberate change, hence this GH issue. What is the reason to break convention like this?

**Comment by alexcrichton** [comment]
In general we try to avoid stdout in Cargo, but this seems pretty reasonable, I'll change it back.
