### ISSUE TITLE
    Blocking waiting for file lock on the git checkouts

### ISSUE THREAD

**Issue by bitcoiners** [rust-lang/cargo#4205]
cargo is stuck at: 

~/dev/parity$ cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Blocking waiting for file lock on the git checkouts

**Comment by CrocdileChan** [comment]
hello， I have this question now.    And I executed `rm -rf  ~/.cargo/registry/index/*`     it is not yet.    How did you fix it?
