### ISSUE TITLE
Add a new --range argument on cargo install to accept semver ranges

### ISSUE THREAD

**Issue by azerupi** [rust-lang/cargo#4207]
Discussion started in #3321 

By mistake, the `cargo install --vers` takes a semver range instead of a precise version. This behaviour is now deprecated and issues a warning, however there are legitimate use cases for installing a binary using a semver range.

My personal use case is for mdBook. A lot of projects have set up automatic deployment of their rendered books through CI. The problem is that if they install the latest version, their deployment might break when we release a "breaking version". So they have to pin the installed version in their CI script, requiring manual intervention every time we release a patch version. The ideal solution would be to allow a binary specifying a semver range so that the CI script can install the latest *compatible* version, only requiring manual update when we release a breaking version.

@alexcrichton proposes to add the `--range` argument on `cargo install` to specify a semver range and keeping the `--vers` argument to specify a strict version.

If this is a desired feature, I would be willing to try and make a PR for this. 😊

**Comment by matklad** [comment]
Hm, could we use a singe `--vers` flag, but allow for `~1.2.3` constraints? That is, interpret `0.1.2` as a precise version, but continue to parse all other [VersionReq syntaxes](http://www.steveklabnik.com/semver/semver/struct.VersionReq.html#examples-1)?

**Comment by alexcrichton** [comment]
@matklad that's a possibility, yeah, but it runs the risk of being backwards from `Cargo.toml` and possibly confusing :(

**Comment by matklad** [comment]
I'd say that `--vers "^1.2.3"` is more obvious then `--range "1.2.3"`, and I don't think this'll cause a lot of confusion.  For the `--vers "1.2.3"` flavor, it works exactly as documented, and is the same under both proposals, so the amount of the confusion is the same. And the `--vers "~1.2.3"` flavor.

As you may have noticed, I usually want to avoid adding separate command line flags, if possible. Way too often I need `| grep` or `| less` to read `--help` of various unix utilities :(

**Comment by alexcrichton** [comment]
Yeah that makes sense to me. ok, I'm convinced!

**Comment by matklad** [comment]
Ok, the only problem is that I am not 100% sure that there isn't some nasty syntactic ambiguity between version and range. Let's ask @steveklabnik about this!

@steveklabnik, we want to interpret stuff like `1.2.3` as a precise sevantic version, and stuff like `^1.2.3` as a SemverRange. Will the following algorithm work without surprises?

1. If input is empty, return error.
2. look at the first character, if it is among `<`, `>`, `=`, `^`, `~`, parse input as range (this may return error)
3. if the first character is not `<`, `>`, `=`, `^`, `~`, parse input as version.

**Comment by alexcrichton** [comment]
What about:

* Parse input as a semver version
  * If successful, match exactly that
  * If failure, parse as a semver range
    * If successful, match that
    * If failure print out that error message

**Comment by matklad** [comment]
@alexcrichton I think this variant can lead to surprises: `--vers "0.1"` will be parsed as range, which is not super obvious if you don't know that in rust versions have three components.

**Comment by alexcrichton** [comment]
Ah yeah that's a very good point! In that case the steps you proposed above sound pretty good to me

**Comment by matklad** [comment]
Yeah, I think we in general need to be wary of patterns like "try A, if that fails, fallback to B", because then fixing a bug in A is a backwards incompatible change (this is exactly the problem with the algorithm for infering binary paths)!

**Comment by azerupi** [comment]
>I think this variant can lead to surprises: `--vers "0.1"` will be parsed as range

So if I understand correctly, this should result in a warning (or error) because it would be parsed as a precise version, right?

**Comment by matklad** [comment]
Yeah, this should say something like "Invalid semantic version string `0.1`". If we want to get fancy with error messages, we can then try to parse this as range, and if that succeeds add "if you want to specify semver range, add qualifier explicitelly, like `^0.1`?"

**Comment by azerupi** [comment]
Ok, I think I understand everything that needs to happen now. I will try to implement this and issue a PR when I'm done. :)

**Comment by azerupi** [comment]
The PR has been merged, so I'm going to close this issue :)
