### ISSUE TITLE
rerun-if-changed always trigger rebuild on non-exist file

### ISSUE THREAD

**Issue by bozaro** [rust-lang/cargo#4213]
**Original cause:** https://github.com/bozaro/lz4-rs/issues/21

**Root cause:**
- I use [skeptic](https://github.com/brson/rust-skeptic/) for file `README.md`
- Skeptic generate some code and tell to cargo:
```
cargo:rerun-if-changed=README.md
cargo:rerun-if-changed=README.md.skt.md
```
- File `README.md.skt.md` is not presend in my project and cargo always rerun build.

I would expect that the restart will only happen if `README.md.skt.md` file appears.

Unfortunatelly, adding check for file exists in `Skeptic` is incorrect, because it should rerun if file appears at some time.

**Comment by alexcrichton** [comment]
Thanks for the report! This is expected behavior, though, for Cargo. Cargo needs to rerun a build script when a file is deleted, so if it's not present Cargo doesn't know whether it ws deleted or just didn't exist before.

**Comment by bozaro** [comment]
I do not understand how you can correctly handle incremental compilation, when the appearance of a file can affect the state of the artifact.
For example, I can't tell cargo: rerun if the list of files changed. Something like:
```
cargo:rerun-wildcard=*.md
```

**Comment by alexcrichton** [comment]
Yeah in general Cargo doesn't (and nor do most build systems) have the ability to get rerun when a file appears. Typically this works out as some other file indicate that said file appeared, but right now it's not possible to do so with Cargo.

**Comment by TheButlah** [comment]
Is this truly intended behavior? If cargo knows which directory to watch for changes via `println!("cargo:rerun-if-changed=maybe_exists")`, it should be able to do (pseudocode):

```rust
enum ChangeHistory {
  Exists(Mtime),
  NoFile
}

for (path, history) in tracked_changes {
  match history {
    Exists(mt) => rerun_if_mtime_changed(path, mt)
    NoFile => rerun_if_file_exists(path),
  }
}
```
