### ISSUE TITLE
Cargo can not find dependent crate when workspace file not in root

### ISSUE THREAD

**Issue by bluejekyll** [rust-lang/cargo#4217]
I haven't looked at the code yet, but here is the related issue: https://github.com/rusoto/rusoto/issues/725

Moving the workspace Cargo.toml from the subdirectory to the root fixes the issue, as done in this PR: https://github.com/rusoto/rusoto/pull/731

**Comment by alexcrichton** [comment]
Oh this is actually just a bad error message and/or how Cargo handles the git repository, the root cause of the failure is [this crate](https://github.com/rusoto/rusoto/blob/master/helpers/Cargo.toml#L11-L13) which depends on a crate that doesn't exist.

**Comment by matthewkmayer** [comment]
Is it an alphabetical search?  When the "main" Cargo.toml file is moved to the root of the git repo things work as expected, which is the issue and PR for the Rusoto project.

That helper crate is laying fallow, we should probably get rid of it until we're back working on it.

**Comment by alexcrichton** [comment]
I'm not actually sure why moving the workspace Cargo.toml would fix things, in theory you'd have the error no matter what...

**Comment by bluejekyll** [comment]
Oh, I know why. I excluded helpers from the root `Cargo.toml` after the move. I didn't realize that was the original issue.

**Comment by kellda** [comment]
Is there still an error / bug or can it be closed ?

**Comment by bluejekyll** [comment]
I don’t know. I don’t normally work on project layouts as complex as the one referenced.

**Comment by bluejekyll** [comment]
We can close, and reopen if it comes up again.
