### ISSUE TITLE
`--host` flag in search command wants registry index URL, not registry website host

### ISSUE THREAD

**Issue by dethoter** [rust-lang/cargo#4219]
The issue is the same as in #3797, but relates to `bin/search`.

**Comment by ashleygwilliams** [comment]
for people interested in taking this on, steps required would include, but may not be limited to:

- deprecate `--host`
- rename it as `--index`

a good example is this PR which does the same thing, but for `publish` https://github.com/rust-lang/cargo/pull/4209

(thanks for filing @dethoter! 🐶 ⭐️ 🌴 )
