### ISSUE TITLE
test --doc can't find dependency of dependency with a proc macro when passing --target

### ISSUE THREAD

**Issue by parched** [rust-lang/cargo#4224]
I was trying to add CI to a proc macro crate of mine, but the CI passes `--target` explicitly even though it's unneeded. To my surprise the test failed https://travis-ci.org/parched/runtime-target-feature-rs/jobs/246862218

I've tried to create a minimal repro below, possibly there are some extra things that aren't needed.

Cargo.toml
```
...

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
```

`src/lib.rs`
```
#![feature(proc_macro)]

extern crate proc_macro;
extern crate syn;

use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn test(_: TokenStream, function: TokenStream) -> TokenStream {
    function
}
```

```
$ cargo test --doc --target x86_64-unknown-linux-gnu
   Compiling quote v0.3.15
   Compiling unicode-xid v0.0.4
   Compiling synom v0.11.3
   Compiling syn v0.11.11
   Compiling runtime-target-feature v0.1.0 (file:///home/james/junk/cargo-dep-test)
    Finished dev [unoptimized + debuginfo] target(s) in 5.35 secs
   Doc-tests runtime-target-feature
error[E0463]: can't find crate for `quote` which `syn` depends on
 --> /home/james/junk/cargo-dep-test/src/lib.rs:4:1
  |
4 | extern crate syn;
  | ^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error(s)

thread '<unnamed>' panicked at 'Box<Any>', src/librustc_errors/lib.rs:512
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: test failed, to rerun pass '--doc'
```

without explicitly passing my native target
```
$ cargo test --doc
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Doc-tests runtime-target-feature

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

```
$ rustc --version
rustc 1.20.0-dev (ec5c2e8fb 2017-06-20)
$ cargo --version
cargo 0.20.0-nightly (0d0f3baad 2017-06-13)
```

**Comment by ashleygwilliams** [comment]
thanks for filing @parched ! sorry that you are running into this, and appreciate the repro case. one thing we'll need to figure out here is whether this is being caused by cargo itself or by the "rust module loader" (not sure the official term, but hopefully you get the gist)

one way to figure this out *might be* to run `cargo build --verbose` to see what rust command cargo is generating, and see if they are different when the target is directly passed. also: does this issue happen when you run `cargo build` or only with `test --doc`? isolating that as well might be helpful.

sorry these aren't super clear directives, but hopefully this gives you an idea of where to start investigating and we'll take a look as well!

**Comment by parched** [comment]
Hi @ashleygwilliams, thanks for the pointers, yes it's only with `test --doc`. I ran with verbose and this is what I see
```
$ cargo test --doc --verbose --target=x86_64-unknown-linux-gnu
...
 Running `rustdoc --test /home/james/junk/cargo-dep-test/src/lib.rs --crate-name runtime_target_feature -L dependency=/home/james/junk/cargo-dep-test/target/x86_64-unknown-linux-gnu/debug/deps --extern runtime_target_feature=/home/james/junk/cargo-dep-test/target/debug/deps/libruntime_target_feature-98b7f9c74b1b8141.so --extern syn=/home/james/junk/cargo-dep-test/target/debug/deps/libsyn-e662069961d8f963.rlib`
```
vs
```
$ cargo test --doc --verbose
...
Running `rustdoc --test /home/james/junk/cargo-dep-test/src/lib.rs --crate-name runtime_target_feature -L dependency=/home/james/junk/cargo-dep-test/target/debug/deps --extern syn=/home/james/junk/cargo-dep-test/target/debug/deps/libsyn-e662069961d8f963.rlib --extern runtime_target_feature=/home/james/junk/cargo-dep-test/target/debug/deps/libruntime_target_feature-98b7f9c74b1b8141.so`
```

So looks like cargo is passing the wrong `-L dependency=...` in the first case. For `cargo build` it is the same, `.../target/debug/...` for both cases.

**Comment by parched** [comment]
Looks like there probably needs to be a similar fix like https://github.com/rust-lang/cargo/commit/a298346d6e8862992be3fd93dd8a6c833cc72719 that @alexcrichton made but applied to [cargo_test.rs](https://github.com/rust-lang/cargo/blob/c7de4859275fe6fc0c1fc3af4ed4f03adeb87cc4/src/cargo/ops/cargo_test.rs#L147).
