### ISSUE TITLE
Parallel building with cargo potentially fails on DragonFly

### ISSUE THREAD

**Issue by mneumann** [rust-lang/cargo#4232]
Is there an option to turn off parallel jobs in cargo? This is somehow broken in DragonFly for yet unknown reasons. When cargo starts two or more "rustc" processes, they will die and cargo will hang forever (not sure if this happens always or only randomly). I hacked cargo in a way to basically disable the job queue, and then these hangs won't happen at all. I think the issue is not with cargo but with rustc or llvm.

**Comment by alexcrichton** [comment]
Does `-j1` help?

**Comment by mneumann** [comment]
yes! thank you.
