### ISSUE TITLE
cargo no std output on windows

### ISSUE THREAD

**Issue by gaganjyot** [rust-lang/cargo#4233]
Cargo doesn't return anything to cmd or powershell. I've installed git bash on windows and there it works perfectly.

Cargo version: cargo 0.21.0-nightly (50b1c24d1 2017-06-17)
OS: Windows 10

**Comment by alexcrichton** [comment]
Thanks for the report! I think this was a bug that was fixed recently, mind updating Cargo and seeing if it works?

**Comment by gaganjyot** [comment]
Hi. It works but I think it displays linux bash style output on windows as well.

?[m?[m?[31m?[1merror:?[m could not find `Cargo.toml` in `C:\Users\singhgag` or any parent directory

where as on bash it displays error in red color

**Comment by alexcrichton** [comment]
What shell are you invoking Cargo in? What's the value of your `TERM` environment variable?

**Comment by gaganjyot** [comment]
Oh Mistake. I was using hyper that gives this error. Thankyou :) I'll close the issue.
