### ISSUE TITLE
Cargo doesn't cache build script dependencies when cross-compiling

### ISSUE THREAD

**Issue by vmchale** [rust-lang/cargo#4235]
As it stands, my [project](https://github.com/vmchale/tin-summer) has a build script, and I would like to be able to cross-compile it so I can make binaries for various platforms. 

However, if I run

```
cargo build --release
cargo build --target=x86_64-pc-windows-gnu --release
```

and try to run `cargo build --release` again, it rebuilds all of `build.rs`'s dependencies. In my case this rebuilds clap unnecessarily, which takes a long time. The issue goes away when I get rid of `build.rs` and take the relevant sections out of my `Cargo.toml`.

Thanks!

**Comment by alexcrichton** [comment]
Is `clap` a build dependency? It looks like the main crate, `tin-summer`, has the build script disabled. Is there another location where a build dependency is getting introduced?

**Comment by vmchale** [comment]
Yes, I disabled it in order to get cross-platform builds working quickly. Past releases such as [this](https://github.com/vmchale/tin-summer/releases/tag/1.6.0) should still show the problem reproducibly.

Thanks.

**Comment by alexcrichton** [comment]
I think that's because `clap` is in `[dependencies]` and `[build-dependencies]`, right?

**Comment by vmchale** [comment]
Well, yes, but if you remove it from either `[dependencies]` or `[build-dependencies]`, it stops working.

**Comment by alexcrichton** [comment]
Ah sorry so my point was that there' sno way for Cargo to cache the dependency here. The command `cargo build --target x86_64-pc-windows-gnu` needs the `clap` crate compiled for Windows, which the previous step didn't generate.

**Comment by carols10cents** [comment]
This sounds like there's no way for us to fix this, since the dependency is needed for both build and dev, which means it's needed for both platforms.
