### ISSUE TITLE
cargo bench --no-run uses release profile

### ISSUE THREAD

**Issue by joliss** [rust-lang/cargo#4240]
I have the following snippet in my `Cargo.toml`:

```
[profile.bench]
debug = true # for profiling
```

However, when I run `cargo bench --no-run`, the binary that is placed in
`target/release/benches-*` does not seem to contain debug information.

Only when I add the following snippet do I get debug information:

```
[profile.release]
debug = true
```

**Comment by alexcrichton** [comment]
cc @matklad, more oddness with profiles!

**Comment by anderejd** [comment]
@joliss Thank you!! My blood pressure were approaching rage quit levels here right before finding this 😆 

For me no matter what combination of profile flags I try I can't get dtrace to produce stack information in combination with `cargo bench --no-run`.

I'm on stable Rust 1.29.1 in combination with [Criterion](https://github.com/japaric/criterion.rs).

Removing `--no-run` and having at least one criterion benchmark execute normally before trying to launch the benchmark executable from dtrace does provide a workaround.

**Comment by ehuss** [comment]
@alexcrichton I hadn't really thought of it, but it does seem surprising that *dependencies* use dev/release profiles even when benching/testing.  Is that really intended?

@anderejd I'm surprised that `--no-run` makes any difference, as all that does is avoid running the executable. Can you provide a sample project and a list of steps to run dtrace to exhibit the lack of stack information?

**Comment by alexcrichton** [comment]
@ehuss I believe that was done historically to ensure that `cargo build` followed by `cargo test` didn't recompile everything, although the way of using entirely different profiles was probably a big enough hack that it wasn't really that necessary at the time and is a bit too codified now :(

**Comment by LightAndLight** [comment]
This is the closest thing I could find to my current problem.

Running `cargo bench` with
```
[profile.bench]
debug = true
```
produces bench binaries without debug symbols.

Running `cargo bench` with
```
[profile.release]
debug = true
```
produces bench binaries *with* debug symbols.

I'm using `perf record -g` to observe the (lack) of debug symbols.
