### ISSUE TITLE
Doccomments for `pub use` statements should document the type

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/cargo#4250]
In `nix` we're aliasing the `libc::termios` type using `pub use libc::termios as Termios`. That type has no documentation in `libc`, but we'd like to offer documentation for the type in our own crate. Specifying a doc comment above it doesn't support anything in the output. It'd be very useful if you could override documentation when aliasing types.

**Comment by alexcrichton** [comment]
I think this is a rustdoc bug, right? If so mind moving this to rust-lang/rust?

**Comment by Susurrus** [comment]
Sure, sorry about this. I keep forgetting rustdoc is separate.
