### ISSUE TITLE
Tilde (~) expansion in paths like build target-dir

### ISSUE THREAD

**Issue by dbr** [rust-lang/cargo#4253]
If I specify `target-dir` using a tilde like `~/example` I would expect it to be expanded to a directory named "example" in my home directory - instead cargo treats it as a relative path to a directory literally named `~`

For example:

```
$ ls
Cargo.lock  Cargo.toml  src/
$ cat .cargo/config
[build]
target-dir = "~/blah_build"
$ cargo build
   Compiling blah v0.1.0 (file:///Users/dbr/blah)
    Finished dev [unoptimized + debuginfo] target(s) in 0.22 secs
$ ls
Cargo.lock  Cargo.toml  src/        ~/
$ ls ./~/blah_build/debug/
build/        deps/         examples/     incremental/  libblah.d     libblah.rlib  native/
$ cargo version
cargo 0.19.0 (28d1d60d4 2017-05-16)
```

**Comment by alexcrichton** [comment]
Thanks for the report! Expansion of `~` is typically done by the shell, however, and other programs would have to explicitly add support for it otherwise. It's possible to implement this perhaps in Cargo itself, but I'd personally prefer not to (sort of muddies the meaning of `~`)

**Comment by nodakai** [comment]
Perhaps we can just delegate to external crates such as

* https://crates.io/crates/shellexpand

**Comment by dbr** [comment]
Alternatively, perhaps just handling `${HOME}/blah_build/` would be better than the shell-like tilde syntax?

**Comment by dwijnand** [comment]
@alexcrichton do we have precedences in cargo for anything akin to `${HOME}` in (no test suite) cargo?

This seems like a simple ticket, which we should either decide on a direction for resolving it or reject the idea and close it.

**Comment by alexcrichton** [comment]
@dwijnand not currently, and yeah I think let's close this as "won't implement for now"
