### ISSUE TITLE
Dynamic metadata

### ISSUE THREAD

**Issue by jeberger** [rust-lang/cargo#4258]
It would be nice if there was a way to specify package metadata dynamically (e.g. from a script or from `build.rs`).

The main reason would be to allow version to be determined automatically from the nearest VCS tag instead of needing to duplicate the version number in the tag and the `Cargo.toml`. I already do this when developping in Python or C (see [here](https://bitbucket.org/jmb/dfl/src/a5a6dc213a5a597d74d380bf018651a8004d680b/setup.py?at=default&fileviewer=file-view-default#setup.py-16) for a Python example).

This should probably be discussed alongside issue #4221 which addresses a similar concern about avoiding duplicate metadata.

**Comment by carols10cents** [comment]
Similarly as #4221, I don't think this is something we're going to support in cargo itself since it could be implemented completely in an external script.
