### ISSUE TITLE
Print progress data for a slow git operation

### ISSUE THREAD

**Issue by antoyo** [rust-lang/cargo#4261]
Hello.
When I have this git dependency `https://github.com/dtolnay/syn`, `cargo update` hangs when trying to fetch it.
I waited 30 minutes without any progress.
I'm able to clone it manually with `git`.
Here's the log from `cargo update`:
```
TRACE:cargo::sources::git::source: updating git source `GitRemote { url: "https://github.com/dtolnay/syn" }`
INFO:cargo::sources::git::utils: update submodules for: "~/.cargo/git/checkouts/syn-6f4912dca572d3ab/0aa50e0/"
```
I don't know if it is related to the other issues mentionning a freeze.
Thanks to fix this issue.

**Comment by alexcrichton** [comment]
I think this is just a case of libgit2 doing a slow clone. The `syn` repo has a submodule to rust-lang/rust, which takes a long time to clone.

**Comment by antoyo** [comment]
It seems this is it.
Should we provide some output so that the users know that something is happening when it's very slow?

**Comment by alexcrichton** [comment]
Certainly yeah!

**Comment by antoyo** [comment]
I think we can close this issue as `cargo` now shows a progress bar.
