### ISSUE TITLE
Default exclude list for cargo --new

### ISSUE THREAD

**Issue by behnam** [rust-lang/cargo#4262]
It recently came up that cargo packages are not expected to publish tests, in addition to other development-related materials. (<https://github.com/servo/unicode-bidi/issues/43>)

So, the question is shouldn't `cargo --new` have the `exclude` list already populated with `test/*`, `banches/*`, etc?

Having it would make publishing new crates faster by helping newcomers with getting it right easier and learning what needs to be done for publishing.

What do you think?

**Comment by steveklabnik** [comment]
> It recently came up that cargo packages are not expected to publish tests, 

I think that's a bit strong. I've never heard of anyone doing this.

**Comment by behnam** [comment]
Cool! So the original assumption here was my misunderstanding of the common practices. Do you think it's worth mentioning this somewhere in the docs? Where would be a good place for it?If so, I can try submitting a PR for that. Otherwise, we can just close this then.

**Comment by alexcrichton** [comment]
I'm always fine with mentioning stuff in the docs, although I don't know offhand where this'd go. Somewhere in `src/doc` most likely, so feel free to throw it in there if you find an appropriate place.

**Comment by behnam** [comment]
I'm going to write up a sentence for this section: http://doc.crates.io/crates-io.html#before-publishing-a-new-crate

**Comment by alexcrichton** [comment]
👍
