### ISSUE TITLE
`cargo install --git` ignores Cargo.lock

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang/cargo#4263]
cargo version: `cargo 0.21.0-nightly (4c0a8b63d 2017-06-27)`

It seems that currently `cargo install --git`( `cargo install` doesn't have this issue ) ignores `Cargo.lock` by default.

Example project here would be [`ripgrep`](https://github.com/BurntSushi/ripgrep).
Running this command:
```
RUSTFLAGS="-C target-cpu=native" cargo +nightly install --git https://github.com/BurntSushi/ripgrep.git --features 'simd-accel avx-accel'
```
will result in `clap` being picked with the version `2.25.0`, which could of been a breaking API change, compared with the one included in `Cargo.lock`.

If I clone the repo and build the project myself:
```
RUSTFLAGS="-C target-cpu=native" cargo +nightly build --release --features 'simd-accel avx-accel'
```
`clap v2.24.1` is being picked-up from `Cargo.lock`.

**Comment by epage** [comment]
This looks to be a subset of #7169  which has a lot more discussion.  Closing in favor of that.  If there was something I overlooked, let us know!
