### ISSUE TITLE
cargo publish timeouts always

### ISSUE THREAD

**Issue by hasufell** [rust-lang/cargo#4264]
Followed all instructions from http://doc.crates.io/crates-io.html and created a token etc.

Cargo version is `cargo 0.21.0-nightly (abf01e1ed 2017-06-25)`. Also tried with stable, fails in the same way.

```
jule@localhost ~/git/rust-libnotify-sys $ cargo publish 
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging libnotify-sys v0.5.0 (file:///home/jule/git/rust-libnotify-sys)
   Verifying libnotify-sys v0.5.0 (file:///home/jule/git/rust-libnotify-sys)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling bitflags v0.8.2
   Compiling pkg-config v0.3.9
   Compiling libc v0.2.26
   Compiling gtypes v0.2.0
   Compiling libnotify-sys v0.5.0 (file:///home/jule/git/rust-libnotify-sys/target/package/libnotify-sys-0.5.0)
   Compiling gio-sys v0.3.4
   Compiling glib-2-0-sys v0.46.4
   Compiling gobject-2-0-sys v0.46.4
   Compiling gobject-sys v0.3.4
   Compiling gdk-pixbuf-sys v0.3.4
   Compiling glib-sys v0.3.4
    Finished dev [unoptimized + debuginfo] target(s) in 12.95 secs
   Uploading libnotify-sys v0.5.0 (file:///home/jule/git/rust-libnotify-sys)
error: [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
```

I don't see any useful way to debug this. It basically doesn't tell me anything, where the error happens, why etc.

**Comment by alexcrichton** [comment]
cc @carols10cents do you know if crates.io had any hiccups over the weekend?

**Comment by carols10cents** [comment]
I saw H28 Client Connection Idle errors in the logs around the time that @hasufell reported this in IRC, but I didn't see any systemic hiccups. This sounds similar to the issue we had reported to help@crates.io from Dennis April 8/9, but I don't think we ever figured that out.

**Comment by aepsil0n** [comment]
I have the same issue. I can't publish anything, although I am on a stable connection (I can browse crates.io without issue, anyway.) I'm using `cargo 0.18.0`.

**Comment by aepsil0n** [comment]
I have the same issue. I can't publish anything, although I am on a stable connection (I can browse crates.io without issue, anyway.) I'm using `cargo 0.18.0`.

**Comment by aepsil0n** [comment]
As mentioned in rust-lang/rust#43658, my problem vanished when I switched to another wifi. So perhaps it was just a network issue of some sort.

**Comment by hasufell** [comment]
Problem didn't vanish here. Still the same, reproducible on 2 machines.

**Comment by jan-hudec** [comment]
Seen this today and it was clearly problems somewhere between the ISP and S3. On different internet connection it didn't happen.

It would help if cargo printed the URLs and addresses it's trying to download from in verbose mode so one can diagnose it with curl, traceroute and similar tools.

**Comment by bgermann** [comment]
I get the same error. If I set a larger timeout, the following error is printed:

error: failed to get a 200 OK response, got 499
headers:
	HTTP/1.1 100 Continue	



	HTTP/1.1 499 Client Disconnected

	Connection: keep-alive

	Server: Cowboy

	Date: Sat, 17 Feb 2018 21:17:07 GMT

	Content-Length: 506

	Content-Type: text/html; charset=utf-8

	Cache-Control: no-cache, no-store

	

body:
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

**Comment by bgermann** [comment]
I am on a Dual-Stack Lite Internet connection. [Heroku is IPv4-only](https://bbs.archlinux.org/viewtopic.php?id=214012). I guess this could be the cause.
