### ISSUE TITLE
Have `--verbose` print `curl` commands for the network requests cargo is doing

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#4265]
I realize this is probably nontrivial and error-prone in itself, but there are a number of times that it would be useful to see what network requests cargo is doing in a manner that would be easy to copy-paste and take cargo out of the equation for debugging purposes.

**Comment by alexcrichton** [comment]
We don't really have the ability to do this as this isn't how it's modeled internally really. I suppose we could print out more specifics about what's happening though?

**Comment by carols10cents** [comment]
Yeah, if there's some other way to get libcurl to print out more about what it's doing when cargo gets `--verbose`, that would be sufficient, I suppose.

**Comment by epage** [comment]
I'm going to assume this predates [`http.debug`](https://doc.rust-lang.org/cargo/reference/config.html#httpdebug).  If there is a reason to keep this open, let us know!
