### ISSUE TITLE
`cargo install` does not honour alternate `cargo` installation directory

### ISSUE THREAD

**Issue by RandomInsano** [rust-lang/cargo#4271]
Hopefully I'm not duplicating an issue here, did a quick search. Jist is `cargo install` should put binaries next to `cargo` instead of a hard-coded directory.

This problem comes up because I'm using Bash for Windows with Rust for some Linux cross-compiling work and also happen to have my $HOME set to "/mnt/c/Users/<username>/" because that makes me happy. This config means that "~/.cargo" is filled with Linux binaries at the moment, and the Windows bins live elsewheres.

I installed using the standalone installer to "C:\Program Files\Rust stable MSVC 1.18\bin" and that's working fine. I managed to get `rust install racer` to build and be happy. However, it didn't place it in "Program Files" and instead went into "~/.cargo/bin".

**Comment by matklad** [comment]
Hm, shouldn't this be handled by `cargo install --root` option? 

I think that installing alongside cargo binary by default won't work really well: Cargo can be installed to a system partition, so to put files there, cargo will need root/administrator privileges.

**Comment by RandomInsano** [comment]
This '--root' magic will work nicely. RTFM strikes again!
