### ISSUE TITLE
cargo inserts an empty path in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#4277]
This causes lookup to check the working directory which is not good.

cc rust-lang/rust#42851

**Comment by jmesmon** [comment]
Introduced by "[784d3154cf084e6bbd49200d3e6e71df6c9cdca2] set dylib path correctly for target when running `cargo test` etc"  #4006 

cc: @mcgoo @alexcrichton 

test:
```
extern crate cargotest;
extern crate hamcrest;

use cargotest::support::{execs, project};
use hamcrest::assert_that;

#[test]
fn build_with_fake_libc_not_loading() {
    let p = project("foo")
        .file("Cargo.toml", r#"
            [package]
            name = "foo"
            version = "0.0.1"
            authors = []
        "#)
        .file("src/main.rs", r#"
            fn main() {}
        "#)
        .file("src/lib.rs", r#" "#)
        .file("libc.so.6", r#""#);

    assert_that(p.cargo_process("build"), execs().with_status(0));
}
```

**Comment by mbrubeck** [comment]
#4006 added lines like [this](https://github.com/mcgoo/cargo/blob/d773d7bb9391f1bdab442a070235ac2acb4adbb3/src/cargo/ops/cargo_rustc/compilation.rs#L110):

```rust
 search_path.push(self.host_dylib_path.iter().collect());
```

where `search_path` is a `Vec<PathBuf>` and `self.host_dylib_path` is an `Option<PathBuf>`.  If `self.host_dylib_path` is set to `None` then this will push an empty path into the search path.
