### ISSUE TITLE
How to get zsh completions?

### ISSUE THREAD

**Issue by cbcoutinho** [rust-lang/cargo#4284]
I see that there are some shell completions for bash and zsh in src/etc/, but I'm not sure how to generate them.

I could just copy/paste them from github - is that current MO?

Thanks for the great tool

**Comment by alexcrichton** [comment]
I think they should in theory be installed with Rust by default, but I'm also not entirely sure we plumb it through correctly everywhere. How'd you install Rust?

**Comment by cbcoutinho** [comment]
I installed rust using rustup. IIUC, rustup has its own shell completion script, which I have used without an issue. I'm using zsh, which means I should just have to execute the following [0]:

`> rustup completions zsh > ~/.zfunc/_rustup`

[0] https://github.com/rust-lang-nursery/rustup.rs#enable-tab-completion-for-bash-fish-or-zsh

**Comment by alexcrichton** [comment]
Ah so in the case you're using rustup I believe the cargo zsh completions are located at `$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/zsh/site-functions`, and yeah unfortunately `rustup completions` I don't think includes the cargo completions.

**Comment by cbcoutinho** [comment]
Ok got it - thanks for the quick reply. I'll just copy it manually for now.

BTW: there's a typo in `../share/zsh/site-functions/_cargo` at around line 513 (at least that's where it is on my system):

```
# These flags are **mutally** exclusive specifiers for the scope of a command; as
# they are used in multiple places without change, they are expanded into the
# appropriate command's `_arguments` where appropriate.
set command_scope_spec
command_scope_spec=(
```

should be:
```
# These flags are **mutually** exclusive specifiers for the scope of a command; as
# they are used in multiple places without change, they are expanded into the
# appropriate command's `_arguments` where appropriate.
set command_scope_spec
command_scope_spec=(
```

I can't find this file anywhere, otherwise I would submit a PR. Let me know if I can help...

**Comment by cbcoutinho** [comment]
Found it. Typo fixed in #4286

**Comment by TirtharajPramanik** [comment]
If you are using `ohmyzsh` just enable the `plugins=(... rust)` in .zshrc. It comes with default.

**Comment by bkane-msft** [comment]
I installed the rustup completions for cargo (`rustup completions zsh cargo > ~/fbin/_cargo`), but the completions are pretty basic. 

Does anyone know if there's an issue I can follow for smarter completions?

For example, my project looks like:

```
$ tree .
.
├── Cargo.lock
├── Cargo.toml
└── src
    └── bin
        ├── main.rs
        └── main2.rs

3 directories, 4 files
```

I would like `cargo run --bin=` to tab complete to `main` or `main2`, but it doesn't currently.

**Comment by weihanglo** [comment]
@bkane-msft we have a unstable feature [native-completions](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#native-completions) that generates shell completion through cargo. That does give us smarter completions as it can hook into Cargo internals. We are calling for testing for it now, please help test and give feedback.


@rustbot note native-completion-call-for-testing

**Comment by bkane-msft** [comment]
Hmm I couldn't get that working, but it's quite likely I need to clear my completion cache. I'll fiddle with it when I have more time.
