### ISSUE TITLE
Impact of adding a `[[test]]` section isn't documented.

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#4290]
In `liquid-rust`, I added a `[[test]]` to specify the needed features to run the tests.  It turns out I didn't set this up correctly, but more of issue is the fact that it [disabled all of the implicit `[[test]]` targets](https://github.com/cobalt-org/liquid-rust/issues/128) without the [documentation](http://doc.crates.io/manifest.html#integration-tests) giving any hint that this will happen.

**Comment by dwijnand** [comment]
While still not documented, the impact at least triggers a runtime lint-like warning with https://github.com/rust-lang/cargo/issues/5330 shipped.

**Comment by ehuss** [comment]
Adding a target definition no longer disables implicit targets with the 2018 edition.

More documentation has been added for this #6898 (https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#target-auto-discovery), so closing as fixed.
