### ISSUE TITLE
Upload size limit on READMEs

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/cargo#4291]
This is currently being [done by npm](http://blog.npmjs.org/post/153186129005/zero-one-infinity-readmes), one of the reasons why is to stop a potential attack vector where an malacious third party could upload a very large README file and gum up crates.io. There are ways to deal with this on the crates.io side, but this could be an interim measure while we figure this out.

**Comment by est31** [comment]
crates.io doesn't display READMEs in any way so I don't see how this could be an issue for crates.io. Maybe there needs to be a limit on the description string or other strings though.

**Comment by vignesh-sankaran** [comment]
There is an open PR for [displaying READMEs](https://github.com/rust-lang/crates.io/pull/869), and READMEs are currently being stored in the database.

**Comment by epage** [comment]
We have some zip comb protection as of #11089 + #11337.  This will limit how big of an overall `.crate` there is.

As for whether `README.md` size is a concern, I'd want to hear from crates.io.  @Turbo87 any thoughts on how we should triage this?

**Comment by Turbo87** [comment]
we have a server-side limit on the size of the metadata json blob, which restricts the size of the readme to some degree. we don't have a restriction specifically for the readme, but once we read it from the tarball we should probably implement something like that.

**Comment by epage** [comment]
Sounds like this is being resolved on the server side, so I'm going to close this out for cargo's side.  If there is a reason this should be enforced on the client side uniformly across all registries, let us know!
