### ISSUE TITLE
confusing path to main.rs in warning, while inside a workspace

### ISSUE THREAD

**Issue by xftroxgpx** [rust-lang/cargo#4293]
`cargo run` inside pwd dir `/home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/rust_books/1_first_edition/closures/`

Original warning:
```
warning: path `src/main.rs` was erroneously implicitly accepted for binary `match`,
please set bin.path in Cargo.toml
```
There's a `match` project/binary in `/home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/rust_books/1_first_edition/match`

But the actual path( [`legacy_path`](https://github.com/rust-lang/cargo/blob/7e00b82d96d3b78241e2b95acdecb28551813b15/src/cargo/util/toml/targets.rs#L179)) is:
`/home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/rust_oddities/variable_shadowing_in_match/src/main.rs`

So, expected warning would be, perhaps:
```
warning: path `rust_oddities/variable_shadowing_in_match/src/main.rs` was erroneously implicitly accepted for binary `match`,
please set bin.path in Cargo.toml
```

Ok, so this happened because `Cargo.toml` in both projects has:
```toml
[[bin]]

name = "match"
```
even though the `package`'s `name=` is different.

This happens in a `[workspace]` where [`rustlearnage/Cargo.toml`](https://github.com/xftroxgpx/rustlearnage/blob/3c11c584bb1dc290a9a05138117bd6e1f2ba2278/Cargo.toml) is the root.

The fix in my above case was to ensure there are no duplicately named binaries (renamed one to `match0`)

The fix for cargo though, I'm unsure. Perhaps [`let short_path = without_prefix(&legacy_path, package_root)`](https://github.com/rust-lang/cargo/blob/7e00b82d96d3b78241e2b95acdecb28551813b15/src/cargo/util/toml/targets.rs#L181) could become `let short_path = without_prefix(&legacy_path, workspace_root)` where `workspace_root` is somehow defined properly, in my case would be `/home/xftroxgpx/build/2nonpkgs/rust.stuff/rustlearnage/`

**Comment by matklad** [comment]
Yeah, that is definitely a confusing error! I think adding those [short paths](https://github.com/rust-lang/cargo/blob/13cf358d5b7c3e2b18a3eac1ce892d971081b323/src/cargo/util/toml/targets.rs#L109-L110) did more harm then good. We should use full `legacy_path` instead: this error message is rather niche, so it's much more important to be unambiguous rather then concise.

Wanna tackle this as well, @xftroxgpx?  If you do, you might need to use `[..]` in tests, like this:

```
[WARNING] path `[..]src[/]bench.rs` was erroneously implicitly accepted for benchmark `bench`,
```

`[..]` matches any string, which is important for things like paths, which differ between CI servers.

**Comment by xftroxgpx** [comment]
Yeah I'd like to try. Thank you!

**Comment by lilianmoraru** [comment]
@matklad I don't understand why this message has to appear in obvious situations.
Having to add the exact same boilerplate to every member project seems wrong(we already have the convention: bin == `src/main.rs`, lib == `src/lib.rs`, why do we have to fallback to explicitness...).

Example from Habitat:
For this [`Cargo.toml`](https://github.com/habitat-sh/habitat/blob/79609f417deb29e852d46776b5986567b16dc599/components/builder-admin/Cargo.toml#L9), you get:
```
warning: path `/home/lilian/git/habitat/components/builder-admin/src/main.rs` was erroneously implicitly accepted for binary `bldr-admin`,
please set bin.path in Cargo.toml
```

And this warning appears for every single member listed here: https://github.com/habitat-sh/habitat/blob/master/Cargo.toml

**Comment by xftroxgpx** [comment]
Looks to me that the message appears due to the existence of `-` in the bin name. 
eg. `bldr-admin` instead of `bldr_admin`
and I'm unsure if this is intended or valid.
<details>
(I actually checked this on my [own project](https://github.com/xftroxgpx/rustlearnage/blob/c6a4788d512ffafe46894252c2170b5378beb5fd/rust_books/1_first_edition/hello_world/Cargo.toml#L9), where I get no such errors, by modifying `name = "hello_world"` to `name = "hello-world"` and seeing the error message appear, then doing the reverse to see the error disappear)
</details>

----------

In the `habitat` case, these are all the bin names (I added an `//X` to each to show which are actually reported in the error message):
```bash
$ find . -iname Cargo.toml -exec grep -nHF -A1 -- "[[bin]]" {} \;|awk -e '/name = / { print $3 }'|sort
"bldr-admin" //X
"bldr-api" //X
"bldr-depot" //X
"bldr-graph" //X
"bldr-job-srv" //X
"bldr-origin-srv" //X
"bldr-router" //X
"bldr-scheduler" //X
"bldr-session-srv" //X
"bldr-worker" //X
"butterfly" //X
"eventsrv"
"eventsrv-client"
"hab"
"hab-butterfly"
"hab-launch" //X
"hab-sup" //X
"subscriber"
```

<details>

<summary>
actual error messages
</summary>

```rust
warning: path `/tmp/habitat/components/builder-admin/src/main.rs` was erroneously implicitly accepted for binary `bldr-admin`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-api/src/main.rs` was erroneously implicitly accepted for binary `bldr-api`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-depot/src/main.rs` was erroneously implicitly accepted for binary `bldr-depot`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-graph/src/main.rs` was erroneously implicitly accepted for binary `bldr-graph`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-jobsrv/src/main.rs` was erroneously implicitly accepted for binary `bldr-job-srv`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-scheduler/src/main.rs` was erroneously implicitly accepted for binary `bldr-scheduler`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-router/src/main.rs` was erroneously implicitly accepted for binary `bldr-router`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-sessionsrv/src/main.rs` was erroneously implicitly accepted for binary `bldr-session-srv`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-originsrv/src/main.rs` was erroneously implicitly accepted for binary `bldr-origin-srv`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/builder-worker/src/main.rs` was erroneously implicitly accepted for binary `bldr-worker`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/launcher/src/main.rs` was erroneously implicitly accepted for binary `hab-launch`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/sup/src/main.rs` was erroneously implicitly accepted for binary `hab-sup`,
please set bin.path in Cargo.toml
warning: path `/tmp/habitat/components/butterfly/src/main.rs` was erroneously implicitly accepted for binary `butterfly`,
please set bin.path in Cargo.toml

```
</details>

For some reason, the `butterfly` bin name is also reported in the errors above. Yet `hab-butterfly` bin name is not. They must be somehow related to each other!
There's `eventsrv-client` which isn't reported, which might be related to the existance of `eventsrv` bin.
So there's definitely some inconsistency issue here, if not just some kind of bug based on the `-` existing in the bine name. I'll look more into it...

**Comment by matklad** [comment]
@lilianmoraru this is  intentional, but perhaps there is more tweaking to be done here.

So, the binary in Cargo is defined by two things: its crate root file, and its name (`path` and `name` attributes from Cargo.toml). You can specify only the `name` in your `Cargo.toml`, and then Cargo would infer path for you. 

Previously, the inference would fall back to a default `src/main.rs`, if there's no more explicit `src/bin/name.rs`. This implicit fallback was problematic, because, for example, to binaries with different names might happen to fallback to the same file. 

The new scheme removes the fallback behavior. Instead, if you specify only `name`, then the binary files must be either `src/bin/name.rs`, `src/bin/name/main.rs` or `src/main.rs` if the `name` is the same as the name of the package. 

The possible solutions are:

* restore the previous behavior

* do nothing, and fix the warnings downstream

* add a special case logic along the lines of "if there's a single bin only, use src/main.rs regardless of the name".

I lean to the second solution at the moment. While the third one seems very compelling, I don't like that adding a second binary to your `Cargo.toml` is not purely additive and requires changing configuration for the first binary as well.

**Comment by xftroxgpx** [comment]
I was wrong in my assumptions of my previous post.
What actually happens is what Matt said:
> src/main.rs if the name is the same as the name of the package.

That is,
If the `bin` name is different than `name` of package, then you get that warning!
Example:
Cargo.toml contains:
```toml
[package]                                                                       
name = "habitat_builder_admin"
[[bin]]
name = "bldr-admin"
```
Thus the bin name is different than package name => you get that warning:
```
warning: path `/tmp/habitat/components/builder-admin/src/main.rs` was erroneously implicitly accepted for binary `bldr-admin`,
please set bin.path in Cargo.toml
```

<details>

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! bin=TomlTarget { name: Some("`bldr-admin`"), crate_type: None, crate_type2: None, path: None, test: None, doctest: None, bench: None, doc: Some(false), plugin: None, proc_macro: None, proc_macro2: None, harness: None, required_features: None } inferred=[("`habitat_builder_admin`", "/tmp/habitat/components/builder-admin/src/main.rs")]
!! legacy_bin_path, package_root="/tmp/habitat/components/builder-admin", name="bldr-admin", has_lib=true
!! path="/tmp/habitat/components/builder-admin/src/main.rs"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!EOF
</details>

And it doesn't matter whether the package-root is or isn't different than the package name.
Example, Cargo.toml
```toml
[package]
name = "hab-butterfly"
[[bin]]
name = "hab-butterfly2"
```

You get the warning:

```
warning: path `/tmp/habitat/components/hab-butterfly/src/main.rs` was erroneously implicitly accepted for binary `hab-butterfly2`,
please set bin.path in Cargo.toml
```

<details>

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! bin=TomlTarget { name: Some("`hab-butterfly2`"), crate_type: None, crate_type2: None, path: None, test: None, doctest: None, bench: None, doc: Some(false), plugin: None, proc_macro: None, proc_macro2: None, harness: None, required_features: None } inferred=[("`hab-butterfly`", "/tmp/habitat/components/hab-butterfly/src/main.rs")]
!! legacy_bin_path, package_root="`/tmp/habitat/components/hab-butterfly`", name="hab-butterfly2", has_lib=true
!! path="/tmp/habitat/components/hab-butterfly/src/main.rs"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!EOF
</details>

<details>

<summary>
patch used for the output in Details
</summary>

```patch
diff --git a/src/cargo/util/toml/targets.rs b/src/cargo/util/toml/targets.rs
index 70b84f81..5de1db06 100644
--- a/src/cargo/util/toml/targets.rs
+++ b/src/cargo/util/toml/targets.rs
@@ -169,7 +169,9 @@ fn clean_bins(toml_bins: Option<&Vec<TomlBinTarget>>,
     validate_unique_names(&bins, "binary")?;
 
     let mut result = Vec::new();
+    eprintln!("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
     for bin in bins.iter() {
+        eprintln!("!! bin={:?} inferred={:?}", bin, inferred);
         let path = target_path(bin, &inferred, "bin", package_root, &mut |_| {
             if let Some(legacy_path) = legacy_bin_path(package_root, &bin.name(), has_lib) {
                 warnings.push(format!(
@@ -186,15 +188,18 @@ fn clean_bins(toml_bins: Option<&Vec<TomlBinTarget>>,
             Ok(path) => path,
             Err(e) => bail!("{}", e),
         };
+        eprintln!("!! path={:?}", path);
 
         let mut target = Target::bin_target(&bin.name(), path,
                                             bin.required_features.clone());
         configure(bin, &mut target);
         result.push(target);
     }
+    eprintln!("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!EOF");
     return Ok(result);
 
     fn legacy_bin_path(package_root: &Path, name: &str, has_lib: bool) -> Option<PathBuf> {
+        eprintln!("!! legacy_bin_path, package_root={:?}, name={:?}, has_lib={}", package_root, name, has_lib);
         if !has_lib {
             let path = package_root.join("src").join(format!("{}.rs", name));
             if path.exists() {
```
</details>
