### ISSUE TITLE
cache result of call include! (and may be other include_*!)

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/cargo#4294]
I use code generation and execute it from `build.rs`.
To include the result of code generation I use 
```rust
include!(concat!(env!("OUT_DIR"), "/code.rs"));
```
the problem is that even if I change nothing in crate,
it rebuild from scratch.

So I have:
```sh
$ cargo build && cargo build
 Finished release [optimized + debuginfo] target(s) in 30 secs
 Finished release [optimized + debuginfo] target(s) in 30 secs
```
Rebuild without any change take exactly the same amount of time as rebuild.

So I suppose it would be great to calc hash/or save modification date of `concat!(env!("OUT_DIR"), "/code.rs")`
and if hash not changed then do nothing.
At now I have to do it by myself in `build.rs`, but I think that it is general functionality,
that should be inside of `cargo`.

**Comment by alexcrichton** [comment]
Thanks for the report! Can you try rerunning with `RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info`? That should help diagnose why Cargo is rebuilding.

**Comment by Dushistov** [comment]
@alexcrichton 

Very strange, 
I use my crate [rust_swig](https://github.com/Dushistov/rust_swig) for code generation, and this crate with `rust` code generate also `java` code, 
and because of my mistake `java code` was updated every time,
and `cargo` rebuild crate because of java code update?

```sh
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for something-android v0.1.0 (file:///home/evgeniy/test): precalculated components have changed: 1500390446.231451330s (/home/evgeniy/test/app/src/main/java/net/akaame/something/core/NativeLogger.java) != 1500390417.428116995s (/home/evgeniy/test/app/src/main/java/net/akaame/something/core/NativeLogger.java)
INFO:cargo::ops::cargo_rustc::fingerprint:   cause: precalculated components have changed: 1500390446.231451330s (/home/evgeniy/test/app/src/main/java/net/akaame/something/core/NativeLogger.java) != 1500390417.428116995s (/home/evgeniy/test/app/src/main/java/net/akaame/something/core/NativeLogger.java)
   Compiling something-android v0.1.0 (file:///home/evgeniy/test)
    Finished release [optimized + debuginfo] target(s) in 26.55 secs
```

In fact I like this behaviour, but it is also very strange.
If you don't think that this is a bug, I want to close this issue?

**Comment by alexcrichton** [comment]
Ah yeah build scripts pessimistically assume that all files in a project can affect the output of a build script, but you can use `println!("cargo:rerun-if-changed=...")` to fix this!
