### ISSUE TITLE
Trouble making binary package with 'cargo new' and '--name'

### ISSUE THREAD

**Issue by 0joshuaolson1** [rust-lang/cargo#4296]
```
$ cargo new not_reserved --name --bin
     Created library `not_reserved` project
$ ls not_reserved/src
lib.rs
```

**Comment by xftroxgpx** [comment]
Cargo takes the arg after `--name` as the name of the project,
```bash
$ cargo new test --name --help
$ cat test/Cargo.toml |grep name
name = "--help"
```

```
$ cargo new --help
!! executing '/home/xftroxgpx/.cargo/bin/cargo' with args: 'new --help'
Create a new cargo package at <path>

Usage:
    cargo new [options] <path>
    cargo new -h | --help

Options:
    -h, --help          Print this message
    --vcs VCS           Initialize a new repository for the given version
                        control system (git, hg, pijul, or fossil) or do not
                        initialize any version control at all (none), overriding
                        a global configuration.
    --bin               Use a binary (application) template
    --lib               Use a library template [default]
    --name NAME         Set the resulting package name, defaults to the value of <path>
    -v, --verbose ...   Use verbose output (-vv very verbose/build.rs output)
    -q, --quiet         No output printed to stdout
    --color WHEN        Coloring: auto, always, never
    --frozen            Require Cargo.lock and cache are up to date
    --locked            Require Cargo.lock is up to date
```

**Comment by 0joshuaolson1** [comment]
I see. This doesn't work either:
```
$ cargo new test --name test --bin
error: The name `test` cannot be used as a crate name
use --name to override crate name
```

**Comment by xftroxgpx** [comment]
My bad. I shouldn't have used `test` as path, because then you'll want to use it as `--name` but `--name` cannot use `test` (probably due to being a rust-lang reserved keyword or something)
>error: The name `test` cannot be used as a crate name


The first one works if not using the name `test` (can use the path `test` though):
```
$ cargo new test --name nottesthere --bin
Created binary (application) `test` project
$ grep name test/Cargo.toml
name = "nottesthere"
```

The second one only works if you specify the required arg `<path>` (and don't use the reserved word `test` in name)
This works:
```
$ cargo new --bin --name cantuse_test_here test
     Created binary (application) `test` project
$ grep name test/Cargo.toml
name = "cantuse_test_here"
```

**Comment by 0joshuaolson1** [comment]
I thought the point of --name was, according to
```
error: The name `test` cannot be used as a crate name
use --name to override crate name
```
, to override the crate name even though the name may be a reserved keyword?

**Comment by xftroxgpx** [comment]
Yep. Normally if you use `cargo new --bin test` the crate name is `test` and that's when you use `--name ` to
>to override the crate name even though the name may be a reserved keyword

This does that: `cargo new --bin --name cantuse_test_here test`
Now the overridden crate name is `cantuse_test_here` instead of `test`

You still can't use the reserved word even with `--name` though. If that's what you meant to say.

**Comment by 0joshuaolson1** [comment]
That's great. How can this be fixed? Please don't tell me the limitations of crates.io or crate importing have anything to do with one-off personal non-libraries.

**Comment by xftroxgpx** [comment]
>Please don't tell me the limitations of crates.io or crate importing have anything to do with one-off personal non-libraries.

They do not indeed. You can make your own local `rand` lib. You can even have `crates.io`'s [`rand`](https://crates.io/crates/rand) as its dependency, without conflicts.

However you can't use any of [these](https://github.com/rust-lang/cargo/blob/c3392142a74669deeddac3911292eaac93bf6783/src/cargo/ops/cargo_new.rs#L125-L135) keywords as crate name:
"abstract", "alignof", "as", "become", "box",
        "break", "const", "continue", "crate", "do",
        "else", "enum", "extern", "false", "final",
        "fn", "for", "if", "impl", "in",
        "let", "loop", "macro", "match", "mod",
        "move", "mut", "offsetof", "override", "priv",
        "proc", "pub", "pure", "ref", "return",
        "self", "sizeof", "static", "struct",
        "super", "test", "trait", "true", "type", "typeof",
        "unsafe", "unsized", "use", "virtual", "where",
        "while", "yield"

Additionally:
>Package names starting with a digit cannot be used as a crate name

Crate name must be composed of only [alphanumeric](https://github.com/rust-lang/cargo/blob/c3392142a74669deeddac3911292eaac93bf6783/src/cargo/ops/cargo_new.rs#L149-L155), `_` and  `-` chars.

If you ever intend to publish it on `crates.io` you might want to consider [this](https://github.com/rust-lang/cargo/blob/74e54214c9d13871934fde0ecb07250e523c4e92/src/doc/crates-io.md#before-publishing-a-new-crate).

**Comment by 0joshuaolson1** [comment]
Closing as implied wontfix.
