### ISSUE TITLE
Are the CARGO_CFG_* environment variables safe to use in build scripts?

### ISSUE THREAD

**Issue by bluetech** [rust-lang/cargo#4302]
Cargo exposes some `CARGO_CFG_*` environment variables to build scripts. Here are the ones from my machine:

```ini
CARGO_CFG_TARGET_FEATURE=sse,sse2
CARGO_CFG_TARGET_ENV=gnu
CARGO_CFG_TARGET_VENDOR=unknown
CARGO_CFG_TARGET_HAS_ATOMIC=16,32,64,8,ptr
CARGO_CFG_TARGET_THREAD_LOCAL=
CARGO_CFG_TARGET_ENDIAN=little
CARGO_CFG_TARGET_ARCH=x86_64
CARGO_CFG_UNIX=
CARGO_CFG_TARGET_POINTER_WIDTH=64
CARGO_CFG_DEBUG_ASSERTIONS=
CARGO_CFG_TARGET_OS=linux
CARGO_CFG_TARGET_FAMILY=unix
```

In my case, I want to use them instead of manually parsing `$TARGET`. It'd be better since I could use the same type of cfg conditions in the build script as in the code.

But these variables are not documented in http://doc.crates.io/environment-variables.html. Should they be? Or are they meant for internal use only and should not be relied upon?

Thanks.

(This was briefly mentioned in https://github.com/rust-lang/rfcs/pull/2048#issuecomment-312918883).

**Comment by alexcrichton** [comment]
Yes these are fine to rely on, they're just missing documentation.
