### ISSUE TITLE
`cargo package` in workspaces doesn't put artifacts in root `target` dir

### ISSUE THREAD

**Issue by behnam** [rust-lang/cargo#4304]
(Since `package` is part of the `publish` command, most of the following concerns also apply to `publish`.)

The current "Publishing on crates.io" doc doesn't have any content regarding workspaces: http://doc.crates.io/crates-io.html

Here's what the workspace RFC (and [The Manifest Format](https://github.com/rust-lang/cargo/issues/new)) say about build outputs:

> Whenever any crate in the workspace is compiled, output will be placed in the `target` directory next to the root `Cargo.toml`.

Now, if you `cd` to the directory of a member crate and execute `cargo package`, the package tarball is created in a `target` directory next to the member `Cargo.toml`, but not the root. It's not clear if `package` falls under this rule, or not, as it's not exactly *compiling*.

So, is this expected behavior for `cargo package`? If so, should we add a note about it to the docs?

Also worth noting is the fact that, when packaging, all the dependent package versions are expected to be available on crates.io. I think that's expected behavior, but it results in different behavior between `build`/`test` and `package`, where first ones pass easily if a dependency is not registered, but the latter fails with `no matching package named [...] found`. Do we need to have a note about this, also?

And, of course, there's the larger issue of `package` not supporting `--all`, which I assume is a KP, but haven't been able to find a tracker for it. I think if we intentionally want to not support `--all` for `package` (and `publish`), we better document it in the CLI and the docs.

**Comment by behnam** [comment]
Okay, found the tracker for `publish --all`: https://github.com/rust-lang/cargo/issues/2878#issuecomment-232999021

Also, should mention [this part from the RFC](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md#future-extensions):

> Once Cargo understands a workspace of crates, we could easily extend various subcommands with a --all flag to perform tasks such as:
> 
> * Test all crates within a workspace (run all unit tests, doc tests, etc)
> * Build all binaries for a set of crates within a workspace
> * Publish all crates in a workspace if necessary to crates.io

----

And, one clarification: even a command like this:

```bash
cargo package --manifest-path <path-to-member>/Cargo.toml
```

results in a `target` dir to be created at `<path-to-member>`, instead of workspace root.

I'm guessing that this is a separate issue from supporting `package --all`.

**Comment by alexcrichton** [comment]
Ah yeah the placement of `target` is just a bug here! Also I'd very much love to see support for `--all` in these commands!
