### ISSUE TITLE
Allow storing builds for multiple versions of Rust

### ISSUE THREAD

**Issue by clarfon** [rust-lang/cargo#4306]
I've tried to search for this and I think that this doesn't have an open issue.

Usually, whenever Rust is updated, everything is rebuilt from scratch, which makes sense. But this makes it harder to test multiple versions of Rust locally without losing all of the stuff that's already been compiled.

Essentially, I want to be able to run `rustup run stable cargo test` and `rustup run nightly cargo test` in sequence without having to rebuild everything every time I switch Rust versions. And while this could be something specific that `rustup` adds to the mix, I think that it would require support directly from cargo.

**Comment by matklad** [comment]
I wonder if sccache can help here: https://users.rust-lang.org/t/sccache-for-caching-rust-compilation/10960...

**Comment by ehuss** [comment]
The rustc version was added to the metadata hash in #4139, which keeps each build separate for each version, allowing you to seamlessly switch between versions.
