### ISSUE TITLE
Document how to use sccache with Cargo

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4307]
Looks like sccache can help quite a bit even with local development, when you are working on different projects, or when you are switching versions of the compiler (https://github.com/rust-lang/cargo/issues/4301 and https://github.com/rust-lang/cargo/issues/4306). 

However, it seems to me that nobody knows how to use sccache with Cargo, and that it even exists. At least, I certainly don't know how to set it up :) I guess I'll try to figure this out and write some docs. 

@luser are there any other existing docs besides https://users.rust-lang.org/t/sccache-for-caching-rust-compilation/10960 and readme at https://github.com/mozilla/sccache/?

**Comment by luser** [comment]
There's [a separate Rust doc](https://github.com/mozilla/sccache/blob/master/docs/Rust.md) linked from the README. It's pretty easy to use, though!

**Comment by alexcrichton** [comment]
The tl;dr; for Rust is:

```
$ cargo install sccache
$ export RUSTC_WRAPPER=sccache
# normal cargo commands here...
```

The `cargo install` step [doesn't quite work yet](https://github.com/mozilla/sccache/issues/153) but I suspect that'll get resolved soon.

**Comment by matklad** [comment]
So, `export RUSTC_WRAPPER=sccache` bit should go to bash_rc or the like? Perhaps this should be configurable via `~/.cargo/config`?

**Comment by alexcrichton** [comment]
Makes sense to me to add a configuration option for it!

**Comment by mqudsi** [comment]
I disagree about adding a configuration option for it, I think an environment variable is fine. However, when I do specify `RUSTC_WRAPPER`, cargo's `rustc` invocations are called via `sccache` as expected, however none of them result in hits as all the invocations come up as non-cacheable calls. I mean that at no point during a full day of rust development, crate installations, etc. etc. does `Cache hits` in `sccache -s` show anything other than zero.

**Comment by luser** [comment]
@mqudsi Interesting! If you run with `SCCACHE_ERROR_LOG=/tmp/sccache.log RUST_LOG=sccache=trace` you can get a lot of information about what sccache is doing. grep'ing the log for `CannotCache` is generally useful in these situations. If you want to post that here or email me, ted@mielczarek.org I'd be happy to take a look.

**Comment by mqudsi** [comment]
@luser thank you for your offer! 

I've attached the sccache trace to this comment. This was from the 4th or 5th subsequent (though ultimately failed) compilation of sccache itself. There are a lot of unhandled compiles, though I don't think there are enough of them to explain why each time I recompile sccache, my hit count only rises by 3.

[sccache.txt](https://github.com/rust-lang/cargo/files/1286183/sccache.txt)
