### ISSUE TITLE
SSL Connect Error with Cargo 0.21.0-nightly on Windows

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/cargo#4311]
I'm not really sure if this is Cargo's fault and it's probably already reported somewhere, but my Windows builds are failing today (see [here](https://ci.appveyor.com/project/KodrAus/elastic/build/1.0.156/job/6wy2t3e7e49uou5s) for example) with a complaint about a failed SSL connection when attempting to download a package.

I've got a Windows machine handy so am happy to quickly test anything if it'll help.

**Comment by alexcrichton** [comment]
Thanks for the report! This is due to http://help.appveyor.com/discussions/problems/7115-curl-cant-download-files-through-ssl and should be fixed upstream shortly.

In the meantime you can set `CARGO_HTTP_CHECK_REVOKE=false` to get past this.
