### ISSUE TITLE
exclude key of package section is ignored when submodule is involved

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/cargo#4319]
When the directory excluded is part of a git submodule (or even the submodule itself), `cargo package` will still include them in the generated crate file.

**Comment by alexcrichton** [comment]
cc @behnam

**Comment by BusyJay** [comment]
I made a mistake, I thought that cargo treat the path the same way as .gitignore, but it turns out it's treated as a globs pattern. Sorry for the carelessness.

**Comment by behnam** [comment]
Right, @BusyJay, at the moment we're matching them as glob patterns.

But, we are changing that behavior and want to stay as close to gitignore as possible. Please see these discussions for more info:
* https://github.com/rust-lang/cargo/pull/4297
* https://github.com/rust-lang/cargo/issues/4268
