### ISSUE TITLE
cargo test -q not works as expected

### ISSUE THREAD

**Issue by davemilter** [rust-lang/cargo#4325]
`cargo test --help` promise "-q, --quiet                  No output printed to stdout",
but `cargo test -q` and `cargo test` produce the same output to terminal.

**Comment by alexcrichton** [comment]
Thanks for the report! Could you gist the output that's getting printed as well?

**Comment by davemilter** [comment]
> Could you gist the output that's getting printed as well?

**cargo test**
```
> cargo new output && cd output
> cargo test
   Compiling output v0.1.0 (file:///tmp/output)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39 secs
     Running target/debug/deps/output-5d078bc893605b55

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests output

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
**cargo test -q**
```
> cargo test -q

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

I've expected not output at all from `cargo test -q`, or may be errors to stderr,
like `cargo test > /dev/null`

**Comment by alexcrichton** [comment]
Ah this is all output coming from the test harness in rust-lang/rust, which Cargo doesn't forward arguments like -q to righ tnow.
