### ISSUE TITLE
Manifest re-serialization in 'cargo package' is non-deterministic

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#4326]
In `Cargo.toml` files generated by `cargo vendor`, the order of dependencies seems not to be deterministic: when updating in Firefox a crate to a version that did not change the set of dependencies, I get a diff like below.

Could this be based on the iteration order of a `HashMap` that uses the default `RandomState` hasher? If so, what do you think of switching to a deterministic hasher? Or perhaps sorting before generating TOML files?

```diff
diff --git a/third_party/rust/cssparser/Cargo.toml b/third_party/rust/cssparser/Cargo.toml
index 76fadfd855e4..94e9f473274c 100644
--- a/third_party/rust/cssparser/Cargo.toml
+++ b/third_party/rust/cssparser/Cargo.toml
@@ -12,7 +12,7 @@
 
 [package]
 name = "cssparser"
-version = "0.18.0"
+version = "0.18.1"
 authors = ["Simon Sapin <simon.sapin@exyr.org>"]
 build = "build.rs"
 exclude = ["src/css-parsing-tests/**", "src/big-data-url.css"]
@@ -22,33 +22,33 @@ readme = "README.md"
 keywords = ["css", "syntax", "parser"]
 license = "MPL-2.0"
 repository = "https://github.com/servo/rust-cssparser"
-[dependencies.heapsize]
-version = ">= 0.3, < 0.5"
-optional = true
-
 [dependencies.serde]
 version = "1.0"
 optional = true
 
+[dependencies.heapsize]
+version = ">= 0.3, < 0.5"
+optional = true
+
 [dependencies.procedural-masquerade]
 version = "0.1"
 
-[dependencies.cssparser-macros]
-version = "0.3"
-
 [dependencies.matches]
 version = "0.1"
 
 [dependencies.phf]
 version = "0.7"
-[dev-dependencies.encoding_rs]
-version = "0.5"
+
+[dependencies.cssparser-macros]
+version = "0.3"
+[dev-dependencies.rustc-serialize]
+version = "0.3"
 
 [dev-dependencies.difference]
 version = "1.0"
 
-[dev-dependencies.rustc-serialize]
-version = "0.3"
+[dev-dependencies.encoding_rs]
+version = "0.5"
 [build-dependencies.syn]
 version = "0.11"
```

**Comment by alexcrichton** [comment]
Hm in theory `cargo vendor` should be deterministic. It looks like this is oscillating between 0.18.0 and 0.18.1, do you know why that might be happening?

**Comment by SimonSapin** [comment]
This was a changeset where I ran `cargo update -p cssparser` to update from 0.18.0 to 0.18.1, then ran `mach vendor rust` which calls `cargo vendor`. The change to the `version` line is expected, the changes to `dependencies.*` and `dev-dependencies.*` are not.

**Comment by alexcrichton** [comment]
Aha it does indeed appear that the [0.18.0 to 0.18.1 transition](https://github.com/servo/rust-cssparser/compare/v0.18.0...v0.18.1) didn't change Cargo.toml so this manifest was produced by [this function](https://github.com/rust-lang/cargo/blob/88aa6423a164774d09abc78a24e74e8e665f651b/src/cargo/util/toml/mod.rs#L431-L498) which I believe does include hash map iteration.

**Comment by SimonSapin** [comment]
It looks like the `TomlManifest` struct contains hash maps, and serde is responsible for (iterating them and) serializing them to TOML. So there is no place where a `.collect::<Vec<_>>()` and `.sort()` could be easily added.

So what do you think of using `BuildHasherDefault<DefaultHasher>` (which despite the name is not `HashMap`’s default) instead of the default `RandomState`, in these maps?

**Comment by SimonSapin** [comment]
Or using `BTreeMap`, to sort by key rather than some arbitrary ordering?

**Comment by alexcrichton** [comment]
I think it'd be fine to just change those to `BTreeMap`

**Comment by SimonSapin** [comment]
I was wrong, it’s not `cargo vendor` but `cargo package` that re-serializes `Cargo.toml`.
