### ISSUE TITLE
cargo check --tests not working

### ISSUE THREAD

**Issue by davemilter** [rust-lang/cargo#4330]
`cargo check --help` tells

>--tests                      Check all tests

I expect that at least it cheks syntax of tests.
I created simple project `cargo new foo`,
and edit `src/lib.rs` like this:
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        baguaga
    }
}
```
I run `cargo check --tests` (`cargo 0.22.0-nightly (88aa6423a 2017-07-22)`) and
it reports nothing:
```sh
$ cargo check --tests
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
$ cargo test
   Compiling foo v0.1.0 (file:///tmp/foo)
error[E0425]: cannot find value `baguaga` in this scope
 --> src/lib.rs:5:9
  |
5 |         baguaga
  |         ^^^^^^^ not found in this scope

error: aborting due to previous error

error: Could not compile `foo`.

To learn more, run the command again with --verbose.
```
I expected the same error report from `cargo check --tests` as from `cargo test`
foo directory in attachment.
[foo.zip](https://github.com/rust-lang/cargo/files/1178053/foo.zip)

**Comment by ehuss** [comment]
This is fixed by #4592.  `cargo check --tests` now really does all tests.
