### ISSUE TITLE
Cargo should backtrack from "Package `...` does not have these features: `...`"

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#4347]
Right now Cargo considers this error during resolution fatal, aborting the entire resolution process. We should instead attempt to backtrack to find a candidate which does indeed have these features as we may have just gone too far back in the history.

**Comment by alexcrichton** [comment]
An example `Cargo.toml` which produces this behavior is https://gist.github.com/jsgf/93c6cbdba58c01713d86261cf7419458, sometimes resolving and sometimes failing with "bzip2 doesn't have the feature tokio"

**Comment by Eh2406** [comment]
I tried to reproduce, in a new new project with that toml I get:
```cmd
>cargo generate-lockfile
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `kvfilter` found (required by `rust-third-party`)
location searched: registry `https://github.com/rust-lang/crates.io-index`
version required: *
```
Removing kvfilter from the dependencies and it builds a lock file reliably. So I think some new versions of the dependencies have prevented it reproducing. But it should be easy to build a test case.

**Comment by Eh2406** [comment]
I have a test at: https://github.com/Eh2406/cargo/tree/i4347
Next to make it green.

**Comment by Eh2406** [comment]
Can this be closed?

**Comment by alexcrichton** [comment]
Indeed!
