### ISSUE TITLE
Can't stop cargo

### ISSUE THREAD

**Issue by M4sterZer0** [rust-lang/cargo#4348]
Hi, I cant stop cargo.exe or delete cargo.exe
If I want execute `cargo --version`, I get only this message: Access denied

**Comment by alexcrichton** [comment]
If you're on Windows this can sometimes happen if there's a `cargo.exe` process still active. Are you sure there's no other processes that have the file open?

Is the bug you're seeing that `cargo --version` won't execute? Do you know if you're using rustup or running Cargo direclty?

**Comment by carols10cents** [comment]
Hi @M4sterZer0, since we haven't heard back from you with the information @alexcrichton requested, there's not much we can do here. I'm going to close this for now, but please reopen if you can provide more details!
