### ISSUE TITLE
Static library linkage error

### ISSUE THREAD

**Issue by overminder** [rust-lang/cargo#4351]
Recently I encountered a strange linkage error when building FFI library bindings with rust and cargo. I'm not sure if it's a bug but it's surely annoying. [Here is a minimal working example of the problem.](https://github.com/overminder/rustc-link-lib-bug/tree/3b8918554e047d700a7fec185c6c0bf9e9896e03)

### Example Description

Let's say you have two static libraries: `libfoo.a` and `libbar.a`, where
the later depends on some symbols from the former.

You are writing two FFI binding crates, `rust-foo-sys` and `rust-bar-sys` for these
libraries. To do this, you print `cargo:rustc-link-lib={kind}={libname}` in
both crates' build scripts. In in the former crate you specify `kind`
to be `static` but in the later crate you don't specify
the `kind` and leave the choice to the compiler.

A undefined symbol error will occur when you are building an executable that depends on
`rust-bar-sys`. More specifically, all the symbols that `libbar.a` imports from `libfoo.a` will be undefined in this case.

### OS / Toolchain Versions

This problem seems to only present when targeting ELF (using gcc or clang as
the linker frontend, bfd or gold as the linker). Both x86_64 and arm targets are affected.

**Comment by alexcrichton** [comment]
I believe in this scenario that `rust-bar-sys` needs to depend on `rust-foo-sys` (e.g. `extern crate rust_foo_sys`). Does that fix things for you?

**Comment by overminder** [comment]
@alexcrichton Thanks for the reply! Unfortunately [this was already being done](https://github.com/overminder/rustc-link-lib-bug/blob/3b8918554e047d700a7fec185c6c0bf9e9896e03/rust-bar-sys/src/lib.rs).

**Comment by overminder** [comment]
After some experimentations with [lld](https://lld.llvm.org/), I come to the conclusion that this is likely caused by a static library link order issue in `rustc`. Basically both `ld.bfd` and `ld.gold` require the order of the static libraries to be passed correctly to them (e.g. in our case, `-l bar` before `-l foo`). `ld.lld` however doesn't require this and I was able to compile my example successfully with it.

I will open an issue in the main rustc repo.

**Comment by alexcrichton** [comment]
Ah ok, thanks for checking! In any case yeah I think this is an upstream rustc issue rather than a Cargo issue, which is just shipping arguments to the compiler.

**Comment by carols10cents** [comment]
Closing this since it was moved to rust-lang/rust!
