### ISSUE TITLE
Override the target directory

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#436]
Cargo writes build results to a `target` directory next `Cargo.toml`. I’d like to have a configuration key in `.cargo/config` to override this location. Ideally, this configuration would be a template based on the project name or path to the source directory: `target_dir = "~/tmp/cargo/{}"` would expand to `/home/simon/tmp/cargo/rust-url` or `/home/simon/tmp/cargo/home/simon/projects/rust-url`.

(Motivation: `~/tmp` is ignored in my backups. Ignoring all directories named `target` is risky as they’re not necessarily from Cargo build results. For what it’s worth, my `~/tmp/servo-build` is currently 2.2 GB (although not using Cargo.))

**Comment by paul-hammant** [comment]
Actually, I think the Cargo.toml file itself could name where the target directory is.

**Comment by SimonSapin** [comment]
For what it’s worth, these days Servo’s build system as configuration to set `$CARGO_TARGET_DIR`, which is how Cargo allows that location to be overridden.

**Comment by paul-hammant** [comment]
If so, a one-liner could be similar to:

```
CARGO_TARGET_DIR=foo; cargo run args
```
Cool.

```
cargo --target-dir=foo run args
```

Would be more unix-like, but I'll settle for the former :)

**Comment by SimonSapin** [comment]
> CARGO_TARGET_DIR=foo; cargo run args

Without the semi-colon, in order to set the variable for that command only.

**Comment by paul-hammant** [comment]
Yes, you're right.

**Comment by mcandre** [comment]
> Closing, since I’m happy with symlinks.

Unsatisfactory for Windows.

> CARGO_TARGET_DIR

Unsatisfactory for scripting; this value should be configurable from the `Cargo.toml` file itself.

**Comment by kpcyrd** [comment]
I think Cargo.toml is a bad place for this, given that this file is committed to git and shared across multiple computers. I think this should go into `$HOME/.cargo/config`.

This feature would help a lot for backups, I currently have to exclude every `target/` folder manually.

**Comment by sfackler** [comment]
Windows supports symlinks.

**Comment by mcandre** [comment]
> I think Cargo.toml is a bad place for this, given that this file is committed to git and shared across multiple computers. I think this should go into `$HOME/.cargo/config`.

That would be worse for per-project configurations.

**Comment by sfackler** [comment]
You can put a .cargo/config in the repository.
