### ISSUE TITLE
New categories: internationalization, localization, accessibility

### ISSUE THREAD

**Issue by behnam** [rust-lang/cargo#4368]
Internationalization (i18n), localization (L10n), and accessibility (a11y) are three major categories of application libraries, mostly in areas of text processing and UI development, but kind of orthogonal to these areas.

I'm not sure what's the policy for categories available in <https://crates.io/category_slugs>, but I think these three can be good additions to the list.

**Comment by behnam** [comment]
Also, would be great to have a note in the page regarding the source of the list and how it's maintained.

**Comment by alexcrichton** [comment]
cc @carols10cents 

Although I think you can add categories by making a PR to the crates.io repo

**Comment by carols10cents** [comment]
Yep! Instructions on adding categories are in crates.io's README: https://github.com/rust-lang/crates.io#categories 

Could you also file an issue (or PR) in crates.io's repo about linking to these instructions from crates.io/category_slugs? Thanks!

Closing this since these are crates.io issues!

**Comment by behnam** [comment]
Thanks for the pointers!

I have sent a PR for i18n and L10n: https://github.com/rust-lang/crates.io/pull/942

Regarding a11y, AFAICT, we still don't have any crate that would sit in such a category. In fact, we don't have much libraries for UI in general, and a11y is kind of a sub-category of UI (both CLI and GUI). I think it's better to wait on that one until there's more development in the area first.
