### ISSUE TITLE
Cargo init panics in root directory

### ISSUE THREAD

**Issue by parkovski** [rust-lang/cargo#4370]
Noticed this by accident - Windows sets cwd to C:\ if your terminal is in a directory that was renamed. The crash happens on both Windows and macOS - in C:\ or /, running 'cargo init --name foo' panics. Without the --name it just complains it couldn't infer a name from an empty directory name.

**Comment by alexcrichton** [comment]
Thanks for the report! Can you gist the panic message, perhaps with `RUST_BACKTRACE=1` as well?

**Comment by parkovski** [comment]
Sure. It's unfortunately not very descriptive. https://gist.github.com/parkovski/2cc7d9bba3df0af818816787de746820

**Comment by parkovski** [comment]
I fixed this by changing https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_new.rs#L406 to say `path.parent().unwrap_or(path)`, not sure if that's correct but it does get rid of the crash.

**Comment by alexcrichton** [comment]
Oh nice! Want to send a PR for that? I think it's effectively correct in the sense that if `parent` returns `None` there we'd just want to set `VersionControl::NoVcs`

**Comment by alexcrichton** [comment]
er, `VersionControl::Git` I mean
