### ISSUE TITLE
bin-publish

### ISSUE THREAD

**Issue by necrose99** [rust-lang/cargo#4371]
while I may not be the package owner , ARM64 anyone ?  
crates.io  push bins I build for others to enjoy , arm64 server I'd care little , but say RPI-3 then the compile times are more of dragging. 

can just contribute a binary build to the package owners... and have a nice day :-)

**Comment by alexcrichton** [comment]
Thanks for the report! Right now though Cargo and crates.io do not support publishing binaries, so I'm going to close this.

**Comment by necrose99** [comment]
just a suggestion , as IOT class of arm64's building can be a touch slow.. ie crowd building.. would ease a bit of pain...
