### ISSUE TITLE
Recent version of cargo fails on pulling a library for musl target

### ISSUE THREAD

**Issue by opensourcegeek** [rust-lang/cargo#4381]
I've just upgraded cargo/rustc and I've started running into issues (failed to verify the checksum) when I target musl, but it works fine when I target gnu. 

cargo --version
cargo 0.20.0 (a60d185c8 2017-07-13)

rustc --version
rustc 1.19.0 (0ade33941 2017-07-17)

Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading google-bigquery2 v1.0.0+20160903
error: unable to get packages from source

Caused by:
  failed to verify the checksum of `google-bigquery2 v1.0.0+20160903`

Any ideas please?

**Comment by alexcrichton** [comment]
I wonder if this may just be a corrupt cache by accident? If you remove `~/.cargo/registry` does it work?

**Comment by opensourcegeek** [comment]
I removed that directory, now I can see the issue in gnu target as well. 

~/projects/rust-playground/sample-bq [master L|…4] 
10:36 $ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading google-bigquery2 v1.0.0+20160903
error: unable to get packages from source

Caused by:
  failed to verify the checksum of `google-bigquery2 v1.0.0+20160903`

10:37 $ cargo --version
cargo 0.20.0 (a60d185c8 2017-07-13)

I downgraded and it works fine again. 
rustc --version
rustc 1.18.0 (03fc9d622 2017-06-06)

cargo --version
cargo 0.19.0 (28d1d60d4 2017-05-16)

**Comment by alexcrichton** [comment]
Do you have a way to reproduce this locally? If so, can you post the instructions for how I might reproduce it?

**Comment by hobofan** [comment]
Steps to reproduce:
- Clean install of Rust 1.19
- Create a new project
- Add as a dependency: `google-storage1 = "=1.0.4+20161123"`
- run `cargo build`

Seems that older versions of multiple (all?) of the google-* API clients are affected, while newer ones aren't.

**Comment by hobofan** [comment]
Looking at the registry index, there are multiple `1.0.4` versions with different postfixes:
https://github.com/rust-lang/crates.io-index/blob/11c63b89053ef70a46be8b2a2f135a99c6b056ec/go/og/google-storage1#L23-L24

**Comment by dweidenfeld** [comment]
+1 ... same with google-drive3 dependency
