### ISSUE TITLE
Linker errors/build scripts cause build cache to become dirty

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#4385]
This is quite a frequent occurrence for me, recent example:
- Added diesel as a dependency
- Ran `cargo build`
- Got a linker error with missing `libpq.lib`
- Added `pq_config.exe` to PATH
- Reran `cargo build`
- Got the same linker error

In this case, the solution is to do a full `cargo clean` and rebuild, but problem is that it's a very poor user experience - there's no real way to discover that a `cargo clean` is required, which makes the user think that their environment is still misconfigured, and there's nothing worse than struggling to configure build environments.

This is a difficult one to solve, because there's no easy way for cargo to know what a build script depends on. However, I can think of a few different approaches worth considering in order from easiest to hardest:

- When a linker error occurs, suggest running `cargo clean`  or one of the below additions if the user recently modified their environment
- Provide an option to clean a specific dependency
- Provide an option to force re-run all build scripts, and then rebuild packages where the build script output changed.
- Store a hash of the environment variables on disk, and more aggressively rerun build scripts when the hash changes
- Track which linker inputs came from which dependencies, and don't cache dependencies which cause linker errors.

Thoughts?

**Comment by cssivision** [comment]
i have a similar  problems. i think the `rust tool chain` which you use is stable version, in the nightly version there is a feature `rerun-if-env-changed=VAR`, [here](http://doc.crates.io/build-script.html). when the env variables changed, the build.rs will rerun.

**Comment by cssivision** [comment]
if you use a nightly version, and still have the problem, i think is the time to fire a pr to the crates you used to force rerun when env variables changed.

**Comment by Diggsey** [comment]
That looks like a good solution, I wasn't aware of that improvement. The problem is that it requires all crates with build scripts to opt-in, and for new crate authors to even be aware of the option. Might be worth getting a list of all the published crates with build scripts and opening issues...

In the mean time, I think some of the suggestions would still be useful, for example, force rerunning all or specific build scripts.

**Comment by cssivision** [comment]
yes, some of the suggestions would still be useful.

**Comment by alexcrichton** [comment]
Ah yes as @cssivision mentioned the real fix here is to get Cargo to learn about these dependencies, which should now be possible through the env vars. There's no real way to make usage of an environment variable automatically detected, this'll basically always have to be opt-in.
