### ISSUE TITLE
Add support for debug builds (-g flag)

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/cargo#439]
I think there should be a way to optionally pass the `-g` flag to `rustc`. My specific use case is that I need a binary with debug information for use with kcov.

**Comment by dumski** [comment]
> This is now implemented! See the `profile` section of http://crates.io/manifest.html for more information.
> 
> I should also note that this is now the default for regular/test profiles, you'll just have to opt-in to debuginfo for release builds.

Hi, this link is broken. Cheers
