### ISSUE TITLE
Aliases entirely undocumented

### ISSUE THREAD

**Issue by Osspial** [rust-lang/cargo#4391]
Cargo has built-in aliases for `cargo build`, `cargo test` and `cargo run`, in the forms of `cargo b`, `cargo t` and `cargo r`. However, these aliases seems to have gone unmentioned in all of `cargo`'s documentation, and I can't find any mention of them on rust-lang.org, crates.io, or cargo's help command. This is admittedly pretty low-priority as far as documentation holes go, but these aliases should get some mention in cargo's help command if not elsewhere.

**Comment by sfackler** [comment]
They are documented down in the bottom of the example `.cargo/config` here, but it's not particularly obvious: http://doc.crates.io/config.html#configuration-keys

**Comment by dwijnand** [comment]
Another URL is https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys.

I (personally) don't have any specific ideas what should change, so maybe we can close this?

**Comment by dwijnand** [comment]
I'm going to close those on the basis that "entirely undocumented" isn't true.

*But* let us know if you have any suggestions on how to document them better.
