### ISSUE TITLE
[book] Add a Glossary section?

### ISSUE THREAD

**Issue by behnam** [rust-lang/cargo#4392]
What terms are used in Cargo and what they mean is a common theme in Cargo issues/pulls, as well as in the documentation. Recently I just updated some of the docs to use the correct term in their place. (See https://github.com/rust-lang/cargo/pull/4376 and https://github.com/rust-lang/cargo/pull/4375)

I think with the expansion of Cargo features, it makes sense to have a Glossary document that describes each term and points to the detailed description.

We can add this to the new mdBook-based docs, and not in-repo.

Here's some example terms that I have seen confusions about in the docs and public spaces, like the users forum:
* crate
* package
* build target (as in platform and its binary format)
* target (as in lib, bins, tests, examples, ...)
* crate file
* package repository (as in git repo)
* package registry (as in crates.io), a.k.a. package index
* package root (the directory)
* workspace root (the directory)
* workspace root package (a package or its manifest)
* repository root (the directory)

What do you think?

**Comment by alexcrichton** [comment]
cc @carols10cents

**Comment by behnam** [comment]
Also cc @istankovic, since this would be a new section on the new mdBook-based repo.
