### ISSUE TITLE
dev-dependencies record doesn't auto-enable optional dependencies record

### ISSUE THREAD

**Issue by behnam** [rust-lang/cargo#4395]
Example: https://github.com/behnam/rust-unic/blob/cf6928933d42eda3014bf73e9de72442838b07b1/unic/ucd/normal/Cargo.toml#L20-L27

Here's a minimal manifest part:
```
[dependencies]
foo = { version = "0.5", optional = true }

[dev-dependencies]
foo = { version = "0.5" }
```

The reason to have it optional is that there's a built-in feature that can fill-in the `foo` dep, but it's optional, so that the package can be built standalone (without other things `foo` provide that are not always necessary.)

Now, apparently, when tests are being built, the dev dep causes the feature to become enabled automatically. I don't think that's expected behavior. Or, if it is, it's not documented and is not inferable from the current docs.

For my project, I'm going to fix the problem by setting up an *explicit* feature, to depend on that for the behavior in the code. But I think there's code or doc issues to fix here in Cargo.

What do you think?

**Comment by behnam** [comment]
Looks like I was wrong here. Adding a `#![cfg(feature = "...")]` to the test file revealed that the feature is not auto-enabled. (<https://github.com/behnam/rust-unic/pull/106>)

Do you think it's worthy of going into the docs?

**Comment by alexcrichton** [comment]
Seems worth documenting!

**Comment by dwijnand** [comment]
Wait.  I'm confused.  What needs documenting?
