### ISSUE TITLE
Cargo seems to exit prematurely when "cargo run" receives SIGINT

### ISSUE THREAD

**Issue by Svedrin** [rust-lang/cargo#4397]
If I write [code that ignores SIGINT](https://play.rust-lang.org/?gist=91e46d8b08e9b3a0c8943f32ff42952a&version=stable), and then send that code an interrupt by hitting `^c`, cargo forwards the signal to the target process but exits prematurely:

```
[13:22]mz1030@mz1030-nb111:~/tmp/threadtests# cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/threadtests`
^C
[13:22]mz1030@mz1030-nb111:~/tmp/threadtests# Thread exiting!

```

If I run the target directly, `^c` is correctly ignored without me being dropped back to the shell:

```
[13:23]mz1030@mz1030-nb111:~/tmp/threadtests# ./target/debug/threadtests 
^C^C^C^C^C^CThread exiting!
[13:23]mz1030@mz1030-nb111:~/tmp/threadtests# 
```

I noticed because I had written an application that takes a second or two to clean up when it receives SIGINT. My Cargo version (installed through rustup) is:

```
[13:25]mz1030@mz1030-nb111:~/tmp/threadtests# cargo --version
cargo 0.20.0 (a60d185c8 2017-07-13)
[13:25]mz1030@mz1030-nb111:~/tmp/threadtests# rustc --version
rustc 1.19.0 (0ade33941 2017-07-17)
```

**Comment by BurntSushi** [comment]
See also:

* https://github.com/rust-lang/cargo/issues/3281
* https://github.com/rust-lang-nursery/rustup.rs/issues/806
* https://github.com/rust-lang/cargo/issues/2343
* https://github.com/rust-lang/cargo/issues/2525
* https://github.com/rust-lang/cargo/issues/3460

**Comment by alexcrichton** [comment]
Thanks for the report! This is, however, how signals work on Unix. When you hit ctrl-c the shell sends SIGINT to the *process group*. In the case of Cargo nothing's listening for SIGINT so everything is torn down in a nondeterministic fashion.

**Comment by Svedrin** [comment]
@alexcrichton shouldn't cargo then make the subprocess its own process group before exec()ing the target, so that cargo "just does the right thing"? From a user perspective, this behavior feels very wrong.

**Comment by alexcrichton** [comment]
The cargo subprocess and all of its children are already in the same process group, so what you're seeing is actually "the right thing" in terms of intention.

The *best* solution here is handling https://github.com/rust-lang-nursery/rustup.rs/issues/806

**Comment by Svedrin** [comment]
@alexcrichton what does rustup have to do with it? :confused:

**Comment by alexcrichton** [comment]
@Svedrin did you install Rust through rustup? If so when you execute `cargo` you're actually executing rustup first, then Cargo.
