### ISSUE TITLE
Document traits from #[derive(...)]

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/cargo#4406]
While documenting every public function of [ThreadPool](https://github.com/rust-threadpool/rust-threadpool) I had to implement `#[derive(Clone)` manually so I would be able to add an example.

I assume `cargo doc` has a default template for the derive-able traits.
So I propose something like this:
```rust
#[derive(Clone)
/// My custom doc
/// ```
/// let my = custom.example();
/// ```
#[derive(PartialEq, Eq)
/// My custom doc for both traits
/// ```
/// let my = custom.example();
/// ```
struct CustomStruct;
```

The template would have to include something like "yield" within the code it is generating.
In this case it should generate something equal to:
```rust
impl Clone for CustomStruct {
    /// My custom doc
    /// ```
    /// let my = custom.example();
    /// ```
    fn clone(&self) -> Self { CustomStruct }
}
/* similar for the other two traits */
struct CustomStruct;
```

What do you think?

**Comment by alexcrichton** [comment]
Thanks for the report! I think though this may be best located on the rust-lang/rust repo perhaps instead of Cargo?

**Comment by carols10cents** [comment]
Yep, this sounds like a job for rustdoc since `cargo doc` mostly just calls `rustdoc`. @dns2utf8 I've taken the liberty of moving this issue over to https://github.com/rust-lang/rust/issues/44118 for you!

**Comment by dns2utf8** [comment]
Thank you 👍
