### ISSUE TITLE
Cargo doesn't rebuild when the source has been edited during the previous build

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#4411]
Because build times can be so long, I sometimes end up editing the source while it's compiling my previous iteration of the code. But then when I run `cargo test` again afterwards, it does nothing, so I need to touch the files again.

**Comment by alexcrichton** [comment]
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/2426, so closing in favor of that. Thanks for the report though!
