### ISSUE TITLE
Possible race condition with parallel builds

### ISSUE THREAD

**Issue by ipetkov** [rust-lang/cargo#4415]
Noticed an issue when building [one of my crates](https://github.com/ipetkov/conch-runtime/) on travis, specifically on linux-beta where running `cargo test` fails with no information, but sometimes succeeds after multiple restarts. I don't remember ever seeing this issue on OS X, but it may have happened on some of the latest linux-nightlies as well (but again not on OS X). I've tried reproducing the issue locally (both in a linux VM and a travis docker image) with no success, but here's what I've been able to glean out:

My crate uses a lot of "integration" tests in the `tests/` directory in an effort to parallelize part of the `cargo test` cycle, and so I can hack on tests without rebuilding the entire lib each time. I've noticed that for a particular build I'd see several errors like 

```
process didn't exit successfully: `rustc tests/foo.rs ...`
process didn't exit successfully: `rustc tests/bar.rs ...`
```

Upon restarting the same job (note I have cargo cache enabled in travis), `foo` and `bar` will compile successfully, but some other tests will fail:
```
process didn't exit successfully: `rustc tests/baz.rs ...`
process didn't exit successfully: `rustc tests/qux.rs ...`
```

My hunch is that thanks to cargo caching, the restart is able to pick up where it left off, effectively building different tests in another order which avoids the issue for specific files, but may result somewhere else (in other words the failure isn't due to any particular test but part of the overall build process). I also noticed that if I force cargo to use a single job (`-j1`) the test build completes successfully, even after nuking the travis cache.

Logs are from effectively running `RUSTFLAGS='--verbose' cargo test -vv`, but if there is a way to get even more context from `rustc` I'd be happy to provide more logs

Sample failed build: https://travis-ci.org/ipetkov/conch-runtime/builds/266189422
Raw log for the same build: https://gist.github.com/ipetkov/17ec8b220e3a22570db78798af440c56
Sample successful build with `-j1`: https://travis-ci.org/ipetkov/conch-runtime/builds/266192089

### Meta

```shell
$ rustc --version

rustc 1.20.0-beta.2 (54279dfac 2017-08-13)

$ rustup --version

rustup 1.5.0 (92d0d1e9e 2017-06-24)

$ cargo --version

cargo 0.21.0-beta (5b4b8b2ae 2017-08-12)
```

**Comment by alexcrichton** [comment]
Thanks for the report! I wonder if this is related to OOM and Travis perhaps? Unfortunately I'm not sure what's going on

**Comment by ipetkov** [comment]
Thanks for the insight @alexcrichton! Tried out a few things to test this hypothesis:

* Increased the RAM of the travis build by using `sudo: required` (according to [this chart](https://docs.travis-ci.com/user/reference/overview/) this gives us 7.5GB instead of the normal 4GB) and the build succeeded even with a cold cache (though we do get ~2 cores, not sure if this means its possible we're running as a single core which may be a misleading solution)
* Also tried torturing `cargo` in a linux VM with super low RAM (using 512MB): seems like if we get an OOM error when compiling crate dependencies a `fatal runtime error: allocator memory exhausted` message is consistently shown. If we hit OOM when building the tests sometimes the message gets shown, but its possible it doesn't (however, the error message that `rustc` exited with a status of `1` is still there)

Although the evidence does point towards OOM errors, I'm still a bit suspect because
* I haven't seen this happening in OS X travis builds, nor have I experienced this locally when developing (my machine has 4GB RAM which is what travis is supposed to have, though swap may play a different role in local vs travis builds)
* I've never seen the `allocator memory exhausted` error in any of the logs for the failed travis builds which I'd expect to at least see it once somewhere 
* If the OOM killer picked `rustc` it would receive SIGKILL IIRC, so the exit status shouldn't be `1`

Not super familiar with the `rustc` internals, maybe the error gets swallowed somewhere without being emitted. Do you have any additional advice on what can be explored? (I did try using `RUSTLOG=INFO ...` but didn't see any meaningful ERROR messages leading up to the build failure)

If this really is an OOM issue I'd be fine with adding some retry logic with fewer parallel builds on my end, but just trying to dig into a deeper root cause to save someone else some extra debugging :)

**Comment by alexcrichton** [comment]
> I've never seen the allocator memory exhausted error in any of the logs for the failed travis builds which I'd expect to at least see it once somewhere

I think this wouldn't happen due to the OOM killer?

> If the OOM killer picked rustc it would receive SIGKILL IIRC, so the exit status shouldn't be 1

I believe that's due to https://github.com/rust-lang-nursery/rustup.rs/issues/806

**Comment by ipetkov** [comment]
> I think this wouldn't happen due to the OOM killer?

Yeah if the OOM is at play it's possible nothing gets a chance to get printed out. I forgot that rustup intercepts `rustc` and we're seeing its return value and not the compiler's.

Noticed there was a fix for the linked issue merged in a few days ago. Do `rustup` updates ship with nightlies or do they use a different cadence? Want to try reproducing the problem with the fix in place and check for different behavior

**Comment by alexcrichton** [comment]
Nah we still currently manually release rustup, so we'll have to ship an update later to get it into a release.

**Comment by alexcrichton** [comment]
I don't think this has come up much in the meantime, so I'm going to close this as chalked up to "travis resource limits bugs"
