### ISSUE TITLE
Cargo should set --cap-lints for build scripts of dependencies

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#4422]
Right now, looking at the `-v` output of cargo, it doesn't look like `--cap-lints` is set when building the build script of a dependency:
```
     Running `rustc --crate-name build_script_build /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/build.rs --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="alloc_jemalloc"' --cfg 'feature="jemalloc"' --cfg 'feature="panic_unwind"' -C metadata=5d32c91031c302ff -C extra-filename=-5d32c91031c302ff --out-dir /tmp/xargo.IGdM4gy63Rh7/target/release/build/std-5d32c91031c302ff -L dependency=/tmp/xargo.IGdM4gy63Rh7/target/release/deps --extern gcc=/tmp/xargo.IGdM4gy63Rh7/target/release/deps/libgcc-95d7f0ac44dd313d.rlib --extern build_helper=/tmp/xargo.IGdM4gy63Rh7/target/release/deps/libbuild_helper-b35ef116d79cdae6.rlib`
```
That is a problem, as of course build scripts of dependencies can fail due to `deny(warnings)` in much the same way as the dependency itself can.

**Comment by alexcrichton** [comment]
Right now `--cap-lints` is set whether or not you're an "upstream" or "local" dependency, and for the Rust repo everything's a "local dependency" (everything's a path dependency) so this is currently behaving as expected.

**Comment by RalfJung** [comment]
Ah I see -- did you mean to say that `--cap-lints` is *only* set for "non-local" dependencies? That actually matches the behavior I can observe, and I agree it makes sense.

**Comment by alexcrichton** [comment]
Oops indeed!
