### ISSUE TITLE
cargo login should try detecting errors 

### ISSUE THREAD

**Issue by xfix** [rust-lang/cargo#4434]
When using `cargo login`, `cargo` asks for

```
please visit https://crates.io/me and paste the API Token below
```

While the input is trimmed, there is more that can be done, for instance removing `cargo login` from beginning of token (if an entire command is pasted for some reason) and detecting things that definitely aren't tokens (too short or too long to be them, having invalid token characters and so on).

**Comment by eminence** [comment]
Triage: removing `cargo login` from the pasted token was implemented in #7588, so I think this issue can be closed.
