### ISSUE TITLE
Make cargo not use the RUST_LOG environment variable

### ISSUE THREAD

**Issue by whitequark** [rust-lang/cargo#4448]
This breaks any naive attempt to raise the log level for your application, e.g. using
```
RUST_LOG=trace cargo run --example foo
```
results in a *lot* of output, and the workaround is to find which file under `./target/...` is the actual binary, which is not always trivial.

Statistically, there are far more people using the `log` crate and `cargo run` than cargo developers so I think cargo should use a different name, perhaps `CARGO_LOG`.

**Comment by alexcrichton** [comment]
Is this not what filters in `env_logger` are intended for?

**Comment by whitequark** [comment]
Oh, you mean use filters to distinguish applications as well as individual modules? I suppose that works.
