### ISSUE TITLE
Cargo fails in Linux chroot without /proc

### ISSUE THREAD

**Issue by apaprocki** [rust-lang/cargo#4450]
```
...
running: /tmp/rust-1.19-1.19.0-0/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build \
    --manifest-path /tmp/rust-1.19-1.19.0-0/src/bootstrap/Cargo.toml --verbose
error: couldn't get the path to cargo executable
```

This is due to [this code](https://github.com/rust-lang/cargo/blob/3da1443551a900bf6501445cd54b7082a39ea827/src/cargo/util/config.rs#L125):

```
    pub fn cargo_exe(&self) -> CargoResult<&Path> {
        self.cargo_exe.get_or_try_init(||
            env::current_exe().and_then(|path| path.canonicalize())
            .chain_err(|| "couldn't get the path to cargo executable")
        ).map(AsRef::as_ref)
    }
```

Which ultimately calls [this code](https://github.com/rust-lang/rust/blob/5dfcd85fd4bae49445383baadf472fbdb414a0e6/src/libstd/sys/unix/os.rs#L254):

```
#[cfg(any(target_os = "linux", target_os = "android", target_os = "emscripten"))]
pub fn current_exe() -> io::Result<PathBuf> {
    let selfexe = PathBuf::from("/proc/self/exe");
    if selfexe.exists() {
        ::fs::read_link(selfexe)
    } else {
        Err(io::Error::new(io::ErrorKind::Other, "no /proc/self/exe available. Is /proc mounted?"))
    }
}
```

Is the project open to modifying this logic to allow the full path to the executable to be specified via config or environment variable if `/proc` intentionally does not exist?

Something along the lines of `CARGO_EXE` or `[build] cargo = "/path/to/cargo"`...

**Comment by alexcrichton** [comment]
Hm I sort of forget at this point what we're even using that for. Maybe we can just remove the dependence on calling `current_exe`?

**Comment by kivikakk** [comment]
@alexcrichton found it! https://github.com/rust-lang/cargo/issues/3778#issuecomment-283448233

Maybe we could use a method other than `env::current_exe` for this case? Or just let the user specify `CARGO` and check if that's present, and if so, use it instead of calling `current_exe`?

**Comment by kivikakk** [comment]
I need to read more context first. We're only setting this for external subcommands so we don't _use_ it ourselves per se, but yeah; we could just check if it's set already and not do anything if so, letting the environment propagate.

**Comment by kivikakk** [comment]
Example of the latter at #4634.
