### ISSUE TITLE
Can't cross-compile doc tests with Cargo

### ISSUE THREAD

**Issue by asomers** [rust-lang/cargo#4471]
I have a project that uses unit, functional, and doc tests. When I run “cargo test”, all three sets of tests execute. But when I cross-compile, only the unit and functional tests do. The output makes no mention of Doc-tests at all.  I can't find anything in the cargo docs that suggests why this should be impossible.  For the case where the host is a 64-bit system and the target is the 32-bit ABI of the same architecture, it ought to work.  Indeed, the unit and functional tests run and pass.  Only the doc tests fail to build.  My host is x86_64 FreeBSD and I’m trying to cross test i686 FreeBSD.

```
> cargo --version
cargo 0.21.0 (5b4b8b2ae 2017-08-12)
> freebsd-version 
11.0-RELEASE-p9
> cargo test --target=i686-unknown-freebsd -v
```

**Comment by alexcrichton** [comment]
This is currently intentional as while Cargo has infrastructure for running cross-compiled tests and handling all that I don't believe this is implemented and/or handled in rustdoc. I'm not sure if `rustdoc --test --target ...` will work as expected.

**Comment by asomers** [comment]
Good explanation, @alexcrichton .  It looks like `rustdoc` ignores `--target` when used with `--test`.  I've opened a separate issue for that.
https://github.com/rust-lang/rust/issues/44404
