### ISSUE TITLE
Warning when using both git and path dependency

### ISSUE THREAD

**Issue by Marwes** [rust-lang/cargo#4475]
```
warning: dependency (serde) specification is ambiguous. Only one of `git` or `path` is allowed. This will be considered an error in future versions
```

```toml
serde = { version = "1.0", optional = true, git = "https://github.com/Marwes/serde_state, branch = "human_readable", path = "serde" }
```

Getting the warning above when using a git dependency on a multi-crate repository (such as serde) and pointing to a specific crate using `path`. I use this way of specifying dependencies when I test a secondary crate with changes from a multi crate repo which have yet to be released. 

Wondering what the alternative is if this will be an error or whether the warning itself is erroneous since everything works fine when building projects which use this pattern.

**Comment by alexcrichton** [comment]
Oh you should be able to just omit `path`, Cargo will probe the repo looking for the right crate and shouldn't need `path` to guide it.

**Comment by Marwes** [comment]
Well that works 😓 I am sure I tried that way, way back and got some workspace related error and the only way I worked around it were to add the path. It works without a path in any case so closing!

**Comment by lizhanhui** [comment]
> Oh you should be able to just omit `path`, Cargo will probe the repo looking for the right crate and shouldn't need `path` to guide it.

What if there are multiple crates in the repository? 
For example, https://github.com/google/flatbuffers.git
In the rust directory, there are two crates that live: flatbuffers and flexbuffers.

**Comment by Marwes** [comment]
Cargo figures out which crate to select by using the given name of the dependency. Not sure if it just fully searches the repository or if it requires the root the be a workspace to figure it out from that

**Comment by weihanglo** [comment]
Marwes is corret. AFAIK, Cargo walks through git source to find the package with the given name, regardless being workspace or not.

https://github.com/rust-lang/cargo/blob/247b22f225af3fbdb82e53e2f1ab81efd3cab050/src/cargo/sources/path.rs#L42-L55
