### ISSUE TITLE
Cargo crashes when using `opt_level = 'z'` with c-backed crates on linux

### ISSUE THREAD

**Issue by mcdenhoed** [rust-lang/cargo#4483]
# Steps to Reproduce

On a linux rust install with nightly installed (tested on `rust version 1.22.0-nightly (ca94c75c5 2017-09-10)`):

* Make a new cargo bin project with the following `Cargo.toml`:

```
[package]
name = "opt_test"
version = "0.1.0"
authors = [""]

[dependencies]
openssl-sys = "0.9.17"

[profile.release]
opt-level = 'z'
```

* `cargo +nightly run --release`

Cargo will crash when attempting to compile `openssl-sys`, complaining about passing `gcc` the `-z` flag, which it does not support.
This does not crash on macOS, I suspect because `gcc` on macOS is just a `clang` alias, which does support the `-z` flag.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this may be a bug for openssl-sys/gcc-rs rather than Cargo though?

**Comment by mcdenhoed** [comment]
Ah, ok. I wasn't sure where it should go. I'll post it over there then. Thanks!
