### ISSUE TITLE
"no matching version" when bumping workspace root package if something depends on it

### ISSUE THREAD

**Issue by bluss** [rust-lang/cargo#4486]
Project layout is like this:

```
.
├── Cargo.toml     # petgraph
├── serialization-tests
│   ├── Cargo.toml # petgraph-serialization-tests
│   ├── src
│   └── tests
├── src
...
```

Cargo.toml is the workspace root and has the following content:

```
[workspace]
members = ["serialization-tests"]
```

The member's dependency relation looks like this:

```
[dependencies]
petgraph = { path = "..", features = ["serde-1", "quickcheck"] }
```
## Steps to Reproduce

1. `cargo build` in the root
2. Edit root Cargo.toml to bump patch version
3. `cargo build` in the root

Step (3) gives an error:

```
error: no matching version `= 0.4.5` found for package `petgraph` (required by `petgraph-serialization-tests`)
location searched: file:///some/path/to/the/crate
versions found: 0.4.6
consider running `cargo update` to update a path dependency's locked version
```

## Expected Behaviour

Take the update of the root package's version in stride, because we are building it itself. Just update the version in the lock file and build.

## Cargo Version
`cargo 0.23.0-nightly (33250c48b 2017-09-09)`

**Comment by alexcrichton** [comment]
I think this may be a result of https://github.com/rust-lang/cargo/issues/4127, although I'm not 100% sure. Certainly run into it before!
