### ISSUE TITLE
Mac OSX index download significantly slower than Linux

### ISSUE THREAD

**Issue by danielpclark** [rust-lang/cargo#4487]
I have TravisCI run tests for my Rust project on both and Ubuntu image and OSX.  When the process gets to getting the cartes.io index it's instantaneous on the Ubuntu image but for Mac OSX it sits about 3 to 5 minutes before downloading its crates.  The downloads are fast once they start so it's not a connection issue.

You can look at my project for the difference in time stamps: https://travis-ci.org/danielpclark/faster_path/builds

The point at which it stalls (only on Mac) is:

    Updating registry `https://github.com/rust-lang/crates.io-index`

And the behavior is consistent.

**Comment by alexcrichton** [comment]
I know that Travis has been having a difficult time recently with OSX, and historically we've seen that macs there are just slower (and we can't really explain why). Is this something you can reproduce locally? If not I'm tempted to chalk it up to "cloud infrastructure is weird sometimes"

**Comment by danielpclark** [comment]
I only have a PowerPC on the Mac end of things.  I'm not sure Rust supports that yet and I don't think that data sample would be fair in comparison to the Intel Mac OSX builds.

**Comment by alexcrichton** [comment]
Ok, in that case I haven't experience this locally on my own Mac and otherwise I think this is a Travis issue, so closing.
