### ISSUE TITLE
Unknown sections are silently ignored for virtual manifest

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#4491]
For a virtual manifest (no `[package]` section), unknown sections in the `Cargo.toml` sections are silently ignored. For non-virtual packages, however, they trigger a warning.

Behavior should be consistent, and probably also trigger a warning for virtual manifests.

Also see <https://github.com/rust-lang/rfcs/pull/1133#issuecomment-329215626>.

**Comment by Ericson2314** [comment]
I'd like all unrecognized data to cause an error---failing fast during configuring is a better user experience than mysterious failure during building. Plugins for declarative `build.rs` replacements can declare what non-standard sections they parse---analogous to the plan for attribute-like procedural macros in Rust.

**Comment by ehuss** [comment]
This was fixed in #5726.
