### ISSUE TITLE
Allow `cargo.toml`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#45]
From http://www.reddit.com/r/rust/comments/28xyrc/cargo_alpha_is_here/cifnlkg

Would be nice to be consistent with `make`, and while I prefer `Cargo.toml`, apparently a bunch of people feel the other way.

**Comment by skyne98** [comment]
+1 for ```cargo.toml``` too

**Comment by AlexAegis** [comment]
+1 for `cargo.toml`. I thought rust is about it's community. And I see the majority of the community wanting a lowercase project file.

**Comment by richardmatheson** [comment]
Cargo.toml is fine. So is cargo.toml. I definitely don’t like Cargofile. Don’t think it’s worth getting het up over though.

**Comment by WHK102** [comment]
Today I have asked myself: why do you use a capital letter? I have looked for information about it and I have come to this place.

Uppercase files smell like Windows files to me unless you use a programming style where all source files must start with uppercase like java, but rust is derived from c so it should be normal to find everything lowercase.

It also bothers me a bit that the configuration format is so old, like the windows .ini files, if rust is a modern language, why didn't you use manifest or json structure files?

Mozilla always tends to privilege technology towards windows and this ideology has been impregnated in rust lang, this is not fair because rust is multiplatform.

**Comment by steveklabnik** [comment]
> why cargo use a capital letter? ... Uppercase files smell like Windows files to me

It's the opposite, it's because `Makefile` with a capital M is traditional in the Unix world.

> It also bothers me a bit that the configuration format is so old,

TOML was created in 2013.

> Mozilla always tends to privilege technology towards windows and this ideology has been impregnated in rust lang,

Mozilla had nothing to do with these choices, but the Rust project does care about Windows quite a bit, like all of our platforms.

**Comment by SinaMobasheri** [comment]
+1 for cargo.toml

**Comment by Mudbill** [comment]
Today I searched "Why is Cargo.toml upper case." A strange thing to search, I admit, and I'm not sure if it's me being pedantic or nitpicky, or if it actually makes an aesthetic difference.

Either way, considering Rust promotes snake_case conventions, I too find it odd that Cargo.toml has an uppercase.

But today I also found out I can simply rename it to use a lower case and everything works. That makes me happy.

Though for the sake of convention, I'm here to put my vote for `cargo.toml`.

**Comment by nathanfranke** [comment]
+1 for `cargo.toml`, should be re-opened for discussion

**Comment by FrantisekVojacek** [comment]
+1 for `cargo.toml`

**Comment by FrantisekVojacek** [comment]
While there may not be an exactly strong reason to allow this, I don't see much sense and a reason to specifically forbid this. A project may have a specific naming convention. I would leave the decision on projects.

**Comment by AlexAegis** [comment]
Because macOS's file system is also case insensitive

**Comment by Mudbill** [comment]
@AlexAegis Oh, wow. I was certain it wasn't, it being Unix based and all. I thought Windows was the only odd one here. My world is falling apart before my eyes 😅
Carry on then.

**Comment by bsdayo** [comment]
+1 for `cargo.toml`

**Comment by Dashbloxx** [comment]
I'll move from C to Rust if they can rename Cargo.toml to `Cargofile` or `cargo.toml`

**Comment by quadgod** [comment]
+1 for cargo.toml

**Comment by parskongar** [comment]
> > why cargo use a capital letter? ... Uppercase files smell like Windows files to me
>
> It's the opposite, it's because `Makefile` with a capital M is traditional in the Unix world.

But, when there is no extension.

**Comment by jimmymcheung** [comment]
> Capital letters group it together with other similar configuration files and avoids it from being interspersed with other files and directories.

Do we have more config file start with c? Because I think files are group first by letters, then by whether it is capital or not

**Comment by jimmymcheung** [comment]
> It also bothers me a bit that the configuration format is so old, like the windows .ini files, if rust is a modern language, why didn't you use manifest or json structure files?

I’d prefer xml file or the current used syntax. Big dislike to json.

**Comment by ogxd** [comment]
Waiting for this issue to be re-opened...

**Comment by DavidBevi** [comment]
**+1** for *`cargo.toml`*

It's the only file that Tauri generates capitalized, so *`Cargo.toml` seems wrong*. Trying to rename it was the first thing I tried.

**Comment by ghost** [comment]
+1 for `cargo.(toml|lock)`, it feels very strange how every file in a project is lowercase except for `Cargo.toml` and `Cargo.lock`

**Comment by Driver86** [comment]
Что-то напомнило, как ждал иконку icq в font-awesome... так и не дождался xd
