### ISSUE TITLE
Cargo sometimes fails to generate documentation

### ISSUE THREAD

**Issue by korteland** [rust-lang/cargo#4503]
Specifically, it fails when:
* documentation has never been generated for that crate
* the crate has binaries in `src/bin/foo.rs` (as you would for a crate with multiple binaries).

To reproduce:
```
cargo new --bin tmp
cd tmp
cd src
mkdir bin
mv main.rs bin/
cd ..
cargo doc --open # fails to work
cargo run # works, prints "hello world"
```

**Comment by korteland** [comment]
For the time being, I've managed to work around it buy creating a "hello, world" `src/main.rs`, running `cargo doc --open`, and removing the second `main.rs`. I can reliably generate documentation after this.

**Comment by korteland** [comment]
Hmm. I just realised doc comments in `src/bin/main.rs` don't get rendered, even if `cargo doc --open` does something. Perhaps documentation generation for crates with multiple binaries is more broken than it first appeared? It seems like it should be supported.

**Comment by alexcrichton** [comment]
Sounds like a bug! We may not be guessing the right crate name or something like that...

**Comment by ehuss** [comment]
I'm not sure, but somewhere along the way this seems to have been fixed.
