### ISSUE TITLE
cargo bench fails with multiple --bench or --test arguments

### ISSUE THREAD

**Issue by rwakulszowa** [rust-lang/cargo#4504]
`cargo bench` runs all benchmarks
`cargo bench --bench=a` runs benchmark `a`
`cargo bench --bench=a --bench=b` gives `error: Invalid arguments.`
`cargo bench --test=a --test=b` gives `error: Invalid arguments.`

`cargo test --test=a --test=b` runs test suites `a` and `b`
`cargo test --bench=a --bench=b` runs test suites for benches `a` and `b`

It seems that `cargo bench` handles its command line arguments differently than `cargo test`.

**Comment by alexcrichton** [comment]
Thanks for the report! Probably a small bug with how we parse the command line arguments here...
