### ISSUE TITLE
Feature/Enhancement: `cargo doc --examples` to render example documentation

### ISSUE THREAD

**Issue by edmccard** [rust-lang/cargo#4508]
`cargo doc` has `--bin NAME` and `--bins` flags for documenting regular binaries; it would be nice to be able to write documentation (and have it rendered) for example binaries (that is, the ones in a project's `examples` directory).

**Comment by QiangHeisenberg** [comment]
This enhancement hasn't been done yet? This sounds interesting, and for me to understand the current crate feature is an example. My understanding is that ```cargo doc --example``` will display existing examples in the generated document. I'm interested in finishing it, so please tell me what else I need to finish.

**Comment by QiangHeisenberg** [comment]
Can this issue be closed?

**Comment by ehuss** [comment]
Yep, thanks!
