### ISSUE TITLE
`cargo build` failed with RUSTFLAGS="--print sysroot"

### ISSUE THREAD

**Issue by mssun** [rust-lang/cargo#4510]
cargo build will fail when passing RUSTFLAGS like `--print sysroot`, `--print native-static-libs`, etc.

I guess cargo will read stdout for other purposes?

For example:

```
$ cargo new hello_world --bin
     Created binary (application) `hello_world` project
$ cd hello_world
$ RUSTFLAGS="--print sysroot" cargo build
error: unexpected character in cfg `/`, expected parens, a comma, an identifier, or a string
```

Versions:
```
$ cargo -V
cargo 0.23.0-nightly (8118b02ac 2017-09-14)
```

**Comment by alexcrichton** [comment]
There's some initial stages where we parse some output from rustc that we still need to pass rustflags, how come you're passing these flags to all compliations? Shouldn't it just be the final compilation?

**Comment by mssun** [comment]
I intended to use a rustc flags (`--print native-static-libs`) to print out if my project relies on any native static libraries.

**Comment by mssun** [comment]
@alexcrichton I misunderstand the usage of the `--print native-static-libs` flag. Sorry for the trouble. Please close this issue if you think relying stdout from rustc is not an problem. Thanks.

**Comment by alexcrichton** [comment]
Ok, thanks for the update!
