### ISSUE TITLE
cargo build --bin src/main.rs

### ISSUE THREAD

**Issue by durka** [rust-lang/cargo#4512]
When I have `src/main.rs` as well as `src/bin/x.rs`, I can run `cargo build --bin x` to build only the latter, but I can't find a way to build only the former. Is there a way or is this missing?

**Comment by alexcrichton** [comment]
You can run `src/main.rs` with `cargo build --bin name-of-your-package` as that's the auto-assigned name to `src/main.rs`

**Comment by durka** [comment]
Could have sworn I tried that. But it works.
