### ISSUE TITLE
openssl-sys always recompiling

### ISSUE THREAD

**Issue by bfrog** [rust-lang/cargo#4514]
As of 0.9.18 of the openssl-sys crate cargo seems to decide to always recompile openssl-sys and all of its dependents. This is causing my project to go from maybe 20s to run cargo build to minutes.

Related issue suggesting this issue be taken up here
https://github.com/sfackler/rust-openssl/issues/732

**Comment by alexcrichton** [comment]
Thanks for the report! Can you set `RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info` and gist the output when Cargo recompiles when it shouldn't?

**Comment by sfackler** [comment]
Turns out that if you use rerun-if-changed rather than rerun-if-env-changed it'll always rebuild since the "files" it's talking about don't exist.

**Comment by alexcrichton** [comment]
Ah that'd do it!
