### ISSUE TITLE
Override location of Cargo.toml as optional arg for cargo command

### ISSUE THREAD

**Issue by paul-hammant** [rust-lang/cargo#4516]
Default is `Cargo.toml` in the current directory.  

It'd be cool to specify `cargo --config foo/bar/cArGo.toml otherArgs` if I wanted to.

**Comment by alexcrichton** [comment]
Does the `--manifest-path` option work for you?

**Comment by paul-hammant** [comment]
That's not current, is it?  It'd be fine if implemented yes (and some part of the description of that option in the help text said `Cargo.toml` as it is not super clear that manifest is a synonym for that config file for Rust-land.

I say that last because a "manifest" is something that's placed inside a JAR in java-land, and the config for a build would be in a build file like `pom.xml`, `ant.xml`, `gradle.build` co-located with the source of code.  I always thought the Maven team made a mistake and should have had maven.pom instead of pom.xml - IDEs can have a number of suffixes for xml.  I'm cursed on the command line forevermore because of this decision because on the Mac `open pom.xml` can only open a single OS-wide application, and my preference for Intellij for that one in particular would replace my preferred editor for other XML documents (Atom).

**Comment by alexcrichton** [comment]
Mind testing it out to see if it works? That was basically the first option ever implemented in Cargo.

**Comment by paul-hammant** [comment]
I did try it, and it wasn't there as an option. Not with the homebrew installed Cargo anyway - v0.21.0

**Comment by alexcrichton** [comment]
Can you gist what commands you were running?

**Comment by paul-hammant** [comment]
```
$ cargo --manifest-path rust/Cargo.toml test
error: Unknown flag: '--manifest-path'

Usage:
    cargo <command> [<args>...]
    cargo [options]
```

**Comment by alexcrichton** [comment]
Ah I believe that's a deficiency in Cargo's command line parsing, you'll need to use `cargo test --manifest-path ..` instead

**Comment by carols10cents** [comment]
I'm able to run `cargo test --manifest-path [path]`, so I'm going to close this issue. Thanks!
