### ISSUE TITLE
Allow linking to multiple libraries

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/cargo#4533]
Currently there is one library per package limitation. I'm trying to write a binding to a library which is distributed as 5 ar files (linked depending on configuration) and 2 system libraries. If we add a glue code that gives a total of 6 libraries. Creating 5 additional -sys cargo packages for libraries which doesn't have any documented interface between them seems a very strange solution.

Currently I WAR it with RUSTFLAGS to get things going but that seems to be non-ideal solution,

**Comment by alexcrichton** [comment]
Thanks for the report! This is not supported by Cargo today as syntacticaly this would require a lot of support options-wise and manifest-wise on crates.io and Cargo otherwise would need a large architectural overhaul to support this. For now you'll need to stick with the one-library-per-crate distinction.

**Comment by vmx** [comment]
If I understand this issue correctly, it asks for the same as the discussion at https://internals.rust-lang.org/t/how-about-changing-lib-to-lib-to-allow-multiple-library-in-a-crate/2022 is about. Wouldn't it then make sense to close this issue to make clear that it won't happen?

**Comment by alexcrichton** [comment]
Good point, thanks @vmx!

**Comment by uzytkownik** [comment]
@vmx  @alexcrichton are they? From what I understood the linked discussion it's about multiple rust libraries to single crate. I just wanted to link multiple C libraries inside a single Rust library. I don't see direct colleration:

- Linked proposal requires multiple outputs.
- My problem requires just adding a few extra parameters to rustc invocation I was able to do with RUSTFLAGS

I'm missing something fundamental?

**Comment by uzytkownik** [comment]
@vmx @alexcrichton Sorry for being insistent but what I'm asking for is relaxing Cargo.toml/build script format to allow emitting multiple `links`/`cargo:rustc-link-lib`. 

There are multiple alternatives but none of them are good:

### Repacking

    mkdir tmp/
    cd tmp/
    ar x ../libone.a
    ar x ../libtwo.a
    ar x ../libthree.a
    ar x ../libfour.a
    ar x ../libfive.a
    ar x ../librust_cpp_generated.a
    ar c librust_cpp_generated.a *
    runlib librust_cpp_generated.a
    mv librust_cpp_generated.a ../

Not 'all' I need to implement is searching for static libraries, Windows support, capture etc. I managed to trick [cpp_build](https://crates.io/crates/cpp_build) to link correctly.

### Override `RUSTFLAGS`

This one  I'm using now. It works but it makes build non-automatic:

    RUSTFLAGS="-lone -ltwo -lthree -lfour -lfive" cargo build

It also causes those libraries to be linked into all dependencies.

### Create -sys libraries

This means I have 5 additional libraries which contain no useful API as they have a private API. If I was to publish it on crates I would need to create 5 'junk' libraries no one would be using except as dependency.

### Summary

Since functionality already exists in Rust I really don't think it would be that hard/against Rust model to allow passing a list to links:

    [package]
    links = ['one', 'two', 'three', 'four', 'five']

or allow emitting multiple `rustc-link-lib`:

    # build.rs
    extern crate cpp_build;
    
    fn main() {
        println!("cargo:rustc-link-lib=static:one");
        println!("cargo:rustc-link-lib=static:two");
        println!("cargo:rustc-link-lib=static:three");
        println!("cargo:rustc-link-lib=static:four");
        println!("cargo:rustc-link-lib=static:five");
        cpp_build::build("src/lib.rs");
    }

What I am **NOT asking for** is multiple `[lib]` sections.

**Comment by alexcrichton** [comment]
Hm I'm not sure I undersatnd this issue then? What's the desired feature again?

**Comment by uzytkownik** [comment]
@alexcrichton I'd like to link to multiple system libraries using Cargo.toml or build script. In other words I'd like to be able to pass multiple `-l` and `-L` arguments to `rustc` using `cargo` command.

**Comment by uzytkownik** [comment]
@alexcrichton I'm referring to [this section of documentation](http://doc.crates.io/build-script.html#case-study-linking-to-system-libraries). Limitation of one `links = "foo"` works for many libraries but in my case I'm using a third party library which packages a single logical library as several archives. 

In other words I would like a single Rust library which links to several C libraries (well, they are not really system due to method of distribution).

If that not clarifies I'd be grateful for explanation of what is unclear.

**Comment by alexcrichton** [comment]
@uzytkownik have you tried printing `rustc-link-lib` multiple times? It sounds like you just shouldn't use `links` in the manifest

**Comment by uzytkownik** [comment]
@alexcrichton I believe I did. I can retry if that's suppose to work and dig in why it doesn't.

**EDIT:** After trying with rust from webpage instead of distribution and fudging a bit it worked.

**Comment by alexcrichton** [comment]
Ok, glad it works!

**Comment by alexcrichton** [comment]
@xxks-kkk Currently `rustc-link-args` can't be used to pass linker arguments, I don't think Cargo actually recognizes that key? You should be able to just use `rustc-link-lib` and have it work though.

**Comment by xxks-kkk** [comment]
Hello @alexcrichton, 

Thanks for the response. My situation is that I have a C program that can be compiled like the following:

```
/usr/bin/cc          -Wall         -Wextra         -Wno-unused-parameter         -Wno-missing-field-initializers         -Wmissing-declarations         -fno-strict-aliasing         -Wformat         -Wformat-security      -g  -rdynamic CMakeFiles/hello_nvme_bdev.dir/hello_nvme_bdev.c.o  -o hello_nvme_bdev  -L/home/zeyuanhu/spdk_install/lib  -L/home/zeyuanhu/dpdk_install/lib -Wl,-rpath,/home/zeyuanhu/spdk_install/lib:/home/zeyuanhu/dpdk_install/lib -Wl,-z,relro,-z,now -Wl,-z,noexecstack -pthread -Wl,--whole-archive /home/zeyuanhu/spdk_install/lib/libspdk_copy_ioat.a /home/zeyuanhu/spdk_install/lib/libspdk_ioat.a -Wl,--no-whole-archive -Wl,--whole-archive /home/zeyuanhu/spdk_install/lib/libspdk_vbdev_lvol.a /home/zeyuanhu/spdk_install/lib/libspdk_blob.a /home/zeyuanhu/spdk_install/lib/libspdk_blob_bdev.a /home/zeyuanhu/spdk_install/lib/libspdk_lvol.a /home/zeyuanhu/spdk_install/lib/libspdk_bdev_malloc.a /home/zeyuanhu/spdk_install/lib/libspdk_bdev_null.a /home/zeyuanhu/spdk_install/lib/libspdk_bdev_nvme.a /home/zeyuanhu/spdk_install/lib/libspdk_nvme.a /home/zeyuanhu/spdk_install/lib/libspdk_vbdev_passthru.a /home/zeyuanhu/spdk_install/lib/libspdk_vbdev_error.a /home/zeyuanhu/spdk_install/lib/libspdk_vbdev_gpt.a /home/zeyuanhu/spdk_install/lib/libspdk_vbdev_split.a /home/zeyuanhu/spdk_install/lib/libspdk_bdev_aio.a /home/zeyuanhu/spdk_install/lib/libspdk_bdev_virtio.a /home/zeyuanhu/spdk_install/lib/libspdk_virtio.a -Wl,--no-whole-archive -laio -Wl,--whole-archive /home/zeyuanhu/spdk_install/lib/libspdk_sock.a /home/zeyuanhu/spdk_install/lib/libspdk_sock_posix.a -Wl,--no-whole-archive -Wl,--whole-archive /home/zeyuanhu/spdk_install/lib/libspdk_event_bdev.a /home/zeyuanhu/spdk_install/lib/libspdk_event_copy.a -Wl,--no-whole-archive /home/zeyuanhu/spdk_install/lib/libspdk_bdev.a /home/zeyuanhu/spdk_install/lib/libspdk_copy.a /home/zeyuanhu/spdk_install/lib/libspdk_event.a /home/zeyuanhu/spdk_install/lib/libspdk_thread.a /home/zeyuanhu/spdk_install/lib/libspdk_util.a /home/zeyuanhu/spdk_install/lib/libspdk_conf.a /home/zeyuanhu/spdk_install/lib/libspdk_trace.a /home/zeyuanhu/spdk_install/lib/libspdk_log.a /home/zeyuanhu/spdk_install/lib/libspdk_jsonrpc.a /home/zeyuanhu/spdk_install/lib/libspdk_json.a /home/zeyuanhu/spdk_install/lib/libspdk_rpc.a /home/zeyuanhu/spdk_install/lib/libspdk_env_dpdk.a -Wl,--start-group -Wl,--whole-archive /home/zeyuanhu/dpdk_install/lib/librte_eal.a /home/zeyuanhu/dpdk_install/lib/librte_mempool.a /home/zeyuanhu/dpdk_install/lib/librte_ring.a /home/zeyuanhu/dpdk_install/lib/librte_mempool_ring.a /home/zeyuanhu/dpdk_install/lib/librte_pci.a /home/zeyuanhu/dpdk_install/lib/librte_bus_pci.a /home/zeyuanhu/dpdk_install/lib/librte_kvargs.a -Wl,--end-group -Wl,--no-whole-archive -lnuma -ldl -lrt -luuid -lcrypto
```

Now, I'm experimenting with FFI and rewrite the C program using Rust with the help of bindings created by the `bindgen`. In my `build.rs`,  I directly copy the link arguments as

```rust
# _spdk_dir has value: /home/zeyuanhu/spdk_install
println!("cargo:rustc-link-search={}/lib", _spdk_dir);
# _dpdk_dir has value: /home/zeyuanhu/dpdk_install
println!("cargo:rustc-link-search={}/lib", _dpdk_dir);

println!("cargo:rustc-link-lib=-Wl,-rpath,/home/zeyuanhu/spdk_install/lib:/home/zeyuanhu/dpdk_install/lib ...");
```

However, during `cargo test`, Rust gives the error

```
renaming of the library `-Wl,-rpath,/home/zeyuanhu/spdk_install/lib` was specified, however this crate contains no #[link(...)] attributes referencing this library.
```

So, I remove `-Wl,-rpath,/home/zeyuanhu/spdk_install/lib` and keep the rest link arguments and I got

```
/usr/bin/ld: cannot find -l-Wl,-z,relro,-z,now -Wl,-z,noexecstack -pthread -Wl ...
```

The C libraries I link with are very sensitve to the linking order and I'm wondering what's the solution I may need to look into in Rust?

Thanks much!

**Comment by alexcrichton** [comment]
@xxks-kkk I think what you want to do basically isn't supported. If you need to specify custom linker flags then you'll need to wrap Cargo rather than trying to pass the arguments via a build script (which isn't supported). Instead you'll want to compile a `staticlib` and then invoke the linker yourself.

**Comment by xxks-kkk** [comment]
Hello @alexcrichton Thank you for the pointers. That's definitely another direction I can look into. Meanwhile, I try to use `.cargo/config` to pass the link arguments. Everything seems to work except that my static C library requires some header definition. I try to include those header files using 

```
"-C", "link-arg=-L", "-C", "link-arg=/home/zeyuanhu/spdk_install/include"
```
 
 I also tried 

```
"-C", "link-args=-I /home/zeyuanhu/spdk_install/include"
```

None of them works for me. My question is in Rust, if I use any C static libraries that require headers definition locate in other place, how can I incoporate those headers during the build? In C, I can include those header files in side my C program but I'm not sure what to do in the Rust.

Thanks much for the help!

**Comment by JackLiar** [comment]
> @alexcrichton I believe I did. I can retry if that's suppose to work and dig in why it doesn't.
> 
> 
> 
> **EDIT:** After trying with rust from webpage instead of distribution and fudging a bit it worked.

Would you explain how to implement this? I printed it multiple times but still failed to link multiple shared libraries
