### ISSUE TITLE
Remove stub-closures?

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/cargo#4540]
Is there (still) a reason which eludes me for closures like the following?

https://github.com/rust-lang/cargo/blob/a1489e8316139b97e0db5f50570b2452e1d9f659/src/cargo/core/registry.rs#L224-L238

A simple block should be enough for the `.chain_err()`. May I remove the one abve and the 10 other closures alike?

**Comment by alexcrichton** [comment]
If they can be removed, sure!

**Comment by Mark-Simulacrum** [comment]
Marking as an "easy" bug -- if this works, it should work, if not, then it won't. Happy to provide mentoring.

**Comment by stevel98** [comment]
Hi, is this still open? If not, I'd like to take it as a first PR.

**Comment by Mark-Simulacrum** [comment]
I don't think this will actually work (and I don't think it would have originally). The stub-closure is needed to ensure that all error paths go through the chain_err, whereas the block wouldn't result in the same behavior, as `?` goes to function boundary, not block boundary.
