### ISSUE TITLE
Difficult to use the presence of an optional dependency to use an optional dependency in a non-optional dependency

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/cargo#4548]
Phew!  That issue title was a mouthful.  So for context see this PR: https://github.com/kvark/collision-rs/pull/38 

We want to export a feature called "serde" and only turn on the "serde" feature in cgmath if our "serde" feature is enabled.  We were able to accomplish this with a few workarounds, but it was fairly non-obvious how to do what might become a common task.

In addition to this it was also discovered that proc-macro crate dependencies are silently ignored if placed under a dependency section using `target.'cfg(...)'.dependencies` I imagine this is due to needing the macro system to evaluate the cfg statement, but it's still annoying and behaves unexpectedly.

**Comment by Xaeroxe** [comment]
```
$ cargo --version
cargo 0.21.0 (5b4b8b2ae 2017-08-12)
```

**Comment by Xaeroxe** [comment]
Something that might help this situation would be having the ability to specify additional feature lists like `["serde", "serde_derive", "cgmath/serde"]` with an optional dependency, and not just as part of a feature not attached to a dependency.

Alternatively: Permit a feature named serde to exist alongside an optional dependency called serde **if and only if** that feature also has "serde" in its feature list so that the optional serde crate is used.  (That's kind of a complicated ruleset so I'm not sure if I like this idea)

**Comment by Xaeroxe** [comment]
> proc-macro crate dependencies are silently ignored

I wanted to provide a few more details on this.  So with this project structure
[collision-rs.zip](https://github.com/rust-lang/cargo/files/1342268/collision-rs.zip). The following commands give the following output (rust stable as default with rust nighty installed as well)

```
$ cargo check
error: failed to learn about crate-type `proc-macro` early on

$ cargo +nightly check
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs

$ cargo +nightly check --features="serde"
   Compiling collision v0.11.0 (file:///C:/Users/JKiesel.CISDEV/collision-rs)
error[E0463]: can't find crate for `serde_derive`
  --> src\lib.rs:46:1
   |
46 | extern crate serde_derive;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `collision`.

To learn more, run the command again with --verbose.

```

**Comment by alexcrichton** [comment]
Thanks for the report! @Xaeroxe would this perhaps be solved by https://github.com/rust-lang/cargo/issues/1286?

**Comment by Xaeroxe** [comment]
@alexcrichton Yes, that RFC sounds great, but doesn't it break backwards compatibility?

**Comment by alexcrichton** [comment]
@Xaeroxe ok! In that case I'm going to close this in favor of that issue.

Strictly interpreted it does indeed break backwards compatibility, but there's a number of possible solutions we could employ to avoid the breaking change.
