### ISSUE TITLE
Cargo doesn't link c++ std lib

### ISSUE THREAD

**Issue by shayanjm** [rust-lang/cargo#4549]
I am currently trying to work with https://github.com/flier/rust-hyperscan. I recently updated cargo via rustup and started noticing that my code breaks when run. 

I am currently running MacOS 10.12.6 and cargo 0.21.0

This is a contrived example, mostly from the upstream "rust-hyperscan" project, which includes the output error I'm seeing when I run `cargo clean && cargo test`: https://gist.github.com/shayanjm/aa7a9ebb0bddd1beb8ec4f3d3f87463b

On L80 of build.rs (https://gist.github.com/shayanjm/aa7a9ebb0bddd1beb8ec4f3d3f87463b#file-build-rs-L80) I've verified that the println! runs as expected by changing `c++` to something I know would break and retrying `cargo clean && cargo test`.

I've also verified that `libc++` has the symbols in question via `nm -gU /usr/lib/libc++dylib | grep dynamic`, which returned `0000000000018c54 I ___dynamic_cast` (the first "undefined symbol" in the error)

Is this an issue with the way Cargo is linking the c++ std lib? Or have I done something wrong?

**Comment by alexcrichton** [comment]
Thanks for the report! In general Cargo's not really responsible for linkage and that boils down to crates themselves or rustc, so this may be the wrong place for this issue?

**Comment by shayanjm** [comment]
Gotcha! I wasn't sure where exactly to trace the blame to. I'll try surfacing this over @ rustc. Thanks!

**Comment by alexcrichton** [comment]
Ok!
