### ISSUE TITLE
[patch] forces registry update at every build

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#4552]
I’m currently working from a moving train (with spotty connectivity) on testing Servo with local cssparser modifications:

```toml
[patch.crates-io]
cssparser = { path = "../rust-cssparser" }
```

On every iteration of the edit-compile-test cycle, Cargo spends a few seconds updating the registry even though everything needed to build is already available in cache:

```
$ cargo check
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling selectors v0.19.0 (file:///home/simon/projects/servo/components/selectors)
[…]
```

It looks like I wouldn’t be able to work at all without connectivity. Adding `--frozen` doesn’t help, even though `Cargo.lock` wouldn’t change:

```
$ cargo check --frozen
error: failed to load source for a dependency on `cssparser`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  attempting to make an HTTP request, but --frozen was specified
```

Is it perhaps having `[patch]` in place that makes Cargo over-eager to check if a seconds-old cache is out of date?

**Comment by SimonSapin** [comment]
> It looks like I wouldn’t be able to work at all without connectivity.

Yup.
```
$ cargo check
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: spurious network error (2 tries remaining): [12/-1] curl error: Couldn't resolve host 'github.com'

warning: spurious network error (1 tries remaining): [12/-1] curl error: Couldn't resolve host 'github.com'

error: failed to load source for a dependency on `cssparser`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [12/-1] curl error: Couldn't resolve host 'github.com'
```

**Comment by SimonSapin** [comment]
Unfortunately I did not manage to reproduce this outside of Servo. Here is my attempt:

```sh
cargo new matches
sed -i s/0.1.0/0.1.999/ matches/Cargo.toml
cargo new foo
echo 'matches = "0.1"' >> foo/Cargo.toml
echo '[patch.crates-io]' >> foo/Cargo.toml
echo 'matches = {path = "../matches"}' >> foo/Cargo.toml
echo 'error' >> foo/src/lib.rs
(cd foo && cargo build)
echo
echo ===== Second build ======
echo
sleep 1
touch foo/src/lib.rs
(cd foo && cargo build)
rm -r foo matches
```

("Updating registry" is correctly skipped after "Second build".)

----

As discussed with @alexcrichton, here is the output of `RUST_LOG=cargo=trace ./mach check -p cssparser 2>/tmp/log` (`./mach check` ends up executing `cargo check`.) Or was is some submodule under `cargo::`?

https://gist.github.com/anonymous/88184dfc4e5f4a3d52bdf603fbe25e96

**Comment by alexcrichton** [comment]
Ok found the bug, fix coming soon!

**Comment by alexcrichton** [comment]
Ok, fixed at https://github.com/rust-lang/cargo/pull/4583
