### ISSUE TITLE
Add support for removing multiple packages with cargo uninstall

### ISSUE THREAD

**Issue by nossralf** [rust-lang/cargo#4560]
The ergonomics of `cargo uninstall` would be improved if it supported uninstalling multiple packages at once.

Since many tools (rustfmt included) require nightly to install, it's not uncommon to use nightly with `cargo install`. However, since nightly receives daily updates, the binaries installed with `cargo install` usually stop working with a nightly update (since the underlying dynamic library file names tend to change) which requires frequent `cargo uninstall`/`cargo install` gymnastics.

Furthermore, supporting uninstallation of multiple packages with a single command would mirror the ability to install multiple packages with a single `cargo install` command.

Open question:
- How should specifying `--bin` interact with uninstallation of multiple packages? (I believe this isn't handled in the `cargo install` case, so it may be a moot point here as well.)

**Comment by withoutboats** [comment]
> Since many tools (rustfmt included) require nightly to install, it's not uncommon to use nightly with cargo install. However, since nightly receives daily updates, the binaries installed with cargo install usually stop working with a nightly update (since the underlying dynamic library file names tend to change) which requires frequent cargo uninstall/cargo install gymnastics.

To me it seems like we should provide tooling to avoid those gymnastics rather than making the gymnastics easier to do - that is, some way to rebuild the cargo install'd projects that depend on nightly dynamic libraries when nightly is updated.

**Comment by nossralf** [comment]
I can get on-board with that.

However, I still believe it's worth having `cargo uninstall` be more similar to `cargo install`'s current behavior in supporting multiple package specs. It also makes life a tad easier in the meantime.
