### ISSUE TITLE
Separate target configuration output directories

### ISSUE THREAD

**Issue by parkovski** [rust-lang/cargo#4577]
#4427 related. I use the Linux subsystem on Windows 10 and commonly build a Windows and Linux build from the same project folder - currently both binaries end up in `target/debug`. It'd be nice to have the option to set up target-based outputs, so I could get Windows binaries in `target/windows/debug` and Linux in `target/linux/debug`.

My preference for this would be providing some interpolated variables so I could put something like this in my `Cargo.toml`:
```
output-dir = "target/${target.os}/${profile}"
```

**Comment by sfackler** [comment]
This will happen if you pass `--target` explicitly.

**Comment by alexcrichton** [comment]
Thanks for the report! As @sfackler notes, however, this already happens when you pass `--target`
