### ISSUE TITLE
add way to print the dependency graph

### ISSUE THREAD

**Issue by metajack** [rust-lang/cargo#460]
This is useful for debugging and checking that the graph is what you think it is.

**Comment by frewsxcv** [comment]
Hey, just discovered this thread. I'm working on a web service (hosted on heroku) that automatically generates the dependency graph images

https://github.com/frewsxcv/crate-deps

If anyone has ideas for improvements, let me know

**Comment by dtolnay** [comment]
[Cargo-tree](https://github.com/sfackler/cargo-tree) is another great solution.

**Comment by vhakulinen** [comment]
Expected to have this functionality builtin but cargo-tree did the job.

Are there any plans to implement this in cargo it self?
