### ISSUE TITLE
"the lock file needs to be updated but --locked was passed to prevent this" error message is unhelpful

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/cargo#4603]
While working on Stylo, several times I have hit this error message:

> error: the lock file needs to be updated but --locked was passed to prevent this

This is an unhelpful error message. At the very least, it should print the path to the lock file, because when building Stylo there are multiple lock files and it's not obvious which one is the problem.

If it can print more than that -- e.g. identifying how the lock file needs changing -- that would be even better.

**Comment by soig** [comment]
I have the same issue

**Comment by nnethercote** [comment]
This is still relevant.

Also, I'm not a fan of closing bugs/PRs merely due to inactivity. It's too close to CADT for comfort: https://www.jwz.org/blog/2003/02/the-cadt-model/.

**Comment by dwijnand** [comment]
I think if someone shared a reproduction of this issue it would help it being resolved.

**Comment by dwijnand** [comment]
Lovely, thank you @ehuss!

Perhaps I'll be able to solve this (no promises).
