### ISSUE TITLE
Git dependency requiring auth doesn't check for `"$XDG_CONFIG_HOME"/git/config`.

### ISSUE THREAD

**Issue by ErichDonGubler** [rust-lang/cargo#4605]
I'm using a private repo in Gitlab as a dependency for another binary crate I'm developing, and rely on Git HTTPS authentication for my dependencies. **Since recently moving my Git config files to `$XDG_CONFIG_HOME` (in my case, `~/.config/git/config`), Cargo no longer can find my Git configuration**, which seems to indicate that Cargo isn't checking `$XDG_CONFIG_HOME`.

## Reproduction Steps

Steps to reproduce this are actually fairly straightforward:

1. **Create a new Cargo project with `cargo init`.** Cargo's default to a lib crate shouldn't matter.
2. In the `Cargo.toml`, **add a dependency on an HTTPS Git repo that requires authentication**, like `something = { git = "https://gitlab.com/erichdongubler-SaveGmailToGoogleDrive/sorter" }`.
3. Run `cargo build` and observe that an error along the lines of `warning: spurious network error (2 tries remaining): [2/-1] could not find 'C:/Users/egubler/.gitconfig' to stat: The system cannot find the file specified.` is printed, and the build fails.

<details>
<summary>Full command output</summary>

```
~/…/experiments/cargo_bug_reproduction HEAD$ cargo build
    Updating git repository `https://gitlab.com/erichdongubler-SaveGmailToGoogleDrive/sorter`
warning: spurious network error (2 tries remaining): [2/-1] could not find 'C:/Users/egubler/.gitconfig' to stat: The system cannot find the file specified.
warning: spurious network error (1 tries remaining): [2/-1] could not find 'C:/Users/egubler/.gitconfig' to stat: The system cannot find the file specified.

error: failed to load source for a dependency on `something`

Caused by:
  Unable to update https://gitlab.com/erichdongubler-SaveGmailToGoogleDrive/sorter

Caused by:
  failed to clone into: C:\Users\egubler\.cargo\git\db\sorter-412f2267324837b9

Caused by:
  failed to authenticate when downloading repository
attempted to find username/password via git's `credential.helper` support, but failed

To learn more, run the command again with --verbose.
```
</details>

<br>

**My expectation is that Cargo would look for a Git configuration at `~/.gitconfig` AND `${XDG_CONFIG_HOME:-~/.config}/git/config`.**

## Environment information

* Window 10 Pro, version 10.0.15063 (x64)
* I am using MSYS2 vanilla (found at http://www.msys2.org/).
* I use `~/.profile` (which gets sourced by my `profile` shell scripts) to set `XDG_CONFIG_HOME` to `$HOME/.config`.

    I use both `bash` AND `zsh` regularly. 
* My `$HOME` is set to `/home/egubler`, which is symlinked to `C:\Users\egubler`.
* Reproducible on MSVC and GNU toolchains, both for `stable` and `nightly-2017-10-09`. Cargo versions tested:
   * `cargo 0.21.0 (5b4b8b2ae 2017-08-12)`
   * `cargo 0.23.0-nightly (e447ac7e9 2017-09-27)`

**Comment by ehuss** [comment]
It seems to work for me when placed into `~/.config/git/config`.  I can try to help you if you'd like, I was just recently digging into this code recently.  

It's a bit of a headscratcher why you are getting the stat errors.  No matter what I do I can't reproduce that.  You don't have any symlinks or anything like that?

Are you setting the XDG_CONFIG_HOME environment variable somewhere?  If not, you may want to check if there are other config files.  libgit2 will pick the first one it finds in the list:
* `%XDG_CONFIG_HOME%\git\config`
* `%APPDATA%\git\config`
* `%LOCALAPPDATA%\git\config`
* `%HOME%\.config\git\config`
* `%HOMEDRIVE%%HOMEPATH%\.config\git\config`
* `%USERPROFILE%\.config\git\config`

**Comment by ErichDonGubler** [comment]
@ehuss: Some things that may be relevant to what you're asking:
* I am using MSYS2 vanilla (found at http://www.msys2.org/).
* I use `~/.profile` (which gets sourced by my `profile` shell scripts) to set `XDG_CONFIG_HOME` to `$HOME/.config`.

    I use both `bash` AND `zsh` regularly. 
* My `$HOME` is set to `/home/egubler`, which is symlinked to `C:\Users\egubler`.

Should I experiment with simply setting `$HOME`, instead of symlinking?

Also, if it simplifies things, I can put this information in the OP. :)

**Comment by ehuss** [comment]
Ah.  I haven't spent much time in the msys2 environment.  Sorry, I don't know much about it.
