### ISSUE TITLE
Enhancement: List which versions of crates are `cargo install`ed

### ISSUE THREAD

**Issue by mcandre** [rust-lang/cargo#4606]
For debugging purposes, it would be really helpful if the Rust cargo package manager was able to list which exact versions of crates have been installed using `cargo install`.

**Comment by carols10cents** [comment]
Is Cargo.lock not sufficient?

**Comment by mcandre** [comment]
Not quite. If a package was installed outside of a per-project context via `cargo install <package>`, then I don't expect there would be a Cargo.lock.

**Comment by carols10cents** [comment]
Oooohhh I see. I was missing that you meant `cargo install`, not "installing a dependency to use in a project". That clears it up!

**Comment by carols10cents** [comment]
Actually, now that I understand, is `cargo install --list` not sufficient?

**Comment by dwijnand** [comment]
I think `cargo install --list` is what @mcandre was looking for!
