### ISSUE TITLE
Add "readme" documentation to docs.crates.io

### ISSUE THREAD

**Issue by alfiedotwtf** [rust-lang/cargo#4620]
I can't seem to find any documentation on the "readme" config item in Cargo.toml (which is a link to the file used to display on the crate's page on crates.io)... the only way I found out which setting to add in order to get the README.md to render on my crate's page was to copy what others have done...

This issue is to make this a bit clearer in crates.io's docs.

**Comment by ehuss** [comment]
This appears to be fixed by #4644.
