### ISSUE TITLE
Cargo 0.22 not on crates.io

### ISSUE THREAD

**Issue by roblabla** [rust-lang/cargo#4621]
Heya, I'm developing a tool that depends on cargo's API directly. I got a request to update it to the latest version of cargo, but to my surprise it wasn't uploaded on `crates.io` : https://crates.io/crates/cargo latest is 0.21.1. Is there a reason behind this, or is it just an oversight ?

Additionally, there's no `0.22.0` tag on the git ?

**Comment by steveklabnik** [comment]
The reason is that @alexcrichton is traveling; this is expected to be fixed early next week.

**Comment by alexcrichton** [comment]
Done!
