### ISSUE TITLE
Fails to preserve transitive dylib order with intermediate

### ISSUE THREAD

**Issue by lolgesten** [rust-lang/cargo#4622]
I think there may be a problem with cargo not keeping dependency order for transitive dependencies.

I have this situation:

```
project/
    Cargo.toml
    main.rs
    fancylib/
        Cargo.toml
        build.rs
        lib.rs
    subcomponent/
        Cargo.toml
        build.rs
        lib.rs
```

`fancylib` is a wrapper around a third party lib that is a C++ lib, but has a C-interface that I wrap. However it does need `stdc++` when linking. `fancylib/build.rs` builds the C++ lib and outputs `cargo:rustc-link-lib=ap4`

`subcomponent` builds some higher level API using `fancylib` also in C, but exposing higher level API as safe rust.

Finally `main.rs` uses the `subcomponent` to produce some binary.

Building this on the top level fails, because the order of `ap4` and `stdc++` is not preserved (stdc++ must come _after_ ap4).

I've tried to express the `stdc++` dependency in fancylib both as `#[link(name="stdc++")]` and `cargo:rustc-flags=-l stdc++`, but both results in the same (wrong) order. Incidentally the order seems to be OK on macOS but not Linux (maybe it's random?).

This is the `cc` that fails when building the intermediary lib from the top level with `cargo test --all`:

```
"cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" 
"/usr/local/rustup/toolchains/1.21.0-x86_64-unknown-linux-gnu
/lib/rustlib/x86_64-unknown-linux-gnu/lib" ... "-l" "stdc++" "-l" "ap4" ...
```

The error are a ton of these (which indicates `stdc++` is missing):

```
/usr/src/.../Ap4Interfaces.h:65: undefined reference to `operator delete(void*, unsigned long)'
```

**Comment by lolgesten** [comment]
Edit: Turns out this is specifically when using `cargo test --all`

**Comment by lolgesten** [comment]
And it's when building the tests for `subcomponent`

**Comment by lolgesten** [comment]
I might have solved it... maybe the magic sauce is:

```
    println!("cargo:rustc-link-lib=ap4");
    println!("cargo:rustc-link-lib=stdc++");
```

**Comment by carols10cents** [comment]
@lolgesten So is this still an issue? Or do you consider the solution you found to be a non-ideal workaround?

**Comment by lolgesten** [comment]
I guess the only thing would maybe be to clarify the "Cargo build script" docs in terms of transitive dependencies. Maybe my reading comprehension, but I assumed you could only have one single`cargo:rustc-link-lib=ap4` which would be the output of the `build.rs`.
