### ISSUE TITLE
cargo-metadata doesn't track target-specific dependencies

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#4632]
While the target configuration for a dependency is included in cargo-metadata's output (e.g. `cfg(windows)`), it's not all that easy to filter down to the dependencies that are enabled for a given target. It'd be nice if cargo-metadata could optionally perform the target-specific filtering.

**Comment by sfackler** [comment]
cargo-tree still needs this before it can stop using cargo-the-library.

**Comment by ehuss** [comment]
I'm going to close, as I think this is now implemented via the `--filter-platform` flag (#7376).  Alternatively, the [`cargo-platform`](https://crates.io/crates/cargo-platform) crate can be used to parse the expressions and compare against the output of `rustc --print=cfg`.
