### ISSUE TITLE
cargo-doc and reexported types

### ISSUE THREAD

**Issue by DarkEld3r** [rust-lang/cargo#4639]
Example (`lib.rs`):
```rust
extern crate serde;

pub mod reexport {
    pub use serde::Serialize;
    pub use serde::ser::Error as SerError;
}
```
In the generated documentation for the `reexport::SerError` type there is a reference to the `serde::Serialize`, but this reference is broken (`target/doc/reexport_test/trait.Serialize.html` instead of `target/doc/reexport_test/reexport/trait.Serialize.html`).

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a bug with rustdoc though perhaps, not Cargo? Mind reopening in rust-lang/rust?
