### ISSUE TITLE
Misinterpreted urls with + in the scheme

### ISSUE THREAD

**Issue by vorner** [rust-lang/cargo#4652]
If I run `cargo install --git git+https://github.com/vorner/jsonrpc-param-ord`, I get this:

```
     Updating git repository `git+https://github.com/vorner/jsonrpc-param-ord`
warning: spurious network error (2 tries remaining): [12/-1] failed to resolve address for git+https: Temporary failure in name resolution
warning: spurious network error (1 tries remaining): [12/-1] failed to resolve address for git+https: Temporary failure in name resolution
```

This seems like a misparsed URL, but I didn't manage to trigger it within the newest `url` crate, so maybe the upstream problem is already gone.

It works OK if I use `https://github.com/...`

**Comment by alexcrichton** [comment]
Thanks for the report! This is a cargo-private encoding, though, and as reported the `git+` syntax is not a valid url, which `--git` requires.

**Comment by vorner** [comment]
Well, even if it is invalid, the error message is kind of wrong. It obviously tries to use „git+https“ as a host name. An „invalid URL format“ or something would be more appropriate.

However, if it *is* invalid, why does cargo put invalid URLs into .cargo/crates.toml. That's where I copy-pasted the URL from in the first place.

**Comment by alexcrichton** [comment]
The metadata for Cargo is just that, metadata for Cargo which is intended to be private
