### ISSUE TITLE
intermittent linker errors on 32-bit MSVC builds

### ISSUE THREAD

**Issue by dimbleby** [rust-lang/cargo#4655]
32-bit MSVC builds for my [c-ares-resolver project](https://github.com/dimbleby/c-ares-resolver) intermittently fail like this:

> fatal error LNK1318: Unexpected PDB error; RPC (23) '(0x000006BA)'

Appveyor build history showing lots of failures [here](https://ci.appveyor.com/project/dimbleby/c-ares-resolver/history).

This looks similar to #3161, but fixes made there are surely long released - so I suppose this is something else.

(It wasn't clear to me whether I should be raising this against cargo or rustc or what - apologies if I've guessed wrong).

**Comment by alexcrichton** [comment]
I wonder if this may have to do with racing build scripts? Unfortunately I don't know how this could resurface :(

The problem here is that a `link.exe` is killed when multiple processes are using it, and the other processes all fail with an error when that happens. Do you have anything in your build which executes `cargo` or `rustc`?

**Comment by dimbleby** [comment]
The failing step is `cargo test`.  I'm not doing anything *else* that runs cargo or rustc, though.

**Comment by dimbleby** [comment]
That will involve building the three separate programs that I have in `examples`.  Does cargo do this in parallel?  Perhaps something going wrong there?

This would be consistent with the fact that the corresponding build for the [rust-c-ares project](https://github.com/dimbleby/rust-c-ares) does _not_ fail in this way - in that one I (weirdly) structured my examples as one big program.

**Comment by dimbleby** [comment]
FWIW I've had two examples since forever, but first saw this failure on 4th August in [this build](https://ci.appveyor.com/project/dimbleby/c-ares-resolver/build/1.0.77) with rustc 1.19.0 and 
cargo 0.20.0.

If the issue was provoked by something I changed: well, [here](https://github.com/dimbleby/c-ares-resolver/commit/1306564893af8ac6a7e8feaf40e172843a154cd5) is the change - tweaking the way that rust is installed on the appveyor boxes.

Builds before that look to have been consistently successful (at least from the point of view of this problem).

**Comment by alexcrichton** [comment]
Ah sorry what I meant is that as part of the build, for example in a build script, are you running rustc/cargo/rustup/etc?

**Comment by dimbleby** [comment]
Not sure whether you missed my answer - which would be my own fault for then making two additional updates - or I misunderstood the question.

> The failing step is cargo test. I'm not doing anything else that runs cargo or rustc, though.

Does that answer the question?

**Comment by alexcrichton** [comment]
Yes I understand you're executing `cargo test`. I'm wondering if within that `cargo test` the build is executing something like `rustc --version` or compiling a shim in a build script.

**Comment by dimbleby** [comment]
No, there's no build script.

(there is a build script in a dependency - `c-ares-sys` - but I have [just experimented](https://ci.appveyor.com/project/dimbleby/c-ares-resolver/build/1.0.114) with separating `cargo build` and `cargo test`, and still see failures at `cargo test`.  so I don't think that can be relevant.  

I'm [currently experimenting](https://ci.appveyor.com/project/dimbleby/c-ares-resolver/build/1.0.115) with `cargo test -j1` and provisionally this looks as though it might be a successful workaround, though I'll want a few more clean builds before I'm convinced).

**Comment by alexcrichton** [comment]
Looking at some failing logs it looks like the failure is isolated to i686 and always happens on the c-ares crate itself (typically in examples, sometimes not). Basically this looks precisely like https://github.com/rust-lang/rust/issues/33145, so something is killing a linker (presumably).

Can you try setting `RUST_LOG=rustup-cli=info,cargo::util::job` and see what's printed?

**Comment by dimbleby** [comment]
build [under way](https://ci.appveyor.com/project/dimbleby/c-ares-resolver/build/1.0.119).

**Comment by alexcrichton** [comment]
Hm maybe `rustup_cli` instead of `rustup-cli`?

**Comment by alexcrichton** [comment]
(I forget the precise syntax)

**Comment by dimbleby** [comment]
well I've never known about this, much less forgotten it!  Happy to follow instructions - just let me know what you want to try.

(having said that I'll be away from the computer soon so will shortly go unresponsive)

meanwhile I see that the previous build exhibited no failures - obviously when you want it to fail it doesn't! - I'll kick off another.

**Comment by Geobert** [comment]
Even in 64bits build we got this error in cobalt.rs project: https://github.com/cobalt-org/cobalt.rs/pull/352
