### ISSUE TITLE
Easy way to recompile all tools with each nightly

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#4662]
Every time I install a new rust nightly on macos via rustup, rustfmt, clippy, etc. break with this error:

```shell
dyld: Library not loaded: @rpath/libsyntax-4bd9bd9f671767da.dylib
  Referenced from: /Users/gnzlbg/.cargo/bin/rustfmt
  Reason: image not found
```

Is there an easy way to recompile all of them when installing a new nightly?

**Comment by Mark-Simulacrum** [comment]
Not today -- but eventually we hope to ship rustfmt and clippy as part of the standard distribution (available via rustup). How that will work remains to be decided, though. For today the best solution is probably to reinstall them via `cargo install -f rustfmt`.

**Comment by ehuss** [comment]
rustfmt and clippy are now distributed with rustup, so I'm going to close this for now.
