### ISSUE TITLE
MacOS deployment target

### ISSUE THREAD

**Issue by pronebird** [rust-lang/cargo#4667]
Targeting macOS builds we found that we needed to set `MACOSX_DEPLOYMENT_TARGET=10.9` explicitly when building with cargo in order for code signing to produce the right SHA-1 hash for older macOS versions. Is it possible to set deployment target via `Cargo.toml`?

**Comment by alexcrichton** [comment]
Nah yeah unfortunately you can't do this in `Cargo.toml`, but I think you can print out `cargo:rustc-env=...` nowadays in build scripts?

**Comment by alexcrichton** [comment]
Closing as I believe this can be done with `cargo:rustc-env`

**Comment by simonbuchan** [comment]
Using `MACOSX_DEPLOYMENT_TARGET` in any way results in messages like this (visible if the compile fails for other reasons):

```
  = note: ld: warning: object file (/Users/simon/code/agent-ui-test/target/debug/deps/libobjc_exception-fd1aed02df04e3f9.rlib(exception.o)) was built for newer macOS version (11.0) than being linked (10.10)
```

Not sure if that could be a problem.

**Comment by bridiver** [comment]
@simonbuchan we're seeing that as well which is a bit concerning. Maybe the env isn't getting passed through to some subprocess?
