### ISSUE TITLE
Alternate Sources for downloads

### ISSUE THREAD

**Issue by shingtaklam1324** [rust-lang/cargo#4670]
Currently, when cargo compiles programs, it downloads crates from `crates-io.s3-us-west-1.amazonaws.com`, which isn't  available from some regions (AWS US is not available in the People's Republic of China without a VPN / Proxy).

Perhaps multiple download servers could be used for different regions.

**Comment by alexcrichton** [comment]
cc @carols10cents about mirrors and such

Unfortunately right now we don't have another option here. Out of curiosity, though, does `www.rust-lang.org` work for you? That's distributed through CloudFront and we could enable that for crates.io downloads which would enable a CDN.

**Comment by shingtaklam1324** [comment]
Yes, all other rust webpages and services work flawlessly, it is only the occasional Amazon AWS issue

**Comment by alexcrichton** [comment]
I've [opened a PR](https://github.com/rust-lang/crates.io/pull/1152) to add CDN support to crates.io and created a CloudFront CDN, hopefully we can merge that and start distributing crates.io crates the same way as Rust, and that way I believe it should work for you!

**Comment by alexcrichton** [comment]
Ok I've enabled a CloudFront CDN, mind testing again and seeing if this works?

**Comment by shingtaklam1324** [comment]
It seems to work flawlessly now. Haven't tested extensively but so far, so good

**Comment by alexcrichton** [comment]
Great! In that case I'll close this for now
