### ISSUE TITLE
Improve the error message for when a patched dependency doesn't resolve to anything

### ISSUE THREAD

**Issue by sunjay** [rust-lang/cargo#4678]
**If you were brought here from an error message:** It may be that the version of a dependency in your Cargo.lock file does not match the version of your patched dependency. You can often fix this by running `cargo update -p <your package name>`. We're working on improving this error message to provide better, more detailed suggestions.

If you ran into this error message because of a different reason with a different solution, please let us know in the comments so we can address it. :)

---

This issue is meant to be a more long term fix than the error message updated in https://github.com/rust-lang/cargo/pull/4607.

From @alexcrichton:
> Ideally what we'd do is upon failure do a query again for a more relaxed version constraint, seeing if you just got the wrong version. If that fails we could say that the package doesn't even exist in the source.

### More details from @sunjay in the original PR (#4607)

The specific problem that I ran into occurred when I was trying to upgrade the `rustfmt` submodule in the rust codebase. The `rustfmt-nightly` dependency changed version numbers and this conflicted with what was in the `Cargo.lock` file. After some detective work I was able to find the [documentation on `[patch]`](http://doc.crates.io/manifest.html#the-patch-section) which I had never read before and the following relevant paragraphs from [some other documentation](http://doc.crates.io/specifying-dependencies.html#testing-a-bugfix):

> Next up we need to ensure that our lock file is updated to use this new version of uuid so our project uses the locally checked out copy instead of one from crates.io. The way [patch] works is that it'll load the dependency at ../path/to/uuid and then whenever crates.io is queried for versions of uuid it'll also return the local version.
> 
> This means that the version number of the local checkout is significant and will affect whether the patch is used. Our manifest declared uuid = "1.0" which means we'll only resolve to >= 1.0.0, < 2.0.0, and Cargo's greedy resolution algorithm also means that we'll resolve to the maximum version within that range. Typically this doesn't matter as the version of the git repository will already be greater or match the maximum version published on crates.io, but it's important to keep this in mind!

If it was not for the person who wrote those docs, I would not have known what to do here!

**Comment by pornel** [comment]
I've ran into this for the reason as described (I've patched a package and then checked out an earlier version in the patch target dir), but the `cargo update -p <package>` command does not fix it — it displays exactly the same message again. Only deleting `Cargo.lock` solves the problem for me. rustc 1.24.0-nightly (0077d128d 2017-12-14)

**Comment by Xanewok** [comment]
Encountered this in the exact scenario described by @sunjay, when trying to upgrade `rustfmt` module in rust repo.
What I did was I upgraded RLS submodule first, which caused Cargo to add
```toml
 [[package]]
 name = "rustfmt-nightly"
 version = "0.3.4"
 source = "registry+https://github.com/rust-lang/crates.io-index"
```
in addition to previously patched, local rustfmt `[[package]]` with 0.3.2 version.
Then, when I tried to checkout new 0.3.4 version of rustfmt module, I got this error. `cargo update -p rustfmt-nightly` didn't help.
What I did what was @pornel suggested, but I only deleted the old
```toml
 [[package]]
 name = "rustfmt-nightly"
 version = "0.3.2"
```
entry and this fixed the issue.

**Comment by Eijebong** [comment]
Just had this issue in servo while trying to use a patched version for `hyper_serde`. The problem was that one dependency of the patched one wasn't up to date. 
Running `cargo update -p time` (time was the dependency that wasn't up to date) without the `[patch]` section and then re adding it fixed my problem.
I'd suggest running `cargo update` before adding the `[patch]` section for people with that problem.

**Comment by Eh2406** [comment]
@alexcrichton did you fix this recently?

**Comment by alexcrichton** [comment]
@Eh2406 I don't think I purposely did but if it was fixed as a side product that'd be nice! (and if so we should certainly add a test for this)

**Comment by sunjay** [comment]
This is likely still an issue and it is probably that no one has gotten to it yet.

**Comment by jethrogb** [comment]
If you got here when trying to compile `rustc`, make sure to update your submodules: `git submodule update --init --recursive`

**Comment by dignifiedquire** [comment]
Same issue here, only removing `Cargo.lock` fixes the issue. (rustc 1.38.0 nightly 2019-08-08)

**Comment by Gowee** [comment]
I just came back to a library I have not touched for months and `git pull` the remote. `cargo update -p foo` results in error of `bar` and vice versa.  `cargo update` w/o any additional args works for me and takes less time than deleting `Cargo.lock`.
