### ISSUE TITLE
Redirect doc.crates.io to doc.rust-lang.org/cargo

### ISSUE THREAD

**Issue by behnam** [rust-lang/cargo#4694]
This is the last step of the migration of the Cargo docs.

Background: https://github.com/rust-lang/rust/issues/44910

We need to wait until <https://github.com/rust-lang/rust/pull/45692> makes it to stable,
 so <https://doc.rust-lang.org/cargo/> won't redirect to <http://doc.crates.io/> anymore, and then we can set up the redirect.

## What needs to be done
Use `MIGRATION_MAP` to create redirect from old doc.crates.io URLs to new doc.rust-lang.org/cargo ones, all with permanent status.

**Comment by alexcrichton** [comment]
Done!
