### ISSUE TITLE
consider merging Cargo.toml webpages

### ISSUE THREAD

**Issue by setharnold** [rust-lang/cargo#4704]
Hello, I'd like to suggest merging all the documentation about the Cargo.toml file into one webpage.

Somehow I never find the information I need on the first page I land on when searching and doing multiple "find in page" searches across multiple pages is more work than doing it on a single page.

I propose merging these pages into a single page:

http://doc.crates.io/manifest.html
http://doc.crates.io/pkgid-spec.html
http://doc.crates.io/build-script.html
http://doc.crates.io/config.html
http://doc.crates.io/environment-variables.html
http://doc.crates.io/specifying-dependencies.html

I'm less convinced about merging in 'the guide':

http://doc.crates.io/guide.html

strictly because I can see the value in a short and sweet walkthrough. Two pages would still be easier for me than the current maze of twisty pages all alike.

Thanks

**Comment by retep998** [comment]
I would prefer to have a *single* page that briefly covers all the options available in `Cargo.toml`, with links to pages that go over specific options in more detail.

**Comment by hobofan** [comment]
I very much am in favor of merge the pages! Especially since they feel very similar and some of them cover overlapping topics, it is very hard to remember which page contained the information you were looking for, so I always end up clicking through most of the pages to find what I was looking for.

**Comment by petrochenkov** [comment]
Two weeks later: Cargo docs are published as multi-page mdbook, this issue is closed with "use 'print as pdf'" excuse.

**Comment by alexcrichton** [comment]
The documentation has been reorganized at https://doc.rust-lang.org/cargo/, so closing.

**Comment by retep998** [comment]
The new documentation still has the same issue of not having one page that covers all the options available. In which repo should this issue be moved to, now that the documentation is in a new location?

**Comment by alexcrichton** [comment]
Can you open a new issue for that?

**Comment by alexcrichton** [comment]
(this repo is fine)
