### ISSUE TITLE
Invalid LICENSE-MIT file

### ISSUE THREAD

**Issue by maghoff** [rust-lang/cargo#4707]
The file LICENSE-MIT is at present invalid, because it refers to a contained copyright notice that was removed in this commit: https://github.com/rust-lang/cargo/commit/d82153017d599e89d6d2aeeeb4ca0022ea6f8382

It is a condition of the license that "The above copyright notice (…) shall be included in all copies or substantial portions of the Software.", but there exists no "above copyright notice" to include. As such, it is impossible to be in compliance with this license.

**Comment by maghoff** [comment]
Another take on avoiding misattribution is what maplit does: https://github.com/bluss/maplit/blob/master/LICENSE-MIT

The license file states `Copyright (c) 2015` without attribution.

I have no idea of the legal bearings of any of this, I just want to be in compliance :)

**Comment by alexcrichton** [comment]
cc @joshtriplett

**Comment by joshtriplett** [comment]
@maghoff This really isn't an issue, and no one will interpret it as such. "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." is normally interpreted to mean "reproduce the entire copyright/license block exactly as you receive it". If there isn't a notice, then that's fine; you just have to reproduce the entire license block. Better that than to change the text to not *exactly* match the MIT license. And better that than to have an inaccurate notice; "The Rust Project Developers" is not a legal entity.

Also note that all works are automatically copyrighted without any need for a notice, and a legally valid copyright notice has a very specific form, which does require an author name. Including a half-formed copyright notice does not have any particular meaning.

**Comment by maghoff** [comment]
Thanks for getting back to me @joshtriplett 🙂

Let me start out by saying that whatever you decide is fine by me, I am by no means an authority here. I'll take this opportunity to explain my viewpoint and then you can decide whether or not you consider it to have any merit.

>This really isn't an issue, and no one will interpret it as such.

What do you mean? No _lawyer_ will interpret it as an issue? Or did you mean to call me nobody? 😉 Because here we are.

>"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." is normally interpreted to mean "reproduce the entire copyright/license block exactly as you receive it".

I take issue with this interpretation, especially in a reality where package managers such as Cargo (but also, for example, npm) make it _so easy_ to drag in hundreds of (transitive) dependencies.

I am currently working on getting my relatively modest project [Sausagewiki](https://github.com/maghoff/sausagewiki) into compliance with the licenses of all its direct and indirect dependencies. For my ~32 declared crate dependencies I now count 117 crate dependencies in total.

I find it user hostile, and against the spirit of the respective licenses, to simply concatenate 117 license files (or ~200, considering all the dual licensing?) and call it compliance.

That's my basis for reacting in this case; I want to be able to show the user the relevant copyright notices while also showing only one copy of each relevant license.

---

Another interpretation of cargo's LICENSE-MIT could be that, considering that there is no "above copyright notice", including no copyright notice would trivially be compliance. For now, I am going to go with this interpretation.

---

I still find the LICENSE-MIT file suspect, but you have given this thought, and I do not consider myself an authority on legal matters. As such, I will now close this issue. But thanks for explaining a little bit 🙂

**Comment by joshtriplett** [comment]
@maghoff 
> What do you mean? No lawyer will interpret it as an issue? Or did you mean to call me nobody? 😉 Because here we are.

My apologies, I did not intend to come across that way, and that implication didn't even occur to me. Let me phrase it another way.

Based on the extensive history of license analysis I've seen, in Linux distributions that care scrupulously about licenses and license compliance, in companies that care scrupulously about licenses and license compliance, and in legal review discussions of various types, I've never seen the interpretation suggested that omitting the copyright notice from the MIT license would lead to such a problem. Rather, the prevailing interpretation the few (non-zero) times the subject has ever come up was...

> Another interpretation of cargo's LICENSE-MIT could be that, considering that there is no "above copyright notice", including no copyright notice would trivially be compliance. For now, I am going to go with this interpretation.

...exactly this interpretation.

Also:

> I find it user hostile, and against the spirit of the respective licenses, to simply concatenate 117 license files (or ~200, considering all the dual licensing?) and call it compliance.

I appreciate your diligence in that. I personally think it's acceptable to aggregate all the licenses directly in a file few people will ever actually read, and to *separately* summarize the list of licenses that apply in a very brief fashion that just names the licenses (e.g. "incorporates works variously under MIT, MIT/Apache-2.0 dual-license, 3-clause BSD, LGPLv2.1 or later, and GPLv2 or later; for full details see LICENSES-THIRD-PARTY.txt"), for user convenience in knowing what terms apply.

**Comment by maghoff** [comment]
Thank you @joshtriplett ! I appreciate this detailed follow-up immensely, as I am not surrounded by people knowledgeable in this topic.

**Comment by nfitzen** [comment]
@joshtriplett I know this issue has been closed already for years, but I didn't want to open an exact one again.

> Including a half-formed copyright notice does not have any particular meaning.

At least in the U.S., a singular copyright notice can work for collective works. See, e.g., [17 U.S.C. &sect; 404]. [This article](https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/) might give more information on that matter. It seems like consensus is that "copyright &copy; \<year\> the \<project-name\> developers" is a valid copyright notice.

That said, I'm not a lawyer, and none of this is legal advice.

[17 U.S.C. &sect; 404]: https://www.law.cornell.edu/uscode/text/17/404
