### ISSUE TITLE
'cargo install --path .' recompiles when configuration flags were used to build

### ISSUE THREAD

**Issue by jpacker** [rust-lang/cargo#4708]
Similar to #2143.

I build https://github.com/BurntSushi/ripgrep with the  command

`RUSTFLAGS="-C target-cpu=native" cargo build --release --features 'simd-accel avx-accel'`

then run `cargo install --path `.

Cargo will recompile. 

However, running:

```
cargo build --release
cargo install --path .
```

Will not recompile.

I expect that I should be able to build with custom flags and install the binaries that were built with those flags without rebuilding. (Presumably, the rebuild is building without my flags.)

I am using cargo 0.24.0-nightly (b83550edc 2017-11-04)

**Comment by alexcrichton** [comment]
Yes the differences here are the `RUSTFLAGS` and `--features` flags which means that Cargo will recompile, which is expected behavior. If you set the flags and env vars for the `install` command though you should be good to go!
