### ISSUE TITLE
cargo clean --all

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#4709]
It seems that cargo clean --all is not supported. Does `cargo clean` clean all crates ?

**Comment by Mark-Simulacrum** [comment]
`cargo clean` without arguments (AFAIK) is effectively equivalent to `rm -rf target`, so I guess "yes"; with a workspace the target directory will be top-level so it should work.

**Comment by gnzlbg** [comment]
Indeed.

One dependency was set up via a hit URL and the travis bots were failing so
to an upstream issue.

I did cargo clean 3 times wondering why I did not have the issue locally
till I realized the lock file is not cleaned up by it and I had to do cargo
update afterwards.

Is there a way to tell cargo clean to also remove the lock file if it is
not checked into git?

It's not a big deal but I expect
Cargo clean + cargo build to have the same effect as doing it in a
completely new host and it is currently not the case.
