### ISSUE TITLE
`cargo test` does not run doctests for cdylib

### ISSUE THREAD

**Issue by rfdonnelly** [rust-lang/cargo#4717]
This is effectively a dupe of https://github.com/rust-lang/cargo/issues/2442.  However, #2442 was closed without action.  Having `cargo test` silently not run doctests for cdylib and other non-rlib crate types is a papercut.  It is confusing for new users that do not know the implementation details of doctests.  

A user should be informed of which tests are not being run, why, and how to resolve.  This would cut down on time spent discovering why doctests are not run.  Configuration should allow these messages to be disabled.

## Discovery Process for Current Behavior

To debug why doctests were not being run, I had to search the cargo source for "Doc-tests" which led me to: https://github.com/rust-lang/cargo/blob/8be175e37dbd2bcd84078b1a3512c5ac04ae77cb/src/cargo/core/manifest.rs#L471  This showed me that this behavior was intended and a function of crate-type but did not explain why.  I then searched open issues, then closed issues and eventually found #2442 which gave some explanation.

## Current Behavior

Running `cargo test --doc` on a new rlib successfully runs doctests:
```text
$ cargo test --doc
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Doc-tests lib

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Running `cargo test --doc` on a new cdylib silently fails with:

```text
$ cargo test --doc
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
```

## Expected Behavior

Running `cargo test --doc` on a cdylib should inform the user that doctests were not run:

```text
$ cargo test --doc
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Doc-tests lib

warning: doc-tests can only be run on rlib, lib, and proc-macro crate-types
due to <terse explanation>.  This warning can be disabled by setting
doctest=false in the [lib] section of Cargo.toml.
```

Ideally, the message should inform the user of alternatives.  I don't know what these are yet.  Maybe adding "rlib" to crate-type in addition to what is already there.  Or break up the code base into multiple crates so that doctest can be run on a subset.

## Cargo Version

```
$ cargo --version
cargo 0.22.0 (3423351a5 2017-10-06)
```

**Comment by alexcrichton** [comment]
This is a limitation of rustdoc, not Cargo, so I think you'll want to open an issue against rust-lang/rust
