### ISSUE TITLE
CARGO_PKG_AUTHOR_NAMES: CARGO_PKG_AUTHORS without email-addresses

### ISSUE THREAD

**Issue by prasannavl** [rust-lang/cargo#4718]
`CARGO_PKG_AUTHORS` just sets the exact string in `Cargo.toml`. I tend to use this in apps, which tends to have the email address as well. I'd like to keep the email address in the crate author list as a means of being able to reach the package author - however, I'd not like to use that in application. 

So, generally I have to manually strip everything `<..>` from the result of the `env!` macro that provides this. Would it be acceptable to have a macro that does this built into cargo? I wonder since this not an uncommon case. Granted, people probably would just manually do this. But I think it'd be nice to have it built into cargo, and it also emphasizes on not sharing email address via the app itself unintentionally - as the usage of macro to pull this is fairly common.

**Comment by alexcrichton** [comment]
I don't believe Cargo even parses this information?

**Comment by prasannavl** [comment]
@alexcrichton - Perhaps, there's something I missed? - https://github.com/rust-lang/cargo/blob/a1489e8316139b97e0db5f50570b2452e1d9f659/src/cargo/ops/cargo_rustc/compilation.rs#L159-L169

What I meant to add was something on the lines of this:

```rust

fn gen_author_names() -> Vec<String> {
    use ::regex::Regex;

    let re = Regex::new(r#" *<.*?@.*?\..*?>.*"#).unwrap();
    crate_authors()
        .split(":")
        .map(|x| re.replace(x, "").into_owned())
        .collect::<Vec<String>>()
}

env("CARGO_PKG_AUTHOR_NAMES", gen_author_names().join(":"))
````

**Comment by alexcrichton** [comment]
What I mean though is that Cargo does not actually have this information, it cannot do this operation. It hasn't ever imposed a formatting on the author names so there's no guarantee what format they will be in, so Cargo does not have this information to show.

**Comment by prasannavl** [comment]
If I understand you correctly, you mean to say there's no defined format on `Cargo.toml` for authors? If so, I believe that makes sense. 

Regardless, it's just left to the application to handle this manually.
