### ISSUE TITLE
Support building crate dependencies at different optimization levels

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/cargo#4719]
This is pretty commonly requested functionality, with a variety of use cases:
1. Building all dependent crates with optimization except for one that's being debugged. This is valuable for situations where running builds with everything built at -opt-level=0 is too slow to be usable but you still need good debug info for part of the application.
2. You can't afford to do opt-level=3 builds because of the long build time but certain crates need opt-level=3 for good codegen. This is directly affecting Gecko and WebRender. Gecko builds its rust code with opt-level=2 but we need to build the serialization code at opt-level=3. See 
https://bugzilla.mozilla.org/show_bug.cgi?id=1413285

**Comment by jrmuizel** [comment]
cc @aturon

**Comment by est31** [comment]
This is an existing and old feature request: #1359

The small issue here that ruins all the fun is that a lot of stuff doesn't get built until it is being put into the leaf crate as it includes generics...

Currently the only way to fix this is to avoid generics altogether.

There is hope on the horizon though in the form of ThinLTO that AFAIK features incremental optimisation.

**Comment by luser** [comment]
@Manishearth proposed an RFC: https://github.com/rust-lang/rfcs/pull/2282

**Comment by Eh2406** [comment]
Move to close ass dop of #1359 and rust-lang/rfcs#2282?

**Comment by alexcrichton** [comment]
Sure!
