### ISSUE TITLE
Add support for disabling jobserver

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/cargo#4721]
There is currently a bug in jobserver (https://github.com/alexcrichton/jobserver-rs/issues/4) which breaks certain windows-gnu builds when an incompatible make is on the system. For situations like this it would be great if there was a way to disable the jobserver support, at least until the jobserver crate is more stable.

**Comment by alexcrichton** [comment]
Unfortunately this is how parallelism limiting works and can't be disabled. It's also why we have nightly! Bugs should be fixed now.
