### ISSUE TITLE
How to get a list of all non-yanked available versions of a package?

### ISSUE THREAD

**Issue by Frederick888** [rust-lang/cargo#4723]
I was trying to fix kbknapp/cargo-outdated#101 and found that it might be a bit tricky to get a list of all non-yanked available versions of a package.

Because I would also like to get the pre-releases, wildcard requirement `"*"` does not work for me. Currently I'm using:
```rust
let dependency = Dependency::parse_no_deprecated(name, None, source_id)?;
let query_result = source.query_vec(&dependency)?;
```
...but `Summary` does not have an API like `Summary::is_yanked()` which could allow me to filter out those yanked ones.

Is there a workaround of this issue?

**Comment by lukaslueg** [comment]
Same as #4679 ?!

**Comment by Frederick888** [comment]
@lukaslueg Related but not the same. #4679 kinda suggests completely hiding yanked packages from [`Registry::query_vec()`](https://docs.rs/cargo/0.22.0/cargo/core/registry/trait.Registry.html#method.query_vec) results, on the other hand here I'm actually asking for a way to access more fields in the `crates.io` API results (e.g. [`quickcheck`](https://crates.io/api/v1/crates/quickcheck)). But it seems that (surprisingly) neither `cargo` nor `crates-io` provides such a functionality?

IMO it might be better to have another layer between `query_vec()` and `Summary` so it can serve as the returned results of `query_vec()` and allows developers to access more fields of `crates-io` API results.
