### ISSUE TITLE
Not all .cargo/config settings are settable via environment variables

### ISSUE THREAD

**Issue by dylanede** [rust-lang/cargo#4728]
For example, the directory for a source cannot be set via an environment variable, i.e.

```text
[source.vendored-sources]
directory = "foo"
```

cannot be equivalently done via `CARGO_SOURCE_VENDORED_SOURCES_DIRECTORY=foo`, despite the docs suggesting otherwise.

Also see #3985.

**Comment by ehuss** [comment]
Closing in favor of #5416 which has more details.
