### ISSUE TITLE
The new progress bars do not react well to the changes in tty width

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#4732]
My strongest dislike of the progress bars is how they mishandle the terminal width changes all the time. In case of cargo, there’s no handling at all.

For example see the attached image of what happens when the terminal is wider at first and then its width is decreased:

![Image with a lot of repeating progress bars](https://user-images.githubusercontent.com/679122/32985119-e6c4653c-ccbb-11e7-8d0a-0c80f3197fa1.png)

This is a surprisingly common problem for me, who tends to change tiling mode, and thus terminal widths, fairly often.

**Comment by nagisa** [comment]
For the reference, the `indicatif` crate handles this case fairly tolerably. While there still are some repeated "bars", the crate recovers gracefully as the terminal size changes.

**Comment by lukaslueg** [comment]
FWIW I think a dependency for fancy bars is inferior to slightly broken bars on terminal resize.
