### ISSUE TITLE
Cargo logo in svg

### ISSUE THREAD

**Issue by robertohuertasm** [rust-lang/cargo#4733]
Hi, I'm one of the core maintainers of [vscode-icons](https://github.com/vscode-icons/vscode-icons/) and I'm willing to [add support for Cargo #1367](https://github.com/vscode-icons/vscode-icons/issues/1367). 

The thing is that it would be awesome if you could provide a `svg` version of your logo for us to use it as an icon for `Cargo.lock` file.

**Comment by alexcrichton** [comment]
Unfortunately I'm not sure we have one right now -- https://users.rust-lang.org/t/hi-res-cargo-icon/10733/5

**Comment by robertohuertasm** [comment]
@alexcrichton, do you have access to the source file (.ai, .psd or whatever)?

**Comment by alexcrichton** [comment]
Unfortunately I don't personally have access (unsure if anyone does)

**Comment by steveklabnik** [comment]
@wycats or @wifelette maybe?

**Comment by wifelette** [comment]
Ask and you shall receive 😄 

[Cargo.zip](https://github.com/rust-lang/cargo/files/1489485/Cargo.zip)

**Comment by robertohuertasm** [comment]
Thanks @wifelette. I've tried to export this as svg but the result is not near acceptable. I'll try it again when I have more time. By the way, if you happen to excel at psd to svg your help will be really appreciated 😉 

Thanks to everyone!

**Comment by JimiC** [comment]
@wifelette @robertohuertasm I can give it a try since I've become pretty good at converting `PNG` to `SVG`. I can even try to make an `SVG` version myself. It will take some time but I think we can do it.

**Comment by robertohuertasm** [comment]
@JimiC, there's no need. I've already got a pretty decent version.

**Comment by robertohuertasm** [comment]
Thanks again for your support. Hopefully we'll be having `Cargo` icons for `vscode` in our next week release.

**Comment by egomezsalasva** [comment]
![cargo-logo](https://github.com/rust-lang/cargo/assets/47556145/27298f5c-43a4-4068-9154-5d07f9e37c11)

Heres a higher fidelity SVG. Still needs some improvements:

Texturise the bottom wood.
Better morphing of the rust logo.
