### ISSUE TITLE
rustdoc should also be passed RUSTFLAGS

### ISSUE THREAD

**Issue by nox** [rust-lang/cargo#4737]
I know about `RUSTDOCFLAGS`, but I would like to understand the rationale against passing `RUSTFLAGS` to `rustdoc` when running `cargo test`.

My use case is the following: I'm using unstable Rust code in a 1.0 crate, and I want to cfg-gate it like Rayon does with `RUSTFLAGS="--cfg rayon_unstable"`. It works great, but my issue is that some code that is now using unstable Rust is tested through doc tests and given `rustdoc` isn't passed `RUSTFLAGS`, putting `# #![cfg_attr(foo_unstable, feature(some_unstable_feature))]` in the doc test does nothing and it fails.

**Comment by alexcrichton** [comment]
This unfortunately cannot be done because rustdoc does not support all of rustc's flags, and I think supporting that would be an upstream rust-lang/rust issue.

**Comment by nox** [comment]
See https://github.com/rust-lang/rust/issues/46189.

**Comment by Kixunil** [comment]
Could there be a warning when `RUSTFLAGS` is set for `doc`? I just spent a lot of time trying to figure out why it doesn't work for me. Would be nice to at least save others.
