### ISSUE TITLE
Cargo does not understand the absolute manifest path

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/cargo#4744]
Cargo building project failed, if --manifest-path is absolute path:

$ cargo build --manifest-path /tmp/Cargo.toml
error: manifest path /tmp/Cargo.tomldoes not exist

While if path is relative, this error does not occur.
My system is i686-pc-windows-gnu.

**Comment by aristarh2704** [comment]
I think reason in std::util::paths::normalize_path

**Comment by retep998** [comment]
`i686-pc-windows-gnu`. Does this mean you are compiling on Windows? If so, `/tmp/Cargo.toml` is not being interpreted the way you think. Cargo and Rust on Windows only understand Windows paths, they do not understand msys/cygwin paths.

**Comment by aristarh2704** [comment]
Thank you.))
