### ISSUE TITLE
Cargo may hit 260 characters path limit on windows when installing dependencies

### ISSUE THREAD

**Issue by ivstas** [rust-lang/cargo#4745]
I encountered this issue when trying to build project that have a transitive dependency on git repository with deep nesting:
`C:/Users/ivstas/.cargo/git/checkouts/servo-css-parser-6b649679bab5995b/0d528c7/servo/tests/wpt/mozilla/meta/mozilla/referrer-policy/origin-when-cross-origin/attr-referrer/same-origin/http-https/iframe-tag/same-origin-downgrade.keep-origin-redirect.http.html.ini`: The filename or extension is too long.

Windows 10 has a feature that enlage this limit, but turning on this feature didn't help either.

My assumption (that could be wrong) is that win 10 has some kind of new api that allows working with paths above 260-character limit.

**Comment by PENGUINLIONG** [comment]
The limit is removed since Windows 10 1607 but:

> However, you must opt-in to the new behavior.

You have to set an value in register or group policies. Go and [check it out](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath).

**Comment by ivstas** [comment]
@PENGUINLIONG 
> turning on this feature didn't help either

I've turned new behaviour on in the registry. Didn't help.

**Comment by alexcrichton** [comment]
@ivstas can you provide the full error message for when this happens?

**Comment by ivstas** [comment]
@alexcrichton i'm trying to use `rsx` lib that has all dependencies in git. This is what I get:
```
C:\Users\ivstas\code\rsx-usage>cargo test --verbose
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/victorporof/rsx.git`
    Updating git repository `https://github.com/victorporof/rsx-primitives.git`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/victorporof/rsx-layout.git`
    Updating git repository `https://github.com/victorporof/webrender.git`
    Updating git repository `https://github.com/victorporof/rsx-dom.git`
    Updating git repository `https://github.com/victorporof/rsx-stylesheet.git`
    Updating git repository `https://github.com/victorporof/rsx-parser.git`
    Updating git repository `https://github.com/victorporof/yoga-rs.git`
    Updating git repository `https://github.com/victorporof/rust-self-tokenize.git`
    Updating git repository `https://github.com/victorporof/servo-css-parser.git`
error: failed to load source for a dependency on `servo-css-parser`

Caused by:
  Unable to update https://github.com/victorporof/servo-css-parser.git

Caused by:
  failed to update submodule `servo`

Caused by:
  [2/-4] failed to stat 'C:/Users/ivstas/.cargo/git/checkouts/servo-css-parser-6b649679bab5995b/0d528c7/servo/tests/wpt/mozilla/meta/mozilla/referrer-policy/origin-when-cross-origin/attr-referrer/same-origin/http-https/iframe-tag/same-origin-downgrade.keep-origin-redirect.http.html.ini': The filename or extension is too long.
```

**Comment by alexcrichton** [comment]
Ok thanks for the info! That also means the error message is coming from libgit2, so there may not be a whole lot we can do here...

**Comment by ivstas** [comment]
Checked out libgit2 repo, there is even an corresponding issue that nobody touched since 2013:
https://github.com/libgit2/libgit2/issues/1899

**Comment by dwijnand** [comment]
The new libgit2 issue is https://github.com/libgit2/libgit2/issues/3053, so I'd say closing this in favour of that upstream issue.
