### ISSUE TITLE
`cargo package` cannot call `cargo metadata`

### ISSUE THREAD

**Issue by rillian** [rust-lang/cargo#4746]
I hit this issue trying to [publish a crate](https://github.com/mozilla/mp4parse-rust/issues/129) from inside a workspace.

The [mp4parse](https://github.com/mozilla/mp4parse-rust/) repo has a virtual manifest referring to two subcrates, one of which depends on the other. The depending crate, `mp4parse_capi`, calls [`cbindgen`](https://github.com/eqrion/cbindgen) from a build script to generate headers. This in turn [calls](https://github.com/eqrion/cbindgen/blob/58d3178dc538af317cdfffe7de79e1420e1db293/src/bindgen/cargo/cargo_metadata.rs#L105) `cargo metadata` on the crate to obtain the dependency graph. So far so good.

But when running `cargo package` this fails, because the test build of the package invokes `cargo metadata` on the version in `target/package/` which isn't listed in the `workspace.members` key of the top-level manifest.

```
$ cd mp4parse_capi
$ cargo package
[...]
error: failed to verify package tarball

Caused by:
  failed to run custom build command for `mp4parse_capi v0.9.0 (file:///home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0)`
process didn't exit successfully: `/home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0/target/debug/build/mp4parse_capi-2a4c3b58d340bafe/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/lib.rs

--- stderr
thread 'main' panicked at 'Could not generate header: "couldn\'t execute `cargo metadata` with manifest \"/home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0/Cargo.toml\"."', /checkout/src/libcore/result.rs:906:4
```

**Comment by rillian** [comment]
I guess the `cargo package` implementation needs to block the search for a parent base crate at the top of the package directory? The idea, I think, is to verify that the packaged crate will build, so it seems like the workspace influence is an inappropriate side-effect here.

I tried adding `target/package/mp4parse_capi-*` to the members list as suggested by cargo's error message, but then of course:
```
error: two packages named `mp4parse_capi` in this workspace:
- /home/giles/mp4parse-rust/mp4parse_capi/Cargo.toml
- /home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0/Cargo.toml
```

**Comment by alexcrichton** [comment]
What was the error of cargo-metadata? I don't see the error from cargo-metdata in the output above?

**Comment by rillian** [comment]
Ah, sorry. The cbindgen eats the cargo error message. Running the same command manually:
```
$ cargo metadata --all-features --format-version 1 --manifest-path /home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0/Cargo.toml
error: current package believes it's in a workspace when it's not:
current:   /home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0/Cargo.toml
workspace: /home/giles/mp4parse-rust/Cargo.toml

this may be fixable by adding `mp4parse_capi/target/package/mp4parse_capi-0.9.0` to the `workspace.members` array of the manifest located at: /home/giles/mp4parse-rust/Cargo.toml
```

**Comment by rillian** [comment]
Steps to reproduce:
```sh
mkdir virtual-manifest
cd virtual-manifest
echo -e '[workspace]\nmembers = [ "foo" ]' > Cargo.toml
cargo new foo
cd foo
cargo package --allow-dirty
cargo metadata --manifest-path target/package/foo-0.1.0/Cargo.toml
```
It's tricky, because this might be a reasonable result, except for the semantics of the target/package directory. It was only a problem for me in the context of running `cargo package` itself. I don't know which of those would be a better gate.

**Comment by rillian** [comment]
Steps to reproduce:
```sh
mkdir virtual-manifest
cd virtual-manifest
echo -e '[workspace]\nmembers = [ "foo" ]' > Cargo.toml
cargo new foo
cd foo
cargo package --allow-dirty
cargo metadata --manifest-path target/package/foo-0.1.0/Cargo.toml
```
It's tricky, because this might be a reasonable result, except for the semantics of the target/package directory. It was only a problem for me in the context of running `cargo package` itself. I don't know which of those would be a better gate.

**Comment by alexcrichton** [comment]
Nah this seems like a clear bug that we should fix, I'm sure there's some trickery we could apply to get this all hooked up and working in Cargo (`cargo package` should probably allow commands like this to work by default somehow at least)
