### ISSUE TITLE
Regression in filename handling on wasm with tests

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#4750]
I believe that now when you execute `cargo test` with the `wasm32-unknown-emscripten` target Cargo will print out:

```
 Running target/wasm32-unknown-emscripten/debug/deps/linux_fcntl_039d1c4280a61bbd.wasm
```

Notably the underscore between the test name and the hash should be a dash, I thinks may be caused by this 

https://github.com/rust-lang/cargo/blob/6a1aee06680d8f074a25431c938c42d7e8d0ab4e/src/cargo/ops/cargo_rustc/context.rs#L723

cc @tatsuya6502, mind taking a look at this? I believe this was caused by https://github.com/rust-lang/cargo/pull/4570

**Comment by alexcrichton** [comment]
Er actually it looks like the regression is that it's trying to run the wasm file at all, previously I think it just ran js!

**Comment by tatsuya6502** [comment]
> mind taking a look at this? I believe this was caused by #4570

@alexcrichton Sorry for the problem and not coming back to you sooner. Hmm, so probably I should change cargo to place the wasm file under /target/{debug,release} only for bin target, not for test?

**Comment by alexcrichton** [comment]
@tatsuya6502 oh no worries! I think in this case we just shouldn't, for the emscripten targets, try to run the wasm files as tests. The curent behavior of renaming them I think is ok (sorry for the misleading OP), it's just that we run both the js and the wasm files when I think we should just run the js
