### ISSUE TITLE
Cargo build --all tries to build examples of dependencies

### ISSUE THREAD

**Issue by pornel** [rust-lang/cargo#4751]
The meaning of `--all` is wider than I expected. I run `cargo build --all` in root of a workspace to build all crates in my workspace. I did not expect this to cause examples in 3rd party dependencies to be built as well (building examples of crates in the workspace is OK).

To reproduce, make a new crate with:

```toml
[dependencies]
rgb = "=0.8.2"
```

and run `cargo build --all`. It fails, because I've published this crate with `[[example]]` in Cargo.toml, but without a necessary file in `include = […]`. I did not expect examples to be relevant to packages on crates.io.

**Comment by alexcrichton** [comment]
I think this is a bug, things like examples should only be built for member of the workspace.

**Comment by lukaslueg** [comment]
@pornel could you give some more information about your setup? I could not reproduce with a member of the workspace depending on `rgb = "0.8.2"` and building the ws with `--all`.

**Comment by pornel** [comment]
Note the syntactic detail, `rgb = "0.8.2"` loads this *or later* version (and I've fixed it in the next version). Needs two `=`: `rgb = "=0.8.2"` to load the old broken version specifically.

**Comment by lukaslueg** [comment]
That's what I did: A member of a workspace depends on `rgb = "=0.8.2"`, I build the ws with `--all`, no examples get built. I've also added an out-of-tree dependency that has broken examples, they don't get built by cargo `0.23.0` as well.

**Comment by pornel** [comment]
I can't reproduce it any more either, so problem solved!
