### ISSUE TITLE
Docs on the target folder structure

### ISSUE THREAD

**Issue by pepsighan** [rust-lang/cargo#4756]
I searched through the cargo docs and google but could not find what each of the files and folders within `target/[mode]` represents. Any direction to the said docs would be great.

**Comment by dwijnand** [comment]
I agree this would be useful.  Even just an initially small amount of information might go a long way.  Perhaps some of it is reserved implementation detail, but I would guess some of it is stable by now.  This is useful, for instance for better caching as well as to tweak the behaviour of the `clean` command, for which there are a few tickets.

Could anyone provide some info?  Even just as a comment here and I'll go through the motions of landing it into on a doc page.
