### ISSUE TITLE
Please continue to publish signed git tags

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#4757]
It seems that there is no [release tag](https://github.com/rust-lang/cargo/releases) for cargo version 0.23. Could one please be provided? It makes life easier for packagers.

At the moment in Debian we're still packaging cargo separately from rustc, so that it can have its own version number separate from rust's version number. Since these version numbers are how dependencies between rust crates are resolved, I've been hesitant to merge the cargo package into the rustc package, since we'd lose the version numbers.

If there are long-term plans to merge cargo into the rustc package completely, it would be good if these extraneous version numbers were dropped, and just have everything use rustc's version number. This greatly simplifies things and matches reality more closely anyways - if rustc "stable" version 1.xx is bundled with "unstable" cargo version 0.yy then cargo 0.yy is effectively a "stable" API anyways, from the point-of-view of people using rust 1.xx.

edit: <del>depends on</del><ins>is bundled with</ins>

**Comment by alexcrichton** [comment]
Oh no worries, I was just super sick at the time of the release and haven't gotten around to this. I'll do this soon with https://github.com/rust-lang/cargo/issues/4754.

**Comment by alexcrichton** [comment]
Tag pushed now!
