### ISSUE TITLE
Fix `frozen_flag_preserves_old_lockfile` test

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#4758]
This test is broken when executing in the Rust CI (after updating RLS and Rustfmt, which really should affect nothing) - https://github.com/rust-lang/rust/pull/46144#issuecomment-347122336 and also on the Cargo CI with [this PR](https://github.com/rust-lang/cargo/pull/4743#issuecomment-347639305)

**Comment by alexcrichton** [comment]
Thankfully taken care of in https://github.com/rust-lang/cargo/pull/4762!
