### ISSUE TITLE
redefinition of table error: print both locations

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#4760]
currently cargo just prints
````
error: failed to parse manifest at `/home/matthias/vcs/github/cargo/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  redefinition of table `profile.release` for key `profile.release` at line 79
````
However this is not very helpful when I just added the duplicate entry at line 79 because I still have to find the original one.

Something like
````
  redefinition of table `profile.release` at line 20 for key `profile.release` at line 79
````
would be more useful :)

**Comment by lukaslueg** [comment]
This error comes straight from the `toml` crate, maybe you want to open an issue [there](https://github.com/alexcrichton/toml-rs)

**Comment by matthiaskrgr** [comment]
stupid bot...

**Comment by dwijnand** [comment]
Is there an issue tracking this in the toml crate?
