### ISSUE TITLE
probe_target_info_kind can't use RUSTFLAGS that contain --print

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#4761]
https://users.rust-lang.org/t/print-native-static-libs/14102

```sh
RUSTFLAGS=--print=native-static-libs  cargo build
```

causes rustc to print extra text, which breaks parsing of its output.

I think filtering out `--print*` args in  `fn env_args()` would fix this.

**Comment by dwijnand** [comment]
I think this is fixed with https://github.com/rust-lang/rust/pull/46705.
