### ISSUE TITLE
When looking for worksapce root, don't step over CARGO_HOME

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4765]
See the description of the problem in https://github.com/rust-lang/cargo/pull/4764#issue-277901728.

The gist is that if you invoke cargo inside CARGO_HOME, which is inside a workspace, Cargo should **not** think that it is inside workspace.

This is the function where I think the fix should be applied: https://github.com/rust-lang/cargo/blob/806e487c0e3b6af6203ef8bebf5d6f49faf8909d/src/cargo/core/workspace.rs#L311

Relevant tests are here: https://github.com/rust-lang/cargo/blob/806e487c0e3b6af6203ef8bebf5d6f49faf8909d/tests/workspaces.rs

**Comment by nox** [comment]
AFAIK, the value that holds `CARGO_HOME` reachable from that code is `self.config.home()`, but that returns a `Filesystem` and there is no way to inspect the inner `PathBuf` from that. Should I implement `PartialEq<&Path>` for `Filesystem`?

**Comment by alexcrichton** [comment]
Yes it should be fine to implement `PartialEq` for that type, the `Filesystem` newtype is basically just preventing access when unlocked to help prevent synchronization bugs.

**Comment by nox** [comment]
@alexcrichton Will do that then.

As for the test, I guess we should make Cargo itself put a dependency in a custom `CARGO_PATH`, and for that to happen it needs to be a `git` dependency with a repository specified as a path. The dependency should then have a build script that invokes `$CARGO metadata` with `CARGO_MANIFEST_PATH`. I've looked at the existing tests and that should be pretty straightforward to do.

**Comment by alexcrichton** [comment]
Each test already has its own `CARGO_HOME` I believe, so it'd be fine to just throw a crate in there and build it. I believe you can use the `Package` helper used throughout to do this.
