### ISSUE TITLE
Complex-ish path dependency graph fails

### ISSUE THREAD

**Issue by remexre** [rust-lang/cargo#4769]
I have a dependency graph like:

```
a -> b;
a -> c;
a -> d;
b -> c;
b -> d;
c -> d;
```

When trying to build `c`:

```
error: failed to select a version for `d` (required by `c`):
all possible versions conflict with previously selected versions of `d`
  version 0.2.0 in use by ??
  possible versions to select: 0.2.0
```

**Comment by withoutboats** [comment]
Can you upload a set of crates that can be used to reproduce the error (e.g. as a git repo)?

**Comment by remexre** [comment]
Try https://github.com/melt-umn/monto-rs/tree/split (note the split branch).

**Comment by alexcrichton** [comment]
@remexre I checked out melt-umn/monto-rs@19fb1235e3959954fe68fe612491ab8d65762ac and ran `cargo build` and it resolved? Is there another way we should reproduce?

**Comment by remexre** [comment]
I tried building this on my desktop, and it worked... This prompted me to check my `~/.cargo/config`, which had `paths` entries pointing to all the crates already. So I guess problem solved?

The error message is definitely suboptimal though, and this being a failure case is somewhat confusing. Should this be closed, or should it stay open as a "document that/why this is illegal" issue?

**Comment by alexcrichton** [comment]
Ah yeah that'd do it! Using `paths` can cause some weird behavior sometimes.

Definitely sounds like we should have a better error message!

**Comment by alexcrichton** [comment]
I think the error messages here were fixed in https://github.com/rust-lang/cargo/pull/5025, so closing.
