### ISSUE TITLE
error: failed to resolve patches

### ISSUE THREAD

**Issue by llvim** [rust-lang/cargo#4773]
```
git clone https://github.com/aochagavia/rocket_wasm.git && cd rocket_wasm
cargo build --release --target wasm32-unknown-unknown --verbose

    Updating git repository `https://github.com/aochagavia/rand.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `rand`

Caused by:
  Unable to update https://github.com/aochagavia/rand.git?branch=wasm#db1e4c31

Caused by:
  [4/-3] revspec 'db1e4c3103d509becd28240fdfc1970519673d81' not found
```
# system info

macos 10.13.1

```bash
rustup show
Default host: x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.24.0-nightly (1956d5535 2017-12-03)
```

**Comment by alexcrichton** [comment]
Thaanks for the report! It looks like the bug here is that the `rand` branch lost a commit? Was it perhaps force-pushed upstream? (I'm not sure this is a bug in cargo?)

**Comment by Timmmm** [comment]
I have this issue too and it was because of a force push. Shouldn't cargo still work in that case though? Presumably `cargo clean` will fix this but it's difficult to do that with the CI system I am using, and also it seems weird that you can change the state of your code such that `cargo build` doesn't work but `cargo clean && cargo build` does. :-/

**Comment by Timmmm** [comment]
After further investigation it seems like Cargo saves the commit hash of your branch in `cargo.lock`, so `cargo clean` has no effect. However if I update the hash I then get this error:

```
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  patch for `serde` in `https://github.com/rust-lang/crates.io-index` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
```

The solutions on that issue seem to be "Delete `cargo.lock`" which isn't great. Oh well.
