### ISSUE TITLE
Cannot be disabled SSL certificate revocation check

### ISSUE THREAD

**Issue by hrektts** [rust-lang/cargo#4779]
A cargo option mentioned in [the comment](https://github.com/rust-lang/cargo/issues/2464#issuecomment-279580096) does not work on the cargo nightly as follows:

```
PS > Set-Item env:CARGO_HTTP_CHECK_REVOKE -Value false
PS > cargo install rustfmt-nightly
    Updating registry `https://github.com/rust-lang/crates.io-index`
Downloading rustfmt-nightly v0.2.17
error: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - �����T�[�o�[���I�t���C���̂��߁A�����̊֐��͎������m�F�ł��܂���ł����B)
```

However, this option works correctly on the stable version of cargo.

The option, that is prepared to be work at [here](https://github.com/rust-lang/cargo/blob/7f0583bd400dcb6ad59ca4b172c2fd41a9c1e5d9/src/cargo/ops/registry.rs#L286-L288), seems to be reset by [this code](https://github.com/rust-lang/cargo/blob/7f0583bd400dcb6ad59ca4b172c2fd41a9c1e5d9/src/cargo/util/config.rs#L636).

The both environments are as follows:

**nightly**
```
PS > rustc -Vv
rustc 1.24.0-nightly (8503b3ff8 2017-12-04)
binary: rustc
commit-hash: 8503b3ff822c1ed01c89773d30e4e10b886d77a5
commit-date: 2017-12-04
host: x86_64-pc-windows-msvc
release: 1.24.0-nightly
LLVM version: 4.0

PS > cargo -Vv
cargo 0.24.0-nightly (5bb478a51 2017-11-29)
release: 0.24.0
commit-hash: 5bb478a518bcf75537409e8b71f6b7cc4af362df
commit-date: 2017-11-29
```
**stable**
```
PS > rustc -Vv
rustc 1.22.1 (05e2e1c41 2017-11-22)
binary: rustc
commit-hash: 05e2e1c41414e8fc73d0f267ea8dab1a3eeeaa99
commit-date: 2017-11-22
host: x86_64-pc-windows-msvc
release: 1.22.1
LLVM version: 4.0

PS > cargo -Vv
cargo 0.23.0 (61fa02415 2017-11-22)
release: 0.23.0
commit-hash: 61fa02415ee1bc17a0c364c1c67107953d04ea87
commit-date: 2017-11-22
```

**Comment by alexcrichton** [comment]
Thanks for the report, definitely seems like a bug! T oconfirm though, this is only on nightly? Or also on stable/beta?

**Comment by hrektts** [comment]
Thanks for your reply. It occurred only on the nightly, though I did not tested it on the beta.

**Comment by alexcrichton** [comment]
Ok no worries! Looks like this logic is indeed on beta, so we'll need to backport the fix.
