### ISSUE TITLE
Compiling without updating registry

### ISSUE THREAD

**Issue by Paxa** [rust-lang/cargo#4783]
Updating registry takes some time when run first time, so building with docker or in CI makes it harder

Is it possible to download compile dependencies and compile project by using only `Cargo.lock`, without downloading github.com/rust-lang/crates.io-index?

I think Cargo.lock has all necessary information

**Comment by alexcrichton** [comment]
Thanks for the report! You can pre-vendor dependencies with `cargo vendor` and [source replacement](http://doc.crates.io/source-replacement.html) which I think should do the trick!

**Comment by Paxa** [comment]
As I understand it just copy all dependencies to local folder, could help with building with docker locally, but to make it work in CI, should I put all dependencies in git?

Or is there a way to reconstruct vendor folder from `Cargo.lock` file?

**Comment by alexcrichton** [comment]
Oh sure yeah what you can do is run `cargo vendor` just before you run Docker so effectively what happens is that when CI starts you'll assemble all dependencies into a format and them ship them over to Docker which then internally uses them.
