### ISSUE TITLE
`cargo test` does not export CARGO_CFG_TEST for build.rs scripts

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#4789]
e here is fairly simple – I need to build a shared library to be used for tests, however it is also important to me that this library is not built when people are compiling the library for regular use.

`rustc --test --print=cfg` does output the `test` configuration variable, however when `cargo test` is run, the build script does not receive this variable in form of `CARGO_CFG_TEST`.

Caveat is that rerunning the build script for both test and non-test would potentially re-run expensive build.rs operations by default, however that seems easily remedied by requiring people to print out a `cargo:rerun-if-env-changed=CARGO_CFG_TEST` (it would become the first exception to the list of environment variables set by cargo and tracked by default).

**Comment by alexcrichton** [comment]
This is currently intentional behavior because build scripts don't have a "I'm running tests" mode. That would require a test build script most likely and it's an unimplemented feature so far.

**Comment by nvzqz** [comment]
@alexcrichton why would a separate test build script be needed and not just allow for `#[cfg(test)]` to work?

**Comment by Supreeeme** [comment]
I'm not sure how this has changed over the last few years, but I don't see why build scripts would need a specific "tests mode". My use case is I have a C++ dependency that I build and link in my application, but I fake it for unit tests so there's no point in building and linking it. 

A workaround for this for anyone interested is using the self depends trick to enable a feature in dev-dependencies:
```toml
[package]
name = "my-crate"

[features]
unittest = []

[dev-dependencies]
my-crate = { path = ".", features = ["unittest"] }
```
You can now use `#[cfg(feature = "unittest")]` in the build script where you would use `#[cfg(test)]`.

**Comment by michaelmior** [comment]
What if my crate is doing code generation and I want to test the behavior of the generated code? It seems a reasonably logical way to do this is to generate and compile the code in the build script, but this is only needed for tests.
