### ISSUE TITLE
RUSTDOCFLAGS passed twice in 'cargo test'

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#4790]
```sh
cargo new foo
cd foo
RUSTDOCFLAGS="--document-private-items" cargo +nightly test -v
```
```rust
       Fresh foo v0.1.0 (file:///tmp/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/tmp/foo/target/debug/deps/foo-347a4c2a546f5546`

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests foo
     Running `rustdoc --test /tmp/foo/src/lib.rs --crate-name foo -L dependency=/tmp/foo/target/debug/deps -L dependency=/tmp/foo/target/debug/deps --extern foo=/tmp/foo/target/debug/deps/libfoo-01aa8301b833d22c.rlib --document-private-items --document-private-items`
rustdoc: Option 'document-private-items' given more than once
Try 'rustdoc --help' for more information.
error: test failed, to rerun pass '--doc'
```

Regression range https://github.com/rust-lang/cargo/compare/5bb478a5...930f9d94 includes https://github.com/rust-lang/cargo/pull/4740, CC @nox

**Comment by SimonSapin** [comment]
(I’ve worked around this in Servo by making `./mach test-unit` not set `RUSTDOCFLAGS="--document-private-items"` when running `cargo test`.)

**Comment by nox** [comment]
I can reproduce the error. I also checked that without #4740, the flag is not passed 
at all*.

**Comment by nox** [comment]
This happens because the `foo` unit is encountered twice when running the code that I changed:

https://github.com/rust-lang/cargo/blob/3992e5259ba99385016e27a7971121e916d01d5a/src/cargo/ops/cargo_rustc/mod.rs#L228-L237

This also means that every `--cfg` feature flag is passed twice too.
