### ISSUE TITLE
sccache integration not resulting in any cache hits

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/cargo#4793]
Running the latest rust/cargo and sccache, with `RUSTC_WRAPPER`  set correctly, sccache is invoked but does not seem to ever cache anything. 

Originally being tracked here: https://github.com/rust-lang/cargo/issues/4307#issuecomment-323127428

[sccache.txt](https://github.com/rust-lang/cargo/files/1541059/sccache.txt)

**Comment by mqudsi** [comment]
cc @luser and thank you

**Comment by luser** [comment]
That log says it's running sccache 0.2.1, which is missing this fix: https://github.com/mozilla/sccache/commit/2d9bdc1e8fb1fa5a531da2930670bbfcb66f78a0 , which definitely was an issue on some platforms.

Is this just the build log from setting `RUST_LOG=sccache=trace`? To get the log output from the server you also need to set `SCCACHE_ERROR_LOG=/path/to/log`.

**Comment by Eh2406** [comment]
Is this fixed? Can this be closed?

**Comment by alexcrichton** [comment]
Sounds good to me!
