### ISSUE TITLE
Docs regarding "nightly binaries" should be removed; links are to a year-old version

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#4794]
Originally filed by @bluehood [in crates.io](https://github.com/rust-lang/crates.io/issues/1202), but the docs are over here (in two places because we're in the middle of transitioning cargo's docs to mdbook):

- https://github.com/rust-lang/cargo/blob/61ca3022bca2c9e627d2ee523d7bd736e2bcaa2a/src/doc/book/src/getting-started/installation.md
- https://github.com/rust-lang/cargo/blob/34c0674a251287c94cdd1a112966bcb9010c62e8/src/doc/index.md

> As discussed in [this PR](https://github.com/rust-lang/cargo/issues/4785) in the cargo repository, the linux 64-bit binaries available at http://doc.crates.io/#install-nightly-cargo are broken in Debian 9 and Ubuntu 16.04 due to certificate issues -- almost surely caused by the "nightly binaries" actually providing the old rust cargo 0.16.0-nightly

**Comment by ehuss** [comment]
I believe this was fixed in #5040, but is still only in the nightly documentation (https://doc.rust-lang.org/nightly/cargo/getting-started/installation.html).

**Comment by matklad** [comment]
Closing than! Thanks @Eh2406 and @ehuss for following this up!
