### ISSUE TITLE
Track checksum in Cargo.lock

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/cargo#4800]
Packages in the registry should never be changed in place. We currently track the content of each package using a checksum in the registry index; I think we should start recording that checksum in the Cargo.lock, to increase the likelihood that we detect if the index were to be maliciously updated like this.

For example, one common way of building programs is to push the entire package source to a build machine, without vendoring crates. This build machine may have a cache of crates and cargo set up, or it may be instantiated from nothing for each build. In the latter case, a targeted MITM attack could replace the registry index with one containing malicious crates when the build machine connects to github to download the index, and this would not visibly changing the output of the build.

If package pushed to the build machine has a lock file (as is the default for applications), a MITM attack like this would be detected, because the checksums in the index would not match the checksums in the lockfile.

Similarly, malicious edits to the actual index would be more likely to be discovered because they would be likely to lead to build failures for anyone who has that crate in their lockfile.

This is a relatively small change, and I'd be glad to make the PR if we think its a good idea. cc @rust-lang/cargo

**Comment by withoutboats** [comment]
It turns out we already do track checksums for each package in the lockfile, they just aren't where I expected them to be (there's a table at the end, rather than inline with each package). Closing as we already have this feature.

**Comment by alexcrichton** [comment]
We've [even got a test](https://github.com/rust-lang/cargo/blob/e3b0cf63a357d099a42a2aba91f38745ce6c0acd/tests/local-registry.rs#L305-L355) for what happens when it changes!

**Comment by matklad** [comment]
>Packages in the registry should never be changed in place. 

That's true! Sometimes, they can be changed by accident:

1) LARLPOP `build.rs` by default overwrites files in the `src` directory 
2) If you run `cargo metadata` inside the registry, you might create a lockfile. 
3) You might be inclined to just edit the files by hand

It would be great to prevent such accidents with a better error message. One useful thing I've observed recently is making certain parts of file-system readonly (nix does this for `/nix/store` and bazel does this for the build dir with dependencies). Could Cargo mark registry and vendored sources as readonly as well?
