### ISSUE TITLE
Ability to run tests on all my dependencies

### ISSUE THREAD

**Issue by vorner** [rust-lang/cargo#4802]
Would it be possible to extend `cargo test` to have something like `--with-deps` to run tests on all the dependencies? It could be handy when trying to debug an issue that happens only on some systems, to try narrowing it down to single failing crate (well, with some luck if a test fails somewhere). I assume the author did run tests before publishing his/her crate, but probably not on all targets or with the current version of dependencies… having the tests run in my exact situation would help.

Or would this be more suited to some external command?

Either way, I might give it a try, but I'd probably need some hints how to start or what code to read through.

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately this cannot be done in general because not all crates uploaded to crates.io have all the necessary files for testing. Otherwise `cargo test --all` should test everything int he current workspace.
