### ISSUE TITLE
Infinite cycle in depgraph resolution

### ISSUE THREAD

**Issue by vorner** [rust-lang/cargo#4810]
Hello

When I check out and try to build this [repository](https://github.com/vorner/slog-retry), cargo gets stuck in this:

```
$ cargo check --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Resolving dependency graph...
```

I tried to look at what it was doing and setting `RUST_LOG=debug`, it seems it is in an infinite cycle, because these same messages keep repeating forever.

```
DEBUG:cargo::core::registry: load/precise  registry `https://github.com/rust-lang/crates.io-index`
DEBUG:cargo::core::registry: load/precise  registry `https://github.com/rust-lang/crates.io-index`
DEBUG:cargo::core::registry: load/precise  registry `https://github.com/rust-lang/crates.io-index`
DEBUG:cargo::core::resolver: checking if unicode-xid v0.0.4 is already activated
DEBUG:cargo::core::resolver: checking if synom v0.11.3 is already activated
DEBUG:cargo::core::resolver: checking if quote v0.3.15 is already activated
DEBUG:cargo::core::resolver: checking if syn v0.11.11 is already activated
```

I was pointed to #4806, but I don't think it is exactly that, since that one mentions pushing forever to a vector and the memory consumption of the process doesn't grow at all. But I didn't get the fix yet from rustup:

```
$ cargo --version
cargo 0.25.0-nightly (930f9d949 2017-12-05)
```

This is also happening with beta and stable.

If I comment either slog-json or version-sync from the dev-dependencies, run `cargo check`, then it works. Afterwards, when I already have Cargo.lock present, I can uncomment it and it continues to work. When I remove Cargo.lock, the problem returns.

**Comment by alexcrichton** [comment]
This is most likely to be https://github.com/rust-lang/cargo/issues/4066, but would have to investigate more to see what's going on.

**Comment by vorner** [comment]
I'm not sure. That one seems to talk about searching a huge space of options and taking a long time, but getting it done eventually. This one, at least according to the log messages, makes no forward progress and has a true cycle.

I'll try letting this run overnight to see if it gets done or not.

**Comment by Marwes** [comment]
Also getting this bug for this repo https://github.com/paritytech/jsonrpc

**Comment by vorner** [comment]
Still running…

**Comment by kivikakk** [comment]
I'm getting this issue on `stable` (1.23.0) and `nightly` (1.25.0-nightly 51b0b3734 2018-01-12) with the following `Cargo.toml` dependencies:

```toml
[dependencies]
piston_window = "0.35.0"
piston2d-graphics = "0.24.0"
pistoncore-glutin_window = "0.43.0"
piston2d-opengl_graphics = "0.50.0"
```

I've just tried installing 1.20.0 and it's happening there too. (It looks like it's taking forever on `Updating registry […]`, but `RUST_LOG=debug` shows it's looping in the resolver.)

**Comment by alexcrichton** [comment]
@kivikakk you're running into https://github.com/rust-lang/cargo/issues/4066

**Comment by Eh2406** [comment]
Move to close? do to #5213.

**Comment by alexcrichton** [comment]
Definitely!
