### ISSUE TITLE
Sharing `target` directories

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#482]
Projects like servo have many dependencies, all of which need to be tested. It's much easier to set up CI for all of the dependencies once than separately. Right now it's the case that `cargo test` must be run once in each dependency, causing many libraries to be built many times. It would be much nicer if the `target` output directories could be shared amongst dependencies (somehow).

**Comment by metajack** [comment]
Is this on the radar at all?

**Comment by alexcrichton** [comment]
@metajack not currently, but I can try to flesh something out if needed.
