### ISSUE TITLE
Weird error messages when disk is full or quota is reached

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/cargo#4842]
Hi all

I hit a strange error on a machine with quotas. Depending on the state of the compilation the error ranges from panic of rustc to linker failure.
Would it be possible to handle this case with a better error message?

Best

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have an example of the error message as well?

**Comment by alexcrichton** [comment]
(just to know where to improve)
