### ISSUE TITLE
Optional git dependency downloaded unconditionally

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/cargo#4847]
I have a project with an optional git dependency (only temporarily until a new version is published), but the (rather large) git repository is being downloaded even if the corresponding feature is not enabled.

I.e. cargo says 
```
Updating git repository `https://github.com/...`
```
with a nice progress bar, but the dependency is never used.

I think that optional dependencies from crates.io are not even downloaded if not used, so this seems like a bug.

**Comment by alexcrichton** [comment]
Thanks for the report! This is currently intentional behavior, however. Optional dependencies for the crate you're working on are always downloaded to generate a `Cargo.lock`, but for upstream dependencies they're not in `Cargo.lock` so they're not downloaded.

**Comment by Boddlnagg** [comment]
Thanks for the clarification!

**Comment by Pyrromanis** [comment]
Has anything changed? I have an optional dependency to a private repo, and it tries to update it (and fails), even when I have not specified the feature, making it unfeasible if you do not have access rights, which in turn makes the whole thing redundant
