### ISSUE TITLE
Reorganize integration tests as one crate with many modules

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#4867]
Currently, Cargo has a huge amount of integration tests. The problem with them is that each test is a separate artifact, and each tests gets a copy of Cargo linked in. This leads to a **HUGE** `./target` directory after `cargo test`, about `7 GB`.

What if instead we have only *one* crate with integration tests, which consists of a number of submodules? That is, to have this layout

```
tests/
  cargosuite/
    main.rs # <- mod build; mod run; mod test; mod publish;
    build.rs
    run.rs
    test.rs
    publish.rs
```

**Comment by alexcrichton** [comment]
This may no longer be a problem with incremental compilation, but historically I haven't done this because it makes compilation time for tests huge. Would just want to be sure that editing tests doesn't take minutes to get a new artifact!

**Comment by matklad** [comment]
>Would just want to be sure that editing tests doesn't take minutes to get a new artifact!

Yeah, the alternative would be for tests not to link with `cargo`. I think it is possible to achieve, but will require moderately more complicated changes. Not that we need to do anything with tests right now, but it would be great to fix it one day :)

**Comment by rochamatcomp** [comment]
I can try to do.
