### ISSUE TITLE
`cargo check --all --examples` actually does a build, in a virtual workspace

### ISSUE THREAD

**Issue by rocallahan** [rust-lang/cargo#4869]
It runs `ld` and generates build output files. This seems unexpected.

Similar to https://github.com/rust-lang/cargo/issues/4387, but instead of failing actually does a build instead.

**Comment by ehuss** [comment]
I think this is a dupe of #4059, and has been fixed in beta (cargo 0.24, rustc 1.23).  Can you try on beta and see if it is still a problem?

**Comment by rocallahan** [comment]
Sorry, this seems to be fixed in nightly.
