### ISSUE TITLE
unused [patch] section should emit warning

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/cargo#4870]
This is similar to #3099 and #3324 but for the new `[patch]` section. In particular, `[patch]` sections in non-virtual workspace manifests are silently ignored. Cargo should emit a warning or deny the `[patch]` section in non-root workspace crates entirely.

**Comment by alexcrichton** [comment]
Agreed!

**Comment by MathieuDuponchelle** [comment]
Ideally, cargo should also explain *why* the patch section gets ignored, I don't know how difficult that is to implement though :)

**Comment by sdroege** [comment]
If someone can provide a testcase I can take a look, but everything I tried either works correct (because the patch matches something), or it fails correctly with "error: failed to resolve patches for ..."
