### ISSUE TITLE
"cargo help test" output should go to stdout

### ISSUE THREAD

**Issue by tromey** [rust-lang/cargo#4878]
Currently, `cargo help test` output goes to stderr.  This makes it unnecessarily difficult to pipe the output through a pager.  Furthermore, this isn't an error situation -- the command exists to print the help, so it seems to me that it ought to go to stdout.  (If it's any use, this is a longstanding GNU convention for tools as well; so many if not most core Linux utilities work this way.)

**Comment by alexcrichton** [comment]
Definitely sounds like a bug!

**Comment by tromey** [comment]
Perhaps the cause is actually in docopt.

**Comment by tromey** [comment]
No, docopt seems to do this properly at first read.

**Comment by tromey** [comment]
Changing `exit_with_error` to print to stdout in the non-fatal case worked for me, but I wonder if this needs a test.

**Comment by matklad** [comment]
> Furthermore, this isn't an error situation 

To give some historical context, we use `stderr` in Cargo not only for errors, but for all "human" content, so that tools can safely parse stdout as JSON.

This definitely should not apply to `cargo --help` though!

**Comment by tromey** [comment]
I added a test to `tests/search.rs` but I can't tell from `cargo test` whether or not it is actually running.  I guess I can try hacking in a println and see if that does anything.

**Comment by tromey** [comment]
Yeah, that doesn't seem to run.

**Comment by tromey** [comment]
Aha, I figured out how to run it by hand.
