### ISSUE TITLE
Cargo build with multi features

### ISSUE THREAD

**Issue by u2** [rust-lang/cargo#4882]
ENV:
```
➜  cita-crypto git:(cache_ci_target) ✗ cargo --version                          
cargo 0.24.0-nightly (5bb478a51 2017-11-29)

➜  cita-crypto git:(cache_ci_target) ✗ rustc --version
rustc 1.24.0-nightly (8503b3ff8 2017-12-04)
```

It only works like `cargo build --features 'sm2 sm3hash kafka'`,
but if I removed the quotes,
```
cargo build --features secp256k1 sha3hash
error: Invalid arguments.

Usage:
    cargo build [options]
```

But both work for cargo test

```
➜  cita-crypto git:(cache_ci_target) ✗ cargo test --no-run --features "secp256k1 sha3hash"
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
➜  cita-crypto git:(cache_ci_target) ✗ cargo test --no-run --features secp256k1 sha3hash  
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
```

so, why it's different? Is it a bug?

**Comment by alexcrichton** [comment]
Thanks for the report! This has to do with CLI parsing and shells and whatnot. When you use quotes it's passed as a single CLI argument which is then interpreted as the value for the `--features` flag. When you don't use quotes it's passed as two separate arguments, one which is interpreted as the value of the `--features` flag and one which is a bare argument to Cargo.

`cargo build` takes no arguments (hence the "Invalid arguments") and `carog test` takes arguments which are forwarded to the test binaries (hence the valid run). `cargo test --no-run --features secp256k1 sha3hash` is not what you want though as it does not enable the `sha3hash` feature, it only enables the `secp256k1` feature.

**Comment by u2** [comment]
Thank you

**Comment by fan-tom** [comment]
> `cargo test --no-run --features secp256k1 sha3hash` is not what you want though as it does not enable the `sha3hash` feature, it only enables the `secp256k1` feature.

Is it documented anywhere? A have spent about a hour figuring out why only the first feature is passed to rustc, using `--verbose` until I found this issue

**Comment by artmg** [comment]
try " " double quotes around multiple features in **cargo** commands

**Comment by rootkea** [comment]
> cargo test --help says only that --features accepts space-separated list of features, not that it must be enclosed by quotes

Yes. From `cargo build --help`:
```
--features <FEATURES>...     Space or comma separated list of features to activate
```

It doesn't say anything about that Space or comma separated list be enclosed by quotes.
