### ISSUE TITLE
cargo test should craft the correct LD_LIBRARY_PATH variable in the case of a cargo:rustc-link-search args

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#4887]
Currently, if you create a crate dynamically linking to a C library, you make this work by feeding `cargo:rustc-link-search` arguments to cargo from the build script.

However, this only impacts the compile time linker args, not the dynamic linker args when running `cargo test`. For `cargo test` we should use a `DYLD_LIBRARY_PATH` or `LD_LIBRARY_PATH` crafted from all the `cargo:rustc-link-search` build script outputs so that the test can run out of the box.

cc @alexcrichton 

(h/t @mgattozzi for discovering this)

**Comment by Manishearth** [comment]
cargo run as well, really

**Comment by alexcrichton** [comment]
Do you have a test case showcasing this behavior? We have a [number of tests](https://github.com/rust-lang/cargo/blob/a88fbace48ac42ab21e1d8609012480d0aeab982/tests/build-script.rs#L1213-L1291) that this is indeed implemented, so there's either a bug we're missing or it's not clear to me what the bug is.

**Comment by Manishearth** [comment]
https://github.com/Manishearth/testcrate

compile test.c into a .so file, keep it in the src folder

(`gcc -c -Wall -Werror -fpic test.c`, and then `gcc -shared -o libtest.so test.o`)

cargo test will compile, but fail to run. You have to run `DYLD_LIBRARY_PATH=src cargo test` for it to work.

`cargo build` seems to fail but I'm not sure why.

**Comment by alexcrichton** [comment]
Ah ok so this is how Cargo only modified `DYLD_LIBRARY_PATH` for artifacts as part of the build (aka those in the `target` directory). Everything outside of the `target` directory is in considered outside Cargo's control, so it's not added to the loader path automatically.

**Comment by Manishearth** [comment]
Right, but for the purposes of `cargo test`, shouldn't we use the same runtime dylib path as the compile time ones used from rustc-link-search (in the case of there being at least one dylib being linked to, which it knows about)?

**Comment by alexcrichton** [comment]
In theory, yes, but anything outside of the `target` directory is outside of Cargo's purview. Cargo used to update the loader path for all `rustc-search-path` prints and it caused too many bugs on various system configurations.

**Comment by Manishearth** [comment]
can we specifically provide a way to instruct cargo to append to the dynamic loader path?

**Comment by alexcrichton** [comment]
Heh yes, we do indeed always have the option of adding features to Cargo to do more things. Mind opening a more targeted issue tagged as a feature request?

**Comment by Manishearth** [comment]
https://github.com/rust-lang/cargo/issues/4895
