### ISSUE TITLE
All dependencies recompiled if there is an error during "cargo install <crate>"

### ISSUE THREAD

**Issue by vezaynk** [rust-lang/cargo#4890]
I am running `cargo install letsencrypt-rs` and every time there is an issue with a dependency (Needed to install make, etc), the process was killed and when I tried again it would recompile every single one of the dependencies.

This is bad because the compiled dependencies should be instead reused as it takes a ton of time, much more so when there is seemingly a hundred dependencies.

There's probably a more minimal way to reproduce it but one way is to take a system without `make`, run `cargo install letsencrypt-rs`, after a certain dependency it will fail and make you restart all over again.

**Comment by weihanglo** [comment]
sputnick1124 is pretty much correct I believe. To improve, we could tell people do what sputnick1124 has taught in the error message, like:

```
error: failed to compile `doomed-to-fail v0.1`, intermediate artifacts can be found at '/some/tmp/directory'
    To reuse those artifacts, set the environment variable `CARGO_TARGET_DIR` to that path.
```
