### ISSUE TITLE
build.rs is not run after src/main.rs changed, when using cargo:rerun-if-env-changed

### ISSUE THREAD

**Issue by xftroxgpx** [rust-lang/cargo#4901]
I made this simple project illustrate the issue: https://github.com/xftroxgpx/buildrs_not_updated
(just run `./go`)

In simple terms:
1. `touch src/main.rs`
2. `cargo build`
 will not recompile `build.rs` because it used `cargo:rerun-if-env-changed` ([doc](http://doc.crates.io/build-script.html#outputs-of-the-build-script))
thus `src/main.rs` will use stale `build.rs` `...../output` !
3. remove the use of `cargo:rerun-if-env-changed`
4. repeat steps 1 and 2.
that recompiles `build.rs` every time you do step 4. now.

tested two versions of cargo:
cargo 0.26.0
release: 0.26.0
and
cargo 0.25.0-nightly (a88fbace4 2017-12-29)
release: 0.25.0
commit-hash: a88fbace48ac42ab21e1d8609012480d0aeab982
commit-date: 2017-12-29

with rust:
rustc 1.24.0-dev (687d3d15b 2018-01-02)
binary: rustc
commit-hash: 687d3d15ba726dbb1ac6b85223ebe0e98c6820cc
commit-date: 2018-01-02
host: x86_64-unknown-linux-gnu
release: 1.24.0-dev
LLVM version: 4.0

**Comment by alexcrichton** [comment]
Thanks for the report! Is this perhaps the same bug as https://github.com/rust-lang/cargo/issues/4587?

**Comment by xftroxgpx** [comment]
Exactly! Thank you for spotting that! I forgot to search first, for some reason :)

I guess I'll close this in favor of that one
