### ISSUE TITLE
Improve CLI parameter validation errors

### ISSUE THREAD

**Issue by masklinn** [rust-lang/cargo#4903]
These are minor QOL issues but following seeing https://www.reddit.com/r/rust/comments/7o3sgg/how_to_use_the_name_option_with_cargo/ I tried:
```sh
> cargo new --bin --name 01-init-instance
error: Invalid arguments.

Usage:
    cargo new [options] <path>
    cargo new -h | --help
```
The error message is unclear, the *Usage* section obliquely hints at the issue but the requirement of an FS path could be spelled out more clearly.

```sh
> cargo new --bin --name 01-init-instance a
error: Package names starting with a digit cannot be used as a crate name
use --name to override crate name
```
The error itself is correct, but the suggestion is not.

**Comment by daschl** [comment]
@masklinn I created PR #4924 which I think does solve the second issue. The invalid arguments is done in a different spot, so that can be a separate PR i think.

**Comment by sanmai-NL** [comment]
See also: https://github.com/rust-lang/cargo/pull/12766
