### ISSUE TITLE
install --reinstall functionality

### ISSUE THREAD

**Issue by bmusin** [rust-lang/cargo#4912]
Hi. 
Do you consider implementing that functionality?
Otherwise, doing manually `cargo uninstall <package> && cargo install <package>` isn't
convenient.

**Comment by lukaslueg** [comment]
There is also `cargo install -f <package>`

**Comment by bltnkl** [comment]
Yes, but it's not exactly that behaviour.
It's meant to be used to force overwrite new files over existing binaries
not to uninstall and then install package anew.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is covered by https://github.com/rust-lang/cargo/issues/2082 so closing in favor of that.
