### ISSUE TITLE
Confusing statement in docs about the [patch] section

### ISSUE THREAD

**Issue by whitequark** [rust-lang/cargo#4918]
Docs currently say:

> These scenarios are currently all solved with the [patch] manifest section. Note that the [patch] feature is not yet currently stable and will be released on 2017-08-31. Historically some of these scenarios have been solved with the [replace] section, but we'll document the [patch] section here.

However, 2017-08-31 has passed. Is it stable yet?

**Comment by alexcrichton** [comment]
It is indeed stable!

**Comment by ehuss** [comment]
This was fixed by #4965.

**Comment by alexcrichton** [comment]
Thanks!
