### ISSUE TITLE
How to get a library type from ops::Compilation::libraries?

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/cargo#4927]
`core::manifest::TargetKind`/`crate-type` can have a list of types, but `ops::Compilation::libraries` has all values set for each path.

Example:
```rust
// ...

let comp = ops::compile(&workspace, &opt)?;
for (_, lib) in comp.libraries {
    for (target, path) in lib {
        println!("{:?} {:?}", target.kind(), path);
    }
}
```

It will return:

```
Lib([Rlib, Other("cdylib"), Other("staticlib")]) "libtest.so"
Lib([Rlib, Other("cdylib"), Other("staticlib")]) "libtest.a"
Lib([Rlib, Other("cdylib"), Other("staticlib")]) "libtest.rlib"
```

But how can I get a path to `cdylib`?

**Comment by alexcrichton** [comment]
I think this is one you'll have to infer yourself for now, but PRs are always welcome to tweak Cargo's API!

**Comment by RazrFalcon** [comment]
Doesn't `LibKind` should contain only one type and not all of them?

**Comment by alexcrichton** [comment]
The various organization of internal structures isn't always the cleanest in Cargo, unfortunately :(. You'll have to do some amount of digging yourself I think to extract information like this. 

The `TargetKind` contains a vector of `LibKind`, where one of those is cdylib in this case. There's not enough information to match that up to which filename is returned right now.
