### ISSUE TITLE
How to detect workspace root?

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#4933]
A recent change (#4788) changed it so that when you run cargo from within a workspace member, the paths in messages are now relative to the workspace root instead of the member package.  I work on the [Sublime integration](https://github.com/rust-lang/rust-enhanced), and the tool needs to know how to resolve the relative paths so that you can jump to the appropriate file when there is an error/warning.  Currently it uses a simple logic of basing paths off the package's root.  However, now it needs to know the workspace root, but I am uncertain how to find that.  `cargo metadata` doesn't seem to offer any help.  Is there some heuristic I can use?

Note: Currently the build tool doesn't know whether or not it is in a workspace.  It blindly runs `cargo build` in the directory of the package.

**Comment by alexcrichton** [comment]
Hm a good point! I actually don't think we've got a great way to learn about the workspace root, but for sure we should add it to `cargo metadata`!

**Comment by ehuss** [comment]
I can open a PR to add that.  I have a few questions:

* What do you think of just adding a new key `"workspace_root"`, or should it be something else?
* Does the metadata version need to change when adding keys?  I would assume no, but the versioning rules don't seem to be defined.
* Would it be feasible to backport this to beta?  Without it I would need to recreate all the logic in parsing manifest files which sounds unpleasant.  I assume all editors/IDEs/tools which read paths will need this.

**Comment by alexcrichton** [comment]
Perhaps something like `workspace_manifest: String`? And yeah no need to bump the version, we'd only do that if we changed the existing version.

And sure yeah, we can backport to beta!
