### ISSUE TITLE
It's impossible to run cargo package on a crate that enables unstable features

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#4954]
For `cargo publish` you just need to pass a registry, but there doesn't appear to be any such flag on `cargo package`. Why do we want to forbid packaging crates with unstable features at all rather than just forbidding publishes?

**Comment by alexcrichton** [comment]
Perhaps just a missing feature? I don't think we intended on explicitly forbidding this

**Comment by sfackler** [comment]
The check looks explicitly for a custom registry, so I think that would need to be changed, or moved to publish.

https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_package.rs#L34-L39

**Comment by alexcrichton** [comment]
Oh right, now that I think about we did actually intend on explicitly forbidding something like this!

More specifically we wanted to forbid uploading crates that enabled features in their manifest to crates.io. I think it'd be fine though to allow `cargo package` over just about anything, it's just the `cargo publish` step we'd want to disallow (to crates.io specifically)

**Comment by sfackler** [comment]
Cool, I'll move it over there.

Should we also check in crates.io? Any check in Cargo would just be a convenience since we don't trust that people are using Cargo to do the publish.

**Comment by alexcrichton** [comment]
Ideally yeah but this wasn't a "we want to forbid this forever" sort of thing it was mostly a roadblock of "hey you really shouldn't do that because we'll be breaking your code"

**Comment by sfackler** [comment]
Ah, that's fine then.
