### ISSUE TITLE
rustfmt: `cargo manifest` failed

### ISSUE THREAD

**Issue by nhynes** [rust-lang/cargo#4963]
platform: Ubuntu 16.04
`rustup --version`: `rustup 1.9.0 (57fc3c087 2018-01-04)`
`cargo +nightly --version`: `cargo 0.26.0-nightly (6a8eb71f6 2018-01-13)`

Steps to reproduce:
```
rustup update nightly
cargo +nightly install rustfmt-nightly --version 0.3.6 --force
cargo +nightly fmt
```
Observe:
```
`cargo manifest` failed.
usage: cargo fmt [options]
...
```

I tried an internet search for "cargo manifest failed" but nothing relevant is returned. Where have I gone wrong?

**Comment by sfackler** [comment]
This seems like something that would best be filed over on the rustfmt repo - https://github.com/rust-lang-nursery/rustfmt.
