### ISSUE TITLE
the links is not doct in manifest.html

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/cargo#4975]
I was looking for the specification for the `links = ` attribute in a `Cargo.toml` so I looked in the definition in https://doc.rust-lang.org/cargo/reference/manifest.html but it is not there!

@sfackler on irc pointed me to https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key but confirmed it should also be in the `manifest.html`

**Comment by matklad** [comment]
The source code for docs lives here: https://github.com/rust-lang/cargo/tree/c157d7dd7a9f5b93b08f3335c29a883990c7fd75/src/doc/src/reference
