### ISSUE TITLE
cargo emits error when run in sandboxie

### ISSUE THREAD

**Issue by retep998** [rust-lang/cargo#4985]
After nearly any command completes:
```
thread 'main' panicked at 'assertion failed: list.len() > 0', src\tools\cargo\src/cargo\util\job.rs:166:12
stack backtrace:
```
It still builds or runs whatever I ask, but it always emits that error when its done.

For those who don't know, sandboxie is a sandboxing thing for Windows, which is really important when building random untrusted projects off the internet which could execute arbitrary build scripts and pwn your computer.

**Comment by retep998** [comment]
It's **much** worse now, because now cargo refuses to work outright!

```
> cargo build
   Compiling winapi v0.3.5 (file:///C:/Users/Peter/Code/winapi-rs)
error: failed to build archive: permission denied

error: aborting due to previous error

thread 'main' panicked at 'assertion failed: list.len() > 0', tools\cargo\src/cargo\util\job.rs:179:13
stack backtrace:
```

**Comment by Eh2406** [comment]
Thanks to the stale bot for reminding me that this exists. Sorry that it has not been addressed already.

I am a contributor to cargo and a windows based lifeform, but I have know idea how to get started on addressing this. I had not heard on `sandboxie` before this issue. How does one start debugging problems caused by it?

**Comment by retep998** [comment]
With a bit of further testing, the refusing to work outright isn't cargo's fault, but rather rustc's fault, so I'll have to open another issue for that, and it only applies when creating rlibs, not binaries.

As for the spurious assertion in cargo itself... after updating my nightly it appears that https://github.com/rust-lang/cargo/pull/5887 fixed it.

**Comment by retep998** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/54297 given the issue in cargo itself was fixed and instead there is now an issue in rustc.
