### ISSUE TITLE
Detect API-breaking changes to help save ecosystem development time

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#4986]
It would be good if cargo had a feature to output the amount of other people's time that one wastes by pointlessly changing APIs. e.g.

~~~~
$ cargo build
$ [.. hack hack hack, change Option<X> -> Result<X, String> ..]
$ cargo build

warning: breaking-API change detected. estimating time cost of change:

transitive dependants of your package: 100
- number of distinct authors: 50
- total callsites of the broken API: 200

time wasted:
- research time: 50 * 10 minutes = 8:20 person-hours
- fixing time: 5 * 200 = 16:40 person-hours
- multiplier to take into account unknown and future dependants: 1.2
- estimated total: 30 person-hours wasted

aborting the build. to ignore this error, pass
--i-really-think-the-benefit-of-this-breaking-API-change-is-worth-wasting-X.YY-person-hours
where X.YY is the estimated total given in the above error message.

exit code 1
~~~~

**Comment by aturon** [comment]
I'm sorry that you've had a bad experience as a downstream user of the crates.io ecosystem, but venting here to the Cargo team isn't helpful either.

[This issue](https://github.com/rust-lang/crates.io/issues/435) on crates.io tracks the creation and use of a semver tool that would probably have a strong impact on the ecosystem.

**Comment by infinity0** [comment]
Thanks for the pointer, and of course I was only half-joking.

Doing this in cargo itself and having it be overridable locally, might help avoid issues around enforcing something whose meaning is vague and context-dependent, as noted on the issue you linked. I also think it's useful and educational to give specific and quantified information on why certain practises are not good, rather than just auto-rejecting stuff.

Also I think my point was mostly independent of adhering to semver. Even if someone version-bumps their package correctly according to semver, they are still wasting other people's time if they change their API constantly in minor "paper cut" ways every week from 79 to 80 to 100 at the end of the year.
