### ISSUE TITLE
Book sentence not describing the real behavior

### ISSUE THREAD

**Issue by Kerollmops** [rust-lang/cargo#4987]
I found in [the cargo book](https://doc.rust-lang.org/cargo/reference/manifest.html#the-project-layout) a sentence that doesn't seems to be right:
> Cargo will no longer automatically build files located in `src/bin/*.rs`.

And when I put files containing `main` functions in the `src/bin/` folder, cargo build all of them without specifying any `[[bin]]` in my `Cargo.toml` file.

**Comment by ehuss** [comment]
I think the documentation is correct.  Cargo will automatically build all the binaries as long as you do **not** specify `[[bin]]`.  That sentence is trying to clarify that once you specify at least one `[[bin]]`, it will only build the bins explicitly specified in Cargo.toml.

Are you seeing different behavior than that?

**Comment by Kerollmops** [comment]
Ho you are completely right about that, this sentence is related to the previous one, speaking about specifying `[[bin]]`.

My bad. Have a good day !
