### ISSUE TITLE
Inconsistent negation flag names

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/cargo#4994]
```
    --no-run                     Compile, but don't run tests
    --no-default-features        Do not build the `default` feature
    --no-fail-fast               Run all tests regardless of failure
    --nocapture
```

As you can see from the above `--nocapture` (which I can not find the definition of outside of the `help` text) which is passed to the test binaries is inconsistent with the other `--no...` flags.

**Comment by sfackler** [comment]
--nocapture is part of the test harness built by rustc, not part of cargo.

**Comment by Eh2406** [comment]
Is there anything we can do? If not move to close?

**Comment by matklad** [comment]
This is indeed does not belong to Cargo per se. However, the inconsistency is real. I would suggest doing a small investigation of how rustup and rustc handle no flags, and if they all use dashes, we should probably open an issue/pr at rust-Lang/rust, which adds no-capture and deprecates nocapture.
