### ISSUE TITLE
Feature Request: Build without build script

### ISSUE THREAD

**Issue by dbrgn** [rust-lang/cargo#4997]
(I searched for this and could not find any solution, I hope this isn't a duplicate of another ticket 🙂)

I have a few projects where I generate C header files during build time using [cbindgen](https://github.com/eqrion/cbindgen). Sometimes the code does not compile, and then the error messages from cbindgen "mask" the real cargo error messages.

Is there a way to build a project while skipping the build script (`build.rs`)?

**Comment by alexcrichton** [comment]
Currently there's no way to skip an arbitrary build script (as it's often critical to build the crate itself), but perhaps the build script itself could provide an opt-out to running it?

**Comment by dbrgn** [comment]
Hm, true, maybe it could be worked around with an environment variable.

**Comment by dbrgn** [comment]
Yep, this works fine:

```diff
--- a/ffi/build.rs
+++ b/ffi/build.rs
@@ -4,7 +4,10 @@ use std::env;
 
 fn main() {
     let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
+    if env::var("SKIP_CBINDGEN").unwrap_or("0".to_string()) == "1" {
+        return;
+    }
     cbindgen::generate(&crate_dir)
         .expect("Unable to generate C bindings")
         .write_to_file("saltyrtc_task_relayed_data_ffi.h");
```

Followed by `SKIP_CBINDGEN=1 cargo build`. It's probably the more flexible approach than skipping the build script altogether.
