### ISSUE TITLE
unhelpful error message trying to uninstall ambiguous crate name

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#5006]
````
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
rustc 1.25.0-nightly (3d292b793 2018-02-03)
````
I have a rustfmt-nightly installed in $CARGO_HOME.
I tried to remove it:
````
cargo uninstall rustfmt-nightly 

error: There are multiple `rustfmt-nightly` packages in your project, and the specification `rustfmt-nightly` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  rustfmt-nightly:0.3.4
  rustfmt-nightly:0.3.8
````

The error message is confusing, according to ````cargo help uninstall````, ````-p```` is not even a valid option for ````uninstall````

I tried a couple of things
````
cargo uninstall  -p "rustfmt-nightly:0.3.4" 
cargo  -p "rustfmt-nightly:0.3.4" uninstall
cargo uninstall rustfmt-nightly -p "rustfmt-nightly:0.3.4" 
````
but none of these worked.

EDIT:
Hmm, I found this in my $CARGO_HOME/.crates.toml
````
"rustfmt-nightly 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-fmt"]
"rustfmt-nightly 0.3.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt", "git-rustfmt", "rustfmt", "rustfmt-format-diff"]
````

**Comment by matthiaskrgr** [comment]
Hmm, I think the underlying problem is that rustfmt changed the name of its executable which might have confused cargo.
https://github.com/rust-lang-nursery/rustfmt/commit/361a30b159b40baf65d314e7498b71df83c206e3#diff-80398c5faae3c069e4e6aa2ed11b28c0
While upgrading from one version to another, cargo apparently did not remove the old binary properly so I ended up with orphaned executables, I guess.

**Comment by seanmonstar** [comment]
To clarify, this issue is that the help text from `cargo uninstall foo` is incorrect if the spec is ambiguous. It suggests running `cargo uninstall -p foo:1.2.3`, when **really you run** `cargo uninstall foo:1.2.3`.

A fix to this issue would be removing the `-p <spec>` part of the help text.
