### ISSUE TITLE
rustc --externs paths should be deterministic

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#5010]
Currently their order varies between runs. 

Could anybody point me to the places where the externs paths are passed to rustc ?

**Comment by alexcrichton** [comment]
This is sort of semi-accidental and semi-intentional. Did this cause a bug though?

**Comment by gnzlbg** [comment]
No bugs, it just makes it harder to test multi-dependency issues with `with_stderr_contains` because the `--externs` paths are already in a different order

**Comment by alexcrichton** [comment]
Ok! In that case I'm going to close this as we have assertions like `[..]` for our test suite, and otherwise I'm not aware of this causing bugs in practice

**Comment by gnzlbg** [comment]
Ok! This isn't part of deterministic build right? Deterministic builds are only about binaries ?

**Comment by alexcrichton** [comment]
Indeed!
