### ISSUE TITLE
How to delete a miss-published version in a crate?

### ISSUE THREAD

**Issue by LEXUGE** [rust-lang/cargo#5016]
I have a [crate](https://crates.io/crates/xch-ceb) named `xch-ceb`.
I wrote a miss version number `v1.1.5` and published it.
Meanwhile, I found out the version should be `v1.0.0`. So, I correct the version and republished it. But now, the latest version actually was `v1.0.1`, and because I published the wrong version(`v1.1.5`) before, so the latest version on crates.io is `v1.1.5`.

How can I delete the `v1.1.5` now?
Or are there any other solutions?

BTW: Sorry for my terrible English.

**Comment by steveklabnik** [comment]
Hi there!

> BTW: Sorry for my terrible English.

Your English is fine, don't worry about it!

> How can I delete the v1.1.5 now?

You cannot delete uploaded packages. However, you can yank them: https://doc.rust-lang.org/stable/cargo/reference/publishing.html#cargo-yank

```shell
$ cargo yank --vers 1.1.5
```

Finally, we try to keep the issues tracker for bugs only; https://users.rust-lang.org/ is often a better way to get help, so you might want to post there in the future.

Thank you!
