### ISSUE TITLE
test update index

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/cargo#5019]
I was working on error messages when I noted that several/meny of cargos test call commands that update the index and are not testing that behavior. We could save some time if these tests use the new `-Zno-index-update`.

**Comment by alexcrichton** [comment]
Just to confirm, these aren't updating the crates.io index, right? Just a local version?

**Comment by Eh2406** [comment]
Correct, nothing severely wrong just an extra GIT pull,  with its round
trip to the internet, for each test.

**Comment by Eh2406** [comment]
I considered adding a `.arg("-Zno-index-update")` to most tests, or eavan making it opt out, but that only works with a `.masquerade_as_nightly_cargo()`. So I thout I would open an issue to discuss how to proceed.

**Comment by alexcrichton** [comment]
Hm do you think this has been masking bugs? Unless it's causing a problem I'd be tempted to just leave it as-is...

**Comment by Eh2406** [comment]
No, and leave it as-is a reasonable solution. If it is running a GIT pull for a bunch of tests then it may be costing us a couple of minutes for each full run of the test sweet. Which would be nice to have, especially given how tite the rust repo CI is. But overall it is not a big deal.

**Comment by alexcrichton** [comment]
Oh hm, aren't these cloning from local git repos on disk? But is that taking awhile?

**Comment by Eh2406** [comment]
The ones that are cloning from local git repos are not my concern. I thought I saw "    Updating registry `https://github.com/rust-lang/crates.io-index`" while updating error messages. If I miss read it than I was wrong and all is well.

**Comment by Eh2406** [comment]
I added `assert_ne!("registry `https://github.com/rust-lang/crates.io-index`", self.source_id.display_registry());` to `update_index` and ran the test sweet.

failures:
    no_index_update
failures:
    finds_author_email
    finds_author_git
    finds_author_user
    finds_author_user_escaped
    finds_author_username
    finds_git_author

So this doesn't look like a problem, sorry.
