### ISSUE TITLE
wrong Nightly Cargo download URL

### ISSUE THREAD

**Issue by Passw** [rust-lang/cargo#5027]
https://doc.rust-lang.org/cargo/getting-started/installation.html

**Install Nightly Cargo**
https://static.rust-lang.org/cargo-dist/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz

```
cargo --version
cargo 0.16.0-nightly (3568be9 2016-11-26)
```

Nightly Cargo download URL is still version of 2016 ...

**Comment by Passw** [comment]
Hi @alexcrichton ,

  Where can I download the latest Cargo nightly binary as before ? [cargo 0.16.0-nightly](https://static.rust-lang.org/cargo-dist/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz)

What is the URL for ***cargo 0.24.0-nightly*** ?

Thanks

**Comment by alexcrichton** [comment]
@Passw Cargo comes with rustc, there's no supported way of downloading *just* Cargo
