### ISSUE TITLE
Very bad diagnostics when git fetching using SSH

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/cargo#5035]
For reasons unrelated to cargo, I have `git` set to always use ssh URLs instead of https URLs. This has unfortunately meant a world of pain for me for a variety of reasons.

I had gotten very used to seeing this error message, which indicated that somewhere in the ridiculous contraption that bound together ssh-agent, git, and my shell, something had gone wrong:

```
Caused by:                                   
  failed to authenticate when downloading repository                                      
attempted ssh-agent authentication, but none of the usernames `git` succeeded             
```

I was especially baffled this time, because `git` was using SSH auth fine, and the error only appeared to be in `cargo`.

After about 20 minutes of confused debugging, I figured out the problem: I was attempting to fetch `withoutboats/anchor-experiment`, but the repo is named `withoutboats/anchor_experiment`.

It would be nice if we could present a better error message that would distinguish between not having access rights to a repository (possibly because it doesn't exist) from not being able to authenticate at all.

**Comment by alexcrichton** [comment]
Just to confirm, you think Cargo was using the SSH url, right?

Locally at least using `git`-the-CLI I get:

```
$ git clone https://github.com/withoutboats/anchor-experiment
Cloning into 'anchor-experiment'...
Password for 'https://alexcrichton@github.com': ^C
$ git clone git@github.com:withoutboats/anchor-experiment
Cloning into 'anchor-experiment'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So I'm not actually sure if there's anything we can do with the `https` url, but if it's via SSH there's presumably *something* we can do!

**Comment by withoutboats** [comment]
Yes, I have this in my `.gitconfig`

```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

And the error message indicated that ssh-agent authentication failed (which is incorrect, but wouldn't make sense if it were over HTTPS).

**Comment by ehuss** [comment]
I took a little look at this.  It seems like part of the problem is that "Internal" errors are not displayed by default unless you pass `--verbose`, in which case it would look like:

```
Caused by:
  [23/-20] ERROR: Repository not found.
```

The code [here](https://github.com/rust-lang/cargo/blob/489f570d47dea88d8f9a1205173d3e779e1a78e2/src/cargo/sources/git/utils.rs#L549) maps most git errors to an Internal error.

Looking through the past, it looks like Cargo has a long history of differentiating "human" vs internal errors, and these git errors have always been hidden this way.  I'm not sure what the correct course would be since I'm unfamiliar with why they are differentiated this way.

**Comment by alexcrichton** [comment]
Oh wow, thanks for looking into this @ehuss! 

I've often though that our internal/human distinction for errors has not worked out well for us so this seems like clearly a case where basically any and all network errors should not be listed as internal! Want to send a patch for this?
