### ISSUE TITLE
Please publish the release tag for 0.25.0

### ISSUE THREAD

**Issue by copyninja** [rust-lang/cargo#5047]
Hi,
It looks like tag for cargo 0.25.0 is not yet published. We in Debian still package cargo separately and it will be helpful for us if you could just publish the tag so we can track and update the cargo package.

See related: #4757

**Comment by Mark-Simulacrum** [comment]
Cc @aturon @alexcrichton, could you publish the tag?

**Comment by aturon** [comment]
Done!
