### ISSUE TITLE
"cargo clean --verbose" prints nothing

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#5056]
Something like "Removing  /path/to/proj/dir/target" might be appropriate in my opinion.

**Comment by tobywhughes** [comment]
Looks like clean just calls a method to remove the individual directories (usually just /target). Should be easy to add. I'll do that.

**Comment by matthiaskrgr** [comment]
Ah, indeed! Closing...

For the record:
````
$ cargo clean -v
    Removing /tmp/rusttest/target
````
