### ISSUE TITLE
`cargo clean` hook to clean up arbitrary stuff.

### ISSUE THREAD

**Issue by vext01** [rust-lang/cargo#5078]
Following on from #5077, we had a project which built some C code using an external build system (make in this case, but it could be autotools or cmake for example):
https://github.com/vext01/rust_link_test

Currently there is no way to clean the externally built code at `cargo clean` time. Such a feature would be very useful.

**Comment by alexcrichton** [comment]
I think this is a dupe of https://github.com/rust-lang/cargo/issues/572, so I'm going to close in favor of that

**Comment by vext01** [comment]
Thanks
