### ISSUE TITLE
Get rid of `Workspace::current` method

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#5087]
`Workspace` has `current` method:

https://github.com/rust-lang/cargo/blob/ce87cfa6295d2562c5bb0e9404e75722e5093d38/src/cargo/core/workspace.rs#L147-L149

It is not actually used that much, and it's uses seem to be incorrect! Basically, it used in a couple of places to give error messages, like this:

https://github.com/rust-lang/cargo/blob/ce87cfa6295d2562c5bb0e9404e75722e5093d38/src/cargo/ops/cargo_compile.rs#L237-L241

However, the messages are not actually correct 100% of the time. For example, here's the case where the warning is just plain wrong:

```
$ cargo new foo
$ cd foo
$ cargo build --all --exclude foo
:fire: bla-bla-bla :explosion:
manifest path `../foo/Cargo.toml` contains no package: The manifest is virtual, and the workspace has no members.
```

Here, the manifest is not virtual!

So, let's move this empty check inside of `into_package_id_specs` method and make sure it is correct! (adding the case above as a test).

After that, we should be able just to remove `Workspace::current` method

**Comment by tdbgamer** [comment]
I'd like to attempt doing this ticket if you guys are okay with it. Not super familiar with the code base, but I skimmed through it and it mostly made sense to me.

Just to make sure I understand the issue correctly. `into_package_id_specs` correctly filters out excluded members from the workspace and the `specs.is_empty()` check incorrectly assume that this means the workspace has a virtual manifest when it actually just a workspace with no members. Right?

**Comment by matklad** [comment]
Awesome @tdbgamer! 

>Just to make sure I understand the issue correctly. into_package_id_specs correctly filters out excluded members from the workspace and the specs.is_empty() check incorrectly assume that this means the workspace has a virtual manifest when it is actually just a workspace with no members. Right?


This seems right to me! if `specs.is_empty()`, than we *incorrectly* assume that this is because workspace is a virtual manifests without any members. This is wrong, because there may be other reasons for spec to be empty: for example, you can manually `--exclude` every package.

**Comment by tdbgamer** [comment]
@matklad 
I removed the `Workspace::current_manifest` method and modified the error message, but this broke a test.
https://github.com/rust-lang/cargo/blob/847f1f76a16e6c11b2bc69cf7ed21e26baf6fa7b/tests/testsuite/workspaces.rs#L774-L786

I think this test may be wrong as well right? It shouldn't fail because the manifest is virtual, it should fail because there are no members to compile I think.
