### ISSUE TITLE
Warning and errors are not shown in color

### ISSUE THREAD

**Issue by JuanPotato** [rust-lang/cargo#5092]
I am on Arch Linux, and when i run any cargo command, the warnings and errors are no longer colored. This only started happening recently and I'm not sure what the cause may be.

```
cargo --version
cargo 0.25.0 (8c93e0895 2018-02-01)

cargo +nightly --version
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
```

when I run any of the following
```
cargo check
cargo check --color=always
cargo +nightly check
cargo +nightly check --color=always
```
I get the same result
![image](https://user-images.githubusercontent.com/9531780/36737919-40b639ac-1baa-11e8-86bf-f63b64bb208d.png)

when I use color=never, Compiling and Finished are not colored. It seems very odd that only the warnings and errors are not colored.

Forgot to add, this is the code I'm trying to compile as a test;
```rust
fn main() {
    let not_used = 0;
    println!("Hello, world!");
}
```

**Comment by sfackler** [comment]
This is a rustc issue, not a Cargo issue: https://github.com/rust-lang/rust/issues/45728

**Comment by JuanPotato** [comment]
my bad, I'll close
