### ISSUE TITLE
Some crates are blocked by firewall

### ISSUE THREAD

**Issue by thibaultdelor** [rust-lang/cargo#5096]
I work for a fairly large company and would be keen to introduce Rust.
Sadly at the moment I can't even compile a simple project because some crates are not going through the firewall. Some fail the antivirus, some seem  to fail at the decompression step, etc...

I guess I'll have to ask to whitelist the domain but cargo (or should I say crates.io?) doesn't have a nice dns in front of cloudfront (https://d19xqa3lc3clo8.cloudfront.net/crates/)

I know that my security department not gonna like that and will very most likely decline my whitelist request.

On the other side I also believe that Rust should have a nice dns in front of cloudfront at least in order to be large-company friendly.

I am open to any other alternative solution.

PS: I work for a bank and they have pretty good reason to be paranoid about security...

**Comment by thibaultdelor** [comment]
If you are wondering what kind of error her two example:

https://d19xqa3lc3clo8.cloudfront.net/crates/curl-sys/curl-sys-0.4.1.crate
`An error occurred while performing an ICAP operation: Anti-virus engine error (3:0x8004020f); File: curl-sys-0.4.1.crate; Sub File: ; Vendor: Sophos, Plc.; Engine version: 3.70.2; Pattern version: 5.48.16773144.0; Pattern date: 2018/02/28 15:14:44`

https://d19xqa3lc3clo8.cloudfront.net/crates/flate2/flate2-1.0.1.crate
`An error occurred while performing an ICAP operation: File decompression/decode error; File: flate2-1.0.1.crate; Sub File: ; Vendor: Sophos, Plc.; Engine version: 3.70.2; Pattern version: 5.48.16773144.0; Pattern date: 2018/02/28 15:20:24`

I am actually wondering if it is just a coincidence that flate2 fail on decompression.... :)

**Comment by alexcrichton** [comment]
Thanks for the report! I've now added a `static.crates.io` CNAME which these should be going through, does that work for you?

**Comment by thibaultdelor** [comment]
Awesome!
That was in the plan right? Looking at the source code of crates.io, I just realized that the code was ready to make the switch.

Thank you very much.

**Comment by alexcrichton** [comment]
Ah yeah I figured we'd do this one day just hadn't gotten around to it yet :)
