### ISSUE TITLE
Usage message doesn't mention +triple argument

### ISSUE THREAD

**Issue by lzybkr** [rust-lang/cargo#5102]
I stumbled upon the `+triple` syntax in a blog post when I was having difficulty using the `--target` option, and the `+triple` argument did exactly what I needed. It seems like the USAGE message should mention it.

**Comment by sfackler** [comment]
The +triple behavior is specific to rustup - managed installs: https://github.com/rust-lang-nursery/rustup.rs/#toolchain-override-shorthand

**Comment by matklad** [comment]
Yeah, that's a rustup thing, not specific to Cargo, so closing!

**Comment by lzybkr** [comment]
If I understand correctly, the `cargo.exe` I'm running is as `rustup.exe` proxy.

In that case, maybe it makes sense for the proxy to parse the command cargo command line and add to the usage message, but could cargo detect that it is invoked as a rustup managed install and change the usage message?

**Comment by matklad** [comment]
>If I understand correctly, the cargo.exe I'm running is as rustup.exe proxy.

Correct!

Note that `+toolchain` syntax is documented at  `rustup run --help`, and is itself a shorthand for `rustup run toolchain bla-bla-bla`. That is, the thing we really should somehow to call attention to is `rustup run` command, but I am not sure what's the best way to do that.

**Comment by lzybkr** [comment]
Thanks for the confirmation.

Please do consider improving the experience for future folks - `rustup` seems to be the preferred way to install, and it's far from obvious how to discover this documentation right now.

My difficulty arose from tying to use `--target`.

Is it accurate to say that if `--target` is actually specifying the current toolset (so not cross compiling), it's worth a warning that might suggest using the `+toolchain` syntax?
