### ISSUE TITLE
Deadlock when using a non-default `Shell` and cargo::ops::compile_with_exec

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang/cargo#5108]
I'm trying to write a tool for analysing a crate using `rustc` and was hoping to offload the work of determining `rustc`'s command-line arguments to `cargo`. In doing so it looks like I've encountered some sort of deadlock during the resolution process (possibly `cargo::core::resolver::resolve` or further down at `cargo::sources::registry::RegistrySource::do_update`).

The source code is [on GitLab] under the `deadlock` tag, however the code of interest is [here]. In particular, lines 37 and 38.

It seems to be something to do with the cargo `Config`. When I create a default config (`Config::default()?`) it'll work just fine, but when I swapped it out where the shell is created from an `io::Write`, the entire process hangs indefinitely with the CPU idling. Looking at the backtrace, this happens somewhere in the depths of the dependency resolution code when updating the registry. I was originally using `io::sink()` (I don't want cargo to generate any output when invoked by my tool), but I get the exact same behavior for `io::stdout()` as well.

I recorded what I've done from the command-line using the linux `script` tool... Unfortunately it's nothing very interesting to look at.

[script.log](https://github.com/rust-lang/cargo/files/1775798/script.log)

I also managed to get a very verbose backtrace using `gdb`. It shows the values of local variables, so hopefully that helps.

[gdb.txt](https://github.com/rust-lang/cargo/files/1775801/gdb.txt)

---

My Environment:

```
$ uname -a
Linux bryan 4.15.5-1-ARCH #1 SMP PREEMPT Thu Feb 22 22:15:20 UTC 2018 x86_64 GNU/Linux
$ rustc --version
rustc 1.26.0-nightly (3eeb5a665 2018-03-01)
$ cargo --version 
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
$ rg 'cargo' Cargo.lock
270: "cargo 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)",
```

[here]: https://gitlab.com/Michael-F-Bryan/dyna-bindgen/blob/deadlock/src/analysis/invoke.rs#L31-66
[on GitLab]: https://gitlab.com/Michael-F-Bryan/dyna-bindgen/tree/deadlock

**Comment by alexcrichton** [comment]
Cargo does tweak its behavior slightly depending on whether a tty is available or not but it's pretty buried to the point that it shouldn't affect anything *too* much, but the behavior is indeed odd!

Historically we've seen hangs in libgit2 with a similar-ish stack trace as you gisted (I think?) so this may also be a bug in libgit2 :(

**Comment by Michael-F-Bryan** [comment]
> Cargo does tweak its behavior slightly depending on whether a tty is available or not but it's pretty buried to the point that it shouldn't affect anything too much, but the behavior is indeed odd!

I saw some code around handling ttys but looking through the code I don't think any of that logic ever gets used when you provide your own writer.

> so this may also be a bug in libgit2

I believe libgit2 tried to do the equivalent of a `git pull` then it uses `select()` to wait for each chunk of data to come in. This "deadlock" may just be a combination of spurious network failures (so the incoming data never arrives) and overly generous timeouts, meaning we seem to wait indefinitely for packets that'll never come. 

Annoyingly, I've come back to the code the morning after and I can no longer reproduce the issue, so I don't think it's actually `cargo`'s fault here. @alexcrichton feel free to close the issue if you don't think it's worth pursuing further.

**Comment by alexcrichton** [comment]
Ah ok, if you hit it again though it'd be worth looking into! This does seem like a ripe libgit2 bug report in the making at some point.
