### ISSUE TITLE
Regression in resolver performance

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5130]
Noticed at https://github.com/rust-lang/cargo/pull/5044#issuecomment-370671565 it looks like the resolver loop was tweaked in https://github.com/rust-lang/cargo/pull/5000 to unconditionally clone the `Context` before each invocation of `activate` instead of only if `has_another` is true later on, some more info at https://github.com/rust-lang/cargo/pull/5044#issuecomment-370816600.

The line in question looks to be https://github.com/rust-lang/cargo/blob/ae796ad84a742ea39a2cb4a0c8adb0def8cee725/src/cargo/core/resolver/mod.rs#L897.

@Eh2406 says they're gonna look into this, so just wanted to open a tracking issue for it!

**Comment by Eh2406** [comment]
Move to close?

**Comment by alexcrichton** [comment]
Oh yes indeed!
