### ISSUE TITLE
Provide colorised compiler messages in json output

### ISSUE THREAD

**Issue by davidhewitt** [rust-lang/cargo#5136]
E.g. [cargo-web](https://github.com/koute/cargo-web) invokes cargo build, parsing and displaying the JSON output.

While `cargo build` has lovely color output, `cargo web build` is simply plaintext, which I understand is because the JSON output by cargo doesn't contain any formatting codes.

The color and formatting in rustc is very nice for making errors easier to read and diagnose quickly; I think it'd be very nice if cargo subcommands like cargo-web were able to leverage this too somehow.

**Comment by alexcrichton** [comment]
Thanks for the report! This is sort of a rust-lang/rust issue though as Cargo's just forwarding out the json that rustc emits.

**Comment by davidhewitt** [comment]
Thanks! Closing; will open there.

**Comment by sfackler** [comment]
Color codes are a Unixism anyway - the Windows console is controlled directly.
