### ISSUE TITLE
Inconsistent behavior between arm-gnueabi and arm-gnueabihf

### ISSUE THREAD

**Issue by eberkund** [rust-lang/cargo#5140]
I have a Rust program which depends on some C libs that I have downloaded the source for and compiled with `arm-linux-gnueabi-gcc` and `arm-linux-gnueabihf-gcc` into two separate directories.

When I run `cargo build --target=arm-unknown-linux-gnueabi --verbose` everything compiles and works correctly and I can run the binary on my Raspberry Pi. However when I run `cargo build --target=arm-unknown-linux-gnueabihf --verbose` it throws an error

    note: /usr/lib/x86_64-linux-gnu/libgphoto2.so: file not recognized: File format not recognized

And I notice that the arguments `cargo` is passing to `rustc` differ by the compiler toolchain `arm-linux-gnueabihf-` vs `arm-linux-gnueabihf` (which is expected) but also by the last pair of flags. With the the hard-float version I get

    rustc ... -L native=/usr/local/lib -L native=/usr/lib/x86_64-linux-gnu

Instead of the correct path to the compiled libs for that architecture.

    -L /home/erik/Code/build/arm/lib

I change this last flag manually and run `rustc` manually I don't get an error. In my `.cargo/config` file I have `rustc-link-search` configured appropriately for each target.

**Comment by alexcrichton** [comment]
Thanks for the report! I think `arm-linux-gnueabihf-gcc` isn't a valid target (as opposed to `arm-unknown-linux-gnueabihf`, so maybe that's what's going on?

**Comment by eberkund** [comment]
Hey, thanks for the quick reply. Sorry that was a typo. I corrected my post with the actual commands I was running. Also this is my `.cargo/config` file contents for clarity:

    [target.arm-unknown-linux-gnueabi]
    linker = "arm-linux-gnueabi-gcc"
    [target.arm-unknown-linux-gnueabi.gphoto2]
    rustc-link-lib = ["gphoto2", "gphoto2_port"]
    rustc-link-search = ["/home/erik/Code/build/arm/lib"]

    [target.arm-unknown-linux-gnueabihf]
    ar = "arm-linux-gnueabihf-ar"
    linker = "arm-linux-gnueabihf-gcc"
    [target.arm-unknown-linux-gnueabihf.gphoto]
    rustc-link-lib = ["gphoto2", "gphoto2_port"]
    rustc-link-search = ["/home/erik/Code/build/armhf/lib"]

    [target.armv7-unknown-linux-gnueabihf]
    ar = "arm-linux-gnueabihf-ar"
    linker = "arm-linux-gnueabihf-gcc"
    [target.armv7-unknown-linux-gnueabihf.gphoto]
    rustc-link-lib = ["gphoto2", "gphoto2_port"]
    rustc-link-search = ["/home/erik/Code/build/armhf/lib"]

**Comment by alexcrichton** [comment]
Ah ok, can you also gist a log of `cargo build -vv` I could poke around as well?

**Comment by eberkund** [comment]
Sure

https://gist.github.com/eberkund/389c6d4ed833d00ce6df89fb5d1f2a5b

**Comment by alexcrichton** [comment]
Oh sorry forgot to mention, but can you run `cargo clean` ahead of that as well?

**Comment by alexcrichton** [comment]
@eberkund hm it looks like that gist doesn't have the same error message as before? For example the current gist doesn't mention `/usr/lib/x86_64-linux-gnu` at all

**Comment by eberkund** [comment]
There is two files in the gist, the first one labelled "arm" is the working one. The second one labelled "armhf" is the one that is not working, it has `/usr/lib/x86_64-linux-gnu` a few times throughout.

**Comment by alexcrichton** [comment]
Ah sorry I missed that! So the output contains:

```
     Running `/home/erik/Code/rust-camera-client/target/debug/build/gphoto2-sys-f69e79f789fee58d/build-script-build`
cargo:rustc-link-search=native=/usr/local/lib
cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu
```

Are you sure the `gphoto2-sys` crate is doing the right thing? It looks like that's finding the wrong linker path

**Comment by eberkund** [comment]
That's possible, but it works with `arm-unknown-linux-gnueabi` just not `arm-unknown-linux-gnueabihf` and the `build.rs` file in `gphoto2-sys` is very simple:

    extern crate pkg_config;

    fn main() {
        pkg_config::find_library("libgphoto2").unwrap();
    }

**Comment by alexcrichton** [comment]
Do you have any environment variables perchance that'd control the `pkg_config` crate?

**Comment by eberkund** [comment]
I don't think so, other than `PKG_CONFIG_ALLOW_CROSS=1` which I need otherwise I get an error telling me to use it

**Comment by alexcrichton** [comment]
I think that may be the bug? It seems like `pkg-config` isn't configured to correctly cross compile?

**Comment by eberkund** [comment]
Sorry, what do you mean? A bug where?

Isn't it normal to [need that variable set](https://github.com/alexcrichton/pkg-config-rs#external-configuration-via-target-scoped-environment-variables) to cross compile?

**Comment by alexcrichton** [comment]
The `pkg-config` utility is rarely "out of the box" ready for cross compilation, so setting the env var to cross compile typically involves *first* configuring `pkg-config` (the CLI) itself first. I haven't personally dont that much, though, I've mostly only heard of others doing it.

**Comment by eberkund** [comment]
So are you suggesting that I play around with those environment variables to get it to work?

**Comment by alexcrichton** [comment]
Yes there's presumably some pkg-config env vars that need to be configured to get it to work correctly in cross-compiled situations (although I don't know which ones)

**Comment by sfackler** [comment]
You'd typically set `PKG_CONFIG_PATH` to point to a copy of the library built for your target.

**Comment by eberkund** [comment]
I tried setting `PKG_CONFIG_PATH` to a bunch of different things but it didn't seem to make any difference. I was using `rustc-link-search` in `.cargo/config` to compile `arm-unknown-linux-gnueabi` successfully. But the approach doesn't work for `arm-unknown-linux-gnueabihf`.

**Comment by eberkund** [comment]
IMO this is an issue with Cargo because:

1) The behavior is not consistent between `arm-unknown-linux-gnueabi` and `arm-unknown-linux-gnueabihf`.
2) If I modify the resulting `rustc` command produced by `cargo` I don't get errors.

```
cargo build --target=arm-unknown-linux-gnueabihf
```

results in this. (It seems to completely ignore what I have in `.cargo/config`)
```
rustc ... -L native=/usr/local/lib -L native=/usr/lib/x86_64-linux-gnu
``` 
compared to, 
```
cargo build --target=arm-unknown-linux-gnueabi
```
results in
```
rustc ... -L /home/erik/Code/build/arm/lib
```
where `/home/erik/Code/build/arm/lib` is defined in my project `.cargo/config` file with `rustc-link-search`. **This is the expected behavior**

**Comment by alexcrichton** [comment]
@eberkund the `/usr/lib/x86_64-linux-gnu` argument isn't injected by Cargo, it's sort of equivalent to shooting the messenger. Cargo's transporting that argument from a build script to the linker, but Cargo's not why it's there.

**Comment by eberkund** [comment]
Ah okay, yeah I just made a fresh hello world project to check and it works as expected. So I referred to [these docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) and searched my `target/arm-unknown-linux-gnueabihf/debug/build` directory and found:

```
➤ rg '/usr/lib/x86_64-linux-gnu' .
gphoto2-sys-8a360ca8035e79e2/output
2:cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu
```

Then I referred to the build script from the package that is producing that, `gphoto2-sys`
```
extern crate pkg_config;

fn main() {
  pkg_config::find_library("libgphoto2").unwrap();
}
```
I followed that to the [here](https://github.com/alexcrichton/pkg-config-rs/blob/5203aff8b20479c9df159be2efb4162450019330/src/lib.rs#L406) and I am still not sure what is happening, maybe the environment variables are not getting picked up and it's printing out `/usr/lib/x86_64-linux-gnu` as a default or something?

**Comment by alexcrichton** [comment]
Sorry I'm not entirely sure, I haven't done much cross-compiling with pkg-config :(. @sfackler indicates that `PKG_CONFIG_PATH` may help.

FWIW in the meantime I'm going to close this as I don't think there's a bug in Cargo, here, but you can of course continue to post questions!

**Comment by eberkund** [comment]
Okay well thank you for all of the help so far.

I will keep trying.

**Comment by eberkund** [comment]
I think I figured out what was going wrong.

Putting this in `.cargo/config` _doesn't_ work

```
[target.arm-unknown-linux-gnueabihf]
ar = "arm-linux-gnueabihf-ar"
linker = "arm-linux-gnueabihf-gcc"
[target.arm-unknown-linux-gnueabihf.gphoto]
rustc-link-lib = ["gphoto2", "gphoto2_port"]
rustc-link-search = ["/home/erik/Code/build/armhf/lib"]
```

But putting this in my `build.rs` _does_ work
```
println!("cargo:rustc-link-search=/home/erik/Code/build/armhf/lib");
```

I think the problem is that the later is "project level" while the former only applies to "gphoto" so the couple of other dependencies I had were not found.

Is there away to write the equivalent in my `.cargo/config`?

**Comment by alexcrichton** [comment]
The .cargo/config configuration will only be read if the crate says `links = "gphoto"`, so to confirm, the crate says that right?
