### ISSUE TITLE
Build Scripts: Get directory `cargo build` was executed in

### ISSUE THREAD

**Issue by oberien** [rust-lang/cargo#5143]
I have a path-dependency to a library which has a build script. That build script reads a path from an environment variable and reads files from there. The current directory of that build script is set to its project folder from cargo. This means that I can't specify relative paths in that environment variable, because those are invalidated in the build scripts.

Is there a way for me (the build script) to find out in which directory `cargo build` was invoked, so that I can use that directory to resolve relative paths passed in an environment variable? If not, would it be possible to add a new environment variable for that use case?

**Comment by alexcrichton** [comment]
Currently this cannot be found out as it can otherwise lead to surprising rebuilds (as it factors into determinisim), but this can be communicated manually and excluded from caches manually if desired.
