### ISSUE TITLE
Can't both generate workspace documentation and open it

### ISSUE THREAD

**Issue by loganmzz** [rust-lang/cargo#5145]
# Description

Running `cargo doc --all --open` results in ``error: Passing multiple packages and `open` is not supported``

# Workaround

```bash
cargo clean
cargo doc --all
cargo doc --open # Refresh root crate but leave existing one
```

**Comment by dwijnand** [comment]
To me it looks like the workaround no longer works:

```
$ cargo doc --open
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
error: Passing multiple packages and `open` is not supported.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  adder
  add-one
```

(using the example workspace from https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html)
