### ISSUE TITLE
Allow cargo-check to run without waiting for the lock file

### ISSUE THREAD

**Issue by avkonst** [rust-lang/cargo#5148]
I am using IDE (Intelij in my case, but this specific is not important), which runs in-flight check via `cargo check` and highlights errors and warnings in-line in the editor. I also use `cargo watch -x run` in separate terminal window to recompile and launch my rust HTTP server-binary application continuously. These 2 are complimentary to each other. However, both are waiting on the same lock file. Tacking into account slow build time, feedback loop is significantly delayed.

I understand, the lock file has got it's reasons for concurrent build tasks, writing to the same target folder. However, `cargo check` is 'read-only' step, which does not touch binaries (should be as far as I imagine it). I propose to enable `cargo check` (or maybe all read-only ops) to run without waiting for the lock file. Would it be a big deal to achieve it?

**Comment by sfackler** [comment]
cargo check still emits files from rustc, they're just metadata-only.

**Comment by alexcrichton** [comment]
Ah yeah unfortunately both of these steps are still writing artifacts into the build directory so they need to be synchronized. @avkonst can your setup be configured for two different target directories perhaps?

**Comment by avkonst** [comment]
@alexcrichton could you please clarify how I configure the `cargo run` via command line arguments to use different (non-default) target directory? Note: I can not configure `cargo check`, because it is out of my control (invoked by IDE and uses default target as far as I understand).

**Comment by alexcrichton** [comment]
@avkonst oh the `CARGO_TARGET_DIR` env var should do the trick

**Comment by avkonst** [comment]
@alexcrichton great! thank you

**Comment by alexcrichton** [comment]
Ok! In that case I'll close this, but feel free to comment if it's still not working!

**Comment by avkonst** [comment]
value of CARGO_TARGET_DIR should be added to .gitignore, otherwise cargo watch does not work properly.

**Comment by Boscop** [comment]
Is it possible to set cargo's `check` dir to something else and keep `target` as the dir for `build`?

**Comment by avkonst** [comment]
Yes. It is possible. Set this environment variable before launching your editor. In this case cargo check invoked by ide will use the configured dir.
