### ISSUE TITLE
Have --dep-info generate gn-compatible dependency files

### ISSUE THREAD

**Issue by rtsuk** [rust-lang/cargo#5162]
In https://github.com/rust-lang/cargo/pull/3557 @raphlinus added dependency file generation to rustc. This issue is about modifying that generation so that it produces gn-compatible dependency files.

[gn](https://chromium.googlesource.com/chromium/src/+/master/tools/gn/README.md) requires, in [dependency files that it is asked to consume](https://chromium.googlesource.com/chromium/src/+/master/tools/gn/docs/reference.md#depfile), that "all paths must be relative to the root build directory." Empirically it appears that this is actually only required of the target paths.

This issue is mostly implemented already, as the [code to generate the dependency](https://github.com/rust-lang/cargo/blob/4429f4efa12dc62985d971fa3ea16e50f541e35a/src/cargo/ops/cargo_rustc/output_depinfo.rs#L73) file already has an option to make target paths relative. I tested it by hard-coding a value and it makes dependency files that gn is happy to consume. So all that's required is to provide some way to pass this value to [output_depinfo()](https://github.com/rust-lang/cargo/blob/4429f4efa12dc62985d971fa3ea16e50f541e35a/src/cargo/ops/cargo_rustc/output_depinfo.rs#L69).

What would be the most correct way to pass such information? Something in cargo config seems easiest.

**Comment by alexcrichton** [comment]
Sounds like a fine idea! I'd be down for something like:

```toml
[build]
dep-info-format = 'gn'
```

or something like that

**Comment by rtsuk** [comment]
Great! I'll get started on this.
