### ISSUE TITLE
cargo test --doc hangs in endless loop

### ISSUE THREAD

**Issue by Weltraumschaf** [rust-lang/cargo#5163]
In this project https://github.com/Weltraumschaf/webserver/ (current commit ff952c66a6443a76d1c3d9204a11c718120a0f0e) the command `cargo test` and also `cargo test --doc` runs into an endless loop without further error:

```bash
cargo test --doc
warning: unused manifest key: package.travis-ci
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Doc-tests webserver

running 1 test
test src/server.rs - server (line 7) has been running for over 60 seconds
```

Of course I've done something wrong with the documentation, but I thik it would be nicer to report an error instead of looping for ever.

My environment:

* macOS 10.12.6 (16G1212)
* rust: stable-x86_64-apple-darwin
  * rustup: 1.11.0
  * rust: 1.24.1 (d3ae9a9e0 2018-02-27)
  * cargo: cargo 0.25.0 (96d8071da 2018-02-26)

**Comment by sfackler** [comment]
How long do you expect this test to take to run? https://github.com/Weltraumschaf/webserver/blob/master/src/server.rs#L8-L25

**Comment by Weltraumschaf** [comment]
I expect it not to run that code. I expected the test tool only compiles/verifies it. But okay, I see the problem: The tool is executing that code, too. 

Then my question is: How do I add example code like that in the documentation without running forever in doc-tests?

**Comment by steveklabnik** [comment]
Turn https://github.com/Weltraumschaf/webserver/blob/master/src/server.rs#L7 into

    ```no_run

And it should work

**Comment by alexcrichton** [comment]
Indeed I think @steveklabnik's suggestion should work here, so closing
