### ISSUE TITLE
is `git clone --recursive` still needed?

### ISSUE THREAD

**Issue by xftroxgpx** [rust-lang/cargo#5165]
The [README.md](https://github.com/rust-lang/cargo/blob/master/README.md) mentions:

> First, you'll want to check out this repository
> ```
> git clone --recursive https://github.com/rust-lang/cargo
> cd cargo
> ```

But cargo doesn't seem to have any submodules anymore.
If this is true, then can `--recursive` be removed?

**Comment by alexcrichton** [comment]
Ah nah this is outdated and should be fine to remove now!
