### ISSUE TITLE
`cargo -Vv` commit-hash: and commit-date:  are missing when building locally as per README

### ISSUE THREAD

**Issue by xftroxgpx** [rust-lang/cargo#5166]
(**I tried this:**)
If following the [readme](https://github.com/rust-lang/cargo/blob/ddffe6063c6ea89710f21d2ac46afa468a563511/README.md#compiling-from-source) steps for building cargo:
> With cargo already installed, you can simply run:
> `cargo build --release`

(**this happened:**)
then the built cargo version shows:
```bash
$ ./target/release/cargo -V
cargo 1.26.0

$ ./target/release/cargo -Vv
cargo 1.26.0
release: 1.26.0
```

(**I expected to see this happen:**)
instead of the expected:
```bash
$ ./target/release/cargo -V
cargo 1.26.0-dev (414cbdfc 2018-03-11)

$ ./target/release/cargo -Vv
cargo 1.26.0-dev (414cbdfc 2018-03-11)
release: 1.26.0
commit-hash: 414cbdfc2b86f622e977a26f80f54d5dc286e9a7
commit-date: 2018-03-11
```

which actually requires these steps to build instead:
```bash
export CFG_RELEASE_CHANNEL=dev
export CFG_COMMIT_HASH="`git rev-parse HEAD`"
export CFG_SHORT_COMMIT_HASH="`git rev-parse --short HEAD`"
export CFG_COMMIT_DATE="`git log -1 --date=short --pretty=format:'%cd'`"
cargo build --release
```

Cargo commit 50a46f47086c01effe195ad6a1566f7cf9084fb5 removed the setting of those environment variables likely because it's expected that cargo is only being built when building the Rust compiler (?  or something): https://github.com/rust-lang/rust/blob/5f2efb09358c1c43ff0f8be11c00948478777e23/src/bootstrap/tool.rs#L169-L177 (thanks to `ehuss` on #cargo IRC for this url)

Relevant cargo code dealing with `commit-hash` and `commit-date`:
https://github.com/rust-lang/cargo/blob/414cbdfc2b86f622e977a26f80f54d5dc286e9a7/src/cargo/lib.rs#L221-L231

**Comment by alexcrichton** [comment]
Yeah when compiling locally some env vars need configuration (this is done in the rust-lang/rust repo), but maybe we should update the README?

**Comment by xftroxgpx** [comment]
> but maybe we should update the README?

Maybe, I am unsure.
Would it replace `cargo build --release` with:
```
export CFG_RELEASE_CHANNEL=dev
export CFG_COMMIT_HASH="`git rev-parse HEAD`"
export CFG_SHORT_COMMIT_HASH="`git rev-parse --short HEAD`"
export CFG_COMMIT_DATE="`git log -1 --date=short --pretty=format:'%cd'`"
cargo build --release
```
?

Or, shouldn't cargo populate those itself? IF not already set.

Because [`Compiling from Source`](https://github.com/rust-lang/cargo#compiling-from-source) seems to imply an independence from the [rust-lang/rust](https://github.com/rust-lang/rust) repo; unless the readme should be updated to reflect such a dependency?

**Comment by alexcrichton** [comment]
I wouldn't recommend documenting those in Cargo's README itself personally (Cargo should just continue to gracefull handle their absence)
