### ISSUE TITLE
Add option to "cargo metadata" that avoids network and filesystem changes, and ignores errors due to missing crates

### ISSUE THREAD

**Issue by xzn** [rust-lang/cargo#5174]
Motivation is from this [racer issue](https://github.com/racer-rust/racer/issues/513).

Currently racer doesn't deal with replaced/patched crates and crates-io mirror correctly, it also doesn't resolve to the correct version of a crate when looking for crate source. It was suggested in comments to use "cargo metadata" which would fix all of this however this currently makes network request to update the index and crate source which seems undesirable.

How difficulty would it be to add something similar to "--frozen," but additionally avoids touching the filesystem and ignores errors due to missing crates?

**Comment by Eh2406** [comment]
Dose `-Z offline` https://github.com/rust-lang/cargo/pull/4770 help with your issues ?

**Comment by dwijnand** [comment]
Optimistically close, given the presence of the offline flag (that we hope to stabilise soon)?

**Comment by alexcrichton** [comment]
Sure!
