### ISSUE TITLE
cargo gets tuck at `Resolving dependency graph...` under some conditions

### ISSUE THREAD

**Issue by fabricedesre** [rust-lang/cargo#5182]
In my case that happens when adding the "actix" crate to an existing projects that is a Servo embedder (so it's not that easy to update some deps).

Here's the current `Cargo.lock`, and the updated `Cargo.toml`. The only change is the additional `actix` dependency.

[Cargo_files.zip](https://github.com/rust-lang/cargo/files/1813295/Cargo_files.zip)

**Comment by fabricedesre** [comment]
cc @alexcrichton who knows the context we discussed on irc.

**Comment by Eh2406** [comment]
Thank you so much for the bug report! I am doing a lot of work on this kind of problem. I have added it to my list of things to try and solve. Anything you or @alexcrichton can add on the context and how to reproduce would be appreciated.

**Comment by fabricedesre** [comment]
These are the Cargo files from https://github.com/fabricedesre/servonk

To reproduce, uncomment `actix` in the Cargo.toml and run `cargo fetch`.

**Comment by Eh2406** [comment]
testing with master I get
```cmd
>MyProjects\cargo\target\debug\cargo fetch -Z no-index-update
error: failed to select a version for `serde_json`.
    ... required by package `skeptic v0.13.0`
    ... which is depended on by `actix v0.3.4`
    ... which is depended on by `actix_derive v0.1.0`
    ... which is depended on by `actix v0.4.2`
    ... which is depended on by `servonk v0.1.0 (file:///C:/Users/.../issues5182)`
versions that meet the requirements `^1.0.3` are: 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3

all possible versions conflict with previously selected packages.

  previously selected package `serde_json v1.0.2`
    ... which is depended on by `script v0.0.1 (https://github.com/fabricedesre/servo?branch=gonk#063e5f3e)`
    ... which is depended on by `layout_thread v0.0.1 (https://github.com/fabricedesre/servo?branch=gonk#063e5f3e)`
    ... which is depended on by `libservo v0.0.1 (https://github.com/fabricedesre/servo?branch=gonk#063e5f3e)`
    ... which is depended on by `servonk v0.1.0 (file:///C:/Users/.../issues5182)`

failed to select a version for `serde_json` which could resolve this conflict
```
Looks like some of the recent changes stop the hang!

**Comment by fabricedesre** [comment]
Indeed! I managed to update everything with a few back and forth... ie, removing actix, doing the serde_json update, and adding it back. Not ideal, but that will do for now :)
