### ISSUE TITLE
Unable to update dependencies under my company proxy: 404 error while URL seems valid

### ISSUE THREAD

**Issue by pjturpeau** [rust-lang/cargo#5189]
Hi

I got a 404 error when Cargo tries to download a crate dependency. It succeeds in updating the index however.

System: Windows 7 (sic!) where I can only install portable apps only in one specific directory
Rust: rust-1.24.1-i686-pc-windows-gnu
Cargo: cargo 0.25.0 (96d8071da 2018-02-26)

Here is the output:

```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading num_cpus v1.8.0
error: unable to get packages from source

Caused by:
  failed to get 200 response from `https://mycompanyincredibleproxy/wxyz/?poui=aHsdmSDSs4s5dss65s4DS8ZSds65sd6s54qdqSZDf3254F4367GG68duDZzEDSJLjSDSDDSbG9hZA==`, got 404
```

When I copy/paste the url `https://mycompanyincredibleproxy/wxyz/?poui=aHsdmSDSs4s5dss65s4DS8ZSds65sd6s54qdqSZDf3254F4367GG68duDZzEDSJLjSDSDDSbG9hZA==` in my browser, it downloads the crate.

So my only solution currently is to copy/paste the URL in the browser, then move the downloaded crate to the cache directory of cargo (I'm using the portable version).

My cargo configuration is:
```
[http]
proxy = "http://user:password@companyproxy:8080"
check-revoke = false
sslVerify = false

[https]
proxy = "https://user:password@companyproxy:8080"
check-revoke = false
sslVerify = false
```

Could this be a Cargo bug due to the strangely formatted URL ? Or could this be a wrong proxy configuration ? What can I check or try to understand a little bit more ? I might try any curl command if this help.

Thank you,
Kind regards.

**Comment by lukaslueg** [comment]
Your company-proxy may be blocking the User-Agent used by Cargo?! Did you check if you can use http(s) by any other means than browsers?

**Comment by pjturpeau** [comment]
git is working well through that proxy.

**Comment by alexcrichton** [comment]
@pjturpeau in theory it's just a plain HTTP request without many bells and/or whistles attached, we use very few headers in Cargo beyond the user-agent. If you use `curl` on the command line does it work?

**Comment by pjturpeau** [comment]
It gives me:

```
$ curl "https://crates.io/api/v1/crates/num_cpus/1.8.0/download?bcsi-ac-f36447ef44bbdc17=2834BE16000006032lBaSDPVCh+u1ukGJ1qK90USEJqTGgAAAwYAAAy6jgEIBwAACAAAAAI/bAA=" --output num_cpus.crate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /mingw64/ssl/certs/ca-bundle.crt
  CApath: none
```

I downloaded the cacert.pem from `https://curl.haxx.se/docs/caextract.html` but it didn't help.

**Comment by alexcrichton** [comment]
Ah I remember seeing that a long time ago but I forget how to fix it :(. It may have been a `curl` vs `mingw-w64-x86_64-curl` package difference maybe?
