### ISSUE TITLE
error: no matching package named `crc` found

### ISSUE THREAD

**Issue by zhangqunshi** [rust-lang/cargo#5191]
My Cargo.toml is

```
[package]
name = "suricata"
version = "4.1.0-dev"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = true

[features]
lua = []
experimental = ["ntp-parser"]
strict = []
debug = []

[dependencies]
nom = "~3.2.1"
libc = "^0.2.36"
crc = "~1.7.0"

ntp-parser = { version = "^0", optional = true }

```

and after run cargo build, i got:

```
error: no matching package named `crc` found (required by `suricata`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ~1.7.0
```

I am new to rust, so can anybody help me?

Thanks a lot,
Kris

**Comment by alexcrichton** [comment]
Thanks for the report! This works locally for me (suspicious!) so I wonder, do you have a proxy and/or cargo configuration (something in `.cargo/config` somewhere) for a source replacement or otherwise configuration of the registry?

**Comment by zhangqunshi** [comment]
Thanks alexcrichton, it's a network issue, it's very slow to download the index from github in China, so I updated the `.cargo/config` and use a mirror site, now it's work.

Thanks again,
Kris

**Comment by thufuxu** [comment]
@zhangqunshi  can you give more details how this be solved?

**Comment by JanYunkai** [comment]
how this be solved? 
git://mirrors.ustc.edu.cn/crates.io-index
