### ISSUE TITLE
build files from before `rustup update` are not deleted.

### ISSUE THREAD

**Issue by rukai** [rust-lang/cargo#5194]
Dont know if this is a rust or cargo issue, it also sounds like something that would have an issue already  but couldnt find it so here goes.

There seems to be build files that do not get deleted when I compile with a newer version of rust.
This led to a 20GB target/ folder.
After deleting the target/ folder and rebuilding, the target/ folder is now 1.7GB (incremental compilation, both release and debug)

**Comment by Mark-Simulacrum** [comment]
Cc @michaelwoerister

**Comment by alexcrichton** [comment]
Yes Cargo does not currently clean up old compilers (but rather it's a feature that it caches artifacts for multiple compilers), so cleaning these out with frequently updating nightlies is an end-user responsibility currently.

**Comment by ehuss** [comment]
See also #5026.

**Comment by dwijnand** [comment]
Looks to me as..

Duplicate of #5026
