### ISSUE TITLE
Build thin binary with one fat dynamic dependency

### ISSUE THREAD

**Issue by axos88** [rust-lang/cargo#5198]
Somewhat related: https://github.com/rust-lang/cargo/issues/4538.

Disclaimer: super newbie to rust.

My workflow when developing to raspberry targets with scala - yes, the result was super-slow startups on the Zero W, one of the reasons i'm exploring rust now - was to create a fat dependency library and a thin binary dynamically loading that.

This way when I was compiling my code in most cases I only needed to rsync over a small binary, since the dependency list changed rarely, and the copy was super-fast this way.

I would love to see this possible with cargo as well. 
Create a PROJECT-deps.so and a PROJECT binary dynamically loading that.

The concerns for an unstable ABI are understandable, but do not apply in this use-case, since the dep library and the binary are guaranteed to be generated by the same compiler. If the compiler is changed, and the ABI updated, the dependency library's checksum would mismatch, and get copied over as well.

**Comment by matklad** [comment]
Am I correct that you would like to compile all of the dependencies as a single dynamic library? I am afraid that this, in general, is not possible in Rust. 

Unlike Scala, rust uses monomorphisation to compile generics. That means that code for generic functions in the libraries is actually compiled to machine code only when the final artifact is built, when all generic substitutions are known. 

If you are concerned with the sizes of rust binaries, there are various ways to make them smalller: 
https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html, the most important of which, for linux, is to strip the binary form stdlib debuginfo.

**Comment by axos88** [comment]
Ah yes... monomorphisation seems to be a real issue... 
How does this work with C++? It definately *seems* possible there, with dynamically loaded libraries and such, or am I wrong?

**Comment by matklad** [comment]
You can create dynamic libraries in Rust or C++, but you need to make sure that the interface is actually not generic. So, specifically crafted dynamic libraries are possible, but automatic creation of fat library of all dependencies will not work.

For creating a shared library with a C-abi, you might want to look at https://github.com/eqrion/cbindgen

I don’t know of great examples of shared libraries with Rust ABI: this use case does not seemed to be explored really well at the moment.

**Comment by axos88** [comment]
Ah, so it's not possible to create a dynamic rust library with a generic public api? That's a pretty huge caveat, and I haven't seen that mentioned in The Book - although I am not finished reading yet.

**Comment by axos88** [comment]
Btw, thanks for that article, stripping the binary reduced size from 25MB to about 3MB...

**Comment by sfackler** [comment]
That's about the size I'd expect for debuginfo and a symbol table.

**Comment by axos88** [comment]
Any reason why this is not the default behaviour for release targets?

**Comment by sfackler** [comment]
Debuginfo isn't on by default for release targets. C compilers don't strip by default either.

**Comment by axos88** [comment]
"The neighbour doesn't do it either" isn't really a very good reason... AFAIK In C it's possible to hack around with pointers that can brake a stripped binary, but that should not be possible with rust, is it?

My question was wether there would be any genuine issues / behabiour changes caused by stripping all release binaries by default?

**Comment by matklad** [comment]
@axos88 @sfackler let's close this issue then, because the discussion somewhat derailed :) 

I've moved it over here: https://users.rust-lang.org/t/rust-binary-sizes-once-again/16287
