### ISSUE TITLE
crate-type has no effect in [[bin]] sections

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#5199]
As per the documentation, one can set `crate-type` in a `[[example]]` section, leading to the example being built as the given crate type(s). It's also possible to set `crate-type` in the `[lib]` section, and the type is used correctly.

It's also possible to set `crate-type` in a `[[bin]]` section, and cargo doesn't complain about it like it does for unknown keywords. It even does input validation, and complains if the type is not right. However, when actually building the corresponding source, it still invokes rustc with `--crate-type bin`.

Either `crate-type` should be rejected there, or it should do the expected thing. In any case, silently ignoring the value is not something anyone would expect. I'd personally prefer the latter.

Cc: @alexcrichton

**Comment by lukaslueg** [comment]
We can reject that in `targets::clean_bins()`, which will give a parse error referring to the manifest, which is nice imho.

While at it: Do we also want to reject `proc-macro` being set as well?
