### ISSUE TITLE
nightly 2018/03/19: change of position of arguments passed to cargo subcommands

### ISSUE THREAD

**Issue by PaulGrandperrin** [rust-lang/cargo#5208]
Hello,
This nightly just broke my crate:
https://travis-ci.org/rust-fuzz/honggfuzz-rs/builds

It looks like it there has been a change in how `cargo` passes arguments to subcommands.

I guess we have a typical case of:
[![xkcd](https://imgs.xkcd.com/comics/workflow.png)](https://xkcd.com/1172/)

Here is the piece of code that worked before and now doesn't: https://github.com/rust-fuzz/honggfuzz-rs/blob/master/src/bin/cargo-hfuzz.rs#L169-L171
```rust
    let mut args = env::args().skip(1);
    if args.next() != Some("hfuzz".to_string()) {
        eprintln!("please launch as a cargo subcommand: \"cargo hfuzz ...\"");
        process::exit(1);
    }
```

Just to be clear, this is absolutely no big deal for me and I don't care adapting my code. I just want to be sure, the change in behavior is known.

**Comment by alexcrichton** [comment]
cc @matklad

**Comment by matklad** [comment]
@PaulGrandperrin if you've already investigated it, could you tell how the `args` looks on stable and on nightly?

**Comment by matklad** [comment]
Figured it out myself:

Before

```
["/home/matklad/.cargo/bin/cargo-hfuzz", "hfuzz", "clean"]
```

After

```
["/home/matklad/.cargo/bin/cargo-hfuzz", "clean"]
```

I can't believe we don't have a test for it...

**Comment by PaulGrandperrin** [comment]
Arg, you were fast!
Yes, that's why I felt it would be sensible to report it :-)

**Comment by matklad** [comment]
@PaulGrandperrin thank you so much for the report! We've recently switched from docopt to clap, so I've expected regressions for some obscure corner cases, but this one is as far from the spacebar heater as it gets...

**Comment by PaulGrandperrin** [comment]
Glad it helped!
And it's always fun to be able to mention XKCD strips in bug reports 😉
Thanks for your work!

**Comment by azriel91** [comment]
Hiya! I know the title says `nightly 2018/03/19`, but I'm wondering if this is the same issue that's causing this to happen on `1.26.0-nightly (d6c3983fe 2018-03-16)`:

```
$ cargo audit
thread 'main' panicked at 'cargo-audit is intended to be invoked as a cargo subcommand', src/main.rs:53:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ cargo audit audit
    Fetching advisories `https://raw.githubusercontent.com/RustSec/advisory-db/master/Advisories.toml`
    Scanning 238 crates for vulnerabilities (5 advisories in database)
     Success No vulnerable packages found

$ cargo --version --verbose
cargo 1.26.0-nightly (d6c3983fe 2018-03-16)
release: 1.26.0
commit-hash: d6c3983fe3bd8fa06b54712e53fb23645598188b
commit-date: 2018-03-16
```

If it's different I can raise another issue, but the test code looks like it's this one.

**Comment by matklad** [comment]
@azriel91 yep, this looks like the same issue! Hopefully the Cargo fix will to the nightlies soon
