### ISSUE TITLE
Rename "epoch" to "edition"

### ISSUE THREAD

**Issue by klnusbaum** [rust-lang/cargo#5214]
In rust repo, we've started [renaming all the references of "epoch" to "edition"](https://github.com/rust-lang/rust/issues/49001). At the request of @Manishearth, let's make any needed parallel changes here in the cargo project.

**Comment by Manishearth** [comment]
(@klnusbaum  is working on this)

**Comment by klnusbaum** [comment]
I've got a PR ready for this. Just waiting for https://github.com/rust-lang/rust/pull/49035 to land in the nightly

**Comment by Manishearth** [comment]
Any progress?

**Comment by klnusbaum** [comment]
I was actually just working on this.

Just put up a PR :)

**Comment by matklad** [comment]
I believe this is fixed by #5274! :tada:
