### ISSUE TITLE
Cargo check does not respect the --release flag

### ISSUE THREAD

**Issue by ben01189998819991197253** [rust-lang/cargo#5218]
Running `cargo check --release` is functionally equivalent to `cargo check`.

Minimal test case:

```rust
// src/main.rs

// Warn about unused stuff when in debug mode, fail compilation in release
#![cfg_attr(debug_assertions, warn(unused))]
#![cfg_attr(not(debug_assertions), deny(unused))]

fn main() {
    let unused = 0;
}
```

Results:

| Command | Expected Result | Actual Result |
| ------------- |-------------| -----|
| `cargo build` | warnings | warnings |
| `cargo build --release` | failure | failure |
| `cargo check` | warnings | warnings |
| `cargo check --release` | failure | **warnings** |

Reproduced on `cargo 0.25.0 (96d8071da 2018-02-26)` and `cargo 1.26.0-nightly (d6c3983fe 2018-03-16)`.

----

I did a bit of digging, and I think I know why this is happening:

When running `cargo check --release`, the `debug_assertions` variable is still set to `true` instead of `false`, but when running `cargo build --release`, that flag is properly left disabled.

`debug_assertions` is defined within the `Profile` struct (`manifest.rs`), and an instance of `Profile` is retrieved during compilation:

https://github.com/rust-lang/cargo/blob/b0a225206352c3930f62c3674243d99fc8b15b07/src/cargo/ops/cargo_compile.rs#L679-L697

As you can see above, when finding the correct `Profile` we essentially just get the default `Profile` instance defined for each action (assuming we're using a default `Workspace` struct, which most people are) - with the notable exception of `CompileMode::Build`: for that mode, we either return a `Profile` made for release-mode or the default `Profile` that has `debug_assertions` enabled. We **don't** do this for `CompileMode::Check`. So, assuming we just retrieve the default `Profile`...

The default profiles are defined as such:

https://github.com/rust-lang/cargo/blob/b0a225206352c3930f62c3674243d99fc8b15b07/src/cargo/core/workspace.rs#L647-L659

Things to note: the release `Profile` actually just corresponds to `cargo build --release`; there isn't a definition for a `check_release` field. The function definitions are here:

https://github.com/rust-lang/cargo/blob/b0a225206352c3930f62c3674243d99fc8b15b07/src/cargo/core/manifest.rs#L708-L799

And as you can see, the default `Profile` for `CompileMode::Check` is equivalent to the default development `Profile`, with `debug_assertions` enabled. There is no `Profile` for `CompileMode::Check` that is also for release mode.

**Comment by ben01189998819991197253** [comment]
I think there are a couple of ways to fix this:

The easy, but not as clean way, would be to define another `Profile` for `CompileMode::Check` that also has the correct flags enabled for release, something like:

```rust
pub fn default_check_release() -> Profile {
    Profile {
        check: true,
        ..Profile::default_release(),
    }
}
```

The other way would be to use something like the Builder Pattern to construct `Profiles`, doing something like:

```rust
let default_profiles: Profiles {
    // ...
    check_release: Profile::default()::with_check()::with_release(),
    check_test_release: Profile::default()::with_check()::with_test()::with_release(),
    // ...
}
```

**Comment by ben01189998819991197253** [comment]
@alexcrichton Sure thing!

Even though it's a bit more work, I'll try to refactor the `Profile` struct to work with the Builder Pattern - it'll make it easier to add new default profiles and also make it more clear what options are set for each default profile.

**Comment by alexcrichton** [comment]
Sounds great!
