### ISSUE TITLE
install crashes when given empty argument: ""

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#5229]
I was trying to do stuff with cargo via a script and it turned out that cargo can crashes when encountering "" as an arg:

````
RUST_BACKTRACE=1 cargo install ""

    Updating registry `https://github.com/rust-lang/crates.io-index`
thread 'main' panicked at 'byte index 2 is out of bounds of ``', libcore/str/mod.rs:2209:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::str::slice_error_fail
             at libcore/str/mod.rs:0
   9: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
  10: cargo::sources::registry::index::RegistryIndex::summaries
  11: cargo::sources::registry::index::RegistryIndex::query
  12: <cargo::sources::registry::RegistrySource<'cfg> as cargo::core::registry::Registry>::query
  13: cargo::core::registry::Registry::query_vec
  14: cargo::ops::cargo_install::install_one
  15: cargo::ops::cargo_install::install
  16: cargo::commands::install::exec
  17: cargo::cli::execute_subcommand
  18: cargo::cli::main
  19: cargo::main
  20: std::rt::lang_start::{{closure}}
  21: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  22: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  23: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  24: main
  25: __libc_start_main
  26: <unknown>
````
````
cargo 1.26.0-nightly (d6c3983fe 2018-03-16)
release: 1.26.0
commit-hash: d6c3983fe3bd8fa06b54712e53fb23645598188b
commit-date: 2018-03-16
````

latest git version also crashes.

**Comment by lukaslueg** [comment]
Ah, the posix shell strikes again. The empty string is passed and the whole argument therefore not `None`. It crashes [here](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/registry/index.rs#L93-L98) when it tries to load the metadata and `fs_name.len()` is actually 0. The band-aid measure would be to just return an error from `load_summaries()` if the name of the package is zero-sized. Or does one need to go down into clap-world and make sure that empty arguments are treated the same way as non-existent arguments? I'd chose the first.

**Comment by matklad** [comment]
@lukaslueg I believe your analysis is correct! I don't feel that we should fix `load_summaries`: I think the code assumes that the `name` is valid. So, I would rather fix this on the clap side, and add an assertion at the place where the name is introduced, that it is not empty. 

So, the fix for this would involve I think:

* Assertion about empty name [here](https://github.com/rust-lang/cargo/blob/c157d7dd7a9f5b93b08f3335c29a883990c7fd75/src/cargo/core/dependency.rs#L188) (it wold be nice to check that it actually fires for empty argument)
* Some clap option [here](https://github.com/rust-lang/cargo/blob/master/src/bin/commands/install.rs#L10) to forbid empty values
* a test :)
