### ISSUE TITLE
Examples cannot have separate sets of dependencies

### ISSUE THREAD

**Issue by brendanzab** [rust-lang/cargo#523]
gfx-rs has [examples](https://github.com/gfx-rs/gfx-rs/tree/f5d1a138ec91234913378952a0d6ad2bd6df2050/examples) which have different dependency requirements. It would be great not to have to litter the Cargo.toml with them.

At the moment we have a [Makefile](https://github.com/gfx-rs/gfx-rs/blob/f5d1a138ec91234913378952a0d6ad2bd6df2050/examples/Makefile) to build them, but it results in a [huge amount of recompilation](https://travis-ci.org/gfx-rs/gfx-rs/builds/34560959#L351-L521).

This could be also useful for external API tests and benchmarks that need to test themselves against different libraries.

**Comment by ModProg** [comment]
maybe the proposed syntax for cargo-script could be used for something like this as well:  https://github.com/rust-lang/cargo/issues/12207, https://github.com/rust-lang/rfcs/pull/3424

//! ```cargo
//! [dependencies]
//! clap = { version = "4.2", features = ["derive"] }
//! ```
