### ISSUE TITLE
cargo build & run don't create a fresh build in WSL

### ISSUE THREAD

**Issue by TheDan64** [rust-lang/cargo#5240]
I decided to give Windows Subsystem for Linux (w/ Ubuntu) a shot and after installing rust via rustup I have this strange issue:

`cargo build` and `cargo run` will create a binary once, but subsequent code changes will not be detected by `build` and `run` (they immediately finish and `run` uses the old binary). A workaround is to delete the binary from the `target` directory, which will cause a fresh one to be built.

`cargo check` does cause a fresh compilation every time, however using `check` does not assist `build` and `run` in generating a new binary (the problem persists).

Happy to provide additional details upon request

cargo --version: `cargo 0.25.0 (96d8071da 2018-02-26)`
uname -a: `Linux DESKTOP-E7Q7M5A 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by TheDan64** [comment]
I believe it's `lxfs`? This is what `df -Th` gives me:
```Filesystem     Type   Size  Used Avail Use% Mounted on
rootfs         lxfs   465G  107G  358G  23% /
none           tmpfs  465G  107G  358G  23% /dev
none           tmpfs  465G  107G  358G  23% /run
none           tmpfs  465G  107G  358G  23% /run/lock
none           tmpfs  465G  107G  358G  23% /run/shm
none           tmpfs  465G  107G  358G  23% /run/user
C:             drvfs  465G  107G  358G  23% /mnt/c
D:             drvfs  1.9T  985G  879G  53% /mnt/d
```

**Comment by TheDan64** [comment]
Though oddly enough `cat /etc/fstab` suggests ext4: `LABEL=cloudimg-rootfs   /        ext4   defaults        0 0`

**Comment by alexcrichton** [comment]
How odd :(

Unfortunately I'm away from my Windows computer right now but I'll try again next and see if I can reproduce this locally

**Comment by TheDan64** [comment]
Sounds good, thanks!

Could you maybe point me to where cargo checks timestamps or any other areas you might suspect? If I find some free time I can try and poke around with a local cargo build as well.

**Comment by alexcrichton** [comment]
Hm I unfortunately can't seem to reproduce this locally, do you have a reproduction and/or set of instructions that reproduces this for you?

**Comment by TheDan64** [comment]
Okay, I've dug a little deeper into this and it seems to stem from me editing Linux files from VSCode which lives in Windows, which apparently [is a big no-no?](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) The issue disappears if I edit a file with say, emacs, and then run cargo build/compile.

**Comment by alexcrichton** [comment]
Ah ok, thanks for the info! In that case I don't think there's a bug for Cargo here, so I'm going to close
