### ISSUE TITLE
`cargo test --doc --no-run`  seems to be no-op.

### ISSUE THREAD

**Issue by vi** [rust-lang/cargo#5242]
Expectation: check only compilability of doctests.
Reality: `Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs`

**Comment by asoderman** [comment]
I don't believe there is a way to `--no-run` doctests. Running `rustdoc --test --test-args no-run` filters the doctests out.

This would first need to be implemented in rustdoc then cargo will need to implement doctest compilation before exiting when using `--no-run`.

Please correct me if I'm wrong.
