### ISSUE TITLE
Fetching resources from a git dependency

### ISSUE THREAD

**Issue by astonbitecode** [rust-lang/cargo#5245]
Hello,

I have  a [crate](https://github.com/astonbitecode/j4rs) that is hosted on GitHub, and I want to use it as a _git_ dependency for an other crate.
The source, Cargo.toml, README.md and build.rs are fetched successfully, but there is one more directory that is included in the GitHub crate called [jassets](https://github.com/astonbitecode/j4rs/tree/master/rust/jassets). 

It seems that cargo does not fetch the contents of this directory. I see the folder created under 
`$HOME/.cargo/git/checkouts/j4rs-*` but it is empty.

I tried adding an `include` field in the Cargo.toml of j4rs with no luck.

I expected to have the contents of the jassets fetched along with the rest.

Instead, jassets folder is empty

I'm using cargo 0.25.0 (8c93e0895 2018-02-01)

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have a Cargo project that I could poke around to see what's going on here as well?

**Comment by alexcrichton** [comment]
Thanks for the investigation @ehuss! @astonbitecode does that sound like it could fix the issue here?

**Comment by astonbitecode** [comment]
Indeed, the build.rs assumes that Java build has been performed before the Rust build. This is not true in the case of fetching the dependency from GitHub, as @ehuss correctly noticed. 

My apologies for not seeing this bug earlier... Cargo behaves as it should, the issue is on my side.

Thank you @alexcrichton and @ehuss for your time and for the great Cargo tool, of course!
