### ISSUE TITLE
Use different example in "Specifying dependencies from git repositories"

### ISSUE THREAD

**Issue by pitdicker** [rust-lang/cargo#5248]
[Specifying dependencies from `git` repositories](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) currently uses the "next" branch from rand as an example. 

That branch has not seen any changes in three years, and arguably should be removed. Development just happens on master.
Is there another common library that uses a separate branch for the development version to replace it with?

**Comment by pitdicker** [comment]
It seems like winapi and clap use a development branch. Or is pointing to an old / maintenance branch of a project a good idea?

**Comment by matklad** [comment]
I don't think we really need to care about branch and repository existing :) If the branch is deleted, and user copy-pastes the example from the docs, they'll get a ``branch `next` does not exist`` error and probably would figure this out? 

And, given that `next` branch have been stable for three years, I guess it might actually be a good example?

Closing this as I don't think we really *should* do anything here, but if you have a better example in mind than rand, please do send a PR! :)
