### ISSUE TITLE
`cargo rustdoc` lost the `--features` flag

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/cargo#5254]
Hi, it seems like `cargo rustdoc` has lost the `--features` flag on current nightly, which prevents building the `curve25519-dalek` docs.

I didn't see any discussion about this -- was this intentional, and if so, is there a replacement?

**Comment by matklad** [comment]
No, this is definitely not intentional and is a fallout from the migration to clap.will fix ASAP.
