### ISSUE TITLE
Produce clean error if lockfile would end up with duplicate packages

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang/cargo#5267]
<short summary of the problem>
I have been getting

```
$ cargo check --verbose
error: failed to parse lock file at: <path to Cargo.lock>

Caused by:
  package <dependency name> is specified twice in the lockfile
```

It builds fine the first time but fails on any subsequent attempt.

I've tried `rm Cargo.lock && cargo clean && cargo check && cargo check --verbose` with nightly, beta, and stable:
```
cargo 1.26.0-nightly (d63299b6e 2018-03-28) | rustc 1.26.0-nightly (ae544ee1c 2018-03-29)
cargo 0.26.0-beta (41480f5cc 2018-02-26)    | rustc 1.25.0-beta.13 (da81b8884 2018-03-24)
cargo 0.26.0 (41480f5cc 2018-02-26)         | rustc 1.25.0 (84203cac6 2018-03-25)

**Comment by TheIronBorn** [comment]
Ahhhh, just discovered that I poorly copy-pasted the package name from the dependency
i.e.
```
[package]
name = "dependency"
version = "0.1.0"

[dependencies]
dependency = { path = "../dependency" }

**Comment by TheIronBorn** [comment]
Seems to me Cargo should be able to catch that and warn you more explicitly than
> specified twice

**Comment by matklad** [comment]
Here's a simple script that reproduces the error, from #5366:

```
set -e

cd /tmp
DIR="$(mktemp -d)"
cd "$DIR"
cargo new --lib common
cargo new --lib a
cargo new --lib b

cd a
ln -s ../common/ common
cd ..

cd b
ln -s ../common/ common
cd ..

printf "common = {path=\"common\"}\n" >> a/Cargo.toml 
printf "common = {path=\"common\"}\n" >> b/Cargo.toml 
printf "a = {path=\"../a\"}\n" >> b/Cargo.toml 

cd b
# first run succeeds because no lockfile
cargo test 
# second run fails
if cargo test; then
    echo "** bug fixed"
else
    echo "** bug still present. Check Cargo.lock file for duplicate entries of 'common'"
fi
```

**Comment by matklad** [comment]
Another interesting test case for, I think, this issue is https://github.com/rust-lang/cargo/issues/5378

**Comment by alexcrichton** [comment]
@dwijnand ah the test suite can't super easily use symlinks due to Windows, but copying files around should be easy enough!

**Comment by boxdot** [comment]
I started to work on this issue. After implementing a fix, which basically makes `cargo` fail when it encounters duplicate entries in the `resolve` object, I am not sure anymore if this is a good approach. If I understand it correctly, we could just deduplicate the entries in the lockfile. After building should work without problem, right? Please correct me, if I am wrong.

**Comment by alexcrichton** [comment]
@boxdot ah at the fundamental layer having two crates in the same namespace from the same source (aka path dependencies) which are named the same is an error. In that sense there should never have been a lock file in the first place with two crates of the same name like this. (and maybe same version?)

We basically need to always be able to uniquely match a lock file entry to an actual package without any ambiguity, and so if they've got the same name and version that should be an error during workspace construction

**Comment by boxdot** [comment]
@alexcrichton: Thanks for the explanation. In the above PR I catch the error when cargo writes the lockfile. However, I like the idea to catch it earlier much better. I will also compare the versions.
