### ISSUE TITLE
Don't compare User-Agent in http_auth_offered test

### ISSUE THREAD

**Issue by tcely** [rust-lang/cargo#5306]
I don't understand why `User-Agent` header is listed as part of valid.

I checked the commits and it seems like you're constantly updating the version strings shown in this header for `libgit2` which is as far as I know not a version you control. It seems like this has nothing to do with the test and should just be removed from the valid headers list.

See: https://github.com/rust-lang/cargo/blob/0.26.0/tests/build-auth.rs#L23

Also, `Accept` doesn't seem to be under test here and doesn't change. I'm not sure why it should be in this list either.

**Comment by alexcrichton** [comment]
I believe this has since been fixed

**Comment by tcely** [comment]
It appears unchanged in the latest release.

https://github.com/rust-lang/cargo/blob/0.28.0/tests/testsuite/build_auth.rs#L20

**Comment by jirutka** [comment]
> I believe this has since been fixed

Programming is not a religion!

It was not fixed, not in 0.28.0, nor in the current master, see [tests/testsuite/build_auth.rs:20](https://github.com/rust-lang/cargo/blob/04c90d38af5e62770c766321711f62728fd228f3/tests/testsuite/build_auth.rs#L20).
