### ISSUE TITLE
document the difference between 'crate-type = ["proc-macro"]' and 'proc-macro = true'

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/cargo#5310]
...whatever it is.

All I can really see is that `crate-type = ["proc-macro"]` makes rustdoc die with `proc-macro crate not dylib` when used in a path dependency.

---

*(er... now that I think about it, I wonder if that's a bug in rustdoc)*
*(...or even a bug in cargo)*
*(...or rustc even! On stable, it produces the same error, but as an ICE!)*

**Comment by ExpHP** [comment]
Hmm, so the troublesome error message comes from rustc, I gather?

The current impression I get is that it is more or less a *bug* that cargo even allows `crate-type = ["proc-macro"]` in the first place.  If this is the case, I think it should be forbidden (**read:** deprecated, with a warning that points you in the right direction).

**Comment by alexcrichton** [comment]
@ehuss could we perhaps both update the rustc error message as well as simply interpret `crate-type = ["proc-macro"]` as a `proc-macro = true`? (perhaps with a warning to prefer the latter)
