### ISSUE TITLE
Incremental build ignores str case changes

### ISSUE THREAD

**Issue by redcape** [rust-lang/cargo#5320]
Incremental build ignores str case insensitive changes. I spent a lot of time changing the code before realizing this was happening.

    fn main() {
        let test_str = "a man a plan a canal panama";
        println!("{}", is_palindrome(test_str));
    }
    
    fn is_palindrome(test_str: &str) -> bool {
        use std::iter::FromIterator;
    
        let non_whitespace = |p : &char| !p.is_whitespace();
        let forward_iter = test_str.chars().filter(non_whitespace);
        let rev_iter = test_str.chars().rev().filter(non_whitespace);
        println!("{:?}", String::from_iter(test_str.chars()));
        println!("{:?}", String::from_iter(test_str.chars().rev()));
        println!("{:?}", String::from_iter(forward_iter.clone()));
        println!("{:?}", String::from_iter(rev_iter.clone()));
        forward_iter.eq(rev_iter)
    }

There is only one file with only this main.rs in it. The output of cargo run is:

    "a man a plan a canal panama"
    "amanap lanac a nalp a nam a"
    "amanaplanacanalpanama"
    "amanaplanacanalpanama"
    true

Now I make a single change to test_str, change the first "a" to "A". Run cargo run again and get the exact same output. I expected to see this:

    "A man a plan a canal panama"
    "amanap lanac a nalp a nam A"
    "Amanaplanacanalpanama"
    "amanaplanacanalpanamA"
    false

Experienced this on both Windows 10 64 bit and Ubuntu on WSL. Running rustc -o hello src/main.rs produced the correct result everytime (case changes and false result and back to normal) when switching the characters around. Deleting the target directory in between runs also fixes the problem, both of these point towards an issue in incremental builds.

Windows:

    >cargo --version
    cargo 1.26.0-nightly (b70ab13b3 2018-04-04)
    >rustc --version
    rustc 1.27.0-nightly (056f589fb 2018-04-07)

WSL Ubuntu:

    $ cargo --version
    cargo 1.26.0-nightly (b70ab13b3 2018-04-04)
    $ rustc --version
    rustc 1.27.0-nightly (056f589fb 2018-04-07)

Let me know if you need anymore details.

**Comment by matklad** [comment]
Hm, I would guess that this is a bug in incremental compilation of rustc itself. Cargo by default enables incremental compilation, but `rustc src/main.rs` is not incremental.

To test this hypothesis, could you

1) Run cargo with `CARGO_INCREMENTAL` environmental variable set to 0 and see if rebuilds happen (they should, if the hypothesis is correct).
2) Run rustc with `-C incremental=/some/temp/dir` and see if no rebuild happens.

**Comment by matklad** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/49783

Thanks for the report!
