### ISSUE TITLE
In 2018 edition, warn about `cargo install`ing the current crate

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#5327]
Running `cargo install` installs the binaries for the project in current working directory. This might be a surprising behavior for people coming from other ecosystems, especially the node one. The confusion here is that, in Cargo, you don't need to "install" a library to actually use it. At the same time, installing local crates seems like a niche use-case, one typically installs crates from crates.io. 

So let's fix confusion by printing a warning, in the next edition, when a user invokes `cargo install`.  The warning should say:

* If you care coming from other ecosystems, you probably have meant `cargo build`
* If you really want to install current package, run `cargo install --path .`

The code for install command is here:

https://github.com/rust-lang/cargo/blob/d8b20310217e5e2bc515c13111ab9a7789709e42/src/bin/commands/install.rs#L81

To check the current edition, one can use this method:

https://github.com/rust-lang/cargo/blob/d8b20310217e5e2bc515c13111ab9a7789709e42/src/cargo/core/manifest.rs#L409

The tests for install are here:

https://github.com/rust-lang/cargo/blob/d8b20310217e5e2bc515c13111ab9a7789709e42/tests/testsuite/install.rs

**Comment by dwijnand** [comment]
I'll take a crack at this.

**Comment by dwijnand** [comment]
@matklad how should the different behaviour when varying rust editions be tested? I can't find any prior art in https://github.com/rust-lang/cargo/issues?utf8=%E2%9C%93&q=sort%3Aupdated-desc+2018
