### ISSUE TITLE
tweak cargo test help message to not allude to multiple test running

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/cargo#5337]
`cargo test --help` contains:

> Usage:
>     cargo test [options] [TESTNAME] [--] [<args>...]

and

> All of the trailing arguments are passed to the test binaries generated for
> filtering tests and generally providing options configuring how they run.

however one cannot define multiple filters for the tests as only the first argument is used.

see https://github.com/rust-lang/rust/issues/30422 for the rust side of things.

until the behaviour is changed in rust the docs should be changed in cargo's help message to match the status quo.

**Comment by matklad** [comment]
I wouldn't say that the wording is necessary outright wrong: you can pass multiple arguments, it's just that only one of them is used for filtering:

```Rust
cargo test -- test-name-filter --test-threads 3
```


In general, this `--` business is rather surprising and hard to explain to users :(
