### ISSUE TITLE
Building cargo from source, without cargo

### ISSUE THREAD

**Issue by jjbandit** [rust-lang/cargo#5338]
I'm trying to bootstrap the Rust toolchain from source, but it appears that cargo is required to recompile cargo from source.

Is it expected that a user installs a pre-built version of cargo to bootstrap, or is there an undocumented path to doing this?

Asking because I could not find an issue related to or answering this question.

**Comment by matklad** [comment]
@jjbandit yep, you need Cargo and rustc to compile Cargo and rustc. The x.py script in rust-lang/rust automatically handles downloading compiler for bootstrapping.

Some docs about build process are here:
https://rust-lang-nursery.github.io/rustc-guide/how-to-build-and-run.html
https://forge.rust-lang.org/x-py.html

**Comment by jirutka** [comment]
> The x.py script in rust-lang/rust automatically handles downloading compiler for bootstrapping.

It handles only downloading dynamically linked `rustc` and `cargo` binaries that works only on _some_ Linux systems (with glibc and various deps in recent-enough version). For example, it does not work on musl-based systems at all and it’s really pain to bootstrap rustc and cargo for such system.
This is practical part of the problem. Other problem is that you have to trust some binary downloaded from internet.

**Comment by alexcrichton** [comment]
@matklad is indeed correct! Like Rust Cargo requires Cargo to build itself, and previous versions are used. For new platforms it's recommended to cross compile Cargo and then use that binary to compile a new Cargo on the target platform.

**Comment by jirutka** [comment]
@alexcrichton Why you don’t provide cargo as static binary (this would work on every Linux system)?

**Comment by alexcrichton** [comment]
Right now Cargo's distribution is tied to rustc's distribution, and we don't have a statically linked rustc so there's no statically linked Cargo. You can compile a statically linked Cargo locally, however, via `cargo build --target x86_64-unknown-linux-musl`
