### ISSUE TITLE
How do I add a Github username to the authors field?

### ISSUE THREAD

**Issue by jamesray1** [rust-lang/cargo#5339]
So according to https://doc.rust-lang.org/cargo/print.html the format for the authors field in cargo.toml is `authors = ["Your Name <you@example.com>"]`, where the email address is optional. However, to avoid getting spam, I'd prefer to avoid publishing my personal email online, and I don't have a business email. What I'd like is to be able to use a Github username instead, e.g. `authors = ["Your Name (@GitHubUsername)"]`. An example of where this can be done is in the [Ethereum EIPs repo](https://github.com/ethereum/eips) with a YAML header. Then the Github username will be a clickable URL which will direct to the user homepage. An example of this is here with EIP-121: http://eips.ethereum.org/erc, while the origin of this is: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-191.md.

**Comment by alexcrichton** [comment]
Cargo (and I believe crates.io) don't validate this field, so something like `Foo Bar (@baz)` should work! If that doesn't work though just let us know
