### ISSUE TITLE
stale nightly docs

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/cargo#5342]
I contributed a fix to the docs in https://github.com/rust-lang/cargo/pull/5328 2 days ago, and today realised I should be able to see them over in https://doc.rust-lang.org/nightly/cargo/reference/manifest.html.

however my fix isn't present. are the nightly docs stale?

**Comment by matklad** [comment]
Nightly toolchain is built from rust-lang/rust repository, which includes Cargo as a submodule. This submodule needs to be updated manually to get changes into nightly.

https://github.com/rust-lang/rust/tree/master/src/tools

**Comment by dwijnand** [comment]
oh I see. thanks.

do you think it's generally worth having another url that tracks master cargo?
