### ISSUE TITLE
package vs project

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/cargo#5344]
looking at [`TomlManifest`](https://github.com/rust-lang/cargo/blob/0.26.0/src/cargo/util/toml/mod.rs#L200-L203) it currently holds both an optional `package` field and an optional `project` field.

it looks like originally it was just `project` and then `package` was introduced in https://github.com/rust-lang/cargo/commit/86b2a2a432a73b3747cca3593850293a5fc3951a giving precedence to `project` over `package`:

```rust
let project = self.project.as_ref().or_else(|| self.package.as_ref());
```

however in https://github.com/rust-lang/cargo/commit/57db8bdef5e84f88045711d7e5b483f4feb1da4c did the opposite was done, giving precedence to `package` over `project`:

```rust
let mut package = self.package.as_ref()
                      .or(self.project.as_ref())
                      .unwrap()
                      .clone();
```

which should be true? also (as an aside) is the current status an issue?

**Comment by matklad** [comment]
`project` and `package` are aliases of each other. For a very long time, `package` is the prefered key.  We probably can more officially deprecate `project`and start to give warnings about it, but we haven't felt a real need for it so far. 

We can't just remove `project`, because there are some published crates with `project`.

**Comment by alexcrichton** [comment]
Yeah long ago we were hoping to tweak the defaults based on `[package]` vs `[project]`, but that never panned out so we're left with aliases

**Comment by dwijnand** [comment]
I understand. so it looks like as soon as `package` was introduced it was introduced as a fallback to `project`, but when years later that other change happened `package` had become the de facto, and thus `project` was made the fallback.

thanks for the info!
