### ISSUE TITLE
Build example as lib and bin at the same time

### ISSUE THREAD

**Issue by pronebird** [rust-lang/cargo#5365]
Hi,

I wonder if it's possible to build an example as a lib and binary at the same time. The reason for that is basically the fact that I have a windows only crate with windows only example.

Adding `#![cfg(windows)]` at the top of the source code works well for libraries, but fails to compile for binaries that need explicit `main`. 

One of solutions is to wrap everything in `example.rs` into `mod` and guard it with proper `#[cfg(windows)]` however it leads to issues with external crates used in the example since dev deps are defined for windows only too `[target.'cfg(windows)'.dev-dependencies]`. So there is a lot of noise in the code if I take this approach.

The other approach is split the source code on two targets (lib + binary):

```rust
// lib.rs
#![cfg(windows)]
#[macro_use]
extern crate log;

pub fn run() {
  // the rest of code.
}
```

```rust
// main.rs
#[cfg(windows)]
extern crate mylib;

#[cfg(windows)]
fn main() {
    mylib::run();
}

#[cfg(not(windows))]
fn main() {
    panic!("This program is only intended to run on Windows.");
}
```

So I configured the example in my `Cargo.toml` to include two crate-types, however Cargo does not seem to understand that configuration. At least what I see during compilation is an error that the compiler can't find `mylib` crate.

```
[[example]]
name = "example"
crate-type = ["lib", "bin"]
```

**Comment by ehuss** [comment]
See #3138 for a similar request (platform-specific examples).

**Comment by azriel91** [comment]
Different use case, but similar symptom: I'd like to create examples that can be run both natively and as a WASM application. The WASM version requires the example to be built as a library, whereas natively it should be a binary.

Currently I've gone with just making the example a normal crate, and users have to enter the directory (or pass in the manifest path) to run it.

**Comment by dclong** [comment]
Similar situation here.

**Comment by epage** [comment]
For myself, I feel like #9208 is the right way to be going such that I'm going to propose to the cargo team that we close this in favor of that.

**Comment by weihanglo** [comment]
Second. Closing in favor of #9208.
