### ISSUE TITLE
Lockfile ends up with 2 duplicate entries

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#5366]
I am reporting this on behalf of IRC user metsu, who isn't on github.

Logs: https://botbot.me/mozilla/cargo/2018-04-16/?msg=99024994&page=1

> metsu: Hello, I'd like to report a bug in cargo where the lockfile ends up with two duplicate entries. I've written a bash script that reproduces this bug using the latest release: https://paste.ubuntu.com/p/2fnHR6ccrC/

Paste content duplicated here just in case:

```
set -e

cd /tmp
DIR="$(mktemp -d)"
cd "$DIR"
cargo new --lib common
cargo new --lib a
cargo new --lib b

cd a
ln -s ../common/ common
cd ..

cd b
ln -s ../common/ common
cd ..

printf "common = {path=\"common\"}\n" >> a/Cargo.toml 
printf "common = {path=\"common\"}\n" >> b/Cargo.toml 
printf "a = {path=\"../a\"}\n" >> b/Cargo.toml 

cd b
# first run succeeds because no lockfile
cargo test 
# second run fails
if cargo test; then
    echo "** bug fixed"
else
    echo "** bug still present. Check Cargo.lock file for duplicate entries of 'common'"
fi
```

This is all the context I have. Please contact metsu in #cargo on moz IRC with followup questions; I'm unsubscribing from this issue.

**Comment by lukaslueg** [comment]
More or less the as #5267 I guess?!

**Comment by matklad** [comment]
Yep! Thanks @lucaskolstad for noticing a duplicate, metsu for creating a super-helpful reproduction script and @carols10cents for reporting the issue!

closing as a duplicate.
