### ISSUE TITLE
`cargo build` for tests builds dependencies with `panic`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5369]
Dependencies for tests should not have `panic` set from the profile.  However, using `cargo build` (instead of `cargo test`) does not correctly clear the `panic` flag for dependencies.

Repro:
```
cargo new --lib a
cd a
cat >> Cargo.toml <<EOL
[profile.dev]
panic = "abort"
EOL
mkdir tests
echo "extern crate a;" > tests/t1.rs
cargo build --test t1 -v
```

I can fix this as part of working on profiles if you'd like.

**Comment by sfackler** [comment]
The test harness requires panic=unwind to work properly.

**Comment by alexcrichton** [comment]
Hm I'm not sure I entirely understand, but @ehuss  I believe @sfackler is right in that if we actually respect the `abort` option for building tests we'll fail compilation?

**Comment by ehuss** [comment]
I would expect `cargo build --test foo` to build the target the same way `cargo test --test foo` does.  Currently it is *close*.  It picks the `test` profile, etc.  However, dependencies don't pick up the `test_deps` profile in order to clear the panic setting.  When you try the given example, `rustc` aborts with an error because of mixed panic settings.

My profile work "fixes" this, in that `panic` gets cleared for test dependencies regardless of which command is used.

**Comment by alexcrichton** [comment]
Aha that makes sense! In that case it'd be great to see this fixed, I definitely agree that `cargo build --test foo` should work the same way as `cargo test --test foo`
