### ISSUE TITLE
`DEBUG` env var in build.rs is incorrect if profile debug=0

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5370]
The `DEBUG` environment variable set for a build script currently gets set to `true` if you have a profile with `debug=0`.  AFAIK, rustc treats debug=0 the same as no debug, so I think it should be false.

Repro:
```
cargo new --lib a
cd a
cat >> Cargo.toml <<EOL
[profile.dev]
debug = 0
EOL
cat > build.rs <<EOL
fn main() { println!("DEBUG={}", std::env::var("DEBUG").unwrap()); }
EOL
cargo build -vv
```

I can fix this if you'd like.

**Comment by alexcrichton** [comment]
Ah yes thanks this'd be good to fix!
