### ISSUE TITLE
`cargo rustc` in root of workspace gives wrong error

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5371]
If you run `cargo rustc` (or `cargo rustdoc`) in the root of a workspace, you get the following error:

```error: manifest path `/path/to/ws` contains no package: The manifest is virtual, and the workspace has no members.```

However, the workspace does have members!  I think it should instead show something like the error message from `Workspace::current` (```manifest path `{}` is a virtual manifest, but this command requires running against an actual package in this workspace```).

I can fix this if you'd like.

**Comment by alexcrichton** [comment]
Sounds like a great fix to me!
