### ISSUE TITLE
Missing metadata in output of `cargo metadata`

### ISSUE THREAD

**Issue by ysimonson** [rust-lang/cargo#5373]
The output of `cargo metadata` does not include the following metadata fields:
* authors
* repository
* readme
* keywords
* categories

Is this a bug?

Context: These fields are among the list in [C-METADATA of the API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#cargotoml-includes-all-common-metadata-c-metadata). There is an [open ticket in clippy](https://github.com/rust-lang-nursery/rust-clippy/issues/1793) to check that these fields are defined. While a lint like this would typically lean on [cargo_metadata](https://docs.rs/cargo_metadata/0.5.4/cargo_metadata/), it's not presently possible to use it, as cargo_metadata uses the output of `cargo metadata`.

**Comment by matklad** [comment]
It seems fine by me to add all these! The relevant bit of code is here: https://github.com/rust-lang/cargo/blob/de23b54b01324a9e17e04e1bbe6d69468904f348/src/cargo/core/package.rs#L32

**Comment by ysimonson** [comment]
OK, I can tackle this
