### ISSUE TITLE
Random resolution failures on path dep with name same as built crate

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/cargo#5378]
I've found an interesting bug, which randomly crashes building crates with specific dependencies.

1. Crate first crate with `Cargo.toml`:
```
[package]
name = "foo"
version = "0.1.0"
```
2. Create second crate with `Cargo.toml`:
```
[package]
name = "foo"
version = "0.2.0"
[dependencies]
foo = { path = "path/to/the/first/foo" }
```
3. Repeatedly run `cargo build` on the second `foo`. Some runs will succeed, but some will randomly fail on dependency resolution:
```
error: no matching version `= 0.2.0` found for package `foo` (required by `foo`)
location searched: file:///path/to/the/first/foo
versions found: 0.1.0
consider running `cargo update` to update a path dependency's locked version
```

**Comment by matklad** [comment]
Hm, interesting! I think is a perfect test-case for https://github.com/rust-lang/cargo/issues/5267, so closing in favor of that!

**Comment by CodeSandwich** [comment]
Sure, thank you :slightly_smiling_face:

**Comment by matklad** [comment]
Hm, indeed!

**Comment by CodeSandwich** [comment]
I can close this issue as already solved. I had an almost 1 month old version of Cargo and after update everything works fine, I can't reproduce problem anymore! Thank you for your help and sorry for the fuss :slightly_smiling_face:
