### ISSUE TITLE
Mirror network

### ISSUE THREAD

**Issue by ghost** [rust-lang/cargo#540]
From what I can tell, there are no plans to distribute the index or the packages across a mirror network. Maybe you have plans which are not documented yet, but in case you don't, here are some arguments to use a mirror network:
##### pros
1. availability of the index in case of outages
2. availability of packages regardless of the original project repository
3. archival of old versions
4. avoiding SPOF (Hackage down, what do we do?)
5. distributing the load across a mirror network like CPAN and FLOSS OSes do
6. it's a model which has been used successfully by major projects for decades
7. depending on from where you access the network, a specific mirror may be the only way of using remote packages
8. maintaining organization wide local mirrors for dev teams
9. it's an important provision for scalability
10. allows Cargo to automatically fall back to other mirrors if a selected mirror is down
11. given widespread use of Rust, many projects' CI setups are going to rely on it, and for that availability is critical
##### cons
1. A configured mirror may lag behind master instance, but this can also be of advantage, and if you always need the latest the moment it's published, you can configure to prefer a certain mirror.
##### how
- the same way as a BSD, a Linux distro, or CPAN
- ideally, support incremental (binary delta) update of index and/or packages

**Comment by bstrie** [comment]
@tuncer Now that crates.io actually exists, feel free to continue this ticket over at https://github.com/rust-lang/crates.io/issues

**Comment by tuncer** [comment]
This requires changes in both cargo and the index+archive, so I'm not sure it's more suitable to file a new ticket over there.

Summary:

1. Uploads go to master.
2. Master is used to sync mirrors.
3. Index is updated and synced.
4. Clients must preferably use mirrors or a redirector.
5. A paid-for CDN can be one of many mirrors.
6. Index needs to be more like Fedora's or Debian's (delta updates, etc.).
7. archive of all published releases
8. git is unsuitable as index storage. What we need is the history of a crate's versions, not the history of index changes. The index points to crates, and for each crate to N releases.
9. It's much more likely to get free mirrors like FreeBSD, Debian, and CTAN than getting sponsorship for a single super CDN.
10. Mirrors mean master can go down and clients can still fetch (only r/o operations), and only index changes will be affected.
11. Naturally, the index is also mirrored together with the archive.
