### ISSUE TITLE
Switch to using --edition

### ISSUE THREAD

**Issue by klnusbaum** [rust-lang/cargo#5406]
In https://github.com/rust-lang/rust/issues/49591 we introduced and official `--edition` flag to the rust compiler. Let's start using that in cargo now.

**Comment by steveklabnik** [comment]
did https://github.com/rust-lang/cargo/pull/5410 supercede this?

**Comment by Manishearth** [comment]
That's a PR

**Comment by steveklabnik** [comment]
Oops, how embarrassing. Carry on!
