### ISSUE TITLE
Running a command against multiple toolchains 

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/cargo#5414]
Sometimes (for example within Cargo itself) you have code and/or tests that behave differently according to the toolchain used.

In such cases there's no convenient way to run a command, such as `test`, against multiple toolchains.

The workaround I've used is to call cargo twice in the shell, with the toolchain argument change, e.g:

```bash
CFG_DISABLE_CROSS_TESTS=1 cargo test run::run_example \
  && CFG_DISABLE_CROSS_TESTS=1 cargo +nightly test run::run_example
```

I've no idea what that could be, maybe something like:

```bash
CFG_DISABLE_CROSS_TESTS=1 cargo +stable/+nightly test run::run_example
```

**Comment by joshtriplett** [comment]
Things like +stable and +nightly aren't part of Cargo, they're part of rustup. Cargo normally just runs `rustc`.

I'm going to close this; I'd suggest discussing it with the rustup folks, but I suspect that you should probably stick with running the commands twice. (Perhaps a bit of scripting would help: `for toolchain in stable nightly ; do ... ; done`, or integrating it into CI.)

**Comment by dwijnand** [comment]
OK, I'll report it upstream and see what they think.

**Comment by dwijnand** [comment]
FWIW I ended up creating and using these shell functions:

```bash
# san = stable AND nightly, stn = stable THEN nightly
cargo-san() { cargo +stable  "$@" ;  cargo +nightly "$@"; }
cargo-stn() { cargo +stable  "$@" && cargo +nightly "$@"; }
cargo-nas() { cargo +nightly "$@" ;  cargo +stable  "$@"; }
cargo-nts() { cargo +nightly "$@" && cargo +stable  "$@"; }
```
