### ISSUE TITLE
Tracking issue for renaming crate dependencies

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5422]
This is a tracking issue for the `package` key in the `[dependencies]` section.

First introduced in https://github.com/rust-lang/cargo/pull/4953 and the original tracking issue was https://github.com/rust-lang/cargo/issues/1311. Known issues are:

* What to do about `--features` on the command line? Does `--features foo/bar` imply the package `foo` or the crate that's renamed to `foo`? We probably want the latter, and that's probably buggy right now.

**Comment by matklad** [comment]
Argh, I've accidentally created https://github.com/rust-lang/cargo/issues/5653#issuecomment-400356447. Closing in favor of that, it has more info.
