### ISSUE TITLE
--message-format=json should indicate which produced files are executables

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#5426]
Currently `--message-format=json` just dumps the list of files that was produced when compiling a project. Cargo doesn't have too much knowledge about what exactly is produced for which target and crate type, but it should indicate at least which artifact is an executable binary. This is important for IDEs, which at the moment have to implement ugly work-arounds to separate actual binaries from debuginfo, for example (see https://github.com/vadimcn/vscode-lldb/issues/104). 

Some pointers to code:

* a struct representing JSON messages: https://github.com/rust-lang/cargo/blob/3b14988d423b1858252ee05c5395abd035bbea5f/src/cargo/util/machine_message.rs#L30
* the place where we actually print the info: https://github.com/rust-lang/cargo/blob/3b14988d423b1858252ee05c5395abd035bbea5f/src/cargo/core/compiler/mod.rs#L603-L612
* a struct which knows where the binaries are: https://github.com/rust-lang/cargo/blob/3b14988d423b1858252ee05c5395abd035bbea5f/src/cargo/core/compiler/compilation.rs#L17-L21

I think we could perhaps add an `executable: Option<PathBuf>` field to the `CompilerArtifact`?

**Comment by patriksvensson** [comment]
I can give this a try if no one else already started working on it.

**Comment by matklad** [comment]
Awesome! I think the relevant test for this is this one: https://github.com/rust-lang/cargo/blob/6cd841fe4a55d21d8f9a74102e86acb9475d45da/tests/testsuite/build.rs#L3994

**Comment by patriksvensson** [comment]
@matklad This is perhaps a stupid question, but how can I know which binary in `Compilation.binaries` is the executable (if any)?

**Comment by matklad** [comment]
@patriksvensson all binaries in `binaries` are executables, either tests, or real binaries with `main` and such. The logic for populating them is here:

https://github.com/rust-lang/cargo/blob/151f37c2a7a797936ba755e52abee192dda8a1d3/src/cargo/core/compiler/context/mod.rs#L164

I think that logic needs to be duplicated when emitting JSON messages.

**Comment by matklad** [comment]
Hm, I think that code is buggy actually! Filed https://github.com/rust-lang/cargo/issues/5474 about it. Would you like to tackle that first?

**Comment by patriksvensson** [comment]
@matklad Sure, I can try that one first.

**Comment by patriksvensson** [comment]
Will go ahead with this one now then.

**Comment by patriksvensson** [comment]
I've not given up on this. Simply just been a lot of work. Planning on continue working on the PR later today.

**Comment by dwijnand** [comment]
Hey @patriksvensson, how close to completion is https://github.com/patriksvensson/cargo/tree/feature/GH-5426 ?  Are you still interested in working on this?  Otherwise, I could try and rebase your work and finish it off...

**Comment by patriksvensson** [comment]
@dwijnand Go ahead! I ran out of free time and encountered a lot of merge conflicts, and then the PR was closed because of inactivity 😄

**Comment by patriksvensson** [comment]
@dwijnand I think that the PR is close to completion, but can't remember to be honest.
