### ISSUE TITLE
The publish-lockfile option is not usable

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/cargo#5427]
The `publish-lockfile` manifest key was introduced in https://github.com/rust-lang/cargo/pull/5093 as a nightly feature. However, it is not usable at the moment because nightly-only features are not allowed on crates.io:

```
> cargo publish
error: cannot publish crates which activate nightly-only cargo features to crates.io
```

cc @alexcrichton

**Comment by oli-obk** [comment]
The same goes for `cargo-features = ["edition"]`, which means that there will be no more published clippy versions until this issue is resolved

**Comment by xianghx** [comment]
mark. cliipy doesn't work
