### ISSUE TITLE
cargo new --bin --lib should be allowed

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#5431]
It makes sense to make a crate with both lib and bin (IMHO it's the best solution for serious projects).

Currently `cargo new` doesn't support both flags at the same time. Would you be interested in PR that adds such functionality?

**Comment by matklad** [comment]
I personally believe that we should do it, and that this, unlike other "let's make project creation better" ideas, does not need to wait for custom project templates.

**Comment by dwijnand** [comment]
The PR (#5433) for this was closed in favour of the pending decision in https://github.com/rust-lang-nursery/api-guidelines/issues/167.

Should we close this as well?

**Comment by alexcrichton** [comment]
Indeed!
