### ISSUE TITLE
Deprecate doc profile?

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5434]
The `doc` profile currently is not used for anything.  Is that intentional?  Currently it is assigned to the `Unit` used for running `rustdoc`, but `rustdoc` does not use any of the flags from the profile.  There are ~24 crates on crates.io that set it for whatever reason.

If it doesn't have a purpose, should we add a deprecation warning?  Just remove it from the documentation?

**Comment by matklad** [comment]
Adding a deprecation warning and removing from the docs sounds good to me!
