### ISSUE TITLE
`--features` doesn't work for `cargo metadata` in projects with workspaces

### ISSUE THREAD

**Issue by koute** [rust-lang/cargo#5439]
Steps to reproduce:

```
cargo new --lib foo
cd foo
echo '[workspace]' >> Cargo.toml
echo 'members = ["bar"]' >> Cargo.toml
cargo new --lib bar
cargo metadata --features dummy
```

This generates the following error on cargo 1.27.0-nightly (0a1add2d8 2018-04-20):

```
error: cannot specify features for more than one package
```

This completely breaks `--features` usage in `cargo-web` on nightly (https://github.com/koute/cargo-web/issues/95).

It works as expected on stable. This is possibly related to https://github.com/rust-lang/cargo/issues/5364.

**Comment by alexcrichton** [comment]
I believe this was reverted and fixed in https://github.com/rust-lang/cargo/pull/5430, so closing in favor of that
