### ISSUE TITLE
Does changing LTO settings have to recompile dependencies?

### ISSUE THREAD

**Issue by durka** [rust-lang/cargo#5442]
If you change the LTO setting in one of the profiles in Cargo.toml, all dependencies get recompiled. Is this really necessary? As far as I know, LTO only affects the very last rustc run (the one that actually links).

**Comment by alexcrichton** [comment]
As of rustc right-this-red-hot-second we don't need to recompile, but possible changes in the future means that we would need to recompile, yes.

**Comment by durka** [comment]
Hmm okay, so maybe not worth adding the bookkeeping to avoid these
recompiles if it will probably change anyway.

**Comment by alexcrichton** [comment]
Such changes are probably far out (not on most roadmaps) as they mostly only affect whole-crate-graph complilation, so it may be wortwhile to add logic in the meantime, PRs are of course always welcome!

**Comment by dwijnand** [comment]
The door is still open to reopening this issue, but I'll take the lack of response to mean there isn't such a burning desire for this optimisation.
