### ISSUE TITLE
`panic` not always tracked in built dependencies

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5445]
Whether or not `panic` was used is not always tracked in the metadata hash.  This can cause cargo to mistakenly reuse a lib with the wrong settings.

In particular, build-dependencies, plugins, and proc-macros and their dependencies do not encode that they were compiled without panic.

This can creep up in a variety of ways, but here is a relatively small repro:
```
mkdir ws
cd ws
cargo new --lib a
cargo new --lib pm
cat > Cargo.toml <<EOL
[workspace]
members = ["a", "pm"]
[profile.dev]
panic = "abort"
EOL

cat >> pm/Cargo.toml <<EOL
a = {path="../a"}
[lib]
proc-macro = true
EOL

echo "extern crate a;" >> pm/src/lib.rs

# This builds `a` with panic.
cargo build -p a -v
# This fails with wrong panic strategy since it reuses `a`.
cargo build -p pm -v
# Note: Compiling these in the other order works.
```

Fixing this is partially blocked by #5444, and possibly other issues.

**Comment by ehuss** [comment]
Panic is set in the profile for proc-macros.  It is only cleared at the end when the args are constructed here:

https://github.com/rust-lang/cargo/blob/181de52b2e08d36822af4178af395b5d3bdc1719/src/cargo/core/compiler/mod.rs#L910-L914

Nothing in the hash indicates that a dependency is used by a proc-macro.

**Comment by alexcrichton** [comment]
Ah ok makes sense! I think we should probably just include `cx.used_in_plugin.contains(unit)` in the fingerprint, right?

**Comment by alexcrichton** [comment]
This should be fixed at https://github.com/rust-lang/cargo/pull/5458

**Comment by ehuss** [comment]
I was thinking about clearing the panic flag when the profile is constructed.  That would fix dependencies shared with proc-macro dependencies (currently shared dependencies are built without panic set).

**Comment by alexcrichton** [comment]
@ehuss ah yes I think that'd probably be the best solution, I was hoping for a quick fix as this is a pretty serious bug and beta is being branched this weekend. That sounds like a good follow-up though!

**Comment by ehuss** [comment]
@alexcrichton kk, i'm working on it now, will hopefully get the bugs nailed down before then.

**Comment by alexcrichton** [comment]
Awesome, thanks!

**Comment by alexcrichton** [comment]
@ehuss btw do you have an example which still fails to build after #5458? If so I can reopen

**Comment by ehuss** [comment]
@alexcrichton  Shared dependencies will be built w/o panic:

```
cargo new --bin foo
cd foo
cargo new --lib shared
cargo new --lib pm

cat >> pm/Cargo.toml <<EOF
shared = {path = "../shared"}
[lib]
proc-macro = true
EOF

cat >> Cargo.toml <<EOF
pm = {path = "pm"}
shared = {path = "shared"}

[profile.dev]
panic = "abort"
EOF

# `shared` will be built without panic.
cargo build -v
```

This doesn't cause any errors since linking with unwind dependencies doesn't fail.

I can't remember if I asked already, but what are the specific problems with linking with a lib built with `unwind`?  It sure would be easier if we could just set panic for bins.
