### ISSUE TITLE
Add a cargo command to clean only the documentation

### ISSUE THREAD

**Issue by DarkDrek** [rust-lang/cargo#5449]
Currently when using `cargo doc` multiple times with different options or changing the bin/lib names the old documentation is still there.
One can use `cargo clean` to remove the documentation but that will also remove the build binaries.

So I think a command to only clean the build documentation should be provided.
Something like `cargo clean --doc` or `cargo doc --clean` or both?

**Comment by alexcrichton** [comment]
Something like `cargo clean --doc` sounds great to me!

**Comment by DarkDrek** [comment]
Ok I will try to implement it myself.

**Comment by DarkDrek** [comment]
Fixed with #5451 
Thanks
