### ISSUE TITLE
cargo workspace can't have two .so builds

### ISSUE THREAD

**Issue by kpcyrd** [rust-lang/cargo#5463]
```
$ cargo --version
cargo 0.26.0 (41480f5cc 2018-02-26)
$ rustc --version
rustc 1.25.0 (84203cac6 2018-03-25)
```

I'm working on a project that can have multiple `.so` files as an output, since Cargo.toml only supports a single library I started using workspaces. This seems to break my build. You can reliably reproduce the issue by executing this script:

```bash
cargo new --lib parent
cd parent
cat >> Cargo.toml <<EOF
[lib]
crate-type = ["lib", "dylib", "staticlib"]

[workspace]
members = ["child"]
EOF

cargo new --lib child
cd child
cat >> Cargo.toml <<EOF
[lib]
crate-type = ["lib", "dylib", "staticlib"]
EOF

cargo build
ldd ../target/debug/libchild.so
```

This results in the following output for me:
```
$ ldd ../target/debug/libchild.so 
	linux-vdso.so.1 (0x000061f797394000)
	libstd-c10c01f750e28d27.so => not found
```

Specifically `libstd-c10c01f750e28d27.so` is confusing since this breaks the library. This ID is always the same for me, I found https://github.com/alexcrichton/rust-ffi-examples/issues/15 which mentions this exact string (but seems to do something else).

**Comment by ehuss** [comment]
This line of code is suspicious since the members check cannot be false in a workspace with more than one member.

https://github.com/rust-lang/cargo/blob/6cd841fe4a55d21d8f9a74102e86acb9475d45da/src/cargo/core/compiler/mod.rs#L896

**Comment by alexcrichton** [comment]
@kpcyrd for building dynamic libraries it's highy recommended to use the `cdylib` crate type, but is there a reason you want to rust dynamic libraries?

**Comment by alexcrichton** [comment]
Ok great, glad to hear!

**Comment by kpcyrd** [comment]
Is the behaviour I noticed expected? I left the issue open because it appears to be a bug. Feel free to close the issue if it isn't. :)

**Comment by alexcrichton** [comment]
Ah ok! It's currently expected (if unfortunate), so I'm gonna close
