### ISSUE TITLE
[Request] Support shared dependency declaration in virtual manifests

### ISSUE THREAD

**Issue by phrohdoh** [rust-lang/cargo#5471]
Given a virtual manifest like so:

```toml
[workspace]
members = [
    "a",
    "b",
    "c",
    "d",
]
```

It would be useful to declare dependencies that are shared between members in a central place (such as this manifest):

```
[dependencies]
serde = "1.0.45"
serde_json = "1.0.17"
serde_derive = "1.0.45"
```

When building if we are looking for crate `serde` in, for example, package `a` but `a/Cargo.toml @ dependencies` does not list `serde` we would look in the virtual manifest that includes `a` as a member (if there is one).

---

This will no doubt complicate dependency resolution somewhat but I do not know to what extent so if it is too crazy please feel free to close this ticket.

---

The idea for this is that, at least in my experience, workspace members have certain shared deps that you want to stay in sync and this makes that easier to express.

**Comment by alexcrichton** [comment]
For anyone interested in this issue I've [posted an RFC](https://github.com/rust-lang/rfcs/pull/2906) which I think will help resolve this. Feedback on the RFC would be most welcome!

**Comment by epage** [comment]
#8415 has been stabilized with support for sharing of dependencies in a workspace
