### ISSUE TITLE
Spurious error in `test_edition` on Travis

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5482]
The test `package::test_edition` can fail randomly.  It looks like the stderr output from rustc is getting intermixed with the output from Cargo.  It results in something like this:

```
Compiling error: Unrecognized option: 'edition'
foo v0.0.1 (...)
Running ...
```

when it should look like this:
```
Compiling foo v0.0.1 (...)
Running ...
error: Unrecognized option: 'edition'
```

I'm able to reproduce this in a Travis docker image, though it doesn't happen often.  I haven't investigated why.  I was under the impression that stderr would be locked to prevent this?  Or maybe because `rustc` inherits stderr it doesn't get locked the same?

**Comment by alexcrichton** [comment]
This may be a case where we print what's happening concurrently with spawning rustc. We may have just gotten lucky up to now that rustc takes enough time to get to an error that we never witnessed this. The fix here is probably going to be to ensure that we're finished printing before we spawn rustc.

**Comment by ehuss** [comment]
I've done some investigation and have found a few problems:

- `Shell` does not do any locking or buffering for output.  `termcolor` has a "Buffer" API for exactly this case, and I think it would be relatively easy to use that API instead.  Without buffering or locking, it allows output to appear in between the status ("Compiling") and the following text ("foo v0.5.0...").
- Ensuring the "Running" message is printed first might be tricky.  It is implemented as an mpsc channel in `JobQueue`.   AFAIK, that does not support returning an acknowledgment.  Do you have any ideas on an easy way to block until it's printed?  (Trying to print from within the threads seems like a fairly heavy change, but is probably doable.)
- (Unrelated to the `test_edition` failure.)  There is no locking or coordination of the output from `rustc` (on [non-Windows platforms](https://github.com/rust-lang/rust/blob/master/src/librustc_errors/lock.rs)).  That means it is relatively easy to have intermixed output if two concurrent `rustc` processes want to print at the same time, or at the same time that cargo wants to print.  This is especially easy to trigger on macos which has a paltry `PIPE_BUF` of 512 ("Running" lines can easily exceed that limit, and it's not too hard to make `rustc` messages that are longer than that).  Do you know why there isn't any locking?

**Comment by alexcrichton** [comment]
Oh unfortunately the Buffer api from `termcolor` afaik only locks within one process, it can still have output intermingled from other processes on Windows. For example there's no way to print "Compiling xxx" in one message, but rather Windows forces us to print "Compiling" first, reset some settings, and then print "xxx".

I was thinking yeah that we'd send a freshly minted channel (or something like that) to the main thread and then wait on it to receive something which happens after the print happens. I don't think we'll want the child threads to start printing themselves.

Hm interesting though! The idea for rustc was that diagnostics could be intermingled from concurrent compilations but diagnostics could never be corrupted (aka line-by-line interleaved). You've found the global lock we use on Windows for this but on Unix we thought that relying on the atomicity of `write` would be enough. Which is to say that we assume that `write(LARGE_BUF)` is atomic wrt any other `write(LARGE_BUF)`, but I see what you mean now in that if `write` simply accepts fewer bytes that one write is indeed "atomic" but not at the layer that we want. This is likely a bug that we'll need to fix in rustc!

**Comment by ehuss** [comment]
> termcolor afaik only locks within one process

Correct.  I was just thinking that it would help keep the line atomic assuming the buffer is under `PIPE_BUF` size, which it normally is for the status messages (except "Running").   This should also apply to Windows 10 which now uses ANSI (which I think has 1k atomic writes).

> send a freshly minted channel

Sounds reasonable.

> This is likely a bug that we'll need to fix in rustc!

It is very rare on Linux which has a large 4k buffer size.  Also, Cargo JSON output looks to be immune since it goes through a pipe.  I'm not sure how important it would be to fix, considering it would probably involve tricky locking, and I don't see any recent complaints about it.

**Comment by alexcrichton** [comment]
Yeah TBH this instance on CI is the *only* time I've ever seen this jumbled up output, so I don't think it's too too common.

**Comment by ehuss** [comment]
I think this issue is no longer valid. All output is now atomically serialized and managed on a single thread.
