### ISSUE TITLE
Features enabled through build scripts should have an effect on dependencies

### ISSUE THREAD

**Issue by glandium** [rust-lang/cargo#5499]
I've been using build scripts to enable features based on rust versions automatically, such that if you build with a version that added a new feature to the language or libstd, users of the crate can automatically get those without having to manually enable features.

But sometimes, the feature needs another crate as dependency. In that case, what you really want is an optional dependency, and for the feature to enable it. But the only way to enable a feature from a build script only enables the feature from rustc perspective, not cargo's.

So, say you have a `Cargo.toml` with something like:
```
[dependencies]
foo = { version = "0.1", optional = true }
```
or
```
[features]
foo = ["bar"]

[dependencies]
bar = { version = "0.1", optional = true }
```

A build script that does:
```rust
fn main() {
    println!("cargo:rustc-cfg=feature=\"foo\"");
}
```
won't make the optional dependency built in either case, which makes sense because it's all about rustc, but should, IMHO, be supported.

**Comment by kevinaboos** [comment]
I just learned from the Cargo IRC channel that this is the expected behavior. It'd definitely be nice to at least mention it in the docs.

However, I'd agree with @glandium that it would be ideal if there was a build-script-time setting that _could_ activate conditional dependencies. It doesn't have to be based on features, it could be based on other configs, such as `"cargo:rustc-cfg=mycfg"`.  Maybe something like `"cargo:cargo-cfg=XYZ"` that affects cargo dependencies too.

**Comment by Eh2406** [comment]
With Cargos current architecture, this is technically not possible. The build script is run (once) after the dependencies are built, so without time travel it can not add dependencies.
Leaving open as better docs and better error messages is reasonable.

**Comment by SRGOM** [comment]
Shouldn't the build script run after the build-dependencies are built and then build the dependencies itself?

**Comment by FizzWizZleDazzle** [comment]
Could you theoretically make a prebuild script, or a setting that enables it depending on what a function returns?

**Comment by kno10** [comment]
An example where the current default-features mechanism is not sufficient is when you use BLAS.

If you want to make a cross-platform library that uses BLAS, welcome to dependency feature hell.
On OSX, you likely will want to use accelerate, on Linux openblas. But this means you need different dependencies & you need to pass different features to other libraries, e.g., <https://crates.io/crates/blas-src> you wan to to pass `blas-src/acclerate` by default on OSX.

Now OpenBLAS and Accelerate are only the *defaults*, you still want the user to be able to choose other BLAS libraries. E.g., Intel-MKL.

This is likely why blas-src does not have any default value, but every time you use it, you have to specify which BLAS to use. And for every library that includes blas functionality, such as ndarray-linalg, e.g., `ndarray-linag/openblas-system`. And then for any crate that depends on ndarray-linalg, e.g., <https://crates.io/crates/ndarray-glm>
