### ISSUE TITLE
`cargo rustc` broken for tests in project with bins

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5502]
If you have a project with a binary and an integration test, then `cargo rustc --test test1 -- -C opt-level=3` will fail with the following error:

```
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
```

The reason is that I changed it to add the implicit bin targets earlier (into `generate_targets` when it was previously in `compute_deps`) in order to avoid some code duplication.

I *think* it should be fine just to move it back to `compute_deps`, the code duplication was very minor.

**Comment by matklad** [comment]
This is a regression, right? So we might want to backport it perhaps?

**Comment by ehuss** [comment]
> This is a regression, right? So we might want to backport it perhaps?

For 1.27, I think so.  If you want, if/when the current PR is approved, I can post another for the backport.

**Comment by matklad** [comment]
> I can post another for the backport.

Yep, let's do the backport dance!
