### ISSUE TITLE
Build script "cargo:warning=..." truncates after new-line

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/cargo#5504]
If I try to print something using `cargo:warning` with a new line character in, it truncates everything from the `\n` onwards:
``` rust
println!("cargo:warning=first line\nsecond line");
```
Prints:
```
warning: first line
```

Whereas I expected:
```
warning: first line
second line
```

Is this intended, and is there a way to work around it? I'm using `cargo 1.27.0-nightly (af3f1cd29 2018-05-03)`

**Comment by alexcrichton** [comment]
Thanks for the report! This is expected behavior in the sense that Cargo only sees the latter output and doesn't understand that it was originally printed as "one unit", so you'll want to split on newlines and print each line with the `cargo:warning` prefix

**Comment by IsaacWoods** [comment]
Okay, thanks!
