### ISSUE TITLE
Reproducible builds: Automatically remap $CARGO_HOME and $PWD

### ISSUE THREAD

**Issue by kpcyrd** [rust-lang/cargo#5505]
As a followup of https://github.com/rust-lang/rust/issues/41555, I think `$CARGO_HOME` and `$PWD` (the location of the project) should be remapped to fixed values automatically.

I found both of those paths inside binaries and I have to add boilerplate to all of my [reprotest] scripts to normalize them.

The motivation behind this is that alice and bob can both download the same release of a rust project, `cargo build --release` it and end up with a 100% identical binary, given a sufficiently similar build environment (rustc version and system libraries).

[reprotest]: https://github.com/ReproducibleBuilds/reprotest

**Comment by sanxiyn** [comment]
Maybe we can do this only on release builds?

**Comment by alexcrichton** [comment]
If we can solve the debug problem, yes we may be able to do it by default on release builds as well.

**Comment by kpcyrd** [comment]
@alexcrichton debugging in rust depends on debug symbols, correct?
```
[profile.dev]
debug = true       # include debug information (debug symbols). Equivalent to
                   # `-C debuginfo=2` compiler flag.
```
couldn't we remap those paths if `debug` is set to false?

**Comment by alexcrichton** [comment]
Perhaps, but I believe they still show up in panic paths

**Comment by mfarrugi** [comment]
@alexcrichton Any additional colour on what could/would break wrt debuggers? I am somewhat surprised $PWD makes it into the binaries at all.

**Comment by alexcrichton** [comment]
@mfarrugi debuggers use the paths in debuginfo (which don't show up in `strings` output) for setting breakpoints and showing code whiel you're stepping through code. Anything which references a registry crate has an absolute path and can be debugged by setting breakpoints on the file and such. Crates in the cwd, if referenced via an absolute path, are also loaded by the debugger and would break as `$PWD/foo.rs` doesn't actually exist

**Comment by infinity0** [comment]
The question is what to map the paths *to*. In Debian we install source code into `/usr/share/cargo/registry` but other systems might be different. Ideally we'd map it to a virtual path like `$CARGO_REGISTRY` and put the logic of "where is `$CARGO_REGISTRY`" into the system debugger itself.

**Comment by chemsaf3** [comment]
these also look blocking

https://github.com/rust-lang/rust/issues/40374
https://github.com/rust-lang/rust/issues/40552
https://github.com/rust-lang/rust/issues/75263

**Comment by sundeep-kokkonda** [comment]
https://github.com/rust-lang/rust/issues/102299

**Comment by sundeep-kokkonda** [comment]
> 

@alexcrichton How can I make rust builds are reproducible? can you let me the procedure that you know or can u guide me?. The reproducible issue I faced is reported here https://github.com/rust-lang/rust/issues/102299

**Comment by epage** [comment]
We also have rust-lang/rust#111540 which might help
