### ISSUE TITLE
Cargo does not recompile dependencies when running a module.

### ISSUE THREAD

**Issue by c-edw** [rust-lang/cargo#5511]
I just updated nightly `rustc`, ran `cargo clippy`, and got a runtime error from it. No dependencies were recompiled.
Then I ran `cargo check`, which recompiled all dependencies as expected after updating `rustc`. 
Then I ran `cargo clippy` and it exited successfully.

**Comment by sfackler** [comment]
`cargo clippy` just calls the `cargo-clippy` binary without doing anything else. You'll want to file this issue with the Clippy people.

**Comment by c-edw** [comment]
@sfackler This is why I have raised the issue. I think running `cargo` with any subcommand should check/recompile dependencies if needed.

**Comment by sfackler** [comment]
How would it know if that’s needed or not?

**Comment by c-edw** [comment]
In the same way it does already. If you run `cargo` with a built-in subcommand, it will automatically detect whether it needs to recompile.

**Comment by sfackler** [comment]
It understands built in subcommands because they're built in! Does `cargo foo` need a lockfile? A full build? A full build with tests? A full build with benchmarks? Nothing?

**Comment by alexcrichton** [comment]
Thanks for the report! As @sfackler said though this sounds like a clippy issue, so I'm going to close this.
