### ISSUE TITLE
Cargo Overrides and/or Cargo checking out project at a specific hash doesn't apply overrides

### ISSUE THREAD

**Issue by valarauca** [rust-lang/cargo#5521]
I'm dealing with a mismatch between a `[patch]`, and what is specified in a project's `Cargo.toml`

Either `cargo` is failing to apply `[patch]`, or `cargo` is failing to read the `Cargo.toml` that the project advertised when its checked out at a specific SHA.

---

I have a Cargo.toml similar to:

```
[dependence]
prometheus = { git = "https://github.com/pingcap/ruts-prometheus", rev = "62cce436c5f07a6d67fb00b1ef21d7a970ff1e92" }


[patch.crates-io]
protobuffer = { git = "https://github.com/stepancheg/rust-protobuf", rev = "51f50f/*etc*/", features = ["with-bytes"]}
```

Now `prometheus` needs `protobuffer`, but its [`62cce436c5f07a6d67fb00b1ef21d7a970ff1e92`](https://github.com/pingcap/rust-prometheus/blob/62cce436c5f07a6d67fb00b1ef21d7a970ff1e92/Cargo.toml) points to `v1.4` which is what my `[patch]` attempts to enforce `v1.4.1` which seems like it would work.

But at build time I'll see `prometheus` does indeed checkout the `62cce436c5f07a6d67fb00b1ef21d7a970ff1e92` revision, but it then attempts to compile against the current head of `https://github.com/stepancheg/rust-protobuf` (`v1.6.1`) which causes trait mismatch errors (failing to build).

**Comment by alexcrichton** [comment]
Have you tried running `cargo update`? Using `[patch]` only *adds* a package to the crates.io registry (in a pseudo-fashion), so if `cargo update` isn't actually used to switch to the new package the project will continue using the older one

**Comment by valarauca** [comment]
Morning,

I did not run `cargo update`, but I was using `[patch.crates-io]` previously to patch other crates. I had never read the `Cargo.lock` as it was working, so I incorrected assumed it was working. 

Instead I deleted `Cargo.lock`, and preformed a `cargo clean`, as well as deleting `cargo`'s caches.

**Comment by alexcrichton** [comment]
Did that cause the new crates to be used as you expected?

**Comment by valarauca** [comment]
The deletions did not. 

The project still defaulted to the `v1.6.0`

---

The full chain of events was roughly

1. `[patch.crates-io]` was being used locally for sub-crates (items in the same workspace, i likely have the terminology wrong.
2. `Prometheus` was working as expected, the build was green.
2. part of the jenkins ci file will run `rustup update` as part of its initialization step. This issue did occur the after the release of `v1.26` so I guess I should state it here.
2. `Prometheus` downloaded `v1.6.1`, which the project was using `protobuf = "1.4.0"` so I believe `cargo ` is allowed to upgrade that `v1.6.1`(?), but I am unclear if `[patch` should apply in this scenario.
3. the build failed.

The initial troubleshooting was to update `Prometheus` to an exact git checkout which specified `v1.4.0`. When this failed, I nuked the caches within `$HOME/.cargo`, the project still was defaulting to `v1.6.1`.

At this stage I moved `prometheus` to my vendoring library, and manually edited the `Cargo.toml` to ensure it was using the information in `[patch.crates-io]`, and it made a member of the primary applications work space. The issue at this state was at least partially resolved.

**Comment by alexcrichton** [comment]
Hm if the `[patch]` pointed at version 1.6.0 then Cargo could still move to 1.6.1, yeah (not using the crate provided by `[patch]`). In that case I think this is expected still?

**Comment by valarauca** [comment]
the `[patch]` section is pointing to version `1.4.1`, but doing so via specifying the revision, not specifying `"=1.4.1"`.

Ultimately no version is declared, I was assuming `[patch]` was just replacing the dependency so the original arg would become the checkout hash.

**Comment by alexcrichton** [comment]
`[patch]` doesn't unconditionally replace the dependency, it simply adds to the specified source (in this case crates.io) the packages listed under it. Otherwise version resolution proceeds as normal

**Comment by valarauca** [comment]
So let me get this straight

1. `[patch]` specifying a specifying a git checkout doesn't enforce this requirement.
2. Even if `[patch]` includes version information it could still be optionally override because of the `^X.Y.Z` default behavior.

I guess I'll close this. Really disappointed these edge cases are poorly taught by the community.

**Comment by alexcrichton** [comment]
@valarauca oh if you've got suggestions about how to improve the documentation, please let us know! We're always more than willing to fix up bugs in the docs!

Otherwise if you don't want dependencies to change that's what a lock file is intended for, which is what we would recommend.
