### ISSUE TITLE
Unrecognized option: 'write-mode'

### ISSUE THREAD

**Issue by volzkzg** [rust-lang/cargo#5545]
I was trying to use write-mode configuration in my CI server. 

`cargo +nightly-2018-05-17 fmt -- --write-mode check
`

It turns out to be 
`Unrecognized option: 'write-mode'
`

I just installed a specific nightly version 2018-05-17 and install rustfmt by 
`rustup component add rustfmt-preview --toolchain nightly-2018-05-17
`

**Comment by sfackler** [comment]
cargo fmt is a subcommand provided by https://github.com/rust-lang-nursery/rustfmt. `--write-mode check` is now `--check`.

**Comment by volzkzg** [comment]
I tried --check now, it also says 
`Unrecognized option: 'check'
`

**Comment by csmoe** [comment]
it seems that the toolchain override shorthand invalidates the option.

**Comment by volzkzg** [comment]
@csmoe it turns out to be 
`cargo manifest failed.`
