### ISSUE TITLE
detect unstable rustc options and suggest the correct syntax

### ISSUE THREAD

**Issue by tanriol** [rust-lang/cargo#5546]
There are cases when a user is suggested to use an unstable `rustc` option (and the suggestion for `external-macro-backtrace` is even in the `rustc` output). However, if a user tries to add this option to his `cargo` command line, the error message just says that this flag is unknown.

It would be a good idea to output something like
```plain
note: option `external-macro-backtrace` is a `rustc` option, not a `cargo` one
note: to use it, prefix the `cargo` command line with `RUSTFLAGS="-Z external-macro-backtrace"`
```

**Comment by PoignardAzur** [comment]
I'd really like this feature too. I've been burned multiple times by this.
