### ISSUE TITLE
RUSTFLAGS="..." cargo .. should recompile std lib with flags enabled

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#5547]
This is required for `rust-san` to work properly, and also for enabling some more efficient algorithms in `std::simd` that require specific target features (`SSE4`, `AVX`, `NEON`, etc.). Adding `Iterator::is_sorted` would also benefit from `SSE4` and `AVX`. It currently does run-time feature detection but it could avoid that if `std` was compiled with the appropriate flags.

**Comment by Eh2406** [comment]
The current conversation is https://github.com/rust-lang/wg-cargo-std-aware/issues/43
If that conversation is not the right issue, then that is the new place to open an issue.
Closing for now, so as to unify the conversations.
