### ISSUE TITLE
Missing git init.templatedir causes deadlock on registry index

### ISSUE THREAD

**Issue by olivernn** [rust-lang/cargo#5551]
cargo version: cargo 1.26.0 (0e7c5a931 2018-04-06)

My git config init.templatedir points to a non existent directory.

In a cargo project directory running cargo build first fails with the following:

```
$ cargo build -vv
error: could not find '/home/oliver/.git_templates/' to stat: No such file or directory; class=Os (2); code=NotFound (-3)
```

Rerunning the same command will then block forever trying to acquire a lock on the registry index

```
$ cargo build -vv
    Blocking waiting for file lock on the registry index
```

This can be resolved only by manually deleting the index.

Failing because of the missing directory is fine (though I am curious as to why it needs it), but I think any locks should then be cleared up.

**Comment by alexcrichton** [comment]
Hm are you sure there's not another Cargo process running in the background? The locks used by Cargo are in theory guaranteed by the OS to get released whenever the process terminates

**Comment by olivernn** [comment]
I'm 99.9% sure there is no other cargo process running. I used `pgrep` to look for other `cargo` processes as my initial thought was that somehow the first `cargo build` was still running.

I'm on Ubuntu 18.04.

**Comment by alexcrichton** [comment]
Could you provide instructions to reproduce this?

**Comment by olivernn** [comment]
Hmm, I can't seem to recreate it now :(

Perhaps it was because it was the first time I was using cargo on a new machine. Let me try and spin up a VM and re-create it.

**Comment by olivernn** [comment]
I can recreate it on a brand new VM, i.e. never successfully run a cargo build before, these are the steps I took:

1. Set git init.templatedir to something that does not exist: `git config --global init.templatedir qwertyuiop`
2. Install rust: `curl https://sh.rustup.rs -sSf | sh`
3. Setup shell: `source $HOME/.cargo/env`
4. Clone an existing crate: `git clone https://github.com/olivernn/bump.git`
5. Try and build: `cd $CRATE && cargo build`

I don't _think_ there is anything special about that crate...

Interestingly I couldn't recreate by creating a _new_ crate, that worked as expected.

**Comment by olivernn** [comment]
So, trying with a different crate, [toml-rs](https://github.com/alexcrichton/toml-rs) I wasn't able to re-create. I got an error about the missing directory but no deadlock on subsequent tries. However, I _was_ able to re-create with [ripgrep](https://github.com/BurntSushi/ripgrep). The difference is I think the presence of the Cargo.lock file in the repository.

**Comment by alexcrichton** [comment]
Ok thanks for the info! I've also been able to recreate it with this `Dockerfile`:

```dockerfile
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y \
  git \
  curl \
  gcc
RUN curl https://sh.rustup.rs | sh -s -- -y
ENV PATH=/root/.cargo/bin:$PATH
RUN git config --global init.templatedir qwertyuiop
RUN git clone https://github.com/olivernn/bump.git
WORKDIR /bump
ENV RUST_LOG cargo=trace
RUN cargo build; cargo build
```

Looking at the `strace` looks it looks like Cargo is recursively locking the registry. The first lock succeeds and the second lock fails, spooky! I'm not actually sure why that's happening and would need to investigate.

**Comment by alexcrichton** [comment]
Managed to track it down! 

https://github.com/rust-lang/cargo/pull/5570

**Comment by bm-stschneider** [comment]
Bug seems to persist.
