### ISSUE TITLE
Add command line option to print URL/path/link to generated documentation

### ISSUE THREAD

**Issue by cpick** [rust-lang/cargo#5562]
I use `cargo doc --open` to generate/update docs and open them in a browser, but often I want to view them in a non-default browser.   Sometimes I want to use the viewer built into my IDE, sometimes I'm testing out a new browser, etc.

It would be nice if either `cargo doc` printed the URL/path/link to the newly generated docs when it was done (similar to how `cargo test` prints "Running target/debug/deps/foo"), or if a new option like `cargo doc --link`, `cargo doc --url`, etc could be added to do this.

If either of these sounds like a reasonable idea I could take a crack at putting a pull request together?

**Comment by alexcrichton** [comment]
Sounds like a reasonable idea to me!

**Comment by esteve** [comment]
@cpick I wasn't sure if you were working on this, so I've submitted #5592, which print the path to the generated docs. I hope I didn't step on your toes, if you already have started working on this I'm happy to withdraw my PR.

**Comment by cpick** [comment]
@esteve no I hadn't gotten to it, this is great!

**Comment by nic-hartley** [comment]
Any update on this? A `--path` like `rustup doc --path` would be very nice for people who use WSL, where none of the default browser commands work. `--open` will print the URL as part of the error message, but that only helps if you don't have something installed which might accept the command despite not actually showing a browser window. (e.g. I had to add a `www-browser` no-op script to get something else to work; luckily, it's no longer on my `$PATH`, so it didn't cause issues)

**Comment by kobenauf** [comment]
As someone who uses Windows/WSL2, it would be nice to have `rustup doc` work.  I can `export BROWSER=firefox.exe`, and then `rustup doc --std` opens firefox, but the browser is empty; no error, nothing in the URL bar.

From a bash window, if I run this:
```
firefox.exe file://///wsl$/Ubuntu/home/name_redacted/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html
```
... Firefox opens to the Rust documentation I want.  Could `rustup doc` potentially figure out that path and for WSL?

**Comment by janpaul123** [comment]
Simple workaround: `BROWSER=echo cargo doc --open`

**Comment by nic-hartley** [comment]
@janpaul123 Clever! Although to be clear I'd still like to have proper support; this is a wonderful hack but still a hack haha
