### ISSUE TITLE
Error in .gitignore

### ISSUE THREAD

**Issue by fprijate** [rust-lang/cargo#5582]
first line of .gitignore, created by cargo new,  should be
**target/** 

instead of 

**/target**

**Comment by matklad** [comment]
Hm, I think this is the intended behavior: with `/target`, we'll ignore the target dir only at the root of the project. With `target/`, any target dir anywhere will be ignored, so, for example, you won't be able to have `src/target/mod.rs`.

**Comment by dragonmaus** [comment]
Technically it should be /target/ , but either works.

**Comment by ehuss** [comment]
I'm going to close this as intended behavior.
