### ISSUE TITLE
Include more information about dependencies in Cargo metadata

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#5583]
See https://github.com/rust-lang/cargo/pull/5461 for the **reverted** attempt at that. Basically, `cargo metadata` prints not enough information about **resolved** dependencies.

The bits of info missing from `cargo metadata` are:

* Which dependency applies to which target: currently we can't distinguish between normal and dev deps   #3984, #4631
* What are the platform restrictions for a dep? #4632
* Which name are you supposed to put in `extern carate name`? This covers `-` to `_` translation, as well as Cargo.toml level renaming.

**Comment by matklad** [comment]
The current plan is to introduce a `TargetId` thing to allow to refer to a target to a package somehow, and then add *per-target* dependencies to resolve field of `cargo metadata`, as a map:

```
deps: {
  "bin foo": [ { "package_id": "bar", "name": "baz", "platform": "cfg(unix)" }]
}
```

**Comment by ehuss** [comment]
I'm going to close this as I believe it is finished.

* The resolve graph now includes `dep_kinds` which allows you to tell which kinds a dependency is used as.
* The `dep_kinds` array includes the "target" field which is the platform for the dependency.
* The `extern crate` name is resolve.nodes.deps.name which handles renaming.  One common point of confusion is that `name` is the *lib name*, with underscores, not the package name.
