### ISSUE TITLE
Support for installing from a text file?

### ISSUE THREAD

**Issue by alichtman** [rust-lang/cargo#5593]
It would be great if I could install a text file of cargo packages like this:

```shell
File Name: cargo_packages.txt
---

cargo-edit
cargo-watch
traffic
...
```
with this command.
```shell
cargo install -list cargo_packages.txt
```

A few alternatives for the option name I came up with were: `-train`, `-convoy`, `-file`, and `-stream`

**Comment by weihanglo** [comment]
Thanks for the proposal.

While we don't have such a feature at this moment, we can easily achieve the same result in your favorite shell: 

```bash
cat cargo_packages.txt | xargs cargo install
```

We're also looking forward to a complete solution to backup/restore installed binaries in #7732. So, close in favor of that.
