### ISSUE TITLE
Impossible (?) situation when publishing a crate using another crate which links a native library in a workspace

### ISSUE THREAD

**Issue by NoraCodes** [rust-lang/cargo#5594]
I'm unable to publish 0.3 of [iui](https://github.com/leotindall/libui-rs) because it depends on `ui-sys` which links the `ui` native library. However if I specify `ui-sys = "0.1.3"` in `Cargo.toml` for `iui` I get:

```
the package `ui-sys` links to the native library `ui`, but it conflicts with a previous package which links to `ui` as well:
package `ui-sys v0.1.3 (file:///home/leo/Projects/libui-rs/ui-sys)`

failed to select a version for `ui-sys` which could resolve this conflict
```

**Comment by ehuss** [comment]
I'm going to close as I believe this is now fixed (at least for this specific situation) in 1.37 via #7026.  Cargo used to unconditionally rebuild the workspace `Cargo.lock`, but now it only builds a minimal `Cargo.lock` if necessary.
