### ISSUE TITLE
`cargo run` kills child processes upon exit

### ISSUE THREAD

**Issue by kuviman** [rust-lang/cargo#5598]
Is this expected behaviour?

```rs
fn main() {
    std::process::Command::new("cmd").arg("/C").arg("start").arg("cmd.exe").spawn().unwrap();
    std::thread::sleep_ms(1000);
}
```

Running this with `cargo run` opens `cmd.exe` for only one second, but running directly via `target/release/project.exe` opens it forever.

**Comment by alexcrichton** [comment]
It's [currently intended](https://github.com/rust-lang/cargo/blob/5fc6eadc362e52c885a8cf24b924be53467fe65f/src/cargo/util/job.rs#L123-L152) that we kill all child processes. That was originally intended, however, so that ctrl-c on Cargo would behave the same way on Windows as it does on Unix by default (kill the process tree). I'm actually not sure why everything is killed on exit though. I *think* that's mainly because if a subprocess failed we want to be sure to clean up after it, but if everything was successful then leaking seems fine

**Comment by SiegeLord** [comment]
This breaks RustGnuplot on Windows. It spawns a persistent gnuplot process showing all the plots that is meant to outlive the spawning Rust program, but since cargo appears to kill everything, it closes all the plots. This works fine on Linux.

**Comment by Seeker14491** [comment]
Reading the linked code for the job object in Cargo, I see that in the job object destructor, processes are killed manually with the `kill_remaining()` method, and then the job object is configured to not kill anything. The stated reason for doing this is to be able to whitelist certain processes to outlive the job object.

If we want all running processes to keep running when cargo exits successfully, then all we would need to do is remove the call to the `kill_remaining()` method. I'd like to know why we went through the trouble of writing the whole `kill_remaining()` method to implement the whitelist approach though. Are there some processes that should always be killed when cargo exits, even on a successful exit?

**Comment by alexcrichton** [comment]
@Seeker14491 job objects were originally added to make ctrl-c work across platforms. On Unix ctrl-c kills the *process group*, not a single process, which means everything gets taken down. On Windows however only one process killed, and by using job objects we also guaranteed unix-like behavior of the whole group of processes being killed.

The initial implementation simply let the job object kill everything on Windows, even on success. This was a bug at the time and didn't really come up till much later (now). When implementing leaking processes it simply preserved the previous behavior, killing everything on all exits.

All that to say, no, there shouldn't be anything that Cargo should kill on successful exits. It should continue to kill everything on abnormal exits though!

**Comment by alexcrichton** [comment]
@Seeker14491 that sounds about right yeah! I don't know how we can configure Cargo to not kill `mspdbsrv.exe` on ctrl-c while still killing everything else on ctrl-c, but if it works it works! That's a relatively minor bug, though, and the main thing to fix I believe is to avoid killing anything on a normal exit.

**Comment by hlavaatch** [comment]
Could you also not kill processes on ctrl+c when `cargo run`, but send them the ctrl+c instead so that they can handle it themselves as intended?

**Comment by alexcrichton** [comment]
@hlavaatch idealy we would yeah! I unfortunately don't know how to personally do that myself though :(

**Comment by hlavaatch** [comment]
But I do! :)

What happens is Windows console sends ctrl-c to all processes associated with the given window.
Cargo has no handler so the default handles is used which kills everything.

There is a crate for handling ctrl-c called [ctrlc](https://crates.io/crates/ctrlc)
All that is needed is to install an no-op empty handler in cargo just prior launching the process that is run.
I have tested this fix and it works fine!
What I did exactly:

- added ctrlc crate to windows target dependencies in Cargo.toml under
```
[target.'cfg(windows)'.dependencies]
ctrlc = "3.1.1"
```
- added extern crate on top of cargo/ops/cargo_run.rs
```
#[cfg(target_os = "windows")]
extern crate ctrlc; 
```
- added a bit of code in run() in cargo/ops/cargo_run.rs that registers empty no-op ctrl-c handler just before the process launch:
```
    config.shell().status("Running", process.to_string())?;

    #[cfg(target_os="windows")]
    ctrlc::set_handler(move || {} )?;

    let result = process.exec_replace();
```
With this hack cargo run no longer interferes with the ctrl-c handling of the crate that is being run :)

**Comment by Seeker14491** [comment]
@hlavaatch could you create a new issue and link to it here?

**Comment by hlavaatch** [comment]
Found a perfect place for setting the handler, cargo/util/process_builder.rs, in windows specific variant of ProcessBuilder::exec_replace(), in fron of the sef.exec()
```
    /// On unix, executes the process using the unix syscall `execvp`, which will block this
    /// process, and will only return if there is an error. On windows this is a synonym for
    /// `exec`.
    #[cfg(windows)]
    pub fn exec_replace(&self) -> CargoResult<()> {
        ctrlc::set_handler(move || {} )?;  // <-- here!
        self.exec()
    }
```
