### ISSUE TITLE
Expose cached build script output in the json output

### ISSUE THREAD

**Issue by konstin** [rust-lang/cargo#5602]
Let's say I have a hello world app with the following `build.rs`:

```rust
fn main() {
    println!("cargo:rustc-cfg=foo");
}
```

Running `cargo build --quiet --message-format=json` on a cold cache yields the following output, containing the `cfg=foo` from the build script:

```
{"features":[],"filenames":["/home/konsti/build-script-json/target/debug/build/build-script-json-a721905d0b722f88/build-script-build"],"fresh":false,"package_id":"build-script-json 0.1.0 (path+file:///home/konsti/build-script-json)","profile":{"debug_assertions":true,"debuginfo":2,"opt_level":"0","overflow_checks":true,"test":false},"reason":"compiler-artifact","target":{"crate_types":["bin"],"kind":["custom-build"],"name":"build-script-build","src_path":"/home/konsti/build-script-json/build.rs"}}
{"cfgs":["foo"],"env":[],"linked_libs":[],"linked_paths":[],"package_id":"build-script-json 0.1.0 (path+file:///home/konsti/build-script-json)","reason":"build-script-executed"}
{"features":[],"filenames":["/home/konsti/build-script-json/target/debug/build-script-json"],"fresh":false,"package_id":"build-script-json 0.1.0 (path+file:///home/konsti/build-script-json)","profile":{"debug_assertions":true,"debuginfo":2,"opt_level":"0","overflow_checks":true,"test":false},"reason":"compiler-artifact","target":{"crate_types":["bin"],"kind":["bin"],"name":"build-script-json","src_path":"/home/konsti/build-script-json/src/main.rs"}}
```

Running the same command another time will omit the build script output:

```
{"features":[],"filenames":["/home/konsti/build-script-json/target/debug/build/build-script-json-a721905d0b722f88/build-script-build"],"fresh":true,"package_id":"build-script-json 0.1.0 (path+file:///home/konsti/build-script-json)","profile":{"debug_assertions":true,"debuginfo":2,"opt_level":"0","overflow_checks":true,"test":false},"reason":"compiler-artifact","target":{"crate_types":["bin"],"kind":["custom-build"],"name":"build-script-build","src_path":"/home/konsti/build-script-json/build.rs"}}
{"features":[],"filenames":["/home/konsti/build-script-json/target/debug/build-script-json"],"fresh":true,"package_id":"build-script-json 0.1.0 (path+file:///home/konsti/build-script-json)","profile":{"debug_assertions":true,"debuginfo":2,"opt_level":"0","overflow_checks":true,"test":false},"reason":"compiler-artifact","target":{"crate_types":["bin"],"kind":["bin"],"name":"build-script-json","src_path":"/home/konsti/build-script-json/src/main.rs"}}
```

While a file with the cached output exists, the path to this file not part of json output. That makes it impossible to determine which configuration is set from the json output without rebuilding each time.

For the real-world context: I want to package libraries build with [pyo3](https://github.com/PyO3/pyo3) and need the build script output to determine the python variant used.

**Comment by matklad** [comment]
Mentoring instructions: 

Cargo build is organized via work items. Each work item exists in two flavors: dirty and fresh. We print message in dirty case:

https://github.com/rust-lang/cargo/blob/cddf9add1fac47cf765c2e2bb8931751e8b59616/src/cargo/core/compiler/custom_build.rs#L338-L351

We should do it in fresh state as well: 

https://github.com/rust-lang/cargo/blob/cddf9add1fac47cf765c2e2bb8931751e8b59616/src/cargo/core/compiler/custom_build.rs#L360-L370

**Comment by matklad** [comment]
Note that we don't have a test even for fresh case!

So, the test should build the code twice and check that `build-script-executed` is present in both cases. See this commit for an example test: https://github.com/rust-lang/cargo/commit/9f6d798961b4e2a8adccb88b3ade58ff24fe444a#diff-076c1db94150296d69d70557d7bd01a0

**Comment by debris** [comment]
I'd like to work on this
