### ISSUE TITLE
Cargo shipped with Rust 1.0.0 can no longer update the index

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/cargo#5605]
```
$ cargo +1.0.0 build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [12] SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

A workaround is to update the index with a newer version of Cargo and then switch back to the older version to build. 

This doesn't affect me, but it might be a thing to note for backwards compatibility concerns.

**Comment by sfackler** [comment]
This appears to work just fine for me on x86_64 Linux - what OS are you running on?

My guess would be that this is due to GitHub dropping support for old TLS versions but the OpenSSL cargo links to from that era should be new enough.

**Comment by shepmaster** [comment]
> what OS are you running on?

Ah, yes, important information! macOS 10.13.5

> to GitHub dropping support for old TLS versions

That was my guess as well.

**Comment by alexcrichton** [comment]
Ah yeah I agree with @sfackler on the diagnosis here and there's not much we can do about it, so closing.
