### ISSUE TITLE
Dependencies in resolve section of cargo metadata ignore --features

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#5618]
Right now, if you have a crate like:
```toml
[package]
name = "foo"
version = "0.1.0"

[dependencies]
byteorder = { version = "1.0", optional = true }
libc = "0.2"

[features]
b = []
```
Now if you inspect the dependencies section of the foo crate in the packages section of cargo metadata you get:
```
$ cargo metadata --format-version 1 | jq  '.packages | map(select( .name == "foo")) | .[].dependencies | map(.name)'
[
  "byteorder",
  "libc"
]
```
And you do `cargo metadata | jq`, this will be the dependencies section of the foo crate inside the resolve section:
```
$ cargo metadata --format-version 1 | jq  '.resolve.nodes | map(select(.id | contains("foo"))) | .[].dependencies'
[
  "libc 0.2.42 (registry+https://github.com/rust-lang/crates.io-index)"
]
```
Now of course, byteorder is an optional dependency, so we need to turn on the feature. Let's turn it on:
```
$ cargo metadata --format-version 1 --features b | jq  '.resolve.nodes | map(select(.id | contains("foo"))) | .[].dependencies'
[
  "libc 0.2.42 (registry+https://github.com/rust-lang/crates.io-index)"
]
```
It still only lists libc. I think that's a bug, it should also list byteorder.

**Comment by matklad** [comment]
Hm, you pass `--features b`, but `b = []` and not `b = ["byteorder"]` in the Cargo.toml. Can this be the issue?

**Comment by est31** [comment]
Oh right I'm stupid. Sorry :)
