### ISSUE TITLE
Pass arguments to send to rustc

### ISSUE THREAD

**Issue by NateDogg1232** [rust-lang/cargo#5624]
There should be a way to pass arguments to the rustc compiler for the main.rs or other rust files when using `cargo build`. Maybe have it be configurable through the Cargo.toml file, or some other way. Either way, it would be useful. I'm trying to make my project debuggable using gdb by passing `-g` to rustc, but this is impossible to do through cargo.

**Comment by sfackler** [comment]
Debuginfo is already configurable through Cargo.toml: https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections

**Comment by matklad** [comment]
Yep, this is covered for the majority of cases by

1) configuring profile section in Cargo.toml (your use-case)
2) setting `RUSTFLAGS` env var: https://doc.rust-lang.org/cargo/reference/environment-variables.html
3) using `cargo rustc` instead of `cargo build`.
