### ISSUE TITLE
Cargo build fails: The server name or address could not be resolved

### ISSUE THREAD

**Issue by mcelayir** [rust-lang/cargo#5626]
Hi All,

when I run cargo build command, I get the following error.

hello-rust>cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
warning: spurious network error (2 tries remaining): failed to send request: The
 server name or address could not be resolved
; class=Os (2)
warning: spurious network error (1 tries remaining): failed to send request: The
 server name or address could not be resolved
; class=Os (2)
error: failed to load source for a dependency on `tokio-tungstenite`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to send request: The server name or address could not be resolved
; class=Os (2)

cargo version: cargo 1.26.0 (0e7c5a931 2018-04-06)
rustc version:  rustc 1.26.2 (594fb253c 2018-06-01)

I tried adding access from firewall but not worked. 

Could you please help me out?

**Comment by Eh2406** [comment]
Sorry no one got back to you sooner. What is your operating system? Do you use a proxy of some kind?

**Comment by dwijnand** [comment]
Optimistically closing on the assumption that this was just a spurious error.
