### ISSUE TITLE
Proper way to use rerun-if-env-changed?

### ISSUE THREAD

**Issue by eberkund** [rust-lang/cargo#5630]
What the proper way of using `rerun-if-env-changed`? I am using a library where I am trying to pass in an env var from my application `build.rs` using  `cargo:rustc-env` but the problem is the library which depends on the env var fails before it can be rerun. If set the env var prior or if I change the code around in the library then it can compile fine. Just not sure what the intended use case is.

**Comment by Eh2406** [comment]
I am sorry, I don't quite understand the problem you are hitting. Can you post a minimal reproducible example? Then maybe we can figure out if `rerun-if-env-changed` is relevant, and how to improve its documentation.

**Comment by eberkund** [comment]
Okay, well this is the 3rd party package which I was talking about: https://github.com/pedrosland/mmal-sys/blob/master/build.rs

The libs are not located in the default path [it panics](https://github.com/pedrosland/mmal-sys/blob/master/build.rs#L94) which means it never gets to be rerun since the build stops on a panic.

So I was wondering what is the proper way to communicate this error (not being able to find the libs) while also maintaining compatibility with overriding and rerunning the build script?

**Comment by ishitatsuyuki** [comment]
See also: https://github.com/rust-lang/rfcs/pull/2391

**Comment by Eh2406** [comment]
So let me see if I understand. Your code depends on `mmal-sys`. `mmal-sys` uses `env:MMAL_INCLUDE_DIR` and panics if not set correctly. So you want to set `env:MMAL_INCLUDE_DIR` to the correct value in your `build.rs` and then have `mmal-sys` see the value you set. However this is not working, as your `build.rs` only gets run after your dependencies are built, and `mmal-sys` panics leading to your `build.rs` never being run to fix the `env:MMAL_INCLUDE_DIR`. Do I understand correctly?

**Comment by eberkund** [comment]
@Eh2406 That is exactly correct.

**Comment by Eh2406** [comment]
I don't think a `build.rs` can affect the environment for its dependencies. But I am not an expert on this part of the code. @alexcrichton, @jsgf, @matklad Am I correct about this?

If you are building a final artifact than you may need to have a build system around cargo to set the `env` before the build starts. 
If you are building a library you may want to document that the `env` needs to be set up for your dependencies.
Alternatively if you think it is widely usable you could make a PR to mmal-sys to make it better at finding the correct value.

**Comment by alexcrichton** [comment]
@Eh2406 you are indeed correct! This is something that'll need to be set by an outer build system rather than a crate

**Comment by eberkund** [comment]
Okay, thank you for the info everyone.
