### ISSUE TITLE
Cargo execution timing is wrong

### ISSUE THREAD

**Issue by Ninjananas** [rust-lang/cargo#5631]
Hi !
I'm new to Rust and I wanted to try out the `cargo check` command. I launched it on an almost blank project, and cargo tells me : 
`Finished dev [unoptimized + debuginfo] target(s) in 0.9 secs`
The problem is that it finished way faster than in 0.9 secs. I tried launching several times the same command, and I sometimes get the output : 
`Finished dev [unoptimized + debuginfo] target(s) in 0.10 secs`
I think that cargo tries to tell me that the ckecking took 0.09 secs, but the time displayed is clearly wrong.

```
> cargo --version
cargo 0.21.0 (5b4b8b2ae 2017-08-12)
```

I hope I could help, even if this is a very minor issue.

**Comment by matklad** [comment]
@Ninjananas could you check if this bug is present in nightly version of Cargo? If you use `rustup`, run `rustup toolchain add nightly`, and then use `cargo +nightly check`. I think this should be fixed by https://github.com/rust-lang/cargo/pull/5357

**Comment by Ninjananas** [comment]
@matklad This error is indeed fixed in the nightly version.

**Comment by matklad** [comment]
Great! Thanks for the report and verifying that the fix actually works!
