### ISSUE TITLE
cargo hangs for infinitely long time when Sublime is open

### ISSUE THREAD

**Issue by spease** [rust-lang/cargo#5633]
I have RLS running via the Sublime LSP plugin, and linting going. I can provide more detail where needed.

When I have Sublime open while running a build from the console, cargo will hang for (so far) an infinitely long time on the very last step (Compiling the crate itself, rather than its dependencies). `cargo -v` suggests that cargo is simply running the last rustc command. As soon as I close Sublime, cargo will finish.

This is distinct from when it is waiting for the lock (blue text).

I've tried rustup update, and building both with stable and nightly. RLS is presumably always being run from Sublime with the current nightly.

I'm sure this probably isn't enough to troubleshoot, so please let me know what additional data is needed.

**Comment by ehuss** [comment]
I haven't seen this, but I can try to help.  

* What OS and version are you on (windows, mac, linux)? 
* Are you using the latest version of the LSP  plugin (0.6)?
* Does it happen on any project, or is there something special about the project you are working on?
* Probably unlikely, but you might want to check if Sublime's indexing is interfering.  Make sure the `target` directory is excluded from your Sublime project (such as adding it to `folder_exclude_patterns` in your project settings).

**Comment by spease** [comment]
- Windows 10 Version 1803, rustc 1.28.0-nightly (1d4dbf488 2018-06-11) cargo 1.28.0-nightly (e2348c2db 2018-06-07)
- Yes, according to Package Control, v0.6.0
- Just started a new project with only duct as a dependency, and yes it does happen. It _might_ only happen when there are errors.
- Hmmm...I don't have a .sublime_project

I added target/** to binary_file_patterns in Sublime User preferences, and at least the first few times I haven't had any more trouble with it hanging.

I'd cautiously suggest it'd be nice if cargo could warn in this situation, although I don't know how big of a request that is. Assuming that was the issue.

**Comment by ehuss** [comment]
Hm, I've been trying to recreate it, but not having much luck.  It seems very strange that rustc would just hang.

Unfortunately I don't have any terribly good ideas.  Here are a few things to try:
* Enable `log_debug` and `log_stderr` in the LSP settings and see if anything interesting is displayed on the Sublime console.
* Try using something like [handle.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/handle) or [process monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to see if the rls or rustc processes are doing anything strange.
* Try using VSCode instead.  If it also has a problem, it might have better debugging options (I am unable to get Sublime LSP to work with the `RUST_LOG` environment variable set).  You can also check the [debugging](https://github.com/rust-lang-nursery/rls/blob/master/debugging.md) instructions.
* Try disabling any anti-virus or Windows Defender, which can often cause annoying issues.

**Comment by spease** [comment]
Commenting out rls in LSP stops the hang from occurring. Not sure if I’ll be able to try any of the other troubleshooting steps right now.

**Comment by ehuss** [comment]
Closing as there doesn't seem to be a reproduction here.  If there's a repro (preferably without needing to set up external tools), feel free to reopen.

**Comment by spease** [comment]
Thanks, this isn’t on my radar anymore anyway - I’ve switched to the CoC plugin
