### ISSUE TITLE
`crt-static` expects table in config, but docs says otherwise

### ISSUE THREAD

**Issue by petergarnaes** [rust-lang/cargo#5636]
Running on the latest stable version of rust (1.26.2) and cargo (1.26.0).

[In the example config file](https://github.com/rust-lang/rust/blob/1.26.2/config.toml.example#L386) the `crt-static` option is a boolean, but when I try to compile with the following config:
```
[build]

build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
crt-static = false
```
I get the following error:
```
error: expected a table, but found a boolean for `crt-static` in .cargo/config
```

How is the correct way to configure this? Is `crt-static` configuration described in any docs?

As a sidenote `target` is described [as an array](https://github.com/rust-lang/rust/blob/1.26.2/config.toml.example#L99) but required a string.

**Comment by ehuss** [comment]
The config file you are looking at is only for compiling the rust compiler itself.  Its options are much different from Cargo's `.cargo/config` file (which is documented [here](https://doc.rust-lang.org/cargo/reference/config.html)).

If you want to pass `crt-static`, I think you need to pass it in manually as a special flag.  For example, set the `RUSTFLAGS` environment variable to `"-C target-feature=+crt-static"` or use `cargo rustc` to pass custom flags to rustc.

AFAIK, target features are only really documented in `rustc --print target-features`.  `crt-static` was introduced in [RFC 1721](https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md) though I'm not sure how current the RFC text is.

**Comment by petergarnaes** [comment]
Thanks for your help! Sorry for my confusion...
