### ISSUE TITLE
Build scripts are difficult to run in a debugger

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#5637]
The output of Cargo has a path to the actual binary that is invoked every time a build script is run. That's useful, but there's not output showing all of the environment variables that are set that the build script may expect to be present. This makes it very difficult to launch the build script under a debugger and replicate the conditions of the Cargo build in order to investigate something that isn't working correctly.

**Comment by epage** [comment]
As of #12829, we now show the env variables as part of `-vv` so I think this is resolved.  If there is something I'm missing, let us know!
