### ISSUE TITLE
No new cargo release to go with rust-1.27.0

### ISSUE THREAD

**Issue by djc** [rust-lang/cargo#5646]
Both on crates.io and in the tags, there's been no new cargo release. Is that expected?

**Comment by Mark-Simulacrum** [comment]
Ah, I forgot to get @aturon to do this yesterday. I'll assign this to them.

**Comment by alexcrichton** [comment]
Should be done now!

**Comment by djc** [comment]
So the tag is 0.28.0, but the `--version` is 1.27.0. Which is the designated version number for this release?

**Comment by alexcrichton** [comment]
Cargo and Rust should not be packaged separately, the 0.28.0 is purely an internal version for Cargo. Cargo has a version in the same way that rustc and rustdoc have a version, they're all the same from the user's point of view. The Rust toolchain currently is at version 1.27.0 and includes rustc/cargo/rustdoc binaries.
