### ISSUE TITLE
Edition key should be per-target, not per-package

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#5661]
Possibly optionally?

**Comment by alexcrichton** [comment]
Seems plausible to me! That way existing crates could migrate one Target at a time instead of all at once

**Comment by alexcrichton** [comment]
@dtolnay your [exact PR to bitflags](https://github.com/bitflags/bitflags/pull/167) is actually what [@dwijnand's PR](https://github.com/rust-lang/cargo/pull/5816) is enabling.

"Targets" in Cargo are basically the same thing as "rustc invocations" or crates, so things like unit tests, libraries, binaries, examples, unit tests for librararies, etc, are all different targets.
