### ISSUE TITLE
cargo install doesn't follow workspace target

### ISSUE THREAD

**Issue by xzn** [rust-lang/cargo#5662]
I'm following this book here: [https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html)

and `cargo build` works as described. However `cargo install` doesn't work in the workspace level, and at crate level it tries to recompile the binary to a `target` folder within the crate folder instead of using the workspace level `target` folder.

`cargo build` from a workspace level also sometimes compiles things differently from `cargo install` from the crate. I was trying to compile [pijul](https://pijul.com/releases/pijul-0.10.0.tar.gz) on Windows earlier and while workspace level `cargo build` completes successfully, `cargo install pijul` (as well as `cargo install` from pijul crate) results in a bunch missing trait implementation errors.

In comparison `cargo run` doesn't have this problem as it uses the executables from workspace level target folder. (Although it'd be nice if `cargo run` can be used from workspace root directly instead of at crate folder)

**Comment by alexcrichton** [comment]
Hm can you describe a bit more precisely what you're executing with `cargo install`? The meaning of `cargo install` and `cargo install pijul` are very different which may be why you're seeing issues.

**Comment by xzn** [comment]
Sorry could've been more clear.

Using [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) as an example,

Executing `cargo build` at workspace root works as expected and binaries from `crates/cli` directory are compiled to workspace root target folder. Now let's say I want to install the binaries with `cargo install`, at workspace root level this doesn't work so I `cd` to `crates/cli` and run `cargo install` from there. The problem is that instead of using the the workspace root target folder, it creates and uses a target folder from `crates/cli` instead.

The expectation is that `cargo install` works like `cargo build` and `cargo run` etc and uses the target folder at workspace root level.

`cargo install pijul` is prolly a separate issue: basically running `cargo build` at workspace root of pijul source tree succeeds with binary being placed in workspace root target folder. Running `cargo install pijul` directly fails with some compilation error.

**Comment by ehuss** [comment]
This is caused by the change in #5350.  @matklad, would it make sense to revert that?  It's not clear to me why it changed.
