### ISSUE TITLE
Anyone can just edit the wiki

### ISSUE THREAD

**Issue by xd009642** [rust-lang/cargo#5668]
I'm not sure if this is deliberate, but I just added my project cargo-tarpaulin to the third party subcommands wiki expecting it to open a PR but it just changed it.

Just making sure this is ok/desired. After all less scrupulous people could potentially abuse this trust

**Comment by xd009642** [comment]
Just closing this cause I've found out you can't actually change this for a repo. Seems a strange decision from github but as there's nothing that can be done no use having an issue.

**Comment by Mark-Simulacrum** [comment]
We can change this -- as far as I can tell -- but I believe the current state is intentional.
