### ISSUE TITLE
`cargo test -- --logfile` should support common CI formats

### ISSUE THREAD

**Issue by lzybkr** [rust-lang/cargo#5670]
It would be useful if `cargo test -- --logfile` would write a file in a format supported by CI systems.

Based on [AppVeyor](https://www.appveyor.com/docs/running-tests/#uploading-xml-test-results) and [VSTS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-test-results?view=vsts), it looks like `junit` or `xunit3` could be good choices.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this has to do with libtest moreso than Cargo though in the rust-lang/rust repo, so want to move the issue over there?

**Comment by lzybkr** [comment]
Done. https://github.com/rust-lang/rust/issues/51924

It looks like json output is already available in nightly builds which might be helpful in the interim:

https://github.com/rust-lang/rust/pull/46450

**Comment by alexcrichton** [comment]
Ok! I'm gonna close this in favor of that issue
