### ISSUE TITLE
Full list of configuration options

### ISSUE THREAD

**Issue by gDelgado14** [rust-lang/cargo#5676]
In the rust book 2nd edition in chapter 14.1, the following is mentioned: 

> For the full list of configuration options and defaults for each profile, see Cargo’s documentation.

Which links to https://doc.rust-lang.org/cargo/

Even after looking through the table of contents on the left hand side, I was unable to find the "full list of configuration options". Is this an error on my part? Or is there really no full list of configuration options?

**Comment by alexcrichton** [comment]
I believe it's this page -- https://doc.rust-lang.org/cargo/reference/config.html

**Comment by steveklabnik** [comment]
And the manifest format page.

Cargo’s docs do need a lot of work; I wonder if we can make this more obvious.

**Comment by gDelgado14** [comment]
@alexcrichton I am new to Rust and can't say whether this is the right page that should be linked or not. However, I cross-reference the textbook content from chapter 14.1 (which makes mention of the `opt-level` config option), with the content in the link you reference. A quick "find" showed no results for `opt-level` ... so either that reference page needs to be extended or it may not be the right one!

**Comment by ehuss** [comment]
@gDelgado14 `opt-level` is part of the profile which is documented here: https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections

**Comment by ehuss** [comment]
It looks like this was resolved by https://github.com/rust-lang/book/pull/2066.
