### ISSUE TITLE
Turn cargo into a library-only crate, and move the binary part to rustc

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#5682]
I just noticed #5083 and have an alternative suggestion:

- Turn cargo into a library-only crate with an unstable 0.x version.
- Move cargo-the-binary into the rustc repo and share its stable 1.y version.

Now there is quite a lot of code in `src/bin` but that could be moved to `src/lib/bin` or something, so cargo-the-binary only has to be a very thin wrapper around it. (On second thoughts, perhaps it's better to simply move this to rustc so that the stability of it is easier to track and keep in line with rustc.)

The unstable cargo version should still be available on `cargo --version --verbose` though.

**Comment by infinity0** [comment]
I'd also very much support upgrading cargo-the-binary to a first-class part of rustc, i.e. keep it in `src` and not `src/tools` and remove all logic about installing it "optionally". After all the version numbers are the same now, they are logically part of the same package. It would also improve the bootstrapping situation for distros, since we then only have a single package that needs to be bootstrapped rather than two that depend on each other in a cycle.

**Comment by ehuss** [comment]
I think it is unlikely that we'll make a change like this, although perhaps I don't fully understand the motivation.  It doesn't seem to matter too much where the `fn main()` lives.
