### ISSUE TITLE
when reading a bad lock file give better error messages

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/cargo#5684]
When we read a lock file we make sure it makes sense and refuse to parse the file if it doesn't. This is the correct behavior but leads to not grate error messages. For example [this merge conflickt](https://www.reddit.com/r/rust/comments/8vzqp2/resolving_conflicts_on_cargolock/).

We should find some way to give better error messages, when the file is a valid `Toml` but does not make sense.

**Comment by alexcrichton** [comment]
Agreed! Ideally Cargo would just deal with merge markers in Cargo.lock, and the suggestion on that thread of "start from master and then re-resolve" is basically what Cargo would do and seems like a great strategy to me!

**Comment by Eh2406** [comment]
I was thinking something more modest. The lock file ([like this one](https://github.com/maccoda/mdBook/blob/5b65ac8e37dc1259083c160defb2ed0927c83c54/Cargo.lock)) that is in a inconsistent state (however it got that way) should lead good error message. As the existing is pretty bad.

```cmd
C:\test> cargo build
error: failed to parse lock file at: C:\test\Cargo.lock

To learn more, run the command again with --verbose.
```

the `--verbose` is slightly better,
```
C:\test> cargo build  --verbose
error: failed to parse lock file at: C:\test\Cargo.lock

Caused by:
  package `proc-macro2 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)` is specified as a dependency, but is missing from the package list

```
But it would be much better if it suggested `cargo update -p tempfile`

I think actually doing a merge would be a much bigger problem.

**Comment by alexcrichton** [comment]
Hm true! In any case it's hard to imagine a worse situation than we're in today with our current error messages :)

**Comment by alexcrichton** [comment]
Sure! I'll hold off on E-easy until there's instructions written up here, but if you're willing to do that I can certainly do the tagging!

**Comment by Eh2406** [comment]
Edited to be more `instruction` like. If you have advice on how to make them better LMK. I don't know how to convert a `--verbose` error to a normal error output, so I can't write the instructions on it.

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by Eh2406** [comment]
> Sounds good to me!

I was hoping you would write instructions for the part I don't know. ☹️

**Comment by alexcrichton** [comment]
Oh sorry! Typically making something non-verbose entails tracking down the call to `internal` that happens along the way and remove it, but I'm not sure offhand where that's happening. If there's a PR for the first pieces I can help track it down!
