### ISSUE TITLE
progress bar does not notice runtime window resizing

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#5696]
If I resized a terminal window while cargo is running, the progress bar does not take into account the new size and gives horrible output.
Is there a way to check the current window width before every writing of output?
![cargo](https://user-images.githubusercontent.com/476013/42418254-9301ffee-829c-11e8-8f07-c1f1951e5aee.png)

**Comment by alexcrichton** [comment]
I believe this is a dupe of https://github.com/rust-lang/cargo/issues/4732, but thanks for the report!
