### ISSUE TITLE
cargo --version reports something other than tag version

### ISSUE THREAD

**Issue by ilovezfs** [rust-lang/cargo#5699]
Is this intentional? Previously `cargo --version` matched the GitHub tag name. Now it seems to report something else, which I'm not quite sure how to interpret. For example, the 0.27.0 tag reports "1.26.0" and the 0.28.0 tag reports "1.27.0."

**Comment by alexcrichton** [comment]
Indeed this is intentional! The tag is an internal version for Cargo but otherwise `--version` is intended to match rustc itself

**Comment by ilovezfs** [comment]
@alexcrichton hmm ... OK, I'm glad to hear it's intentional. I'm not sure it works as expected, though. For the Homebrew formula it was reporting
```
iMac-TMP:~ joe$  /usr/local/Cellar/rust/1.27.0/bin/cargo --version
cargo 1.26.0
iMac-TMP:~ joe$  /usr/local/Cellar/rust/1.27.0/bin/rustc --version
rustc 1.27.0
```
up until today when I happened to bump cargo to 0.28.0 such that now it says
```
iMac-TMP:homebrew-core joe$ /usr/local/Cellar/rust/1.27.0/bin/cargo --version
cargo 1.27.0
iMac-TMP:homebrew-core joe$ /usr/local/Cellar/rust/1.27.0/bin/rustc --version
rustc 1.27.0
```

Why the initial divergence where it was saying 1.26.0?

**Comment by ilovezfs** [comment]
In particular, cargo 0.27.0 (before today) and cargo 0.28.0 (today) were both built with rustc 1.27.0 (or at least I think so!) due to

https://github.com/Homebrew/homebrew-core/blob/4b0f36382f73db6478a53bb5f9fd68feab4e4603/Formula/rust.rb#L98

**Comment by alexcrichton** [comment]
Oh how curious! Perhaps it's shenanigans with packaging in Homebrew? I'm not entirely sure how that all works out :(

**Comment by ilovezfs** [comment]
OK. I'll keep an eye on it. My guess is that the version is somehow hard coded as opposed to actually looked up from rustc's at build time. Thanks @alexcrichton

**Comment by ilovezfs** [comment]
@alexcrichton the mismatch issue also affects the version installed via rustup:
```
iMac-TMP:~ joe$ rustc --version
rustc 1.27.2 (58cc626de 2018-07-18)
iMac-TMP:~ joe$ cargo --version
cargo 1.27.0 (1e95190e5 2018-05-27)
```

**Comment by alexcrichton** [comment]
Yes point releases only affect rustc, not Cargo (Cargo hasn't needed a point release yet)

**Comment by ilovezfs** [comment]
Ah, OK. I'll watch out for divergence on non-point releases then! Thanks for the clarification.
