### ISSUE TITLE
Cargo can't find the package it just found

### ISSUE THREAD

**Issue by BatmanAoD** [rust-lang/cargo#5705]
I tried to install ion-shell directly from git, per the instructions in [the readme](https://github.com/redox-os/ion/blob/master/README.md).

The Ion repository apparently has two binaries. But when I tried to specify which one I wanted, Cargo couldn't find it:

    $> cargo +nightly install --git https://gitlab.redox-os.org/redox-os/ion/
        Updating git repository `https://gitlab.redox-os.org/redox-os/ion/`
    error: multiple packages with binaries found: ion-shell, ion-shell-fuzz
    $> cargo +nightly install --git https://gitlab.redox-os.org/redox-os/ion/ ion-shell
        Updating git repository `https://gitlab.redox-os.org/redox-os/ion/`
    error: could not find `ion-shell` in https://gitlab.redox-os.org/redox-os/ion/

Why does Cargo tell me that it found the `ion-shell` package, but then tell me it can't find it when I try to specify it?

**Comment by ehuss** [comment]
Which version of nightly are you using?  This should have been fixed by #5616, which has been part of nightly since 2018-06-29.

**Comment by BatmanAoD** [comment]
Ah, looks like it's 6-07. Updating now...

**Comment by BatmanAoD** [comment]
Okay, that seems to have resolved it. Thanks.
