### ISSUE TITLE
Fonts do not load in firefox when docs are accesed from a file url

### ISSUE THREAD

**Issue by jendrikw** [rust-lang/cargo#5706]
When using `cargo doc --open`, the docs are generated and placed in `target/doc` and the url `file:///path/to/project/target/doc/cratename/index.html` is opened in the default browser.
Due to CORS restrictions, Firefox does not allow pages from file urls to access fonts further up in the directory tree, so the fonts in `target/docs` are not loaded.

The docs then look like this: 
![image](https://user-images.githubusercontent.com/12938023/42538928-a0db5148-8499-11e8-8ec5-9751d46177dd.png)

I found some an archived artivel on MDN describing the policy: https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/Same-origin_policy_for_file:_URIs. When setting the key `security.fileuri.strict_origin_policy` to false, the fonts get loaded as expected.

A solution would have to change the directory structure of the output, or move the index.html one level up. I am not sure how documentation of workspaces is handled.

Debug info:
cargo 1.29.0-nightly (af9e40c26 2018-07-05)
Firefox 61.0.1

**Comment by alexcrichton** [comment]
Oh dear! cc @rust-lang/docs, y'all may be interested in this issue

**Comment by luser** [comment]
I filed this in the Rust repo a while back: https://github.com/rust-lang/rust/issues/34681

**Comment by ehuss** [comment]
I believe this is no longer an issue as of firefox [68.0.2](https://www.mozilla.org/en-US/firefox/68.0.2/releasenotes/).  Can anyone confirm if it is still a problem or should this be closed?

**Comment by luser** [comment]
This seems to work fine now in Firefox 69.

**Comment by luser** [comment]
For reference it looks like this behavior was changed in Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1565942, which landed in Firefox 69 and was backported to 68.0.2.

**Comment by ehuss** [comment]
Thanks @luser. 

I'll close this for now.  If there are any other problems, please file a new issue or comment on #4966 which would be the solution for most of these kinds of problems.
