### ISSUE TITLE
RFE: add option to specify path to Cargo.lock

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/cargo#5707]
In Fedora we package all crate sources (including tests) in `/usr/share/cargo/registry` which is not user-writable. However, we would like to run tests for them after installation. There is already option for `target-dir` and it would be very nice to get option to put Cargo.lock in some other directory so that we could run `cargo test` from there.

**Comment by ignatenkobrain** [comment]
@alexcrichton any idea how the option could be named? I'm thinking about making a patch.

**Comment by alexcrichton** [comment]
Perhaps `--lockfile-path` to mirror `--manifest-path`?

**Comment by epage** [comment]
We talked about this in the Cargo team meeting and are open to people experimenting with this
- CLI flag only, no config, no manifest support
- Name: `--lockfile-path <path>`
- Behind `-Zunstable-options` and docs
  - The flag's docs / `--help` should have `(unstable)` in them
- Looks like it belongs on all commands that take `--manifest-path` except `cargo locate-project`
- Must require the `file_name` be `Cargo.lock` (like we do for `--manifest-path`).  We can always re-evaluate this in the future
- Main question is how this should work if the lockfile or a parent directory is not present
  - I would lean towards "create them" rather than "error"

**Comment by Ifropc** [comment]
@epage sorry it took me some time, but the PR is ready for review.
I followed the guideline you posted in [your comment](https://github.com/rust-lang/cargo/issues/5707#issuecomment-2231276362) (thank you very much!)
1 slight difference is I haven't added `--lockfile-path` on `cargo install` yet, as it's not one of the command that takes the `--manifest-path`. 
I think the main usage of the `lockfile-path` is to enable folks to run commands on readonly folders (and adding it to almost all --`manifest-path` commands for consistency is a good idea). However, `cargo install` doesn't really fit into this category, so I doubt there's going to be any demand for that. 
That being sad, adding it is very easy (and to be completely honest I just completely missed your suggestion up until I opened the PR), so if you think it'd be a nice addition it's not a problem to add it to the set of supported commands.

**Comment by weihanglo** [comment]
@Ifropc No worry. As `--lockfile-path` is not going to be insta-stable, that seems fine to me. We can always discuss use cases later.

**Comment by weihanglo** [comment]
Most major tasks in https://github.com/rust-lang/cargo/issues/5707#issuecomment-2231276362 were addressed via #14326. Below are remaining tasks:

- [ ] `cargo install` should make `--lockfile-path` imply `--locked`
  - [#14326] didn't add `--lockfile-path` to `cargo-install`. This should be addressed before stabilization.
- [x] Main question is how this should work if the lockfile or a parent directory is not present
  - In [#14326], missing parent directories will be created when Cargo is about to write the lockfile. This minimizes the chance of creating dangling directories. 
- [ ] Shell completions.
  - May have conflicts with the [GSoC shell completion project](https://rust-lang.zulipchat.com/#narrow/stream/421156-gsoc/topic/Project.3A.20Move.20cargo.20shell.20completions.20to.20Rust).
- [ ] Feature gate tests.
  - We forgot to add those tests in [#14326].


[#14326]: https://github.com/rust-lang/cargo/pull/14326

**Comment by epage** [comment]
>  Main question is how this should work if the lockfile or a parent directory is not present 

Personally, I wouldn't make a checkbox for that.  That is enough of an open question that it should be carried forward to stabilization with a call out of what was chosen for the implementation.

> May have conflicts with the [GSoC shell completion project](https://rust-lang.zulipchat.com/#narrow/stream/421156-gsoc/topic/Project.3A.20Move.20cargo.20shell.20completions.20to.20Rust).

We should not be blocking completion work on that effort.  We'll likely have that start as a nightly-only opt-in so we can do acceptance testing on it.

**Comment by Ifropc** [comment]
Thanks for your reviews! I will do the follow ups for `cargo install` and tests in separate PRs. 
As for GSoC shell completion, from my understanding it's an ongoing effort, as of now. I don't see why would it be conflicting with the new flag, but if any help needed I would be happy to be involved!

**Comment by epage** [comment]
> As for GSoC shell completion, from my understanding it's an ongoing effort, as of now. I don't see why would it be conflicting with the new flag, but if any help needed I would be happy to be involved!

I believe the intent was to call out the potential for it being throwaway work which it would be if it was close to being merged *and* stabilized.  However, we do not know how close we are to stabilization until we merge and do a couple rounds of call-for-testing, so any completion work that is pending should still be done.

**Comment by weihanglo** [comment]
Close in favor of the tracking issue https://github.com/rust-lang/cargo/issues/14421
