### ISSUE TITLE
Do not cancel downloads behind proxy just because it is slow

### ISSUE THREAD

**Issue by lostiniceland** [rust-lang/cargo#5717]
```
PS C:\Dev\git\project> cargo build
 Downloading serde_json v1.0.11
warning: spurious network error (2 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 1705032704 seconds)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 1705032704 seconds)
error: unable to get packages from source
```

Our company proxy is also scanning the downloaded artefacts. While doing so, it still sends some data (5 bytes/sec), probably in order to keep the connection alive.
Cargo thinks this is to slow and stops with an error.

Can we have an option to ignore this check?

**Comment by alexcrichton** [comment]
You should be able to add global `.cargo/config` configuration like:

```toml
[http]
timeout = 1000000
```

would that work for your use case?

**Comment by lostiniceland** [comment]
Unfortunately not. I am already using a very long timeout.

The error message also does not appear after a certain amount of time(out). It is immediately appearing (I assume as soon as the connection is established). I've tried many things, including a local mirror of the crates.io-index. The index seems to be ok, since it is trying to download the first crate.

As said, and as others have reported, I guess it wouldnt be a problem if our proxy wouldn't send any data. But it does, which must trigger some exception in the cargo chain.

**Comment by alexcrichton** [comment]
Hm this may either be a bug in curl, the proxy, or a timeout in curl that we accidentally aren't configuring? I'm not entirely sure unfortunately :(

If you're using a super long timeout already though and it's failing quickly, then that probably means it's a bug in how we're telling curl about timeouts (maybe we're missing one?)

**Comment by lostiniceland** [comment]
Curl provides these two options

- https://curl.haxx.se/libcurl/c/curl_easy_setopt.html#CURLOPTLOWSPEEDLIMIT
- https://curl.haxx.se/libcurl/c/curl_easy_setopt.html#CURLOPTLOWSPEEDTIME

An option to override those would probably be enough. Or Cargo sets higher values if a proxy is configured.

**Comment by alexcrichton** [comment]
It looks like Cargo doesn't currently have the ability to overrides its configuration of [`low_speed_limit`](https://github.com/rust-lang/cargo/blob/9ab347d2203b924d303940df468748185a45eea1/src/cargo/ops/registry.rs#L370) and that may do the trick! (Providing the ability to override that)

**Comment by lostiniceland** [comment]
Thanks for providing the location. This is exactly our problem since the proxy only sends 5 bytes/sec.

I can try to work on a PR. 
Can I just replace my local cargo binary with an updated one for testing? Or is there a better way?

**Comment by alexcrichton** [comment]
Ah yeah a `cargo build` in this repository should produce another cargo binary and you should be able to use that one in-place instead of the already installed version

**Comment by lostiniceland** [comment]
Here´s how to reproduce the issue (adjust tc to your network adapter.

`sudo tc qdisc add dev eth0 handle 1: root htb default 11 && sudo tc class add dev eth0 parent 1: classid 1:1 htb rate 5bps && sudo tc class add dev eth0 parent 1:1 classid 1:11 htb rate 5bps`

to clear tc call 
`sudo tc qdisc del dev wlan1 root`

How to reproduce

- clear cargo download cache

- start a cargo build

- wait for the crate download to start

- execute the tc command to limit bandwith under 10bps

- note that the first connection fails with the low-speed...the next retry will timeout because the connection cannot be established quick enough

- clear tc
