### ISSUE TITLE
Build plan should more clearly distinguish custom build steps

### ISSUE THREAD

**Issue by luser** [rust-lang/cargo#5719]
Currently each build script in a build produces two invocations in the build plan--one to compile the build script, and one to run it. However, they both have `"target_kind": ["custom-build"]` so it's difficult to distinguish them when consuming a build plan.

In my [`cargo-build-plan-graph`](https://github.com/luser/cargo-build-plan-graph) tool I wound up [using a heuristic](https://github.com/luser/cargo-build-plan-graph/blob/ca55c7fad25021854ff219ce40223a6c7188b92a/add-timings.py#L49) that I do not love. It would be better if they had unique `target_kind` keys or some other straightforward way to distinguish them.

Here's [a sample build plan](https://gist.github.com/luser/1cb6c6577be3f984c8c371b5ccbadce1) from sccache.

**Comment by Mark-Simulacrum** [comment]
For now a better heuristic might be `endswith("build-script-build")`

**Comment by ehuss** [comment]
I think that would be `starts_with("build-script-")` since the user can change the name with the `build` key.

**Comment by Mark-Simulacrum** [comment]
Huh, I never thought about the `build` being user dependent; is that documented anywhere? It seems needlessly complicated...

**Comment by ehuss** [comment]
The key is documented in [build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) and the [manifest reference](https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field-optional).  It doesn't really talk about the binary/crate name of the build script, presumably because that's not something that's really relevant to most users.

**Comment by dwijnand** [comment]
Is changing the `target_kind` something we're happy to change in Cargo?  (post soft freeze)

**Comment by ehuss** [comment]
It might get complicated if something like #5855 is implemented.  Something like Doctest would appear with `target_kind=["lib"]` with no other distinction.  `target_kind` could be sort of a mix between `TargetKind` and `CompileMode`.  I'm trying to think if it would be better to keep them separate, but I can't think of a good one.

**Comment by ehuss** [comment]
cc #5508 which also discusses the problems with `target_kind` in the build-plan.
