### ISSUE TITLE
Configurable clean behavior

### ISSUE THREAD

**Issue by saneyuki** [rust-lang/cargo#572]
Cargo can configure `build` behavior to build non-rust code. Likewise, we should be able to configure `clean` behavior to clean up the items which are built by the customized build behavior.

**Comment by pornel** [comment]
:+1: 
In my build scripts I'm running 3rd party `make`, and I can't easily control where it puts temporary files, but it has `make clean` that cleans that up.

**Comment by WiSaGaN** [comment]
Since `build.rs` runs before `rustc`, a custom clean-up script which runs after current `cargo clean` would be nice to have.

**Comment by sehyoc** [comment]
This feature will be handy +1

**Comment by vext01** [comment]
I'm also looking for this feature.

In #5078 someone noted that:
>If you run the build in OUT_DIR, it'll be cleaned up via a cargo clean.

This might work for you as a workaround until this feature is implemented.

On a semi-related note, I'm starting to feel there are too many places where one can configure things related to cargo: `build.rs`, `Cargo.toml`, `config.toml`.

**Comment by seamlik** [comment]
This feature would be great for projects that incorporate code generators into their building process. Think about `wasm-bindgen`, or even a Rust version of GObject Introspection.

I suggest reopen it.

**Comment by brainstorm** [comment]
I would help as well for project that have a C binding library, like `rust-htslib`:

https://github.com/rust-bio/rust-htslib

Right now the submodule under `hts-sys` has to be cleaned with a `build.rs` "make clean", otherwise the crate does not reliably compile across separate runs:

https://github.com/rust-bio/rust-htslib/tree/master/hts-sys

**Comment by kairoswater-jason** [comment]
I need this for interoperability with a makefile based system to compile a C library. When `cargo clean` is called, I need to issue a `make clean` in the third party library's build system

**Comment by epage** [comment]
Not a fan of stale bot and glad we stopped using it.  However, I would have also proposed closing this if I had come across it.

First, I think it could be surprising for users to have cargo remove unconventional paths by convention.

Second, there is the question of how this would be done.  If we have to build something to see how to clean it, that feels off.  We could have a directive in `build.rs` and cargo stores this off in `target-dir` for what should be cleaned but that basically means anything can drop a path in that file to have it removed which feels icky to me (even though `build.rs` can do all of this on its own).

Third, most of the discussion has not been focused on the circumstances around why this is needed.  What are the problems with using `OUT_DIR` for this and why?  @kornelski mentioned third-party Makefiles without customizable build directories.  How often does that come up?  Does that justify a Cargo change or a patch to those tools?  Can it be upstreamed?  it seems allowing customizing of the location is a very useful tool. For example, we support that in Cargo!

**Comment by kairoswater-jason** [comment]
The only thing that is needed for third party build system integration is for for `build.rs` to define a function `fn on_clean()` and have cargo call `on_clean()` when `cargo clean` is issued (ie. it is up to the user to define the behavior, cargo does not know about external builds systems)

**Comment by kornelski** [comment]
My comment about Makefiles is so old, that Cargo still supported `build="sh make"` instead of `build.rs`.

There may be `Makefile`s that just dump compiled products into the same directory, but today I'd advise either copying everything to OUT_DIR to make a mess there, or replace the makefile with the `cc` crate.
