### ISSUE TITLE
Terminal color auto-detection no longer working with mintty (git-bash)

### ISSUE THREAD

**Issue by aloucks** [rust-lang/cargo#5724]
Color auto-detection isn't working for `mintty` (git-bash) shells. Running with `--color always` or using `winpty` does show color correctly. `Powershell` and `cmd.exe` seem to work fine as well. 

![image](https://user-images.githubusercontent.com/221559/42722630-5659b638-871d-11e8-8247-cd2d82e6d2f9.png)

Color detection was working fine until I just updated via rustup. The issue is not present in `beta`.

![image](https://user-images.githubusercontent.com/221559/42722723-2966abb6-871f-11e8-9cc2-47f64b16eb6f.png)

**Comment by ehuss** [comment]
Looks like the update to the winapi crate in the rust repo broke tty detection.  I have posted a fix at softprops/atty#28.  If that goes through, we'll need to wait for a new release, and then bump the lock file in the rust repo.

**Comment by alexcrichton** [comment]
Thanks for tracking this down @ehuss!
