### ISSUE TITLE
man pages are out of date

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5729]
Someone on IRC noticed that the cargo man pages are a little out of date or wrong.  In particular, `cargo-bench` documents a `--release` flag that does not exist.  Browsing through some of the other entries I see a few that are also out of date.  It might be worthwhile to review all of them and bring them up-to-date.

**Comment by ehuss** [comment]
Note: I'm preferring to wait and see what the wg-cli group comes up with.  They have a prototype that will generate man pages from the CLI help, so maybe we'll be able to use that.

**Comment by dwijnand** [comment]
Here's the upstream (clap) issue for auto-generating man pages: https://github.com/clap-rs/clap/issues/552
