### ISSUE TITLE
Should be able to selectively build/clean deps

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#573]
Especially when the deps are in-tree. For example, we should be able to run `cargo build script` and `cargo clean script` to only build/clean that dependency.

**Comment by icanrealizeum** [comment]
This is great: `cargo clean -p projectnamehere` cleans only the exe file, not the deps - so it saved me 1m23s of build time when using clippy like [so](https://github.com/Manishearth/rust-clippy#as-a-compiler-plugin)

**Comment by DrSensor** [comment]
It's unfortunate that there is no `cargo clean --no-deps` as `cargo metadata` have `--no-deps` flag. For now, I'm using this one-liner to clean only the exec and rlib file of my workspace:
```sh
cargo clean $(cargo metadata --no-deps --format-version=1 | jq -r '["-p" + " " + .packages[].name] | join(" ")')
```
