### ISSUE TITLE
Documentation: profile.XXX.debug can be u32 or bool 

### ISSUE THREAD

**Issue by enizor** [rust-lang/cargo#5734]
`profile.XXX.debug` is parsed as either an `u32` or a `bool` https://github.com/rust-lang/cargo/blob/558eee4fbca56bdc4969e114ed2cc4ed7c3913bb/src/cargo/core/profiles.rs#L349

The [documentation](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/manifest.md)
only show an `u32` in `profile.test`. It could be clearer to explain that both types are accepted.

As a result, `cargo-deb` only parses it as a `bool` (I will make a PR to fix this in a bit).

Something like this might do the trick?
```
debug = true       # (u32 or bool) Include debug information (debug symbols).
                   # Equivalent to`-C debuginfo=2` compiler flag.
```

**Comment by alexcrichton** [comment]
Sounds good to me!
