### ISSUE TITLE
cargo fix: Print targets/features/cfg that will be fixed

### ISSUE THREAD

**Issue by killercup** [rust-lang/cargo#5740]
With #5739, `cargo fix` learnt to check all targets by default. Since this might be a source of confusion, it would be helpful to also print out which targets we are fixing.

Running `cargo fix` should print out a line like this (right at the start):

> Collecting suggestions for these targets: library, `foo` (binary), and `bar` (example). No optional features enabled. No specific cfg flags given.

**Comment by killercup** [comment]
This might require changing/dealing with some cargo internals. There is this method:

https://github.com/rust-lang/cargo/blob/6a7672ef5344c1bb570610f2574250fbee932355/src/cargo/ops/cargo_compile.rs#L440-L448

as part of `ops::compile`, but it's not directly accessible in cargo-fix' entry function ([here](https://github.com/rust-lang/cargo/blob/6a7672ef5344c1bb570610f2574250fbee932355/src/cargo/ops/fix.rs#L39)).

**Comment by JoshBrudnak** [comment]
@killercup I would like to help out with this. Thanks.

**Comment by killercup** [comment]
@JoshBrudnak this is assigned to me to remind me to check in on this. How's it going? :)

**Comment by JoshBrudnak** [comment]
I haven't had much time to work on it, but I'll be able to look into it later today. Thanks. :+1:

**Comment by JoshBrudnak** [comment]
I guess I won't be working on this since @dwijnand took it. :smile:

**Comment by dwijnand** [comment]
There's an initial, starting implementation in #5947, but @alexcrichton is hoping to get a few more user reports to figure out what needs printing. See [his comment](https://github.com/rust-lang/cargo/pull/5947#issuecomment-417147253).

**Comment by dwijnand** [comment]
Move to close?

**Comment by alexcrichton** [comment]
Agreed yeah, we can always reopen if necessary!
