### ISSUE TITLE
test cleanup: Remove Cargo's internal `hamcrest` module

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5742]
This used to be an upstream crate and we switched due to it being outdated, and otherwise nowadays it's very much showing its age! We primarily use this module to assert various properties of each executed command, but nowadays we should stop using `hamcrest` in favor of a new form of specifying what should happen.

I'm personally partial to the system I made for `cargo-fix` the other day for a replacement which features:

* A [builder](https://github.com/rust-lang-nursery/rustfix/blob/116c7e9f7b666d92c049ab86c1d83e8ced1cead4/cargo-fix/tests/all/smoke.rs#L84-L93) style instead of a method-oriented style of building up a command
* By default asserts output status is 0 (unless otherwise specified)
* Lifts the awesome idea of supporting `foo("arg1 arg2 arg3")` instead of using `arg("arg1").arg("arg2")...`
* Has a [vastly simplified](https://github.com/rust-lang-nursery/rustfix/blob/116c7e9f7b666d92c049ab86c1d83e8ced1cead4/cargo-fix/tests/all/main.rs#L291-L320) method of matching output (avoids things like `[/]` and dealing with things like cwd changing)
* Was [relatively simple to implement](https://github.com/rust-lang-nursery/rustfix/blob/116c7e9f7b666d92c049ab86c1d83e8ced1cead4/cargo-fix/tests/all/main.rs#L122-L329)!

I think it'd be worth moving such a system into Cargo and migrating tests to use this assertion builder as well, I think it'd make assertions more concise and be a strong step forward to removing the `hamcrest` module.

**Comment by dwijnand** [comment]
💯 for removing the confusing `[/]` shenanigans!

Thus I've an interest in this issue, but I'll have to see if I'm able to do it.

**Comment by dwijnand** [comment]
> Lifts the awesome idea of supporting `foo("arg1 arg2 arg3")` instead of using `arg("arg1").arg("arg2")`...

Looks like @matklad took care of that a little while ago! 🎉

https://github.com/rust-lang/cargo/pull/5197

**Comment by dwijnand** [comment]
After #5942 the last remaining hamcrest usage is this kind of stuff:

```rust
    assert_that(&paths::root().join("src/lib.rs"), existing_file());
    assert_that(&paths::root().join("target/release"), existing_dir());
    assert_that(&project.bin("foo"), existing_file());
    assert_that(&res, contains(names(&["root", "foo", "bar", "baz"])));
    assert_that(&res, contains(names(&["root", "foo", "bar"])));
    assert_that(&res, is_not(contains(names(&[("util", "1.0.0")]))));
    assert_that(&res, is_not(contains(names(&[("util", "1.0.1")]))));
    assert_that(&res, is_not(contains(names(&[("util", "1.1.1")]))));
    assert_that(&res, is_not(contains(names(&[("util", "1.2.2")]))));
    assert_that(&t1, has_installed_exe("foo"));
    assert_that(&t2, has_installed_exe("foo"));
    assert_that(&t2, is_not(has_installed_exe("foo")));
    assert_that(&t3, has_installed_exe("foo"));
    assert_that(&t3, is_not(has_installed_exe("foo")));
    assert_that(&t4, has_installed_exe("foo"));
    assert_that(&t4, is_not(has_installed_exe("foo")));
    assert_that(&test.join("Cargo.toml"), is_not(existing_file()));
    assert_that(cargo_home(), has_installed_exe("bar"));
    assert_that(cargo_home(), has_installed_exe("foo"));
    assert_that(cargo_home(), has_installed_exe("foo_1"));
    assert_that(cargo_home(), has_installed_exe("foo_2"));
    assert_that(cargo_home(), is_not(has_installed_exe("bar")));
    assert_that(cargo_home(), is_not(has_installed_exe("foo")));
    assert_that(cargo_home(), is_not(has_installed_exe("foo_1")));
    assert_that(cargo_home(), is_not(has_installed_exe("foo_2")));
```

Any preferences on what to use in place of hamcrest?

**Comment by alexcrichton** [comment]
I'd probably just switch most of those just plain old `assert!` statements, no need to be too too fancy!
