### ISSUE TITLE
test cleanup: Remove the argument from the `project` function

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5746]
This argument can be "foo" 99.9% of the time, so let's remove it as an argument and simply hardcode it to `"foo"`!

**Comment by dwijnand** [comment]
Baited by the 99.9% I've started to take this on.

(Turns out it's more like 80%..

```
21:31:28 $ rg --stats 'project\("foo"\)' tests/ | tail -4
962 matched lines
66 files contained matches
85 files searched
0.005 seconds

21:31:38 $ rg --stats 'project\("' tests/ | tail -4
1208 matched lines
72 files contained matches
85 files searched
0.006 seconds
```

:smile:)

**Comment by alexcrichton** [comment]
Heh true! I think in basically all cases though it can be `"foo"` without breaking tests

**Comment by Mark-Simulacrum** [comment]
Sure, though some tests are specifically testing for things like `core` or `syntax` and making sure those work (i.e., lack of sysroot conflicts).

**Comment by dwijnand** [comment]
Yeah I had a look at the outliers and some deviate without a great reason, but there are a number of them that do have a good reason. Like workspace projects, or any kind of "foo" project and "bar" project.

Anyways, after landing the change to remove the argument from the project function, I'll follow it up with a more curated change to make them use the default "foo".
