### ISSUE TITLE
cargo doc: pass `--cap-lints allow` when documenting dependencies

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/cargo#5749]
When https://github.com/rust-lang/rust/pull/52354 lands, rustdoc will be able to accept `--cap-lints` to suppress lints when building documentation. Cargo should take advantage of this to pass `--cap-lints allow` when documenting dependencies, like how `cargo build` does the same. This will help contain the damage of https://github.com/rust-lang/rust/issues/51468 and errors like it.

**Comment by QuietMisdreavus** [comment]
Update: https://github.com/rust-lang/rust/pull/52354 has just landed.

**Comment by ehuss** [comment]
I have a patch ready, just waiting for a new nightly to be published.
