### ISSUE TITLE
How to find binary from integration test?

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#5758]
Is there a cleaner way to find a binary executable from an integration test other than looking at `current_exe()` and finding it from there?  Cargo itself uses this logic:

https://github.com/rust-lang/cargo/blob/848250597527659dd54b533c3d35d6505dd60a20/tests/testsuite/cargotest/support/mod.rs#L392-L409

I've seen others use `Command::new("./target/debug/NAME")` which can fail in some cases.

It seems like this should be easier.  Am I missing a better way?  If not, would it make sense to provide some method to more easily find binaries?

**Comment by alexcrichton** [comment]
The `if path.ends_with("deps")` is a compatibility hack for older Cargos, but otherwise that's AFAIK the "state of the art" in terms of being robust to future tweaks in Cargo as well.
