### ISSUE TITLE
UI nit: Progress bar partially overwritten by errors

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/cargo#5764]
cc #3448, #2536

When compilation terminates with an error, the progress bar is partially overwritten. Perhaps there is a missing `\n` that needs to be output before the first error?

Sample error:
```console
$ cargo +nightly check
    Checking x86_64 v0.2.4 (file:///home/mark/Documents/home/x86_64)                                                                                                                                                
error[E0573]: expected type, found module `self`==============>          ] 5/6: x86_64                                                                                                                              
   --> src/structures/paging/recursive.rs:354:14
    |
354 |         &mut self,
    |              ^^^^ did you mean `Self`?
```

Notice this part: `==============>          ] 5/6: x86_64`. This is the progress bar (I'm compiling the x86_64 crate), which is overwritten by the first error.

```console
$ cargo --version
cargo 1.27.0 (1e95190e5 2018-05-27)
```

**Comment by alexcrichton** [comment]
Thanks for the report! This has been [fixed in Cargo](https://github.com/rust-lang/cargo/pull/5698) for a bit now and thankfully we just got a nightly with the fix out, so we should be good to go!
