### ISSUE TITLE
Documentation question about handling DLLs for crates

### ISSUE THREAD

**Issue by fedor-rusak** [rust-lang/cargo#5769]
Hi everyone.

I am trying to simplify a task involving [GLFW3](http://www.glfw.org/) library usage on Windows. I don't want to force users to download windows libraries separately.

Is it possible to add some DLL file as part of crate? So that when I reference my helper-crate I get rust stuff and windows native stuff.

Maybe there is documentation for this?

Thank you,
Fedor

**Comment by alexcrichton** [comment]
You can publish binary files with your crate to crates.io, but Cargo doesn't have any sort of special support for this per se. You'd want to do detection in a build script to hook it into the build process.

Currently there's no documentation for something like this, but it seems plausible that such documentation could exist!

**Comment by fedor-rusak** [comment]
I guess this is not popular feature so I suggest to close this ticket for now.

Thanks for feedback. Have a nice day!
