### ISSUE TITLE
Why does rustc print so much verbose stuff ONLY when I run it in powershell (not in cmd.exe)? 

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#5776]
Why does rustc print so much verbose stuff ONLY when I run it in powershell (not in cmd.exe)? 

http://pastebin.centos.org/1064996/23211891/   

I don't have `RUST_LOG` set:
```
> Get-ChildItem Env:RUST_LOG
Get-ChildItem : Cannot find path 'RUST_LOG' because it does not exist.
At line:1 char:1
+ Get-ChildItem Env:RUST_LOG
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RUST_LOG:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

rustc 1.29.0-nightly (874dec25e 2018-07-21)

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like you're using `cargo web` here so this is likely a bug for that project. If it can be narrowed down to Cargo though please feel free to comment and I'll reopen!

**Comment by Boscop** [comment]
It also happens with every normal cargo build.
Here is an example that's not using cargo-web:
https://paste.rs/qJL
(Sorry that it's cut off, the whole output is 30mb, and for another build it's 371mb).

Can you please reopen this issue? :)

**Comment by alexcrichton** [comment]
That output looks like `RUST_LOG` is set for Cargo? Have you tried removing the env var?

**Comment by Boscop** [comment]
With `Remove-Variable`? It doesn't work because the var is not set:
```
> Remove-Variable RUST_LOG
Remove-Variable : Cannot find a variable with the name 'RUST_LOG'.
At line:1 char:1
+ Remove-Variable RUST_LOG
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RUST_LOG:String) [Remove-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand
```

Btw, I'm using the default Git-Shell (powershell) from GitHub Desktop for Windows.

**Comment by Boscop** [comment]
Btw, `gci env:` also doesn't list `RUST_LOG`, only
```
CARGO_HOME                     D:\Program Files\.multirust\cargo
[...]
RUST_BACKTRACE                 1
RUST_SRC_PATH                  D:\Program Files\.multirust\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src...
RUSTUP_HOME                    D:\Program Files\.multirust
```

**Comment by alexcrichton** [comment]
You may want to investigate how that env var can be getting set though? These log lines look exactly like the env var was set

**Comment by Boscop** [comment]
Yes, but how can I investigate this further? :)

**Comment by alexcrichton** [comment]
Sorry I don't know much about powershell/windows shells, and am pretty overloaded right now
