### ISSUE TITLE
cargo fix: Prevent fixing in mixed up transition steps

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#5778]
A common problem we're seeing in the 2018 transition is that steps are performed out of order, rendering `cargo fix` not too useful any more! I think we should implement two important fixes in `cargo fix` to remedy the situation:

* First, Cargo should be able to deduce a set of "interesting crates" which are actually being fixed. This is driven by the `-p` arguments on the command line.
* Next, if these crates have the 2018 edition enabled *and* `--prepare-for` is passed, then an error is generated. You can't prepare for an edition if you're already in the 2018 edition!
* And finally, if the crate is compiled but *doesn't* have `#![feature(rust_2018_preview)]` inside it then we should either warn or fail compilation.

This should hopefully fix the bugs of "you enabled the edition too early" or "you forgot to enable the feature gate"!

**Comment by alexcrichton** [comment]
cc @killercup

**Comment by johnthagen** [comment]
> Next, if these crates have the 2018 edition enabled and --prepare-for is passed, then an error is generated. You can't prepare for an edition if you're already in the 2018 edition!

Wanted to share anecdotal support for this feature. When I was doing a [transition of a crate](https://internals.rust-lang.org/t/help-test-out-the-2018-module-system-changes/8047/19?u=johnthagen), it was very natural to up-arrow in the terminal and pull down my first `cargo fix --prepare-for 2018 ...` command even after I added the edition to my `Cargo.toml`. I'd expect others to make this small mistake as well.

**Comment by alexcrichton** [comment]
Yes currently I'm not sure if we've got the best ergonomics. Another option would be to issue a warning and keep going (without the lint group), but that runs *more* risk of causing hundreds of errors I think than the annoyance of tweaking arguments.

**Comment by johnthagen** [comment]
Yeah, I feel like shooting for a "fail-fast" error in this case with a good message would be the best IMO.
