### ISSUE TITLE
The cargo reference should mention how to control number of jobs via env

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#5780]
The environment variables section of the cargo reference does not mention how to control the number of jobs for cargo via an environment variable. It should.

https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by zachlute** [comment]
There is a link at the bottom of the "Environment Variables Cargo reads" section that states:

>Note that Cargo will also read environment variables for .cargo/config configuration values, as described in that documentation

The documentation at that link says:

> Cargo can also be configured through environment variables in addition to the TOML syntax above. For each configuration key above of the form foo.bar the environment variable CARGO_FOO_BAR can also be used to define the value. For example the build.jobs key can also be defined by CARGO_BUILD_JOBS.

So I guess the question is, does it make sense to specifically call out things you'd commonly use as "Environment Variables Cargo reads" for more discoverability, or to remain consistent and have all of the config-override variables handled the same?

**Comment by zachlute** [comment]
#5690 appears to be asking for essentially the same thing, FWIW. It's clear there could be some improvement in discoverability here.
