### ISSUE TITLE
cargo fix prepare-for 2018 errors after due to 'async' identifier

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/cargo#5783]
I tried out `cargo fix --prepare-for 2018` on hyper, and after it ran, it showed an error and claimed it was a bug in cargo or rustc, and to report it here. There is an identifier currently named `async` in a file, here: https://github.com/hyperium/hyper/blob/069a32b1acc5ece35643c26cf5d9972dace5481c/src/body/body.rs#L268

In this specific case, it would have been fine to just renamed that binding to `async_`, or perhaps `r#async`. I'm not sure if trying to do that automatically would accidentally name `async` blocks or functions wrongly, though.

**Comment by Nemo157** [comment]
Just hit this right now with [`websocket::async`](https://docs.rs/websocket/0.20.3/websocket/async/index.html) as well. It seems doing an unconditional replacement to `r#async` should work, the lint should only be triggered on identifiers so won't affect `async fn`, and `async` blocks don't exist in 2015.

**Comment by alexcrichton** [comment]
Thanks for the report @seanmonstar and @Nemo157! 

It looks like this may be a bug in the lint and/or compiler. To confirm, if you place `#![feature(raw_identifiers)]` at the top of the crate, does the migration succeed?

If so, I'll fix this in rustc. If not, there's more digging to do!

**Comment by Nemo157** [comment]
@alexcrichton `#![feature(raw_identifiers)]` worked, it updated the import to `r#async` and `cargo fix` didn't report any errors.

**Comment by alexcrichton** [comment]
Ok great, thanks for checking @Nemo157!

**Comment by alexcrichton** [comment]
Ok the fixes are now in nightly and with @Nemo157's confirmation it worked I'm gonna close, we can always reopen if this comes up again though!
