### ISSUE TITLE
Allow setting `edition = "2018"` in a workspace

### ISSUE THREAD

**Issue by Centril** [rust-lang/cargo#5784]
For larger projects, it could be useful to set the edition once instead of in each project's `Cargo.toml` file. This would then be equivalent to setting the edition key in every member project in the workspace.

Currently, the edition key is ignored instead: https://github.com/rust-lang/cargo/pull/5726

See also: https://github.com/rust-lang-nursery/edition-guide/issues/45

**Comment by dwijnand** [comment]
Like #5661, but _less_ granular 🙂.

(I mention it also because one might want to tackle these in one swing.)

**Comment by lucksus** [comment]
Especially since `cargo fix --edition` updates every crate in the whole workspace.

**Comment by pksunkara** [comment]
With the new edition coming next year, we should look into implementing this. @ehuss Are there any blockers for this?

**Comment by ehuss** [comment]
I believe it is being implemented as part of #8664.

**Comment by futile** [comment]
#9684 seems to be the relevant PR now. Also bump, since the 2021 edition is coming up, and this could be relevant for migration.

**Comment by ehuss** [comment]
Yea, I think RFC 2906 is the solution to this.  There was a lot of discussion in RFC 2906 about whether or not workspace fields should be implicitly inherited, and it was decided that it is best to not make anything implicit, edition in particular. It looks like the edition field is already supported, so closing in favor of #8415.
