### ISSUE TITLE
How to `cargo clean` only a sub crate of a workspace?

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#5788]
How to `cargo clean` only a sub crate of a workspace?
I tried `cargo clean -p cratename` but it didn't work..

I wanted to run clippy on the subcrate without having to clean & rebuild the main crate because rebuilding takes hours. But clippy just said `Finished dev [optimized + debuginfo] target(s) in 7.01s` but it didn't say "compiling ...", so I want to clean only the sub crate.

**Comment by ehuss** [comment]
> I tried cargo clean -p cratename but it didn't work..

It should work.  Can you say more about what happened?

In particular for `check`, you should see this:
1. Notice `target/debug/deps/libNAME-*.rmeta` exists from previous `check` runs.
2. Run `cargo clean -p NAME`.
3. Check if `target/debug/deps/libNAME-*.rmeta` has been removed.
4. Running `cargo check -p NAME` should re-check the `NAME` package and regenerate the rmeta file.

**Comment by Boscop** [comment]
Why `check`? I'm talking about `clean` :)

**Comment by ehuss** [comment]
Oh...some reason my brain translated `clippy` to `check` (they use similar mechanisms underneath).  Just substitute the word "clippy" for "check", it's the same (they both generate rmeta files).

Are you using "cargo clippy" from the command-line?  Or maybe using the new integrated rls support?

**Comment by dwijnand** [comment]
The other way to rerun Clippy is to touch the lib.rs/main.rs of the crate.
