### ISSUE TITLE
workspace cargo build --bin [target] error

### ISSUE THREAD

**Issue by Bert-Proesmans** [rust-lang/cargo#5819]
Building a specific bin target with cargo from a workspace root does not work.

I tried this: 
- Have a cargo workspace with two library crates
- Both crates have autobins = false, but one crate has a manual [[bin]] entry
- Try to compile the specific bin from the workspace root; cargo build --bin [target]

I expected to see this happen: The binary target gets built.  
Because the test-subcommand works as expected..

Instead, this happened: error message  
-> error: no bin target named `[target]`

I'm using cargo 1.27.0 (1e95190e5 2018-05-27) - Stable toolchain

**Note:** 
`cargo build --bins` DOES work and compiles all binaries, effectively that one target binary.
changing work-directory into sub crate with bin and running `cargo build --bin [target]` DOES work and compiles the selected binary.

**Comment by ehuss** [comment]
Is it expected that without `-p` that specifying targets would work?  If there are multiple packages with a bin named "foo" and you ran `cargo build --bin foo` would it build all of them matching that name?  Similarly, `cargo build --lib` would skip any package without a lib?

**Comment by Bert-Proesmans** [comment]
@ehuss I deduced the expectation from the cargo help page about build. 
This expectation is similar to `cargo test [filter]` on virtual workspaces: compiles and executes all tests which have [filter] in their name. 

In my opinion clashes don't matter because there is no first-and-only expectation of the effect, contrary to the run subcommand.
Talking about the run-subcommand; it's not allowed to be executed on a virtual manifest. Clashes are avoided because a single crate is not expected to have multiple bin targets with the same name.
To be more in line with the run command disallowing `cargo build --bin` on a virtual manifest shouldn't be allowed either. Optionally tell the user to specify a specific package with `-p` within the error message. 
There is still `cargo build --bins` if building all bin targets becomes necessary.

Going forward i believe the following options are available. I leave it up for debate to make them mutually exclusive or not.
Note: I talk about these options in the context of executing them on a virtual manifest.

- Fix the current `build --bin` subcommand to correctly select matching targets from available ones
- Disallow usage of `build --bin` subcommand, just like `run --bin`

**Comment by alexcrichton** [comment]
@ehuss it's true yeah there can be conflicts, I'd imagine though we could do something like run the bin `foo` if there's only one and error if there's multiple (asking for `-p` to disambiguate). I agree with @Bert-Proesmans that it's a little inconsistent right now to accept `--bins` but not `--bin foo` (where we can)

**Comment by ehuss** [comment]
@alexcrichton if you want to assign this to me, I'll take a look at it soon.

**Comment by dwijnand** [comment]
You should be assignable now your on the team! 😁
