### ISSUE TITLE
crates-io version is 0.18.0 but max in https://crates.io/crates/crates-io is 0.16.0

### ISSUE THREAD

**Issue by donbright** [rust-lang/cargo#5821]
in Cargo.tml the crates-io version is 0.18.0

however the index https://github.com/rust-lang/crates.io-index/blob/master/cr/at/crates-io shows only 0.16.0 (as does crates.io)

this breaks 3rd party tool https://github.com/dhuseby/cargo-bootstrap

thanks

**Comment by alexcrichton** [comment]
Ah we don't publish what's on master, only when it hits the stable channel. Thanks for the report though!
