### ISSUE TITLE
It's hard to find options in the manifest reference doc

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#5822]
[The manifest documentation page](https://doc.rust-lang.org/cargo/reference/manifest.html) has grown rather large. 

To find documentation about particular section or property I have to search within the page, but that's not always convenient as the keywords are mentioned in many places.

Mdbook's table of contents isn't helpful either, because it only has a single entry for the whole page and doesn't break it down by section.

* Would it be possible to make table of contents more detailed? i.e. at least link to description of each section of the manifest, or ideally to every property?

* If not, could this page be split? e.g. package-related and workspace-related parts separately.

**Comment by dwijnand** [comment]
I think it's a relatively recent addition, though I'm not sure if it predates 28 Jul, but Cargo docs are now searchable (by virtue of mdbook having search functionality).

Does that resolve this issue sufficiently?

Though I'm not against splitting workspace-related parts into a dedicated page.

**Comment by kornelski** [comment]
mdbook searchability doesn't address this issue, because there still is one search results entry for the entire page with all of the sections, and clicking on the search result only goes to the top of the very long page.
