### ISSUE TITLE
cargo fix won't fix double-error of crate renamed to reserved identier

### ISSUE THREAD

**Issue by cramertj** [rust-lang/cargo#5827]
This is particularly pathological and might be to the point of "wontfix", but in fuchsia prior to edition 2018 we had a crate called "fuchsia_async" that we would commonly import as "extern crate fuchsia_async as async;", and could then use from other files in the same crate as "async::...". `cargo fix` fails on these examples. I'd expect it to do something like `async::T` -> `r#async::T` -> `crate::r#async::T`, but it just outputs a warning instead.

Note: this is with `#![feature(raw_identifiers, crate_in_paths)]`.

**Comment by alexcrichton** [comment]
Thanks for the report! This certainly isn't the only example of what we have to deal with here, there's also things like [`::local_path::<::LocalType>()`](https://github.com/rust-lang/cargo/issues/5797). A solution in `cargo fix` for this is being tracked at https://github.com/rust-lang/cargo/issues/5813, so I'm gonna close this in favor of that.
