### ISSUE TITLE
cargo fix with #![warn(rust_2018_idioms)] panics with: thread 'main' panicked at 'text to replace is empty', libcore\option.rs:989:5

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/cargo#5833]
I have a project that is panicking when `#![warn(rust_2018_idioms)]` is specified. `cargo check` succeeds so I am assuming this is a problem with `cargo` and not `rustc`.

Windows 10 x64
cargo 1.29.0-nightly (2cd36b4ed 2018-07-25)
rustc 1.29.0-nightly (866a71325 2018-07-29)

> $ RUST_BACKTRACE=1 cargo fix --allow-no-vcs
    Checking pathfinder-actix v0.1.0 (file:///C:/projects/test/pathfinder-actix-problem)
thread 'main' panicked at 'text to replace is empty', libcore\option.rs:989:5
stack backtrace:
   0: git_reference_type
   1: git_reference_type
   2: git_reference_type
   3: git_reference_type
   4: git_reference_type
   5: git_reference_type
   6: git_reference_type
   7: git_reference_type
   8: git_reference_type
   9: git_worktree_name
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: git_reference_type
  15: git_reference_type
  16: git_reference_type
  17: <unknown>
  18: git_openssl_set_locking
  19: BaseThreadInitThunk
  20: RtlUserThreadStart
error: Could not compile `pathfinder-actix`.
>
>To learn more, run the command again with --verbose.

I find it suspicious that the stack trace is hinting at git when there is no repo (in fact I removed my .git directory because of the above trace).
If I remove `#![warn(rust_2018_idioms)]` it succeeds.  A `cargo check` also succeeds and a subsequent `cargo fix` passes.

Project: 
[pathfinder-actix-problem.zip](https://github.com/rust-lang/cargo/files/2242610/pathfinder-actix-problem.zip)

**Comment by alexcrichton** [comment]
Thanks for the report! I've submitted a fix for this in https://github.com/rust-lang-nursery/rustfix/pull/139

**Comment by alexcrichton** [comment]
Ok the fix has been merged and we'll get this in nightly on the next Cargo update, hopefully happening soon!

**Comment by kjeremy** [comment]
Thanks @alexcrichton!
