### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/cargo#5839]
As an author of a cargo plugin, it's extremely hard to update to a newer cargo version, since changes are undocumented.

The only "solution" is to look up in commits history and git blame.

**Comment by RazrFalcon** [comment]
I see. I have to run the build process thought my plugin, so I need an access to the `core::compiler::Compilation` struct. And I'm not sure it's possible via `cargo metadata`.

**Comment by matklad** [comment]
@RazrFalcon yep, `metadata` won't help with `Compliation`. However  `cargo build --message-format=json` or `cargo +nightly build --build-plan -Z unstable-options` (currently unstable, https://doc.rust-lang.org/beta/cargo/reference/unstable.html#build-plan) might help

**Comment by RazrFalcon** [comment]
Will give it a try.

By the way, is this ok that json output is malformed?

**Comment by matklad** [comment]
No, it is not ok :) `--message-format` and `--build-plan` should have stdout as a series of newline separated JSON objects (we use that instead of a single array to allow streaming), and nothing else should be printed to stdout.

**Comment by RazrFalcon** [comment]
Oh, I see. Than it's fine.
