### ISSUE TITLE
`make` doesn't re-./configure as necessary

### ISSUE THREAD

**Issue by kballard** [rust-lang/cargo#587]
In rust-lang/rust, `make` will re-run `./configure` as necessary. It doesn't appear to do that in cargo. I just had an issue where `make && sudo make install` would spew "No such file" errors when copying build artifacts, fully reproducible after `make clean`, and it didn't go away until I manually re-ran `./configure`.

**Comment by steveklabnik** [comment]
Huh, this is interesting, I've always had the opposite expectation: why is Rust re-running configure when I didn't ask it to.
