### ISSUE TITLE
`cargo doc` / `cargo fmt` / `cargo test`'s docstrings fail to notice the `edition = "2018"` tag

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/cargo#5875]
(on latest nightly as of writing, from 2018-08-06)

When cloning and building https://github.com/Ekleog/erlust/commit/85e4bbb4974b541eb9e848eaf62f81613f5e1557, everything goes right.

When trying to `cargo doc`, `cargo fmt` or at the docstring stage of `cargo test`, though, I'm getting the following error message:
```
error: missing `fn`, `type`, or `const` for impl-item declaration
   --> […]/erlust/erlust/src/lib.rs:105:6
    |
105 |       }
    |  ______^
106 | |
107 | |     async fn send<M: Message>(&self, msg: Box<M>) -> Result<(), SendError> {
    | |____^ missing `fn`, `type`, or `const`
```

Which is the same error message as when trying to build without the `edition = "2018"` tag, so I assume that's the issue.

This appears to be unrelated with the workspace, as it reproduces with the inner crate copied into `/tmp` too.

Hope that helps make `cargo` better, and thank you for your work on cargo!

**Comment by ehuss** [comment]
Thanks for the report.  This looks like a problem with rustdoc.  I have filed an issue rust-lang/rust#53203 for this.

As for `cargo fmt`, I think you need to have a `rustfmt.toml` file that specifies the edition with `edition = "Edition2018"` (see https://github.com/rust-lang-nursery/rustfmt).

**Comment by Ekleog** [comment]
Indeed, thank you for `rustfmt`! Closing this in favor of https://github.com/rust-lang/rust/issues/53203 :)
