### ISSUE TITLE
Trying to install mdbook, fails with 'Couldn't resolve host static.crates.io'

### ISSUE THREAD

**Issue by PhilipDaniels** [rust-lang/cargo#5894]
Transcript below. This is on Linux Mint 18.3.

```
[phil:~/repos] 8m45s $ cargo install mdbook
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading mdbook v0.2.0
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: static.crates.io)                                                           
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: static.crates.io)                                                           
error: [6] Couldn't resolve host name (Could not resolve host: static.crates.io)                                                                                                         
[phil:~/repos] 8m50s $ ping static.crates.io
PING d19xqa3lc3clo8.cloudfront.net (13.32.67.146) 56(84) bytes of data.
64 bytes from server-13-32-67-146.lhr4.r.cloudfront.net (13.32.67.146): icmp_seq=1 ttl=245 time=17.1 ms
64 bytes from server-13-32-67-146.lhr4.r.cloudfront.net (13.32.67.146): icmp_seq=2 ttl=245 time=17.4 ms
64 bytes from server-13-32-67-146.lhr4.r.cloudfront.net (13.32.67.146): icmp_seq=3 ttl=245 time=15.9 ms
64 bytes from server-13-32-67-146.lhr4.r.cloudfront.net (13.32.67.146): icmp_seq=4 ttl=245 time=22.8 ms
^C
--- d19xqa3lc3clo8.cloudfront.net ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 15.925/18.333/22.830/2.657 ms
[phil:~/repos] 9m1s $ cargo --version
cargo 1.29.0-nightly (b42488270 2018-08-04)
[phil:~/repos] 9m4s $ 
```

**Comment by PhilipDaniels** [comment]
It's not transient, in fact if you look at the original post I did try pinging that host and it succeeded, but the cargo command failed. Since then I have rebooted and it still fails with the same error.

Interestingly, I have two Windows computers connected to the Internet via the same router, and installing mdbook in both Cygwin and WSL works fine. So it looks like something is screwed with the Linux mint installation? No idea what though.

**Comment by PhilipDaniels** [comment]
Further fact: cloning mdbook and building it manually using `cargo build` works fine.

**Comment by 10110111** [comment]
I have the same failure when trying to fetch dependencies like `getopt` while building `rustc-1.25.0` using BLFS instructions on Ubuntu 14.04.

The symptoms are the same: I can ping `static.crates.io`, but `cargo` fails to resolve the host. Interestingly, adding the `13.33.76.234 static.crates.io` to `/etc/hosts` works around the problem (the IP address was taken from `ping` output).

**Comment by PhilipDaniels** [comment]
Same thing occurs with `cargo install alacritty`.

**Comment by mati865** [comment]
Probably DNS issues, you can try using different DNS servers.

**Comment by Strum355** [comment]
Same issue on Arch, using 8.8.8.8

```
~  cargo install --git https://github.com/greshake/i3status-rust i3status-rs
    Updating git repository `https://github.com/greshake/i3status-rust`
  Installing i3status-rs v0.14.1 (https://github.com/greshake/i3status-rust#39fb0a11)
    Updating crates.io index
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: static.crates.io)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: static.crates.io)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: static.crates.io)
^C
~  dig +short static.crates.io
d19xqa3lc3clo8.cloudfront.net.
13.224.66.56
13.224.66.64
13.224.66.49
13.224.66.19
~  cargo version
cargo 1.44.0-nightly (390e8f245 2020-04-07)
```

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. Feel free to comment below or open a new issue if there is any update.

**Comment by mrkara** [comment]
@weihanglo I've just encountered the same error while building a package on Gitpod.

```
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: static.crates.io)
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
error: failed to download from `https://crates.io/api/v1/crates/borsh-derive/0.8.2/download`
```

**Comment by torabkheslat** [comment]
> @weihanglo I've just encountered the same error while building a package on Gitpod.
> 
> ```
> warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: static.crates.io)
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (1 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> warning: spurious network error (2 tries remaining): [7] Couldn't connect to server
> error: failed to download from `https://crates.io/api/v1/crates/borsh-derive/0.8.2/download`
> ```
> 
> Edit: It worked after a few tries. May be an intermittent networking issue?

It seems there is temporarily issue, add this line to `/etc/hosts`:
```
13.224.66.56 static.crates.io
```

**Comment by weihanglo** [comment]
Probably related to recent [CDN changes](https://blog.rust-lang.org/inside-rust/2023/01/24/content-delivery-networks.html)

See also https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Could.20not.20resolve.20host.3A.20static.2Ecrates.2Eio

**Comment by NickyAlan** [comment]
In my case open the HOSTS file, which is located at C:\Windows\System32\Drivers\etc, in notepad running as Administrator.
Adding this 1 line
`13.33.76.234 static.crates.io`
