### ISSUE TITLE
`cargo fix --edition` does not make the code compilable in rust 2018 if `uniform_paths` are enabled

### ISSUE THREAD

**Issue by orium** [rust-lang/cargo#5905]
Hi,

while testing `cargo fix` I believe I have found a bug:  When using `uniform_paths` `cargo fix --edition` does not migrate paths in `use`, and those will fail to build on rust 2018.

To reproduce create the following project:

`Cargo.toml`: 
```toml
[package]
name = "foobar"
version = "0.0.0"
authors = ["Foo <example@example.com>"]

[dependencies]
criterion = "0.2"
```

`src/lib.rs`:
```rust
#![allow(unused)]
#![feature(rust_2018_preview, uniform_paths)]
extern crate criterion;
use criterion::Criterion;
```

If you now run `cargo +nightly fix --edition` nothing will change, but the code is not compilable in rust 2018.  Change `Cargo.toml` to enable edition 2018 (by adding `cargo-features = ["edition"]` and `package.edition = "2018"`) and run `cargo +nightly build`:

```text
$ cargo +nightly build
[...]
error: `criterion` import is ambiguous
 --> src/lib.rs:4:5
  |
3 | extern crate criterion;
  | ----------------------- can refer to `self::criterion`
4 | use criterion::Criterion;
  |     ^^^^^^^^^ can refer to external crate `::criterion`
  |
  = help: write `::criterion` or `self::criterion` explicitly instead
  = note: relative `use` paths enabled by `#![feature(uniform_paths)]`
[...]
```

As this diagnostic suggests, `cargo +nightly fix --edition` should have changed line 4 to `use ::criterion::Criterion`.

**Comment by alexcrichton** [comment]
Thanks for the report! Currently not all suggestions in the compiler are marked as "machine applicable" which means that `cargo fix` will actually apply the fix. In that sense this is mostly an issue for upstream rust-lang/rust and related to https://github.com/rust-lang/rust/issues/50723

**Comment by orium** [comment]
rustc doesn't even emit a warning.  Opened issue rust-lang/rust#53797.

**Comment by alexcrichton** [comment]
Thanks! In that case I'll close this in favor of that
