### ISSUE TITLE
Using a crate of a binary (not library) as a dependency?

### ISSUE THREAD

**Issue by ks** [rust-lang/cargo#5938]
There's a bitcoin client in Rust, not on crates.io, I've installed with: 
```cargo install --git https://github.com/paritytech/parity-bitcoin pbtc```

I'm not interested in the resulting binary `pbtc`, but want to use it's code as a dependency.

Is that possible? Having my own main function outside of the pbtc repo, reusing the library parts?

If it's not possible to specify it in Cargo.toml, the only option I suppose is actually forking of the repo, correct?

**Comment by alexcrichton** [comment]
Thanks for the report! For Rust code you'll want to use the normal `[dependencies]` section for crate deps, does that work for you?

**Comment by ks** [comment]
Hmm, I understand from the cargo doc that it supports git repos as deps...
But how to deal with the fact it's not a library but produces a binary executable (has main.rs ...) ?

**Comment by alexcrichton** [comment]
Ah currently Rust crates can only depend on libraries, they can't depend on binaries

**Comment by ks** [comment]
Understood, thank you.
