### ISSUE TITLE
cargo rustc subcommand

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#595]
Thoughts?

```
Compile a package and all of its dependencies

Usage:
    cargo rustc [options] [<pkgid>] [--] [<opts>...]

Options:
    -h, --help              Print this message
    -j N, --jobs N          The number of jobs to run in parallel
    --features FEATURES     Features to compile for the package
    --no-default-features   Do not compile default features for the package
    -p, --profile PROFILE   The profile to compile for
    --target TRIPLE         Target triple which compiles will be for
    --manifest-path PATH    Path to the manifest to fetch depednencies for
    -v, --verbose           Use verbose output

The <pkgid> specified (defaults to the current package) will have all of its
dependencies compiled, and then the package itself will be compiled. This
command requires that a lockfile is available and dependencies have been
fetched.

All of the trailing arguments are passed through to the *final* rustc
invocation, not any of the dependencies.

Dependencies will not be recompiled if they do not need to be, but the package
specified will always be compiled. The compiler will receive a number of
arguments unconditionally such as --extern, -L, etc. Note that dependencies are
recompiled when the flags they're compiled with change, so it is not allowed to
manually compile a package's dependencies and then compile the package against
the artifacts just generated.
```

**Comment by zeonin** [comment]
I think this or something like it should happen.

Personally, I'm still waiting on a way to pass a linker script to the linker without writing a custom Makefile (and defeating a lot of the things that make cargo so nice to use). I'm still fairly new to rust/cargo, so I may be overlooking something. The problem I'm running into is that cargo is almost *too* high level for such a low level language.

**Comment by Manishearth** [comment]
This seems like what we want. So, `cargo rustc --foo` will internally call `rustc -lbar -lbaz --extern quux=.... -L target/foobar ....... --foo`?

As long as the usual link args are available I think we can make this work :)

**Comment by larsbergstrom** [comment]
We have worked around this for now by instead setting the linker to be a shell script that manually invokes everything we need.

**Comment by nwin** [comment]
Such a function would be really helpful. Otherwise it is almost impossible to use any rustc flag that is not exposed by cargo.

**Comment by RalfJung** [comment]
I've already found myself using the verbose flag of cargo to obtain the rustc call, and then alter its flags to obtain, e.g., the LLVM bytecode or similar. A command like this would make that much easier.

**Comment by larsbergstrom** [comment]
@RalfJung Rust team members have told me that they replace the rustc binary with a shell script that calls out to the binary itself in order to add extra arguments, as a workaround for this lack of functionality when debugging.

**Comment by RalfJung** [comment]
Thanks :) . A trick I already used on other occasions, but it's
certainly worth remembering that it also helps here.

**Comment by GBGamer** [comment]
Attempting to get better rust support into Emacs's Flycheck has really shown me the usefulness of this -- this would make my life much, much easier.

**Comment by mkpankov** [comment]
I concur with @GBGamer - this is something really useful for editors and IDE's, as well as some refactoring and analysis tools.

I'd like to see this implemented as it would enable Emacs' Flycheck to use cargo and properly handle dependencies.

**Comment by gsingh93** [comment]
+1, the sooner this gets implemented the better.

**Comment by alexcrichton** [comment]
Added in https://github.com/rust-lang/cargo/pull/1568, thanks @sondrele!
