### ISSUE TITLE
Target directory isolation/locking fails when cross-compiling

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#5968]
Usually, when multiple cargo builds are invoked in parallel, the build directory is locked, so they don't interfere with each other.

This locking doesn't work properly when cross-compiling, so two `cargo` processes running in parallel overwrite and delete each other's build scripts.

To reproduce, run two builds of a project that has some large build-time dependencies:

```sh
cargo build --release --target=x86_64-unknown-linux-gnu &
cargo build --release --target=aarch64-unknown-linux-gnu
```

(or same in `make -j2`)

One of the builds will intermittently fail, e.g. due to missing `build-script-build` file. I suspect it's because `target/$triple/release` dir is locked, but the host `target/release` is not.

Tested on Rust 1.28 on Linux

**Comment by alexcrichton** [comment]
Are you sure that the intermittent failure is related to Cargo? I made a dummy project with a build script that sleeps infinitely and built the project with two targets concurrently, and the second one makes no progress until the first one is killed.

**Comment by alexcrichton** [comment]
It may also be the case that file locking doesn't work on the filesystem perhaps? Cargo's file locking is opportunistic in that if the filesystem or platform doesn't support it then Cargo just skips locking internally.

**Comment by kornelski** [comment]
I see. This build was running in Docker, so perhaps the filesystem was to blame. Thanks for checking this.
