### ISSUE TITLE
`cargo new --edition 2018`?

### ISSUE THREAD

**Issue by japaric** [rust-lang/cargo#5980]
`cargo new` creates a new project for the 2015 edition. If you want to use the 2018 features like not having to type `extern crate foo` to be able to import `foo::bar` then you have to add this to your Cargo.toml:

``` toml
cargo-features = ["edition"]

[package]
edition = "2018"
# ..
```

Would it make sense to add an `--edition` flag to `cargo new` to indicate which edition the project will use? For example, `cargo new --edition 2018` would create a project with a Cargo.toml that includes `package.edition = "2018"`

Please avoid discussing whether `cargo new` should default to the 2018 edition. That's a separate issue and should be discussed separately.

**Comment by MggMuggins** [comment]
Does this flag in Cargo.toml change how your crate is used as a dependency? AKA, does specifying `edition = "2018"` mean that someone using a project with `edition = "2015"` or no edition use my crate as a dependency?

**Comment by ehuss** [comment]
@MggMuggins Dependencies will use the edition that they declare, regardless of the edition in your root package.  It should be safe to use 2018 dependencies in a 2015 package.
