### ISSUE TITLE
Specify crate-type by target in .cargo/config

### ISSUE THREAD

**Issue by prographo** [rust-lang/cargo#5996]
I believe I have found what I am looking for, a way of specifying the crate-type for a specific target.

In .cargo/config:

```
[target.aarch64-linux-android]
ar = "/pp/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/pp/NDK/arm64/bin/aarch64-linux-android-clang"
crate-type = "cdylib"
```

However:

```
cargo build --target aarch64-linux-android --release
error: expected a table, but found a string for `crate-type` in /pp/fast/fast-c/.cargo/config
```

Clearly it has been programmed to recognise crate-type, but how to specify correctly?

**Comment by prographo** [comment]
Please save me from these error messages:

warning: dropping unsupported crate type `cdylib` for target `x86_64-apple-ios`
warning: dropping unsupported crate type `cdylib` for target `i386-apple-ios`
etc.

I'm diagnosed OCD, error messages cause me physical pain.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/4881 as I believe it's a duplicate. Whiel it looks like Cargo recognizes `crate-type` it's actually thinking that `crate-type` is a [native library override](https://doc.rust-lang.org/stable/cargo/reference/build-scripts.html#overriding-build-scripts)
