### ISSUE TITLE
Running tests with elevated privileges

### ISSUE THREAD

**Issue by levex** [rust-lang/cargo#5999]
Hi all,

I work on [a crate](https://crates.io/crates/cgroups) for managing control groups under Linux and I'm trying to add some tests, however most of these tests require running with elevated privileges (read: sudo) because the kernel doesn't allow a normal user to modify the cgroup tree.

Unfortunately, simply running `sudo cargo test` results in `error: no default toolchain configured`.

I currently have three workarounds to this:

1) `sudo -E cargo test`, which keeps the normal user's environment but the effective user will still be the root user.
2) Manually run each generated test binary with `sudo target/debug/...`
3) I created [a script](https://github.com/levex/cgroups-rs/blob/master/tools/create_cgroup.sh)  that I run _manually_ before each test run to create the appropriate cgroups and use `chown`/`chmod` to give permissions to the user.

Now, neither of these solutions are "perfect" in my mind:

- The problem with the first approach is that I'd prefer to not have cargo run with elevated privileges.
- The second approach is quite cumbersome, but works reasonably well.
- The third approach is error-prone and (right now) requires that whenever I add a new test the script is re-run.

Finally, I see two solutions to this, one of which I have already implemented:

1) Add a new `--elevated` option to `cargo test` which executes the test binary under `sudo`. I have implemented this [here](https://github.com/levex/rust-lang-cargo/commit/93342b01d3b2714bc2b6c5c4394e414abb90e56b).

2) Add a new annotation to tests (i.e., `#[elevated]`) that automatically executes the tests under sudo. (Which would still ask for a password to confirm).

But maybe there is a better solution to this that I'm not aware of?

Thanks!

**Comment by alexcrichton** [comment]
Could `target.$target.runner` be used perhaps? That's a way you can specify an executable to wrap tests and you could probably get something like this working:

```toml
# in .cargo/config
[target.x86_64-unknown-linux-gnu]
runner = 'sudo -E'
```

and then in your project:

```
cargo test
```

**Comment by levex** [comment]
That's definitely a way more elegant solution than mine, thanks @alexcrichton !

**Comment by vityafx** [comment]
> Could `target.$target.runner` be used perhaps? That's a way you can specify an executable to wrap tests and you could probably get something like this working:
> 
> ```toml
> # in .cargo/config
> [target.x86_64-unknown-linux-gnu]
> runner = 'sudo -E'
> ```
> 
> and then in your project:
> 
> ```
> cargo test
> ```

I don't like the solution as it blindly enables the whole test suite to run with elevated privileges all the time. There should be a way to enable either certain tests to requires privileges or expect to fail when those aren't there or a much easier way to just run the tests manually that way. It shouldn't be harder to a user than just either `#[should_panic]` or `sudo cargo test`.

**Comment by lonok** [comment]
sudo -E /home/${USER}/.cargo/bin/cargo run

**Comment by sergey-somkov** [comment]
You can use environment variable instead of config file modification:
```
$ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='sudo -E' cargo test
```
About cargo environment variables: https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by AlexTMjugador** [comment]
For those poor souls on Windows, this wrapper command does the trick, although I couldn't get the test runner to not open a new window or keep it open after it finishes:

```toml
[target.'cfg(windows)']
runner = "powershell -Command Start-Process -Verb runAs -FilePath"
```

**Comment by Sytten** [comment]
I am trying to just run `sudo setcap 'cap_net_bind_service=+ep'` on the generated test binaries, if someone has an idea so I can keep using cargo test.

**Comment by Pr0methean** [comment]
> For those poor souls on Windows, this wrapper command does the trick, although I couldn't get the test runner to not open a new window or keep it open after it finishes:
> 
> [target.'cfg(windows)']
> runner = "powershell -Command Start-Process -Verb runAs -FilePath"
> Essentially, it mimics what the "Run as administrator" context menu option does.

Is there a way to do this for one specific test, with that one being run in a separate process, so that we can verify the other tests in the crate don't need the extra privilege? Also, is there a way to add only a specific capability, such as SeCreateSymbolicLinkPrivilege within `temp_dir()`, rather than blank-check admin powers?

**Comment by AlexTMjugador** [comment]
> Is there a way to do this for one specific test, with that one being run in a separate process, so that we can verify the other tests in the crate don't need the extra privilege? Also, is there a way to add only a specific capability, such as SeCreateSymbolicLinkPrivilege within `temp_dir()`, rather than blank-check admin powers?

For solving such specific needs today you'd probably need to either go with [a custom test harness](https://docs.rs/libtest-mimic/latest/libtest_mimic/), a more sophisticated wrapper command, or some mix of both ([the nextest per-test wrapper script feature](https://nexte.st/docs/configuration/wrapper-scripts/) looks quite handy here).
