### ISSUE TITLE
Ensure that readme file (from metadata) is included and path is mangled

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/cargo#6007]
Imagine that Cargo.toml contains `readme = "../README.md"`. This will work just fine for publishing, but that file doesn't end up in tarball which is distributed on crates.io (so distributions can't use it as documentation file).

**Comment by dwijnand** [comment]
Duplicate of #5911

**Comment by ignatenkobrain** [comment]
Indeed. Sorry for bad search!
