### ISSUE TITLE
Why changing building sequence can cause dependency error?

### ISSUE THREAD

**Issue by liufuyang** [rust-lang/cargo#6013]
I have a project were have two components, defined in a root Cargo.toml file in the same work space like this:
```
[workspace]

members = [
    "backend",
    "oauth2-rs"
]
```
--- 
Where the backend is a main runnable component, and the oauth2-rs is a local lib component. 
To help save build time on Docker, I have build file like this, let's all it version `A`:
```
FROM rustlang/rust:nightly-slim

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        pkg-config libssl-dev libcurl4-gnutls-dev libz-dev

# create a new empty shell project
WORKDIR /sm-webui
RUN USER=root cargo new --bin backend && \
  USER=root cargo new --lib oauth2-rs

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml
COPY ./backend/Cargo.toml ./backend/Cargo.toml
COPY ./oauth2-rs/Cargo.toml ./oauth2-rs/Cargo.toml

# this build step will allow cargo to download and compile all the dependencies
# this process might take a long time
RUN cargo build --release
RUN rm ./backend/src/*.rs
RUN rm ./oauth2-rs/src/*.rs

# copy your source tree
### when code upladed, this will be the starting point
COPY ./backend ./backend
COPY ./oauth2-rs ./oauth2-rs

# build for release. need to seperate the build process as backend requires oauth2
RUN cargo build --release
```
However,  doing this results in some weird dependency errors saying many things defined in `oauth2-rs` is not found, such as this error:
```
   Compiling backend v0.1.0 (file:///sm-webui/backend)
error[E0432]: unresolved import `self::oauth2::basic`
  --> backend/src/auth/mod.rs:11:19
   |
11 | use self::oauth2::basic::{BasicClient, BasicTokenType};
   |                   ^^^^^ Could not find `basic` in `oauth2`
```
But the project works locally.

I then tried to update the dockerfile to version `B`:
```
FROM rustlang/rust:nightly-slim

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        pkg-config libssl-dev libcurl4-gnutls-dev libz-dev

# create a new empty shell project
WORKDIR /sm-webui
RUN USER=root cargo new --bin backend && \
  USER=root cargo new --lib oauth2-rs

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml
COPY ./backend/Cargo.toml ./backend/Cargo.toml
COPY ./oauth2-rs ./oauth2-rs

# this build step will allow cargo to download and compile all the dependencies
# this process might take a long time
RUN cargo build --release
RUN rm ./backend/src/*.rs

# copy your source tree
### when code upladed, this will be the starting point
COPY ./backend ./backend

# build for release. need to seperate the build process as backend requires oauth2
RUN cargo build --release
```
However this time it can work? How could this happen? The only difference is that 
* the version `A`'s first time build, with fully configured Cargo.toml files but no `oauth2-rs` code.
* the version `B`'s first time build, with fully configured Cargo.toml files but also having `oauth2-rs` code.

Can some one give some help here? Could it be a bug?
----- 

here's backend's Cargo.toml and oauth2-rs's Cargo.toml
```
[package]
name = "backend"
version = "0.1.0"
authors = ["Fuyang Liu <fli@tradeshift.com>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"
hyper = "0.12"
tokio="0.1.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.3"
multipart = "0.15.2"
csv = "1"
indexmap = { version = "1.0.1", features = ["serde-1"] }
url = "1.7.1"
base64 = "0.9.2"

[dependencies.oauth2]
path = "../oauth2-rs"
```

```
[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Florin Lipan <florinlipan@gmail.com>", "David A. Ramos <ramos@cs.stanford.edu>"]
version = "2.0.0-alpha.2"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/ramosbugs/oauth2-rs"

[dependencies]
base64 = "0.9"
curl = "0.4.0"
failure = "0.1"
rand = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.0"

[dev-dependencies]
mockito = "0.8.2"
```

**Comment by ehuss** [comment]
I think the issue is that docker's COPY includes the metadata including the mtime.  After the first build, you copy in files with an mtime older than the first build, so Cargo does not believe any of the files have changed.

As to why it builds incorrectly in this case, the reason is...complicated.  In general, Cargo gets confused when the mtimes go backwards in time.  `oauth2-rs` is considered fresh (because the mtimes are older), but `backend` is rebuilt because it doesn't compare dependency fingerprints in the same way.  It ends up using the wrong (old) library and fails.

Personally I don't think backwards time-traveling files is worth fixing, but it is a little odd.

**Comment by liufuyang** [comment]
oh cool. Thanks for the reply. Nice to know, I agree there is no need for considering the backwards time-traveling. BTW, how do I see the mtime and where is the metadata you mentioned?  Is it on the file it self? 

Or if that is the case, perhaps I an simply add `Run touch oauth2-rs/src/*.rs` then it will work?

**Comment by liufuyang** [comment]
Nice. I tried to just touch that single file again after copy, and now the build can work. 

Cargo is nice. Thank you again for the answer :)
