### ISSUE TITLE
cargo fix renames unused local variables from foo to _foo

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/cargo#6023]
For example:

```
let device = &self.ctx.device;
let _device = &self.ctx.device;
```

I don't like that refactor because I might end up with local variables that do nothing. I think `cargo fix` should just ignore unused local variables all together.  If `cargo fix` just renames local variables to hide the warnings from the compiler, then the compiler lint is a bit pointless.

Renaming unused function parameters seems fine.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this may be best reported at rust-lang/rust though where the fix would live. Mind reopening the issue over there?

**Comment by MaikKlein** [comment]
@alexcrichton Sure no problem, I created a new issue https://github.com/rust-lang/rust/issues/54196
