### ISSUE TITLE
`cargo install` should read `$HOME/.cargo/config` only

### ISSUE THREAD

**Issue by traviscross** [rust-lang/cargo#6025]
The `cargo install` command should read configuration from `$HOME/.cargo/config` but not from other configuration files.

Normally cargo looks for configuration in `$PWD/.cargo/config`, `$PWD/../.cargo/config`, etc., and in `$HOME/.cargo/config`.  For `cargo install`, however, the tree walking behavior is surprising.  `cargo install foo` should work the same regardless of the directory from which we run it.

This surprising behavior resulted in #5850 and PR #5874.  That PR causes `cargo install` to ignore any configured `build.target` value from a configuration file.

However, that change does both too little and too much.  It does too much because we don't want to ignore configured values in `$HOME/.cargo/config`.  Values set there make sense for `cargo install`.  E.g., we might use that to set musl as our default build target.  On the other hand, the change does too little because we want to ignore all configuration values from `$PWD/(../)*/.cargo/config`, not just `build.target`.

The correct behavior is that `cargo install` should load only `$HOME/.cargo/config` and should apply all values found there.

cc @alexcrichton @japaric

**Comment by dwijnand** [comment]
The walking up the filesystem and looking in `~/.cargo` happens in:

https://github.com/rust-lang/cargo/blob/0.29.0/src/cargo/util/config.rs#L1553-L1582

**Comment by marcbowes** [comment]
How can you run `cargo install` with a source-replacement for crates.io after this change?

**Comment by alexcrichton** [comment]
@marcbowes I believe you should be able to configure via env vars or place configuration in $HOME

**Comment by marcbowes** [comment]
@alexcrichton the env vars don't allow you to do source replacement. https://doc.rust-lang.org/cargo/reference/config.html#environment-variables

> Environment variables will take precedent over TOML configuration, and currently only integer, boolean, and string keys are supported to be defined by environment variables. This means that source replacement, which is expressed by tables, cannot be configured through environment variables.

Moving configuration in $HOME is a global thing, i.e. it can create a mess that needs to be cleaned up, can be difficult to actually do (merge, undo) and prevents parallel installs with different config (e.g. registries).

Moving $HOME to a different folder temporarily breaks rustup. That can be worked around too, of course.

A much simpler option would be to have the config load from $CARGO_HOME as well as $HOME. Then I can just change $CARGO_HOME (and already do).

Alternatively, can we have an option or env var to switch out the root config?

**Comment by ehuss** [comment]
Would the change recommended in https://github.com/rust-lang/cargo/pull/6026#issuecomment-421519652 work?  It sounds like a good idea to me.
