### ISSUE TITLE
There is no way to pass a -L flag with a path that contains a white space

### ISSUE THREAD

**Issue by Jan-Ellmers** [rust-lang/cargo#6028]
Here 
    https://github.com/rust-lang/cargo/blob/a5d82949485802abb45f888d5b8b7f23927f031d/src/cargo/core/compiler/custom_build.rs#L497-L499

the flags get separated by white space so half of the path is interpreted as a new flag.

**Comment by alexcrichton** [comment]
Thanks for the report! You should be able to accomplish this in theory though with `println!("cargo:rustc-link-search=...`")` which can contain spaces. Does that work for you?

**Comment by alexcrichton** [comment]
Ok great!
