### ISSUE TITLE
Cargo doc --open no longer opens my default web browser

### ISSUE THREAD

**Issue by Neurrone** [rust-lang/cargo#6029]
I have firefox set as my default web browser, and using cargo doc --open hasn't worked to open documentation in it for quite some time now.

**Comment by dwijnand** [comment]
What platform are you on? Also could you give some indication on rust versions and/or channel you've seen this breakage?

**Comment by Neurrone** [comment]
Windows 10 1803 X64, rustc 1.30.0-nightly (90d36fb59 2018-09-13)

**Comment by ehuss** [comment]
I think this is due to rust-lang-nursery/rustup.rs#1493.  I feel like it is important to get that fixed before 1.30 hits stable.

**Comment by Seeker14491** [comment]
This is fixed in rustup 1.14.0, which was recently released.

**Comment by ehuss** [comment]
Thanks @Seeker14491!
