### ISSUE TITLE
Workspaces support for gitsubmodules

### ISSUE THREAD

**Issue by fulara** [rust-lang/cargo#6041]
Its just an idea.. or maybe even a question whether this is usable right now.

So.. workspaces are godlike, they are super good, but they have limitation of having the need to be on filesystem. this is both limitation and very practical.

However, sometimes i'd like my library which used to be a part of my project to become a completely separate entity.
Then I migrate that project to separate repo.
But my workflow remains the same, i want to work on these projects in similar fashion, workspace like fashion, where usually if i change project A then i change also project B, so it would be perfect to have these in workspace.

So.. the idea would be that i'd migrate that code to separate repo, but I would depend on that project in form of git submodule, pointing to a particular commit and dirty local changes.

Is something like that achievable? Do you even think that its good idea?

**Comment by ehuss** [comment]
The rustc compiler leverages git submodules (https://github.com/rust-lang/rust/tree/master/src/tools/) in a single workspace (https://github.com/rust-lang/rust/blob/master/src/Cargo.toml).  I warn you that it requires more ceremony compared to a single repo, so I think it only makes sense if you have multiple teams who want to work independently.  I'm not sure what your motivation is to move libraries to separate repos, though.

**Comment by fulara** [comment]
Thanks for answer, 
My motivation is as follows:
I start working on a project, lets call it Carrot. in that project i have library Leaf. 
With time the library Leaf grows to be an entity on its own, it provides such great functionality and is so independent that Leaf can stand on its own. People working on Leaf do not need to know anything about Carrot, the decision is to split Leaf to separate repo so it can live its own life, however Carrot still want to have path-system-like dependency on Leaf allowing for much easier and seamless work.

Another motivation is a reverse one. 
I start working on Carrot, but i am also working on a library that is now a separate repo. the work between Carrot and the Library is so close, that I want to have them on the same tree. Also this eases up debugging, workspaces are great for debugging, having symbols under one tree gives me access to everything.

Yes, I do know that you can use submodules for this, because its simply nothing but a path dependency but you need to invoke the `git submodule init`. However, I have not tested this, but can you depend on a library that has  workspace one of project in that workspace is a submodule? Will that work?
I am sorry but I didnt get to test it yet, I will :)

**Comment by ehuss** [comment]
I'm not sure if I understand your question.  Workspaces cannot be nested within the same directory tree.  You can reference packages from another workspace directly via path dependencies if they are outside your workspace tree (though I'm not sure if there will be any issues, that's a little strange to me).

**Comment by fulara** [comment]
Closing this, since I havent had the time recently to investigate further.
