### ISSUE TITLE
Publishing a crate is case-sensitive

### ISSUE THREAD

**Issue by jasonwilliams** [rust-lang/cargo#6043]
It's the first time i published a crate, so i followed https://doc.rust-lang.org/book/2018-edition/ch14-02-publishing-to-crates-io.html

It didn't mention that the name of your crate is case sensitive.
I ended up publishing `Boa` instead of `boa` and I didn't realised i made the mistake until it was too late.  It was only until after i published i noticed that most crates were lowercase.

Is there something we can do about this?

**Comment by joshtriplett** [comment]
By convention, we almost always use lowercase for crate names, so we should probably warn about this at some step in the process.

**Comment by epage** [comment]
Considering users should have gotten a warning from rustc
```
warning: crate `UPPERcase_name` should have a snake case name such as `uppercase_name`, #[warn(non_snake_case)] on by default
```

And we now have a warning from `cargo new` in #12766, I'm going to close this as resolved.  If there is a reason we should re-open this, let us know!
