### ISSUE TITLE
docker build hangs forever on cargo install

### ISSUE THREAD

**Issue by bgbahoue** [rust-lang/cargo#6044]
I am trying to build a Docker image using [Rust official image](https://docs.docker.com/samples/library/rust/) but it hangs forever on the `cargo install` command while it works fine when I run `cargo install` from a terminal.

I have seen a few old issues on this but none of the solutions that were listed then are working.

Anything I can do to solve this?

Output from `docker install -t <myapp> .` command

> Sending build context to Docker daemon   1.73MB
> Step 1/5 : FROM rust:1.23.0
>  ---> c694858c0c3c
> Step 2/5 : WORKDIR /usr/src/<myapp>
>  ---> Using cache
>  ---> 7af2b1e4af1f
> Step 3/5 : COPY . .
>  ---> Using cache
>  ---> a61f33cd9dd3
> Step 4/5 : RUN cargo install
>  ---> Running in c9c573188020
>   Installing <myapp> v0.1.0 (file:///usr/src/<myapp>)
>     Updating registry `https://github.com/rust-lang/crates.io-index`

**Comment by tbezemer** [comment]
@bgbahoue How did you resolve this issue? I am experiencing the same issue. For my project, it is very implausible that it would take a long time, since local build outside of Docker takes a few seconds.

**Comment by userxfce** [comment]
same on nightly toolchain 2025-01-24&25
