### ISSUE TITLE
Some rustdoc diagnostic colors are missing

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6045]
As of #5995, some error messages from rustdoc are no longer getting colored.

Example code:
```
/// [BadLink]
/// ```
/// \
/// ```
pub fn f() {}
```

The result I get on nightly:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/43198/45654873-71adb080-ba92-11e8-8a5f-d08a8f8307ad.png">

The result of cargo just before #5995:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/43198/45654894-8d18bb80-ba92-11e8-9cab-bc568612038c.png">

Notice that the `warning` emitted by rustdoc is still colored, but the `error: unknown start of token` line caused by the backslash is not!  So strange!

Tested on Windows and Mac.

cc @kennytm

**Comment by alexcrichton** [comment]
I believe the bug is [here](https://github.com/rust-lang/rust/blob/79fcc58b24d85743d025fd880fca55748662ed3e/src/librustdoc/test.rs#L91) where the CLI `--color` argument isn't passed to all locations it's needed

**Comment by ehuss** [comment]
I think for the particular example above is specifically related to tokenization for syntax highlighting which goes through this line: https://github.com/rust-lang/rust/blob/60c846046ec26c9e5c1216a6e118cc2e69a2956c/src/libsyntax/parse/mod.rs#L67

The test one probably seems more useful to fix, though, since tokenization errors should be rare.

**Comment by ehuss** [comment]
This is now mostly fixed by rust-lang/rust#56884
