### ISSUE TITLE
Make it easy to use `external-macro-backtrace`

### ISSUE THREAD

**Issue by dhardy** [rust-lang/cargo#6049]
Yes, stupid title, for a stupid issue. I know it was decided a while back not to support pass-through of unknown options to Rustc, which implies that Rustc options should be replicated in Cargo.

Currently, one must switch to the nightly compiler then can:

1.  `RUSTFLAGS="-Z external-macro-backtrace" cargo test` 
    This works (in Bash), but requires all dependencies to be recompiled (unnecessarily since the option is only required for the failing crate, generally the final one).
2.  Run `cargo test -v`, copy the failing command and append `-Z external-macro-backtrace` 
    This works but is tedious.

There are two ways to solve this:

1.  Enable the switch by default, everywhere (in nightly compilers). This would of course have to be a Rust decision not a Cargo one. See: https://github.com/rust-lang/rust/pull/45545
2.  Add a Cargo switch to add the appropriate Rustc switch (possibly only to the last binary).

**Comment by najamelan** [comment]
This might have to be a different issue, but I would like to add:
Print line numbers that correspond to the file where the macro is defined. Currently the line numbers don't match to anything I can make sense of, and I have to rely on recognizing the code in the expanded errors to find the actual error location.

**Comment by eddyb** [comment]
> Currently the line numbers don't match to anything I can make sense of, and I have to rely on recognizing the code in the expanded errors to find the actual error location.

This is due to how we serialize macros across crates, https://github.com/rust-lang/rust/pull/66364 should take care of that.

**Comment by epage** [comment]
#5546 is about discoverability of rustc `-Z` flags which was resolved in #12857.

Whats not clear to me is the benefit of duplicating `-Z` flags vs having people set them.   I'm going to propose to the cargo team that we close this.

> This works (in Bash), but requires all dependencies to be recompiled (unnecessarily since the option is only required for the failing crate, generally the final one).

This is the nature of RUSTFLAGS and improvements are being tracked in #8716 and #12739.

**Comment by weihanglo** [comment]
Generally, we don't easily duplicate `-Z` flag from rustc to cargo. Cargo would need to think at a higher level than rustc for the usability as a "build tool".

For now, if you want to apply rustflags only to the final binary, [`cargo rustc`] is the command to-go.

Second that we can close this as #12857 provides sufficient information to fix the human error.
