### ISSUE TITLE
unable to find local dependency with version x.y.z-dev

### ISSUE THREAD

**Issue by JeanMertz** [rust-lang/cargo#6051]
I've got [two crates in a repository](https://github.com/rusty-rockets/sm). One references the other. When I'm working, I've got both crate's `version` configuration set to `x.y.z-dev`, with`z` being one higher than the currently released version.

This does not work when building the crate:

```
$ cargo build
error: no matching package named `sm_macro` found
location searched: file:///Users/jean/code/sm/sm_macro
did you mean: sm_macro
required by package `sm v0.6.2-beta (file:///Users/jean/code/sm/sm)`
```

As soon as I change the crate versions from `x.y.z-dev` to `x.y.z`, again with `z` being a not-yet-released version, it works as expected.

The same happens when using anything other than `dev` after the dash. From my understanding, this is [valid SemVer syntax](https://semver.org/#spec-item-9), and in fact this is also what's used in the [`cargo-release`](https://github.com/sunng87/cargo-release) crate.

Is this a bug, or did I miss some part of the documentation that mentions that this is not how it's supposed to work?

**Comment by dvdplm** [comment]
We're seeing exactly the same quirky behaviour. I am almost sure this is a regression.

**Comment by alexcrichton** [comment]
I believe this is because a version requirement of `x.y.(z-1)` doesn't match `x.y.z-dev`, you have to explicitly have a version requirement of `x.y.z-dev` to get it to match.

Is that perhaps the issue here?
