### ISSUE TITLE
cargo build: wait for lock *after* checking if everything is fresh

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#6067]
````cargo run```` runs ````cargo build```` and executes the main binary afterwards.

If I run ````cargo build```` and then ````cargo check```` or `cargo clippy` and try to launch the executable in a different terminal via `cargo run`, `cargo run` runs `cargo build` which will wait until the lock of `cargo check/clippy` is gone which is unnecessary since `cargo build` is still fresh and I have to wait until clippy is done checking everything, or run the binary directly from somewhere inside target directory.

Can we make `cargo build` check if everything is fresh *before* checking for the lock?

**Comment by epage** [comment]
We need the lock to determine if things are fresh, so I'm going to close this.  if there is a reason we should re-evaluate this, let us know!
