### ISSUE TITLE
Cargo not working in the last Nightly (64-pc-windows-gnu)

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/cargo#6073]
Cargo shipped with yesterdays Nightly (it was rustc 1.30.0-nightly, 20dc0c507 2018-09-19, x86_64-pc-windows-gnu) was working fine. Today Cargo doesn't work to me. "Today" means rustc 1.30.0-nightly 3bc2ca7e4 2018-09-20.

```
...>cargo new foo1
error: Failed to create project `foo1` at `...\foo1`

Caused by:
  an unknown git error occurred
```

Beside giving that error it creates the foo1 directory with just a "`.git`" directory inside (that contains some files).

If I perform a "`cargo build`" inside a directory created by an older version of Cargo, it just crashes without error messages.

**Comment by alexcrichton** [comment]
Thanks for the report! This should be fixed by https://github.com/alexcrichton/git2-rs/commit/9c1604ef7abbbdf4a2312f18c0e60370961a14b2 and will be available once https://github.com/rust-lang/rust/pull/54443 is merged and deployed!
