### ISSUE TITLE
compile progress: don't count jobs that are fresh

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#6075]
Currently, the compile progress just counts the total amount of possible jobs as "total jobs" when building.

Maybe we can be more clever and don't add jobs that are "fresh" (will be skipped anyway) to the total amount of jobs that we need to process.

**Comment by epage** [comment]
As we need to know the total number of jobs at the start and won't know which jobs are fresh until we get to them, I'm going to close this.  We could reduce the count as we go but I'm not seeing enough benefit to that.  If there is a reason we should re-evaluate this, let us know!
