### ISSUE TITLE
Links in mdbook search result pages have incorrect anchors, don't scroll to the relevant section

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#6084]
If I search for "links manifest key": https://doc.rust-lang.org/cargo/reference/build-scripts.html?search=links%20manifest%20key

the first result is the expected section, but the link to the section is:

https://doc.rust-lang.org/cargo/reference/build-scripts.html?highlight=links,manifest,key#the--links--manifest-key

with `#the--links--manifest-key` fragment, but the section's URL is:

https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key

with `#the-links-manifest-key`

This breaks scrolling to the correct section, and for very long pages ([like this one](https://github.com/rust-lang/cargo/issues/5822)), this is confusing and gives impression that the wrong page has been shown.

**Comment by ehuss** [comment]
This is rust-lang-nursery/mdBook#720.  I don't think there's much we can do about it until it is fixed in mdbook.

**Comment by ehuss** [comment]
This was fixed for Cargo a long while back via https://github.com/rust-lang/rust/pull/62733.  There are still some potential areas where it might not match, but I'm not aware of any existing ones in the docs today.
