### ISSUE TITLE
cargo list does not de-duplicate entries

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#6088]
On Arch Linux, among other distros, `/bin` is a symlink to `/usr/bin`. This makes `cargo list` show many components twice:
```console
$ which -a cargo-clippy
/usr/bin/cargo-clippy
/bin/cargo-clippy
$ cargo list | grep clippy
    clippy
    clippy
```
It's a little unclear how to fix this though, since `cargo` would have to know that those two binaries are indeed the same. Resolving symlinks with `readlink` before de-duplicating [here](https://github.com/rust-lang/cargo/blob/72eee12f0d4a81e61c59d96b3b3cfa99c7031158/src/bin/cargo/main.rs#L89L112) might be the way to go? Alternatively, maybe the list should be de-duplicated based only on the command name, and not on the full path as well. That is, make that `BTreeSet` a `BTreeMap` with `name` as the key. We'd still then have to resolve conflicts, but have to do that today anyway!

As an aside to this, it'd be great if `cargo list` showed the path of the command it'll use to execute a given component by default. This happens [if `--verbose` is passed](https://github.com/rust-lang/cargo/blob/9b5b295459ab2140fc7a240af1397a355c1d55d5/src/bin/cargo/cli.rs#L66L70) currently, but I'm not sure I see the reason to hide it in non-verbose output, given that the command descriptions for built-ins are always shown?

**Comment by jonhoo** [comment]
cc @akshayknarayan

**Comment by ehuss** [comment]
Note: This often happens on Windows, where rustup adds the toolchain bin directory to PATH (for DLL loading).

This should be a relatively simple fix, to use a BTreeMap instead of a BTreeSet [here](https://github.com/rust-lang/cargo/blob/d555e49abee3e68036402f89e31f208a793cace1/src/bin/cargo/main.rs#L89).

**Comment by nipunn1313** [comment]
@rustbot claim

Sorry @hi-rustin - I think I just raced with you - I had just coded this one up. Perhaps you can review #9773 ?

**Comment by hi-rustin** [comment]
> @rustbot claim
> 
> Sorry @hi-rustin - I think I just raced with you - I had just coded this one up. Perhaps you can review #9773 ?

Maybe you should get my permission instead of just submitting a PR and unassigning me right away. But it's okay you can submit it. But hopefully next time you can claim early and get someone else's permission to do it after they claim. Thanks! 🤝

**Comment by hi-rustin** [comment]
Sorry, the bot seems to have recognized the quote in my reply, please cliam again. Thanks!

**Comment by nipunn1313** [comment]
Yes I am sorry. I should have assigned it to myself when I started looking at - instead of as I was completing it.
I had completed it literally 45 seconds after you claimed. It was bad etiquette on my part.
