### ISSUE TITLE
[Question] Cargo Offline/Global Packages

### ISSUE THREAD

**Issue by rburmorrison** [rust-lang/cargo#6095]
I've seen this question asked before, however they were all a few years ago and not for my particular use case. My question is this: **is there any way to install cargo packages globally on a system?** I am a systems programmer that works in environments that are disconnected from the internet. Rust with Cargo seems like a great environment that I would love to invest my time into, however I cannot just download packages on a whim. Currently, I use Golang because it has both the option to have packages installed globally, or have them installed within the project folder. As much as I love Go, I need something faster.

I agree that in a production environment it's more practical and preferred to have the system that Cargo is built around (a Cargo.toml file that lists the dependencies). Overall, **I would like to pre-install a bunch of dependencies** that I know I'll need on my offline machine before disconnecting it from the internet (basically forever) like I can with Golang, Python (although it's not practical), and C/C++. Is this a possibility? Thanks.

**Comment by sfackler** [comment]
The `--offline` flag is designed to support this kind of workflow: https://github.com/rust-lang/cargo/issues/5655

**Comment by alexcrichton** [comment]
Indeed! I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/5655 as that's the unstable feature implemented to solve this problem, and it's currently tracking stabilization/implementation.
