### ISSUE TITLE
Add a way to only optimize dependencies

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/cargo#6099]
I have a project which has a test taking 30 sec in debug mode and 1 sec in release mode. I think most of the time is spent in a dependency, so I want to have it optimized, but I also don't want my project itself to be optimized, because it takes much time to compile it.

**Comment by alexcrichton** [comment]
This is indeed something we'd like to have! This is [implemented on nightly](https://doc.rust-lang.org/stable/cargo/reference/unstable.html#profile-overrides) and has a [separate tracking issue](https://github.com/rust-lang/rust/issues/48683), so I'm going to close in favor of those.
