### ISSUE TITLE
error: could not find native static library `secp256k1`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by jamesray1** [rust-lang/cargo#6105]
I have the same issue as in: https://github.com/rust-lang/cargo/issues/1185.

When running `cargo build`, I get the error: ``error: could not find native static library `secp256k1`, perhaps an -L flag is missing?``. Removing that particular library from the build with `cargo build --no-default-features --features "libp2p-secio"`, I then get the same error for `ring`, which is not a feature, so needs to be in the build:

```rust
   Compiling ring v0.12.1
   Compiling libp2p-core v0.1.0 (file:///home/james/rust/lp2p/core)
error: could not find native static library `ring-test`, perhaps an -L flag is missing?
```

More details for my situation are in https://github.com/libp2p/rust-libp2p/issues/416.

I tried to reproduce this by cloning my origin and upstream, however, the upstream and origin both build correctly:

```bash
git clone https://github.com/libp2p/rust-libp2p.git;
rust-libp2p;
cargo build;
# end of build output:
Finished dev [unoptimized + debuginfo] target(s) in 4m 36s
```
```bash
git clone https://github.com/jamesray1/rust-libp2p.git jrl
jrl
➜  jrl git:(master) cargo build
# ...
Finished dev [unoptimized + debuginfo] target(s) in 2m 30s
```
So since `target` is in `.gitignore`, this seems to confirm that the cause of this `cargo build` error is due to something in that folder. However, it would be good to fix the root cause of the error so that I don't have to clone the repo again into a new folder, which I have done for the mean time.

**Comment by alexcrichton** [comment]
Thanks for the report! This error is coming from the compiler, not Cargo, and is likely indicative of a bug in a build script or your system configuration, not rustc/cargo. Do you think this is a Cargo bug though?

**Comment by jamesray1** [comment]
OK, thanks. I'll try to diagnose and fix. No I don't have good reason to believe it is a cargo bug.

**Comment by alexcrichton** [comment]
Ok it sounds like it's unlikely to be a Cargo bug, but opening a rustc bug for the incremental error would be good!
