### ISSUE TITLE
New cargo output is broken in MSYS2

### ISSUE THREAD

**Issue by Pzixel** [rust-lang/cargo#6108]
I recently updated my compiler and figured out that you added fancy new output with progress bars and so on. Looks pretty nice, but it's output is somehow broken.

Here is example of one build output: https://gist.github.com/Pzixel/4a02dc90496a02a10b1208c4646bf096

It looks innocent, but if you add "word wrap" you could see following:

                                                                                                                                                                  

> Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 0/406:                                                                                     Building [                                                         ] 1/406:                                                                                     Building [                                                         ] 2/406:                                                                                     Building [                                                         ] 3/406:                                                                                     Building [                                                         ] 4/406:                                                                                     Building [                                                         ] 5/406:                                                                                     Building [                                                         ] 6/406:                                                                                     Building [                                                         ] 7/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 8/406:                                                                                     Building [>                                                        ] 9/406:                                                                                     Building [>                                                       ] 10/406:                                                                                     Building [>                                                       ] 11/406:                                                                                     Building [>                                                       ] 12/406:                                                                                     Building [>                                                       ] 13/406:                                                                                     Building [>                                                       ] 14/406:                                                                                     Building [=>                                                      ] 15/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 16/406:                                                                                     Building [=>                                                      ] 17/406:                                                                                     Building [=>                                                      ] 18/406:                                                                                     Building [=>                                                      ] 19/406:                                                                                     Building [=>                                                      ] 20/406:                                                                                     Building [=>                                                      ] 21/406:                                                                                     Building [==>                                                     ] 22/406:                                                                                     Building [==>                                                     ] 23/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 24/406:                                                                                     Building [==>                                                     ] 25/406:                                                                                     Building [==>                                                     ] 26/406:                                                                                     Building [==>                                                     ] 27/406:                                                                                     Building [==>                                                     ] 28/406:                                                                                     Building [===>                                                    ] 29/406:                                                                                     Building [===>                                                    ] 30/406:                                                                                     Building [===>                                                    ] 31/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 32/406:                                                                                     Building [===>                                                    ] 33/406:                                                                                     Building [===>                                                    ] 34/406:                                                                                     Building [===>                                                    ] 35/406:                                                                                     Building [===>                                                    ] 36/406:                                                                                     Building [====>                                                   ] 37/406:                                                                                     Building [====>                                                   ] 38/406:                                                                                     Building [====>                                                   ] 39/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 40/406:                                                                                     Building [====>                                                   ] 41/406:                                                                                     Building [====>                                                   ] 42/406:                                                                                     Building [====>                                                   ] 43/406:                                                                                     Building [=====>                                                  ] 44/406:                                                                                     Building [=====>                                                  ] 45/406:                                                                                     Building [=====>                                                  ] 46/406:                                                                                     Building [=====>                                                  ] 47/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 48/406:                                                                                     Building [=====>                                                  ] 49/406:                                                                                     Building [=====>                                                  ] 50/406:                                                                                     Building [======>                                                 ] 51/406:                                                                                     Building [======>                                                 ] 52/406:                                                                                     Building [======>                                                 ] 53/406:                                                                                     Building [======>                                                 ] 54/406:                                                                                     Building [======>                                                 ] 55/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 56/406:                                                                                     Building [======>                                                 ] 57/406:                                                                                     Building [=======>                                                ] 58/406:                                                                                     Building [=======>                                                ] 59/406:                                                                                     Building [=======>                                                ] 60/406:                                                                                     Building [=======>                                                ] 61/406:                                                                                     Building [=======>                                                ] 62/406:                                                                                     Building [=======>                                                ] 63/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 64/406:                                                                                     Building [=======>                                                ] 65/406:                                                                                     Building [========>                                               ] 66/406:                                                                                     Building [========>                                               ] 67/406:                                                                                     Building [========>                                               ] 68/406:                                                                                     Building [========>                                               ] 69/406:                                                                                     Building [========>                                               ] 70/406:                                                                                     Building [========>                                               ] 71/406: 
...

I've tested it in powershell console and I've got much nicer output:

```
PS C:\Users\Alex\Documents\Repo\parity-ethereum> cargo +nightly-x86_64-pc-windows-msvc build
   Compiling ring v0.12.1 (https://github.com/paritytech/ring#bae475e9)
   Compiling evm v0.1.0 (C:\Users\Alex\Documents\Repo\parity-ethereum\ethcore\evm)
   Compiling wasm v0.1.0 (C:\Users\Alex\Documents\Repo\parity-ethereum\ethcore\wasm)
error: failed to run custom build command for `ring v0.12.1 (https://github.com/paritytech/ring#bae475e9)`
process didn't exit successfully: `C:\Users\Alex\Documents\Repo\parity-ethereum\target\debug\build\ring-4b8f5fc9e045b30e\build-script-build` (exit code: 101)
```

**Comment by ehuss** [comment]
Hm, I'm unable to reproduce any issues with the progress bar.  Which console are you using (mintty? conemu? etc.)  Which version?  Which msys distribution and version are using?

**Comment by Pzixel** [comment]
@ehuss I'm using bash installed via Git for Windows (*C:\Program Files\Git\git-bash.exe*)

**Comment by ehuss** [comment]
Indeed strange.  It looks like in your second attempt the window was resized?  That might impact it.  The window does need to be at least 60 characters wide, but it looks like you started with the default 80.

**Comment by Pzixel** [comment]
Yep, I resized it indeed, but then I resized it back, but correct behavior persisted... Not sure what does affect this.

**Comment by Pzixel** [comment]
I've reproduces the issue again on latest MSYS

![image](https://user-images.githubusercontent.com/11201122/46277904-569c6f80-c56d-11e8-89e5-b882a0e8e36c.png)
![image](https://user-images.githubusercontent.com/11201122/46277909-5c925080-c56d-11e8-8265-991e329872e8.png)

I'm not sure what's wrong though.

**Comment by alexcrichton** [comment]
@ehuss FWIW I can reproduce this as well. After opening a msys terminal and without changing its size at all we print the status across many lines.

I wonder if we have an off-by-one error or something like that which is causing us to print more characters than intended?

**Comment by ehuss** [comment]
Hm, I couldn't repro on my desktop, but I started a fresh VM and was able to repro there.  The console is reporting a width of 119 regardless of the actual width.  

I don't have any good ideas.  Some options I'm thinking:
* Unconditionally use max 60 width in msys terminals.  Even though terminals like conemu report the correct size, there's not an easy way to differentiate between that and mintty.
* Shell out to `stty size` if it is available.

Any thoughts?

**Comment by alexcrichton** [comment]
Weird! I wonder if something changed recnetly in windows?

In any case using 60 seems fine by me, and `stty size` as a fallback also seems ok
