### ISSUE TITLE
Error message should be more informative when build fails due to missing vendored dependencies

### ISSUE THREAD

**Issue by bholley** [rust-lang/cargo#6111]
We use 'replace-with' in mozilla-central [1] to force all dependencies to be vendored. However, if somebody does |cargo update| and then does not re-vendor the sources, the provided error message is pretty opaque:

> 0:10.34 error: no matching version `= 1.0.23` found for package `libz-sys`
> 0:10.34 location searched: registry `https://github.com/rust-lang/crates.io-index`
> 0:10.34 versions found: 1.0.16
> 0:10.34 required by package `mozjs_sys v0.0.0 (file:///files/mozilla/mc/b/js/src)`

It would be nice to inform the user that a replace-with is active for source.crates-io and that they may want to revendor. This bit @ekr today.

CC @alexcrichton @aturon 

[1] https://searchfox.org/mozilla-central/rev/819cd31a93fd50b7167979607371878c4d6f18e8/.cargo/config.in#6

**Comment by ekr** [comment]
Thanks Bobby. FWIW, I wasn't trying to revendor or anything like that. Rather mach complained that I had too old a version of cargo and I had been using apt recently and thought "hey, cargo update might fix this", and obviously it didn't!

**Comment by alexcrichton** [comment]
Ah yes definitely something we should improve! The error message is [generated here](https://github.com/rust-lang/cargo/blob/ad6e5c0037d88602a1c95051e42b392ed5ffcbe8/src/cargo/core/resolver/mod.rs#L935-L957) for now, and it's not currently trivial to reach into the [directory source](https://github.com/rust-lang/cargo/blob/ad6e5c0037d88602a1c95051e42b392ed5ffcbe8/src/cargo/sources/directory.rs) to pull out a good error message (that source is buried within the package registry in Cargo terms), but I think we could massage things to get a better error message out of this.

@ekr to confirm though, it sounds like you ran a `cargo update` to fix a problem, but it didnt end up fixing the problem and gave the error message above? (which definitely seems like it could be confusing if it didn't fix the original problem!)

cc @Eh2406, you may also have thoughts on this as well!

**Comment by ekr** [comment]
@alexcrichton. The order of things was

1. mach complained about cargo being too old
2. ran cargo update
3. realized cargo update isn't what I wanted and then updated rust
4. Ran mach build
5. Got the error above.

**Comment by alexcrichton** [comment]
Ok cool, makes sense, thanks!

**Comment by alexcrichton** [comment]
Ok I've tried to improve the state of affairs in https://github.com/rust-lang/cargo/pull/6112 here

@ekr if you have a moment mind taking a look at the [new error message](https://github.com/rust-lang/cargo/blob/fc34ba1252513eb4fb3d969696ac03cd17cd7ef2/tests/testsuite/directory.rs#L715-L721) and seeing if that would have been less confusing in your case?

**Comment by ekr** [comment]
I'm sorry to say that I don't think this would have been clear to me. In
particular, I don't think I would have realized that it was I who had
messed up the local state rather than that it was some kind of problem with
the build (which is what I initially thought)

-Ekr

**Comment by bholley** [comment]
So IIUC, the last line of the actual error message ekr would have seen would be:

> location searched: directory source `/path/to/mc/third_party/rust` (which is replacing registry `crates.io`)

Which still might not be enough, but is a bit more specific than the regexp in the test linked above.

Perhaps in the case where we write the "which is replacing registry" bit, we can add something like:

> (Perhaps you added a dependency on a crate from `crates.io` without adding a corresponding crate to `/path/to/mc/third_party/rust` ?)

Or something like that. Thoughts?

**Comment by ekr** [comment]
I'm starting to wonder if it wouldn't just be better to have mach check for
this occurrence. Is that something we could do?

**Comment by bholley** [comment]
Assuming by 'mach' you really mean 'the build system' (to which |mach build| delegates), that seems like it could plausibly work. I don't have a good sense of exactly how it'd be done but it seems reasonable.

Maybe a good path forward here is for Alex to land whatever more-informative error messaging he feels is reasonable to put in Cargo, and then we can file a bug and ask the build people to detect that message, and supplement it with an additional message specific to our setup (suggesting |mach vendor rust|)?

**Comment by bholley** [comment]
Sure, we can see what the build folks think. We can probably take that discussion to a Bugzilla bug.

In the mean time, I think we're probably good on the Cargo side with the new messages, though the additional parenthetical hint I suggested above could be helpful in this case if Alex thinks it's generally appropriate. Thanks!

**Comment by alexcrichton** [comment]
@bholley that all sounds good to me! I'll see if I can fit in a message like that

**Comment by alexcrichton** [comment]
Ok, there's now [an extra line in the error message explaining so](https://github.com/rust-lang/cargo/blob/20cfb41e42938a84a69c67cb83483c1f18ccb80b/tests/testsuite/directory.rs#L715-L722)

(our error format output isn't very good...

**Comment by bholley** [comment]
lgtm, thanks!
