### ISSUE TITLE
`build plan` fails with random missing crate

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#6116]
I'm trying to run `cargo build -Z unstable-options --build-plan`

Each time I run it, it fails with a different random crate from my dependency tree. Each time it gives a different error, of the form:

`error: failed to find <random crate> <version>`

**Comment by ehuss** [comment]
This should be fixed by #6086 and is just waiting for rust-lang/rust#54648 to be merged.

**Comment by ehuss** [comment]
@Diggsey the fix is now available on the latest nightly.  Can you confirm it fixed your issue?

**Comment by Diggsey** [comment]
Yep, it's fixed!
