### ISSUE TITLE
Args supplied to subcommands

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/cargo#6127]
If we install a subcommand called `cargo-testcmd`, and then install it with `cargo install --path .` and call it like `cargo testcmd arg1 arg2` we get the args as `["cargo", "testcmd", "arg1", "arg2"]`. Would it be better to supply the arguments as `["cargo-testcmd", "arg1", "arg2"]`, that way tools like clap can ignore the command name, and don't need to do anything special because it is split in two.

Alternative: `["cargo testcmd", "arg1", "arg2"]`.

**Comment by derekdreery** [comment]
I just got stung by this making https://github.com/derekdreery/cargo-docserve, and I've included this hacky code to fix the issue:

```rust
    let cargo_args = opts
        .cargo_args
        .iter()
        .enumerate()
        .filter_map(|(idx, val)| {
            if idx == 0 && val == "docserve" {
                None
            } else {
                Some(val.clone())
            }
        }).collect::<Vec<_>>();
```

**Comment by alexcrichton** [comment]
Thanks for the report! I definitely agree that not passing the subcommand argument to the subcommand would be better, but unfortunately that ship sailed long ago as all subcommands today expect it and would break if we stopped passing it. I think this is just a wart we're gonna have to live with :(

**Comment by dwijnand** [comment]
Perhaps there's scope for subsuming code like that, if it's helpful for future, new subcommands to integrate more smoothly with clap?  Without breaking existing subcommands.

**Comment by alexcrichton** [comment]
If possible sounds good to me! I don't know how we would do that, though
