### ISSUE TITLE
`cargo test` without `cargo build` won't create `target/debug/libfoo.rlib` while `cargo build` does

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/cargo#6131]
I always expect that `cargo test` basically runs a `cargo build` before doing anything test specific. But that's apparently not the case.

---

### Minimal example:

**Cargo.toml**
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["me"]
edition = "2018"
```

**src/lib.rs**
```rust
pub fn foo() {}
```

**tests/main.rs**
```rust
use foo::foo;

#[test]
fn main() {
    foo();
}
```

Executing `cargo test` will compile the `foo` crate and execute tests. Fine. BUT: **`cargo clean && cargo test` won't create the file `target/debug/libfoo.rlib` while `cargo clean && cargo build` does create that file.** This is very unexpected.

Tests on `rustc 1.31.0-nightly (5597ee8a6 2018-10-03)`

**Comment by LukasKalbertodt** [comment]
Mhhh maybe? 

The reason I noticed this is because I am writing my own test runners which call rustc with an `--extern` parameter. There I pass the path to my library (the `.rlib` file). So for my test runners it is important that this file exists.

Of course, maybe I shouldn't use this file as it's implementation detail. That would be fine. So far I've been using the build-plan feature to get the correct path. *But* I still think it's strange that `cargo test` doesn't run a normal `cargo build` beforehand. *I* think it's surprising and not what the user would expect.

**Comment by alexcrichton** [comment]
Interesting! I don't think it's necessarily problematic that we don't do this but I don't see a great reason to *not* create these artifacts. Seems good to me to fix!

**Comment by ehuss** [comment]
I think this is behaving as expected.  This is a result of #5460.  Because the lib is not an explicit target in this case, it is not uplifted out of `deps`.  Previously @alexcrichton you said that you didn't think `rlib` should *ever* be uplifted, so changing that would be the opposite of the direction you previously  indicated.  I think in this case using the true path in `deps` is the correct thing to do.

**Comment by epage** [comment]
As far as I can tell, this is working as expected.  `cargo test` is focused on building and preparing what is needed for running tests.  It is not a superset of `cargo build`.  I'm going to propose to the cargo team that we close this.

**Comment by weihanglo** [comment]
Agree with closing. Thank you for the triage.
