### ISSUE TITLE
`cargo fix` fails to fix unused_parens

### ISSUE THREAD

**Issue by vi** [rust-lang/cargo#6137]
It shows `warning: failed to automatically apply fixes suggested by rustc to crate ...` with a suggestion to report issue here.

**Comment by alexcrichton** [comment]
Thanks for the report! Can you provide an example of how to reproduce this?

**Comment by alexcrichton** [comment]
Ok I'm gonna close this as I'm not sure how to reproduce, but if you get a reproduction please let us know and I'll reopen!
