### ISSUE TITLE
[Feature request]: Print names of all examples when `--examples` is missing a value.

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/cargo#6145]
If you do `cargo run --example`, you will get an error saying that a value was expected, but none was supplied.

It would be great if you also got a list of the available examples.

I'm not sure if `clap` currently supports this functionality, either
 1. Custom error path when an option with name `example` is missing a value.
 2. Ability to specify that a value is optional, and then manually call the clap error handler with the extra info.

**Comment by derekdreery** [comment]
I thought this may just not be possible because of the ambiguous situation `cargo run --example --test`, but I see that clap already rejects this, requiring it to be written as `cargo run --example=--test`.

**Comment by ehuss** [comment]
Thanks for the report.  This is a duplicate of #2548, so closing in favor of that.

**Comment by derekdreery** [comment]
Yep, thought I'd checked for dupes sorry!
