### ISSUE TITLE
Specific dependency configuration causes target to be rebuilt needlessly

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/cargo#6154]
So I took @ehuss 's advice in #6143 , and changed my plugins not to rely on `plugin = true`.

Turns out, my binary is still rebuilt needlessly, because there is something else that triggers this behavior besides `plugin = true`. It looked like a plugin depending on `html5ever` triggered this issue, so I went down the rabbit hole, and tried to create a minimal test case that doesn't have external dependencies.

The result is at https://github.com/crumblingstatue/cargo-rebuild-repro-2 .

The problem is still the same. Do `cargo build --all`, see the `fooproject` binary in `target/debug`, do `cargo run`, see `fooproject` and its dependency get needlessly rebuilt.

**Comment by crumblingstatue** [comment]
> It's just that the fix might cause some things to be built multiple times when they previously weren't (specifically when you set panic = "abort"), and I'm a little uncertain if that extra compile time will be a problem for other users

Well, this issue is specifically a problem **because** of the extra compile time it causes. I certainly don't want a fix that would cause needless recompilations elsewhere.

If this can be fixed with clever engineering without causing needless recompiles elsewhere, I'd rather wait for a proper fix, even if it means rewriting the whole system.

**Comment by alexcrichton** [comment]
Thanks for digging into this @ehuss!
