### ISSUE TITLE
"error: [48] An unknown option was passed in to libcurl" on nightly only

### ISSUE THREAD

**Issue by nickolay** [rust-lang/cargo#6155]
I'm on OS X 10.9.5 (I know) and attempting to install any package using the nightly version (cargo 1.31.0-nightly (ad6e5c003 2018-09-28)) results in:

```
$  cargo install cargo-cov
    Updating crates.io index
error: [48] An unknown option was passed in to libcurl
```

Adding `-v` doesn't reveal the source of error.
`curl crates.io` with or without https works.

Stable cargo 1.29.0 (524a578d7 2018-08-05) and cargo 1.30.0-beta (05e9b01fc 2018-09-21) work fine.

I first suspected network censorship was the reason and tried to configure a proxy in ~/.cargo/config, but that didn't have any effect.

I'm not an active rust user, so I'm not sure if/how I can troubleshoot this further without delving in too deep.

**Comment by ehuss** [comment]
@nickolay What version of curl is on your system? (`curl -V`)

@alexcrichton it looks like curl-sys just gained the ability to statically link a few days ago  🎉 .  I'm curious if that is a feasible option.

**Comment by alexcrichton** [comment]
Ah I believe the bug here is that we blindly link cargo dynamically on osx hoping it has all the features. We should probably just link cargo statically like other platforms already do. Definitely a bug for us to fix!

**Comment by nickolay** [comment]
Thanks for the quick reply! My version of curl is:
```
$ curl -V
curl 7.59.0 (x86_64-apple-darwin13.4.0) libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11 libidn2/2.0.4 libpsl/0.20.1 (+libidn2/2.0.4) nghttp2/1.31.1
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by alexcrichton** [comment]
This should get fixed as part of https://github.com/rust-lang/rust/pull/54919 where we should force Cargo to always compile the `curl` submodule and link it

**Comment by carols10cents** [comment]
Hey, I'm reopening this because I'm helping out @synapticarbors at a meetup, and they're seeing this error even though they're on a newer nightly than Nov 4 (`cargo +nightly -v` = `2018-12-02`)

They're on macos 10.9.5, and curl -V 7.55.1. They're seeing the same error message as in the original report...

I'm not sure what to check to see if something broke the linked PR that changes to have cargo always compile the `curl` submodule and link it... is there any chance that's the case?

Or are we missing something?

This is NOT more urgent than the release or the all-hands <3

**Comment by ehuss** [comment]
@carols10cents We ended up needing to link libcurl dynamically on MacOS.  Since 10.9 has a relatively old version of libcurl, it was breaking on an newer option that was added.  I have posted a PR with a proposed fix.

**Comment by carols10cents** [comment]
Ahh, awesome. Thank you @ehuss! ❤️
