### ISSUE TITLE
`cargo run --example` false positive "is a library and cannot be executed"

### ISSUE THREAD

**Issue by Walther** [rust-lang/cargo#6159]
https://github.com/rust-dsp/rust-vst/issues/71

In `rust-vst`'s Cargo.toml, there is the following definition:

```
[[example]]
name = "simple_host"
crate-type = ["bin"]
```

among other example declarations which are `crate-type = ["cdylib"]` instead.

Trying to run it:
```
cargo run --example simple_host
error: example target `simple_host` is a library and cannot be executed
```

However, if you simply remove the line `crate-type = ["bin"]`, it starts working.

> <&mbrubeck> Walther: I think the bug is here https://github.com/rust-lang/cargo/blob/master/src/cargo/core/manifest.rs#L654-L658
> <&mbrubeck> Any non-empty list is treated as ExampleLib, which triggers https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_run.rs#L40-L45

**Comment by Walther** [comment]
Looking at https://github.com/rust-lang/cargo/blob/5dbac98885199bbd7c0f189d7405b5523434d1e3/src/cargo/core/manifest.rs#L647-L658 it seems there's a heavy assumption that examples will only ever be libraries.

If one changes the type signature to `Vec<TargetKind>`, line 655 `TargetKind::ExampleLib(crate_targets)` errors because `ExampleLib` cannot take `TargetKind` as an input. Additionally, there's a new error in line 355 https://github.com/rust-lang/cargo/blob/90fc9f620190d5fa3c80b0c8c65a1e1361e6b8ae/src/cargo/util/toml/targets.rs#L328-L371 caused by the `.into()` call:

```
the trait `std::convert::From<&std::string::String>` is not implemented for `core::manifest::TargetKind`
```

---

How should this be handled?
- Should we change the type of `crate_targets` in `fn example_target()`, and implement the conversion from string to `TargetKind` as well? How could that be done cleanly, with minimal repetition ref. `LibKind`'s conversion method?
- Should we instead create some sort of an `ExampleKind` wrapper so that within `fn clean_examples()` method in `targets.rs` the `into()` call can be more restricted?
- Should we just keep the type as `crate_targets: Vec<LibKind>,` and blindly rely on the `LibKind::Other` -catch-all in the conversion, and parse for an `Other`-type and see if it contains a "bin" value? This would feel a bit dirty. On the other hand, that's exactly the codepath that is happening right now for examples with "bin" declared as the type
- On an even broader scope, how should we handle these `crate_targets` being `Vec`'s - is it valid to have an example with both "lib" and "bin" target? What should happen then? What about possible other lists of targets?

**Comment by alexcrichton** [comment]
Thanks for the report, this definitely sounds like a bug! I agree that we should do some actual parsing here and realize that the string `bin` is a binary, not actually a library.

I'd be down for basically any fix that works here, feel free to refactor as necessary!
