### ISSUE TITLE
[Feature Request] Force If Newer

### ISSUE THREAD

**Issue by TheDan64** [rust-lang/cargo#6163]
In my project's CI, I cache a rust binary CLI tool so that it doesn't have to be reinstalled every time. However, when newer versions of the binary are released, it'd be nice to force an update.

So for example, it'd be great to have a `cargo install X --force-if-newer` flag which acts like the `--force` flag but is conditional on a never version of the binary being available. That way it doesn't reinstall blindly every time but only as necessary.

Edit: Oops, didn't open an internals thread first.

**Comment by k-nasa** [comment]
I'll take this task, is it ok❓

**Comment by dwijnand** [comment]
Shouldn't this be the behaviour under `--ensure`, too?  I.e in your #6592 PR?

**Comment by k-nasa** [comment]
Oops. You're right.

**Comment by ehuss** [comment]
I believe this is now stabilized via #7560.

**Comment by TheDan64** [comment]
@ehuss Do I understand your change correctly - `cargo install` will now overwrite the binary by default, if it finds a new version?

**Comment by ehuss** [comment]
Yes, starting with 1.41 which is currently the nightly channel.
