### ISSUE TITLE
Suppress warning: the cargo feature `edition` is now stable and is no longer necessary to be listed in the manifest

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#6168]
I updated my nightly and I'm getting:
> warning: the cargo feature `edition` is now stable and is no longer necessary to be listed in the manifest

It's not used in my workspace but by some dependency. Shouldn't this warning be suppressed for dependencies?

**Comment by alexcrichton** [comment]
Is the dependency a `path` dependency or a workspace member? Or a crates.io/git dependency? Could you provide a sample repo to reproduce this?

**Comment by Boscop** [comment]
It's a `path` dependency, not a workspace member. But the workspace is using a newer nightly than the dependency (via `rust-toolchain` file), so the `edition` key is still needed when building the dependency crate by itself..

**Comment by alexcrichton** [comment]
It's a bug in Cargo that the crate can't be easily found today, but it's expected behavior that the you get warnings for `path` dependencies.
