### ISSUE TITLE
OSX Compile fails for x86_64-linux-android

### ISSUE THREAD

**Issue by prographo** [rust-lang/cargo#6174]
I'm on a mac, cargo build --target x86_64-linux-android

```
  = note: ld: unknown option: --as-needed
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
error: aborting due to previous error
```

**Comment by alexcrichton** [comment]
Thanks for the report! This isn't a bug with Cargo though and moreso a problem with the configuration. When cross compiling you'll need to be sure to configure the linker for the target, for example `CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER=...` (or via `.cargo/config`). Once that's configured that should resolve this particular error message

**Comment by prographo** [comment]
Ok, I tried that too, I set it to i686-linux-android-clang in the NDK, but that gave a similar error:   

= note: ld: unknown option: --sysroot=/Users/local/NDK/x86/bin/../sysroot
          clang60: error: linker command failed with exit code 1 (use -v to see invocation)

Then I changed the Cargo.toml from crate-type "cdylib" to "staticlib" which worked.

**Comment by alexcrichton** [comment]
@prographo I'm not entirely sure what the issue is but that sounds like a toolchain issue, not a cargo issue?
