### ISSUE TITLE
Cargo doesn't fetch dev-dependencies when compiling tests for a sub crate in a workspace

### ISSUE THREAD

**Issue by zacps** [rust-lang/cargo#6183]
**Problem**

If a workspace has a subpackage which contains a test using an external crate like this:

```rust
#[cfg(test)]
mod tests {
    extern crate blah;

    fn test_blah() {
        blah::blah();
    }
}
```

And `blah` is declared in `dev-dependencies`:

```rust
[dev-dependencies]
blah = "*"
```

Then running from the package will work:

```
[subpackage]$ cargo test
```

But running from the parent will fail:

```
[parentpackage]$ cargo test -p subpackage
error: can't find crate blah
```

**Notes**

Output of `cargo version`:

```
cargo 1.31.0-nightly (5dbac9888 2018-10-08)
release: 1.31.0
commit-hash: 5dbac98885199bbd7c0f189d7405b5523434d1e3
commit-date: 2018-10-08
```

OS: Windows 10

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have a sample project which reproduces that we could poke around with? (having the full workspace configuration is convenient)

**Comment by zacps** [comment]
This should work as a minimal example.

https://github.com/zacps/workspace_test

**Comment by ehuss** [comment]
@zacps I think the issue is that `subpackage` is not actually a member of the workspace. You can add `[workspace]` to your top-level `Cargo.toml` to turn your project into a workspace, and then `-p` should work.

Otherwise, `cargo test -p somedep` doesn't work for arbitrary dependencies (this is similar to #5156 where `cargo test -p` for downstream dependencies doesn't work).

**Comment by ehuss** [comment]
I believe it doesn't work because dev-dependencies of downstream dependencies are not included in your local `Cargo.lock` so those dev-dependencies don't exist as far as cargo is concerned.

I definitely agree on having a better error message.  I'll try to add that soon.
