### ISSUE TITLE
Add cmd option to pass Rustc arguments containing spaces

### ISSUE THREAD

**Issue by humenda** [rust-lang/cargo#6184]
I am trying to pass `pre-link-arg`s and `link-arg`s to Rustc using Cargo. These dynamic an hence cannot be in the `Cargo.toml`. Since they contain spaces, I cannot use `CARGO_RUSTC_FLAGS`. If cargo had an option as `--rustc-arg=`, it would be possible to pass (multiple) arguments through to Rust, even if some would contain spaces. This could be useful for passing library paths, too.

**Comment by ehuss** [comment]
cc #6139, another issue about spaces in flags.

**Comment by atopia** [comment]
The problem of arguments with spaces in `CARGO_RUSTC_FLAGS` has been addressed with the introduction of `CARGO_ENCODED_RUSTFLAGS` in #9601 and the viability of the solution confirmed as part of working on rust-lang/rust/pull/85967. Although this issue proposes a command line option, unless @humenda objects I would argue that this issue can be closed.

@rustbot ready

**Comment by humenda** [comment]
`CARGO_ENCODED_RUSTFLAGS` is the thing that was missing and I have been
wanting for quite some time. Thanks for spotting the new feature.

**Comment by weihanglo** [comment]
Thanks everyone for participating in this issue. Glad the inconvenience has been resolved!

As a result, this is going to be closed. For a more general `--rustflags` CLI option, you can find recent discussions here <https://github.com/rust-lang/rfcs/pull/3310>.
