### ISSUE TITLE
check/build on workspace forces build of package not required by current target

### ISSUE THREAD

**Issue by temoto** [rust-lang/cargo#6185]
**Problem**

```
# project/Cargo.toml
[workspace]
members = ["cmd/iodin"]

# project/cmd/iodin/Cargo.toml
#...
[dependencies]
[target.'cfg(target_os = "macos")'.dependencies]
[target.'cfg(target_os = "linux")'.dependencies]
pigiron = { path = "../../hardware/pigiron" }  # impossible to build on macos
```

**Steps**

- cargo commands in binary directory work as expected
```shell
cd project/cmd/iodin
cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```
- but in workspace it tries to compile dependency that was not required by target
```shell
cd project
cargo check
   Compiling pigiron v0.1.0 (/Users/temoto/dev/github.com/temoto/vender/hardware/pigiron)
error: failed to run custom build command for `pigiron v0.1.0 (/Users/temoto/dev/github.com/temoto/vender/hardware/pigiron)`
...
```

**Possible Solution(s)**

For workaround I just use bash script instead of cargo at top level.

**Notes**

Output of `cargo version`:

- cargo 1.31.0-nightly (5dbac9888 2018-10-08)
- toolchain: nightly-x86_64-apple-darwin (default)
- OS: OSX Darwin Kernel Version 16.7.0

**Comment by ehuss** [comment]
I think this is to be expected (albeit surprising), as all path dependencies are implicitly added as workspace members.  One workaround should be to add it to the workspace exclude list.  I don't think it would be feasible for target dependencies to be automatically excluded because we don't have the target configuration before the workspace is constructed.

**Comment by epage** [comment]
With #6179 and #9208, we'd have the tools to allow a package to be a no-op when building workspace members which I feel takes care of this problem.  I'm closing in favor of those.  If there is a reason we should keep this open, let us know!
