### ISSUE TITLE
Missing / on Windows with no api token

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#6187]
I needed to `cargo login`, but saw this:

![image](https://user-images.githubusercontent.com/27786/47217529-9ee1cd00-d376-11e8-8613-8a44dd45807c.png)

Note the missing `/`, `crates.iome`

**Comment by alexcrichton** [comment]
This I believe is fixed in https://github.com/rust-lang/cargo/pull/6078 and should be riding the trains now!
