### ISSUE TITLE
No way to disable autobins

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6205]
A user on Discord noted that there is no way to completely disable automatic target discovery. Example:

`src/lib.rs`:
```rust
pub mod bin;
```

`src/bin/mod.rs`:
```rust
// empty
```

Currently this fails because it thinks there is a bin target called `mod`, regardless of whether `autobins` is specified. 

I'd like to propose that `autobins=false` should disable autodiscovery, even if you don't specify any `[[bin]]` targets.

**Comment by alexcrichton** [comment]
This seems reasonable to me! I'm surprised that `autobins = false` doesn't already work, and I'm also somewhat surprised that it's connected to the contents of `src/lib.rs`!
