### ISSUE TITLE
CARGO_PKG values should probably be in fingerprint, not metadata

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6208]
Currently, "authors", "description", and "homepage" are included in the metadata hash. This is done because the corresponding CARGO_PKG environment variables might be included in the crate. I think these values should be in the fingerprint instead.  It is a minor distinction, but the consequence is that changing any of these values will cause a recompile, but leave the old crates in the target directory, forever to be unused until the next `cargo clean`.  If they were in the fingerprint, the recompile would overwrite the old files.

Also, the recently added "repository" was not included in the hash, but it should have.

**Comment by ehuss** [comment]
@alexcrichton I've been thinking about this some more, and it seems like the fingerprint probably should contain all used environment variables. Do you think that would be a good idea? I noticed you mentioned something along these lines at rust-lang/rust#40364. I hacked something together that implements what you suggested (comments in the dep file). It wasn't hard, though it's a little messy passing the env names all the way through.

**Comment by alexcrichton** [comment]
Yeah that seems fine by me, the only real problem hashing has ever caused is uncover situations where things were being rebuilt when they weren't expected to be, but often fixable via configuration changes.
