### ISSUE TITLE
Docs are missing possible values for LTO

### ISSUE THREAD

**Issue by 0xpr03** [rust-lang/cargo#6214]
**Problem**

Docs are missing the possible values for lto.
I just got to know via #rust irc about
```toml
[profile.release]
lto = "fat"
```
This value isn't listed or documented in the cargo docs.

**Steps**

1. Go to https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys it's not documented

**Possible Solution(s)**

Document all possible values.

**Notes**
I was told that lto is enabled by default for release builds, going by the docs that isn't true, is it ?
At least for me it made a difference of ~3 MiB to set lto = "fat"

**Comment by ehuss** [comment]
The LTO settings and defaults are documented at https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections
`true` is the same as "fat LTO".  Debug/release default to LTO off (false).

**Comment by magicmaaaaan** [comment]
One thing that's not clear is if enabling `lto` affects `codegen-units`.

There's a [note in the code](https://github.com/rust-lang/cargo/blob/efb7972a095bcd043dfd55edca3a3fd1590b34c8/src/cargo/core/compiler/mod.rs#L786-L790), but that condition seems to set `codegen-units` regardless.

**Comment by 0xpr03** [comment]
I'd also like to have some more clarification about "fat" etc being the same. And a note that you can trim down the size even more by using this.

**Comment by ehuss** [comment]
There's also a rustc issue https://github.com/rust-lang/rust/issues/48518 about the codegen units/lto interaction.

**Comment by b0dski** [comment]
> Debug/release default to LTO off (false).

According to [this](https://doc.rust-lang.org/cargo/reference/profiles.html#lto) `lto = false` enables _thin local_ LTO as opposed to `lto = "off"` which fully disables it.
