### ISSUE TITLE
Alias for `check`

### ISSUE THREAD

**Issue by ordovicia** [rust-lang/cargo#6215]
How about adding `cargo c` alias for `cargo check`?

I believe that one of the most frequently used subcommands is `check`.
Adding this alias would save much time.

Currently, there are three aliases: `b` for `build`, `r` for `run`, and `t` for `test`.
I think that adding `c` alias would cover most of the use cases.

One problem I have come up with is that the `clean` subcommand also starts with the letter `c`.
But I believe that running `check` subcommand by mistake would not hurt developers so much.

I would like to prepare a PR for this change.

**Comment by ehuss** [comment]
You can define your own aliases in `~/.cargo/config`.  They are briefly mentioned at the bottom of this page: https://doc.rust-lang.org/nightly/cargo/reference/config.html#configuration-keys

This is the alias that I personally use:
```
[alias]
c = ["check", "--all-targets"]
```

**Comment by ordovicia** [comment]
I did not know the configuration. Thank you!

Still, I personally want the out-of-the-box `c` alias for `check` because the subcommand is frequently used.
I want to know how people feel about this addition.

**Comment by dwijnand** [comment]
I would argue it warrants equal status in the single-char alias club.  I'd say send the PR and let's see 🙂
