### ISSUE TITLE
Rust reference missing edition entry for Cargo.toml

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/cargo#6228]
**Problem**

https://doc.rust-lang.org/cargo/reference/manifest.html does not have documentation for the `edition` Cargo.toml entry.

**Comment by dwijnand** [comment]
It's not clear to me _why_ this is the case, but this was intentionally dropped in #6216.

**Comment by ehuss** [comment]
Thanks, editions are not available on stable yet.  It is available in nightly channel and the [nightly documentation](https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-edition-field-optional), and should ship in 1.31!
