### ISSUE TITLE
git-fetch-with-cli doesn't work well with custom registries

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#6241]
The git repository URLs for custom registries are currently forbidden from containing credentials. Unfortunately, that interacts poorly with the `git-fetch-with-cli` option since command-line git will default to using your username as the username when authenticating. However, a common configuration (e.g. with Github) is to use a single user named `git` for all users, so you end up with an error:

```
    Updating crates.io index
    Updating `ssh://my-git-server/my-registry-index` index
sfackler@my-git-server: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: failed to load source for a dependency on `some-crate`

Caused by:
  Unable to update registry `ssh://my-git-server/my-registry-index`

Caused by:
  failed to fetch `ssh://my-git-server/my-registry-index`

Caused by:
  process didn't exit successfully: `git fetch --tags --quiet 'ssh://my-git-server/my-registry-index' 'refs/heads/master:refs/remotes/origin/master'` (exit code: 128)
```

Note how the Permission denied message tried `sfackler@my-git-server` rather than `git@my-git-server` which would have worked.

It seems like we should relax the restriction on credentials in custom registry configurations to only forbid passwords and not usernames.

**Comment by alexcrichton** [comment]
Hm interesting!

Can you try running with `-v` as well? That should hopefully print the git command that's executed

**Comment by sfackler** [comment]
That's down on the last line:

```
git fetch --tags --quiet 'ssh://my-git-server/my-registry-index' 'refs/heads/master:refs/remotes/origin/master'
```

**Comment by alexcrichton** [comment]
Er right, sorry!

Since that doesn't work, can the user be specified in the url when configuring?

**Comment by sfackler** [comment]
Nope, allowing that is the proposed fix :P

```
error: failed to parse manifest at `/Volumes/git/chatter/chatter/Cargo.toml`

Caused by:
  Registry URLs may not contain credentials
```

**Comment by alexcrichton** [comment]
Sorry I'm definitely a bit slow today...

Seems like a solid use case to me to relax the restriction!
