### ISSUE TITLE
`cargo fix --edition` compiles dependencies for all platforms

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#6244]
**Problem**

Running `cargo fix --edition` on Linux in the Servo repo fails in the build script of a macOS-only crate

**Steps**

1. Clone the servo/servo repository on a Linux machine
2. Run `cargo +nightly fix --edition`
3. See a build error `src/task_info.c:10:10: fatal error: mach/mach_init.h: No such file or directory` in the `task_info` crate, even though that crate should not be built at all since it’s only depended on in a `[target.'cfg(target_os = "macos")'.dependencies]` section.

**Possible Solution(s)**

I assume that `cargo fix` tries to fix all the code it can find. Instead, it should probably default to building the same code that `cargo check` does, and not try to be more eager. That extra code might not be supported on the current platform/configuration.

**Notes**

Output of `cargo version`: cargo 1.31.0-nightly (2d0863f65 2018-10-20)

Toolchain: nightly-2018-10-31

**Comment by dwijnand** [comment]
It used to default to what `check` built, but it was argued to do more than that in #5739.

I think the current, loud (i.e erroring) behaviour is desired over silently not fixing non-supported platform/configurations.

If you want to restrict it to what it builds with `cargo check` I think you need to run `cargo +nightly fix --edition --lib` or maybe `cargo +nightly fix --edition --bins`.

**Comment by SimonSapin** [comment]
Uh, never mind. This problem is actually unrelated to `cargo fix`, closing.

I forgot that our build system normally uses `--manifest-path` to make Cargo only build one "root" crate. Without that, Cargo tries to build every workspace member including `task_info` which is a member because it happens to be a path dependency in the same repository, even though it is macOS-specific.
