### ISSUE TITLE
windows: remove installation requirement of mingw

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/cargo#626]
With rustc bundling mingw with itself, it's now possible to run rustc in windows cmd.exe without having mingw/msys installed. However, cargo still requires it to install (not to run). Only the most interested of Windows developers will bother to figure out how to install mingw.

Possible fix: re-write the installation script in Rust?

**Comment by alexcrichton** [comment]
This has now been fixed with the combined installers. The installers on rust-lang.org will install Cargo with Rust by default.
