### ISSUE TITLE
Way to turn off cargo progressbar

### ISSUE THREAD

**Issue by mocsy** [rust-lang/cargo#6263]
Since 1.30 Cargo comes with a strange progress-bar which is turned on by default.
It significantly increases the lines on the output and requires a lot more scrolling if I want to look at what cargo did.
I want to turn it off permanently.

Maybe off by default would be nice for anything large enough to have more than 3 dependencies?

Example output from my console:

`Building [====================================================>  ] 212/216:                                                                                     Building [====================================================>  ] 212/216:                                                                                     Building [====================================================>  ] 212/216:                                                                                     Building [=====================================================> ] 213/216:                                                                                     Building [=====================================================> ] 213/216:                                                                                     Building [=====================================================> ] 213/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 215/216:                                                                                                                                                                     Finished dev [unoptimized + debuginfo] target(s) in 1m 32s`

Nothing useful here to see, got to scroll back an entire screen to find a useful information.

**Comment by Eh2406** [comment]
doop of #5721

**Comment by mocsy** [comment]
@Eh2406 I'm not so sure, because using +beta the progress-bar disappears correctly and doesn't spam the output window.
