### ISSUE TITLE
resolve tests running on several cores when running "cargo test -j 1"

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#6265]
Repo @ 0c6bb242ba474ca2686738e555dbe3343f52db5e

When running `cargo test resolve -j 1` I can see some tests running on all core although I stated `-j 1`.
This annoying when I just wanted to run the tests in the background without them slowing down my system noticeably.

**Comment by weihanglo** [comment]
Unfortunately `--job` is for building stuff not for controling runtime behavior. This should do the job for you:

```
cargo test -p resolver-tests --test resolve  -- --test-threads 1
```

See <https://doc.rust-lang.org/nightly/cargo/commands/cargo-test.html#miscellaneous-options>. 

Going to close this. If you have any idea or think this shouldn't be closed, please comment here!
