### ISSUE TITLE
Make `cargo fix` remove unused imports

### ISSUE THREAD

**Issue by hirschenberger** [rust-lang/cargo#6278]
**Describe the problem you are trying to solve**

It would be great, if `cargo fix` could remove unused imports. Import handling is already tedious when using many dependencies without preludes and so it would be great it cargo could automatically remove the superfluous imports. 

**Describe the solution you'd like**

`cargo fix` and all `warning: unused import:...` messages are gone.

**Notes**

Unfortunately rustc does not give a hint, how to get rid of the warning. So one could either handle the fix in cargo itself or extend rustc's warning message.

**Comment by alexcrichton** [comment]
Thanks for the report! This is covered by https://github.com/rust-lang/rust/issues/50723 in upstream rust-lang/rust as it'll need support from rustc to emit the right fix annotations.

**Comment by dwijnand** [comment]
Duplicate of #5846

**Comment by cjhopman** [comment]
@alexcrichton The upstream issue is now closed, but afaict `cargo fix` still doesn't remove unused imports. Am I missing something?

**Comment by cjhopman** [comment]
Maybe rust-lang/rust#47888 or rust-lang/rust#53934 cover what remains to support this.

**Comment by teohhanhui** [comment]
For those ending up here from a Google search, there's https://crates.io/crates/cargo-udeps

**Comment by Friendly-Banana** [comment]
I'm on version `1.72.0 (103a7ff2e 2023-08-15)` and `cargo fix` removes unused imports for me. It's not perfect as empty lines may be left behind, but it works. Is this issue done?

**Comment by juliankrieger** [comment]
Is this issue dead? What is left to support this?
