### ISSUE TITLE
In some cases, cargo reports it can't execute itself because it's not in the PATH

### ISSUE THREAD

**Issue by andy5995** [rust-lang/cargo#6291]
**Problem**
If `cargo bloat` is run outside of a project directory, cargo reports that it can't execute itself because it's not in the PATH.

**Steps**

```
:~$ cargo bloat
Compiling ...
Error: failed to execute 'cargo'. It should be in the PATH.
```

**Possible Solution(s)**
Probably the same output should be shown as if `cargo run` were executed outside a project directory:

```
~$ cargo run
error: could not find `Cargo.toml` in `/home/andy` or any parent directory
```

**Notes**
This is a minor bug I found when someone suggested I run `cargo bloat` before I had reached section 1.3 of the book. I didn't understand that `cargo` really only has an effect when working with projects created with `cargo new`.

Output of `cargo version`: cargo 1.30.0 (36d96825d 2018-10-24)

OS platform: Debian Linux 9

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like this may be a bug in `cargo-bloat` (not an official part of Cargo, but a third-party subcommand). Is this perhaps a better bug for `cargo-bloat`?

For `cargo run` that error message looks correct (what it prints when it can't find `Cargo.toml`), although I may be misunderstanding the connection between that and `cargo bloat`

**Comment by andy5995** [comment]
>Is this perhaps a better bug for cargo-bloat?

I'll let one of the cargo maintainers decide that. (I recently noticed there's a GitHub beta feature where a project admin can "transfer" a ticket to another repo, and that would be better than me re-opening this ticket on another repo and closing this one, imo.)

>For cargo run that error message looks correct

Yes; I mentioned that under the "possible solution" section.

**Comment by dwijnand** [comment]
I agree this should be filed against cargo-bloat.  GitHub only allows transferring issues between organisation repositories, so it would be possible to transfer from this issue tracker to https://github.com/RazrFalcon/cargo-bloat, automatically.  Would you be happy to do so?

(Btw, Alex is a cargo maintainer)

**Comment by andy5995** [comment]
>Would you be happy to do transfer this, manually?

Done! https://github.com/RazrFalcon/cargo-bloat/issues/29
