### ISSUE TITLE
skip output files checking if fingerprints compare failed

### ISSUE THREAD

**Issue by joekyo** [rust-lang/cargo#6296]
I noticed that when cargo builds a crate, it compares the fingerprints and then check the output file.
A compile unit is considered Fresh only when both fingerprints and output files are valid.
I guess as long as the fingerprints checking failed, the compile unit can be considered Dirty, and the output file checking step can be skipped totally?

For example, when cargo compile itself first time, the fingerprints and output files are not there.
Cargo can figure out that a unit is Dirty if there is no fingerprint file for that unit.
This can save cargo from checking another 222 non-existent output files.

```
ls cargo/target/release/deps/ | wc -l
222
```

> DEBUG 2018-11-09T09:07:20Z: cargo::core::compiler::fingerprint: fingerprint at: /root/z/target/debug/.fingerprint/ucd-util-25204790852711e2/lib-ucd_util-25204790852711e2
>  INFO 2018-11-09T09:07:20Z: cargo::core::compiler::fingerprint: fingerprint error for ucd-util v0.1.2: failed to read `/root/z/target/debug/.fingerprint/ucd-util-25204790852711e2/lib-ucd_util-25204790852711e2`
>  INFO 2018-11-09T09:07:20Z: cargo::core::compiler::fingerprint:   cause: No such file or directory (os error 2)
> DEBUG 2018-11-09T09:07:20Z: cargo::core::compiler::fingerprint: checking output file: OutputFile { path: "/root/z/target/debug/deps/libucd_util-25204790852711e2.rlib", hardlink: None, flavor: Linkable }
>  INFO 2018-11-09T09:07:20Z: cargo::core::compiler::fingerprint: missing output path "/root/z/target/debug/deps/libucd_util-25204790852711e2.rlib"
> DEBUG 2018-11-09T09:07:20Z: cargo::core::compiler: unit Unit { pkg: Package { id: PackageId { name: "ucd-util", version: "0.1.2", source: "registry `https://github.com/rust-lang/crates.io-index`" }, ..: ".." },
> target: Target { ..: lib_target("ucd-util", ["lib"], "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ucd-util-0.1.2/src/lib.rs", Edition2015) }, profile: Profile { ..: default_dev() }, kind: Host, mode: Build } is fresh? Dirty
>

**Comment by alexcrichton** [comment]
Seems plausible to me! Do you know if this is causing a slowdown for you locally? Or just a possible perf win?

**Comment by joekyo** [comment]
I didn't do benchmark for testing performance. To check the output files or not won't make a big difference, I guess. I just think that this step is not necessary and can be skipped.

**Comment by epage** [comment]
Fingerprinting has dramatically changed since this was written.  Looking over the code, we always need to calculate the full fingerprint so we can write it out.  When we compare fingerprints, we short-circuit all over the place.  I'm not seeing anything from this that is still relevant and there weren't numbers to this, just an abstract potential improvement.  I'm going to go ahead and close this.
