### ISSUE TITLE
OUT_DIR missing when building source files

### ISSUE THREAD

**Issue by axos88** [rust-lang/cargo#6302]
Recently upgraded from rust 1.28 to 1.30, and the following line now returns an error, seems like OUT_DIR is not defined anymore when buiding the source files:

```
error: couldn't read "src/routes/false/data.rs": No such file or directory (os error 2)
  --> src/routes/statics.rs:11:1
   |
11 | include!(concat!(env!("OUT_DIR"), "/data.rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

build.rs:
```
extern crate includedir_codegen;

use includedir_codegen::Compression;

fn main() {
    includedir_codegen::start("ASSETS")
        .dir("../frontend/dist/rust-angular", Compression::Gzip)
        .build("data.rs")
        .unwrap();
}
```

The file is generated in the correct place but `include!` is looking in the wrong place.

**Notes**

Output of `cargo version`: cargo 1.30.0 (a1a4ad372 2018-11-02)
Rust version: rustc 1.30.1 (1433507eb 2018-11-07), stable

**Comment by ehuss** [comment]
The example project at https://github.com/tilpner/includedir/tree/master/example seems to run just fine, so I think OUT_DIR maybe isn't the problem.  Is your project publicly available, or can you create a reproduction, or say more about your layout?  I see that you have `..` in your path, maybe that has something to do with it?

**Comment by axos88** [comment]
It's not currently publicly available, but I will try to create a repro repo (HA!), and share that. I don't think `..` has anything to do with it, that's in the build script, and it's defined there correctly. The problem is in "normal" code, when trying to include it.

**Comment by axos88** [comment]
@ehuss,

So during the creation of the repro repo, I have found that the issue is a `use env`. But i'm baffled on why it causes issues, and why it doesn't create a more meaningful compile error: https://github.com/axos88/out_dir_bug

Apparantly the use `prelude:*` is mandatory to repro the issue, although I'm not sure how that compiles... There used to be a `prelude` module in the project, however it is now removed, but it doesn't give a compile error for that... Maybe it's resolving `std::prelude` somehow?

**Comment by alexcrichton** [comment]
Ok thanks for refiling! I'm gonna close this in favor of the rustc bug in that case
