### ISSUE TITLE
Can cargo build do conservative updates?

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/cargo#6310]
**Describe the problem you are trying to solve**
Currently, if `cargo build` detects that the lock file is out of date, it does a regular `cargo update`, i.e. the one described by this line in the help:

> If SPEC is not given, then all dependencies will be re-resolved and updated.

For a workspace with a large number of frequently changing `Cargo.toml` files, the lock file is almost always out of date. This proves to be a problem because of two reasons:
1. Longer build times, especially if upstream deps get upgraded.
2. A great number of tricky merge conflicts, and there's no merge tool available to resolve them yet.

**Describe the solution you'd like**

Instead, we would like to configure things so that:
1. `cargo build` does a conservative update by default: it figures out which dependencies are missing from the `Cargo.lock` and only adds new versions. Of course, if one of those deps causes an update to another dep, it's fine to change that as well.
2. Separately, we set up a cron job that updates the `Cargo.lock` file and checks the new version in.

The problem is that there appears to be no way to configure `cargo build` to do a conservative update. Ideally this would be somewhere in the workspace `Cargo.toml` file, but an environment variable is also fine.

This won't completely eliminate either problem, but at least greatly reduce its likelihood.

**Comment by alexcrichton** [comment]
Thanks for the report! This should actually already the be the default (conservative updates) but do you have an example of where a conservative update isn't being done so we can debug?

**Comment by sunshowers** [comment]
Thanks Alex!

Hmm, interesting -- that didn't seem to match the behavior I or my coworkers saw. Though I did just run `cargo update` and saw a large number of updates. I'm going to see if I can get a repro over the next couple of days, but I suspect it might have been PEBKAC on my end :)

**Comment by Eh2406** [comment]
I am going to close this for now. If you find a more precise description of the problem please comment so we can reopen.
