### ISSUE TITLE
Extra display lines when compiling on Linux VM with Windows host

### ISSUE THREAD

**Issue by CatGarab** [rust-lang/cargo#6314]
**Problem**

I develop in a Linux VM (VirtualBox provider) on a Windows 7 host machine.
After upgrading from Cargo v1.27.0 to v1.30.0, when I do `cargo build` there are multiple empty lines which are output during the compile process.

```
vagrant@vagrant:~/project $ cargo build
warning: unused manifest key: profile.release.opt-size
   Compiling proc-macro2 v0.4.20

   Compiling unicode-xid v0.1.0




   Compiling cc v1.0.25



   Compiling libc v0.2.43



   Compiling serde v1.0.80



   Compiling failure_derive v0.1.3



   Compiling num-traits v0.2.6



   Compiling ryu v0.2.6



   Compiling rustc-demangle v0.1.9



   Compiling cfg-if v0.1.6



   Compiling num-integer v0.1.39



   Compiling unicode-width v0.1.5



   Compiling itoa v0.4.3






   Compiling time v0.1.40









   Compiling backtrace-sys v0.1.24









   Compiling getopts v0.2.18










Building [============================>                            ] 22/42: proc-macro2, serde
```

**Steps**

1. Setup a VM with Linux on a Windows host machine
2. Install the latest stable version of Cargo
3. Build a Rust project

**Notes**

Output of `cargo version`: `cargo 1.30.0 (a1a4ad372 2018-11-02)`

- Issue present when using Cygwin or Windows Command Prompt to access VM via SSH
- Issue not present when using Cygwin or Windows Command Prompt to compile a project on the host machine
- Issue not present when coworker built a project on Linux VM using a Linux host machine

**Comment by ehuss** [comment]
@CatGarab would you be able to try with the latest nightly version of rust? It includes a new method for clearing the progress bar which may work better in your situation.

**Comment by ehuss** [comment]
I believe this is now fixed.
