### ISSUE TITLE
Build script dylib test issue

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6318]
The test `build_script_with_dynamic_native_dependency` does not seem to be working as it was originally intended. I was going to fix it myself, but there are too many changes that I don't understand. There are two primary issues:

- This line in the test points to a non-existing path: https://github.com/rust-lang/cargo/blob/b3d0b2e545b61d4cd08096911724b7d49d213f73/tests/testsuite/build_script.rs#L1440
- These lines do not have any test coverage (removing `add_plugin_deps` does not cause any errors): https://github.com/rust-lang/cargo/blob/b3d0b2e545b61d4cd08096911724b7d49d213f73/src/cargo/core/compiler/mod.rs#L517-L542

The history for this test:
- The test and `add_plugin_deps` added in #1195.
- The test dylib builder was changed to add `plugin = true` in #1960. ← This one I particularly don't understand.
- Test was changed to use a workspace in #3974 which resulted in the build script emitting a path that does not exist. That PR also changed it so that linker paths must be prefixes of the `target/debug` directory, so you can't just switch it back to a non-workspace.

It's not clear to me how #3974 was supposed to work. It's also not clear if `add_plugin_deps` is even needed anymore. I would think all plugin dylibs should already live in the `deps` dir which is already included in the LD_LIBRARY_PATH, so I don't know why `add_plugin_deps` exists.

**Comment by alexcrichton** [comment]
Hm ok I think that test is basically *the* test for why `add_plugin_deps` exist. The addition of a workspace breaks the intention of the test, so those two projects definitely shouldn't be in the same workspace. 

As for #1960 I dunno if it's necessary any more, if you can remove `plugin = true` and the test still works I'd remove it, it looks like one of those things where I just added it to keep something working at the time, and it may have been erroneous and/or no longer necessary
