### ISSUE TITLE
Give better error messages when out-of-memory (OOM) killer kills rustc

### ISSUE THREAD

**Issue by pzmarzly** [rust-lang/cargo#6325]
Recently I was building `gio` on Raspberry Pi 0. It kept failing due to lack of RAM and swap space. `cargo build` gave no error information, suggested `--verbose`. Verbose mode informs that `rustc` received `SIGKILL`. It took me a while to realize where that signal came from. It would be nice to have a hint like "rustc was killed by SIGKILL. Do you have enough RAM?"

**Comment by pzmarzly** [comment]
For the reference, it is possible to build `gio` crate on RPi 0 without X11, but barely (512MB of RAM is not enough, it hits swap, default 100MB of swap is enough)

**Comment by dwijnand** [comment]
RAM is only one of many reasons a process might die to a SIGKILL so, while it would have been useful in this case, it would've been wrong and misleading in other cases.  So unless a way is found to avoid these false positives, I'm going to close this issue.
