### ISSUE TITLE
Features cannot enable/disable features of dependencies

### ISSUE THREAD

**Issue by lilyball** [rust-lang/cargo#633]
According to the [documentation on features](https://github.com/rust-lang/cargo/blob/master/src/doc/manifest.md#the-features-section), a dependency can have its features specified with the `features` key (although this is not documented in the actual [dependencies section doc](https://github.com/rust-lang/cargo/blob/master/src/doc/manifest.md#the-dependencies-sections)). However, it looks like there's no way for a feature to modify the feature list of an existing dependency, only to enable an optional dependency.

If I have a dependency with a feature, and I want to expose that feature as a feature of my own package, I don't see any way to do this. I can't use two dependencies with separate feature lists because a feature cannot disable a dependency. And there's no syntax for a feature to modify the feature list of a dependency.

This seems potentially very problematic to me. Ultimately, I think it's a consequence of features being designed far too heavily as merely toggles for optional dependencies. I think features need to have more control than just turning on optional dependencies. Yes, there's also a `--cfg` flag, but that doesn't help here either. In #385 I wrote [two long comments](https://github.com/rust-lang/cargo/issues/385#issuecomment-56127824) with my thoughts on the feature design, which got no response. Admittedly it was pretty late in the process, but I still think it's important feedback. With the first feature syntax I suggested, there's plenty of room there to add extra power to features, such as the ability to disable dependencies, or to modify the feature list of a dependency. FWIW I think disabling dependencies might also be important, as I can imagine plenty of reasons why a library might want to have a feature to enable a rarely-used alternative implementation of something, which would need to disable any dependencies used by the disabled default implementation.

**Comment by dnspies** [comment]
Can you add a not to [manifest.html](http://doc.crates.io/manifest.html#the-features-section) about the "/" separator?  I spent quite a while looking for this.

**Comment by jonhoo** [comment]
How would this be used to enable *multiple* features of `bar`?
```rust
foo = ["bar/baz/qux"]
```
or
```rust
foo = ["bar/baz", "bar/qux"]
```

**Comment by sfackler** [comment]
The second.

**Comment by jhpratt** [comment]
Still doesn't look like it's possible to disable a feature? I'm trying to set up a crate to have a "std" feature, which would indicate that "serde/alloc" is _not_ enabled. For current compilers, this isn't an issue, but my goal is to provide support back to 1.34.0, before alloc was stabilized.

@sfackler perhaps?
