### ISSUE TITLE
cargo clean --release removes entire target directory without warning

### ISSUE THREAD

**Issue by spearman** [rust-lang/cargo#6339]
**Problem**

Running `$ cargo clean --release` seems to silently remove the entire target directory. I would expect at least a warning that this would happen when passing the '--release' flag since the intention was to only clean the release build.

**Comment by mbrubeck** [comment]
I'm not sure why `clean` even has a `--release` flag, since both with and without the flag, it removes both dev and release artifacts.  So even if this bug were fixed, there'd be no way to remove only *non*-release artifacts.

**Comment by lukaslueg** [comment]
Having taken a quick look at the tests, it seems `cargo clean` will always clean everything. `cargo clean -p mypkg --release` should only remove the release-artifacts.

**Comment by dwijnand** [comment]
Yep, I can reproduce this too:

```bash
21:39:38 $ cargo new foo
     Created binary (application) `foo` project

21:39:42 $ cd $_

21:39:44 $ cargo build
   Compiling foo v0.1.0 (/s/foo)
Finished dev [unoptimized + debuginfo] target(s) in 0.80s

21:39:56 $ cargo build --release
   Compiling foo v0.1.0 (/s/foo)
    Finished release [optimized] target(s) in 0.35s

21:39:59 $ ls -l target
total 0
drwxr-xr-x@ 12 dnw  staff  384 20 Nov 21:39 debug/
drwxr-xr-x@ 11 dnw  staff  352 20 Nov 21:39 release/

21:40:03 $ cargo clean --release

21:40:11 $ ls -l target
ls: target: No such file or directory

21:40:13 ! cargo -Vv
cargo 1.30.0 (a1a4ad372 2018-11-02)
release: 1.30.0
commit-hash: a1a4ad37271b61209cd55d21f2c83f2773cbe113
commit-date: 2018-11-02
```

**Comment by lukaslueg** [comment]
```
cargo new foo
cd foo
cargo build
cargo build --release
cargo clean -p foo --release
```

leaves you with a `target/debug` intact. Maybe the best course of action is to disallow `--release` if `-p` is not specified?

**Comment by dwijnand** [comment]
> Maybe the best course of action is to disallow `--release` if `-p` is not specified?

Only if fully fixing it isn't possible, sure!
