### ISSUE TITLE
Migrate from AppVeyor to Travis CI Windows?

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/cargo#6346]
With Travis CI adding support for Windows (https://blog.travis-ci.com/2018-10-11-windows-early-release) should we transition from AppVeyor to Travis CI for Windows testing too?

Any feels for or against?

**Comment by dwijnand** [comment]
One benefit is I seem to be able to restart Travis CI jobs, but not AppVeyor jobs.

**Comment by alexcrichton** [comment]
This seems like it's worthwhile to test for! The main reason for us I believe is that we have more capacity on Travis than AppVeyor so builds may finish more quickly. Should be fine to test out a PR regardless!

**Comment by Eh2406** [comment]
People are reporting that it is nearly unusable slow do to https://github.com/rust-lang/rustup.rs/issues/998#issuecomment-432587631
It is worth a shot, but I am not hopefully until that is fixed.

**Comment by dwijnand** [comment]
Hmm.  OK, then let's park this for now.

**Comment by slonopotamus** [comment]
rust-lang/rustup.rs#998 is now fixed
