### ISSUE TITLE
`cmake` is no longer required?

### ISSUE THREAD

**Issue by RandomInsano** [rust-lang/cargo#6367]
**Problem**
The README claims I need `cmake`. I do not have `cmake`. Cargo built anywhoo.

Mainly curious where `cmake` is still needed and if the docs should be made more specific or refreshed.

**Steps**
1. Install a clean copy of macOS Mojave
2. Install rust via `rustup`
3. Install dev tools via `xcode-select`
4. Install Homebrew, then `openssl`
4. Clone, then build `cargo`

**Possible Solution(s)**
Be specific on which OSes require `cmake`?

**Comment by dwijnand** [comment]
It was added when there was a makefile, so probably not anymore!  PR?

**Comment by RandomInsano** [comment]
And so the PR did get created:
https://github.com/rust-lang/cargo/pull/6368

**Comment by RandomInsano** [comment]
It’s been merged.
