### ISSUE TITLE
Warn if a feature is called "default-features"

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#6370]
### Describe the problem you are trying to solve

In https://twitter.com/myrrlyn/status/1069378052184915968 it was observed that a Cargo.toml containing:

```toml
[features]
default-features = ["..."]
```

is exceedingly likely to have meant to write `default = ["..."]`. This is an *easy mistake to make* because the key to turn off default features in a dependency really is called `default-features`. It is a *hard mistake to notice* because your crate is likely to compile successfully when you build it.<br><br>

### Describe the solution you'd like

I would expect a warning, very similar to what you would see from unrecognized keys in Cargo.toml.<br><br>

Mentioning: @myrrlyn

**Comment by fbunt** [comment]
I can take this.

**Comment by fbunt** [comment]
For clarification, should the warning only occur if it `default-features` appears under the features section?
