### ISSUE TITLE
`Cargo init` creates duplicates in .gitignore

### ISSUE THREAD

**Issue by collin5** [rust-lang/cargo#6377]
Doing `cargo init` in an existing git repository will either create a new `.gitignore` or append to an existing one. However if we already have a `.gitignore` file with both `/target` and `**/*.rs.bk` ignored, `cargo init` will still add these to the existing file.

**Steps**

```
$ mkdir foo && cd foo 
$ git init
$ echo "/target\n**/*.rs.bk" > .gitignore
$ cargo init
```
The new `.gitignore` will now contain
```
/target
**/*.rs.bk

/target
**/*.rs.bk
```
**Possible Solution(s)**

Before creating or adding to the existing `.gitignore`, we could perhaps check the contents and only add what is missing. Looks like the code handling this is https://github.com/rust-lang/cargo/blob/485670b3983b52289a2f353d589c57fae2f60f82/src/cargo/ops/cargo_new.rs#L460-L465, https://github.com/rust-lang/cargo/blob/485670b3983b52289a2f353d589c57fae2f60f82/src/cargo/ops/cargo_new.rs#L471-L476 and https://github.com/rust-lang/cargo/blob/485670b3983b52289a2f353d589c57fae2f60f82/src/cargo/ops/cargo_new.rs#L482-L487

Version: cargo 1.31.0-nightly (2d0863f65 2018-10-20)

**Comment by starsheriff** [comment]
I'd happily start working on that one as a first contribution. Seems to be quite straight forward.

**Comment by collin5** [comment]
Great! Go for it.

**Comment by Lucretiel** [comment]
I'd like to reopen this issue; I'm still seeing this behavior on git when I run `cargo init --lib .`

**Comment by dwijnand** [comment]
@Lucretiel That's because this fix hasn't made it way into stable Rust yet.  It's in nightly and beta (try `cargo +nightly init` or `cargo +beta init`) and stable is releasing in next week Friday 1 March.

**Comment by Lucretiel** [comment]
Oh, sorry, I didn't see the dates that this was so recent. Thank you!
