### ISSUE TITLE
cargo install never ends on nightly and linux

### ISSUE THREAD

**Issue by ghusse** [rust-lang/cargo#6384]
**Problem**
I'm trying to use some packages that need nightly.

Running `cargo install xxxx` works correctly
Running `cargo +nightly install racer` (for instance, but I have the same issue for other packages) never ends. The installation is stuck in "installing".

**Steps**

1. `rustup toolchain add nightly`
2. `cargo +nightly install racer`

**Notes**
I installed rust/nightly on windows a few days ago, and did not have this issue

Output of `cargo version`:
`cargo 1.30.0 (a1a4ad372 2018-11-02)`

**Comment by ehuss** [comment]
>  cargo 1.30.0 (a1a4ad372 2018-11-02)

This version is quite old.  Can you try with a newer version (current nightly is 1.32 2018-12-05)?  You may want to check your PATH is set up correctly and you are using the correct cargo/rustc as installed by rustup.

**Comment by ghusse** [comment]
It seems to be an issue with rustc in nightly.

```
rustc --version
```

Never ends, with nightly on my machine. On stable it works as expected.

**Comment by ghusse** [comment]
I upgraded everything, `rustc --version` works correctly, `rustc +nightly --version` is stuck.

I should have posted the result of `cargo +nightly --version` which is now

```
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)
```

**Comment by alexcrichton** [comment]
@ghusse out of curiosity, can you attach a debugger and try to get a stack trace of the stuck process?

**Comment by alexcrichton** [comment]
Oh sure, you should be able to:

* First, execute rustc and wait for it to hagn
* Next, figure out the pid for rustc (I used `ps` typically for that)
* Execute `gdb -p $PID`, this should attach GDB to the process
* Execute `thread apply all bt`

And hopefully that's enough output to gist!

**Comment by ghusse** [comment]
> @ghusse Do you have ESET antivirus installed (or any security software)?

@ehuss Yes, I have ESET antivirus. I tried to deactivate its protection to see if it works but that did not do anything.

@alexcrichton I followed the steps, but I don't see any output for the command `thread apply all bt`. Am I missing anything?

**Comment by ehuss** [comment]
Ah, in that case, I'm going to close in favor of the upstream issue https://github.com/rust-lang/rust/issues/56736 as it is a problem with how rust is built. You can follow that for more updates. I think we understand what's wrong. It's an unfortunate interaction between ESET, jemalloc 5, and how rust is built.  At this time I don't know of a good fix, though there are some ideas listed on that issue.

**Comment by ghusse** [comment]
Thanks for the explanations.
