### ISSUE TITLE
`cargo t --all` seems to ignore the `--all` option

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#6394]
**Problem**

In Cargo 1.32, `cargo t --all` and `cargo test --all` have a different behaviour.
Calling `cargo test --all` runs the tests of all the crates of the current workspace (as intended), while `cargo t --all` only runs the tests of the current crate.

**Steps**

- Clone https://github.com/libp2p/rust-libp2p
- Run `cargo t --all`. Notice that only the tests of `libp2p` are being run (5 doctests as of the writing of this issue).
- Run `cargo test --all`. Notice how all the crates of the repository get tested (around 40 tests).

**Notes**

Output of `cargo version`: cargo 1.32.0-nightly (5e85ba14a 2018-12-02)

**Comment by ehuss** [comment]
Thanks for the report.  This has been fixed in #6382.  I'll try to get it in nightly soon.
