### ISSUE TITLE
Allow use of manifest-path with `cargo fmt`

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/cargo#6396]
**Describe the problem you are trying to solve**

I have a number of workspaces in the same repository, and have a Makefile target for formatting them all with `cargo fmt`. I tried to use `--manifest-path` to select the package to run `rustfmt` in without switching to it, as works with e.g. `cargo build`, but this is not supported by `cargo fmt`.

**Describe the solution you'd like**

Being able to pass `--manifest-path path/to/Cargo.toml` to `cargo fmt` would solve this issue, along with making the Cargo subcommands more uniform, as this seems like an artificial limitation.

**Comment by ehuss** [comment]
Thanks for the report.  I think this is a known issue, see rust-lang/rustfmt#2817.
