### ISSUE TITLE
RUSTFLAGS is easy to misspell as RUST_FLAGS

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#6406]
**Problem**

I can never remember if it's `RUSTFLAGS` or `RUST_FLAGS`, and writing the latter silently does nothing. This is made worse because essentially every other environment variable cargo understands or declares uses `_`s: https://doc.rust-lang.org/cargo/reference/environment-variables.html

(This also applies to `RUSTDOCFLAGS` vs. the incorrect `RUSTDOC_FLAGS`.)

**Steps**

1. Be forgetful and write `RUST_FLAGS` instead of `RUSTFLAGS`
2. Run `RUST_FLAGS=some-arg cargo build`
3. Don't notice (and/or be surprised) that `some-arg` didn't take effect (for that specific example, the build "should" fail but doesn't).

**Possible Solution(s)**

Cargo could check for a `RUST_FLAGS` environment variable and emit a warning (or note) that `RUSTFLAGS` was meant.

**Notes**

Output of `cargo version`: cargo 1.31.0 (339d9f9c8 2018-11-16)

**Comment by Ygg01** [comment]
@yjkimjunior Wouldn't that break all existing implementations? Huonw's suggestion makes me think it will add an additional spelling for RUST_FLAGS
@huonw Should this be a specific solution or is a more generic solution be needed. I.e. print warning for all env. variables at some  [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).
