### ISSUE TITLE
Make possible to use a different build profile to compile build.rs

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/cargo#6418]
Time-consuming add-ons such as `cbindgen` should be always built in release mode if you aren't trying to debug `build.rs` itself.

Ideally should be possible to add a command line override and a `Cargo.toml` key to specify it.

**Comment by alexcrichton** [comment]
I believe this is covered by https://github.com/rust-lang/rust/issues/48683, so I'm gonna close in favor of that, but thanks for the report!

**Comment by lu-zero** [comment]
Probably it is, maybe it should be moved to the cargo repo btw.
