### ISSUE TITLE
cargo install sccache fails to compile w/ Microsoft Visual Studio\\2019\\Preview

### ISSUE THREAD

**Issue by JaiSoone** [rust-lang/cargo#6420]
**Problem**
sccache fails to compile. I have both Visual Studio 2017 and the Preview version of 2019 installed.
To my surprise cargo is attempting to utilize the preview edition and I see no way to force it to use the 2017 version.

**Steps**

1. cargo install sccache 2>&1 | tee ~/logs/sccache.log
[sccache.log](https://github.com/rust-lang/cargo/files/2670459/sccache.log)

2.
3.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

**Comment by alexcrichton** [comment]
Thanks for the report! 

This is probably actually best a bug for the [`cc` crate](https://github.com/alexcrichton/cc-rs) which is used by build scripts to find an MSVC compiler. That crate I think doesn't have support for 2019 which means it just finds the one it knows how to find, 2017. 

Perhaps this bug could be moved to that repository to add support for finding the 2019 compilers?

**Comment by dwijnand** [comment]
Closed in favour of an issue in the cc crate.
