### ISSUE TITLE
Cargo check  - wrong warning about unused code (edition=2018, nightly 2018-12-7)

### ISSUE THREAD

**Issue by apiraino** [rust-lang/cargo#6430]
**Problem**
`cargo check` warns about unused code that is actually used.
The desidered behaviour should be not to have these false positives.

**Steps**

1. Have a look [at this gist](https://gist.github.com/apiraino/744729b62bafcc551b7b45b9b424a130). This is a reduced version, with a slightly different behaviour, of something I'm experiencing [in this repo](https://github.com/apiraino/open-taffeta/blob/962991b9ce5388081261fd73e5b3684d0dae4866/tests/common/dbstate.rs#L55)
2. Running `cargo check` produces the warning `warning: method is never used: new`

**Possible Solution(s)**
I suspect that is another manifestation of rust-lang/rust#54180. In case, feel free to clone in favor of that.

**Notes**

Output of `cargo version`:

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

$ cargo version
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)

$ rustc --version
rustc 1.32.0-nightly (4a45578bc 2018-12-07)

Thanks for looking!

**Comment by ehuss** [comment]
I think this is expected.  You can run `cargo check --profile=test` to check with tests enabled which will make your warning disappear.  When a `cfg` block is used, rustc essentially deletes the code if it is not enabled, so it is not considered (beyond basic parsing).

**Comment by alexcrichton** [comment]
Ah yes indeed, so closing!

**Comment by apiraino** [comment]
thanks @ehuss for the super-quick answer. Yes, that warning disappears adding that param, but I'm still slightly confused when it comes to integration tests (the real reason I submitted this issue).

So, when I want to run `cargo check` on my integration tests (i.e. in `../tests`) should I run `cargo check --tests --profile=test`? I had that warning also in code not marked by any `#[cfg(test)]` or `#[test]` block.

And if yes, why do I need two params to have cargo check my integration tests code?

Thanks for clarifying a bit more (still a newbie, sorry about that).

**Comment by apiraino** [comment]
@ehuss it was not easy! :) but I managed to create a small repo with the smallest test case possible: https://github.com/apiraino/cargo_issue_6430

I also _think_ I understand exactly how to trigger the `unused_code` false positive: basically when in the integration tests a submodule is not used by all tests file.

**Comment by ehuss** [comment]
Ah, yea, I think that is expected to happen, since each test is essentially independent of one another. The `test_2` target is correctly reporting that there are things unused as far as it's concerned.  It's not unusual for some projects to combine all of their integration tests into one executable.  It can simplify situations like this, and if you have a lot of tests, uses much less disk space.  Cargo itself does this – it has one [main.rs](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/main.rs) which imports everything.

**Comment by apiraino** [comment]
Wow, the more I learn, the more I discover new things :-) That looked counter-intuitive to me, but I understand the rationale behind.

Thank you for your time, really appreciated! :+1:

**Comment by apiraino** [comment]
ok, follow-up to this issue.

I've moved all my tests into a separate crate. Now I'm building a monolithic library with all the integration tests. I've crated [a separate project](https://github.com/apiraino/rust-tests-stub-project) for this crate so I can copy and paste it as a starting point for my integration tests.

I think this issue can be closed
