### ISSUE TITLE
[Cargo fix] anonymous lifetime/custom derive

### ISSUE THREAD

**Issue by D4nte** [rust-lang/cargo#6436]
Here:
https://github.com/comit-network/comit-rs/blob/0e62f27b801824cd9938ab1475964102c080c2c0/application/comit_node/src/swap_protocols/rfc003/state_machine.rs#L504

When running `cargo fix`, the anonymous lifetime `<'_>` was added to `fmt::Formatter` 20+ times instead of just one.

Feel free to get latest master, remove the lifetime and re-run `cargo fix`

**Comment by ehuss** [comment]
Thanks for the report! I believe this is the same as rust-lang/rust#55768.
