### ISSUE TITLE
Add a "cargo bench --debug" option

### ISSUE THREAD

**Issue by asomers** [rust-lang/cargo#6445]
A mere `cargo test` neither compiles nor runs the benchmarks.  In order to keep them from bitrotting, they must be built and run in CI.  But release builds take much more time and RAM than debug builds.  In a CI situation, the benchmark results aren't important; only the fact that they can run without errors.  So it would be very helpful if there were a `cargo bench --debug` option 

The closest that can be done right now is to do `cargo build --benches && target/debug/<my_benchmark>-*`.  That usage is problematic because
1) The CI script must be updated everytime a new benchmark program is added, and
2) That invocation will run old, stale binaries, too.

Instead, it would be great if cargo had a single `cargo bench --debug` command that would build the benchmarks in debug mode and then run them.

**Comment by droundy** [comment]
Any chance there is a workaround on this yet? I've got a bug that shows up only in my benchmark, and it'd be far easier to find with debug symbols enabled.

**Comment by sfackler** [comment]
You can turn on debug symbols when building benchmarks.

**Comment by asomers** [comment]
Try `cargo +nightly build --benches`.

**Comment by ehuss** [comment]
You can now run `cargo test --bench '*'` to build and run all of the benchmarks in the `benches/` directory, and the libtest test runner will run one iteration to verify that it works.

**Comment by asomers** [comment]
@ehuss that's a perfect solution!
