### ISSUE TITLE
easier way to add crates in cargo

### ISSUE THREAD

**Issue by mrwanashraf** [rust-lang/cargo#6457]
**Describe the problem you are trying to solve**

I'm new to `rust` and i came from `javascript/nodejs` background, 
for me i use `npm` to install packages using `npm install package_name`.

as I was exploring `rust` i learnt about `cargo` and `crates.io`.
and i found that the way to install `crates` in `cargo` is through going to `crates.io` searching for the package then adding it manually to `cargo.toml`.
 that takes lots of time when you wanna add crate(s) and therefore it impacts the developer's productivity.

**Describe the solution you'd like**

is it possible for this feature to be implemented in `cargo` as well? 

to run a command like 
`cargo add crate_name`
or
`cargo install crate_name`

then `cargo` fetches the `crate_name` version adds it to the `cargo.toml` file and finally adds the `crate` to the project?

**Comment by dwijnand** [comment]
Welcome to Rust!  You're looking for the https://github.com/killercup/cargo-edit/ extension of Cargo, which we'll on the way to merging into cargo proper.

**Comment by dwijnand** [comment]
You can track that effort in https://github.com/rust-lang/cargo/issues/5586, if you'd like.

**Comment by mrwanashraf** [comment]
i will , thanks! :+1:

**Comment by cup** [comment]
https://github.com/rust-lang/cargo/issues/1917
https://github.com/rust-lang/cargo/issues/2179
https://github.com/rust-lang/cargo/issues/4
https://github.com/rust-lang/cargo/issues/5586

https://github.com/rust-lang/cargo/issues/6457
https://github.com/rust-lang/cargo/issues/6488
https://github.com/rust-lang/cargo/issues/651
https://github.com/rust-lang/cargo/pull/5611
