### ISSUE TITLE
`cargo test --all` passed but `cargo test` failed

### ISSUE THREAD

**Issue by quake** [rust-lang/cargo#6458]
**Problem**

different testing result between `cargo test --all` and `cargo test`

**Steps**

1. Clone repo: https://github.com/quake/cargo-test
2. run `cargo test --all`, passed
3. run `cargo test`, failed

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo 1.31.0 (339d9f9c8 2018-11-16)

OS: MacOS 10.14.1

**Comment by ehuss** [comment]
I think this is to be expected.  Just because a package is a member of a workspace doesn't mean that all dev-dependencies will be used all the time.  Since you are not running the tests for `lib2` in step 3, the dev-dependencies of `lib2` are not activated.  It's treated as a normal dependency.   Since the dev-dependency isn't activated, that means the feature won't be turned on.

**Comment by alexcrichton** [comment]
Is this another instance of https://github.com/rust-lang/cargo/issues/2589 perhaps?

**Comment by quake** [comment]
> I think this is to be expected. Just because a package is a member of a workspace doesn't mean that all dev-dependencies will be used all the time. Since you are not running the tests for `lib2` in step 3, the dev-dependencies of `lib2` are not activated. It's treated as a normal dependency. Since the dev-dependency isn't activated, that means the feature won't be turned on.

I got it. but how it explains the output result `foo 1` after running `./target/debug/foo` when build with `cargo build --all` ?

**Comment by ehuss** [comment]
> the output result `foo 1` after running `./target/debug/foo` when build with `cargo build --all` ?

Heh, that's #1796.
Just for context, there are a large number of known issues involving features, workspaces, and dependency kinds.  They are mostly tracked [here](https://github.com/rust-lang/cargo/issues?q=is%3Aopen+is%3Aissue+label%3AA-features).  There are different use cases where sometimes people want features and dependencies to be unified, and sometimes they must not be unified.

**Comment by ehuss** [comment]
Yea, I think that captures it.
