### ISSUE TITLE
Let `cargo check` work in lockless mode when `Cargo.lock` is not present

### ISSUE THREAD

**Issue by lucatrv** [rust-lang/cargo#6474]
I originally reported this feature request for RLS, see description [here](https://github.com/rust-lang/rls/issues/1163). However IMHO it does apply to `cargo check` itself, as in my opinion it should just check against what already exists. If `Cargo.lock` is present it should check against it, but if it does not exist it should check against latest crates versions compatible with `Cargo.toml` specifications.

**Comment by epage** [comment]
Looking at the RLS link, the use case seems to be: develop two packages, not in a workspace, and only want the lockfile on the root package.

Is there a reason you aren't putting these in a workspace?  If they are being developed that closely together, it seems like that would be the way to go.  If they aren't developed that closely, then there are [good reasons](https://doc.rust-lang.org/nightly/cargo/faq.html#why-have-cargolock-in-version-control) to have the `Cargo.lock` committed for libs.

**Comment by lucatrv** [comment]
@epage I opened this issue years ago and I do not have the same bin and lib projects available to test anymore, so bear with me if my comment is not accurate. My point was (if I do not mistake) that with that development configuration, issuing `cargo build` only one new `Cargo.lock` file was created in the bin folder, while RLS created also a new `Cargo.lock` file in the lib folder if I edited a file. In other words, if I was developing the project without RLS I ended up with only one `Cargo.lock` file in the bin folder, while if I was developing with RLS then I ended up with two `Cargo.lock` files both in the bin and lib folders. I understand that this was related to issuing `cargo check` in the lib folder.
Workspaces had just been introduced in November 2018, so I was not using them. Please feel free to close this issue if you think it is not valid anymore.
