### ISSUE TITLE
Travis CI .com domain

### ISSUE THREAD

**Issue by sunjay** [rust-lang/cargo#6482]
**Problem**
I just published the [`component_group`](https://crates.io/crates/component_group) crate. The badge for Travis CI doesn't work though because it assumes travis-ci.org. The problem with this assumption is that Travis CI [recently decided](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/) to group all projects under one travis-ci.com domain. New projects are added under this by default.

![image](https://user-images.githubusercontent.com/530939/50388234-55db2b80-06cd-11e9-80d6-acc09e8fe56e.png)

**Possible Solution(s)**

If the domain to use can't be detected automatically, could it be possible to configure which domain to use in Cargo.toml?

**Notes**

Output of `cargo version`:

cargo 1.31.0 (339d9f9c8 2018-11-16)

**Comment by ehuss** [comment]
Thanks for the report! I believe this is better tracked on crates.io at https://github.com/rust-lang/crates.io/issues/1392.  It looks like Travis has a final deadline of the end of January to migrate all open source projects, so always using .com at that time would probably be sufficient.

**Comment by sunjay** [comment]
Thanks! Sorry, I searched in this repo and should have thought to search that one too 😅
