### ISSUE TITLE
`cargo install` should check if binary isn't installed/outdated before downloading crate and it shouldn't fail otherwise

### ISSUE THREAD

**Issue by I60R** [rust-lang/cargo#6485]
Currently with cargo:

```
$ cargo install cargo-pkgbuild         # I have it already installed                                                                                                                                                                            
    Updating crates.io index
  Downloaded cargo-pkgbuild v0.1.1
  Downloaded 1 crates (717.7 KB) in 10.13s
  Installing cargo-pkgbuild v0.1.1
error: binary `cargo-pkgbuild` already exists in destination as part of `cargo-pkgbuild v0.1.1 (/home/igor/Rust/cargo-pkgbuild)`
Add --force to overwrite
```

This exits with 101 error code. But for me it seems that downloading crate and issuing an error here doesn't make any sense.

E.g. rustup has expected behavior:

```
$ rustup component add clippy              # It's also installed
info: component 'clippy' for target 'x86_64-unknown-linux-gnu' is up to date
```

This exits with 0.

---

Just failed into that on CI setup and wondered why this problem exists at all

**Comment by k-nasa** [comment]
I'll take this task, is it ok❓

**Comment by dwijnand** [comment]
Sure!  Btw, I recently discovered https://crates.io/crates/cargo-ensure-installed which seems to be the workaround for this.

**Comment by k-nasa** [comment]
OK! Thank you

**Comment by colindean** [comment]
I encountered this just now while setting up a new project that needed a few cargo-provided binaries to be available as a part of a make task. I'd love to see this built into `cargo install` as an option, perhaps `--ensure` or something like that.

**Comment by ehuss** [comment]
Pinging anyone following this issue, I have a proposal to add upgrade functionality to `cargo install` at #6667.  If you have any comments, I would appreciate if you can leave some over on that issue.
