### ISSUE TITLE
"cargo install" doesn't read the "rustflags" setting in .cargo/config

### ISSUE THREAD

**Issue by xaon** [rust-lang/cargo#6487]
**Problem**

`Cargo install` command doesn't read the `rustflags` setting in `.cargo/config`

**Steps**

In order to fix a linker issue on macOS (https://github.com/alexcrichton/git2-rs/issues/180), i have to use something like: `RUSTFLAGS='-L /usr/lib' cargo build`.

And I put this flag inside `{project-folder}/.cargo/config` file: 

```
[build]
rustflags = ["-L", "/usr/lib"]
```
This works for `cargo build`, but not `cargo install`

It looks like `cargo install` ignores that setting.
I have to use `RUSTFLAGS='-L /usr/lib' cargo install --path .` to make it work again.

i also tried something like: 

```
[targer.x86_64-apple-darwin]
rustflags = ["-L", "/usr/lib"]
```
No luck either.

**Notes**

Output of `cargo version`:

```
$ cargo version
cargo 1.31.0 (339d9f9c8 2018-11-16)
```

Operating System: macOS High Sierra, 10.13.6

I have `edition = "2018"` in `Cargo.toml`

**Comment by dwijnand** [comment]
As suggested in https://github.com/rust-lang/cargo/pull/6026#issuecomment-421519652 `cargo install --path .` _should_ read `.cargo/config` in my, and Mark's, opinion.

**Comment by xaon** [comment]
Thanks for the pointer @Eh2406 .

Yes, I agree with @dwijnand  and @Mark-Simulacrum , that there should be a way to provide "local configuration"

Just created a feature request (#6498) to keep it tracked.

**Comment by xaon** [comment]
Yes @dwijnand , closing this one.
