### ISSUE TITLE
Ability to `cargo install <dependency>@<version>` should update `Cargo.toml`

### ISSUE THREAD

**Issue by shaunwarman** [rust-lang/cargo#6488]
>Warning: New to rust. 

**Problem**
It seems to add a dependency using cargo to my rust project, I need to manually alter `Cargo.toml` directly. For bootstrapping projects, this seems a bit slow and cumbersome.

**Solution**
It would be great to just `cargo install <dependency>@<version>` or `cargo install <dep_1> <dep_2> <dep_3>` where dependencies 1 thru 3 are installed as the latest and `Cargo.toml` is updated appropriately.

Instead of README's adding:
```
# Cargo.toml
[dependencies]
<dependency> = "<version>"
```
Make it easy for consumers of the crate via:
```
cargo install --save <dependency>@<version>
```

**Comment by carols10cents** [comment]
You can do this today with the [cargo-edit crate](https://crates.io/crates/cargo-edit)! There are plans to integrate cargo-edit into Cargo proper, which is tracked in https://github.com/rust-lang/cargo/issues/5586, so I'm going to close this in favor of that issue. Thanks!

**Comment by cup** [comment]
https://github.com/rust-lang/cargo/issues/1917
https://github.com/rust-lang/cargo/issues/2179
https://github.com/rust-lang/cargo/issues/4
https://github.com/rust-lang/cargo/issues/5586
https://github.com/rust-lang/cargo/issues/6457

https://github.com/rust-lang/cargo/issues/6488
https://github.com/rust-lang/cargo/issues/651
https://github.com/rust-lang/cargo/pull/5611
