### ISSUE TITLE
RFC: Be able to provide "local configuration" while installing a "local crate"

### ISSUE THREAD

**Issue by xaon** [rust-lang/cargo#6498]
**Describe the problem you are trying to solve**

After #6026, `cargo install` will only use the configuration file at `~/.cargo/config`
However, it would be nice to be able to provide a "local configuration" while installing a "local crate"

**Describe the solution you'd like**

While installing a local crate using `cargo install --path {proj-folder}`, either:

**Only** look for `{proj-folder}/.cargo/config`, 

or

First look for `{proj-folder}/.cargo/config`, and then fall back to `~/.cargo/config` if it doesn't exist.

**Comment by dwijnand** [comment]
In #6026 @alexcrichton indicated this behaviour could land in a future PR, so I've marked this proposal as accepted.
