### ISSUE TITLE
Questions regarding `registry-index`.

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6499]
The ability to specify an alternate registry via URL with `registry-index` in a dependency was added in #4957.  I had some questions about this:
- Should this be documented?
- Why was it chosen to use a different key instead of reusing the `registry` field as suggested in the RFC? 
- How is it supposed to work? `cargo publish` doesn't seem to handle it properly.  There are almost no tests for it.

cc @sfackler

**Comment by sfackler** [comment]
`registry` is elaborated into `registry-index` by `cargo package` so that the published crate doesn't depend on what the user decided the name of the registry should be. It's basically an implementation detail and shouldn't be used by people directly.

**Comment by sfackler** [comment]
The linked issue goes into more detail: https://github.com/rust-lang/cargo/issues/4880

**Comment by sfackler** [comment]
https://github.com/rust-lang/cargo/issues/4880#issuecomment-358506926

**Comment by sfackler** [comment]
The registry name is resolved to a URL at manifest parse time. We definitely parse the manifest, or there'd be no reason to go through all the effort of canonicalizing it in the first place.

**Comment by ehuss** [comment]
Ah, yea, I understand now. I'm working on a PR at #6500, and I updated it with some fixes related to this. If you have some time to look at it and provide feedback, I'd appreciate it.
