### ISSUE TITLE
"cargo package" by default seems to produce a debug build

### ISSUE THREAD

**Issue by apiraino** [rust-lang/cargo#6508]
**Problem**
`cargo package` by default seems to produce a `debug` build. I couldn't find a way / param to tweak the build, nor did I find help in the [publishing documentation](https://doc.rust-lang.org/cargo/reference/publishing.html) - still possible that I've missed some other resource.
In case this is not an actionable parameter, we might want to change this behaviour and publish on `crates.io` the optimized binary. A parameter flag is not even necessary (imo).

**Steps**
```
$ cargo package
   Packaging prj v0.1.4 (/home/user/prj)
   Verifying prj v0.1.4 (/home/user/prj)
   Updating crates.io index
   Compiling ...
   ...
   Finished dev [unoptimized + debuginfo] target(s) in 31.81s                                
```

**Possible Solution(s)**
Would it make sense to change the default [compile flag here](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/build_config.rs#L85)?
```
--- a/src/cargo/core/compiler/build_config.rs
+++ b/src/cargo/core/compiler/build_config.rs
@@ -82,7 +82,7 @@ impl BuildConfig {
         Ok(BuildConfig {
             requested_target: target,
             jobs,
-            release: false,
+            release: true,
             mode,
             message_format: MessageFormat::Human,
             force_rebuild: false,
```

**Notes**

Output of `cargo version`:
`cargo 1.31.0 (339d9f9c8 2018-11-16)`

**Comment by ehuss** [comment]
The binary is not published in the crate. It only builds it to verify that it is in a buildable state.
