### ISSUE TITLE
cargo dependency subcommands

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/cargo#651]
Hi,

I had a few ideas for new cargo commands, I think they're fairly self explanatory: 

    cargo dependency add nickel --git https://github.com/nickel-org/nickel.rs.git

    cargo dependency rm nickel
    
    cargo dependency lint
    Checks for unused dependencies, out-of-date dependencies, etc.
    
Thoughts?

**Comment by alexcrichton** [comment]
I think https://github.com/killercup/cargo-edit serves this quite well!

**Comment by cup** [comment]
https://github.com/rust-lang/cargo/issues/1917
https://github.com/rust-lang/cargo/issues/2179
https://github.com/rust-lang/cargo/issues/4
https://github.com/rust-lang/cargo/issues/5586
https://github.com/rust-lang/cargo/issues/6457
https://github.com/rust-lang/cargo/issues/6488

https://github.com/rust-lang/cargo/issues/651
https://github.com/rust-lang/cargo/pull/5611
