### ISSUE TITLE
Downloading a single package is much more painful on master than on 0.31

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#6518]
**Problem**

Downloading a single package in `cargo` 0.31 was as simple as:

```rust
let package_id: PackageId;
let package = source.source.download(&package_id)?;
```

With `cargo` master one needs to: 

```rust
let package_ids: [PackageId];  
let source: Box<Source + 'a>;
let config: Config;
let sources = {
    let mut s = SourceMap::new();
    s.insert(source);
    s
};

let package_set = PackageSet::new(&package_ids, sources, config)?;
let mut downloads = package_set.enable_download()?;
let package = if let Some(package) = downloads.start(package_ids[0])? {
    package
} else {
    downloads.wait()?;
    downloads.start(package_ids[0])?.expect("started download did not finish after wait")
};
```

This feels like a big API regression.

**Comment by alexcrichton** [comment]
FWIW [`get_one`](https://docs.rs/cargo/0.32.0/cargo/core/package/struct.PackageSet.html#method.get_one) was added as a convenience to do all this

**Comment by gnzlbg** [comment]
Thanks! `get_one` cuts it down to:

```rust
```rust
let package_ids: [PackageId];  
let source: Box<Source + 'a>;
let config: Config;
let sources = {
    let mut s = SourceMap::new();
    s.insert(source);
    s
};

let package_set = PackageSet::new(&package_ids, sources, config)?;
let package = package_set.get_one(package_ids[0])?;
```

**Comment by dwijnand** [comment]
I feel bad for the libraries removal thing.  I'd be happy to try and land some improvements to the API if you have any recommendations...

**Comment by gnzlbg** [comment]
@dwijnand I pretty much agree with you that we should be able to do that via the `cargo metadata` somehow. I've opened an issue about that in the `cargo-metadata` bindings (https://github.com/oli-obk/cargo_metadata/issues/60 ) and it might make more sense to improve the bindings to support that, also improving `cargo metadata` as required.

We can revisit adding a better API to cargo for that if the `cargo metadata` approach ends up being too complicated.

**Comment by dwijnand** [comment]
Good to hear!

But I actually was thinking for the single download API.  Perhaps source.source could have a download method that does the necessary packageset/sourcemap setup to download a package.

**Comment by gnzlbg** [comment]
That would help!

**Comment by dwijnand** [comment]
So I was looking back at this, trying to understand what cargo API rust-semverver used to use that's now gone.  And I'm confused because `source.download(&package_id)` still exists:

https://github.com/rust-lang/cargo/blob/23fa4003bae555f2c4a5037928584384ca2f20a2/src/cargo/core/source/mod.rs#L50-L52

So going back to the outset, why doesn't that work any more?

**Comment by ehuss** [comment]
@dwijnand It was changed to return a `MaybePackage`, so it doesn't actually download.  `PackageSet` can be used to download now.
