### ISSUE TITLE
Regression in target-specific dev-dependencies

### ISSUE THREAD

**Issue by RandomInsano** [rust-lang/cargo#6523]
**Problem**

It seems that `[target.'cfg(unix)'.dev-dependencies]` no longer works.

I've copy & pasted the line from [this documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#development-dependencies) but it unfortunately doesn't work. However, it's workng a-okay with just 'dependencies'.

Tested both with 1.31 as well as the 2019-01-03 nightly.

**Steps**

Start with a handy Cargo.toml:
```
[package]
name = "test-cargo"
version = "0.1.0"
authors = ["Me <someone@example.com>"]
edition = "2018"

[dependencies]

[target.'cfg(unix)'.dev-dependencies]
bitflags = "1.0.4"
```

Try building it:

```text
me@pi-02:~/Documents/Code/rust/test-cargo $ cargo build
    Updating crates.io index
   Compiling test-cargo v0.1.0 (/home/me/Documents/Code/rust/test-cargo)                                                    
    Finished dev [unoptimized + debuginfo] target(s) in 9.17s                                                                        
```

Now, remove the four '-dev' characters from the Cargo.toml and run it again:
```
me@pi-02:~/Documents/Code/rust/test-cargo $ cargo build
   Compiling bitflags v1.0.4                                                                                                         
   Compiling test-cargo v0.1.0 (/home/me/Documents/Code/rust/test-cargo)                                                    
    Finished dev [unoptimized + debuginfo] target(s) in 5.24s                                                                        
```

I'm a fairly niche use-case as I'm running `rls` and VSCode on Mac but my testing platform is Linux. I don't expect a lot of people are feature-gating their dev dependencies, but the docs claim this should be working.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

cargo 1.31.0 (339d9f9c8 2018-11-16)

**Comment by ehuss** [comment]
dev-dependencies are not built unless they are needed.  You need to build a test, bench, or example to get it to build it.

**Comment by RandomInsano** [comment]
Ugh. I've been the source of quite a bit of noise here this week. Thanks @ehuss
