### ISSUE TITLE
cargo fix --edition-idioms removes `extern crate test`

### ISSUE THREAD

**Issue by Apanatshka** [rust-lang/cargo#6524]
[The Rust Edition Guide clearly states exceptions to the rule of removing `extern crate`](https://rust-lang-nursery.github.io/edition-guide/rust-2018/module-system/path-clarity.html#an-exception), but it looks like `cargo fix --edition-idioms` does not take these exceptions into account.

**Comment by ehuss** [comment]
It should be working.  Crates like `proc_macro` and `test` are preserved.

Without any more detail, I can only guess what you're running into.  In particular, I'm guessing you are using `extern crate test` in a non-bench target, and not protecting it with `#[cfg(test)]`.  If that's the case, then it's not too surprising that when fixing the target, it doesn't see that `test` is used and it gets removed.  Any of the following in something like lib.rs should work.

```rust
#![feature(test)]
#![warn(rust_2018_idioms)]

#[cfg(test)]  // cfg here is important
extern crate test;

#[bench]
fn bench(b: &mut test::Bencher) {
    b.iter(|| {})
}
```

or

```rust
#![feature(test)]
#![warn(rust_2018_idioms)]

#[cfg(test)]  // cfg here is important
mod tests {
    extern crate test;

    #[bench]
    fn bench(b: &mut test::Bencher) {
        b.iter(|| {})
    }
}
```

Can you show an example of what you're running into?

**Comment by Apanatshka** [comment]
I shouldn't have assumed 😳 

I'm using `extern crate test` in a bench target, namely [`benches/basic.rs`](https://github.com/Apanatshka/dnfa/blob/5cdb4307a06aee51f2d19f2619e0ff2e5e49af18/benches/basic.rs#L3) and [`benches/sherlock.rs`](https://github.com/Apanatshka/dnfa/blob/5cdb4307a06aee51f2d19f2619e0ff2e5e49af18/benches/sherlock.rs#L3) (I'm linking to the Rust 2015 version of the code here). Am I mistaken and should I add a `#[cfg(test)]` to the `extern crate`?

**Comment by ehuss** [comment]
It shouldn't be necessary. I can't reproduce it with a normal benchmark. Can you show me a complete example (source and Cargo.toml)?

**Comment by ehuss** [comment]
Oh, sorry, I missed the link.  Thanks for the info.  It looks like the idiom lint doesn't properly handle usage nested within a module.  As a temporary workaround, you can tag the `extern crate` with `#![allow(unused)]`.

@alexcrichton here's a repro.  Would you like me to file these in rust-lang/rust?  
```rust
#![warn(rust_2018_idioms)]

extern crate proc_macro;  // suggests removing this which is incorrect.

pub mod m {
    pub fn f(_ts: proc_macro::TokenStream) {
    }
}

**Comment by alexcrichton** [comment]
@ehuss yeah that'd be great! These are all inevitably rust-lang/rust bugs rather than Cargo bugs, I originally just wanted a location to funnel through the bugs to sift out cargo-fix related noise (aka bugs in cargo-fix itself).
