### ISSUE TITLE
cargo fix should serialize on entire workspace

### ISSUE THREAD

**Issue by baumanj** [rust-lang/cargo#6528]
(Edit ehuss): `cargo fix` in a workspace should serialize across the entire workspace (currently it only locks each package). This is needed if something like `include!` is used in multiple packages to the same file.  The two packages will attempt to fix the shared file at the same time, causing problems.

## Original Issue

Starting from https://github.com/habitat-sh/habitat/tree/066d60d52d4e65c6978d6a8f62962035b5fa4ba5, applying `cargo fix --edition-idioms` led to compilation errors, so I'm filing a bug report per the output's request. Some additional system information:

```
➤ rustc --version
rustc 1.31.0 (abe02cefd 2018-12-04)

09:18:05 AM jbauman@ubuntu:~
➤ cargo --version
cargo 1.31.0 (339d9f9c8 2018-11-16)

➤ uname -a
Linux ubuntu 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

If I find any interesting information in fixing up the errors, I'll post a follow-up. In the meantime, I'm attaching the full output of the cargo fix command.
[cargo-fix-output.txt](https://github.com/rust-lang/cargo/files/2733625/cargo-fix-output.txt)

**Comment by ehuss** [comment]
Yikes, that's quite a few issues.  I noticed that your initial edition transition did not fix non-linux targets. Any code marked with things like `#[cfg(target_os = "macos")]` is currently broken.  Dealing with `cfg` blocks is something that `cargo fix` doesn't handle too well.

I can try to reduce some of the errors. I already see a few that haven't been reported before.

**Comment by baumanj** [comment]
[Here are the fixes that I made](https://github.com/habitat-sh/habitat/pull/6041/commits/a12523e0a068a4651ac315f37e2349bec9d7e671) to get things building again (at least on linux) after running `cargo fix --edition-idioms`.

**Comment by ehuss** [comment]
> Should I file a separate issue for that

Nah, I'm finding quite a few different issues, and I'll file upstream and link here once I've got them all.

**Comment by ehuss** [comment]
OK, not sure if I got all of them, but here's what I found:

- `include!` of the same file from multiple crates in a workspace causes them to conflict when they are fixed simultaneously.  This is similar to #6434, but across crates.  @alexcrichton would it be worth serializing crates in a workspace during `cargo fix`?
- unused_extern_crates: does not handle cfg attributes — https://github.com/rust-lang/rust/issues/57420
- unused_extern_crates: does not handle renamed crates used in other modules — https://github.com/rust-lang/rust/issues/57421
- edition compatbility lint: fails to handle macro and crate with same name — https://github.com/rust-lang/rust/issues/57422

@baumanj Have you been able to get everything working?  Let me know if you have any questions, or anything you can't figure out.

**Comment by alexcrichton** [comment]
@ehuss oh jeez, but yeah for now seems like we need to serialize workspace crates, not just packages

**Comment by baumanj** [comment]
> @baumanj Have you been able to get everything working? Let me know if you have any questions, or anything you can't figure out.

I think so! Everything builds locally, but we're having an issue with our CI so can't say for certain that it's working on all platforms. I don't anticipate any further cargo-related issues, but if there's anything relevant, I'll follow up here.

Thanks for being so responsive and all your awesome work here!
