### ISSUE TITLE
Cargo run should have a `quiet` option

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/cargo#653]
`cargo run` prints out a lot of extra info ("Compiling ...", "Running ...") to stdout, which sometimes is annoying if you want to pipe the output elsewhere. A `--quiet` option to silence all `stdout` output except that from the program itself would be nice.

**Comment by samuela** [comment]
Why was this closed? What was the resolution?

**Comment by Manishearth** [comment]
The quiet option was added, see https://github.com/rust-lang/cargo/commit/88e557fbdcdf754929c8dcd33f630fc2423971eb and https://github.com/rust-lang/cargo/pull/1748
