### ISSUE TITLE
Do not deprecate cargo install from current directory

### ISSUE THREAD

**Issue by xlz** [rust-lang/cargo#6538]
Previous: https://github.com/rust-lang/cargo/issues/5327

The decision was `cargo install` from current directory is deprecated and will be removed soon.

I find this hard to accept as a new user to Rust. Since Rust is branded as the next big system programming language I would expect it to respect systems conventions, i.e. the deployment holy trinity:
```
./configure
make
make install
```
in which `make install` installs built binaries to appropriate locations so the user can run the binaries without adding `./` prefixes. Now, since Rust has batteries included we can skip `./configure` and reasonably expect a `build` argument in place of `make`, but why break the expectation of `make install`?

For a command so central to daily workflows, `cargo install --path .` makes it suboptimal by allowing a space of ambiguities: is it `cargo install .`, `cargo install --local`, `cargo install --path=.`, `cargo install --^H^HI still have to check --help`? 

For the node crowd they can always do `cargo uninstall` if `cargo install` is not what they expect, but if I have to look up the documentation just for the equivalent of `make install` something is wrong here.

**Comment by matklad** [comment]
Note that `cargo install` differs significantly from `make install`: it doesn't install stuff into "appropriate location" (`/usr/bin`), it installs into `~/.cargo/bin`, and it doesn't work with libraries at all. So I guess "`cargo install` is not equal to `X install`, please read the docs" applies in this case as well.

**Comment by xlz** [comment]
`make install` without sudo installs things into `/usr/local/bin`, which is not that different from `~/.cargo/bin` as they are both modifiable by non-root users and located in $PATH by default.

**Comment by t3hmrman** [comment]
So I just ran into this while porting a `Dockerfile` (and was surprised by it, but the error messages from Cargo were extremely helpful as always) -- while I think it's nice to have `cargo install` still get transformed for `cargo install --path .` for new users, the comparison to `make` here is not a good leg to stand on IMO.

Make sits *above* compilation tools, `cargo` is a compilation tool that would be used *by* make, so I don't think they're equivalent. Projects that want to follow the usual flow (`configure` + `make` + `make install`) should add `Makefiles` (I do this on every project), and hide the fact that `cargo` is being used at all (maybe sometimes it's `rustc` directly).

At present I think this is purely an ergonomics issue, and is going to be very hard to prove either way.

**Comment by nrc** [comment]
We discussed this in today's Cargo team meeting. While we understand the motivation for wanting to keep the old behaviour of `cargo install`, we still believe that the advantages of removing a footgun for some users outweighs the convenience of eliding an argument. Cargo is not very similar to `make`, and indeed from the classic commands in the OP, `make install` is the only one that is reflected in Cargo, so we did not feel that it was a very important similarity to keep around.

**Comment by haydonryan** [comment]
This was a step backwards in my opinion.  

Having to run cargo install --path . vs cargo install for simple projects makes it harder.  It would be nice to add an "allow from current" flag in cargo.toml so that if the writer of the app deems it safe it's ok.

Personally I don't understand what footgun you're trying to avoid.
