### ISSUE TITLE
Tilde in --extend-css path works with rustdoc but not cargo

### ISSUE THREAD

**Issue by Evanjs** [rust-lang/cargo#6541]
**Problem**
#### Expected behavior:
When specifying RUSTDOCFLAGS with extend-css and a path containing a tilde, use the given style for rustdoc.
#### Actual behavior:
Cargo fails to use the given file, and returns the error `option --extend-css argument must be a file`

**Steps**

1. `RUSTDOCFLAGS="--extend-css ~/path/to/style.css" cargo doc`
2. Get error message

**Possible Solution(s)**

The attempted rustdoc commands seem to wrap the style path with apostrophes (e.g. ` --extend-css '~/src/rustdoc_styles/ayu.css'`).
Removing these apostrophes and running the same rustdoc commands seem to work fine:
``` rust
rustdoc --crate-name void /home/evanjs/.cargo/registry/src/github.com-1ecc6299db9ec823/void-1.0.2/src/lib.rs --cap-lints allow --color always -o /home/evanjs/src/rrbg/target/doc -L dependency=/home/evanjs/src/rrbg/target/debug/deps --extend-css '~/src/rustdoc_styles/ayu.css'
```
 becomes 
```rust
rustdoc --crate-name void /home/evanjs/.cargo/registry/src/github.com-1ecc6299db9ec823/void-1.0.2/src/lib.rs --cap-lints allow --color always -o /home/evanjs/src/rrbg/target/doc -L dependency=/home/evanjs/src/rrbg/target/debug/deps --extend-css ~/src/rustdoc_styles/ayu.css
```

**Notes**

Output of `cargo version`:
cargo 1.33.0-nightly (34320dhttps://github.com/rust-lang/cargo/issues/6541212 2019-01-03)

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.0, NixOS, 18.09.1853.c2950341d03 (Jellyfish)`

``` rust
RUSTDOCFLAGS="--extend-css ~/src/rustdoc_styles/ayu.css" cargo rustdoc
```
seems to work totally fine, though it does not cover dependencies.
`$HOME` and `/home/user/` work fine.

I did see https://github.com/rust-lang/cargo/issues/4253, but wasn't sure if the issue is the same.  Seems odd that it would work in rustdoc but not if it goes through cargo, first.

### Originally discovered in https://github.com/Cldfire/ayu-rs/issues/23

**Comment by alexcrichton** [comment]
Thanks for the report! Tilde expansion happens in your shell, not in Cargo or rustc or other related tooling. The shell doesn't expand tildes I think in the middle of env vars, so you'll want to use `$HOME` which will get expanded.

**Comment by Evanjs** [comment]
Thanks, Alex.  Sometimes I just need to say or hear the problem out loud.  In this case, it was putting ~ in an environment variable, so of course it's not going to be evaluated, and on top of that, rustdoc takes it as a normal flag, so of course it's going to work there 😅
