### ISSUE TITLE
cargo misses crate for --target=aarch64-pc-windows-msvc

### ISSUE THREAD

**Issue by EwoutH** [rust-lang/cargo#6551]
**Problem**
`cargo` fails to build when the build target is set to `aarch64-pc-windows-msvc` because is can't find a create for `core`.

I realize the target `aarch64-pc-windows-msvc` is in it's early stages of development, hopefully makes that this bug report usefull.

```
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-pc-windows-msvc` target may not be installed
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
error: Could not compile `unicode-xid`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Command exited with code 101
```

**Steps**

**1.** Clone rav1e from git, fetch PR 854, fetch head:
```
git clone -q https://github.com/xiph/rav1e.git C:\projects\rav1e
git fetch -q origin +refs/pull/854/merge:
git checkout -qf FETCH_HEAD
```
**2.** Download supporting files, extract them:
https://win.rustup.rs/
https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip
```
7z e -y nasm.zip
```
**3.** `Run rustup-init` (change --default-host for Linux)
```
rustup-init -yv --default-toolchain nightly
```
**4.** And run `cargo`
```
cargo build --release --target=aarch64-pc-windows-msvc
```

**Cargo version:** `
```
cargo 1.33.0-nightly (34320d212 2019-01-03)
release: 1.33.0
commit-hash: 34320d212dca8cd27d06ce93c16c6151f46fcf2e
commit-date: 2019-01-03
```
**Rust version:**
```
rustc 1.33.0-nightly (2fadb0a16 2019-01-13)
binary: rustc
commit-hash: 2fadb0a16c8737a45746e95df9138912590ed8ad
commit-date: 2019-01-13
host: x86_64-pc-windows-msvc
release: 1.33.0-nightly
LLVM version: 8.0
```

Full log: https://ci.appveyor.com/project/tdaede/rav1e/builds/21613314/job/cvd4nmgjlmmpixxg

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this is a case of a forgotten `rustup target add aarch64-pc-windows-msvc`, but other than that you should be good to go!

**Comment by EwoutH** [comment]
@alexcrichton Thanks! Adding `rustup target add aarch64-pc-windows-msvc` helped indeed.

May I ask why it's not added by default?

Now I get a load of errors (`E0206`, `E0412`, `E0425` and `E0432`) when compling `winapi v0.3.6`, will file a bugreport there.

**Comment by alexcrichton** [comment]
A good question! Currently we only install the host target by default (like `x86_64-pc-windows-msvc`). There's dozens of targets to add so we wouldn't want to install them all by default!
