### ISSUE TITLE
Make source offer for libgit2

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#657]
Because we ship Cargo binaries that include GPL software, to be in compliance with the GPL, we  have to provide the original matching source of the GPL software in a form that can be used to build the shipped version of Cargo. To fulfill the spirit of the GPL this probably also means providing the source for the revision of Cargo and all non-GPL dependencies used to produce the binary.
Doing this is a fair technical challenge, and since Cargo builds with Cargo, will probably involve teaching Cargo how to publish source in such a form when publishing binaries.

In the near term I think we should make a weak effort to comply, and in the README put text like, "in binary form, this product includes software that is licensed under the terms of the GNU General Public License, version 2, with a linking exception, which can be obtained from the [upstream repository](link to repo)".

**Comment by alexcrichton** [comment]
Closing due to @brson's last comment.
