### ISSUE TITLE
New Cargo progress bar jittery in Emacs terms

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/cargo#6574]
If I run `cargo run` in any Emacs terms like `ansi-term` or `term`, it will always display the progress bar and won't animate correctly. See here for a screen recording comparing it to other progress bars working fine in Emacs as well as to itself working fine in my regular terminal: https://youtu.be/AJjVSsu5RSI

It also seems like it takes time to run again in Emacs and always shows the progress bar, even after not changing any code. In the normal, non-Emacs terminal if I don't change any code it seems to just run immediately without showing the bar at all.

Output of `cargo version`: cargo 1.32.0 (8610973aa 2019-01-02)

**Comment by alexcrichton** [comment]
Thanks for this! I think that this is related to the large number of draws that are being done, and I've noticed this on my Windows machine as well where the terminal is quite slow. Most of the time the progress bars are throttled in updates to ensure we don't overload the terminal, but in this case I think we unconditionally update the progress bar to have the most accurate information. 

@kennytm or @ehuss would y'all be willing to look into this? I think there's two things we could tackle here:

* One is that I think we clear current progress from the terminal a bit too aggressively. I think we pessimistically do it in some cases where we *could* print other information, but it ends up not being necessary in many cases. (this causes some flickering I believe)
* The second is that we're unconditionally updating the terminal whenever a crate completes, but all "fresh" crates finish in the first half second which causes a huge number of draws. I think we'll want to throttle this somehow and live with a terminal that may be wrong for 100-200ms
