### ISSUE TITLE
source command not work 

### ISSUE THREAD

**Issue by duvalCC** [rust-lang/cargo#6580]
**Problem**
 source command not work well.
```
source ~/.bash_profile
```

**Steps**
1. I try to delete an environment variable in file ~/.bash_profile, and source it .
2. Cargo run my code to print all env variables.That deleted dev is still existed. It seems like a bug ?
```
fn main() {
    for (name,value) in env::vars(){
        println!("{}->{}",name,value)

    }
}
```

**Notes**

Output of `cargo version`:
cargo 1.32.0-nightly (b3d0b2e54 2018-11-15)

macOs Mojave 10.14.2

**Comment by dwijnand** [comment]
I can't reproduce it:

```bash
10:22:05 $ more src/main.rs
fn main() {
    for (name,value) in std::env::vars(){
        if name == "FOO" {
            println!("{}->{}",name,value)
        }
    }
}

10:22:13 $ more source-me.bash
unset FOO

10:22:17 $ export FOO=1

10:22:21 $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/t-cargo-unset-env-var`
FOO->1

10:22:24 $ source source-me.bash

10:22:28 $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/t-cargo-unset-env-var`

10:22:31 $
```

Does my reproduction match yours?

**Comment by duvalCC** [comment]
@dwijnand   I see. I need to unset the env variables to disable it. thanks
