### ISSUE TITLE
cargo 1.30.0 doesn't compile under 32-bit Funtoo

### ISSUE THREAD

**Issue by mauricev** [rust-lang/cargo#6586]
When I try to emerge cargo after rust has been installed, presumably with cargo support, cargo fails to build with the error
```
error: process didn't exit successfully: `rustc -vV` (exit code: 1)
--- stdout
rustc 1.29.2
binary: rustc
commit-hash: unknown
commit-date: unknown
host: i686-unknown-linux-gnu
release: 1.29.2

--- stderr
error: failed to find a `codegen-backends` folder in the sysroot candidates:
* /usr
* /usr/lib
```
I found codegen-backends at /usr/lib/rust-1.29.2/rust-1.29.2/rustlib/i686-unknown-linux-gnu/codegen-backends, and I tried copying it to /usr and /usr/lib, but cargo still complains.

**Comment by ehuss** [comment]
This sounds like an issue with how rust was installed.  Did you install it with a package manager? Which platform are you on? How did you install rust?

**Comment by mauricev** [comment]
Rust was installed via the standard way to install packages on Funtoo, via emerge. I filed a bug there, https://bugs.funtoo.org/browse/FL-6161 too as I don't know whether the bug is intrinsic to the 32-bit installation of cargo anywhere or specific to Funtoo.

**Comment by ehuss** [comment]
The funtoo issue seems to be resolved.
