### ISSUE TITLE
Cargo does not build in latest FreeBSD

### ISSUE THREAD

**Issue by BSDer** [rust-lang/cargo#6612]
Hi,
Cargo does not build in latest FreeBSD because it bootstraps from an unsupported old version.

There is an open bug in FreeBSD but it seems the problem is from upstream (here).
Please check out https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235241

I tried this:
    cd /usr/ports/lang/rust
    make
and got:
```
...
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/share/doc/cargo/LICENSE-APACHE
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/share/doc/cargo/LICENSE-MIT
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/share/doc/cargo/LICENSE-THIRD-PARTY
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/share/doc/cargo/README.md
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/manifest.in
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/etc/bash_completion.d/cargo
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/bin/cargo
  extracting cargo-0.32.0-x86_64-unknown-freebsd/cargo/share/zsh/site-functions/_cargo
running: /usr/ports/lang/rust/work/rustc-1.32.0-src/build/x86_64-unknown-freebsd/stage0/bin/cargo build --manifest-path /usr/ports/lang/rust/work/rustc-1.32.0-src/src/bootstrap/Cargo.toml --frozen
Traceback (most recent call last):
  File "/usr/ports/lang/rust/work/rustc-1.32.0-src/x.py", line 20, in <module>
    bootstrap.main()
  File "/usr/ports/lang/rust/work/rustc-1.32.0-src/src/bootstrap/bootstrap.py", line 853, in main  
    bootstrap(help_triggered)
  File "/usr/ports/lang/rust/work/rustc-1.32.0-src/src/bootstrap/bootstrap.py", line 824, in bootstrap
    build.build_bootstrap()
  File "/usr/ports/lang/rust/work/rustc-1.32.0-src/src/bootstrap/bootstrap.py", line 652, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/usr/ports/lang/rust/work/rustc-1.32.0-src/src/bootstrap/bootstrap.py", line 151, in run   
    raise RuntimeError(err)
RuntimeError: failed to run: /usr/ports/lang/rust/work/rustc-1.32.0-src/build/x86_64-unknown-freebsd/stage0/bin/cargo build --manifest-path /usr/ports/lang/rust/work/rustc-1.32.0-src/src/bootstrap/Cargo.toml --frozen
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/lang/rust
*** Error code 1

Stop.
make: stopped in /usr/ports/lang/rust
```

Now, while the above is FreeBSD specific, the problem is that cargo depends on itself to be built, so we have to bootstrap from somewhere. We currently bootstrap from:
https://static.rust-lang.org/dist/2018-12-20/cargo-0.32.0-x86_64-unknown-freebsd.tar.gz
which has a very old cargo binary:
```
# file /usr/ports/lang/rust/work/rustc-1.32.0-src/build/x86_64-unknown-freebsd/stage0/bin/cargo
/usr/ports/lang/rust/work/rustc-1.32.0-src/build/x86_64-unknown-freebsd/stage0/bin/cargo: ELF 64-bit LSB shared object, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 10.3, FreeBSD-style, with debug_info, not stripped
```

As you can see it's for *FreeBSD 10.3* which is now in EoL.

I lack the knowledge to bootstrap a new cargo for FreeBSD 12.0 or 13 (CURRENT). Can someone point me to the right direction?

I have given cargo a try but anything that is built on FreeBSD <12.0 does not run on >=12.0.
```
# cargo --version
Bad system call (core dumped)
```
Thank you.

**Comment by tmfink-juniper** [comment]
I agree that this is important.

FreeBSD Wiki page:
https://wiki.freebsd.org/Rust

Notes on bootstrapping Rust/Cargo for FreeBSD/aarch64:
https://gist.github.com/dumbbell/b587da50ef014078da9e732a4331ebad

**Comment by mati865** [comment]
> Bad system call (core dumped)

Could you debug it to see what was called?

**Comment by bdrewery** [comment]
This should be closed (as the FreeBSD bug was as well). The reported bug was due to lack of FreeBSD10 ABI compatibility in the kernel. This is needed due to the compat solution I put in place last year. It's in the standard GENERIC FreeBSD kernel config as well.
