### ISSUE TITLE
meta_test_multiple_versions_strategy is spuriously failing

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6613]
`meta_test_multiple_versions_strategy` has failed a few times during CI:

- Nov 9: https://github.com/rust-lang/rust/pull/55637#issuecomment-437382988
- Jan 25: https://github.com/rust-lang/cargo/pull/6599#issuecomment-457733984
- Jan 29: https://github.com/rust-lang/rust/pull/57495#issuecomment-458800983

with errors that look like:

thread 'support::resolver::meta_test_multiple_versions_strategy' panicked at 'In 1280 tries we did not see a wide enough distribution of multiple versions of the same library! dis: [1099, 45, 31, 16, 20, 15, 3, 3, 0, 9]', tests/testsuite/support/resolver.rs:564:5

thread 'support::resolver::meta_test_multiple_versions_strategy' panicked at 'In 1280 tries we did not see a wide enough distribution of multiple versions of the same library! dis: [1026, 75, 30, 24, 14, 5, 4, 7, 0, 19]', src/tools/cargo/tests/testsuite/support/resolver.rs:564:5

**Comment by ehuss** [comment]
Hit again today.
---- support::resolver::meta_test_multiple_versions_strategy stdout ----
thread 'support::resolver::meta_test_multiple_versions_strategy' panicked at 'In 1280 tries we did not see a wide enough distribution of multiple versions of the same library! dis: [1086, 55, 16, 11, 9, 10, 3, 10, 0, 22]', tests/testsuite/support/resolver.rs:564:5

**Comment by Eh2406** [comment]
So with the number of different things running Cargos test sweet flaky tests are not acceptable. I am sorry for adding them! It does make me wonder if something changed to make the distribution worse. The real solution is to switch to using a fixed seed so as to be sure we have consistent tests.

**Comment by ehuss** [comment]
Also occurs with `meta_test_deep_trees_from_strategy`
https://travis-ci.com/rust-lang/cargo/jobs/178165928

`thread 'support::resolver::meta_test_deep_trees_from_strategy' panicked at 'In 1280 tries we did not see a wide enough distribution of dependency trees! dis: [49, 852, 94, 43, 32, 23, 21, 24, 16, 16, 17, 10, 9, 7, 5, 9, 8, 4, 4, 0, 23]', tests/testsuite/support/resolver.rs:524:5`

**Comment by mati865** [comment]
Fixed by #6753?

**Comment by Eh2406** [comment]
Yes! Thanks!
