### ISSUE TITLE
Cargo fails to select version of tiff compatible with byteorder 1.3.1

### ISSUE THREAD

**Issue by CryZe** [rust-lang/cargo#6624]
**Problem**

I'm trying to depend on both the image crate version 0.21.0 and byteorder 1.3.1. The image crate depends on tiff 0.2.0. However in the tiff crate at version 0.2.0 they had a dependency on byteorder 1.2.\*, meaning that byteorder 1.3.1 is not in that range. Cargo correctly refused to compile at this point due to tiff explicitly not being compatible with byteorder 1.3.1. However other people noticed the problem and they released a tiff version 0.2.1 since then, which supposedly fixes the problem. Instead of depending on byteorder 1.2.\* they now depend on byteorder 1.2 which at least according to the docs means >=1.2.0. 

BUT cargo still tries to select a version of byteorder 1.2.\* and apparently tiff 0.2.0 even though 0.2.1 is published. So there seems to be some bug going on.

![https://i.imgur.com/0pvwHS2.png](https://i.imgur.com/0pvwHS2.png)

**Steps**

1. Depend on image 0.21.0
2. Depend on byteorder 1.3.1
3. Compile

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo 1.32.0 (8610973aa 2019-01-02)

**Comment by ehuss** [comment]
[tiff 0.2.1](https://crates.io/api/v1/crates/tiff/0.2.1/download) still has the old `*` requirements.

**Comment by CryZe** [comment]
Oh wow, yeah that's true. Somehow master being on 0.2.1 with the fix in made me think that 0.2.1 would be the version that is fixed. Thank you so much.
