### ISSUE TITLE
Make cargo's testsuite faster

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/cargo#6629]
Would splitting up the tests so it doesn't all build into a big testsuite binary make iterating faster?

I'm not 100% convinced myself (but I thought I'd share my thought with the team anyway) because I think the incremental compiler should solve this problem, so is the real problem that we have too many huge test files? (`tests/testsuite/test.rs` is 3500 lines, `tests/testsuite/build.rs` is approaching 5000).

**Comment by ehuss** [comment]
How much time does it typically take to build the testsuite?  For me, small changes take about 10s.

It was unified as part of #4867 where having them completely split up was also expensive.

I wonder if it would help much to remove linking cargo-the-lib.  Almost all of the tests are just exercising the cargo executable.  The few tests that actually use the library could be separated. It looks like there are a few path-related utility functions that could probably have some way of sharing.  I suspect it wouldn't help dramatically, though.

**Comment by dwijnand** [comment]
Huh, interesting.  Thanks, @ehuss.
