### ISSUE TITLE
Switch to `Accept: application/json` when downloading crates

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#6639]
Currently we fetch a url on crates.io which redirects us to S3, but crates.io has a feature where if you specify `Accept: application/json` we'll get a JSON blob with the url instead. We should switch Cargo to this interface so we can learn auxiliary information in the future if necessary, and we still know how to get the final crate!

**Comment by ehuss** [comment]
What extra information might it learn or display?

**Comment by alexcrichton** [comment]
We discussed this with some crates.io folks briefly today and @sgrif mentioned that one possible use is to send auxiliary information about things like yank reasons, although this'd largely be future proofing moreso than anything else I think. @sgrif or other crates.io folks may have more to fill in though!

**Comment by sgrif** [comment]
Can confirm this is mostly future proofing. The way we'd be most likely to use this in the near future is to provide information about insecure dependencies

**Comment by epage** [comment]
Would there be any compatibility issues with alternative registries?

**Comment by Eh2406** [comment]
For backwards compatibility cargo would have to be robust to receiving any of:
- the actual crate
- the json data with a url
- a redirect to either of the previous

As long as cargo accepts whatever response it gets for the request, and we document the JSON structures it should work. Although whether it's still the best way to get this data into cargo :shrug:

**Comment by Turbo87** [comment]
FWIW now that we directed cargo to download crates directly from the CDN (without the indirection through the crates.io API) an implementation of this would become quite a bit more complicated. since the JSON blob only supports a redirect URL cargo would then need to perform two requests (JSON + actual download) for each crate, which seems a bit wasteful.

**Comment by epage** [comment]
If this is for mutable metadata about a project (yank reason, etc), I'm unsure if only getting updates at `.crate` download time would be the best approach.

Based on @Turbo87's comment and that, I'm going to propose we close this.

**Comment by weihanglo** [comment]
Second. Closing.
