### ISSUE TITLE
cargo rustc: "--profile" does not work with "--lib"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#6640]
**Problem**

When I pass both `--lib` and `--profile` options to cargo rustc, compilation errors.

**Steps**

1. Clone [hashbrown](https://github.com/Amanieu/hashbrown)
2. `"cargo" "rustc" "--lib" "hashbrown" "--profile" "test"`

This errors saying
```
error: Unrecognized option: 'profile'

error: Could not compile `hashbrown`.

To learn more, run the command again with --verbose.
```

Seems like it passes the flag to rustc?

Changing the argument order changes the error:

2. `"cargo" "rustc" --profile test "--lib" "hashbrown"`

```
error: multiple input filenames provided

error: Could not compile `hashbrown`.

To learn more, run the command again with --verbose.
```

**Notes**

With `--bin`, everything works as expected.  Just `--lib` is affected.

Output of `cargo version`: cargo 1.32.0 (8610973aa 2019-01-02)

**Comment by ehuss** [comment]
`--lib` does not take an argument.  When you pass the arg `hashbrown`, clap decides everything after it belongs to the rustc arguments.  This is a convenience which is maybe not always so convenient.

I think what you want is.

```
cargo rustc --lib --profile test
```

**Comment by RalfJung** [comment]
D'oh. Yes that works. Thanks!
