### ISSUE TITLE
Specify config file on the command line

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#6648]
Several times I've wanted to have a config file (not a full manifest) in my repo that is not on the config search path, but that I can invoke on demand to change cargo's behavior.

One example of this is https://github.com/tikv/tikv/issues/4189, where I am trying to add a "custom profile" by using config profiles. I only want to use this profile in certain situations, and would rather not enable it by copying the config file into cargo's search path, but by directly telling cargo to use that config.

**Describe the solution you'd like**

`cargo build --config etc/release.config`, like `cargo build --manifest-path`.

**Comment by spacekookie** [comment]
I guess this would only be valid for `build` and `test` subcommands? Don't wanna allow publishing with a manifest that might be outside the repository scope.

Are there other applications where this could be relevant?

**Comment by alexcrichton** [comment]
@ehuss has written a possible design for solving this at https://github.com/rust-lang/cargo/issues/6699

**Comment by ehuss** [comment]
Closing in favor of tracking issue #7722.
