### ISSUE TITLE
error: could not find `disel_cli` in registry `https://github.com/rust-lang/crates.io-index`

### ISSUE THREAD

**Issue by jparr721** [rust-lang/cargo#6662]
**Problem**
I cannot seem to install global packages using the global `cargo install` command. I have seen this issue twice now on the issue board here and I have tried all recommended fixes to no avail whatsoever. I am opening this issue because I simply cannot figure out what might be going wrong here.

**Steps**

1. `cargo install diesel_cli --no-default-features --features postgres`
2. Let it run
3. `error: could not find 'disel_cli' in registry 'https://github.com/rust-lang/crates.io-index'`

However, Diesel_cli does exist and is right [here](https://github.com/rust-lang/crates.io-index/blob/master/di/es/diesel_cli)

**Possible Solution(s)**
I have tried to delete $CARGO_HOME/registry, added a .cargo/config file, and also checked my `.gitconfig` as per @alexcrichton in #4007 and #2605 

**Notes**

Output of `cargo version`: cargo 1.34.0-nightly (865cb7010 2019-02-10)

I am running linux 4.20.7-arch1-1-ARCH with a Intel i5-8400 (6) @ 4.000GHz CPU.

I really am not sure what the heck is going on here. Could this be a linux-related issue?

**Comment by ehuss** [comment]
Is `disel_cli` in your error message a typo, or is that what it actually says?

**Comment by jparr721** [comment]
Sorry for the delay @ehuss, what do you mean for this?

**Comment by ehuss** [comment]
The error message you posted is missing the letter `e`.  It is `diesel_cli` not `disel_cli`.  I was wondering if Cargo actually printed that, or if there was a copy-paste error.  If it actually printed that, there is a typo somewhere.

**Comment by jparr721** [comment]
Oh my god. That was the mistake. Forgive me man, thanks for the prompt responses.

**Comment by sopheaksem1993** [comment]
Pay attention to spelling rather than code

**Comment by hadamssmith** [comment]
I cannot seem to install findomain packages using the global cargo install on termux

error: could not find `findomain` in registry `crates-io` with version `*`

**Comment by Eh2406** [comment]
@hadamssmith it looks like all versions of that crate have been yanked https://crates.io/crates/findomain
