### ISSUE TITLE
Add `cargo lucifer` subcommand

### ISSUE THREAD

**Issue by killercup** [rust-lang/cargo#6666]
Add a new subcommand that brings light (get it?) to cargo's dependency resolving, answering questions like

- Why was that dependency included?
- Why was that feature on this dependency enabled?
- Which other versions were considered and why was this one chosen?

- - -

Yes, I made this issue because I saw the last issue was number 6665. Feel free to close it as "bad joke".

**Comment by dwijnand** [comment]
I dig the joke 😄

Could this be resolved by documenting something along the lines of `RUST_LOG=cargo::ops::resolve=info cargo generate-lockfile`?

**Comment by spacekookie** [comment]
To propose a bikeshed here, I think it should be called `cargo cult`

**Comment by killercup** [comment]
@dwijnand Maybe `env RUST_LOG=cargo::core::resolver=trace cargo generate-lockfile` if it was more pretty :D

**Comment by dwijnand** [comment]
This is how I map log levels:
* `trace` I'm _deeeep_ in this module, give me lots of details
* `debug` I'm a cargo dev, give me the general-sense detailed log for this module
* `info` I'm a cargo user, looking some more info from the operations in this module

But actually, make this detail (or some of it) should be printed by `cargo generate-lockfile -v`.

**Comment by epage** [comment]
`cargo tree` I think solves
- Why was it included (`cargo tree -i`)
- Features (`cargo tree -e features`)

As for "what other versions and why this one", that gets complicated with a lot of information involved.  Not really seeing a way around that than `env CARGO_LOG=cargo::core::resolver=trace cargo generate-lockfile`.

Probably the main thing left is documenting these resources somewhere.  Like the section of the documentation on the resolver.
