### ISSUE TITLE
alternative registry doesn't work for subdependencies

### ISSUE THREAD

**Issue by arturoc** [rust-lang/cargo#6670]
**Problem**
When using alternative registries, they work fine when using a dependency from an alternative registry but when a crate depends on another crate that depends on a third on an alternative registry, it tries to find it on crates.io instead of the alternative registry

**Steps**
- Create a package "A" on an alternative registry
- Create a package "B" depending on "A" from the alternative registry
- Create a package "C" depending on "B"

Building crate B works fined but when building crate C cargo complains that it can't find "A" trying to find it in crates.io instead of the alternative registry

```
error: no matching package named `A` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `B v0.1.0 (registry `alternative registry url`)`
    ... which is depended on by `C v0.1.0 (local path)`
```

**Notes**

This seems to happen with both the latest cargo from rustup:

Output of `cargo version`:
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)

And the latest cargo from master:
cargo 1.34.0

**Comment by ehuss** [comment]
I put together a little test, and this seems to work for me.  Can you say more about how you generated your index?  If both A and B are in the same registry, the entries should look like this:

A:
```json
{"name":"a","vers":"0.1.0","deps":[],"features":{},"cksum":"346f79d1c951d39beed7979352c9d75805660d623faa913910fb9bde348e5fc5","yanked":false,"links":null}
```

B:
```json
{"name":"b","vers":"0.1.0","deps":[{"name":"a","req":"^0.1","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal","registry":null,"package":null}],"features":{},"cksum":"a3656b96edb6cec7bc56a98b520a977ae43054fa1ba7e0006dd453685e7df30d","yanked":false,"links":null}
```

Notably the `registry` field should be null if a dependency is from the same registry.

**Comment by arturoc** [comment]
oh i see, i'm using https://crates.io/crates/cargo-index to generate the index which seems to have a bug where registry of dependecies points to crates.io always no matter what.

thanks!

**Comment by ehuss** [comment]
Ah, well I'm the author of that.  I used it for my test, and it seemed to work.  The `--index-url` that is used when adding should match the same index url in `.cargo/config`.

**Comment by arturoc** [comment]
ah i see thanks so much

**Comment by arturoc** [comment]
mmh just tried that but i get the same result, dependencies are created with their registry pointing the main crates.io

i can open an issue in cargo-index repo if you prefer

**Comment by ehuss** [comment]
Sure, that would be good.
