### ISSUE TITLE
Cargo stopped working with read-only srcdir between 1.31.0 and 1.34.0-nightly

### ISSUE THREAD

**Issue by federicomenaquintero** [rust-lang/cargo#6672]
**Problem**
Between cargo 1.31.0 and 1.34.0-nightly, cargo stopped working for the case where the srcdir is really read-only, and `CARGO_TARGET_DIR` points to a writable directory.

This occurs in the context of a crate being built inside a larger autotools-based module.  In there, `make distcheck` creates a read-only source directory with the unpacked source tarball, and a read-write build directory.  The autotools setup in my problematic crate (librsvg) uses CARGO_TARGET_DIR to use the writable build directory, and stopped working recently.

**Steps**

1. Unpack the attached tarball, which has a minimal directory structure to reproduce this.
2. `cd cargo-read-only/read-only-srcdir`
3. `CARGO_TARGET_DIR=read-write-builddir cargo build`

This works in 1.31.0, and fails in 1.34.0-nightly.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo 1.34.0-nightly (245818076 2019-01-27)

**Comment by federicomenaquintero** [comment]
[cargo-read-only.zip](https://github.com/rust-lang/cargo/files/2871264/cargo-read-only.zip)

Argh, github won't let me upload a .tar.xz.  Please use this .zip file; unpack it and then the tarball that came inside it.  (I'm using a tarball to preserve the directory permissions, which are relevant to this bug.)

**Comment by ehuss** [comment]
Is the issue that it is trying to write to `Cargo.lock`?  You can use `--locked` to prevent it from trying to update the lock file.  Or you can make sure the lock file is up-to-date before starting.  (Recent versions added a comment at the top of the file.)

**Comment by federicomenaquintero** [comment]
The example works with `--locked`!  I'll try the autotools build...

(Still, why did this behavior change?)

Just tried it with cargo 1.32.0 on the example and it works, too.   So it changed between 1.32 and 1.34.

**Comment by ehuss** [comment]
A comment was added to the top of the file in 1.34.  You can add that comment in and it should continue to work with older versions of Cargo.

**Comment by federicomenaquintero** [comment]
Thanks, it works if I add `--locked` in the right places in the autotools files.  Will close the bug now.
