### ISSUE TITLE
Using examples crate lib in examples crate

### ISSUE THREAD

**Issue by jsancio** [rust-lang/cargo#6680]
**Problem**
Examples crate is unable to use an examples crate lib. The Cargo [documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#examples) explains how to do this but looking at this [project](https://github.com/jsancio/example_crate/tree/b639ef69e133479129289e7abff62915b0e9e061) implementation, cargo/rustc is unable to find the create:

```
cargo build --examples
   Compiling example_crate v0.1.0 (/home/jsancio/work/example_crate)
error[E0432]: unresolved import `b`
 --> examples/c.rs:1:5
  |
1 | use b::b;
  |     ^ use of undeclared type or module `b`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `example_crate`.

To learn more, run the command again with --verbose.
```

**Steps**
1. `git clone git@github.com:jsancio/example_crate.git`
2. `cd example_crate` 
3. `cargo build --examples`

**Possible Solution(s)**

**Notes**
This issue was [posted](https://users.rust-lang.org/t/using-examples-crate-lib-in-another-examples-crate/22565) in the rust language user form a few months ago. A user suggested importing `b` as a module but unfortunately that leads to the warnings "unused create attributes" and "crate attributes can only be applied at the root". Is this a bug in cargo? If not what is the correct way of doing this?

Output of `cargo version`:
```
cargo --version
cargo 1.32.0 (8610973aa 2019-01-02)
```

**Comment by ehuss** [comment]
Example libraries cannot be used as extern crates or dependencies.  One alternative is to pull it in as a module (`mod b;`). Another is to use a workspace and promote your examples to full Cargo packages, which can depend on one another ([here](https://github.com/SergioBenitez/Rocket/tree/master/examples) is an example of a project that uses package-based examples).

**Comment by jsancio** [comment]
Thanks @ehuss. I give it a try this weekend and close the issue.

**Comment by jsancio** [comment]
Okay. I think I now understand what is going on. The project didn't `b` as a library/crate.
