### ISSUE TITLE
neither cargo update nor cargo package works, and says "error: no matching package named..."

### ISSUE THREAD

**Issue by 1inguini** [rust-lang/cargo#6686]
**Problem**

I'm pretty sure this error isn't the packages' fault, since number of packages fails to get installed(by the way, cargo install works).
for example:
~~~
➤ cargo package
error: no matching package named `cursive` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `お試し v0.1.0 (/home/linguini/Desktop/rust/お試し)`
~~~

~~~
➤ cargo package
error: no matching package named `cortex-m` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `nucleo-64 v0.1.0 (/home/linguini/Desktop/rust/nucleo-64)`
~~~

~~~
➤ cargo package
error: no matching package named `cc` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
did you mean: gcc, clap, libc, ...
required by package `bootstrap v0.0.0 (/home/linguini/Desktop/rust/rust/src/bootstrap)`
~~~

I think it started to happen after I deleted `~/.cargo` and `~/.rustup` and reinstalled rustup because a kept failing to make [avr-rust](https://github.com/avr-rust/rust), but maybe it was from before that, and the reason `make` kept failing was this. 

Output of `cargo version`: `cargo 1.32.0`

**Comment by 1inguini** [comment]
I got a new error when running `cargo search`:

~~~
➤ cargo search cursive
    Updating `/home/linguini/Desktop/rust/rust/vendor` index
error: failed to update dir /home/linguini/Desktop/rust/rust/vendor

Caused by:
  failed to fetch `file:///home/linguini/Desktop/rust/rust/vendor`

Caused by:
  could not find repository from '/home/linguini/Desktop/rust/rust/vendor'; class=Repository (6)

~~~

**Comment by ehuss** [comment]
It looks like you enabled vendoring somehow with an old set of dependencies.  Check if you have a `.cargo/config` file somewhere (which likely has a source-replacement).

**Comment by 1inguini** [comment]
Its in ~/Desktop/rust, which is one layer under the rust project. what should I do whith it?

**Comment by 1inguini** [comment]
there was another one in ~/Desktop/rust/nucleo-64/

**Comment by ehuss** [comment]
It's hard to say without knowing why it was created in the first place, but you can just remove it (or temporarily rename it) and see if that clears up your situation.

Rustbuild will set up vendoring if `vendor = true` is set in `config.toml` in the root of the rust tree. It will also do this if the build is run under sudo.

**Comment by 1inguini** [comment]
Removing `~/Desktop/rust/.cargo` did the trick!
Thank you so much!

**Comment by dwijnand** [comment]
Should we close this issue now?

**Comment by 1inguini** [comment]
Oops, I've thought I've already closed this issue.
