### ISSUE TITLE
[replace] section package causes conflicts in [package] links field

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/cargo#6693]
**Problem**

When I use a local copy to [replace] a dependency, if the dependency has "links" field, it causes confliction.

**Possible Solution(s)**
It shouldn't be, since the older package is supposed to be replaced.

Output of `cargo version`:
Newest stable.

**Comment by ehuss** [comment]
`[patch]` should be used instead of `[replace]`, and should work in this case.

**Comment by epage** [comment]
Considering `[replace]` is deprecated, I'm going to close this.
