### ISSUE TITLE
Cargo doesn't download the latest version of a dependency

### ISSUE THREAD

**Issue by ghost** [rust-lang/cargo#67]
As I'm writing this, the [latest version of cgmath-rs](https://github.com/bjz/cgmath-rs/commit/92b5a4b31f8e2b6a39c4e46af9b1b29e4bd576cb) compiles without errors for me when built manually (`git clone https://github.com/bjz/cgmath-rs.git` etc.). Cargo however seems to download an older version that fails to compile. Since I have not specified a version of cgmath-rs in my project, I'm assuming this is a bug. A minimal Cargo.toml which replicates this bug:

```
[package]

name = "testproject"
version = "0.0.0"
authors = [ "bachm" ]

[[lib]]

name = "testproject"

[dependencies.cgmath-rs]

git = "https://github.com/bjz/cgmath-rs.git"
```

**Comment by gavynriebau** [comment]
With recent versions of rust/cargo I think you have to run `cargo update` instead.
See: https://doc.rust-lang.org/cargo/commands/cargo-update.html
