### ISSUE TITLE
Warn if dependency doesn't have library target kind

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/cargo#6702]
When specifying a crate without a library target kind as a dependency, cargo currently just silently ignores it. For example:

```
[package]
name = "deptest"
version = "0.1.0"
edition = "2018"

[dependencies]
ripgrep = "*"
```

```
$ cargo run
   Compiling deptest v0.1.0 (/tmp/deptest)
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/deptest`
Hello, world!
```

Note that the dependency isn't even compiled. Clearly, Cargo has already decided to elide this crate in the dependency graph, but the cause is not obvious to the user. All this can be confusing if the user is expecting to be able to use the dependency. I think a warning message is in order.

**Comment by lukaslueg** [comment]
I concur that this is confusing and should result in a warning (especially since there usually is `ripgrep` and `libripgrep` and such). Two use cases that are probably legimate:

* An "empty" dependency still means "A solution to my dependency graph exists. Proof me wrong!"
* Docs are pulled in unless `--no-deps` is supplied.

**Comment by MonliH** [comment]
I'd be interested in implementing this.

@rustbot claim

**Comment by MonliH** [comment]
Unfortunately, I no longer have the time to work on this.

@rustbot release-assignment

**Comment by hi-rustin** [comment]
@ehuss I'm trying to add this warning, but I can't find anywhere to add it when resolving dependencies. Could you help with some hints?

**Comment by ehuss** [comment]
Hm, I'm not sure exactly where would be the best place. 

Essentially, it needs to iterate over the workspace member IDs, call `resolve.deps(member_id)`, iterate over those dependencies and fetch the package object for each one (`pkg_set.get_one(dep_id)`), and call `if !dep_pkg.targets().iter().any(|t| t.is_lib()) { /*warn*/ }`.

There are a few places where it could do that. I think one place would be the bottom of [`resolve_ws_with_opts`](https://github.com/rust-lang/cargo/blob/d555e49abee3e68036402f89e31f208a793cace1/src/cargo/ops/resolve.rs#L173). That is a common place where resolution is done. Another place would be in [`create_bcx`](https://github.com/rust-lang/cargo/blob/d555e49abee3e68036402f89e31f208a793cace1/src/cargo/ops/cargo_compile.rs#L387). That is where all the build commands create their build graph. A drawback of `create_bcx` is that would only warn on build commands, and not others. I'm not sure if that matters much.

**Comment by hi-rustin** [comment]
> Hm, I'm not sure exactly where would be the best place.
> 
> Essentially, it needs to iterate over the workspace member IDs, call `resolve.deps(member_id)`, iterate over those dependencies and fetch the package object for each one (`pkg_set.get_one(dep_id)`), and call `if !dep_pkg.targets().iter().any(|t| t.is_lib()) { /*warn*/ }`.
> 
> There are a few places where it could do that. I think one place would be the bottom of [`resolve_ws_with_opts`](https://github.com/rust-lang/cargo/blob/d555e49abee3e68036402f89e31f208a793cace1/src/cargo/ops/resolve.rs#L173). That is a common place where resolution is done. Another place would be in [`create_bcx`](https://github.com/rust-lang/cargo/blob/d555e49abee3e68036402f89e31f208a793cace1/src/cargo/ops/cargo_compile.rs#L387). That is where all the build commands create their build graph. A drawback of `create_bcx` is that would only warn on build commands, and not others. I'm not sure if that matters much.

Thanks for your help! Created a [PR](https://github.com/rust-lang/cargo/pull/9771) for it.
