### ISSUE TITLE
Cargo update build fails on Solus

### ISSUE THREAD

**Issue by Girtablulu** [rust-lang/cargo#6709]
I'm trying to update cargo for Solus but suddenly it fails to build which was never an issue before with the steps, because it tries compiling stuff from nightly with the` --release` flag, which as far as I understood shouldn't be doing. 

The source.tar the build package  is using is the rustc-1.33.0-src.tar.gz. 
The build will cd into src/tools/cargo and after this it executes` cargo build --release` but then it fails

The terminal build log
https://pastebin.com/SBwHyywd

As far as I understood the cargo changelogs nothing should cause this.

**Comment by ehuss** [comment]
I don't think the rustc source tree is designed to allow building using `cargo` by itself. In this case, there is a `rustc-workspace-hack` crate which is used to unify deps across packages, and requires a nightly feature.

To build cargo from the rustc tree, usually you run `./x.py build src/tools/cargo`.  Cargo generally should not be built separate from rustc, so using something like `./x.py dist` is usually run.  There are a number of config settings that are normally set for distribution, so it's more complex than that (the defaults are not really appropriate for many cases).

I think some distributions have their own build scripts which use a clone of https://github.com/rust-lang/cargo/ (or the version in crates.io), but I'm not terribly familiar with them.

**Comment by Girtablulu** [comment]
We are switching the way the Software is packaged to the correct way, dunno why it was done this way in the first place. 

Thanks for the help
