### ISSUE TITLE
cargo doc --open throught error

### ISSUE THREAD

**Issue by HobDev** [rust-lang/cargo#6712]
**Problem**
cargo doc --open through following error:
error:could not find `Cargo.toml` in `/Users/username` or any parent directory
**Steps**

1.open terminal
2.stay on home directory 
3.run cargo doc --open

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo version= 1.33.0
MacOS Mojave 10.14.3

**Comment by dwijnand** [comment]
I think you mean to do `rustup doc`?  There's also `rustup doc --book`.

`cargo doc --open` is for generating and opening the rustdocs in a browser, for the given project and dependencies, and for that it needs a Cargo.toml manifest to exist.

**Comment by HobDev** [comment]
@dwijnand I am reading "The Book".But I didn't understand I need to run the command inside the project. Sorry for the noise
