### ISSUE TITLE
cargo install errors if same version already installed

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/cargo#6727]
**Problem**

`cargo install` is not idempotent on nightly (probably has never been)

**Steps**

```
cargo install xargo # OK if xargo not installed
cargo install xargo # Errors
```

errors with: 

```
Updating crates.io index
  Installing xargo v0.3.13
error: binary `xargo` already exists in destination as part of `xargo v0.3.13`
```

but the version to install is identical with the version currently installed. This should be a warning instead of a hard error.

**Comment by dwijnand** [comment]
Will be fixed if we go ahead with the proposal in #6667.

**Comment by gnzlbg** [comment]
@dwijnand we didn't go with that, @ehuss is there a plan for solving this ?

For CI systems it is often useful to use the `cargo: cache` on, e.g., Travis. I want `cargo install foo --XYZ` to only install `foo` if it is not already installed, or if there is a newer version, or similar. But if the exact same version is installed, I don't want `cargo` to just "fail" here.

**Comment by ehuss** [comment]
@gnzlbg This has been implemented on nightly.  `cargo +nightly install foo -Z install-upgrade`.  If you can try it out and leave feedback on the tracking issue (#6797), I'd appreciate it.

**Comment by gnzlbg** [comment]
Nice! Thank you!
