### ISSUE TITLE
cargo build reports can't find crate  when that crate exists

### ISSUE THREAD

**Issue by fulara** [rust-lang/cargo#6730]
not sure if this should be reported here on on the rust itself.
**Problem**
When depending on particular crate and arguments to that crate cargo/rustc returns confusing and misleading error: 
```
error[E0463]: can't find crate for `magnet_schema`
 --> src\main.rs:1:1
  |
1 | extern crate magnet_schema;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

I would expect at least more detail into what this error means rather than just `can't find crate` error.

**Steps**
1. `cargo new --bin minimal`
2. add dependency: 
` magnet_schema = { version = "0.8.0", optional = true, features = ["uuid", "url"] }`
3. main:
```
 extern crate magnet_schema;
 fn main() {
     println!("Hello, world!");
 }
```
4. invoke `cargo build` result is: 
```
error[E0463]: can't find crate for `magnet_schema`
 --> src\main.rs:1:1
  |
1 | extern crate magnet_schema;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```
5. change depencies to:  
`magnet_schema = "0.8.0"`
6. project now builds.

**Possible Solution(s)**
This is probably an error in that magnet_schema, however still the error I am getting is confusing to me and misleading - could it hint somehow whats the underlying issue?
**Notes**

Output of `cargo version`:
`cargo 1.33.0 (f099fe94b 2019-02-12)`  
windows.

**Comment by jethrogb** [comment]
You didn't show the command that you used to build in step 4, but it's an optional dependency, so if you just did `cargo build` this is expected behavior.

**Comment by fulara** [comment]
Oh. I totally missed that somehow... thanks, closing.
