### ISSUE TITLE
build.rs script output for "cargo:rustc-link-lib=krb5" ignored

### ISSUE THREAD

**Issue by decathorpe** [rust-lang/cargo#6731]
**Problem**

I've been trying to port a python utility library for `krb5` to rust, for which I adapted some C code and wrote a rust wrapper around it (similar to how the `cccolutils` python package is done): [`cccolutils-rs`](https://github.com/ironthree/cccolutils-rs).

The documentation for build scripts states that cargo reads [output from the build script ](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script). So, I should be able to set the `cargo:rustc-link-lib=krb5` flag, to make cargo link my library with `-lkrb5` (same for `k5crypto` and `com_err`, which are the output from `pkg-config --libs krb5`).

The following line is printed when running `cargo -vv test`:

`[cccolutils 0.0.1] cargo:rustc-link-lib=krb5`, so the print statement does what it's supposed to, but it doesn't seem to have any effect.

Which means I had to put

```
[build]
rustflags = ["-Clink-args=-lkrb5 -lk5crypto -lcom_err"]
```

into the project's  `.cargo/config` file to make this work. This is ugly, and that doesn't even work for doctests, for some reason (which means I had to add the ignore attribute to all code in doc comments).

**Steps**

1. build a library with a "C extension" that needs to be linked to a C library
2. put the expected cargo output prints into the build script
3. try to run the code (`cargo test`)
4. crash with: `undefined reference to *` and `collect2: error: ld returned 1 exit status`

**Notes**

Output of `cargo version`: `cargo 1.33.0 (f099fe94b 2019-02-12)`

I'm working on fedora 29, with rust and cargo installed via rustup.

```
$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by ehuss** [comment]
It should work. I checked out your project and made the following changes:
1. Removed `.cargo/config`
2. Added to `build.rs`: `println!("cargo:rustc-link-lib=krb5");`

And ran `cargo test` and it built and linked and ran correctly.

Can you run `cargo test -vv` to verify that the "-l krb5" flag is passed to rustc?  Can you include the entire output from `cargo test -vv` in a gist?

My only idea is that maybe there is a linker flag order problem.  RUSTFLAGS will appear before your native `cccolutils`, but rustc-link-lib will depend on the order that you print them.

**Comment by decathorpe** [comment]
Thanks, it seems you pointed me in the right direction, but now I feel stupid.

I moved the `println!()` statement in `build.rs` **after** the native build command, and now it works!

Still, do you know why this

```rust
    cc::Build::new()
        .file("src/cccolutils.c")
        .compile("cccolutils");

    println!("cargo:rustc-link-lib=krb5");
```

works, but this

```rust
    println!("cargo:rustc-link-lib=krb5");

    cc::Build::new()
        .file("src/cccolutils.c")
        .compile("cccolutils");
```

doesn't?

**Comment by ehuss** [comment]
It depends on the linker, and which specific flags are used.  The linker looks at its inputs left-to-right.  Generally you want the libraries that "fill in" unresolved symbols to be towards the end of the list.

**Comment by decathorpe** [comment]
> It depends on the linker, and which specific flags are used. The linker looks at its inputs left-to-right. Generally you want the libraries that "fill in" unresolved symbols to be towards the end of the list.

That explains it. Thanks for your help! :smile:
