### ISSUE TITLE
Can you implement a way to pass --target via ~/.cargo/config?

### ISSUE THREAD

**Issue by stefson** [rust-lang/cargo#6735]
I'm trying to get cross-compile working, from x86_64 to armv7. 

While it's possible to setup a linker specificly per target in the cargo config file, it's not possible to do that for what would be `--target = armv7-unknown-linux-gnueabihf`

Why is this a good idea? To get rust/cargo based cross compile out of the box for distros. Gentoo for instance uses a handcrafted cargo/config file for every package out there, but sticks to the simple `rustc` command for compiling stuff, when it has to be `rustc -C --target = armv7-unknown-linux-gnueabihf`. If passing that --target via the config file, it is possible to enable cross compile without much hassle. 

Thanks :-)

**Comment by ehuss** [comment]
I'm not sure I understand.  The default target can be set via the `build.target` key in [`.cargo/config`](https://doc.rust-lang.org/cargo/reference/config.html).  If you are compiling without cargo, it sounds like this is a request for Gentoo?

**Comment by ehuss** [comment]
Without more information, I don't think this is actionable.  If you can maybe provide more detail, feel free to reopen.

**Comment by stefson** [comment]
this was fixed in the meantime, I forgot to close :-S
