### ISSUE TITLE
cargo --list/version triggers /boot automount

### ISSUE THREAD

**Issue by cjmayo** [rust-lang/cargo#6737]
**Problem**
With a separate /boot partition that is not mounted by default and systemd creating an automount unit for it, running `cargo --list` causes /boot to be mounted.
I wouldn't expect cargo to need to mount /boot.

Because Bash autocompletion file runs `cargo --list`:
https://github.com/rust-lang/cargo/blob/5773aaafdc5a375a388c08d8fb6ee742cdaf2707/src/etc/cargo.bashcomp.sh#L150
Every time i create a new Bash session e.g. a new GNOME terminal or terminal tab /boot is automounted.

**Steps**

1. /boot is not mounted
2. `cargo --list`
3. /boot is mounted (`boot.automount: Got automount request for /boot` in systemd journal)

**Notes**

Output of `cargo version`: cargo 1.32.0

Gentoo Linux:
dev-lang/rust-1.32.0
sys-apps/systemd-241-r1

**Comment by cjmayo** [comment]
`cargo version` also triggers this.

strace and grep points to the included vendor/openssl-probe crate:

```
"/boot/system/data/ssl",
```
https://github.com/alexcrichton/openssl-probe/blob/a014ef5d4dba06a497df0969823ace290b9dfcdd/src/lib.rs#L35

**Comment by ehuss** [comment]
I believe this is now fixed.  The code which initializes git2 (`init_git_transports`) is now done after `--list` or `version` commands are executed (part of #7649 I think in release 1.42).

**Comment by cjmayo** [comment]
Looks good. Thanks.
