### ISSUE TITLE
Allow optional cyclic dependencies

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/cargo#6743]
**Describe the problem you are trying to solve**

I have two crates: `foo` and `foo-generator`. `foo` contains a datatype `D`, and `foo-generator` contains a proc-macro to help manipulate this datatype. `foo-generator` depends on `foo` because it uses `D`. `foo` contains many things, notably some `impl`s for `D`.
I'd like to be able to use the code-generation utilities of `foo-generator` when defining some of those `impl`s, but of course that would be a cyclic dependency and cannot be resolved. And I can't define those impls in a 3rd crate because of orphan rules.
However, since `foo-generator` doesn't need those `impl`s, I had the idea of doing the following:
```
// foo/Cargo.toml
[package]
name = "foo"
[features]
impls = [ "foo_generator" ]
[dependencies]
foo_generator = { path = "../foo_generator", optional = true }
```
```
// foo_generator/Cargo.toml
[package]
name = "foo_generator"
[lib]
proc-macro = true
[dependencies]
foo = { path = "../foo" } // `impls` feature not active
```
```
// foo/lib.rs
struct D;
#[cfg(feature = "impls")]
impl Trait for D {}
```

That way, `foo` with the `impl` feature depends on `foo-generator`, which depends on `foo` with the feature disabled, which doesn't depend on anything and everything can be compiled.
Currently, cargo does not support this and complains about cyclic dependencies, but it seems to me that this could work in principle.

**Describe the solution you'd like**

`cargo` accepts the situation above and resolves this not-really-cyclic dependency.

**Notes**

`cargo` would need to think about a given crate with different features enabled as separate compilable entities, which may or may not be a major change to how `cargo` is currently structured.

**Comment by Nadrieril** [comment]
More generally, solving this would allow crates to depend on themselves and e.g. both define a proc-macro and use it in the same crate under different features (once proc-macro crates are allowed to export non-proc-macro things).

**Comment by Nadrieril** [comment]
Well, I don't need this anymore and it looks far-fetched anyways so I'll close this issue. If anyone else wants this I can reopen it.

**Comment by Cyrix126** [comment]
Actually I had the same situation and has been thinking about this theoretical solution.  What did you use in the mean time ?

**Comment by Nadrieril** [comment]
I made it so that `foo_generator` didn't use `D`
