### ISSUE TITLE
Patch will change the resolved version of indirect dependency.

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/cargo#6762]
**Problem**

After adding a patch, the indirect dependency can be resolved to a different version.

**Steps**

Cargo.toml:
```
[package]
name = "test-deps"
version = "0.1.0"
edition = "2018"

[dependencies]
protobuf = "~2.0"
prometheus = "0.5"
```
After running `cargo build`, dependencies are resolved as following:
```
% cargo tree
test-deps v0.1.0 (file:///tmp/test-deps)
[dependencies]
├── prometheus v0.5.0
│   [dependencies]
│   ├── cfg-if v0.1.7
│   ├── fnv v1.0.6
│   ├── lazy_static v1.3.0
│   ├── protobuf v2.0.6
│   ├── quick-error v1.2.2
│   └── spin v0.4.10
└── protobuf v2.0.6 (*)

```
And then appending following lines to Cargo.toml,
```
[patch.crates-io]
protobuf = { git = "https://github.com/busyjay/rust-protobuf.git", branch = "customize-lite-runtime-2.0" }
```
Remove Cargo.lock and build again, dependencies change to
```
% cargo tree
test-deps v0.1.0 (file:///tmp/test-deps)
[dependencies]
└── prometheus v0.5.0
    [dependencies]
    ├── cfg-if v0.1.7
    ├── fnv v1.0.6
    ├── lazy_static v1.3.0
    ├── protobuf v2.4.0
    ├── quick-error v1.2.2
    └── spin v0.4.10
```
protobuf's version changes from v2.0.6 to v2.4.0.

**Notes**

Output of `cargo version`:

```
% cargo version
cargo 1.33.0 (f099fe94b 2019-02-12)
```

**Comment by ehuss** [comment]
There are a few workarounds for this:

- Don't delete `Cargo.lock` after adding the patch. This will keep it locked to the 2.0.6 version.
- If you do delete the lock, run `cargo update -p protobuf:2.4.0 --precise 2.0.6` to reset the version.
- Use `[replace]` which doesn't seem to have this issue (at least in this scenario).

**Comment by BusyJay** [comment]
Thanks @ehuss, `[replace]` works.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/7117 since that documents what I believe is the bug happening here.

FWIW `[replace]` is not recommended long-term. This is a bug in `[patch]` that we should fix, and `[replace]` is going to be deprecated/removed eventually from Cargo.
