### ISSUE TITLE
The "rustup fix --edition" command claims project is not under VCS

### ISSUE THREAD

**Issue by patriksvensson** [rust-lang/cargo#6766]
**Problem**

I wanted to update an old project to the 2018 edition (on Windows 10.0.1809.0), so I ran `cargo fix --edition`. However, even though my project is under source control, it says it's not:

```
Patrik@SPECTRE-3 [C:\Users\Patrik\Source\Git\cake-build\cakeup] [master ≡]
> cargo fix --edition
error: no VCS found for this package and `cargo fix` can potentially perform destructive changes; if you'd like to suppress this error pass `--allow-no-vcs`
```

Of course I can use the `--allow-no-vcs` flag, so it's not really a problem but thought I should report this anyway.

**Steps**

1. Update the toolchain by running `rustup update`
2. Clone `git@github.com:cake-build/cakeup.git`
3. Run `cargo fix --edition`

**Notes**

Output of `cargo version`: 

```
cargo 1.33.0 (f099fe94b 2019-02-12)
```

**Comment by ehuss** [comment]
Looks like the issue is that there is a `cakeup*` entry in `.gitignore`, and that is being compared to the root working directory.  I think it should probably not check the root against the ignore list.

**Comment by patriksvensson** [comment]
Oh, this was resolved fast. Thanks 👍
