### ISSUE TITLE
.cargo/config equivalent for --frozen

### ISSUE THREAD

**Issue by jrvanwhy** [rust-lang/cargo#6769]
**Describe the problem you are trying to solve**
We would like to vendor all of our dependencies and transitive dependencies, such that cargo does not make network requests when running in our project.

We can currently do this by issuing the `--frozen` argument to cargo, but that is a manual process. It would be better if we could make this the default in our repository-wide .cargo/config file.

**Describe the solution you'd like**
We'd like an option added to .cargo/config to make `--frozen` the default cargo behavior. The new option may belong under `[net]`.

**Notes**
We are currently using the following workaround:

```
[http]
proxy = "socks://proxy.invalid/"
```

This produces less-than-ideal error messages, and is of course not a very clean solution.

**Comment by jrvanwhy** [comment]
Actually, it turns out `--frozen` isn't quite what I needed: I needed a way to prevent network requests. `--frozen` additionally requires Cargo.lock to be up to date.

This feature request is for a way to prevent network requests (as the proxy hack does), not a `.cargo/config` clone of `--frozen`.

**Comment by ehuss** [comment]
There is an unstable flag to force offline behavior (https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#offline-mode).  Its status is tracked at #5655.  It would be good to know if that can cover your use case.

**Comment by jrvanwhy** [comment]
I believe that's exactly the functionality I'm looking for! I'm requesting that it be added as an option in .cargo/config, so that we can confirm that cargo runs without network requests.

If you think this request belongs in #5655 instead, let me know and I'll comment there and mark this as a duplicate.

**Comment by ehuss** [comment]
Yea, just add a comment over there.  It sounds like a reasonable request to me.

**Comment by jrvanwhy** [comment]
I added a comment on #5655, closing this as a duplicate.
