### ISSUE TITLE
HTTP/2 stream errors aren't considered spurious network failures

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#6788]
First discovered [in these logs](https://dev.azure.com/rustwasm/wasm-bindgen/_build/results?buildId=264&view=logs), it looks like Cargo isn't correctly detecting a spurious network failure:

```
error: failed to download from `https://crates.io/api/v1/crates/docopt/1.0.2/download`

Caused by:
  [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 11 was not closed cleanly: INTERNAL_ERROR (err 2))
```

That's one that Cargo should automatically restart and attempt to redownload!

**Comment by fluffysquirrels** [comment]
I've taken a brief look at this and would submit a PR.

Does the relevant curl error just need to be added to this set of conditions (https://github.com/rust-lang/cargo/blob/master/src/cargo/util/network.rs#L48-L52)?

What testing needs to be done for this change? For what it's worth the existing curl errors don't seem to have unit tests. If I can easily create a `curl:;Error` in a unit test I will do so.

It looks like this curl error isn't in `curl-rust` yet ([docs for `curl::Error`](https://docs.rs/curl/0.5.0/curl/struct.Error.html), so the first step would probably be to add it there.

**Comment by fluffysquirrels** [comment]
https://github.com/alexcrichton/curl-rust/pull/266 adds the required error to the `curl-rust` crate.

**Comment by Ancient123** [comment]
I am running nightly builds of rust and seem to be having this issue again. Did something cause a regression. :(

**Comment by ehuss** [comment]
@Ancient123 What is the exact output from Cargo?  What platform are you on?  Are you using a system-linked version of libcurl? If so, which version?

**Comment by Ancient123** [comment]
```
error: failed to download from `https://crates.io/api/v1/crates/rust-argon2/0.7.0/download`

Caused by:
  [16] Error in the HTTP2 framing layer
```

and similar for different crates at random.
System is pretty agnostic, its the official `rustlang/rust:nightly-buster` docker. The symptom started on the 10th (April) or earlier.

**Comment by alexcrichton** [comment]
Thanks @Ancient123! I've added that code as a whitelist for a spurious error on https://github.com/rust-lang/cargo/pull/8102
