### ISSUE TITLE
Install skip existing crates

### ISSUE THREAD

**Issue by liamdawson** [rust-lang/cargo#6813]
**Describe the problem you are trying to solve**
I would like to install some cargo utilities via a bootstrap script, and would like it to skip utilities that have already been installed.

**Describe the solution you'd like**
```shell
$ cargo install --skip-existing cargo-edit
warning: crate `cargo-add v0.3.1` already exists in destination, skipping install
```

Prior art from `rbenv`:
```shell
$ rbenv install --help
...
-s/--skip-existing Skip if the version appears to be installed already
...
```

This flag would output a message to `stderr` indicating the crate is already installed, and return a status code of `0` (instead of the current `101`).

**Notes**
I was working around this with `command -v cargo-tree | cargo install cargo-tree`, but that approach fails with `cargo-edit`, because it adds multiple binaries, none of which are called `cargo-edit`. I also feel this is a simple, partial workaround to the multiple requests for using `install` to upgrade crates.

**Comment by ehuss** [comment]
Thanks for the report! I've recently implemented a feature that will automatically skip the install if it is already installed. It hasn't been merged yet (#6798), but could you take a look at [the documentation](https://github.com/rust-lang/cargo/blob/39294311bc03ffb4f048f626958b8111edde545a/src/doc/src/reference/unstable.md#install-upgrade) and let me know if it covers your needs?

**Comment by liamdawson** [comment]
It would definitely cover my needs in this scenario! I thought I'd propose this as a (hopefully) uncontroversial/uncomplicated way to achieve my goals in the short term, but do you think there's any value in it vs. your PR there? (I'm happy to open a PR for this suggestion).

**Comment by ehuss** [comment]
Probably not at this time.  New features tend to go through the unstable process, and I don't think we need multiple ones doing similar functionality.

**Comment by ehuss** [comment]
Closing in favor of #6797.
