### ISSUE TITLE
`cargo test --doc` fails with `multiple rlib candidates for * found`

### ISSUE THREAD

**Issue by indutny** [rust-lang/cargo#6819]
**Problem**

I'm getting an error when trying to run `cargo test --doc` on this (practically empty) project:

https://github.com/indutny/append-multi-log

**Steps**

1. `git clone git@github.com:indutny/append-multi-log.git`
2. `cd append-multi-log`
3. `cargo test --doc`

**Possible Solution(s)**

No ideas, but I suppose it is somehow related to having docs (`///` comments) in the dependency?

**Notes**

Output of `cargo version`:

```
cargo 1.33.0 (f099fe94b 2019-02-12)
```

The platform is:

```
Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
```

Rustc:

```
$ rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by indutny** [comment]
Full `cargo test --doc` output: https://gist.github.com/indutny/31b2f68bad11b4c8bf95158641dd14f8

**Comment by ehuss** [comment]
Hm, that's interesting.  It looks like `cargo test --doc` is having problems if you depend on a package with the same name (in your case `append-log 0.1.0-dev` depends on `append-log 0.1.4-dev`).  Cargo is issuing two `--extern` flags with the same package name, which confuses rustdoc.

I think the issue is somewhere around [here](https://github.com/rust-lang/cargo/blame/d62dcd6af4ab4c43816b3d0659055f042a3d7061/src/cargo/core/compiler/context/mod.rs#L204-L219). This was changed in #3721 to attempt to address this, but the doctest case seems broken.  I'll try to look at it sometime soon.

**Comment by indutny** [comment]
Oh gosh. I've copy-pasted Cargo.toml and forgot to update it. Thank you for finding this!

It is weird that only the doc test are failing, though! Let me know if you'd like me to close the issue.

**Comment by ehuss** [comment]
Hm, thinking about it more, it may be difficult/impossible to fix.  rustdoc is building the tests from scratch and doesn't know about the local crate.

One workaround is to give the other crate a different name (using [rename](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml)), something like this:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 23d1086..f8dde9e 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -12,7 +12,7 @@ license = "MIT"
 repository = "https://github.com/indutny/append-multi-log"

 [dependencies]
-append-log = "0.1.4-dev"
+append-log-other = { version="0.1.4-dev", package="append-log" }

 [dev-dependencies]
 tempfile = "^3.0.7"
diff --git a/src/log.rs b/src/log.rs
index 86eda7a..a537fb2 100644
--- a/src/log.rs
+++ b/src/log.rs
@@ -1,6 +1,6 @@
-extern crate append_log;
+extern crate append_log_other;

-use append_log::Log;
+use append_log_other::Log;

 pub struct MultiLog {
 }
```

**Comment by indutny** [comment]
I didn't intend that package to have the same name as its dependency. Sorry for the noise. I guess it is better to close the issue then!

Thank you for help.
