### ISSUE TITLE
Cannot easily use git dependencies that contain Cargo.toml files in subdirectories

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#6822]
**Problem**
Using a git dependency from a repository that contains multiple Cargo.toml files is complicated. If any of these files are invalid (such as files that are used as input for tests), or the result of complicated vendoring situations like Gecko, Cargo tries to make sense of them even if they will not actually contribute anything to the build. Using this same dependency as a path or published package works fine since only the appropriate package's Cargo.toml is read, but the git dependency is recursively walked for all Cargo.toml files that exist.

**Steps**
1. Clone https://github.com/jdm/rust-mozjs/tree/smup66-cargo-problem
2. Run `cargo build`

**Possible Solution(s)**
One easy way out - leave the current behaviour as default, but add an extra TOML property for git deps that makes it possible to specify a particular path inside the working tree which should be treated as the package root.

**Notes**

Output of `cargo version`:
cargo 1.35.0-nightly (63231f438 2019-03-27)

Without a solution to this problem, anyone using an unusual git dep must end up modifying its contents to remove the TOML files that Cargo can't understand. This is very frustrating, especially when the other dependency modes work just fine.

**Comment by sallaben** [comment]
@ehuss example use case: referencing the shaderc-sys crate if I fork this https://github.com/google/shaderc-rs

**Comment by ehuss** [comment]
This is more or less fixed by #7947.  It would probably be good for some time in the future to have a way to restrict which directory Cargo looks at, but for now this should now work.
