### ISSUE TITLE
Test Option --last-failed-only

### ISSUE THREAD

**Issue by Nokel81** [rust-lang/cargo#6826]
**Describe the problem you are trying to solve**
I have a very large test suite that does quite a but of file IO, which makes the tests rather long to run. I need the file IO because I use external programs to verify my output. It would be very useful to be able to only run the tests that failed the last time I ran the suit.

**Describe the solution you'd like**
A new option (namely something like `--last-failed-only`) that would limit which tests are run.

**Comment by weihanglo** [comment]
We could definitely rerun a single test suite if there is any test case failed in a test suite. However, if we want to rerun only one failed test function annotated with `#[test]`, it is not currently supported (1.69). Unless we get libest JSON format stabilized (<https://github.com/rust-lang/rust/issues/49359>), there is no enough information for Cargo to rerun a single `#[test]` function.

Marked this as <https://github.com/rust-lang/cargo/labels/S-blocked-external> accordingly.

**Comment by weihanglo** [comment]
Close in favor of #10673. More discussions happen there.
