### ISSUE TITLE
cargo test does not run tests in examples

### ISSUE THREAD

**Issue by lcnr** [rust-lang/cargo#6831]
I added a test to examples/foo.rs

```rust
#[test]
fn add_works() {
    assert_eq(4 + 2, 6);
}
```

it would be great if cargo test also runs test in examples. Currently it only compiles the example projects.

The tests can currently be run by calling `cargo test --example foo`, so this should not be that complicated to implement. In case this feature may be implemented I would be glad to do this myself.

**Comment by ehuss** [comment]
You can enable tests for examples by setting `test = true` for the `[[example]]` section for each example in `Cargo.toml`, like this:

```toml
[[example]]
name = "myexample"
test = true
```

**Comment by lcnr** [comment]
@ehuss Thank you, do you know if there was a a discussion about changing be the default of this value to true?

**Comment by ehuss** [comment]
I don't think the default can be changed, as it would affect a large number of projects.  It would also add a lot of noise for the vast majority of examples which don't have tests in their examples.  I think it might be reasonable to have some heuristic to scan examples for `#[test]` attributes, and issue a hint to the user if `test = true` is not set. There might be performance implications or false positives, so I'm not sure how well that would work.
