### ISSUE TITLE
Cargo linkage fails with dependencies on -llber and -lldap

### ISSUE THREAD

**Issue by serejkus** [rust-lang/cargo#684]
Attempting to build cargo from master with prefix=$HOME:

    localhost :: repos/rust/cargo ‹master› » git status
    # On branch master
    nothing to commit, working directory cleant
    localhost :: repos/rust/cargo ‹master› » git rev-parse HEAD
    861c07f01517a7c86fea022965413e408b89d6c9
    localhost :: repos/rust/cargo ‹master› » ./configure --prefix=$HOME && make -j4 && make install
    configure: looking for configure programs
    ...
    configure: complete
    configure: 
    configure: 
    "/home/elantsev/bin/rustc" -v
    rustc 0.12.0-nightly (b5ba2f551 2014-10-06 20:27:14 +0000)
    target/snapshot/bin/cargo build --target x86_64-unknown-linux-gnu  

So, configure finishes OK. Next, fetching and compiling dependencies does not produce any issues

        Updating git repository `https://github.com/alexcrichton/flate2-rs`
        Updating git repository `https://github.com/docopt/docopt.rs`
        Updating git repository `https://github.com/alexcrichton/git2-rs`
        Updating git repository `https://github.com/lifthrasiir/rust-encoding`
        Updating git repository `https://github.com/rust-lang/glob`
        Updating git repository `https://github.com/alexcrichton/openssl-static-sys`
        Updating git repository `https://github.com/alexcrichton/toml-rs`
        Updating git repository `https://github.com/alexcrichton/curl-rust`
        Updating git repository `https://github.com/servo/rust-url`
        Updating git repository `https://github.com/rust-lang/semver`
        Updating git repository `https://github.com/alexcrichton/libssh2-static-sys`
        Updating git repository `https://github.com/alexcrichton/link-config`
        Updating git repository `https://github.com/alexcrichton/tar-rs`
        Updating git repository `https://github.com/carllerche/hamcrest-rust.git`
       Compiling glob v0.0.1 (https://github.com/rust-lang/glob#27338cbd)
       Compiling openssl-static-sys v0.0.1 (https://github.com/alexcrichton/openssl-static-sys#b46ca510)
       Compiling encoding v0.1.0 (https://github.com/lifthrasiir/rust-encoding#ea41c022)
       Compiling libssh2-static-sys v0.0.1 (https://github.com/alexcrichton/libssh2-static-sys#e084c0e0)
       Compiling link-config v0.0.1 (https://github.com/alexcrichton/link-config#0afbf50b)
       Compiling tar v0.0.1 (https://github.com/alexcrichton/tar-rs#e7c9952e)
       Compiling curl-sys v0.0.1 (https://github.com/alexcrichton/curl-rust?ref=bundle#720d87fa)
       Compiling docopt v0.6.4 (https://github.com/docopt/docopt.rs#21ce1190)
       Compiling toml v0.1.0 (https://github.com/alexcrichton/toml-rs#8cdb2747)
       Compiling flate2 v0.0.1 (https://github.com/alexcrichton/flate2-rs#2730aeaa)
       Compiling semver v0.1.0 (https://github.com/rust-lang/semver#5dee9181)
       Compiling url v0.1.0 (https://github.com/servo/rust-url#f320b1e6)
       Compiling libgit2 v0.0.1 (https://github.com/alexcrichton/git2-rs#0e068d21)
       Compiling curl v0.0.1 (https://github.com/alexcrichton/curl-rust?ref=bundle#720d87fa)
       Compiling docopt_macros v0.6.4 (https://github.com/docopt/docopt.rs#21ce1190)
       Compiling git2 v0.0.1 (https://github.com/alexcrichton/git2-rs#0e068d21)
       Compiling cargo v0.0.1-pre (file:///home/elantsev/repos/rust/cargo)
    error: linking with `cc` failed: exit code: 1
    note: cc '-m64' '-L' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-o' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/cargo' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/cargo.o' '-Wl,--whole-archive' '-lmorestack' '-Wl,--no-whole-archive' '-nodefaultlibs' '-fno-lto' '-Wl,--gc-sections' '-pie' '-Wl,--as-needed' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libnative-4e7c5e5c.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/libcargo-c7615fa0d9241c11.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libdocopt-c190fc8d655c6f84.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libtoml-a3516e82ea71aded.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libglob-54e4fdcda4a7c968.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libcurl-f3f9ef32955b72e6.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libgit2-09174fe7d724f48b.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtime-4e7c5e5c.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/liblibgit2-fcba23a36b59f31c.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/liburl-921578b148f50e06.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libencoding-4805bc5305f7cd87.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libdebug-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libserialize-4e7c5e5c.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libsemver-6324dd0606536988.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libopenssl-static-sys-6ae299ea46a69e57.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libflate2-7571a86064e76c6d.rlib' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps/libtar-6ccba66e5440ac37.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libregex-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libsync-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustrt-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode-4e7c5e5c.rlib' '/home/elantsev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4e7c5e5c.rlib' '-L' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu' '-L' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/deps' '-L' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/native/libgit2-fcba23a36b59f31c' '-L' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/native/openssl-static-sys-6ae299ea46a69e57' '-L' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/native/libssh2-static-sys-c29829f2cf163ffd' '-L' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/native/flate2-7571a86064e76c6d' '-L' '/home/elantsev/repos/rust/cargo/target/x86_64-unknown-linux-gnu/native/curl-sys-9d9d6a6df3c98f14' '-L' '/home/elantsev/repos/rust/cargo/.rust' '-L' '/home/elantsev/repos/rust/cargo' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-archive' '-Wl,-Bdynamic' '-lcurl' '-lidn' '-lssh2' '-lssl3' '-lsmime3' '-lnss3' '-lnssutil3' '-lplds4' '-lplc4' '-lnspr4' '-lpthread' '-ldl' '-lgssapi_krb5' '-lkrb5' '-lk5crypto' '-lcom_err' '-llber' '-lldap' '-lz' '-lrt' '-lrt' '-lssl' '-lgssapi_krb5' '-lkrb5' '-lcom_err' '-lk5crypto' '-lcrypto' '-ldl' '-lz' '-ldl' '-lpthread' '-lgcc_s' '-lpthread' '-lc' '-lm' '-lcompiler-rt'
    note: /usr/bin/ld: cannot find -llber
    /usr/bin/ld: cannot find -lldap
    collect2: error: ld returned 1 exit status

    error: aborting due to previous error
    Could not compile `cargo`.

    To learn more, run the command again with --verbose.
    make: *** [cargo-x86_64-unknown-linux-gnu] Error 101

I've grepped cargo's dependencies to check for llber and lldap, it seems like it is curl-rust who could bring them. It builds libcurl inside self, and it seems like some of the options are not passed to libcurl's configure.
OS: Fedora 19.

**Comment by alexcrichton** [comment]
I think that this has long since been fixed, but feel free to reopen if it still happens!
