### ISSUE TITLE
In the default Cargo.toml template provide help for completing the metadata

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#6845]
Currently `cargo new` generates `Cargo.toml` with absolutely minimal set of fields.

It's left up to users to discover and learn about other `Cargo.toml` fields. I think it could be improved, for example:

* Insert comments with hints or links, e.g.   
   `# See more https://doc.rust-lang.org/cargo/reference/manifest.html`

* Insert some fields with default or empty values, e.g. `categories = [] # https://crates.io/category_slugs`. That would show users that this field exists, and prompt them to complete it. The category field in particular is often missing, and that reduces usefulness of browsing https://crates.io/categories

**Comment by k-nasa** [comment]
I think this is wonderful 😄

**Comment by k-nasa** [comment]
May I work on this?

**Comment by kornelski** [comment]
I don't mind :)

**Comment by k-nasa** [comment]
Thank you!
