### ISSUE TITLE
Request api token if necessary instead of error after building when publishing a crate

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/cargo#6847]
**Describe the problem you are trying to solve**

I forgot to login before using `cargo publish`. It started building the crate to verify it, but when it was finished it gave an error about not being logged in. When I logged in I had to wait for it getting built again.

**Describe the solution you'd like**

Either error immediately after running `cargo publish` without logging in first or ask for an api key.

**Comment by fluffysquirrels** [comment]
I can take a look at this.

**Comment by fluffysquirrels** [comment]
For my own benefit at least, here is the relevant control flow on the current master:

* [cargo publish CLI command](https://github.com/rust-lang/cargo/blob/ef0223f12597b5e0d9d2feed1b92c41306b1fc05/src/bin/cargo/commands/publish.rs)
* [src/cargo/ops/registry.rs](https://github.com/rust-lang/cargo/blob/ef0223f12597b5e0d9d2feed1b92c41306b1fc05/src/cargo/ops/registry.rs)
  * fn publish: verifies, calls package, calls transmit
  * fn transmit: calls crates_io::Registry.publish, bails if publish is a dry-run
* [src/crates-io/lib.rs](https://github.com/rust-lang/cargo/blob/ef0223f12597b5e0d9d2feed1b92c41306b1fc05/src/crates-io/lib.rs): API for crates.io, (other registries too?)
  * struct Registry
  * [Registry::publish](https://github.com/rust-lang/cargo/blob/ef0223f12597b5e0d9d2feed1b92c41306b1fc05/src/crates-io/lib.rs#L163-L244) does the HTTP request to "${HOST}/api/v1/crates/new", contains the error message "no upload token found, please run `cargo login`"

**Comment by fluffysquirrels** [comment]
So it looks like we could run the auth token check from `crates-io/lib.rs`' `fn Registry::publish` in `cargo/ops/registry.rs`' `fn publish` when the publish is not a dry-run. We already have a `Registry` instance at this point, so how about we keep this DRY by creating a utility method on `impl Registry` to check we have the necessary token?

I'm not sure what automated testing is already done on this part of the code base, I'll take a quick look at that next.

**Comment by fluffysquirrels** [comment]
grepping for the error message "no upload token found" reveals 2 call sites and 2 tests:
```
~/Code/cargo % rg -e "no upload token found"
src/crates-io/lib.rs
201:            None => bail!("no upload token found, please run `cargo login`"),
295:                None => bail!("no upload token found, please run `cargo login`"),

tests/testsuite/publish.rs
136:        .with_stderr_contains("[ERROR] no upload token found, please run `cargo login`")

tests/testsuite/alt_registry.rs
422:        .with_stderr_contains("error: no upload token found, please run `cargo login`")
```
So this error is already tested and the tests should still pass if the error message is returned earlier, so I don't anticipate changing the tests substantially.

**Comment by fluffysquirrels** [comment]
Hmmm, I wrote code for this and then realised it's not I-nominated yet, as required by the [contribution guidelines](https://github.com/rust-lang/cargo/blob/master/CONTRIBUTING.md). I'm asking in Discord about it but until I get a reply the changes are on my branch here: https://github.com/fluffysquirrels/cargo/tree/validate-login
