### ISSUE TITLE
Sources and registries documentation suggestions

### ISSUE THREAD

**Issue by fluffysquirrels** [rust-lang/cargo#6862]
CC: @ehuss as discussed on discord

These are suggestions only, happy to discuss.

[Source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html):

* Define a "source" on this page, perhaps copying [the definition from the glossary](https://doc.rust-lang.org/cargo/appendix/glossary.html#source).
* There are two blocks of toml near the top of this page that define the configuration for source replacement. Merge these.
* "[P]rivate registry support is planned for a future version of Cargo.": the future is here! Link to the registries documentation.
* Describe when sources are used: when cargo fetches source code for dependencies to build them. Are there other cases? List some of the commands that use sources.
* Add links to `cargo-local-registry` and `cargo-vendor` on crates.io

[Registries](https://doc.rust-lang.org/cargo/reference/registries.html):

* ~~Links to cargo-local-registry~~  __EDIT:__ I don't think local registries are supported by e.g. `cargo publish` and `cargo login`, so this is not relevant.

----------

I'm happy to submit a PR for these. I may have other suggestions as I start to write.

Hope that helps!

**Comment by ehuss** [comment]
These sound great!

> Are there other cases?

Just for dependencies.

> Add links to cargo-local-registry and cargo-vendor on crates.io

The source replacement page does link to both of the commands.  Maybe because the CSS style for `code` overrides the `a` link styling it's hard to see.  I believe this is due to rust-lang-nursery/mdbook#537.

Thanks!  Any help with clarifying and expanding the docs is greatly appreciated!

**Comment by fluffysquirrels** [comment]
@ehuss, thanks for the clarifications.

Given the mdBook issue hasn't been updated in 6 months, is it worth sidestepping it and rendering the links like: 

> The primary way to manage and create local registry sources is through the `cargo-local-registry` subcommand, available as a [crate on crates.io](https://crates.io/crates/cargo-local-registry), and can be installed with `cargo install cargo-local-registry`.

I'm working on the other edits.
