### ISSUE TITLE
error during cargo update, something about link

### ISSUE THREAD

**Issue by idotial** [rust-lang/cargo#6868]
**Problem**
When i add a dependency to a project, and run `cargo update`, it shows a error.
```
  Updating crates.io index
    Blocking waiting for file lock on the git checkouts
    Blocking waiting for file lock on the git checkouts
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/idotial/rust-fil-proofs.git`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/bellman`
    Updating git repository `https://github.com/filecoin-project/pairing`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/phase2`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/sapling-crypto`
    Updating git repository `https://github.com/oconnor663/blake2s_simd`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/tyranron/config-rs`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/merkle_light`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/gtank/blake2-rfc`
    Blocking waiting for file lock on the registry index
error: failed to select a version for `parity-rocksdb-sys`.
    ... required by package `parity-rocksdb v0.5.0`
    ... which is depended on by `kvdb-rocksdb v0.1.4`
    ... which is depended on by `storage v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/core/storage)`
    ... which is depended on by `beacon v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/beacon)`
    ... which is depended on by `client v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/client)`
    ... which is depended on by `alphanet v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/alphanet)`
    ... which is depended on by `devnet v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/devnet)`
    ... which is depended on by `filesys v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust)`
versions that meet the requirements `^0.5` are: 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0

the package `parity-rocksdb-sys` links to the native library `rocksdb`, but it conflicts with a previous package which links to `rocksdb` as well:
package `librocksdb-sys v5.17.2`
    ... which is depended on by `rocksdb v0.12.0`
    ... which is depended on by `filecoin-proofs v0.1.0 (https://github.com/idotial/rust-fil-proofs.git#53676171)`
    ... which is depended on by `filesys v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust)`

failed to select a version for `parity-rocksdb-sys` which could resolve this conflict
```

**Steps**
1.new a project depended on `parity-rocksdb v0.5.0`
2.add a dependency which require `rocksdb v0.12.0`
3.cargo update

**Notes**
cargo 1.36.0-nightly (b6581d383 2019-04-16)
macOS 10.14.4 (18E226)

**Comment by idotial** [comment]
> ⇒  cargo update
    Updating crates.io index
    Blocking waiting for file lock on the registry index
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/nearprotocol/pairing.git`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/nearprotocol/wasmer.git`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/idotial/rust-fil-proofs.git`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/bellman`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/pairing`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/phase2`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/sapling-crypto`
    Updating git repository `https://github.com/oconnor663/blake2s_simd`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/tyranron/config-rs`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/merkle_light`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/gtank/blake2-rfc`
    Blocking waiting for file lock on the registry index
error: failed to select a version for `parity-rocksdb-sys`.
    ... required by package `parity-rocksdb v0.5.0`
    ... which is depended on by `kvdb-rocksdb v0.1.4`
    ... which is depended on by `storage v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/core/storage)`
    ... which is depended on by `beacon v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/beacon)`
    ... which is depended on by `client v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/client)`
    ... which is depended on by `alphanet v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/alphanet)`
    ... which is depended on by `devnet v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/devnet)`
    ... which is depended on by `filesys v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust)`
versions that meet the requirements `^0.5` are: 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0

the package `parity-rocksdb-sys` links to the native library `rocksdb`, but it conflicts with a previous package which links to `rocksdb` as well:
package `librocksdb-sys v5.17.2`
    ... which is depended on by `rocksdb v0.12.0`
    ... which is depended on by `filecoin-proofs v0.1.0 (https://github.com/idotial/rust-fil-proofs.git#53676171)`
    ... which is depended on by `filesys v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust)`

failed to select a version for `parity-rocksdb-sys` which could resolve this conflict

**Comment by idotial** [comment]
`⇒  cargo update
    Updating crates.io index
    Blocking waiting for file lock on the registry index
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/nearprotocol/pairing.git`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/nearprotocol/wasmer.git`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/idotial/rust-fil-proofs.git`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/bellman`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/pairing`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/phase2`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/sapling-crypto`
    Updating git repository `https://github.com/oconnor663/blake2s_simd`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/tyranron/config-rs`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/filecoin-project/merkle_light`
    Blocking waiting for file lock on the git checkouts
    Updating git repository `https://github.com/gtank/blake2-rfc`
    Blocking waiting for file lock on the registry index
error: failed to select a version for `parity-rocksdb-sys`.
    ... required by package `parity-rocksdb v0.5.0`
    ... which is depended on by `kvdb-rocksdb v0.1.4`
    ... which is depended on by `storage v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/core/storage)`
    ... which is depended on by `beacon v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/beacon)`
    ... which is depended on by `client v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/client)`
    ... which is depended on by `alphanet v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/alphanet)`
    ... which is depended on by `devnet v0.1.0 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust/node/devnet)`
    ... which is depended on by `filesys v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust)`
versions that meet the requirements `^0.5` are: 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0

the package `parity-rocksdb-sys` links to the native library `rocksdb`, but it conflicts with a previous package which links to `rocksdb` as well:
package `librocksdb-sys v5.17.2`
    ... which is depended on by `rocksdb v0.12.0`
    ... which is depended on by `filecoin-proofs v0.1.0 (https://github.com/idotial/rust-fil-proofs.git#53676171)`
    ... which is depended on by `filesys v0.0.1 (/Users/chenrui/Desktop/blockchain/WendingWorkStation/ipfs/filesys-rust)`

failed to select a version for `parity-rocksdb-sys` which could resolve this conflict`

**Comment by idotial** [comment]
https://github.com/idotial/testlinks.git here is the example project, run cargo update can set the error.

**Comment by Eh2406** [comment]
If I had to guess the repeated `Blocking waiting for file lock on the git checkouts` is do to an editor running cargo commands at the same time you are and leeding to lock contention. 

The error message I get from your testlinks is:
```
cargo generate-lockfile
    Updating crates.io index
error: failed to select a version for `parity-rocksdb-sys`.
    ... required by package `parity-rocksdb v0.5.0`
    ... which is depended on by `testlinks v0.1.0 (C:\issues6868)`
versions that meet the requirements `^0.5` are: 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0

the package `parity-rocksdb-sys` links to the native library `rocksdb`, but it conflicts with a previous package which links to `rocksdb` as well:
package `librocksdb-sys v5.17.2`
    ... which is depended on by `testlinks v0.1.0 (C:\issues6868)`

failed to select a version for `parity-rocksdb-sys` which could resolve this conflict
```

This is saying that `parity-rocksdb = "0.5"` useses an older version (`0.5`) of `parity-rocksdb-sys` witch is not compatible with the new version (`5.17`) of `librocksdb-sys` that you asked for. In general cargo lets you have more then one semver in-compatible version, but there is an exception for `sys`  crates. `sys`  crates specify a `links` attribute that tells cargo that they will not work if linked more than once.

**Comment by idotial** [comment]
@Eh2406 you are right. `parity-rocksdb-sys` and `librocksdb-sys` both specify a links attribute as `rocksdb`. I have check the source file of this two crate, the `rocksdb` that they included looks the same(have the same interface), is there any way i can combine the links of `rocksdb` or make it specified in outer project(in testlinks's cargo.toml) without changing the content of this two crete.

**Comment by Eh2406** [comment]
I am almost certain that you can't from the outside. If they really have the same interface, and link to the same thing, then you can make a branch of `parity-rocksdb`or `rocksdb` to use the other ones sys crate. Then you can use the [`[replace]`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-replace-section) section to make the dependency tree use your version.

**Comment by epage** [comment]
As it looks like the the concern has been resolved.  I'm at least not seeing a way to further improve this error message.  I'm going to go ahead and close this.  If there is a reason for us to re-evaluate this, let us know!
