### ISSUE TITLE
Bash syntax errors reported when loading cargo shell completions

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/cargo#6874]
This is a re-report of https://github.com/rust-lang/rustup.rs/issues/1799, per the comment it received.

---

**Problem**

The cargo command completion shell script produces syntax errors when loaded:

```
-bash: /redacted/.rustup/toolchains/stable-x86_64-apple-darwin/etc/bash_completion.d/cargo: line 82: syntax error in conditional expression: unexpected token `('
-bash: /redacted/.rustup/toolchains/stable-x86_64-apple-darwin/etc/bash_completion.d/cargo: line 82: syntax error near `@(t'
-bash: /redacted/.rustup/toolchains/stable-x86_64-apple-darwin/etc/bash_completion.d/cargo: line 82: `		if [[ "${cmd}" = @(test|bench) ]]; then'
```

**Steps**

1. Install latest rustup. I'm using rustup 1.18.0 (8603e2c56 2019-04-22).
2. Run `source $(rustc --print sysroot)/etc/bash_completion.d/cargo` in a shell.
3. Observe output.

**Possible Solution(s)**

**Notes**

Output of `bash --version`:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.

Output of `rustup --version`: rustup 1.18.0 (8603e2c56 2019-04-22)
Output of `cargo --version`: cargo 1.34.0 (6789d8a0a 2019-04-01)

**Comment by ArifRoktim** [comment]
The `@(pattern-list)` syntax was introduced in bash 4.0. Is it feasible for you to update your version of bash?

**Comment by jimmycuadra** [comment]
I'm apparently using the version that comes installed on the latest macOS. I could have sworn I used to have a more recent version installed via Homebrew...

In any case, I can fix upgrade/enable the option, but if this script will fail in the same way for everyone else on stock macOS, that doesn't seem acceptable.
