### ISSUE TITLE
Enable namspaces for packages

### ISSUE THREAD

**Issue by calidion** [rust-lang/cargo#6886]
Currently cargo seems only have global namespace which all packages are sharing with.

I would like to suggest cargo to introduce namespaces for packages which can avoid name collisions.

for instance:

```
cargo install serializer@std
cargo install crypto@vigcoin
cargo install hash@vigcoin
cargo install cryptonight@hash@vigcoin
cargo install cryptonight:v7@hash:12.1.0@vigcoin:latest
```

**Comment by Eh2406** [comment]
This would be a crates.io feature. The conversation would start with a post on internals. But it has bean brought up many times before: https://internals.rust-lang.org/search?q=namespaces

So I am going close this discussion.
