### ISSUE TITLE
can_not_mix_doc_tests_and_regular_tests test is failing

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6887]
The [`can_not_mix_doc_tests_and_regular_tests`](https://github.com/rust-lang/cargo/blob/8fd0bd46e674be5eec1ae6ff397b436ccf5e11a0/tests/testsuite/test.rs#L3506-L3587) test has failed randomly a few times recently on Travis:

https://travis-ci.com/rust-lang/cargo/jobs/185086470 (#6749, 2019-03-14)
https://travis-ci.com/rust-lang/cargo/jobs/196095265 (#6884, 2019-04-28)

Both were `x86_64-unknown-linux-gnu`, one was on `1.34.1` and the other was `1.35.0-nightly (bc44841ad 2019-03-14)`.

I cannot reproduce this. I have tried running the test in a loop for hours and I can't get it to fail. The test is very basic, and I can't imagine how it is possibly failing.  Essentially it does:

1. `cargo test`
2. `cargo test --lib`
3. `cargo test --doc` ← This step fails because it rebuilds the library.

It may be unrelated, but this started after recent changes to fingerprints (#6720, #6734).  The test was added 2018-09-16.

**Comment by epage** [comment]
@ehuss the test is enabled and I'm not seeing any talk of this failing lately.  Can we close this?

**Comment by ehuss** [comment]
Yea, I think it is fine to close.
