### ISSUE TITLE
Add cargo test --release

### ISSUE THREAD

**Issue by ebfe** [rust-lang/cargo#691]
Unless I'm missing something, there is currently no way to run tests with optimizations turned on.

**Comment by psdh** [comment]
I would like to fix this. How should I go about it?

**Comment by alexcrichton** [comment]
It'd probably start off with adding `--release` to the `src/bin/test.rs` file and then propagating the changes downwards to get the optimizations turned on in `src/cargo/ops/cargo_rustc`. That being said there's some internal refactoring which needs to happen to enable a change such as this, so I don't think that it will be easy to accomplish unfortunately.

**Comment by alexcrichton** [comment]
This should now be very easy to do now that #1441  has landed!

**Comment by alexcrichton** [comment]
@psdh would you still be interested in implementing this?

**Comment by psdh** [comment]
I was actually trying to figure this out yesterday. I would love to fix this. Does this now just involve changes to the `src/bin/test.rs` ?

**Comment by alexcrichton** [comment]
Yes that should be easy enough to add the flag, and then the other half would be writing a test to ensure that it works correctly (e.g. passes optimization flags).

**Comment by alexcrichton** [comment]
Done!
