### ISSUE TITLE
After rustup to stable dawrin channel, then cargo-fmt can't be installed

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [rust-lang/cargo#6911]
**Problem**

Problems reported elsewhere when rustup is run and then rustfmt and cargo-fmt are removed and then cannot be located by rustup to be installed again after update.

rustfmt successfully reinstalled after rustup by executing the following commands:

> rustup self update

to confirm the fix the following command finds 'rustfmt' for the stable toolchain

> rustup run stable rustfmt --version
rustfmt 1.0.3-stable (d6829d62 2019-02-14)

But even after the self update, cargo-fmt is still missing ....

>rustup run stable rustfmt --version
rustfmt 1.0.3-stable (d6829d62 2019-02-14)
 
Then when attempting to run cargo to install cargo-fmt ...
                                                         
➜  cargo install cargo-fmt
    Updating crates.io index
error: could not find `cargo-fmt` in registry `https://github.com/rust-lang/crates.io-index`

Even attempts to install cargo-fmt using the now updated rustup and cargo.io package index fail ....

rustup component add cargo-fmt --toolchain stable-x86_64-apple-darwin
error: toolchain 'stable-x86_64-apple'

All this is run on OSX 10.9 

Output of `cargo version`:

**Comment by pinnaclesystemsgroup** [comment]
After further searching for an answer to this problem, I located the following: 

cargo-fmt is now bundled with rustfmt, so please use that instead. More information can be found at https://github.com/rust-lang-nursery/rustfmt

Found here: >>> https://github.com/pwoolcoc/cargo-fmt

**Comment by ehuss** [comment]
Yes, `cargo fmt` is now shipped with the `rustfmt` component in rustup.
