### ISSUE TITLE
Cargo should provide --remap-path-prefix or not hash it from RUSTFLAGS.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/cargo#6914]
After #6503, reproducible build setups that were setting `RUSTFLAGS="--remap-path-prefix=..."` in order to normalize paths in rustc, stopped being reproducible, as Cargo is now hashing the whole `RUSTFLAGS` value, resulting in different `-C metadata` values.

This was originally reported in https://github.com/rust-lang/rust/issues/59542, and one of the solutions suggested there was that Cargo should provide its own `--remap-path-prefix`, which *would not be* hashed, and that becomes the supported way set this flag.

Another possibility could be Cargo parsing `--remap-path-prefix` out of `RUSTFLAGS`, before hashing the rest, but that seems perhaps a bit brittle.

cc @michaelwoerister @Eh2406

**Comment by jhfrontz** [comment]
Can I petition to have this changed from "feature request" to "use-blocking bug"?  I mean, it was working fine until it got broken.

**Comment by alexcrichton** [comment]
One workaround for this which I've forgotten to mention earlier is something like this:

```sh
$ RUSTC=./my-rustc-wrapper.sh cargo build
```

and the contents of `my-rustc-wrapper.sh` are:

```sh
#!/bin/sh
exec rustc "$@" --remap-path-prefix ...
```

and that will subvert Cargo's hashing.
