### ISSUE TITLE
`cargo fmt` panics

### ISSUE THREAD

**Issue by ark0f** [rust-lang/cargo#6922]
**Problem**

`cargo fmt` panics instead of printing incorrect close delimiter message

**Steps**

1. Create simple cargo project
2. Use source code below

`main.rs`:
```rust
mod crash_test;

fn main() {}
```
`crash_test.rs`:
```rust
fn some_func() {
    anything_or_nothing(here_too
}
```
3. Call `cargo fmt`

**Possible Solution(s)**

**Notes**
Output of `cargo version`: `cargo 1.34.0 (6789d8a0a 2019-04-01)`

Output of `cargo fmt --version`: `rustfmt 1.0.3-stable (d6829d62 2019-02-14)`

Panic message:
```
thread 'main' panicked at 'Request to format inverted span: Loc { file: SourceFile(\\?\E:\ark0f\Programming\Rust\projects\report\src\crash_test.rs), line: 3, col: CharPos(1), col_display: 1 } to Loc { file: SourceFile(\\?\E:\ark0f\Programming\Rust\projects\report\src\crash_test.rs), line: 3, col: CharPos(0), col_display: 0 }', src\tools\rustfmt\src\missed_spans.rs:97:9
```

Expected message (I called `rustfmt src/crash_test.rs` and it works fine):
```rust
error: incorrect close delimiter: `}`
 --> \\?\E:\ark0f\Programming\Rust\projects\report\src\crash_test.rs:3:1
  |
1 | fn some_func() {
  |                - close delimiter possibly meant for this
2 |     anything_or_nothing(here_too
  |                        - un-closed delimiter
3 | }
  | ^ incorrect close delimiter
```

**Comment by ehuss** [comment]
Thanks for the report!  This appears to be fixed in 1.35 (currently in beta), see https://github.com/rust-lang/rustfmt/issues/3429.  Feel free to reopen if the newer versions don't work for you.
