### ISSUE TITLE
Should cargo package check for new directories?

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/cargo#6931]
In trying to work around a [problem involving excludes](https://users.rust-lang.org/t/cargo-exclude-all-contents-of-a-directory-but-keep-the-directory/28137) I noticed that `cargo package` does not complain about a build script that creates directories:

**`build.rs`**

```rust
fn main() {
    // 'cargo package' is designed to fail if you do this:
    // let _ = std::fs::File::create("lol.txt");

    // but it's okay with this:
    let _ = std::fs::create_dir("lol");
}
```

Is this a feature or a bug?  

**Notes**

cargo 1.36.0-nightly (759b6161a 2019-05-06)

**Comment by lukaslueg** [comment]
Empty directories are not tracked by git, therefore creating an empty directory does mark the workspace as being dirty.

**Comment by ExpHP** [comment]
Sorry, I am referring to this error message:

```
$ cargo package
warning: manifest has no description, license, license-file, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
   Packaging buildme v0.1.0 (/home/lampam/cpp/throwaway/buildme)
   Verifying buildme v0.1.0 (/home/lampam/cpp/throwaway/buildme)
   Compiling buildme v0.1.0 (/home/lampam/cpp/throwaway/buildme/target/package/buildme-0.1.0)
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
Added: /home/lampam/cpp/throwaway/buildme/target/package/buildme-0.1.0/lol.txt
```

**Comment by ehuss** [comment]
Build scripts probably shouldn't be creating empty directories.  The "does not modify" check during packaging isn't really intended to be bullet-proof.  However, it recently changed and it would be trivial to add a check for directories by checking for a directory [here](https://github.com/rust-lang/cargo/blob/1d75407858c29f0a8f58b39635c68bc25c8b0968/src/cargo/ops/cargo_package.rs#L661) if someone wants to.

**Comment by ExpHP** [comment]
Looks quite trivial indeed!  I'll have a go at it.
