### ISSUE TITLE
Cargo new --example

### ISSUE THREAD

**Issue by Alxandr** [rust-lang/cargo#6939]
**Describe the problem you are trying to solve**

Make it easier to add examples to a project.

**Describe the solution you'd like**

I would like a basic scaffold of an example, probably with just an empty main method when I run `cargo new --example <name>`.

**Comment by jesselawson** [comment]
So if I were to run `cargo new --example celeryman`, what would be different code-wise from running `cargo new celeryman`? 

I wonder if you might be referring to scaffolding, and are hoping to get some Yeoman-esque functionality in the cargo tool?

**Comment by Alxandr** [comment]
Probably only that it lands in "examples" folder. I'm not looking for much.
Just a little help for the people who's new, and don't know how the
examples should look. For instance, I'm making a library, and had to go
look up how a main method in rust looks, cause I didn't remember. Then, I
didn't know if I could do examples/<name>/main.rs, or if I had to do
examples/<name>.rs. Also, considering there's `run --example`, I would say
it fits together, and I sort of expected it to work.

**Comment by mbartelsm** [comment]
It would be nice to have this feature.

The command should generate:
* An `examples` folder, if one doesn't exist already
* A `examples/{name}` subfolder
* A `examples/{name}/main.rs` file, potentially with a hello-world program, much like with the standard `cargo new` command
* The necessary manifest data within the `cargo.toml` file of the root project.

**Comment by theWebalyst** [comment]
It would help if the docs for `cargo run --example` said more than 'Runs the specified example' [here](https://doc.rust-lang.org/cargo/commands/cargo-run.html). That's just annoying. I got there by searching the web, but so far haven't found an explanation of what it really means and how to create an example.

I can just copy stuff from an [cough] example crate and fiddle until it works, but it would help to have a pointer to an explanation in the docs.

**Comment by mbartelsm** [comment]
Yeah, there's also that. The only reason I know about the feature is because I noticed a large-ish project using it and I reverse engineered it. The docs weren't of much help.

**Comment by epage** [comment]
From #3832

> As of now, `cargo init` doesn't really generate many files. I doubt it worth making it additive. That said, when cargo gets `cargo-template` support (#5151), this might be quite interesting to explore.

**Comment by TheToddmeister** [comment]
Bumping this one for interest
