### ISSUE TITLE
Cargo prints warnings with full paths

### ISSUE THREAD

**Issue by vrinek** [rust-lang/cargo#694]
`cargo build` prints compile time warnings using full file paths. This results in very long lines making it either wrap on a moderately widened terminal window and/or hard to follow.

Sample cargo output:
```
$ cargo build
   Compiling hello_world v0.0.1 (file:///Users/kostaskarachalios/Code/Learning/Rust/guide/hello_world)
/Users/kostaskarachalios/Code/Learning/Rust/guide/hello_world/src/main.rs:2:9: 2:14 warning: value assigned to `x` is never read, #[warn(dead_assignment)] on by default
/Users/kostaskarachalios/Code/Learning/Rust/guide/hello_world/src/main.rs:2     let mut x = 5i;
                                                                                    ^~~~~
```

For comparison:
```
$ rustc src/main.rs
src/main.rs:2:9: 2:14 warning: value assigned to `x` is never read, #[warn(dead_assignment)] on by default
src/main.rs:2     let mut x = 5i;
                      ^~~~~
```

Versions: 
```
$ cargo -V
cargo 0.0.1-pre-nightly (0881adf 2014-10-10 22:03:11 -0700)
$ rustc -v
rustc 0.13.0-nightly (adb44f53d 2014-10-12 00:07:15 +0000)
```

**Comment by Stibbons** [comment]
Please let the user have the choice. You can have cargo build --rel-path and cargo build --full-path and have one of them by default, but you will never find one that fit everyone !

I absolutely need absolute path for integration in some IDE, but some might not need it. Command line parameter is the key.

**Comment by vrinek** [comment]
I agreed with @Stibbons. For now we just need the command line option and either of them as a default.

**Comment by emoon** [comment]
I would also like to have the option of having a `--full-paths` option to allow for easier integration into editors. Currenty I'm using another build system to build Rust code and it invokes Cargo. The problem is that sometimes the paths will show up as `src/something.rs` which is somewhere with in the tree and the editor can't find it.

**Comment by alexcrichton** [comment]
@emoon I think we could definitely do that, want to open a separate issue to track that?

**Comment by emoon** [comment]
Awesome! Will do :) Thanks.
