### ISSUE TITLE
cargo doc --all -p mypackage --open should work

### ISSUE THREAD

**Issue by martinellison** [rust-lang/cargo#6949]
I want to be able to generate doco for all crates in and dependent on a workspace.

**Describe the solution you'd like**
I would like to be able to run a command like `cargo doc --all --open` or `cargo doc --all -p somecrate --open` and get documentation for all the crates that are (a) in my package or (b) dependent on them (or just the specified crate and its dependencies, if I specify one of the crates in my workspace).

**Notes**
At the moment, I get an error message:
```
error: Passing multiple packages and `open` is not supported.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following
... [list of crates]
```

**Comment by ehuss** [comment]
This should be fixed in 1.35 (which releases next week).  Can you try out the beta and see if it works for you?

**Comment by martinellison** [comment]
It's working in nightly, anyway. Thanks.

**Comment by ehuss** [comment]
Do you have javascript enabled?

**Comment by martinellison** [comment]
> Do you have javascript enabled?

javascript.enabled;true

**Comment by ehuss** [comment]
Hm, that's strange.  Just to be clear, is the "Crates" listing in the sidebar visible? Is it empty?  Did Cargo print out that it was "Documenting" the crates?  Are the crates listed in `target/doc/…`?  Are there any errors printed on the javascript console?  Have you tried different browsers?  Running `cargo clean`?  Failing that, can you create an [MRE](https://stackoverflow.com/help/reprex)?

**Comment by martinellison** [comment]
Now this is working differently on two different boxes. On one box, after a few seconds, a list of crates appears, which is what I want,

On the box that I am using at the moment, that does not happen. So let me check your questions.

...is the "Crates" listing in the sidebar visible? _No._

~~Is it empty? ~~

Did Cargo print out that it was "Documenting" the crates?  _Yes._

Are the crates listed in target/doc/…? _Yes._

Are there any errors printed on the javascript console? _Yes: TypeError: paths is undefined_

>     buildIndex file:///home/martin/git/shmup2/target/doc/main.js:95
>     initSearch file:///home/martin/git/shmup2/target/doc/main.js:95
>     <anonymous> file:///home/martin/git/shmup2/target/doc/search-index.js:758

I hope that helps.

**Comment by ehuss** [comment]
Hm, so some time ago rustdoc changed (presumably a change in the minifier).  The only way I can think of this happening is if you documented different crates with different versions of cargo.  Did you run `cargo clean` and try again, making sure only one version of cargo is used?

**Comment by martinellison** [comment]
@ehuss I did `cargo clean` and it is working now thanks.
