### ISSUE TITLE
Ability To Use Targets In cfg_attr

### ISSUE THREAD

**Issue by raytiley** [rust-lang/cargo#6950]
I am trying to conditionally compile other attributes based on the target `debug` or `release` but it doesn't seem like this is possible.

An example of what I would like to see work is

`#![cfg_attr(release, windows_subsystem = "windows")]`

The above allows me to have a console window for diagnostics in development, but for it to not be created for release builds. This is one example, but I imagine there are other times where it would be useful to conditionally include attributes based on the target output.

**Comment by ehuss** [comment]
This is commonly accomplished by checking the [`debug_assertions`](https://doc.rust-lang.org/reference/conditional-compilation.html#debug_assertions) cfg option.

`#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]`

Alternatively, you can use [cargo features](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section), and manually pass `--features` when you need it.
