### ISSUE TITLE
`cargo metadata --no-deps` in workspace with local dep emits wrong workspace members

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/cargo#6952]
**Problem**

When running `cargo metadata --no-deps` in a workspace with local dependency, the output contains wrong wrong workspace member.

For example, consider a workspace with the following structure:

```
.
├── bar
│   ├── Cargo.toml
│   └── src
├── Cargo.toml
├── foo
│   ├── Cargo.toml
│   └── src
└── foobar
    ├── Cargo.toml
    └── src
```

The workspace has two members `foo` and `bar`, and `foobar` as a local dependency.

```toml
# Cargo.toml
[workspace]
members = [
    "foo",
    "bar",
]
```
```toml
# foo/Cargo.toml
[dependencies]
foobar = { path = "../foobar" }
```

In this setup, I expect the output of `cargo manifest --no-deps` does not include `foobar` as a workspace member, but it actually does.

**Steps**

1. `git clone https://github.com/topecongiro/dummy-workspace && cd dummy-workspace`
2. `cargo metadata --no-deps --format-version 1`

**Expected behavior**

`workspace_members` field only contains `foo` and `bar`.

**Actual behavior**

`workspace_members` field contains `foo`, `bar` and `foobar`:

```
  "workspace_members": [
    "foo 0.1.0 (path+file:///home/topecongiro/workspace/dummy-workspace/foo)",
    "foobar 0.1.0 (path+file:///home/topecongiro/workspace/dummy-workspace/foobar)",
    "bar 0.1.0 (path+file:///home/topecongiro/workspace/dummy-workspace/bar)"
  ],
```

**Notes**

Output of `cargo version`: `cargo 1.36.0-nightly (c4fcfb725 2019-05-15)`

**Comment by ehuss** [comment]
All `path` dependencies are implicitly members of the workspace. This is documented [here](https://doc.rust-lang.org/cargo/reference/manifest.html#the-workspace-section).  The `exclude` key can be used to remove path dependencies you don't want.

**Comment by topecongiro** [comment]
Thank you, I wan't aware of that.
