### ISSUE TITLE
cargo doc --open does not show crates, only the system involved

### ISSUE THREAD

**Issue by gbonnema** [rust-lang/cargo#6955]
**Problem**
When running `cargo doc --open` I get a page of the crate I am having a look at, but I do not get the crates even though I created `--all`. I checked the `target` directory contains all crates.

**Notes**

I am not 100% sure it is a bug, because the crate maintainer (using a nightly version of cargo) does get the crates when he does `cargo doc --open`. So it might be a feature that was added recently. I am using version `cargo 1.34.0 (6789d8a0a 2019-04-01)`.

I run the statement on `gyscos/Cursive` and get the output as in the following image. The issue on Cursive leading to this issue being posted is https://github.com/gyscos/Cursive/issues/347.

![image](https://user-images.githubusercontent.com/2283947/57954974-cbea6400-78f4-11e9-987c-b2f3f1535064.png)

**Comment by ehuss** [comment]
That's unusual, rustdoc has supported that for some time, so it is not recent.

Can you confirm that you have javascript enabled?  The list is built dynamically in the browser. You can also check the javascript console to see if there are any errors or messages?

Also, just to confirm, the crates all have separate directories in `target/doc/…`?  Have you tried running `cargo clean` and then `cargo doc` again?

I assume that's firefox in the picture? Have you tried other browsers?

**Comment by gbonnema** [comment]
Thanks for the swift response.

You are completely right. I knew it when you mentioned javascript. I have noscript, ghostery and adblock plus active. As soon as I marked `file:` for being trusted, the crates appeared.

My bad. I should have realised. P.S. I will leave closing the issue to you.
