### ISSUE TITLE
build script not found while compiling project using musl in docker container

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/cargo#6960]
**Problem**
`build script not found` error happens while compiling cargo project using docker container

**Steps**

https://github.com/GopherJ/repro-build-script-not-found

**Possible Solution(s)**

**Notes**

Output of `cargo version`: cargo 1.35.0-nightly (6f3e9c367 2019-04-04)

**Comment by ehuss** [comment]
I'm not sure if I understand the repro correctly. There seems to be multiple issues:
- The repro steps say to run docker after `cd repro-build-script-not-found/server`, but the build script needs to access `../client` which won't exist from that directory.  Seems like it should be `cd repro-build-script-not-found`.
- `emk/rust-musl-builder` doesn't contain npm. The build script is just reporting that.

**Comment by GopherJ** [comment]
hello @ehuss, sorry my bad I used manifest-path parameter in my locla project but not on this repo.

Yes I think you are right, I forgot that maybe they don't have npm, but the error message is a little bit confusing because the error message is reporting that build-script fails to be compiled but actually it should be a runtime error
