### ISSUE TITLE
build pipelining fails

### ISSUE THREAD

**Issue by khuey** [rust-lang/cargo#6993]
**Problem**

When running `CARGO_BUILD_PIPELINING=true cargo build --all --tests` on my project, I get

```
error: crate `<foo>` required to be available in rlib format, but was not found in this form
```

Unfortunately this project is not open source, so I'm not sure what else to report.

**Notes**

Output of `cargo version`: cargo 1.37.0-nightly (545f35425 2019-05-23)

**Comment by nnethercote** [comment]
CC @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the report! Is it possible to share the project that generated this error?

**Comment by khuey** [comment]
Probably not. Is there a way to get debugging information out of cargo?

**Comment by alexcrichton** [comment]
If you're ok with it you can do a `CARGO_LOG=trace cargo build ...` and I can try to piece together what went wrong.

**Comment by khuey** [comment]
I can do that. The log is 67 MB. Can I email you a link to it?

**Comment by alexcrichton** [comment]
Sure!

**Comment by khuey** [comment]
Sent.

**Comment by alexcrichton** [comment]
Is this a build where `RUSTC_WRAPPER` is set in one way or another? The metadata file looks like it's getting produced at the exact same time as the output file which seems like there may be some caching somewhere. If so does this bug reproduce without the caching layer/wrapper?

**Comment by khuey** [comment]
We don't set that anywhere. I think the most interesting thing going on in our build is a linker script. We don't have anything like ccache involved.

**Comment by alexcrichton** [comment]
Ok thanks for the clarification, digging more I believe https://github.com/rust-lang/cargo/pull/7008 should at least fix one of the issues I saw (and was able to reproduce locally). Could you test that out and see if it fixes the issues you're seeing?

**Comment by khuey** [comment]
Unfortunately cargo master (and your PR) dies earlier with `error: Unrecognized option: 'json-rendered'` when `CARGO_BUILD_PIPELINING=true`, so I can't actually test it.

**Comment by alexcrichton** [comment]
To double check, you're doing the equivalent of `rustup run nightly /path/to/cargo/target/debug/cargo build`?

**Comment by khuey** [comment]
Apparently not!

That gets me farther, to `crate `rusoto_ec2` required to be available in rlib format, but was not found in this form` which is similar to but different from the original error.

**Comment by alexcrichton** [comment]
Can you send me the logs for that as well?

**Comment by khuey** [comment]
After I cleared out the existing target/ directory to get a log from scratch, I haven't been able to reproduce this with your branch.

So it appears that it is in fact fixed \o/

**Comment by brson** [comment]
Seen in tikv here https://github.com/tikv/tikv/issues/5130

**Comment by corygabrielsen** [comment]
I am repeatedly facing this issue with a large rust project which depends on `libp2p`

```
error: crate `ring` required to be available in rlib format, but was not found in this form
```

I have spent multiple dev-days trying to fix this. There is clearly still an issue.
