### ISSUE TITLE
Don't remove color information from rendered string in `--message-format=json` output

### ISSUE THREAD

**Issue by mchernyavsky** [rust-lang/cargo#6994]
**Describe the problem you are trying to solve**

I'm trying to support new build tool window for IntelliJ Rust:

![image](https://user-images.githubusercontent.com/6079006/58558071-8c8f1200-8228-11e9-90e0-82f8c744b831.png)

I use `--message-format=json` option, but unfortunately the rendered string doesn't contain color information.

**Describe the solution you'd like**

I would like to use `--color=always` option (or some new one) to include color information.

**Notes**
I think this is the place where it can be fixed:
https://github.com/rust-lang/cargo/blob/9be45944b14c51f5f2c2ed31d73bb1f7a7f1b4e9/src/cargo/core/compiler/mod.rs#L1222-L1238

**Comment by ehuss** [comment]
This is gated on https://github.com/rust-lang/rust/issues/60987

**Comment by mchernyavsky** [comment]
Thanks!
