### ISSUE TITLE
Use git source or local path, based on cfg?

### ISSUE THREAD

**Issue by SamuelMarks** [rust-lang/cargo#6997]
**Describe the problem you are trying to solve**
I go crazy on modularity. My teams have to handle this craziness. Repository explosions. During local development, we might be modifying 5+ dependencies. On our build servers—whether they be custom or aaS like Travis—we're happy to use `git` dependencies. But during local development, anything other than a `path =` wouldn't work.

**Describe the solution you'd like**
Support for this syntax may actually suffice:
```
[target.'cfg(debug_assertions)'.dependencies]
```

**Notes**
I do understand the risk of modifying multiple dependencies concurrently with automated build/test pipelines.

**Comment by ehuss** [comment]
Sorry, I don't really understand what this issue is for.  Can you restate the problem?  What are you trying to do?

**Comment by ehuss** [comment]
Closing as I haven't heard back.  Feel free to reopen if needed.
