### ISSUE TITLE
Can't run a minimal RUSTC_WRAPPER

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/cargo#7002]
**Problem**

I'm trying to write a simple RUSTC_WRAPPER, but I'm getting an obscure error.

My wrapper (should simply run the rustc):

```python
#!/usr/bin/env python3

import sys
import subprocess

args = ['/home/razr/.cargo/bin/rustc'] # force full path
args.extend(sys.argv[2:])
subprocess.run(args, check=True)

# args content:
# ['/home/razr/.cargo/bin/rustc', '-', '--crate-name', '___', '--print=file-names', '-Ctarget-cpu=native', '--crate-type', 'bin', '--crate-type', 'rlib', '--crate-type', 'dylib', '--crate-type', 'cdylib', '--crate-type', 'staticlib', '--crate-type', 'proc-macro']
```

```
> env RUSTC_WRAPPER='./wrap.py' cargo build -v
error: unexpected character in cfg `/`, expected parens, a comma, an identifier, or a string
```

Am I missing something? 

**Notes**

Output of `cargo version`: cargo 1.35.0 (6f3e9c367 2019-04-04)

Gentoo Linux, Rust installed via rustup.

**Comment by ehuss** [comment]
Can you post the contents of `target/.rustc_info.json` if it exists?  It's possible it cached invalid output from previous runs.  If that's the case, try deleting the file.

**Comment by RazrFalcon** [comment]
There are not `target` dir. It's a first/clean build.

**Comment by ehuss** [comment]
Hm, that's strange, your example works for me.

Can you log the output and post the results? Maybe something like this:

```python
#!/usr/bin/env python3

import sys
import subprocess

args = ['/home/razr/.cargo/bin/rustc'] # force full path
args.extend(sys.argv[2:])
open('wrap_output','a').write('%s\n' % (args,))
output = subprocess.run(args,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    check=True,
    encoding='utf8')
open('wrap_output','a').write('stdout:\n%s\nstderr:\n%s\n' % (output.stdout, output.stderr))
sys.stdout.write(output.stdout)
sys.stderr.write(output.stderr)
```

**Comment by RazrFalcon** [comment]
I fixed it by running `cargo clean`. I'm was sure that this is a clean build. Probably broke my config somehow.

Sorry for the trouble.

**Comment by RazrFalcon** [comment]
I've found the problem! You can't print some character via wrapper.

This code works:

```python
print('A')
subprocess.run(sys.argv[1:], check=True)
```

This not:

```python
print('[')
subprocess.run(sys.argv[1:], check=True)
```

Is this is an expected behavior?

**Comment by ehuss** [comment]
Wrappers generally should not print anything to stdout or stderr.  Cargo has certain expectations of the output of rustc.

**Comment by RazrFalcon** [comment]
I see. Thanks.
