### ISSUE TITLE
`cargo test` builds its own version of dependencies for integration tests

### ISSUE THREAD

**Issue by skletsun** [rust-lang/cargo#7005]
**Problem**
We've got a Rust project (dynamic library) which is a part of a more complex project. The Rust part is a workspace that consists of a library, app, and integration tests. Building and testing of rust part is a part of building and testing the whole project (maven). We've got (1) a "compile" phase, when we execute `cargo build` and our library gets built and put to the `target/debug` and the "test" phase when (2) non-Rust integration tests are executed against produced library and (3) Rust integration tests. The problem is that during (3) we execute `cargo test` that builds its own library version in the `target/debug/deps` and executes tests against it, which leads to a situation, when one part of integration tests are executed against one shared library and the rest of them - against another one.
If I get things right, the documentation for `cargo test` (https://doc.rust-lang.org/cargo/commands/cargo-test.html) states that integration tests and their dependencies should be built using `test` and `dev` profiles respectively. Thus, my expectation was that integration tests' binaries could reuse the library from step (1) (which obviously should be built using `dev` profile).
So my question is if the observed behavior of `cargo test` is expected? Any chance to link against the prebuilt library in the integration tests executed with `cargo test`?
Thanks in advance!

**Steps**
1. Create a workspace with two projects: (1) `lib` of type `dylib` and (2) `int_tests` for integration tests that depends on `lib`.
2. Execute `cargo build` and notice dynamic library artifact for `lib` in the `target/debug` and `target/debug/deps`.
3. Execute unit tests with `cargo test --all` and notice there is a new dynamic library artifact for `lib` in the `target/debug/deps` that overwrites the one produced at step (2) and which is used to link against during the execution of integration tests.

**Notes**

Output of `cargo version`: cargo 1.35.0 (6f3e9c367 2019-04-04).
The libraries are built with exact features. Tested this on OSX on latest stable 1.35.0.

**Comment by ehuss** [comment]
I'm not sure I understand the setup correctly. It should reuse the library unless certain profile settings are changed.  Can you upload a zip file containing a sample workspace?

**Comment by skletsun** [comment]
You are right - it does reuse the library. When I managed to reproduce this behavior with the sample workspace I noticed that it is reproduced only if I involve features into the library. And it turned out that `cargo build` and `cargo test` had a different set of features in the original project.
Now it's fixed. Thanks for your assistance and sorry for disturbance!
