### ISSUE TITLE
[workspace] Prereleases with path dependencies fail

### ISSUE THREAD

**Issue by dignifiedquire** [rust-lang/cargo#7007]
**Problem**

I am not certain this is a bug, but at least it is very surprising to me:

- Using workspaces with multiple crates `a` and `b`
- `b` depends on `a`, using `a = {version = "^0.1", path = "../a"}`
- All is fine, e.g `cargo test --all` works
- Bumping `a` to a prerelease of `0.1.1-alpha.0` triggers the following error

```
$ cargo test --all
error: no matching package named `a` found
location searched: /Users/dignifiedquire/opensource/cargo-workspace-prerelease/a
perhaps you meant: a
required by package `b v0.1.0 (/Users/dignifiedquire/opensource/cargo-workspace-prerelease/b)`
```

**Steps**

1. Clone https://github.com/dignifiedquire/cargo-workspace-prerelease-bug
2. Run `cargo test --all`

**Possible Solution(s)**

It would be great if it either worked, or at least the error message was more clear as to what the actual problem is.

**Notes**

Output of `cargo version`:

```
cargo version
cargo 1.36.0-nightly (c4fcfb725 2019-05-15)
```

**Comment by dignifiedquire** [comment]
Is there any selector that would work? Neither `*`, nor `~0.1`, nor `>=0.1` work.

**Comment by sfackler** [comment]
`0.1.1-alpha.0` will work.
