### ISSUE TITLE
Cargo test fails to find associated function in doc tests

### ISSUE THREAD

**Issue by wellcaffeinated** [rust-lang/cargo#7013]
**Problem**

I apologize if this turns out to be my misunderstanding of rust modules...but i don't think it is. 

I can successfully run the same test case using cfg(test), but it fails in the rust doc test.

I've created a module called crystals, which should re-export the struct BBO_1 defined in the submodule.
```rust
// in crystals/mod.rs
//! Defines types of crystals used in spdc.

pub mod meta;
pub use self::meta::*;

trait Crystal {
  /// Constant holding the meta information for this crystal
  const META: meta::CrystalMeta;
  /// Get the refractive indicies for the crystal
  fn get_indicies( wavelength :f64, temperature :f64 ) -> Indicies;
}

// re-exports of predefined crystals
mod bbo_1;
pub use bbo_1::BBO_1;
```

I have a submodule i want to re-export:
```rust
// in crystals/bbo_1.rs
//! # BBO1 Crystal
//!
//! [More Information](http://www.newlightphotonics.com/v1/bbo-properties.html)

use super::*;

// from Newlight Photonics
const DNO :f64 = -9.3e-6;
const DNE :f64 = -16.6e-6;

#[allow(non_camel_case_types)]
pub struct BBO_1;
impl Crystal for BBO_1 {
  /// Meta information for the crystal
  ///
  /// ## Example
  /// ```
  /// use spdcalc::crystals::{BBO_1};
  /// let name = &BBO_1::META.name;
  /// assert_eq!(name, 'BBO ref 1');
  /// ```
  const META: CrystalMeta = CrystalMeta {
    name: "BBO ref 1",
    reference_url: "http://www.newlightphotonics.com/bbo-properties.html",
    axis_type: OpticAxisType::NegativeUniaxial,
    point_group: PointGroup::HM_3m,
    temperature_dependence_known: true,
  };

  /// Get refractive Indicies
  ///
  /// ## Example
  /// ```
  /// use spdcalc::crystals::{BBO_1, Indicies};
  /// let nm = 1e-9;
  /// let indicies = BBO_1::get_indicies( 720.0 * nm, 293.0 );
  /// let expected = Indicies(1.6607191519167868, 1.6607191519167868, 1.5420245834707935);
  /// assert_eq!(indicies, expected);
  /// ```
  #[allow(clippy::unreadable_literal)]
  fn get_indicies(wavelength: f64, temperature: f64) -> Indicies {
    let lambda_sq = (wavelength * 1.0e6).powi(2); // Convert for Sellmeir Coefficients

    let mut no = (2.7359 + 0.01878 / (lambda_sq - 0.01822) - 0.01354 * lambda_sq).sqrt();
    let mut ne = (2.3753 + 0.01224 / (lambda_sq - 0.01667) - 0.01516 * lambda_sq).sqrt();

    no += (temperature - 20.0) * DNO;
    ne += (temperature - 20.0) * DNE;

    Indicies(no, no, ne)
  }
}

#[cfg(test)]
mod tests {
    // Note this useful idiom: importing names from outer (for mod tests) scope.
    use super::*;

    #[test]
    fn test() {
      let nm = 1e-9;
      let indicies = BBO_1::get_indicies( 720.0 * nm, 293.0 );
      let expected = Indicies(1.6607191519167868, 1.6607191519167868, 1.5420245834707935);
      assert_eq!(indicies, expected);
    }
}
```

Cargo test gives this:

```
   Compiling spdcalc v0.1.0 (/Users/jep5/Documents/github/nist/spdcalc/spdcalc)
    Finished dev [unoptimized + debuginfo] target(s) in 1.67s
     Running /Users/jep5/Documents/github/nist/spdcalc/target/debug/deps/spdcalc-e3584d870d522872

running 1 test
test crystals::bbo_1::tests::test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests spdcalc

running 2 tests
test src/crystals/bbo_1.rs - crystals::bbo_1::BBO_1::META (line 17) ... FAILED
test src/crystals/bbo_1.rs - crystals::bbo_1::BBO_1::get_indicies (line 33) ... FAILED

failures:

---- src/crystals/bbo_1.rs - crystals::bbo_1::BBO_1::get_indicies (line 33) stdout ----
error[E0599]: no function or associated item named `get_indicies` found for type `spdcalc::crystals::BBO_1` in the current scope
 --> src/crystals/bbo_1.rs:36:23
  |
6 | let indicies = BBO_1::get_indicies( 720.0 * nm, 293.0 );
  |                       ^^^^^^^^^^^^ function or associated item not found in `spdcalc::crystals::BBO_1`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
thread 'src/crystals/bbo_1.rs - crystals::bbo_1::BBO_1::get_indicies (line 33)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    src/crystals/bbo_1.rs - crystals::bbo_1::BBO_1::META (line 17)
    src/crystals/bbo_1.rs - crystals::bbo_1::BBO_1::get_indicies (line 33)

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'
```

**Notes**

Output of `cargo version`:

 cargo 1.35.0 (6f3e9c367 2019-04-04)

**Comment by ehuss** [comment]
In the doc example I think you need to also import your `Crystal` trait.  Traits need to be imported to be accessible (`use spdcalc::crystals::Crystal;`).  Each doc test lives in its own little world.

**Comment by wellcaffeinated** [comment]
Thanks for responding!
I'm confused... i'm not using the `Crystal` directly in the test case. Why would i need to import it? Isn't it getting imported already in the bbo_1.rs module?

**Comment by ehuss** [comment]
The `CrystalMeta` example is using `&BBO_1::META`. The `META` associated value only exists on the `Crystal` trait.  Same story for the other example, where `get_indicies` only exists on the `Crystal` trait.  Without importing the trait, it essentially doesn't exist.  Doctests don't implicitly import anything from the surrounding scope (other than the crate itself as an `extern crate`).

**Comment by wellcaffeinated** [comment]
so even though in this same file it implements Crystal as part of the definition it's not imported by the doc test? Is there a reference for how doc tests import things? it seems different from everything else. I'm very confused

**Comment by ehuss** [comment]
Here is the specification for how doctests work: https://doc.rust-lang.org/rustdoc/documentation-tests.html#pre-processing-examples

It's essentially creating a new, separate executable for each code block.

**Comment by wellcaffeinated** [comment]
Sorry, I'm still confused after reading the docs.
I'm still importing the `bbo_1` module through the `crystals` module with
```
use spdcalc::crystals::{BBO_1};
```

Why doesn't that work? If `BBO_1` gets accessed (which it does. the compiler doesn't complain about missing `BBO_1`), then why would `Crystal` need to be imported since the definition of BBO_1 is in the same file as the `impl Crystal for...`?

**Comment by wellcaffeinated** [comment]
After doing some tests I finally realized two things:
1. the trait `Crystal` wasn't public
2. the trait needs to be in scope in order to use the methods implemented on it (as you said)

It's related to this: https://github.com/rust-lang/book/issues/1018

Number 2 doesn't make sense to me. IMO i expect that if i define a struct and then implement a public trait in the same file it should "attach" to that struct. I guess that's not how it works, but seems to me like that's more error prone as a library writer, since I want people who use my library to be able to use the trait methods I implement on structs without explicitly knowing about the traits themselves.

I'd expect to be able to do something like
```
pub(crate) impl MyTrait for MyStruct {
  // ...
}
```
or something similar, in order to bring that implementation into scope by default when `MyStruct` is in scope. 

Anyways, this isn't a bug. But as a newcomer it didn't seem well documented, and the error message wasn't as descriptive as the rest of the messages I've come across.

In any case, I appreciate the help!

**Comment by ehuss** [comment]
Yea, I think it will usually have a hint to import the trait, but since it was private, it couldn't do that.

For future questions, I suggest one of the forums like [urlo](https://users.rust-lang.org/) or one of the chat channels.  This issue tracker is generally for cargo-specific issues, although I sympathize it's not always obvious to know where things should go.
