### ISSUE TITLE
cargo check fails, cargo build fails, cargo build --release works

### ISSUE THREAD

**Issue by uggwar** [rust-lang/cargo#7015]
**Problem**

cargo check on a project using serde fails the final linking, with a rather huge amount of undefine references. The same goes for debug build, but release works as expected.

**Steps**

1. cargo build
2. Output with error messages attached

**Possible Solution(s)**

Build with --release creates a working binary, but is slow and doesn't work as well with 'cargo watch -c' (my workflow...)

cargo +nightly check
cargo 1.37.0-nightly (545f35425 2019-05-23)

**Notes**

cargo 1.35.0 (6f3e9c367 2019-04-04)
rustc 1.35.0 (3c235d560 2019-05-20)
stable-x86_64-unknown-linux-gnu (default)
Debian GNU/Linux 10 testing amd64

[cargo_check_serde_output.txt](https://github.com/rust-lang/cargo/files/3260797/cargo_check_serde_output.txt)

**Comment by ehuss** [comment]
Can you post a project or Cargo.toml that reproduces the problem?

**Comment by uggwar** [comment]
[lompe.tar.gz](https://github.com/rust-lang/cargo/files/3265022/lompe.tar.gz)

**Comment by ehuss** [comment]
Hm, I can't seem to find a way to reproduce it.  Have you tried running `cargo clean`?

**Comment by uggwar** [comment]
Yes, sure. Same error in the project I posted earlier.

**Comment by ehuss** [comment]
Sorry, I'm not able to reproduce your issue, and I don't really see any clues which could explain it.  You might get more help on one of the forums like [URLO](https://users.rust-lang.org/).

**Comment by ehuss** [comment]
Oh, another thing you might try is disabling incremental compilation to see if that is the culprit.  Set the environment variable `CARGO_INCREMENTAL=0`.  There are a number of people reporting similar issues with undefined symbols related to incremental.

**Comment by uggwar** [comment]
CARGO_INCREMENTAL=0 builds correctly! Thanks! Should I report this somewhere maybe?

**Comment by Eh2406** [comment]
Move to close?

**Comment by ehuss** [comment]
Yep, hopefully the compiler team can wrangle it.  People may follow https://github.com/rust-lang/rust/issues/59535 for updates.
