### ISSUE TITLE
cargo new without initializing a git repository

### ISSUE THREAD

**Issue by catastrop** [rust-lang/cargo#7016]
How can i run 
``` sh
cargo new name
```
without initializing a Git repository.

And can use other version control system?

**Comment by k-nasa** [comment]
@catastrop strop ```cargo new``` has [vcs option](https://doc.rust-lang.org/cargo/commands/cargo-new.html).
Is this what you are looking for?
```
cargo new --vcs hg name
```

**Comment by catastrop** [comment]
```sh
#no vcs
cargo new --vcs none name 

cargo new --vcs [ vsc name ] name 

```
