### ISSUE TITLE
Cargo clean: Provide an option to only clean debug artifacts

### ISSUE THREAD

**Issue by heidezomp** [rust-lang/cargo#7021]
**Describe the problem you are trying to solve**

Using `cargo clean` it is currently impossible to only clean the debug artifacts, while keeping the release and documentation artifacts intact. A use case for this is the cargo subcommand `cargo-bloat`'s use of `cargo clean` for removing artifacts before timing a build, as described in RazrFalcon/cargo-bloat#33.

**Describe the solution you'd like**

I propose a flag `cargo clean --debug` to only clean debug artifacts, similar to how `cargo clean --release` only cleans release artifacts. This doesn't seem too hard to implement for me, so if this is accepted, I'd like to try and implement this myself if that is okay :smile:

**Notes**

The phrasing for the `--release` flag in the help output is confusing to me. It says "Whether or not to clean release artifacts". To me this suggests that if you _don't_ supply the `--release` flag, the release artifacts are _not_ cleaned, which is not the case. I had to test out the behavior to see that not providing `--release` in fact removes the entire target directory. To me the phrasing "Clean only release artifacts" would be much clearer. The same goes for the `--doc` help output.

**Comment by ehuss** [comment]
As part of named profiles (#6989), `cargo clean` will gain a `--profile` flag to clean just a specific profile.  `--release` will be an alias for `--profile=release`, and you can specify any profile.

The documentation for the `clean` command could definitely use some improvement.  It's a little tricky since there are a number of problems with how `clean` works.

**Comment by heidezomp** [comment]
Oh, that looks super useful! :smile: 

Should I close this report in favor of #6988 then, or wait until it has been merged or stabilized?

**Comment by ehuss** [comment]
I'll close this now.  You can subscribe to #6988 to get notified of any changes, or when it gets stabilized.
