### ISSUE TITLE
`cargo fmt -- --help` displays no output

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#7027]
**Problem**

I ran `cargo fmt -- --help` and didn't get any output. I expected to get the same output that I *do* get when I run `rustfmt --help`, especially because the last line in `cargo fmt --help` says ``Arguments after `--` are passed to rustfmt.``

The weirdest part is if I run `cargo fmt -- --help=config`, I *do* get the same output as I get if I run `rustfmt --help=config`, the configuration specific help. So cargo is passing through `--help` when it has an argument? And not passing it through when there isn't? I haven't investigated the cause at all, I'm just guessing based on the symptoms.

**Steps**

1. Be on stable Rust with the `rustfmt` component installed.
2. Run `cargo fmt -- --help`.
3. Observe that there is no output.
4. Observe the expected output by running `rustfmt --help`.

**Notes**

Output of `cargo version`: cargo 1.35.0 (6f3e9c367 2019-04-04)
Output of `rustfmt --version`: rustfmt 1.2.0-stable (09940a70 2019-03-27)
OS: macOS Mojave

**Comment by ehuss** [comment]
This is a bug in rustfmt.  I posted a fix at rust-lang/rustfmt#3620.

**Comment by ehuss** [comment]
This is now fixed on nightly via https://github.com/rust-lang/rustfmt/pull/3620 and https://github.com/rust-lang/rust/pull/62688.
