### ISSUE TITLE
Add beta/alpha attributes

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/cargo#7028]
**Describe the problem you are trying to solve**

While building public API, I would like to have `beta`/`alpha` attributes to use. Currently the only option is `deprecated = "beta"`. But `deprecated` should not be used in this context, because it obviously has other meaning than `beta`/`alpha`. For example:

- Version `1.0` introduces new struct A with `deprecated = "beta"`.
- Version `1.1` still keeps struct A, but with `deprecated = "alpha"`. This, in my opinion, looks weird, since a deprecated item was... promoted from "beta" to... "alpha".

**Describe the solution you'd like**

`beta` and `alpha` should have notes, like `deprecated`.

Thank you,

**Comment by ehuss** [comment]
I don't fully understand the request here.  I'm guessing you want some kind of warning emitted if an alpha/beta annotated type is used?  I can't think of a way to do that other than `deprecated`.  

The typical way this is handled is to make alpha/beta releases (like `1.0.0-beta`).  Cargo won't select versions with pre-release identifiers unless it is explicitly selected (like `somepackage = "1.0.0-beta"`).

New attributes would need to go through the RFC process, which would likely start with a discussion on [irlo](https://internals.rust-lang.org/).  

As this is unrelated to cargo, I'm going to close this.
