### ISSUE TITLE
Unable to compile cargo master

### ISSUE THREAD

**Issue by leopck** [rust-lang/cargo#7043]
**Problem**

Unable to compile the cargo master
```
error: internal compiler error: src/librustc/ty/subst.rs:480: Type parameter `T/#1` (T/1) out of range when substituting (root type=Some(T)) substs=[T]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:526:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `sized-chunks`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Steps**

1. git clone https://github.com/rust-lang/cargo
2. cd cargo
3. cargo build --release

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
```
cargo version
cargo 1.33.0 (f099fe94b 2019-02-12)
```

**Comment by ehuss** [comment]
> cargo 1.33.0 (f099fe94b 2019-02-12)

Can you try with a more recent version of rust?  Cargo generally only supports current stable (which is 1.35 right now).

**Comment by matthiaskrgr** [comment]
Looks like https://github.com/rust-lang/rust-clippy/issues/4121

**Comment by ehuss** [comment]
Oh, haha, I even filed that, I forgot!

Yea, I can repro that it is an issue with 1.33, and that a newer version should work.  Considering that this specific case has been fixed in newer versions of rust (by https://github.com/rust-lang/rust/pull/57606 I believe), I'm going to close this.

**Comment by leopck** [comment]
Alright thanks!
