### ISSUE TITLE
git global settings (name, email) are private, do not read or use

### ISSUE THREAD

**Issue by Meai1** [rust-lang/cargo#7044]
I am using my real name and private email for my own repos that will never go public. Why should cargo read this information? I do not consent!
If I were to accidentally leave that information and publish it, it would be pretty bad. I would have to get a new email and who knows what else can be compromised. I dont want to get into it, but the entire point of this issue is that it's none of your business what my name and email is unless I want to share it.

**Comment by ehuss** [comment]
You may set the global `[cargo-new]` config settings to whichever value you want (described on the [init](https://doc.rust-lang.org/nightly/cargo/commands/cargo-init.html) page), or the CARGO_NAME/CARGO_EMAIL environment variables. Or you can just edit the Cargo.toml file after creating it, or create it manually.

**Comment by substack** [comment]
This should be re-opened. Cargo is violating consent by scraping personal information from the environment without asking. The fact that you can opt-out by setting `cargo-new.name` and `cargo-new.email` doesn't change the fact that this is a violation of privacy and consent.

**Comment by ehuss** [comment]
@substack It is being removed in #9282.
