### ISSUE TITLE
distcc master slave rpc capabilities integrated within cargo and call it distcc_cargo/distcc_rustc

### ISSUE THREAD

**Issue by omac777** [rust-lang/cargo#7046]
**Describe the problem you are trying to solve**

Cargo elegantly compiles different .rs files in parallel and different crates in parallel using all the local computer resources at its disposal.

Distcc compiles different c/c++ .c/.cc/.cpp files in parallel not only using all the local computer resources at its disposal, but also using other LAN/WAN computers configured with distcc.

My feature request is to see cargo extend its capabilities to include being being distcc-aware and when requested, that cargo connect to a list of network distcc nodes and to also delegate some rustc tasks those network distcc nodes and then return its results to be shuffled as if it was built locally.  There should continue to be some rustc tasks delegated to the local computer resources, but rather than having all the rustc tasks being done locally, the point is when you're building a large project with many .rs files that take up 4 hours+ to build on one computer, it would be advantageous to spread all those rustc tasks around to other computers also and then gather the results back to the node that invoked the master cargo build request in the first place.

**Describe the solution you'd like**

integrated distcc client/server within cargo itself. support all distcc, but also support rustc and possibly full cargo itself as a slave cargo requested by the master cargo.  Would just supporting rustc be sufficient?

what would we call such a tool?
distcc_cargo
distcc_rustc

Could the master cargo call some slave cargo distcc nodes and run a full cargo there, but just to build object files and return them back to the master cargo?
If that was possible, then distcc_cargo would be the best name for it, since it would be fully compatible with distcc and cargo aware.
It would be like building a cargo with grpc client/server within it to do stuff like this.

Thank you for listening.
**Notes**

**Comment by alexcrichton** [comment]
Thanks for the report! This is definitely a huge feature request and one we're unlikely to add to native Cargo. I'd recommend looking into [sccache](https://github.com/mozilla/sccache) which should have support for many of the features I think you'd like here.
