### ISSUE TITLE
Support checksum in git sources

### ISSUE THREAD

**Issue by nmattia** [rust-lang/cargo#7059]
**Describe the problem you are trying to solve**

I’m trying to have reproducible cargo builds through the [nix] package manager. Nix does not provide network access during builds which means that cargo is not allowed to fetch crates for crates.io.

My current solution is to parse the Cargo.lock using Nix, read all the URLs and checksums and tell nix (1) where to get any particular crate from and (2) what checksum to expect. After that I specify a source replacement in the cargo config which instructs cargo to use a the directory where nix unpacked all the crates as repository.

This works well enough for sources with kind “registry” (`registry+...`). However “git” sources (`git+...`) [do _not_ specify a checksum](https://github.com/rust-lang/cargo/blob/973356143c6b16c8536f84b8fce8cf43ccf48c74/src/cargo/sources/git/source.rs#L144) which is a problem for Nix (there are some workarounds to using git repositories without checksums in Nix but unfortunately they are inconvenient and do not support submodules).

**Describe the solution you'd like**

If we can figure out a canonical way to compute checksums for git repositories (and submodules) I’m happy to contribute the feature to cargo.

**Notes**

current implementation of the Nix builds: [nmattia/naersk](https://github.com/nmattia/naersk/blob/master/default.nix)

[nix]: https://nixos.org/nix/

**Comment by est31** [comment]
@nmattia are you aware that cargo puts [git commit hashes](https://github.com/servo/servo/blob/1d2c0ba0bc71e34495accde61f58443f0f18c28c/Cargo.lock#L5235) into the package section?

**Comment by nmattia** [comment]
@est31 thanks for the pointer; unfortunately nix needs an actual checksum, or a hash of the content. The commit hash alone won't do.

**Comment by est31** [comment]
@nmattia why? git takes a hash of the content as part of the information used to build the commit hash.

**Comment by leo60228** [comment]
@est31 Nix can only run non-Nix code with access to the network if it is a "fixed-output derivation." Fixed-output derivations require a hash of the filesystem output of the command to be included. The raw data included in the Git SHA-1 cannot be transformed into a hash of the full filesystem as of that commit.

**Comment by leo60228** [comment]
As an example of this, let's look at a repository with 3 files. To simplify this, each commit has either 1 or 0 parents, and the only thing a commit can do is add a single file.
Commit A (`4438c472f49f59192b8fd8c330b44ff5a9356b23`):
```
(root)
file1:
a
```
Commit B (`8b75ab7da6960f4fff84f7ff637cebb3c4600efd`):
```
4438c472f49f59192b8fd8c330b44ff5a9356b23
file2:
b
```
Commit C (`278131ae3bc3d250a6299eabfb96a2bf1cd7d99f`):
```
8b75ab7da6960f4fff84f7ff637cebb3c4600efd
file3:
c
```
The resulting filesystem is:
```
file1: a
file2: b
file3: c
```
The hash `278131ae3bc3d250a6299eabfb96a2bf1cd7d99f` allows verifying `file3`, and partially allows verifying `file2`. However, the singular hash `278131ae3bc3d250a6299eabfb96a2bf1cd7d99f` does *not* allow verifying `file1` in any way! The hash `4438c472f49f59192b8fd8c330b44ff5a9356b23` is required for this.

**Comment by leo60228** [comment]
Git supports two different http protocols. I believe both of them, *in theory* could be implemented in pure Nix, solving this issue. However, this would both be very inefficient, and the only protocol supported by GitHub has very little documentation.

**Comment by leo60228** [comment]
Hm, it doesn't seem possible to implement the smart protocol (the only one GitHub supports) in Nix *remotely* efficiently. You're only allowed to download the latest *n* commits from a branch or tag, not a specific *n*th commit. Since every commit has to be downloaded individually for Nix to know the hash of the next commit, this would be *very* inefficient...

**Comment by leo60228** [comment]
Hm, though the fact that this is *theoretically* possible implies that `builtins.fetchGit` shouldn't require a hash.

**Comment by leo60228** [comment]
Oh, it already doesn't...

**Comment by est31** [comment]
@leo60228

> the singular hash 278131ae3bc3d250a6299eabfb96a2bf1cd7d99f does not allow verifying file1 in any way! The hash 4438c472f49f59192b8fd8c330b44ff5a9356b23 is required for this.

Git commits don't work like you imagine. Each commit includes a full hash of the *entire* tracked tree. This means that you can verify every single file from that tree using that hash. Furthermore, git ships with sha1 collision detection mitigations enabled, which protect from known practical collision attacks.

You can read more about how git hashes work in [this](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects) link.

**Comment by tadfisher** [comment]
Nix doesn't know or care about Git; it computes its own hash over the result of unpacking a tree into the Nix store. Essentially a Nix build is a function of inputs -> outputs, where all inputs are rooted by fixed-output derivations with known content hashes.

So even if you *could* verify a tree given a commit hash, there is no mechanism in Nix to do so. Its method of hashing a file tree is to hash the "NAR archive" of the tree, which is Nix-specific and wouldn't make sense to support directly in cargo. A tool wishing to generate fixed-output derivations given only Git sources must therefore fetch and generate those hashes itself.

@nmattia Make sense?

**Comment by nmattia** [comment]
Hi @tadfisher,

Yes that's true, it's quite a long shot to think about implementing the NAR stuff in cargo, but if there was one agreed upon way of hashing source trees we could support this in Nix and kill many birds with one stone!

**Comment by jD91mZM2** [comment]
Is this fixed by [your naersk commit](https://github.com/nmattia/naersk/commit/47b22494d94d7548234b3ab241a38c68bd2b0233) which uses `builtins.fetchGit` (which doesn't require a checksum because git revisions already do that)?

**Comment by nmattia** [comment]
Oh I guess it is. Thanks @jD91mZM2 !
