### ISSUE TITLE
cannot "cargo build -p <pkgid>" with virtual manifest

### ISSUE THREAD

**Issue by nmattia** [rust-lang/cargo#7073]
**Problem**

When running `cargo build -p <pkgid>` in a workspace where `<pkgid>` is not a workspace member, cargo fails even if the package is present in the `Cargo.lock`:

```
$ cargo build -p ansi_term
error: package ID specification `ansi_term` matched no packages
$ cat Cargo.lock | grep ansi_term
name = "ansi_term"
 "ansi_term 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)",
"checksum ansi_term 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = "ee49baf6cb617b853aa8d93bf420db2383fab46d314482ca2803b40d5fde979b"
```

The same thing happens if I `cd` into a member which doesn't have `<pkgid>` as a (transitive) dependency. This however works if I first `cd` into a member which _has_ `<pkgid>` as a (transitive) dependency.

```
$ cd some-member/
$ cargo build -p ansi_term
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
```

**Notes**

Maybe this is totally expected and my mental model is wrong. However since all builds end up in the `target/` at the top-level directory of the workspace, I assumed I could build the dependencies from anywhere.

Output of `cargo version`:

```
$ cargo version
cargo 1.35.0 (6f3e9c367 2019-04-04)
```

**Comment by schomatis** [comment]
Hi @nmattia, I went through a similar issue, what I've learned (and consider this just an incomplete/incorrect answer until someone from the Cargo team can add more information) is that `--package` isn't an arbitrary package selection option (that Cargo could eventually resolve from the `Cargo.toml` file) but rather a "whitelist filter" applied to the dependency graph of the workspace being worked on (the current directory if `--manifest-path` isn't specified), analogous to the `--exclude` option that could be seen as the blacklist filter for the same workspace.

In general I think Cargo only sees what's in `Cargo.toml` (independent of the directory structure) and will resort to `Cargo.lock` only for dependency resolution (of packages already discovered through `Cargo.toml`).

(cc'ing @Eh2406 as this might be an opportunity for some minor documentation improvement)

**Comment by ehuss** [comment]
Yea, I don't think this can be done in the general case.  For example, the set of features enabled for dependencies depends on which members are being built.  You can pass `--manifest-path` with the path to a workspace member to give cargo some context so it knows which dependency to build.

**Comment by nmattia** [comment]
That actually makes a lot of sense! Thanks for the info.
