### ISSUE TITLE
Automatic dependency management

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/cargo#7086]
**Describe the problem you are trying to solve**

Dependency management helpers like `cargo-edit` are great, but I think the process could be more streamlined.

**Describe the solution you'd like**

When I try to compile a program with `use some_crate` and if `some_crate` is not already in my `Cargo.toml` file, instead of cargo throwing an `unresolved import` error, it would instead display a prompt asking if I want to install `some_crate` from crates.io.

It would also offer a preview of some data about the crate so that users can easily confirm that is the correct crate they want to install.

If I confirm, cargo would add it to my `Cargo.toml` file. If not, it would exit and not install anything.

**Comment by ehuss** [comment]
Thanks for the suggestion!  I don't think we'd like to add interactive prompts to the normal build process, though.  This is likely something that would be better suited for an IDE like rust-analyzer, RLS, or IntelliJ.  It might be helpful to follow up with one of those projects.
