### ISSUE TITLE
How do I download a yanked crate (through a library API)?

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#7087]
**Describe the problem you are trying to solve**

For `cargo-crev`, I need to download a source a yanked crate (sometimes arbitrary, and not in `Cargo.lock`) to calculate the digest and some other things. I'm trying to figure out how to do that exactly. The reason is - I'm trying to allow the user to report a vulnerability in it (which might be the reason why it was yanked). 

**Describe the solution you'd like**
Some `allow_yanked: bool` field on `cargo::util::config::Config` maybe?

**Notes**
I've seen some PRs that were rejected to enable behavior like this.

**Comment by ehuss** [comment]
I'm not sure I understand the question, it is very broad.  There are a variety of ways to download packages directly. For example, either the `PackageSet` or `Source` APIs offer ways to download individual packages.

```rust
    let src_id = cargo::core::SourceId::crates_io(&config)?;
    let pkg_id = cargo::core::PackageId::new("bitflags", "1.0.5", src_id)?;
    let mut source = src_id.load(&config, &HashSet::new())?;
    let pkg = Box::new(&mut source).download_now(pkg_id, &config)?;
```

Or you can construct direct URLs to the registry using the url template and download using any http library.

**Comment by dpc** [comment]
I might be wrong but that's what I'm doing:

https://github.com/dpc/crev/blob/3312163f0d7d77c1a979d8ff516c05ef31a1e6b0/cargo-crev/src/main.rs#L173

the problem is - I think `cargo` wants me to have this version in `Cargo.lock` to allow me to download it (as it's yanked). But I don't and can't. And I'd like to avoid having to bring new machinery for something that is just a corner case.

**Comment by ehuss** [comment]
It looks like you are using a `PackagetSet` created by the resolver. It is pre-populated with unyanked crates, so it won't have the yanked `PackageId`s.  The example above I created the PackageId manually.

I don't think it is possible to forcefully resolve the graph with yanked crates if you don't ahead of time know which crates are yanked.  I don't have enough context of what you are trying to do to offer any suggestions.

**Comment by dpc** [comment]
That might do it. I'll try. Thank you!
