### ISSUE TITLE
Give path to executables in tests

### ISSUE THREAD

**Issue by nmattia** [rust-lang/cargo#7108]
**Describe the problem you are trying to solve**

I'm trying to run some of my crate's executables in a test. Currently I have to
1. Figure out the relative path to `target` (that path changes depending on whether this is a single crate project (`./target`) or if the crate is being built as part of a workspace (`../target`)).
1. Figure out whether this is a `release` or `debug` build by comparing the modification times of the executable.

**Describe the solution you'd like**

I would like environment variables that tell me 
1. The full path to where the executables are located.
1. (optionally) Whether this is a debug or release build.

**Notes**

`cargo` makes sure that the executables are built before the tests are run, so I believe this doesn't go against cargo best-practices to use freshly-built executables in test, but I'm happy to reconsider.

**Comment by ehuss** [comment]
Thanks for the report!  Issue #5758 is already tracking this, so I'm going to close in favor of that.  I'm working on a solution, so hopefully will have something soonish.
