### ISSUE TITLE
cargo vendor lacks compiler_builtins

### ISSUE THREAD

**Issue by WildCryptoFox** [rust-lang/cargo#7111]
**Problem**

Previously reported: https://github.com/alexcrichton/cargo-vendor/issues/177

`cargo vendor`'s output /vendor/ omits `compiler_builtins`, which doesn't mix well with custom targets using xargo and/or cargo-xbuild.

**Steps**

1. use a custom target
2. use xargo/xbuild
3. use cargo vendor
4. attempt to build anything with the /vendor/ enabled

**Possible Solution(s)**

Include compiler_builtins.

**Comment by ehuss** [comment]
I'm going to close this, as Cargo doesn't know anything about xargo/xbuild.  The intended path forward is the [build-std](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std) feature, and supporting vendoring is tracked in https://github.com/rust-lang/wg-cargo-std-aware/issues/23.
