### ISSUE TITLE
Cargo builds duplicate copies of dependencies

### ISSUE THREAD

**Issue by neachdainn** [rust-lang/cargo#7112]
**Problem**

It is possible for Cargo to build duplicate copies of dependencies that are common among workspace members. This is particularly painful when one of the common dependencies takes a while to compile.

**Example**

[This Zip file](https://github.com/rust-lang/cargo/files/3374714/duplicate.zip) contains an example workspace with this problem. The `nalgebra` dependency is only built once when running `cargo build` but it is built twice if each component is built separately. An example script is included in the Zip file to demonstrate this (`test.sh`).

The compile time of `cargo build` is ~51s on my machine while the component-wise build is ~1m25s. Some overhead is to be expected, but not that much.

**Notes**

I am personally building the workspace this way as Cargo has been integrated into the Catkin build system. This issue increases my personal build time from ~6m20s to ~11m7s.

Output of `cargo version`: cargo 1.32.0

**Comment by ehuss** [comment]
Thanks for the report.  This is a known problem where the features enabled depend on which packages you select.  #4463 is probably the most similar to this situation.  In your example, you'll just need to make sure every package enables the same set of features.  Or, if possible, you can create an empty package that all other packages depend on to have one place to define the features. This is how rust itself handles it, see [rustc-workspace-hack](https://github.com/rust-lang/rust/tree/master/src/tools/rustc-workspace-hack), though that is obviously not a good solution.

**Comment by neachdainn** [comment]
Sounds good. Thank you!
