### ISSUE TITLE
SIGSEGV while verifying crate to publish

### ISSUE THREAD

**Issue by 8573** [rust-lang/cargo#7141]
**Problem**
I run `cargo publish` to try to publish a crate. Rather than publishing the crate, Cargo fails with the following error message:

```
   Packaging c74d-test-20190717-01 v0.1.0 (/home/c74d/proj/own/rust/c74d-test-20190717-01)
   Verifying c74d-test-20190717-01 v0.1.0 (/home/c74d/proj/own/rust/c74d-test-20190717-01)
error: failed to verify package tarball

Caused by:
  process didn't exit successfully: `rustc -vV` (signal: 11, SIGSEGV: invalid memory reference)
--- stdout
rustc 1.34.2 (6c2484dc3 2019-05-13)
binary: rustc
commit-hash: 6c2484dc3c532c052f159264e970278d8b77cdc9
commit-date: 2019-05-13
host: x86_64-unknown-linux-gnu
release: 1.34.2
```

This happens even with a new crate just created with `cargo new`.

**Steps**
1. Try to publish a crate.

**Notes**

Output of `cargo version`: `cargo 1.34.0 (6789d8a0a 2019-04-01)`

I'm using NixOS, which is a weird Linux distribution, although one that seemingly once enjoyed popularity in a certain segment of the Rust community.

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like this is a local configuration issue, however, since it's `rustc -vV` that's segfaulting (as the error message says)

**Comment by 8573** [comment]
Does that mean that I should file against @rust-lang/rust instead, or that it's not the Rust team's problem?

**Comment by alexcrichton** [comment]
This is unlikely to be an issue with the Rust compiler itself, so I'd recommend posting to the users.rust-lang.org forum if you'd like assistance in debugging this.
