### ISSUE TITLE
Should a version indicator be encoded into `Cargo.lock`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#7144]
The `Cargo.lock` format is changing over time (and is practically guaranteed to continue changing) and the [most recent change](https://github.com/rust-lang/cargo/pull/7070) has brought up ideas again about possibly encoding a version number into `Cargo.lock`. There's a number of comments on that thread weighing some pros and cons (including [this one](https://github.com/rust-lang/cargo/pull/7070#issuecomment-511011808)).

One possible way to implement this would be to add a field to the `[metadata]` table. Every version of Cargo ever preserves the `[metadata]` table, and so we can add a version number in there practically any time and have it preserved by older Cargo while recognized by newer Cargo.

**Comment by mathstuf** [comment]
An alternative would be to add flags to newer compilers to write out old formats as well.

**Comment by est31** [comment]
PR #8522 has been opened to add such version numbers.

**Comment by epage** [comment]
At this point we are on version 3 of lock files.  Any reason to not close this issue?

**Comment by est31** [comment]
Yeah #8522 has added that number as 3. The issue can be closed.
