### ISSUE TITLE
Add "cargo new --proc-macro"

### ISSUE THREAD

**Issue by CreepySkeleton** [rust-lang/cargo#7155]
**Describe the problem you are trying to solve**
Allow people to make a new proc-macro in one command.

**Describe the solution you'd like**
Extend `cargo new` subcommand with `--proc-macro` flag. It should behave similarly to `cargo new --lib` except that `Cargo.toml` contains this:
```rust
[package]
name = "package_name"
version = "0.1.0"
authors = ["Author <mail@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```
and `src/lib.rs` file should contain something like this:

```rust
extern crate proc_macro;

#[proc_macro]
pub fn hello(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    unreachable!()
}
```

**Notes**

Probably we should also add `--proc-macro-attr` and `--proc-macro-derive` flags, they affect the default contains of `Cargo.toml`

**Comment by CreepySkeleton** [comment]
A could actually sign up on implementing this if you guys approve this change

**Comment by ehuss** [comment]
Thanks for the suggestion!  I don't think at this time we want to extend `cargo new` to create different project types. You may be interested in something like [cargo-generate](https://github.com/ashleygwilliams/cargo-generate) which can be given templates for creating any kind of project you want.
