### ISSUE TITLE
Question about VersionInfo in src/cargo/lib/rs

### ISSUE THREAD

**Issue by ShaneLillieRAD** [rust-lang/cargo#7166]
Hello,

I'm wondering about the usage of VersionInfo here: https://github.com/rust-lang/cargo/blob/9ef364a5507ef87843c5f37b11d3ccfbd8cbe478/src/cargo/lib.rs#L64 where the major / minor / patch sizes are u8 rather than u64. It seems like this struct is only used for the version of Cargo itself, but the commenting around it has me a little unsure. Is it correct to assume it is not used internally for anything else?

The reason I'm asking is that my team is looking into setting up an internal crate registry and we'll potentially be using our Perforce changelist number as the patch value of our crate versions. That number is approaching half a million at this point and we just want to be sure we aren't going to overflow anything internal to Cargo or the crates themselves in doing that.

**Comment by ehuss** [comment]
Correct, that struct is only for cargo's version itself (currently 39, gives us about 24 years till it overflows).  

Versions for packages use the [`semver`](https://crates.io/crates/semver) crate which looks to use u64.

**Comment by ShaneLillieRAD** [comment]
Awesome, thank you so much for the quick response!
