### ISSUE TITLE
New project without git

### ISSUE THREAD

**Issue by stevenleeS0ht** [rust-lang/cargo#7177]
The project is created with git support by cargo in default.

It would be awesome to provide an option to create project without git in order to use other scm-tools.

It can make it more flexible for other scm or no scm.

**Describe the solution you'd like**

an option like `--no-git` would be fine.

**Notes**

**Comment by ehuss** [comment]
You can set the vcs with the `--vcs` flag, including `none` to not use any.  You can also set the default in the [config](https://doc.rust-lang.org/cargo/reference/config.html).

**Comment by klishevich** [comment]
This worked for me `cargo new --vcs=none my-new-project`

**Comment by AbstractWhy** [comment]
thx
