### ISSUE TITLE
Cargo doesn't check the value of CI environment variable

### ISSUE THREAD

**Issue by mchernyavsky** [rust-lang/cargo#7184]
**Problem**

Currently, Cargo only checks that `CI` variable exists, but doesn't check its value.
https://github.com/rust-lang/cargo/blob/5251d92d47e5b30516a9ac5cc9440cd33afea161/src/cargo/util/progress.rs#L48

Because of this, even if the value is empty or set to `false`, Cargo still thinks that we are on CI.

**Possible Solution(s)**

I'm not sure about other CI services, but AppVeyor and Travis set `CI` to `true` ([1](https://www.appveyor.com/docs/environment-variables/), [2](https://docs.travis-ci.com/user/environment-variables/)). We can do something like that:

```rust
let ci = match env::var("CI") {
    Ok(value) => !value.is_empty() && !value.eq_ignore_ascii_case("false"),
    Err(_) => false,
};
```

**Notes**

Output of `cargo version`:

```
cargo 1.38.0-nightly (e3563dbdc 2019-07-16)
```

**Comment by ehuss** [comment]
I'm going to close this, per the discussion in #7229.  This is intended for CI environments, and it is unlikely a CI system would set it to a falsey value.
