### ISSUE TITLE
Build with pipelining enabled fails with `error: Unrecognized option: 'json-rendered'`

### ISSUE THREAD

**Issue by dmit** [rust-lang/cargo#7195]
**Problem**
A new **nightly** cargo project failed to compile while the env variable `CARGO_BUILD_PIPELINING` was set to `true`.

```
>cargo build
    Updating crates.io index
   Compiling proc-macro2 v0.4.30
   Compiling winapi v0.3.7
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.42
   Compiling bitflags v1.1.0
   Compiling unicode-width v0.1.5
   Compiling unicode-segmentation v1.3.0
   Compiling vec_map v0.8.1
error: Unrecognized option: 'json-rendered'
error: Could not compile `unicode-xid`.
warning: build failed, waiting for other jobs to finish...
error: Unrecognized option: 'json-rendered'
error: Could not compile `unicode-width`.
warning: build failed, waiting for other jobs to finish...
error: Unrecognized option: 'json-rendered'
error: Could not compile `unicode-segmentation`.
warning: build failed, waiting for other jobs to finish...
error: Unrecognized option: 'json-rendered'
error: Could not compile `vec_map`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Unsetting the variable fixed the build error.

**Steps**
1. Clone https://github.com/dmit/cargo-pipeline-fail for a minimized repro, or create a new cargo project and add `structopt 0.2` as a dependency
2. `cargo build`

**Possible Solution(s)**
The project only has a single dependency: `structopt = "0.2"`. Brief testing with other dependency crates failed to trigger the problem. Since the failure only happens with build pipelining enabled, might possibly be caused by the topology of this particular dependency graph?

**Notes**
OS: Windows 10

>cargo version
cargo 1.38.0-nightly (d0f828419 2019-07-23)

>rustc -V
rustc 1.38.0-nightly (dddb7fca0 2019-07-30)

**Comment by ehuss** [comment]
Pipelining is in the process of being stabilized.  You can follow #7143 which is the Cargo side, I'll hopefully review it today.  It then needs to make its way into nightly which can take anywhere from a couple days to a couple weeks.
