### ISSUE TITLE
Incremental build scripts?

### ISSUE THREAD

**Issue by axos88** [rust-lang/cargo#7197]
I have a have a setup with rust code interfacing with C code. My build.rs is set up to compile the C code, generate the rust bindings, and generate a few other source files (memory maps for the linker script - this is an embedded environment).

The build.rs spits out the correct `cargo-rerun-if-changed` line, and it is reinvoked correctly if any of them changes, BUT:

The problem is that EVERYTHING is regenerated. If I change the memory layout a bit, not only the linker script is regenerated, but the library is also rebuilt AND the bindgen is rerun, which takes quite some time.

Question: Is there (more-or-less) standard way to either:
  - split a build script into multiple sub-build scripts with their own rerun settings (one for each job)
  - determine during run if the dependencies of one of the jobs changed, and skip it otherwise. SOMETHING definetly changed, so it's not a problem that the build script is rerun, but I ONLY want to rerun the jobs that actually need updating. This might be tricky if environment variables, etc changed instead of the files, since I'd want to rebuild everything in that case.

**Comment by alexcrichton** [comment]
Currently there's not really a standard way to do this, but rather build scripts need to implement the incremental logic themselves. Cargo provides support to know when to not run the build script at all, but when it runs the build script will have to know itself to check filesystem timings (for example) to see what's changed.

I think this is out of scope for Cargo at this time so I'm going to close this, but let me know if you still have questions!

**Comment by axos88** [comment]
Is there a way to tap into / access the information cargo has based its decision to run the build script?

**Comment by axos88** [comment]
Also what is your take on having "multiple" build scripts? Would that be totally out of scope as well?

**Comment by alexcrichton** [comment]
Currently, no, there's no way to get access to information about why Cargo is executing the build script. I think multiple build scripts is a bit of a strech, but if you're interested in championing that feature you can always write an RFC!

**Comment by axos88** [comment]
Hmm. Never done that, and it sounds scary :), but I might try to tackle it if I have some free time.
