### ISSUE TITLE
cargo nightly build with RUSTFLAGS having --remap-path-prefix broke since last nightly on Windows

### ISSUE THREAD

**Issue by pocesar** [rust-lang/cargo#7211]
**Problem**

When using `remap-path-prefix` before, I was able to set the paths to a common root like : "build/src/", now the generated .d files had wrong paths when trying to set the RUSTFLAGS with remap-path-prefix and cargo fails with:

```
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling serde v1.0.98
error: could not parse/generate dep info at: C:\ard\target\debug\deps\unicode_xid-d89e93a95ce7a9a5.d

Caused by:
  The system cannot find the path specified. (os error 3)
warning: build failed, waiting for other jobs to finish...
error: could not parse/generate dep info at: C:\ard\target\debug\build\serde-cbe4cec761dd61b5\build_script_build-cbe4cec761dd61b5.d

Caused by:
  The system cannot find the file specified. (os error 2)
warning: build failed, waiting for other jobs to finish...
error: could not parse/generate dep info at: C:\ard\target\debug\build\proc-macro2-c6a71a674b70c483\build_script_build-c6a71a674b70c483.d

Caused by:
  The system cannot find the file specified. (os error 2)
build failed, exit code 101 null
```

So at the moment, the builds are non reproducible (for me at least)

**Steps**

1. Setup a simple bin with any dependencies, put some code that uses it
2. set `RUSTFLAGS=--remap-path-prefix=C:\ard\=\build\src\` on the console
3. try to `cargo build`

N.B: used to work fine before
PS: if you put "quotes" around the value as in `"C:\ard\=\build\src\"`, the remap fails

**Possible Solution(s)**

It seems that some commits regarding the `remap-path-prefix` and dealing with Windows paths, might have broken it: 

d99b7fede7eaff781c9160331f5bb005f00b530f
1140c527c4c3b3e2533b9771d67f88509ef7fc16
c8a9f88f097c13fb297f48ca898914dd6d7e683a
65e3885ce3a60e61aaede458233616c177a1f701
3595de3608d83bd64206c46bc7f4da2db38659c6
4f6553ab553ca127ab653bec9f2f65e64735912f

**Notes**

Output of `cargo version`: cargo 1.38.0-nightly (26092da33 2019-07-31)

Windows 10 x64
rustc 1.38.0-nightly (d3f8a0b5d 2019-08-04)

**Comment by ehuss** [comment]
Thanks for the report. I'm having a hard time reproducing the issue.  Can you tell me which terminal you are using (cmd, powershell, mingw, etc.) and exactly which commands you ran? Also, does it happen with any project, or does it require certain dependencies?

**Comment by pocesar** [comment]
I'll try to make a minimal repro, meanwhile, if I set to `--remap-path-prefix=C:\ard\=`, it works as before (which has the same reproducible result but the paths are empty)

**Comment by alexcrichton** [comment]
@ehuss I think this may be caused by https://github.com/rust-lang/cargo/pull/7030 where we're expecting absolute paths coming out of the compiler but actually the dep-info files are likely lying since they're respecting `remap-path-prefix` which means they point to paths which don't exist...

cc @Mark-Simulacrum, you're likely interested in this as well

**Comment by Mark-Simulacrum** [comment]
That's quite likely, yes, I wasn't aware that dep-info files are remapped by `--remap-path-prefix`, in fact that feels a bit odd? Presumably independent of the mapped path in the binary and such you'd want Cargo to receive the real on-the-disk path...

**Comment by ehuss** [comment]
I see what's happening.  It's due to [this line](https://github.com/rust-lang/cargo/blob/c6044168921bade7147e34457cb130bd5eaaadfb/src/cargo/core/compiler/fingerprint.rs#L1584) I added to canonicalize the path.  I'll post a PR to try to work around it.

As to whether or not the `.d` file should include remapped files or not is a rustc issue.  I'll file an issue over there to track that.

**Comment by ehuss** [comment]
Posted #7219 with a fix.

Posted https://github.com/rust-lang/rust/issues/63329 for the rustc side.  Rebuild detection is broken in Cargo when using `--remap-path-prefix`, so if/when it is fixed, we should probably add a test for that.
