### ISSUE TITLE
Enabling more than one dependency's feature enables its default features.

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/cargo#7228]
My crate depends on cpython crate, and I need to compile the latter with support for Python 2.7.  According to [crate's documentation](http://dgrunwald.github.io/rust-cpython/doc/cpython/#python-27), this is achieved by turning off default features (=`python3-sys`) and adding `python27-sys`:
```toml
[dependencies]
cpython = { version = "0.3.0", default-features = false, features = ["python27-sys"] }
```
So far so good.  

However, when I try to enable one more feature,
```toml
[dependencies]
cpython = { version = "0.3.0", default-features = false, features = ["python27-sys", "extension-module"] }
```
... I get a compilation error in cpython's build script:
```
error[E0428]: the name `PYTHONSYS_ENV_VAR` is defined multiple times
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cpython-0.3.0/build.rs:10:1
   |
7  | const PYTHONSYS_ENV_VAR: &'static str = "DEP_PYTHON27_PYTHON_FLAGS";
   | -------------------------------------------------------------------- previous definition of the value `PYTHONSYS_ENV_VAR` here
...
10 | const PYTHONSYS_ENV_VAR: &'static str = "DEP_PYTHON3_PYTHON_FLAGS";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `PYTHONSYS_ENV_VAR` redefined here
   |
   = note: `PYTHONSYS_ENV_VAR` must be defined only once in the value namespace of this module
```

Turns out that cargo passed both `--cfg 'feature="python27-sys"'` and `--cfg 'feature="python3-sys"'` into build script compilation, whereas they are supposed to be [mutually-exclusive](https://github.com/dgrunwald/rust-cpython/blob/c7224ad2da6a0d2a72cdbc8e358a7522e0e1f1f8/build.rs#L10).   
It looks as if adding more than one dependency feature overrides "default-features = false"...

**Notes**
Output of `cargo version`: `cargo 1.38.0-nightly (26092da33 2019-07-31)`

**Comment by ehuss** [comment]
Looks like you need to use the [`extension-module-2-7`](https://github.com/dgrunwald/rust-cpython/blob/c7224ad2da6a0d2a72cdbc8e358a7522e0e1f1f8/Cargo.toml#L64-L66) feature instead.

**Comment by vadimcn** [comment]
Ah, ok, I guess that makes certain sense...
