### ISSUE TITLE
"Warning: Multiple versions of lib" if version of dependency not specified

### ISSUE THREAD

**Issue by brandonson** [rust-lang/cargo#723]
Say we have dependencies something like this:

libA -> libB
Executable -> libA libB

If the Cargo.toml files for Executable and libA declare a version for libB, everything works fine (as far as I can tell).  However, if they don't have a version specified, cargo seems to compile libB multiple times, which creates multiple copies of it causing all kinds of nastiness.  (For example, trait impls that exist not being found because they're implemented for the trait in the other copy of libB)

Interestingly, removing the dependency declaration for libB in the Cargo.toml for Executable will make everything work - you can still use libB in code, even though it's not declared as a dependency.  This might be because libB still gets compiled while building libA.

My personal expectation would be that if no version dependencies are specified, Cargo should compile only a single copy of libB, preferably the latest version, and use that copy to build all libraries that depend on it.  Even if it's not the latest version, I'm pretty sure we definitely don't want multiple copies of a lib.

Example cargo files:

`libA/Cargo.toml:`
```
[package]
...
[dependencies.libB]
git = "..."
//version = "0.0.1" //works with this line and the version 
                    //line in Executable/Cargo.toml, without it it fails
```

`Executable/Cargo.toml:`
```
[package]
...
[dependencies.libB]
git = "..."
//version = "0.0.1" //works with this line and the version 
                    //line in libA/Cargo.toml, without it it fails
```

**Comment by alexcrichton** [comment]
This warning has since been removed from the compiler.
