### ISSUE TITLE
Adding email by default to Cargo.toml can be a privacy issue

### ISSUE THREAD

**Issue by madprops** [rust-lang/cargo#7250]
I just realized after somebody else told me, that my email was visible on the git repo. It was added automatically to Cargo.toml - It's an email I don't like to be public-facing. Not sure why putting the email on the file is necessary.

**Comment by Mark-Simulacrum** [comment]
IIRC, we use the same email as configured in Git by default; presumably, all of your commits also have the same email? If not, the bug is probably there.

**Comment by madprops** [comment]
But I think I can hide the email from being public in Github?

**Comment by Mark-Simulacrum** [comment]
I don't think that's true, as it's part of the hash, so you'd never be able to work with anyone at least. Just pulling a random commit, https://github.com/madprops/armtrak/commit/4c426293dd115f465c40a13f5de0b88c4b79ea4f.patch, lists `madprops <manuelchaves@gmail.com>` -- is that the email you're intending to keep hidden?
