### ISSUE TITLE
Support `.toml` file extension on `.cargo/config`

### ISSUE THREAD

**Issue by anp** [rust-lang/cargo#7273]
**Describe the problem you are trying to solve**

To have syntax highlighting in VSCode I currently create a custom file association in my settings:

```json
    "files.associations": {
        "**/.cargo/config": "toml"
    },
```

I'd love to not have to do this!

**Describe the solution you'd like**

Could cargo accept `.cargo/config.toml` as a path for local configuration?

**Notes**

There are many alternatives available, like making the Rust editor plugins aware of this association. However, cargo's usage of TOML elsewhere is identified by the file extension (consistency), and this change would presumably improve ergonomics in other places that do syntax highlighting, not just in editors (availability).

**Comment by oli-obk** [comment]
We should just change our docs to show `config.toml` everywhere and support both `config` and `config.toml` for backwards compat. Noone will be affected and everyone can update as they please.

**Comment by fluffysquirrels** [comment]
What do we do where both `config` and `config.toml` exist? How about issuing a warning and defaulting to `config`? My preference leans toward issuing an error if both exist, but this is a breaking change affecting people that already have both for some reason.

**Comment by anp** [comment]
I agree re: an error being a weird change for someone who had both paths available.

Defaulting to `config` on conflict sounds great to me, since it matches the behavior someone with both files would already have observed. Printing a warning also sounds great to me.
