### ISSUE TITLE
Support for --explicit-version in `cargo vendor`

### ISSUE THREAD

**Issue by acmcarther** [rust-lang/cargo#7291]
As requested [by the embedded error message on flag usage](https://github.com/rust-lang/cargo/blob/9ef364a5507ef87843c5f37b11d3ccfbd8cbe478/src/bin/cargo/commands/vendor.rs#L95-L107), I'm filing this bug to request re-inclusion of versioning functionality. 

I maintain [cargo-raze](https://github.com/google/cargo-raze), a tool that generates BUILD files for Cargo dependencies for projects using the [Bazel build tool](https://https://bazel.build/). Historically the cargo-vendor crate has been a primary component of our "pre vendored dependency" use case, and we rely on explicitly versioned crate directory output in order to make the generated output directories more predictable.

Without this functionality, we'll need to suggest users continue to use the cargo-vendor crate, deprecate the vendored dependency use case, or package this functionality into our own crate.

**Comment by apoelstra** [comment]
Is there any way to update the toolchain past 1.36 with this bug present?

**Comment by apoelstra** [comment]
Ah! Directly calling `cargo-vendor vendor` (two `vendor`s) is the workaround.

**Comment by jgallagher** [comment]
Is this resolved as of #7631? (Sorry if this is an out-of-left-field comment, but I was just poking around and noticed that cargo-raze as linked in the original request had updated its Readme to reference the new `--versioned-dirs` flag added in that PR.)

**Comment by ehuss** [comment]
Yes, this appears to be done, thanks!
