### ISSUE TITLE
Cargo give SSL certificate invalid error when building in rust:latest docker image

### ISSUE THREAD

**Issue by ccqpein** [rust-lang/cargo#7305]
When I try to build my project in rust docker image, cargo return me error `the SSL certificate is invalid; class=Ssl (16); code=Certificate (-17)`. 

Output of `cargo version`: cargo 1.37.0 (9edd08916 2019-08-02)

Whole command I use to find this problem:
`docker run --rm -it rust cargo install rustfmt`

**Comment by ccqpein** [comment]
I have run some tests in docker container. The problem is I have a `self signed certificate` behind my local machine proxy. 

The solution is: I run container with `-v /self-signed-CA-cert.pem:/in_docker_cert.pem`, then `export SSL_CERT_FILE=/in_docker_cert.pem`. 

Problem solved.

**Comment by ehuss** [comment]
Closing, as this looks like this was solved.
