### ISSUE TITLE
Fill the gap between "cargo install" and "cargo build --release"

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/cargo#7309]
Currently we can use "cargo install" to install an executable. And we can use "cargo build" to build the artifact. There should be a third command that deploys the executable artifact to $CARGO_HOME/bin and let cargo install manage them.

**Comment by joshtriplett** [comment]
It feels like this request went directly to having a particular solution in mind, rather than describing the problem you're trying to solve. Could you please explain what problem you're trying to solve here?

**Comment by crlf0710** [comment]
Sure~ #1 When we develop a binary crate for our own use #2 When we use other's binary crate but does some patching and hacking ourselves, we modify the code, run `cargo run --release` and made sure it works ok. Now we're happy with the code and want to install the built artifacts to our systems' "~/.cargo/bin" directory. If we do a `git install`, everything will be built from scratch - works but can be really slow.

So, the best approach could be copying the built artifacts to that directory. Currently i do this manually, but I wish this could be covered by some use of cargo.

**Comment by raftario** [comment]
This is a feature I thought about too and I'd be interested in working on it. Would a new `--install` flag added to the build command make sense ?

**Comment by Huanzo** [comment]
You can use the the install subcommand to install a local crate without recompiling it with the path argument.

`cargo install --path .` inside your project root should install the current binary crate without recompilation.

**Comment by weihanglo** [comment]
I feel like [this comment](https://github.com/rust-lang/cargo/issues/7309#issuecomment-546721182) from Huanzo should do the trick. Things need to beware is that `cargo install` defaults to do a `--release` build whereas `cargo build` using dev profile. See [Cargo Guide: Profiles](https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#default-profiles).

There should be nearly no recompile if their compiler flags and the profile matche. Sometimes a mismatch happens though.

**Comment by epage** [comment]
Considering that cargo install seems to be able to do the trick, I'm going to close this.  If there is a reason for us to reconsider this, let us know!
