### ISSUE TITLE
Cargo install uses rustup override for current folder

### ISSUE THREAD

**Issue by johalun** [rust-lang/cargo#7312]
**Problem**

`cargo install` seem to use the rust version specified with `rustup override` for the current folder.

**Steps**

1. rustup override set stable
2. cargo install xxx (builds with stable)
3.  rustup override set nightly
4 cargo install xxx (builds with nightly)

**Possible Solution(s)**

I think it would make more sense to use the default toolchain.

**Notes**

Output of `cargo version`: cargo 1.39.0-nightly (22f7dd049 2019-08-27)

Rust stable 1.37 and nightly 1.39.
FreeBSD 13-CURRENT.

**Comment by steffahn** [comment]
This behavior is insane. I’ve been using Rust for 2 years now and never noticed this until today when a `cargo install` failed in a directory with an old version in the override. So I’ve been unintentionally occasionally installing tools with `nightly` without even noticing!

**Comment by epage** [comment]
While this is the original, closing in favor of #11036 since it has more of a conversation.  Technically, they were created for different ways within `rustup` of setting the override (local file, user config) but I think we should look at them holistically which means one issue.
