### ISSUE TITLE
Cargo is not excluding target/ directories from MacOS time machine

### ISSUE THREAD

**Issue by orf** [rust-lang/cargo#7317]
**Problem**
Seems to be the same as #7189. Cargo no longer marks `target/`, or any subdirectories, as excluded from time machine backups. This causes lots of backup bloat!

**Steps**
1. Run `cargo new my-cool-project`
2. Run `cargo build my-cool-project`
3. Run `tmutil isexcluded target/` and see that it says the `target/` directory is included in backups.

**Possible Solution(s)**
The current implementation seems too fragile, as it's broken before and it's broken now. Simply setting the `com.apple.metadata:com_apple_backup_excludeItem` xattr on the directory is enough, rather than invoking an Objective-C framework method.

**Notes**

Output of `cargo version`: cargo 1.37.0 (9edd08916 2019-08-02)

Latest MacOS.

**Comment by orf** [comment]
CC @alexcrichton - sorry for the notification, but I saw you worked on this in #7189.

**Comment by ehuss** [comment]
It was fixed in [1.38](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-138-2019-09-26), did you try that version?

**Comment by orf** [comment]
I feel so stupid, I'm sorry. I thought that it was fixed in 1.37. Confirmed it works as expected in 1.38.0.
