### ISSUE TITLE
Warning when replacing crate using copy from local registry in Rust 1.37

### ISSUE THREAD

**Issue by richardwhiuk** [rust-lang/cargo#7328]
**Problem**

One pattern that we've started to use is to override a dependency in crates-io with a local fork, published to a private registry. This is normally done in order to fast-track a bug fix while it's in consideration upstream, or to patch a bug in a crate / release which is no longer maintained.

This works by doing:

```
[replace]
"hyper:0.11.27" = { registry = "private" }
```

However, in Rust 1.37, this produces a warning:

```
warning: dependency (hyper) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
```

If we specify a version (which must be 0.11.27 for the replace to match), then Cargo complains:

```
+ cargo fetch
error: failed to parse manifest at `/src/project/Cargo.toml`

Caused by:
  replacements cannot specify a version requirement, but found one for `https://github.com/rust-lang/crates.io-index#hyper:0.11.27`
```

Is this workflow expected?

Note, it surprises me that `[replace]` is the preferred option instead of patch - to me `[patch]` feels much more powerful (in particular, you can patch something with a version with a different version number, whereas replace doesn't allow you to version the replacement).

**Steps**
1. Have a private registry
2. Use replace to replace a crate from crates.io with one from the private registry, with the same number and version
3. Attempt to build the crate on Rust 1.37

**Possible Solution(s)**

a) Allow just `registry` in a replacement.
b) Allow specifying a version in a replacement.
   i) Only allow specifying the same version as is being replaced
   ii) [Preferred] Allow specifying a different version in a replacement.

**Notes**

Output of `cargo version`:

```
# cargo --version
cargo 1.37.0 (9edd08916 2019-08-02)
```

**Comment by ehuss** [comment]
> `[replace]` is the preferred option instead of patch

It is the other way around.  You should be using `[patch]`, not `[replace]`.  Does `[patch]` work for you?

**Comment by ehuss** [comment]
I'm going to close this as expected behavior. `[replace]` should no longer be used, and `[patch]` should allow specifying a crate to a registry with a version.
