### ISSUE TITLE
Docs for build script `cargo:rustc-cfg` are unclear

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/cargo#7338]
In the [Build Scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) page the docs for `cargo:rustc-cfg` give it as `rustc-cfg=FEATURE`, but apparently the correct form is to use `cargo:rustc-cfg=feature=\"feature_name\"` , so perhaps we should update that page.

**Comment by sfackler** [comment]
`rustc-cfg=FEATURE` will enable `#[cfg(FEATURE)]`.

**Comment by Lokathor** [comment]
_ooooooooooooh_

Yeah that's not clear in the docs.
