### ISSUE TITLE
Cargo hangs when building four build-script packages simultaneously

### ISSUE THREAD

**Issue by asonix** [rust-lang/cargo#7341]
**Problem**

Cargo hangs when building one of my projects:
```
   Compiling backtrace-sys v0.1.31
   Compiling libloading v0.5.2
   Compiling miniz-sys v0.1.12
   Compiling brotli-sys v0.3.2
     Running `/home/asonix/Development/rust/actix-sled-authentication/target/debug/build/backtrace-sys-7d82d131ecf96f50/build-script-build`
     Running `/home/asonix/Development/rust/actix-sled-authentication/target/debug/build/libloading-1c2e6504b4ce6ed6/build-script-build`
     Running `/home/asonix/Development/rust/actix-sled-authentication/target/debug/build/miniz-sys-e2da2eca70b6e698/build-script-build`
     Running `/home/asonix/Development/rust/actix-sled-authentication/target/debug/build/brotli-sys-4bcf637074d9f2a6/build-script-build`
   Building [===>            ] 215/271: libloading(build), miniz-sys(build), brotli-sys(build), backtrace-sys(build)   
```
It's not an issue with any of these crates individually, as building the "flate2-rs" repo, which depends on `miniz-sys`, works fine.

I've tried this on my desktop with an older quad-core Intel Core i5, and on my laptop with a newer dual-core (with hyperthreading) i7u processor, both running elementary OS 5.0 Juno (`Linux asonix-librem 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`).

I've also tried both the nightly and the stable toolchains, and the problem persists across both.

**Steps**

1. clone this repository: https://git.asonix.dog/asonix/actix-sled-authentication
2. run `cargo build`

**Possible Solution(s)**

not sure

**Notes**

Output of `cargo version`:
- stable: cargo 1.37.0 (9edd08916 2019-08-02)
- nightly: cargo 1.39.0-nightly (fe0e5a48b 2019-09-04)

**Comment by alexcrichton** [comment]
Thanks for the report, but this is a bug in the `cc` crate's recent releases, not Cargo. Should be fixed in `cc` though.
