### ISSUE TITLE
Why so many lifetimes?

### ISSUE THREAD

**Issue by dpc** [rust-lang/cargo#7342]
I'm sorry for bothering you, but I'm interacting with cargo library a lot and I can't help but wonder - why is there so many complications in the API? There are many lifetimes, `RefCell`s (that make stuff `!Sync` etc.

Like, why can't `Config` be taken by move so that `Workspace` and bunch of other structs doesn't require lifetime? Why not just `Arc<Mutex<_>>` stuff instead of playing with `RefCell`s? I don't think there's much performance wins to be had in the code that will always be blocked on IO anyway. Is there something I am missing here?

**Comment by alexcrichton** [comment]
I think the answer here is "Alex thought it was fun to avoid `RefCell` and `Mutex`", there's no real technical motivation.

**Comment by dpc** [comment]
Is it something that can be easily fixed? If I submitted a PR would it get accepted? It does affect my code quite a lot, because many times I do want to store these structs and it bubble up in the code.

**Comment by alexcrichton** [comment]
To be honest it's not really something that's ever been considered I think. It would be a pretty massive and major refactoring of Cargo, so I suspect this would not be easily fixed. I would encourage discussing with the cargo team (e.g. not just me) about this before proceeding.

**Comment by dpc** [comment]
https://internals.rust-lang.org/ ?

**Comment by dpc** [comment]
What's the deal with interning? https://github.com/rust-lang/cargo/blob/59f50abc4ca3b9cc4594e6601f84107d2d454e34/src/cargo/core/interning.rs#L17

**Comment by Eh2406** [comment]
We don't just intern strings, we do the same for package_ids #6332 and source_ids #6342. The structure of interning has changed, but the justification is the same as when it was introduced https://github.com/rust-lang/cargo/pull/5121 (I used blame in the github UI to find that PR). 

There are 3 reasons interning is grate:
1. A significant percent of all the strings cargo makes are the string "serde". keeping only one copy of each string significantly reduces memory usage.
2. Having deduplicated a string, EQ is `O(1)` not `O(n)`, and does not require a cache miss.
3. An interned string has `O(1)` clone, no allocations no `O(n)` copy and no cache miss. The Resolver needs to copy most of its internals for each of the crates in the dependency tree, so clone speed really matters.

BTW, what project are you working on?

**Comment by dpc** [comment]
Oh. So it's a perf optimization. I wonder if this really makes a difference. I mean... how many dependencies people have etc.? Anyway - thanks for answer.

I am working on https://github.com/crev-dev

**Comment by epage** [comment]
Considering cargo-the-library is provided as-is, a major refactor like this would likely be driven by the needs of cargo-the-bin, rather than users of the API.  It'll also likely be done opportunistically as other feature development is happening.  As such, I'm going to go ahead and close this out.  If there is a reason for us to reconsider, let us know!
