### ISSUE TITLE
Can't publish from workspace root, no -p option

### ISSUE THREAD

**Issue by Riateche** [rust-lang/cargo#7345]
Unlike other `cargo` commands, `cargo publish` doesn't accept `-p` or `--package` option, so `cargo publish` doesn't work at all at the workspace root:
```
$ cargo publish
error: manifest path `.../Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
$ cargo publish -p name 
error: Found argument '-p' which wasn't expected, or isn't valid in this context
```

Lack of the `-p` option seems like an oversight.

**Comment by sfackler** [comment]
You can use `cargo publish --manifest-path name/Cargo.toml`, but a `-p` flag would be much cleaner.
