### ISSUE TITLE
ZSH completions don't work

### ISSUE THREAD

**Issue by burjui** [rust-lang/cargo#7357]
**Problem**
ZSH completions for Cargo provided by `rustup` don't work. Completions for `rustup` work fine though. 
[Corresponding `rustup` issue](https://github.com/rust-lang/rustup.rs/issues/1821)

**Steps**
```sh
mkdir ~/.zfunc
rustup completions zsh cargo > ~/.zfunc/_cargo
rustup completions zsh > ~/.zfunc/_rustup
fpath+=~/.zfunc
compinit
```

**Notes**

```sh
$ cargo version
cargo 1.37.0 (9edd08916 2019-08-02)

$rustup --version
rustup 1.18.3 (435397f48 2019-05-22)
```

**Comment by Eh2406** [comment]
Looks to me (as a windows based lifeform) like they have had some work done recently, see #7296. Can you reproduce on a recent nightly toolchain?

**Comment by ehuss** [comment]
Oh, I should have cc'd here, I left a comment on the rustup issue. I think it is due to the way rustup generates the completion, and isn't affected by the recent updates.

**Comment by burjui** [comment]
@ehuss I just checked your response on the `rustup` issue, and indeed, it works the way you did it. So it's clearly not a `Cargo` issue.

**Comment by sgtz** [comment]
_cargo and _rustup completions stopped working for me while others were okay. Since zsh completions create a .zcompdump cache file, removing .zcompdump and allowing it to be regenerated got completions working again.
