### ISSUE TITLE
--timings: show crate version in the graph?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#7384]
When different dependencies pull in multiple versions of the same crate, it would help to see the version of the crate that was compiled. (See syn when building rustfmt
![syn](https://user-images.githubusercontent.com/476013/65191630-ec7a2480-da74-11e9-8808-ccf02468b741.png)
)

**Comment by m-bal** [comment]
I would like to take a crack at this. I understand the team doesn't accept new features without the `S-accpeted` label, but I thought I'd ask in case. Is it okay to work on this?

**Comment by weihanglo** [comment]
Hi, @m-bal. Thank you for being interested in this. I feel like it would be good to have that option off by default, and have a toggle button for that. Some pointers:

* The units table is serialized here <https://github.com/rust-lang/cargo/blob/27a41d67899dfc84e6f859a9fe938e93fcca564a/src/cargo/core/compiler/timings.rs#L564-L568>
* The drawing of the SVG of an unit lives in <https://github.com/rust-lang/cargo/blob/27a41d67899dfc84e6f859a9fe938e93fcca564a/src/cargo/core/compiler/timings.js#L114>
* The unit data passed into JavaScript is here <https://github.com/rust-lang/cargo/blob/27a41d67899dfc84e6f859a9fe938e93fcca564a/src/cargo/core/compiler/timings.rs#L496>

**Comment by m-bal** [comment]
> ... when they need to disambiguate.

@weihanglo Do you mean only add the crate version if we see a duplicate crate (same crate name) with a different version in the list of crates (`units`)? If so, would creating a list of duplicate crates with a different version, then checking that list when creating the `label` and adding the version be a sufficient implementation?

**Comment by remkop22** [comment]
I don't see any progress on this. Would it be okay if I picked this up?

**Comment by weihanglo** [comment]
@remkop22, not sure whether @m-bal already started or not. Since it was a month ago, it's probably fine for you to take over I guess.

Feel free to ask questions here!

**Comment by Angelin01** [comment]
@weihanglo Pardon my intrusion as I believe there's two people that said they'd fix this issue, but I took a quick look at the code you linked and I do believe the solution is as simple as this patch:

```diff
diff --git a/src/cargo/core/compiler/timings.js b/src/cargo/core/compiler/timings.js
index 986070ab0..92f57fb9a 100644
--- a/src/cargo/core/compiler/timings.js
+++ b/src/cargo/core/compiler/timings.js
@@ -111,7 +111,7 @@ function render_pipeline_graph() {
     ctx.textAlign = 'start';
     ctx.textBaseline = 'middle';
     ctx.font = '14px sans-serif';
-    const label = `${unit.name}${unit.target} ${unit.duration}s`;
+    const label = `${unit.name}${unit.target} (v${unit.version}) ${unit.duration}s`;
     const text_info = ctx.measureText(label);
     const label_x = Math.min(x + 5.0, canvas_width - text_info.width - X_LINE);
     ctx.fillText(label, label_x, y + BOX_HEIGHT / 2);
```

Which gives this result:
![image](https://github.com/rust-lang/cargo/assets/17818024/38a2442d-0216-4352-979b-f5164e03a802)

It doesn't only mark the version when there are duplicate crates, but in my opinion this is more "honest" as the version is shown.  
Is this acceptable?

**Comment by weihanglo** [comment]
Hey @Angelin01, thanks for being interested in this!

My original idea is that duplicate crates are minority, so it may be worth showing versions only when there are really duplicates to reduce visual noise. I don't really have a strong opinion, and it is easy to revert if people feel too noisy then.

So, go ahead!

(BTW I may display it as `syn v2.0.18` since the table below uses this format. Having the same format make it easy to do text search)
