### ISSUE TITLE
cargo doc --open doesn't work on Windows

### ISSUE THREAD

**Issue by tomaka** [rust-lang/cargo#741]
Unfortunately I can't compile Cargo on Windows, so I don't understand why.
Running `start path/to/docs` manually (what [Cargo is supposed to do](https://github.com/rust-lang/cargo/blob/abc712795321d13dcf6839242c476e42d3e211d2/src/cargo/ops/cargo_doc.rs#L77)) works.

**Comment by tomaka** [comment]
Just confirming that it doesn't work on a fresh installation of Windows 7, so the problem didn't come from my system.

**Comment by mohtar** [comment]
Have you tested on other operating systems? Seems like you're implying that this problem only happens on Windows only and not other operating systems, or am I reading this wrong?

**Comment by tomaka** [comment]
Yes, it works on Ubuntu.

**Comment by mohtar** [comment]
Launching `start` programmatically won't work. See my solution: #1535
