### ISSUE TITLE
Warn for missing `lib.rs` when using local crate

### ISSUE THREAD

**Issue by ClementNerma** [rust-lang/cargo#7410]
**Problem**
I currently have a project splitten into multiple crates. Currently I have two of them, `backend` which works on its own as a library and `server` which relies on `backend`.

So I created my `server` project using `cargo new server --bin` and added `backend` as a dependency:

```toml
[dependencies]
backend = { path = "../backend" }
```

But when I ran `cargo build`, I got a message telling: `can't find crate for backend`.

The issue is that my library's main file was called `main.rs` (I originally created it as a binary project). When I renamed it to `lib.rs`, it worked immediatly. But it took me some time to figure it out.

**Steps**

1. Create a binary project (A)
2. Create another binary project (B)
3. Reference (A) as a dependency in (B) using `Cargo.toml`
4. Build - that won't work

Solution is to rename `main.rs` in (A) to `lib.rs`.

**Possible Solution(s)**

Instead of telling `can't find crate for backend`, the compiler should tell `can't find lib.rs file in backend crate` or something like this (precise error message is to define).

**Notes**

Output of `cargo version`: `cargo 1.39.0-nightly (3596cb86b 2019-09-19)`

**Comment by eminence** [comment]
Triage:  Here is the warning that cargo will print out today if you add a dependency on a crate without a library:

> warning: server v0.1.0 (/home/achin/tmp/54/server) ignoring invalid dependency `backend` which is missing a lib target

**Comment by ClementNerma** [comment]
Thanks, this seems clear enough.
Closing the issue.
