### ISSUE TITLE
Failed to parse manifest when packaging.

### ISSUE THREAD

**Issue by YoEight** [rust-lang/cargo#7412]
Greetings!

**Problem**

With version 1.37.0, I'm unable to `cargo package` a library of mine. Cargo failed with this error message.
```
~/c/eventstore-rs ❯❯❯ cargo package                                                                                                                                                                                                     master
   Packaging eventstore v0.4.2 (/home/yoeight/code/eventstore-rs)
   Verifying eventstore v0.4.2 (/home/yoeight/code/eventstore-rs)
error: failed to verify package tarball

Caused by:
  failed to parse manifest at `/home/yoeight/code/eventstore-rs/target/package/eventstore-0.4.2/Cargo.toml`

Caused by:
  can't find `integration` test, specify test.path
```
Note that I don't experience that issue if I use 1.36.0 version.

**Steps**

1. Clone https://github.com/YoEight/eventstore-rs. You might have to install openssl lib, I know it's `libssl-dev` on Ubuntu.
2. cargo build
3. cargo package (It will fail every time)

**Possible Solution(s)**

If you pass `--no-verify`, `cargo package` succeeds.

**Notes**

```
~/c/eventstore-rs ❯❯❯ cargo --version                                       master
cargo 1.37.0 (9edd08916 2019-08-02)
```

```
~/c/eventstore-rs ❯❯❯ rustc --version                                       master
rustc 1.37.0 (eae3437df 2019-08-13)
```
I experienced that issue on both Ubuntu 18.04LTS and 19.04. I didn't try on a different OS yet.

Thank you for your time.

**Comment by alexcrichton** [comment]
Thanks for the report! I believe this is because [tests are excluded from the package](https://github.com/YoEight/eventstore-rs/blob/d9f5e1ebf10c6365c3c17a45f9f9d1379de55fd2/Cargo.toml#L21)

**Comment by YoEight** [comment]
@alexcrichton Thanks. By no longer excluding `tests/**/*`, it works. I will update my `Cargo.toml` accordingly. Do you know why that behaviour changed after 1.36 version?
