### ISSUE TITLE
Source replace works on Linux, but not Windows under git-bash/Cygwin

### ISSUE THREAD

**Issue by Thomspoon** [rust-lang/cargo#7415]
**Problem**

I'm trying to set up a crates.io local repository at work, and the settings that I use on a Linux machine don't seem to work on a Windows machine under git-bash (or Cygwin). I'm currently using Source Replacement with the following configuration:

```
$ cat .cargo/config
[source]

[source.mirror]
registry = "ssh://git@url/~username/crates.io-index.git"

[source.crates-io]
replace-with = "mirror"

[net]
git-fetch-with-cli = true
```

The output when building indicates that the source replacement sort of works:

```
$ cargo build
    Updating `ssh://git@url/~username/crates.io-index.git` index
error: failed to download from `https://crates.io/api/v1/crates/cortex-m/0.6.1/download`

Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.)
```
As shown above its updating the local repository location, but then still tries to pull crates from crates.io, which I don't have permissions to do.

**Steps**

0. Have very restrictive web access through work
1. Create local/user cargo config
2. Try to build with Cygwin/git bash
3. :(

**Possible Solution(s)**

Perhaps company GitBash/Windows https certificates are getting in the way.

**Notes**

Output of `cargo version`: cargo 1.37.0 (9edd08916 2019-08-02)

**Comment by alexcrichton** [comment]
Thanks for the report! Cargo learns where to download crates from with a `config.json` file inside the index, does that still mention to download crates from crates.io? If so that's where the error is it looks like

**Comment by Thomspoon** [comment]
Hey @alexcrichton, unfortunately I don't see a config.json in my registry anywhere.. Would this be in ~/.cargo/registry? Or would it be in the crates-io repo? I used bitbucket's clone git repo tool to clone all of crates.io into a local repository for which I'm trying to point to.

**Comment by alexcrichton** [comment]
@Thomspoon it should be in the root of the `crates.io-index` repository you're using, like this -- https://github.com/rust-lang/crates.io-index/blob/master/config.json

**Comment by Thomspoon** [comment]
That seems to point to a rest API, is it possible to have this point to a raw github repo?

**Comment by alexcrichton** [comment]
It may be possible to structure the github repo that way to have everything arranged just right, but in general, no, Cargo doesn't have support for custom url schemes for registries yet.

**Comment by ehuss** [comment]
I'm not understanding the last few comments very well.

If you want to mirror crates.io, when you clone the index, you need to edit `config.json` to point to your local download endpoint for `.crate` files. The format is documented [here](https://doc.rust-lang.org/cargo/reference/registries.html#index-format), including the ability to adjust the URL format with `{crate}` and `{version}` tags.  Presumably you have some kind of web server with the `.crate` files?  The `api` field can be removed if you don't want to support `cargo publish`.

**Comment by ehuss** [comment]
Closing, as I believe there is a solution to this (modifying `config.json` to point to the local download host).  Also, there is #6219 for making that process a little smoother.
