### ISSUE TITLE
PGO cannot be used via cargo because of how `RUSTFLAGS` are handled.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/cargo#7416]
**Problem**

PGO works in two phases: 

1. Compile an instrumented binary of your program that enables collecting profile data. This is done via `RUSTFLAGS=-Cprofile-generate`.
2. Compile an optimized binary that makes use of the profile data collected in step (1). This is done via `RUSTFLAGS=-Cprofile-use`.

In order for this to work, the symbol names within the two program versions must match up because LLVM generates profiling data in terms of symbol names. 

However, since https://github.com/rust-lang/cargo/pull/6503, `RUSTFLAGS` are fed into the `-Cmetadata` argument to `rustc`. This causes symbol names to differ because one version has `-Cprofile-generate` and the other has `-Cprofile-use` in their `RUSTFLAGS`. 

I think I would prefer not feeding `RUSTFLAGS` into `-C metadata` at all. It does not seem right to me that symbol names are affected by random command line arguments to the compiler.

**Comment by alexcrichton** [comment]
I've proposed a revert of #6503 at https://github.com/rust-lang/cargo/pull/7417 to fix this.

@michaelwoerister out of curiosity was this the cause of why y'all weren't seeing great wins for PGO in Firefox?

**Comment by michaelwoerister** [comment]
@alexcrichton I have confirmed that this issue prevents Firefox from getting any PGO wins, yes. However, I don't know yet if it is the only issue (e.g. GNU ld seems to have a bug that sometimes causes instrumented builds to not record anything 😱). 

I have some microbenchmarks that show a 10-15% win with PGO but have not been able to replicate that with the `regex` benchmark suite, which is my next bigger test case.

**Comment by alexcrichton** [comment]
Oh dear that must have been absolutely gnarly to figure this out, sorry about that!

**Comment by michaelwoerister** [comment]
It's exactly the kind of issue I expected to encounter `:)`
