### ISSUE TITLE
Cargo should not prepend `$HOME/.cargo/bin` to `PATH` for subcommands when it's already in `PATH`, to avoid unnecessary recompilations

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#7431]
`cargo` is [prepending `$HOME/.cargo/bin`/`%HOME%\.cargo\bin` to `PATH`](https://github.com/passcod/cargo-watch/issues/106#issuecomment-445569998), even if `PATH` already contains this dir.
Cargo should only prepend it if it's not already in `PATH`!
Currently this behavior causes unnecessarily recompilations when any dependency uses `rerun-if-env-changed=PATH`, such as [`libsqlite3-sys`](https://github.com/jgallagher/rusqlite/issues/435).
(I have to wait several minutes every time when switching between `cargo check` in my editor and having `cargo watch -x run` running in cmd.exe, because cargo passes an unnecessarily modified PATH to cargo-watch, even though my PATH already contains `%HOME%\.cargo\bin`.)

**Comment by jonhoo** [comment]
Hmm, no, that doesn't seem right. Even when commenting out all those, _and_ using a subcommand to print the env implemented purely in Rust, I still see `PATH` being prepended to 🤔

**Comment by jonhoo** [comment]
Aha! Rustup is the culprit, not Cargo:
https://github.com/rust-lang/rustup/blob/641f498159f7480716cfebfd1eec464770ece4b6/src/toolchain.rs#L459-L466

**Comment by jonhoo** [comment]
See also https://github.com/rust-lang/rustup/issues/2922 and https://github.com/rust-lang/rustup/issues/2848.

**Comment by jonhoo** [comment]
Filed a fix for this in https://github.com/rust-lang/rustup/pull/2978.

**Comment by weihanglo** [comment]
Closed as rustup patch was released in 1.25.0. Thank you all involving in this issue.
