### ISSUE TITLE
`replace` silently ignores parts of the version

### ISSUE THREAD

**Issue by nrc** [rust-lang/cargo#7434]
If you try and `replace` a crate with a version more complex than `x.y.z`, the parts of the version other than `x.y.z` are ignored, which usually means the `replace` does not match any crates and has no effect (Cargo warns about this).

E.g., `grpcio:0.5.0-alpha.3` will not match deps with `version = "0.5.0-alpha.3"`

**Comment by ehuss** [comment]
Considering `replace` is mostly [deprecated](https://github.com/rust-lang/cargo/issues/7092), I imagine it may be unlikely that effort will go into fixing this.  There are also [several known issues](https://github.com/rust-lang/cargo/issues/2222) with how pre-release versions are handled, which may be the root of this problem.

Can `[patch]` work for you instead?

**Comment by epage** [comment]
As `replace` is deprecated and without further information in several years on if `patch` would instead work, I'm going to go ahead and close this.  If there is a reason to keep this open, let us know!
