### ISSUE TITLE
Proc Macro Build Fails with Package Flag

### ISSUE THREAD

**Issue by cwfitzgerald** [rust-lang/cargo#7435]
**Problem**
Inside a multiple crate workspace, `cargo build` succeeds but `cargo build -p bve` fails to build a proc macro crate.

**Steps**
1. Clone my respository https://github.com/BVE-Reborn/bve-reborn at commit `053b7f`.
2. Run `cargo build`. It should succeed and build `bve`, `bve-native`, `bve-derive`, and `bve-build`.
3. Run `cargo build -p bve` or `cargo rustc -p bve`. It will fail to build `bve-derive` because it says it's missing things from the `syn` crate.

**Notes**

This bug is especially annoying as you have to do `-p` to be able to run cargo expand.

Output of `cargo version`:

`cargo 1.39.0-nightly (fe0e5a48b 2019-09-04)`

I am using `nightly-2019-09-12` as my toolchain. Seems to fail on both windows-gnu and linux so is probably not a platform specific issue.

**Comment by alexcrichton** [comment]
Thanks for the report! This is due to how features are unified in Cargo during crate graph builds. You'll need to enable required features in your `syn` dependency if you want to guarantee that `syn` is built with those features.

**Comment by ehuss** [comment]
Yea, what Alex said. 😉 

Something like this should work:

```diff
diff --git a/bve-derive/Cargo.toml b/bve-derive/Cargo.toml
index a5de3b1..7a79247 100644
--- a/bve-derive/Cargo.toml
+++ b/bve-derive/Cargo.toml
@@ -20,4 +20,4 @@ proc-macro = true
 itertools = "0.8"
 proc-macro2 = "1"
 quote = "1"
-syn = "1"
+syn = {version="1", features=["extra-traits", "full"]}
```

When building all of the packages in the workspace, Cargo will unify the features across all the packages.  bve-build includes structopt which includes structopt-derive which includes syn with the "full" feature.  When you build just one package ("bve"), then it doesn't include the unification of unbuilt packages.

**Comment by cwfitzgerald** [comment]
Well I'll be damned, totally hadn't thought of that, thanks both of you!
