### ISSUE TITLE
Cargo Build Timings graph hits browser’s max canvas size

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#7436]
https://gistpreview.github.io/?eeb6459081cf75648d507eeaf1d414f3 is `cargo build -Z timings` for Servo. The canvas appears broken in Firefox and Chromium until the "Min unit time" slider is moved to a non-zero value. This appears to be because the canvas height exceeds `i16::MAX`:

* https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#Maximum_canvas_size
* https://bugs.chromium.org/p/chromium/issues/detail?id=339725

Changing "Min unit time" to even 0.1 seconds filters out many units/crates, making a much smaller canvas.

I’m not sure what a proper solution would be, but maybe we could at least detect this situation and suggest that work-around?

**Comment by SimonSapin** [comment]
> I’m not sure what a proper solution would be,

Maybe splitting the graph into multiple `<canvas>` elements? @ehuss, @alexcrichton, how involved would that be?

**Comment by nox** [comment]
Alternatively, maybe `rustc` should be producing something that can be fed to https://profiler.firefox.com/.

**Comment by SimonSapin** [comment]
@nox that could be good also, but an entirely different feature from Cargo’s `-Z timings` which IMO is about exploring dependencies in the crate graph.

**Comment by alexcrichton** [comment]
I believe this was fixed in https://github.com/rust-lang/cargo/pull/7397 which just hasn't made its way to nightly yet, but let us know if it's still not working after that update hits though!

**Comment by discord9** [comment]
I think there is a regression here now, the following report file(https://gistpreview.github.io/?ecabd731cbe662d562dffe00e39f1465 generate by cargo 1.84.0-nightly (8c30ce536 2024-10-15)) works on chrome 131.0.6778.206, but on firefox 134.0 it still says `Uncaught DOMException: CanvasRenderingContext2D.scale: Canvas exceeds max size.`

**Comment by weihanglo** [comment]
@discord9 are you looking for <https://github.com/rust-lang/cargo/issues/8850>?
