### ISSUE TITLE
Support [profile.*] for setting things across all profiles

### ISSUE THREAD

**Issue by nox** [rust-lang/cargo#7439]
Looking at the ongoing effort to reduce build times across the ecosystem, I've stumbled upon [this](https://github.com/bjorn3/rustc_codegen_cranelift/commit/3a7aa6c0fafa5d0b4954b2b48897db73860da166) commit, which makes `syn` and other build-time dependencies be compiled with no debug info nor optimisations. This is neat, but it only happens for the `dev` profile, whereas AFAICT we don't want to compile `syn` with optimisations even in release mode in this instance. Unfortunately, the Cargo manifest has no way to specify things for multiple profiles at all.

Would it make sense to support something like `[profile.*.blablabla]` to set something across all profiles at once?

**Comment by ehuss** [comment]
There are multiple changes underway that may address this in a way.

[Named profiles](https://github.com/rust-lang/cargo/pull/6989) introduce an inheritance mechanism where profiles can inherit the values from other profiles.

[Build profiles](https://github.com/rust-lang/cargo/pull/6577) will allow you to set a common profile for build scripts and proc macros.

Would those be sufficient to express what you want?

**Comment by nox** [comment]
The build profiles thing seems like it totally supersedes what I want, thanks for the pointer!
