### ISSUE TITLE
Cargo accepts conditional dependencies based on feature, but documented not to

### ISSUE THREAD

**Issue by jsgf** [rust-lang/cargo#7442]
**Problem**
According to the [Cargo documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies):
> Unlike in your Rust source code, you cannot use `[target.'cfg(feature = "my_crate")'.dependencies]` to add dependencies based on optional crate features. Use the [features] section instead.

However, the [tracing](https://github.com/tokio-rs/tracing/blob/930bd731cc30afc26c6d3daabf959b1d97b77574/tracing-core/Cargo.toml#L40-L42) crates are apparently doing this successfully:
```
[target.'cfg(not(feature = "std"))'.dependencies]
spin = "0.5"
lazy_static = { version = "1", features = ["spin_no_std"] }
```

I would expect this to fail.

**Possible Solution(s)**
It's not clear to me whether the code or the documentation is correct.

I encountered this because I'm writing tools to process Cargo metadata which understands platform-specific dependencies, and it failed on encountering a dependency predicated on a feature. I'm not sure if I should implement support for that or not.

**Notes**

Output of `cargo version`:
cargo 1.37.0 (9edd08916 2019-08-02)

**Comment by ehuss** [comment]
That expression is always true, so it is essentially always on, it looks to be a mistake.

Cargo could maybe display a warning about this, though?   I'm not sure, because one can say `RUSTFLAGS='--cfg feature="std"'`, which will enable it.  But that seems somewhat unusual.

**Comment by jsgf** [comment]
@ehuss Ok, so in that context `cfg(feature = "foo")` will always evaluate to false? Does that apply to any unknown predicate?

**Comment by ehuss** [comment]
I believe so.  If it is not in the output of `rustc --print=cfg $RUSTFLAGS`, then it is false.

**Comment by ehuss** [comment]
Closing as warnings are now emitted via #7660.
