### ISSUE TITLE
`cargo doc --open` opens VSCode instead of a browser

### ISSUE THREAD

**Issue by rask** [rust-lang/cargo#7447]
**Problem**

When I invoke

    cargo doc --open

on Ubuntu 18.04 with Chromium and Firefox available, the command decides to open VSCode instead of either of those browsers. Even when Chromium is running, VSCode is opened.

**Steps**

1. Install Ubuntu
2. Install `chromium-browser` and `firefox`
3. Install Rust tooling via rustup
4. Install VSCode
5. Create library crate locally
6. Run `cargo doc --open`

Not sure what else might be required to get a 100% reproduction.

**Possible Solution(s)**

I presume this stems from VSCode being an Electron app (right?) and Cargo somehow detects this as a browser or something?

**Notes**

Output of `cargo version`: `cargo 1.38.0 (23ef9a4ef 2019-08-20)`

**Comment by sfackler** [comment]
Cargo just calls `xdg-open <path_to_index.html>` via https://docs.rs/opener/0.4.0/opener/.

**Comment by rask** [comment]
I see, will try and see if my system is messed up in this regard.

**Comment by rask** [comment]
For reference, this issue was fixed with

    $ xdg-mime default chromium-browser.desktop text/html

**Comment by MechThumbs** [comment]
other solution is to find the file location
index.html (Right Click) - (Properties) - (Open with) - (Change the default app)
