### ISSUE TITLE
'index out of bounds' panic on beta on Travis macOS

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/cargo#7453]
As of yesterday's release, I've started seeing a Cargo panic in my CI, only on macOS hosts with the beta compiler (no repro on nightly):

> thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/tools/cargo/src/cargo/util/cpu.rs:152:29

Here are builds from two different projects demonstrating the panic:

https://travis-ci.org/oconnor663/duct.rs/jobs/590451953
https://travis-ci.org/oconnor663/os_pipe.rs/builds/590452207

**Comment by pnkfelix** [comment]
I saw @RalfJung mention something similar over here: https://github.com/rust-lang/rust/issues/64798#issuecomment-535717566

**Comment by alexcrichton** [comment]
Thanks for the report! This was fixed in https://github.com/rust-lang/cargo/pull/7429 and landed in the rust repo a few hours ago for the beta branch at https://github.com/rust-lang/rust/pull/64814, and the fix should propagate to the beta channel tonight.
