### ISSUE TITLE
CARGO_TARGET_DIR not set for build script on Windows

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#7458]
According to https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads the `CARGO_TARGET_DIR` environment variable should always be set for build scripts. However in https://github.com/servo/servo/pull/24303 we’ve seen `env::var_os("CARGO_TARGET_DIR").unwrap()` intermittently panic with ``Option::unwrap()` on a `None` value``, but only on Windows.

Have you seen something like this before?

Output of `cargo version`: cargo 1.39.0-nightly (ab6fa8908 2019-09-25)

**Comment by nox** [comment]
I think we are misunderstanding our problem, given https://github.com/rust-lang/cargo/pull/7325.

**Comment by SimonSapin** [comment]
Oh, the docs link is in the “variables Cargo *reads*” section.

**Comment by ssrlive** [comment]
As of today, the value of the `CARGO_TARGET_DIR` environment variable that `cargo` returns to me is still `Err(NotPresent)`.
