### ISSUE TITLE
Some tests will fail if one have a local git config user.name/user.email

### ISSUE THREAD

**Issue by hbina** [rust-lang/cargo#7469]
**Problem**

Running `cargo test --all` will fail if you have a local `.git/config`. Link to the log file is here https://gist.github.com/hbina/8b09995b55e95267b3286a99a30a54f2

Specifically, the following unit tests will fail.
```
new::finds_author_email
new::finds_author_git
new::finds_author_user
new::finds_author_user_escaped
new::finds_author_username
new::finds_git_author
new::strip_angle_bracket_author_email
```

**Steps**

1. Clone the repository
2. Set a local `user.name` and/or `user.email`
3. Run test
4. ????
5. No profit!

**Possible Solution(s)**

@ehuss suggested a solution that uses the environment variable `__CARGO_TEST_ROOT`. The following is my attempt to use that. This code could be infinitely better, I guess. Note that this does not actually solve the problem, but some variations of them work (except for one test). I think the problem is with my logic.

```
diff --git a/src/cargo/ops/cargo_new.rs b/src/cargo/ops/cargo_new.rs
index 512eed7e..9ae7ba1d 100644
--- a/src/cargo/ops/cargo_new.rs
+++ b/src/cargo/ops/cargo_new.rs
@@ -698,9 +698,23 @@ fn get_environment_variable(variables: &[&str]) -> Option<String> {
 fn discover_author() -> CargoResult<(String, Option<String>)> {
     let cwd = env::current_dir()?;
     let git_config = if let Ok(repo) = GitRepository::discover(&cwd) {
-        repo.config()
-            .ok()
-            .or_else(|| GitConfig::open_default().ok())
+        let repo_path = repo.path();
+        let cargo_test_root = env::var("__CARGO_TEST_ROOT");
+        match cargo_test_root {
+            Ok(ok) => {
+                if repo_path.starts_with(ok) 

{

+                    GitConfig::open_default().ok()
+                } else {
+                    repo.config()
+                        .ok()
+                        .or_else(|| GitConfig::open_default().ok())
+                }
+            }
+            Err(_) => repo
+                .config()
+                .ok()
+                .or_else(|| GitConfig::open_default().ok()),
+        }
     } else {
         GitConfig::open_default().ok()
     };
```
**Notes**

Output of `cargo version`: `cargo 1.38.0 (23ef9a4ef 2019-08-20)`

**Comment by mathstuf** [comment]
I have a local `user.email` set in my repo and I'm not seeing this. What version of `git` are you using? Can you get a `strace -f -e file` log of running just those tests to see what `.git/config` files it is using (and maybe see how that is getting picked up)?

**Comment by ehuss** [comment]
I'm able to repro it pretty easily by running `git config user.email foo@example.com` to populate `cargo/.git/config`, then `cargo test --test testsuite -- new::`.  It makes sense because [these lines](https://github.com/rust-lang/cargo/blob/0a59a767eded80265c48cea8700ebb8c726fc4f6/src/cargo/ops/cargo_new.rs#L700-L703) hunt for the closest repository which happens to be cargo itself, and then loads the config from there.  Something akin to the given patch should probably work, though I think the starts_with logic may need to be reversed.

**Comment by hbina** [comment]
> Can you get a strace -f -e file log of running just those tests to see what .git/config files it is using (and maybe see how that is getting picked up)?
Sorry, but I don't quite understand this instructions at all...

**Comment by mathstuf** [comment]
Oh, I see. I'm saved because my build tree is off in the weeds on another partition (I do this to keep build artifacts out of my backups).
