### ISSUE TITLE
Support cargo build --load-average / -l like GNU make

### ISSUE THREAD

**Issue by devurandom** [rust-lang/cargo#7480]
**Describe the problem you are trying to solve**

I am trying to limit the load on my system while building Rust software.

**Describe the solution you'd like**

GNU make supports a `make -l4` / `make --load-average=4` parameter, that allows me to limit the target system load to `4` (e.g.). It would be nice, if Cargo would support the same.

**Comment by guanqun** [comment]
I did some quick googling and find this answer: https://stackoverflow.com/a/13355071 . It seems the author prefer using a `-j` option, and in `cargo`, the `-j` option is implemented, do you think you can use that instead to limit the load?

**Comment by devurandom** [comment]
`-j` does not care about the load on the system. Keep in mind that many processes can create load, not just `make` or `cargo`. Spawning many compilation tasks, where each uses `-j N` (or worse, unbounded `-j`), can bring a system to halt. `-l M` prevents that reasonably well.

I think the author of that answer also makes the mistake of passing an unbounded `-j` in combination with `-l`. If one passes a limit as in `-j 6 -l 4`, then `make` will spawn up to 6 processes, but only when the load does not exceed 4.

**Comment by jaccc** [comment]
it would be useful

**Comment by weihanglo** [comment]
Not aware of this issue until today! Seems like it is https://github.com/rust-lang/cargo/issues/8556 with a specific solution in mind
