### ISSUE TITLE
Improve test output

### ISSUE THREAD

**Issue by pbbob** [rust-lang/cargo#7485]
As it stands `cargo test` currently has very bloated output of which the majority of it is useless.
There is a lot of stuff that is printed out during tests and we should really try to clean up the cargo test output to minimize junk.

**Comment by ehuss** [comment]
Thanks for the report, though this issue as-is isn't really actionable.

To produce less output, `-q` may be used.  

[Custom test frameworks](https://github.com/rust-lang/rust/issues/50297) are a way towards getting a parseable output which can be processed and aggregated.  [JSON output](https://github.com/rust-lang/rust/issues/49359) is already implemented.

There are also a number of other issues regarding test output and aggregation, such as #2832, #4324, #5089.

I think making progress on the JSON output is the most applicable route here, though AFAIK there hasn't been much movement on test frameworks in general.  Also, major changes in the interface for tests will likely need to go through an RFC process (although given the lack of momentum for custom test frameworks, that might be difficult at this time).

Closing for now, with the given items above already tracking this and other ways to address this.
