### ISSUE TITLE
"cargo clean" puts lock on package cache

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#7490]
**Problem**
`cargo clean` puts a lock on the package cache (cargo home) but I think it should not need it at all?

**Steps**

1. Have `cargo fetch` of some git repo run on project 1.
2. Try to `cargo clean` a different repo at the same time
=>
`    Blocking waiting for file lock on package cache`

**Possible Solution(s)**
I don't really see why we need to take the `$CARGO_HOME` lock into account here, after all we only need to `rm -rf target`..?

**Notes**

Output of `cargo version`:
`cargo 1.40.0-nightly (8b0561d68 2019-09-30)`

**Comment by ehuss** [comment]
I think it would be fine to move [this line](https://github.com/rust-lang/cargo/blob/aa4820bb8749f1487b3a195d9d1fdb85c066f531/src/cargo/ops/cargo_clean.rs#L42) below line 63 if you want to fix this.

**Comment by matthiaskrgr** [comment]
Thanks!
