### ISSUE TITLE
`cargo fix` should respect allow directives

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/cargo#7498]
**Problem**
Consider the following example trait
```rust
pub trait MyTrait {
    #[allow(unused_variables)]
    fn overridable_fn(&mut self, val1: u8) {}
}
```
Here we are providing a function that by default does nothing, allowing but not forcing the user to override it.

To get nicer docs, we don't prefix the name of the variable with a `_`, instead opting to opt-out of the `unused_variables` lint for this item.

When you run `cargo fix` (--version 1.36.0 c4fcfb725), it comments out the directive for the lint and adds an underscore. It should instead respect the opt-out and ignore this unused variable.

**Comment by derekdreery** [comment]
I'm sorry if this bug report comes across as brash - I wanted it to be clear as possible. Please believe me that I am very polite in RL :D

**Comment by ehuss** [comment]
Hm, I can't reproduce the issue with the sample code.

```shell
> cargo new --lib f
> cd f
> rm src/lib.rs
> cat >> src/lib.rs <<EOL
pub trait MyTrait {
    #[allow(unused_variables)]
    fn overridable_fn(&mut self, val1: u8) {}
}
EOL
> cargo +1.36.0 fix
> cat src/lib.rs
pub trait MyTrait {
    #[allow(unused_variables)]
    fn overridable_fn(&mut self, val1: u8) {}
}
```

> I'm sorry if this bug report comes across as brash

No worries! It didn't come across that way at all to me.

**Comment by derekdreery** [comment]
Urgh now I can't reproduce either. Sorry to take up your time!
