### ISSUE TITLE
cargo 0.39 incorrectly published

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#7503]
The cargo 0.39.0 crate on crates.io is not the correct version.  It looks like 0.38 was uploaded with just the version changed.

I'm not sure what the best way to fix this is.  We could publish 0.38.1, but that would break anyone depending on 0.38.  Or we could 🤷‍♂ and just wait 4 weeks for the next release?  I don't think there is much we can do.

cc @pietroalbini @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
This is probably my fault. I guess I checked out the wrong commit? I think we should probably just wait -- there's not much we can do here, to some extent. There's no version under the "0.39.0" namespace that is incompatible, right? Like we can't do "0.39.0+actual" or something.

**Comment by ehuss** [comment]
A pre-release version (`-foo`) would prevent "^0.39" dependencies from matching, but it's kinda the opposite of the intent of a pre-release, and are somewhat buggy in Cargo.  I'm fine with waiting unless anyone has any other thoughts, a minor 6-week hiccup isn't too painful.  The reason I noticed it was because `cargo tree` doesn't work in the rustc repo with the new `Cargo.lock` format, but the rust repo should be the only one using it right now.

**Comment by alexcrichton** [comment]
Agreed it's fine to probably just let this slide unless someone specifically requests it. We can always do something like an 0.39.1 release if necessary.

**Comment by ehuss** [comment]
I'm going to close this, as there's not much we can do.
