### ISSUE TITLE
also read cargo.toml

### ISSUE THREAD

**Issue by hlb-schmidt** [rust-lang/cargo#7505]
https://doc.rust-lang.org/cargo/faq.html#why-cargotoml

## "Sorting files often puts capital letters before lowercase letters"

could you please provide your analysis on how you count "often"?

cause its not with coreutils 8.31, `ls`:
```
$> touch foo Foo bar Bar
$> \ls
bar  Bar  foo  Foo
```

nor `sort`:
```
$> \ls | \sort
bar
Bar
foo
Foo
```

> `\` is used here to bypass aliases.

## "ensuring files like Makefile and Cargo.toml are placed together"

did you know that `make` also reads `makefile`?

so please follow `make`s lead and also read `cargo.toml`.

**Comment by sinkuu** [comment]
An example of where "capital letters before lowercase letters" sorting is done is Github.

**Comment by hlb-schmidt** [comment]
i'm sorry, i should not have brought this up (again, it seems. was hard to find old tickets cause github has no case-sensitive search, the irony...).

FWIW, why do i get angry about a single character?!
i guess it comes from my "artistic" side...
i like it when my source tree looks clean:

```
doc/
src/
cargo.toml
makefile
readme.md
```

and when theres something odd, i get angry:
```
doc/
src/
Cargo.toml
makefile
readme.md
```
thats a freaking tomato stain on a table to me!

hmm, maybe i should start to use capital letter everywhere:
```
Doc/
Src/
Cargo.toml
Makefile
Readme.md
```

but wait, now the semantics are all wrong!
this should be the ultimate naming convention:
```
Doc/
Source/
Cargo.TOML
MakeFile
ReadMe.MD
```

;P

sorry for the noise, i'm an idiot.
