### ISSUE TITLE
Cargo: unnecessary rebuilds

### ISSUE THREAD

**Issue by brightlandco** [rust-lang/cargo#7514]
**Problem**

**cargo test** causes a rebuild of unchanged files.

**Steps**

For a reasonably large project with multiple sub-crates etc:

1. cargo test
2. cargo test
3. cargo test

Each time cargo rebuilds files before running tests- major time waste (doesn't happen for small projects).

**Possible Solution(s)**

Delta checking / dependency system isn't working?

**Notes**

Output of `cargo version`:

cargo 1.38.0 (23ef9a4ef 2019-08-20)

**Comment by ehuss** [comment]
Can you provide more details or a reproduction?  I would look for a misbehaving build script.

You can also run with the `CARGO_LOG=cargo::core::compiler::fingerprint=trace` environment variable to get some logging information which explains why cargo thinks it needs to be rebuilt.

**Comment by ehuss** [comment]
I'm going to close this for now.  If you can provide more detail, feel free to reopen.
