### ISSUE TITLE
./source/ as alias for ./src/

### ISSUE THREAD

**Issue by sivizius** [rust-lang/cargo#7516]
**Describe the problem you are trying to solve**

The project-directory contains or may contain certain directories like ./benches/, ./examples/, ./target/, ./tests/ (see [here](../blob/master/src/doc/src/guide/project-layout.md)) … and ./src/, which is the only directory that is abbreviated. On the other hand, ./src/ is the directory in some other languages and for a long time now the source-directory in cargo. Therefore, replacing is a bad idea.

**Describe the solution you'd like**

I suggest to load source-files from ./source/ if, and only if, ./src/ is not present.

**Notes**

I suggest to make this the default in a far future.

**Comment by ehuss** [comment]
Thanks for the feedback.  However, I think this is something that we would be unlikely to change.

If you want to use a different directory, you can specify them in the bin and lib targets via the [path key](https://doc.rust-lang.org/cargo/reference/manifest.html#configuring-a-target).
