### ISSUE TITLE
Cargo.toml: include = [] missing some specified paths

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#7518]
**Problem**
````toml
include = []
````
is not actually including all specified files.

**Steps**

I have a crate that contains an otherwise unreferenced subcrate.
When I set it to be included in the `.crate` via `Cargo.toml`s `include` key:
````toml
include = ["*", "/subcrate"]
````
It does not end up in the `.crate` archive generated by `cargo package`.

**Possible Solution(s)**
`include = [...]` should work on all specified files or directories.

Output of `cargo version`:
cargo 1.40.0-nightly (a429e8cc4 2019-10-04)

**Comment by ehuss** [comment]
It is intentional that a `.crate` only includes one package.  Can you say more about why you want another package included?

**Comment by matthiaskrgr** [comment]
I want to ship an optional binary with my crate that is not installed by default (`cargo install`) but only when explicitly specified (`cargo install rootcrate subcrate`).
The subcrate shares functionality with the root crate but cannot depend on it as that would bloat compiletime from 2 seconds to several minutes.

**Comment by ehuss** [comment]
We probably won't extend crate files to include multiple packages.  `cargo install` already supports the ability to specify multiple crates, so I'm not sure I understand the difference.  Can't they be published separately?

**Comment by ehuss** [comment]
Without more detail, I don't think this is actionable.  I don't think we will allow a `.crate` to include multiple packages.  There might be other ways to address what you are trying to do, but there's not enough detail here.  If you want to include a more detailed description of how the packages are related (preferably a concrete example) and the problem this is trying to solve (build times?), feel free to comment.
