### ISSUE TITLE
Local dependencies- `~` and `$HOME` not recognized

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/cargo#7528]
This isn't a feature request as much as a question (didn't want to file as a bug)- how do I mention a dependency that depends on a local path relative to $HOME?

I've tried both: 

```toml
[dependencies]
debug = { path = "$HOME/workspace/rust/debug/" }
```

and 

```toml
[dependencies]
debug = { path = "~/workspace/rust/debug/" }
```

but `cargo` complains in both cases. Is there anything else I could do?

**Comment by ehuss** [comment]
It's currently not possible, cargo doesn't do any sort of interpretation of the path.  These paths are typically used as relative to the current project.  For absolute paths, it is intended to use the full path since it will be specific to the machine it is running on.
