### ISSUE TITLE
Set `cc` for rustdoc

### ISSUE THREAD

**Issue by nmattia** [rust-lang/cargo#7529]
**Describe the problem you are trying to solve**

I can't find a way to set the `cc` for `rustdoc`.

`CARGO_TARGET_XXX_LINKER` is not passed, and it appears that `rustdoc` reacts neither to `CARGO_BUILD_RUSTFLAGS=-C linker=/path/to/cc` nor to `CC=/path/to/cc`. One solution may be to set `RUSTDOCFLAGS=-Z unstable-options --linker=/path/to/cc` but this is only enabled on nightly, which I don't have.

**Describe the solution you'd like**

It would be great for cargo to forward `CARGO_TARGET_XX_LINKER` to `rustdoc`, where `XXX` is the `CARGO_BUILD_TARGET`.

**Comment by ehuss** [comment]
1.39 will now allow `-C linker=cc` (see https://github.com/rust-lang/rust/pull/63834).  Cargo doesn't issue that flag, though, so you'll still need to use `RUSTDOCFLAGS`.

What is your use case for passing a custom linker?  Doctests don't support cross-compiling without the unstable `-Zdoctest-xcompile`, so I'm curious why the default host linker is not working for you.

With `-Zdoctest-xcompile`, it seems like a reasonable idea to pass that flag, but I'm not too familiar with the use cases for using custom linkers with doc tests.

**Comment by nmattia** [comment]
Thanks for the feedback! Looking forward to 1.39.

> What is your use case for passing a custom linker? 

I work on systems that unfortunately do not have a `cc` in the path or in any standard location.

**Comment by benesch** [comment]
Also, sometimes linkers have bugs. For example binutils 2.30 (shipped with Ubuntu 18.04 LTS) mishandles some compressed debug info sections: https://sourceware.org/bugzilla/show_bug.cgi?id=23919.

We work around this at Materialize by setting `CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER` appropriately, to a toolchain that does not exhibit the bug, but the fact that this setting does _not_ apply to rustdoc links is very surprising! Here's a build failure that took me well over an hour to track down: https://buildkite.com/materialize/tests/builds/7669#e8398bc6-91d4-4130-b417-be4233dfcfd8.

So even when you're not cross compiling, I think it's important that `CARGO_TARGET_<HOST TRIPLE>_LINKER` apply to rustdoc too.
