### ISSUE TITLE
Extra trailing new-line at the end of Cargo.lock

### ISSUE THREAD

**Issue by petervaro** [rust-lang/cargo#7537]
**Problem**

I updated my toolchain (and unfortunately I don't know what the previous version was) and with the latest `cargo` every time it touches the `Cargo.lock` it adds 2 new-lines at the end of the file.  (Just to be clear: it does not append 2 new-lines every time but the end result of the generation is 2 new-lines at the end of the file.)

The expectation is to have a single new-line at the end of the file.

**Steps**

1. Delete `Cargo.lock` and possibly the `target` folder
2. Run `cargo build|run|test` commands
3. Inspect `Cargo.lock`

**Notes**

Output of `cargo version`: `cargo 1.38.0 (23ef9a4ef 2019-08-20)` but the same happens with `cargo 1.40.0-nightly (3a9abe3f0 2019-10-15)` as well

**Comment by ehuss** [comment]
I think this is somewhat intentional.  Cargo has historically had a blank line at the end.  There was an accidental regression on beta/nightly back in August (#7262) where it removed the blank line, but it was reverted for the stable release.  Perhaps your lock file came from during that time?

There will be a new lock file format on the horizon, which removes the pesky blank line.

**Comment by petervaro** [comment]
@ehuss It did, indeed!  The new format is wonderful news.  Just out of curiosity, what possible advantage could the extra line at the end of the file has?

**Comment by ehuss** [comment]
> what possible advantage could the extra line at the end of the file has?

There is none that I know of, I think it was just an artifact of how it was initially implemented.  The PR mentioned above keeps the old style just so it doesn't cause needless churn for people who check the lock file into source control.

**Comment by petervaro** [comment]
>  [...] it doesn't cause needless churn for people who check the lock file into source control.

Oh, the irony, 'cause that's exactly what have happened the other way around :stuck_out_tongue_closed_eyes:   Anyway, cheers for the heads up!
