### ISSUE TITLE
Wrong message in a cyclic dependency scenario

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/cargo#7538]
**Scenario**

Project `A` has a `Foo` trait and project `B` has a `Bar` trait. `Foo` has the `Bar` bound associated with it (`Foo: Bar`), therefore, project `A` depends on project `B` (`[dependencies]
b = { path = "../b" }`). Now, project `B` depends on project `A` as a development dependency (`[dev-dependencies] a = { path = "../a" }`) and the following code:

```rust
#[cfg(test)]
mod tests {
    struct Something;
    impl crate::Bar for Something {}
    impl a::Foo for Something {}
}
```

Triggers an erroneous message of this cyclic dependency: `the trait 'a::Foo' is not implemented for 'tests::Something'`.
Not sure if cyclic dependencies are allowed with development crates but the showed message in this case is obviously wrong.

**Notes**

Output of `cargo version`: cargo 1.40.0-nightly (a429e8cc4 2019-10-04)

**Comment by ehuss** [comment]
Thanks for the report. I think this is essentially the same as #6765, so I'm going to close in favor of that.

**Comment by c410-f3r** [comment]
Thanks. They are indeed the same
