### ISSUE TITLE
cargo test: --include-ignored flag is broken

### ISSUE THREAD

**Issue by murlakatamenka** [rust-lang/cargo#7540]
**Problem**

The flag `--include-ignored` of `cargo test` is currently broken (`cargo` 1.38/1.40 stable/nightly)

**Steps**

```sh
cargo test -- --include-ignored
# or
cargo +nightly test -- --include-ignored
```

**Short screencast**

[![asciicast](https://asciinema.org/a/276756.svg)](https://asciinema.org/a/276756)

**Comment by ehuss** [comment]
You have to pass the `-Zunstable-options` flag.  That is a bit confusing, so I opened https://github.com/rust-lang/rust/issues/65770.  (libtest issues are tracked on https://github.com/rust-lang/rust/issues/)

**Comment by rexhoffman** [comment]
I guess there's a nightly --include-ignored       https://github.com/rust-lang/cargo/issues/7540
