### ISSUE TITLE
default-features = false -> does not work.

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/cargo#7545]
Configure a dependency to be compiled with default-features = false. Example:
num-traits = { version = ">=0.2.0", default-features = false }

Compile with: cargo --verbose build --target thumbv7m-none-eabi

What currently happens:
   Compiling num-traits v0.2.8
     Running `rustc --crate-name num_traits /home/mswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.8/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=616873d37e025f24 -C extra-filename=-616873d37e025f24 --out-dir '/mnt/sdb2/@home/mswanson/src/stm32/rust-compression/target/thumbv7m-none-eabi/debug/deps' --target thumbv7m-none-eabi -L 'dependency=/mnt/sdb2/@home/mswanson/src/stm32/rust-compression/target/thumbv7m-none-eabi/debug/deps' -L 'dependency=/mnt/sdb2/@home/mswanson/src/stm32/rust-compression/target/debug/deps' --cap-lints allow --cfg has_i128`

I would expect the --cfg feature parts to _not_ include the default "std".
However, rustc is attempting to include "std".

Output of `cargo version`:
cargo 1.40.0-nightly (a429e8cc4 2019-10-04)
(This happens with a cargo that is 6 months older too)

**Comment by Mark-Simulacrum** [comment]
Can you post a full Cargo.toml and Cargo.lock? Do you have other dependencies?

**Comment by MarkSwanson** [comment]
Hopefully this saves you or other folks some time. I created a tiny test repo here:
git clone git@github.com:MarkSwanson/cargo_default_features.git

The README.md shows how to trigger the problem: cargo --verbose build --target thumbv7m-none-eabi

The repo contains the Cargo.toml and Cargo.lock as well. Also pasted next:

* Cargo.toml:
[package]
authors = ["Mark Swanson <mark.swanson.sw@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "cargo_default_features"
version = "0.0.1"

[dependencies]
num-traits = { version = ">=0.2.0", default-features = false }

[[bin]]
name = "cargo_default_features"

* Cargo.lock
[[package]]
name = "autocfg"
version = "0.1.7"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "cargo_default_features"
version = "0.0.1"
dependencies = [
 "num-traits 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "num-traits"
version = "0.2.8"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "autocfg 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)",
]

[metadata]
"checksum autocfg 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" = "1d49d90015b3c36167a20fe2810c5cd875ad504b39cff3d4eae7977e6b7c1cb2"
"checksum num-traits 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)" = "6ba9a427cfca2be13aa6f6403b0b7e7368fe982bfa16fccc450ce74c46cd9b32"

**Comment by alexcrichton** [comment]
Thanks for the report! This is likely due to Cargo's unioning behavior of features so just because you disable a feature doesn't mean that everyone disabled the feature. I believe Cargo is working as expected here, so I'm going to close.
