### ISSUE TITLE
Span information for errors

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#7548]
It would be cool if Cargo could supply library users with span information when there is an error. RLS for example has to underline the entire file (using vscode) becuase it has no details, even though only one dependency could have an error.

![Screenshot_20191028_165522](https://user-images.githubusercontent.com/8872119/67695338-2825d980-f9a5-11e9-8696-a3f1dc77c1c3.png)

See also https://github.com/rust-lang/rls/issues/1581

The span could also be printed for CLI users, but the feature can be lib-only as well.

**Comment by epage** [comment]
With RLS dead, is anyone still requesting this or should we close this?

**Comment by est31** [comment]
> The span could also be printed for CLI users

In general, it would be good if cargo could start printing spans, and point users to the cause of errors.

**Comment by est31** [comment]
What I'm trying to say is, #6144 was closed as RLS related, and while this issue used RLS in its example to make it clear what the issue means to end users, it also exists just as well with rust-analyzer. In fact, there the issue is even worse, as rust-analyzer shows it as an "internal error" of sorts, instead of listing it in the compilation errors.

**Comment by epage** [comment]
This issue is also scoped to cargo-as-a-library which I don't think rust-analyzer uses.  Without concrete users to give feedback on a feature request (RLS being the previous one), I don't see value in keeping an issue on this open.

**Comment by epage** [comment]
btw if we re-opened anything, I would expect it to be the other issue as it has more discussion on the matter (even though its not much)

**Comment by est31** [comment]
> This issue is also scoped to cargo-as-a-library which I don't think rust-analyzer uses

Good point, rls uses cargo-as-a-library: https://github.com/rust-lang/rls/blob/master/Cargo.toml#L34 , but I couldn't find any library use of cargo in rust-analyzer.

Maybe it might make sense to file a new issue as the rust-analyzer case is too different, instead of repurposing the rls one. There is a lack in how nice IDEs are to users when it comes to cargo level errors. So I think an issue should be open in cargo for adding span info to diagnostics (if there isn't one already).
