### ISSUE TITLE
Make it possible to override values in Cargo.toml from external source

### ISSUE THREAD

**Issue by magnusart** [rust-lang/cargo#7554]
**Describe the problem you are trying to solve**
I wish to be able to set cargo package version from an external source. Maybe I'm ignorant but I could not figure out how to do this.

My use case is to correlate artifacts built with CI to specific commits. These artifacts I typically store for a longer period of time.

Example of a custom version would be running `git describe --always --dirty --abbrev=7 --tags` which could result in something like `1.0.0-RC1-10-g0a51bc6` (ten commits since git tag `1.0.0-RC1` with hash `g0a51bc6`).
 
**Describe the solution you'd like**
I would have expected to be able to do something like `println!("cargo:package-version={}", myCustomVersion);` in `build.rs`. Being able to override values in `Cargo.toml` I assume is a general use case.

**Comment by Kaiser1989** [comment]
Similar to this one:
https://github.com/rust-lang/cargo/issues/6583

**Comment by epage** [comment]
While the title is generic, motivation and use cases are only for version.  I'm going to close in favor of #6583 so we can keep all of the conversation around that in one place.  If there is a reason we should reconsider this, let us know!
