### ISSUE TITLE
Mixing proxy and non-proxied crates

### ISSUE THREAD

**Issue by swfsql** [rust-lang/cargo#7561]
Hello! (I don't know much of this subject),
At work I've been trying to use Rust and the policy there is as follows: we do need a *proxy* setup to get to github; and we need a *no-proxy* setup to get to our internal git server. 

But projects usually depend on both internal projects and github projects.
When an internal dependency is updated, `cargo fetch` usually doesn't work - with or without a *proxy* setup. When on a *no-proxy* setup, it fails to update the registry. When on a *proxy* setup, it is barred from the internal git server.

I've tried many times, with both settings (*proxy* and *no-proxy*), and vice-versa, and then also trying `--offline` on all situations, and there are times that it still doesn't work. Then I proceed to comment-out all crates from `Cargo.toml` which are not internal, and in a *no-proxy* setup, run a `cargo check` until it fetches and then starts to build and then errors'. Then I un-comment the github crates and run again in a *proxy* setup - and then it does work.

I really don't know if this is an overall configuration flaw (or bad decision) from the company-side on the proxy setting, but would you have some ideas on improvement? Thanks a lot!

**Comment by alexcrichton** [comment]
Currently Cargo doesn't support a mixed configuration where some hosts use a proxy and others don't, but this sounds like a feature that can be added!

**Comment by gilescope** [comment]
**cough** your internal server could be http and external be https? That would allow you to configure both. It's a hack but it's quite a neat one!

**Comment by swfsql** [comment]
@gilescope Thanks for the idea! I think they could be!

I reality I didn't update on this issue, but the proxy setup changed (in overall), and now they made it work under a proxied setup even when accessing the company's internal content! So I stoped having this proxy issue! (don't know if others would still encounter this though..)

Well, I guess I'm closing then! 
Thanks once again!
