### ISSUE TITLE
Option to emit relative paths in cargo vendor

### ISSUE THREAD

**Issue by jsgf** [rust-lang/cargo#7562]
`cargo vendor somedir` will always put an absolute path in the emitted `.cargo/config.toml`:
```
[sources.vendored-sources]
directory = "/full/path/to/somedir"
```

This path might be OK at vendoring time, but if it is committed along with the vendored sources (so the they can all be tracked in source control), the absolute path is meaningless if checked out at a different path.

The goal would be to make sure that if packages are vendored and committed at one path, the whole repo can be checked out elsewhere at a different path and the vendored sources can be used transparently.

I'd like `cargo vendor` to have an option to make sure all paths are relative to the Cargo.toml/lock so it is all relocatable to a different directory without needing any changes.

The [Source Replacement](https://doc.rust-lang.org/nightly/cargo/reference/source-replacement.html#configuration) documentation uses relative paths for its examples, so I assume there's no problem in principle with the mechanism. It's just a question of what `cargo vendor` emits.

**Comment by ehuss** [comment]
I think this is essentially #7316, so I'm going to close in favor of that.  I think it should probably be a relative path, but it is inadvertently using an absolute path in some cases.
