### ISSUE TITLE
cargo --version date/hash do not match expected values

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/cargo#7567]
**Problem**

The date and commit of `cargo version` do not match.

According to https://github.com/rust-lang/cargo/releases 1.39.0 should have a date of `2019-09-26` and a commit hash of `23ef9a4`.

BUT

https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-139-2019-11-07 Says `2019-11-07` with a hash of `4b105b6a`

`cargo version --verbose` shows 

```
cargo 1.39.0 (1c6ec66d5 2019-09-30)
release: 1.39.0
commit-hash: 1c6ec66d5bae40e9dfd2fb82f091b5172c212d73
commit-date: 2019-09-30
```

**Steps**

1. Run `cargo --version`

**Possible Solution(s)**

**Notes**

Output of `cargo version`: cargo 1.39.0 (1c6ec66d5 2019-09-30)

Windows 10, stable rust 1.39

$ cargo --version --verbose
cargo 1.39.0 (1c6ec66d5 2019-09-30)
release: 1.39.0
commit-hash: 1c6ec66d5bae40e9dfd2fb82f091b5172c212d73
commit-date: 2019-09-30

**Comment by ehuss** [comment]
Thanks for the heads up.  There are a few things here:

- The date in `--version` is the date of the last commit.  The last commit on the 1.39 release was 1c6ec66d5bae40e9dfd2fb82f091b5172c212d73 on Sep 30th: https://github.com/rust-lang/cargo/commits/rust-1.39.0

- Cargo-the-library has a version number that is different from the CLI release.  Rust 1.39.0 corresponds to the cargo library version of 0.40.0.

- The Changelog is not usually updated for every patch during beta.  I'll update it to the correct hash (1c6ec66d5bae40e9dfd2fb82f091b5172c212d73) when I write the 1.40 release notes (usually happens a few days after release).
