### ISSUE TITLE
Documentation doesn't explain where the cargo config file is on Windows.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/cargo#7571]
<https://doc.rust-lang.org/cargo/reference/config.html>

Gives the following list:

* /projects/foo/bar/baz/.cargo/config
* /projects/foo/bar/.cargo/config
* /projects/foo/.cargo/config
* /projects/.cargo/config
* /.cargo/config
* $CARGO_HOME/config ($CARGO_HOME defaults to $HOME/.cargo)

Yet on windows neither of the two suggested path variables seem to exist:

```
D:\dev\terbium>echo %CARGO_HOME% 
%CARGO_HOME%

D:\dev\terbium>echo %HOME%       
%HOME%
````

The actual `.cargo` directory seems to be located in `C:\Users\<username>\.cargo`, so that should be mentioned.

**Comment by ehuss** [comment]
Yea, $HOME is usually %USERPROFILE% on windows, seems reasonable to mention that!
