### ISSUE TITLE
Starting with cargo 1.37 I'm getting error: could not find `Cargo.toml`

### ISSUE THREAD

**Issue by psumbera** [rust-lang/cargo#7572]
I'm using cargo-vendor to vendor sources for later offline build. It worked like this:
1. mkdir rustc-1.38.0-src-vendored-sources 
2. cd rustc-1.38.0-src-vendored-sources
3. tar xf /data/rustc-1.38.0-src.tar.xz
3. cargo vendor -s rustc-1.38.0-src/Cargo.lock

But newly with cargo 1.37 I'm getting: error: could not find `Cargo.toml`

```
gtar xf rustc-1.38.0-src.tar.xz -C /builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources; \
cd /builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources/rustc-1.38.0-src; \
  for i in `find /builds/psumbera/userland-rust/components/rust/rustc/patches -name '*.patch'` ; do gpatch -p1 < $i; done
cd /builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources; PATH=/builds/psumbera/cargo-vendor-0.1.23/bin:/builds/psumbera/rustc-1.37.0/bin/:/usr/gnu/bin:/usr/bin \
  CARGO_HOME=/builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources/.cargo cargo vendor -s rustc-1.38.0-src/Cargo.lock
error: could not find `Cargo.toml` in `/builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources` or any parent directory
```

--

Any idea what have changed and how should I modify my procedure? Thanks!

**Comment by ehuss** [comment]
`cargo vendor` was changed so that the `--sync` flag only accepts `Cargo.toml` files, not `Cargo.lock` files.  Can you update your script to use `-s rustc-1.38.0-src/Cargo.toml` instead?

**Comment by psumbera** [comment]
Thanks for looking at it. But it doesn't make any difference:

```
ul11u4x-0 09:22 /builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources: PATH=/builds/psumbera/cargo-vendor-0.1.23/bin:/builds/psumbera/rustc-1.37.0/bin/:/usr/gnu/bin:/usr/bin   CARGO_HOME=/builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources/.cargo cargo vendor -s rustc-1.38.0-src/Cargo.toml
error: could not find `Cargo.toml` in `/builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src-vendored-sources` or any parent directory
```

**Comment by ehuss** [comment]
Oh, I see the `sync` flag was changed so that it adds to the current workspace, instead of replacing it.  Maybe `--manifest-path=rustc-1.38.0-src/Cargo.toml` is what you are looking for.  However, I'm not sure why you are re-vendoring the sources in the first place since the source tarball already includes them.

**Comment by psumbera** [comment]
Good point. I can see now that there is rustc-1.38.0-src/vendor directory with vendored sources. I see it was present from version 1.32.

But still by default it seems to download dependencies from internet.

```
make[1]: Entering directory '/builds/psumbera/userland-rust/components/rust/rustc/build/amd64'
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to connect to github.com: Network is unreachable; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Network is unreachable; class=Os (2)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`
```

Though adding following into cargo config file will use bundled vendored sources:

```
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "/builds/psumbera/userland-rust/components/rust/rustc/rustc-1.38.0-src/vendor"
```

**Comment by ehuss** [comment]
I'm going to close this, as this seems like an interaction between rustc's build system and some local patches.  And it sounds like you've figured out what you need to do.
