### ISSUE TITLE
failed to find branch with dash

### ISSUE THREAD

**Issue by ctaggart** [rust-lang/cargo#7581]
**Problem**

I was working on https://github.com/BurntSushi/ripgrep/pull/1427 by adding this to `Cargo.toml`:
``` toml
[replace]
"ignore:0.4.10" = { git = "https://github.com/ctaggart/ripgrep", package = "ignore", branch = "crossbeam-channel" }
```

This fails with:
```
    Updating git repository `https://github.com/ctaggart/ripgrep`
error: failed to load source for a dependency on `ignore`

Caused by:
  Unable to update https://github.com/ctaggart/ripgrep?branch=crossbeam-channel

Caused by:
  failed to find branch `crossbeam-channel`

Caused by:
  cannot locate local branch 'crossbeam-channel'; class=Reference (4); code=NotFound (-3)
```

The branch definitely exists https://github.com/ctaggart/ripgrep/branches. I created another without the `-channel` and it works.

**Notes**

Output of `cargo version`:
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)

**Comment by sfackler** [comment]
Your branch name is `crosssbeam-channel`, not `crossbeam-channel`.

**Comment by ctaggart** [comment]
Thank you @sfackler. I works fine. This is not a bug, just a typo that I failed to see.
