### ISSUE TITLE
Explicit support for whole-archive linker option

### ISSUE THREAD

**Issue by leeopop** [rust-lang/cargo#7586]
1. The problem

Some libraries using `__attribute__((constructor))` suffers when their libraries are not linked via `whole-archive` linker option.
However, current cargo build script does not support this functionality.

2. Alternatives

We may use `RUSTFLAGS` option to give custom linker option, however I expect that this is not a desired use case of cargo.

`whole-archive` is not needed when dynamically loading a shared library.
(the loader explicitly invoke the constructor function)
(in static linking case, linker finds no explicit linkage so that the library is omitted)

3. Solution

Add another link type to cargo's `link-lib` list.
Currently, we have `static`, `dylib`, and `framework`.
As whole-archive works on static linking case, we may name it as `static-whole`.

e.g. `cargo:rustc-link-lib=static-whole=foo` at the build script.

I'm aware of the risk when the linker flag is fully open.
I expect that this is the reason why linker flags are not open to build scripts.
Thus, I suggest to explicit support a single type of linking: `static-whole` along with other specialized link types.

4. Implementation strategy

Cargo internally manages the `static-whole` database.
At the final linking state, cargo opens a `whole-archive`, listing all `static-whole` libraries from the depending crates, and closes `whole-archive`.

**Comment by leeopop** [comment]
ping @alexcrichton @ehuss 

My previous writing is not that clear.
To be more specific, I would like to propose a concrete abstraction for the `--whole-archive` compiler option.

**Comment by leeopop** [comment]
Here is an example of possible workaround of this topic.
https://github.com/ANLAB-KAIST/rust-dpdk/blob/master/Dockerfile#L44

However, I think it is better to have this feature as standard cargo options.

**Comment by dcsommer** [comment]
@ehuss I think this issue can be closed now that 53ec56cbae80c6001df62958802809466de115e5 is in?

**Comment by ehuss** [comment]
Seems like it, thanks!

**Comment by dcsommer** [comment]
Just a note: there are still some issues with whole archive linking. However, the issues are on the rustc side, not cargo. See:
* https://github.com/rust-lang/rust/issues/73632
* https://github.com/rust-lang/rust/issues/99429
* https://github.com/rust-lang/rust/issues/100066
