### ISSUE TITLE
failed to select a version for `rust_hawktracer_sys` error

### ISSUE THREAD

**Issue by vaishnavsivadas** [rust-lang/cargo#7592]
I have been trying to build the project rust_hawktracer but this conflict with dependency version keeps on showing up which is failing the build.

Here is the error log which I get: 

```   vaishnav@ubuntu ~/rust_hawktracer> cargo build
    Updating crates.io index
error: failed to select a version for `rust_hawktracer_sys`.
    ... required by package `rust_hawktracer_normal_macro v0.1.0`
    ... which is depended on by `rust_hawktracer v0.5.0 (/home/vaishnav/rust_hawktracer)`
versions that meet the requirements `^0.1` are: 0.1.0

the package `rust_hawktracer_sys` links to the native library `hawktracer`, but it conflicts with a previous package which links to `hawktracer` as well:
package `rust_hawktracer v0.4.0`
    ... which is depended on by `rust_hawktracer v0.5.0 (/home/vaishnav/rust_hawktracer)`

failed to select a version for `rust_hawktracer_sys` which could resolve this conflict
```
This is the content of Cargo.toml file:

```[package]
name = "rust_hawktracer"
version = "0.4.0"
authors = ["Alexandru Ene <alex.ene0x11@gmail.com>"]
description = "Rust bindings for hawktracer profiling library."
keywords = ["profiling"]
categories = ["development-tools::profiling"]
repository = "https://github.com/AlexEne/rust_hawktracer"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies.rust_hawktracer]
version="0.4.0"
features = ["profiling_enabled", "generate_bindings"]

[build-dependencies]
cmake = "0.1"

[features]
profiling_enabled = ["rust_hawktracer_normal_macro/profiling_enabled", "rust_hawktracer_proc_macro/profiling_enabled"]
generate_bindings = ["rust_hawktracer_normal_macro/generate_bindings"]

[dependencies.rust_hawktracer_normal_macro]
version = "0.1"

[dependencies.rust_hawktracer_proc_macro]
version = "0.1"
```

**Comment by ehuss** [comment]
I'm a bit confused by your example, it looks like you are creating a package named `rust_hawktracer` that depends on a package with the exact same name?

Also, your error message doesn't match with the example manifest you show. It mentions `rust_hawktracer v0.5.0`, but you haven't listed that version anywhere.  Is the example maybe different from what you used? I notice it is also missing the `[package]` line.

Also, it looks like `rust_hawktracer_normal_macro` is not intended to work with `rust_hawktracer` 0.4, but maybe the upcomping 0.5 release?  

---

The error is basically telling you, only one package can link against the C library `hawktracer`.  But you have two: `rust_hawktracer 0.4` and `rust_hawktracer_sys 0.1`.  It looks like you are mixing version 0.4 and 0.5 at the same time.

**Comment by vaishnavsivadas** [comment]
I understood the mistake, thanks for the reply. Got a bit confused following the documentation which caused the issue.
