### ISSUE TITLE
Cargo can not install to /sbin or /libexec

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/cargo#7598]
**Problem**
Cargo install currently emits binaries to a pattern such as:

```
$root/bin/$exec_name
```

This causes a problem when attempting to package for a platform - we may not want everything in $prefix/bin. We may want to use /sbin or /libexec based on platform policies. This leads to hacks such as:

```
cargo build --release
install target/release/$exec_name $buildroot/sbin/
OR
cargo install --root $buildroot
mv $buildroot/bin/$exec_name $buildroot/sbin
```

Neither of these are obvious or intuitive. Cargo should allow people to truly express the path they want to install to. 

Effectively, --root should not be inserting a "/bin" anywhere, and should actually be an expression of the prefix:

```
cargo install --root $buildroot/bin/
cargo install --root $buildroot/sbin/
cargo install --root $buildroot/where/ever/i/hope/and/dream
```

**Steps**

1. Attempt to package something with cargo for a distribution package manager.

**Possible Solution(s)**
As above.

Another alternate is to have a rootprefix option added whicch ccontains the "bin" by default, but can be overriden or removed. 

**Notes**

Output of `cargo version`:

- affects all versions to date.

**Comment by alexcrichton** [comment]
Thanks for the report! The `cargo install` command isn't a general-purpose packaging system, so if you're packaging software you'll need to have step movement after the `cargo` steps.
