### ISSUE TITLE
“Cargo.lock” filename is annoying because it shares a stem with “Cargo.toml”

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/cargo#7603]
**Describe the problem you are trying to solve**

Where convenient, I make the first three or ideally two characters of filenames unique, so that I can use <kbd>Tab</kbd> to expand the rest of the filename, in text editors, terminals, and anything else with tab completion.

Cargo.toml and Cargo.lock don’t let me do this. If the completer goes as far as it can, then I end up with “Ca<kbd>Tab</kbd>” giving me “Cargo.” and I need to type “toml” or “t<kbd>Tab</kbd>” to make it “Cargo.toml”. Or if the completer cycles through complete filenames, then “Ca<kbd>Tab</kbd>” gets me “Cargo.lock”, although “Cargo.toml” is what I want almost every time.

**Describe the solution you'd like**

Rename Cargo.lock to something else that doesn’t start with “Ca”. I have no immediate suggestions.

Alternatively, naming it “Cargo.toml.lock” wouldn’t be *perfect* in this regard, but would be marginally better because Cargo.toml would be the first tab completion with whichever technique (even if it wouldn’t be a known-complete match).

**Notes**

This is a constant niggling annoyance, whenever I interact with the files. It may sound small or even petty, but this is honestly a surprisingly big deal for usability.

Cargo isn’t the only annoying project in this. npm has package.json and package-lock.json. Quite seriously, the fact that Yarn uses yarn.lock is about enough to tip the scales its way when I choose which to use.

And then Git, with .git, .gitmodules, .gitignore… they all just disrupt flow, though I acknowledge there’s no good solution *there*.

If this is changed, there are various tools that would need to be updated, but it’s not a big list, and I honestly don’t believe the trouble would be in any way significant.

**Comment by MikailBag** [comment]
Just few variants: `package-lock.toml`, `Lockfile.cargo.toml`, `_Cargo_lock.toml`

**Comment by ehuss** [comment]
I can appreciate the frustration when things like this don't work as smoothly as one would like, but I don't think the disruption of changing the name at this time is worth the benefits.
