### ISSUE TITLE
Regression in beta: failed to parse slash in a custom cfg name

### ISSUE THREAD

**Issue by ordian** [rust-lang/cargo#7613]
According to https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies, custom target specification is allowed, e.g.
```toml
[target."x86_64/windows.json".dependencies]
winhttp = "0.4.0"
```
`cargo +stable metadata` works on this toml, while `cargo +beta metadata` fails 
```
❯ cargo +stable --version      
cargo 1.39.0 (1c6ec66d5 2019-09-30)
❯ cargo +beta --version
cargo 1.40.0-beta (5da4b4d47 2019-10-28)
❯ cat Cargo.toml 
[package]
name = "None"
version = "0.1.0"
[target."x86_64/windows.json"]
dependencies = { hello = "1.0" }
```
```
❯ cargo +stable metadata
<snip>
❯ cargo +beta metadata 
error: failed to parse manifest at `/tmp/Cargo.toml`

Caused by:
  failed to parse `x86_64/windows.json` as a cfg expression: invalid target specifier: unexpected character / in target name
```

**Comment by ehuss** [comment]
This is a result of a change in the parsing code in #7375.  However, this hasn't worked in a long time (if ever?), as the target was an absolute, canonicalized path.  Then, in #7425 it was changed to be the file stem.

So a target like `--target foo/bar.json` now matches the platform in `[target.bar.dependencies]`.

@alexcrichton Does the current behavior (file_stem) seem like the correct choice?  If so, this seems like a documentation change (and adding a test).

**Comment by alexcrichton** [comment]
Yeah I believe the filestem is what we've always intended as the general identifier for the target

**Comment by ordian** [comment]
Thanks for confirming this is a documentation bug!
