### ISSUE TITLE
Cargo.toml displaying user password in OpenSUSE (Tumbleweed)

### ISSUE THREAD

**Issue by HoKiady** [rust-lang/cargo#7633]
**Problem**
I tried creating a new rust project using cargo but I've noticed that my user password is displayed next to my email in the "authors" entry of the _cargo.toml_ file. I can't say much about where this problem is coming from, but I suppose that it may be related to some way I've configured the password manager in KDE.

```
[package]
name = "HelloWorld"
version = "0.1.0"
authors = ["*mail* <*password*>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
...
```

**Steps**
1.Creating new project using cargo
2.Checking on "Cargo.toml" file
3.On the "authors" entry my password is displayed

Thank you !

**Notes**
Output of `cargo version`:
`cargo 1.41.0-nightly (750cb1482 2019-11-23)
`

**Current Platform**
Operating System: openSUSE Tumbleweed 20191124
KDE Plasma Version: 5.17.3
KDE Frameworks Version: 5.64.0
Qt Version: 5.13.1
Kernel Version: 5.3.12-1-default
OS Type: 64-bit

**Comment by ehuss** [comment]
The places Cargo looks is documented in https://doc.rust-lang.org/cargo/commands/cargo-new.html.  Can you check those values to see where it is coming from?  It only uses `.cargo/config`, environment variables, and git configuration. There probably shouldn't be a password in any of those.

**Comment by HoKiady** [comment]
I checked `.gitconfig` and the issue might come from it.
```
[user]
	name = *mail*
	email = *password*
```
So finally, not an issue from cargo.
Git has certainly been configured in a wrong way on my system. Guess I'll have to check that out now.
Thank you for helping !
