### ISSUE TITLE
Add new flag in package cmd to use a path dependency's version

### ISSUE THREAD

**Issue by stiiifff** [rust-lang/cargo#7636]
**Describe the problem you are trying to solve**
When working in big codebases composed of many crates, it is common to use path dependencies in Cargo.toml manifests. This however prevents to `cargo package` those crates as there is currently a check in place (in `cargo_package.verify_dependencies`) that enforce the need for a version for path dependencies. This rule is rather blocking one when one wants to publish the initial versions for all crates of a bigger product. It would be nice if the crate version specified in each crate's manifest could be dynamically referred to when cargo generates a new Cargo.toml file during the packaging process.

**Describe the solution you'd like**
We could add a `--use-path-dependency-version` flag to bypass the version checks and dynamically replace the `path` attribute by the `version` attribute (coming from the dependency's Cargo.toml) for each dependency.

As an example, if we have crates A & B in same workspace, with A's manifest:
```toml
[package]
name = "A"
version = "0.1.0"
```
and B's manifest:
```toml
[dependencies]
A = { path = "./A" }
```

when packaging with `--use-path-dependency-version`, B's manifest would become:
```toml
[dependencies]
A = { version = "0.1.0" }
```
instead of failing with
```bash
"all path dependencies must have a version specified when packaging.
dependency `A` does not specify a version.
```

**Comment by alexcrichton** [comment]
Thanks for the report! You can actually specify both `path` and `version` for this issue, and that should do the trick!
