### ISSUE TITLE
Extracting `with_authentication` into a crate

### ISSUE THREAD

**Issue by maraisr** [rust-lang/cargo#7638]
I have been building a git utility, and have faced a credentials problem, like most people doing fetching, clone, pushing etc... And stumbled upon your implementation of this, and it's by far the most bulletproof abstraction I've seen - even solves the infinite loop problem..

I can't find a crate that houses that or a similar abstraction, and was wondering if you guys would be open at pulling it out into a crate, that you guys just use, and potentially something I could also use. I'd hate to copy-paste, and be prone to missing out o bug fixes and improvements to it.

> This stuff: https://github.com/rust-lang/cargo/blob/a41c8eae701c33abd327d13ff5c057389d8801b9/src/cargo/sources/git/utils.rs#L410-L624

**Comment by est31** [comment]
Maybe it should be put into the git2 crate directly? https://github.com/rust-lang/git2-rs

**Comment by maraisr** [comment]
Would it though? I feel like git2 isn't mean to be a git implementation, but rather the primitives that allows us to build things. So I think what git2 is doing is okay... I mean its not like libgit2 exposes implementations for this stuff for the c guys.

Could be horribly wrong - but do feel there still needs to be a separation of concerns. 

Perhaps a `git2-utils` crate, that complements `git2` makes more sense.

**Comment by est31** [comment]
The function highlighted by you is only 200 lines, most of it being comments. It would be useful for anyone who uses the git2 crate. Note that crates have a certain management overhead.

**Comment by maraisr** [comment]
Copy-paste it is. Thanks for your time!

**Comment by est31** [comment]
@maraisr just try filing a PR for the git2 crate first...
