### ISSUE TITLE
could not find native static library `crypto`

### ISSUE THREAD

**Issue by richardchey** [rust-lang/cargo#7639]
rust: 1.39.0
host: Ubuntu 18.04.3 LTS

I have installed the "libssl-dev" on my host, but it still got the error "could not find native static library `crypto`". 
And if i change it to `cargo:rustc-link-lib=crypto`, or add `rustc-link-search=<crypto-path>`,  or create a bin crate(rename `lib.rs` to `main.rs`) with the same code, it will be ok.
Why is this?

```rust
// build.rs: 

fn main() {
    println!("cargo:rustc-link-lib=static=crypto");
}
```

```rust
// lib.rs:

extern "C" {
    pub fn ERR_get_error() -> ::std::os::raw::c_ulong;
}

fn main() {
    let err: u64;
    unsafe {
        err = ERR_get_error() as u64;
    }
    println!("study-main: {:?}", err);
}
```

**Comment by ehuss** [comment]
Without a `kind`, rustc will default to linking a dylib, which I presume defers the linking decision to your system linker.  With a static library, I think rustc is building the archive itself, so it needs to be able to locate the static library.  Without the `-L` flag, I'm guessing it doesn't search your system directories the same way the native linker does.  I think the solution here is to provide the correct linking paths if you want to statically link.

Also, this is more of a rustc issue.  I recommend if you have more questions trying one of the user forums, or filing an issue on https://github.com/rust-lang/rust/issues.

**Comment by richardchey** [comment]
I have filed two issues on ructc, but they close all. It seems to need cargo to resolve the problem.

https://github.com/rust-lang/rust/issues/66861
https://github.com/rust-lang/rust/issues/67050

**Comment by csmoe** [comment]
@richardchey my bad, your issue in rustc reopened :)

**Comment by ehuss** [comment]
Yea, sorry you got bounced around.  In this case, I think `rustc` may be working as expected, though.  Linking of static libraries does not invoke the system linker, and I don't think rustc should be trying to gather what the system's linker search path is (which is not generally possible AFAIK).  You'll need to somehow pass the correct location to `rustc-link-search`.  Typically build scripts use something like [`pkg-config`](https://crates.io/crates/pkg-config) or require the user to define an environment variable with the correct path.

**Comment by richardchey** [comment]
Thanks for your patience. But there is still a problem, if the crate is bin, not lib, it's ok. that is rustc could link a static library in the system directories in a bin crate without needing to pass the correct location to `rustc-link-search`. It seems to be inconsonant.

**Comment by ehuss** [comment]
I think that's because binaries use the system linker, whereas libraries use a built-in archiver.

**Comment by alexcrichton** [comment]
I agree with others that this is a rustc issue, so I'm going to close this.
