### ISSUE TITLE
Does cargo read `.cargo/config` in the project directory?

### ISSUE THREAD

**Issue by NickeZ** [rust-lang/cargo#7640]
**Problem**

It seems `.cargo/config` is not read from the project directory. Maybe I misunderstood how it is supposed to work.

I have a no-std rust crate which I would like to compile. I compile with the following flags:
1. `--manifest-path`
2. `--target-dir`
3. `--release`

I've put the following in `<my-projec-dir>/.cargo/config`:

```
[build]
target = "thumbv7em-none-eabi"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```

**Steps**
1. cargo build

**Possible Solution(s)**
Putting `.cargo/config` in the home directory seems to have effect. But then it changes all my crates IIUC.

**Notes**

Output of `cargo version`:

`cargo 1.39.0 (1c6ec66d5 2019-09-30)`

**Comment by alexcrichton** [comment]
The `.cargo/config` files are read from the cwd of `cargo build` up to the root of the filesystem and applied for the entire compilation. Cargo has various other configuration systems for per-crate configuration, although not for things like source-replacement.

**Comment by NickeZ** [comment]
So the conclusion is that `--manifest-path` is not compatible with `cargo vendor`?

I realized that I probably can work around it by `cd`ing to the project directory instead of using `--manifest-path`.

thanks!

**Comment by alexcrichton** [comment]
Yeah the `cd` trick should work!
