### ISSUE TITLE
Coloured output despite setting $TERM to "xterm-mono"

### ISSUE THREAD

**Issue by ainar-g** [rust-lang/cargo#7646]
**Problem**
When I set `TERM` to `xterm-mono`, I expect programmes to honor that.  Cargo shows colours despite me telling it that my terminal is monochrome.  Yes, I know about `--color=never`, that's not the point.  The point is that when a terminal doesn't support colours, programmes shouldn't attempt to print them.

**Steps**
``` sh
$ export TERM="xterm-mono"
$ cargo $ANY_COMMAND
```

**Possible Solution(s)**
Default to `--color=never` on non-coloured terminals.

**Notes**

Output of `cargo version`:
```
$ cargo --version
cargo 1.39.0 (1c6ec66d5 2019-09-30)
$ uname -a
Linux ainar-IdeaPad-U330p 4.15.0-71-generic #80-Ubuntu SMP Thu Nov 14 02:19:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by aleksator** [comment]
The behavior is not going to be changed in `termcolor` (see https://github.com/BurntSushi/termcolor/issues/27).

Should this issue be closed as well?

**Comment by ainar-g** [comment]
I haven't used cargo much since then, so I don't mind closing this.  Thanks.
