### ISSUE TITLE
third party crate fails as custom cargo subcommand

### ISSUE THREAD

**Issue by DevinR528** [rust-lang/cargo#7653]
**Problem**
I maintain the [`cargo-sort-ck`](https://github.com/DevinR528/cargo-sort-ck) crate and got an [issue](https://github.com/DevinR528/cargo-sort-ck/issues/4) about my command not working as a special subcommand when invoked as `cargo sort-ck`.

**Steps**

1. `cargo install cargo-sort-ck`
2. `cargo sort-ck`
3. we both get this error `Failure: No file found at: sort-ck/Cargo.toml`

**Possible Solution(s)**
I'm probably doing something wrong.

**Notes**

Output of `cargo version`:
cargo 1.41.0-nightly (8280633db 2019-11-11)

**Comment by ehuss** [comment]
The first argument to a custom subcommand is the name of the subcommand itself.  It looks like maybe you are interpreting it as a path? More information can be found at https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands

**Comment by DevinR528** [comment]
Thanks for taking the time to answer that I appreciate it.
