### ISSUE TITLE
Format placeholder code when generating a crate

### ISSUE THREAD

**Issue by Kinrany** [rust-lang/cargo#7656]
### Problem
My workspace has a shared `.rustfmt.toml`. I'm using `cargo new` to create crates in the workspace. I'm also using VSCode and RLS.

My config file contains `tab_spaces = 2`, but `main.rs` is not initially formatted according to the config file. When opened in VSCode, the code style is inferred to be 4 spaces, not 2. VSCode does not update this parameter after I format the file.

This becomes a problem later, when I try to create a function or a block. Typing `{` and `Enter` creates two curly brackets and places the cursor on the next line, as usual, but indented by 4 spaces instead of 2.

### Solution
If there's a `.rustfmt.toml` in the workspace, use the config to format the placeholder code.

Alternatively add `cargo new --fmt`, so that this behavior is opt-in.

### Notes
Workaround: run `cargo fmt` after `cargo new`.

I'm willing to work on this feature, though this will be my first time contributing to Cargo :)

**Comment by Stupremee** [comment]
I would like to work on this.
Should the code only be formatted if the `fmt` argument is present?

**Comment by Kinrany** [comment]
I was waiting for a team member to comment on whether this is something they'd accept.

IMO looking for `.rustfmt.toml` is the more intuitive option.

**Comment by ehuss** [comment]
The team briefly discussed this, and it should be ok to run rustfmt on the new file (as long as rustfmt is in the path).  It should also probably ignore failures to run rustfmt, though that should be rare (maybe print a warning).  I wouldn't bother hunting for rustfmt.toml files.

**Comment by ehuss** [comment]
Yea, it also embeds some knowledge about rustfmt that wouldn't be necessary (and checking things like home directory locations, etc. makes it complicated).

**Comment by Kinrany** [comment]
Great. I'll try to do this on the weekend. 05:26, January 15, 2020, Eric Huss <notifications@github.com>:Yea, it also embeds some knowledge about rustfmt that wouldn't be necessary (and checking things like home directory locations, etc. makes it complicated).

**Comment by Kinrany** [comment]
It seems `rustfmt` CLI is deprecated, and `cargo fmt` should be used instead.

**Comment by Kinrany** [comment]
This should already be in the latest stable version, right?

It's not working for me, so it seems my implementation is not actually doing anything D:

**Comment by ehuss** [comment]
@Kinrany This change is in 1.43 which should be released tomorrow.
