### ISSUE TITLE
Suggestion for cargo book Continuous Integration section to include GitHub Actions

### ISSUE THREAD

**Issue by trevordmiller** [rust-lang/cargo#7664]
**Describe the problem you are trying to solve**
It would be helpful to have an official example of using cargo with GitHub actions for CI/CD.

**Describe the solution you'd like**
A "GitHub Actions" section in https://doc.rust-lang.org/cargo/guide/continuous-integration.html.

**Notes**
Might be related to https://github.com/rust-lang-nursery/cli-wg/issues/161.

**Comment by ehuss** [comment]
Thanks for the suggestion!  There's a tracking issue (#5656) for updating that chapter in the documentation.  I copied your suggestion over there, and I'm going to close this in favor of that issue.
