### ISSUE TITLE
Suggestion for cargo book Continuous Integration section to include more examples

### ISSUE THREAD

**Issue by trevordmiller** [rust-lang/cargo#7665]
**Describe the problem you are trying to solve**
Currently the Cargo book CI section only shows `cargo build` and `cargo test`:
https://doc.rust-lang.org/cargo/guide/continuous-integration.html

**Describe the solution you'd like**
It would be helpful to include examples of other static analysis, documentation generation, sharing executables like:

```sh
cargo check
cargo test
cargo clippy
cargo fmt
cargo audit
cargo doc
cargo build --release
# how to share executables to GitHub releases / packages?
```

**Comment by ehuss** [comment]
Thanks for the suggestion!  There's a tracking issue (#5656) for updating that chapter in the documentation.  I copied your suggestion over there, and I'm going to close this in favor of that issue.
