### ISSUE TITLE
cargo test don't work in macos and doesn't detect my tests

### ISSUE THREAD

**Issue by Arshiamidos** [rust-lang/cargo#7668]
**Problem**
when running `cargo test --all` doesn't detect tests.
**Steps**
write a test file.   
```rust 

#[cfg(test)]
mod tests {
   
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```
run `cargo test `.   
but cargo won't recognize my tests.  
also i ran `cargo test <file_test.rs>` .   
but `rustc --test <file_test.rs> ; ./<file_test> ` will work!

**Comment by ehuss** [comment]
Can you include the output that you got from cargo?

[`cargo test`](https://doc.rust-lang.org/cargo/commands/cargo-test.html) doesn't accept filenames.  You need to set up a [package](https://doc.rust-lang.org/cargo/guide/creating-a-new-project.html) which has a particular [layout](https://doc.rust-lang.org/cargo/guide/project-layout.html).

**Comment by Arshiamidos** [comment]
`cargo test` normally runs, but it doesn't detect any test case.
```    
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running /Users/macuser/Documents/GitHub/BIIIIIIIIIIIIIG/target/debug/deps/big-946bdd8dd498cc60

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
[link](https://github.com/Arshiamidos/BIIIIIIIIIIIIIG)

**Comment by ehuss** [comment]
I don't see any functions marked with `#[test]` in the repo you linked.

**Comment by Arshiamidos** [comment]
sorry @ehuss , it's conflicted by `nightly` and `racer` .
