### ISSUE TITLE
Very slow binary execution after build if network connection is established but works slow

### ISSUE THREAD

**Issue by olegnn** [rust-lang/cargo#7675]
**Problem**

Code executed right after fresh build using `cargo +nightly run --offline` command takes very long time to execute with slow network connection.
It looks like even with `--offline` flag  it attempts to make some network request(s) if network connection is established.

**Steps**

1. Having following code and slow network connection
```rust
fn main() { 
    println!("Running..."); 
}
```
2. Run `cargo +nightly run --offline`
For me It took 23 seconds to run.
```
$ time cargo +nightly run --offline
   Compiling strange v0.1.0 (/Users/oleg/Documents/strange)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/strange`
Running...
cargo +nightly run --offline  0,20s user 0,14s system 1% cpu 23,153 total
```
But my current record is 1 minute.
```
cargo +nightly run --offline 0,56s user 0,31s system 1% cpu 1:04,35 total
```
**Possible Solution(s)**

Disable all network requests if `--offline` flag passed.
**Notes**

Output of `cargo version`:
cargo 1.39.0 (1c6ec66d5 2019-09-30)

**Comment by alexcrichton** [comment]
Can you try setting [`CARGO_HTTP_DEBUG=true` and then enabling logs](https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys) and see if anything looks awry?

Do you know why cargo is hitting the network without the `--offline` flag?

**Comment by olegnn** [comment]
I set these flags - no changes in output. I suggest (only idea) that it makes something like DNS host resolving - maybe calls `getaddrinfo` or something related. 
I recorded a video with this behaviour - https://youtu.be/AcO2fCgcPBM. It will be processed to HD quality, it will take some time. 
Please, don't ask me how I uploaded this video with such internet connection: it was painful.

**Comment by olegnn** [comment]
I got the same issue with direct first time execution using `./target/debug/strange`, so the problem isn't with `cargo`.
