### ISSUE TITLE
Cargo considers pre-release versions compatible with other pre-release versions or released versions

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo#7676]
**Problem**

When dependency is specified for `0.x.y-alpha.z` cargo is willing to use `0.x.y` or `0.x.y-alpha.q` as valid versions for this dependency.

This is not correct, as `-alpha.z` versions have no compatibility guarantees whatsoever.

**Steps**
1. Add a dependency on `tokio = 0.2.0-alpha.5`
2. Run cargo update -p tokio
3. Notice `tokio = 0.2.3` being dependent on and your crate failing to compile, because `tokio::runtime::current_thread` has been removed.

**Possible Solution(s)**

Consider all pre-release versions to be not compatible with any other version.

**Comment by nagisa** [comment]
cc #2222

**Comment by ehuss** [comment]
Thanks!  I'm going to close in favor of #2222.  In general we know that pre-release versions (and metadata) don't often work as expected, and that issue is for tracking whatever fixes need to be done.
