### ISSUE TITLE
cargo does not work seamlessly with tor; cargo-xbuild issues spurious network access

### ISSUE THREAD

**Issue by elmarstellnberger** [rust-lang/cargo#7684]
basically the following procedure should work for cargo:
torsocks cargo fetch
torsocks cargo --offline vendor
torsocks cargo --offline build
torsocks cargo --offline install

I have written torsocks before the offline invocations because as it turned out cargo still wants to access the network blocking not only at "torsocks cargo fetch" but also at "torsocks cargo --offline build". However the procedure worked like follows:
torsocks cargo vendor
** unplug the network cable **
cargo --offline build
cargo --offline install

The fact that "cargo --offline build" still issues some network request is a harsh security issue as this would impersonate my tor network connection thus rendering the protection by tor useless.

**Comment by lukaslueg** [comment]
Notice that ultimately there is no way to prevent network access during `cargo build` due to build-scripts.

**Comment by elmarstellnberger** [comment]
Hmm; then it would need to be reported against cargo-xbuild.

**Comment by alexcrichton** [comment]
Thanks for the report! Cargo-xbuild though is not part of Cargo, so it sounds like this should be an issue with that repository?

If you can reduce this to a bug with just Cargo where `cargo build --offline` still makes a network request, though, please let us know!

**Comment by elmarstellnberger** [comment]
In a fact I have reported two issues above. One issue is that torsocks cargo fetch stalls. The other one may be cargo-xbuild specific. Nonetheless I would ask you to tell me where I can report such an issue correctly. for the first issue: Please reopen this report!!

**Comment by alexcrichton** [comment]
I don't manage the cargo-xbuild project myself, if this is a bug report for Cargo can you provide steps to reproduce, build logs, or other information that can be used to verify this bug report?

**Comment by elmarstellnberger** [comment]
how to reproduce:
$ torsocks git clone https://github.com/rust-osdev/cargo-xbuild
$ cd cargo-xbuild
$ torsocks cargo fetch
You need a clean installation for this to stall, not a rootkitted one; at best use a live cd.
I do not know how to gather the build logs; it would be nice if you could assist or help me in doing so, if needed.
