### ISSUE TITLE
cargo xrustc hangs at a certain stage when invoked with torsocks

### ISSUE THREAD

**Issue by elmarstellnberger** [rust-lang/cargo#7685]
The problem arises when trying to compile the firmware for my darp5 notebook: https://trac.torproject.org/projects/tor/ticket/32577
  Recently I have installed all the dependencies for this build manually (scripts/deps.sh); i.e. I have found ways to ship around the torsocks problems with rustup and cargo-xbuild: https://github.com/rust-lang/rustup/issues/2027 https://github.com/rust-lang/cargo/issues/7684
  However now cargo hangs at some other build stage where I do not know why it wants to access the network. Consequently I could not find any way to circumvent this problem: have a look at the two attachements for scripts/build.sh:
[firmware-compile-online.msg.txt](https://github.com/rust-lang/cargo/files/3936343/firmware-compile-online.msg.txt)
[firmware-compile-offline.msg.txt](https://github.com/rust-lang/cargo/files/3936344/firmware-compile-offline.msg.txt)

**Comment by alexcrichton** [comment]
Thanks for the report, but cargo-xrustc is not part of Cargo itself. If you can reduce it to just using Cargo though, please feel free to file a new issue!

**Comment by elmarstellnberger** [comment]
Where to report issues for xrustc?
