### ISSUE TITLE
Documentation about maintenance field confusing

### ISSUE THREAD

**Issue by danielparks** [rust-lang/cargo#7691]
**Problem**
~~According to The Manifest Format, [the `maintenance` key is required](https://github.com/rust-lang/cargo/blame/774d9492dc359d9a2068924c01e9231cfadb0c0a/src/doc/src/reference/manifest.md#L331-L346). However, the setting the key causes a warning to be displayed (“warning: unused manifest key: package.maintenance”) when running various cargo commands, including `cargo check`.~~

**Update:** the documentation for the `[package]` and `[badges]` sections were mixed together. In particular, there is no heading for [`[badges]`](https://github.com/rust-lang/cargo/blame/774d9492dc359d9a2068924c01e9231cfadb0c0a/src/doc/src/reference/manifest.md#L287), and [part of the documentation for `[package]`](https://github.com/rust-lang/cargo/blame/774d9492dc359d9a2068924c01e9231cfadb0c0a/src/doc/src/reference/manifest.md#L349-L358) was below information about `[badges]`.

**Steps**

1. ~~Create a new cargo package~~
2. ~~Add `maintenance = { status = "actively-developed" }` to the `[package]` section of `Cargo.toml`.~~
3. ~~Run `cargo check`:~~

```
❯ cargo check   
warning: unused manifest key: package.maintenance
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

**Possible Solution(s)**
~~I’m not sure if this is a documentation issue or a code issue. `cargo` itself doesn’t seem to do anything with the key, but crates.io appears to have code related to it.~~

**Notes**

```
❯ cargo --version
cargo 1.39.0 (1c6ec66d5 2019-09-30)
```

**Comment by sfackler** [comment]
The key is not required, the status field inside of the maintenance block is (only if you have a maintenance block in the first place). Also, maintenance goes in the `[badges]` block, not in `[package]`.

**Comment by danielparks** [comment]
Ah, I see now. Thanks!

I think this is a docs issue then, since the docs for the `[badges]` section are all currently under “The `[package]` section” heading. If I don’t get distracted by my new puppy, I’ll file a PR later today.

Would you like me to file a separate issue, update the description of this issue, or something else?

**Comment by danielparks** [comment]
PR #7694 filed.

**Comment by danielparks** [comment]
PR merged. Thanks!
