### ISSUE TITLE
`cargo login` with 2nd alternate registry overwrites 1st alternate registry's token in ~/.cargo/credentials

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/cargo#7701]
**Problem**

When working on crates.io, I often run an instance locally and interact with it through cargo. We also have a staging instance where I test things out. So this is 2 alternate registries in addition to the main crates.io.

My `~/.cargo/config` looks like this:

```
[registries]
staging = { index = "https://github.com/rust-lang/staging.crates.io-index" }
local = { index = "file:///Users/carolnichols/rust/crates.io/tmp/index-bare" }
```

If I run `cargo login --registry staging [token]` then run `cargo login --registry local [other-token]`, `~/.cargo/credentials` only contains the credentials for the local registry.

**Steps**

1. Using rustc 1.39.0 (4560ea788 2019-11-04)/cargo 1.39.0 (1c6ec66d5 2019-09-30), create a `~/.cargo/config` containing 2 alternate registries as shown above.

2. Move your existing `~/.cargo/credentials` file elsewhere if you don't want to mess it up reproducing this.

2. Run `cargo login abcde` to set your token for the main crates.io registry.

3. Observe that `~/.cargo/credentials` contains these contents, as expected:

```
[registry]
token = "abcde"
```

4. Run `cargo login --registry staging fghij`.
5. Observe that `~/.cargo/credentials` contains these contents, as expected:

```
[registries.staging]
token = "fghij"

[registry]
token = "abcde"
```

6. Run `cargo login --registry local klmno`.
7. Observe that `~/.cargo/credentials` contains these contents, with `local` and the main registry present as expected, but with `staging` gone:

```
[registries.local]
token = "klmno"

[registry]
token = "abcde"
```

The contents I expected to have would contain tokens for all 3 registries, like:

```
[registries.local]
token = "klmno"

[registries.staging]
token = "fghij"

[registry]
token = "abcde"
```

**Possible Solution(s)**

Unclear, I was going to go poking around after filing this.

**Notes**

Output of `cargo version`: `cargo 1.39.0 (1c6ec66d5 2019-09-30)`, current stable on macOS. 

I was also able to reproduce with `rustc 1.41.0-nightly (27d6f55f4 2019-12-11)`/`cargo 1.41.0-nightly (626f0f40e 2019-12-03)`.

**Comment by giraffate** [comment]
When `registries` is set for key, 
https://github.com/rust-lang/cargo/blob/19a0de242f442ac7149c511031599aafa35b36dc/src/cargo/util/config/mod.rs#L1327-L1330
it seems to overwrite value here.
https://github.com/rust-lang/cargo/blob/19a0de242f442ac7149c511031599aafa35b36dc/src/cargo/util/config/mod.rs#L1355


When key `registries` has the value, it seems better to fix to merge the original value with the new value, but what about?
