### ISSUE TITLE
cargo build error: missing config key `build.target`

### ISSUE THREAD

**Issue by zoumi** [rust-lang/cargo#7709]
$ cargo -v build
error: missing config key `build.target`
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  E:\rustup

installed toolchains
--------------------

nightly-i686-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.41.0-nightly (3eeb8d4f2 2019-12-12)

I had uninstalled rustup by accident.But, after reinstalling it.I got this error and I can't figure out what's wrong.

**Comment by ehuss** [comment]
Hm, that's really strange!  The `build.target` config key is optional, so it shouldn't be possible for it to cause an error if it is missing.

Can you check for any `.cargo/config` files?  Either in the current directory, or any parent directory, or in your home directory.  Also maybe check for any CARGO or RUST environment variables?  Also double check the output of `cargo --version`.

**Comment by zoumi** [comment]
```
zoumi@zoumi-PC MINGW64 /e
$ cargo --version
cargo 1.41.0-nightly (626f0f40e 2019-12-03)

zoumi@zoumi-PC MINGW64 /c
$ cargo new atest
warning: compiling this new crate may not work due to invalid workspace configuration

missing config key `build.target`
     Created binary (application) `atest` package

zoumi@zoumi-PC MINGW64 /c
$ cd ./atest

zoumi@zoumi-PC MINGW64 /c/atest (master)
$ cargo build
error: missing config key `build.target`

```
There is warning when create new cargo project. I had removed config file in CARGO_HOME.

**Comment by zoumi** [comment]
My environment vars:
CARGO_BUILD_TARGET_DIR E:\rustdir\target
CARGO_HOME E:\rustdir
RUSTUP_HOME E:\rustup

The SHA-256 of 
E:\rustup\toolchains\nightly-i686-pc-windows-msvc\bin\cargo.exe
is: c4f4e430e0b5901257338af5e7caaa0802d7b6ef00bb61ff18331cce41cc8b70

The SHA-256 of 
E:\rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo.exe
is: e054ef11f81716af08fb85b6665fd3c6658ef97c057a9ba08ad932f492b2aee8

**Comment by ehuss** [comment]
>  CARGO_BUILD_TARGET_DIR E:\rustdir\target

Ah, that's the problem.  We have a bug with environment variables where one is a prefix of another.  In this case, you can use `CARGO_TARGET_DIR` instead, which should work.

**Comment by zoumi** [comment]
It works! Thank you!
