### ISSUE TITLE
Generate default `.rustfmt.toml` template based on Rust edition

### ISSUE THREAD

**Issue by lzutao** [rust-lang/cargo#7712]
Sometimes I don't use `cargo fmt` to format codes but I use rustfmt directly.
**Reason**: `cargo fmt` sometimes updates the registry and lockfile on call, which I don't want.

With async / await in Rust 2018 edition, the rustfmt's default mode (Rust 2015)
cannot work.

I would suggest creating new `.rustfmt.toml` on `cargo new` and `cargo init` invocations.
The generated `.rustfmt.toml` could be:
```toml
edition = "2018"
```
which corresponds to value passed to `--edition` option.

**Comment by sfackler** [comment]
Have you filed an issue with rustfmt about cargo-fmt updating the registry and lockfile?

**Comment by lzutao** [comment]
Nope, I haven't.
If I run `cargo fmt` on CI, it usually takes time to initiate. But with rustfmt it does formatting immediately.

**Comment by alexcrichton** [comment]
Thanks for the report, but this sounds like a `cargo fmt` bug which is either updating the registry too eagerly or isn't reading the `edition` directive from `Cargo.toml`

**Comment by lzutao** [comment]
Another point for keeping this issue is that sometimes I want to format individual file
in project. And default `.rustfmt.toml` is nice to have to avoid problem I described on OP.
