### ISSUE TITLE
Cargo command for turning a single crate into a workspace

### ISSUE THREAD

**Issue by Havvy** [rust-lang/cargo#7713]
Sometimes I create a crate and work on it, and then realize I want to have some of its code in another crate. To do so, I have to make a new workspace and put the current crate into it. Doing so while keeping VCS correct and looking at all the things that need to go where is time-consuming and error-prone. It's also all mechanical.

As such, I'd like to see a new command `cargo workspace promote` that does this transformation for us.

**Comment by ehuss** [comment]
I'm not sure I fully understand.  If you want to create a workspace, it's a one-line change (add an empty `[workspace]` to the top `Cargo.toml` file).  There shouldn't be any other changes necessary.

I've considered an alternative, if there is a parent manifest that lists the package as a path dependency to automatically treat it like `[workspace]` if a workspace is not defined, but I'm not sure if that is too non-local or would cause other problems.

**Comment by ehuss** [comment]
I'm going to close this since it's not really clear what this would do (other than adding an empty `[workspace]`?).  There's also a pretty high bar for new commands (which would probably need a much more detailed specification), and we currently don't have any toml editing capabilities.  New commands can also be prototyped as a plugin.

**Comment by rendaw** [comment]
I've encountered the same use case a number of times.  To clarify, this is about when you know you'll need multiple workspaces, a command that converts a workspace-less project into a project with a root workspace and subworkspace, where the current code is all moved into the subworkspace.

This would require toml modifications, plus creating a directory, generating new toml files, moving files, etc.  It sounds like OP wanted it to handle updating git too (staging moves, etc).

I second OP's reasons for wanting it too.

**Comment by cowlicks** [comment]
Here's a start on a bash script to do what you want:
```bash
# get crate name
CRATE_NAME=$(cat Cargo.toml | grep '^name')
# extract just the name part somehow
# ....
#
mkdir $CRATE_NAME
# move our tracked files all into the new crate directory
git mv $(ls -a | grep -f <(git ls-files | sed 's/\/.*//g' | sort | uniq)) $CRATE_NAME

# add the new Cargo.toml
cat << EOF > Cargo.toml
[workspace]

members = [
    "$CRATE_NAME",
]
EOF
```

**Comment by 414owen** [comment]
A few adjustments on the above: 

```
#!/usr/bin/env bash

if [[ ! -z "$(git status -s)" ]]; then
  echo "Git repository is dirty. Refusing to evaluate."
  exit 1
fi

CRATE_NAME="$(cat Cargo.toml | grep '^name\s*=' | sed 's/^name\s*=\s*"\|"$//g')"
mkdir "$CRATE_NAME"

git mv $(git ls-files | sed 's/\/.*//g' | sort | uniq | grep -v '^\.gitignore$') "$CRATE_NAME"

cat << EOF > Cargo.toml
[workspace]

members = [
    "$CRATE_NAME",
]
EOF

```
