### ISSUE TITLE
pkgid spec confusion

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#7725]
The documentation for the package id spec (https://doc.rust-lang.org/1.40.0/cargo/reference/pkgid-spec.html) does not seem to be correct in several ways.

* The proto is not optional.  Cargo defaults to `cargo://` which is not a scheme Cargo understands anywhere.
* `crates.io` as a host does not work.  It looks like you can only give the full path to the index, like `https://github.com/rust-lang/crates.io-index#bitflags:1.2.1`
* `host/name` doesn't work.  It looks like [the matching code](https://github.com/rust-lang/cargo/blame/d5e20a9b7f9e3888fd6144f606aadb62bbabece0/src/cargo/core/package_id_spec.rs#L160-L175) requires the entire scheme/host/path to match.

The question is, what should we do?  Should we just remove all the things that don't work from the documentation?  Or should we try to enhance the parsing/matching code to work better.  

* Should `crates.io` work as an alias for `https://github.com/rust-lang/crates.io-index`?
* Missing proto probably shouldn't default to anything, and should probably match any proto.
* Should `host/name` match `host/path#name`?

EDIT: #9188 and #9249 fixed the broken parts, but leaving this open to consider adding abbreviated forms.

**Comment by alexcrichton** [comment]
Oh dear that didn't exactly age well...

I think though we've started using `crates-io` in other places such as `[source.crates-io]`, so supporting either a full host name or the "short name" of the registry seems like a good thing to support (we don't support this today afaik). 

As for the proto business I think it's fine to basically remove that and make the docs match the current implementation.

In any case, what I would propose:

* First make the docs match the current implementation
* Next support `registry-identifier/crate-name` where `registry-identifier` matches what we do for alternative registries.

**Comment by epage** [comment]
I'm proposing we close this.  All that is left is considering more abbreviated forms.  In the 5 years this has been open, no one has piped in about wanting some.  Instead of tracking this as a speculated need, I'd recommend we wait until a user requests it.

**Comment by ehuss** [comment]
Sounds good!

**Comment by ayanwaar** [comment]
why my deposite not arrive how to i recive
