### ISSUE TITLE
cargo-metadata does not work with Tokio's gated imports

### ISSUE THREAD

**Issue by vorot93** [rust-lang/cargo#7732]
**Problem**
`cargo-metadata --all-features` does not list [Tokio's](https://github.com/tokio-rs/tokio) modules that are gated behind various feature flags.

**Steps**
1. Run `cargo-metadata --all-features`
2. Observe abscence of files in the runtime folder.

**Notes**
Tokio's feature gating is implemented by wrapping imports in macros that contain `feature` and `docs` attributes. This is probably the cause of the issue.

**Comment by sfackler** [comment]
`cargo metadata` doesn't list files in a crate as far as I know - are you using some thing other than cargo's built in subcommand?

**Comment by ehuss** [comment]
Closing since it doesn't look like this is related to Cargo directly.  Feel free to reopen if you can put together a repro, but it is also not clear to me which files you are referring to.  I'm also unclear about the dash in `cargo-metadata`, cargo's commands are space-separated.
