### ISSUE TITLE
Systems with CARGO_TARGET_DIR set fail to distinguish between separate binary crates with identical names

### ISSUE THREAD

**Issue by Osspial** [rust-lang/cargo#7740]
**Problem**

On systems with a shared target directory specified by the `CARGO_TARGET_DIR` environment variable, Cargo doesn't properly handle building root projects with name collisions. As a result, it can mistakenly fail to rebuild code when moving from one top-level crate to another top-level crate with an identical name.

**Steps**

1. Create two binary crates, both with `name = "awful"` set in their `Cargo.toml` files
2. Have crate A and crate B print different things in their `main` function
3. Execute `cargo run` in crate A, then `cd` into crate B and execute `cargo run` in that crate

An example setup has been created in this repo: https://github.com/Osspial/cargo_target_dir_awful_test_case

You'd expect to get the following output:

```
S:\programming\git\awful\a>cargo r
   Compiling awful v0.1.0 (S:\programming\git\awful\a)
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `S:\programming\cargo_shared_target\debug\awful.exe`
Awful A

S:\programming\git\awful\a>cd ../b

S:\programming\git\awful\b>cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `S:\programming\cargo_shared_target\debug\awful.exe`
Awful B

S:\programming\git\awful\b>
```

Instead, you get the following:

```
S:\programming\git\awful\a>cargo r
   Compiling awful v0.1.0 (S:\programming\git\awful\a)
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `S:\programming\cargo_shared_target\debug\awful.exe`
Awful A

S:\programming\git\awful\a>cd ../b

S:\programming\git\awful\b>cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `S:\programming\cargo_shared_target\debug\awful.exe`
Awful A

S:\programming\git\awful\b>
```

**Possible Solution(s)**

Integrate the canonicalized project path into the crate rebuild algorithm.

**Notes**

Output of `cargo version`:

```
> cargo --version
cargo 1.41.0-nightly (626f0f40e 2019-12-03)
```

I have also been informed that there are cases where building multiple projects concurrently with `CARGO_TARGET_DIR` set results in build corruption, which I believe was fixed for local target directories a ways back. However, I don't have a solid test case for that, and troubleshooting that issue doesn't really belong in this thread anyway.

**Comment by epage** [comment]
I'm having a hard time figuring out how cargo is meant to prevent two similar looking projects using the same target dir from not colliding with each other since how can it tell that apart from one project changing branches?  If you are wanting this for reusing intermediate build artifacts, official support for this would be the better route which are are tracking in #5931.  Closing in favor of that.  If there is a reason we should reconsider this, let us know!

**Comment by Ralith** [comment]
> how can it tell that apart from one project changing branches

Disambiguate by absolute filesystem path, perhaps?

**Comment by epage** [comment]
On the flip side, people want the target directory to be agnostic of that so CI can save and restore caches.

**Comment by Ralith** [comment]
Why would absolute filesystem path vary between CI runs?

**Comment by epage** [comment]
Also, people generally assume they can move their project without full rebuild.

> Why would absolute filesystem path vary between CI runs?

In some CI runners, they use a temp dir in the path from what I understand.
