### ISSUE TITLE
Cannot build vendored crates that include resources from another crate within the same workspace

### ISSUE THREAD

**Issue by MetaDark** [rust-lang/cargo#7744]
**Context**
The [Nix package manager](https://nixos.org/nix/) uses `cargo vendor` to separate downloading and building dependencies for a package. This is necessary because packages are normally built in a sandboxed environment without internet access.

**Problem**
@doronbehar and I are package maintainers for [texlab](https://github.com/latex-lsp/texlab), and while trying to upgrade texlab from 1.7.0 to 1.8.0, I've run into a build failure caused by a vendored crate depending on a resource from another crate within the same workspace:

```
error: couldn't read /tmp/nix/texlab/texlab-1.8.0-vendor/citeproc-db/src/../../wasm/src/locales-en-US.xml: No such file or directory (o
s error 2)                                                                                                                            
   --> /tmp/nix/texlab/texlab-1.8.0-vendor/citeproc-db/src/xml.rs:320:13
    |
320 |             include_str!("../../wasm/src/locales-en-US.xml").to_string(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```
I can build the project manually without the `cargo vendor` step, but I won't be able to submit this to `nixpkgs` because it can't be built in a sandboxed environment.

I've also opened a bug report in https://github.com/cormacrelf/citeproc-rs/issues/23 to work around this issue, but this seems like a fundemental problem with `cargo vendor`.

**Steps**

1. Create a workspace with two crates
eg. `crate1`, `crate2`
2. Use `include_str` to include a resource from one crate into another
eg. from `crate2`: `include_str!(../../crate1/src/resource)`

3. Create a new crate, `crate3`, outside the workspace that depends on `crate2`
4. Vendor `crate3` with `cargo vendor`
5. Follow the instructions displayed in the output of `cargo vendor`
6. Try to build `crate3` with `cargo build`
The build will fail trying to build `crate2`, but it will succeed if the vendor step is skipped.

**Possible Solution(s)**
- Vendor the entire workspace, keeping the original directory structure.
- Create a sandbox to prevent a crate from including resources from outside the crate.

**Notes**

Output of `cargo version`: `cargo 1.39.0`

**Comment by ehuss** [comment]
I think this is expected behavior.  Crates should be able to be built in isolation, and should not reference files outside of their directory.

**Comment by MetaDark** [comment]
@ehuss I understand why this may be expected behaviour, but there is still an inconsistency between building with and without `cargo vendor`.

**Comment by ehuss** [comment]
`cargo package` and `publish` will attempt to verify the package can be built in isolation, so there are some checks for it already.  I don't think it is likely that Cargo will implement sandboxing for normal development.  It may be possible to warn about file dependencies outside of the package root, though I'm not sure if that would result in false positives. Some projects may do this intentionally if they have no intention to publish to a registry.

**Comment by MetaDark** [comment]
Ok thank you, that makes sense. I was worried this was a more general problem, but since this is only isolated to unpublished packages I will close this.
