### ISSUE TITLE
Minor: Some creates have problematic permissions.

### ISSUE THREAD

**Issue by cheako** [rust-lang/cargo#7793]
I did something that is at best unsupported and through that experiment I discovered that not all crates are as identical as they should be.

I used a tool from X11-utils pkg called ```lndir```, it creates a directory tree of symlinks, for each directory it finds it'll create a directory and for anything else it creates a symlink.  This has been used for a long time to 'clone' source code trees.

I did this with the .cargo and .rustup folders from another user.  Some of the unpackaged create files had read permissions turned off for this other user.

Some examples:
base64-0.10.1
tempfile-3.1.0
unicode-xid-0.2.0

**Comment by alexcrichton** [comment]
Thanks for the report! This is likely best an issue for those crates themselves rather than this repository, since this is a function of the published crates themselves.

**Comment by cheako** [comment]
That's a good point, but it speaks to the selection or archive technologies.  This ticket should server as a reminder that the current strategy has more features that intended, in that the archive format should have exactly what's needed and not more.
