### ISSUE TITLE
tests unoptimized with opt-level = 2

### ISSUE THREAD

**Issue by giarc3** [rust-lang/cargo#7795]
@giarc3 commented on [Mon Jan 13 2020](https://github.com/rust-lang/rust/issues/68187)

With a Cargo.toml that contains
```
[profile.dev]
opt-level = 0

[profile.test]
opt-level = 2
```
running `cargo t --no-run --verbose` results in: 
```
Finished test [unoptimized + debuginfo] target(s) in 2m 44s
```
even though `opt-level = 2` is included in the rustc command. This shows that the build did use the `test` profile, but did not add optimization.

However, changing it to 
```
[profile.dev]
opt-level = 1

[profile.test]
opt-level = 2
```
and running `cargo t --no-run --verbose` results in: 
```
Finished test [optimized + debuginfo] target(s) in 6m 39s
```

This implies that test compilation uses optimization from `[profile.dev]` instead of `[profile.test]` as expected.

## Meta
`rustc --version --verbose`:
```
rustc 1.40.0 (73528e339 2019-12-16)
binary: rustc
commit-hash: 73528e339aae0f17a15ffa49a8ac608f50c6cf14
commit-date: 2019-12-16
host: x86_64-unknown-linux-gnu
release: 1.40.0
LLVM version: 9.0
```

---

@jonas-schievink commented on [Mon Jan 13 2020](https://github.com/rust-lang/rust/issues/68187#issuecomment-573844086)

`cargo test` builds the crate twice, once just like `cargo build` does, using the `dev` profile, and once using the `test` profile and passing `--test` to the compiler. Could it be that Cargo just prints what it used for the non-test compilation?

In any case, since this is a Cargo issue this should be filed over at https://github.com/rust-lang/cargo, not here

---

@giarc3 commented on [Mon Jan 13 2020](https://github.com/rust-lang/rust/issues/68187#issuecomment-573848091)

From the speed of the tests, I think that I can confirm that it is indeed unoptimized when it prints out as such. 
I was unsure of where to open the issue, as I do see Cargo correctly passing `-C opt-level=2` and thought that that implied it was a rust issue. I apologize if I was incorrect.

---

@sfackler commented on [Mon Jan 13 2020](https://github.com/rust-lang/rust/issues/68187#issuecomment-573848559)

rustc doesn't print the `Finished test ...` line, cargo does. This issue should be filed over there.

**Comment by ehuss** [comment]
Yea, the `Finished` line has not been terribly accurate, since it prints the mode for the library itself.  When multiple things are built with different profiles, it's not really clear which value it should print.

As mentioned, the behavior is that the dependencies use the `dev` profile, and the tests themselves (the final binary) uses the `test` profile.  There is a diagram at https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#profile-selection that shows how this works.  (Note: this is a known point of confusion, and we're still contemplating how it should work.)

**Comment by giarc3** [comment]
Thank you for the clarification
