### ISSUE TITLE
Support `rustc-link-args` in order to properly pass `-pthread` and flags

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#7796]
On rust-lang/rust#62117 it was discovered that certain C/C++ dependencies need to be linked with `-pthread` instead of `-lpthread` on certain platforms such as riscv64 and some arm cases.

Currently there is no way for a `build.rs` script to express this however. The closest thing is `rustc-dylib-link-args` which only applies when building a cdylib.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/cargo/pull/7811

**Comment by XieJiSS** [comment]
Just a reminder: This should be closed by #8441

**Comment by ehuss** [comment]
Closing, as it does sound like this is resolved, at least when using build scripts ([docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html)).
