### ISSUE TITLE
`cargo:rerun-if-env-changed` and `dotenv`

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/cargo#7802]
It seems like adding environment variables to cargo via `build.rs` doesn't trigger a rebuild when used with `cargo:rerun-if-env-changed`.

e.g. `build.rs`

```rust
fn main() {
    match dotenv::dotenv() {
        Ok(_) => (),
        Err(e) if e.not_found() => (),
        Err(e) => panic!("{}", e),
    };

    println!("cargo:rerun-if-env-changed=MY_ENV_VAR");
    println!(
        "cargo:rustc-env=MY_ENV_VAR={}",
        std::env::var("MY_ENV_VAR").unwrap()
    );   
}
```

If `MY_ENV_VAR` is changed in `.env`, then the project won't update to use the new value.

I work around this by deleting `target/release/build/my_package-*` to force a rebuild.

**Comment by derekdreery** [comment]
I'm not sure if this is a bug or not, but I thought I'd report it just in case there is interest.

**Comment by ehuss** [comment]
I don't think this would be possible for Cargo to check.  The value of `MY_ENV_VAR` before the build script runs would always be unset.  In this case, I think you would need to print `rerun-if-changed` for the `.env` filenames.

**Comment by derekdreery** [comment]
@ehuss Thankyou for a suggested workaround :).

Could/should cargo check the environment *after* the build script has run, rather than before?

**Comment by sfackler** [comment]
There is no way to check what the environment of a process that has exited was.
