### ISSUE TITLE
Cargo build fails: tarfile.ReadError

### ISSUE THREAD

**Issue by Michele31415** [rust-lang/cargo#7806]
While attempting to build cargo on a Sun T4-1 running Solaris 11.4 using the script https://github.com/starius/config/blob/master/.bin/install-rust from here https://github.com/rust-lang/cargo/issues/3437#issuecomment-574447699

I get the following:

root@hemlock:/scratch/solaris-userland/components/rust# ./makerust.sh
+ RUST_ROOT=/export/home/michele/.rust-root
+ RUST_SRC=/export/home/michele/src/github.com/rust-lang/rust
+ CARGO_SRC=/export/home/michele/src/github.com/rust-lang/cargo
+ '[' '!' -d /export/home/michele/src/github.com/rust-lang/rust ']'
++ mktemp -d
+ RUST_BUILD=/tmp/tmp.6wOCSc
+ cd /tmp/tmp.6wOCSc
+ /export/home/michele/src/github.com/rust-lang/rust/configure --prefix=/export/home/michele/.rust-root --disable-docs
configure: processing command line
configure: 
configure: build.docs           := False
configure: install.prefix       := /export/home/michele/.rust-root
configure: build.configure-args := ['--prefix=/export/home/michele/.rust-root', '- ...
configure: 
configure: writing `config.toml` in current directory
configure: 
configure: run `python /export/home/michele/src/github.com/rust-lang/rust/x.py --help`
configure: 
+ gmake -C /tmp/tmp.6wOCSc -j 4
gmake: Entering directory '/tmp/tmp.6wOCSc'
Updating only changed submodules
Submodules updated in 0.28 seconds
downloading https://static.rust-lang.org/dist/2019-12-18/rust-std-beta-sparcv9-sun-solaris.tar.gz
######################################################################### 100.0%
verifying /tmp/tmp5UbUjR
extracting /tmp/tmp.6wOCSc/build/cache/2019-12-18/rust-std-beta-sparcv9-sun-solaris.tar.gz
downloading https://static.rust-lang.org/dist/2019-12-18/rustc-beta-sparcv9-sun-solaris.tar.gz
######################################################################### 100.0%
verifying /tmp/tmpJ6kNUH
extracting /tmp/tmp.6wOCSc/build/cache/2019-12-18/rustc-beta-sparcv9-sun-solaris.tar.gz
Traceback (most recent call last):
  File "/export/home/michele/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 971, in <module>
    main()
  File "/export/home/michele/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 954, in main
    bootstrap(help_triggered)
  File "/export/home/michele/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 920, in bootstrap
    build.download_stage0()
  File "/export/home/michele/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 376, in download_stage0
    self._download_stage0_helper(filename, "rustc", tarball_suffix)
  File "/export/home/michele/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 427, in _download_stage0_helper
    unpack(tarball, tarball_suffix, self.bin_root(), match=pattern, verbose=self.verbose)
  File "/export/home/michele/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 112, in unpack
    with contextlib.closing(tarfile.open(tarball)) as tar:
  File "/usr/lib/python2.7/tarfile.py", line 1680, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
gmake: *** [Makefile:18: all] Error 1
gmake: Leaving directory '/tmp/tmp.6wOCSc'
root@hemlock:/scratch/solaris-userland/components/rust# 

I'm not sure what to make of this.  Which "file could not be opened successfully" and why not?

I note someone else with the same problem here: https://github.com/felipecode/coiltraine/issues/6 but no resolution.

**Comment by ehuss** [comment]
Solaris is not a platform that has pre-built images, which is required for bootstrapping.  You might want to check one of the user forums to see if anyone has successfully bootstrapped on your platform.

**Comment by Michele31415** [comment]
Um, now I'm confused.  A pre-built image is required for bootstrapping?  But I thought bootstrapping was what built the image.  It did download some file that contained SPARC, V9, Sun and Solaris in its name so I figured I was on the right track.  And it looks to me like the C compiler is trying to compile something.

I haven't been able to find anyone with a rust compiler for Solaris SPARC, although such a thing must exist somewhere since Oracle is now distributing Firefox 68 with the Solaris 11.4 updates.

**Comment by ehuss** [comment]
Since the Rust compiler is written in Rust, it needs a working `rustc` binary for your host platform to get started.  The bootstrapping system downloads the most recent beta release of the compiler to build itself.  However, the Rust project only builds and distributes the compiler for a limited number of platforms.

There is a larger set of the platforms `rustc` can *target*.  The rust compiler can cross-compile from other platforms (like Linux x86) to SPARC.   It's possible the Solaris Firefox is using cross-compiling from another host, I'm not sure.

There are a few ways to bring up rustc on a new host:
1. Cross compile from another host where `rustc` binaries are already available.
2. Find a working OCaml compiler, and start from the first release of Rust (which was originally written in OCaml). I suspect this would be extremely difficult nowadays, and take a very long time.
3. Use a Rust compiler not written in Rust, such as [mrustc](https://github.com/thepowersgang/mrustc).

**Comment by Michele31415** [comment]
I believe Oracle uses a Rust compiler made using the github solaris userland stuff but I haven't been able to get that to work either.  I do have a working Rust in Ubuntu but figuring out how to cross compile anything with that is daunting.  So I'll have a look at mrustc.  Thanks for the suggestions.
