### ISSUE TITLE
Build Script Isn't Run for Examples

### ISSUE THREAD

**Issue by solarane** [rust-lang/cargo#7816]
**Problem**
When I place a build script inside an example and run it with `cargo run --example <my-example>`, it seems that the build script does not get run.

**Steps**

1. Create a new example:
```toml
[[example]]
name = "hello-world"
path = "examples/hello-world/src/main.rs"
```
2. Create a `build.rs` build script inside `examples/hello-world/` with the following content:
```rust
fn main() {
    eprintln!("Hello, World!");
}
```
3. Run the example using `cargo run --example hello-world -vv`
4. Observe that "Hello, World!" is not printed to the console

**Possible Solution(s)**

**Notes**
I'm not entirely sure if this is a bug or if this is intended behavior, but I couldn't find any documentation stating examples didn't support build scripts. I apologize if this *is* documented somewhere and I just missed it, but either way it's not made very obvious.

Output of `cargo version`: cargo 1.40.0 (bc8e4c8be 2019-11-22)

**Comment by sfackler** [comment]
Build scripts operate at the crate level, not at the individual example level.

**Comment by solarane** [comment]
Wow, that was fast. So if a library crate's functionality requires build-time operations to demonstrate, cargo examples won't work for the library in question?

**Comment by solarane** [comment]
> Build scripts operate at the crate level, not at the individual example level.
Also, this doesn't make much sense to me.
The following is valid:
```toml
[[example]]
name = "foo"
crate-type = ["staticlib"]
```
Note the `crate-type`. I don't see why build scripts shouldn't run for examples, unless explicitly documented as such.

**Comment by sfackler** [comment]
To be more precise, build scripts are a property of the overall *package*, not an individual target, like the library, or a binary, or an example.

If you need a build script that's specific to an example, I'd split it off into a separate crate.

**Comment by solarane** [comment]
Ah, that makes a bit more sense. Thanks for the super quick response! Closing this now.
