### ISSUE TITLE
Provide target-cpu and target-features to buildscripts

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/cargo#7828]
As far as I can see there is no reliable way for a buildscript to determine the value of `target-cpu` and `target-features`. Could we add and env-flag for Cargo to provide the values that will be used _when the final crate is compiled for the target platform_?

Downstream feature request from [here](https://github.com/lukaslueg/built/issues/22)

**Comment by ehuss** [comment]
Target features should be exposed in the `CARGO_CFG_TARGET_FEATURE` environment variable.  The request to expose the target-cpu is tracked in https://github.com/rust-lang/rust/issues/44036.

**Comment by ehuss** [comment]
Going to close since supporting target-cpu is tracked in rustc.
