### ISSUE TITLE
Is there any way to make code changes work faster? 

### ISSUE THREAD

**Issue by insub** [rust-lang/cargo#7839]
I develop a rust + rocket project right now.
But every time I change the code, even if it's only one file, I have to wait 50s to recompile it, Is it normal to consume this time?
[
cargo run --features sqlite
....
Finished dev [unoptimized + debuginfo] target(s) in 53.89s
]
BTW, the cargo's incremental build look like work.

Does this mean that if I modify a api or view, I have to wait 50 seconds before actually preview it on the browser?
After I modify the code, I hope to preview it on the client. Is there any way to make code changes work faster?(i'm a javascript coder, i don't have compiled language work experience)

**Comment by insub** [comment]
i rty to i set debug=0 && codegen-units=1 , then run :
cargo rustc --features sqlite -- -Z time-passes
The compilation time reduced to 30s !
and the following tasks take a more times:

time: 12.916 expand crate
time: 2.944 monomorphization collection
time: 4.509 linking
time: 4.560 codegen

Any suggestions?

**Comment by ehuss** [comment]
The amount of time will depend heavily on your project, the kind of changes you make, your hardware, etc.  For example, for me working on Cargo itself, rebuild times tend to be about 20s.

There are several things you can do to reduce build times.  You can split your project into multiple crates. You can be more careful with using generics (use them less, avoid large generic functions, etc.).  

Questions like these are best asked on one of the user forums, as the issue tracker here is for specific bugs.

**Comment by insub** [comment]
@ehuss ok. thank you.
