### ISSUE TITLE
Cargo build uses a very high amount of memory

### ISSUE THREAD

**Issue by alexbowers** [rust-lang/cargo#7842]
**Problem**
Currently I can not build a cargo binary on my laptop because it uses so much memory (72GB).

Eventually it crashes, and I get "Killed" in the console output, and if i run `echo $?` i get 137 as the exit code.

![image](https://user-images.githubusercontent.com/842974/73264023-b8a0cf80-41c9-11ea-8569-f4b8c1fc7279.png)

```
alex@Alexs-MacBook-Pro static-server % cargo build
   Compiling ring v0.16.9
   Compiling quote v1.0.2
   Compiling quote v0.6.9
   Compiling unicase v1.4.2
   Compiling idna v0.1.5
   Compiling rocket_codegen v0.5.0-dev (https://github.com/SergioBenitez/Rocket#f35e3c4a)
   Compiling serde v1.0.80
   Compiling rocket v0.5.0-dev (https://github.com/SergioBenitez/Rocket#f35e3c4a)
   Compiling mime v0.2.6
   Compiling num_cpus v1.8.0
   Compiling url v1.7.2
zsh: killed     cargo build
```

Unsure how to debug this down to something that is helpful.

Output of `cargo version`:

```
rustc 1.42.0-nightly (8a79d08fa 2020-01-27)
cargo 1.42.0-nightly (b68b0978a 2020-01-24)
```

Mac OS X 10.15.2

**Comment by ehuss** [comment]
Thanks for the report, this will be fixed in the next nightly.

**Comment by alexbowers** [comment]
This may be a daft question, but when do nightlies get built? Is it every night? Every few days?

**Comment by ehuss** [comment]
No worries, it's a good question. 😄   The release cron job starts at midnight 00:00 UTC, and I think takes about 30 to 60 minutes to package and upload.  So, roughly, every day shortly after midnight utc.

**Comment by alexbowers** [comment]
Thanks! 

if the nightly tomorrow doesn't fix it, what should I do? Come back here, or open a new issue?

Is there any other information that would help to track issues like this down in future?
