### ISSUE TITLE
`DEP_*` environment variable documentation not clear

### ISSUE THREAD

**Issue by indygreg** [rust-lang/cargo#7846]
**Problem**

https://doc.rust-lang.org/cargo/reference/build-scripts.html says:

```
Any other element is a user-defined metadata that will be passed to dependents. More information about this can be found in the links section.
```

This implies to me that `DEP_*` variables will always be set if they are emitted by a dependent crate.

But if you read the linked https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key it starts to mention association with the `links` manifest key. It doesn't say so explicitly, but experimentation reveals the `links` key is required in order for `DEP_*` variables to be set on the dependent crate.

**Possible Solution(s)**

Clarify documentation that `links` is necessary to make `DEP_*` appear.

Even better would be to always set the `DEP_*` environment variables. Cargo seems to lack a generic way to pass metadata between crate build scripts outside of library/linkage info. I frequently find myself wanting this feature for indygreg/PyOxidizer, which is doing some wonky things in build scripts. It would be **immensely** useful if state could be passed between dependencies via environment variables. I'm sure there is already a feature request for that somewhere though...

**Notes**

Output of `cargo version`:

`1.40.0`

**Comment by ehuss** [comment]
The build script chapter has been largely reworked, which I think should go live tomorrow with the new release.  https://doc.rust-lang.org/beta/cargo/reference/build-scripts.html   Perhaps you can take a look and see if it makes it clearer that it is `links` specific?

As for passing more information, I think that is covered by #3544?

**Comment by indygreg** [comment]
The new docs say `cargo:KEY=VALUE — Metadata, used by links scripts.` and the docs for `[links]` appears largely unchanged. I think I'd like to see an _only used by_ where it defines the `cargo:KEY=VALUE` syntax.

#3544 does appear to track the feature I want!

**Comment by ehuss** [comment]
Would be happy to have a PR that clarifies whichever parts are not clear.
