### ISSUE TITLE
Place artifacts of the default target into a subdirectory of ./target

### ISSUE THREAD

**Issue by huonw** [rust-lang/cargo#785]
We currently have `cargo build` putting things in `./target` and `cargo build --release` putting them in `./target/release`. This [leads to confusion](http://www.reddit.com/r/rust/comments/2kp1di/presenting_rustimage_v01/clo0mxc?context=3), and could be improved by instead building everything to a subdirectory, e.g. `./target/debug` for the default target.

(It occurs to me that the current scheme could fail catastrophically if a binary was called `release`.)

**Comment by lahwran** [comment]
just wanted to point out that cargo could simply print the relative path of the binary it wrote, and then a whole class of confusion is avoided.
