### ISSUE TITLE
`cargo new` hangs if hg hangs in existing_vcs_repo

### ISSUE THREAD

**Issue by luser** [rust-lang/cargo#7881]
I had changed something about my `pyenv` environment which caused my installed `hg` binary to hang. This caused `cargo new` to hang and it took me a while to figure out why.

It looks like [`existing_vcs_repo`](https://github.com/rust-lang/cargo/blob/ad3dbe10e1e654fb1f032a5dd9481d7cbaa00d65/src/cargo/util/vcs.rs#L11) calls [`HgRepo::discover`](https://github.com/rust-lang/cargo/blob/ad3dbe10e1e654fb1f032a5dd9481d7cbaa00d65/src/cargo/util/vcs.rs#L48) which runs `hg` using `exec_with_output`.

Perhaps for something like this that's non-critical it'd be useful to have a version of that exec with a timeout? Even printing an error like "process ran for too long: hg ran for <duration> before timeout" and failing the process would have made diagnosing this a lot easier.

**Comment by epage** [comment]
This seems very specialized.  Among the different external process we call, this is likely the only type that a timeout would work reasonably well on.  If one of these other external tools hung, we wouldn't be able to handle it either.  As the case for this seems very specialized (and timeouts can be fairly problematic to implement and support), I'm going to go ahead and close this.  If there is a reason we should re-evaluate this, let us know!
