### ISSUE TITLE
`cargo fix` uses wrong `crlf` git setting for deciding which newlines to use

### ISSUE THREAD

**Issue by Boscop** [rust-lang/cargo#7882]
On Windows in my repo where files have unix line ending I ran `cargo fix --edition`.
I noticed, I had a huge diff: The line endings were switched to windows.
Someone pointed out to me that it could be my crlf setting that cargo fix is using, but I have it off:
```
> git config --global core.autocrlf
false

> git config core.autocrlf
false

> git config --get core.autocrlf
false
```
At least I thought. But `git config --list` showed `core.autocrlf=true`!
It turns out, it was set to true in `D:\Program Files\SmartGit\git\mingw64\etc\gitconfig`, but not in my HOME .gitconfig (it was set to false there).
Anyway, after I also set it to false there, and did git reset and reran cargo fix, the newlines were preserved as unix.

So the bug consists of cargo not looking up the setting correctly.
Or even: Cargo should just not use that setting but preserve each file's current newline format!

**Comment by ehuss** [comment]
I'm not sure I can see how to reproduce this.  Neither cargo, rustfix, or rustc look at git for crlf behavior. Rustfix only works on byte offsets, it cannot modify line endings.

If SmartGit was configured for windows newlines, then maybe smartgit is responsible for changing them?  Or maybe some other tool or editor was running and modified them for you?

**Comment by Boscop** [comment]
Hm, no other tool was modifying the files..
I only used SmartGit to see that the newlines had been changed by `cargo fix`, which I ran in `cmd.exe` that uses a `PATH` that contains the `bin` dir from SmartGit (so it uses the same git.exe. Btw, in my .cargo/config I have `[net] git-fetch-with-cli = true`).

**Comment by ehuss** [comment]
`cargo fix` doesn't use git at all, so I don't think that is related.

If you can create an exact set of steps to reproduce the issue, that would help.  Otherwise, I don't think there's anything we can do here.

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. Feel free to comment below or open a new issue if there is any update.
