### ISSUE TITLE
cargo prints color inside docker build despite --color=never

### ISSUE THREAD

**Issue by larstobi** [rust-lang/cargo#7884]
**Problem**
```cargo build``` still prints color when running in ```docker build``` even with ```--color=never``` option specified.

Dockerfile:

    FROM alpine:edge as builder
    RUN apk add --no-cache rust cargo
    WORKDIR /code
    COPY . .
    RUN cargo install --path . --color=never

Alpine Linux Edge installs rust and cargo version 1.41.

**Steps**
1. ```docker build -t code:latest .```
2. Watch colors being printed.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

* cargo 1.41.0
* Same result on both Docker for Mac and AWS Codebuild with standard:2.0 builder image.

**Comment by ehuss** [comment]
Can you post a screenshot of what you are seeing?  I see this:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/43198/74469760-239d0800-4e52-11ea-8991-29f822c9466b.png">

This is normal behavior for Docker.  It prints all stderr content in red.

**Comment by larstobi** [comment]
Thanks, that helped. I changed the cargo command to this, and then it stopped printing red:

```RUN cargo install --path . --color never 2>&1```

Why is cargo build output printed to stderr even when there are no build errors?

**Comment by larstobi** [comment]
I guess I'll answer my own question.

POSIX defines:

* standard output = for writing conventional output
* standard error = for writing diagnostic output

Build progress is a diagnostic output so it belongs to standard error.
