### ISSUE TITLE
cargo metadata --no-deps includes all packages in the workspace

### ISSUE THREAD

**Issue by sfackler** [rust-lang/cargo#7893]
**Problem**

The `--no-deps` flag of `cargo-metadata` is documented as such

```
        --no-deps                     Output information only about the root package and don't fetch dependencies
```

From that, I would expect that the output would only include a single package. However, when run in a workspace, information about *all* packages in the workspace is output.

**Steps**

1. Find a workspace with multiple packages.
2. Run `cargo metadata --no-deps --format-version 1`
3. Observe multiple packages in output

**Notes**

Output of `cargo version`: `cargo 1.41.0 (626f0f40e 2019-12-03)`

**Comment by ehuss** [comment]
Would you be OK with just updating the help page?  I don't think it's something we can change.  Does it cause a problem in some way?

**Comment by sfackler** [comment]
Ideally there'd be a better way of using cargo-metadata with crate-oriented operations, but minimally the help docs should say how it behaves here.

**Comment by ehuss** [comment]
I filed #7927 as a simple doc fix.  As for the way `cargo metadata` handles the "current" package, I agree it is limiting and confusing.  I think #4018 and #7754 cover that problem, though.
