### ISSUE TITLE
Is there an scriptable way to get the final binary which cargo run uses?

### ISSUE THREAD

**Issue by zserik** [rust-lang/cargo#7895]
I want to run the program built by `cargo build [--release]` in a loop, but I haven't found a way to get the path the produced binary "programmatically" (e.g. automatable).
I have multiple developing machines with differing [`target-dir`](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir)'s, thus, on some machines, the target dir would be `./target/`, but on others it would be `/mnt/path/to/target.x64/` or something like that, which makes the [easier approach](https://github.com/rust-lang/cargo/issues/3773) (just using `target/release/$binname`) unusable. Running `cargo run [--release]` in a loop is currently not a good solution because each call introduces an overhead and additional output which is (at least) annoying.

* Is there already a way to get the produced binary path "programmatically"?
* Or a way to prevent `cargo run` from trying to `rebuild` the program every time + suppress the `Finished` message?

**Comment by zserik** [comment]
Usage example for "easier approach: https://github.com/zserik/crulz-rs/blob/827b7b76a58c381d500da079330f0707957c892b/run_examples.sh

**Comment by ehuss** [comment]
`cargo run --message-format=json` will emit "compiler-artifact" messages with the path to the binary ([docs](https://doc.rust-lang.org/cargo/reference/external-tools.html#artifact-messages)). 

Alternatively, you can run `cargo metadata` and look at the `"target_directory"` field to know which target directory is used.  You can also scan the packages binary targets if you don't know the names.  [docs](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html)

#3670 tracks some ideas for future enhancements.

**Comment by zserik** [comment]
Ok. Is this (`cargo metadata`) documented somewhere? I think it should be mentioned in the `.cargo/config` page linked above.

**Comment by zserik** [comment]
@ehuss Thanks.

**Comment by zserik** [comment]
for future reference, working version using `cargo metadata`: https://github.com/zserik/crulz-rs/blob/a8b9c124e1ac5d878f563a17b416fa326167eae0/run_examples.sh

**Comment by hoijui** [comment]
The previous link gets one to the output ("target") directory. you you know the binary name, you can manually just add it like it is done there. if not, you can get the binary name from `cargo metadata` too, as explained here:
https://users.rust-lang.org/t/what-is-the-best-way-to-get-the-name-of-the-binary-that-cargo-will-produce/17907/4

**Comment by wr7** [comment]
For anyone else that finds this on google, here's a script that directly uses `cargo build`:
```sh
#!/bin/sh

json=$(cargo build --message-format=json-render-diagnostics "$@") && \
printf "%s" "$json" | jq -js '[.[] | select(.reason == "compiler-artifact") | select(.executable != null)] | last | .executable'
```
Flags for `cargo build` are forwarded from the script's arguments.
