### ISSUE TITLE
Make `repository` mandatory in Cargo.toml to find repositories easily

### ISSUE THREAD

**Issue by gfx** [rust-lang/cargo#7897]
When I walk in crates.io, sometimes a crate has no `repository` URL, which makes it difficult to find its repository. I think this is really problematic in finding libraries for a Rust program.

If the `repository` metadata in Cargo.toml is required, most of this issue should be solved.

**Comment by ehuss** [comment]
I don't think we can make it mandatory, as we don't want to require a public repository to publish. This is particularly true of local and private registries.  Cargo will warn if the homepage/repository/documentation fields are not set.  

I'm not sure how the repository URL is related to finding libraries.  If crates.io is not providing enough information, you may want to check the crates.io issue tracker: https://github.com/rust-lang/crates.io/issues

I'm going to close, but if you have any questions, feel free to ask.

**Comment by gfx** [comment]
Thanks for your reply. Yes, it does not need to be mandatory for private projects, so how about to make warnings for missing `repository` on public projects  (i.e., when `publish` is not `false`)?
 I believe it is one of the best practices to follow for those who publish crates.

**Comment by ehuss** [comment]
It should display a warning if the repository/homepage/docs fields are not set in `cargo package` and `cargo publish`.
