### ISSUE TITLE
cargo --help needs network access?

### ISSUE THREAD

**Issue by gilescope** [rust-lang/cargo#7898]
Small niggle:

Cargo --help doesn't look good if it can't phone home:
```
>cargo --help
info: syncing channel updates for 'nightly-2020-01-21-x86_64-pc-windows-msvc'
error: could not download file from 'https://static.rust-lang.org/dist/2020-01-21/channel-rust-nightly.toml.sha256' to 
```
Is it possible to reorder things slightly so `--help` gets checked before trying to upload from crates.io? (Train of thought: I was looking in the help to see if I could get it to tell me where it thinks it's config is and what configuration its currently picked up)

**Comment by alexcrichton** [comment]
Thanks for the report, but this is an issue with the rustup wrapper around Cargo rather than Cargo itself.
