### ISSUE TITLE
Tracking issue for -Z crate-versions

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#7907]
Implementation: #7903
Original issue: #1681

**Summary**

`-Z crate-versions` will add the crate version to `cargo doc` via the unstable rustdoc flag.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/43198/74869839-8fc5b300-530d-11ea-90fd-440a36ee9cbe.png">

**Unresolved issues**

* [x] Need to stabilize `--crate-version` in rustdoc. DONE: https://github.com/rust-lang/rust/pull/69494
* [ ] Wait for `--crate-version` to hit stable (1.44 on June 4th).  (This is done so we don't have to query rustdoc if it supports the flag.)

**Comment by aleksator** [comment]
What needs to be done to stabilize both features (rustdoc's and cargo's parts)?
I'd be happy to do the required work.

**Comment by ehuss** [comment]
First step would be to follow up with the rustdoc team to figure out if there is a reason it hasn't been stabilized, yet.  Maybe ask on their channel on Discord?

Also, I just thought of a concern about how it works. The standard library passes a custom string to the flag. If Cargo starts passing the flag, it will fail since the flag is passed multiple times. We'll need to figure out some solution for that. Offhand I don't have any ideas.  If they're OK with dropping the git hash/date, then maybe we can just remove the custom code when building the standard library.  Maybe follow up with the docs people about that, too.

**Comment by aleksator** [comment]
Stabilization in rustdoc has landed.
The next steps are to wait until it has reached rustc's stable branch and then it would be possible to pass the flag by default in cargo.

**Comment by ehuss** [comment]
@aleksator would you be willing to open a PR to stabilize this in Cargo?  If not, that's ok, just wanted to check.

**Comment by aleksator** [comment]
@ehuss Sorry I wasn't available. Thank you for doing the PR, looks good to me.

**Comment by aleksator** [comment]
I'm happy this is finally in: it completes the first issue I picked up for Rust project. Thank you @ehuss for the guidance!
