### ISSUE TITLE
Tag for 0.42 missing

### ISSUE THREAD

**Issue by jnbr** [rust-lang/cargo#7910]
Cargo-1.41 / 0.42 has been release a few weeks ago but there is no tag for cargo-0.42 on github.
If there is no reason why it is missing, it would be helpful if someone can create it.

**Comment by ehuss** [comment]
I tagged 0.42.0 at 626f0f40efd32e6b3dbade50cd53fdfaa08446ba

@Mark-Simulacrum or @pietroalbini, can tagging be automated during the release process? Or, can it be added to a release checklist?

**Comment by jnbr** [comment]
Thank you.

**Comment by jnbr** [comment]
The tag looks a bit old though.

**Comment by Mark-Simulacrum** [comment]
Hm, the tag is in the release process. Perhaps @pietroalbini forgot to push it last time?

**Comment by pietroalbini** [comment]
Uh maybe. Woops.

**Comment by ehuss** [comment]
> The tag looks a bit old though.

I made a "lightweight" tag, as that is what the other tags looked like.  I believe the date for those is the commit date.  Since beta takes 6 weeks, and we didn't do any beta backports, and there aren't commits every day, Dec 3 was the last day a commit was made for that release.

**Comment by jnbr** [comment]
I would have expected the tag cargo-0.42.0 tag to be in sync with rust-1.41.0.
Did cargo stop being in sync with rust-1.(cargo.minor - 1).0 ?

**Comment by ehuss** [comment]
> I would have expected the tag cargo-0.42.0 tag to be in sync with rust-1.41.0.

It is.  You can see the rust-1.41.0 branch at https://github.com/rust-lang/rust/tree/1.41.0/src/tools, where the last cargo update was 626f0f4.

If you mean the rust-1.41.0 branch here on the cargo repo (https://github.com/rust-lang/cargo/commits/rust-1.41.0), there was one extra commit made (for testing purposes), but was never upstreamed because it wasn't needed.

**Comment by jnbr** [comment]
Alright, thanks for clarifying.
