### ISSUE TITLE
Want to change e.g. README file without rebuilding and update lock file

### ISSUE THREAD

**Issue by montao** [rust-lang/cargo#7920]
**Describe the problem you are trying to solve**

I have a repository https://github.com/montao/spooks
That uses cargo for a crate. But if I want to change just the README and correct a typo, then I must rebuild it locally because it requires the lock file to regenerate. This makes it not possible to change the files of my project without regenerating the lock file. Therefore I cannot update the documentation e.g. the README because that requires the version in Cargo.toml to change and that requires in its turn that the lock file must change and I must shave the Yak locally.

**Describe the solution you'd like**

Make it easy just to make a small update, bump the version so that I can publish a new version of my crate without regenerating the lock file.
**Notes**

**Comment by ehuss** [comment]
This is unfortunately necessary due to the way README is tied to the published crate file.  I'm going to close this in favor of the request at https://github.com/rust-lang/crates.io/issues/1750 which covers this, as this is a repository issue.
