### ISSUE TITLE
Scaffold modules with cargo new

### ISSUE THREAD

**Issue by thedrow** [rust-lang/cargo#7923]
**Describe the problem you are trying to solve**
One of the things I haven't figured out yet is how to use modules with Rust. I don't know why I'm having trouble with them but I do. I'm assuming I'm not the only beginner that has that problem.

**Describe the solution you'd like**
I'd like `cargo new` to scaffold new modules. The command should be something like `cargo new --module --public modname`. I'd also accept the full module referencing syntax e.g. `cargo new --module --public modname::inner_mod`.

If modname already exists, only `inner_mod` should be created.

The output of the program needs to explain how to import it to `lib.rs` or `main.rs`.

**Notes**
None.

**Comment by weihanglo** [comment]
Thanks for the feature request. 

I am seeing this as an IDE feature. Intellij Rust and rust-analzyer should have alrady supported it by different approaches, i.e. <https://github.com/rust-lang/rust-analyzer/issues/4200#issuecomment-621012262>. To myself, doing this inside editors is smoother than jumping between editors and terminals.

If you're talking about scaffolding a new package with a desired module layout, <https://github.com/rust-lang/cargo/issues/5151> is the way to go.

Given the above mentioned, I am going to close this. Please let us know if there is something I am missing and this should remain open.
