### ISSUE TITLE
Filter invalid CARGO_CFG_ in build scripts

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#7933]
The environment variables `CARGO_CFG_DEBUG_ASSERTIONS` and `CARGO_CFG_PROC_MACRO` are set when a build script is executed.  These variables have no meaning, due to the way `cfg` discovery is done.  The build script code should probably avoid setting these two values to avoid any possible confusion.

Cargo has been issuing a warning for a little while for using these in `cfg` expressions, so I think it should be OK to just filter these two values entirely.  `cfg` values are collected [here](https://github.com/rust-lang/cargo/blob/9ac6af8d17b5903c515c3d4730e046e8714bfc05/src/cargo/core/compiler/build_context/target_info.rs#L152-L160), so I think just filtering them there at the source should be ok.

**Comment by aleksator** [comment]
Isn't it better to stop setting those variables altogether instead of filtering them out? If they aren't used at all, that is.

**Comment by ehuss** [comment]
In Cargo's `TargetInfo`, it collects these `cfg` values by querying `rustc`.  `proc_macro` is set because Cargo queries all crate types at once, and `proc_macro` is included in the list.  `rustc` sets `debug_assertions` by default, and I don't think it is really necessary to try to unset it with `-C debug_assertions=off` (that is an option, but it seems easier to just filter it so that these exceptions are listed in one place).

**Comment by aleksator** [comment]
Got it: those variables are of use on users' side, but shouldn't be on Cargo's side.
Let me do the required change.
