### ISSUE TITLE
Duplicate dependency checking for CI

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/cargo#7941]
(Filing this issue based on a discussion from the cargo team meeting today.)

For use in CI, we'd like to have an option for a gentle nudge to fix duplicate dependencies in your dependency graph, which doesn't fail unless you can actually fix the problem without having to fix your dependencies. The algorithm would be "pretend that all of your direct declared dependencies (and also dependencies from crates in your workspace or that use path dependencies) that use ~ (semver compatible) used >= instead, resolve dependencies accordingly, and if that would eliminate a duplicate, report it as a failure".

That way, you don't get a CI failure for something that you can't actually fix yourself by just fixing your Cargo.toml.

See also https://github.com/sfackler/cargo-tree/issues/87 .

**Comment by ehuss** [comment]
cc #7285

**Comment by epage** [comment]
Closing in favor of #7285
