### ISSUE TITLE
Delete files in target folder that are no longer needed

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/cargo#7948]
My problem is that I have a lot of projects, which takes up disc space. From time to time I need to go through projects and delete "target" folders. I checked the size of these folders, and I wonder why they can be over 1GB in size sometimes.

If possible, I would like a command working like "cargo build", but in addition removes the files that are no longer needed for this particular build.

I know that I can use "cargo clean", but this removes all files, including those who could save time for the next build.

**Comment by bvssvni** [comment]
Here is an example use case: I update dependency versions of libraries, which means that Cargo downloads a new version and builds it. However, it does not delete the old version when no longer needed. The old versions stays in the target folder and accumulate over time. If I delete the "target" folder, I need to wait for rebuilding all dependencies.

**Comment by ehuss** [comment]
Thanks for the suggestion.  There is a meta tracking issue for this at #7150 with links to various duplicate issues, so I'm going to close in favor of that.
