### ISSUE TITLE
`cargo new` ignores umask

### ISSUE THREAD

**Issue by jashank** [rust-lang/cargo#795]
If I create a new project from cargo 0.0.1-pre nightly 5c5255f (and reading the diff from there to master doesn't reveal anything obvious to me):

    > umask
    022
    > cargo new windchime
    > touch windchime/testfile
    > ls -ld windchime
    drwxr-xr-x  4 jashank jeremy 4096 Nov  4 20:46 windchime
    > ls -la windchime
    [...]
    -rw-------  1 jashank jeremy  100 Nov  4 20:46 Cargo.toml
    drwxr-xr-x  6 jashank jeremy 4096 Nov  4 20:46 .git
    -rw-------  1 jashank jeremy   20 Nov  4 20:46 .gitignore
    drwx------  2 jashank jeremy 4096 Nov  4 20:46 src
    -rw-r--r--  1 jashank jeremy    0 Nov  4 20:46 testfile
    > ls -l windchime/src
    [...]
    -rw-------  1 jashank jeremy   26 Nov  4 20:46 lib.rs

It seems `cargo new` ignores umask and behaves as if umask were 077. IMO this behaviour is incorrect (and violates POLA).

**Comment by alexcrichton** [comment]
I believe this is just the default behavior of the standard library. For example:

```rust
use std::io::File;

fn main() {
    File::create(&Path::new("bar"));
}
```

creates a file with 600 permissions locally for me (using a 002) umask. I think this issue may belong in the rust-lang/rust repo if you think the behavior should change.
