### ISSUE TITLE
cargo depends on crossbeam without needing it

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#7953]
The cargo crate transitively depends on crossbeam and crossbeam-util crates without actually using functionality provided by either of the two.

This increases compile time of tools like cargo-udeps, where users have (justifyably) complained about the large number of dependencies already https://github.com/est31/cargo-udeps/issues/13

The only dependency of cargo that uses crossbeam is the ignore crate, which can be found at https://github.com/BurntSushi/ripgrep/blob/master/crates/ignore/

However, that crate only uses it to create `WalkParallel` which is not used by cargo.

Solving this bug would involve the following steps:

1. Add "parallel" feature to the ignore crate
1. Clone cargo locally, check if only enabling the parallel feature works by [overriding the ignore crate dep](https://doc.rust-lang.org/nightly/cargo/reference/overriding-dependencies.html)
1. Get the PR to the ignore crate merged and a new version published
1. Use updated ignore crate in cargo

cc @BurntSushi

**Comment by est31** [comment]
Also please add the easy and help wanted labels, this should be a good beginner issue.

**Comment by ehuss** [comment]
I don't think this is currently possible.  Cargo now depends directly on crossbeam-channel ([Cargo.lock](https://github.com/rust-lang/cargo/blob/62180bf27d83e1d8785b32bbe4d6f6fb07fff4bc/Cargo.toml#L26-L27])), and has used crossbeam-utils for years.

**Comment by est31** [comment]
Oh I wasn't aware of that. Thanks for pointing it out. Obviously my request makes no sense then.
