### ISSUE TITLE
cargo test --test <testname> builds binaries

### ISSUE THREAD

**Issue by alkim0** [rust-lang/cargo#7958]
**Problem**
The documentation for cargo seems to suggest that if I run: `cargo test --test apple`, then, 
this should run test `apple` without compiling any of the binaries. However, this doesn't seem to be the case.

**Steps**
1. Build a new rust project using: `cargo new banana`.
2. Create a simple `lib.rs` file in `src/`. My contents were:
```
pub struct A {}
```
3. Create a binary directory `bin/` in `src/` then add a file `run.rs`; my contents were:
```
use banana::A;
fn main() {
    let a = A {};
    println!("Hi");
}
```
4. Create a tests directory `tests/` at the project root. Add a simple test file `sample.rs` with contents:
```
use banana::A;
#[test]
fn sample() {
    let a = A {};
    println!("Hi");
}
```
5. Run `cargo test --test sample`
6. `bin/run.rs` is compiled. We can tell since we can warnings about unused variables from it.

**Notes**

Output of `cargo version`:
```
cargo 1.43.0-nightly (e57bd0299 2020-02-21)
```

**Comment by ehuss** [comment]
This is done intentionally so that integration tests can execute the binaries to exercise their behavior.  Seems like it would be good to document that!  In general the Cargo documentation on writing tests is a little shallow.

**Comment by alkim0** [comment]
Yes, I figured, but according to the [Cargo Book](https://doc.rust-lang.org/cargo/commands/cargo-test.html), it says:

> Passing target selection flags will test only the specified targets.

and it also states that `--all-targets` is equivalent to:
```
--lib --bins --tests --benches --examples
```
implying that there is a way to build tests without binaries (since `--bins` is specifically specified).

I propose these parts be rewritten for clarity, or allow a way to build tests without binaries.

**Comment by ehuss** [comment]
There is not currently a way to skip building the binaries.

**Comment by weihanglo** [comment]
Seems a explanation for auto-build binaries is already there?

> Binary targets are automatically built if there is an integration test or benchmark. This allows an integration test to execute the binary to exercise and test its behavior.

https://github.com/rust-lang/cargo/blob/7b7d80e84ae74dd620c0f294d6f12ada16cdb94e/src/doc/man/cargo-test.md#target-selection

**Comment by weihanglo** [comment]
#10726 improves the doc a little. I'll close this issue as resolved. If you feel we need a fix other than a doc update, please file a new issue. Thank you!

**Comment by rambip** [comment]
> There is not currently a way to skip building the binaries.

Oh, that was exactly the feature I was looking for 😕
I have a Yew project (so it compiles to webassembly, and then generates some javascript glue)
I wanted to write unit tests for this project, but I was not able to make it work:
- if I run `cargo test`, cargo will say it cannot run a wasm file
- if I try to change the target, it will fail to compile parts of the code
- if I decide to give up the unit tests and write integration tests instead, cargo will still complain it cannot run (if I chose the wasm target) or compile (if I chose the linux target) the tests ...
