### ISSUE TITLE
Enforcing a specific version of Rust

### ISSUE THREAD

**Issue by jordiae** [rust-lang/cargo#7967]
Hi, I'm not familiar with Rust, but I'm using a Python module that has Rust dependencies (Huggingface's tokenizers). I'm trying to compile the code in a PowerPC cluster without access to the Internet and without admin permissions, but with a built-in Rust install, which doesn't work in my case since PyO3 requires Rust Nightly.

So, I have transferred to the cluster the right Rust version (nightly, PowerPC), but when I execute the corresponding Cargo, I still get the same error:

`error: failed to run custom build command for "pyo3 v0.8.4"`

`Error: pyo3 requires a nightly or dev version of Rust.`

My best guess is that since I haven't installed this new version of Rust (because I do not have permissions to do so, so I'm just calling the corresponding binaries), at some moment Cargo just calls "rustc", which in this case is the built-in Rust compiler that doesn't work in my case.

Is there any way to enforce a specific rustc path (instead of calling rustc, call /path/to/my/rustc)? So far, I haven't found any workaround.

For reference, this was the original issue in the tokenizers repository: https://github.com/huggingface/tokenizers/issues/176#issuecomment-594091846

Many thanks in advance.

**Comment by ehuss** [comment]
The typical way of managing toolchain versions is with [rustup](https://github.com/rust-lang/rustup).  This allows you to set overrides (globally, per-directory, etc.).  In this case I would run `rustup override set nightly` in the directory where you want to use nightly.

If you don't have rustup or can't use it, setting the `RUSTC` environment variable is the typical way to specify which compiler to use.

In the future, questions like these are better asked on one of the user forums.

**Comment by jordiae** [comment]
@ehuss Many thanks for your answer and please excuse any inconvenience.
