### ISSUE TITLE
proc-macro lib causes change in behaviour when using cargo as a library

### ISSUE THREAD

**Issue by xd009642** [rust-lang/cargo#7968]
So I make cargo-tarpaulin a code coverage crate which uses cargo as a library to build tests and over artefacts a user wants to get coverage from. But with edition 2018 crates there's an issue with proc-macro crates with:

```
[lib]
proc-macro = true
```

If we look at rocket's codegen subcrate as an example, when run via tarpaulin cargo outputs:

```
   Compiling tokio-util v0.2.0
   Compiling rustfix v0.4.6
   Compiling rocket_contrib_codegen v0.5.0-dev (/home/xd009642/code/rust/metatarp/Rocket/contrib/codegen)
   Compiling futures v0.3.4
error[E0432]: unresolved import `proc_macro`
  --> contrib/codegen/src/lib.rs:39:5
   |
39 | use proc_macro::TokenStream;
   |     ^^^^^^^^^^ help: a similar path exists: `quote::proc_macro`
  |
error[E0432]: unresolved import `proc_macro`
 --> contrib/codegen/src/database.rs:1:5
  |
1 | use proc_macro::TokenStream;
  |     ^^^^^^^^^^ help: a similar path exists: `quote::proc_macro`
For more information about this error, try `rustc --explain E0432`.
error: aborting due to 2 previous errors
```

Below is a minimal recreation of the cargo using code that fails to compile:

```Rust
cargo::core::enable_nightly_features();
// cwd is the current working directory supplied by the user
// and home is gotten via homedir function in cargo
let mut cargo_config = CargoConfig::new(Shell::new(), cwd, home);
let flag_quiet = Some(true);

// This shouldn't fail so no checking the error.
let _ = cargo_config.configure(
    0u32,
    flag_quiet,
    &None,
    config.frozen,
    config.locked,
    config.offline,
    &config.target_dir,
    &config.unstable_features,
);

let workspace = Workspace::new(config.manifest.as_path(), &cargo_config)
    .map_err(|e| RunError::Manifest(e.to_string()))?;

let compile_options = get_compile_options(&config, &cargo_config)?;

for copt in &compile_options {
    let compilation = compile(&workspace, &compile_options);
    // Compilation is now an err type!
}
```

**Comment by xd009642** [comment]
So I've moved my cargo dependency to latest master and it seems to sort the issue as well as another issue raised in my repo! Just wondering when the next release can be released?

**Comment by ehuss** [comment]
Calling `enable_nightly_features` can cause breakage because it is only compatible with the version of nightly that happened to exist at one moment in time (roughly 6 weeks before the stable release).  I took a quick look, and I don't really see why tarpaulin is using the cargo library (instead of just calling the `cargo` binary).  Generally that will make life easier if you can approach it that way.

Releases are done every 6 weeks. The upcoming calendar is at https://forge.rust-lang.org/.

**Comment by xd009642** [comment]
`enable_nightly_features` was on so it wouldn't fail to compile if users are using nightly features. And I don't know about now but when I started the project you couldn't get the path to the generated test binaries for compiled tests or compile doc-tests from running cargo in the command line but if there's a way to get that then I'm more than happy to move things over

**Comment by ehuss** [comment]
`cargo build --message-format=json` will emit JSON messages with the paths to the artifacts.  More information is at https://doc.rust-lang.org/cargo/reference/external-tools.html#artifact-messages.  The [`cargo_metadata`](https://docs.rs/cargo_metadata/0.9.1/cargo_metadata/struct.Artifact.html) crate contains serde definitions if you wan to reuse those.

**Comment by ehuss** [comment]
I'm going to close, as it seems like this is mostly resolved. Enabling nightly features in cargo makes if fundamentally coupled with the nightly release of rustc that existed at the time the beta is branched.
