### ISSUE TITLE
error: linking with `link.exe` failed: exit code: 1

### ISSUE THREAD

**Issue by francis-du** [rust-lang/cargo#7975]
**Problem**

When i run `cargo run`, The error is as follows:

![image](https://user-images.githubusercontent.com/25944814/76167457-c1f66200-61a1-11ea-9ddc-dcf005f0c497.png)

**Steps**

1. `cargo new hello_cargo`
2.  `cargo run`

**Possible Solution(s)**

**Notes**

Output of `cargo version`: cargo 1.41.0 (626f0f40e 2019-12-03)

OS version is Windows 10 Home

**Comment by ehuss** [comment]
It looks like your environment is misconfigured.  If `VCINSTALLDIR` is set, then rust will search your `PATH` for `link.exe`.  In this case, the MSVC `link.exe` needs to be first in the path.  It looks like you have a cygwin/msys/mingw `link` executable somewhere earlier in your PATH.

I recommend to avoid setting the vcvars, as rustc will then use various windows APIs to find `link.exe`, and won't get confused by the GNU programs.  

This isn't an issue for Cargo, as cargo doesn't manage linking.  If you need more assistance, I recommend one of the user forums.
