### ISSUE TITLE
Typos in badge names aren't caught by cargo publish --dry-run

### ISSUE THREAD

**Issue by daboross** [rust-lang/cargo#7979]
**Problem**

If I make a typo in the badges portion of my cargo library, there's no warning on compile nor on a dry-run publish, and I only get to see that something's wrong _after the publish succeeds_.

**Steps**

1. Create a new cargo library.
2. Add to `Cargo.toml`:

  ```toml
  [badges]
  is-it-mantained-issue-resolution = { repository = "daboross/fern" }
  ```
3. Try to catch publish errors using `cargo publish --dry-run` (no errors are displayed)
4. Publish the crate on crates.io using `cargo publish` (this displays a warning about `is-it-mantained-issue-resolution` being ignored as a badge)

**Possible Solution(s)**

I'd expect this should be possible by pinging the crates.io servers on a dry-run upload to check whether there are any invalid attributes. I expect `cargo publish --dry-run` to do everything that `cargo publish` does short of actually publishing it, so if there's a step separate from uploading that `cargo publish` does to display errors about ignored badges, maybe it could do that?

**Notes**

Output of `cargo version`: `cargo 1.43.0-nightly (e57bd0299 2020-02-21)`

**Comment by ehuss** [comment]
Eventually we would like to have a new publish API that supports this.  Since this is already reported in #3576, closing as a duplicate.
