### ISSUE TITLE
Cargo failed to install the mdbook.

### ISSUE THREAD

**Issue by emilianonatella** [rust-lang/cargo#7980]
**Install mdbook**
I would like to use mdbook and I am trying to understand how to use and configure it. 
The guide says that you need to install rust first.

**Steps**

1. I installed RUST from the command line: `curl --proto '= https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
Cargo is installed with version "1.41.0"
RUST is installed with version "1.41.1"
2. Install mdbook with the command: `cargo install mdbook`
But it gives me an error. 

**Error**
`Updating crates.io index`
`Installing mdbook v0.3.5`
`Compiling libc v0.2.67`
`Compiling cfg-if v0.1.10`   
`Compiling proc-macro2 v1.0.9`
`Compiling unicode-xid v0.2.0`
...
...
...
`Running rustc --crate-name build_script_build /Users/...`
`error: linking with cc failed: exit code: 1`
...
`error: aborting due to previous error`
`error: could not compile log.`
...
`warning: build failed, waiting for other jobs to finish...`
`error: linking with cc failed: exit code: 1`
...
`error: aborting due to previous error`
`error: could not compile libc.`
...
`error: aborting due to previous error`
`error: could not compile syn.`
...
`error: linking with cc failed: exit code: 1`
...
`error: aborting due to previous error`
`error: failed to compile mdbook v0.3.5, intermediate artifacts can be found at /var/folders/sh/.../T/cargo-installQcUbqz`

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like most of the error logs was snipped out though, can you provide a more complete error log?

**Comment by emilianonatella** [comment]
Hi alexcrichton,
thank you.
I hadn't reported the whole log file because I'm not sure if there was some private data.
Can I proceed safely?

However, maybe it could depend on something wrong, some missing steps

After installing rust all I have to do is install mdbook with command ?
Or I should have add Cargo's bin directory to my PATH before? How?

After installing rust he tells me:
> Rust is installed now. Great!
> 
> To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
> environment variable. Next time you log in this will be done
> automatically.

Also if I use `cargo check` command it returns the following error:
```markdown
error: could not find Cargo.toml in /Users/emiliano/Applications or any parent directory
```

**Comment by alexcrichton** [comment]
Ah well it's up to you how much data you'd like to upload. Given what we can see of the log this doesn't look like a Cargo issue, but rather it's most likely a system configuration issue or something like that.

**Comment by emilianonatella** [comment]
>doesn't look like a Cargo issue, but rather it's most likely a system configuration issue or something like that.

I'm sure too

But i'm not sure about insert all the whole log file. What do you suggest?

Based on what I wrote I did all the steps correctly then?
Do I have to set any cargo's bin directory in my path? How?

I tried to reinstall rust and now after redoing the steps described above it gives me this error:
```markdown
...
...
error: could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `syn`.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
  |
= note: "cc" "-m64" "-L" "/Users/emiliano/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib"...
...
...
= note: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
          

error: aborting due to previous error

error: failed to compile `mdbook v0.3.5`, intermediate artifacts can be found at `/var/folders/sh/cbbm5nwx55qdss9hzv03536m0000gn/T/cargo-installJLJD6U`

Caused by:
  could not compile `proc-macro2`.
```

**Comment by alexcrichton** [comment]
There could be a massive number of things that are possibly going wrong here, there's really no great way to help narrow it down without more information. I'd recomend probably trying to compile simple C programs and see if that works out. If that doesn't work then it's likely an issue independent of rustc/cargo.

**Comment by emilianonatella** [comment]
Now it works!!!
After upgrading to MacOS X 10.15 Catalina I had to reinstall the command line tools:
`$ xcode-select --install`

**Comment by hashbangash** [comment]
Thanks for posting the solution! Worked for me as well :)

**Comment by chijiokeNwafor** [comment]
yeah it worked for me too. Thanks
