### ISSUE TITLE
doesn't say which Cargo.toml has a reference to path that doesn't exist

### ISSUE THREAD

**Issue by nlewycky** [rust-lang/cargo#7981]
**Problem**
I have a project with many Cargo.toml's in it. One of them refers to a path outside the project (absolute path to another project that we depend on and are making changes to). The error message did not tell me which Cargo.toml file had the path.

1. I'm in /home/nicholas/wasmer and run `cargo build`.
2. I get this error:
```
$ cargo test
error: failed to read `/home/nick/wasmerio-cranelift/cranelift-wasm/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```
3. The bad path is in `/home/nicholas/wasmer/lib/clif-backend/Cargo.toml`. This filename was not included anywhere in the error message.

**Steps**
I'm not exactly sure. I've tried reproducing this by creating a fake tree `fnf` which depends on one subdirs `left` which depends the other subdir `right`, then cargo build, then remove `right`, but in this case it does emit a "Caused by: Unable to update" that includes where the bad path came from.

For the original issue, I moved a 'git diff' from one machine to another where the absolute path was no longer correct, this patch included the Cargo.lock.

**Notes**

Output of `cargo version`:
cargo 1.43.0-nightly (bda50510d 2020-03-02)

**Comment by ehuss** [comment]
Are you using `[patch]` or anything like that?

Would it be possible to maybe post your patch to cranelift somewhere that reproduces this?  (Maybe on a branch in your repo, or as a gist.)

**Comment by weihanglo** [comment]
I am going to close due to lack of a minimal set of steps to reproduce, and it has been inactive for a while. Feel free to comment below or open a new issue if there is any update.
