### ISSUE TITLE
nightly doesn't include zsh completion

### ISSUE THREAD

**Issue by doronbehar** [rust-lang/cargo#7991]
**Problem**

When trying to tab complete a `cargo` command withing a project using nighty, I got the following error:

```
_cargo:source:2: no such file or directory: /home/doron/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/zsh/site-functions/_cargo
```

**Steps**

Try to tab complete a `cargo` command withing a project using nighty,

**Possible Solution(s)**

Don't use rust nightly

**Notes**

Output of `rustup --version`:

```
rustup 1.21.1 (1970-01-01)
```

Output of `rustup show`:

```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/doron/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-2019-05-22-x86_64-unknown-linux-gnu
nightly-2019-08-21-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.41.0-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.43.0-nightly (158127853 2020-03-10)
```

**Further info**

I'm using NixOS.

All other toolchains in `~/.rustup/toolchains/` have a `share/zsh/site-functions/_cargo` file. I'm not sure this is the right place to report this.

**Comment by pietroalbini** [comment]
Moved this isssue to the Cargo repo from the rustup repo.

**Comment by ehuss** [comment]
Hm, that's really strange.  My copy of `rustc 1.43.0-nightly (158127853 2020-03-10)` contains the file.  Is it possible that maybe the `cargo` component has been uninstalled from the toolchain?  Is `cargo` listed in `nightly-x86_64-unknown-linux-gnu//bin`?  If you run `rustup component add --toolchain nightly cargo` does it help?

**Comment by doronbehar** [comment]
Here are the directories I have in `~/.rustup/toolchains`:

```
1.41.0-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-2019-05-22-x86_64-unknown-linux-gnu
nightly-2019-08-21-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
stable-x86_64-unknown-linux-gnu
```

Every such directory has the following files in it's `bin/`:

```
1.41.0-x86_64-unknown-linux-gnu/bin/:
cargo  cargo-clippy  cargo-fmt  clippy-driver  rls  rustc  rustdoc  rustfmt  rust-gdb  rust-gdbgui  rust-lldb

beta-x86_64-unknown-linux-gnu/bin/:
cargo  cargo-clippy  clippy-driver

nightly-2019-05-22-x86_64-unknown-linux-gnu/bin/:
cargo  rls  rustc  rustdoc  rust-gdb  rust-gdbgui  rust-lldb

nightly-2019-08-21-x86_64-unknown-linux-gnu/bin/:
cargo  rls  rustc  rustdoc  rust-gdb  rust-gdbgui  rust-lldb

nightly-x86_64-unknown-linux-gnu/bin/:
cargo-clippy  cargo-fmt  clippy-driver  rustc  rustdoc  rustfmt  rust-gdb  rust-gdbgui  rust-lldb

stable-x86_64-unknown-linux-gnu/bin/:
cargo  rls  rustc  rustdoc  rust-gdb  rust-gdbgui  rust-lldb
```

You were right to guess that cargo itself is not found in `nightly-x86_64-unknown-linux-gnu/bin/`. Running `rustup component add --toolchain nightly cargo` didn't help. I did ran however the following commands:

```
rustup toolchain remove nightly
rustup toolchain add nightly
rustup default nightly
```

And now the issue is fixed and I can't reproduce it anymore. Feel free to close this.

**Comment by ehuss** [comment]
Strange!  Glad it got fixed!

**Comment by thiagodebastos** [comment]
I started having this issue today, for both `stable` and `nightly`, the suggestions didn't help. I'll keep fiddling around before raising an issue.
