### ISSUE TITLE
0.43.0 published with wrong version

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#7994]
**Problem**
It looks like 0.43.0 was published with the wrong version.  rust 1.42.0 was published with 86334295e82ef241fe5ec618d9fb612585bd7c1f (seen at https://github.com/rust-lang/rust/tree/1.42.0/src/tools or running `cargo -V`).  However, it looks like 0.43.0 was tagged with 9d32b7b01409024b165545c568b1525d86e2b7cb ([0.43.0](https://github.com/rust-lang/cargo/releases/tag/0.43.0)), missing #7848, and the version on crates.io is also the older commit.

I'm not sure what the best solution is.  Maybe publish 0.43.1 with the fix?  

**Notes**
@pietroalbini is there something we can do to improve the release process to avoid problems like these?  This happened recently (#7503), and I'd like to try to avoid it happening again.  I'm not familiar with your process, but if it is automated perhaps there's something that needs to be fixed?

**Comment by pietroalbini** [comment]
> I'm not sure what the best solution is. Maybe publish 0.43.1 with the fix?

@Mark-Simulacrum what do we want to do?

>  I'm not familiar with your process, but if it is automated perhaps there's something that needs to be fixed?

I'm mostly doing stuff manually, which is probably the cause of my occasional errors :(

**Comment by Mark-Simulacrum** [comment]
I think we should yank what we've published and publish 0.43.1 (with the correct version).

I think we should also work on automating the release process in general; this step at least seems like it could plausibly happen entirely automatically. Testing that automation may be a bit painful, but maybe we can publish to a staging version of crates.io?

I should be able to find the time to work on such automation in the next 6 weeks. In theory it should just be built-in to our normal release process I think.

**Comment by ehuss** [comment]
I have bumped the version to 0.43.1 on the rust-1.42.0 branch.  If someone with permission could re-publish cargo, this can be closed (make sure it is revision 5b129c4fed8a5cf1e8834c49add647740f536259).

**Comment by pietroalbini** [comment]
Published!

**Comment by ehuss** [comment]
Thanks!
