### ISSUE TITLE
Ergonomics: errors could be better

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/cargo#80]
Right now, if you make a `Cargo.toml`, and you `mkdir src`, and then you `cargo build`:

```
$ cargo build
  Compiling guessing_game v0.1.0 (file:/home/steve/tmp/guessing_game)
error: couldn't read src/guessing_game.rs: couldn't open file (no such file or directory (No such file or directory); path=src/guessing_game.rs; mode=open; access=read)
```

@wycats would like this to improve. :smile:

**Comment by alexcrichton** [comment]
This is a pretty generic issue that isn't necessarily actionable any more. I think that we can definitely improve on particular errors here and there, but it would be good to open up sub-issues about these errors at this point I think.
