### ISSUE TITLE
Add clippy step to CI 

### ISSUE THREAD

**Issue by aleksator** [rust-lang/cargo#8000]
**Describe the problem you are trying to solve**
When working on cargo's codebase, I try to check my work with clippy to see if everything I've done is idiomatic. However, the output usually contains some warnings from unrelated parts of the codebase.

**Describe the solution you'd like**
Add a clippy check to CI builds so that all PRs follow the suggestions.

**Notes**
The existing warnings would needed to be fixed before enabling the checks in CI.

**Comment by ehuss** [comment]
We have discussed this in the past, and in general we don't want to gate CI on clippy.  We don't want to have yet another hurdle for contributors to get through.  Clippy can also be somewhat opinionated, that not every agrees with.

We're happy to review occasional PRs that clean up the code base, though!
