### ISSUE TITLE
Command-line-friendly version of locate-project

### ISSUE THREAD

**Issue by sollyucko** [rust-lang/cargo#8009]
**Describe the problem you are trying to solve**
`cargo locate-project` and `cargo metadata` both return JSON output, which may be easiest when writing programs to parse it, but it is much more difficult to use in simple shell scripts.

**Describe the solution you'd like**
A `--output-format` flag or similar might be the neatest way to solve this. For example, `cargo locate-project --output-format minimal` (or something similar) would return **just** the path to `Cargo.toml`. It could also be formatted as <code>root *path*</code> or something similar, allowing the use of `grep` + `cut` for parsing, and would be more generalizable and allow for future extension `locate-project`.

Additionally, this sort of flag could also be extended to other commands and formats, as needed.

**Comment by sollyucko** [comment]
As a workaround, for now I'm using [`jq`](https://stedolan.github.io/jq/), as `cargo locate-project | jq -r '.root'`.

**Comment by dtolnay** [comment]
Submitted a PR for this. #8683
