### ISSUE TITLE
Is flate2's rust_backend feature really used?

### ISSUE THREAD

**Issue by est31** [rust-lang/cargo#8019]
The flate2 dependency is included by cargo in the following way:

https://github.com/rust-lang/cargo/blob/03d7154e77431f2e8b9c1ea588313ac0c4d52808/Cargo.toml#L34

This includes the [on-by-default](https://github.com/alexcrichton/flate2-rs/blob/962930cb3a1b1c50b710c9f4749f1686365eb70a/Cargo.toml#L46) `rust_backend` feature, which adds the `miniz_oxide` dependency to flate2 and the `adler32` transitive dependency. In the rustc repo you can find the following note though, saying that adler32 is not used:

https://github.com/rust-lang/rust/commit/61fe2e4036cb8917372e42df66c54596a05d69b7#diff-3ac60df36be32d72842bf5351fc2bb1dR43

It might be better to turn off the default features of flate2 so that the unused crate doesn't have to be compiled by people.

**Comment by ehuss** [comment]
I believe the answer is "no".  Removing it saves about 0.1 seconds on my system, so I'm not sure it really matters, but if you want to send a PR to disable default features, it should probably be OK.

**Comment by est31** [comment]
Can you label it easy and help wanted? Thanks!

**Comment by aleksator** [comment]
Done. I'll create a PR to rust repository to remove these 2 dependencies from their whitelist once 8023 is merged.

**Comment by est31** [comment]
@aleksator thanks! Don't forget to also update the cargo submodule

**Comment by ehuss** [comment]
> Done. I'll create a PR to rust repository to remove these 2 dependencies from their whitelist once 8023 is merged.

That won't be necessary. `flate2` is used in a number of other projects in the rust repository, which use the default features.

**Comment by est31** [comment]
Good point. The comment still needs updating because it's not just an unused dep of cargo but used inside the compiler, too.

**Comment by aleksator** [comment]
@ehuss 
> That won't be necessary. flate2 is used in a number of other projects in the rust repository, which use the default features.

Certainly true in regards to this constant in deps.rs then:
```
/// These are exceptions to Rust's permissive licensing policy, and
/// should be considered bugs. Exceptions are only allowed in Rust
/// tooling. It is _crucial_ that no exception crates be dependencies
/// of the Rust runtime (std/test).
const EXCEPTIONS: &[(&str, &str)]
```
But what about 
```
/// Whitelist of crates rustc is allowed to depend on. Avoid adding to the list if possible.
///
/// This list is here to provide a speed-bump to adding a new dependency to
/// rustc. Please check with the compiler team before adding an entry.
const WHITELIST: &[&str]
```
? This one is internal for rustc if I understand it correctly, so probably should be changed. Is it?

@est31 
>Good point. The comment still needs updating because it's not just an unused dep of cargo but used inside the compiler, too.

What would it change it to?
