### ISSUE TITLE
`cargo metadata` should return default workspace members

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/cargo#8033]
**Describe the problem you are trying to solve**

For a workspace, it is possible to [specify default members](https://doc.rust-lang.org/cargo/reference/workspaces.html#package-selection) through the `workspace.default-members` key. It would be great to expose this information through `cargo metadata`.

**Describe the solution you'd like**
The same format as `workspace_members` in `cargo metadata` -- a list of package IDs.

**Comment by sunshowers** [comment]
cc @metajack

**Comment by charles-r-earp** [comment]
I implemented this here https://github.com/charles-r-earp/cargo. I fixed one test "cargo_metadata_simple".

**Comment by sunshowers** [comment]
@charles-r-earp that looks great! you can probably submit that as a PR to this repo.

**Comment by weihanglo** [comment]
Hello all. Thanks for the proposal and the pull request. I'd like to know more about why default members in `cargo metadata` output is useful. Could you share some details? 

Will do a simple FCP collecting options from the team then if it is reasonable.

(And sorry for the way too late reply 😅)

**Comment by sunshowers** [comment]
A simple use case is writing a linter that triggers only on default workspace members. Without support for this, one has to manually scrape the root Cargo.toml.

**Comment by charles-r-earp** [comment]
Cargo extensions and dev tools will want to emulate cargo, like having options like --manifest-path, --workspace, --package, etc. There are tools to do this like clap_cargo + cargo_metadata which makes use of cargo metadata. This allows cargo-foo bar to operate on all workspace default members just like cargo check / build / test / etc.

**Comment by weihanglo** [comment]
Thank you all for sharing!

I propose adding workspace default member information to the output of `cargo metadata`, to make external plugins easier to align to Cargo's behavior.

One concern is that the size of the output grows overtime.

@rfcbot fcp merge

We don't need to wait for 10 days after the poll btw.
