### ISSUE TITLE
Cargo cannot read index with namespaced features.

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#8044]
**Problem**
An index that contains namespaced features (those with `crate:`) cannot be used by nightly cargo.  The versions published with those features cannot be selected by the resolver.

**Steps**
1.  Create an index containing crates with namespaced features.
2. Attempt to use those crates from the index.
3. Notice that you cannot select versions with those features.

From the log output:

[2020-03-27T16:15:07Z INFO  cargo::sources::registry::index] failed to parse "my/th/mything" registry package: Features and dependencies cannot have the same name: `common`

**Possible Solution(s)**
It looks like the crux of the issue is [this line](https://github.com/rust-lang/cargo/blob/334279295891f50726669282f806cdf2bfa4ed8f/src/cargo/sources/registry/index.rs#L725) where the index cache will not parse summaries with namespaced features.

cc @djc

**Comment by djc** [comment]
So I guess `RegistryPackage` will need to gain a `namespaced_features: Option<bool>` field, which should be uploaded to the index as well as read from it, right?

**Comment by ehuss** [comment]
Hm, that would be quite a disappointment if namespaced-features has to be marked in the index. Adding new fields should be done very carefully.
