### ISSUE TITLE
Question: How can I list the installed files for a rust crate?

### ISSUE THREAD

**Issue by dbarnett** [rust-lang/cargo#8050]
Is there a way to list the files cargo has installed for a crate (all files created by a given `cargo install CRATE` command)?

For comparison, it would be equivalent to the `dpkg --listfiles PKG` command for installed deb packages on Debian/Ubuntu.

**Comment by alexcrichton** [comment]
The `cargo install --list` command will list everything, but currently at this time there's no flag to list only the files for a specific crate.

**Comment by dbarnett** [comment]
Thanks for the reply, Alex!

Specifically I wanted to check after `cargo install skim` if any of the files from https://github.com/lotabout/skim/tree/master/shell ended up anywhere on my system (re lotabout/skim#292). `cargo install --list` shows me this excerpt for the `skim` crate:
```
skim v0.8.0:
    sk
```
but does that mean there are no other files besides the one executable file, or what?

**Comment by alexcrichton** [comment]
Indeed, yeah, `cargo install` only installs binaries right now.

**Comment by dbarnett** [comment]
K, then you can close out this issue provided that any plans to install non-binary files would also include hooking them up to be shown under `--list`.
