### ISSUE TITLE
Cargo should check for windows-reserved filenames when extracting a package.

### ISSUE THREAD

**Issue by Skgland** [rust-lang/cargo#8055]
EDIT (ehuss): The issue is that `navi` includes a file named `aux.rs` which is not a valid filename on windows. Cargo should check for these reserved filenames while extracting and provide a better error message.

**Problem**

On Windows Cargo failes to install a package because it fails to set mtime fo a file.
The package where the error occourse is  navi version 2.2.0

[Console Log](https://gist.github.com/Skgland/d022afd94aa78afa34b0c49a88215439)

**Steps**

1. On windows run `cargo install navi` 

**Possible Solution(s)**

**Notes**

Output of `cargo version`: 
`cargo 1.44.0-nightly (7019b3ed3 2020-03-17)`

`cargo 1.42.0 (86334295e 2020-01-31)` has the same problem under Windows but gives shorter error trace.

Same package and cargo versions work under Linux Mint.
Also I currently cannot reproduce this with other packages.

**Comment by alexcrichton** [comment]
This is likely cropping up due to https://github.com/rust-lang/cargo/pull/7935 (cc @cwndrws)

I'm unfortunately not really sure what this error message means, it seems highly likely to be related to something Windows-specific, though.

**Comment by ehuss** [comment]
`aux.rs` is not a valid filename on windows. As of #7959 Cargo will now display a warning when *publishing* a package with names like these. But it should probably check for these explicitly when extracting, too, so it is not so confusing.

**Comment by hbina** [comment]
Since this is marked Easy, I assume an explicit warning of this behavior by Windows is sufficient? Or is there a way to work around this

**Comment by ehuss** [comment]
@hbina Sorry, I'm not sure I understand your question.

I think the best thing to do is to just elaborate the error message when extracting a reserved file.

Extracting happens around [here](https://github.com/rust-lang/cargo/blob/f044cf9fb0fc1f24df905f636c4cd9198e1b8b6d/src/cargo/sources/registry/mod.rs#L499-L503).  When an error happens, Cargo should check (only on Windows) if the file name (minus any extension), or any of the directory components is reserved (using [`is_windows_reserved`](https://github.com/rust-lang/cargo/blob/f044cf9fb0fc1f24df905f636c4cd9198e1b8b6d/src/cargo/util/restricted_names.rs#L25-L31)).  If so, add a hint to the error message explaining that the package contains a reserved filename on Windows, and cannot be used.

**Comment by hbina** [comment]
that answered my question. Thanks!

**Comment by CPerezz** [comment]
Hey, if @hbina agrees, I would like to take that issue! :)

**Comment by ehuss** [comment]
Fixed by #8136.
