### ISSUE TITLE
Running cargo commands do nothing

### ISSUE THREAD

**Issue by Eros** [rust-lang/cargo#8056]
**Problem**
Whenever I run any of the cargo commands they just sit there and do nothing, just like a blank screen really. Running `cargo build` or `cargo run`, just act like this: https://i.imgur.com/xY4iHx2.png
I've attempted the commands on multiple projects and to be sure it's not my code I've tried it on the rustlings project (install followed exactly btw). Also tried different terminals just to be sure it's not the one I'm using same problem (main one is cmder, also tried basic powershell/windows cmd)

I've had this running for about 30 minutes before just to make sure that my computer wasn't having issues still did nothing, no files/executables are outputted have to kill the program with CTRL+C.

**Steps**

1. run `cargo build` or `cargo run`
2. let it do nothing

**Notes**

Output of `cargo version`: cargo 1.42.0 (86334295e 2020-01-31)
Other commands like `cargo --help` and `cargo --version` work perfectly fine
Also tried to forcefully generate an error by going into the cargo.toml file and changing `edition` from 2018 to 2020 (as it's not valid) and it did provide an invalid error https://i.imgur.com/8IF5p4u.png

**Comment by alexcrichton** [comment]
Can you try setting `RUST_LOG=trace` and `CARGO_LOG=trace` to see if something is happening in the background?

**Comment by Eros** [comment]
Still the same, nothing has changed.

**Comment by alexcrichton** [comment]
How odd! Is it possible to attach a debugger to figure out what's going on? Do you have some sort of system protection settings or something like that which may prevent it from being run? (anti-virus stuff has caused issues in the past)

**Comment by Eros** [comment]
Attached a debugger to it and after about 2 hours it turned out my firewall (comodo) was preventing it from running without warning. Not sure why this had only started happening now after updating.

**Comment by k0pernicus** [comment]
Is it possible that, when building the project, `cargo` is trying to update the dependencies before, and just hang due to your firewall settings?

**Comment by Eros** [comment]
@k0pernicus from what i can see with the firewall it is in fact trying to block out dependencies updating, after tinkering with it mine specifically allows it to be ignored in future cases which has now fixed it but still not sure as to why it has only started blocking once updating Rust itself.

**Comment by ehuss** [comment]
I'm going to close this as it seems like it is an issue with Comodo.  If a tool is blocking Cargo from proceeding, there's not a lot it can do.
