### ISSUE TITLE
build-dependencies should not share the same feature space with target dependencies

### ISSUE THREAD

**Issue by kvinwang** [rust-lang/cargo#8064]
**Problem**
The `bindgen` crate turns on the feature `log/std`. When I use bindgen as a build-dependency in a no_std crate which using the `log` crate, the `log/std` is turned on unexpectly.

**Steps**

```shell
cargo new --lib foo
cd foo
cat >> Cargo.toml <<EOF
[dependencies.log]
default-features = false
version = "0.4"

[build-dependencies]
bindgen = "0.49"
EOF
cargo +nightly check -Z build-std=core,alloc --target=x86_64-linux-kernel
```

output:

```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-linux-kernel` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `log`.
```

Changing then version of log to `= 0.3.8` makes the `cargo check` happy.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo 1.44.0-nightly (7019b3ed3 2020-03-17)

**Comment by Eh2406** [comment]
This is a well known issue, these days there is an experimental fix at https://github.com/rust-lang/cargo/issues/7916. Please leave the report there or on one of the other open issues.
