### ISSUE TITLE
Check for missing features in Cargo.toml

### ISSUE THREAD

**Issue by elichai** [rust-lang/cargo#8070]
Hi,
Right not as I understand it there's no real communication between rustc to cargo about what cfg features exist in the code, only the opposite(cargo passes `--cfg` flags to rustc).

But it would be a great feature IMHO to check somehow if there are any cfg features in the code that don't exist in the toml and produce a warning.

Example:
toml:
```
[package]
name = "Example"
version = "0.1.0"
authors = ["Elichai Turkel <elichai.turkel@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
```
main.rs:
```
#[cfg(feature = "binary")]
fn main() {
    println!("Hello, world!");
}
```

Real world example: https://github.com/rust-bitcoin/rust-secp256k1/pull/199 A typo in a feature name, in cargo toml it was defined as `external-symbols` but in rust it was `external_symbols`

**Comment by QiangHeisenberg** [comment]
I'm sorry, I don't understand this very well. This is also checked for syntax or ```cfg``` in cargo? But as far as I know, the rust compiler does a check at compile time. What is the point of doing this?

**Comment by ehuss** [comment]
I think the point is to check for typos and other mistakes, where the author writes the wrong `cfg` expressions.

I'm going to close this, as there is an accepted RFC to implemented this, see tracking issue https://github.com/rust-lang/rust/issues/82450.
