### ISSUE TITLE
Tracking issue for minimum supported Rust version (RFC 2495)

### ISSUE THREAD

**Issue by djc** [rust-lang/cargo#8072]
RFC: https://github.com/rust-lang/rfcs/blob/master/text/2495-min-rust-version.md
Rust tracking issue: https://github.com/rust-lang/rust/issues/65262
Initial implementation: #8037

Concise description of the implementation:

* An optional `rust-version` field in the `Cargo.toml` `package` section, which can contain a version number like `"1.43.1"` or `"1.56"`. It must be a single version number, with no semver operator(s) or pre-release identifier. The version must be equal to or newer than the version that first introduces support for the configured edition.
* If specified, Cargo versions newer than the one stabilizing this feature will start to fail any compile-like commands with an error referring to the specified `rust-version` if the crate is compiled with an older version of the compiler. Pre-release identifiers for the active compilers are ignored for purposed of comparison.
* The `rust-version` field may be ignored using the `--ignore-rust-version` option.

**Comment by djc** [comment]
My call for testing in https://users.rust-lang.org/t/call-for-testing-unstable-cargo-support-for-rust-version/59386/4 has not yielded any explicit feedback (other than likes on the post). What should we do next? Would be nice to have this finished (the edition coming up is also one reason why this might start being more useful).

**Comment by ehuss** [comment]
I think stabilizing would be fine.  Just need to submit a PR, updating the documentation, and write a clear description of what is being stabilized.

**Comment by djc** [comment]
What is being stabilized:

* An optional `rust-version` field in the `Cargo.toml` `package` section, which can contain a version number like `"1.43.1"` or `"1.56"`. It must be a single version number, with no semver operator(s) or pre-release identifier. The version must be equal to or newer than the version that first introduces support for the configured edition.
* If specified, Cargo versions newer than the one stabilizing this feature will start to fail any compile-like commands with an error referring to the specified `rust-version` if the crate is compiled with an older version of the compiler. Pre-release identifiers for the active compilers are ignored for purposed of comparison.
* The `rust-version` field may be ignored using the `--ignore-rust-version` option.

**Comment by ehuss** [comment]
Closing as this has been stabilized in #9732.

**Comment by djc** [comment]
Shouldn't cargo tracking issue FCPs get tracked in This Week in Rust?

**Comment by est31** [comment]
List of issues in rust related tooling to provide support for the new feature:

* https://github.com/actions-rs/toolchain/issues/206
* https://github.com/rust-lang/rust-clippy/issues/7765
* https://github.com/rust-lang/rustup/issues/2925
