### ISSUE TITLE
Allow GitHub Actions badges in the badges section

### ISSUE THREAD

**Issue by m-lima** [rust-lang/cargo#8076]
Allow [github action](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions) badges to be included in the `[badges]` section of **Cargo.toml**

Currently, the [badges section](https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section) of **Cargo.toml** supports Appveyor, CircleCI, Cirrus CI, GitLab, Azure DevOps, Travis CI, and Bitbucket Pipelines.
Gihub has made their Actions available for all public github repositories. And, with [actions-rs](https://github.com/actions-rs), it is very easy to add tests and builds to the github workflow. They generate badges that could be accepted by **Cargo.toml** and [crates.io](https://crates.io/)

**Comment by ehuss** [comment]
GitHub Actions badge support is pending in the PR at https://github.com/rust-lang/crates.io/pull/1838.
