### ISSUE TITLE
Make cargo repo compatible with homebrew formulae

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/cargo#808]
A colleague is interested in trying to help write a homebrew formula for installing cargo, so that `brew install cargo` will work.

 * [Opening Homebrew PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md#how-to-open-a-homebrew-pull-request-and-get-it-merged)
 * [Homebrew Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md)

One hurdle that my colleague pointed out is that the homebrew policies for acceptable formulae requires that stable versions be tagged in the upstream project repository.  I'm not a cargo developer, so perhaps the plan is indeed to start using the tag mechanism once we have hit a version beyond `0.0.1-pre`, but we have not yet hit a stable version, and thus no tags yet exist.

Anyway, I figured I would open this ticket to track any effort towards homebrew compatibility, with the intention that this ticket be closed once `brew install cargo` does something plausible.  :)

**Comment by schickling** [comment]
+1

**Comment by pnkfelix** [comment]
it sounds like the fundamental problem here has not been resolved.  Reopening.

**Comment by schickling** [comment]
Current workaround:

```sh
$ brew cask install cargo
```

**Comment by rogeriopvl** [comment]
+1

**Comment by quadrupleslap** [comment]
Has this been done yet? Because `brew install cargo` still doesn't work afaict.

**Comment by pnkfelix** [comment]
to my knowledge it is still unaddressed.

**Comment by lepture** [comment]
+1

**Comment by bwhitty** [comment]
+1

**Comment by fiag** [comment]
+1

**Comment by pwnall** [comment]
+1

**Comment by nickbroon** [comment]
:+1:

**Comment by iyedb** [comment]
+1

**Comment by mbaltrusitis** [comment]
+1

**Comment by parkr** [comment]
still can't `brew install cargo`. was expecting `brew install rust` to install cargo as well, but alas.

**Comment by archshift** [comment]
`brew install rust` now installs cargo as of https://github.com/Homebrew/homebrew/commit/1be7f90419594fed9bbd035336239ed5e7c4a032
