### ISSUE TITLE
Stale rustc_info cache reused after modifying custom target

### ISSUE THREAD

**Issue by roblabla** [rust-lang/cargo#8085]
**Problem**
When using a custom target JSON, cargo will reuse `rustc_info` cached target information even after modifying said JSON. When building with potentially unsupported crate types (like cdylib), this can cause `cargo` to keep saying the crate type is unsupported even after having modified the custom target JSON to add support to it, until the `target` folder is cleaned.

**Steps**
1. Clone https://github.com/roblabla/cargo-custom-target-stale-cache-repro
2. run `cargo build --target aarch64-roblabla-switch.json`. This will fail with `error: cannot produce cdylib for ``no_std_test v0.1.0 (/home/roblabla/Dropbox/dev/src/rust/test)` as the target `aarch64-roblabla-switch` does not support these crate types``, which is expected.
3. Change the `aarch64-roblabla-switch.json` file to have `dynamic-linking: true`.
4. Run `cargo build --target aarch64-roblabla-switch.json` again. It will fail with the same error again, even though now the target JSON supports it.
5. `rm target/.rustc_info.json` and run `cargo build --target aarch64-roblabla-switch.json`. This time, it will start building (and complain `core` isn't present, because we aren't using xargo for simplicity's sake).

**Possible Solution(s)**
For custom targets, cargo should probably cache a modification timestamp of the JSON, and check it before using the cache?

**Notes**

Output of `cargo version`:

cargo 1.42.0 (86334295e 2020-01-31)
rustc 1.42.0 (b8cedc004 2020-03-09)

**Comment by ehuss** [comment]
Thanks for the report.  This is almost identical to #2616, so closing in favor of that.
