### ISSUE TITLE
Colors from rustc are not shown on Windows.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/cargo#8089]
Environment is Windows 7 with `cmd.exe`. Rust and cargo are stable 1.42, nightly does the same.

Here’s a screenshot:
![Screenshot](https://user-images.githubusercontent.com/3986214/78836576-ab3a6980-79f2-11ea-9bd6-f66a87d91d53.png)
```rust
struct S;
fn main() {
    let x = S;
    drop(x);
    drop(x);
}
```

**Comment by ehuss** [comment]
This is actually an upstream issue. There's more detail at https://github.com/rust-lang/rust/issues/55769.  I have mostly forgotten where things stand, but I think there still might be a blocking issue (https://github.com/kennytm/fwdansi/issues/2).  There's also more detail about the reset problems in https://github.com/kennytm/fwdansi/issues/1.

**Comment by ehuss** [comment]
This should be fixed on the latest nightly (2020-07-31) via https://github.com/rust-lang/cargo/pull/8540 and https://github.com/rust-lang/rust/pull/74923.
