### ISSUE TITLE
`cargo doc` and `cargo test --doc` execute `rustdoc` in different directories.

### ISSUE THREAD

**Issue by olson-sean-k** [rust-lang/cargo#8097]
### Problem
It appears that when using workspaces and executing `cargo` against a manifest with only workspace members (i.e., at the root of a repository), `cargo doc` and `cargo test --doc` execute `rustdoc` in different directories. **This interacts poorly with relative paths used in additional flags for `rustdoc`** (either from environment variables or a Cargo configuration file).

Depending on the relative paths involved (e.g., `./path` vs. `../path`), this causes one of `cargo doc` or `cargo test --doc` to fail with an error stating that the path cannot be found.

This is likely complicated, but at first I expected that relative paths would resolve the same way for both `cargo doc` and `cargo test --doc` when executed in the same directory.

### Steps
1. Create a repository with a workspace and a member package in a subdirectory.
2. Create an HTML file at the root of the repository (its contents do not matter).
3. Pass a relative path to this file to `rustdoc` via `--html-in-header` using an environment variable or Cargo configuration file.
4. Execute `cargo doc` and `cargo test --doc` from the root of the repository (using the workspace manifest).

See [this commit](https://github.com/olson-sean-k/plexus/commit/89f850f83d1edf8f1119004c19a5074e3f31d988) in a workspace repository for an example of this problem. The CI for that project fails with [similar errors](https://github.com/olson-sean-k/plexus/runs/581329099#step:4:551) on different operating systems.

### Possible Solution(s)
I'm really not sure what is acceptable here. I encountered this when I tried to migrate away from using a simple shell script for generating documentation that uses the `RUSTDOCFLAGS` environment variable.

### Notes
I've encountered this using both stable and nightly toolchains on Windows 10 and Arch Linux.

Output of `cargo version`: `cargo 1.42.0 (86334295e 2020-01-31)`
Output of `cargo +nightly version`: `cargo 1.44.0-nightly (7019b3ed3 2020-03-17)`

**Comment by ehuss** [comment]
I suspect it was mostly an oversight that `test --doc` doesn't adjust the current dir.  Normal rustc/rustdoc execution is very careful about using relative paths and cwd [here](https://github.com/rust-lang/cargo/blob/15d8044f05551446aeef638354b79aba3389a4e1/src/cargo/core/compiler/mod.rs#L660-L693), but the [corresponding usage](https://github.com/rust-lang/cargo/blob/15d8044f05551446aeef638354b79aba3389a4e1/src/cargo/ops/cargo_test.rs#L161) for doc tests isn't so careful.
