### ISSUE TITLE
Make --offline flag variable

### ISSUE THREAD

**Issue by Zapeth** [rust-lang/cargo#8099]
**Describe the problem you are trying to solve**

Currently the `--offline` specifier can only be used to enforce offline mode for cargo, but there doesn't seem to be way to do the reverse operation (enforce online mode), at least `cargo fetch --offline=false` still fails in offline mode.

**Describe the solution you'd like**

Either add an `--online` specifier or make the `--offline` specifier variable when executing cargo, like so: `--offline=[true|false]`

**Comment by ehuss** [comment]
Can you explain why this would be useful? "Online" is the default mode if you don't pass `--offline`.

**Comment by Zapeth** [comment]
I would like cargo to connect online only when necessary/specified, therefore I have set `offline = true` in `$CARGO_HOME/config`.

However when doing that, there seems to be no way to override/unset the setting from CLI.

So whenever I want to fetch updates or install new packages I have to disable the setting in the config manually, run the command and then re-enable the setting instead of just doing something like `cargo fetch --offline=false`.

**Comment by ehuss** [comment]
Ah.  An alternative for now is to use the `CARGO_NET_OFFLINE=false` environment variable, which takes precedence over files.  Cargo also has an experimental feature to control config settings via the command line with `-Zunstable-options --config net.offline=false`.

Unfortunately the argument parser we use doesn't easily support optional values, so `--offline=false` would be difficult to support.

**Comment by Zapeth** [comment]
Thanks for the information, `--config net.offline=false` would also work fine for me.

I guess I'll make do with the environment variable until it gets into stable.
