### ISSUE TITLE
Cargo skips "Doc-tests" when targeting x86_64-pc-windows-msvc.

### ISSUE THREAD

**Issue by Antigroup** [rust-lang/cargo#8111]
**Problem**
If I run `cargo test` out of the box, "Doc-tests" is run and cargo invokes rustdoc as expected, but if I set `--target x86_64-pc-windows-msvc` on Windows (after installing the target with rustup), "Doc-tests"

**Steps**
1. `cargo test --target i686-pc-windows-msvc`
"Doc-tests" in the output
2. `cargo test --target x86_64-pc-windows-msvc`
"Doc-tests not in the output

**Notes**
i686-pc-windows-msvc is the default target used on Windows.

Output of `cargo version`: `cargo 1.42.0 (86334295e 2020-01-31)`
Output of `rustup --version`: `rustup 1.21.1 (7832b2ebe 2019-12-20)`
Output of `rustc --version`: `rustc 1.42.0 (b8cedc004 2020-03-09)`

**Comment by ehuss** [comment]
Cross-compilation of doc tests is currently an experimental feature.  See #7040 for more detail.
