### ISSUE TITLE
Want Cargo with add/remove/update dependencies command

### ISSUE THREAD

**Issue by Gumichocopengin8** [rust-lang/cargo#8131]
Thank you for the Cargo. I really love it.
However, I need to write each dependency by hand in Cargo.toml.
It is a tough task for me. I want commands like npm and yarn.
such as, `cargo add rand`

Thank you!

**Comment by ehuss** [comment]
Thanks!  

You can install [cargo-edit](https://crates.io/crates/cargo-edit) which incorporates these commands (`cargo install cargo-edit`).  #5586 is tracking making that built-in.
