### ISSUE TITLE
Please tag 0.43.1

### ISSUE THREAD

**Issue by infinity0** [rust-lang/cargo#8132]
Version 0.43.1 was published to crates.io as part of #7994 but there is no corresponding tag. Thanks in advance!

**Comment by infinity0** [comment]
Commit 5b129c4fed8a5cf1e8834c49add647740f536259 [for reference](https://github.com/rust-lang/cargo/issues/7994#issuecomment-600111341).

**Comment by infinity0** [comment]
Apparently this commit is dangling so you'll have to `git fetch origin 5b129c4fed8a5cf1e8834c49add647740f536259` directly

**Comment by Mark-Simulacrum** [comment]
The commit appears to be the tip of the rust-1.42.0 branch?

**Comment by Mark-Simulacrum** [comment]
Anyway, tagged 0.43.1 at that commit, and pushed; closing.

**Comment by infinity0** [comment]
Thanks! Yes my mistake, I forgot about side branches when pulling.
