### ISSUE TITLE
Default values for `readme` if not specified

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/cargo#8133]
Many packages specify `readme = "README.md"`. Could we automatically detect `README.md`,`README`, or `README.txt`, and use those as the values of `readme` if the files exist and the manifest key doesn't, just as we do for `build`? That would avoid the need to specify it in most common cases.

**Comment by joshtriplett** [comment]
We discussed this in the cargo meeting, and agreed we should do this.

Also, `readme = false` should disable this behavior, just as `build = false` disables the default of using `build.rs` if it exists.

**Comment by tverghis** [comment]
I'd like to take a stab at this!

**Comment by ehuss** [comment]
Thanks @tverghis!  Let us know if you have any questions.
