### ISSUE TITLE
Expose machine_message.rs as a crate so that it's easy for third party tools

### ISSUE THREAD

**Issue by richardwhiuk** [rust-lang/cargo#8142]
**Describe the problem you are trying to solve**

Currently https://doc.rust-lang.org/cargo/reference/external-tools.html#json-messages nicely describes the messages which Cargo can output.

However, there's no programmatic definition, so integrations are forced to copy and paste structs out of Cargo's code to parse them.

**Describe the solution you'd like**

It'd be nice if there was a rust crate which a) Cargo used to define these messages and b) third party developers could pull and use `serde::Deserialise` to parse them.

**Comment by ehuss** [comment]
The types are available via the [`cargo_metadata`](https://crates.io/crates/cargo_metadata) crate (see the [`Message`](https://docs.rs/cargo_metadata/0.9.1/cargo_metadata/enum.Message.html) type).

**Comment by ehuss** [comment]
Closing, `cargo_metadata` is the intended way, particularly if using serde.
