### ISSUE TITLE
target-cpu seems to be ignored in Cargo.toml

### ISSUE THREAD

**Issue by synthercat** [rust-lang/cargo#8150]
I'm rather new to rust but I'm pretty sure I found a bug here.
Let me show an example. I have this as my Cargo.toml
```
[package]
name = "benchmark"
version = "1.0.0"
authors = ["Antonis Savvidis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
target-cpu = "k6"
```
and then I try **cargo build --release**
which **should** output something like: LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it! 
That's what's happening when I try to parse k6 on rustc.

However what does happen is that the option is ignored & the app is compiled without any warnings. You could try

`[profile.release]
target-cpu = "Antonis was here!"`

it will still compile under **cargo build --release**

**Comment by ehuss** [comment]
`target-cpu` is not a profile setting. You can see the list of valid profile settings at: https://doc.rust-lang.org/cargo/reference/profiles.html

Additional [rustc flags](https://doc.rust-lang.org/rustc/codegen-options/index.html) can be passed via the RUSTFLAGS [environment variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html) or a [config file](https://doc.rust-lang.org/cargo/reference/config.html).

**Comment by synthercat** [comment]
I was just under the impression that an error/warning should be shown. Thank you for your time. Rust rocks!
