### ISSUE TITLE
Configuration setting to select toolchain (nightly)

### ISSUE THREAD

**Issue by binkley** [rust-lang/cargo#8152]
**Describe the problem you are trying to solve**

I feel my issue might already be covered in another issue, or be a non-issue, however I was not able to find the right issue in GitHub.  Apologies if this is a duplicate.

I would like _local_ per-project configuration on which toolchain to use (stable, beta, nightly).  I am making use of the `feature` macro in a particular project, and when I `cd` to that project, I would like to type just `cargo build` rather than `cargo +nightly build`.

**Describe the solution you'd like**

I am looking for a setting in `./.cargo/config` for my local directory which sets the toolchain to "nightly".  This may exist!  However, reading https://doc.rust-lang.org/cargo/reference/config.html I did not spot a setting to configure.

**Notes**

My project is here: https://github.com/binkley/spikes/tree/master/rust-green-threads

**Comment by ehuss** [comment]
`rustup` has several override features. You can either add a [`rust-toolchain` file](https://github.com/rust-lang/rustup#the-toolchain-file) or use [per-directory overrides](https://github.com/rust-lang/rustup#directory-overrides).

**Comment by Eh2406** [comment]
So that is a rustup feature, not strictly a Cargo thing. You are looking for `rustup override set nightly` or the `.toolchain` file. ... and Eric beat me to it.

**Comment by binkley** [comment]
@ehuss Fantastic, thank you!  Now `cargo build` works just fine.

Two requests:

- `git status` does not show any changes.  How would one cloning a repository needing nightly builds pick this up automatically?
- The documentation on this (https://doc.rust-lang.org/cargo/reference/config.html) does reference what you describe, but only obliquely.  Could the documentation improve here?

**Comment by ehuss** [comment]
> `git status` does not show any changes. How would one cloning a repository needing nightly builds pick this up automatically?

I'm not sure I understand the question. If you add and commit a `rust-toolchain` file to your repository, anyone checking it out should pick it up and start using that toolchain.

> Could the documentation improve here?

Yea, we have an open issue (#8058) to improve it. It is a little awkward because rustup is a completely separate tool, and not everyone uses it, so it is not directly related to cargo per se. But I'd definitely like to make the documentation clearer and more discoverable.

**Comment by binkley** [comment]
@ehuss I'm looking for something like a `.cargo/config` which I can commit to a repository.  The goal would be that when one clones a git repository needing the nightly toolchain, no more effort from them is required than just `cargo build`.

(See https://github.com/rust-lang/cargo/issues/8058 on documentation)

**Comment by sfackler** [comment]
> I'm looking for something like a `.cargo/config` which I can commit to a repository. The goal would be that when one clones a git repository needing the nightly toolchain, no more effort from them is required than just `cargo build`.

If you add and commit a rust-toolchain file to your repository, anyone checking it out should pick it up and start using that toolchain.

**Comment by binkley** [comment]
@sfackler Fantastic, just what I was looking for!  Thank you
