### ISSUE TITLE
Cargo is missing the .git from the crates io repo url

### ISSUE THREAD

**Issue by gilescope** [rust-lang/cargo#8174]
With the removal of CARGO_REGISTRY_INDEX we have to find another workaround for a problem we've been having living behind an enterprise proxy. 

In order to escape through the proxy cargo needs to request 
`https://github.com/rust-lang/crates.io-index.git` rather than the default of 
`https://github.com/rust-lang/crates.io-index`.

I'm sure we can find another work-around, but I'm just wondering if the more standard thing is to have the `.git` on the end - I need to add that for normal personal repos that I clone, so I'm thinking that's the more standard approach?

Thoughts?

**Comment by ehuss** [comment]
AFAIK this hasn't ever come up with github or the crates.io index. I believe GitHub treats the two URLs identically. Some services, like gitlab, use a redirect, but I don't think that is relevant here. 

I think it would be very risky to change it at this time, as existing setups may be depending on the exact URL, and probably not worth the churn.  In the distant future we're looking at alternate ways to serve the index, so we may have to put more consideration into how to differentiate different protocols, but that's a ways off.

In terms of workarounds, one option is [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html).  Something like the following should work:

```toml
[source.crates-io-git]
registry = "https://github.com/rust-lang/crates.io-index.git"

[source.crates-io]
replace-with = "crates-io-git"
```

**Comment by gilescope** [comment]
Yep that work around works well for us. Just thought I should mention it as others might come across the same problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gilescope** [comment]
Btw I can see that adding .git on the end changes the hash dir name that it's stored as - I can see how that might be disruptive so let's leave as is.
