### ISSUE TITLE
Tracking issues for the `-Zmultitarget` feature

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#8176]
This is intended to be a tracking issue for `-Zmultitarget` being implemented in https://github.com/rust-lang/cargo/pull/8167. This feature allows passing the `--target` flag multiple times to Cargo to build code simultaneously for multiple targets. This was originally requested in https://github.com/rust-lang/cargo/issues/8156 and https://github.com/rust-lang/cargo/issues/3913.

Currently the semantics of `-Zmultitarget` is that it simply allows passing `--target` multiple times (2 or more) to Cargo. Cargo recognizes this as doing what it was already doing, only now for multiple targets instead of just a single target. Internally Cargo's unit graph should still have all the edges drawn correctly and whatnot.

**Comment by 4ad** [comment]
How is this supposed to interact with the (currently single) target specification in `config.toml`?

**Comment by alexcrichton** [comment]
I think we'd probably want to implement support for `build.target = ["array", "of", "targets"]`

**Comment by 4ad** [comment]
SGTM.

**Comment by khionu** [comment]
Just saw that the referenced PR is closed. Is this

**Comment by Jasper-Bekkers** [comment]
> Just saw that the referenced PR is closed. Are there any pending steps before closing this issue?

I'm also curious about potential next steps on this issue.

**Comment by edwincoronado** [comment]
I have a `config.toml` file that looks like this:

```toml
[unstable]
multitarget = true

[build]
target = ["nightly", "nightly-i686-unknown-linux-gnu"]
```

but getting an error `"build.target" expected a string, but found a array`, using the cli `--target` argument is really not an option for me since I'm using workspaces for a large project. 

Does anybody know a workaround?

**Comment by weihanglo** [comment]
`-Zmultitarget` exists on nightly for years (https://github.com/rust-lang/cargo/pull/8167, merged in April 2020). It has already been in the wild for a long time, and is the main code path of cargo compilation since then. The support of multitarget in `.cargo/config.toml` has landed (March 2022 #10473) with only minimal additions.

It may be the time to push it to stable. #10766 tries to stabilize it. Need some inputs from others.

@rfcbot fcp merge

**Comment by ehuss** [comment]
One note I wanted to point out is that `cargo doc` and `cargo install` do not support multiple targets. I do not think that is a blocker for stabilizing, but is something that may want to be considered in the future if those are things someone wants.

It is also not supported by the unstable artifact-dependencies and per-package-target feature (in the sense that they only allow selecting a single target).  Also not a blocker, and also can be added at any time in the future. Just trying to note that this has a ripple effect across other features.

**Comment by khionu** [comment]
> One note I wanted to point out is that `cargo doc` and `cargo install` do not support multiple targets. I do not think that is a blocker for stabilizing, but is something that may want to be considered in the future if those are things someone wants.
> 
> It is also not supported by the unstable artifact-dependencies and per-package-target feature (in the sense that they only allow selecting a single target). Also not a blocker, and also can be added at any time in the future. Just trying to note that this has a ripple effect across other features.

Rustdoc marks features as being only active for certain targets, and `cargo install` is meant for installing on the local machine, so neither `cargo doc` or `cargo install` really make any sense. The one exception I can think of is for WASM applications, you would want `cargo install` to build for WASM, but that seems a bit of a clunky use of `cargo install` anyways.

**Comment by Lokathor** [comment]
cargo install might be wanted to build for any platform with an emulator, but yes you probably don't need multitarget in that case, a project probably only supports that one platform.

**Comment by ehuss** [comment]
Yea, `cargo install` is probably not applicable.

However, for `cargo doc` I was thinking it would generate:
```
target/x86_64-apple-darwin/doc/…
target/aarch64-apple-darwin/doc/…
```
That is, equivalent to running `cargo doc --target x86_64-apple-darwin && cargo doc --target aarch64-apple-darwin`. I can't think of a good use case for that, though. 

It would be interesting if rustdoc could union multiple target cfgs within the same documentation (without needing to do `#[cfg(doc)]` shenanigans like the standard library does).
