### ISSUE TITLE
latest cargo update broke `cargo install` command in my ci

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#8183]
Hi, it looks like the latest cargo submodule bump in the rustc repo
https://github.com/rust-lang/rust/commit/f23db015ad5d306bbb0de104817c9a8cc4ee1db9
broke my [cargo-cache ci](https://github.com/matthiaskrgr/cargo-cache/actions).

I was running the command `cargo install --force --git https://github.com/matthiaskrgr/cargo-cache --no-default-features --features ci-autoclean cargo-cache`
which worked prior to the submodule update and [now fails with](https://github.com/matthiaskrgr/cargo-cache/runs/631882362?check_suite_focus=true#step:27:1)
````
    Updating git repository `https://github.com/matthiaskrgr/cargo-cache`
  Installing cargo-cache v0.4.2 (https://github.com/matthiaskrgr/cargo-cache#379c40c2)
    Updating crates.io index
error: failed to compile `cargo-cache v0.4.2 (https://github.com/matthiaskrgr/cargo-cache#379c40c2)`, intermediate artifacts can be found at `/tmp/cargo-installDT5PxT`

Caused by:
  failed to determine package fingerprint for build script for cargo-cache v0.4.2 (/home/runner/.cargo/git/checkouts/cargo-cache-16826c8e13331adc/379c40c)

Caused by:
  failed to determine the most recently modified file in /home/runner/.cargo/git/checkouts/cargo-cache-16826c8e13331adc/379c40c

Caused by:
  failed to determine list of files in /home/runner/.cargo/git/checkouts/cargo-cache-16826c8e13331adc/379c40c

Caused by:
  expected git repo /usr/share/rust/.cargo/git/checkouts/cargo-cache-16826c8e13331adc/379c40c/.git/ to be parent of package /home/runner/.cargo/git/checkouts/cargo-cache-16826c8e13331adc/379c40c

Caused by:
  prefix not found
##[error]Process completed with exit code 101.
````

I have never seen this error before and was not able to reproduce locally yet with `rustc 1.45.0-nightly (fa51f810e 2020-04-29` / `cargo 1.45.0-nightly (90931d9b3 2020-04-28)`

Do you have any ideas what could be happening here?

**Comment by ehuss** [comment]
Thanks for the report. It looks like if CARGO_HOME is a symlink causes the problem. Part of the fallout from #8095.  I'll take a look.
