### ISSUE TITLE
Rust unable to perform cargo run and cargo build on WSL

### ISSUE THREAD

**Issue by RussellAjax** [rust-lang/cargo#8184]
**Problem**

While learning Rust, I experienced a problem regarding `cargo build` and `cargo run` .
The error code is as follows:
```
richardrussell@Russell: /mnt/c/Users/Russell/amorfati/rust/test_file/src$ cargo run
Compiling test_file v0.1.0 (/mnt/c/Users/Russell/amorfati/rust/test_file)
error: Operation not permitted (os error 1)
```

Aside from these two, other commands such as `cargo new` works perfectly. 
**Steps**

1. Create a new cargo directory using `cargo new`
2. Since `cargo new` will create a default main.rs file with "Hello, World", we can automatically run `cargo run`
3. The error message will appear as above

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo 1.43.0 (3532cf738 2020-03-17)

Installation method: Since this uses WSL, my Ubuntu version is Ubunutu 18.04.4 LTS which I downloaded over from the Microsoft Store. I also installed Rust using the WSL command in their website (`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`)

**Comment by ehuss** [comment]
Thanks for the report. For now, I think you'll need to use a local Ubuntu filesystem. The mounted Windows filesystems don't seem to support file mtime modifications.  I have posted a fix at #8185.
