### ISSUE TITLE
Readme says cargo just needs git to build on windows...

### ISSUE THREAD

**Issue by gilescope** [rust-lang/cargo#8190]
**Problem**

Quite a few crates use cargo as a dependency. As such it would be great if cargo built on windows easily (we use the msvc toolchain).

But when you build something depending on the cargo crate in windows 10 you get:

Caused by:
  process didn't exit successfully: `C:\DEVELO~1\Temp\cargo-installR7sgTS\release\build\libz-sys-c5dba26ec57df1d6\build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
cargo:rerun-if-changed=build.rs
note, vcpkg did not find zlib: Aborted because VCPKGRS_DYNAMIC is not set

 **Steps to reproduce**
1. cargo install cargo-local-registry

Should we be manually building vcpkg and then downloading some packages for it? It's not clear how we should be building this in windows.

**Possible Solutions**
A pure rust zip crate instead as a dependency is the long term solution.
Give additional guidance on the readme as to how to build on windows.

**Comment by weihanglo** [comment]
I have the impression that https://github.com/rust-lang/cargo/pull/11030 expands the requirements well, so we may close this issue at this moment. Thank you!

I do agree that pure Rust crate sounds great but it is really a long long long term solution 😆
