### ISSUE TITLE
Cannot product disassembly file using ```cargo rustc -- --emit asm```

### ISSUE THREAD

**Issue by GregWoods** [rust-lang/cargo#8199]
I am using rust 1.43.0.
My code compiles just fine.
I am compiling for stm32f411.

```cargo rustc -- --emit asm```
does not produce any disassembly files either (which I believe have a .s file extension)

There is a warning:
```warning: ignoring emit path because multiple .s files were produced```

Not sure what other info to supply.
I'm sure I'm making some noob mistake, but I can't figure it out.

**Comment by ehuss** [comment]
Did you check the `target/debug/deps` directory? That's where all of rustc's output goes.

As for the "multiple .s files", IIRC I think that is a consequence of multiple codegen units. Setting codegen-units to 1 I think should make it produce a single assembly file. Also, FYI, it looks like this has changed on nightly (which I think automatically switches to codegen-units=1).

**Comment by GregWoods** [comment]
Awesome fast response, thank you.
I was using the semi-useless Windows Explorer search to look for any .s files. That was my mistake.
The files are in: 
```target\thumbv7em-none-eabihf\debug\deps```
Now I feel dumb for not finding them :)

The compiler has produced 8 different Assembler source files, which is what the warning, and your comment are talking about.

By adding the "Optimize" -O parameter, I get get from 8 .s files down to 2
Adding ```-C codegen-units=1``` results in no .s files being produced.

**Comment by GregWoods** [comment]
The following works
```cargo rustc --release -- --emit asm -C codegen-units=1```

With the following in my cargo.toml
```
[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 1   #default was 16. Changed to 1 to allow creating a single disassembly file using -- --emit asm
rpath = false
```
