### ISSUE TITLE
error: could not find `Cargo.toml`

### ISSUE THREAD

**Issue by glebcomissarov** [rust-lang/cargo#8201]
hello guys!
I've just started to code on Rust and I have a problem)))
I set up `PATH` for cargo, rustc and rustup like `~\.cargo\bin`
and

**Problem**
I launched VS Code and created a new project and 
1. all code in `Cargo.toml` in was underlined with a red line (like on the picture)
2. when I tried to run the project I meet this error
`error: could not find Cargo.toml in C:\Users\Green Eagle\Desktop\progr\rust or any parent directory`

I would be very grateful if you can help me
thank you)))

![image](https://user-images.githubusercontent.com/49168459/80924107-d1ec8580-8d8f-11ea-88cb-398c2bb0cd8b.png)
and 
![image](https://user-images.githubusercontent.com/49168459/80924800-bedbb480-8d93-11ea-981e-72c42776c4eb.png)

**Comment by ehuss** [comment]
I would suggest if you're having problems getting started to ask on https://users.rust-lang.org/ or one of the chat channels or other forums.

From a brief glance at your screenshot, it looks like you created a project in a directory named "ggg".  Cargo needs to run within the directory that contains the file `Cargo.toml`.

**Comment by glebcomissarov** [comment]
thanks, I'll try to ask at the site you mentioned.
