### ISSUE TITLE
Add option to disable --document-private-items for targets that have it by default

### ISSUE THREAD

**Issue by Pand9** [rust-lang/cargo#8237]
Building a documentation for a Rust project - which at this stage is just a single crate with single binary target - I've discovered that all private items are included. Running `-vv` helped me discover that Cargo has ran `rustdoc` with flag `--document-private-items`, even though I haven't passed it to cargo. There is no option `cargo doc --no-document-private-items` either.

I would like to have such option.

**Comment by ehuss** [comment]
Thanks for the report!  Closing as a duplicate of #7963.
