### ISSUE TITLE
Visualising public type structure of a library

### ISSUE THREAD

**Issue by nicolaiunrein** [rust-lang/cargo#8240]
**Describe the problem you are trying to solve**

I would like to be able to quickly get an overview of the structure of public types and their relationship. 

**Describe the solution you'd like**

I would like to have a cargo subcommand to list all exported types from a library. Basically visualising all the paths a user can "use".

Something like calling `cargo export-tree` and see a tree of my exported types starting with my crate-name as the root.

**Notes**

The expected output would look something like this:

```
my_lib
  |__ MyError
  |__ MyImportantStruct
  |__ my_mod_a
  |    |__ my_fn_a
  |    |__ my_fn_aa
  |
  |__ my_mod_b
       |__ MyStructB
       |__ MyTraitB
```

I would write the tool myself but I don’t know where to best get the relevant information which I can then traverse and turn into a tree like above.

**Comment by ehuss** [comment]
I think this would be best implemented as an external command. You can see `[cargo-modules]`(https://crates.io/crates/cargo-modules) as an example. rustc has a variety of unstable flags (see `rustc -Zhelp`) that can maybe export the information you're looking for. I think I've also seen some people scrape the output from rustdoc, though that can break over time.

**Comment by nicolaiunrein** [comment]
Thank you!
