### ISSUE TITLE
error: no such subcommand: `tree`

### ISSUE THREAD

**Issue by muv1** [rust-lang/cargo#8257]
I see this: https://github.com/rust-lang/cargo/pull/8062

but for some reason I cannot use it:

~~~
$ cargo -V
cargo 1.43.0 (2cbe9048e 2020-05-03)

$ cargo init
     Created binary (application) package

$ cargo tree
error: no such subcommand: `tree`

        Did you mean `new`?
~~~

am I doing something wrong? I got Rust from here:

<https://static.rust-lang.org/dist/rust-1.43.1-x86_64-pc-windows-gnu.msi>

**Comment by ehuss** [comment]
Rust uses a release train model, where it can take 6 to 12 weeks for changes to reach the stable channel. You can read more about it at https://doc.rust-lang.org/book/appendix-07-nightly-rust.html.  `cargo tree` will be in 1.44 which is now available as beta.  You can also install the old version if you can't use beta (`cargo install cargo-tree`).
