### ISSUE TITLE
git2 repository update lead to read zlib stream error when fetch repo

### ISSUE THREAD

**Issue by jongwu** [rust-lang/cargo#8258]
**Problem**
there maybe a bug in the latest cargo dependency repo of git2 which will lead to "error reading from the zlib stream" when fetch a certain repo (I don't know which of  its group) in cargo build.
I have not detected why these happen, but I confirm that it is the git2 repo(0.12, 0.12+) in cargo dependency cause the error.
**Steps**
I have just one example to reproduce the error.
1. go get github.com/kata-containers/kata-containers
2. cd $(GOPATH)/github.com/kata-containers/kata-containers/ && git checkout 7087b5f43c86367f78d28
3. make
be patient, then you will get the error log.

**Possible Solution(s)**
I'm not familiar with libgit2, so I can't tell why this happen, only, I can tell the error come from git_packfile_stream_read in the libgit2/src/pack.c

**Notes**

Output of `cargo version`:

I have tested cargo 1.43.1 even the latest cargo from source code (13bded9a335a855a15b95f54)

@wycats  @halorgium  @alex

**Comment by alexcrichton** [comment]
Thanks for the report! Would it be possible to minimize this a bit more? Or could you provide some logs of what happens? It'd be useful to know what Cargo is cloning. You might have some success digging with `CARGO_LOG=trace` as well.

**Comment by jongwu** [comment]
hello @alexcrichton , sorry to have not add the error log. here it is:

`Updating git submodule `https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer`
error: failed to get `grpcio` as a dependency of package `protocols v0.1.0 (/root/go/src/github.com/kata-containers/kata-containers/src/agent/protocols)`

Caused by:
  failed to load source for dependency `grpcio`

Caused by:
  Unable to update https://github.com/alipay/grpc-rs?branch=rust_agent#eee4635f

Caused by:
  failed to update submodule `grpc-sys/grpc`

Caused by:
  failed to update submodule `third_party/bloaty`

Caused by:
  failed to update submodule `third_party/libFuzzer`

Caused by:
  failed to fetch submodule `third_party/libFuzzer` from https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer
Caused by:
  error reading from the zlib stream; class=Zlib (5)

`
I hope it will be helpful.

**Comment by alexcrichton** [comment]
Thanks! I'm indeed able to reproduce this with 

```rust
git2::Repository::clone(                                                      
    "https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer",
    "test",                                                                    
)                                                                             
.unwrap();                                                                    
```

Running in a debugger it does indeed look like libz is simply returning an error. [The origin of the git error](https://github.com/libgit2/libgit2/blob/b7b872f51074ef8231ae8b94dd93eada127c9365/src/pack.c#L794) fails on [this call to `inflate`](https://github.com/libgit2/libgit2/blob/b7b872f51074ef8231ae8b94dd93eada127c9365/src/zstream.c#L123) where the error gets [generated here](https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/inflate.c#L1212-L1213). 

I haven't extracted the zlib stream but it sort of seems like this is a legitimately invalid zlib stream, or at least according to libz it is. Either that or it's being fed into libz incorrectly by libgit2, which is also possible.

In any case this isn't an issue Cargo itself can deal with. At most it's an issue with libgit2, but it could also be an issue with libz or the server itself.

**Comment by jongwu** [comment]
@alexcrichton so, should we pass this ball to libgit2 community to resolve this issue?

**Comment by alexcrichton** [comment]
Indeed, I've opened up https://github.com/libgit2/libgit2/issues/5525
