### ISSUE TITLE
Opening cargo docs in browser on windows subsystem for Linux

### ISSUE THREAD

**Issue by Jumail** [rust-lang/cargo#8259]
I have been using WSL for a while and I have switched to using rust on it as well. But when I try to build the documentation for a project, it returns this error
`xdg-open: no method available for opening `
I have worked with React and I haven't faced any errors my project in the browser so far.

I am using cargo 1.43.0 (2cbe9048e 2020-05-03)

**Comment by ehuss** [comment]
Thanks for the report, this is essentially the same as #7557, so closing in favor of that.
