### ISSUE TITLE
cargo build --release issue

### ISSUE THREAD

**Issue by SahiDemon** [rust-lang/cargo#8260]
**cargo build --release** when i use this command in that directory above mention it says 
'cargo' is not recognized as an internal or external command,
operable program or batch file.

how to fix this please help me

**Comment by Eh2406** [comment]
Witch directory? How did you install rust? What Operating system are you on? Have you tried rebooting?

**Comment by ehuss** [comment]
Closing since we haven't heard from you in a while.  You might also want to try one of the user forums for help with getting started.
