### ISSUE TITLE
"cargo install --target-dir" does not work

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/cargo#8263]
`cargo install` clearly needs a target dir, and honors the `CARGO_TARGET_DIR` env var. But for some reason it does not accept the `--target-dir` flag, unlike the other commands.

Would be nice to make this consistent. :)

**Comment by ehuss** [comment]
@alexcrichton mentioned in https://github.com/rust-lang/cargo/issues/4725#issuecomment-350373564 that you would prefer not to add the flag at that time. I wonder if your mind has changed on that?  I don't see any particular downsides to adding it, and it would provide consistency with all the other build commands.

**Comment by alexcrichton** [comment]
I believe that comment was more in reference to "let's not add a single flag for just `cargo install`", but now that `--target-dir` is everywhere *except* `cargo install` then makes sense to me to add support there.

**Comment by bl2e** [comment]
Would like to work on this!

**Comment by ehuss** [comment]
Great!  Let us know if you have any questions.

**Comment by AlvinKuruvilla** [comment]
Hello Im considering working on this issue, where exactly would this new flag be added I'm thinking it would be in the same file as https://github.com/rust-lang/cargo/pull/8344/commits/3fbd5aefd4bf47047924ce01e49106b78286146c or would there be a more suitable place ?

**Comment by ehuss** [comment]
@AlvinKuruvilla I think @bl2e mentioned they were working on this.  @bl2e are you still working on it?

Some brief instructions:
* There is an [`arg_target_dir`](https://github.com/rust-lang/cargo/blob/ee417cbc2fea5c63bb32f91af53e64a3ccbb381e/src/cargo/util/command_prelude.rs#L145-L149) function that needs to be called in the [install command](https://github.com/rust-lang/cargo/blob/master/src/bin/cargo/commands/install.rs).  
* Install has special consideration for the target dir, so [this code](https://github.com/rust-lang/cargo/blob/ee417cbc2fea5c63bb32f91af53e64a3ccbb381e/src/cargo/ops/cargo_install.rs#L266-L289) will need to be updated.
* At least one test should be added (perhaps more to test different source behavior).  Tests would go in [`install.rs`](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/install.rs). There are some existing tests for target-dir behavior there already. More details about running and writing tests can be found in [`CONTRIBUTING.md`](https://github.com/rust-lang/cargo/blob/master/CONTRIBUTING.md#running-tests) and [`cargo-test-support`](https://github.com/rust-lang/cargo/blob/master/crates/cargo-test-support/src/lib.rs).
* The documentation needs to be updated. There is some discussion of how to update the man pages in the [docs README](https://github.com/rust-lang/cargo/blob/master/src/doc/README.md).  The help item also needs to be updated.

**Comment by bl2e** [comment]
Yes still working on it.

**Comment by thiagoarrais** [comment]
Should be closed as of #8391?

**Comment by ehuss** [comment]
Yes, thanks!
