### ISSUE TITLE
Updating local registry

### ISSUE THREAD

**Issue by serayuzgur** [rust-lang/cargo#8273]
Hi,
I am the maintainer of the crates extension for vsc. We added  a feature for fetching crates versions from local registry. Since we couldn't find any way to update the registry with a cargo
command is it ok to  `git pull https://github.com/rust-lang/crates.io.git` to the `~/.cargo/registry/index/github.com-1ecc6299db9ec823/` folder ? 

The issue is [here](https://github.com/serayuzgur/crates/issues/81)

**Comment by alexcrichton** [comment]
Thanks for the report! The internal git repository Cargo uses doesn't have stability guarantees about it and we're not able to commit to any git operation working one way or another at this time. If you've got a need for this it'd be great to discuss it in a feature request to see if Cargo can support your use case!

**Comment by LucianoBestia** [comment]
Many cargo commands start with Updating crates.io index:
![image](https://user-images.githubusercontent.com/31509965/82995984-f6035580-a021-11ea-92a2-64a88c2ac8c7.png)
For example: cargo check, cargo build, cargo update,...
Is it possible to call only this action standalone with a cargo command?
Maybe like this  `cargo update --crates-io-index`
The extension of @serayuzgur  needs the local index to be updated to show the user fresh data.

**Comment by lnicola** [comment]
See also https://github.com/rust-lang/cargo/issues/3377.

**Comment by LucianoBestia** [comment]
Thanks @lnicola , I see this has a long history. And there are no stability guarantee, anyway.
