### ISSUE TITLE
P2P dependencies backed by IPFS

### ISSUE THREAD

**Issue by olanod** [rust-lang/cargo#8278]
I guess there are different ways of decentralizing the package repository and making use of IPFS to distribute crates but one approach that I think doesn't feel like a major change or very obtrusive would be to allow specifying a distributed dependency in the `Cargo.toml` file in a similar way we do with git dependencies.
```toml
[dependencies]
super-library = { p2p = "<ipfs hash of a directory containing a rust repository>" }
```
People can start using it for private repos or in any way they see fit, e.g. all devs in a company are fetching packages from each other and updating a shared registry(a toml/json file) where they communicate what are the latest versions of their libraries.

The fetch strategy would be first trying to get files from a local ipfs node and then try with a list of well known IPFS gateways. Later there can be a tighter integration with ipfs making use of the new [rust IPFS port](https://github.com/rs-ipfs/rust-ipfs).  
This feature can keep evolving little by little, a next step could be a cargo sub-command that helps "publishing" the crate doing the equivalent to `ipfs -r .` and ignoring unneeded files. The publishing procedure can further evolve, once there's a bunch of people relying on p2p dependencies is only natural that they will organize themselves and make a more advanced version of the shared json file I mentioned. Ideally I imagine a blockchain based decentralized organization that is economically incentivized to keep a high quality version of that file that not only maps package names to hashes but also versions and dependencies, members of the organization decide what to include and hopefully review packages carefully before inclusion similar to how linux distros do also having different channels like a `testing`, `stable`, etc. Or a community where package authors buy/register their package name and only them can publish new versions of their package.  
With a decentralized registry in place version dependency can be changed to 
```toml
[dependencies]
super-library = "🌎v1.2.3"
```

**Comment by joshtriplett** [comment]
There's a great deal of complexity involved here, and I don't think this would count as a minor change. That is *especially* true for any kind of partially decentralized registry as described here. Those aren't policies we'd be prepared to consider at this time, even if we had a concrete proposal in front of us.

As a more manageable initial step, I think it'd be reasonable to support some kind of "transport helpers", where you could specify a dependency via URL and provide a transport for the protocol used in that URL. That would allow experimenting with things like "download package from magnet link" or "download package from ipfs" outside of Cargo.

Meanwhile, I'm going to close this issue for now.

**Comment by Nemo157** [comment]
It should already be possible to setup an alternative registry hosted inside IPFS accessible via the local web gateway.
