### ISSUE TITLE
No colored output when run in Travis CI

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/cargo#8281]
Both Cargo and [cargo-all-features](https://github.com/frewsxcv/cargo-all-features/) (a utility I just wrote) utilize the termcolor crate for terminal colors. I was [trying out my utility in Travis CI](https://travis-ci.org/github/georust/geo/builds/690956246) and noticed this:

<img width="941" alt="Screen Shot 2020-05-25 at 11 43 34 AM" src="https://user-images.githubusercontent.com/416575/82827418-ff06f200-9e7c-11ea-9321-f1f071a414f9.png">

It seems like my utility is printing colors in CI fine, but Cargo isn't. Is this intentional or an oversight?

**Comment by ehuss** [comment]
Hm, that's really strange!  I did some tests, and I can't figure out what's going on.

Looking at https://travis-ci.org/github/georust/geo/pull_requests, it seems like some builds have color and some don't.  One thing I notice that is common is that the ones without color say this at the top:

```
Setting environment variables from repository settings
```

and the ones that have color say:

```
Encrypted environment variables have been removed for security reasons.
````

I'm wondering if maybe there is something weird about the cache?  Maybe try clearing the Travis cache and see if that makes a difference?  Or maybe Travis just behaves differently in these two modes (I'm not sure why some builds have secrets and some don't).  

I notice it also affects libtest as well, which uses the `term` crate, whereas Cargo uses `termcolor`. They both check if the stdout or stderr is a tty to decide to use color.  Maybe in the "no secrets" mode, Travis is piping the output without a tty?

**Comment by ehuss** [comment]
I'm going to close, as I have not heard back on any updates. Feel free to re-open if you come up with more information. From what I can tell, I think this just might be expected behavior on Travis due to how it filters the output.
