### ISSUE TITLE
Filter and build integration tests needed only

### ISSUE THREAD

**Issue by pickfire** [rust-lang/cargo#8282]
**Describe the problem you are trying to solve**

There is a project with 20+ integration tests, it takes like few minutes to build all of them. Even with a small change in one of the tests file and I wanted to just run one of the tests file, I did `cargo tests part_a` but it still compiles everything again.

The solution right now,

1. `rm tests/*`
2. `git restore tests/part_a.rs`
3. `cargo test part_a`, try rebuilding
4. `git restore src/dep.rs`, add some dependencies needed

Essentially, this will also remove the issue of clogging the screen with 0 tests run and the need to scroll up multiple times to search for the tests run #4324.

**Describe the solution you'd like**

Search for the functions used in the filter (`cargo test <filter>`), build and run only those files needed. Something like ripgrep for function name, but this requires cargo to include the dependencies too.

This provides 2 benefits, reducing the need to build unneeded files and prevent clogging the screen by running file without tests matching the filter.

**Notes**

I would like to take on this issue if the complexity is not high or if there are people willing to mentor.

**Comment by alexcrichton** [comment]
Thanks for the report, but `cargo test part_a` does not mean, to Cargo, "run the `part_a` test" but it instead means "pass `part_a` to all test executables as an argument". To run only one test you can use `--test part_a`, and then Cargo won't build the other targets.

**Comment by pickfire** [comment]
Ah, I did not know `cargo --test part_a` exists, I believe it would be nice to add an example for that. Yes, all my functions are prefixed with `part_a`, so `cargo test part_a` should work.

**Comment by ehuss** [comment]
I think this is already documented in the `cargo test` man page.  There is an example for exactly this case at the bottom of https://doc.rust-lang.org/cargo/commands/cargo-test.html.  However, I think it would be reasonable to emphasize how target selection works at the top where it introduces test filtering.

**Comment by pickfire** [comment]
Ah, I just realized it is documented in `cargo test` man page, I rarely read `cargo` man pages since it is more troublesome to read it, like I need to `rustup man cargo-test` rather than just `alt-h` in fish to show the man page since it is not in the `MANPATH`, so usually I just `rustup test --help`. Should we add rustup man pages to the `MANPATH` during installation?

**Comment by icorbrey** [comment]
Mind if I take a stab at this? I haven't been able to contribute to an OSS project before so I'm trying to find ways to help out. It looks like I should be able to add specific wording in `src/doc/man/cargo-test.adoc` to emphasize the usage of `--test`

**Comment by pickfire** [comment]
@icorbrey Yes, definitely. It would be good to make the wordings simpler and clearer. One thing I like is https://github.com/Dhghomon/easy_rust

**Comment by icorbrey** [comment]
I think that adding the rust manuals to the `MANPATH` would be good, but that's probably outside the scope of this issue lol
