### ISSUE TITLE
CARGO_TARGET_<triple>_LINKER environment variable is ignored during build

### ISSUE THREAD

**Issue by smacintyre** [rust-lang/cargo#8285]
## Problem

Setting the `CARGO_TARGET_<triple>_LINKER` [environment variable](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinker) has no affect on `cargo build`. 

I am targeting `x86_64-unknown-linux-musl` and I need to be able to build on both macOS (for development) and Linux (for CI). The linker is named differently on the two platforms: `x86_64-linux-musl-gcc` on macOS and `musl-gcc` on Linux (which is the what `rustc` expects by default). I would like to be able to the CARGO_TARGET_<triple>_LINKER environment variable to override the default on macOS only.

## Steps (macOS)

1. `rustup default stable` (fails for nightly too)
1. `rustup target add x86_64-unknown-linux-musl`
2. `brew install filosottile/musl-cross/musl-cross`
3. `cargo new envtest`
3. `cd envtest`
3. `export CARGO_TARGET_x86_64_unknown_linux_musl_LINKER=x86_64-linux-musl-gcc`
3. `cargo build --target x86_64-unknown-linux-musl`

**Result**: `error: linking with ``cc`` failed: exit code: 1`

**Expected Result**: a binary linked with x86_64-linux-musl-gcc

## Suggested Fix

Rather than just being able to specify target specific configurations in `.cargo/config`, it would be nice to be able to specify configurations by target and host combinations. 

For example I want this rule to only apply when building for the musl target on macOS:
```toml
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
```
If narrow this rule by host would be amazing. Something like:
```toml
[target.x86_64-unknown-linux-musl.cfg(host_os = "macos")]
linker = "x86_64-linux-musl-gcc"
```

That said, being able to use the `CARGO_TARGET_<triple>_LINKER` environment variable is more than enough for my needs. Thank you.

## Notes

Output of `cargo version`: cargo 1.43.0 (2cbe9048e 2020-05-03)

Release channels tested:
- stable-x86_64-apple-darwin unchanged - rustc 1.43.1 (8d69840ab 2020-05-04)
- nightly-x86_64-apple-darwin unchanged - rustc 1.45.0-nightly (a74d1862d 2020-05-14)

OSes tested on: 
- macOS Catalina 10.15.5 Beta (19F83c)
- debian buster -- from the official [rust:latest](https://hub.docker.com/_/rust) docker image

**Comment by petrochenkov** [comment]
The triple has to be uppercased - `CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER`.

(This is still a documentation issue.)

**Comment by smacintyre** [comment]
Thank you! It works! Yes, an example in the docs would be enough to make it clear. I spent a lot of time trying to get it working.

**Comment by joshtriplett** [comment]
We discussed this issue in the Cargo meeting today. In addition to updating the documentation, we also think it'd be a good idea for cargo to detect environment variables that start with `CARGO_TARGET_` and end with `_LINKER` (or any other target-specific environment variable pattern), where the target in the middle isn't uppercase with underscores, and warn that it's ignored.

**Comment by phamhm** [comment]
I'd like to work on this.

**Comment by Liberatys** [comment]
It seems like this issue has been sitting here for some time :D I'd like to pick it up it that is okay?

**Comment by ehuss** [comment]
@Liberatys Feel free to take a crack at it.  There are some notes [here](https://github.com/rust-lang/cargo/pull/8313#issuecomment-651364202) about how to approach this.  The environment is already captured [here](https://github.com/rust-lang/cargo/blob/b842849732f89df8675eb2d933c384d6338e4466/src/cargo/util/config/mod.rs#L204-L212), so I think it would just need to add a case-insensitive hashset of environment keys, and check those.

**Comment by pronebird** [comment]
It does not seem that there are any warnings when for instance when providing `RUSTFLAGS_aarch64-apple-ios=..`. In fact it seems to work on my Intel Mac but it doesn't work on m3 macbook.
