### ISSUE TITLE
name conflict `cargo-update` 

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/cargo#8288]
The command `cargo-update` has a name conflict with another project.
https://github.com/nabijaczleweli/cargo-update

In the Cargo Book there is a command with the same name:
https://doc.rust-lang.org/cargo/commands/cargo-update.html

But they do different things:
1. cargo-update - Update dependencies as recorded in the local lock file

2. A cargo subcommand for checking and applying updates to installed executables

This is a confusing name conflict.
In neither of this 2 names is clear what is actually being updated?
"Cargo" is not being updated by any of these, to be clear.
One could be `update_ installed_executables`
The other `update_cargo_toml_dependencies`

**Comment by Eh2406** [comment]
Yes it is confusing. We have no control over the name of @nabijaczleweli's project. The built in command is stable and subject to the stability guarantees. So I don't know what we can do about the confusion.

**Comment by sfackler** [comment]
That third-party subcommand is invoked as `cargo install-update`, not `cargo update`. There's no naming conflict there: https://github.com/nabijaczleweli/cargo-update#usage.

**Comment by nabijaczleweli** [comment]
That's also the explanation I gave when closing this very same issue in the supposedly conflicting repository: https://github.com/nabijaczleweli/cargo-update/issues/133

NB: `cargo-install-update[-config]` is also stable and will remain so :Р

**Comment by ehuss** [comment]
I'm going to close this as it doesn't seem there is anything to do here.
