### ISSUE TITLE
NEW CARGO SWITCHES "--fetch-merge-requests" and "--send-mass-merge-requests"

### ISSUE THREAD

**Issue by omac777** [rust-lang/cargo#8292]
Not to focus on redox-os code base, but the pattern of it could be elsewhere.  So there are capabilities specific to different os/hardware targets wanting to be tweaked in all crates. THAT'S THE PATTERN.

It has surfaced before as a painpoint in go and rust, but crystallized for me with the above. NO TOOL seems to adequately deal with this BROAD REFACTORING PATTERN.  Patch files are for small cases in small projects here and there.  What I am identifying is breadth of change is possible and to integrate something broad quickly is the goal. Resorting to change/merge requests on a per-project/crate basis depends on the reaction time of each project/crate maintainer to approve/merge into their project.  The only way to circumvent the delay is to clearly clone/fork each of these projects/crates locally and apply changes locally and continue to maintain those changes locally.

AS AN EXAMPLE OF PAIN
NOTE:  This is intended as a constructive criticism towards redox or its dependent crates.io rust crates.  This is not to be taken personally by anyone involved in these.

redox-os rust code targetted to run on "unix"/linux could just reuse whatever "unix" has.
```
#[cfg(all(unix, not(target_os = "redox")))]
```

redox-os rust code targetted to run on redox-os as a separate set of code NOT currently existing cfg("unix") stuff
```
#[cfg(target_os = "redox")]
```

Code pattern like this needs to trickle down and be submitted in all existing crates.io crates
where redox-os wants to participate in terms of hardware targets and in terms of compatibility with other "unix" family OS targets.

WHERE THERE IS NO PAIN
I like "cargo build" fetching crates to .cargo/registry/src/github.com-1ecc6299db9ec823...it has been working when the crates are good and don't have to be changed. 
i.e. x86_64 LINUX

BUT NOW IN THIS REDOX ISN'T ENTIRELY UNIX FAMILY SCENARIO ALL CRATES' sources related to redox-os NEED TO BE CHANGED. It isn't just a couple, potentially all of them could be affected.  

Here is my change request: 
1. Preserve .git directories within cargo registry
make cargo build preserve the ".git" directories within all .cargo/registry/src/github.com-1ecc6299db9ec823 crates 

2. Empower developers somehow to "git diff" entire cargo registry crates in one shot

ANOTHER CARGO SWITCH "--send-mass-merge-requests"
3. Empower developers to somehow to submit cargo registry crates changes/merge-requests to all related git diffs related git projects "EN-MASSE" in one-shot.

Capabilities like the above would help the nightly-like changes to happen more quickly within each crate.  It would help all those wanting to keep up with nightly versions of crates where fixes have been applied.

ANOTHER CARGO SWITCH "--fetch-merge-requests"
A crazy nightly-like switch would allow you to try submitted merge-requests before they have been merged from the different crates, prevent developers to individually patch different dependant projects/crates.  Just grab merge-requests from master for all of them, unless another version is specified.  This would alleviate having to modify Cargo.toml files in each subproject to apply patches.

I understand "cargo" developers intentionally separate the tasks of pulling/merging from the build, but the fact of the matter is cargo pulls crates so the instance you fetch something you are affecting the build.  git no longer seems to be the right place for this kind of change request especially in the rust compiler build workflow implies fetching dependant packages if they don't exist locally.  Well my change request is ok fetch dependant packages, BUT include merge-request code too and optionally specify a version for specific crate if not master(latest version)(default).

The above follows the spirit of the "rustup update" getting all the goodness of nightly, but zealous for seeking fetching anyone's contributions with the assumption the code compiles and runs since it has been submitted.

**Comment by ehuss** [comment]
I don't think Cargo will include the entire git repository of dependencies.  It doesn't even know if a package necessarily has a git repository.  There are tools like my own [cargo-clone-crate](https://crates.io/crates/cargo-clone-crate) for fetching the repository for a crate.  I also don't think Cargo will have any built-in support for opening merge requests.  That would best be solved by a plugin.   Closing as I think this is best solved with external tools.
