### ISSUE TITLE
cargo update: repo updated twice

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/cargo#8293]
**Problem**
when running `cargo update` in the rustc or rls repo, it looks like the clippy repo inside the cache is updated twice. This seems redundant.
````
  Updating crates.io index
    Updating git repository `https://github.com/rust-lang/cargo`
    Updating git repository `https://github.com/rust-lang/rust-clippy`
    Updating git repository `https://github.com/rust-lang/rust-clippy`
      Adding addr2line v0.12.1
    Updating anyhow v1.0.28 -> v1.0.31
````

**Steps**

1. `cargo update`

**Possible Solution(s)**
Don't update the git repo two times back-to-back.

**Notes**

Output of `cargo version`:
`cargo 1.45.0-nightly (cb06cb269 2020-05-08)`

Note: It doesn't look like `cargo update -vvvvv` has any additional effect :/

**Comment by epage** [comment]
This looks to be a duplicate of #6921, closing in favor of that.  If there is something I missed, let us know!
