### ISSUE TITLE
Running Cargo install on a library crate with crate-type=["dylib"] should install .dll/.so

### ISSUE THREAD

**Issue by sldr** [rust-lang/cargo#8294]
Steps to reproduce
* cargo new --lib foo
* cd foo
* Add the following to Cargo.toml:
     [lib]
     crate-type=["dylib"]
* Add the following to lib.rs:
     pub fn foo() {}
* cargo install --path . --root C:\rustinstalls

The problem is that you have to manually copy over the foo.dll so that other rust packages that depend on foo can find the foo.dll. Another fix would be to copy the .dll when an install is done for the package that depends on it.

Thanks,
SLDR
(Stephen L. De Rudder)

Extra Info:
cargo 1.43.0 (2cbe9048e 2020-05-03)
rustc 1.43.1 (8d69840ab 2020-05-04)

**Comment by repi** [comment]
Related to #8317

**Comment by weihanglo** [comment]
I think this is largely the same as #8317, or the solution for one can help the other. Closing as more people were there in the discussion. Let us know if you think they are inherently different.
