### ISSUE TITLE
Possible typo in all `Cargo.lock`s

### ISSUE THREAD

**Issue by scOwez** [rust-lang/cargo#8300]
**Problem**
There is a possible typo included in all `Cargo.lock` files. When cargo generates a `Cargo.lock` file for you, there is the following comment above the content:

```toml
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
more_below_this_lock = "0.0.0"
```

It doesn't look like `@` prefixing `generated` has been used before in other repositories as an indicator so looks to be a typo.

**Steps**

1. Generate a `Cargo.lock` file using the cargo CLI

**Possible Solution(s)**

Remove the `@` from `@generated`

**Notes**

Output of `cargo version`:
```none
cargo 1.45.0-nightly (cb06cb269 2020-05-08)
```

Looks like this was made 17 months ago so a decent amount of recent cargo builds are affected (if this is indeed a typo).

**Comment by sfackler** [comment]
No, it is not a typo: https://github.com/rust-lang/cargo/issues/6180.

**Comment by scOwez** [comment]
Alright, good to know :)
