### ISSUE TITLE
Allow passing a registry index url directly to `cargo install`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/cargo#8318]
**Describe the problem you are trying to solve**
If a binary is published to an alternative registry then installing it requires first editing `.cargo/config` to add an alias for the alternative registry, then calling `cargo install foobar --registry alias` to install it.

**Describe the solution you'd like**
Be able to pass the index url directly to `cargo install`, some ideas on how to do so:

 * Add a new `--registry-index` flag that takes an index url instead of a registry alias (this matches with the undocumented(?) `dependencies.*.registry-index` config used in published crates).
 * Have a prefix like `--registry index:https://github.com/rust-lang/crates.io-index` to identify this is an index-url instead of a registry alias.
 * Autodetect that it is a url instead of an alias since aliases must be identifiers, so cannot contain `/` characters. (Though whether this is an index url or api url may be ambiguous).

The rationale for requiring global aliases was:

> A previous RFC proposed having the registry information completely defined within Cargo.toml rather than using .cargo/config. This requires repeating the same information multiple times for multiple projects, and encourages checking in credentials that might be needed to access the registries.

Neither of these apply to the `cargo install` usecase. The registry itself is already repeating the registry information multiple times in the `Cargo.toml` it stores so that the user doesn't have to, and this is a command invocation that won't be checked in anywhere. (And supporting transient calls like this does not preclude the user creating an alias for the registry if they're using it often).

**Comment by ehuss** [comment]
I think it would be fine to add the `--index` flag to `cargo install`.  That flag is available in other commands, and I think it would be good to be consistent across commands.

I'm going to mark this Easy, though I haven't looked to see exactly how difficult it will be. The install code is a little hairy, but I think the addition would go somewhere around [here](https://github.com/rust-lang/cargo/blob/0227f048fcb7c798026ede6cc20c92befc84c3a4/src/bin/cargo/commands/install.rs#L146-L150).  If anyone wants to work on this, feel free to ask any questions.

**Comment by kellda** [comment]
@ehuss I'm interested to add this flag. Is it better to add another `else if` where you mentioned or to directly include this in [AppExt::registry](https://github.com/rust-lang/cargo/blob/bf1a26d355f2b12230eeef37b1e8617d90d2db99/src/cargo/util/command_prelude.rs#L536-L554) ?

**Comment by ehuss** [comment]
Thanks @kellda!  Yea, I think it would just be another `else if`.

**Comment by kellda** [comment]
Is it possible to reuse part of ops::registry which is used by every command that accepts `--index` ?

https://github.com/rust-lang/cargo/blob/7274307af4eecd221c152ad9affd0a7eeaffab44/src/cargo/ops/registry.rs#L372-L382

If so I think it will need to be refactored to be accessible from `cargo install` code.
