### ISSUE TITLE
Windows hard-linked executables are modified in place

### ISSUE THREAD

**Issue by rogday** [rust-lang/cargo#8348]
**Problem**

As the title says, cargo overrides all executables in a build folder. Expected behavior: don't override unrelated executables.

**Steps**

1. Write any program and run 'cargo build/run [--release]'.
2. Locate compiled binary(assume its foo.exe) and calculate its checksum.
3. Rename the executable to something different(assume bar.exe).
4. Change your program a little bit to differentiate resulting binary and compile again.
5. Compare checksums of foo.exe and bar.exe - they are the same.

**Notes**

It doesn't work with third-party binary.

Output of `cargo version`:

cargo 1.45.0-nightly (9fcb8c1d2 2020-05-25)

**Comment by ehuss** [comment]
This is a consequence of Cargo using a hard link from the actual executable (in the `deps` directory) and the one in the output directory (`target/debug`).  On Windows, I believe link.exe does not remove the executable, but instead truncates and modifies it.  When you rename the executable, the hard link is preserved, so the modifications made by the linker show up in all hard-linked copies.

It might be possible to unlink the executable before running the build.  I'm uncertain what the consequences of that would be.
