### ISSUE TITLE
cargo build fails with git dependency in rust 1.44

### ISSUE THREAD

**Issue by Roguelazer** [rust-lang/cargo#8352]
**Problem**
Since Rust 1.44, cloning git dependencies fails the first time with an error like the following:

```
$ cargo build
    Updating git repository `ssh://git@internal-server/path/to/git-repo.git`
error: failed to get `internal-lib-name` as a dependency of package `internal_project v0.1.0 (/Users/jbrown/work/easypost/internal-project)`

Caused by:
  failed to load source for dependency `internal-lib-name`

Caused by:
  Unable to update ssh://git@internal-server/path/to/git-repo.git?tag=v0.1.0#f582cac3

Caused by:
  failed to clone into: /Users/jbrown/.cargo/git/db/internal-lib-name-835eff812df18c1c

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  failed to map '1'; class=Config (7)
```

Rerunning `cargo build` a second time always succeeds.

This worked fine in 1.43.

**Steps**
1. Attempt to build a repo with a git dependency

**Possible Solution(s)**
Working on trying to make a minimal reproducer; figured I'd file this first.

**Notes**

Output of `cargo version`: `cargo 1.44.0 (05d080faa 2020-05-06)` (repros on macOS and Linux)

**Comment by Roguelazer** [comment]
Here's a minimal reproducer using one of the open-source libraries I maintain:

```
$ cargo new --bin issue-8352-test
     Created binary (application) `issue-8352-test` package
$ cd issue-8352-test
$ cat >Cargo.toml <<EOF
[package]
name = "i8352test"
version = "0.1.0"
authors = ["James Brown <jbrown@easypost.com>"]

[dependencies]
mysql_binlog = { git = "ssh://git@github.com/EasyPost/rust-mysql-binlog", tag = "0.3.0", version = "0.3.0"}
EOF
$ cargo build
    Updating git repository `ssh://git@github.com/EasyPost/rust-mysql-binlog`
error: failed to get `mysql_binlog` as a dependency of package `i8352test v0.1.0 (/Users/jbrown/tmp/2020-06-11/issue-8352-test)`

Caused by:
  failed to load source for dependency `mysql_binlog`

Caused by:
  Unable to update ssh://git@github.com/EasyPost/rust-mysql-binlog?tag=0.3.0

Caused by:
  failed to fetch into /Users/jbrown/.cargo/git/db/rust-mysql-binlog-e9f9b299f3d76a53

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  failed to map '1'; class=Config (7)
```

**Comment by ehuss** [comment]
`failed to map` indicates the git library failed to parse your `.gitconfig`.  Can you narrow down which part of your `.gitconfig` is causing the error and post it here?

Also, FYI, your reproduction has a small mistake (the tag needs `v` as in `tag = "v0.3.0"`).

**Comment by Roguelazer** [comment]
It appears to be
```
[core]
    logAllRefUpdates = 1
```
which causes the issue

Perhaps your gitconfig parser does not handle `1` as an alias for `true`?

**Comment by ehuss** [comment]
Yea, looks like an issue in the libgit2 library. I have filed a report at https://github.com/libgit2/libgit2/issues/5555.  A workaround is to use `true`.

I'm not yet sure why running twice works. For some reason, the second run thinks the repo is up-to-date.  Perhaps the error happens late enough that the repo is partially updated.  It will take some more investigation to figure that out.

**Comment by njerschow** [comment]
`git clean -f` fixed this for me

**Comment by JuiceDrinker** [comment]
If you ran into this and can clone using git cli adding --config net.git-fetch-with-cli=true to the end of your cargo command will fix it for you
