### ISSUE TITLE
cargo tree character encoding problem

### ISSUE THREAD

**Issue by alilleybrinker** [rust-lang/cargo#8369]
**Problem**

When running `cargo tree` (Cargo version 1.44.0) in Git Bash on Windows 10, I get output that looks like the following (snippet of actual output):

```
Γö£ΓöÇΓöÇ anyhow v1.0.30
Γö£ΓöÇΓöÇ chrono v0.4.11
Γöé   Γö£ΓöÇΓöÇ num-integer v0.1.42
Γöé   Γöé   ΓööΓöÇΓöÇ num-traits v0.2.11
Γöé   Γöé       [build-dependencies]
Γöé   Γöé       ΓööΓöÇΓöÇ autocfg v1.0.0
Γöé   Γöé   [build-dependencies]
Γöé   Γöé   ΓööΓöÇΓöÇ autocfg v1.0.0
Γöé   Γö£ΓöÇΓöÇ num-traits v0.2.11 (*)
Γöé   Γö£ΓöÇΓöÇ serde v1.0.110
```

**Steps**

1. Open Git Bash on Windows 10
2. Navigate to Rust crate
3. Run `cargo tree`

**Possible Solution(s)**

It certainly looks like a character encoding issue but I don't know enough to say more than that.

**Notes**

Output of `cargo version`: `cargo 1.44.0 (05d080faa 2020-05-06)`
Output of `rustc --version`: `rustc 1.44.0 (49cae5576 2020-06-01)`
Git Bash MinTTY version: `3.1.6 (x86_64-pc-msys)`

**Comment by ehuss** [comment]
This seems to be a recent regression in MinTTY.  See https://github.com/git-for-windows/git/issues/2648 and https://github.com/msys2/MSYS2-packages/issues/1974.  It looks like there might be some workarounds noted in those issues, or you can run `cargo tree --charset=ascii` for now.

**Comment by alilleybrinker** [comment]
Huh. Thanks for the explanation and workaround!

**Comment by dscho** [comment]
Seems that there is a work-around: `cmd //c chcp 65001`, but I think we have a good grasp on https://github.com/msys2/MSYS2-packages/issues/1974 and once that is resolved, this here bug will be fixed, too.
