### ISSUE TITLE
--target $host causes doctests to be silently ignored

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/cargo#8392]
**Problem**

`--target` causes doctests to be silently ignored even though `target` == `host`.

**Steps**

```bash
$ cargo new --lib doctesttest
$ cd doctesttest
$ echo $'/// ```\n/// invalid\n/// ```\npub fn abc() {}' > src/lib.rs
$ cargo test
# runs doctests and fails
$ cargo test --target x86_64-apple-darwin
# doesn't run doctests and succeeds
$ cargo test --target x86_64-apple-darwin -Zdoctest-xcompile
# runs doctests and fails
```

One other thing I noticed: doctests for proc-macro crates do seem to run.

**Possible Solution(s)**

Using `-Zdoctest-xcompile` works as a workaround but of course is unstable.

**Notes**

Output of `cargo version`:

```text
$ cargo -V
cargo 1.46.0-nightly (79c769c3d 2020-06-11)
$ rustc -Vv
rustc 1.46.0-nightly (f455e46ea 2020-06-20)
binary: rustc
commit-hash: f455e46eae1a227d735091091144601b467e1565
commit-date: 2020-06-20
host: x86_64-apple-darwin
release: 1.46.0-nightly
LLVM version: 10.0
```

**Comment by ehuss** [comment]
Thanks for the report! This will be fixed as soon as https://github.com/rust-lang/rust/pull/73415 merges.

**Comment by alecmocatta** [comment]
Oh I see, thanks! I couldn't see an issue for this (I didn't think to check PRs) so my inclination is to leave it open for anyone else looking? And I'll be sure to close once that PR merges and I've confirmed this is fixed.
