### ISSUE TITLE
Add filter to only run integration tests.

### ISSUE THREAD

**Issue by jschwe** [rust-lang/cargo#8396]
**Describe the problem you are trying to solve**

Currently `cargo test --tests` runs both unit and integration tests. Using `cargo test --lib` runs only the unit-tests of the library, however there is no way to only let the integration tests run, apart from maybe using a naming scheme for the integration tests, which I would like to avoid. It's also possible to write a script which calls `cargo test --test <name>` for each `.rs` file in the tests folder, but again, this is something I would like to avoid.

**Describe the solution you'd like**

I would like to run **only** the integration tests with e.g. `cargo test --integration_tests`. 

**Notes**

Looking into `libtest` the enum `TestType` seems to already provide the necessary information.

**Comment by leokhodel** [comment]
I'd like to take this, if no one else has started work on it. I read in the docs that integration tests are generally put in `tests`, would it be OK to add a flag `-i, --integration` that just runs the tests in that directory?

**Comment by ehuss** [comment]
I'm curious if either of you could state your motivation for this?  From my perspective, the unit tests are just another testable thing, so I'm uncertain why you would want to specifically exclude them.

As for a design/implementation perspective, I was wondering if maybe it would be better to add globbing to the target names instead of adding new flags?  Perhaps something like `--test '*'` or `--test client*`?

**Comment by jschwe** [comment]
The motivation in my case is kind of a "We probably shouldn't be doing it like this" situation. Historically the project I'm working on has unit-tests that are meant to be executed on the host system. I'm now working on integration tests and those target our target platform, so compiling both at the same time doesn't really work. 

Of course in the long run our unit-tests should also be able to run on our target platform, but that is currently not the case. `TestDesc` including information like `should_panic` is a `libtest` internal and thus not available on our target. As a quick-fix I'd like to be able to run unit-tests and integration tests separately, so that we can continue to use `libtest` features for the existing unit-tests until `TestDesc` is hopefully available outside of `libtest` one day.

Regarding globbing: I personally would like globbing to be available for `--test`, but in addition to a specific filter for integration tests, since I would like to avoid adding some prefix to every integration test file.

**Comment by ehuss** [comment]
> I would like to avoid adding some prefix to every integration test file.

With `--test '*'` you wouldn't need a prefix. That would match all integration tests.

**Comment by jschwe** [comment]
Ah, okay. The only thing that might be a bit confusing is that `--test '*'` would have different behavior compared to `--tests`, which is not that intuitive.

**Comment by ehuss** [comment]
I'm going to close this as fixed by #8752.  It now adds the syntax `--test '*'` which will select all integration tests. It should land on nightly within a few days.

**Comment by Integralist** [comment]
👋🏻 probably a silly question but re:

> With `--test '*'` you wouldn't need a prefix. That would match all integration tests.

Why does that only match integration tests? I expect the glob to match _every_ test (unit _and_ integration).

**Comment by jschwe** [comment]
@Integralist Because `--test` is [documented as](https://doc.rust-lang.org/cargo/commands/cargo-test.html): 

> Test the specified integration test. This flag may be specified multiple times and supports common Unix glob patterns.

`--tests` on the other hand does also include unittests.

**Comment by CyonAlexRDX** [comment]
How to do it in 2025?

```sh
$ cargo test --test '*'
error: no test target matches pattern `*`.
```

**Comment by weihanglo** [comment]
@CyonAlexRDX 

You need to have `[[test]]` targets in your packages. See https://doc.rust-lang.org/nightly/cargo/reference/cargo-targets.html#tests
