### ISSUE TITLE
`CARGO_MANIFEST_DIR` doesn't work as documented.

### ISSUE THREAD

**Issue by ldm0** [rust-lang/cargo#8397]
**Problem**
[Doc](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) says: 
> `CARGO_MANIFEST_DIR` — The directory containing the manifest for the package being built (the package containing the build script). Also note that this is the value of the current working directory of the build script when it starts.

However, from my recent development experience, `CARGO_MANIFEST_DIR` points to **the package being built** rather than **the package being built (the package containing the build script)**.

For example, a crate `foo` uses another crate `bar`, and the `bar` contains a build script which uses `CARGO_MANIFEST_DIR`. When compiling `foo`, the build script gets the path of `foo`'s manifest directory rather than `bar`'s.

---

### Edit:
The example below is wrong, the build script gets the path of `bar`'s manifest file.

**Comment by ehuss** [comment]
@ldm0 Can you show an example of what you are seeing?  It seems to work correctly for me:

```
cargo new --lib foo
cd foo
cargo new --lib bar
echo "bar = {path='bar'}" >> Cargo.toml
echo 'fn main() {println!("{:?}", std::env::var("CARGO_MANIFEST_DIR"));}' > build.rs
echo 'fn main() {println!("{:?}", std::env::var("CARGO_MANIFEST_DIR"));}' > bar/build.rs
cargo build -vv
```

Results in:

```
[bar 0.1.0] Ok("/Users/eric/foo/bar")
[foo 0.1.0] Ok("/Users/eric/foo")
```

Perhaps there is some confusion in the wording?  When package `bar` is being built, the `CARGO_MANIFEST_DIR` is `bar`'s directory.

**Comment by ldm0** [comment]
Oops, there is a sync issue in my project which causes the problem. The `CARGO_MANIFEST_DIR` is just      work as expect. I'm sorry for the wrong bug report.
