### ISSUE TITLE
Generate .gitignore for new packages within a repository

### ISSUE THREAD

**Issue by Flying-Toast** [rust-lang/cargo#8425]
This has already been discussed in #6357 and #7673 but not resolved.

When running `cargo new` inside an existing git repository, cargo does not create a .gitignore file. This means that the `target` directory will be tracked by git, unless the user manually creates the gitignore. As mentioned [here](https://github.com/rust-lang/cargo/pull/7673#issuecomment-562976400), this behavior is because of the possibility of the package being a member of a workspace.

Instead, in cases like these, cargo should default to generating the .gitignore, but give the option to *opt out* of creating it by passing `cargo new` an option such as `--workspace-member` or `--in-workspace`. IMO, this would be more correct since there are no circumstances where build artifacts should actually be tracked in VCS.

**Comment by ehuss** [comment]
Instead of opening a new issue, would you mind moving your comment to #6357? Or maybe I'm misunderstanding how this is different from #6357?
