### ISSUE TITLE
Why are the `Expression` word of lines 47 and 50 different?

### ISSUE THREAD

**Issue by xxxxzb** [rust-lang/cargo#8426]
https://github.com/rust-lang/cargo/blob/67075be62607d14d84ef858017e15f177b4b346d/crates/cargo-platform/src/error.rs#L47
https://github.com/rust-lang/cargo/blob/67075be62607d14d84ef858017e15f177b4b346d/crates/cargo-platform/src/error.rs#L50
Hi, I found a little problem, maybe picky.  
On line 47, the word ```Expression``` are abbreviated, but on line 50, there is no.  
: )

**Comment by ehuss** [comment]
I don't think there was a reason.  It would probably not be worth the hassle to rename it now, though, since it would be an API breaking change.

**Comment by xxxxzb** [comment]
Thank you for your answer.
