### ISSUE TITLE
cfg flags passed to the build script and active during the compile during `cargo doc` are inconsistent

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/cargo#8429]
**Problem**
When configuring cfg flags via `RUSTFLAGS` and `RUSTDOCFLAGS` while running `cargo doc` the flags which are passed to the build script and to the library itself are inconsistent. `RUSTFLAGS` is visiable in the build script, but not the library; `RUSTDOCFLAGS` applies to the library, but is not visible in the build script.

**Steps**
```rust
// build.rs
fn main() {
    eprintln!("CARGO_CFG_FOO = {:?}", std::env::var("CARGO_CFG_FOO"));
}
```

```rust
// src/main.rs
#[cfg(foo)]
/// Foo is active
pub fn main() {
}
#[cfg(not(foo))]
/// Foo is not active
pub fn main() {
}
```

```console
> RUSTDOCFLAGS='--cfg foo' cargo doc -vv |& grep CFG_FOO
[foo 0.1.0] CARGO_CFG_FOO = Err(NotPresent)

> rg -o 'Foo is [^<]*' target/doc/foo/index.html
2:Foo is active
```

```console
> RUSTFLAGS='--cfg foo' cargo doc -vv |& grep CFG_FOO
[foo 0.1.0] CARGO_CFG_FOO = Ok("")

> rg -o 'Foo is [^<]*' target/doc/foo/index.html
2:Foo is not active
```

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

**Comment by ehuss** [comment]
I think this is to be expected.  `RUSTDOCFLAGS` is only used when running `rustdoc`, and `RUSTFLAGS` is only used for `rustc`.

**Comment by ehuss** [comment]
Closing as expected per the explanation above.
