### ISSUE TITLE
`cargo test` color ignores both environment var and commandline arg

### ISSUE THREAD

**Issue by TheButlah** [rust-lang/cargo#8470]
**Problem**
`cargo test` appears to be ignoring both `CARGO_TERM_COLOR` and the `--color` option and always autodetecting color support. This means that if you want to force color on or off, it doesn't respect either the env var or the flag.

**Steps**

1. `cargo test --color never` produces color in a terminal (bug)
2. `CARGO_TERM_COLOR=never cargo test` produces color in a terminal (bug)
3. Same occurrs with the inverse - try the commands in CI (like gitlab) and try forcing on color - it doesn't work.

**Notes**

Output of `cargo version`:
`cargo 1.46.0-nightly (c26576f9a 2020-06-23)`

Note that this doesn't seem to apply to `check`, `build`, or `doc` - they all appear to work as intended. Note also that in the below screenshot (run with --color always in an environment that cargo detects as without color by default), the doc/build steps in `cargo test` have colored output, but the test status does not

![image](https://user-images.githubusercontent.com/6969415/86960104-05031a80-c12d-11ea-989a-d5c3610f18c5.png)

**Comment by ehuss** [comment]
If this is in reference to the color of the tests themselves, then I think this is issue #1983.  Libtest has its own set of flags that need to be passed separately.

**Comment by ehuss** [comment]
Closing as I believe this is essentially #1983.
