### ISSUE TITLE
Unexpected internal error when doing nightly build and then stable build

### ISSUE THREAD

**Issue by mtkennerly** [rust-lang/cargo#8472]
**Problem**

I had Rust stable 1.44.1 installed and working fine. I then added nightly and did a build with:

```

rustup toolchain install nightly --allow-downgrade
cargo +nightly run --release
```

which worked fine. Then I tried to build on stable again, and I got an error:

```
$ cargo run --release
error: dep-info invalid
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note: cargo 1.44.1 (88ba85757 2020-06-11)
```

However, `cargo run` (without `--release`) still works.

**Steps**

Method A:

1. `cargo clean`
2. `cargo run --release`
3. `cargo +nightly run --release`
4. `cargo run --release`

Method B:

1. `cargo clean`
2. `cargo +nightly run --release`
3. `cargo run --release`
4. `cargo +nightly run --release`
   * This invocation only showed incremental build output, whereas the other invocations resulted in full builds:
5. `cargo run --release`

**Possible Solution(s)**

Just a workaround, but `cargo clean` resolves the issue.

**Notes**

Output of `cargo version`:

```
cargo 1.44.1 (88ba85757 2020-06-11)
```

* OS: Windows 10
* Toolchains: stable-x86_64-pc-windows-msvc (default) and nightly-x86_64-pc-windows-msvc

**Comment by ehuss** [comment]
Thanks for the report!

This is essentially the same as #8298, though triggered by a different change (#8421).  The repro:
1. Create a project with dylib or cdylib crate type.
2. `cargo +nightly-2020-07-06 build`
3. `cargo +1.44.1 build`

I should have remembered that case during review, since I had just been looking at #8421.

**Comment by alexcrichton** [comment]
I've tried to fix this in https://github.com/rust-lang/cargo/pull/8473 by ensuring that the reason bin/rlib works works for dylib/cdylib as well.
