### ISSUE TITLE
[Feature request] Display bytes transferred when updating <crates.io> index

### ISSUE THREAD

**Issue by gendx** [rust-lang/cargo#8483]
**Describe the problem you are trying to solve**
When updating an index such as crates.io on a slow network connection (e.g. tethering from a mobile device), the "Fetch" step is often quite slow. In particular on a fresh install of Cargo this is often the slowest step.

For now, there is a progress bar showing a percentage of progress, such as the following.

```
      Fetch [============================>                          ]  53.00%
```

However, this percentage is quite opaque.

**Describe the solution you'd like**
It would be useful to also display:
1. how many bytes have been received,
1. how many bytes are remaining,
1. the current throughput.

**Notes**
I believe the relevant code that updates the progress bar is the following:
https://github.com/rust-lang/cargo/blob/f12d72e11b8643b4851a50325d77af962931fe98/src/cargo/sources/git/utils.rs#L693-L697

In particular, the relevant information (`stats`) seem to come from a callback from libgit2 ([git2::Progress](https://docs.rs/git2/0.13.6/git2/struct.Progress.html)). This struct already contains a `received_bytes()` which would provide information for (1). I'm not sure how to get the total/remaining bytes from libgit2, nor the throughput. But seeing how many bytes have been transferred would already be a great improvement.

**Comment by Eh2406** [comment]
That sounds reasonable to me!
