### ISSUE TITLE
while in test env, cargo failed to resolve package when the package is in dev-dependencies 

### ISSUE THREAD

**Issue by w93163red** [rust-lang/cargo#8484]
**Problem**
I put a package in dev-dependencies. However, when I compile it, the compiler complains that it failed to resolve the dependencies.
I have deployed this project on other computers, it works fine. And I have encountered this problem multiple times and did not have a clue on how to fix it.  
![图片](https://user-images.githubusercontent.com/7308728/87470110-4cd0e880-c5ea-11ea-9183-b3b7390a803c.png)
![图片](https://user-images.githubusercontent.com/7308728/87470729-324b3f00-c5eb-11ea-827f-30951c148a26.png)
![图片](https://user-images.githubusercontent.com/7308728/87470755-3c6d3d80-c5eb-11ea-967f-368e18fad918.png)

**Steps**
1. Please check the screenshot above
2. The cargo command is:
cargo test --no-run --features "sdk_test" -- --nocapture

**Notes**

Output of `cargo version`:cargo 1.45.0-nightly (258c89644 2020-04-30)

rust version: nightly-2020-05-07
OS: Debian 9
target toolchain: x86-64

**Comment by ehuss** [comment]
Is `use mocktopus` inside your library or binary? If so, is it in a `#[cfg(test)]` block?  dev-dependencies will only be built for tests, so when the `lib` is built as a normal library for other things (like executables or doctests), it will not be included.

**Comment by w93163red** [comment]
Thanks for the quick reply!
> Is `use mocktopus` inside your library or binary?
Yes.

>  If so, is it in a #[cfg(test)] block?
Yes

**Comment by w93163red** [comment]
The weird problem is that the same code can work on other machines, but not for this one..

**Comment by w93163red** [comment]
I am trying to build the unit test in this crate, so I think it should be built based on your explanation...

**Comment by ehuss** [comment]
Hm, I would try to narrow it down a little. `cargo test` builds a lot of stuff, so I would try a few different things:
* `cargo test --lib --features "sdk_test"`: This should build just the unit tests.  If this fails, run with `-v` and check if it is passing `--extern mocktopus`. If not, check if `mocktopus` is being properly registered in the dependency graph (look at `cargo tree` or inspect the `Cargo.lock` file).
* `cargo test --doc --features "sdk_test"`: This builds doc tests, which also requires building your library as a normal library. If this fails, then I would double check that you have the `cfg(test)` configured properly.

**Comment by w93163red** [comment]
Thanks for the hint! I will try it out and paste the result here.

**Comment by w93163red** [comment]
--lib can works.
