### ISSUE TITLE
Cargo tries to build dynamic libraries for Emscripten targets

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cargo#8496]
Given a crate with:

```toml
[lib]
crate-type = ["cdylib", "lib", "staticlib"]
```

```bash
cargo build --target wasm32-unknown-emscripten
```

invokes:

```bash
rustc … --crate-type cdylib --crate-type lib --crate-type staticlib --emit=dep-info,link --target wasm32-unknown-emscripten …
```

which causes:

> thread 'rustc' panicked at 'src/librustc_codegen_ssa/back/linker.rs:893: building dynamic library is unsupported on Emscripten', src/librustc_middle/util/bug.rs:37:26

This behavior makes it impossible to support WASM and native (not WASM) dynamic libraries in the same crate.

It would be helpful if Cargo knew that `wasm32-unknown-emscripten` doesn't support `cdylib`, and didn't try to build it.

Note that unsupported `cdylib` breaks builds that *don't* use the crate as a dynamic library, because Cargo seems to unconditionally build `cdylib` even when the crate is used as a regular dependency linked as `.rlib`.

**Comment by ehuss** [comment]
This seems to have been changed in 1.45 (it no longer errors via https://github.com/rust-lang/rust/pull/71804). Which version are you using?

This also sounds like a rustc issue (https://github.com/rust-lang/rust/issues/67782), not a cargo one.  Typically rustc ignores unsupported crate types ([here](https://github.com/rust-lang/rust/blob/c2dbebd3d4ad21e80ef4e7535dd1e868aaad7e50/src/librustc_interface/util.rs#L508-L516))

**Comment by kornelski** [comment]
Ah, I've had 1.44.1. Thanks for fixing this in negative amount of time!
