### ISSUE TITLE
Rename Cargo.lock

### ISSUE THREAD

**Issue by Koxiaet** [rust-lang/cargo#8498]
Cargo.lock as a name has a few problems:
1. It doesn't play well with tab completion (as reported before in #7603).
1. It is never edited by hand and yet it has a very user-friendly name which is similar to Cargo.toml (despite it being completely different from the user's perspective). This is potentially misleading.
1. It doesn't have the `.toml` extension despite being TOML (although this doesn't matter too much).

To solve this, I recommend adding support for another name as well as `Cargo.lock` that will solve the above three problems. `Cargo.lock` will continue to be supported forever, but the new name will take precedence and `cargo new` will use the new name.

This new name should start with `.`, to emphasize that it is only used by programs and not people. Doing this will also reduce clutter in root directories as it will be hidden or tucked away at the top. It should also not drastically change the name (e.g. adding `package`/`Lockfile` etc), so that existing Rustaceans won't be confused. Something like `.cargo.lock.toml`, `.Cargo.lock.toml` or `.cargo-lock.toml` would be ideal.

**Comment by joshtriplett** [comment]
With the benefit of hindsight, perhaps we would have used another name for the lockfile. (And in particular, we ideally would have used a name that ended in `.toml`.) But at this point, a transition would be a substantial amount of churn.

Also, I don't think we should use a hidden file for something that appears in every crate, affects the build of the crate, and will often be checked into version control. I could imagine using `cargo.lock.toml`, though.

Given the amount of churn this would entail, and the fact that for the foreseeable future we'd have two names rather than one, versus the amount of benefit this would provide, I don't think we should rename this file.

**Comment by Eh2406** [comment]
In addition we would need a plan for the transition. One that does not have different versions of Cargo successfully building the same project but using different lockfiles.

**Comment by Koxiaet** [comment]
> Also, I don't think we should use a hidden file for something that appears in every crate, affects the build of the crate, and will often be checked into version control.

I think a hidden file is appropriate, since at least from the user's perspective Cargo.lock is merely an implementation detail of Cargo. Most users will never even touch it, so it makes sense to hide it. If someone tries manually editing their Cargo.lock, having it be a dotfile lets them know what they're getting in to - something that you don't have to think about in 99% of cases.

I don't see what churn this would cause. Most external Cargo tools rely on the cargo crate and don't implement Cargo.lock finding themselves. No existing crates would have to change, and new crates wouldn't even notice the difference.

**Comment by Koxiaet** [comment]
> One that does not have different versions of Cargo successfully building the same project but using different lockfiles.

Crates that commit their Cargo.lock would have to stick to the old system for a while to support old Cargo versions. Maybe cargo new --bin would use the old Cargo.lock for a while until everyone has updated their Cargo.

**Comment by DerSaidin** [comment]
A third issue about the same thing: https://github.com/rust-lang/cargo/issues/8624

Would it be possible to change this with a rust edition, such as [2024](https://github.com/orgs/rust-lang/projects/30/views/1)?

**Comment by weihanglo** [comment]
See https://github.com/rust-lang/cargo/issues/5707#issuecomment-2231276362
 
There is no plan to support different filename now.
