### ISSUE TITLE
`cargo test` compiles twice

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/cargo#851]
Running `cargo test` compiles the code twice before running the compiled tester binary. This is obviously irritating to look at when there are a bunch of warnings and the like, and is also much slower.

**Comment by jimmycuadra** [comment]
I think this is a poor user experience. For quite a while I've been dealing with duplicate output from `cargo test` and assumed it was just a bug that was going to get fixed. Now that I've found this issue, I don't think it's at all obvious that the duplicate output is coming from attempting to run non-existent doctests. If there really isn't a way to disable running doctests when there are none, it'd be great if there were an obvious warning message (or some other form of easily discoverable documentation) that explains why the output shows up twice by default.

**Comment by SimonSapin** [comment]
@jimmycuadra You can add `doctest = false` in the `[lib]` section of your `Cargo.toml`. (Though I still wish Cargo would do better by default.)

**Comment by jimmycuadra** [comment]
Yes, that is what I did. It's just totally non-obvious that that's why you see double output by default.

**Comment by nixpulvis** [comment]
This is still painful FWIW, getting a lot of unused warnings, and double errors on failed compiles.

**Comment by jimmycuadra** [comment]
@alexcrichton I understand the technical reason why this happens now, but since it is still a confusing user experience (as noted by duplicates of this issue in various forms continuing to be opened), would you be amenable to either reopening this issue, or me opening a new issue specifically for discussion and tracking of possible ways to address user confusion about the output?

**Comment by alexcrichton** [comment]
@jimmycuadra that's tracked by #1854

**Comment by nathanaeljones** [comment]
`cargo test --lib` fixes this for me, but not `doctest = false` under `[lib]`. Using nightly- 2016-11-04. Is this expected or should `doctest=false` always eliminate duplicate output? 

(FWIW, I ignored duplicates for three months in hopes the "bug" would be fixed. If there's a pain points FAQ/wiki I'd be glad to contribute to it).

**Comment by alexcrichton** [comment]
@nathanaeljones do you have integration tests (`tests/*.rs`) or binaries? In that case `cargo test` would also have to build the library for those targets.

**Comment by nathanaeljones** [comment]
Yes, I do. That makes sense, thanks!

**Comment by a13xb** [comment]
I'd echo the user experience complaints. As a newcomer, the current behaviour (still the case as of 1.30) is extremely baffling. I don't think it should be considered "fixed".

**Comment by Syndog** [comment]
I'm adding my voice to the chorus with this.  Duplicate messages by default makes an extremely poor and unprofessional user experience.  Though a minor issue, the fact that it continues to be pointedly ignored after so many years (now 1.41.0) only exacerbates matters.  It reveals an administrative problem that doesn't speak well for Rust as a project.

**Comment by pauljherring** [comment]
Hello, from Jul 2020; 6 years later, and still a thing.

As with @lilith, `[lib]doctest = false` didn't work, `cargo test --lib` did.

**Comment by rsalmei** [comment]
How awful! Is it really the intended behavior?
The errors rust gives us are dense, we shouldn't have to try to interpret them twice! 

December 2020
stable-x86_64-apple-darwin (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

![image](https://user-images.githubusercontent.com/6652853/102006243-5330d100-3cfe-11eb-8b3a-3c8b47dce100.png)

**Comment by Iron-E** [comment]
Latest nightly here. This makes it pretty difficult to find unique errors that I need to fix in the middle of a refactor:

![cap](https://user-images.githubusercontent.com/36409591/103373639-60570980-4acd-11eb-9200-077bb85f2f8c.png)

Especially when I don't just want to test just by `--lib`, I really do want to test everything.

**Comment by nixpulvis** [comment]
@alexcrichton @SimonSapin I realize that this issue thread is kind of messy and apologize for that, but I do not feel like it should be considered closed. Would it be possible to reopen? or create a new issue without the mess for this bad user experience?

**Comment by ehuss** [comment]
@nixpulvis I don't think this should be reopened because due to the way Rust testing works, the library fundamentally needs to be built twice. However, we have been planning to add some kind of deduplicate support. I realize we never opened an issue to track that, so I have opened #9104.

**Comment by nixpulvis** [comment]
@ehuss awesome, thanks for doing that.
