### ISSUE TITLE
network timeout configuration doesn't always work

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#8516]
**Problem**
Cargo seems to mostly ignore the `http.timeout` configuration.

The problem is that [progress](https://github.com/rust-lang/cargo/blob/f84f3f8c630c75a1ec01b818ff469d3496228c6b/src/cargo/core/package.rs#L914) function that handles timeouts is not called when there is no network traffic. According to https://curl.haxx.se/libcurl/c/CURLOPT_PROGRESSFUNCTION.html, when using the multi interface the progress won't get called during idleness "unless you call the appropriate libcurl function that performs transfers" whatever that means.

**Steps**
1. Start a network transfer (`cargo fetch`).
2. Pull the network cord.
3. Wait.  Cargo's timeout will not match the value in `http.timeout`.  Typically it seems to time out after 2.5 minutes on Linux and macOS. Windows was a little more confusing (I couldn't really get a good reading).

**Possible Solution(s)**
Uncertain if there is some way to force libcurl to call the progress function with the multi interface?

**Notes**

`cargo 1.46.0-nightly (4f74d9b2a 2020-07-08)`

**Comment by alexcrichton** [comment]
Can you test to see if this diff fixes the issue for you?

```diff
diff --git a/src/cargo/core/package.rs b/src/cargo/core/package.rs
index 1187def1d..07d50041e 100644
--- a/src/cargo/core/package.rs
+++ b/src/cargo/core/package.rs
@@ -899,11 +899,9 @@ impl<'a, 'cfg> Downloads<'a, 'cfg> {
                 break Ok(pair);
             }
             assert!(!self.pending.is_empty());
-            let timeout = self
-                .set
-                .multi
-                .get_timeout()?
-                .unwrap_or_else(|| Duration::new(5, 0));
+            let min_timeout = Duration::new(1, 0);
+            let timeout = self.set.multi.get_timeout()?.unwrap_or(min_timeout);
+            let timeout = timeout.min(min_timeout);
             self.set
                 .multi
                 .wait(&mut [], timeout)
```
