### ISSUE TITLE
Cargo build failure : recipe for target 'cargo-x86_64-pc-windows-gnu' failed

### ISSUE THREAD

**Issue by 1sp** [rust-lang/cargo#852]
rustc :  0.13.0-nightly (e4ead7b03 2014-11-12 12:21:57 +0000)
Cargo : rev e6ec71a

Steps:
1. ./configure --enable-nightly && make

Output:
touch target/snapshot/bin/cargo.exe
"/usr/local/bin/rustc" -v
rustc 0.13.0-nightly (e4ead7b03 2014-11-12 12:21:57 +0000)
target/snapshot/bin/cargo.exe build --target x86_64-pc-windows-gnu
Unable to update https://github.com/alexcrichton/curl-rust?ref=build-cmd#c7a6c512

To learn more, run the command again with --verbose.
Makefile:77: recipe for target 'cargo-x86_64-pc-windows-gnu' failed
make: **\* [cargo-x86_64-pc-windows-gnu] Error 101

Addition info:
Running command "cargo build --target x86_64-pc-windows-gnu --release --verbose" gives following error  - 

Unable to update https://github.com/alexcrichton/curl-rust?ref=build-cmd#c7a6c512

Caused by:
  failed to update submodules

Caused by:
  [4] Reference 'refs/heads/master' not found

**Comment by MeRahulAhire** [comment]
Hi, I'm on a windows PC I want to know how do I compile for Linux and MacOS?
