### ISSUE TITLE
Collision error when running cargo outdated

### ISSUE THREAD

**Issue by OskarPersson** [rust-lang/cargo#8521]
**Problem**
When running `cargo outdated` with the dependencies described below, a collision error occurs. `cargo build`, `cargo update` and all other commands I've tested works as expected.

```
$ cargo outdated
error: failed to select a version for `redis-async`.
    ... required by package `actix-redis v0.8.2`
    ... which is depended on by `outdated-redis v0.1.0 (/var/folders/x6/y9my30zs0sgbv71fl1pp0p000000gn/T/cargo-outdatedAIRVg9)`
versions that meet the requirements `= 0.6.2` are: 0.6.2

all possible versions conflict with previously selected packages.

  previously selected package `redis-async v0.6.3`
    ... which is depended on by `outdated-redis v0.1.0 (/var/folders/x6/y9my30zs0sgbv71fl1pp0p000000gn/T/cargo-outdatedAIRVg9)`

failed to select a version for `redis-async` which could resolve this conflict
```

**Steps**
1. Create a new project (`cargo new outdated-redis`) and add the following dependencies to Cargo.toml:
```
actix-redis = "0.8.2"
redis-async = "0.6.2"
```

2. Run `cargo outdated`

**Notes**

Output of `cargo version`:
cargo 1.45.0 (744bd1fbb 2020-06-15)

Output of `rustc --version`
rustc 1.45.0 (5c1f21c3b 2020-07-13)

**Comment by Eh2406** [comment]
What should `cargo outdated` be outputting in this case? Is this a bug with Cargo or with [cargo-outdated](https://github.com/kbknapp/cargo-outdated)?

**Comment by OskarPersson** [comment]
Oops, i totally forgot that it was a separate project. This should probably be moved there.
