### ISSUE TITLE
`cargo test --no-run` doesn't appear to produce a binary

### ISSUE THREAD

**Issue by iostat** [rust-lang/cargo#8525]
**Problem**

Running `cargo test --no-run` doesn't seem to produce a binary in `target/debug` like it used to. While it does appear to "compile, but not run tests" as advertised, the output of this compilation is nowhere to be found. Previously, it could be found in `target/debug/crate_name-some_build_hash`

**Steps**

1. Clean your `target` directory
2. Run `cargo test --no-run`
3. Cargo will appear to build your test suite /somewhere/, but that somewhere isn't in `target/debug` like it used to be, nor is it anywhere immediately obvious within the `target/debug/build` subdirectories
4. Check `target/debug`, and find that there are no binaries to be found

**Possible Solution(s)**
Restoring the behavior where it would put the binary into `target/debug` would be ideal. However it may make more sense to have a separate `target/test` or something along those lines as well. Essentially, there appears to currently be no way to manually invoke a test binary so that test results can be parsed and stored in CI-friendly formats (e.g. JUnit as [cargo-suity](https://github.com/andoriyu/cargo-suity) does)

**Notes**

Output of `cargo version`:
`cargo 1.46.0-nightly (4f74d9b2a 2020-07-08)`
with `rustup toolchain nightly-2020-07-12`. This is confirmed to be happening on macOS 10.15.4 and Ubuntu 19.10

**Comment by iostat** [comment]
nb: this change might've been intentional, in which case, maybe treat it as a feature request?

**Comment by iostat** [comment]
on futher inspection, it appears to be emitted to `target/debug/deps/<crate_name>-<some_build_hash>` Maybe we can reframe this as a feature request to emit as `target/debug/<crate_name>-test` or something along those lines?

**Comment by ehuss** [comment]
For now, the intent is to use `--message-format=json` to get the path to the file to execute the tests.  I think the following issues match your feature request: #1924, #3670

**Comment by ehuss** [comment]
Closing as a duplicate per the comment above.
