### ISSUE TITLE
failed to get `futures` as a dependency of package `node-template v2.0.0-rc4 (/Users/nter/substrate-node-template/node)`

### ISSUE THREAD

**Issue by link202064** [rust-lang/cargo#8544]
nter@MacBook-Air ~ % cd substrate-node-template/
git checkout -b my-first-substrate-chain
cargo build --release
fatal: A branch named 'my-first-substrate-chain' already exists.
    Updating crates.io index
error: failed to get `futures` as a dependency of package `node-template v2.0.0-rc4 (/Users/nter/substrate-node-template/node)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  http parser error: stream ended at an unexpected time; class=Http (34)
nter@MacBook-Air substrate-node-template %

**Comment by link202064** [comment]
nter@MacBook-Air substrate-node-template % rustc --version
rustc 1.45.0 (5c1f21c3b 2020-07-13)
nter@MacBook-Air substrate-node-template % cargo --version
cargo 1.45.0 (744bd1fbb 2020-06-15)
nter@MacBook-Air substrate-node-template %

**Comment by alexcrichton** [comment]
This looks like it was possibly an intermittent network error. Does this consistently fail for you though?

**Comment by ehuss** [comment]
Without further information, I'm going to close this.  The relevant error will now trigger a retry (#8553), so if it is really a temporary connection interruption, Cargo 1.47 should be able to resolve it automatically.  If you run into the issue again, or have further information, feel free to reopen or file a new issue.
