### ISSUE TITLE
git-fetch-with-cli does not work with `store` credentials helper

### ISSUE THREAD

**Issue by Ploppz** [rust-lang/cargo#8548]
I'm trying to build my crate in a private CI with jenkins. It depends on a crate `common` that is hosted in our private git repository.
The idea is to use git 'store' credentials helper to read credentials from a file, and then to make Cargo use the git CLI so that the store credentials helper will be used.

In Cargo.toml: `common = {git = "https://scm.ourdomain.com/git/common.git", tag = "v0.3.0"}`

Jenkinsfile excerpt:
```
environment {
    CARGO_HOME = "${env.WORKSPACE}/.cargo"
    GIT_TERMINAL_PROMPT = 0
}
...
withCredentials([usernameColonPassword(credentialsId: 'jenkins', variable: 'USERPASS')]) {
    sh "mkdir -p $CARGO_HOME"
    sh "echo '[net]\ngit-fetch-with-cli = true' > $CARGO_HOME/config"
    sh "echo 'https://$USERPASS@scm.ourdomain.com' > ${env.WORKSPACE}/git-credentials"
    sh "git config credential.helper 'store --file ${env.WORKSPACE}/git-credentials'"
    sh "CARGO_HOME=$CARGO_HOME cargo build --release --bin worker"
    ...
}
```
Note: `$USERPASS` is of format `<username>:<password>`
Output:

```
    Updating crates.io index

    Updating git repository `https://scm.ourdomain.com/git/common.git`
error: failed to get `common` as a dependency of package `hci v0.6.0 (/home/jenkins/agent/workspace/git_hci_jenkins-test)`

Caused by:
  failed to load source for dependency `common`

Caused by:
  Unable to update https://scm.ourdomain.com/git/common.git?tag=v0.3.0

Caused by:
  failed to clone into: /home/jenkins/agent/workspace/git_hci_jenkins-test/.cargo/git/db/common-e100cf7443f6f326

Caused by:
  process didn't exit successfully: `git fetch --tags --force --update-head-ok 'https://scm.ourdomain.com/git/common.git' 'refs/heads/*:refs/heads/*'` (exit code: 128)
--- stderr
fatal: could not read Username for 'https://scm.ourdomain.com': terminal prompts disabled
```

I tried to reproduce this locally to make sure I control all variables. Here is what you can do to reproduce the issue:
* `git credential-cache exit` if you use that, or exit anything that would help git to get credentials
* `cargo init hey`
* add any private repository to dependencies in `Cargo.toml`
* `export GIT_TERMINAL_PROMPT=0`
* write your credentials in `./git-credentials`, like: `https://<username>:<password>@somedomain.com`
* `git config credential.helper 'store --file $(pwd)/git-credentials'`
* `mkdir .cargo; export CARGO_HOME="$(pwd)/.cargo"; echo '[net]\ngit-fetch-with-cli = true' > .cargo/config`
* `cargo c`

You should get a similar error as above.
Then copy the `git fetch` command it mentions, and it should succeed, which means that the git setup is fine and using the 'store' helper, but Cargo is not able to tap into that apparently.

**Comment by ehuss** [comment]
I think you'll need to find an authentication solution that does not require interactive password input. Git offers things like setting the `GIT_ASKPASS` environment variable to a program to fetch the password. Alternatively, I have usually seen the use of SSH keys for authentication instead of git-credentials. I do not know the intricacies of configuring git with jenkins, I would suggest asking on one of the user forums for help.

**Comment by Ploppz** [comment]
Alright, I can look into those options, thanks, but 
> I think you'll need to find an authentication solution that does not require interactive password input. 

What I'm doing does not require interactive password input at all, as can be seen if you do the manual steps yourself.
The bug I report is that this is not the case when using Cargo, which is wrong I believe.
It may seem as if it does not actually use the git CLI in the same way that we do manually, to name one possible cause.

**Comment by ehuss** [comment]
Hm, I tried your reproduction steps, but it seemed to work for me.  One observation, your steps mention using `git config credential.helper`, but that only updates the local git configuration by default.  Cargo runs the fetch within its home directory, so I don't think it will read that configuration. Setting it in the global git config might help.

**Comment by Ploppz** [comment]
Thanks a ton, that was it!

**Comment by varnit-shukla** [comment]
> Setting it in the global git config might help.
@Ploppz @ehuss  , I am facing the same issue when working with a private registry
Could you please specify what the above reference means? i.e, what changes did you have to make to your above Jenkinsfile/project directory to make it work?

**Comment by Ploppz** [comment]
We have changed the way we do it, but reading the comment above it seems like ehuss meant just add `--global` to git config command?

What we do right now is different. We use a groovy script in Jenkins. We have this code to set up credentials.

```
def generateNetrc() {
  // Generate .netrc file to let `git` authenticate with bitbucket
  scmlib.withGitAskPassCredentials('bitbucket', [retry: 3], {
    sh "echo machine <bitbucket url> login ${util.shellEscape(GIT_USER, true)} password ${util.shellEscape(GIT_PASS, true)} > ~/.netrc"
  })
}
```
And setting `CARGO_NET_GIT_FETCH_WITH_CLI=true`

This works well for us.
