### ISSUE TITLE
When building a workspace, cargo will report that multiple packages link to a native library when it should not.

### ISSUE THREAD

**Issue by 0xc0deface** [rust-lang/cargo#8550]
**Problem**

**Steps**
See test repo here for example.
https://github.com/0xc0deface/cargo_workspace_issue

1. Make a project with two libs, one (lib1) should depend on the other (lib2)
2. Make lib1 link a native library. i did this by adding the the diesel crate with the sqlite feature.
3. Make lib2 link the same native library, but only in its dev-dependencies. i did this using the sqlite crate with default-features off, then on for the dev-dependencies.

This will result in `cargo build` and `cargo test` not working due to 
```
error: multiple packages link to native library `sqlite3`, but a native library can be linked only once
```

however if you build and test the libs seperately you will not get any errors suggesting there is actually no problem, and the error message is incorrect.

**Possible Solution(s)**

**Notes**

Output of `cargo version`: `cargo 1.45.0 (744bd1fbb 2020-06-15)`

**Comment by 0xc0deface** [comment]
Cargo should be able to work this out itsely, however a workaround for this issue is to put this build.rs file in lib2:
```
fn main()
{
	pkg_config::Config::new().probe("sqlite3").unwrap();
	println!("cargo:rerun-if-changed=build.rs");
}
```

**Comment by ehuss** [comment]
Thanks for the report!  In this particular case, this is a consequence of feature unification.  Running with `-Zfeatures=all` breaks the restriction (#8088), though this is only because it is a post-resolver "links" check.

I'm consolidating `links` collisions in workspaces in #7880, so I am going to close in favor of that.
