### ISSUE TITLE
-Z build-std stopped working in 7/29 rust nightly

### ISSUE THREAD

**Issue by jdm** [rust-lang/cargo#8568]
[surfman's CI]() has the following using the nightly rustc compiler:
```
cd surfman
rustup component add rust-src --target=aarch64-uwp-windows-msvc
cargo build -Z build-std --verbose --target=aarch64-uwp-windows-msvc
```
This regressed on 7/29, according to https://travis-ci.com/github/servo/surfman/builds/177861097. It used to complete without issue, and now it gives this output:
```
error: failed to read `/home/travis/.rustup/toolchains/nightly-2020-07-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/Cargo.toml`

Caused by:

  No such file or directory (os error 2)

The command "cargo build -Z build-std --verbose --target=aarch64-uwp-windows-msvc" exited with 101.
```

**Comment by jdm** [comment]
This may be a regression in the rust-src bundle somehow. This affects the CI on all of Linux, macOS, and Windows.

**Comment by alexcrichton** [comment]
I believe this was already fixed in https://github.com/rust-lang/cargo/pull/8558/ and  rust-lang/rust was updated today in https://github.com/rust-lang/rust/pull/74923
