### ISSUE TITLE
Are multiple binaries fully supported?

### ISSUE THREAD

**Issue by hongliang5316** [rust-lang/cargo#8570]
I have a cargo project like this:
![image](https://user-images.githubusercontent.com/13626322/89015969-8758b600-d34a-11ea-9570-5672c8b32a19.png)

I know that `bin-a/main.rs` can access mod1's `pub struct` through `mod mod1`, but how does `mod1` access mod2's `pub struct`?

**Comment by ehuss** [comment]
`bin-a/main.rs` should have:

```rust
mod mod1;
mod mod2;
```

and inside `mod1.rs` to access something from `mod2` you can reference it via the path `crate::mod2::my_struct`.

Questions like these should be asked on one of the user forums (like https://users.rust-lang.org/).

**Comment by hongliang5316** [comment]
@ehuss 
Thanks for your answer!
