### ISSUE TITLE
"cargo fix --edition" claims no failure, but crate can not be built with edition = "2018"

### ISSUE THREAD

**Issue by strake** [rust-lang/cargo#8580]
**Problem**
I want to migrate the [containers](https://crates.io/crates/containers) crate to the 2018 edition. I do "cargo fix --edition" in the crate root, which emits no error message, then write 'edition = "2018"' in Cargo.toml, but building the crate so fails.

Wanted outcome: Crate can be built with edition = "2018".
Actual outcome: "cargo build" fails.

**Steps**

1. git clone https://github.com/strake/containers.rs
2. git checkout a0a3e5df95057a015e6935a13f3a4b893329f39e
3. cargo fix --edition
4. <write 'edition = "2018"' in Cargo.toml>
5. cargo build

**Possible Solution(s)**

**Notes**

Seems to be due to name conflicts between the `ptr` crate and `core::ptr`. I am not sure how to bestly disambiguate, but "cargo fix" should at least emit an error message and fail.

Output of `cargo version`:
cargo 1.45.0 (744bd1fbb 2020-06-15)

**Comment by ehuss** [comment]
Thanks for the report!  This is a known issue, tracked in https://github.com/rust-lang/rust/issues/53797.  For now you'll need to manually fix any remaining errors.
