### ISSUE TITLE
cargo should automatically enable an example's required features

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/cargo#8583]
**Describe the problem you are trying to solve**
If you attempt to run an example with a required feature that's not a default feature of the crate, cargo prints an error message.

**Describe the solution you'd like**
Instead, cargo should "do what I mean": just enable any additional required features for that example and then run the example.

**Notes**
A similar change can be made for test and bins.

cc @joshtriplett

**Comment by joshtriplett** [comment]
I think this would be reasonable, as long as Cargo printed a message saying that was what it was doing. For instance:
```
Example `abc` requires feature `xyz`; rebuilding crate with feature `xyz`...
```

**Comment by pksunkara** [comment]
Duplicate of #4663?

**Comment by Lokathor** [comment]
sure looks that way. closing.
