### ISSUE TITLE
Set an environment variable for an executable's name when building it

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/cargo#8590]
**Describe the problem you are trying to solve**
I would like executables (bin/example/etc) to know what name they have (according to `Cargo.toml`), but there's no appropriate environment variable for this.

**Describe the solution you'd like**
an additional env variable, similar to `CARGO_PKG_NAME`, something like `CARGO_EXECUTABLE_NAME`. Obviously this only applies if cargo is building an executable of some sort.

**Comment by ehuss** [comment]
Does [`CARGO_BIN_NAME`](https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) address what you need?

**Comment by Lokathor** [comment]
Ah, it does! but it's not listed here, https://doc.rust-lang.org/cargo/reference/environment-variables.html

So, I take it this is a nightly-only for now?

**Comment by ehuss** [comment]
It is in [1.46](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-146-2020-08-27).
