### ISSUE TITLE
A build dependency can force runtime features to be enabled in the final artifact

### ISSUE THREAD

**Issue by mwcampbell** [rust-lang/cargo#8592]
[Minimal repro test case](https://github.com/mwcampbell/cargo-forced-feature-repro)

In Cargo.toml, default_features is set to false for env_logger. But when you build the binary, env_logger has all features enabled anyway, as is evident from the binary size and the output of cargo-tree.

This is caused by the dependency on speech-dispatcher, which has an indirect build dependency on bindgen, which depends on env_logger with default features. This dependency forces env_logger in the final program to have default features even when built on a non-Linux platform (the dependency on speech-dispatcher is conditional). If you remove the dependency on speech-dispatcher, then the optional features of env_logger are disabled as expected.

Tested with Cargo 1.45.1 (f242df6ed 2020-07-22).

**Comment by ehuss** [comment]
This should already be implemented with the `-Zfeatures` option (see [docs](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#features) and #7915).

**Comment by mwcampbell** [comment]
Ah, sorry for the duplicate.
