### ISSUE TITLE
Cargo reports an issue with a super old Cargo.lock

### ISSUE THREAD

**Issue by thegatsbylofiexperience** [rust-lang/cargo#8594]
**Problem**
Cargo is failing to pull one of my private libraries. Once I deleted the Cargo.lock file. Everything worked again.

What happens: Cargo does not pull and compile a git dependency.

What Should happen: cargo should pull the git dependency and compile.

Error notes below:
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note: cargo 1.45.1 (f242df6ed 2020-07-22)

**Steps**
1. Update cargo to 1.45.1
2.  try to compile a repo from that has not been compiled for alteast a year.
3. fail horribly.

**Possible Solution(s)**
Removing Cargo.lock fixes the issue and allows compilation.
**Notes**

Output of `cargo version`:
cargo 1.45.1 (f242df6ed 2020-07-22)

**Comment by thegatsbylofiexperience** [comment]
Sadly I am not sure about when I last built this repo.

**Comment by ehuss** [comment]
Was there an error message?  It should start with "error:".

**Comment by thegatsbylofiexperience** [comment]
It was an error in regards to a pulling a git repo from my local git server. It did not give much information. I am sorry I have lost the build log as it was on my laptop.

**Comment by ehuss** [comment]
Unfortunately without the error message or more information, I don't think there is much we can do with this issue, so I'm going to close.  If you run into it again, please reopen with whatever additional information you can provide.
