### ISSUE TITLE
dylib and cdylib crate type support on musl target is needed.

### ISSUE THREAD

**Issue by sisungo** [rust-lang/cargo#8607]
**Describe the problem you are trying to solve**

To build a crate with type “cdylib” or “dylib” on x86_64-unknown-linux-musl target.

**Describe the solution you'd like**

Make cargo’s “cdylib” and “dylib” crate types usable on musl targets.

**Notes**

**Comment by ehuss** [comment]
I believe you can set `RUSTFLAGS="-C target-feature=-crt-static"` to build a dylib on musl. More information can be found at https://github.com/rust-lang/rust/issues/59302. Closing as this is more of a rustc issue.
