### ISSUE TITLE
Can't Scaffold A New Project With Name Beginning With Number?

### ISSUE THREAD

**Issue by JimLynchCodes** [rust-lang/cargo#8613]
**Problem**
Problem is that cargo gives an error "error: Package names starting with a digit cannot be used as a crate name" rather than creating a project with name beginning with number.

**Steps**

run this:
```
cargo new 1-hello-world
```

**Possible Solution(s)**

**Notes**

There is the additional output in the console, "use --name to override crate name", but I'm not really sure how to change my command to make it work. 🤔

Output of `cargo version`: cargo 1.42.0 (86334295e 2020-01-31)

**Comment by hbina** [comment]
I am not sure I understand this issue. `cargo` simply does not allow crates to have names starting with a digit. This is a reasonable restriction imo.

Or did I misunderstood you?

**Comment by JimLynchCodes** [comment]
@hbina "This is a reasonable restriction imo."

To me is seems like a completely unnecessary restriction. Folder names beginning with numbers are perfectly valid, and in this case I do want to create a folder name that begins with a number (mostly because they represent chapters and I want them to be ordered automatically by the file system).

Can we remove this digit check altogether? I don't see what purpose or benefit it serves.

**Comment by Eh2406** [comment]
This works if you want the folder to start with a number:
`cargo new 1-hello-world --name hello-world`
or
`cargo new hello-world && mv hello-world 1-hello-world`
The fact that the `name` field in `Cargo.toml` can not start with a digit is connected to the fact that in Rust identifiers can not start with a digit. That would be hard to change.

Now, I'd be excited for a PR that improved the error message to something like:
```
> cargo new 1-hello-world
error: Package names starting with a digit cannot be used as a crate name
did you mean "cargo new 1-hello-world --name hello-world"?
```
I don't know how hard that would be.

**Comment by lofiguy** [comment]
I know that it's been a long time @JimLynchCodes. However maybe someone encounter this problem again so the solution is:
```
$ cargo new hello-world
```

And you can simply change the directory's name:
```
$ mv hello-world/ 1-hello-world/
```

And after that operation if you go to project dir:
```
$ cd 1-hello-world/
```
You can simply run the project without any problems:
```
┌─(~/dev/rust//0-hello-world)
└─(12:01:55 on master ✭)──> cargo run                                                                                                                                                                                                                                  ──(Sun,Jun26)─┘
   Compiling hello-world v0.1.0 (/home/ax/dev/rust/book-1.58/by-example/0-hello-world)
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/hello-world
Hello, world!
```

*Important*:

You shouldn't change the `name` field in `Cargo.toml` for `1-hello-world`. The file should looks like this:
```yaml
[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
```

**Comment by Anynomouss** [comment]
@lofiguy Is your answer not unnecessary long and complex? 
The simple answer is that you can specify a project folder with a number, but not a crate name with a number using the  cargo --name option:

`cargo new 1-hello-world --name hello-world`

The above code will create a folder  _1-hello-world_ with a crate with the name _hello-world_

The code in the directory _1-hello-world_ can be run like any project using _cargo run_

**Comment by ydrea** [comment]
I am looking for the same thing, for the same reasons ;)
Have moticed that rustlings don't have an issue with that...
