### ISSUE TITLE
Cargo recompiles unchanged re-saved files

### ISSUE THREAD

**Issue by mattrossman** [rust-lang/cargo#8616]
**Problem**
Re-saving a file but not changing its contents causes cargo to recompile the project.

This doesn't follow what's written in the [Rust Programming Language book](https://doc.rust-lang.org/stable/book/ch01-03-hello-cargo.html):

> Cargo figured out that the files hadn’t changed, so it just ran the binary. If you had modified your source code, Cargo would have rebuilt the project before running

**Steps**

1. Create a new project and build it
```
cargo new hello
cd hello
cargo build
```
2. Open `main.rs` and re-save it, e.g. with `vim src/main.rs` and `:wq`
3. Run another `cargo build`

Cargo will show a "Compiling" phase before "Finished" as if the file had changed.

**Possible Solution(s)**
Not sure what the current implementation is but perhaps it's considering the timestamp at which files were modified?

**Notes**

Output of `cargo version`:
```
cargo 1.45.1 (f242df6ed 2020-07-22)
```

I am on WSL running Ubuntu 20.04.

**Comment by Eh2406** [comment]
Yes we use mtime the, adding a way to look at contents is tracked in https://github.com/rust-lang/cargo/issues/6529

**Comment by ehuss** [comment]
Closing as this is tracked in #6529, and fortunately someone is working on a solution at #8623.
