### ISSUE TITLE
Cargo can't execute process on Ubuntu 20.04

### ISSUE THREAD

**Issue by CupOfTea134** [rust-lang/cargo#8621]
**Problem**

Using `cargo run` on a new binary Cargo project with a new install of rustup / Cargo results in error message:
```
error: could not execute process `target/debug/<project name>` (never executed)
```

**Steps**

1. Install the minimal installation of Ubuntu.
2. Install cargo and rustup.
3. Create a new project using `cargo new`
4. Install build-essentials using `sudo apt install build-essentials`
5. `cargo run`

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo 1.45.1 (f242df6ed 2020-07-22)

Minimal installation of Ubuntu 20.04 with build-essentials, VS Code, rustup, Cargo. I am on rustc version 1.45.2

**Comment by ehuss** [comment]
Unfortunately Cargo is not showing the underlying error message (I posted a fix for that in #8627).

Can you try running the executable manually and see if it works?  That is, just execute `target/debug/foo`.

**Comment by CupOfTea134** [comment]
Well, I just created the project. Since I can't run the project, there is no executable.

**Comment by CupOfTea134** [comment]
Yes, it works. I reinstalled Ubuntu and the problem seemed to be fixed.

**Comment by ehuss** [comment]
Since it sounds like this is resolved, I'm going to close.
