### ISSUE TITLE
version-selection fails for workspace with native build-dependencies 

### ISSUE THREAD

**Issue by M1cha** [rust-lang/cargo#8636]
**Problem**
When there are multiple libraries in the workspace and each has their own build-dependencies cargo tries to select a version that fits all of them.
That ultimately fails when the dependencies use native libraries with different versions.
It's not necessary to resolve this on a workspace-level though because each crate using a build.rs will have it's own, separate build-time binary anyway.

**Steps**

1. `git clone https://github.com/M1cha/rust-bugs.git -b cargo_workspace_issue`
2. `cd cargo_workspace_issue`
3. `cargo build`

output:
```
    Updating crates.io index
error: failed to select a version for `clang-sys`.
    ... required by package `lib2 v0.1.0 (/home/m1cha/nbu/cargo-workspace-bug/lib2)`
versions that meet the requirements `^0.29.3` are: 0.29.3

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v1.0.0`
    ... which is depended on by `lib1 v0.1.0 (/home/m1cha/nbu/cargo-workspace-bug/lib1)`

failed to select a version for `clang-sys` which could resolve this conflict
```

**Possible Solution(s)**
Ignore other workspace-crate's build-dependencies during version selection.

Output of `cargo version`:
`cargo 1.45.1 (f242df6ed 2020-07-22)`

**Comment by ehuss** [comment]
Thanks for the report!  I'm going to consolidate issues about `links` collisions in workspaces in issue #7880, so I'm going to close this in favor of that.
