### ISSUE TITLE
`cargo install` should not delete the contents of `~/.config/<program>` by default

### ISSUE THREAD

**Issue by spencerkohan** [rust-lang/cargo#8642]
**Describe the problem you are trying to solve**

I'm building a CLI application which stores some configuration files in `~/.config/my_app`.  For development, it's convenient to occasionally reinstall the binary using `cargo install`.  The issue I am running into is that the configs get wiped every time I do this, meaning they have to be recreated.

I think it's actually not a good practice to silently delete user configurations without warning - it took me some time to understand this was actually when the config is being deleted.

**Describe the solution you'd like**

`cargo install` should leave the contents of `~/.config` if they exist, and there should be a `--clean` option to delete the configuration directory during install.

**Comment by ehuss** [comment]
`cargo install` does not modify anything outside of the $CARGO_HOME directory.  Perhaps use something like `strace` to find what is happening?

**Comment by ehuss** [comment]
I'm going to close, as I have not heard back from you in a while.  But if you are able to provide more information, feel free to reopen!
