### ISSUE TITLE
cargo rustc --workspace/--exclude

### ISSUE THREAD

**Issue by xd009642** [rust-lang/cargo#8651]
So I'm working on [tarpaulin](https://github.com/xd009642/tarpaulin), and I'm trying to solve an issue where linker flags of dependencies can conflict with the linker flags I need to set for code coverage, namely `-C link-dead-code` (conflict issue https://github.com/rust-lang/rust/issues/64685). It should also keep the target directory smaller by not having dead code for all the dependencies included and prevent rebuilds when working with tarpaulin making things faster. So that's the motivation.

Now my idea to solve this is using `cargo rustc` to just pass the flags to the crate only. However if the user is using workspaces and has multiple packages in their project all the packages need `link-dead-code` applied not just the one under test. But I get the feeling from the docs that this isn't how `cargo rustc` works? 

Providing `cargo rustc` works as I've grokked it, I was thinking that making the flags compatible with cargo build/test/etc and allowing it to operate on a whole workspace would be a solution. 

Also, I'll need this to work with `cargo test --bins/--examples/--doc/--lib/--benches/--tests` with the compiled artefacts and anything in the project workspace linked with dead code. But that's just a side note in case I'm wrong and there's a better solution for doing this either with `cargo rustc` or a different cargo command

**Comment by ehuss** [comment]
You are correct, `cargo rustc` only applies to the final artifact.

I would suggest looking at `RUSTC_WORKSPACE_WRAPPER` (see #8143), which is used for all workspace members. You could inject your own flags via that.

**Comment by xd009642** [comment]
Oh cool, so that's available on stable as well? Or does the tracking issue mean it's not yet on stable rust?

**Comment by ehuss** [comment]
It is not stable, it requires `-Zunstable-options`.

**Comment by xd009642** [comment]
So I'm part way through implementing this and I've got this as compiler output:

```
 -C link-dead-code --cfg=tarpaulin -C debuginfo=2  rustc --crate-name faktory ...
```

Is there a way to get the args to appear after `rustc`? I've had a perusal of the issue and associated PR and didn't spot anything. In the meantime I'm going to keep looking and adjust it so it should create this monstrosity:

```
rustc -C link-dead-code --cfg=tarpaulin -C debuginfo=2  --cfg=tarpaulin_rustc --crate-name faktory ...
```

**Comment by ehuss** [comment]
`RUSTC_WORKSPACE_WRAPPER` should point to an executable that replaces `rustc`.  It is passed the path to `rustc` and all its arguments, and you can just append to the argument list, and execute rustc (the first argument).  [Here](https://github.com/rust-lang/rust-clippy/blob/07c5e9edb5db8723b15573eb6ebe183fddbc5d33/src/main.rs#L151) is where `cargo clippy` uses `clippy-driver` as a wrapper.

Thinking about it some more, I can see that might be awkward for your use case since you can't pass in arguments via the environment variable, so you would need a dedicated executable for that.  I added a note to the tracking issue about that.

**Comment by ehuss** [comment]
I'm going to close, as I think this seems to be mostly addressed by `RUSTC_WORKSPACE_WRAPPER`.  Feel free to reopen if that is not the case, or if there is some feedback for that feature, please leave a comment on that tracking issue.
