### ISSUE TITLE
build::close_output occasionally fails on Rust CI

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/cargo#8665]
For example, recent failures:
* https://github.com/rust-lang-ci/rust/runs/1051208363:
* https://github.com/rust-lang-ci/rust/runs/1051857620

```
---- build::close_output stdout ----
thread 'build::close_output' panicked at 'lines differ:
   Compiling foo v0.1.0 (/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t216/foo)
error: Broken pipe (os error 32)
warning: build failed, waiting for other jobs to finish...
hello stderr!
error: build failed
', src/tools/cargo/tests/testsuite/build.rs:5043:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This might be related to changes to LineWriter backing stdout in the standard library. Previously, it used to ignore first encountered I/O error, now it should report it immediately.

**Comment by alexcrichton** [comment]
This was tweaked recently in https://github.com/rust-lang/cargo/pull/8587, can you see whether that PR was included in that failing CI run?

**Comment by tmiasko** [comment]
Yes, it is included already (based on line number from the error message `build.rs:5043:5`).

**Comment by tmiasko** [comment]
I can reproduce this locally, but only with recent rustc (not yet available from nightly). Pretty sure the issue has been exposed by recent changes mentioned earlier, since failures are now quite frequent.
