### ISSUE TITLE
`lto = true` causes build failure on macos

### ISSUE THREAD

**Issue by JAicewizard** [rust-lang/cargo#8673]
**Problem**
When adding `lto = true` to my project I end up with an LTO error from rust:
```
error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)

error: aborting due to previous error; 8 warnings emitted

error: could not compile `martens_martens_icons`.
```
This only happens on macos (building for macos), not on linux (windows not tested).

**Steps**

-
Very unclear, I added `lto = true` to the release profile and it failed to build on macos.
I am not sure what excect steps are needed for minimum reproduction, I can try to get this later.

**Possible Solution(s)**

**Notes**
Stable rust 1.46

**Comment by ehuss** [comment]
Can you provide any additional information, or perhaps a reproduction?  Or maybe narrow it down to a specific dependency?  From a fresh project (`cargo new foo`) can you build with lto?  Is it still a problem with 1.47?  Which version of macOS and Xcode?

**Comment by JAicewizard** [comment]
Sorry for the late reply, but I had some time today to recreate this in a minimal example.
[here](https://github.com/JAicewizard/cargo-ltotrue/runs/1203725887?check_suite_focus=true) is an example run failing on all channels right now. 

The only remaining part is the importing the crate as library, I am pretty sure its the library "crate_type".

**Comment by JAicewizard** [comment]
wow that was very fast!

**Comment by JAicewizard** [comment]
@ehuss 
I am getting a very similar issue to this, but it is extremely hard to reproduce.
Actually it is very easy, but it only happens in a single directory. Renaming the directory fixes it, naming it back introduces it again.
I want to file an issue about this, but with no reproducible case that is almost useless.<
Are you aware of any directory name specific things in cargo? I removed all but the bin folder in ~/.cargo but that doesnt fix it either.

Cargo.toml:
```
[package]
name = "example"
version = "0.1.2"
edition = "2018"

[lib]
name = "example_lib"
crate_type = ["lib"]

[profile.release]
lto = true
```

There is an empty library, and a binary. The binary just imports the library with `extern crate example_lib` and an empty main function.

```
$ rm ~/.cargo/registry # just in case
$ cd {dir_1}
$ cargo run --release --verbose # release is important, and see -Cembed-bitcode=no
   Compiling example v0.1.2 (/home/jaap/Projects/antipy/martens-martens-icons)
     Running `rustc --crate-name example_lib --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type dylib --crate-type lib --emit=dep-info,link -C opt-level=3 -Cembed-bitcode=no -C metadata=e44ce4df605df33c --out-dir /home/jaap/Projects/antipy/martens-martens-icons/target/release/deps -L dependency=/home/jaap/Projects/antipy/martens-martens-icons/target/release/deps`
     Running `rustc --crate-name gui --edition=2018 src/bin/gui/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=8a1a55ad9c000c64 -C extra-filename=-8a1a55ad9c000c64 --out-dir /home/jaap/Projects/antipy/martens-martens-icons/target/release/deps -L dependency=/home/jaap/Projects/antipy/martens-martens-icons/target/release/deps --extern example_lib=/home/jaap/Projects/antipy/martens-martens-icons/target/release/deps/libexample_lib.so --extern example_lib=/home/jaap/Projects/antipy/martens-martens-icons/target/release/deps/libexample_lib.rlib`
error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)

error: aborting due to previous error

error: could not compile `example`.

Caused by:
  process didn't exit successfully: `rustc --crate-name gui --edition=2018 src/bin/gui/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=8a1a55ad9c000c64 -C extra-filename=-8a1a55ad9c000c64 --out-dir /home/jaap/Projects/antipy/martens-martens-icons/target/release/deps -L dependency=/home/jaap/Projects/antipy/martens-martens-icons/target/release/deps --extern example_lib=/home/jaap/Projects/antipy/martens-martens-icons/target/release/deps/libexample_lib.so --extern example_lib=/home/jaap/Projects/antipy/martens-martens-icons/target/release/deps/libexample_lib.rlib` (exit code: 1)
$ cd ../
$ rm ~/.cargo/registry # just in case
$ mv {dir_1} {dir_2}
$ cd {dir_2}
$ cargo clean
$ cargo run --release --verbose # release is important, and see the lack of -Cembed-bitcode=no
   Compiling example v0.1.2 (/home/jaap/Projects/antipy/martens-martens-icons2)
     Running `rustc --crate-name example_lib --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type dylib --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=e44ce4df605df33c --out-dir /home/jaap/Projects/antipy/martens-martens-icons2/target/release/deps -L dependency=/home/jaap/Projects/antipy/martens-martens-icons2/target/release/deps`
     Running `rustc --crate-name gui --edition=2018 src/bin/gui/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=2f6f62c0556451fc -C extra-filename=-2f6f62c0556451fc --out-dir /home/jaap/Projects/antipy/martens-martens-icons2/target/release/deps -L dependency=/home/jaap/Projects/antipy/martens-martens-icons2/target/release/deps --extern example_lib=/home/jaap/Projects/antipy/martens-martens-icons2/target/release/deps/libexample_lib.so --extern example_lib=/home/jaap/Projects/antipy/martens-martens-icons2/target/release/deps/libexample_lib.rlib`
    Finished release [optimized] target(s) in 3.45s

```

**Comment by ehuss** [comment]
@JAicewizard Do you maybe have a rustup override switching which toolchain is used in the other directory?  `rustup override list` will show any directory overrides.  Maybe also check `rustc -V` prints the version you expect (should be at least 1.49).

**Comment by JAicewizard** [comment]
DAMMIT you got me, I am sorry for pinging you. I guess its one of the negatives of rustup, its so out of the way that you just forget about it. I thought I had covered all the global state by removing ~/.cargo. I guess I will remove this overwrite and forget they exist to avoid this in the future.

**Comment by eaglgenes101** [comment]
I ran into this same problem working on my own projects (rustc 1.52.0-nightly (9c09c1f7c 2021-02-26)). Moving the project's directory didn't help, though putting `rustflags = ["-C", "embed-bitcode"]` does resolve it.
