### ISSUE TITLE
SearchIndexer takes time indexing \target on windows

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/cargo#8694]
Windows Search Indexer can spend significant time interrupting project builds. This is mostly a problem on older computers with slower hard drives, but can be measurable on all systems. 
![image](https://user-images.githubusercontent.com/3709504/92660334-37193000-f2c8-11ea-9378-c6c4e8dfdee4.png)

Unchecking the "allow files in this folder to have contents indexed" seams to help. (on cmd `attrib +I target`) There may be other setting that can also help. Can Cargo programmatically check that flag when it crates `target`?

**Comment by weihanglo** [comment]
Is this in the same scope as #8684?

**Comment by weihanglo** [comment]
Looks like we get this issue on macOS too (#8684). Is there any chance to reuse some logic between OSs?

**Comment by Eh2406** [comment]
I was inspired to report this during discussion of #8684. It is conceptually related, but the implementation is likely to be more straightforward. Hopefully it can build on the code for https://github.com/rust-lang/cargo/blob/1857880b5124580c4aeb4e8bc5f1198f491d61b1/src/cargo/util/paths.rs#L529

**Comment by alexcrichton** [comment]
According to [`SetFileAttributes`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesa) the `FILE_ATTRIBUTE_NOT_CONTENT_INDEXED` may be useful here, but I think that would need to be tested if that affected folders. According to [this](https://sourcedaddy.com/windows-7/understanding-the-fanci-attribute.html), though, it may be what we want here.

**Comment by toothbrush7777777** [comment]
I'll work on this.
@rustbot claim

**Comment by pravic** [comment]
> The file *or directory* is not to be indexed by the content indexing service.

So, it should work with directories as well.
