### ISSUE TITLE
cargo yank's error message should be clearer

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/cargo#8695]
If you try to use `cargo yank` without passing the `--vers` flag, it errors with the message:

```
error: a version must be specified to yank
```

It would be helpful if this message specified that the version must be specified using the `--vers` flag. My prompt just now looks like:

```
> cargo yank
error: a version must be specified to yank
> cargo yank 0.7
error: a version must be specified to yank
> cargo yank 0.7.0
error: a version must be specified to yank
> cargo yank --help
...
> cargo yank --vers 0.7.0
```

**Comment by Eh2406** [comment]
Looks like the code is https://github.com/rust-lang/cargo/blob/868a1cf00a02cf29b75338dd283acb6acbddea4f/src/cargo/ops/registry.rs#L804 I'd love a PR with a better message!

**Comment by Mikastiv** [comment]
Could I do this as my first contribution?

**Comment by Mikastiv** [comment]
#8697 I changed the message in this PR
