### ISSUE TITLE
Beta cargo update failing with "object not found - no match for ID"

### ISSUE THREAD

**Issue by djmcgill** [rust-lang/cargo#8705]
```
> cargo update --verbose
    Updating crates.io index
error: failed to load source for a dependency on `base64`
Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  object not found - no match for id (bda449abf35bff2a6c0f3bc72e840f02bf054b2a); class=Odb (9); code=NotFound (-3)
```
This is on the latest beta:
```
> cargo -V
cargo 1.31.0-beta (efb7972a0 2018-10-24)
```
I've seen previous issues about cargo not correctly handling changed dependencies, could this be related? I'm going to zip my .cargo and .rustup, let me know if they'd be useful and what the best way to send them would be.

Platform is Windows 10's Debian WSL, i.e. unknown-linux-gnu

**Comment by ehuss** [comment]
Transferred to the cargo repository.  This sounds like #3561 has maybe returned?

**Comment by ehuss** [comment]
I think this is a duplicate of #4007, so closing in favor of that.

If any of you still have the problem, can you compress `~/.cargo/registry/index` and post it somewhere?  I think github supports up to 100mb zip files if you want to attach it here. I'd like to dig through and see if there is some way to reverse-engineer what has gone wrong.  (Feel free to post it here or #4007, I'll get it either way.)

**Comment by asayers** [comment]
I was getting this:

```
error: failed to get `anyhow` as a dependency of package [...]

Caused by:
  failed to load source for dependency `anyhow`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  object not found - no match for id (83dc7519562889d815343161b3bcd95e620e2efc); class=Odb (9); code=NotFound (-3)
```

Wiping $HOME/.cargo/registry fixed the issue.  Here's the contents of registry/anyhow*:

[bad-registry.tar.gz](https://github.com/rust-lang/cargo/files/5266065/bad-registry.tar.gz)

**Comment by ehuss** [comment]
@asayers Thanks for sending the snapshot. Unfortunately the part that is needed is the entire `.cargo/registry/index/github.com-1ecc6299db9ec823` directory.

**Comment by asayers** [comment]
Oh, sorry - it's already gone! :disappointed:
