### ISSUE TITLE
In workspaces, `cargo fmt` only works in the top-level directory

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#8724]
**Problem**

```
$ cargo fmt
Failed to find targets
cargo-fmt 1.4.18
This utility formats all bin and lib files of the current crate using rustfmt.

USAGE:
    cargo fmt [FLAGS] [OPTIONS] [-- <rustfmt-options>...]

FLAGS:
        --all        Format all packages (only usable in workspaces)
    -q, --quiet      No output printed to stdout
    -v, --verbose    Use verbose output
        --version    Print rustfmt version and exit

OPTIONS:
        --manifest-path <manifest-path>      Specify path to Cargo.toml
        --message-format <message-format>    Specify message-format: short|json|human
    -p, --package <package>...               Specify package to format (only usable in workspaces)

ARGS:
    <rustfmt-options>...    Options passed to rustfmt
```

**Steps**

1. `cargo new outer && cd outer`
2. `cargo new inner`
3. `printf '[workspace]\nmembers = ["inner"]' >> Cargo.toml`
4. `cd src`
5. `cargo fmt`

**Possible Solution(s)**

`cargo fmt` should format all packages in the workspace, like it does from the top-level directory.

**Notes**

Output of `cargo version`:

`cargo 1.48.0-nightly (875e01232 2020-09-08)` (but the problem also occurs on 1.46 stable)

**Comment by ehuss** [comment]
This seems like an issue for rustfmt. Can you move this to that issue tracker? https://github.com/rust-lang/rustfmt/issues

**Comment by jyn514** [comment]
I opened https://github.com/rust-lang/rustfmt/issues/4432
