### ISSUE TITLE
Update mdBook

### ISSUE THREAD

**Issue by camelid** [rust-lang/cargo#8726]
Currently on version 0.3.7 and the newest version is 0.4.3, so there _are_ breaking changes.

Relevant file:

https://github.com/rust-lang/cargo/blob/13b73cdaf76b2d9182515c9cf26a8f68342d08ef/.github/workflows/main.yml#L97-L100

**Comment by camelid** [comment]
Also, why are we not using `cargo install`?

**Comment by ehuss** [comment]
The version shouldn't matter, it is only used for linkchecking.  As for installation, downloading the binary is significantly faster.

**Comment by camelid** [comment]
> The version shouldn't matter, it is only used for linkchecking.

Ah okay, I didn't notice that.

> As for installation, downloading the binary is significantly faster.

Oops, I forgot that `cargo install` builds from source :)

**Comment by camelid** [comment]
Where is the book actually built for the website then?

**Comment by ehuss** [comment]
All the books are built in the rust-lang/rust repo as part of the normal build. The code is in [bootstrap](https://github.com/rust-lang/rust/blob/master/src/bootstrap/doc.rs), and can be built with commands like `x.py doc src/tools/cargo/src/doc` (though it is extremely rare anyone needs to do that manually).

**Comment by camelid** [comment]
Okay, thanks! I'll close this issue then and do it upstream.
