### ISSUE TITLE
cargo version throws not found error

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [rust-lang/cargo#8753]
**Problem**
`cargo install tarpaulin --version 0.14.3` throws the below error but version found here [https://docs.rs/crate/cargo-tarpaulin/0.14.3](https://docs.rs/crate/cargo-tarpaulin/0.14.3﻿)

```
error: could not find `tarpaulin` in registry `https://github.com/rust-lang/crates.io-index` with version `=0.14.3`
```

**Notes**

Output of `cargo version`:

`cargo 1.43.0 (2cbe9048e 2020-05-03)`

**Comment by ehuss** [comment]
[`tarpaulin`](https://crates.io/crates/tarpaulin) is a different package than [`cargo-tarpaulin`](https://crates.io/crates/cargo-tarpaulin).

**Comment by KarthikNedunchezhiyan** [comment]
Ahh thanks! my bad 🤣, will close this issue
