### ISSUE TITLE
LLVM pass with cargo

### ISSUE THREAD

**Issue by gladys95a** [rust-lang/cargo#8763]
Hi, would like to check how to do custom llvm passes in cargo, I am using the following command:
RUSTFLAGS="-C passes=my-custom-pass" cargo build

As expected, I got: warning: unknown pass `my-custom-pass`, ignoring

How do i load my customPass.so? TIA

**Comment by ehuss** [comment]
Cargo just passes flags to rustc, so I don't think this is really a cargo issue.  I'm not familiar with custom LLVM passes, but if it requires a custom LLVM, then you'll probably need to rebuild rustc with your custom LLVM.

Questions like these would probably be better to ask on one of the user forums like https://users.rust-lang.org/.
