### ISSUE TITLE
--features in workspace note not actionable

### ISSUE THREAD

**Issue by pickfire** [rust-lang/cargo#8770]
**Describe the problem you are trying to solve**

I am trying to use `--features` for one of the package in workspace but the reported error is not actionable.
```
error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything
```

**Describe the solution you'd like**

I haven't check how yet but the features, I guess one needs to search through github issue or stackoverflow to figure this.

**Notes**

Aside, the `note` text should be bold, `rustc` does but `cargo` does not.

**Comment by ehuss** [comment]
The `--features` flag only works in a package directory.

On nightly, you can use the [`-Z package-features`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#package-features) flag to use it in a workspace.

**Comment by pickfire** [comment]
Yeah, but what should an average joe do on stable? Do they need to edit the `Cargo.toml` in the package?

**Comment by ehuss** [comment]
You can `cd` into the package directory.

**Comment by pickfire** [comment]
Maybe we can add that as a suggestion?

**Comment by Xanewok** [comment]
I feel it's also worth mentioning the `--manifest-path` since it doesn't require changing the current dir, AIUI it also respects the rules around workspaces/parent manifests and such.
