### ISSUE TITLE
cargo-tree: A flag to get parent crates of a package id

### ISSUE THREAD

**Issue by lzutao** [rust-lang/cargo#8782]
**Describe the problem you are trying to solve**

I would like `cargo-tree` has a flag to *filter* parent crates of a package id.
The specifically use case of me is that I sometimes want to build
static binaries with crates has dependency on openssl.
I had to search in `cargo-tree | less` for parent crates of `openssl`/`openssl-sys`
crate and pass the feature flag respectively (i.e. `<parent>/vendor-openssl`).

**Describe the solution you'd like**

```console
% cargo tree -p openssl-sys --filter=parent
cargo-bisect-rustc v0.5.2 (/home/lzutao/fork/rust/official/bisect-rustc)
├── git2 v0.13.12
│   ├── libgit2-sys v0.12.14+1.1.0
│   │   └── openssl-sys v0.9.58 (*)
│   ├── openssl-sys v0.9.58 (*)
│   ├── hyper-tls v0.4.3
│   │   ├── native-tls v0.2.4
│   │   │   ├── openssl v0.10.30
│   │   │   │   └── openssl-sys v0.9.58 (*)
│   │   │   └── openssl-sys v0.9.58 (*)
```

**Notes**

---

I'm sorry if this is a duplicate of another or the team decide this is a wont-fix.
I'm OK and respect the cargo team decision.

**Comment by sfackler** [comment]
`cargo tree -i -p openssl-sys` is basically this, with the direction of the tree inverted.

**Comment by lzutao** [comment]
Great! Thank you. I don't see the neat to the flag any more.
But I have another question: How do we teach this ? Can we document this elsewhere ?

**Comment by ehuss** [comment]
Do you have suggestions on where else it could be documented? https://doc.rust-lang.org/cargo/commands/cargo-tree.html mentions `--invert` as the first option, and the "Examples" section shows how it can be used for a similar situation.

**Comment by lzutao** [comment]
Thank you. I don't look close enough. It is the 2nd example in the link you gave.

In the help menu of `cargo tree`, after `--invert` is a `<SPEC>`. 
Why does `cargo tree -i -p openssl-sys` work when there is no spec after `-i` ?

**Comment by ehuss** [comment]
>  Why does `cargo tree -i -p openssl-sys` work when there is no spec after `-i` ?

Backwards compatibility with the original `cargo tree`.

**Comment by lzutao** [comment]
Through I don't agree with keeping this feature compatibility with old cargo-tree,
my questions is answered. Thank you.
