### ISSUE TITLE
Cargo new fails with side effect when $USER env variable is not set

### ISSUE THREAD

**Issue by nixphix** [rust-lang/cargo#8783]
**Problem**
When running `cargo new foo` in the vscode built-in terminal it fails with error `$USER` env variable is not set but it does so after initializing the package repository `foo` so now I have repo created but it is not initialized

```zsh
└── foo
    ├── .git
    └── .gitignore
```

The expectation is if the command fails there should be no side effect, no folder or git repo created.

**Steps**

1. `unset USER`
2. `cargo new foo`
3.  `ls`

**Possible Solution(s)**
[discover_author](https://github.com/rust-lang/cargo/blob/2fbce89dd625bcd49ce7fd75f02d793ce0e1b658/src/cargo/ops/cargo_new.rs#L648) bails when `$USER` is not found, so it should be called before [init_vcs](https://github.com/rust-lang/cargo/blob/2fbce89dd625bcd49ce7fd75f02d793ce0e1b658/src/cargo/ops/cargo_new.rs#L645)

**Notes**

Output of `cargo version`:
`cargo 1.47.0 (f3c7e066a 2020-08-28)`

**Comment by ehuss** [comment]
I would also suggest that it could maybe query the operating system for the username. Or, it could just not fill out the `authors` field and print a warning or something.
