### ISSUE TITLE
Please support cargo update --offline

### ISSUE THREAD

**Issue by Silentdoer** [rust-lang/cargo#8785]
in offline working mode, i want update Cargo.lock file for rust analyzer's analysis, but not compile, so i want use cargo update --offline, but --offline can't work with update.

**Comment by Eh2406** [comment]
I find this surprising. In what way does --offline not work with update? Can you show the error you are getting?

**Comment by Silentdoer** [comment]
Hi, this is for offline dev env, I have copy .cargo to my offline machine, so when i create a cargo project and paste some dependencies, i want generate Cargo.lock file but not compile, so i need cargo update --offline.

**Comment by Eh2406** [comment]
What command are you running and what error messages are you getting?

**Comment by Silentdoer** [comment]
yes, this is my need, thank you
