### ISSUE TITLE
Allow usage of . (dot) character in package or library names.

### ISSUE THREAD

**Issue by nekitdev** [rust-lang/cargo#8787]
**Describe the problem you are trying to solve**
Currently, Cargo will not allow `.` to be used in package or library name:
```toml
[package]
# ... other fields are omitted
name = "package.rs"
```
Will cause an error:
```
invalid character `.` in package name: `package.rs`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
```

**Describe the solution you'd like**
Ideal solution will be to allow `.` in package or library names, which will pretty much require a simple change in [cargo::util::restricted_names](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/restricted_names.rs):
```rust
    for ch in chars {
        if !(unicode_xid::UnicodeXID::is_xid_continue(ch) || ch == '-') {  // || ch == '.' here
            bail!(
                "invalid character `{}` in {}: `{}`, \
                characters must be Unicode XID characters \
                (numbers, `-`, `_`, or most letters){}",  // `.` here
                ch,
                what,
                name,
                help
            );
        }
    }
```
And changed:
```rust
    for ch in chars {
        if !(unicode_xid::UnicodeXID::is_xid_continue(ch) || ch == '-' || ch == '.') {
            bail!(
                "invalid character `{}` in {}: `{}`, \
                characters must be Unicode XID characters \
                (numbers, `-`, `_`, `.` or most letters){}",
                ch,
                what,
                name,
                help
            );
        }
    }
```

**Notes**
I personally don't see any bad effects this small change might cause. `.` is a pretty much accepted character in many package managers and indexes, for example pip and PyPI in python.

**Comment by FireCubez** [comment]
Here's the problem with this. To include dependencies, you do this:
```toml
[dependencies]
winapi = "*"
```
To add features, you can use dots:
```toml
[dependencies]
winapi = "*"
winapi.features = ["winsock2"] # i think this is the syntax?
```

So, as you can see, there's the problem. `package.rs = "*"` would be something like `package = {rs = "*"}`

**Comment by nekitdev** [comment]
Interesting. I'll have a look at TOML specification - perhaps we can account for this issue.

**Comment by nekitdev** [comment]
Oh, forgot about it, haha. We can pretty easily solve this with:
```toml
[dependencies]
"package.rs".version = ">=x.y.z"
"package.rs".features = ["whatever"]
```

**Comment by Emerentius** [comment]
Dots are not accepted characters in identifiers either, so they'd have to be translated just like `-`.
The bigger issue here is that this request is lacking a motivation. Why would dots be worth all the work? "It could be done" is not one.

**Comment by nekitdev** [comment]
Translated? But yeah, indeed, this issue lacks motivation.
