### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by JonasVautherin** [rust-lang/cargo#8788]
**Problem**
When cross-compiling VLCKit for iOS (aarch64, though armv7 seems to work), I get the following error:

```
export TARGET_CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang && export TARGET_AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar && export TARGET_CFLAGS="-mios-version-min=9.0 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk -Werror=partial-availability -fno-stack-check -I/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0/include -g -O2" && export RUSTFLAGS="-C lto -C panic=abort -C opt-level=z" && export RUSTUP_USE_HYPER=1 && . /Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.cargo/env && RUSTUP_HOME=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.rustup CARGO_HOME=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.cargo cargo capi install --target=aarch64-apple-ios --prefix=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0 --library-type staticlib --release --locked --no-default-features --features=asm
Error: CliError { error: Some(failed to download from `https://crates.io/api/v1/crates/time/0.1.44/download`

Caused by:
    [1] Unsupported protocol (Protocol "https" not supported or disabled in libcurl)), exit_code: 101 }
```

As can be seen above, the command that fails is: `cargo capi install --target=aarch64-apple-ios --prefix=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0 --library-type staticlib --release --locked --no-default-features --features=asm`

**Steps**

1. Clone VLCKit (https://code.videolan.org/videolan/VLCKit)
2. Run the script: `./compileAndBuildVLCKit.sh -a aarch64 -v`. May need some patches as reported in [my report here](https://code.videolan.org/videolan/VLCKit/-/issues/437).
3. Observe that the error happens

**Notes**

Running on macOS Catalina 10.15.7

**Comment by ehuss** [comment]
This error doesn't seem to be coming directly from cargo.  It looks like you're running an extension (`cargo capi`). I can't find that extension via google or anywhere, so I don't know where it is coming from.  Can you create a reproduction that uses cargo directly?  If not, maybe try to find where `cargo capi` comes from and investigate with that project?

**Comment by JonasVautherin** [comment]
Right. I think I'm out of my depth here. I wanted to bring some new support to VLCKit, but that's also not a project I know. I'll see if I find what `capi`, but I suspect it comes from a dependency of a dependency of vlc, so it won't be easy to track :sweat_smile:.

Thanks a lot!

**Comment by JonasVautherin** [comment]
Ok, I'm back here, after having tried a patch by the author of the dependency (@lu_zero) that fails. It was about using `cargo-c --features curl-sys/static-curl`, but if fails with the following error:

```
  Downloaded cargo-c v0.6.16+cargo-0.45
  Downloaded 1 crate (25.4 KB) in 0.74s
  Installing cargo-c v0.6.16+cargo-0.45
error: failed to compile `cargo-c v0.6.16+cargo-0.45`, intermediate artifacts can be found at `/var/folders/path/to/artifacts`

Caused by:
  Package `cargo-c v0.6.16+cargo-0.45` does not have these features: `curl-sys`
```

@lu_zero says:

> It seems to pick a libcurl w/out https support, to force the libcurl binding to behave additional work is required in cargo itself =/

If somebody feels like having a look: https://code.videolan.org/videolan/VLCKit/-/issues/438
