### ISSUE TITLE
OUT_DIR is not defined during `cargo test`

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/cargo#879]
This makes it difficult to test libraries that depend on generated code.

**Comment by John-Nagle** [comment]
Did this fix make it into the pre-alpha versions?  I'm getting this error when trying to build the "rust-http" module, just downloaded from "https://github.com/chris-morgan/rust-http/archive/master.zip".

> cargo build
   Compiling http v0.1.0-pre (file:///home/john/projects/rustcode/rust-http)
   Compiling rustc-serialize v0.2.7
   Compiling gcc v0.1.4
   Compiling regex v0.1.10
   Compiling matches v0.1.2
   Compiling pkg-config v0.1.4
   Compiling time v0.1.12
   Compiling openssl-sys v0.2.15
   Compiling log v0.1.9
   Compiling openssl v0.2.15
   Compiling url v0.2.16
src/http/server/request.rs:127:21: 127:75 error: couldn't read /home/john/projects/rustcode/rust-http/target/build/http-2b9772103c3d8d3f/out/read_method.rs: IoError { kind: FileNotFound, desc: "couldn\'t open path as file", detail: Some("no such file or directory (No such file or directory); path=/home/john/projects/rustcode/rust-http/target/build/http-2b9772103c3d8d3f/out/read_method.rs; mode=open; access=read") }
src/http/server/request.rs:127         mod dummy { include!(concat!(env!("OUT_DIR"), "/read_method.rs")); }
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not compile `http`.
To learn more, run the command again with --verbose.

> cargo --version
cargo 0.0.1-pre-nightly (8c01b6b 2015-01-08 20:52:43 +0000)

**Comment by alexcrichton** [comment]
Yes this change should definitely be in that version of Cargo. Perhaps a local bug?

**Comment by John-Nagle** [comment]
It's a problem with the build script for "rust-http". Just for the record, rust-http has a program which generates "read_method.rs", but into the codegen directory, which is not OUT_DIR.  "rust-http" is now abandoned - ("OBSOLETION NOTICE...This library is DEAD...YOU SHOULD NOT USE THIS LIBRARY AT ALL.") So this will not be fixed. Switching to "Hyper" for HTTP use. Sigh.

**Comment by pbougue** [comment]
I think I'm having that same problem but using OUT_DIR just in tests:
```
#Cargo.toml

[package]
name = "foo"
version = "0.0.1"
authors = [ ]
```
```
//tests/tests.rs

#[test]
fn test() {
    println!(env!("OUT_DIR"));
}
```

Resulting in:
```
$ cargo --version
cargo 0.9.0-nightly (8fc3fd8 2016-02-29)
$ cargo test
   Compiling foo v0.0.1 (file:///~~~/dev/sources/foo)
tests/tests.rs:3:5: 3:31 error: environment variable `OUT_DIR` not defined
tests/tests.rs:3     println!(env!("OUT_DIR"));
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
error: Could not compile `foo`.

To learn more, run the command again with --verbose.
```

I have a workaround: adding a `build.rs`.
If I add a `build.rs` as follows, that works fine:
```
#Cargo.toml

[package]
name = "foo"
version = "0.0.1"
authors = [ ]
build = "build.rs"
```
```
//build.rs

fn main() { }
```

Resulting in:
```
$ cargo test
   Compiling foo v0.0.1 (file:///~~~/dev/sources/foo)
     Running target/debug/tests-695fd20f593eeffc

running 1 test
test test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
```

**Comment by alexcrichton** [comment]
@pbougue currently `OUT_DIR` is only defined if a build script is defined as well I believe

**Comment by pbougue** [comment]
Ok, we'll let it that way then!

**Comment by RReverser** [comment]
> currently OUT_DIR is only defined if a build script is defined as well I believe

Oh wow, that wasn't very obvious.
