### ISSUE TITLE
With libgit2, cargo is unable to update a custom registry behind a cross-domain redirect

### ISSUE THREAD

**Issue by tux3** [rust-lang/cargo#8815]
**Problem**

In my `~/.cargo/config.toml` I have a custom registry:

```toml
[registries]
custom = { index = "https://crates.myproject.org/crate-index/" }
```

This URL redirects to my actual crate-index repository, currently hosted at `https://gitlab.com/myproject/crate-index/`.

Trying to `cargo build` a project that uses a dependency from my registry (with all cargo settings to default) fails with:

```
    Updating `https://crates.myproject.org/crate-index/` index
warning: spurious network error (2 tries remaining): cannot redirect from 'crates.myproject.org' to 'gitlab.com'; class=Net (12)
warning: spurious network error (1 tries remaining): cannot redirect from 'crates.myproject.org' to 'gitlab.com'; class=Net (12)
error: failed to get `mydependency` as a dependency of package `mytestpackage v0.1.0 (/tmp/wherever/)`

Caused by:
  failed to load source for dependency `mydependency`

Caused by:
  Unable to update registry `http://crates.myproject.org/crate-index/`

Caused by:
  failed to fetch `http://crates.myproject.org/crate-index/`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  cannot redirect from 'crates.myproject.org' to 'gitlab.com'; class=Net (12)
```

This error seems to be caused by a hardcoded check in libgit2: https://github.com/libgit2/libgit2/blob/e316b0d3d64eb8f65f4109c1565d929b29e1d33a/src/net.c#L311-L317

When the git cli or the custom HTTP transport is used by cargo (non-default configuration), there is no error.  
This means that any `http` configuration option in the cargo config will make the error disappear,  due to enabling the custom transport: https://github.com/rust-lang/cargo/blob/master/src/bin/cargo/main.rs#L206-L209

Concretely, just `cargo build` will fail with the error shown above
`CARGO_HTTP_DEBUG=true cargo build` will work, because this uses the custom HTTP transport
`CARGO_HTTP_DEBUG=false cargo build` will work, because this *also uses* the custom HTTP transport

I want to say that setting an env var like CARGO_HTTP_DEBUG to its default value should not create or silence errors, so I'd argue that this is a bug in and of itself =)  
But more importantly I think cross-domain redirects should not fail in the default configuration. Unfortunately, because this behavior is hardcoded in libgit2, I'm not sure how to best fix it, but I've added a couple possibilities.

**Steps**

1. Redirect `crates.myproject.org/crate-index/*` to `gitlab.com/myproject/crate-index/*`
2. Setup the custom registry in Cargo config (e.g. ~/.cargo/config.toml)
3. Create a new test project with a dependency on a crate in the custom repository
4. Ensure that `net.git-fetch-with-cli` and `http` options are *NOT* set in Cargo config (so that libgit2 is used)
5. `cargo build` the test project, so that cargo will try to update the custom crate index

**Possible Solution(s)**

- Cargo could use the custom http transport by default
- Cargo could try to fallback to the custom http transport when libgit2 fails
- Cargo could try to resolve and apply cross-domain redirects before calling libgit2
- Cargo could use the git cli by default, when available
- This behavior could be fixed or made optional in libgit2: https://github.com/libgit2/libgit2/issues/5687

**Notes**

Output of `cargo version`: cargo 1.49.0-nightly (dd83ae55c 2020-10-20)

**Comment by alexcrichton** [comment]
Thanks for the very thorough bug report!

I've often thought that we should probably enable the Rust-curl backend for  libgit2 by default for data transfer to have a more consistent experience across platforms. I'm not actually sure if the backend has any outstanding issues, but it's good to know that it at least works for you in this case!

**Comment by tux3** [comment]
I believe this is now fixed by upstream =)
