### ISSUE TITLE
fingerprint.rs uses different target roots when serializing/deserializing

### ISSUE THREAD

**Issue by khyperia** [rust-lang/cargo#8817]
Originally found in https://github.com/EmbarkStudios/rust-gpu/issues/120, I'll use paths from my debugging there 

On this line of code, serializing the dep file, `target_root` == `/home/khyperia/me/rust-gpu/target`

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/fingerprint.rs#L1834-L1835

On this line of code, parsing the dep file, `target_root` == `/home/khyperia/me/rust-gpu/target/release`

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/fingerprint.rs#L1669

This causes extremely bizzare incorrect paths to show up in `target/spirv-unknown-unknown/release/example_shader.d`, for example, `/home/khyperia/me/rust-gpu/target/release/debug/deps/librustc_codegen_spirv.so` (note the `release/debug`)

---

I believe this is because when serializing, the root is taken from `cx.bcx.ws.target_dir().into_path_unlocked()`, which is the simple `target` dir.

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/mod.rs#L221

But when parsing the dep file, the root is taken from `cx.files().host_root()`, which is the specific target directory `target/release`.

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/output_depinfo.rs#L66

I think the only reason this hasn't been noticed before is that before https://github.com/rust-lang/rust/pull/77565, absolute paths converted to relative paths never went through the `TargetRootRelative` codepath, it was always kept as absolute paths. Maybe? I don't know.

---

I would submit a PR to fix this, but I don't know which path is correct to use here.

**Comment by alexcrichton** [comment]
Oh dear, thanks for the report and investigation here though! I believe the intention was to be relative to `target` itself, so anything that's actually relative to `target/{debug,release}` is a bug!

**Comment by khyperia** [comment]
Ah cool! Submitted a PR changing that one, then.
