### ISSUE TITLE
`cargo update --package X` updates other git repositories

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#8821]
**Problem**

`cargo update -p` should only update the specify package. Instead, it updates git repositories as well.

**Steps**

1. `git clone https://github.com/rust-lang/crater/`
2. `cd crater`
3. `git checkout dcc54566d5ec82cabca435c0145cbd06f32d3602`
4. `cargo update -p crater`

```
$ cargo update -p crater
    Updating crates.io index
    Updating git repository `https://github.com/rust-lang/team`
    Updating rust_team_data v1.0.0 (https://github.com/rust-lang/team#8d8902d7) -> #a3c474be
```

Output of `cargo version`: cargo 1.47.0 (f3c7e066a 2020-08-28)

**Comment by epage** [comment]
Git support is sort of hacked in and the resolver has to make a best guess as to when a git dependency should be updated or not.

**Comment by epage** [comment]
#12599 is similar in not wanting git updates to happen when `--workspace` is specified.
