### ISSUE TITLE
Command for generating acknowledgments

### ISSUE THREAD

**Issue by vhbit** [rust-lang/cargo#884]
There should be an automated way (either just as a build step or through a specific command) to generate  acknowledgments for all project dependencies in txt/markdown format like:

```
# rust-openssl

... text of LICENSE file from project root if it exists or contents of manifest's "license" field ...

# curl-rust

... text of LICENSE file from project root if it exists or contents of manifest's "license" field ...
```

**Comment by alexcrichton** [comment]
Currently Cargo isn't really in the business of managing licenses beyond displaying them on crates.io, and I think that it's going to remain that way for awhile, so I'm going to close this as out of the scope of Cargo currently.
