### ISSUE TITLE
Cargo not respecting build.target-dir

### ISSUE THREAD

**Issue by dfarley1** [rust-lang/cargo#8858]
**Problem**

I have a `/depot/{project_dir}/rust/Cargo.toml` that includes the following:
```
[build]
target-dir = "/depot/out/cur/target"
```
However, calling `cargo (build|check)` keeps creating `/depot/{project_dir}/rust/target` and `cargo metadata` includes `"target_directory":"/depot/{project_dir}/rust/target"`. It seems like Cargo is disregarding this option in most cases? Using `--target-dir` CLI option seems to work as intended.

**Notes**

Output of `cargo version`: `cargo 1.41.0`

**Comment by ehuss** [comment]
Configuration settings should go in a file named `.cargo/config.toml`. More information about configuration files may be found at https://doc.rust-lang.org/cargo/reference/config.html.

**Comment by dfarley1** [comment]
:facepalm: Sorry about that, I need to read more carefully!
