### ISSUE TITLE
native library `openssl` is being linked to by more than one package, and can only be linked to by one package

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/cargo#886]
```
native library `openssl` is being linked to by more than one package, and can only be linked to by one package
  openssl-sys v0.0.1 (https://github.com/alexcrichton/openssl-sys#d66fe840)
  openssl-sys v0.0.1 (https://github.com/sfackler/rust-openssl#fa42ed9e)
```

Affects master of [hyper](https://github.com/hyperium/hyper)

**Comment by softprops** [comment]
This just started happening to me recently as well.

**Comment by dbrgn** [comment]
I'm also having this problem on Travis recently (https://travis-ci.org/coredump-ch/spaceapi-server-rs/jobs/94403932). The thing is, I cannot reproduce this locally, even after deleting Cargo.lock and the `target` directory. Any ideas?

**Comment by alexcrichton** [comment]
@dbrgn that basically means that something in the graph is requiring 0.6 and something else is requiring 0.7, to fix the issue you'll need to make sure that everyone works with one or the other

**Comment by dbrgn** [comment]
Yep, that was the case :)
