### ISSUE TITLE
cargo run --{example,bin,bench,test} tab completion

### ISSUE THREAD

**Issue by pbrw** [rust-lang/cargo#8871]
**Problem**
If you want to run an example, you have to write it's full name in `cargo run --example <example_name>`. Name may be long and time is precious.

**Solution**
It would be great to have a tab completion implemented. We already have a list of possible targets displayed (#6505).

**Notes**
This was already mentioned [here](https://github.com/rust-lang/cargo/issues/2548#issue-146356558)

**Comment by ehuss** [comment]
It should already work, at least with bash.  The source is [here](https://github.com/rust-lang/cargo/blob/41c0f484a8b40874312751d47037826b3c2248b5/src/etc/cargo.bashcomp.sh#L216-L227).  Which shell are you using?  

The existing implementation is a bit of a hack, so perhaps it doesn't work in some situations.  Quickly retrieving the target names is not currently possible.  The long-term solution is intended to be #6645 where the `cargo` binary itself would drive the completions, where it has easy access to all the information.

**Comment by pbrw** [comment]
I use GNOME Terminal 3.36.2 and it clearly doesn't work

**Comment by ehuss** [comment]
GNOME Terminal is a GUI terminal program which is the interface to the underlying shell.  The shell is something like bash, zsh, or fish.  Each shell has different shell completion, so it is important to know which one you are using, and to check that the completions are integrated properly.  The exact method of integration will depend on the shell, OS, and how your startup scripts are setup.  Do any of the completions work?  If not, then maybe check that the completion is linked in properly for your environment. If completions are working, but just not the `--example` flag, can you provide a sample project that demonstrates where it doesn't work?

**Comment by pickfire** [comment]
Yeah, I am wondering why `cargo` does not auto complete `--example`.

**Comment by pickfire** [comment]
Ah, looks like it was in fish but there was a bug probably, or maybe it was new. https://github.com/fish-shell/fish-shell/pull/7566
