### ISSUE TITLE
Problems to compile on MacOs BigSur due to Linking Issues with Clang

### ISSUE THREAD

**Issue by jescobar** [rust-lang/cargo#8876]
Thanks for all the great job!!
**Problem**
I have updated to MacOs Big sur and I have started to get this issue when compiling some projects:

"/Users/josue/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-60333aa00936c5ce.rlib" "/Users/josue/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-116aaeaea873ef94.rlib" "-lpq" "-framework" "Security" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: library not found for -lpq
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

 I have run this without lucky:

 sudo xcode-select --install

also I read this:
New in macOS Big Sur 11, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

**Steps**
Just compile a project

**Notes**

Output of `cargo version`:
cargo 1.48.0 (65cbdd2dc 2020-10-14)
rustc 1.48.0 (7eac88abb 2020-11-16)

rustup toolchain list
stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

**Comment by ehuss** [comment]
Thanks for the report!  Can you provide an example of which project you are building?  AFAIK, `pq` is postgres?  Maybe you are using diesel with the `postgres` feature?  Maybe this is an issue with the pq-sys crate?

**Comment by jescobar** [comment]
Thanks for your help, you are right, I'm using diesel with postgres feature enable, so maybe that is the error. in fact I have check and I found other user reporting the same issue in mac os big sur just trying to install diesel_cli with postgres support

**Comment by jescobar** [comment]
the cargo toml file is

[package]
name = ""
version = "0.1.0"
authors = ["Josue Escobar"]
edition = "2018"

[dependencies]
actix = "0.9.0"
actix-web = "2.0.0"
actix-http = { version = "1.0.1", default-features = false }
actix-rt = "1.1.1"
actix-multipart = "0.2.0"
actix-codec = "0.2.0"
actix-server = "1.0.3"
actix-service = "1.0.5"
actix-cors = "0.2.0"
actix-identity = "0.2.1"
actix-web-httpauth = "0.4.1"
actix-files = "0.2.2"

structopt = "0.3"

regex = "1"

async-std = "1.6.2"

csv = "1.1.3"
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono", "uuidv07", "network-address", "serde_json", "numeric", "quickcheck", "with-deprecated"] }

dotenv = "0.15.0"
dotenv_codegen = "0.15.0"

bytes = "0.5.4"
env_logger = "0.7.1"
futures = "0.3.5"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
serde = "1.0.105"
serde_json = "1.0.50"
serde_derive = "1.0.105"
r2d2 = "0.8.8"
chrono = { version = "0.4.11", features = ["serde"] }
ip_network = { version = "0.3.4", features = ["serde", "diesel"] }
askama = "0.9.0"
markup = "0.4.1"
num_cpus = "1.13.0"
log = { version = "0.4.8", features = ["release_max_level_off"] }
derive_more = "0.99.7"
jsonwebtoken = "7.1.0"
bigdecimal = { version = "0.1.0", features = ["serde"] }
juniper = { version = "0.14.2", default-features = false, features = [  "url",
    "uuid",] }
itertools = "0.9.0"
bcrypt = "0.8.0"

**Comment by ehuss** [comment]
Since this sounds like an issue with the pq-sys crate locating the appropriate libraries, I would suggest following up with that project (https://github.com/sgrif/pq-sys).  Closing as this doesn't seem to be an issue with Cargo itself, though if you find out any information about this being a problem with Cargo, feel free to follow up here.
