### ISSUE TITLE
Unable to use cfg(test) modules from benchmarks

### ISSUE THREAD

**Issue by seanpianka** [rust-lang/cargo#8897]
**Problem**
Modules annotated with the `#[cfg(test)]` macro cannot be `use`'d by benchmarks, as an unresolved import error is thrown when `$ cargo bench` is run. 

The goal is to re-use test fixtures from the crate's modules in the benchmarks, as they often contain re-useable environment setup logic (which is useful for writing benchmarks!).

**Steps**

1. `$ cargo new --lib mycoolcrate && cd mycoolcrate`
2. Replace the contents of `src/lib.rs` with the following:
```rust
#[cfg(test)]
pub mod tests {
    pub struct Fixture {
        pub value: u8
    }
    impl Fixture {
        pub fn new() -> Self {
            Self { value: 1 }
        }
    }

    #[test]
    fn should_work() {
        let f = Fixture::new();
        assert_eq!(2 + f.value, 3);
    }
}
```
3. Add the following sections to `Cargo.toml`:
```toml
[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "mycoolcrate"
harness = false
```
4. `$ mkdir benches`
5. Add the following contents to `benches/mycoolcrate.rs`:
```rust
extern crate mycoolcrate;
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use mycoolcrate::tests::Fixture;

fn add(a: u8, b: u8) -> u8 {
    a + b
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("add 1", |b| {
        let fixture = Fixture::new();
        b.iter(|| add(black_box(1), black_box(fixture.value)))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```
6. Run `$ cargo bench` and see the compiler error:
```rust
error[E0432]: unresolved import `mycoolcrate::tests`
 --> benches/mycoolcrate.rs:3:18
  |
3 | use mycoolcrate::tests::Fixture;
  |                  ^^^^^ could not find `tests` in `mycoolcrate`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `mycoolcrate`
```

**Possible Solution(s)**

I have a workaround that involves nesting modules, where the outer module contains the definition/`impl` of the test fixture, and a nested module is annotated with `#[cfg(test)]` and contains all the unit test cases.

Here is a barebones version of the solution:
`src/lib.rs`:
```rust
pub mod test {
    pub struct Fixture {
        pub value: u8
    }
    impl Fixture {
        pub fn new() -> Self {
            Self { value: 1 }
        }
    }

    #[cfg(test)]
    mod cases {
        use super::Fixture;

        #[test]
        fn should_work() {
            let f = Fixture::new();
            assert_eq!(2 + f.value, 3);
        }
    }
}
```

`benches/mycoolcrate.rs`:
```rust
extern crate mycoolcrate;
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use mycoolcrate::test::Fixture;

fn add(a: u8, b: u8) -> u8 {
    a + b
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("add 1", |b| {
        let fixture = Fixture::new();
        b.iter(|| add(black_box(1), black_box(fixture.value)))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

This nesting of `test` and `cases` keeps the output of `$ cargo test` fairly readable:
```
// This:
test test::cases::should_work ... ok
// Instead of:
test tests::tests::should_work ... ok
```

However, I think it's preferable that the original attempt compiles, since benchmarking and testing are related concepts.

**Notes**

Output of `cargo version`:
```
$ cargo version
cargo 1.48.0 (65cbdd2dc 2020-10-14)

$ rustup show
<..snip..>
active toolchain
----------------
stable-x86_64-apple-darwin (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

$ system_profiler SPSoftwareDataType
Software:
    System Software Overview:
      System Version: macOS 10.15.7 (19H2)
      Kernel Version: Darwin 19.6.0
      ...
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

**Comment by ehuss** [comment]
I believe this is working as intended.  The benches in the `benches` directory are similar to tests in the `tests` directory in that they link to the library (without `--cfg test`) and only have access to the public API.

If your benches must access private APIs in the library, then they should be included as modules within the library (which allows private access).

If you are just trying to reuse some common benchmark code across separate bench targets, there are a few approaches to this.  You can put the shared code in a separate file `common.rs`, and use `mod common;` in each bench to mount it directly, or use `#[path]` tricks if benches are in separate directories.  This has a slight drawback in that it is recompiled for each bench target. Or, you can place the common code in a separate package (this is what cargo does itself with the [cargo-test-support](https://github.com/rust-lang/cargo/tree/master/crates/cargo-test-support) package).

**Comment by ehuss** [comment]
I'm going to close as I think this is working as intended.  If you have more questions about how packages, crates, and modules work, I suggest following up on one of the user forums (such as [urlo](https://users.rust-lang.org/)).
