### ISSUE TITLE
More helpful error message on .cargo/config paths problem

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/cargo#890]
**Scenario:**
- Create a cargo project called `myrs` that depends on another cargo project `librs`, both of which you are writing
- Tell cargo to use local librs with a `.cargo/config` file in your develop root (`paths = ["/home/me/develop/librs"]`)
- Rename "librs" to "librs2" but forget to update your `.cargo/config` file
- Run `cargo build` (with verbose or without)

**Helpful message:**

```
Unable to update file:///home/me/develop/librs

in file:///home/me/develop/.cargo/config line 1

Please check if the folder exists and if there is an error in your .cargo file
```

**Actual message:**

```
Unable to update file:///home/me/develop/librs

Caused by:
  Could not find Cargo.toml in `/home/me/develop/librs`
```

**Comment by kellda** [comment]
Now the error message is better:

```
error: failed to unable to update path override `/home/me/develop/librs` (defined in `/home/me/develop/.cargo/config`)

Caused by:
  failed to read directory `/home/me/develop/librs`

Caused by:
  No such file or directory (os error 2)
```

Should this issue be closed then ?

**Comment by ehuss** [comment]
Yea, I think the current error seems to provide enough information to figure out what is wrong.
