### ISSUE TITLE
Cargo keeps recompiling github dependencies

### ISSUE THREAD

**Issue by xixixao** [rust-lang/cargo#8925]
**Problem**

I am using a github URL dependency like this:

`orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }`

When I run `cargo build`/`cargo run`, it recompiles my project every time, even when I'm making no changes. I expect it to not recompile these dependencies every time.

When I use the master version from cargo this is not an issue.

**Notes**

Output of `cargo version`:
cargo 1.48.0 (65cbdd2dc 2020-10-14)

I'm on MacOS (10.15.7)

**Repro**
You can clone this repo:
https://github.com/xixixao/rust-raytracer

You will need cmake (which might be another reason why these keep recompiling)

----

cc @FloVanGH in case this is known thing for this library

Thanks!

----

This is the build/run ouput, every time:

```
23:17:23 ray-tracer cargo run                                               main
   Compiling orbtk_utils v0.3.1-alpha4 (https://github.com/redox-os/orbtk.git?branch=develop#583123d3)
   Compiling orbtk_render v0.3.1-alpha4 (https://github.com/redox-os/orbtk.git?branch=develop#583123d3)
   Compiling orbtk_shell v0.3.1-alpha4 (https://github.com/redox-os/orbtk.git?branch=develop#583123d3)
   Compiling orbtk_api v0.3.1-alpha4 (https://github.com/redox-os/orbtk.git?branch=develop#583123d3)
   Compiling orbtk_widgets v0.3.1-alpha4 (https://github.com/redox-os/orbtk.git?branch=develop#583123d3)
   Compiling orbtk v0.3.1-alpha4 (https://github.com/redox-os/orbtk.git?branch=develop#583123d3)
   Compiling ray-tracer v0.1.0 (/Users/srb/Work/Rust/ray-tracer)
    Finished dev [unoptimized + debuginfo] target(s) in 13.36s
     Running `target/debug/ray-tracer`

**Comment by alexcrichton** [comment]
One tip to help out with this is to set `CARGO_LOG=cargo::core::compiler::fingerprint=info` and something it prints out is 

```
[2020-12-01T15:20:31Z INFO  cargo::core::compiler::fingerprint] stale: missing "/Users/acrichton/.cargo/git/checkouts/orbtk-90d798f349c2ab56/583123d/crates/utils/colors.csv"
```


which I believe is a bug in [this build script](https://github.com/redox-os/orbtk/blob/583123d3757d4e5fc121580dafaffe6dbf31ae39/crates/utils/build.rs#L8) since that file doesn't exist in the repository.

**Comment by xixixao** [comment]
@alexcrichton Thank you so much for your help with an issue not related to cargo.

The only thing I can think of cargo could benefit from, but I don't see it being high on your priority list, is to detect a situation like this (when repeated builds lead to the same output) and warn the user somehow about it.
