### ISSUE TITLE
Change default git branch name to Main instead of Master

### ISSUE THREAD

**Issue by NangiDev** [rust-lang/cargo#8926]
When running
```
cargo new project-name --bin
```
The generated project initiates git with default branch name _master_.

My suggestion is that when running the new project command the default branch name should be _main_

 I know it's not a universal agreement that git branches using _main_ as default now a days, but it is has been growing. Also GitHub that this project is hosted on has decided on _main_.

**Comment by NangiDev** [comment]
Could be a duplicate of [cargo init](https://github.com/rust-lang/cargo/issues/8827) and [use HEAD instead](https://github.com/rust-lang/cargo/issues/3517)

Also I found out that using a git-template could fix this for me if we decides to keep it as is

**Comment by LordSentox** [comment]
I think a reason for keeping `master` as the main branch and hopefully without getting too political would be that when calling `git init` the default branch is still `master` eventhough some websites have changed their behaviour. Could this be more of a git issue than a cargo issue?

**Comment by Nemo157** [comment]
You need to just configure your git, I have `init.defaultBranch = prīmum` in my `~/.gitconfig` and:

```console
/tmp/tmp.qSrokxe56d > cargo new foo
     Created binary (application) `foo` package
/tmp/tmp.qSrokxe56d > cd foo
/tmp/tmp.qSrokxe56d/foo on prīmum >
```

**Comment by NangiDev** [comment]
> I think a reason for keeping `master` as the main branch and hopefully without getting too political would be that when calling `git init` the default branch is still `master` eventhough some websites have changed their behaviour. Could this be more of a git issue than a cargo issue?

Yes it makes sense. I guess you could look at changing to main to be a custom config on these websites part. So staying with git standard makes sense to me. Also I found the git-template solution. I think that is a valid solution for people who want main as default.


> You need to just configure your git, I have `init.defaultBranch = prīmum` in my `~/.gitconfig` and:
> 
> ```
> /tmp/tmp.qSrokxe56d > cargo new foo
>      Created binary (application) `foo` package
> /tmp/tmp.qSrokxe56d > cd foo
> /tmp/tmp.qSrokxe56d/foo on prīmum >
> ```

This is a good solution for me. Thanks. I'm guessing this is a global gitconfig right? So it would change all my future git inits.

**Comment by NangiDev** [comment]
Closing issue.
The "workaround" Nemo157 mentioned is a good solution.

**Comment by teohhanhui** [comment]
Seems like something is not working correctly.

I have this set correctly in my `~/.gitconfig`:
```
[init]
	defaultBranch = main
```

And `git init` gives the correct default branch name. However, `cargo new` still uses `master` :disappointed:

**Comment by scottshambaugh** [comment]
To give a one-liner that accomplishes this, run
```
git config --global init.defaultBranch 'main'
```

**Comment by indianakernick** [comment]
I ran `git init` and it uses `main`. I ran `cargo new` and it uses `master`. Perhaps something changed?

**Comment by Nemo157** [comment]
I can't reproduce locally, without configuration both `git` (2.41.0) and `cargo` (latest nightly) use `master`, with configuration both use the configured value.

@indianakernick What do `git config --get init.defaultBranch`, `git --version` and `cargo --version` say?

One thing I notice is that cargo uses `libgit2` to initialize the repository, which I presume queries the config and has a hard-coded default of `master`. If you have a version of `git` patched to use a different default (which hasn't happened upstream, but maybe some distros patch it?) then they may differ.

**Comment by indianakernick** [comment]
I'm also on macOS but I'm using the version of `git` that's bundled with Xcode.

```
> git config --get init.defaultBranch
main
> git --version
git version 2.39.2 (Apple Git-143)
> cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
```

**Comment by indianakernick** [comment]
I get `/Applications/Xcode.app/Contents/Developer/usr/share/git-core/gitconfig`. That's probably it then. It doesn't look in this Xcode-specific place. Makes sense. Probably not a bug.

**Comment by JohnnyWalkerDigital** [comment]
Hmm. It's nearly 2025:

GitLab - default branch `main`
GitHub - default branch `main`
Apple Git - default branch `main`

I know git itself is still lagging, but isn't it time it was hardcoded to `main` in `cargo new` to match the rest of the industry while git sorts itself out?

**Comment by weihanglo** [comment]
Cargo respects whatever libgit2 chooses, which largely respects what is set on users's local/system config. That said, if you're on macOS, there is a bug in libgit2: <https://github.com/rust-lang/cargo/issues/14650>.
