### ISSUE TITLE
Misleading help text for metadata --quiet

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#8928]
**Problem**
`cargo metadata --quiet` prints to stdout even though `--help` says
```
OPTIONS:
    -q, --quiet                          No output printed to stdout
```

**Steps**
1. `cargo metadata --help`
2. `cargo metadata --quiet`
3. Observe that stdout is not empty

**Possible Solution(s)**
Obviously, `--quiet` _meant_ to indicate that no cargo messages are printed to stdout (or maybe stderr) like "Updating index". But, the way it's written, it clearly implies that _no_ output should go to stdout.

**Notes**

Output of `cargo version`: cargo 1.47.0 (f3c7e066a 2020-08-28)

**Comment by bishtpawan** [comment]
Hi @jonhoo, can you please share the message that fits this scenario?

Thanks

**Comment by jonhoo** [comment]
Hmm, how about:
> Do not print cargo log messages.

**Comment by bishtpawan** [comment]
Looks good to me. Thanks

**Comment by Maxpxt** [comment]
This also applies to `cargo build --quiet`, `cargo run --quiet`, `cargo test --quiet`, `cargo bench --quiet`, `cargo doc --quiet`, and possibly other commands. They are all documented as "No output printed to stdout", but warnings, errors, test results, ..., are shown.
