### ISSUE TITLE
Tests not found when dead code warning disabled

### ISSUE THREAD

**Issue by Pluriscient** [rust-lang/cargo#8936]
**Problem**
When the warning for dead code is disabled, cargo doesn't find any of my submodule tests.

**Steps**

1. Put `#[cfg(warn_dead_code)]` in main.rs
2. Create a submodule with a simple test
3. Try running `cargo test`, be sad :(

**Minimal repro**
main.rs: 
```rust
#[cfg(warn_dead_code)]
mod sub;

fn main() {
    println!("hello");
}
```

sub/mod.rs
```rust
mod subtester;
```
subtester.rs
```rust
#[test]
fn test_sub() {
    println!("hello from the module");
}


mod test {
    #[test]
    fn test() {
        println!("hello from the sub submodule")
    }
}
```

Output of `cargo test`:
```
   Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running target\debug\deps\broken-dd0e69b7978850b2.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Possible Solution(s)**

Probably a regression?

**Notes**

Output of `cargo version`:
cargo 1.47.0-nightly (51b66125b 2020-08-19)

**Comment by Eh2406** [comment]
`#[cfg(warn_dead_code)]` means only compile if the feature `warn_dead_code` is activated. I think you want `#[warn(dead_code)]`.

**Comment by Pluriscient** [comment]
Oh thank you for the correction, seems this issue was non-existent then 💯
