### ISSUE TITLE
Cargo prints warnings about the workspace root twice

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#8948]
**Problem**

Adding `[profile.dev] debug = 1` prints a warning twice instead of once:

```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/joshua/rustc2/src/librustdoc/Cargo.toml
workspace: /home/joshua/rustc2/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/joshua/rustc2/src/librustdoc/Cargo.toml
workspace: /home/joshua/rustc2/Cargo.toml
```

**Steps**

1. git clone https://github.com/rust-lang/rust/
2. cd rust/src/librustdoc
3. git checkout 500b0f3c1ba651f31abc551ccbcf222f48e355a2
4. printf '[profile.dev]\ndebug = 1\n' >> Cargo.toml
5. cargo build

**Notes**

Output of `cargo version`: cargo 1.50.0-nightly (bfca1cd22 2020-11-24)

**Comment by ehuss** [comment]
Hm, I'm unable to figure out a way to reproduce this. Can you maybe show the output of these commands:

`cargo metadata | jq .workspace_members`

`CARGO_LOG=cargo::core::workspace=debug cargo build`

**Comment by jyn514** [comment]
Sorry, I had bad reproduction steps. The command I was running was

```
cargo clean -p rustdoc && cargo rustc --lib -- -Z self-profile -Z time-llvm-passes=yes -Z self-profile-events=default,args  -Z human-readable-cgu-names -C codegen-units=2000
```

which shows that cargo is actually being run twice, and only warning once per run. Sorry for the noise.
