### ISSUE TITLE
Failing to use exported trait from cargo workspace github repo

### ISSUE THREAD

**Issue by asnaseer-resilient** [rust-lang/cargo#8956]
**Problem**
I have a git repo that contains a Cargo workspace made up of a set of re-useable library modules. One of the re-useable library modules (`Describable`) is depended on by another module in the same workspace (`HealthCheckable`) using the **path** attribute in its `Cargo.toml`. When I try to use `HealthCheckable` and `Describable` in another project then Cargo thinks I have two versions of `Describable`.

The issue is fully described in this [stackoverflow](https://stackoverflow.com/questions/65174433/how-to-export-traits-from-a-separate-cargo-workspace-github-repo) question.

kmdreko posted this comment on the issue:

> I'm pretty sure that cargo thinks lib_describable(git) is different than lib_health_check(git) -> lib_describable(path), you might be able to override depenedencies to get them in line

**Notes**

Output of `cargo version`: cargo 1.48.0-nightly (126907a7c 2020-08-31)
Output of `rustup --version`: rustup 1.22.1 (b01adbbc3 2020-07-08)

**OS**: macOS Big Sur Version 11.0.1

**Comment by alexcrichton** [comment]
Thanks for the report! The bug, however, is that the `git` dependencies use different tags. To Cargo those are two different sources of code which are compiled separately. You'll want to specify the same tag and then things should work out!

**Comment by asnaseer-resilient** [comment]
@alexcrichton Thanks for looking at this. However, I /think/ have a catch 22 situation here. I tag the repo only if the build succeeds. So how can I specify the "future" tag in my `Cargo.toml` file in my workspace repo?

**Comment by alexcrichton** [comment]
I think Cargo isn't compatible with how you're trying to use git repositories and CI. The two crates need to be pulled from the same git repo one way or another, and that needs to be specified the same way with both dependencies.
