### ISSUE TITLE
Cargo panics when building a proc-macro crate with build-std present in any parent .cargo/config.toml

### ISSUE THREAD

**Issue by rjb3977** [rust-lang/cargo#8975]
**Problem**
If you have a `.cargo/config.toml` file with `build-std = ['std']` (and valid `target`), and you try to build a crate with `proc-macro = true`, Cargo panics. This is only really a problem if that `.cargo/config.toml` exists in some parent directory of the crate.

**Steps**
1. Clone [this minimal repo](https://github.com/rjb3977/cargo-panic-example).
2. Run `cargo build`, or `RUST_BACKTRACE=full cargo build` if you so desire.

**Possible Solution(s)**
- Display an error message saying that `build-std` is not allowed for `proc-macro` crates.
- Fix `build-std` for `proc-macro` crates.
- Ignore `build-std` for `proc-macro` crates.
- Implement something like #8687.

**Notes**

Output of `cargo version`: `cargo 1.50.0-nightly (d274fcf86 2020-12-07)`
Backtrace: [hastebin](https://hastebin.com/udabovanuf.txt)

**My actual use case**

I have a crate that targets `wasm32-unknown-unknown`, and I'd like to have a small child crate so I can use procedural macros. Since I'm using atomics in the `wasm32` crate, I need `build-std`. In this case, I will still most likely need something like #8687, so that I can reset the `rustflags` array. I'll probably just end up figuring out how to pull the `proc-macro` crate up a level to get around this whole issue, but I figure a panic is still undesirable and at the very least can be turned into a helpful error message.

**Comment by weihanglo** [comment]
This has been fixed in a corresponding nightly version between stable 1.55.0 to 1.56.0. I didn't dive deeper but at least the reproducer doesn't panic on 1.56.0 and today's nightly (`cargo 1.84.0-nightly (66221abde 2024-11-19)`), and in <https://github.com/rust-lang/cargo/pull/14850>. Hence closing.

If you still encounter this, let us know about it!
