### ISSUE TITLE
Not all cargo requests contains User-Agent header

### ISSUE THREAD

**Issue by lightsing** [rust-lang/cargo#8979]
**Problem**

**Steps**

1. setup mitmproxy
2. setup proxychains4
3. proxychains4 cargo build

**Possible Solution(s)**
Add missing fields.

**Notes**

Output of `cargo version`: cargo 1.48.0 (65cbdd2dc 2020-10-14)

rustup: 1.23.1 (3df2264a9 2020-11-30)
toolchain: stable-x86_64-unknown-linux-gnu
![header-exists](https://user-images.githubusercontent.com/15951701/102323482-80f66e00-3fbb-11eb-8e13-d68d051dfe1a.png)
![header-missing](https://user-images.githubusercontent.com/15951701/102323486-82c03180-3fbb-11eb-879a-9774f8dd3244.png)

**Comment by alexcrichton** [comment]
Could you perhaps share the configuration you have? (e.g. `.cargo/config.toml`)

I've double-checked and there's only one place we create an HTTP request handle and it should always have the user-agent field set. Additionally those URLs don't look like ones that Cargo is creating, so are you sure that this is something that Cargo is doing?

**Comment by lightsing** [comment]
We found this issue in lightsing/crates-io-cn#14.
Our CDN used to be configured for User-Agent whitelisting (forbidding empty User-Agents and non-cargo User-Agents).
This caused some of the requests sent by cargo to encounter a 403 response, which was reproduced in several places. After examination by mitmproxy, it was found that some of the cargo requests were missing the User-Agent header.

p.s. We now turn off the CDN check for User-Agents. You are probably not being able to reproduce the identical 403 response.

cargo configuration:
```
[source.crates-io]
replace-with = 'cn'

[source.cn]
registry = "https://crates-io.cn/crates.io-index"
```

**Comment by alexcrichton** [comment]
Can you try running the command with:

```sh
$ export CARGO_HTTP_DEBUG=true
$ export CARGO_LOG=cargo::ops::registry
$ cargo fetch
```

and gist the output? Cargo should print the headers it sends on every request which would be useful to figure out which one is missing the user-agent header.

**Comment by lightsing** [comment]
Here you go: https://gist.github.com/a7844ef965813962030590ffad6d00db

**Comment by alexcrichton** [comment]
Unfortunately I don't really know what's going on here, that log definitely shows Cargo not always sending a user-agent field. The HTTP handle is [created here](https://github.com/rust-lang/cargo/blob/27dba04f406a870f00241b53cbda74411cd53c9f/src/cargo/core/package.rs#L651) which is [configured here](https://github.com/rust-lang/cargo/blob/27dba04f406a870f00241b53cbda74411cd53c9f/src/cargo/ops/registry.rs#L540) and unconditionally sets the useragent [here](https://github.com/rust-lang/cargo/blob/27dba04f406a870f00241b53cbda74411cd53c9f/src/cargo/ops/registry.rs#L564-L568).


Have you perhaps configured `http.user-agent` to an empty string? Maybe in the environment or `.cargo/config.toml`? Or maybe this is a bug in curl if it's not sending the header? Sorry I don't really know how to investigate this myself.

**Comment by ehuss** [comment]
One suspicious thing I noticed in your debug output is that the `accept: */*` header is using a lowercase `a`.  The [default header](https://github.com/curl/curl/blob/a56f263cdc72cef293bda899a0ae482a89502fa2/lib/http.c#L3048) that libcurl adds uses an uppercase `A`.  I don't think those requests are being generated by cargo (unless you have a build with a custom libcurl).

I'm not familiar with `proxychains4`, but looking at the description, I would highly suspect that (or the actual proxy) is the source of the issue.
