### ISSUE TITLE
cargo metadata downloads crate files for unused targets

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#8981]
**Problem**
`cargo metadata` (and `cargo tree`, possibly also others) downloads the `.crate` files for dependencies that are not used under the current `cfg` parameters. This means that it will, for example, download windows-only dependencies even if run on a UNIX platform. `cargo build` and friends do not do this. This occurs even with `--filter-platform`/`--target` is passed to filter for a particular target (I understand `cargo metadata` is _supposed_ to cover all targets unless explicitly otherwise specified).

**Steps**

1. Construct a `Cargo.toml` with a `cfg`-guarded dependency:
   ```toml
   [package]
   name = "bug"
   version = "0.1.0"
   edition = "2018"
   
   [target.'cfg(bogus)'.dependencies]
   serde = "1"
   ```
2. Run `cargo check`, and notice that it does not download `serde`.
3. Run `cargo metadata --filter-platform x86_64-unknown-linux-gnu`, and notice that it _does_ download `serde`.

**Possible Solution(s)**
The cause of the bug is here:
https://github.com/rust-lang/cargo/blob/de4230293d01000fe13052e9bef38278d7b268fd/src/cargo/ops/cargo_output_metadata.rs#L133-L136

As the comment notes, that logic should do target filtering as expressed in `PackageSet::download_accessible`:
https://github.com/rust-lang/cargo/blob/862df617991a327579d1f8ee6b9e861e96fc96a9/src/cargo/core/package.rs#L485

**Notes**

Output of `cargo version`: cargo 1.48.0 (65cbdd2dc 2020-10-14)

**Comment by jonhoo** [comment]
Arguably the same bug exists in `cargo fetch`, except that there it appears to be intentional:
https://github.com/rust-lang/cargo/blob/862df617991a327579d1f8ee6b9e861e96fc96a9/src/cargo/ops/cargo_fetch.rs#L40-L44

**Comment by jonhoo** [comment]
Hmm, this will be complicated by the fact that for `cargo metadata` filtering by platform is opt-in using `--filter-platform`, not opt-out (like `cargo tree` and friends). So, if we want tools like `rust-analyzer` to not download unnecessary dependencies, they will need to also pass in `--filter-platform`, rather than us doing the conservative thing by default and requiring explicit opt-in (with `--target all`) to fetch all targets.

**Comment by alexcrichton** [comment]
Sorry I'm still catching up on the issues so if this is irrelevant by this point ignore me, but I believe this is intentional. Without `--filter-platform` the metadata subcommand assumes everything *could* match. If the dependency is downloaded with `--filter-platform` that's almost certainly a bug to be fixed.

**Comment by jonhoo** [comment]
Ah, sorry missed your question:

Yes, this PR fixes the bug that `cargo metadata` (and `cargo tree`) would download dependencies for all targets _even when_ `--filter-platform`/`--target` are passed.

My point above was more that since the default for `cargo metadata` defaults to all targets, the onus is on downstream tools to remember to pass `--filter-platform` if they don't want that behavior. I've already fixed that issue in `rust-analyzer` (https://github.com/rust-analyzer/rust-analyzer/pull/6912), though the fix would have been nicer if there was a `--filter-platform host`.
