### ISSUE TITLE
Specifing toolchain requires full host specified

### ISSUE THREAD

**Issue by NukeManDan** [rust-lang/cargo#8989]
**Problem**

I can't use the shorthand for specifying the toolchain with cargo. 
I need to use a specific toolchain in a build script for many targets, so the `Default host: x86_64-unknown-linux-gnu` not being interoperated by cargo is an issue! 

```bash
$ cargo +nighty-2020-10-05 build --release
error: toolchain 'nighty-2020-10-05' is not installed
```

I have the toolchain installed: 
```bash
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  xxx

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2020-10-05-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2020-10-05-x86_64-unknown-linux-gnu (default)
rustc 1.49.0-nightly (beb5ae474 2020-10-04)

```
what does work:
```bash
cargo +nightly-2020-10-05-x86_64-unknown-linux-gnu build --release
```

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
cargo 1.48.0-nightly (75615f8e6 2020-09-29)

This is related to issues substrate builds that require nightly from 2020-10-5 and before. https://github.com/paritytech/substrate/issues/7150

**Comment by Eh2406** [comment]
The toolchain is a rustup concept as is the ` +nighty` syntax. I do not have permission to transfer this issue to https://github.com/rust-lang/rustup, but someone else may be able to do that for you.

**Comment by TomaszWaszczyk** [comment]
@NukeManDan Is it issue connected with https://github.com/paritytech/substrate/issues/7150 (look at the bottom)?

**Comment by NukeManDan** [comment]
yes @TomaszWaszczyk - I referenced this issue in the opening comment here ;) 

We don't want to have to set a default global toolchain to make builds of substrate work. That is what this issue addresses 🙏🏼

**Comment by ehuss** [comment]
I'm going to close, as this is a rustup issue.  I suggest re-filing over at the rustup issue tracker: https://github.com/rust-lang/rustup/issues/

Normally that shorthand syntax should work.  There are many steps to determining the default host and toolchain information.  Make sure to include as much information as you can, such as:
* How rustup was installed (which triple was used).
* What's in the settings file (`~/.rustup/settings.toml`)
* Information about your OS (rustup has some [probes](https://github.com/rust-lang/rustup/blob/3cca9ff11dd4ea31f2611c03cb5861baa1a13a9c/src/dist/dist.rs#L152-L233) for detecting this, it may be getting confused).
* Do you have any environment variables set, like `RUSTUP_OVERRIDE_BUILD_TRIPLE` or `TARGET`?  Any environment variable that contains `RUSTUP` in it?
