### ISSUE TITLE
error: could not read vendor path

### ISSUE THREAD

**Issue by ethindp** [rust-lang/cargo#8999]
**Problem**

I just recently updated rust via rustup and now cargo gives me this error when I do cargo run (the project I'm building requires the rust sources):

```
error: could not read vendor path C:\Users\ethin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\vendor

Caused by:
  The system cannot find the path specified. (os error 3)
```

I've never seen this error before and it's making it impossible to build my project.

**Steps**

1. Install rustup
2. Install at least rustc 1.50.0-nightly (eb4fc71dc 2020-12-17).
3. Try to build a no_std project for any CPU architecture.

**Possible Solution(s)**

I'm not honestly sure how this bug even arose. I don't know why cargo would need vendored deps (I'm connected to the internet) and I can't find any reference for this happening. I don't know if the above steps are truly reproduceable but that's what I did.

**Notes**

Output of `cargo version`:

cargo 1.50.0-nightly (d274fcf86 2020-12-07)

Doing this on the nightly toolchain. I happened to be debugging the project at the time when I ran rustup update, cargo clean and then cargo run, but cargo clean never complained, only cargo run, and I don't know how running rustup update when I'm debugging anything really matters in terms of affecting the installation process.

**Comment by ehuss** [comment]
Can you try updating to nightly-2020-12-19 (published about an hour ago). There was a temporary hiccup in the 2020-12-18 release that should be fixed now.

**Comment by ethindp** [comment]
Yep, that solved things. Thanks!
