### ISSUE TITLE
Crate failed to unpack on Windows -- The system cannot find the path specified (os error 3)

### ISSUE THREAD

**Issue by sachinparyani** [rust-lang/cargo#9008]
**Problem**
Cannot install a package because of the following:

(C:\Users\Administrator\anaconda3) C:\Users\Administrator\source\AzureMlCli\dataprep\Core\rust_lex>cargo install cargo-edit-locally
    Updating crates.io index
  Installing cargo-edit-locally v0.1.3
error: failed to compile `cargo-edit-locally v0.1.3`, intermediate artifacts can be found at `C:\Users\ADMINI~1\AppData\Local\Temp\cargo-installeyslmu`

Caused by:
  failed to download `libgit2-sys v0.6.19`

Caused by:
  unable to get packages from source

Caused by:
  failed to unpack package `libgit2-sys v0.6.19`

Caused by:
  failed to unpack entry at `libgit2-sys-0.6.19/libgit2/tests/resources/push_src/.gitted/modules/submodule/objects/pack/pack-a81e489679b7d3418f9ab594bda8ceb37dd4c695.idx`

Caused by:
  failed to unpack `C:\Users\Administrator\AppData\Local\viennaBuildTools\rust\nightly-2020-09-09\cargo\registry\src\github.com-1ecc6299db9ec823\libgit2-sys-0.6.19\libgit2\tests\resources\push_src\.gitted\modules\submodule\objects\pack\pack-a81e489679b7d3418f9ab594bda8ceb37dd4c695.idx`

Caused by:
  failed to unpack `libgit2-sys-0.6.19/libgit2/tests/resources/push_src/.gitted/modules/submodule/objects/pack/pack-a81e489679b7d3418f9ab594bda8ceb37dd4c695.idx` into `C:\Users\Administrator\AppData\Local\viennaBuildTools\rust\nightly-2020-09-09\cargo\registry\src\github.com-1ecc6299db9ec823\libgit2-sys-0.6.19\libgit2\tests\resources\push_src\.gitted\modules\submodule\objects\pack\pack-a81e489679b7d3418f9ab594bda8ceb37dd4c695.idx`

Caused by:
  The system cannot find the path specified. (os error 3)

Output of `cargo version`: cargo 1.48.0-nightly (75615f8e6 2020-09-29)

**Comment by ehuss** [comment]
It looks like the path is too long for Windows. `C:\Users\Administrator\AppData\Local\viennaBuildTools\rust\nightly-2020-09-09\cargo` is a somewhat unusual location for Cargo's home directory, are you using a custom installation of Rust?

Also, that version of libgit2-sys is 2 years old. Newer versions do not include those extra long paths.

**Comment by sachinparyani** [comment]
@ehuss here's my output of rustup show

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Administrator\AppData\Local\viennaBuildTools\rust\nightly-2020-09-09\rustup

installed toolchains
--------------------

nightly-2020-09-09-x86_64-pc-windows-msvc
nightly-2020-09-18-x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-gnu (default)
1.45.0-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-gnu (default)
rustc 1.49.0-nightly (beb5ae474 2020-10-04)

**Comment by ehuss** [comment]
Usually Rust is installed in the root of your home directory when installed with the defaults of rustup (such as `C:\Users\eric\.rustup` and `C:\Users\eric\.cargo`). This helps ensure the paths don't get too long.  I don't know what "viennaBuildTools" is, but I would recommend trying to relocate it closer to the root. I don't know if this is your project or not, but upgrading to a more recent libgit2-sys should also remove those long files.  The [`CARGO_HOME`](https://doc.rust-lang.org/cargo/guide/cargo-home.html) environment variable can also be set to a directory closer to the root
