### ISSUE TITLE
Including a sub crate in cargo package doesn't seem to be possible?

### ISSUE THREAD

**Issue by emilio** [rust-lang/cargo#9017]
STR:

 * `git clone https://github.com/eqrion/cbindgen && cd cbindgen && git checkout v0.16.0`
 * `cargo package` (succeeds)
 * Add to the `Cargo.toml` file something like `include = ["tests/rust/expand_dep"]` (or any other test sub-crate). I expected something like that to fix https://github.com/eqrion/cbindgen/issues/637.
 * `cargo package`

Expected:

 * Crates get packaged?

Actual:

```
error: couldn't read src/lib.rs: No such file or directory (os error 2)
error: aborting due to previous error
error: could not compile `cbindgen`
```

**Comment by emilio** [comment]
Hmm, ok, so `include = []` is not doing what I expected, which is fine, but is there a way to include a subcrate? Doing it explicitly doesn't seem to help. I guess for now I can avoid packaging those tests but...

**Comment by ehuss** [comment]
Cargo intentionally does not allow a single `.crate` file to include multiple packages (see #6917 and #8597).  In general, the `.crate` file should not be expected to be able to run all tests.  Although it works in many cases, there are various edge cases that do not work.  If you want a fully testable snapshot of a release, I would suggest packaging it separately (for example, using GitHub Releases).

**Comment by emilio** [comment]
I see, thanks. That's a kind of unfortunate limitation, as it'd be nice if `cargo package` did "the right thing" off-hand.

I guess for now skipping those tests is fine. If somebody cares, making a separate source release is probably also an option.

I'll close this since this seems basically a dupe of https://github.com/rust-lang/cargo/issues/8597. Thanks for the references!
