### ISSUE TITLE
How to publish a xx.crate or a cargo project to local repository

### ISSUE THREAD

**Issue by Silentdoer** [rust-lang/cargo#9018]
it is useful for offline mode, we pre fetch all of needs crate file to offline machine, then use cargo publish --offline x1.crate, x2.crate ...;

and cargo tree should support package all dependencies, like cargo tree --package /usr/local/rust-dep, cargo will copy all of deps to /usr/local/rust-dep folder, then we can copy the folder to offline machine.

**Comment by ehuss** [comment]
Sorry, I'm having a hard time understanding what you are asking.  

`cargo publish` fundamentally cannot work offline, it sends the package to a registry, which is usually on the network.

If you're referring to a [local registry source](https://doc.rust-lang.org/cargo/reference/source-replacement.html#local-registry-sources), there is the [cargo-local-registry](https://crates.io/crates/cargo-local-registry) tool for managing those.

I don't really understand the comment about `cargo tree`.  If you want `cargo tree` to read from a local repository, you need to set up the appropriate [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html).  Or, you can use a local [registry](https://doc.rust-lang.org/cargo/reference/registries.html), which can support `file://` urls.

**Comment by Silentdoer** [comment]
> Sorry, I'm having a hard time understanding what you are asking.  
> 
> `cargo publish` fundamentally cannot work offline, it sends the package to a registry, which is usually on the network.
> 
> If you're referring to a [local registry source](https://doc.rust-lang.org/cargo/reference/source-replacement.html#local-registry-sources), there is the [cargo-local-registry](https://crates.io/crates/cargo-local-registry) tool for managing those.
> 
> I don't really understand the comment about `cargo tree`.  If you want `cargo tree` to read from a local repository, you need to set up the appropriate [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html).  Or, you can use a local [registry](https://doc.rust-lang.org/cargo/reference/registries.html), which can support `file://` urls.
> 

such as I have a my-lib.crate file, and it is not contains in .cargo folder, i want install it to .cargo/cache, and generate index, there has some cargo sub command?

**Comment by Silentdoer** [comment]
> Sorry, I'm having a hard time understanding what you are asking.  
> 
> `cargo publish` fundamentally cannot work offline, it sends the package to a registry, which is usually on the network.
> 
> If you're referring to a [local registry source](https://doc.rust-lang.org/cargo/reference/source-replacement.html#local-registry-sources), there is the [cargo-local-registry](https://crates.io/crates/cargo-local-registry) tool for managing those.
> 
> I don't really understand the comment about `cargo tree`.  If you want `cargo tree` to read from a local repository, you need to set up the appropriate [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html).  Or, you can use a local [registry](https://doc.rust-lang.org/cargo/reference/registries.html), which can support `file://` urls.
> 
the function is very similar java's maven: mvn install command

**Comment by ehuss** [comment]
I'm sorry, this issue is pretty abstract and incomplete.  I don't think there is anything exactly like what you are asking. A local registry is probably closest to what you are asking.

**Comment by ehuss** [comment]
I'm going to close this as this seems like a major feature request that would better suited for something like the [RFC process](https://doc.crates.io/contrib/process/index.html#working-on-large-features) than an issue here.
