### ISSUE TITLE
cargo generate reports missing libssl.so.1.0.0 

### ISSUE THREAD

**Issue by cryptable** [rust-lang/cargo#9025]
**Problem**
I found in my CLion a way to generate rust application using 'cargo generate', but this fails. I tried it on the command line and it fails also.
```
$ cargo generate https://github.com/cryptable/rust-arm-template.git r03_knock-knock-interrupt
/home/david/.cargo/bin/cargo-generate: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

I'm using Linux mint based on Ubuntu 2.10
```
$ uname -a
Linux rosa-lee 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps**
1. Just run 'cargo generate' on a recent linux

**Possible Solution(s)**
- You should probably rebuild the rust openssl and openssl-sys using the version of openSSL 1.1.x . This more secure, because it supports TLS 1.3. 
- Another solution is to link it with libssl.so with the risk of the incompatibility problems between OpenSSL 1.0.x and OpenSSL 1.1.x.
- Very bad solution would be statically link an openssl version (I prefer version 1)

**Notes**

Output of `cargo version`:
- (stable) cargo 1.48.0 (65cbdd2dc 2020-10-14)
- (nightly) cargo 1.50.0-nightly (75d5d8cff 2020-12-22)

**Comment by sfackler** [comment]
cargo generate is a third party tool: https://crates.io/crates/cargo-generate.

**Comment by cryptable** [comment]
Thanks, didn't know that! Updating cargo generate fixed the issue.
