### ISSUE TITLE
cargo install cross -> error: failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`

### ISSUE THREAD

**Issue by Michele31415** [rust-lang/cargo#9028]
Following the directions here: https://github.com/rust-embedded/cross
to install cross on a Ubuntu 20.04 system with a working rust, I get:

michele@michele-VirtualBox:~/.cargo/bin$ cargo install cross
error: failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to read root of directory source: /home/michele/vendor

Caused by:
  No such file or directory (os error 2)
michele@michele-VirtualBox:~/.cargo/bin$ cd
michele@michele-VirtualBox:~$ ls -l vendor
ls: cannot access 'vendor': No such file or directory
michele@michele-VirtualBox:~$ cargo vendor
error: could not find `Cargo.toml` in `/home/michele` or any parent directory
michele@michele-VirtualBox:~$ cargo fix
error: could not find `Cargo.toml` in `/home/michele` or any parent directory
michele@michele-VirtualBox:~$ cargo install cross
error: failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to read root of directory source: /home/michele/vendor

Caused by:
  No such file or directory (os error 2)
michele@michele-VirtualBox:~$ 

According to the above, I am missing a file in my home directory called "vendor".  However, I have no idea what this file might be nor how or where to get one, nor why this install command should fail  Any help would be appreciated.

**Comment by ehuss** [comment]
`failed to update replaced source registry` indicates you have a [config file](https://doc.rust-lang.org/cargo/reference/config.html) with a [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html) configured. I would check for `~/.cargo/config` (or `config.toml`) and remove the source replacement.

**Comment by Michele31415** [comment]
Thank you so much for a clear and informative answer.  For the record (and for the benefit of anyone else later on with the same problem) here is what I had:

```
michele@michele-VirtualBox:~$ cd .cargo
michele@michele-VirtualBox:~/.cargo$ ls
bin  config  env  registry
michele@michele-VirtualBox:~/.cargo$ more config
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.sparcv9-sun-solaris]
linker = "/usr/sparcv9-solaris/solaris/cross/bin/sparcv9-solaris2.11-gcc"
michele@michele-VirtualBox:~/.cargo$ 
```

I removed the "vendored" lines, reran the `cargo install cross `command and this time it worked.  Thanks again.

**Comment by ehuss** [comment]
Closing as resolved.
