### ISSUE TITLE
cargo update with git repo gives "Assertion `ref' failed. Aborted (core dumped)"

### ISSUE THREAD

**Issue by detly** [rust-lang/cargo#9036]
**Problem**

I have a project with this in `Cargo.toml`:

```toml
[dependencies]
rumqttc = { git = "https://github.com/bytebeamio/rumqtt", rev = "e74d915ce1c4766389cd7df892d3aa1233c22091"}
```

When I run `cargo update` I get:

```plain
    Updating crates.io index
    Updating git repository `https://github.com/bytebeamio/rumqtt`
cargo: libgit2/src/refs.c:315: const char *git_reference_name(const git_reference *): Assertion `ref' failed.
Aborted (core dumped)
```

Problems:

1. Obviously the crash instead of successful completion.
2. The error message is not particularly useful and doesn't give me much to go on.

## Versions

Cargo installed via Rustup.

- Cargo version: `cargo 1.49.0 (d00d64df9 2020-12-05)`
- Rustc version: `rustc 1.49.0 (e1884a8e3 2020-12-29)`
- Environment: Ubuntu 20.10

## Additional info

If I run with `CARGO_NET_GIT_FETCH_WITH_CLI=true` I get:

```plain
    Updating crates.io index
    Updating git repository `https://github.com/bytebeamio/rumqtt`
error: failed to get `rumqttc` as a dependency of package `rumz v0.1.1 (/home/jason/Code/rumz)`

Caused by:
  failed to load source for dependency `rumqttc`

Caused by:
  Unable to update https://github.com/bytebeamio/rumqtt?rev=e74d915ce1c4766389cd7df892d3aa1233c22091

Caused by:
  the given reference name 'refs/heads/' is not valid; class=Reference (4)
```

Note that this [ref really exists](https://github.com/bytebeamio/rumqtt/commit/e74d915ce1c4766389cd7df892d3aa1233c22091).

**Comment by detly** [comment]
One user on the Rust Discord tried to reproduce it on `x86_64-pc-windows-msvc`, but their `cargo update` succeeded.

**Comment by detly** [comment]
(Did I really add that `C-bug` label? I didn't mean to, but I won't remove it in case it's something automatic.)

**Comment by detly** [comment]
On beta and nightly channels I get a segfault instead:

```plain
    Updating crates.io index
    Updating git repository `https://github.com/bytebeamio/rumqtt`
Segmentation fault (core dumped)
```

**Comment by detly** [comment]
I removed a tab from my `~/.gitconfig` and now it works. Adding the tab back in could not reproduce the bug. I have no idea what has happened. :man_shrugging:

**Comment by detly** [comment]
Oops, no, if I change it to `tag = "R3"` the core dump is back.

**Comment by detly** [comment]
I have become obsessed. This issue only happens on one of my machines (all Ubuntu, different releases). Git is the same on all (2.30.0). On the machine where it happens, I used git bisect on the cargo repo, with my good/bad criterion being "can I do `cargo fetch` with a git repo?". Git bisect tells me the first "bad" commit was 82239d7a100acae243f6aa45e9bed19375d07a6f ("Bump libgit2 dependencies") by @alexcrichton.

I still have no idea why it only happens on this one machine, and why a statically linked library bump would be an issue.

**Comment by detly** [comment]
I figured it out. On the machine with the problem, I had the following in `~/.gitconfig`:

```.gitconfig
[init]                                                                                                         
defaultBranch = "" 
```

(I don't know why. I didn't set it to that, at least not on purpose.)

Older versions of libgit2 and git did not use this setting. Newer ones do. I'm guessing that having it empty caused a problem with string substitution somewhere, resulting in the problems above.

On the bright side, I sure learned a lot about debugging Rust programs today.

**Comment by ehuss** [comment]
I filed https://github.com/libgit2/libgit2/issues/5761 for the seg fault issue, it shouldn't do that even with an invalid config.
