### ISSUE TITLE
Cargo failed to compile, stating it can't download a dependency.

### ISSUE THREAD

**Issue by sokorototo** [rust-lang/cargo#9043]
So, I am kinda new to Rust. I am getting better with Rust and so decided to try and open a simple GUI window with the rust crate `iced = "0.2.0`. I try a basic example and cargo returns the following error:
 ```
error: failed to download `rayon v1.5.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.5.0\Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  unexpected character found: `\u{0}` at line 1 column 1
```

I don't know what's wrong and would really appreciate some help. For reference my cargo.toml: 
```toml
[package]
name = "iced-window"
version = "0.1.0"
authors = ["Newton Toto <sokorototo@noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
iced = "0.2.0"
```

**Comment by alexcrichton** [comment]
Hm this looks like the manifest file is corrupted somehow. If you remove the `registry/src` directory it may fix the issue, but how this character snuck in there is also a bit of a mystery...

**Comment by sokorototo** [comment]
Where is this directory specifically?

**Comment by Eh2406** [comment]
according to the error message you posted it is at `C:\Users\user\.cargo\registry\src`
