### ISSUE TITLE
Documentation uses `†` in the markdown, but it's rendered as `1`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#9056]
This is not so much a bug as an oddity (I noticed it while tracking down another bug in deadlinks: https://github.com/deadlinks/cargo-deadlinks/issues/133#issuecomment-748399781). In https://github.com/rust-lang/cargo/blob/94e21ada550f91f5d32f2f51635792a79aeb8d63/src/doc/src/reference/build-script-examples.md#build-script-examples, the link shows †, but it shows up differently when rendered:

![image](https://user-images.githubusercontent.com/23638587/104041959-cfa4bb80-51a7-11eb-8944-9298ef6234ab.png)
![image](https://user-images.githubusercontent.com/23638587/104041964-d29fac00-51a7-11eb-9051-669c2e2f59f9.png)

I assume that's not intentional? Is this a mdbook bug maybe - I think footnotes are an mdbook extension? The links work fine, it just seems odd.

**Comment by ehuss** [comment]
I wouldn't consider it a bug.  The footnote references can be any sort of label (a word for example), and those get numbered sequentially.  That makes it easier to maintain so you don't have to renumber footnotes when they are added/removed.  It could be changed to a more descriptive label, but I'm not sure it really matters.
