### ISSUE TITLE
Cargo reference doc: Wrong example of "Specifying Dependecies"

### ISSUE THREAD

**Issue by supernatural** [rust-lang/cargo#9062]
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

Example of Caret requirements is wrong:
^1.2.3  :=  >=1.2.3, <2.0.0
^1.2    :=  >=1.2.0, <2.0.0
...
^0.0.3  :=  >=0.0.3, <0.0.4

Should be:
^1.2.3  :=  >=1.2.3, <1.3.0
^1.2    :=  >=1.2.0, <1.3.0
...
^0.0.3  :=  >=0.0.3, <0.1.0

Output of `cargo version`:
cargo 1.43.0

**Comment by ehuss** [comment]
I believe it is correct. Caret requirements only constrain the leftmost nonzero component.  Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2fc98e22aa6f1d130f0580e2cfb2d609

Is there something that leads you to believe otherwise?

**Comment by supernatural** [comment]
Yes, you're right, I made a mistake of '~' and '^', Sorry!
