### ISSUE TITLE
How to find output of cargo rustc?

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/cargo#9080]
When calling `cargo rustc -- --emit obj`, how do I find the created object file?

**Comment by ehuss** [comment]
Output usually goes into `target/debug/deps`.

**Comment by mahkoh** [comment]
Under which file name?

**Comment by ehuss** [comment]
Usually the name of the crate with the `.o` extension.  See https://doc.rust-lang.org/rustc/command-line-arguments.html#--emit-specifies-the-types-of-output-files-to-generate for more information on the default filenames.

**Comment by mahkoh** [comment]
>Usually the name of the crate with the .o extension.

That's incorrect. The only object files produced contain a hash.

**Comment by ehuss** [comment]
It depends on the platform, the target type, and other factors.  For libraries, it is the crate name, plus Cargo uses `-C extra-filename` to add a hash to differentiate it between other crates of the same name.

**Comment by mahkoh** [comment]
This does not answer my original question. Let me repeat: When calling `cargo rustc -- --emit obj` how do I find the file created by rustc?

**Comment by ehuss** [comment]
There's not a simple answer.  You can use `ls target/debug/deps/*.o`.  You can use `--emit obj=somepath.o` to explicitly set the output path.  Cargo is not generally oriented for using these low-level options, so it won't tell you the explicit filenames.

**Comment by mahkoh** [comment]
> You can use `--emit obj=somepath.o` to explicitly set the output path.

That's exactly what I was looking for. Unlike `-o`, this ignores `--extra-filename`. This difference does not seem to be documented though.
