### ISSUE TITLE
cargo install fails because dependency was yanked

### ISSUE THREAD

**Issue by cedricje** [rust-lang/cargo#9091]
I'm trying to install sccache to a specific version, which depends on a yanked crate. This causes the build to fail. I thought yanked crates were still available to crated depending on them.

**Steps**
```
cargo -vv install sccache --version 0.2.13 --features redis

    Updating crates.io index
  Installing sccache v0.2.13
error: failed to compile `sccache v0.2.13`, intermediate artifacts can be found at `/tmp/cargo-installmvxuY4`

Caused by:
  no matching package named `lru-disk-cache` found
  location searched: registry `https://github.com/rust-lang/crates.io-index`
  required by package `sccache v0.2.13`
```

**Notes**
```
 cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)
```

**Comment by ehuss** [comment]
Try with `--locked`.  By default, `cargo install` attempts to use the latest versions of dependencies. `--locked` will use the versions from `Cargo.lock` when `sccache` was published, which allows using yanked versions.

**Comment by cedricje** [comment]
That works. Thanks for the help!
