### ISSUE TITLE
Program terminate with unexpected `SIGABRT` when using panic = "abort"

### ISSUE THREAD

**Issue by arnaudgolfouse** [rust-lang/cargo#9103]
**Problem**
My program terminate with `SIGABRT` unexpectedly.

**Steps**
1. In `Cargo.toml`:
    ```toml
    [dependencies]
    syn = { version = "1.0.60", default-features = false, features = ["parsing", "full"] }
    thiserror = "1.0.23"

    [profile.dev]
    panic = "abort"
    ```

2. And in `main.rs`
    ```rust
    fn main() {
        let _ = syn::parse_str::<syn::Expr>("");
    }
    ```
3. run `cargo run` (on rust stable 1.49): the ouput is
    ```
    fish: “cargo run” terminated by signal SIGABRT (Abort)
    ```

I suspect this belongs in the cargo issues, because removing either
```toml
thiserror = "1.0.23"
```
or
```toml
panic = "abort"
```
Fixes the issue.

**Notes**

Output of `cargo version`:
```
cargo 1.49.0 (d00d64df9 2020-12-05)
```
On ubuntu 20.04.1, rust 1.49 stable, target x86_64-unknown-linux-gnu

**Comment by ehuss** [comment]
I think this is working as expected.  Adding `thiserror` enables the `proc-macro` feature on `syn`, which is incompatible with `panic="abort"`.  See https://github.com/alexcrichton/proc-macro2/issues/218 for more information.

**Comment by arnaudgolfouse** [comment]
Wow, ok... well at least this is not a bug in cargo 😅
Thank you for the response !
