### ISSUE TITLE
Add warning when `cargo install --locked` used, but there is no Cargo.lock available

### ISSUE THREAD

**Issue by dekellum** [rust-lang/cargo#9106]
This warning would help understanding the cause of install failures, as in this [URLO Thread](https://users.rust-lang.org/t/cant-install-binary-due-to-yanked-dependency/54697/3).

So for example, cargo-graph 0.3.1 was published without a Cargo.lock (prior to that feature being stabilized in cargo 1.37), and so using the `--locked` flag has no effect (the build still fails due to a yanked dependency).  It would be much easier to understand why `--locked` doesn't help, if the following warning was introduced in the output:

```diff
cargo install cargo-graph --locked 
    Updating crates.io index
  Installing cargo-graph v0.3.1
+warning: no Cargo.lock file published in cargo-graph v0.3.1
error: failed to compile `cargo-graph v0.3.1`, intermediate artifacts can be found at `/tmp/cargo-installdryLBw`

Caused by:
  failed to select a version for the requirement `clap = "~2.11.3"`
  candidate versions found which didn't match: 2.33.3, 2.33.2, 2.33.1, ...
  location searched: crates.io index
  required by package `cargo-graph v0.3.1`
```

**Comment by CPerezz** [comment]
As @alexcrichton  correctly stated in https://github.com/rust-lang/cargo/pull/9108#issuecomment-769162649 I made a PR to change this when indeed it was decided some time ago to specifically not warn about this.

Therefore, my question is whether it should still be like this, or instead, a warning should be added as suggested in the Rust forum thread linked above?

**Comment by dekellum** [comment]
Can you (or cc, @alexcrichton) summarize the historic rationale (or current advantage) of _not_ warning?  I'm very surprised by that, but then again, I'm surpised by a lot of things.  The comment you link just states that there was a historic reason. In the scenario of the above linked URLO thread, it seems entirely obvious that warning _should_ be output!.

**Comment by CPerezz** [comment]
Hi @dekellum I'm completely unaware of the rationale behind. I was told by Alex in the PR that this was decided some time ago. but maybe @Eh2406 or @ehuss can bring some light here and decide whether it's worth or not to go for this.

**Comment by alexcrichton** [comment]
Gah my apologies, I completely misinterpreted this issue and the associated PR. I basically didn't read an inversion of logic and I thought this issue was about warning if `--locked` isn't used when a `Cargo.lock` is present. I see now that is not the case. 

That being  said I typically find it more helpful if the issue description isn't simply "Do it!" but rather puts some more effort in to explaining what the issue is about.

**Comment by dekellum** [comment]
@alexcrichton my bad, sorry. I felt the URLO comment made it very clear (inline diff format) and neglected to reproduce it here. I'll edit above shortly.
