### ISSUE TITLE
Building cargo in msys2 on Win64 failing with default instructions

### ISSUE THREAD

**Issue by CraZySacX** [rust-lang/cargo#911]
The .travis.install.deps.sh script has various checks for a BITS variable.  It appears that .travis.yml was setting this and calling it appropriately in the CI environment.  However, running .travis.install.deps.sh without BITS set causes everything to default to i686-pc-windows-gnu.

I worked around this by executing ```BITS=64 ./.travis.install.deps.sh```

I don't normally build on Windows, this was my first shot, so I may be doing something wrong.

**Comment by alexcrichton** [comment]
The instructions now mention running `.travis.install.deps.sh`, so I believe this is fixed now.
