### ISSUE TITLE
Cargo publish fails to publish Windows crate

### ISSUE THREAD

**Issue by kennykerr** [rust-lang/cargo#9134]
I can only publish the [windows](https://crates.io/crates/windows) crate by using the `--no-verify` flag. It complains about a `Cargo.lock` file created outside of `OUT_DIR` but that file isn't created by the `windows` crate at all.

To reproduce, clone http://github.com/microsoft/windows-rs and issue the `cargo publish` command. Here's what I get:

```
C:\git\windows-rs>cargo publish
    Updating crates.io index
   Packaging windows v0.3.1 (C:\git\windows-rs)
   Verifying windows v0.3.1 (C:\git\windows-rs)
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.60
   Compiling squote v0.1.2
   Compiling const-sha1 v0.2.0
   Compiling quote v1.0.8
   Compiling windows_winmd_macros v0.3.1
   Compiling windows_gen_macros v0.3.1
   Compiling windows_winmd v0.3.1
   Compiling windows_gen v0.3.1
   Compiling windows_macros v0.3.1
   Compiling windows v0.3.1 (C:\git\windows-rs\target\package\windows-0.3.1)
    Finished dev [unoptimized + debuginfo] target(s) in 31.42s
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Added: C:\git\windows-rs\target\package\windows-0.3.1\Cargo.lock

  To proceed despite this, pass the `--no-verify` flag.
```

Am I doing something wrong?

**Comment by alexcrichton** [comment]
Do you perhaps have a build script which executes Cargo commands to learn about your crate? (e.g. `cargo metadata` without the `--no-deps` flag). That's my best guess at least for where `Cargo.lock` appears from.

**Comment by kennykerr** [comment]
Ah yes, I call `cargo metadata` to find the workspace dir. Adding `--no-deps` indeed avoids the creation of the `Cargo.lock` file. 

Thanks Alex!
