### ISSUE TITLE
Allow build.rs reruns to be triggered on feature flag changes

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/cargo#9135]
**Describe the problem you are trying to solve**

It should be possible to cause `build.rs` to rerun if feature flags change. Currently, it can only be configured to re-run when files or environment variables change, which can lead to a situation where cfg flags that influence codegen aren't detected, causeing stale code in `OUT_DIR`.

**Describe the solution you'd like**

Propose adding `cargo:rerun_if_feature_changed`. This would cause the build script to re-run if the feature flag changes state; ie, if it becomes enabled when it was previously disabled, or vice versa.

**Notes**
None

**Comment by ehuss** [comment]
The build script should be rebuilt and rerun whenever features change, and the results are independently cached.  What would be the reason to rerun the script again?

**Comment by Lucretiel** [comment]
I'll double check my results; the intermittent test failures I'm seeing seem to be caused be stale gen'd code from the build script (ie, the code isn't regenerated, but the tests are run under the updated feature set, leading to failures).

**Comment by Lucretiel** [comment]
Yup, it turns out this is related to how build.rs sandboxes builds with different features, and how that interacts with our unusual codegen requirements (code must be gen'd into a predictable directory, making `OUT_DIR` unsuitable.
