### ISSUE TITLE
Unstable options config problems in config.toml

### ISSUE THREAD

**Issue by CPerezz** [rust-lang/cargo#9138]
Maybe I'm doing it in the wrong way. But I wanted to enable [this rustdoc unstable feature](https://doc.rust-lang.org/rustdoc/unstable-features.html#--enable-per-target-ignores-allow-ignore-foo-style-filters-for-doctests).

So I have the following:
```toml
#.cargo/config.toml
[unstable]
enable-per-target-ignores = "yes"

[build]
rustdocflags = ["--cfg", "docsrs", "--enable-per-target-ignores"]
```

Then inside of my code i use the feature like ` \```ignore-whatever_feature`.

Everything seems to follow the guidelines in [the docs](https://doc.rust-lang.org/cargo/reference/unstable.html) but oce I run `cargo doc` I get:
```
✦ ❯ cargo doc
warning: unused config key `unstable.enable-per-target-ignores` in `path_to/.cargo/config.toml`
 Documenting unicode-xid v0.2.1
 Documenting cfg-if v1.0.0
 Documenting spin v0.5.2
 Documenting byteorder v1.4.2
error: the `-Z unstable-options` flag must also be passed to enable the flag `enable-per-target-ignores`
error: the `-Z unstable-options` flag must also be passed to enable the flag `enable-per-target-ignores`


error: could not document `unicode-xid`

Caused by:
  process didn't exit successfully: `rustdoc --crate-type lib --crate-name unicode_xid /home/_/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.2.1/src/lib.rs --cap-lints allow -o /home/_/Desktop/HDD/dusk/dusk-blindbid/target/doc --cfg 'feature="default"' --error-format=json --json=diagnostic-rendered-ansi -L dependency=/path_to/target/debug/deps --cfg docsrs --enable-per-target-ignores --crate-version 0.2.1` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: the `-Z unstable-options` flag must also be passed to enable the flag `enable-per-target-ignores`

error: the `-Z unstable-options` flag must also be passed to enable the flag `enable-per-target-ignores`

error: build failed
```

Also
```toml
[build]
rustdocflags = ["--cfg", "docsrs", "-Z unstable-options --enable-per-target-ignores"]
```
Neither did the job.

Is the CLI-args the only way to run this thing? Can't it be implicitly added to the cargo config on any way?

**Comment by ehuss** [comment]
The unstable table is only for Cargo's own unstable options. You'll need to use rustdocflags for now.

**Comment by ehuss** [comment]
Oh, and I notice an error in your example.  When using a TOML array, each string is a separate argument. `"-Z unstable-options --enable-per-target-ignores"` needs to be split into multiple strings.

**Comment by CPerezz** [comment]
You're completely right @ehuss, while the `[unstable]` did nothing this is solvable by writing arrays in TOML syntax correctly (so not like me :sweat_smile: ).

If it happens to anyone, on this way it should work:
```toml
#.cargo/config.toml
[build]
rustdocflags = ["--cfg", "docsrs", "-Z", "unstable-options", "--enable-per-target-ignores"]
```

**Comment by CPerezz** [comment]
Would be nice to be able to specify this kind of features also in the config and allow cargo to pass them with the lint level `-Z` as it does with `-D, -W, -F` . Would an RFC be required for this? Or an issue with a good description would do?

**Comment by CPerezz** [comment]
Update: The flag does not work. It gets digested by Cargo but doesn't work atm.
