### ISSUE TITLE
How to turn off cargo doc test and compile for a specific package in Rust

### ISSUE THREAD

**Issue by liufuyang** [rust-lang/cargo#9146]
**Describe the problem you are trying to solve**

I have some generated rs code (from grpc proto filles) and they are checked in with my normal rust code under src but in some sub modules. The issue is when doing cargo test the doc test will run and some of the generated rs have comments with some indentations and cargo doc test trying to compile them and failed.

For example `cargo test` will try to compile (and perhaps run these lines) [show here](https://github.com/liufuyang/bigtable_rs/blob/3678b99a7b7554197dd97e633f5919e975790f81/bigtable_rs/src/google/google.bigtable.v2.rs#L267-L283).

The cargo output could be like:
```
---- src/google/google.bigtable.v2.rs - google::bigtable::v2::row_filter::Interleave::filters (line 268) stdout ----
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `row`
 --> src/google/google.bigtable.v2.rs:269:7
  |
3 | input row
  |       ^^^ expected one of 8 possible tokens

error: aborting due to previous error

Couldn't compile the test.
```

I seem cannot find a way to exclude or ignore those generated rs for doc test (without manually changing them)?

**Describe the solution you'd like**

Perhaps allow some type of configuration in `Cargo.toml` or some ignore file like `.cargo_test_ignore` to specify some path or packages to ignore cargo doing doc test on those?

---

PS: I asked the same on [stackoverlow](https://stackoverflow.com/questions/66074003/how-to-turn-off-cargo-doc-test-and-compile-for-a-specific-package-in-rust)

**Comment by ehuss** [comment]
Does setting the [doctest field](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-doctest-field) to false work for you?

**Comment by liufuyang** [comment]
But that turns off doctest completely? I have other rs files, the ones I edited, having doc tests.

**Comment by ehuss** [comment]
I do not think that is currently possible. See issues https://github.com/rust-lang/rust/issues/59867 and https://github.com/rust-lang/rust/issues/63193.

**Comment by ehuss** [comment]
Closing in favor of the linked issues.
