### ISSUE TITLE
std::process::Command::new("arch") in build.rs on Apple M1 is i386

### ISSUE THREAD

**Issue by schell** [rust-lang/cargo#9158]
**Problem**
`std::process::Command::new("arch")` in build.rs on an Apple M1 returns `i386`, when it should be returning `arm64` or `aarch64`. 

**Steps**

1. new project w/ build.rs
2. use `std::process::Command::new("arch").output().unwrap()`
3. observe the result

**Notes**
I'm not sure if this is a problem with cargo, `std::process` or my system 🤷 .

My cargo is nightly and is `arm64`:
```
schell~/test$ cargo --version
cargo 1.51.0-nightly (c3abcfe8a 2021-01-25)
schell~/test$ file (which cargo)
/Users/schell/.cargo/bin/cargo: Mach-O 64-bit executable arm64
```

**Comment by alexcrichton** [comment]
While I do not have  a mac myself to test on I believe you need to ensure that you're entire toolchain is arm64. This includes the actual rustc/cargo binaries themselves (you're only looking at the rustup shims in your example) and perhaps as well as the native linker and such.

**Comment by schell** [comment]
Thank you for your help. Hopefully this is sufficient to verify the `arm64`ness of the toolchain? Otherwise I'll try again :) 
```
schell~/.r/t/n/bin$ rustup toolchain list
stable-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)
schell~/.r/t/n/bin$ pwd
/Users/schell/.rustup/toolchains/nightly-aarch64-apple-darwin/bin
schell~/.r/t/n/bin$ file cargo && file rustc
cargo: Mach-O 64-bit executable arm64
rustc: Mach-O 64-bit executable arm64
schell~/.r/t/n/bin$ file (which ld)
/usr/bin/ld: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/ld (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/ld (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

**Comment by alexcrichton** [comment]
Sorry I don't know enough about arm64 macs to help more here. This is pretty unlikely to be a bug in Cargo though.

**Comment by ehuss** [comment]
Just to elaborate, *everything* needs to be arm64, your shell, your terminal, etc.  I notice that it looks like you are maybe using a non-standard shell (fish?), so maybe try with the system zsh.

FWIW, I cannot reproduce on an arm mac.

**Comment by schell** [comment]
> This is pretty unlikely to be a bug in Cargo though.
Very likely.

The `Command` process is picking `/bin/zsh` which is a universal binary, or at least that is what is set for the `SHELL` env var. I'll try playing around some more to verify that the entire chain is `arm64`.

**Comment by schell** [comment]
It's my editor, emacs! Running `cargo build` directly in the terminal results in `arm64`. 🤦 

Thank you :)
