### ISSUE TITLE
Can't update duplicated git dependency

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/cargo#9160]
**Problem**
I have a project which has a direct git dependency with branch "X", and an indirect git dependency on the same repo, but branch "Y".

I would like to update the direct dependency. (Although I don't care if both are updated, that's also fine)

**Steps**

I ran `cargo update -p openapi-gen` and got the following error:

```
error: There are multiple `openapi-gen` packages in your project, and the specification `openapi-gen` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  ssh://git@github.com/<org>/openapi-gen.git#openapi-gen:0.1.0
  ssh://git@github.com/<org>/openapi-gen.git#openapi-gen:0.1.0
```

Now... clearly these two "specs" are identical so this is not going to help. As expected, running the proposed command does not work:

```
error: There are multiple `openapi-gen` packages in your project, and the specification `ssh://git@github.com/<org>/openapi-gen.git#openapi-gen:0.1.0` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  ssh://git@github.com/<org>/openapi-gen.git#openapi-gen:0.1.0
  ssh://git@github.com/<org>/openapi-gen.git#openapi-gen:0.1.0
```

... and it suggests running the exact command I just ran 😆

**Comment by ehuss** [comment]
Thanks for the report, I think this may be a duplicate of #8481?

**Comment by Diggsey** [comment]
Ah yes, closing.
