### ISSUE TITLE
Fallback to Unix passwd database and /etc/mailname to initialize authors field in Cargo.toml

### ISSUE THREAD

**Issue by guillemj** [rust-lang/cargo#9163]
**Describe the problem you are trying to solve**

When creating a new project with `cargo new`, it would be nice to get as much of the authors information in `Cargo.toml` automatically filled with the most accurate and pre-existing data source as possible, w/o needing to set special-purpose settings or repeating information already defined elsewhere.

**Describe the solution you'd like**

At least on Unix systems, it would be nice to derive the username from the current uid, instead of requiring a USER variable (or any of the other existing data sources). It would be even better to derive the user name (in contrast to username :),  from the first comma-separated element in the GECOS field of the passwd database entry for that user. For the email, as a fallback for the current data sources, `/etc/mailname` could also be used.

**Notes**

This seems common practice at  least on Unix, it's what git is doing f.ex.

**Comment by Eh2406** [comment]
cc https://github.com/rust-lang/rfcs/pull/3052

**Comment by ehuss** [comment]
I'm going to close this as cargo no longer generates the authors fields per [RFC 3052](https://github.com/rust-lang/rfcs/blob/master/text/3052-optional-authors-field.md). Thanks for the suggestion, though!
