### ISSUE TITLE
Is there a way to package local dependencies?

### ISSUE THREAD

**Issue by konstin** [rust-lang/cargo#9170]
I'm writing [a tool](https://github.com/pyo3/maturin) that packages rust crates into python packages. For that, I need to pack all local crates into a .tar.gz. For a single crate, I use `cargo package --list --allow-dirty` and take those files. This however breaks when another local crate is linked.

I can find all local packages using `cargo metadata` and copying also works, but then I need to rewrite each Cargo.toml to point to the updated locations since I can't conserve the existing directory structure. Are there any rules or references on how to rewrite the Cargo.toml, or is there a recommended mechanism for doing this kind of automated replacement?

**Comment by sfackler** [comment]
`cargo vendor` may do what you're looking for.

**Comment by konstin** [comment]
Is there an option to only vendor local crates? As I understood it, `cargo vendor` will always vendor everything, which most users wouldn't want.

**Comment by ehuss** [comment]
I don't think there is anything existing that will do that.

> can't conserve the existing directory structure

Why can you preserve the original structure?

**Comment by konstin** [comment]
> Why can't you preserve the original structure?

Users might e.g. use crates that are on a different disk or other file system funkiness, and I expect trying to reproduce that structure in a zip file would rather error-prone, especially cross platform.

> I don't think there is anything existing that will do that.

Ok, thanks anyway, I've now gone with a cargo-edit style solution of rewriting the toml (https://github.com/PyO3/maturin/pull/441)
