### ISSUE TITLE
Incorrect feature set determination with conditional dependencies

### ISSUE THREAD

**Issue by d-e-s-o** [rust-lang/cargo#9176]
Please consider the following `Cargo.toml` (just use it after a `cargo init --bin foo`):
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = {version = "1.0", default-features = false, features = ["sync"]}
```

This project, unsurprisingly, builds. Notably, it also builds under the WASM target:
```bash
$ cargo build --target wasm32-unknown-unknown
   Compiling foo v0.1.0 (foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
```

Now let's apply the following patch:
```patch
--- Cargo.toml
+++ Cargo.toml
@@ -4,3 +4,6 @@ version = "0.1.0"

 [dependencies]
 tokio = {version = "1.0", default-features = false, features = ["sync"]}
+
+[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
+tokio = {version = "1.0", features = ["full"]}
```

Basically, when the target is *not* WASM, build `tokio` with all features. This project still builds natively, but it fails to build for WASM:
```bash
deso@nuc /tmp/foo (master *) $ cargo build --target wasm32-unknown-unknown
   Compiling mio v0.7.7
error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/mio-0.7.7/src/io_source.rs:12:5
   |
12 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`
```

As we can see, `mio` (and other crates) is now being pulled in. That should *not* happen! We are building for WASM, the feature set should only be comprised of `sync` (does not have additional dependencies), nothing else, but for some reason Cargo seems to determine the final set of features for `tokio` before looking at the conditional compilation (at least that's what it looks like).

If we apply the following patch:
```patch
--- Cargo.toml
+++ Cargo.toml
@@ -2,8 +2,8 @@
 name = "foo"
 version = "0.1.0"

-[dependencies]
-tokio = {version = "1.0", default-features = false, features = ["sync"]}
+#[dependencies]
+#tokio = {version = "1.0", default-features = false, features = ["sync"]}

 [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
 tokio = {version = "1.0", features = ["full"]}
```

We indeed get back a valid WASM build. At the same time we see that `tokio` is indeed pulled in correctly on a native build (making it clear that the configuration seems to be accepted properly otherwise):
```
$ cargo build
   Compiling libc v0.2.86
   Compiling proc-macro2 v1.0.24
   Compiling cfg-if v1.0.0
   Compiling unicode-xid v0.2.1
   Compiling log v0.4.14
   Compiling syn v1.0.60
   Compiling autocfg v1.0.1
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.6.1
   Compiling memchr v2.3.4
   Compiling bytes v1.0.1
   Compiling pin-project-lite v0.2.4
   Compiling once_cell v1.5.2
   Compiling instant v0.1.9
   Compiling lock_api v0.4.2
   Compiling tokio v1.2.0
   Compiling quote v1.0.9
   Compiling parking_lot_core v0.8.3
   Compiling mio v0.7.7
...
```

**Problem**
See above. The final feature set determination seems to be wrong.

**Steps**
See above.

**Notes**

Output of `cargo version`:
```
$ cargo version
cargo 1.50.0
```

I am on Linux.

**Comment by d-e-s-o** [comment]
FYI, using mirror the example gets a bit smaller and easier to debug:
```toml
[package]
name = "foo"
version = "0.1.0"

[dependencies]
mio = "0.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mio = {version = "0.7", features = ["os-poll"]}
```
(result is the same)

And here is some logging from a WASM build:
```
[2021-02-16T05:29:23Z INFO  cargo::core::compiler::job_queue] end (Unit { pkg: Package { id: PackageId { name: "mio", version: "0.7.7", source: "registry `https://github.com/rust-lang/crates.io-index`" }, ..: ".." }, target: TargetInner { ..: lib_target("mio", ["lib"], "/tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/mio-0.7.7/src/lib.rs", Edition2018) }, profile: Profile { incremental: false, ..: default_dev() }, kind: Target(CompileTarget { name: "wasm32-unknown-unknown" }), mode: Build, features: ["default", "os-poll"], is_std: false, dep_hash: 0 }): Err(could not compile `mio`
```

So if I am reading this correctly Cargo indeed compiles `mio` with the `os-poll` feature (as it does when building natively).

**Comment by ehuss** [comment]
You may want to try the new feature resolver which does not include features for inactive targets. It will hit stable in 1.51, and the documentation is [here](https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2).

**Comment by d-e-s-o** [comment]
Thanks for the pointer! Indeed, it determines the correct set of features.

**Comment by ehuss** [comment]
OK, glad it worked out!
