### ISSUE TITLE
Cargo can't run help sub-command in command line mode.

### ISSUE THREAD

**Issue by tomaswuhua123** [rust-lang/cargo#9197]
I don't know whether it's Cargo's bug or something wrong with my setting. Here is error in detail:
`$ cargo help bench`
//or other sub-command
And an error like this pop out:
`No manual entry for ~\AppData\Local\Temp\cargo-manGE7Y90`
Hope for help ,thanks a lot.

**Comment by ehuss** [comment]
Hm, I'm not sure what could cause that.  Could you provide some more information, such as what toolchain you are using?

The way it works, is that it writes the file to a temporary directory.  Then, if you have a `man` executable in your PATH, it will run `man` with the path to that temp file.  It is a bit unusual to have `man` on Windows, are you using something like mingw?

Do you have any of the following environment variables set?

* `TMP`
* `TEMP`
* `USERPROFILE`

The thing that seems suspicious to me is the `~` character, though I am uncertain how that could be created.

**Comment by tomaswuhua123** [comment]
Thanks for responding!
1.The toolchain I used to use is `stable-x86_64-pc-windows-gnu`, but now I'm using `stable-x86_64-pc-windows-msvc`
2.I'm sure I've never changed any environment variable like `TEP`
3.The `~`character means my user directory, the full path is `C:\Users\Myname\AppData\Local\Temp\cargo-mancpbmyf`
4.For my own preference, I didn't install my Cargo as default but I installed it as `D:\Rustlang\Cargo`
5.I used to use mingw, but since I changed my toolchain, I've deleted it.
That's all I think about my settings, and I'm trying to solve this under your hint.

**Comment by ehuss** [comment]
You might try running `which man` and `man --version` to figure out where the `man` executable is coming from (it is somewhere in the PATH).

**Comment by tomaswuhua123** [comment]
Thanks for your help, I found it's my `cygwin64` acting wrongly, which is the `man` executable comes from. When I remove my `cygwin64` from my environment variable, everything get Ok. My cargo help runs well, thank you.

**Comment by rmccampbell** [comment]
I encountered this same problem. I think this should be considered a bug; rust on windows should ignore any `man` found in the path and just use the default behavior.

**Comment by ehuss** [comment]
Sorry, I meant to reopen this issue.  I have posted a fix at #9378.
