### ISSUE TITLE
Don't pass `--features` from `target.'cfg(...)'.dependencies` to `dependencies`

### ISSUE THREAD

**Issue by JAicewizard** [rust-lang/cargo#9199]
Exactly like #4664, but for different `target.'cfg(...)'.dependencies` dependencies.
This came up when looking at build times in the `druid` crate after enabling tracing. Almost all of the increase was a wasm-only dependency which enabled all features for` tracing-subscriber`causing 24 extra crates to get build.

I hope this isnt a lot of work since its already been implemented once, but I never know.
I also think this should be enough information since its the same issue as an already fixed issue, but if you need more details feel free to ask.

**Comment by ehuss** [comment]
@JAicewizard Have you tried the new feature resolver?  It should hit stable in the next release, and there is documentation about how to use it [here](https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2).  It should avoid enabling features for any `target` dependency that is not being used.

**Comment by JAicewizard** [comment]
Ah yes, I read it was stabilized so I assumed it would also be enabled by default.
Using that does indeed fix the issue!
