### ISSUE TITLE
docs: `split-debuginfo` docs claim `unpacked` is the default on macOS.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/cargo#9218]
See https://github.com/rust-lang/cargo/pull/9112#discussion_r584767537 - I believe the rest of the PR was updated to keep the default `packed` (see https://github.com/rust-lang/cargo/pull/9112/commits/ffa9dbd34853457fd07f5c7152dc03adee069c96), but docs were missed.

This is now in beta so the doc fix would have to be backported to that as well.

cc @ehuss @alexcrichton

**Comment by ehuss** [comment]
Sorry for the confusion, posted #9224, and I will take care of beta as well.
