### ISSUE TITLE
Specifying jobs = 0 in .cargo/config hangs cargo forever without output

### ISSUE THREAD

**Issue by orlp** [rust-lang/cargo#9219]
If you specify `jobs = 0` in `.cargo/config`, your `cargo build` invocations will hang forever without output. Note that if you try to invoke `cargo build -j 0` it will warn you:

```
$ cargo build -j 0
error: jobs must be at least 1
```

**Steps**

1. Place a `.cargo/config` in any valid location with the following content:

        [build]
        jobs = 0

2. Run `cargo build`.
3. You will never reach step 3.

**Possible Solution(s)**

Check for `jobs` being 0 when reading the config file.

**Notes**

Output of `cargo version`: latest `master` commit, https://github.com/rust-lang/cargo/commit/0b2059e9811caa238a603f0300d9c5fb485000a6.

**Comment by Eh2406** [comment]
Looks like this go fix to return an error.

**Comment by ehuss** [comment]
@Eh2406 What kind of error are you seeing? It still seems to hang for me on the latest nightly.

**Comment by Eh2406** [comment]
Just me miss reading the code. Sorry.

**Comment by henrifrancois** [comment]
Does the issue still persist? If so I would like to give it a try

**Comment by Eh2406** [comment]
I believe it is still an issue. And nobody's working on it that I know of.
Have at it.

**Comment by henrifrancois** [comment]
@orlp do you know where the config files are read and processed?

**Comment by henrifrancois** [comment]
Hey, @Eh2406 could you help me out with this? I have something I think should work, but I am not sure why it isn't making a difference at all. 

In `build_context.rs` I have:
```rust
impl BuildConfig {
    /// Parses all config files to learn about build configuration. Currently
    /// configured options are:
    ///
    /// * `build.jobs`
    /// * `build.target`
    /// * `target.$target.ar`
    /// * `target.$target.linker`
    /// * `target.$target.libfoo.metadata`
    pub fn new(
        config: &Config,
        jobs: Option<u32>,
        requested_targets: &[String],
        mode: CompileMode,
    ) -> CargoResult<BuildConfig> {
        let cfg = config.build_config()?;
        let requested_kinds = CompileKind::from_requested_targets(config, requested_targets)?;
        if jobs == Some(0) {
            anyhow::bail!("jobs must be at least 1")
        }
        if jobs.is_some() && config.jobserver_from_env().is_some() {
            config.shell().warn(
                "a `-j` argument was passed to Cargo but Cargo is \
                 also configured with an external jobserver in \
                 its environment, ignoring the `-j` parameter",
            )?;
        }
        let jobs = match jobs.or(cfg.jobs) {
            None => ::num_cpus::get() as u32,
            Some(j) if j != 0 => (::num_cpus::get() as u32).max(j),
            Some(_) => anyhow::bail!("jobs may not be 0"),
        }; //.unwrap_or(::num_cpus::get() as u32);
```
which I assumed would be enough to handle the case where the jobs argument has a value of 0. Any pointers?

**Comment by Eh2406** [comment]
That is what I would have expected to work. And when I am careful to run the Cargo I just build and not the cargo from rustup, it worked for me!

**Comment by henrifrancois** [comment]
@Eh2406 How did you do that? I am following the instructions on the cargo contribution documentation, but maybe they could use some clarification?

**Comment by henrifrancois** [comment]
Oop, nevermind. I think I got it working.
