### ISSUE TITLE
Cargo build failed - likely rust issue 

### ISSUE THREAD

**Issue by jmosullivan** [rust-lang/cargo#9244]
Hi, 

I am running "cargo build --release" to compile dependencies with repeated error of "could not compile 'cfg-if' and the process stops. 

I think it may relate to rust which when I run "rustup update" gives the following"

info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
error: error creating temp directory
error: caused by: No such file or directory (os error 2) at path "/data/tmp/rustup-updatedsWPgl"

Any help with this would be really appreciated, 

Jennifer

**Comment by ehuss** [comment]
It looks like you maybe have the `TMPDIR` environment variable set to a path that doesn't exist (`/data/tmp`)?  I'd check that, and maybe unset it or figure out why it is pointing to that directory, and whether or not it exists.

This doesn't seem like an issue with cargo, though.  Perhaps try one of the user forums, such as https://users.rust-lang.org/.

**Comment by ehuss** [comment]
Without more information, I'm going to close this issue.  Hopefully you were able to fix whatever was wrong.  The user forums or chat platforms can possibly help with future issues getting things set up.
