### ISSUE TITLE
Cargo build forcing stable channel

### ISSUE THREAD

**Issue by AngelOnFira** [rust-lang/cargo#9254]
**Problem**

I'm trying to build a project with `cargo build`. It seems to be locking to the stable channel, even though I'm overriding with a toolchain file as well as with rustup. The project contains a `rust-toolchain` file, locked to `nightly-2021-01-01`. When I run `cargo build`, I get:

```
error: failed to parse manifest at `/home/forest/Documents/git/veloren/Cargo.toml`

Caused by:
  the cargo feature `named-profiles` requires a nightly version of Cargo, but this is the `stable` channel
  See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
```

The features that we're using in `Cargo.toml` are:

```
cargo-features = ["named-profiles","profile-overrides"]
```

**Steps**

I tried reproducing this inside a Docker container, but I wasn't able to. I'd be happy to give any other information that is helpful.

**Notes**

Output of `cargo version`:

Operating system - Garuda Linux

$ cargo version
cargo 1.50.0

$ rustup toolchain list
stable-x86_64-unknown-linux-gnu
nightly-2021-03-01-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default) (override)

**Comment by ehuss** [comment]
Do you maybe have a [directory override](https://rust-lang.github.io/rustup/overrides.html#directory-overrides) or `RUSTUP_TOOLCHAIN` env var set?  Those take precedence over the rust-toolchain fail (see https://rust-lang.github.io/rustup/overrides.html).

**Comment by ehuss** [comment]
Oh, I also think `rustup show` will tell you why it is picking a particular toolchain.

**Comment by AngelOnFira** [comment]
The only Rust env vars I have set up are:
```
$ env | grep RUST
RUSTFLAGS=-C target-cpu=native
RUST_BACKTRACE=1
```

With rustup show I get:

```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/forest/.rustup

installed toolchains
--------------------

nightly-2021-01-01-x86_64-unknown-linux-gnu (default)
nightly-2021-03-01-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/forest/Documents/git/veloren')
rustc 1.52.0-nightly (f98721f88 2021-03-10)
```

I even went and removed the stable toolchain, but got the same result.

**Comment by ehuss** [comment]
Maybe check that the `cargo` executable is the rustup wrapper.  Run `which cargo` and make sure it is `~/.cargo/bin/cargo`.  You may have another installation of `cargo` coming from some other directory in your PATH.

**Comment by ehuss** [comment]
Without more information I'm going to close this issue.  If you have further issues with using rustup or setting up overrides, I suggest trying one of the [user forums](https://users.rust-lang.org/) or chat platforms for help. Rustup also has its own issue tracker at https://github.com/rust-lang/rustup/issues.
