### ISSUE TITLE
A rustc error may be related to the cargo

### ISSUE THREAD

**Issue by wfxr** [rust-lang/cargo#9258]
**Problem**

Compiler panics on macos after I did some refactors on Cargo.toml: 
```
thread 'rustc' panicked at 'Failed to get crate data for crate22', compiler/rustc_metadata/src/creader.rs:136:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (4a8b6f708 2021-03-11) running on x86_64-apple-darwin

note: compiler flags: -C opt-level=3 -C linker-plugin-lto -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `clitrans`

To learn more, run the command again with --verbose.
Error: Process completed with exit code 101.
```

Details can be found in this CI report (Note Windows and Ubuntu target were both built successfully):
https://github.com/wfxr/clitrans/runs/2091606690

I reported this error to the rustc (https://github.com/rust-lang/rust/issues/83045) but it seems to be related to cargo so I also report it here.

**Steps**

https://github.com/wfxr/clitrans/commit/57ca835c2e009168f29e21208c3b01a9cc1809bd

Sorry I don’t have a macos computer at the moment so it's hard to debug which is the exactly change caused this error.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

```
toolchain: nightly-x86_64-apple-darwin (default)
cargo 1.52.0-nightly (970bc67c3 2021-03-07)
rustc 1.52.0-nightly (4a8b6f708 2021-03-11)
```

**Comment by ehuss** [comment]
Thanks for the report!  ICE is a `rustc` issue, so it is correct to file it in rust-lang/rust.  It's best to only file one issue.  If it is in the wrong repository, someone will move it for you.  Closing for https://github.com/rust-lang/rust/issues/83045.
