### ISSUE TITLE
cargo test --target x86_64-unknown-linux-gnu --target i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by Kissadas** [rust-lang/cargo#9259]
**Problem**

**Steps**

1.
2.
3.

**Possible Solution(s)**

**Notes**

Output of `cargo version`:

**Comment by Kissadas** [comment]
cargo test --target x86_64-unknown-linux-gnu --target i686-unknown-linux-gnu

**Comment by ehuss** [comment]
@Kissadas did you mean to open an issue here?
