### ISSUE TITLE
`--no-default--features` doesn't work with package in workspace

### ISSUE THREAD

**Issue by CfirTsabari** [rust-lang/cargo#9266]
**Problem**

Using `--no-default--features` when building a package in a workspace doesn't work.

**Steps**
run this unit test:
```rust
#[cargo_test]
fn build_no_default_features_workspace() {
    let p = project()
        .file(
            "Cargo.toml",
            r#"
                [package]
                name = "foo"
                version = "0.0.1"
                authors = []
                [workspace]
                members = [
                    "a",
                ]
            "#,
        )
        .file("a/src/lib.rs", "")
        .file("src/lib.rs", "")
        .file(
            "a/Cargo.toml",
            r#"
                [package]
                name = "a"
                version = "0.0.1"
                authors = []

                [features]
                default = ["a"]
                a = []
            "#,
        )
        .build();

    p.cargo("build --verbose --no-default-features -p a").with_stderr_does_not_contain(r#"[..]--cfg 'feature="default"'[..]"#).run();

}

```

**Possible Solution(s)**

**Notes**

Output of `cargo version`:
i used the current master i don't know how to get version

**Comment by ehuss** [comment]
Hi, thanks for writing the unittest.  I believe this is expected behavior.  The feature flags only apply to the package in the current working directory (it ignores `-p` flags).  If you add `resolver="2"` in the `[workspace]` section (available in beta), it will enable the new feature resolver which does not have that behavior.

More information can be found here: https://doc.rust-lang.org/nightly/cargo/reference/features.html#resolver-version-2-command-line-flags

**Comment by CfirTsabari** [comment]
hi, @ehuss I thought it should work since if i change a bit the test it does work:
```rust
#[cargo_test]
fn build_no_default_features_workspace_no_root() {
    let p = project()
        .file(
            "Cargo.toml",
            r#"
                [workspace]
                members = [
                    "a",
                ]
            "#,
        )
        .file("a/src/lib.rs", "")
        .file(
            "a/Cargo.toml",
            r#"
                [package]
                name = "a"
                version = "0.0.1"
                authors = []

                [features]
                default = ["a"]
                a = []
            "#,
        )
        .build();

    p.cargo("build --verbose --no-default-features -p a").with_stderr_does_not_contain(r#"[..]--cfg 'feature="default"'[..]"#).run();

}

```

**Comment by ehuss** [comment]
In the root of a virtual workspace, it works because there is no ambiguity because there is no package in the cwd.  More information about this change can be found at https://github.com/rust-lang/rfcs/blob/master/text/2957-cargo-features2.md#new-command-line-behavior
