### ISSUE TITLE
CLI parsing regression between 1.48.0 and 1.49.0

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#9267]
I recently received https://github.com/rustwasm/wasm-bindgen/pull/2490 as a bug report but it looked suspicious to me. Turns out the parsing for CLI arguments has changed between 1.48.0 and 1.49.0, which may have broken old build scripts! I'm not sure if this was intentional but I suspect it wasn't, so I figured I'd open an issue.

**Comment by ehuss** [comment]
I suspect this is due to #8808?

**Comment by alexcrichton** [comment]
Hm yeah that does look like a likely culprit :(

**Comment by Eh2406** [comment]
I will Close as won't fix. This was a braking change, but the new behavior is on stable for a while. So it will also be a braking change to go back, and we mostly like the new way thing work. If you disagree feel free to comment or reopen.
