### ISSUE TITLE
Tracking Issue for `-Z patch-in-config`

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#9269]
**Summary**

Original issue: https://github.com/rust-lang/cargo/issues/5539
Implementation: https://github.com/rust-lang/cargo/pull/9204
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#patch-in-config

The `-Z patch-in-config` flag enables the use of `[patch]` sections in cargo configuration files (`.cargo/config.toml`).

**Unresolved issues**

None known.

**Future extensions**

None known.

**Comment by jonhoo** [comment]
Documentation for feature in https://github.com/rust-lang/cargo/pull/9270

**Comment by jonhoo** [comment]
I'm trying to figure out the best way for me to test this feature, since I don't want to change cargo/rustc we use internally to be nightly, as it might cause developers to start adopting experimental features. I wonder, is there a way to use a cargo `-Z` feature on beta/stable specifically for this kind of testing? I'd like to be able to opt into _just_ one feature rather than all of them, but "all" cargo features would probably also be fine. I'm thinking something like `-Zallow-Zs` :p

Alternatively, is there an "inverse" of `RUST_BOOTSTRAP` to disallow the use of nightly-only features on nightly? 😅

**Comment by alexcrichton** [comment]
I believe there's an `[unstable]` table in `.cargo/config.toml` which can globally enable nightly features, and then if you use nightly Cargo you should be able to use the feature without any opt-in anywhere else

**Comment by jyn514** [comment]
> Alternatively, is there an "inverse" of RUST_BOOTSTRAP to disallow the use of nightly-only features on nightly? sweat_smile

I've suggested adding `RUSTC_BOOTSTRAP=0` in the pass (a little whimsically, but I think the idea is good). https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Require.20users.20to.20confirm.20they.20know.20RUSTC_.E2.80.A6.20compiler-team.23350/near/212978290

**Comment by joshtriplett** [comment]
I would *love* to have a mechanism to prevent the use of nightly features, regardless of compiler branch. That'd be helpful, for instance, if using nightly for toolchain reasons (needing specific options or optimizations or targets), but not wanting to make code depend on nightly.

**Comment by jonhoo** [comment]
Ah, so, I specifically want to disallow all unstable features _except one_, since I want the ability to test a particular feature without opening the floodgates to all the others.

**Comment by jonhoo** [comment]
I started an internals discussion over in https://internals.rust-lang.org/t/mechanism-for-beta-testing-unstable-features/14280 for those interested in that line of discussion :)

**Comment by jonhoo** [comment]
I can report that I've been using this to great success in a fairly large internal developer ecosystem for a while now. What kind of evidence report would be helpful to the Cargo team to aid in making a stabilization decision?

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/cargo meeting. We felt like, for this feature, the signal that you've used this extensively in a large internal developer ecosystem is enough of a proof point.

We did have one concern that we felt needs addressing before this stabilizes: it sounds like a `[patch]` in `Cargo.toml` takes precedence over one in `.cargo/config.toml`, whereas in most cases, `.cargo/config.toml` takes precedence over `Cargo.toml`. We'd like to be consistent there. Could you make `.cargo/config.toml` consistently take precedence?

Other than that, we think this can be stabilized, and we'd welcome a stabilization PR.

Separately, and *not* as a blocker from this: it would be nice if `cargo publish` ignored a variety of configuration bits that would make others unable to reproduce your build, including `patch`, `rustflags`, `rustc`, and similar. If you have the bandwidth, we'd really appreciate a PR implementing that. Please? :smile:

**Comment by jonhoo** [comment]
Exciting! Done in https://github.com/rust-lang/cargo/pull/9839.

That would be a really good change, though given that I don't actually use `cargo publish` for said internal ecosystem, it's not clear that I'm the right person to do it 😅 In fact, in my situation (for just `cargo package`, which I _do_ use), I would explicitly _want_ to continue using the patches and other config, because the overarching build system ensures that the same configuration options _are_ set for any consumer that wants to build.

**Comment by ehuss** [comment]
Sorry, I don't think I expressed my concern about publishing clearly.  There are a few concerns here:

* If you have a config file with `[patch]` inside a binary package, and you publish it, I believe it will continue to use those patches. That would be a sort of runaround of the stability guarantees of crates.io whereby you can depend on crates from anywhere.  I haven't tested that, but I believe that is what would happen.  I think that is probably something we would want to prevent.

* A lesser concern is that if you have `[patch]` in `~/.cargo/config`, and you run `cargo publish` (or `cargo package`), the verification step will use those patches.  However, the published package will not have those patches, so it may fail when other users try to use it.  I'm less concerned about this, since it unlikely to happen in practice, and if it does, the author can just publish a fixed version.

**Comment by jonhoo** [comment]
I believe this can now be closed since the feature has landed?

**Comment by ehuss** [comment]
Indeed, thanks @jonhoo!

**Comment by matanox** [comment]
Thanks for the dependency patch feature. 

It would be nice to somehow make patching transitive across a hierarchy of dependencies which patch to one another.

Imagine these dependencies of the following crates

Crate A : B
Crate B : C

Now if A patches B and B patches C, things get brittle:

- A needs to explicitly patch C, if it wants to use crate B with B's patch of C.
- This may not be the desired behavior in some developer cases.

In other words, making patching transitively apply without requiring _explicit configuration at the topmost crate of the chain_ ― can be a useful thing IMHO.  It comes up in putting together configuration for cloud environments (CI, AI Agent) v.s. local development hinging on patching local environments to use patches.

The cost of explicit configuration of the chain of transivitiy in the topmost crate, is that it's brittle to manage across the lifecycle of the crates: you add a dependency as patched in B, then you need to manually patch it in A. This gets brittle in several ways.

# Possible Alternative Suggestions

## Relax a scenario-related warning
I have mentioned an easy way out in https://github.com/rust-lang/cargo/issues/11782 ― introducing the ability to suppress a related warning like mentioned there, can make it sufficient to apply a global/shared config with all patches ― patch transitivity is thus accomplished for all crate workspaces using that shared config, if the warning can be suppressed by configuration.

## Introduce some affordance making the patching resolve transitively: 

When A is being built while patching B, it would pick up B's patch from B's active configuration and that patch would take effect too for that build of A. Currently that does not happen. 

# Related Features
There's a similar "paths" affordance to consider in all this I guess, which is somewhat parallel to the patch affordance in many ways.

---

I am placing this here as nearest to the design document of the patch theme, I hope it's fine. Thanks in case you find this use case relevant.
