### ISSUE TITLE
Cargo compiled with wasm32-wasi as host

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/cargo#9287]
**Describe the problem you are trying to solve**

Have a version of cargo and rustc compiled to wasm32-wasi (or some other wasm arch) such that they can securely/reproducably be run cross-platform/cross-arch even if compiling malicious code.

**Describe the solution you'd like**

Maybe this can be done by having an alternate host ABI that includes posix_spawn as one of the provided functions? Maybe cargo could be changed to add a configure option to not require pthread_create or equivalent?
**Notes**

WASI doesn't currently have create_thread or posix_spawn functions iirc...posix_spawn is much easier to implement.
iirc someone got rustc to work with wasm as the host arch, I wasn't able to find it again when I looked later.

**Comment by programmerjake** [comment]
WASI posix_spawn: https://github.com/WebAssembly/WASI/issues/414

**Comment by alexcrichton** [comment]
Thanks for the report, but Cargo fundamentally, as you've seen, spawns subprocesses which isn't supported with WASI yet. Furthermore Cargo does a lot of network traffic and pipe managment with subprocesses, so WASI has a bit of aways to go I think before it can support Cargo.

**Comment by programmerjake** [comment]
What would you consider the minimal additions to WASI to allow cargo to work (perhaps with some modifications to avoid threads)?

My guess:
posix_spawn
pipe
proc_wait (or async equivalent)
