### ISSUE TITLE
error: failed to select a version for `hidapi`.

### ISSUE THREAD

**Issue by ndcroos** [rust-lang/cargo#9294]
**Problem**

I am trying to add the crate 'hidapi' to my project, but I have a dependency issue. I don't know how to resolve this.

When I execute cargo build, I get the following:

```
$ cargo build
    Updating crates.io index
error: failed to select a version for `hidapi`.
    ... required by package `ledger-transport-hid v0.8.0`
    ... which is depended on by `ledger-transport v0.8.0`
    ... which is depended on by `test-ledger-rs v0.1.0 (/home/nick-test/test-ledger-rs2)`
versions that meet the requirements `^1.2.3` are: 1.2.5, 1.2.3

the package `hidapi` links to the native library `hidapi`, but it conflicts with a previous package which links to `hidapi` as well:
package `hidapi v0.5.2`
    ... which is depended on by `ledger v0.2.5`
    ... which is depended on by `test-ledger-rs v0.1.0 (/home/nick-test/test-ledger-rs2)`
```

When I change the hidapi versio, the error remains.

**Steps**

1. Add the following to the Cargo.toml file:

ledger = "0.2.5"
ledger-transport-hid = "0.8.0"
ledger-apdu = "0.8.0"
ledger-transport = "0.8.0"
hidapi = "0.5.2"

2. Execute cargo build

3. Eventually, change hidapi to other versions that meet the requirements.

**Notes**

Output of `cargo version`: cargo 1.49.0 (d00d64df9 2020-12-05)

I am working on Debian 10.

**Comment by Eh2406** [comment]
Indeed they are not compatible.
[ledger](https://crates.io/crates/ledger/0.2.5/dependencies) depends on `= 0.5.2`  of hidapi and
[ledger-transport-hid](https://crates.io/crates/ledger-transport-hid/0.8.0/dependencies) depends on `^1.2.3`  of hidapi.
So you will need to find versions that are intended to work together. It looks like there is no version of ledger-transport-hid without that requirement, so as someone that dose not know the libraries, I don't know what to advice.

**Comment by ehuss** [comment]
Leaving open to perhaps extend the error message with a little more information.  I'm thinking a note after the error that maybe says something like the following:

> Only one package in the dependency graph may specify the same `links` value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = 'hidapi'` value. For more information, see <https://doc.rust-lang.org/cargo/reference/resolver.html#links>.
