### ISSUE TITLE
Missing documentation about [env] section

### ISSUE THREAD

**Issue by flxo** [rust-lang/cargo#9296]
**Problem**

With #9175 a new feature landed: 

An `[env]` section in the cargo configuration to pass additional env variables to all program invocations does by `cargo`.

From the PR:
```
[env]
FOOBAR = "Apple"
PATH_TO_SOME_TOOL = { value = "bin/tool", relative = true }
USERNAME = { value = "test_user", force = true }
```

This information is missing in the `Cargo Reference`/`Configuration` section.

**Possible Solution(s)**

Add `[env]` to the [Configuration format](https://doc.rust-lang.org/cargo/reference/config.html#configuration-format) section and to the [Configuration Keys](https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys)

**Comment by ehuss** [comment]
Closing per https://github.com/rust-lang/cargo/pull/9297#issuecomment-805841174.
