### ISSUE TITLE
Specify package to be published with `cargo publish -p ...`

### ISSUE THREAD

**Issue by kaleidawave** [rust-lang/cargo#9303]
**Describe the problem you are trying to solve**

It would be nice if you could specify the specific package to be published when in a workspace. Currently requires `cd`ing in and out

**Describe the solution you'd like**

Similar to `build` and `run` commands a `-p` flag could be used to specify the package

**Notes**

**Comment by ehuss** [comment]
Thanks for opening an issue!  I think this is a duplicate of #7345, so closing in favor of that.
