### ISSUE TITLE
cargo clean and cargo build fails to handle renamed sub-crate in a workspace

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/cargo#9319]
**Problem**
In a workspace, after doing `git mv foo bar` to rename a sub-crate, `cargo build` and `cargo clean` fails to find renamed sub-crate.

what currently happens:

```
$ cargo build
error: failed to read `/Users/me/work/foo/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

$ cargo clean
error: failed to read `/Users/me/work/foo/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

what you expected to happen:

`cargo build`, especially `cargo clean` can find `foo` was renamed to `bar`, and continue to work.

**Steps**
1. create a Cargo workspace, including at least 2 crates, say `app` and `foo`.  The root `Cargo.toml` looks like:

```
[workspace]
members = [
    "app",
    "foo"
]
```
`app` is an application (executable), while `foo` is a library. The structure looks like this:

```
├── Cargo.toml
├── app
│   ├── Cargo.toml
│   ├── src
│   │   ├── main.rs
├── foo
│   ├── Cargo.toml
│   ├── src
│   │   ├── lib.rs
```

2. In the sub-crate `foo`, its `Cargo.toml` looks like this:

```
[package]
name = "foo"
version = "0.1.0"
authors = ["me@gmail.com"]
edition = "2018"
```

3. build the project using `cargo build`. It should succeed.

4. rename `foo` to `bar`:  `git mv foo bar` .

5. modify root `Cargo.toml` to replace `foo` with `bar`.

6. modify sub-crate `Cargo.toml` under `bar/`, to replace `foo` with `bar`.

7. Now run `cargo build` again,  or `cargo clean`.  Will see the errors.

**Possible Solution(s)**
Not a real fix:  remove the project and use git to re-pull the project.

**Notes**
Tried to remove `target/` and remove `Cargo.lock`, did not fix the issue.

Output of `cargo version`:

cargo 1.51.0 (43b129a20 2021-03-16)

**Comment by ehuss** [comment]
Hm, sorry you're running into that problem.  I'm unable to reproduce with the steps given, though.  I tried:

```sh
mkdir ws9319
cd ws9319
cargo new app
cargo new --lib foo
cat <<EOF > Cargo.toml
[workspace]
members = [
    "app",
    "foo"
]
EOF
cargo build
mv foo bar
sed -i -e 's/foo/bar/g' Cargo.toml
sed -i -e 's/foo/bar/g' bar/Cargo.toml
cargo build
```

The last step successfully built `bar`.

Do you maybe have a `path` dependency on `foo` somewhere in the workspace?

The error message definitely could be better here.

**Comment by keepsimple1** [comment]
Thank you for your quick response.  Could you please try to add the following and see if the error happens? i.e. use `foo` from `app` : 

```
$ cat <<EOF >> app/Cargo.toml
> foo = { version = "0.1", path = "../foo" }
> EOF

$ cat <<EOF > foo/src/lib.rs
> pub fn lib_hello() {
>     println!("hello from lib");
> }
> EOF

$ cat <<EOF > app/src/main.rs
> fn main() {
>     println!("Hello, world!");
>     foo::lib_hello();
> }
> EOF

```

Thanks!

**Comment by ehuss** [comment]
Yea, if there is a dependency `foo = { version = "0.1", path = "../foo" }`, then when the directory is moved, the path in the dependency will also need to be updated to `bar = { version = "0.1", path = "../bar" }`.

It would be good if the error message pointed to where that dependency is defined.

**Comment by keepsimple1** [comment]
you are right, my bad, I missed that.  Will close this. Thanks!

**Comment by ehuss** [comment]
If you don't mind, I'm going to reopen this to track improving the error message.

**Comment by keepsimple1** [comment]
Of course I don't mind. That will be great to improve the error message. Thanks!
