### ISSUE TITLE
warning: spurious network error

### ISSUE THREAD

**Issue by hello350** [rust-lang/cargo#9335]
Hello, I keep getting this message:

warning: spurious network error (2 tries remaining): failed to read data: The server returned an invalid or unrecognized response
; class=Os (2)

I tried:
- Using another machine
- Using another OS
- Disabling firewall
- Reinstalling rust
- Deleting my entire machine (hard reset)
but it doesn't work

This is my Cargo.toml file
[package]
name = "game1"
version = "0.1.0"
authors = ["name"]
edition = "2018"

[dependencies]
bevy = "0.5"

literally, what?
Updating crates.io index
warning: spurious network error (2 tries remaining): failed to read data: The server returned an invalid or unrecognized response
; class=Os (2)
warning: spurious network error (1 tries remaining): failed to read data: The server returned an invalid or unrecognized response
; class=Os (2)
error: failed to get bevy as a dependency of package game1 v0.1.0 (C:\Users\myname\Desktop\Files\game1)

Caused by:
  failed to load source for dependency bevy

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch https://github.com/rust-lang/crates.io-index

Caused by:
  failed to read data: The server returned an invalid or unrecognized response
  ; class=Os (2)
this is the full error message

Keep in mind that I disabled firewall, I have no proxy (I checked) and no VPN. I also read posts https://github.com/rust-lang/cargo/issues/6513 and https://github.com/rust-lang/cargo/issues/3750 but they didn't help. This isn't a problem with my machine, nor my network. What is this? Is there a fix?

**Comment by Eh2406** [comment]
I think we have issues where libgit2 cant work on IPv6. @ehuss do I remember that correctly? It may be worth trying with the [`git-fetch-with-cli = true`](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli) set.

**Comment by hello350** [comment]
Fixed it, by adding 
`[net] 
git-fetch-with-cli = true`
in `C:\Users\my_name\.cargo\config`

**Comment by cryptopaiyan** [comment]
> 

can you explain it with more details or any photos i'm new to it

**Comment by 6542javed** [comment]
In my case adding `[net]  git-fetch-with-cli = true` was not enough. I had to increase buffer size as well by running this command `git config --global http.postBuffer 524288000`
