### ISSUE TITLE
Get structured cargo config info

### ISSUE THREAD

**Issue by Undin** [rust-lang/cargo#9342]
I want to get `target` info defined in cargo config to improve IDE support (in my case it's about IntelliJ Rust plugin but I suppose it may be useful for any IDE integration). More precisely, I want to fetch correct info about cfg options from the compiler if a user uses some specific target to compiler the project to provide the corresponding highlighting, name resolution and other code insight features that may depend on cfg options. For example, see https://github.com/intellij-rust/intellij-rust/issues/5183.

According to https://doc.rust-lang.org/cargo/reference/config.html, config file may be placed not only in project dir but also in parent directories. Moreover, some specific options can be overridden by environment variables. And all this logic is already implemented in cargo and will be updated in the future if rules about config files are changed.
So, **question**: is there a way to get structured output about cargo config from cargo (or at least, info about target) not to re-implement described logic in the plugin?

If it's not possible for now, what's the best place for it? A separate command (something like `cargo config`), `cargo metadata` or anything else?

**Comment by Undin** [comment]
CC @ehuss

**Comment by ehuss** [comment]
Sorry, I'm a bit confused about the discussion of config files and how that relates to target `cfg` values.

On nightly, you can use `cargo rustc --print cfg` to display cfg values from the compiler.

**Comment by Undin** [comment]
> Sorry, I'm a bit confused about the discussion of config files and how that relates to target cfg values.

Sorry if the question was not clear. We want to support cases when a project is supposed to be built with a non-host target.
One subtask is to evaluate `cfg` attributes according to target option to provide proper name resolution, completion, etc.
To do it, we need to retrieve the corresponding info from some source. Here there are a lot of implementation variants but we want to support the existing one (Cargo config) not to introduce a new entity for users. Hence, we need to get info from Cargo config somehow.

> On nightly, you can use `cargo rustc --print cfg` to display cfg values from the compiler.

Yeah and it actually takes into account cargo config. But unfortunately, this command requires you to pass the concrete target if there are several ones and compiles it. The latest thing makes this option unusable for us because it may require a lot of time and may fail because of different reasons.
So it would be great to get config info without project compilation.

**Comment by ehuss** [comment]
>  this command requires you to pass the concrete target if there are several ones and compiles it.

That command shouldn't trigger a compile.  It should print something like the following and exit immediately.  Are you not seeing that?

```
~/Temp/z1> cargo +nightly rustc --print=cfg -Zunstable-options
debug_assertions
panic="unwind"
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_has_atomic_equal_alignment="16"
target_has_atomic_equal_alignment="32"
target_has_atomic_equal_alignment="64"
target_has_atomic_equal_alignment="8"
target_has_atomic_equal_alignment="ptr"
target_has_atomic_load_store="16"
target_has_atomic_load_store="32"
target_has_atomic_load_store="64"
target_has_atomic_load_store="8"
target_has_atomic_load_store="ptr"
target_os="linux"
target_pointer_width="64"
target_thread_local
target_vendor="unknown"
unix
```

**Comment by Undin** [comment]
Oh, looks awesome!
Actually, I ran `cargo rustc -- --print cfg` because I knew that it worked and thought that you just missed `--` in command. And `cargo rustc -- --print cfg` tries to compile the target.
But with nightly toolchain `cargo rustc --print cfg` works as expected and it's an answer to my initial question (and in fact it's a duplicate of #8923). Thanks!

Some questions about the feature itself:
- Do I understand correctly that the option will be released in 1.52?
- Are there plans to stabilize it?

**Comment by ehuss** [comment]
It is a part of 1.52, but is unstable so should only be used on nightly.

No particular plans right now. I opened #9357 for more discussion.

**Comment by Undin** [comment]
@ehuss Thank you!
I think this issue can be closed then
