### ISSUE TITLE
Optional name other than Cargo.toml ?

### ISSUE THREAD

**Issue by stormasm** [rust-lang/cargo#9345]
**Describe the problem you are trying to solve**
Make has a way to pass a -f flag to give any Makefile name

**Describe the solution you'd like**
Does it make sense for cargo to allow file names other than Cargo.toml ?

**Notes**
If this question or Feature request has already been asked for thanks for just letting
me know and closing this issue...

**Comment by stormasm** [comment]
In thinking about this request further it seems to me that its probably not worth the extra added complexity of having more code to maintain within the cargo eco-system as well as the thing that I like about cargo which is the fact that it does not have a lot of extra added functionality and features...

Thanks for confirming this....

**Comment by Eh2406** [comment]
I can't find a citation at the moment, but Yes this lack of flexibility is intended. A Cargo project will use a Cargo.toml and it will have that name. This was done to make it more straight forward to understand a new project. It would take a rely good argument to convince us to allow more complicated system.

**Comment by stormasm** [comment]
Thank you, I appreciate the simplicity of cargo...
