### ISSUE TITLE
`cargo fmt` has `--all` option but not `--workspace` like other commands

### ISSUE THREAD

**Issue by jplatte** [rust-lang/cargo#9347]
**Problem**

The `--all` option for cargo commands was soft-deprecated in favor of the `--workspace` option, which does the same thing. It seems like this same thing was not done for `cargo fmt`, which still only has `--all` as an option to run it on all workspace packages.

**Steps**

1. run `cargo fmt --workspace`
2. observe `error: Found argument '--workspace' which wasn't expected, or isn't valid in this context`

**Possible Solution(s)**

Introduce `--workspace` flag for `cargo fmt`.

**Notes**

Latest version I currently have installed is `cargo 1.52.0-nightly (90691f2bf 2021-03-16)`, I can't update right now; sorry if this already got fixed.

**Comment by weihanglo** [comment]
cargo-fmt is bundled with rustfmt as a thin cargo subcommand. Maybe we can move this issue there.
 
https://github.com/rust-lang/rustfmt/blob/a9876e8/src/cargo-fmt/main.rs#L58-L60

**Comment by jplatte** [comment]
Moving the issue requires somebody with high enough privileges on both repos, right? Or do you just mean close this issue and open a new one on rustfmt?

**Comment by weihanglo** [comment]
I have no privileges neither 🙂. The latter is much more easier for us.

**Comment by jplatte** [comment]
Turns out there were already several issues about it, and they got closed because `cargo fmt` already affects the entire workspace without any options. `--all` is for path-based deps outside the workspace, which seems like a weird feature but whatever.

For more info, see https://github.com/rust-lang/rustfmt/issues/3911.
