### ISSUE TITLE
`cargo build -Z help` is missing options

### ISSUE THREAD

**Issue by jyn514** [rust-lang/cargo#9350]
**Problem**
`cargo build -Z help` should show all available unstable options. Instead, it's missing at least `-Z build-std` and `-Z build-std-features`.

**Steps**

1. `cargo build -Z help`

```
Available unstable (nightly-only) flags:

    -Z avoid-dev-deps      -- Avoid installing dev-dependencies if possible
    -Z extra-link-arg      -- Allow `cargo:rustc-link-arg` in build scripts
    -Z minimal-versions    -- Install minimal dependency versions instead of maximum
    -Z no-index-update     -- Do not update the registry, avoids a network request for benchmarking
    -Z unstable-options    -- Allow the usage of unstable options
    -Z timings             -- Display concurrency information
    -Z doctest-xcompile    -- Compile and run doctests for non-host target using runner config
    -Z terminal-width      -- Provide a terminal width to rustc for error truncation
    -Z namespaced-features -- Allow features with `dep:` prefix
    -Z weak-dep-features   -- Allow `dep_name?/feature` feature syntax
    -Z patch-in-config     -- Allow `[patch]` sections in .cargo/config.toml files

Run with 'cargo -Z [FLAG] [SUBCOMMAND]'

See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html for more information about these flags.
```

**Possible Solution(s)**
Autogenerate `-Z help` from the unstable options somehow (maybe look how rustc does it?), so it isn't possible to forget to update it.

**Notes**

Output of `cargo version`: cargo 1.53.0-nightly (3c44c3c4b 2021-03-31)

**Comment by weihanglo** [comment]
Hmmm.... rustc uses its ad-hoc options macro to generate those flags.
https://github.com/rust-lang/rust/blob/c18c0ad2/compiler/rustc_session/src/options.rs#L886-L1221

**Comment by jyn514** [comment]
Sure, you could copy the macro from rustc and modify it for cargo.

**Comment by PicoJr** [comment]
It should be possible to generate _most_ of `cargo build -Z help` content automatically.
IMO the help message still has to be written by a human at some point though.

Maybe the help message for each option can be derived in a similar way as [thiserror](https://crates.io/crates/thiserror) derives error messages?

```rust
#[derive(Help)]
pub struct CliUnstable {
   // ...
   #[help("Allow *only* the listed unstable features")]
   pub allow_features: Option<BTreeSet<String>>,
    // ...
```

cf https://github.com/rust-lang/cargo/blob/master/src/cargo/core/features.rs#L548-L585

**Comment by PicoJr** [comment]
I'm working on it, it's time to learn about derive macros!

**Comment by ehuss** [comment]
I would suggest not using a derive or proc-macro.  That would add some undesired weight for a relatively obscure part of the code.  A regular macro_rules macro may be fine as long as it is not too complicated.

**Comment by ehuss** [comment]
Oh, and if you have any questions or need any guidance, let me know.  (Here or on Zulip whichever you prefer.)

**Comment by PicoJr** [comment]
@ehuss thanks, you are probably right derive macros might be overkill for this situation, I'll write a macro_rules instead.
Yes I'd be happy to ask questions, I'm completely inexperienced when it comes to macros and It would be nice to share with you on Zulip (just registered a minute ago).

**Comment by PicoJr** [comment]
Here is what I've written so far: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=be40772212f24e9728e6adddcc388b4a
