### ISSUE TITLE
Cargo error: failed to join search paths together

### ISSUE THREAD

**Issue by FaresAhmedb** [rust-lang/cargo#9355]
**Problem**
When I run cargo build it shows this error
```
error: failed to join search paths together
Does $LD_LIBRARY_PATH have an unterminated quote character?

Caused by:
  failed to join path array: ["/home/fares/D:/hello_cargo/target/debug/deps", "/home/fares/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib", "/home/fares/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib"]

Caused by:
  path segment contains separator `58`
```

Output of `cargo version`:
cargo 1.51.0 (43b129a20 2021-03-16)

OS: Ubuntu 18.04

Edit: I didn't know the directory name will be the problem so I removed it from the project path while writing the issue I tried making a new project in $HOME and the program built was successful
I think the problem was the Colon in D: was a problem

**Comment by ehuss** [comment]
Hm, that's really strange!  I'm racking my brain trying to figure out how that could possibly happen, since the paths shown clearly don't have a colon in them.  Sorry, I don't have any ideas, but maybe someone else does.  If you're comfortable with running a debugger, you can try building a debug build of cargo locally ([docs](https://github.com/rust-lang/cargo/#compiling-from-source)) and setting a breakpoint on the [`join_paths`](https://github.com/rust-lang/cargo/blob/57c512b3dfc47a6fc62d978313ec4eac7757f6de/crates/cargo-util/src/paths.rs#L20-L33) function and step through and see why it is failing.

**Comment by FaresAhmedb** [comment]
@ehuss 
> Hm, that's really strange! I'm racking my brain trying to figure out how that could possibly happen, since the paths shown clearly don't have a colon in them. Sorry, I don't have any ideas, but maybe someone else does. If you're comfortable with running a debugger, you can try building a debug build of cargo locally ([docs](https://github.com/rust-lang/cargo/#compiling-from-source)) and setting a breakpoint on the [`join_paths`](https://github.com/rust-lang/cargo/blob/57c512b3dfc47a6fc62d978313ec4eac7757f6de/crates/cargo-util/src/paths.rs#L20-L33) function and step through and see why it is failing.

Hi thanks for your reply! I tried compiling from source and set a breakpoint in cartes/cargo-util/src/path.rs 
```rust
//! Various utilities for working with files and paths.

use anyhow::{Context, Result};
use filetime::FileTime;
use std::env;
use std::ffi::{OsStr, OsString};
use std::fs::{self, File, OpenOptions};
use std::io;
use std::io::prelude::*;
use std::iter;
use std::path::{Component, Path, PathBuf};
use tempfile::Builder as TempFileBuilder;
#![feature(asm)]
#[macro_use] extern crate breakpoint;

/// Joins paths into a string suitable for the `PATH` environment variable.
///
/// This is equivalent to [`std::env::join_paths`], but includes a more
/// detailed error message. The given `env` argument is the name of the
/// environment variable this is will be used for, which is included in the
/// error message.
pub fn join_paths<T: AsRef<OsStr>>(paths: &[T], env: &str) -> Result<OsString> {
    env::join_paths(paths.iter())
        .with_context(|| {
            let paths = paths.iter().map(Path::new).collect::<Vec<_>>();
            format!("failed to join path array: {:?}", paths)
        })
        .with_context(|| {
            format!(
                "failed to join search paths together\n\
                     Does ${} have an unterminated quote character?",
                env
            )
        })
}
breakpoint!();
...
```
however looks like the code I wrote is wrong so it shows this error while compiling
```
A plugin/crate was declared but cannot be found.

Erroneous code example:

A plugin/crate was declared but cannot be found.

Erroneous code example:

   Compiling cargo-util v0.1.0 (/home/fares/cargo/crates/cargo-util)
error: an inner attribute is not permitted in this context
  --> crates/cargo-util/src/paths.rs:13:1
   |
13 | #![feature(asm)]
   | ^^^^^^^^^^^^^^^^
   |
   = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

error[E0463]: can't find crate for `breakpoint`
  --> crates/cargo-util/src/paths.rs:14:14
   |
14 | #[macro_use] extern crate breakpoint;
   |              ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cargo-util`
```
I am new to the language and Im not sure how to put a breakpoint

**Comment by FaresAhmedb** [comment]
I think Cargo couldn't build because of the Colon in D:
When I made a new project in $HOME the program built successfully
