### ISSUE TITLE
junit support

### ISSUE THREAD

**Issue by tschuett** [rust-lang/cargo#9360]
It would be great if `cargo test` could output the result as an junit xml file.

There are some hacks like https://github.com/CWood1/cargo-junit, but integrated support would be awesome.

**Comment by ehuss** [comment]
Thanks for the suggestion!  The test output is driven by libtest, also known as the test harness. It already supports JSON on nightly.  There's more discussion of support for formats such as junit at https://github.com/rust-lang/rust/issues/49359, so closing in favor of that.  Also, [custom test frameworks](https://github.com/rust-lang/rust/issues/50297) are another approach for supporting junit output via a custom runner.
