### ISSUE TITLE
cargo new doesn't write authors info to Cargo.toml file

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/cargo#9366]
**Problem**

I'm using the nightly version cargo 1.53.0-nightly (65d57e6f3 2021-04-04), and use it to create a new rust project, but it doesn't write the authors info to Cargo.toml file.
I've tried using the stable version cargo 1.51.0 (43b129a20 2021-03-16), it writes authors info correctly

**Steps**

1. `cargo new abc`
2. `cat abc/Cargo.toml`

Output of `cargo version`:

cargo 1.53.0-nightly (65d57e6f3 2021-04-04)

**Comment by ehuss** [comment]
Hi!  This change was a result of [RFC 3052](https://github.com/rust-lang/rfcs/blob/master/text/3052-optional-authors-field.md).  You can still manually add the `authors` field, but it won't be added automatically anymore. The RFC contains some information on the motivation.

**Comment by Sherlock-Holo** [comment]
I read the rfc but I don't find a way to make cargo still add the authors info. Is there any way to make it possible？

**Comment by ehuss** [comment]
No, you will need to add it manually.
