### ISSUE TITLE
Cargo does not strip the name of a custom cargo command from the argument list

### ISSUE THREAD

**Issue by mfdorst** [rust-lang/cargo#9373]
**Problem**

I'm building a little tool called `cargo-latest` which will just print out the latest version of any crates you pass to it. E.g.
```
$ cargo-latest serde thiserror anyhow
serde = "1.0.125"
thiserror = "1.0.24"
anyhow = "1.0.40"
```
Unfortunately, when I run it as `cargo latest serde` I get
```
latest = "0.1.1"
serde = "1.0.125"
```
It seems that cargo does not strip `latest` from the argument list, like I assumed it would. Unfortunately in my case I can't find a good way around this since `latest` is a valid crate name (and is in fact the name of a real crate), so I can't just check for it and strip it out if I want the following commands to both work: `cargo-latest latest` and `cargo latest latest`.

**Possible Solution(s)**

I don't know if this behavior is intended or not. If it is the intended behavior then it would be good to have some sort of workaround for programs like mine. If there was some way to check if the program was called directly vs through cargo (maybe there already is?) then a workaround would be possible. If it is not the intended behavior then I think the solution is self explanatory.

**Notes**

Output of `cargo version`: `cargo 1.51.0 (43b129a20 2021-03-16)`

**Comment by ehuss** [comment]
It is intended behavior to provide a way for subcommands to know which command is being run.

It may not be reliable, but you can check if the "CARGO" environment variable is set to determine if it is being launched by cargo. This may be a false positive if "CARGO" is set by something else. Otherwise there currently isn't a way to differentiate.

**Comment by mfdorst** [comment]
@ehuss sounds like a good enough work around for me. Thanks.
