### ISSUE TITLE
Cargo publish --manifest-path ... does not work when called from different directory

### ISSUE THREAD

**Issue by sebschmi** [rust-lang/cargo#9377]
**Problem**

When using `cargo publish --manifest-path ...` from a directory that is not related to the manifest's directory, the command fails as follows:

```txt
cargo publish --manifest-path /home/user/git/practical-omnitigs/implementation/traitsequence/Cargo.toml
    Updating crates.io index
   Packaging traitsequence v0.3.1 (/home/user/git/practical-omnitigs/implementation/traitsequence)
   Verifying traitsequence v0.3.1 (/home/user/git/practical-omnitigs/implementation/traitsequence)
error: failed to verify package tarball

Caused by:
  failed to read `/home/user/git/practical-omnitigs/implementation/target/package/traitsequence-0.3.1/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

```

**Steps**

1. Create a workspace of crates at e.g. `/home/you/workspace`
2. Switch to a different directory, e.g. `/home/you/different-directory`
3. Execute `cargo publish --manifest-path /home/you/workspace/crate1/Cargo.toml`

**Possible Solution(s)**

**Notes**

Output of `cargo version`: `cargo 1.51.0 (43b129a20 2021-03-16)`

The bug can also be reproduced with the ´--dry-run´ flag.
I did not test if the bug also occurs without workspace.

**Comment by ehuss** [comment]
Hm, I'm having trouble recreating the problem.

Can you maybe run `cargo package --list --manifest-path /home/user/git/practical-omnitigs/implementation/traitsequence/Cargo.toml` and check that it includes `Cargo.toml`?  Also maybe check the `.crate` file contents with `tar -tzvf /home/user/git/practical-omnitigs/implementation/target/package/traitsequence-0.3.1.crate`.

**Comment by sebschmi** [comment]
I seem to also not be able to reproduce the problem now. Neither with my _Steps_, nor by releasing the same workspace that I released yesterday again.
Not that yesterday, there was no file `/home/user/git/practical-omnitigs/implementation/target/package/traitsequence-0.3.1.crate`, which was very confusing.

But I guess since I am unable to reproduce myself, this can be closed.
