### ISSUE TITLE
Pass cargo subcommand to build scripts

### ISSUE THREAD

**Issue by shlevy** [rust-lang/cargo#9394]
**Describe the problem you are trying to solve**
I'd like to have build scripts behave differently for different subcommands. For example, I'm using an external tool [BNFC](https://bnfc.digitalgrammars.com/) to generate a parser, and it has the ability to also generate a nice PDF describing the language, I'd like to generate that PDF only when running `cargo doc`.

Also would be nice to be able to distinguish `cargo build` and `cargo build --tests`
**Describe the solution you'd like**
Some env var passed from cargo to the build script.

**Comment by Eh2406** [comment]
In the current model, the build script may not even be rerun when switching between those commands. So it may need more changes than just an env var. On the other hand, your use case makes sense and I don't have a good suggestion for you at this time.

**Comment by aviramha** [comment]
Is it okay if I implement it?

**Comment by epage** [comment]
See also #4001

**Comment by epage** [comment]
Closing in favor of #4001.  If there is a reason we should keep this open, let us know!
