### ISSUE TITLE
Add option for trimming prefix path

### ISSUE THREAD

**Issue by Morganamilo** [rust-lang/cargo#9399]
**Describe the problem you are trying to solve**

Currently there's no easy way to trim the path prefix when compiling.

rustc has `--remap-path-prefix ` but this requires you to know the prefix. This is hard to know when using build systems and you can't expect users to have this set when distributing source.

**Describe the solution you'd like**

I believe we should copy Go:

>The new go build flag -trimpath removes all file system paths from the compiled executable, to improve build reproducibility.

With a `trimpath` option in cargo.toml. This would pass `--remap-path-prefix=$CARGO_MANIFEST_DIR=/` to rustc.

This could also perhaps be enabled by default on release builds.

**Notes**

**Comment by Morganamilo** [comment]
I would be interesting in implemented this myself. Some guidance would be appreciated on how to get this accepted, if I need to write an RFC, etc.

**Comment by Morganamilo** [comment]
I've just found #5505, which is basically the problem i'm trying to solve here.

**Comment by Eh2406** [comment]
I will close for now and guide the conversations to continue in #5505 and #9407.
