### ISSUE TITLE
error with `cargo new`: could not find '/git/.git_template/' to stat

### ISSUE THREAD

**Issue by githorse** [rust-lang/cargo#9409]
**Problem**

Rust newbie. I'm seeing a bizarre error right out of the box. Google coming up empty so I guess I'm the only one?

```
$ cargo new hello-rust
error: Failed to create package `hello-rust` at `/home/githorse/hello-rust`

Caused by:
  could not find '/git/.git_template/' to stat: No such file or directory; class=Os (2); code=NotFound (-3)
```
 
**Steps**

I'm following the [Getting Started](https://www.rust-lang.org/learn/get-started) steps:

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ rustup update # just for kicks
$ rustup --version
rustup 1.23.1 (3df2264a9 2020-11-30)
$ cargo --version
cargo 1.51.0 (43b129a20 2021-03-16)
$ cargo new hello-rust 
🤦
```

**Notes**

I don't have a `/git/.git_template` ... is that a thing? I do have a `~/.git_template`. Either way cargo probably should not blow up without it.

Providing the required template does resolve the error:
```
$ sudo mkdir /git
$ sudo ln -s ~/.git_template /git/.git_template
$ cargo new hello-rust
     Created binary (application) `hello-rust` package
```

But again ... why?

**Comment by ehuss** [comment]
Hm, that is strange! Could you try running `git config init.templateDir` and check if it is set to anything?  Or maybe run `git config --list` to see if there are any other config settings that might be changed from the default?

**Comment by githorse** [comment]
Got it in one! Config fail on my part (the path was being set by `$MISSING_VARIABLE_HERE/git/.git_template`). My bad.

Still, maybe Cargo could issue a warning here rather than failing. `git clone` for instance just gives me a warning but doesn't fail. I must have had this issue for a while now (through many installs of different tools) but haven't noticed until now. But probably not a corner case worth worrying about :)
