### ISSUE TITLE
cargo config list/set/get command

### ISSUE THREAD

**Issue by netroby** [rust-lang/cargo#9412]
hello, I want the feature  get config, set, list all config with cargo.

The idea come from golang ,  git cli

for example 
```
> git config --list
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=false
core.fscache=true
core.symlinks=false
core.longpaths=true
pull.rebase=true
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=david
user.email=example@domain.com
gc.autodetach=false
http.https://github.com.proxy=http://localhost:8123
http.https://github.com.sslverify=false
http.https://fuchsia.googlesource.com.proxy=http://localhost:8123
http.https://fuchsia.googlesource.com.sslverify=false
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd=''
mergetool.sourcetree.trustexitcode=true
core.longpaths=true
PS C:\WINDOWS\system32> git config --global user.name "xxx"

```

The cargo has it's configure also, but where is it ?

can we easy to know what's current configure, I f we changed some configure, how do we know it works.

The git command will show exactly result, yes , we change our configure , then `git config --list `

I hope cargo has the same ability.

tell me more about the configuration.

**Comment by Eh2406** [comment]
A `cargo config` command was added in #9302, all though I am not seeing the stabilization plan at the moment.

**Comment by ehuss** [comment]
Yes, this command should be available in the latest nightly.  I updated the tracking issue #9301 with some details, and closing in favor of that.
