### ISSUE TITLE
Using git to manage cargo.io-index may be not good solution.

### ISSUE THREAD

**Issue by netroby** [rust-lang/cargo#9413]
The bad part of git, large space waste( History will growth, and waste user diskspace)
and git does not support continue download, if the download break. their be much more problem with it.

```
warning: spurious network error (2 tries remaining): failed to read data: 服务器返回的信息无效或不可识别
```

**Comment by Eh2406** [comment]
There are meny advantages to the way we use git. Most of the disadvantages we have mitigations for. But there is work being done to build a new way. https://github.com/rust-lang/rfcs/pull/2789
