### ISSUE TITLE
`cargo metadata` panic: unable to get packages from source

### ISSUE THREAD

**Issue by cmichi** [rust-lang/cargo#9417]
**Problem**
`cargo install` fails with "`cargo metadata` can not fail!" and told me to create a bug report here.

I'm using the latest nightlies.

**Steps**
```
cargo install --git https://github.com/paritytech/canvas-node --force --branch cmichi-some-fixes --locked
…
      Finished release [optimized] target(s) in 4m 06s
  thread 'main' panicked at '`cargo metadata` can not fail!: CargoMetadata { stderr: "error: failed to download `sp-maybe-compressed-blob v3.0.0 (https://github.com/paritytech/substrate#8060a437)`

Caused by:
  unable to get packages from source

Caused by:
  failed to find sp-maybe-compressed-blob v3.0.0 (https://github.com/paritytech/substrate#8060a437) in path source
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note:cargo 1.53.0-nightly (0ed318d18 2021-04-23)
" }', /home/michi/.cargo/git/checkouts/substrate-7e08433d4c370a21/8060a43/utils/wasm-builder/src/wasm_project.rs:590:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace               
warning: build failed, waiting for other jobs to finish...
error: failed to compile `canvas-node v0.1.1 (https://github.com/paritytech/canvas-node?branch=cmichi-some-fixes#c6a2da4b)`, intermediate artifacts can be found at `/tmp/cargo-install7wlBRT`
```

**Possible Solution(s)**
A thing that stands out to me is that the package for which this error `unable to get packages from source` appears is referenced by it's relative path [in the `Cargo.toml` here](https://github.com/paritytech/substrate/blob/c93ef27486e5f14696e5b6d36edafea7936edbc8/utils/wasm-builder/Cargo.toml#L24).

**Notes**

Output of `cargo version`:

```
$ rustup show
rustc 1.53.0-nightly (42816d61e 2021-04-24)
$ cargo --version
cargo 1.53.0-nightly (0ed318d18 2021-04-23)
```

**Comment by alexcrichton** [comment]
Thanks for the report! It doesn't look like this panic is coming from Cargo itself but instead from soem external test runner or something like that? Nevertheless this looks like a bug in Cargo still. This looks somewhat complicated, though, would it be possible to isolate the command that its executed to get Cargo to print that this is an unexpected internal error?

**Comment by cmichi** [comment]
@alexcrichton So after upgrading a dependency in the project (the `cargo_metadata` crate) to its latest release the bug disappeared. I suspect some invalid input by this crate to `cargo metadata`.

I guess this should still not result in the internal cargo error, but I wasn't able to isolate the issue and since it's quite hairy to reproduce I'll close this issue for now.
