### ISSUE TITLE
Allow top-level overrides to be stored in the manifest

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cargo#942]
It is quite frequent that a dependency needs to be changed temporarily for various reasons and committed upstream. The `paths` override is not appropriate for this use case because these overrides need to be committed upstream.

Top-level overrides should use the pkgid syntax for determining which dependency should be overridden, and the dependency itself should be encoded into the metadata somehow. Note that the override should also find its way into the lockfile.

**Comment by seanmonstar** [comment]
I'd love something like this to let me use github urls while waiting for someone to publish the crate to crates.io. Needing to clone the repo is tedious, and doesn't scale when I push the PR to Travis.

**Comment by alexcrichton** [comment]
Another note is that the top-level overrides should also allow specifying features to be activated for dependencies as well (so they may not be overridden, just adding new features)

**Comment by jdub** [comment]
Would this resolve #1481?
