### ISSUE TITLE
`cargo install` suggests an unrelated package

### ISSUE THREAD

**Issue by bronson** [rust-lang/cargo#9422]
**Problem**

When I ask Cargo to install cargo-edit from git, it says that I'm being ambiguous and suggests the `two` crate as an alternative.

```txt
$ cargo install --git=https://github.com/killercup/cargo-edit --features vendored-openssl
    Updating git repository `https://github.com/killercup/cargo-edit`
error: multiple packages with binaries found: cargo-edit, two
```

I [downloaded](https://github.com/rust-lang/crates.io/issues/65) the `two` crate and glanced through it... I don't see any reason for Cargo to suggest it.

**Steps**
1. `cargo install --git=https://github.com/killercup/cargo-edit --features vendored-openssl`
2. Notice Cargo's suggestions. On my computer: `cargo-edit, two`

It's true that explicitly stating `cargo-edit` succeeds: `cargo install cargo-edit --git=https://github.com/killercup/cargo-edit --features vendored-openssl`

But, why did Cargo suggest the `two` crate?

**Notes**

Output of `cargo version`: cargo 1.51.0 (43b129a20 2021-03-16)

**Comment by ehuss** [comment]
When installing a git repository, cargo will always search the entire repo for any `Cargo.toml`.  In this case, it is finding https://github.com/killercup/cargo-edit/blob/master/tests/fixtures/workspace/two/Cargo.toml.

The error message could definitely be better (which I think is #9011).

**Comment by bronson** [comment]
Ah! Yes, that's it. I wondered why Cargo was being sloppy with the words `package` and `crate`.

If it had said something like this then I would have understood immediately:

```txt
cargo-edit provides multiple binaries:
  - cargo-edit
  - tests/fixtures/workspace/two/two
Please specify which to install.
```
