### ISSUE TITLE
An error occurred when cargo downloads crates from the standby registry.

### ISSUE THREAD

**Issue by QiangHeisenberg** [rust-lang/cargo#9431]
I built my own private repository using the crates.io project, which took me a lot of time. As it stands, I can upload my own crates. However, an error occurred while running the cargo run.

First I ran cargo new test_li and created a new project.
Here's the content of my cargo.toml:
```
[package]
name = "test_li"
version = "0.1.0"
authors = ["author<email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"       //  from crates.io
test-li = {version = "0.1.0", registry = "my-registry" }    // from  my private  crates.io
```

I had the following error while running cargo run:

```
error: failed to download from `http://crates.inhuawei.com/api/v1/crates/test-wql/0.1.0/download`

Caused by:
  [52] Server returned nothing (no headers, no data) (Empty reply from server)
```

I know there was an error here in the cargo, but I don't know what the root cause of the error was.
https://github.com/rust-lang/cargo/blob/e9e09077a16456664e8ae9266b95dfc97cec4a11/src/cargo/core/package.rs#L790
It seems that something has gone wrong with curl.

/root/.cargo/config.toml:
```
[source.crates-io]
replace-with = 'mirror'
[source.mirror]
registry ="http://mirrors.xxxxxxx.com/rust/crates.io-index/"

[registries]
my-registry = { index = "ssh://git@xxxxxxx.yyyyyyyy/crates.io-index.git" }
```

**Comment by ehuss** [comment]
Can you run cargo with `CARGO_HTTP_DEBUG=true` and `CARGO_LOG=cargo::ops::registry=trace` environment variables set? This should log all the network I/O.  

Also, can you download from that URL manually with the curl command-line?  `curl -O http://crates.inhuawei.com/api/v1/crates/test-wql/0.1.0/download` and check that the contents are what you expect?

**Comment by QiangHeisenberg** [comment]
@ehuss  Thank you very much for your reply, it helped me a lot. After analysis, I discovered the problem. Doesn't seem to be a problem with cartes.io. I type ```https://crates.io/api/v1/crates/rand/0.8.3/download``` in my browser and download rand crates. But I type in ```http://crates.inhuawei.com/api/v1/crates/ok/3.5.0/download``` and it returns ```Oops, that route doesn't exist!```.

If I want to solve this problem, I need to continue researching.

**Comment by QiangHeisenberg** [comment]
As a supplement to the problem, I'm not sure what the problem is and why all of my routes are non-existent.
Includes:
```
http://crates.inhuawei.com/api/v1/me
http://crates.inhuawei.com/api/v1/download
http://crates.inhuawei.com/api/v1/crates/test-li
http://crates.inhuawei.com/api/v1/crates/test-li/0.1.0/authors
......
```
