### ISSUE TITLE
rustdoc: Support building docs for examples

### ISSUE THREAD

**Issue by dalcde** [rust-lang/cargo#9433]
Examples are often documented but said documentation cannot be rendered as far as I can tell. It is especially useful to use top-level documentation to provide usage notes.

From a presentation point of view, they can be treated as extra crates or listed after modules/macros/functions/etc. In the latter case, it would also serve as an enumeration of examples accompanied with short descriptions.

**Comment by ehuss** [comment]
Sure, transferred to rust-lang/cargo.

**Comment by dalcde** [comment]
`cargo rustdoc --examples` seems to do the job. In any case this is a duplicate.
