### ISSUE TITLE
Can't create a package for a library

### ISSUE THREAD

**Issue by abdelmonem17** [rust-lang/cargo#9442]
I have compiler errors when I try to call a cargo package and this is because I use a build script in this library to generate rust code using tonic-build  and prost so I there a way to solve this problem.
Thank you in advance.

**Comment by Eh2406** [comment]
It is hard to figure out how to help without a reproducible example. What are you trying to do? What have you tried? What about it is not working?

Also, given that you where you posted this Why do you think this is a limitation/Bug in Cargo? You may have better luck on a more general forum like users.rust-lang.org

**Comment by abdelmonem17** [comment]
@Eh2406 I have a library with following structure 
.
├── Cargo.toml
├── build.rs
└── src
    └── lib.rs

inside build.rs I use crate to generate some rust code to be used 
//build.rs
```
 tonic_build::configure()
        .build_client(true)
        .build_server(true)
        .compile(&["proto/cluster.proto"], &["proto/"])?;
```
and inside lib.rs I uses the generated code for example
```
pub mod my_mod{

    include!(concat!(env!("OUT_DIR"), concat!("/", "test", ".rs")));

//defined inside test.proto that used to generate test.rs 
impl Color{
}
}
```
so when I run `cargo build` all thigs goes well 
but when I run `cargo package` I have compilation error that Color not found so how to force cargo to use build script inside build.rs .

**Comment by Eh2406** [comment]
Normally the build.rs scrip is run during package, if it is not that would be odd. 
Can you have the build.rs wright a file, or print something, before your call to other code to test if the build.rs is run?
If the build.rs is not being run, that is a bug and you are in the correct place.
If it is running but not outputting what you need...
I don't know anything about `tonic_build`. As I said before "You may have better luck on a more general forum like users.rust-lang.org". 
But I would investigate if the `proto` files got included into your package. Maybe, they were not included, so `tonic_build` did not output anything.

**Comment by abdelmonem17** [comment]
@Eh2406 cargo build succeed but packaging not,
I read "Check that build scripts did not modify any source files."
at [cargo package]( https://doc.rust-lang.org/cargo/commands/cargo-package.html)

**Comment by Eh2406** [comment]
> cargo build succeed but packaging not

Yes you have said that several times. The question is Does the build script run as part of cargo package?

> I read "Check that build scripts did not modify any source files."

The build script is not supposed to modify anything in `src`, but your script is putting it in `env!("OUT_DIR")` witch should be Ok. So I don't think that is your problem.

Can you make and example I can run to see the problem you are having?

**Comment by abdelmonem17** [comment]
@Eh2406 I added a simple project at  [lib test project](https://github.com/abdelmonem17/test-lib) that uses [raft-rs](https://github.com/tikv/raft-rs) which uses proto

**Comment by Eh2406** [comment]
I did get a minute to try that and I can confirm that that is odd. @ehuss any thoughts?

**Comment by abdelmonem17** [comment]
thank you @Eh2406 I discovered the issue and it was because of depending on github crate so when using cargo package this crate fetched from crate.io which has different component so I had compilation error and this was misleading errors,
so I think it is better to give an error on github dependence when using cargo package.
finally is there a workaround to solve this issue ?

**Comment by ehuss** [comment]
This is caused because publishing/packaging does not support `git` or `path` dependencies.  The `git` dependency on `raft` is converted to `raft="*"`, which is raft 0.5.0 at this time.  

We should probably change it so that is an error (on publish/package) instead of the confusing warning.
