### ISSUE TITLE
[vcs] `cargo new --vcs fossil` changes global settings for fossil-scm.

### ISSUE THREAD

**Issue by yasuoohno** [rust-lang/cargo#9449]
**Problem**

`cargo new --vcs fossil` changes global ignore-glob/clean-glob settings for fossil-scm instead of repository local settings.
It will also affect other fossil-scm working copies.

**Steps**

1. clear global setings `fossil unset ignore-glob --global & fossil unset clean-glob --global
2. create new cargo package with `cargo new project_name --vcs fossil`
3. global settings has been changed.

**Possible Solution(s)**

https://github.com/rust-lang/cargo/blob/master/src/cargo/util/vcs.rs#L99-L111

It seems that cargo executes `fossil settings` on the current working directory for cargo.
If it has to change the local settings of the repository, we need to do it in the project working directory.

just like this?

```rust
        ProcessBuilder::new("fossil")
            .cwd(&path)
            .arg("settings")
            .arg("ignore-glob")
            .arg("target")
            .exec()?;

        ProcessBuilder::new("fossil")
            .cwd(&path)
            .arg("settings")
            .arg("clean-glob")
            .arg("target")
            .exec()?;
```

But it is unversioned settings.
I think it would be better using versioned setting files in the project working directory.

1. create `.fossil-settings/ignore-glob` and `.fossil-settings/clean-glob` files.
2. (optional) add configuration files to the repository.  
  `fossil add .fossil-settings/ignore-glob .fossil-settings/clean-glob`

**Notes**

Output of `cargo version`:
cargo 1.51.0 (43b129a20 2021-03-16)

output of `rustup show`:
Default host: x86_64-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)

Output of `fossil version`:
This is fossil version 2.15.1 [2f901f98b3] 2021-04-08 01:05:44 UTC

**Comment by ehuss** [comment]
Yea, it seems like it would make sense to have those be repository settings.  I don't use fossil, but it sounds reasonable to me to change it.

**Comment by PaulDance** [comment]
@yasuoohno #9469 hopefully fixed this part of the code. If you have a bit of time to try this out when it lands on nightly, I would love to hear some feedback!

**Comment by yasuoohno** [comment]
Hi @PaulDance, Thank you for the fix. I'll try this and give you some feedback when I have time.

**Comment by yasuoohno** [comment]
I confirmed with cargo 1.54.0-nightly.
It works fine as I expected with `cargo new --vcs fossil` and also `cargo init --vcs fossil`.

```console
# the global settings are unchanged :-)
$ fossil settings ignore-glob --global
ignore-glob
$ fossil settings clean-glob --global
clean-glob

# and local settings are versionable
$ fossil settings ignore-glob
ignore-glob
  (overridden by contents of file .fossil-settings/ignore-glob)
$ fossil settings clean-glob
clean-glob
  (overridden by contents of file .fossil-settings/clean-glob)

$ cat .fossil-settings/ignore-glob
target
$ cat .fossil-settings/clean-glob
target
```

Thanks!

**Comment by PaulDance** [comment]
@yasuoohno Cool, glad to hear it works as expected!
