### ISSUE TITLE
Fail to install package

### ISSUE THREAD

**Issue by gitboy16** [rust-lang/cargo#9460]
Hi,
I am trying to install the csv package. I am currently running on windows 10 , corporate computer. R, Python and git run all fine if we configure the proxy like that (for git):
```
[http]
proxy="http://user:password@proxy:8000/"
sslVerify=false
```

Same for [https]
Now when I try to the hello rust example with
```
[dependencies]
cvs="1.1"
```
In file Cargo.toml I get the following error:

```
D:\hello-rust>cargo run --verbose
Updating crates.io index
warning: spurious network error (2 tries remaining): failed to convert string to wide form: The parameter is incorrect ; class=Os (2) 
warning: spurious network error (1 tries remaining): failed to convert string to wide form: the parameter is incorrect ; class=Os (2) 
error: failed to get `csv` as a dependency package`hello-rust v0.1.0 (D:\hello-rust)` 
Caused by: Failed to load source for dependency `csv` Caused by: Unable to update registry `https://github.com/rust-lang/crates.io-index` 
Caused by: failed to fetch  `https://github.com/rust-lang/crates.io-index` 
Caused by: failed to convert string to wide form: The parameter is incorrect ; class=Os (2)
```
I am not sure whether it is the same issue as #6513 and might be related to #1180 as well ? I have tried to set up http(s)_proxy as an environment variable without success. I get the following error:

```
warning: spurious network error (2 tries remaining): [5] Couldn't resolve proxy name (unsupported proxy syntax in "http:user:password@proxy:8000"); class-Net (12)
```
Then I tried to set up `net.git-fetch-with-cli` and `CARGO_NET_GIT_FETCH_WITH_CLI` to `true` (documentation was not clear so I have set both to true) and I got a different error:
```
process didn't exit succesfully:`git fetch --force --update-head-ok https://github.com/rust-lang/crates.io-index refs/heads/master:refs/remotes/origin/master HEAD:refs/remotes/origin/HEAD (exit code 128)
--- stderr
fatal unable to access https://github.com/rust-lang/crates.io-index/ SSL certificate problem: self signed certificate in certificate chain
```

(Please note that I have written all the above a small phone keyboard as I can't post on  github from a corporate pc)
Thank you

**Comment by Eh2406** [comment]
I was going to suggest, `git-fetch-with-cli` but it looks like you found that. What happens if you run that `git fetch --force ...` command directly?

**Comment by gitboy16** [comment]
Managed to solve the issue, I had a `#` in my password which is transformed into `\#` it seems...so removed it and replaced it by `_` which is not transformed to `\_`. I created the config file according to rust documentation with the proxy address and all worked fine. I noticed that `npm` has the same issue with character `#` however when configuring R and git in their respective "config" file the character `#` was interpreted correctly so I am not sure whether it is a bug or not. It would be good if someone could try to reproduce it. I am closing for now as I have solved it on my side, however if you believe it is a bug please feel free to re-open. Thank you
