### ISSUE TITLE
How to update cargo after building from source?

### ISSUE THREAD

**Issue by forliuyifei** [rust-lang/cargo#9461]
Sorry this is not a bug, but I have no idea...

**Problem**

How to update cargo after building?

**Steps**

```
$ cd ~/xx/xx/cargo
$ cargo build --release
Finished release [optimized] target(s) in 0.05s

$ cargo -V
cargo 1.51.0 (43b129a20 2021-03-16)

$ ./target/release/cargo -V
cargo 1.53.0

~/.cargo/bin/cargo -V
cargo 1.51.0 (43b129a20 2021-03-16)
```

**Possible Solution(s)**

Can I just replace `~/.cargo/bin/cargo` with `./target/release/cargo` ?

Is there any simple way to update the newest rust and cargo ?

**Comment by Eh2406** [comment]
> Is there any simple way to update the newest rust and cargo ?

If you installed Rust using `rustup` then `rustup update`. If you installed some other way, then you will have to consult with that.

**Comment by ehuss** [comment]
> Can I just replace `~/.cargo/bin/cargo` with `./target/release/cargo` ?

I would not recommend doing that, as it would break rustup, assuming you installed with that.

> Is there any simple way to update the newest rust and cargo ?

The best way is to use `rustup install nightly` assuming you are using rustup.

**Comment by ehuss** [comment]
I'm going to close, as the recommended way to update is via [rustup](https://rust-lang.github.io/rustup/) (or using whatever tools you are using to manage the rust installation).  If you are doing development of cargo itself there is documentation [here](https://doc.crates.io/contrib/process/working-on-cargo.html#running-cargo) for overriding which cargo to use.
