### ISSUE TITLE
Failed to recognize std manifest for target aarch64-pc-windows-msvc

### ISSUE THREAD

**Issue by bgklein** [rust-lang/cargo#9462]
**Problem**
When attempting to build a package linking fails due to not being able to find stdlibs manifest, even though it exists. If you have other targets available such as x86/x64 it will attempt to use those and fail due to mismatch with the linker/compiled bits. If you don't it will fail prior to linking with 
```
For more information about this error, try `rustc --explain E0463`.
error: build failed
```

**Steps**
1.  git checkout https://github.com/pyca/cryptography.git
2.  cd src/rust
3.  cargo build --target "aarch64-pc-windows-msvc"

**Notes**

Output of `cargo version`:
cargo 1.51.0 (43b129a20 2021-03-16)
Windows x64 targeting  target aarch64-pc-windows-msvc

![image](https://user-images.githubusercontent.com/18502617/117221306-de9a2400-adbd-11eb-8d1b-eb96aa981511.png)

**Comment by Eh2406** [comment]
How did you install Rust? How did you set up for cross compilation?

What exact error message did you get? (And as text. My screen reader can not get me anything useful from a screenshot.)

**Comment by bgklein** [comment]
Found out the issue with help of a colleague

    Does your crate include a build.rs?
    Based on the error message from your original posting, it looks like Cargo might be trying/failing to link a build.rs script either from your own crate or maybe one of your dependencies
    Since build.rs runs at build time, it needs to be compiled/linked for the host architecture, which is why you're seeing a bunch of x86_64 libs on the command line. I think the linker error is because Cargo is for some reason trying to use the ARM64 linker to link an x86_64 build.rs

    Ah that may make sense. Doesn't look like the crate I am building has one but possibly a downstream dependency

    num-traits I believe
 VS environment (i.e. just open PowerShell or CMD but don't run vsdevcmd) do you get a different error message?
```

**Comment by Eh2406** [comment]
I don't know much about cross compiling, and what I do know Is based on `rustup`. Sorry I could not be more helpful.
