### ISSUE TITLE
Improve vendoring of unpublished crates

### ISSUE THREAD

**Issue by phyber** [rust-lang/cargo#9463]
**Describe the problem you are trying to solve**

I have a situation where an upstream crate has fixes for some issues, but they're taking their time publishing a new version of the crate. In the meantime, my own crate is broken on some platforms because of this.

Cargo seems to (understandably) fight every attempt to vendor an unpublished crate like this.

**Describe the solution you'd like**

I'd like to be able to temporarily vendor the code from the upstream crate, so that my crate can continue to work.  Perhaps some kind of "internal only" crate could solve this.

I'd love to be able to:

  - Check out fixed upstream code to `vendor/lib`
  - Add `$something` to cargo
  - Cargo compiles, tests, and publishes as if it had used a regular old crate

The `$something` could be a new section, or a flag on an existing dependency.

```toml
[dependencies.lib]
path = "vendor/lib"
internal = true
```

or

```toml
[internal-dependencies]
lib = { path = "vendor/lib" }
```

This would effectively turn the crate into a "fancy module" and the `lib` dependency would disappear from the list of dependencies on crates.io, etc, as I'm now using internal code that just behaves like a crate for compilation and dependency purposes.  A version isn't required here, Cargo should trust that the developer knows what they're doing and the code under the path is what they'd like to use.

Cargo would hopefully be able to treat this like a normal crate while compiling and building the `Cargo.lock`, and during publish would include the vendored code in the published crate so that others can actually compile it.

**Notes**

Perhaps there is already a good solution in place for the above, and I'm just not reading the documentation correctly.  If so, a link to or explaination of how to achieve this type of vendoring would be fantastic.

A vendoring solution that enables a user to be avoid doing things like the following would be great:
  - Forking and publishing the upstream code under a new name
    - Upstream may eventually respond and publish a new crate version
    - Want to avoid polluting the crates.io namespace with an unnecessary crate
    - Don''t want to be responsible for that crate on crate.io if/when it's no longer needed
    - Can always go this route later if upstream really is dead
  - Pulling all of the upstream code into the users own crate as a module
    - Introduces a lot of direct dependencies to the code that weren't there before
    - Lots of extra work

The feature may also be useful for users who wish to start breaking their own crates out into multiple crates, but don't want to start publishing anything yet. They can have these "hidden" internal crates in their own code until they finally break them out into Real Crates and publish them.

If it helps, maybe think of this as "I'd like to include this extra crate shaped lump of code in my own crate, and use it like it was an actual published crate.  Please, Cargo, help me do this".

Thanks for your time.

**Comment by ehuss** [comment]
The intended workflow for switching to a temporary fork is to use the [`[patch]` table](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section). Does that work for you?

**Comment by phyber** [comment]
I tried quite a few things with the `[patch]` table, but it's been a month, so I've forgotten all of the ways in which it failed.

The documentation for `[patch]` seems to be a little bit lacking, so maybe it is possible, but I couldn't make it work. If you have a concrete example of using `[patch]` to use local vendored code (or a fork on GitHub) instead of an upstream crate from crates.io, and have `cargo publish` actually publish the crate that is using `[patch]`, I'd love to see it.

**Comment by ehuss** [comment]
Ah, maybe I misunderstood.  You cannot publish while depending on unpublished sources.

**Comment by phyber** [comment]
> Ah, maybe I misunderstood.

To be fair, I almost certainly did a bad job of explaining what I want. I'll give it another shot.

I'd like to be able to vendor a crate within my crate, _and have it work for `cargo publish`_, so that I don't have to fork and publish someone elses code (license permitting) under a new name on crates.io.

The reasons for this are:
  - Upstream is slow to respond, they do respond eventually, but it's incredibly slow and in the meantime my crates depending on this code are broken on certain platforms
  - Upstream _does_ have the fixes for these problems in their main branch, with passing tests
  - Upstream has not yet published a new version to crates.io
  - My crate does work and passes tests when we test against the upstream code using `[patch]` shenanigans

I need to be able to take that working code, vendor it with my crate, and publish with it.

I could, of course, publish the working code under a new name on crates.io and just consume that. The problem here is that I am now responsible for this random crate on crates.io that will be abandoned as soon as I no longer need it, I do not wish to polute crates.io like this, nor do I wish to have have the responsibility of maintaining this crate forever (since we can't delete crates from crates.io) in the event that someone elses also starts consuming the crate.

**Comment by ehuss** [comment]
Cargo has a pretty fundamental assumption that a single dependency has a single library.  That is unlikely to change.  I understand that this situation can be awkward or frustrating. I would suggest that just publishing the fork is probably the easiest options. You can yank it when it is no longer needed.  You can also make it clear in the README that it is an unsupported fork.

**Comment by phyber** [comment]
> Cargo has a pretty fundamental assumption that a single dependency has a single library.

A single dependency would still be a single library, the difference is just where Cargo would find that dependency.

If my `Cargo.toml` has `foo` listed as a vendored crate, instead of looking at crates.io, Cargo would look in my `vendor` path to find `vendor/foo`, a single library. It would resolve the `Cargo.toml` in `foo` as normal and pull crates for that from crates.io or where ever.

Almost like alternative crate registries, except the registry is shipping along with the rest of the crate, since it's the `vendor` directory.

**Comment by ehuss** [comment]
I'm going to close, as the intended behavior at this time is that a single package contains a single library. Forks can be published on crates.io if needed, which is generally the intended way to deal with an unsupported or unreleased package. Otherwise, since this would be a large and significant change in the way Cargo works, this would likely need to work through the RFC process.  A GitHub issue isn't particularly well suited for these kinds of feature requests.
