### ISSUE TITLE
Terminal startup error

### ISSUE THREAD

**Issue by youssef-mostafa1** [rust-lang/cargo#9479]
I installed rust and cargo recently and now every time I start my terminal it says this:

/.cargo/env (line 4): 'case' builtin not inside of switch block
case ":${PATH}:" in
^
from sourcing file ~/.cargo/env
called on line 8 of file ~/.profile
from sourcing file ~/.profile
called on line 14 of file ~/.config/fish/config.fish
ce64f67dc8ae.png)
from sourcing file ~/.config/fish/config.fish
called during startup
.: Error while reading file “/home/youssef/.cargo/env”
![Screenshot_~ : fish_1](https://user-images.githubusercontent.com/75551868/117806115-286d8900-b25a-11eb-8be0-d03d0cbeb166.png)
it still works but kinda bugs me, so can you help me

**Comment by Eh2406** [comment]
I am sorry you are having a frustrating experience! Have you tried asking for help on the [user form](https://users.rust-lang.org/)? How did you install Cargo?

**Comment by youssef-mostafa1** [comment]
> I am sorry you are having a frustrating experience! Have you tried asking for help on the [user form](https://users.rust-lang.org/)? How did you install Cargo?

I have tried googling the problem but it gave me a bunch of different problems but not the problem that I am encountering
I installed cargo first through "curl https://sh.rustup.rs -sSf | sh" and then realized it took quite a while so I canceled it and then used "sudo pacman -S rust" and at first, it worked just fine and then this happened

**Comment by PaulDance** [comment]
@youssef-mostafa1 Can you show the contents of the `.cargo/env` file? It seems to me that it contains Bash-like syntax while you are using the Fish shell. Do you know if it is part of the `rust` Arch package or if its generated by Cargo itself?

**Comment by youssef-mostafa1** [comment]
> @youssef-mostafa1 Can you show the contents of the `.cargo/env` file? It seems to me that it contains Bash-like syntax while you are using the Fish shell. Do you know if it is part of the `rust` Arch package or if its generated by Cargo itself?

sorry but idk if it was installed with rust or generated but I know what the problem is, it's because of an unfinished switch statement but Idk how to fix it

here are the contents of the env file: 
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac

**Comment by PaulDance** [comment]
@youssef-mostafa1 Well, from what I see, everything should run fine in a POSIX-compatible shell regarding the `case` statement, like Dash, Bash and Zsh. However, Fish does not use the same syntax: the error messages show it's done using `switch` instead of `case` and `case` for match arms. You should refer to its documentation if you want to adapt the script to Fish.

What the script seems to do is check whether the `$HOME/.cargo/bin` substring is already present in the `PATH` environment variable in order to avoid prepending it if it is. This enables you to source the script multiple times without worrying about producing a huge `PATH` environment variable for nothing. It does not break anything if you do however. Therefore, a simpler solution would be to just replace everything with `export PATH="$HOME/.cargo/bin:$PATH"` in POSIX syntax or `set --export PATH $HOME/.cargo/bin $PATH` in Fish I think.

**Comment by youssef-mostafa1534** [comment]
> @youssef-mostafa1 Well, from what I see, everything should run fine in a POSIX-compatible shell regarding the `case` statement, like Dash, Bash and Zsh. However, Fish does not use the same syntax: the error messages show it's done using `switch` instead of `case` and `case` for match arms. You should refer to its documentation if you want to adapt the script to Fish.
> 
> What the script seems to do is check whether the `$HOME/.cargo/bin` substring is already present in the `PATH` environment variable in order to avoid prepending it if it is. This enables you to source the script multiple times without worrying about producing a huge `PATH` environment variable for nothing. It does not break anything if you do however. Therefore, a simpler solution would be to just replace everything with `export PATH="$HOME/.cargo/bin:$PATH"` in POSIX syntax or `set --export PATH $HOME/.cargo/bin $PATH` in Fish I think.

But idk how to do that

**Comment by PaulDance** [comment]
@youssef-mostafa1 How to do what? If you just replace the `~/.cargo/env` file's entire contents with `set --export PATH $HOME/.cargo/bin $PATH`, I *think* it should work, as you seem to use the Fish shell. But if you're looking to adapt the script to make it work the same way under Fish, then you should take a look at its documentation.

**Comment by youssef-mostafa1534** [comment]
ok I will try it thank you

**Comment by ehuss** [comment]
I'm going to close as this is a configuration or rustup issue.  Just to give some context:

AFAIK, it is not normal to configure fish to source the `~/.profile` file (although I have not used fish, so I am not certain if that is sometimes done). That file is usually in sh syntax which is different from fish.  The error message:

```
from sourcing file ~/.profile
     called on line 14 of file ~/.config/fish/config.fish
```

implies that the `~/.config/fish/config.fish` file is set up to source it.  When rustup installs, it updates `~/.profile` to source the cargo environment file which is written in sh syntax.  

rustup currently only supports sh, bash, and zsh.  There is an open issue at https://github.com/rust-lang/rustup/issues/478 for supporting fish.  For now, as suggested above, I would remove the source lines and just update the PATH to include `$HOME/.cargo/bin`.  Hopefully you've been able to get that going, and if not I suggest trying one of the user forums.

**Comment by haennes** [comment]
For those of you wondering whether it will work on garuda.
After logging out and logging back in the cargo command is available so the theory of @ehuss is correct.
