### ISSUE TITLE
trivial typos

### ISSUE THREAD

**Issue by kklibo** [rust-lang/cargo#9483]
Thanks for writing this book.

I just read through the entire thing and I noticed 7 trivial typos, Would it be easier to fix them if I just listed them, or should I make a PR?

**Comment by ehuss** [comment]
Please make a PR, that would be greatly appreciated!

**Comment by weihanglo** [comment]
To fix typo, Cargo has a [great guide here](https://github.com/rust-lang/cargo/blob/449743b1/src/doc/README.md). Typically the workflow may like following:

1. Fix the typo for templated markdown files under [src/doc/man](https://github.com/rust-lang/cargo/tree/master/src/doc/man).
2. Run `build-man.sh` in `src/doc` to generate other formats.
2. Run `mdbook serve` and `cargo help <cmd>` to check if your fix looks great.

**Comment by kklibo** [comment]
Fixed in #9484 (one of my 7 had already been fixed)
