### ISSUE TITLE
crates.io really should be changed to cargo

### ISSUE THREAD

**Issue by hashkeeper** [rust-lang/cargo#9485]
those who have mastered a skill forget what it's like to learn. Some are raced in their learning process by mentors to the finish line, kinda like running deadmines over and over for your party which needs another healer. 

every little bit helps. i think using crates.io creates a moment for beginners of fear and insecurity, that we can say, statistically speaking, many cases of beginners attempting to self-teach, will choose to stop learning over.

it's a url, and it's like this miniature stumbling block that creates frustration, just saying. 

free urls at freenom in ampsterdam, maybe link up

**Comment by Eh2406** [comment]
I do wish the messaging had bean more consistent. But the past cant be changed. crates.io is a part of all documentation, blog posts, and lockfies. I don't se a practical way to change it now.

**Comment by hashkeeper** [comment]
vim has extensive features for this exact issue. where would we be if we couldn't change such a simple aspect of our work.

**Comment by memoryruins** [comment]
It's not clear to me what this issue is about. `cargo` can be used with [registries](https://doc.rust-lang.org/cargo/reference/registries.html) that are not crates.io, as well as other sources like paths and repos. If the issue is about the names being different, that seems like a good thing since the cargo is not forced to use crates.io. If the issue is about mentioning crates.io in docs from the start, would it help to add more disclaimers to those pages that crates.io is not the only registry?

**Comment by hashkeeper** [comment]
but crates.io is the rust developer team's registry. 
my point was that you've created a miniature stumbling block for beginners that just stacks onto a pile of other things that have to memorize all up front (as is the learning process). 
the main cargo team's registry should be called cargo.anything. it's just not great social engineering

but seriously i dont care, i'm just letting you know an outsider perspective. CS gotta look out for its new learners because of the incredibly insane learning curve

**Comment by hashkeeper** [comment]
but crates.io is the rust developer team's registry.
my point was that you've created a miniature stumbling block for beginners that just stacks onto a pile of other things that have to memorize all up front (as is the learning process).
the main cargo team's registry should be called cargo.anything. it's just not great social engineering

but seriously i dont care, i'm just letting you know an outsider perspective. CS gotta look out for its new learners because of the incredibly insane learning curve

**Comment by memoryruins** [comment]
> i'm just letting you know an outsider perspective. 

I am also an outsider when it comes to the cargo repo and its docs (only a user of both). I was curious how this came up for you and what you thought could be changed. For example, I'm interested which feature is being referred to in "vim has extensive features for this exact issue".

> CS gotta look out for its new learners because of the incredibly insane learning curve

I agree, and  I think cargo's guide has often taken that into consideration. Resources can still have room to clarify though, so I imagine the feedback about stumbling blocks is appreciated :)

**Comment by hashkeeper** [comment]
this thread was created concerning the URL. Eh2406 brought up that if the team was to decide to change that URL, documentation would need to be changed in order to reflect such a change. VIMs find and replace tools incorporate regex, it's ability to change text content is incredibly sophisticated.
aah finally found the tutorial i saw about it: [youtube link](https://www.youtube.com/watch?v=FXCitlsA7eQ&list=PL-p5XmQHB_JSTaEPygu1DZjuFfb704Uv7&ab_channel=LukeSmith)

**Comment by Eh2406** [comment]
Updating our documentation would not be hard. As you point out there are good find and replace tools in all the editors. Updating all the projects maintained by the Rust organization, would take some time but is doable. The part that is hard, is updating the thousands of projects that we have no control over.
