### ISSUE TITLE
"file found to be present in multiple build targets" ...why is this a warning?

### ISSUE THREAD

**Issue by sayrer** [rust-lang/cargo#9489]
**Problem**
Why is it a problem for a file to be included in multiple targets?

**Steps**
Put a file in an integration tests directory, and also expose it as a benchmark target.

**Comment by ehuss** [comment]
If multiple targets are using the same source, it likely indicates a configuration problem.  

If you have a target containing benchmarks with `#[bench]`, I would suggest just putting them into `benches`, and then use something like `cargo test --all-targets` or `cargo test --benches` if you want to "test" them, where the harness will run benchmarks with a single iteration.

If you have code you want to share between them, I would suggest putting the shared code in a separate package.

**Comment by sayrer** [comment]
> If multiple targets are using the same source, it likely indicates a configuration problem.
...
> If you have code you want to share between them, I would suggest putting the shared code in a separate package.

That would be the way to silence the warning, but it doesn't actually fix anything. There's no problem.

**Comment by ehuss** [comment]
I'm sorry if this seems like a difficulty for you, but the warning is intentional as mentioned. There are a few ways to organize a project to avoid the warning, and I suggest exploring those. I'm going to close as working as intended.
