### ISSUE TITLE
Build only the default run binary

### ISSUE THREAD

**Issue by danielzfranklin** [rust-lang/cargo#9491]
I'd like a way to build only the default run binary, i.e. what `cargo run` runs. (I'm writing a subcommand that lets the user run the various binaries cargo builds under a time-travelling debugger. By default, I want to build and run only the default run binary)

**Describe the solution you'd like**

Either `cargo build --default-bin`, or some way to get the name of the default binary.

(I think `--no-run` is being phased out. If not, `cargo run --no-run` could also be added, although it sounds a little silly.)

**Notes**

If this is a wontfix I'd like to confirm that the algorithm used by cargo run is as follows.

- main.rs
- bin/foo.rs if only one exists
- value of default-run key in manifest (requires #9497 to get from `cargo metadata`)

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/cargo meeting. We'd be fine with an option to build what `cargo run` would run, but it should definitely be a `cargo build` option (e.g. `--default-bin`); we felt it would be confusing to have `cargo run --no-run` when what you're actually asking for is to build and not run.

On the other hand, you also filed https://github.com/rust-lang/cargo/issues/9497 to provide this information in `cargo metadata`, and our general sentiment in the meeting was that if metadata would suffice we'd be much happier providing it that way and not adding a new command-line option to `cargo build`.

Would metadata suffice for your use case?

**Comment by danielzfranklin** [comment]
Hi Josh, sorry I missed your reply. Metadata would be sufficient.
