### ISSUE TITLE
feature: default-run included in `cargo metadata`

### ISSUE THREAD

**Issue by danielzfranklin** [rust-lang/cargo#9497]
**Describe the problem you are trying to solve**

I'm writing a subcommand that mirrors cargo, but records things under a time-travelling debugger instead of running them. When someone types `cargo rr run` I need to get whatever binary cargo would have run.

In #9491 I requested a solution for this specific use case (something like `cargo build --default-bin`). When looking into replicating the algorithm cargo uses as a workaround I learned cargo doesn't expose the field `default_run` in `cargo metadata`.

**Describe the solution you'd like**

The `default_run` field under `[package]` in `Cargo.toml` is included in `cargo metadata`

**Notes**

Based on a cursory look I think this would just require adding a field to `SerializedPackage` and changing [`Package::serialized`](https://github.com/rust-lang/cargo/blob/d1c0a9d9ca31ec1b861940b30c1a660dfa2e3b56/src/cargo/core/package.rs#L210) to propagate the field value from `Manifest`. I'd be happy to file a PR for this.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/cargo meeting, and we'd be entirely in favor.

**Comment by hi-rustin** [comment]
@danielzfranklin  @ehuss I would like to try to add it.
