### ISSUE TITLE
Document default values of `package.include` and `package.exclude` of `Cargo.toml`

### ISSUE THREAD

**Issue by malaire** [rust-lang/cargo#9502]
Default values of `package.include` and `package.exclude` doesn't seem to be documented anywhere, so it can be a surprise what files `cargo publish` actually includes in the crate.

This is especially bad since `cargo publish` is irreversible.

**Comment by weihanglo** [comment]
AFAIK there is no default value for `package.include` and `package.exclude` [add a `.*` rule under some circumstances](https://github.com/rust-lang/cargo/blob/070e459c/src/cargo/sources/path.rs#L110-L121). There is [a document about `cargo package` respecting gitignore](https://doc.rust-lang.org/cargo/reference/publishing.html#packaging-a-crate) but it's not very detailed. Maybe we can add more information into the manifest chapter instead. 

Also, if you're in trouble with `cargo publish` inclusion rules, providing a reproducible example would help a lot 😀

**Comment by weihanglo** [comment]
I think so. At least for a package under git-control and without `package.include`.

**Comment by malaire** [comment]
Documentation is contradictory about that:

https://doc.rust-lang.org/cargo/reference/publishing.html#packaging-a-crate
> Cargo will automatically ignore files ignored by your version control system when packaging

That implies that both `.gitignore` and `.git/info/exclude` are used.


https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields
> If git is being used for a package, the exclude field will be seeded with the gitignore settings from the repository.

That says that only `.gitignore` is used and `.git/info/exclude` is not used.

So is `.git/info/exclude` used or not?

**Comment by weihanglo** [comment]
First time knows `.git/info/exclud`. Cool stuff!

After some quick testing, I found that, unfortunately, `cargo publish` only support `.gitignore`, which means it is not fully git-compliance nor supporting other VCS. One solution is to make the doc aligns to the current implementation, but for now let's wait for cargo team's opinion.

**Comment by ehuss** [comment]
I opened PR #9538 to add documentation for this, please let me know if you have any feedback.



> After some quick testing, I found that, unfortunately, `cargo publish` only support `.gitignore`, which means it is not fully git-compliance nor supporting other VCS.

This should be working, can you put together an example where it doesn't?  Did you maybe not have any commits?  Or have an `include` rule?  The following works for me:

```sh
cargo new foo
cd foo
git add .gitignore Cargo.toml src
git commit -m test
touch bar
cargo package --list --allow-dirty  # Should contain `bar`
echo bar >> .git/info/exclude
cargo package --list --allow-dirty  # Should not contain `bar`
```

**Comment by weihanglo** [comment]
It works for me now. I guess I made some mistake days ago. 😞

Sorry about that and thank for your patch PR!
