### ISSUE TITLE
Using cargo clippy without rustup

### ISSUE THREAD

**Issue by FloLo100** [rust-lang/cargo#9505]
**Describe the problem you are trying to solve**
I work on an air-gapped system. Therefore I currently need to install cargo without `rustup`. However `cargo clippy` is only available as part of the rustup toolchain (I get "`error: no override and no default toolchain set`" if I execute cargo clippy).
`cargo-driver` works fine, however working on complex projects with many dependency means this is no solution for me.

**Describe the solution you'd like**
I would like to run `cargo clippy` on my air-gapped system. I see two possible solutions:

1. Allow rustup to run on offline systems.
2. Allow cargo clippy to run without rustup.

**Notes**
I don't know what the hurdles for these two solutions would be, so I don't know how easily this could be implemented.

**Comment by Eh2406** [comment]
Also this is Cargos issue tracker, depending on the solution this should probably belong in Rustup or Clippy issue tracker.

**Comment by FloLo100** [comment]
I was unsure if this is belonged to the Clippy tracker because clippy-driver works fine. If this can't be fixed by cargo I could try opening up tickets there too of course.

**Comment by ehuss** [comment]
Can you explain more about how you installed cargo and clippy?  If you use the standalone installers, they should work correctly. Is it possible that you previously tried to install rustup?  By default, cargo will search the `$CARGO_HOME/bin` directory first. If you have a previous installation located in that directory, then it will take priority over other things.  If so, uninstalling the old rustup may help.

**Comment by ehuss** [comment]
I'm going to close without more information.  However, if you can elaborate more, feel free to reopen. In general, the standalone installers should be able to install clippy.
