### ISSUE TITLE
error: failed to run custom build command for `curl-sys v0.4.43+curl-7.76.0`

### ISSUE THREAD

**Issue by jhunnius** [rust-lang/cargo#9509]
I can not build cargo manually on cygwin (Windows 10).

Originally, I wanted to `cargo install cargo-generate` to build WebASM applications, but cargo itself fails to build with the same error as cargo-generate.

**Problem**
error: failed to run custom build command for `curl-sys v0.4.43+curl-7.76.0`

Log:
   Updating crates.io index
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.9
   Compiling jobserver v0.1.22
   Compiling pkg-config v0.3.19
   Compiling libc v0.2.95
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling serde_derive v1.0.126
   Compiling log v0.4.14
   Compiling memchr v2.4.0
   Compiling serde v1.0.126
   Compiling crc32fast v1.2.1
   Compiling tinyvec_macros v0.1.0
   Compiling matches v0.1.8
   Compiling percent-encoding v2.1.0
   Compiling typenum v1.13.0
   Compiling anyhow v1.0.40
   Compiling ryu v1.0.5
   Compiling bitflags v1.2.1
   Compiling curl v0.4.37
   Compiling autocfg v1.0.1
   Compiling ppv-lite86 v0.2.10
   Compiling serde_json v1.0.64
   Compiling regex-syntax v0.6.25
   Compiling itoa v0.4.7
   Compiling version_check v0.9.3
   Compiling utf8parse v0.1.1
   Compiling rand_core v0.5.1
   Compiling once_cell v1.7.2
   Compiling unicode-width v0.1.8
   Compiling hex v0.3.2
   Compiling fnv v1.0.7
   Compiling lazy_static v1.4.0
   Compiling strsim v0.8.0
   Compiling humantime v2.1.0
   Compiling vec_map v0.8.2
   Compiling semver-parser v0.7.0
   Compiling shell-escape v0.1.5
   Compiling hex v0.4.3
   Compiling bytesize v1.0.1
   Compiling lazycell v1.3.0
   Compiling glob v0.3.0
   Compiling rustc-workspace-hack v1.0.0
   Compiling getrandom v0.2.3
   Compiling cc v1.0.68
   Compiling tinyvec v1.2.0
   Compiling unicode-bidi v0.3.5
   Compiling form_urlencoded v1.0.1
   Compiling vte v0.3.3
   Compiling rand_xoshiro v0.4.0
   Compiling textwrap v0.11.0
   Compiling thread_local v1.1.3
   Compiling im-rc v15.0.0
   Compiling crossbeam-utils v0.8.4
   Compiling rand_core v0.6.2
   Compiling strip-ansi-escapes v0.1.0
   Compiling unicode-normalization v0.1.17
   Compiling rand_chacha v0.3.0
   Compiling num_cpus v1.13.0
   Compiling libz-sys v1.1.3
   Compiling libnghttp2-sys v0.1.6+1.43.0
   Compiling curl-sys v0.4.43+curl-7.76.0
   Compiling libssh2-sys v0.2.21
   Compiling libgit2-sys v0.12.21+1.1.0
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.16
   Compiling quote v1.0.9
   Compiling rand v0.8.3
   Compiling idna v0.2.3
   Compiling bitmaps v2.1.0
   Compiling regex v1.5.4
   Compiling url v2.2.2
   Compiling filetime v0.2.14
   Compiling sized-chunks v0.6.5
   Compiling winapi-util v0.1.5
   Compiling socket2 v0.4.0
   Compiling remove_dir_all v0.5.3
   Compiling atty v0.2.14
   Compiling crypto-hash v0.3.4
   Compiling miow v0.3.7
   Compiling opener v0.4.1
   Compiling home v0.5.3
   Compiling globset v0.4.6
   Compiling tar v0.4.33
   Compiling same-file v1.0.6
   Compiling termcolor v1.1.2
   Compiling clap v2.33.3
   Compiling tempfile v3.2.0
   Compiling walkdir v2.3.2
   Compiling fwdansi v1.1.0
   Compiling env_logger v0.8.3
   Compiling ignore v0.4.17
   Compiling cargo-util v0.1.0 (C:\cygwin64\home\jan_2\cargo\crates\cargo-util)
   Compiling serde_ignored v0.1.2
   Compiling toml v0.5.8
   Compiling semver v0.10.0
   Compiling cargo-platform v0.1.1 (C:\cygwin64\home\jan_2\cargo\crates\cargo-pl
atform)
   Compiling rustfix v0.5.1
   Compiling flate2 v1.0.20
   Compiling cargo v0.55.0 (C:\cygwin64\home\jan_2\cargo)
The following warnings were emitted during compilation:

warning: gcc: fatal error: no input files
warning: compilation terminated.
warning: gcc: fatal error: no input files
warning: compilation terminated.

error: failed to run custom build command for `curl-sys v0.4.43+curl-7.76.0`

Caused by:
  process didn't exit successfully: `C:\cygwin64\home\jan_2\cargo\target\release
\build\curl-sys-9fd8b6919fe5eefd\build-script-build` (exit code: 1)
  --- stdout
  cargo:root=C:\cygwin64\home\jan_2\cargo\target\release\build\curl-sys-0854f4c5
8ee1a36a\out
  cargo:include=C:\cygwin64\home\jan_2\cargo\target\release\build\curl-sys-0854f
4c58ee1a36a\out\include
  cargo:static=1
  cargo:rustc-cfg=link_libnghttp2
  cargo:rustc-cfg=link_libz
  TARGET = Some("x86_64-pc-windows-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "
curl/lib" "-I" "curl/include" "-I" "C:\\cygwin64\\home\\jan_2\\cargo\\target\\re
lease\\build\\libnghttp2-sys-0421b25a89b26c34\\out\\i\\include" "-I" "C:\\cygwin
64\\home\\jan_2\\cargo\\target\\release\\build\\libz-sys-968ff0acde6cac4d\\out/i
nclude" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT"
"-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISA
BLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-D
CURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_
TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-
DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GE
TSOCKNAME" "-DCURL_DISABLE_FTP" "-DUSE_NGHTTP2" "-DNGHTTP2_STATICLIB" "-DUSE_WIN
DOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_
FIONBIO" "-DUSE_WINSOCK" "-o" "C:\\cygwin64\\home\\jan_2\\cargo\\target\\release
\\build\\curl-sys-0854f4c58ee1a36a\\out\\build\\curl/lib/asyn-thread.o" "-c" "cu
rl/lib/asyn-thread.c"
  cargo:warning=gcc: fatal error: no input files
  cargo:warning=compilation terminated.
  exit code: 1
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "
curl/lib" "-I" "curl/include" "-I" "C:\\cygwin64\\home\\jan_2\\cargo\\target\\re
lease\\build\\libnghttp2-sys-0421b25a89b26c34\\out\\i\\include" "-I" "C:\\cygwin
64\\home\\jan_2\\cargo\\target\\release\\build\\libz-sys-968ff0acde6cac4d\\out/i
nclude" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT"
"-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISA
BLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-D
CURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_
TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-
DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GE
TSOCKNAME" "-DCURL_DISABLE_FTP" "-DUSE_NGHTTP2" "-DNGHTTP2_STATICLIB" "-DUSE_WIN
DOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_
FIONBIO" "-DUSE_WINSOCK" "-o" "C:\\cygwin64\\home\\jan_2\\cargo\\target\\release
\\build\\curl-sys-0854f4c58ee1a36a\\out\\build\\curl/lib/altsvc.o" "-c" "curl/li
b/altsvc.c"
  cargo:warning=gcc: fatal error: no input files
  cargo:warning=compilation terminated.
  exit code: 1

  --- stderr
  fatal: not a git repository (or any parent up to mount point /cygdrive)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

  error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections
" "-m64" "-I" "curl/lib" "-I" "curl/include" "-I" "C:\\cygwin64\\home\\jan_2\\ca
rgo\\target\\release\\build\\libnghttp2-sys-0421b25a89b26c34\\out\\i\\include" "
-I" "C:\\cygwin64\\home\\jan_2\\cargo\\target\\release\\build\\libz-sys-968ff0ac
de6cac4d\\out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL
_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDA
P" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_POP3" "-DCURL_DI
SABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "
-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=
\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERN
AME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_FTP" "-DUSE_NGHTTP2" "-DNGHTTP2_STATIC
LIB" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHA
VE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-o" "C:\\cygwin64\\home\\jan_2\\cargo\\
target\\release\\build\\curl-sys-0854f4c58ee1a36a\\out\\build\\curl/lib/asyn-thr
ead.o" "-c" "curl/lib/asyn-thread.c" with args "gcc.exe" did not execute success
fully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed

**Steps**
1.  `git clone https://github.com/rust-lang/cargo`
2.  `cd cargo`
3.  `cargo build --release`

**Possible Solution(s)**
Maybe use other versions of curl-sys and curl in Cargo.toml?

**Notes**

I can't `cargo install cargo` as a pre-action to `cargo install cargo-generate`, because it is already installed (as part of rustup).

Can I use a verndored curl?

Output of `cargo version`:
cargo 1.52.0 (69767412a 2021-04-21)

**Comment by Eh2406** [comment]
Why do you need to run `cargo install cargo` in order to run `cargo install cargo-generate`? Why cant you use the rustup installed `cargo`?
Also how did you install Cargo/Rust? Dose it work outside of cygwin?

**Comment by jhunnius** [comment]
I tried `cargo install cargo-generate`. It throws the same issue when trying to compile cargo 0.53.0.

Rust and cargo run fine from CLion and from cygwin.

The cargo as well as the cargo-generate build also run far into the process, but then fail near the end.

**Comment by ehuss** [comment]
@Eh2406 `cargo-generate` depends on `cargo` the library to build.

@jhunnius To build C libraries for `x86_64-pc-windows-gnu`, it needs an environment with gcc that can handle windows-style paths. The section at https://github.com/alexcrichton/cc-rs#compile-time-requirements contains some links for mingw-w64 which should work.  I don't fully understand how it works, but I believe it detects executables that don't link the msys2 executable, and in that scenario will translate C:\ style paths to posix paths like `/c/foo/...` internally.  It seems hit-and-miss which kind of cygwin environment works, but I have mingw-w64-v8.0.0 which seems to work.  I've tried many times to understand the relationship of cygwin/msys/msys2/mingw/mingw-w64/..., but I still don't fully understand it.

**Comment by jhunnius** [comment]
An old mingw version in the path was to blame (the one that ships with RStudio). Moved it out of the way, and both builds (wasm-pack and cargo-generate) work.

cygwin does translate `C:\` to `/cygdrive/c` btw.
