### ISSUE TITLE
Tracking Issue for -Z configurable-env

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#9539]
**Summary**

Original issue: #4121 
Implementation: #9175 
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#configurable-env

The `-Z configurable-env` option enables reading the `[env]` table from config which will set the specified environment variables.

**Unresolved issues**

* [ ] Interaction with environment variables cargo sets itself (some can be overridden, some cannot, for example anything set after `fill_env` like build-script env vars).

**About tracking issues**

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by wickerwaka** [comment]
Is there a discussion about this occurring in some other other place?

**Comment by ehuss** [comment]
I don't think so. Feel free to discuss it here or on Zulip or internals.  The boilerplate in the issue is just meant to keep the noise down so that people following the issue only get relevant updates, but I doubt there are too many people following here (esp since it was just opened).

**Comment by h4x3rotab** [comment]
This is still not available by setting `cargo-features` in Cargo.toml, but `-Z configurable-env` only. I'm wondering why it's not added.

**Comment by Eh2406** [comment]
It will have a `-Z` flag until it is stabilized. Do you think it should also have an opt in in Cargo.toml after sablazation?

**Comment by h4x3rotab** [comment]
Sorry, I misunderstood how `cargo-features` works. In my situation, I'd love to enable this unstable feature by Cargo.toml instead of command line flags, because in some cases (e.g. working with IDE or some other tools), there's no standard way to specify the unstable feature flag. However it turns out `cargo-features` is for the features affecting Cargo.toml file.

**Comment by Eh2406** [comment]
Does adding 
```toml
[unstable]
configurable-env = true
```
to a `.cargo/config.toml` do what you need?

**Comment by oblique** [comment]
Any opinions on expanding an environment variable?

For example:

```toml
[env]
FOO = "$BAR/xyz"
PATH = "/opt/foobar/bin:$PATH"
```

**Comment by jonhoo** [comment]
I'd also like to propose another (minor?) missing part of the current design: the ability to _unset_ an environment variable. The current design would only let you set a variables value to `""`, but that's not quite the same.

**Comment by ehuss** [comment]
Yea, thanks for the ping. Going ahead and closing since this was stabilized.

If you want to extend it to support unsetting, that is probably OK.  I can imagine an `{unset=true}` flag or something like that.
