### ISSUE TITLE
Detect incorrectly named cargo.toml

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/cargo#9541]
A new user following tutorials won't necessarily use `cargo new`; they may create files by hand.

In practice, I have found that such users may accidentally create `cargo.toml` instead of `Cargo.toml`.

If `Cargo.toml` is missing, `cargo` should detect the presence of a file like `cargo.toml` and suggest that the user rename it to `Cargo.toml`.

**Comment by hedonhermdev** [comment]
Hey can I take this up?

**Comment by ehuss** [comment]
Of course, let me know if you have any questions.  There is a contributor guide [here](https://doc.crates.io/contrib/) if you need more information on working on cargo.

Also, just for the future, you are welcome to automatically claim an issue yourself (as noted [here](https://doc.crates.io/contrib/process/index.html#issue-assignment), you can use `@rustbot claim` if you want to make it formal).

**Comment by hedonhermdev** [comment]
Should I also add a test for this?

**Comment by ehuss** [comment]
Yea, that would be good!  We try to add tests for every addition and fix when possible.

**Comment by hedonhermdev** [comment]
Hey, so the filesystem on MacOS is case-insensitive and treats `cargo.toml` and `Cargo.toml` as the same. So I'm not sure how to test it.

**Comment by ehuss** [comment]
The test could create a file (`Test`) and then try to open it with lowercase (`test`) and if that succeeds, you'll know you're on a case-insensitive filesystem.  I'm not sure how you're planning to implement it for that case, if you will silently allow it, issue a warning, or an error.  I'm thinking in the spirit of the issue, it might be good to detect it, but I'm not sure how difficult that would be.

**Comment by hi-rustin** [comment]
@hedonhermdev  Are you still fixing this issue? I want to try to improve it!

**Comment by hedonhermdev** [comment]
Hey yes you can continue with it

**Comment by hi-rustin** [comment]
@ehuss Could you offer some help please? I seem to be having trouble finding a place to add that suggestion. Is there a place where these commands uniformly parse Cargo.toml that can be modified?

**Comment by ehuss** [comment]
I think it might go [here](https://github.com/rust-lang/cargo/blob/3b171935944aeaea7479267ab81288cc93bd5db3/src/cargo/util/toml/mod.rs#L35-L58) where it is loaded, and just check for a `NotFound` error.

**Comment by hi-rustin** [comment]
> I think it might go [here](https://github.com/rust-lang/cargo/blob/3b171935944aeaea7479267ab81288cc93bd5db3/src/cargo/util/toml/mod.rs#L35-L58) where it is loaded, and just check for a `NotFound` error.

There still seems to be a lot of places where that path is being used. I try to try to warn them uniformly.
