### ISSUE TITLE
Cargo doesn't allow to pass extra linker arguments per binary or for examples

### ISSUE THREAD

**Issue by curldivergence** [rust-lang/cargo#9542]
Hello, I need to export some specific symbols from the binaries that use my library (including the examples that are in the same crate), and to do this, I have to pass some extra linker args since nothing is exported by default. But unfortunately, .cargo/config.toml doesn't allow to specify extra compiler/linker args with fine granularity: it applies the `build.rustflags` option contents to every compiler call, which is unfortunate since the dependencies of my library (and my library itself) do not contain the required symbols and thus fail to link.

Ideally, I'd love to have a language attribute that would allow forwarding extra compiler args from source, but it looks like a serious and probably controversial change, so I believe this issue should be handled on cargo level.
As to my taste, the most obvious place to put extra flags is cargo.toml (since it's the place where some people, including me and the reporter of #3261, have tried to put this flag :)), but since it has not been done already, I can guess there are some arguments against it? So please share your thoughts.

Thanks!

**Comment by ehuss** [comment]
Have you checked out the [rustc-link-arg](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#extra-link-arg) feature? That allows you to specify per-binary linker arguments in a build script.  It is currently only on nightly, but would be good to have someone test it out.

**Comment by curldivergence** [comment]
@ehuss Unfortunately I don't see this option as available on `rustc 1.54.0-nightly (cc77ba46f 2021-06-03)` (as I understand, I should be able to see it in the output of `rustc.exe -Z help`?)

**Comment by ehuss** [comment]
The `-Z` flag is passed to cargo, not rustc. It should be listed in `cargo -Z help`.

**Comment by curldivergence** [comment]
@ehuss, it worked!! Thank you very much, you really saved the day :)
![image](https://user-images.githubusercontent.com/1927180/120825679-4b8e0e80-c562-11eb-8b6d-b1a5d30f607f.png)
I was about to start writing custom build scripts for manual rustc invocation for each library example :)

I think we won't need the feature I have requested when your option is stabilized, so please feel free to close the issue.

**Comment by curldivergence** [comment]
However, I have one more question: is there a possibility to add this option to cargo config or manifest so that one doesn’t have to use it explicitly on command line?

**Comment by curldivergence** [comment]
@ehuss, also, judging from the fact this option is pretty young I can guess it's kind of early to ask this, but anyway, is there any sort of vision regarding the timeline of stabilization of this flag? Thanks!

**Comment by ehuss** [comment]
Before it is stabilized, you can place it in the `[unstable]` config section (described [here](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html)) so you don't have to specify it on the command-line.

There is a proposal to stabilize it at #9557.  I'm not sure how long it will take, though. We just discovered an issue with the implementation which will need to be resolved first.

Closing since this seems to be resolved.
