### ISSUE TITLE
Run executable as sudo on Linux

### ISSUE THREAD

**Issue by matt-hu** [rust-lang/cargo#9573]
**Describe the problem you are trying to solve**

Sometimes libraries require sudo permission to run (on Linux). If using `cargo run`, there isn't a way to run *just the executable* as sudo, as far as I am aware. I don't want to run the build process as sudo.

**Describe the solution you'd like**

A flag for cargo run (e.g. `cargo run --sudo`) that would run just the executable as sudo.

**Notes**

OS: Linux
Cargo version:  1.52.0

**Comment by Bryysen** [comment]
Maybe a bit contrived, but you can already do this by making use of `target.<triple>.runner`. Here's how:
In your project folder, create the file `.cargo/config` and write the following:
```
[target.x86_64-unknown-linux-gnu]
runner = "/usr/bin/sudo"
```
Replace `x86_64-unknown-linux-gnu` with your target triple, or use `'cfg(unix)'`, whatever works best for you.
Doing cargo run (or cargo test/cargo bench) should now invoke the binaries through `sudo`.

**Comment by ehuss** [comment]
I'm going to close, as I don't think Cargo would add something specifically for `sudo`. But as mentioned, there is a config for setting the runner.  Alternatively, you can use a wrapper (like [`cargo-xtask`](https://github.com/matklad/cargo-xtask) or [`cargo-make`](https://crates.io/crates/cargo-make)) that could run cargo and then run your executable however you want.
