### ISSUE TITLE
cargo update --no-update or some such

### ISSUE THREAD

**Issue by ijackson** [rust-lang/cargo#9587]
**Describe the problem you are trying to solve**

I often have `Cargo.lock` committed to git and I like to precisely control my dependency updates.  I usually use `--locked --offline`.

After I have added a dependency to `Cargo.toml` I need to update the lockfile.  `cargo update` likes to update everything.  `cargo update -p NEW-DEPENDENCY` does not work: it prints `error: package ID specification NEW-DEPENDENCY did not match any packages`.

Similar problems arise when removing dependencies or restructuring my packages.  (`cargo update -p REMOVED-DEPENDENCY` can update the version of the crate if it is an indirect dependency.)

**Describe the solution you'd like**

I would like option or subcommand which is exactly like `cargo update -p SOME-PACKAGE-WHICH-HAS-NOT-CHANGED`.

I suggest `cargo update --no-update`

**Notes**

I have discovered that `cargo update --precise THIS-PACKAGE-VERSION -p THIS-PACKAGE` is a reliable workaround, although the rune has to vary according to where it's run so cannot be made into a simple shell alias.

**Comment by illicitonion** [comment]
Does running a command like `cargo metadata >/dev/null` do the job for you? I believe it will make your `Cargo.lock` reflect all of the dependencies in your `Cargo.toml` _without_ trying to update ones which may be out of date (unless a constraint on the newly added one requires it).

**Comment by ehuss** [comment]
As mentioned, most commands (`cargo metadata`, `cargo tree`, etc.) will update only what is necessary.

Additionally, in 1.50, `cargo update --workspace` was added which essentially does the same thing (only updates things that are absolutely necessary), which is intended for this use case.

**Comment by ehuss** [comment]
I'm going to close, as `cargo update --workspace` is the recommended approach, or you can just run another command.
