### ISSUE TITLE
Build scripts are not informed of rustflags or rustc wrapper

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#9600]
**Describe the problem you are trying to solve**

I recently came across a [bug in anyhow](https://github.com/dtolnay/anyhow/issues/156) whose root cause is that it does  "test compile" to see whether it can make use of some nightly features, but that test compile does not take into account Cargo configuration like `[build] rustflags = `. Looking through the [environment variables Cargo sets for build scripts](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) it doesn't appear that things like the rustc wrapper or the final rustflags is actually passed to the build script. Specifically, this can be seen by running

```shell
cargo new cargo-build-no-flags
cd cargo-build-no-flags
mkdir .cargo
cat >.cargo/config.toml <<EOF
[build]
rustflags = ["--cfg=wrapped"]
rustc-wrapper = "$PWD/.cargo/wrap.sh"
EOF
cat > .cargo/wrap.sh <<'EOF'
#!/bin/sh
rustc=$1
shift
exec "$rustc" "$@"
EOF
chmod +x .cargo/wrap.sh
cat > build.rs <<EOF
fn main() {
    for var in std::env::vars() {
        eprintln!("{:?}", var);
    }
}
EOF
cargo check -vv 2>&1 | grep '^\[cargo-build-no-flags' | tee build-output.log
```

Then, observe that "wrap", which appears in both `build.rustflags` and `build.rustc-wrapper`, does not appear in the build output:

```console
$ grep wrap build-output.log
$
```

**Describe the solution you'd like**

The rust compiler is given to the build script in the form of the `RUSTC` environment variable, but that alone is not sufficient for a build script that wants to inspect (or use) the target Rust compilation context. The rustc configuration (the wrapper and RUSTFLAGS) should be passed to the build script as well, likely through two new environment variables:

 - `CARGO_RUSTC_WRAPPER`
 - `CARGO_RUSTFLAGS`

Note that these do _not_ include `_BUILD` to avoid overlap with the [environment variables Cargo _reads_](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads).

**Comment by cuviper** [comment]
> **Describe the solution you'd like**
> 
> The rust compiler is given to the build script in the form of the `RUSTC` environment variable, but that alone is not sufficient for a build script that wants to inspect (or use) the target Rust compilation context. The rustc configuration (the wrapper and RUSTFLAGS) should be passed to the build script as well, likely through two new environment variables:
> 
> * `CARGO_RUSTC_WRAPPER`
> * `CARGO_RUSTFLAGS`

So those would be the target-specific flags, right? (i.e. matching the `TARGET` that cargo also sets for the build script.)

This would be a real boon to `autocfg`! (cc cuviper/autocfg#15 cuviper/autocfg#34)

**Comment by jonhoo** [comment]
Yes, my thinking was that they'd be set based on how Cargo decides to build the build script itself. See also the implementation of this in https://github.com/rust-lang/cargo/pull/9601, which is really quite simple.

**Comment by cuviper** [comment]
> Yes, my thinking was that they'd be set based on how Cargo decides to build the build script itself.

I don't think that's quite the same thing, since the build script runs on the host. But AFAICT the call you added does use the current `bcx.target_data`, the same that `TARGET` is set from, so it should be what I want.
