### ISSUE TITLE
Non optional dependency being removed on --no-default-features

### ISSUE THREAD

**Issue by edrevo** [rust-lang/cargo#9608]
**Problem**
I have a cargo workspace with the following projects:
1. ballista-scheduler has an optional dependency on `tokio-stream` for a default feature
2. ballista-executor has a mandatory dependency on `tokio-streams` and another mandatory dependency on ballista-scheduler

When running `cargo build --no-default-features`, the following error is emitted:

```
error[E0433]: failed to resolve: could not find `TcpListenerStream` in `wrappers`
  --> ballista/rust/executor/src/standalone.rs:57:37
   |
57 |             tokio_stream::wrappers::TcpListenerStream::new(listener),
   |                                     ^^^^^^^^^^^^^^^^^ could not find `TcpListenerStream` in `wrappers`
```

**Steps**
`cargo build --no-default-features` on https://github.com/apache/arrow-datafusion/pull/589

**Possible Solution(s)**
`tokio-stream` should be available to `ballista-executor`

**Notes**

Output of `cargo version`:

❯ cargo version
cargo 1.53.0 (4369396ce 2021-04-27)

**Comment by ehuss** [comment]
It looks like `tokio_stream` is being built, at least from what I see.  `tokio_stream` only defines `TcpListenerStream` if the `net` feature is enabled on it. I don't see that feature being enabled, so I would think ballista-executor would need to depend on it as:

```toml
tokio-stream = { version = "0.1", features= ["net"] }
```

if you want to assume that it can use the net feature.

Does that help?

**Comment by edrevo** [comment]
🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️

You are 100% correct. Sorry for opening a false issue, and many thanks for the super quick and super friendly reply ♥ These kinds of replies are what make the Rust community so great.

Sorry again for the false issue. I forgot to check whether TcpListenerStream was part of a non-default feature in `tokio-stream`.
