### ISSUE TITLE
cargo build won't create staticlib

### ISSUE THREAD

**Issue by kuchaguangjie** [rust-lang/cargo#9609]
**Problem**
`cargo build` didn't create a `xxx.a` file in `target/debug`.

**Steps**

**1.  create a rust project.**

   **src/lib.rs:**
```
#![crate_type = "staticlib"]

#[no_mangle]
pub extern fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

  **Cargo.toml:**

```
[package]
name = "ffi-c-call-rust"
version = "0.1.0"
authors = ["eric"]
edition = "2018"

[lib]
name = "add_input"
crate-type = ["staticlib"]
```

**2. Build**
Run command: `cargo build`, then no `target` is created.

**Possible Solution(s)**

But if I instead run:
  ```
  mkdir -p target/debug
  rustc --crate-type=staticlib -o target/debug/libadd_input.a src/lib.rs
  ```
Then the `.a` file is created, and could be used by `.c` code.

So, how to make `cargo build` to create the staticlib, aka the `.a` file.

**Notes**

Output of `cargo version`:

> cargo 1.52.0 (69767412a 2021-04-21)

BTW, I'm using Linux (mint mate 20).

**Comment by ehuss** [comment]
Using the `#![crate_type]` attribute won't work with cargo.  Cargo needs to know the crate type, and it can't if it is set in the source files.  You can set the crate type in `Cargo.toml` with the [`crate-type`](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-crate-type-field) setting.

**Comment by kuchaguangjie** [comment]
@ehuss Check my question, already set it.

**Comment by ehuss** [comment]
Oh, sorry, I missed that.  Hm, it sounds like the `target` directory is completely missing?  Perhaps you can run with `cargo build -v` to verify where it is placing the output?  You should see something like `Running `rustc --crate-name add_input`, and you should see an `--out-dir` flag indicating where the output is going.  You can also run with the `CARGO_LOG=debug` environment variable, and it should print a bunch of debugging information which should show where it is placing the output.

**Comment by kuchaguangjie** [comment]
@ehuss Thanks.
Running `export CARGO_LOG=debug; cargo b -v`, then I saw the output is created in the root's `target/`, the code above is a member of that root.

**Comment by kuchaguangjie** [comment]
I have figured it out, use:

> cargo b --target-dir=target/

Then it will generate in current dir's `target/`, instead of searching for parent root.
