### ISSUE TITLE
cargo 1.50.0 can not cope with filedescriptor-0.8.0

### ISSUE THREAD

**Issue by mcr** [rust-lang/cargo#9610]
dooku-[~](2.6.6) mcr 10001 %cargo install filedescriptor
    Updating crates.io index
  Downloaded filedescriptor v0.8.0
error: failed to parse manifest at `/home/mcr/.cargo/registry/src/github.com-1ecc6299db9ec823/filedescriptor-0.8.0/Cargo.toml`

I expected to get installed. (I came across this after an cargo update on another project)

**Steps**

1. install cargo 1.50.0
2. try to install this version of filedescriptor (which I think is the latest)
3.

**Possible Solution(s)**
Upgrade to cargo 1.53.0

**Notes**

The comment at the top of that file says:

~~~~
# If you believe there's an error in this file please file an
# issue against the rust-lang/cargo repository. If you're
# editing this file be aware that the upstream Cargo.toml
# will likely look very different (and much more reasonable)
~~~~

I think that the goal of the rewriting is to keep people from being forced to upgrade.

**Comment by ehuss** [comment]
It can be helpful to post the full message:

```
error: failed to download `filedescriptor v0.8.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/filedescriptor-0.8.0/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

As you may see, 1.50 does not support this feature. You'll need at least 1.51.   When a project uses new features or syntax, they may require a newer version of Rust to use.

Also, from what I can see, `filedescriptor` is not a binary crate, so `cargo install` won't work.

**Comment by ehuss** [comment]
I'm going to close, as I believe the error message indicates why it is unable to use that package.  I think that is about the best the error message can do, as it does not know when a particular feature gets stabilized.   Of course, if you have any suggestions on how it could be clearer, feel free to suggest them.

**Comment by mcr** [comment]
> It can be helpful to post the full message:

Yes, but how does telling me to right nightly cargo, sync with the VERY VERY clear message in the generated Cargo.toml, that tells me that if it doesn't work, then it's a bug that should be reported.
It seems to me that the ENTIRE PURPOSE of rewriting the Cargo toml is to make it backwards compatible.
The message 

~~~~
this Cargo does not support nightly features, but if you
switch to nightly channel you can add
~~~~

so, this has nothing to do with a nightly feature, but in fact a feature deployed.  Perhaps when the Cargo toml is updated, then it should contain a minimum Cargo version that it can be used with?

**Comment by ehuss** [comment]
Ah, I think I understand.  I think the error message could be improved when it comes from a registry dependency, since the user does not have control over those.  

The preamble in the rewritten Cargo.toml also probably isn't too helpful.  

There is an unstable enhancement to add specifying the [rust version](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#rust-version), but it has not been stabilized, yet.
