### ISSUE TITLE
cargo clean attempts to remove everything from /tmp

### ISSUE THREAD

**Issue by deliverystack** [rust-lang/cargo#9628]
**Problem**

It appears that I used cargo build for a project with a package that created a cargo config file that defaulted the build directory to /tmp, after which cargo clean tried to delete everything from /tmp, which is inappropriate.

The unexpected behavior of cargo attempting to truncate /tmp was highly upsetting for me and could be disastrous for others. I would appreciate it if you could inform me about any similar concerns I should have regarding rust and cargo.

**Steps**

1. cargo new
2. update .toml to reference packages (I do not know which)
3. cargo build
4. cargo clean

cargo attempts to truncate /tmp

**Possible Solution(s)**

I have some serious concerns about the rust toolchain and library system in general. I am not sure that this is the optimal solution for this case, but alice suggested that cargo could issue a warning (and I would say possibly halt or prompt for confirmation) under bad configuration like this. I would not provide an --override as some developers would likely add that to all command lines before even being aware of the potential issue. Also maybe "build to a subdirectory of that setting, using a unique directory name each time, possibly copying artifacts from a prior build before optionally deleting that prior build, partially to avoid issues such as this but also so that there can be a record of builds, and only delete subdirectories of that setting that match a cargo naming convention, or contain a specific file, or something."

**Notes**

Output of `cargo version`:

```text
[2021-06-26 07:50:42]:jw@HAL9000-6WQ9TQ2:~/.cargo
$ cargo version
cargo 1.53.0 (4369396ce 2021-04-27)
```

I use cargo for Linux under WSL, but I am not sure that is relevant.

https://users.rust-lang.org/t/cargo-clean-removing-irrelevant-files-and-directories-from-tmp/61556

**Comment by deliverystack** [comment]
Added additional suggestions about using subdirectories of build directory

**Comment by weihanglo** [comment]
Going to close this issue as [the discussion in the forum](https://users.rust-lang.org/t/cargo-clean-removing-irrelevant-files-and-directories-from-tmp/61556) is pretty clear about the default behaivor and configuration. The help manual of `cargo clean` also [states that](https://doc.rust-lang.org/nightly/cargo/commands/cargo-clean.html#description): _“With no options, `cargo clean` will delete the entire target directory.”_

> Added additional suggestions about using subdirectories of build directory

This is unlikely to happen as it would be a breaking change.

Thank you for the detailed report anyway.

**Comment by weihanglo** [comment]
See related issue https://github.com/rust-lang/cargo/issues/9192

**Comment by BartMassey** [comment]
As long as #9192 is open we're going to see people accidentally deleting random directory trees on their target machine. I'm not comfortable with that, especially since it's going to bite new Rustaceans the hardest. The documentation is a bit hard to find and hard to understand, and conflicts hard with user expectations. Until #9192 hit me, I didn't imagine that `cargo clean --target` was effectively an alias of `rm -rf`, and I've been using Rust for a long time.

All of that said, #9192 is probably the place to continue this discussion.
