### ISSUE TITLE
Windows environment variables are case preserving (but case-insensitive)

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/cargo#9630]
I recently submitted a PR to stop Rust ASCII upper casing environment variables: https://github.com/rust-lang/rust/pull/85270. This causes the following test to fail.

https://github.com/rust-lang/cargo/blob/36917524b96ebe701b5006b8773042dace8bca05/tests/testsuite/tool_paths.rs#L360-L373 

I think it's because something relies on a new process upper casing key names? Which only happened before because Rust manually ASCII upper cased keys when starting a new process.

---

Hm, that seems to be the assumption here:

https://github.com/rust-lang/cargo/blob/36917524b96ebe701b5006b8773042dace8bca05/src/cargo/util/config/mod.rs#L698-L703

Whereas Windows itself does no such conversion.

---

cc @ehuss ? (only because you most recently touched the relevant test 🙂)

**Comment by ChrisDenton** [comment]
Here's a quick summary of the issue the linked PR seeks to address (using a few simple Rust programs you can try):

<details>

`listenv.rs`:
```rust
fn main() {
    for (key, _) in std::env::vars() {
        println!("{}", key);
    }
}
```

`spawn.rs`:
```rust
fn main() -> std::io::Result<()> {
    std::process::Command::new(r".\listenv.exe").spawn()?.wait()?;
    Ok(())
}
```

`withenv.rs`
```rust
fn main() ->  std::io::Result<()> {
    std::process::Command::new(r".\listenv.exe").env("hello", "world").spawn()?.wait()?;
    Ok(())
}
```

Compile all these with Rust:

```
Z:\test> rustc listenv.rs
Z:\test> rustc spawn.rs
Z:\test> rustc withenv.rs
```

If you run `.\listenv.exe` you should see environment keys with lower case values (e.g. "windir", "Path", "ProgramFiles", etc). The same goes for `.\spawn.exe`. However `.\withenv.exe` invokes Rust's ASCII upper casing behaviour and therefore all keys are upper cased (or were, if my PR gets merged).

Note that in any case, `std::env::var(key)` will work case-insensitively.

</details>

**Comment by ehuss** [comment]
I posted #9646 to disable the test on Windows for now.  Once that is merged, I'll update rust-lang/rust, and then re-approve your PR.   Afterwards, I'll work on fixing Cargo to work with the preserved casing.

**Comment by ChrisDenton** [comment]
Thanks! I've added a comment to my PR with a (hopefully accurate) summary of the issue.
