### ISSUE TITLE
Cargo.lock updated when running cargo publish, causing git error

### ISSUE THREAD

**Issue by TheDutchMC** [rust-lang/cargo#9636]
**Problem**

When running `cargo publish`, the `Cargo.lock` file can get updated. For binaries I've been advised to include this in the git repo. Because of this update, cargo publish will give an error saying that `Cargo.lock` hasn't yet been committed yet, which makes sense since cargo just updated it

**Steps**

1. Have Cargo.lock in a git repository, and have it not be excluded
2. run Cargo publish
3. cargo will give the error

**Possible Solution(s)**

A possible solution would be to ignore if Cargo.lock is committed or not. A better solution would be to perform the git check *before* updating the Cargo.lock file

**Notes**
While this isn't a high priority bug of any sorts, it definitely is an inconvenience.

Output of `cargo version`: `cargo 1.52.0 (69767412a 2021-04-21)`

**Comment by ehuss** [comment]
Hm, that's strange!  I'm uncertain how to reproduce that, as Cargo generates a new `Cargo.lock` in memory and shouldn't modify the one currently checked out.  Can you put together some reproduction steps or a repository I can check out?  Something like this should work:

```
cargo new foo
cd foo
cargo generate-lockfile
git add .gitignore src Cargo.toml Cargo.lock
git commit -m test
cargo publish --token xyz
```

(of course, the last step will fail to actually publish, but there shouldn't be any errors about uncomitted Cargo.lock)

**Comment by TheDutchMC** [comment]
I'm unable to reproduce it on my laptop either, strange enough.

The issue occurred for me on my desktop, running WSL2 (Ubuntu) under Windows 10 Pro, on the following repo: https://github.com/TheDutchMC/GSync

**Comment by ehuss** [comment]
Oh, I can think of one way to reproduce it.  If you modify `Cargo.toml`, and commit that without running any cargo commands to update `Cargo.lock`, then it will complain. It does a check to verify that `Cargo.lock` is up-to-date relative to what is specified in `Cargo.toml`.  Maybe you updated the version just before publishing?

**Comment by TheDutchMC** [comment]
Thats definitely a possibility yeah!
I imagine people do these version bumps often before releasing (At least, I do), is this intended behaviour, or should we want to allow a difference in package version within the Cargo.lock file?

**Comment by ehuss** [comment]
Yea, that is intentional. We want to make sure that the `Cargo.lock` is up-to-date before continuing.

**Comment by TheDutchMC** [comment]
Check!

I think it's safe to close this issue then!
