### ISSUE TITLE
Docs for documentation tests should mention where doctests are picked up from (e.g. not from files in tests/*)

### ISSUE THREAD

**Issue by robinst** [rust-lang/cargo#9648]
(@GuillaumeGomez asked me to open an issue here, see his comment: https://github.com/GuillaumeGomez/doc-comment/issues/25#issuecomment-734745278)

The docs for documentation tests (https://doc.rust-lang.org/rustdoc/documentation-tests.html) don't currently mention in which files doctests can be put. E.g. they work if put into `src/*` files, but not in integration test files in `tests/*`. It would be good if that was mentioned there.

**Comment by weihanglo** [comment]
Close as #10726 mentioning "doctests only applied to lib target" in more places (https://github.com/rust-lang/cargo/pull/10726/commits/78604581499a96cbb789fcc7f4924db1ebc223b3, https://github.com/rust-lang/cargo/pull/10726/commits/2c9cfd6485009c742698582e3e92b04dcd39b63f)
