### ISSUE TITLE
Target-specific workspace default-members (or excludes)

### ISSUE THREAD

**Issue by ratijas** [rust-lang/cargo#9650]
**Describe the problem you are trying to solve**

I want to exclude (or rather, specify different subset of default members) for certain platforms in cargo toml/config.

**Describe the solution you'd like**

Just like there are triples-specific overrides in _.cargo/config.toml_, I'd like to see workspace-related keys there.

My primary use case is to disable certain example (implemented as a full-blown workspace member) when compiling on Windows + MinGW toolchain, because certain libraries (namely, QtWebEngine) are not easily available there. So, I'd expect something like this in my workspace root _Cargo.toml_:

```toml
[workspace]
members = [
    'qmetaobject',
    'examples/todos',
    'examples/webengine',
]

[target.i686-pc-windows-gnu]
default-members = [
    'qmetaobject',
    'examples/todos',
]

```

**Notes**

I tried tweaking in such way both _Cargo.toml_ and _.cargo/config.toml_, and none of that currently works. The only workaround for now is manually commenting out or disabling a package via `--workspace --exclude <SPEC>`.

See https://github.com/woboq/qmetaobject-rs/issues/167

**Comment by epage** [comment]
This looks to be another variant of #6179.  Closing in favor of that so we keep the conversation in one place for how to solve the need, rather than focus on each individual idea separately.  If there is a reason for us to reconsider that, let us know!
