### ISSUE TITLE
cargo +nightly fails if running without rustup wrapper

### ISSUE THREAD

**Issue by gilescope** [rust-lang/cargo#9652]
It would be nice if +nightly was a no-op on nightly. (Happy to have a warning saying you're already on nightly, but would like to be able to run the same command line as on stable and have it work.)

**Comment by ehuss** [comment]
Can you say more about what this means?  What is the error you are experiencing?  What commands did you run? What versions are you using?  It shouldn't fail if nightly is already installed.

FWIW, the toolchain selection is done as part of rustup, so this is unlikely to be related to cargo.  Rustup has its own tracker at https://github.com/rust-lang/rustup.

**Comment by gilescope** [comment]
If nightly is the default toolchain then cargo +nightly check for example
fails because it’s already on nightly.

**Comment by ehuss** [comment]
What is the error that you are getting?

**Comment by gilescope** [comment]
No subcommand +nightly

**Comment by gilescope** [comment]
Ah. +nighlty on nightly works fine on windows and linux. This seems to only
be osx specific hickup.

**Comment by ehuss** [comment]
That indicates that it isn't running the rustup wrapper. I would check that your `PATH` is configured properly (adding `~/.cargo/bin` towards the front).  You can also check by running `which cargo` to check which it is running and make sure it says `~/.cargo/bin/cargo`.

**Comment by gilescope** [comment]
Ah didn’t realise that it was part of rustup and not part of cargo. I guess
it’s rare enough that we don’t want to give a specialised error message in
cargo.

**Comment by VincentWo** [comment]
I think it would still be nice to give an special error for this case. Rustup is the official way of installing Rust and a lot of tutorials use it, this could be confusing to newcomers (or in this case confused you)

Especially since this probably isn't the easiest term to google for

**Comment by gilescope** [comment]
Have also hit this a different way this week on a different OS. Nixos
doesn’t use rustup and thus any example with +stable or + nightly fails.

**Comment by ehuss** [comment]
Closing in favor of #10900.
