### ISSUE TITLE
cargo-fmt cleans up /// cargo-doc-tables

### ISSUE THREAD

**Issue by meltyness** [rust-lang/cargo#9656]
**Describe the problem you are trying to solve**
cargo-fmt leaves doc tables with whatever bizarre spacing was typed in.

**Describe the solution you'd like**
max and center contents within the typed table when cargo-fmt is run

**Notes**
cargo-doc supports tables: https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#tables

**Comment by ehuss** [comment]
Thanks for the report, would you mind moving it to https://github.com/rust-lang/rustfmt/issues?  `rustfmt` is the tool that drives the formatting.

**Comment by meltyness** [comment]
Done
