### ISSUE TITLE
Standard library panicking

### ISSUE THREAD

**Issue by BrandonLeeDotDev** [rust-lang/cargo#9664]
thread '<unnamed>' panicked at 'removal index (is 1) should be < len (is 1)', library/alloc/src/vec/mod.rs:1355:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::remove::assert_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/mod.rs:1355:13
   3: alloc::vec::Vec<T,A>::remove
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1360:13

**Comment by Eh2406** [comment]
What are the instructions to reproduce?

**Comment by BrandonLeeDotDev** [comment]
I created a global static mutable matrix with embedded vectors, a for loop to remove items from the one of the embedded vectors and a counter to decide what index to remove. If index 0 was removed, moving 1 to 0, and the counter was on the second pass at 1 it would panic.

**Comment by BrandonLeeDotDev** [comment]
I dont know if it panicked every-time... the matrix has almost 300k addresses / indices / locations.

**Comment by Eh2406** [comment]
It would be much easier to help you if there was code that we could run to see the problem.

**Comment by BrandonLeeDotDev** [comment]
Ive already solved the problem for myself... I was under the impression libraries should not be crashing for this reason.

**Comment by Eh2406** [comment]
I agree, and would like to see what makes the bug to happen so we can get it fixed.

**Comment by BrandonLeeDotDev** [comment]
Ill rebuild a non project specific version and randomize the removal / entry of arbitrary data... just give me a bit to do it... Im right in the middle of this project, but do have time to work on this...

**Comment by BrandonLeeDotDev** [comment]
```
static NUM: f64 = 4.0;

static INCRIMENT: f64 = 0.5;

struct Data {
    block: Vec<Block2>,
}

struct Block2 {
    block_data: f64,
    block: Vec<Block3>,
}

struct Block3 {
    block_data: f64,
    block: Vec<Block4>,
}

struct Block4 {
    block_data: f64,
    block: Vec<FinalData>,
}

struct FinalData {
    data: f64,
}

static mut IterationData: Data = Data { block: Vec::new() };

fn main(){
    unsafe {
        let mut count = 0.0;
                let mut block2_vec = vec![];

                let mut block2_data = 0.0;

                for _ in 0..(NUM / INCRIMENT) as usize
                {
                    let mut block3_vec = vec![];

                    let mut block3_data = 0.0;

                    for _ in 0..(NUM / INCRIMENT) as usize
                    {

                        let mut block4_vec = vec![];

                        let mut block4_data = 0.0;

                        for _ in 0..(NUM / INCRIMENT) as usize  {
                                block4_vec.push(FinalData {
                                    data: count,
                                });

                                count+=1.0;

                            block4_data += INCRIMENT;
                        }

                        block3_vec.push(Block4{
                            block_data: count,
                            block: block4_vec
                        });

                        block3_data += INCRIMENT;
                    }

                    block2_vec.push(Block3 {
                        block_data: count,
                        block: block3_vec
                    });

                    block2_data += INCRIMENT;
                }

            IterationData.block.push(Block2 {
                block_data: count,
                block: block2_vec
            });

        loop{

            let mut count1 = 0;
            for i in &IterationData.block {
                let mut count2 = 0;
                for b1 in &i.block {
                    let mut count3 = 0;
                    for b2 in &b1.block {
                        let mut count4 = 0;
                        for b3 in &b2.block {

                                    IterationData.block[count1]
                                        .block[count2]
                                        .block[count3]
                                        .block
                                        .remove(count4);

                            count4+=1;
                        }
                        count3+=1;
                    }
                    count2+=1;
                }
                count1+=1;
            }
        }
    }
}
```

**Comment by Eh2406** [comment]
```rs
fn main(){
    vec![0.0].remove(1);
}
```
Indexing in Rust is 0 based. So the `vec![0.0]`, has a value at index `0` but no value at index `1`.  `remove` is documented to panic when the argument is out of bounds. https://doc.rust-lang.org/std/vec/struct.Vec.html#panics-6
