### ISSUE TITLE
Workspace::members returns all crates in a workspace regardless of wether they are in the Cargo.toml `members`

### ISSUE THREAD

**Issue by khuey** [rust-lang/cargo#9668]
Is there a way to get just the listed `members`?

**Comment by ehuss** [comment]
I don't see a public API for accessing that, no.

**Comment by khuey** [comment]
Would a PR to add `Workspace::named_members` (feel free to bikeshed) be accepted?

**Comment by ehuss** [comment]
Can you say more why you need it? Workspace members are members regardless if they are listed or not.

If it were be to added, I think it would likely best be an accessor in `WorkspaceRootConfig`.

**Comment by epage** [comment]
Considering implicit workspace members are members, and a use case hasn't been given in the last couple of years, I'm proposing to the cargo team that we close this.

**Comment by weihanglo** [comment]
Second this. We can explore later once we're confident in shipping more stable API for `cargo` library.
