### ISSUE TITLE
cargo build no-warning version that does not rebuild

### ISSUE THREAD

**Issue by lucaszanella** [rust-lang/cargo#9669]
The flag `-Awarnings`, when added like this:

`RUSTFLAGS=-Awarnings cargo build`
   
rebuild the entire project. It makes sense, of course, since the flags were changed.

However, disabling warnings is a very special case that should have an option on cargo that does not alter the flags and simply disables warnings. It's very annoying when you're developing and the project emits 70 warnings + 15 errors, and you have to find the errors in the middle of the warnings. And they are not even grouped together.

Putting `-Awarnings` and then taking it out makes the entire project rebuild, which takes 10 minutes for me. Not very good. A `cargo build --no-warnings` would be very useful.

**Comment by ehuss** [comment]
Thanks for the report!  I'm going to close as there are already several issues covering this request. In particular, #8716 for caching changes in RUSTFLAGS, and #5034 and #3591 for allow Cargo itself to control lint levels.
