### ISSUE TITLE
Support picking from multiple Rust version

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/cargo#967]
If Rust gains support for installing multiple versions in parallel (see https://github.com/rust-lang/rust/issues/19263 for details), Cargo should have a mechanism to pick which one is used. Maybe an environment variable? `RUSTC=rustc-beta cargo test`

**Comment by DeadDork** [comment]
+1

**Comment by alexcrichton** [comment]
I think that given the current state of affairs [multirust](https://github.com/brson/multirust) is filling this niche quite nicely, although I would still like a RUSTC env var

**Comment by SimonSapin** [comment]
Multirust is based on having multiple "toolchains", each containing different versions of an arbitrary number of tools, including rustc, rustdoc, and Cargo.

Long term, I think it makes more sense to stabilize the rustc command-line interface and have a single version of Cargo that can drives multiples versions of rustc+rustdoc.
