### ISSUE TITLE
cargo test invokes rustdoc with absolute paths, causing compile errors

### ISSUE THREAD

**Issue by kwi-dk** [rust-lang/cargo#9676]
**Problem**

`cargo test` invokes `rustdoc` with absolute paths, causing compile errors if the code depends on source paths being relative, e.g. through using
```rust
include!(concat!(env!("OUT_DIR"), "/", file!()));
```
to auto-include matching `build.rs`-generated code.

**Steps**
To demonstrate, let's make a [quine](https://en.wikipedia.org/wiki/Quine_(computing))!

1. Create a new Cargo binary project with `cargo new quine`, and put this in `src/main.rs`:
    ```rust
    const MAIN_SOURCE: &str = include_str!(concat!("../", file!()));

    fn main() {
        print!("{}", MAIN_SOURCE);
    }
    ```
    ✔️ `cargo run` shows that the code is working, and
    ✔️ `cargo test` confirms that our non-existing test suite is green.

2. This code works, but is horribly unorganized. The next obvious step is to create a separate library crate, so put this in `src/lib.rs`:
    ```rust
    pub const LIB_SOURCE: &str = include_str!(concat!("../", file!()));
    ```
    and add this line to the end of `main()`, in `src/main.rs`:
    ```rust
        print!("{}", quine::LIB_SOURCE);
    ```
    ✔️ `cargo run` works as expected, but...
    ❌ `cargo test` chokes when trying to run doc tests:
    ```
       Doc-tests quine
    error: couldn't read /data/projects/quine/src/..//data/projects/quine/src/lib.rs: No such file or directory (os error 2)
    ```
    `cargo test -v` confirms that Cargo is passing absolute source paths to `rustdoc`. If I run the same `rustdoc` command, except with a relative path to the source file, everything compiles as expected.

**Possible Solution(s)**

For now, my workaround is to disable doc tests in `Cargo.toml`, and then invoke `rustdoc` manually from build automation.
```toml
[lib]
doctest = false
```

But intuitively, I'd not expect the value of `path!()` to change between my normal build and my doc tests.
To ensure that, it seems that Cargo must pass a relative source path to `rustdoc`, not an absolute path.

**Notes**

Output of `cargo version`:

> cargo 1.53.0 (4369396ce 2021-04-27)
> cargo 1.55.0-nightly (3ebb5f15a 2021-07-02)

Confirmed with both above versions, on Linux and Windows.

**Comment by ehuss** [comment]
Thanks for the thorough report!  This is a known issue, and there is a fix on the nightly channel using the `-Z doctest-in-workspace` flag. If you could give it a try on your projects and report if there are any problems, that would be appreciated. Closing in favor of tracking issue #9427.

**Comment by kwi-dk** [comment]
Ah! I did see that issue, but it's talk of working directories seemed unrelated to my issue with absolute paths.

Nevertheless, `cargo +nightly -Z doctest-in-workspace test` does indeed solve the problem. Thanks!
