### ISSUE TITLE
Add `--check` flag to `cargo rustc`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/cargo#9678]
**Describe the problem you are trying to solve**

Running `cargo check` is useful to compile a crate quickly when the actually binary output is not needed. `cargo rustc` can be used to pass extra options to rustc only when compiling the 'main' crate. However, there is no (easy) way to combine these two commands - you can use use `cargo check` with `RUSTFLAGS` (which uses the flags when compiling every crate), or use `cargo rustc` with a non-check build.

**Describe the solution you'd like**

Add a `--check` flag to `cargo rustc`. This will perform a 'check' build, but allow passing additional compiler flags to the 'main' crate.

**Comment by ehuss** [comment]
It's undocumented, but you can run `cargo rustc --profile=check` to get that behavior.

**Comment by ehuss** [comment]
I'm going to close this as it is already implemented.  We will be likely stabilizing custom named profiles, and when I do that I'll try to make sure the documentation gets updated.
