### ISSUE TITLE
`cargo doc` should support documenting only dependencies

### ISSUE THREAD

**Issue by lilyball** [rust-lang/cargo#969]
The `cargo doc` command will document a package and all its dependencies, and supports `--no-deps` to only document the package. However, during development it can be useful to have the dependency documentation available without caring about the current crate's docs (notably, the current crate may not be in a compiling state). `cargo doc` should support this with a `--deps-only` flag, or alternatively with a `-p SPEC` flag a la `cargo test`.

**Comment by najamelan** [comment]
@alexcrichton So how do you document all dependencies, but not the current crate that doesn't compile? I don't quite get how the linked commit fixes this problem? Do we have to list all dependencies and all their dependencies manually on the cli? Or comment out all code in the current crate until it compiles?

And even after listing all dependencies, `--open` is now broken...:-(
