### ISSUE TITLE
Pass environment variables to dependencies.

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/cargo#97]
For cargo's `build` scripts, it would be handy to be able to pass arguments to them via environment variables.

Usage would look something like:

```
[dependency.foo]
git = "......"
env = ["BAR", "BAZ", "A=B"]
```

**Comment by ccll** [comment]
I found a use case, the [rust-ffmpeg-sys](https://github.com/meh/rust-ffmpeg) has a custom build.rs which allows you to pass a environment variable 'FFMPEG_DIR' to specify the path to the pre-compiled header/lib of FFMPEG.
So when my project depends on 'rust-ffmpeg-sys', it's better to allow the developer define the env var 'FFMPEG_DIR' directly in Cargo.toml, instead of define it outside of Cargo ecosystem.
Does that sound legitimate?

**Comment by alexcrichton** [comment]
@ccll note that this is a super old issue, dependencies today can [pass env vars to each other](http://doc.crates.io/build-script.html#the-links-manifest-key)

**Comment by ccll** [comment]
@alexcrichton Thanks for the tip, but it doesn't look like what I want.

![image](https://cloud.githubusercontent.com/assets/5366582/25836781/36efd3e0-34bc-11e7-9566-d90e4f5e7904.png)

What I want is to set env vars for `libfoo` from `libbar`'s config/manifest/buildscript, not the other way around, while I have control over `libbar`, but not `libfoo`. Also the env var name is distorted a bit automatically.
Is there any way to pass **arbitrarily named** env vars to **any upstream dependencies** (no necessarily immediate ones)?

**Comment by alexcrichton** [comment]
Correct yeah, that feature is covered by https://github.com/rust-lang/cargo/issues/3544

**Comment by ccll** [comment]
@alexcrichton I'm afraid it's still not quite the same feature.
What DEP_<name>_<key> does: down stream <-- set env <-- upstream
What I want: down stream --> set env --> upstream  (to control the building behavior of upstream lib)

#3544 only eliminate the mandatory requirements on 'links' key, but still not solving the control flow direction, right? Am I correct on understanding DEP_<name>_<key> and #3544 ?

**Comment by alexcrichton** [comment]
@ccll functionality like that is typically exposed through features on crates, rather than programmatic access to env vars I believe.

**Comment by ccll** [comment]
@alexcrichton 'feature' works like a Boolean flag, but sometimes a String value is needed.
In the `rust-ffmpeg-sys` package, the package needs to know where to find the pre-built binaries and header files of FFMpeg, so the down-stream application code who uses the package needs to fill a env var 'FFMPEG_DIR' to tell it.

I think this is a very valid use case, especially in code involving FFI with existing C library.

**Comment by alexcrichton** [comment]
Ah yes that's currently not supported, but if you'd like to open an issue that'd be great!

**Comment by ccll** [comment]
@alexcrichton How about re-opening this issue? No?

**Comment by alexcrichton** [comment]
Mind opening a new one? This one's got a fair bit of semi-unlreated discussion now unfortunately :(

**Comment by ccll** [comment]
@alexcrichton Sure, moved to #4121 .
