### ISSUE TITLE
  Rust WASM toolchain not installed, please install it!

### ISSUE THREAD

**Issue by nuel77** [rust-lang/cargo#9709]
**Problem**
trying to run the https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/ tutorial and running into errors.
the environment is WSL2 for windows.

**Steps**
1. installed latest version of rust and nightly -- (stable1.53.0, nightly 1.55.0)
2. cargo run --release

Error message on terminal:
  ------------------------------------------------------------
error: failed to run custom build command for `node-template-runtime v3.0.0 (/mnt/d/Desktop/Rust/Substrate/substrate-node-template/runtime)`

Caused by:
  process didn't exit successfully: `/mnt/d/Desktop/Rust/Substrate/substrate-node-template/target/release/build/node-template-runtime-c51364d566070823/build-script-build` (exit status: 1)
  --- stderr
  Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
  warning: output filename collision.
  The bin target `wasm-test` in package `wasm-test v1.0.0 (/tmp/.tmpiuxypU)` has the same output filename as the lib target `wasm_test` in package `wasm-test v1.0.0 (/tmp/.tmpiuxypU)`.
  Colliding filename is: /tmp/.tmpiuxypU/target/wasm32-unknown-unknown/debug/deps/wasm_test.wasm
  The output filenames should be unique.
  Consider changing their names to be unique or compiling them separately.
  This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
  If this looks unexpected, it may be a bug in Cargo. Please file a bug report at
  https://github.com/rust-lang/cargo/issues/ with as much information as you
  can provide.
  cargo 1.55.0-nightly (27277d966 2021-07-16) running on `x86_64-unknown-linux-gnu` target `wasm32-unknown-unknown`
  First unit: Unit { pkg: Package { id: PackageId { name: "wasm-test", version: "1.0.0", source: "/tmp/.tmpiuxypU" }, ..: ".." }, target: TargetInner { name: "wasm-test", doc: true, ..: with_path("/tmp/.tmpiuxypU/src/main.rs", Edition2018) }, profile: Profile { ..: default_dev() }, kind: Target(CompileTarget { name: "wasm32-unknown-unknown" }), mode: Build, features: [], is_std: false, dep_hash: 0 }
  Second unit: Unit { pkg: Package { id: PackageId { name: "wasm-test", version: "1.0.0", source: "/tmp/.tmpiuxypU" }, ..: ".." }, target: TargetInner { ..: lib_target("wasm_test", ["cdylib"], "/tmp/.tmpiuxypU/src/lib.rs", Edition2018) }, profile: Profile { ..: default_dev() }, kind: Target(CompileTarget { name: "wasm32-unknown-unknown" }), mode: Build, features: [], is_std: false, dep_hash: 0 }
     Compiling wasm-test v1.0.0 (/tmp/.tmpiuxypU)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed
    = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test` due to previous error
  warning: build failed, waiting for other jobs to finish...
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed
    = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  For more information about this error, try `rustc --explain E0463`.
  error: build failed
  ------------------------------------------------------------

warning: build failed, waiting for other jobs to finish...
error: build failed

**Notes**

Output of `cargo version`:
cargo 1.53.0 (4369396ce 2021-04-27)

**Comment by patricksjackson** [comment]
Did you get any errors when you tried installing the missing WASM toolchain? The command is in the error message above and the [Substrate guide](https://substrate.dev/docs/en/knowledgebase/getting-started/#2-rust-developer-environment) walks you through it as well.

```
rustup target add wasm32-unknown-unknown --toolchain nightly
```

**Comment by nuel77** [comment]
> Did you get any errors when you tried installing the missing WASM toolchain? The command is in the error message above and the [Substrate guide](https://substrate.dev/docs/en/knowledgebase/getting-started/#2-rust-developer-environment) walks you through it as well.
> 
> ```
> rustup target add wasm32-unknown-unknown --toolchain nightly
> ```

This solve the issue.. thanks!
