### ISSUE TITLE
proc macro && canadian cross toolchain && --target

### ISSUE THREAD

**Issue by jwinarske** [rust-lang/cargo#9713]
**Problem**
Not able to set sysroot for host (proc macro) when using --target on a Canadian Cross toolchain.

Using .cargo/config
```
 [target.x86_64-unknown-linux-gnu]
 rustflags = ["--sysroot", "/opt/poky/3.1.9/sysroots/x86_64-pokysdk-linux"]
```

I don't see my sysroot show up in -vv output.

**Notes**

Output of `cargo version`: 1.51.0

**Comment by jwinarske** [comment]
For the curious SDKs available here:  https://drive.google.com/drive/folders/1OfaYuU6tg97cd4WJfcUsuwrxrgHFoCwG?usp=sharing
corei7(x86_64) and rpi4(aarch64) includes rust-cross-canadian 1.51.0 + clang 10.0.1. 

Basic setup is:
```
./poky-glibc-x86_64-core-image-minimal-corei7-64-intel-corei7-64-toolchain-3.1.9.sh
. /opt/poky/3.1.9/environment-setup-corei7-64-poky-linux
sudo chown $USER:$USER -R /opt/poky/3.1.9/sysroots/corei7-64-poky-linux/home/cargo
cargo build --lib --target x86_64-poky-linux
```

I need a way to pass a sysroot to HOST for proc macro.  Nothing I have tried appears to work.  Any ideas?

**Comment by ehuss** [comment]
Similar to #9712, I don't understand what is being reported here.  Can you show a reproduction of what you are trying to do?

**Comment by ehuss** [comment]
Without more information, I'm going to close.  But if you can provide the information above, feel free to reopen.
