### ISSUE TITLE
Change the deafult git branch

### ISSUE THREAD

**Issue by Prajwal-Koirala** [rust-lang/cargo#9716]
Hello,
So when a person runs `cargo init main` if u check the folder the main repo is in `master` channel and i was wondering if it is possible to change it to `main`

**Comment by ehuss** [comment]
`cargo init` should use the default branch you have configured in the global git configuration. You can update that with `git config --global init.defaultBranch main`

**Comment by XsongyangX** [comment]
It would be nice if `main` becomes on Cargo instead of `master`, just like how Git is right now.
