### ISSUE TITLE
fail for cargo build 

### ISSUE THREAD

**Issue by jessica-ji** [rust-lang/cargo#9719]
run cargo build but meet some problems:
linuxmachine: ~/work/crosvm/crosvm/src/platform/crosvm$ cargo build
warning: /home/abstract/work/crosvm/crosvm/src/platform/crosvm/Cargo.toml: file found to be present in multiple build targets: /home/abstract/work/crosvm/crosvm/src/platform/crosvm/src/main.rs
   Compiling cras-sys v0.1.0 (/home/abstract/work/crosvm/crosvm/src/third_party/adhd/cras/client/cras-sys)
   Compiling minijail-sys v0.0.12 (/home/abstract/work/crosvm/crosvm/src/aosp/external/minijail/rust/minijail-sys)
   Compiling gpu_display v0.1.0 (/home/abstract/work/crosvm/crosvm/src/platform/crosvm/gpu_display)
   Compiling syn v1.0.72
   Compiling memoffset v0.5.6
   Compiling futures v0.3.13
error: failed to run custom build command for `cras-sys v0.1.0 (/home/abstract/work/crosvm/crosvm/src/third_party/adhd/cras/client/cras-sys)`

Caused by:
  process didn't exit successfully: `/home/abstract/work/crosvm/crosvm/src/platform/crosvm/target/debug/build/cras-sys-30009a23de3557e0/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=../../src/common/cras_bindgen.h

  --- stderr
  thread 'main' panicked at 'Failed in bindgen command.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/abstract/work/crosvm/crosvm/src/third_party/adhd/cras/client/cras-sys/build.rs:33:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

how to handle it?

**Comment by ehuss** [comment]
Hi! This does not appear to be a Cargo issue, but is instead an error generated by the `cras-sys` package. Perhaps try asking in their issue tracker, or try one of the user forums like [urlo](https://users.rust-lang.org/)?

**Comment by ehuss** [comment]
Closing as this does not appear to be an issue with Cargo.
