### ISSUE TITLE
Exact features set to be used for testing

### ISSUE THREAD

**Issue by vporton** [rust-lang/cargo#9725]
**Describe the problem you are trying to solve**
The software needs to be recompiled several times to test with every set of features to be tested with.

Moreover, there is no automated way to make cargo to test a package with several different sets of features.

**Describe the solution you'd like**
Please add to target section of `Cargo.toml` new key `exact-features` that will cause this target to be compiled with this exact set of features, independently of what features are specified in the command line:

```
exact-features = ["use_assembler", "no_api_v2"]
```

This would allow to use such a target together with `test = true` to test it fully automatically.

**Notes**
Also, the suggested feature is useful for software requiring especially good reliability to complicate user to change features (but the reason I suggest it is for testing).

**Comment by ehuss** [comment]
Thanks for the suggestion!  I'm not sure I fully understand what is being requested here, but I believe this is suggesting that [cargo targets](https://doc.rust-lang.org/cargo/reference/cargo-targets.html) could have certain features enabled by default.  If so, I believe this is covered by [RFC 3020](https://github.com/rust-lang/rfcs/pull/3020).  Regardless, a major change like this should probably go through the RFC process.
