### ISSUE TITLE
Symbol name collision: What is the correct, idiomatic way to handle this?

### ISSUE THREAD

**Issue by koraa** [rust-lang/cargo#9726]
Morning!

Insert the usual salutations and overflowing expressions of gratitude in this line. Cargo is stunningly good!

# Situation: Resolving the symbol collision manually using `ar`

I have an issue with a symbol collision: I am linking in a project against the pqcrypto project and against the rust_sodium package; both ultimately resolve to ffi interfaces embedding plain C libs. Both of these libraries have a `randombytes` symbol to extract entropy from the system RNG.

I am currently dealing with this (successfully) by using the `ar` command to erase the randombytes symbol from the pqcrypto archives:

    ar d ./target/debug/deps/libpqcrypto_*.rlib randombytes.o

This does solve the issue for me and allows me to compile my project successfully. So:

1. Compile, producing a predictable error.
2. Modify the object archives.
3. Compile with my modifications in the compiler cache.

# Question: Build script executing a hook after the compilation but before the linking phase.

What would be the correct way to automate this process? Certainly with a build script, but I need to essentially interrupt the build process after the compilation phase for each dependency and run my script; I'd need to either access gcc/clang/llvm system tools to modify the archives or access some rusty library for dealing with object archives (does that even exist? Does rustc/cargo expose such a thing?). And I would need to run this build script every time mutating child dependencies when my software is exposed as a library.

This seems all very suboptimal and hacky… I am assuming a clean solution for that situation is ATM out of reach or is there something I am missing?

# Alternative

While in my specific situation having libpqclean use the libsodium RNG is quite nice, I think a more comprehensive and user-friendly solution would be implementing some sort of namespace isolation for FFI symbols. E.g. automatically prefixing all pqclean symbols with `<uuid>_pqclean_`, not allowing FFI symbols to leak their namespace across crate boundaries unless explicitly accessed…

**Comment by ehuss** [comment]
Unfortunately Cargo (and even rustc) does not provide a great deal of control over the linking process.  You can maybe play around with some of the options like `-Zno-link` to drive the linking yourself.  Otherwise, I think this issue is a little too open-ended.  It might be best to discuss the problem on one of the forums first (like [urlo](https://users.rust-lang.org/)), and see if others have ideas on approaches you can take.  Closing this, as ultimately a large feature request should go through the RFC process.
