### ISSUE TITLE
doctests run via cargo test are not silenced with --quiet

### ISSUE THREAD

**Issue by slurps-mad-rips** [rust-lang/cargo#9728]
**Problem**
When passing `--quiet` to `cargo test`, doctests are still printed in a verbose style, a though `--quiet` had not been forwarded to them (output cut for brevity)

```console
$ cargo test --quiet

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 36 tests
test src/lib.rs - (line 156) ... ignored
test src/lib.rs - (line 173) ... ignored
test src/lib.rs - (line 71) ... ok
test src/lib.rs - (line 27) ... ok
test src/lib.rs - (line 10) ... ok
# ...
test result: ok. 34 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 2.48s
```

This can also be seen by running `cargo test -- --quiet`, which manually passes `--quiet` to each doctest.

```console
$ cargo test -- --quiet

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests my-crate


running 36 tests
ii..................................
test result: ok. 34 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 2.51s
```

**Steps**

1. Add several doctests to any library crate
2. Run `cargo test --quiet`
3. Run `cargo test -- --quiet`

**Possible Solution(s)**
After looking in [src/cargo/ops/cargo_test.rs](https://github.com/rust-lang/cargo/blob/58a961314437258065e23cb6316dfc121d96fb71/src/cargo/ops/cargo_test.rs), I noticed that `run_unit_tests` will [add `--quiet` to each target if `harness=true` and the verbosity is set to quiet](https://github.com/rust-lang/cargo/blob/58a961314437258065e23cb6316dfc121d96fb71/src/cargo/ops/cargo_test.rs#L108-L110). 

However, this same operation does not happen in `run_doc_tests`. Having had a brief look at the source it seems the same `unit.target.harness()` and `console.shell().verbosity()` could be done [after the `test_args` are pushed into the command](https://github.com/rust-lang/cargo/blob/58a961314437258065e23cb6316dfc121d96fb71/src/cargo/ops/cargo_test.rs#L235-L237)

This would explain why `--quiet` does not work, but `-- --quiet` *does*.

**Notes**

Output of `cargo version`: cargo 1.53.0 (4369396ce 2021-04-27)
OS: Windows 10

Although I linked above to recent commits, this code has remained untouched since March of 2021.

**Comment by ehuss** [comment]
Thanks for the report!  Yea, it should be easy to add.  No need to check for the harness, since rustdoc does not support custom harnesses.  It just needs to be passed as a `--test-arg`.
