### ISSUE TITLE
crates.io: Package Groups

### ISSUE THREAD

**Issue by reem** [rust-lang/cargo#975]
## Motivation

We want to support "special" or "blessed" packages and would also like to limit the contention for important names in a flat namespace.
## Overview

Cargo will support groups as package namespaces with special permissions. Any user can create a new group whose name is not taken and begin adding packages and owners to it. Packages in a group can be referenced in the `[dependencies]` section and on crates.io as `<group>/<package>`. Only owners of a group can add new packages to the group or update existing packages.
## Details

New cargo commands:

``` sh
cargo group create <name>
```

Creates a new blank group with the passed-in name, make yourself an owner, and push it.

``` sh
cargo group edit <name>
```

Download and open the group's configuration as a `toml` file and edit it with `$EDITOR`. This includes description, members, etc. Only owners of a group may run this command.

Adding a package to a group is as easy as adding `group = "<name>"` to the `[package]` section of that package's `Cargo.toml` and running `cargo publish`. Permission to do this action is checked during `cargo publish`.

Expressing a dependency on a package within a group is the same as with a normal package, except the package is referred to as `<group>/<package>` in `Cargo.toml`. Notably, the name of the package does _not_ change, and you still access the crate by doing `extern crate <package>`. This has the potential to cause some naming conflicts, but cargo could provide a solution to this by adding optional `alias` metadata to a dependency that tells cargo what name it should use when linking that dependency.

Each group gets its own page on crates.io that shows all the packages within it, and all packages in a group share owners.
### Group configuration

`cargo group edit <name>` brings up the configuration file for a group, which contains the following structure in toml:

Necessary:

```
name
owners
```

Optional:

```
description
homepage
```

More fields could be added if/when they are needed.

**Comment by sergey-shandar** [comment]
@steveklabnik the link http://discuss.rust-lang.org/t/crates-io-package-policies/1041 is broken.

**Comment by steveklabnik** [comment]
It's https://internals.rust-lang.org/t/crates-io-package-policies/1041 now :)
