### ISSUE TITLE
Please publish new version of cargo-platform to include the license files

### ISSUE THREAD

**Issue by erickt** [rust-lang/cargo#9758]
The published version of `cargo-platform` does not include the LICENSE-APACHE or LICENSE-MIT files, which can be seen on https://docs.rs/crate/cargo-platform/0.1.1/source/. Could a new version be published that includes these files? This makes it much easier to audit that the code to make sure it is correctly licensed.

There were also a handful of small clippy fixes since `cargo-platform` was last published, but as best as I can tell, they don't appear to be significant changes.

**Possible Solution(s)**

It appears that all we need to do to address this is to:

* Bump the cargo-platform to 0.1.2
* Verify that `cargo publish --list` includes LICENSE-APACHE and LICENSE-MIT
* Publish cargo-platform 0.1.2

Thanks so much!

**Comment by ehuss** [comment]
Feel free to post a PR to bump the version, and I can publish it.
