### ISSUE TITLE
Cannot get sources from https://crates.io as curl fails the certificate check

### ISSUE THREAD

**Issue by Siosm** [rust-lang/cargo#976]
Building any project with dependencies on crates.io, with the latest nightly, on Arch Linux, ends with this error:
```
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading pkg-config v0.0.1
Unable to get packages from source

Caused by:
  Failed to download package `pkg-config v0.0.1` from https://crates.io/api/v1/crates/pkg-config/0.0.1/download

Caused by:
  Peer certificate cannot be authenticated with given CA certificates
```

Sample Cargo.toml reproducing the issue:
```
$ cat Cargo.toml
[package]

name = "nickel-demo"
version = "0.0.1"
authors = ["Timothée Ravier <tim@siosm.fr>"]

[dependencies.nickel]

git = "https://github.com/nickel-org/nickel.rs.git"
```

And version info:
```
$ rustc --version=verbose
rustc 0.13.0-nightly (395901393 2014-11-24 00:46:30 +0000)
binary: rustc
commit-hash: 395901393c369c910a8ae36ace71402cb206d217
commit-date: 2014-11-24 00:46:30 +0000
host: x86_64-unknown-linux-gnu
release: 0.13.0-nightly
$ cargo --version
cargo 0.0.1-pre-nightly (1bdfb25 2014-11-20 19:29:22 +0000)
```

Using curl manually gives the following output:
```
$ curl -v https://crates.io/api/v1/crates/pkg-config/0.0.1/download
* Hostname was NOT found in DNS cache
*   Trying 107.20.211.76...
* Connected to crates.io (107.20.211.76) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=GT87339749; OU=See www.rapidssl.com/resources/cps (c)14; OU=Domain Control Validated - RapidSSL(R); CN=crates.io
*        start date: 2014-11-06 11:11:23 GMT
*        expire date: 2015-11-09 14:30:14 GMT
*        subjectAltName: crates.io matched
*        issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
*        SSL certificate verify ok.
> GET /api/v1/crates/pkg-config/0.0.1/download HTTP/1.1
> User-Agent: curl/7.39.0
> Host: crates.io
> Accept: */*
> 
< HTTP/1.1 302 Found
< Connection: keep-alive
< Server: nginx
< Date: Tue, 25 Nov 2014 13:46:14 GMT
< Transfer-Encoding: chunked
< Set-Cookie: cargo_session=--3c156d7a3629aa08a1a0d538832f99ea30835cc8; HttpOnly; Secure; Path=/
< Location: https://crates-io.s3-us-west-1.amazonaws.com/crates/pkg-config/pkg-config-0.0.1.crate
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 vegur
< 
* Connection #0 to host crates.io left intact
```

And tracing cargo build with strace gives:
```
$ strace -f -e trace=file cargo build --verbose
(...)
 Downloading pkg-config v0.0.1
stat("/home/tim/.cargo/registry/cache/github.com-1ecc6299db9ec823", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getcwd("/home/tim/projects/perso/rust/nickel-demo", 2048) = 42
stat("/home/tim/projects/perso/rust/nickel-demo/.cargo/config", 0x7fffb1eba210) = -1 ENOENT (No such file or directory)
stat("/home/tim/projects/perso/rust/.cargo/config", 0x7fffb1eba210) = -1 ENOENT (No such file or directory)
stat("/home/tim/projects/perso/.cargo/config", 0x7fffb1eba210) = -1 ENOENT (No such file or directory)
stat("/home/tim/projects/.cargo/config", 0x7fffb1eba210) = -1 ENOENT (No such file or directory)
stat("/home/tim/.cargo/config", 0x7fffb1eba210) = -1 ENOENT (No such file or directory)
stat("/home/.cargo/config", 0x7fffb1eba210) = -1 ENOENT (No such file or directory)
stat("/.cargo/config", 0x7fffb1eba210)  = -1 ENOENT (No such file or directory)
access("/home/tim/.gitconfig", F_OK)    = 0
stat("/home/tim/.gitconfig", {st_mode=S_IFREG|0644, st_size=1541, ...}) = 0
stat("/home/tim/.gitconfig", {st_mode=S_IFREG|0644, st_size=1541, ...}) = 0
open("/home/tim/.gitconfig", O_RDONLY)  = 3
access("/home/tim/.config/git/config", F_OK) = -1 ENOENT (No such file or directory)
access("/etc/gitconfig", F_OK)          = -1 ENOENT (No such file or directory)
stat("/home/tim/.gitconfig", {st_mode=S_IFREG|0644, st_size=1541, ...}) = 0
open("/home/rustbuild/root64/ssl/openssl.cnf", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/var/ssl", 0x7fffb1eba7a0)        = -1 ENOENT (No such file or directory)
stat("/usr/share/ssl", 0x7fffb1eba7a0)  = -1 ENOENT (No such file or directory)
stat("/usr/local/ssl", 0x7fffb1eba7a0)  = -1 ENOENT (No such file or directory)
stat("/usr/local/openssl", 0x7fffb1eba7a0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/lib/ssl", 0x7fffb1eba7a0)    = -1 ENOENT (No such file or directory)
stat("/usr/ssl", 0x7fffb1eba7a0)        = -1 ENOENT (No such file or directory)
stat("/etc/openssl", 0x7fffb1eba7a0)    = -1 ENOENT (No such file or directory)
stat("/etc/pki/tls", 0x7fffb1eba7a0)    = -1 ENOENT (No such file or directory)
stat("/etc/ssl", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/gai.conf", O_RDONLY|O_CLOEXEC) = 3
stat("/dev/urandom", {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
open("/dev/urandom", O_RDONLY)          = 4
open("/etc/ssl/cert.pem", O_RDONLY)     = 4
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 4
open("/etc/ssl/cert.pem", O_RDONLY)     = 5
stat("/etc/ssl/certs/415660c1.0", 0x7fffb1eba1e0) = -1 ENOENT (No such file or directory)
Unable to get packages from source

Caused by:
  Failed to download package `pkg-config v0.0.1` from https://crates.io/api/v1/crates/pkg-config/0.0.1/download

Caused by:
  Peer certificate cannot be authenticated with given CA certificates
+++ exited with 101 +++
```

So it looks like the curl module is not looking at the correct place for certificate checking and so far my attempts to use environment variables such as `CURL_CA_BUNDLE` have been unsuccessful with cargo.

This may be a rust-curl bug but I can't confirm this because trying to build a minimal example with the curl-rust crate using cargo fails with the same error :(.

**Comment by Siosm** [comment]
I would like to reopen this issue because I think that I have found the underlying issue.

It looks like cargo is affected by this openssl bug: https://bugzilla.redhat.com/show_bug.cgi?id=1144808, which has only been recently been fixed in openssl 1.0.2b (see discussions and similar issues at https://gist.github.com/grawity/15eabf67191e17080241, https://bugs.archlinux.org/task/42921).

Both the stable (OpenSSL 1.0.1i 6 Aug 2014) and latest nightly (OpenSSL 1.0.2a 19 Mar 2015) cargo builds are affected by this.

As the openssl issue has been fixed in Arch Linux, the old certificates were removed (https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nss&id=d0ccc2d596f2414eb277aead14233a5cf06cbef5) thus I had this issue again using cargo.

The issue #1689 might also be a duplicate of this one.

A "simple" fix would be to rebuild cargo against openssl 1.0.2b or superior. In the mean time, manually re-adding the old certificates to the trust store will work as a workaround.

Another way to fix this would be to remove the old certificate from the certificate list sent by the server hosting crates.io, but this may prevent some clients on old systems without the updated certificate from connecting to it.

**Comment by Siosm** [comment]
Note: the ca-certificate-mozilla package update is currently in the testing repository on Arch Linux.

Workaround example on Arch Linux:
1. With ca-certificates-mozilla-3.19.1-1-x86_64.pkg.tar.xz installed:
  sudo cp /etc/ca-certificates/extracted/cadir/Verisign_Class_3_Public_Primary_Certification_Authority.pem /etc/ca-certificates/trust-source/anchors/
2. Run: sudo update-ca-trust or update the system to the latest ca-certificates-mozilla package (currently in testing).

**Comment by alexcrichton** [comment]
Wow, thanks for the thorough investigation @Siosm! I'll try to update OpenSSL on the bots soon.

**Comment by alexcrichton** [comment]
Deployed! The next nightlies should have the updated version of OpenSSL.

**Comment by sjmackenzie** [comment]
NixOS (nixos.org) is also affected by this issue.
I'm using rustcMaster (https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L4578) which points to this file https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/rustc/head.nix

Shall wait for the update or do it myself, @Siosm great job on finding the recon.

**Comment by globin** [comment]
@sjmackenzie using the cargoSnapshot binary works if you patch it to a newer version:
mayflower/nixpkgs@14c8a8e

If you find a real fix please give a notice. I can't seem to fix it by building cargo with the newest openssl.

**Comment by sjmackenzie** [comment]
@globin Thanks for the info! If you couldn't get it solved after trying the newest openssl, I've very curious to see if this issue is solved in other distros. btw I'm using it w.r.t. building `regex_syntax` as part of https://github.com/killercup/trpl-ebook.

It throws this error:

```
$ cargo run --verbose
 Downloading regex-syntax v0.1.0
Unable to get packages from source

Caused by:
  Failed to download package `regex-syntax v0.1.0` from https://crates.io/api/v1/crates/regex-syntax/0.1.0/download

Caused by:
  Peer certificate cannot be authenticated with given CA certificates

```

**Comment by globin** [comment]
It fails for any crate because of certificate failure with Amazon S3, curl does, too:
```
curl https://crates-io.s3-us-west-1.amazonaws.com/crates/cookie/cookie-0.1.21.crate -v
*   Trying 54.231.235.8...
* Connected to crates-io.s3-us-west-1.amazonaws.com (54.231.235.8) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2, TLS handshake, Client hello (1):
* TLSv1.2, TLS handshake, Server hello (2):
* TLSv1.2, TLS handshake, CERT (11):
* TLSv1.2, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
```

**Comment by sjmackenzie** [comment]
@globin https://github.com/NixOS/nixpkgs/issues/8431

**Comment by southerngs** [comment]
I'm experiencing the same problem with a Ubuntu 14.04.1 system.  I'm trying to figure out if there's a problem with my local configuration or if the problem is with Amazon S3 (or somewhere else).

**Comment by eat-multi** [comment]
Just to add, working for me now on Arch Linux x86_64 (4 hours fresh install):
```
> cargo -V 
cargo 0.3.0-nightly (a2dd2ac 2015-06-24) (built 2015-06-23) 
```
Version below did not work:
```
> cargo -V
cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)
```

**Comment by southerngs** [comment]
I tried on two other systems this evening (one Ubuntu 12.04 and one Arch Linux) and was not able to reproduce the problem.  The system that I have the problem with is behind a firewall and requires use of a proxy server (the ones that work are not).  I thought I would add this information in case anyone else sees this issue.

Also in all cases I'm testing with the release 1.0 version of Rust and included Cargo (`cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)`).

**Comment by azerupi** [comment]
I am also on Arch Linux and I have the same issue on stable that uses `cargo 0.2.0-nightly`. 

```
multirust: stable revision:

rustc 1.1.0 (35ceea399 2015-06-19)
cargo 0.2.0-nightly (a483581 2015-05-14) (built 2015-05-15)
```

But it's gone on the beta version that uses `cargo 0.3.0-nightly`

```
multirust: beta revision:

rustc 1.2.0-beta.1 (2ad26e850 2015-06-23)
cargo 0.3.0-nightly (a2dd2ac 2015-06-24) (built 2015-06-23)
```

So I guess I will have to stick to the beta version for the next couple of weeks until it moves to stable

**Comment by Keats** [comment]
On Archlinux as well, I didn't use Rust for about a month when it was working and i am now running into the issue, same after running a rustup to get 1.1:
```
cargo 0.2.0-nightly (a483581 2015-05-14) (built 2015-05-15)
```
I'll try @Siosm workaround when I have time

**Comment by eat-multi** [comment]
Just to note cargo `0.3.0-nightly` can be installed for older rusts (I'm on `1.0.0`). 
The newer version runs on my Arch box fine.

Binaries are available here:
https://crates.io/install

**Comment by Siosm** [comment]
As far as I'm concerned, this issue is only affecting the stable 1.0 and 1.1 releases. The 1.2 beta and nightly releases are working for me.

**Comment by tksfz** [comment]
Same here  (works on 1.2  beta and 1.3  nightly;  breaks  on  stable 1.1).

**Comment by sjmackenzie** [comment]
So the NixOS community have updated rust and it's without problem. I'm running `rustMaster` and `cargoSnapshot`.

```
$ rustc --version
rustc 1.1.0-dev (built 2015-06-05)
$ cargo --version
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-04-01)

```

**Comment by Keats** [comment]
It seems to now work for me, only did a pacman -Syu, nothing related to rust

**Comment by kendall** [comment]
I get this error trying to work through the guessing game toy program in the docs:

```
~/work/rust/gg • rustc --version -v 
rustc 1.2.0-beta.2 (c8bab9d06 2015-07-09)
binary: rustc
commit-hash: c8bab9d06a179028a0d5129aa62f09d694d9cc49
commit-date: 2015-07-09
host: x86_64-apple-darwin
release: 1.2.0-beta.2
```

```
~/work/rust/gg • openssl version
OpenSSL 1.0.2d 9 Jul 2015
```

Fetching libc by hand with curl seems fine:

```
~/work/rust/gg • curl -v https://crates.io/api/v1/crates/libc/0.1.9/download          
* Hostname was NOT found in DNS cache
*   Trying 54.243.176.56...
* Connected to crates.io (54.243.176.56) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: crates.io
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /api/v1/crates/libc/0.1.9/download HTTP/1.1
> User-Agent: curl/7.37.1
> Host: crates.io
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
* Server nginx is not blacklisted
< Server: nginx
< Date: Mon, 13 Jul 2015 14:44:00 GMT
< Transfer-Encoding: chunked
< Location: https://crates-io.s3-us-west-1.amazonaws.com/crates/libc/libc-0.1.9.crate
< Set-Cookie: cargo_session=--3c156d7a3629aa08a1a0d538832f99ea30835cc8; HttpOnly; Secure; Path=/
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 vegur
<
* Connection #0 to host crates.io left intact
```
