### ISSUE TITLE
warning: spurious network error

### ISSUE THREAD

**Issue by DIMHAKRYT** [rust-lang/cargo#9766]
Issue: When entering the "cargo build" command, an error occurs "warning: spurious network error"

Solution:

On windows go to the folder ".cargo" it is located in C:\Users\%USERPROFILE%\.cargo
Inside this folder there is a "config.toml" file, if it is not there, it's not scary, create a file with this name
in it, write the following lines:

[net]
git-fetch-with-cli = true
[source.crates-io]
replace-with = 'ustc'
[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

and save, congratulations everything should work!
most likely, the same solution works on Linux.

cargo 1.54.0 (5ae8d74b3 2021-06-22)
OS Windows 10 LTSC 1809, No Proxy and VPN 

I hope my solution will help someone

**Comment by ehuss** [comment]
Sorry, I'm not sure what this issue is for.  Is there something specific you are asking for here?

**Comment by DIMHAKRYT** [comment]
> Sorry, I'm not sure what this issue is for. Is there something specific you are asking for here?

I created this issue so that people who have the same problem can quickly find a solution, in other issues with similar problems I did not find a solution and described my method.

**Comment by patricksjackson** [comment]
This change causes Cargo to replace the crates.io registry with one owned by the University of Science and Technology of China.

That is **definitely not** what people should be doing to fix a network issue, with the possible exception of users within China. 

As explained in #9335, only the first two lines are necessary to fix the issue. 

```
[net]
git-fetch-with-cli = true
```

Please edit the advice in the original post to remove the unnecessary change to the registry in the event that someone else finds this issue and tries to follow it.

**Comment by DIMHAKRYT** [comment]
> This change causes Cargo to replace the crates.io registry with one owned by the University of Science and Technology of China.
> 
> That is **definitely not** what people should be doing to fix a network issue, with the possible exception of users within China.
> 
> As explained in #9335, only the first two lines are necessary to fix the issue.
> 
> ```
> [net]
> git-fetch-with-cli = true
> ```
> 
> Please edit the advice in the original post to remove the unnecessary change to the registry in the event that someone else finds this issue and tries to follow it.

there was an awkward situation, I will fix it now, thank you for your comment
