### ISSUE TITLE
unexpected cargo internal error

### ISSUE THREAD

**Issue by 0xdeafbeef** [rust-lang/cargo#9779]
**Problem**
Compiling project. Getting:
```
error: failed to download `nekoton v0.2.1 (https://github.com/broxus/nekoton.git#9bcb91ed)`

Caused by:
  unable to get packages from source

Caused by:
  failed to find nekoton v0.2.1 (https://github.com/broxus/nekoton.git#9bcb91ed) in path source
note: this is an unexpected cargo internal error

```
**Steps**

1. cargo check

**Notes**
I can attach  cargo lock, if needed. 
It happened after doing cargo update + changing git path for another dependence. 
Output of `cargo version`:
```
cargo 1.54.0 (5ae8d74b3 2021-06-22)
or
cargo 1.56.0-nightly (cc17afbb0 2021-08-02)
```

**Comment by 0xdeafbeef** [comment]
Removing of cargo lock fixes error

**Comment by ehuss** [comment]
If you switch `nekoton` back to the problematic revision (`cargo update -p nekoton --precise=9bcb91ede878bb3c0f1b3a5fa684e16971cd864b`), does it still reproduce the problem?  If so, can you inspect the contents of `~/.cargo/git/checkouts/nekoton-*/9bcb91e/` and check that it has a valid `Cargo.toml`?  My only thought is that the cache somehow got corrupted.

**Comment by ehuss** [comment]
I'm going to assume the cache got corrupted somehow, but if you're able to reproduce it, feel free to reopen.
