### ISSUE TITLE
Prepare stabilizing Rust 2021

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/cargo#9781]
Rust 2021 will probably be stabilied soon. Cargo also has knowledge of which editions are stable, so should be updated too. It'd be good to prepare that PR, so we can merge it as soon the edition is stabilized in rustc.

Alternatively, can we make it such that Cargo will allow `--edition=2021` but will not pass `-Z unstable-options` when the edition2021 cargo feature is not enabled? Then it'll be usable as soon as rustc allows it, without having to do the cargo change in sync.

**Comment by m-ou-se** [comment]
cc @ehuss

**Comment by ehuss** [comment]
> Alternatively, can we make it such that Cargo will allow `--edition=2021` but will not pass `-Z unstable-options`

I would kinda prefer to avoid doing that, since it requires probing rustc to see what it supports.  We can land cargo support within a few days after it lands in rustc. I'm not too concerned about the small window in-between.

I can post a draft PR to prep things, though.

**Comment by ehuss** [comment]
Opened https://github.com/rust-lang/cargo/pull/9800 for this.
