### ISSUE TITLE
`cargo package` and `cargo publish` cannot serialise Cargo.toml

### ISSUE THREAD

**Issue by EmmyGH** [rust-lang/cargo#9787]
**Problem**

Running `cargo package` or `cargo publish` yields an error, despite `cargo build` and `cargo run` working successfully.
```
error: failed to prepare local package for uploading

Caused by:
  values must be emitted before tables
```

**Steps**

1. Clone [the project I'm trying to publish](https://github.com/Dirout/larz)
2. Run `cargo package` or `cargo publish` on the project

**Notes**

Output of `cargo version`:
`cargo 1.56.0-nightly (b51439fd8 2021-08-09)`

Platform:
`aarch64-apple-darwin`, MacBook Air (M1, 2020), macOS Monterey (12.0 beta 5; 21A5304g)

**Comment by ehuss** [comment]
Thanks for the report!  I have posted a fix at #9789.
