### ISSUE TITLE
cargo test does not discover all tests in workspace

### ISSUE THREAD

**Issue by benwis** [rust-lang/cargo#9811]
**Problem**
I have a workspace with two members, member1 and member2, with a set of tests in each of them. Running cargo test from the workspace root finds the unit tests defined in member1, defined with #cfg[tests] in a test module. The member2 crate only has a set of integration tests in the tests folder. From the root, cargo test never runs the integration tests defined in the tests folder unless I comment out the unit tests in lib.rs in member1(I don't need to comment out the unit tests in domain.rs.

If I change into the member2 directory and run cargo test it can run the tests found within. If I run cargo test testname from the workspace root it will run tests from the integration tests in member2

This is the directory structure:
```
├── Cargo.lock
├── Cargo.toml
├── Dockerfile
├── README.md
├── configuration
│   ├── base.yml
│   ├── local.yml
│   ├── production.yml
│   └── test.yml
├── member1
│   ├── Cargo.toml
│   └── src
│       ├── domain.rs
│       ├── errors.rs
│       └── lib.rs
├── sqlx-data.json
└── member2
    ├── Cargo.toml
    ├── scripts
    │   └── init_db.sh
    ├── src
    │   ├── auth
    │   │   ├── handler.rs
    │   │   ├── hash.rs
    │   │   ├── lib.rs
    │   │   └── token.rs
    │   ├── auth.rs
    │   ├── configuration.rs
    │   ├── db.rs
    │   ├── db_models.rs
    │   ├── email_helpers.rs
    │   ├── errors.rs
    │   ├── gql_models.rs
    │   ├── lib.rs
    │   ├── main.rs
    │   ├── model.rs
    │   ├── routes
    │   │   ├── health_check.rs
    │   │   └── mod.rs
    │   └── startup.rs
    └── tests
        └── api
            ├── health_check.rs
            ├── helpers.rs
            ├── main.rs
            ├── mutations
            │   ├── invite.rs
            │   ├── login.rs
            │   ├── logout.rs
            │   ├── mod.rs
            │   ├── password_reset.rs
            │   ├── signup.rs
            │   └── team.rs
            └── query_tests.rs
```
Is there a way to run both the unit tests in member1 and the integration tests in member2 with one command? I can't think of a reason why cargo test or cargo test --all-targets doesn't run all of the tests. The tests in lib.rs have #[tokio::test] on them and the ones in domain.rs have #[test]. Does that matter?

**Notes**

Output of `cargo version`:
cargo 1.54.0 (5ae8d74b3 2021-06-22)
Macos on an Apple M1 Macbook
rustc 1.54.0 (a178d0322 2021-07-26)

**Comment by ehuss** [comment]
Hm, that shouldn't be happening unless there is a test failure.  If this isn't a public project, can you maybe put together a minimal reproduction?

**Comment by benwis** [comment]
You are absolutely right. I did not know that a test failure in one member would prevent running tests in the other member. I have fixed the test failure and it now performs as expected. Closing, but it'd be nice if that behavior is noted somewhere. :)
Thanks!
