### ISSUE TITLE
command for new workspace

### ISSUE THREAD

**Issue by tinsel-grumble** [rust-lang/cargo#9825]
**Describe the problem you are trying to solve**
use cargo new to make workspace for multi bins and libs

**Describe the solution you'd like**
option to cargo new to setup workspace Cargo.toml not just bin or lib. maybe relate to https://github.com/rust-lang/cargo/issues/9823

**Notes**

**Comment by ehuss** [comment]
Thanks for the suggestion!  I think this is pretty much the same as #8365 (combined with #9823), so closing as a duplicate of that.
