### ISSUE TITLE
Support `CLICOLOR`

### ISSUE THREAD

**Issue by Mythra** [rust-lang/cargo#9835]
**Describe the problem you are trying to solve**

On a current project I'm invoking cargo from some rust code, and capturing it's output to add some helpful debugging information to the beginning of the line outputs, i.e. running the cargo command with: `.stdout(Stdio::Piped())`. (as an example log line instead of printing: `Finished dev [unoptimized + debuginfo] target(s) in 0.32s`, it'd print something like: `Thread #2 | Finished dev [unoptimized + debuginfo] target(s) in 0.32s`.

The problem comes in when the tool wants the color output of cargo to be auto detected, similar to how it'd be run without using the tool. Unfortunately Cargo forces color auto detection based off of a tty. While this is a good fallback, it leads to the case where the tool, has to know that cargo supports: `--color` on certain commands (e.g. `cargo fmt --color` does not work), and how to append it when it wants to show the user the pretty colors they see without the tool. This means a very tight integration with cargo specifically, as opposed to being able to do something generic like it does for other tools.

**Describe the solution you'd like**

I'd propose adding support for `CLICOLOR` which is an environment variable that is not specific to just cargo (it's not standard, but there really isn't any one specific standard for colors here, [and is recommended in many other places/tools](https://bixense.com/clicolors/)). Which can be set to `1`, to tell a tool to _turn on colors_. The tool already does this today for other applications.

I should note there is also a semi-standard color option called: `NO_COLOR`, I'm happy to add support in for this as well, but I really want to focus on 'turning colors on' part which is tied to `CLICOLOR`.

**Notes**

- I'm happy to add support for this myself I just want to make sure moving forward using CLICOLOR, and supporting CLICOLOR is okay.

**Comment by ehuss** [comment]
Does the environment variable `CARGO_TERM_COLOR=always` not work for your case?

**Comment by Mythra** [comment]
I should note rustc also supports CLICOLOR: https://github.com/rust-lang/rust/pull/27867 (a friend pointed this out to me, along with things like clang/llvm).

Color always doesn't quite do what I want, my tool my be directed to a file in which case there should be no ansi color codes. or if someone does set CLICOLOR=0 I want turn it off. Now could I build a specific env var integration that used a cargo specific variable, swapping between `always`, and `never` which:

1. Isn't in the number format many other tools use for a Boolean state.
2. Is specific to cargo.

Sure, I could, but again then I'm bound to cargo. I'd rather use the widely supported generic argument that just works for everything else.

**Comment by epage** [comment]
This is supported as of #12751
