### ISSUE TITLE
Installing cargo via conda?

### ISSUE THREAD

**Issue by Hoeze** [rust-lang/cargo#9845]
Hi, I'm not sure if this is the correct place for my question, but anyways:

Is it possible to have `cargo` as a conda package, s.t. I can just call `conda install cargo`?
Or even better, would it be possible to directly integrate `cargo` with conda as done with `pip` and `bioconductor`?

**Comment by raygozag** [comment]
It actually isn't included in the rust conda package.

**Comment by ZWael** [comment]
Just a heads-up for anyone landing here: cargo is available via conda-forge. 
```{bash}
conda install -c conda-forge rust
......
cargo

Rust's package manager
Usage: cargo [OPTIONS] [COMMAND]
           cargo [OPTIONS] -Zscript <MANIFEST_RS> [ARGS]...

cargo --version
cargo 1.88.0 (873a06493 2025-05-10)
```
