### ISSUE TITLE
Error in "cargo run" on windows

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/cargo#986]
Occasionally, "cargo run" will fail. It tries to run the executable even though it doesn't exist:

```
C:\Users\Nathan\Dropbox\code\in-progress\rustvoxel>C:\cargo\bin\cargo run --release --verbose
       Fresh toml v0.1.2 (https://github.com/alexcrichton/toml-rs#1e35b001)
       Fresh rest_easy v0.0.1 (https://github.com/cmr/rest_easy#b648459e)
       Fresh openal-rs v0.0.1 (https://github.com/bjz/openal-rs/#72686f84)
       Fresh freetype-rs v0.0.0 (https://github.com/PistonDevelopers/freetype-rs#3f014f4a)
       Fresh sndfile v0.0.1 (https://github.com/jeremyletang/rust-sndfile#9a083d4a)
       Fresh image v0.2.0-alpha.2 (https://github.com/PistonDevelopers/rust-image#58ace47e)
       Fresh rust-xml v0.1.2-pre (https://github.com/netvl/rust-xml#2d9df326)
       Fresh gl_common v0.0.1 (https://github.com/bjz/gl-rs#157de977)
       Fresh semver v0.1.3 (https://github.com/rust-lang/semver#29212953)
       Fresh khronos_api v0.0.2 (https://github.com/bjz/gl-rs#157de977)
       Fresh glfw v0.0.1 (https://github.com/bjz/glfw-rs.git#a9fdda1e)
       Fresh gl_generator v0.0.1 (https://github.com/bjz/gl-rs#157de977)
       Fresh gl v0.0.1 (https://github.com/bjz/gl-rs#157de977)
       Fresh rustvoxel v0.0.1 (file:///C:/Users/Nathan/Dropbox/code/in-progress/rustvoxel)
     Running `target\release\voxelgame`
An unknown error occurred
Could not execute process `target\release\voxelgame` (status=never executed)

Caused by:
  file not found (OS Error 2: The system cannot find the file specified.
)
```

This is on Windows 7, 64-bit Rust, rustc 0.13.0-nightly (395901393 2014-11-24 00:46:30 +0000), cargo 0.0.1-pre-nightly (e1dc4bc 2014-11-25 21:59:15 +0000).

One way to reproduce this is to press ctrl-c before "cargo run" is finished with compilation, and then run the same command again. I'm not sure if it happens at any other time; it might, but I can't reproduce it. Even if it turns out that it only happens when you press ctrl-c, it's still a problem because sometimes it's convenient to interrupt compilation, and it shouldn't cause cargo to get into an inconsistent state.

This problem didn't happen with cargo 0.0.1-pre-nightly (603f29d 2014-11-01 19:29:48 +0000).

**Comment by alexcrichton** [comment]
I haven't seen this recently, so I'm going to close assuming that #1021 fixed it, but please feel free to reopen if you see it again!
