### ISSUE TITLE
When opening a web browser, the cargo should close as soon as the URL is open

### ISSUE THREAD

**Issue by alt-art** [rust-lang/cargo#9875]
**Problem**
When I use the command `cargo doc --open` it should close as soon as the URL is open. But it only closes if I use `Ctrl + c` or close the browser.

**Steps**

1. `cargo doc --open`
2. Wait for the `cargo` to close by itself

**Possible Solution(s)**
Use the [open](https://crates.io/crates/open) crate with the [that_in_background](https://docs.rs/open/2.0.1/open/fn.that_in_background.html) function. When I was making a command-line program that needed to open a URL, I had the same problem. Using this method, the problem was solved. The other away to resolve this is making a `thread::spawn(open(url))`

**Notes**

Output of `cargo version`: cargo 1.54.0 (5ae8d74b3 2021-06-22)

Web browser: Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)

My `uname -a` output: `Linux stonks 5.11.0-7620-generic #21~1626191760~20.04~55de9c3-Ubuntu SMP Wed Jul 21 20:31:55 UTC x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ehuss** [comment]
Thanks for the report!  Can you also say what platform you are on?  It is normal for cargo to exit with `--open` (I have not seen it stay running on windows, mac, or linux), so it may take a bit to debug what is going on here.

**Comment by alt-art** [comment]
My `uname -a` output: `Linux stonks 5.11.0-7620-generic #21~1626191760~20.04~55de9c3-Ubuntu SMP Wed Jul 21 20:31:55 UTC  x86_64 x86_64 x86_64 GNU/Linux`

**Comment by alt-art** [comment]
The other away to resolve this is making a thread spawn

**Comment by alt-art** [comment]
I don't know exactly when this started to happen or if it already happened, I only realized it was happening after I needed to use it. There's a chance that something on my system or browser is wrong, but the solution makes me believe it isn't.

**Comment by alt-art** [comment]
I searched the internet for fear. And saw that by default, xdg-open does not close itself when opening something.

**Comment by ehuss** [comment]
Hm, that's strange.  Cargo uses the `opener` crate to open the URL.  It [spawns the process in the background](https://github.com/Seeker14491/opener/blob/86e0a154d29a87fbde1dd2548ccb216f078951ee/opener/src/linux_and_more.rs#L52-L59), so it shouldn't cause cargo to stay running.  If you are comfortable with a debugger, you can attach to the process and see why it is hanging.

**Comment by ehuss** [comment]
I don't disagree that you are experiencing the hang, however I don't think anyone else has reported this problem, and I can't reproduce it, either.  The way the `opener` crate works is that it spawns the process for xdg-open, and does not wait for it to finish. There is no need for using threads in that situation. When cargo exits, whatever the xdg-open process did will continue running (such as the browser being launched).  Using a debugger could help isolate why it is hanging for you.

**Comment by alt-art** [comment]
> The way the `opener` crate works is that it spawns the process for xdg-open, and does not wait for it to finish.

You are wrong about that.

> [process::Comand::spawn()](https://doc.rust-lang.org/stable/std/process/struct.Command.html#method.spawn)
Executes the command as a child process.

**Comment by ehuss** [comment]
I'm pretty familiar with how the `spawn` function works.  Please use a friendlier tone in your responses.

You can try running a program such as this:

```rust
fn main() {
    use std::process::Command;

    Command::new("sleep").arg("1000").spawn().unwrap();
}
```

`cargo run` should return immediately after building, and you can run `ps` to verify that the `sleep 1000` process is still running.

**Comment by alt-art** [comment]
I ended up noticing that the expected result does not always happen in this bug, but that doesn't mean everything is fine when there is no window open, it is a fact that the bug will be present.
[Here is my video with the bug](https://youtu.be/9skYGdh0-RQ)

**Comment by alt-art** [comment]
Make this:
```rust
use std::process::Command;

fn main() {
    Command::new("xdg-open")
    .arg("/home/altart/code/genius-rs/target/doc/genius_rs/index.html")
    .spawn()
    .unwrap();
}
```

**Comment by ehuss** [comment]
Spawning the xdg-open process on my Linux system works fine, and the parent process exits as expected.  There is something unique about your environment that is causing the issue.  However, without more information, I don't think it is possible to help or understand your situation better.  If that basic program is hanging for you, I think the best route is to attach to it with a debugger and see where it is hanging.  If the process isn't running, then it may be an issue with the shell configuration.

**Comment by ehuss** [comment]
Other thought, what is your desktop environment (that is, which in [this list](https://github.com/freedesktop/xdg-utils/blob/d11b33ec7f24cfb1546f6b459611d440013bdc72/scripts/xdg-open.in#L523-L579) is xdg-open using)?  I'm wondering if for some reason that is grabbing onto the tty.  It may be becoming the session leader, in which case we may need to take extra steps to prevent that.

**Comment by alt-art** [comment]
$XDG_CURRENT_DESKTOP return i3, the selected DE is generic.

**Comment by alt-art** [comment]
As it's already become something out of scope, I think I'll solve this problem in another way. Thanks for the help!
