### ISSUE TITLE
Rust 1.55,  cargo rustc --release --verbose --profile dev :  error: usage of `--profile` requires `-Z unstable-options`

### ISSUE THREAD

**Issue by selassje** [rust-lang/cargo#9897]
**Problem**

This stopped working on 1.55 : 
cargo rustc --release --verbose --profile dev
error: usage of `--profile` requires `-Z unstable-options`

Works fine on 1,54

Output of `cargo version`:
cargo 1.55.0 (32da73ab1 2021-08-23)
release: 1.55.0
commit-hash: 32da73ab19417aa89686e1d85c1440b72fdf877d
commit-date: 2021-08-23

**Comment by ehuss** [comment]
Apologies!  I have posted #9898 to fix this.  In the meantime, `--profile=dev` is the default, so one workaround is to not use that option.
