### ISSUE TITLE
Compile-on-update mode

### ISSUE THREAD

**Issue by saosebastiao** [rust-lang/cargo#99]
I'm not sure if feature requests belong on here, but I'll try it out: 

Can we have a continuous compile mode like the `~compile` and `~run` modes from SBT? 

http://www.scala-sbt.org/0.13.5/docs/Getting-Started/Running.html

**Comment by marccarre** [comment]
Though more basic, `inotifywait` from [`inotify-tools`](https://github.com/rvoicilas/inotify-tools/wiki) may also be useful, e.g.:

    $ src=path/to/rust/sources
    $ inotifywait -mr -e create,modify,delete \
            --exclude "^.*?[^\.][^r][^s]$" "$src" | while read _ event file; do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] $event on $file. Rebuilding now..." && cargo build
    done
