### ISSUE TITLE
"Spurious network error" when building on GitHub Actions with Nightly 2021-09-18

### ISSUE THREAD

**Issue by lambda-fairy** [rust-lang/cargo#9919]
**Problem**

On my GitHub Actions build, one of the jobs (`cd doctest && cargo test`) fails with the following:

```
    Updating crates.io index
 Downloading crates ...
  Downloaded actix-codec v0.3.0
  Downloaded hyper v0.10.16
  Downloaded hashbrown v0.11.2
  Downloaded aes v0.6.0
  Downloaded mac v0.1.1
  Downloaded version_check v0.1.5
  Downloaded idna v0.2.3
  Downloaded atty v0.2.14
warning: spurious network error (2 tries remaining): [18] Transferred a partial file (transfer closed with 4382 bytes remaining to read)
warning: spurious network error (2 tries remaining): [18] Transferred a partial file (transfer closed with 4586 bytes remaining to read)
  Downloaded atomic-waker v1.0.0
  Downloaded async-task v4.0.3
  Downloaded async-global-executor v2.0.2
  Downloaded adler32 v1.2.0
  Downloaded kv-log-macro v1.0.7
warning: spurious network error (2 tries remaining): [18] Transferred a partial file (transfer closed with 97406 bytes remaining to read)
warning: spurious network error (2 tries remaining): [18] Transferred a partial file (transfer closed with 11302 bytes remaining to read)
  Downloaded arrayvec v0.5.2
warning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `ascii v1.0.0` failed to transfer more than 10 bytes in 30s)
warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `arrayref v0.3.6` within 30s)
warning: spurious network error (2 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 201 was not closed cleanly before end of the underlying stream)
warning: spurious network error (2 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 147 was not closed cleanly before end of the underlying stream)
... many more similar errors ...
```

https://github.com/lambda-fairy/maud/runs/3639098684?check_suite_focus=true

This is a daily build, and only started failing today.

**Steps**
1. Trigger a CI build on https://github.com/lambda-fairy/maud (e.g. by opening a pull request)
2. Wait for the "Examples" job to complete

**Possible Solution(s)**
I notice a curl update landed yesterday (#9917). Could that be related?

**Notes**

Output of `cargo version`: `cargo 1.57.0-nightly (33ee5f82e 2021-09-17)`

- If I [downgrade to `nightly-2021-09-16`](https://github.com/lambda-fairy/maud/pull/293/commits/48286eb26fc9a4c3ad31982dcb13f1de882101da), then the build works again.
- If I set [`CARGO_HTTP_MULTIPLEXING=false`](https://github.com/lambda-fairy/maud/commit/41d17939b6d41cfa99505b9c99a7fdc70d9c2536), it also works.
- I cannot reproduce this issue in another environment (macOS laptop, Linux workstation). Nor does this issue appear in other jobs – only the "Examples" one.
- This is not a duplicate of #9913, as this failure is in downloading dependencies, not cloning the index.

**Comment by lambda-fairy** [comment]
Ooh, I've just reproduced this on my Arch Linux laptop. Using `cargo 1.57.0-nightly (33ee5f82e 2021-09-17)` as well. So it's not just the GitHub Actions runner.

**Comment by Emilgardis** [comment]
I'm seeing the same thing. https://github.com/Emilgardis/twitch_oauth2/runs/3639858168#step:6:234

**Comment by Emilgardis** [comment]
This could be the bump in curl-sys to curl 0.79. e.g this

https://github.com/curl/curl/issues/7730#issuecomment-920687382

**Comment by Emilgardis** [comment]
cc rust-lang/rust#88956
