### ISSUE TITLE
Cargo Contributor Guide Section 3.1 'Commit as you go' Link is broken

### ISSUE THREAD

**Issue by ytmimi** [rust-lang/cargo#9924]
**Problem**

The [Commit as you go](https://dont-be-afraid-to-commit.readthedocs.io/en/latest/git/commandlinegit.html) link in the  [Making a Change](https://doc.crates.io/contrib/process/working-on-cargo.html#making-a-change) Section (3.1) of the Contributor Guide links to a 404 page on readthedocs.io

**Comment by ehuss** [comment]
Thanks for the heads up!  I have opened #9928 to just remove it.

**Comment by ehuss** [comment]
Closed via #9928.
