### ISSUE TITLE
.crates2.json & .crates.toml file's directory

### ISSUE THREAD

**Issue by esdnm** [rust-lang/cargo#9940]
I used cargo to install xsv.

```
cargo install xsv
```

After a few lookup i found that cargo stores some metadata in `.crates2.json` & `.crates.toml`. I looked for those files and found them in `$HOME`.

Is `$HOME` the right directory for them? I thought they will be stored in `$CARGO_HOME`.

Output of `cargo version`: 1.51.0

**Comment by ehuss** [comment]
The default should be `$CARGO_HOME`.  There are several overrides, so maybe check that any of them are not set?  They are described at https://doc.rust-lang.org/cargo/commands/cargo-install.html

**Comment by esdnm** [comment]
I wanted cargo to store binaries in `~/bin` and to do that i set `install.root` to my home directory.

As ` .crates2.json` & `.crates.toml` are stored in home directory this tells cargo store them in `install.root`.

But I don't see any statements on this files and where they will be stored in https://doc.rust-lang.org/cargo/commands/cargo-install.html

**Comment by ehuss** [comment]
Yea, that could definitely be made clearer.  There is a brief mention in [`--no-track`](https://doc.rust-lang.org/cargo/commands/cargo-install.html#option-cargo-install---no-track), but that is pretty obscure.
