### ISSUE TITLE
`cargo test --no-run`  should print the resulting binary name

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#9957]
Problem:

I am profiling my Rust application, so I want to compile the tests with `--no-run` and run the binary directly. However, the output doesn't say where the result is:

```console
$ cargo test --no-run --release --package runtime-tester --features nearcore/no_cache --lib -- perf_cliff --exact --nocapture
   Compiling runtime-tester v0.1.0 (/home/matklad/projects/nearcore/test-utils/runtime-tester)
    Finished release [optimized] target(s) in 5.49s
$
```

I have to manually `ls traget/release/deps` to get the file name

Proposed solution:

The name is convenientl printed when you don't pass no-run:

```console
$ cargo test --release --package runtime-tester --features nearcore/no_cache --lib -- perf_cliff --exact --nocapture
    Finished release [optimized] target(s) in 0.13s
     Running unittests (target/release/deps/runtime_tester-160c2544f9ae8411)
```

Would be great to add a message similar to `Running target (path)` to `--no-run` output.

**Comment by ehuss** [comment]
Hm, yea, as you probably know the usual intended use-case is to use `--no-run` with JSON.  I think it probably would be reasonable to display the executables generated with `--no-run`.  I wouldn't use the status `Running` since it isn't actually running it, though I'm not sure what to say.  Generated? Built? Executable? Those don't sound great to me, but maybe something like that.

In the meantime, one workaround is to use `jq`:

```sh
cargo test --no-run --message-format=json | jq 'select(.reason=="compiler-artifact") | .executable'
```

**Comment by matklad** [comment]
> the usual intended use-case is to use --no-run with JSON. 

I think no-run actually predates JSON support, so I imagine original use-case was different
 Perhaps 

    Compiled unittests (target/release/deps/runtime_tester-160c2544f9ae8411)

?

Would also be cool to put the tests into a better location that deps, but target directory layout is a whole different yak

**Comment by vrongmeal** [comment]
I guess we might also want to do the same for `cargo build` ?

Anyways, I would like to work on this, if possible.

**Comment by ehuss** [comment]
> I think no-run actually predates JSON support, so I imagine original use-case was different.

Ah, indeed.  Perhaps Alex just used `*` to glob on the filename hash.

@vrongmeal Sure!  I would start off being a little conservative and just add a message when `--no-run` is used with test or bench.  Let me know if you have any questions.

**Comment by vrongmeal** [comment]
@ehuss I just submitted a draft PR for now: #9959
