### ISSUE TITLE
`cargo report future-incompatibilities` doesn't check for color support correctly

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#9960]
**Problem**
`cargo report future-incompatibilities` does not check for color support correctly.  If you pipe the output to a file or something like `less`, it is not stripping the colors. This wasn't quite the intended behavior in #9606.  The issue is [here](https://github.com/rust-lang/cargo/blame/a821e2cb24d7b6013433f069ab3bad53d160e100/src/cargo/core/compiler/future_incompat.rs#L189) where it only checks if stderr supports color.

**Steps**
1. `cargo report future-incompatibilities > some_file`

Notice that `some_file` contains lots of escape characters

**Possible Solution(s)**

I'm not entirely sure of the best approach to fix this.  Perhaps just check if both stdout and stderr support color at the line noted above?  I can't imagine a scenario where that would matter.  I'd be reluctant to make this too fussy or complicated, though worst case the check to call `strip_ansi_escapes::strip` could be moved to the callers, but I think I'd rather avoid that.

**Notes**

Output of `cargo version`:

cargo 1.57.0-nightly (d56b42c54 2021-09-27)

**Comment by dswij** [comment]
I might be missing something here, but since `cargo report future-incompatibilities` command prints to stdout, what's the reason behind checking stderr only?

**Comment by ehuss** [comment]
That code is shared for two different places.  When displaying as part of a regular build ([here](https://github.com/rust-lang/cargo/blob/4a166de89ffb78c8206da22e50f4b5b4ce53fb6a/src/cargo/core/compiler/job_queue.rs#L938)) it is sent to stderr (since all build errors/warnings go to stderr).  When displayed as part of the `cargo report` subcommand, it is displayed to stdout as it is intended to be a human-readable text report, and it seemed more natural to send that to stdout (and more convenient to pipe the output).

**Comment by ehuss** [comment]
@dswij Just checking if you've had a chance to look at this, or had any questions.

**Comment by dswij** [comment]
I've had a look, but got distracted along the way. I'll continue working on it once I have the chance to.
