### ISSUE TITLE
Cargo can't set rpath into library or binary

### ISSUE THREAD

**Issue by ruisv** [rust-lang/cargo#9966]
build.rs

println!("cargo:rustc-link-arg=-Wl,-rpath={}", &libdir);

I set rpath in this way but it didn't take effect.
How  to set rpath into library or binary?

Thank you for your reply.

**Comment by ehuss** [comment]
Closing as there doesn't appear to be enough information here to move this forward. If the questions above could be answered, preferably with a full reproduction and set of steps, feel free to re-open.
