### ISSUE TITLE
Way for dependencies to read configuration from dependents/access dependent's manifest directory

### ISSUE THREAD

**Issue by kepexx** [rust-lang/cargo#9977]
### Problem

I was working on a project and I needed a way for my crate to be able to be customized based on a configuration file from the dependent, via `build.rs`. The configuration would be to add extra fields to structs, as they will be present in actual builds due to a custom build system (which also reads from those config files and adds the fields). This is for the sake of IDEs properly error reporting.

### Proposed Solution

The build script is given an environment variable such as `CARGO_DEPENDENT`, which contains the dependent crates' manifests' paths separated by commas.

### Notes

If this isn't practical, is there any other way to achieve the specific use case I'm trying to do here?

**Comment by epage** [comment]
As this inverts the relationship of dependency / dependent, I propose we close this.

For controlling the behavior of dependencies, we have
- `--cfg`
- `[features]`

We also have a proposal for [global, mutually exclusive features](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618).

**Comment by weihanglo** [comment]
Second. See also <https://github.com/rust-lang/cargo/issues/13484>.
