### ISSUE TITLE
Configure cargo to ignore rustup

### ISSUE THREAD

**Issue by jonnius** [rust-lang/cargo#9993]
### Problem

As described [here](https://gitlab.com/clickable/clickable/-/issues/294) we have a scenario where cargo runs inside a container that has the rust toolchain installed. When defaulting to `stable` or `nightly` a `rustup update` seems to be triggered on running `cargo build`. The rust toolchain update does not make sense in that situation though, because the container is only temporary.

### Proposed Solution

I would like to have a flag/env var to disable the automatic rust toolchain update and have cargo just use the already installed rust toolchain.

**Comment by Eh2406** [comment]
Rustup provides a wrapper around Cargo, that looks in your Rustup configuration to decide witch toolchains' Cargo to invoke. I bet that if you run `which cargo` it will point to the wrapper program provided by Rustup. Or you can try `cargo +stable` as the `+stable` argument is added by the wrapper, If you are invoking Cargo directly it will complain about an unknown argument.
