### ISSUE TITLE
Cargo failed to select a version for dependencies, but problem is fixed when state is reset

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-lang/cargo#9994]
### Problem

Users use an old version of a library in one project, then create a new project with the updated version of our library.

The new project has dependency conflicts, reporting "failed to select a version for DEPENDENCY".

[Bevy](https://github.com/bevyengine/bevy) users report this problem on a near daily basis, but I can't reproduce it locally.

The workaround is to use `cargo clean`, `cargo update` and delete `Cargo.lock`, which invariably resolves the issue.

### Steps

I have not been able to reproduce this from a clean slate.

### Possible Solution(s)

Automatically check for stale dependencies in some fashion.

Failing that, supply an error message suggesting the workaround given.

### Version

```text
cargo 1.53.0-nightly (f3e13226d 2021-04-30)
release: 1.53.0
commit-hash: f3e13226d6d17a2bc5f325303494b43a45f53b7f
commit-date: 2021-04-30
```

**Comment by ehuss** [comment]
Thanks for digging into a reproduction!  I think this is almost certainly the same as #9240.  When switching from a crates.io dep to a git dep, and the git dep has new dependency requirements, the dependencies in `Cargo.lock` remain locked, and cargo is not unlocking them when it should.

**Comment by timstr** [comment]
Seeing this also for `web-sys`, also after switching one crate from a cargo version to a git URL.

```
error: failed to select a version for `web-sys`.
    ... required by package `eframe v0.28.1 (https://github.com/timstr/egui?rev=df6fa145#df6fa145)`
    ... which satisfies git dependency `eframe` of package `flosion v0.1.0 (/home/tim/dev/rust/flosion-rs)`
versions that meet the requirements `^0.3.70` are: 0.3.70

all possible versions conflict with previously selected packages.

  previously selected package `web-sys v0.3.69`
    ... which satisfies dependency `web-sys = "^0.3.35"` (locked to 0.3.69) of package `cpal v0.13.5`
    ... which satisfies dependency `cpal = "^0.13.3"` (locked to 0.13.5) of package `flosion v0.1.0 (/home/tim/dev/rust/flosion-rs)`

failed to select a version for `web-sys` which could resolve this conflict
```
