### ISSUE TITLE
Allow use of new behaviour for `--no-default-features` and `--features` without changing resolver

### ISSUE THREAD

**Issue by philipc** [rust-lang/cargo#9997]
### Problem

I would like the command line options `--no-default-features` and `--features` to apply to all members of the workspace. Currently, this only appears to work for `resolver = "2"`. However, I am unable to change the resolver due to MSRV restrictions.

This problem is occurring for the [`object`](https://github.com/gimli-rs/object) crate. The `object` crate is the root of the workspace, and `object-examples` is another member. With `resolver = "2"` I get:
```
$ cargo tree --no-default-features --features read_core -e features -i object-examples
object-examples v0.0.0 (/home/philipc/code/rust/object/crates/examples)
```
and with `resolver = "1"` I get:
```
$ cargo tree --no-default-features --features read_core -e features -i object-examples
object-examples v0.0.0 (/home/philipc/code/rust/object/crates/examples)
├── object-examples feature "default" (command-line)
└── object-examples feature "read"
    └── object-examples feature "default" (command-line)
```
As shown, `--no-default-features` is not applied to `object-examples`.

Alternatively, if I change the default features of `object_examples` to `[]`, then I would like the following to also enable `object-examples/read` but it does not:
```
$ cargo tree --features read -e features -i object-examples
object-examples v0.0.0 (/home/philipc/code/rust/object/crates/examples)
└── object-examples feature "default" (command-line)
```

### Proposed Solution

I don't have any great ideas for how this might be solved. The only possibility I can think of is adding a new workspace setting in `Cargo.toml`, but I expect that's not very palatable, and this is a problem that will eventually disappear when the MSRV is increased.

**Comment by ehuss** [comment]
Yea, I don't think we are likely to add another flag to opt-in to this behavior.  Hopefully the wait to make 1.51 your minimum version won't be too bothersome.
